### ISSUE TITLE
[License info] Longformer SQuAD finetuned model

### ISSUE THREAD

**Issue by guillaume-be** [huggingface/transformers#10005]
Hello @patil-suraj ,

would it be possible to provide licensing information for the pretrained model weights shared at:
https://huggingface.co/valhalla/longformer-base-4096-finetuned-squadv1

I would be interested in offering a Rust implementation for this model, but would like to know under which license this model was shared so that I can document my codebase accordingly.

Thank you!

**Comment by patil-suraj** [comment]
Hey @guillaume-be, glad to know that you are offering Rust implementation of this model :)

There's no license currently, but I'll add MIT license to this model.

**Comment by guillaume-be** [comment]
Hello @patil-suraj ,
Could you please share an update on this issue? 
Thank you!

**Comment by patil-suraj** [comment]
Hi @guillaume-be 
I just added an MIT license  https://huggingface.co/valhalla/longformer-base-4096-finetuned-squadv1/blob/main/LICENSE

**Comment by julien-c** [comment]
@patil-suraj also referenced it from your model card's YAML: https://huggingface.co/valhalla/longformer-base-4096-finetuned-squadv1/commit/1ad74ed17896eb4d3a314b1acedefbfc184cc582

**Comment by patil-suraj** [comment]
Thanks Julien !

**Comment by guillaume-be** [comment]
This is great thank you!
