### ISSUE TITLE
Why two separators?

### ISSUE THREAD

**Issue by ZJaume** [huggingface/transformers#10009]
I want to fine-tune the model in Keras with my own dataset and I'm trying to figure out the format of the input sentences. When I take a look at `input_ids` I can see two sentence separators (`</s>` which has id 2) between each sentence after tokenization. Is this the expected behaviour? In that case, why are two separators needed? Will I get the same performance if I use one?

## Environment info

- `transformers` version: `4.2.2`
- Platform: Ubuntu 18.04
- Python version: `3.7.5`
- PyTorch version (GPU?):
- Tensorflow version (GPU): `2.3.1`
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Nope

## Information

Model I am using (TFRoberta, TFXLMRoberta...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: https://huggingface.co/transformers/training.html#fine-tuning-in-native-tensorflow-2
* [x] my own task or dataset: 

## To reproduce

```python
from transformers import RobertaTokenizer, glue_convert_examples_to_features
import tensorflow_datasets as tfds
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
data = tfds.load('glue/mrpc')
train_dataset = glue_convert_examples_to_features(data['train'].take(4), tokenizer, max_length=128, task='mrpc')
list(train_dataset.as_numpy_iterator())
```
```
Out[48]:
[({'input_ids': array([    0,   133, 14085,  4533,  3697,    40,  1760,    25, 20701,
           5473, 10974,  2156,  6062,    13,  1283,     9,   375,   514,
            479,     2,     2,   133,  4533,  3697,  1760,    25, 20701,
           5473, 10974,  2156,  1375,    15,   411, 10562,   479,     2,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1,     1,     1,     1,     1,     1,     1,     1,
              1,     1], dtype=int32),
   'attention_mask': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)},
  0),
 ...
  ```

**Comment by LysandreJik** [comment]
Good question! That's how the original `roberta-base` model was pretrained. I recommend you stick to the way the model was pretrained in order to obtain best performance.

You can find the [roberta paper here](https://arxiv.org/pdf/1907.11692.pdf). I believe the section 4.2 contains information regarding model inputs.

**Comment by ZJaume** [comment]
Alright, thanks!
