### ISSUE TITLE
Tokenizer Batch decoding  of predictions obtained from model.generate in t5

### ISSUE THREAD

**Issue by rohanshingade** [huggingface/transformers#10019]
How to do batch decoding of sequences obtained from model.generate in t5? Is there a function available for batch decoding in tokenizer `tokenizer.batch_decode_plus` similar to batch enocding `tokenizer.batch_encode_plus`?

**Comment by LysandreJik** [comment]
There is `batch_decode`, yes, the docs are [here](https://huggingface.co/transformers/internal/tokenization_utils.html?highlight=batch_decode#transformers.tokenization_utils_base.PreTrainedTokenizerBase.batch_decode).

@sgugger I wonder if we shouldn't make the docs of this method more prominent? The "Utilities for tokenizer" page mentions: "Most of those are only useful if you are studying the code of the tokenizers in the library.", but `batch_decode` and `decode` are only found here, and are very important methods of the tokenization pipeline.

**Comment by sgugger** [comment]
We should add them to the `PreTrainedTokenizer` and `PreTrainedTokenizerFast` documentation. Or did you want to add them to all models?

**Comment by rohanshingade** [comment]
@LysandreJik `tokenizer.batch_decode` and tokenizer.decode` in loop, both the functions take almost the same time. can you suggest something, how can I speed up the decoding in T5? why is batch_decode not as fast as batch_encode_plus? Is there a way to make decoding even faster?

**Comment by LysandreJik** [comment]
Unfortunately we have no way to go faster than that.

**Comment by sadransh** [comment]
@LysandreJik this function is used in compute_metrics. and it seems it is limited to the number of GPUs ( it uses the same number of `--nproc_per_node` when doing ddp training, how is it possible to extend that to the maximum number of cores) any guide on how to fix and maybe do a PR?
