### ISSUE TITLE
[Question] Pipeline QA start_index

### ISSUE THREAD

**Issue by ahnz7** [huggingface/transformers#10013]
I got a dictionary with 'score', 'start', 'end' and 'answer'. I want to use the 'start' and 'end' index. But the index of 'start' and 'end' are usually greater than length of encoding? Code:
text = text
question = quesiton
pipeline = pipeline('question-answering' , model = model)
answers = pipeline(context = data, question = questions)
print(answers)
{'score': 0.7909670472145081, 'start': 6192, 'end': 6195, 'answer': '111'}
but the length of context + question is smaller than 6000. How can I use 'start_index' and 'end_index' to verify that the result is '111'?

**Comment by LysandreJik** [comment]
Hi! So that we may help you, could  you provide the information related to your environment as asked in the issue template?

Also, we can't understand what's happening here because we don't know what's your text, your question, and most importantly the model you used.

Finally, you instantiated a model, but you didn't do so for the tokenizer. If you have mismatched models/tokenizers, then outputs are bound to be confusing.

**Comment by ahnz7** [comment]
> Hi! So that we may help you, could you provide the information related to your environment as asked in the issue template?
> 
> Also, we can't understand what's happening here because we don't know what's your text, your question, and most importantly the model you used.
> 
> Finally, you instantiated a model, but you didn't do so for the tokenizer. If you have mismatched models/tokenizers, then outputs are bound to be confusing.

Oh,sorry. My enviroonment is as follows:
OS: Macos catalina
python version: python3.7.3
Package Version: transformers 3.4 
The model, which I have used, is 'ktrapeznikov/biobert_v1.1_pubmed_squad_v2'. And the code is like following:
data ='I live in Berkeley. I am 30 years old. And my name is Clara.'
question = 'What's my name?'
pipeline = pipeline('question-answering',model = 'ktrapeznikov/biobert_v1.1_pubmed_squad_v2')
answers = pipeline(context = data, question = question)
# answer is like {'score': 0.9977871179580688, 'start': 54, 'end': 59, 'answer': 'Clara.'}

#instantiate a tokenizer
tokenizer = AutoTokenizer.from_pretrained('ktrapeznikov/biobert_v1.1_pubmed_squad_v2')
encoding = tokenizer.encode(questions,data)

# length of encoding is 26
len(encoding)

But from the answer I got start index as 54 and end index as 59?

**Comment by LysandreJik** [comment]
Yes, the length of encoding is the length of the list of tokens. The start and end index are the start and end index of characters, not tokens. We should clarify that in the docs.

**Comment by ahnz7** [comment]
> Yes, the length of encoding is the length of the list of tokens. The start and end index are the start and end index of characters, not tokens. We should clarify that in the docs.

okay, thats what i mean. Thx
