### ISSUE TITLE
Override Default Params on QnA Pipeline

### ISSUE THREAD

**Issue by mabu-dev** [huggingface/transformers#10029]
How should we override the default params of QnA Model in Pipelines?

I tried the below but it throws an error?!

![image](https://user-images.githubusercontent.com/22409996/107048748-f586a580-67d1-11eb-88fe-f78901d99734.png)

**Comment by NielsRogge** [comment]
For the documentation of the `__call__` method of `QuestionAnsweringPipeline`, see [here](https://huggingface.co/transformers/main_classes/pipelines.html#transformers.QuestionAnsweringPipeline.__call__).

**Comment by mabu-dev** [comment]
This solved my issue. Thank you very much.
