### ISSUE TITLE
Cannot import DataCollatorForSeq2Seq from Transformers library

### ISSUE THREAD

**Issue by Arman-IMRSV** [huggingface/transformers#10035]
## Environment info

- `transformers` version: 4.2.2
- Platform: Ubuntu
- Python version: 3.7
- PyTorch version (GPU?):
- Tensorflow version (GPU?): 1.7.1 - GPU : T4
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?:

### Who can help
@patil-suraj 
@sgugger 

## Information

Model I am using (Bert, XLNet ...): mT5

The problem arises when using:
* [ ] the official example scripts: run_seq2seq.py

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: Translation
* [ ] my own task or dataset: My own json dataset

## To reproduce

```
python run_seq2seq.py \
    --model_name_or_path google/mt5-small \
    --do_train \
    --do_eval \
    --task translation_en_to_fa \
    --train_file Persian/seq2seq_train.json \
    --validation_file Persian/seq2seq_val.json \
    --output_dir translation_task_output \
    --overwrite_output_dir \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --predict_with_generate \
    --text_column text_column_name \
    --max_source_length 64 \
    --max_target_length 64 \
    --max_train_samples 10240 \
    --max_val_samples 512 \
    --source_lang en \
    --target_lang fa \
    --eval_beams 1 \
    --source_prefix "translate English to Persian: "
```

## Error:
```
File "run_seq2seq.py", line 31, in <module>
    from transformers import (
ImportError: cannot import name 'DataCollatorForSeq2Seq' from 'transformers' (unknown location)

```

**Comment by patil-suraj** [comment]
Could you try running this on master ? I just ran this script on master and it's working fine.

**Comment by sgugger** [comment]
As mentioned in the README of the [examples folder](https://github.com/huggingface/transformers/tree/master/examples#important-note), all examples require a [source install](https://huggingface.co/transformers/installation.html#installing-from-source).

`DataCollatorForSeq2Seq` is not in the last release, it was introduced since then.

**Comment by Arman-IMRSV** [comment]
@sgugger @patil-suraj Thanks :)
