### ISSUE TITLE
Can't GPT-2 set special_tokens? (or unk tokens)

### ISSUE THREAD

**Issue by jeonggwanlee** [huggingface/transformers#1003]
## ❓ Questions & Help

In GPT, we can set special tokens. (I also did it branch 0.6.2)
https://github.com/huggingface/pytorch-transformers/blob/v1.0.0/pytorch_transformers/modeling_openai.py

But, in GPT-2, It seems like no way to add special tokens.
https://github.com/huggingface/pytorch-transformers/blob/b33a385091de604afb566155ec03329b84c96926/pytorch_transformers/modeling_gpt2.py#L619

I also saw #994. They said it's impossible. 
It it true? and do you have any plan to add it?

**Comment by jeonggwanlee** [comment]
I also saw #468. It will be probably added soon.
But, If someone informs new information about this, I'll thank for that.

**Comment by aburkard** [comment]
Passing them like so works for me:

`GPT2Tokenizer.from_pretrained(args.model_name, unk_token="<|endoftext|>")`

**Comment by jeonggwanlee** [comment]
@aburkard  Thank you so much!!!!

**Comment by LysandreJik** [comment]
Hi, in GPT-2 there wasn't the option at first but we've added it down the line. It is available if you compile this repo from source from the master branch, or you can wait for the version 1.1 which should drop sometimes this week. In this version you're able to add special tokens to GPT-2.

**Comment by thomwolf** [comment]
Release 1.1.0 is here :-)
