### ISSUE TITLE
AttributeError: module 'transformers' has no attribute 'PegasusForCausalLM'

### ISSUE THREAD

**Issue by ibrahim-elsawy** [huggingface/transformers#10031]
## Environment info

- `transformers` version: 4.2.2
- Platform: Linux-5.8.0-40-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help
@sgugger @patil-suraj 
Models:
-tuner007/pegasus_paraphrase

## Information

trying to import "PegasusForCausalLM" from transformers and I got AttributeError: module 'transformers' has no attribute 'PegasusForCausalLM'

## To reproduce

```python

from transformers import PegasusForCausalLM, AutoConfig
model_name = "tuner007/pegasus_paraphrase"
output_logits = True
output_hidden_states = True
p_config =AutoConfig.from_pretrained(
            model_name,
            output_hidden_states=output_hidden_states,
            output_logits=output_logits)
pegasus = PegasusForCausalLM.from_pretrained(model_name, config=p_config)


```
```
AttributeError: module transformers has no attribute PegasusForCausalLM
```

**Comment by sgugger** [comment]
Yes, this model was only added recently, it's not in v4.2.1 (check the [documentation](https://huggingface.co/transformers/model_doc/pegasus.html)). 
You need to install the pre-release:
```
pip install transformers --pre
```
or [install from source](https://huggingface.co/transformers/installation.html#installing-from-source) to use it.
