### ISSUE TITLE
Error: "Transformers CLI tool: error: unrecognized arguments: kvantorium-small"  while deploying machine learning model to hugging face profile

### ISSUE THREAD

**Issue by IndianMLGay** [huggingface/transformers#10054]
I work with hugging face on Google Colab
My process of training and tuning the model looks like this. The model is successfully trained and saved in the models folder, but when I am going to upload it to my huggingface repository, an error occurs

````
tokenizer = `PreTrainedTokenizerFast(tokenizer_file='/content/bert-datas7.json')
tokenizer.add_special_tokens({'pad_token': '[PAD]'})

dataset = LineByLineTextDataset(tokenizer=tokenizer, file_path="/content/For_ITMO (1).txt",block_size=128)

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer, mlm=mlm, mlm_probability=0.15
    )
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="models/kvantorium-small",
    overwrite_output_dir=True,
    num_train_epochs=1000,
    per_gpu_train_batch_size=64,
    save_steps=10_000,
    save_total_limit=2,
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=dataset)

trainer.train()
```` 
#8480 
When I am going to upload it to my huggingface repository, an error occurs, why is it displayed for me? And how to specify the correct documentation? My folder in the Google Colab directory is called "/ content / models / kvantorium-small" This is the folder where I save the model after training

````
!transformers-cli login
!transformers-cli upload  "/content/models/kvantorium-small"



2021-02-07 16:56:32.089450: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
usage: transformers-cli <command> [<args>]
Transformers CLI tool: error: unrecognized arguments: /content/models/kvantorium-small
````
Is this a google collab problem and how can I rewrite the request or fix the error?

Sorry in advance if my issue seems to be incorrect to you, I'm new to git. 
I also attached my data and my tokenizer file
[For_ITMO (1).txt](https://github.com/huggingface/transformers/files/5939713/For_ITMO.1.txt)

[For_ITMO.txt-vocab (1) (1).txt](https://github.com/huggingface/transformers/files/5939719/For_ITMO.txt-vocab.1.1.txt)

**Comment by LysandreJik** [comment]
Hello! Since version v4.0.0, we recommend using git and git-lfs to upload your models. Could you take a look at the following documentation page: [Model sharing and uploading](https://huggingface.co/transformers/model_sharing.html) and try what is shown in that document? Thank you!

**Comment by IndianMLGay** [comment]
> Hello! Since version v4.0.0, we recommend using git and git-lfs to upload your models. Could you take a look at the following documentation page: [Model sharing and uploading](https://huggingface.co/transformers/model_sharing.html) and try what is shown in that document? Thank you!

@LysandreJik  That is, I first need to connect github to my google colab and only then upload my model files to the hugging face? Thank you very much in advance

**Comment by LysandreJik** [comment]
No, you'll only need a huggingface hub account to upload to it.

**Comment by IndianMLGay** [comment]
@LysandreJik Error Again
````
!transformers-cli upload https://huggingface.co/Fidlobabovic/your-model-name

````

**Comment by LysandreJik** [comment]
Hi @IndianMLGay. I'm sorry but I don't understand what is the issue. Nowhere in the file I linked is there a `transformers-cli upload` command.
