### ISSUE TITLE
model.generate needs BART config update

### ISSUE THREAD

**Issue by swethmandava** [huggingface/transformers#10083]
### Who can help
@patrickvonplaten @patil-suraj 

```
model = BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn')

tokenizer = BartTokenizer.from_pretrained('facebook/bart-large-cnn')

ARTICLE_TO_SUMMARIZE = "My friends are cool but they eat too many carbs."
inputs = tokenizer([ARTICLE_TO_SUMMARIZE], max_length=1024, return_tensors='pt')

# Generate Summary
summary_ids = model.generate(inputs['input_ids'], num_beams=4, max_length=5, early_stopping=True)
```

model.generate runs into errors. num_beam_groups, return_dict_in_generate and encoder_no_repeat_ngram_size are not defined in BART config. Should they be added?

**Comment by patrickvonplaten** [comment]
Hey @swethmandava,

Sorry I don't understand the issue here - what do you mean by `model.generate` runs into errors? Your above code snippet works fine for me. Could you clarify the issue? Thank you!

**Comment by swethmandava** [comment]
`summary_ids = model.generate(inputs['input_ids'], num_beams=4, max_length=5, early_stopping=True, num_beam_groups=1, output_scores=False, return_dict_in_generate=False, encoder_no_repeat_ngram_size=0, diversity_penalty=0.0)
`

I have to define the following defaults (num_beam_groups, output_scores, return_dict_in_generate, encoder_no_repeat_ngram_size, diversity_penalty) explicitly since they are not in BARTConfig and default to None

**Comment by patil-suraj** [comment]
Hey @swethmandava 

You shouldn't need to define these param. All these config params have default values defined in the `PretrainedConfig` class from which all other configs inherit. 

Could you try again with the newest transformers version?
