### ISSUE TITLE
[question] Are the tensorflow bert weights same as the original repo ?

### ISSUE THREAD

**Issue by Slyne** [huggingface/transformers#10090]
## Environment info

- `transformers` version:
- `transformers` version: 4.2.2
- Platform: Linux-4.15.0-133-generic-x86_64-with-debian-stretch-sid
- Python version: 3.6.8
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.5.0-dev20210204 (True)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: distributed

### Who can help

Models:

- albert, bert, xlm: @LysandreJik

## Information
I'm using the pretrained bert-base-chinese [here](https://huggingface.co/bert-base-chinese). I print out the pooler_output and the result is different from the tensorflow2.0 published hub saved model [here](https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/3).
I want to confirm whether the two checkpoints weights are the same.

## To reproduce

```
from transformers import TFBert
bert = bert = TFBertModel.from_pretrained('bert-base-chinese', output_hidden_states=True)
output = bert(input_ids=tf.convert_to_tensor([[ 101,  791, 1921, 1921, 3698, 2582,  720, 3416,  102]]), 
                   attention_mask=tf.convert_to_tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]]), training=False)
print(output.pooler_output)
```
```
# print the beginning weights:
array([[ 0.99749047,  0.9999622 ,  0.99657625,  0.96953416,  0.8489984 ,
         0.06474952, 
```

The tensorflow hub output can be produced from https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/3.
The input text is "今天天气怎么样"
```
[[ 9.97488916e-01  9.99962687e-01  9.96489942e-01  9.69992220e-01
   8.49602520e-01  6.62192404e-02 ,
```

The tensorflow part claims they use the original bert checkpoints from tf1.X. 
There is no training=True/False option in tensorflow hub so I'm confused if the difference is due to this option? (I've set trainable=False in tensorflow hub)

## Expected behavior
Expect the outputs to be the same.

**Comment by LysandreJik** [comment]
Hi! Could you provide the code you used to get the predictions with the BERT checkpoint on TF Hub? The two should be identical.

**Comment by Slyne** [comment]
> Hi! Could you provide the code you used to get the predictions with the BERT checkpoint on TF Hub? The two should be identical.

I copied from https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/3
```python
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
preprocessor = hub.KerasLayer(
    "https://tfhub.dev/tensorflow/bert_zh_preprocess/3")
encoder_inputs = preprocessor(text_input)
encoder = hub.KerasLayer(
    "https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/3",
    trainable=True)
outputs = encoder(encoder_inputs)
pooled_output = outputs["pooled_output"]      # [batch_size, 768].
sequence_output = outputs["sequence_output"]  # [batch_size, seq_length, 768].
embedding_model = tf.keras.Model(text_input, pooled_output)
sentences = tf.constant(["今天天气怎么样"])
print(embedding_model(sentences))
```

**Comment by Slyne** [comment]
Any update ? @LysandreJik
