### ISSUE TITLE
Pre-Training for Question Generation

### ISSUE THREAD

**Issue by saichandrapandraju** [huggingface/transformers#10093]
Hi,
How to pre-train any of language generation models (T5, BART or GPT ) for Question Generation task where I had passage, question and answer?

**Comment by NielsRogge** [comment]
I guess @patil-suraj is the expert in this, check out his [repo](https://github.com/patil-suraj/question_generation) explaining all the details.

**Comment by saichandrapandraju** [comment]
ok..
@patil-suraj , plz revert on [this](https://github.com/patil-suraj/question_generation/issues/69) issue I raised in your repo
