### ISSUE TITLE
Git does not find the model folder and does not commit model files in the hugging face

### ISSUE THREAD

**Issue by IndianMLGay** [huggingface/transformers#10109]
I work for Google Colab. This is how I save my training model files
````
trainer.save_model("./kvantorium-small")
tokenizer.save_pretrained("/content/For_tokenize", legacy_format=False)
````

Next, I want to commit my files to the hugging face repository. As shown in the guide (https://huggingface.co/welcome)

all these lines of code compile successfully:

````
!sudo apt-get install git-lfs
!pip install huggingface_hub
!huggingface-cli login
!huggingface-cli repo create simple-small-kvantorium

!git lfs install
!git clone https://huggingface.co/Fidlobabovic/simple-small-kvantorium
````
But when I want to make a push request to save files to the repository, I get an error that there is no such repository. How do I rewrite the request to publish the files to the repository? Is this a problem that I work for Google Colab? Thanks a lot in advance, you are helping me a lot

#9878 

````
!git add .
!git commit -m "commit from $Fidlobabovic/simple-small-kvantorium"
!git push

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
````

**Comment by patil-suraj** [comment]
hi @IndianMLGay 

You should `cd` into `simple-small-kvantorium` directory and then do `git add/commit/push` etc
