### ISSUE TITLE
Exporting transformers models in ONNX format

### ISSUE THREAD

**Issue by chetanambi** [huggingface/transformers#10118]
I am trying to convert transformer model to ONNX by referring the article **[here](https://huggingface.co/transformers/serialization.html)** but running into below error. Can you please guide me if this is not the correct way of doing it.

Code I am using in Colab:
```
!git clone https://github.com/huggingface/transformers.git
%cd transformers
!pip install .
%cd src/transformers
!python3 convert_graph_to_onnx.py --framework pt --model bert-base-cased bert-base-cased.onnx
```

Traceback (most recent call last):
  File "convert_graph_to_onnx.py", line 22, in <module>
    from .file_utils import ModelOutput, is_tf_available, is_torch_available
ModuleNotFoundError: No module named '__main__.file_utils'; '__main__' is not a package

**Comment by Denovitz** [comment]
Hi!
Try this one, but do it from an empty folder:
`python3 -m transformers.convert_graph_to_onnx --framework pt --model bert-base-cased bert-base-cased.onnx`

**Comment by chetanambi** [comment]
@Denovitz Thanks a lot. I was able to convert the BERT model to ONNX successfully. Do you have a sample code of how the converted ONNX model can be used further for inferences? I am able to use ONNX for TF, Keras, Sklearn, Xgboost and other models but stuck with transformer model. Appreciate any inputs.
