### ISSUE TITLE
Bug in RAG Sequence generate 

### ISSUE THREAD

**Issue by krishanudb** [huggingface/transformers#10111]
IMHO there is a bug in the RAG Sequence model, in the generate function.
The shapes mismatch all the time. I looked into the code and found the issue in the following loop. 

https://github.com/huggingface/transformers/blob/85395e4901f87b880f364bcd6424fe37da94574b/src/transformers/models/rag/modeling_rag.py#L936

Kindly let me know if there is indeed a bug or is it just my code problem.
Thanks.

**Comment by patil-suraj** [comment]
Hi @krishanudb 

Could you post a code snippet so we can reproduce the issue? Please post your env info, short code snippet, and stack trace if possible when reporting bugs. Thanks.
