### ISSUE TITLE
XLM-R tokenizer is none

### ISSUE THREAD

**Issue by aggiejiang** [huggingface/transformers#10127]
## Environment info

- `transformers` version: 4.3.2
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.7.0+cu101 (True)
- Tensorflow version (GPU?): 2.4.1 (True)

### Who can help
@LysandreJik @n1t0

## Information

I am using XLM-R:

The problem arises when using:
* the official example scripts: (give details below)

The tasks I am working on is:
* my own task or dataset: (give details below)

## To reproduce

Steps to reproduce the behaviour:
```
tokenizer = XLMRobertaTokenizer.from_pretrained('xlm-roberta-base')
model = XLMRobertaModel.from_pretrained('xlm-roberta-base')
print(tokenizer, model)
```

## Result

The xlm-r tokenizer is none but the model can be found. 

I am a beginner for this model. Many thanks for your help.

**Comment by LysandreJik** [comment]
Hello! This is weird, it shouldn't happen. Could you try to install `sentencepiece` and let me know if it fixes your issue? Thank you!

**Comment by chandu8542** [comment]
I'm still facing this issue.

![Screenshot from 2021-05-01 16-39-09](https://user-images.githubusercontent.com/12872080/116780709-f7dc6100-aa9b-11eb-93f5-e2ab59f67035.png)

**Comment by LysandreJik** [comment]
Do you have a reproducible colab notebook? Thanks

**Comment by chandu8542** [comment]
Not sure why but it's working today.
![image](https://user-images.githubusercontent.com/12872080/116853234-5d069280-ac13-11eb-8cc9-4fa5098e27f8.png)

**Comment by LysandreJik** [comment]
This is probably because you hadn't restarted your kernel after installing the `sentencepiece` dependency!
