### ISSUE TITLE
Bug in numpy_pad_and_concatenate

### ISSUE THREAD

**Issue by liamcli** [huggingface/transformers#10128]
https://github.com/huggingface/transformers/blob/77b862847b8069d57c0849ca012f48414c427d8e/src/transformers/trainer_pt_utils.py#L71

I believe this should be 
`np.concatenate((array1, array2), axis=0)`

**Comment by sgugger** [comment]
Indeed. Would you like to do a PR to fix this since you spotted the bug?

**Comment by liamcli** [comment]
sure thing!
