### ISSUE TITLE
Where the helsinki models downloaded to? when using the pretrained models

### ISSUE THREAD

**Issue by vishnu3741** [huggingface/transformers#10132]
src_text=['No, los préstamos existentes continuarán por debajo de la tasa de referencia existente.']

model_name='Helsinki-NLP/opus-mt-es-en'
tokenizer=MarianTokenizer.from_pretrained(model_name)
model=MarianMTModel.from_pretrained(model_name)
translated=model.generate(**tokenizer.prepare_seq2seq_batch(src_text, return_tensors="pt"))
tgt_text=[tokenizer.decode(t, skip_special_tokens=True) for t in translated]

when calling the MarianTokenizer and MarianMTModel, the package is automatically downloading the pre_trained model, is there a way to download and integrate it manually from https://huggingface.co/Helsinki-NLP/opus-mt-es-en.

Thank you.

**Comment by patrickvonplaten** [comment]
You can also just clone the repo: 

```
git clone https://huggingface.co/Helsinki-NLP/opus-mt-es-en
```

and then load it locally:

```
model = MarianMTModel.from_pretrained("/path/to/cloned/repo")
tokenizer = MarianTokenizer.from_pretrained("/path/to/cloned/repo")
```

**Comment by vishnu3741** [comment]
OSError: Can't load tokenizer for './model/opus-mt-en-es/'. Make sure that:

- './model/opus-mt-en-es/' is a correct model identifier listed on 'https://huggingface.co/models'

- or './model/opus-mt-en-es/' is the correct path to a directory containing relevant tokenizer files

I am getting this error, even though I am passing the correct path.

**Comment by vishnu3741** [comment]
Thanks, it is working.
