### ISSUE TITLE
cant install from source

### ISSUE THREAD

**Issue by prathameshk** [huggingface/transformers#10134]
## Environment info
transformers-cli env

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 3.3.1
- Platform: Linux-4.19.0-13-cloud-amd64-x86_64-with-debian-10.7
- Python version: 3.7.8
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

## To reproduce
pip install git+https://github.com/huggingface/transformers

Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-BEpAl9
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-BEpAl9/setup.py", line 192
        entries = "\n".join([f'    "{k}": "{v}",' for k, v in deps.items()])
                                                ^
    SyntaxError: invalid syntax

**Comment by mariosasko** [comment]
Hi,

maybe `pip` is not connected to a proper Python version (f-strings work in >= 3.6). To make sure that the right version gets called, you can execute the following command:
```
python -m pip install git+https://github.com/huggingface/transformers
```

This is why it's a good idea to use a virtual env.

Let me know if this helps.

**Comment by prathameshk** [comment]
this was issue with the wrong pip version
