### ISSUE TITLE
Trainer Evaluates at every step

### ISSUE THREAD

**Issue by Megh-Thakkar** [huggingface/transformers#10131]
Hi, thanks for the amazing and easy to use library. While using the Trainer with Training Arguments, the trainer is evaluating at every step, instead of eval_steps.
Version: 4.3.0
```python
training_args = TrainingArguments(output_dir='outputs', per_device_train_batch_size=1,per_device_eval_batch_size=2,
                                        evaluation_strategy='steps', do_eval=True,do_train=True, eval_steps=6)
```
Am I passing any wrong combination of arguments? None of the training_args are getting manually changed at any place in the code.

Thank you very much.

**Comment by sgugger** [comment]
It's hard to know without seeing your code. This combination of arguments should evaluate every 6 steps.
Also how do you know it's evaluation every step instead of every 6 steps?

**Comment by Megh-Thakkar** [comment]
Hi, thank you for the reply. I have actually overridden the 'evaluate' function of the trainer, and have certain print statements inside the function plus a tqdm progress bar as well. This function is executed after every training step.
