### ISSUE TITLE
T5 Base length of Tokenizer not equal config vocab_size 

### ISSUE THREAD

**Issue by ari9dam** [huggingface/transformers#10144]
## Environment info

- `transformers` version: Installed from git

## Issue
The `len(AutoTokenizer.from_pretrained("t5-base"))` is `32100` but the `T5ForConditionalGeneration.from_pretrained("t5-base").config.vocab_size`  is `32128`. Seems to be a similar issue to that of : https://github.com/huggingface/transformers/issues/2020

**Comment by patrickvonplaten** [comment]
duplicate of https://github.com/huggingface/transformers/issues/4875 I think
