### ISSUE TITLE
Problem with evaluation_strategy

### ISSUE THREAD

**Issue by mtortoli** [huggingface/transformers#10150]
Hi everyone!
I have a problem (i think is a bug but i'm not sure) with the parameter "evaluation_strategy" in TFTrainingArguments.
I created a script for finetuning a transfomers model, based on the example "run_tf_text_classification.py" file.

In "TFTrainingArguments" i put the parameter "evaluation_strategy="epoch"", to see how the eval_loss change after  each epoch.

Unfortunately, the eval_loss is not printed after each epoch, but if a change from "epoch" to "steps", actually the eval_loss is printed after each steps.

**Comment by sgugger** [comment]
`evaluation_strategy` is not an argument fully implemented in `TFTrainer`, it only supports "steps". (The PyTorch counterpart supports all the possibilities.)
To evaluate every epoch, the best is to use the native Keras fit method.

**Comment by mtortoli** [comment]
Thanks a lot!!
