### ISSUE TITLE
inconsistent between class name (Pretrained vs PreTrained)

### ISSUE THREAD

**Issue by boy2000-007man** [huggingface/transformers#1016]
## ❓ Questions & Help

https://github.com/huggingface/pytorch-transformers/blob/1b35d05d4b3c121a9740544aa6f884f1039780b1/pytorch_transformers/__init__.py#L37

I notice there are `Pre**t**rainedConfig`, `Pre**T**rainedModel` and `Pre**T**rainedTokenizer` have different naming case which is confusing.

Is this naming style expected? Or just typo?

thx

**Comment by LysandreJik** [comment]
Hi, it isn't really expected and I agree that it can be a bit confusing, but now that it's like that we'll probably keep is so as to not make a breaking change.
