### ISSUE TITLE
`super()` does not have `prepare_seq2seq_batch()`  in `transformers/models/rag/tokenization_rag.py` 

### ISSUE THREAD

**Issue by moyapchen** [huggingface/transformers#10182]
## Environment info

- `transformers` version: 4.3.2
- Platform: Linux-5.4.0-52-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.6.12
- PyTorch version (GPU?): 1.7.1+cu110 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: N/A
- Using distributed or parallel set-up in script?: nope

### Who can help

Models:
- rag: @patrickvonplaten, @lhoestq

## Information

Model I am using (Bert, XLNet ...): RAG

The problem arises when using:
* [ x ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x ] my own task or dataset: (give details below)

## To reproduce

1. Run any of the scripts in the examples on https://huggingface.co/transformers/model_doc/rag.html#overview , ex. 
```
from transformers import RagTokenizer, RagRetriever, RagModel
import torch
tokenizer = RagTokenizer.from_pretrained("facebook/rag-token-base")
retriever = RagRetriever.from_pretrained("facebook/rag-token-base", index_name="exact", use_dummy_dataset=True)
# initialize with RagRetriever to do everything in one forward call
model = RagModel.from_pretrained("facebook/rag-token-base", retriever=retriever)
input_dict = tokenizer.prepare_seq2seq_batch("How many people live in Paris?", "In Paris, there are 10 million people.", return_tensors="pt")
input_ids = input_dict["input_ids"]
outputs = model(input_ids=input_ids)
```

2. Get an error on https://github.com/huggingface/transformers/blob/master/src/transformers/models/rag/tokenization_rag.py#L77 about how `super()` does not have `prepare_seq2seq_batch()` 
   * Indeed, looking at the relevant file, RagTokenizer does not inherit from any other class. 

## Expected behavior

RAG works properly. 

Note that if I copy/paste the code in the file prior to https://github.com/huggingface/transformers/pull/9524 , it works fine. CC: @sgugger of that change.

**Comment by lhoestq** [comment]
Hi ! Thanks for reporting
#10167 should fix this issue

**Comment by moyapchen** [comment]
Convenient to see that the fix was already in the pipeline. Thanks!
