### ISSUE TITLE
Support for DeBERTa V2 models

### ISSUE THREAD

**Issue by saichandrapandraju** [huggingface/transformers#10186]
Hi,

I downloaded [DeBERTa V2-XLarge](https://github.com/microsoft/DeBERTa) from [here](https://huggingface.co/microsoft/deberta-v2-xlarge) and trying to implement V2-XLarge model but I'm getting this error -

**RuntimeError: Error(s) in loading state_dict for DebertaForSequenceClassification:
	size mismatch for deberta.encoder.rel_embeddings.weight: copying a param with shape torch.Size([512, 1536]) from checkpoint, the shape in current model is torch.Size([1024, 1536]).**

I saw that vocab got changed for V2 models. If that is the reason for above issue, is there any workaround to implement V2 models with HF ?

**Comment by LysandreJik** [comment]
Hi, no workaround, we're working on the implementation now (https://github.com/huggingface/transformers/pull/10018). It should be available in a few days.

**Comment by saichandrapandraju** [comment]
Thanks @LysandreJik

**Comment by yaysummeriscoming** [comment]
@saichandrapandraju the PR was merged, so I think this issue can be closed now?

**Comment by saichandrapandraju** [comment]
ok @yaysummeriscoming ,

May I know when will be the stable release( I think 4.4.0) for these merges?

**Comment by LysandreJik** [comment]
Yes, this issue can be closed! v4.4.0 should be released in the next two weeks.

**Comment by roshan-k-patel** [comment]
Has this been fixed? I'm downloading the model direct from huggingface [here](https://huggingface.co/microsoft/deberta-v2-xlarge) and i still get this error thrown

**Comment by LysandreJik** [comment]
Are you using the `DebertaV2Model` or the `DebertaModel` ?

**Comment by roshan-k-patel** [comment]
I am using the simpletransformers library, i'm not sure if you're familiar with it but i believe by default it uses the DebertaModel, not sure how and if i can change it to DebertaV2Model

**Comment by smdp2000** [comment]
encode batch plus is not supported by DebertaV2Model ?
