### ISSUE TITLE
Uploaded a new model but is not found on the hub.

### ISSUE THREAD

**Issue by zolekode** [huggingface/transformers#10194]
# 🌟 New model addition
I recently added this model: https://huggingface.co/flexudy/t5-small-wav2vec2-grammar-fixer

However, I get this error whilst trying to download it.
```
Can't load tokenizer for 'flexudy/t5-small-wav2vec2-grammar-fixer'
```
How can I fix it please?

**Comment by stefan-it** [comment]
Hi @zolekode ,

the folder structure is not quite correct:

https://huggingface.co/flexudy/t5-small-wav2vec2-grammar-fixer/tree/main

You just need to move everything from the `t5-small-wav2vec2-grammar-fixer` to the root folder. Then it should work :hugs:

**Comment by zolekode** [comment]
Ah I see. awesome. Thanks alot @stefan-it
