### ISSUE TITLE
No module named 'tasks'

### ISSUE THREAD

**Issue by Daniel-z-Kaplan** [huggingface/transformers#10224]
## Environment info

- `transformers` version: 4.3.2
- Platform: 5.10.8-200.fc33.x86_64
- Python version: 3.8.3
- PyTorch version (GPU?): 1.6.0 (GPU)
- Tensorflow version (GPU?): 2.4.1 (GPU)
- Using GPU in script?: No.
- Using distributed or parallel set-up in script?: No.

@sgugger, @patil-suraj

## Information

Model I am using (Bert, XLNet ...): allenai/scibert_scivocab_uncased

The problem arises when using:
* [X ] the official example scripts: (give details below)

I'm using the old NER script, since the model I'm using doesn't support Fast Tokenizers. 
https://github.com/huggingface/transformers/blob/master/examples/legacy/token-classification/run_ner.py
However, I get an error on trying to import "tasks.py". I did find a previous git issue for this, which recommended downloading said file.... but it no longer exists. 

The tasks I am working on is:
* [X ] my own task or dataset: (give details below)
I'm using the bc2gm-corpus dataset.

## To reproduce

Steps to reproduce the behaviour:

1. Download the script from the provided github link.
2. Run it with any real model name, a real directory for data (doesn't need to include data), and an output directory.
I used the following command: python3 run_ner.py --model_name_or_path allenai/scibert_scivocab_uncased --data_dir bc2gm-corpus/conll --output_dir ./output 

`  File "run_ner.py", line 323, in <module>
    main()
  File "run_ner.py", line 122, in main
    module = import_module("tasks")
  File "/home/dkaplan/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tasks' `
## Expected behavior

I expect the NER script to run, finetuning a model on the provided dataset.

**Comment by sgugger** [comment]
I think you did not clone the repository properly or are not running the command from the folder `examples/legacy/token-classification`, since that folder does have a task.py file.

**Comment by Daniel-z-Kaplan** [comment]
Ah, I was searching for "tasks.py" instead. Just user error, thanks for the fast reply.
