### ISSUE TITLE
ConvBert not compatible with torch v1.6

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#10238]
ConvBERT uses statements like `torch.multiply` which did not exist in pytorch v1.6 => ConvBERT is not compatible with v1.6 (cc @abhishekkrthakur).

This can easily be checked when running:

`pytest tests/test_modeling_convbert.py`

@LysandreJik, @sgugger - It would be great to test all the different pytorch versions in a slow test I think.

**Comment by LysandreJik** [comment]
Testing all versions from torch v1.3.0+ is indeed on the roadmap, I expect ~1 month out alongside all the other tests improvements.
