### ISSUE TITLE
Question about (no_decay = ['bias', 'LayerNorm.weight']) in BERT(Transformer-based) 

### ISSUE THREAD

**Issue by fightnyy** [huggingface/transformers#10239]
Hi, I have a Question about the BERT model code.
I saw "no_decay = ['bias', 'LayerNorm.weight']" in BERT code(especially, in Optimizer part). It seemed reasonable, however, did this prove to be better performance? Or is it just to speed up calculations?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
