### ISSUE TITLE
Upgrade transformers from 3.5.0 to 4.3.2 instance error

### ISSUE THREAD

**Issue by bp91** [huggingface/transformers#10242]
Hi guys. I tried to update the transformers module from the version 3.5.0 to the version 4.3.2.
After this upgrade, the code that previously was working now has some problems.

This is my code:
```
from transformers import AutoConfig, AutoTokenizer, TFAutoModel

config = AutoConfig.from_pretrained("amazon/bort")
model = TFAutoModel.from_pretrained("amazon/bort", config=config)
bert_main_layer = model.bert

encoder, pooler = bert_main_layer(input_ids_in, attention_mask=input_masks_in)

X = tf.keras.layers.Dropout(config.hidden_dropout_prob)(pooler)
X = tf.keras.layers.Dense(
    constants.CLASSES,
    kernel_initializer=tf.keras.initializers.TruncatedNormal(stddev=config.initializer_range),
    activation="softmax"
)(X)

model = tf.keras.Model(
    inputs=[input_ids_in, input_masks_in],
    outputs=[X]
)
```

In particular, when I instantiate the class `bert_model` (`bert_main_layer(input_ids_in, attention_mask=input_masks_in)`), with the 3.5.0 version it returns two tensors:
```
<tf.Tensor 'bert/encoder/layer_._3/output/LayerNorm/batchnorm/add_1:0' shape=(None, 333, 1024) dtype=float32>
<tf.Tensor 'bert/pooler/dense/Tanh:0' shape=(None, 1024) dtype=float32>
```

With the version 4.3.2 it returns two strings:
```
last_hidden_state
pooler_output
```

The consequence is that now I have this exception on the Dense layer:
```
ValueError: Input 0 of layer dense is incompatible with the layer: : expected min_ndim=2, found ndim=0. Full shape received: []
```

Since I haven't found any documentation or guidance, can you please help me? What I'm doing wrong?
Thank you

**Comment by LysandreJik** [comment]
Hi, thanks for opening an issue. The breaking changes from version v3 to v4 are heavily documented: https://huggingface.co/transformers/migration.html#migrating-from-transformers-v3-x-to-v4-x

Your particular issue is [bullet number 4](https://huggingface.co/transformers/migration.html#switching-the-return-dict-argument-to-true-by-default).

**Comment by LysandreJik** [comment]
For our reference, when trying to look for breaking changes between v3 and v4, where did you look? If we can improve visibility for those, it would be great. Maybe "Migration" isn't the best identifier? Are there some specific keywords you used?
