### ISSUE TITLE
microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract not available for tensorflow

### ISSUE THREAD

**Issue by abhijithneilabraham** [huggingface/transformers#10252]
@jplu
The above said model is available for pytorch but not for tensorflow. How to convert a pytorch checkpoint to tensorflow for this one? Is it possible for doing a contribution for the same?

**Comment by jplu** [comment]
Hello!

You can load PyTorch weights into Tensorflow with `TFBertModel.from_pretrained("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract", from_pt=True)`

**Comment by abhijithneilabraham** [comment]
That works, thanks!
