### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by gwc4github** [huggingface/transformers#10288]
## Minor issue in the Fine tuning docs
In the "Named Entity Recognition" section of the "Summary of tasks" documentation page there are some bad links.
Here is a link to the section: https://huggingface.co/transformers/task_summary.html#named-entity-recognition

The text in question is:
##Named Entity Recognition
Named Entity Recognition (NER) is the task of classifying tokens according to a class, for example, identifying a token as a person, an organisation or a location. An example of a named entity recognition dataset is the CoNLL-2003 dataset, which is entirely based on that task. If you would like to fine-tune a model on an NER task, you may leverage the run_ner.py (PyTorch), run_pl_ner.py (leveraging pytorch-lightning) or the run_tf_ner.py (TensorFlow) scripts.

## ISSUE:
The links for the following give a 404 error:
       run_pl_ner.py, run_tf_ner.py

**Comment by sgugger** [comment]
Thanks for flagging! Those have not been updated in a while so I made a pass over that file.

**Comment by gwc4github** [comment]
I still see the bad links.  Is the change getting pushed later?

**Comment by sgugger** [comment]
It will only be seen in the [master documentation](https://huggingface.co/transformers/master/) for now. At the next release, it will become visible in the stable documentation.

**Comment by gwc4github** [comment]
Will the new run_ner.py work with PyTorch and TF?  PyTorch-Lightening too?
