### ISSUE TITLE
if cutoffs=[], convert_transfo_xl_checkpoint_to_pytorch.py has a bug

### ISSUE THREAD

**Issue by Pydataman** [huggingface/transformers#1029]
## 🐛 Bug

Model I am using (Bert, XLNet....): transformer_xl

Language I am using the model on (English, Chinese....): I train xl model base on own dataset

## Environment

* OS: centos 7.3
* Python version: python3.6
* PyTorch version: torch1.1
* PyTorch Transformers version (or branch): 1.0.0
* Using GPU: yes
* Distributed of parallel setup ? no
* Any other relevant information: no 

## detail context

AttributeError: 'ProjectedAdaptiveLogSoftmax' object has no attribute  'cluster_weight'

I see 'ProjectedAdaptiveLogSoftmax' code, if len(cutoffs) - 1 > 0,  will have attribute  'cluster_weight'

**Comment by LysandreJik** [comment]
Hi!

Yes, you should indeed specify `cutoffs` in your `TransfoXLConfig` or the adaptive softmax won't be able to create its clusters. We should probably put a more explicit error.

**Comment by kaiidams** [comment]
Hello, @LysandreJik

The checkpoint of https://github.com/kimiyoung/transformer-xl doesn't have cutoff_N when adaptive softmax is not used. Does PyTorch-Transformers support TransfoXLConfig.adaptive = False? If supported, should it read checkpoint without explicit error? The content of checkpoint is like this without adaptive softmax.

```
transformer/adaptive_embed/lookup_table (DT_FLOAT) [32768,512]
transformer/adaptive_embed/lookup_table/Adam (DT_FLOAT) [32768,512]
transformer/adaptive_embed/lookup_table/Adam_1 (DT_FLOAT) [32768,512]
transformer/adaptive_softmax/bias (DT_FLOAT) [32768]
transformer/adaptive_softmax/bias/Adam (DT_FLOAT) [32768]
transformer/adaptive_softmax/bias/Adam_1 (DT_FLOAT) [32768]
transformer/layer_0/ff/LayerNorm/beta (DT_FLOAT) [512]
```
