### ISSUE TITLE
Documentation of the decode method is missing

### ISSUE THREAD

**Issue by cronoik** [huggingface/transformers#10305]
The tokenizer documentation [page](https://huggingface.co/transformers/main_classes/tokenizer.html) is generated from the following files:

- tokenization_utils_base.py  
- tokenization_utils_fast.py  
- tokenization_utils.py  

At least the documentation of the decode method is missing even if it is properly documented in the [source file](https://github.com/huggingface/transformers/blob/9a7e63729f3ff6ddf065fd0d443421e46b1a2ffb/src/transformers/tokenization_utils_base.py#L3099).

@sgugger 
Could you please have a look?

**Comment by sgugger** [comment]
This has been fixed a few days ago, I believe. Look at the [master doc tokenizer page](https://huggingface.co/transformers/master/main_classes/tokenizer.html) (the stable documentation is only updated at each release).

**Comment by cronoik** [comment]
Yes, you are right.
