### ISSUE TITLE
Issue Loading bert-based-german-cased

### ISSUE THREAD

**Issue by George-Ogden** [huggingface/transformers#10306]
Message on the website is:
 Can't load tokenizer using from_pretrained, please update its configuration: 400 Client Error: Bad Request for url: https://int-deepset-models-bert.s3.eu-central-1.amazonaws.com/pytorch/bert-base-german-cased-vocab.txt

**Comment by cronoik** [comment]
Which code caused this error?

**Comment by George-Ogden** [comment]
This issue comes from the hosted API https://huggingface.co/bert-base-german-cased?text=Ich+bin+%5BMASK%5D

**Comment by julien-c** [comment]
@tholor The url above currently loads for me, but to be future-proof should we cp the files currently loaded from that S3 bucket to the corresponding model repo (here, https://huggingface.co/bert-base-german-cased)?

cc'ing @LysandreJik

**Comment by tholor** [comment]
@julien-c Sure, let's copy them from our S3 to the model repo.

**Comment by julien-c** [comment]
copied to the model repo in 
https://huggingface.co/bert-base-german-cased/commit/876457621368b8c955478cfe1cdee634f47ea34c

Changed hardcoded url in https://github.com/huggingface/transformers/pull/10353

**Comment by julien-c** [comment]
@Narsil  could you please check if the inference widget works for this model when you get a chance to upgrade the transformers dependency in the API? Thanks!

**Comment by George-Ogden** [comment]
⚠️ Can't load tokenizer using from_pretrained, please update its configuration: 400 Client Error: Bad Request for url: https://int-deepset-models-bert.s3.eu-central-1.amazonaws.com/pytorch/bert-base-german-cased-vocab.txt
It's still not working!

**Comment by LysandreJik** [comment]
Hi @George-Ogden, the change was merged two days ago and is therefore available on the `master` branch, but not yet in a release.

Do you still get the same error when installing from source?

**Comment by George-Ogden** [comment]
This is on the inference API on the website I haven't tried it from source.
