### ISSUE TITLE
Efficient data loading functionality

### ISSUE THREAD

**Issue by shubhamagarwal92** [huggingface/transformers#1031]
## 🚀 Feature

Efficient data loader for huge dataset with lazy loading! 

## Motivation

I am working with a huge dataset consisting of 120m examples (~40G raw text) in a single csv file. I tried to follow the [run_glue](https://github.com/huggingface/pytorch-transformers/blob/master/examples/run_glue.py) distributed training example, however this is too slow as it first creates all the examples and cache it [here](https://github.com/huggingface/pytorch-transformers/blob/master/examples/run_glue.py#L251). Basically only first process in distributed training process the dataset and others just use the cache. 

Is there any data loader (or a working example) that would be efficient for training the model on such a huge dataset?

**Comment by shubhamagarwal92** [comment]
@thomwolf Is there an efficient implementation for this?

**Comment by Santosh-Gupta** [comment]
CSV generally has slower load times. How about benchmarking with pickle, parquet, and feather? Pytorch's dataloader can handle multiple files and multiple lines per file 
https://discuss.pytorch.org/t/dataloaders-multiple-files-and-multiple-rows-per-column-with-lazy-evaluation/11769
