### ISSUE TITLE
[Question] Add a new token to tokenizer and bart model

### ISSUE THREAD

**Issue by mwang98** [huggingface/transformers#10319]
Hi,  
I have extended the word embedding of a tokenizer and a bart model through `tokenizer.add_token()` and `model.resize_token_embeddings(len(tokenizer))`. Because the ground truth consist of a newly added token, the dimension of the decoder output should be extended as well.

But I can't figure out how to extend the model. Can anyone give me some help?

Thanks in advance ! 💯

**Comment by LysandreJik** [comment]
Hello! You should use the [resize_token_embeddings](https://huggingface.co/transformers/main_classes/model.html?highlight=resize_token_embeddings#transformers.PreTrainedModel.resize_token_embeddings) method for that. Will add that to the documentation.
