### ISSUE TITLE
Huggingface mt5 does not reach the performance of original mt5 on paws-x 

### ISSUE THREAD

**Issue by dorost1234** [huggingface/transformers#10315]
## Environment info

- `transformers` version: 4.3.2
- Platform: linux
- Python version: 3.7
- PyTorch version (GPU?): 1.7 
- Tensorflow version (GPU?): - 
- Using GPU in script?: yes 
- Using distributed or parallel set-up in script?: yes 

### Who can help

 t5: @patrickvonplaten, @patil-suraj

## Information

Hi
I ran the model of mT5-small on paws-x in zero-shot cross-lingual setup where we tune on english and evaluate on all languages in paws-x dataset and obtain only 80.2 while the reported original mt5-small on this datasets is 82.4. (see table 2 in mt5 paper) I used the setup in mt5 paper, is there any missing details from original mt5 work in the huggingface implementation? thanks 
 

## Expected behavior

reaching the performance of original model.

**Comment by patrickvonplaten** [comment]
Hey @dorost1234, 

could you post your question on the [forum](https://discuss.huggingface.co/) and see whether you can get help from the community there? We try to keep GitHub issues for bug reports mostly. 

It would also be very important that you attach a notebook or something that allows people to understand what you have done and what you might have missed...

**Comment by dorost1234** [comment]
Hi  Patrick
thanks, sure, I posted here because I mainly wanted to ask if you have in
the past compared the performance of original mt5 with the HuggingFace
model side by side on one setting?
this is unfortunately a lot of codes for me to share, since I build on top
of my codebase, and this is not very easy to make a small example showing
these differences.
Overall, knowing if in the past such comparison is done is great.
thanks.
