### ISSUE TITLE
ForTokenClassification head on BART

### ISSUE THREAD

**Issue by jonatasgrosman** [huggingface/transformers#10317]
# 🚀 Feature request

Hello guys! I'm trying to reproduce the token classification experiments from the [BART paper](https://arxiv.org/abs/1910.13461) using the HF/Transformers and found that a token classification head is missing on the current BART model HF implementation. 

The current BART implementation only has the "BartForConditionalGeneration" and "BartForSequenceClassification". Are there any plans to add a "BartForTokenClassification" head too?

**Comment by NielsRogge** [comment]
It would be great to have a `BartForTokenClassification`. Does it use the same head as `BertForTokenClassification`, etc.? 

Feel free to open a PR :)
