### ISSUE TITLE
BERT for speech

### ISSUE THREAD

**Issue by arunraja-hub** [huggingface/transformers#10320]
How can I use HF's BERT models for speech-to-text training?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Also, [here's the doc](https://huggingface.co/transformers/model_doc/wav2vec2.html#transformers.Wav2Vec2ForCTC for `Wav2Vec2ForCTC` which seems to be the model you're interested in.

Thanks!
