### ISSUE TITLE
Return cross-attention weights in generation function

### ISSUE THREAD

**Issue by Mehrad0711** [huggingface/transformers#10335]
# 🚀 Feature request

With v4.2.0 release, generation can now return encoder and decoder self-attention weights but it still doesn't return cross-attention weights. These weights are already computed and returned in model `forward` method, and just need to be returned in `generate` method.
## Motivation

Visualizing cross-attention weights is useful for many applications such as token-alignment.

## Your contribution

I can submit a PR.

**Comment by Mehrad0711** [comment]
Hi @patrickvonplaten!
Please let me know what you think about the feature. I can send a PR for it once you confirm.

**Comment by patrickvonplaten** [comment]
Yes, this would be a nice addition indeed :-)

**Comment by patrickvonplaten** [comment]
Happy to help you in your PR!
