### ISSUE TITLE
DialoGPT tokenizer config issue

### ISSUE THREAD

**Issue by ayubSubhaniya** [huggingface/transformers#10342]
## Environment info

- `transformers` version: 4.3.2
- Platform: Darwin-19.3.0-x86_64-i386-64bit
- Python version: 3.6.5
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
Models:

- gpt2: @patrickvonplaten, @LysandreJik

Library:
- tokenizers: @n1t0, @LysandreJik

## Information

Model I am using (DialoGPT-small.):
When I load tokenizer, its `model_max_len` is coming infinite.

```
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch


tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-small")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-small")

max_len = tokenizer.model_max_length
```

## Expected behavior
Before It was coming as 1024. 

Is this some recent change?

**Comment by LysandreJik** [comment]
Hi! This change may have originated from the move to the git-based repos. @patrickvonplaten have just modified the DialoGPT tokenizer configuration to have 1024 as model max length, you shouldn't have to do anything but re-run your script to see it updated.

**Comment by julien-c** [comment]
@LysandreJik Don't hesitate to reference the url for the commit on huggingface.co for future reference

Here I believe it's https://huggingface.co/microsoft/DialoGPT-small/commit/9fb5c2d6a01395898bfd90acce2dbec1537730f1

**Comment by LysandreJik** [comment]
Indeed! Here are the commits:

`DialoGPT-small`: [huggingface@364722e](https://huggingface.co/microsoft/DialoGPT-small/commit/364722ef15f5c04dcb9a57d3b77815bbc1d51efc) and [huggingface@9fb5c2d](https://huggingface.co/microsoft/DialoGPT-small/commit/364722ef15f5c04dcb9a57d3b77815bbc1d51efc)
`DialoGPT-medium`: [huggingface@e84a3e](https://huggingface.co/microsoft/DialoGPT-medium/commit/e84a3e0adc90aabc6b57e59318e15bf4b733eedc)
`DialoGPT-large`: [huggingface@acc7ea](https://huggingface.co/microsoft/DialoGPT-large/commit/acc7eaf98122bc6922976182b4d365d650f179b3)

**Comment by ayubSubhaniya** [comment]
Thanks @LysandreJik for quick fix.
