### ISSUE TITLE
Where can we find the `RAG` implementation?

### ISSUE THREAD

**Issue by RoderickGu** [huggingface/transformers#10343]
I noticed that `transformers` included the implementation for `DPR`. But for `RAG`, I only find a [demo](https://huggingface.co/rag/). Is there a source code for `RAG`? Or do you know where is Facebook's source code for `RAG`? Thanks

**Comment by NielsRogge** [comment]
The implementation can be found [here](https://github.com/huggingface/transformers/tree/master/src/transformers/models/rag).

**Comment by RoderickGu** [comment]
@NielsRogge Thanks! That's it.
