### ISSUE TITLE
Security Bug found - looking for contact for responsible disclosure

### ISSUE THREAD

**Issue by ethan-carlten** [huggingface/transformers#10359]
Hi,
I found a security bug on software related to you. 
Can you please tell me how to contact you for a responsible disclosure?
Thanks.

**Comment by julien-c** [comment]
Hi – can you send an email to `tech at huggingface.co`? Thanks.

**Comment by ethan-carlten** [comment]
I did send it.

**Comment by julien-c** [comment]
closing as will handle over email. Thanks!
