### ISSUE TITLE
denoising objective for pretraining

### ISSUE THREAD

**Issue by dorooddorood606** [huggingface/transformers#10361]
Hi
Denoising objective is used in T5 and BART models, could you please add it in pretraining language models?
For now, if you could I appreciate sharing some advice how I can implement it. is there a piece of codes in huggingface I could start from? 
thanks

**Comment by dorooddorood606** [comment]
@patil-suraj @patrickvonplaten  please help. thanks

**Comment by patrickvonplaten** [comment]
Hey @dorooddorood606,

could you please make use of the forum: https://discuss.huggingface.co/ for such questions. Thanks!
