### ISSUE TITLE
Training LongformerForQuestionAnswering on TriviaQA

### ISSUE THREAD

**Issue by SapirWeissbuch** [huggingface/transformers#10377]
Hello,

Could you please give a short explanation on how to retrain `LongformerForQuestionAnswering` in order to receive these weights: `allenai/longformer-large-4096-finetuned-triviaqa` (https://huggingface.co/allenai/longformer-large-4096-finetuned-triviaqa/tree/main). 

Thank you,
Sapir

**Comment by LysandreJik** [comment]
Pinging @ibeltagy and @patrickvonplaten who would know better.
