### ISSUE TITLE
deprecated reference `tokenizer.max_len` in glue.py (PR #10220)

### ISSUE THREAD

**Issue by poedator** [huggingface/transformers#10372]
There is a deprecated reference to `tokenizer.max_len` with `tokenizer.model_max_length` - similar to [issue 8739](https://github.com/huggingface/transformers/issues/8739) and [PR 8604](https://github.com/huggingface/transformers/pull/8604). 
See error example [in Colab here](https://colab.research.google.com/gist/poedator/f8776349e5c625ce287fc6fcd312fa1e/tokenizer-max_len-error-in-transformers_glue.ipynb).  it causes `AttributeError: 'BertTokenizer' object has no attribute 'max_len'`
The error happens when `glue_convert_examples_to_features()` is called without `max_length` parameter specified. In that case [line 119](https://github.com/huggingface/transformers/blob/master/src/transformers/data/processors/glue.py#L119) with wrong reference gets called. 

I submitted a [simple PR #10220](https://github.com/huggingface/transformers/pull/10220). It should be able to fix this issue.

**Comment by LysandreJik** [comment]
Thanks for opening a PR which fixes the issue! I just merged it.
