### ISSUE TITLE
wrong generation of training sentence pairs. method: get_corpus_line, in finetune_on_pregenerated.py

### ISSUE THREAD

**Issue by Evgeneus** [huggingface/transformers#1037]
## 🐛 Bug

Model I am using:
BERT

Language I am using the model on (English, Chinese....):

The problem arise when using:
* [ ] the official example scripts: (give details)

The tasks I am working on is:
I am running on my own text corpus the official example to fine-tune BERT

1. create my_corpus.txt:
AAA
BBB

CCC
DDD

EEE
FFF
2. run python3 simple_lm_finetuning.py 
--train_corpus my_corpus.txt 
--bert_model bert-base-uncased 
--do_lower_case 
--output_dir finetuned_lm/
--do_train

## Expected behavior
I expected to see the following first 3 outputs of get_corpus_line method, ie, t1 t2:
1)
t1=AAA
t2=BBB
2)
t1=CCC
t2=DDD
3)
t1=EEE
t2=FFF

But received:
1)
t1=AAA
t2=BBB
2)
t1=CCC
t2=DDD
3) **!!!!!!! (HERE)
t1=DDD
t2=AAA

## Additional context 

It seems we need to make self.line_buffer equal to None whenever we close the file. 
Possible silution:
line 118:
if cur_id != 0 and (cur_id % len(self) == 0):
    self.file.close()
    self.file = open(self.corpus_path, "r", encoding=self.encoding)
    ***self.line_buffer = None***

**Comment by thomwolf** [comment]
Hi @Evgeneus, does your proposed solution solves the problem on your side?

**Comment by Evgeneus** [comment]
> Hi @Evgeneus, does your proposed solution solve the problem on your side?

Hi @thomwolf, seems yes.
