### ISSUE TITLE
[Documentation issue] Sequence to sequence models

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/transformers#10373]
Most models have their example docstrings appended using the `add_code_sample_docstrings` method. This method checks the name of the architecture, and according to its suffix, adds the corresponding sequence.

However, this isn't perfect with the difference between sequence-to-sequence and enc/dec only models, which can have the same suffix: `BertModel` and `MarianModel` have the same suffixes, but should not have the same docstrings, the latter needing `decoder_input_ids` in order to work.

I propose to return a different code sample according to the architecture type (seq-to-seq vs enc/dec). The signature of the method that updates the code sample is the following:

https://github.com/huggingface/transformers/blob/2d458b2c7d6fb1dd5b2361938d1b5bd4c2106479/src/transformers/file_utils.py#L884-L886

There are in my opinion two ways to go about it:

- We can infer the type from the `output_type`. We've mentioned some while ago that having inheritance with model outputs and being able to identify categories of outputs from their classes would make sense for a potential pipeline-v2 implementation, this could be implemented here to detect if a model is seq-2-seq or not.
- We could add another argument to the signature too mention if it's seq-2-seq or not. However, this isn't very future-proof and can result in increased complexity if we ever need an additional separation across architectures.

@patrickvonplaten @sgugger @patil-suraj looking forward to your feedback. I tend to prefer the first option even if it requires a bit more work.

Related issue: https://github.com/huggingface/transformers/issues/10368

**Comment by patrickvonplaten** [comment]
Option 1) seems the way to go for me as well here!

**Comment by sgugger** [comment]
Said the same in private but realized I didn't put it here. So option 1 it is!

**Comment by sgugger** [comment]
Don't close this one robot!
