### ISSUE TITLE
Fine-tune pretrained Wav2Vec2 on a small custom dataset 

### ISSUE THREAD

**Issue by Omarnabk** [huggingface/transformers#10384]
I am wondering how to **fine-tune** a pre-trained model on a small speech/audio dataset. I have 10 hours of audio with their transcript. 

I would like to fine-tune a model and then use it as described here:
[](https://huggingface.co/facebook/wav2vec2-large-960h)

Thanks!

**Comment by NielsRogge** [comment]
Patrick is working on it, see #10145

**Comment by amiyamandal-dev** [comment]
I am also searching for fine-tuning of this model.
