### ISSUE TITLE
 how to freeze specific layers of TFbert model and just train a classifier? 

### ISSUE THREAD

**Issue by nerses0** [huggingface/transformers#10396]
Could someone help me to freeze say first 3 layers of transformers.TFDistilBertModel.from_pretrained('distilbert-base-multilingual-cased'). I've tried recommendations for TF model from [#400](https://github.com/huggingface/transformers/issues/400) but it seems to freeze all layers at once.
Thanks in advance!

**Comment by NielsRogge** [comment]
I googled it, this should be working:

https://colab.research.google.com/drive/1EAVhQGdVvXbCu8gGq0lZ9dOnN4jJtvAj?usp=sharing

**Comment by nerses0** [comment]
@NielsRogge thanks for the help!

**Comment by Vstay97** [comment]
> I googled it, this should be working:
> 
> https://colab.research.google.com/drive/1EAVhQGdVvXbCu8gGq0lZ9dOnN4jJtvAj?usp=sharing


Thank you very much, this is very useful to me

**Comment by Drew2019** [comment]
Is there a reason this would not work for "model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=1)"? I am only able to access the layers using this code for "TFBertForSequenceClassification.from_pretrained("bert-base-uncased")"
