### ISSUE TITLE
NER Pipeline not working

### ISSUE THREAD

**Issue by GuillemGSubies** [huggingface/transformers#10393]
I just followed the token classification notebook and created a pipeline from the model I trained there. Here you can see the full notebook: https://colab.research.google.com/drive/1OzfFTgZwjxdIikbQ8lVJbA2SRF3IeJ5F?usp=sharing

The only thing that I changed (apart from creating the pipeline and calling it) s the number of training steps so the training is faster.

In the last cell you can see the error:

```
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.
```

### Who can help

- pipelines: @LysandreJik

**Comment by LysandreJik** [comment]
Hello! The fix for this was merged a few days ago: https://github.com/huggingface/transformers/pull/10184

I recommend you install from source while no new version is available for Transformers (a new version should be out in ~2 weeks). Sorry for the inconvenience.

**Comment by GuillemGSubies** [comment]
Ok thank you for the fast response. I always open the issues before checking master branch :sweat:

**Comment by LysandreJik** [comment]
No worries, better to have too much issues reported than not enough!
