### ISSUE TITLE
Question about the `decoder_input_ids`  in `LEDForConditionalGeneration` forward method

### ISSUE THREAD

**Issue by yww211** [huggingface/transformers#10408]
https://github.com/huggingface/transformers/blob/17b6e0d474b797cdddf5225b0f51bf0e928091b9/src/transformers/models/led/modeling_led.py#L2337

Hi, 
I have a question about the `LEDForConditionalGeneration` forward args. 
The `decoder_input_ids`  has a comment that `decoder_input_ids (torch.LongTensor of shape (batch_size, target_sequence_length), optional) – Provide for translation and summarization training. By default, the model will create this tensor by shifting the input_ids to the right, following the paper.`. 
Form the forward method in  `LEDForConditionalGeneration`, i can see that when not  assigning the `decoder_input_ids` in the forward method of  `LEDForConditionalGeneration` object , the `decoder_input_ids` will be generated by [shifting  the `labels`  value one token to right in the  forward method](https://github.com/huggingface/transformers/blob/17b6e0d474b797cdddf5225b0f51bf0e928091b9/src/transformers/models/led/modeling_led.py#L2337). 

So my question is  if i want to explictly pass the `decoder_input_ids` to the forward method, do i need to explictly shift it one token as the [code](https://github.com/huggingface/transformers/blob/17b6e0d474b797cdddf5225b0f51bf0e928091b9/src/transformers/models/led/modeling_led.py#L2337) shows before the forward pass?

**Comment by patrickvonplaten** [comment]
Hey @yww211, 

actually there was a bug in the docstring, that I found thanks to you :-) The attached PR corrects this mistake.

To answer your question, you should not shift the `decoder_input_ids` explicitly by one when passing them & in fact you have to pass the `decoder_input_ids` if you want to use the forward method.
