### ISSUE TITLE
Model Hub: Search by model size

### ISSUE THREAD

**Issue by ioana-blue** [huggingface/transformers#10404]
# 🚀 Feature request

It would be great if the model cards for models would include the model size (i.e., the number of parameters) and then the model hub will allow searching for models by size.

## Motivation
Depending on the task/problem/context, smaller or larger models are more beneficial. It's hard to keep up with all the models out there. For example, if I'm interested in distilled/compressed/smaller BERTs, I may be able to remember DistilBERT, MobileBERT but maybe forget about SqueezeBERT, TinyBERT, etc. A search by size would make all these smaller models visible.

**Comment by julien-c** [comment]
Definitely a good idea

**Comment by ioana-blue** [comment]
And since I started talking about model cards... :) I think it would be cool if you guys actually imposed some format. I think the original paper/idea had a format. Now "model cards" stands for "whatever the researcher had time to fill in that day" :) A few fields of interest: model size, training data, NLP tasks, language(s), paper, _maybe_ something about model of inspiration (e.g., TinyBERT is a modification of BERT by...).

**Comment by NielsRogge** [comment]
I agree, there should at least be a template in my opinion. I hate to find models on the hub who don't provide any information. Moreover, all model cards look different, there's not really a structure.

**Comment by julien-c** [comment]
There is a template we link to in the second question of https://huggingface.co/docs (=> https://github.com/huggingface/model_card), though we should make it more built-in/central at some point.

**Comment by david-waterworth** [comment]
It would also be nice if the template also included details on tokenisation, what algorithm was used (BPE, Unigram, Word Piece) and the parameters (vocab size etc).
