### ISSUE TITLE
Trainer: Make `best_model_checkpoint` path in `trainer_state.json` relative to `args.output_dir`

### ISSUE THREAD

**Issue by tanmay17061** [huggingface/transformers#10412]
# 🚀 Feature request
An enhancement of `best_model_checkpoint` for more robustness.

Currently `Trainer.state.best_model_checkpoint` holds absolute path to the best checkpoint when `Trainer.args.load_best_model_at_end=True` is passed.  
It can be useful if `Trainer.state.best_model_checkpoint` value is relative to `Trainer.args.output_dir`
## Motivation

**Absolute path hinders portability** of the trained models.  
For example, if a user wants to continue _previous training_ using argument `resume_from_checkpoint` for `Trainer.train`, not having the `output_dir` exactly same as the _previous training_ (eg- renaming of any directory in the path) can break the `load_best_model_at_end` functionality due to the previous absolute paths being no longer valid.

## Your contribution

I can raise a PR if this is a useful change to have!

**Comment by sgugger** [comment]
I think this would a very welcome change indeed, so please work on that if you have time and if it's something you'd like to do!
