### ISSUE TITLE
Unable to convert Facebook/mbart-many-to-many model to onxx

### ISSUE THREAD

**Issue by sankarsiva123** [huggingface/transformers#10420]
When I tried to convert Facebook/mbart-many-to-many model . I am unable to convert I am getting issue.
Pls help me to convert this model to ONXX

**Comment by LysandreJik** [comment]
I do not think mBART can be converted to ONNX as of now.

**Comment by sankarsiva123** [comment]
Hi Thanks for the information.
Facebook/many-to-many takes 9s seconds for translation on cpu , is there a way to reduce the inference time ?

**Comment by Narsil** [comment]
Hi @sankarsiva123, have you tried HF's API inference.

9s per inference seems a bit off: https://huggingface.co/facebook/mbart-large-50-many-to-many-mmt?text=Hello+there+%21+
We do run some optimizations there as HF's hosted API but still it seems like you could have better inference times than 9s.

**Comment by sankarsiva123** [comment]
Hi, @Narsil Yeah, I tried HF's API inference, it is pretty much fast.
I am using CPU, I tried both in google colab, and in my local, it is taking around 9s.
Am I missing something while using the model, so my inference time is high than normal?
![image](https://user-images.githubusercontent.com/58412261/109768056-6c229180-7c1e-11eb-9ad2-b3d9bf0a14ca.png)

**Comment by Narsil** [comment]
Can you time your inner loop without the tokenizer ? (Just making sure it's not that).

Otherwise you see to use generate, which is the right way to go.
I don't know colab's CPU nor yours, but it could definitely be the problem (or the pytorch version you're rolling which might have not been optimized for your CPU instruction set.)
