### ISSUE TITLE
[examples] add --max_train_samples  --max_val_samples  --max_test_samples cl args to all scripts

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#10423]
As a part of an effort to make all examples have the same look and feel this issue requests to sync the support for these 3 cl args in `run_seq2seq.py`:
```
--max_train_samples 5 --max_val_samples 5 --max_test_samples 5
```
into:
1. all other `examples/*/run_*.py`
2. `templates/adding_a_new_example_script`

Part B. the metrics should be now updated to include the actual number of samples that were run. here is an example for train:
https://github.com/huggingface/transformers/blob/f52a15897b46ffa40af5c96d3726f0e18e91879b/examples/seq2seq/run_seq2seq.py#L586-L590
and the same for eval/test.

I'd say this can probable refactored too. Let me check with Sylvain.

The way it's currently used is to limit the number of dataset entries w/o needing to change the dataset, example:
```
run_seq2seq.py --model_name_or_path t5-small --output_dir output_dir  --do_eval --do_predict --do_train \
--evaluation_strategy=steps  --predict_with_generate  --task summarization     --dataset_name xsum \
--max_train_samples 60 --max_val_samples 10 --n_test 10
```

All the code that currently takes care of it can be found inside https://github.com/huggingface/transformers/blob/master/examples/seq2seq/run_seq2seq.py

This issue is open to anybody in the community who would like to tackle it.

Thank you!

**Comment by bhadreshpsavani** [comment]
Can I work on this?

**Comment by stas00** [comment]
Yes please! Thank you, @bhadreshpsavani

**Comment by stas00** [comment]
I was just thinking about this and why do we not have this functionality in the Trainer in first place? then perhaps none of this will be needed.

**Comment by bhadreshpsavani** [comment]
Cool!

**Comment by bhadreshpsavani** [comment]
Hi @stas00,
We can also close this issue right?

**Comment by stas00** [comment]
That's correct! Thank you for remembering it!

**Comment by stas00** [comment]
It sounds right. Use your internal compiler.

Probably once it's written, it can be run through the cookie-cutter and then tested? But I think it shouldn't be too difficult to test it visually.
