### ISSUE TITLE
RAG and retrieved documents

### ISSUE THREAD

**Issue by calderma** [huggingface/transformers#10425]
I pretrained a rag model using the "finetune_rag.py" script and it generates pretty good results for my (knowledge intensive) use case, certainly better than the straight finetuned BART model i was using before. I am using my own custom datasource generated from use_own_knowledge_dataset.py. One curious thing that is happening is that when i try to find what documents were retrieved during the generation process, i always get the same documents. I'm using the basic code snippet from issue#8104 and no matter what input i give, it returns the same few documents no matter how unrelated they are to the input. The generated results are still very good, so I'm not sure if there's an issue with how i'm retrieving the documents or if it really is always grabbing the same few docs for some reason, potentially an issue with my data. Any help or pointers with this would be greatly appreciated. Thank you.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
