### ISSUE TITLE
Confused about the time of forword

### ISSUE THREAD

**Issue by dy1998** [huggingface/transformers#10435]
## Environment info

- `transformers` version:3.0.0
- Platform: ubuntu 1604
- Python version: 3.7
- PyTorch version (GPU?):1.2.0 gpu
- Tensorflow version (GPU?): none
- Using GPU in script?: none
- Using distributed or parallel set-up in script?:No

### Who can help
@LysandreJik

## Information

Model I am using Bert, spceifically roberta_chinese_clue_tiny

The problem arises when using:
BertModel.from_pretrained

The tasks I am working on is:
just forward

Question:
Why the time of same forword is different? How to make it same?

## To reproduce
```
from transformers import BertTokenizer, BertModel
import time

tokenizer = BertTokenizer.from_pretrained("clue/roberta_chinese_clue_tiny")

model = BertModel.from_pretrained("clue/roberta_chinese_clue_tiny")

inputs = tokenizer("testtest", return_tensors="pt")

time_start=time.time()
outputs = model(**inputs)
time_end=time.time()

time_start2=time.time()
outputs = model(**inputs)
time_end2=time.time()

print('totally cost',time_end-time_start)
print('totally cost2',time_end2-time_start2)
```

## Expected behavior
```
totally cost 0.2720155715942383
totally cost2 0.007731199264526367
```

**Comment by NielsRogge** [comment]
I assume that that's how Python works, if you run the same thing again, the result will be cached. If you had provided different inputs, then the time would be the same.

**Comment by dy1998** [comment]
> I assume that that's how Python works, if you run the same thing again, the result will be cached. If you had provided different inputs, then the time would be the same.

Thanks for reply，but when i have tried differnt input, the inference time of first forword is longer than second forword(even 100x), i guess the model init produce the time cost

**Comment by patil-suraj** [comment]
The same length sentences can have a different number of tokens after tokenizing. You could rather randomly create `input_ids` of the same shape to test this reliabley.
