### ISSUE TITLE
Bug in Electra Example

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/transformers#10442]
The description for Electra (https://huggingface.co/google/electra-small-discriminator) contains code the example below. The last line fails, I think instead of predictions.tolist() it should be predictions.squeeze() as predictions is 1xN

Also the example doesn't seem to detect the corrupted tokens.

```
from transformers import ElectraForPreTraining, ElectraTokenizerFast
import torch

discriminator = ElectraForPreTraining.from_pretrained("google/electra-small-discriminator")
tokenizer = ElectraTokenizerFast.from_pretrained("google/electra-small-discriminator")

sentence = "The quick brown fox jumps over the lazy dog"
fake_sentence = "The quick brown fox fake over the lazy dog"

fake_tokens = tokenizer.tokenize(fake_sentence)
fake_inputs = tokenizer.encode(fake_sentence, return_tensors="pt")
discriminator_outputs = discriminator(fake_inputs)
predictions = torch.round((torch.sign(discriminator_outputs[0]) + 1) / 2)

[print("%7s" % token, end="") for token in fake_tokens]
[print("%7s" % int(prediction), end="") for prediction in predictions.tolist()]

```

**Comment by LysandreJik** [comment]
Ah, good point! I'll edit it now, thanks for letting us know.

**Comment by LysandreJik** [comment]
Just fixed it in [hf@cf81dc](https://huggingface.co/google/electra-small-discriminator/commit/cf81dc100ac08ff43eb688cb1e3e7d69a822f359)!

**Comment by david-waterworth** [comment]
Thanks @LysandreJik, out of interest did you get the same results as me - the model doesn't appear to have identified the fake token? I'll do some more investigation and perhaps post in the forum but it seems that no matter what I do it always retuns zeros? Also really the example should demonstrate the model working :)
