### ISSUE TITLE
How can I make the logging utils log to a file as well? 

### ISSUE THREAD

**Issue by howardlau1999** [huggingface/transformers#10454]
# 🚀 Feature request

I want to make the logging utils log to a file in addition to the console. But I can't find an API that lets me add a handler to the logging utils.

**Comment by howardlau1999** [comment]
I just realize that I can enable the propagation and add the file handler to logging.root

**Comment by sid8491** [comment]
> I just realize that I can enable the propagation and add the file handler to logging.root

how? can you please provide the example code, if possible.

**Comment by howardlau1999** [comment]
> > I just realize that I can enable the propagation and add the file handler to logging.root
> 
> how? can you please provide the example code, if possible.

@sid8491 add this piece of code at the beginning of your script
```python
file_formatter = logging.Formatter(fmt="%(asctime)s - %(levelname)s - %(name)s -   %(message)s",
                                       datefmt="%m/%d/%Y %H:%M:%S", )
file_handler = logging.FileHandler(
    os.path.join(training_args.output_dir, f"log.{os.getpid()}.{training_args.local_rank}.txt"))
file_handler.setFormatter(file_formatter)
logging.root.addHandler(file_handler)
```

**Comment by benjpau** [comment]
Thank you for providing the solution. However, after I set it up this way, I found that the log in the main.py file can be logged to the file properly. However, the logs in other files (such as trainer.py) are not logged to the file. In addition, everything is fine to be logged in the command line. Have you encountered this situation?

**Comment by HarikrishnanBalagopal** [comment]
This is still an issue, is there a simple way to send all logs to a file?
