### ISSUE TITLE
How to Improve inference time of facebook/mbart many to many model?

### ISSUE THREAD

**Issue by Vimal0307** [huggingface/transformers#10456]
If we tried to run translation service on facebook mbart many to many on cpu it take 9 secs to translate, how do we reduce the inference time further

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
