### ISSUE TITLE
Script for squad_v2 for custom data not working

### ISSUE THREAD

**Issue by BatMrE** [huggingface/transformers#10463]
**Environment info**
transformers version: 4.3.3
Platform: Linux-4.15.0-91-generic-x86_64-with-debian-buster-sid
Python version: 3.7.6
Using GPU in script?: True
Using distributed or parallel set-up in script?: True

**Who can help**
@gowtham1997 @patil-suraj 

I am running the script from docs to train and evaluate squad_v2 data with custom arguments.
My dataset is as per the structure of squad format with every keys and values properly.
[colabJson2.zip](https://github.com/huggingface/transformers/files/6063805/colabJson2.zip)

```
python run_qa.py \
  --model_name_or_path bert-base-uncased \
  --version_2_with_negative\
  --train_file=/content/colabJson.json \
  --validation_file=/content/dev-v2.0.json \
  --do_train \
  --do_eval \
  --per_device_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /content/debug_squad_16
```

Output of the script i am getting error as 

```
Traceback (most recent call last):
  File "run_qa.py", line 507, in <module>
    main()
  File "run_qa.py", line 230, in main
    datasets = load_dataset(extension, data_files=data_files, field="data")
  File "/usr/local/lib/python3.7/dist-packages/datasets/load.py", line 750, in load_dataset
    ds = builder_instance.as_dataset(split=split, ignore_verifications=ignore_verifications, in_memory=keep_in_memory)
  File "/usr/local/lib/python3.7/dist-packages/datasets/builder.py", line 740, in as_dataset
    map_tuple=True,
  File "/usr/local/lib/python3.7/dist-packages/datasets/utils/py_utils.py", line 234, in map_nested
    _single_map_nested((function, obj, types, None, True)) for obj in tqdm(iterable, disable=disable_tqdm)
  File "/usr/local/lib/python3.7/dist-packages/datasets/utils/py_utils.py", line 234, in <listcomp>
    _single_map_nested((function, obj, types, None, True)) for obj in tqdm(iterable, disable=disable_tqdm)
  File "/usr/local/lib/python3.7/dist-packages/datasets/utils/py_utils.py", line 172, in _single_map_nested
    return function(data_struct)
  File "/usr/local/lib/python3.7/dist-packages/datasets/builder.py", line 757, in _build_single_dataset
    in_memory=in_memory,
  File "/usr/local/lib/python3.7/dist-packages/datasets/builder.py", line 831, in _as_dataset
    return Dataset(**dataset_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/datasets/arrow_dataset.py", line 250, in __init__
    self.info.features, self.info.features.type, inferred_features, inferred_features.type
ValueError: External features info don't match the dataset:
Got
{'title': Value(dtype='string', id=None), 'paragraphs': [{'qas': [{'question': Value(dtype='string', id=None), 'id': Value(dtype='string', id=None), 'answers': [{'text': Value(dtype='string', id=None), 'answer_start': Value(dtype='int64', id=None)}], 'is_impossible': Value(dtype='bool', id=None), 'plausible_answers': [{'text': Value(dtype='string', id=None), 'answer_start': Value(dtype='int64', id=None)}]}], 'context': Value(dtype='string', id=None)}]}
with type
struct<paragraphs: list<item: struct<context: string, qas: list<item: struct<answers: list<item: struct<answer_start: int64, text: string>>, id: string, is_impossible: bool, plausible_answers: list<item: struct<answer_start: int64, text: string>>, question: string>>>>, title: string>

but expected something like
{'title': Value(dtype='string', id=None), 'paragraphs': [{'context': Value(dtype='string', id=None), 'qas': [{'answers': [{'text': Value(dtype='string', id=None), 'answer_start': Value(dtype='int64', id=None)}], 'question': Value(dtype='string', id=None), 'id': Value(dtype='string', id=None)}]}]}
with type
struct<paragraphs: list<item: struct<context: string, qas: list<item: struct<answers: list<item: struct<answer_start: int64, text: string>>, id: string, question: string>>>>, title: string>
```
In my dataset I don't have any field as **plausible_answers**, **is_impossible** ..
how to match it with expected format when it is already in that format

**Comment by patil-suraj** [comment]
hi @BatMrE 

could you try the new `run_qa.py` example script and let us know if you still face the issue. You can find the new script here 
https://github.com/huggingface/transformers/tree/master/examples/question-answering

**Comment by BatMrE** [comment]
> hi @BatMrE
> 
> could you try the new `run_qa.py` example script and let us know if you still face the issue. You can find the new script here
> https://github.com/huggingface/transformers/tree/master/examples/question-answering

[INFO|tokenization_utils_base.py:1786] 2021-03-02 18:56:09,448 >> loading file https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt from cache at /root/.cache/huggingface/transformers/45c3f7a79a80e1cf0a489e5c62b43f173c15db47864303a55d623bb3c96f72a5.d789d64ebfe299b0e416afc4a169632f903f693095b4629a7ea271d5a0cf2c99
[INFO|tokenization_utils_base.py:1786] 2021-03-02 18:56:09,448 >> loading file https://huggingface.co/bert-base-uncased/resolve/main/tokenizer.json from cache at /root/.cache/huggingface/transformers/534479488c54aeaf9c3406f647aa2ec13648c06771ffe269edabebd4c412da1d.7f2721073f19841be16f41b0a70b600ca6b880c8f3df6f3535cbc704371bdfa4
[INFO|modeling_utils.py:1027] 2021-03-02 18:56:09,548 >> loading weights file https://huggingface.co/bert-base-uncased/resolve/main/pytorch_model.bin from cache at /root/.cache/huggingface/transformers/a8041bf617d7f94ea26d15e218abd04afc2004805632abc0ed2066aa16d50d04.faf6ea826ae9c5867d12b22257f9877e6b8367890837bd60f7c54a29633f7f2f
[WARNING|modeling_utils.py:1135] 2021-03-02 18:56:14,139 >> Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForQuestionAnswering: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[WARNING|modeling_utils.py:1146] 2021-03-02 18:56:14,139 >> Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['qa_outputs.weight', 'qa_outputs.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  1% 3/227 [00:01<02:25,  1.54ba/s]thread '<unnamed>' panicked at 'assertion failed: stride < max_len', /__w/tokenizers/tokenizers/tokenizers/src/tokenizer/encoding.rs:322:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
