### ISSUE TITLE
The described function in docs was not implemented in source code

### ISSUE THREAD

**Issue by yww211** [huggingface/transformers#10469]
https://github.com/huggingface/transformers/blob/0c2325198fd638e5d1f0c7dcbdd8bf7f14c0ff7d/src/transformers/file_utils.py#L1512

The method of `update` in `ModelOutput` described as below,
https://huggingface.co/transformers/main_classes/output.html?highlight=modeloutput#transformers.file_utils.ModelOutput.update
but the source code will raise an exception when try to use it, which disagree with the docs.

**Comment by LysandreJik** [comment]
Ah, indeed! cc @sgugger
