### ISSUE TITLE
The size of CoNLL-2003 is not consistant with the official release.

### ISSUE THREAD

**Issue by h-peng17** [huggingface/transformers#10476]
## Environment info

- `transformers` version:
- Platform: -
- Python version: -
- PyTorch version (GPU?): -
- Tensorflow version (GPU?): -
- Using GPU in script?: -
- Using distributed or parallel set-up in script?: -

### Who can help
@sgugger, @patil-suraj

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: CoNLL-2003

## To reproduce

1. just run the code

## Expected behavior

The official release of CoNLL-2003 is: 
# train 14987
# dev 3466
# test 3684
While CoNLL-2003 in datasets is:
# train 14041
# dev 3250
# test 3453

Wish for your reply~ Thank you!

**Comment by patil-suraj** [comment]
Hi there, 

The training scripts load the dataset using the `datasets` library, so this issue is related to the `datasets` lib, you can open it in that repo https://github.com/huggingface/datasets.

**Comment by h-peng17** [comment]
Thank you!
