### ISSUE TITLE
Fine tune of speaker embeddings model

### ISSUE THREAD

**Issue by karthikgali** [huggingface/transformers#10500]
# 🚀 Feature request

Provide a way to fine tune the X-vector speaker embeddings model using our own custom dataset. (https://huggingface.co/hbredin/SpeakerEmbedding-XVectorMFCC-VoxCeleb)

## Motivation

This will help in finetuning the model for new domain/speakers.

**Comment by LysandreJik** [comment]
Hi! I think this is more of a question for `pyannote` rather than for `transformers`?

**Comment by julien-c** [comment]
cc'ing @hbredin for visibility :)

**Comment by hbredin** [comment]
Thanks @julien-c for the ping.

@karthikgali please open an issue or discussion in [pyannote.audio Github repo](https://github.com/pyannote/pyannote-audio) instead.
