### ISSUE TITLE
Fine tuning a pipeline

### ISSUE THREAD

**Issue by thiziri** [huggingface/transformers#10503]
# 🚀 Feature request

[Already asked](https://github.com/huggingface/transformers/issues/8127)

## Motivation

I would like to fine-tune a pipeline using a model (pre-trained or fine-tuned).

**Comment by LysandreJik** [comment]
Hi! I'm sorry, I don't understand what you mean exactly. A pipeline uses a model and a tokenizer under the hood, do you mean you want to fine-tune the model used underneath, and use that fine-tuned model?

If that is so, it is simple: any model/tokenizer can be loaded in the pipeline via local path/hub identifier. I invite you to read the [documentation of the pipelines](https://huggingface.co/transformers/main_classes/pipelines.html#transformers.pipeline), especially the `model` and `tokenizer` arguments.
