### ISSUE TITLE
'Trainer' object has no attribute 'log_metrics'

### ISSUE THREAD

**Issue by fatihbeyhan** [huggingface/transformers#10507]
I was trying to use run_mlm.py to fine-tune roberta-large with a custom dataset on Google Colab.

!python /content/transformers/examples/language-modeling/run_mlm.py \
    --model_name_or_path roberta-large \
    --train_file /content/traincorpus.txt \
    --validation_file /content/devcorpus.txt \
    --do_train \
    --do_eval \
    --per_device_train_batch_size 2 \
    --output_dir finetunedmodel \
    --overwrite_output_dir True

I am able to train the model however at the end I can not see the evaluation due to an error:

Traceback (most recent call last):
  File "/content/transformers/examples/language-modeling/run_mlm.py", line 442, in <module>
    main()
  File "/content/transformers/examples/language-modeling/run_mlm.py", line 416, in main
    trainer.log_metrics("train", metrics)
AttributeError: 'Trainer' object has no attribute 'log_metrics'

There is nothing extra on colab env. I wasn't getting this error a week ago or something.

**Comment by NielsRogge** [comment]
Hi, this is a duplicate, see #10446
