### ISSUE TITLE
Error in converting tensorflow checkpoints to pytorch 

### ISSUE THREAD

**Issue by kalyanks0611** [huggingface/transformers#1050]
@thomwolf 
 I downloaded tensorflow checkpoints  for domain specific bert model and extracted the zip file into the folder  **pretrained_bert** which contains the following the three files

model.ckpt.data-00000-of-00001
model.ckpt.index
model.ckpt.meta

I used the following code to convert tensorflow checkpoints to pytorch

```
import torch

from pytorch_transformers.modeling_bert import BertConfig, BertForPreTraining, load_tf_weights_in_bert


tf_checkpoint_path="pretrained_bert/model.ckpt"
bert_config_file = "bert-base-cased-config.json"
pytorch_dump_path="pytorch_bert"

config = BertConfig.from_json_file(bert_config_file)
print("Building PyTorch model from configuration: {}".format(str(config)))
model = BertForPreTraining(config)

# Load weights from tf checkpoint
load_tf_weights_in_bert(model, config, tf_checkpoint_path)

# Save pytorch-model
print("Save PyTorch model to {}".format(pytorch_dump_path))
torch.save(model.state_dict(), pytorch_dump_path)
```

I got this error when ran the above code

**NotFoundError: Unsuccessful TensorSliceReader constructor:** Failed to find any matching files for pretrained_bert/model.ckpt

Any help is really appreciated............

**Comment by HansBambel** [comment]
For me it worked to convert checkpoints without specifying the exact checkpoint. So only pointing to the folder of the checkpoint:
`tf_checkpoint_path="pretrained_bert"`
