### ISSUE TITLE
Error in run_squad.py with BartForQuestionAnswering model

### ISSUE THREAD

**Issue by nrjvarshney** [huggingface/transformers#10510]
I am using the  BartForQuestionAnswering model and getting the following error during evaluation 
`Evaluating:   0%|          | 0/315 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "../run_squad.py", line 831, in <module>
    main()
  File "../run_squad.py", line 820, in main
    result = evaluate(args, model, tokenizer, prefix=global_step)
  File "../run_squad.py", line 325, in evaluate
    output = [to_list(output[i]) for output in outputs.to_tuple()]
  File "../run_squad.py", line 325, in <listcomp>
    output = [to_list(output[i]) for output in outputs.to_tuple()]
  File "../run_squad.py", line 73, in to_list
    return tensor.detach().cpu().tolist()
AttributeError: 'tuple' object has no attribute 'detach'`

It works perfectly fine with the bert-base-uncased model but fails in case of BART model.
What could resolve this issue?
Thanks

**Comment by LysandreJik** [comment]
Hello! Could you provide all the information required in the issue template?

Thank you!
