### ISSUE TITLE
Why the positional embeddings in bert are not inplemented by sin/cos as the original paper said? Are these embeddings trainable?

### ISSUE THREAD

**Issue by SeaEagleI** [huggingface/transformers#10511]
https://github.com/huggingface/transformers/blob/948b730f9777174335812cf76de2a9dd9e4cf20e/src/transformers/models/bert/modeling_bert.py#L172

**Comment by NielsRogge** [comment]
BERT uses absolute position embeddings by default. The sin/cos embeddings are from the original Transformer paper IRRC.
