### ISSUE TITLE
Typo in deberta_v2/__init__.py

### ISSUE THREAD

**Issue by cliang1453** [huggingface/transformers#10529]
https://github.com/huggingface/transformers/blob/c503a1c15ec1b11e69a3eaaf06edfa87c05a2849/src/transformers/models/deberta_v2/__init__.py#L31
Should be '' DEBERTA_V2_PRETRAINED_MODEL_ARCHIVE_LIST ''.

**Comment by LysandreJik** [comment]
That's correct! Do you want to open a PR to fix it?
