### ISSUE TITLE
Unable to translate Arabic to many other languages in MBart-50

### ISSUE THREAD

**Issue by lecidhugo** [huggingface/transformers#10520]
## Environment info

- `transformers` version: 4.4.0.dev0
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.7.1+cu101 (True)
- Tensorflow version (GPU?): 2.4.1 (True)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help

@patrickvonplaten
## Information

Model I am using (Bert, XLNet ...): Mbart-50

The problem arises when using:
* [ X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ X] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce
```
# translate Arabic to Hindi
article_ar = "الأمين العام للأمم المتحدة يقول إنه لا يوجد حل عسكري في سوريا."
tokenizer.src_lang = "ar_AR"
encoded_ar = tokenizer(article_ar, return_tensors="pt")
generated_tokens = model.generate(
    **encoded_ar,
    forced_bos_token_id=tokenizer.lang_code_to_id["hi_IN"]
)
tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
```
**Result: ['Secretary of the United Nations says there is no military solution to Syria.']**

## Expected behavior
The result should be in Hindi, but it weirdly it is in English. Arabic --> Hindi is an example. But if you test Arabic -->xx_XX you will obtain the same behavior except for a few ones (such as `fr_XX` or `de_DE`)

**Comment by patil-suraj** [comment]
Hi @lecidhugo 

Thank you for reporting this. Is this for one particular example or is it happening for all examples?

**Comment by lecidhugo** [comment]
Hi @patil-suraj,
Thank you for your reply.
Indeed, it is for all examples and for many languages

**Comment by patil-suraj** [comment]
Thanks. I'll look into it next week.

**Comment by patil-suraj** [comment]
Unstale
