### ISSUE TITLE
BERT as encoder - position ids

### ISSUE THREAD

**Issue by md975** [huggingface/transformers#10523]
Hello,

I have an EncoderDecoderModel.from_encoder_decoder_pretrained which is using BERT as both the decoder and encoder.
I would like to adjust position_ids for the encoder input, however, looking at [this documentation](https://huggingface.co/transformers/model_doc/encoderdecoder.html#transformers.EncoderDecoderModel.forward) it seems like there is no such argument.
How can I do this?
Sorry if this is an obvious question, I'm new to this stuff.
Thanks!

**Comment by LysandreJik** [comment]
Hello! In the documentation you pointed to, you'll see that there is the `kwargs` argument, which accepts any keyword argument. The doc says:

```
(optional) Remaining dictionary of keyword arguments. Keyword arguments come in two flavors:

Without a prefix which will be input as **encoder_kwargs for the encoder forward function.

With a decoder_ prefix which will be input as **decoder_kwargs for the decoder forward function.
```

Have you tried passing `position_ids` to the `__call__` method of your model instantiated with the `EncoderDecoderModel.from_encoder_decoder_pretrained`? It should work!

**Comment by md975** [comment]
Thanks so much!
