### ISSUE TITLE
RAG with RAY workers keep repetitive copies  of knowledge base as  .nfs files until the process is done. 

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#10533]
As mentioned in [this PR](https://github.com/huggingface/transformers/pull/10410), I update the **my_knowledge_dataset**  object all the time. I save the new my_knowledge_dataset in the same place by removing previously saved stuff. But still, I see there are always some hidden files left.  Please check the screenshot below.

![image](https://user-images.githubusercontent.com/16892570/110067455-a0da4880-7dd8-11eb-95cd-5b908c7a04af.png)
![image](https://user-images.githubusercontent.com/16892570/110067527-ccf5c980-7dd8-11eb-9328-7a361f554454.png)

I did some checks and found that these .nfs files being used by RAY. But my local KB is 30GB, so I do not want to add a .nfs file in every iteration. Is there a way to get over this?

@amogkam 
@lhoestq

**Comment by lhoestq** [comment]
I don't know what those .nfs are used for in Ray, is it safe to remove them @amogkam ?
