### ISSUE TITLE
Test/Predict on summarization task

### ISSUE THREAD

**Issue by ZhouyxNLP** [huggingface/transformers#10530]
## Environment info

- `transformers` version: 4.4.0.dev0
- Platform: Linux-5.3.0-53-generic-x86_64-with-glibc2.10
- Python version: 3.8.3
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help

- maintained examples using bart: @patrickvonplaten, @patil-suraj

## Information

Model I am using (Bart):

The problem arises when using:
* [ ] only have train and eval example, do not have test/predict example script
* [ ] my own modified scripts: (give details below)
* [ ] CUDA_VISIBLE_DEVICES=2,3 python examples/seq2seq/run_seq2seq.py \
    --model_name_or_path /home/yxzhou/experiment/ASBG/output/xsum_bart_large/ \
    --do_predict \
    --task summarization \
    --dataset_name xsum \
    --output_dir /home/yxzhou/experiment/ASBG/output/xsum_bart_large/test/ \
    --num_beams 1 \

The tasks I am working on is:
* [ ] CNNDAILYMAIL , XSUM

## Expected behavior

Use the above script to test on CNNDAILYMAIL and XSUM dataset, the program seems will be always stuck at training_step (e.g., 26/709)

Could you please kindly provide a test/predict example script of the summarization task (e.g., XSUM). Thank you so much!

**Comment by NielsRogge** [comment]
Hi,

could you please ask questions related to training of models on the [forum]()?

All questions related to fine-tuning a model for summarization on CNN can be found [here](https://discuss.huggingface.co/search?q=summarization%20cnn) for example.

**Comment by ZhouyxNLP** [comment]
> Hi,
> 
> could you please ask questions related to training of models on the [forum](https://discuss.huggingface.co/)?
> 
> All questions related to fine-tuning a model for summarization on CNN can be found [here](https://discuss.huggingface.co/search?q=summarization%20cnn) for example.

@NielsRogge Oh, thank you for your reminder, that really helped!
