### ISSUE TITLE
Similar issue like #1091 in Blenderbot

### ISSUE THREAD

**Issue by karthikgrama** [huggingface/transformers#10543]
Tokenizer and model are not in sync. I am using "facebook/blenderbot-400M-distill" 

Tokenizer has 8009 base tokens where as model has 8008. 

Could you please help me with this?

`from transformers import BlenderbotTokenizer, BlenderbotForConditionalGeneration

mname = "facebook/blenderbot-400M-distill"

model = BlenderbotForConditionalGeneration.from_pretrained(mname)
tokenizer = BlenderbotTokenizer.from_pretrained(mname, local_files_only=True)

print(len(tokenizer))
print(model.config.to_dict()['vocab_size'])`

Here is the output that I get.
8009
8008

## Environment info

- `transformers` version: 4.3.2
- Platform: Windows-10-10.0.18362-SP0
- Python version: 3.8.6
- PyTorch version (GPU?): 1.7.1+cpu (False)
- Tensorflow version (GPU?): 2.3.1 (False)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

- blenderbot, bart, marian, pegasus, encoderdecoder,  t5: @patrickvonplaten, @patil-suraj

**Comment by patrickvonplaten** [comment]
Do you encounter any errors because of the mismatch in length?
