### ISSUE TITLE
🐛 Bug in attention head mask for cross-attention module in encoder-decoder models

### ISSUE THREAD

**Issue by stancld** [huggingface/transformers#10540]
Currently, encoder-decoder models use either `head_mask` or `decoder_head_mask` for masking attention heads in cross-attention modules. Both cases are not perfectly correct. Furthermore, MHA in cross-attention modules shares the parameters with the decoder, i.e. `shape = (decoder.num_layers, decoder.num_attention_heads)`, therefore, the usage of encoder `head_mask` in the cross-attention module may lead to errors due to the shape mismatch.

<hr>

**My contribution:** I will take care of this issue this weekend.

<hr>

**Reviewers:** @patil-suraj @patrickvonplaten

**Comment by patil-suraj** [comment]
Unstale

**Comment by patrickvonplaten** [comment]
Hey @stancld,

Sorry for being so unresponsive here - I'm happy to change the behavior and provide 3 masks
