### ISSUE TITLE
Dead link to optuna.create_study under hyperparamter_search in Trainer

### ISSUE THREAD

**Issue by jwa018** [huggingface/transformers#10548]
I noticed the hyperlink to the documentation of optuna's create_study under ```kwargs``` in the ```hyperparameter_search``` method of Trainer is outdated. 

https://huggingface.co/transformers/main_classes/trainer.html

### Who can help
Documentation: @sgugger

New URL (I'm guessing): https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.create_study.html
Old (currently used): https://optuna.readthedocs.io/en/stable/reference/alias_generated/optuna.create_study.html#optuna.create_study

**Comment by sgugger** [comment]
Thanks for flagging! Do you want to make a PR to fix it?

**Comment by jwa018** [comment]
> Thanks for flagging! Do you want to make a PR to fix it?

I tried (#10554). Did I do it correctly?

**Comment by sgugger** [comment]
Looks okay to me! Let's just wait to check the tests pass. Thanks! :-)
