### ISSUE TITLE
Dear developer, does transformers have the support to translate Chinese text into English?

### ISSUE THREAD

**Issue by j2538318409** [huggingface/transformers#10558]
# 🚀 Feature request

**Comment by bhadreshpsavani** [comment]
Hi @j2538318409,

I think Mbart model from facebook can do that for you [mbart](https://huggingface.co/facebook/mbart-large-50-many-to-many-mmt), 

You need to specify `zh_CN` as the source language and `en_XX` as the target language.

 This [colab notebook](https://github.com/bhadreshpsavani/UnderstandingNLP/blob/master/MultilingualMBart.ipynb) does translation from English to hindi. You can use the same for doing translation from Chinese to English by modifying `src_lang` and `trg_lang`.

There are other translation models also available in huggingface like [Helsinki-NLP/opus-mt-zh-en](https://huggingface.co/Helsinki-NLP/opus-mt-zh-en).  You can find more details on [huggingface models section](https://huggingface.co/models?pipeline_tag=translation)

**Comment by flozi00** [comment]
https://huggingface.co/transformers/master/model_doc/m2m_100.html

M2M is in master since today, is this what you are looking for ?
