### ISSUE TITLE
The dimension of Feature extraction

### ISSUE THREAD

**Issue by SakerLiu** [huggingface/transformers#10574]
![image](https://user-images.githubusercontent.com/30914380/110243654-4dadf480-7f96-11eb-8a2a-1bff9407c786.png)
![image](https://user-images.githubusercontent.com/30914380/110243672-5999b680-7f96-11eb-91e4-2728099b2418.png)
why this happened?

**Comment by NielsRogge** [comment]
How did you create the `nlp_features` function?

The sequence length is different due to different tokenization.
