### ISSUE TITLE
bug in run_finetune

### ISSUE THREAD

**Issue by dorost1234** [huggingface/transformers#10575]
## Environment info

- `transformers` version: 4.3.3
- Platform: linux
- Python version: 3.7
- PyTorch version (GPU?): 1.8 
- Tensorflow version (GPU?): - 
- Using GPU in script?: -
- Using distributed or parallel set-up in script?: - 

### Who can help

@patrickvonplaten, @patil-suraj

## Information
I am running  run_seq2seq.py getting 

ImportError: cannot import name 'is_offline_mode' from 'transformers.file_utils'

## To reproduce

python run_seq2seq.py

thnaks

**Comment by dorost1234** [comment]
sorry my mistake to use last version of examples

**Comment by kscp123** [comment]
hi how you solved this. i also face this error. i can't find "is_offline_mode"  and "get_full_repo_name" under transformers.utils. i use https://github.com/huggingface/transformers/tree/main/examples/pytorch/summarization

**Comment by patil-suraj** [comment]
This should work if you are using `transformers` master/main

**Comment by BitCalSaul** [comment]
> https://github.com/huggingface/transformers/tree/main/examples/pytorch/summarization

I miss the same issue. How do you solve it?
