### ISSUE TITLE
Import error for class Speech2TextProcessor, Speech2TextTransformerForConditionalGeneration

### ISSUE THREAD

**Issue by amiyamandal-dev** [huggingface/transformers#10572]
## Environment info
- `transformers` version: 4.4.0.dev0
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.8.8
- PyTorch version (GPU?): 1.7.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help

Models:
- Speech2TextProcessor, Speech2TextTransformerForConditionalGeneration @patil-suraj 

## Information

Model I am using (Speech2TextProcessor, Speech2TextTransformerForConditionalGeneration):

The problem arises when using:
* trying to import the model

## To reproduce

1. first install master brach 
2. then try to import the  Speech2TextProcessor, Speech2TextTransformerForConditionalGeneration class then showing import error
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8149e8a8d76d> in <module>
      1 import torch
----> 2 from transformers import Speech2TextProcessor, Speech2TextTransformerForConditionalGeneration
      3 from datasets import load_dataset
      4 import soundfile as sf

ImportError: cannot import name 'Speech2TextProcessor' from 'transformers' (unknown location)
```
## Expected behavior
able to run the code from _https://huggingface.co/facebook/s2t-large-librispeech-asr_ from docs

one suggestion, if any fine-tuning script for s2t-large-librispeech-asr model it would be a great help

thankyou

**Comment by patil-suraj** [comment]
hi @amiyamandal-dev 
Thank you for your interest in `S2T`. It's still a work in progress and not available on master yet. If you want to try it, you could checkout this PR #10175

**Comment by patil-suraj** [comment]
Hey @amiyamandal-dev ,

The model is now available on [master](https://huggingface.co/transformers/master/model_doc/speech_to_text.html)! You could install transformers from the source if you want to try it.
