### ISSUE TITLE
Initialising XLMTokenizer 

### ISSUE THREAD

**Issue by hiyingnn** [huggingface/transformers#1058]
## ❓ Questions & Help
To initialise the XLMTokenizer, both the vocab file and the merges.txt file are needed. If I am pre-training XLM, how do I obtain the merges.txt file?

**Comment by thomwolf** [comment]
To pretrain XLM, you should use the original (PyTorch) codebase and training scripts which are [here](https://github.com/facebookresearch/XLM)
