### ISSUE TITLE
No model card for  roberta-large-finetuned-wsc

### ISSUE THREAD

**Issue by ngoquanghuy99** [huggingface/transformers#10597]
# 🚀 Feature request

## Motivation

I can not finetune this model `roberta-large-finetuned-wsc`, it doesn't have model card.

## Your contribution
Please fix this!

**Comment by LysandreJik** [comment]
Are you talking about this model? https://huggingface.co/mrm8488/roberta-large-finetuned-wsc

**Comment by ngoquanghuy99** [comment]
> Are you talking about this model? https://huggingface.co/mrm8488/roberta-large-finetuned-wsc

Yes, this model i can not call by transformers. So how can i use it?

**Comment by ngoquanghuy99** [comment]
> You can't call it from transformers? Do you get an error?
> It seems I can load it:
> 
> ```python
> >>> from transformers import AutoModelForMaskedLM
> >>> model = AutoModelForMaskedLM.from_pretrained("mrm8488/roberta-large-finetuned-wsc")
> ```

I couldn't load it from "AutoModel". Thanks for your snippet! Anyways, should i finetune this for text classification task by removing Language Modeling head on top? Just for experiments!

**Comment by ngoquanghuy99** [comment]
Oh wow, i don't fine tuned for classification by this way. I directly removed the LM head though. But still thank you Lysandre!

**Comment by LysandreJik** [comment]
Happy to help!
