### ISSUE TITLE
Not able to convert T5 tf checkpoints

### ISSUE THREAD

**Issue by RachitBansal** [huggingface/transformers#10614]
Hi,
I was trying to convert some tf checkpoints for T5 into PyTorch using ```transformers-cli convert```, and am getting the following error:

> Traceback (most recent call last):
  File "/home/william18026/miniconda3/bin/transformers-cli", line 32, in <module>
    service.run()
  File "/home/william18026/miniconda3/lib/python3.7/site-packages/transformers/commands/convert.py", line 158, in run
    raise ValueError("--model_type should be selected in the list [bert, gpt, gpt2, transfo_xl, xlnet, xlm]")
ValueError: --model_type should be selected in the list [bert, gpt, gpt2, transfo_xl, xlnet, xlm]

My initial attempt was with transformers==4.3.3, but then I also tried using the source version (4.4.0dev) and the editable clone, but got the same error with all. T5 seems to have been added to the pipeline in #9654, but for some reason, it's not working at the user (/my) end.

What could I be doing wrong?

**Comment by LysandreJik** [comment]
It seems that T5 was added to the conversion scripts two months ago in https://github.com/huggingface/transformers/pull/9654 as you've mentioned.

However, in your error there is no mention of "t5":
```
ValueError: --model_type should be selected in the list [bert, gpt, gpt2, transfo_xl, xlnet, xlm]
```

But on master it clearly shows there should be one:
```
"--model_type should be selected in the list [bert, gpt, gpt2, t5, transfo_xl, xlnet, xlm, lxmert]"
```

Are you certain you're launching the command in the correct environment? Could you share the result of `transformers-cli env`?

---

Also, this conversion command is far from being complete, I think it could use some of your templating magic @sgugger if you ever feel like it :) 
It isn't high priority as we already have the model-specific conversion scripts.
