### ISSUE TITLE
How to use deepspeed finetune RAG?

### ISSUE THREAD

**Issue by qixintechnology** [huggingface/transformers#10659]
Hi Stas!@stas00 Thanks for your great work! I have a question that is it possible to use deepspeed finetune RAG (finetune_rag.py)? Thanks!

**Comment by stas00** [comment]
Thank you for your kind words, @qixintechnology 

I haven't tried it with RAG, but I don't see any reason why it shouldn't work - if you encounter any problems please open a specific issue with details so that we could reproduce it.
