### ISSUE TITLE
MarianMT - tokenizer.supported_language_codes -> 'NoneType' object has no attribute 'supported_language_codes'

### ISSUE THREAD

**Issue by gagy3798** [huggingface/transformers#10655]
## Environment info
- colab.research.google.com

### Who can help
@patrickvonplaten

Models:
- MarianMT

Examples:
https://huggingface.co/transformers/model_doc/marian.html

## Information
I'm trying to run example code in colab but it fails

`from transformers import MarianMTModel, MarianTokenizer
src_text = [
    '>>fra<< this is a sentence in english that we want to translate to french',
    '>>por<< This should go to portuguese',
    '>>esp<< And this to Spanish'
]

model_name = 'Helsinki-NLP/opus-mt-en-roa'
tokenizer = MarianTokenizer.from_pretrained(model_name)
print(tokenizer.supported_language_codes)
model = MarianMTModel.from_pretrained(model_name)
translated = model.generate(**tokenizer.prepare_seq2seq_batch(src_text, return_tensors="pt"))
tgt_text = [tokenizer.decode(t, skip_special_tokens=True) for t in translated]`

---> 10 print(tokenizer.supported_language_codes)
AttributeError: 'NoneType' object has no attribute 'supported_language_codes'

Could you please provide working translation sample.

**Comment by patil-suraj** [comment]
Hi @gagy3798 

I couldn't reproduce the issue on master and with the latest pypi version as well. What is your transformers version? 
(please always make sure to post the env info when opening an issue)

**Comment by gagy3798** [comment]
Hi @patil-suraj 

please try it on this colab [https://colab.research.google.com/drive/1z9UtSETxVrDhYnH1eN9lyMv2g-YTFNrz?usp=sharing#scrollTo=Daq50BqvdmW3](url)

transformers 4.3.3

**Comment by patil-suraj** [comment]
probably `sentencepiece` is not installed. Please install `sentencepiece` and restart the colab. That should resolve the issue.

**Comment by gagy3798** [comment]
Ok, thank you.
