### ISSUE TITLE
Has anyone reproduced RoBERTa scores on Squad dataset?

### ISSUE THREAD

**Issue by Morizeyao** [huggingface/transformers#1065]
I have been working on and made some modifications to run_squad.py in examples folder and is currently having problem reproduce the scores. 

If we can have help (or even a PR) on RoBERTa in run_squad.py that would be great.

**Comment by cformosa** [comment]
@Morizeyao Were you able to find any answers to this?

**Comment by julien-c** [comment]
Can you give us more info on what you tried and which results you obtained?

**Comment by Morizeyao** [comment]
Sorry I was no longer working with the RoBERTa solution and switched to XLNet. Sadly the RoBERTa tries are overwritten. :(
