### ISSUE TITLE
OSerror, when loading 'wav2vec2-large-xlsr-53' Model of Wav2vec2

### ISSUE THREAD

**Issue by LifaSun** [huggingface/transformers#10696]
## Environment info
- `transformers` version: 4.3.3
- Platform: Linux-4.15.0-29-generic-x86_64-with-glibc2.10
- Python version: 3.8.8
- PyTorch version (GPU?): 1.8.0 (False)
- Tensorflow version (GPU?): not installed (NA)

  @patrickvonplaten

## Information

Model I am using  Wav2vec2.0:

The problem arises when using:

Scipts:
import soundfile as sf
import torch
from transformers import AutoTokenizer, AutoModel,Wav2Vec2ForCTC, Wav2Vec2Tokenizer

tokenizer4 = AutoTokenizer.from_pretrained("facebook/wav2vec2-large-xlsr-53")
model4 = AutoModel.from_pretrained("facebook/wav2vec2-large-xlsr-53")

OSError: 
OSError: Can't load tokenizer for 'facebook/wav2vec2-large-xlsr-53'. Make sure that:

- 'facebook/wav2vec2-large-xlsr-53' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'facebook/wav2vec2-large-xlsr-53' is the correct path to a directory containing relevant tokenizer files

The tasks I am working on is:
* an official wav2vec task: facebook/wav2vec2-large-xlsr-53

## To reproduce
Follow the instructions
https://huggingface.co/facebook/wav2vec2-large-xlsr-53

## Expected behavior

I try to use xlsr model as the pre-trained model to finetune my own ASR model, but the xlsr model, especially tokenizer, can't be loaded smoothly. Could you tell me how to modify it? Thank you very much!

**Comment by flozi00** [comment]
The model doesn't contains the tokenizer and preprocessing files.
Checkout this notebook:
https://huggingface.co/blog/fine-tune-xlsr-wav2vec2

To build your own vocab etc

**Comment by LifaSun** [comment]
@flozi00 Thank you! 

> The model doesn't contains the tokenizer and preprocessing files.
> Checkout this notebook:
> https://huggingface.co/blog/fine-tune-xlsr-wav2vec2
> 
> To build your own vocab etc

**Comment by mmbejani** [comment]
Forget about `transformers.AutoProcessor`. This class is used to load a general `processor` model. By call the constructor of this class you have to submit `feature_extractor` and `tokenizer`, however `Wav2Vec2` just extract the features from raw speech data. Then, there is no `tokenizer` has been defined for it. To load the `processor` you can use `transformers.Wav2Vec2FeatureExtractor` as follow:

```
from transformers import Wav2Vec2FeatureExtractor

processor = Wav2Vec2FeatureExtractor.from_pretrained('facebook/wav2vec2-large-xlsr-53')
```

**Comment by bagustris** [comment]
> Forget about `transformers.AutoProcessor`. This class is used to load a general `processor` model. By call the constructor of this class you have to submit `feature_extractor` and `tokenizer`, however `Wav2Vec2` just extract the features from raw speech data. Then, there is no `tokenizer` has been defined for it. To load the `processor` you can use `transformers.Wav2Vec2FeatureExtractor` as follow:
> 
> ```
> from transformers import Wav2Vec2FeatureExtractor
> 
> processor = Wav2Vec2FeatureExtractor.from_pretrained('facebook/wav2vec2-large-xlsr-53')
> ```

Using this approach, I got segmentation fault on the same wav2vec2-large-xlsr-53 model.
Output:
```bash
Some weights of the model checkpoint at facebook/wav2vec2-large-xlsr-53 were not used when initializing Wav2Vec2Model: ['quantizer.weight_proj.bias', 'project_q.weight', 'project_q.bias', 'quantizer.codevectors', 'quantizer.weight_proj.weight', 'project_hid.bias', 'project_hid.weight']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Processing 24393.wav
Segmentation fault (core dumped)
```
