### ISSUE TITLE
mBART Large-50 MMT provides incorrect translation when the source and target language are the same

### ISSUE THREAD

**Issue by xhlulu** [huggingface/transformers#10693]
mBART Large-50 MMT provides incorrect translation when the source and target language are the same, e.g. when translating from "en_XX" to "en_XX"

## Environment info

- `transformers` version: 4.4.0.dev0
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.8.0+cu101 (False)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

@patrickvonplaten, @patil-suraj

## Information

Model I am using (Bert, XLNet ...): 
`facebook/mbart-large-50-one-to-many-mmt`

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

```python
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast
article_en = "The head of the United Nations says there is no military solution in Syria"
model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-one-to-many-mmt")
tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-one-to-many-mmt", src_lang="en_XX")
model_inputs = tokenizer(article_en, return_tensors="pt")
generated_tokens = model.generate(
    **model_inputs,
    forced_bos_token_id=tokenizer.lang_code_to_id["en_XX"]
)
decoded = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
print(decoded)
```

Returns:
```
['Şeful Naţiunilor Unite declară că nu există o soluţie militară în Siria']
```

## Expected behavior

Should return something in english, preferably the same content as the original input

**Comment by xhlulu** [comment]
@patil-suraj Was this resolved? If so I'll close this issue

**Comment by patil-suraj** [comment]
HI @xhlulu 

I don't think if this is an issue with the model implementation, also the model is not really expected to do well on paraphrasing (which English-English), I've seen few other issues where models output text in the wrong language but it's the same with original model in `fairseq` as well. From my experience, multilingual models tend to do this in few cases.

**Comment by xhlulu** [comment]
Thanks, that makes sense! Glad you clarified it 😊
