### ISSUE TITLE
ru language

### ISSUE THREAD

**Issue by vtrokhymenko** [huggingface/transformers#1069]
which pre-trained model can work for russian language? i want get only vectors

**Comment by vtrokhymenko** [comment]
of course i can use bert aka multi-language but they work very bad  in my mind for ru

**Comment by avostryakov** [comment]
I think XLM models is better than mBERT. There are XLM models for 17 and 100 languages including ru.

**Comment by vtrokhymenko** [comment]
cool
can u help me where i can download pre-trained xlm from ru because [here](https://huggingface.co/pytorch-transformers/pretrained_models.html) i can't find models for RU?

**Comment by vtrokhymenko** [comment]
i think [here](https://github.com/facebookresearch/XLM) i can get pre-trained

**Comment by avostryakov** [comment]
@vtrokhymenko Yes, it's here
