### ISSUE TITLE
Please provide format of the dataset to finetuning wav2vec using run_asr.py script

### ISSUE THREAD

**Issue by vigneshgig** [huggingface/transformers#10705]
Hi @patrickvonplaten, thanks for the great work, could you please provide some examples for the dataset format to train the wav2vec model using run_asr.py script.

**Comment by patrickvonplaten** [comment]
We are organizing a "fine-tuning XLSR-53" event. Check this announcement: https://discuss.huggingface.co/t/open-to-the-community-xlsr-wav2vec2-fine-tuning-week-for-low-resource-languages/4467. Would be awesome if you want to participate :-)
