### ISSUE TITLE
Language model for wav2vec2.0 decoding

### ISSUE THREAD

**Issue by EmreOzkose** [huggingface/transformers#10716]
Hello, I implemented [wav2vec2.0 code](https://huggingface.co/blog/fine-tune-xlsr-wav2vec2) and a language model is not used for decoding. How can I add a language model (let's say a language model which is trained with KenLM) for decoding?

thanks in advance.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

You can ping @patrickvonplaten on the forum as he's the best suited to help you out.

Thanks!

**Comment by EmreOzkose** [comment]
I moved the question to the forum and @patrickvonplaten said that the feature is not supported for now, but will be soon. 
https://discuss.huggingface.co/t/language-model-for-wav2vec2-0-decoding/4434

**Comment by patrickvonplaten** [comment]
I'm now working on this topic full time. 

We will most likely foster a closer collaboration between [pyctcdecode](https://github.com/kensho-technologies/pyctcdecode) and Transformers. [Here](https://github.com/patrickvonplaten/Wav2Vec2_PyCTCDecode) is a github repo that shows how to use `pyctcdecode` with Wav2Vec2 for LM supported decoding. It works quite well with KenLM.
