### ISSUE TITLE
Is any possible with pipeline for using local model?

### ISSUE THREAD

**Issue by ahnz7** [huggingface/transformers#10713]
Hallo
I have fine tuned a model in my local PC. I have read the Doc for Pipeline to search a way to use local model in Pipeline. But didn't find. Someone who knows how should I do?

**Comment by NielsRogge** [comment]
As mentioned in the docs, you can either provide a model identifier from the hub or a model that inherits from `PreTrainedModel` or `TFPreTrainedModel`. 

So suppose you have fine-tuned a model and stored it into a variable called model, then you can initialize a corresponding pipeline by providing this model variable at initialization.

**Comment by ahnz7** [comment]
> docs

Thanks a lot.
