### ISSUE TITLE
Pegasus-Large Question

### ISSUE THREAD

**Issue by karrtikiyer** [huggingface/transformers#10715]
Is [Pegasus Large model checkpoint](https://huggingface.co/google/pegasus-large) trained on any downstream task? Or is it only trained on pre-training task of gap sentence?

**Comment by patil-suraj** [comment]
`pegasus-large` is a pre-trained checkpoint. It's not fine-tuned on downstream task. The finetuned checkpoint name will have the name of the datsets in them. 

Also please the [forum](https://discuss.huggingface.co/) to ask such questions.

Thanks.
