### ISSUE TITLE
Multi-node training with the latest transformers/examples code

### ISSUE THREAD

**Issue by phqtuyen** [huggingface/transformers#10729]
Hi,

I am trying to follow the instructions on how to use the examples from [https://huggingface.co/transformers/examples.html] and I notice there is a difference between version 4.3 and 1.2 in the distributed training session. In the older version it seems that it supports multi-node training with 
"    --node_rank=$THIS_MACHINE_INDEX \
    --master_addr="192.168.1.1" \
    --master_port=1234 run_bert_classifier.py \"
  But these options no longer exist in the latest tutorial. Does the latest version still support multi-node training? Thanks.

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
I'm unsure what you think is not supported. Launching any of the example scripts with 
```
python -m torch.distributed.launch --nproc_per_node=xxx \
   --node_rank=$THIS_MACHINE_INDEX \
   --master_addr="192.168.1.1" \
   --master_port=1234 \
   run_xxx.py
```
is going to work.

**Comment by phqtuyen** [comment]
Hi @sgugger , thank you for your answer. My understanding is that "--nproc_per_node" is the number of gpus will be used for the launched process? Also, if I want to launch another training node, I assume I will just run the same command with "node_rank=1"?

**Comment by sgugger** [comment]
Yes, that is the number of GPUs.

You can refer to the [PyTorch documentation](https://pytorch.org/docs/stable/distributed.html#launch-utility) for all the arguments of the PyTorch launcher as all the example scripts are fully compatible with it. You will also need to pass `--nnodes=$NUMBER_OF_NODES` for completeness.

**Comment by phqtuyen** [comment]
Thanks, I am able to make it work now.

**Comment by hamid-ramezani** [comment]
Hi @sgugger , I have the same issue. I'm trying to run the following script from two nodes (with different `node_rank`), but training is not going to start. 

`  python -m torch.distributed.launch nnode \
      --nproc_per_node=$nproc_per_node \
      --nnodes=2 \
      --node_rank=0 \
      --master_addr="192.168.1.1" \
      --master_port=1234  run_clm.py \
      --model_name_or_path gpt2 \
      --block_size 256 \
      --dataset_name wikitext \
      --dataset_config_name wikitext-2-raw-v1 \
      --do_train \
      --do_eval \
      --overwrite_output_dir \
      --num_train_epochs 1 \
      --output_dir /tmp/test-clm
`


Can you please let me know if the above script seems fine?
