### ISSUE TITLE
Train tokenizer for Deberta

### ISSUE THREAD

**Issue by alexvaca0** [huggingface/transformers#10723]
Hi, I would like to know how can I train a DeBERTa tokenizer. From the paper I saw it uses BPETokenizer, but the BPETokenizer from huggingface/tokenizers doesn't work for this. Could you recommend me another implementation or library or a correct configuration for huggingface/tokenizers implementation to be able to train a DeBERTa model from scratch?

**Comment by NielsRogge** [comment]
HuggingFace has another library called tokenizers especially for this.

**Comment by cronoik** [comment]
Currently, the training of Deberta Tokenizer is not supported directly by huggingface. Of course, you can create the required files by yourself from BPETokenizer training output, but you could also simply wait until #10703 is merged into the master branch and released. :)

**Comment by alexvaca0** [comment]
How would be the process of creating the required files from the BPETokenizer training output? @cronoik I'd really appreciate a little bit of explanation, as I tried to do so and I failed.

**Comment by cronoik** [comment]
You can save me a lot of time by simply using the mentioned patch above. Just copy the DebertaTokenizer class to your runtime.
