### ISSUE TITLE
load wav2vec model from local path

### ISSUE THREAD

**Issue by roboticsai** [huggingface/transformers#10738]
I'm trying to run the wav2vec based ASR on my machine.  This is my code:
```
import soundfile as sf
import torch
from transformers import Wav2Vec2ForMaskedLM, Wav2Vec2Tokenizer

# load pretrained model
cp = "./my_model_directory/wav2vec_small.pt"
tokenizer = Wav2Vec2Tokenizer.from_pretrained(cp)
model = Wav2Vec2ForMaskedLM.from_pretrained(cp)

# load audio
audio_input, _ = sf.read("/home/robot/Music/dinesh.flac")

# transcribe
input_values = tokenizer(audio_input, return_tensors="pt").input_values
logits = model(input_values).logits
predicted_ids = torch.argmax(logits, dim=-1)
transcription = tokenizer.batch_decode(predicted_ids)[0]
print(transcription)

```
Here cp is the path to the wav2ved local model file. But when i try to run this i'm getting error;
`- or './my_model_directory' is the correct path to a directory containing relevant tokenizer files`
Here when i use the model present in the cloud eg. cp = "facebook/wav2vec2-base-960h". This works perfectly. 
Isn't this possible to run the transformers wav2vec without cloud?

**Comment by patil-suraj** [comment]
hi @roboticsai 

`from_pretrained` expects path of the directory where it can find `config.json` and `pytorch_model.bin` files. It seems that you haven't saved the model using `save_pretrained`. 

To use `from_pretrained`, the model should be saved using `save_pretrained` method.
