### ISSUE TITLE
run_clm.py does not work with any other block_size other than 1024

### ISSUE THREAD

**Issue by sytelus** [huggingface/transformers#10732]
**Note:** This issue can be fixed with one character change as described in last section.

## Environment info
- `transformers` version: 4.4.0.dev0
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.8.5
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
- maintained examples (not research project or legacy): @sgugger, @patil-suraj

## Information

Model I am using (Bert, XLNet ...): GPT2

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: Causal language modelling
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Use GPT based model which has block_size different than 1024
2. Try to train it or fine tune with run_clm.py setting setting block_size in data_args.

In GPU mode, you will get following error:
```
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

In CPU mode, you will get following error:

```
index out of range in self
```

## Expected behavior
Above error should not occur.

## Cause and Proposed Fix

The issue is because block_size on [line 337](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_clm.py#L337) always get set to 1024 because of wrong indentation:

```
    if data_args.block_size is None:
        block_size = tokenizer.model_max_length
        if block_size > 1024:
            logger.warn(
                f"The tokenizer picked seems to have a very large `model_max_length` ({tokenizer.model_max_length}). "
                "Picking 1024 instead. You can change that default value by passing --block_size xxx."
            )
        block_size = 1024 # <<< THIS LINE NEEDS TO BE INTENDED!!!
```
 So just tabbing that line should fix the issue.

**Comment by sgugger** [comment]
Indeed! Would you mind making a PR with that change since you found the correct fix?

**Comment by sytelus** [comment]
Sure, I'll get that prepared!
