### ISSUE TITLE
Fix log message for training from checkpoint with global step

### ISSUE THREAD

**Issue by ioana-blue** [huggingface/transformers#10731]
# 🚀 Feature request

I think the log message here is wrong:

https://github.com/huggingface/transformers/blob/master/src/transformers/trainer.py#L978

I think it should read something along these lines:

```
logger.info(
                    f"  Will skip the first {epochs_trained} epochs then the first {steps_trained_in_current_epoch} "
                    "batches in the current epoch {epochs_trained + 1}."
                )
```

The batches that are skipped are not skipped in the first epoch since the training was already done for `epochs_trained`. As the variable name indicates, the training is going to skip the steps already trained in the current epoch. The current epoch is `epochs_trained + 1`. 

## Motivation

The log message was confusing. I went and traced the code to ensure that it does the right skipping (which I think it does).

**Comment by sgugger** [comment]
Yes, that sounds clearer. Would you mind making a PR with this?

**Comment by ioana-blue** [comment]
Will make time this week.
