### ISSUE TITLE
Tokenizer becomes very slow after adding new tokens

### ISSUE THREAD

**Issue by shauli-ravfogel** [huggingface/transformers#10739]
## Environment info

- `transformers` version: 4.1.1
- Platform: Linux-5.4.0-58-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.9
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): 2.3.1 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@LysandreJik

## Information

Hi,

When I am trying to add a large number (50k) new tokens to BERT's tokenizer, the tokenizer becomes very slow, taking 29 seconds to tokenize a single short sentence.

## To reproduce

```
from transformers import BertTokenizer
import time

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

new_tokens = ["aaa"+str(i) for i in range(50000)]
tokenizer.add_tokens(new_tokens) # takes some time

sentence = "a short sentence."
start = time.time()
tokenizer.tokenize(sentence)
print(time.time() - start)

> 29.049
```

**Comment by shauli-ravfogel** [comment]
This happens since the added tokens are automatically added to the list `unique_no_split_tokens`, which is iterated over in the function `split_on_tokens`. A workaround is to manually remove the added tokens from `unique_no_split_tokens`.

**Comment by LysandreJik** [comment]
Hey @shauli-ravfogel, this should have been fixed on `master`. Can you try installing from source and let me know if it works better?
