### ISSUE TITLE
Issues with MODEL_FOR_MASKED_LM_MAPPING.keys(), and transformer.utils.check_min_version()

### ISSUE THREAD

**Issue by RasmusEdvardsen** [huggingface/transformers#10747]
Hey,

I just recently wanted to pre-train on top of a BERT model, and ran into some issues. When I run `python run_mlm.py`,
I get the following error:
```
Traceback (most recent call last):
  File "run_mlm.py", line 46, in <module>
    from transformers.utils import check_min_version
ImportError: cannot import name 'check_min_version' from 'transformers.utils' (/PATH/TO/site-packages/transformers/utils/__init__.py)
```
https://github.com/huggingface/transformers/blob/d3d388b934ef515e96246ba643c924d675f6515d/examples/language-modeling/run_mlm.py#L46

After commenting out that line, and it's import (I know, shame on me), I get the following error:
```
Traceback (most recent call last):
  File "run_mlm.py", line 53, in <module>
    MODEL_CONFIG_CLASSES = list(MODEL_FOR_MASKED_LM_MAPPING.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```
https://github.com/huggingface/transformers/blob/d3d388b934ef515e96246ba643c924d675f6515d/examples/language-modeling/run_mlm.py#L54

Tried with python 3.7.10 and 3.8.3

Thanks

**Comment by LysandreJik** [comment]
Hello! Have you checked the ["Important note" at the top of the examples README](https://github.com/huggingface/transformers/tree/master/examples#important-note)? 

Did you get this error with a source install?

**Comment by RasmusEdvardsen** [comment]
@LysandreJik that does the trick - I'll be more thorough in the future with my reading :)
