### ISSUE TITLE
BigBird

### ISSUE THREAD

**Issue by slvcsl** [huggingface/transformers#10740]
## Environment info
- `transformers` version: 4.4.0.dev0
- Platform: Linux-5.3.0-64-generic-x86_64-with-glibc2.30
- Python version: 3.9.2
- PyTorch version (GPU?): 1.8.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: Y
- Using distributed or parallel set-up in script?: N

### Who can help
@patrickvonplaten, @patil-suraj (guessing)
## Information

Model I am using **BigBird**:

The problem arises when using: the official example scripts: **seq2seq**

The tasks I am working on is: the official **BigPatent** dataset

## To reproduce
I'm trying to use BigBird for a summarization task (on the BigPatent dataset). I'm using the official seq2seq script, which I run as (all lengths/batches are small for testing)

```
python run_seq2seq.py \
    --model_name_or_path google/bigbird-roberta-base \
    --dataset_name big_patent \
    --max_source_length 3 \
    --max_target_length 3 \
    --val_max_target_length 3 \
    --do_eval --do_predict \
    --per_gpu_train_batch_size 1 \
    --per_gpu_eval_batch_size 1 \
    --num_train_epochs 1 \
    --output_dir tmp 
```

However, I get the following error message:
```
Traceback (most recent call last):
  File "/home/scasola/factuality/factuality/transformers/examples/seq2seq/run_seq2seq.py", line 657, in <module>     
    main()
  File "/home/scasola/factuality/factuality/transformers/examples/seq2seq/run_seq2seq.py", line 344, in main
    config = AutoConfig.from_pretrained(
  File "/home/scasola/anaconda3/envs/factuality/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 382, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
KeyError: 'big_bird'
```

**Comment by patil-suraj** [comment]
hi @slvcsl 

`BigBird` is till WIP and not yet added into the lib,. You can follow the progress here #10183

**Comment by slvcsl** [comment]
Thank you for your response. I'll check it out!
