### ISSUE TITLE
Online decoding for ASR

### ISSUE THREAD

**Issue by arkadyark** [huggingface/transformers#10755]
# 🚀 Feature request

Are there plans to implement online decoding for the speech recognition models such as wav2vec2 and XLSR? More specifically, to be able to receive audio in short chunks, and output partial transcripts as they become available.

## Motivation

Many use cases are covered by the current wav2vec2 model in the library, involving batch recognition of pre-recorded text. However for an online application that wanted to continuously recognize speech on a live input stream, this may not be sufficient.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

cc @patrickvonplaten 

Thanks!

**Comment by arkadyark** [comment]
Sure, no problem, sorry about that. There seems to be a typo in the forum link - for anybody reading this in the future here are the [forums:](https://discuss.huggingface.co/)
