### ISSUE TITLE
Even slower when using multiple gpus with sharded_ddp

### ISSUE THREAD

**Issue by yana-xuyan** [huggingface/transformers#10758]
## Environment info

- `transformers` version: 4.2.2
- Platform: Linux-3.10.0-1062.el7.x86_64-x86_64-with-centos-7.7.1908-Core
- Python version: 3.7.10
- PyTorch version (GPU?): 1.8.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: True
- Using distributed or parallel set-up in script?: True

### Who can help

Library:
- trainer: @sgugger

 -->

## Information

Model I am using (Bert, XLNet ...): facebook/bart-large-cnn

## To reproduce

When I was trying to use sharded_ddp and multiple GPUs to accelerate the training process, my command I used is as follows:

CUDA_VISIBLE_DEIVCES=6,7 python -m torch.distributed.launch --nproc_per_node=2 finetune_trainer.py \
--sharded_ddp --[other_args]

However, the experiment even took a longer time than the experiment using a single GPU. May I ask which part I did was wrong?

**Comment by sgugger** [comment]
`--sharded_ddp` is not there to accelerate your training, it's there to save GPU memory (for very large models) at some cost on the training time. So if you can finetune on one GPU, you should definitely use this option.

**Comment by dorost1234** [comment]
@sgugger  as long as I know sharded_ddp is only for distributed training, not sure why you have suggested to use sharded_ddp on one GPU?

**Comment by sgugger** [comment]
I have not suggested that. I have said to just fine-tune your model on one GPU without any kind of DDP (so no `--sharded_ddp`). It does not make any sense to use this option if your model and its training can fit on one GPU as it is there to reduce GPU memory, not speed up training.

**Comment by dorost1234** [comment]
thanks a lot, now I understood what you meant.
