### ISSUE TITLE
Bug in multi-gpu training setting max_iters 

### ISSUE THREAD

**Issue by dorooddorood606** [huggingface/transformers#10768]
## Environment info

- `transformers` version: 4.3.3
- Platform:
- Python version: 3.8
- PyTorch version (GPU?): 1.8
- Tensorflow version (GPU?): - 
- Using GPU in script?: yes 
- Using distributed or parallel set-up in script?: yes 

### Who can help

 trainer: @sgugger

## Information

I am training T5 model using the command in the repo on 4 GPUs in a distributed way, the issue arises that if one set max_iters then the number of iterations with 4 GPUs is not divided by 4 anymore, only one get speed up if max_iters is not set, and this looks like this is a bug. 

## To reproduce

Please run 
python -m torch.distributed.launch \
    --nproc_per_node 8 \
    examples/seq2seq/run_summarization.py \
    --model_name_or_path t5-small \
    --do_train \
    --do_eval \
    --dataset_name xsum \
    --output_dir /tmp/tst-summarization \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --overwrite_output_dir \
    --predict_with_generate \
    --max_train_samples 500 \
    --max_val_samples 500
   --max_iters 100 

compare the results with the case you run on 1 GPU, both would have the same number of iterations to get completed once running which is not correct

**Comment by sgugger** [comment]
There is no `--max_iters` argument in the `run_summarization` script, so I'm not sure what you're referring.

**Comment by dorooddorood606** [comment]
Hi
I apologize for the typo, this is max_steps, if you set it and run a code
in a distributed way and compare it with non-distributed way, the number of
steps would not differ, but if you try with setting max_train_epochs, you
would see less number of iterations for training, meaning that the code is
correctly setting the parameters. thanks

**Comment by sgugger** [comment]
Yes, `max_steps` is the number of training steps, so whether you run on one or several GPUs, you will do that number of training steps. That is the intended behavior and it is not a bug.
 
`num_epochs` is the number of training epochs. Depending on your number of GPUs you will not have the same number of training steps per epoch (as long as you keep `per_device_train_batch_size` the same) so you will not train for the same number of total steps.

**Comment by dorooddorood606** [comment]
Hi
thanks for the response, still to me if a user needs max_steps on multiple
gpus, it needs to become a smaller number as this divides per number of
gpus, similar to number of epochs.
