### ISSUE TITLE
How to interpret fine-tuned model results and use model

### ISSUE THREAD

**Issue by zakerytclarke** [huggingface/transformers#10784]
Hello,

Apologies if this is the wrong forum to ask these kinds of questions, but I was unable to find this in the documentation.

I fine-tuned a seq2seq model on my custom dataset using the tutorial found here: https://github.com/huggingface/transformers/tree/master/examples/seq2seq

I am trying to find out the F1 and EM accuracy for the fine-tuned model, but am not sure how to interpret the output. I've attached a link to the training's output below:
https://github.com/zakerytclarke/transformers/tree/master/modelResults
```
{
    "epoch": 3.0,
    "eval_gen_len": 55.7429,
    "eval_loss": 2.063843250274658,
    "eval_mem_cpu_alloc_delta": 1998448,
    "eval_mem_cpu_peaked_delta": 638828,
    "eval_rouge1": 33.8505,
    "eval_rouge2": 13.1365,
    "eval_rougeL": 27.8332,
    "eval_rougeLsum": 31.5921,
    "eval_runtime": 119.8097,
    "eval_samples": 35,
    "eval_samples_per_second": 0.292
}
```
Can you point me to documentation about how to interpret these results and how I can load my fine-tuned model in order to evaluate it on a new piece of text?

Thanks for your help,
--Zak

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

@patrickvonplaten @stas00 

Thanks!

**Comment by zakerytclarke** [comment]
@LysandreJik Thanks for pointing me in the right direction, I've moved the post over to the forum.
