### ISSUE TITLE
HerbertTokenizer doesn't work on version 3.5.1

### ISSUE THREAD

**Issue by Zhylkaaa** [huggingface/transformers#10790]
## Environment info

- `transformers` version: 3.5.1
- Platform: MacOS X, Linux
- Python version: 3.7
- PyTorch version (GPU?): 1.6.0

## Information

Model I am using (Bert, XLNet ...): allegro/herbert-base-cased

I tried to use official script on model hub page with transformers version 3.5.1. Week ago it worked just fine, but now I am getting error listed below.
@rmroczkowski maybe you have some information on this topic, I saw some new commits on model hub, but they shouldn't change anything
 
For latest version it works fine with AutoTokenizers (EDIT: only version 4.4 works, I tasted version 3.5.1, 4.0.0, 4.3 and got same error)

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)
I tried importing AutoTokenizers and HerbertTokenizer, but got the same error 
`OSError: Can't load tokenizer for 'allegro/herbert-base-cased'. Make sure that:

- 'allegro/herbert-base-cased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'allegro/herbert-base-cased' is the correct path to a directory containing relevant tokenizer files`

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. install transformers 3.5.1
2. try to use official script from https://huggingface.co/allegro/herbert-base-case

## Expected behavior

tokenizer loads and works

**Comment by Zhylkaaa** [comment]
I guess this is related to URL issue #10744 ? and one should change model URL

**Comment by Zhylkaaa** [comment]
I resolved this by updating URL's to models, this is my current code:
```PRETRAINED_VOCAB_FILES_MAP = {
    "vocab_file": {"allegro/herbert-base-cased": "https://huggingface.co/allegro/herbert-base-cased/resolve/main/vocab.json"},
    "merges_file": {"allegro/herbert-base-cased": "https://huggingface.co/allegro/herbert-base-cased/resolve/main/merges.txt"},
}``` 
Is there a way to fix this to maintain backward compatibility? @LysandreJik

**Comment by julien-c** [comment]
Cross-posting the Forum thread: https://discuss.huggingface.co/t/delete-organizations-models-from-the-hub/954/40
