### ISSUE TITLE
Truncated words on GPT-2 output

### ISSUE THREAD

**Issue by Vova-B** [huggingface/transformers#10798]
Hi! I use the GPT-2 model for the seq2seq task, but unfortunately, at the output of the model, words are cut off and sentences are not added, how can I make the model end sentences at the output and not cut off words? (increasing the maximum length does not correct the situation)
P.S.
I'm sorry, this question is probably very stupid, but I just can't figure it out.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
