### ISSUE TITLE
How much vRAM should I have for fine tuning DeBERTa v2 xxlarge?

### ISSUE THREAD

**Issue by ngoquanghuy99** [huggingface/transformers#10803]
I'm fine tuning DeBERTa v2 xxlarge with 1.5B parameters on Nvidia Tesla T4 (16GB vRAM) and it returns "CUDA out of memory".
How much vRAM is enough? 
@LysandreJik

**Comment by flozi00** [comment]
I don't know the answer, but hoping that it works after this PR got merged https://github.com/huggingface/transformers/pull/10753

Do you already use deepspeed ?

**Comment by ngoquanghuy99** [comment]
No, i did not
