### ISSUE TITLE
Domain adaptation 

### ISSUE THREAD

**Issue by lematmat** [huggingface/transformers#10812]
Hi all,

I'm just wondering how to do model adaptation of pre-trained Camembert model on my custom dataset ?

I haven't found any information in Transformers documentation.

Best regards,

Lematmat
## Environment info

- `transformers` version:4.4.0
- Platform:Jupyter Notebook
- Python version:3.7
- PyTorch version (GPU?):1.8, no GPU
- Tensorflow version (GPU?):
- Using GPU in script?:no
- Using distributed or parallel set-up in script?:no

 -->

## Information

Model I am using (Bert, XLNet ...): Camembert

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!

**Comment by lematmat** [comment]
Thank you very much.
I will contact the forum.
Regards,
lematmat
