### ISSUE TITLE
JSONLINES support on examples/seq2seq/run_translation.py 

### ISSUE THREAD

**Issue by HeroadZ** [huggingface/transformers#10820]
## Environment info

- `transformers` version:
- Platform: windows 10 
- Python version: 3.8
- PyTorch version (GPU?): 1.8.0
- Using GPU in script?: yes, tesla v100
- Using distributed or parallel set-up in script?: no

### Who can help

@sgugger @stas00 @LysandreJik
## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

It is said in the seq2seq READ.me that 
> The task of translation supports only custom JSONLINES files

However, in the line 202, the extension of file should be `.json`
```py
if self.train_file is not None:
    extension = self.train_file.split(".")[-1]
    assert extension == "json", "`train_file` should be a json file."
```

Even if I changed it to 
```py
assert extension in ("json", "jsonl")
```

it throws another error, which says that there's no jsonl process file in library `datasets`

```py
Traceback (most recent call last):
  File "/home/zchelllo/anaconda3/envs/ex/lib/python3.8/site-packages/datasets/load.py", line 323, in prepare_module
    local_path = cached_path(file_path, download_config=download_config)
  File "/home/zchelllo/anaconda3/envs/ex/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 274, in cached_path
    output_path = get_from_cache(
  File "/home/zchelllo/anaconda3/envs/ex/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 614, in get_from_cache
    raise FileNotFoundError("Couldn't find file at {}".format(url))
FileNotFoundError: Couldn't find file at https://raw.githubusercontent.com/huggingface/datasets/master/datasets/jsonl/jsonl.py

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zchelllo/anaconda3/envs/ex/lib/python3.8/site-packages/datasets/load.py", line 335, in prepare_module
    local_path = cached_path(file_path, download_config=download_config)
  File "/home/zchelllo/anaconda3/envs/ex/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 274, in cached_path
    output_path = get_from_cache(
  File "/home/zchelllo/anaconda3/envs/ex/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 614, in get_from_cache
    raise FileNotFoundError("Couldn't find file at {}".format(url))
FileNotFoundError: Couldn't find file at https://raw.githubusercontent.com/huggingface/datasets/master/datasets/jsonl/jsonl.py

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/seq2seq/run_translation.py", line 562, in <module>
    main()
  File "examples/seq2seq/run_translation.py", line 295, in main
    datasets = load_dataset(extension, data_files=data_files)
  File "/home/zchelllo/anaconda3/envs/ex/lib/python3.8/site-packages/datasets/load.py", line 707, in load_dataset
    module_path, hash, resolved_file_path = prepare_module(
  File "/home/zchelllo/anaconda3/envs/ex/lib/python3.8/site-packages/datasets/load.py", line 343, in prepare_module
    raise FileNotFoundError(
FileNotFoundError: Couldn't find file locally at jsonl/jsonl.py, or remotely at https://raw.githubusercontent.com/huggingface/datasets/master/datasets/jsonl/jsonl.py.
The file is also not present on the master branch on github.
```

Is this part in the stage of dev now? I think it is related to [#1943](https://github.com/huggingface/datasets/pull/1943)
Could you add the original csv support before this implementation is over?
Thanks in advance!

**Comment by sgugger** [comment]
I think you just have to name your file with a ".json" extension for the script to work.

There is no support for other formats that will be added to this script as it's not easy to add the csv format while continue to support all the translation datasets in Datasets. You should just tweak the data processing of your example (for instance by doing the same as in `run_summarization`) to your needs if you need to use a csv file.

**Comment by HeroadZ** [comment]
Thank you very much! It works. 
Because the extension for JSONLINES format is `jsonl`, it's better to explain it in the readme.

**Comment by stas00** [comment]
This actually might be a good idea to change the extension to `.jsonl` to make it less ambiguous and it would require no special documentation then.

**Comment by bricksdont** [comment]
Currently, running https://github.com/huggingface/transformers/blob/main/examples/pytorch/translation/run_translation.py with a custom JSON dataset still fails if the file extension is `jsonl`.

The script itself has a check for file extensions that incorrectly accepts `jsonl`:

https://github.com/huggingface/transformers/blob/main/examples/pytorch/translation/run_translation.py#L238
