### ISSUE TITLE
Getting tokenization ERROR while running run_generation.py 

### ISSUE THREAD

**Issue by realdiganta** [huggingface/transformers#1082]
## 🐛 Bug

Model I am using (GPT-2....):

Language I am using the model on (English):

The problem arise when using:
* [ ] the official example scripts: (give details)
pytorch-transformers/examples/run_generation.py \

The tasks I am working on is:
* [ ] my own task or dataset: (give details)
-> just simple next sentence prediction. My actual text 'Saw her in the park yesterday'

## To Reproduce

1.
2.
3.

Error message I got is
ERROR - pytorch_transformers.tokenization_utils -   Using sep_token, but it is not set yet.

And then the next sentence that it predicts has nothing to do with my given sentence.

## Expected behavior

-> Not give the error. and work like it is supposed to,

## Environment

* OS: Google Colab
* Python version:
* PyTorch version:
* PyTorch Transformers version (or branch):
* Using GPU ? Yes
* Distributed of parallel setup ?
* Any other relevant information:

## Additional context

I am pretty sure that the problem is not so hard to solve. But I am a noob here. So please forgive me .

**Comment by LysandreJik** [comment]
Hi! Yes currently there's a small issue with the tokenizer that outputs this warning during the decoding of the sentence. It will be fixed very shortly. 

It won't affect your training however, as it is only a warning :)
