### ISSUE TITLE
ReformerEmbedding unclear behavior

### ISSUE THREAD

**Issue by fostiropoulos** [huggingface/transformers#10825]
## Environment info
- `transformers` version: 4.3.3
- Platform: Linux-4.15.0-136-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help
@patrickvonplaten
## Information

Model I am using (Bert, XLNet ...): Reformer

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: MNIST

## To reproduce

1. Leave max_position_embeddings undefined or different than axial_pos_embedding shape
2. Observe the assert get triggered for large sequence lengths (within limit of axial_pos_embedding) https://github.com/huggingface/transformers/blob/master/src/transformers/models/reformer/modeling_reformer.py#L255

## Expected behavior

* No assert

## Additional Details:

`max_position_embeddings` is only used by `PositionEmbeddings`, thus if we provide `axial_pos_embds`  in the configuration, the `max_position_embeddings` will be not used for positional embedding. Moreover it is considered for factorizing `num_buckets` in `LSHSelfAttention` layer. 

Thus in a scenario of using axial positional embedding, both the assert check will be useless as well as the [bucket factorization](https://github.com/huggingface/transformers/blob/master/src/transformers/models/reformer/modeling_reformer.py#L711)

**Comment by patrickvonplaten** [comment]
I think I don't fully agree here...`max_position_embeddings` is important even if `axial_pos_embedding` is used. If a user makes use of `axial_pos_embeddings` then `max_position_embeddings` is clearly defined by the tuple of `axial_pos_embeddings`. IMO, it's important that the user fully understands how `axial_pos_embeddigs` work and should therefore also set `max_position_embeddigns`
