### ISSUE TITLE
transformers import error

### ISSUE THREAD

**Issue by KYUNGGUK-CHOI** [huggingface/transformers#10864]
## Environment info

- `transformers` version: 4.4.2
- Platform: MACOS
- Python version: Python 3.6.13
- PyTorch version (GPU?): 1.8.0 (cpu)
- Tensorflow version (GPU?): tensorflow-cpu  2.4.1
- Using GPU in script?: no
- Using distributed or parallel set-up in script?:no

### Who can help

@LysandreJik 

I setup my conda envs as below
 
<img width="470" alt="스크린샷 2021-03-23 오후 8 57 52" src="https://user-images.githubusercontent.com/55866896/112142854-70890b80-8c1a-11eb-8752-14857d4529e7.png">

and there are all librarys needed list in !pip3 list 

<img width="310" alt="스크린샷 2021-03-23 오후 9 05 00" src="https://user-images.githubusercontent.com/55866896/112143640-84813d00-8c1b-11eb-8e6c-735d0a57e1c2.png">

but whenever I try to import BertTokenizer(from transformers import BertTokenizer), ImportError occurs.

<img width="662" alt="스크린샷 2021-03-23 오후 8 59 13" src="https://user-images.githubusercontent.com/55866896/112142993-a0381380-8c1a-11eb-8ec1-722d71a947ed.png">

I tried all process in google colab , it works well 
I have no idea why it does not work in my Macbook local environment

please help me

**Comment by LysandreJik** [comment]
Hello! I would guess something is wrongly setup in your local environment; especially it it works in colab! Are you sure you're using the `python` from the same environment as your `pip3`?
