### ISSUE TITLE
transformers.models.auto.tokenization_auto

### ISSUE THREAD

**Issue by Sankalp1233** [huggingface/transformers#10874]
I installed the version transformers 3.5.1 to get the version in GitHub using !pip3 install transformers==3.5.1 and !pip3 install transformers but then when I try to install SentenceTransofrmer using : from sentence_transformers import SentenceTransformer I get ModuleNotFoundError: No module named 'transformers.models.auto.tokenization_auto'. I am not sure how to resolve this issue.

**Comment by LysandreJik** [comment]
Could you reproduce this in a colab so that we can take a look? Thanks!

**Comment by Sankalp1233** [comment]
I reworked my code so I didn't get the error anymore I'm honestly not sure how it got fixed

**Comment by Sankalp1233** [comment]
I think it maybe because I didn't restart the runtime
