### ISSUE TITLE
`XLMRobertaTokenizer` `encode_plus` api producing `<unk>` for a valid token

### ISSUE THREAD

**Issue by abgoswam** [huggingface/transformers#10877]
## Environment info
- `transformers` version: 4.5.0.dev0   (latest master)
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.7.10
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@LysandreJik

## Information

`XLMRobertaTokenizer`   `encode_plus` api producing  `<unk>` for a valid token

## To reproduce

```Python
from transformers import XLMRobertaTokenizer

tokenizer = XLMRobertaTokenizer.from_pretrained("xlm-roberta-base")

text = "请在黄鹂餐厅预订今晚7点半的位置。"
toks = tokenizer.tokenize(text)
assert toks == ['▁', '请', '在', '黄', '鹂', '餐厅', '预订', '今晚', '7', '点', '半', '的位置', '。']

output = tokenizer.encode_plus(text, add_special_tokens=False)
toks_converted = tokenizer.convert_ids_to_tokens(output['input_ids'])

assert toks_converted == ['▁', '请', '在', '黄', '<unk>', '餐厅', '预订', '今晚', '7', '点', '半', '的位置', '。']
```

## Expected behavior

```Python
assert toks_converted[4] == '鹂'  # not <unk>
```

**Comment by LysandreJik** [comment]
Hi, thanks for opening an issue! Seen with @n1to, and this comes from the Unigram-based tokenizers: Unigram's tokenize cuts the string into tokens, and then converts them to IDs. Unknown tokens are detected during the token to IDs conversion, rather than when the string is cut into tokens.

This is different to BPE, where the string is cut in a lot of independant characters, converted to IDs, then merged to gether.

This is also different to WordPiece, where we start from the word and cut it until we find a token representation for each word piece; if we don't, then that's unknown.

**Comment by abgoswam** [comment]
hi @LysandreJik .  Thanks for looking into this, and sharing the info

based on your response it seems that for the `XLMRobertaTokenizer` tokenizer, we **cannot** guarantee that  the following holds:

```Python
assert tokenizer.decode(tokenizer.convert_tokens_to_ids(tokenizer.tokenize(text))) == text
```

am i right ?

**Comment by LysandreJik** [comment]
I believe that's true for any tokenizer. If the tokenizer cannot tokenize one part of your text as it is not part of your vocabulary, then some information is lost.

**Comment by stefan-it** [comment]
Hey  guys,

for the sake of completeness, there's the double check with the reference implementation/tokenizer:

```python
import torch
xlmr = torch.hub.load('pytorch/fairseq', 'xlmr.base')
xlmr.eval()

tokens = xlmr.encode('请在黄鹂餐厅预订今晚7点半的位置。')
```

It outputs:

```bash
tensor([     0,      6,   9736,    213,  19390,      3, 113638, 209093, 155755,
           966,   2391,   6193,  57486,     30,      2])
```

3 is the id for the unknown token, but you "reverse" tokenization with:

```python
xlmr.decode(tokens)
```

This outputs:

```bash
'请在黄<unk>餐厅预订今晚7点半的位置。'
```

So the `<unk>` token also appears :)

**Comment by abgoswam** [comment]
Thanks folks for the discussion and insight in behaviour of tokenizers in HF.  

Closing this issue, since its not a bug per se.

**Comment by hapazv** [comment]
hi guys.

I try to reproduce the code that is at the beginning of the topic and I get the following:
![token roberta](https://user-images.githubusercontent.com/70067770/115905249-73e70100-a42b-11eb-8aa8-accbbc7a1e5b.png)
