### ISSUE TITLE
❓ Why in `run_squad.py` using XLNet, CLS token is not set at the end ?

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#1088]
## ❓ Questions & Help

[This line](https://github.com/huggingface/pytorch-transformers/blob/e00b4ff1de0591d5093407b16e665e5c86028f04/examples/run_squad.py#L292)  of the file `run_squad.py` create the features for the dataset.

No matter which model is used (BERT or XLNet), the function will create the format :

> CLS A SEP B SEP

But for XLNet case, we want :

> A SEP B SEP CLS

---

**Isn' it wrong ? Did I miss something ?**

**Comment by thomwolf** [comment]
Humm I think you are right.

The SquAD example looks a bit broken in pytorch-transformers, we will have to review it @LysandreJik.
