### ISSUE TITLE
save only the best performing checkpoint

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/transformers#10896]
# 🚀 Feature request

In the Trainer - Enable an option to save only the best performing checkpoints (rather than the newsest) 

## Motivation

Usually when we train a model we would like to keep only the best performing checkpoints (on the dev set according to the specified metric) rather than the newest checkpoints.

**Comment by sgugger** [comment]
The checkpoints are saved to resume training in case you are interrupted, so saving only the best checkpoints wouldn't work with this.

The `load_best_model_at_end` functionality already keeps track of the best checkpoint during training and reloads it at the end, I think it should cover what you need.

**Comment by Gpwner** [comment]
So，when I  finish training，how can I load the best performing checkpoint ？ @sgugger

**Comment by Gpwner** [comment]
When  I check the `trainer_state.json`  file I found these mssage:
```
  "best_metric": null,
  "best_model_checkpoint": null,
  "epoch": 100.0,
  "global_step": 559300,
  "is_hyper_param_search": false,
  "is_local_process_zero": true,
  "is_world_process_zero": true,
```

as shown above，"best_model_checkpoint"   is null.

**Comment by sgugger** [comment]
If you did not specify `--load_best_model_at_end` for your script, you won't get it automatically.
