### ISSUE TITLE
[doc] Custom datasets page reference dataset library as NLP library

### ISSUE THREAD

**Issue by tomy0000000** [huggingface/transformers#10897]
### Who can help

@sgugger 

## Information

The page [Fine-tuning with custom datasets](https://huggingface.co/transformers/custom_datasets.html) is referencing dataset library a lot, but in the old name (NLP library), and I've noticed that this still holds true in the [source .rst](https://github.com/huggingface/transformers/blob/master/docs/source/custom_datasets.rst) file.

If it wasn't left unmodified intended, I'm willing to help submitting a PR, just filling the issue to confirm.

**Comment by sgugger** [comment]
Yes, the name should indeed be updated! If you want to do a PR with this, please go ahead!
