### ISSUE TITLE
Getting a model to work on a system with no internet access

### ISSUE THREAD

**Issue by XapaJIaMnu** [huggingface/transformers#10900]
## Environment info
We are trying to use the model from https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment on a system that has no connection to the internet. Normally one can do:
`pipeline = Pipeline(model='model_name")`
and huggingface will fetch everything it needs from the internet. Unfortunately, some datasets reside within a highly protected environment that does not allow for any internet connection and we can't fetch our models. (Hell, we can't even copy/paste errors).

Uploading files to that environment is really cumbersome and every file needs to go through a review process. Through trial and error, i have gotten the model and tokenizer to load, but it is now missing a "vocabulary". Before I got a submit a request for extra files to be uploaded, could someone just confirm for me what files do I need so that the model could be loaded offline. As far as I understand i have to have every single file from here: https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment/tree/main
and my script should look like:
`pipeline = Pipeline(model='/path/to/dir")`

### Who can help

Models:
- pipelines: @LysandreJik

## Information
https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment

The problem arises when using:
Running in a restricted environment

## To reproduce
Use the example script from https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment and try to manually input the files

## Expected behavior
The model should work just as if it were in a system connected to the internet.

**Comment by NielsRogge** [comment]
Yes, if you place all files which you find on the model page on the hub in a directory, then it will work.

**Comment by julien-c** [comment]
You can even just `git clone` the model repo
