### ISSUE TITLE
LengthGroupedSampler slowly iterates over dataset

### ISSUE THREAD

**Issue by maxidl** [huggingface/transformers#10909]
https://github.com/huggingface/transformers/blob/86c6f8a8b1f2bfc6c6d175590efc95a5e6facb51/src/transformers/trainer_pt_utils.py#L506

When using training arg "group_by_length", the sampler has to get the length of every input. it does so by iterating over the dataset in a simple for loop, without the use of a dataloader.

In my case, this led to long delays before the training starts, as reading the dataset without the worker parallelization from a dataloader took a long time.

I believe this can potentially improved, although one could also precompute the lengths and pass them to the sampler (but this can only happen if the user is aware of it being a potential bottleneck).
Maybe it is a good idea to add a dataloader + num_workers option here?

Thanks to Pere-Lluís and Pedro for being my co-detectives in spotting this caveat.

**Comment by sgugger** [comment]
I think the solution you suggested on the forums (leaving the length computation up to the user in the dataset) is a bit better. Will investigate a bit more.

**Comment by maxidl** [comment]
> I think the solution you suggested on the forums (leaving the length computation up to the user in the dataset) is a bit better. Will investigate a bit more.

I agree, that surely is a good solution if the user is aware of it. It just took us a while to find the source of that delay before training. Maybe we can have some sort of user hint?

**Comment by sgugger** [comment]
Fixed by #10953
