### ISSUE TITLE
No such file or directory: '..\\VERSION'

### ISSUE THREAD

**Issue by balkon16** [huggingface/transformers#1090]
## 🐛 Bug

While trying to install `pytorch-transformers` I get the following error:
```

    ERROR: Command errored out with exit status 1:
     command: 'c:\users\pawel.lonca\appdata\local\programs\python\python35\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PAWEL~1.LON\\AppData\\Local\\Temp\\pip-install-b5eog20_\\sentencepiece\\setup.py'"'"'; __file__='"'"'C:\\Users\\PAWEL~1.LON\\AppData\\Local\\Temp\\pip-install-b5eog20_\\sentencepiece\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\PAWEL~1.LON\AppData\Local\Temp\pip-install-b5eog20_\sentencepiece\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PAWEL~1.LON\AppData\Local\Temp\pip-install-b5eog20_\sentencepiece\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "c:\users\pawel.lonca\appdata\local\programs\python\python35\lib\codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Google search suggests that the recommended solution is upgrading the `setuptools` but it didn't work in my case.

## Environment

* OS: Windows 10
* Python version: 3.5.2
* PyTorch version: 1.2.0+cpu

**Comment by DayuanJiang** [comment]
The same bug occurs when installing.

**Comment by thomwolf** [comment]
This looks like an issue with sentencepiece and python 3.5. Do you want to have a look there maybe? https://github.com/google/sentencepiece

**Comment by DayuanJiang** [comment]
> This looks like an issue with sentencepiece and python 3.5. Do you want to have a look there maybe? https://github.com/google/sentencepiece

I switched to python 3.6 and successfully installed it.

**Comment by mkumar10** [comment]
I'm getting the same issue. Changing to 3.6 or 3.7 did not fix it.

**Comment by asaisra1** [comment]
Download the wheel file from https://github.com/google/sentencepiece/releases for your python version and install it with
 pip install sentencepiece-xxx-cpxx-xx.whl

**Comment by JasonJi-0521** [comment]
> Download the wheel file from https://github.com/google/sentencepiece/releases for your python version and install it with
> pip install sentencepiece-xxx-cpxx-xx.whl

this trick works fantastically, many thanks!
