### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'log_metrics'

### ISSUE THREAD

**Issue by yananchen1989** [huggingface/transformers#10916]
I try to fine tune the distilbert-base-uncased on my own dataset, which are csv made up of each news line by line.
here is my command:

```
nohup python run_mlm.py \
    --model_name_or_path distilbert-base-uncased \
    --train_file df_finetune_train.csv \
    --validation_file df_finetune_test.csv  \
    --do_train \
    --do_eval \
    --preprocessing_num_workers 72 \
    --output_dir ./finetuned_bert \
    --overwrite_cache True \
    --max_seq_length 256 \
    --line_by_line True > log_fintune_mlm &
```
Here is the error.

> {'loss': 1.7847, 'learning_rate': 3.264263411864888e-07, 'epoch': 2.98}
> {'loss': 1.7906, 'learning_rate': 1.7858832434478192e-07, 'epoch': 2.99}
> {'loss': 1.7839, 'learning_rate': 3.075030750307503e-08, 'epoch': 3.0}
> {'train_runtime': 65966.5445, 'train_samples_per_second': 2.563, 'epoch': 3.0}
> Traceback (most recent call last):
>   File "run_mlm.py", line 487, in <module>
>     main()
>   File "run_mlm.py", line 462, in main
>     trainer.log_metrics("train", metrics)
> AttributeError: 'Trainer' object has no attribute 'log_metrics'

transformers version: 4.3.3
torch version: 1.5.0+cu101

**Comment by NielsRogge** [comment]
You should install Transformers from source. See #10446.
