### ISSUE TITLE
OSError: file bert-base-uncased/config.json not found

### ISSUE THREAD

**Issue by pkuzengqi** [huggingface/transformers#10918]
## Environment info

- `transformers` version: 4.4.2
- Python version: 3.6
- PyTorch version (GPU?): 1.8.0 (Tesla V100)

## Information

The problem arises when using:
```
from transformers import BertModel
model = BertModel.from_pretrained('bert-base-uncased')
```

Error Info (Some personal info has been replaced by ---)
```
file bert-base-uncased/config.json not found
Traceback (most recent call last):
  File "---/anaconda3/envs/attn/lib/python3.6/site-packages/transformers-4.2.2-py3.8.egg/transformers/configuration_utils.py", line 420, in get_config_dict
  File "---/anaconda3/envs/attn/lib/python3.6/site-packages/transformers-4.2.2-py3.8.egg/transformers/file_utils.py", line 1063, in cached_path
OSError: file bert-base-uncased/config.json not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "---.py", line 107, in <module>
    from_pretrained_input()
  File "---.py", line 96, in from_pretrained_input
    model = BertModel.from_pretrained('bert-base-uncased')
  File "---/anaconda3/envs/attn/lib/python3.6/site-packages/transformers-4.2.2-py3.8.egg/transformers/modeling_utils.py", line 962, in from_pretrained
  File "---/anaconda3/envs/attn/lib/python3.6/site-packages/transformers-4.2.2-py3.8.egg/transformers/configuration_utils.py", line 372, in from_pretrained
  File "---/anaconda3/envs/attn/lib/python3.6/site-packages/transformers-4.2.2-py3.8.egg/transformers/configuration_utils.py", line 432, in get_config_dict
OSError: Can't load config for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-uncased' is the correct path to a directory containing a config.json file
```

#### what I have read:

https://github.com/huggingface/transformers/issues/353

#### what I have tried:

1. loading from a downloaded model file works well

```
wget https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz
```
unzip the file and rename ```bert_config.json``` as ```config.json```, then
```
model = BertModel.from_pretrained(BERT_BASE_UNCASED_CACHE)
```

2. enough disk space, enough memory, free GPU

3. open internet connection, no proxy

4. 
```
import pytorch_pretrained_bert as ppb
assert 'bert-large-cased' in ppb.modeling.PRETRAINED_MODEL_ARCHIVE_MAP
```

5. The following models work well
```
model = BertModel.from_pretrained('bert-base-cased')

model = RobertaModel.from_pretrained('roberta-base')
```

6. working well in server cmd but not in local pycharm (remote deployment to server)

Observation: 
- Pycharm can found the ```transfromers``` installed with pip, but that will trigger this problem 
- Pycharm cannot find the current  ```transformers```  installed with conda 
```conda install transformers=4.4 -n env -c huggingface```

**Comment by theainerd** [comment]
I'm also facing the same issue. Did you find any fix yet . ??

**Comment by stepbystep88** [comment]
I'm also facing the same issue. Did you guys find any fix yet . ??

**Comment by VlaDanilov** [comment]
Same problem here, please write if someone found a valid solution.

**Comment by thak123** [comment]
Facing same error

**Comment by vildhet** [comment]
Hi, I've had the same error but with `roberta-base`. It appeared that I had an empty folder named `roberta-base` in my working directory. Removing it solved the issue.

**Comment by leoliu0** [comment]
I found this issue is caused by setting cache directory using checkpoint name
TrainingArguments(checkpoint,evaluation_strategy='steps')

change checkpoint to something else resolve the issue

**Comment by vikas95** [comment]
> #353

Got the same issue, thanks for reporting it here. Was able to fix it following after going through your comment.

**Comment by ericc2023** [comment]
> Hi, I've had the same error but with `roberta-base`. It appeared that I had an empty folder named `roberta-base` in my working directory. Removing it solved the issue.

You are literally an angel.
