### ISSUE TITLE
Typo in examples/text-classification README

### ISSUE THREAD

**Issue by lukemelas** [huggingface/transformers#10926]
In the examples/text-classification README, the example scripts for "PyTorch version, no Trainer" are slightly incorrect. They should be adjusted as: 
```diff
export TASK_NAME=mrpc

python run_glue_no_trainer.py \
  --model_name_or_path bert-base-cased \
  --task_name $TASK_NAME \
-   --max_seq_length 128 \
+   --max_length 128 \
  --per_device_train_batch_size 32 \
  --learning_rate 2e-5 \
  --num_train_epochs 3 \
  --output_dir /tmp/$TASK_NAME/
```
Thanks for your great repo!
Luke

**Comment by sgugger** [comment]
Indeed, do you want to open a PR with the fix since you found it?

PS: I didn't know that \`\`\`diff feature, it's soooo pretty 🤩 !
