### ISSUE TITLE
Addition of  SequenceClassification config specific documentation to XModelForSequenceClassification.

### ISSUE THREAD

**Issue by nasheedyasin** [huggingface/transformers#10940]
## Environment info

- `transformers` version:
- Platform: Windows 10
- Python version: 3.6.12
- Tensorflow version (GPU?): 2.3.1
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

## Information

Model I am using (DistilBert, Longformer):

The tasks I am working on is:
* [ ] my own task or dataset:
A document classification task with 2 or more custom classes.

## To reproduce

1. Navigate to the documentation of any [transformers.XForSequenceClassification](https://huggingface.co/transformers/model_doc/longformer.html#transformers.LongformerForSequenceClassification)
2. You will notice an absence of documentation for setting of any Sequence Classification related configs.
3. For example: `id2label, label2id, num_labels`

## Expected behavior

Documentation for SequenceClassification specific settings like: `id2label, label2id, num_labels` in the documentation page for  [transformers.XForSequenceClassification](https://huggingface.co/transformers/model_doc/longformer.html#transformers.LongformerForSequenceClassification)
Additionally in the documentation of the  `from_pretrained` method, when loading models fine-tuned on non `SequenceClassification` tasks.

**Comment by sgugger** [comment]
Those are generic config parameters and as such, they can't be documented on a model (they are config parameters, not model parameters). The documentation is in the [config page](https://huggingface.co/transformers/main_classes/configuration.html).

The documentation of the `from_pretrained` [method](https://huggingface.co/transformers/main_classes/model.html#transformers.PreTrainedModel.from_pretrained) also tells the user any parameter of the config can be passed to this method as a kwarg.

**Comment by nasheedyasin** [comment]
Understood, the params in question are mentioned there in detail. Thanks 👍🏽 @sgugger
