### ISSUE TITLE
How to load weights from a private server?

### ISSUE THREAD

**Issue by hwijeen** [huggingface/transformers#11009]
Hi, thank you for the great library!

I am trying instantiate a model with weights uploaded on my private server.  By looking at [`is_remote_url`](https://github.com/huggingface/transformers/blob/8780caa388c7b2aa937454ed96bcdd3f097f851d/src/transformers/modeling_utils.py#L1011) function, it seems that transformers supports loading from a private server, but it seems a bit tricky.
```python
BertModel.from_pretrained('http://my-server/my-bert-cased/pytorch_model.bin') # cannot not find config
BertModel.from_pretrained('http://my-server/my-bert-cased/config.json') # finds config, but cannot find model weights
BertModel.from_pretrained('http://my-server/my-bert-cased', config='http://my-server/my-bert-cased/config.json') # works!
```

Although the third one works, it is cumbersome as I need to download config from private server to my local machine beforehand.

I would appreciate it if someone could share or point to a better way!

**Comment by hwijeen** [comment]
My workaround was to manually download checkpoints using `cached_file` function to local, and instantiate a model from the download file using `from_pretrained`.

**Comment by julien-c** [comment]
Yes that's indeed the preferred workaround. Thanks!
