### ISSUE TITLE
OSError: Can't load config for '/content/wav2vec2-large-xlsr-asr-demo'. Make sure that:

### ISSUE THREAD

**Issue by Kowsher** [huggingface/transformers#11014]
I'm using
pip install transformers==4.4.2

After completing the training process of ASR I can not read the trained file from my local storage. Although the path is right. But can read  from hugging face 
model = Wav2Vec2ForCTC.from_pretrained("/content/wav2vec2-large-xlsr-asr-demo").to("cuda")

The error:

OSError: Can't load config for '/content/wav2vec2-large-xlsr-asr-demo'. Make sure that:

- '/content/wav2vec2-large-xlsr-asr-demo' is a correct model identifier listed on 'https://huggingface.co/models'

- or '/content/wav2vec2-large-xlsr-asr-demo' is the correct path to a directory containing a config.json file

**Comment by LysandreJik** [comment]
Can you `ls` what's in `/content/wav2vec2-large-xlsr-asr-demo`?
