### ISSUE TITLE
evaluate bert on Senteval dataset

### ISSUE THREAD

**Issue by juliahane** [huggingface/transformers#1101]
Hi
I would like to evaluate bert on senteval datasets, with Senteval, I am not sure how to do it,
Do you provide any evaluation toolkit to evaluate the trained models?
thanks

**Comment by nikhilno1** [comment]
This should help you: https://medium.com/dsnet/running-pytorch-transformers-on-custom-datasets-717fd9e10fe2
I did it for IMDB dataset which you should be able to customize for any other dataset.
