### ISSUE TITLE
cannot import name 'AutoModelForSequenceClassification' from 'transformers'

### ISSUE THREAD

**Issue by nithinreddyy** [huggingface/transformers#11022]
```
from transformers import pipeline
classifier = pipeline('sentiment-analysis') #This code will download the pipeline
classifier('We are very happy to show you the 🤗 Transformers library.')
classifier.save_pretrained('/some/directory') 
```

I'm trying to save the model and trying to perform the sentiment-analysis operation offline

```
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

t = AutoTokenizer.from_pretrained('/some/directory')
m = AutoModelForSequenceClassification.from_pretrained('/some/directory')
c2 = pipeline(task = 'sentiment-analysis', model=m, tokenizer=t)

I'm facing import error for jupyter notebook as given below

`**cannot import name 'AutoModelForSequenceClassification' from 'transformers'**`
```

**Comment by cronoik** [comment]
Please tell us which version you are using and also check [your SO question](https://stackoverflow.com/questions/66906652/how-to-download-hugging-face-sentiment-analysis-pipeline-to-use-it-offline/66907181#comment118269245_66907181) again because the was revised.

**Comment by abhdhar-1618** [comment]
I am trying the below codes

```
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from scipy.special import softmax
```

however, getting the below errors in jupyter notebook

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[49], line 2
      1 from transformers import AutoTokenizer
----> 2 from transformers import AutoModelForSequenceClassification
      3 from scipy.special import softmax

ImportError: cannot import name 'AutoModelForSequenceClassification' from 'transformers' (C:\Users\Abhik\anaconda3\Lib\site-packages\transformers\__init__.py)`


are there any changes to it? I am using jupyter notebbok 7
