### ISSUE TITLE
Module Not found: datasets_modules.datasets.output

### ISSUE THREAD

**Issue by ashleylew** [huggingface/transformers#11021]
## Environment info

- `transformers` version: 4.5.0.dev0
- Platform: Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.8.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: not sure
- Using distributed or parallel set-up in script?: <fill in> ? 

### Who can help
@patil-suraj

## Information

Model I am using (Bert, XLNet ...): BART seq2seq

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. "Install from source" method
2. ran this command, where "data/output.jsonl" is my dataset: 
```
python examples/seq2seq/run_translation.py \
    --model_name_or_path t5-small \
    --do_train \
    --do_eval \
    --source_lang en \
    --target_lang de \
    --source_prefix "Translate English to Logical Forms: " \
    --dataset_name data/output.jsonl \
    --output_dir /tmp/tst-translation \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --overwrite_output_dir \
    --predict_with_generate
```
3. Got the following error: 
```
ModuleNotFoundError: No module named 'datasets_modules.datasets.output'
```

At first it told me that "datasets" was not installed, so I did ```pip install datasets``` and that worked fine. Then I got this error and haven't been able to figure out what it means or how to fix it.

**Comment by WadoodAbdul** [comment]
@ashleylew were you able to fix this? Could you please share what did?

**Comment by ashleylew** [comment]
I was just loading the data incorrectly. I misunderstood how to load custom data in and was treating it like one of Hugging Face's datasets rather than a custom one, but once I fixed that, everything was fine! I can give more details if necessary.

**Comment by WadoodAbdul** [comment]
I'll check that part out in my script then, thanks!

**Comment by abhishekkuber** [comment]
@ashleylew Hi I'm getting the same error, can you share the data loading script? I tried doing stuff but it doesn't work for me. 
Thanks

**Comment by ashleylew** [comment]
Yeah! So in my command script that I posted here, I used `    --dataset_name data/output.jsonl \ ` but that command is for pre-loaded data sets, whereas mine is a custom one. So instead you'll want to use: 

`  --train_file train.json \
    --validation_file validation.json \`
