### ISSUE TITLE
How to get masked word prediction for other languages

### ISSUE THREAD

**Issue by AnnaSou** [huggingface/transformers#11032]
Hello,

I trying to get masked words predictions for languages except English with Roberta or XLM Roberta.

```
from transformers import pipeline
nlp = pipeline("fill-mask", model="roberta-base")
template = f"That woman is {nlp.tokenizer.mask_token}."
output = nlp(template)

nlp4 = pipeline("fill-mask", model="roberta-base")
nlp4(f"Женщины работают {nlp4.tokenizer.mask_token}.")
```
The output for English example is quite good, while for Russian one does not make sense at all:

`[{'sequence': 'Женщины работаюта.', 'score': 0.2504434883594513, 'token': 26161, 'token_str': 'а'}, {'sequence': 'Женщины работають.', 'score': 0.24665573239326477, 'token': 47015, 'token_str': 'ь'}, {'sequence': 'Женщины работаюты.', 'score': 0.1454654186964035, 'token': 46800, 'token_str': 'ы'}, {'sequence': 'Женщины работаюте.', 'score': 0.07919821888208389, 'token': 25482, 'token_str': 'е'}, {'sequence': 'Женщины работаюти.', 'score': 0.07401203364133835, 'token': 35328, 'token_str': 'и'}]`

Neither "roberta-base" nor "xlm-roberta-base" work for Russian language example. 

Maybe I am doing it wrong, but how would one use masked word prediction for other languages?

Thanks!

**Comment by NielsRogge** [comment]
You can filter the model hub on 'ru' (Russian) and 'fill-mask' (masked language modeling): https://huggingface.co/models?filter=ru&pipeline_tag=fill-mask

robert-base was trained on English text only, so it will not work for Russian. 

Maybe a good choice is this model: https://huggingface.co/blinoff/roberta-base-russian-v0

**Comment by TristaCao** [comment]
How about XLM-RoBERTa? That should be trained with multiple languages, but I got the same issue.

**Comment by AnnaSou** [comment]
Thank you for the reply! I second the comment above regarding XLM-Roberta.
