### ISSUE TITLE
Potential incorrect application of layer norm in BlenderbotSmallDecoder

### ISSUE THREAD

**Issue by sougata-ub** [huggingface/transformers#11046]
In BlenderbotSmallDecoder,  layer norm is applied only on the token embeddings, and not on the hidden_states, whereas in the BlenderbotSmallEncoder, layer norm is applied after adding the input_embeds and positional embeds

BlenderbotSmallEncoder:
`hidden_states = inputs_embeds + embed_pos`
`hidden_states = self.layernorm_embedding(hidden_states)`

BlenderbotSmallDecoder:
`inputs_embeds = self.layernorm_embedding(inputs_embeds)`
`hidden_states = inputs_embeds + positions`

**Comment by LysandreJik** [comment]
cc @patrickvonplaten @patil-suraj

**Comment by patil-suraj** [comment]
Great catch @sougata-ub! This indeed seems like a bug. Will check the original implementation and fix this.

**Comment by patrickvonplaten** [comment]
Hey @sougata-ub - did you try to change the order in the `BlenderbotSmallDecoder` manually and run a couple of examples to see whether the model performs better? Think, we can check this in a first step -> If we get much worse results than the previous implementation was probably correct. If results seem to be better, it's a strong hint that there is a bug actually.
