### ISSUE TITLE
Changing the _read_tsv method in class DataProcessor

### ISSUE THREAD

**Issue by Sudeep09** [huggingface/transformers#1107]
## 🚀 Feature
I would request changing the class method to the following:
@classmethod
def _read_tsv(cls, input_file, quotechar=None)
        """Reads a tab separated value file."""
        lines = []
        df = pd.read_csv(input_file, delimiter='\t')
        for line in (df.values):
            lines.append(line)
        return lines

## Motivation

The reader used to read the files incorrectly.

**Comment by thomwolf** [comment]
Hi, we need more information about what script you are talking about (like the information asked in the issue templates for instance).

**Comment by Sudeep09** [comment]
The file path is: /examples/utils_glue.py
The class is DataProcessor(object):

@classmethod
def _read_tsv(cls, input_file, quotechar=None)
"""Reads a tab separated value file."""
lines = []
df = pd.read_csv(input_file, delimiter='\t')
for line in (df.values):
lines.append(line)
return lines

**Comment by thomwolf** [comment]
We also need a lot more details and a clear example of why you think the reader used to read the files incorrectly.
