### ISSUE TITLE
'BertTokenizer' object has no attribute 'decode'

### ISSUE THREAD

**Issue by merleyc** [huggingface/transformers#11080]
## Environment info
- `transformers` version: 4.4.2 and 3.5.0
- Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core (centos 7)
- Python version: 3.7.7
- PyTorch version (GPU?): CPU torch=1.6.0
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No
- tokenizers-0.10.2 
- pytorch-pretrained-bert=0.6.2 (installed by using 'pip install pytorch_pretrained_bert'
- Using jupyter notebook

### Who can help
- tokenizers: @LysandreJik

## Information

Model I am using (Bert, XLNet ...): BertTokenizer

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details below)

## To reproduce

When I run the code below I am getting the following error:
```
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>
<timed exec> in <listcomp>(.0)
AttributeError: 'BertTokenizer' object has no attribute 'decode'
```

```
from pytorch_pretrained_bert import BertTokenizer
import pandas as pd
from tqdm.notebook import tqdm
import transformers
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased', do_lower_case=False)
df = pd.read_parquet('file.parquet', engine="pyarrow")
df['coll'] = [ tokenizer.decode( [ int(n) for n in t.split('\t') ] ) for t in tqdm(df.text_tokens.values) ] 
```

## Expected behavior
Get the tokenized words.

Thank you!

**Comment by frankhart2018** [comment]
@merleyc Instead of using pytorch_pretrained_bert try using transformers:- `from transformers import BertTokenizer`.

**Comment by merleyc** [comment]
Thanks a lot, @frankhart2018! It works.
