### ISSUE TITLE
using RAG with local documents

### ISSUE THREAD

**Issue by saichandrapandraju** [huggingface/transformers#11086]
Hi,
I have a requirement that model should search for relevant documents to answer the query and I found [RAG](https://arxiv.org/pdf/2005.11401.pdf) from [Facebook AI](https://ai.facebook.com/) which perfectly fits my usecase. I also found [this](https://huggingface.co/blog/ray-rag) post in which HuggingFace explains RAG and came to know that HF implemented RAG which is awesome! 
My doubt is whether I could extend this functionality so that the model should do retrieval from local documents rather than from HF's wikipedia corpus.
Are there any notebooks to refer to?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!

**Comment by saichandrapandraju** [comment]
ok. Created [issue](https://discuss.huggingface.co/t/using-rag-with-local-documents/5326) in [forum](https://discuss.huggingface.co)

Thanks @LysandreJik
