### ISSUE TITLE
How to use tensorboard with Trainer?

### ISSUE THREAD

**Issue by tanujjain** [huggingface/transformers#11084]
From the docs, TrainingArguments has a 'logging_dir' parameter that defaults to 'runs/'. Also, Trainer uses a default callback called TensorBoardCallback that should log to a tensorboard by default.

I use:
```
training_args = TrainingArguments(
    output_dir=".",
    group_by_length=True,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    evaluation_strategy="steps",
    num_train_epochs=1,
    save_steps=1,
    eval_steps=1,
    logging_steps=1,
    learning_rate=3e-4,
    max_steps=1,
) 

trainer = Trainer(
    model=model,
    data_collator=data_collator,
    args=training_args,
    compute_metrics=compute_metrics,
    train_dataset=dataset_train,
    eval_dataset=dataset_test,
    tokenizer=feature_ext,
)
```
So, I rely on default parameters of TrainingArguments and Trainer while hoping to find a `runs/` directory that should contain some logs but I don't find any such directory. Could someone please help on how to get tensorboard working?

**Comment by sgugger** [comment]
Are you sure it's properly installed? This code should indeed work if `tensoboard` is installed in the environment in which you execute it. You can try to force the `TensorBoard` integration by adding `report_to=["tensorboard"]` in your `TrainingArguments`.

**Comment by tanujjain** [comment]
@sgugger My bad, somehow missed tensorboard installation.  Apologies for the inconvenience. Closing the issue.

**Comment by phamkhactu** [comment]
I have the same, @git-baahubali  have you fixed it?

**Comment by git-baahubali** [comment]
> I have the same, [@git-baahubali](https://github.com/git-baahubali) have you fixed it?

Nope
