### ISSUE TITLE
Errors in inference API

### ISSUE THREAD

**Issue by DeveloperInProgress** [huggingface/transformers#11121]
I understand that the inference API returns a json with "error" field if an error occurs. Where can I find the list of such possible errors?

**Comment by LysandreJik** [comment]
Maybe of interest to @Narsil

**Comment by Narsil** [comment]
@DeveloperInProgress .
Sorry, there is no exhaustive list of those as of yet (as a number of them are actual exceptions raised by transformers itself)

What I can say, is that Environment and ValueError are simply displayed as is and treated as user error (usually problem in the model configuration or inputs of the model).

Any other exception is raised as a server error (and looked at regularly).

Any "unknown error" is an error for which we can't find a good message, we try to accompany it (when it's possible) with any warnings that might have been raised earlier by transformers (for instance too long sequences make certain models crash, deep cuda errors are unusable as is, the warning is better).

Does that answer your question ?

**Comment by DeveloperInProgress** [comment]
@Narsil gotcha
