### ISSUE TITLE
Not very good answers

### ISSUE THREAD

**Issue by Sankalp1233** [huggingface/transformers#11125]
When I try to feed in this context from a long txt file lets say below:
[New_Spark_Questions.txt](https://github.com/huggingface/transformers/files/6273496/New_Spark_Questions.txt)
and I feed in a question from that txt file: Would police or the FBI ever be able to access DNA or other information collected?
it is not giving me a very good answer: I get Answer: 'help speed up the progress of autism research' with score 0.4306815266609192. How do we see all the cores available, how does the model decide which answer is the best?

**Comment by NielsRogge** [comment]
The text you are providing is probably too long for the model. Most Transformer models accept a sequence length of 512 tokens.

Which model did you use?

**Comment by Sankalp1233** [comment]
I just used the general q-a pipeline:
from google.colab import files
uploaded = files.upload() 
filename = "New_Spark_Questions.txt"
# filename = "police_fbi_question.txt"
new_file = uploaded[filename].decode("utf-8")
# !pip3 uninstall transformers
!pip3 install sentencepiece
!pip3 install git+https://github.com/huggingface/transformers
question = "Why should I take part in SPARK?" 
# import sentencepiece
# Generating an answer to the question in context
from transformers import pipeline
qa = pipeline("question-answering")
answer = qa(question=question, context=new_file)
# Print the answer
print(f"Question: {question}")
print(f"Answer: '{answer['answer']}' with score {answer['score']}")
