### ISSUE TITLE
cannot import name 'BigBirdModel' from 'transformers'

### ISSUE THREAD

**Issue by Shengyu-Liu558** [huggingface/transformers#11153]
when I write the “from transformers import BigBirdModel”， the error is “cannot import name 'BigBirdConfig' from 'transformers'”,how to solve the problem? thank you.

**Comment by LysandreJik** [comment]
Hello! Please respect the issue template so that we can help you. Big Bird is only available in the latest transformers version, do you have this version in your setup?
