### ISSUE TITLE
tokenizer.encode_plus returns torch.tensors loaded on the desired device

### ISSUE THREAD

**Issue by sadakmed** [huggingface/transformers#11165]
# 🚀 Feature request

add device attribute to tokenizer.encode_plus so when it returns a torch.tensors it loads it on the desired device

## Motivation

- to pass the output of tokenizer to the model, one only can unpack the returned output using ** without bothering about the content of tokenizer, that only true when with cpu, but for gpu u need to unpack the output and load each input to device, and then pass them to the model.
this process will be also frustrating if you don't know the keys from the output or when you want to switch from a model to another -eg from bert to roberta, roberta doesnt need token_type_ids-.

**Comment by LysandreJik** [comment]
Hi! You can cast the `BatchEncoding` output by `encode_plus` to your device:
```py
model_input = tokenizer.encode_plus(xxx, return_tensors="pt")
model_input.to("cuda")
```

**Comment by sadakmed** [comment]
niiice, thank you!!
