### ISSUE TITLE
Decoding throws Segmentation Fault 

### ISSUE THREAD

**Issue by macabdul9** [huggingface/transformers#11191]
## Environment info

- `transformers` version: 4.4.2
- Platform: Linux-5.8.0-48-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.8.1 (True)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

Models:

- bert

## Information

A very simple decoding step throws `24272 segmentation fault (core dumped)` .

## To reproduce

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
print(tokenizer.decode(token_ids=torch.tensor([3446])))
```

## Expected behavior

It should print `'rate'`

**Comment by LysandreJik** [comment]
I get `rate` printed out on my setup! Do you mind sharing your `pip list`?

**Comment by macabdul9** [comment]
This was mentioned in #4857 and #5359 ....fiixed it after reinstalling.

**Comment by alexcdot** [comment]
For me, i didn't have sentencepiece installed. I needed to import torch before transformers to fix this
