### ISSUE TITLE
wav2vec 2.0 doesn't appear to do vector quantization

### ISSUE THREAD

**Issue by noahtren** [huggingface/transformers#11190]
In the [paper](https://arxiv.org/abs/2006.11477) from FAIR, they describe wav2vec 2.0 as using a vector quantization module to learn discrete vectors of speech units (section 2.) As far as I know, this should be happening between `Wav2Vec2FeatureExtractor` and `Wav2Vec2FeatureProjection`.

The HuggingFace implementation doesn't seem to do any vector quantization. Is this a correct implementation?

**Comment by Nian-Chen** [comment]
Hi, I think VQ only works for Pretraining, it doesn't look like Transformers currently support Pretrain

**Comment by patrickvonplaten** [comment]
Vector quantization is only required for pretraining which is currently not supported. It should be added soon: https://github.com/huggingface/transformers/issues/10873.

**Comment by noahtren** [comment]
Thanks! Just to clarify, was the [base model](https://huggingface.co/facebook/wav2vec2-base) pretrained with quantization, and it's just that the port to HF doesn't include the quantization module?

**Comment by patrickvonplaten** [comment]
The port didn't include the quantization module - we should re-port the model :-)

**Comment by patrickvonplaten** [comment]
It was trained with quantization if I remember correctly
