### ISSUE TITLE
Transfer learning on bert

### ISSUE THREAD

**Issue by gopalpurama** [huggingface/transformers#11194]
We take pretrained bert model and passing our dataset we save model on .bin file and we take predictions.
But how can we retrain a model with new data set on top of generated bin file 
Please help me on this issue

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
