### ISSUE TITLE
How to extract the specific output using the method "encoder_output[0]"

### ISSUE THREAD

**Issue by bruceszq** [huggingface/transformers#11203]
Dear Transformers Team

Thank you very much for Transformers which provides me solutions for relation extraction problems. I have a question. My input is like " [E1]Jack[/E2] was born in [E2]London[/E2]". I want to only extract the sequence output of "[E1] and "[E2]" with the method of "encoder_output[0]". And then concat the [CLS] output and sequence output of "[E1] and "[E2]". Could you help me solve the problem? This is a question that I took more than a month to thank aout the solution but I am not able to solve it. Thank you very much for your help. Thank you!

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
