### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.modeling_camembert'

### ISSUE THREAD

**Issue by siwarBM** [huggingface/transformers#11204]
## Environment info

`transformers` version: 4.2.2
-Python version: 3.7.9
- PyTorch version (GPU?):1.7.1
- Tensorflow version (GPU?) : 2.4.1
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by NielsRogge** [comment]
Which version of Transformers are you using?

If you're using one of the latest versions of Transformers, `modeling_camembert.py` will be located at `transformers.models.camembert.modeling_camembert.py`.
