### ISSUE TITLE
Rework examples/ to overwrite cache_dir for datasets too. 

### ISSUE THREAD

**Issue by philschmid** [huggingface/transformers#11205]
# 🚀 Feature request

Currently, you can pass [cache_dir](https://github.com/huggingface/transformers/blob/ef102c48865d70ff354b8ba1488d3fa8bfc116d8/examples/seq2seq/run_summarization.py#L79) into the `examples/` script to overwrite the `cache_dir` of [model config and tokenizers](https://github.com/huggingface/transformers/blob/ef102c48865d70ff354b8ba1488d3fa8bfc116d8/examples/seq2seq/run_summarization.py#L336). 
What would be the best way to adjust this to be able to use the `cache_dir` parameter for `datasets` [load_dataset](https://github.com/huggingface/transformers/blob/ef102c48865d70ff354b8ba1488d3fa8bfc116d8/examples/seq2seq/run_summarization.py#L313) method and `transformers`

## Motivation

When running training on Amazon SageMaker the cache_dir (`~/.cache/`) is not mounted to an EBS and cannot be increased. Therefore we need an option to point the `cache_dir` to an EBS backed directory for using the `examples/` scripts with large datasets.

**Comment by sgugger** [comment]
Well someone would need to go other all the examples and add it as an argument in those calls to `load_dataset`.

**Comment by philschmid** [comment]
Would you still keep it in 
```python
@dataclass
class ModelArguments:
```
I can adjust the examples in the near future. I just wanted to align on we can adjust this.

**Comment by sgugger** [comment]
We can switch it but to be honest it's more an internal class to the script than something of real significance so we don't really care.
