### ISSUE TITLE
Question about validation_set

### ISSUE THREAD

**Issue by Shengyu-Liu558** [huggingface/transformers#11217]
I want to ask a simple question. The parameters of the model have been set before model training. What is the purpose of the validation set in model training? Thank you！

**Comment by NielsRogge** [comment]
Hi,

You can use Stackoverflow for that: https://stats.stackexchange.com/questions/19048/what-is-the-difference-between-test-set-and-validation-set

We like to keep Github issues for feature requests/bug reports. There's also the [forum](https://discuss.huggingface.co/) where you can ask training-related questions.

Thanks!
