### ISSUE TITLE
Load BART-base error

### ISSUE THREAD

**Issue by ahmad-abdellatif** [huggingface/transformers#11216]
## Environment info

- `transformers` version: 4.5.0 
- simpletransformers: 0.61.4
- Platform: CentOS
- Python version: Python 3.8.2
- PyTorch version (GPU?): torch-1.8.1 (yes)
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

Models:
- bart: @patrickvonplaten, @patil-suraj

## Information

Model I am using (Bert, XLNet ...): Bart

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details below)

## To reproduce

I downloaded the bart-base and un zip it.  I have the following code:

`
from sklearn.model_selection import train_test_split
from simpletransformers.seq2seq import Seq2SeqModel, Seq2SeqArgs

model_args = Seq2SeqArgs()
model_args.do_sample = True
model_args.eval_batch_size = 64
model_args.evaluate_during_training = True
model_args.evaluate_during_training_steps = 2500
model_args.evaluate_during_training_verbose = True
model_args.fp16 = False
model_args.learning_rate = 5e-5
model_args.max_length = 128
model_args.max_seq_length = 128
model_args.num_beams = None
model_args.num_return_sequences = 3
model_args.num_train_epochs = 2
model_args.overwrite_output_dir = True
model_args.reprocess_input_data = True
model_args.save_eval_checkpoints = False
model_args.save_steps = -1
model_args.top_k = 50
model_args.top_p = 0.95
model_args.train_batch_size = 8
model_args.use_multiprocessing = False
model_args.wandb_project = "Paraphrasing with BART"

model = Seq2SeqModel(
    encoder_decoder_type="bart",
    encoder_decoder_name="/home/ahmad2/.cache/huggingface/transformers/bart-base",
    args=model_args,
    use_cuda = False,
    from_tf=True,
}`

However, the above code throws the following error:
`Traceback (most recent call last):
  File "original_BART.py", line 109, in <module>
    model = Seq2SeqModel(
  File "/home/ahmad2/.local/lib/python3.8/site-packages/simpletransformers/seq2seq/seq2seq_model.py", line 275, in __init__
    self.model = model_class.from_pretrained(encoder_decoder_name)
  File "/home/ahmad2/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1065, in from_pretrained
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/home/ahmad2/.cache/huggingface/transformers/bart-base' at '/home/ahmad2/.cache/huggingface/transformers/bart-base/pytorch_model.bin'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.`

I am not sure if there is an issue with the above code. Thanks in advance!

**Comment by patil-suraj** [comment]
This seems to be an issue with `simpletransformers` so please post it there since we won't get time to look into other code bases to fix such issues.
