### ISSUE TITLE
PyTorch library dependency

### ISSUE THREAD

**Issue by makcedward** [huggingface/transformers#1122]
## 🐛 Bug

Model I am using (Bert, XLNet....): XLNet

Language I am using the model on (English, Chinese....): English

```
pytorch_transformers\modeling_xlnet.py in forward(self, input_ids, token_type_ids, input_mask, attention_mask, mems, perm_mask, target_mapping, head_mask)
    925             # `1` indicates not in the same segment [qlen x klen x bsz]
    926             seg_mat = (token_type_ids[:, None] != cat_ids[None, :]).long()
--> 927             seg_mat = F.one_hot(seg_mat, num_classes=2).to(dtype_float)
    928         else:
    929             seg_mat = None

AttributeError: module 'torch.nn.functional' has no attribute 'one_hot'
```

## To Reproduce

1. Install pytprch 1.0.1 version
2. Use XLNet model to do the prediction.

'torch.nn.functional''s 'one_hot' function introduced from [1.1.0](https://pytorch.org/docs/1.1.0/nn.html#one-hot) while [requirements.txt](https://github.com/huggingface/pytorch-transformers/blob/master/requirements.txt#L2 ) requests 1.0.0+

**Comment by tayciryahmed** [comment]
I have the same issue with `pytorch 1.0.1.post2`. I am not sure this is specific to `pytorch-transformers` because when I perform the below test, I get the same error:
```
import torch 
import torch.nn.functional as F
F.one_hot(torch.tensor([1]))
```
When pytorch version is upgraded (to `1.2.0` for instance), this error is removed, however I get an import error:

```
ImportError: /opt/conda/lib/python3.7/site-packages/fused_layer_norm_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
```

**Comment by tayciryahmed** [comment]
For some reason, I had to reinstall apex after upgrading pytorch.

**Comment by shiningliang** [comment]
> For some reason, I had to reinstall apex after upgrading pytorch.

So have you fixed your ImportError？ I met this error when initializing BertAdam. I will try to migrate my code from pytorch-pretrained-bert to pytorch-transformers.

**Comment by tayciryahmed** [comment]
Yes, upgraded pytorch, then reinstalled apex.

**Comment by shiningliang** [comment]
> Yes, upgraded pytorch, then reinstalled apex.

Thank you. I will try.

**Comment by sajastu** [comment]
Just to confirm, I had the same issue. As @tayciryahmed said, re-installing apex would do the trick as it did for me :)
