### ISSUE TITLE
Extracting Features Example

### ISSUE THREAD

**Issue by SaschaStenger** [huggingface/transformers#1123]
## ❓ Questions & Help

Hello. 

Sorry, if my question is out of date or i just didn't find it, but i'm looking for the example/extract_features.py 
that was supposed to be in in this repo (as mentioned in this stackoverflow  [post](https://stackoverflow.com/questions/55369821/how-to-train-a-neural-network-model-with-bert-embeddings-instead-of-static-embed)) and can't find it anymore. Was it just in an earlier release and got scrapped?

Thank you in advance for any help

**Comment by thomwolf** [comment]
Yes it was removed from the repo. I think we’ll add it again (and update it
to pytorch-transformers) since several people have been missing it.

Cc @LysandreJik

**Comment by SaschaStenger** [comment]
That's nice to hear. Thank you very much

**Comment by hsajjad** [comment]
Any update on the extract_features script?
