### ISSUE TITLE
position_ids generated from Roberta

### ISSUE THREAD

**Issue by hwijeen** [huggingface/transformers#11242]
Hi,

Roberta created `position_ids` from `input_ids` using [this function](https://github.com/huggingface/transformers/blob/3d339ee6595b9e42925559ae21a0f6e77f032873/src/transformers/models/roberta/modeling_roberta.py#L1494).
When the max sequence length is 512, I expect the `position_ids` to be [0, 1, ..., 512].
However, the function gives me [1, 2, ..., 513] which later results in an CUDA index error for position embedding.
I would appreciate if someone could tell me what I am doing wrong.
```python

def create_position_ids_from_input_ids(input_ids, padding_idx, past_key_values_length=0):
    mask = input_ids.ne(padding_idx).int()
    incremental_indices = (torch.cumsum(mask, dim=1).type_as(mask) + past_key_values_length) * mask
    return incremental_indices.long() + padding_idx

ipdb> input_ids
tensor([[    2,    20,   630,  ...,    22,    20,     3],
        [    2,   168,   106,  ...,     4, 31532,     3],
        [    2,   287, 14603,  ...,   284,  1594,     3],
        ...,
        [    2,     4,   873,  ...,  5549, 24276,     3],
        [    2,    12,    56,  ...,    87,   419,     3],
        [    2, 30683,   419,  ...,   761,   312,     3]], device='cuda:0')

ipdb> incremental_indices
tensor([[  1,   2,   3,  ..., 510, 511, 512],
        [  1,   2,   3,  ..., 510, 511, 512],
        [  1,   2,   3,  ..., 510, 511, 512],
        ...,
        [  1,   2,   3,  ..., 510, 511, 512],
        [  1,   2,   3,  ..., 510, 511, 512],
        [  1,   2,   3,  ..., 510, 511, 512]], device='cuda:0',
       dtype=torch.int32)

ipdb> padding_idx
0

```

**Comment by NielsRogge** [comment]
See https://github.com/huggingface/transformers/issues/10736#issuecomment-800175342

Tip: if you search on this Github repo "position ids roberta", you get a lot of answers.
