### ISSUE TITLE
Multi-Workers distributed training

### ISSUE THREAD

**Issue by Gforky** [huggingface/transformers#11264]
Hi, does transformers support multi-workers distributed training for bert fine-tuning?

**Comment by LysandreJik** [comment]
Hi, here are a few resources to get you started:
- [Examples](https://github.com/huggingface/transformers/tree/master/examples)
- [Docs on distributed training](https://huggingface.co/transformers/examples.html#distributed-training-and-mixed-precision)

**Comment by Gforky** [comment]
> Hi, here are a few resources to get you started:
> 
> * [Examples](https://github.com/huggingface/transformers/tree/master/examples)
> * [Docs on distributed training](https://huggingface.co/transformers/examples.html#distributed-training-and-mixed-precision)

Got it, after I get familiar with pytorch, this problem solved😀
