### ISSUE TITLE
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect

### ISSUE THREAD

**Issue by deadsoul44** [huggingface/transformers#11263]
Probably due to assertion, traceback is lost and I cannot debug the code. 

C:\Users\m00596504\.virtualenvs\porn_tr\lib\site-packages\transformers\modeling_utils.py:1759: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert all(

Process finished with exit code -1073741819 (0xC0000005)

**Comment by LysandreJik** [comment]
Hi, please provide all the information required in the template so that we may help you. Thanks!
