### ISSUE TITLE
squad_convert_example_to_features is broken

### ISSUE THREAD

**Issue by brian8128** [huggingface/transformers#11272]
## Environment info
- `transformers` version: 4.2.2
- Platform: Linux-4.15.0-132-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.7.1+cu101 (True)
- Tensorflow version (GPU?): No
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@sgugger 

Models:

NA

## Information

The squad_convert_example_to_features function requires a tokenizer but there is no way to give it one so you always get `NameError: name 'tokenizer' is not defined`

## To reproduce

Call `squad_convert_example_to_features` with any input. 

## Expected behavior

Convert a squad example to features.

**Comment by cronoik** [comment]
Please use `squad_convert_example_to_features_init(yourtokenizer)` to set the tokenizer.
