### ISSUE TITLE
gpt-neo 2.7 crashes, 1.3 runs fine

### ISSUE THREAD

**Issue by caseybasichis** [huggingface/transformers#11271]
Loading the generator crashes Python

```
python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import pipeline
>>> generator = pipeline('text-generation', model='EleutherAI/gpt-neo-2.7B', device=0)
[2]+  Killed                  python3
Killed
```

I have an A6000 with 48gb.
... it looks like I'm running on 16gb of ram?? maybe a stick is dead -- usually 32gb.

Is it a system ram issue?

## Environment info
- `transformers` version: 4.5.0
- Platform: Linux-5.4.0-70-generic-x86_64-with-glibc2.29
- Python version: 3.8.5
- PyTorch version (GPU?): 1.9.0.dev20210217+cu112 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by LysandreJik** [comment]
I would guess that's a memory issue indeed! That should be the only difference between the two checkpoints.

**Comment by caseybasichis** [comment]
Oof makes sense.  I'll check back if that doesn't fix it.  Thanks!
