### ISSUE TITLE
Zero-shot pipeline feature extraction

### ISSUE THREAD

**Issue by rodrigoheck** [huggingface/transformers#11287]
Is it possible to extract the hidden states representation from the zero-shot pipeline? I have these two tasks: feature extraction and zero-shot classification. But I don't want to load the same model twice, since it is a major burden on GPU memory. Any suggestions to how I can do both tasks without having to load it twice?

**Comment by zxcvb4657** [comment]
The

**Comment by rodrigoheck** [comment]
> The

Yes?

**Comment by rodrigoheck** [comment]
Answering my question: pipeline returns the model as well. You just have to use it directly to extract the hidden states.
