### ISSUE TITLE
small bug in RAG model

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/transformers#11303]
## Environment info

- `transformers` version: 4.5.1
- Platform: Linux-5.4.0-66-generic-x86_64-with-glibc2.27
- Python version: 3.8.3
- PyTorch version (GPU?): 1.8.1+cu111 (True)

### Who can help
@ola13 

Models:

- rag

## Information

Model I am using (Bert, XLNet ...): RAG

The problem arises when using:
* [ ] the official example scripts: seems to be a bug in https://github.com/huggingface/transformers/blob/master/src/transformers/models/rag/modeling_rag.py#L306
To pass my own question encoder the argument needs to be `question_encoder_model`, but the suffix ("model") gets trimmed because the len is taken according to `question_question_encoder_`.

```python
kwargs_question_encoder = {
            argument[len("question_question_encoder_") :]: value
            for argument, value in kwargs.items()
            if argument.startswith("question_encoder_")
        }
```

## To reproduce

```python
question_encoder = AutoModel.from_pretrained("any model")
rag_model = model_class.from_pretrained_question_encoder_generator(
        question_encoder_model=question_encoder, generator_pretrained_model_name_or_path=generator_name_or_path, config=rag_config
    )
```

## Expected behavior

be able to pass a question encoder **model** and not just a config to the rag model.

**Comment by patrickvonplaten** [comment]
This indeed looks like a typo! Thanks for your issue :-)

The kwargs should not be trimmed by `"question_question_encoder"`, but by `"question_encoder"`.

Would you like to open a PR to fix it? Otherwise I can do it as well :-)

**Comment by patrickvonplaten** [comment]
Unping
