### ISSUE TITLE
Problems with webbased editing of model cards 

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#11302]
When I open a model in hugging face model repository - like here: https://huggingface.co/german-nlp-group/electra-base-german-uncased

And then click "Edit model card" the text in the webbased editor contains `\r` characters. When the webbased editor is now used to save the modelcard these characters are saved and shown.

See screenshot:
![image](https://user-images.githubusercontent.com/229382/115135797-88865c00-a01b-11eb-9fae-de9fc3b48908.png)

This is a bug.

**Comment by PhilipMay** [comment]
The probem only seems to happen on some models. This model here works ok: https://huggingface.co/T-Systems-onsite/cross-en-de-roberta-sentence-transformer

**Comment by julien-c** [comment]
Tagging @Pierrci for visibility

**Comment by Pierrci** [comment]
Hi @PhilipMay, thank you for reporting this, we just deployed a fix for that, let us know if you still encounter the problem, otherwise feel free to close the issue :)

**Comment by PhilipMay** [comment]
Works now. Thanks.
