### ISSUE TITLE
Error in loading model tokenizer ('Helsinki-NLP/opus-mt-en-fr' actually loads 'Helsinki-NLP/opus-mt-en-de')

### ISSUE THREAD

**Issue by BenoitDalFerro** [huggingface/transformers#11319]
## Environment info

- `transformers` version: 4.3.3
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.7.1
- PyTorch version (GPU?): 1.7.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: not at this stage in the code
- Using distributed or parallel set-up in script?: no

### Who can help
@patrickvonplaten as per https://huggingface.co/transformers/model_doc/marian.html specifications

Models:

- marian : @patrickvonplaten

Library:

- tokenizers: @LysandreJik

Documentation: @sgugger

## Information

Model I am using : MarianMT, 'Helsinki-NLP/opus-mt-en-fr' 

The problem arises when using:

[X] the official example scripts

The tasks I am working on is:
not relevant

## To reproduce

```
from transformers import (MarianMTModel, MarianTokenize)

MT_model_name = 'Helsinki-NLP/opus-mt-en-fr'
MT_tokenizer = MarianTokenizer.from_pretrained(MT_model_name)

def download_vocab_files_for_tokenizer(tokenizer, model_type, output_path='/vocab'):
    vocab_files_map = tokenizer.pretrained_vocab_files_map
    vocab_files = {}
    for resource in vocab_files_map.keys():
        print (vocab_files_map[resource])
        download_location = vocab_files_map[resource][model_type]
        f_path = os.path.join(output_path, os.path.basename(download_location))
        urllib.request.urlretrieve(download_location, f_path)
        vocab_files[resource] = f_path
    return vocab_files

vocab_files = download_vocab_files_for_tokenizer(tokenizer=MT_tokenizer, model_type=MT_model_name, output_path="/vocab")
```

> {'Helsinki-NLP/opus-mt-en-de': 'https://cdn.huggingface.co/Helsinki-NLP/opus-mt-en-de/source.spm'}
> 
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-6-9d4f64132d23> in <module>
> ----> 1 process_datasets(source_datasets_paths, dataset_dir, test_mode=True, clean_sentences=True, translate=False)
> 
> ~\...py in process_datasets(source_datasets_paths, dataset_dir, test_mode, clean_sentences, translate, max_sample, negative_sampling)
>     171             MT_model_name = 'Helsinki-NLP/opus-mt-en-fr'
>     172             MT_tokenizer = MarianTokenizer.from_pretrained(MT_model_name)
> --> 173             vocab_files = download_vocab_files_for_tokenizer(tokenizer=MT_tokenizer, model_type=MT_model_name, output_path="/vocab")
>     174 
>     175             print (vocab_files)
> 
> ~...py in download_vocab_files_for_tokenizer(tokenizer, model_type, output_path)
>      29         print (vocab_files_map[resource])
>      30         print (model_type)
> ---> 31         print (vocab_files_map[resource][model_type])
>      32         download_location = vocab_files_map[resource][model_type]
>      33         f_path = os.path.join(output_path, os.path.basename(download_location))
> 
> KeyError: 'Helsinki-NLP/opus-mt-en-fr'

## Expected behavior

> {'Helsinki-NLP/opus-mt-en-fr': 'https://cdn.huggingface.co/Helsinki-NLP/opus-mt-en-fr/source.spm'}

Then function outputs a dictionnary containing for the 'Helsinki-NLP/opus-mt-en-fr' key, the corresponding value being a path to file found remotely at https://cdn.huggingface.co/Helsinki-NLP/opus-mt-en-fr/source.spm (checked link it works) downloaded on local folder ./vocab

**Comment by sgugger** [comment]
You should upgrade to the last version of transformers, which fully relies on the repository of a pretrained model instead of using special files like here.

**Comment by BenoitDalFerro** [comment]
Thanks!
