### ISSUE TITLE
batch_encode_plus set a sort parameter

### ISSUE THREAD

**Issue by yuys0602** [huggingface/transformers#11332]
# 🚀 Feature request

When use `tokenizer.batch_encode_plus`, I hope get the sorted results, so hope have the sort parameter.
Such as: `tokenizer.batch_encode_plus(..., sorted=True)`

**Comment by LSinev** [comment]
Sorted by length?
How this helps you?

**Comment by yuys0602** [comment]
> Sorted by length?
> How this helps you?

for next lstm layer
