### ISSUE TITLE
absolute embeddings in Deberta

### ISSUE THREAD

**Issue by ylwangy** [huggingface/transformers#11345]
The paper says they add absolute position embeddings at the last layer, however, the models is still using the addition of position embeddings and word embeddings.

In configuration_deberta.py
------------
 position_biased_input (:obj:`bool`, `optional`, defaults to :obj:`True`):
          Whether add absolute position embedding to content embedding.

default setting: position_biased_input=True

**Comment by BigBird01** [comment]
> The paper says they add absolute position embeddings at the last layer, however, the models is still using the addition of position embeddings and word embeddings.
> 
> ## In configuration_deberta.py
> position_biased_input (:obj:`bool`, `optional`, defaults to :obj:`True`):
> Whether add absolute position embedding to content embedding.
> 
> default setting: position_biased_input=True

It's disabled by the model_config.json along with the model repository.

**Comment by qhd1996** [comment]
The implementation of Deberta is actually not the same as the paper, the absolute embeddings should be added at the last two layers.
