### ISSUE TITLE
Whyhttps://github.com/huggingface/transformers/tree/master/examples/pplm

### ISSUE THREAD

**Issue by 27182812** [huggingface/transformers#11356]
## Environment info

- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by 27182812** [comment]
The html doesn‘t work. I can't see "https://github.com/huggingface/transformers/tree/master/examples/pplm".

**Comment by vickysvicky** [comment]
Did something went wrong? A lot of the scripts are gone like there used to be examples for clm and plm in transformers/examples/language-modeling but now there's only run_mlm_noflax.py

**Comment by 27182812** [comment]
Soga，haha. Thank you!

**Comment by vickysvicky** [comment]
Apparently they are moving stuff around. So what was originally `transformers/examples/language-modeling` has become `transformer/examples/pytorch/language-modeling` now. So maybe you can look around to find if they've moved what you're looking for into some other folder.

**Comment by 27182812** [comment]
I got it. Thank you very much!
