### ISSUE TITLE
Wav2vec2: comparison to original implementation

### ISSUE THREAD

**Issue by cceyda** [huggingface/transformers#11376]
# 🚀 Reproducibility challenge 

During the fine-tuning week I realized some of the smaller details in the implementation are a bit different than the original fairseq implementation. @patrickvonplaten 

Original Code: https://github.com/pytorch/fairseq/blob/master/fairseq/models/wav2vec/wav2vec2.py
🤗 Code: https://github.com/huggingface/transformers/blob/master/src/transformers/models/wav2vec2/modeling_wav2vec2.py

For example in `compute_mask_indices` function comparing scripts:
- There are naming differences, not that important as long as it is *documented* somewhere(?) for people transitioning to 🤗 & trying to replicate with the same hyper-parameters.
    `mask_time_prob=mask_prob (in fairseq)`
    `mask_time_length=mask_length(in fairseq)`
    `mask_feature_prob=mask_channel_length(in fairseq)`
    `mask_feature_length=mask_channel_length (in fairseq)`
   Also with the naming of different dropouts.

- But there are also seem to be some un-specified parameters:
`no_overlap`,`min_space`.
https://github.com/pytorch/fairseq/blob/05b86005bcca0155319fa9b81abfd69f63c06906/fairseq/models/wav2vec/wav2vec2.py#L348

Not sure how these effect, didn't look deeply, wanted to report just in case.

## Motivation

I realized while digging deeper because there was minor differences on results while finetuning (might be also be a fairseq problem https://github.com/pytorch/fairseq/issues/1448)

## Your contribution

opening this issue 😛

**Comment by patrickvonplaten** [comment]
Hey @cceyda - thanks for the issue!

Yes, this was an intentional choice since those parameters seemed to be the same in all experiments after studying the paper. If people want to change those params, we could always add them in a later version.
