### ISSUE TITLE
S3 checkpoints not working with distributed training on sagemaker 

### ISSUE THREAD

**Issue by laphang** [huggingface/transformers#11390]
## Environment info

- `transformers` version: 4.5.0
- Platform: AWS Sagemaker
- Python version: 3.6
- PyTorch version (GPU?): 1.7.1
- Tensorflow version (GPU?):
- Using GPU in script?: yes 
- Using distributed or parallel set-up in script?: yes 

### Who can help

@sgugger 

## Information

Model I am using (Bert, XLNet ...): gpt-neo

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Use the run_clm.py example script to finetune gpt-neo in Sagemaker with either torch.distributed.launch, or using Sagemaker distributed model parallel (say on a p4d.24xlarge with 8 gpus)
2. Only the first checkpoint is synced to the checkpoint_s3_uri location. Subsequent checkpoints do not appear in S3
3. Also, at the end of the training job, it spends around 1 hour in the "Uploading" state and ends with the error below. 

InternalServerError: We encountered an internal error. Please try again.

## Expected behavior

I expected the training to work normally, and all the checkpoints and final model to get synced to the S3 location. 

NB: training is working when I don't use the checkpoint_s3_uri (with both torch.distributed.launch and sagemaker distributed model parallel).

Also with a single gpu (on a p3.2xlarge), training with checkpoint_s3_uri is working, all the checkpoints and final model are synced to S3.

**Comment by sgugger** [comment]
cc @philschmid

**Comment by philschmid** [comment]
Hey @laphang, 

Could you please share your `estimator` configuration? that would help debug and reproduce your problem. Thanks!

**Comment by philschmid** [comment]
@laphang I tried to reproduce your error and for me its works using the following `HuggingFace` estimator. 
```python
# estimator
huggingface_estimator = HuggingFace(entry_point='run_glue.py',
                                    source_dir='./scripts',
                                    metrics_definition=metric_definitions,
                                    instance_type=instance_type,
                                    instance_count=instance_count,
                                    volume_size=volume_size,
                                    role=role,
                                    transformers_version='4.4.2',
                                    pytorch_version='1.6.0',
                                    checkpoint_s3_uri=f's3://{sess.default_bucket()}/checkpoints',
                                    py_version='py36',
                                    distribution= distribution,
                                    hyperparameters = hyperparameters,
                                    debugger_hook_config=False)
```
This estimator just extends the estimator from our [04_distributed_training_model_parallelism](https://github.com/huggingface/notebooks/blob/master/sagemaker/04_distributed_training_model_parallelism/sagemaker-notebook.ipynb) and includes the `checkpoint_s3_uri`. 
![Bildschirmfoto 2021-04-23 um 14 08 55](https://user-images.githubusercontent.com/32632186/115869189-d2b57600-a43d-11eb-90d7-7a4c2df70f18.png)

> ## Environment info
> * `transformers` version: 4.5.0
> * Platform: AWS Sagemaker
> * Python version: 3.6
> * PyTorch version (GPU?): 1.7.1
> * Tensorflow version (GPU?):
> * Using GPU in script?: yes
> * Using distributed or parallel set-up in script?: yes

Reading your **environment** it seems that you are not yet using the new Hugging Face Deep Learning Container for Amazon SageMaker. Is that true? or have you update them?

**Comment by laphang** [comment]
@philschmid 
Ah yes, I'm still using the PyTorchEstimator and installing transformers via requirements.txt. I'll try again with the HuggingFace Estimator and get back to you guys. Thanks for the quick response.

**Comment by laphang** [comment]
@philschmid  yeah, made the changes below from using the PyTorch estimator to the HuggingFace one, and now distributed training with s3 checkpoints is working properly now (training job completes successfully, and all the checkpoints are synced to s3). It's working both using Sagemaker distributed model parallel, and also using torch.distributed.launch

Also just wanted to say that I was pleasantly surprised with how seamlessly Transformers is working with SageMaker model parallel. Great work guys!

```
before:
estimator = PyTorch(base_job_name=job_name,     
                       entry_point = 'run_clm.py', 
                       source_dir=source_dir,
                       code_location=output_path,
                       role=role,
                       framework_version='1.7.1',
                       py_version='py3',                    
                       hyperparameters=hyperparameters,
                       tags=tags, 
                       output_path=output_path, 
                       checkpoint_s3_uri=checkpoint_path, 
                       instance_count=1, 
                       instance_type='ml.p4d.24xlarge', 
                       distribution= distribution, 
                       use_spot_instances=train_use_spot_instances,
                       max_run=train_max_run,
                       max_wait=train_max_wait, 
                       metric_definitions=metric_definition
                       )

after:
estimator = HuggingFace(base_job_name=job_name,     
                       entry_point = 'run_clm.py', 
                       source_dir=source_dir,
                       code_location=output_path,
                       role=role,
                       transformers_version='4.4.2',
                       pytorch_version='1.6.0',
                       py_version='py36',                    
                       hyperparameters=hyperparameters,
                       tags=tags, 
                       output_path=output_path, 
                       checkpoint_s3_uri=checkpoint_s3_uri, 
                       debugger_hook_config=False,
                       instance_count=1, 
                       instance_type='ml.p4d.24xlarge', 
                       distribution= distribution, 
                       use_spot_instances=train_use_spot_instances,
                       max_run=train_max_run,
                       max_wait=train_max_wait, 
                       metric_definitions=metric_definition
                       )
```

**Comment by philschmid** [comment]
@laphang that are great news and thank you for the kind words! 🤗

**Comment by philschmid** [comment]
@laphang that are great news and thank you for the kind words! 🤗  
Should you have any questions or problems in the future feel free to tag me directly in the issue.

**Comment by Harshitcmd** [comment]
Hey @philschmid,

I tried adding overwrite_output_dir=True, it's partially solved my issue. Now, the checkpoints are in sync with s3(all the checkpoints and model artifacts are getting saved at the desired location). Even though all the checkpoints got uploaded to the s3 it has showed the status as **Uploading** for an hour and ended with an internal error(weird).

PS: When I didn't integrate the data parallelism with the same instance type (p4d.24xlarge) everything worked seamlessly.

**Comment by nicolaiberk** [comment]
Is there any way to do this locally without the estimator? I am trying to train modernBERT from scratch, which afaik requires the development version of transformers, which I have to install myself using

```
pip install git+https://github.com/huggingface/transformers.git
```

which seems to break the Estimator environment (pardon for the bad description, I have a very shallow understanding of what the estimator actually does).

So I am trying to set up my own container, simply passing the s3 URI to `get_last_checkpoint` (and later `trainer.save_model`), but this results in `FileNotFoundError`. The weird thing is that the data loads fine from s3 using `load_dataset`, at least when using the RevisedDownloadConfig referenced [here](https://github.com/huggingface/datasets/issues/6598#issuecomment-1926271027).
