### ISSUE TITLE
Documentation 404 error

### ISSUE THREAD

**Issue by gwc4github** [huggingface/transformers#11404]
For this page: https://huggingface.co/transformers/examples.html
several (all?) of the links in the "The Big Table of Tasks" section are getting a 404 error.
Ex: https://github.com/huggingface/transformers/tree/master/examples/token-classification

**Comment by hassaanhameed786** [comment]
thanks alot

**Comment by TheColorman** [comment]
[https://huggingface.co/transformers/examples.html](https://huggingface.co/transformers/examples.html) now points towards [https://huggingface.co/docs/transformers/main/en/examples](https://huggingface.co/docs/transformers/main/en/examples), which is a 404.
