### ISSUE TITLE
How to use GPU when running run_summarization.py

### ISSUE THREAD

**Issue by liubest** [huggingface/transformers#11409]
When I run run_summarization.py on my computer and my computer has 2 GPUs. But the code didn't run with gpu cuda and is very very slow. Can anyone tell me how to use transformers with GPU? Thank you very much!

**Comment by patil-suraj** [comment]
Hi @liubest 

Please make sure that your torch installation can detect the GPU. All scripts will run on GPU if it's available.
If you want to run on multiple GPUs, follow the docs [here](https://github.com/huggingface/transformers/tree/master/examples/pytorch#distributed-training-and-mixed-precision).

And if you just want to use a single GPU, you could select the device by setting `CUDA_VISIBLE_DEVICES=0" which will select the first GPU.
