### ISSUE TITLE
Download offile HuggingFace Models in other format than ".bin" Format

### ISSUE THREAD

**Issue by deepaksinghtopwal** [huggingface/transformers#11401]
# 🚀 Feature request
### Just wandering if there is any other way of downloading Huggingface models in a restricted environment?

For example : 
**a.)** we have a network which doesn't allow downloading the model by internet (so the auto download feature in transformer wont work), 
**b.)** we can't download Bin files(So cannot download the files from "Models" option in Huggingface.co)
**c.)** Using the Git clone option gives the Proxy error.

So is there any other way which can be used to download the Huggingface Models ?

**Comment by julien-c** [comment]
Not sure how to help here... can you download the files from another machine and sync them to the restricted env?

**Comment by deepaksinghtopwal** [comment]
No, that's the only problem that all the devices within organization are same network and have same policies(as mentioned above).. :)
I see huggingFace has already provided many methods but the challenge is that none of it is working for me ..

But it does support downloading other format(i.e. i recently downloaded models from Easyocr in .pth  and Spacy language models) , So just a query if any solution can be provided around that which can help me using Hugginface models in such restricted environment..
