### ISSUE TITLE
`sp_model_kwargs` param missing at unpickle in `XLMRobertaTokenizer`

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#11429]
When `XLMRobertaTokenizer` is unpickled the `sp_model_kwargs` is not set. See:

https://github.com/huggingface/transformers/blob/35cd8eed887891bee60194a95adc35b884f68f55/src/transformers/models/xlm_roberta/tokenization_xlm_roberta.py#L178

PS: I will provide a fix.

**Comment by PhilipMay** [comment]
fix pr at #11430

**Comment by LysandreJik** [comment]
Closed by #11430, thanks @PhilipMay!
