### ISSUE TITLE
tensorflow version is not able to pick the trained model from local directory in an air gapped system

### ISSUE THREAD

**Issue by hiteshkum123** [huggingface/transformers#11433]
hi ,
i have trained  the TFBertForSequenceClassification model and i have to deploy the trained model in an air gapped server.

code -
from transformers import BertTokenizer, TFBertForSequenceClassification
from transformers import InputExample, InputFeatures

model1=TFBertForSequenceClassification.from_pretrained(local_path)
tokenizer1=BertTokenizer.from_pretrained(loacal_path)

 ImportError: cannot import name 'TFBertForSequenceClassification' from 'transformers' (unknown location)

Same code works if i am using the PyTorch version( BertForSequenceClassification)

**Comment by LysandreJik** [comment]
Did you install TensorFlow in your environment? You might need a more recent TensorFlow version if so.
