### ISSUE TITLE
Feedback whilst resuming

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/transformers#11440]
# 🚀 Feature request

Add some sort of progress bar during resumption of training from a checkpoint

## Motivation

I resumed training from a checkpoint mid-way through a 100 Epoch training. The progress bar sat on zero for quite some time, and I could see CPU activity but no GPU's were active. Eventually the progress bar jumped to 50% and training resumed - I assume it's doing some sort of initialisation.

It would be nice if there were some indication that some progress is being made as it's not obvious what's occuring

**Comment by sgugger** [comment]
This has been fixed by #11324. If you use a source install, you will be able to use (or in this case see) this feature :-)
