### ISSUE TITLE
cannot import name 'set_seed' from 'transformers'

### ISSUE THREAD

**Issue by andy311p** [huggingface/transformers#11454]
i run with transformers==4.5.1 and get the following error:
![image](https://user-images.githubusercontent.com/68938613/116115472-18cf3b80-a6c3-11eb-9a2d-f3c9ad1d5588.png)

do you know how to resolve this issue?

thanks

**Comment by bihani-g** [comment]
Try the following code:
`from transformers.trainer_utils import set_seed`
Let me know if it works.
