### ISSUE TITLE
extending metric_for_best_model to a list of strings 

### ISSUE THREAD

**Issue by dorooddorood606** [huggingface/transformers#11459]
# 🚀 Feature request

Hi
Currently ` metric_for_best_model(:obj:`str`, `optional`) ` only covers one metric, for some datasets like MRPC, one have several metrics, like accuracy/F1 or like in STSB both pearson/spearman, and user might need to choose the best based on average on all metrics, it could be helpful to have this option.

This is related to the trainer @sgugger 

thanks.

**Comment by flckv** [comment]
> 

hi @sgugger is it already added since then or should we use the workaround?
