### ISSUE TITLE
[Docs] Add Caching Example For CI? 

### ISSUE THREAD

**Issue by hamelsmu** [huggingface/transformers#11479]
From the [installation instructions](https://huggingface.co/transformers/installation.html#caching-models):

> If you expect to be downloading large volumes of models (more than 10,000) from huggingface.co (for instance through your CI setup, or a large-scale production deployment), please cache the model files on your end. It will be way faster, and cheaper. Feel free to contact us privately, we’d love to help with this.

I'm happy to write an example of how to cache with GitHub Actions.  Shall I contribute this to the docs?  If so, please assign the issue to me and I'll do it.   If this is not a good idea, please feel free to close the issue.

@sgugger

**Comment by sgugger** [comment]
This was written by @julien-c so I'll let him reply on this :-)

**Comment by julien-c** [comment]
This was written before we moved from S3 to our own Cloudfront-served repositories so we could also probably just remove that paragraph.

**Comment by hamelsmu** [comment]
Interesting. Maybe it could _still_ a good reminder as many folks would forget to do this (I know I might have and have wasted so much of my own compute!)?

However, I'll open a PR to remove the paragraph if that's preferred 🙇🏽
