### ISSUE TITLE
Importing problem 

### ISSUE THREAD

**Issue by abetatos** [huggingface/transformers#11487]
- `transformers` version: 4.5.1
- It just cannot import the version., . cannot import name 'PegasusTokenizer' from 'transformers', python 3.8

**Comment by TingNLP** [comment]
try the newest version 4.6.0.dev0

![image](https://user-images.githubusercontent.com/54096137/116375279-b81a3d00-a841-11eb-9771-c54c8de789bc.png)

**Comment by LysandreJik** [comment]
Could you install `sentencepiece` and try again? The `PegasusTokenizer` is based on the `sentencepiece` library.

**Comment by dk6304273089** [comment]
Iam also facing the same issue
