### ISSUE TITLE
encoder decoder in transformers

### ISSUE THREAD

**Issue by lytum** [huggingface/transformers#11505]
Thanks for your contribution for EncoderDecoderModel

I want to ask a question about the pool_layer of encoder.

Generally the default 'add_pooling_layer=True' in encoder, while the output of encoder in EncoderDecoder is without pool_layer. Is my understanding correct?

Now i want to add a classification layer in encoder, how should i do now?

Thanks in advance

**Comment by patil-suraj** [comment]
Hi there!

It would be nice if you ask such questions on the [forum](https://discuss.huggingface.co/). Use issues to report bugs and for feature requests or anything else that can't be discussed on the forum. Thanks!
