### ISSUE TITLE
I-BERT: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by fdlci** [huggingface/transformers#11509]
Hi, I have an issue when running this code provided by the HF documentation:
>>> from transformers import RobertaTokenizer, IBertForTokenClassification
>>> import torch

>>> tokenizer = RobertaTokenizer.from_pretrained('kssteven/ibert-roberta-base')

When running this i get the following error for the tokenizer:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by LysandreJik** [comment]
Hi! I believe this checkpoint does not have a slow tokenizer, only a fast tokenizer. Can you try with:

```py
from transformers import RobertaTokenizerFast
tokenizer = RobertaTokenizerFast.from_pretrained('kssteven/ibert-roberta-base')
```

**Comment by fdlci** [comment]
Thank you! It loaded the tokenizer without showing an error.

**Comment by Moeus** [comment]
> Hi! I believe this checkpoint does not have a slow tokenizer, only a fast tokenizer. Can you try with:
> 
> from transformers import RobertaTokenizerFast
> tokenizer = RobertaTokenizerFast.from_pretrained('kssteven/ibert-roberta-base')

I come up with the same problem ，how to solve it？
The model link is "https://huggingface.co/ValkyriaLenneth/longformer_zh/tree/main"
<img width="1327" height="627" alt="Image" src="https://github.com/user-attachments/assets/e4461ef6-6ce9-4ef5-be15-36f1b393bb5f" />
