### ISSUE TITLE
RoBERTa adds two sep tokens

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/transformers#11519]
## Environment info

- `transformers` version: 4.5.1
- Platform: Linux-5.4.0-72-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.6
- PyTorch version (GPU?): NA
- Tensorflow version (GPU?): NA
- Using GPU in script?: NA
- Using distributed or parallel set-up in script?: NA

## Information

I'm using RoBERTa. I noticed when I pass a text pair, two <eos> tokens are added - see the linked code

https://github.com/huggingface/transformers/blob/f37f2adb68b186f175a81a870cc526349385b9a8/src/transformers/models/roberta/tokenization_roberta_fast.py#L230

This differs to the BERT implementation

https://github.com/huggingface/transformers/blob/60d5bda4fd0381075a300dc11903c76df694bd1c/src/transformers/models/bert/tokenization_bert_fast.py#L255

Is this intentional? I'm trying to create a hybrid BERT/RoBERTa style training strategy. I want to pass two sentances but I don't want to use NSP so I was hoping to use my existing custom RoBERTa tokenizer. I ran into two issues - this, and the fact that as per the comment "RoBERTa does not make use of token type ids, therefore a list of zeros is returned." - this comment also doesn't appear correct, from what I can see Roberta's Tokenizer simply does not return `token_type_ids` I've not figured out why yet 

EDIT: seems the default for `return_token_type_ids` is different for BERT (true) and RoBERTa (false).

Also as far as I can see RoBETa will use `token_type_ids` if they're provided, It's just that the tokeniser has been coded to return all zeros.

https://github.com/huggingface/transformers/blob/f37f2adb68b186f175a81a870cc526349385b9a8/src/transformers/models/roberta/modeling_roberta.py#L79

**Comment by cronoik** [comment]
> Is this intentional? 
Yes. It is in line with the original implementation. (Check [link](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.md) for more information).

> I ran into two issues - this, and the fact that as per the comment "RoBERTa does not make use of token type ids, therefore a list of zeros is returned." - this comment also doesn't appear correct, from what I can see Roberta's Tokenizer simply does not return token_type_ids I've not figured out why yet
The comment is also correct. The original RoBERTa doesn't even have a token_type layer and the huggingface Roberta has one which is just full of zeros (i.e. does nothing as long as you don't do something with it) and only exists due to legacy reasons (check #2871).

**Comment by david-waterworth** [comment]
Thanks, it appears I can put a BERT tokeniser in front of a RoBERTa mlm model and get why I want.

**Comment by cronoik** [comment]
You can put every tokenizer in front of RoBERTa, but when you use the pre-trained weights you should stick to the original one as it will otherwise lead to garbage. :)

**Comment by david-waterworth** [comment]
Yeah I understand that but I'm training from scratch.
