### ISSUE TITLE
Idea to improve DistilBERT

### ISSUE THREAD

**Issue by tchaton** [huggingface/transformers#1151]
## 🚀 Feature

Based on https://medium.com/huggingface/distilbert-8cf3380435b5, you are using KL_loss to train the student from the teacher.

You can do something a little bit different there.

Loss = KL_loss(teacher, student when teacher is right) and CE(when the teacher is wrong).
Therefore, the student should converge to be better than the teacher by no learning from its mistake. 

Or even better, you could correct the teacher by artificially telling him the GT;
By replacing in the teacher prediction the GT class probability value by 1 and then renormalizing 
by the sum of probs (here: some of sort of artificial smooth).

## Motivation

Improve DistillBert performance.

**Comment by AlexYoung757** [comment]
good idea.  i aggree with the second idea

**Comment by tchaton** [comment]
If you give it a try, please tell me in the loop : thomas.chaton.ai@gmail.com

**Comment by malarinv** [comment]
There is Albert now https://arxiv.org/abs/1909.11942 which seems to be even better. It isn't based on KD.

**Comment by AlexYoung757** [comment]
anthor solution is here. [https://github.com/intersun/PKD-for-BERT-Model-Compression](url)
