### ISSUE TITLE
Compute probability of target sentences given an input

### ISSUE THREAD

**Issue by fferlito** [huggingface/transformers#11522]
I need to test the probabilities that the model would produce certain outputs. Let me give you an example:
I have a source sentence X, and several possible target sentences Y1, Y2, Y3, Y4 , ... 

I want to know if I can compute the probability that the model would give to each of the translation Y, given X. 
Is there a function to compute these values?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
