### ISSUE TITLE
How to set up a custom tokenizer for distilbart

### ISSUE THREAD

**Issue by neptune233** [huggingface/transformers#11521]
Hi, I am currently using the distillbart. I pretrained a bart-large model with my own Chinese corpus and I just simply map each character to an id when I do the pre-training. In the distillition.py, the path or name of the tokenizer should be defined. My question is how can I build a custom tokenizer class which can be used in the code? Assume that we get a word dictionary which map character to the input id when I do the pre-training. 

Thank you.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
