### ISSUE TITLE
why run_translation.py automatically is running on cpu?

### ISSUE THREAD

**Issue by Aniruddha-JU** [huggingface/transformers#11548]
-`transformers` version: 4.5.0
- Platform: linux
- Python version: 3.8
- PyTorch version (GPU?): 1.7.1
- Tensorflow version (GPU?):
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?:yes

@patrickvonplaten, @patil-suraj
Models: mbart-large-50

**Comment by patil-suraj** [comment]
Could you please post the command that you used?

**Comment by Aniruddha-JU** [comment]
I run the command for telugu to telugu


 python examples/pytorch/translation/run_translation.py     --model_name_or_path  facebook/mbart-large-50     --do_train     --do_eval     --do_predict     --source_lang te_IN     --target_lang te_IN     --test_file /home/aniruddha/mbart/     --train_file "/content/te_train_mbart.json"     --validation_file "/content/te_dev_mbart.json"     --source_prefix "translate Telugu to Telugu: "     --output_dir "/content/transformers/examples/pytorch/summarization/chkpt"     --overwrite_output_dir yes     --per_device_train_batch_size=1     --per_device_eval_batch_size=2     --predict_with_generate yes

**Comment by Aniruddha-JU** [comment]
@patil-suraj

**Comment by LysandreJik** [comment]
Hi! Is your CUDA environment correctly set up? What is the output of the following in your environment?
```
python -c "import torch;print(torch.cuda.is_available())"   
```

**Comment by Aniruddha-JU** [comment]
True

**Comment by LysandreJik** [comment]
Then it should run on GPU. Why do you say it doesn't?

**Comment by Why1005** [comment]
I have same issues. How do you solve it ?
