### ISSUE TITLE
Error when trying to use GPTNeo model

### ISSUE THREAD

**Issue by PimTournaye** [huggingface/transformers#11543]
## Environment info

- `transformers` version: 4.6.0.dev0
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.8.7
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.4.0 (False)
- Using GPU in script?: Not yet
- Using distributed or parallel set-up in script?: yes

### Who can help

Models:

- gpt2: @patrickvonplaten
- tensorflow: @Rocketknight1 

## Information

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)
Using GPTNeo

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)
I want to try to convert GPT-Neo to a TF.js model for a class

## To reproduce

1. pip install transformers
2. import the necessary parts
3. run file

Here's the error I get after running:
```
model = GPTNeoForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B")
AttributeError: type object 'GPTNeoForCausalLM' has no attribute 'from_pretrained
```

## Expected behavior

The model should be saved in a new folder.

**Comment by patrickvonplaten** [comment]
I cannot reproduce the error. `GPTNeoForCausalLM` clearly has a `from_pretrained(...)` method

**Comment by PimTournaye** [comment]
Not sure what I'm doing wrong then. I'll post another snippet. 

`from transformers import GPT2Tokenizer, GPTNeoForCausalLM, pipeline
import tensorflowjs

tokenizer = GPT2Tokenizer.from_pretrained('EleutherAI/gpt-neo-1.3B')
#model = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B')
model = GPTNeoForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B")

model.save("./test_gptneo")`

**Comment by patil-suraj** [comment]
Hi there, this is because PyTorch is not installed. Currently, GPT Neo is only implemented `pt` and `pt` should be installed if you want to use a model implemented in PyTorch.

When it's not installed a dummy object is returned, which is the reason for the above error.

**Comment by LysandreJik** [comment]
It would be nice to output a warning when a dummy object is imported, because that is quite an opaque error otherwise.

**Comment by patil-suraj** [comment]
@LysandreJik 

The issue is that the `from_pretrained` method which raises the warning in dummy objects is not implemented for `GPTNeoForCausalLM`
https://github.com/huggingface/transformers/blob/a5d2967bd8a5ed2456c593fa9eb5d9c0d726ae7a/src/transformers/utils/dummy_pt_objects.py#L1509-L1512

There are few more dummy objects which don't have this method implemented.

**Comment by PimTournaye** [comment]
Thanks all, after installing PyTorch, the script does run, only for me to discover that it doesn't have a .save method. Guess I should have looked into that. Any pointers on how I could convert this model to Tensorflow, or even better, TF.js? I might have overlooked a method while browsing through the scripts.

**Comment by patil-suraj** [comment]
All Transformers models have `save_pretrained` method, `save` is the wrong method name.

**Comment by willieseun** [comment]
Were you able to convert the model to Tensorflow?
