### ISSUE TITLE
AttributeError: 'TrainingArguments' object has no attribute 'resume_from_checkpoint' in training GPT2

### ISSUE THREAD

**Issue by vittot** [huggingface/transformers#11561]
## Environment info

 `transformers` version: 4.6.0.dev0
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.8.9
- PyTorch version (GPU?): 1.8.1+cpu (False)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help
@patrickvonplaten @sgugger 

## Information

Model I am using: GPT-2

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details below)

## To reproduce

I am running

```
subprocess.call([python_path,
                     'transformers/examples/pytorch/language-modeling/run_clm.py',
                     '--model_type', 'gpt2',
                     '--model_name_or_path', 'gpt2',
                     '--train_file', 'train.txt',
                     '--do_train',
                     '--validation_file', 'eval.txt',
                     '--do_eval',
                     '--per_gpu_train_batch_size', '1',
                     '--save_steps', '-1',
                     '--num_train_epochs', '2',
                     '--output_dir', output_dir])
```
and after the downloads/initialization phase I obtain the following:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "transformers/examples/pytorch/language-modeling/run_clm.py", line 459, in <module>
    main()
  File "transformers/examples/pytorch/language-modeling/run_clm.py", line 417, in main
    if training_args.resume_from_checkpoint is not None:
AttributeError: 'TrainingArguments' object has no attribute 'resume_from_checkpoint'
```

I tried to debug it and in effect the `TrainingArguments` object doesn't have the attribute `resume_from_checkpoint`. I see that it is indicated as an optional field, but on google colab, with the same command, it is present, with value None, as expected. 

## Expected behavior

It should start the training, and the weird thing is that running it on Google Colab it works perfectly.

**Comment by sgugger** [comment]
You don't have the latest master installed and the examples are synced with it. The easiest way is probably to do:
```
pip uninstall transformers
pip install git+https://github.com/huggingface/transformers
```
to upgrade to the latest!

Otherwise you can do an [editable install](https://huggingface.co/transformers/installation.html#editable-install) to avoid those problems in the future.

**Comment by vittot** [comment]
You are right, I even tried to pull from the repo, but I didn't realize my installation was not synched with it. Now it should be, using the editable install. 
Thank you!
