### ISSUE TITLE
no connection error

### ISSUE THREAD

**Issue by Aniruddha-JU** [huggingface/transformers#11576]
- `transformers` version: 4.5.0
- Platform: linux
- Python version: 3.8
- PyTorch version (GPU?): 1.7.1
- Tensorflow version (GPU?):
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?:

Models: mbart and mt5

 @patrickvonplaten, @patil-suraj

output: ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

**Comment by LysandreJik** [comment]
Please put the code you used that led to this error.
