### ISSUE TITLE
reformer-enwik8 Fine-tuning

### ISSUE THREAD

**Issue by WHU-Peter** [huggingface/transformers#11571]
Could you pls provide a demo for training and Fine-tuning the model of 'reformer-enwik8'? @patrickvonplaten

**Comment by patil-suraj** [comment]
Hi, you could use [this ](https://colab.research.google.com/github/patrickvonplaten/notebooks/blob/master/PyTorch_Reformer.ipynb) notebook as a reference, it shows how to train reformer on the crime-and-punishment data. 

You could usually find such examples in the community notebooks section [here](https://huggingface.co/transformers/community.html). Also, please use [forum](https://discuss.huggingface.co/) to ask such questions.

**Comment by WHU-Peter** [comment]
@patil-suraj Thank you for your reply. Actually, I do not know how to build the enwik8 dataset, it do not need a tokenizer, which is different from others. I am an beginner
