### ISSUE TITLE
Support saving (and loading) models to a remote bucket

### ISSUE THREAD

**Issue by oriram** [huggingface/transformers#11579]
# 🚀 Feature request

Support saving and loading models to and from remote buckets, e.g. Google Cloud Storage and Amazon S3.

## Motivation

Currently this is not supported, making it more difficult to train in AWS/GCP.

**Comment by maximilianeber** [comment]
For reference, pandas leverages `s3fs` and `gcsfs`. A generic implementation is available through `fsspec.open()` (see [docs](https://filesystem-spec.readthedocs.io/en/latest/usage.html#higher-level)). Would the maintainers be open to that? I would be happy to contribute.

**Comment by Harish-Sridhar** [comment]
This seems to be a useful feature. any thoughts about implementation of this?

**Comment by pavanchhatpar** [comment]
[Hugging Datasets](https://huggingface.co/docs/datasets/filesystems.html) supports this feature. It really looks like a useful feature that the PreTrainedModel doesn't support today
