### ISSUE TITLE
unable to save model1.h5 .I am using huggingface distilbert

### ISSUE THREAD

**Issue by Somabhadra** [huggingface/transformers#11581]
Hi Team,
I was trying to save model but i got error.
model.save("model1.h5")
but it didn't work.
I tried different method like model.save("model1") so it will save as .pb file. But when i was trying to load I am getting below error. 
please let me know how to solved it. how can save model after using distil-bert with my model.
~\.conda\envs\bot2\lib\site-packages\tensorflow\python\keras\engine\training.py in get_config(self)
   2229 
   2230   def get_config(self):
-> 2231     raise NotImplementedError
   2232 
   2233   @classmethod

NotImplementedError:

**Comment by patil-suraj** [comment]
You should use the `save_pretrained` method to save the models.

**Comment by Somabhadra** [comment]
when i was trying to save model model.save_pretrained("./model/").
I got error
AttributeError: 'Functional' object has no attribute 'save_pretrained'
