### ISSUE TITLE
Punctuation in Wav2Vec2

### ISSUE THREAD

**Issue by krrishdholakia** [huggingface/transformers#11584]
Playing around with Wav2Vec2, and some of the sentences contain punctuation (like apostrophes, etc.) but i don't see any periods, question marks, commas etc. in my output. 

I'm not sure if this a new feature, or just a way of handling the processing, but would it be possible to get punctuation in the Wav2Vec2 outputs ?

**Comment by patrickvonplaten** [comment]
Hey @krrishdholakia,

Wav2Vec2 was fine-tuned mostly on Librispeech which does not contain any punctuation so it'll be very difficult for the model to predict punctuation. You could take a pre-trained Wav2Vec2 model and fine-tune it on a downstream task that contains punctuation. This should then just work fine

**Comment by raja1196** [comment]
I came across [this](https://huggingface.co/flexudy/t5-small-wav2vec2-grammar-fixer) t5 model trained to correct grammar outputs of wav2vec2. Not sure if this is what you were looking for @krrishdholakia, but you can pass the text to [this](https://huggingface.co/flexudy/t5-small-wav2vec2-grammar-fixer) model and get back punctuated sentences.
