### ISSUE TITLE
Windows Test Errors 

### ISSUE THREAD

**Issue by Lynx1820** [huggingface/transformers#11586]
There are some errors that I encounter when running tests on Windows. 

**tests\test_benchmark.py**
```
obj = <MemoryMeasureProcess(MemoryMeasureProcess-8, initial)>
 file = <_io.BufferedWriter name=10>, protocol = None

 def dump(obj, file, protocol=None):
     '''Replacement for pickle.dump() using ForkingPickler.'''
      ForkingPickler(file, protocol).dump(obj)
      AttributeError: Can't pickle local object 'measure_peak_memory_cpu.<locals>.MemoryMeasureProcess'
```

**tests/test_modeling_led.py**
`RuntimeError: 0INTERNAL ASSERT FAILED at "..\\torch\\csrc\\jit\\ir\\alias_analysis.cpp":532, please report a bug to PyTorch. We don't have an op for aten::constant_pad_nd but it isn't a special case.  Argument types: Tensor, int[], bool,`

**tests/test_modeling_bart.py**
The timeout-decorator uses SIGALRM, which causes an error on Windows. Can we skip this tests on Windows? 

**test_tokenization_wav2vec2.py** - makes the assumption that paths are separated with forward slashes, but Windows uses backslash. 
`    AssertionError: Sequences differ: ['added_tokens.json', 'special_tokens_map.j[39 chars]son'] != ['C:\\Users\\AzureUser\\AppData\\Local\\Tem[267 chars]son']`

**tests/test_utils_check_copies.py**
```
tests\test_utils_check_copies.py:76: in check_copy_consistency
  self.assertTrue(len(check_copies.is_copy_consistent(fname)) == 0)
   AssertionError: False is not true
```

**tests/extended/test_trainer_ext.py**
```
 def encode(self, input, final=False):
     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-59: character maps to <undefined>
```

[additional-logs.txt](https://github.com/huggingface/transformers/files/6422688/windows-logs.txt)

## Environment info
- `transformers` version: master
- Platform: Windows
- Python version:
- PyTorch version (GPU?): 1.8.1 10.2cuda 
- Tensorflow version (GPU?): none
- Using GPU in script?: 10.2cuda 

 @sgugger, @patil-suraj

**Comment by sgugger** [comment]
The tests are not run on Windows, so there is absolutely no guarantee any of them passes there.

**Comment by Lynx1820** [comment]
> The tests are not run on Windows, so there is absolutely no guarantee any of them passes there.

Isn't Windows a supported platform? If so, would it be helpful to run HF tests on Windows as well?
