### ISSUE TITLE
[RAG] ModuleNotFoundError: No module named 'git' when finetuning the model

### ISSUE THREAD

**Issue by giobin** [huggingface/transformers#11609]
## Environment info
- `transformers` version: 4.6.0.dev0
- Platform: Linux-3.10.0-1127.10.1.el7.x86_64-x86_64-with-debian-buster-sid
- Python version: 3.6.13
- PyTorch version (GPU?): 1.8.1+cu102 (False)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help
- rag: @patrickvonplaten, @lhoestq

## Information
I get an import error ModuleNotFoundError: No module named 'git' when running the RAG finetuning script.
I am not sure if the module `git` is somewhere in the project or must be installed. I am using a virtual environment built with `pip install -e '[.dev]'` from `/transformers` and `pip install -r requirements.txt` from /rag. 

The problem arises when using:
[RAG] finetune_rag.py
I'm using the original `finetune_rag.sh` script (here below) but without GPU and less iterations. I also modified the `finetune_ray.py` path in the command below from `examples/rag/finetune_rag.py` to just `finetune_rag.py` since there is no `examples/rag` directory in the repo. I call the script from the `transformers/examples/research_projects/rag/` directory. 

export PYTHONPATH="../":"${PYTHONPATH}"
python finetune_rag.py \
    --data_dir mydatadir \
    --output_dir myoutdir \
    --model_name_or_path facebook/rag-sequence-base \
    --model_type rag_sequence \
    --fp16 \
    --profile \
    --do_train \
    --do_predict \
    --n_val -1 \
    --train_batch_size 8 \
    --eval_batch_size 1 \
    --max_source_length 128 \
    --max_target_length 25 \
    --val_max_target_length 25 \
    --test_max_target_length 25 \
    --label_smoothing 0.1 \
    --dropout 0.1 \
    --attention_dropout 0.1 \
    --weight_decay 0.001 \
    --adam_epsilon 1e-08 \
    --max_grad_norm 0.1 \
    --lr_scheduler polynomial \
    --learning_rate 3e-05 \
    --num_train_epochs 10 \
    --warmup_steps 500 \
    --gradient_accumulation_steps 1 \`

The tasks I am working on is:
just to run the simplest finetuning exercise possible to get familiar with the haggingface library.

## To reproduce

1. `cd transformers/examples/research_projects/rag/`
2. `bash finetune_rag.sh` (the same code shown above)

Error:
`Traceback (most recent call last):
  File "finetune_rag.py", line 40, in <module>
    from callbacks_rag import (  # noqa: E402 # isort:skipq
  File "/nlu/users/giovanni_bonetta/transformers/examples/research_projects/rag/callbacks_rag.py", line 11, in <module>
    from utils_rag import save_json
  File "/nlu/users/giovanni_bonetta/transformers/examples/research_projects/rag/utils_rag.py", line 14, in <module>
    import git
ModuleNotFoundError: No module named 'git'
`

## Expected behavior
have the finetuning script recognising `git` and running.

**Comment by lhoestq** [comment]
Indeed you need to install `pip install GitPython` to make it work
I created a PR to add it to the requirements.txt of the RAG example

**Comment by giobin** [comment]
Thanks @lhoestq . I confirm that it works after installing GitPython.
