### ISSUE TITLE
TFWav2Vec2Model

### ISSUE THREAD

**Issue by will-rice** [huggingface/transformers#11603]
# 🌟 New model addition
I want a Tensorflow version of Wav2Vec2 and it's something I'm willing to work on. I just wanted to make sure no one else was working on it. I looked at the issues, PR's, and source code. The only mention of TFWav2Vec2Model is in the current docs so just wanted to double-check no one was working on this before I dive in. 

> vocab_size (int, optional, defaults to 32) – Vocabulary size of the Wav2Vec2 model. Defines the number of different tokens that can be represented by the inputs_ids passed when calling Wav2Vec2Model or TFWav2Vec2Model. 

## Model description
Tensorflow port of Wav2Vec2 

## Open source status
Tensorflow version of existing Transformers Model
* [x] the model implementation is available: (give details)
* [x] the model weights are available: (give details)
* [ ] who are the authors: (mention them, if possible by @gh-username)

**Comment by NielsRogge** [comment]
Sure, there's a [general conversion script](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_pytorch_checkpoint_to_tf2.py) that allows you to convert the weights from a PyTorch model to its TF counterpart. You only need to make sure that all the attributes of the TF model correspond to the names of the PyTorch model.

cc @patrickvonplaten

**Comment by patrickvonplaten** [comment]
@will-rice, adding TFWav2Vec2Model would be a great addition indeed -> I'm more than happy to help you on the PR
