### ISSUE TITLE
Model type to AutoModelForQuestionAnswering incorrect

### ISSUE THREAD

**Issue by AjaxFB** [huggingface/transformers#11604]
`model = AutoModelForQuestionAnswering.from_pretrained("dbmdz/german-gpt2")

ValueError: Unrecognized configuration class <class 'transformers.models.gpt2.configuration_gpt2.GPT2Config'> for this kind of AutoModel: AutoModelForQuestionAnswering.
Model type should be one of BigBirdConfig, ConvBertConfig, LEDConfig, DistilBertConfig, AlbertConfig, CamembertConfig, BartConfig, MBartConfig, 
LongformerConfig, XLMRobertaConfig, RobertaConfig, SqueezeBertConfig, BertConfig, XLNetConfig, FlaubertConfig, MobileBertConfig, XLMConfig, 
ElectraConfig, ReformerConfig, FunnelConfig, LxmertConfig, MPNetConfig, DebertaConfig, DebertaV2Config, IBertConfig.`

How i can convert Model Type? If its not possible, i need suggestions to solve this problem ;(

**Comment by patil-suraj** [comment]
`AutoModelForQuestionAnswering` expects a model with a span classification head on top, GPT2 is an auto-regressive language model and does not have `ForQuestionAnswering` class defined for it.
