### ISSUE TITLE
In "Question Answering" separate context from question

### ISSUE THREAD

**Issue by yoeldk** [huggingface/transformers#11610]
# 🚀 Feature request

## Motivation
Often one may have many questions on the same content. In the current implementation, the function will be called multiple times with the same context but with different questions causing a lot of computational time. 

## Idea
I was wondering if there's a way to speed up runtime by splitting the context and question instead of the single question_answering() which gets both arguments. 
This way the algorithmic parts that are only dependent on the context can be calculated once, and re-used many times when asking several questions on the same content.

**Comment by yoeldk** [comment]
Any update on this?

**Comment by LysandreJik** [comment]
Currently there is no way to handle this in the pipelines. You should be able to achieve this pretty simply by using a model/tokenizer without the pipeline. See here for an example of how to do that: https://huggingface.co/transformers/task_summary.html#extractive-question-answering

**Comment by yoeldk** [comment]
@LysandreJik In the link you had provided it looks like all the computation is being done in the loop that iterates over the questions, so no work is being done only once for the context outside the loop. Why do we have to tokenize the same context for every question?

**Comment by yoeldk** [comment]
> @yoeldk did you figure this out?

Not really, but I'm now dealing with other things so I decided to leave it
