### ISSUE TITLE
Error when using Adafactor without learn rate

### ISSUE THREAD

**Issue by oliverguhr** [huggingface/transformers#11612]
Hi,
I get these strange errors when I use the Adafactor.  This code will result in this (expected) error:
```
optimizer = Adafactor(model.parameters(), scale_parameter=True, relative_step=True, warmup_init=True, lr=1e-4)
```

> ValueError: Cannot combine manual `lr` and `relative_step=True` options

however, if I do not set a manual learn rate I get a different error. Btw: This code is recommended in the [documentation](https://huggingface.co/transformers/main_classes/optimizer_schedules.html?highlight=others%20reported%20following%20combination%20work%20well).
```
optimizer = Adafactor(model.parameters(), scale_parameter=True, relative_step=True, warmup_init=True, lr=None)
# same for 
optimizer = Adafactor(model.parameters(), scale_parameter=True, relative_step=True, warmup_init=True)
```
will return this error
> TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

## Environment info

- `transformers` version: 4.5.1
- Platform: Linux
- Python version: 3.7.1
- PyTorch version (GPU?): 1.8.0+cu111 and 1.8.1+cu111
- Tensorflow version (GPU?):  -
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help

Trainer: @sgugger

**Comment by sgugger** [comment]
This was added by @jsrozner and @stas00 in #10526, so pinging them here.

**Comment by oliverguhr** [comment]
Thank you for the feedback. I tried to install the latest transformers version from source using: 
```pip install git+https://github.com/huggingface/transformers```

However, the error message remains the same. Can you give me a hint where I can address this issue?

**Comment by stas00** [comment]
@oliverguhr, please always post a full traceback for errors. It's impossible otherwise to know where the error came from, please refer to https://github.com/huggingface/transformers/blob/master/ISSUES.md#the-github-issues item (3). 

The actual recommendation is:
```
Adafactor(model.parameters(), scale_parameter=False, relative_step=False, warmup_init=False, lr=1e-3)
```
The alternative one I saved because others said it worked well for them.

Once you post the full traceback then we can see why it fails.

Thank you!

**Comment by oliverguhr** [comment]
Thanks for looking at this @stas00 

Here is a stacktrace and this [is a notebook to reproduce the issue](https://colab.research.google.com/drive/1DFsmXObv8JVvGRbX8uc6_sfPfbAnKKMx?usp=sharing).

Hint: Depending on setting

```
lrs = get_constant_schedule_with_warmup(optimizer,100)
```
or 

```
lrs = none
```
`
get_constant_schedule_with_warmup` fails directly or `trainer.train()`.

```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-18-031302865887> in <module>()
     12 
     13 optimizer = Adafactor(model.parameters(), scale_parameter=False, relative_step=True, warmup_init=True, lr=None)
---> 14 lrs = get_constant_schedule_with_warmup(optimizer,100)
     15 
     16 training_args = TrainingArguments(

5 frames

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py in get_constant_schedule_with_warmup(optimizer, num_warmup_steps, last_epoch)
     67         return 1.0
     68 
---> 69     return LambdaLR(optimizer, lr_lambda, last_epoch=last_epoch)
     70 
     71 

/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py in __init__(self, optimizer, lr_lambda, last_epoch, verbose)
    201                     len(optimizer.param_groups), len(lr_lambda)))
    202             self.lr_lambdas = list(lr_lambda)
--> 203         super(LambdaLR, self).__init__(optimizer, last_epoch, verbose)
    204 
    205     def state_dict(self):

/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py in __init__(self, optimizer, last_epoch, verbose)
     75         self.verbose = verbose
     76 
---> 77         self.step()
     78 
     79     def state_dict(self):

/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py in step(self, epoch)
    150             if epoch is None:
    151                 self.last_epoch += 1
--> 152                 values = self.get_lr()
    153             else:
    154                 warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)

/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py in get_lr(self)
    249 
    250         return [base_lr * lmbda(self.last_epoch)
--> 251                 for lmbda, base_lr in zip(self.lr_lambdas, self.base_lrs)]
    252 
    253 

/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py in <listcomp>(.0)
    249 
    250         return [base_lr * lmbda(self.last_epoch)
--> 251                 for lmbda, base_lr in zip(self.lr_lambdas, self.base_lrs)]
    252 
    253 

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

```

**Comment by stas00** [comment]
Thank you for creating the reproducible colab notebook, @oliverguhr - that's very helpful.

So when you use `Adafactor(model.parameters(), scale_parameter=False, relative_step=False, warmup_init=False, lr=None)` the learning rate scheduling is performed internally by the optimizer and so there is no need for a scheduler. 

But I see that barebones HF Trainer doesn't support training w/o a scheduler. So we aren't quite supporting this option then and perhaps we should. 

Regardless of the outcome we should document the conclusion of this thread in the Adafactor docstring.

So here are a few ideas meanwhile:

1. Create a dummy scheduler that always returns a fixed lr, example:
```
from torch.optim.lr_scheduler import LambdaLR
class DummyLR(LambdaLR):
    def __init__(self, optimizer, lr=0):
        for group in optimizer.param_groups:
            group['initial_lr'] = 0
        lr_lambda = lambda x: lr
        super().__init__(optimizer, lr_lambda)
        for group in optimizer.param_groups:
            del group['initial_lr']

def get_dummy_schedule(optimizer):
    return DummyLR(optimizer)

lrs = get_dummy_schedule(optimizer) 
``` 

Let me know if this unblocks you a bit.

2. Probably can create a scheduler that gets its data from the optimizer. Let me experiment with that.

**Comment by stas00** [comment]
So @sgugger suggests the 3rd option. For that will have to track down all the cases where the scheduler is used and condition those on `scheduler != None`

Not sure about back-compat though since we auto-create a scheduler if it's not passed:

https://github.com/huggingface/transformers/blob/33fd83bc01e781633dad58a9de6c91591e2fc786/src/transformers/trainer.py#L817

**Comment by stas00** [comment]
Another proposition from @sgugger is:
>  this can be handled with the `lr_scheduler_type` argument: we could add an acceptable value "no"  that would leave the scheduler at `None`.

**Comment by oliverguhr** [comment]
@stas00 Sorry for the late reply and thanks for your feedback. The DummyLR worked for me, but this parameter combination did not improve my results, maybe these parameter settings are kind of an edge case. 

Regarding the 3rd option: Would it possible to check if ```lr_scheduler is None``` and ```optimizer is Adafactor``` and then auto-create an instance of the "AdafactorScheduler"? This could eliminate the need to check all the other parts of the code that rely on the LR value from the opimzier.

**Comment by stas00** [comment]
> Regarding the 3rd option: Would it possible to check if lr_scheduler is None and optimizer is Adafactor and then auto-create an instance of the "AdafactorScheduler"? This could eliminate the need to check all the other parts of the code that rely on the LR value from the opimzier.

@sgugger, what is your take - `AdafactorScheduler` is the hack I posted here: https://github.com/huggingface/transformers/issues/11612#issuecomment-833888170

I'm happy with either way, but let's resolve it one way or another.

**Comment by sgugger** [comment]
Mmm, the `lr_scheduler` is always None by default. Can we add a value `"adafactor"` that would use that `AdafactorScheduler`?

**Comment by stas00** [comment]
@oliverguhr, we went with the `AdafactorSchedule` - please check that it works for you

https://github.com/huggingface/transformers/pull/12123
