### ISSUE TITLE
Very large difference between the results after resume

### ISSUE THREAD

**Issue by dorooddorood606** [huggingface/transformers#11648]
Dear HuggingFace team,

There is unfortunately no option to reopen the bugs, the issue I reported here [1] still exists with testing the last version of transformers. I add my comments on the same ticket. Could you kindly reopen this bug?

The variations are very high after resume, which makes the results not usable with resuming after checkpoint, I also tried to make things deterministic in torch, but it also could not solve the issue. I study in an institution where I only have access to GPUs for short hours, and I very much appreciate your help on this issue to make training reproducible after resume from the checkpoints in trainer.

@sgugger 

[1] https://github.com/huggingface/transformers/issues/11323

**Comment by sgugger** [comment]
Please do not open a duplicate issue, you can reopen the old one.

**Comment by dorooddorood606** [comment]
Dear Sylvain
If huggingFace team closes an issue, the user is not able to reopen it, at least on my side, I also attached the screenshot of it. 

https://ibb.co/56S00LT

Thank you.

**Comment by sgugger** [comment]
Your screenshot does not show the bottom of the dialog box where there should be the button "Reopen" normally.

**Comment by dorooddorood606** [comment]
there is really no reopen on the users sides. Sure I will  make sure to ask and I will avoid recreate the issue, thank you very much for the remark :)  I pay attention

**Comment by dorooddorood606** [comment]
Dear @sgugger 

Thank you for the PR, I checked it with the last version of transformers now, and the issue still exists, please kindly run this command and break this after first 50 steps:
```
TASK_NAME=mrpc
python run_glue.py   --model_name_or_path bert-base-cased   --task_name $TASK_NAME   --do_train   --do_eval   --max_seq_length 128   --per_device_train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3   --output_dir /tmp/$TASK_NAME/  --eval_steps 50 --evaluation_strategy steps --load_best_model_at_end --fp16 --do_test  
```
Here are the results:
If you do not break:
```
After 50 steps:

{'eval_loss': 0.6383711695671082, 'eval_accuracy': 0.6764705882352942, 'eval_f1': 0.8070175438596491, 'eval_combined_score': 0.7417440660474717, 'eval_runtime': 2.1914, 'eval_samples_per_second': 93.091, 'eval_average_metrics': 0.7417440660474717, 'epoch': 0.43}

After 100 steps:
{'eval_loss': 0.6184656023979187, 'eval_accuracy': 0.6862745098039216, 'eval_f1': 0.813953488372093, 'eval_combined_score': 0.7501139990880072, 'eval_runtime': 2.1089, 'eval_samples_per_second': 96.731, 'eval_average_metrics': 0.7501139990880072, 'epoch': 0.87}
 ```

if you break after 50 steps:

```
After 100 steps
{'eval_loss': 0.6308265328407288, 'eval_accuracy': 0.6862745098039216, 'eval_f1': 0.813953488372093, 'eval_combined_score': 0.7501139990880072, 'eval_runtime': 2.1549, 'eval_samples_per_second': 94.668, 'eval_average_metrics': 0.7501139990880072, 'epoch': 0.87}                                                    
```

The differences accumulates and the results at the end varies a lot that resumed results are not usable.
I really appreciate if you could kindly have another look. Could you kindly reopen this issue as well?

thanks.
