### ISSUE TITLE
Reformer inference widget is broken

### ISSUE THREAD

**Issue by hamelsmu** [huggingface/transformers#11649]
From: https://huggingface.co/google/reformer-enwik8?text=My+name+is+Julien+and+I+like+to

![image](https://user-images.githubusercontent.com/1483922/117581699-17cede80-b0b3-11eb-8cb7-1bd790f2e8c2.png)

@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Yeah Reformer has no tokenizer so this doesn't work...sadly I also think since Reformer doesn't work super well, it's low priority to fix this (cc @Narsil )

**Comment by Narsil** [comment]
Seems like the tokenizer fix is not that hard to make given the README (simply byte shift+2).

However the code seems to refer to a spiece.model : https://github.com/huggingface/transformers/blob/master/src/transformers/models/reformer/tokenization_reformer.py#L37

How bad is reformer performing ? (I am also curious to know how bad are character level models)

**Comment by patrickvonplaten** [comment]
The character level Reformer  model does quite well at text generation

Here is a demo (from a while back) for generating Wikipedia like entries: 
https://colab.research.google.com/drive/1Oao8vBtDkz6v1E1efUhTlug5uuxC_BnE?usp=sharing
