### ISSUE TITLE
DISTILBERT: run_squad.py not working

### ISSUE THREAD

**Issue by fdlci** [huggingface/transformers#11656]
Hi, 

I am trying to use the transformers/examples/legacy/question-answering/run_squad.py script to train and evaluate DistilBERT on squad2.0. Unfortunately it throws the following error:

**TypeError: forward() got an unexpected keyword argument 'token_type_ids'**

I used the following tokenizer: distilbert-base-uncased

Is there a way for me to fix this issue? Thank you for your reply!

**Comment by LysandreJik** [comment]
Hi! This script is a legacy script that we will not be maintaining anymore. Have you tried with the `run_qa.py` script available [here](https://github.com/huggingface/transformers/tree/master/examples/pytorch/question-answering)? This script should be simpler to understand and more complete.

Let us know if you run in any issues, thanks.

**Comment by LysandreJik** [comment]
Ah, since you're using the squad V2 dataset I believe you must also tell the script that it should understand examples that don't have an answer. For this, you can add the `--version_2_with_negative` argument when running your script.

Does that help?
