### ISSUE TITLE
IBERT: Testing the speedup

### ISSUE THREAD

**Issue by fdlci** [huggingface/transformers#11662]
Hi,

I want to test IBERT's speedup, and I have done exactly what is said in https://huggingface.co/kssteven/ibert-roberta-base. For the quantization part, when I set quant_mode to true and run the evaluation again, I get a much slower model. What am I doing wrong?

Thank you for your reply!

**Comment by LysandreJik** [comment]
Hi! You may find the discussion in https://github.com/huggingface/transformers/issues/11312 by @kssteven418 interesting!
