### ISSUE TITLE
license missing for xlm-roberta-large, and bert-base-spanish-wwm models

### ISSUE THREAD

**Issue by devgunn** [huggingface/transformers#11670]
Hi HuggingFace team,
I am gratefully using many of huggingface models, but I have found 'xlm-roberta-large' model is missing its license policy.
also 'dccuchile/bert-base-spanish-wwm-uncased' and 'dccuchile/bert-base-spanish-wwm-cased'

[xlm-roberta-large](https://huggingface.co/xlm-roberta-large)
[dccuchile/bert-base-spanish-wwm-uncased](https://huggingface.co/dccuchile/bert-base-spanish-wwm-uncased)
[dccuchile/bert-base-spanish-wwm-cased](https://huggingface.co/dccuchile/bert-base-spanish-wwm-cased)

Could you please add license information using readme or model card or this thread?

Thanks !

**Comment by julien-c** [comment]
xlm-roberta should be licensed under MIT like all models available through [fairseq](https://github.com/pytorch/fairseq#license). @aconneau could you please confirm?
