### ISSUE TITLE
Trainer skips training when continuing training with model.from_pretrained()

### ISSUE THREAD

**Issue by elenif** [huggingface/transformers#11688]
I'm fine-tuning the gpt2 model using TFTrainer.

As I have to save some computational power, I needed to part the data set and train it one after another.

The first training (from TFGPT2LMHeadModel.from_pretrained('gpt2')) works well. After storing the model in a folder under a different name, and reloading it again to continue training, the trainer basically skips the training and stores the old model in the new model folder.

I don't understand the reason for this behavior.

transformers: 4.5.0
tensorflow:2.4.1

@Rocketknight1 

Training code:
```

def train(file, file_id, batch_size, num_epochs):
    tokenizer, vocab_size = load_tokenizer()
    max_seq_length = 1000

    args = TFTrainingArguments(output_dir='out_gpt',
                               num_train_epochs=num_epochs,
                               do_train=True,
                               per_device_train_batch_size=batch_size,
                               gradient_accumulation_steps=2,
                               max_grad_norm=1.0)

    data = prepare_pre_training_data_set(file, tokenizer, max_seq_length)
    print("Datasets loaded...")

    with args.strategy.scope():
        model = TFGPT2LMHeadModel.from_pretrained('gpt2_trained_' + str(file_id)) 

        optimizer = tf.keras.optimizers.Adam(lr=0.0005)
        cat_loss = tf.losses.CategoricalCrossentropy()
        model.compile(optimizer=optimizer, loss=cat_loss)

    trainer = TFTrainer(model=model,
                        train_dataset=data,
                        args=args)

    trainer.train()

    trainer.save_model("gpt2_trained_+str(file_id+1)")
```

**Comment by elenif** [comment]
I'm really sorry to may have bothered you with that. Turns out, it works when using a different GPU :) 

It struck me when I tested the same code with less data on my local machine, the trainer logged epochs (which it did not before), so I tested it on several devices. I was just a bit confused to be honest, since there were no errors/warnings thrown neither by tensorflow nor the transformers library even when using trainer (debug=True).

**Comment by Rocketknight1** [comment]
Hey! Don't worry about it - TFTrainer is currently not very maintained, and we're looking at switching away from it to a pure Keras framework, so some bits of it can be quite confusing right now. Don't be shy about letting us know if you run into other issues, especially if they look like they might be bugs at our end!
