### ISSUE TITLE
Mixed precision training : link broken

### ISSUE THREAD

**Issue by IvanoLauriola** [huggingface/transformers#11699]
A few weeks ago this link
https://github.com/huggingface/transformers/tree/master/examples/text-classification#mixed-precision-training
showed a comparison between models trained with and without mixed precision for a bunch of sequence/text classification tasks.

Now I think that link is broken and something (examples and similar) has been moved but I do not find the new location of this comparison.
Do you know where can I find that?

**Comment by NielsRogge** [comment]
Yes, it's here: https://github.com/huggingface/transformers/tree/master/examples/pytorch/text-classification#mixed-precision-training

**Comment by IvanoLauriola** [comment]
Cool, thank you!
