### ISSUE TITLE
How to use BERT or word embedding for e-commerce product classification. 

### ISSUE THREAD

**Issue by Raghavendra15** [huggingface/transformers#1170]
## ❓ Questions & Help

I want to classify products on an e-commerce site. For example, if we take Amazon for example if a product name is iPhone XS then it should be categorized to Electronics -> mobile, very straight forward, however, the problem comes when we train the model on clothes and many other sports items. 
For example: "George - George Men's Cargo Short" found on walmart is being classified as SPORTS & OUTDOOR, FASHION. However, it should be classified to Clothes.

Currently, we have tried text CNN but I'm very positive that BERT or other word embeddings can enhance the performance. 

Base Code: 
https://github.com/brightmart/text_classification
However, it appears that TextCNN is better than BERT as per the author of this repository. Does anyone know what's the ideal way to approach this problem?
![image](https://user-images.githubusercontent.com/7957331/64069995-c22b0900-cc24-11e9-8077-21313e38c970.png)

**Comment by nomorecoke** [comment]
you solve this problem?
