### ISSUE TITLE
channel_len specified but not used

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#11702]
Here `channel_len` is specified but not used. Smells like a possible bug.

https://github.com/huggingface/transformers/blob/f063c56d942737d2c7aac93895cd8310afd9c7a4/src/transformers/models/ibert/quant_modules.py#L133

**Comment by PhilipMay** [comment]
@LysandreJik or @sgugger could you please check this before it gets closed by the "stale bot"?

**Comment by LysandreJik** [comment]
cc @kssteven418
