### ISSUE TITLE
How to accelerate the inference speed when using pipeline

### ISSUE THREAD

**Issue by yananchen1989** [huggingface/transformers#11711]
> transformers version: 4.6.0.dev0
> torch version:1.8.1+cu102

I am using the simple API - pipeline, to do inference, where the input are tens of thousands of sentences.

```
nlp  = pipeline("text-generation", model= 'gpt2', device=0, return_full_text=False)
results = nlp(df_train['content'].tolist(), max_length=250, do_sample=True, top_p=0.9, top_k=0, \
                    repetition_penalty=1, num_return_sequences=64)
```
take the generation, for instance, I want to generate new synthesized samples from each sentence from the df_train.
The codes work well, but it is not fast enough. I mean the GPU usage is just 76% ~ 85%.
Is there any trick or parameters I can tune to speed up ?

Another question is that how can I eliminate the info:

> Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

**Comment by menaenahoro** [comment]
Hi @yananchen1989 did you get a solution yet
