### ISSUE TITLE
Plug a custom tokenizer into PreTrainedTokenizer

### ISSUE THREAD

**Issue by DhruvilKarani** [huggingface/transformers#11722]
Is there a clean way to use a customer tokenizer trained from the tokenizers library in a PretrainedTokenizer interface?

```
from tokenizers import Tokenizer
tokenizer = Tokenizer.from_file(config_file)

```

The config file is generated using tokenizer.save() method.

I want to use this tokenizer in a PretrainedTokenizer/PretrainedTokenizerFast class.

The closest thing I found in the existing issues is [this](https://github.com/huggingface/tokenizers/issues/259#issuecomment-625905930)

When I tried the above solution using a PretrainedTokenizer class, 

```
class CustomTokenizer(PreTrainedTokenizer):
    def __init__(
            self,
            vocab_file=vocab_file,
            merges_file=merges_file,
            bos_token="<s>",
            eos_token="</s>",
            sep_token="</s>",
            cls_token="<s>",
            unk_token="<unk>",
            pad_token="<pad>",
            mask_token="<mask>",
            **kwargs
        ):
        super().__init__(
            tokenizer,
            bos_token=bos_token,
            eos_token=eos_token,
            unk_token=unk_token,
            sep_token=sep_token,
            cls_token=cls_token,
            pad_token=pad_token,
            mask_token=mask_token,
            **kwargs,
        )
```

I got an exception

```

  File /path/custom_tokenizer.py", line 37, in __init__
    super().__init__(
TypeError: __init__() takes 1 positional argument but 2 were given
```

Is there a solution/workaround?

**Comment by LysandreJik** [comment]
Would this [documentation](https://huggingface.co/transformers/fast_tokenizers.html) help you out?

**Comment by DhruvilKarani** [comment]
This is exactly what I was looking for! No idea how I missed it. Thank you :)
