### ISSUE TITLE
`ci/circleci: run_tests_torch` reaches 10 min. time limit

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#11731]
`ci/circleci: run_tests_torch` reaches 10 min. time limit - see here:
https://app.circleci.com/pipelines/github/huggingface/transformers/23426/workflows/349bd527-b66a-46ed-a168-365794da6856/jobs/211948

**Comment by PhilipMay** [comment]
An other one here: https://app.circleci.com/pipelines/github/huggingface/transformers/23647/workflows/b0de5fa6-3f1d-446f-8ce9-11461ff1fb10/jobs/214869

**Comment by PhilipMay** [comment]
@sgugger are you aware of this issue?

**Comment by sgugger** [comment]
Yes we are aware. This is something we will work on in the next weeks, we're just wrapping another project first.

**Comment by PhilipMay** [comment]
Seems to be fixed now. Closing.
