### ISSUE TITLE
Cant load google/reformer-enwik8

### ISSUE THREAD

**Issue by hadaev8** [huggingface/transformers#11734]
OSError: Can't load tokenizer for 'google/reformer-enwik8'. Make sure that:

- 'google/reformer-enwik8' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'google/reformer-enwik8' is the correct path to a directory containing relevant tokenizer files

https://huggingface.co/google/reformer-enwik8?text=My+name+is+Julien+and+I+like+to

**Comment by cronoik** [comment]
Duplicate of #11649
