### ISSUE TITLE
mbart-large-cc25 tokenization_utils_fast.py TypeError 

### ISSUE THREAD

**Issue by lysa-n** [huggingface/transformers#11747]
## Environment info
Hi, I am trying to fine-tune a dutch summarization algorithm. I used the [following ](https://github.com/huggingface/notebooks/blob/master/examples/summarization.ipynb) example notebook provided by huggingface.co. 

To prepare the targets for the model, we need to tokenize them inside the as_target_tokenizer context manager. This will make sure the tokenizer uses the special tokens corresponding to the targets. This is achieved by running the following code:

```
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
  
tokenizer = AutoTokenizer.from_pretrained("facebook/mbart-large-cc25")

with tokenizer.as_target_tokenizer():
    print(tokenizer(["Hello, this one sentence", "This is another sentence."]))
```

However, I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-0fc6af9091da> in <module>()
----> 1 with tokenizer.as_target_tokenizer():
      2     print(tokenizer(["Hello, this one sentence", "This is another sentence."]))
      3 

3 frames
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_fast.py in convert_ids_to_tokens(self, ids, skip_special_tokens)
    293         tokens = []
    294         for index in ids:
--> 295             index = int(index)
    296             if skip_special_tokens and index in self.all_special_ids:
    297                 continue

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
How can I work around this TypeError? I am not a professional and this is actually the first time submitting any question at all. 
Thanks in advance :)

**Comment by vishal-burman** [comment]
Hi @lysa-n,
For multilingual models you must define input language(src_lang) and target language(tgt_lang). Since you are using it for summarization for the Dutch language the src_lang and tgt_lang will be the same.
This should work:
```python
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
  
tokenizer = AutoTokenizer.from_pretrained("facebook/mbart-large-cc25", src_lang='nl_XX', tgt_lang='nl_XX')

with tokenizer.as_target_tokenizer():
    print(tokenizer(["Hello, this one sentence", "This is another sentence."]))
```
Note: Please cross-check the Dutch language code

**Comment by lysa-n** [comment]
> Hi @lysa-n,
> For multilingual models you must define input language(src_lang) and target language(tgt_lang). Since you are using it for summarization for the Dutch language the src_lang and tgt_lang will be the same.
> This should work:
> 
> ```python
> from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
>   
> tokenizer = AutoTokenizer.from_pretrained("facebook/mbart-large-cc25", src_lang='nl_XX', tgt_lang='nl_XX')
> 
> with tokenizer.as_target_tokenizer():
>     print(tokenizer(["Hello, this one sentence", "This is another sentence."]))
> ```
> 
> Note: Please cross-check the Dutch language code

Hi @vishal-burman, 

This seems to work. Thank you so much!
