### ISSUE TITLE
Add batching to pipelines

### ISSUE THREAD

**Issue by skurzhanskyi** [huggingface/transformers#11761]
# Add batching to pipelines

Are there any plans to add a batching option to existing pipelines? Currently, the model tries to process all the input simultaneously, which sometimes (if the input is considerable) leads to memory errors.

**Comment by LysandreJik** [comment]
Hi! You may find the discussion on this PR useful: https://github.com/huggingface/transformers/pull/11251

**Comment by skurzhanskyi** [comment]
Thanks for explaining this
