### ISSUE TITLE
How to install previous versions of pytorch-transformers 

### ISSUE THREAD

**Issue by juliahane** [huggingface/transformers#1177]
Hi
I am using some codes requiring old versions of your work, do you mind telling me 
how to install old version of this repository?
thanks
Best
Julia

**Comment by LysandreJik** [comment]
You can install an older version using the standard pypi procedure: `pip install pytorch-transformers==$VERSION`. The examples showcased on this repository probably won't work on older versions though.

**Comment by juliahane** [comment]
HI
Thanks a lot, I need though a version which I think was called
pretrained_bert , thanks for your help.
Best
Julia

**Comment by LysandreJik** [comment]
I believe you can still install it with `pip install pytorch-pretrained-BERT==$VERSION`!
