### ISSUE TITLE
LongformerForSequenceClassification: global_attention_mask=None

### ISSUE THREAD

**Issue by jackashore** [huggingface/transformers#11791]
Hi, my question is, what happens if `global_attention_mask` in `LongformerForSequenceClassification` is not stated? Does it mean that only local attention works in this case? I haven't found anything about it in the docs. Thanks in advance!

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
