### ISSUE TITLE
[trainer] multi-node tweaks

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#11796]
As I'm using Trainer in a multi-node setup, I will use this issue to post the things that could be improved for that type of env.

1. Repeated logging for non-rank-0 process rank-0 machine:

I gathered all these that get repeated 16 times on a 16 nodes machine:

```
[INFO|trainer.py:1145] 2021-05-20 20:16:39,037 >> ***** Running training *****
[INFO|trainer.py:1146] 2021-05-20 20:16:39,037 >>   Num examples = 1000
[INFO|trainer.py:1147] 2021-05-20 20:16:39,037 >>   Num Epochs = 1
[INFO|trainer.py:1148] 2021-05-20 20:16:39,037 >>   Instantaneous batch size per device = 4
[INFO|trainer.py:1149] 2021-05-20 20:16:39,037 >>   Total train batch size (w. parallel, distributed & accumulation) = 256
[INFO|trainer.py:1150] 2021-05-20 20:16:39,037 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1151] 2021-05-20 20:16:39,037 >>   Total optimization steps = 4

100%|██████████| 4/4 [00:02<00:00,  1.95it/s][INFO|trainer.py:1341] 2021-05-20 20:16:41,214 >> 
{'train_runtime': 2.185, 'train_samples_per_second': 1.831, 'epoch': 1.0}
Training completed. Do not forget to share your model on huggingface.co/models =)

INFO:__main__:*** Evaluate ***
[INFO|trainer.py:2115] 2021-05-20 20:16:41,690 >> ***** Running Evaluation *****
[INFO|trainer.py:2117] 2021-05-20 20:16:41,690 >>   Num examples = 200
[INFO|trainer.py:2120] 2021-05-20 20:16:41,690 >>   Batch size = 4
```

Probably should check not only rank of the process, but also the rank of the machine, right?

@sgugger

**Comment by sgugger** [comment]
Mmm I guess there should be some argument controlling this: when I'm using multi-node I launch the command on two separate machines and have two separate terminals, so having both output the logs is helpful to know where each is at.

**Comment by stas00** [comment]
Absolutely agree for a few nodes! This becomes an issue on 64+ nodes ;) 

Let's have a flag that by default it logs on each node, and can be turned off if wanted.

This is all new so I'm first just sharing the things that can be improved

One other thing to figure out is pytorch error handling, when the launcher crashes it generated 64 interleaved tracebacks - impossible to understand what went wrong half the time... But that's not trainer-related...
