### ISSUE TITLE
[trainer] the noisy tensorflow loaded when asked explicitly not to load it

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#11793]
Unrequested TF loading and its noisy disrespectful logging is back it seems:

```
USE_TF=0 python  examples/pytorch/language-modeling/run_clm.py \
    --model_name_or_path $MODEL \
    --dataset_name $DATASET \
    --output_dir output_dir \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --max_train_samples 1000 \
    --max_eval_samples 200 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --num_train_epochs 1 \
    --warmup_steps 8 \
    --block_size 64 \
    --fp16 \
    --report_to none
```

```
r10i6n8: 2021-05-20 19:52:04.357654: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: [...]
r10i6n8: 2021-05-20 19:52:04.357677: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

I am testing multinode setups so am I'm getting hundreds of these! 256 gpus - 512 of these warnings!

How can we make sure that `USE_TF=0` is respected and `tensorflow` doesn't get loaded - I can't uninstall it since it's a shared environment.

Thank you!

@sgugger

**Comment by sgugger** [comment]
Indeed, the `import Trainer` seems to be importing TensorFlow again. Let me try to see if I can remove that.

**Comment by sgugger** [comment]
I messed up my branch and pushed directly on master by mistake, but I don't think it needs reverting and doing a PR since it's a short fix.
Short story is that I locally have no tensorflow import with `USE_TF=0` after [this commit](https://github.com/huggingface/transformers/commit/b8697bc62216b9e2ca60811626c6a6ca992b0d34). Can you confirm?

**Comment by stas00** [comment]
I confirm. Apologies I missed that request.

Thank you for fixing it!
