### ISSUE TITLE
facebook/mbart-large-50-one-to-many-mmt fails on Swahili

### ISSUE THREAD

**Issue by DCNemesis** [huggingface/transformers#11790]
## Environment info

- `transformers` version: 4.6.0
- Platform: Linux-5.4.109+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.8.1+cu101 (False)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

@patil-suraj @patrickvonplaten 

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ x] my own task or dataset: (give details below)

## To reproduce

1. Run the below code

```
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast`

model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")
tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")

article_hi = "संयुक्त राष्ट्र के प्रमुख का कहना है कि सीरिया में कोई सैन्य समाधान नहीं है"
article_en = "Let's try this again..."
article_sw = 'Mzozo wa Israeli na Palestina:Marekani imekuwa ikiilinda Israel na kuifanya kutogoopa kufanya lolote'

# translate Hindi to Swahili
tokenizer.src_lang = "hi_IN"
encoded_hi = tokenizer(article_hi, return_tensors="pt")
generated_tokens = model.generate(**encoded_hi, forced_bos_token_id=tokenizer.lang_code_to_id["sw_KE"])
output = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
print(output)

# translate English to Swahili
tokenizer.src_lang = "en_XX"
encoded_en = tokenizer(article_en, return_tensors="pt")
generated_tokens = model.generate(**encoded_en, forced_bos_token_id=tokenizer.lang_code_to_id["sw_KE"])
output = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
print(output)

#translate Swahili to English
tokenizer.src_lang = 'sw_KE'
encoded_sw = tokenizer(article_sw, return_tensors="pt")
generated_tokens = model.generate(**encoded_sw, forced_bos_token_id=tokenizer.lang_code_to_id["en_XX"])
output = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
print(output)
```

## Expected behavior

Output is: 
['U. N. head says there is no military solution in Syria']
["! Let's try this again..."]
['The Israeli Prime Minister in Palestine: He visited Israel and visited Israel on any day of the week. Read more']

The translation from Swahili to English works, but the translations to Swahili all end up in English.

**Comment by patil-suraj** [comment]
Hi @DCNemesis 

Does this happen for this specific example or for all the examples that you tried?

And this isn't really an issue with implementation. As the model is many-to-many is not trained in every single language pair this does happen in some cases. It's likey that there's far less data for X to Swalihi translation which could be the reason for this.

**Comment by DCNemesis** [comment]
@patil-suraj it fails every time I try English to Swahili. M2M100 does fine on the same tasks, so I'll probably just use that in this case, but it is hard to believe this is the intended behavior of mbart-large-50.

**Comment by ACForward** [comment]
This issue still has not been fixed. Mbart-large-50-many-to-many-mmt has the same issue.

**Comment by Witty-Kitty** [comment]
This issue has still not been fixed. 
I am unable to do translation either into or out of Kiswahili but tested other languages with the same code and it works fine.
