### ISSUE TITLE
bert model (bert-base-chinese) consumed too much memory

### ISSUE THREAD

**Issue by LiuChiennan** [huggingface/transformers#11803]
## Environment info

- `transformers` version: 4.6.0
- Platform: Linux-4.19.117.bsk.5-amd64-x86_64-with-debian-10.7
- Python version: 3.7.3
- PyTorch version (GPU?): 1.8.1+cu102 (False)
- Tensorflow version (GPU?): 2.5.0 (False)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

## Information

Model I am using Bert:

When I run a code like this: 
```
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained('bert-base-chinese')
bert = AutoModel.from_pretrained('bert-base-chinese')
tokens = tokenizer(query, answer, padding=True, truncation=True, max_length=128, return_tensors="pt")
out = bert(**tokens)
```
where query and answer are both tensors with batch size 128
however, it consumes over 10G memory in this line of code, ```out = bert(**tokens)```, anyone knows why?
and in the next iteration, it consumes 20, 30, 40G memory...

**Comment by LysandreJik** [comment]
A batch size of 128 is a lot! Are you using batch size 128 with sequence length 128?

**Comment by resquilleur** [comment]
Most likely you have a large tensor size of 128 * 128 * 768 - and also depends on what type of tensor data you put int32 / float32 / float64? Try to reduce the batch size, even to 2.

**Comment by LiuChiennan** [comment]
> A batch size of 128 is a lot! Are you using batch size 128 with sequence length 128?

yes,  maybe batch size 128 is large, but I don't know why the memory cost becomes larger in each iteration. I mean in the first iteration(with batch size 128) it consumes 10G, and when the process goes to the second iteration(still batch size 128), it consumes 20G, and 30G,40G,.....

**Comment by LiuChiennan** [comment]
> Most likely you have a large tensor size of 128 * 128 * 768 - and also depends on what type of tensor data you put int32 / float32 / float64? Try to reduce the batch size, even to 2.

The input tensor size actually is 128*128? I am just confused why the memory cost rises in each iteration.
