### ISSUE TITLE
CamemBert Tokenizer AttributeError: 'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by Quang-Vinh** [huggingface/transformers#11800]
## Environment info

- `transformers` version: 4.5.1
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.8.8
- PyTorch version (GPU?): 1.8.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: No

### Who can help

Library:
- tokenizers: @LysandreJik

## Information

Model I am using camemBert https://huggingface.co/camembert-base.

The problem arises when using:
* [x ] the official example scripts: 

``` python
from transformers import CamembertModel, CamembertTokenizer

# You can replace "camembert-base" with any other model from the table, e.g. "camembert/camembert-large".
tokenizer = CamembertTokenizer.from_pretrained("camembert-base")
camembert = CamembertModel.from_pretrained("camembert-base")

camembert.eval()  # disable dropout (or leave in train mode to finetune)

import torch
# Tokenize in sub-words with SentencePiece
tokenized_sentence = tokenizer.tokenize("J'aime le camembert !")
```

## To reproduce

1. Install transformers
2. Run code 

I get a AttributeError: 'NoneType' object has no attribute 'tokenize' Error as the tokenizer is None when I load from pre trained.

**Comment by LysandreJik** [comment]
Hi! Could you try installing `sentencepiece` to see if that solves the problem?

**Comment by Quang-Vinh** [comment]
I got an error when sentencepiece wasn't installed and after installing it returned None. Trying it again now I don't see the error anymore though so I'll close the issue 🙂

**Comment by LysandreJik** [comment]
If this was on colab it's possible that you needed the runtime to restart!
