### ISSUE TITLE
How to save and load model from local path in pipeline api ?

### ISSUE THREAD

**Issue by yananchen1989** [huggingface/transformers#11808]
In `from_pretrained` api, the model can be loaded from local path by passing the `cache_dir`. However, I have not found any parameter when using `pipeline` 

for example, `nlp = pipeline("fill-mask" , model = 'distilbert-base-uncased', device=0)`
how to save the downloaded model and load it next time from local path, rather than default cache path ?
Thanks.

**Comment by LysandreJik** [comment]
I don't think it's currently possible, you would have to specify the local path in `model` but it won't ping the custom `cache_dir`.

We would happily welcome a PR that enables that for pipelines, would you be interested in that?

**Comment by yananchen1989** [comment]
> I don't think it's currently possible, you would have to specify the local path in `model` but it won't ping the custom `cache_dir`.
> 
> We would happily welcome a PR that enables that for pipelines, would you be interested in that?

Thanks for your solution. I prefer to wait for new features in the future.
