### ISSUE TITLE
version of T5 is not reported in HuggingFace models 

### ISSUE THREAD

**Issue by dorooddorood606** [huggingface/transformers#11807]
Hi  @patrickvonplaten, @patil-suraj,
Google T5 model has two checkpoints, of t5.0.0 and t5.1.0, the performance of the two models is very different, in huggingface mdoels it is not specified which version HuggingFace is using, could you kindly add the details?
thanks

**Comment by patil-suraj** [comment]
Hi there,

for T5V1.1 models we explicitly mention it in the model name, for example see here 
https://huggingface.co/google/t5-v1_1-base

the model version is mentioned in the name as `v1_1`.
