### ISSUE TITLE
Permission error for cardiffnlp/twitter-roberta-base-emotion

### ISSUE THREAD

**Issue by StephenQuirolgico** [huggingface/transformers#11814]
@patrickvonplaten,

I'm having issues accessing  the `cardiffnlp/twitter-roberta-base-emotion` model using:
```
task='emotion'
MODEL = f"cardiffnlp/twitter-roberta-base-{task}"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
```
When I substitute another task, such as `task='sentiment'`, it works fine. I have also tried using the `cardiffnlp/twitter-roberta-base-emotion` model within an NLP framework (AdaptNLP) but got a `permission denied` error. However, I did not receive a `permission denied` error when using the `sentiment ` task within this NLP framework.

**Comment by patrickvonplaten** [comment]
Hey @StephenQuirolgico,

could you attach a code snippet that I can copy-paste to reproduce the error? :-)

**Comment by StephenQuirolgico** [comment]
@patrickvonplaten, Not exactly sure what the issue was but it's working now. Thanks!
