### ISSUE TITLE
possible bug in `TokenizerFast` when setting `return_offset_mapping=True`

### ISSUE THREAD

**Issue by YiweiJiang2015** [huggingface/transformers#11828]
## Environment info

- `transformers` version: 4.5.1, 4.6.1
- `tokenizers` version 0.10.2
- Platform: Linux/Ubuntu 18.04
- Python version: 3.9.1
- PyTorch version (GPU?): 1.7.1
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
- tokenizers: @n1t0, @LysandreJik 

## Information

I am building a model (using Bert) which needs the `offsets` between tokens and original words. However, if I set `return_offset_mapping=True` in `BertTokenizerFast`, the returned encodings are not accepted by the model. Is this a bug or is it intended behavior?

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

The following code snippet reproduces the problem for me:
```python
from transformers import BertTokenizerFast, BertModel

if __name__ == '__main__':
    test_string = 'text with percentage%'

    tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')
    encodings = tokenizer(test_string, return_offsets_mapping=True, return_tensors='pt')
    print(encodings.keys())
    model = BertModel.from_pretrained('bert-base-uncased')
    out = model(**encodings)
```
I got the following error trace showing that `BertModel.forward()` does not accept `offset_mapping` which is included in the dict of `encodings`:
```
dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'offset_mapping'])
Traceback (most recent call last):
  File "~/trans_test.py", line 9, in <module>
    out = model(**tokens)
  File "~/miniconda3/envs/tf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'offset_mapping'
```

## Expected behavior
At least, `Model.forward()` is supposed to have a key-arg placeholder for `offset_mapping`. For now, a workaround solution is to pop out `offset_mapping` from `encodings` before feeding the model. :(

**Comment by LysandreJik** [comment]
Indeed, the model does not accept the `offset_mapping`, and does not need them for anything; so when using the standard BERT model, make sure you don't feed this value to the model.

If you're making a custom BERT model that accepts offset mappings, then you should also update the signature to handle them!

**Comment by YiweiJiang2015** [comment]
Ok. Thanks for reminding!
