### ISSUE TITLE
[AutomaticSpeechRecognitionPipeline] CUDA support

### ISSUE THREAD

**Issue by francescorubbo** [huggingface/transformers#11829]
## Environment info

- `transformers` version: 4.6.0
- Platform: Linux-4.15.0-106-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.8.1+cu101 (True)
- Tensorflow version (GPU?): 2.3.1 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help
- pipelines: @LysandreJik

## Information

Model I am using (Bert, XLNet ...): Wav2Vec2

The problem arises when using:
* [ X ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)
* [ X ]  Automatic Speech Recognition 

## To reproduce

1. Instantiate AutomaticSpeechRecognitionPipeline with device set to GPU
2. Run pipeline inference on example  audio input

```
import transformers
model = transformers.Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-large-xlsr-53-spanish")
tokenizer = transformers.AutoTokenizer.from_pretrained("facebook/wav2vec2-large-xlsr-53-spanish")
feature_extractor = transformers.AutoFeatureExtractor.from_pretrained("facebook/wav2vec2-large-xlsr-53-spanish")
pl = transformers.AutomaticSpeechRecognitionPipeline(feature_extractor=feature_extractor, model=model, tokenizer=tokenizer, framework='pt',device=0)

pl('waveform.wav')
```

The snippet above results in the following error:

`RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same`

## Expected behavior

Inputs should be converted to CUDA tensor. 
I believe this is happening because the feature extractor doesn't preserve the device.
I'm able to solve the issue if I add 
`processed = self.ensure_tensor_on_device(**processed)`
after https://github.com/huggingface/transformers/blob/master/src/transformers/pipelines/automatic_speech_recognition.py#L136-L138

If this solution is acceptable, I'm happy to open a PR.

**Comment by LysandreJik** [comment]
Sure, feel free to open a PR! Thanks @francescorubbo
