### ISSUE TITLE
[docs] XLnet reference link bug in description of past_index Parameter of TrainingArguments 

### ISSUE THREAD

**Issue by Muktan** [huggingface/transformers#11831]
XLnet reference link bug in description of past_index Parameter of TrainingArguments 
link to the doc: https://huggingface.co/transformers/main_classes/trainer.html#transformers.TrainingArguments

**current description:** Some models like TransformerXL or **:doc`XLNet <../model_doc/xlnet>`** can make use of the past hidden states for their predictions. If this argument is set to a positive int, the Trainer will use the corresponding output (usually index 2) as the past state and feed it to the model at the next training step under the keyword argument mems.

**expected description:** Some models like TransformerXL or **XLNet** can make use of the past hidden states for their predictions. If this argument is set to a positive int, the Trainer will use the corresponding output (usually index 2) as the past state and feed it to the model at the next training step under the keyword argument mems.

## Environment info
Not required

### Who can help
@sgugger
<!-- Your issue will be replied to more quickly if you can figure out the right person to tag with @
 If you know how to use git blame, that is the easiest way, otherwise, here is a rough guide of **who to tag**.
 Please tag fewer than 3 people.

**Comment by sgugger** [comment]
Thanks for flagging! Should be fixed by the PR linked above!
