### ISSUE TITLE
Seq2seq-based model running slowly on TPU

### ISSUE THREAD

**Issue by heraclex12** [huggingface/transformers#11832]
## Environment info

- `transformers` version: v4.5.1 and newest version
- Platform: Colab
- Python version: 3.8
- PyTorch version (GPU?): 1.8.1
- TPU v2-8

### Who can help
@patil-suraj @patrickvonplaten

## Information

I tried to finetune mBART, T5, and MarianMTModel but all of them are running slowly on Colab TPUv2. I think the cause may come from Seq2seqTrainer since it works very well when I finetuned BERT on TPUv2 for MNLI Text classification.

The problem arises when using:
* The official example scripts: I use exactly the example parameter in README to train Translation model.
```
python xla_spawn.py --num_cores 8 \
    seq2seq/run_translation.py \
    --model_name_or_path Helsinki-NLP/opus-mt-en-ro \
    --do_train \
    --do_eval \
    --source_lang en \
    --target_lang ro \
    --dataset_name wmt16 \
    --dataset_config_name ro-en \
    --output_dir /tmp/tst-translation \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --overwrite_output_dir 
```

I provide my [Colab notebook](https://colab.research.google.com/drive/1Y8kSbuZJ8ChIjgAf67F1cSciVaHfGTyq?usp=sharing)

The tasks I am working on is:
* an official GLUE/SQUaD task: WMT16

## Expected behavior
Currently, with each step, the training duration increases many times. I want the duration is more stable and faster than GPU.

**Comment by patrickvonplaten** [comment]
I'm not sure if we ever tested whether those seq2seq models run correctly on TPU (@patil-suraj). It might be the case that a lot of the computations are dynamic and therefore are constantly re-compiled.

**Comment by heraclex12** [comment]
I realize that I haven't passed --pad_to_max_length to the script, which leads to our model running slowly. So I will close this issue. Thank you for your support and sorry about that.

**Comment by patil-suraj** [comment]
I have tested T5 and Marian on colab TPU and they work well

@heraclex12 you are right, on TPU we should always pass `--pad_to_max_length` to avoid XLA re-compilation, and ideally `max_length` should be multiple of 8.
