### ISSUE TITLE
Convert RoBERTa to TF checkpoint

### ISSUE THREAD

**Issue by YoPatapon** [huggingface/transformers#1184]
Can we use the "convert_pytorch_checkpoint_to_tf" script to convert the RoBERTa checkpoint to the Tensorflow ckpt? Thanks.

**Comment by LysandreJik** [comment]
Hello, I believe that unfortunately the script currently only works for the `BertModel` base class. You would have to create a similar script for RoBERTa, it shouldn't be too different as both models have very similar architectures!
