### ISSUE TITLE
Permission denied for cardiffnlp/twitter-roberta-base-emotion

### ISSUE THREAD

**Issue by StephenQuirolgico** [huggingface/transformers#11854]
@patrickvonplaten

When trying to access `cardiffnlp/twitter-roberta-base-emotion` using the example code, it can't seem to find the model. I also tried calling the model from an NLP framework (AdaptNLP) and it gave a Permission denied error. However, I don't get this error  when using `cardiffnlp/twitter-roberta-base-sentiment`. Any suggestions?

**Comment by LysandreJik** [comment]
The model seems accessible: https://huggingface.co/cardiffnlp/twitter-roberta-base-emotion 

And running the example code locally correctly loads the model, and outputs the following:

```py
1) joy 0.9382
2) optimism 0.0362
3) anger 0.0145
4) sadness 0.0112
```

Could you try again to make sure it wasn't a connection issue?

**Comment by StephenQuirolgico** [comment]
@LysandreJik, thanks - it's working now.
