### ISSUE TITLE
Errors in Quickstart  Documentation related to GPT-2

### ISSUE THREAD

**Issue by williamsdoug** [huggingface/transformers#11873]
To: @sgugger, @patrickvonplaten, @LysandreJik

## Environment info

- `transformers` version: 4.6.0
- Platform: Linux-5.4.0-73-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.8.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: True
- Using distributed or parallel set-up in script?: False

### Who can help
@sgugger, @patrickvonplaten, @LysandreJik

## Information

Model I am using (gpt-2 ...):

The problem arises when using:
* Example code in **Quickstart** page on online [documentation](https://huggingface.co/transformers/quickstart.html) section **OpenAI GPT-2** / **Using the past**

### Existing Code
```
for i in range(100):
    print(i)
    output, past = model(context, past=past)
    token = torch.argmax(output[..., -1, :])

    generated += [token.tolist()]
    context = token.unsqueeze(0)

sequence = tokenizer.decode(generated)

print(sequence)
```

### Errors Encountered in statement ```output, past = model(context, past=past)```

-  Obsolete named parameter **past**, replaced by **past_key_values** in current release
-  Assignment to ```output, past =``` does not assign expected values
   - model() statement returns value of type ```transformers.modeling_outputs.CausalLMOutputWithCrossAttentions``` 

### Suggested Corrected Version

```
for i in range(100):
    print(i)
    ret = model(context, past_key_values=past)
    output, past = ret.logits, ret.past_key_values
    # or
    # output, past = ret[0], ret[1]
    token = torch.argmax(output[..., -1, :])

    generated += [token.tolist()]
    context = token.unsqueeze(0)

sequence = tokenizer.decode(generated)

print(sequence)
```

**Comment by sgugger** [comment]
Oh, this page should not be there anymore, it's part of the old documentation. Out of curiosity, how did you get on it?

**Comment by williamsdoug** [comment]
Hi @sgugger -

I think I see the problem.  If the user navigates to huggingface.co first, then follows the links, it points to the updated documentation.  Also, the link associated with the Transformers github repo points to the current docs..

However, if the user navigates via a Google search and clicks on Quickstart, it redirects to  an obsolete version of the docs.  See screenshot attached.

![Screenshot from 2021-05-25 15-30-02](https://user-images.githubusercontent.com/2381871/119558029-ec184d80-bd6e-11eb-8308-699f3f4fa2e8.png)

**Comment by sgugger** [comment]
I have removed the page from the doc website. Hopefully Google will update its recommendation soon!

**Comment by julien-c** [comment]
Note that there probably are some SEO-related optimisations to our doc site layout to make sure Sitelinks are kept up-to-date (and the latest released version is the one best ranked by Google):

https://support.google.com/webmasters/answer/47334?hl=en

In terms of UX, one can also display a banner on top on the doc for every non-latest version. cc @gary149

**Comment by sgugger** [comment]
Note that here it was trying to render that file in the current version (the version selector said stable doc for instance), so it was really confusing.
