### ISSUE TITLE
[lm examples] replicate --config_overrides addition to other LM examples

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#11875]
This PR https://github.com/huggingface/transformers/pull/11798 created for `run_clm.py` which adds a new feature `--config_overrides` needs to be replayed for other scripts under `examples/pytorch/language-modeling/`.

If you choose to work on this small project, please comment that you're working on it.

And thank you!

**Comment by kumar-abhishek** [comment]
I am getting started with this task.

**Comment by stas00** [comment]
Thank you, @kumar-abhishek!
