### ISSUE TITLE
Trainer : AttributeError: 'str' object has no attribute '_memory_tracker'

### ISSUE THREAD

**Issue by KhalidAlt** [huggingface/transformers#11879]
## Environment info
- `transformers` version: 4.6.0
- Platform: Linux-5.8.0-53-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.8.0+cu111 (True)
- Tensorflow version (GPU?): 2.4.1 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help

Library:

- trainer: @sgugger 

## Information

Model I am using (Bert, XLNet ...):

T5ForConditionalGeneration

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Training a T5 from scratch over 20GB of data for one epoch and save the model checkpoints using Trainer library
2. Trying to (resume_from_checkpoint="./checkpoint-1320000")

The code :

```
model=T5ForConditionalGeneration.from_pretrained('./checkpoint-1320000/')

%%time
Trainer.train("./T5_model_result/checkpoint-1320000/")
```

The Error message : 

```
AttributeError                            Traceback (most recent call last)
<timed eval> in <module>

~/anaconda3/envs/py38/lib/python3.8/site-packages/transformers/trainer.py in train(self, resume_from_checkpoint, trial, **kwargs)
    998 
    999         # memory metrics - must set up as early as possible
-> 1000         self._memory_tracker.start()
   1001 
   1002         args = self.args

AttributeError: 'str' object has no attribute '_memory_tracker'
```

## Expected behavior

The Traianer library should resume from the last epoch to continue the learning.

**Comment by sgugger** [comment]
The `Trainer` will resume from the last epoch and continue the learning... if you create it. You are using the class directly, not a `Trainer` object.
