### ISSUE TITLE
Using do_eval from run_glue.py uses the cached result

### ISSUE THREAD

**Issue by wahlforss** [huggingface/transformers#1187]
## ❓ Questions & Help

Using do_eval from run_glue.py uses the cached result. I want to evaluate my fine-tuned models and I can't find any guide on how to do so. Anybody that can point me in the right direction?

**Comment by ruanchaves** [comment]
If you simply remove the cached file or move it elsewhere, it won't be used by run_glue.py. That's what I have been doing.
