### ISSUE TITLE
Want to use bert-base-uncased model without internet connection

### ISSUE THREAD

**Issue by soumochatterjee** [huggingface/transformers#11871]
I want to use the bert-base-uncased model in offline , for that I need the bert tokenizer and bert model have there packages saved in my local . **I am unable to understand how should I achieve it in my local without any internet connection** ?

import transformers
transformers.BertTokenizer.from_pretrained("bert-base-uncased", do_lower_case=True)
transformers.BertModel.from_pretrained("bert-base-uncased")

currently getting the error
![image](https://user-images.githubusercontent.com/42636586/119517715-7c698900-bd95-11eb-9ab6-6d647e095204.png)

What file should I add inplace for ("bert-base-uncased") so that it can work corectly in offline?
here is the link to my [notebook](https://www.kaggle.com/soumochatterjee/inference-commonlit-readability)

**Comment by julien-c** [comment]
This would be better suited on the Forum, but I would suggest doing (with git-lfs installed)

```bash
git clone https://huggingface.co/bert-base-uncased
```

and then
```python
import transformers
transformers.BertTokenizer.from_pretrained("./bert-base-uncased", do_lower_case=True)
transformers.BertModel.from_pretrained("./bert-base-uncased")
```

**Comment by eckarthik** [comment]
> 
> 
> This would be better suited on the Forum, but I would suggest doing (with git-lfs installed)
> 
> ```shell
> git clone https://huggingface.co/bert-base-uncased
> ```
> 
> and then
> 
> ```python
> import transformers
> transformers.BertTokenizer.from_pretrained("./bert-base-uncased", do_lower_case=True)
> transformers.BertModel.from_pretrained("./bert-base-uncased")
> ```

@julien-c 
Clone is failing with below errors

```
C:\Users\Karthik\Desktop>git clone https://huggingface.co/bert-base-uncased
Cloning into 'bert-base-uncased'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 52 (delta 19), reused 0 (delta 0)
Unpacking objects: 100% (52/52), 304.24 KiB | 61.00 KiB/s, done.
Updating files: 100% (10/10), done.
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Exiting because of "interrupt" signal.
```

**Comment by soumochatterjee** [comment]
@julien-c I also got the same error.

**Comment by julien-c** [comment]
Can you add `GIT_CURL_VERBOSE=1 GIT_TRACE=1` to your command to get more info?

**Comment by julien-c** [comment]
And also paste your `git --version` and `git lfs --version`

**Comment by soumochatterjee** [comment]
I was able to resolve this problem with the help of code :

```
BERT_MODEL_PATH = 'PATH FOR THE DATASET YOU SAVED IN YOUR LOCAL THROUGH THE [LINK](https://www.kaggle.com/abhishek/bert-base-uncased)'

TOKENIZER = transformers.BertTokenizer.from_pretrained(BERT_MODEL_PATH, do_lower_case=True, local_files_only=True)
model = BertModel.from_pretrained("BERT_MODEL_PATH")
```

**Comment by soumochatterjee** [comment]
Posted my solution to my asked question here in the issue
