### ISSUE TITLE
Find the requested files in the cached path without the internet

### ISSUE THREAD

**Issue by Bachstelze** [huggingface/transformers#11885]
# 🚀 Feature request
The pipeline needs an internet connection to find the cached path. A request usually consumes time. 

## Motivation
Could we search only localy for a better performance?

## Your contribution
 My test code:
```
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-de-en")
model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-de-en")

de_en_translator = pipeline("translation_de_to_en", model=model, tokenizer=tokenizer)
translation = de_en_translator("Ein kleiner Test.")
```

**Comment by LysandreJik** [comment]
You can save your model and tokenizer to a directory using `save_pretrained` and load them from there! You only need to specify the directory path to the model/tokenizer arguments you pass to the `pipeline` method.
