### ISSUE TITLE
Mask token mismatch with the model on hosted inference API of Model Hub

### ISSUE THREAD

**Issue by Ethan-yt** [huggingface/transformers#11884]
### Who can help

@LysandreJik 
@julien-c 
@mfuntowicz 

## Information

In my model card: https://huggingface.co/ethanyt/guwenbert-base, I used to be able to run the hosted inference successfully, but recently it prompted an error: `"<mask>" must be present in your input.`

My model uses RoBERTa MLM and BERT Tokenizer. So the mask token is actually "[MASK]". I have already set it in `tokenizer_confg.json` but the inference API still mismatches with that.

In the past it is OK but recently it turns to prompt an error. Seems like the front-end start to double-check the mask token. How can I set the mask token in an appropriate way? Is it documented to set mask token in inference API?

Thanks!

## To reproduce

1. Go to https://huggingface.co/ethanyt/guwenbert-base
2. Run an example with "[MASK]"

## Expected behavior
In the past it was OK. See snapshot in  https://github.com/ethan-yt/guwenbert/blob/main/README_EN.md

**Comment by Ethan-yt** [comment]
In the past, it was no error.
<img width="510" alt="lm-demo" src="https://user-images.githubusercontent.com/9592150/120172538-bd4e1b80-c235-11eb-8576-6446a2dd0ed8.png">
I don't know when it starts to emit an error.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/9592150/120172600-ce972800-c235-11eb-91b0-a231cfaf4f5f.png">

**Comment by julien-c** [comment]
I've fixed it by explicitly specifying the `mask_token` in your model card metadata: https://huggingface.co/ethanyt/guwenbert-base/commit/30aaff24928389096312600511a9ca2fad1b3974

**Comment by julien-c** [comment]
thanks for reporting!

**Comment by Ethan-yt** [comment]
> thanks for reporting!

Thanks!
