### ISSUE TITLE
 Provides an option to select the parallel mode of the Trainer.

### ISSUE THREAD

**Issue by hijkzzz** [huggingface/transformers#11899]
# 🚀 Feature request

Provides an option to select the parallel mode of the Trainer.

## Motivation

For multiple GPUs, Trainer uses `nn.DataParallel` for parallel computing by default, however, this approach results in a large memory occupation for the first GPU. Please provide an API to switch to `nn.parallel.DistributedDataParallel`. Also, for the `Trainer.predict()` function is there an option to turn off parallel computing?

## Your contribution

@sgugger

**Comment by sgugger** [comment]
This is already implemented, it just depends on how you launch your training script. To use distributed data parallel, you have to launch it with `torch.distributed.launch`.

**Comment by hijkzzz** [comment]
> This is already implemented, it just depends on how you launch your training script. To use distributed data parallel, you have to launch it with `torch.distributed.launch`.

Hi~
How to do for jupyter?
Also what if I use DataParallel for train and only want to use one GPU for predict?

**Comment by sgugger** [comment]
You can't do this directly in jupyter, you have to launch a script using the pytorch utilities (it's not a Trainer limitation, it's a PyTorch one). You can completely predict in parallel with the `Trainer`, it will complete the last batch to make it the same size as the others and then truncate the predictions.

**Comment by hijkzzz** [comment]
> You can't do this directly in jupyter, you have to launch a script using the pytorch utilities (it's not a Trainer limitation, it's a PyTorch one). You can completely predict in parallel with the `Trainer`, it will complete the last batch to make it the same size as the others and then truncate the predictions.

But we can't truncate predictions because it's a contest or a client's demand and we need all the test results we can get.

As a demo, #11833
https://github.com/huggingface/transformers/issues/11833
