### ISSUE TITLE
mutil gpu errors

### ISSUE THREAD

**Issue by Soulscb** [huggingface/transformers#11898]
i want to use multi gpus to train,but it erros;

model = nn.DataParallel(model)
model = model.cuda()
model.train_model(train_df, eval_data=eval_df)
torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'train_model'

so how can i to use multi gpus

**Comment by LysandreJik** [comment]
Is this related to `transformers`?

**Comment by Soulscb** [comment]
yes    this is simpletransformers and i find transformers multi gpus is hard to  run
