### ISSUE TITLE
Inference for pinned model keeps loading

### ISSUE THREAD

**Issue by Kvit** [huggingface/transformers#11913]
I have pinned the enterprise model: `ligolab/DxRoberta`
This model is pinned for instant start. 
When I try the Inference API `fill-mask` task, it responds instantly 
However, when I try API call to embedding pipeline https://api-inference.huggingface.co/pipeline/feature-extraction/ligolab/DxRoberta , I keep getting the message: `{'error': 'Model ligolab/DxRoberta is currently loading', 'estimated_time': 20}` and status does not change with time. 
API call to embedding pipeline was working yesterday when I tested it.

**Comment by Kvit** [comment]
after I have unpinned the model embeddings pipeline started working again (unless you did something on the back end)

**Comment by Kvit** [comment]
I have repeated the experiment:  pinned model - embedding pipeline API returns "loading" status; unpinned model - embedding pipeline returns valid results (after model 'warm up'). Look like inference API to embedding pipeline stops working if the model is pinned for instant inference access.

**Comment by julien-c** [comment]
Tagging @Narsil for visibility (API support issues are best handled over email if possible!)

**Comment by Narsil** [comment]
Thanks for tagging me, the `ligolab/DxRoberta` is defined a `fill-mask` by default, so that was what was being pinned down leading the issues you were encountering. You can override that by changing the `pipeline_tag` in the model card (if you want).

There is currently no way to specify the `task` when pinning, so I did it manually for now ! You should be good to go !

**Comment by Kvit** [comment]
If we change `pipeline_tag `do we still need to use API endpoint `/pipeline/feature-extraction/ ` ?

**Comment by Narsil** [comment]
No if you change the default tag, then the regular route /models/{MODEL} will work !
