### ISSUE TITLE
how to use 'spiece.model' to create the xlnet_tokenizer

### ISSUE THREAD

**Issue by yangzh9106** [huggingface/transformers#1191]
## ❓ Questions & Help
For some reason, my computer can not connect to Internet, which means I can not use the code "tokenizer = tokenizer_class.from_pretrained('xlnet-base-cased', do_lower_case = True)" to create the tokenizer.
The Piece model (spiece.model)  is used for (de)tokenization, how can I use it to create the tokenizer?
I have tried :
`
from pytorch_transformers import XLNetTokenizer
config = {
'vocab_path' :  path.sep.join([BASIC_DIR,'pretrained/pytorch_xlnet_pretrained/spiece.model'])      
        }
tokenizer = XLNetTokenizer.from_pretrained(config['vocab_path'], do_lower_case = True)
`
it doesn't work.

**Comment by thomwolf** [comment]
First, note that you can give proxies to the prom_pretrained method if your connection problem comes from a proxy (see the doc/docstring for an example).

You can download the sentence piece model from our (see the top of the `tokenization_xlnet.py` file for the url) and put it in a folder with the name `spiece.model`, then just give this folder path to the `from_pretrained` method.
