### ISSUE TITLE
LayoutLMv2 Model

### ISSUE THREAD

**Issue by monuminu** [huggingface/transformers#11932]
# 🌟 New model addition

## Model description

LayoutLMv2 by pre-training text, layout and image in a multi-modal framework, where new model architectures and pre-training tasks are leveraged. Specifically, LayoutLMv2 not only uses the existing masked visual-language modeling task but also the new text-image alignment and text-image matching tasks in the pre-training stage, where cross-modality interaction is better learned.

## Open source status

* [ ] the model implementation is available: (give details) https://github.com/microsoft/unilm/tree/master/layoutlmv2
* [ ] the model weights are available: (give details) https://huggingface.co/microsoft/layoutlmv2-base-uncased/
* [ ] who are the authors: (mention them, if possible by @gh-username) 
@inproceedings{Xu2020LayoutLMv2MP,
  title     = {LayoutLMv2: Multi-modal Pre-training for Visually-Rich Document Understanding},
  author    = {Yang Xu and Yiheng Xu and Tengchao Lv and Lei Cui and Furu Wei and Guoxin Wang and Yijuan Lu and Dinei Florencio and Cha Zhang and Wanxiang Che and Min Zhang and Lidong Zhou},
  booktitle = {Proceedings of the 59th Annual Meeting of the Association for Computational Linguistics (ACL) 2021},
  year      = {2021},
  month     = {August},
}

**Comment by lirus7** [comment]
What's the current status of this?
I see Microsoft has already pushed the code as mentioned above for this but i can't import from huggingface.

**Comment by monuminu** [comment]
I have completed the work but there is a problem with installing detectron2 using pip . Anyone can help on this ?

**Comment by lirus7** [comment]
Can you tell me the issue with installing detectron2? I can prolly help

**Comment by monuminu** [comment]
Its saying pip install detectron2 is giving issue .

**Comment by raguiar2** [comment]
You have to install detectron from git+https://github.com/facebookresearch/detectron2.git. 

See https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md for instructions 

`python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'`
