### ISSUE TITLE
[docs] XLNETModel forward returns last_hidden_state 3rd dim should be d_model instead of hidden_size 

### ISSUE THREAD

**Issue by Muktan** [huggingface/transformers#11938]
**Link to doc** - https://huggingface.co/transformers/model_doc/xlnet.html#xlnetmodel

**Problem description** - forward method of XLNETModel returns `last_hidden_state` with dimension `(batch_size, num_predict, hidden_size)`. However, `hidden_size` is not an XLNET config (unlike for BERT) instead that dimension should be `d_model` which is a config of XLNETModel.

**current shape** - (batch_size, num_predict, hidden_size)
**expected shape** - (batch_size, num_predict, d_model)

## Environment info
Not required

### Who can help
@sgugger
<!-- Your issue will be replied to more quickly if you can figure out the right person to tag with @
 If you know how to use git blame, that is the easiest way, otherwise, here is a rough guide of **who to tag**.
 Please tag fewer than 3 people.

**Comment by NielsRogge** [comment]
Hi,

Actually, `hidden_size` is an alias for `d_model`, as can be seen [here](https://github.com/huggingface/transformers/blob/7e73601f3240b99d952c34b63bf4f8b78ca1462d/src/transformers/models/xlnet/configuration_xlnet.py#L233).

They mean the same thing. But I get your confusion, as some models use `hidden_size`, others `d_model`, or other names.

Feel free to open a PR to fix this in the docs of XLNet.
