### ISSUE TITLE
Loading mbart-large-50-one-to-many-mmt is very slow

### ISSUE THREAD

**Issue by MK096** [huggingface/transformers#11946]
Whenever i try to run :
model = MBartForConditionalGeneration.from_pretrained(" [local path]/mbart-large-50-one-to-many-mmt")
My computer ether freezes or it takes 15-20 minutes to load the model.

I am using it for translation 
Code: https://huggingface.co/facebook/mbart-large-50-one-to-many-mmt

Any solution fo this?

-Thanks

**Comment by patil-suraj** [comment]
Hi there, `mbart-50` is actlly a big model and takes a while to load. But 15-20 min seems a lot, it's could probably an issue with your system. You could try to load it using a colab and see how much time it takes.
