### ISSUE TITLE
report_to flag does not work with TFTrainer

### ISSUE THREAD

**Issue by tomy0000000** [huggingface/transformers#11949]
## Environment info

- `transformers` version: 4.6.1
- Platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.27
- Python version: 3.8.10
- PyTorch version (GPU?): 1.7.1+cu101 (True)
- Tensorflow version (GPU?): 2.5.0 (False)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Yes

### Who can help

@sgugger @LysandreJik @Rocketknight1 

## Information

The problem arises when using my own modified scripts: [CoLA from BLUE on TF version BERT](https://gist.github.com/tomy0000000/af06394aa00a8b0fffb992e5bf444adf)

My modified script only run the CoLA task, which is minimized from the official [tf_glue.py](https://github.com/huggingface/transformers/blob/master/examples/tensorflow/text-classification/run_tf_glue.py)

I've setup comet.ml and wandb for other project, but don't want to use them in this one.
However `report_to` flag don't seems to work in `TFTrainingArguments`.
More specific in the [trainer_tf.py](https://github.com/huggingface/transformers/blob/master/src/transformers/trainer_tf.py#L113-L127)

## To reproduce

Just run the notebook in jupyter, error pops in the 8th cell when `TFTrainer` is initialized.

Stacktrace:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-308135373fed> in <module>
----> 1 trainer = TFTrainer(
      2     model=model,
      3     args=TFTrainingArguments(output_dir=".", report_to="tensorboard"),
      4     train_dataset=train_dataset,
      5     eval_dataset=eval_dataset,

~/.local/lib/python3.8/site-packages/transformers/trainer_tf.py in __init__(self, model, args, train_dataset, eval_dataset, compute_metrics, tb_writer, optimizers)
    120 
    121         if is_comet_available():
--> 122             self.setup_comet()
    123         elif os.environ.get("COMET_MODE") != "DISABLED":
    124             logger.info(

~/.local/lib/python3.8/site-packages/transformers/trainer_tf.py in setup_comet(self)
    274         experiment = None
    275         if comet_mode == "ONLINE":
--> 276             experiment = comet_ml.Experiment(**args)
    277             logger.info("Automatic Comet.ml online logging enabled")
    278         elif comet_mode == "OFFLINE":

~/.local/lib/python3.8/site-packages/comet_ml/__init__.py in __init__(self, api_key, project_name, workspace, log_code, log_graph, auto_param_logging, auto_metric_logging, parse_args, auto_output_logging, log_env_details, log_git_metadata, log_git_patch, disabled, log_env_gpu, log_env_host, display_summary, log_env_cpu, display_summary_level, optimizer_data, auto_weight_logging, auto_log_co2, auto_metric_step_rate, auto_histogram_tensorboard_logging, auto_histogram_epoch_rate, auto_histogram_weight_logging, auto_histogram_gradient_logging, auto_histogram_activation_logging)
    239             )
    240 
--> 241         super(Experiment, self).__init__(
    242             project_name=project_name,
    243             workspace=workspace,

~/.local/lib/python3.8/site-packages/comet_ml/experiment.py in __init__(self, project_name, workspace, log_code, log_graph, auto_param_logging, auto_metric_logging, parse_args, auto_output_logging, log_env_details, log_git_metadata, log_git_patch, disabled, log_env_gpu, log_env_host, display_summary, log_env_cpu, display_summary_level, optimizer_data, auto_weight_logging, auto_log_co2, auto_metric_step_rate, auto_histogram_tensorboard_logging, auto_histogram_epoch_rate, auto_histogram_weight_logging, auto_histogram_gradient_logging, auto_histogram_activation_logging)
    458                     ALREADY_IMPORTED_MODULES
    459                 )
--> 460                 raise ImportError(msg)
    461 
    462         # Generate a unique identifier for this experiment.

ImportError: You must import Comet before these modules: tensorflow, torch, tensorboard
```

## Expected behavior

`TFTrainer` should respect the `report_to` arguments provided

**Comment by sgugger** [comment]
No this is not implemented for the `TFTrainer`. More generally, we are moving away from `TFTrainer` to go to pure Keras for the training loop.

**Comment by tomy0000000** [comment]
Well, does that means `trainer_tf.py` is getting a huge rewrite? If not, I'm willing to work on a PR solving this particular issue. Let me know if anyone have thoughts about how this should be implemented.

**Comment by sgugger** [comment]
No it's just going to disappear and we will use the Keras methods (fit etc.) instead.
