### ISSUE TITLE
How to finetune DistilBERT on custom data?

### ISSUE THREAD

**Issue by 008karan** [huggingface/transformers#1194]
## ❓ Questions & Help

I want to build classifier by using DistillBERT. I would like to know how to finetune it on the custom dataset and build classifier on it.
Thansk!

**Comment by VictorSanh** [comment]
Hello @008karan,
There is the class `DistilBertForSequenceClassification` for classification tasks. Its used is really similar to `BertForSequenceClassification`: the main difference is that `DistilBertForSequenceClassification` does not need `token_type_ids` as inputs.
