### ISSUE TITLE
Killed Message

### ISSUE THREAD

**Issue by adnan-fakahr-pk-90** [huggingface/transformers#11955]
Describe the bug
When I run this command
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-2.7B')
or even download the model in a folder like this
generator = pipeline('text-generation', model=neo-models/')

It is not loading and produce the result as "Killed" text.
which usually means "out of memory"

even though I have nothing loaded except pycharm GUI

I have tested this on Ubuntu and Centos Server. Same result

below is the whole code:

import gc
import os
from transformers import pipeline
import torch

gc.collect()
print("================1")
**generator = pipeline('text-generation', model='EleutherAI/gpt-neo-2.7B') ====> here comes the KILLED**
#generator = pipeline('text-generation', model='neo-models/'')
print("================2")
prompt = "what is the meaning of life"
res = generator(prompt, max_length=50, do_sample=True, Temperature=0.9)
print("================")
print(res)

**Comment by LysandreJik** [comment]
The `EleutherAI/gpt-neo-2.7B` is a large model. Loading it in memory takes  more than 10GB. 
Do you have the same results when trying to use the 1.3B or the 125M variants?

**Comment by adnan-fakahr-pk-90** [comment]
> The `EleutherAI/gpt-neo-2.7B` is a large model. Loading it in memory takes more than 10GB.
> Do you have the same results when trying to use the 1.3B or the 125M variants?

yes I did with 2.7 and then 1.3 both have the same result....
Then how we use it, if a person has 8GB or 16GB memory installed in a PC...
