### ISSUE TITLE
Add new token to pretrained GPT2 tokenizer

### ISSUE THREAD

**Issue by sooftware** [huggingface/transformers#11959]
Hi! Thank you for awesome project!    
I want to add several tokens to pre-trained GPT2 tokenizer.   
Can I?

**Comment by sooftware** [comment]
I will use "EleutherAI/gpt-neo-1.3B" tokenizer. Is there a

**Comment by LysandreJik** [comment]
This should help you out: https://huggingface.co/transformers/internal/tokenization_utils.html?highlight=add_tokens#transformers.tokenization_utils_base.SpecialTokensMixin.add_tokens

**Comment by hyunwoongko** [comment]
요거 제가 잘 알아요. 내일 도와드릴게용

**Comment by sooftware** [comment]
Thank you! @LysandreJik
