### ISSUE TITLE
run_qa.py for Question and answering doesn't work for SQUAD2 

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [huggingface/transformers#11969]
Hi I am using custom data set for fine tune QnA. When I am trying to train the run_qa.py for my dataset. preprocessing is not working. My dataset is look like this.

```
!python /home/jupyter/Project/transformers/examples/pytorch/question-answering/run_qa.py \
  --model_name_or_path deepset/bert-large-uncased-whole-word-masking-squad2  \
  --train_file /home/jupyter/Project/QnAwatersoftner/squad/train-v2.0.json  \
  --do_train \
  --per_device_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir ./Exp_model/ \
  --version_2_with_negative
```

![squd2](https://user-images.githubusercontent.com/46083296/120276871-e079d900-c2d0-11eb-8b5f-5cf9638074ec.PNG)
![squad2](https://user-images.githubusercontent.com/46083296/120276875-e2439c80-c2d0-11eb-8c8d-0a2d12474b52.PNG)

Can you please help me with this. Thanks

@sgugger

**Comment by sgugger** [comment]
Yes, the script is an example for squad, not an app that works on any data. You will need to adapt the preprocessing steps to your dataset or change your dataset to be formatted exactly like squad.
