### ISSUE TITLE
Summarization also supports MT5ForConditionalGeneration

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#11960]
The [README.md](https://github.com/huggingface/transformers/blob/master/examples/pytorch/summarization/README.md) of the summarization examples sais it supports `T5ForConditionalGeneration` IMO `MT5ForConditionalGeneration` should be added - right?

Tagging @sgugger and @sshleifer ...

**Comment by PhilipMay** [comment]
And @patil-suraj

**Comment by patil-suraj** [comment]
Yes, you are right!

We could also add it  in the[ translation readme](https://github.com/huggingface/transformers/blob/master/examples/pytorch/translation/README.md) as well.

**Comment by PhilipMay** [comment]
> Feel free to open a PR :)

see #11961

**Comment by LysandreJik** [comment]
Fixed by #11961
