### ISSUE TITLE
It seems not able to add the args "repetition_penalty" when running the code run_summarization.py for prediction.

### ISSUE THREAD

**Issue by moooooser999** [huggingface/transformers#11975]
I am using the summarization code provided in example/pytorch/summarization/run_summarization.py

However, I could not add the argument "repetition_penalty" when generating.

After tracing the source code of Seq2SeqTrainer(), I found that the function `predict()` does not take the argument as input.

It might be helpful if the arguments the function takes could be much more flexible. For now, it only takes `max_len` and `num_beams` for the function `generate()`

**Comment by patil-suraj** [comment]
Yes, that's right. The `run_summarization` script does not accept all `generate` arguments. Instead, those arguments should be set in the `config`.  For your use-case, it should easy to modify the script to accept these args and then pass those to `config` so `generate` can directly access those.
