### ISSUE TITLE
No package metadata found for tqdm while generating exe

### ISSUE THREAD

**Issue by MK096** [huggingface/transformers#11978]
Hi,
Whenever i try to make executable file i always get an error : No package metadata found for tqdm.
I've tried hidden-import tqdm but it didn't work. In python IDLE it works fine but while running exe it doesn't work.

I am using Win 10 (64-bit)

Code:

              _import eel
              import tqdm # i thought of importing it to see wheter this solves anything..but it didn't help
              from transformers import pipeline
              
              print("Loaded")
              eel.init('Web')
              
              // try...Catch to open index.html_ [UI]
![error](https://user-images.githubusercontent.com/20142735/120370044-8c511200-c32d-11eb-9bd1-b2d63dfb1600.PNG)

Any help will be really appreciated.

Thank You

**Comment by mostafaedress** [comment]
Hello, 
Can you please tell me how you managed to solve this issue ?
