### ISSUE TITLE
Saving and loading a model does not work

### ISSUE THREAD

**Issue by bipinkc19** [huggingface/transformers#11970]
![image](https://user-images.githubusercontent.com/41479925/120278069-8e3ab700-c2d4-11eb-935e-a3a733a24cfd.png)
After pulling a model, tuning it and saving it, it shows this error while loading it back.

I pulled other files except `pytorch_model.bin` from the pretrained model in hugging face
![image](https://user-images.githubusercontent.com/41479925/120278270-cb06ae00-c2d4-11eb-9a40-3e1de6fc123c.png)

**Comment by LysandreJik** [comment]
Your file is called `pytoch_model.bin` instead of `pytorch_model.bin`.

You should use `save_pretrained` :)

**Comment by bipinkc19** [comment]
Sometime I wonder how more stupid I can be.
Thanks for the help
