### ISSUE TITLE
    EOFError("No valid references for a sentence!") for run_translation example

### ISSUE THREAD

**Issue by puraminy** [huggingface/transformers#11989]
I tried to apply `run_translation` on a dataset I created. I tried to get sure there is no blank target. 

example of test file:
`
{"data": [{"translation": {"en": "You're quite impatient with the rest of humanity, in fact.", "fa": "ﺩﺭ ﻭﺎﻘﻋ ﺩﺭ ﻢﻗﺎﺒﻟ ﺱﺎﯾﺭ ﺎﻨﺳﺎﻧ<200c>ﻫﺍ ﮎﺎﻣﻻ ﺐﯾ<200c>ﺣﻮﺼﻠﻫ ﻪﺴﺘﯾﺩ."}}, {"translation": {"en": "Now despite this history of distrust, I still believe that indigenous people can benefit from genetic research.", "fa": "ﺡﺍﻻ ﺏﺍ ﻮﺟﻭﺩ ﺎﯿﻧ ﺐﯾ ﺎﻌﺘﻣﺍﺪﯾ ﺕﺍﺮﯿﺨﯾ ﻢﻧ ﻪﻧﻭﺯ ﻢﻌﺘﻗﺪﻣ ﻡﺭﺪﻣﺎﻧ ﺏﻮﻤﯾ ﻢﯾ ﺕﻭﺎﻨﻧﺩ ﺍﺯ ﺖﺤﻘﯿﻗﺎﺗ ﮋﻨﺘﯿﮐ ﺱﻭﺩ ﺐﺑﺮﻧﺩ."}},
`
However I get this error:

```
File "run_translation.py", line 496, in compute_metrics
    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/datasets/metric.py", line 40$
, in compute
    output = self._compute(predictions=predictions, references=references, **kwargs)
  File "/home/pouramini/.cache/huggingface/modules/datasets_modules/metrics/sacrebleu/4dba4$
29caa3766d885f0b9cde070fedb22ac3190c264a6454b8ea6703ddd466/sacrebleu.py", line 128, in _com$
ute
    use_effective_order=use_effective_order,
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/sacrebleu/compat.py", line 3$
, in corpus_bleu
    sys_stream, ref_streams, use_effective_order=use_effective_order)
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/sacrebleu/metrics/bleu.py", $
ine 286, in corpus_score
    raise EOFError("No valid references for a sentence!")
EOFError: No valid references for a sentence!

```

@patil-suraj @patrickvonplaten @lhoestq

**Comment by patil-suraj** [comment]
Hi @puraminy 

Could you debug the `compute_metrics` function? Maybe print/log a few `decoded_labels` that are used as references. Bit hard to guess without running the script.

**Comment by puraminy** [comment]
@patil-suraj  

I actually did, and the problem is that the predictions are in English than Persian (the target language)! I consider it a serious bug and I posted more details in:

https://github.com/huggingface/transformers/issues/12010
