### ISSUE TITLE
where is the code for  DetrFeatureExtractor, DetrForObjectDetection

### ISSUE THREAD

**Issue by zhangbo2008** [huggingface/transformers#12005]
Hello my dear friend. 
i am long for the model of https://huggingface.co/facebook/detr-resnet-50
i cannot find the code of it in transformers==4.7.0.dev0  and  4.6.1  pleae help me . appreciated.

## Environment info

- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by NielsRogge** [comment]
Haha it's not merged yet, thanks for your interest :) will be available soon

**Comment by zhangbo2008** [comment]
thanks dude

**Comment by nateraw** [comment]
Resolved by #11653 . Code can be found [here](https://github.com/huggingface/transformers/blob/master/src/transformers/models/detr/modeling_detr.py).
