### ISSUE TITLE
Distributed device ordinal question

### ISSUE THREAD

**Issue by Zhaofeng-Wu** [huggingface/transformers#1200]
## ❓ Questions & Help

In the following line, we set the device ordinal to be local rank. However, suppose we have four independent nodes each with only one GPU. Then the 4th node (rank 3) will execute this line with the device ordinal 3, but it really only has 1 GPU, so it'll be invalid to ask for the GPU 3. So won't that break things? Shouldn't it be `torch.device("cuda", 0)`?

https://github.com/huggingface/pytorch-transformers/blob/0287d264e913e10018a95a2723115dc9121e5fc6/examples/run_glue.py#L403

**Comment by thomwolf** [comment]
No, `local_rank` is only the local rank on each node.

**Comment by Zhaofeng-Wu** [comment]
Ah I see, thanks! A tangential question, considering the distributed setting only, would it be the same if we simply call `.cuda()` instead of passing around the device?
