### ISSUE TITLE
Translation example generates the same input

### ISSUE THREAD

**Issue by puraminy** [huggingface/transformers#12010]
I trained the [translation](https://github.com/huggingface/transformers/tree/master/examples/pytorch/translation ) example, using a custom json file with the format specefied in README. 

It has a bug, I don't know where, but strangely it just generated the same input. For example if you set `--do_predict`, the `generated_predictions.txt` is some of (or in language or format) of inputs.

**Comment by patrickvonplaten** [comment]
Hey @puraminy,

Could you provide a reproducible code snippet? Otherwise, it's very difficult to reproduce the error you got.

**Comment by puraminy** [comment]
@patrickvonplaten 

Here is my code on github

https://github.com/puraminy/mt5-comet

you should be able to `run_trans` in root folder. You can see my settings there.
The data were provided there. For test I decreased the number of train and test data in input parameters. I didn't check it recently, but I guess it's the last one with the error I specified above. 
There is another seq2seq task, which follows run_translation, named run_comet. That task is from English 2 English. It also generates the input than target. 
However, for now you can first try `run_trans` and for example check the generated texts by `do_predict`
