### ISSUE TITLE
Remove "Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation."

### ISSUE THREAD

**Issue by yananchen1989** [huggingface/transformers#12020]
When using GPT2 for generation, there is always info:

> Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation

I find this message hides in https://github.com/huggingface/transformers/blob/master/src/transformers/generation_utils.py
It seems redundancy. Can it be removed for simplicity ?

@patrickvonplaten @patil-suraj

**Comment by dataframing** [comment]
+1, it seems like this method gets triggered on each call to open-ended generation, which pollutes logs quite a bit :/ Is there a way to have it run just once on `pipeline` creation?

**Comment by patrickvonplaten** [comment]
You can manually set the pad_token_id to prevent this error message before running the pipeline, e.g.

```python
gen_pipe = pipeline("generation")
gen_pipe.model.config.pad_token_id = gen_pipe.model.config.eos_token_id
```

**Comment by lucasjinreal** [comment]
@patrickvonplaten Hello, I have set

model.config.pad_token_id = tokenizer.eos_token_id

but still got this warning, is it an error? How to disable it totally、

**Comment by seg-aiaec** [comment]
This error still persists and with other models too. This doesn't work

> You can manually set the pad_token_id to prevent this error message before running the pipeline, e.g.
> 
> ```python
> gen_pipe = pipeline("text-generation")
> gen_pipe.model.config.pad_token_id = gen_pipe.model.config.eos_token_id
> ```

**Comment by ArthurZucker** [comment]
Which version of `transformers` are you using? COuld you pass a reproducer? Both of you are not passing a full reproducer.

**Comment by DollarAkshay** [comment]
Looks like both the model and the tokenizer pad token have to be set to eradicate this error.
```
pipeline.model.config.pad_token_id = pipeline.model.config.eos_token_id
pipeline.tokenizer.pad_token = pipeline.tokenizer.eos_token
```

**Comment by sumanthprabhu** [comment]
If you are ok with disabling all info messages, setting the verbosity level to error would also work
```py
import transformers
transformers.logging.set_verbosity_error()
```

**Comment by shermansiu** [comment]
FYI: For newer versions of `transformers`, you need to set `model.generation_config.pad_token_id` instead of the one from `model.config` to suppress the warning message
