### ISSUE TITLE
pipelines should allow passing in tokenizer arguments

### ISSUE THREAD

**Issue by EtienneT** [huggingface/transformers#12039]
# 🚀 Feature request

It should be possible to pass in additional arguments for the tokenizer in the pipeline constructor.

Something like this:

```
from transformers import pipeline
classifier = pipeline('sentiment-analysis', padding=True, truncation=True, max_length=512, device=0)
```

## Motivation

For example for a sentiment-analysis pipeline, if the model has a maximum number of tokens and you pass-in larger text than that to the pipeline it will make the pipeline crash.  It would be really nice to be able to provide additional arguments for the tokenizer like padding=True, truncation=True, max_length=512 for example.  The only workaround I found was to create the tokenizer and model separately and provide the arguments to the tokenizer directly.

Here is how I do it right now:

```
pt_batch = tokenizer(texts, padding=True, truncation=True, max_length=512, return_tensors="pt")
    for x in pt_batch.keys():
        pt_batch[x] = pt_batch[x].to('cuda')
    pt_outputs = model(**pt_batch)
```

and how I would prefer to be able to do it instead:

```
from transformers import pipeline
classifier = pipeline('sentiment-analysis', padding=True, truncation=True, max_length=512, device=0)
preds = classifier(texts)
```

**Comment by mariosasko** [comment]
Hi,

you can pass a 2-tuple `(tokenizer_name, tokenizer_kwargs)` to achieve this. E.g.:
```python
from transformers import pipeline
classifier = pipeline('sentiment-analysis', tokenizer=(tokenizer_name, {"padding": True, "truncation": True, "max_length": 512}), device=0)
```
@patrickvonplaten Any particular reason why this is not documented?

**Comment by EtienneT** [comment]
@mariosasko thanks for your response! I tried this, but unfortunately I get the same error.
```
from transformers import pipeline
model_name = 'distilbert-base-uncased-finetuned-sst-2-english'
classifier = pipeline('sentiment-analysis', model=model_name, tokenizer=(model_name, {"padding": True, "truncation": True, "max_length": 512}), device=0)
```

The error:

> Token indices sequence length is longer than the specified maximum sequence length for this model (1055 > 512). Running this sequence through the model will result in indexing errors

Thanks,

**Comment by mariosasko** [comment]
My bad. Just checked the source. This should work:
```python
from transformers import pipeline
classifier = pipeline('sentiment-analysis', device=0)
classifier(texts, padding=True, truncation=True, max_length=512)
```

**Comment by EtienneT** [comment]
This works!  I was sure I had tried that, but it seems not.

Thank you!
