### ISSUE TITLE
Settings for perfect Story writing based on the input text?

### ISSUE THREAD

**Issue by krigeta** [huggingface/transformers#12055]
Hello, thank you so much for this awesome project.

What settings do you suggest so by using those settings it seems like a story is continuing based on the previous story input as a text file?

**Comment by LysandreJik** [comment]
Hello, sorry for the long answer time! Unfortunately, we favor using the [forum](https://discuss.huggingface.co) for questions like this where you're much more likely to get an answer than on Github Issues. If that's not already the case, do you mind opening a thread there?

Thanks!
