### ISSUE TITLE
How can we predict story future based on past events?

### ISSUE THREAD

**Issue by krigeta** [huggingface/transformers#12065]
Hello, is it possible to predict story future events on the basis of past events using transformer?

**Comment by NielsRogge** [comment]
Hi,

Please ask this question on the [forum](https://discuss.huggingface.co/), rather than here. Github issues are mostly for bugs/feature requests.

Thanks.

**Comment by krigeta** [comment]
Okay I will hop there

**Comment by krigeta** [comment]
Hello @NielsRogge, I posted there but I think the forum is not so resposive. so it would be great if you help me with this request.

Please.
