### ISSUE TITLE
src_lang/tgt_lang missing in mbart example

### ISSUE THREAD

**Issue by zijwang** [huggingface/transformers#12073]
## Environment info

- `transformers` version: 4.6
- Platform: linux
- Python version: 3.8
- PyTorch version (GPU?): 1.8

### Who can help

Models:

- blenderbot, bart, marian, pegasus, encoderdecoder,  t5: @patrickvonplaten, @patil-suraj

Library:
- tokenizers: @LysandreJik

## Information

Model I am using (Bert, XLNet ...): mbart

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

I am running the official example in the doc [here](https://huggingface.co/transformers/model_doc/mbart.html) under `Supervised training`. However, there is a warning of 

```
Keyword arguments {'src_lang': 'en_XX', 'tgt_lang': 'ro_RO'} not recognized.
```

when running

```
inputs = tokenizer(example_english_phrase, return_tensors="pt", src_lang="en_XX", tgt_lang="ro_RO")
```

Is this normal?

**Comment by zijwang** [comment]
Tagging @patrickvonplaten @patil-suraj @LysandreJik again in case you know what was going on here.

**Comment by patil-suraj** [comment]
Hi @zijwang , thanks a lot for spotting this.

The tokenizer API is changed a bit,  instead of passing `src_lang` and `tgt_lang` to tokenizes `__call__` method, we can now pass these when initializing the tokenizer, or we could set those properties as well. Here's a minimal example 

```python
from transformers import MBartForConditionalGeneration, MBartTokenizer

tokenizer = MBartTokenizer.from_pretrained("facebook/mbart-large-en-ro", src_lang="en_XX", tgt_lang="ro_RO")

# to change the src_lang
tokenizer.src_lang = "fr_XX"
```
