### ISSUE TITLE
examples requirements isn't in sync with `require_version_examples`

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#12086]
We have `require_version_examples`
https://github.com/huggingface/transformers/blob/b1a8aa94f0a2ccea7c68b79066141aa822b96e42/src/transformers/utils/versions.py#L123-L126

but it looks like it wasn't updated in the last reshuffle and requirements got split and it suggests incorrect solution.

I tried to offer to use it here: https://github.com/huggingface/transformers/pull/11927
but since requirements are now scattered over multiple files we probably should remove it and its usage in legacy scripts, since it gives wrong info where it's currently still used.

It's just one usage in several legacy scripts:
```
require_version_examples("pytorch_lightning>=1.0.4")
```
so we can just replace it with:
```
require_version("pytorch_lightning>=1.0.4")
```
which would do the trick.

@sgugger

**Comment by sgugger** [comment]
Yes, that works.
