### ISSUE TITLE
Provide more useful error message in Detr from_pretrained when timm not installed

### ISSUE THREAD

**Issue by nateraw** [huggingface/transformers#12091]
## Environment info

- `transformers` version: master
- Platform: Google Colab
- Python version: 3.7
- PyTorch version (GPU?):1.8.1+cu101
- Tensorflow version (GPU?):N/A
- Using GPU in script?:N/A
- Using distributed or parallel set-up in script?:N/A

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

[Here's a colab notebook.
](https://colab.research.google.com/drive/1b8RVCARcZU8kBFywRID8ZLPAYwhcd10p?usp=sharing)

1. install latest transformers from master w/o installing `timm`.
2. Try to init any `DetrModel` `from_pretrained`, and you'll see you get a misleading error
```python
from transformers import DetrForObjectDetection

model = DetrForObjectDetection.from_pretrained('facebook/detr-resnet-50')
```

Error thrown:

```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-175d7bae5f8e> in <module>()
      1 from transformers import DetrForObjectDetection
      2 
----> 3 model = DetrForObjectDetection.from_pretrained('facebook/detr-resnet-50')

AttributeError: type object 'DetrForObjectDetection' has no attribute 'from_pretrained'
```

3. Try the same w/ timm installed, and see that it works.

## Expected behavior

Have message informing user that they must have `timm` installed to use `from_pretrained` with `Detr` models instead of just telling them there is no attribute `from_pretrained`.

**Comment by LysandreJik** [comment]
Thanks for raising an issue! Fixing this in #12097

**Comment by NielsRogge** [comment]
Thanks for already testing out the model! Highly appreciate your feedback. If anything related to the model/docs can be improved, feel free to reach out.
