### ISSUE TITLE
Continuous training on Fine-tuned Model

### ISSUE THREAD

**Issue by Noskid1999** [huggingface/transformers#12095]
# 🚀 Feature request

How can I continue training on a Fine-tuned Model?
I have a fine tuned model from OpenSLR data. And I want to continue training on an model as I continue to gain transcribed audio data over time. Can I do like making the fine-tuned model as a checkpoint?

## Motivation

I am aiming to make a model for Nepali Language. I have a way to collect data over time and it is continuous. So, I want to find a way I can train the model continuously as I gain data over time

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!

**Comment by Noskid1999** [comment]
Sure, thank you.
