### ISSUE TITLE
run_squad.py predictions

### ISSUE THREAD

**Issue by Arjunsankarlal** [huggingface/transformers#1209]
## ❓ Can anyone explain how start_logit and end_logit value is been determined ? And how it can used to measure the reliability of the answer span
In some issues I saw that if start_logit and end_logit = -1 then it is concluded to be unanswerable question.

There are some cases where I get the

> "1": [
{
"text": "hover your mouse pointer",
"probability": 1.0,
"start_logit": -12.987695693969727,
"end_logit": -12.40383529663086
}
],

In this place, what these values of start_logit and end_logit actually mean ? Since logit is natural log of odds, what is considered here as odds ?

In some cases, if the number of nbest predictions is 1, then [here in utils_squad.py](https://github.com/huggingface/pytorch-transformers/blob/master/examples/utils_squad.py#L613-L614) the answer span is made `empty`, does it means that it is the right answer ?

            if len(nbest)==1:
                nbest.insert(0,
                    _NbestPrediction(text="empty", start_logit=0.0, end_logit=0.0))

But in the [same file](https://github.com/huggingface/pytorch-transformers/blob/master/examples/utils_squad.py#L618-L620), when there is no nbest predictions, again the answer span is made `empty`

        if not nbest:
            nbest.append(
                _NbestPrediction(text="empty", start_logit=0.0, end_logit=0.0))

For two different situations why the same answer is been set ?

**Comment by Santosh-Gupta** [comment]
The comments say this situation is when the answer is a single null , but I don't see any conditionals to filter for this. hmmm did you figure it out?
