### ISSUE TITLE
 'Speech2TextProcessor' has no attribute 'from_pretrained'`

### ISSUE THREAD

**Issue by Shiro-LK** [huggingface/transformers#12100]
## Environment info

- `transformers` version: 4.6.1
- Platform: ubuntu
- Python version: 3.7.10
- PyTorch version (GPU?): cpu 1.8.1
- Tensorflow version (GPU?): no tensorflow
- Using GPU in script?: no cpu

Models:

Speech2TextProcessor

## To reproduce

1. processor =Speech2TextProcessor.from_pretrained("facebook/s2t-small-librispeech-asr")

The error I got : 

`AttributeError: type object 'Speech2TextProcessor' has no attribute 'from_pretrained'`

I don't understand why I got this issue because in processing_speech_to_text.py, line 78 "from_pretrained" exist.

**Comment by LysandreJik** [comment]
Hello! I'm fixing this in #12145 to return a better warning.
