### ISSUE TITLE
GPT Neo Tokenizers can't change BOS or EOS token

### ISSUE THREAD

**Issue by mallorbc** [huggingface/transformers#12117]
## Environment info

- Platform: Linux-5.8.0-55-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.10
- PyTorch version (GPU?): 1.8.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: RTX 3090
- Using distributed or parallel set-up in script?: Using DeepSpeed

Conda env:
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py37h89c1867_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.2.0=h06a4308_610
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.1=h27cfd23_0
  - liblapack=3.9.0=9_mkl
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py37h27cfd23_1
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.1=py37ha9443f7_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.2=hbbd107a_1
  - numpy=1.20.2=py37h2d18471_0
  - numpy-base=1.20.2=py37hfae3a4d_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.2.0=py37he98fc37_0
  - pip=21.1.1=py37h06a4308_0
  - python=3.7.10=hdb3f193_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.8.1=py3.7_cuda11.1_cudnn8.0.5_0
  - readline=8.1=h27cfd23_0
  - scikit-learn=0.23.2=py37hddcf8d6_3
  - scipy=1.5.3=py37h8911b10_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.8.1=py37
  - torchvision=0.9.1=py37_cu111
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - chardet==4.0.0
    - click==8.0.1
    - datasets==1.7.0
    - deepspeed==0.4.0+8def3cb
    - dill==0.3.3
    - filelock==3.0.12
    - fsspec==2021.6.0
    - huggingface-hub==0.0.8
    - idna==2.10
    - importlib-metadata==4.5.0
    - multiprocess==0.70.11.1
    - ninja==1.10.0.post2
    - packaging==20.9
    - pandas==1.2.4
    - protobuf==3.17.3
    - psutil==5.8.0
    - pyarrow==3.0.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - regex==2021.4.4
    - requests==2.25.1
    - sacremoses==0.0.45
    - tensorboardx==1.8
    - tokenizers==0.10.3
    - tqdm==4.49.0
    - transformers==4.6.1
    - triton==0.4.2
    - urllib3==1.26.5
    - xxhash==2.0.2
    - zipp==3.4.1

### Who can help
@LysandreJik seems to be the one to tag as this is an issue with the tokenizer

## Information
When loading the GPT Neo tokenizer with either the GPT2Tokenizer, or with the AutoTokenizer, you are unable to change the EOS of BOS tokens through passing arguments

Model I am using: GPT Neo 2.7B and 1.3B  and its Tokenizer

The problem arises when using:
* [* ] my own modified scripts: (give details below)

The tasks I am working on is:
*[ *] my own task or dataset: (give details below)
I am trying to finetune the model using DeepSpeed and a custom dataset

## To reproduce

1. Load GPT Neo Tokenizer from pretrained using either AutoTokenizer or GPT2Tokenizer
2. Pass arguments to change EOS and BOS tokens
3. Print out the tokens using tokenizer.bos_token and tokenizer.eos_token
4. Notice that it has not changed
5. Do steps 1-3 for another model, say gpt2 and notice that it does change

```python
    tokenizer = AutoTokenizer.from_pretrained(
    "gpt2-xl",bos_token='<|beginoftext|>',
    eos_token='<|endoftext|>', pad_token='<|pad|>')
    print(tokenizer.bos_token)
    print(tokenizer.eos_token)
    print()
    tokenizer = AutoTokenizer.from_pretrained(
    "EleutherAI/gpt-neo-2.7B",bos_token='<|beginoftext|>',
    eos_token='<|endoftext|>', pad_token='<|pad|>')
    print(tokenizer.bos_token)
    print(tokenizer.eos_token)

    print()
    tokenizer = AutoTokenizer.from_pretrained(
    "EleutherAI/gpt-neo-1.3B",bos_token='<|beginoftext|>',
    eos_token='<|endoftext|>', pad_token='<|pad|>')
    print(tokenizer.bos_token)
    print(tokenizer.eos_token)
    quit()
```

That gives this:
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
<|beginoftext|>
<|endoftext|>

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
<|endoftext|>
<|endoftext|>

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
<|endoftext|>
<|endoftext|>

## Expected behavior
The expected behavior is that the values of the bos and eos tokens change.  It does not change though.

**Comment by patil-suraj** [comment]
Hi there, I just tried this but couldn't reproduce it. Here's the colab if you want to check https://colab.research.google.com/drive/1gGWMOdjF6wIVfUlo0XE1LfupY5T7ioVS?usp=sharing

**Comment by mallorbc** [comment]
I was using 4.6.1.  Perhaps its been fixed.  I ran your code as well and didn't see the issue.  I will close this issue.
