### ISSUE TITLE
TypeError when trying to load pretrained ALBERT model in BertTokenizer 

### ISSUE THREAD

**Issue by Puranjay-del-Mishra** [huggingface/transformers#12129]
## Environment info

- `transformers` version: 4.6.1
- Platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.8.1+cu101 (False)
- Tensorflow version (GPU?): 2.5.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@LysandreJik 

## Information

Model I am using (Bert, XLNet ...): BertTokenizer

The problem arises when using:
* [ *] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [* ] my own task or dataset: (give details below)

Trying to tokenize a dataset of tweets  
## To reproduce

from transformers import BertTokenizer

tokenizerr = BertTokenizer.from_pretrained("albert-base-v2")
->> The error message is ->
TypeError                                 Traceback (most recent call last)
<ipython-input-11-f632f8d4de7e> in <module>()
      1 from transformers import BertTokenizer
----> 2 tokenizerr = BertTokenizer.from_pretrained("albert-base-v2")

3 frames
/usr/lib/python3.7/genericpath.py in isfile(path)
     28     """Test whether a path is a regular file"""
     29     try:
---> 30         st = os.stat(path)
     31     except OSError:
     32         return False

TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

## Expected behavior
The code should load the pre-trained BertTokenizer model for the Albert-base-v2  model. The same thing happened with Albert-base-v1

**Comment by LysandreJik** [comment]
Hello! Why don't you try to load the ALBERT tokenizer in an ALBERT tokenizer?
```py
from transformers import AlbertTokenizer

tokenizer = AlbertTokenizer.from_pretrained("albert-base-v2")
```

**Comment by Puranjay-del-Mishra** [comment]
Hey!
I was not aware of its existence to be honest, but shouldnt loading it in the BertTokenizer work?

**Comment by LysandreJik** [comment]
ALBERT and BERT are different models, and the ALBERT tokenizer isn't related to BERT's tokenizer at all. They're not based on the same algorithms: BERT's tokenizer is using WordPiece, ALBERT's using Unigram.

If you're looking for a tokenizer to encompass all other tokenizers, take a look at the [`Auto*` classes](https://huggingface.co/transformers/model_doc/auto.html):

```py
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("albert-base-v2")
```
