### ISSUE TITLE
Ouput Includes Input

### ISSUE THREAD

**Issue by kurbster** [huggingface/transformers#12143]
Whenever I am generating text the input is included in the output. When the input is close to the maximum length the model barely produces any useful output.
# Information
When using transformers.pipeline or transformers.from_pretrianed, the model is only generating the input, when the input is long. For example,
`generator = transformers.pipeline('text-generation', model='gpt2')`
`prompt = "really long text that is 1023 tokens ..."`
`output = generator(prompt, mex_length=1024, do_sample=True, temperature=0.9)`
output in this case would be equal to the input prompt.
## To reproduce
[Here is a Collab notebook](https://colab.research.google.com/drive/1JzwSmFGrWY1bU6f-t-mgMug88NsRVllp#scrollTo=OgOhZxQJNseL) with simple examples of the problem. I am looking to generate output from input ~1300 tokens and running into this issue consistently. Is there a way around this?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!

**Comment by kurbster** [comment]
Ok, I posted my question [here](https://discuss.huggingface.co/t/output-includes-input/6831).

Thank you!
