### ISSUE TITLE
Cut off sequences of length greater than max_length= 512 for roberta

### ISSUE THREAD

**Issue by rush86999** [huggingface/transformers#1215]
## 🚀 Feature

Roberta uses max_length of 512 but text to tokenize is variable length. Is there an option to cut off source text to maximum length during tokenization process?
## Motivation
Most text are not fixed sizes but are still required for end goal of using roberta on new datasets. The roberta model will throw an error when it encounters a text size > 512. Any help is appreciated to allow tokenization and limit the size to maximum length for pretrained encoders. Alternative is to let the pretrained encoder adapt by increasing positional embedding size so an error is not thrown or use average pooling. I m not sure how this would be implemented and allow fine tuning.

I can't seem to figure out how to circumvent the text length problem as new data text length can go as large as 2500 or more but roberta is only 512 max.

**Comment by LysandreJik** [comment]
Hi! Indeed RoBERTa has a max length of 512. Why don't you slice your text?

**Comment by rush86999** [comment]
I was hoping the tokenizer could take care of it as a functionality? The actual hope is not to throw an error but allow training with it by increasing the positional encoding as a way to allow training on the whole text length. Is this possible?
