### ISSUE TITLE
Allow setting permissions of downloaded models (via envvar)

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#12169]
In our research group we all have user accounts on a server where we each run our own experiments (Ubuntu behind the scenes). By default, everyone is downloading `transformers` models to their own home directory. Let's say we have 20 researchers, that might mean that we have 20 duplicates of "bert-base-cased" on the server (and of many other models). This is not efficient at all and takes too much room to our liking.

We have tried creating a 777 directory as TRANSFORMERS_CACHE globally, but that does not work. If I download a model, some of the downloaded files get a read/write access for me as the creator of the file. This means that others cannot use the model (permission denied).

Our suggestion or request would be to have an option when downloading a model to also set its permissions for all downloaded files. Preferably adjustable via a (system-wide) environment variable. This would probably need to be added in file_utils.py, similar to other options like "local_files_only". 

I currently do not have time to work on this myself, but I am open to any feedback of course.

**Comment by LysandreJik** [comment]
Would PR https://github.com/huggingface/transformers/pull/11119 help with your use-case?

**Comment by BramVanroy** [comment]
> Would PR #11119 help with your use-case?

Indeed, thanks!
