### ISSUE TITLE
ViT for resolution beyond 224x224 support

### ISSUE THREAD

**Issue by empty-id** [huggingface/transformers#12167]
When the resolution changes, the size of position embedding of ViTModel also changes, which makes ```from_pretrained``` method not working.

So, how can I use ViT with a different resolution like 64x64?

**Comment by NielsRogge** [comment]
One would need to interpolate the pre-trained position embeddings. You can see how this is done in the original implementation [here](https://github.com/google-research/vision_transformer/blob/00883dd691c63a6830751563748663526e811cee/vit_jax/checkpoint.py#L224).

You can find a PyTorch implementation of that [here](https://github.com/yitu-opensource/T2T-ViT/blob/964796c75445aa5163766d1caa20755f67b0da6f/models/vit.py#L337).

**Comment by empty-id** [comment]
Thank you for your reply! Actually, I know how to interpolate the pos embedding. But I don't know how to do it seamlessly with huggingface ViTModel. Is it necessary to modify the internal code?

**Comment by empty-id** [comment]
When I change the image size of ViTModel, I cannot even load it from a pretrained checkpoint.

```python
from transformers import ViTModel
model = ViTModel.from_pretrained('vit-base-patch16-224', image_size=64)
```

This raises an error due to the mismatch of position embedding size.

**Comment by NielsRogge** [comment]
I think you first need to load the `state_dict` of the original model, like so:

```
from transformers import ViTModel

model = ViTModel.from_pretrained('google/vit-base-patch16-224') # load pretrained model
state_dict = model.state_dict()
```

Then, initialize a new `ViTModel` with custom `image_size`, update the position embeddings of the `state_dict` and load the new model with that `state_dict`:

```
from transformers import ViTConfig

config = ViTConfig.from_pretrained('google/vit-base-patch16-224', image_size=64)
# new model with custom image_size
model = ViTModel(config=config)

# update state_dict
new_state_dict = state_dict.copy()
old_posemb = new_state_dict['embeddings.position_embeddings']
if model.embeddings.position_embeddings.shape != old_posemb.shape:  # need resize the position embedding by interpolate
    new_posemb = resize_pos_embed(old_posemb, model.embeddings.position_embeddings) # use PyTorch function linked above
    new_state_dict['embeddings.position_embeddings'] = new_posemb

# equip new model with state_dict
model.load_state_dict(new_state_dict)
```

**Comment by empty-id** [comment]
Wow, you are so smart! That's awesome!

**Comment by clrkwng** [comment]
Thanks NielsRogge for pointing me here, very helpful resource. Just another quick question, where can we specify the patch size we would like ViT to extract from images?
