### ISSUE TITLE
How can we modify the MM-IMDB model for sequence to sequence generation tasks?

### ISSUE THREAD

**Issue by abhaygargab** [huggingface/transformers#12172]
Hi all, thank you so much for the wonderful service.

I have some doubts regarding the training details for MM-Imdb dataset.

Are the image encoder's and tokenizer's embeddings fine-tuned during training on MM-Imdb dataset? If not, can you suggest a way to do it or refer any material for help?

Is there a way to modify the code so that the model’s pre-trained weights can be used for sequence-to-sequence generations tasks instead of classification?

Thank You..

**Comment by NielsRogge** [comment]
Hi,

could you please ask this question on the [forum](https://discuss.huggingface.co/) rather than here? We like to keep Github issues for bugs/feature requests.

Thanks!
