### ISSUE TITLE
[Docs] Broken Link in the Benchmarks.rst

### ISSUE THREAD

**Issue by bhadreshpsavani** [huggingface/transformers#12200]
## Issue info

In the documentation at [Benchmarks page](https://huggingface.co/transformers/benchmarks.html) the last link is broken due to the reordering of examples folders

It is 
```
With the new `benchmark` tools, it is easier than ever to share your benchmark results with the community
:prefix_link:`here <examples/benchmarking/README.md>`.
```
should be changed to
```
With the new `benchmark` tools, it is easier than ever to share your benchmark results with the community
- :prefix_link:`Pytorch Benchmarking Results<examples/pytorch/benchmarking/README.md>`.
- :prefix_link:`Tensorflow Benchmarking Results<examples/tensorflow/benchmarking/README.md>`.
```
or a separate documentation page can be created for benchmarking the results of the model. Please Let me know if I can help or if it is being covered by another ongoing effort.

## Who can help?
@patrickvonplaten
@sgugger

**Comment by sgugger** [comment]
Don't hesitate to submit a PR with a fix!
