### ISSUE TITLE
Getting 404 Client Error when loading BaptisteDoyen/camembert-base-xnli

### ISSUE THREAD

**Issue by mothguib** [huggingface/transformers#12214]
## Environment info

- `transformers` version: 4.6.1
- Platform: Linux-5.11.16-arch1-1-x86_64-with-glibc2.33
- Python version: 3.9.5
- PyTorch version (GPU?): 1.9.0+cu111 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

## Information

The problem arises when using:
* [ ] the official example scripts: https://huggingface.co/BaptisteDoyen/camembert-base-xlni

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task

## To reproduce

```
from transformers import pipeline
classifier = pipeline("zero-shot-classification", 
                      model="BaptisteDoyen/camembert-base-xnli")
```

returns:

```
404 Client Error: Not Found for url: https://huggingface.co/BaptisteDoyen/camembert-base-xnli/resolve/main/config.json
```

**Comment by LysandreJik** [comment]
There's a typo in your model identifier:
```diff
- BaptisteDoyen/camembert-base-xlni
+ BaptisteDoyen/camembert-base-xnli
```
