### ISSUE TITLE
Argument `never_split` not working on `AutoTokenizer`

### ISSUE THREAD

**Issue by udeepam** [huggingface/transformers#12223]
## Environment info

- `transformers` version: 4.6.1
- Platform: Linux-4.19.0-14-cloud-amd64-x86_64-with-debian-10.7
- Python version: 3.7.9
- PyTorch version (GPU?): 1.8.1+cu102 (True)
- Tensorflow version (GPU?): 2.5.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

- tokenizers: @LysandreJik

## Information

Model I am using (Bert, XLNet ...): BERT

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased', never_split={'lol'})
tokenizer.tokenize("lol That's funny")
"""
['lo', '##l', 'that', "'", 's', 'funny']
"""
```

## Expected behavior

The expected output should be
```python
['lol', 'that', "'", 's', 'funny']
```

I know by using the `BertTokenizer` the `never_split` argument works e.g.
```python
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-large-uncased', never_split={'lol'})
tokenizer.tokenize("lol That's funny")
"""
['lol', 'that', "'", 's', 'funny']
"""
```
But I want to use the `AutoTokenizer` for another model,  `nghuyong/ernie-2.0-en`, and it doesn't work there either.

**Comment by LysandreJik** [comment]
Ah, I believe the fast tokenizers do not have the `never_split` option. In order to achieve this I would add the tokens to the vocabulary instead cc @n1t0 is there another way to handle this?

```py
>>> tokenizer.tokenize("lol that's funny")
['lo', '##l', 'that', "'", 's', 'funny']
>>> tokenizer.add_tokens(["lol"])
1
>>> tokenizer.tokenize("lol that's funny")
['lol', 'that', "'", 's', 'funny']
```

**Comment by udeepam** [comment]
Thanks! The suggestion works for the token `lol`. However another token that I do not want to be split is `...` and the suggestion does not work for this as shown below.
```python
>>> from transformers import AutoTokenizer
>>> tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased')
>>> tokenizer.tokenize("... that's funny")
['.', '.', '.', 'that', "'", 's', 'funny']
>>> tokenizer.add_tokens(["..."])
0
>>> tokenizer.tokenize("... that's funny")
['.', '.', '.', 'that', 
```

However, again it does work using the `BertTokenizer` and the `never_split` argument e.g.
```python
>>> from transformers import BertTokenizer
>>> tokenizer = BertTokenizer.from_pretrained('bert-large-uncased', never_split={'...'})
>>> tokenizer.tokenize("... That's funny")
['...', 'that', "'", 's', 'funny']
```

Is there another workaround?

**Comment by n1t0** [comment]
Hi @udeepam, I'm not sure to understand the goal of doing this.

```python
>>> tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased', use_fast=False, never_split={'lol'})
>>> tokenizer.tokenize("lol That's funny")
['lol', 'that', "'", 's', 'funny']
>>> tokens = tokenizer.encode("lol That's funny")
>>> tokens
[101, 100, 2008, 1005, 1055, 6057, 102]
>>> tokenizer.convert_ids_to_tokens(tokens)
['[CLS]', '[UNK]', 'that', "'", 's', 'funny', '[SEP]']
```

As you can see, the tokenizer doesn't split the `lol` token, but it doesn't know it. So it ends up being an `[UNK]` token. If it knew it, it wouldn't have split it in the first place. Is it the behavior you expect to get?

Unfortunately, I don't see any other workaround than what @LysandreJik proposed in the first place.
