### ISSUE TITLE
can predict_with_generate (do_eval) work with sharded_ddp fairscale in 4.6.1+?

### ISSUE THREAD

**Issue by gyin-ai** [huggingface/transformers#12235]
In 4.5.0, sharded_ddp won't work with  predict_with_generate in seq2seq or clm model training during the eval step. Wonder whether it can work in the latest version.

**Comment by gyin-ai** [comment]
Can I ask whether we have any progress on the model prediction (text generation) during the training with fairscale? Thanks/ cc @stas00

**Comment by stas00** [comment]
most likely you'd want to ask @sgugger as I he did the integration.

**Comment by sgugger** [comment]
`sharded_ddp` does not work for evaluation, as is mentioned in the documentation. I have mentioned that on the fairscale repository but did not get any update for the authors (same for the blocking aprt of Zero offload via fairscale) so I suggest you use DeepSpeed instead, where we have a much better support from the team at Microsoft.

**Comment by stas00** [comment]
and if fairscale solves the problem on their side and the work resumes in this direction, the key to making generate work would be to enabled `synced_gpus` here for fairscale:

https://github.com/huggingface/transformers/blob/fb65f65ea6175036f0cc8318145853e9c833f914/src/transformers/trainer_seq2seq.py#L164
