### ISSUE TITLE
Reconstructing Tokens from Bert Embedding?

### ISSUE THREAD

**Issue by patdflynn** [huggingface/transformers#12234]
Sorry if this was posted before but I couldn't it after a few searches.

My goal is to take a sentence, run it through BERT, perturb the contextualized embeddings from the output of BERT, and reconstruct the sentence text.

I'm currently using 'bert-base-uncased' as my tokenizer and model and a perturbed output torch tensor with each token embedding size 768. How do I reconstruct the sentence text?

Thanks!

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
