### ISSUE TITLE
Got unexpected result when using BertTokenizer in Chinese

### ISSUE THREAD

**Issue by hxxxxh** [huggingface/transformers#12249]
## Environment info
- `transformers` version: 4.7.0
- Platform: Linux-5.4.0-74-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.10
- PyTorch version (GPU?): 1.8.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False
- `tokenizers` version: 0.10.3

### Who can help
@LysandreJik 
@sgugger 

## Information

Model I am using (Bert, XLNet ...): bert-base-chinese

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

When I use BertTokenizer, I got unexpected results in some "strange" chars.
```python
text = "这是一个���中文句子"
tokenizer = BertTokenizer.from_pretrained("bert-base-chinese")
print(tokenizer.tokenize(text))
```
Output: ```['这', '是', '一', '个', '中', '文', '句', '子']```  
And I got the same result using BertTokenizerFast too.

## Expected behavior
I think it may cause an error or affect performance when doing sequence labeling tasks, like NER or Word Segment. 
And I noticed that I will get a more reasonable result when I downgrade the transformers to version 3.3.0 (with tokenizers==0.8.1rc2):  
```['这', '是', '一', '个', '[UNK]', '中', '文', '[UNK]', '句', '子']```

why this happens？Is there any way to get the correct result in the new version of transformers？

**Comment by LysandreJik** [comment]
Pinging @JetRunner

**Comment by JetRunner** [comment]
This behavior seems to be related to `BertTokenizerFast`. I'm not very sure whether I know how to fix it but I can give it a look at `tokenizers`.

**Comment by JetRunner** [comment]
I wouldn't say the current tokenization is "wrong", but I would prefer `BertTokenizerFast` to be consistent with Google's tokenizer. I'll look into this and let's see what's the behavior of Google BERT.

**Comment by JetRunner** [comment]
![image](https://user-images.githubusercontent.com/22514219/122767175-f594c700-d2d4-11eb-9168-954fa29297e7.png)
Here's what you get with the original Google BERT tokenizer. Kinda confusing..

**Comment by JetRunner** [comment]
@hxxxxh Given the chaotic output of different implementations, rather than try to "fix" one to be consistent with another, I would recommend you to clean the text before using it as an input.
