### ISSUE TITLE
finding a bug in training the code of /src/transformers/models/detr/modeling_detr.py

### ISSUE THREAD

**Issue by zhangbo2008** [huggingface/transformers#12248]
finding a bug in training the code of https://github.com/huggingface/transformers/blob/f74655cd9b2e316af9d862968bc59c15d6849cad/src/transformers/models/detr/modeling_detr.py

https://github.com/huggingface/transformers/blob/f74655cd9b2e316af9d862968bc59c15d6849cad/src/transformers/models/detr/feature_extraction_detr.py#L616
should change  encoded_inputs["targets"] to  encoded_inputs["labels"]
because in  https://github.com/huggingface/transformers/blob/f74655cd9b2e316af9d862968bc59c15d6849cad/src/transformers/models/detr/modeling_detr.py#L1350  we use variable of name labels in the function.

**Comment by NielsRogge** [comment]
Oh yeah, that makes sense, thanks for spotting it. I didn't have an issue with it as I never directly provided labels created by `DetrFeatureExtractor` to the model, but in case you do, you indeed will encounter an error.

Will update it!
