### ISSUE TITLE
Can't load tokenizer for 'imxly/t5-pegasus'.

### ISSUE THREAD

**Issue by xiaojinglu** [huggingface/transformers#12242]
when I use t5-pegasus on huggingface.co, What's the problem？
<img width="1589" alt="截屏2021-06-18 上午11 10 34" src="https://user-images.githubusercontent.com/12478408/122500741-e76d4f00-d025-11eb-839c-96f259c89af0.png">

**Comment by LysandreJik** [comment]
The tokenizer specified for that model is `T5Tokenizer`, which is a sentencepiece-based tokenizer. However, the tokenizer file is `vocab.txt`, which is a BERT-like (WordPiece) file.

The T5 tokenizer expects as `spiece.model` file generated by the SentencePiece library, or a `tokenizer.json` file generated by the Tokenizers library.

**Comment by xiaojinglu** [comment]
> The tokenizer specified for that model is `T5Tokenizer`, which is a sentencepiece-based tokenizer. However, the tokenizer file is `vocab.txt`, which is a BERT-like (WordPiece) file.
> 
> The T5 tokenizer expects as `spiece.model` file generated by the SentencePiece library, or a `tokenizer.json` file generated by the Tokenizers library.

so is it the fault of the uploaded model ?

**Comment by pony-m** [comment]
Can't load tokenizer for './models/t5-pegasus'

下载后使用也存在这个问题
