### ISSUE TITLE
Remove duplicate hidden_states of the last layer in BertEncoder in modeling_bert.py

### ISSUE THREAD

**Issue by usertomlin** [huggingface/transformers#1224]
## 🚀 Feature

For  "class BertEncoder" in modeling_bert.py, remove duplicate hidden_states of the last layer 

## Motivation

 
![image](https://user-images.githubusercontent.com/2401439/64491964-fb0c5300-d2a0-11e9-9873-d86ee9041db3.png)

Bert-Base models have 12 layers instead of 13 layers. But when config.output_hidden_states is true, "len(all_hidden_states)" is printed 13 instead of 12. It seems that the two lines under "# Add last layer" is improper, since the last layer's hidden_states are already added.

**Comment by LysandreJik** [comment]
Hi! Indeed, the BERT-base only has 12 layers. The `hidden_states` is 13-dimensional however because it keeps track of the inputs as well.

In the code you have shown, the `hidden_states` variable is computed between the two underlined variables you mentioned. None of it is redundant :)!

**Comment by usertomlin** [comment]
> Hi! Indeed, the BERT-base only has 12 layers. The `all_hidden_states` is 13-dimensional however because it keeps track of the inputs as well.
> 
> In the code you have shown, the `hidden_states` variable is computed between the two underlined variables you mentioned. None of it is redundant :)!

Thanks, I see :)
