### ISSUE TITLE
RAG with T5 in a multitask setting

### ISSUE THREAD

**Issue by sb1992** [huggingface/transformers#12250]
I was trying to run RAG with t5 for multiple tasks i.e fact checking and QA. As i understand only with t5 you can do that by adding a unique prefix for the particular task before the input I was wondering what could be the best way to handle that ? Do i preprocess  train.source, val.source so that they already have these prefixes or is their an easier way as well?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!

**Comment by shamanez** [comment]
@sb1992 

No, it doesn't matter whether you use T5 or BART. You can actually use a special token in front of every line in the target files.
