### ISSUE TITLE
Causal Mask in BertGeneration

### ISSUE THREAD

**Issue by JamesHujy** [huggingface/transformers#12266]
I cannot find the implementation of CausalMask in BertGeneration. Can you help me locate it?

**Comment by patrickvonplaten** [comment]
It's here:
https://github.com/huggingface/transformers/blob/cabcc75171650f9131a4cf31c62e1f102589014e/src/transformers/modeling_utils.py#L243
:-)
Note that `is_decoder` has to be set to True
