### ISSUE TITLE
ViTFeatureExtractor.save_pretrained() generate "preprocessor_config.json" but not "config.json"

### ISSUE THREAD

**Issue by daquarti** [huggingface/transformers#12278]
config.json is needed to use ViTForImageClassification.from_pretrained()

I made a pull-request

**Comment by LysandreJik** [comment]
`ViTFeatureExtractor` is the feature extractor, not the model itself. The model itself requires the `config.json` file that specifies the architecture of the model, while the feature extractor requires its `preprocessor_config.json` file. These two are different files.

**Comment by daquarti** [comment]
The problem is ViTForImageClassification.from_pretrained() not take "preprocessor_config.json" and you need to rename it "config.json"

**Comment by LysandreJik** [comment]
`ViTForImageClassification` is not `ViTFeatureExtractor`, the first one is a model while the second one is a feature extractor. See some usage examples [here](https://huggingface.co/transformers/model_doc/vit.html#transformers.ViTForImageClassification)
