### ISSUE TITLE
Are there any examples showing how to use the `metric_for_best_model` of class `TrainingArguments`?

### ISSUE THREAD

**Issue by yc1999** [huggingface/transformers#12301]
<img width="567" alt="截屏2021-06-22 下午5 49 14" src="https://user-images.githubusercontent.com/37548571/122903624-2a128c80-d382-11eb-9400-4bb884d6c0c6.png">

In the [documents](https://huggingface.co/transformers/master/main_classes/trainer.html#trainingarguments), it says one can pass a `str` to `metric_for_best_model `.I am kind of confused why this can work. For example, can I just set `metric_for_best_model="accuracy"`, and it will compute accuracy itself? And if I have my own metric, how can I customize it? Thank you😄

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Pinging @sgugger 

Thanks!

**Comment by sgugger** [comment]
The metrics need to be computed and have a name that is in what your `compute_metrics` function returns.

**Comment by yc1999** [comment]
> The metrics need to be computed and have a name that is in what your `compute_metrics` function returns.

this works for me，thank you~

**Comment by rjurney** [comment]
@sgugger are there standard metrics included? Can you use the ones from your evaluator?
