### ISSUE TITLE
Downloading the models is getting slower than before

### ISSUE THREAD

**Issue by stepbystep88** [huggingface/transformers#12318]
Downloading the models (using the **model.pre_trained('')** function) is getting slower than before, now the download speed is stable at 1MB/s, but it could reach 10MB/s a month ago.

I wonder if the official limits the download speed, please let me know if so.

Thanks for your supports.

**Comment by julien-c** [comment]
Nothing changed on our side.

Can you paste the output of e.g. `wget -O /dev/null https://huggingface.co/bert-base-uncased/resolve/main/pytorch_model.bin`?

**Comment by stepbystep88** [comment]
![image](https://user-images.githubusercontent.com/47015435/123083858-16832680-d453-11eb-94c6-6f18104b1376.png)

Of course, please check the above picture.

**Comment by julien-c** [comment]
Yep, that's downloading directly from [AWS Cloudfront](https://aws.amazon.com/cloudfront/), there's not much we can do on our side unfortunately

cc @osanseviero

**Comment by stepbystep88** [comment]
Okay, thanks for your attention to this issue.
