### ISSUE TITLE
Missing tokenizer_class for `mbart-large-50-many-to-one-mmt` model

### ISSUE THREAD

**Issue by Mehrad0711** [huggingface/transformers#12333]
Hi @patil-suraj,

I noticed all `mbart-50` models have their tokenizer_class set to "MBart50Tokenizer" in their config file except for `mbart-large-50-many-to-one-mmt`. This causes the wrong tokenizer to be loaded for this model (`tokenization_mbart` instead of `tokenization_mbart50`). Please check. Thanks!

**Comment by patil-suraj** [comment]
Good catch @Mehrad0711 ! Thank you for reporting this. I just fixed it https://huggingface.co/facebook/mbart-large-50-many-to-one-mmt/blob/main/config.json
