### ISSUE TITLE
ERROR: Failed building wheel for tokenizers

### ISSUE THREAD

**Issue by JaheimLee** [huggingface/transformers#12353]
## Environment info

- `transformers` version: 4.8.1
- Platform: Macbook pro M1 16G
- Python version: 3.8.10
- PyTorch version (GPU?):
- Tensorflow version (GPU?): 2.5.0

### Who can help
@LysandreJik

When I install transformers in my mac, this error occurred! 
`ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot be installed directly`

**Comment by LysandreJik** [comment]
Hi! Could you open an issue on `tokenizers` instead? https://github.com/huggingface/tokenizers
