### ISSUE TITLE
[Trainer.py] when --load_best_model_at_end is set in Distributed Training

### ISSUE THREAD

**Issue by logoutlzh** [huggingface/transformers#12369]
## Environment info

- `transformers` version: 4.4, not very sure
- Platform: linux
- Python version: 3.7
- PyTorch version (GPU?): 1.8
- Tensorflow version (GPU?): ////
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Distributed training in a single node with multi-gpus

### Who can help
 @sgugger 

## Information

Model I am using (Bert, XLNet ...): Bart

The problem arises when using:
trainer.py

The tasks I am working on is:
my own task or dataset

## To reproduce
I'm not sure if it's a bug or I misunderstood. So I am here for help. 

1.  set `--load_best_model_at_end` and use distributed training mode with multi-gpus.
2.  When the best model appears in the last step, the main process needs to save the model in `self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)` after training. However, the subprocess may run `self.model = self.model.from_pretrained(self.state.best_model_checkpoint)` before the best model is completely saved.
3. So the subprocess will occur `OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory <best model dir>......`

Evaluate:
1. I print the time after `self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)`  and time before `self.model = self.model.from_pretrained(self.state.best_model_checkpoint)`.  It seems that the result has confirmed my guess.
2. I add `dist.barrier()` after `self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)` and the error doesn't appear anymore.

**Comment by sgugger** [comment]
Could you try again on the latest version? This bug has normally been fixed (see [this comment](https://github.com/huggingface/transformers/blob/9a7545943dd611b0d4887a5ab3a7ef7f53b8e76f/src/transformers/trainer.py#L1351) and the four line below).

**Comment by logoutlzh** [comment]
> Could you try again on the latest version? This bug has normally been fixed (see [this comment](https://github.com/huggingface/transformers/blob/9a7545943dd611b0d4887a5ab3a7ef7f53b8e76f/src/transformers/trainer.py#L1351) and the four line below).

Yes, it looks good. I download the source code to the project, so I can't update it in time. I'm sorry to take up your time。
