### ISSUE TITLE
ImportError: cannot import name 'BertEncoder' from 'transformers'

### ISSUE THREAD

**Issue by Tikquuss** [huggingface/transformers#12374]
```
from transformers import  BertEncoder 
```

A week ago this import was working normally, but this morning I ran my code and got this error.
```
ImportError: cannot import name 'BertEncoder' from 'transformers' (unknown location)
```

How to import BertEncoder? ```'BertEncoder' in dir(transformers)``` is `False`

########################################
- `transformers` version: 4.8.1
- Platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.9.0+cu102 (False)
- Tensorflow version (GPU?): 2.5.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by LysandreJik** [comment]
Hello! I'm failing to find a version where this worked, going back to version 1.0.0. If you have it handy, could you point me to the version that had it?

If you want to import `BertEncoder` you can do it as such:
```
from transformers.models.bert.modeling_bert import BertEncoder
```
