### ISSUE TITLE
Module version identification problem

### ISSUE THREAD

**Issue by gaowanliang** [huggingface/transformers#12380]
## Environment info

- `transformers` version:  4.8.1
- Platform: Windows 10 x64
- Python version: 3.7.3
- PyTorch version (GPU?): 1.7.1
- Tensorflow version (GPU?): 2.0.0
- Using GPU in script?: GTX1060
##  Module version identification problem caused by "importlib_metadata"
![image](https://user-images.githubusercontent.com/41822468/123531202-1d50b880-d735-11eb-9d15-7223c587148e.png)

**Comment by LysandreJik** [comment]
Hello! What command did you run to get the first error?

**Comment by gaowanliang** [comment]
I just executed `python xxx.py` from the command, which references this package, and the specific project is [this](https://github.com/yangjianxin1/GPT2-chitchat)

**Comment by nreimers** [comment]
I have a similar issue after upgrading to transformers 4.9.1:

```
>>> import transformers
>>> transformers.__version__
'4.9.1'
>>> from transformers.utils.versions import require_version
>>> require_version("torch>=1.5.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reimers/miniconda3/envs/sbert/lib/python3.7/site-packages/transformers/utils/versions.py", line 114, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/home/reimers/miniconda3/envs/sbert/lib/python3.7/site-packages/transformers/utils/versions.py", line 50, in _compare_versions
    f"{requirement} is required for a normal functioning of this module, but found {pkg}=={got_ver}.{hint}"
ImportError: torch>=1.5.0 is required for a normal functioning of this module, but found torch==1.2.0.
>>> import torch
>>> torch.__version__
'1.7.1'
```


On an Ubuntu 20.04 system with Python 3.7.6 using miniconda.

Not sure why the wrong torch version is detected.
