### ISSUE TITLE
Wrong logical operation

### ISSUE THREAD

**Issue by alberto-hong** [huggingface/transformers#12408]
None of datasets in glue has bath "validation" and "validation_matched".

So, 'and' operation in https://github.com/huggingface/transformers/blob/7682e97702e4317231b3afe92359de384dba1e20/examples/pytorch/text-classification/run_glue.py#L418 should be fixed as 'or' operation.

It makes sense with following line 420 at run_glue.py 
(eval_dataset = raw_datasets["validation_matched" if data_args.task_name == "mnli" else "validation"])

Please let me know if there is something I miss :)

**Comment by LysandreJik** [comment]
If it was an 'or' operation, then with `raw_datasets = ["validation"]`, the second part of the statement would return `True` which would raise an error
