### ISSUE TITLE
Streaming mode in training examples

### ISSUE THREAD

**Issue by gsarti** [huggingface/transformers#12414]
# 🚀 Feature request

The v1.8,0 of `datasets` introduced [streaming mode](https://huggingface.co/docs/datasets/master/dataset_streaming.html). It would be very useful to include this mode in the training examples, either with a parameter `--stream_dataset` or an ad-hoc training script if radical changes are required to make it work.

## Motivation

Besides showcasing the potential of the new streaming feature, this would be very useful in the context of pre-training scripts (e.g., the new [`run_t5_mlm_flax.py`](https://github.com/huggingface/transformers/blob/master/examples/flax/language-modeling/run_t5_mlm_flax.py)) where large dataset like OSCAR and C4 are commonly leveraged. It would be especially useful to have it for the Flax Community Event!

## Your contribution

I can submit a PR and work to integrate the feature in some of the Flax examples.

Would love to hear the opinion of @patrickvonplaten and @patil-suraj on whether this is relatively easy to pull off!

**Comment by patrickvonplaten** [comment]
Hey @gsarti,

That's a great issue! We will provide at least one streaming example until Friday :-)

**Comment by gsarti** [comment]
For future watchers, @patrickvonplaten is working on this in #12470! Thanks!

**Comment by lhoestq** [comment]
Note that it's actually `datasets` 1.9.0 that will probably be released on Monday that will feature Streaming.
For now it's still available on the `master` branch only !
