### ISSUE TITLE
[DeBerta V2] The vocab size of DeBerta V2 is incorrect

### ISSUE THREAD

**Issue by hjptriplebee** [huggingface/transformers#12428]
### Who can help

@LysandreJik

## Information

I am using Deberta V2. The document and vocab of the tokenizer shows that its vocab size is 128K. But the vocab size in its [configuration](https://huggingface.co/microsoft/deberta-v2-xlarge/resolve/main/config.json) is 128100 which is 100 larger.
![image](https://user-images.githubusercontent.com/22477665/123915975-ae34c780-d9b3-11eb-916a-1159e04922e6.png)
It will make embedding not work as expected.

## Expected behavior

May be we should modify the vocab size in configuration?

**Comment by LysandreJik** [comment]
Maybe @BigBird01 can chime in :)

**Comment by hjptriplebee** [comment]
@LysandreJik I emailed to the author. He leave some space to add customized tokens for downstream tasks and this is by design.

**Comment by anhdungitvn** [comment]
v2/v3: 128000 + 100 (special tokens, unused tokens, e.g. reservation for PostOCR customized tokens) ---> 128100 in total

https://huggingface.co/transformers/v4.9.2/model_doc/deberta_v2.html
