### ISSUE TITLE
HfArgumentParser defaults booleans to on

### ISSUE THREAD

**Issue by Craigacp** [huggingface/transformers#12423]
## Environment info
- `transformers` version: 4.9.0.dev0 (initially discovered on 4.8.1)
- Platform: macOS-11.4-x86_64-i386-64bit
- Python version: 3.9.5
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Who can help
@sgugger

## Information

HfArgumentParser when used on a dataclass with a bool field with no default turns the bool on unless it's supplied with `--<field_name> False` or similar "false-y" value. I would expect that as the field has no default it should be false unless `--<field_name>` or `--<field_name> True` is supplied.  This is a behaviour change from `v3.0.0` where the booleans are parsed correctly as we're looking at upgrading and this issue hit us.

## To reproduce

1. Define a dataclass with a boolean field
2. Supply a list of arguments which does not include that field name
3. The field is turned on.

Appending this snippet to the bottom of [`test_basic` at line 110](https://github.com/huggingface/transformers/blob/master/tests/test_hf_argparser.py#L110) in `test_hf_argparser.py` fails the test.

```python

        args = ["--foo", "1", "--baz", "quux", "--bar", "0.5"]

        example, = parser.parse_args_into_dataclasses(args, look_for_args_file=False)

        self.assertFalse(example.flag)
```

Extending `args` with `["--flag","False"]` recovers the expected behaviour.

## Expected behavior

The boolean should be set to false if the argument is not passed in.

**Comment by Craigacp** [comment]
If you agree this is a bug in the parsing logic then we'd be happy to fix it and send a PR.

**Comment by sgugger** [comment]
Yes, it does look like a bug. Fix is quite simple, I can make a PR.

**Comment by Craigacp** [comment]
Ok thanks. That saves me a job later this week.

**Comment by sgugger** [comment]
If you want to have a look at the PR mentioned above and check it does give the expected behavior, that would be great!

**Comment by Craigacp** [comment]
Ok, I'll check it tomorrow against our internal use case to make sure it fixes that too.
