### ISSUE TITLE
Loading custom model

### ISSUE THREAD

**Issue by saksham-s** [huggingface/transformers#12425]
I had changed the definition of a token classification model and added another output head. Now when I try to load the model using AutoModelForTokenClassification it does not load the weights of the modified final layer which I had added. Is there any other class I can use to load this custom model.

**Comment by bablf** [comment]
Same. I run into several problems. I figured that I would need to call something like `CustomModel.from_pretrained("PATH_TO_CHECKPOINT")` to load the model. But that did not work for me either. If I find a solution I will give an update.
