### ISSUE TITLE
Using huggingface Pipeline in industry

### ISSUE THREAD

**Issue by Lassehhansen** [huggingface/transformers#12435]
Hi,

I was wondering if there is anything to be aware of when using your sentiment-analysis pipeline for industry projects at work. Are there any limitations to what I can or cannot do?

Thank you for your always amazing service.

Lasse

**Comment by LysandreJik** [comment]
The pipeline is a simple wrapper over the model and tokenizer. When using a pipeline in production you should be aware of:
- The pipeline is doing simple pre and post-processing reflecting the model's behavior. If you want to understand how the pipeline behaves, you should understand how the model behaves as the pipeline isn't doing anything fancy (true for sentiment analysis, less true for token classification or QA which have very specific post-processing).
- Pipelines are very simple to use, but they remain an abstraction over the model and tokenizer. If you're looking for performance and you have a very specific use-case, you will get on par or better performance when using the model and tokenizer directly.

Does that answer your question?

**Comment by Lassehhansen** [comment]
I think my question was minded for whether the pipeline is free to use in industry, and or whether there is any security issues with using it in an automated work process for industry projects? Not so much minded for the bias of the model.

Thanks in advance
Lasse

**Comment by julien-c** [comment]
For industry usage including security guidance etc I would recommend getting in touch with our Expert Acceleration Program at https://huggingface.co/support

Cheers

**Comment by Lassehhansen** [comment]
Perfect, I will try and do that. Thanks for the help
