### ISSUE TITLE
Wiki content part : XLM-RoBERTa,   "xlm-roberta-base"

### ISSUE THREAD

**Issue by pangbochen** [huggingface/transformers#12451]
In the wiki page for XLM-R
https://huggingface.co/transformers/model_doc/xlmroberta.html

the model name should be 'xlm-roberta-base'  instead of 'roberta-base'

@sgugger

**Comment by sgugger** [comment]
Yes, that's because those models are direct subclasses of Roberta, so they have the same documentation.
