### ISSUE TITLE
How to fine-tune a model with my custom tokenizer?

### ISSUE THREAD

**Issue by luoling1993** [huggingface/transformers#12476]
1. I want to train a tokenizer with my own datasets.
2. I have no enough data and resources to train a pretrained model from scratch.

pipeline:
1. train a tokenizer like [tokenizer_training](https://github.com/huggingface/notebooks/blob/master/examples/tokenizer_training.ipynb)
2. do something with current pretrained model, get a new pretrained model
3. fine-tune the pretrained model with my domain datasets, get my domain pretrained model
4. fine-tune the domain pretrained model for my downstream task.

and what should I do in the 2rd step?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
