### ISSUE TITLE
Release `utils/style_doc.py` as a python package

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#12473]
Hi,
I like the functionality of your [`utils/style_doc.py`](https://github.com/huggingface/transformers/blob/master/utils/style_doc.py).
Did you ever think about open sourcing it as a python package?

I think other projects might also want to use it.

**Comment by PhilipMay** [comment]
@sgugger

**Comment by sgugger** [comment]
It's very much linked to the way we write documentation in Transformers so it would need a bit of work to become a standalone package that can be used. I have no time to do it personally, but if someone wants to start building it, I'm happy to review things!

**Comment by PhilipMay** [comment]
> It's very much linked to the way we write documentation in Transformers so it would need a bit of work to become a standalone package that can be used. I have no time to do it personally, but if someone wants to start building it, I'm happy to review things!

@sgugger ok - cool! So if I would create such a standalone package which can be used by you and others - you would:
- help with review
- switch transformers to that implementation if it works and if I add you as maintainers

Would you do that?

**Comment by sgugger** [comment]
Definitely!

**Comment by PhilipMay** [comment]
> Definitely!

That is nice! Thanks.

> It's very much linked to the way we write documentation in Transformers

@sgugger The docstring formatter looks very "normal". Do you mean the rst formatter when you say "very much linked"?

**Comment by sgugger** [comment]
I meant there could be plenty of edge cases I never thought of since we write the Transformers documentation a certain way, sorry if I was unclear. Everything in that file is pretty standard otherwise.

**Comment by PhilipMay** [comment]
Hey @sgugger and @LysandreJik 
We creatated the new repository and added you with "write" role: https://github.com/telekom/style-doc

We can invite more ppl. from HF if you want.
The license is unchanged at "Apache 2.0" with HF still having the copyright with me (us) added.

Credits are given at the readme file.
I hope everything is nice for you.

An review is very welcome. :+1: 

Unfortunately, I also found the first small problem right away: https://github.com/telekom/style-doc/issues/10

**Comment by PhilipMay** [comment]
Everything is updated now and ready for a first release.

**Comment by PhilipMay** [comment]
So since the project is out at pypi now: Do you (HF) want to migrate to that tool?
You have commit rights on the project and can maintain it together with me.
First bug reports (and improvements) are already coming.
@sgugger @LysandreJik 

I can provide a PR if wanted.
