### ISSUE TITLE
model_type for gpt

### ISSUE THREAD

**Issue by tuhinjubcse** [huggingface/transformers#1248]
## ❓ Questions & Help

To run openai-gpt model in run_glue.py what should we provide as model_type? The model classes contains 
MODEL_CLASSES = {
    'bert'
    'xlnet'
    'xlm'
    'roberta'
}

**Comment by thomwolf** [comment]
Hi Tuhin, adding GPT/GPT2 is a tiny bit more complicated since these models need to have special tokens added to their vocabulary prior to fine-tuning (just a few more lines of code though).

Do you want to try to make a PR with these other models?

**Comment by tuhinjubcse** [comment]
Okay I will add bert as the model type i was just not sure if that d be the right thing to do , hence asked :)
