### ISSUE TITLE
text-classification example broken; version issue / inconsistency issues

### ISSUE THREAD

**Issue by pasta41** [huggingface/transformers#12500]
## Environment info
- `transformers` version: 4.8.2 (latest on master)
- Platform: Ubuntu 20.04
- Python version: 3.8.5
- PyTorch version (GPU?): 1.9
- Tensorflow version (GPU?): N/A
- Using GPU in script?: Didn't get that far
- Using distributed or parallel set-up in script?: No

### Who can help

@sgugger (because they have a commit that mentions to the 4.9dev release; and cross-checked that they are listed under the examples)
@patil-suraj (because they are listed under the examples)

## Information

Model I am using (Bert, XLNet ...): Bert

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The text-classification example crashes because it wants version 4.9.dev0 or more recent, but the latest on master is 4.8.2. I tried commenting this line out and running with 4.8.2, but there are arguments used that I'm guessing were introduced in 4.9 that 4.8.2 does not understand. In other words, the example crashes immediately.

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

Any of the tasks. I tried the example mrpc task in the text-classification readme.

## To reproduce

Copied from the readme / what is currently on master in terms of the code, run:

```
export TASK_NAME=mrpc

python run_glue.py \
  --model_name_or_path bert-base-cased \
  --task_name $TASK_NAME \
  --do_train \
  --do_eval \
  --max_seq_length 128 \
  --per_device_train_batch_size 32 \
  --learning_rate 2e-5 \
  --num_train_epochs 3 \
  --output_dir /tmp/$TASK_NAME/
```

## Expected behavior

Crashes because 4.8.2 is the latest in master and at least 4.9 is expected; when forcing to run with 4.8.2, crashes due to unrecognized arguments.

**Comment by LysandreJik** [comment]
Hello! Installing from `master` should yield the appropriate v4.9.0dev0 version, as this is the current version: https://github.com/huggingface/transformers/blob/master/src/transformers/__init__.py#L25

Did you install it from Pypi? `pip install transformers`
or from source? `pip install git+https://github.com/huggingface/transformers`

The latter should be done to install from source.

If you're looking for v4.8.2 examples, you can find them by going to that tag version: https://github.com/huggingface/transformers/tree/v4.8.2/examples

**Comment by pasta41** [comment]
Thank you so much for the quick response. I suppose the issue was installing via conda instead of pip. I will give this a try and get back to you. Thanks again!

**Comment by pasta41** [comment]
Thank you! Seems to be working. I am going to double check a few things tomorrow before closing. Thanks again!
