### ISSUE TITLE
Our Model works well in the local ! But when we upload that it doesnt work showing irrelevent performance ! 

### ISSUE THREAD

**Issue by sami10644** [huggingface/transformers#12508]
We tried every possible way . We followed the uploading steps perfectly . Deleting and re uploading  are done several times . It performs perfectly in the local ! When we download after uploading it  it shows this mysterious  problem  .

**Comment by sami10644** [comment]
https://www.facebook.com/messenger_media/?thread_id=4030097467081916&attachment_id=1014328569338034&message_id=mid.%24gAA5RWi_vhLyAp677_F6dmmqJ1S08

**Comment by LysandreJik** [comment]
Do you have a link to your model?

**Comment by sami10644** [comment]
Yes ! can you tell something about tokenizer ?
