### ISSUE TITLE
R-BERT implementation

### ISSUE THREAD

**Issue by RichJackson** [huggingface/transformers#1250]
## 🚀 Feature

An implementation of the R-BERT architecture for relationship classification

## Motivation

Hi @Huggingface. A recent paper describes an architecture for relationship classification called [R-BERT](https://arxiv.org/pdf/1905.08284.pdf), which claims SOTA performance on the Semeval 2010 Task 8 challenge. However, no code was provided with the paper. [I’ve written an implementation of this](https://github.com/azdatascience/pytorch-transformers/blob/rbert/examples/run_semeval.py) and can confirm it produces very good results (F1=89.07 using the official Semeval scoring script). Is this suitable for merging into the pytorch-transformers repo, or should it exist as a separate package?

**Comment by thomwolf** [comment]
This is mostly a new head for Bert, right?
If so, yes I think it could be a nice addition.
Is the tokenizer different as well?

**Comment by RichJackson** [comment]
That's correct. The new head is [here](https://github.com/azdatascience/pytorch-transformers/blob/rbert/pytorch_transformers/modeling_bert.py#L832) (Think that's in the right place). A new [tokenizer](https://github.com/azdatascience/pytorch-transformers/blob/rbert/pytorch_transformers/tokenization_rbert.py) is required as well, as it needs to insert some special characters surrounding the entities of interest.

**Comment by thomwolf** [comment]
Ok, I think we can accept a PR for that if you want to submit one.

Two notes on that:
- the tokenizer can inherit from `BertTokenizer` and you can probably mostly override the methods called `add_special_tokens_single_sentence` and `add_special_tokens_sentences_pair` to insert the special characters.
- the model and tokenizer should have tests for the head (check how we test the other heads, it's pretty simple) and a docstring like the other models.
- adding an example similar to `run_glue` would be nice also I think or just a usage example in the docstring.
