### ISSUE TITLE
Running XLNet on Squad

### ISSUE THREAD

**Issue by LeonCrashCode** [huggingface/transformers#1253]
## ❓ Questions & Help

This is the padding problem. In GLUE codes in the examples, the padding for XLNet is on the left of the input, but in Squad codes, the padding is on right. I was wondering which one is correct. 

Also, the inputs of `convert_examples_to_features` are different in Glue and Squad, where Squad uses most of default values like `pad_token, sep_token, pad_token_segment_id and cis_token_segment_id`, but Glue use the value of `tokenizer`. which one is correct?

Or the example codes are out-of-date? Thanks

**Comment by tbright17** [comment]
Seems like the run_squad script is in bad shape now. It just doesn't work.

**Comment by hohoCode** [comment]
same question..
