### ISSUE TITLE
Write With Transformer adding spaces?

### ISSUE THREAD

**Issue by zacharymacleod** [huggingface/transformers#1254]
This issue didn't happen before, but now whenever you use the autocomplete it always adds a space to the beginning, even when a space is not needed. I.E: when adding a comma / period to the end of a sentence, when starting a new line, or (most egregiously) when finishing a word that was only partially written.

As an aside, I wouldn't mind waiting a few extra seconds to get auto-fill suggestions that are longer than two words.

**Comment by estgvz** [comment]
Commenting to say I have also noticed this. Also I would assume the small amount of tokens being generated per autocomplete lately is because of compute concerns, not time concerns. It is a bit limiting.

**Comment by varkarrus** [comment]
Also having this problem!
