### ISSUE TITLE
Pegasus from Pytorch to tensorflow

### ISSUE THREAD

**Issue by karimfayed** [huggingface/transformers#12568]
I have fine-tuned PEGASUS model for abstractive  summarization using [this script](https://gist.github.com/jiahao87/50cec29725824da7ff6dd9314b53c4b3) which uses huggingface.
 The output model is in pytorch.

On huggingface [docs](https://huggingface.co/transformers/serialization.html) the following is supposed to do the required conversion:
`python convert_graph_to_onnx.py --framework <pt, tf> --model bert-base-cased bert-base-cased.onnx`
I use colab and I ran the following command to transform my pegasus model:
`!python convert_graph_to_onnx.py --framework <pt, tf> --model ./results/checkpoint-4000 ./results/checkpoint-4000.onnx`
I keep getting the following message which is confusing as  it is written in the documentation that the script convert_graph_to_onnx.py is at the root of the transformers sources:
![Screenshot (84)](https://user-images.githubusercontent.com/46823709/124824521-c2a82f80-df72-11eb-8406-128555604460.png)

**Thank you in advance.**

**Comment by LysandreJik** [comment]
You should update `<pt, tf>` to reflect the library you want to use to export the graph. Either `pt` or `tf`.
