### ISSUE TITLE
ImportError: cannot import name 'LineByLineTextDataset' from 'transformers' (unknown location)

### ISSUE THREAD

**Issue by ccyccxcl** [huggingface/transformers#12579]
when I tried to run the following codes as in **https://huggingface.co/blog/how-to-train** , it raised a bug:

from transformers import LineByLineTextDataset
dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="./oscar.eo.txt",
    block_size=128,
)

ImportError: cannot import name 'LineByLineTextDataset' from 'transformers' (unknown location)

@sgugger

**Comment by sgugger** [comment]
Yes this notebook is deprecated, you should look at the new version [here](https://github.com/huggingface/notebooks/blob/master/examples/language_modeling_from_scratch.ipynb) (or on [colab](https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/language_modeling_from_scratch.ipynb)).

More generally the up-to-date list of notebooks is in the [documentation](https://huggingface.co/transformers/master/notebooks.html).
