### ISSUE TITLE
HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded

### ISSUE THREAD

**Issue by moh-yani** [huggingface/transformers#12575]
Dear, 
I am new in Transformers, I just tried to run the syntax below:

from transformers import BertForSequenceClassification, AdamW, BertConfig
model = BertForSequenceClassification.from_pretrained(
    "bert-base-cased", 
    num_labels = 2, 
    output_attentions = False, 
    output_hidden_states = False 
)

model.cuda()

However, I got an error message like:

`HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /bert-base-cased/d6992b8cd27d7a132eafce6a8210272329a371b1c762d453588795dd3
835593e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9e60c6dd0>: Failed to establish a new connection: [Errno -2] Name or service 
not known'))
Traceback (most recent call last):
  File "/root/anaconda3/envs/bert/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/root/anaconda3/envs/bert/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/root/anaconda3/envs/bert/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
`

Any suggestions on how to fix it?

Kind regards,

MY

**Comment by julien-c** [comment]
Looks like a networking or DNS error. Can you try again, or try from another machine/network?

**Comment by moh-yani** [comment]
Dear @julien-c 

Thank you for the assistance. We will try again to run this.

Kind regards,

MY

**Comment by r4mbhardwaz** [comment]
are you using pythonanywhere.com for hosting by any chance..?
because they have a system known as whitelisting sites. you need to go and convince them on their forum to make it whitelisted then it will work perfectly.

@julien-c is right, it is a problem of DNS

**Comment by ctoxyz** [comment]
HTTPSConnectionPool(host='cdn-lfs.huggingface.co' - constant - unable to install this - all day long

**Comment by vijaykumar-1551** [comment]
from transformers import AutoModelWithLMHead, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-cased")
model = AutoModelWithLMHead.from_pretrained("distilbert-base-cased")

i am getting this error while I run the above code lines 
ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

any thoughts on how to proceed ?

**Comment by ajayaadit** [comment]
i am observing this error while trining the gpt4all 
ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url:

**Comment by joisonwk** [comment]
> HTTPSConnectionPool(host='cdn-lfs.huggingface.co' - constant - unable to install this - all day long

I also encountered the same problem, how did you solve it later?

**Comment by mohith7548** [comment]
any updates on this one?

**Comment by MikhailKravets** [comment]
@vijaykumar-1551 

> from transformers import AutoModelWithLMHead, AutoTokenizer
>
> tokenizer = AutoTokenizer.from_pretrained("distilbert-base-cased")
> model = AutoModelWithLMHead.from_pretrained("distilbert-base-cased")
>
> i am getting this error while I run the above code lines
> ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
>
> any thoughts on how to proceed ?

I encountered the same issue. As a workaraund I pass `resume_download=True` argument to `from_pretrained` and when the error occurs just restart the script 🤷 

For example,

```python
    model = AutoModelForCausalLM.from_pretrained(
        model_name, 
        torch_dtype=torch.float16, 
        device_map='sequential', 
        resume_download=True,
        cache_dir='.cache/open-llama-13b-open-instruct'
    )
```

**Comment by vijaykumar-1551** [comment]
hey sorry i was abit busy, i could not resolve the error yet, will update
as soon I find a solution.
Sorry for the delay.
--
Thanks & Regards
Vijay Kumar V
Python Developer
P2Fsemiconductors
https://www.p2fsemi.com/index.php
Contact: 6361960718

**Comment by mikechen66** [comment]
I have solved the issue with the combined two methods to

**1. set a higher timeout of 2MB ( about 2000000 bytes)** 

It can improve half of the efficiency from 20% to up to 50% of the downloaded content (240MB in my case) 

```
import urllib3, socket
from urllib3.connection import HTTPConnection

HTTPConnection.default_socket_options = ( 
    HTTPConnection.default_socket_options + [
    (socket.SOL_SOCKET, socket.SO_SNDBUF, 2000000), 
    (socket.SOL_SOCKET, socket.SO_RCVBUF, 2000000)
    ])
```

**2. Add  the parameter of resume_download=True**

For example, I use from_pretrained() function as similar as your case.  It helps my jupyter notebook complete the last half of the downloaded content  according to the progress bar. 

```
from transformers import TFAutoModelForSeq2SeqLM, DataCollatorForSeq2Seq

model = TFAutoModelForSeq2SeqLM.from_pretrained(MODEL_CHECKPOINT, 
                                                resume_download=True,)

```

Since I add the timeout first, and then add the download parameter. So I have no chance to try the download parameter alone. The 2nd method could work alone. 

Cheers!

**Comment by vijaykumar-1551** [comment]
Thank you for the help buddy. WIll try these pointers.!!
--
Thanks & Regards
Vijay Kumar V
Python Developer
P2Fsemiconductors
https://www.p2fsemi.com/index.php
Contact: 6361960718

**Comment by svlandeg** [comment]
> 1. set a higher timeout of 2MB ( about 2000000 bytes)

Thanks for this, works like a charm! 🎉
