### ISSUE TITLE
Summarization failure "All images are copyrighted" for certain text inputs

### ISSUE THREAD

**Issue by polplop** [huggingface/transformers#12576]
## Environment info

- `transformers` version: 4.5.1
- Platform: Linux-5.2.18-200.fc30.x86_64-x86_64-with-fedora-30-Thirty
- Python version: 3.7.4
- PyTorch version (GPU?): 1.7.1+cu101 (True)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: nope

## Information

Model I am using (PEGASUS-xsum):

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details below)

## To reproduce

```python
# Minimal example
import torch

bad_txt = "delivery giant DoorDash launched its Japan operation on Wednesday, a move that is expected to further intensify the already fierce competition for a slice of the country's food delivery market. Starting Wednesday, customers in Sendai, a major city in northeastern Japan, can order from hundreds of local restaurants as well as national chains via DoorDash.  Japan is one of the largest delivery markets in the world, but it's still very underpenetrated relative to the size of the population and the size of the economy,  DoorDash co-founder and CEO Tony Xu told Nikkei Asia in an interview on Tuesday."

model_name = 'google/pegasus-xsum' # Fails
#model_name = 'google/pegasus-cnn_dailymail' # Works fine
device = 'cuda' if torch.cuda.is_available() else 'cpu'

from transformers import PegasusForConditionalGeneration, PegasusTokenizer, PegasusConfig
tokenizer = PegasusTokenizer.from_pretrained(model_name)
model = PegasusForConditionalGeneration.from_pretrained(model_name).to(device)


def summarize(src_text):
    batch = tokenizer(src_text, truncation=True, padding='longest', return_tensors="pt").to(device)
    translated = model.generate(**batch,
                                early_stopping=True).to(device)
    tgt_text = tokenizer.batch_decode(translated, skip_special_tokens=True)[0]
    return tgt_text
    
print(summarize(bad_txt))
# Summary output (xsum) :  All images are copyrighted.
# Summary output (cnndm): delivery giant DoorDash launched its Japan operation on Wednesday.<n>The move is expected to further intensify the already fierce competition for a slice of the country's food delivery market.<n>Japan is one of the largest delivery markets in the world, but it's still very underpenetrated relative to the size of the population.
```

## Expected behavior
A relevant summary is produced by the model. 

Shortening the length of the input at the start or end seems to make it work, however words removed are arbitrary. Input is already much less than token limit 512.

**Comment by Sba-Stuff** [comment]
It seems Pegasus-XSum is waste of time and space, let me try cnn-dailymail

**Comment by Sba-Stuff** [comment]
I tried cnn-dailymail. its working. I wasted my 2.5 GB of data trying XSum. Soon In University will try Bart too...
![image](https://github.com/huggingface/transformers/assets/36412543/4f216fc3-620c-4eb4-8d08-c0c83e2f7dfa)
