### ISSUE TITLE
'MT5Tokenizer' is not defined (on Google colab) 

### ISSUE THREAD

**Issue by rashmibanthia** [huggingface/transformers#12588]
## Environment info

- `transformers` version: `transformers-4.9.0.dev0`
- Platform: Google Colab
- Python version: `3.7.10` 
- PyTorch version (GPU?):  `1.9.0+cu102`
- Tensorflow version (GPU?): `2.5.0`
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@sgugger , @patil-suraj 

## Information

Trying to run_mlm.py  - 

The problem arises when using:
- Just importing packages. 

## To reproduce

1. Run the following on Google colab 
2. 

```
!pip install git+https://github.com/huggingface/transformers.git

from transformers import (
    CONFIG_MAPPING,
    MODEL_FOR_MASKED_LM_MAPPING,
    AutoConfig,
    AutoModelForMaskedLM,
    AutoTokenizer,
    DataCollatorForLanguageModeling,
    HfArgumentParser,
    Trainer,
    TrainingArguments,
    set_seed,
)
```
Error message - 
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-a06d7b6932ed> in <module>()
      2 
      3 
----> 4 from transformers import (
      5     CONFIG_MAPPING,
      6     MODEL_FOR_MASKED_LM_MAPPING,

5 frames
/usr/local/lib/python3.7/dist-packages/transformers/models/mt5/__init__.py in <module>()
     94         globals()["__file__"],
     95         _import_structure,
---> 96         extra_objects={"MT5Tokenizer": MT5Tokenizer, "MT5TokenizerFast": MT5TokenizerFast},
     97     )

NameError: name 'MT5Tokenizer' is not defined
```

## Expected behavior
No error when importing.

Thank you for your help!

**Comment by rashmibanthia** [comment]
Fixed it for now - `!pip install git+https://github.com/huggingface/transformers.git@b29c394`

**Comment by sgugger** [comment]
Should be fixed now, thanks for reporting!
