### ISSUE TITLE
ViT doesnt use tokenizer, yet shown as example transformer website

### ISSUE THREAD

**Issue by dmatos2012** [huggingface/transformers#12581]
## Environment info

- `transformers` version: 4.9.0.dev0
- Platform: Linux-5.4.0-1043-gcp-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.3.4 (tpu)
- Jax version: 0.2.16
- JaxLib version: 0.1.68
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

## Information

Model I am using (Bert, XLNet ...): ViT

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Open vit [transformer](https://huggingface.co/google/vit-base-patch16-224) website 
2. Click on "</> Use in Transformers"
3. Copy the text  and run it

Error trace:
```
    tokenizer = AutoTokenizer.from_pretrained("google/vit-base-patch16-224")
  File "/home/david/transformers/src/transformers/models/auto/tokenization_auto.py", line 576, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.vit.configuration_vit.ViTConfig'> to build an AutoTokenizer.
Model type should be one of RetriBertConfig, RoFormerConfig, T5Config, MT5Config, MobileBertConfig, DistilBertConfig, AlbertConfig, CamembertConfig, PegasusConfig, MBartConfig, XLMRobertaConfig, MarianConfig, BlenderbotSmallConfig, BlenderbotConfig, BartConfig, LongformerConfig, RobertaConfig, ReformerConfig, ElectraConfig, FunnelConfig, LxmertConfig, LayoutLMConfig, DPRConfig, SqueezeBertConfig, BertConfig, OpenAIGPTConfig, GPT2Config, TransfoXLConfig, XLNetConfig, FlaubertConfig, XLMConfig, CTRLConfig, FSMTConfig, BertGenerationConfig, DebertaConfig, DebertaV2Config, RagConfig, XLMProphetNetConfig, Speech2TextConfig, M2M100Config, ProphetNetConfig, MPNetConfig, TapasConfig, LEDConfig, ConvBertConfig, BigBirdConfig, IBertConfig, Wav2Vec2Config, HubertConfig, GPTNeoConfig, LukeConfig, BigBirdPegasusConfig, CanineConfig.
```

## Expected behavior
Able to load the model correctly. Also @patrickvonplaten already solved it for me saying its ViTFeatureExtractor instead, but still it should be changed in the website. Thank you!

**Comment by patrickvonplaten** [comment]
cc @julien-c @LysandreJik @sgugger @patil-suraj - For Vision and Speech models we probably should create a `AutoProcessor` and adapt the default website widget to not use `AutoTokenizer` for Vision & Speech

**Comment by sgugger** [comment]
There is the `AutoFeatureExtractor` class already for vision (since there are no processors there).

**Comment by kartikpodugu** [comment]
I am facing same problem for 'facebook/dino-vitb16' on hugging face. 
I am trying to do use transformers.onnx to convert model to onnx. 
Though, there is no tokenizer for this model, it looks for tokenizer. 
Any solution for this ?

**Comment by ydshieh** [comment]
> 

Hi @kartikpodugu Could you open a new issue with a description and a code snippet that reproduce the issue? Thank you.

**Comment by SangbumChoi** [comment]
@kartikpodugu @ydshieh 
I also faced same issue in from transformers import ViTForImageClassification.
However, I resolved this issue by upgrade the transformers version.

[Old] 4.12.0.dev0
[New] 4.29.2

**Comment by ydshieh** [comment]
@SangbumChoi Could you open a new issue with a description, your full environment information, and a code snippet that reproduce the issue? Thank you.

Tried `from transformers import ViTForImageClassification` and it works fine.
