### ISSUE TITLE
XLNet tokenizer returns empty list instead of string for some indexes

### ISSUE THREAD

**Issue by andrey999333** [huggingface/transformers#1260]
## 🐛 Bug

Model I am using (Bert, XLNet....):

XLNet

Language I am using the model on (English, Chinese....):

English

The problem arise when using:
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] my own task or dataset: (give details)

## To Reproduce

1. Create tokenizer: tokenizer = XLNetTokenizer.from_pretrained(path)
2. Try to decode index 4: tokenizer.decode(4)
3. You get empty list [] although expected is a string

## Expected behavior

Decode method of the tokenizer should return a string and not a list.

## Environment

* OS:
* Python version: 3.7
* PyTorch version: 1.1.0
* PyTorch Transformers version (or branch): 1.2.0

**Comment by thomwolf** [comment]
Hi,
`tokenizer.decode()` expect a sequence of ids as indicated in the doc/docstring: https://huggingface.co/pytorch-transformers/main_classes/tokenizer.html#pytorch_transformers.PreTrainedTokenizer.decode

**Comment by andrey999333** [comment]
well, as far as i see, the tokenizer can accept both - sequence or single index. For example:
`tokenizer = XLNetTokenizer.from_pretrained('xlnet-base-cased')`
`tokenizer.decode(3)`
produce '<cls>' as well as `tokenizer.decode([3])`.

And the problem happens in both cases:
`tokenizer.decode([4])` produces empty string. And what is even more strange if index 4 is in the sequence the result is list instead of a string. For example:

`tokenizer.decode([35,109])` gives 'I new', but `tokenizer.decode([35,109,4])` generates list instead of a string `['I new']`

**Comment by andrey999333** [comment]
ok, it looks like 4 is an index of a separation token and it turns one sequence into sequence of sequences each of which will be decoded into string. So if index 4 presents in the sequence, the result will be list of strings. This behavior is quite unintuitive. If it was created purposely, should be properly documented. I've got very strange bug in my code that was hard to track, since index 4 was predicted very rarely and out of 500 predictions 1 was buggy.

**Comment by thomwolf** [comment]
Thanks for the bug report. Indeed this was an unwanted behavior. Fixed on master now.
