### ISSUE TITLE
Vocab Size does not change when adding new tokens

### ISSUE THREAD

**Issue by ncoop57** [huggingface/transformers#12632]
Env:
- `transformers` version: 4.8.2
- Platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.9.0+cu102

When adding new tokens to an existing tokenizer, the tokenizer's vocab size variable doesn't change. I believe it should be updated every time the tokens change.

Here is a google colab to reproduce: https://colab.research.google.com/drive/1mC_eSmHOgA_F5fPX7AsUt86jAbC7iSSw?usp=sharing

Specifics:
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("gpt2")
current_size = tokenizer.vocab_size
tokenizer.add_tokens(["new_token"])
tokenizer.vocab_size, current_size, len(tokenizer.vocab)
```

Outputs: (50257, 50257, 50258)

The same happens when I do the following as well
`tokenizer = AutoTokenizer.from_pretrained("gpt2", additional_special_tokens=["new_token"])`

**Comment by NielsRogge** [comment]
I think you should print(len(tokenizer)) instead of vocab_size (the latter being a fixed attribute). Refer to [this](https://github.com/huggingface/transformers/issues/1413#issuecomment-538083512) and [this](https://github.com/huggingface/transformers/blob/2dd9440d0835782e41ae415a68e71fd15051c428/src/transformers/tokenization_utils.py#L161).

**Comment by ncoop57** [comment]
ah okay, didn't realize this was expected behavior. Thanks!

**Comment by Debolena7** [comment]
So, shouldn't we change the vocab size, too, after adding the new tokens? But when I try to change the vocab size in the config, we can't load the pre-trained model as there is a size mismatch in the weights.
