### ISSUE TITLE
USE_TORCH while import transformers forever true

### ISSUE THREAD

**Issue by Talisberg** [huggingface/transformers#12641]
## Environment info

- `transformers` version: 4.8.0
- Platform: linux
- Python version: 3.6
- PyTorch version (GPU?):1.8.1(No)
- Tensorflow version (GPU?):2.0.1(No)
- Using GPU in script?:No
- Using distributed or parallel set-up in script?:No

### Who can help
@sgugger @Rocketknight1 

## Information

Model I am using (Bert, XLNet ...):AutoTokenizer(Bert)

The problem arises when using:
* Importing transformers while Using TensorFlow backend
error arises : 
```transformers/file_utils.py``` 
```if _torch_available:
    280     torch_version = version.parse(importlib_metadata.version("torch"))
--> 281     _torch_fx_available = (torch_version.major, torch_version.minor) == (
    282         TORCH_FX_REQUIRED_VERSION.major,
    283         TORCH_FX_REQUIRED_VERSION.minor,

AttributeError: 'Version' object has no attribute 'major'
```

The tasks I am working on is:
* [ ] trying to use ```train_new_from_iterator``` on top of ```bert-base-cased``` 
* [ ] my own task or dataset: (give details below)

## To reproduce

1. https://github.com/huggingface/transformers/pull/9441
2. row 67, forever True (```USE_TORCH```) So cannot reach (```USE_TF```) , row 80

## Expected behavior
allow transformers import, when using TF

**Comment by sgugger** [comment]
I am unsure of what the bug is and the reproducer you are suggesting. You are not supposed to change the source code of the library to activate `USE_TORCH`, you should set it as an environment variable.

**Comment by Talisberg** [comment]
Please close issue,
Something wrong with my env

בתאריך יום ב׳, 12 ביולי 2021 ב-17:33 מאת Sylvain Gugger <
***@***.***>:
