### ISSUE TITLE
translation with identical source and target language, for text normalization

### ISSUE THREAD

**Issue by desothier1** [huggingface/transformers#12666]
Hi,

This is rather a general question about translation and I am aware that I don't follow exactly your guidelines, so I am sorry for that.
(We could run the examples mentioned in your readme, great tool!)

We try to conceive normalization for Dutch, as a 'translation' task.

So, is it for instance possible to use source + target language, defined as the same language, for instance

    --source_lang nl_XX \
    --target_lang nl_XX \

{"translation": {"nl_XX": "liefst geen energie vandaag . waar is **m'n** oplaadstation ?", "nl_XX": "liefst geen energie vandaag . waar is **mijn** oplaadstation ?"}}

or

    --source_lang source\
    --target_lang target \

{"translation": {"source": "liefst geen energie vandaag . waar is **m'n** oplaadstation ?", "target": "liefst geen energie vandaag . waar is **mijn** oplaadstation ?"}}

## Environment info
https://github.com/huggingface/transformers/tree/master/examples/pytorch/translation

--model_name_or_path facebook/mbart-large-50-many-to-many-mmt

Thanks for your answer!

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
