### ISSUE TITLE
'TransfoXLLMHeadModelOutput' object has no attribute 'loss'

### ISSUE THREAD

**Issue by phfaustini** [huggingface/transformers#12661]
## Environment info

- `transformers` version: 4.6.1
- Platform: Linux-5.11.0-7620-generic-x86_64-with-glibc2.10
- Python version: 3.8.10
- PyTorch version (GPU?): 1.8.1 (True)
- Tensorflow version (GPU?): not installed (NA)

Models:
- Transformer XL

## To reproduce

Just to run the example from the documentation: https://huggingface.co/transformers/model_doc/transformerxl.html#transfoxllmheadmodel

```python
import torch
from transformers import TransfoXLTokenizer, TransfoXLLMHeadModel
tokenizer = TransfoXLTokenizer.from_pretrained('transfo-xl-wt103')
model = TransfoXLLMHeadModel.from_pretrained('transfo-xl-wt103')
inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs, labels=inputs["input_ids"])
loss = outputs.loss
```

## Expected behavior

I should get a loss, but an exception is thrown instead: 

AttributeError: 'TransfoXLLMHeadModelOutput' object has no attribute 'loss'

**Comment by LysandreJik** [comment]
Indeed, there's an issue with the docstring! `TransfoXL` has two losses, here's the correct snippet:
```py
import torch
from transformers import TransfoXLTokenizer, TransfoXLLMHeadModel
tokenizer = TransfoXLTokenizer.from_pretrained('transfo-xl-wt103')
model = TransfoXLLMHeadModel.from_pretrained('transfo-xl-wt103')
inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs, labels=inputs["input_ids"])
losses = outputs.losses
```

Would you like to open a PR to fix the docstring?
