### ISSUE TITLE
Converting fairseq roberta to transformer throws ModuleAttributeError: 'RobertaHubInterface' object has no attribute 'args'

### ISSUE THREAD

**Issue by fdas3213** [huggingface/transformers#12670]
https://github.com/huggingface/transformers/blob/c523b241c2e50c3ed035bb76b938b6a944fed7e5/src/transformers/models/roberta/convert_roberta_original_pytorch_checkpoint_to_pytorch.py#L59

Had this error `ModuleAttributeError: 'RobertaHubInterface' object has no attribute 'args'` when running
```
convert_roberta_original_pytorch_checkpoint_to_pytorch.convert_roberta_checkpoint_to_pytorch(roberta_checkpoint_path='/home/ubuntu/fairseq/checkpoints/',
                                                                                                 pytorch_dump_folder_path='./huggingface/',
                                                                                                 classification_head=False)
```

`roberta.args.encoder_embed_dim` should now be converted to `roberta.model.encoder.args.encoder_embed_dim` to bypass this issue with the current fairseq version

**Comment by fdas3213** [comment]
line 81&82 `roberta_sent_encoder.emb_layer_norm` should be changed to `roberta_sent_encoder.layernorm_embedding`

**Comment by diiogofernands** [comment]
hi @fdas3213, are any other changes needed?

**Comment by fuyang1013** [comment]
I met the same error just now, thanks for your solution, and I was wondering why attention was not paid to this bug?

**Comment by yanpengt06** [comment]
I just met too. Thanks for sharing the bugs here!!
