### ISSUE TITLE
confusing description in prepare_seq2seq_batch of MBart

### ISSUE THREAD

**Issue by XuhuiZhou** [huggingface/transformers#12683]
## Information

The model that I am using is `MBart-50`

In the description of `prepare_seq2seq_batch`, it says _Prepare model inputs for translation. For best performance, translate one sentence at a time._. Does this mean we should not do batching if we want to obtain the best performance? I am curious why it is the case since the paper itself does not mention that.

## Expected behavior

The performance should be the same doing batching or not.

@patil-suraj

**Comment by patil-suraj** [comment]
Hi @XuhuiZhou, the `prepare_seq2seq_batch` method is now deprecated and the description is a bit outdated.
we don't recommend using it anymore. You could refer to this section to see how to prepare data for mbart-50 https://huggingface.co/transformers/model_doc/mbart.html#training-of-mbart-50
