### ISSUE TITLE
No docs for v2.3.0

### ISSUE THREAD

**Issue by alexcoca** [huggingface/transformers#12686]
## Environment info

- `transformers` version: 2.3.0

### Who can help

Documentation: @sgugger

## To reproduce

Click [here](https://huggingface.co/transformers/v2.3.0/model_doc/gpt2.html#gpt2doubleheadsmodel) and see there are no docs for 2.3.0.

## Expected behavior

Documentation should be displayed when clicking [here](https://huggingface.co/transformers/v2.3.0/model_doc/gpt2.html#gpt2doubleheadsmodel)

**Comment by alexcoca** [comment]
@sgugger , I think all docs up to 2.9 are gone (checked 2.8 randomly and it was missing) so there might be a broader isssue.

**Comment by sgugger** [comment]
It might be linked to use more recent versions of sphinx when building it, though I'm not sure. This is not a priority for us, especially for such an older version (it would be different if the docs of the last major version were down), so I don't think anyone on our side will investigate this further.

**Comment by alexcoca** [comment]
@sgugger, you are making a valid point. 

However, I just wanted to highlight that _a lot_ of research hinges on these older versions as, unfortunately, people do not maintain their research code once it's out there. It would be helpful if the docs did not disappear so we can still work with others' legacy code when we have to.
