### ISSUE TITLE
Flax - Loading pretrained model overwrites weights of different shapes

### ISSUE THREAD

**Issue by borisdayma** [huggingface/transformers#12681]
## Environment info

- `transformers` version: master
- Platform: Ubuntu
- Python version: 3.9

### Who can help
@patil-suraj @sgugger 

## Information

Model I am using (Bert, XLNet ...): Custom FlaxBart

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details below)

## To reproduce

1. Create a custom model by subclassing - just change output shape (lm_head & final_logits_bias)
2. use `CustomModel.from_pretrained('facebook/bart-large-c')
3. check `model.params['final_logits_bias'].shape`, it will come from the pretrained model

## Expected behavior

The shape of weights should be checked prior to be overwritten.

Right now my approach is:
* load pre trained model
* init custom model from config
* update manually the weights needed

**Comment by sgugger** [comment]
This should be fixed by the work in #12664

**Comment by borisdayma** [comment]
Closing because it was fixed
