### ISSUE TITLE
could you add an option to transfer variables from float32 to float16 in GPT2 model to reduce model size and accelerate the inference speed 

### ISSUE THREAD

**Issue by carter54** [huggingface/transformers#1269]
## 🚀 Feature
could you add an option to transfer variables from float32 to float16 in GPT2 model
## Motivation
reduce model size and accelerate the inference speed

**Comment by thomwolf** [comment]
You should give a look at NVIDIA's apex library and PyTorch `model.half()` method.

**Comment by Damiox** [comment]
@thomwolf Do you know if the gpt2 model needs to be pre-trained with apex support in order to use NVIDIA's apex library (e.g. O1 mode) at inference time? Was mixed precision used during the training of the gpt2 model? Is there a way I can verify that?

**Comment by Damiox** [comment]
Do we have models trained with mixed precision enabled for gpt2? I can't find them in huggingface's repo.
