### ISSUE TITLE
[Examples]Flax Seq2Seq example fails when doing only eval or predict

### ISSUE THREAD

**Issue by bhadreshpsavani** [huggingface/transformers#12698]
## Descriptions

In the flax example if we only do predict or eval step it is not flexible enough to work. It will fail at this line
https://github.com/huggingface/transformers/blob/5dd0c956a8eb492c8597e9673cc1d818f0e6b501/examples/flax/summarization/run_summarization_flax.py#L569

because the current script is written in such a way it will always need a training dataset
I have modified a version of the same file which works but I need to remove the below line in that case
https://github.com/huggingface/transformers/blob/5dd0c956a8eb492c8597e9673cc1d818f0e6b501/examples/flax/summarization/run_summarization_flax.py#L467
and i always need to pass training data and create train_dataset by preprocessing even if i am not doing training

### Who can help
@patrickvonplaten @patil-suraj @sgugger

**Comment by patil-suraj** [comment]
yes, right now for simplicity the scripts are written such that they always expect train datasets.

Feel free to open a PR :)

**Comment by bhadreshpsavani** [comment]
Sure, I will open PR!
