### ISSUE TITLE
OSError: Not found: "/root/.cache/huggingface/transformers/5ec31591d9130cc9be0872e6b3dc0b276e514ab96e68404ac4a876ff03cb413b.dbd4bc2544d5c9f8f0d109844726c1600fa95cf0ba770b54c146f702be6e55dc": No such file or directory Error #2

### ISSUE THREAD

**Issue by EricPeter** [huggingface/transformers#12691]
This happens when try to load the model on another device

## Environment info

- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by LysandreJik** [comment]
Hello! What's the code that triggers this error?

**Comment by EricPeter** [comment]
import os
loaded_model = torch.load("mt_luganda.pt",map_location=torch.device('cpu'))

**Comment by LysandreJik** [comment]
Are you sure? That's unrelated to `tranformers` or `huggingface`, yet I do see a `transformers` cache error in your issue title.

**Comment by EricPeter** [comment]
am trying to load that model in another machine

**Comment by pepi99** [comment]
Same problem.

**Comment by pepi99** [comment]
Any solution?

**Comment by bvelker** [comment]
Same issue. Trying to load a pickled tokenizer inside of a docker container
with open(f"t5-base_tokenizer.pkl", 'rb') as f:
     tok = pickle.load(f)
