### ISSUE TITLE
Strange output from summarization models 

### ISSUE THREAD

**Issue by Zahz1** [huggingface/transformers#12693]
I am trying to get some models working for summarizing news articles, but for some reason I keep getting this strange out

Output:
"In our series of letters from African journalists, film-maker and columnist Farai Sevenzo looks at ... [subject of input article]"

This has happened on multiple models (Pegasus, Bart, and Roberta) and multiple different inputs. The output is either the correct summary for the article or this incorrect output listed above. Does anyone have any idea how to fix this problem?

code:

from transformers import PegasusTokenizer, TFPegasusModel, PegasusModel, TFPegasusForConditionalGeneration
import tensorflow as tf

src_text = """ article text put here """

tokenizer = PegasusTokenizer.from_pretrained('google/pegasus-xsum')
model = TFPegasusForConditionalGeneration.from_pretrained('google/pegasus-xsum')

inputs = tokenizer(src_text, truncation=True, padding='longest', return_tensors="tf", )
translated = model.generate(**inputs)
tgt_text = tokenizer.batch_decode(translated, skip_special_tokens=True)
print(tgt_text)

**Comment by dtsukiyama** [comment]
I see this happening now with pegasus models. Similar to the @Zahz1 I get the following:

"In our series of letters from African journalists, filmmaker and columnist Ahmed Rashid looks at some of the issues facing the continent."

The text that is being summarized has nothing to do with the above generated summarization.
