### ISSUE TITLE
Examples/flax/run_clm_flax.py showing error file extension error for train_file attribute even though file has the correct extension

### ISSUE THREAD

**Issue by AnantShankhdhar** [huggingface/transformers#12702]
## Environment info

- `transformers` version: 4.9.0.dev0
- Platform: Linux-5.4.0-1043-gcp-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.3.4 (tpu)
- Jax version: 0.2.16
- JaxLib version: 0.1.68
- Using GPU in script?: NO
- Using distributed or parallel set-up in script?: NO

### Who can help
@patrickvonplaten @patil-suraj 

## Information

Model I am using (Bert, XLNet ...): GPT2

The problem arises when using:
* [ 1] the official example scripts: (give details below)
Used examples/flax/run_clm_flax.py for gpt 2 text generation
* [ 2] my own modified scripts: (give details below)
For the running command I modified the one given for contextual language modelling in examples/flax/language-modeling/README.md by removing dataset name parameter and instead passing the train_file argument as
--train_file = "/home/anantshankhdhar/gpt2-rap-lyric-generator/Lilgpt.txt"\  from my system

The tasks I am working on is:
* [ 1] my own task or dataset: (give details below)
I made a dataset call Lilgpt.txt which is a txt file consisting rap lyrics . Each song starts with a <BOS> token and ends with an <EOS> token

## To reproduce

1.Make a new directory test and change to this directory
2.Add tokenizer.json and config.json from the gpt2 repo from (https://huggingface.co/gpt2/tree/main) to this repository
3.make a run.sh file like this
<img width="1440" alt="Screenshot 2021-07-14 at 2 34 59 AM" src="https://user-images.githubusercontent.com/56432951/125616296-4fbc7b18-1432-4d35-a4e6-7563ed8edd9e.png">
4.Add a txt file as the train_file attribute in run.sh and add a txt file dataset to the directory
5. type ./run.sh in terminal

## Expected behavior

1. you will get the following error:-

 File "./run_clm_flax.py", line 640, in <module>
    main()
  File "./run_clm_flax.py", line 241, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/anantshankhdhar/transformers/src/transformers/hf_argparser.py", line 191, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 13, in __init__
  File "./run_clm_flax.py", line 164, in __post_init__
    assert extension in ["csv", "json", "txt"], "`train_file` should be a csv, a json or a txt file."
AssertionError: `train_file` should be a csv, a json or a txt file.
 
2. However our train_file is txt only so we should have not got the error
3. The ideal behavior is training begins smoothly

**Comment by patrickvonplaten** [comment]
Hey @AnantShankhdhar, 

I cannot copy paste the script to run the code since it's a screenshot (please never post screenshots of code in an issue, always copy-paste & format them with:

```
run.sh --param1 --param2
```

**Comment by patrickvonplaten** [comment]
To solve you error, you should not do:

```bash
./run_clm_flax.py \
     ...
     --train_file = "file.txt" \
```

but 

```bash
./run_clm_flax.py \
     ...
     --train_file="file.txt" \
```

(Note how there are no whitespaces around the `=` in the bash script)

**Comment by AnantShankhdhar** [comment]
Thanks yes it worked
