### ISSUE TITLE
[Bug?] question answering - end position of each input is weird

### ISSUE THREAD

**Issue by woong97** [huggingface/transformers#12708]
I run "python run_qa.py" in transformers/examples/pytorch/question-answering.
In prepare_train_features function, I think "end position" is lower than expected postiion.

I tested first example in examples(squad) in "prepare_train_features" function
For example, answer text = 'Saint Bernadette Soubirous'
print(tokenizer(answer_text))
=> return: {'input_ids': [101, 3002, 16595, 9648, 4674, 2061, 12083, 9711, 2271, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

print(input_ids[tokenized_examples['start_positions'][0]:tokenized_examples['end_positions'][0]])
=> return: [3002, 16595, 9648, 4674, 2061, 12083, 9711]

=> Thus I think last token 2271 is dropped. 

For other input sentences, I think last token is dropped
Isn't it bug??

**Comment by LysandreJik** [comment]
I believe @sgugger worked on that script

**Comment by sgugger** [comment]
Hi there, noticed you closed this so may have come to the same conclusion, but the "end_positions" will give you the position of the last token in the answer. So you should add a +1 in your slice to include that token at "end_positions".

**Comment by woong97** [comment]
Thank you for your reply.
I recognized my mistakes, thus I closed the issue myself.
Thank you for checking one more time.
Next time, I'll post the issue deliberately!

2021년 7월 16일 (금) 오전 2:13, Sylvain Gugger ***@***.***>님이 작성:
