### ISSUE TITLE
Doc - expecting `push_to_hub` method for Tokenizers to be also in the Tokenizer class doc pages

### ISSUE THREAD

**Issue by thomwolf** [huggingface/transformers#12700]
# 🚀 Doc request

The gist is in the title. I was expecting the doc/docstring for the `push_to_hub` method for Tokenizers to be also in the Tokenizer class doc pages, e.g. on the main `Tokenizer` API landing page: https://huggingface.co/transformers/main_classes/tokenizer.html

**Comment by LysandreJik** [comment]
cc @sgugger
