### ISSUE TITLE
layoutlm TokenClassificationPipeline

### ISSUE THREAD

**Issue by uwong** [huggingface/transformers#12714]
Hi, I was looking at using transformers.pipeline for TokenClassification with an instance of  microsoft/layoutlm-base-uncased that I have fine tuned.  I would like to use pipeline to take advantage of the entity aggregation_strategy feature for extracted entities.

However it is unclear to me how/whether TokenClassificationPipeline works with layoutlm for inference because layoutlm expects both a input text and input bounding boxes, unlike other text only models.  

Do you know if TokenClassificationPipeline is supposed to work with layoutlm and are there any examples?

**Comment by LysandreJik** [comment]
cc @NielsRogge

**Comment by NielsRogge** [comment]
I'm afraid the TokenClassificationPipeline will not work with LayoutLM, the reason being that, as you mention, the model expects an additional input besides text, namely bounding boxes.

We are currently discussing the design of pipelines for models like LayoutLM.

**Comment by uwong** [comment]
Ok thanks for the information!  I'll just work around it for now.

**Comment by vprecup** [comment]
@NielsRogge are you aware of any developments in terms of pipeline integration for LayoutLM-like models? Thanks :)

**Comment by NielsRogge** [comment]
@mishig25 worked on supporting LayoutLM for the object detection pipeline, but that wasn't added in the end. Not sure if we can add it to the existing pipeline, cause the model requires a few additional inputs (`bbox`, and `pixel_values`), cc @Narsil
