### ISSUE TITLE
Doctest Integration

### ISSUE THREAD

**Issue by will-rice** [huggingface/transformers#12738]
# 🚀 Feature request

It would be nice to add doctest to ensure new additions have working examples in the docstrings and that existing examples do not become outdated with API changes. The feature is already in [pytest](https://docs.pytest.org/en/6.2.x/doctest.html) so adding it should be straightforward.

## Motivation

This will reduce the number of PRs for typos/errors in docstring examples which should allow reviewers to focus on other PRs.

## Your contribution

I wouldn't mind working on this if everyone thinks it is a good idea.

**Comment by LysandreJik** [comment]
Hi @will-rice! Most of our tests are setup to work with doctest, and we had doctest coverage a few months back. Unfortunately, as the number of model grows, the issue is less of a documentation issue and more of an infrastructure issue :) We're working on setting them back up as we speak.

**Comment by will-rice** [comment]
ok awesome! I'll go ahead and close this then.
