### ISSUE TITLE
How to finetune mT5

### ISSUE THREAD

**Issue by laibamehnaz** [huggingface/transformers#12746]
I am using mT5 for the task of summarization on a language other than English. But even after training for 30 epochs, the generations are very bad with rouge 1 as 31.5, whereas mBART gives a rouge 1 of 43.1 after training only for 11 epochs. 
I wanted to know if mT5's performance is expected to be like this compared to mBART, or am I doing something wrong. 
Appreciate any help. Thank you :)

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!

**Comment by laibamehnaz** [comment]
> Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
> Could you ask your question on the [forum](https://discuss.huggingface.co) instead?
> 
> Thanks!

Alright. Thank you so much!!
