### ISSUE TITLE
Write with Transformer: Please, add an autosave to browser cache!

### ISSUE THREAD

**Issue by varkarrus** [huggingface/transformers#1276]
## 🚀 Feature

In Write with Transformer, the writing should be periodically saved to the browser cache, so that if the user accidentally refreshes the page, their work that they may have spent hours on won't be lost.

## Motivation

I just lost several hours worth of writing because I accidentally refreshed the page.

## Additional context

:(

**Comment by LysandreJik** [comment]
Hi @varkarrus, thank you for your feature request. There is a "save & publish" button on the top right-hand side, which saves your document on a specific URL. Does this fit your needs?

**Comment by varkarrus** [comment]
Does it begin autosaving after you do that? If so, then probably!

**Comment by julien-c** [comment]
Nope, it does not currently auto-save 🙁

One quick fix I've thought about would be to pop a window alert if closing a tab that's got non-saved changes.

**Comment by varkarrus** [comment]
Oh, even that alone would be a lifesaver!
