### ISSUE TITLE
How to override model.generate() function in GenerationMixin class?

### ISSUE THREAD

**Issue by yeounyi** [huggingface/transformers#12767]
Hi, I want to override `_generate_no_beam_search`, `_generate_beam_search` methods in `GenerationMixin` class to adjust `next_token_logits`. 
I tried it by adding adjusted methods in my custom model code but seems not working. 
I'd appreciate any help. Thanks!

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!

**Comment by rxlian** [comment]
Hi, have you found the solutions?

**Comment by yeounyi** [comment]
@rxlian Hi, I failed to override `model.generate()` function, but in my case overriding `_prepare_encoder_decoder_kwargs_for_generation` function in the model definition was successful!
