### ISSUE TITLE
max_length parameter in Wav2Vec2FeatureExtractor doesn't affect

### ISSUE THREAD

**Issue by yanirmr** [huggingface/transformers#12774]
## Environment info

- `transformers` version: 4.8.2
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.8.5
- PyTorch version (GPU?): 1.9.0+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?:no

### Who can help
@sgugger

## Information

I'm attempting to receive a features vector of short wav (audio) files using wav2vec by using Hugging Face Transformers.

The problem arises when using:

* [ X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ X] my own task or dataset: (give details below)

## To reproduce
I ask a question about that in [StackOverflow](https://stackoverflow.com/questions/68430210/how-to-limit-the-size-of-the-features-vector-in-wav2vec)
1.  Two wav files for example are in this [drive ](https://drive.google.com/drive/folders/1j-BNp8D8yN16exgoacgDtDrnMF-jQP91?usp=sharing)
2. extract the feature vector of any file by using a pre-trained wav2vec model with a size limit parameter
3. measure the size of the output  vector
4. surprise...

minimal code example: 
```
import librose
import numpy as np
from transformers import Wav2Vec2FeatureExtractor
input_audio, _ = librosa.load(file,
                                      sr=16000)
        features_with_padding = feature_extractor(input_audio, sampling_rate=16000,
                                return_tensors="np", padding="max_length", max_length=60000).input_values                                
        features_without_padding = feature_extractor(input_audio, sampling_rate=16000,
                                  return_tensors="np", max_length=60000).input_values
        print(features_with_padding.shape, features_without_padding.shape)
```

## Expected behavior
The expected behavior is to get only 60K vector size and not 80-90K vector.
Ideally, I want to get the same size vectors but I don't think that it's possible.

Thanks!

**Comment by sgugger** [comment]
cc @patrickvonplaten and @patil-suraj

**Comment by patrickvonplaten** [comment]
@yanirmr - thanks a lot for you issue! The problem is that we currently don't support "truncation" in Transformers which means that when one wants to pad to a length that is shorter than the `max_length` nothing is changed. However, `truncation` is a very important feature so I will work on adding this functionality!
