### ISSUE TITLE
Error in the model card page

### ISSUE THREAD

**Issue by yananchen1989** [huggingface/transformers#12777]
https://huggingface.co/facebook/bart-large-mnli
this page is about the 

> facebook/bart-large-mnli model. 

However, in the section of 

> With manual PyTorch

the example show the loaded model is joeddav/xlm-roberta-large-xnli, which is not 

> facebook/bart-large-mnli

I suppose that this is an error .

**Comment by LysandreJik** [comment]
Thank you for the report, I have updated the modelcard in [`hf.co#c626438`](https://huggingface.co/facebook/bart-large-mnli/commit/c626438eeca63a93bd6024b0a0fbf8b3c0c30d7b)
