### ISSUE TITLE
Raise exceptions instead of using assertions for control flow

### ISSUE THREAD

**Issue by willfrey** [huggingface/transformers#12789]
https://github.com/huggingface/transformers/blob/546dc24e0883e5e9f5eb06ec8060e3e6ccc5f6d7/src/transformers/models/gpt2/modeling_gpt2.py#L698

Assertions can't be relied upon for control flow because they can be disabled, as per the following:

```shell
$ python --help
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
...
-O     : remove assert and __debug__-dependent statements; add .opt-1 before
         .pyc extension; also PYTHONOPTIMIZE=x
...
```

From my understanding, this is why mypy has no qualms about using them to narrow types because you can turn them off at runtime and so they incur zero cost.

Would you be open to me changing these assertions to other appropriate exceptions as I encounter them?

**Comment by sgugger** [comment]
That is an excellent point, and we welcome any PR that changes assert's to proper exception. We have been doing that for long error messages anyway, and I agree with you it's a better choice (as long as we raise the appropriate exception of course).

**Comment by sgugger** [comment]
I'm adding the good first issue label, this way if someone wants to take care of one file to remove all asserts and replace them with proper exceptions, they can make a PR with it!

(Don't try to do all files of the library at one ;-) )

**Comment by Josh1108** [comment]
Hi @sgugger,

I'd like to take up one of the files to start. Should I pick up modelling_gpt2.py and go ahead?

**Comment by sgugger** [comment]
Any of the files with assert statements is fair game :-)

**Comment by AmbiTyga** [comment]
Hi @sgugger,
I'd be happy to do this. So I need to change `assert` to 'Exception' type error for only one file?
(Not allowed to do this for every file?)

**Comment by willfrey** [comment]
Just adding my two cents but I wouldn’t raise bare `Exception`s but instead raise the appropriate type of exception given the error.

**Comment by AmbiTyga** [comment]
I have created PR #13184 for this issue. Kindly go through it.
Thanks

**Comment by jeffin07** [comment]
@sgugger   is this still open ? If so any files with assertion came under the issue right ? Can i join this issue if it's not completed

**Comment by sgugger** [comment]
@jeffin07 You can pick any file that has not already been treated.

**Comment by litanlitudan** [comment]
@sgugger I am also going to pick several files to kill my time.

**Comment by m5l14i11** [comment]
I've created PR #13894 . Please take a look.

**Comment by kushagrabhushan** [comment]
Hello, I'm new to open source. I wanted to know if this issue is still open and if so how do i check which files have not been edited already and which files require changes still?

**Comment by LysandreJik** [comment]
Hello @kushagrabhushan! You can do a search across the repository and look for the `assert` keyword. Here's an example:
https://github.com/huggingface/transformers/blob/3e218523e87002c572f6424d6d24ac656bcc40be/src/transformers/models/bert/modeling_bert.py#L453

I recommend looking only for files in `src/transformers` and in `tests`. In `src/transformers`, it would be nice to replace them by `ValueError`s, and in `tests`, it would be ideal to replace them by unittest assertions. These can be `self.assertEqual`, `self.assertDictEqual`, etc, according to what the assertion is supposed to do.

I would recommend cloning the repository and using a tool to search for these, as the GitHub search isn't ideal for a search like this.

**Comment by JuheonChu** [comment]
I am going to tackle on this [modeling_distilbert.py](\src\transformers\models\distilbert\modeling_distilbert.py) with @Batese2001

**Comment by katiele47** [comment]
I'd like to work on this file [run_image_captioning_flax.py](https://github.com/huggingface/transformers/blob/main/examples/flax/image-captioning/run_image_captioning_flax.py)

**Comment by JuheonChu** [comment]
Replace assertion with ValueError in modeling_distilbert.py #20433

**Comment by JuheonChu** [comment]
> I am going to tackle on the file [modeling_distilbert.py](%5Csrc%5Ctransformers%5Cmodels%5Cdistilbert%5Cmodeling_distilbert.py) with @Batese2001

Replace assertion with ValueError exceptions in modeling_distilbert.py  #https://github.com/huggingface/transformers/pull/20433

**Comment by miyu386** [comment]
First time contributing here! I've created PR https://github.com/huggingface/transformers/pull/20478 for this issue. Would appreciate it if anyone could take a look

**Comment by JuheonChu** [comment]
I will look and give you a comment after it

Best,
John

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Baukebrenninkmeijer** [comment]
First time contributing for me as well! Please have a look at the following PR when you have time! #24757
