### ISSUE TITLE
Error while converting a RoBERTa TF checkpoint to Pytorch

### ISSUE THREAD

**Issue by LeenaShekhar** [huggingface/transformers#12798]
## Environment info

- `transformers` version: '3.5.1'
- Platform: Linux
- Python version: 3.6.8
- PyTorch version (GPU?): '1.6.0+cu101'
- Tensorflow version (GPU?): '1.14.0'
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

@LysandreJik, and @patrickvonplaten may be. 

## Information
Model I am using is RoBERTa (finetuned on a custom task). I would like to convert this TF checkpoint to a Pytorch checkpoint that I can further use with the HuggingFace codebase. I tried loading it through with the _from_tf_ flag set but it did not work (shown below). 
## To reproduce

```
>>> from transformers import RobertaConfig, RobertaForMaskedLM
>>> config = RobertaConfig.from_pretrained('../roberta_config.json')
>>> model = RobertaForMaskedLM.from_pretrained('../model.ckpt-396000.index', from_tf=True, config=config)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leshekha/.local/lib/python3.6/site-packages/transformers/modeling_utils.py", line 966, in from_pretrained
    model = cls.load_tf_weights(model, config, resolved_archive_file[:-6])  # Remove the '.index'
AttributeError: type object 'RobertaForMaskedLM' has no attribute 'load_tf_weights'
```

## Expected behavior

I expect to get a model object with the parameters initialized from the checkpoint provided. Just like the provided example in the documents page.

```
from transformers import BertConfig, BertModel
>>> # Loading from a TF checkpoint file instead of a PyTorch model (slower, for example purposes, not runnable).
>>> config = BertConfig.from_json_file('./tf_model/my_tf_model_config.json')
>>> model = BertModel.from_pretrained('./tf_model/my_tf_checkpoint.ckpt.index', from_tf=True, config=config)
```

**Comment by LeenaShekhar** [comment]
I solved it. Thanks.

**Comment by jonscottstevens** [comment]
How did you solve it?

**Comment by Ab1992ao** [comment]
Hello, how did you solved your problem?
