### ISSUE TITLE
FineTuning using single sentence document

### ISSUE THREAD

**Issue by tuhinjubcse** [huggingface/transformers#1280]
Hello

roBERTa is not using the next sentence prediction objective. I want to fine-tune the pre-trained model on an unlabelled corpus of domain-specific text (ULMFIT style intermediate pretraining).
The bottleneck is my examples are single short sentences, instead of a document with multiple sentences 

The INPUT format here says it requires a file with one sentence per line and one blank line between documents. For me, each document has a single sentence
https://github.com/huggingface/pytorch-transformers/tree/b62abe87c94f8df4d5fdc2e9202da651be9c331d/examples/lm_finetuning

The last time I raised an issue this was an expected behavior I know
Re : https://github.com/huggingface/pytorch-transformers/issues/272

How to do it now :) ? Any help is appreciated .

**Comment by thomwolf** [comment]
Hi Tuhin, you can use `example/run_lm_finetuning` now. The scripts in `examples/lm_finetuning` are deprecated (removed on master now).

**Comment by tuhinjubcse** [comment]
Thomas i checked the wiki text 2 format and its confusing to me . Do we have to seperate documents by new lines ? My input file is a set of single sentence documents one per line . Do i need a new line after each sentence ?

My format is
sent1
sent2
sent3

Do i need to have
sent1

sent2

sent3 ?

I am currently running without a new line after each sentence and getting 09/19/2019 03:37:22 - WARNING - pytorch_transformers.tokenization_utils -   Token indices sequence length is longer than the specified maximum sequence length for this model (3989110 >
 512). Running this sequence through the model will result in indexing errors

**Comment by tuhinjubcse** [comment]
Also while running
def mask_tokens(inputs, tokenizer, args):
    labels = inputs.clone()
    # We sample a few tokens in each sequence for masked-LM training (with probability args.mlm_probability defaults to 0.15 in Bert/RoBERTa)
    **masked_indices = torch.bernoulli(torch.full(labels.shape, args.mlm_probability)).bool()**

Getting error 
AttributeError: 'Tensor' object has no attribute 'bool'

**Comment by kaushaltrivedi** [comment]
you need to update your pytorch version.  I believe bool() function was intrcoduced in torch 1.1.0 or 1.2.0

**Comment by pmbaumgartner** [comment]
> I am currently running without a new line after each sentence and getting 09/19/2019 03:37:22 - WARNING - pytorch_transformers.tokenization_utils - Token indices sequence length is longer than the specified maximum sequence length for this model (3989110 >
> 512). Running this sequence through the model will result in indexing errors

I'm also getting this error. Is there more detail on the expected input format for the LM pretraining?
