### ISSUE TITLE
Converting a tensor to a python boolean might cause the trace to be incorrect. We can't record the data flow of python values

### ISSUE THREAD

**Issue by leoozy** [huggingface/transformers#12819]
## Environment info

- `transformers` version:
- Platform: CENTOS 8.
- Python version: 3.7
- PyTorch version (GPU?): 1.9.0 + cuda
- Tensorflow version (GPU?): No
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

## Information
![image](https://user-images.githubusercontent.com/26025961/126442774-d5833dbb-3ebb-4eeb-a12b-4a47141c9a74.png)
I convert the hugging face bart model to onnx model using transformer.onnx (thanks for the excellent tools). But these warnings occured and they may have a influencec on the performance of model.

**Comment by LysandreJik** [comment]
Hi @leoozy, you should safely disregard these warnings. The warnings should only apply to assertions we make to ensure that the input shape passed is correct.
