### ISSUE TITLE
run_mlm_no_trainer.py requires accelerate but not in requirements.txt

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/transformers#12849]
I just installed Transformers 4.9.0 as I'm really excited to investigate the tokeniser free CANINE model.

I noticed that the `examples/pytorch/language-modeling/run_mlm_no_trainer.py` script requires the `accelerate` library but that doesn't appear to be included in `examples/pytorch/language-modeling/requirements.txt` or the main `setup.py`

**Comment by sgugger** [comment]
Thanks for flagging, I added those to all examples in the PR mentioned above!

**Comment by LysandreJik** [comment]
Cosed by #12888
