### ISSUE TITLE
Set Experiment Name in `MLflowCallback`

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#12841]
In the `MLflowCallback` it is not possible to set the Experiment Name. 
As a consequence the run is logged to the Default experiment.

I would like to suggest the following feature:

It is possible to set an env. variable called `ML_FLOW_CALLBACK_EXPERIMENT_NAME`
which then calls `mlflow.set_experiment(experiment_name)`.

What do you think? As always I can provide a PR if wanted.

**Comment by PhilipMay** [comment]
PS: additionaly to the env. var we might want to add a constructore parameter - what do you think?

**Comment by orieg** [comment]
This issue should be reopened as it is intended for mlflow experiment name which is different from run_name.
