### ISSUE TITLE
wav2vec pretrain and fine-tune with huge data

### ISSUE THREAD

**Issue by lixx0105** [huggingface/transformers#12857]
Hi,
Thanks for the great efforts for wav2vec!

is there good example to fine-tune and pretrain wav2vec with huge data? 
it seems the official examples works fine with one GPU but not so good for multigpus.

Thanks.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
