### ISSUE TITLE
I donnot want print trainer's logging info

### ISSUE THREAD

**Issue by cdhx** [huggingface/transformers#12869]
torch 1.18.0，tf 1.14.0

every thing works well yesterday

i didn't do any thing, but today when i use predict of trainer, it print this infomation before the output 

this situation didn't occur before

```
***** Running Prediction *****
  Num examples = 1
  Batch size = 256
```

now i want this info don't print

I check the document, but didn't find a parameter to control don't print logger

```
In predict_loop  function

        batch_size = dataloader.batch_size
        num_examples = self.num_examples(dataloader)
        logger.info(f"***** Running {description} *****")
        logger.info(f"  Num examples = {num_examples}")
        logger.info(f"  Batch size = {batch_size}")
        losses_host: torch.Tensor = None
        preds_host: Union[torch.Tensor, List[torch.Tensor]] = None
        labels_host: Union[torch.Tensor, List[torch.Tensor]] = None
```

thanks @sgugger

**Comment by sgugger** [comment]
You can use the argument `log_level` to adjust the level of the logger. If you set it to "warning", it won't print this.

**Comment by cdhx** [comment]
thanks, it works
