### ISSUE TITLE
Evaluation result.txt path suggestion

### ISSUE THREAD

**Issue by brian41005** [huggingface/transformers#1286]
## 🚀 Feature

At pytorch-transformers/examples/**run_lm_finetuning**.py and **run_glue**.py
There is a line ```output_eval_file = os.path.join(eval_output_dir, "eval_results.txt")```

When setting evaluate_during_training **True**, `output_eval_file` will keep being overwritten.

I think `output_eval_file` can be assigned like

 `output_eval_file = os.path.join(eval_output_dir, prefix, "eval_results.txt")`

Meanwhile, in the main() function

```result = evaluate(args, model, tokenizer, prefix=global_step)```

change into 
```
result = evaluate(args, model, tokenizer, prefix=checkpoint.split('/')[-1] if checkpoint.find('checkpoint') != -1 else "")
```
Just a little suggestion

**Comment by thomwolf** [comment]
Yes, why not, do you want to submit a PR for that?

**Comment by brian41005** [comment]
> Yes, why not, do you want to submit a PR for that?
Thanks~

By the way, is there any code formatting requirement or a contribution docs for developers?

**Comment by yuchenlin** [comment]
seems like the first checkpoint's eval results does not have a prefix?
