### ISSUE TITLE
Asking for consent to publish `_LazyModule` as a standalone PyPI package on GitHub

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#12861]
Hi,

I very much like your `_LazyModule` implementation.

https://github.com/huggingface/transformers/blob/e218249b02465ec8b6029f201f2503b9e3b61feb/src/transformers/file_utils.py#L1945

I would like to reuse it on different other projects. That is why I ask for your consent to publish it as a 
standalone PyPI package on GitHub while keeping the license. Are you ok with that?

**Comment by PhilipMay** [comment]
Tagging @LysandreJik and @sgugger

**Comment by sgugger** [comment]
Thanks for asking! You can definitely package this class in a module as long as it's on the same license as in this repo (Apache 2.0) and you are willing to maintain it.

**Comment by PhilipMay** [comment]
Here you go. A release will follow the next days:
https://github.com/telekom/lazy-imports

**Comment by PhilipMay** [comment]
Many thanks again. I will close the issue now.
