### ISSUE TITLE
New transformers.onnx CLI does not support ONNX quantization

### ISSUE THREAD

**Issue by minimaxir** [huggingface/transformers#12876]
# 🚀 Feature request

New transformers.onnx CLI introduced in 4.9.0 does not support ONNX quantization, which is a notable missing feature from the `convert_graph_to_onnx.py` script.

Semi-related: the [source quantize() function](https://github.com/microsoft/onnxruntime/blob/79097ef5535cc5ac18fc8e9010c99de08df21340/onnxruntime/python/tools/quantization/quantize.py#L56) that script leverages is depreciated so it might be a good time to switch to `quantize_dynamic()` too.

**Comment by mfuntowicz** [comment]
Hi @minimaxir, 

Thanks for reporting this.

With the new "configuration based" capabilities we are taking a very different approach from the initial `convert_graph_to_onnx.py` which was relying on heuristics to match dynamic axes and was exporting them in the wrong order quite often.

The new approach focus on a more reliable approach and on exporting only to "raw" ONNX graphs which can then be consumed by different "runtimes" not only onnxruntime. Thus we are not exposing anymore optimizations/quantizations features as part of transformers.

Still, we are currently working on another project will provide such features, leveraging the new configuration based export. It should be available in August and ONNX Runtime will be one of the first component we will provide optimizations for. 

Stay tuned 🤗

**Comment by minimaxir** [comment]
SGTM. (it's not a dealbreaker as Microsoft's approach is to create a raw ONNX and quantize it too).

Excited to see future ONNX support!

**Comment by leoozy** [comment]
@mfuntowicz Excidetd to see onnxruntime supported BART/MBART models

**Comment by sentian** [comment]
Hi @mfuntowicz, any updates on the new project? Thanks.
