### ISSUE TITLE
Feature Request: Add support for --do_train/eval/predict arguments in the TF examples script for token classification

### ISSUE THREAD

**Issue by MalteHB** [huggingface/transformers#12879]
It would be truly awesome if the TensorFlow example of token classification could mimic the capabilities of the PyTorch implementation, by providing additional argument-functionality, including `--do_train`, `--do_eval` and `--do_predict`. 

Furthermore, giving the user the opportunity to provide a custom dataset through the `--predict_file` argument.  💯 

I see that you, @Rocketknight1, are already doing some awesome work, so perhaps you know whether this will be implemented anytime soon?

https://github.com/huggingface/transformers/blob/9ff672fc4d84db3b077e03ea22e2dafbd5d99fa4/examples/tensorflow/token-classification/run_ner.py#L494-L527

**Comment by Rocketknight1** [comment]
Hi, you can use the `--train_file` and `--validation_file` arguments to pass custom data to the model! Are you specifically interested in doing predictions too?

**Comment by MalteHB** [comment]
Yes! It is the predictions I think would be awesome to have the option to do! 🥇

**Comment by Rocketknight1** [comment]
Hi, I didn't mean to let this go stale! We're planning a rewrite of our examples with the new data pipeline soon - I'll try to make sure we include the option for a `--predict_file` when that happens.
