### ISSUE TITLE
Bart Generation

### ISSUE THREAD

**Issue by Hannibal046** [huggingface/transformers#12870]
## Environment info

- `transformers` version: 4.9.0
- Platform:Linux
- Python version:3.7
- PyTorch version (GPU?):1.9.0
- Using GPU in script?:true
- Using distributed or parallel set-up in script?:false

### Who can help

@patrickvonplaten 
@patil-suraj 
@sgugger 
@patil-suraj

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts:run_summarization.py
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: summarization
* [ ] my own task or dataset: (give details below)

### Question 1
In `src/examples/pytorch/summarizations/run_summarization.py`. I choose Bart as my model.

since it uses `BartTokenzier` and `DataCollatorForSeq2Seq`. So the labels to the datacollator is `<bos> summarization <eos>` and the automatically generated `decoder_input_ids` is `<eos> <bos> summarization`, because the `decoder_start_token_id` in `bart_config` is the same as that of `<eos>` , is there any special reasons to do it ? I think the `labels` should be `summarization <eos>` and `decoder_input_ids` should be `<bos> summarization`.

### Question 2
Why `decoder_start_token_id` is the same as `<eos>` , which means all bart will use `<eos>` as its first token to start generating, isn't this against the way the bart was trained?

**Comment by patrickvonplaten** [comment]
Bart was trained to have EOS as it's start_token_id and we've noticed that forcing the first token to be BOS gives better results, see: https://github.com/huggingface/transformers/issues/3668
