### ISSUE TITLE
Possibly wrong API documentation for BigBirdTokenizerFast 

### ISSUE THREAD

**Issue by nabito** [huggingface/transformers#12873]
- `transformers` version: v.4.9.0

### Who can help

Documentation: @sgugger 

## Information

At this URL: 
https://huggingface.co/transformers/model_doc/bigbird.html#transformers.BigBirdTokenizerFast

The doc says,

`bos_token (str, optional, defaults to "[CLS]")`
and
`eos_token (str, optional, defaults to "[SEP]")`

but the actual code is:

```
    def __init__(
        self,
        vocab_file=None,
        tokenizer_file=None,
        unk_token="<unk>",
        bos_token="<s>",
        eos_token="</s>",
        pad_token="<pad>",
```
May be the API document need a fix? the explanation seems already clear though, only default value of those params are wrong.

**Comment by sgugger** [comment]
Thanks for flagging, should be fixed by the PR mentioned above!
