### ISSUE TITLE
Model card updated/deleted

### ISSUE THREAD

**Issue by tuner007** [huggingface/transformers#12875]
Hi,

I can check that the Model "tuner007/t5_abs_qa" has been removed from model hub...Is there anything i need to update ?
@patrickvonplaten  [Refer](https://huggingface.co/tuner007/t5_abs_qa/commit/faf30925ced0f25d0d5d321fb0ada04caaf5568d)

/thanks

**Comment by patrickvonplaten** [comment]
Hey @tuner007,

Thanks a lot for your issue! I'm very sorry that this has happened - this was a bug from my side :-/ I corrected it and your model should work as before now :-)

**Comment by tuner007** [comment]
> Hey @tuner007,
> 
> Thanks a lot for your issue! I'm very sorry that this has happened - this was a bug from my side :-/ I corrected it and your model should work as before now :-)

No worries ! thanks
