### ISSUE TITLE
an unexpected keyword argument 'output_signature'

### ISSUE THREAD

**Issue by grandzhang001** [huggingface/transformers#12885]
## Environment info

- `transformers` version:4.9.0
- Platform:linux
- Python version:3.6
- PyTorch version (GPU?):1.7
- Tensorflow version (GPU?):2.3,gpu version
- Using GPU in script?:k40m
- Using distributed or parallel set-up in script?:no

when I execute
python run_mlm.py 
--model_name_or_path bert-base-chinese 
--output_dir /data/bert_virtual/modelinfo/ 
--train_file /data/zxdata/000002_0.txt
from examples/tensorflow/language-modeling,this error happens

Traceback (most recent call last):
File "run_mlm.py", line 619, in <module>
main()
File "run_mlm.py", line 543, in main
tf.data.Dataset.from_generator(train_generator, output_signature=train_signature)
TypeError: from_generator() got an unexpected keyword argument 'output_signature'

**Comment by grandzhang001** [comment]
update tensorflow to 2.5 solve this.

**Comment by axiom5** [comment]
Use tf > v2.4 to solve this issue. This was in the release notes.

**Comment by Keshavraj52** [comment]
i solved this error by converting list into tuple like this
def data_generator(descriptions,images,tokenizer,max_length,vocab_size):
    while 1:
        for key,desc_list in descriptions.items():
            image =images[key][0]
            in_img,in_seq,out_word = create_sequences(tokenizer,max_length,desc_list,image,vocab_size)
            yield (in_img,in_seq), out_word
