### ISSUE TITLE
loss sudden increase

### ISSUE THREAD

**Issue by hongjianyuan** [huggingface/transformers#12882]
![image](https://user-images.githubusercontent.com/41334719/126919981-52d9f969-8a26-4fef-ac91-3528b2426942.png)
I tried this a few times

**Comment by NielsRogge** [comment]
Hi,

We like to keep Github issues for bugs/feature requests. For training related questions, please see the [forum](https://discuss.huggingface.co/). Also, make sure to make it possible for people to reproduce your issue, by providing code or a colab notebook.

Thanks!
