### ISSUE TITLE
pipeline does not load a (local) model

### ISSUE THREAD

**Issue by randomgambit** [huggingface/transformers#12902]
Hello the great `huggingface` team!

I am using a computer behind a firewall so I cannot download files from python. I am simply trying to load a sentiment-analysis pipeline so I downloaded all the files available here https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english/tree/main in a local folder (I am using tensorflow)

- config.json
- tf_model.h5
- tokenizer_config.json
- vocab.txt

However, when I tried to use this path in a `pipeline`, I get a strange error:

```
from transformers import pipeline

classifier = pipeline(task= 'sentiment-analysis', 
                      model= "C:\\Users\\me\\mymodel",
                      tokenizer = "C:\\Users\\me\\mymodel")

ValueError: unable to parse C:\Users\me\mymodel\modelcard.json as a URL or as a local path
```

Is this a bug?
Thanks!

**Comment by NielsRogge** [comment]
As the error specifies, there's a problem with the path you are providing. Make sure the path can be parsed correctly.

**Comment by randomgambit** [comment]
thanks @NielsRogge, actually I was able to make it work indirectly: first load the model on another computer, then use `save_pretrained`, transfer the save folder to the offline computer and use the path to the folder. This raises the fundamental question: can we download the files directly from the web? Thanks!

**Comment by NielsRogge** [comment]
Yes you can download them directly from the web. On the [model page](https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english), there's a button "Use in Transformers". This shows how you either load the weights from the hub into your RAM using `.from_pretrained()`, or by git cloning the files using git-lfs.

**Comment by randomgambit** [comment]
Oh I see, so instead of doing `model = pipeline(model = "to/my/path", tokenizer ="to/my/path")` I should do `model = AutoModelForSequenceClassification.from_pretrained('to/my/path")`?

**Comment by NielsRogge** [comment]
It depends on whether you want to use the pipeline, or the model right away. Both should work with the files stored locally.
