### ISSUE TITLE
ValueError: Outputs values doesn't match between reference model and ONNX exported model

### ISSUE THREAD

**Issue by leoozy** [huggingface/transformers#12903]
## Expected behavior

![image](https://user-images.githubusercontent.com/26025961/127114981-7381b15b-f871-4f26-ab4b-1ee68be12e26.png)

**Comment by leoozy** [comment]
python -m transformers.onnx --model=facebook/bart-large /home/sysadmin/downlaod/onnx_models/bart-large

Hello, the doc says bart has been supported by transformers.onnx. But this error occers while I run it.

Pytorch version: 1.9.0
transformers version: 4.9.1
platform: centos 7
python version: 3.7

**Comment by leoozy** [comment]
@mfuntowicz @LysandreJik

**Comment by rumeshmadhusanka** [comment]
I'm getting the same error for mBART. I'm using a colab notebook with/without GPU.

> Using framework PyTorch: 1.10.0+cu111
> ValueError: Outputs values doesn't match between reference model and ONNX exported model: Got max absolute difference of: 3.5762786865234375e-05

**Comment by pacowong** [comment]
You can change the `atol` as described in this [PR](https://github.com/huggingface/transformers/issues/15716).
For example
```
!python -m transformers.onnx --model=facebook/mbart-large-50 --atol=5e-5 --feature seq2seq-lm-with-past onnx/
```
