### ISSUE TITLE
saved checkpoint for best model and last model needs to be different 

### ISSUE THREAD

**Issue by jackfeinmann5** [huggingface/transformers#12915]
## Environment info

- `transformers` version: 4.8.2
- Platform: linux
- Python version: 2.7
- PyTorch version (GPU?): 1.9
- Tensorflow version (GPU?): - 
- Using GPU in script?: - 
- Using distributed or parallel set-up in script?: - 

### Who can help

- trainer: @sgugger

## Information
I am training T5 on glue, I need to save the checkpoints and then continuing the training. I checked the trainer codes.
It considers the last checkpoint as the checkpoint to load the models+optimizers from.
I am setting these options when training:

```
"save_total_limit": 1,
"load_best_model_at_end": true,
"greater_is_better": true,
"evaluation_strategy": "steps"
```
The last checkpoint belongs to the best model scoring the highest on evaluation criterion, but not the last saved model, which is not correct.

The tasks I am working on is:
*GLUE tasks

## To reproduce

1. please consider run_translation official examples and train it with adding the options mentioned above

```
python examples/pytorch/seq2seq/run_translation.py \
    --model_name_or_path t5-small \
    --do_train \
    --do_eval \
    --source_lang en \
    --target_lang ro \
    --source_prefix "translate English to Romanian: " \
    --dataset_name wmt16 \
    --dataset_config_name ro-en \
    --output_dir /tmp/tst-translation \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --overwrite_output_dir \
    --predict_with_generate \ 
```

and please add these options
```
"save_total_limit": 1,
"load_best_model_at_end": true,
"greater_is_better": true,
"evaluation_strategy": "steps"
```

## Expected behavior
the trainer needs to load the last checkpoint in a separate folder to load from it, but keep the checkpoint for the best model separaletely

many thanks.

**Comment by sgugger** [comment]
As you can see [here](https://github.com/huggingface/transformers/blob/d3c3e722d69627d6334d7ef8faaced7df3103174/src/transformers/trainer.py#L1982) we have special code to deal with that situation exactly, and I just checked locally and always have two checkpoints (the best model and the oldest) with `save_total_limit=1` in conjunction with `load_best_model_at_end=True`.

This was introduced 2 months ago so before the release of v4.8.2, you should therefore not have any problem.

**Comment by jackfeinmann5** [comment]
thank you so much for the response.
