### ISSUE TITLE
Feature request: Show command line argument defaults

### ISSUE THREAD

**Issue by mbforbes** [huggingface/transformers#12924]
# 🚀 Feature request

When running with `--help`, show the default values for command line arguments.

## Motivation

There are dozens of command line arguments. When I'm trying to figure out how to run a script, I often want to know what value is being used when I don't specify it. But running with `--help` doesn't show the default values unless it's explicitly written in the description (which is only for three of them for the example script I'm using).

For example, `--evaluation_strategy`

```
  --evaluation_strategy {no,steps,epoch}
                        The evaluation strategy to use.
```

This ends up being a bit of a frustrating user experience. The two ways I currently use to find the value are:

1. Run the script again without `--help` and log all the arguments (done in the examples). This shows the assigned value, which will be the default if not passed. However, it doesn't show the description of what it does.

2. Go to the documentation. This will show the default value and a more thorough description, but requires opening a web browser and Googling to find the right page.

In other Python projects, I use the `argparse.ArgumentDefaultsHelpFormatter`, which automatically displays default values in the `--help` message along with their descriptions.

```python
parser = argparse.ArgumentParser(
    formatter_class=argparse.ArgumentDefaultsHelpFormatter
)
```

I wonder whether the Huggingface arguments could support the same feature?

Many thanks for considering this!

**Comment by sgugger** [comment]
This is a very reasonable request and thanks for suggesting an easy way to do it! I added that in the PR linked above.

**Comment by mbforbes** [comment]
Wow, thank you so much for the support and quick turnaround, I really appreciate it!! 🎉
