### ISSUE TITLE
LEDForSequenceClassification and LEDForQuestionAnswering example codes don't work.

### ISSUE THREAD

**Issue by jacklxc** [huggingface/transformers#12921]
## Environment info
Tried on both transformers=4.2.0 and the latest transformer package.

### Who can help
@patrickvonplaten

Models:

LED

## Information

LEDForSequenceClassification and LEDForQuestionAnswering example code doesn't work. Please fix these bugs. LEDForConditionalGeneration works though. [here](https://huggingface.co/transformers/model_doc/led.html#ledforsequenceclassification)

The example [notebook](https://colab.research.google.com/drive/12LjJazBl7Gam0XBPy_y0CTOJZeZ34c2v?usp=sharing) only works for transformers=4.2.0. Specifically, there will be an error of in-place operation during the training. It will be helpful if you can update the code to adapt to the latest packages.

**Comment by patrickvonplaten** [comment]
Actually we should probs just remove those examples since there is no fine-tuned model anyways...@jacklxc would you like to make a PR? :-)
