### ISSUE TITLE
GPT2 Layers

### ISSUE THREAD

**Issue by MarcM0** [huggingface/transformers#12922]
When the trainer API is used to finetune gpt-2, does it finetune all the layers or just some? Is there a way to control which layers it finetunes? 
gpt2: @patrickvonplaten, @LysandreJik

**Comment by sgugger** [comment]
It finetunes all the layers. You can set the `require_grads` attribute of the model layers you don't want to train to `False` before sending the model to the `Trainer` if you want to change that behavior.

**Comment by MarcM0** [comment]
thank you!
