### ISSUE TITLE
Error when trying `push_to_hub` for a fine-tuned model on Colab

### ISSUE THREAD

**Issue by phosseini** [huggingface/transformers#12932]
## Environment info

- `transformers` version: 4.9.1
- Platform: Colab

### Who can help
@sgugger

## To reproduce

Steps to reproduce the behavior. This is the code I'm running:

I first install the following packages:

```
! pip install transformers datasets
! sudo apt-get install git-lfs
```

Then I run the `! transformers-cli login` and successfully login and my token is saved at: `/root/.huggingface/token`

Then I run the following code:

```
from transformers import AutoModel

model = AutoModel.from_pretrained('/path/to/my/fine-tuned/model/on/my/google/drive')

model.push_to_hub("my-username/my-model-name")

```

Per @sgugger's suggestion, I also tried the following line but I'm getting the very error:

`model.push_to_hub("my-model-name")`

And this is the error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-84aee0bf13c0> in <module>()
      4 model = AutoModel.from_pretrained(model_path)
      5 
----> 6 model.push_to_hub("my-username/my-model-name")

2 frames
/usr/local/lib/python3.7/dist-packages/huggingface_hub/repository.py in __init__(self, local_dir, clone_from, use_auth_token, git_user, git_email)
    102                 )
    103                 raise ValueError(
--> 104                     "If not specifying `clone_from`, you need to pass Repository a valid git clone."
    105                 )
    106 

ValueError: If not specifying `clone_from`, you need to pass Repository a valid git clone.
```

## Expected behavior
To have my fine-tuned model uploaded to my private repo on Huggingface.

**Comment by sgugger** [comment]
Just tried on a fresh colab and could upload a model without any problem (as long as there is no "/" in the model ID). Do you already have a model with the same username maybe?

Note that you are missing the step `! git config --global user.email "your_email"` in the preparation.

Are you certain you do have the latest version of Transformers installed?

**Comment by phosseini** [comment]
Thanks for the tips. Problem solved. I think it was because I created a repo and a model with the very name on the Hugging Face website (I thought there should already be a model with the name there if we want to push the model.) I removed the model with the same name and now it works!
