### ISSUE TITLE
How to fuse copy mechnism into the GenerationMixin？

### ISSUE THREAD

**Issue by Hannibal046** [huggingface/transformers#12931]
Hello， is there any way to directly fuse copy mechanism into beamsearch? since the beam_search function receive model_output.logit rather than probabily of vocab?
https://github.com/huggingface/transformers/blob/72aee83ced5f31302c5e331d896412737287f976/src/transformers/generation_utils.py#L1801

**Comment by LysandreJik** [comment]
Pinging @patrickvonplaten and @patil-suraj

**Comment by patrickvonplaten** [comment]
Hey @Hannibal046,

Could you clarify a bit what you mean by "copy-mechanism" ?
Maybe a code example of what you want to do?

**Comment by Hannibal046** [comment]
Hello,I also find others to talk about the `copy mechanism`. in this [link](https://discuss.huggingface.co/t/copying-mechanism-for-transformer/5025)
BTW,could you please check my another issue about BART Generation? It confused me a long time, https://github.com/huggingface/transformers/issues/12870,  thanks so much.
