### ISSUE TITLE
cannot import name 'XLNetForMultipleChoice' but python can import

### ISSUE THREAD

**Issue by yyHaker** [huggingface/transformers#1293]
## 🐛 Bug

Model I am using (Bert):

Language I am using the model on (English):

when I use the following command to run run_multiple_choice.py, like:
'''
python examples/run_multiple_choice.py --model_type bert --task_name race --model_name_or_path bert_large --do_train --do_eval --do_lower_case --data_dir $RACE_DIR --learning_rate 5e-5 --num_train_epochs 3 --max_seq_length 80 --output_dir models_bert/race_base --per_gpu_eval_batch_size=16 --per_gpu_train_batch_size=16 --gradient_accumulation_steps 2 --overwrite_output
'''
it gives the error information:
![image](https://user-images.githubusercontent.com/18585628/65219953-479b2e00-daec-11e9-9ecf-fd85bc8e5e34.png)
but when I in my python environment to import the package , it has no problem!
![image](https://user-images.githubusercontent.com/18585628/65220000-626da280-daec-11e9-935b-4cd951474b39.png)
what's wrong with the run_multiple_choice.py?
## Environment

* OS:
* Python version: 3.6.2
* PyTorch version: 1.1.0
* PyTorch Transformers version (or branch): 1.2.0
* Using GPU ? yes
* Distributed of parallel setup ? 
* Any other relevant information:

**Comment by yyHaker** [comment]
we found maybe the current code is not consistent with the pip package pytorch_transformers, so when use the pip package it does't work, but when just run the code without the pip package, it can work, but you need change some path to make the code work correctly!

**Comment by LysandreJik** [comment]
Hi, I believe this was fixed with @VictorSanh's commit ae50ad9
