### ISSUE TITLE
Starting today, I get an error downloading pre-trained models

### ISSUE THREAD

**Issue by jason-weddington** [huggingface/transformers#12940]
## Environment info
Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 2.1.1
- Platform: Linux-5.8.0-63-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.9.0+cu111 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

## Information

Model I am using (Bert, XLNet ...):

roberta-base, but this is currently an issue with all models

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
- downloading pre-trained models is currently failing, this seems have have started just in the last day

## To reproduce

1. attempt to load any pre-trained model from HuggingFace (code below)

This code:

`generator = pipeline("text-generation", model="bert-base-uncased")`

Generates this error:

403 Client Error: Forbidden for url: https://huggingface.co/bert-base-uncased/resolve/main/config.json
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)

...

OSError: Can't load config for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-uncased' is the correct path to a directory containing a config.json file

## Expected behavior

I expect the pre-trained model to be downloaded. This issue just started today.

**Comment by julien-c** [comment]
Hi @jason-weddington, are you calling those URLs from any particular workload or infrastructure?

The only reason I can see where you would get a 403 on this URL is if your usage triggers our infra's firewall. Would you mind contacting us at `expert-acceleration at huggingface.co` so we can take a look?

**Comment by jason-weddington** [comment]
Thanks, I'll email you. I'm running this in a notebook on my desktop, using my home internet connection, but we're also seeing this in Google Colab. The issue just stated today.

**Comment by jason-weddington** [comment]
This is working again, thanks for the help.
