### ISSUE TITLE
OSError: Can't load config for 'bert-base-uncased

### ISSUE THREAD

**Issue by WinMinTun** [huggingface/transformers#12941]
## Environment info
It happens in local machine, Colab, and my colleagues also.

- `transformers` version:
- Platform: Window, Colab
- Python version: 3.7
- PyTorch version (GPU?): 1.8.1 (GPU yes)
- Tensorflow version (GPU?):
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help
@LysandreJik It is to do with 'bert-base-uncased'

## Information
Hi, I m having this error suddenly this afternoon. It was all okay before for days. It happens in local machine, Colab and also to my colleagues. I can access this file in browser https://huggingface.co/bert-base-uncased/resolve/main/config.json no problem. Btw, I m from Singapore. Any urgent help will be appreciated because I m rushing some project and stuck there.

Thanks

![image](https://user-images.githubusercontent.com/22287008/127519960-114ef793-03f6-494e-ab10-7700b693b87d.png)

403 Client Error: Forbidden for url: https://huggingface.co/bert-base-uncased/resolve/main/config.json
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    505                 use_auth_token=use_auth_token,
--> 506                 user_agent=user_agent,
    507             )

6 frames
HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/bert-base-uncased/resolve/main/config.json
During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    516                 f"- or '{pretrained_model_name_or_path}' is the correct path to a directory containing a {CONFIG_NAME} file\n\n"
    517             )
--> 518             raise EnvironmentError(msg)
    519 
    520         except json.JSONDecodeError:

OSError: Can't load config for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-uncased' is the correct path to a directory containing a config.json file

**Comment by sgugger** [comment]
Was it just a fluke or is the issue still happening? On Colab I have no problem downloading that model.

**Comment by WinMinTun** [comment]
@sgugger Hi it is still happening now. Not just me, many people I know of. I can access the config file from browser, but not through the code. Thanks

**Comment by WinMinTun** [comment]
Still not okay online, but I managed to do it locally

git clone https://huggingface.co/bert-base-uncased

#model = AutoModelWithHeads.from_pretrained("bert-base-uncased")
model = AutoModelWithHeads.from_pretrained(BERT_LOCAL_PATH, local_files_only=True)

#tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
tokenizer = AutoTokenizer.from_pretrained(BERT_LOCAL_PATH, local_files_only=True)

adapter_name = model2.load_adapter(localpath, config=config, model_name=BERT_LOCAL_PATH)

**Comment by julien-c** [comment]
This, like #12940, is probably related to a change we've made on the infra side (cc @n1t0), which we'll partially revert. Please let us know if this still occurs.

**Comment by n1t0** [comment]
@WinMinTun Could you share a small collab that reproduces the bug? I'd like to have a look at it.

**Comment by jason-weddington** [comment]
With additional testing, I've found that this issue only occurs with adapter-tranformers, the AdapterHub.ml modified version of the transformers module. With the HuggingFace module, we can pull pretrained weights without issue.

Using adapter-transformers this is now working again from Google Colab, but is still failing locally and from servers running in AWS. Interestingly, with adapter-transformers I get a 403 even if I try to load a nonexistent model (e.g. fake-model-that-should-fail). I would expect this to fail with a 401, as there is no corresponding config.json on huggingface.co. The fact that it fails with a 403 seems to indicate that something in front of the web host is rejecting the request before the web host has a change to respond with a not found error.

**Comment by julien-c** [comment]
Thanks so much @jason-weddington. This will help us pinpoint the issue. (@n1t0 @Pierrci)

**Comment by luis-at-navteca** [comment]
I have the same problem, but it only happens when the model is private.

![Screenshot](https://user-images.githubusercontent.com/53347273/129016843-01d11fa8-40b0-4155-9405-75dcccfd5a0c.png)

**Comment by sgugger** [comment]
Your token for `use_auth_token` is not the same as your API token. The easiest way to get it is to login with `!huggingface-cli login` and then just pass `use_auth_token=True`.

**Comment by luis-at-navteca** [comment]
I think the problem is something else:

![Screenshot 2021-08-11 at 14 34 44](https://user-images.githubusercontent.com/53347273/129029925-a5c4c43d-2f1d-442b-8da0-09d19d2d58a4.png)

**Comment by bennimmo** [comment]
Yes, I have come across this as well. I have tracked it down to this line

https://github.com/huggingface/transformers/blob/143738214cb83e471f3a43652617c8881370342c/src/transformers/pipelines/__init__.py#L422

It's because the `use_auth_token` has not been set up early enough in the model_kwargs. The line referenced above needs to be moved above instantiate config section.

**Comment by bennimmo** [comment]
I've added a pull request to which I think will fix this issue.

**Comment by hemangjoshi37a** [comment]
Still getting the same error 
Here is my code : 
```
from transformers import AutoModelForTokenClassification, AutoTokenizer
model = AutoModelForTokenClassification.from_pretrained("hemangjoshi37a/autotrain-ratnakar_600_sample_test-1427753567", use_auth_token=True)
tokenizer = AutoTokenizer.from_pretrained("hemangjoshi37a/autotrain-ratnakar_600_sample_test-1427753567", use_auth_token=True)
inputs = tokenizer("I love AutoTrain", return_tensors="pt")
outputs = model(**inputs)
```
Error :
```
----> 3 model = AutoModelForTokenClassification.from_pretrained("hemangjoshi37a/autotrain-ratnakar_600_sample_test-1427753567", use_auth_token=True)
OSError: Can't load config for 'hemangjoshi37a/autotrain-ratnakar_600_sample_test-1427753567'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'hemangjoshi37a/autotrain-ratnakar_600_sample_test-1427753567' is the correct path to a directory containing a config.json file
```
https://hjlabs.in

**Comment by hemangjoshi37a** [comment]
runnign this command and authenticating it solved issue: `huggingface-cli login`
https://hjlabs.in

**Comment by PaskalSunari** [comment]
I am facing the same problem in Kaggle too... How can I
![Capture](https://user-images.githubusercontent.com/60564521/196048189-292c7bf0-848e-4904-8fd2-65df37f8308b.JPG)
 resolve this issue ?

**Comment by lyk0013** [comment]
Hello, I had the same problem when using transformers - pipeline in the aws-sagemaker notebook.

I started to think it was the version or the network problem. But, after some local tests,  this guess is wrong. So,  I just debug the source code.  I find that:
![image](https://user-images.githubusercontent.com/42571564/212821105-b55fed97-d916-4edc-8918-1cfa5aea18f2.png)
This will raise any error as EnviromentError. So, from experience, I solve it, by running this pip:
!pip install --upgrade jupyter
!pip install --upgrade ipywidgets

You guys can try it!

**Comment by VRDJ** [comment]
![image](https://user-images.githubusercontent.com/117170100/217241740-9d66735a-3bf9-40b4-be96-f9d83e908035.png)


I am unable to solve this issues Since Morning .. i had been trying to Solve it ... 

Im working on my Final Year Project .. can someone pls help me in it ...

**Comment by hemangjoshi37a** [comment]
Just ask chatGPT LOL...😂😂

**Comment by VRDJ** [comment]
I dont understand it ?? What do u mean

**Comment by hemangjoshi37a** [comment]
@VRDJ  goto this website [chatGPT](chat.openai.com) and enter your error in the chatbox in this website and for the 99% you will get your solution there.

**Comment by DuanXiaoyue-LittleMoon** [comment]
> Still not okay online, but I managed to do it locally
> 
> git clone https://huggingface.co/bert-base-uncased
> 
> #model = AutoModelWithHeads.from_pretrained("bert-base-uncased") model = AutoModelWithHeads.from_pretrained(BERT_LOCAL_PATH, local_files_only=True)
> 
> #tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased") tokenizer = AutoTokenizer.from_pretrained(BERT_LOCAL_PATH, local_files_only=True)
> 
> adapter_name = model2.load_adapter(localpath, config=config, model_name=BERT_LOCAL_PATH)
-------------------

Hello! Thanks for your sharing. I wonder in 
'tokenizer = AutoTokenizer.from_pretrained(BERT_LOCAL_PATH, local_files_only=True)', 
which file does 'BERT_LOCAL_PATH' refer to specifically? Is it the path for the directory 'bert-base-uncased', or the 'pytorch_model.bin', or something else?

**Comment by fedral** [comment]
> Just ask chatGPT LOL...😂😂

I solved this error by downloading files from 'bert-base-uncased‘ repo：  https://huggingface.co/google-bert/bert-base-uncased/tree/main
