### ISSUE TITLE
ImportError: cannot import name 'BigBirdTokenizer' from 'transformers'

### ISSUE THREAD

**Issue by zynos** [huggingface/transformers#12946]
## Environment info

- `transformers` version: 4.9.1
- Platform: windows
- Python version: 3.9
- PyTorch version (GPU?): 1.9 (CPU)
- Tensorflow version (GPU?):
- Using GPU in script?: no
- Using distributed or parallel set-up in script?:

## Information

Model I am using BigBird:

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```

from transformers import BigBirdTokenizer,BigBirdModel

print("hello")

```

## Expected behavior

No import error.
Importing **BigBirdTokenizerFast** works without a problem.

**Comment by zynos** [comment]
Closing because this was a project specific bug. (4.9.1 succesfully imports BigBirdTokenizer in another project)

**Comment by zynos** [comment]
The sentencepiece library was missing.

**Comment by sgugger** [comment]
`BigBirdTokenizer` requires a sentencepiece installation, but you should have had that error instead of an import error. This is because the `BigBirdTokenizer` was misplaced in the init, the PR linked above fixes it.

**Comment by zynos** [comment]
I sadly only got the import error, nothing else. An error indicating that sentencepiece is missing is definately more helpful. Thanks for creating the PR

**Comment by TobyCello** [comment]
Hi @zynos @sgugger . I'm using transformers 4.8.0 and have installed sentencepiece. But I'm having same cannot import name 'BigBirdTokenizer' issue. Thanks.

**Comment by sgugger** [comment]
Make sure you use the latest version of Transformers. It should include a clearer error message if the import fails.
