### ISSUE TITLE
Wav2Vec2 WER remains 1.00 and return blank transcriptions.

### ISSUE THREAD

**Issue by theainerd** [huggingface/transformers#12956]
## Environment info

- `transformers` version: transformers==4.4.0
- Platform: 
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help

@patrickvonplaten  @patil-suraj 

## Information
Wav2Vec2 WER remains 1.00 no matter which dataset we use and also can see the same behaviour across multiple datasets. 
Returns blank transcriptions when making predictions.

## To reproduce
 

1. Run the following colab notebook : https://colab.research.google.com/github/patrickvonplaten/notebooks/blob/master/Fine_tuning_Wav2Vec2_for_English_ASR.ipynb

**Comment by theainerd** [comment]
![Screenshot from 2021-07-30 22-54-23](https://user-images.githubusercontent.com/15798640/127691113-ce47674c-1617-4d5f-ba3a-ced72ff68ed5.png)

**Comment by cceyda** [comment]
I see you are using transformers==4.4.0
there seems to be some updates to [wav2vec2 model ](https://github.com/huggingface/transformers/tree/master/src/transformers/models/wav2vec2) after that so maybe try with the latest release or pull from master

**Comment by patrickvonplaten** [comment]
In case someone stumbles upon this issue while using a version between 4.9.0 and master: https://github.com/huggingface/transformers/pull/13512
