### ISSUE TITLE
huggingface-hub version conflict

### ISSUE THREAD

**Issue by CraigMiloRogers** [huggingface/transformers#12959]
`transformers` requires `huggingface-hub==0.0.12` in `setup.py` in the `master` branch. 

`huggingface-hub` has just released version `0.0.15`. 

Other projects that use `huggingface-hub`, such as `https://github.com/UKPLab/sentence-transformers`, are happy with the latest version of `huggingface-hub`.

Depending upon the order of installation, a version conflict may result.  Here's a sample message from our project, `kgtk`, which requires both `transformers` and `sentence-transformers`:

```pkg_resources.ContextualVersionConflict: (huggingface-hub 0.0.15 (/opt/anaconda3/envs/kgtk-env/lib/python3.8/site-packages/huggingface_hub-0.0.15-py3.8.egg), Requirement.parse('huggingface-hub==0.0.12'), {'transformers'})```

**Comment by sgugger** [comment]
This is discussed in #12961
