### ISSUE TITLE
Using `model.sample()` and increasing the `max_length` leads to CUDA OOM crash

### ISSUE THREAD

**Issue by moinedgylabs** [huggingface/transformers#12964]
## Environment info

- `transformers` version: 4.6.0.dev0
- Platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.11
- PyTorch version (GPU?): 1.9.0+cu102 (True)
- Tensorflow version (GPU?): 2.5.0 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help

I think @patrickvonplaten and @LysandreJik

## Information

Model I am using GPT-NEO:

The problem arises when using:
* my own modified scripts: Simply using `.sample()` method with `GPTNeoForCausalLM`

The tasks I am working on is:

* my own task: Simple Text generation.

## To reproduce

1. Visit this colab and run GPU runtime: https://colab.research.google.com/drive/1VjVUrptwgUx3TxdlcVqPNwXyX6YJYSAK
2. Execute Runtime -> Run All
3. Note the `nvidia-smi` output.
4. In the last cell, increase the `max_length` from 30 to 350. And run again.
4. Even if the crash doesn't occur, check `nvidia-smi` again.

## Expected behavior

To not consume that much GPU memory. It is understood that some tasks may take some memory, but using **~10 GB** for an increase of 300 tokens is... something wrong.

**Comment by patrickvonplaten** [comment]
Related to https://github.com/huggingface/transformers/issues/11320

Cc @patil-suraj
