### ISSUE TITLE
Documentation: Dataset to Model interface examples

### ISSUE THREAD

**Issue by iandanforth-alation** [huggingface/transformers#12979]
# 🚀 Feature request

Add explicit examples to the custom dataset docs which use fully realized key-value pairs and link to the forward methods of the relevant models to emphasize the contract between Dataset `__getitem__()` output and model `forward()`.

## Motivation

This issue arises when you consider the interaction of Datasets and Models. They may be independently well documented but when trying to use them together there are gaps.

Example:

You want to fine tune T5 using `Trainer` using a custom `Dataset`.

The minimal API for T5 a user needs to be aware of in this scenario is small but not well documented in the context of custom datasets. The `Dataset` must return an object in this format from it's `__getitem__()` method.

```
        return {
            'input_ids': input_ids, 
            'attention_mask': attention_mask, 
            'labels': labels,
        }
```

Those three keys are then passed by `Trainer` to T5 via its forward method. Arguably those parameters are the most important first interface you need to know about to train T5 (inside or outside of `Trainer`). 

This *is* documented in the T5 docs, however the key disconnect is that in the custom dataset docs none of the examples use explicit, fully realized set of key-value pairs. Also the docs don't emphasize that those return values *must match* the expected inputs to a model's `forward()` method.

## Your contribution

I can add these if this get's a few thumbs up.

**Comment by sgugger** [comment]
The custom dataset doc page is outdated and will be rewritten soon, you should use the [examples scripts](https://github.com/huggingface/transformers/tree/master/examples) or [example notebooks](https://huggingface.co/transformers/notebooks.html) as a base to fine-tune models.
