### ISSUE TITLE
`Trainer.train(resume_from_checkpoint=False)` is causing an exception

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#12970]
Since `resume_from_checkpoint` can be `str` and `bool` it should be possible to pass `False` to it.
But when `resume_from_checkpoint` is `False` it causes an exception here:

https://github.com/huggingface/transformers/blob/3d4b3bc3fd77e0e48e2364464ea90379f13bcf37/src/transformers/trainer.py#L1049-L1050

```text
E       TypeError: expected str, bytes or os.PathLike object, not bool
```

The most simple solution would be to do this at the beginning of the `train` function:

```python
resume_from_checkpoint = None if not resume_from_checkpoint else resume_from_checkpoint
```

If wanted I can provide a PR.

**Comment by sgugger** [comment]
That seems like the right fix indeed. Please go ahead with a PR, thanks! :-)
