### ISSUE TITLE
pylint error when using `transformers.AutoModelForSequenceClassification.from_pretrained(path)`

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#12986]
I am using transformers 4.9.1 from PyPI.
When using pylint on `transformers.AutoModelForSequenceClassification.from_pretrained(path)` I am getting this error:
`my_scipt.py:277:11: E1120: No value for argument 'pretrained_model_name_or_path' in unbound method call (no-value-for-parameter)`

It I change it to
`transformers.AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path=path)`

I am getting

`script.py:277:11: E1120: No value for argument 'cls' in unbound method call (no-value-for-parameter)`

Could you maybe fix this?

**Comment by sgugger** [comment]
This may be linked to the missing `classmethod` decorators that were fixed in #12927, could you try on a source install?

**Comment by PhilipMay** [comment]
> This may be linked to the missing `classmethod` decorators that were fixed in #12927, could you try on a source install?

I made a source install and then I am getting no pylint error anymore.
So this is fixed in the main branch. Closing this.

Thanks!
