### ISSUE TITLE
Fine-Tune Wav2Vec2 for English ASR with 🤗 Transformers, loading fine-tune models from local isn't working

### ISSUE THREAD

**Issue by Azitt** [huggingface/transformers#12982]
![image](https://user-images.githubusercontent.com/32965166/127952279-3c20a4e8-2f79-49e8-b77f-6ca0f4e03664.png)

## Environment info

- `transformers` version: Wav2Vec2
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by sgugger** [comment]
Are you sure you saved your tokenizer in that folder with `tokenizer.save_pretrained`? What files are in this folder?

**Comment by Azitt** [comment]
No, I didn't. I'm following this notebook https://huggingface.co/blog/fine-tune-wav2vec2-english  it doesn't say save tokenizer. I have these files in my folder. 
![image](https://user-images.githubusercontent.com/32965166/128017137-31769e79-1f26-4047-9f8d-700915fc5ed7.png)

**Comment by sgugger** [comment]
Sorry, I meant the `processor`, not the `tokenizer`. You should save it if you want to be able to reload it with `from_pretrained`, or use the initial model to load the processor, since it's unlikely to have changed during your fine-tuning.

**Comment by Azitt** [comment]
somehow saving the processor doesn't add  tokenzier_config.json and special_tokens_map.json to the folder. I saved the tokenizer in the same folder, everything is working now. thank you for your support.
