### ISSUE TITLE
How is Bert fine-tuned on STS-B task?

### ISSUE THREAD

**Issue by PosoSAgapo** [huggingface/transformers#12991]
Hi, I am new to NLP and trying to reproduce fine-tune results of Bert. However, the STST-B task troubles me, from what I understand, the STST-B task is a regression task, but Bert treats it as a classification task. I do not quite know the transformation between scores and label in detail, is anybody willing to give me a hint?

**Comment by sgugger** [comment]
Please ask those questions on the [forums](https://discuss.huggingface.co/). We keep the issues for bugs and feature requests only.

**Comment by PosoSAgapo** [comment]
> Please ask those questions on the [forums](https://discuss.huggingface.co/). We keep the issues for bugs and feature requests only.

Thank you for your reply, I will post it on the forums
