### ISSUE TITLE
how to user class_weight in transformers.trainer

### ISSUE THREAD

**Issue by wangdong1992** [huggingface/transformers#12997]
In tensorflow，I can use class_weight for unbalanced data. Now, I want to train the model  through  transformers.trainer，how to use class_weight in transformers.trainer, This is an introduction to it
1.https://huggingface.co/transformers/custom_datasets.html#fine-tuning-with-trainer
2.https://huggingface.co/transformers/main_classes/trainer.html#transformers.TFTrainer
Please take a look at this question. Thank you

**Comment by NielsRogge** [comment]
For training related questions, refer to our [forum](https://discuss.huggingface.co). We like to keep Github issues for bugs/feature requests.

[This post](https://discuss.huggingface.co/t/how-can-i-use-class-weights-when-training/1067) for example will probably answer your question.

Therefore closing this issue.
