### ISSUE TITLE
Problem saving tf wav2vec in savedmodel format

### ISSUE THREAD

**Issue by ahmedlone127** [huggingface/transformers#13009]
![image](https://user-images.githubusercontent.com/66001253/128309653-9939e715-2792-419c-b310-0a18fb92194d.png)
this is my code

**Comment by patrickvonplaten** [comment]
Hey @ahmed451 - could you please add a code snippet to reproduce the error instead of a screenshot? Thanks!

**Comment by ahmedlone127** [comment]
sure

 `from transformers import TFWav2Vec2ForCTC
model= TFWav2Vec2ForCTC.from_pretrained('patrickvonplaten/wav2vec2-base-timit-demo',from_pt = True)
model.save_pretrained("/content/test",saved_model = True)`

**Comment by patrickvonplaten** [comment]
I've run your code snippet in the following environment:

```
- `transformers` version: 4.10.0.dev0
- Platform: Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.5
- Tensorflow version (GPU?): 2.3.0 (False)
```


and to me it looks like this is a problem coming from Tensorflow directly. I.E. the error output is:

```
UnimplementedError: The Conv2D op currently does not support grouped convolutions on the CPU. A grouped convolution was attempted to be run because the input depth of 768 does not match the filter input depth of 48 [Op:Conv2D]
```

Also gently pinging @will-rice here in case he has seen something like this before :-)

**Comment by will-rice** [comment]
This is/was a TensorFlow limitation, but according to [this](https://github.com/tensorflow/tensorflow/issues/29005) `2.6` may have solved it. First I would try upgrading to `2.6` or the latest nightly. Another option could be the [workaround](https://github.com/tensorflow/tensorflow/issues/40044) for this problem in TFLite. I will say the workaround is slower though.

**Comment by ahmedlone127** [comment]
@patrickvonplaten  How do I install the transformers 4.10.0 version?

**Comment by patrickvonplaten** [comment]
It's current master :-) So `!pip install git+https://github.com/huggingface/transformers.git@master` should do
