### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'save_strategy'

### ISSUE THREAD

**Issue by jmasom** [huggingface/transformers#13021]
### Environment
- `transformers` version: 4.2.2
- Platform: Linux-4.15.0-151-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.4.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: Not explicitly (but probably)
- Using distributed or parallel set-up in script?: Not explicitly (but probably)

### Who can help
@sgugger

### Details
I am using RoBERTa for seq classification, but that is not where my issue is coming from. My issue is coming from the Trainer API. Specifically, when I try to specify save_strategy=epoch in TrainingArguments, I get the error message in the issue title. I tried updating to a more recent version of Transformers as per another issue, but that didn't work. I'm not sure what to do about it.

**Comment by sgugger** [comment]
You probably did not properly install it. The environment above shows 4.2.2 and `save_strategy` was introduced later on.
You can check the version of Transformers executed by your script by adding
```
import transformers
print(transformers.__version__)
```
at the top of it.
