### ISSUE TITLE
Get multiple results from Hugging face pipeline library

### ISSUE THREAD

**Issue by BatMrE** [huggingface/transformers#13027]
I am using simple transformers library to get auto suggested text for my question based on a context .
It give me a single suggestion, is there any possible way to get multiple results for the same.
    
    text2text_generator = pipeline("text2text-generation")
    text2text_generator("question: What is ? context: 42 is the answer to life, the universe and everything")

The "text2text-generation" model uses T5 model on its backend.

I tried something like:

```
from transformers import T5Tokenizer, T5Model
tokenizer = T5Tokenizer.from_pretrained('t5-small')

model = T5ForConditionalGeneration.from_pretrained('t5-small')
input_ids = tokenizer("question: What is ? context:42 is the answer to life, the universe and everything", return_tensors="pt").input_ids  # Batch size 1

outputs = model.generate(input_ids,do_sample=True, top_k=5)
tokenizer.decode(outputs[0])
```

nothing works.!

**Comment by LysandreJik** [comment]
Hello! The `Text2TextGenerationPipeline` accepts any keyword arguments to be handled by the `generate` method that does the generation under the hood. You can check the input signature of that method here to see what arguments it accepts: [generate](https://huggingface.co/transformers/main_classes/model.html#transformers.generation_utils.GenerationMixin.generate)

Namely, it accepts the `do_sample` argument. You can try it out:

```py
>>> from transformers import pipeline
>>> text2text_generator = pipeline("text2text-generation")

>>> text2text_generator("question: What is ? context: 42 is the answer to life, the universe and everything", do_sample=True, min_length=15)
[{'generated_text': '42 also is the answer to life, the universe and everything but the universe'}]

>>> text2text_generator("question: What is ? context: 42 is the answer to life, the universe and everything", do_sample=True, min_length=15)
[{'generated_text': '42 is the answer to life, the universe and everything but the universe'}]

>>> text2text_generator("question: What is ? context: 42 is the answer to life, the universe and everything", do_sample=True, min_length=15)
[{'generated_text': 'The answer to life, the universe and everything to everybody. 42 is the answer'}]
```

**Comment by BatMrE** [comment]
Great, that adds a lot of value to output. Thanks @LysandreJik

**Comment by enze5088** [comment]
Can I get multiple results in a single generation?
I think it may be a bug for the  num_return_sequences just take effect in 

`
model_outputs = self.forward(model_inputs, **forward_params)
`

but in 

`
outputs = self.postprocess(model_outputs, **postprocess_params)
`

the decode always return one result

`
    record = {
        f"{self.return_name}_text": self.tokenizer.decode(
            model_outputs["output_ids"][0],
            skip_special_tokens=True,
            clean_up_tokenization_spaces=clean_up_tokenization_spaces,
        )
    }
`
