### ISSUE TITLE
Do the Trainer docs need an update?

### ISSUE THREAD

**Issue by UrosOgrizovic** [huggingface/transformers#13036]
On [this](https://huggingface.co/transformers/main_classes/trainer.html) documentation page regarding `Trainer`, `torch.utils.data.dataset.Dataset` is mentioned. However, I can only seem to find `torch.utils.data.Dataset` [here](https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset). Do the docs require an update?

The same goes for `IterableDataset`, on the same page.

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
Sure, would you mind making a PR with that?
