### ISSUE TITLE
Spanish NER bad extraction

### ISSUE THREAD

**Issue by diego6662** [huggingface/transformers#13037]
## Environment info

- `transformers` version: 4.9.1
- Platform: linux-ubuntu 20.04.2 LTS x86_64
- Python version: 3.7.6
- PyTorch version (GPU?): No
- Tensorflow version (GPU?): No
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Details
I used this hugginface model for NER extraction https://huggingface.co/mrm8488/bert-spanish-cased-finetuned-ner 
Input: "Efrain Avella"
Expected output :  {
    "entity_group": "PER",
    "score": 0.9992852807044983,
    "word": "Efrain Avella",
    "start": 0,
    "end": 12
  }
Transformers output: {
    "entity_group": "PER",
    "score": 0.9990411400794983,
    "word": "E",
    "start": 0,
    "end": 1
  },
  {
    "entity_group": "PER",
    "score": 0.8103020787239075,
    "word": "##frain Avella",
    "start": 1,
    "end": 13
  }

**Comment by LysandreJik** [comment]
Hello! Did you try with the `aggregation_strategy` parameter as mentioned in the [docs](https://huggingface.co/transformers/main_classes/pipelines.html#tokenclassificationpipeline)?

**Comment by diego6662** [comment]
No, I used grouped_entities but I saw that it is deprecated, thanks, I will try it with the aggregation_strategy
