### ISSUE TITLE
How do i pre-train Bert_mlm model [Discussion]

### ISSUE THREAD

**Issue by mosh98** [huggingface/transformers#13047]
Hi, 
i've been able to pre train a Bert model using the run_mlm.py file. Thanks to huggingface team ofc. :D

I do have one question tho, if i want to further pre train a bert_mlm model, do i use the same pre training script such as run_mlm.py for the mlm model. Is that the "correct" way or is there another type of training script i should use.

Any help is much appreciated

**Comment by mosh98** [comment]
@NielsRogge 
@sgugger 

Any thoughts?

Kind regards,
Mosleh

**Comment by sgugger** [comment]
Hi there! Please use the [forums](https://discuss.huggingface.co/) for questions like this, as we keep the issues for bugs and feature requests only.

As for your question, you can fine-tune any existing model with that `run_mlm` script.

**Comment by mosh98** [comment]
Hi,

Alright thanks, i'll post in forums next time.

/Mosleh
