### ISSUE TITLE
MLM example not able to run_mlm_flax.py

### ISSUE THREAD

**Issue by R4ZZ3** [huggingface/transformers#13044]
I am going through this mlm exaxmple on Google TPU VM instance v3-8 https://github.com/huggingface/transformers/tree/master/examples/flax/language-modeling

I have defined MODEL_DIR with:
export MODEL_DIR="./norwegian-roberta-base"

I have defined symbolic link with:
ln -s home/Admin/Research/transformers/examples/flax/language-modeling/run_mlm_flax.py norwegian-roberta-base/run_mlm_flax.py

I am running with remove VS code and am able to run first 2 steps. now at run_mlm_flax_py if I run referring to symbolic link I am getting:
![image](https://user-images.githubusercontent.com/25264037/128644570-b7b04397-2077-4420-9f25-8e9277473939.png)

If I run directly the original script I am getting: 
![image](https://user-images.githubusercontent.com/25264037/128644580-68089b5c-d50a-4a90-8501-5b4945ada394.png)

![image](https://user-images.githubusercontent.com/25264037/128644591-fd843934-a67f-4714-b47e-5847404ac4a9.png)

Do you have some idea what I have done wrong?

**Comment by patrickvonplaten** [comment]
Hey @R4ZZ3,

Can you run:

```transformers-cli env```

And post the output here?

**Comment by R4ZZ3** [comment]
Sure, I will run it late this evening and post output here (UTC +3)

**Comment by R4ZZ3** [comment]
Ok, found time in between the day @patrickvonplaten 

- `transformers` version: 4.3.3
- Platform: Linux-5.4.0-1043-gcp-x86_64-with-debian-bullseye-sid
- Python version: 3.7.11
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: To my knowledge this script should only use TPUs
- Using distributed or parallel set-up in script?: To my knowledge processing is spread out to 8 tpu cores

**Comment by R4ZZ3** [comment]
I did pull changes. Tokenizer saving gives error (Doing this from norwegian-roberta-base folder)

![image](https://user-images.githubusercontent.com/25264037/128717682-4484f027-2598-4ff5-848d-ecfe4c43ea51.png)


tokenizer.save(./tokenizer.json) works

**Comment by R4ZZ3** [comment]
I was able to fix symbolic link issue with by giving full paths but still have the same error with. Also FYI installed Pytorch 1.9 as I remember from Flax event that for some things it was necessary to have for some processing but no change to error
![image](https://user-images.githubusercontent.com/25264037/128721317-330a80c4-d9c1-46f9-9ca2-794ab76f4726.png)

**Comment by patrickvonplaten** [comment]
Hey @R4ZZ3,

Could you please update your transformer version to a newer one? Ideally master for Flax examples as they have been added very recently?

**Comment by R4ZZ3** [comment]
Sure thing, ill try

**Comment by R4ZZ3** [comment]
Ok, now seems to move further @patrickvonplaten Thanks!
Still had to save tokenizer with tokenizer.save(./tokenizer.json) though

![image](https://user-images.githubusercontent.com/25264037/128925529-ced5f775-e9a4-43dc-bc0e-58085de28386.png)
