### ISSUE TITLE
max_len_single_sentence should be max_len - 2 for RoBERTa

### ISSUE THREAD

**Issue by kaushaltrivedi** [huggingface/transformers#1304]
## 🐛 Bug

Model I am using (Bert, XLNet....): RoBERTa

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [ ] the official example scripts: (give details) run_lm_finetuning
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details) . Language model finetuning

## To Reproduce

1. 
2.
3.

## Expected behavior

While using language model finetuning for roberta-base, I got an error cublas runtime error : resource allocation failed at /pytorch/aten/src/THC/THCGeneral.cpp:216.

When I checked the tokenized dataset, I observed that it had 514 tokens, i.e. 512 coming from max_len_single_sentence plus 2 special tokens.  RoBERTa tokenizer should have max_len_single_sentence set to 510 just like the one in BERT.  

max_len_single_sentence = max_len - 2

## Environment

* OS: Ubuntu
* Python version: 3.7
* PyTorch version: 1.2.0
* PyTorch Transformers version (or branch): Master
* Using GPU ? Yes
* Distributed of parallel setup ? No
* Any other relevant information: 

## Additional context

R

**Comment by julien-c** [comment]
I think you may be right and we've been meaning to fix this. cf recent discussion @LysandreJik @VictorSanh

**Comment by kaushaltrivedi** [comment]
thanks. Adding LM fine-tuning to fast-bert.  Have added a workaround for now :)

**Comment by julien-c** [comment]
Also see https://github.com/pytorch/fairseq/issues/1187
