### ISSUE TITLE
RAG: building my own dataset

### ISSUE THREAD

**Issue by Arij-Aladel** [huggingface/transformers#13059]
@shamanez Hello! My question is about building our own dataset to train RAG from scratch. It was mentioned [here](https://github.com/huggingface/transformers/tree/master/examples/research_projects/rag#finetuning) that we can build our dataset to finetune the model, but the links do not open. Could you please provide us with the steps and examples?

**Comment by shamanez** [comment]
Check this script.

https://www.github.com/huggingface/transformers/tree/master/examples%2Fresearch_projects%2Frag%2Fuse_own_knowledge_dataset.py
