### ISSUE TITLE
Can not instantiate `PreTrainedTokenizerFast` from instantiated tokenizer object

### ISSUE THREAD

**Issue by brand17** [huggingface/transformers#13068]
## Environment info

- `transformers` version: 4.3.2
- Platform: Windows
- Python version: 3.6.6
- PyTorch version (GPU?): N/A
- Tensorflow version (GPU?): 2.3.0
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@LysandreJik

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Run the following script:

```
from tokenizers import Tokenizer
tok = Tokenizer(BPE(unk_token="[UNK]"))
trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"])
tok.pre_tokenizer = Whitespace()
def it():
  for t in ['one', 'two', 'three']:
    yield t

tok.train_from_iterator(it(), trainer)
from transformers import PreTrainedTokenizerFast
tok = PreTrainedTokenizerFast(tokenizer_object=tok)

```

I am getting error:

> Exception has occurred: ValueError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
> Couldn't instantiate the backend tokenizer from one of: (1) a `tokenizers` library serialization file, (2) a slow tokenizer instance to convert or (3) an equivalent slow tokenizer class to instantiate and convert. You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
> 

I have sentencepiece installed (0.1.91).

## Expected behavior

No error

**Comment by LysandreJik** [comment]
The ability to load a tokenizer object directly was introduced in version v4.5.x! Could you upgrade your `transformers` version to a more recent one?
