### ISSUE TITLE
Cannot import name 'BEiTForImageClassification' from 'transformers' 

### ISSUE THREAD

**Issue by dnnxl** [huggingface/transformers#13062]
## Environment info

Hi trying to run the BEiTForImageClassification in Google Colab and got the following error Cannot import name 'BEiTForImageClassification' from 'transformers'. Any suggestion on how to fix it?

- `transformers` version: 4.9.2
- Platform: Google Colab

Models:
- nielsr/beit-base-patch16-224

## To reproduce

Based on https://huggingface.co/nielsr/beit-base-patch16-224.
1. Run and using the following code
` ` ` 
from transformers import AutoTokenizer, BEiTForImageClassification  
tokenizer = AutoTokenizer.from_pretrained("nielsr/beit-base-patch16-224")
model = BEiTForImageClassification.from_pretrained("nielsr/beit-base-patch16-224")
` ` ` 

## Expected behavior

An error "Cannot import name 'BEiTForImageClassification' from 'transformers' "

**Comment by aycatakmaz** [comment]
I have encountered the same problem, and solved it by re-installing `transformers` from the source via the following command:
`pip install git+https://github.com/huggingface/transformers` (for further details please see https://huggingface.co/transformers/installation.html). Installing from the source resulted in a transformers version of 4.10.0, and I could import Beit models.

Another thing that caught my attention is that in your code sample is a little typo that might also be causing a problem, the module to be imported is written as `BEiTForImageClassification`, however it is supposed to be `BeitForImageClassification`.

**Comment by dnnxl** [comment]
Thanks it solves the problem. Also for the clarification.
