### ISSUE TITLE
Which model is best to used for language model rescoring for ASR

### ISSUE THREAD

**Issue by LearnedVector** [huggingface/transformers#1306]
## ❓ Questions & Help

Hello all, I am wanting to use this library to rescore an output from an automatic speech recognition model. Still learning a lot about language model so out of curiosity for anyone who's tried, which model has given you the best performance? Looking to a language model that can predict score the probability of a sentence most effectively.

**Comment by nshmyrev** [comment]
Same as https://github.com/google-research/bert/issues/35

**Comment by nshmyrev** [comment]
And https://github.com/huggingface/transformers/issues/37

**Comment by oplatek** [comment]
GPT2 can be used for rescoring https://arxiv.org/pdf/1910.11450.pdf

**Comment by simonepri** [comment]
[I tested](https://github.com/simonepri/lm-scorer/blob/master/tests/models/test_gpt2.py#L52-L239) GPT2  on different english error types (I used the one defined in the [ERRANT framework](https://www.aclweb.org/anthology/P17-1074/)) and it seems that is able to give a lower probability to the wrong version of a sentence (At least for simple examples).
