### ISSUE TITLE
t5 base not found.

### ISSUE THREAD

**Issue by s4sarath** [huggingface/transformers#13073]
- 't5-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 't5-base' is the correct path to a directory containing a config.json file

**Comment by patrickvonplaten** [comment]
Hey @s4sarath,

https://huggingface.co/t5-base looks normal to me - what exactly is your error?

**Comment by s4sarath** [comment]
Hi @patrickvonplaten , t5-small is working fine. Transformers version is **4.9.0.dev0**

```
from transformers import TFT5Model
model = TFT5Model.from_pretrained("t5-base")
```

OSError: file t5-base/config.json not found
OSError: Can't load config for 't5-base'. Make sure that:

- 't5-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 't5-base' is the correct path to a directory containing a config.json file

**Comment by LysandreJik** [comment]
Do you have a folder called `t5-base` in your working directory? The `TFT5Model` may be trying to load from that directory rather than from the hub.

**Comment by s4sarath** [comment]
Hi Lysandre. You were true. My bad.
Closing this ticket.

Thanks for your help.
