### ISSUE TITLE
Planned support for new Grover 1.5B models?

### ISSUE THREAD

**Issue by GenTxt** [huggingface/transformers#1308]
Thanks for the great repo.

Just wondering if there's any planned support for the new Grover 1.5B models?

https://github.com/rowanz/grover (original 1.5B now available via download_model.py)

https://github.com/vanyacohen/opengpt2-1.5B-gpu-inference (slightly different variation)

Cheers

**Comment by julien-c** [comment]
No short-term plan to implement this ourselves, but we'd welcome a PR (especially one involving the original authors for validation).
