### ISSUE TITLE
can"t connect ther online datasets.the issue:ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/1.7.0/datasets/glue/glue.py

### ISSUE THREAD

**Issue by jinec** [huggingface/transformers#13089]
## Environment info

- `transformers` version:4.6.1
- Platform:
- Python version:3.6
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by NielsRogge** [comment]
Hi,

Can you create a Colab/code example to reproduce the issue?
