### ISSUE TITLE
 AttributeError: module 'sacrebleu' has no attribute 'DEFAULT_TOKENIZER'  in translation.ipynb notebook

### ISSUE THREAD

**Issue by Azitt** [huggingface/transformers#13093]
I'm trying to use translation.ipynb notebook. I'm getting below error:

![image](https://user-images.githubusercontent.com/32965166/129086137-d5a1daca-ad95-4e8f-98a5-01f1618de791.png)

## Environment info

- `transformers` version: 4.9.2
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by LysandreJik** [comment]
Hello! A new release of sacrebleu was released with breaking changes. Could you reinstall sacrebleu on version 1.5.1 to see if it runs? cc @sgugger

**Comment by Azitt** [comment]
installing version 1.5.1 solves the problem. thanks!

**Comment by nauxuoh00** [comment]
I used 1.5.1 but faild
