### ISSUE TITLE
RoBERTa : add_special_tokens=True

### ISSUE THREAD

**Issue by HongyanJiao** [huggingface/transformers#1311]
I set add_special_tokens=True
but I still get:
A sequence with no special tokens has been passed to the RoBERTa model. This model requires special tokens in order to work. Please specify add_special_tokens=True in your encoding.

**Comment by josecannete** [comment]
I'm getting the same warning, also here: https://github.com/huggingface/pytorch-transformers/issues/1318

**Comment by Oxi84** [comment]
I think you should add <s> before and after sentences.
