### ISSUE TITLE
type object 'AutoModelForSequenceClassification' has no attribute 'from_config'

### ISSUE THREAD

**Issue by Sujeeth-Shetty** [huggingface/transformers#13125]
I'm using Transformer version 4.4.2 and have been getting "type object 'AutoModelForSequenceClassification' has no attribute 'from_config'" error. Here is my code snippet. I went through the document, the syntax seem to be correct. Your help is very much appreciated. 

from transformers import AutoConfig, AutoTokenizer, AutoModel, AutoModelForSequenceClassification, Trainer, TrainingArguments

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
config = AutoConfig.from_pretrained('distilbert-base-uncased', num_labels=2)

**Comment by LysandreJik** [comment]
Hello! I just tried the following code snippet in both `v4.9.2` and `v4.4.2` and both seem to work:

```py
from transformers import AutoConfig, AutoTokenizer, AutoModel, AutoModelForSequenceClassification, Trainer, TrainingArguments

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
config = AutoConfig.from_pretrained('distilbert-base-uncased', num_labels=2)

AutoModelForSequenceClassification.from_config(config)
```
