### ISSUE TITLE
AutoModel KeyError: 'layoutlmv2'

### ISSUE THREAD

**Issue by nurgel** [huggingface/transformers#13121]
## Environment info
- `transformers` version: 4.9.2
- Platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.11
- PyTorch version (GPU?): 1.9.0+cu102 (False)
- Tensorflow version (GPU?): 2.5.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

## Information

I am trying to run layoutlmv2. When I run the code from documentation:

```
from transformers import AutoTokenizer, AutoModel
  
tokenizer = AutoTokenizer.from_pretrained("microsoft/layoutlmv2-base-uncased")
```

I get the below error:

> KeyError                                  Traceback (most recent call last)
> <ipython-input-7-457d9de7bf01> in <module>()
>       1 from transformers import AutoTokenizer, AutoModel
>       2 
> ----> 3 tokenizer = AutoTokenizer.from_pretrained("microsoft/layoutlmv2-base-uncased")
>       4 
>       5 model = AutoModel.from_pretrained("microsoft/layoutlmv2-base-uncased")
> 
> /usr/local/lib/python3.7/dist-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
>     532         if config_tokenizer_class is None:
>     533             if not isinstance(config, PretrainedConfig):
> --> 534                 config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
>     535             config_tokenizer_class = config.tokenizer_class
>     536 
> 
> /usr/local/lib/python3.7/dist-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
>     450         config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
>     451         if "model_type" in config_dict:
> --> 452             config_class = CONFIG_MAPPING[config_dict["model_type"]]
>     453             return config_class.from_dict(config_dict, **kwargs)
>     454         else:
> 
> KeyError: 'layoutlmv2'

**Comment by nurgel** [comment]
@NielsRogge

**Comment by LysandreJik** [comment]
Hello @nurgel! LayoutLM v2 is not merged yet so it isn't available in the latest version. You can follow the development here https://github.com/huggingface/transformers/pull/12604
