### ISSUE TITLE
RobertaTokenizerFast object has no attribute '_convert_token_to_id'

### ISSUE THREAD

**Issue by demongolem-biz** [huggingface/transformers#13169]
## Environment info

- `transformers` version: 4.9
- Platform: Linux
- Python version: 3.6
- Tensorflow version (GPU?): 2.5
- Using GPU in script?: No

### Who can help

The example given by the maintainers of LM-BFF supposedly runs successfully, at least with what they claim is version 3.4 or higher of transformers.  However, upon my inspection of source code of transformers, I see that _convert_token_to_id is not associated with fast tokenizers only with standard tokenizers.  For example, if I view transformers.tokenization_gpt2 (Roberta tokenizer being built on gpt2)  for v 3.4.0, I see _convert_token_to_id present and implemented.  However, if I go to transformers.tokenization_gpt2_fast, it is not there.  Is this a bug, is this something that was removed at some point, or are we simply not able to access _convert_token_to_id when using a Fast tokenizer?

**Comment by patrickvonplaten** [comment]
Hey @demongolem-biz,

Could you maybe post a short, reproducible code snippet that showcases the problem? Also note that `_convert_token_to_id` is a private method and that the corresponding public method `convert_token_to_id` is the one to be checked.

**Comment by demongolem-biz** [comment]
The code is not mine, I am trying to use someone else's but here is the __init__ function from the beginning to the point when _convert_token_to_id is used.  I know tokenizer is being passed in, but runtime the error message claims the tokenizer object is a RobertaTokenizerFast.

`   def __init__(self, args, tokenizer, cache_dir=None, mode="train", use_demo=False):
        self.args = args
        self.task_name = args.task_name
        self.processor = processors_mapping[args.task_name]
        self.tokenizer = tokenizer
        self.mode = mode

        # If not using demonstrations, use use_demo=True
        self.use_demo = use_demo
        if self.use_demo:
            logger.info("Use demonstrations")
        assert mode in ["train", "dev", "test"]

        # Get label list and (for prompt) label word list
        self.label_list = self.processor.get_labels()
        self.num_labels = len(self.label_list)
        if args.prompt:
            assert args.mapping is not None
            self.label_to_word = eval(args.mapping)

            for key in self.label_to_word:
                # For RoBERTa/BART/T5, tokenization also considers space, so we use space+word as label words.
                if self.label_to_word[key][0] not in ['<', '[', '.', ',']:
                    # Make sure space+word is in the vocabulary
                    assert len(tokenizer.tokenize(' ' + self.label_to_word[key])) == 1
                    self.label_to_word[key] = tokenizer._convert_token_to_id(tokenizer.tokenize(' ' + self.label_to_word[key])[0])
                else:
                    self.label_to_word[key] = tokenizer._convert_token_to_id(self.label_to_word[key])
                logger.info("Label {} to word {} ({})".format(key, tokenizer._convert_id_to_token(self.label_to_word[key]), self.label_to_word[key]))
           

`
