### ISSUE TITLE
 Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [huggingface/transformers#13165]
Hello,I found a performance issue in the definition of `convert_dataset_for_tensorflow` ,
examples/tensorflow/text-classification/run_glue.py,
[tf_dataset = tf_dataset.batch(batch_size=batch_size, drop_remainder=drop_remainder).map](https://github.com/huggingface/transformers/blob/439a43b6b403205eeda2d62645fc16c93627d30d/examples/tensorflow/text-classification/run_glue.py#L83) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

The same issues also exist in [tf_dataset.batch(batch_size=batch_size, drop_remainder=drop_remainder).map](https://github.com/huggingface/transformers/blob/439a43b6b403205eeda2d62645fc16c93627d30d/examples/tensorflow/text-classification/run_text_classification.py#L98) ,
[.map(densify_ragged_batch)](https://github.com/huggingface/transformers/blob/439a43b6b403205eeda2d62645fc16c93627d30d/examples/tensorflow/multiple-choice/run_swag.py#L109) and [tf_dataset.batch(batch_size=batch_size, drop_remainder=drop_remainder).map](https://github.com/huggingface/transformers/blob/439a43b6b403205eeda2d62645fc16c93627d30d/examples/tensorflow/question-answering/run_qa.py#L253)

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by Rocketknight1** [comment]
Hi @DLPerf, thanks for the warning! We're actually in the process of refactoring our Datasets to automatically support conversion to TF Datasets, at which point I'll be removing this part of our examples and replacing it with a call to the conversion method.

However, if you have any insights for how we can improve the performance of our conversion methods there, that would be very helpful! You can review the code at https://github.com/huggingface/datasets/pull/2731 and leave suggestions as comments on that PR.
