### ISSUE TITLE
Missing weight in pretrained model `pegasus-xsum`

### ISSUE THREAD

**Issue by Linyxus** [huggingface/transformers#13164]
## Environment info

- `transformers` version: 4.9.2
- Platform: Linux
- Python version: 3.9.6
- PyTorch version (GPU?): 1.9.0 with GPU
- Tensorflow version (GPU?):
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help

@patrickvonplaten

## Information

I am using the PegasusForConditionalGeneration model. I found that the pretrained weight `google/pegasus-xsum` hosted by HuggingFace does not have the weight `lm_head.weight` defined here: https://github.com/huggingface/transformers/blob/master/src/transformers/models/pegasus/modeling_pegasus.py#L1210.

## To reproduce

1. Download the `google/pegasus-xsum` weight from HuggingFace.
2. Load it use `torch.load`.
3. List its keys, no `lm_head.weight` is contained!

## Expected behavior

We should have the `lm_head` weights, because the weight file actually contains the bias `final_logits_bias` defined here: https://github.com/huggingface/transformers/blob/master/src/transformers/models/pegasus/modeling_pegasus.py#L1209. And the pretrained model name `google/pegasus-xsum` suggests that it is finetuned on the XSum dataset (which is a ConditionalGeneration task), so the weight for `lm_head` should be contained to make the finetuned model complete!

**Comment by NielsRogge** [comment]
I just tested this. Colab notebook here: https://colab.research.google.com/drive/1oCrC3Tb07C7V1l-0Fx6_c8xdEbyqx9Km?usp=sharing

It works fine for me, `lm_head` is included.

**Comment by Linyxus** [comment]
A lot of thanks for your reply! :^)

I just figured out that the `lm_head.weight` actually maps the internal embeddings back to word predictions, whose weights will be tied to the input word embeddings! So the lm_head's weight will definitely not be included in the pretrained weight file. I did not realize this due to my lack of knowledge about NLP models :^(. Thanks again for your time!
