### ISSUE TITLE
No module named: Regex while importing GPT2Tokenizer

### ISSUE THREAD

**Issue by akalieren** [huggingface/transformers#13172]
## Environment info

- `transformers` version: 4.9.0
- Platform: Linux
- Python version: 3.6.13
- PyTorch version (GPU?):  1.9.0
- Tensorflow version (GPU?):  2.6.0
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

## Information

Model I am using (Bert, XLNet ...): GPT2 Tokenizer

The problem arises when using:
* [ X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

I am still confused about this error but it is very simple to reproduce:

```
from transformers import GPT2Tokenizer
tokenizer = GPT2.from_pretrained('gpt2')
```

The problem is occurred due to this line: https://github.com/huggingface/transformers/blob/1fec32adc6a4840123d5ec5ff5cf419c02342b5a/src/transformers/models/bertweet/tokenization_bertweet.py#L25

Is it about my python version? Normally regex imported as `re`, but can't understand why it is happened!

Thanks.

## Expected behavior
Able to initialize GPT2

**Comment by qqaatw** [comment]
I can run the following code on Colab without any error:

```
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
```

Tested python version: 3.7.1, transformers version: v4.9.0 and v4.9.2.

**Comment by akalieren** [comment]
Thats true, it should work. Probably problem is environmental but the case that the line I added raise an error since it should be `re`.  e.g: [this one](https://github.com/huggingface/transformers/blob/1c06240e1b3477728129bb58e7b6c7734bb5074e/examples/research_projects/seq2seq-distillation/sentence_splitter.py#L1)

**Comment by qqaatw** [comment]
@akalieren The `regex` package should not be the problem as it is automatically installed with transformers. The reason why it used `regex` instead of `re` can be found at the following comment in that file. 

https://github.com/huggingface/transformers/blob/1fec32adc6a4840123d5ec5ff5cf419c02342b5a/src/transformers/models/bertweet/tokenization_bertweet.py#L461

However, I think using `GPT2Tokenizer` should not be linked to `Bertweet` since they are not dependent to each other. Did you add additional code to use them together?

**Comment by akalieren** [comment]
I deleted environment and created again. It is working now as it is expected. I jumped [this issue](https://github.com/conda-forge/conda-forge.github.io/issues/1161) from the link you sent. I guess the problem is about conda environment. 

Probably it is called from [`__init__.py`](https://github.com/huggingface/transformers/blob/1fec32adc6a4840123d5ec5ff5cf419c02342b5a/src/transformers/models/__init__.py#L19)
