### ISSUE TITLE
how to finetune based huggingface: run_glue.py

### ISSUE THREAD

**Issue by lbda1** [huggingface/transformers#13178]
python transformers-master/examples/pytorch/text-classification/run_glue.py \
  --model_name_or_path chinese_bert-base \
  --train_file=transformers-master/dataset/class/train.csv \
  --validation_file=transformers-master/dataset/class/dev.csv \
  --do_train \
  --do_eval \
  --max_seq_length 128 \
  --per_device_train_batch_size 32 \
  --learning_rate 2e-5 \
  --num_train_epochs 3 \
  --output_dir output

When I use run_glue.py, and train.csv/dev.csv data format has two columns which contain “sentence” and “label”.
But It reports an error "pandas.errors. ParserError: Error tokenizing data. C error: Expected 1 fields in line 10, saw 2".
What is reason of this error?  It is the data format error?

**Comment by NielsRogge** [comment]
Can you provide a Colab notebook to reproduce your issue?

**Comment by lbda1** [comment]
what is the format of the classification data which used in run_glue.py?

**Comment by NielsRogge** [comment]
The [README](https://github.com/huggingface/transformers/tree/master/examples/pytorch/text-classification) mentions that "your own data in a csv or a JSON file (the script might need some tweaks in that case, refer to the comments inside for help)". Looking at the comments, it says:

    # Get the datasets: you can either provide your own CSV/JSON training and evaluation files (see below)
    # or specify a GLUE benchmark task (the dataset will be downloaded automatically from the datasets Hub).
    #
    # For CSV/JSON files, this script will use as labels the column called 'label' and as pair of sentences the
    # sentences in columns called 'sentence1' and 'sentence2' if such column exists or the first two columns not named
    # label if at least two columns are provided.
    #
    # If the CSVs/JSONs contain only one non-label column, the script does single sentence classification on this
    # single column. You can easily tweak this behavior (see below)
