### ISSUE TITLE
BertTokenizer provides wrong encode function for Japanese BERT

### ISSUE THREAD

**Issue by khaimaitien** [huggingface/transformers#1317]
## 🐛 Bug

Model I am using (Bert, XLNet....): BertTokenizer 

Language I am using the model on (English, Chinese....): Japanese

I tried to load the tokenizer for Bert from pretrained [Bert for Japanese](http://nlp.ist.i.kyoto-u.ac.jp/index.php?BERT%E6%97%A5%E6%9C%AC%E8%AA%9EPretrained%E3%83%A2%E3%83%87%E3%83%AB). The tokenizer recognize "が" the same as "か"　although both appears in vocab file. Here is example code:

```
from pytorch_transformers import BertTokenizer 
tokenizer = BertTokenizer.from_pretrained('vocab.txt')
token_ids = tokenizer.encode('が')
print('token_ids: ', token_ids)
print(tokenizer.decode(token_ids))

token_ids = tokenizer.encode('か')
print('token_ids: ', token_ids)
print(tokenizer.decode(token_ids))
```
the result:
```
token_ids:  [90]
か
token_ids: [90]
か
```
The vocab.txt file can be downloaded from [here](https://drive.google.com/open?id=1f3k9GcyqEIjjFo8EgqqaOQmiSXxT1hqF): 
I also found that BertTokenizer also mis-recognized: 'て' and 'で', 'ば' and 'は'

**Comment by khaimaitien** [comment]
I had discovered that this phenomenon is due to function: _run_strip_accents(token) in class: BasicTokenizer. Perhaps, the authors should give an option to choose whether to remove accents or not because in some language such as Japanese, removing accents makes a new word

**Comment by tomohideshibata** [comment]
Hi, I have trained this Japanese BERT model, and made it public.
Please set `do_lower_case` option to false so that the function `_run_strip_accents` is disabled.
