### ISSUE TITLE
[Docs] Function signatures on website not correctly reflecting current code.

### ISSUE THREAD

**Issue by qqaatw** [huggingface/transformers#13171]
## Environment info

Tested v4.9.2 and master.

### Who can help

@sgugger 

## Information

In [Trainer docs](https://huggingface.co/transformers/main_classes/trainer.html#transformers.Trainer), the first argument `model` in the function signature should be 

`model: Union[transformers.modeling_utils.PreTrainedModel, torch.nn.modules.module.Module] = None` as defined in the [code](https://github.com/huggingface/transformers/blob/1fec32adc6a4840123d5ec5ff5cf419c02342b5a/src/transformers/trainer.py#L267). 

But it currently shows

`model: torch.nn.modules.module.Module = None`, which seems to be outdated, however.

I've tested building the docs on my system, and the resulting html is correct.

**Comment by patrickvonplaten** [comment]
Would you like to open a PR to correct it @qqaatw ? :-)

**Comment by qqaatw** [comment]
@patrickvonplaten I could try, but the problem seems to be related to the CI/CD since function signatures are automatically generated by Sphinx, and the problem didn't occur on the docs I built manually on my machine. (Tested ubuntu 18.04 with python 3.6 / windows 10 with python 3.8)

**Comment by qqaatw** [comment]
Closed as the PR has been merged.
