### ISSUE TITLE
[Documentation] PLEASE HELP with very simple tasks!!!

### ISSUE THREAD

**Issue by alev61** [huggingface/transformers#13190]
Hello hugginface team,.

First of all, I wanted to report a bug I am getting in Google Colab.

When I do:

from transformers import AutoTokenizer, AutoModel

```
tokenizer = AutoTokenizer.from_pretrained('allenai/scibert_scivocab_uncased')
input_ids = tokenizer('I enjoy walking with my cute dog', return_tensors='pt').input_ids
model = AutoModel.from_pretrained('allenai/scibert_scivocab_uncased')
model.eval()
model.generate(input_ids)
```

I get:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-85c40f45fd28> in <module>()
      1 input_ids = tokenizer('I enjoy walking with my cute dog', return_tensors='pt').input_ids
----> 2 model.generate(input_ids=input_ids)

2 frames
/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     26         def decorate_context(*args, **kwargs):
     27             with self.__class__():
---> 28                 return func(*args, **kwargs)
     29         return cast(F, decorate_context)
     30 

/usr/local/lib/python3.7/dist-packages/transformers/generation_utils.py in generate(self, input_ids, max_length, min_length, do_sample, early_stopping, num_beams, temperature, top_k, top_p, repetition_penalty, bad_words_ids, bos_token_id, pad_token_id, eos_token_id, length_penalty, no_repeat_ngram_size, encoder_no_repeat_ngram_size, num_return_sequences, max_time, max_new_tokens, decoder_start_token_id, use_cache, num_beam_groups, diversity_penalty, prefix_allowed_tokens_fn, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, forced_bos_token_id, forced_eos_token_id, remove_invalid_values, synced_gpus, **model_kwargs)
    996                 return_dict_in_generate=return_dict_in_generate,
    997                 synced_gpus=synced_gpus,
--> 998                 **model_kwargs,
    999             )
   1000 

/usr/local/lib/python3.7/dist-packages/transformers/generation_utils.py in greedy_search(self, input_ids, logits_processor, stopping_criteria, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   1301                 continue  # don't waste resources running the code we don't need
   1302 
-> 1303             next_token_logits = outputs.logits[:, -1, :]
   1304 
   1305             # Store scores, attentions and hidden_states when required

AttributeError: 'BaseModelOutputWithPoolingAndCrossAttentions' object has no attribute 'logits'
```
===========================================================================

Secondly, I am reporting to you another very serious issue IMHO that needs to be addressed ASAP!!! 

THERE ARE NO CLEAR AND SIMPLE EXAMPLES ON HOW TO USE HUGGINFACE models/software ANYWHERE !!!!

WTF??? I do not mean to be rude but this is ridiculous and insulting. I have wasted hours going through your docs, w/o ANY success. Everything is either absolutely unclear or does not work properly.

WHAT I PERSONALLY NEED:

GOOGLE COLABS that show in a few lines of code how to train Huggingface models from scratch (NOT A SINGLE EXAMPLE ANYWHERE). And also most of your examples and colabs are either incomplete/not working or very specific so they can't be used elsewhere!!!

====================================================================

I would really appreciate it if you would address all of these issues ASAP because otherwise, I will not be able to use Huggingface transformers nor would I recommend it to anyone.

Thank you very much for listening to my criticism. I do not mean to chastise, only to help make huggingface better! :)

Alex.

**Comment by patrickvonplaten** [comment]
Hey Alex,

I'm sorry that you didn't manage to find what you were looking for in the docs.

1) Please not that "bert-like" models should not be used for sequence generation, but rather for sequence classification. The model "`allenai/scibert_scivocab_uncased`" is essentially a `bert-base-uncased` model you can checkout [here](https://huggingface.co/bert-base-uncased) where you can see some examples. Only seq2seq and lm-head models should make use of `generate`. This doc might help you for more explanation: https://huggingface.co/transformers/model_summary.html

2) Re: Examples:
- We try to have at least one example for every model architecture which you can find under the model pages in the docs, *e.g.* here for BERT: https://huggingface.co/transformers/model_doc/bert.html#bertforsequenceclassification
- Also we have a couple of "Quickstart" sections on how to use our models here: https://huggingface.co/transformers/training.html which you can open as a Google Colab (there is a button on the top right)
- There is also the Hugging Face course which dives a bit deeper into how everything works here: https://huggingface.co/course/chapter1
