### ISSUE TITLE
Training DetrForObjectDetection failed in a multiple-GPU environment.

### ISSUE THREAD

**Issue by jnishi** [huggingface/transformers#13197]
## Environment info

- `transformers` version: 4.9.2
- Platform: Linux-5.4.0-80-generic-x86_64-with-glibc2.27
- Python version: 3.8.0
- PyTorch version (GPU?): 1.9.0+cu111 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <yes>
- Using distributed or parallel set-up in script?: <yes>

### Who can help
@NielsRogge

## Information

Model I am using (Bert, XLNet ...): DetrForObjectDetection

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Save this script as `run.py` It is the same as https://colab.research.google.com/drive/1oIHGwr1U0sw-6KW-MG60s-ksXA-kYyUO?usp=sharing#scrollTo=VCr7Y7zW5a2a
2. Put sample.json, sample.jpg, sample2.jpg in [detr_samples.tar.gz](https://github.com/huggingface/transformers/files/7019224/detr_samples.tar.gz)  to the same directory.

```python
from typing import Any, Dict, List, Union
from dataclasses import dataclass
import torch
from torchvision.datasets import CocoDetection

from transformers import (
    DetrConfig,
    DetrFeatureExtractor,
    DetrForObjectDetection,
    HfArgumentParser,
    Trainer,
    TrainingArguments,
)

class DetrTrainer(Trainer):
  # Overwrite _prepare_inputs method to make sure dict is also placed on device
  def _prepare_inputs(self, inputs: Dict[str, Union[torch.Tensor, Any]]) -> Dict[str, Union[torch.Tensor, Any]]:
        """
        Prepare :obj:`inputs` before feeding them to the model, converting them to tensors if they are not already and
        handling potential state.
        """
        for k, v in inputs.items():
            if isinstance(v, torch.Tensor):
                kwargs = dict(device=self.args.device)
                if self.deepspeed and inputs[k].dtype != torch.int64:
                    # NLP models inputs are int64 and those get adjusted to the right dtype of the
                    # embedding. Other models such as wav2vec2's inputs are already float and thus
                    # may need special handling to match the dtypes of the model
                    kwargs.update(dict(dtype=self.args.hf_deepspeed_config.dtype()))

                inputs[k] = v.to(**kwargs)
            # labels are a list of dictionaries, each dictionary being a COCO annotation
            if isinstance(v, list):
              for annotation_dict in v:
                  for key, value in annotation_dict.items():
                    annotation_dict[key] = value.to(self.args.device)

        if self.args.past_index >= 0 and self._past is not None:
            inputs["mems"] = self._past

        return inputs


def load_category(category):
    id2label = {}
    label2id = {}
    maxid = 0
    for k, v in category.items():
        id2label[int(k)] = v["name"]
        label2id[v["name"]] = int(k)
        maxid = max(maxid, int(k))
    for i in range(maxid):
        if not (i in id2label):
            id2label[i] = None
    return id2label, label2id


class DetrData(CocoDetection):
    def __init__(self, img_folder, annotations, feature_extractor, train=True):
        super(DetrData, self).__init__(img_folder, annotations)
        self.feature_extractor = feature_extractor

    def __getitem__(self, idx):
      # read in PIL image and target in COCO format
      img, target = super(DetrData, self).__getitem__(idx)

      # preprocess image and target (converting target to DETR format, resizing + normalization of both image and target)
      image_id = self.ids[idx]
      target = {'image_id': image_id, 'annotations': target}
      encoding = self.feature_extractor(images=img, annotations=target, return_tensors="pt")
      encoding["pixel_values"] = encoding["pixel_values"].squeeze() # remove batch dimension
      encoding["labels"] = encoding["labels"][0] # remove batch dimension
      return encoding

@dataclass
class DataCollatorDetr:

    feature_extractor: DetrFeatureExtractor

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        pixel_values = [item["pixel_values"] for item in features]
        encoding = self.feature_extractor.pad_and_create_pixel_mask(pixel_values, return_tensors="pt")
        encoding["labels"] = [item["labels"] for item in features]
        return encoding


def main():
    training_args = TrainingArguments(output_dir=".")
    feature_extractor = DetrFeatureExtractor()
    train_dataset = DetrData(img_folder=".", annotations="sample.json", feature_extractor=feature_extractor)
    id2label, label2id = load_category(train_dataset.coco.cats)
    config = DetrConfig.from_pretrained("facebook/detr-resnet-50")
    config.id2label = id2label
    config.label2id = label2id

    model = DetrForObjectDetection.from_pretrained(
        "facebook/detr-resnet-50",
        config=config)

    # Initialize our Trainer
    trainer = DetrTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        tokenizer=feature_extractor,
        data_collator=DataCollatorDetr(feature_extractor=feature_extractor),
    )

    train_result = trainer.train()

if __name__ == "__main__":
    main()
```

3.  Run by `python run.py` in a multiple-GPU environment.
Then `IndexError` is caused.

```
Traceback (most recent call last):
  File "run.py", line 112, in <module>
    main()
  File "run.py", line 109, in main
    train_result = trainer.train()
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/transformers/trainer.py", line 1286, in train
    tr_loss += self.training_step(model, inputs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/transformers/trainer.py", line 1779, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/transformers/trainer.py", line 1811, in compute_loss
    outputs = model(**inputs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/transformers/models/detr/modeling_detr.py", line 1430, in forward
    loss_dict = criterion(outputs_loss, labels)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/transformers/models/detr/modeling_detr.py", line 2004, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/transformers/models/detr/modeling_detr.py", line 2132, in forward
    indices = [linear_sum_assignment(c[i]) for i, c in enumerate(cost_matrix.split(sizes, -1))]
  File "/home/christopher/detr_samples/env/lib/python3.8/site-packages/transformers/models/detr/modeling_detr.py", line 2132, in <listcomp>
    indices = [linear_sum_assignment(c[i]) for i, c in enumerate(cost_matrix.split(sizes, -1))]
IndexError: index 1 is out of bounds for dimension 0 with size 1
```
It works fine with a single GPU.

## Expected behavior
Successfully complete training.

**Comment by NielsRogge** [comment]
Hi,

As explained in the [docs](https://huggingface.co/transformers/model_doc/detr.html):
> If you want to train the model in a distributed environment across multiple nodes, then one should update the num_boxes variable in the DetrLoss class of modeling_detr.py. When training on multiple nodes, this should be set to the average number of target boxes across all nodes, as can be seen in the original implementation here.

**Comment by jnishi** [comment]
Hi, thank you for the quick reply.

> When training on multiple nodes, this should be set to the average number of target boxes across all nodes, 

I'd like to ask you two questions.
1. Do I need to insert `num_boxes / (the number of nodes)`  after the following line https://github.com/huggingface/transformers/blob/master/src/transformers/models/detr/modeling_detr.py#L2013 ? 
For example, if I'm training on two GPUs, should I insert `num_boxes = num_boxes / 2` after the line?

2. The error occurs at https://github.com/huggingface/transformers/blob/master/src/transformers/models/detr/modeling_detr.py#L2004 which is before the declaration of `num_boxes`. Could you tell me more about how to solve this error?

**Comment by NielsRogge** [comment]
For now, the code has not been tested to work on multiple GPUs, so this is a good opportunity to make it work. We can perhaps write a guide on which things to take into account. 

> Do I need to insert num_boxes / (the number of nodes) after the following line https://github.com/huggingface/transformers/blob/master/src/transformers/models/detr/modeling_detr.py#L2013 ?
For example, if I'm training on two GPUs, should I insert num_boxes = num_boxes / 2 after the line?

The [original implementation](https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/models/detr.py#L230-L232) used the following code:
```
if is_dist_avail_and_initialized():
   torch.distributed.all_reduce(num_boxes)
num_boxes = torch.clamp(num_boxes / get_world_size(), min=1).item()
```
with

```
import torch.distributed as dist

def is_dist_avail_and_initialized():
    if not dist.is_available():
        return False
    if not dist.is_initialized():
        return False
    return True
```
> The error occurs at https://github.com/huggingface/transformers/blob/master/src/transformers/models/detr/modeling_detr.py#L2004 which is before the declaration of num_boxes. Could you tell me more about how to solve this error?

This could have to do with the `targets` not being on the proper devices, which is the responsibility of the `Trainer`. In the original implementation, they use `DistributedSampler`. Can you perhaps print the `sizes that are computed right before it? These should be a list containing the number of bounding boxes for every example in the batch.

**Comment by jnishi** [comment]
> For now, the code has not been tested to work on multiple GPUs, so this is a good opportunity to make it work. We can perhaps write a guide on which things to take into account.

It would be great if you could support multiple GPUs.

> The world size is 2 if you're training on a single node with 2 GPUs, so you can divide them indeed by 2.

I found out that if you do it manually, divide by the number of GPUs.

> This could have to do with the targets not being on the proper devices, which is the responsibility of the Trainer. In the original implementation, they use DistributedSampler. Can you perhaps print the sizes that are computed right before it? These should be a list containing the number of bounding boxes for every example in the batch.

The reason for the error is that DistributedSampler does not support `labels` data. 
Thank you very much.

**Comment by RajamannarAanjaram** [comment]
1. If I want to extend this to panoptic segmentation using coco stuff classes, how should I change the class config to do it.
I have only 1things categories balloon and 53 stuff categories from coco dataset
2. How do I freeze the weights for training mask head for 25 epochs

**Comment by NielsRogge** [comment]
> If I want to extend this to panoptic segmentation using coco stuff classes, how should I change the class config to do it.
I have only 1things categories balloon and 53 stuff categories from coco dataset

If you want to do panoptic segmentation, you first need to load the model as follows:

```
from transformers import DetrForSegmentation

model = DetrForSegmentation.from_pretrained("facebook/detr-resnet-50-panoptic", num_labels=54, ignore_mismatched_sizes=True)

```
You can possibly also add the `id2label` and `label2id` dictionaries as additional arguments.

> How do I freeze the weights for training mask head for 25 epochs

```
for name, param in model.named_parameters():
  if 'mask_head' in name or 'bbox_attention' in name:
    param.requires_grad = False
```

> How do we edit the classifier layer of the model say by default this will have 92 class, but from the above example if I have only 2 class (balloon, 'N/A') how should I change them?

There's a new argument called `ignore_mismatched_sizes` which you can set to `True`. If you then specify a different number of labels, no error will be thrown (only a warning), as shown above.

**Comment by NielsRogge** [comment]
If you want a neural network to learn additional classes, it's advised to add a new classification head and fine-tune the model on all classes you want. So indeed, now the class embedding layer should have 57 outputs.

> One general question in your notebook the model is trained using pl rather that torch what is the reason for using pl

Because it's very easy to train PyTorch models. You can of course just train using native PyTorch or using HuggingFace Accelerate, or using HuggingFace's Trainer, etc.
