### ISSUE TITLE
Using pytorch-transformer to reimplement the "Attention is all you need" paper

### ISSUE THREAD

**Issue by roholazandie** [huggingface/transformers#1321]
## ❓ Questions & Help
I use this repo for a long time but I realized even though the name is PyTorch transformers I can't find an easy way to re-implement the original paper of "Attention is all you need" with pretrained model. Can someone help me?

**Comment by LysandreJik** [comment]
Hi, this repository's objective is mainly to host **pretrained** models, not really to build a model from scratch.

You could use some of this library's components though, like multi-headed attention, to help you in your endeavor.
