### ISSUE TITLE
Unable to load 'rembert' checkpoint 

### ISSUE THREAD

**Issue by Sam131112** [huggingface/transformers#13223]
## Environment info

- `transformers` version: 4.10.0.dev0
- Platform: Linux-5.4.0-54-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.6.10
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

## Information

from transformers import RemBertTokenizer,RemBertTokenizerFast,RemBertForQuestionAnswering
tokenizer = RemBertTokenizer.from_pretrained('rembert')

## Output

HTTPError                                 Traceback (most recent call last)
<ipython-input-23-22b8f1f94b36> in <module>
      1 from transformers import RemBertTokenizer,RemBertTokenizerFast,RemBertForQuestionAnswering
----> 2 tokenizer = RemBertTokenizer.from_pretrained('rembert')

~/anaconda3/envs/Sam1/lib/python3.6/site-packages/transformers/tokenization_utils_base.py in from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
   1646             # At this point pretrained_model_name_or_path is either a directory or a model identifier name
   1647             fast_tokenizer_file = get_fast_tokenizer_file(
-> 1648                 pretrained_model_name_or_path, revision=revision, use_auth_token=use_auth_token
   1649             )
   1650             additional_files_names = {

~/anaconda3/envs/Sam1/lib/python3.6/site-packages/transformers/tokenization_utils_base.py in get_fast_tokenizer_file(path_or_repo, revision, use_auth_token)
   3409     """
   3410     # Inspect all files from the repo/folder.
-> 3411     all_files = get_list_of_files(path_or_repo, revision=revision, use_auth_token=use_auth_token)
   3412     tokenizer_files_map = {}
   3413     for file_name in all_files:

~/anaconda3/envs/Sam1/lib/python3.6/site-packages/transformers/file_utils.py in get_list_of_files(path_or_repo, revision, use_auth_token)
   1693         token = None
   1694     model_info = HfApi(endpoint=HUGGINGFACE_CO_RESOLVE_ENDPOINT).model_info(
-> 1695         path_or_repo, revision=revision, token=token
   1696     )
   1697     return [f.rfilename for f in model_info.siblings]

~/anaconda3/envs/Sam1/lib/python3.6/site-packages/huggingface_hub/hf_api.py in model_info(self, repo_id, revision, token)
    246         )
    247         r = requests.get(path, headers=headers)
--> 248         r.raise_for_status()
    249         d = r.json()
    250         return ModelInfo(**d)

~/anaconda3/envs/Sam1/lib/python3.6/site-packages/requests/models.py in raise_for_status(self)
    939 
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 
    943     def close(self):

HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/rembert

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by LysandreJik** [comment]
The checkpoint is `google/rembert`: https://huggingface.co/google/rembert

**Comment by Sam131112** [comment]
thanks :)
