### ISSUE TITLE
Typo in M2M100 1.2B model card page, strange translation results and new M2M100 615M model

### ISSUE THREAD

**Issue by Fikavec** [huggingface/transformers#13221]
@patil-suraj thank you so much for your great work, seems like there's a typo in the [M2M100 1.2B page:](https://huggingface.co/facebook/m2m100_1.2B)
>model = M2M100ForConditionalGeneration.from_pretrained("facebook/m2m100_418M") 
>tokenizer = M2M100Tokenizer.from_pretrained("facebook/m2m100_418M")

It should be "m2m100_1.2B" instead of "m2m100_418M". 

Model m2m100_1.2B sometimes gives a strange translation results on news titles - incorrectly translates the names of countries and cities in sentences, but model m2m100_418M translates correctly (i'm saw this in many languages pairs) - it is normal, or maybe there error in uploaded "facebook/m2m100_1.2B" tokenizer/model or function code M2M100Tokenizer.from_pretrained("facebook/m2m100_1.2B")?
For example:

> from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer
model = M2M100ForConditionalGeneration.from_pretrained("facebook/m2m100_418M")
tokenizer = M2M100Tokenizer.from_pretrained("facebook/m2m100_418M")
sentence = "في ميسان"
tokenizer.src_lang = "ar"
encoded_zh = tokenizer(sentence, return_tensors="pt")
generated_tokens = model.generate(**encoded_zh, forced_bos_token_id=tokenizer.get_lang_id("en"))
print(tokenizer.batch_decode(generated_tokens, skip_special_tokens=True))
model = M2M100ForConditionalGeneration.from_pretrained("facebook/m2m100_1.2B")
tokenizer = M2M100Tokenizer.from_pretrained("facebook/m2m100_1.2B")
tokenizer.src_lang = "ar"
encoded_zh = tokenizer(sentence, return_tensors="pt")
generated_tokens = model.generate(**encoded_zh, forced_bos_token_id=tokenizer.get_lang_id("en"))
print(tokenizer.batch_decode(generated_tokens, skip_special_tokens=True))

gives ['in Messan.'] and ['in Messengers'] Try also sentence = "متهمين في ميسان" - gives ['Accused in Messiah.'] ['Prosecutors in Missouri'] - why [ميسان](https://en.wikipedia.org/wiki/Maysan_Governorate) in news titles translates by m2m100_1.2B as Messengers, Missouri, Mexico, Munich? 

It is possible to add [new M2M100 615M model?](https://github.com/huggingface/transformers/issues/12775#issuecomment-889437365)

**Comment by patil-suraj** [comment]
Hi @Fikavec 

Thank you for reporting this, the typo is fixed now!

> It is possible to add a new M2M100 615M model?
Yes, I will take a look.

> Model m2m100_1.2B sometimes gives a strange translation results on news titles - incorrectly translates the names of countries and cities in sentences, but model m2m100_418M translates correctly (i'm saw this in many languages pairs) - it is normal, or maybe there error in uploaded "facebook/m2m100_1.2B" tokenizer/model or function code M2M100Tokenizer.from_pretrained("facebook/m2m100_1.2B")?

I don't think this is an error but I will take a look. But I have observed this behavior with multi-linguial models, the translations sometimes could be wrong especially for low-resource languages.
