### ISSUE TITLE
Correct way to use pre-trained models - Any document on this?

### ISSUE THREAD

**Issue by pratikchhapolika** [huggingface/transformers#13238]
I want to do `Multiclass-Multilabel ( MLMC)` **classification** problem using `Conv-BERT` model.

**Steps that I have taken is:**

I downloaded the Conv-Bert model from this link: https://huggingface.co/YituTech/conv-bert-base
<< **YituTech/conv-bert-base**>>

```
from pytorch_pretrained_bert import BertTokenizer, BertForSequenceClassification, BertAdam
tokenizer = **BertTokenizer.from_pretrained**("path_to_Conv-Bert_model", do_lower_case = True)
model = **BertForSequenceClassification.from_pretrained**("path_to_Conv-Bert_model", num_labels = 240)
model.cuda()
```

I want to understand can we call any classification module from Hugging face and pass any pre-trained models to it like `Roberta, Conv-BERT.. so on`. ? << As in above example>> 
Is it mandatory to use Conv-Bert classification pre-trained model ?

**Comment by LysandreJik** [comment]
Hello! We have several documents that can help you get started! First of all, the [quicktour](https://huggingface.co/transformers/quicktour.html), and the [free course](https://huggingface.co/course/chapter1) of the HF ecosystem may help you out.

**Comment by pratikchhapolika** [comment]
> Hello! We have several documents that can help you get started! First of all, the [quicktour](https://huggingface.co/transformers/quicktour.html), and the [free course](https://huggingface.co/course/chapter1) of the HF ecosystem may help you out.

What about my code above. Is this correct way of doing things?
