### ISSUE TITLE
A Micro BERT

### ISSUE THREAD

**Issue by aditya-malte** [huggingface/transformers#1324]
## ❓ Questions & Help

Hello,
Has anyone solved a problem like this, or knows of a solution:
I want to pre-train BERT on a custom dataset, but this data is much smaller than the one used by Google.
So is it possible to train it on a "micro" bert with much lesser layers, etc.
Thanks in advance

**Comment by royhuang9** [comment]
I am using a much smaller dataset with my project, but it doesn't mean I need a bert with lesser layers. Otherwise, I have no way to utilize the pre-trained model.

What is the problem you have with the smaller dataset?

**Comment by aditya-malte** [comment]
My dataset is very esoteric, in the sense that BERTs pretrained weights will almost be like noise.

**Comment by cavities** [comment]
YOU NEED ALBERT

**Comment by aditya-malte** [comment]
Einstein?

**Comment by wassname** [comment]
They are referring to this new [ALBERT paper](https://old.reddit.com/r/MachineLearning/comments/d9tdfo/albert_a_lite_bert_for_selfsupervised_learning_of/). No weights are available however so give it a few months.

**Comment by aditya-malte** [comment]
Interesting. Can't I train a very small BERT as you said(maybe 2 layers) on like 4million tokens

**Comment by wassname** [comment]
I'm not sure what the minimum tokens and layers are, I'm not sure anyone has published that. Best to try it out.
