### ISSUE TITLE
Add ability to include additional model card info within Trainer

### ISSUE THREAD

**Issue by nateraw** [huggingface/transformers#13245]
# 🚀 Feature request

Allow users to optionally provide model description, intended use, ethical considerations, caveats and recommendations, etc. when calling `trainer.push_to_hub` and/or `trainer.create_model_card`. 

## Motivation

Right now, when you do `trainer.push_to_hub`, it runs `trainer.create_model_card`, which calls `transformers.modelcard.TrainingSummary.to_model_card` behind the scenes to put together the model card's text. It does not allow you to pass the sections mentioned above. 

https://github.com/huggingface/transformers/blob/b1198a8440cc05f569b0bc22038993a1e5e707ab/src/transformers/trainer.py#L2479-L2502

Thus, whenever someone pushes to the hub with `Trainer`, there are a bunch of sections that say "More information needed".  

---

I see that `transformers.modelcard.ModelCard` has these options, but there's a note about it being deprecated. 

https://github.com/huggingface/transformers/blob/b1198a8440cc05f569b0bc22038993a1e5e707ab/src/transformers/modelcard.py#L74-L100

**Comment by sgugger** [comment]
Yes the `ModelCard` is deprecated as it does not make any sense to deal with this programmatically (the class was there for more than a year and I haven't seen it used once).

The Trainer drafts the model card, it's then the responsibility of the user to edit it in a followup commit, but the easiest way to do this, is through the user's preferred text editor IMO.

**Comment by julien-c** [comment]
> but the easiest way to do this, is through the user's preferred text editor IMO

or directly on the hub website 👍 

we should remove the current `ModelCard` implementation to make room for new helpers IMO (which will be in `huggingface_hub`)

**Comment by sgugger** [comment]
It will disappear in v5 as it's a breaking change.

**Comment by nateraw** [comment]
closing and will address in `huggingface_hub`
