### ISSUE TITLE
Label Smoothing for Question Answering task

### ISSUE THREAD

**Issue by ubamba98** [huggingface/transformers#13255]
# 🚀 Feature request

Currently label smoothing is only applied when "label" is present in the input in compute_loss function and not in case of question answering default in Trainer class.

## Your contribution

I would like to work on this issue and submit a PR by modifying compute_loss to use label_names to apply label smoothing for question answering.

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
I'm not entirely sure how straightforward this could be, plus it seems like a very narrow use case. I think this should be implemented independently by the user with a custom `compute_loss`  function.
