### ISSUE TITLE
Cannot use RemBert

### ISSUE THREAD

**Issue by KappalaSaikumar** [huggingface/transformers#13253]
![Screenshot (1508)](https://user-images.githubusercontent.com/65230225/130734536-0d498812-2ee4-45fe-96a0-6c33fc007916.png)

When I am trying to use the AutoTokenizer for the newly added RemBert model it's giving me this error

![Screenshot (1509)](https://user-images.githubusercontent.com/65230225/130736371-869e52d9-d4cb-4dc1-a480-8234d658420c.png)

When I try importing RemBertTokenizer then it's giving me this error.

**Comment by NielsRogge** [comment]
Make sure to install Transformers from master: `pip install git+https://github.com/huggingface/transformers.git`

**Comment by KappalaSaikumar** [comment]
Thanks @NielsRogge It's working fine now
