### ISSUE TITLE
请问一下，情感分析的模型只是针对英文的吗

### ISSUE THREAD

**Issue by ArlanCooper** [huggingface/transformers#13254]
classifier = pipeline('sentiment-analysis')
这里面封装的模型是只针对英文的吗？我使用中文发现完全不对，比如：
words = '这是一个不错的服务'
judge1 = classifier(words)
words = '这是一个很好的服务'
judge2 = classifier(words)
print(judge1,judge2)

结果展示:
[{'label': 'NEGATIVE', 'score': 0.9500061273574829}] [{'label': 'NEGATIVE', 'score': 0.92015540599823}]

**Comment by llhll** [comment]
You should ask in English to obtain more answers.

**Comment by NielsRogge** [comment]
This is a bit intimidating to me haha. I'll use deep learning to translate your issue (😮 ):

DeepL says:

classifier = pipeline('sentiment-analysis')
Is the model encapsulated in this only for English? I found it completely wrong using Chinese, e.g.
words = 'this is a good service'
judge1 = classifier(words)
words = 'This is a good service'
judge2 = classifier(words)
print(judge1,judge2)

=> answer: yes, the default sentiment analysis pipeline is English-only, as it uses a `DistilBertForSequenceClassification` model fine-tuned on English data (I'm not sure, Ii's a bummer that it's difficult to know what the default model is that is used for each pipeline, see #12845)

**Comment by patrickvonplaten** [comment]
You could use the model hub to find sentiment analysis models in Chinese as follows:

https://huggingface.co/models?language=zh&pipeline_tag=text-classification&sort=downloads

**Comment by patrickvonplaten** [comment]
And then do:

```python
classifier = pipeline('sentiment-analysis', model="https://huggingface.co/uer/roberta-base-finetuned-chinanews-chinese")
```

**Comment by ArlanCooper** [comment]
> And then do:
> 
> ```python
> classifier = pipeline('sentiment-analysis', model="https://huggingface.co/uer/roberta-base-finetuned-chinanews-chinese")
> ```

thank you  for your answer,that's help a lot

**Comment by ArlanCooper** [comment]
> This is a bit intimidating to me haha. I'll use deep learning to translate your issue (😮 ):
> 
> DeepL says:
> 
> classifier = pipeline('sentiment-analysis')
> Is the model encapsulated in this only for English? I found it completely wrong using Chinese, e.g.
> words = 'this is a good service'
> judge1 = classifier(words)
> words = 'This is a good service'
> judge2 = classifier(words)
> print(judge1,judge2)
> 
> => answer: yes, the default sentiment analysis pipeline is English-only, as it uses a `DistilBertForSequenceClassification` model fine-tuned on English data (I'm not sure, Ii's a bummer that it's difficult to know what the default model is that is used for each pipeline, see #12845). You can indeed, as Patrick mentions below, use a custom model from the hub.

sorry i use chinese, and thank you  for your answer,that's help a lot
