### ISSUE TITLE
ingore_mismatched_sizes Wav2Vec2 unknown argument

### ISSUE THREAD

**Issue by flozi00** [huggingface/transformers#13256]
## Environment info

- `transformers` version:
- Platform: Win 10
- Python version: 3.8
- PyTorch version (GPU?): yes
- Tensorflow version (GPU?):
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?:

### Who can help

@patrickvonplaten @sgugger 

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below) added size missmatch ignore to loading model

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce
```
model = Wav2Vec2ForCTC.from_pretrained(
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\transformers\modeling_utils.py", line 1321, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ingore_mismatched_sizes'
```

```
model = Wav2Vec2ForCTC.from_pretrained(
        model_args.model_name_or_path,
        cache_dir=model_args.cache_dir,
        activation_dropout=model_args.activation_dropout,
        attention_dropout=model_args.attention_dropout,
        hidden_dropout=model_args.hidden_dropout,
        feat_proj_dropout=model_args.feat_proj_dropout,
        mask_time_prob=model_args.mask_time_prob,
        gradient_checkpointing=model_args.gradient_checkpointing,
        layerdrop=model_args.layerdrop,
        ctc_loss_reduction="mean",
        pad_token_id=processor.tokenizer.pad_token_id,
        vocab_size=len(processor.tokenizer),
        ingore_mismatched_sizes=True,
    )
```

## Expected behavior

The model can be loaded like Vit,Deit or Beit do with the ingore_mismatched_sizes argument

**Comment by qqaatw** [comment]
Hello, kindly check out this [issue](https://github.com/huggingface/transformers/issues/13187#issuecomment-902116183) and see if it can solve your problem.

**Comment by flozi00** [comment]
Oh, thank you.
I didn't see that, I just copied it from another issue here
