### ISSUE TITLE
Docs: TrainingArguments call incorrect

### ISSUE THREAD

**Issue by UrosOgrizovic** [huggingface/transformers#13273]
On [this](https://huggingface.co/transformers/training.html) page, there's the following code:

```
from transformers import TrainingArguments
training_args = TrainingArguments("test_trainer", evaluation_strategy="epoch")
```

However, `evaluation_strategy` needs to be an `IntervalStrategy` instead of a `string`. The way `TrainingArguments` actually needs to be called is:

```
training_args = TrainingArguments("test_trainer", evaluation_strategy=IntervalStrategy.EPOCH)
```

**Comment by sgugger** [comment]
No, this example is correct, as both syntax work.
