### ISSUE TITLE
Commit v4.9.2 release appears as v4.5.1 in "transformers-cli env"

### ISSUE THREAD

**Issue by merleyc** [huggingface/transformers#13270]
## Environment info
The command **_transformers-cli env_** returns:
_2021-08-26 07:30:45.855430: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-26 07:30:45.855484: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From /home/mypath/miniconda3/lib/python3.7/site-packages/transformers/commands/env.py:50: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2021-08-26 07:30:47.909798: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-26 07:30:47.920073: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-08-26 07:30:47.920123: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-26 07:30:47.920158: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (sr507): /proc/driver/nvidia/version does not exist_

- `transformers` version: 4.5.1
- Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core
- Python version: 3.7.7
- PyTorch version (GPU?): 1.9.0+cu102 (False)
- Tensorflow version (GPU?): 2.6.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
Documentation: @sgugger

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x ] my own task or dataset: (give details below)

## To reproduce

1. git clone --recursive https://github.com/merleyc/transformers.git
2. conda create -n hf-dev-py380 python=3.8.0
3. ipython kernel install --user --name=hf-dev-py380
4. cd transformers/
5. git checkout v4.9.2-release
6. git log -> It appears the correct release version:
_commit 41981a25cdd028007a7491d68935c8d93f9e8b47 (HEAD -> exploration, tag: v4.9.2, origin/v4.9.2-release, v4.9.2-release)
Author: Lysandre <lysandre.debut@reseau.eseo.fr>
Date:   Mon Aug 9 16:01:36 2021 +0200
    Patch release: v4.9.2_

7. git checkout -b exploration
8. pip uninstall transformers
9. pip install -e ".[dev]"
10. git clone --recursive  https://github.com/huggingface/datasets
11. cd datasets/
12. pip install -e ".[dev]"
13. export http_proxy=http://xxx:yyy; export https_proxy=http://xxx:yyy; export ftp_proxy=xxx:yyy
14. python -m pytest -n 52 --dist=loadfile -s -v ./tests/ > ~/results_cli4.txt
15. conda install cloudpickle -> because it complained: "distributed 1.26.0 requires cloudpickle>=0.2.2, which is not installed."
16. pip uninstall huggingface-hub
17. pip install  huggingface-hub==0.0.12 -> because it complained "transformers 4.9.2 requires huggingface-hub==0.0.12, but you have huggingface-hub 0.0.15 which is incompatible."

18. pip uninstall pycodestyle
19. pip install pycodestyle==2.7.0 -> because it complained: "autopep8 1.5.6 requires pycodestyle>=2.7.0, but you have pycodestyle 2.5.0 which is incompatible."
20. pip install -e ".[dev]" -> It complained: "flake8 3.7.9 requires pycodestyle<2.6.0,>=2.5.0, but you have pycodestyle 2.7.0 which is incompatible." and showed the below result: 
"_9 failed, 3240 passed, 2803 skipped, 172 warnings in 2630.90s (0:43:50)_"

There are several issues I observed while following these steps, like unmatched python versions, pip package dependency incompatibilities, and failing tests, but let's, for now, focus on the transformer version please. I will be happy to open other issues if needed.

## Expected behavior

The result of  **_transformers-cli env_**  should be the version I cloned from the repo, which is version: 4.9.2

**Comment by LysandreJik** [comment]
`pip install -e .[dev]` means you'll be installing all the dependencies that we have put down for the `dev` option; which is the option we use to imply that a user is working on the `transformers` package directly. It adds all possible dependencies that would otherwise be blocking: TensorFlow, PyTorch, Flax, speech, vision, ...

It is not necessary to install this to use the `transformers` library, only to work on it.

See the `setup.py` for more information: https://github.com/huggingface/transformers/blob/master/setup.py#L301-L308

**Comment by merleyc** [comment]
Thanks for the explanation, @LysandreJik !

I was only able to successfully run `pip install -e .[dev]` after I installed extra packages (librosa and libgcc ) and set up the LD_LIBRARY_PATH. Do you also need to install these packages and set up this env variable or is it something only in my environment? If you also have this dependency, I should probably open a new issue about this it.

Thanks!

**Comment by LysandreJik** [comment]
Those are requirements that PIL and `soundfile` have on system-wide dependencies. Unfortunately, these are not dependencies that we can control from within the `setup.py` - but we should at least make that clearer, for example on this page: https://huggingface.co/transformers/installation.html#installation-with-pip

Would you like to try your hand at modifying the docs to mention what might need to be done in case of a `[dev]` installation?

**Comment by merleyc** [comment]
I will be happy to (will work on that next week :) )

**Comment by LysandreJik** [comment]
That sounds great @merleyc, looking forward to it!
