### ISSUE TITLE
Examples: label mapping for text classication tasks are not written into configuration

### ISSUE THREAD

**Issue by stefan-it** [huggingface/transformers#13298]
Hi,

I've shortly discussed this with @patrickvonplaten , and we came to the conclusion that the following scenario is a bug:

When using the text classification for a GLUE task, no label mapping will be written into the configuration of the final fine-tuned model.

This leads to an unesthetic "label_0" on the model hub, as it can be seen here:

![Bildschirmfoto_2021-08-27_12-17-09](https://user-images.githubusercontent.com/20651387/131112292-ab2fc8f8-2fad-42cf-b436-0a0a5e0a4475.png)

One has to manually extend the `config.json`:

```json
"id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  }
```

to get the following output:

![Bildschirmfoto_2021-08-27_12-17-29](https://user-images.githubusercontent.com/20651387/131112468-bff93d0f-4f3f-428d-ac3b-696ae6e08543.png)

The text classification examples should be extended, so that those label mappings are automatically added to the configuration file.

**Comment by LysandreJik** [comment]
cc @sgugger @Rocketknight1

**Comment by sgugger** [comment]
Should be fixed by the PR above, I forgot the `label_to_name` dict was left to None for GLUE tasks.
