### ISSUE TITLE
Missing on_predict event in TrainerCallback

### ISSUE THREAD

**Issue by rpowalski** [huggingface/transformers#13306]
# 🚀 Feature request

Can we add `on_predict` event support in the `Trainer` and `TrainerCallback`?

## Motivation

I was in need to use it already in multiple projects. I think it makes sense since `Trainer` already support `on_evaluate` event inside `evaluate()` method. Corresponding event handler is missing in `predict()` method which is part of the `Trainer` class. Some of the training support libraries are supporting such events, so I guess there are no strong reasons against that ([link](https://pytorch-lightning.readthedocs.io/en/latest/extensions/generated/pytorch_lightning.callbacks.Callback.html#pytorch_lightning.callbacks.Callback.on_test_end)).

## Your contribution

I am willing to make a PR that will implement that.

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
The reason why there is no `on_predict` event is that the `predict` method is never called during the training loop. You can add the code you want to be run after `Trainer.predict` just after calling that method.

**Comment by rpowalski** [comment]
Ok, I see. For my cases having this custom code in the callback feels cleaner and more consistent to the post-processing done during `evaluate()` method, but will do it as you suggest.
