### ISSUE TITLE
Typo in modeling_bert file

### ISSUE THREAD

**Issue by ishan00** [huggingface/transformers#1334]
I was looking at the code of BertModel adapted for different tasks here 
https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/modeling_bert.py

I noticed a small typo in line 882
`self.classifier = nn.Linear(config.hidden_size, self.config.num_labels)`
I think it should be either `self.num_labels` or `config.num_labels` in the second argument

The complete function
```
def __init__(self, config):
        super(BertForSequenceClassification, self).__init__(config)
        self.num_labels = config.num_labels

        self.bert = BertModel(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.classifier = nn.Linear(config.hidden_size, self.config.num_labels)

        self.init_weights()
```

**Comment by LysandreJik** [comment]
Hi! Indeed it is inconsistent, but it  doesn't really change anything as the superclass `PreTrainedModel` assigns the config as one of its attributes: `self.config = config`. Referencing `config` or `self.config` therefore references the same object!
