### ISSUE TITLE
wav2vec2-large-xlsr-53 Tokenizer unable to load

### ISSUE THREAD

**Issue by felixlut** [huggingface/transformers#13371]
## Environment info

- `transformers` version: 4.10.0
- Platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.11
- PyTorch version (GPU?): 1.9.0+cu102 (True)
- Tensorflow version (GPU?): 2.6.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@patrickvonplaten 

## Information
Model I am using (Bert, XLNet ...):

I'm using the Wav2Vec2-XLSR-53 model, and it is specifically the loading part that doesn't work properly. The script below is provided on the model's huggingface page, and the tokenizer (2:nd line) does not load, while the actual model does work (3:d line). 

```python
from transformers import AutoTokenizer, AutoModelForPreTraining
  
tokenizer = AutoTokenizer.from_pretrained("facebook/wav2vec2-large-xlsr-53")

model = AutoModelForPreTraining.from_pretrained("facebook/wav2vec2-large-xlsr-53")
```
## To reproduce

1. Run the script above

## Expected behavior

I would expect the tokenizer to load.

**Comment by flozi00** [comment]
https://github.com/huggingface/transformers/blob/ecd5397106e243021ef28e65ca566881bb825bcb/examples/research_projects/wav2vec2/run_common_voice.py#L343-L366

The pretrained model has no tokenizer, you need to built your own one.

If you want to pretrain there is an example script here: https://github.com/huggingface/transformers/blob/master/examples/research_projects/wav2vec2/run_pretrain.py

**Comment by felixlut** [comment]
Ok, thanks for the quick response!
