### ISSUE TITLE
Extending `examples/` to TensorFlow

### ISSUE THREAD

**Issue by HanGuo97** [huggingface/transformers#1338]
## 🚀 Feature

Hi, thanks for putting in the tremendous effort for TensorFlow-PyTorch interoperability! Would those scripts in the `examples/` be soon extended to Tensorflow as well?

## Motivation

I (and presumably many others) rely on the examples to quickly experiment with models and ideas. Extending the examples to Tensorflow would be hugely helpful, and should help the codebase reach a broader set of audiences.

**Comment by thomwolf** [comment]
Indeed, there is currently one example for tensorflow, `run_tf_glue` and it doesn't have command-line arguments. We'll update this one to make it as flexible as the PyTorch one and add other examples when we have the bandwidth.

Do you want to help in this project? Happy to welcome a PR on this topic (for instance to add command line argument similar to `run_glue` in `run_tf_glue`).

**Comment by HanGuo97** [comment]
Thanks for the response. I'm not an expert in this field but I'm happy to help and review codes.
