### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by mehmetsinanyildirim** [huggingface/transformers#13382]
https://github.com/huggingface/transformers/blob/4475f1dc2aa7153adb5e66b361c48aed1321fe3d/examples/pytorch/question-answering/run_qa.py#L423

On this line, the word 'agument' has a typo. I believe it should be argument. While we are at it, I think changing it to 'the argument' would be better as well.

**Comment by NielsRogge** [comment]
If there's a typo, feel free to open a PR! Thanks.

**Comment by akulagrawal** [comment]
Just spotted this issue again, creating a PR
