### ISSUE TITLE
Hard time installing huggingface for python3.8 cuda10.1

### ISSUE THREAD

**Issue by GTimothee** [huggingface/transformers#13388]
## Environment info
- `transformers` version: 4.10.0
- Platform: linux (ubuntu)
- Python version: 3.8
- PyTorch version (GPU?): 1.7.1+cu101
- Tensorflow version (GPU?): 2.2.0 , tf-gpu : 2.2.0
- Using GPU in script?: not even using it for now
- Using distributed or parallel set-up in script?: no

## Assignees
- trainer: @sgugger

## Information
I am trying to fine tune the LayoutLMv2ForSequenceClassification model. 

When I test my installation inside a venv with the following command it crashes: 
```
python -c "import tensorflow as tf"
```

Output: 
```
env_3.8/lib/python3.8/site-packages/transformers/onnx/convert.py", line 23, in <module>
    from .. import PreTrainedModel, PreTrainedTokenizer, TensorType, TFPreTrainedModel, is_torch_available
ImportError: cannot import name 'TFPreTrainedModel' from 'transformers' 
```

**Comment by LysandreJik** [comment]
Can you try updating your TensorFlow version and letting us know if it fixes your issue? For example to tensorflow v2.5.0

**Comment by GTimothee** [comment]
Hello, finally I solved my issue : it was a tensorflow-related issue. In fact I was playing with a small script named code.py in which I was importing stuff from huggingface, and tensorflow was trying to import something else, also named code.py so there was a circular import or something. So in the end I just renamed my script file and it works !

**Comment by LysandreJik** [comment]
Ah interesting! Thanks for updating us.
