### ISSUE TITLE
Possibility of disabling add_pooling_layer that works for all models

### ISSUE THREAD

**Issue by ZhaofengWu** [huggingface/transformers#13413]
# 🚀 Feature request

A way to ensure that no additional pooling layers are added that works for all model types.

## Motivation

I just want a barebone transformer and I need the per-token representation. Hence the pooling layer that is added in BERT-based models is not necessary for me, but it still occupies memory and forward pass time. Now, I think this can be disabled via `AutoModel.from_pretrained(name, add_pooling_layer=False)` (right?), but I don't think this would work for all models since some don't have this flag (e.g., GPT-2).

**Comment by ZhaofengWu** [comment]
Commenting for activity

**Comment by LysandreJik** [comment]
The GPT-2 doesn't have a pooling layer, so what would you like to disable?

**Comment by ZhaofengWu** [comment]
The issue is that if I pass `add_pooling_layer=False` to GPT-2, it will break. But I want a model-agnostic way to create a base model and ensure that there is no pooling layer added.

**Comment by ZhaofengWu** [comment]
Commenting for activity
