### ISSUE TITLE
Examples in Colab

### ISSUE THREAD

**Issue by redditTroll** [huggingface/transformers#1341]
Hi all , does anyone have a Colab sample to share ?

**Comment by BramVanroy** [comment]
Why not simply run the example scripts in colab yourself?

**Comment by redditTroll** [comment]
I'm not exactly sure how to set it up , this is a pretty popular library so I was thinking their might be a blog post out there

**Comment by Santosh-Gupta** [comment]
https://huggingface.co/transformers/notebooks.html
