### ISSUE TITLE
Huggingface Inference API

### ISSUE THREAD

**Issue by robertalanm** [huggingface/transformers#13423]
Hello,

I recently bought the startup subscription for my organization. However, it appears I cannot add large models to inference API. I am trying to serve GPT-J-6B model on inference API. When I emailed "api-inference@huggingface.co" it returns an error message:
```host aspmx.l.google.com[142.251.4.27] said:
The email account that you tried to reach does not exist. 
Please try double-checking the recipient's email address for typos or unnecessary spaces.
```
What is the updated support email for startup plan users?

**Comment by julien-c** [comment]
Hi, it is `api-enterprise@huggingface.co` – I think there was an incorrect reference to the other email address somewhere that we fixed recently (cc @jeffboudier)

**Comment by robertalanm** [comment]
I sent this address an email but have not received a response. Is there another way to contact the engineers in charge of setting up large models for inference api endpoints?

**Comment by robertalanm** [comment]
I'm just going to cancel the sub. Sorry for taking up anyone's time.
