### ISSUE TITLE
AttributeError: 'RobertaTokenizer' object has no attribute 'add_special_tokens_sentences_pair'

### ISSUE THREAD

**Issue by frankfka** [huggingface/transformers#1342]
With the latest update to `Transformers`, has the function been removed? I still see it in the code, but I run into the error:

`AttributeError: 'RobertaTokenizer' object has no attribute 'add_special_tokens_sentences_pair'`

**Comment by cformosa** [comment]
Hey @frankfka 

Perhaps you are looking for tokenizer.add_special_tokens_sequence_pair instead of tokenizer.add_special_tokens_sentences_pair?

```
from transformers import RobertaTokenizer
tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

tokenizer.add_special_tokens_sequence_pair([31414], [31414])
```
This returns <br>
```
[0, 31414, 2, 2, 31425, 2]
```

**Comment by frankfka** [comment]
> Hey @frankfka
> 
> Perhaps you are looking for tokenizer.add_special_tokens_sequence_pair instead of tokenizer.add_special_tokens_sentences_pair?
> 
> ```
> from transformers import RobertaTokenizer
> tokenizer = RobertaTokenizer.from_pretrained("roberta-base")
> 
> tokenizer.add_special_tokens_sequence_pair([31414], [31414])
> ```
> 
> This returns
> 
> ```
> [0, 31414, 2, 2, 31414, 2]
> ```

Good catch, thanks! I suppose this was renamed in this release?
