### ISSUE TITLE
convert pytorch checkpoints to TF1.x checkpoints (reverse of transformers-cli convert)

### ISSUE THREAD

**Issue by fangli08** [huggingface/transformers#13426]
# 🚀 Feature request

Hello, 
Some BERT models were pre-trained using Huggingface/Facebook/NIVIDA's implementations and only have `pytorch.bin`. I am wondering if I can convert the checkpoints to  TF1.x (compatible with google's BERT https://github.com/google-research/bert).

**Comment by LysandreJik** [comment]
Hello! We don't have a conversion script capable of doing that. Is there a feature of google-research/bert we could implement to make your life easier with `transformers` ?

**Comment by fangli08** [comment]
This is simply for comparison reasons. We want to see if there is a performance difference due to the implementation. 

By the way, I also tried to convert the PyTorch checkpoint to TF2 using the `convert_pytorch_checkpoint_to_tf2.py` script. But I got this error:

```
$ python convert_pytorch_checkpoint_to_tf2.py 
Traceback (most recent call last):
  File "convert_pytorch_checkpoint_to_tf2.py", line 21, in <module>
    from . import (
ImportError: attempted relative import with no known parent package
```

I am using transformers v4.10.0 and I have installed this package. 

Thanks! 
Li

**Comment by fangli08** [comment]
By the way, my python version is 3.8.11
I am using ubuntu 18.04

**Comment by fangli08** [comment]
> Is there a feature of google-research/bert we could implement to make your life easier with transformers? 

the `run_classifier.py` script supports input of tsv text. the `datasets` library of huggingface only supports csv format. tsv format is easier to parse than csv format.
