### ISSUE TITLE
Please add GPT Jaaye model ine right with Transformers website

### ISSUE THREAD

**Issue by danish9129** [huggingface/transformers#13428]
Please add GPT Jaaye AI model to use in right with Transformers website to write text because this model has 6 billion parameters and you can scale it up to 40 billion parameters to find this model you can go to GitHub and search for GPTJ

**Comment by chris-aeviator** [comment]
GPT J is already part of the transformer library  https://huggingface.co/EleutherAI/gpt-j-6B - you may need to install the master branch (`pip install git+https://github.com/huggingface/transformers` )
