### ISSUE TITLE
A dead link in GPT2 description

### ISSUE THREAD

**Issue by shabie** [huggingface/transformers#13434]
I see that there is a dead link in the GPT2 description for some time referring to an argument on how pre-computed values can be reused.

The link to the description with the dead link (the 3rd tip): https://huggingface.co/transformers/model_doc/gpt2.html

The link that is dead: https://huggingface.co/transformers/quickstart.html#using-the-past

My suggestion is that if this quickstart page does not exist anymore than just linking it to the `forward` function docs on the same page (that has the parameter `past_key_values`) should do the job.

As you are taking care of the docs @sgugger, I can make a PR to do this if it makes sense to you.

**Comment by sgugger** [comment]
Thanks for reporting, feel free to open a PR with your change indeed!

**Comment by shabie** [comment]
So I have made a PR. One problem I did find however was the inconsistency between the TF and PT arguments.

In PT it is called `past_key_values` and in TF it is simply called `past`. I have made this clear in the PR for the docs but it would be nice if they hadn't diverged.

However, fixing this is problematic since this would be a breaking change (probably the reason it i still there :D)

**Comment by sgugger** [comment]
The way you did it is great! I think the divergence comes from when we unified that argument on the PyTorch side a while ago (it was different names for different models), but forgot to do the same on the TF side.
