### ISSUE TITLE
RobertaTokenizer documentation is off with the new transformers library

### ISSUE THREAD

**Issue by cformosa** [huggingface/transformers#1343]
## 🐛 Bug

Model I am using (Bert, XLNet....): Roberta

Language I am using the model on (English, Chinese....): NA

The problem arise when using:
* [ ] the official example scripts:

The tasks I am working on is:
NA

## To Reproduce

In the documentation for the tokenization_roberta.py, it says in the RobertaTokenizer class

```
    RoBERTa BPE tokenizer, derived from the GPT-2 tokenizer. Peculiarities:
        - Byte-level Byte-Pair-Encoding
        - Requires a space to start the input string => will add a space is there isn't.
          As a consequence, this tokenizer `encode` and `decode` method will not conserve
          the absence of a space at the beginning of a string: `tokenizer.decode(tokenizer.encode("Hello")) = " Hello"
```
However, with using the new transformers library, when I run this example I get
```
from transformers import RobertaTokenizer
tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

tokenizer.decode(tokenizer.encode("Hello"))
"Hello"
```
The leading space seems to no longer present as it was in pytorch_transformers, however if (per the source code) if I add the arg add_prefix_space = True, then it outputs with the leading space. Just a tiny fix to hopefully help out anyone else who gets confused by it.

Thanks and love the new updates to the library!

**Comment by LysandreJik** [comment]
You're right! Thanks for letting us know.
