### ISSUE TITLE
T5Tokenizer.from_pretrained("t5-small") returning NoneType

### ISSUE THREAD

**Issue by santoshnlp** [huggingface/transformers#13450]
## Environment info

- `transformers` version:
- Platform:
- Python version:  Python 3.7.11
- PyTorch version (GPU?):  1.9.0+cu102
- Tensorflow version (GPU?): 2.6.0

-Google colab

### Who can help
@patrickvonplaten, @patil-suraj @sgugger @LysandreJik

Models:

-   t5: @patrickvonplaten, @patil-suraj

Library:

- text generation: @patrickvonplaten
- tokenizers: @LysandreJik

Examples:

- maintained examples (not research project or legacy): @sgugger, @patil-suraj

 -->

## Information

Model I am using (Bert, XLNet ...): t5

The problem arises when using:
* [ ] the official example scripts: (give details below)
tokenizer = T5Tokenizer.from_pretrained("t5-small")

## To reproduce

using google colab
1.  tokenizer = T5Tokenizer.from_pretrained("t5-small")  as in
https://huggingface.co/transformers/model_doc/t5.html#transformers.T5Tokenizer
2. type(tokenizer)  -->NoneType 

## Expected behavior
tokenizer should not be NoneType

**Comment by patil-suraj** [comment]
Hi there, 

PLEASE, do not tag so many people in an issue, usually just tag one or two maintainers. Tagging everyone will unnecessarily disturb. While we  are happy to answer, we would expect people to consider this before opening an issue. Thanks.

Now regarding your issue, did you install `sentencpiece` ? If not the you could
```pip install sentencepiece```
and restart the colab.

**Comment by santoshnlp** [comment]
hi Suraj,
       Thanks. It is working.
