### ISSUE TITLE
Upcasting of attention computation for reliable pretraining of GPT-2 models

### ISSUE THREAD

**Issue by lvwerra** [huggingface/transformers#13463]
# 🚀 Feature request

In a recent [talk](https://youtu.be/AYPOzc50PHw?t=3662) about pretraining language models as part of the [Mistral](https://github.com/stanford-crfm/mistral/) project @siddk mentioned that in order to achieve stable pretraining a slight modification in the GPT-2 code is necessary. The issue is a numerical instability when training with mixed precision in the attention mechanism which can be solved by upcasting the attention computation (see [here](https://github.com/stanford-crfm/mistral/blob/53ebb290e55fe367dcaebb54ab63de4a137802db/src/models/mistral_gpt2.py#L324)).

## Motivation

Enable reliable pretraining of GPT-2 models.

## Your contribution

I can create a PR if adding this is an option.

cc @thomwolf

**Comment by osanseviero** [comment]
Also related are https://github.com/huggingface/huggingface_hub/issues/300 and https://github.com/stanford-crfm/mistral/issues/86

**Comment by siddk** [comment]
Hey folks, sorry I'm late to the party. Replying here to just to centralize things.

The upcasting + scaled-dot product attn reordering implemented in Mistral is a pretty straightforward tweak on top of the existing GPT-2 model definition in `transformers`. The only other change we made was the weight initialization procedure for GPT-2 models, which shouldn't affect anyone downstream.

If you give me a day or two, I can do the following:
- Submit a PR to `transformers` with a flag for turning on "mistral" (upcasting of scaled-dot product attention)
- Edit the GPT2Config and Arguments to reflect this flag... ensure `.from_pretrained()` works as expected.
- Fix the GPT2 weight initialization.

This would 1) be simple, 2) be easy for anyone looking to use the Mistral models in the future, and 3) would stop us from defining a new "MistralGPT" class (which we might do anyway for v2 when we add other types of parallelism and the like.

What do y'all think?

@osanseviero @lvwerra @thomwolf @LysandreJik

**Comment by lvwerra** [comment]
Hi @siddk, that sounds good to me. I would like to start training a larger model in the coming days so that would be very welcome on my side :)
