### ISSUE TITLE
[Errno 13] Permission denied: '/.cache'

### ISSUE THREAD

**Issue by RachelDong** [huggingface/transformers#13472]
Hello,

I'm using the Dialo-GPT model:
```
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
model_name = "microsoft/DialoGPT-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)
```
When I run the above code in server, the error throws:
```
[Errno 13] Permission denied: '/.cache'
```
Does anyone know how to solve this problem? Thanks a lot.

**Comment by patil-suraj** [comment]
It seems like the `/.cache` directory is not writable, you could try changing permissions or you could tell transformers to use a different dir for cache by setting the env variable `HF_HOME`

**Comment by RachelDong** [comment]
Yes thank you for the answer:)
