### ISSUE TITLE
Cannot run Movement pruning on GLUE

### ISSUE THREAD

**Issue by zheng-ningxin** [huggingface/transformers#13487]
## Environment info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 2.8.0
- Platform: Linux-4.15.0-136-generic-x86_64-with-glibc2.17
- Python version: 3.8.11
- PyTorch version (GPU?): 1.9.0+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

## Information

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

I try to reproduce the movement pruning on the GLUE dataset and install the dependent packages following the `requirements.txt`, I try to run the `masked_run_glue.py` by the following commands:

```
SERIALIZATION_DIR=./finegrained_bert_0.95
GLUE_DATA=~/data-bin/glue_data/QQP

CUDA_VISIBLE_DEVICES=1 python masked_run_glue.py \
    --output_dir $SERIALIZATION_DIR \
    --data_dir $GLUE_DATA \
    --task_name qqp \
    --do_train --do_eval --do_lower_case \
    --model_type masked_bert \
    --model_name_or_path bert-base-uncased \
    --per_gpu_train_batch_size 16 \
    --warmup_steps 5400 \
    --num_train_epochs 10 \
    --learning_rate 3e-5 --mask_scores_learning_rate 1e-2 \
    --initial_threshold 1 --final_threshold 0.15 \
    --initial_warmup 1 --final_warmup 2 \
    --pruning_method topK --mask_init constant --mask_scale 0.
```
 and I get the following errors:
```
Traceback (most recent call last):
  File "masked_run_squad.py", line 33, in <module>
    from emmental import MaskedBertConfig, MaskedBertForQuestionAnswering
  File "/root/transformers/examples/research_projects/movement-pruning/emmental/__init__.py", line 3, in <module>
    from .modeling_bert_masked import (
  File "/root/transformers/examples/research_projects/movement-pruning/emmental/modeling_bert_masked.py", line 31, in <module>
    from transformers.file_utils import add_start_docstrings, add_start_docstrings_to_model_forward
ImportError: cannot import name 'add_start_docstrings_to_model_forward' from 'transformers.file_utils' (/root/transformers/examples/research_projects/movement-pruning/src/transformers/src/transformers/file_utils.py)
```

**Comment by dorost1234** [comment]
Hi @zheng-ningxin 
I have the exact same issue, do you mind telling me how you solved this? thanks

**Comment by zheng-ningxin** [comment]
@dorost1234  Please have a try on version 4.9.0.

**Comment by jackfeinmann5** [comment]
Hi @zheng-ningxin 
I am trying to use this method, for me this does not work at all, since you seems to have worked on this code, could you let me know if you could obtain the results on GLUE? thanks
