### ISSUE TITLE
Package transformers.onnx should handle Tensorflow

### ISSUE THREAD

**Issue by Albertobegue** [huggingface/transformers#13534]
# 🚀 Feature request

The package transformers.onnx should allow the conversion of tensorflow models as well as Pytorch's. 

## Motivation

[This documentation](https://huggingface.co/transformers/serialization.html) features the following code snippet 

```

python -m transformers.onnx --help

usage: Hugging Face ONNX Exporter tool [-h] -m MODEL -f {pytorch} [--features {default}] [--opset OPSET] [--atol ATOL] output

positional arguments:
  output                Path indicating where to store generated ONNX model.

optional arguments:
  -h, --help            show this help message and exit
  -m MODEL, --model MODEL
                        Model's name of path on disk to load.
  --features {default}  Export the model with some additional features.
  --opset OPSET         ONNX opset version to export the model with (default 12).
  --atol ATOL           Absolute difference tolerance when validating the model.
```

which introduces the new package transformers.onnx. It also says: "This conversion is handled with the PyTorch version of models - it, therefore, requires PyTorch to be installed. If you would like to be able to convert from TensorFlow, please let us know by opening an issue." so here I am, opening an issue :) 

I have been converting Tensorflow models with ONNX for a while but I am not observing the same time-saving as expected and described by various references, mainly using Pytorch though (like this one: https://medium.com/microsoftazure/accelerate-your-nlp-pipelines-using-hugging-face-transformers-and-onnx-runtime-2443578f4333). Therefore, I am eager to try this new package for my conversions but I cannot currently because we use Tensorflow.

## Your contribution

I would be very keen to contribute to this development but as it would be my first contribution to transformers I would very much appreciate any guidance on how to do it and what to read!

Thank you :))

**Comment by LysandreJik** [comment]
Thank you for the feature request! We'll prevent the stale bot from closing that PR and see if there is a lot of interest in this addition.

**Comment by lewtun** [comment]
Closing this since PR #13831 implemented the feature :)
