### ISSUE TITLE
Joint Sequence and Token Classification

### ISSUE THREAD

**Issue by will-rice** [huggingface/transformers#13533]
# 🚀 Feature request
A common NLU task for voice assistants and chatbots is intent classification and slot filling. This can be modeled as a joint task via a model like [BERT](https://arxiv.org/abs/1902.10909). The implementation is essentially a token classification head along with a sequence classification head attached to a pre-trained encoder. 

## Motivation

I think this could be a good addition because it would allow the upload of joint slot/intent models and allow a common NLU task to be added to pipelines. Furthermore, this would enable audio encoder models like Wav2Vec2 to be used for End-to-End SLU tasks like [this](https://arxiv.org/abs/1904.03670). 

## Your contribution

I would be open to contributing the implementation to BERT and uploading pre-trained NLU/SLU models on mainstream benchmarks like [snips](https://arxiv.org/abs/1805.10190v3) if other members of the community would benefit.

**Comment by LysandreJik** [comment]
Hello @will-rice, we're currently working on a feature to enable loading sharing and loading custom architectures like the one you mention cc @sgugger.

We'll let you know as soon as it's ready for testing so that you may take a look and let us know if it's helpful.
