### ISSUE TITLE
How to use transformers pipeline with multi-gpu?

### ISSUE THREAD

**Issue by Deep-sea-boy** [huggingface/transformers#13557]
`ner_model = pipeline('ner', model=model, tokenizer=tokenizer, device=0, grouped_entities=True)`

the device indicated pipeline to use no_gpu=0(only using GPU), please show me how to use multi-gpu.

**Comment by cylnlp** [comment]
same question...

**Comment by Narsil** [comment]
Currently this information is not supported.

You could to `n pipelines` on the `n` devices as a workaround, would that work ?
