### ISSUE TITLE
Support for SuperGLUE fine-tune/eval?

### ISSUE THREAD

**Issue by julien-c** [huggingface/transformers#1357]
## 🚀 Feature

https://super.gluebenchmark.com/

Current canonical implem is https://github.com/nyu-mll/jiant/

## Motivation

https://twitter.com/_florianmai/status/1177489945918722050

**Comment by jiachangliu** [comment]
So is HuggingFace going to write the finetuning implementation for SuperGlue?

**Comment by estelleaf** [comment]
Hi @jiachangliu, did you have any news about support for superglue?

**Comment by jiachangliu** [comment]
> Hi @jiachangliu, did you have any news about support for superglue?

No I have not heard any HugginFace support on SuperGlue. It was not urgent for me to run those experiments. However, if you want to run SuperGlue, I guess you need to install JIANT, which uses the model structures built by HuggingFace.

**Comment by estelleaf** [comment]
> > Hi @jiachangliu, did you have any news about support for superglue?
> 
> No I have not heard any HugginFace support on SuperGlue. It was not urgent for me to run those experiments. However, if you want to run SuperGlue, I guess you need to install JIANT, which uses the model structures built by HuggingFace.

Thank you !!
