### ISSUE TITLE
Option to serialize tokenizers in memory instead of to a directory

### ISSUE THREAD

**Issue by justinaustin** [huggingface/transformers#13584]
# 🚀 Feature request
Hello!

It would be useful to serialize tokenizers to bytes in memory instead of having to write to a directory. [`PreTrainedModel.save_pretrained`](https://huggingface.co/transformers/internal/tokenization_utils.html#transformers.tokenization_utils_base.PreTrainedTokenizerBase.save_pretrained) only takes in a `save_directory`, where ideally it would also accept a [`BytesIO`](https://docs.python.org/3/library/io.html#io.BytesIO) or similar to serialize in memory (or there would be another method to call for this).

## Motivation

We're trying to integrate `transformers` with some existing software that handles signing serialized models for security. We're able to save to a directory on the local filesystem and then read the bytes back into memory, but it would be nice to avoid that and serialize directly to an in-memory BytesIO object. Also, this would expose a more flexible API that would make it easier for others using this great package to export their models.

## Your contribution

Unfortunately, I'm not familiar with the internals of the package and just wanted to see the feasibility of this. I'm happy to help however I can, especially if the change wasn't too involved. Thank you!

**Comment by qqaatw** [comment]
Hi @justinaustin, how about pickling it?

The following code works for me:
```
import pickle
import torch
import transformers
from transformers import BertTokenizer, BertModel

print('PyTorch version:', torch.__version__, ' transformers version:', transformers.__version__)

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased", additional_special_tokens=["[SP]"])
print(tokenizer("Hello World[SP]!"))

pickled_tokenizer = pickle.dumps(tokenizer)
tokenizer = pickle.loads(pickled_tokenizer)
print(tokenizer("Hello World[SP]!"))
```

**Comment by justinaustin** [comment]
Thank you for the suggestion @qqaatw ! Pickling is a great short-term solution for us. We hesitate to use pickle long-term because of brittleness between different Python versions and potential security concerns when deserializing.

It's just unfortunate that there's already a great serialization framework within transformers that takes care serializing to well-defined json and text files but you're unable to use if you want to avoid writing intermediate files to disk.

**Comment by qqaatw** [comment]
I understand your concern. However, I think currently pickling is the only way to serialize entire tokenizer, and this approach is tested in the unit test of `transformers`. Additionally, you may find that the loading and saving utilities of PyTorch also leverage `pickle` package to process serialization so I believe pickling still remain somewhat of reliabilities to complete these general things.
