### ISSUE TITLE
 Unrecognized configuration class <class 'transformers.models.distilbert.configuration_distilbert.DistilBertConfig'> for this kind of AutoModel: AutoModelForSeq2SeqLM.

### ISSUE THREAD

**Issue by Azitt** [huggingface/transformers#13590]
I'm trying to use translate notebook with model_checkpoint = "distilbert-base-uncased" but it gives me below error:

![image](https://user-images.githubusercontent.com/32965166/133535533-0e18f5ec-4542-4494-8a78-862cd90e8e03.png)

any idea what is wrong?

## Environment info

- `transformers` version: distilbert
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by LysandreJik** [comment]
Hello! DistilBERT is not a seq2seq model, hence why there's no seq2seq architecture for that model!
