### ISSUE TITLE
Inconsistency in  class naming

### ISSUE THREAD

**Issue by sadakmed** [huggingface/transformers#13596]
@patrickvonplaten

in `modeling_utils.py` the pretrained model class is written as `PreTrainedModel` While in `configuration_utils` the pretrained config class is named as `PretrainedConfig`
https://github.com/huggingface/transformers/blob/421929b556aedf022a1c4a1f3b2f116b14a7b88a/src/transformers/modeling_utils.py#L413

https://github.com/huggingface/transformers/blob/421929b556aedf022a1c4a1f3b2f116b14a7b88a/src/transformers/modeling_utils.py#L30

and not just that, in `transformers` there's `PretrainedFSMTModel, PretrainedBartModel, PreTrainedModel, PretrainedConfig, PreTrainedTokenizer`
and some part of the documentations
https://github.com/huggingface/transformers/blob/421929b556aedf022a1c4a1f3b2f116b14a7b88a/src/transformers/modeling_utils.py#L425-L433

Edit:
Also in the `transformers.__init__.py` there's this type of inconsistency 

example:

https://github.com/huggingface/transformers/blob/421929b556aedf022a1c4a1f3b2f116b14a7b88a/src/transformers/__init__.py#L728

https://github.com/huggingface/transformers/blob/421929b556aedf022a1c4a1f3b2f116b14a7b88a/src/transformers/__init__.py#L580

**Comment by patrickvonplaten** [comment]
Hey @sadakmed,

Very good observation! We are aware of these slightly different names :-) However it would create quite some problems with backward compatibility so that we decided to leave as is. Hope this is ok for you!

**Comment by sadakmed** [comment]
> However it would create quite some problems

Totally agree, it's ok for me anyway!
