### ISSUE TITLE
ResourceExhaustedError: Failed to allocate request for 64.00MiB (67108864B) on device ordinal 0

### ISSUE THREAD

**Issue by Jassy87** [huggingface/transformers#13629]
I'm training an XLM model from huggingface on a small dataset using Colab TPU. However, I get the following error:
<ResourceExhaustedError: Failed to allocate request for 64.00MiB (67108864B) on device ordinal 0>

I tried reducing the batch size and restarting the kernel and freeing memory but nothing is working.
Any help would be appreciated.

**Comment by rojagtap** [comment]
Can you give some additional info? like the number of layers and the batch size?

**Comment by Jassy87** [comment]
I'm following this notebook ->https://www.kaggle.com/dimasmunoz/text-classification-with-roberta-and-tpus
I've tried Roberta, BERT, DistilBert and all working okay on my dataset. Except for XML !

**Comment by Jassy87** [comment]
Worked fine for the EnghlishGerman model "xlm-mlm-ende-1024" with 6 layers, 8 heads
