### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by dingusagar** [huggingface/transformers#13638]
https://huggingface.co/transformers/model_doc/distilbert.html
In this page, under the paragraph,

_This model was contributed by victorsanh. This model jax version was contributed by kamalkraj. The original code can be found [here](https://github.com/huggingface/transformers/blob/master/examples/research-projects/distillation)._

The link to the original code is broken.

**Comment by LysandreJik** [comment]
Fixed by #13643
