### ISSUE TITLE
[typo] invalid URL

### ISSUE THREAD

**Issue by Freed-Wu** [huggingface/transformers#13635]
In <https://github.com/huggingface/transformers/blob/master/docs/source/training.rst?plain=1#L36>

```
We will use the `🤗 Datasets <https:/github.com/huggingface/datasets/>`__ library to download and preprocess the IMDB
```

Correct URL should be <https://github.com/huggingface/datasets/>.

**Comment by LysandreJik** [comment]
Closed by #13644
