### ISSUE TITLE
Auto model for conditional generation

### ISSUE THREAD

**Issue by sadakmed** [huggingface/transformers#13648]
# 🚀 Feature request

The majority of tasks (CausalLM, QuestionAnswering...) have the option to be loaded without importing the specific architecture of the model with `AutoModel` yet for  `ConditionalGeneration`  you need to import the specific class.

is there a technical reason restraining such an implementation?

**Comment by sadakmed** [comment]
If you can confirm that this would be a good plus, I can push my modification for this.

**Comment by LysandreJik** [comment]
Hello! These models are available in `AutoModelForSeq2SeqLM`!
