### ISSUE TITLE
Tried to import  TFBertForPreTraining in google colab

### ISSUE THREAD

**Issue by mandavachetana** [huggingface/transformers#1368]
Tried to import TFBertForPreTraining and received an error

from transformers import BertTokenizer, TFBertForPreTraining
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-24-91f8709e090f> in <module>()
----> 1 from transformers import BertTokenizer, TFBertForPreTraining

ImportError: cannot import name 'TFBertForPreTraining'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by cformosa** [comment]
Hey @mandavachetana its not just a google colab thing. Take a look here #1375 You need to make sure you are using tensorflow 2.0 and it should work.
