### ISSUE TITLE
Wav2vec2 pretraining

### ISSUE THREAD

**Issue by aniket7joshi** [huggingface/transformers#13685]
How can I pretrain the base wav2vec2 model using the *transformers.Wav2Vec2ForPreTraining* class on my own data?
I saw the example given on the official website -https://huggingface.co/transformers/model_doc/wav2vec2.html#wav2vec2forpretraining
But it wasn't of much help. Is there any notebook or script which I can follow?

**Comment by flozi00** [comment]
https://github.com/huggingface/transformers/blob/master/examples/research_projects/wav2vec2/run_pretrain.py

Does this script helps you ?

**Comment by LysandreJik** [comment]
cc @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @aniket7joshi,

I'm currently working on it. Hope to have a good blog/notebook in 2,3 weeks!

**Comment by patrickvonplaten** [comment]
I'll let you know :-)

**Comment by patrickvonplaten** [comment]
Wav2vec2 Pretraining at the moment only works for PyTorch. I want to make it work for Flax to be able to showcase it nicely in a google colab with 8 TPUs. Still working on it!

**Comment by aniket7joshi** [comment]
Hey @patrickvonplaten Can you please share any notebook or resource which I can use to pre-train wav2vec2 using pytorch?

**Comment by aniket7joshi** [comment]
Hey @patrickvonplaten Can you help me as to how I use the script here: https://github.com/huggingface/transformers/blob/master/examples/research_projects/wav2vec2/run_pretrain.py

As input, I have a folder of audio files based on which I want to pretrain my model. I don't want to use any datasets available online or on huggingface. 
TIA :)

**Comment by patrickvonplaten** [comment]
Planning to look into this again in 2 weeks
