### ISSUE TITLE
Wav2vec2 with different tokenizer ?

### ISSUE THREAD

**Issue by Shiro-LK** [huggingface/transformers#13695]
Hello,

thank you for having make wav2vec compatible with the transformer package.
I have a question regarding the tokenizer part. By default, the tokenizer is doing prediction at character level. I wanted to know if it is possible to use similar tokenizer than the one use in NLP such as the RobertaTokenizer ? (Or other one based on sentence piece/word piece)

I tried to use the roberta tokenizer for example but got an error with the processor : 

> ValueError: `tokenizer` has to be of type <class 'type'>, but is <class 'transformers.models.roberta.tokenization_roberta.RobertaTokenizer'>

Is it possible to use a different tokenizer than char level with this wav2vec implementation ?

**Comment by OllieBroadhurst** [comment]
[This](https://huggingface.co/transformers/master/model_doc/speechencoderdecoder.html) could be of interest to you. Notice the examples given, you can use the [Speech2Text2Processor](https://huggingface.co/transformers/master/model_doc/speech_to_text_2.html#speech2text2processor) to wrap the feature extractor and the tokenizer you want to use.

**Comment by patrickvonplaten** [comment]
Hey @Shiro-LK,

When using `Wav2Vec2ForCTC` then it is necessary to use the `Wav2Vec2Tokenizer` which operates on the char level. In order to use a Roberta-like tokenizer, one should probably use the `SpeechEncoderDecoder` framework with `Wav2Vec2` being the encoder and roberta the decoder.
