### ISSUE TITLE
Pipeline “zero-shot-classification” gives “TypeError: __call__() takes 2 positional arguments but 3 were given.”

### ISSUE THREAD

**Issue by Jcwscience** [huggingface/transformers#13697]
- `transformers` version: 4.11.0.dev0
- Platform: Linux-4.9.253-rt168-tegra-aarch64-with-debian-buster-sid
- Python version: 3.6.13
- PyTorch version (GPU?): 1.9.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: (True)
- Using distributed or parallel set-up in script?: (False)

@LysandreJik

## Information

Model I am using (‘facebook/bart-large-mnli’):

The problem arises when using:
the official example scripts: (basically)

```python
from transformers import pipeline

classify=pipeline('zero-shot-classification')

text=("Give me a weather report")
tags=["request_weather", "catch_fire"]

classify(text, tags)
```

The tasks I am working on is:
my own task or dataset:

It’s a bunch of ugly hacks on each other’s shoulders, in a trench coat, masquerading as a Python script.

## To reproduce

1. Run script

Result:

```bash
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    classify(text, tags)
TypeError: __call__() takes 2 positional arguments but 3 were given
```

## Expected behavior

Literally anything but this. I am very confused. Please help, very much appreciated, getting gray hairs from this, thanks!

**Comment by LysandreJik** [comment]
Hello, it seems that there is an issue indeed, the argument is not recognized unless it is a keyword argument (cc @Narsil)

You can do the following in order to have your code work:
```py
classify(text, candidate_labels=tags)
```
which will output
```
{'sequence': 'Give me a weather report', 'labels': ['request_weather', 'catch_fire'], 'scores': [0.9743501543998718, 0.02564983256161213]}
```

**Comment by Jcwscience** [comment]
@LysandreJik Ahh, ok so that’s what was happening. I’ll be curious to know when you find out what caused it. Thanks for the fix!

**Comment by Narsil** [comment]
Hi @Jcwscience ,

There was a bit rework of pipelines to enable new features (GPU streaming most importantly), and this specific call option wasn't tested so we forgot to account for it.

FYI, in return we enabled this:

```python
classify=pipeline('zero-shot-classification', candidate_labels=["request_weather", "catch_fire"])

classify("text")
classify("something")
```

**Comment by Jcwscience** [comment]
@Narsil 
Makes sense. Happens to my code about 3 times a day. I was honestly thrilled that I wasn't just doing something stupid! Thanks!

**Comment by Narsil** [comment]
We will make a PR to fix that too.

**Comment by Narsil** [comment]
PR is up for review.
