### ISSUE TITLE
Fine-tuning GPT-J 6B with 16Gb of VRAM

### ISSUE THREAD

**Issue by zgerrard** [huggingface/transformers#13698]
Hi

I am trying to fine-tune GPT-J 6B with 16Gb of VRAM. Do you have any ideas/pointers on what can be done to lower the amount of VRAM needed for fine-tuning?

@StellaAthena @EricHallahan

**Comment by zgerrard** [comment]
I've tried DeepSpeed with Zero-3 and Zero-Offload, and the model still doesn't fit.

**Comment by StellaAthena** [comment]
Try checking out the instructions [here](https://github.com/kingoflolz/mesh-transformer-jax/blob/master/howto_finetune.md)
