### ISSUE TITLE
Documentation Mistake: no_multi_processing for Benchmarks

### ISSUE THREAD

**Issue by liaeh** [huggingface/transformers#13713]
The documentation on setting the argument [no_multi_processing during benchmarking](https://huggingface.co/transformers/v4.0.1/benchmarks.html#benchmark-best-practices) is unclear: _The option **no_multi_processing should only be set to True** for testing and debugging. To ensure accurate memory measurement it is recommended to run each memory benchmark in a separate process by making sure **no_multi_processing is set to True**._

From looking at the [docstrings in benchmark_args_utils.py](https://github.com/huggingface/transformers/blob/master/src/transformers/benchmark/benchmark_args_utils.py#L86), no_multi_processing should only be set to False for testing and debugging.

**Comment by LysandreJik** [comment]
Pinging @patrickvonplaten as the author of https://github.com/huggingface/transformers/pull/5360
