### ISSUE TITLE
How can i Use transformers to classify a obfuscated text (multinomial classification)

### ISSUE THREAD

**Issue by santhoshcameo** [huggingface/transformers#13719]
## Model description

I have a train data which contains many obfuscated sentences associated with its labels, so how can I use Transformers to classify them ?

one sample raw is given here. Please help.

`twypmviwskuhpmuluhlrvimvvilekruluhqgskmvenqvuhletwululenlpuhtwamuluhijohultwsauhtwiwskskmvleuhtwamuluhsktwqvqvtwkrlruhkrpmsauhtwmkenlpkguhijraxeiwtwqvsaezuhucleeneztwleuhpmuluhlrvimvpmlruhqvendfuhiguhulenamdfuhulqvkrbruhpktwqvlekrpmypuhxepmuhqgtwqvlekrpmypuhxeyvkguhqgqvtwsatwuhqvulmvuhlrvimvvitwgzpmuhulkrpmamulmvdfuhqgskmvenqvuhskvienuhqgsaiwulvitwmvulengzezmvuhskentwamuhqvulmvuhucpmpmamqvuhtwqvkrpmezlepmmcuhtwamgu`

note: as you see the single document contains no spaces and no words etc. this is labeled as 1, and like this many other lines which are respectively labeled from 1 to 10.

Please advice.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
