### ISSUE TITLE
FNet model card

### ISSUE THREAD

**Issue by stefan-it** [huggingface/transformers#13748]
Hi guys,

I think that the current FNet model cards both for [fnet-base](https://huggingface.co/google/fnet-base) and [fnet-large](https://huggingface.co/google/fnet-large) are a bit misleading:

```text
This model is uncased: it does not make a difference between english and English.
```

After manually inspecting the original sentencepiece vocab from:

```
https://storage.googleapis.com/gresearch/f_net/vocab/c4_bpe_sentencepiece.model
```
and the version on model hub, it seems that the vocab is cased instead:

![image](https://user-images.githubusercontent.com/20651387/134800605-10536560-5a64-4530-92e1-433de1be50ac.png)

And the tokenizer itself also produces a cased output:

![image](https://user-images.githubusercontent.com/20651387/134800649-adc1e635-79a0-414b-a676-6b9b98bf1cfa.png)

So I think the model card should be updated then :hugs:

**Comment by gchhablani** [comment]
@stefan-it I made a mistake there. Sorry, I'll fix it.

**Comment by stefan-it** [comment]
Many thanks for the fix 🤗

**Comment by gchhablani** [comment]
Thanks @stefan-it for pointing it out :)
