### ISSUE TITLE
using translate notebook for my dataset I get this error : ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.

### ISSUE THREAD

**Issue by Azitt** [huggingface/transformers#13744]
I'm trying to finetune the model in translate notebook for my data.. in trainer.train() part I receive this error: 

![image](https://user-images.githubusercontent.com/32965166/134790175-e89ff5b5-2aa4-4651-8c93-7f45db91c0fc.png)

I added 'padding=True' 'truncation=True' to the tokenizer but it's still the same.

![image](https://user-images.githubusercontent.com/32965166/134790466-41182826-ebb9-4c9d-b4b3-97879cf023d6.png)

any idea/suggestion to fix the problem would be appreciated.

## Environment info

- `transformers` version: translate notebook
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by LysandreJik** [comment]
Hello, could you please provide a reproducible code example, library version, and everything required by the issue template? Thanks.

**Comment by Azitt** [comment]
# -*- coding: utf-8 -*-
"""Text2Text_fa_en2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iwmHD8rQazwoqjjlfrokfnqLZ9bYyhhg
"""

!pip install datasets transformers sacrebleu==1.5.1
#!pip3 install sentencepiece
!pip3 install transformers sentencepiece

import transformers
print(transformers.__version__)

#model_checkpoint = "distilbert-base-uncased"
model_checkpoint = "sshleifer/tiny-mbart"

from google.colab import drive
drive.mount('/content/gdrive/')

from datasets import load_dataset, load_metric
raw_datasets = load_dataset('json', data_files="/content/gdrive/MyDrive/translate-English-demo/dataset_translate/faen_translate.json", field='translation')
metric = load_metric("sacrebleu")

raw_datasets

raw_datasets['train'][0]

import datasets
import random
import pandas as pd
from IPython.display import display, HTML

def show_random_elements(dataset, num_examples=5):
    assert num_examples <= len(dataset), "Can't pick more elements than there are in the dataset."
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset)-1)
        while pick in picks:
            pick = random.randint(0, len(dataset)-1)
        picks.append(pick)
    
    df = pd.DataFrame(dataset[picks])
    for column, typ in dataset.features.items():
        if isinstance(typ, datasets.ClassLabel):
            df[column] = df[column].transform(lambda i: typ.names[i])
    display(HTML(df.to_html()))

show_random_elements(raw_datasets["train"])

import re
chars_to_ignore_regex = '[\,\?\.\!\-\;\:\"\“\%\‘\”\�]'

def remove_special_characters(batch):
    batch["fa"] = re.sub(chars_to_ignore_regex, '', batch["fa"]).lower() + " "
    return batch

raw_datasets = raw_datasets.map(remove_special_characters)

show_random_elements(raw_datasets["train"])

metric

fake_preds = ["سلام", "hello"]
fake_labels = [["سلام"], ["hello"]]
metric.compute(predictions=fake_preds, references=fake_labels)

from transformers import AutoTokenizer    
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

!pip install parsivar

from parsivar import Tokenizer
fa_tokenizer = Tokenizer()

vocab_dict = {'ـ': 0, 'm': 1, 'ﭘ': 2, 'آ': 3, 'ﺑ': 4, '؛': 5, 'y': 6, 'u': 7, ' ': 8, 'z': 9, 'ى': 10, 'ﯾ': 11, 'ﺧ': 12, 'ﺭ': 13, 'خ': 14, 'چ': 15, '؟': 16, 'ً': 17, 'ۀ': 18, 'ئ': 19, 'ﻌ': 20, 's': 21, 'h': 22, 'ْ': 23, 'ﺖ': 24, 'q': 25, 'ā': 26, 'س': 27, 'c': 28, 'ﺷ': 29, 'ظ': 30, '…': 31, ')': 32, 'َ': 33, 'ِ': 34, 'ژ': 35, 'e': 36, 'ب': 37, 'f': 38, 'ﯽ': 39, 'ﯿ': 40, 'ٌ': 41, 'p': 42, 'ﮔ': 43, 'م': 44, 'ﻮ': 45, 'ّ': 46, 'i': 47, 'و': 48, 'ة': 49, 'o': 50, 'گ': 51, 'ﻋ': 52, 'ف': 53, '«': 54, 'ؤ': 55, 'ج': 56, 'ُ': 57, 'ﺸ': 58, 'پ': 59, 'أ': 60, 'ي': 61, 'ﮐ': 62, 'n': 63, 'ﻧ': 64, 'ﺒ': 65, 'ﻟ': 66, 'ﺴ': 67, 'ے': 68, 'ع': 69, 'ﺮ': 70, 'ی': 71, 'ﻀ': 72, 'ﺘ': 73, 'ﺍ': 74, 'g': 75, 'ﺱ': 76, 'š': 77, 'ح': 78, 'ض': 79, 'ن': 80, 't': 81, 'b': 82, 'ک': 83, '»': 84, 'ﺎ': 85, '&': 86, '#': 87, 'ه': 88, 'ل': 89, 'ﺩ': 90, 'ك': 91, 'ز': 92, 'ر': 93, 'ﺪ': 94, 'ء': 95, 'ﻡ': 96, 'ﻭ': 97, 'ق': 98, 'k': 99, '(': 100, 'ﻥ': 101, '_': 102, 'ث': 103, 'ص': 104, 'ﻤ': 105, 'ط': 106, 'r': 107, '–': 108, 'ٔ': 109, 'ا': 110, 'd': 111, 'ت': 112, 'غ': 113, 'a': 114, 'ﻢ': 115, '٬': 116, 'ﻪ': 117, 'د': 118, 'ذ': 119, '،': 120, 'ش': 121}

vocab_dict["|"] = vocab_dict[" "]
del vocab_dict[" "]

vocab_dict["[UNK]"] = len(vocab_dict)
vocab_dict["[PAD]"] = len(vocab_dict)
print(len(vocab_dict))

import json
with open('vocab.json', 'w') as vocab_file:
    json.dump(vocab_dict, vocab_file)

fa_XX = "./vocab.json"
tokenizer.save_pretrained("fa_XX")
#tokenizer_config = get_tokenizer_config("tokenizer-test")

if "mbart" in model_checkpoint:
    tokenizer.src_lang = "fa_XX"
    tokenizer.tgt_lang = "en-XX"

tokenizer("سلام خوهستی دوست نازنینم")

tokenizer("hello how")

tokenizer(["سلام, این یک جمله است", "این یک جمله دیگر است."])

with tokenizer.as_target_tokenizer():
    print(tokenizer(["سلام, این یک جمله است", "این یک جمله دیگر است."]))

if model_checkpoint in ["t5-small", "t5-base", "t5-larg", "t5-3b", "t5-11b"]:
    prefix = "translate English to Romanian: "
else:
    prefix = " "

max_input_length = 128
max_target_length = 128
source_lang = "fa"
target_lang = "en"

def preprocess_function(examples):
   # print(examples)
     #inputs  = [examples[source_lang][ex] for ex in range (len(examples)-1)]
    # targets = [examples[target_lang][ex] for ex in range (len(examples)-1)]
    inputs = [examples[source_lang] for ex in examples]
    targets = [examples[target_lang] for ex in examples]
    #inputs = [prefix + ex[source_lang] for ex in examples["translation"]]
    #targets = [ex[target_lang] for ex in examples["translation"]]
    model_inputs = tokenizer(inputs, max_length=max_input_length, truncation=True,padding=True)

    # Setup the tokenizer for targets
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(targets, max_length=max_target_length, truncation=True,padding=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

preprocess_function(raw_datasets["train"][:2])

tokenized_datasets = raw_datasets.map(preprocess_function)

raw_datasetsvalid = load_dataset('json', data_files="/content/gdrive/MyDrive/translate-English-demo/dataset_translate/faen_validation.json", field='translation')

raw_datasetsvalid

tokenized_datasetsvalid = raw_datasetsvalid.map(preprocess_function)

tokenized_datasetsvalid

from transformers import AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainingArguments, Seq2SeqTrainer

model = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint)

batch_size = 16
model_name = model_checkpoint.split("/")[-1]
args = Seq2SeqTrainingArguments(
    #"test-translation",
    output_dir="/content/gdrive/MyDrive/translate-English-demo",   
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    evaluation_strategy = "steps",
    num_train_epochs=1,
    fp16=True,
    save_steps=10000,
    eval_steps=10000,
    logging_steps=10000,
    weight_decay=0.01,
    save_total_limit=3,    
    predict_with_generate=True,   
    #push_to_hub=False,
    #push_to_hub_model_id=f"{model_name}-finetuned-{source_lang}-to-{target_lang}",
)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

import numpy as np

def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [[label.strip()] for label in labels]

    return preds, labels

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Some simple post-processing
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
    result = {"bleu": result["score"]}

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    return result

trainer = Seq2SeqTrainer(
    model=model,
    data_collator=data_collator,
    args=args,
    compute_metrics=compute_metrics,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasetsvalid["train"],
    tokenizer=tokenizer
)

trainer.train()

text = 'Nice to meet you'
mname = 'Helsinki-NLP/opus-mt-ru-en'
#tokenizer = MarianTokenizer.from_pretrained(mname)
model = AutoModelForSeq2SeqLM.from_pretrained("/content/gdrive/MyDrive/translate-English-demo/checkpoint-30000")
input_ids = tokenizer.encode(text, return_tensors="pt")
outputs = model.generate(input_ids)
decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(decoded) #Nice to meet you

text = 'I am here'
input_ids = tokenizer.encode(text, return_tensors="pt")
outputs = model.generate(input_ids)
decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(decoded)

text = 'this is my dog'
input_ids = tokenizer.encode(text, return_tensors="pt")
outputs = model.generate(input_ids)
decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(decoded)

**Comment by Azitt** [comment]
that's the code I'm working on..it's googlecolab notebook I copy past the code but there is a colab link in there. my data is saved in my google drive, this is the format of the data:
{
  "translation": [
    {
      "fa": "ما از برنامه بهبود اقتصادی اروپا کمیسیون استقبال می کنیم.",
      "en": "We welcome the Commission's European Economic Recovery Plan."
    },
    {
      "fa": "این یک گام مهمی از فرآیند است که ما در این زمان خودمان را پیدا می کنیم.",
      "en": "It is an important step out of the morass in which we find ourselves at this time."
    },
	{
      "fa": "من باید زمان بیشتری را در راه حل های سطح ملی صرف کنم.",
      "en": "I shall spend a little more time on national-level solutions."
    }
  ]
}

**Comment by Azitt** [comment]
any update on this topic?
