### ISSUE TITLE
Scrolling through the docs has become very slow

### ISSUE THREAD

**Issue by ekdnam** [huggingface/transformers#13751]
The problem is the same as the title states. 

While scrolling through the docs, say [Pipelines](https://huggingface.co/transformers/main_classes/pipelines.html), it takes a lot of time to scroll down, which I think was not the case before.

### Who can help

@sgugger

**Comment by sgugger** [comment]
Not sure what you mean, I can scroll through that page at any speed I want.

**Comment by ekdnam** [comment]
> Not sure what you mean, I can scroll through that page at any speed I want.
Okay.

![Untitled_ Sep 26, 2021 11_37 PM (1)](https://user-images.githubusercontent.com/40426312/134819273-e3370e43-a433-47cd-847f-96296becad65.gif)

A screengrab while scrolling through the website.

**Comment by sgugger** [comment]
Maybe restarting chrome is necessary? I don't have it installed locally, but everything is fine on Edge.

**Comment by DeepP2667** [comment]
I also have this problem on chrome. Restarted it and my computer but it didn't fix it.

**Comment by LysandreJik** [comment]
That's interesting - I use chrome and an array of chromium-based browsers but have never encountered this issue. Could this be linked to one of your extensions? Does it happen on older versions of the docs? Does it also happen on other docs, for example, our datasets docs, or the PyTorch docs which also use the same backend?

**Comment by DeepP2667** [comment]
I've disabled my extensions and tried but still doesn't work. Sorry I am pretty new to programming so I don't know how to open up older versions of the documents. Do I go to a branch that is at an older release?
Also I did notice that when I used my trackpad on my computer it works fine. But I have a mouse connected to my computer and when I use the scroll on that, it causes the problem. Are you using a mouse or the trackpad?

**Comment by DeepP2667** [comment]
I am using an external mouse in the video, not the trackpad.
So I'm not exactly sure why it works with a trackpad but not a mouse, but here is a video of what seems to be happening. When I scroll over on the left hand side with the table of contents info, it works fine. The left scrollbar is separate from the right scrollbar. But when I scroll where the actual information is, the left and right scrollbar scroll at the same time. But once the left scrollbar hits the end, the right scrollbar scrolls without it slowing down. I hope that makes sense from the video. I'm not sure how big of an issue this is but maybe having the 2 scroll bars work separately might help?

https://user-images.githubusercontent.com/70382249/135101581-158d869b-5cfe-42ff-b4fb-a5c48147c7a1.mp4

.

**Comment by LysandreJik** [comment]
We're in the process of moving away from Sphinx in the next few weeks, so as it seems to affect only a small number of people *and* we'll have a new frontend in a couple of weeks, we'll focus our efforts on getting the new frontend out as early as possible. Hope that's fine!

**Comment by redwizard100** [comment]
I experienced it as well on Chrome 94. I realized if I turn off smooth scrolling the stuttering scroll issue is gone.

![image](https://user-images.githubusercontent.com/15170425/135848988-66e51308-b51b-49c8-8833-6e5aca6b85ec.png)


Although another issue appears i.e scrolling the main content will scroll the sidebar as well.
And it seems another person experienced that as well https://discuss.huggingface.co/t/docs-sidebar-scrolls-while-scrolling-main-content/10387

**Comment by LysandreJik** [comment]
Is it still the case @ekdnam, @DeepP2667?

**Comment by DeepP2667** [comment]
It works great now Thank you!

**Comment by LysandreJik** [comment]
AFAICT, we didn't change anything :smile:

**Comment by DeepP2667** [comment]
Oh, I'm not sure but it works now

**Comment by LysandreJik** [comment]
It might have been an issue with a chrome or Sphinx version, but glad to hear that it works now!

**Comment by julien-c** [comment]
Closing this as stale but please give us feedback on the new doc frontend!

Announcement at https://twitter.com/huggingface/status/1466462283576533003
