### ISSUE TITLE
cannot import name 'TFBertForSequenceClassification'

### ISSUE THREAD

**Issue by samarthsarin** [huggingface/transformers#1375]
I am unable to import TFBertForSequenceClassification.

from transformers import TFBertForSequenceClassification shows an error of cannot import name 'TFBertForSequenceClassification'

**Comment by LysandreJik** [comment]
Hi! The TensorFlow components are only available when you have TF2 installed on your system. Could you please check that you have it in the environment in which you're running your code?

**Comment by samarthsarin** [comment]
It worked. Thanks
