### ISSUE TITLE
This problem happend when I train the model

### ISSUE THREAD

**Issue by PPPHUB** [huggingface/transformers#13754]
`The expanded size of the tensor (824) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [32, 824].  Tensor sizes: [1, 512]`
why this happend and what should I do?

**Comment by qqaatw** [comment]
We cannot identify the problem without additional context. Please provide the code that can reproduce this error.

**Comment by NielsRogge** [comment]
Hi,

For training-related questions, please refer to the [forum](https://discuss.huggingface.co/). We like to keep Github issues for bugs/feature requests.

Thanks!
