### ISSUE TITLE
LengthGroupedSampler: why longest examples go first?

### ISSUE THREAD

**Issue by ZhaofengWu** [huggingface/transformers#13794]
Is there any reason for the longest, but not the shortest, examples to go first? I think in some curriculum learning literature people start with the easiest example. What's design decision behind starting with the longest ones?

**Comment by LysandreJik** [comment]
Correct me if I'm wrong @sgugger, but I believe this is because this way, if a memory error happens, it's at the absolute beginning - and not mid-training, which is much more annoying.

**Comment by sgugger** [comment]
Exactly, this is to get the OOM as soon as possible if it should ever happen.

**Comment by ZhaofengWu** [comment]
That makes a lot of sense -- thanks!
