### ISSUE TITLE
Loading wav2vec2 pre-trained models

### ISSUE THREAD

**Issue by jvel07** [huggingface/transformers#13806]
Hi, my aim is to get embeddings from a pre-trained wav2vec2 model using my own data (over 9k samples for each: train, dev, and test; the wavs are from 1 to 4 secs of duration) 
I got two main inquiries:
1. I am trying to load a pre-trained model in the following way and I get "CUDA out of memory" error:
```device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_name = "facebook/wav2vec2-large-xlsr-53-german"
feature_extractor = Wav2Vec2Processor.from_pretrained(model_name)
model = Wav2Vec2Model.from_pretrained(model_name)
model.to(device)
```
Am I missing something here? The only way I could load the model is when I don't do `.to(device)` so it loads in the RAM, but in this way, inferencing is way too slow.

2. After loading the model without using GPU, I could get the embeddings in this way:
```
input_values = feature_extractor(train_dataset["speech"], return_tensors="pt", padding=True, 
                                 feature_size=1, sampling_rate=16000 )
outs = model(**input_values)
last_hiddens = outs.last_hidden_state   # embeddings here correspond to the sequence of last_hidden_states
last_cnn_embs = outs.extract_features  # sequence of features of the last conv layer of the model
```
Saving the embeddings to a binary file resulted in over 20 GB for the `last_hiddens` and over 10 GB for the `last_cnn_embs`.
Is that a normal thing?

**Comment by patrickvonplaten** [comment]
Hey @jvel07 - you would be able to load the model to GPU. The model is "only" 1GB in size so it should be easily useable on most GPUs. Are you sure there aren't any other processes occupying the GPU when you try loading the model? 

Regarding the binary files - I can't really say anything here as I've never saved the embedding outputs to binaries.

**Comment by jvel07** [comment]
Thanks for your answer. Will check everything and try again. 
May I ask about fine-tuning a wav2vec2 model on my data? I mean, what would be the recommended GPU memory for this case?

**Comment by patrickvonplaten** [comment]
Can you please check the forum: https://discuss.huggingface.co/ for more specific Wav2Vec2 questions? :-) Also these blog posts might be useful:

- https://huggingface.co/blog/fine-tune-wav2vec2-english
- https://huggingface.co/blog/fine-tune-xlsr-wav2vec2
