### ISSUE TITLE
How to use LayoutLM Tensorflow version on Google Colab?

### ISSUE THREAD

**Issue by alucor-it** [huggingface/transformers#13804]
Hi,
Could you please help me implement LayoutLM's tensorflow version in Google Colab?
Previously I have implemented using the following link: https://github.com/microsoft/unilm.git

I would like to understand how to implement the Tensorflow version.
https://huggingface.co/atahmasb/tf-layoutlm-base-uncased

Thank you.

**Comment by NielsRogge** [comment]
You can check out the documentation in order to use the model: https://huggingface.co/transformers/model_doc/layoutlm.html#tflayoutlmmodel
