### ISSUE TITLE
[examples/pytorch/image-classification] why does it require `torch>=1.9.0`

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#13802]
Why do we have these particular requirements at:

https://github.com/huggingface/transformers/blob/b90096fe1424e1927e549b73b5db67341a0d27d0/examples/pytorch/image-classification/requirements.txt#L1-L2

I tested it and it works with pt-1.8.2 just fine.
```
RUN_SLOW=1 pyt examples/pytorch/test_examples.py -k test_run_image_classification
```

Let's not set a higher version requirement than it actually is needed.

I propose to remove both entries altogether unless they are actually needed and if so tested with the lowest supported version.

It's important in this particular case since HF Deepspeed integration tests are now included in the Deepspeeed CI which runs on pt-1.8 so I can't test HF image models on the Deepspeed side then.

Thank you!

@nateraw, @LysandreJik

**Comment by nateraw** [comment]
Feel free to PR if ya want if it's a blocker for you! Otherwise I'll get to it when I fix the config issue (on mobile can't link to issue number)

**Comment by stas00** [comment]
I can wait no problem, @nateraw - I just didn't know which lower version is actually required.

Thank you!
