### ISSUE TITLE
how to train RoBERTa from scratch

### ISSUE THREAD

**Issue by 008karan** [huggingface/transformers#1381]
## ❓ Questions & Help

I want to train RoBERTa model from scratch on different language. Is there any implementation available here to do this?

**Comment by FrankWork** [comment]
https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md

**Comment by julien-c** [comment]
You can now leave `--model_name_or_path` to None in `run_language_modeling.py` to train a model from scratch.

See also https://huggingface.co/blog/how-to-train

**Comment by miluki01** [comment]
When I put new --config_name and --tokenizer_name. It shows me that 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Anyone can help me?
