### ISSUE TITLE
Bort always predict wrong words

### ISSUE THREAD

**Issue by Oxi84** [huggingface/transformers#13827]
Even on api interface Bort predict wrong words in MaskedLM for example here - https://huggingface.co/amazon/bort?text=Paris+is+the+%3Cmask%3E+of+France.

So there has to be some configuration bug that should be fixed.

The same happens when calling Bort using auto classes.

Could you take a look?

**Comment by NielsRogge** [comment]
Pinging @stefan-it here as he contributed this model

**Comment by stefan-it** [comment]
Hi @Oxi84 , we were not able to get mask prediction working, even with the original Gluonnlp implementation. So I think it's a good idea to disable the inference for now.
