### ISSUE TITLE
TF mT5 model is not adding new tokens into it's vocabulary.

### ISSUE THREAD

**Issue by laddhakrishna** [huggingface/transformers#13839]
## Environment info

- `transformers` version: 4.11.2
- Platform: google colab
- Python version: 3.7.12
- PyTorch version (GPU?):
- Tensorflow version (GPU?): 2.6.0
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

## Information

Model I am using (Bert, XLNet ...):
I am using mT5 model. The problem arised when I am trying to resize the token embeddings. I added new special tokens to my tokenizer's vocabulary, when I resized the model's token embeddings according to the length of the tokenizer, I am facing the issue.  

Link for the notebook:  https://colab.research.google.com/drive/1ooKa5aQ_FAEnicxBL8bJnNAO4H9vFuv-?usp=sharing
Code from the notebook:  
!pip install transformers
!pip install sentencepiece
from transformers import TFMT5ForConditionalGeneration, T5Tokenizer
model = TFMT5ForConditionalGeneration.from_pretrained("google/mt5-base")
tokenizer = T5Tokenizer.from_pretrained("google/mt5-base")
tokenizer.add_special_tokens({'bos_token':'<bos>','eos_token':'<eos>'})
model._resize_token_embeddings(len(tokenizer))

The error message is: 
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

The problem arises when using:

* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. You can directly run the code & check the error coming from the last line.
2. Also you can go the colab notebook & have a look at the error as well.
3.

**Comment by patil-suraj** [comment]
This seems to be an issue with TF model cc @Rocketknight1 

@patrickvonplaten it seems there are no extra tokens in mt5 tokenizer and there's a mismatch between `tokenizer.vocab_size` and `config.vocab_size`. Is this a known issue?

**Comment by patrickvonplaten** [comment]
Hey @laddhakrishna,

could you provide a google colab that reproduces the error with `model.resize_token_embeddings(...)`? I didn't manage to reproduce the error. Thanks!

**Comment by patrickvonplaten** [comment]
Hey @laddhakrishna,

Thanks for the colab I can reproduce!

**Comment by LysandreJik** [comment]
Maybe @Rocketknight1 or @gante can take a look?
