### ISSUE TITLE
Multilingual T5 is not adding new tokens

### ISSUE THREAD

**Issue by sasidharreddy25** [huggingface/transformers#13840]
## Environment info

- `transformers` version: 4.11.2
- Platform:google colab
- Python version:3.7.12
- PyTorch version (GPU?):
- Tensorflow version (GPU?): 2.6.0
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?:No

## Information

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.You can directly run the code & check the error coming from the last line.
2.Also you can go the colab notebook & have a look at the error as well.

**Comment by patil-suraj** [comment]
related #13840
