### ISSUE TITLE
Zero-shot classification pipeline change in 4.11.2

### ISSUE THREAD

**Issue by davidmezzetti** [huggingface/transformers#13846]
The latest version of the ZSL classification pipeline appears to give slightly different output for the following test code:

```python
from transformers import pipeline

nlp = pipeline("zero-shot-classification")
print(nlp(["I am happy", "I am sad"], ["negative", "positive"]))
```

Version 4.10.2 output
```
[{'sequence': 'I am happy', 'labels': ['positive', 'negative'], 'scores': [0.9984542727470398, 0.0015457083936780691]}, {'sequence': 'I am sad', 'labels': ['negative', 'positive'], 'scores': [0.9985381364822388, 0.0014618091518059373]}]
```

Version 4.11.2 output
```
[[{'sequence': 'I am happy', 'labels': ['positive', 'negative'], 'scores': [0.9984542727470398, 0.0015457083936780691]}], [{'sequence': 'I am sad', 'labels': ['negative', 'positive'], 'scores': [0.9985381364822388, 0.00146180868614465]}]]
```

It appears that 4.11.2 is adding an extra list around each element. This can be manually processed out but I also wanted to pass this along in case this wasn't expected new behavior.

**Comment by lalitpagaria** [comment]
@Narsil @LysandreJik fyi
Facing similar issue as well.

**Comment by Narsil** [comment]
Thanks for letting us know, 

This is unknown breaking backward compatible, fortunately it's an easy fix !

**Comment by lalitpagaria** [comment]
@Narsil Thank you for quick fix.
Any idea when this fix will be released?

**Comment by Narsil** [comment]
I will let core maintainers answer there but first the PR needs to be reviewed.
