### ISSUE TITLE
there is not more toolkit and model  architecture about tabular format in hugginggface, tabular text in NLP = language + layout

### ISSUE THREAD

**Issue by hengfanz** [huggingface/transformers#13858]
# 🚀 Feature request

last few years, many industry work of deep learning about tabular text boom, such as "CascadeTabNet","tablenet". many old work about  tabular text  developed from web html table, but there is no united toolkit and mode architecture to accelerate the tabluar text research in NLP.

**Comment by LysandreJik** [comment]
We have support for the TAPAS model in `transformers` - would it help your use-case?
