### ISSUE TITLE
Update examples/documentation for torch.distributed.run

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#13850]
Most examples now read local rank from a CLI argument `--local_rank`. This ensures for it to work when using the torch launch utility `torch.distributed.launch`. However, since recent torch versions, `launch` is deprecated. The new suggested way to run distributed code from CLI is with `torch.distributed.run`. The difference from before is that instead of automatically passing CLI arguments, it sets the rank **as an environment variable**. The examples therefore need to be updated to read the ENV variable instead of the CLI argument.

See https://pytorch.org/docs/stable/elastic/run.html#launcher-api for more.

**Comment by BramVanroy** [comment]
I missed that the training arguments already have this covered:

https://github.com/huggingface/transformers/blob/bcc3f7b6560c1ed427f051107c7755956a27a9f2/src/transformers/training_args.py#L681-L685

**Comment by LysandreJik** [comment]
Hi @BramVanroy! Let us know if this isn't sufficiently documented so that we may patch the issue

**Comment by BramVanroy** [comment]
@LysandreJik I think the code in the TrainingArgs is fine. Documentation may need an update as it refers to `launch` in a couple of places. A quick search gives me mentions of `torch.distributed.launch` in these documents that may need to be replaced by `torch.distributed.run`. You'd also need to check whether `--nproc_per_node` is still an accepted argument for that command because I am not sure. So it is not only a find-and-replace update!

- https://huggingface.co/transformers/performance.html
- https://huggingface.co/transformers/main_classes/deepspeed.html
- https://huggingface.co/transformers/debugging.html

**Comment by LysandreJik** [comment]
Maybe of interest to @sgugger

**Comment by sgugger** [comment]
I wouldn't update the documentation as it won't work for older versions of PyTorch and I would prefer to only put one command vs If your PyTorch version is this then xxx else yyy. Let's wait a bit more :-)

**Comment by BramVanroy** [comment]
`launch` is currently deprecated.

**Comment by sgugger** [comment]
My previous comment still stands :-)

**Comment by BramVanroy** [comment]
Definitely. I think it's a good idea to keep bumping this to open, so that others can also find this issue easily, and it can serve as a reminder that as soon as `launch` is obsolete, the docs need an update. It's a tiny thing and easy to forget, so an open issue may help to remember as time goes on.
