### ISSUE TITLE
Can't use add_prefix_space in RobertaTokenizerFast

### ISSUE THREAD

**Issue by yujianll** [huggingface/transformers#13868]
## Environment info

- `transformers` version: 4.11.2
- Platform: Linux-5.11.0-34-generic-x86_64-with-glibc2.31
- Python version: 3.9.1
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help

- tokenizers: @LysandreJik
- Documentation: @sgugger

## Information

Model I am using: RobertaTokenizerFast

The problem arises when using RobertaTokenizerFast with add_prefix_space:
```
tokenizer = RobertaTokenizerFast.from_pretrained('roberta-base')
inputs = tokenizer("This is a sentence.", add_prefix_space=True)
```
it gives me error: `TypeError: _batch_encode_plus() got an unexpected keyword argument 'add_prefix_space'`

However, the doc says 

> You can get around that behavior by passing add_prefix_space=True when instantiating this tokenizer or when you call it on some text

I wonder how I can specify this when I call the tokenizer on some text.

## Expected behavior
Be able to pass in `add_prefix_space=True` after initializing the tokenizer, just like RobertaTokenizer.

**Comment by sgugger** [comment]
Hi there! Instantiating is different from calling, it means creating the object. So you create the tokenizer:
```
tokenizer = RobertaTokenizerFast.from_pretrained('roberta-base', add_prefix_space=True)
```

**Comment by yujianll** [comment]
Thanks! I see the difference, I'm trying ask if we can instantiate tokenizer without `add_prefix_space=True` and call it with `add_prefix_space=True`. Because the  doc seems to say we can do that. And also we can do that for `RobertaTokenizer`.

**Comment by sgugger** [comment]
No, the latter is not possible. I see what you were saying at first, the doc should indeed be adapted to remove the part "when you call it"
