### ISSUE TITLE
The Pegasus model generator function ignores the temperature parameter.

### ISSUE THREAD

**Issue by ftarin-suspership** [huggingface/transformers#13899]
Loading the model using the from_pretrained method, using the 'tuner007/pegasus_summarizer' weights, and invoking the generate method with different temperatures results in always the same output text being generated regardless of the temperature.

## Environment info

- `transformers` version: 4.11.2
- Platform: Linux-5.4.0-1055-aws-x86_64-with-debian-buster-sid
- Python version: 3.7.10
- PyTorch version (GPU?): 1.9.1+cu102 (True)
- Tensorflow version (GPU?): 2.3.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help

Models:
Pegasus model (using the torch implementation)
loading the weights from 'tuner007/pegasus_summarizer'

## To reproduce

1. Load the model using the from_pretrained method
2. Invoke the generate method with different temperatures.

## Expected behavior
Get different output texts

**Comment by patil-suraj** [comment]
Could you post a code snippet so we could take a look ? Also `temperature` parameter is for sampling so make sure to enable sampling, you could do this by passing the `do_sample=True` argument to the `generate` method, otherwise `temperature` won't have any effect.

**Comment by ftarin-suspership** [comment]
What I mean is that in the absence of the to_sample=True parameter modifying the num_beams changes the output but not changing the temperature
