### ISSUE TITLE
Inference of ONNX exported BART

### ISSUE THREAD

**Issue by GRIGORR** [huggingface/transformers#13893]
As I understand correctly, one should use generate function for Seq2Seq model inference. I have exported BART to ONNX, but ONNX InferenceSession().run() returns result of BART.forward(), which is different from BART.generate(). Is there any way to get the BART.generate() from ONNX? Thanks.

**Comment by GRIGORR** [comment]
Thanks for the response. Just a small clarification, in the pull request you mentioned is handling of beam search, if I want to use greedy decoding, I still cant have it for ONNX BART right?

**Comment by Anku5hk** [comment]
Nope, for now you need to implement your own greedy search or beam search for generating.
