### ISSUE TITLE
`from_pretrained` doesn't validate its kwargs

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#13912]
splitting off from https://github.com/huggingface/transformers/issues/13895

```
AutoModel.from_pretrained(mname, reviison=ckpt) # dyslexic typist
```
Throws no exception and it definitely should, since this could be unnoticed for a long time and meanwhile the user gets incorrect behavior.

Expected behavior:

There should be an assert if a user passes an argument that is not expected by the function.

@LysandreJik, @sgugger

**Comment by sgugger** [comment]
Digging more, I think you're using a GPT-like model, and this is caused by [this line](https://github.com/huggingface/transformers/blob/5be59a364961a8e2fc986f1276cba977db87512a/src/transformers/models/gpt2/modeling_gpt2.py#L456) or the equivalent in other GPT model classes. Not sure what it achieves but it definitely causes the bug you are seeing.

**Comment by stas00** [comment]
> Which checkpoint are you using?

gpt2 indeed.

> Do you have a checkpoint I can use to reproduce the issue?

https://huggingface.co/bigscience/gpt2-1b3-en

**Comment by stas00** [comment]
indeed, let me try with the original model that was reported to have this issue.

Also you mentioned invalid config please see my updated comment above.

**Comment by sgugger** [comment]
This [line](https://github.com/huggingface/transformers/blob/5be59a364961a8e2fc986f1276cba977db87512a/src/transformers/models/megatron_gpt2/convert_megatron_gpt2_checkpoint.py#L303) in the script does not save the config in the same format as the others. I don't know why they don't use the method of the config to properly save it.

**Comment by stas00** [comment]
I suppose our use case is probably rare and it's probably ok to leave it as is. I think the only issue is `use_auth_token`

It'd probably  help the user if the hub were to report 403 (access denied), rather than:
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/bigscience/gpt2-1b3-en/resolve/main/config.json
```
then the user is likely to review their config and discover they are either missing `use_auth_token` or it is misspelled.

Moreover, if the client side got 403 - it could have suggested to the user path `use_auth_token=True`.
