### ISSUE TITLE
valhalla/distilbart-mnli-12-3' is a correct model identifier listed on 'https://huggingface.co/models'

### ISSUE THREAD

**Issue by muiPomeranian** [huggingface/transformers#13927]
i was using AWS batch transform with this model and worked fine but since after last week, somehow it complains with this 
message:

```valhalla/distilbart-mnli-12-3' is a correct model identifier listed on 'https://huggingface.co/models'```

but I do see that this is a valid model config. Is this awared from your side ?

**Comment by patil-suraj** [comment]
Hi! Could you post the full stack trace?

**Comment by muiPomeranian** [comment]
Appreciate. Please do let me know as this is quiet unexpected failure which blocks me quiet hard :(

**Comment by philschmid** [comment]
(1) Yes, we provide a custom hf internal handler which leverages the `pipelines` module and has a similar API as the Inference-API: documentation here: https://huggingface.co/docs/sagemaker/inference#inference-toolkit---api-description

`multiRecord` is currently not supported by the hf internal handler. See (2) on how to leverage multiRecord

(2) Yes you can customize your handler by creating an `inference.py` script in their you have can overwrite the same methods as you know including `input_fn`, `predict_fn`, `output_fn` and `model_fn`. 
There are two option to provide the `inference.py` afterwards, either you bundle it into the `model.tar.gz` but it needs to be in a `code/` or you add it to your `HuggingFaceModel` as `entry_point`: documentation here: https://huggingface.co/docs/sagemaker/inference#user-defined-codemodules

(3) Yes you can easily manually create those `model.tar.gz` for the `HuggingFaceModel`

**Comment by muiPomeranian** [comment]
Hello again :( sorry but I swtiched tokenizer to `bart-large-mnli` 

and somehow now i am seeing

``` 
W-9069-model_0-stdout MODEL_LOG - requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/models/facebook/bart-large-mnli
```

Although sagemaker endpoint is able to load tokenizer from huggingface, but somehow batch transform only raise this error... 

Why now im seeing 403 error ... ?
