### ISSUE TITLE
Bert's keyword argument 'output_all_encoded_layers' does not exist anymore?

### ISSUE THREAD

**Issue by fhamborg** [huggingface/transformers#1392]
## 📚 Migration

Model I am using (Bert, XLNet....): Bert

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [ ] the official example scripts: (give details)
* [X] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details)

Details of the issue:

I was using the keyword argument `output_all_encoded_layers` before. Now the code throws an error, since it seems that this argument was removed. How can I still set `output_all_encoded_layers` to either True or False, e.g.:

```
context, _ = self.bert(context, output_all_encoded_layers=False)
```

## Checklist

- [X] I have read the migration guide in the readme.
- [X] I checked if a related official extension example runs on my machine.

**Comment by LysandreJik** [comment]
Hi! @thomwolf can correct me if I'm wrong, but I believe this keyword was changed to `output_hidden_states` in version 1.0.0.

**Comment by BramVanroy** [comment]
I can confirm what @LysandreJik suggests.

**Comment by fhamborg** [comment]
Alright, thank you very much!
