### ISSUE TITLE
Licensing of LayoutLM models

### ISSUE THREAD

**Issue by athuljays** [huggingface/transformers#13932]
Hi, Can you clarify the licensing of the layoutLM models provided in HuggingFace?

It is very ambiguous right now. 

Ref: [https://github.com/microsoft/unilm/issues/352](url)

**Comment by NielsRogge** [comment]
I've updated the license of LayoutLMv2 and LayoutXLM on the hub to CC BY-NC-SA 4.0 as stated on [this page](https://github.com/microsoft/unilm/tree/master/layoutlmft).

**Comment by riteshkumarumassedu** [comment]
@NielsRogge,
How about the usage of just the code from HuggingFace? Could we use LayoutLMv2 code from HuggingFace, pretrain our own model from scratch and use it in production?

**Comment by riteshkumarumassedu** [comment]
@NielsRogge,
Can someone from your team confirm on the above comment: https://github.com/huggingface/transformers/issues/13932#issuecomment-1387206937
