### ISSUE TITLE
Add support for `push_to_hub` for `AutoFeatureExtractor`

### ISSUE THREAD

**Issue by philschmid** [huggingface/transformers#13958]
# 🚀 Feature request

Add support for `push_to_hub` for `AutoFeatureExtractor.save_pretrained()`.

Hey, while doing some Speech tests I noticed that
`AutoFeatureExtractor.save_pretrained()` is not supporting `push_to_hub`.
https://github.com/huggingface/transformers/blob/46efc5802458e91a702528332d76d464061d201f/src/transformers/feature_extraction_utils.py#L194
compared to `AutoTokenizer`
https://github.com/huggingface/transformers/blob/0b8c84e110bf9012f30a85c40b9ff8ea868689fd/src/transformers/tokenization_utils_base.py#L1432

**Comment by anton-l** [comment]
unstale
