### ISSUE TITLE
```input_embeds``` keyword not working properly (GPT2)

### ISSUE THREAD

**Issue by johncwok** [huggingface/transformers#13978]
```transfomer-cli env``` command was not recognized so I do not know which environment I have.

- `transformers` version: latest
- Platform: windows 10
- Python version: 3.8.5
- PyTorch version (GPU?): CPU
- Tensorflow version (GPU?): None
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@patrickvonplaten, @LysandreJik

## Information

Model I am using (GPT2):

When I want to provide my own embeded representation instead of input indices to a GPT2 that I want to train from scratch, I get the following error:
```Python
Traceback (most recent call last):

  File "<ipython-input-18-d0df910b9d57>", line 10, in <module>
    model(inputs_embeds=inputs_embeds)  # runs without error

  File "C:\Users\cnelias\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)

TypeError: forward() got an unexpected keyword argument 'inputs_embeds'
```
It does not come from my implementation since the following code also throws the same error:
```
from transformers import GPT2Model, GPT2Tokenizer
import torch

model = GPT2Model.from_pretrained('gpt2')
tokenizer = GPT2Tokenizer.from_pretrained('gpt2', pad_token='<PAD>')

input_ids = tokenizer.encode("Hello, how are you?", return_tensors='pt')
inputs_embeds = model.wte(input_ids)

model(inputs_embeds=inputs_embeds) 
```

I installed pytorch via conda, this could be the cause.

**Comment by qqaatw** [comment]
I think you probably checked a wrong docs version, the GPT2 in [v2.1.1 docs](https://huggingface.co/transformers/v2.1.1/model_doc/gpt2.html) was still under construction at that moment.

**Comment by johncwok** [comment]
This does not work, I get this error 
```
ERROR: Could not find a version that satisfies the requirement torchaudio (from versions: none)
ERROR: No matching distribution found for torchaudio
```
This issue has been reported by other users on the torchaudio github page, and it seems to be due to the fact that windows in not supported yet.

**Comment by johncwok** [comment]
I'll try that. I do have one last question: you mention the fact that in the latest version, ```input_embeds``` is not used anymore. Yet, when I look at the latest [doc](https://huggingface.co/transformers/model_doc/gpt2.html), I see that it is still an argument from the ```forward``` method. If the argument doesnt exist anymore, what is the current name?

**Comment by sugarandgugu** [comment]
I define a new class using transformers extend LlamaForCausalLM，when i use peft to get lora model， in the training process，it occur this  “TypeError: forward() got an unexpected keyword argument 'inputs_embeds'
”，Then I added these parameter in forward func, it solve my problem.`
    def forward(
        self, 
        user, 
        item, 
        input_ids, 
        attention_mask,
        labels,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Union[Cache, List[torch.FloatTensor]]] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        return_dict: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None
        ):`
