### ISSUE TITLE
Integration.py

### ISSUE THREAD

**Issue by f3n1Xx** [huggingface/transformers#14003]
# 🚀 Feature request

CometCallback in integration is overriding my experiment object declared in optimizer.

## Motivation

reporting logs to comet through cometcallback is overriding experiment objects already declared before the TrainerAPI is invoked. Is there any way to make space for cometcallback to get the experiment object instead of overriding it. This way, we can not only use Optimizers of comet_ml but also use important metrics like "log_confusion_matrix".

If it's not viable, please let me know.

**Comment by dsblank** [comment]
I think we have solved this issue here:

https://github.com/comet-ml/issue-tracking/issues/434

And we are working on an internal refactor to allow more flexibility on the transformer side.
