### ISSUE TITLE
[feature request] a tool to clone existing models to make new models with small changes

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#14032]
# 🚀 Feature request

So we have great templates for creating a new model.

### Can you think of a way to create full clones of existing models? 

Practically for BigScience needs we will have to create something like GPTMeg which is 99.9% identical to GPT2 with 2-3 tiny changes. And then we will need another GPT2 variant that replaces Positional Embeddings with ALiBi. And there will be more variants.

Using templates would be quite expensive, when always everything is really identical.

So ideally a user will do:
```
transformers-clone-model GPT2 GPTMeg
```
and voila it'd replicate model's files, tests and docs.

If all source files could be easily identified this perhaps could be done in a few perl one liners. Here is a very rough outline:

1. find the pertinent source files grep -Irl GPT2 .
2. rename files/dirs while copying s/gpt2/gpt_meg/
3. rename internals to s/GPT2/GPTMeg/g

The hard to automate part is the index files as they is only one of each

I think I can work it out, but I'm afraid that the end result would be a set of Perl one-liners only Stas will know what to do with. So perhaps long term this is not a good solution.

Here is the Issue where we need to implement this: https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/138
and 2 more will be coming soon.

@LysandreJik, @patrickvonplaten, @sgugger

**Comment by LysandreJik** [comment]
That's an interesting feature request, would be very useful indeed! Could provide a better starting point than the templates in many situations.

**Comment by stas00** [comment]
Open this to the community if perhaps someone would be interested to work on this?

**Comment by LysandreJik** [comment]
Yes, that's a good starting point! I would advise studying the templates and how they were implemented (with cookiecutter) in order to provide something similar: it has been used quite a bit by now and should be able to handle most of it. 

They are available here: https://github.com/huggingface/transformers/tree/master/templates/adding_a_new_model

**Comment by sgugger** [comment]
Unstale, will soon have time for this :-)

**Comment by stas00** [comment]
a gentle ping

**Comment by stas00** [comment]
would love to have this tool, as I think this model will now have to be re-done as many thing have changed since 2 months ago when the PR was created. https://github.com/huggingface/transformers/pull/14084
It'd be much easier to clone and add the few changes then trying to catch up with all the mods that happened around gpt2 model.

**Comment by sgugger** [comment]
I can work on this a bit next week once I have re-enabled the doc styler. I don't promise to have something fully finished before I go on vacation (first week of January) however.

**Comment by stas00** [comment]
Not expecting any promises, just appreciating you wanting to work on it, @sgugger - thank you so much!
