### ISSUE TITLE
Which is better ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [huggingface/transformers#14068]
I want to train a GPT-J-6B model on Arabic dataset but i am facing an important question.
Should i train the model from scratch or fine tune it on the new language … which is better ?

**Comment by sgugger** [comment]
You should use the [forums](https://discuss.huggingface.co/) to discuss this, as we keep issues for bugs and feature requests only.

**Comment by srulikbd** [comment]
@MohamedAliRashad did you ask it on the forum?
If yes, can you provide the link?
thanks.

**Comment by MohamedAliRashad** [comment]
@srulikbd 
Found similar questions not answered or recommended the training from scratch part but knew it is impossible because it requires huge amount of computation.
