### ISSUE TITLE
bert onnx to tensorrt wrong

### ISSUE THREAD

**Issue by WallE-Chang** [huggingface/transformers#14100]
## Environment info

- `transformers` version:
- Platform: ubuntu 18
- Python version: 4.11.3
- PyTorch version (GPU?):1.8.0 gpu
- Tensorflow version (GPU?):
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?:

I get bert onnx ckpt by
`python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/`

Then, I want to convert onnx to tensorrt 
`TensorRT-8.2.0.6/bin/trtexec --verbose \
                             --workspace=20000 \
                             --minShapes="input_ids":1x1,'attention_mask':1x1,'token_type_ids':1x1 \
                             --optShapes="input_ids":4x64,"attention_mask":4x64,"token_type_ids":4x64 \
                             --maxShapes="input_ids":8x128,"attention_mask":8x128,"token_type_ids":8x128 \
                             --onnx=./onnx/bert-base-cased/model.onnx \
                             --saveEngine=./trt/bert-base-cased/model.trt \
                             --fp16`

However, I get error

![image](https://user-images.githubusercontent.com/22662737/138287788-8ff5d519-1ef9-40e1-9bd8-6411ff415a14.png)

Can you give me some help ？

**Comment by pommedeterresautee** [comment]
I am currently working on that there: https://github.com/ELS-RD/transformer-deploy
TBH, it's not a simple problem, but it brings lots of performance improvement compared to vanilla pytorch or even CUDA provider on ONNX Runtime

**Comment by lewtun** [comment]
Hey @WallE-Chang this issue would be better suited for the `optimum` [library](https://github.com/huggingface/optimum), which is more focused on these framework-specific aspects. Would you mind opening your issue there?
