### ISSUE TITLE
OnnxRuntime error " The input tensor cannot be reshaped to the requested shape."

### ISSUE THREAD

**Issue by husnain-ali21** [huggingface/transformers#14147]
Hello! I have quantised the bart model for abstractive summarisation using transformers.onnx as suggested at https://huggingface.co/transformers/serialization.html.When I run the session with inputs for getting outputs  back, I get a shape mismatch error. I have checked that the input shapes  of my input text are in accordance with 
https://github.com/huggingface/transformers/blob/master/src/transformers/models/bart/configuration_bart.py

 Here is the error message I am receiving.

`onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_109' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape &, std::vector<int64_t> &, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{2}, requested shape:{1,1}`

## Environment info

- `transformers` version: 4.11.3
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.9.6
- PyTorch version (GPU?): 1.9.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False

Models:

@patil-suraj
@patrickvonplaten

## Information

Model I am using (Bart, i.e  facebook/bart-large-cnn ...):

**Comment by patil-suraj** [comment]
Not sure about this error, but we have added an experimental bart onnx generation example [here](https://github.com/huggingface/transformers/tree/master/examples/onnx/pytorch/translation), maybe that could help :)

**Comment by husnain-ali21** [comment]
Thank you, That would be of great help!
