### ISSUE TITLE
run_glue.py - Import Error

### ISSUE THREAD

**Issue by yukioichida** [huggingface/transformers#1415]
## 🐛 Bug

Model I am using (Bert, XLNet....): XLNET (from example/run_glue.py)

The problem arise when using:
* [ ] the official example scripts: run_glue.py
- Stacktrace:
Traceback (most recent call last):
  File "run_glue.py", line 49, in <module>
    from transformers import glue_compute_metrics as compute_metrics
ImportError: cannot import name 'glue_compute_metrics'

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: MNLI

## To Reproduce

1. Execute run_glue.py after install requirements.
## Environment

* OS: Linux - Ubuntu
* Python version: 3.6
* PyTorch version: 1.2.0
* PyTorch Transformers version (or branch): tag 2.0.0

## Additional context
I found that some scripts related to glue tasks were not in *transformer* directory, which causes the import problem.But I really don't know if it may be a project setup issue or the files that contains glue utility code should be in */transformer* dir instead of */transformer/data/metrics*.

**Comment by LysandreJik** [comment]
Hi! You may have seen this warning when importing from our library: `To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html`.

Do you have this issue even with scikit-learn installed?

**Comment by yukioichida** [comment]
Hi @LysandreJik ,

Thanks for the answer. I already have scikit-learn but actually I'm working using a conda environment with *transformer* package installed using conda pip.
However, I solved this issue exporting the *PYTHONNOUSERSITE=1*, which enabled the scikit-learn installed in my conda environment. I discovered this problem because the stack trace was pointing to files contained in local packages instead of my conda environment packages.

I'll close this issue. Thanks for the explanation.

*OBS*: Do you guys intend to publish a conda package of transformers?

**Comment by ameet-1997** [comment]
I face the exact same issue, even though `scikit-learn` is installed. The steps to reproduce are exactly identical, and I built from source.

I tried the `PYTHONNOUSERSITE=1` solution, but that does not change things because I can already import `sklearn` from the shell, and all required packages are in the conda environment.

Repeating the stack trace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'glue_compute_metrics' from 'transformers' (path/to/transformers/__init__.py)
```

My python version is `3.7.6`

**Comment by zhjohnchan** [comment]
I fixed it by downgrading the python from 3.7.7 to 3.7.0:
```
conda install python=3.7.0
```

**Comment by galshachaf** [comment]
fixed for me by adding "import sklearn" to run_glue.py before the imports from transformers.

**Comment by ldong87** [comment]
> I face the exact same issue, even though `scikit-learn` is installed. The steps to reproduce are exactly identical, and I built from source.
> 
> I tried the `PYTHONNOUSERSITE=1` solution, but that does not change things because I can already import `sklearn` from the shell, and all required packages are in the conda environment.
> 
> Repeating the stack trace
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'glue_compute_metrics' from 'transformers' (path/to/anaconda3/envs/nlp/lib/python3.7/site-packages/transformers/__init__.py)
> ```
> 
> # Environment
> * OS: `Springdale Linux 7.7 (Verona)`
> * Python version: `3.7.6`
> * PyTorch version: `1.3.1`
> * PyTorch Transformers version (or branch): `2.4.1`
> 
> > Hi! You may have seen this warning when importing from our library: `To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html`.
> > Do you have this issue even with scikit-learn installed?
> 
> > Yes :(

I'm facing the same issue even when sklearn is installed.
