### ISSUE TITLE
Decoding Large Audio Files Using Wav2Vec2ForCTC Model

### ISSUE THREAD

**Issue by farisalasmary** [huggingface/transformers#14162]
https://discuss.huggingface.co/t/decding-large-audio-files-using-wav2vec2forctc-model/11097

I’ve been working on Wav2Vec2ForCTC model for a while. I used to have small audio files, i.e., audio files with relatively short durations (~ 1 min). When I tested the model on a large file (~ 14 mins), the model could not handle it in GPU, so, I shifted to use CPU. I notices that it used more than 200 GB of RAM to decode! I’ve tried to split the audio file into smaller audio files and use hidden states to link them together while decoding each segment but I could not find a way to feed the hidden states of the current audio file to the next audio file for the model to use it while decoding!

Any ideas or suggestions?
@patrickvonplaten, @anton-l

**Comment by farisalasmary** [comment]
Hi, @anton-l
Thank you for your reply! 
I'll try to use your approach and see what will happen.

**Comment by leg0m4n** [comment]
hey @anton-l, thank you for your code, it doesn't handle the first and last chunks properly though, do you think its better to add empty audio chunks in the beginning and the end of an audio or just not use start padding in the 1st chunk and end padding in the last chunk?
