### ISSUE TITLE
fx: don't copy by reference

### ISSUE THREAD

**Issue by dar-tau** [huggingface/transformers#14213]
Here:
https://github.com/huggingface/transformers/blob/9fc1951711e5377ffa1f06614ca37d4d5ad281a8/src/transformers/utils/fx.py#L307

there's a copy by reference which is problematic because you append values to `shape`. 
You should make it a copy by value, e.g. by adding the following line right after:
``
shape = shape[:]
``

Cheers, Guy :)

**Comment by LysandreJik** [comment]
cc @michaelbenayoun
