### ISSUE TITLE
Can't access Huggingface page and cant download models from laptop. Can it be IP ban?

### ISSUE THREAD

**Issue by Rajmehta123** [huggingface/transformers#14227]
## Environment info

- `transformers` version: 4.3.3
- Platform: Darwin-20.6.0-x86_64-i386-64bit
- Python version: 3.7.9
- PyTorch version (GPU?): 1.9.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help
@LysandreJik

### Error
ERR_NAME_NOT_RESOLVED 
![image](https://user-images.githubusercontent.com/22636443/139662198-9a8c1b4e-a920-435e-bf6b-11b755299c6c.png)

Dev tools response when loading the page
![image](https://user-images.githubusercontent.com/22636443/139662006-2b4b114e-6755-4693-b947-b321925852d2.png)

Cannot download pre-trained models from python
`ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.`

When I access the page from another device connected to the same network, it works. I could access the site few days back.

**Comment by LysandreJik** [comment]
Hello! We don't IP ban. Could it be linked to your OS's DNS cache? cc @Pierrci

**Comment by riddhikul** [comment]
even i m facing the same issue , is there any way to resolve it ?

**Comment by riddhikul** [comment]
Okay so i changed my wifi and then it started working , for some reason i cant access it from a certain network

**Comment by wildcommunist** [comment]
I am experiencing the same issue  as of 14 hours ago

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: Ia2BsSzLNtQxWlurd1LzsXCV53YfR2xzFOJG24dU-zEOhxAtcnNARA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

Using the same token from another (external) IP works just fine
