### ISSUE TITLE
Option to upload a trained model from gpt-2-simple to use with Write With Transformer

### ISSUE THREAD

**Issue by torakoneko** [huggingface/transformers#1422]
## 🚀 Feature

I would like to be able to upload model checkpoints created in GPT-2-simple to use with Write with Transformer.

## Motivation

It would be really fun and allow people to use their own checkpoints without having to get them approved or anything or make them public.

## Additional context

none

**Comment by julien-c** [comment]
That's on the long term horizon, but that'd be a cool feature, indeed. We are working on a way to let users of `🤗/transformers` upload their weights to share them with the community super easily.

Once we ship this, it would be doable to also host some of those on Write With Transformer.

**Comment by torakoneko** [comment]
I'm training GPT-2 on all the Harry Potter books and I'd really love to play with it in Write With Transformer if you guys wanted to put it up, lol.

**Comment by julien-c** [comment]
@torakoneko No ETA yet, but things are progressing on the aforementioned roadmap.

**Comment by torakoneko** [comment]
@julien-c Would it be possible to run it locally or on something like RunwayML with one's own checkpoint?
