### ISSUE TITLE
Problem loading trained keras model

### ISSUE THREAD

**Issue by johnwu0604** [huggingface/transformers#1423]
I'm running the following line of code:
```
model = TFBertForSequenceClassification.from_pretrained(model_dir, num_labels=len(labels))
```
where model_dir is a directory containing a tf_model.h5 and a config.json file that was exported using the .save_pretrained() method.

However I get the following error shown below:

![image](https://user-images.githubusercontent.com/44329080/66222304-bb5d3f00-e685-11e9-9017-6d7733bd5d15.png)

Could someone help here?

**Comment by LysandreJik** [comment]
It seems to me like your file is corrupted 😕

**Comment by thomwolf** [comment]
You can refresh the file in the cache with the `force_download` option (`model.from_pretrained(shortcut_name, force_download=True)`)

**Comment by johnwu0604** [comment]
@thomwolf Tried the force_download option and it doesn't work :(

This seems to only happen when I train my model for more than 1 epoch ....

**Comment by johnwu0604** [comment]
I think this worked @thomwolf, thanks!

**Comment by johnwu0604** [comment]
Bringing this back up because it seems like the corrupted file actually happens even when it isn't in the cache. It seems like every 2/3 runs using .save_pretrained() results in a corrupted file for some reason.

**Comment by thomwolf** [comment]
Not sure we can do much about this here, we are just calling `tf.keras.Model.save_weights()` for that. Maybe ask upstream in the TensorFlow issues?
