### ISSUE TITLE
Get FLOP count for a model

### ISSUE THREAD

**Issue by mrtpk123** [huggingface/transformers#14259]
# 🚀 Feature request

Is there a way to calculate the number of FLOPs (an approximate is also fine) from a HuggingFace model?

## Motivation

I'm trying to look at the variation of FLOPs as sequence length varies for a BERT base model. Unfortunately, I could not find it and it is a super useful metric.

**Comment by AndreaLombax** [comment]
Me too...
UP.

**Comment by fzyzcjy** [comment]
Is there any updates? Thanks!

**Comment by kejie7243** [comment]
maybe use pytorch profiler?

**Comment by Antoniano1963** [comment]
> maybe use pytorch profiler?

How to use pytorch profiler in Trainer?

**Comment by AaronZLT** [comment]
Can everybody check the total_flos in trainer_state or in trainer_state.json is correct or not?
