### ISSUE TITLE
ELECTRA Model

### ISSUE THREAD

**Issue by josecannete** [huggingface/transformers#1425]
## 🚀 Feature

New Transformer based model: ELECTRA

## Motivation

Hi guys, did you see the following paper: https://openreview.net/forum?id=r1xMH1BtvB ? There is a new Transformer based model called ELECTRA that seems very interesting and promising. It would be very useful to have a implementation of the model in PyTorch.

## Additional context

Paper: https://openreview.net/forum?id=r1xMH1BtvB

**Comment by rlouf** [comment]
Hi @josecannete 

Thanks for the tip! We are busy building other awesome things at the moment, but feel free to start a PR with a first draft and we will be happy to have a look at it 😄

**Comment by thomwolf** [comment]
And not that it's probably better to wait for the author's original code and pretrained weights.

**Comment by josecannete** [comment]
Any news? Do you know if the code was released?

**Comment by sloth2012** [comment]
waiting...

**Comment by anbasile** [comment]
The original code is available from here: https://github.com/google-research/electra

**Comment by julien-c** [comment]
Anyone wants to give it a go? We can help!

**Comment by LysandreJik** [comment]
We're on it! :hugs:

**Comment by stefan-it** [comment]
@LysandreJik I can help you with evaluating the model on downstream tasks to compare it with the original implementation (I'm currently training an ELECTRA model on GPU, so I'm highly interested in using it with Transformers 😅

**Comment by clarkkev** [comment]
@LysandreJik If it helps, I believe ELECTRA weights are drop-in replacements into the BERT codebase except we do not use a pooler layer and just take the final [CLS] hidden state for sentence representations.

**Comment by MrRace** [comment]
waiting...+10086

**Comment by LysandreJik** [comment]
Since v2.8.0 ELECTRA is in the library :)

**Comment by 008karan** [comment]
@LysandreJik Is pretraining of Electra from scratch support available now?

**Comment by parmarsuraj99** [comment]
Using default scripts?

**Comment by ngoquanghuy99** [comment]
Hi, I'm trying to fine tune ELECTRA large discriminator for a downstream classification task. I took the [CLS] at the last hidden state as the sentence representation like some Autoencoding pretrained LM (BERT, RoBERTa,...). Is that right? 
Just because my results are not stable.
