### ISSUE TITLE
Document or add more detail on `DPRPretrainedModel`

### ISSUE THREAD

**Issue by xhlulu** [huggingface/transformers#14254]
What exactly is [`DPRPretrainedModel`](https://huggingface.co/transformers/model_doc/dpr.html#dprpretrainedmodel)? There's no documentation about it, and it's only subclassed by a undocumented model when I look at the source code. DPR is also a 3-model system, so it's confusing which one this is supposed to correspond to, and how the end user can use it.

It would be nice to have more documentation or description on that.

**Comment by NielsRogge** [comment]
`DPRPretrainedModel` shouldn't actually be included in the documentation, as `BertPretrainedModel` for example is also not documented.

Each model in the Transformers library defines a `<model_name>PretrainedModel`, which is just an abstract class defining the weights initialization of all models (base model + head models) and a simple interface for downloading and loading pretrained models.
