### ISSUE TITLE
About qa example

### ISSUE THREAD

**Issue by wutong4012** [huggingface/transformers#14267]
https://github.com/huggingface/transformers/blob/ce01122a3bb690a944054bef216f87b90c2c9e63/examples/pytorch/question-answering/run_qa.py#L400

According to my understanding, although this is the last 1 that reaches the sequence_id, it should correspond to the [SEP] mark in the real text? So I think it should be reduced by one more here?

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
The [SEP] token has a sequence_id of `None`, not `-1`, so it's not going to be taken into account.
