### ISSUE TITLE
Replace TensorboardX with Pytorch's built in SummaryWriter

### ISSUE THREAD

**Issue by bkkaggle** [huggingface/transformers#1427]
## 🚀 Feature

Import `SummaryWriter` from `from torch.utils.tensorboard` instead of from `tensorboardX`

If you're interested, I can make a pull request to merge the changes that I made in my [fork](https://github.com/bkkaggle/transformers) into the main repository.

## Motivation

TensorboardX isn't needed anymore now that Pytorch 1.2 has been released. The relevant Pytorch docs are available [here](https://pytorch.org/docs/stable/tensorboard.html).

**Comment by BramVanroy** [comment]
You cannot assume that suddenly _everyone_ is on 1.2. You'll need a fallback for people who are 1.x. Something like

```python
try:
    from torch.utils.tensorboard import SummaryWriter
except AttributeError
    from tensorboardX import SummaryWriter
```

That's a good way to 'ease into' a definite change.

**Comment by bkkaggle** [comment]
Fixed.

 I undid the commits removing tensorboardX from the requirements and added a try-except block around the imports to check if the user's pytorch version comes with tensorboard (It's 'experimental' in 1.1.0 and is now stable in 1.2.0).

**Comment by bkkaggle** [comment]
I updated my fork to be in line with the recommendations for contributing in #1448

I created the pull request:

**Comment by bkkaggle** [comment]
closing now that #1454 has been merged in
