### ISSUE TITLE
how can I use convert_marian_to_pytorch.py to convert translation model from marian to pytorch model?

### ISSUE THREAD

**Issue by xiuzhilu** [huggingface/transformers#14270]
I train a translation model by using Marian C++ library, and I get model that model file type is npz, at same time I get model.npz.decoder.yml and model.npz.yml. I want convert the model from Marian C++ library to pytorch model. I find the convert_marian_to_pytorch.py can accomplish it from the document(https://huggingface.co/transformers/model_doc/marian.html). But I can't convert it. How can I use convert_marian_to_pytorch.py to convert it? Thanks

**Comment by Rom4rio74** [comment]
I have the same problem, I can't generate the pytorch_model.bin file, it generates model.safetensors. Anyone kind to explain how to do it? Thanks in advance and congratulations for the great work you are doing

**Comment by ArthurZucker** [comment]
Safetensors is the new default for model saving for security and performance reasons! You can de-activate this but we recommend sharing the models via safetensors!
