### ISSUE TITLE
is pooler output vector directly comparable to vector representation of word?

### ISSUE THREAD

**Issue by jha46** [huggingface/transformers#14299]
Hello, all. 

I have a quick question to understand vector representation for a document (I think it is saved in 'pooler_output').
I am sorry to ask a question here. I was not sure where I can ask about this.

If I understand BERT correctly, we can compare similarity across different documents with this vector and
we can also compare similarity across different words with last_hidden_state vectors.

My question is 'are these two types of vectors are in the same embedding space and thus comparable to each other'?
Thanks.

**Comment by fcakyon** [comment]
Awesome question, I am also wondering the difference between `pooler_output` and `last_hidden_state` sgugger . It is not clear from the documentation.

**Comment by fcakyon** [comment]
I got my answer by checking the source code: https://github.com/huggingface/transformers/blob/92d4ef9ab038dfbbe02556375c4c3c14215b37d2/src/transformers/models/vit/modeling_vit.py#L553

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for questions like this, as we keep issues for bug reports and feature requests only :-)
