### ISSUE TITLE
tokenize_plus doesn't work when moving from pip to conda

### ISSUE THREAD

**Issue by crisz** [huggingface/transformers#14302]
## Environment info

- `transformers` version: 4.12.2
- Platform: macOS-11.6-arm64-arm-64bit
- Python version: 3.8.9
- PyTorch version (GPU?): 1.10.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

## Information

Model I am using (Bert, XLNet ...): Bert

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Install transformers from conda
2. Run the following code:
```
    for sentence in sentences:
        encoded_dict = tokenizer.encode_plus(
            sentence,  # Sentence to encode.
            add_special_tokens=True,  # Add '[CLS]' and '[SEP]'
            truncation=True,
            max_length=64,  # Pad & truncate all sentences.
            padding='max_length',
            return_attention_mask=True,  # Construct attn. masks.
            return_tensors='pt',  # Return pytorch tensors.
        )

        input_ids.append(encoded_dict['input_ids'])
        attention_masks.append(encoded_dict['attention_mask'])
```

3. Receive the following error message:
**TypeError: _tokenize() got an unexpected keyword argument 'truncation'**

## Expected behavior
The parameters of the `encode_plus` method to be consistent between pip and conda installations

**Comment by LysandreJik** [comment]
Hello! In your script, could you import `from transformers import __version__` and let me know what's the version shown? Thank you!

**Comment by crisz** [comment]
> Hello! In your script, could you import `from transformers import __version__` and let me know what's the version shown? Thank you!

Hello! it prints:
2.1.1

The same number version is printed when using the pip/venv environment. Also, "pip freeze" and "conda list" give the same version number

**Comment by LysandreJik** [comment]
That makes sense! The `encode_plus` method was not in the `transformers` version 2.1.1, which is now very old. How did you install `transformers` ? Both the `conda-forge` and the `huggingface` channels provide more recent versions than this one:
![image](https://user-images.githubusercontent.com/30755778/140613604-c5f0e9e7-122d-419b-a3c4-34ffc7ae1953.png)

**Comment by crisz** [comment]
> That makes sense! The `encode_plus` method was not in the `transformers` version 2.1.1, which is now very old. How did you install `transformers` ? Both the `conda-forge` and the `huggingface` channels provide more recent versions than this one: ![image](https://user-images.githubusercontent.com/30755778/140613604-c5f0e9e7-122d-419b-a3c4-34ffc7ae1953.png)

Thank you, I hadn't noticed that the version I was using was so much outdated. It was a fresh install, with no version specified, so I supposed that the *2.1.1* was the last version available. Instead, apparently, it installed the *2.1.1* because it was the latest compatible version, and the problem is somehow related to issue #13229. Downgrading the python version from 3.9 to 3.8 solved the problem
