### ISSUE TITLE
convert_graph_to_onnx.py quantization still has relative imports which break when running as a script.

### ISSUE THREAD

**Issue by nbertagnolli** [huggingface/transformers#14314]
It's my first issue so please let me know if I missed something I was supposed to include : ).

## Environment info
- `transformers` version: 4.12.3
- Platform: macOS-10.15.7-x86_64-i386-64bit
- Python version: 3.8.8
- PyTorch version (GPU?): 1.10.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@LysandreJik
@sgugger

I didn't quite know who to tag but I saw you two on a PR related to this in the past so figured that might be the right place to start.  Sorry if I got it wrong.

## Information

I'm converting a fine-tuned distillbert model to onnx.  Everything works fine when I don't run quantization, but if I try to quantize with the script.  For example by running:

`python transformers/convert_graph_to_onnx.py --framework pt --model distilbert-base-uncased --tokenizer=distilbert-base-uncased --quantize onnx/distilbert-toxic-uncased.onnx
`

I get:

`Error while converting the model: attempted relative import beyond top-level package`

I believe the problem occurs in lines 23-26 of transformers/onnx/convert.py.  When I change these relative imports to the main library transformers like you did in this PR [#10857](https://github.com/huggingface/transformers/pull/10857) everything seems to work : ).  I'd love to open a PR with this fix if you think that would be a good idea.

The problem arises when using:
* [ x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

1. cd Transformers/src
2. Run `python transformers/convert_graph_to_onnx.py --framework pt --model distilbert-base-uncased --tokenizer=distilbert-base-uncased --quantize onnx/distilbert-base-uncased.onnx`
3. You should get the error `Error while converting the model: attempted relative import beyond top-level package`

## Expected behavior

I expect that quantization should complete and generate the `distilbert-base-uncased-quantized.onnx` file

**Comment by nbertagnolli** [comment]
I have the fix on my fork and would love to open a PR if this is the right thing to do : ).  https://github.com/nbertagnolli/transformers/tree/bugfix/onnx-convert-script

**Comment by sgugger** [comment]
Thanks for flagging this. This looks like the right fix, so feel free to open a PR! :-)
