### ISSUE TITLE
How to return  bert self attention, so that i can do visualization??

### ISSUE THREAD

**Issue by alshahrani2030** [huggingface/transformers#1432]
## ❓ Questions & Help
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels= 2, output_attentions=True)
model.cuda()
I am useing the above code to return the attention weights, for visualizing the attention by BertViz.
But it gave me this error ( __init__( ) got an unexpected keyword argument 'output_attentions').
Also, please if you recommend any tutorial for beginner, which explain how to return the attention

**Comment by LysandreJik** [comment]
Hi! Could you specify which version of our library you are using? Thank you.

**Comment by alshahrani2030** [comment]
Hi
I am useing "pip install pytorch-pretrained-bert pytorch-nlp"

**Comment by LysandreJik** [comment]
I believe the way to output attentions in `pytorch-pretrained-BERT` v0.6.2 was to specify the `output_all_encoded_layers` to `True` in the model forward call.

Please be aware that this version has been deprecated for some time now. The new version is called `transformers` and should be installed with `pip install transformers`.

**Comment by alshahrani2030** [comment]
Thank for the quick reply
how about if i want to use transformers how to output the attention ??

**Comment by LysandreJik** [comment]
If you want to use transformers to output the attention you can specify it in the config:

```py
config = BertConfig.from_pretrained("bert-base-cased", output_attentions=True, num_labels=2)
model = BertForSequenceClassification.from_pretrained("bert-base-cased", config=config)
```

**Comment by alshahrani2030** [comment]
Thank you so much sir
during training i got this error!! any idea  
![erorr](https://user-images.githubusercontent.com/55197626/66278570-66cde580-e878-11e9-92ea-1d28ef500844.PNG)

**Comment by alshahrani2030** [comment]
> I believe the way to output attentions in pytorch-pretrained-BERT v0.6.2 was to specify the output_all_encoded_layers to True in the model forward call.
> Please be aware that this version has been deprecated for some time now. The new version is called transformers and should be installed with pip install transformers.

Do you mean some things like this
# Forward pass
loss = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels, output_all_encoded_layers = True)

**Comment by LysandreJik** [comment]
Yes, that’s what I meant!

**Comment by alshahrani2030** [comment]
> Yes, that’s what I meant!

I am getting  this error 
TypeError: forward() got an unexpected keyword argument 'output_all_encoded_layers'

**Comment by alshahrani2030** [comment]
> Yes, that’s what I meant!
This what I got. please help
![attention](https://user-images.githubusercontent.com/55197626/66332707-50b93700-e903-11e9-8533-d8ddd3dd4fe4.PNG)

**Comment by alshahrani2030** [comment]
> Yes, that’s what I meant!
I am getting this error. any idea please
TypeError: forward() got an unexpected keyword argument 'output_all_encoded_layers'
![attentionError](https://user-images.githubusercontent.com/55197626/66332937-e1901280-e903-11e9-8af6-0587d7a00296.PNG)

**Comment by LysandreJik** [comment]
Which version of the lib are you using in that example?

**Comment by alshahrani2030** [comment]
> Which version of the lib are you using in that example?

old one 
pytorch-pretrained-bert pytorch-nlp
