### ISSUE TITLE
Avoiding the time consuming for downloading the pre-trained models

### ISSUE THREAD

**Issue by ForawardStar** [huggingface/transformers#14336]
# 📚 Migration
Very great project! I can successfully run the code:

```
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("bert-base-chinese")
model_Bert = AutoModel.from_pretrained("bert-base-chinese")
```

But, every time I run my code, the downloading processing are repeated, which is time consuming. So I wonder how to load the pre-trained models from my local directory instead of downloading the pre-trained models everytime?

**Comment by zartdinov** [comment]
Hi! It should work
```python
# Load model from directory:
model = AutoModel.from_pretrained("./my_model_directory/")

# Save model to directory:
model.save_pretrained("./my_model_directory/") 

# Cache model to directory:
model = AutoModel.from_pretrained("bert-base-chinese", cache_dir="./my_model_directory/")
```

**Comment by ForawardStar** [comment]
Thanks! It is useful for me. One more question: I found that the files saved in "./my_model_directory/" do not contain 'vocab.txt', is it reasonable?

**Comment by zartdinov** [comment]
I think this file is only needed for the tokenizer. The tokenizer can also be saved in the same directory.

**Comment by LysandreJik** [comment]
When you do 
```
tokenizer = AutoTokenizer.from_pretrained("bert-base-chinese")
model_Bert = AutoModel.from_pretrained("bert-base-chinese")
```

this should be caching the files in your local cache, it shouldn't redownload the files every time. You shouldn't need to specify a local folder in which to save them.

How are you identifying that the files are redownloaded every time?

**Comment by earonesty** [comment]
> this should be caching the files in your local cache, it shouldn't redownload the files every time. You shouldn't need to specify a local folder in which to save them.

model cards are updated frequently.   so people re-download them a lot!
