### ISSUE TITLE
Can you get Q/A links from LayoutLM

### ISSUE THREAD

**Issue by gregg-ADP** [huggingface/transformers#14330]
We are fine tuning the LayoutLM model from microsoft and we can’t see where you can get the links from the inference output. We get the list of labels for each word (if it is a question, answer, title) but we don’t get the links from the question to the answer.
Can someone tell us where to find that?

I think @NielsRogge is an expert on this?

**Comment by NielsRogge** [comment]
Hi,

This is a question that is asked a lot. The LayoutXLM authors have implemented a `LayoutLMv2ForRelationExtraction`, of which an example script can be found [here](https://github.com/microsoft/unilm/tree/master/layoutxlm).

**Comment by gregg-ADP** [comment]
Thanks so much for the quick response @NielsRogge.  That does look like it will help with what we are looking for.  
Right now we are fixing dependency and other issues to get it running.  We will share what we learned so that the next person won't have to go through the fixes.

Thanks again!
