### ISSUE TITLE
how to config gpu for run_text_classification?

### ISSUE THREAD

**Issue by reneix** [huggingface/transformers#14347]
I'm using example script for a text classfication，it works well on my laptop without gpu, but not using gpu in a docker environment.
would you please help on it?

nvidia-smi returns: 
No running processes found

example script:
https://github.com/huggingface/transformers/tree/master/examples/tensorflow/text-classification
version:
tf 2.4.1
cudnn 10.0
transformers 4.12.3

**Comment by NielsRogge** [comment]
Hi,

As stated in the [README](https://github.com/huggingface/transformers/tree/master/examples/tensorflow/text-classification#multi-gpu-and-tpu-usage):

> By default, the script uses a MirroredStrategy and will use multiple GPUs effectively if they are available. TPUs can also be used by passing the name of the TPU resource with the --tpu argument.

**Comment by reneix** [comment]
thanks, seem tf2.4 need cuda11, I will check it first
