### ISSUE TITLE
BEIT masked lm

### ISSUE THREAD

**Issue by dar-tau** [huggingface/transformers#14349]
How can one generate labels for BEIT masked LM?

**Comment by NielsRogge** [comment]
Hi,

I've created a Colab notebook to illustrate `BeitForMaskedImageModeling` [here](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/BEiT/Understanding_BeitForMaskedImageModeling.ipynb).

**Comment by NielsRogge** [comment]
See also this issue: https://github.com/microsoft/unilm/issues/401

**Comment by dar-tau** [comment]
Thanks!

**Comment by yatsurama** [comment]
Hi @NielsRogge

did you have any progress in reproducing the masked visual tokens with BEiT so that they correspond to the ground truth labels? I am having the same issue.

Thanks

**Comment by NielsRogge** [comment]
Hi,

I'm pretty sure my implementation is correct. You can visualize the predictions of BeitForMaskedImageModeling using DALL-E's decoder.
