### ISSUE TITLE
Which model should I use for machine translation?

### ISSUE THREAD

**Issue by maurus56** [huggingface/transformers#1436]
## ❓ Questions & Help

I’m interested in training a model for translating articles from Spanish to English. There is too little information (Tutorials) about MT, should I use BERT, XLM or any other one? Also could you explain how to train the proposed model feeding the data, and output the predicted translation.
 And is there a way to use XLNet so when translating chapters of a book it can remember the context of the previous ones and better translate?

There is even a model by Microsoft ([MASS](https://github.com/microsoft/MASS)) that looks simple to use, would you recommend it?

**Comment by thomwolf** [comment]
Hi I recommend using XLM from Facebook for MT currently: https://github.com/facebookresearch/XLM
We may add some models for MT in the mid-term though.

**Comment by Bachstelze** [comment]
[MASS](https://arxiv.org/pdf/1905.02450.pdf) reports higher BLEU-scores than [XLM](https://arxiv.org/abs/1901.07291) which is good in pretraining an encoder, but lacks in the training description of the decoder. So we could try to extend the XML-R #1769 encoder with MASS.

**Comment by Bachstelze** [comment]
In which languages and domains are you interested?

**Comment by maurus56** [comment]
I'm looking for translation of Chinese to English, mainly books and articles so maintaining an overall consistency of the terms and words is crucial

**Comment by mahlettaye** [comment]
Please  help me on how to use xmlr for summarization?  Also if there is any example based on xmlr.
