### ISSUE TITLE
[Consistency] Automatically set decoder_input_ids for TFEncoderDecoderModel

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#14397]
# 🚀 Feature request

Currently, the `EncoderDecoderModel` class in PyTorch automatically creates the `decoder_input_ids` based on the `labels` provided by the user (similar to how this is done for T5/BART). This should also be implemented for `TFEncoderDecoderModel`, because currently users should manually provide `decoder_input_ids` to the model.

One can take a look at the TF implementation of BART for example to see how to shift the labels in order to automatically create the `decoder_input_ids`, namely [here](https://github.com/huggingface/transformers/blob/29dfb2dbb10cdba6327ff287db56b182c1db29b1/src/transformers/models/bart/modeling_tf_bart.py#L1120).

One should then also update the docstring correspondingly.

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is there anyone already working on it?

**Comment by NielsRogge** [comment]
No, you can work on it if you want!

**Comment by ankushbhatia2** [comment]
Hi, Is it still open? I can work on this issue

**Comment by NielsRogge** [comment]
There's a PR open (#14397), however it's not finished yet.

**Comment by hackyon** [comment]
I believe this issue has already been fixed as part of #14139.

**Comment by hackyon** [comment]
I believe this has already been resolved in #15175.

**Comment by byi8220** [comment]
It appears that way, this block appears to implement this functionality as part of the PR: https://github.com/huggingface/transformers/blob/831bc25d8fdb85768402f772cf65cc3d7872b211/src/transformers/models/vision_encoder_decoder/modeling_tf_vision_encoder_decoder.py#L572-L575

If this is true, would it make sense to close this issue?

**Comment by NielsRogge** [comment]
Closing this one as it has ben resolved by #15175. Thanks for reporting
