### ISSUE TITLE
force_bos_token_to_be_generated is depricated, should be replaced by forced_bos_token_id in BART documentation

### ISSUE THREAD

**Issue by kforkaran** [huggingface/transformers#14395]
Replace force_bos_token_to_be_generated in the following file

https://github.com/huggingface/transformers/blob/29dfb2dbb10cdba6327ff287db56b182c1db29b1/docs/source/model_doc/bart.rst

**Comment by NielsRogge** [comment]
Thanks for spotting. Feel free to open a PR to fix this!

**Comment by NielsRogge** [comment]
Closing, as it's fixed by #14434
