### ISSUE TITLE
support for pytorch-directml

### ISSUE THREAD

**Issue by kotoroshinoto** [huggingface/transformers#14409]
# 🚀 Feature request

I would like to be able to work with the available models and trainer classes when using pytorch-directml under WSL

## Motivation

importing relevant huggingface packages results in a message that pytorch could not be detected and as such the models would not be available. there is an importable torch module though, provided by the pytorch-directml package.

## Your contribution

I'm not sure how many changes would be required to make this work. If the features of the fork of pytorch are close to the newest release, it wouldn't be much, but I do know that the directml implementation for tensorflow is quite out of date. (using 1.15 instead of 2 or greater)

**Comment by LysandreJik** [comment]
Hello! If you can provide a reproducible example, we're happy to take a look!

It's probably a matter of adding `pytorch-directml` to this part of the `file_utils.py` file:

https://github.com/huggingface/transformers/blob/558f8543ba3860c736a7a9a4176ac20f23f9d5a0/src/transformers/file_utils.py#L67-L77

Like it is done here for many TensorFlow flavors:

https://github.com/huggingface/transformers/blob/558f8543ba3860c736a7a9a4176ac20f23f9d5a0/src/transformers/file_utils.py#L80-L112

**Comment by B4ngB4ng** [comment]
`pytorch-directml` replces `torch`
But `transformers` dont recognice/accept it  

https://pypi.org/project/pytorch-directml/
https://docs.microsoft.com/en-us/windows/ai/directml/dml-intro
