### ISSUE TITLE
Add documentation for exporting TorchScript model to accelerator

### ISSUE THREAD

**Issue by kct22aws** [huggingface/transformers#14425]
# 🚀 Feature request

Add examples about how to trace a TorchScript transformer model and deploy it in an accelerator such as [AWS Inferentia](https://aws.amazon.com/machine-learning/inferentia/ "Inferentia accelerator"). 

## Motivation
Communicated with @philschmid. HuggingFace transformer models can be traced to TorchScript models and run on accelerators. We would like to help HF transformer users save the cost of deploying and running HF transformer models at scale. We wish to upstream additional documentation showing minimal code updates to deploy traced TorchScript model in an accelerator. 

## Your contribution

Example code snippet to trace and deploy a TorchScript model in an accelerator such as [AWS Inferentia](https://aws.amazon.com/machine-learning/inferentia/ "Inferentia accelerator")

**Comment by LysandreJik** [comment]
That sounds good! We'd welcome a section about deploying a TorchScript model in AWS Inferentia! Ideally this would be under a new documentation page "deployment". You can take inspiration from either the RST [serialization page](https://github.com/huggingface/transformers/blob/master/docs/source/serialization.rst) or the MD [migration page](https://github.com/huggingface/transformers/blob/master/docs/source/migration.md).

You should then add a link to it in the index [here](https://github.com/huggingface/transformers/blob/master/docs/source/index.rst). Thank you, and let @philschmid or I know if you need any help!

**Comment by DevBey** [comment]
Hi @kct22aws ,

Please let me know if you need any help regarding this as we also have several huggingface and custom models running in AWS inferentia !!
