### ISSUE TITLE
Tracing LayoutLMv2 results in wrong input_shape dimension

### ISSUE THREAD

**Issue by mikkeldenker** [huggingface/transformers#14457]
## Environment info

- `transformers` version: 4.11.3
- Platform: macOS-12.0-arm64-arm-64bit
- Python version: 3.9.0
- PyTorch version (GPU?): 1.10.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help

@NielsRogge 

## Information

When tracing the LayoutLMv2 model, I get the following error:
```
RuntimeError: The expanded size of the tensor (561) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [1, 561].  Tensor sizes: [1, 512]
```

This seems to be caused by [this line](https://github.com/huggingface/transformers/blob/efea0f868bd381244e3cef51b388293e41a36d1e/src/transformers/models/layoutlmv2/modeling_layoutlmv2.py#L862) in the model. I think pytorch might be reusing the memory for `final_shape` and `input_shape` when tracing, so when `final_shape` is updated it also updates `input_shape` which leads to the mismatch in dimensions later on. I've currently solved the problem by changing the shapes to 
```
final_shape = list(torch.empty(size=input_shape).size())
visual_shape = list(torch.empty(size=input_shape).size())
```

I've also changed `visual_shape` for good measure, but it doesn't really seem to be necessary. With the above changes I'm able to successfully trace the model. It seems a bit overkill to allocate an entire new tensor, just to get a copy of the shape but I didn't really find any other solution. Please let me know if there is a better solution.

I'm happy to submit a PR with the fixes if you want.

## To reproduce

1. Initialise `LayoutLMv2Model`
2. Trace the model using `torch.jit.trace`

**Comment by NielsRogge** [comment]
Hi,

Thanks for working on making LayoutLMv2 torchscriptable. It would indeed be great if you can open a PR for this.

Also, if LayoutLMv2 works with TorchScript, we can update tests/test_modeling_layoutlmv2.py, to also take into account the TorchScript tests (as these are not run right now as seen [here](https://github.com/huggingface/transformers/blob/efea0f868bd381244e3cef51b388293e41a36d1e/tests/test_modeling_layoutlmv2.py#L262)).

**Comment by mikkeldenker** [comment]
That's really the least I can do compared to how you guys make NLP easily accessible to everyone. So thank you for all your amazing work!

I've created a pull request that should fix the issue, and will therefore close this. We can continue the discussion in the PR if needed.
