### ISSUE TITLE
Performance degradation with new version of this library (inference)

### ISSUE THREAD

**Issue by mgrankin** [huggingface/transformers#1445]
## 🐛 Bug

Model I am using (Bert, XLNet....): GPT-2

Language I am using the model on (English, Chinese....): Russian

The problem arise when using:
* [ ] the official example scripts: (give details)
* [ x] my own modified scripts: (give details)

I do inference with a bit modified run_generation.py

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ x] my own task or dataset: (give details)
I'm training Russian GPT-2

## To Reproduce

1. Use pytorch-tranformers library (1.2)
2. Use sample_sequence from run_generation.py on GPU
3. Use tranformers library (2.0)
4. Use sample_sequence from run_generation.py on GPU
5. Step 4 is running 5 times slower than step 2. 

## Expected behavior

The speed probably should stay the same.

## Environment

* OS: Ubuntu 18.04
* Python version: 3.7.3
* PyTorch version: 
* PyTorch Transformers version (or branch): 1.2 vs 2.0
* Using GPU  - yes
* Distributed of parallel setup - no
* Any other relevant information:

## Additional context
https://github.com/mgrankin/ru_transformers

**Comment by mgrankin** [comment]
I'm so sorry, I haven't replaced all occurrences of pytorch-tranformers to tranformers. That was the source of the problem.

**Comment by LysandreJik** [comment]
Glad to hear that!
