### ISSUE TITLE
Patrick von Platen

### ISSUE THREAD

**Issue by aheirich** [huggingface/transformers#14451]
Dear Patrick von Platen
I have some questions about the use of Helsinki-NLP models in commercial projects, can you please contact me by email?  alan.heirich@gmail.com

Sorry to use this issue tracker, I know of no other way to reach Patrick.

**Comment by qqaatw** [comment]
Thank you @aheirich for opening this issue, allowing me to take this opportunity to reach Patrick.

Dear Patrick von Platen,

I've sent two emails to you in recent two weeks about the internship in Hugging Face, can you please reply me by email? 

qqaatw[at]gmail.com

Thank you in advance!
