### ISSUE TITLE
GPT2 Generate doesn't pass the user defined past_key_values.

### ISSUE THREAD

**Issue by KnightZhang625** [huggingface/transformers#14454]
## Environment info

- `transformers` version:
- Platform: MacOS Intel
- Python version: 3.7.10
- PyTorch version (GPU?): '1.8.1' (CPU)
- Tensorflow version (GPU?): '1.15.0' (CPU)
- Using GPU in script?: Nope
- Using distributed or parallel set-up in script?: Nope

## Information

Bug in Huggingface Transformers "generate" for Auto-Regression Model (like GPT-2). If you wanna pass your own "past_key_values", the function will not pass it to the model as you wish. 

## To reproduce

Send used defined "past_key_values" to the generate() function, the "past_key_values" in model forward() should be none.

**Comment by patrickvonplaten** [comment]
Hey @KnightZhang625, 

Could you please provide a reproducible code-snippet?
