### ISSUE TITLE
facebook / wav2vec2-base-100k-voxpopuli fails to load on huggingface.co (also on system)

### ISSUE THREAD

**Issue by genevera** [huggingface/transformers#14479]
## Environment info
- `transformers` version: 4.13.0.dev0
- Platform: macOS-11.6.1-arm64-arm-64bit
- Python version: 3.9.7
- PyTorch version (GPU?): 1.10.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: idk

### Who can help
@patrickvonplaten, @anton-l

Library:

- Tokenizers: @LysandreJik
- Speech: @patrickvonplaten, @anton-l

Model hub:

- for issues with a model, report at https://discuss.huggingface.co/ and tag the model's creator

## Information

Model I am using (wav2vec2-base-100k-voxpopuli):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] my own task or dataset: (give details below)

Error message in browser is same as on cli:
![image](https://user-images.githubusercontent.com/12733137/142779290-95feda63-237a-42e8-8ca4-2ad08c7706c6.png)

## To reproduce

on huggingface.co:
1. Load https://huggingface.co/facebook/wav2vec2-base-100k-voxpopuli
2. Upload a file to analyze
3. Click the Compute button

Here is a cli script that fails in the same way:
```python3
from transformers import Wav2Vec2FeatureExtractor, Wav2Vec2Processor, Wav2Vec2ForCTC, Wav2Vec2CTCTokenizer
import librosa as lb
import torch
import numpy

model_name='facebook/wav2vec2-base-100k-voxpopuli'


# FE
feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(model_name)

# Initialize the tokenizer
tokenizer = Wav2Vec2CTCTokenizer.from_pretrained(model_name)

# Initialize the model
model = Wav2Vec2ForCTC.from_pretrained(model_name)

# we need a processor, too
processor = Wav2Vec2Processor(feature_extractor,tokenizer)

# Read the sound file
waveform, rate = lb.load('./DD000.wav', sr = 16000)

# process
input_values = processor(waveform, sampling_rate=16000, return_tensors='pt').input_values

# Retrieve logits from the model
logits = model(input_values).logits

# Take argmax value and decode into transcription
predicted_ids = torch.argmax(logits, dim=-1)
transcription = tokenizer.batch_decode(predicted_ids)

# Print the output
print(transcription)
```

Running it nets you:
```bash
traceback (most recent call last):
  File "/Users/genevera/src/ml/transformers/examples/./wave2vec_stt.py", line 13, in <module>
    tokenizer = Wav2Vec2CTCTokenizer.from_pretrained(model_name)
  File "/Users/genevera/.pyenv/versions/miniforge3-4.10.1-5/envs/trans/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1733, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load tokenizer for 'facebook/wav2vec2-base-100k-voxpopuli'. Make sure that:

- 'facebook/wav2vec2-base-100k-voxpopuli' is a correct model identifier listed on 'https://huggingface.co/models'
  (make sure 'facebook/wav2vec2-base-100k-voxpopuli' is not a path to a local directory with something else, in that case)

- or 'facebook/wav2vec2-base-100k-voxpopuli' is the correct path to a directory containing relevant tokenizer files
```

## Expected behavior
I would expect the file to be analyzed without an error message about the tokenizer.

**Comment by LysandreJik** [comment]
@anton-l can chime in if I'm wrong, but I believe that it is expected that you should create your vocabulary as shown in https://huggingface.co/blog/fine-tune-wav2vec2-english

This could be made clearer in the model card, wdyt @anton-l?
