### ISSUE TITLE
Unable to load DeBERTa-v3 tokenizer

### ISSUE THREAD

**Issue by maiiabocharova** [huggingface/transformers#14470]
```
from transformers import AutoTokenizer
  
tokenizer = AutoTokenizer.from_pretrained("microsoft/mdeberta-v3-base")
```
Gives me an error:
ValueError: This tokenizer cannot be instantiated. Please make sure you have `sentencepiece` installed in order to use this tokenizer.
Installing sentencepiece doesn't help.

**Comment by maiiabocharova** [comment]
> Hello! Could you please share your environment information? Thanks.

Hello, sure! transformers==4.12.5, python 3.7. I am using Colab for experiments

**Comment by LysandreJik** [comment]
If you're using colab, then have you restarted the runtime after installing `sentencepiece`?

**Comment by maiiabocharova** [comment]
> If you're using colab, then have you restarted the runtime after installing `sentencepiece`?

Thank you!!! It solved the issue. Thank you once again!

**Comment by LysandreJik** [comment]
Glad to hear it!
