### ISSUE TITLE
Where do I find the class documentation

### ISSUE THREAD

**Issue by avnerbarr** [huggingface/transformers#14475]
Stupid question:

The website is great and all, but where do I find the FULL code documentation for the APIs (i.e. pydoc or something)? For instance any time a class is "highlighted" , i.e. `model` I would expect to be able to click on it and see the full set of functions/properties it provides.

Also, navigating the website is cumbersome. The left menu doesn't scroll to the section you are currently visiting, the additional nested sections (headers) for that subject should always be visible (and have a always visible "+" icon in the menu pane) to be easier to navigate to. I find myself clicking away (since I might have forgotten under what something is nested under) , going back and forth etc. because of that. 

Thanks!

**Comment by LysandreJik** [comment]
Hy @avnerbarr, the documentation is undergoing a large refactor which should be out in a couple of days, and which should hopefully resolve most of your pain points, stay tuned.

**Comment by LysandreJik** [comment]
Hey @avnerbarr, do you have any feedback of the new documentation frontend?

**Comment by avnerbarr** [comment]
seems much better. I'll update once I start working with it 👍
