### ISSUE TITLE
How do I preserve HTML structure when putting data through transformers

### ISSUE THREAD

**Issue by brianSERP-Ai** [huggingface/transformers#14474]
I am trying to create a bulk paraphrasing tool. I have managed to get everything working fine with normal text but now I would like to also keep the <html> structure intact.  Can anyone give me some tips on how to achieve this? When I put html through the models it is removed in the output.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
