### ISSUE TITLE
Can't replicate Language Model finetuning

### ISSUE THREAD

**Issue by kristjanArumae** [huggingface/transformers#1449]
I cannot replicate BioBERT results by using finetune_on_pregenerated.py with data generated using pregenerate_training_data.py.  

I've noticed that the LM code has been removed from the repo in that last couple versions.  Does this mean there were known issues with this process?

**Comment by LysandreJik** [comment]
Hello, this language model fine-tuning was community-maintained and is now deprecated. The example script to fine-tune on language modeling is now `run_lm_finetuning.py`.
