### ISSUE TITLE
LayoutXLMProcessor applies the english Tesseract model

### ISSUE THREAD

**Issue by Xargonus** [huggingface/transformers#14511]
# 🚀 Feature request
LayoutXLMProcessor.\_\_call\_\_ should support a language argument for Tesseract OCR

## Motivation

LayoutXLM is a multilingual version of the successful LayoutLMv2 model. The main reason to use it over LayoutLMV2 is to handle different languages, yet the current API does not allow specifying the language to be used in apply_tesseract.

## Your contribution

I could submit a PR but I am not that familiar with the Transformers library to suggest the best place to add the lang argument.

**Comment by NielsRogge** [comment]
Hi,

Great point, thanks for the feature request.

It would be rather straightforward: one should just add a lang parameter to [this line](https://github.com/huggingface/transformers/blob/956a483173e77ebf655ca9636a5f7b6ef010b307/src/transformers/models/layoutlmv2/feature_extraction_layoutlmv2.py#L54).

Can you open a PR for this?
