### ISSUE TITLE
TAPAS tokenizer is unable to handle indexed dataframes

### ISSUE THREAD

**Issue by xhlulu** [huggingface/transformers#14544]
Running the following code will result in a `iloc` error:

```python
from transformers import TapasTokenizer
import pandas as pd

model_name = 'google/tapas-base'
tokenizer = TapasTokenizer.from_pretrained(model_name)

data = {'Actors': ["Brad Pitt", "Leonardo Di Caprio", "George Clooney"], 'Number of movies': ["87", "53", "69"]}
queries = ["What is the name of the first actor?", "How many movies has George Clooney played in?", "What is the total number of movies?"]
answer_coordinates = [[(0, 0)], [(2, 1)], [(0, 1), (1, 1), (2, 1)]]
answer_text = [["Brad Pitt"], ["69"], ["209"]]
table = pd.DataFrame.from_dict(data)

# Let's add random years - this will break the tokenzier
table.index = [2000, 2010, 2020]

inputs = tokenizer(table=table, queries=queries, answer_coordinates=answer_coordinates, answer_text=answer_text, padding='max_length', return_tensors='pt')
inputs
```

**Comment by NielsRogge** [comment]
Hi,

This has been reported before in #10265. Would you mind opening a PR to fix this?

**Comment by xhlulu** [comment]
@NielsRogge I started a PR here: https://github.com/huggingface/transformers/pull/14549

I'm not sure if it totally solves the problem, but it's a start

**Comment by xhlulu** [comment]
@NielsRogge I'm looking about at this comment right now:

> Here's a notebook illustrating the issue, and fixing it:
> 
> https://colab.research.google.com/drive/10MbZiMKyEWUGk2Y1fvIj0Y0_lB42NO38?usp=sharing
> 
> The reason why you're getting the error is because in the part where each cell of the table is replaced by a Cell object:
> 
> https://github.com/huggingface/transformers/blob/97e688bc220514cd5ea072f06b186401c9cfbbd0/src/transformers/models/tapas/tokenization_tapas.py#L2742-L2745
> , the row indices are used.
> 
> This can be fixed by replacing `table` with `table.reset_index(drop=True)` in the first line (or resetting the index of the table before providing it to the tokenizer). Another solution is to replace the final line by `table.iloc[row_index, col_index] = Cell(text=table.iloc[row_index, col_index])`. Will make a small PR to add this.
> 
> Thank you for spotting the error!


I'm wondering if there's any performance improvement in iterating this way through the dataframe over something like:

```
df.applymap(lambda cell: Cell(text=cell)
```

**Comment by xhlulu** [comment]
@NielsRogge has this been resolved?
