### ISSUE TITLE
Huggingface Missing Larger T5 Flax Models

### ISSUE THREAD

**Issue by kev-zhao** [huggingface/transformers#14550]
## Environment info

- `transformers` version: 4.12.5
- Platform: Linux-5.4.0-90-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.8.1+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.3.5 (gpu)
- Jax version: 0.2.17
- JaxLib version: 0.1.65
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help

@patrickvonplaten, @patil-suraj

## Information

Model I am using (Bert, XLNet ...): T5

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

`404 Client Error: Not Found for url: https://huggingface.co/t5-large/resolve/main/flax_model.msgpack`

## To reproduce

```
import jax.numpy as jnp
import transformers

model = transformers.FlaxT5ForConditionalGeneration.from_pretrained("t5-large", dtype=jnp.dtype("bfloat16"))
```

## Expected behavior

For `https://huggingface.co/t5-large/resolve/main/flax_model.msgpack` to exist and used to load the model.

As the corresponding URLs for `t5-small` and `t5-base` work, I'm assuming the files for larger models just haven't been uploaded yet. I only need `t5-11b`, although I would prefer to perform sanity checks on the large or 3B versions first.

**Comment by patrickvonplaten** [comment]
Thanks for the issue - just uploaded it: https://huggingface.co/t5-large/blob/main/flax_model.msgpack

**Comment by mohammad-al-zoubi** [comment]
I just noticed that the Flax checkpoints for t5-3b and t5-11b are also missing. 

@patrickvonplaten is it also possible that you upload them? Thanks!
