### ISSUE TITLE
questions on checkpoint and 'training_args.bin' in run_lm_finetuning.py

### ISSUE THREAD

**Issue by molsheim** [huggingface/transformers#1456]
## ❓ Questions & Help

2 questions:

1. there is a **checkpoint** save logical, but don't see any logical to load this checkpoint. nothe load method in code
1. there is '**training_args.bin**' has been store with checkpoint together. no load code to support it. 

could you please tell how to use these checkpoint and 'training_args.bin' to **continue** training?
thanks.

**Comment by LysandreJik** [comment]
The model saved can be loaded by using the `model.from_pretrained(directory)` method. The training arguments are saved so that they can be re-used later. You can load them using the `torch.load(directory/training_args.bin)` method.

**Comment by molsheim** [comment]
thanks for reply.

**Comment by CrasCris** [comment]
> The model saved can be loaded by using the `model.from_pretrained(directory)` method. The training arguments are saved so that they can be re-used later. You can load them using the `torch.load(directory/training_args.bin)` method.

if i'm using a pretraining model (TrOCR) , what are the necessary and enought file to use it in production ?, the folder have like 6 files 8
