### ISSUE TITLE
when running run_squad.py it is showing no progress . stuck after feature building

### ISSUE THREAD

**Issue by vikrant094** [huggingface/transformers#1457]

**Comment by vikrant094** [comment]
when i use  
export SQUAD_DIR=/path/to/SQUAD  
python run_squad.py \   --model_type bert \   --model_name_or_path bert-base-cased \   --do_train \   --do_eval \   --do_lower_case \   --train_file $SQUAD_DIR/train-v1.1.json \   --predict_file $SQUAD_DIR/dev-v1.1.json \   --per_gpu_train_batch_size 12 \   --learning_rate 3e-5 \   --num_train_epochs 2.0 \   --max_seq_length 384 \   --doc_stride 128 \   --output_dir /tmp/debug_squad/

it is showing no progress. no gpu utilization.

**Comment by vikrant094** [comment]
like this



 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
10/08/2019 15:32:45 - INFO - utils_squad -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
10/08/2019 15:32:45 - INFO - utils_squad -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
10/08/2019 15:32:45 - INFO - utils_squad -   start_position: 49
10/08/2019 15:32:45 - INFO - utils_squad -   end_position: 50
10/08/2019 15:32:45 - INFO - utils_squad -   answer: the 1870s

**Comment by vikrant094** [comment]
what is the meaning of this????

**Comment by vikrant094** [comment]
wait for 10-15 min ...it will work.

**Comment by LysandreJik** [comment]
Hi, the program probably didn't hang but was still converting the examples to features, which can be a timely process.
If you want to have more information, you could always add a print statement notifying you of the current index it is converting to feature.

Please note that once you have done this conversion to features, these will be cached on your disk to be used the next time. This conversion is only done once.

**Comment by cockroachzl** [comment]
I observed exactly the same, it took 18 minutes to log the next line in a p3.2xlarge host. Would be great to parallelize this portion(I notice only one cpu is running in this period.), and show a progress bar for converting the examples to features.

```
10/27/2019 02:45:46 - INFO - utils_squad -   start_position: 47
10/27/2019 02:45:46 - INFO - utils_squad -   end_position: 48
10/27/2019 02:45:46 - INFO - utils_squad -   answer: the 1870s
10/27/2019 03:03:05 - INFO - __main__ -   Saving features into cached file /home/ubuntu/SQuAD-explorer/dataset/cached_train_bert-base-uncased_384
10/27/2019 03:05:09 - INFO - __main__ -   ***** Running training *****
```

**Comment by ahotrod** [comment]
@cockroachzl @vikrant094
If you're running on a Linux variant OS you might try adding **`export OMP_NUM_THREADS=x`**  at the top of your script file, where x is the number of cores, not threads, of your CPU.  With this script file addition on my Ubuntu 18.04 machine, examples-to-features uses 2 of my 6 CPUs @ 100%, instead of just a single CPU.
