### ISSUE TITLE
Config overrides option working on any kind of config

### ISSUE THREAD

**Issue by michaelbenayoun** [huggingface/transformers#14587]
# 🚀 Feature request

Allow the `--config_overrides` option in language-modeling examples to override a config that was specified by `--config_name` or `--model_name_or_path`, currently this is blocked by:
```python
if self.config_overrides is not None and (self.config_name is not None or self.model_name_or_path is not None):                                                    
            raise ValueError(                                                                                                                                              
                "--config_overrides can't be used in combination with --config_name or --model_name_or_path"                                                               
            )  
```

## Motivation

It is unclear why this is prevented, and it can make things a lot easier when tweaking the settings compared to having to edit a json file everytime. Is there a good reason for not allowing that?

## Your contribution

I can create a PR and make the changes myself.

**Comment by stas00** [comment]
If I remember correctly, it's because the transformers logic prevents us from overriding config if either of those 2 are defined.

I'm sure you will see it immediately if you remove the constraint.

If you find a good way to fix it, by all means please do.
