### ISSUE TITLE
Recover when the `sha` of the local file is not correct.

### ISSUE THREAD

**Issue by Narsil** [huggingface/transformers#14603]
## Environment info

- `transformers` version: `master` (probably any version)
- Platform: ubuntu
- Python version: 3.9
- PyTorch version (GPU?): 1.10
- Tensorflow version (GPU?): X
- Using GPU in script?:no
- Using distributed or parallel set-up in script?:no

### Who can help

@LysandreJik 

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. If a model get incorrectly downloaded or corrupted later. You will end up in an incorrect state where `from_pretrained` won't work anymore.

Script to create incorrect state artificially:
```python
  import os
  from transformers import AutoModel
  from transformers.file_utils import cached_path, hf_bucket_url


model_id = "Narsil/small2"
  model = AutoModel.from_pretrained(model_id)
  path = cached_path(hf_bucket_url(model_id, "pytorch_model.bin"))
  os.remove(path)
  with open(path, "w") as f:
      f.write("")

  model = AutoModel.from_pretrained(model_id) # Triggers an unrecoverable error
```

## Expected behavior

Since we still have `.json` that contains the  expected `etag` we can actually check the file against it and trigger a redownload in such situations instead.

Roughly I expect to get a warning that something was wrong with my local file compared to what was expected and that it will attempt to download again, download again and work (if there's nothing obviously wrong there).

(I actually expect for the sha to be run regularly too, even if it's expensive, if someone modified my weights under me, and they're still loadable, I can have big mistakes occurring, no ? I can see users doing cp `mymodel/pytorch_model.bin ~/.cache/..../232323.232aedc`.)

**Comment by LysandreJik** [comment]
That's interesting. We have the `force_download` option which you can use to force a redownload in case of a corrupted file, but your approach doesn't have any drawbacks that I am aware of.
