### ISSUE TITLE
datasets doesn't support NSP? should I implement my custom DataCollator or function for dataset.map?

### ISSUE THREAD

**Issue by dancingpipi** [huggingface/transformers#14614]
As the title, I haven't find NSP dataset, there is only transformers.TextDatasetForNextSentencePrediction, but it's not work while loading data by `load_dataset(...)`.

So have I to implement my custom DataCollator or function for dataset.map? Which one is better?

Or I miss something?

**Comment by LysandreJik** [comment]
Pinging @sgugger

**Comment by sgugger** [comment]
Yes, you have to implement your own function for preprocessing the data.
