### ISSUE TITLE
How can I use a TensorFlow 2.0 model for Named-Entity-Recognition (NER)? (using TFBertForTokenClassification )

### ISSUE THREAD

**Issue by romulocosta100** [huggingface/transformers#1461]
## ❓ Questions & Help

How can I use a TensorFlow 2.0 model for Named-Entity-Recognition (NER)? (using TFBertForTokenClassification )

**Comment by vpertsas** [comment]
Exactly the same question here! Can someone please provide us with a small tutorial or even some general guidelines?

**Comment by amankedia** [comment]
Any response here? I was looking for something similar
