### ISSUE TITLE
to use FX - your torch version must be *exactly* 1.9, even though fx also works in later versions

### ISSUE THREAD

**Issue by sdtblck** [huggingface/transformers#14632]
[this line](https://github.com/huggingface/transformers/blob/3977b58437b8ce1ea1da6e31747d888efec2419b/src/transformers/file_utils.py#L375) checks that the torch version matches 1.9 exactly, even though fx is available in 1.9+ (i.e torch 1.10).

To use it in torch 1.10, i had to do the following, and the symbolic trace worked just fine, so i'm not sure that this strict versioning is necessary:

```python
from transformers import GPTNeoForCausalLM
import torch
from transformers.models.gpt_neo.modeling_gpt_neo import GPTNeoSelfAttention
from transformers.utils.fx import symbolic_trace
import transformers 

transformers.utils.fx.is_torch_fx_available = lambda: True

model = GPTNeoForCausalLM.from_pretrained("EleutherAI/gpt-neo-125M")

g = symbolic_trace(model)

print(g)
```

**Comment by LysandreJik** [comment]
cc @michaelbenayoun, what's the status of our support of torch fx?

**Comment by michaelbenayoun** [comment]
Currently working on a PR (#14321), that should be merged soon, it should allow to use symbolic trace for torch 1.10 and above.
