### ISSUE TITLE
bert ids

### ISSUE THREAD

**Issue by alshahrani2030** [huggingface/transformers#1463]
## ❓ Questions & Help
after I Use the BERT tokenizer to convert the tokens to their index numbers in the BERT vocabulary

input_ids = [tokenizer.convert_tokens_to_ids(x) for x in tokenized_texts]

How I can convert them back to the original sentence???

Thank you in advance

**Comment by LysandreJik** [comment]
Hello, you should take a look at the `encode` and `decode` methods in the [documentation](https://huggingface.co/transformers/main_classes/tokenizer.html#transformers.PreTrainedTokenizer.decode).

**Comment by alshahrani2030** [comment]
Thank you so much that was very helpful

**Comment by LysandreJik** [comment]
Glad I could help!

**Comment by alshahrani2030** [comment]
Hi



![1](https://user-images.githubusercontent.com/55197626/66767034-88812b00-ee7d-11e9-9f93-e46da71e1062.PNG)
![2](https://user-images.githubusercontent.com/55197626/66767036-8919c180-ee7d-11e9-8501-4c581a3c7e0a.PNG)

**Comment by alshahrani2030** [comment]
Hi 
I am trying to use the code in this link (https://colab.research.google.com/drive/1pS-eegmUz9EqXJw22VbVIHlHoXjNaYuc#scrollTo=JggjeDC9m2MH) to plot my trained  model
But, I am getting an error. any idea please??
![1](https://user-images.githubusercontent.com/55197626/66767341-2ecd3080-ee7e-11e9-9bc7-4b6f93654793.PNG)
![2](https://user-images.githubusercontent.com/55197626/66767342-2ecd3080-ee7e-11e9-8aac-8743151a95b9.PNG)
