### ISSUE TITLE
Dynamic Inputs for fx traced GPTNeoLM 

### ISSUE THREAD

**Issue by sdtblck** [huggingface/transformers#14633]
# 🚀 Feature request

I've been looking a little into using torch.fx + HF lately, and run into a problem that the traced GPTNeoLM can't take dynamic inputs - would love to know what work would be needed to enable that, and what the current blockers are - it would be great to be able to use the traced module for inference.

I'm assuming the problem has something to do with caching of keys/values?

## Your contribution

Given guidance, I could put some work into adding this feature, yes :)

**Comment by LysandreJik** [comment]
cc @michaelbenayoun

**Comment by michaelbenayoun** [comment]
Hi @sdtblck ,
The issue with dynamic inputs is not related to the `past_key_values` but to dynamic control-flow in the model forward pass implementation. The PR #14321, that I plan to merge at some point (hopefully before the end of the year) solves this kind of issues for the supported models.
