### ISSUE TITLE
Missing weight parameter when loading from deepspeed stage-2

### ISSUE THREAD

**Issue by Atharva-Phatak** [huggingface/transformers#14653]
Converting deepspeed_zero_stage_2 to fp32 misses some parameters. I was finetuning bart-large using deepspeed_stage_2. I converted to fp32 checkpoints(using zero_to_fp32.py) and got a .bin file.

When I try to load this model using model.load_state_dict(path_to_bin_file) I get the following keys missing error.
"model.embed.tokens.weight" ?

I am using using pytorch-lightning for training.

**Comment by LysandreJik** [comment]
Maybe @stas00 has encountered this error in the past

**Comment by stas00** [comment]
Since you were using PL, you probably want to ask that question there. Since I don't know how they did the Deepspeed integration.

i.e. this question is unrelated to `transformers`
