### ISSUE TITLE
Wrong link in the documentation (ConvBERT, BART, Fnet)

### ISSUE THREAD

**Issue by Tikquuss** [huggingface/transformers#14667]
In the documentation on transform-based models [0], the link that is supposed to point to the **ConvBERT** paper [1, 2] points instead to the **DistilBERT** paper [3].

[0] https://huggingface.co/docs/transformers
[1] https://huggingface.co/docs/transformers/model_summary#convbert
[2] https://arxiv.org/pdf/2008.02496.pdf
[3] https://arxiv.org/pdf/1910.01108.pdf

**Comment by LysandreJik** [comment]
Nice catch! Would you like to submit a PR to amend this?

**Comment by Tikquuss** [comment]
Sure ! As soon as I finish reading the documentation, to avoid making two PRs in case I find another error.

**Comment by Tikquuss** [comment]
Going through the documentation I found an error and a warning. I'll make a PR about it. I just want to note that I didn't do a documentation review, I stumbled upon these errors by coincidence: my remarks should therefore not be considered an absolute documentation review.

# Fnet [1]
At the level of model documentation, the label corresponding to FNet is rather FlauBERT (see screenshot below)

![fnet](https://user-images.githubusercontent.com/49171640/145333383-08cd58e6-4739-403b-943c-b4fd48fb39ab.jpg)


# BART [2]
At the level of the model documentation, the link that points to the BART authors' code points to a github branch that has been modified [3, 4].

[1] https://huggingface.co/docs/transformers/model_doc/fnet
[2] https://huggingface.co/docs/transformers/model_doc/bart#overview
[3] https://github.com/pytorch/fairseq/tree/master/examples/bart
[4] https://github.com/pytorch/fairseq/tree/main/examples/bart

**Comment by LysandreJik** [comment]
@mishig25 do you know where this could come from?

**Comment by mishig25** [comment]
@LysandreJik https://github.com/huggingface/transformers/pull/14704
