### ISSUE TITLE
Loading t5 from config file

### ISSUE THREAD

**Issue by hadifar** [huggingface/transformers#14674]
Why cannot load T5 from a config file? 

Python: 3.9.5
Transformer: 4.12.5
OS: ubuntu 18.04
CPU

```
from transformers import (
    AutoConfig, T5Model, T5ForConditionalGeneration, T5Config,
)


config = AutoConfig.from_pretrained('t5-small')
model = T5ForConditionalGeneration.from_pretrained(config)

```

Here is the link to reproduce the issue in colab:

https://colab.research.google.com/drive/17tKE50_CGH12I-McVrob7JfFkveOH6Mc?usp=sharing

**Comment by NielsRogge** [comment]
This is due to the fact that the "architectures" attribute of the [config](https://huggingface.co/t5-small/blob/main/config.json#L3) of the "t5-small" checkpoint is set to `T5WithLMHeadModel`, however it was renamed to `T5ForConditionalGeneration`.

**Comment by patrickvonplaten** [comment]
@hadifar if you want to load the model from scratch with a specific config you can do:

```python
config = AutoConfig.from_pretrained('t5-small')
model = T5ForConditionalGeneration(config)
```

if you want to load the pretrained weights with a specific config (that matches the weights) you should do:

```python
config = AutoConfig.from_pretrained('t5-small')
model = T5ForConditionalGeneration.from_pretrained('t5-small', config)
```
