### ISSUE TITLE
[Feature request] Doc example copy button - option to remove input prompts and outputs

### ISSUE THREAD

**Issue by ydshieh** [huggingface/transformers#14677]
# 🚀 Feature request

Documentation page: Make example copy buttons remove input prompts (`>>>` and `...`) before copying, as well as skip lines that don’t start with prompts (in case they are output lines). Or provide the option to toggle this functionality.

## Motivation

When I copy doc examples, the input prompts & outputs lines are also copied. It would be very convenient to remove these automatically. I have seen some websites that can do this, or even toggle the modes for copying or not copying these prompts.

You can find an example here:

[Sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/#)

## Your contribution

It's not clear to me how to contribute to this, but I will be happy to do it if it's possible and welcomed.

**Comment by NielsRogge** [comment]
This is a bug that will be fixed soon, see https://github.com/huggingface/doc-builder/issues/41. cc @mishig25. Thanks for reporting.

**Comment by ydshieh** [comment]
Thanks, @NielsRogge . I didn't follow that repository. I am closing this issue.
