### ISSUE TITLE
Occasional Can not load roberta-base tokenizer 

### ISSUE THREAD

**Issue by CaoYiqingT** [huggingface/transformers#14696]
**Environment info**
transformers 4.12.0.dev

**issue**
when using `tokenizer = AutoTokenizer.from_pretrained('roberta-base')`, got the bug as following:
```
OSError: Can't load config for 'roberta-base'. Make sure that:

- 'roberta-base' is a correct model identifier listed on 'https://huggingface.co/models'
  (make sure 'roberta-base' is not a path to a local directory with something else, in that case)

- or 'roberta-base' is the correct path to a directory containing a config.json file
```
Sometimes this bug occurs while sometimes it works well
@LysandreJik

**Comment by LysandreJik** [comment]
I think this is probably due to an internet connection error, unfortunately
