### ISSUE TITLE
Write with Transformer: Changing settings on Mobile?

### ISSUE THREAD

**Issue by varkarrus** [huggingface/transformers#1471]
## ❓ Questions & Help

It's great to see new features and options, in particular the Max Time option to generate longer outputs. However, none of the Model Settings are available on mobile...?

In order to change the model settings on mobile, I had to download Firefox, mess with the CSS settings in about://config to make everything really tiny, zoom in on the extremely small settings box, slide things around, then set everything back, and I'd have to do most of those all over again if I end up closing / reloading the tab.

**Comment by LysandreJik** [comment]
You're right, the interface isn't well suited to mess with settings on mobile. It's on our roadmap!

**Comment by varkarrus** [comment]
awesome! I found a dumb workaround; saved a copy of the page, changed the default values, then put it in my dropbox!

**Comment by julien-c** [comment]
Haha that’s a great hack!

Closing this for now, thanks
