### ISSUE TITLE
Include documentation on linking to transformers docs with Intersphinx

### ISSUE THREAD

**Issue by cthoyt** [huggingface/transformers#14728]
I'm one of the maintainers of PyKEEN and we're adding a feature where you can use various transformers in combination with knowledge graph embedding models in https://github.com/pykeen/pykeen/pull/652. We're using sphinx to build our documentation and have out-links to various packages like numpy, but we haven't been able to figure out how to use the intersphinx configuration to link to transformers' docs. I spent a bit of time googling, but did not find any answers. Is this even possible? If so, could you include some information either here or in your docs themselves on what the objects.inv URL for your docs?

**Comment by julien-c** [comment]
Note that we do not use Sphinx anymore for our doc, since moving to https://huggingface.co/docs/transformers

However (not at all familiar with Intersphinx so I'm shooting in the dark here) maybe there's a specification that we could implement to facilitate linking to specific classes or methods inside our documentation? Does anyone know more about this?

**Comment by dblalock** [comment]
I got this working by adding the following to my `intersphinx_mapping` in the sphinx `conf.py`:
```python
intersphinx_mapping = {
    'datasets': ('https://huggingface.co/docs/datasets/master/en/', None),
    'transformers': ('https://huggingface.co/docs/transformers/master/en/', None),
} 
```
The key is that there's an `objects.inv` file in each of these directories, which is what sphinx needs.

**Comment by plutonium-239** [comment]
Just an update for anyone that stumbles upon this: use `main` instead of `master` in the URL (the git branch name changed, although it does redirect now but may break in the future)
