### ISSUE TITLE
XLNetLMHeadModel has no attribute 'from_config'

### ISSUE THREAD

**Issue by josutk** [huggingface/transformers#14736]
## Environment info

- `transformers` version: 4.8.0
- Platform: Linux-4.15.0-20-generic-x86_64-with-LinuxMint-19-tara
- Python version: 3.6.9
- PyTorch version (GPU?): 1.8.0+cu111 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes

### Who can help
@patrickvonplaten

## Information

Model I am trying to train a XLNet model from scratch to portuguese but when i run this script: https://github.com/huggingface/transformers/blob/v4.8.2-release/examples/pytorch/language-modeling/run_plm.py i get this error:

Traceback (most recent call last):
  File "run_plm.py", line 498, in <module>
    main()
  File "run_plm.py", line 330, in main
    model = XLNetLMHeadModel.from_config(config)
AttributeError: type object 'XLNetLMHeadModel' has no attribute 'from_config'

The problem arises when using:
* [x] the official example scripts: (give details below)

The tasks I am working on is:
* [x] my own task or dataset: (give details below)
portuguese wikipedia dataset

**Comment by patrickvonplaten** [comment]
Good catch @josutk,

I think we should change this line to:

```
model = XLNetLMHeadModel(config)
```

would you like to open a PR for this? :-)

**Comment by josutk** [comment]
@patrickvonplaten I have open PR.
