### ISSUE TITLE
Fix docs pointers for DeepSpeed

### ISSUE THREAD

**Issue by marctorsoc** [huggingface/transformers#14730]
In this [section](https://huggingface.co/docs/transformers/master/en/main_classes/trainer#deepspeed), the reader is pointed to several links that are broken:

* https://huggingface.co/docs/transformers/master/en/main_classes/trainer#deepspeed-trainer-integration
* https://huggingface.co/docs/transformers/master/en/main_classes/trainer#deepspeed-installation
* https://huggingface.co/docs/transformers/master/en/main_classes/trainer#deepspeed-multi-gpu
* https://huggingface.co/docs/transformers/master/en/main_classes/trainer#deepspeed-one-gpu
*https://huggingface.co/docs/transformers/master/en/main_classes/trainer#deepspeed-config-passing
* etc

All of them should be changed like this:

`https://huggingface.co/docs/transformers/master/en/main_classes/trainer#(.*)` --> `https://huggingface.co/docs/transformers/master/en/main_classes/deepspeed#(.*)`

I would do it myself, but I see that the code uses e.g. `:ref:`deepspeed-notebook` and not sure how to point to a section in another page 🤷‍♂️  It looks like a trivial change though

**Comment by LysandreJik** [comment]
If I'm not mistaken this is patched on `master` and will be reflected soon on the documentation cc @sgugger

**Comment by marctorsoc** [comment]
@LysandreJik At least in this line: https://github.com/huggingface/transformers/blame/master/docs/source/main_classes/trainer.rst#L506, it seems to be still outdated. Are you sure this is patched?

**Comment by sgugger** [comment]
I will push a patch later today.
