### ISSUE TITLE
TF and PT code confuse in the documentation 

### ISSUE THREAD

**Issue by LucienShui** [huggingface/transformers#14741]
Hi, @sgugger, at [quicktour.mdx#L337](https://github.com/huggingface/transformers/blame/5eca742f6c0e513d8c7d8085fd14b7a754ea96f7/docs/source/quicktour.mdx#L337) and [quicktour.mdx#L345](https://github.com/huggingface/transformers/blame/5eca742f6c0e513d8c7d8085fd14b7a754ea96f7/docs/source/quicktour.mdx#L345), TF code was written in PT block, so do PT.

**Comment by sgugger** [comment]
Thanks again for fixing it!
