### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by pratikchhapolika** [huggingface/transformers#14761]
I am downloading the model <<https://huggingface.co/microsoft/Multilingual-MiniLM-L12-H384/tree/main>> **microsoft/Multilingual-MiniLM-L12-H384** and then using it.

**Transformer Version: '4.11.3'**

Following are the files in the links:
<img width="277" alt="Screenshot 2021-12-14 at 3 29 09 PM" src="https://user-images.githubusercontent.com/11159549/145976626-afde48a9-224f-4298-817c-e56a912ec036.png">

When I use this line:

`tokenizer = tr.BertTokenizer.from_pretrained("/home/pchhapolika/minilm_model/")`

**Error: TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType**

**Comment by LysandreJik** [comment]
How are you downloading the files, and what are the size of the files @pratikchhapolika ?
