### ISSUE TITLE
Addition of Swin Transformer for Computer Vision

### ISSUE THREAD

**Issue by bhadreshpsavani** [huggingface/transformers#14760]
# 🌟 Addition Swin Transformer

## Model description
Swin Transformer (the name Swin stands for Shifted window) is initially described in arxiv, which capably serves as a general-purpose backbone for computer vision. It is basically a hierarchical Transformer whose representation is computed with shifted windows. The shifted windowing scheme brings greater efficiency by limiting self-attention computation to non-overlapping local windows while also allowing for cross-window connection.

Swin Transformer achieves strong performance on COCO object detection (58.7 box AP and 51.1 masks AP on test-dev) and ADE20K semantic segmentation (53.5 mIoU on Val), surpassing previous models by a large margin.

## Open source status

* [x] the model implementation is available: https://github.com/microsoft/Swin-Transformer
* [x] the model weights are available: https://github.com/microsoft/Swin-Transformer
* [x] who are the authors: [Swin Transformer](https://arxiv.org/pdf/2103.14030.pdf)

## Possible Task Support:
Opensource Version Supports below tasks
* Image Classification
* Object Detection
* Instance Segmentation
* Semantic Segmentation
* Video Recognition

**Comment by LysandreJik** [comment]
Maybe of interest to @NielsRogge

**Comment by novice03** [comment]
Hello, I would like to work on adding Swin.

**Comment by LysandreJik** [comment]
Hey @novice03, thanks for your effort! I believe that @FrancescoSaverioZuppichini is in the process of adding the `Mask2Former` model which depends on Swin, so he's probably working on that too. 

I'll let him share more about his work.
