### ISSUE TITLE
Is there a way to batch examples by max number of tokens using tokenizers and datasets?

### ISSUE THREAD

**Issue by goncalomcorreia** [huggingface/transformers#14767]
I want to batch my dataset ("super_glue") by the number of tokens instead of the number of sentences. Does this library have any Sampler or Collater that can do this while using a huggingface tokenizer and a huggingface dataset?

**Comment by NielsRogge** [comment]
Yes, see this answer on our forum: https://discuss.huggingface.co/t/are-dynamic-padding-and-smart-batching-in-the-library/10404/4

**Comment by shuoyangd** [comment]
Sorry for bumping this up -- I had the same question but I think the page linked here is answering a different question.

Let me ask again differently: is there a [fairseq `--max-tokens` counterpart](https://github.com/facebookresearch/fairseq/issues/165) I can use in huggingface?
