### ISSUE TITLE
make docs failing

### ISSUE THREAD

**Issue by kamalkraj** [huggingface/transformers#14762]
https://github.com/huggingface/transformers/blob/2a606f9974feb0f7578e6a638c7e5b548523ecb4/CONTRIBUTING.md?plain=1#L211-L221

```bash
make docs
cd docs && make html SPHINXOPTS="-W -j 4"

Application error:
config directory doesn't contain a conf.py file (source)
make[1]: *** [html] Error 2
make: *** [docs] Error 2
```

transformers version: master branch

@sgugger

**Comment by sgugger** [comment]
Yes we are not using sphinx anymore to build the doc. The contributing guide will be updated in the coming days.

**Comment by kamalkraj** [comment]
Okay
