### ISSUE TITLE
Enable ONNX export for `VisionDecoderEncoderModel`

### ISSUE THREAD

**Issue by lewtun** [huggingface/transformers#14812]
# 🚀 Feature request

As discussed on the [forums](https://discuss.huggingface.co/t/can-i-export-a-visionencoderdecoder-checkpoint-to-onnx/12885), it would be nice if one could export `VisionDecoderEncoderModel` classes using the `transformers.onnx` package.

## Motivation

It is currently not possible to export `VisionDecoderEncoderModel` classes (or vision models more generally), unless the end user is willing to write their own `OnnxConfig`. It might make sense to first explore what is involved in exporting ViT before tackling this more complex example. 

Looking at this a bit more closely, I can see that `transformers.onnx` currently has a tight integration with tokenizers (e.g. to generate dummy inputs), so some refactoring will be necessary to support other modalities.

**Comment by lewtun** [comment]
Hey @albertoandreottiATgmail thanks for the interest! This is next up on my list now that we've just merged the ViT export in #15658 :)

**Comment by IlyasMoutawwakil** [comment]
> Hey @albertoandreottiATgmail thanks for the interest! This is next up on my list now that we've just merged the ViT export in #15658 :)

Hi @lewtun is there any way (or script) to export trocr to onnx ?

**Comment by NielsRogge** [comment]
Re-opening this issue as it hasn't been resolved yet

**Comment by IlyasMoutawwakil** [comment]
I have actually succeeded in converting TrOCR to ONNX by splitting its two components (encoder and decoder) and rebuilding the HF model with the inference sessions. You lose some performance and it's not very fast (tried it with CUDAExecutionProvider).

**Comment by NielsRogge** [comment]
Adding another feature request for this: https://github.com/NielsRogge/Transformers-Tutorials/issues/183

**Comment by IlyasMoutawwakil** [comment]
Here's a notebook where I ONNXized TrOCR and also made a modification to the generation function so that it won't compute for lines that already ended (EOS).
https://colab.research.google.com/drive/1PApn7yl4E5RX0rz4AnxHqD0IqSOmpY9-?usp=sharing

**Comment by BakingBrains** [comment]
> Adding another feature request for this: [NielsRogge/Transformers-Tutorials#183](https://github.com/NielsRogge/Transformers-Tutorials/issues/183)

Any updates on this one?

Thank you

**Comment by lewtun** [comment]
Hi folks, @mht-sharma will be tackling this issue - stay tuned :)

**Comment by BakingBrains** [comment]
@mht-sharma Any updates?

Thank you.

**Comment by lewtun** [comment]
@BakingBrains you can see the PR from @mht-sharma linked above - we should be able to get this merged pretty soon!

**Comment by BakingBrains** [comment]
@lewtun and @mht-sharma Thank you.
