### ISSUE TITLE
Roberta Classification Head

### ISSUE THREAD

**Issue by arijitthegame** [huggingface/transformers#14817]
Why does Roberta classification Head uses 2 linear layers? https://github.com/huggingface/transformers/blob/84ea427f460ffc8d2ddc08a341ccda076c24fc1f/src/transformers/models/roberta/modeling_roberta.py#L1443 

The BERT classification head uses only one and it makes sense since all the work is done by the Transformer layers.

**Comment by LysandreJik** [comment]
Hi! We try to stick as much as possible to the original implementation. See fairseq's original implementation here: https://github.com/pytorch/fairseq/blob/a54021305d6b3c4c5959ac9395135f63202db8f1/fairseq/models/roberta/model.py#L394-L429

**Comment by arijitthegame** [comment]
Thank you so much.
