### ISSUE TITLE
as_target_tokenizer is not an attribute of PreTrainedTokenizerBase and Bart/RobertaTokenizer

### ISSUE THREAD

**Issue by EvgheniiBeriozchin** [huggingface/transformers#14827]
### Environment
Instance: Paperspace Gradient Cloud Instance
transformers: 3.5.1 (same issue on 4.14.1)
Python: 3.6.9

### Information
When creating an instance of the Roberta/Bart tokenizer the method as_target_tokenizer is not recognized. Code almost entirely the same as in the summarization example of Huggingface (https://github.com/huggingface/transformers/blob/master/examples/pytorch/summarization/run_summarization.py).

The tokenizer is instantiated in the following way:

```python
tokenizer = AutoTokenizer.from_pretrained("roberta-base")
```

and the executed code is:

```python
with tokenizer.as_target_tokenizer():
            labels = tokenizer(targets, max_length=MAX_TARGET_LENGTH, padding=USES_PADDING, truncation=True)
```

The error that occurs is:
AttributeError: 'RobertaTokenizer' object has no attribute 'as_target_tokenizer'

Same thing happens when instantiating just PreTrainedTokenizerBase, which according to the documentation has this function (https://huggingface.co/docs/transformers/internal/tokenization_utils).

**Comment by LysandreJik** [comment]
Hello! The `as_target_tokenizer` method is specifically for seq2seq models in order to separate between the source and target tokenizers. Why do you need it for RoBERTa?

cc @patrickvonplaten @sgugger

**Comment by sgugger** [comment]
I would double-check on v4.14.1 as every tokenizer has this method (it just doesn't do anything for models that are not seq2seq). It didn't exist for v3.5.1, so it's normal if you have an error on that version.
