### ISSUE TITLE
Train Bart-Large multi-labels

### ISSUE THREAD

**Issue by gennarovaccaro** [huggingface/transformers#14846]
Hello,
I have two similar questions. **First**, I'm trying to fine-tune the facebook/bart-large ([https://huggingface.co/facebook/bart-large](url)) but I want to train with 2 classes:

Example:
```
Text-input: "Hello, this text is about school and education."
Class 1: [X, Y, Z]
Class 2: [A, B, C]

Model answer: Y, C
```

I'm using the run_glue file on my personal training files. My question is: How should I set the labels of the training file to train?

My labels with 1 class (8 labels) are actually 0, 1, 2...7 so my csv-entry is something like:
```
Input - Label
Text1 - 2
Text2 - 6
Text3 - 4
```
(This is an example, my csv is in the glue-like format and work with 1 class)
I don't know how to modify them to train on 2 classes.

**Next** question, I want also to fine-tune the network with 1 class but in multi-label mode.

Example:
```
Text-input: "Hello, this text is about school and education."
Class 1: 0, 1, 2, 3, 4, 5, 6, 7

Model answer: 2, 4, 6
```

I've tried something like this, but it's not working

```
Input - Label
Text1 - [2,3]
Text2 - [6]
Text3 - [1,2,5,6]
```

Thank you, sorry if it is explained a little badly.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue and sorry for getting back late to this! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) for a better chance of getting an answer?

Thanks!
