### ISSUE TITLE
A potential bug in ModuleUtilsMixin.get_extended_attention_mask

### ISSUE THREAD

**Issue by jk-jung** [huggingface/transformers#14859]
## Environment info

- `transformers` version: 4.13.0
- Platform: 
- Python version: 3.8.5
- PyTorch version (GPU?): 1.10.0+cu102
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help
@LysandreJik 

## Information

Model I am using (Bert, XLNet ...): T5

There is a potential bug in ModuleUtilsMixin.get_extended_attention_mask, and actually, it has happened to me while I've trained the T5 model from scratch. In the function, it masks a tensor by setting a large negative number(-1e-4), since it will be added to the raw scores before the softmax. 
However, occasionally the value -1e4 is not small enough to nullify the scores in masked positions. In my case, some values in the raw scores before the softmax were small then -1e4 during training, so the model couldn't be trained correctly.

Here is the code I mentioned: [link](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_utils.py#L295-L302)

I think you use -1e4 because of fp16 compatibility, then how about dividing the case based on dtype like in [the code](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_utils.py#L233-L236).

## Expected behavior

the function get_extended_attention_mask uses the smaller number to mask a tensor.

**Comment by LysandreJik** [comment]
I understand that the choice of 1e-4 may be suboptimal and that the masking may not be enough. I believe we've had this conversation before but I can't find it anywhere, I'm open to revisiting it.

WDYT @patrickvonplaten @sgugger @patil-suraj @stas00

**Comment by patil-suraj** [comment]
I agree 1e-4 might not be the best choice for every model. I think it's a good idea to handle this based on the `dtype`

Also, I think maybe we should add an argument `masked_value` to `get_extended_attention_mask` to specify the default mask value for each model from its original implementation.

**Comment by patil-suraj** [comment]
@LysandreJik related discussion #10484

**Comment by stas00** [comment]
What @patil-suraj said, see the code here:

https://github.com/huggingface/transformers/blob/033c3ed95a14b58f5a657f5124bc5988e4109c9f/src/transformers/modeling_utils.py#L233-L236

**Comment by patrickvonplaten** [comment]
I'm also curious what you guys think is the best move here.
IMO, the -10e4 comes from the original Google implementation of BERT and we just copied it everywhere. However I've now seen a couple of issues related to this. In addition to the one @patil-suraj posted we also have this one https://github.com/huggingface/transformers/issues/14521#issuecomment-992428858

@LysandreJik  @sgugger @stas00 @patil-suraj - do you think it could make sense to change -10e4 to the minimum value of that dtype?

**Comment by sgugger** [comment]
Makes sense to me!

**Comment by stas00** [comment]
Could it be that the original implementation had this hardcoded because it worked with a single specific dtype?

I think it makes a total sense to use the logic in https://github.com/huggingface/transformers/issues/14859#issuecomment-998969055

**Comment by LysandreJik** [comment]
I think leveraging the minimum value for the `dtype` as @patrickvonplaten would work too and be quite better than the if/else statement, right? Something like `torch.finfo(self.dtype).min`

**Comment by stas00** [comment]
> `torch.finfo(self.dtype).min`

Loving it! 

We should do the same for all other places we have the conditional for when we that for masking and where no weights will be impacted by this change.

**Comment by patrickvonplaten** [comment]
Ok, happy to do a PR for this next week - putting it on my ToDo list

**Comment by LysandreJik** [comment]
Centralizing all discussions on this:

https://github.com/huggingface/transformers/issues/9594
https://github.com/huggingface/transformers/issues/10484
https://github.com/huggingface/transformers/issues/15199

**Comment by maxwellzh** [comment]
For people using GPT2 Model, there is a hacked hot fix of this issue:

```python
for name, buffer in model.named_buffers():
    if '.masked_bias' in name:
        buffer.data = torch.tensor(float('-inf'))
```

Add these codes after model initialization.

**Comment by patrickvonplaten** [comment]
I won't be able to look into this until the next 3,4 weeks - still have it on my ToDo list though. Depending on how important this is, feel free to take over whoever is interested

**Comment by LSinev** [comment]
Any ideas which `transformers` versions are affected?

**Comment by patrickvonplaten** [comment]
We've always used -10_000 from the very beginning for the `attention_mask` so changing this now would affect all transformers versions

**Comment by ydshieh** [comment]
Hi, this is on my TODO list - I have a few remaining things to finalize about PT/TF/Flax more aggressive testings, and will come back to this issue!

**Comment by ydshieh** [comment]
Start working on it :-)

**Comment by FayeXXX** [comment]
When i install version 4.29.0.dev0, there is a bug in modeling_utils.py in line902:
TypeError: torch.iinfo() requires an integer input type. Use torch.finfo to handle 'torch.iinfo'
Could you plz give some advices? @ydshieh
