### ISSUE TITLE
improve final answer extraction in utils_squad.py

### ISSUE THREAD

**Issue by adai183** [huggingface/transformers#1485]
Shouldn't ` get_final_text` use the specific optionally pre-trained tokenizer instead of generically using `BasicTokenizer` ?

[examples/utils_squad.py L911](https://github.com/huggingface/transformers/blob/6596e3d56626c921b3920e313866b7412633b91a/examples/utils_squad.py#L911)

**Comment by Santosh-Gupta** [comment]
Any update?
