### ISSUE TITLE
Huggingface Transformers fastTokenizer for DeBERTa v3

### ISSUE THREAD

**Issue by bluesky333** [huggingface/transformers#14860]
# 🚀 Feature request

I want to try NER for custom dataset using huggingface transformers DeBERTa v3 xsmall.
I need to use fastTokenizer, but it is not available.
I need to use fastTokenizer for the return_offsets_mapping function.

Do you have plans for releasing fastTokenizer for DeBERTa v3?

When I run the below code,
`train_encodings = tokenizer(train_texts, is_split_into_words=True, return_offsets_mapping=True, padding=True, truncation=True, max_length=MAX_LENGTH)`

I get the below is the error message:
`NotImplementedError: return_offset_mapping is not available when using Python tokenizers.To use this feature, change your tokenizer to one deriving from transformers.PreTrainedTokenizerFast.`

**Comment by bluesky333** [comment]
Found #14712 for the same purpose

**Comment by LysandreJik** [comment]
Let's centralize the discussion on #14712 if you don't mind :)

**Comment by mohsen202** [comment]
i have same problem
