### ISSUE TITLE
dataset of Helsinki-NLP/opus-mt-en-zh

### ISSUE THREAD

**Issue by QzzIsCoding** [huggingface/transformers#14877]
Hi, thanks for your model. I have two questions of the train datasets of opus-mt-en-zh.

https://github.com/Helsinki-NLP/Tatoeba-Challenge/blob/master/data/README-v2021-08-07.md
English - Chinese eng-zho 10390 | 43075 | 129323178
Middle English (1100-1500) - Chinese enm-zho

In this website, there are two datasets from en to zh. Which is the dataset of opus-mt-en-zh?
When fine-tuning the model, does it need to add ">>cmn_Hans<< " before train_src?

**Comment by LysandreJik** [comment]
The README here mentions `eng-zho`, if I'm not mistaken: https://huggingface.co/Helsinki-NLP/opus-mt-en-zh
