### ISSUE TITLE
TrOCR processor cannot be loaded from AutoProcessor

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/transformers#14884]
The following works on current `master`:

```py
>>> from transformers import TrOCRProcessor
>>> processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-printed")
Downloading: 100%|██████████| 878k/878k [00:00<00:00, 1.61MB/s]
Downloading: 100%|██████████| 446k/446k [00:00<00:00, 1.03MB/s]
Downloading: 100%|██████████| 772/772 [00:00<00:00, 1.18MB/s]
Downloading: 100%|██████████| 1.28k/1.28k [00:00<00:00, 1.70MB/s]
```

The following does not:

```
>>> from transformers import AutoProcessor
>>> processor = AutoProcessor.from_pretrained("microsoft/trocr-base-printed")
Downloading: 100%|██████████| 228/228 [00:00<00:00, 404kB/s]
Downloading: 100%|██████████| 4.03k/4.03k [00:00<00:00, 6.88MB/s]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/lysandre/Workspaces/Python/transformers/src/transformers/models/auto/processing_auto.py", line 171, in from_pretrained
    return PROCESSOR_MAPPING[type(config)].from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/lysandre/Workspaces/Python/transformers/src/transformers/models/auto/auto_factory.py", line 559, in __getitem__
    raise KeyError(key)
KeyError: <class 'transformers.models.vision_encoder_decoder.configuration_vision_encoder_decoder.VisionEncoderDecoderConfig'
```

cc @NielsRogge

**Comment by NielsRogge** [comment]
Currently looking into this

**Comment by NouamaneTazi** [comment]
Reopening this issue since I'm still getting the same error @NielsRogge

**Comment by ydshieh** [comment]
I verified with v4.19, and there is no issue. @NouamaneTazi Could you try the new version?

**Comment by NouamaneTazi** [comment]
It's working now. Thanks for your help! 🤗

**Comment by zainali60** [comment]
loaded_model = VisionEncoderDecoderModel.from_pretrained('/content/drive/MyDrive/ocr_pth/checkpoint-5000')
processor = TrOCRProcessor.from_pretrained("/content/drive/MyDrive/ocr_pth/checkpoint-5000")

KeyError                                  Traceback (most recent call last)
[<ipython-input-12-a5659b723d72>](https://localhost:8080/#) in <module>
      1 # loaded_preprocessor = TrOCRProcessor.from_pretrained('/content/drive/MyDrive/ocr_pth/checkpoint-5000')
      2 loaded_model = VisionEncoderDecoderModel.from_pretrained('/content/drive/MyDrive/ocr_pth/checkpoint-5000')
----> 3 processor = TrOCRProcessor.from_pretrained("/content/drive/MyDrive/ocr_pth/checkpoint-5000")

3 frames
[/usr/local/lib/python3.7/dist-packages/transformers/models/auto/auto_factory.py](https://localhost:8080/#) in __getitem__(self, key)
    570                 model_name = self._model_mapping[mtype]
    571                 return self._load_attr_from_module(mtype, model_name)
--> 572         raise KeyError(key)
    573 
    574     def _load_attr_from_module(self, model_type, attr):

KeyError: <class 'transformers.models.vision_encoder_decoder.configuration_vision_encoder_decoder.VisionEncoderDecoderConfig'>

kindly guide me how resolve this problem.Thanks

**Comment by ydshieh** [comment]
Hi @zainali60 What's your `transformers` version? Could you try the latest one? If the same error still occurs, could you open a new issue with a small but self-contained code snippet to reproduce the issue? Thank you!

**Comment by zainali60** [comment]
Thanks for reply @ydshieh  i resolve my issue and get results
if you have implementation scratch ocr transformers model kindly share me.thanks

**Comment by HebaGamalElDin** [comment]
Hi, I'm getting same error.. I tried v4.19, v4.21.3, v4.22.1 which is the last version so far.

```
# LOAD PRE_PROCESSOR
from transformers import AdamW, TrOCRProcessor, VisionEncoderDecoderModel, get_scheduler
def load_processor() -> TrOCRProcessor:
    return TrOCRProcessor.from_pretrained('gagan3012/TrOCR-Ar-Small')

# LOAD MODEL
def load_model() -> VisionEncoderDecoderModel:
    model: VisionEncoderDecoderModel = VisionEncoderDecoderModel.from_pretrained('gagan3012/TrOCR-Ar-Small')
    return model#.to('cuda')#(accelerator.device)

load_processor()
```

**Comment by ydshieh** [comment]
@HebaGamalElDin I can reproduce the issue with the checkpoint `gagan3012/TrOCR-Ar-Small`, but not `microsoft/trocr-base-printed`. By looking the files in these 2 model repositories, I believe it is because `gagan3012/TrOCR-Ar-Small` doesn't contain the tokenizer files.

I think you can get the tokenizer from [microsoft/trocr-small-stage1](https://huggingface.co/microsoft/trocr-small-stage1). But it would be nice if you can leave a message or even open a PR in [gagan3012/TrOCR-Ar-Small](https://huggingface.co/gagan3012/TrOCR-Ar-Small) to upload the tokenizer files :-)
