### ISSUE TITLE
[doc] bug in docstring conversion

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#14892]
There is an issue of rendering items in a docstring (in some places)

Here is an example:
https://huggingface.co/docs/transformers/main_classes/logging#transformers.utils.logging.set_verbosity
 has a lose `<`

but I'm not sure where this one is coming from

It appears to be a messed up `<ul>` block:

```
Logging level, e.g., one of:</p>
<ul>
<li><code>transformers.logging.CRITICAL</code> or <code>transformers.logging.FATAL</code></li>
<li><code>transformers.logging.ERROR</code></li>
<li><code>transformers.logging.WARNING</code> or <code>transformers.logging.WARN</code></li>
<li><code>transformers.logging.INFO</code></li>
<li><code>transformers.logging.DEBUG</code></li>
<
							</span></span>
					</li></ul>
```

So the following chunk shouldn't be there:
```
<
							</span></span>
					</li>
```

It's a systemic issue, here are more examples:
https://huggingface.co/docs/transformers/main_classes/data_collator#transformers.DataCollatorWithPadding
and several after it.

@sgugger

**Comment by sgugger** [comment]
It seems to be happening every time we have a list in a parameter description. Filing an [issue](https://github.com/huggingface/doc-builder/issues/70) on `doc-builder` for this, Mishig will have a look when he's back from vacation :-)

Closing on this side as there is nothing to do in Transformers. The generated MDX is correct.
