### ISSUE TITLE
Generate does not take into account config.decoder.eos_token_id

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#14905]
As reported by some people (see https://github.com/NielsRogge/Transformers-Tutorials/issues/53 and on the [forum](https://discuss.huggingface.co/t/trocr-repeated-generation/12361)), the `generate()` method currently does not take into account `config.decoder.eos_token_id`, only` config.eos_token_id` to properly stop generation.

Hence, models that are made using `EncoderDecoderModel`/`VisionEncoderDecoderModel`/`SpeechEncoderDecoderModel` will not properly stop generation if `config.eos_token_id` is not set.

cc @patrickvonplaten @patil-suraj

**Comment by patrickvonplaten** [comment]
Hmm, yeah I think I'm fine with adding some `if - statements` to the `generate()` method

**Comment by patrickvonplaten** [comment]
Do you want to open a PR for it? :-)

**Comment by thinksoso** [comment]
i will try to fix it

**Comment by thinksoso** [comment]
https://github.com/huggingface/transformers/pull/15403

**Comment by Batese2001** [comment]
Hi, the above pull request mentioned offhandedly that this had been fixed, is that the case or is this still open as indicated?

**Comment by NielsRogge** [comment]
Seems like this got fixed, closing the issue.
