### ISSUE TITLE
Why I met Type 'seq(tensor(int64))' of operator (MemcpyFromHost) is invalid when using onnxruntime.InferenceSession() in GPU, and How to resolve it? On emergency hold，thanks!

### ISSUE THREAD

**Issue by yuanhuachao** [huggingface/transformers#14918]
## Environment info
when I run exported onnx model of transformers (BARTBeamSearchGenerator model example) on GPU. I met this. Who knows how can resolve it?
<img width="1392" alt="截屏2021-12-24 下午3 32 55" src="https://user-images.githubusercontent.com/13781668/147331435-f518d5c7-b6fd-4550-9de9-940a9ec87003.png">

- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):1.10.1
- Tensorflow version (GPU?):
- Using GPU in script?:YES
- Onnxruntime version: 1.8.0
- onnx version: 1.10.0

**Comment by lewtun** [comment]
Hi @yuanhuachao thanks for raising this issue! Can you please provide the exact command you used to export the model with? You might also be interested in a related issue #14882 about running this example script on a GPU.

**Comment by yuanhuachao** [comment]
Hi @lewtun ,i run the run_onnx_exporter.py with command 'python run_onnx_exporter.py --model_name_or_path facebook/bart-base  --device=cuda', in the directory of '/home/transformers/examples/onnx/pytorch/summarization'.
