### ISSUE TITLE
Unable to see total_flos in ViT training logs

### ISSUE THREAD

**Issue by minhdeal** [huggingface/transformers#14945]
## Environment info

- `transformers` version: 4.14.1
- Platform: Ubuntu 20.04.1
- Python version: 3.8.5
- PyTorch version (GPU?): 1.8.0 (True)
- Tensorflow version (GPU?): n/a
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: DDP

### Who can help

Models:
- TAPAS, LayoutLM, LayoutLMv2, LUKE, ViT, BEiT, DEiT, DETR, CANINE: @NielsRogge

Library:
- Trainer: @sgugger

Examples:
- maintained examples (not research project or legacy): @sgugger, @patil-suraj

## Information

Model I am using (Bert, XLNet ...): ViT

The problem arises when using:
* [ o] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ o] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. download transformers with git clone and pip install
2. run example script in transformers/examples/pytorch/image-classification/run_image_classification.py
3. the resulting logs always give "total_flos=0.0"

```
"log_history": [
  {
  ...
  "step": 17,
  "total_flos: 0.0,
  "train_loss": 0.54699146...,
  ... 
```

## Expected behavior

Being able to see total floating points operations of the whole training (total_flos) in the logs

**Comment by sgugger** [comment]
Could you update your Transformers to the last version? I think this was fixed recently.

**Comment by minhdeal** [comment]
I updated Transformers to the latest (master) version and I can see total_flos now. Thank you for your help.
