### ISSUE TITLE
Documentation in CTRL linksto 404

### ISSUE THREAD

**Issue by osanseviero** [huggingface/transformers#14969]
In https://huggingface.co/docs/transformers/master/en/model_doc/ctrl#overview, when clicking "See reusing the past in generative models", the user is redirected to a 404 (https://huggingface.co/docs/transformers/master/en/quickstart#using-the-past)

**Comment by LysandreJik** [comment]
Nice catch! @stevhliu, would you like to take a look at that?

**Comment by stevhliu** [comment]
Looks like a [throwback](https://huggingface.co/transformers/v2.2.0/quickstart.html) to `transformers 2.2.0`! Should we point the user to [`CTRLModel.forward()`](https://huggingface.co/docs/transformers/master/en/model_doc/ctrl#transformers.CTRLModel.forward.past_key_values) where they can get more information about the parameter? It looks like I can also update it to say PyTorch accepts `past_key_values` and TF accepts `past`.

Another option could be to also add a code example in [`CTRLModel`](https://huggingface.co/docs/transformers/master/en/model_doc/ctrl#transformers.CTRLModel).

**Comment by LysandreJik** [comment]
What you propose sounds good to me @stevhliu!

**Comment by osanseviero** [comment]
This is now fixed after #15615
