### ISSUE TITLE
can I use different pre-trained model for autoTokenizer and autoModel?

### ISSUE THREAD

**Issue by SharonJin422** [huggingface/transformers#14986]
In the train_config.json file, I set:
"model_name_or_path": "ckiplab/albert-tiny-chinese",
 "tokenizer_name": "bert-base-chinese",

this also make sense right?

**Comment by LysandreJik** [comment]
Sorry just seeing this now - you can use different tokenizer/models, but be aware that if they were not trained together then the embeddings of the model will not correspond to the IDs output by the tokenizer. The result will be gibberish, unfortunately.
