### ISSUE TITLE
Finetune M2M on multiple language pairs

### ISSUE THREAD

**Issue by nikhiljaiswal** [huggingface/transformers#14984]
Hi @all, I am able to finetune the M2M model for one lang pair using the below script.

CUDA_VISIBLE_DEVICES=0,1,2,3,6 python -m torch.distributed.run --nproc_per_node=5 run_translation.py --model_name_or_path=m2m100_418M_new_token --do_train --do_eval --source_lang ja --target_lang en --fp16=True --evaluation_strategy epoch --output_dir bigfrall --per_device_train_batch_size=48 --per_device_eval_batch_size=48 --overwrite_output_dir --forced_bos_token “en” --train_file orig_manga/orig/train_exp_frame_50k.json --validation_file orig_manga/orig/valid_exp_frame_50k.json --tokenizer_name tokenizer_new_token --num_train_epochs 50 --save_total_limit=5 --save_strategy=epoch --load_best_model_at_end=True --predict_with_generate

But I do not find a solution to finetune the model on more than one language pair simultaneously which I could easily do using FairSeq.
E.g. now I want to finetune it on ja-en and ja-zh pairs. How to pass these both languages? I could not find an option in the run_translation.py script. Please help.

**Comment by Jourdelune** [comment]
hi, I don't think it's possible :( But you plan to make your model public?

**Comment by lavine-lmu** [comment]
I also want to do this, do you solve it? @Jourdelune

**Comment by Jourdelune** [comment]
No :(
