### ISSUE TITLE
How to load a different domain BERT-based pre-trained model?

### ISSUE THREAD

**Issue by vr25** [huggingface/transformers#1500]
I am trying to load the pre-trained model at pred/FinBERT-Pre2K_128MSL-500K  [FinBERT](https://github.com/psnonis/FinBERT)  and trying to run the basic task of SST-2 (sentiment classification) using run_glue.py (https://huggingface.co/transformers/examples.html#glue).

But I run into the following error:
OSError: Model name '/data/ftm/xgb_regr/FinBERT/pred/FinBERT-Pre2K_128MSL-250K' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed '/data/ftm/xgb_regr/FinBERT/pred/FinBERT-Pre2K_128MSL-250K' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Also, since this seems to be trained using TF, I was wondering if I can use PyTorch to load it.

Thanks.

**Comment by AdityaSoni19031997** [comment]
i think you have to first convert the tf-checkpoint to pytorch-format (iirc lib does that for you);
Fins the base class that you need to re-implement matching your base model.

Like for `BertForTokenClassification`, i had to override the class `BertForTokenClassification` in the file as shown [here](https://github.com/huggingface/transformers/blob/master/transformers/modeling_bert.py#L849)

**Comment by AdityaSoni19031997** [comment]
You can use torch to load it, convert the weights using the helper files;
Not sure about your task, but for mine, i was using a BertModel with different pre-trained weights,
```
model = BertForSequenceClassification(MODEL_PATH, num_labels=len(np.unique(y_train_torch)))
```

where `MODEL_PATH` is a directory that has 
- config.json
- model*checkpoint/bin files etc

**Comment by vr25** [comment]
Thank you for your reply. 

The issue is a little different. All the 3 files: config.json, checkpoint, and vocab.txt are linked by a symbolic link in their repo. I am not sure how to get the actual files. Any suggestions for such a case?

**Comment by AdityaSoni19031997** [comment]
Well if you are running the experiments yourself, you will be downloading them either ways, just make changes where ever needed?

(i haven't tried passing a symbolic link to this func so not sure myself but it should work imo as well)
