### ISSUE TITLE
Issue with XLNet pretrained model

### ISSUE THREAD

**Issue by anandhperumal** [huggingface/transformers#1501]
## 🐛 Bug

Model I am using (Bert, XLNet....): XLNet

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [ ] the official example scripts: (give details)
* [X] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details)

## To Reproduce

I'm trying to train the XLNet dropping the last layer, I get error stating that 

below is my code :

```
class xlmodel(nn.Module):
    def __init__(self, xlnetModell):
        super(xlmodel, self).__init__()
        self.xlnetfeatures = nn.Sequential(*list(xlnetModel.children())[:-1])
        self.concat = nn.Linear(786, 200)
        self.predict = nn.Linear(200,2)

    def forward(self, xlinput_ids, xlattention_mask, labels, xltoken_type_ids) :
        inputs = { 'input_ids' : xlinput_ids , 'attention_mask' : xlattention_mask, 'token_type_ids' : xltoken_type_ids }
        xlnet_output = self.xlnetfeatures(**inputs)
        xl = nn.functional.relu((xlnet_output))
        output = self.predict(xl)
        return output

pretrained_weights = 'xlnet-base-cased'
 xlnetmodel = XLNetForSequenceClassification.from_pretrained(pretrained_weights, num_labels=2)
model(xlnetmodel)
    for _ in trange(num_train_epochs, desc="Epochs"):
        ep_tr_loss, nb_tr_steps, eval_accuracy = 0, 0, 0
        for step, batch in enumerate(train_data):
            model.train()
            batch = tuple(t.to(device) for t in batch)
            # model.
            inputs = {'xlinput_ids': batch[0], 'xlattention_mask': batch[1], 'labels': batch[3],
                      'xltoken_type_ids': batch[2] }
            optimizer.zero_grad()
            output = model(**inputs) -----> this is where error occurs
```
error stack :

```
    xlnet_output = self.xlnetfeatures(**inputs)
  File "E:\PycharmProjects\CommonSense\venv\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'input_ids'
Epochs:   0%|          | 0/10 [00:10<?, ?it/s]

``` 

I even tried not passing the inputs as dictionary but still i get this error.
I verified the input variable name in pytorch xlnet transformer it has input_ids
Any lead will be appreciated thanks.

But if I try to run xlnet as it is works fine.

## Environment

* OS: Windows 10
* Python version: 3.7
* PyTorch version: 1.2.0
* PyTorch Transformers version (or branch): master
* Using GPU ? YEs
* Distributed of parallel setup ? No
* Any other relevant information:

**Comment by AdityaSoni19031997** [comment]
I think you have the wrong Base-Class imported?

**Comment by anandhperumal** [comment]
@AdityaSoni19031997 Sorry for the delay.
I'm fixed the issue but I don't what was the issue though, anyways Thanks.
