### ISSUE TITLE
Wav2Vec2 bart-large - finetuning failing with ValueError: tokenizer has to be of type....but is <class 'transformers.models.bart.tokenization_bart_fast.BartTokenizerFast'

### ISSUE THREAD

**Issue by programmeddeath1** [huggingface/transformers#15039]
Hii,

I am trying to understand how to finetune wav2vec2 models with my own decoder, I am trying to replicate the finetuning for the 
patrickvonplaten/wav2vec2-2-bart-large model with the run script from 
https://github.com/huggingface/transformers/tree/master/examples/pytorch/speech-recognition

The create_model.py as well as the config contains 'Wav2Vec2Processor' as the processor class.

But on  the line 429(run_speech_recognition_seq2seq.py) this command
processor = AutoProcessor.from_pretrained(training_args.output_dir)
fails with -
'''
AttributeError: 'str' object has no attribute 'from_pretrained'
'''
And if i pass the processor class directly it then fails with 
'''
alueError: tokenizer has to be of type <class 'type'>, but is <class 'transformers.models.bart.tokenization_bart_fast.BartTokenizerFast'
'''
I am am still debugging but unable to figure out what the issue is.

--- Update
The internal error is  it has to be of type PreTrainedTokenizer but Bart has PreTrainedTokenizerFast, due to which it fails
Thanks!

**Comment by patrickvonplaten** [comment]
Hey @programmeddeath1,

Sorry to answer so late. Could you please provide a short code snippet that reproduces the error? Thanks!
