### ISSUE TITLE
Issue with `stas/tiny-wmt19-en-de` model

### ISSUE THREAD

**Issue by tingofurro** [huggingface/transformers#15035]
## Environment info

The environment in the Hosted inference API

### Who can help

@stas00

Models:

`stas/tiny-wmt19-en-de` (I assume the issue might be there with other language pairs)

## Information

I am unable to use the model to generate translations, it seems to be generating gibberish (see Screenshot attached).
I tried to use both on the Hosted API & on a local Python setup and get similar results.

## To reproduce

1. Open this link: https://huggingface.co/stas/tiny-wmt19-en-de?text=This+is+a+sentence+in+English.
2. Click Generate and the output should be strange.

# Screenshot

<img width="1316" alt="Screen Shot 2022-01-04 at 4 47 53 PM" src="https://user-images.githubusercontent.com/2609265/148128671-eb021720-efcb-4dd5-95a1-71f68717cf38.png">

**Comment by stas00** [comment]
Hi, tingofurro

Have a look at what the model card says:

> This is a tiny model that is used in the transformers test suite. It doesn't do anything useful, other than testing that modeling_fsmt.py is functional.
> 
> Do not try to use it for anything that requires quality.

Thus closing this.

**Comment by tingofurro** [comment]
Oops! Thanks for the clarification.
