### ISSUE TITLE
ValueError: Layer weight shape (30522, 768) not compatible with provided weight shape torch.Size([1, 15, 3072])

### ISSUE THREAD

**Issue by mathshangw** [huggingface/transformers#15034]
I tried to use word embedding from using BERT as an embedding layer using Keras like that 
```
    inputs2 = Input(shape=(max_length,)) 
    sent = Embedding(vocab_size, 768, mask_zero=True)(inputs2)
    model.layers[1].set_weights([embedding_matrix])    
    model.layers[1].trainable = False
```
but got the following error 
 ```
  model.layers[1].set_weights([embedding_matrix])
  File "/home/user/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1801, in set_weights
    'shape %s' % (ref_shape, weight_shape))
ValueError: Layer weight shape (30522, 768) not compatible with provided weight shape torch.Size([1, 15, 3072])

```

**Comment by LysandreJik** [comment]
Hi @mathshangw, is there a way for you to share more? We don't have knowledge of most of the variables you're showing here.

**Comment by mathshangw** [comment]
i'm trying to do image captioning using keras and tried to make the embedding layer is the output of BERT for word embedding like the above code is the part of the decoder model and i used this for getting the word-embedding 
```
def get_bert_embed_matrix(sentences):
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    model_config = transformers.AutoConfig.from_pretrained('bert-base-uncased', output_hidden_states=True)
    model = transformers.AutoModel.from_pretrained('bert-base-uncased', config=model_config)
    tokenizer = transformers.AutoTokenizer.from_pretrained('bert-base-uncased')
    for sent in sentences:
        marked_text = "[CLS] " + sent + " [SEP]"
        tokenized_text = tokenizer.tokenize(marked_text)
        indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)        
        tokens_tensor = torch.tensor([indexed_tokens])
        model.eval()
        outputs = model(tokens_tensor)
        last_hidden_state = outputs[0]
        word_embed_1 = last_hidden_state
        hidden_states = outputs[2]
        word_embed_6 = torch.cat([hidden_states[i] for i in [-1,-2,-3,-4]], dim=-1)
    return word_embed_6
```
if there is anything i did wrong , please let me know .. Thanks in advance

**Comment by gante** [comment]
Hi @mathshangw! Thank you for sharing your issue with us.

I see three potential issues, given the information you gave us so far:
1. the return of your `get_bert_embed_matrix` function is the concatenation of 4 hidden states, and thus the dimension on your `Embedding` layer should be 768*4, not 768;
2. the `inputs2` variable in your initial script contains a pytorch tensor. I am not sure whether Keras accept pytorch tensors as inputs, try to convert it to a TF tensor;
3. you may need to change the order of the input dimensions.

Let me know if it helps.

Finally -- I know this is your first issue here, but check our [guide for issues](https://github.com/huggingface/transformers/blob/master/ISSUES.md) if you haven't so far. It helps you find the answer faster (if it exists out there) and it helps us and the community to deliver the best experience possible (if it doesn't) 🤗

**Comment by mathshangw** [comment]
Thanks a lot for replying .. so excuse me does this function write for return word-embedding using BERT ?

**Comment by gante** [comment]
Yes, the concatenation of the last 4 hidden states, returned by your `get_bert_embed_matrix` function, is one of the most well-known methods ([table 7 in the original BERT paper](https://arxiv.org/pdf/1810.04805.pdf)) to obtain word-level embeddings for BERT :)

**Comment by mathshangw** [comment]
> Hi @mathshangw! Thank you for sharing your issue with us.
> 
> I see two potential issues, given the information you gave us so far:
> 
>     1. the `inputs2` variable in your initial script contains a pytorch tensor. I am not sure whether Keras accept pytorch tensors as inputs, try to convert it to a TF tensor. Alternatively, you can change Bert to be a tensorflow model, by changing  `AutoModel` to `TFAutoModel` (then the output would be a TF tensor);
> 
>     2. The output of your `get_bert_embed_matrix` function is already an embedding, so you don't need an Embedding layer. You can use that as an input to a downstream model.
> 
> 
> Let me know if it helps.
> 
> Finally -- I know this is your first issue here, but check our [guide for issues](https://github.com/huggingface/transformers/blob/master/ISSUES.md) if you haven't so far. It helps you find the answer faster (if it exists out there) and it helps us and the community to deliver the best experience possible (if it doesn't) hugs

thanks a lot but how can i use the function as an input to a downstream model , please

**Comment by gante** [comment]
You can do as follows (there are actually many ways to do it):
1. Ensure you get the output of `get_bert_embed_matrix` as a tf.Tensor ([docs](https://www.tensorflow.org/api_docs/python/tf/Tensor))
2. Define your model using the sequential API ([docs](https://www.tensorflow.org/api_docs/python/tf/keras/Sequential))
3. Ensure the first later is a `Flatten` keras layer, so it handles the input shapes for you (see the examples in the [docs](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Flatten))
4. Define the rest of your downstream model

**Comment by mathshangw** [comment]
for the first step, I already have a tensor shape like 
```
word_embed_6 tensor([[[ 0.0155,  0.5562, -0.5415,  ..., -0.9124, -0.1821,  0.3324],
         [ 0.1608,  0.6736, -0.2573,  ..., -0.4021, -0.1037,  1.0414],
         [ 0.2988,  0.9358, -0.3037,  ..., -0.3654,  0.5728,  1.0828],
         ...,
         [-0.1464,  0.4040, -0.0260,  ..., -0.2809, -0.0515, -0.4529],
         [-0.1704,  0.6463, -0.1619,  ..., -0.4853,  0.2173,  0.1919],
         [ 0.0724,  0.6961, -0.1094,  ..., -0.3674,  0.1334,  0.0856]]],
       grad_fn=<CatBackward>)

```
for the second step, I have the model like 
```
inputs2 = Input(shape=(max_length,))
sent = Embedding(vocab_size, 3072, mask_zero=True)(inputs2)
model.layers[1].set_weights([embedding_matrix])   
model.layers[1].trainable = False
```
This is the problem with me cause I got this error 
`ValueError: Layer weight shape (30522, 3072) not compatible with provided weight shape torch.Size([1, 10, 3072])`
