### ISSUE TITLE
Multilabel Token Classification in trainer

### ISSUE THREAD

**Issue by hasansalimkanmaz** [huggingface/transformers#15052]
# 🚀 Feature request

We need to be able to use the trainer for multilabel token classification problems.

## Motivation

Right now we create a custom model and a custom trainer class. The model has an additional layer for the second set of labels. Which makes the codebase complicated and harder to maintain. This feature may help to identify entity groups or roles as it is implemented in [RASA](https://rasa.com/blog/introducing-entity-roles-and-groups/)

## Your contribution

I can try to help if you direct me to the solution.

**Comment by sgugger** [comment]
I am unsure why the model would need an additional layer. Can't it all be treated by a proper loss function?

**Comment by hasansalimkanmaz** [comment]
Could you elaborate on it a bit? I am not sure I understand thoroughly

**Comment by hasansalimkanmaz** [comment]
Thanks for the suggestion. After brainstorming with my team, it seems to be possible. I am closing this thread.
