### ISSUE TITLE
How can I update special token ids?

### ISSUE THREAD

**Issue by vitalyshalumov** [huggingface/transformers#15054]
I am combining a tokenizer from model A with apretrained model B. 
I want to align special token ids.
I am able to change the token name such as <s> but I cannot change the token id number. 
How can I aproach this problem?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
