### ISSUE TITLE
Seq2Seq model with HugginFace

### ISSUE THREAD

**Issue by juliahane** [huggingface/transformers#1506]
Hi
I am looking for a Seq2Seq model which is based on HuggingFace BERT model, I know fairseq has some implementation, but they are generally to me not very clean or easy to use, and I am looking for some good implementation based on HuggingFace work, thanks a lot for your help

**Comment by rlouf** [comment]
Hey @juliahane, glad you’re asking: I am currently working on this (See PR #1455) Stay tuned! Closing this as it is not an issue per se.

**Comment by juliahane** [comment]
Hi Remi
thanks a lot for the great work, since I need it for a deadline approaching
very soon, I would really appreciate
if you may know approximately when could be possible to use?
thanks a lot again for your efforts.
Best regards
Julia

**Comment by thomwolf** [comment]
Hi, probably not in time for your deadline. We are expecting a first working version in a few weeks.

**Comment by juliahane** [comment]
Hi Thomas,
I really need to make this code working for a deadline, I really appreciate to point me to the current existing implementations you may be aware of which I could use for now, thank you so much for your help

**Comment by juliahane** [comment]
@thomwolf , I see you have run_lm_finetuning.py script, can I use this script for seq2seq generation task? Does it work for  this purpose? thanks

**Comment by thomwolf** [comment]
Hi @juliahane, no you cannot use `run_lm_finetuning` for seq2seq generation.

If you cannot wait, I think this repo is a good place to start. It's based on our library and specifically target seq2seq for summarization: https://github.com/nlpyang/PreSumm

**Comment by thomwolf** [comment]
Let's keep this issue open to gather all threads asking about seq2seq in the repo.

**Comment by rlouf** [comment]
> Hi Thomas,
> I really need to make this code working for a deadline, I really appreciate to point me to the current existing implementations you may be aware of which I could use for now, thank you so much for your help

You can have a look at PR #1455 . What you're looking for is in the `modeling_seq2seq.py` and `run_seq2seq_finetuning.py` scripts. This only works for Bert at the moment.

**Comment by juliahane** [comment]
Hi
thanks a lot for the response, I cannot see the files, I really
appreciate sharing the files with me, thanks

**Comment by juliahane** [comment]
BERT is sufficient for me, I really appreciate sharing the files and
telling me the commands to run them, thanks

**Comment by juliahane** [comment]
Hi Remi
I really appreciate providing me with the command that I could get this
pull request in my installed huggingface library, thanks
Best
Julia

**Comment by rlouf** [comment]
https://stackoverflow.com/questions/9537392/git-fetch-remote-branch

The name of the branch is `conditional-generation`. However I am afraid we cannot provide support for ongoing work that has not made its way into the library yet.

**Comment by juliahane** [comment]
Hi Remi
I was trying to run the bert seq2seq based codes, It gots a lot of errors,
I really appreciate if you could run it, and
making sure BERT one works, thanks a lot

**Comment by juliahane** [comment]
Hi Remi
Sure, I understand you cannot provide support for ongoing work, I anyway
have a deadline and will need to use it,
could you tell me please just how much this code is tested? Does it work
for BERT? what I saw the code had
several bugs in the optimizer part and does not run, I really appreciate if
you could just tell me how much this
code is tested
thanks

**Comment by juliahane** [comment]
Hi Remi
I made this work, could you please tell me how can I get the generated
sequence from decoder please?
thanks

**Comment by juliahane** [comment]
Hi Thomas
Remi was saying in PR:#1455 it has the bert seq2seq ready, could you move in a gradual way please? So merging the codes for BERT already so people can use the BERT one, this is already great, then after a while when this is ready for also other encoders, add  them later, I really appreciate adding the BERT ones thanks

**Comment by rlouf** [comment]
#1455 was merged and it is now possible to define and train encoder-decoder models. Only Bert is supported at the moment.

**Comment by juliahane** [comment]
Hi Remi and thomas
Thank you so much for the great help, this is awesome, and I would like to
really appreciate your hard work,
Best regards
Julia

**Comment by juliahane** [comment]
Hi
I was wondering if you could give some explanations how the decoder part
work, I see this is a masked language model head BERT,
used as decoder, I think masked language model head bert mask some part and
predict specific masked tokens,
I am not sure how this work as a generation module, thanks for clarifying.

**Comment by rabeehk** [comment]
> #1455 was merged and it is now possible to define and train encoder-decoder models. Only Bert is supported at the moment.

Hi Remi, I posted some bugs/suggestions about this code at #1674, thanks

**Comment by juliahane** [comment]
Hi
when I run this code I got this erorr, thanks for help.

 File "/user/julia/dev/temp/transformers/examples/utils_summarization.py",
line 143, in encode_for_summarization
    for line in story_lines
  File "/user/julia/dev/temp/transformers/examples/utils_summarization.py",
line 143, in <listcomp>
    for line in story_lines
AttributeError: 'BertTokenizer' object has no attribute
'add_special_tokens_single_sequence'

**Comment by juliahane** [comment]
Hi
can you please also add a way to see the generated sequences? thanks

**Comment by rajarsheem** [comment]
Well, with a next word prediction language models like GPT2, you can just create a dataset like "source [SEP] target" and the run the LM (```run_lm_finetuning.py```) on it. During test time, you can provide "source [SEP]" as your prompt and you will get "target" as your prediction.

One small thing that you can do is mask your source tokens in the loss computation because you don't want to predict the source tokens as well!

**Comment by nonva** [comment]
> `modeling_seq2seq.py` and `run_seq2seq_finetuning.py` scripts.

excuse me, where are these two files ?

**Comment by nonva** [comment]
> #1455 was merged and it is now possible to define and train encoder-decoder models. Only Bert is supported at the moment.

 could you tell me how to get the two file modeling_seq2seq.py and run_seq2seq_finetuning.py,
so l could fine tune seq2seq model with pretrained encode model like bert?

**Comment by yuvalkirstain** [comment]
any news about seq2seq training script using transformers?
