### ISSUE TITLE
How to use an unpretrained model?

### ISSUE THREAD

**Issue by jiacheng-ye** [huggingface/transformers#15069]
By using the following codes, I can load a **pretrained** model for fine-tuning on QA tasks. I'm wondering how to load a same (same architecture with roberta-base) **unpretrained** model , and train it on my own data from scratch?
```
tokenizer = AutoTokenizer.from_pretrained("roberta-base")
model = AutoModelForQuestionAnswering.from_pretrained("roberta-base")
```

**Comment by NielsRogge** [comment]
You can initialize a model using a configuration object, like so:

```
from transformers import RobertaConfig, RobertaModel

config = RobertaConfig()
model = RobertaModel(config)
```
This for instance will load the default configuration of RoBERTa, as documented [here](https://huggingface.co/docs/transformers/model_doc/roberta#transformers.RobertaConfig) - which means, a hidden_size of 768, 12 hidden layers, etc. All weights of the model will be randomly initialized, as we're not instantiating it using the `from_pretrained()` method. To customize the architecture, you can load it as follows:
```
from transformers import RobertaConfig, RobertaModel

config = RobertaConfig(num_hidden_layers=2, hidden_size=20)
model = RobertaModel(config)
```

You can also load a model with randomly initialized weights, but with the architecture of a particular model on the hub, for instance, like so:

```
from transformers import AutoConfig

config = AutoConfig.from_pretrained("klue/roberta-small") # note, this is equivalent to instantiating a RobertaConfig

model = RobertaModel(config)
```

**Comment by jiacheng-ye** [comment]
Thanks a lot :)
