### ISSUE TITLE
GPT-J Tokenizer model_max_length=1024 despite n_positions=2048

### ISSUE THREAD

**Issue by oborchers** [huggingface/transformers#15097]
On  the hub the `tokenizer_config.json` states, that GPT-J has a `"model_max_length": 1024`, despite the fact that it can generate up to `2048` tokens, as per `"n_positions": 2048` according to the config.

Is this intended? 

Tagging due to knowledge of the original issue:
@StellaAthena @EricHallahan @patrickvonplaten

**Comment by StellaAthena** [comment]
This sounds like its a typo. If you change it to 2048, does the model run without issue?

**Comment by oborchers** [comment]
Yes, that’s why I raised the issue 👍🏻

**Comment by patil-suraj** [comment]
Hi, good catch! This is because GPT-J uses `GPT2Tokenizer`which has `model_max_length` set to 1024.  Here we could directly update`tokenizer_config.json` file on the hub.

@StellaAthena would it be okay if I update the file in the `tokenizer_config` repo with this change?

**Comment by StellaAthena** [comment]
@patil-suraj I got it :)

**Comment by patil-suraj** [comment]
Thanks a lot!
