### ISSUE TITLE
Example script to edit kenlm arpa file does not work correctly in kaggle notebook

### ISSUE THREAD

**Issue by R4ZZ3** [huggingface/transformers#15128]
## Environment info

Kaggle Python environment with GPU acceleration
- `transformers` version: 4.12.5
- Platform: Linux-5.10.68+-x86_64-with-debian-bullseye-sid
- Python version: 3.7.12
- PyTorch version (GPU?): 1.9.1 (True)
- Tensorflow version (GPU?): 2.6.2 (True)
- Flax version (CPU?/GPU?/TPU?): 0.3.6 (gpu)
- Jax version: 0.2.25
- JaxLib version: 0.1.70
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@patrickvonplaten 

The problem arises when using:
* [ ] the official example scripts: (give details below) https://huggingface.co/blog/wav2vec2-with-ngram

The tasks I am working on is: Training KenLM and using KenLM with xlsr

## To reproduce

At step:
![image](https://user-images.githubusercontent.com/25264037/149226114-7f52e449-f319-4893-97b0-1a1b333b4f99.png)

if I run it like that my output in kenlm.arpa is (count is updated correctly but < /s > line is not added )
![image](https://user-images.githubusercontent.com/25264037/149225404-074f09b7-8ad0-42c2-9a71-44057dcabdae.png)

Once I  change that code above to (Inserting that change as a code block did not make the problem visible, sublime code and kaggle notebook images below)
![image](https://user-images.githubusercontent.com/25264037/149228896-ef8a0893-a16e-47f1-9eb8-9a67ece01aea.png)

![image](https://user-images.githubusercontent.com/25264037/149227673-de309990-3b1f-4d68-9df7-78823095e6c9.png)

I get correct output
![image](https://user-images.githubusercontent.com/25264037/149225552-0b657b14-5ae2-4885-9bac-20261f2e262d.png)

**Comment by patrickvonplaten** [comment]
I see thanks a lot for reporting the problem here! Indeed, the regex I use in the blog is not general enough. I'll change it! Thanks a lot for reporting it here and seems like you solved your problem already :-)

**Comment by patrickvonplaten** [comment]
Should be fixed here: https://github.com/huggingface/blog/pull/206

**Comment by R4ZZ3** [comment]
Fixed
