### ISSUE TITLE
Text generation with TAPAS as encoder

### ISSUE THREAD

**Issue by perlitz** [huggingface/transformers#15126]
Hi @NielsRogge,
Thanks for the TAPAS implementation!

I'm trying to to train the model to perform text generation conditioned on tables.
Since TAPAS can encode the semi-structured meaning in tables, I guessed it was a good choice to use it as an encoder and say GPT2 as a decoder.

I however encountered a problem when trying to generate from that EncoderDecoder model, this:
![image](https://user-images.githubusercontent.com/4630195/149194029-d7a664b6-374d-4dc9-a2dd-fb3bf007cd93.png)

results in the following error:
![image](https://user-images.githubusercontent.com/4630195/149193959-601a3129-7bc8-49ad-aa72-2463158f7202.png)

I guess this is since model.generate() for EncoderDecoder does not expect to have the extra token_type_ids that TAPAS has. Can you think of a way I can make this work?

Thanks!

**Comment by NielsRogge** [comment]
This question has been answered on the [forum](https://discuss.huggingface.co/t/using-generate-with-tapas-as-encoder-in-encoderdecoder/13655).
