### ISSUE TITLE
Error when running TFT5ForConditionalGeneration with tensorflow-cpu==2.8.0-rc0

### ISSUE THREAD

**Issue by tdomagal** [huggingface/transformers#15139]
### Environment info
- `transformers` version: 4.15.0
- Platform: Linux-5.4.0-88-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.8.0-rc0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
- T5: @patrickvonplaten
or
- TensorFlow: @Rocketknight1

## Information

Model I am using T5:

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

## To reproduce

Steps to reproduce the behaviour:

1. upgrade tensorflow to 2.8.0

> pip install -U tensorflow-cpu==2.8.0rc0

2. follow example, like in https://github.com/snapthat/TF-T5-text-to-text/blob/master/snapthatT5/notebooks/TF-T5-%20Training.ipynb
3. error raised during fit call:
```
        ValueError: Found unexpected losses or metrics that do not correspond to any Model output: dict_keys(['loss']).
 Valid mode output names: ['output_1']. Received struct is: {'loss': <function dummy_loss at 0x7f7a2d430e50>}.
```

## Expected behavior

No error

**Comment by Rocketknight1** [comment]
Can you confirm if this issue still occurs when using TF 2.6 or 2.7?

**Comment by tdomagal** [comment]
In case of 2.7.0 issue does not reproduce.

The following steps allow for easy reproduce using transformers/examples/tensorflow/question-answering:

`python -m virtualenv -p python3 venv
source venv/bin/activate
pip install tensorflow==2.8.0-rc0

git clone https://github.com/huggingface/transformers
cd transformers
pip install .

cd examples/tensorflow/question-answering
pip install -r requirements.txt

# missing requirement:
pip install torch

python run_qa.py \
--model_name_or_path distilbert-base-cased \
--output_dir output \
--dataset_name squad \
--do_train \
--do_eval
`

**Comment by Rocketknight1** [comment]
Hmm, okay, this seems like a compatibility issue with TF 2.8 that we'll have to resolve soon. I'd guess it's likely caused by us overriding `train_step` in our code, but TF 2.8 changing the default `train_step` to handle the new `Model.compute_losses` and `Model.compute_metrics`.

Will discuss with the team and see if we can figure out a solution before the final 2.8 release. Thank you for the bug report!

**Comment by Rocketknight1** [comment]
@tdomagal @atom00 We have identified the issue - the Keras method `compute_loss` which was newly added in 2.8 is clobbering the `compute_loss` method that all HuggingFace models already had. We're going to rename our method and see if that resolves things. Thank you again for this report - it alerted us to an important issue before 2.8 went live!
