### ISSUE TITLE
/pytorch/aten/src/THC/THCTensorScatterGather.cu:100: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 3]: block: [4,0,0], thread: [319,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.

### ISSUE THREAD

**Issue by DeepFool** [huggingface/transformers#1514]
## ❓ Questions & Help

I have no idea about this error。

**Comment by LysandreJik** [comment]
Could you please provide more information? Where does this error occur? Are you using one of our example scripts? I believe there are templates you can use so we may help you more efficiently.

**Comment by DeepFool** [comment]
I run run_squad.py in a chinese reading comprehension dataset. I change sereval places in utils_squad.py ,I throw all examples which have no answer because my passage is so longth. if i don't throw all examples without answer, my trained model will predict no answer in test dataset. This error occur in the begining of training. I have no idea why this error happen ?

**Comment by DeepFool** [comment]
> Could you please provide more information? Where does this error occur? Are you using one of our example scripts? I believe there are templates you can use so we may help you more efficiently.

I run run_squad.py in a chinese reading comprehension dataset. I change sereval places in utils_squad.py ,I throw all examples which have no answer because my passage is so longth. if i don't throw all examples without answer, my trained model will predict no answer in test dataset. This error occur in the begining of training. I have no idea why this error happen ?
