### ISSUE TITLE
Main and train for CTRL model

### ISSUE THREAD

**Issue by roholazandie** [huggingface/transformers#1515]
## 🚀 Feature

I have seen the CTRL model has been added to the repo but I don't see any script to run or train it. Is this going to be added soon?

**Comment by LysandreJik** [comment]
The CTRL model has been added to the [run_generation](https://github.com/huggingface/transformers/blob/master/examples/run_generation.py) script as of now. We will implement it in other scripts as time goes on, but as it has the same API as the other models hosted on our repo it the training script would be very similar to the current training scripts.
