### ISSUE TITLE
Add in `model.generate` support to encoder outputs  for flax models

### ISSUE THREAD

**Issue by borisdayma** [huggingface/transformers#15161]
# 🚀 Feature request

Add support to encoder outputs in `model.generate` for flax models (similar to Pytorch models).

## Motivation

With JAX, we need to pass a seed for each generation iteration. So when we want different samples, we may need to run the same function multiple times.

For Encoder/Decoder models such as Bart, we could calculate the encoder outputs once and then directly pass them to the decoder, which could potentially save half of the computations (when encoder/decoder have same size).

## Your contribution

Not sure the best way to implement it but it seems that they typically come from `model._prepare_encoder_decoder_kwargs_for_generation`

@patil-suraj @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @borisdayma, 

Aren't we already doing this here: https://github.com/huggingface/transformers/blob/b8810847d0576e3c142854ad3b8a607ecd3df291/src/transformers/generation_flax_utils.py#L140 ?

**Comment by patrickvonplaten** [comment]
I see! Yeah you're right it should be as easy as this. We can add a `encoder_outputs` to the `generate()` function and then only call `encode()` if it's not present (that's what we're doing in PyTorch as well). Would you like to open a PR about it maybe? :-)
