### ISSUE TITLE
Bug in seq2seq fine tuning section of Automatic Speech Recognition Examples

### ISSUE THREAD

**Issue by sekharvth** [huggingface/transformers#15176]
## Environment info
- `transformers` version: 4.16.0.dev0
- Platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.12
- PyTorch version (GPU?): 1.10.0+cu111 (True)
- Tensorflow version (GPU?): 2.7.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help
@patrickvonplaten , @anton-l 

## Information

Model I am using (Bert, XLNet ...): Wave2vec2-2-BART fine tuning

The problem arises when using:
* [ ] the official example scripts: 

In the code snippet from this section : https://github.com/huggingface/transformers/tree/master/examples/pytorch/speech-recognition#sequence-to-sequence

In this line :
```model = SpeechEncoderDecoderModel.from_encoder_decoder_pretrained(encoder_id, decoder_id, encoder_add_adapter=True, encoder_feat_proj_dropout=0.0, encoder_layerdrop=0.0, max_length=200, num_beams=5)```

the arguments ```encoder_add_adapter=True, encoder_feat_proj_dropout=0.0, encoder_layerdrop=0.0``` throws an error with the traceback:

```TypeError: __init__() got an unexpected keyword argument 'add_adapter'```

When I remove those 3 arguments, it works and trains properly. 

Per the Readme, these arguments are added because`**by default a single output vector of wav2vec2-base has a receptive field of ca. 25ms (cf. with section 4.2 of the official Wav2Vec2 paper), which represents a little less a single character. BART on the other hand makes use of a sentence-piece tokenizer as an input processor so that a single hidden vector of bart-base represents ca. 4 characters. To better align the output of Wav2Vec2 and BART's hidden vectors for the cross-attention mechanism, we further subsample Wav2Vec2's output by a factor of 8 by adding a convolution-based adapter.**' 

It seems the accuracy would take a hit on removing those arguments. However, adding them raises exceptions. 

Could you please look into this? @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Thanks for reporting this. It should be fixed soon: https://github.com/huggingface/transformers/pull/15056 . I'll make sure to speed-up the process now - sorry for being so late on this.

**Comment by sekharvth** [comment]
No worries! Thanks for the prompt resolution
