### ISSUE TITLE
Unclear documentation regarding sequence length for all-MiniLM-L6-v2

### ISSUE THREAD

**Issue by sanderland** [huggingface/transformers#15179]
On [the model card for MiniLM-L6](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2) it says

> By default, input text longer than 256 word pieces is truncated.

However, looking at the model and tokenizer
```model = AutoModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")```

It seems to have a sequence length of 512 in its embeddings, and also have this set in the tokenizer as the max length.
The huggingface tokenizer picks up on this higher max length, and does not truncate to 256, although using the SentenceTransformer package does this in its tokenization step.

I am not sure whether this is merely a documentation oversight, or a sign of some deeper problem.

Version:  transformers  4.15.0

**Comment by mistborn17** [comment]
There is a related discussion here - https://stackoverflow.com/questions/75901231/max-seq-length-for-transformer-sentence-bert
