### ISSUE TITLE
run_t5_mlm_flax.py Multi GPU Training

### ISSUE THREAD

**Issue by ToluClassics** [huggingface/transformers#15189]
## Environment info

- `transformers` version:  4.15.0
- Platform: Ubuntu
- Python version: Python 3.9.9
- PyTorch version (GPU?): 1.10.1

### Who can help
@patil-suraj 
@patrickvonplaten

## Information

Model I am using (T5):

I am currently trying to pretrain T5 from scratch on a custom dataset using the [`run_t5_mlm_flax.py`](https://github.com/huggingface/transformers/blob/master/examples/flax/language-modeling/run_t5_mlm_flax.py) on multiple gpus but when I log the GPU count using `jax.local_device_count()` and `jax.local_device_count()` it returns 1.

Does this mean the script is training with just one GPU and if so how can I make It distributed?
Thank you!

The tasks I am working on is:
* [ ] Pretraining T5 from scratch on a custom dataset

**Comment by patrickvonplaten** [comment]
Hey @ToluClassics,

Could you please open an issue on https://github.com/google/jax as your problem does not seem to be related to Transformers

**Comment by gundalav** [comment]
@ToluClassics @patrickvonplaten 
I also have the same issue with the exact same script.

How is it resolved finally?
How can I make run_t5_mlm_flax.py use GPU instead of CPU?

G.V.
