### ISSUE TITLE
Question about fine-tuning with vision transformer (VIT)

### ISSUE THREAD

**Issue by YHYeooooong** [huggingface/transformers#15192]
Thanks for sharing great work!
I have a simple question about fine-tuning with VIT.
Is there any option for selecting trainable weight during fine-tuning phase? Or can I only train all weight?

**Comment by NielsRogge** [comment]
Hi,

You can easily disable parameters which you don't want to train with requires_grad=False:

```
from transformers import ViTForImageClassification

model = ViTForImageClassification.from_pretrained("google/vit-base-patch16-224-in21k")

for name, param in model.named_parameters():
      if name == "...":
         param.requires_grad = False
```

**Comment by YHYeooooong** [comment]
Thank you for your fast and kind response! I will try it!
