### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#1520]
## 🚀 Add changelog between versions

New versions are pushed to PyPi at a steady pace, but it's not evident to find the changes that new versions bring. Is there a changelog anywhere? Something similar to a HISTORY file would be nice. I think it would definitely contribute to better documentation!

**Comment by LysandreJik** [comment]
Hi @BramVanroy, we detail the changes in the ["Releases" section](https://github.com/huggingface/transformers/releases).  Are you thinking of something different?

Having a documentation per-version is on our roadmap, it should help tremendously regarding version changes.

**Comment by BramVanroy** [comment]
Ah, I was looking inside different major version commits for some sort of changelog file - which still might be useful in itself, as you indicate. But having the Github releases is exactly what I was after! Apologies, should've thought this through.
