### ISSUE TITLE
Add support for BERT SequenceClassification conversion to ONNX

### ISSUE THREAD

**Issue by naimenz** [huggingface/transformers#15214]
# 🚀 Feature request

Currently, the `SequenceClassification` pipeline is not supported for converting BERT-based models to ONNX. Support for this pipeline would be great.

## Motivation

As part of a recent internship, I needed to deploy a `SequenceClassification` `SciBERT` model by first converting it to ONNX and quantizing it. I wrote a script that did this, and so thought I should contribute this to the repo.

## Your contribution

I'd be happy to make a PR, but I haven't contributed before so I thought I'd make an issue first to check that there were no problems I hadn't seen before diving in.

For example:
* Is this something that is already being worked on? (I couldn't see an open PR or issue related to it, but maybe there's other work I don't know about)
* Are there other factors that would complicate this work? (It was pretty simple to quantize the individual models I was working with, but I can imagine there being more difficulties in implementing it generally)

**Comment by NielsRogge** [comment]
I'm pretty sure xxxForSequenceClassification models are supported. You can read the updated docs [here](https://huggingface.co/docs/transformers/master/en/serialization).

For instance, you can convert one as follows:

```
python -m transformers.onnx --model=distilbert-base-uncased-finetuned-sst-2-english \
                            --feature=sequence-classification onnx/
```

**Comment by naimenz** [comment]
Ah you're right, I must have somehow had an older version, really sorry about that! Next time I'll try to make a first issue that is actually an issue.
