### ISSUE TITLE
ALL YOUR BASE ARE BELONG TO 504.

### ISSUE THREAD

**Issue by ark10806** [huggingface/transformers#15215]
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/30382262/150070377-edb319a5-7c28-4478-ba8e-123aebc46499.png">

**Comment by kcoms555** [comment]
![image](https://user-images.githubusercontent.com/48780754/150070713-002d6e62-f87f-4d8e-b380-7963413953b8.png)
