### ISSUE TITLE
where is the 4.16.0dev??

### ISSUE THREAD

**Issue by sipie800** [huggingface/transformers#15223]
I'm running the run_mlm.py script.
There is such a line,

# Will error if the minimal version of Transformers is not installed. Remove at your own risks.
check_min_version("4.16.0.dev0")

but where is it?
can't find by pip,no in github too.

**Comment by LysandreJik** [comment]
Hey! That's the current `master` version :)

https://github.com/huggingface/transformers/blob/80f72960913ab6682451c33dfa8035ef0c932128/setup.py#L354

**Comment by LysandreJik** [comment]
You can either clone the repo and install it locally, or install it with the following:
```
pip install -U git+https://github.com/huggingface/transformers
```
