### ISSUE TITLE
Why the codes of training BERT from scratch are deprecated 

### ISSUE THREAD

**Issue by anhnt170489** [huggingface/transformers#1523]
## ❓ Questions & Help
I'm wondering why the team removed the codes of training BERT from scratch, including pregenerate_training_data.py and finetune_on_pregenerated.py. They're very helpful and I still continue developing them to train the BERT as well as Roberta from scratch.

**Comment by thomwolf** [comment]
They were community provided and the core team didn't have the bandwidth to maintain them.

Also we want to limit the number of single-model examples now and favor examples that work for a range of models.

If you want to update them to the current version of the repo and add the various models (for instance all the models currently in `run_lm_finetuning`), happy to review a PR.
