### ISSUE TITLE
Export LayoutLMv2 to TorchScript

### ISSUE THREAD

**Issue by vvalouch** [huggingface/transformers#15254]
## Environment info

- `transformers` version: 4.15.0
- Platform: MacOS
- Python version: 3.8
- PyTorch version (GPU?): 1.10 CPU
- Tensorflow version (GPU?): N/A
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@LysandreJik

## Information

Model I am using LayoutLMv2:

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```
model_dir = "microsoft/layoutlmv2-base-uncased"
model = AutoModelForTokenClassification.from_pretrained(model_dir)
processor = LayoutLMv2Processor.from_pretrained(model_dir)
image = Image.open('./image.jpg').convert("RGB")
encoded_input = processor(
    image, return_tensors="pt"
)

traced_model = torch.jit.trace(func=model,
                                   strict=False,  
                                   example_inputs=[encoded_input['input_ids'], encoded_input['bbox'],
                                                   encoded_input['image'], encoded_input['attention_mask'],
                                                   encoded_input['token_type_ids']])
```
Results in:
<img width="998" alt="Screenshot 2022-01-20 at 15 52 02" src="https://user-images.githubusercontent.com/22592860/150364030-c79e4a1e-b694-48e6-9ed7-175eb516a6ac.png">

```
Traceback (most recent call last):
  File "/some_path/python3.8/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
  File "/some_path/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/some_path/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/some_path/python3.8/site-packages/transformers/models/layoutlmv2/modeling_layoutlmv2.py", line 1179, in forward
    outputs = self.layoutlmv2(
  File "/some_path/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/some_path/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/some_path/python3.8/site-packages/transformers/models/layoutlmv2/modeling_layoutlmv2.py", line 888, in forward
    text_layout_emb = self._calc_text_embeddings(
  File "/some_path/python3.8/site-packages/transformers/models/layoutlmv2/modeling_layoutlmv2.py", line 753, in _calc_text_embeddings
    embeddings = inputs_embeds + position_embeddings + spatial_position_embeddings + token_type_embeddings
RuntimeError: The size of tensor a (241) must match the size of tensor b (290) at non-singleton dimension 1
```

## Expected behavior

1. the torch.jit.trace conversion should not crash

**Comment by LysandreJik** [comment]
cc @NielsRogge

**Comment by vvalouch** [comment]
I was looking into a bit more and I found out that the reason why the torchscript conversion is crashing are following:
1) torch.jit._trace.py ->line 958 module._c._create_method_from_trace is unsqueezing the inputs thus instead of passing original e.g. attention_mask input as {Tensor:(1,241)} it is passing {Tensor:(tensor(1),tensor(241)}
2) modeling_layoutlmv2.forward (line 804) is expecting input in form of {Tensor:(1,input_size)}. It would be great to add some check that would warn me that the input that I am passing in has invalid shape as `The size of tensor a (241) must match the size of tensor b (290)` is rather hard to track where exactly is the mistake.

**Comment by NielsRogge** [comment]
Hi,

Currently, LayoutLMv2 is not supported out-of-the-box to work with TorchScript (see #14457). However, there was an effort to make it work (see #14462). Feel free to work further on this to make it available.
