### ISSUE TITLE
Benchmark link in transformers/notebooks/README.md is broken

### ISSUE THREAD

**Issue by evandros-ks** [huggingface/transformers#15267]
Hi @sgugger,

I noticed the link in the transformers/notebooks/README.md (https://github.com/huggingface/transformers/tree/master/notebooks) for the Benchmarks notebook is broken.

I believe the correct link should be: https://github.com/huggingface/notebooks/blob/master/examples/benchmark.ipynb

**Comment by sgugger** [comment]
Thanks for flagging this! Do you want to a make a PR to fix it?

**Comment by evandros-ks** [comment]
Sure, I'll send one shortly
