### ISSUE TITLE
Training GPT or GPT-2 from scratch

### ISSUE THREAD

**Issue by LeonCrashCode** [huggingface/transformers#1527]
## ❓ Questions & Help

I am trying to retrain GPT or GPT-2 from scratch, is there any implementation for this?

**Comment by iedmrc** [comment]
I think, just create an instance of the model (without loading from pretrained one), switch it to train mode and run. That's all.

**Comment by johncwok** [comment]
I am currently trying to implement this as well. Once I figured it out i'll let you know !
