### ISSUE TITLE
Self-Attention Layers for Perceiver Decoder

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [huggingface/transformers#15282]
This feature request is about the PerceiverIO codebase, specifically about the implemented decoders. It seems like there are no self-attention layers, only a single cross-attention layer.  Is that by design?  Several current published methods mention cross- and self-attention layers as part of the decoding process, would it be possible to include this functionality?   

https://github.com/huggingface/transformers/blob/7799b6128feb17b63c47ed77a71fa367d26492d2/src/transformers/models/perceiver/modeling_perceiver.py#L2035

**Comment by NielsRogge** [comment]
Closing this issue, as I've answered your question. Feel free to re-open if you have further questions.
