### ISSUE TITLE
pytorch NER example dataset deleted

### ISSUE THREAD

**Issue by KentonMurray** [huggingface/transformers#15281]
The file examples/pytorch/token-classification/run_ner.py is looking for a hardcoded conll2003 dataset.

In the hardcoded link, the following change removed the dataset:
https://github.com/davidsbatista/NER-datasets/commit/9d8f45cc7331569af8eb3422bbe1c97cbebd5690

To fix, the hardcoded link needs to be changed to a stable location or not be hardcoded.

**Comment by NielsRogge** [comment]
Closing this, as datasets has updated the URL (see https://github.com/huggingface/datasets/issues/3582).
