### ISSUE TITLE
Robust Speech Challenge Evaluation File does not use entire dataset for metric calculation

### ISSUE THREAD

**Issue by anuragshas** [huggingface/transformers#15307]
## Environment info

- `transformers` version: 4.15.0
- Platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.12
- PyTorch version (GPU?): 1.10.0+cu111 (True)
- Using GPU in script?: Yes

### Who can help
@patrickvonplaten, @anton-l

## To reproduce

1. ~/transformers/examples/research_projects/robust-speech-event/eval.py --model_id ./ --dataset mozilla-foundation/common_voice_7_0 --config sv-SE --split test --log_outputs

## Expected behavior

1. Evaluation is done only on 10 examples [https://github.com/huggingface/transformers/blob/master/examples/research_projects/robust-speech-event/eval.py#L71 ](https://github.com/huggingface/transformers/blob/master/examples/research_projects/robust-speech-event/eval.py#L71 ) It should be done on entire dataset provided
2. To avoid any ambiguity WER and CER are generally reported in percentages but [https://github.com/huggingface/transformers/blob/master/examples/research_projects/robust-speech-event/eval.py#L26](https://github.com/huggingface/transformers/blob/master/examples/research_projects/robust-speech-event/eval.py#L26) will print the results in range of 0-1

**Comment by patrickvonplaten** [comment]
Thanks a lot for opening this issue @anuragshas! Indeed one should comment out this line when evaluating the model actually on the full dataset! I've left it here so that one can easily test the script. Will comment it out on master now :-)
