### ISSUE TITLE
preprocessing_num_workers missing in run_summarization_no_trainer

### ISSUE THREAD

**Issue by yananchen1989** [huggingface/transformers#15338]
Hello, I find that in script: https://github.com/huggingface/transformers/blob/master/examples/pytorch/summarization/run_summarization_no_trainer.py

The `preprocessing_num_workers` does not exist. It just appears in the arguments, but does not take effect in dataset map operations.

So is it intentionally missing ?

**Comment by sgugger** [comment]
Seems like an oversight. Do you want to make a PR to fix this?

**Comment by yananchen1989** [comment]
> Seems like an oversight. Do you want to make a PR to fix this?

Sorry, I don't know how to make a PR.
