### ISSUE TITLE
how can i write tensorboard when i train model with the script "run_speech_recognition_ctc.py" 

### ISSUE THREAD

**Issue by JucyCherry** [huggingface/transformers#15339]
I found that there was no "outputdir/runs/" directory created  during training ，is there any params to write tensorboard？
 @sgugger @patrickvonplaten @anton-l 

## Environment info
transformers 4.16.0.dev0

**Comment by patrickvonplaten** [comment]
Hey @JucyCherry,

Thanks for the issue! I think all you need to do is the following:

1. Install `tensorboard`: https://pypi.org/project/tensorboard/
2. Run training. The Trainer in the `run_speech_recognition_ctc.py` script automatically correctly uses the `tensorboard`.

You could try out the explanation to check if it works: https://github.com/huggingface/transformers/tree/master/examples/research_projects/robust-speech-event#how-to-finetune-an-acoustic-model

**Comment by JucyCherry** [comment]
thanks a lot !
