### ISSUE TITLE
DebertaV2 For run_qa.py

### ISSUE THREAD

**Issue by yinzhangyue** [huggingface/transformers#15345]
## Environment info
- `transformers` version: 4.15.0
- Platform: Linux-4.4.0-142-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.9
- PyTorch version (GPU?): 1.10.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.3.5 (cpu)
- Jax version: 0.2.22
- JaxLib version: 0.1.72

## Models:

- [microsoft/deberta-v2-xlarge](https://huggingface.co/microsoft/deberta-v2-xlarge)

## Error:
```
Traceback (most recent call last):
  File "run_qa.py", line 642, in <module>
    main()
  File "run_qa.py", line 308, in main
    "This example script only works for models that have a fast tokenizer. Checkout the big table of models "
ValueError: This example script only works for models that have a fast tokenizer. Checkout the big table of models at https://huggingface.co/transformers/index.html#supported-frameworks to find the model types that meet this requirement
```

## Script
```
CUDA_VISIBLE_DEVICES=0 python run_qa.py \
      --model_name_or_path microsoft/deberta-v2-xlarge \
      --dataset_name squad \
      --do_train \
      --do_eval \
      --per_device_train_batch_size 12 \
      --learning_rate 3e-5 \
      --num_train_epochs 2 \
      --max_seq_length 384 \
      --doc_stride 128 \
      --output_dir /tmp/debug_squad/
```
[last run_qa.py](https://github.com/huggingface/transformers/blob/master/examples/pytorch/question-answering/run_qa.py)

## My Problem
DebertaV2 has significant capabilities in NLI task. I want to use DebertaV2 for QA task. However, DebertaV2 don't have DebertaV2TokenizerFast. How can I use DevertaV2 for QA task? Is it possible to get offset_mapping without TokenizerFast? Thank you very much!

**Comment by nbroad1881** [comment]
DebertaV2TokenizerFast is close to being merged. If you look at the code in the PR, you can use it now. https://github.com/huggingface/transformers/pull/14928

**Comment by yinzhangyue** [comment]
OK! thank you~
