### ISSUE TITLE
what is the equivalent manner for those lines?

### ISSUE THREAD

**Issue by mathshangw** [huggingface/transformers#15404]
layers,_ = BERTModel(tokens_tensor)
embedding = layers[11].squeeze(0)

what is the equivalent manner for those lines if I need to import BERT from transformer instead Pytorch? does that mean the embedding from all eleven layers ? or the last only?

**Comment by mathshangw** [comment]
is there any help please ?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!

**Comment by mathshangw** [comment]
i  already opened one but no response .. i hope someone can help
https://discuss.huggingface.co/t/indexerror-tuple-index-out-of-range-problem/14225

**Comment by mathshangw** [comment]
is there any help please?
