### ISSUE TITLE
AutoTokenizer does not support XGLMTokenizer

### ISSUE THREAD

**Issue by mrseeker** [huggingface/transformers#15405]
## Environment info

- `transformers` version:  4.17.0.dev (f380bf2b612e6030ef8bc8904b287d274f035e29)
- Platform: Linux
- Python version: 3.8
- PyTorch version (GPU?): 1.9.0
- Tensorflow version (GPU?): n/a
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?:

### Who can help
@patil-suraj 

## Information

Model I am using (Bert, XLNet ...): XGLM

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details below)

## To reproduce

Just execute this piece of code:
```
from transformers import AutoTokenizer
tokenizer=AutoTokenizer.from_pretrained(facebook/xglm-1.7B")
```

## Expected behavior

tokenizer to be of class "XGLMTokenizer"

**Comment by patil-suraj** [comment]
Thank you for reporting this issue! The fix is here #15406
