### ISSUE TITLE
Type of model for each GLUE task

### ISSUE THREAD

**Issue by evanweissburg** [huggingface/transformers#1541]
## ❓ Questions & Help

There are nine GLUE tasks, and I wanted to verify which BERT model type is best suited for each task. Can anyone confirm these matchings? I am not sure what to do for STS-B especially, and am unsure if BertForMultipleChoice is the correct option for MNLI.

Corpus of Linguistic Acceptability (CoLA) - **boolean**: _BertForSequenceClassification_
Stanford Sentiment Treebank (SST-2) - **boolean**: _BertForSequenceClassification_

Microsoft Research Paraphrase Corpus (MRPC) - **boolean**: _BertForSequenceClassification_
Quora Question Pairs Dataset (QQP) - **boolean**: _BertForSequenceClassification_
Semantic Textual Similarity Benchmark (STS-B) - **float**: ???

Multi-Genre Natural Language Inference Corpus (MNLI) - **3-class**: _BertForMultipleChoice_
Stanford Question Answering Dataset (QNLI) - **boolean**: _BertForSequenceClassification_
Recognizing Textual Entailment Dataset (RTE) - **boolean**: _BertForSequenceClassification_
Winograd Schema Challenge (WNLI) - not used

**Comment by evanweissburg** [comment]
All models on GLUE should use BertForSequenceClassification (MNLI is 3 class, STS-B is 1 class).

**Comment by julien-c** [comment]
As specified in the documentation, for `XxxForSequenceClassification` models:

```
If ``config.num_labels == 1`` a regression loss is computed (Mean-Square loss),
If ``config.num_labels > 1`` a classification loss is computed (Cross-Entropy).
```

So you can use `BertForSequenceClassification` for a regression task such as STS-B.
