### ISSUE TITLE
Performance of T5

### ISSUE THREAD

**Issue by zzasdf** [huggingface/transformers#15415]
I'm testing the performance of T5, and want to reproduce the result on WMT  English to German newstest2014 in the table 14. But the results I got were always 1 or 2 points lower. Are there any scripts that can reproduce the result with pytorch?

**Comment by zzasdf** [comment]
I have found that

**Comment by MichaelZhouwang** [comment]
> I have found that

Hi, could you please share how you get to reproduce to results?

**Comment by zzasdf** [comment]
It's impossible, because the model hasn't been finetune on the translation. The details are on https://github.com/huggingface/transformers/tree/v2.9.0/examples/translation/t5

**Comment by MichaelZhouwang** [comment]
@zzasdf Thanks a lot!
