### ISSUE TITLE
Running CTRL Model On Google Colab Environment

### ISSUE THREAD

**Issue by yusufani** [huggingface/transformers#1542]
## ❓ Questions & Help

As you know Google Colab environment has ****12 GB** ram** limit . When i want to run [run_generation.py](https://github.com/huggingface/transformers/blob/master/examples/run_generation.py) file , Colab automatically stops the process. How much ram does the CTRL Model need? Where can I learn that? Or is there another way to run it?

**Comment by BramVanroy** [comment]
[In the official repo,](https://github.com/salesforce/ctrl) you can find a 'lower_memory' branch. You can take a look there. As always, you can try to make the batch size and max sequence length smaller, too.

**Comment by yusufani** [comment]
Thank you for your help

**Comment by BramVanroy** [comment]
Please close this topic if you have no further questions.
