### ISSUE TITLE
Where is pytorch-pretrained-BERT?

### ISSUE THREAD

**Issue by ShallTearchen** [huggingface/transformers#1543]
## ❓ Questions & Help

As the title shows, where is pytorch-pretrained-BERT? Please tell me the path, THX.

**Comment by LysandreJik** [comment]
`pytorch-pretrained-BERT` is this library, but four or five months ago. It evolved into `pytorch-transformers` as more models were added to the library, before becoming `transformers` as we now have a front-end for both pytorch and tensorflow.

**Comment by iedmrc** [comment]
is this still an issue?

**Comment by TheEdoardo93** [comment]
I don't think so. In my opinion, @ShallTearchen would know where it goes pytorch-pretrained-BERT, but I think that @LysandreJik explains very well the transformation of this library to Transformers.
In my opinion, I'll close this "issue"!

> is this still an issue?
