### ISSUE TITLE
line 111 in convert_megatron_bert_checkpoint.py cause error "AttributeError: 'Namespace' object has no attribute 'get'"

### ISSUE THREAD

**Issue by bugface** [huggingface/transformers#15448]
The new script convert_megatron_bert_checkpoint.py for converting Megatron checkpoint to HF model has a minor error at line 111  

```
config.intermediate_size = ds_args.get("ffn_hidden_size", 4 * ds_args.hidden_size)
```

ds_args is <class 'argparse.Namespace'> which does not have "get" function

change to 

```
config.intermediate_size = ds_args.ffn_hidden_size if "ffn_hidden_size" in ds_args else 4 * ds_args.hidden_size
```
fix the issue.

**Comment by LysandreJik** [comment]
hey @bugface, thanks for opening an issue! Do you want to open a PR to fix this? :)
