### ISSUE TITLE
tokenizer truncation_side is not set up with from_pretrained call

### ISSUE THREAD

**Issue by LSinev** [huggingface/transformers#15440]
## Environment info

- `transformers` version: 4.16.1

### Who can help
Library:
- Tokenizers: @SaulLu
- Pipelines: @Narsil

## Information

Model I am using (Bert, XLNet ...): **GPT2Tokenizer**

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce
```
tokenizer = GPT2Tokenizer.from_pretrained("gpt2", truncation_side="left")
print(tokenizer.truncation_side)
```
```
right
```

## Expected behavior

```
left
```
## Possible solution

I believe the problem is in the missing part at `tokenization_utils_base.py` (just like the one for the padding side at https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils_base.py#L1457-L1462)
```
        # Truncation side is right by default and overridden in subclasses. If specified in the kwargs, it is changed.
        self.truncation_side = kwargs.pop("truncation_side", self.truncation_side)
        assert self.truncation_side in [
            "right",
            "left",
        ], f"Truncation side should be selected between 'right' and 'left', current value: {self.truncation_side}"
```
Feel free to add this solution if it is good enough without writing tests, as I don't have transformers dev environment ready for PR right now.

**Comment by SaulLu** [comment]
Thanks for the detailed issue @LSinev ! Indeed, this seems to be a desirable change! 

@Narsil, it looks like we doubled the work, we should choose one of the 2 PRs. :relaxed:

**Comment by Narsil** [comment]
Haha no worries @SaulLu .

Whichever you prefer as a PR, I don't have a real preference for the test choice. (Yours has much more coverage, mine is much simpler)

**Comment by SaulLu** [comment]
Thank you! Personally, I think it would be good to test the behavior on as many tokenizer classes as possible, so we'll start with mine? 

I will of course put both of you as co-authors.

**Comment by Narsil** [comment]
Go right ahead, I'll close my PR.
