### ISSUE TITLE
Support dynamical input size and shape for TrOcr input image

### ISSUE THREAD

**Issue by kolia1985** [huggingface/transformers#15458]
# 🚀 Feature request

Support dynamical input size and shape for TrOcr input image.

## Motivation

TrOcr has input shape for image 384x384, but can recognise only single line. So It does not effective utilize resources.

**Comment by Nikhil34712** [comment]
Hey @kolia1985  actually im implementing TrOCR for  ocr when i am trying to run the error has been showing up as The input dimensions are not matching to model input dimensions do you have idea about thesolution to this error??
