### ISSUE TITLE
Pretrained model for sequence to sequence question answering

### ISSUE THREAD

**Issue by dharakotecha** [huggingface/transformers#15478]
Hi,
Is there a model available which has been trained on sequence to sequence question answering with the SQUAD v1/v2 dataset?
I could not find any in the huggingface model hub.

**Comment by dharakotecha** [comment]
Hi
Thanks for your response @NielsRogge. 
I meant a generative question answering model trained on SQuAD. This implies that the model is trained with an objective to generate answer sequence unlike the objective to predict start and end index of the answer.

**Comment by NielsRogge** [comment]
Hi,

There are a few available, like this one: https://huggingface.co/valhalla/t5-small-qa-qg-hl

**Comment by dharakotecha** [comment]
Thanks @NielsRogge 
This is exactly what I am looking for.
