### ISSUE TITLE
tf.concatenate does not exist

### ISSUE THREAD

**Issue by pedro-r-marques** [huggingface/transformers#15477]
## Environment info
Any

### Who can help
@Rocketknight1

## Information

BERT TFBertSelfAttention layer calls a function `tf.concatenate` when given a `past_key_value` parameter. This function does not exist in the TF 2.0 API. The correct function name is `tf.concat`.

## To reproduce

Call a TFBertLayer layer with a non nil `past_key_value` argument.

## Expected behavior

The code should be modified to use `tf.concat` instead.

**Comment by Rocketknight1** [comment]
Good spot! Would you be willing to submit a PR? If not, don't worry, let us know and we'll do it instead.

**Comment by pedro-r-marques** [comment]
I will try to submit a PR. It will probably take me a few days to craft a test case that exercises this functionality.

**Comment by ydshieh** [comment]
Hi, this is my faute in my PR: #13222. There are a few files involved, in particular, the TF template file

```
transformers\templates\adding_a_new_model\cookiecutter-template-{{cookiecutter.modelname}}\test_modeling_tf_{{cookiecutter.lowercase_modelname}}.py
```

I am sorry about this mistake. @pedro-r-marques If you still want to open the PR, could you also fix the other models that have `tf.concatenate`, please? Thank you!

**Comment by ydshieh** [comment]
Hi @pedro-r-marques 

Would it be OK for me to submit a PR for this issue? Or you want to contribute once you have the time?

**Comment by pedro-r-marques** [comment]
@ydshieh Please do go ahead. I didn't have the opportunity to reproduce the use case for `past_key_value`.
