### ISSUE TITLE
Isn't `transformers.utils.fx` compatible with torch 1.10+ ?

### ISSUE THREAD

**Issue by hyunwoongko** [huggingface/transformers#15483]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/transformers/utils/fx.py", line 579, in symbolic_trace
    tracer = HFTracer(batch_size=batch_size, sequence_length=sequence_length, num_choices=num_choices)
  File "/opt/conda/lib/python3.7/site-packages/transformers/utils/fx.py", line 244, in __init__
    f"Found an incompatible version of torch. Found version {torch_version}, but only version "
ImportError: Found an incompatible version of torch. Found version 1.10.0, but only version 1.9 is supported.
```

torch 1.10+ is also providing fx, but why the Transformers limits it to torch 1.9?

cc @stas00 @thomasw21 @michaelbenayoun

**Comment by hyunwoongko** [comment]
I checked this removing [this line](https://github.com/huggingface/transformers/blob/master/src/transformers/utils/fx.py#L243). but it worked well. I think we should change [this line](https://github.com/huggingface/transformers/blob/13297ac71cb45241c7de6b9716ae48f523a824f7/src/transformers/file_utils.py#L408).

I'll open a new PR.

**Comment by hyunwoongko** [comment]
I found [this](https://github.com/huggingface/transformers/pull/14321).

**Comment by LysandreJik** [comment]
cc @michaelbenayoun

**Comment by stas00** [comment]
Yeah, it had to do with torch doing not back-compat changes in the FX API - since this is all experimental.

But yes, Michael is your man.

Since FX API is in flux still I think ideally we should target pt-1.11 which should be out in probably a month or so.

**Comment by thomasw21** [comment]
I think fx became stable as of torch 1.10, so we should maybe drop that constraint?

**Comment by michaelbenayoun** [comment]
Hi, you are right #14321 solves your issue, and as @thomasw21 said, if FX indeed became stable at torch 1.10, we will relax that constraint to something more like 1.10+.
Should merge the PR soon!
