### ISSUE TITLE
502 Server Error: Bad Gateway for url: https://huggingface.co/api/models/t5-base

### ISSUE THREAD

**Issue by EdieLu** [huggingface/transformers#15487]
Saw similar issue in this forum before, and it seems that a reboot is needed for the data centre? 

It happens when I try this - 
t5_tokenizer = T5Tokenizer.from_pretrained("t5-base")

**Comment by xudongyuuuu** [comment]
I have the same issue when I try to train a distilbert model:

502 Server Error: Bad Gateway for url: https://huggingface.co/distilbert-base-uncased/resolve/main/config.json

**Comment by heungson** [comment]
Currently, it seems that the huggingface server is down.

**Comment by EdieLu** [comment]
it's back up now
