### ISSUE TITLE
How to convert  tf_model.h5 to tf_model.ckpt

### ISSUE THREAD

**Issue by kusumlata123** [huggingface/transformers#15490]
bert model folder containd these files:

config.json
tf_model.h5
tokenizer_config.json
tokenizer.json
vocab.txt
instead of these if we require these files
 bert_config.json
 bert_model.ckpt.data-00000-of-00001
 bert_model.ckpt.index
 bert_model.ckpt.meta
 vocab.txt
then how to do this

**Comment by gante** [comment]
Hey @kusumlata123 👋 

The format you'd like to have BERT in is a TensorFlow 1.x format, which we don't support. There are two possible paths you could follow:
1. Migrate to Tensorflow 2.x, and get full compatibility with our models;
2. Attempt to convert our Keras `.h5` model into a TF 1.x checkpoint (e.g. see [here](https://stackoverflow.com/questions/45466020/how-to-export-keras-h5-to-tensorflow-pb)). However, we have no guarantees this will work :)

I'm closing the issue as there are no actions we can do from our end.
