### ISSUE TITLE
Download models from a private hub

### ISSUE THREAD

**Issue by juliensimon** [huggingface/transformers#15514]
In the context of a private hub deployment, customers would like to use from_pretrained() to load models from their hub, not from the public hub. This doesn't seem to be configurable at the moment and it would be nice to add this feature.

The obvious workaround is to clone the repo first and then load it from local storage, but this adds an extra step. It'd be great to have the same experience regardless of where the hub is hosted.

The same issue exists with the datasets library and the CLI. I'm going to create issues there as well, and I'll reference them below.

**Comment by juliensimon** [comment]
For reference:
https://github.com/huggingface/datasets/issues/3679
https://github.com/huggingface/huggingface_hub/issues/650

**Comment by NielsRogge** [comment]
Correct me if I'm wrong, but this is already supported. You only need to pass an additional argument `use_auth_token=True` for private models.

This token can be obtained by either doing the following in a notebook:

```
from huggingface_hub import notebook_login

notebook_login()
```
Note that you don't need to install `huggingface_hub`, it's included in the Transformers library.

Or, in case you're working with a terminal, by running the following command:
```
huggingface-cli login
```

**Comment by julien-c** [comment]
no @NielsRogge here Julien would like to switch the endpoint to hit a private alternative to the hf.co hub (not just a private repo) e.g. like passing a custom `HF_ENDPOINT` in `dataset` (i think we may have the same here)

Maybe it can also a a param in the `from_pretrained()` calls for ease of use (we used to have something like that for mirrors at some point)

**Comment by juliensimon** [comment]
I looked around, and what we'd basically need to do is to check for an environment variable (this already works for datasets and the hub CLI):

```
hub_url = os.getenv("HF_ENDPOINT", "https://huggingface.co")
```

What would be the best place to do this once and once only? Is there a common data structure that is globally visible in the lib?

Then, we have to update all urls for config files, tokenizers and models, e.g.

```
DISTILBERT_PRETRAINED_CONFIG_ARCHIVE_MAP = {
    "distilbert-base-uncased": f"{hub_url}/distilbert-base-uncased/resolve/main/config.json",
    "distilbert-base-uncased-distilled-squad": f"{hub_url}/distilbert-base-uncased-distilled-squad/resolve/main/config.json",
    "distilbert-base-cased": f"{hub_url}/distilbert-base-cased/resolve/main/config.json",
    "distilbert-base-cased-distilled-squad": f"{hub_url}/distilbert-base-cased-distilled-squad/resolve/main/config.json",
    "distilbert-base-german-cased": f"{hub_url}/distilbert-base-german-cased/resolve/main/config.json",
    "distilbert-base-multilingual-cased": f"{hub_url}/distilbert-base-multilingual-cased/resolve/main/config.json",
    "distilbert-base-uncased-finetuned-sst-2-english": f"{hub_url}/distilbert-base-uncased-finetuned-sst-2-english/resolve/main/config.json",
}
```

What do you think @julien-c @sgugger @LysandreJik ?

**Comment by sgugger** [comment]
Those urls are not used anywhere except internal tests, so you don't need to update them.
The endpoint just needs to be set via the env variable `HUGGINGFACE_CO_RESOLVE_ENDPOINT`, I think this is the only thing to change.

**Comment by julien-c** [comment]
Yep i think that's what I was alluding to when I wrote 
> (i think we may have the same here)

Maybe we can just rename (or alias) `HUGGINGFACE_CO_RESOLVE_ENDPOINT` to `HF_ENDPOINT` for consistency across the different libraries? WDYT?

**Comment by sgugger** [comment]
That works for me. Suggested in the PR linked above.

**Comment by juliensimon** [comment]
Great, thanks!
