### ISSUE TITLE
Various issues with  accelerate launch command for Large example

### ISSUE THREAD

**Issue by ThomasGmeinder** [huggingface/transformers#15523]
## Environment info
https://github.com/huggingface/transformers/tree/master/examples/pytorch/speech-pretraining

Python 3.6.9

## Information
I'm trying to run this command:
https://github.com/huggingface/transformers/tree/master/examples/pytorch/speech-pretraining#large

and found various issues with it:
1.  first line contains an erroneous space after the escape character:
`accelerate launch run_wav2vec2_pretraining_no_trainer.py \ `

2. The following line is missing the newline escape:
`--model_name_or_path=./ `

After fixing both I found another problem:

3. The value of --model_name_or_path is invalid: `./`

## Suggested Fix:
I fixed this with
` --model_name_or_path=patrickvonplaten/wav2vec2-large-xlsr-53-spanish-with-lm`

This command works now:
```
accelerate launch run_wav2vec2_pretraining_no_trainer.py \
	--dataset_name=librispeech_asr \
	--dataset_config_names clean clean other \
	--dataset_split_names train.100 train.360 train.500 \
	--output_dir=./test \
	--max_train_steps=200000 \
	--num_warmup_steps=32000 \
	--gradient_accumulation_steps=8 \
	--learning_rate=0.001 \
	--weight_decay=0.01 \
	--max_duration_in_seconds=20.0 \
	--min_duration_in_seconds=2.0 \
	--model_name_or_path=patrickvonplaten/wav2vec2-large-xlsr-53-spanish-with-lm \
	--logging_steps=1 \
	--saving_steps=10000 \
	--per_device_train_batch_size=2 \
	--per_device_eval_batch_size=4 \
	--adam_beta1=0.9 \
	--adam_beta2=0.98 \
	--adam_epsilon=1e-06 \
	--gradient_checkpointing
```

**Comment by patil-suraj** [comment]
cc @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @ThomasGmeinder,

Thanks for spotting `1.` and `2.` - feel free to open a PR to correct the docs :-) 
The reason why I put `--model_name_or_path=./` is because this way you can train from your local directory, but the docs should have been cleaner here indeed
