### ISSUE TITLE
Not able to load CharacterBERT

### ISSUE THREAD

**Issue by hadi-abdine** [huggingface/transformers#15545]
@LysandreJik @helboukkouri 
I faced a problem when I tried to load CharcterBERT using the following code:

```python
from transformers import AutoTokenizer, AutoConfig
from transformers import AutoModel

config = AutoConfig.from_pretrained("helboukkouri/character-bert")
tokenizer = AutoTokenizer.from_pretrained("helboukkouri/character-bert")
model = AutoModel.from_pretrained("helboukkouri/character-bert")
```

 I got this error related to model_type not found:

```
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_208703/3530088082.py in <module>
     38 
     39 
---> 40 config = AutoConfig.from_pretrained("helboukkouri/character-bert")
     41 tokenizer = AutoTokenizer.from_pretrained("helboukkouri/character-bert")
     42 model = AutoModel.from_pretrained("helboukkouri/character-bert")

~/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    630             return config_class.from_pretrained(pretrained_model_name_or_path, **kwargs)
    631         elif "model_type" in config_dict:
--> 632             config_class = CONFIG_MAPPING[config_dict["model_type"]]
    633             return config_class.from_dict(config_dict, **kwargs)
    634         else:

~/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py in __getitem__(self, key)
    345             return self._extra_content[key]
    346         if key not in self._mapping:
--> 347             raise KeyError(key)
    348         value = self._mapping[key]
    349         module_name = model_type_to_module_name(key)

KeyError: 'character_bert'
```
The same issue happens when I try any variant of CharacterBERT
Thanks for your help

## Environment info

- `transformers` version: 4.16.2
- Platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.10
- Python version: 3.8.12
- PyTorch version (GPU?): 1.10.1 (True)
- Tensorflow version (GPU?): 2.8.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by NielsRogge** [comment]
Hi,

As far as I know, the model has not yet been added to the library (see #15061).

If you're interested in character-level models, we do have 3 models available in the library right now:
* [CANINE](https://huggingface.co/docs/transformers/model_doc/canine)
* [Perceiver](https://huggingface.co/docs/transformers/model_doc/perceiver)
* [ByT5](https://huggingface.co/docs/transformers/model_doc/byt5)

**Comment by hadi-abdine** [comment]
> Hi all, so Indeed the model has not been integrated to the library yet 😢. Which is unfortunate, but at the same time I can't seem to find the time to work on that lately. If you're interested @hadi-abdine I can ping you whenever I make progress on this. And by the way, there is also [my own code](https://github.com/helboukkouri/character-bert/) which could be enough for you to start using the model.
> 
> I would just add one small comment regarding what @NielsRogge said: CharacterBERT, despite its name, is actually a word-level model (i.e. it embeds pre-tokenized pieces of strings or "words"). However, to do so, it aggregates character-level (actually, byte-level) information at the level of each of these words.
> 
> Anyway, thank you for your interest in my work! 😊

Thanks  @NielsRogge and @helboukkouri for your replies.
@helboukkouri, I just checked your code, I think it's enough for me to use the model. Thank you! But Of course I am also interested to know when CharacterBERT will be added to HuggingFace.
