### ISSUE TITLE
Fine-tune blenderbot 2.0 to retrieve from my own documents instead internet

### ISSUE THREAD

**Issue by BayanIssa** [huggingface/transformers#15548]
i have database contain of many documents , and try to build chatbot which reply for users from those documents in my database .
can i use this [way(ONLY GOLD DOCS)](https://github.com/facebookresearch/ParlAI/tree/main/projects/blenderbot2/agents)?

**Comment by patil-suraj** [comment]
Hi @BayanIssa ! It would be nice if you could use the [forum](https://discuss.huggingface.co/) for such general questions. We use issues to report bugs and for feature requests.

Also blenderbot 2.0 will soon be included in Transformers :) #12807
