### ISSUE TITLE
GPT2 not in modeltype

### ISSUE THREAD

**Issue by tuhinjubcse** [huggingface/transformers#1554]
## 🐛 Bug

Model I am using (Bert, XLNet....): GPT2

Language I am using the model on (English, Chinese....): ENGLISH

The problem arise when using:
* [ ] the official example scripts: (give details) run_glue.py
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name) MRPC GLUE
* [ ] my own task or dataset: (give details)

## To Reproduce

1.
2.
3.

python ./examples/run_glue.py --model_type gpt2 --model_name_or_path gp
t2 --task_name MRPC --do_train --do_eval --do_lower_case --data_dir ./fake --max_seq_length 512 --per_gpu_eval_batc
h_size=8 --per_gpu_train_batch_size=8 --learning_rate 2e-5 --num_train_epochs 3.0 --output_dir /tmp/bot/
10/18/2019 00:22:28 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 1, distributed training: False,
 16-bits training: False
Traceback (most recent call last):
  File "./examples/run_glue.py", line 541, in <module>
    main()
  File "./examples/run_glue.py", line 476, in main
    config_class, model_class, tokenizer_class = MODEL_CLASSES[args.model_type]
KeyError: 'gpt2'
## Environment

* OS: UBUNTU LINUX
* Python version: 3.7
* PyTorch version: LATEST
* PyTorch Transformers version (or branch): LATEST
* Using GPU ? YES
* Distributed of parallel setup ? NO
* Any other relevant information:

**Comment by cformosa** [comment]
Hey @tuhinjubcse gpt2 is a text generation model. If you look in the run_glue.py file you will see your options for model selection for using the run_glue.py script.
```
MODEL_CLASSES = {
    'bert': (BertConfig, BertForSequenceClassification, BertTokenizer),
    'xlnet': (XLNetConfig, XLNetForSequenceClassification, XLNetTokenizer),
    'xlm': (XLMConfig, XLMForSequenceClassification, XLMTokenizer),
    'roberta': (RobertaConfig, RobertaForSequenceClassification, RobertaTokenizer),
    'distilbert': (DistilBertConfig, DistilBertForSequenceClassification, DistilBertTokenizer)
}
```

**Comment by tuhinjubcse** [comment]
gpt2 is a transformer model. Why would it be limited to only generation ??

**Comment by cformosa** [comment]
It's not that you can't use it for classification, etc. It's that you would need to make a few changes to the code and model. #1248 . Right now the changes are not made for gpt2. Generally speaking, people use gpt2 for text generation.

**Comment by iedmrc** [comment]
Autoregressive models are not as good as mlms, at classification tasks. You should check masked language models (mlm) or similars. But it's not impossible, Open AI has shown some example use cases on original [GPT paper](https://s3-us-west-2.amazonaws.com/openai-assets/research-covers/language-unsupervised/language_understanding_paper.pdf). Check the figure 1 and page 6 for more details.
Also, this is not a bug but just not implemented.
