### ISSUE TITLE
i cannot connect the hf webset

### ISSUE THREAD

**Issue by zhangbo2008** [huggingface/transformers#15576]
![image](https://user-images.githubusercontent.com/35842504/153197802-010b8a95-2e7a-4a4a-9295-008107f98fdf.png)

## Environment info

- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by cronoik** [comment]
Their services are currently down. Check: https://status.huggingface.co/ to see when they are up again.
