### ISSUE TITLE
Documentation error 

### ISSUE THREAD

**Issue by Moumeneb1** [huggingface/transformers#15578]
## 

Hi, I think there is a tiny issue in the documentation of using pipelines

The current [doc](https://github.com/huggingface/transformers/blob/4a6a35bc6506dd5deb528580184c39e3e778d53b/docs/source/main_classes/pipelines.mdx) says that the KeyDataset class is in the transformers.pipelines.base, however the class is actually in the [pt_utils](https://github.com/huggingface/transformers/blob/19d37c2dd36d73537a6855c56808e524fb584459/src/transformers/pipelines/pt_utils.py)

```python
#The current doc (not working)
from transformers.pipelines.base import KeyDataset
```

```python
#The actual class is in 
from transformers.pipelines.pt_utils import KeyDataset
```

Running the current doc's examples won't work : 
```
ImportError: cannot import name 'KeyDataset' from 'transformers.pipelines.base' (/usr/local/lib/python3.7/dist-packages/transformers/pipelines/base.py)
```

**Comment by NielsRogge** [comment]
Hi,

Thanks for spotting. Feel free to open a PR to fix this!
