### ISSUE TITLE
unable to parse E:/litao/bert/bert-base-cased\config.json as a URL or as a local path

### ISSUE THREAD

**Issue by 754563116** [huggingface/transformers#1558]
## ❓ Questions & Help

train_file = 'E:/litao/bert/SQuAD 1.1/train-v1.1.json'
    predict_file = 'E:/litao/bert/SQuAD 1.1/dev-v1.1.json'
    model_type = 'bert'
    model_name_or_path  = 'E:/litao/bert/bert-base-cased'
    output_dir = 'E:/litao/bert/transformers-master/examples/output'

![微信图片_20191018180549](https://user-images.githubusercontent.com/32032029/67085767-058c0780-f1d2-11e9-96ca-df431f70b7c8.png)

**Comment by BenF99** [comment]
Did you find a solution?

**Comment by KindRoach** [comment]
> Did you find a solution?

Rename "bert_config.json" to "config.json".
