### ISSUE TITLE
Documentation of DataCollatorForLanguageModeling

### ISSUE THREAD

**Issue by yarongef** [huggingface/transformers#15609]
# 🚀 Feature request

Would you consider adding to the following tip:

"For best performance, this data collator should be used with a dataset having items that are dictionaries or BatchEncoding, with the "special_tokens_mask" key, ...."

The reason for doing so, for example: "So that special mask tokens won't be masked".

**Comment by LysandreJik** [comment]
Hey! Would you like to open a PR?

**Comment by yarongef** [comment]
Yes, I'll do that
