### ISSUE TITLE
make style produces a lot of reformatted lines

### ISSUE THREAD

**Issue by ydshieh** [huggingface/transformers#15628]
## Environment info

- `transformers` version: 4.17.0.dev0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.9.5

## Information

I am at commit `3fae83d2` (in `master` branch). When I run `make style`, there are tones of files being reformatted (no local change on my side).

```
reformatted examples\pytorch\speech-pretraining\run_wav2vec2_pretraining_no_trainer.py
reformatted examples\research_projects\jax-projects\wav2vec2\run_wav2vec2_pretrain_flax.py
reformatted examples\research_projects\onnx\summarization\bart_onnx\generation_onnx.py
reformatted examples\research_projects\distillation\run_squad_w_distillation.py
reformatted examples\research_projects\wav2vec2\run_pretrain.py
reformatted examples\research_projects\movement-pruning\masked_run_glue.py
reformatted examples\research_projects\pplm\run_pplm.py
reformatted examples\research_projects\movement-pruning\masked_run_squad.py
reformatted examples\research_projects\lxmert\modeling_frcnn.py
reformatted src\transformers\generation_beam_search.py
reformatted examples\research_projects\visual_bert\modeling_frcnn.py
reformatted src\transformers\generation_flax_utils.py
reformatted src\transformers\generation_tf_utils.py
reformatted src\transformers\models\bart\tokenization_bart.py
reformatted src\transformers\modeling_tf_utils.py
....(many more)
```

Most of them are something like: `1 / (d_head**0.5)` --> `(d_head ** 0.5)`.
(not very sure if this is a problem only on my machine)

### Who can help
@sgugger  @LysandreJik

**Comment by sgugger** [comment]
It looks like you haven't updated your black version. Make sure to run `pip install -e .[quality]` again.

**Comment by ydshieh** [comment]
@sgugger Thanks, I am thinking maybe it's the version and trying to verify -- and you already gave the answer!
