### ISSUE TITLE
TrOCR not working anymore after 4.16.2 update

### ISSUE THREAD

**Issue by thetruejacob** [huggingface/transformers#15648]
## Environment info

- `transformers` version: 4.16.2
- Platform:  Colab
- Python version: 3.8?
- PyTorch version (GPU?): latest in colab
- Tensorflow version (GPU?):
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?:

### Who can help
Models:
TrOCR @NielsRogge  

I believe something has happened to the Trainer class that now makes evaluation of NielsRogge's TrOCR  model run into a bug. 

I have reproduced his notebook here, and encountered the bug when using the latest transformers version. 
  https://colab.research.google.com/drive/1ZcwbH_JzBMT7M84eDkUw9eJRqBxyofkB?usp=sharing

**Comment by NielsRogge** [comment]
Thanks for reporting, this has been fixed in #15603.

For now, you have to install from source to have it: pip install git+https://github.com/huggingface/transformers.git
