### ISSUE TITLE
ALBERT: will it be supported?

### ISSUE THREAD

**Issue by xinqipony** [huggingface/transformers#1564]
will you release an ALBERT model?
it sets the new state of art;

# 🌟New model addition
ALBERT: A LITE BERT FOR SELF-SUPERVISED
LEARNING OF LANGUAGE REPRESENTATIONS
https://arxiv.org/pdf/1909.11942.pdf

## Model description
![image](https://user-images.githubusercontent.com/42603620/67136720-eedec280-f25c-11e9-8681-383c5e3d27a0.png)

## Open Source status

* [ ] the model implementation is available: (give details)
* [ ] the model weights are available: (give details)

**Comment by roccqqck** [comment]
https://github.com/brightmart/albert_zh

**Comment by BramVanroy** [comment]
Please direct all your questions to the main albert topic. https://github.com/huggingface/transformers/issues/1370 

Please close this current topic. It does not add anything.

**Comment by stefan-it** [comment]
... We should extend the issue template and redirect all ALBERT questions to #1370 😂
