### ISSUE TITLE
Inference API with GPT2 {"error": "Unknown error"}

### ISSUE THREAD

**Issue by nbravulapalli** [huggingface/transformers#15650]
### Who can help

@Narsil 
@LysandreJik 

## Information

When I try to use the Inference API with gpt2, I am receiving a response saying there is an `Unknown error`. I have used the same codebase for a few months now, initially it was working, then the API started returning errors about cuda (only when using gpu), then the API was working again, now the API is returning  `{'error': 'Unknown error'}` for both CPU and GPU inference.

## To reproduce

headers = {"Authorization": f"Bearer {BEARER}"}
API_URL = "https://api-inference.huggingface.co/models/gpt2"
data = json.dumps({"inputs": 'Here is a sentence that I like', "parameters":{"num_return_sequences":1,  "max_length":1},"options": {"wait_for_model": False, "use_cache": False, "use_gpu":False}})
response = requests.request("POST", API_URL, headers=headers, data=data)
test_output = json.loads(response.content.decode("utf-8"))

## Expected behavior

Returns the generated completion by gpt2

**Comment by Narsil** [comment]
```python
import json
import os

API_TOKEN = os.getenv("API_TOKEN")

import requests

headers = {"Authorization": f"Bearer {API_TOKEN}"}
API_URL = "https://api-inference.huggingface.co/models/gpt2"


def query(payload):
    data = json.dumps(payload)
    response = requests.request("POST", API_URL, headers=headers, data=data)
    return json.loads(response.content.decode("utf-8"))


data = query(
    {
        "inputs": "The answer to the universe is",
        "parameters": {"num_return_sequences": 1, "max_length": 1},
        "options": {"wait_for_model": False, "use_cache": False, "use_gpu": False},
    }
)

print(data)
```

This seems to work currently. Are you sure about your Bearer ? (It shouldn't produce `unknown error` anyway, but I fail to see what's wrong in your code).
Can you share a little your environmnet too ? (Python version, requests version)
