### ISSUE TITLE
LayoutLMv2Model can not be imported from transformers

### ISSUE THREAD

**Issue by MustafaYagmur-v39300** [huggingface/transformers#15654]
Hi @NielsRogge 

Getting error when calling LayoutLMv2Model class with `from transformers import LayoutLMv2Model` as instructed at the [official documentation](https://huggingface.co/docs/transformers/model_doc/layoutxlm)

`ImportError: cannot import name 'LayoutLMv2Model' from transformers (unknown location)`

It should be under **transformers/models/layoutlmv2/modeling_layoutlmv2.py**

I have `transformers` version: 4.5.1:

**Comment by MustafaYagmur-v39300** [comment]
The issue has been resolved. LayoutLMv2Model class exist in `transformers=4.16.2` version

**Comment by OmarMohammed88** [comment]
what about installing from the source 

```!git clone https://github.com/huggingface/transformers.git
%cd transformers
!pip install -e .```
i tried to run run_mlm.py but got many errors in importing the modules
