### ISSUE TITLE
How to add the output word vector of bert to my model

### ISSUE THREAD

**Issue by vvain** [huggingface/transformers#1565]
## ❓ Questions & Help
Hello, I am a student who is learning nlp. 
Now I want to use the word vector output by bert to apply to my model, but **I can't connect the word vector to the network**. Could you give me an example program or tutorial about this which use textCNN or LSTM. You can sent e-mail to **vvain0208@163.com** or reply me, please.
Thank you for your kind cooperation!

**Comment by TheEdoardo93** [comment]
I think you can see [here](https://jalammar.github.io/a-visual-guide-to-using-bert-for-the-first-time/). In more details, this tutorial uses **BERT** as **feature extractor** and on-top they have used a **Logistic Regression** model from [Scikit-learn](https://scikit-learn.org/stable/) for the **sentiment analysis** task. 

Question: which is the problem in details? Are you not able to connect the feature vector extracted by BERT to a custom classifier on-top? Is the shape of the feature vector fixed?

> ##  Questions & Help
> Hello, I am a student who is learning nlp.
> Now I want to use the word vector output by bert to apply to my model, but **I can't connect the word vector to the network**. Could you give me an example program or tutorial about this which use textCNN or LSTM. You can sent e-mail to **[vvain0208@163.com](mailto:vvain0208@163.com)** or reply me, please.
> Thank you for your kind cooperation!
