### ISSUE TITLE
error load bert model ：not found model file

### ISSUE THREAD

**Issue by iambyd** [huggingface/transformers#1566]
Error content:
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory ./uncased_L-12_H-768_A-12_transformers or `from_tf` set to False
but file exists
![image](https://user-images.githubusercontent.com/11927058/67140873-4d259880-f291-11e9-8e27-25ae7fb661f7.png)

**Comment by iedmrc** [comment]
I don't understand when you get this error?

**Comment by TheEdoardo93** [comment]
In order to understand when you've encountered this bug, as suggested by @iedmrc , you've to write down the source code that generates the bug! And please show your environment (Python, Transformers, PyTorch, TensorFlow versions) too! 

> Error content:
> OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory ./uncased_L-12_H-768_A-12_transformers or `from_tf` set to False
> but file exists
> ![image](https://user-images.githubusercontent.com/11927058/67140873-4d259880-f291-11e9-8e27-25ae7fb661f7.png)

**Comment by danyaljj** [comment]
I got the same error when loading a TF BERT model: 
```
dir = "/Users/danielk/ideaProjects/farsi-language-models/src/models/perbert_L-12_H-768_A-12/"
tokenizer = BertTokenizer.from_pretrained(dir)
config = BertConfig.from_json_file(dir + '/bert_config.json')
model = TFBertForMaskedLM.from_pretrained(dir, config=config)
```
The error happens in the last line.
