### ISSUE TITLE
Incorrect information in "Getting started" regarding API tokens

### ISSUE THREAD

**Issue by ToonTalk** [huggingface/transformers#15693]
https://api-inference.huggingface.co/docs/curl/html/quicktour.html#get-your-api-token states

You should see a token api_XXXXXXXX or api_org_XXXXXXX.

But the keys start with hf_

Also https://huggingface.co/docs/hub/security#user-access-tokens describes the read and write tokens without mention of API tokens

**Comment by Narsil** [comment]
The `hf_` tokens will work. 

Will update the doc which is out of date (well the old tokenizer `api_` `api_org` still work, we just don't generate new ones anymore).

**Comment by Narsil** [comment]
Updated ! closing this issue, feel free to reopen.
