### ISSUE TITLE
Trainer can't estimate SpeechEncoderDecoder tokens for `floating_point_ops`

### ISSUE THREAD

**Issue by OllieBroadhurst** [huggingface/transformers#15715]
## Environment info

- `transformers` version: 4.16.2
- Platform: Ubuntu
- Python version: 3.7
- PyTorch version (GPU?): 1.9
- Tensorflow version (GPU?): NA
- Using GPU in script?: Y
- Using distributed or parallel set-up in script?: N

### Who can help
Maybe @sgugger?

## Information

Model I am using (Bert, XLNet ...): SpeechEncoderDecoder

Training the model results in `Could not estimate the number of tokens of the input, floating-point operations will not be computed` warnings due to [this function](https://github.com/huggingface/transformers/blob/240cc6cbdc07fc1a7c103d71cfe38d5e60e489e4/src/transformers/modeling_utils.py#L378) being unable to find the correct `self.main_input_name`. For `SpeechEncoderDecoderModel`s, the default name is [`inputs` ](https://github.com/huggingface/transformers/blob/v4.16.2/src/transformers/models/speech_encoder_decoder/modeling_speech_encoder_decoder.py#L183) even though the encoder should either accept `input_values` or `input_features`. The function expects `inputs` to be in the `input_dict` but could only find the main input name of the encoder.

## To reproduce

1. Train a `SpeechEncoderDecoderModel` using the `Seq2SeqTrainer` and monitor console output.

## Expected behavior

The function should be able to determine the correct `main_input_name` of a `SpeechEncoderDecoderModel`. Presumably that of the encoder. I'm not sure if this applies to `VisionEncoderDecoderModel`s but I suspect it would.

**Comment by sgugger** [comment]
I don't think this can be solved since the model input name is not always the same. You can just ignore the warning.
