### ISSUE TITLE
Drop support for Python 3.6

### ISSUE THREAD

**Issue by cdeepali** [huggingface/transformers#15720]
Drop support for Python 3.6 as it is EOL

**Comment by henk717** [comment]
Why deliberately drop support? If people are stuck on 3.6 for whatever reason it will be nice for them to be able to use it as long as it lasts.

**Comment by cdeepali** [comment]
Python 3.6 is EOL now.  Do we still want to retain support for it?

**Comment by function2-llx** [comment]
> Why deliberately drop support? If people are stuck on 3.6 for whatever reason it will be nice for them to be able to use it as long as it lasts.

But this will also make the development & maintenance of the library harder. Many libraries drop support for Python 3.6.

**Comment by LysandreJik** [comment]
Thanks for your request! As long as there isn't a very impactful feature missing or compatibility issue with our current setup, we're unlikely to drop support for Python 3.6 just yet as we aim for maximum compatibility across versions.

**Comment by cdeepali** [comment]
Thanks @LysandreJik for your reply on this.

**Comment by LysandreJik** [comment]
Python 3.6 will be dropped over the next few weeks: https://github.com/huggingface/transformers/issues/16832

**Comment by LysandreJik** [comment]
This has been addressed.
