### ISSUE TITLE
Can I training an XLM model from scratch by transformers?

### ISSUE THREAD

**Issue by thomas-li-sjtu** [huggingface/transformers#15738]
How can I pretain XLM by transformers? Any example? Please.

**Comment by jaketae** [comment]
Hey @thomas-li-sjtu, you definitely can. I recommend that you check out [this HF blog post](https://huggingface.co/blog/how-to-train). Although the article doesn't use XLM, the process should roughly look the same.

Also, a gentle reminder to use the [discussion forum](https://discuss.huggingface.co) for inquiries. GitHub Issues is used for bug reports and feature requests!
