### ISSUE TITLE
Add support to export Blenderbot models to onnx

### ISSUE THREAD

**Issue by Darth-Carrotpie** [huggingface/transformers#15757]
# 🚀 Feature request
Add support to export Blenderbot models to onnx. Please! Or help guide towards a correct direction!

## Motivation
There is someone working to implement Blenderbot 2.0 into transformers [12807](https://github.com/huggingface/transformers/issues/12807#issuecomment-1039315898), yet we still do not have a proper 1.0 export to onnx. 

### Error with torch.onnx.export
Tried to export Blenderbot 1.0 model via ```torch.onnx.export(model, input_values, output_path)``` and it failed with an error:
```ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds```
I've seen issues like this around with seq2seq models being encoder and decoder at the same time, thus needing to somehow export to models. Seems that onnx export of Bart model being of similar type has been properly implemeneted, as there's an onnx [config object](https://github.com/huggingface/transformers/blob/master/src/transformers/models/bart/configuration_bart.py).

### Weird outcome with transformers.onnx.export
Next thing I tried was to follow T5 model export implementation using Bart config as an example. I am not experienced enough in this, so obviously I stumbled onto a weird outcome which I cannot grasp / google out what's happening and why. I created a ```BlenderbotOnnxConfig(OnnxSeq2SeqConfigWithPast)``` class using simply same properties as in ```BartOnnxConfig(OnnxSeq2SeqConfigWithPast)```.
It then succesfully save files to a designated directory, but there's hundreds of them!!! Seems as if each layer is exported with its bias files separate...
When trying to do ```onnx.load``` console cries out the error about ```final_logits_bias``` file being missing. After digging into it, seems this file is in mentioned in a variable ```_keys_to_ignore_on_load_missing```, but still seems getting included. Not sure what I missed and where to go on from, therefore writing this issue for help / support.

### Notebook
You can [see the notebook](https://www.kaggle.com/danieliusv/blenderbot1-0-test-and-export) with my unsuccessful tries.

**Comment by patil-suraj** [comment]
>**Motivation**
There is someone working to implement Blenderbot 2.0 into transformers https://github.com/huggingface/transformers/issues/12807#issuecomment-1039315898, yet we still do not have a proper 1.0 export to onnx.

Nice motivation! More seriously though, note that onnx support is optional and is not a core feature. There will always be some models that don't have onnx support and we usually tend to add it only when some users request it.

Also pinging our onnx expert @lewtun :)

**Comment by Darth-Carrotpie** [comment]
Sorry, didn't really know what to write in the *Motivation* section... uh.. "we need it for a project"? ¯\_(ツ)_/¯

**Comment by lewtun** [comment]
Hey @Darth-Carrotpie thanks for raising this issue and sharing a solid first stab at the export! I'll take a look at this later in the week and see what the problem is :)

**Comment by lewtun** [comment]
Re-open this issue
