### ISSUE TITLE
Docstring says target_sizes is optional (in DETR post_process) but the code disagrees

### ISSUE THREAD

**Issue by amgreene** [huggingface/transformers#15769]
https://github.com/huggingface/transformers/blob/db7d6a80e82d66127b2a44b6e3382969fdc8b207/src/transformers/models/detr/feature_extraction_detr.py#L677

The Docstring marks the `target_sizes` parameter as `*optional*` but the parameter has no default value and is used without any conditional checking for whether it is `None`, so it would seem to be required.

**Comment by ankitsharma07** [comment]
Is this resolved?

**Comment by Manobal-Singh-Bagady** [comment]
This issue should be marked closed. The problem seems to be resolved.

**Comment by NielsRogge** [comment]
We're actually updating this at the moment (see #19262), it will become optional. Closing this issue for now.
