### ISSUE TITLE
distilled gpt2 to be added to run_generation and run_lm_fintuning

### ISSUE THREAD

**Issue by juliahane** [huggingface/transformers#1578]
Hi
I greatly appreciated also adding distilled GPT2 to the codes above, thanks

**Comment by LysandreJik** [comment]
Hi, DistilGPT-2 is considered to be a checkpoint of GPT-2 in our library (differently to DistilBERT). You can already use DistilGPT-2 for both of these scripts with the following:
```bash
python run_generation --model_type=gpt2 --model_name_or_path=distilgpt2
```
