### ISSUE TITLE
seq2seq with gpt2

### ISSUE THREAD

**Issue by juliahane** [huggingface/transformers#1579]
Hi,
I want to have a seq2seq model from gpt2, if I change the script of "run_lm_finetuning.py" in a way that it gets a sequence, then make it a context ids, and let it generate another sequence, like "run_generation.py" code, then minimize the cross-entropy loss, does it this way, create a seq2seq model? I rgreatly appreciate your help. thanks a lot.

**Comment by thomwolf** [comment]
Merging with #1506
