### ISSUE TITLE
run_glue_no_trainer.py

### ISSUE THREAD

**Issue by backurs** [huggingface/transformers#15801]
Line 428 in "text-classification/run_glue_no_trainer.py":

if step % args.gradient_accumulation_steps == 0 or step == len(train_dataloader) - 1:

replace it with:

if (step + 1) % args.gradient_accumulation_steps == 0 or step == len(train_dataloader) - 1:

**Comment by gante** [comment]
Hi @backurs -- would you like to open a PR with the change? :)

**Comment by backurs** [comment]
Hi Joao,
I get this error when trying to push my branch to the origin:
[image: image.png]
How do I fix this problem?
Thanks,
Arturs

**Comment by gante** [comment]
Hi @backurs  -- there was a problem with the image attachment (possibly because your comment was an email reply). Can you resubmit it through a GitHub comment, please?
