### ISSUE TITLE
Absence

### ISSUE THREAD

**Issue by hgeorgescu** [huggingface/transformers#15827]
## Environment info

- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by hgeorgescu** [comment]
model_name = "Helsinki-NLP/opus-mt-en-roa"
tokenizer = MarianTokenizer.from_pretrained(model_name)
 Error:"TypeError: 'NoneType' object is not callable"

**Comment by patil-suraj** [comment]
`MarianTokenizer` depends on `sentencepiece`. Make sure to install it before importing the tokenizer.
`pip install sentencepiece` should resolve this.
