### ISSUE TITLE
Output embedding from each self-attention head from each encoder layer

### ISSUE THREAD

**Issue by Sreyan88** [huggingface/transformers#15842]
Hi there!

I wanted the embeddings from each self-attention head of each encoder layer for one of my projects, is this possible with the hugging face library?

If not, can I just slice the original embeddings from each layer (suppose 768/12 = 128 size slice) to get the attention head output?

Thank You

**Comment by patil-suraj** [comment]
Hi @Sreyan88 ! The best place to ask this question is [the forum](https://discuss.huggingface.co/). We use issues for bug reports and feature requests. Thank you!
