### ISSUE TITLE
Missing tags on Docker Hub after version 4.9.1

### ISSUE THREAD

**Issue by AdrienDS** [huggingface/transformers#15899]
## Environment info

- `transformers` version: > 4.9.1

### Who can help

@mfuntowicz ?

## Information

https://hub.docker.com/r/huggingface/transformers-pytorch-gpu/tags

I was expecting 1 tag per transformers version on the docker hub, but the most recent tag (aside from `latest`) is for 4.9.1 and was pushed on July 26, 2021.

## To reproduce

Steps to reproduce the behavior (and see existing tags):

1. Either visit https://hub.docker.com/r/huggingface/transformers-pytorch-gpu/tags and sort by Newest
2. Or run `wget -q https://registry.hub.docker.com/v1/repositories/huggingface/transformers-pytorch-gpu/tags -O - | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}'`

Current tags available:

```
latest
2.10.0
2.11.0
2.6.0
2.7.0
2.8.0
2.9.0
2.9.1
3.0.0
3.0.1
3.0.2
3.1.0
3.2.0
3.3.0
3.3.1
3.4.0
3.5.0
3.5.1
4
4.0.0
4.0.1
4.1.0
4.1.1
4.2.0
4.2.1
4.2.2
4.3.0
4.3.1
4.3.2
4.3.3
4.4.0
4.4.1
4.4.2
4.5.0
4.5.1
4.6.1
4.7.0
4.8.0
4.8.1
4.8.2
4.9.0
4.9.1
````

## Expected behavior

Each time a image is pushed with the `latest` tag, it could also be tagged with the current version number, like it was before version 4.9.1. (I was expecting to see 4.16.2 for example)

**Comment by julien-c** [comment]
cc'ing @mfuntowicz (among others)

**Comment by LysandreJik** [comment]
Hey! We indeed stopped pushing images a while back, but we've started doing so again a few weeks ago. It makes sense to push images with the versions.

Will try to make some time and do so.
