### ISSUE TITLE
Tranformers documentation translation to Spanish

### ISSUE THREAD

**Issue by omarespejel** [huggingface/transformers#15947]
Hi!

Let's bring the documentation to all the Spanish-speaking community :)

Who would want to translate? **Please follow the instructions in the [Translating guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md)**. Here is a list of the files ready for translation. Let us know here if you'd like to translate any and we'll add your name to the list.

Some notes:
- Please translate using an informal tone (imagine you are talking with a friend about `transformers` 🤗). For example, use `Tú` instead of `Usted`; or `colabora` instead of `colabore`.
- Please translate in a gender-neutral way. For example, instead of "Nosotros podemos" it could be "Podemos"; or "Los que quieran" could be "Las personas que quieran."
- Add your translations to the folder called `es` inside the [`source` folder](https://github.com/huggingface/transformers/tree/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source).
- Register your translation in [es/_toctree.yml](https://github.com/huggingface/transformers/blob/main/docs/source/es/_toctree.yml); please follow the order of the [English version](https://github.com/huggingface/transformers/blob/main/docs/source/en/_toctree.yml).
- Once you're finished, open a pull request and tag this issue by including `#issue-number` in the description, where `issue-number` is the number of this issue.
- 🙋 If you'd like others to help you with the translation, you can also post in our [forums](https://discuss.huggingface.co/) or tag [@osanseviero](https://twitter.com/osanseviero) on Twitter to gain some visibility.

### Get Started section
- [x] [quicktour.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/quicktour.mdx). @Duedme 
- [x] [installation.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/installation.mdx). @lilianabs

### Tutorial section
- [x] [pipeline_tutorial.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/pipeline_tutorial.mdx) @FernandoLpz
- [x] [autoclass_tutorial.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/autoclass_tutorial.mdx) @Duedme
- [x] [preprocessing.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/preprocessing.mdx) @yharyarias 
- [x] [training.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/training.mdx) @yharyarias 
- [x] [accelerate.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/accelerate.mdx) @Sangohe
- [x] [model_sharing.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/model_sharing.mdx) @Gerard-170
- [x] [multilingual.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/multilingual.mdx) @SimplyJuanjo

## How-to guides
- [x] [fast_tokenizers.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/fast_tokenizers.mdx "fast_tokenizers.mdx") @jloayza10
- [x] [create_a_model.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/create_a_model.mdx "create_a_model.mdx") @ignacioct
- [x] [custom_models.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/custom_models.mdx "custom_models.mdx") @donelianc
- [x] [run_scripts.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/run_scripts.mdx "run_scripts.mdx") WIP @donelianc
- [x] [sagemaker.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/sagemaker.mdx "sagemaker.mdx") @SimplyJuanjo
- [x] [converting_tensorflow_models.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/converting_tensorflow_models.mdx "converting_tensorflow_models.mdx") @donelianc
- [ ] [serialization.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/serialization.mdx "serialization.mdx")
- [ ] [performance.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/performance.mdx "performance.mdx")
- [ ] [parallelism.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/parallelism.mdx "parallelism.mdx") WIP @astrocronopio
- [ ] [benchmarks.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/benchmarks.mdx "benchmarks.mdx")
- [ ] [migration.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/migration.mdx "migration.mdx")
- [ ] [troubleshooting.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/troubleshooting.mdx "troubleshooting.mdx")
- [ ] [debugging.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/debugging.mdx "debugging.mdx") WIP @SimplyJuanjo
- [ ] [community.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/community.mdx "community.mdx")
- [ ] [add_new_model.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/add_new_model.mdx "docs/source/en/add_new_model.mdx")
- [ ] [add_new_pipeline.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/add_new_pipeline.mdx "add_new_pipeline.mdx")
- [ ] [testing.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/testing.mdx "testing.mdx")
- [ ] [pr_checks.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/pr_checks.mdx "pr_checks.mdx")

## FINE-TUNE FOR DOWNSTREAM TASKS
- [ ] [sequence_classification.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/sequence_classification.mdx "sequence_classification.mdx")
- [ ] [token_classification.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/token_classification.mdx "token_classification.mdx") WIP @gpalomeque
- [ ] [question_answering.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/question_answering.mdx "question_answering.mdx")
- [x] [language_modeling.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/language_modeling.mdx "language_modeling.mdx") @jQuinRivero
- [ ] [translation.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/translation.mdx "translation.mdx")
- [x] [summarization.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/summarization.mdx "summarization.mdx") @AguilaCudicio
- [ ] [audio_classification.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/audio_classification.mdx "audio_classification.mdx")
- [ ] [asr.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/asr.mdx "asr.mdx")
-  [x] [image_classification.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/image_classification.mdx "image_classification.mdx") @SimplyJuanjo
- [ ] [multiple_choice.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/multiple_choice.mdx "multiple_choice.mdx")

## CONCEPTUAL GUIDES
- [x] [philosophy.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/philosophy.mdx "philosophy.mdx") @[jkmg](https://github.com/jkmg)
- [ ] [glossary.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/glossary.mdx "glossary.mdx")
- [ ] [pad_truncation.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/pad_truncation.mdx "docs/source/en/pad_truncation.mdx")
- [x] [bertology.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/bertology.mdx "bertology.mdx") @jQuinRivero
- [ ] [perplexity.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/perplexity.mdx "perplexity.mdx")

FYI @osanseviero @stevhliu @sgugger @mishig25

**Comment by Duedme** [comment]
Hi, I can do the translation of **quicktour.mdx** in two days at the latest.

**Comment by yharyarias** [comment]
I'll translate "Fine-tune a pretrained model" into Spanish to file [training.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/training.mdx).

**Comment by omarespejel** [comment]
Thanks, @Duedme and @yharyarias! That would be great. Please let me know anything you need.

**Comment by FernandoLpz** [comment]
Hi, I can translate [pipeline_tutorial.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/pipeline_tutorial.mdx) 🙂

**Comment by Sangohe** [comment]
Hi, I would like to do the translation for [accelerate.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/accelerate.mdx)

**Comment by Gerard-170** [comment]
Hi, I will work on [model_sharing.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/model_sharing.mdx) :D

**Comment by osanseviero** [comment]
Hey all! I updated the initial comment cc'ing the WIP translations. When you create a PR, please make sure to tag this issue by adding #15947 to it.

**Comment by lilianabs** [comment]
Hi, I can work on [installation.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/installation.mdx) :D

**Comment by yharyarias** [comment]
Hi, I would like to translate [preprocessing.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/preprocessing.mdx)

**Comment by Duedme** [comment]
I made this Pull-Request #16158 to translate quicktour.mdx. I would like to work on **autoclass_tutorial.mdx**.

**Comment by SimplyJuanjo** [comment]
I new in the community but I'll like to translate [multilingual.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/multilingual.mdx)
I'm finishing my Udacity Deep Learning Nanodegree this week, therefore I can do the translation next monday if that's okey.

**Comment by omarespejel** [comment]
Thanks, @SimplyJuanjo! Welcome to the HF community and congrats on the Nanodegree 🤗. Sure, next week is perfect!

**Comment by SimplyJuanjo** [comment]
I made this pull request https://github.com/huggingface/transformers/pull/16329 to translate multilingual.mdx. Is everything done the right way?
@omarespejel @osanseviero

**Comment by SimplyJuanjo** [comment]
Hey, I would like to translate sagemaker.mdx

**Comment by omarespejel** [comment]
Thanks, @jloayza10 @SimplyJuanjo @jkmg! I just added your names to those files 🤗. Please let me know anything you need.

**Comment by ignacioct** [comment]
Hi! I would like to translate [create_a_model.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/create_a_model.mdx), if it's still available

**Comment by jQuinRivero** [comment]
Hey! I would like to translate language_modeling.mdx.

**Comment by omarespejel** [comment]
Thank you @ignacioct and @jQuinRivero! I added your names to those files above. Will be reviewing your PRs.

**Comment by astrocronopio** [comment]
Hi! I would like to translate [parallelism.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/parallelism.mdx). Do I translate English words on images as well?

**Comment by jQuinRivero** [comment]
Hi, @omarespejel

I would like to translate bertology.mdx next!

**Comment by omarespejel** [comment]
Gracias @jQuinRivero y @astrocronopio! I added you in the main comment to the file you will translate 🤗

**Comment by SimplyJuanjo** [comment]
Sorry for the delay, I've been settling into a new position as a junior AI programmer this month.

I made this pull request https://github.com/huggingface/transformers/pull/17262 to translate sagemaker.mdx. Should I also translate the documentations mentioned in the table of contents of this documentation?
@omarespejel @osanseviero @sgugger 

Additionally, I would like to translate [image_classification.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/image_classification.mdx) if possible.

**Comment by omarespejel** [comment]
Congrats on the new position and we wish you a lot of success in it, @SimplyJuanjo! 🤗

No, for the moment it is not required to translate the documentation mentioned in `sagemaker.mdx`. Thanks for noting that!

Thank you! I will tag you for `image_classfication.mdx` 🚀

**Comment by SimplyJuanjo** [comment]
Thx @omarespejel! 🤗

Already added the `image_classification.mdx` to my PR.

I would like to translate now `debbuging.mdx` if possible.

**Comment by omarespejel** [comment]
@SimplyJuanjo thank you for your PR. I am checking it. 

Sure! You can start `debugging.mdx`, that would be great! Thank you. I will add your name to the checklist above.

**Comment by gpalomeque** [comment]
Hola, me gustaría contribuir traduciendo token_classification.mdx

**Comment by omarespejel** [comment]
Hola @gpalomeque! Thank you very much! That would be great. Let me add you to the list.

**Comment by donelianc** [comment]
Hola @omarespejel, I'd like to help with translating _custom_models.mdx_.

**Comment by osanseviero** [comment]
Sounds good! Feel free to open a PR @donelianc

**Comment by gpalomeque** [comment]
Hola envié el pull request 17992. Veo que aun esta disponible la tarea question_answering.mdx y me gustaría realizar la traducción correspondiente. Saludos.

**Comment by omarespejel** [comment]
Hola @gpalomeque! Muchas gracias por tu traducción de `token_classification.mdx` #17992. Coloqué algunos comentarios.

Sorry for my late reply and review. Are you still interested in translating `question_answering.mdx`?

**Comment by omarespejel** [comment]
Hi @donelianc! I assigned you to `run_scripts` as you mentioned in your previous PR! Thanks! :)

**Comment by AguilaCudicio** [comment]
Hola. Me gustaria traducir benchmarks.mdx

**Comment by AguilaCudicio** [comment]
Hi, I'd like to translate summarization.mdx  @omarespejel

**Comment by omarespejel** [comment]
Hi @AguilaCudicio! That would be amazing. Thanks I added you to the list :)

**Comment by alceballosa** [comment]
Hi all, I'd like to translate question_answering.mdx and multiple_choice.mdx :) @omarespejel

**Comment by osanseviero** [comment]
Feel free to open a PR @alceballosa :)

**Comment by donelianc** [comment]
Hey 🤗 team! I noticed this task being inactive for some days now. 

I'll try to keep working on it, but updating the task checklist for the latest contributions would be helpful to avoid duplications.

I'll translate [serialization.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/serialization.mdx) and submit a PR when it's ready.

**Comment by KarmaTashiCat** [comment]
Hi all! I'd like to contribute with [performance.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/performance.mdx) spanish translation. Could it be assigned to me first please?

**Comment by donelianc** [comment]
Hi folks, I'd like to translate the [pr_checks.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/pr_checks.mdx) doc. I'll submit a PR when ready.

**Comment by alceballosa** [comment]
Hi all, I'd like to translate [asr.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/asr.mdx).

**Comment by shogohida** [comment]
Hi all! I would like to translate [community.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/community.mdx).

I'll make a pull request when the translation is ready! I'm not a native speaker of Spanish (I'm Japanese) but I'll do my best with the skills I earned working in Guatemala for 2 years :)

**Comment by osanseviero** [comment]
Hey all! As some people were interested in a place to discuss about translations, we opened a category in the [HF Discord server](hf.co/join/discord) with a category for internationalization and translation efforts, including a Spanish channel!
