### ISSUE TITLE
Unable to run run_glue.py offline

### ISSUE THREAD

**Issue by Nithanaroy** [huggingface/transformers#15945]
## Environment info
An host without internet access but with ~/.cache/huggingface pre-populated

### Who can help
@sgugger @LysandreJik @SaulLu 

## Information

Model I am using (Bert, XLNet ...): 
```
--model_name_or_path bert-base-uncased --task_name mrpc --do_train --output_dir /home/jobuser/output_bart_test --per_device_train_batch_size 16 --do_eval --do_predict --per_device_eval_batch_size 8 --overwrite_output_dir --cache_dir /home/jobuser/hf_cache
```

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce
1. Run https://github.com/huggingface/transformers/blob/master/examples/tensorflow/text-classification/run_glue.py with internet using
```
--model_name_or_path bert-base-uncased --task_name mrpc --do_train --output_dir /home/jobuser/output_bart_test --per_device_train_batch_size 16 --do_eval --do_predict --per_device_eval_batch_size 8 --overwrite_output_dir --cache_dir /home/jobuser/hf_cache
```
2. Run the same command without internet (literally disconnect the wire / wifi)
3. It fails at https://github.com/huggingface/transformers/blob/master/examples/tensorflow/text-classification/run_glue.py#L282

## Expected behavior
It should leverage the existing caches and train without breaking

**Comment by sgugger** [comment]
You need to set the env variable `HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1` to be able to use the libraries in offline mode, as pointed out in the [documentation](https://huggingface.co/docs/transformers/installation#offline-mode)

**Comment by Nithanaroy** [comment]
@sgugger thanks for the blazing fast response! I forgot to add that I set `HF_DATASETS_OFFLINE=1`. I didnt know about `TRANSFORMERS_OFFLINE=1`. It works now.
