### ISSUE TITLE
Make benchmark more flexible (TF or PT)

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#1594]
I've been trying to run the benchmark, but I gave up after running into a trillion compatibility issues with tensorflow and bazel. To be fair, I just want to contribute and test all there is to test on PyTorch with 4x Tesla V100. It would be great if only the required modules are needed, and not all of them. So only try to import PyTorch or Tensorflow when the tester actually wants to test those frameworks.

**Comment by tlkh** [comment]
I believe a quick workaround is to just install the pre-built, CPU version of TensorFlow 2.0. If you won't be running the TF benchmarks, it wouldn't affect anything.

**Comment by BramVanroy** [comment]
True, but still not quite flexible. Since the goal of the benchmark script is to, I believe, encourage the community to add there runtimes, it's a good to make this as easy-to-use as possible.

**Comment by LysandreJik** [comment]
You're right that we shouldn't require to have both libraries installed in order to benchmark only one of them. I've updated the Benchmark code so that you can run it with only a single library installed.

**Comment by BramVanroy** [comment]
That's great, Lysandre. Thanks for pushing out changes so quickly!
