### ISSUE TITLE
Blenderbot 1.0B Distilled eats up memory over many inferences

### ISSUE THREAD

**Issue by alu13** [huggingface/transformers#15958]
Hi, I've noticed that over the course of many inferences, the  Blenderbot 1.0B Distilled model continuously allocates GPU memory and eventually causes the GPU to crash. My project only uses single-turn inferences, and I was wondering how to prevent Blenderbot from continuously allocating memory. Thanks
<img width="1209" alt="Screen Shot 2022-03-06 at 11 27 45 PM" src="https://user-images.githubusercontent.com/12601917/156968067-425cf072-a182-4f85-87f7-64517ef2b93b.png">
!

**Comment by patil-suraj** [comment]
It's hard to say anything without looking at the code. Also for such general question, [forum](https://discuss.huggingface.co/) would be the best place to ask. Thank you!

**Comment by alu13** [comment]
Hi, thank you! I'll definitely post in the forum. 

My code is below. It's just basic generation (with somewhat high volume). Thanks!
<img width="1244" alt="Screen Shot 2022-03-07 at 4 21 31 PM" src="https://user-images.githubusercontent.com/12601917/157120053-fa9b94dd-2931-4c03-9c8a-4bc747bebba0.png">
