### ISSUE TITLE
_tokenize() got an unexpected keyword argument 'add_prefix_space' in CTRL

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#1597]
## 🐛 Bug

If you look at [the search results in this repo](https://github.com/huggingface/transformers/search?q=add_prefix_space) for `add_prefix_space`, you'll find gpt2, roberta, and ctrl all document that 

> `add_prefix_space`: Requires a space to start the input string => the encoding methods should be called with the --``add_prefix_space`` flag set to ``True``.

However, this attribute is only implemented in the GPT2Tokenizer. Since RobertaTokenizer subclasses GPT2Tokenizer, that is fine. However, CTRLTokenizer just subclasses the PretrainedTokenizer. As such, it does not have a `_tokenize()` method that accepts the `add_prefix_space` keyword. 

I would fix this in a PR, but I am not sure what the actual correct fix is: does CTRL need the added space, or not? And can it subclass GPT2's tokenizer, or should it implement its own `_tokenize(*, add_prefix_space)` method?

**Comment by LysandreJik** [comment]
Hi @BramVanroy, thanks for reporting this. There was an issue in the docstring. It does not use prefix spaces and it does not use a byte-level BPE like GPT-2 does. The docstring should be fixed now.
