### ISSUE TITLE
Add custom classifcation dataset - computer vision

### ISSUE THREAD

**Issue by INF800** [huggingface/transformers#15978]
Hi, I recently read your amazing blog https://huggingface.co/blog/fine-tune-vit

There I could not find any reference to how to create our own dataset. Is there any class helper that we can use? Something like -

```python
from xyz import ImageClassificationDataset

dataset = ImageClassificationDataset.from_directory('/path/to/dataset')
```

For directory structured as

```
train
  +- class0
  +- class1
  ...
  +- classn
valid
  +- class0
  +- class1
  ...
  +- classn
test
  +- class0
  +- class1
  ...
  +- classn
```
where every class folder has images

**Comment by INF800** [comment]
Or, If you don't have that kind of class what would be the best way to generate dataset dict
```python
DatasetDict({
    train: Dataset({
        features: ['image_file_path', 'image', 'labels'],
        num_rows: 1034
    })
    validation: Dataset({
        features: ['image_file_path', 'image', 'labels'],
        num_rows: 133
    })
    test: Dataset({
        features: ['image_file_path', 'image', 'labels'],
        num_rows: 128
    })
})
```

**Comment by NielsRogge** [comment]
Hi,

We've just added the [ImageFolder](https://huggingface.co/docs/datasets/master/en/loading#image-folders) to the Datasets library :)

This way, you can easily load your custom data as follows:

```
from datasets import load_dataset

dataset = load_dataset("imagefolder", data_dir="/path/to/data")
```
