### ISSUE TITLE
PerceiverAudioPreprocessor: forward() missing 1 required positional argument: 'pos'

### ISSUE THREAD

**Issue by basilevh** [huggingface/transformers#15971]
The [`forward()` method implementation of `PerceiverAudioPreprocessor`](https://github.com/huggingface/transformers/blob/38cc35069c10d153e872162265288263bb7394b7/src/transformers/models/perceiver/modeling_perceiver.py#L3267) seems to be problematic because it has an extra required `pos` argument, whereas all other preprocessors do not (or it is optional). In fact, while it is passed to `_build_network_inputs()`, `pos` is not actually used in that method. Hence, I am not sure why it exists. Moreover, it breaks the default `PerceiverModel` operation, because that class assumes that there only one positional argument called `inputs` [when calling the preprocessor](https://github.com/huggingface/transformers/blob/38cc35069c10d153e872162265288263bb7394b7/src/transformers/models/perceiver/modeling_perceiver.py#L865). This seems to be a serious issue in my opinion because it crashes any instantiation of `PerceiverModel` with a `PerceiverAudioPreprocessor` as `input_preprocessor`.

**Comment by NielsRogge** [comment]
Hi,

Thanks for raising this issue. This was a leftover from porting Deepmind's original repo. However, as I'm implementing the position embeddings differently in PyTorch (vs. the original implementation which was in Haiku), this can probably be deleted. I'll work on a PR to remove it everywhere.

**Comment by NielsRogge** [comment]
Reopening this and marking it as a good first issue.

**Comment by daspartho** [comment]
Is this issue open? I'd love to take it on.
