### ISSUE TITLE
FeaturesManager assumes only one of Torch or TensorFlow is installed

### ISSUE THREAD

**Issue by ndronen** [huggingface/transformers#15990]
## Environment info

- `transformers` version: 4.12.5
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.9.10
- PyTorch version (GPU?): 1.10.0 (False)
- Tensorflow version (GPU?): 2.8.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

@michaelbenayoun @Albertobegue 

## Information

When both Torch and TensorFlow are installed, `FeaturesManager` defaults to using `AutoModel`, so the model returned by `get_model_from_feature` is always Torch.

## To reproduce

1. Install Torch and TF
2. Call `FeatureManager.get_model_from_feature` with arbitrary but supported `features` and `model_name` arguments
3. The resulting model is always a Torch model

```python
features = "default" # randomly chosen, supported feature
model_name = "bert" # randomly chosen, supported model
model = FeaturesManager.get_model_from_feature(features, model_name)
```

## Expected behavior

Some test environments have both Torch and TensorFlow installed, because the immediate task is to ensure functionality is the same regardless of the framework. I would expect `FeaturesManager.get_model_from_feature` to allow TensorFlow to be used even when Torch is installed. This could be implemented by e.g. a keyword argument to `get_model_from_feature` with a default value of `None`. When the keyword argument is `None`, and both Torch and TensorFlow are installed, `FeatureManager` would default to Torch, as it does now. Otherwise, it would use the specified framework.

**Comment by patil-suraj** [comment]
Also cc @lewtun

**Comment by michaelbenayoun** [comment]
I'm on it!

**Comment by ndronen** [comment]
> I'm on it!

Thanks!
