### ISSUE TITLE
resize_token_embeddings() failed with GPT-J, after sync to the latest DeepSpeed 0.6.1

### ISSUE THREAD

**Issue by dunalduck0** [huggingface/transformers#16008]
## Environment info
- DeepSpeed version: 0.6.1+097efeb7
- Transformers version: 4.18.0.dev0
- Platform: Linux-5.4.0-99-generic-x86_64-with-glibc2.17
- Python version: 3.8.10
- Huggingface_hub version: 0.2.1
- PyTorch version (GPU?): 1.10.0+cu113 (True)
- Tensorflow version (GPU?): 2.8.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.4.0 (cpu)
- Jax version: 0.3.1
- JaxLib version: 0.3.0
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help
@stas00 @patil-suraj @jeffra 

## Information

Model I am using GPT-J and GPT2

The problem arises when using:
* [ ] the official example scripts: https://github.com/huggingface/transformers/blob/master/examples/pytorch/language-modeling/run_clm.py

## To reproduce

Replace line 360 in run_clm.py from ` model.resize_token_embeddings(len(tokenizer))` to ` model.resize_token_embeddings(50402); exit()`. Then run DeepSpeed + run_clm.py:
```
deepspeed --num_gpus 2 /home/meiyang/src/transformers_fork/examples/pytorch/language-modeling/run_clm.py --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 4 --per_device_eval_batch_size 4 --deepspeed zero3.json --output_dir /tmp/model_output --model_name_or_path ~/models/gpt-j-6B/

Traceback (most recent call last):
  File "/home/meiyang/src/transformers_fork/examples/pytorch/language-modeling/run_clm.py", line 546, in <module>
    main()
  File "/home/meiyang/src/transformers_fork/examples/pytorch/language-modeling/run_clm.py", line 360, in main
    model.resize_token_embeddings(54002)
  File "/home/meiyang/src/transformers_fork/src/transformers/modeling_utils.py", line 744, in resize_token_embeddings
    model_embeds = self._resize_token_embeddings(new_num_tokens)
  File "/home/meiyang/src/transformers_fork/src/transformers/modeling_utils.py", line 765, in _resize_token_embeddings
    new_lm_head = self._get_resized_lm_head(old_lm_head, new_num_tokens)
  File "/home/meiyang/src/transformers_fork/src/transformers/modeling_utils.py", line 911, in _get_resized_lm_head
    new_lm_head.bias.data[:num_tokens_to_copy] = old_lm_head.bias.data[:num_tokens_to_copy]
RuntimeError: The expanded size of the tensor (50400) must match the existing size (0) at non-singleton dimension 0.  Target sizes: [50400].  Tensor sizes: [0]
```

1. The error was triggered by the following code and happened to GPT-J only, not other GPT models such as GPT2 or GPT-neo, probably because only GPT-J has_new_lm_head_bias. 
2. The error didn't happen if I run run_clm.py along without DeepSpeed.
3. The error first occurred when I pulled the latest source code of DeepSpeed. I've tried to bring Transformers to the latest but no help. 

https://github.com/huggingface/transformers/blob/5b7dcc73427d16218488846a365d10866dca9c3e/src/transformers/modeling_utils.py#L833
```
            # Copy bias weights to new lm head
            if has_new_lm_head_bias:
                new_lm_head.bias.data[:num_tokens_to_copy] = old_lm_head.bias.data[:num_tokens_to_copy]
```

**Comment by stas00** [comment]
Thank you for the report, @dunalduck0 and to @jeffra for the PR with the fix.
