### ISSUE TITLE
None in openAi-gpt tokenization

### ISSUE THREAD

**Issue by juliahane** [huggingface/transformers#1600]
Hi
I want to concat two sentences, and give it to openAI-gpt, I use cl sentence1 sep sentence2 sep
I got none with openai-gpt in the first position, could you tell me what is the expected format? thanks

**Comment by rlouf** [comment]
Are you using the GPT tokenizer? If not try

```
tokenizer = transformers.OpenAIGTPTTokenizer()
input_ids = tokenizer.encode(your_text)
```
