### ISSUE TITLE
what's the difference between Megatron-gpt2 and GPT2 inside transformers?

### ISSUE THREAD

**Issue by jinfagang** [huggingface/transformers#16016]
what's the difference between Megatron-gpt2 and GPT2 inside transformers?

**Comment by patil-suraj** [comment]
Hi @jinfagang ! For such general questions please use the [forum](https://discuss.huggingface.co/). We use issues for bug reports and feature requests.

Megatron-gpt2  is the models trained using the megatron library. The arch is similar to the GPT2 arch. You can find more info in the doc https://huggingface.co/docs/transformers/model_doc/megatron_gpt2

**Comment by jinfagang** [comment]
@patil-suraj thanks. I'll move to forum for further discuss. hope you can give me a hand on understanding.
