### ISSUE TITLE
[CI] switching CI to pytorch-1.11

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#16025]
Heads up: pytorch-1.11 will be released tomorrow

@LysandreJik , I recommend we switch our CI to it once it's released - note that nightly is 1.12-tobe so should remain as it is now. 

I have already requested torch-scatter binary wheels for 1.11 which will be needed to switch to : https://github.com/rusty1s/pytorch_scatter/issues/276

we can use this issue to track if anything else is needed.

**Comment by stas00** [comment]
@LysandreJik, `pip install torch-scatter -f https://data.pyg.org/whl/torch-1.11.0+cu113.html` is already avaialble, 

`pip install torch-scatter -f https://data.pyg.org/whl/torch-1.11.0+cu115.html` should be available on Friday.

So no show-stoppers to switch to pt-1.11 now as soon as it's released.

At your convenience of course. I was just trying to make sure that all components are ready.

**Comment by LysandreJik** [comment]
CI was switched to PyTorch 1.11 on the release date, `pytorch-scatter` was updated with the link you shared above. Thank you, for helping track it!
