### ISSUE TITLE
what us the difference between Trainer and Seq2SeqTrainer ?

### ISSUE THREAD

**Issue by Darshan2104** [huggingface/transformers#16038]
Anybody?

**Comment by NielsRogge** [comment]
There's a website called Google, it's pretty great. 
<img width="892" alt="Screenshot 2022-03-10 at 09 41 21" src="https://user-images.githubusercontent.com/48327001/157622136-0a1d5ced-20dd-4d41-bbad-a1d0088f02f3.png">


=> answer explained here: https://discuss.huggingface.co/t/trainer-vs-seq2seqtrainer/3145
