### ISSUE TITLE
raise ValueError(f"Unrecognized tokenizer_type {tokenizer_type}") ValueError: Unrecognized tokenizer_type BertWordPieceCase

### ISSUE THREAD

**Issue by jinfagang** [huggingface/transformers#16035]
BertWordPieceCase is actually a builtin tokenizer inside magatron. But when I using `convert_megatron_gpt2_checkpoint.py` to convert. I got this error:

```
raise ValueError(f"Unrecognized tokenizer_type {tokenizer_type}")
ValueError: Unrecognized tokenizer_type BertWordPieceCase
```

Just wonder, how to make it support？ Does it also works If i using default `gpt2` tokenizer? Any ulternate in transformers interms of `BertWordPieceCase` ?

**Comment by pranav-nair-rit** [comment]
Hey @jinfagang 
Can you kindly tell how did you incorporate BertWordPieceCase tokenizer into the Megatron model? I am trying to do the same.
Thanks!
