### ISSUE TITLE
How to add uppercase letter in chinese-roberta-wwm-ext-large vocab?

### ISSUE THREAD

**Issue by scaler2017** [huggingface/transformers#16039]
I found chinese-roberta-wwm-ext-large vocab  without uppercase letter
?How to add uppercase letter in vocab?

chinese-roberta-wwm-ext-large:  https://huggingface.co/hfl/chinese-roberta-wwm-ext-large/tree/main

**Comment by gante** [comment]
Hi @scaler2017 👋  We try to reserve GitHub issues for bugs and unexpected code behavior. For further other questions, please use our forum here: https://discuss.huggingface.co/ :)
