### ISSUE TITLE
The documentation of transformers.generation_utils.GenerationMixin.generate doesn't match the code of it

### ISSUE THREAD

**Issue by zhaowei-wang98** [huggingface/transformers#16037]
## Environment info

- `transformers` version: 4.17.0
- Platform: Linux
- Python version: 3.8.12
- PyTorch version (GPU?): 1.7.1
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help
 @sgugger@patrickvonplaten @narsil

## Information
The documentation of transformers.generation_utils.GenerationMixin.generate shows many parameters have default value, but the code of it shows all parameters are set to be None by default.

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce
It is about documentation, just look at it.

**Comment by Narsil** [comment]
Hi @zhaowei-wang98 ,

The documentation is sort of correct I think.

The values will be defaulted from the config values of the model, which themselves have a default value which is the one provided in the docs: check here how those variables are initialized https://github.com/huggingface/transformers/blob/master/src/transformers/generation_utils.py#L1062

So even though, technically they are None by default, they will actually inherit the default of the config values (which can be overidden too).
It seems `max_length` does say the default values comes from the config, where other values don't necessarily.
@patrickvonplaten Should we harmonize?

So I think the doc reflects reality as much as possible. https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/model#transformers.generation_utils.GenerationMixin.generate

But maybe some value is incorrectly reported in particular ?
Did you encounter a particular issue with the default values ?

**Comment by patrickvonplaten** [comment]
We do write this in the docs:

> Apart from inputs, all the arguments below will default to the value of the attribute of the same name inside the [PretrainedConfig](https://huggingface.co/docs/transformers/v4.17.0/en/main_classes/configuration#transformers.PretrainedConfig) of the model. The default values indicated are the default values of those config.

Let's maybe wrap this message in a warning to make it clearer? Putting it in my generate doc refactor PR: https://github.com/huggingface/transformers/pull/15988
