### ISSUE TITLE
how can we use the model output to do predict?

### ISSUE THREAD

**Issue by lavine-lmu** [huggingface/transformers#16032]
Hi, I am using transformers to do generation now. especially in ```m2m100``` model. We can easily call ```model.generate()``` to generate the sentences, but can not do predict using the model outputs. can anyone help me? @patrickvonplaten @Narsil 
For example, in the following code, what should we do after we have ```outputs``` from the model to generate the translation text?
```
from transformers import M2M100Config, M2M100ForConditionalGeneration, M2M100Tokenizer

model = M2M100ForConditionalGeneration.from_pretrained("facebook/m2m100_418M")
tokenizer = M2M100Tokenizer.from_pretrained("facebook/m2m100_418M", src_lang="en", tgt_lang="fr")

src_text = "Life is like a box of chocolates."
tgt_text = "La vie est comme une boîte de chocolat."

model_inputs = tokenizer(src_text, return_tensors="pt")
with tokenizer.as_target_tokenizer():
    labels = tokenizer(tgt_text, return_tensors="pt").input_ids

outputs = model(**model_inputs, labels=labels)
```
I mean, whether we can use the ```logits``` to generate the text? Any suggestions will be welcome.

**Comment by NielsRogge** [comment]
Hi

I've answered this question on our forum here: https://discuss.huggingface.co/t/generate-without-using-the-generate-method/11379?u=nielsr

**Comment by NielsRogge** [comment]
For such questions, please use the forum rather than GitHub issues, which are meant for bugs/feature requests.

Thanks!

**Comment by lavine-lmu** [comment]
@NielsRogge Thanks for the reply, this really help me and solve my problems.
