### ISSUE TITLE
Use decoder_inputs in generate function

### ISSUE THREAD

**Issue by JoaoLages** [huggingface/transformers#16040]
# 🚀 Feature request
Use the generate function with some initial decoder inputs.

## Motivation
Imagining I have a trained encoder-decoder transformer and want to generate some output for a given input, but I also have part of the output completed. How do I pass decoder_inputs to the generate method for the model to start the beam search decoding with some initial decoder inputs?
I don't think that it is possible nowadays, even with the `model_kwargs` argument.

## Your contribution
I'm available to help change the `generate` function to make it work. Just need someone to point me to the needed changes to make it easier.

**Comment by patil-suraj** [comment]
it's possible to pass `decoder_input_ids` to `generate`, it takes it as a keyword argument.

```python
model.generate(...,  decoder_input_ids=decoder_input_ids)
```

**Comment by patil-suraj** [comment]
> Even if it accepts the argument, it does not perform the generate method as intended

What do you mean by it does not perform as intended. Could you post the code-snippet to re-produce what the exact issue is ?

**Comment by JoaoLages** [comment]
Just tried it and it's working, it was either solved or I was mistaken. Thank you!
