### ISSUE TITLE
Support for gpt2-medium, gpt2-large and distilgpt2 in pytorch-pretrained-bert 0.6.2

### ISSUE THREAD

**Issue by g-karthik** [huggingface/transformers#1605]
## 🚀 Feature

Request: Inclusion of the below 3 lines in pytorch-pretrained-bert 0.6.2
https://github.com/huggingface/transformers/blob/ef1b8b2ae5ad1057154a126879f7eb8de685f862/transformers/modeling_gpt2.py#L40-L42

## Motivation

Currently, the above 3 lines exist in the latest version of transformers in PyPI, but not in pytorch-pretrained-bert 0.6.2 (also available in PyPI). Consequently, folks wanting to experiment with the above 3 pre-trained models need to necessarily upgrade to the latest version of transformers immediately. As a relief for such folks who plan to migrate eventually but not immediately, it would be great if the above 3 lines are added in pytorch-pretrained-bert 0.6.2.

**Comment by BramVanroy** [comment]
As far as I know pytorch-pretrained-bert development has been discontinued. That makes sense. If you want the new features, you have to upgrade.

**Comment by g-karthik** [comment]
Well technically what I'm asking for isn't a new feature, it's just backwards-compatibility for the above three model artifacts.

I can manually add them to the `modeling_gpt2.py` in my conda environment containing pytorch-pretrained-bert 0.6.2 and verify if these model artifacts work with the old package by invoking the `from_pretrained()` method with each of these three artifact names. I am guessing they would work, but I haven't tried yet.

I feel like this dictionary containing pre-trained artifact names should itself reside in S3, and in `modeling_gpt2.py`, the dictionary should be pulled from S3. Then you could continually add new artifact sizes to that dictionary in S3 and it will work with all versions of this repo, not just some versions. Does that make sense?
