### ISSUE TITLE
`torch.dtype` not JSON serializable if config is nested dict

### ISSUE THREAD

**Issue by feifang24** [huggingface/transformers#16054]
## Environment info

- `transformers` version: 4.16.2
- Platform: Linux-5.4.0-1066-aws-x86_64-with-debian-buster-sid
- Python version: 3.7.12
- PyTorch version (GPU?): 1.10.2 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help

@stas00 

## Information

Model I am using (Bert, XLNet ...): custom model that subclasses `VisionEncoderDecoderModel`

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)
Training an encoder-decoder model where encoder is a `VisionTextDualEncoderModel`, i.e., input is image + text, output is text. When saving the model ran into the following error:`TypeError: Object of type dtype is not JSON serializable`. 
Due to the model architecture, my encoder config has nested dicts, and it turns out that in the nested dicts, `'torch.dtype'` has value `torch.float32` instead of a string. 
Changing `configuration_utils.dict_torch_dtype_to_str` to check for nested dicts resolved the issue:
```
python
    def dict_torch_dtype_to_str(self, d: Dict[str, Any]) -> None:
        """
        Checks whether the passed dictionary has a *torch_dtype* key and if it's not None, converts torch.dtype to a
        string of just the type. For example, `torch.float32` get converted into *"float32"* string, which can then be
        stored in the json format.
        """
        if d.get("torch_dtype", None) is not None and not isinstance(d["torch_dtype"], str):
            d["torch_dtype"] = str(d["torch_dtype"]).split(".")[1]
        for value in d.values():
            if isinstance(value, dict):
                self.dict_torch_dtype_to_str(value)
```

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)
(Image + text)-to-text generation.

## To reproduce

1. Load a regular encoder decoder model
2. Modify the model config by adding a nested dict to either encoder config or decoder config
3. Set value of `'torch.dtype'` to `torch.float32` in the nested dict
4. Try saving the model

## Expected behavior

`TypeError: Object of type dtype is not JSON serializable`

**Comment by stas00** [comment]
Thank you for the report and proposing the fix, which looks great, @feifang24 

the next step is to make a PR out of your proposed fix if that works for you.

**Comment by feifang24** [comment]
That would be awesome! Thank you @stas00 for getting back to me so quickly 🤩 I will file a PR and tag you as a reviewer.

**Comment by krahnikblis** [comment]
still broken in diffusers, recommend something like this unless you can port over the stuff done here?
class dtypeEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, torch.dtype): # might wanna add np, jnp types too?
            return str(obj)
        return json.JSONEncoder.default(self, obj)

## tests:
d = {"torch_dtype": torch.float16}
json.dumps(d) ## fail: TypeError: Object of type dtype is not JSON serializable
json.dumps(d, cls=dtypeEncoder) ## woot: {"torch_dtype": "torch.float16"}
