### ISSUE TITLE
Add missing type hints

### ISSUE THREAD

**Issue by Rocketknight1** [huggingface/transformers#16059]
### This issue is part of our **Great Code Cleanup 2022**. If you're interested in helping out, take a look at [this thread](https://twitter.com/carrigmat/status/1502319813510766599), or come [join us on Discord](https://t.co/kS42XBvpWH) and talk with other contributors!

# 🚀 Add missing type hints

Type hints are used inconsistently in the `transformers` repo across both TF and PT models, and it'd be nice to make them a complete, consistent thing for the core models, especially because we want to develop features that depend on them!

### Guide to contributing:

1. Ensure you've read our contributing [guidelines](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md) 📜 
2. Claim your architecture(s) in this thread (ensure no one is working on it). It's 100% okay to only take the TensorFlow or PyTorch version of a model, if you're not familiar with both frameworks! It's also okay to claim multiple models and group those changes into a single PR! 🎯 
3. Implement the changes as in https://github.com/huggingface/transformers/pull/16057 or https://github.com/huggingface/transformers/pull/16074 (see the diff on the model architectures for a few examples) 💪 
4. Open the PR and tag me in it. You should run `make fixup` at the end to do a code quality check before your final commit!

### Tips for making your PR

1. The files you need to edit will be in `src/transformers/models/[model_name]/`
2. For TensorFlow, you want the `modeling_tf_[model_name].py` file. For PyTorch, you want the `modeling_[model_name].py` file.
3.  Remember, you **do not** have to cover every class in that file!. The main thing we want to cover is the `call` (for TF) or `forward` (for PT) method for user-facing classes like `TFRobertaForMaskedLM` or `RobertaForSequenceClassification`. It's not necessary to add type hints to layers or base classes like `RobertaModel` or `TFRobertaPreTrainedModel` - these are trickier to write, and generally people do not use those classes as standalone models.
4. If you're unfamiliar with how type hints work, you can read the [Python library documentation on them](https://docs.python.org/3/library/typing.html), but it's probably even easier to just look at another PR that added them. Take a look at the list of changes in the pull requests linked above!
5. The types will usually be obvious - most inputs are `Optional[Union[np.ndarray, tf.Tensor]]` for TF models and `Optional[torch.Tensor]` for PyTorch models, and boolean inputs are `Optional[bool]`. Pay attention to the first input of TF models, though, which is usually `TFModelInputType` - this is because Keras handles that first input in a special way! Other inputs to pay attention to are `past_key_values`, which can vary between models, and also the model output type. For the base model classes like `RobertaModel`, you may have to look at the corresponding `MainLayer` to figure out the right output type! Also, note that the output type may be a tuple if `return_dict` is False, in which case you should specify `Union[Tuple, ...]`. Finally, note that in TF models, `training` is never `None`, so it should be `training: bool` and not `training: Optional[bool]`.
6. Note that some code is copied across our codebase. If you see a line like `# Copied from transformers.models.bert...`, this means that the code is copied from that source, and our scripts will automatically keep that in sync. If you see that, you should not edit the copied method! Instead, edit the original method it's copied from, and run `make fixup` to synchronize that across all the copies. Be sure you installed the development dependencies with `pip install -e ".[dev"]`, as described in the contributor guidelines above, to ensure that the code quality tools in `make fixup` can run.

### How can I find models that need type hints?

I used to maintain a list here, but it got out of date, I'm sorry. Instead, you can use [this Colab notebook](https://colab.research.google.com/drive/1EvZTslb50yfRqIcXjCZFrbod4HrPdA0G?usp=sharing). If you run this, it will show you models in PyTorch or TF that are still missing type hints. Unlike my manually curated lists, it's guaranteed to be up to date - but do double-check that someone else in the thread hasn't claimed a model before you start, because the Colab code will only register type hints after the PR containing them is merged!

**Comment by johnnv1** [comment]
Hi, I would like to work on PyTorch `ImageGPT`

**Comment by ChainYo** [comment]
Hi, I would like to work on `CamemBERT` for PT & TF.

I will take a look at `LayoutLMv2` after the first one :)

**Comment by johnryan465** [comment]
I'll try PyTorch BERT to start!

**Comment by Rocketknight1** [comment]
@johnryan465 I just did it as an example, I'm sorry! I'm marking off the completed models now.

**Comment by johnryan465** [comment]
@Rocketknight1 no worries, will try and do DistillBert instead

**Comment by cakiki** [comment]
I'd like to work on GPT2 (TF).

**Comment by ChainYo** [comment]
@Rocketknight1 I switch to Roberta PyTorch because CamemBERT depends on Roberta modeling

**Comment by johnnygreco** [comment]
Awesome! Hey @Rocketknight1 – I'd like to work on Longformer for both PyTorch & TF!

**Comment by tanmoyio** [comment]
I'd like to work on BigBird

**Comment by jacobdineen** [comment]
I work like to work on Clip for pytorch.

**Comment by johnnv1** [comment]
Also, will work on `BeiT`, `Deit` and `ViT`

**Comment by tanmoyio** [comment]
https://github.com/huggingface/transformers/pull/16091

**Comment by bhavika** [comment]
I can work on ImageGPT.

**Comment by omer-dor** [comment]
I can work on Swin (Pytorch)

**Comment by elusenji** [comment]
I'd like to work on XLM (Tensorflow)

**Comment by Dahlbomii** [comment]
I'll take T5 (Tensorflow)!

**Comment by robotjellyzone** [comment]
Hi,

I would like to work on  BART of  both TF and PyTorch

**Comment by kamalkraj** [comment]
ELECTRA TF and PT

**Comment by manandey** [comment]
XLMRobertaXL (PyTorch)

**Comment by p-mishra1** [comment]
segformer pytorch

**Comment by TristanBilot** [comment]
I'll take OpenAIGPT!

**Comment by robotjellyzone** [comment]
> Hi @Rocketknight1,
> 
> I would like to work on BART of both TF and PyTorch

can you please confirm with emoji whether i am eligible to take these or not? @Rocketknight1

**Comment by jbrry** [comment]
I will work on XLM (PyTorch)

**Comment by Rocketknight1** [comment]
@robotjellyzone You can! Please note that we accepted a PR yesterday to add the TF decorator to BART, so make sure you're working on the most recent version of the library before you start your PR!

**Comment by PepijnBoers** [comment]
I'll take Distilbert (TensorFlow)

**Comment by frgfm** [comment]
Happy to take T5 (PyTorch)

@Rocketknight1 isn't the list missing ConvNext? If so, I'm happy to take care of that one too :ok_hand:

**Comment by tmastrom** [comment]
I'll work on GPTJ

**Comment by robotjellyzone** [comment]
> @robotjellyzone You can! Please note that we accepted a PR yesterday to add the TF decorator to BART, so make sure you're working on the most recent version of the library before you start your PR!

OK sure! I will keep this in mind 😊👍...

**Comment by jacobdineen** [comment]
I'll take Splinter and Segformer for torch

**Comment by wpan03** [comment]
I'll work on MobileBert for PyTorch

**Comment by bhavika** [comment]
Looks like ImageGPT was done. I can take Luke and Data2Vec in PyTorch.

**Comment by soomiles** [comment]
I'd like to take PoolFormer

**Comment by ChainYo** [comment]
I'm going for `Flaubert` now !

**Comment by wpan03** [comment]
Just noticed that MobileBert was done. I'll work on BigBirdPegasus for PyTorch instead.

**Comment by wpan03** [comment]
Just noticed that MobileBert was done. I'll work on FNet for PyTorch instead.

**Comment by Tegzes** [comment]
Hello, I will work on GPTNeo and SqueezeBERT for Pytorch!

**Comment by Tegzes** [comment]
I will also work on GPTNeo for Pytorch

**Comment by jcmc00** [comment]
I'd like to work on Perceiver (torch)

**Comment by Tegzes** [comment]
I will also work on Pegasus for pytorch

**Comment by Tegzes** [comment]
I will work on XLMRoberta for TF

**Comment by mowafess** [comment]
I will work on YOSO for PT

**Comment by clefourrier** [comment]
Hi, I'll take Marian (Pytorch)

**Comment by akashe** [comment]
Hi, I will work on RAG(pytorch).

**Comment by Tegzes** [comment]
Nevermind, XLMRoberta relies on Roberta (for TF)

**Comment by GigaMoksh** [comment]
Hey, I would like to work on the BigBirdPegasus model of Pytorch.

**Comment by pratyushsingh97** [comment]
Happy to take CTRL and MPNet. Let me know if someone already has these!

**Comment by elusenji** [comment]
I'm working on MobileBert for both TensorFlow & PyTorch.

**Comment by TristanBilot** [comment]
Hi @DPT4, it has already been done here: https://github.com/huggingface/transformers/pull/16156

**Comment by DPT4** [comment]
Hi @TristanBilot thanks for informing me. Then, I'd like to take MegatronBert for PyTorch.

**Comment by neelrast** [comment]
This is Awesome! Hey, @Rocketknight1 I'd like to work on ConvBERT for both PyTorch & TF 🤗

**Comment by jcmc00** [comment]
I'd like to work on TransfoXL if still available

**Comment by DPT4** [comment]
I'll take Data2Vec for PyTorch looks like seems available.

**Comment by mowafess** [comment]
I will work on XLMProphetNet for PT

**Comment by mowafess** [comment]
I will work on XGLM for PT

**Comment by yhl48** [comment]
I would like to work on MT5 (PyTorch)

**Comment by Tegzes** [comment]
I will work on ProphetNet, UniSpeech and UnispeechSat

**Comment by IvanLauLinTiong** [comment]
I'll work on 
TF - Blenderbot 
PyTorch - Blenderbot and BlenderbotSmall

**Comment by gchhablani** [comment]
I can take up 
PyTorch: PLBart and VisualBert

**Comment by AMontgomerie** [comment]
Hi, I'll take Funnel

**Comment by yhl48** [comment]
I will take IBert, Lxmert, XLMProphetNet for PyTorch.

**Comment by Rocketknight1** [comment]
Hi all, with the end of the sprint I probably won't be actively maintaining this issue, but there are still models outstanding! If you're curious about what's left to do, I've added [this Colab notebook](https://colab.research.google.com/drive/1EvZTslb50yfRqIcXjCZFrbod4HrPdA0G?usp=sharing) that you can use to find model classes without type hints. We'd appreciate type hints for any and all of them!

**Comment by Tegzes** [comment]
@Vaibhavs10 Are you still working on the Wav2Vec model? I'm working on UniSpeech and some ```make fixup``` tests fail because of inconsistencies with that model. I could take care of it if want

**Comment by hiromu166** [comment]
Hi, I'd like to work on Canine.

**Comment by jQuinRivero** [comment]
Hey, I'd like to work on XLMRoBERTa (Pytorch)

**Comment by F02934** [comment]
Hello @Rocketknight1  I would like to try working on CTRL (Tensorflow and Pytorch)

**Comment by F02934** [comment]
@Rocketknight1 It seems that "ConvBert" is already done PR #16377 for both TensorFlow and Pytorch.
So I would like to work on "yoso"

**Comment by willtai** [comment]
Hey there @Rocketknight1 I would like to work on MegatronBERT 😄

**Comment by F02934** [comment]
Hi @Rocketknight1 I checked the Colab notebook and I will be adding the missing type hints for CVT (Pytorch)

> Hi all, with the end of the sprint I probably won't be actively maintaining this issue, but there are still models outstanding! If you're curious about what's left to do, I've added [this Colab notebook](https://colab.research.google.com/drive/1EvZTslb50yfRqIcXjCZFrbod4HrPdA0G?usp=sharing) that you can use to find model classes without type hints. We'd appreciate type hints for any and all of them!

**Comment by willtai** [comment]
Good shout @F02934 ! 

@Rocketknight1 I've checked the above Colab notebook and looks like MegatronBERT is done. I will add missing type hints for QDQBertModel

**Comment by willtai** [comment]
Can I take `GPTNeoxForCausalLM` and `GPTNeoXModel`?

**Comment by donelianc** [comment]
I would like to add type hints for `RoFormer` (only in Pytorch). After running and checking the notebook Colab [notebook](https://colab.research.google.com/drive/1EvZTslb50yfRqIcXjCZFrbod4HrPdA0G), I think I can take care of the seven classes missing type hints 👍️.

Should I submit a single PR for all the seven updated classes?

**Comment by Mathews-Tom** [comment]
Hi, I would like to work on `TensorFlow` : `OpenAIGPT`

**Comment by Mathews-Tom** [comment]
Hi, I would like to work on `TensorFlow` : `CTRL`

**Comment by asofiaoliveira** [comment]
Hello, according to the colab notebook, `XLMRobertaXL` (PyTorch) classes are still missing type annotations
They were mentioned here back on March 12th but there is no PR associated, so I can work on that if @manandey hasn't already

**Comment by manandey** [comment]
> I can work on that if @manandey hasn't already

@asofiaoliveira Feel free to work on this incase you are interested!

**Comment by donelianc** [comment]
Hi 🤗. `Vilt` (PyTorch) model remains without type hints, so I would like to work on it.

**Comment by daspartho** [comment]
I'll take on PyTorch BigBirdPegasus and open a PR :)

**Comment by daspartho** [comment]
M2M model missing type hints, I'll work on it and open a PR.

**Comment by daspartho** [comment]
I'll create a PR for FSMT :)

**Comment by daspartho** [comment]
Some type hints are missing in PyTorch UniSpeech, MPNet, and Nystromformer.
I'll take on it and group those changes into a single PR!

**Comment by daspartho** [comment]
PyTorch SEWD model missing some type hints, I'll work on it and open a PR.

**Comment by kishore-s-15** [comment]
`TFConvBERTModel` does not have type hints. I would like to work on adding typing hints for it.

**Comment by kishore-s-15** [comment]
I would like to work on adding type hints for `TFMPNet` models.

**Comment by debjit-bw** [comment]
Hi, I would like to work on PyTorch: OpenAIGPT

**Comment by kalashjain23** [comment]
I would like to work on Tensorflow's XLNet!

**Comment by debjit-bw** [comment]
I'm taking up `TF Rag`

**Comment by elusenji** [comment]
I'd like to work on Lxmert for TF and PyTorch.

**Comment by E-Aho** [comment]
> MobileBert

Did you manage to get this merged in @elusenji? Otherwise I'm gonna start on the MobileBERT type hints 🤗

**Comment by IMvision12** [comment]
I would love to work on Tensorflow XLNet🚀

**Comment by thliang01** [comment]
HI, I would like to work on Tensorflow XLNet

**Comment by arcAman07** [comment]
Hi, I would like to work on PyTorch XLMRoBERTa

**Comment by thliang01** [comment]
Adding type hints for TFXLnet #19344

**Comment by thliang01** [comment]
Adding type hints for TFXLnet #19344

**Comment by mariagrandury** [comment]
Hey! I'll take `OpenAIGPT` both for TensorFlow & PyTorch

**Comment by arcAman07** [comment]
I would love to work on PyTorch SEWD for the remaining classes.

**Comment by RamitPahwa** [comment]
Hi!, I can create a PR for CTRL for Pytorch and Tensorflow.

**Comment by rchan26** [comment]
Hi, I'd like to work on MT5 for Pytorch and Tensorflow 🙂

**Comment by WhiteWolf47** [comment]
Hey, I would like to work on the Swin model files!

**Comment by sirmammingtonham** [comment]
Hi I'd love to work on Reformer and RoFormer pytorch 😊

**Comment by Rocketknight1** [comment]
Hi @sirmammingtonham thank you so much for pointing that out! I just realized I'd been failing to keep the list of models up to date - I made a Colab to check our codebase instead, which is linked at the bottom of the initial post and will always be up to date.

**Comment by Rocketknight1** [comment]
This applies to other people who recently started, cc @mariagrandury @arcAman07 @RamitPahwa @rchan26 @WhiteWolf47. If you found the model you chose already has type hints, this is why! Please double-check in the Colab to see where type hints are still needed.

**Comment by arcAman07** [comment]
Hey just saw the codebase and realised a lot of models already have type hints. I did notice dpt list of models didn't have type hints and I would love to work on that issue.

**Comment by WhiteWolf47** [comment]
> This applies to other people who recently started, cc @mariagrandury @arcAman07 @RamitPahwa @rchan26 @WhiteWolf47. If you found the model you chose already has type hints, this is why! Please double-check in the Colab to see where type hints are still needed.

Hey, just checked out the colab notebook, i have decided to work on the YolosModel

**Comment by Rocketknight1** [comment]
Thanks all, and sorry again about the list being out of date initially!

**Comment by SaurabhBudhwani26** [comment]
Hi, I would love to work on FLAVA and LEVIT Pytorch , can you assign this to me?

**Comment by rchan26** [comment]
Hi I was going to work on MT5 for Pytorch and TF, but looking at `src/transformers/models/mt5/modeling_mt5.py` and `src/transformers/models/mt5/modelling_tf_mt5`, it looks like each of the classes in these files override other models (`T5model`, `T5ForConditionalGeneration`, `T5EncoderModel`, `TFT5Model`, `TFT5ForConditionalGeneration`, `TFT5EncoderModel`). Each of these already have type hints, so I guess there isn't anything to do for MT5 now?

**Comment by soma2000-lang** [comment]
@Rocketknight1  I will work on ViTModel

**Comment by EdAbati** [comment]
Hi @Rocketknight1 , I will take `TFViTPreTrainedModel` :)

**Comment by ringohoffman** [comment]
I would like to work on `EsmForProteinFolding`

**Comment by donelianc** [comment]
Hi folks, 

We are almost done with this task! From the [notebook](https://colab.research.google.com/drive/1EvZTslb50yfRqIcXjCZFrbod4HrPdA0G?usp=sharing) created by RK ([Rocketknight1](https://github.com/Rocketknight1)), I'm sharing here the remaining models to gain some visibility and encourage one last push.

1. PyTorch models: 
   - ASTModel
   - EsmForProteinFolding (taken by [ringohoffman](https://github.com/ringohoffman))

2. TF models (excluding pre-trained classes):
   - TFDeiTModel
   - TFEncoderDecoderModel
   - TFLEDForConditionalGeneration
   - TFLEDModel
   - TFLxmertForPreTraining
   - TFMarianMTModel
   - TFMarianModel
   - TFRagModel
   - TFRagTokenForGeneration
   - TFSegformerDecodeHead
   - TFTransfoXLLMHeadModel
   - TFTransfoXLModel
   - TFVisionEncoderDecoderModel
   - TFWhisperForConditionalGeneration
   - TFWhisperModel (_I'll take this one 🙂_)

_Important_: Remember to run the [notebook](https://colab.research.google.com/drive/1EvZTslb50yfRqIcXjCZFrbod4HrPdA0G?usp=sharing) to check which models are still missing type hints and look if anyone has claimed before start working on it.

**Comment by Batese2001** [comment]
Hello @Rocketknight1 I'd love to tackle TFEncoderDecoderModel if it is available

**Comment by JuheonChu** [comment]
Hello @Rocketknight1 I would like to tackle TFVisionEncoderDeocderModel if possible with @miyu386  and @AdiaWu.

**Comment by katiele47** [comment]
Hi @Rocketknight1 I'd love to take TFMarianModel with @Batese2001 and @mollerup23!

**Comment by szymonrucinski** [comment]
Good Morning @Rocketknight1,
I would love to help you with adding types to the following models:

1. TFAlbertPreTrainedModel
2. TFBartPretrainedModel
3. TFBertPreTrainedModel

**Comment by mollerup23** [comment]
@Rocketknight1 Are there other models that need type hints? I looked at the list generated by the Google Colab notebook, and noticed the 'TFPegasusPreTrainedModel' still needs type hints. If so, I'd like to pick this up.

**Comment by Rocketknight1** [comment]
Oops, yep, I didn't realize that last PR had auto-closed it. If you can find other models that need type hints, then please submit PRs to add them! Make sure to 'sync changes' in your fork before creating the PR branch so that there aren't any issues with rebasing and it should go smoothly.

**Comment by mollerup23** [comment]
Great! In that case I'd like to claim the TFPegasusPreTrainedModel. I'll make sure to sync before making any commits. Thanks!

**Comment by Batese2001** [comment]
@Rocketknight1 I would love to take TFDeiTModel if that's alright.

**Comment by Batese2001** [comment]
@Rocketknight1 Actually, looking deeper into the model, it looks like the type hints are already implemented in the call method for the TFDeiTModel class. Should I be adding the type hints to some of the other call methods in modeling_tf_deit.py?

**Comment by Rocketknight1** [comment]
@Batese2001 If the script is listing models as needing type hints but they already have them, it's possible that they're missing some part of the hints. Maybe the return type from the main model `call()` methods is not present?

**Comment by mollerup23** [comment]
@Rocketknight1 Hi Matt, can I work on TFBlenderbot for this issue?

**Comment by dewasahu2003** [comment]
@Rocketknight1 Hi Matt 👋 , i would like to take `Graphormer`

**Comment by dewasahu2003** [comment]
hi there 👋 can anybody tell me how to perform all check before comitting, make fixup- not working and github ci/cd failing, is it because i'm using python 3.11 or some other error

**Comment by Rocketknight1** [comment]
Hi @dewasahu2003, to run `make fixup` you will need to install some dependencies for code formatting and quality tools. The easiest way to do this is `pip install transformers[quality]` or `pip install -e .[quality]` in the directory where you cloned the `transformers` repo.

**Comment by MuskaanCAIR** [comment]
If ALBERT or XLMRoBERTa (Tensorflow) are still available then I would like to work on any one of them.

**Comment by Rocketknight1** [comment]
@MuskaanCAIR You can use the [colab script](https://colab.research.google.com/drive/1EvZTslb50yfRqIcXjCZFrbod4HrPdA0G?usp=sharing) in the first post to see which models still need hints. Remember that models will be listed by that Colab as long as they're missing full type hints including return type hints on the `call()` method. It's less important to annotate layers and functions in the model files, although still appreciated!

**Comment by MuskaanCAIR** [comment]
Colab lists TFXLMRobertaPreTrainedModel as one of the models. Can I take that?

**Comment by Rocketknight1** [comment]
@nablabits If the Colab doc says type hints are missing, then at least some are still missing, so you can totally take it!

(People often forget the return type, and the Colab will still mark a model as missing type hints if it isn't there)

**Comment by nablabits** [comment]
@Rocketknight1, ahh yeah, thanks for the reminder, I've seen that in the comments before, I will pay extra attention to that when opening the PR

**Comment by nablabits** [comment]
Hi @Rocketknight1 I've just pushed above PR :point_up:, hope I'm not missing anything :crossed_fingers:  

Chances are this has been suggested/tried in the past and there's a good reason to not do it, but just in case, probably we can improve the notebook with this bit that not only will check for the `return` but also for all the arguments in the `forward` method:

```python
import transformers
from typing import get_type_hints
from inspect import getfullargspec
for obj in dir(transformers):
    try:
        model = getattr(transformers, obj)
        if issubclass(model, transformers.PreTrainedModel):
            actual_hints = set(get_type_hints(model.forward))
            expected_hints = set(getfullargspec(model.forward).args)
            expected_hints.remove('self')  # self does not carry type hints
            expected_hints.add('return')  # we need a type hint also for the output

            missing_hints = expected_hints - actual_hints
            if missing_hints:
                print(f"{obj}: {missing_hints}")

    except:
        pass
```

Running above, yields that for instance `AltCLIPModel` is missing `token_type_ids` ([check here](https://github.com/huggingface/transformers/blob/83f9314d10ffe4ed30b9b7e642d3621e77ae080e/src/transformers/models/altclip/modeling_altclip.py#L1616))

**Comment by nablabits** [comment]
Hey @Rocketknight1 I will continue with `AltCLIP` now (a quick search on this page does not return any result for that)

**Comment by nablabits** [comment]
@sgugger I'd say that this might have been closed automatically but it shouldn't have. Probably there's some automation I don't know about that closes issues whenever some conditions are met, in that case lmk if I need to change anything whenever I open a PR. 
Thanks for your patience :pray:

**Comment by Rocketknight1** [comment]
@nablabits That happens when you link an issue in the PR - Github assumes the PR resolves the issue!

Also, your suggestion for the notebook is good - I'll update it today!

**Comment by Rocketknight1** [comment]
@nablabits notebook updated based on your suggestion, thank you!

**Comment by nablabits** [comment]
> That happens when you link an issue in the PR - Github assumes the PR resolves the issue!

Hey Matt, that makes sense, probably it was picking the `16059` in the title of the PR or in the commit or even the bit `fixes 16059` as a whole. I can see some other PRs that didn't close the issue and still keep a reference in the first comment, eg, https://github.com/huggingface/transformers/pull/23071

> notebook updated based on your suggestion, thank you!

Brilliant, always happy to be useful :hugs: 

---
I'm keen to further reduce that list so I will pick some of the first entries:

- [BigBirdForQuestionAnswering](https://github.com/huggingface/transformers/pull/16555/files#diff-105050df48478038230c39542f0b33bbdac053c19cbad5e7748f04f6cc7559e5R2962) was picked back in the day but it's still missing one

These ones have not been  picked yet:
- `Blip2QFormerModel`
- `ConditionalDetrForObjectDetection`
- `ConditionalDetrForSegmentation`
-  `ConditionalDetrModel`

Is it ok to open a PR with all of them?

@Rocketknight1

**Comment by nablabits** [comment]
Hey Matt, I will pick now these guys, let's crush that list 📋:
- `CpmAntModel`
- `DecisionTransformerModel`
- DPR family: `DPRContextEncoder`, `DPRQuestionEncoder`, `DPRReader`
- Deformable Detr family: `DeformableDetrForObjectDetection`, `DeformableDetrModel`
- Deta family: `DetaForObjectDetection`, `DetaModel`
- Detr family: `DetrForObjectDetection`, `DetrForSegmentation`, `DetrModel`

@Rocketknight1

**Comment by nablabits** [comment]
Hey Matt, I'm working now on the next 6 items:
- ErnieM Family: `ErnieMForInformationExtraction`, `ErnieMForMultipleChoice`, `ErnieMForQuestionAnswering`, `ErnieMForSequenceClassification`, `ErnieMForTokenClassification` & `ErnieMModel`
- `EsmForProteinFolding`
- `GraphormerModel`
- `InstructBlipQFormerModel`
- `LayoutLMForMaskedLM`
- `LukeForEntitySpanClassification`

@Rocketknight1

**Comment by nablabits** [comment]
Hi Matt, at this point I'm keen to finish all the remaining type hints for the pytorch models (17). I will open a couple of PRs so the review won't be a pain (unless you tell me otherwise)

@Rocketknight1

**Comment by nablabits** [comment]
So these :point_up: are the last ones for the pytorch models. 

By looking at the git history I appreciate that you are pretty busy these days so no rush on this. Here you have a quick recap on what we have so far:
- https://github.com/huggingface/transformers/pull/25557: in this guy I tested [what we talked about](https://github.com/huggingface/transformers/pull/25557#discussion_r1300884334) and kept the type hints so it might be good to deploy.
- https://github.com/huggingface/transformers/pull/25705: no action yet
- https://github.com/huggingface/transformers/pull/25749: no action yet
- https://github.com/huggingface/transformers/pull/25750: no action yet

In the meantime I will start getting an intuition of how the TF ones work, I can't say that I'm going to address all of them (as there are a lot) but let's see how far we can get :snail:

**Comment by nablabits** [comment]
> In the meantime I will start getting an intuition of how the TF ones work, I can't say that I'm going to address all of them (as there are a lot) but let's see how far we can get 🐌

It turns out that there are not that many after all, because most of them are ultimately subclassing from `tf.keras.model` [whose call method](https://github.com/keras-team/keras/blob/master/keras/engine/training.py#L593) is not annotated itself, hence the error. I'd say that we are only interested in the models that actually override the `call` method, so I updated a bit the script to retrieve missing type hints:

```python
from inspect import getfullargspec, isclass, isfunction
import transformers
from typing import get_type_hints

def is_call_overridden(cls):
    return "call" in cls.__dict__ and isfunction(cls.__dict__["call"])

def compute_missing_hints_tf(model):
    if isclass(model) and issubclass(model, transformers.TFPreTrainedModel) and is_call_overridden(model):
        actual_hints = set(get_type_hints(model.call))
        expected_hints = set(getfullargspec(model.call).args)
        expected_hints.remove("self")  # self does not carry type hints
        expected_hints.add("return")  # we need a type hint also for the output

        missing_hints = expected_hints - actual_hints
        if missing_hints:
            print(f"{obj}: {missing_hints}")
```

This yields a much narrower list, so if these assumptions are right, with another PR we might be done with the issue. Matt, let me know what you think.

@Rocketknight1

**Comment by Rocketknight1** [comment]
@nablabits Ah, of course! I should have realized that the base `PreTrainedModel` classes do not have an overridden `call()`, because they're always subclassed before being used. Good catch.

**Comment by Rocketknight1** [comment]
This project is now officially complete! Thank you to everyone in this thread, and to other people who filed PRs, and congratulations to @nablabits who filed the final PR to finish it all!

**Comment by Cebtenzzre** [comment]
Are we any closer to reverting #18485?
