### ISSUE TITLE
Show pretrained model and config file download address directly in README.md & doc

### ISSUE THREAD

**Issue by Sunnycheey** [huggingface/transformers#1606]
## 🚀 Feature

Show download address of pretrained model address directly in markdown file.
## Motivation
Since my server cannot directly go to aws server, and it's not configed to proxy too. Intuitively i need to download pretrained model in my computer and then upload it to my server. The question is I need to checkout source code for download address. It's a really bad experience.

**Comment by BramVanroy** [comment]
I feel that this would clutter the README, leading to a bad experience for 99.99% of users. But you can always submit a PR and see what the maintainers think.

**Comment by Sunnycheey** [comment]
Just make a PR.
