### ISSUE TITLE
[INFO|modelcard.py:460] 2022-03-11 19:03:24,502 >> Dropping the following result as it does not have all the necessary fields: {'task': {'name': 'Causal Language Modeling', 'type': 'text-generation'}}

### ISSUE THREAD

**Issue by Penguin-jpg** [huggingface/transformers#16069]
## Environment info
- `transformers` version: 4.18.0.dev0
- Platform: Windows-10-10.0.17763-SP0
- Python version: 3.6.8
- Huggingface_hub version: 0.4.0
- PyTorch version (GPU?): 1.10.2+cu113 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

Models:
- GPT-Neo

Examples:
- lanuage modelling/run_clm.py and run_clm_no_trainer.py
- maintained examples (not research project or legacy): @sgugger, @patil-suraj

## Information

Model I am using (Bert, XLNet ...):GPT-NEO

The problem arises when using:
* [x] the official example scripts: (give details below)
   I used run_clm.py and run_clm_no_trainer.py to train GPT-NEO, but it doesn't work today. It worked everytime before today.
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)
  I repeated the process in https://github.com/gagan3012/project-code-py/blob/master/notebooks/gptneomodel.ipynb to create this dataset. I didn't make it a txt file, I use csv. But I also tried a txt file(the data is from https://s3.amazonaws.com/code-search-net/CodeSearchNet/v2/python.zip), and it didn't work.(Both file worked before.)

## To reproduce

1. change directory to transformers\examples\pytorch\language-modeling
2. run the command below
```
python run_clm.py^
      --output_dir C:\GPT_Coder\model_gpt_neo_test^
      --model_name_or_path EleutherAI/gpt-neo-125M^
	  --train_file C:\GPT_Coder\data\leetcode\train.csv^
      --validation_file C:\GPT_Coder\data\leetcode\valid.csv^
	  --validation_split_percentage 0^
      --per_device_train_batch_size 8^
      --per_device_eval_batch_size 8^
      --learning_rate 5e-5^
	  --block_size 128^
	  --num_train_epochs 10
```
3. after tokenized the dataset and group text, this message shows
![image](https://user-images.githubusercontent.com/69071861/157858881-197e5677-52c2-4ed8-a9cb-00b3deb513e7.png)

## Expected behavior
I expected it to start training just like how it worked before.

**Comment by patil-suraj** [comment]
Hi @Penguin-jpg , to run the training and evaluation you should pass the `--do_train` and `--do_eval` arguments to the script.

**Comment by Penguin-jpg** [comment]
> Hi @Penguin-jpg , to run the training and evaluation you should pass the `--do_train` and `--do_eval` arguments to the script.

Thanks!! It works! But it is weird. I am pretty sure that when I passed do_train and do_eval then it said no such argument or something like that before today. I had to remove them to make it work.
