### ISSUE TITLE
failed to download pretrained weights

### ISSUE THREAD

**Issue by minapril** [huggingface/transformers#1607]
## 🐛 Bug

Model I am using (Bert, XLNet....):BERT

Language I am using the model on (English, Chinese....):English

During downloading  pretrained weights with code of modeling_bert.BertForMaskedLM.from_pretrained('bert-base-uncased'),another exception occurred:
![image](https://user-images.githubusercontent.com/52790610/67380476-faafe900-f5bc-11e9-84a1-bd0c8eeb7515.png)

**Comment by LysandreJik** [comment]
Hi, this seems to be a network error. Are you sure you have access to the internet on this machine, or is it behind a firewall?
