### ISSUE TITLE
Want to push a branch for a PR that fixes Deberta classification dropout and armonizes the dropout class, but have no permissions.

### ISSUE THREAD

**Issue by alexvaca0** [huggingface/transformers#16071]
Hi, I'm trying to push a new branch that fixes Deberta classification dropout by adding cls_dropout to DebertaConfiguration. In this branch I've also changed the Dropout class of DebertaForTokenClassification to StableDropout, to use the same type of dropout as the other classes. 

However, I am not able to perform this operation even this is a new branch and wouldn't break anything in master or other branches... @LysandreJik  @vanpelt @patrickvonplaten How can I do it??

**Comment by gante** [comment]
Hi @alexvaca0 👋  From your message I can't confirm whether you're doing this or not, so here it goes: [we expect the contributions](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests) to come from *branches on a fork*, from which you can open a PR to the main repo. Have you tried doing this? :)

**Comment by alexvaca0** [comment]
Hey @gante thank you very much for your answer :) I didn't know contributions needed to come from a fork! I'll do that then ! thank you ❤️

**Comment by gante** [comment]
Awesome, glad I could help! Closing this issue :)
