### ISSUE TITLE
Nystromformer Pretrained model with longer sequence length 

### ISSUE THREAD

**Issue by etrigger** [huggingface/transformers#16130]
The released Nystromformer model only deals with 512 tokens. Will we release some pretrained models with max sequence length such as 1024, 2048 and 4096 mentioned in the paper.

@novice03 @NielsRogge

**Comment by novice03** [comment]
Hello, the model for larger sequence lengths might be released in a few weeks.

**Comment by NielsRogge** [comment]
Hi,

Nyströmformer trained on sequence length 1024 is available now: https://huggingface.co/uw-madison/nystromformer-1024

Closing this issue.
