### ISSUE TITLE
Text2Speech classes

### ISSUE THREAD

**Issue by alexvaca0** [huggingface/transformers#16159]
Hey, it would be very cool if there were classes already developed for carrying out Text2Speech tasks. We do have many classes capable of doing Speech2Text, but for the opposite task there are no transformer classes available, although there are starting to be models in the hub: https://huggingface.co/facebook/tts_transformer-es-css10

It would be great if instead of using fairseq for loading those models, we could load them and fine-tune them further with Transformers.

**Comment by LysandreJik** [comment]
Pinging @anton-l for knowledge :)

**Comment by anton-l** [comment]
Hi @alexvaca0, thanks for your interest!
We're currently working on implementing FastSpeech2 natively: https://github.com/huggingface/transformers/pull/15773
And looking into FastPitch as well: https://github.com/huggingface/transformers/issues/16349

Feel free to subscribe to those PRs/issues to follow the progress :)
