### ISSUE TITLE
Add T5 model

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#1617]
# 🌟New model addition

## Model description

Google released paper + code + dataset + pre-trained model about their new **T5**, beating state-of-the-art in 17/24 tasks.

[Paper link](https://arxiv.org/pdf/1910.10683.pdf)

## Open Source status

* [x] the model implementation and weights are available: [Official codebase](https://github.com/google-research/text-to-text-transfer-transformer)

**Comment by tnlin** [comment]
+1, it is a very impressive work

**Comment by Quetzalcohuatl** [comment]
https://github.com/google-research/text-to-text-transfer-transformer

**Comment by elfprince13** [comment]
It's not super-well documented, but it's clearly present: 
https://github.com/huggingface/transformers/blob/dc17f2a1110aed8d1729e77b0619601e3d96b84e/src/transformers/modeling_tf_t5.py
