### ISSUE TITLE
Format problem when training DistilBert

### ISSUE THREAD

**Issue by alexandrabenamar** [huggingface/transformers#1618]
## Format problem when training DistilBert

Hello,

I'm trying to train DistilBert from scratch on French language with the official "trainin with distillation task" script.

## To Reproduce

The problem arise when I invoke the script : 
https://github.com/huggingface/transformers/blob/master/examples/distillation/distiller.py
With the command line : 
```bash
python train.py --student_type distilbert --student_config training_configs/distilbert-base-uncased.json \
    --teacher_type bert --teacher_name bert-base-uncased --mlm --dump_path train_model/my_first_training --data_file data/binarized_text.bert-base-multilingual-cased.pickle \
    --token_counts data/token_counts.bert-base-uncased.pickle --force --n_gpu 1
```

I did not modify the script in any way, and I get the error : 

```bash
Traceback (most recent call last):
  File "train.py", line 286, in <module>
    main()
  File "train.py", line 281, in main
    distiller.train()
  File "/dds/work/distil/transformers/examples/distillation/distiller.py", line 335, in train
    token_ids, attn_mask, lm_labels = self.prepare_batch_mlm(batch=batch)
  File "/dds/work/distil/transformers/examples/distillation/distiller.py", line 227, in prepare_batch_mlm
    token_ids = token_ids.masked_scatter(pred_mask, _token_ids)
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'mask'
```

## Environment

* OS: Windows
* Python version: 3.6
* PyTorch version: 1.1.0
* PyTorch Transformers version (or branch): 2.1.1
* Using 1 GPU

Could you help me resolve this ?

**Comment by LysandreJik** [comment]
Hi, I believe that `torch.bool` was introduced in PyTorch 1.2.0. Do you think you could try to upgrade it to 1.2.0 to try out the distillation scripts?

**Comment by alexandrabenamar** [comment]
Problem fixed, the problem was the PyTorch version as you said, thank you so much! :)
