### ISSUE TITLE
'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by lipingbj** [huggingface/transformers#1620]
When I load the pretrained model from the local bin file, there is a decoding problem.

**Comment by LysandreJik** [comment]
Hi, could you provide more information: **e.g. respect the template**? Please tell us which model, which bin file, with which command?

**Comment by lipingbj** [comment]
> Hi, could you provide more information: **e.g. respect the template**? Please tell us which model, which bin file, with which command?

tokenizer = BertTokenizer.from_pretrained("/home/liping/liping/bert/bert-base-cased-pytorch_model.bin")

XLNetModel.from_pretrained("/data2/liping/xlnet/xlnet-base-cased-pytorch_model.bin")
Those two command will make the problem occur.

**Comment by stefan-it** [comment]
@lipingbj With the latest versions of `transformers` you need to pass the path to the PyTorch-compatible model, so in your example use: 

```
tokenizer = BertTokenizer.from_pretrained("/home/liping/liping/bert/")
```

The following files must be located in that folder: 

* `vocab.txt` - vocabulary file
* `pytorch_model.bin` - the PyTorch-compatible (and converted) model
* `config.json` - json-based model configuration

Please make sure that these files exist and e.g. rename `bert-base-cased-pytorch_model.bin` to `pytorch_model.bin`.

That should work :)

**Comment by lipingbj** [comment]
> @lipingbj With the latest versions of `transformers` you need to pass the path to the PyTorch-compatible model, so in your example use:
> 
> ```
> tokenizer = BertTokenizer.from_pretrained("/home/liping/liping/bert/")
> ```
> 
> The following files must be located in that folder:
> 
> * `vocab.txt` - vocabulary file
> * `pytorch_model.bin` - the PyTorch-compatible (and converted) model
> * `config.json` - json-based model configuration
> 
> Please make sure that these files exist and e.g. rename `bert-base-cased-pytorch_model.bin` to `pytorch_model.bin`.
> 
> That should work :)


encoder_model = BertModel.from_pretrained("/home/liping/liping/bert/pytorch-bert-model")
    tokenizer = BertTokenizer.from_pretrained("/home/liping/liping/bert/pytorch-bert-model")

vocab.txt, pytorch_model.bin,  config.json have included in directory bert/pytorch-bert-model

**Comment by LysandreJik** [comment]
As the error says, "We assumed '/home/liping/liping/bert/pytorch-bert-model/config.json' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url."

Your data does not seem to be in "/home/liping/liping/bert/pytorch-bert-model"

**Comment by phaniram-sayapaneni** [comment]
Hello,

I'm trying to load biobert into pytorch, seeing a different error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

any hints? @LysandreJik

**Comment by khu834** [comment]
> Hello,
> 
> I'm trying to load biobert into pytorch, seeing a different error:
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
> 
> any hints? @LysandreJik

Can you show the code that you are running to load from pre-trained weights?
For example
```
model = BertForSequenceClassification.from_pretrained('/path/to/directory/containing/model_artifacts/')
```

As stafan-it mentioned above, the directory must contain the 3 required files.
