### ISSUE TITLE
How to pass args of generate() method via batch_decode

### ISSUE THREAD

**Issue by rafikg** [huggingface/transformers#16233]
I want to specify the generate params in the line below:

```
generate(tokenized_input.input_ids,
                                     max_length=64,
                                     no_repeat_ngram_size=2,
                                     early_stopping=True,
                                     num_beams=4,
                                     num_return_sequences=3)
```
https://github.com/huggingface/transformers/blob/93d3fd86459eb27bc584da29a3d542817a395bca/examples/pytorch/summarization/run_summarization.py#L662

I specified the args as following. I did not get any error, but it is still getting one sequence instead of 3 as expected.
```
batch_decode(
          predict_results.predictions,
          skip_special_tokens=True,
          early_stopping=True,
          clean_up_tokenization_spaces=False,
          no_repeat_ngram_size=2,
          num_return_sequences=3
)
```

**Comment by qqaatw** [comment]
Currently the seq2seq trainer doesn't support `num_return_sequence` argument for generation. 

You might need to tweak it here:
https://github.com/huggingface/transformers/blob/v4.17.0/src/transformers/trainer_seq2seq.py#L158-L162

**Comment by rafikg** [comment]
Thanks @qqaatw. Because batch_decode cotains **kwargs, I thought maybe I can pass them through it but it seems that is not implemented. So, in this case `Generate()` will use default values

**Comment by qqaatw** [comment]
`batch_decode` isn't responsible for generation by design, it only converts ids to tokens and does some normalizations. So passing generation-related arguments for it won't work.
