### ISSUE TITLE
Enable the use of private models in example scripts using use_auth_token

### ISSUE THREAD

**Issue by KMFODA** [huggingface/transformers#16235]
# 🚀 Feature request

Currently private models can be used with the examples scripts by setting the `use_auth_token argument` as `True` however this doesn't seem to be an option for private datasets.

## Motivation

Enabling the use of private datasets using the example scripts

## Your contribution

I'm happy to work on a PR to add this to all example scripts if this is indeed the case and I haven't missed another method for using private datasets.

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
Sure, I believe it's just a matter of passing the token in the right places :-)

**Comment by KMFODA** [comment]
Great thanks @sgugger. Will work on a PR adding those in :)
