### ISSUE TITLE
Loading from AutoModel gives ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#16234]
Executing the following code snippet states that ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds.

```py
from transformers import AutoModel, AutoTokenizer 
model_name = "castorini/t5-base-canard" 

model = AutoModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

context = '''
    Frank Zappa ||| Disbandment ||| What group disbanded ||| Zappa and the Mothers of Invention ||| When did they disband?
'''

encoded_input = tokenizer(
    context,
    padding='max_length',
    max_length=512,
    truncation=True,
    return_tensors="pt",
)
decoder_input = tokenizer(
    context,
    padding='max_length',
    max_length=512,
    truncation=True,
    return_tensors="pt",
)

encoder_output = model.generate(input_ids=encoded_input["input_ids"], decoder_input_ids=decoder_input["input_ids"])
output = tokenizer.decode(
    encoder_output[0],
    skip_special_tokens=True
)
output
```

yields this error:

```
Some weights of the model checkpoint at castorini/t5-base-canard were not used when initializing T5Model: ['lm_head.weight']
- This IS expected if you are initializing T5Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing T5Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Input length of decoder_input_ids is 512, but ``max_length`` is set to 20. This can lead to unexpected behavior. You should consider increasing ``config.max_length`` or ``max_length``.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-11-b9fe12b71812>](https://localhost:8080/#) in <module>()
     24 )
     25 
---> 26 encoder_output = model.generate(input_ids=encoded_input["input_ids"], decoder_input_ids=decoder_input["input_ids"])
     27 output = tokenizer.decode(
     28     encoder_output[0],

6 frames
[/usr/local/lib/python3.7/dist-packages/transformers/models/t5/modeling_t5.py](https://localhost:8080/#) in forward(self, input_ids, attention_mask, encoder_hidden_states, encoder_attention_mask, inputs_embeds, head_mask, cross_attn_head_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
    925         else:
    926             err_msg_prefix = "decoder_" if self.is_decoder else ""
--> 927             raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds")
    928 
    929         if inputs_embeds is None:

ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds
```

**Comment by patrickvonplaten** [comment]
The problem here is that `AutoModel` does not load the full T5 model wiht a language head. One should use `AutoModelForSeq2SeqLM` inseatd:

```py
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer 
model_name = "castorini/t5-base-canard" 

model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

context = '''
    Frank Zappa ||| Disbandment ||| What group disbanded ||| Zappa and the Mothers of Invention ||| When did they disband?
'''

encoded_input = tokenizer(
    context,
    padding='max_length',
    max_length=512,
    truncation=True,
    return_tensors="pt",
)
decoder_input = tokenizer(
    context,
    padding='max_length',
    max_length=512,
    truncation=True,
    return_tensors="pt",
)

encoder_output = model.generate(input_ids=encoded_input["input_ids"], decoder_input_ids=decoder_input["input_ids"])
output = tokenizer.decode(
    encoder_output[0],
    skip_special_tokens=True
)
output
```

This should work just fine @dxlong2000

**Comment by dxlong2000** [comment]
> The problem here is that `AutoModel` does not load the full T5 model wiht a language head. One should use `AutoModelForSeq2SeqLM` inseatd:
> 
> ```python
> from transformers import AutoModelForSeq2SeqLM, AutoTokenizer 
> model_name = "castorini/t5-base-canard" 
> 
> model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
> tokenizer = AutoTokenizer.from_pretrained(model_name)
> 
> context = '''
>     Frank Zappa ||| Disbandment ||| What group disbanded ||| Zappa and the Mothers of Invention ||| When did they disband?
> '''
> 
> encoded_input = tokenizer(
>     context,
>     padding='max_length',
>     max_length=512,
>     truncation=True,
>     return_tensors="pt",
> )
> decoder_input = tokenizer(
>     context,
>     padding='max_length',
>     max_length=512,
>     truncation=True,
>     return_tensors="pt",
> )
> 
> encoder_output = model.generate(input_ids=encoded_input["input_ids"], decoder_input_ids=decoder_input["input_ids"])
> output = tokenizer.decode(
>     encoder_output[0],
>     skip_special_tokens=True
> )
> output
> ```
> 
> This should work just fine @dxlong2000

Sure thanks @patrickvonplaten !

**Comment by aegonwolf** [comment]
> ```python
> model.generate(input_ids=encoded_input["input_ids"], decoder_input_ids=decoder_input["input_ids"])
> ```

Dear Patrick, thank you very much for all your helpful answers here on github. They've helped me so many times!

If I train a T5 model from `AutoModelForSeq2SeqLM` with my custom dataset with `Trainer`, what type of decoder input is the Trainer using?
It seems I do not have to specify, and I've tried deducing it from the source and docs but I couldn't find an answer to that.
I'd super appreciate some insights!

**Comment by Pascalsmdt** [comment]
Hi, im currently trying to export a mT5 Model to onnx using the following code: 

`
model = MT5ForConditionalGeneration.from_pretrained("./mt5_multitask_model")
model.eval()
tokenizer = MT5Tokenizer.from_pretrained("./mt5_multitask_model")


encoder_input = tokenizer("Dummy input to test the multitasking mT5 model with a maximum of 512 tokens.", 
                        return_tensors="pt", max_length=512, padding="max_length", truncation=True)
decoder_input = tokenizer("Dummy decoder input", 
                        return_tensors="pt", max_length=512, padding="max_length", truncation=True)


torch.onnx.export(
    model,
    (encoder_input['input_ids'],decoder_input['input_ids']),
    "mt5_multitask_model.onnx",
    input_names=["input_ids"],          # Eingabenamen
    output_names=["logits"],            # Ausgabename (je nach Aufgabe evtl. anpassen)
    dynamic_axes={                      # Dynamische Achsen für Batchgröße und Sequenzlänge
        "input_ids": {0: "batch_size", 1: "sequence_length"}, 
        "logits": {0: "batch_size", 1: "sequence_length"}
    },
    opset_version=13
)` 


However i'm also getting the Value Error everybody else does: 

`{
	"name": "ValueError",
	"message": "You have to specify either decoder_input_ids or decoder_inputs_embeds",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[73], line 13
      7 encoder_input = tokenizer(\"Dummy input to test the multitasking mT5 model with a maximum of 512 tokens.\", 
      8                         return_tensors=\"pt\", max_length=512, padding=\"max_length\", truncation=True)
      9 decoder_input = tokenizer(\"Dummy decoder input\", 
     10                         return_tensors=\"pt\", max_length=512, padding=\"max_length\", truncation=True)
---> 13 torch.onnx.export(
     14     model,
     15     (encoder_input['input_ids'],decoder_input['input_ids']),
     16     \"mt5_multitask_model.onnx\",
     17     input_names=[\"input_ids\"],          # Eingabenamen
     18     output_names=[\"logits\"],            # Ausgabename (je nach Aufgabe evtl. anpassen)
     19     dynamic_axes={                      # Dynamische Achsen für Batchgröße und Sequenzlänge
     20         \"input_ids\": {0: \"batch_size\", 1: \"sequence_length\"}, 
     21         \"logits\": {0: \"batch_size\", 1: \"sequence_length\"}
     22     },
     23     opset_version=13
     24 )

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\\onnx\\utils.py:506, in export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, custom_opsets, export_modules_as_functions)
    188 @_beartype.beartype
    189 def export(
    190     model: Union[torch.nn.Module, torch.jit.ScriptModule, torch.jit.ScriptFunction],
   (...)
    206     export_modules_as_functions: Union[bool, Collection[Type[torch.nn.Module]]] = False,
    207 ) -> None:
    208     r\"\"\"Exports a model into ONNX format.
    209 
    210     If ``model`` is not a :class:`torch.jit.ScriptModule` nor a
   (...)
    503             All errors are subclasses of :class:`errors.OnnxExporterError`.
    504     \"\"\"
--> 506     _export(
    507         model,
    508         args,
    509         f,
    510         export_params,
    511         verbose,
    512         training,
    513         input_names,
    514         output_names,
    515         operator_export_type=operator_export_type,
    516         opset_version=opset_version,
    517         do_constant_folding=do_constant_folding,
    518         dynamic_axes=dynamic_axes,
    519         keep_initializers_as_inputs=keep_initializers_as_inputs,
    520         custom_opsets=custom_opsets,
    521         export_modules_as_functions=export_modules_as_functions,
    522     )

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\\onnx\\utils.py:1548, in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, onnx_shape_inference, export_modules_as_functions)
   1545     dynamic_axes = {}
   1546 _validate_dynamic_axes(dynamic_axes, model, input_names, output_names)
-> 1548 graph, params_dict, torch_out = _model_to_graph(
   1549     model,
   1550     args,
   1551     verbose,
   1552     input_names,
   1553     output_names,
   1554     operator_export_type,
   1555     val_do_constant_folding,
   1556     fixed_batch_size=fixed_batch_size,
   1557     training=training,
   1558     dynamic_axes=dynamic_axes,
   1559 )
   1561 # TODO: Don't allocate a in-memory string for the protobuf
   1562 defer_weight_export = (
   1563     export_type is not _exporter_states.ExportTypes.PROTOBUF_FILE
   1564 )

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\\onnx\\utils.py:1113, in _model_to_graph(model, args, verbose, input_names, output_names, operator_export_type, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size, training, dynamic_axes)
   1110     args = (args,)
   1112 model = _pre_trace_quant_model(model, args)
-> 1113 graph, params, torch_out, module = _create_jit_graph(model, args)
   1114 params_dict = _get_named_param_dict(graph, params)
   1116 try:

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\\onnx\\utils.py:989, in _create_jit_graph(model, args)
    984     graph = _C._propagate_and_assign_input_shapes(
    985         graph, flattened_args, param_count_list, False, False
    986     )
    987     return graph, params, torch_out, None
--> 989 graph, torch_out = _trace_and_get_graph_from_model(model, args)
    990 _C._jit_pass_onnx_lint(graph)
    991 state_dict = torch.jit._unique_state_dict(model)

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\\onnx\\utils.py:893, in _trace_and_get_graph_from_model(model, args)
    891 prev_autocast_cache_enabled = torch.is_autocast_cache_enabled()
    892 torch.set_autocast_cache_enabled(False)
--> 893 trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
    894     model,
    895     args,
    896     strict=False,
    897     _force_outplace=False,
    898     _return_inputs_states=True,
    899 )
    900 torch.set_autocast_cache_enabled(prev_autocast_cache_enabled)
    902 warn_on_static_input_change(inputs_states)

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\\jit\\_trace.py:1268, in _get_trace_graph(f, args, kwargs, strict, _force_outplace, return_inputs, _return_inputs_states)
   1266 if not isinstance(args, tuple):
   1267     args = (args,)
-> 1268 outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
   1269 return outs

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\
n\\modules\\module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\\jit\\_trace.py:127, in ONNXTracedModule.forward(self, *args)
    124     else:
    125         return tuple(out_vars)
--> 127 graph, out = torch._C._create_graph_by_tracing(
    128     wrapper,
    129     in_vars + module_state,
    130     _create_interpreter_name_lookup_fn(),
    131     self.strict,
    132     self._force_outplace,
    133 )
    135 if self._return_inputs:
    136     return graph, outs[0], ret_inputs[0]

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\\jit\\_trace.py:118, in ONNXTracedModule.forward.<locals>.wrapper(*args)
    116 if self._return_inputs_states:
    117     inputs_states.append(_unflatten(in_args, in_desc))
--> 118 outs.append(self.inner(*trace_inputs))
    119 if self._return_inputs_states:
    120     inputs_states[0] = (inputs_states[0], trace_inputs)

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\
n\\modules\\module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\
n\\modules\\module.py:1488, in Module._slow_forward(self, *input, **kwargs)
   1486         recording_scopes = False
   1487 try:
-> 1488     result = self.forward(*input, **kwargs)
   1489 finally:
   1490     if recording_scopes:

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\transformers\\models\\mt5\\modeling_mt5.py:1769, in MT5ForConditionalGeneration.forward(self, input_ids, attention_mask, decoder_input_ids, decoder_attention_mask, head_mask, decoder_head_mask, cross_attn_head_mask, encoder_outputs, past_key_values, inputs_embeds, decoder_inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict)
   1766         decoder_attention_mask = decoder_attention_mask.to(self.decoder.first_device)
   1768 # Decode
-> 1769 decoder_outputs = self.decoder(
   1770     input_ids=decoder_input_ids,
   1771     attention_mask=decoder_attention_mask,
   1772     inputs_embeds=decoder_inputs_embeds,
   1773     past_key_values=past_key_values,
   1774     encoder_hidden_states=hidden_states,
   1775     encoder_attention_mask=attention_mask,
   1776     head_mask=decoder_head_mask,
   1777     cross_attn_head_mask=cross_attn_head_mask,
   1778     use_cache=use_cache,
   1779     output_attentions=output_attentions,
   1780     output_hidden_states=output_hidden_states,
   1781     return_dict=return_dict,
   1782 )
   1784 sequence_output = decoder_outputs[0]
   1786 # Set device for model parallelism

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\
n\\modules\\module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\torch\
n\\modules\\module.py:1488, in Module._slow_forward(self, *input, **kwargs)
   1486         recording_scopes = False
   1487 try:
-> 1488     result = self.forward(*input, **kwargs)
   1489 finally:
   1490     if recording_scopes:

File c:\\workspace\\databricks-notebooks-017\\.venv\\lib\\site-packages\\transformers\\models\\mt5\\modeling_mt5.py:995, in MT5Stack.forward(self, input_ids, attention_mask, encoder_hidden_states, encoder_attention_mask, inputs_embeds, head_mask, cross_attn_head_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
    993 else:
    994     err_msg_prefix = \"decoder_\" if self.is_decoder else \"\"
--> 995     raise ValueError(f\"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds\")
    997 if inputs_embeds is None:
    998     if self.embed_tokens is None:

ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds"
}`  

would be nice if someone can help!
