### ISSUE TITLE
ViT-mae missing parameter at comments of `copied  from`

### ISSUE THREAD

**Issue by johnnv1** [huggingface/transformers#16251]
### Who can help
@NielsRogge

## Information
As describe in #16151

When i was type annotating the ViT model, i get some problem when running `make fix-copies` for vit-mae. When i annotated the cofig parameter at ViT, and run  `make fix-copies` the script fix at deit model (update the type annotation to Deit config), but at vit-mae he just copied the type annotation of ViT config.

This seems to be because don't have with ViT->VitMAE at the end of the “Copied from …” comment in vit_mae model;

But I don't know if this annotation is really missing, or it was supposed to be this way

## To reproduce

1. Add type annotation at ViTSelfAttention src/transformers/models/vit/modeling_vit.py
2. run `git diff`
```diff
--- a/src/transformers/models/vit/modeling_vit.py
+++ b/src/transformers/models/vit/modeling_vit.py
@@ -192,7 +192,7 @@ class PatchEmbeddings(nn.Module):
 
 
 class ViTSelfAttention(nn.Module):
-    def __init__(self, config) -> None:
+    def __init__(self, config: ViTConfig) -> None:
         super().__init__()

```

3. Run `make fix-copies`
4. Run `git diff src/transformers/models/vit_mae/`
```diff
@@ -318,7 +318,7 @@ class PatchEmbeddings(nn.Module):
 
 # Copied from transformers.models.vit.modeling_vit.ViTSelfAttention
 class ViTMAESelfAttention(nn.Module):
-    def __init__(self, config) -> None:
+    def __init__(self, config: ViTConfig) -> None:
```

## Expected behavior
I was expecting 

```diff
@@ -318,7 +318,7 @@ class PatchEmbeddings(nn.Module):
 
 # Copied from transformers.models.vit.modeling_vit.ViTSelfAttention
 class ViTMAESelfAttention(nn.Module):
-    def __init__(self, config) -> None:
+    def __init__(self, config: ViTMAEConfig) -> None:
```

This can be fixed with 

```diff
@@ -316,9 +316,9 @@ class PatchEmbeddings(nn.Module):
         return x
 

-# Copied from transformers.models.vit.modeling_vit.ViTSelfAttention
+# Copied from transformers.models.vit.modeling_vit.ViTSelfAttention ViT->VitMAE
```

But I don't know if this annotation is really missing, or it was supposed to be this way

**Comment by NielsRogge** [comment]
Hey,

Yeah you add the with ViT->ViTMAE if you need to.
