### ISSUE TITLE
Typo: Missing a coma in document

### ISSUE THREAD

**Issue by PolarisRisingWar** [huggingface/transformers#16277]
In `https://huggingface.co/docs/transformers/master/en/task_summary#extractive-question-answering`, this sentence:
![image](https://user-images.githubusercontent.com/48322321/159153847-6a1bcd93-855b-4425-9716-fd1a576068ea.png)
Should it be `model-specific separators, token type ids and attention masks`?

**Comment by gante** [comment]
Thank you for flagging this typo 👍  Would you like to open a PR with the fix, @PolarisRisingWar? (source file [here](https://github.com/huggingface/transformers/blob/master/docs/source/task_summary.mdx)) 

If not, I can take care of it :)
