### ISSUE TITLE
cannot import name 'RobertaForTokenClassification'

### ISSUE THREAD

**Issue by dsindex** [huggingface/transformers#1631]
## 🐛 Bug

Model I am using (Bert, XLNet....): BERT

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [x] the official example scripts: (give details) examples/run_ner.py
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name) NER on CoNLL2003 ENG
* [ ] my own task or dataset: (give details)

## To Reproduce

1. $ pip install transformers
2. $ python
3. > from transformers import RobertaConfig, RobertaForTokenClassification, RobertaTokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RobertaForTokenClassification'

## Environment

* OS: Ubuntu 18.04.3
* Python version: 3.6
* PyTorch version: 1.2.0
* PyTorch Transformers version (or branch): pip install transformers
* Using GPU ? Yes, CUDA 10
* Distributed of parallel setup ? No
* Any other relevant information:

**Comment by dsindex** [comment]
+ other bug
  - with '--evaluate_during_training'
```
File "/path-to/run_ner.py", line 167, in train
    results, _ = evaluate(args, model, tokenizer, labels, pad_token_label_id)
TypeError: evaluate() missing 1 required positional argument: 'mode'
```

**Comment by dsindex** [comment]
- update
  - using `pip3 install git+https://github.com/huggingface/transformers.git --upgrade` command, the first bug got away.

**Comment by mohitsewak** [comment]
I am also facing the same issue, but even installing from git (as stated by dsindex) did not help.

**Comment by jyoti-peakon** [comment]
It could be because torch is not installed. transformers doesn't install torch automatically but needs the same to load the models. try `pip install torch` and import again!

**Comment by robertour** [comment]
I am having the same issue, neither installing from git, nor `pip install torch` have fixed the issue

**Comment by LysandreJik** [comment]
Could you provide your software versions, by running `transformers-cli env` in your environment?
