### ISSUE TITLE
ibert seems to be quite slow in quant_mode = True

### ISSUE THREAD

**Issue by ontocord** [huggingface/transformers#16319]
Hi, for iBert - 

I found it is MUCH slower in quant_mode = True. here's a notebook with a slightly modified version of the HF code to allow dynamically switching quant_mode. You can see the timing difference.

https://colab.research.google.com/drive/1DkYFGc18oPvAn5nyGEL1aIFHmD_aNlXW

 @patrickvonplaten

https://github.com/kssteven418/I-BERT/issues/21

**Comment by patrickvonplaten** [comment]
Hey @ontocord,

I don't have much experience with iBERT. @kssteven418 any ideas here? Is such a slowdown expected?
