### ISSUE TITLE
Implement HybridNets: End-to-End Perception Network

### ISSUE THREAD

**Issue by chainyo** [huggingface/transformers#16325]
# 🌟 New model addition

## Model description

Quote from the Github repository:

```markdown
HybridNets is an end2end perception network for multi-tasks.    
Our work focused on traffic object detection, drivable area segmentation and lane detection.   
HybridNets can run real-time on embedded systems, and obtains SOTA Object Detection, 
Lane Detection on BDD100K Dataset.
```

## Open source status

* [x] the model implementation is available: yes, they have pushed everything [here](https://github.com/datvuthanh/HybridNets) on Github
* [x] the model weights are available: yes, there are available directly [here](https://github.com/datvuthanh/HybridNets/releases/download/v1.0/hybridnets.pth) on Github.
* [x] who are the authors: Dat Vu  and Bao Ngo and Hung Phan (@xoiga123 @datvuthanh)

Btw, I would love to help to implement this kind of models to the Hub if possible :hugs: .
But I don't know if it fits to `Transformers` library or not and if it involves a lot of work to implement it, but I want to try to help!

**Comment by patil-suraj** [comment]
cc @NielsRogge
