### ISSUE TITLE
Can we support the trace of ViT and Swin-Transformer based on torch.fx?

### ISSUE THREAD

**Issue by maggiez0138** [huggingface/transformers#16320]
# 🚀 Feature request

Can we support the trace of ViT and Swin-Transformer based on torch.fx()? If not, what's the difficulty for that?

## Motivation

ViT and Swin-Transformation is widely used in CV scenarios. Hope we could support the trace of torch.fx, so we can do the quantization based on the work.

## Your contribution

I'm not sure right now. Currently I wanda whether we could support the ViT and Swin-Transformer. If not, the reason.

**Comment by maggiez0138** [comment]
@michaelbenayoun   May I know the current situation or your schedule first? Thanks.

**Comment by michaelbenayoun** [comment]
Hi, 
The plan is to work on a nicer solution for tracing the model as soon as possible.
I will take a look to add those models in the mean time as they might not be hard to add in the current setting.
