### ISSUE TITLE
The huggingface web site crashed

### ISSUE THREAD

**Issue by mokeyish** [huggingface/transformers#16351]
<img width="800" src="https://user-images.githubusercontent.com/16131917/159614484-741db4c9-5c60-442a-8df2-efa39869369d.png">

**Set `local_files_only` to be True for reading the local cache first。**

```python
tokenizer = BertTokenizer.from_pretrained(tokenizer_config.model_path, local_files_only=True)
```

# Is there any mirror of this web site?

**Comment by czb2133** [comment]
yes, and I couldn't use from_pretrained() in my code

**Comment by hezhaozhao-git** [comment]
+1

**Comment by Subhojyoti22** [comment]
+1

**Comment by sindhura97** [comment]
+1

**Comment by ytf-philp** [comment]
+1

**Comment by ArvinZhuang** [comment]
+1

**Comment by guoaokiral** [comment]
+2

**Comment by ravindra-ut** [comment]
+1

**Comment by sindhura97** [comment]
+1

**Comment by Legend94rz** [comment]
How to prevent Tokenizer/Model from requesting Internet when local cache is available? Force HuggingFace read the local cache first?

**Comment by z-bookworm** [comment]
> How to prevent Tokenizer/Model from requesting Internet when local cache is available? Force HuggingFace read the local cache first?

You can set `local_files_only ` to be True.

```python
tokenizer = BertTokenizer.from_pretrained(tokenizer_config.model_path, local_files_only=True)
```

**Comment by Subhojyoti22** [comment]
@z-bookworm Thanks it worked.

**Comment by ALixuhui** [comment]
+1

**Comment by hxxxxh** [comment]
+1

**Comment by JFChi** [comment]
+1

**Comment by julien-c** [comment]
Sorry about that! 
See this tweet for some context on our work on Hub scalability and performance: https://twitter.com/julien_c/status/1496129354023288838

Will close this issue for now, thanks for reporting 🙏
