### ISSUE TITLE
question about the the specific text generation question

### ISSUE THREAD

**Issue by shaoniana1997** [huggingface/transformers#16364]
Hello, i am a tiro in transformers, and i have a question.
if i want to use serval concepts like:  I question english ,and i want to the output like this: i have a english question, or i have a question rather than english question.
Does any project in the hub can handle this? If not ,can you give me some useful advice about how to use the current model and modify it to finish my above mentioned question?
Thank you very much

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
