### ISSUE TITLE
when I using pytorch to load "distilbert-base-uncased", it's get an error:"HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/distilbert-base-uncased/resolve/main/vocab.txt". But load other models can't get this error. 

### ISSUE THREAD

**Issue by ayispace** [huggingface/transformers#16379]
## Environment info

- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by Joyrocky** [comment]
To see #16351

**Comment by ayispace** [comment]
> To see #16351

thank you

**Comment by julien-c** [comment]
Closing this for now 🙏
