### ISSUE TITLE
Cache the files in get_fast_tokenizer_file()

### ISSUE THREAD

**Issue by AnthonyBarbier** [huggingface/transformers#16382]
# 🚀 Feature request

`transformers.BertTokenizer.from_pretrained()` calls `get_fast_tokenizer_file()` which downloads a file from the HuggingFace server but never adds it to the cache.

Would be useful to cache that file (in the same folder as the models) to make CI runs more robust.

## Motivation

Try to avoid having issues such as the one below in our CI runs:
```
E           requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/models/mrm8488/bert-small-finetuned-squadv2
```

This is a duplicate of https://github.com/huggingface/transformers/issues/14862 which was closed without getting fixed and I don't seem able to re-open it.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! This should be fixed by https://github.com/huggingface/transformers/pull/16362 which should drop in the next release.

**Comment by LysandreJik** [comment]
Closing for now, feel free to reopen if it doesn't solve your issue.
