### ISSUE TITLE
Unable to install transformers & its related dependencies due Issue with Python Versions

### ISSUE THREAD

**Issue by robotjellyzone** [huggingface/transformers#16404]
## Environment info

- `transformers` version: NA
- Platform: Windows 10 (64 bit)
- Python version: 3.6 / 3.10
- PyTorch version (GPU?): NA
- Tensorflow version (GPU?): NA
- Using GPU in script?: NA
- Using distributed or parallel set-up in script?: NA

### Who can help
@gante @Rocketknight1 

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: Following the contribution guidelines wherein its written to run command - `pip install -e ".[dev]"`  inside a virtual environment
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: The task was to add type hints & decorators for the various models [part of code cleanup 2022]
* [ ] my own task or dataset: (give details below)

## To reproduce

1.  Create a virtual environment with python version 3.10 (latest) or with 3.6 .
2.  Install the required dependencides mentioned in setup.py file via command - `pip install -e ".[dev]"` 
3.  During installation it gives out this error -> 
![image](https://user-images.githubusercontent.com/36916536/160109627-df2f7bf1-a9b1-40e3-a4eb-2e29cee481f3.png)
 which causes no further installation of any dependencies ie transformer was not installed.

## Expected behavior
On running the pip install command every dependency along with transformers should get install completely with the python version 3.6 or 3.10 as in the setup.py file its mentioned `python>=3.6.0`  but still it didnt work with 3.6/3.10 versions
![image](https://user-images.githubusercontent.com/36916536/160110165-99771a4c-9b67-4461-b44c-08f2ce6a6b96.png)

**Note** :- But I was able to install all the dependencies completely & smoothly with **`python version 3.8`**

**Comment by gante** [comment]
cc @ydshieh -- @robotjellyzone was the user I mentioned yesterday, that had the installation uses. It seems like we have related problems for python 3.6 and 3.10 :(

**Comment by robotjellyzone** [comment]
is this issue resolved or is it just fine to let it as it is in a close state? @gante @ydshieh

**Comment by ydshieh** [comment]
Hi, @robotjellyzone 

- Python 3.6 will be dropped over the next few weeks: #16832
- And as far as I know, `ray` still doesn't support Python 3.10 (yet). See https://github.com/ray-project/ray/pull/21221

I believe closing this issue is reasonable.

**Comment by robotjellyzone** [comment]
> Hi, @robotjellyzone
> 
> * Python 3.6 will be dropped over the next few weeks: [Dropping support for Python 3.6 #16832](https://github.com/huggingface/transformers/issues/16832)
> * And as far as I know, `ray` still doesn't support Python 3.10 (yet). See [Add support for Python 3.10 ray-project/ray#21221](https://github.com/ray-project/ray/pull/21221)
> 
> I believe closing this issue is reasonable.

Oh Great! if python 3.6 will be dropped then i guess everything will be fine but then it needs to be mentioned in the setup file as well so that others can use versions greater than 3.6. 
so shall i create a pr for changing the version mentioned in the setup.py file?

**Comment by ydshieh** [comment]
Hi, @robotjellyzone Thank you for the offer. But we will do this when v4.19.0 is released. Currently we are still in v4.18.0 release, and we can't change setup.py before we officially drop it :-)

**Comment by krishnacloud77** [comment]
i have an issue with installing transformers using packer. Can someone help me with transformers not getting installed ?

      "inline": [
        "python3 -m venv .env",
        "source .env/bin/activate",
        "source activate tensorflow2_p38",
        "pip install --upgrade pip",
        "pip install transformers",
        "pip install torch",
        "pip install tensorflow-gpu==2.7.0"
      ],
      "type": "shell"
    },

**Comment by gante** [comment]
Hi @krishnacloud77 👋  Reading above, it seems like you are activating two python environments (assuming `tensorflow2_p38` is a python environment) -- try using only one of them. Also, I'd recommend installing TF and PT from the extras, i.e. `pip install transformers[tf,torch]`

**Comment by krishnacloud77** [comment]
Hi gante

> Hi @krishnacloud77 👋 Reading above, it seems like you are activating two python environments (assuming `tensorflow2_p38` is a python environment) -- try using only one of them. Also, I'd recommend installing TF and PT from the extras, i.e. `pip install transformers[tf,torch]`

Hi gante
still issue not resolved after removing one venv.

      "inline": [
        "python3 -m venv",
        "source .venv/bin/activate",
        "source activate tensorflow2_p38",
        "pip install  --upgrade pip",
        "pip install transformers[tf,torch]",
        "pip install torch",
        "pip install --user tensorflow-gpu==2.7.0"
      ],
      "type": "shell"
    },

**Comment by gante** [comment]
The series of commands above is still activating two environments, and it's also installing torch and tensorflow externally. Try this:

```
    "source activate tensorflow2_p38",
    "pip install  --upgrade pip",
    "pip install transformers[tf,torch]",
```

**Comment by krishnacloud77** [comment]
I have tried those commands already. Amazon ebs error. Says source activate command not found. This is getting installed through packer, to build an AMI.
