### ISSUE TITLE
Providing a easier way to download pre-trained models.

### ISSUE THREAD

**Issue by zhaowei-wang98** [huggingface/transformers#16420]
# 🚀 Feature request
I tried to download T5-base manually because of my special environment. I tried to git clone T5-base from https://huggingface.co/t5-base. The model in PyTorch (which I am using) is only about 800M. However, I need to download files used in other DL frameworks (like TensorFlow). Also, I need to download the git files (.git directory). Finally, I need to download about 7G files, which is much larger than the model itself.

So, could there be a way to manually download pre-trained models in a specific DL framework only?

## Motivation
I need to download much more files than the model itself, which is too slow

**Comment by julien-c** [comment]
@LysandreJik is 100% right, or an alternative if it's just a one-off download is you could just download individual files from the `Files and versions` tab (note that depending on your browser you might need to rename the files):

<img width="1833" alt="Screenshot 2022-03-28 at 12 04 16" src="https://user-images.githubusercontent.com/326577/160375553-4f920b72-8644-4300-a0b6-d782b0bafd91.png">

**Comment by zhaowei-wang98** [comment]
Thank you guys a lot!
