### ISSUE TITLE
Add TF implementation of XGLM model

### ISSUE THREAD

**Issue by stancld** [huggingface/transformers#16422]
# 🚀 Feature request

Add TF implementation of XGLM model

## Motivation

Narrow the gap between PT and TF implementations.

## Your contribution

I'd like to work on this.

**Comment by patil-suraj** [comment]
Thanks a lot for willing to work on this, happy to help with it :)

**Comment by stancld** [comment]
Still active

**Comment by stancld** [comment]
still active
