### ISSUE TITLE
How can I use MLM and NSP to train Bert from scratch?

### ISSUE THREAD

**Issue by onlyonewater** [huggingface/transformers#16440]
How can I use MLM and NSP to train Bert from scratch?

**Comment by NielsRogge** [comment]
Hi,

I've answered this question on Stackoverflow [here](https://stackoverflow.com/questions/65646925/how-to-train-bert-from-scratch-on-a-new-domain-for-both-mlm-and-nsp/65760008#65760008).

**Comment by onlyonewater** [comment]
OK, thanks!!!
