### ISSUE TITLE
How can i train wav2vec2 with my dataset?

### ISSUE THREAD

**Issue by ddoron9** [huggingface/transformers#16443]
# 🚀 Feature request

i wonder how to preprocess it

**Comment by NielsRogge** [comment]
Hi,

We do have several blog posts on that:

* Fine-Tune Wav2Vec2 for English ASR with 🤗 Transformers: https://huggingface.co/blog/fine-tune-wav2vec2-english
* Fine-tuning XLS-R for Multi-Lingual ASR with 🤗 Transformers: https://huggingface.co/blog/fine-tune-xlsr-wav2vec2
