### ISSUE TITLE
Is there a possible way to moniter the realtime training  in the example?

### ISSUE THREAD

**Issue by Gare-Ng** [huggingface/transformers#16442]
In the `transformers/examples/pytorch/translation/run_translation.py`, it seems it only produce `the runs` log file after stopping training. Is it possible to generate the runs log while training through certain steps in that script? I fail to see any readme talk about it. Any advice will be appreciated.

**Comment by patil-suraj** [comment]
Hi, please consider using the forum to ask such general questions as we use issues for for bug reports and feature requests, thanks!

The `Trainer` should automatically log during training, you can control the logging using `--logging_strategy` and `--logging_steps` argument. You can also use TensorBoard or w&B for logging, refer to this [doc](https://github.com/huggingface/transformers/tree/main/examples/pytorch#logging--experiment-tracking).

**Comment by Gare-Ng** [comment]
Thank you, I will use forum in the future.😊
