### ISSUE TITLE
How to improve accuracy (Model on TrOCR)

### ISSUE THREAD

**Issue by C108152117** [huggingface/transformers#16458]
I use TrOCR model to generate the math expression LATEX sequence according to the handwritten math expression image .
but the consequences are unsatisfactory ;below are eval/loss 、train loss and the repository :https://github.com/win5923/TrOCR-Handwritten-Mathematical-Expression-Recognition
![image](https://user-images.githubusercontent.com/101984630/160461914-30724c88-5984-4a76-bc3d-782499867406.png)
![image](https://user-images.githubusercontent.com/101984630/160461972-6c8c7161-7e51-4996-8412-c593a55b1612.png)
![image](https://user-images.githubusercontent.com/101984630/160463995-cde3ef6a-5912-4b2d-b1c5-01728efe009a.png)

![image](https://user-images.githubusercontent.com/101984630/160463408-93be2dd2-29c9-4e2e-911b-707fb0d9f3c0.png)
I use CROHME 2014 to test this model but worse than above image's models

**Comment by ekdma7077** [comment]
Not exactly, but i think your pretrained_model's tokenizer is not optimized your math latex. so 

you should use trained latex tokenizer.
find it or collect latex data and create a new tokenizer using sentencepiece

**Comment by BizmanSS** [comment]
does training a new tokenizer not mess with the pretrained weights? since they use a specific tokenizer.
