### ISSUE TITLE
Export longformer to ONNX

### ISSUE THREAD

**Issue by anasilvasd** [huggingface/transformers#16463]
Hi :) I need to convert a pre-trained pytorch model to tensorflow 2. I'm trying to follow these instructions https://huggingface.co/docs/transformers/serialization#exporting-a-model-to-onnx (export to onnx first).

But I'm having this error:

KeyError: "longformer is not supported yet. Only ['albert', 'bart', 'mbart', 'bert', 'ibert', 'camembert', 'distilbert', 'marian', 'm2m-100', 'roberta', 't5', 'xlm-roberta', 'gpt2', 'gpt-neo', 'layoutlm', 'electra'] are supported. If you want to support longformer please propose a PR or open up an issue."

Is it possible to add support to longformer, please? Thanks

**Comment by ChainYo** [comment]
> Is it possible to add support to longformer, please? Thanks

Hey @anasilvasd we have created a group recently that aims to add ONNX support for all models on the hub. Maybe you could help us by doing the implementation yourself?

Here is the link of the issue relating all the models that need help #16308
And here is the HF org if you want to join us: [ONNXConfig for all][https://huggingface.co/OWG)
