### ISSUE TITLE
distilroberta-base unavailable in pip install transformers

### ISSUE THREAD

**Issue by duyvuleo** [huggingface/transformers#1647]
## ❓ Questions & Help

Hi,

Would you please update the `pip install transformers` with the addition of `distilroberta-base`? 

As of 28 Nov 2019, I tried `pip install transformers` or `pip install --upgrade transformers` but the `distilroberta-base` model is not available. But I can see it from the master branch and if I install it from source, it will work btw. 

Thanks!

**Comment by julien-c** [comment]
Yes, we should push a new pip release this coming week. In the meantime please use master.
