### ISSUE TITLE
ALBERT

### ISSUE THREAD

**Issue by duyvuleo** [huggingface/transformers#1649]
# 🌟New model addition

## Model description

ALBERT is "A Lite" version of BERT, a popular unsupervised language representation learning algorithm. ALBERT uses parameter-reduction techniques that allow for large-scale configurations, overcome previous memory limitations, and achieve better behavior with respect to model degradation.

For a technical description of the algorithm, see our paper:

ALBERT: A Lite BERT for Self-supervised Learning of Language Representations

Zhenzhong Lan, Mingda Chen, Sebastian Goodman, Kevin Gimpel, Piyush Sharma, Radu Soricut

## Open Source status

* [ ] the model implementation is available: https://github.com/google-research/google-research/tree/master/albert.

I just want to ask whether you guys have plan to add ALBERT in near future.

**Comment by thomwolf** [comment]
Merging with #1370
