### ISSUE TITLE
Script to convert huggingface models to deepspeed/megatron checkpoints

### ISSUE THREAD

**Issue by ShivamSharma2705** [huggingface/transformers#16504]
Do we have a script to convert the huggingface pretrained models on the server to deepspeed/megatron style model checkpoints?

**Comment by stas00** [comment]
We don't at the moment. You can probably try to reverse the existing conversion scripts.

@tjruwase (Deepspeed) has been working on doing various conversions between Meg-LM, Meg-DS and HF Transformers:
https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/239
so perhaps it'd fit there the best, but it's a slow going, as we keep asking Tunji to work on other things every time we try to go back to work on the checkpoints

**Comment by lulia0228** [comment]
how to convert llama2 hf format model to megatron-ds format?
