### ISSUE TITLE
Missing required argument 'mode' in run_ner.

### ISSUE THREAD

**Issue by apohllo** [huggingface/transformers#1652]
## 🐛 Bug

Model I am using: BERT

Language I am using the model on: Polish (irrelevant for the error)

The problem arise when using:
* [x] the official example scripts: run_ner.py

The tasks I am working on is:
* [x] my own task or dataset: token classification (aka NER)

## To Reproduce

1. Start run_ner.py with --evaluate_during_training
2. During evaluation the error will happen

## Expected behavior

Evaluation should run fine

## Additional context

There is a missing argument in line 156 `mode`, which (I belive) should be `"dev"`.
I can provide a PR if the above solution is confirmed.

**Comment by thomwolf** [comment]
yes sure, happy to welcome a PR on this
