### ISSUE TITLE
Can I load a CTRL model that was fine-tuned using the Salesforce code?

### ISSUE THREAD

**Issue by orenmelamud** [huggingface/transformers#1654]
## ❓ Questions & Help

I have a custom CTRL model that I trained using the Salesforce TF code and I was hoping that I could convert it into the transformers format and load it there. Any advice?

**Comment by julien-c** [comment]
cc @keskarnitish :)

**Comment by orenmelamud** [comment]
Thanks  @keskarnitish! That would be great!

**Comment by julien-c** [comment]
That is awesome @keskarnitish! We'll add it to our doc here as well.
