### ISSUE TITLE
Missing a line in examples/distillation/README.md

### ISSUE THREAD

**Issue by jianwolf** [huggingface/transformers#1655]
In How to train Distil* -> B, in both of the training commands, you should add `--alpha_clm 0.0 \`, otherwise an assertion error will be triggered (https://github.com/huggingface/transformers/blob/079bfb32fba4f2b39d344ca7af88d79a3ff27c7c/examples/distillation/train.py#L49).

**Comment by VictorSanh** [comment]
Oh yes indeed. Let me correct it. Thank you for pointing that out @jianwolf!
