### ISSUE TITLE
Force Alignment with Wav2Vec2 models

### ISSUE THREAD

**Issue by arijitx** [huggingface/transformers#16570]
# 🚀 Feature request

Most TTS acoustic models like FastSpeech, FastPitch requires duration of each phonemes or characters while training. In some cases there are force alignment models and aligners available for some languages, but most languages don't have one. leveraging the wav2vec model for force alignment [Forcelignment with wav2vec2](https://pytorch.org/audio/main/tutorials/forced_alignment_tutorial.html) . ASR models from [Robust Speech Challenge](https://huggingface.co/models?other=robust-speech-event) can be used for this.

## Motivation

Making it easy to force align for low resource languages 

## Your contribution

I can contribute by writing a method to force align using wav2vec2 models following the above mentioned pytorch tutorial.

**Comment by patrickvonplaten** [comment]
I fully agree and I think it would be great if we could add a code snippet such as the one you mention to `transformers`. I think the place for now should be here: https://github.com/huggingface/transformers/tree/main/examples/research_projects/wav2vec2 - maybe we could add a `alignment.py` file there? 

More than happy to help if you want to give it a try :-)
