### ISSUE TITLE
How to fine-tune the models on huggingface hub with run_mlm.py

### ISSUE THREAD

**Issue by ralgond** [huggingface/transformers#16576]
Say I have a corpus, I want to use it to fine-tune a model which is on huggingface hub, How should I do?

Thanks.

**Comment by gante** [comment]
Hi @ralgond 👋 Our documentation probably has the information you need, check [this page](https://huggingface.co/docs/transformers/main/en/training#finetune-a-pretrained-model) (for instance). The documentation is searchable, try looking for the keywords related to your problem. Alternatively, in the `run_mlm.py` script, try running with `--help` to have a description of the arguments. I hope this helps! :D 

We also reserve these GitHub issues for bugs in the repository and/or feature requests. For any other requests, we'd like to invite you to use our [forum](https://discuss.huggingface.co/) 🤗 I'm closing this issue, but feel free to reopen with queries that fit the criteria I described.
