### ISSUE TITLE
How to fine tune xlm-mlm-100-128 model.

### ISSUE THREAD

**Issue by Radeeswar** [huggingface/transformers#1658]
## ❓ Questions & Help

How to fine tune xlm-mlm-17-128 model for own dataset. Since, run_lm_finetuning.py has no option to fine tune XLM models.

**Comment by LysandreJik** [comment]
If you're looking to fine-tune it on an MLM task you could simply re-use some parts of the `run_lm_finetuning.py` script to do it.
