### ISSUE TITLE
Only get generated text from Bart Generate

### ISSUE THREAD

**Issue by musitafa0032** [huggingface/transformers#16598]
I know Bart can be used to fill in Multi masked tokens with only one [mask], but how can I only get filled in /generated text, not the whole sentence! If it is single token, I can figure it out, but how do I get span of text for multi masked tokens.

Thank you!

**Comment by patil-suraj** [comment]
Hi @musitafa0032 ! The best place to ask this question would the [forum](https://discuss.huggingface.co/). We use issues for bug reports and feature requests. Thanks!
