### ISSUE TITLE
Convert PyTorch Model to Hugging Face model

### ISSUE THREAD

**Issue by Freemanlabs** [huggingface/transformers#16603]
I have looked at many resources but I still seem to have issues/
I have a "model.pt" file which I got from finetuning a BERT model (with additional custom layesr added). I want to upload this to the hugging face hub. How can I convert the `.pt` model to files/model that can be used on hugging face hub?

**Comment by patil-suraj** [comment]
Hi, we have guide which explains how to share custom PT models:, which should help with this. https://huggingface.co/docs/transformers/custom_models

**Comment by Freemanlabs** [comment]
Thank s for your response. However, I do not seem to grasp the resource. It looks like it requires implementing the code from the start. In my own case, I already have a `.pt` file.

I am not sure what part of the docs handles this.

I will appreciate any further help.

**Comment by patil-suraj** [comment]
Hi @Freemanlabs , it would be best to use the [forum](https://discuss.huggingface.co/) for this question. We use issues for bug reports and feature requests. Thanks!

**Comment by zeke-john** [comment]
@Freemanlabs @patil-suraj Were you able to Convert a PyTorch Model (model.pt) to Hugging Face model? I am also trying to also do the same thing, and If so, i would appreciate any help.
