### ISSUE TITLE
version 4.2.0 vs newer version

### ISSUE THREAD

**Issue by PNMinh286** [huggingface/transformers#16601]
I have this problem with ver 4.2.0+ but is ok for under ver. Can anyone help me because other parts of my project were used ver 4.10+
![image](https://user-images.githubusercontent.com/75312938/161733457-088d19fd-4176-4c5c-902c-169efefca361.png)

**Comment by gante** [comment]
Hi @PNMinh286 👋   The information you provided is not enough for us to help you, as we don't know exactly what you're to do :) Ideally, a script with which we can reproduce the issue should be provided. Have a look at our [issue guidelines](https://github.com/huggingface/transformers/blob/main/ISSUES.md).
