### ISSUE TITLE
How to fine-tune CTRL?

### ISSUE THREAD

**Issue by zhongpeixiang** [huggingface/transformers#1660]
How to fine-tune CTRL on a custom dataset with custom control codes using the transformers package?

I'm aware of the [guide](https://github.com/salesforce/ctrl/tree/master/training_utils) for tensorflow users. However, as a PyTorch user, the guide is not friendly to me. 

I'm also aware of the language modelling fine-tuning script [here](https://github.com/huggingface/transformers/blob/master/examples/run_lm_finetuning.py). However, it does not support CTRL right now.

Thanks,
Peixiang

**Comment by saippuakauppias** [comment]
@zhongpeixiang do you have any info about finetuning ctrl?

**Comment by zhongpeixiang** [comment]
@saippuakauppias No, in the end I chose the original CTRL repo from Salesforce to finetune.

**Comment by ludoro** [comment]
Hey @zhongpeixiang, could you share some more information on how you fine-tuned the CTRL? I am also struggling to fine tune it using transformers.

**Comment by zhongpeixiang** [comment]
@ludoro I followed this repo to fine-tune the CTRL: https://github.com/salesforce/ctrl

**Comment by HadasKedem** [comment]
also struggling through the fine-tuning of CTRL, if someone can show a notebook or just the code to do that, it will help a lot!

**Comment by dheerajiiitv** [comment]
> also struggling through the fine-tuning of CTRL, if someone can show a notebook or just the code to do that, it will help a lot!

https://github.com/salesforce/ctrl/tree/master/training_utils
