### ISSUE TITLE
BERT multi heads attentions

### ISSUE THREAD

**Issue by alshahrani2030** [huggingface/transformers#1661]
Hello,
I would like to analysis the effect of specific heads' attention.
Is it possible to turn off some heads attentions in a particular layer?
if yes, can you please tell me how to do that or share any helpful document? 

Thank you in advance

**Comment by stefan-it** [comment]
I think the [BERTology](https://huggingface.co/transformers/bertology.html) section could help, especially the [run_bertology.py](https://github.com/huggingface/transformers/blob/master/examples/run_bertology.py) script can perform pruning and includes other useful functions :)
