### ISSUE TITLE
Fill-in-the-Blank Text Generation of T5

### ISSUE THREAD

**Issue by yananchen1989** [huggingface/transformers#16613]
Hello, any guys know how to implement the `Fill-in-the-Blank Text Generation` of T5 in this post: https://ai.googleblog.com/2020/02/exploring-transfer-learning-with-t5.html

Is there any demo codes in huggingface transformers to do this ?

Thanks.

**Comment by jbmaxwell** [comment]
I'm wondering the same. I've got pretraining going with the `run_t5_mlm_flax.py` script, which is great(!), but help with fill-in-the-blank generation is my next step.
