### ISSUE TITLE
ModelForSequenceClassification (Roberta/Bert) don't support mean_pool

### ISSUE THREAD

**Issue by gpucce** [huggingface/transformers#16651]
# 🚀 Feature request

I hope I did not miss it, but it looks like there is no way to use `RobertaForSequenceClassification` or `BertForSequenceClassification` with mean_pool rather than `[CLS]` or `<s>` tokens as pooler. 

## Motivation

It would be useful for benchmarking and in some cases it can work better than the start of sequence token I believe?

## Your contribution

I can try to make the PR if it makes sense for the repo to add it

**Comment by gpucce** [comment]
I think @patrickvonplaten might be the person to tag to check if this slipped through.

If this doesn't make sense I'll close the issue!

**Comment by patrickvonplaten** [comment]
Think in this case the best is to do a little tweak to the original modeling file and use this one instead :-)

**Comment by patrickvonplaten** [comment]
cc @sgugger - think that's also a good use case for: https://huggingface.co/docs/transformers/custom_models?

**Comment by sgugger** [comment]
BERT and RoBERTa supports the pooling that was introduced in their paper. Transformers is not a modular toolbox, so as Patrick said, if you want to tweak this, you will need to edit the modeling file, but we won't accept a change in the code to support this. And as Patrick pointed out, you can still share your tweaked model if it performs better!

**Comment by gpucce** [comment]
Ok thanks! I will close the issue then
