### ISSUE TITLE
ASR Pipeline: End of transcripts missing when chunking enabled 

### ISSUE THREAD

**Issue by nkaenzig-aifund** [huggingface/transformers#16671]
## Environment info
- `transformers` version: 4.18.0
- Platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- Huggingface_hub version: 0.5.1
- PyTorch version (GPU?): 1.10.0+cu111 (False)
- Tensorflow version (GPU?): 2.8.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes & no
- Using distributed or parallel set-up in script?: no

### Who can help
@Narsil, @patrickvonplaten, @jonatasgrosman, @anton-l

## Information
If you use the chunking feature implemented in the asr pipeline, in some cases it cuts off the end of the audio transcripts.

Model I am using:
`facebook/wav2vec2-large-960h-lv60-self`

The problem arises when using:
* [x] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce
The issue can be reproduced using the following colab notebook:
https://colab.research.google.com/drive/1SSWr-2X2nnbKLa5dUSEm_Y_WFTju2-fN?usp=sharing

## Expected behavior
`chunk_length_s=None` and `chunk_length_s=10` should yield the same (or similar) results, without cutting off the end of the transcript.

**Comment by patrickvonplaten** [comment]
Hey @nkaenzig-aifund,

Thanks a lot for the reproducible bug report! I'm looking into it and will try to submit a fix today. cc @Narsil 

```python
#!/usr/bin/env python3
from transformers import pipeline

pipe = pipeline(model='facebook/wav2vec2-large-960h-lv60-self')

result_1 = pipe('47.wav', chunk_length_s=None)

result_2 = pipe('47.wav', chunk_length_s=10)

print("Correct", result_1)
print("Wrong", result_2)
```

with:

!wget https://public-a2d129863a16ad26b0deda49d22c64b8.s3.us-west-2.amazonaws.com/47.wav
