### ISSUE TITLE
Optional keys in TrainingArguments aren't always labelled as such

### ISSUE THREAD

**Issue by d-miketa** [huggingface/transformers#16701]
Inside `TrainingArguments` there are a few keys such as [tf32](https://github.com/huggingface/transformers/blob/098b0026447271a340d2d7e6bff428c82cb6d744/src/transformers/training_args.py#L594) which are optional and have a default of `None`, but aren't explicitly labelled as such. This can cause problems downstream; for example, OmegaConf will complain that 
```
omegaconf.errors.ValidationError: Non optional field cannot be assigned None
    full_key: tf32
    object_type=Seq2SeqTrainingArguments
```

The fix is simple, just make sure every key with a default of `None` has `Optional` type. I'm busy with another PR atm, but can have a look later.

**Comment by LysandreJik** [comment]
cc @sgugger
