### ISSUE TITLE
group_texts function in language-modeling seems get wrong

### ISSUE THREAD

**Issue by zheyuye** [huggingface/transformers#16702]
During preprocssing of language-modeling, function `group_texts` as https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py#L447-L460

seeems ingore the special tokens like [CLS] and [SEP], and just concatenated them together. An obvious bug would appear that one example may have multiple [CLS] tokens that confuses model and also the [CLS] may not be sure to be placed in the first place.

**Comment by heraclex12** [comment]
I am confused about the efficiency of this function. Does anyone test the performance of trained models by this way?

**Comment by zheyuye** [comment]
I got my except answer from https://github.com/huggingface/transformers/issues/10737, closing this issue.
