### ISSUE TITLE
AutoConfig.from_pretrained can fail with Tokenizers

### ISSUE THREAD

**Issue by d-miketa** [huggingface/transformers#16710]
`tokenizer_config = AutoConfig.from_pretrained("/path/to/tokenizer_config.json")` resolves the Auto Class by checking the `model_type` key, which is not always included for tokenizers, see e.g. https://huggingface.co/seyonec/ChemBERTa-zinc-base-v1/blob/main/tokenizer_config.json.

Perhaps `model_type` should be exported in `tokenizer_config.json` when running `trainer.save(/path/to)`?

**Comment by LysandreJik** [comment]
The `AutoConfig` utility is a utility for models only, it's the tool one can use to instantiate a model. 

What would you like to do by instantiating a configuration for a tokenizer? The `AutoTokenizer` class should handle everything on its own.
