### ISSUE TITLE
Quick Tour TF2.0 Training Script has Control Flow Error when Replacing TFBERT with TFRoberta

### ISSUE THREAD

**Issue by ryanrgarland** [huggingface/transformers#1671]
## 📚 Migration

Model I am using (Bert, XLNet....): TFRoberta.

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [x] the official example scripts: Quick Tour TF2.0 Training Script.
* [ ] my own modified scripts: 

Details of the issue:

When replacing TF BERT with TF Roberta (and the relevant tokenizer) in the quick tour script, I get the following error:

```
TypeError: You are attempting to use Python control flow in a layer that was not declared to be dynamic. Pass `dynamic=True` to the class constructor.
Encountered error:
"""
using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph is disabled in this function. Try decorating it directly with @tf.function.
"""
```

I suspect this extends to all models, though I haven't verified this. Any thoughts?

## Environment

* OS: Catalina
* Python version: 3.7.14
* PyTorch version: NA
* PyTorch Transformers version (or branch): Transformers
* Using GPU ? No
* Distributed of parallel setup ? No
* Any other relevant information:

## Checklist

- [x] I have read the migration guide in the readme.
- [x] I checked if a related official extension example runs on my machine.

**Comment by LysandreJik** [comment]
Hi, I think this was fixed by #1601, could you try now by cloning and installing from master?
