### ISSUE TITLE
[PegasusConfig] wrong default vocab_size

### ISSUE THREAD

**Issue by yaozhaogoogle** [huggingface/transformers#16735]
In PegasusConfig (https://github.com/huggingface/transformers/blob/v4.18.0/src/transformers/models/pegasus/configuration_pegasus.py#L108), the default vocab size should be 96000 instead of 50265.
 @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @yaozhaogoogle,

Thanks for the issue, could you maybe link to the original configuration that shows a default vocab size of 96000?

**Comment by yaozhaogoogle** [comment]
from the github https://github.com/google-research/pegasus , there is a link to the checkpoints and vocabs, https://pantheon.corp.google.com/storage/browser/pegasus_ckpt . They are all using a single vocab size of 96k

**Comment by patrickvonplaten** [comment]
Thanks for the link @yaozhaogoogle, 

Note that in the configuration we just provide a default value that could be used when initializing Pegagus from scratch. If one loads a pretrained checkpoint the vocab size is overwritten by the value defined in the config on the HF Hub. 

E.g. this Pegagus checkpoint: https://huggingface.co/google/pegasus-large/blob/main/config.json#L122 has a vocab size of 96000 which would be used when doing:

```py
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("google/pegasus-large")

model = AutoModelForSeq2SeqLM.from_pretrained("google/pegasus-large")
```

**Comment by yaozhaogoogle** [comment]
Thanks for the explanation!
