### ISSUE TITLE
KeyError when using AutoTokenizer for facebook/detr-resnet-*

### ISSUE THREAD

**Issue by grassjelly** [huggingface/transformers#16745]
## Environment info

- `transformers` version: 4.16.0
- Platform: Ubuntu 20.04
- Python version: 3.8.12
- PyTorch version (GPU?): 1.11.0
- Tensorflow version (GPU?): NA
- Using GPU in script?: NA 
- Using distributed or parallel set-up in script?: No

### Who can help
- DETR: @NielsRogge
- Tokenizers: @SaulLu
## Information
I'm following this tutorial https://huggingface.co/docs/transformers/serialization on how to export models to ONNX. Tr
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("facebook/detr-resnet-101")ying to export one for DETR but I can't proceed as I'm stuck with this error on AutoTokenizer:

```
Traceback (most recent call last):
  File "detr_config.py", line 2, in <module>
    tokenizer = AutoTokenizer.from_pretrained("facebook/detr-resnet-101")
  File "/home/juan/miniconda3/envs/pytorch/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 530, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
  File "/home/juan/miniconda3/envs/pytorch/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 565, in __getitem__
    raise KeyError(key)
KeyError: <class 'transformers.models.detr.configuration_detr.DetrConfig'>
```
Here's the snippet of code to reproduce the error:
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("facebook/detr-resnet-101")
```

**Comment by NielsRogge** [comment]
Hi,

DETR is a vision model, not a text model, hence it doesn't have a tokenizer, but a so-called feature extractor (useful for preparing images for the model). You can load it using the AutoFeatureExtractor API:

```
from transformers import AutoFeatureExtractor

feature_extractor = AutoFeatureExtractor.from_pretrained("facebook/detr-resnet-101")
```

**Comment by grassjelly** [comment]
thanks @NielsRogge . That worked for me.
