### ISSUE TITLE
possible issues with run_summarization_finetuning.py

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#1674]
Hi,
thanks for pushing summarization codes, here are my comments on this file:
 
- line 473: checkpoints = [] is empty and will not be evaluated. Also, the evaluation script is not called.

- line 482: results = "placeholder" is set to the placeholder, I was wondering if the function could return the generated text,so user could see the performance of the method visually. 

- line 463: the model is only saved after the training, would be great to have the saving option like run_glue, "eval_during_training" also during the training activated.

- line 272 /transformers/modeling_encoder_decoder.py, the tie of weights is not done, this is a part of the model, would be great to have it implemented

- line 139 of transformers/modeling_auto.py, here you check the "path" if this starts with the name of bert, ..., you load the relevant one, but in run_summarization_finetuning, the user does not need to save the model in args.output_dir which starts with the name of model, so the codes wont work if the model is not saved with the path starting with the name of the model

- line 152 of /run_summarization_finetuning.py for param_group in optimizer.param_groups: I think this should be optimizer[stack] not optimizer alone 

- utils_summarization.py: line 180, the comparison should not work, since s is a sequence, and then it is compared with special token, 

- utils_summarization.py:  line 182: embeddings.append(sentence_num % 2), to me you need to add sentence_sum%2 for the length of the sentence, but not 1 for each sentence.

thanks.

**Comment by rlouf** [comment]
Hi!

The summarization is still work in progress and should be included in the next release. Latest changes are in the `example-summarizarion` branch.
