### ISSUE TITLE
Any example of how to do multi-class classification with TFBertSequenceClassification

### ISSUE THREAD

**Issue by usmanmalik57** [huggingface/transformers#1675]
## ❓ Questions & Help

I am trying to create a multi-class text classification model using BertSequenceClassifier for Tensorflow 2.0. Any help with the implementation strategy would be appreciated. Also, are there any recommendations as to how to convert a simple CSV file containing text and labels into TF dataset format such as Glue?

**Comment by tongbc** [comment]
im asking for the same thing

**Comment by vinodsharma** [comment]
I also need this. experts, please help/guide.
