### ISSUE TITLE
ValueError: Reference at 'refs/heads/master' does not exist

### ISSUE THREAD

**Issue by deema-A** [huggingface/transformers#16753]
Hi, 
in the RAG example. 
I got the error (ValueError: Reference at 'refs/heads/master' does not exist)
in 
opt/anaconda3/envs/chatbotper/lib/python3.7/site-packages/git/refs/symbolic.py", line 184, in_get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)

after running: 
python examples/research_projects/rag/finetune_rag.py \
    --data_dir data_dir \
    --output_dir output_dir \
    --model_name_or_path facebook/rag-sequence-nq \
    --model_type rag_sequence \
    --fp16 \
    --gpus 8
    --index_name custom
    --passages_path path/to/data/my_knowledge_dataset
    --index_path path/to/my_knowledge_dataset_hnsw_index.faiss

any advice? thanx

**Comment by warumso7** [comment]
Same question from training yolov5, it seems that there are no effective solutions...
