### ISSUE TITLE
NER training crash

### ISSUE THREAD

**Issue by yananchen1989** [huggingface/transformers#16764]
transformers version: 4.17.0

Hi, I run the script for NER task for [few-nerd](https://huggingface.co/datasets/dfki-nlp/few-nerd) dataset
https://github.com/huggingface/transformers/blob/main/examples/pytorch/token-classification/run_ner_no_trainer.py

```
 CUDA_VISIBLE_DEVICES=3  python -u run_ner_no_trainer.py \
  --model_name_or_path roberta-large \
  --dataset_name dfki-nlp/few-nerd \
  --dataset_config_name "supervised" \
  --output_dir /scratch/w/wluyliu/yananc/finetunes/roberta_nerd_fine \
  --text_column_name "tokens" \
  --label_column_name "fine_ner_tags" \
  --num_train_epochs 7  --local_files_only --debug  --debug_cnt 50000
```
When I use small samples, for example below 30000, things go smoothly and the precision, recall and F1 are in good alignment with the original paper.

However, when I increase the samples used for training, for example, 50000, or full set, the metrics become zero, where the predictions from model are all "O".  It is quite weird. 

I also try the conll2003 dataset, it is the same. 

Am I miss something ?

Thanks.

**Comment by tahmiddialpad** [comment]
Was that issue resolved? I am facing a similar problem with the HF implementation of LUKE: https://github.com/huggingface/transformers/tree/main/examples/research_projects/luke
