### ISSUE TITLE
i want to use bert pre-trained modle in a text classification problem which the text with Multi-label. But，there are some problems .

### ISSUE THREAD

**Issue by lushishuai** [huggingface/transformers#1677]
## ❓ Questions & Help

i want to use bert pre-trained modle in a text classification problem which the text with Multi-labels. Which program and task should i select between run_glue.py、run_multiple_choice.py、run_squad.py and so on？
for example of my text：“I'd like 2 tickets to see Zoolander 2 tomorrow at Regal Meridian 16 theater in Seattle at 9:25 PM”     
 in this text include this labels: request_ticket;inform_moviename;inform_date;inform_theater;inform_city;inform_starttime;inform_numberofpeople	
which program  should i select?  Thanks very much!

**Comment by dsindex** [comment]
run_multiple_choice.py will be a good choice.
in case ‘bert’, it uses 
https://github.com/huggingface/transformers/blob/master/transformers/modeling_bert.py#L1021

but i think your problem formulation is odd.
what about classifying ‘request_*’ intent as normal classification problem and slot tagging ‘inform_*’ as sequence classification?

**Comment by lushishuai** [comment]
hi. i just start to learn bert for a very short time,so i could not have learned it clearly. 
‘request_’ intent classifying can be very different with the normal classification problem?
i have not understand this.
