### ISSUE TITLE
Download assets directly to the specified cache_dir

### ISSUE THREAD

**Issue by n-a-sz** [huggingface/transformers#1678]
## 🚀 Feature

```
import torch
from transformers import *
TRANSFORMERS_CACHE='/path/to/my/transformers-cache'
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', cache_dir=TRANSFORMERS_CACHE) 
```

Actual behavior: It downloads the asset into a temp folder and then copies it to the specified cache_dir.

Proposed behavior: Download the asset directly to the specified cache_dir.

Impacted code part: https://github.com/huggingface/transformers/blob/master/transformers/file_utils.py#L295-L322

## Motivation

We have an environment setup where the tmp folders have limited space, because it is not a mounted docker volume. If the `"asset size" > 10GB - "docker image size"` then it won't be able to download the asset. (The 10GB limitation is a docker limitation)

**Comment by thomwolf** [comment]
I would propose to download to the cache_dir with a specific temporary name (like a `.part` suffix) and copy + rename at the end.

Probably best to activate that with an option `use_cache_dir_as_tmp`. To not clutter the cache dir with temporary files in the default settings.

Do you want to submit a PR for that? Would be happy to review it

**Comment by n-a-sz** [comment]
Yes that is also a good approach. For now, we seem to be okay with this limitation, but I'll do a pr if we face this as an issue or have some free time.

**Comment by zeeqy** [comment]
Same problem here. On cluster, /tmp folder is small. Keep getting no space on device.

**Comment by aaugustin** [comment]
I fixed this in b67fa1a8d2302d808ecb9d95355181eaf21ee3b6.

**Comment by aaugustin** [comment]
Until there's a release with this fix, you can set $TMPDIR to an appropriate location if /tmp is too small.

**Comment by n-a-sz** [comment]
Cool, thank you @aaugustin !
