### ISSUE TITLE
Error when creating RobertTokenizer for distilroberta-base

### ISSUE THREAD

**Issue by fhamborg** [huggingface/transformers#1680]
## 🐛 Bug

Model I am using (Bert, XLNet....): DistilRoberta

Language I am using the model on (English, Chinese....): EN

The problem arise when using the official example scripts: https://github.com/huggingface/transformers/tree/master/examples/distillation

## To Reproduce
```
RobertaTokenizer.from_pretrained('distilroberta-base')
```

this will yield an error:
```
OSError: Model name 'distilroberta-base' was not found in tokenizers model name list (roberta-base, roberta-large, roberta-large-mnli). We assumed 'distilroberta-base' was a path or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.
```

## Expected behavior
should produce a RobertaTokenizer instance, which can also be used for `distilroberta-base`. 

## Environment

* OS: MacOS
* Python version: 3.7
* PyTorch version: 1.3.0
* PyTorch Transformers version (or branch):  2.1.1
* Using GPU ? no

**Comment by julien-c** [comment]
It's not in a pip released version yet so you need to pull from master if you want to use it for now.

We'll do a release soon.

**Comment by fhamborg** [comment]
Thanks for the info. Do you have an estimation when that pip release would be, @julien-c ?

**Comment by oersoy1** [comment]
Reviving this thread. I just cloned 2.2.2 from the master and updated `transformers`. `distilroberta-base` is still not available.  Am I missing something? Thanks, you all!..

> OSError: Model name 'distilroberta-base' was not found in model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad, distilbert-base-german-cased, distilbert-base-multilingual-cased)

**Comment by julien-c** [comment]
What are the exact commands you typed @oersoy1?

**Comment by oersoy1** [comment]
@julien-c OK, I found out what is happening and will document here just in case someone else falls into the same trap. I wrote my custom script similar to run_glue.py.  I was passing `distilbert` to the `args.model_type` argument and the `model_name` got `distilroberta-base` assigned.  I assumed that it was a subclass of `distilbert` models so the type intuitively looked as if it should have been distilbert. [This list](https://huggingface.co/transformers/pretrained_models.html) certainly gives me that impression.

However, looking at the distillation [examples](https://github.com/huggingface/transformers/tree/master/examples/distillation), I realized the model type needs to be `roberta` not `distilbert`. 

It is a little bit confusing but regardless, I got `distilroberta-base` working and it gave me great results. 

Thanks a lot!

**Comment by julien-c** [comment]
Ah, yeah, you are correct. Moved the model shortcut in the table in ac1b449

**Comment by oersoy1** [comment]
No worries. I see that you have corrected the pretrained models list and moved `distilroberta-base` under `roberta` which was the main problem for me. Updating all documentation when you make the changes could be difficult, especially when the gatekeepers for a specific document is different than the ones making the change.
