### ISSUE TITLE
use transformers on apple mac m1 (TF backend)

### ISSUE THREAD

**Issue by srulik-ben-david-hs** [huggingface/transformers#16807]
is it possible?
I saw that there is an option to use tensorflow-metal..but does it gonna work seamlessly with transformers?
https://developer.apple.com/metal/tensorflow-plugin/

for pytorch it seems not possible yet.

**Comment by LysandreJik** [comment]
I believe it should work with both on M1, @NielsRogge you have experience using `transformers` on M1 macs right?

**Comment by NielsRogge** [comment]
I'm using PyTorch only on my Mac, but if you use TF for Transformers you get a nice speedup, see here for a nice thread: https://twitter.com/lvwerra/status/1470818833619468290?t=1bDbo3Kl-MHBF2MbDh5GiA&s=19

**Comment by srulik-ben-david-hs** [comment]
thanks a lot!
I'll try it.
so do you mean that you use pytorch without the m1 gpu?

**Comment by NielsRogge** [comment]
> so do you mean that you use pytorch without the m1 gpu?

Yes, for now. However the PyTorch team is planning to add support for it.
