### ISSUE TITLE
Wrong Roberta special tokens in releases on GitHub

### ISSUE THREAD

**Issue by fhamborg** [huggingface/transformers#1681]
## 🐛 Bug

Model I am using (Bert, XLNet....): Roberta

Language I am using the model on (English, Chinese....): Potentially wrong on any language

The problem arise when using the official example scripts: see https://github.com/huggingface/transformers/releases/tag/1.1.0

In the section `Tokenizer sequence pair handling` the special tokens for Roberta are wrong if I'm not mistaken. The example reads:
```
[CLS] SEQUENCE_0 [SEP] [SEP] SEQUENCE_1 [SEP]
```

whereas Roberta's actual representation for a sequence pair including special tokens should be (also following transformer's official documentation, cf. https://huggingface.co/transformers/model_doc/roberta.html):
```
<s> SEQUENCE_0 </s> <s> SEQUENCE_1 </s> 
```
Note the <s> or </s> instead of [SEP]. I am not sure about the [CLS], though, but I think for Roberta it should not be there.

**Comment by LysandreJik** [comment]
You are right the release is wrong, it should be `<s> SEQUENCE_0 </s></s> SEQUENCE_1 </s>`. I just updated it; thank you!
