### ISSUE TITLE
huggingface-cli login in dockerfile

### ISSUE THREAD

**Issue by hyunwoongko** [huggingface/transformers#16813]
Hello. I want to use private model in my docker environment.
for that, I need to login in the dockerfile. (to deploy model using entrypoint)
is there anyway to do this?

**Comment by hyunwoongko** [comment]
I copied token file to my /root/.huggingace. but it doesn't work.

**Comment by LysandreJik** [comment]
In your dockerfile, you can manually save the token with the following:

```
python -c 'from huggingface_hub import HfFolder; HfFolder.save_token("<TOKEN>")'
```

It will save it in `~/.huggingface/token`. You can check it works with 

```
python -c 'from huggingface_hub import whoami; print(whoami())'
```

**Comment by hyunwoongko** [comment]
Thank you !

**Comment by LysandreJik** [comment]
Perfect!

**Comment by taki0112** [comment]
Hello @hyunwoongko 
The `_login` function requires `hf_api` argument, which one did you give?

**Comment by hyunwoongko** [comment]
Hello. @taki0112  I am using the follow script.

```python
from huggingface_hub import HfApi
from huggingface_hub.commands.user import _login

_login(HfApi(), token="YOUR_KEY")
```

**Comment by taki0112** [comment]
@hyunwoongko Thanks a lot !

**Comment by lanzani** [comment]
> I go through the code but It was not work for me, I think it is regarding new updates, but you can use directly _login from _login.py
> 
> from huggingface_hub._login import _login
> _login(token='your token as string', add_to_git_credential=False)

For future reference: in my Dockerfile, I've added these lines:

```Dockerfile
ARG HF_TOKEN
ENV HF_TOKEN=${HF_TOKEN}
RUN python3 -c "from huggingface_hub._login import _login; _login(token='${HF_TOKEN}', add_to_git_credential=False)"
```
