### ISSUE TITLE
Tranformers documentation translation to Portuguese

### ISSUE THREAD

**Issue by omarespejel** [huggingface/transformers#16824]
Hi!

Let's bring the documentation to all the Portuguese-speaking community :)

Who would want to translate? **Please follow our [TRANSLATING guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md).** Here is a list of the files ready for translation. Let us know here if you'd like to translate any and we'll add your name to the list.

Some notes:
- Please translate using `Você` and not `Tu`.
- Please translate in a gender-neutral way.
- Add your translations to the folder [source/pt/](https://github.com/huggingface/transformers/blob/main/docs/source/pt/)
- Register your translation in [pt/_toctree.yml](https://github.com/huggingface/transformers/blob/main/docs/source/pt/_toctree.yml); please follow the order of the [English version](https://github.com/huggingface/transformers/blob/main/docs/source/en/_toctree.yml).
- Once you're finished, open a pull request and tag this issue by including `#issue-number` in the description, where `issue-number` is the number of this issue.
- 🙋 If you'd like others to help you with the translation, you can also post in our [forums](https://discuss.huggingface.co/) or tag [@espejelomar](https://twitter.com/espejelomar) on Twitter to gain some visibility.

## Get Started section
- [x] [quicktour.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/quicktour.mdx). @vitorfrois
- [x] [installation.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/installation.mdx). @rzimmerdev

## Tutorials
- [x] [pipeline_tutorial.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/pipeline_tutorial.mdx) @rzimmerdev
- [ ] [autoclass_tutorial.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/autoclass_tutorial.mdx) 
- [ ] [preprocessing.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/preprocessing.mdx) WIP @rzimmerdev
- [x] [training.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/training.mdx) @rzimmerdev
- [x] [accelerate.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/accelerate.mdx) @rzimmerdev
- [x] [model_sharing.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/model_sharing.mdx) @rzimmerdev
- [x] [multilingual.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/multilingual.mdx) @rzimmerdev

## How-to guides
- [x] [fast_tokenizers.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/fast_tokenizers.mdx "fast_tokenizers.mdx") WIP @Fellip15
- [x] [create_a_model.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/create_a_model.mdx "create_a_model.mdx") WIP @[Fellip15](https://github.com/Fellip15)
- [ ] [custom_models.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/custom_models.mdx "custom_models.mdx")
- [ ] [run_scripts.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/run_scripts.mdx "run_scripts.mdx")
- [ ] [sagemaker.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/sagemaker.mdx "sagemaker.mdx")
- [ ] [converting_tensorflow_models.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/converting_tensorflow_models.mdx "converting_tensorflow_models.mdx")
- [ ] [serialization.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/serialization.mdx "serialization.mdx")
- [ ] [performance.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/performance.mdx "performance.mdx")
- [ ] [parallelism.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/parallelism.mdx "parallelism.mdx")
- [ ] [benchmarks.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/benchmarks.mdx "benchmarks.mdx")
- [ ] [migration.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/migration.mdx "migration.mdx")
- [ ] [troubleshooting.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/troubleshooting.mdx "troubleshooting.mdx") 
- [ ] [debugging.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/debugging.mdx "debugging.mdx") 
- [ ] [community.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/community.mdx "community.mdx") 
- [ ] [add_new_model.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/add_new_model.mdx "docs/source/en/add_new_model.mdx") 
- [ ] [add_new_pipeline.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/add_new_pipeline.mdx "add_new_pipeline.mdx") @Felipehonorato1
- [ ] [testing.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/testing.mdx "testing.mdx") 
- [ ] [pr_checks.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/pr_checks.mdx "pr_checks.mdx") 

## FINE-TUNE FOR DOWNSTREAM TASKS
- [x] [sequence_classification.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/sequence_classification.mdx "sequence_classification.mdx") @jonatasgrosman
- [x] [token_classification.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/token_classification.mdx "token_classification.mdx") @jonatasgrosman
- [ ] [question_answering.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/question_answering.mdx "question_answering.mdx") WIP @jonatasgrosman
- [ ] [language_modeling.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/language_modeling.mdx "language_modeling.mdx") WIP @jonatasgrosman
- [ ] [translation.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/translation.mdx "translation.mdx") WIP @jonatasgrosman
- [ ] [summarization.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/summarization.mdx "summarization.mdx") WIP @jonatasgrosman
- [ ] [audio_classification.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/audio_classification.mdx "audio_classification.mdx") WIP @jonatasgrosman
- [ ] [asr.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/asr.mdx "asr.mdx") WIP @jonatasgrosman
-  [ ] [image_classification.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/image_classification.mdx "image_classification.mdx") WIP @jonatasgrosman
- [ ] [multiple_choice.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/tasks/multiple_choice.mdx "multiple_choice.mdx") WIP @jonatasgrosman

## CONCEPTUAL GUIDES
- [ ] [philosophy.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/philosophy.mdx "philosophy.mdx") @victorescosta
- [ ] [glossary.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/glossary.mdx "glossary.mdx") @victorescosta
- [ ] [pad_truncation.mdx](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/pad_truncation.mdx "docs/source/en/pad_truncation.mdx") @victorescosta
- [ ] [bertology.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/bertology.mdx "bertology.mdx") @victorescosta
- [ ] [perplexity.mdx](https://github.com/huggingface/transformers/blob/9c9db751e29432e8924624ef44856cd9fa671ef3/docs/source/en/perplexity.mdx "perplexity.mdx") @victorescosta

FYI @osanseviero @stevhliu @sgugger @mishig25

**Comment by omarespejel** [comment]
USP 🇧🇷 presente!

Obrigado @vitorfrois e @rzimmerdev! Coloquei como WIP (work in progress) os docs em que estão trabalhando 🤗. @rzimmerdev muito obrigado pelo seu PR! Se você puder, por favor, coloque aqui quais outros documentos você deseja traduzir. Podemos adicionar mais se formos mais longe 🚀

**Comment by rzimmerdev** [comment]
Oi Omar, eu conclui a tradução dos seguintes docs:

pipeline_tutorial.mdx
training.mdx
accelerate.mdx
multilingual.mdx
installation.mdx

Ainda pretendo concluir os seguintes:
preprocessing.mdx
model_sharing.mdx

Quando eu concluir esses ultimos dois eu dou um update sobre os próximos que vou fazer.

🤗

**Comment by omarespejel** [comment]
@rzimmerdev muito obrigado! I just added your name above to the files you already translated and the ones you plan to translate 🤗

**Comment by Fellip15** [comment]
Olá Omar,

Estou traduzindo:
* fast_tokenizers.mdx

A medida que for pegando mais para traduzir vou colocando nesse comentário.

**Comment by omarespejel** [comment]
Muito obrigado @Fellip15! I added your name to the first comment in this issue for `fast_tokenizers`.

**Comment by jonatasgrosman** [comment]
Hi @omarespejel I'd like to contribute here! 😃 🇧🇷 

I'll translate the "FINE-TUNE FOR DOWNSTREAM TASKS" section.

PS: It seems that some "How-to guides" pages is in the "Downstream tasks" section on your checklist

**Comment by omarespejel** [comment]
Oi @jonatasgrosman! Amazing 🇧🇷! I added your name to the "FINE-TUNE FOR DOWNSTREAM TASKS" section and also reviewed your #17352 PR!

Thank you for your feedback on the checklist order! I applied it 🤗.

**Comment by rzimmerdev** [comment]
Oi Omar, vou enviar as traduções pros arquivos que me pediu :)

**Comment by omarespejel** [comment]
Muito obrigado @rzimmerdev. Eles são chave para ter pronta a documentação para seguinte release de Transformers 🤗.

**Comment by rzimmerdev** [comment]
Oi Omar, vou voltar a traduzir alguns documentos

**Comment by omarespejel** [comment]
Olá @rzimmerdev! Thank you, that would be great! Any one you prefer to translate? Sorry for my late reply.

**Comment by victorescosta** [comment]
@omarespejel I can translate the entire part of conceptual guides!

**Comment by omarespejel** [comment]
Thank you, @victorescosta! I added your name to the guide above! 🚀 Do you use Brazilian or Portuguese PT?

**Comment by victorescosta** [comment]
> Thank you, @victorescosta! I added your name to the guide above! 🚀 Do you use Brazilian or Portuguese PT?

Brazilian portuguese. Is it ok? I will try to minimize these differences in my translation

**Comment by omarespejel** [comment]
@victorescosta, that sounds perfect, thank you!

**Comment by omarespejel** [comment]
Obrigado @Felipehonorato1! I added you to the list 🇧🇷. Please tag me in your PR.

**Comment by davialvb** [comment]
Hey, I'll translate:
- custom_models.mdx
- run_scripts.mdx
- converting_tensorflow_models.mdx
- serialization.mdx

**Comment by osanseviero** [comment]
Awesome! Looking forward the PR! :fire:
