### ISSUE TITLE
no attribute ViTFeatureExtractor

### ISSUE THREAD

**Issue by Pannu22** [huggingface/transformers#16837]
Getting following error:
AttributeError: module transformers.models.vit has no attribute ViTFeatureExtractor

on calling:
`processor = TrOCRProcessor.from_pretrained("microsoft/trocr-large-printed")`

System:
Jenson AGX

Tried in RTX & it is working fine.

Installation:
`pip install git+https://github.com/huggingface/transformers`

**Comment by Pannu22** [comment]
Installing `Pillow` to env fixed it.

**Comment by wjbmattingly** [comment]
Thanks for this!
