### ISSUE TITLE
Dropping support for Python 3.6

### ISSUE THREAD

**Issue by sgugger** [huggingface/transformers#16832]
Python 3.6 [has been retired](https://peps.python.org/pep-0494/#lifespan) on December 21st 2021 and won't get new security releases anymore. As a result, Transformers will stop supporting Python 3.6 and have a minimum requirement of Python 3.7 in the next release (v4.19.0), around the beginning of May.

**Comment by LSinev** [comment]
What is the purpose of dropping support while not using latest features of newer python versions (or newer versions of other libraries, which are dropping support)?

**Comment by LysandreJik** [comment]
Hey @LSinev, thank you for asking. There are some features that would have been implemented in a simpler manner had Python 3.6 been dropped earlier (https://github.com/huggingface/transformers/issues/15739, @sgugger can chime in on the init system), and we already use features that are only available in 3.7 (`dataclasses`). 

Furthermore:
- Python 3.6 is now EOL and will not be receiving new bug and security patches
- All backends of `transformers` newer versions (torch 1.11, tensorflow 2.8, jax  0.2.18) now require python 3.7

**Comment by sgugger** [comment]
We were not using the features of newest Python versions without dropping the old ones ;-)
For instance, our inits will now be able to use [PEP 562](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep562)
