### ISSUE TITLE
Repeated Generation

### ISSUE THREAD

**Issue by Sandip-Hapani134** [huggingface/transformers#16830]
When I am giving input for the summarization, every time it is the generating same summary.  (Sometimes even if I consider the first few lines of input as new input, in those cases also it is generating the same output summary.)

Example: 

Input: With an immunocompromised son, how could we not be terrified of COVID making its way into our home? For the past two years, we’ve been so careful to limit exposure; we were able to homeschool our kids last year and we’ve been conscious of avoiding large crowds even with the vaccines. Our kids being able to receive the vaccine was a huge step for us in feeling less of the overwhelming worry of what would happen if any of us were to get COVID, but the concerns were still there. Our son Conner has Duchenne muscular dystrophy, so any virus could have a detrimental effect on his health. With DMD, the whole body is already fighting everyday so it’s possible that the body won’t be able to fight off any illnesses. The heart and lungs are also already working overtime, so the potential of getting a virus that is known to harm the heart and lungs is a scary thing.    We made it almost two years without any of us getting COVID but that came to end over the holidays. I got sick first and despite our precautions, Conner ended up testing positive right before he was supposed to go back to school, with his initial symptom being a stuffy nose. We called our doctor right away and she told us that we should just keep a close eye on him to make sure he didn’t get any worse. Luckily, his symptoms never got too bad (just a low grade fever, sore throat, and slight cold) and he was able to get the booster shot as soon as possible after testing negative again. All things considered, we truly believe that he was as lucky as he was because he had both doses of the vaccine and got Omicron instead of one of the earlier variants.   Through our whole experience with the pandemic and getting COVID, one of the most difficult aspects was understanding and coming to terms with the fact that many people don’t share our caution. It can be hard to understand why we’re as careful as we are when you don’t know what it feels like to have someone you love be immunocompromised during a deadly pandemic. We found ourselves having to explain to those around us why it is so important for us all to wear our masks and avoid large crowds and people don’t always understand, especially with the ‘stereotypes’ surrounding what happens when you get COVID as a child. The main information about children and COVID has been that children are resilient and won’t be too negatively impacted by it, but that just isn’t true for immunocompromised children. The majority of people will never truly understand our situation until they find themselves in a similar one so it can be hard to hear people complaining about still having to wear masks and saying that COVID isn’t a big deal anymore. At the beginning, it was also hard to find balance in the conversations we had to have with our children because of our own levels of worry. We wanted to be clear about the importance of staying safe but at the same time didn't want to scare them or project our own fears onto them.”    Karen Morales, a mom of two, lives with a very rare form of a rare disease called Limb-girdle muscular dystrophy. This is her COVID experience from her perspective:     “It's inevitable. Or at least that was always my feeling: someday we were bound to get infected with the virus. The question we really struggled with was when?  In the early days of lockdown and homeschool, we felt scared. It was easiest to stay in our homes and order groceries from isolation, then to risk the fear in the world. But like many things, over time, especially with vaccines and home testing, the COVID-19 pandemic shifted from a new fear to just the normal way of life.   My ten year old daughter got it first, spiking a fever after a day on the ski slopes. It was then that our first family decision was made: do we isolate or go through this together. For us, the decision to leave a young child who had lived in fear of this moment for almost 24 months was harder than just getting it together.   In rare disease families, we are used to making hard choices. We are accustomed to inconvenience and we understand, out of practice, how isolating some experiences can be. At the same time, we have a special bond. There is a flavor of love that is only captured when you must depend on each other for basic needs and survival. That depth of connection and trust is what our families are built on.   For us, we weathered COVID as a team. We trusted in the science of vaccinations and boosters and we leaned into natural immunity of vitamins and healing food. The hardest part for us was not the illness itself, but the toll that laying around for multiple days takes on a body with fragile mobility. I find that recovering from being immobile is always the harder part than the fall or disease before it.  The body adapts to what it experiences and for me, the more it sits around the more it prefers that state.   I challenge the conventional wisdom that you lose function so quickly and I always tell myself that my body must again learn to move with fear. Having a mobility challenge is like walking on a rocking cruise ship every day. You must remind yourself that you can do it and keep alert and aware of any changes in your body or environment.   We survived COVID as I knew we would. And we carry those lessons with us into everyday life.     In a world that sometimes feels isolated, we have a depth of bond that is hard to emulate. And when the forces impact our health it takes strength and courage to find a way to regain our footing in an ever changing environment.

Summary: We’ve been living in fear of the COVID-19 pandemic for the past two years and it’s been a difficult time for many people to understand what it feels like to have someone you love be immunocompromised during a deadly pandemic Like many people, we’re accustomed to inconvenience and we understand, out of practice, how isolating some experiences can be, but it can be hard to understand why many people don’t share our caution and why some people are able to avoid large crowds even with the vaccines we received when we were in the state of the virus in 2015..”- Karen Morales, a mom of two, lives with a very rare form of a rare disease called Limb-girdle muscular dystrophy and has been living with the virus for the last two years, including the first COVID pandemic in the United States, which killed more than 1,000 people and left more than 2,000 of them in a coma and hundreds of others with life-threatening conditions, including a severe brain injury and a brain haemorrhage, a stroke, and a heart attack and a broken heart, among other things, and many others with rare diseases, including my son Conner, who has Duchenne.

------------------------------------------------

Input: With an immunocompromised son, how could we not be terrified of COVID making its way into our home? For the past two years, we’ve been so careful to limit exposure; we were able to homeschool our kids last year and we’ve been conscious of avoiding large crowds even with the vaccines. Our kids being able to receive the vaccine was a huge step for us in feeling less of the overwhelming worry of what would happen if any of us were to get COVID, but the concerns were still there. Our son Conner has Duchenne muscular dystrophy, so any virus could have a detrimental effect on his health. With DMD, the whole body is already fighting everyday so it’s possible that the body won’t be able to fight off any illnesses. The heart and lungs are also already working overtime, so the potential of getting a virus that is known to harm the heart and lungs is a scary thing.    We made it almost two years without any of us getting COVID but that came to end over the holidays. I got sick first and despite our precautions, Conner ended up testing positive right before he was supposed to go back to school, with his initial symptom being a stuffy nose. We called our doctor right away and she told us that we should just keep a close eye on him to make sure he didn’t get any worse. Luckily, his symptoms never got too bad (just a low grade fever, sore throat, and slight cold) and he was able to get the booster shot as soon as possible after testing negative again. All things considered, we truly believe that he was as lucky as he was because he had both doses of the vaccine and got Omicron instead of one of the earlier variants.   Through our whole experience with the pandemic and getting COVID, one of the most difficult aspects was understanding and coming to terms with the fact that many people don’t share our caution. It can be hard to understand why we’re as careful as we are when you don’t know what it feels like to have someone you love be immunocompromised during a deadly pandemic. We found ourselves having to explain to those around us why it is so important for us all to wear our masks and avoid large crowds and people don’t always understand, especially with the ‘stereotypes’ surrounding what happens when you get COVID as a child. The main information about children and COVID has been that children are resilient and won’t be too negatively impacted by it, but that just isn’t true for immunocompromised children. The majority of people will never truly understand our situation until they find themselves in a similar one so it can be hard to hear people complaining about still having to wear masks and saying that COVID isn’t a big deal anymore. At the beginning, it was also hard to find balance in the conversations we had to have with our children because of our own levels of worry.

Summary: We’ve been living in fear of the COVID-19 pandemic for the past two years and it’s been a difficult time for many people to understand what it feels like to have someone you love be immunocompromised during a deadly pandemic Like many people, we’re accustomed to inconvenience and we understand, out of practice, how isolating some experiences can be, but it can be hard to understand why many people don’t share our caution and why some people are able to avoid large crowds even with the vaccines we received when we were in the state of the virus in 2015..”- Karen Morales, a mom of two, lives with a very rare form of a rare disease called Limb-girdle muscular dystrophy and has been living with the virus for the last two years, including the first COVID pandemic in the United States, which killed more than 1,000 people and left more than 2,000 of them in a coma and hundreds of others with life-threatening conditions, including a severe brain injury and a brain haemorrhage, a stroke, and a heart attack and a broken heart, among other things, and many others with rare diseases, including my son Conner, who has Duchenne.

**Comment by gante** [comment]
Hi @Sandip-Hapani134 👋  Assuming you are using our `generate()` function, try adding the `do_sample=True` argument to it. 

Let us know if it helped :)
