### ISSUE TITLE
request for a Bert_base uncase model.bin file

### ISSUE THREAD

**Issue by rhl2k** [huggingface/transformers#1687]
## 🚀 Feature

currently we r using BERT_Large uncased which slows down our application we like to use BERT_Base uncased model but BERT_base uncased model does not contain bin file.could  you please let me know where I get model.bin file.

**Comment by LysandreJik** [comment]
As with any model hosted on our S3, you can do as follows to load one of the checkpoints:

```py
from transformers import BertModel

model = BertModel.from_pretrained("bert-base-uncased")
```

You can find the list of pre-trained models in [the documentation](https://huggingface.co/transformers/pretrained_models.html).

**Comment by rhl2k** [comment]
can we use bert-based-uncased model for QA(question-answer) if yes then how

because model.predict(doc,q) giving error( **BertModel has no attribute predict**)

**Comment by pohanchi** [comment]
The usage u need to reference on examples/run_squad.py and u will know
everything on that code

**Comment by LysandreJik** [comment]
You can find the documentation [here](https://huggingface.co/transformers/). The [quickstart](https://huggingface.co/transformers/quickstart.html) may be especially useful for you. As @pohanchi said, looking at the examples can also help in understanding the usage.
