### ISSUE TITLE
Source link of transformers.pipeline is broken

### ISSUE THREAD

**Issue by ftnext** [huggingface/transformers#16904]
This is about **documentation link error**.

There is a issue on the page https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline

<img width="550" alt="image" src="https://user-images.githubusercontent.com/21273221/164890499-54a79a1a-12c7-4776-bcf7-c39bf6f3efc1.png">

**Procedure**
Click the link of `<source>`, then go to https://github.com/huggingface/transformers/blob/v4.18.0/src/transformers/pipelines.py#L372 but see 404 Page not found on GitHub.

**Correct link**
I found that the correct link is https://github.com/huggingface/transformers/blob/v4.18.0/src/transformers/pipelines/__init__.py#L372

---

It seems that the content is generated by

https://github.com/huggingface/transformers/blob/31ec2cb2badfbdd4c1ac9c6c9b8a74e974984206/docs/source/en/main_classes/pipelines.mdx#L123

**Comment by LysandreJik** [comment]
cc @sgugger @mishig25

**Comment by sgugger** [comment]
`doc-builder` doesn't like objects defined in `__init__`, will send a fix.
