### ISSUE TITLE
LayoutLMv3: Pre-training for Document AI with Unified Text and Image Masking

### ISSUE THREAD

**Issue by seanbenhur** [huggingface/transformers#16914]
### Model description

LayoutLMV3 is the successor of the LayoutLM models. the models are specialized in multimodal document analysis tasks and achieve SOTA results on them.

The current [code](https://github.com/microsoft/unilm/blob/master/layoutlmv3/layoutlmft/models/layoutlmv3/modeling_layoutlmv3.py) for the LayoutLMV3 is implemented in huggingface format.

Since the code is already more similar to the Huggingface format, I am not sure whether integrating this model into this repo is necessary, but there will be an ease of use if it is available in the library itself.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Model Implementation: https://github.com/microsoft/unilm/tree/master/layoutlmv3
Model Weights: https://huggingface.co/microsoft/layoutlmv3-base
Authors: Yupan Huang,Tengchao Lv, Lei Cui, Yutong Lu ,Furu Wei

**Comment by LysandreJik** [comment]
cc @NielsRogge :)
