### ISSUE TITLE
cannot import name 'Data2VecForCTC' from 'transformers'

### ISSUE THREAD

**Issue by Sorrow321** [huggingface/transformers#16952]
### System Info

```shell
- `transformers` version: 4.18.0
- Platform: Linux-5.13.0-40-generic-x86_64-with-glibc2.31
- Python version: 3.9.7
- Huggingface_hub version: 0.2.1
- PyTorch version (GPU?): 1.11.0 (True)
- Tensorflow version (GPU?): 2.7.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

@patrickvonplaten

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Following the code sample in https://huggingface.co/facebook/data2vec-audio-large-960h I'm trying to import the name **Data2VecForCTC**, but unsuccessful.
Possibly a typo: **Data2VecForCTC** -> **Data2VecAudioForCTC**

### Expected behavior

```shell
Correct code sample is expected.
```

**Comment by NielsRogge** [comment]
Hi,

Data2Vec is only available on the main branch for now: pip install git+https://github.com/huggingface/transformers.git.

**Comment by Sorrow321** [comment]
Hi

I can't find the name **Data2VecForCTC** in https://github.com/huggingface/transformers/blob/main/src/transformers/__init__.py either.

**Comment by patrickvonplaten** [comment]
Here it is: https://github.com/huggingface/transformers/blob/dced262409177586bb510b6b724c762fb89da0e8/src/transformers/__init__.py#L880

Note that: 

```python
from transformers import Data2VecAudioForCTC

model = Data2VecAudioForCTC.from_pretrained("...")
```

should also already work on master

**Comment by Sorrow321** [comment]
Data2VecForCTC is not the same as Data2Vec**Audio**ForCTC

**Comment by patrickvonplaten** [comment]
There is no `Data2VecForCTC`

**Comment by Sorrow321** [comment]
Yes, but there is on the [website](https://huggingface.co/facebook/data2vec-audio-large-960h)
![image](https://user-images.githubusercontent.com/20703486/165815507-0fb4054f-f6e2-4f48-9a2c-ca21a497ad27.png)

**Comment by NielsRogge** [comment]
Soon we'll have a feature that allows you to report this directly on the model repo ;) stay tuned!

**Comment by NielsRogge** [comment]
But yes I'll fix it, thanks for reporting

**Comment by NielsRogge** [comment]
Opened a PR to fix it: https://huggingface.co/facebook/data2vec-audio-large-960h/discussions/1
