### ISSUE TITLE
Why do I get 13 hidden layers?

### ISSUE THREAD

**Issue by acmilannesta** [huggingface/transformers#1699]
## ❓ Questions & Help

Hi,

When I try to type
```
model = TFRobertaForSequenceClassification.from_pretrained('roberta-base', output_hidden_states=True)
hidden_layers = model([input])

```

The length of hidden_layers is 13. But base model should have 12 layers, right?
And if I want to get the last hidden layer, should I use "hidden_layers[-1]"?

Thanks in advance!

**Comment by julien-c** [comment]
The first element is the embedding output.

Yes, use `hidden_layers[-1]`.
