### ISSUE TITLE
The current equivalent of transformers.models.bert.modeling_bert.gelu

### ISSUE THREAD

**Issue by Pzoom522** [huggingface/transformers#16991]
### System Info

```shell
- `transformers` version: 4.5.0
- Platform: Linux-5.13.0-40-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.11.0+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi, I believe it's an issue relevant to version migration. The code I'm using contains
```
x = transformers.models.bert.modeling_bert.gelu(x)
```
which seems to be no longer usable.

Similar problem was discussed in https://stackoverflow.com/questions/66133626 but with no good answer.

### Expected behavior

Please let me know what is the current API that can be a replacement of `transformers.models.bert.modeling_bert.gelu`, or it's safe to directly use `x = x * 0.5 * (1.0 + torch.erf(x / math.sqrt(2.0)))` instead.

Many thanks!

PS: the link to the migration guide should be changed into https://huggingface.co/docs/transformers/migration.

### Checklist

- [X] I have read the migration guide in the readme. ([pytorch-transformers](https://github.com/huggingface/transformers#migrating-from-pytorch-transformers-to-transformers); [pytorch-pretrained-bert](https://github.com/huggingface/transformers#migrating-from-pytorch-pretrained-bert-to-transformers))
- [X] I checked if a related official extension example runs on my machine.

**Comment by LysandreJik** [comment]
All of those have been refactored in a `ACT2FN` dictionary which is used across the codebase. You can import it as such:

```py
from transformers.activations import ACT2FN

gelu_function = ACT2FN['gelu']
```

Hope that helps!

**Comment by Pzoom522** [comment]
Many thx. Closed : )
