### ISSUE TITLE
wavlm s3prl emotion recognition

### ISSUE THREAD

**Issue by sciai-ai** [huggingface/transformers#17023]
Hi

I have trained a downstream emotion recognition task using s3prl wavlm where a checkpoint has been saved `dev-best.ckpt`. The inference setup in s3prl is not ideal requiring batches of wav files split by session rather a single wav file which is useful in production endpoints. 

@anton-l can you please share how you ported the wav2vec2-er s3prl model to do inference below.

![image](https://user-images.githubusercontent.com/52277510/166095746-7970ef1b-bdb3-4db4-98f2-14395337b3d9.png)

**Comment by anton-l** [comment]
Hi @sciai-ai! You can find the rough model conversion script is here: https://github.com/huggingface/transformers/blob/main/src/transformers/models/wavlm/convert_wavlm_original_s3prl_checkpoint_to_pytorch.py

The command is:
```bash
python convert_wavlm_original_s3prl_checkpoint_to_pytorch.py \
    --base_model_name "microsoft/wavlm-base (depends on your base model)" \
    --config_path "hf_model/config.json (should be modified by hand, probably just add id2label and label2id fields to the base WavLM config.json)" \
    --checkpoint_path "path/to/s3prl/dev-best.ckpt" \
    --model_dump_path "hf_model/output/dir/"
```
