### ISSUE TITLE
Unable to reproduce gigawords results from google/pegasus-gigaword

### ISSUE THREAD

**Issue by xu1998hz** [huggingface/transformers#17039]
@patrickvonplaten

Hi Patrick,

I am trying to reproduce the PEGASUS results for gigaword. I used gigawords in datasets library and directly use its testing portion without further preprocessing. I used PegasusForConditionalGeneration, PegasusTokenizer (I used checkpoint from Google, google/pegasus-gigaword) to decode summary using default setting. However, my ROUGE score is bit deviated from the original paper reported (my results roug1,2,L: 28/12/25 vs 39.65/20.47/36.76). I wondered if my setup was incorrect.

**Comment by patrickvonplaten** [comment]
Hey @xu1998hz,

We're trying to keep Transformers issues for bugs in the core library. Could you try to use the forum instead: https://discuss.huggingface.co/ ? :-)
