### ISSUE TITLE
No separation between Torch and TF examples in create_a_model.md

### ISSUE THREAD

**Issue by ignacioct** [huggingface/transformers#17041]
Hi! 

While writing the Spanish translation of the guide to create a custom mode (#15947), I've come across something that I think it is not intentional. In the section Model, we have this first paragraph explaining how to start initializing and customizing a - custom - model. 

![image](https://user-images.githubusercontent.com/56955040/166233739-9f83de75-0dfc-46c8-b0be-e169d6f7ef3e.png)

And then, immediately after that, the texts repeats itself, but this time using TF models.

![image](https://user-images.githubusercontent.com/56955040/166234019-6887b5b4-6ee0-4a74-a663-d8ba0550e2a9.png)
 
I think there is a missing subsection title separating both ways of doing the procedure, or the information is redundant and one of then should be removed. One way or the other, is strange to be reading this from top to bottom and see some text repeating itself without any clue.

**Comment by stevhliu** [comment]
Hi, thanks for your help in translating the docs! :)

From my end on the `main` version of the docs, there are two separate blocks for PyTorch and TensorFlow content:

![Screen Shot 2022-05-03 at 10 30 01 AM](https://user-images.githubusercontent.com/59462357/166507509-7aabe3d4-ef88-4657-a57e-44ec4d841518.png)

**Comment by ignacioct** [comment]
Oh, I was directly looking using https://github.com/huggingface/transformers/blob/main/docs/source/en/create_a_model.mdx, and there is no separation there I think (that should also be the main version). If that is handled in the docs, I can just go on and replace the text in the same fashion. 

Thank you!
