### ISSUE TITLE
AutoConfig.from_pretrained("model", return_unused_kwargs=True) returns `"_from_auto": True` field against specification

### ISSUE THREAD

**Issue by GabrielKP** [huggingface/transformers#17056]
### System Info

```shell
- `transformers` version: 4.17.0
- Platform: Linux-5.13.0-40-generic-x86_64-with-glibc2.34
- Python version: 3.9.7
- PyTorch version (GPU?): 1.11.0+cu102 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
```

### Who can help?

@sgugger

Small bug in which for some cases `{"_from_auto": True}` is returned [against specification](https://github.com/huggingface/transformers/blob/31ec2cb2badfbdd4c1ac9c6c9b8a74e974984206/src/transformers/models/auto/configuration_auto.py#L646).

Seems to originate [here](https://github.com/huggingface/transformers/blob/31ec2cb2badfbdd4c1ac9c6c9b8a74e974984206/src/transformers/models/auto/configuration_auto.py#L671) and/or [here](https://github.com/huggingface/transformers/blob/31ec2cb2badfbdd4c1ac9c6c9b8a74e974984206/src/transformers/configuration_utils.py#L659)

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Replicable with
```py
>>> from transformers import AutoConfig
>>> config, kwargs = AutoConfig.from_pretrained("bert-base-uncased", return_unused_kwargs=True)
>>> kwargs
{'_from_auto': True}
```

### Expected behavior

There should be no `"_from_auto": True` field in returned dict.
```py
>>> from transformers import AutoConfig
>>> config, kwargs = AutoConfig.from_pretrained("bert-base-uncased", return_unused_kwargs=True)
>>> kwargs
{}
```

**Comment by sgugger** [comment]
I can reproduce, thanks for flagging and for taking the time to give us a clear example of code that fails!
I will try to dive into this and have a fix ready later today.
