### ISSUE TITLE
unable to import from utils_squad 

### ISSUE THREAD

**Issue by shahik** [huggingface/transformers#1705]
Hi, 
    I am using BertForQuestionAnswering on colab and I have installed 
` 
!pip install transformers
!pip install pytorch-transformers
`
when I import 

` from utils_squad import (read_squad_examples, convert_examples_to_features) `

I get the following error:

ModuleNotFoundError: No module named 'utils_squad'

any solution to this? 
Greetings!

**Comment by manishiitg** [comment]
try this 

```
%%bash
rm -r hugging-face-squad
mkdir hugging-face-squad
echo > hugging-face-squad/__init__.py
cd hugging-face-squad
wget 'https://raw.githubusercontent.com/huggingface/pytorch-transformers/master/examples/run_squad.py'
wget 'https://raw.githubusercontent.com/huggingface/pytorch-transformers/master/examples/utils_squad.py'
wget 'https://raw.githubusercontent.com/huggingface/pytorch-transformers/master/examples/utils_squad_evaluate.py'
sed -i 's/utils_squad_evaluate/.utils_squad_evaluate/g' utils_squad.py
sed -i 's/utils_squad/.utils_squad/g' run_squad.py

import importlib
hfs = importlib.import_module('.run_squad', package='hugging-face-squad')

examples = hfs.read_squad_examples(input_file="train-v2.0.json",
                                                is_training=True,
                                                version_2_with_negative=True)



```

**Comment by Santosh-Gupta** [comment]
I am having the same issue, the fix didn't work for me. For convenience, here's a link to a colab notebook with the full code

https://colab.research.google.com/drive/1tNisXX5siuNnkuEQ-X_XdEdDTtdJ0qeL

**Comment by UMaa69** [comment]
> try this
> 
> ```
> %%bash
> rm -r hugging-face-squad
> mkdir hugging-face-squad
> echo > hugging-face-squad/__init__.py
> cd hugging-face-squad
> wget 'https://raw.githubusercontent.com/huggingface/pytorch-transformers/master/examples/run_squad.py'
> wget 'https://raw.githubusercontent.com/huggingface/pytorch-transformers/master/examples/utils_squad.py'
> wget 'https://raw.githubusercontent.com/huggingface/pytorch-transformers/master/examples/utils_squad_evaluate.py'
> sed -i 's/utils_squad_evaluate/.utils_squad_evaluate/g' utils_squad.py
> sed -i 's/utils_squad/.utils_squad/g' run_squad.py
> 
> import importlib
> hfs = importlib.import_module('.run_squad', package='hugging-face-squad')
> 
> examples = hfs.read_squad_examples(input_file="train-v2.0.json",
>                                                 is_training=True,
>                                                 version_2_with_negative=True)
>
@manishiitg ...For this also getting errors....utils_squad.py, & utils_squad_evaluate.py, was not found.

**Comment by JayCC83** [comment]
Hi, when I was trying to wget the scripts, it says 404 not found... Probably it is been removed somewhere? 

`!wget 'https://raw.githubusercontent.com/huggingface/transformers/master/examples/run_squad.py'`

**Comment by Santosh-Gupta** [comment]
I believe the code has been refactored a while ago, maybe try the Dec version of transformers, or update your code to get the location of the new data processors

**Comment by lazyCodes7** [comment]
I was facing this issue and finally, after some thinking, I tried finding utils_squad.py and utils_squad_evaluate.py from this [repo](https://github.com/nlpyang/pytorch-transformers) and copied the link of the raw version of those two files. So these commands won't give a 404 error and import then worked for me:)
`
!wget 'https://raw.githubusercontent.com/nlpyang/pytorch-transformers/master/examples/utils_squad.py'
`
`
!wget 'https://raw.githubusercontent.com/nlpyang/pytorch-transformers/master/examples/utils_squad_evaluate.py'
`

**Comment by JayCC83** [comment]
Thanks @lazyCodes7!

**Comment by lazyCodes7** [comment]
> Thanks @lazyCodes7!

cool!
