### ISSUE TITLE
Regression Loss

### ISSUE THREAD

**Issue by JiajunBao** [huggingface/transformers#1706]
I want `BertForSequenceClassification` to compute regression loss. I load the pre-trained model through
```
config = BertConfig.from_pretrained('bert-base-uncased')
config.num_labels = 1  # Is it proper to set the num_label in this way?
model = BertForSequenceClassification(config)
```

How shall I change the num_labels properly?

Thank you!

**Comment by LysandreJik** [comment]
That is a good way to load the labels! 

Please be aware, however, that by loading the configuration this way you will not load the weights for your model associated with the `bert-base-uncased` checkpoint as you would have done had you used the `BertForSequenceClassification.from_pretrained(...)` method.
