### ISSUE TITLE
When will the official 4.19 release be?

### ISSUE THREAD

**Issue by yinzhangyue** [huggingface/transformers#17077]
### Feature request

The official 4.19 release

### Motivation

\

### Your contribution

\

**Comment by LysandreJik** [comment]
Likely Thursday!

**Comment by yinzhangyue** [comment]
Thank you very much!

**Comment by LysandreJik** [comment]
It was released a few hours ago.

**Comment by yinzhangyue** [comment]
OK~ Thank you so much for your help!
