### ISSUE TITLE
bugs with run_summarization script

### ISSUE THREAD

**Issue by jimkim3** [huggingface/transformers#1707]
Hi
The evaluation part of this script is missing, I tried to complete it myself but this code does not generation proper string during decoding part for me and does not converege, encoder and decoder weights are not tied as the paper, could you please add the generated text as the output of evaluation code, also please complete the evaluation code, maybe you could use some codes in run_generation.py for this, thanks

**Comment by rlouf** [comment]
The summarization/generation scripts are still work in progress. They should be included in the next release.
