### ISSUE TITLE
The id of the word obtained by tokenizer.encode does not correspond to the id of the word in vocab.txt

### ISSUE THREAD

**Issue by lijinze9456yy000** [huggingface/transformers#1708]
## ❓ Questions & Help

hello，I encountered a problem，code show as below.
tokenizer=BertTokenizer.from_pretrained('bert-base-uncased')
input_ids=torch.LongTensor(tokenizer.encode("[CLS] the 2018 boss nationals [SEP]"))
print(input_ids)
The result is:tensor([  101,  1996,  2760,  5795, 10342,   102]) , but In the voab.txt, the id of "the" word is 8174, not 1996. Why is this the reason for the berttokenizer token dictionary error?

**Comment by LysandreJik** [comment]
Hi, in the `bert-base-uncased` vocab.txt file, the id of the token "the" is 1996. You can see it [inside the file, where "the" is on the row 1996](https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt). You can also check it out directly in the tokenizer with the following command: 

```py
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokenizer.vocab.get("the")  # 1996
```
