### ISSUE TITLE
pip install "sacremoses>=0.0.50" breaks on SageMaker Studio

### ISSUE THREAD

**Issue by juliensimon** [huggingface/transformers#17096]
### System Info

```shell
This was verified today on a fresh SageMaker Studio instance running in us-west-2.

It's not a Transformer issue, but as sacremoses is a dependency, this is likely to break 'pip install transformers' on SageMaker Studio at some point.
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1) Open an SM Studio notebook

2) Run the following cell:
```
%%sh
pip install "sacremoses>=0.0.50"
```

The obvious workaround for now is
```
pip install "sacremoses==0.0.49"
```

### Expected behavior

```shell
sacremoses should install without error.
```

**Comment by LysandreJik** [comment]
Thanks for the issue @juliensimon, this should be fixed by https://github.com/huggingface/transformers/pull/17049. It will be in the next release which should drop early next week.

**Comment by LysandreJik** [comment]
Should be fixed now!
