### ISSUE TITLE
Docs link to example scripts is broken

### ISSUE THREAD

**Issue by ftnext** [huggingface/transformers#17098]
This is about **documentation link error**.

## Error

At https://huggingface.co/docs/transformers/main/en/main_classes/trainer#trainer
>It’s used in most of the [example scripts](https://huggingface.co/docs/transformers/main/en/examples).

The link *example scripts* https://huggingface.co/docs/transformers/main/en/examples is broken, got 404.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/21273221/166940684-aa6489cb-d47a-4c94-beab-c197d0b588f0.png">

## Source

https://github.com/huggingface/transformers/blob/dd16a113a48cc2117953397e9611383577d6a70d/docs/source/en/main_classes/trainer.mdx#L15

## Question

The *example scripts* link means https://github.com/huggingface/transformers/tree/main/examples ?

**Comment by stevhliu** [comment]
Hi, a PR has been opened to fix this issue. Thanks for reporting! :)

The problem was `examples` had been removed from the `toctree` which caused the link to be broken.
