### ISSUE TITLE
CTRL does not react to the "seed" argument

### ISSUE THREAD

**Issue by iwolford** [huggingface/transformers#1710]
Using latest master branch and run_generation.py.
When passing different seeds to GPT-2 it produces different results, as expected,
however CTRL does not.

**GPT-2** 
python run_generation.py **--seed=42** --model_type=gpt2 --length=10 --model_name_or_path=gpt2 --prompt="Transformers movie is"
**>>> a great example of bringing early, action-packed**

python run_generation.py **--seed=22** --model_type=gpt2 --length=10 --model_name_or_path=gpt2 --prompt="Transformers movie is"
**>>> a lot of fun. It's a decent one**

**CTRL**
python run_generation.py -**-seed=42** --model_type=ctrl --length=10 --model_name_or_path=ctrl --temperature=0 --repetition_penalty=1.2 --prompt="Links Transformers movie is"
**>>> a big deal for the company, and it has been**

python run_generation.py **--seed=22** --model_type=ctrl --length=10 --model_name_or_path=ctrl --temperature=0 --repetition_penalty=1.2 --prompt="Links Transformers movie is"
**>>> a big deal for the company, and it has been**

**Comment by tanselmi** [comment]
Noticed the same thing on the Salesforce version as well.

**Comment by TheEdoardo93** [comment]
Do you test with [this url](https://github.com/salesforce/ctrl/blob/master/generation.py)?
@tanselmi If not, please specify which script do you try out

**Comment by TheEdoardo93** [comment]
> Noticed the same thing on the Salesforce version as well.

In general, is it a bug or a "model property"?

**Comment by TheEdoardo93** [comment]
> > Noticed the same thing on the Salesforce version as well.
> 
> In general, is it a bug in the code implementation of the CTRL model or a "model property" (i.e. the CTRL model is not affect by a random seed set at the start of the process) ?

@tanselmi

**Comment by LysandreJik** [comment]
Hi, this is not due to a bug, this is due to your argument `temperature=0`, which implies greedy sampling via argmax, rather than polynomial sampling like it is usually done.

You can try it out with a temperature of 0.2:

With seed 42 - Links Transformers movie is **a huge hit in the box office and has been**
With seed 22 - Links Transformers movie is **a big deal for the studio. The first film was**

**Comment by tanselmi** [comment]
Thanks for the update and explanation. I will give it a go.

**Comment by iwolford** [comment]
@LysandreJik I confirm setting temperature to non-zero makes the seed argument work fine.
Thank you!
