### ISSUE TITLE
Hello, how to upload a .ckpt file in TFBertForSequenceClassification?

### ISSUE THREAD

**Issue by hecongqing** [huggingface/transformers#1718]
## ❓ Questions & Help

I find the TFBertForSequenceClassification only can upload .h5 file

**Comment by TheEdoardo93** [comment]
What model is referring to this .ckpt file? If the model is BERT or ALBERT, you can:
- use the `convert_X_original_tf_checkpoint_to_pytorch --tf_checkpoint_path=dir/model.ckpt-xxx`, where _X_ is albert or bert
- load the .pt model into Transformers as usual

**Comment by zwqjoy** [comment]
@TheEdoardo93  if load the .pt model into Transformers as usual.  I think it will be pytorch model.
But I want use the TFBertForSequenceClassification to train with the model.fit, and with the mutil gpu with tf Strategy.

What can I do?
