### ISSUE TITLE
Support MobileBert model in transformer.onnx package

### ISSUE THREAD

**Issue by YUNQIUGUO** [huggingface/transformers#17251]
### Feature request

Just wondering would it be possible to support mobilebert in transformer.onnx package? or is there any quick hack that we can try to export the mobilebert model from huggingface to onnx?

Thanks. 

The mobile I am trying is : `google/mobilebert-uncased`

And the command : `python -m transformers.onnx --model=google/mobilebert-uncased onnx/`

`raise KeyError(
KeyError: "mobilebert is not supported yet. Only ['albert', 'bart', 'mbart', 'bert', 'ibert', 'camembert', 'distilbert', 'flaubert', 'marian', 'm2m-100', 'roberta', 't5', 'xlm-roberta', 'gpt2', 'gpt-j', 'gpt-neo', 'layoutlm', 'electra', 'vit', 'beit', 'blenderbot', 'blenderbot-small'] are supported. If you want to support mobilebert please propose a PR or open up an issue."`

### Motivation

Trying to get mobileBert model exported to onnx format to further investigate and for the usage of some ORT mobile scenarios.

### Your contribution

A PR is not available for now.

**Comment by LysandreJik** [comment]
It seems it is supported now: https://github.com/huggingface/transformers/pull/17029

**Comment by YUNQIUGUO** [comment]
Thanks for the pointer to this pr!
