### ISSUE TITLE
Swin Transformer V2

### ISSUE THREAD

**Issue by RyanHuangNLP** [huggingface/transformers#17268]
### Model description

[Swin Transformer V2: Scaling Up Capacity and Resolution](https://arxiv.org/pdf/2111.09883.pdf)

repo origin: [Swin Transformer V2](https://github.com/microsoft/Swin-Transformer#updates)

repo timm: [Swin Transformer V2](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/swin_transformer_v2.py)

all the model the pretrain is ready

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

repo origin: [Swin Transformer](https://github.com/microsoft/Swin-Transformer#updates)

**Comment by NielsRogge** [comment]
Marking this as a good first issue as Swin v2 only adds a couple of small design improvements compared to Swin v1.

One could use the [add new-model-like](https://github.com/huggingface/transformers/tree/main/templates/adding_a_new_model#add-new-model-like-command) feature to copy all Swin files, and then implement Swin v2 by tweaking these files.

**Comment by jQuinRivero** [comment]
Hey! Can I give it a shot?

**Comment by nandwalritik** [comment]
@NielsRogge I would like to add this model.

**Comment by NielsRogge** [comment]
Hi :) sure, maybe you can give me your email addresses such that we can set up a Slack channel for coordination.

**Comment by nandwalritik** [comment]
> Hi :) sure, maybe you can give me your email addresses such that we can set up a Slack channel for coordination.

Here is mine : ritiknandwal021@gmail.com

**Comment by sabarish-srinivasan** [comment]
Hey @NielsRogge, I'd like to help out as well. My email is srinivasansabarish@gmail.com

**Comment by jQuinRivero** [comment]
my email is joaquinrivero94@gmail.com

**Comment by NielsRogge** [comment]
Thanks, I'll create one. You should receive an invite soon

**Comment by skanjila** [comment]
Hi all is this work complete, I'd love to help if possible.
