### ISSUE TITLE
Loading facebook/regnet-y-040 FeatureExtractor fails mysteriously unless pillow is installed

### ISSUE THREAD

**Issue by eric-mitchell** [huggingface/transformers#17266]
### System Info

```shell
I'm running transformers installed directly from `ee393c0`.
```

### Who can help?

@NielsRogge @sgugger 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

    import transformers
    feature_extractor = transformers.AutoFeatureExtractor.from_pretrained("facebook/regnet-y-040")

If I don't have pillow installed, the second line fails with:

    AttributeError: module transformers.models.convnext has no attribute ConvNextFeatureExtractor

If I then run `pip install pillow`, everything works as expected.

### Expected behavior

```shell
The feature extractor should be loaded successfully.
```

**Comment by sgugger** [comment]
Will look into this today. There should be a way to indicate the missing dependencies when the object is not found by using our dummy objects.
