### ISSUE TITLE
about the opt model KeyError: 'opt'

### ISSUE THREAD

**Issue by DericZhao** [huggingface/transformers#17296]
### System Info

```shell
I just copy the code from the model card on the https://huggingface.co/facebook/opt-30b, then there is an error, can you help me to find what's the problem of it?

Traceback (most recent call last):
  File "D:\SentenceRewrite\opt.py", line 4, in <module>
    model = AutoModelForCausalLM.from_pretrained("facebook/opt-30b", torch_dtype=torch.float16).cuda()
  File "D:\Anaconda\envs\torch\lib\site-packages\transformers\models\auto\auto_factory.py", line 382, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "D:\Anaconda\envs\torch\lib\site-packages\transformers\models\auto\configuration_auto.py", line 517, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "D:\Anaconda\envs\torch\lib\site-packages\transformers\models\auto\configuration_auto.py", line 266, in __getitem__
    raise KeyError(key)
KeyError: 'opt'
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model = AutoModelForCausalLM.from_pretrained("facebook/opt-30b", torch_dtype=torch.float16).cuda()

# the fast tokenizer currently does not work correctly
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-30b", use_fast=False)

prompt = "Hello, I'm am conscious and"

input_ids = tokenizer(prompt, return_tensors="pt").input_ids.cuda()

generated_ids = model.generate(input_ids)

tokenizer.batch_decode(generated_ids, skip_special_tokens=True)

### Expected behavior

```shell
KeyError: 'opt' how to solve it?
```

**Comment by violetymr** [comment]
I met the same problem. Have you fixed this?

**Comment by DericZhao** [comment]
> 

You can download the latest version of transformers, have a good day.

**Comment by roshkins** [comment]
@DericZhao  I installed the latest version, I am still getting the error. Any help?

**Comment by xuyifan-0731** [comment]
I met the same problem. Any solutions?

**Comment by lkywlp99** [comment]
me too!my transformers version is 4.4.1,I still have the problem.

**Comment by sgugger** [comment]
`pip install --upgrade transformers`

**Comment by knn-art** [comment]
Check the versions of python(>=3.8 required) and pytorch , they may not match transformers
