### ISSUE TITLE
add doctests for data2VecText

### ISSUE THREAD

**Issue by Ruihua-Fang** [huggingface/transformers#17338]
### Feature request

Enable doctests for data2VecText model, as part of https://github.com/huggingface/transformers/issues/16292

### Motivation

please see https://github.com/huggingface/transformers/issues/16292

### Your contribution

implement this feature

**Comment by patrickvonplaten** [comment]
Hey @Ruihua-Fang,

Would you like to give it a try? :-)

**Comment by Ruihua-Fang** [comment]
Hey @patrickvonplaten , yep, Thanks :)
