### ISSUE TITLE
VisualBERT: Low accuracy on VQA v2

### ISSUE THREAD

**Issue by nikich28** [huggingface/transformers#17360]
I use the exact code from visual bert demo, but only got about 46% accuracy on VQA v2 validation data. Has anyone had the same issue?

**Comment by 25icecreamflavors** [comment]
Has anyone found a problem solution?

**Comment by guanhdrmq** [comment]
Hi I have the same issues? One possible reason is the id2label and label2id in config.json. The other possbile reason is the frcnn image features are not exact. Can anyone solve this issue? Thank you very much.

**Comment by guanhdrmq** [comment]
@nikich28 Hi nick, have you solve this issue? many thanks
