### ISSUE TITLE
About model loading without parameter

### ISSUE THREAD

**Issue by LiuJinzhe-Keepgoing** [huggingface/transformers#17362]
https://github.com/huggingface/transformers/blob/6e535425feae20ca61a8b10ae5e8a7fab4d394ba/src/transformers/models/vilt/modeling_vilt.py#L1175
Hello, I want to use vilt in other fields through from_ Can Pretrain only load models without loading model parameters. Because the coco dataset is very different from my domain dataset. I don't know if there is any way.

**Comment by NielsRogge** [comment]
To initialize a model without any pretrained weights, you can just load it with a configuration:

```
from transformers import ViltConfig, ViltForImageAndTextRetrieval

config = ViltConfig()
model = ViltForImageAndTextRetrieval(config)
```
All weights will be randomly initialized.

**Comment by NielsRogge** [comment]
Closing this issue, as I believe I've answered it. Feel free to re-open.
