### ISSUE TITLE
`_fast_init` overwrites weights passed to custom model

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#17370]
### System Info

```shell
Transformers > 4.6.0
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Copy-pasting an issue from https://github.com/huggingface/transformers/pull/11471#issuecomment-1132324119 into a new issue to make it more visible as multiple people could have this problem.

When abstracting a `transformers` model and passing custom layers to the init method, the initialization can show strange behavior. 

Consider the following case (taken from @josh-heyer ):

```python
from torch.nn import Linear
from transformers import BertModel


class MyCustomModel(BertModel):
    def __init__(self, config, custom_layer=None):
        super().__init__(config)
        if custom_layer is not None:
            self.custom_layer = custom_layer
        else:
            self.custom_layer = Linear(1024, 1024)


if __name__ == "__main__":
    import transformers
    print(transformers.__version__)
    layer = Linear(1024, 1024)
    print(layer.weight.sum())
    custom_model = MyCustomModel.from_pretrained('bert-base-uncased', custom_layer=layer)
    # used to be the same as the layer above, but it is "re-initialized" in the from_pretrained method
    print(custom_model.custom_layer.weight.sum())
```

What will happen here since `_fast_init` was introduced in 4.6.0: https://github.com/huggingface/transformers/pull/11471 is that the weights of the custom layer will be overriden.

### Expected behavior

It might be reasonable to state that the custom layer should **not** be overriden.

**Comment by patrickvonplaten** [comment]
To describe what happens here:

`_fast_init` compares the weight names of the state_dict of `bert-base-uncased` with all weight names of the random state_dict of `MyCustomModel` **after** having called the `__init__(...)` method of `MyCustomModel`. Now after having called the `__init__(...)` `self.custom_layer` is a missing key and will be overridden.

This seems unexpected from the outside, but after having looked a bit into the interals of `from_pretrained(...)`, we sadly cannot really change this behavior and don't consider it a bug.

In our opinion the problems rather lies in the following:

- 1. We **never** abstract `nn.Module` model classes that have an `__init__(...)` method except `PretrainedModel` which has an absolute minimal `__init__(...)` method that just sets the config. 
In the whole code base of `transformers`, models only abstract from their `...PretrainedModel` class, *e.g.* `BertModel` abstracts from `BertPretrainedModel`, but those classes don't have an __init__ method. 
This way we can be sure that the only `__init__(...)` method that matters is the one of `BertModel`. Now this is broken here. `MyCustomModel` abstracts away `BertModel` which is exactly not what we want. Instead of abstraction we rely on **modularization**, which in our opinion, is less error-prone and easier to understand. 

- 2. We never have the option to pass layers into the `__init__` for the outer-most `nn.Module` classes. Surely, one should **never** pass a layer through `from_pretrained(...)` as this breaks the assumption that all weights are stored in the model (*i.e.* `"bert-base-cased"`). All layers should be defined **unconditionally** in the `__init__(...)` method of the outermost model class.

**Comment by patrickvonplaten** [comment]
To solve the problem above, we recommend to instead of using abstraction, to just use modularization:


```python
from torch.nn import Linear
from transformers import BertPreTrainedModel, BertModel


class MyCustomModel(BertPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.bert = BertModel(config)
        self.costum_layer = Linear(1024, 1024)

   def forward(self, ...):
       self.bert(....)

   def set_costum_layer(self, linear_embed):
       self.custom_layer = linear_embed
```

Note that this is also exactly how we coded up `BertForMaskedLM`: https://github.com/huggingface/transformers/blob/3fd7de49f4d53832621ef67cfd1825b000323250/src/transformers/models/bert/modeling_bert.py#L1292

**Comment by john-heyer** [comment]
Thanks @patrickvonplaten  - btw you tagged "josh-heyer" rather than "john"* haha. I'll take a deeper look and see how we can change our model initialization.

**Comment by patrickvonplaten** [comment]
Ups sorry :sweat_smile:
