### ISSUE TITLE
BART

### ISSUE THREAD

**Issue by clmnt** [huggingface/transformers#1738]
# 🌟New model addition

## Model description

method for pre-training seq2seq models by de-noising text. BART outperforms previous work on a bunch of generation tasks (summarization/dialogue/QA), while getting similar performance to RoBERTa on SQuAD/GLUE

## Open Source status

* [ ] the model implementation is available: not yet
* [ ] the model weights are available: not yet
* [ ] who are the authors: @yinhanliu @ernamangoyal

**Comment by julien-c** [comment]
Duplicate of #1676
