### ISSUE TITLE
AutoTokenizer _batch_encode_plus method don't have add_prefix_space argument

### ISSUE THREAD

**Issue by c00k1ez** [huggingface/transformers#17391]
### System Info

```shell
- `transformers` version: 4.20.0.dev0
- Platform: macOS-12.3.1-arm64-arm-64bit
- Python version: 3.8.12
- Huggingface_hub version: 0.6.0
- PyTorch version (GPU?): 1.11.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no
```

### Who can help?

@SaulLu @LysandreJik
Hi, im just noticed that `AutoTokenizer._batch_encode_plus` method don't have `add_prefix_space` argument if I init it as `roberta-base` model.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
tokenizer = transformers.AutoTokenizer.from_pretrained('roberta-base')
input_ids = tokenizer('test string', add_prefix_space=True).data["input_ids"]
# Output: TypeError: _batch_encode_plus() got an unexpected keyword argument 'add_prefix_space'
```

### Expected behavior

```shell
tokenizer = transformers.AutoTokenizer.from_pretrained('roberta-base')
input_ids = tokenizer('test string', add_prefix_space=True).data["input_ids"]
# Output: >>> input_ids [0, 1296, 6755, 2]
```

**Comment by SaulLu** [comment]
Hi @c00k1ez , 

I think I can guess a little confusion, this argument must be specified during the initialization of the tokenizer or redefined when using `from_pretrained` but it won't work in the `__call__` method. 

If any documentation has misled you, I would be very grateful if you would share it with us! :pray: (and even better that you propose an improvement in PR :smile: )

Here is the snippet which will give what you expect:
```python
tokenizer = transformers.AutoTokenizer.from_pretrained('roberta-base', add_prefix_space=True)
input_ids = tokenizer('test string').data["input_ids"]
```

**Comment by c00k1ez** [comment]
Thank you for your answer, it becomes much clearer!
I think it seems great to add smth like 
```python
>>> # Download vocabulary from huggingface.co and define model-specific arguments
>>> tokenizer = AutoTokenizer.from_pretrained("roberta-base", add_prefix_space=True)
```  
to

https://github.com/huggingface/transformers/blob/71e602725b90f63f404109bae9f72cbdf755477b/src/transformers/models/auto/tokenization_auto.py#L476

What do u think?

**Comment by SaulLu** [comment]
It makes sense to me! Do you want to open a PR with this proposal?

**Comment by c00k1ez** [comment]
Yeah, no problem

**Comment by michaelomahony-edgetier** [comment]
> Hi @c00k1ez ,
> 
> I think I can guess a little confusion, this argument must be specified during the initialization of the tokenizer or redefined when using `from_pretrained` but it won't work in the `__call__` method.
> 
> If any documentation has misled you, I would be very grateful if you would share it with us! 🙏 (and even better that you propose an improvement in PR 😄 )
> 
> Here is the snippet which will give what you expect:
> 
> ```python
> tokenizer = transformers.AutoTokenizer.from_pretrained('roberta-base', add_prefix_space=True)
> input_ids = tokenizer('test string').data["input_ids"]
> ```

Hi @SaulLu, some documentation which I found misleading in relation to this: https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig.bad_words_ids(List[List[int]],
Huggingface Docs > Transformers > Text Generation > GenerationConfig > Params > bad_words_ids

"**bad_words_ids**(List[List[int]], optional) — List of token ids that are not allowed to be generated. In order to get the token ids of the words that should not appear in the generated text, use tokenizer(bad_words, add_prefix_space=True, add_special_tokens=False).input_ids."

Here, it seems like the docs are telling us to use add_prefix_space=True in the `__call__` method.
