### ISSUE TITLE
No 'Translation template'

### ISSUE THREAD

**Issue by mfumanelli** [huggingface/transformers#17404]
Hi!

Following the [TRANSLATING guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md), I realised that there is no 'Translation template' when I try to open an issue.

I would like to try to fix the bug myself by creating the template from: [#15947](https://github.com/huggingface/transformers/issues/15947) and [#16824](https://github.com/huggingface/transformers/issues/16824), unless the file with the template already exists and is simply in some other folder.

**Comment by omarespejel** [comment]
Hi @mfumanelli! Thank you for your issue 🤗. Would the translation be for Italian? @sgugger @osanseviero, would this be a step we would wish to pursue?

If that is the case, @mfumanelli, you can use the format in issues #15947 and #16824. Particularly:
- Use informal language.
- Use inclusive language; eg. not letting know any gender and rather talking about "the people".

**Comment by mfumanelli** [comment]
Yes @omarespejel, in case it would be for Italian. Perfect for the two suggestions ☺️.

Then I'll wait to see if it's something you want to pursue at the moment or not, thanks!

**Comment by osanseviero** [comment]
Yes! Let's do this for Italian and any other language the community would like to help translating :fire: 

@omarespejel, do we have a smaller list of documents that need to get translated that are higher priority? I think Get Started section + Tutorial section is the most important, but I might be wrong

**Comment by mfumanelli** [comment]
If you agree as a first step I will shortly make a PR to add the file "Translation template" to the transformers/.github/ISSUE_TEMPLATE folder. So that anyone who wants to translate into other languages can follow the [TRANSLATING guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md), and select the "Translation template" from the "New issue" button 🤗.

I will then open a dedicated issue for Italian so that other people can collaborate. I will ask among my contacts if others want to help with the translation 🌈

**Comment by mfumanelli** [comment]
Perfect, then I will open the issue for Italian translation. Thanks! 🤗🌈🌈

**Comment by omarespejel** [comment]
Sure @mfumanelli you can open it! Thank you 🤗

I can edit it if when necessary, no problem with that. Also please let me know if you have any doubt 🚀

**Comment by mfumanelli** [comment]
Thanks @omarespejel! I created it, you can find it here [#17459](https://github.com/huggingface/transformers/issues/17459). If you agree we can close this issue 🌈

**Comment by omarespejel** [comment]
Agreed! Thank you @mfumanelli 🤗. On Monday I will send a tweet directed to the Italian-speaking community that wants to contribute to #17459 🇮🇹. I will let you know,
