### ISSUE TITLE
illegal hardware instruction

### ISSUE THREAD

**Issue by Jasperty** [huggingface/transformers#17402]
### System Info

```shell
i use macbookpro, and pip install transformers, but i get this error:
>>> from transformers import DistilBertConfig
zsh: illegal hardware instruction  python
could you help me?
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

zsh: illegal hardware instruction  python

### Expected behavior

```shell
zsh: illegal hardware instruction  python
```

**Comment by ArthurZucker** [comment]
I think this is due to you installation of tensorflow and not necessarily the library  . 
Did you try installing with 
```
conda install -c apple  tensorflow-deps
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
```

**Comment by aus10powell** [comment]
I'm having the same issue. It happened with the same code recently after installing Big Sur.

**Comment by ApparaoMulpuri** [comment]
I am still getting this in macOS.
