### ISSUE TITLE
The tokenizer config for OPT-30B is missing a pad token

### ISSUE THREAD

**Issue by aninrusimha** [huggingface/transformers#17425]
### System Info

```shell
Version 4.20.0.dev0, built from source
Issue is in https://huggingface.co/facebook/opt-30b/blob/main/tokenizer_config.json
```

### Who can help?

@patrickvonplaten has his name in the code :)
Discovered when testing the OPT models on various datasets.
https://huggingface.co/facebook/opt-30b/blob/main/tokenizer_config.json is missing a padding token
https://huggingface.co/facebook/opt-13b/blob/main/tokenizer_config.json looks to have the real config for opt-13b?

https://huggingface.co/facebook/opt-13b/blob/main/tokenizer_config.json 
{"errors": "replace", "unk_token": {"content": "</s>", "single_word": false, "lstrip": false, "rstrip": false, "normalized": true, "__type": "AddedToken"}, "bos_token": {"content": "</s>", "single_word": false, "lstrip": false, "rstrip": false, "normalized": true, "__type": "AddedToken"}, "eos_token": {"content": "</s>", "single_word": false, "lstrip": false, "rstrip": false, "normalized": true, "__type": "AddedToken"}, "pad_token": {"content": "<pad>", "single_word": false, "lstrip": false, "rstrip": false, "normalized": true, "__type": "AddedToken"}, "add_prefix_space": false, "add_bos_token": true, "special_tokens_map_file": null, "name_or_path": "patrickvonplaten/opt-30b", "tokenizer_class": "GPT2Tokenizer"}

https://huggingface.co/facebook/opt-30b/blob/main/tokenizer_config.json
{"errors": "replace", "bos_token": {"content": "<s>", "single_word": false, "lstrip": false, "rstrip": false, "normalized": true, "__type": "AddedToken"}, "eos_token": {"content": "</s>", "single_word": false, "lstrip": false, "rstrip": false, "normalized": true, "__type": "AddedToken"}, "add_prefix_space": false, "special_tokens_map_file": null, "name_or_path": "patrickvonplaten/opt_gpt2_tokenizer", "tokenizer_class": "GPT2Tokenizer"}

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the following code snippet

```
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset

dataset = load_dataset("wikitext", "wikitext-2-raw-v1", split="validation")
dataset = [s['text'] for s in dataset if s['text'] != '']
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-30b", use_fast=False)
encoded = tokenizer(dataset, 
            return_tensors="pt", 
            padding=True)
```
You will see an error because the tokenizer lacks a padding token.

### Expected behavior

```shell
The OPT-30B tokenizer has a padding token and pads the input.
```

**Comment by patrickvonplaten** [comment]
Fixed it - https://huggingface.co/facebook/opt-30b/discussions/1
