### ISSUE TITLE
Make all configs nicely readable

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#17432]
### Feature request

All configs nicely readable (tokenizers & feature extractor)

### Motivation

https://huggingface.co/facebook/opt-30b/discussions/1

### Your contribution

Happy to do it early next week - happy if someone else wants to take it over though!

**Comment by julien-c** [comment]
in strong favor of this!

**Comment by patrickvonplaten** [comment]
PR: https://github.com/huggingface/transformers/pull/17457
