### ISSUE TITLE
XLM-Roberta offset mapping is off by one in case of whitespace-subwords

### ISSUE THREAD

**Issue by robvanderg** [huggingface/transformers#17454]
### System Info

```shell
- `transformers` version: 4.19.2
- Platform: Linux-5.4.0-94-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.6.0
- PyTorch version (GPU?): 1.7.1+cu110 (True)
- Tensorflow version (GPU?): 2.9.1 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

@LysandreJik @SaulLu

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

>>> from transformers import AutoTokenizer
>>> tokenizer = AutoTokenizer.from_pretrained('xlm-roberta-large', use_fast=True)
>>> tokenizer.tokenize('Quality of work is sufficient')
['▁Quality', '▁of', '▁work', '▁is', '▁', 'sufficient']
>>> tokenizer.encode_plus('Quality of work is sufficient', return_offsets_mapping=True)
{'input_ids': [0, 124604, 111, 4488, 83, 6, 129980, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1], 'offset_mapping': [(0, 0), (0, 7), (8, 10), (11, 15), (16, 18), (19, 20), (19, 29), (0, 0)]}

### Expected behavior

```shell
The third-last offset-tuple (19,20) overlaps with the second-last offset-tuple(19,29). I believe that this should be (18,19), and thus refer to the whitespace.
```

**Comment by ydshieh** [comment]
I think @robvanderg is right (with my intuitive understanding). Since `return_offsets_mapping` is only for fast tokenizer, let me kindly tag @Narsil here

The results should be like
`... (18, 19), (19, 29) ...`
I think.
