### ISSUE TITLE
How to stop wordpiece-tokenizing in BertTokenizer?

### ISSUE THREAD

**Issue by RichardHWD** [huggingface/transformers#1745]
Default BertTokenizer may split one word into two parts or three parts, which is harmful to token labeling task because it will make sentence length lager than input length. It is difficult to fuse these parts back to one representation.
So, how to stop this operation in BertTokenizer? Or there are alternative Tokenizers without spliting words?

**Comment by julien-c** [comment]
No, that's how the model works.

Short of creating your own model (with you own custom tokenizer) there's no way to do what you want to do.

**Comment by RichardHWD** [comment]
Okkkkkk, it is unreasonable ....
