### ISSUE TITLE
How to use gpt-2-xl with run_generation.py

### ISSUE THREAD

**Issue by avianion** [huggingface/transformers#1747]
## ❓ Questions & Help

I am currently running the run_generation.py and putting the model as gpt-2, however I am not satisfied with the results frm the small model.

How can I insert the big model instead?

**Comment by LysandreJik** [comment]
You're probably using the command:
```
python run_generation.py --model_type=gpt2 --model_name_or_path=gpt2
```

to use GPT2-XL for generation you would change the last argument to `gpt2-xl`:
```
python run_generation.py --model_type=gpt2 --model_name_or_path=gpt2-xl
```

**Comment by avianion** [comment]
ah. its because the latest version isnt available on pypi yet. and i pip installed it. 2.1.1 is the version I've got installed.

Is there any way to force pip to install the latest version that was commited 21 hours ago.

**Comment by LysandreJik** [comment]
Ah yes we're yet to release a pypi version with GPT2-XL. To install from source you would have to do:

```
pip install git+https://github.com/huggingface/transformers
```

**Comment by PearlW1** [comment]
pip install transformers==3.4.0
this version of transforrmers solved my problem: OSError: Model name 'ckiplab/gpt2-base-chinese' was not found in model name list (gpt2, gpt2-medium, gpt2-large, gpt2-xl, distilgpt2). We assumed 'ckiplab/gpt2-base-chinese' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.
