### ISSUE TITLE
Released OpenAI GPT-2 1.5B model

### ISSUE THREAD

**Issue by TheEdoardo93** [huggingface/transformers#1748]
## 🚀 Feature

- [ ] Blog: [https://openai.com/blog/gpt-2-1-5b-release/](url)
- [ ] Code: [https://github.com/openai/gpt-2](url)
- [ ] Dataset: [https://github.com/openai/gpt-2-output-dataset](url)

## Motivation

A bigger model for text generation which is more human than the OpenAI GPT-2 774M parameters

## Additional context

Maybe this is not the most requested feature by AI researchers. Maybe, it's better to implement and standardize **new** NLG models!

**Comment by LysandreJik** [comment]
Hi, GPT-2 XL was added yesterday with commit d7d36181fdefdabadc53adf51bed4a2680f5880a

**Comment by TheEdoardo93** [comment]
Yes, sorry for opening a new issue! I didn't see this commit. I'll close the issue! Thank you for your time!
