### ISSUE TITLE
model.parallelize() for OPT models 

### ISSUE THREAD

**Issue by MikeWangWZHL** [huggingface/transformers#17482]
### Feature request

It would be great if we can have function for fitting OPT model on multiple GPUs using **model.parallelize()**, similar to what we already have for [GPT-J](https://github.com/huggingface/transformers/blob/6e535425feae20ca61a8b10ae5e8a7fab4d394ba/src/transformers/models/gptj/modeling_gptj.py#L494)

### Motivation

It would be extremely helpful for fitting large OPT models such as opt-30b, opt-13b. An ideal solution would be similar to what has been integrated in [GPT-J](https://github.com/huggingface/transformers/blob/6e535425feae20ca61a8b10ae5e8a7fab4d394ba/src/transformers/models/gptj/modeling_gptj.py#L494), where we can simply call **model.parallelize()** to load the model on multiple gpus.

### Your contribution

glad to help on making this feature possible

**Comment by MichaelZhouwang** [comment]
@sgugger Hi, that's very helpful for me. However I wonder what's the difference between directly using ```AutoModel.from_pretrained(checkpoint, device_map="auto")```  and that using ```load_checkpoint_and_dispatch()``` and ```infer_auto_device_map()```? Does both of them support fine-tuning something like OPT-30B on multiple GPUs with model parallelism? Thanks a lot for your help!

**Comment by sgugger** [comment]
No this is inference only. For training/fine-tuning we recommend the use of DeepSpeed Zero-3.
