### ISSUE TITLE
modeling_swin.py img_mask doesn't have expected torch dtype 

### ISSUE THREAD

**Issue by LiweiPeng** [huggingface/transformers#17481]
### System Info

```shell
transformers: master branch
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

How to repro:
  Run Swin Transformer with NVIDIA mixed precision apex amp opt_level=O2.

The problem is at this line: https://github.com/huggingface/transformers/blob/main/src/transformers/models/swin/modeling_swin.py#L600, it creates img_mask as float32 type, which will conflict other types (float16) when mixed precision O2 is used.

One way to fix  is shown below:
```
-    def get_attn_mask(self, height, width):
+    def get_attn_mask(self, height, width, dtype):
         if self.shift_size > 0:
             # calculate attention mask for SW-MSA
-            img_mask = torch.zeros((1, height, width, 1))
+            img_mask = torch.zeros((1, height, width, 1), dtype=dtype)
             height_slices = (
                 slice(0, -self.window_size),
                 slice(-self.window_size, -self.shift_size),
@@ -641,7 +641,7 @@ class SwinLayer(nn.Module):
         # partition windows
         hidden_states_windows = window_partition(shifted_hidden_states, self.window_size)
         hidden_states_windows = hidden_states_windows.view(-1, self.window_size * self.window_size, channels)
-        attn_mask = self.get_attn_mask(height_pad, width_pad)
+        attn_mask = self.get_attn_mask(height_pad, width_pad, dtype=hidden_states.dtype)
```

### Expected behavior

```shell
the img_mask tensor should be created with the same type of hidden_states.
```

**Comment by NielsRogge** [comment]
Hi,

Thanks for your interest in Swin Transformer! Do you mind opening a PR to fix this?

Thanks!

**Comment by NielsRogge** [comment]
Hi @LiweiPeng do you mind opening a PR for this?

**Comment by NielsRogge** [comment]
Gently pinging @LiweiPeng here
