### ISSUE TITLE
Not able to import tensorflow OPT

### ISSUE THREAD

**Issue by Leli1024** [huggingface/transformers#17523]
### System Info

```shell
Using the latest git repo as a source install, when I try to import TFOPTForCasualLM I will get the following error.


ImportError: cannot import name 'TFOPTForCasualLM' from 'transformers' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/transformers/__init__.py)
```
```


### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import TFOPTForCausalLM, GPT2Tokenizer

model = TFOPTForCausalLM.from_pretrained("facebook/opt-350m")
tokenizer = GPT2Tokenizer.from_pretrained("facebook/opt-350m")
```

### Expected behavior

```shell
Was expecting model class to import normally
```

**Comment by patil-suraj** [comment]
I just tried this with latest source install and it's working for me. Make sure you have TF installed to be able to import TF models.

**Comment by Leli1024** [comment]
> I just tried this with latest source install and it's working for me. Make sure you have TF installed to be able to import TF models.

I have tensorflow installed, even checked it by running a quick test

**Comment by ArthurZucker** [comment]
Could you share details about your script and maybe your environment?

**Comment by Leli1024** [comment]
> Could you share details about your script and maybe your environment?

I was working on an Azure compute machine. I found the problem, apparently I needed to install tensorflow GPU. as well as the regular distro
