### ISSUE TITLE
Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by juliencarbonnell** [huggingface/transformers#17544]
Hi @patrickvonplaten 
I'm trying to import the following:  
from transformers import BartTokenizer, BartForConditionalGeneration
tokenizer = BartTokenizer.from_pretrained('facebook/bart-large')

and get the error:
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

All I can find on the web to fix it is to set:
!protobuf==3.20.1
but it's not working for me. Sorry I can't manage to fix it myself.

**Comment by juliencarbonnell** [comment]
This error doesn't show up when you run the code on google colab. you should try that @gunjan075 in the meantime

**Comment by ykl7** [comment]
I have the same problem with the T0 model. My protobuf version is `4.21.1`. Any idea how to fix it? Cannot use Google Colab, only desktop machines.

**Comment by ykl7** [comment]
Update: I used `protobuf==3.20.0` and it worked. It's not ideal but it will do for now.

**Comment by sgugger** [comment]
This is all fixed on the main branch FYI.

**Comment by sgugger** [comment]
There was a patch release v4.19.3 just done to fix this issue FYI.

**Comment by juliencarbonnell** [comment]
Awesome
Thank you

**Comment by sanderland** [comment]
With protobuf 4.21.8 and debertav2, this error still appears
```
AutoTokenizer.from_pretrained('microsoft/deberta-v3-small')
```

```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Comment by off99555** [comment]
this error still happens for me. Downgrading is not an elegant solution because it breaks other packages that rely on latest version of protobuf e.g. google-cloud-documentai

**Comment by EricCart** [comment]
I met this issue when using `AutoTokenizer`, I fix it by specific the tokenizer to `LlamaTokenizer`.

**Comment by ain-soph** [comment]
> I met this issue when using `AutoTokenizer`, I fix it by specific the tokenizer to `LlamaTokenizer`.

This absolutely save my day! I meet with this issue for LLMs/vicuna. And this is a useful workaround.

**Comment by LarryStewart2022** [comment]
pip install protobuf==3.19.4 worked for me
