### ISSUE TITLE
word_ids() is not available when using FlauBERT

### ISSUE THREAD

**Issue by rgriot** [huggingface/transformers#17543]
### System Info

```shell
- `transformers` version: 4.19.2
- Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- Huggingface_hub version: 0.7.0
- PyTorch version (GPU?): 1.11.0+cu113 (True)
- Tensorflow version (GPU?): 2.8.2 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: No
```

### Who can help?

@SaulLu

Hi HuggingFace community,
I'm trying to fine-tune models for token classification task.
As french, I want to try different models trained in french or in multi languages.

I succeded to train camembert !

However, when using flauBERT, I have an issue when I align labels to the tokens after tokenisation.

I used to function :
`def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True)

    labels = []
    for i, label in enumerate(examples[f"ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)  # Map tokens to their respective word.
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:  # Set the special tokens to -100.
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:  # Only label the first token of a given word.
                label_ids.append(label[word_idx])
            else:
                label_ids.append(-100)
            previous_word_idx = word_idx
        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs`

Eventhough the function worked perfectly for camembert, I have the following error when using flauBERT:
`word_ids() is not available when using Python-based tokenizers`

I don't know if it's a tokenizer issue or if I have to write a new function to align the labels

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Steps to reproduce the error:

1. Import flaubert model
`model_name = "flaubert/flaubert_base_cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)`

2. Run the function
`def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True)

    labels = []
    for i, label in enumerate(examples[f"ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)  # Map tokens to their respective word.
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:  # Set the special tokens to -100.
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:  # Only label the first token of a given word.
                label_ids.append(label[word_idx])
            else:
                label_ids.append(-100)
            previous_word_idx = word_idx
        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs`

### Expected behavior

```shell
Get a new dataset with the labels align to the tokens after tokenization
```

**Comment by SaulLu** [comment]
Hi @rgriot ,

You do get this error because Flaubert does not have a fast version implemented (yet!) in the library and unfortunately only fast versions support this feature.

If you're interested, feel free to work on a PR to add this fast version to FlauBERT! :hugs:
