### ISSUE TITLE
Is it possible fine tune XLNet?

### ISSUE THREAD

**Issue by tyu0912** [huggingface/transformers#1757]
## ❓ Questions & Help

Hello, is there currently a script or recommended process to fine tune XLNet? Currently I am writing my own and using https://mccormickml.com/2019/09/19/XLNet-fine-tuning/ as an inspiration but overall I am still pretty new at this. I managed to get it to run but it seems to be taking forever so just thought I'd check. 

Thanks! Any help would be great.

**Comment by ShengeBelmendo** [comment]
I have tried to fine-tune xlnet on squad1.0 and squad2.0, although it's a few points lower than original results, but it works fine. This #1803 is for fine-tuning on squad2.0, I'm not familiar with other datasets.
