### ISSUE TITLE
ONNX support for gpt-neox

### ISSUE THREAD

**Issue by hannan72** [huggingface/transformers#17584]
### Feature request

Is there any possibility that we can convert gpt-neox to onnx using transformer library?

### Motivation

onnx model will be faster.

### Your contribution

-

**Comment by hannan72** [comment]
Hi @lewtun 
It is totally welcome if I can convert GPT like models to onnx. I did the conversion for gpt-j-6b. The problem was that the inference time improvement was only 5% in comparison to PyTorch on my GPU. Did you have any benchmark for the conversion of GPT models to onnx?

**Comment by lewtun** [comment]
Hi @hannan72 

> It is totally welcome if I can convert GPT like models to onnx. I did the conversion for gpt-j-6b.

Cool, this would be a nice addition! 

> The problem was that the inference time improvement was only 5% in comparison to PyTorch on my GPU. Did you have any benchmark for the conversion of GPT models to onnx?

Were you running on ONNXRuntime? We've found that to really speed up generations with GPT-like models, one needs to include ONNXRuntime's [IO bindings](https://onnxruntime.ai/docs/api/python/api_summary.html#iobinding) and [ORTValue](https://onnxruntime.ai/docs/api/python/api_summary.html#ortvalue). I don't have a benchmark for this currently, but it's something we're looking into in `optimum`
