### ISSUE TITLE
Pyramid Vision Transformer

### ISSUE THREAD

**Issue by danielhoshizaki** [huggingface/transformers#17596]
### Model description

I would like to add the[ Pyramid Vision Transformer model](https://arxiv.org/abs/2102.12122).

#### Paper Abstract
Pyramid Vision Transformer~(PVT), has several merits compared to prior arts. (1) Different from ViT that typically has low-resolution outputs and high computational and memory cost, PVT can be not only trained on dense partitions of the image to achieve high output resolution, which is important for dense predictions but also using a progressive shrinking pyramid to reduce computations of large feature maps. (2) PVT inherits the advantages from both CNN and Transformer, making it a unified backbone in various vision tasks without convolutions by simply replacing CNN backbones. (3) We validate PVT by conducting extensive experiments, showing that it boosts the performance of many downstream tasks

### Open source status

- [X] The model implementation is available
- [x] The model weights are available

### Provide useful links for the implementation

Model Implementation: https://github.com/whai362/PVT

Pretrained model weights for semantic segmentation: https://github.com/whai362/PVT/tree/v2/segmentation (based on ADE20K)

**Comment by satpalsr** [comment]
Hey @danielhoshizaki, Can I join you?

**Comment by andy1122** [comment]
@danielhoshizaki , I would love to contribute for this new model.

**Comment by danielhoshizaki** [comment]
Thanks for offering to help and sorry about the late response.
I'm going to have a go at this model and if I need any help I will let you know.

**Comment by satpalsr** [comment]
Sure @danielhoshizaki

**Comment by BakingBrains** [comment]
anyone working on this?
