### ISSUE TITLE
Add Checkpoint Loading from MLflow Model Registry

### ISSUE THREAD

**Issue by sam-h-bean** [huggingface/transformers#17618]
### Feature request

I would like the ability to pass a model URI that points to a model in an MLflow model registry then load a HuggingFace transformer directly from the registry. 

### Motivation

Model versioning and lifecycle management is a common practice in MLOps so I think it makes sense for this to be a first-class feature in HuggingFace.

### Your contribution

I already have this functional but would like to contribute it back to the project so others can leverage the MLflow model registry to maintain their model lifecycles from development to production!

**Comment by sgugger** [comment]
Hi @sam-h-bean !

We do not plan on supporting other model repositories than our model Hub for the `from_pretrained` method in Transformers. You should build a bridge to upload those checkpoints from MLFlow to the Hub and benefit from all the goodies we have such as the inference widget, model cards, community PRs etc. :-)

**Comment by sam-h-bean** [comment]
Hey @sgugger does the Hub have support for private models? These are proprietary models and thus can not be made public. What is the suggest method for cases such as this? It seems like this is a case that will become more prevalent as more companies adopt large language models.

**Comment by sgugger** [comment]
Yes, you can have private models/datasets/spaces on the Hub. See the [doc](https://huggingface.co/docs/hub/repositories-settings#private-repositories)!
