### ISSUE TITLE
Can we do adaptive pretraining on BERT-related models using transformers?

### ISSUE THREAD

**Issue by dr-GitHub-account** [huggingface/transformers#17654]
### Feature request

Adaptive pretraining methods like domain adaptive pretraining and task adaptive pretraining can benefit downstream tasks, which is illustrated in [https://aclanthology.org/2020.acl-main.740.pdf](url). In [https://huggingface.co/models](url), there are successful models pretrained with data from source domain. I would like to do adaptive pretraining(with tasks like MLM) to chinese-roberta-wwm-ext-large: [https://huggingface.co/hfl/chinese-roberta-wwm-ext-large](url) using unlabeled target domain data, so as to get better result in downstream tasks.

### Motivation

BERT and related models are benefiting some areas. The following are some examples:
1. [http://arxiv.org/abs/2004.02288](url)
2. [http://arxiv.org/abs/1908.10063](url)
3. [http://arxiv.org/abs/2007.15779](url)
4. [http://arxiv.org/abs/1906.02124](url)
5. [http://arxiv.org/abs/1904.05342](url)
I would like to do adaptive pretraining to chinese-roberta-wwm-ext-large, using unlabeled Chinese data in my area. It is good to start with conventional MLM. Afterwards, I might try and follow the pretraining task setting of chinese-roberta-wwm-ext-large, i.e. whole word masking and dynamic masking.

### Your contribution

Hopefully, a domain-specific pretrained language model.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!

**Comment by dr-GitHub-account** [comment]
I will. Thanks for the instruction.
