### ISSUE TITLE
Transformer Vit-MAE hard coded image channels

### ISSUE THREAD

**Issue by EmreTaha** [huggingface/transformers#17665]
### Feature request

Although the config file for the model accepts number of input channels, the class methods patchify and unpatchify use hard coded 3 channel image input. It should use num_channels argument of the config. https://github.com/huggingface/transformers/blob/a727db62f4f4e5cb15020fa5efa86ae559324616/src/transformers/models/vit_mae/modeling_vit_mae.py#L899

### Motivation

With this feature, VIT MAE model will be able to run on gray scale images as well

### Your contribution

I already fixed it in my code, but I haven't tested it thoroughly

**Comment by NielsRogge** [comment]
Hi,

This has already been asked in #17473. I'll review the related PR #17491
