### ISSUE TITLE
GPT2 - XL

### ISSUE THREAD

**Issue by anandhperumal** [huggingface/transformers#1767]
## 🐛 Bug

Model I am using (Bert, XLNet....):

Language I am using the model on (English, Chinese....):

The problem arise when using:
* [X ] the official example scripts: (give details)
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details)

## To Reproduce

1. In the documentation, it's given how to load GPT2-XL. But I'm getting an error when I try to load is GPT2 XL available as of now or it would take some time? 

Error:
```
>>> model = GPT2DoubleHeadsModel.from_pretrained('gpt2-xl')
Model name 'gpt2-xl' was not found in model name list (gpt2-large, gpt2, gpt2-medium). We assumed 'gpt2-xl' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cshome/anandhpe/.local/lib/python3.5/site-packages/pytorch_transformers/modeling_utils.py", line 492, in from_pretrained
    **kwargs
  File "/cshome/anandhpe/.local/lib/python3.5/site-packages/pytorch_transformers/modeling_utils.py", line 194, in from_pretrained
    raise e
  File "/cshome/anandhpe/.local/lib/python3.5/site-packages/pytorch_transformers/modeling_utils.py", line 180, in from_pretrained
    resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)  File "/cshome/anandhpe/.local/lib/python3.5/site-packages/pytorch_transformers/file_utils.py", line 124, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file gpt2-xl not found

```

## Environment

* OS:Ubuntu
* Python version:3.7
* PyTorch version: 1.3.1
* PyTorch Transformers version (or branch): 
* Using GPU ? yes
* Distributed of parallel setup ? no
* Any other relevant information:

**Comment by TheEdoardo93** [comment]
> ##  Bug
> Model I am using (Bert, XLNet....):
> 
> Language I am using the model on (English, Chinese....):
> 
> The problem arise when using:
> 
> * [X ] the official example scripts: (give details)
> * [ ]  my own modified scripts: (give details)
> 
> The tasks I am working on is:
> 
> * [ ]  an official GLUE/SQUaD task: (give the name)
> * [x]  my own task or dataset: (give details)
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 1. In the documentation, it's given how to load GPT2-XL. But I'm getting an error when I try to load is GPT2 XL available as of now or it would take some time?
> 
> Error:
> 
> ```
> >>> model = GPT2DoubleHeadsModel.from_pretrained('gpt2-xl')
> Model name 'gpt2-xl' was not found in model name list (gpt2-large, gpt2, gpt2-medium). We assumed 'gpt2-xl' was a path or url but couldn't find any file associated to this path or url.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/cshome/anandhpe/.local/lib/python3.5/site-packages/pytorch_transformers/modeling_utils.py", line 492, in from_pretrained
>     **kwargs
>   File "/cshome/anandhpe/.local/lib/python3.5/site-packages/pytorch_transformers/modeling_utils.py", line 194, in from_pretrained
>     raise e
>   File "/cshome/anandhpe/.local/lib/python3.5/site-packages/pytorch_transformers/modeling_utils.py", line 180, in from_pretrained
>     resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)  File "/cshome/anandhpe/.local/lib/python3.5/site-packages/pytorch_transformers/file_utils.py", line 124, in cached_path
>     raise EnvironmentError("file {} not found".format(url_or_filename))
> OSError: file gpt2-xl not found
> ```
> 
> ## Expected behavior
> ## Environment
> * OS:Ubuntu
> * Python version:3.7
> * PyTorch version: 1.3.1
> * PyTorch Transformers version (or branch):
> * Using GPU ? yes
> * Distributed of parallel setup ? no
> * Any other relevant information:
> 
> ## Additional context

This "issue" you have opened is the same as the #1747 . It's not a bug, but a **mismatch between version on Pypi and source GitHub**.

As stated by @LysandreJik 2 days ago , they haven't released the version with OpenAI GPT-2-xl yet on Pypi. Please, install Huggingface from source with the following command:
`pip install git+https://github.com/huggingface/transformers`

**Comment by anandhperumal** [comment]
@TheEdoardo93 sure thanks
