### ISSUE TITLE
AutoTokenizer fails to do_lower_case

### ISSUE THREAD

**Issue by pratyushmaini** [huggingface/transformers#17675]
If we use the AutoTokenizer library, this still does not work. 

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("roberta-base", do_lower_case=True)
tokenizer.do_lower_case = True
print(tokenizer.tokenize("Huggingface"))
```

_Originally posted by @pratyushmaini in https://github.com/huggingface/transformers/issues/9122#issuecomment-1152939838_

**Comment by shira-g** [comment]
>>> print(tokenizer.tokenize("Huggingface"))
['Hug', 'ging', 'face']
