### ISSUE TITLE
Need the ability to modify PSM values for Tesseract call in LayoutLM V2/ XLM / V3 Processor

### ISSUE THREAD

**Issue by kelvinAI** [huggingface/transformers#17697]
### Feature request

There exists a need to modify PSM values while calling Tesseract during feature extraction stage with OCR enabled.
https://github.com/huggingface/transformers/blob/31ee80d55673f32c0f5d50936f371e661b74b21a/src/transformers/models/layoutlmv3/feature_extraction_layoutlmv3.py#L53

### Motivation

Changing Page Segmentation Modes(PSM) values have significant impact on the output of all LayoutLM models, depending on the type/formatting of input document. The default psm value is set to 3, and is not optimal in every situation. It is helpful if users can modify PSM values based on different document types. [PSM Reference](https://stackoverflow.com/questions/44619077/pytesseract-ocr-multiple-config-options)

### Your contribution

I've already created a PR in a branch (https://github.com/huggingface/transformers/pull/17005) for LMV2/XLM and currently using it for my own projects, but it would be better if the official repo have it so there is no need to keep maintaining/updating my own fork. Hoping to see this feature added to LayoutLMV3!

**Comment by LysandreJik** [comment]
cc @NielsRogge
