### ISSUE TITLE
Cannot run run_qa.py due to "ImportError: cannot import name 'send_example_telemetry'"

### ISSUE THREAD

**Issue by maria364** [huggingface/transformers#17704]
### System Info

```shell
- `transformers` version: 4.18.0.dev0
- Platform: Linux-4.15.0-180-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- Huggingface_hub version: 0.4.0
- PyTorch version (GPU?): 1.10.0+cu102 (True)
- Tensorflow version (GPU?): 2.6.2 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to run the [run_qa.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/question-answering/run_qa.py) using the corresponding command provided in the instructions. However, I face the following issue:
 
Traceback (most recent call last):
  File "run_qa.py", line 45, in <module>
    from transformers.utils import check_min_version, send_example_telemetry
ImportError: cannot import name 'send_example_telemetry'

### Expected behavior

```shell
I would expect to see the following values, as mentioned in the instructions.

f1 = 88.52
exact_match = 81.22
```

**Comment by xueqianyi** [comment]
Hi, did you solve this problem, I have the same problem now

**Comment by xueqianyi** [comment]
@maria364 
Hi, did you solve this problem, I have the same problem now TAT

**Comment by DidiDerDenker** [comment]
Hi, I am experiencing the same problem when trying to run "run_mlm.py".

**Comment by ydshieh** [comment]
Hi, @maria364 @xueqianyi @DidiDerDenker  Could you try the latest version of `transformers`? This should fix the issue I believe.

**Comment by xueqianyi** [comment]
> 

Thanks so much！And that makes sense：
`pip install git+https://github.com/huggingface/transformers`
