### ISSUE TITLE
GPT-NEOX RuntimeError

### ISSUE THREAD

**Issue by yupei9** [huggingface/transformers#17745]
Hi, when I ran the model GPT-NEOX, I got the "RuntimeError: batch1 dim 2 must match batch2 dim1" in modeling_gpt_neox.py, line 212. 
So I tried to debugg and fix this problem, I found the code "present = None if use_cache else (key, value)" in modeling_gpt_neox.py, line 146. 
Is that logical wrong? and the correct coding should be "present = None if not use_cache else (key, value)" ?

**Comment by patrickvonplaten** [comment]
Hey @yupei9 - great catch! I think you're 100% right - do you want to open a PR to fix it? Also cc @sgugger

**Comment by sgugger** [comment]
Ahah sorry, I had a PR ready already since I wanted to test if the fix worked.
