### ISSUE TITLE
Is there Any difference of performance when finetuning bert use the huggingface or the google official code?

### ISSUE THREAD

**Issue by Doragd** [huggingface/transformers#17746]
Hi, 
I tend to finetune BERT with a simple text classification task.
However, I got different results when using the huggingface library (torch 1.8.1+cu111) and google's official code (tf 1.15).
I wonder if there is any optimization in huggingface for fine-tuning bert?

By the way, I believe that I use the same hyper-parameters. But I got the higher performance using the huggingface library

**Comment by gante** [comment]
Hi @Doragd  👋 As per our [issues guidelines](https://github.com/huggingface/transformers/blob/main/ISSUES.md), we reserve GitHub issues for bugs in the repository and/or feature requests. For any other matters, we'd like to invite you to use our [forum](https://discuss.huggingface.co/) 🤗
