### ISSUE TITLE
For HuggingFace GPT2DoubleHeadsModel, is there a way to directly provide a hidden state for an input? 

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#1774]
Hello,
Say I have two custom trained HuggingFace GPT2DoubleHeadsModels (Model 1 and 2).
 I want to take an hidden state of m-th layer of model 1, and use that hidden state as my input for model 2.
Is this possible with HuggingFace GPT2DoubleHeadsModels?

Some coding example would be a great help!

Thank you,

**Comment by LysandreJik** [comment]
Hi! You have access to the models' internals so you could definitely rewrite the main loop function to handle such a use-case!

You can access the hidden layers as follows:

```py
blocks = model.transformer.h  # this is a list of "block"s
block[0]  # contains the MLP/LayerNorm/attention layers
```

I'd recommend taking a look at the `forward` method of the [`GPT2DoubleLMHeadModel`](https://github.com/huggingface/transformers/blob/master/transformers/modeling_gpt2.py#L642) to 
understand how the `transformer` is managed, and to take a look at the [loop inside the `GPT2Model`](https://github.com/huggingface/transformers/blob/master/transformers/modeling_gpt2.py#L451) which you will probably have to replicate a little to achieve what you want to do.

**Comment by h56cho** [comment]
Hello, 
Thank you very much for your reply.
So if I am understanding this correctly, the part of the loop inside GPT2 model below is what I am supposed to use to generate output based on a given hidden state, am I correct?
```
outputs = block(hidden_states,
                            layer_past=layer_past,
                            attention_mask=attention_mask,
                            head_mask=head_mask[i])
```
Thank you again,

**Comment by julien-c** [comment]
Yas.

**Comment by h56cho** [comment]
Hello,

What exactly is the `block`? Does `block[0]` refer to the first gtp-2 layer, and `block[1]` refers to the second gtp-2 layer and so on? How can I utilize `block` to have access to the uppermost output layer of a gtp-2?

Thank you,

**Comment by LysandreJik** [comment]
Yes, `block` refers to the GPT-2 layers. `block[0]` is the first layer, ... `block[-1]` is the last layer.
