### ISSUE TITLE
pip install transformers not downloading gpt2-xl

### ISSUE THREAD

**Issue by samern92** [huggingface/transformers#1775]
Following the release of 1.5 B parameter model, I attempted to upgrade my version using the following command:

pip install transformers --upgrade

The installed library does not have gpt2-xl, and throws this error when I try calling it:

OSError: Model name 'gpt2-xl' was not found in model name list (gpt2, gpt2-medium, gpt2-large, distilgpt2). We assumed 'gpt2-xl' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Please update the pip installer to allow the easy installation of the latest model

**Comment by LysandreJik** [comment]
We haven't updated the pip version yet, we'll do so in the following weeks. Please install it from source in the meantime:

```
pip install git+https://github.com/huggingface/transformers
```

**Comment by huanghonggit** [comment]
Traceback (most recent call last):
  File "run_pplm.py", line 936, in <module>
    run_pplm_example(**vars(args))
  File "run_pplm.py", line 738, in run_pplm_example
    tokenizer = GPT2Tokenizer.from_pretrained(pretrained_model)
  File "/home/xps/anaconda3/envs/nlg_entity/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 911, in from_pretrained
    return cls._from_pr
etrained(*inputs, **kwargs)
  File "/home/xps/anaconda3/envs/nlg_entity/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 1014, in _from_pretraine
    list(cls.vocab_files_names.values()),
OSError: Model name 'gpt2-medium' was not found in tokenizers model name list (gpt2, gpt2-medium, gpt2-large, gpt2-xl, distilgpt2). We asswas a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find sucat this path or url.




I also reported the same error....@LysandreJik

**Comment by Jeremiah0425** [comment]
> 回溯（最近一次调用）：
> 文件“run_pplm.py”，第 936 行，在
> run_pplm_example(**vars(args))
> 文件“run_pplm.py”，第 738 行，在 run_pplm_example
> tokenizer = GPT2Tokenizer.from_pretrained(pretrained_model)
> 文件“ /home/xps/anaconda3/envs/nlg_entity/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 911, in from_pretrained
> return
> cls._from_pretrained(*inputs, **kwargs)
> File "/home /xps/anaconda3/envs/nlg_entity/lib/python3.7/site-packages/transformers/tokenization_utils.py”，第 1014 行，在 _from_pretraine
> 列表（cls.vocab_files_names.values()）中，
> OSError：在标记器模型名称列表（gpt2、gpt2-medium、gpt2-large、gpt2-xl、distlgpt2）中找不到模型名称“gpt2-medium”。我们为包含名为 ['vocab.json', 'merges.txt'] 的词汇文件的目录添加了路径、模型标识符或 url，但找不到此路径或 url。
> 
> 我也报了同样的错误.... @LysandreJik

hi,you can run this model?
