### ISSUE TITLE
__init__() got an unexpected keyword argument '_name_or_path'

### ISSUE THREAD

**Issue by rajnishrajput12** [huggingface/transformers#17792]
### System Info

```shell
sentence_transformer versiob 2.2.0
windows
python version- 3.9.12
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying the following code :-
1. it gave me error no file "C:\\Users\\ra*****\\Downloads\\bert-base-nli-mean-tokens\\1_Pooling\\config.json"
the i create folder 1_Pooling and kept the downloaded json but then it gave me error
2.__init__() got an unexpected keyword argument '_name_or_path'
NOTE:- I downloaded all the files from https://huggingface.co/sentence-transformers/bert-base-nli-mean-tokens/tree/main"
from sentence_transformers import SentenceTransformer
embedder = SentenceTransformer(r'C:\Users\raj****\Downloads\bert-base-nli-mean-tokens')
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'A cheetah is running behind its prey.']
corpus_embeddings = embedder.encode(corpus)
sentence_transformer version 2.2.0

### Expected behavior

```shell
we should be able to load the sentence_transformer from local
```

**Comment by ydshieh** [comment]
Close as this is a question for the library `sentence_transformer`
