### ISSUE TITLE
`seed_generator` would casue tensorflow gpu memory growth immediately

### ISSUE THREAD

**Issue by Atakey** [huggingface/transformers#17804]
https://github.com/huggingface/transformers/blob/7cced021fa8ddc59f0f77384300760d34545394e/src/transformers/generation_tf_utils.py#L349

In transformers version >=4.18.0, import something from `generation_tf_utils.py` would casue gpu memory growth immediately if I don't set env `TF_FORCE_GPU_ALLOW_GROWTH=true` before importing modules from this file.

And I locate the problem at this line. 

Making attr `seed_generator` lazy loaded could solve this.

```
# ...
class TFGenerationMixin:
    """
    A class containing all of the functions supporting generation, to be used as a mixin in [`TFPreTrainedModel`].
    """

    # seed_generator = tf.random.Generator.from_non_deterministic_state()

    _seed_generator = None
    
    @property
    def seed_generator(self):
        if self._seed_generator is None:
            self._seed_generator = tf.random.Generator.from_non_deterministic_state()
        return self._seed_generator
# ...
```

**Comment by gante** [comment]
Hey @Atakey 👋  Great finding! Would you be able to open a PR? The suggestion you gave looks great!
