### ISSUE TITLE
How to use LayoutLMv3 for Document Layout Detection  task?

### ISSUE THREAD

**Issue by matthew-wei** [huggingface/transformers#17820]
### System Info

```shell
trasformers = 4.20.1
Models: layoutlmv3

How to use LayoutLMv3 for Document Layout Detection, for example microsoft unilm(https://github.com/microsoft/unilm/tree/master/layoutlmv3)?
I do not find Document Layout Detection task infomation in example and modeling.
The typical dataset for Document Layout Detection is call PubLayNet (https://github.com/ibm-aur-nlp/PubLayNet).


example :https://github.com/huggingface/transformers/tree/main/examples/research_projects/layoutlmv3
modeling: https://github.com/huggingface/transformers/tree/main/src/transformers/models/layoutlmv3
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

How to use LayoutLMv3 for Document Layout Detection, for example microsoft unilm(https://github.com/microsoft/unilm/tree/master/layoutlmv3)?
I do not find Document Layout Detection task infomation in example and modeling.
The typical dataset for Document Layout Detection is call PubLayNet (https://github.com/ibm-aur-nlp/PubLayNet).

### Expected behavior

```shell
I can know how to use layoutlmv3 model in transformers for  Document Layout Detection?
I would really appreciate it if you can give me an example code.
```

**Comment by NielsRogge** [comment]
Hi,

If you read a bit more closely: https://github.com/microsoft/unilm/tree/master/layoutlmv3#document-layout-analysis-on-publaynet

You'll see they provide a guide regarding fine-tuning LayoutLMv3 on PubLayNet. The Mask R-CNN framework is leveraged. This framework currently is not available in Huggingface Transformers, so you'll need to use the unilm repo for that.
