### ISSUE TITLE
Unclear documentation for special_tokens_mask

### ISSUE THREAD

**Issue by Evpok** [huggingface/transformers#1784]
According to [the docs](https://huggingface.co/transformers/main_classes/tokenizer.html#transformers.PreTrainedTokenizer.get_special_tokens_mask), the `special_tokens_mask` returned by e.g. `encode_plus` should have

> 0 for a special token, 1 for a sequence token

Yet when I try

```python
tokenizer = transformers.BertTokenizer.from_pretrained('bert-base-uncased')
tokenizer.encode_plus("This is a test sentence", add_special_tokens=True) 
```

I get

```python
{'special_tokens_mask': [1, 0, 0, 0, 0, 0, 1],
 'input_ids': [101, 2023, 2003, 1037, 3231, 6251, 102],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0]}
```

Which — to me — would suggest that it is in fact 1 for special tokens and 0 for sequence tokens.
The implementations for [BERT](https://github.com/huggingface/transformers/blob/700331b5ece63381ad1b775fc8661cf3ae4493fd/transformers/tokenization_bert.py#L210) and [RoBERTa](https://github.com/huggingface/transformers/blob/1c542df7e554a2014051dd09becf60f157fed524/transformers/tokenization_roberta.py#L110) support this, so should the documentation be made clearer or is it just me who understood it backward?

**Comment by LysandreJik** [comment]
Indeed, this is a documentation error! Thank you for letting us know!

**Comment by Evpok** [comment]
@LysandreJik This was reintroduced in https://github.com/huggingface/transformers/pull/2989 apparently

**Comment by LysandreJik** [comment]
Thanks @Evpok for letting me know, this flew under my radar.

**Comment by Evpok** [comment]
My pleasure 😄
