### ISSUE TITLE
"Write with Transformer" source code?

### ISSUE THREAD

**Issue by AIsysxd** [huggingface/transformers#1785]
## ❓ Questions & Help
Hello, can't find source code of it. May you help, please?

**Comment by julien-c** [comment]
Hello,

Sorry, the web app is not open source right now.

**Comment by jonrbates** [comment]
Thanks @julien-c .  Can you comment on how elastic inference with pytorch models is done?

**Comment by flarn2006** [comment]
Is there any chance this could be reconsidered? I'd love to use it for experimenting with custom fine-tuned models.

**Comment by sosuperic** [comment]
Would also love for this for experimenting with custom models.

**Comment by Aspie96** [comment]
It'd be very interesting to open source this.

**Comment by JD1174** [comment]
Is there any possibility of this becoming reconsidered? I've been trying to look for this as well... :/

**Comment by davidnarganes** [comment]
Any chance of this being public? @thomwolf

**Comment by sky1ove** [comment]
> Would also love for this for experimenting with custom models.

Same!
