### ISSUE TITLE
Bad readme for HF model codeparrot/codeparrot-small

### ISSUE THREAD

**Issue by shi-kejian** [huggingface/transformers#17859]
### System Info

```shell
Not system-dependent 
https://huggingface.co/codeparrot/codeparrot-small
The README is not updated
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AutoTokenizer, AutoModelWithLMHead
  
tokenizer = AutoTokenizer.from_pretrained("lvwerra/codeparrot-small")
model = AutoModelWithLMHead.from_pretrained("lvwerra/codeparrot-small")

### Expected behavior

```shell
The model loading should be successful
The model card is "codeparrot/codeparrot-small" but in example usage it's "lvwerra/codeparrot-small". 
A simple update to the model card README will do
```

**Comment by NielsRogge** [comment]
Hi!

Thanks for reporting. We now have a discussion and PR feature on the hub, meaning that you can directly open an issue on the hub for a particular repository. So feel free to ping them there!

**Comment by NielsRogge** [comment]
Closing the issue in that case!
