### ISSUE TITLE
Calling `generate` on a `T5ForConditionalGeneration` returns `n` tokens but `n-1` scores

### ISSUE THREAD

**Issue by ClementRomac** [huggingface/transformers#17868]
### System Info

```shell
- `transformers` version: 4.20.1
- Platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.17
- Python version: 3.8.13
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): 1.11.0+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no
```

### Who can help?

@patrickvonplaten, @Narsil

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import torch

if __name__ == '__main__':
    torch.manual_seed(0)
    tokenizer = AutoTokenizer.from_pretrained('t5-small')
    model = AutoModelForSeq2SeqLM.from_pretrained('t5-small')

    input = tokenizer.encode("I enjoy walking with my cute dog", return_tensors='pt')
    result = model.generate(
        input,
        max_new_tokens=15,
        do_sample=True,
        return_dict_in_generate=True,
        output_scores=True,
    )

    print(len(result["scores"]))
    for sequence in result["sequences"]:
        print(len(sequence))
        print(tokenizer.decode(sequence))
```

Output:
```
15
16
<pad> Ich, liebe es, mes lustig beim laufen
```

### Expected behavior

I would have expected to have up to 15 tokens (as `max_new_tokens=15`) and `len(result["scores"]) == len(result["sequences"][0])`. However, the size of the returned sequence of tokens is always `len(result["scores"]) + 1`. In addition, if `max_new_tokens` is reached we have `len(result["sequences"][0]) == max_new_tokens + 1`.

When looking at the decoded sequence, there is always a pad token at the beginning.

I don't know if this is necessarily a bug but this behaviour is somewhat confusing, especially when trying to compute the probability of the sequence given scores.

**Comment by ydshieh** [comment]
Hi, @ClementRomac 

If you look the [config.json](https://huggingface.co/t5-small/blob/main/config.json) file of the `t5-small` model, you will see it uses  `pad_token_id` as `decoder_start_token_id` (both are `0`).

The `scores` having length `len(sequence) - 1` is expected. Think it this way, 

```python
generated sequence = [decoder_start_token_id, token_1, token_2]
```

The scores is/are:

- score for generating `token_1` while we have `[decoder_start_token_id]`
- score for generating `token_2` while we have `[decoder_start_token_id, token_1]`

This is also documented in [generation_utils.py](https://github.com/huggingface/transformers/blob/main/src/transformers/generation_utils.py), for example

(`SampleEncoderDecoderOutput`)
https://github.com/huggingface/transformers/blob/afb71b672679e57449085e4955a321db8e5705b9/src/transformers/generation_utils.py#L172
or
(`GreedySearchEncoderDecoderOutput`)
https://github.com/huggingface/transformers/blob/afb71b672679e57449085e4955a321db8e5705b9/src/transformers/generation_utils.py#L101

etc.

**Comment by ydshieh** [comment]
@gante Looks good to me, as long as we keep `batch_size*num_return_sequences` instead of `batch_size` wherever it applies.

**Comment by patrickvonplaten** [comment]
Very much agree with @gante here!

**Comment by gante** [comment]
Assigned to me to update the docstring for all three frameworks

**Comment by Waqar-107** [comment]
@ClementRomac Hi! I have been trying to calculate the probability of a sequence but am not sure how to do it. As you mentioned calculating the probability, can you please tell me how to do it?

I have the scores for each step of the generate method, but not sure how to use them.

What I am doing is, given a premise and a hypothesis, I am trying to identify whether they are entailment, contradiction, or, neutral. I am getting the classification correctly, I just don't know how to calculate the probability of the sequence being **entailment**

```python
def is_entailment(premise, hypothesis):
    entailment_premise = premise
    entailment_hypothesis = hypothesis

    token_output = tokenizer("mnli premise: " + entailment_premise + " hypothesis: " + entailment_hypothesis,
                             return_tensors="pt", return_length=True)
    input_ids = token_output.input_ids

    output = model.generate(input_ids, output_scores=True, return_dict_in_generate=True, max_length=50)
    entailment_ids = output["sequences"]

    entailment = tokenizer.decode(entailment_ids[0], skip_special_tokens=True)
    return entailment
```
