### ISSUE TITLE
Inference API failing: `"Unknown error in run_once : postprocess() got an unexpected keyword argument 'return_all_scores'`

### ISSUE THREAD

**Issue by sergeyf** [huggingface/transformers#17876]
This model doesn't seem to work on the Hub: https://huggingface.co/guidecare/feelings_and_issues_large?text=I+like+you.+I+love+you 

Note the Unknown Error in red. It worked fine last week.

Further, if I try to use the Accelerated Inference API via

```python
import requests

API_URL = "https://api-inference.huggingface.co/models/guidecare/feelings_and_issues_large"
headers = {"Authorization": "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}  # i just put my own in here

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()
	
output = query({
	"inputs": "I like you. I love you",
})
```

I get this:

```
{'error': 'unknown error',
 'warnings': ["Unknown error in run_once : postprocess() got an unexpected keyword argument 'return_all_scores'"]}
```

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

Clearly defined above.

### Expected behavior

```shell
No error!
```

**Comment by sergeyf** [comment]
Hello again. Any ideas here?

**Comment by sergeyf** [comment]
Perhaps this has something to do with the `.bin` file being "unsafe" for some reason?

![image](https://user-images.githubusercontent.com/1874668/176098156-9a5d9413-959c-4e00-bb9d-e10f98f8a9e6.png)

**Comment by sergeyf** [comment]
Looks like the error is different now:

![image](https://user-images.githubusercontent.com/1874668/176098571-c71dbd4f-478b-44a9-8360-a5f76ad0011d.png)

**Comment by sergeyf** [comment]
I am no longer getting an error when running this code:

```
import requests

API_URL = "https://api-inference.huggingface.co/models/guidecare/feelings_and_issues_large"
headers = {"Authorization": "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}  # i just put my own in here

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()
	
output = query({
	"inputs": "I like you. I love you",
})
```

**Comment by sergeyf** [comment]
Closing in favor of https://github.com/huggingface/huggingface_hub/issues/932

**Comment by admehta01** [comment]
We've been using Inference API in production and it was down for multiple days for us. We didn't see any updates on https://status.huggingface.co under Inference API.

How can we get notified of downtimes in the future? Is Inference API recommended for production use?
