### ISSUE TITLE
Pruning function in T5Attention doesnt affect _relative_position_bucket

### ISSUE THREAD

**Issue by hadaev8** [huggingface/transformers#17886]
### Who can help?

@patrickvonplaten

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run pruning function in t5 model, then run inference.

### Expected behavior

Relative position head should be pruned too.

Here it is
https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L355

**Comment by ydshieh** [comment]
@hadaev8 

It is not clear to me about this.

`_relative_position_bucket` is a `staticmethod` without using any model weight in it, and IMO there is no need to do anything when pruning a model.

**Comment by hadaev8** [comment]
@ydshieh 

Relative position bias have shape (dim, heads).
For example I have 6 heads and pruned one, would be mismatch, (dim, 5) + (dim, 6)

Here this line
https://github.com/huggingface/transformers/blob/3ccff0d400ffd1b0c5074e15afb2b1f2af0e7b44/src/transformers/models/t5/modeling_t5.py#L529

I realized all layers use same positional bias, so it should be masked in forward, not pruned.

**Comment by hadaev8** [comment]
@ydshieh 
Here it is
https://colab.research.google.com/drive/1HYu-yzmmbumbskGZExXlOP0WFmDYdgAp?usp=sharing

I fixed rel pos bias, but where is some other error

**Comment by patrickvonplaten** [comment]
Hey @hadaev8,

That's actually quite a smart fix :-) Think I'd be ok with adding this! Do you want to open a PR for it ? :-)

**Comment by hadaev8** [comment]
@patrickvonplaten 
Okay, if you think its ok, i will do pr tomorrow.
