### ISSUE TITLE
Deploying a  pytorch-pretrained-bert on mobile

### ISSUE THREAD

**Issue by CowryCode** [huggingface/transformers#17896]
### System Info

```shell
I use google colab
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code here https://medium.com/huggingface/how-to-build-a-state-of-the-art-conversational-ai-with-transfer-learning-2d818ac26313

### Expected behavior

```shell
I want to export the model for use in a mobile app (flutter). I am new to this and I just can't figure it out. Have tried many recommendations online, but something seems off. Kindly help
```

### Checklist

- [X] I have read the migration guide in the readme. ([pytorch-transformers](https://github.com/huggingface/transformers#migrating-from-pytorch-transformers-to-transformers); [pytorch-pretrained-bert](https://github.com/huggingface/transformers#migrating-from-pytorch-pretrained-bert-to-transformers))
- [X] I checked if a related official extension example runs on my machine.

**Comment by NielsRogge** [comment]
Hi,

Regarding exporting Transformers models, refer to the guide here: https://huggingface.co/docs/transformers/serialization.

Also cc'ing @hollance who's an expert on mobile ML.

**Comment by hollance** [comment]
It would be helpful to know what mobile platform you're trying to export to, how you've tried to do the export, and what errors you're running into. There are too many unknowns here to give an answer.

**Comment by CowryCode** [comment]
Thanks @hollance for your response, I just saw the message now. I will drop detail of both the code and screenshot shortly

**Comment by CowryCode** [comment]
@hollance below are the codes and errors they threw. What I want to achieve is to use the model on edge device (mobile) developed in flutter. 

**Output of the training**
![image](https://user-images.githubusercontent.com/23655212/176263865-0e1964a6-460d-47cd-bf13-90cd3866e57e.png)
**First Approach I tried**
`model_class = OpenAIGPTDoubleHeadsModel
model = model_class.from_pretrained('./themodel')
Scripted_model = torch.jit.script(model)
opt_model = optimize_for_mobile(Scripted_model)
opt_model._save_for_lite_interpreter("Mobile_model.ptl")`

**Error from Approach 1**
![image](https://user-images.githubusercontent.com/23655212/176264730-60237895-fc57-4607-94c2-f5dbdec9a4c5.png)


**Approach 2**
`from itertools import chain
# Let's define our contexts and special tokens
persona = [["i", "like", "playing", "football", "."],
           ["i", "am", "from", "NYC", "."]]
history = [["hello", "how", "are", "you", "?"],
           ["i", "am", "fine", "thanks", "."]]
reply = ["great", "to", "hear"]
bos, eos, speaker1, speaker2 = "<bos>", "<eos>", "<speaker1>", "<speaker2>"

def build_inputs(persona, history, reply):
    # Build our sequence by adding delimiters and concatenating
    sequence = [[bos] + list(chain(*persona))] + history + [reply + [eos]]
    sequence = [sequence[0]] + [ [speaker2 if (len(sequence)-i) % 2 else speaker1] + s
                                for i, s in enumerate(sequence[1:])]
    # Build our word, segments and position inputs from the sequence
    words = list(chain(*sequence))                          # word tokens
    segments = [speaker2 if i % 2 else speaker1             # segment tokens
                for i, s in enumerate(sequence) for _ in s]
    position = list(range(len(words)))                      # position tokens
    return words, segments, position, sequence

words, segments, position, sequence = build_inputs(persona, history, reply)

# Tokenize words and segments embeddings:
words = tokenizer.convert_tokens_to_ids(words)
segments = tokenizer.convert_tokens_to_ids(segments)

tokenizer_class, model_class = (OpenAIGPTTokenizer, OpenAIGPTDoubleHeadsModel)
tokens_tensor = torch.tensor([words])
segments_tensors = torch.tensor([segments])
model = torch.load('./themodel/pytorch_model.bin')
Scripted_model = torch.jit.trace(model,[tokens_tensor, segments_tensors])
opt_model = optimize_for_mobile(Scripted_model)
opt_model._save_for_lite_interpreter("Mobile_model.ptl")`

**Error of the Second Approach**
![image](https://user-images.githubusercontent.com/23655212/176266493-6d969c7d-bb12-4ba8-b230-4afc818c55ae.png)

**Comment by hollance** [comment]
The second approach of tracing the model (rather than scripting it), is what I would prefer. However, you need to load the model using `model = OpenAIGPTDoubleHeadsModel.from_pretrained("themodel")` instead of `torch.load`.

**Comment by CowryCode** [comment]
**Thank you @hollance, I really appreciate your effort. I tried it, and below were the error I got.**

**When I changed the model load, I got the error below:**
![image](https://user-images.githubusercontent.com/23655212/176485673-2c69ea09-dc0a-4e4c-8af7-35a60a366cd7.png)

**When I removed the torchscript argument, I got the error below:**
![image](https://user-images.githubusercontent.com/23655212/176486848-6b728116-c1d8-40ba-a333-1e7210a6c401.png)
![image](https://user-images.githubusercontent.com/23655212/176487133-9f825229-4ec3-4fdf-b71a-8f0f22e0573e.png)

**Comment by hollance** [comment]
That looks like you're not giving it inputs of the correct size. It's a good idea to using your input tensors first in a normal inference call:

```
with torch.no_grad():
    outputs = model(inputs, return_dict=False)
```

where `inputs` are the input tensors this model needs. I expect this to also give an error message, so first make sure that works without problems.

**Comment by CowryCode** [comment]
Thank you @hollance for your support, I tried it and that failed. Below is a link to the google colab file, I really appreciate your effort to help a newbie in ML. 

https://drive.google.com/file/d/1Oi5rDh08d0EJMF_Q7F9pfixbANV7bKvw/view?usp=sharing

**Comment by hollance** [comment]
Sorry but there's just way too much stuff in that notebook for me to make sense of. Could you create a notebook that has the minimum amount of code in it to reproduce the problem?

**Comment by CowryCode** [comment]
Hi @hollance, kindly find below as requested to recreate the problem:
**This is link to the minimized version of the colable file**
https://drive.google.com/file/d/1CTVA6wD26BMHXlU6JY2VJ3S5TW5dI2Ac/view?usp=sharing

**Below is a link to training output (i.e content of "themodel" folder)**
https://drive.google.com/file/d/1ppib_rexC6_XsOlUQeOf3goD-v2uhqad/view?usp=sharing

**Below is a link to the dataset (in case you may want to take a look)**
https://s3.amazonaws.com/datasets.huggingface.co/personachat/personachat_self_original.json


Thank you for your support so far I am grateful. I feel really excited and relieved knowing that I am getting the needed help.

**Comment by chainesanbuenaventura** [comment]
@hollance hi, I wanted to deploy pix2struct into mobile. Do you have advice on which mobile dev technology, etc to use and steps on deploying it?
