### ISSUE TITLE
Trainer.predict multiple progress bars

### ISSUE THREAD

**Issue by neverix** [huggingface/transformers#17952]
### System Info

- `transformers` version: 4.21.0.dev0
- Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): 1.11.0+cu113 (False)
- Tensorflow version (GPU?): 2.8.2 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@sgugger 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased")
trainer = Trainer(model)
trainer.predict([{"input_ids": torch.zeros(20).long()} for _ in range(48)])  # [6/6  00:03]
trainer.predict([{"input_ids": torch.zeros(20).long()} for _ in range(96)])  # [6/6  00:12] despite having more examples
```

### Expected behavior

Two progress bars, one of length 6 and the other of length 12.

**Comment by neverix** [comment]
A simple fix would be to add an `on_predict` method to the `ProgressCallback`.

Alternatively, `Trainer.predict` could just call `on_evaluate` in the end.

**Comment by sgugger** [comment]
There is no `on_predict` event, but I guess we can reuse `on_evaluate` here. Do you want to make a PR?

**Comment by neverix** [comment]
I wrote a draft, but it breaks in Jupyter because `NotebookProgressBar` adds custom logic to `on_evaluate`. `on_predict` might be necessary.

**Comment by sgugger** [comment]
Feel free to create it then!
