### ISSUE TITLE
RuntimeError: Connection timed out in Single node Multi GPU training

### ISSUE THREAD

**Issue by kamalravi** [huggingface/transformers#1795]
I am trying to pre-train DistilBERT with single node multigpu as given here https://github.com/huggingface/transformers/tree/master/examples/distillation.

I have set the IP address of my gcp instance and port number. I am getting this error. Any solutions?

> File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Connection timed out

**Comment by VictorSanh** [comment]
By any chance, did you open the port number you're using?

**Comment by kamalravi** [comment]
Yes, it is established. What is the master_addr and master_port when submitting a job with single node and multigpu config in GCP?
