### ISSUE TITLE
rust_model.ot not saved by save_pretrained()

### ISSUE THREAD

**Issue by Zacchaeus14** [huggingface/transformers#17977]
### System Info

I am running my experiments on a machine without internet, so I need to save the tokenizers first. However, I found that with the `save_pretrained()` method, the `rust_model.ot` is not saved to the directory. The model is `deberta-v3-base` and the version is 4.20.1.

### Who can help?

@LysandreJik @SaulLu

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
ckpt = 'microsoft/deberta-v3-base'
tokz = AutoTokenizer.from_pretrained(ckpt, use_fast=True)
model = AutoModel.from_pretrained(ckpt)
tokz.save_pretrained(ckpt)
model.save_pretrained(ckpt)
$ls
> added_tokens.json  pytorch_model.bin	    spm.model
> config.json	   special_tokens_map.json  tokenizer_config.json
```

### Expected behavior

rust_model.ot saved by save_pretrained()

**Comment by LysandreJik** [comment]
Rust models are not supported by `transformers`. I believe the models you're talking about are the ones coming from @guillaume-be's [rust-bert](https://github.com/guillaume-be/rust-bert) repository.

**Comment by Zacchaeus14** [comment]
@LysandreJik Thanks. I got it. I was thinking about https://huggingface.co/microsoft/deberta-v3-base/blob/main/rust_model.ot.
