### ISSUE TITLE
BART with multiple encoders. 

### ISSUE THREAD

**Issue by prakamya-mishra** [huggingface/transformers#17993]
Hi @patrickvonplaten , I am trying to evaluate my a model (Custom BART model with 2 inputs) that has 2 encoder and 1 decoder. For evaluation in the prediction_step method, it uses model.generate  (from generation_utils.py) for generating outputs. But the problem is that it only accepts inputs: Optional[torch.Tensor] = None,  but in my case I need to pass 2 set of inputs (one for both the encoders). So is there a way to pass 2 set of inputs to the generate method?

**Comment by gante** [comment]
Hi @prakamya-mishra -- if your model is designed to take two inputs, then you may be able to pass the second through `model_kwargs`. E.g. if the model signature is `model(input_ids, foo)`, then you may be able to run `model.generate(input_ids, model_kwargs{"foo": foo})`. Although you have to make sure your `prepare_inputs_for_generation` [method](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bart/modeling_bart.py#L1393) is expecting this argument.

Please note that as per our [issues guidelines](https://github.com/huggingface/transformers/blob/main/ISSUES.md), we do not provide support to custom code. We also reserve these issues for bugs and feature requests -- for other questions, we'd like to invite you to use the [forums](https://discuss.huggingface.co/) :)
