### ISSUE TITLE
issue installing SentencePiece

### ISSUE THREAD

**Issue by SamitM1** [huggingface/transformers#17991]
### System Info

the error i get when i do "pip3 install SentencePiece":

  ./build_bundled.sh: line 15: cmake: command not found
      ./build_bundled.sh: line 16: nproc: command not found
      make: *** No targets specified and no makefile found.  Stop.
      make: *** No rule to make target `install'.  Stop.
      env: pkg-config: No such file or directory
      Failed to find sentencepiece pkg-config
      [end of output]

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

pip3 install SentencePiece

### Expected behavior

unable to install

**Comment by gante** [comment]
Hi @SamitM1 👋 The issue seems to be related to the package you mentioned, not `transformers` -- I'd suggest opening an issue there (https://github.com/google/sentencepiece)
