### ISSUE TITLE
pip cannot install transformers with python version 3.8.0

### ISSUE THREAD

**Issue by Lyther** [huggingface/transformers#1802]
## ❓ Questions & Help

    The error message looks like this,

`    ERROR: Command errored out with exit status 1:
     command: 'c:\users\enderaoe\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Enderaoe\\AppData\\Local\\Temp\\pip-install-g7jzfokt\\sentencepiece\\setup.py'"'"'; __file__='"'"'C:\\Users\\Enderaoe\\AppData\\Local\\Temp\\pip-install-g7jzfokt\\sentencepiece\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Enderaoe\AppData\Local\Temp\pip-install-g7jzfokt\sentencepiece\pip-egg-info'
         cwd: C:\Users\Enderaoe\AppData\Local\Temp\pip-install-g7jzfokt\sentencepiece\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Enderaoe\AppData\Local\Temp\pip-install-g7jzfokt\sentencepiece\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "c:\users\enderaoe\appdata\local\programs\python\python38-32\lib\codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

    Should I lower my python version, or there is any other solution?

**Comment by thomwolf** [comment]
This looks like an error related to Google SentencePiece and in particular this issue: https://github.com/google/sentencepiece/issues/411

**Comment by n8henrie** [comment]
https://github.com/google/sentencepiece/issues/411#issuecomment-557596691

**Comment by tawfiq3** [comment]
I've got problem installing matplotlib in python. While installing these error massage is shown. What to do now?
![pythonerror](https://user-images.githubusercontent.com/55088805/69539112-091f6500-0fae-11ea-90a9-53829fa1e0a3.PNG)

Command "C:\Users\tawfiq\PycharmProjects\untitled4\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\tawfiq\\AppData\\Local\\Temp\\pip-install-yfe_bqlr\\matplotlib\\setup.py';f=getatt
r(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\tawfiq\AppData\Local\Temp\pip-record-vmiaih4n\install-record.txt -
-single-version-externally-managed --compile --install-headers C:\Users\tawfiq\PycharmProjects\untitled4\venv\include\site\python3.8\matplotlib" failed with error code 1 in C:\Users\tawfiq\AppData\Local\Temp\pip-i
nstall-yfe_bqlr\matplotlib\

**Comment by n8henrie** [comment]
This is still an issue on MacOS: https://github.com/google/sentencepiece/issues/411#issuecomment-578509088

**Comment by vikramsubramanian** [comment]
> google/sentencepiece#411 (comment)

This error comes up: ``` ERROR: sentencepiece-0.1.84-cp38-cp38-manylinux1_x86_64.whl is not a supported wheel on this platform.```
