### ISSUE TITLE
EfficientFormer

### ISSUE THREAD

**Issue by jhabr** [huggingface/transformers#18041]
### Model description

[EfficientFormer: Vision Transformers at MobileNet Speed](https://arxiv.org/abs/2206.01191)

Submitted on 2 Jun 2022, last revised 5 Jul 2022.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://github.com/snap-research/EfficientFormer

Happy to support the model contribution!

**Comment by NielsRogge** [comment]
cc @hollance
