### ISSUE TITLE
ValueError: You have to specify pixel_values in CLIP for ver >= 4.18.0 

### ISSUE THREAD

**Issue by naoto0804** [huggingface/transformers#18040]
### System Info

- `transformers` version: 4.20.1
- Platform: Linux-4.19.0-21-cloud-amd64-x86_64-with-debian-10.12
- Python version: 3.7.12
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.8.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@patil-suraj

I try to run TFCLIPModel.get_image_features example [here](https://huggingface.co/docs/transformers/model_doc/clip#transformers.TFCLIPModel.get_image_features.example), which is also pasted in Reproduction section.
When I use `transformers >= 4.18.0`, it throws an error "ValueError: You have to specify pixel_values" (details pasted below).
Is there any way to fix this?

```
Traceback (most recent call last):
  File "dummy.py", line 13, in <module>
    image_features = model.get_image_features(**inputs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 383, in run_call_with_unpacked_inputs
    return func(self, **unpacked_inputs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/clip/modeling_tf_clip.py", line 1318, in get_image_features
    return_dict=return_dict,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 383, in run_call_with_unpacked_inputs
    return func(self, **unpacked_inputs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/clip/modeling_tf_clip.py", line 796, in get_image_features
    raise ValueError("You have to specify pixel_values")
ValueError: You have to specify pixel_values
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from PIL import Image
import requests
from transformers import CLIPProcessor, TFCLIPModel

model = TFCLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
inputs = processor(images=image, return_tensors="tf")
image_features = model.get_image_features(**inputs)
```

### Expected behavior

Finish without throwing an error described above.

**Comment by LysandreJik** [comment]
cc @NielsRogge, or @amyeroberts @alaradirik if you have any pointers

**Comment by naoto0804** [comment]
@amyeroberts thank you for the answer, which saved my day!
