### ISSUE TITLE
Different sentiment class probabilities for sequential processing vs batch processing

### ISSUE THREAD

**Issue by Kayne88** [huggingface/transformers#18047]
### System Info

platform: windows
python: 3.7
transformers: latest
Model: finetuned BERT (from cardiffnlp/twitter-roberta-base-sentiment)

I have posted the issue here [https://discuss.huggingface.co/t/different-sentiments-when-texts-processed-in-batches-vs-singles/19462](url), but didn't receive any answer. The behavior is not really explainable and might look like a bug.

Cheers

@LysandreJik 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

see description under the above link.

### Expected behavior

I would expect the class probabilities to be equal for a given text, no matter if the classification is done sequentially or in batches.

**Comment by gante** [comment]
Hi @Kayne88 -- could you please share a complete script for reproducibility? In your [original script](https://discuss.huggingface.co/t/different-sentiments-when-texts-processed-in-batches-vs-singles/19462) you were missing the definition of `tokenizer` and `model` :)
