### ISSUE TITLE
Whether it belongs to the bug of class trainedtokenizer decode?

### ISSUE THREAD

**Issue by yuanxiaosc** [huggingface/transformers#1807]
## ❓ Questions & Help

![1](https://user-images.githubusercontent.com/16183570/68684557-a4bed780-05a3-11ea-8d06-1c5638be6ac6.png)
![2](https://user-images.githubusercontent.com/16183570/68684572-abe5e580-05a3-11ea-9620-847264507fae.png)

**Comment by LysandreJik** [comment]
You're right, this is an error. The PR #1811 aims to fix that issue!

**Comment by LysandreJik** [comment]
It should be fixed now, thanks! Feel free to re-open if the error persists.
