### ISSUE TITLE
LayoutLMv2ForRelationExtraction is missing in transformers

### ISSUE THREAD

**Issue by binkjakub** [huggingface/transformers#18091]
### Feature request

Microsoft's [unilim repository](https://github.com/microsoft/unilm/tree/db1095a693aa0d6d15bb9312cccb7f8af42b0aeb/layoutlmft/layoutlmft), which originally implements all `LayoutLM` models, contains implementation of the model for relation extraction with Biaffine Attention Classifier, namely [`LayoutLMv2ForRelationExtraction`](https://github.com/microsoft/unilm/blob/db1095a693aa0d6d15bb9312cccb7f8af42b0aeb/layoutlmft/layoutlmft/models/layoutlmv2/modeling_layoutlmv2.py#L895). However, this class wasn't included in `transfromers`, due to unknown reasons. Therefore, the implementation for relation extraction `LayoutLMv2ForRelationExtraction` should be included to extend current LayoutLMv2 and LayoutXLM.

### Motivation

This repository should implement all tasks included in papers ([LayoutLMv2](https://arxiv.org/pdf/2012.14740.pdf), [LayoutXLM](https://arxiv.org/pdf/2104.08836.pdf)) and [unilim repository]((https://github.com/microsoft/unilm/tree/db1095a693aa0d6d15bb9312cccb7f8af42b0aeb/layoutlmft/layoutlmft)), thus this missing part should be added to `transformers`. It would enable users to easily reproduce entire paper as well as convenient use of relation extraction in their downstream applications.

### Your contribution

If there are no obstacles unknown to me, I could try to move the implementation from unilim to transformers.

**Comment by LysandreJik** [comment]
cc @NielsRogge

**Comment by sijunhe** [comment]
+1 to this
