### ISSUE TITLE
Cannot set up development environment on Python 3.10

### ISSUE THREAD

**Issue by CakeCrusher** [huggingface/transformers#18112]
### System Info

- `transformers` version: 4.20.1
- Platform: Windows-10-10.0.19043-SP0
- Python version: 3.10.2
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@aaugustin @sgugger 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. under the same environment conditions 
2. go through the steps described in https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests
3. when you run `pip install -e ".[dev]"` you will see the following error 

> ERROR: Could not find a version that satisfies the requirement ray[tune]; extra == "dev" (from transformers[dev]) (from versions: none)
ERROR: No matching distribution found for ray[tune]; extra == "dev"

the full traceback:

> Obtaining file:///C:/Projects/transformers
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: filelock in c:\projects\transformers\env\lib\site-packages (from transformers==4.21.0.dev0) (3.7.1)
Requirement already satisfied: packaging>=20.0 in c:\projects\transformers\env\lib\site-packages (from transformers==4.21.0.dev0) (21.3)
Requirement already satisfied: pyyaml>=5.1 in c:\projects\transformers\env\lib\site-packages (from transformers==4.21.0.dev0) (6.0)
Collecting regex!=2019.12.17
  Using cached regex-2022.7.9-cp310-cp310-win_amd64.whl (262 kB)
Requirement already satisfied: tqdm>=4.27 in c:\projects\transformers\env\lib\site-packages (from transformers==4.21.0.dev0) (4.64.0)
Requirement already satisfied: numpy>=1.17 in c:\projects\transformers\env\lib\site-packages (from transformers==4.21.0.dev0) (1.23.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in c:\projects\transformers\env\lib\site-packages 
(from transformers==4.21.0.dev0) (0.8.1)
Requirement already satisfied: requests in c:\projects\transformers\env\lib\site-packages (from transformers==4.21.0.dev0) (2.28.1)
Collecting tokenizers!=0.11.3,<0.13,>=0.11.1
  Using cached tokenizers-0.12.1-cp310-cp310-win_amd64.whl (3.3 MB)
Collecting phonemizer
  Using cached phonemizer-3.2.1-py3-none-any.whl (90 kB)
Collecting tensorflow>=2.3
  Using cached tensorflow-2.9.1-cp310-cp310-win_amd64.whl (444.1 MB)
Collecting dill<0.3.5
  Using cached dill-0.3.4-py2.py3-none-any.whl (86 kB)
Collecting sentencepiece!=0.1.92,>=0.1.91
  Using cached sentencepiece-0.1.96-cp310-cp310-win_amd64.whl (1.1 MB)
Collecting onnxconverter-common
  Using cached onnxconverter_common-1.9.0-py2.py3-none-any.whl (78 kB)
Collecting pyctcdecode>=0.3.0
  Using cached pyctcdecode-0.3.0-py2.py3-none-any.whl (43 kB)
Collecting ipadic<2.0,>=1.0.0
  Using cached ipadic-1.0.0.tar.gz (13.4 MB)
Collecting torchaudio
  Using cached torchaudio-0.12.0-cp310-cp310-win_amd64.whl (969 kB)
Collecting unidic-lite>=1.0.7
  Using cached unidic-lite-1.0.8.tar.gz (47.4 MB)
Collecting sigopt
  Using cached sigopt-8.5.0-py2.py3-none-any.whl (182 kB)
Collecting timeout-decorator
  Using cached timeout-decorator-0.5.0.tar.gz (4.8 kB)
Collecting fugashi>=1.0
  Using cached fugashi-1.1.2-cp310-cp310-win_amd64.whl (497 kB)
Collecting protobuf<=3.20.1
  Using cached protobuf-3.20.1-cp310-cp310-win_amd64.whl (903 kB)
Collecting hf-doc-builder>=0.3.0
  Using cached hf_doc_builder-0.3.0-py3-none-any.whl (56 kB)
Collecting flake8>=3.8.3
  Using cached flake8-4.0.1-py2.py3-none-any.whl (64 kB)
Collecting cookiecutter==1.7.3
  Using cached cookiecutter-1.7.3-py2.py3-none-any.whl (34 kB)
Collecting tf2onnx
  Using cached tf2onnx-1.11.1-py3-none-any.whl (440 kB)
Collecting parameterized
  Using cached parameterized-0.8.1-py2.py3-none-any.whl (26 kB)
Collecting pytest-xdist
  Using cached pytest_xdist-2.5.0-py3-none-any.whl (41 kB)
Collecting unidic>=1.0.2
  Using cached unidic-1.1.0.tar.gz (7.7 kB)
Collecting sacrebleu<2.0.0,>=1.4.12
  Using cached sacrebleu-1.5.1-py3-none-any.whl (54 kB)
ERROR: Could not find a version that satisfies the requirement ray[tune]; extra == "dev" (from transformers[dev]) (from versions: none)
ERROR: No matching distribution found for ray[tune]; extra == "dev"
WARNING: You are using pip version 21.2.4; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Projects\transformers\env\Scripts\python.exe -m pip install --upgrade pip' command.

(this error stems the process significantly  to the extent that I couldn't run tests as a result)

### Expected behavior

When running this command in Python 10 the whole development process run without errors like it does with `Python 3.8.8`.

**Comment by sgugger** [comment]
As the error clearly mentions, this is because the ray package does not offer a distribution for Python 3.10, so I would open the issue there :-)

**Comment by aaugustin** [comment]
As a matter of GitHub etiquette, pinging random people ain't cool.

**Comment by CakeCrusher** [comment]
@sgugger yeah i forgot to mention that to resolve it you need to downgrade as mentioned in this issue https://github.com/ray-project/tune-sklearn/issues/169 but I figured idealy you would want development to work on any python distribution

@aaugustin 
[![image](https://user-images.githubusercontent.com/37946988/178571219-c79968a4-cecf-4eef-a6f5-53a30b50282d.png)](https://github.com/huggingface/transformers/commit/3233b58ad4aceb9d048b3c48cad44ef526470b53)

**Comment by aaugustin** [comment]
Exactly my point. Just because someone did something 3 years ago doesn't mean you can ping them. If I want to contribute to Hugging Face Transformers for free, I'll follow the repo!
