### ISSUE TITLE
model.generate doesn't validate kwargs

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#18130]
### Feature request

I made a mistake in a script:
```
model.generate(**tokens, in_length=num_tokens)
```
missing `m` in `min_length` and I was puzzling over why I was getting unexpected results (as it was using the default value which was quite different from mine)

Would it be possible to have `generate` validate its input and assert on unexpected args?

Thank you!

@patrickvonplaten

**Comment by LysandreJik** [comment]
cc @gante as well

**Comment by gante** [comment]
Hi @stas00 -- we do have a plan for it. The rough sketch is [here](https://github.com/huggingface/transformers/pull/17196#issuecomment-1155002093), and I will pick it up after the last wrinkles related to TF generate have been ironed out (which should be very soon!)

**Comment by stas00** [comment]
excellent. Thank you, @gante!

I guess let's keep this Issue open for tracking unless there is another one already?
