### ISSUE TITLE
MaskFormer documentation - `is_thing_map`

### ISSUE THREAD

**Issue by morrisalp** [huggingface/transformers#18157]
The MaskFormer documentation states: "Both tasks can be solved using [MaskFormerForInstanceSegmentation](https://huggingface.co/docs/transformers/v4.20.1/en/model_doc/maskformer#transformers.MaskFormerForInstanceSegmentation) output, the latter needs an additional is_thing_map to know which instances must be merged together.."

However, `is_thing_map` does not appear in the source code, and it looks like this was replaced with `label_ids_to_fuse`.

**Comment by LysandreJik** [comment]
cc @NielsRogge

**Comment by alaradirik** [comment]
@LysandreJik @NielsRogge I updated the MaskFormer docs to reflect the current code and added a [PR](https://github.com/huggingface/transformers/pull/18423)

**Comment by alaradirik** [comment]
I merged the PR, closing this issue!
