### ISSUE TITLE
computing self-attention for tokens in a sentence

### ISSUE THREAD

**Issue by vr25** [huggingface/transformers#1815]
## ❓ Questions & Help

Hi,

Please refer to this [issue](https://github.com/google-research/bert/issues/914).

Thanks!

**Comment by Colanim** [comment]
To get the attention score of each heads, refer to the [documentation](https://huggingface.co/transformers/model_doc/bert.html#transformers.BertModel) : see `outputs`.

---

> how do I know which heads give the best scores ?

You can't really know. Each heads will compute some kind of attention. It can be attention for "this token refer to that token", or it can be attention for "this token is similar to that token" or even if can be any kind of relation, even something, we human, can't interpret.  

If you want to extract some specific kind, I see no other solution than manually inspect all the heads' attention and empirically choose one (or several).  

Some papers did it : [Contrastive Attention Mechanism for Abstractive Sentence Summarization](https://arxiv.org/abs/1910.13114)

**Comment by vr25** [comment]
Thanks for your reply.

Please refer to [here](https://github.com/huggingface/transformers/issues/2054) for more details.

Thanks!
