### ISSUE TITLE
pretrain longT5

### ISSUE THREAD

**Issue by Arij-Aladel** [huggingface/transformers#18159]
Could you please provide us with the steps of pretraining the longT5 on both MLM and PSG objectives?
Denoising rates and other details and steps?

**Comment by reelmath** [comment]
https://arxiv.org/pdf/2112.07916.pdf

All the requested information is on the paper. I would recommend sending questions over to https://github.com/google-research/longt5 since the authors will be far more able to answer specific questions.

**Comment by Arij-Aladel** [comment]
@reelmath  thanks alot!  I already know that but the steps are in c++ script and no clear documentation to generate the corpus and using it to calculate loss. Since in Pegasus these are two losses. what is not clear do they calculate just one loss or two losses in longt5 during pretraining?

https://github.com/google-research/longt5/issues/7#issue-1319140379
