### ISSUE TITLE
Fine tune TrOCR for persian language

### ISSUE THREAD

**Issue by PersianSpock** [huggingface/transformers#18163]
### Model description

Hello! 
I'm a newbie and I am trying to use TrOCR for recognizing Persian digital text(like PDF) from image. I don't know what will be the requirements if I want to fine tune pre-trained TrOCR model but with decoder of multilingual cased. I've followed this post https://github.com/huggingface/transformers/issues/15823 but it doesn't work out for Persian with the info they gave.
Please guide me on how should I proceed? I've seen that there are some models in https://huggingface.co/models?language=fa&sort=downloads but I can't figure out how to use them. Please guide me.

### Open source status

- [x] The model implementation is available
- [x] The model weights are available

**Comment by NielsRogge** [comment]
Hi,

I explain how to train TrOCR on a different language here: https://github.com/huggingface/transformers/issues/14195#issuecomment-1039204836

**Comment by PersianSpock** [comment]
Hi Niels! Thank you for your response. the thing is that I use:
      ```
from transformers import VisionEncoderDecoderModel

      device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
      model = VisionEncoderDecoderModel.from_encoder_decoder_pretrained("google/vit-base-patch16-224-in21k", "xlm-roberta-base")
      model.to(device)
```
And I use your Fine_tune_TrOCR_on_IAM_Handwriting_Database_using_native_PyTorch code and at the end of the code my last result is this error:

> ValueError: Input image size (384*384) doesn't match model (224*224).

What's wrong?

**Comment by NielsRogge** [comment]
It seems that the images you provide are of size 384x384, but the model (the ViT encoder) expects them to be of size 224x224.

**Comment by PersianSpock** [comment]
I changed the images size but it still says that

**Comment by PersianSpock** [comment]
```
import os, sys

path = '/content/drive/MyDrive/data_test/image/'
new_path = '/content/drive/MyDrive/data_test/newimage/'
dirs = os.listdir( path )

def resize():
    for item in dirs:
        source = path + item
        newsource = new_path + item
        im = Image.open(source)
        f, e = os.path.splitext(source)
        imResize = im.resize((224,224), Image.ANTIALIAS)
        imResize.save(newsource)
```

**Comment by PersianSpock** [comment]
this part still gives 384, 384:

`encoding = train_dataset[0]
for k,v in encoding.items():
  print(k, v.shape)
encoding = eval_dataset[0]
for k,v in encoding.items():
  print(k, v.shape)`

**Comment by PersianSpock** [comment]
the problem in error seems to be because of the ViT and in your own code the training set is 384*384 as the last piece of code I commented shows 
what's wrong?

**Comment by NielsRogge** [comment]
The model I'm fine-tuning in my notebook expects images to be of size 384, as seen [here](https://huggingface.co/microsoft/trocr-base-printed/blob/main/config.json#L104).

**Comment by PersianSpock** [comment]
I used "google/vit-base-patch16-224-in21k" and "xlm-roberta-base". the first one you suggested in https://github.com/huggingface/transformers/issues/14195#issuecomment-1039204836
what is the issue that says the model has the picture of size 224*224?

**Comment by NielsRogge** [comment]
Yes, `google/vit-base-patch16-224-in21k` expects images to be of size 224, but you're resizing the images to 384.

**Comment by PersianSpock** [comment]
```
def resize():
    for item in dirs:
        source = path + item
        newsource = new_path + item
        im = Image.open(source)
        f, e = os.path.splitext(source)
        imResize = im.resize((224,224), Image.ANTIALIAS)
        imResize.save(newsource) 


```
im turning it to 224 but still my training set is 384. I tried my training set 384 and test set 224 but it doesn't work either

**Comment by PersianSpock** [comment]
can you please take a look at my code and say what is wrong?

https://colab.research.google.com/drive/1H47WtAPfecwjI17iGtNkWc75gFjPYG-8?usp=sharing

**Comment by PersianSpock** [comment]
you create a class IAMDataset(Dataset), do you change the size of an image in this class? because after I create my dataset with this class the image sizes get back to 384.

**Comment by PersianSpock** [comment]
Thank you it got solved! How much should be my validation CER at the end? what range is good enough?

**Comment by PersianSpock** [comment]
i get Validation CER: 0.9615384615384616. is it good enough?

**Comment by PersianSpock** [comment]
I'm fine tuning trocr for Farsi language and I did it once using your code and it was ok and now with another larger dataset I get different label sizes and it's a problem. 
after this part:
`encoding = train_dataset[0]
for k,v in encoding.items():
  print(k, v.shape)
encoding = eval_dataset[0]
for k,v in encoding.items():
  print(k, v.shape)`

I get:

> pixel_values torch.Size([3, 224, 224])
> labels torch.Size([1220])
> pixel_values torch.Size([3, 224, 224])
> labels torch.Size([1146])

label torch sizes are not the same although I'm using https://github.com/NielsRogge/Transformers-Tutorials/tree/master/TrOCR
and it the code it says that the max_length for labels should be 128. how can I change the code so it'll be the same size for all of the data?

**Comment by NielsRogge** [comment]
> How much should be my validation CER at the end?

CER (character error rate) is a number between 0 and 1, the closer to 0 the better.

Regarding the labels, you need to make sure each target sequence gets padded/truncated to the same length, to make batching possible.

**Comment by PersianSpock** [comment]
I'm using your own code. it has:
`labels = self.processor.tokenizer(text, 
                                          padding="max_length", 
                                          max_length=self.max_target_length).input_ids`

and 
`self.max_target_length = 128`

how am I getting different numbers?

**Comment by NielsRogge** [comment]
Yes it doesn't have `truncation=True`, which you need to add.

**Comment by NielsRogge** [comment]
Note that the sequence length of 128 was just a choice, you can set it to whatever you think is needed for the language you're training on. If you're training on very long sentences, you might need to increase it.

**Comment by PersianSpock** [comment]
Thank you so much it worked out.

**Comment by jonas-da** [comment]
@PersianSpock which processor do you use for training on an other language ? 

do you use a processor which is build up of the same encoders and decoders, or do you use the handwritten stage 1 processor, which is pre-trained already ? 

it would really help, If you could post your Model and processor initialization. And maybe also your config. 
Thank you!

**Comment by PersianSpock** [comment]
since I am using xlm-roberta-large I do it like this:

```
feature_extractor = ViTFeatureExtractor.from_pretrained('google/vit-base-patch16-224-in21k')
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

processor = TrOCRProcessor(feature_extractor = feature_extractor, tokenizer = tokenizer
```

**Comment by PersianSpock** [comment]
@jonas-da it says here: https://huggingface.co/docs/transformers/main/model_doc/trocr#transformers.TrOCRProcessor

since I am using xlm-roberta-large I do it like this:

feature_extractor = ViTFeatureExtractor.from_pretrained('google/vit-base-patch16-224-in21k')
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

processor = TrOCRProcessor(feature_extractor = feature_extractor, tokenizer = tokenizer

**Comment by jonas-da** [comment]
Ah thank you! @PersianSpock 

and as above mentioned you use 

`model = VisionEncoderDecoderModel.from_encoder_decoder_pretrained("google/vit-base-patch16-224-in21k", "xlm-roberta-base")`

as model or ? 

One more question. How much Training Data do you use and what CER did you achieved ? 

Thank you very much!

**Comment by PersianSpock** [comment]
I used base and large both and for the data I used 7000 data and it still wasn't enough and I think I should use more.

**Comment by NielsRogge** [comment]
Closing this issue as it seems resolved.

**Comment by jasmine400** [comment]
@PersianSpock  how did you prepare dataset for train trocr on other language ?

**Comment by Ulduzpp** [comment]
> Thank you it got solved! How much should be my validation CER at the end? what range is good enough?
hi, may I ask how did you solve it? I have the same problem but I got stuck and don't know what to do

**Comment by CrasCris** [comment]
> ow

how did you change the input size for the model ? i got this error 
"ValueError: Input image size (384*384) doesn't match model (224*224)."
