### ISSUE TITLE
NLLB model file for the 600M model

### ISSUE THREAD

**Issue by Olubayode** [huggingface/transformers#18174]
1. Please where can I locate the  MODEL_FILE i.e  the Path to python file containing the model architecture. I believe the model architecture file will contain only one class definition extended from torch.nn.modules.
2. Please where can I locate  the Handler file that can be use for TorchServe inference logic. 

Please me out with the location to the model_File and handler file

**Comment by NielsRogge** [comment]
Hi,

The 600 million parameter model can be found here: https://huggingface.co/facebook/nllb-200-distilled-600M.

The weights of the model can be found in the "files and versions" tab (check the "pytorch_model.bin" file): https://huggingface.co/facebook/nllb-200-distilled-600M/tree/main.

**Comment by NielsRogge** [comment]
Closing this issue as I feel like this has been answered, feel free to reopen.
