### ISSUE TITLE
Model Loading Imbalance

### ISSUE THREAD

**Issue by c-liangyu** [huggingface/transformers#18176]
### System Info

- `transformers` version: 4.20.1
- Platform: Linux-5.4.0-81-generic-x86_64-with-glibc2.31
- Python version: 3.10.4
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): 1.12.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: I guess I tried :)

### Who can help?

@patil-suraj @patrickvonplaten @LysandreJik 
This is a OPT related issue.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
with init_empty_weights():
    model = OPTModel.from_pretrained("facebook/opt-6.7b", device_map="auto")
```

Model loading imbalance across the GPUs.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/45140242/179495680-b1a4dae5-be85-4818-a969-8a58346be57d.png">

### Expected behavior

Model parameter numbers are balanced.

**Comment by LysandreJik** [comment]
I think @sgugger is working on that as we speak

**Comment by sgugger** [comment]
Yes, we will add support for more options to `device_map`, one of which is `"balanced"` after the next release. It's already available in Accelerate if you want to try it on.
