### ISSUE TITLE
add Decision Transformer ONNX config to Transformers

### ISSUE THREAD

**Issue by skanjila** [huggingface/transformers#18191]
### Feature request

Add Decision Transformer OnnxConfig to make this model available for conversion.

### Motivation

This is part of adding OnnxConfigs for unsupported models https://huggingface.co/docs/transformers/v4.20.1/en/serialization#exporting-a-model-for-an-unsupported-architecture

### Your contribution

I will be submitting a new PR to address DecisionTransformer model

**Comment by skanjila** [comment]
@ChainYo @regisss Issue is here, will add PR once its in a workable state

**Comment by skanjila** [comment]
@ChainYo @regisss I am finally starting work on this, sorry about the delay, so I was reading through the code in this PR and using that as an example: https://github.com/huggingface/transformers/pull/14059/files, one question here, I was trying to understand how we determine what goes in the json structure below, I understand about the last config term but its the terms before it that I was trying to dig into, any insight you guys can provide into this would be most helpful:

"camembert": supported_features_mapping(
            "default",
            "causal-lm",
            "sequence-classification",
            "token-classification",
            "question-answering",
            onnx_config_cls=CamembertOnnxConfig,
        ),

**Comment by ChainYo** [comment]
> @ChainYo @regisss I am finally starting work on this, sorry about the delay, so I was reading through the code in this PR and using that as an example: https://github.com/huggingface/transformers/pull/14059/files, one question here, I was trying to understand how we determine what goes in the json structure below, I understand about the last config term but its the terms before it that I was trying to dig into, any insight you guys can provide into this would be most helpful:

Hi @skanjila, if you check the associated docs for `Decision Transformer`, you can see that there is no other feature than the default: https://huggingface.co/docs/transformers/model_doc/decision_transformer

![image](https://user-images.githubusercontent.com/50595514/189597188-c1a6d021-3611-4f12-9e5f-8118cf863451.png)

I think that for this model, `default` is the only convenient feature.

**Comment by skanjila** [comment]
@ChainYo I think what you're saying is that the only parameters that are needed are the following as mentioned in the documentation in the configuration section, is that correct? 

( state_dim = 17act_dim = 4hidden_size = 128max_ep_len = 4096action_tanh = Truevocab_size = 1n_positions = 1024n_embd = 768n_layer = 3n_head = 1n_inner = Noneactivation_function = 'relu'resid_pdrop = 0.1embd_pdrop = 0.1attn_pdrop = 0.1layer_norm_epsilon = 1e-05initializer_range = 0.02summary_type = 'cls_index'summary_use_proj = Truesummary_activation = Nonesummary_proj_to_labels = Truesummary_first_dropout = 0.1scale_attn_weights = Trueuse_cache = Truebos_token_id = 50256eos_token_id = 50256scale_attn_by_inverse_layer_idx = Falsereorder_and_upcast_attn = False**kwargs )

Let me know if I am missing anything here
