### ISSUE TITLE
Argument inconsistency between processor and tokenizer

### ISSUE THREAD

**Issue by qqaatw** [huggingface/transformers#18209]
### System Info

transformers on master

### Who can help?

@sgugger who modified the line lastly from git blame

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

In `processing_utils.py`, to use the slow version, one needs to specify `use_fast=False` in `from_pretrained`,

https://github.com/huggingface/transformers/blob/d0acc9537829e7d067edbb791473bbceb2ecf056/src/transformers/processing_utils.py#L222-L226

while in `tokenization_utils_base.py`, to use the slow version, one needs to specify `from_slow=True` in `from_pretrained`

https://github.com/huggingface/transformers/blob/d0acc9537829e7d067edbb791473bbceb2ecf056/src/transformers/tokenization_utils_base.py#L1804-L1815

This inconsistency leads to strange usages. 

For example, when we want to use the slow version of LayoutLMv2 processor, we have to pass both arguments simultaneously:

```python
processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", use_fast=False, from_slow=True)
```

### Expected behavior

I suggest we change the option in  `processing_utils.py` from `use_fast` to `from_slow`.

**Comment by sgugger** [comment]
No `from_slow` is an internal argument that determines whether the tokenizer should be loaded from slow tokenizer files or a fast tokenizer file. That is why you're not finding it in the documentation for instance.

**Comment by qqaatw** [comment]
@sgugger  Oh thanks. I confused the purpose of `from_slow`. Now it looks that I can only use `use_fast` to get the slow version.
