### ISSUE TITLE
Is there a way of finetuning DistilGPT2?

### ISSUE THREAD

**Issue by aditya1702** [huggingface/transformers#1820]
## ❓ Questions & Help

Hello! I am trying to finetune GPT2 for a project of mine but my aim is to deploy the model on a server and hence, I would like the final model file to be small. I was thinking of using the Distil* models especially the DistilGPT2 but couldnt find it in the run_lm_finetuning.py script. 

Currently, is finetuning distilGPT2 supported? If yes, then how should I do it?

**Comment by iedmrc** [comment]
Yes you can, add these parameters to `run_lm_finetuning`:

```
--model_type gpt2 \
--model_name_or_path distilgpt2 
```

**Comment by Abbyyan** [comment]
I can't find the file `run_lm_finetuning.py` under this repo. Could you please give the full file path please? Thanks a lot.

**Comment by Abbyyan** [comment]
> I can't find the file `run_lm_finetuning.py` under this repo. Could you please give the full file path please? Thanks a lot.

Got it . it has been renamed to [run_language_modeling.py](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py) now.
