### ISSUE TITLE
Can't load tokenizer for longt5-xl

### ISSUE THREAD

**Issue by whiteRa2bit** [huggingface/transformers#18227]
### System Info

transformers version: 4.20.0
Platform: Linux-4.15.0-135-generic
Python version: 3.8.13
PyTorch version (GPU?): torch==1.10.2+cu113
Using GPU in script?: no
Using distributed or parallel set-up in script?: no

### Who can help?

@patrickvonplate

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm using the example provided on this page: https://huggingface.co/google/long-t5-tglobal-xl:
```

from transformers import AutoTokenizer, LongT5Model

tokenizer = AutoTokenizer.from_pretrained("google/long-t5-tglobal-xl")
```

### Expected behavior

A tokenizer for a longt5-xl works

**Comment by NicolasAG** [comment]
I have the same issue: When I try to load the model with its tokenizer I get the following error message:
```
OSError: Can't load tokenizer for 'google/long-t5-tglobal-xl'.
If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name.
Otherwise, make sure 'google/long-t5-tglobal-xl' is the correct path to a directory containing all relevant files for a T5TokenizerFast tokenizer.
```

**Comment by LysandreJik** [comment]
Indeed, it seems the tokenizer files were not uploaded to that repository. Pinging @stancld, could you mention which tokenizer files should be used here? I'm happy to add these to `google`'s repositories.

**Comment by stancld** [comment]
@LysandreJik AFAIK, the `LongT5` models use the same tokenizer as the `T5` model. I'd, therefore, just copy the `tokenizer.json` config e.g. from `LongT5-TGlobal-Large` to the XL repo, and it should work as expected.

**Comment by LysandreJik** [comment]
Sounds good, I'll take care of that. Thanks!

**Comment by LysandreJik** [comment]
Should work now, this was the only repository that needed to be updated (was lacking the tokenizer files). Feel free to close this issue if your problem is solved!
