### ISSUE TITLE
VisualBERT, visual feature projection.

### ISSUE THREAD

**Issue by Shiv681991** [huggingface/transformers#18228]
The default implementation takes in 1x197x768 visual features and gives an error while multiplying 197x768 with 2048x768 (or 1021/512 x 768 depending upon the model used).
Do we really need to modify the inner visual projection code for VisualBERT? Feels weird. Can someone help pl?

**Comment by LysandreJik** [comment]
cc @gchhablani

**Comment by gchhablani** [comment]
@Shiv681991 Can you please share some code examples of what you are trying to do? It'll help me replicate and understand the issue better.
