### ISSUE TITLE
how to use convert_pytorch_checkpoint_to_tf2.py 

### ISSUE THREAD

**Issue by chiyuzhang94** [huggingface/transformers#1823]
## ❓ Questions & Help
I am wondering how to use convert_pytorch_checkpoint_to_tf2.py to convert pytorch checkpoint to tensorflow checkpoint.  I found Comparing-PT-and-TF-models.ipynb have an example to use pytorch_pretrained_bert. But It doesn't work for convert_pytorch_checkpoint_to_tf2. Could you please give me any help?

**Comment by LysandreJik** [comment]
Hi, you can show the help with the following command:

```
python transformers/convert_pytorch_checkpoint_to_tf2.py --help  
```

What is your use-case?

**Comment by chiyuzhang94** [comment]
> Hi, you can show the help with the following command:
> 
> ```
> python transformers/convert_pytorch_checkpoint_to_tf2.py --help  
> ```
> 
> What is your use-case?

Thanks for your suggestion. I used convert_bert_pytorch_checkpoint_to_original_tf. It works for me.
