### ISSUE TITLE
Add callback that saves only best checkpoints

### ISSUE THREAD

**Issue by KseniaSycheva** [huggingface/transformers#18240]
### Feature request

A new class for a callback that saves checkpoint only if it performs better than the previous checkpoint on the evaluation dataset. It can work similar to the [EvalCallback](https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html) that is proposed by stable_baselines3.

### Motivation

This callback will enable evaluating model frequently without using a lot of memory, because only several checkpoints will  be kept. 

### Your contribution

Submitting PR

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
We already have `save_total_limits` to limit the number of checkpoint saved, and with `load_best_model_at_end=True` the best checkpoint is always kept. Which use case that is not currently available would this new callback permit?

**Comment by KseniaSycheva** [comment]
I haven't noticed that it is possible to use these options together. The only thing that is different in proposed callback is that all saved checkpoints perform better on the evaluation dataset than the rest of the checkpoints.
