### ISSUE TITLE
RuntimeError: "triu_tril_cuda_template" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by DogeWatch** [huggingface/transformers#18246]
### System Info

transformers==4.19.2

### Who can help?

use bf16 with accelerate config
```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
use_cpu: false
```
model is LongformerModel, and get error

File "~/miniconda3/envs/bai/lib/python3.8/site-packages/transformers/models/longformer/modeling_longformer.py", line 788, in _mask_invalid_locations
    beginning_mask_2d = input_tensor.new_ones(affected_seq_len, affected_seq_len + 1).tril().flip(dims=[0])
RuntimeError: "triu_tril_cuda_template" not implemented for 'BFloat16'

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

none

### Expected behavior

none

**Comment by xiezhipeng-git** [comment]
I have same error. And it is only in windows.How can I do can resolve it.Although WSL does not have this error, running CUDA programs on Windows always causes VSCode to disconnect or the computer to freeze (the screen is static, all input functions are disabled, including keyboard and mouse), or a blue screen occurs.
