### ISSUE TITLE
Not able to load the Facebook OPT model

### ISSUE THREAD

**Issue by xiajinxiong** [huggingface/transformers#18245]
### System Info

- `transformers` version: 4.20.1
- Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.10
- Python version: 3.8.3
- Huggingface_hub version: 0.5.1
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): 2.6.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Who can help?

@LysandreJik

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("facebook/opt-13b", torch_dtype=torch.float16)
```

Errors:

KeyError                                  Traceback (most recent call last)

<ipython-input-15-00179d7539d3> in <module>
      2 from transformers import AutoModelForCausalLM, AutoTokenizer
      3 
----> 4 model = AutoModelForCausalLM.from_pretrained("facebook/opt-13b", torch_dtype=torch.float16)

~/workspace/anaconda3/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    421         kwargs["_from_auto"] = True
    422         if not isinstance(config, PretrainedConfig):
--> 423             config, kwargs = AutoConfig.from_pretrained(
    424                 pretrained_model_name_or_path, return_unused_kwargs=True, trust_remote_code=trust_remote_code, **kwargs
    425             )

~/workspace/anaconda3/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    670 
    671         Examples:
--> 672 
    673         ```python
    674         >>> from transformers import AutoConfig

~/workspace/anaconda3/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py in __getitem__(self, key)
    385         ("xlsr_wav2vec2", "XLSR-Wav2Vec2"),
    386         ("yolos", "YOLOS"),
--> 387         ("yoso", "YOSO"),
    388     ]
    389 )

KeyError: 'opt'

### Expected behavior

The code is expected to run with any error.

**Comment by LysandreJik** [comment]
Hey @xiajinxiong, this seems to be a version error!

In order to verify, could you run the following snippet and copy-paste the output?

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, __version__

print("Version", __version__)
model = AutoModelForCausalLM.from_pretrained("facebook/opt-13b", torch_dtype=torch.float16)
```

**Comment by xiajinxiong** [comment]
I reaffirmed that the transformers version was 4.20.1.
But it's because my jupyter kernel didn't synchronize with the transformers version.
After I restart the jupyter, it works fine.
Thanks.

**Comment by xiajinxiong** [comment]
I reaffirmed that the transformers version was 4.20.1.
But it's because my jupyter kernel didn't synchronize with the transformers version.
After I restart the jupyter, it works fine.
Thanks.
