### ISSUE TITLE
cannot import name 'TrainingArguments' from 'transformers'

### ISSUE THREAD

**Issue by takfarine** [huggingface/transformers#18269]
### System Info

Traceback (most recent call last):
  File "dv2xxl.py", line 30, in <module>
    from transformers import TrainingArguments,Trainer
**ImportError: cannot import name 'TrainingArguments' from 'transformers'** (/lustre06/project/6005433/takfa/UW/ue/lib/python3.7/site-packages/transformers/__init__.py)

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Traceback (most recent call last):
  File "dv2xxl.py", line 30, in <module>
    from transformers import TrainingArguments,Trainer
ImportError: cannot import name 'TrainingArguments' from 'transformers' (/lustre06/project/6005433/takfa/UW/ue/lib/python3.7/site-packages/transformers/__init__.py)

### Expected behavior

looking for help

**Comment by LysandreJik** [comment]
Hey! Could you please provide your transformers version? How did you install transformers?

**Comment by rabeya-ferdousi** [comment]
Problem in "from transformers import TrainingArguments,Trainer" How to resolve it
