### ISSUE TITLE
'FlavaModelOutput' object has no attribute 'contrastive_logits_per_image'

### ISSUE THREAD

**Issue by ans92** [huggingface/transformers#18279]
Hi, I have used a code of Flava model from this link:
```
https://huggingface.co/docs/transformers/model_doc/flava#transformers.FlavaModel.forward.example
```
But I am getting the following error:
```
'FlavaModelOutput' object has no attribute 'contrastive_logits_per_image'
```
Could you please help me in solving the above question. Thank you.

**Comment by LysandreJik** [comment]
Hey @ans92! It seems there's an error in the documentation indeed. This code example works with the `FlavaForPreTraining` model, rather than the `FlavaModel.

Would you like to open a Pr to fix this?

**Comment by Maddy12** [comment]
I am experiencing this issue as well and the documentation shows it with the `FlavaModel`. 

There are also a large set of warnings when loading the `FlavaModel`, is this normal?

**Comment by thesofakillers** [comment]
This issue needs re-opening

**Comment by DianeBouchacourt** [comment]
Yes agreed, I just ran in the same issue and I also think it needs re-opening. Only following the doc here with `FlavaForPreTraining` works
https://huggingface.co/facebook/flava-full
