### ISSUE TITLE
Define metric for save the best model

### ISSUE THREAD

**Issue by dimka11** [huggingface/transformers#18274]
### Feature request

I suggest to add a metric choice to save the best model

### Motivation

I use multiple metrics in process of fine tuning models through Trainer and don't know how the metric is chosen to save the best model (I suppose it's first metric in dictionaty?!).

### Your contribution

-

**Comment by pkavumba** [comment]
If you are using HF trainer it provides two arguments for selecting your preferred metric for choosing the best model. The first one is
`metric_for_best_model`. It defaults to "loss". The second argument is `greater_is_better`. The default value is `False` but If metric for best model is set to any value other than "loss" then it will default to `True`
