### ISSUE TITLE
This code block will not be executed 

### ISSUE THREAD

**Issue by AlfredQin** [huggingface/transformers#18270]
### System Info

python 3.9

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

[](urlhttps://github.com/huggingface/transformers/blob/main/src/transformers/models/detr/modeling_detr.py)

`        combined_attention_mask = None

        if attention_mask is not None and combined_attention_mask is not None:
            # [bsz, seq_len] -> [bsz, 1, tgt_seq_len, src_seq_len]
            combined_attention_mask = combined_attention_mask + _expand_mask(
                attention_mask, inputs_embeds.dtype, tgt_len=input_shape[-1]
            )`

### Expected behavior

The combined_attention_mask is set to None, so the if code block below it will never be executed because it  will check combined_attention_mask is not None.

**Comment by LysandreJik** [comment]
Where is that code block from?

**Comment by AlfredQin** [comment]
The code block is from https://github.com/huggingface/transformers/blob/8e8384663d716d4b5a4f510070ff954fc0ba4a52/src/transformers/models/detr/modeling_detr.py#L1076

**Comment by LysandreJik** [comment]
cc @NielsRogge

**Comment by NielsRogge** [comment]
Hi @AlfredQin, thanks for spotting that. The combined_attention_mask was probably taken from another model, which is not relevant for DETR.

Feel free to open a PR to remove that code block!
