### ISSUE TITLE
Run_mlm.py for fine-tuning generator(mlm) of electra 

### ISSUE THREAD

**Issue by ToanKGO** [huggingface/transformers#18285]
Hi, I have a new corpus and want to fine-tune ELECTRA for better result. ELECTRA used generator as generator after that used discriminator. Can run file run_mlm.py makes my pre-trained electra works better ?

**Comment by stefan-it** [comment]
Hi @ToanKGO,

I think the latest update on the ELECTRA pretraining/fine-tuning is this comment from @LysandreJik :+1: 
https://github.com/huggingface/transformers/pull/4656#issuecomment-711082850

So you could use e.g. this implementation: https://github.com/richarddwang/electra_pytorch
