### ISSUE TITLE
Numpy arrays used instead of jax array in example

### ISSUE THREAD

**Issue by isunitha98selvan** [huggingface/transformers#18287]
### System Info

The example[ here](https://github.com/huggingface/transformers/blob/main/examples/flax/text-classification/run_flax_glue.py#L286) should yield jax device arrays instead of numpy arrays. 

@patil-suraj

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/blob/main/examples/flax/text-classification/run_flax_glue.py#L286

### Expected behavior

Should return batches with jax device arrays

**Comment by sanchit-gandhi** [comment]
Answered in https://github.com/huggingface/transformers/issues/18289#issuecomment-1198216304
