### ISSUE TITLE
NotImplementedError when using TFDistilBertModel

### ISSUE THREAD

**Issue by Riccorl** [huggingface/transformers#1829]
## 🐛 Bug

I have this error when I train a model with TFDistilBertModel. The same code works if I change to BERT for example. The transformers is loaded with `TFDistilBertModel.from_pretrained("distilbert-base-uncased")`

```
  File "/home/<user>/miniconda3/envs/nlp/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NotImplementedError: in converted code:
    relative to /home/<user>:

    ../models.py:68 call  *
        bert_hidden_states = self.model(
    miniconda3/envs/nlp/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:842 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    miniconda3/envs/nlp/lib/python3.7/site-packages/transformers/modeling_tf_distilbert.py:545 call  *
        outputs = self.distilbert(inputs, **kwargs)
    miniconda3/envs/nlp/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:842 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    miniconda3/envs/nlp/lib/python3.7/site-packages/transformers/modeling_tf_distilbert.py:431 call  *
        raise NotImplementedError

    NotImplementedError: 


```
## Environment

* OS: Manjaro
* Python version: 3.7.5
* TF: 2.0
* Using GPU ? Yes

**Comment by TheEdoardo93** [comment]
> ##  Bug
> I have this error when I train a model with TFDistilBertModel. The same code works if I change to BERT for example. The transformers is loaded with `TFDistilBertModel.from_pretrained("distilbert-base-uncased")`
> 
> ```
>   File "/home/<user>/miniconda3/envs/nlp/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
>     raise e.ag_error_metadata.to_exception(e)
> NotImplementedError: in converted code:
>     relative to /home/<user>:
> 
>     ../models.py:68 call  *
>         bert_hidden_states = self.model(
>     miniconda3/envs/nlp/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:842 __call__
>         outputs = call_fn(cast_inputs, *args, **kwargs)
>     miniconda3/envs/nlp/lib/python3.7/site-packages/transformers/modeling_tf_distilbert.py:545 call  *
>         outputs = self.distilbert(inputs, **kwargs)
>     miniconda3/envs/nlp/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:842 __call__
>         outputs = call_fn(cast_inputs, *args, **kwargs)
>     miniconda3/envs/nlp/lib/python3.7/site-packages/transformers/modeling_tf_distilbert.py:431 call  *
>         raise NotImplementedError
> 
>     NotImplementedError: 
> ```
> 
> ## Environment
> * OS: Manjaro
> * Python version: 3.7.5
> * TF: 2.0
> * Using GPU ? Yes

In my case, HuggingFace's Transformers seems to not expose the TFDistilBertModel class (with the PyTorch version of the model it works as expected).

**TensorFlow version:**
```
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
>>> from transformers import DistilBertTokenizer, TFDistilBertModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TFDistilBertModel'
```

**PyTorch version**

```
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
>>> from transformers import DistilBertTokenizer, DistilBertModel
>>>
```

**Environment:**

- Python: 3.6.9
- Transformers: 2.2.1. (installed from source)
- PyTorch: 1.3.1
- TensorFlow: 2.0.0
- GPU? No

**Comment by TheEdoardo93** [comment]
In my environemnt, it **works as expected**.

**Environment:**

- Python: 3.6.9
- HuggingFace's Transformers: 2.1.1 (installed **today** from source with `pip install git+https://github.com/huggingface/transformers`)
- PyTorch: 1.3.1
- TensorFlow: 2.0

Below the execution:
```
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
/home/<user>/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-11-14 13:56:38.199689: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-14 13:56:38.337808: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-11-14 13:56:38.338355: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560bcbc86ae0 executing computations on platform Host. Devices:
2019-11-14 13:56:38.338375: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
>>> transformers.__version__
'2.1.1'
>>> import torch
>>> torch.__version__
'1.3.1'
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0'
>>> import platform
>>> platform.platform()
'Linux-4.15.0-69-generic-x86_64-with-debian-buster-sid'
>>> platform.python_version()
'3.6.9'
>>> from transformers import DistilBertTokenizer, TFDistilBertModel
>>> tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
>>> model = TFDistilBertModel.from_pretrained('distilbert-base-uncased')
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 363423424/363423424 [00:39<00:00, 9179101.04B/s]
2019-11-14 13:58:58.633432: W tensorflow/python/util/util.cc:299] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
>>> 
```

> ##  Bug
> I have this error when I train a model with TFDistilBertModel. The same code works if I change to BERT for example. The transformers is loaded with `TFDistilBertModel.from_pretrained("distilbert-base-uncased")`
> 
> ```
>   File "/home/<user>/miniconda3/envs/nlp/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
>     raise e.ag_error_metadata.to_exception(e)
> NotImplementedError: in converted code:
>     relative to /home/<user>:
> 
>     ../models.py:68 call  *
>         bert_hidden_states = self.model(
>     miniconda3/envs/nlp/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:842 __call__
>         outputs = call_fn(cast_inputs, *args, **kwargs)
>     miniconda3/envs/nlp/lib/python3.7/site-packages/transformers/modeling_tf_distilbert.py:545 call  *
>         outputs = self.distilbert(inputs, **kwargs)
>     miniconda3/envs/nlp/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py:842 __call__
>         outputs = call_fn(cast_inputs, *args, **kwargs)
>     miniconda3/envs/nlp/lib/python3.7/site-packages/transformers/modeling_tf_distilbert.py:431 call  *
>         raise NotImplementedError
> 
>     NotImplementedError: 
> ```
> 
> ## Environment
> * OS: Manjaro
> * Python version: 3.7.5
> * TF: 2.0
> * Using GPU ? Yes

**Comment by Riccorl** [comment]
@TheEdoardo93 thank you for showing me it's not a problem of the library. I uninstalled and reinstalled from source (like you did) and now it works.
