### ISSUE TITLE
Migrate metrics used in all examples from Datasets to Evaluate

### ISSUE THREAD

**Issue by sgugger** [huggingface/transformers#18306]
The metrics are slowly leaving [Datasets](https://github.com/huggingface/datasets) (they are being deprecated as we speak) to move to the [Evaluate](https://github.com/huggingface/evaluate) library. We are looking for contributors to help us with the move.

Normally, the migration should be as easy as replacing the import of `load_metric` from Datasets to the `load` function in Evaluate. See a use in this [Accelerate example](https://github.com/huggingface/accelerate/blob/1486fa35b19abc788ddb609401118a601e68ff5d/examples/nlp_example.py#L104). To fix all tests, a dependency to evaluate will need to be added in the [requirements file](https://github.com/huggingface/transformers/blob/main/examples/pytorch/_tests_requirements.txt) (this is the link for PyTorch, there is another one for the Flax examples).

If you're interested in contributing, please reply to this issue with the examples you plan to move.

**Comment by atturaioe** [comment]
Hi, I would like to try to move Pytorch examples.

**Comment by sgugger** [comment]
Please go ahead and make a PR when you're ready then @atturaioe. You can check our [contributing guide](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md) to get started.

**Comment by VijayKalmath** [comment]
@sgugger  , I would like to work on the tensorflow examples.

**Comment by sgugger** [comment]
Please go ahead @VijayKalmath :-)

**Comment by VijayKalmath** [comment]
@sgugger , I wanted to know if there are tests to run the examples in the tensorflow folder.

**Comment by sgugger** [comment]
No tests for TensorFlow yet, we'll add those in the near future.

**Comment by VijayKalmath** [comment]
@sgugger , I don't think anyone is working on the flax examples. Will open a new PR for migrating the flax examples?

**Comment by sgugger** [comment]
By all means, please go ahead! The only change will be that those are actually tested.

**Comment by atturaioe** [comment]
@sgugger, can I work on `research_projects` examples?

**Comment by sgugger** [comment]
@atturaioe We don't update research projects to the new APIs as they use pinned versions of libraries. So this one should stay as is unless the author want to do a general update of them. Thanks for offering though!
