### ISSUE TITLE
"AttributeError: cls.seq_relationship.weight not found in PyTorch model" when converting pytorch to tensorflow

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#18316]
### System Info

- `transformers` version: 4.21.0.dev0
- Platform: Linux-5.15.0-41-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): 1.12.0+cu113 (True)
- Tensorflow version (GPU?): 2.9.1 (True)

### Who can help?

 @Rocketknight1 @sgugger

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying to convert [this model](https://huggingface.co/BramVanroy/bert-base-dutch-cased-hebban-reviews) to a tensorflow checkpoint on the command line. (I know that users can specify `from_pt` but I'd like the models to be present in both formats from the start). The model has been finetuned on a text classification task.

When I run

```python
from transformers.convert_pytorch_checkpoint_to_tf2 import convert_pt_checkpoint_to_tf
convert_pt_checkpoint_to_tf("bert", "/path/to/pytorch_model.bin", "/path/to/config.json", "my_output_dir")
```

I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bram/Python/projects/transformers-finetuner/transformers/src/transformers/convert_pytorch_checkpoint_to_tf2.py", line 326, in convert_pt_checkpoint_to_tf
    tf_model = load_pytorch_checkpoint_in_tf2_model(tf_model, pytorch_checkpoint_path)
  File "/home/bram/Python/projects/transformers-finetuner/transformers/src/transformers/modeling_tf_pytorch_utils.py", line 126, in load_pytorch_checkpoint_in_tf2_model
    return load_pytorch_weights_in_tf2_model(
  File "/home/bram/Python/projects/transformers-finetuner/transformers/src/transformers/modeling_tf_pytorch_utils.py", line 210, in load_pytorch_weights_in_tf2_model
    raise AttributeError(f"{name} not found in PyTorch model")
AttributeError: cls.seq_relationship.weight not found in PyTorch model
```

### Expected behavior

No error and a correct conversion of my model to TF.

**Comment by Rocketknight1** [comment]
Hi @BramVanroy, you shouldn't ever need to directly call `convert_pt_checkpoint_to_tf`. If you want to make a native TensorFlow checkpoint for that model, then the easiest way would be just:

```
model = TFAutoModelForSequenceClassification.from_pretrained("BramVanroy/bert-base-dutch-cased-hebban-reviews", from_pt=True)
model.save_pretrained("bert-base-dutch-cased-hebban-reviews-tf")
```
