### ISSUE TITLE
Only use one gpu when generating the hidden states (text embeddings) by "Model output" api

### ISSUE THREAD

**Issue by zyddora** [huggingface/transformers#18311]
### System Info

Report an issue about model output efficiency. 
I want to get the certain hidden states from the fine-tuned roberta model, then I chose Model Output api([link](https://huggingface.co/docs/transformers/main_classes/output#transformers.utils.ModelOutput)) to get those dense embeddings. 
However, when executing below model output code, only ONE gpu is used (actually, I have one worker with 4 gpus), which severely hinders inference efficiency. Also, I cannot find the instructions or docs to help to use multiple gpus when using model output.

<img width="1397" alt="Screen Shot 2022-07-27 at 15 51 37" src="https://user-images.githubusercontent.com/12815760/181194206-1483d4ce-39db-4f20-9355-a46844f6e39c.png">

<img width="681" alt="Screen Shot 2022-07-27 at 15 52 01" src="https://user-images.githubusercontent.com/12815760/181194264-893ceab2-c63e-4fa7-87c0-a9cf5b530782.png">

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

please refer to the above info form.

### Expected behavior

Multiple gpus can be used when using transformers Model Output api.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

As an aside, we recommend looking into the [accelerate](https://github.com/huggingface/accelerate) package for multi-GPU usage.

Thanks!

**Comment by zyddora** [comment]
Cannot loggin to hugging face, so just to pose the issue here.
