### ISSUE TITLE
tensorflow-aarch64 is not a viable candidate tensorflow version

### ISSUE THREAD

**Issue by ankrgyl** [huggingface/transformers#18323]
### System Info

On ARM64 machines, the official tensorflow package is named `tensorflow-aarch64`. On transformers==4.20.1, in `utils/import_utils.py`, there is a list of `candidates` for tensorflow packages which does not include this package. As a result, you cannot use TF+transformers on arm64 machines that have installed tensorflow via this package.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

On an ARM64 machine `pip install tensorflow-aarch64 transformers` and then try using a tensorflow transformer.

### Expected behavior

If you've installed `tensorflow-aarch64` you should be able to use tensorflow with transformers.

**Comment by LysandreJik** [comment]
Hey @ankrgyl, would you like to open a PR to enable that candidate?

**Comment by ankrgyl** [comment]
Happy to! I am a bit rusty on the PR process but here it is: https://github.com/huggingface/transformers/pull/18345

**Comment by LysandreJik** [comment]
Closed in https://github.com/huggingface/transformers/pull/18345

Thanks for your contribution!
