### ISSUE TITLE
T5 Tokenizer misses a space

### ISSUE THREAD

**Issue by ari9dam** [huggingface/transformers#18329]
### System Info

```
tokenizer = AutoTokenizer.from_pretrained("t5-3b", use_fast=False)#metrics_util.tokenizer
tokenizer.decode(tokenizer("Intel unveils Project Alloy 'merged reality' headset")["input_ids"], skip_special_tokens=True)

Output: Intel unveils Project Alloy'merged reality' headset 
```
Note that the space between Alloy and 'merged reality' is missing.

System
---------------------
transformers == 4.21.0
python == 3.7.11
Ubuntu 18.04.6 LTS

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("t5-3b", use_fast=False)#metrics_util.tokenizer
print(tokenizer.decode(tokenizer("Intel unveils Project Alloy 'merged reality' headset")["input_ids"], skip_special_tokens=True))

### Expected behavior

Intel unveils Project Alloy 'merged reality' headset

**Comment by banda-larga** [comment]
One workaround is adding `clean_up_tokenization_spaces=False` in tokenizer.decode
