### ISSUE TITLE
Model parallelism support?

### ISSUE THREAD

**Issue by orenmelamud** [huggingface/transformers#1836]
Hi. I'm running into memory issues when trying to fine tune the CTRL language model on a 16 GB GPU. Is there any built-in support for splitting models across more than one GPU? I suppose that mapping the input embedding layer to a different GPU or even the CPU would do the trick.

**Comment by iedmrc** [comment]
How do you training CTRL ? Did you check this: https://github.com/huggingface/transformers/blob/0477b307c7501ea76e01b03cb387a2312db752b3/examples/run_lm_finetuning.py#L198

You can also decrease batch size up to 1.

And also gradients can be accumulated:
https://github.com/huggingface/transformers/blob/0477b307c7501ea76e01b03cb387a2312db752b3/examples/run_lm_finetuning.py#L389

**Comment by orenmelamud** [comment]
@iedmrc Thanks for the suggestions. I'm using a slightly modified version of run_lm_finetuning.py but for CTRL even with a batch size of 1 the fine tuning consumes more than 16 GB of memory. I tried also to fine tune with half precision (fp16), but for some reason that didn't help either (I have seen other people complain about similar issues here).

**Comment by patrickvonplaten** [comment]
See https://github.com/huggingface/transformers/pull/3578.
