### ISSUE TITLE
How can I use DDP mode without `torch.distributed.launch` command when I use transformers.Trainer

### ISSUE THREAD

**Issue by EeyoreLee** [huggingface/transformers#18360]
I checked the historical issues and readed a part of source code. But I didn't find the way out to use DDP without `torch.distributed.launch`. Is there a way to use deepspeed or ddp without modifying the command? Like a field named `strategy: str` to select the way weather I use DDP.

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
No, you need to launch your Python script with the torch/DeepSpeed launcher.

**Comment by EeyoreLee** [comment]
> 

Thank you. I got it.
