### ISSUE TITLE
Implement pytorch model with BetterTransformer in pytorch1.12?

### ISSUE THREAD

**Issue by luoling1993** [huggingface/transformers#18374]
### Feature request

BetterTransformer is a fastpath for the PyTorch Transformer API. The fastpath is a native, specialized implementation of key Transformer functions for CPU and GPU that applies to common Transformer use cases.

### Motivation

Faster.

### Your contribution

Pytorch official blog: https://pytorch.org/blog/a-better-transformer-for-fast-transformer-encoder-inference/

**Comment by LysandreJik** [comment]
Hey @luoling1993, we're currently in talks with PyTorch to see how to best approach this. cc @erichan1

**Comment by erichan1** [comment]
Hey there @luoling1993! I'm from the PyTorch team - we are working on this. My working PR https://github.com/erichan1/transformers/pull/2

**Comment by younesbelkada** [comment]
This has been implemented now. Please check: https://medium.com/pytorch/bettertransformer-out-of-the-box-performance-for-huggingface-transformers-3fbe27d50ab2
