### ISSUE TITLE
NLLB-200 is too slow

### ISSUE THREAD

**Issue by Yakovtam** [huggingface/transformers#18378]
### Feature request

When I use modle 'facebook/nllb-200-distilled-600M' to translate , it consuming 0.5 second. And it look like not async。
I want make it consuming 0.1 second ，and make it async。 Is there anyone who can help me 。Thanks!

### Motivation

When I use modle 'facebook/nllb-200-distilled-600M' to translate , it consuming 0.5 second. And it look like not async。
I want make it consuming 0.1 second ，and make it async。 Is there anyone who can help me 。Thanks!

### Your contribution

When I use modle 'facebook/nllb-200-distilled-600M' to translate , it consuming 0.5 second. And it look like not async。
I want make it consuming 0.1 second ，and make it async。 Is there anyone who can help me 。Thanks!

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
