### ISSUE TITLE
Getting Torchvision Transforms of `feature_extractor`s

### ISSUE THREAD

**Issue by sachinruk** [huggingface/transformers#18377]
### Feature request

Currently if I was to add any transforms in my training pipeline, it's not quite obvious how to do so. My usual process is to read through the source code and hope to find what I'm after.

What I'm after is something like in `timm` where you can do
```
config = resolve_data_config({}, model=model)
transform = create_transform(**config)
```
In the above I can append any torchvision transforms at will by inspecting transforms.

While I'm here it seems to be that the mean and standard deviations are 0.5 each for `VitFeatureExtractor` and same with Beit. Was this intentional as it might be incorrect if trained using imagenet data.

### Motivation

See above.

### Your contribution

Happy to contribute, but not sure where and how to start on unifying `FeatureExtractor` classes to return `torchvision.transforms`.

**Comment by LysandreJik** [comment]
cc @amyeroberts

**Comment by amyeroberts** [comment]
Thanks for adding this request @sachinruk :) 

Regarding the the mean and standard deviation values, can you raise a separate issue? 

We're currently going through an update of the feature extractor class for images. At the moment, it's not possible to compose the individual transformations we apply, like `create_transform` does. It's something we were thinking about doing down the road and it's great to hear there's support for it! 

To control what is and isn't applied by a `FeatureExtractor` you can toggle flags like e.g. `do_normalize` on the call. Note: there are some known bugs with this logic we're looking to address soon (see: [#15055](https://github.com/huggingface/transformers/issues/15055))

If you want to add transformations that aren't already applied by the `FeatureExtractor`, or work completely within `torchvision.transforms` there's a great example of a custom pipeline in our [example notebooks here](https://github.com/huggingface/notebooks/blob/main/examples/image_classification.ipynb).
