### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by qiuxia-alone** [huggingface/transformers#18386]
### System Info

macos
pycharm
python                            3.7
transformers                  4.20.1
torch                               1.12.0
torch-scatter.                 2.0.9
tensorflow                      2.3.0

### Who can help?

@NielsRogge

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

when i run `from transformers import TapasForQuestionAnswering`, then i meet error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### Expected behavior

expect nothing happened

**Comment by LysandreJik** [comment]
It's likely that you have a mismatch between your torch and torch-scatter installs. Can you import torch-scatter on its own without the SIGSEGV?

**Comment by qiuxia-alone** [comment]
> It's likely that you have a mismatch between your torch and torch-scatter installs. Can you import torch-scatter on its own without the SIGSEGV?

hi, i have installed the right version of torch-scatter(2.0.9) as showed in [https://pytorch-geometric.com/whl/](url)

**Comment by qiuxia-alone** [comment]
sorry, i get the wrong version of torch, the problem solved, thank you for your apply.

**Comment by LysandreJik** [comment]
Great, happy you could solve the problem!

**Comment by CharlesDDDD** [comment]
Having faced the same issues and also fixed it by updating the version of pytorch
