### ISSUE TITLE
BPE error when fine-tuning a CTRL model

### ISSUE THREAD

**Issue by orenmelamud** [huggingface/transformers#1841]
Hi,

cc @keskarnitish

I'm using a slightly modified version of the exapmles/run_lm_finetuning.py code to fine-tune a CTRL model and getting this BPE warning: 

```
WARNING - transformers.tokenization_ctrl -   Saving vocabulary to /home/ubuntu/data/ctrl/pytrained4/merges.txt: BPE merge indices are not consecutive. Please check that the tokenizer is not corrupted!
```

Is this something I should be concerned about?

**Comment by keskarnitish** [comment]
Can you post the code for the `run_lm_finetuning`? I am not as familiar with what this error message might entail.

**Comment by orenmelamud** [comment]
Sure. Here it is.

[run_ctrl_finetuning.py.zip](https://github.com/huggingface/transformers/files/3852748/run_ctrl_finetuning.py.zip)
