### ISSUE TITLE
Tranformers documentation translation to Japanese 🇯🇵

### ISSUE THREAD

**Issue by omarespejel** [huggingface/transformers#18413]
Hi!

Let's bring the documentation to all the Japanese-speaking community :)

Who would want to translate? Please follow the 🤗 [TRANSLATING guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md). Here is a list of the files ready for translation. Let us know in this issue if you'd like to translate any, and we'll add your name to the list.

Some notes:

- Please translate using an informal tone (imagine you are talking with a friend about transformers 🤗).
- Please translate in a gender-neutral way.
- Add your translations to the folder called `ja` inside the [source folder](https://github.com/huggingface/transformers/tree/main/docs/source).
- Register your translation in `ja/_toctree.yml`; please follow the order of the [English version](https://github.com/huggingface/transformers/blob/main/docs/source/en/_toctree.yml).
- Once you're finished, open a pull request and tag this issue by including #issue-number in the description, where issue-number is the number of this issue. Please ping @omarespejel and @sgugger for review.
- 🙋 If you'd like others to help you with the translation, you can also post in the 🤗 [forums](https://discuss.huggingface.co/).

## Get Started section
- [x] [index.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/index.mdx) | https://github.com/huggingface/transformers/pull/21186
- [ ] [quicktour.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/quicktour.mdx).
- [x] [installation.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/installation.mdx) | https://github.com/huggingface/transformers/pull/21241

## Tutorial section
- [ ] [pipeline_tutorial.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/pipeline_tutorial.mdx) 
- [ ] [autoclass_tutorial.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/autoclass_tutorial.mdx) 
- [ ] [preprocessing.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/preprocessing.mdx) 
- [ ] [training.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/training.mdx) 
- [ ] [accelerate.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/accelerate.mdx) 
- [ ] [model_sharing.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_sharing.mdx) 
- [x] [multilingual.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/multilingual.mdx) | https://github.com/huggingface/transformers/pull/21084

**Comment by LysandreJik** [comment]
cc @younesbelkada as we talked about that last week

**Comment by younesbelkada** [comment]
That's great 🔥 !
Linking this issue to the one on HF course: https://github.com/huggingface/course/issues/114

**Comment by kambehmw** [comment]
Hi, I would like to translate the 3 mdx files in the Get Started section. (index.mdx, quicktour.mdx, installation.mdx)
If there is no person in charge yet.

**Comment by younesbelkada** [comment]
Thanks @kambehmw for your interest in this!
Sure, feel free to start working on it as no one is in charge of that yet!

**Comment by younesbelkada** [comment]
Thank you very much, looking forward to it!!

**Comment by shogohida** [comment]
Hi @younesbelkada! Still working on [this PR request](https://github.com/huggingface/optimum/pull/542) but I would like to work on this issue too because I'm Japanese 🇯🇵 

Can I work on [multilingual.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/multilingual.mdx)?

By the way, the link for [autoclass_tutorial.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/autoclass_tutorial.mdx) is broken. I think [this](https://github.com/huggingface/transformers/blob/main/docs/source/en/autoclass_tutorial.mdx) is the correct one 🙏

**Comment by rustinwelter** [comment]
I would like to work on this as well if it is OK.

**Comment by younesbelkada** [comment]
Sure yes @rustinwelter , that would be great,
let us know what topic would you like to pick up for translation!

**Comment by rustinwelter** [comment]
Thank you @younesbelkada! Let me just try accelerate.mdx as I'm a still a bit nervous. But if it goes well and I'm feeling comfortable with it, will you let me do others as well?

**Comment by younesbelkada** [comment]
Of course yes! Don't worry all will go very well 💪 And looking forward to your contributions!

**Comment by rustinwelter** [comment]
Thank you! I have sent my pull request! :)

**Comment by younesbelkada** [comment]
Awesome! Thanks a lot for your contribution!

**Comment by osanseviero** [comment]
Hey all! As some people were interested in a place to discuss about translations, we opened a category in the [HF Discord server](http://hf.co/join/discord) with a category for internationalization and translation efforts, including a Japanese channel!
