### ISSUE TITLE
Increase notebooks page visibility

### ISSUE THREAD

**Issue by alaradirik** [huggingface/transformers#18430]
Hi, I was looking at the [notebooks page](https://huggingface.co/docs/transformers/notebooks) and I noticed that the community notebooks link is broken and some of the official notebooks are outdated and throw errors when run. 

It would be great to reorganize the notebooks page such that:
1) The [community page ](https://huggingface.co/docs/transformers/v4.21.0/en/community) is renamed as Community Notebooks or merged with the Notebooks page
2) We add tags or organize the community notebooks page by task and topic (fine-tuning, image classification, etc.)
3) Existing official notebooks are updated
4) Notebooks page/s are promoted on the homepage

@NielsRogge @sgugger @amyeroberts @LysandreJik could you comment on this?

**Comment by sgugger** [comment]
I wouldn't merge the community notebooks page with the notebooks page, just make the link work again. I think it's important to separate what we officially support from what we don't. Organizing things a bit better would certainly be welcome, as always, happy to look at a PR!

Same for fixing some of the notebooks if they don't run anymore. They are not tested like the examples scripts so it's possible that some API changes broke them.

**Comment by alaradirik** [comment]
Makes sense, I will reorganize the Community page and double check the official notebooks then!
