### ISSUE TITLE
Add zero-shot object detection pipeline

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#18445]
### Feature request

We currently have [OWL-ViT](https://huggingface.co/docs/transformers/main/model_doc/owlvit) in the library, which is capable of performing zero-shot object detection.

It would be great to have a pipeline for this task, with the following API:

```
from transformers import pipeline

pipe = pipeline("zero-shot-object-detection")
pipe("cats.png", ["cat", "remote"])
```

This pipeline could default to the https://huggingface.co/google/owlvit-base-patch32 checkpoint. Also check out the [demo notebook](https://github.com/huggingface/notebooks/blob/main/examples/zeroshot_object_detection_with_owlvit.ipynb) that showcases the model.

This can be implemented similar to [other pipelines](https://github.com/huggingface/transformers/tree/main/src/transformers/pipelines) (we already have one for zero-shot image classificaiton with CLIP, so it would be very similar to that one). For an example PR that added a pipeline, see https://github.com/huggingface/transformers/pull/11598.

### Motivation

Pipelines are great for abstracting away all the complexity for quick inference with a model.

### Your contribution

I can assist with this, together with @Narsil.

**Comment by LysandreJik** [comment]
As seen with @alaradirik this morning, this could also be leveraging the custom pipeline feature that was implemented last week, especially if this pipeline works with a very limited number of artchitectures.

cf https://github.com/huggingface/transformers/pull/18079

**Comment by NielsRogge** [comment]
cc @alaradirik

**Comment by MocktaiLEngineer** [comment]
Can I take this up and work on it?

**Comment by alaradirik** [comment]
Hi @MocktaiLEngineer! Of course, you can also @NielsRogge, @Narsil or me if you need any help or have any questions.

**Comment by LysandreJik** [comment]
cc @sgugger as we chatted about it as well

**Comment by sgugger** [comment]
I was going to do a custom pipeline on this today actually, as the dev advocates want more examples of it :-)

**Comment by sahamrit** [comment]
Hi @NielsRogge , if no one is working on it, can i take this up?

**Comment by alaradirik** [comment]
Hi @sahamrit, I don't think anyone is working on this right now but I'd need to double check with @NielsRogge and @sgugger

**Comment by Narsil** [comment]
Yes you can take a stab at it. Pinging @OlivierDehaene that might be able to provide guidance too.
