### ISSUE TITLE
Add depth estimation pipeline

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#18446]
### Feature request

We currently have 2 monocular depth estimation models in the library, namely [DPT](https://huggingface.co/docs/transformers/model_doc/dpt) and [GLPN](https://huggingface.co/docs/transformers/model_doc/glpn).

It would be great to have a pipeline for this task, with the following API:

```
from transformers import pipeline

pipe = pipeline("depth-estimation")
pipe("cats.png")
```

This pipeline could default to the https://huggingface.co/Intel/dpt-large checkpoint. Also check out the [Space](https://huggingface.co/spaces/nielsr/dpt-depth-estimation) that showcases the model.

This can be implemented similar to [other pipelines](https://github.com/huggingface/transformers/tree/main/src/transformers/pipelines). For an example PR that added a pipeline, see https://github.com/huggingface/transformers/pull/11598.

### Motivation

Pipelines are a great way to quickly perform inference with a model for a given task, abstracting away all the complexity.

### Your contribution

I can assist with this, together with @Narsil.

**Comment by Narsil** [comment]
What would be the output like @NielsRogge  ?

My understanding is that depth is just a gray scale image (black = infinitely far, white = infinitely close).


If that's the case It seems really close to `image-segmentation` in the sense that it's generating a new image from the original image, so we should try and reuse as much as possible.

Also maybe we could have something like `image-generation` to try and keep the name generic ? (And have an alias for `depth-estimation` for instance ?)

**Comment by nandwalritik** [comment]
Hi @NielsRogge I would like to add this pipeline.

**Comment by NielsRogge** [comment]
Hi @Narsil,

I'm not sure whether we should add this to the existing image-segmentation pipeline. Depth estimation is basically pixel regression, rather than pixel classification (the latter is image segmentation). It would be quite confusing to add it there.

Depth estimation is quite a different field, see e.g. https://paperswithcode.com/task/depth-estimation

**Comment by nandwalritik** [comment]
Thanks I will start working on it.

**Comment by Narsil** [comment]
> I'm not sure whether we should add this to the existing image-segmentation pipeline.
I said we should inspire from it, not reuse it, but I suggested using an `image-generation`one.

The output is a grayscale image, right ?
