### ISSUE TITLE
CUDA runtime error (59) : device-side assert triggered 

### ISSUE THREAD

**Issue by iedmrc** [huggingface/transformers#1848]
Hi,
When you run `run_lm_finetuning.py` with a custom tokenizer via `--tokenizer_name tokenizer` parameter, you need to resize model embedding according to the new tokenizer. Otherwise you are going to get `CUDA runtime error (59) : device-side assert triggered` or `Assertion 'srcIndex < srcSelectDimSize' failed`.

I fixed this issue and going to create a PR if it's okay?
Thanks!

**Comment by LysandreJik** [comment]
Indeed, this seems to be a problem. Thanks for the PR!

**Comment by iedmrc** [comment]
fixed at #1849
