### ISSUE TITLE
https://github.com/huggingface/transformers/blob/f0d496828d3da3bf1e3c8fbed394d7847e839fa6/src/transformers/models/funnel/modeling_funnel.py#L1004

### ISSUE THREAD

**Issue by Tharolzakariya** [huggingface/transformers#18507]
https://github.com/huggingface/transformers/blob/f0d496828d3da3bf1e3c8fbed394d7847e839fa6/src/transformers/models/funnel/modeling_funnel.py#L1004

**Comment by gante** [comment]
This does not look like an issue :) Closing 

Feel free to reopen with the actual question.
