### ISSUE TITLE
Small typo in docs/README.md

### ISSUE THREAD

**Issue by ankrgyl** [huggingface/transformers#18508]
### System Info

Working on main (commit 9129fd0377e4d46cb2d0ea28dc1eb91a15f65b77).

The suggested command:

```
doc-builder build transformers docs/source/ --build_dir ~/tmp/test-build
```

fails with:

```
FileNotFoundError: [Errno 2] No such file or directory: 'docs/source/_toctree.yml'
```

I think is because you have to specify a language (e.g. `en`) while building the docs, e.g.

```
doc-builder build transformers docs/source/en/ --build_dir ~/tmp/test-build
```

I'm happy to contribute a fix.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the following command:

```
doc-builder build transformers docs/source/ --build_dir ~/tmp/test-build
```

### Expected behavior

The command should _not_ error, and instead should generate the expected MDX files.

**Comment by LysandreJik** [comment]
Hey @ankrgyl! It seems that is correct! Would you like to open a PR to fix the problem? Happy to guide you through it if you need pointers; please ping @sgugger and myself on the PR. Thanks!

**Comment by NinedayWang** [comment]
Hi, `CONTRIBUTING.md` also requires a language such as "en" to be specified in the doc-builder. @ankrgyl @LysandreJik

**Comment by NinedayWang** [comment]
> CONTRIBUTING.md

This typo has been fixed, sorry I missed the latest version of `CONTRIBUTING.md`.

**Comment by NinedayWang** [comment]
> Hi, `CONTRIBUTING.md` also requires a language such as "en" to be specified in the doc-builder. @ankrgyl @LysandreJik

This typo has been fixed, sorry I missed the latest version of CONTRIBUTING.md.
