### ISSUE TITLE
How to use run_glue.py with tensorboard?

### ISSUE THREAD

**Issue by Daromog** [huggingface/transformers#18509]
### System Info

I'm writting a folder path in --logging_dir but nothing is written there .
I've tried with 

--logging_dir foldername
--logging_dir pathtofolder

But nothing works

@LysandreJik 
@sgugger

### Who can help?

@sgugger
@LysandreJik 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

    --logging_dir foldername
    --logging_dir pathtofolder

    --logging_strategy steps \
    --logging_first_step True \
    --logging_steps 5 \

### Expected behavior

Nothing is saved in the folder

**Comment by nbroad1881** [comment]
Try using `--report_to tensorboard`
