### ISSUE TITLE
[New Model] LiLT: A Simple yet Effective Language-Independent Layout Transformer for Structured Document Understanding

### ISSUE THREAD

**Issue by WaterKnight1998** [huggingface/transformers#18528]
### Model description

Structured document understanding has attracted considerable attention and made significant progress recently, owing to its crucial role in intelligent document processing. However, most existing related models can only deal with the document data of specific language(s) (typically English) included in the pre-training collection, which is extremely limited. To address this issue, we propose a simple yet effective Language-independent Layout Transformer (LiLT) for structured document understanding. LiLT can be pre-trained on the structured documents of a single language and then directly fine-tuned on other languages with the corresponding off-the-shelf monolingual/multilingual pre-trained textual models. Experimental results on eight languages have shown that LiLT can achieve competitive or even superior performance on diverse widely-used downstream benchmarks, which enables language-independent benefit from the pre-training of document layout structure. Code and model are publicly available at [this https URL](https://github.com/jpWang/LiLT).

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Code @jpWang  : https://github.com/jpWang/LiLT

Weights (Author @ManuelFay ): 
- https://huggingface.co/manu/lilt-camembert-dit-base-hf
- https://huggingface.co/manu/lilt-camembert-base
- https://huggingface.co/manu/lilt-camembert-dit-base
- https://huggingface.co/manu/lilt-infoxlm-base

**Comment by jpWang** [comment]
Hi,
thanks for your great effort. Contact me if any problem encountered :)

**Comment by NielsRogge** [comment]
Closing as it has been added in #19450
