### ISSUE TITLE
AutoModel(s) do not respect the `revision` flag while loading custom models

### ISSUE THREAD

**Issue by ankrgyl** [huggingface/transformers#18537]
### System Info

- `transformers` version: 4.21.1
- Platform: macOS-12.4-arm64-arm-64bit
- Python version: 3.10.5
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): 1.12.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?:no

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python

from transformers import AutoModelForImageClassification
m = AutoModelForImageClassification.from_pretrained(
        "sgugger/custom-resnet50d",
        trust_remote_code=True,
        revision="ed94a7c6247d8aedce4647f00f20de6875b5b292"
)
# It will print:
# Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
```

I stepped through the code and observed that `AutoConfig.from_pretrained` [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/auto/auto_factory.py#L423) swallows the `revision` from `kwargs`, meaning that later on line [433](https://github.com/huggingface/transformers/blob/main/src/transformers/models/auto/auto_factory.py#L433) it's no longer there. I believe the same issue applies to `use_auth_token`.

### Expected behavior

I think the revision should propagate to both the configuration and model.

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
Thanks for flagging! The PR linked above should solve this.

**Comment by ankrgyl** [comment]
Appreciate the quick turnaround :)
