### ISSUE TITLE
[New Model] Donut: Document Understanding Transformer

### ISSUE THREAD

**Issue by WaterKnight1998** [huggingface/transformers#18530]
### Model description

Donut doughnut, Document understanding transformer, is a new method of document understanding that utilizes an OCR-free end-to-end Transformer model. Donut does not require off-the-shelf OCR engines/APIs, yet it shows state-of-the-art performances on various visual document understanding tasks, such as visual document classification or information extraction (a.k.a. document parsing). In addition, we present SynthDoG dog, Synthetic Document Generator, that helps the model pre-training to be flexible on vairous languages and domains.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Code @clovaai : https://github.com/clovaai/donut

Weights: 
- https://huggingface.co/naver-clova-ix/donut-base
- https://huggingface.co/naver-clova-ix/donut-base-finetuned-cord-v1-2560
- https://huggingface.co/naver-clova-ix/donut-base-finetuned-zhtrainticket
- https://huggingface.co/naver-clova-ix/donut-base-finetuned-rvlcdip
- https://huggingface.co/naver-clova-ix/donut-base-finetuned-cord-v1
- https://huggingface.co/naver-clova-ix/donut-base-finetuned-docvqa
- https://huggingface.co/naver-clova-ix/donut-base-finetuned-cord-v2

**Comment by NielsRogge** [comment]
See #18488

**Comment by WaterKnight1998** [comment]
Cool to see you working there, thank you very much =D
