### ISSUE TITLE
Typo in configuration

### ISSUE THREAD

**Issue by ariG23498** [huggingface/transformers#18543]
Hey @NielsRogge 

I found an inconsistency in the documentation and the code for configuration of GroupViT. The default for `num_output_groups` is `[64, 8, 8]` (notice the last element in the list), while that documented is `[64, 8, 0]`. It would be great if we could make the two consistent.

https://github.com/huggingface/transformers/blob/8cb5ecd912e09301be126c6ce6e9a22ca7153da4/src/transformers/models/groupvit/configuration_groupvit.py#L158

https://github.com/huggingface/transformers/blob/8cb5ecd912e09301be126c6ce6e9a22ca7153da4/src/transformers/models/groupvit/configuration_groupvit.py#L204

**Comment by NielsRogge** [comment]
Hi,

thanks for spotting, feel free to fix it in #18020

**Comment by ariG23498** [comment]
Will do!
