### ISSUE TITLE
Illegal instruction: 4 error when importing TextClassificationPipeline

### ISSUE THREAD

**Issue by ehsong** [huggingface/transformers#18554]
### System Info

```
Name: transformers
Version: 4.22.0.dev0

Name: tensorflow
Version: 2.5.0

Name: torch
Version: 1.12.1

Python 3.9.12
```

I keep getting the error 'Illegal instruction: 4 ' when trying to import TextClassificationPipeline from transformers, does this have anything to do with the versions of the dependencies? 

It is quite confusing which versions of the packages are compatible with TextClassificationPipeline, I had the same error when with tensorflow version 2.9

### Who can help?

@Narsil

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

-

### Expected behavior

-

**Comment by Narsil** [comment]
hi @ehsong ,

Are you on Mac M1 ? Do you mind running `transformers-cli env` and printing the output here ?

What code are you using the trigger the issue ?

I googled and found this : https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10
I can't tell you exactly what's the issue, but it seems to be the environment you're running in that's causing this.
