### ISSUE TITLE
Segformer ouput size

### ISSUE THREAD

**Issue by joihn** [huggingface/transformers#18557]
### System Info

thanks for this repo,

Segformer `output size` is `input_size/4,` as mentionned here
https://github.com/huggingface/transformers/blob/main/src/transformers/models/segformer/modeling_tf_segformer.py#L780

However, this line of documentation is wrong:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/segformer/modeling_tf_segformer.py#L850

By the way, what would be the easiest way to augment the ouput size, adding upsampling layers at the end ? 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

read the code :) there is an inconsitency in the doc :)

### Expected behavior

the doc. should be consistent

**Comment by NielsRogge** [comment]
Hi,

Yes it should be `(batch_size, num_labels, height/4, width/4)`.

**Comment by joihn** [comment]
PR merged
