### ISSUE TITLE
`transformers.convert_graph_to_onnx.quantize` fails in unit tests

### ISSUE THREAD

**Issue by rachthree** [huggingface/transformers#18614]
### System Info

- `transformers` version: 4.22.0.dev0
- Platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
  * Used `tensorflow/tensorflow:latest` Docker image for this environment, then used `pip install -e '.[dev,onnx]'`
- Python version: 3.8.10
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Tensorflow version (GPU?): 2.9.1 (True)
- Flax version (CPU?/GPU?/TPU?): 0.5.3 (cpu)
- Jax version: 0.3.6
- JaxLib version: 0.3.5
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

Other:
- `onnxruntime` version: 1.12.1

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run `RUN_SLOW=true pytest tests/onnx/test_onnx.py`

Get failures:
```
FAILED tests/onnx/test_onnx.py::OnnxExportTestCase::test_quantize_pytorch - TypeError: 'module' object is not callable
FAILED tests/onnx/test_onnx.py::OnnxExportTestCase::test_quantize_tf - TypeError: 'module' object is not callable
```

### Expected behavior

The unit tests should pass.

I believe this failure is due to `onnxruntime.quantization.quantize` which is a module that contains functions `quantize_static` and `quantize_dynamic`. The API may have changed since the unit test was written. I'm not sure which is the one to use for the unit tests. Even after fixing, not sure how `transformers` should handle the different versions of `onnxruntime` or should the required version change in `setup.py`.

See https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/quantization/quantize.py

**Comment by LysandreJik** [comment]
cc @lewtun

**Comment by severinsimmler** [comment]
I have fixed this in https://github.com/huggingface/transformers/pull/18336, but still waiting for a review.

**Comment by rachthree** [comment]
Looks like this has been fixed! Closing this.
