### ISSUE TITLE
Big Bird cannot be converted to ONNX

### ISSUE THREAD

**Issue by cigrainger** [huggingface/transformers#18620]
### System Info

- `transformers` version: 4.22.0.dev0
- Platform: Linux-5.17.5-x86_64-with-glibc2.33
- Python version: 3.9.6
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): 1.12.0+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@ydshie

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```bash
python -m transformers.onnx --model=google/bigbird-roberta-base bigbird
```

Returns:
```bash
ValueError: Outputs values doesn't match between reference model and ONNX exported model: Got max absolute difference of: 6.103515625e-05
```

### Expected behavior

I expect the export to work and return: `All good, model saved at: bigbird/model.onnx`.

**Comment by LysandreJik** [comment]
cc @vumichien, have you encountered this when contributing the BigBird ONNX exporter?

**Comment by vumichien** [comment]
@LysandreJik I didn't encounter this problem when contributing the BigBird ONNX exporter. I do check again by running `RUN_SLOW=1 pytest tests/onnx/test_onnx_v2.py -k "bigbird"` , and all the tests are still passed.

**Comment by LysandreJik** [comment]
Maybe we could put a higher tolerance in that case. WDYT @lewtun ?

**Comment by lewtun** [comment]
Hey @cigrainger I'm not able to reproduce this behaviour using either CPU or GPU. Could you please try running this again with the latest state of the `main` branch in `transformers` and report back if the issue persists?

If yes, we can certainly increase the tolerance as Lysandre suggested :)
