### ISSUE TITLE
_tf_available for customized built tensorflow

### ISSUE THREAD

**Issue by kevint324** [huggingface/transformers#18642]
### System Info

n/a

### Who can help?

@Rocketknight1 

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
  File "virtualenv_mlu/lib/python3.8/site-packages/transformers/pipelines/base.py", line 212, in infer_framework_load_model
    raise RuntimeError(
RuntimeError: At least one of TensorFlow 2.0 or PyTorch should be installed. To install TensorFlow 2.0, read the instructions at https://www.tensorflow.org/install/ To install PyTorch, read the instructions at https://pytorch.or
```

### Expected behavior

https://github.com/huggingface/transformers/blob/02b176c4ce14340d26d42825523f406959c6c202/src/transformers/utils/import_utils.py#L63L75

I built a tensorflow-xxu for our in house accelerator and tried to run the transformer example.
I got the RuntimeError indicates tf is not available.
Currently the _tf_available has a hard-coded candidates list.
I'm not suire if extending the existing list is a good idea.
Maybe adding some runtime flexibility would be better?

Thanks
Kevin

**Comment by ydshieh** [comment]
I think it (extending the list ) is fine if you would work with a specific `transformers` version. But it would be a bit tedious if you want to use newer versions constantly.

cc @Rocketknight1 for the idea regarding `adding some runtime flexibility`.

**Comment by ydshieh** [comment]
Changed the tag to `Feature request` instead :-)

**Comment by Rocketknight1** [comment]
Hi @kevint324, I filed a PR that might resolve this, but I want to check with other maintainers that it's okay before I merge it. In the meantime, can you try it out? Just run `pip install git+https://github.com/huggingface/transformers.git@allow_force_tf_availability`, then set the environment variable `FORCE_TF_AVAILABLE=1` before running your code, and it should skip those checks now.

**Comment by kevint324** [comment]
Yes, it works.
Thanks for the quick fix.
