### ISSUE TITLE
tensorflow2.0 does not has mean, but reduce mean

### ISSUE THREAD

**Issue by andompesta** [huggingface/transformers#1864]
## 🐛 Bug
tensorflow2.0 does not has a mean function but only a reduce_mean().
```
output = tf.mean(hidden_states, axis=1)
```
should be:
```
output = tf.reduce_mean(hidden_states, axis=1)
```

Model I am using: TFXLMForSequenceClassification with summary_type == 'mean'

Language I am using the model on (English, Chinese....): any

The problem arise when using:
when loading the model, due to the lazy initialisation of tf2.0 you have to run the model with dummy input.
```
TFXLMForSequenceClassification.from_pretrained(os.path.join(args.model_path, "xlm-mlm-17-1280-tf_model.h5"), config=config)
```

The tasks I am working on is:
* [ x] my own task or dataset: I want to finetune the model on a custom english dataset and transfer it to multiple language

## To Reproduce

1. load config file and add summary info
```
config = XLMConfig.from_pretrained(os.path.join(args.data_path, "xlm-mlm-17-1280-config.json"))
config.summary_use_proj = True
config.summary_type = 'mean'
config.summary_proj_to_labels = True
config.num_labels = len(LABELS)
config.summary_activation = "tanh"
```
2. load the model
```
model = TFXLMForSequenceClassification.from_pretrained(os.path.join(args.model_path, "xlm-mlm-17-1280-tf_model.h5"), config=config)
```

## Expected behavior

You should see an error stating that tf2.0 does not has a mean function.
File "transformers/modeling_tf_utils.py", line 442:
    ``output = tf.mean(hidden_states, axis=1)`` should be ``output = tf.reduce_mean(hidden_states, axis=1)``

```AttributeError: module 'tensorflow' has no attribute 'mean'```

## Environment

* OS: Ubuntu16.04
* Python version: 3.7.5
* Tensorflow version: 2.0
* Transformers version (or branch): 2.1.1
* Using GPU: yes
* Distributed of parallel setup : not distributed, only single GPU

**Comment by TheEdoardo93** [comment]
This bug has been reviewed and corrected in this PR #1876!
Close this issue.
