### ISSUE TITLE
`AttributeError: 'BertTokenizer' object has no attribute 'tokens_trie'

### ISSUE THREAD

**Issue by roetezadi** [huggingface/transformers#18643]
### System Info

Google colab

### Who can help?

Anyone

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi, 
I have trained a model with `transformers==4.9.1`. 
Now I want to run this saved model with the new version of transformers and I get this error: `AttributeError: 'BertTokenizer' object has no attribute 'tokens_trie'`. 
As I looked at transformers codes `token_trie` has been added which was not in the previous versions if I am correct. How can I solve this problem from my side? and is there any possibilities that this compatibility problem can be handled in the newer versions of transformers?

### Expected behavior

None

**Comment by ydshieh** [comment]
@Narsil is the one knows the best.

This is added in the PR #13220

**Comment by Narsil** [comment]
@roetezadi How did you solve this ?
