### ISSUE TITLE
No module named 'evaluate'

### ISSUE THREAD

**Issue by skye95git** [huggingface/transformers#18663]
https://github.com/huggingface/transformers/blob/c99e984657b64dd8f19de74405bbf13763ab4f2b/examples/pytorch/language-modeling/run_mlm.py#L35

When I pre-train RoBerta from scratch using the latest version `run_mlm.py`, there is an error :
```
import evaluate
ModuleNotFoundError: No module named 'evaluate'
```

**Comment by muellerzr** [comment]
Hi! You need to do `pip install evaluate`. #18666 will also add it to each of the `examples` internal `requirements.txt` file, so it will be installed when you do `pip install -r requirements.txt`

**Comment by skye95git** [comment]
> Hi! You need to do `pip install evaluate`. #18666 will also add it to each of the `examples` internal `requirements.txt` file, so it will be installed when you do `pip install -r requirements.txt`

Thanks! It work.
