### ISSUE TITLE
_no_load_in_8bit module list have custom ignored layers 

### ISSUE THREAD

**Issue by ArthurZucker** [huggingface/transformers#18660]
### Feature request

Could be awesome to have the property `_no_load_in_8bit = []` for the 8bit quantisation to allow custom layers to not be converted. 
CC @younesbelkada 

### Motivation

Would increase flexibility 

### Your contribution

Would be testing on `Jukebox`

**Comment by younesbelkada** [comment]
Hi @ArthurZucker 
Thanks a lot for the feature request! 
I have addressed a commit in https://github.com/huggingface/transformers/pull/18646 that should support adding an argument `no_load_in_8bit_modules` in `from_pretrained` function. Could you try it in your usecase and let me know if this helped?

**Comment by younesbelkada** [comment]
Closing as completed
