### ISSUE TITLE
Adding a documentation to save the best checkpoint during the training in summarization example project

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#18708]
### Feature request

I am working with the latest [latest summarization example](https://github.com/huggingface/transformers/tree/main/examples/pytorch/summarization). But after the training loop ends, I can't find an easy way to find what is the best checkpoint saved. 

### Motivation

I would be easy to keep a separate checkpoint for the best one.

### Your contribution

If there's already a way, please let me know, so that we can document it. Else I can contribute to this feature. I think we can use trainer_arguments.

**Comment by gante** [comment]
Hi @shamanez  👋 As per our [issues guidelines](https://github.com/huggingface/transformers/blob/main/ISSUES.md), we reserve GitHub issues for bugs in the repository and/or feature requests. For any other matters, we'd like to invite you to use our [forum](https://discuss.huggingface.co/) 🤗
