### ISSUE TITLE
add timesformer model

### ISSUE THREAD

**Issue by fcakyon** [huggingface/transformers#18724]
### Feature request

Add [TimeSformer, ICML 2021](https://arxiv.org/abs/2102.05095) model to HuggingFace transformers library.

Source code: https://github.com/facebookresearch/TimeSformer
Weight files: https://github.com/facebookresearch/TimeSformer#model-zoo
Alternative implementation: https://github.com/lucidrains/TimeSformer-pytorch

### Motivation

[TimeSformer, ICML 2021](https://arxiv.org/abs/2102.05095) is a transformer-based video understanding model from META AI, and all recent video classification/action recognition papers compare their proposal with this model.

As a Ph.D. candidate researching video transformers, I want to add TimeSformer support to my [video-transformers](https://github.com/fcakyon/video-transformers) package, but there is no easy way of doing that. It would be super easy if HuggingFace included it.

It would be an excellent addition to the `transformers` library considering it has 400+ citations and is an essential benchmark model.

### Your contribution

As a Ph.D. candidate working on video transformers, I would like to work on adding this architecture to the HuggingFace.

I want to start a PR but don't know where to start. Should I take the VideoMAE model as a reference since it has similar input/output to TimeSformer?

### Open source status
- [x] The model implementation is available
- [x] The model weights are available

**Comment by LysandreJik** [comment]
cc @NielsRogge!

**Comment by NielsRogge** [comment]
Hi,

Sure, let me know your email address, then we can set up a slack channel for easier communication.

**Comment by fcakyon** [comment]
> Hi,
> 
> Sure, let me know your email address, then we can set up a slack channel for easier communication.

I have written my mail to you by Discord message 👍
