### ISSUE TITLE
License for the pretrained DistilBert Models

### ISSUE THREAD

**Issue by official-dev** [huggingface/transformers#1872]
Hi Team,
It would be a great help if the license for the pre-trained models is mentioned in the repository.
and particularly for Distil Models.

**Comment by henrywallace** [comment]
Note that for roBERTa and all fairseq pre-trained models, there is a statement that explicitly has the license covering all their pre-trained models: https://github.com/pytorch/fairseq#license.

If applicable, it would be useful to state this in the README.

**Comment by henrywallace** [comment]
If such a license were to be created, could it applied to the newly trained distil models as well? Without a license it is questionable whether to use any of the trained models.

**Comment by guillaume-be** [comment]
I would also be interested in knowing under which license the DistilBert model weights are shared.

**Comment by julien-c** [comment]
Merging this into #3357
