### ISSUE TITLE
Cannot import ORTModelForSeq2SeqLM

### ISSUE THREAD

**Issue by lyriccoder** [huggingface/transformers#18745]
### System Info

- `transformers` version: 4.21.1
- Platform: Linux-5.4.0-109-generic-x86_64-with-glibc2.31
- Python version: 3.9.5
- Huggingface_hub version: 0.4.0
- PyTorch version (GPU? no): 1.12.1+cu102 (False)
- Tensorflow version (GPU? no): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No, only CPU. But it doesn't work even with GPU enabled
- Using distributed or parallel set-up in script?: No

@deepspeed

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. install python3.10
2. install `pip install optimum[onnxruntime]` (or `pip install optimum[deepspeed]`)
3. run any script with the foollowing import:
`from optimum.onnxruntime import ORTModelForSeq2SeqLM`
It fails with error:

```
from optimum.onnxruntime import ORTModelForSeq2SeqLM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CodeBERT/venv_3.9_onxx/lib/python3.9/site-packages/optimum/onnxruntime/__init__.py", line 62, in <module>
    from .trainer import ORTTrainer
  File "CodeBERT/venv_3.9_onxx/lib/python3.9/site-packages/optimum/onnxruntime/trainer.py", line 47, in <module>
    from transformers.deepspeed import deepspeed_init, deepspeed_reinit, is_deepspeed_zero3_enabled
ImportError: cannot import name 'deepspeed_reinit' from 'transformers.deepspeed' (CodeBERT/venv_3.9_onxx/lib/python3.9/site-packages/tr
ansformers/deepspeed.py)
```
4. Run 
```
model = ORTModelForSeq2SeqLM.from_pretrained(model_id, from_transformers=True)
```
It fails with the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ORTModelForSeq2SeqLM' is not defined
```

### Expected behavior

Import should be done correctly and it is possible to use it

**Comment by regisss** [comment]
Hi @lyriccoder! It looks like you are not using the latest release of Optimum. Could you try to upgrade it and let me know if it works?
