### ISSUE TITLE
Progress bars shown despite disable_tqdm=True in Trainer

### ISSUE THREAD

**Issue by Eichhof** [huggingface/transformers#18740]
### System Info

- `transformers` version: 4.19.2
- Platform: CentOS Linux 7.9.2009
- Python version: 3.10.4
- Huggingface_hub version: 0.2.1
- PyTorch version (GPU?): 1.12.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Yes

### Who can help?

@sgugger

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I'm running HuggingFace Trainer with `TrainingArguments(disable_tqdm=True, ...)` for fine-tuning the EleutherAI/gpt-j-6B model but there are still progress bars displayed, see screenshot.

```
    training_args = TrainingArguments(
        disable_tqdm=True,
        output_dir='./checkpoints',
        save_total_limit=10,
        logging_dir='/content/logs',
        num_train_epochs=config["N_EPOCHS"],
        evaluation_strategy='epoch'
        save_strategy='steps',
        save_steps=30,
        logging_steps=10,
        overwrite_output_dir=True,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=4,
        gradient_accumulation_steps=4,
        eval_accumulation_steps=4,
        gradient_checkpointing=True,
        max_grad_norm=0.5,
        lr_scheduler_type="cosine",
        learning_rate=1e-4,
        warmup_ratio=0.05,
        weight_decay=0.1,
        fp16_full_eval=True
        fp16=True,
        fp16_opt_level='O1',
        report_to=['tensorboard']
    )
```

![Untitled](https://user-images.githubusercontent.com/6844011/186213857-528e089b-1114-4490-a799-e2598604e1c3.png)

### Expected behavior

No progress bars displayed anymore.

**Comment by NielsRogge** [comment]
This question has been answered on the [forum](https://discuss.huggingface.co/t/progress-bars-shown-despite-disable-tqdm-true-in-trainer/22003/2?u=nielsr); therefore closing this issue.
