### ISSUE TITLE
run finetune_rag.py -- errror OSError: Not enough disk space. Needed: 139.13 GiB (download: 66.09 GiB, generated: 73.03 GiB, post-processed: Unknown size)

### ISSUE THREAD

**Issue by wangyu185** [huggingface/transformers#18751]
### System Info

faiss-cpu                     1.7.2
datasets                      2.4.0
psutil                        5.7.0
torch                         1.12.1+cu113
ray                           2.0.0
pytorch-lightning             1.7.2
transformers                  4.21.1
GitPython                     3.1.27

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

!python3 /content/drive/MyDrive/colab/rag/finetune_rag.py \
    --data_dir /content/drive/MyDrive/colab/rag/data \
    --output_dir /content/drive/MyDrive/colab/rag/output_data \
    --model_name_or_path facebook/rag-token-base \
    --model_type rag_sequence \
    --fp16 \
    --gpus 8 \
    --profile \
    --do_train \
    --do_predict \
    --n_val -1 \
    --train_batch_size 8 \
    --eval_batch_size 1 \
    --max_source_length 128 \
    --max_target_length 25 \
    --val_max_target_length 25 \
    --test_max_target_length 25 \
    --label_smoothing 0.1 \
    --dropout 0.1 \
    --attention_dropout 0.1 \
    --weight_decay 0.001 \
    --adam_epsilon 1e-08 \
    --max_grad_norm 0.1 \
    --lr_scheduler polynomial \
    --learning_rate 3e-05 \
    --num_train_epochs 100 \
    --warmup_steps 500 \
    --gradient_accumulation_steps 1

OSError: Not enough disk space. Needed: 139.13 GiB (download: 66.09 GiB, generated: 73.03 GiB, post-processed: Unknown size)

### Expected behavior

Why rag need 139Gib?

**Comment by gante** [comment]
Hi @wangyu185 👋 RAG is a retrieval-augmented model, meaning that it queries some databases. It needs to have the database in disk. Please check the [model card](https://huggingface.co/facebook/rag-token-nq) and the [documentation](https://huggingface.co/docs/transformers/model_doc/rag) for more info.

As per our [issues guidelines](https://github.com/huggingface/transformers/blob/main/ISSUES.md), we reserve GitHub issues for bugs in the repository and/or feature requests. For any other matters, we'd like to invite you to use our [forum](https://discuss.huggingface.co/) 🤗

**Comment by MALLI7622** [comment]
Hi @wangyu185 have you resolve this error?
