### ISSUE TITLE
Is this a bug? 

### ISSUE THREAD

**Issue by moh55m55** [huggingface/transformers#1878]
Hello, 
I tried to import this: 

`from transformers import AdamW, get_linear_schedule_with_warmup`
but got error : model not found
but when i did this, it worked: 
```
from transformers import AdamW
from transformers import WarmupLinearSchedule as get_linear_schedule_with_warmup
```
however when I set the scheduler like this : 
```
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=args.warmup_steps, num_training_steps=t_total) 
```
I got this error : 
```
__init__() got an unexpected keyword argument 'num_warmup_steps'
```

**Comment by moh55m55** [comment]
duplicated 
https://github.com/huggingface/transformers/issues/1837#issue-523145270

**Comment by moh55m55** [comment]
I checked the other comment but did not work. Any idea ? 
```
__init__() got an unexpected keyword argument 'num_warmup_steps'
```

**Comment by LysandreJik** [comment]
Hi, could you specify which versions of Python and Transformers is your environment running on?

**Comment by moh55m55** [comment]
Thanks
```
python: 3.6.8
Transformers: 2.1.1
```

**Comment by LysandreJik** [comment]
Did you install transformers from source or from pypi?

**Comment by moh55m55** [comment]
From pypi

--Mohammed

On Nov 20, 2019, at 10:50 AM, Lysandre Debut <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you install transformers from source or from pypi?

**Comment by LysandreJik** [comment]
Could you try installing from source and telling me if it fixes your problem?

**Comment by moh55m55** [comment]
Thanks it worked

**Comment by moh55m55** [comment]
worked with building from the source and this 
```
from transformers import AdamW,get_linear_schedule_with_warmup
```

**Comment by LysandreJik** [comment]
Great to hear!

**Comment by TLCFYBJJHYYSND** [comment]
whats the meaning of installing from source ,i am a little bit confused. could you please tell me ,thank you

**Comment by TLCFYBJJHYYSND** [comment]
> Hello,
> I tried to import this:
> 
> `from transformers import AdamW, get_linear_schedule_with_warmup`
> but got error : model not found
> but when i did this, it worked:
> 
> ```
> from transformers import AdamW
> from transformers import WarmupLinearSchedule as get_linear_schedule_with_warmup
> ```
> 
> however when I set the scheduler like this :
> 
> ```
> scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=args.warmup_steps, num_training_steps=t_total) 
> ```
> 
> I got this error :
> 
> ```
> __init__() got an unexpected keyword argument 'num_warmup_steps'
> ```

can you kindly tell me how to install from source.

**Comment by julien-c** [comment]
@TLCFYBJJHYYSND See https://github.com/huggingface/transformers#from-source

**Comment by TheEdoardo93** [comment]
In order to install Transformers library, you have to open your command line and enter:
```
pip install git+https://github.com/huggingface/transformers.git
```
> > Hello,
> > I tried to import this:
> > `from transformers import AdamW, get_linear_schedule_with_warmup`
> > but got error : model not found
> > but when i did this, it worked:
> > ```
> > from transformers import AdamW
> > from transformers import WarmupLinearSchedule as get_linear_schedule_with_warmup
> > ```
> > 
> > 
> > however when I set the scheduler like this :
> > ```
> > scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=args.warmup_steps, num_training_steps=t_total) 
> > ```
> > 
> > 
> > I got this error :
> > ```
> > __init__() got an unexpected keyword argument 'num_warmup_steps'
> > ```
> 
> can you kindly tell me how to install from source.

**Comment by TLCFYBJJHYYSND** [comment]
Thanks for that, it really works!!!
