### ISSUE TITLE
torchmetrics support

### ISSUE THREAD

**Issue by izapolsk** [huggingface/transformers#18799]
### Feature request

In eval loop the HF transformers collects and keeps in memory predictions and targets up to the end of eval and then computes metrics passed via callback.
When transformers is used to fine-tune heavy models with big datasets and many labels (in my case up to 150k), predictions and targets take huge amount of RAM. It's especially noticable with torch DDP and many GPUs per node.
It would be great to add support of metrics which are computed for every eval step and then averaged at the end of eval loop
(like [torchmetrics](https://torchmetrics.readthedocs.io/en/stable/index.html)).

### Motivation

It took some time to implement custom eval loop with turning eval data into sparse format as a first way to tackle this issue.
However, it turned out that with growing dataset and number of labels, such approach anyway sometimes led to OOM issues and turning data to dense row by row in order to compute sophisticated metrics. What in turn led to very long eval.
So, I had to re-implement custom eval loop again with torchmetrics and custom metrics.
This framework is great, I like it but I'm a little bit frustrated due to spent time.
So, it would be great to have this feature out-of-the-box.

### Your contribution

in theory I could make a PR but I'm not that familiar with HF internals.

**Comment by izapolsk** [comment]
@sgugger, could you please share your opinion on above feature request ? ^^

**Comment by sgugger** [comment]
At this stage we're not planning to add this no. You can always subclass the Trainer to put your own evaluation loop in it however.

**Comment by izapolsk** [comment]
> At this stage we're not planning to add this no. You can always subclass the Trainer to put your own evaluation loop in it however.

this is exactly what I did. I just thought that it could be useful for others because I saw some other reports in GH about OOM in eval.

**Comment by sgugger** [comment]
Note that you can use `eval_accumulation_steps` to avoid taking too much space on the GPU. There is no need to use torchmetrics for that.
