### ISSUE TITLE
ONNX test suite is slow - run in 5.5 hours

### ISSUE THREAD

**Issue by ydshieh** [huggingface/transformers#18819]
### Who can help?

@lewtun  @LysandreJik 

As shown in [this job](https://github.com/huggingface/transformers/runs/8074936385?check_suite_focus=true) run, the ONNX tests now run in 5.5 hours.

From https://github.com/huggingface/transformers/blob/73c6273d481f9052098a2a5a5f001fa75daaace9/tests/onnx/test_onnx_v2.py#L182
we see that the tests use real model checkpoints. As ONNX graph compile is known to be slow, and the models are quite big, it makes the tests very slow.

The whole scheduled CI test suite now run in 14.5 hours, and we have 2 test suites to run each day, so it requires 29 hours and can't finish in one day. This causes the test suite and their reports being delayed a lot.

We are wondering if it is possible to use tiny models from [hf-internal-testing](https://huggingface.co/hf-internal-testing) for ONNX tests.

**Comment by lewtun** [comment]
Thanks for raising this - it's an issue we've also faced with `optimum`'s test suite. Let me take a look and see if it's possible to use the tiny models as you suggest

**Comment by lewtun** [comment]
Thanks for the ping - on my TODO list this week!
