### ISSUE TITLE
Examples do not seem to work on any spaces right now (possible downtime?)

### ISSUE THREAD

**Issue by ankrgyl** [huggingface/transformers#18826]
### System Info

This is observed online on spaces:

E.g. https://huggingface.co/spaces/nielsr/donut-docvqa, if you click any of the examples, you see
![Screen Shot 2022-08-30 at 4 06 41 PM](https://user-images.githubusercontent.com/565363/187558797-d0858c72-a580-4650-8f2d-b451f294da3d.png)

Similarly, https://huggingface.co/spaces/impira/docquery produces console errors like:

```
POST https://hf.space/embed/impira/docquery/api/predict/ 500
post_data @ index.09173af6.js:7790
(anonymous) @ index.09173af6.js:7872
(anonymous) @ index.09173af6.js:6566
(anonymous) @ index.09173af6.js:506
(anonymous) @ index.09173af6.js:505
click_handler_1 @ index.d284cf1a.js:1881
click_handler_1 @ index.d284cf1a.js:1346
```

I also tried https://huggingface.co/spaces/Epoching/DocumentQA.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Visit any space with examples, and try clicking on them.

### Expected behavior

The examples should populate.

**Comment by LysandreJik** [comment]
Hey @ankrgyl! I tried using them a few seconds ago and it seems to work; is the issue still happening from your side? It may have been a transient error.

**Comment by ankrgyl** [comment]
It wasn't working until around 11:15 PM PST, at which point the website seem to have reset (see screenshot below) and ~10 minutes later, it started working.

![image](https://user-images.githubusercontent.com/565363/187689585-8ba4f00a-6606-4d04-9b7a-66f300bee25b.png)

During this period, I also noticed that deploying a gradio space with `enable_queue=False` would not work -- it seemed like something was broken with the `/predict` handler (which gets called in that case). I did some extensive testing while working with the Gradio team on https://github.com/gradio-app/gradio/issues/2132#issuecomment-1232331491.

**Comment by LysandreJik** [comment]
Understood, thank you! Should this be closed as it seems the error has been resolved?

**Comment by ankrgyl** [comment]
Yes it can definitely be closed! I mostly opened it in case it was helpful as an alert while things were behaving weirdly.

**Comment by LysandreJik** [comment]
Sounds good! Let me close it and feel free to reopen if you ever run into something similar.
