### ISSUE TITLE
Adding multiprocessing option to transformers.pipelines.automatic_speech_recognition 

### ISSUE THREAD

**Issue by mehrzadai** [huggingface/transformers#18835]
### Feature request

Hi, 
in `transformers.pipelines.automatic_speech_recognition` in case of `self.type = ctc_wit_lm`, the `postprocess` method uses `self.decoder.decode_beams(items)`. This is too slow and does decoding iterative.
`decoder.decode_beams_batch(pool,items)` is able to make things faster and pharallel.

### Motivation

`transformers.pipelines.automatic_speech_recognition` works really slow in complex `ctc_with_lm` scenarios.

### Your contribution

`None`

**Comment by LysandreJik** [comment]
WDYT @Narsil?

**Comment by Narsil** [comment]
Hi, I don't mind having a parameter for that for sure.

The biggest reason I don't think it should be the defaults is that some users might already be using different processes for different pipelines so doing parallelism twice is usually hurtful.

Also, do you mind providing small benchmarks to see the performance improvement ?
