### ISSUE TITLE
BartForSequenceClassification: Use eos_token or cls_token?

### ISSUE THREAD

**Issue by ekagra-ranjan** [huggingface/transformers#18849]
### System Info

NA

### Who can help?

@patil-suraj 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The [BartTokenizer doc](https://huggingface.co/docs/transformers/v4.21.1/en/model_doc/bart#transformers.BartTokenizer) mentions that `cls_token` is attached to the beginning of the input sentence and is used as the token for sequence classification purposes. However, in the HF code it is picking the last eos_token:
https://github.com/huggingface/transformers/blob/v4.21.1/src/transformers/models/bart/modeling_bart.py#L1514-L1521

### Expected behavior

The [Bart paper (Sec 3.1)](https://arxiv.org/pdf/1910.13461.pdf) matches with what the code does, i.e. the last token is to be used as the classification token.

```
3.1 Sequence Classification Tasks
For sequence classification tasks, the same input is fed
into the encoder and decoder, and the final hidden state
of the final decoder token is fed into new multi-class
linear classifier. This approach is related to the CLS
token in BERT; however we add the additional token
to the end so that representation for the token in the
decoder can attend to decoder states from the complete
input (Figure 3a).
```

Should I update the Bart doc with this method of classification?

**Comment by animeshkumarpaul** [comment]
Yes, I also think so. It should be fixed, otherwise it makes confusion for beginners.
