### ISSUE TITLE
GPT2 Tokenizer Special Token ID Bug

### ISSUE THREAD

**Issue by sshearing** [huggingface/transformers#1885]
## 🐛 Bug

Model I am using (Bert, XLNet....): GPT2 Tokenizer

The problem arise when using:
my own modified script: The problem arises when I try to add special tokens to the GPT2 tokenizer, specifically a pad token and a sep token.

The tasks I am working on is:
* [ ] my own task or dataset: summarization on the xsum dataset, however, the current bug does not actually affect the model, but the pre-processing.

## To Reproduce

from transformers import AutoTokenizer
encoder = AutoTokenizer.from_pretrained('gpt2')
encoder.add_special_tokens({'pad_token': '[PAD]', 'sep_token': '[SEP]'})
print(encoder.sep_token, encoder.sep_token_id)
print(encoder.pad_token, encoder.pad_token_id)
print('All special tokens:', encoder.all_special_tokens)
print('All special ids:', encoder.all_special_ids)

## Expected behavior

The expected output of this script is below:
[SEP] 50258
[PAD] 50257
All special tokens: ['<|endoftext|>', '[PAD]', '[SEP]']
All special ids: [50256, 50257, 50258]

The actual output is:
[SEP] 50258
[PAD] 50257
All special tokens: ['<|endoftext|>', '[PAD]', '[SEP]']
All special ids: [50256, 50256, 50256]

As you can see, All special IDS do not match the actual ids of the [SEP] and [PAD] token. Not sure why this is the case. Am I misunderstanding something about how add_special_tokens works?

## Environment

* OS: Ubuntu 18.04
* Python version: 3.7
* PyTorch version: 1.0.0
* PyTorch Transformers version (or branch): 2.1.0
* Using GPU ? No
* Distributed of parallel setup ? No
* Any other relevant information: None

**Comment by LysandreJik** [comment]
Hi, there have been a few fixes done on the tokenizers recently that haven't been released on Pypi yet. When I run your script with the library installed from source, I obtain: 

```py
[SEP] 50258
[PAD] 50257
All special tokens: ['[PAD]', '[SEP]', '<|endoftext|>']
All special ids: [50257, 50258, 50256]
```

Would you mind installing from source using `pip install git+https://github.com/huggingface/transformers`  and let me know if it fixes your problem,?

**Comment by sshearing** [comment]
That fixed it, thank you!
