### ISSUE TITLE
we want to submit a PR about Source-Free compression training on huggingface NLP model，Where would you suggest submitting it?

### ISSUE THREAD

**Issue by leiqing1** [huggingface/transformers#18872]
### Feature request

Hello, we have done a Source-Free compression training function, and the benefits of bert-base-cased are as follows. I want to submit a PR, is it ok?  and which repo, huggingface/transformers or huggingface/optimum, is more suitable?
![image](https://user-images.githubusercontent.com/54695910/188194251-ef204386-e1fc-40a3-9796-36a2fa5b0a56.png)
![image](https://user-images.githubusercontent.com/54695910/188194560-171f1c31-1828-4272-9cc6-df241b2fb45d.png)

### Motivation

Improve the inference speed of NLP models

### Your contribution

we want to submit a pr for huggingface～

**Comment by ydshieh** [comment]
Hey @leiqing1 ! Thanks a lot for being motivated to contribute 🤗 ! You mention this is about training, right? In this case, I would say `huggingface/transformers` is the place to go. But let's wait the opinions from my colleagues @sgugger @LysandreJik and @michaelbenayoun

As the training (for PyTorch models) is done by using the [Trainer class](https://github.com/huggingface/transformers/blob/ecdf9b06bc03af272ceb8d6951e30e677fdfd35c/src/transformers/trainer.py#L223), the PR is likely to involve the integration your compression method into that class.

**Comment by sgugger** [comment]
Let's maybe start with a simple training script that you could add as a new research project in the repo?

**Comment by ceci3** [comment]
Thanks for the reply. @ydshieh Yes, the compression process  is about training.   You mean we can prepare a simple training script to submit to https://github.com/huggingface/transformers/tree/main/examples/research_projects this directory？
@sgugger

**Comment by sgugger** [comment]
Yes, alongside with the extra modules you might need, all in the same folder.
