### ISSUE TITLE
Using GPU for gpt2-xl

### ISSUE THREAD

**Issue by samern92** [huggingface/transformers#1887]
I want to use gpt2-xl using my PC's GPU (NVIDIA GeForce GTX 1070). The usual way to do this is via conda, but it appears that the latest version of gpt-2 is not available for conda. For example, the following installation commands don't work:
```
conda install transformers
conda install git+https://github.com/huggingface/transformers
```
The latest version of transformers for conda is a[ month old,](https://anaconda.org/conda-forge/transformers) and therefore doesn't include gpt2-xl. How can I use my machine's GPU to run gpt2-xl without using conda? Will there be conda support soon?

**Comment by LysandreJik** [comment]
We have not released a new Pypi/conda version yet, but will do so in the next few days. You can install from source if you want to use GPT2-xl before that!

**Comment by iedmrc** [comment]
Via docker:
https://github.com/huggingface/transformers/blob/master/docker/Dockerfile

Via pip:
https://github.com/huggingface/transformers/blob/master/docker/Dockerfile
or 
https://github.com/huggingface/transformers/issues/1837#issuecomment-554594306
