### ISSUE TITLE
LayoutLMV3 Tokenizer Inserts Odd Characters

### ISSUE THREAD

**Issue by logan-markewich** [huggingface/transformers#18873]
### System Info

(This is on a fresh google colab instance)
- `transformers` version: 4.21.2
- Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- Huggingface_hub version: 0.9.1
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Tensorflow version (GPU?): 2.8.2 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@NielsRogge 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import LayoutLMv3TokenizerFast

tok = LayoutLMv3TokenizerFast.from_pretrained('microsoft/layoutlmv3-base')

tok.tokenize('Hello world')
>>> ['ĠHello', 'Ġworld']
```

### Expected behavior

The special characters are not expected when calling tokenize(). This doesn't happen when using the LayoutLMV2 tokenizer.

**Comment by gante** [comment]
@logan-markewich -- have a look at this [entry in our forum](https://discuss.huggingface.co/t/bpe-tokenizers-and-spaces-before-words/475/2?u=joaogante)

**Comment by logan-markewich** [comment]
@gante Yea ok, that gives some context for what is actually going on

I guess I will just need to remove those characters myself? A little annoying, but oh well

**Comment by NielsRogge** [comment]
Hi,

No that's just the way tokenization happens. The tokenization is based on the SentencePiece algorithm.

You can check out the Huggingface course if you want to learn about this: hf.co/course
