### ISSUE TITLE
While trying to train seq2seq distillation model i am getting an error message that __init__() got an unexpected keyword argument 'weights_summary'.

### ISSUE THREAD

**Issue by techthiyanes** [huggingface/transformers#18886]
### System Info

Transformer version : 4.21.2
pytorch-lightning             1.7.4
Used colab to test

Please find below colab link
https://colab.research.google.com/drive/1INGpr5nV2qnb8wKf2FAc0VqgPQWSPFdZ#scrollTo=DC8Tj2qtlfiZ

### Who can help?
@sgugger 
_No response_

### Information

- https://github.com/huggingface/transformers/blob/main/examples/research_projects/seq2seq-distillation/distillation.py

### Tasks

- XSUM dataset with seq2seq distillation

### Reproduction

Kindly try to train the below snippet.
!python /content/transformers/examples/research_projects/seq2seq-distillation/distillation.py \
  --teacher facebook/bart-large-xsum \
  --data_dir /content/transformers/examples/research_projects/seq2seq-distillation/xsum \
  --tokenizer_name facebook/bart-large-xsum \
  --student_decoder_layers 6 --student_encoder_layers 12 \
  --freeze_encoder --freeze_embeds \
  --learning_rate=3e-4 \
  --do_train \
  --do_predict \
  --fp16 --fp16_opt_level=O1 \
  --val_check_interval 0.1 --n_val 1000 --eval_beams 2 --length_penalty=0.5 \
  --max_target_length=60 --val_max_target_length=60 --test_max_target_length=100 \
  --model_name_or_path IGNORED \
  --alpha_hid=3. \
  --train_batch_size=16 --eval_batch_size=16 --gradient_accumulation_steps=2 \
  --sortish_sampler \
  --num_train_epochs=6 \
  --warmup_steps 500 \
  --output_dir distilbart_xsum_12_6 \
  --weights_summary None \
  "$@"

### Expected behavior

Is it something related to pt lightning version that i installed?

Error stacktrace:
Global seed set to 42
Traceback (most recent call last):
  File "/content/transformers/examples/research_projects/seq2seq-distillation/finetune.py", line 454, in <module>
    main(args)
  File "/content/transformers/examples/research_projects/seq2seq-distillation/finetune.py", line 429, in main
    logger=logger,
  File "/content/transformers/examples/research_projects/seq2seq-distillation/lightning_base.py", line 387, in generic_train
    **train_params,
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 2449, in from_argparse_args
    return from_argparse_args(cls, args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/argparse.py", line 72, in from_argparse_args
    return cls(**trainer_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'weights_summary'

**Comment by sgugger** [comment]
This example is not maintained anymore. It was written for an older version of PyTorch Lightning, so you probably need to downgrade to what was the last release at the time around its release (roughly 2 years ago).
