### ISSUE TITLE
Cannot Import BigBirdModel

### ISSUE THREAD

**Issue by jaideep11061982** [huggingface/transformers#18914]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 3.0.2
- Platform: Linux-5.10.133+-x86_64-with-debian-9.9
- Python version: 3.6.6
- PyTorch version (GPU?): 1.4.0 (True)
- Tensorflow version (GPU?): 2.1.0 (True)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
----> 2 from transformers import BigBirdTokenizer,BigBirdModel

ImportError: cannot import name 'BigBirdTokenizer'
```

```
----> 4 from transformers import (AlbertModel, AlbertTokenizer, BartModel, BigBirdModel, BigBirdTokenizer,
      5                           BartTokenizer, BertModel, BertTokenizer,
      6                           CamembertModel, CamembertTokenizer, CTRLModel,

ImportError: cannot import name 'BigBirdModel'
```

### Expected behavior

Model should get imported without the error

**Comment by manish-95** [comment]
I don't think transformers version 3.0.2 contains the BigBird model. I think updating your version of the transformers package should solve the issue.

**Comment by jaideep11061982** [comment]
Which version does

**Comment by manish-95** [comment]
@jaideep11061982 I believe the model was added in v4.5.0, but I think either @sgugger or @NielsRogge will be able to better comment on the exact version that you could use.

**Comment by sgugger** [comment]
Yes, it was introduced in v4.5.0.

In general, please do not open issues without updating to some recent version of Transformers, v3.0.2 is more than two years old and bugs are fixed as continuous development of the new versions, so you need to upgrade to the latest releases to see the fixes anyway.
