### ISSUE TITLE
facebook/wav2vec2-xls-r-300m-21-to-en  TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Shiro-LK** [huggingface/transformers#18916]
### System Info

transformers == 4.21.3
python == 3.9.2
ubuntu 18

### Who can help?

@patrickvonplaten @sanchit-gandhi 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. from transformers import  Speech2Text2Processor
2. processor =Speech2Text2Processor.from_pretrained("facebook/wav2vec2-xls-r-300m-21-to-en")

### Expected behavior

the processor should be loaded but got this error instead :

`TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by sanchit-gandhi** [comment]
Hey @Shiro-LK!

Good catch, we're loading a Wav2Vec2 processor here so need to instantiate the corresponding class accordingly:

```python
from transformers import Wav2Vec2Processor

processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-xls-r-300m-21-to-en")
```

I've opened a PR to update the example on the model card accordingly: https://huggingface.co/facebook/wav2vec2-xls-r-300m-21-to-en/discussions/3
