### ISSUE TITLE
Getting the heat map out of VILT (Figure 4 in the paper)

### ISSUE THREAD

**Issue by Ngheissari** [huggingface/transformers#18940]
### Feature request

I would like to get the heatmap from ViLT (Visualizations of transportation plan of word patch alignment). 

### Motivation

It is useful for debug and also might be useful for other applications. It is shown in Figure 4 in the paper: https://arxiv.org/pdf/2102.03334.pdf

### Your contribution

NA

**Comment by NielsRogge** [comment]
Hi,

Yes it's totally possible to re-create that. Basically it comes down to translate [this script](https://github.com/dandelin/ViLT/blob/master/demo.py) to a Gradio demo.

I'm marking this as "good first issue" as it seems fairly straightforward.

**Comment by atturaioe** [comment]
Hi, I would like to work on it

**Comment by therajatrai** [comment]
@NielsRogge Is this issue still open ? I would to like to work on this. Can you assign this issue to me ?

**Comment by rajathpatel23** [comment]
@NielsRogge , is this issue still open I would like to contribute to this

**Comment by atturaioe** [comment]
Yeah, I guess. I think you guys can go ahead and open PR.

**Comment by vishwajeet-hogale** [comment]
> @NielsRogge , is this issue still open I would like to contribute to this

Hey Rajath ! Would love to work on this issue with you. Do you mind working with me on this? Kinda new to open source contribution.

**Comment by Infrared1029** [comment]
Is anyone still working on this? I can help

**Comment by Infrared1029** [comment]
@NielsRogge is this supposed to be implemented as a method on all vilts or a function that takes a vilt model as input and launches the gradio demo?

**Comment by NielsRogge** [comment]
You can just implement a Gradio demo and host it on https://huggingface.co/spaces.

**Comment by Infrared1029** [comment]
> > You can just implement a Gradio demo and host it on https://huggingface.co/spaces.
> 
> I've made one https://huggingface.co/spaces/MikailDuzenli/vilt_demo , I just implemented the demo of the model itself for the moment but I'm trying to add the heatmap (help is welcome).

I could help

**Comment by NielsRogge** [comment]
Very cool demo @MikailINTech! Awesome work. Final step is indeed visualizing the heatmap

**Comment by MikailINTech** [comment]
> Very cool demo @MikailINTech! Awesome work. Final step is indeed visualizing the heatmap

Thank you ! Just finished adding the heatmap. Is there a way I can have this issue mark as resolved ?

**Comment by NielsRogge** [comment]
Really cool! Although I'd also include the entire image in the result (not just the heat map), to compare.

Then I'll close this issue!

**Comment by MikailINTech** [comment]
> 

Thanks for the suggestion, now one can see the image and the heatmap. I hope that it's what @Ngheissari was looking for

**Comment by NielsRogge** [comment]
Awesome! Closing this issue.

I tweeted about it here :) https://twitter.com/NielsRogge/status/1580246704011370496
