### ISSUE TITLE
`overwrite_cache` argument in `run_lm_finetuning.py` not used at all

### ISSUE THREAD

**Issue by iedmrc** [huggingface/transformers#1894]
There is an unused argument in `run_lm_finetuning.py`

https://github.com/huggingface/transformers/blob/e70cdf083ddb8bfe298d43e6d70d698a3a2f56d3/examples/run_lm_finetuning.py#L418

Is it forgotten?

**Comment by LysandreJik** [comment]
Indeed, thank you!
