### ISSUE TITLE
wrong wav2vec link in audio classification blog

### ISSUE THREAD

**Issue by chrisemezue** [huggingface/transformers#18944]
[This wonderful blog](https://huggingface.co/docs/transformers/main/en/tasks/audio_classification#preprocess) has an issue with the wav2vec model card link. See below:  

> 2. Check the sampling rate of the audio file matches the sampling rate of the audio data a model was pretrained with. You can find this information on the Wav2Vec2 `[model card]((https://huggingface.co/facebook/wav2vec2-base))`.

The right link should be https://huggingface.co/facebook/wav2vec2-base

**Comment by LysandreJik** [comment]
Closed by #18945
