### ISSUE TITLE
Update decision transformers to gym 0.26

### ISSUE THREAD

**Issue by RedTachyon** [huggingface/transformers#18954]
### Feature request

We recently published a [new release of gym](https://github.com/openai/gym/releases/tag/0.26.0), which carries with it a bunch of breaking changes. 
However, this is the last of the API changes, and it will be stable going forward. So it would be great to update the decision transformers to be compatible with that.

### Motivation

I'd say there are two main reasons to switch to the new API that goes with 0.26:
- The new API "makes sense"- we're still preparing a proper writeup of the rationale behind each decision, but they were deliberately made to support good research, flexibility and reproducibility. 
- It will be supported in the future - we have many exciting features on the horizon (e.g. hardware-accelerated environments), which will be predicated on using the new API

### Your contribution

I'll be happy to help with the whole process, including contributing the PR. 

From what I can see, most of the code in transformers is rather self-contained, so it would mainly be the the `run_decision_transformer.py` example that needs updating, and then potentially other resources about decision transformers (like the blog), which would be separate PRs naturally

The biggest question would be how you want to handle versioning. My intuition is that it'd be best to update to gym 0.26 together with some "significant" version of transformers, like `4.22 -> 4.23` (or later, depending on how long it takes).

**Comment by LysandreJik** [comment]
cc @edbeeching
