### ISSUE TITLE
The configuration is not a valid json file

### ISSUE THREAD

**Issue by nicolaspi** [huggingface/transformers#18965]
### System Info

The config at this url [https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/config.json](https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/config.json) is not a valid JSON and produces error:
`json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 88 column 3 (char 2317)`

### Who can help?

@patil-suraj

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import CLIPTextModel
CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14")
```

### Expected behavior

The config should be a valid json.

**Comment by adamhowell** [comment]
👆🏼Same error just started occuring about 30 mins ago across all machines

**Comment by adamhowell** [comment]
<img width="502" alt="Screen Shot 2022-09-09 at 3 00 30 PM" src="https://user-images.githubusercontent.com/26133/189424655-2d594077-d358-41aa-a265-86571dabb522.png">

**Comment by NielsRogge** [comment]
Related to #18962

**Comment by julien-c** [comment]
Just in case, pinging @patil-suraj given a few commits on that model repo today =) https://huggingface.co/openai/clip-vit-large-patch14/commits/main

**Comment by timwillhack** [comment]
is there a way to disable it grabbing the newest?  I disabled my ethernet ran the app, and then turned it back on after it got past that point in the script and I'm running again if someone needs a fast temporary bandaid

**Comment by LysandreJik** [comment]
Thank you for reporting, this was fixed in [openai/clip-vit-large-patch14#4](https://huggingface.co/openai/clip-vit-large-patch14/discussions/4)

**Comment by Lime-Cakes** [comment]
If you have a set of downloaded cache of the unbroken files, you can get around the problem by forcing an offline only mode and using your cache.

If you don't want to edit your script, add TRANSFORMERS_OFFLINE=1, as seen by document here https://huggingface.co/docs/transformers/installation#offline-mode
If you prefer to edit your python scripts, you can pass local_files_only when calling from_pretrained https://huggingface.co/docs/transformers/main_classes/model

**Comment by nicolaspi** [comment]
Fixed
