### ISSUE TITLE
position_ids cannot be specified for GPTNeoXForCausalLM

### ISSUE THREAD

**Issue by nkandpa2** [huggingface/transformers#18999]
### Feature request

The GPTNeoXForCausalLM class' forward method does not support passing `position_ids`. This model class uses rotary positional encodings so `position_ids` are needed for correct forward passes on left padded sequences. 

### Motivation

The GPTNeoXModel class uses rotary positional encodings so `position_ids` are needed for correct forward passes on left padded sequences. Additionally, the documentation (https://huggingface.co/docs/transformers/model_doc/gpt_neox#transformers.GPTNeoXForCausalLM) list `position_ids` as an argument for `forward` but this is not consistent with the implementation. 

### Your contribution

I've taken a look through the code and it's not immediately obvious how to implement this. I'd be happy to contribute but may need some pointers.

**Comment by gante** [comment]
Hi @nkandpa2 👋 

We are aware of this problem (see also https://github.com/huggingface/transformers/issues/17283), and we are working on a fix (https://github.com/huggingface/transformers/pull/18048)

As you wrote, it is not a trivial change :D
