### ISSUE TITLE
Add Molecular Attention Transformer

### ISSUE THREAD

**Issue by shivance** [huggingface/transformers#18990]
### Model description

I would like to add the Molecular Attention Transformer [MAT](https://github.com/ardigen/MAT) model to the Transformers

MAT has been a big leap towards development of a single neural network architecture that performs competitively across a range of molecule property prediction tasks. It unlocked a widespread use of deep learning in the drug discovery industry.  Key innovation in MAT is to augment the attention mechanism in Transformer using inter-atomic distances and the molecular graph structure. Experiments show that MAT performs competitively on a diverse set of molecular prediction tasks. 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Link to Model Repo : [Link](https://github.com/ardigen/MAT)
Link to Paper : [Link](https://arxiv.org/abs/2002.08264)

**Comment by shivance** [comment]
@sgugger Hi, would it be a valuable contribution to HuggingFace?

**Comment by sgugger** [comment]
If you want to dive into this model, yes it would definitely be of interest!

**Comment by shivance** [comment]
Alright @sgugger , I'll soon put up a PR on this !

**Comment by Bearnardd** [comment]
Hi @shivance! - Are you still working on this model? Since if not I would be interested in picking it up. Have a nice day!

**Comment by shivance** [comment]
Sure go ahead @Bearnardd
