### ISSUE TITLE
Can GPT2DoubleHeadsModel be used for regular next token prediction task without adjusting its head?

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#1900]
Hello,

According to the HuggingFace Transformer's website (https://huggingface.co/transformers/model_doc/gpt2.html#gpt2doubleheadsmodel), **GPT2DoubleHeadsModel** is the GPT2 Model transformer with a language modelling and a multiple-choice classification head on top e.g. for RocStories/SWAG tasks. 

Does this mean that we can use the **GPT2DoubleHeadsModel** for the regular language modelling task (i.e. next word prediction) without modifying its head? or would I need to adjust the head of **GPT2DoubleHeadsModel** if I want to do the next word prediction, since GPT2DoubleHeadsModel is for answering multiple-choice type questions only?

Thank you,

**Comment by iedmrc** [comment]
You don't need to do anything in order to make it predict the next word. That's what it is. But you may consider finetuning it with your own dataset.

**Comment by h56cho** [comment]
Hello,

Thank you for your reply.
so the **GPT2DoubleHeadsModel** itself, without any adjustment on the head, can be used for (non-multiple choice based) next token prediction, as well as for the multiple-choice questions?

Thank you,

**Comment by iedmrc** [comment]
Yes,
Check GPT paper figure 1 :
https://s3-us-west-2.amazonaws.com/openai-assets/research-covers/language-unsupervised/language_understanding_paper.pdf
I also suggest you read the entire paper. It gives a good understanding about GPT and language modelling.

**Comment by h56cho** [comment]
If GPT2DoubleHeadsModel can process both multiple-choice questions as well as non-multiple-choice next token predictions without any adjustment, why did HuggingFace make 2 different GPT2 models -- GPT2DoubleHeadsModel and GPT2LMHeadModel ?

Can GPT2DoubleHeadsModel process both multiple-choice questions as well as non-multiple-choice next token predictions without any further adjustment(s) [e.g. adjustment on its head, etc,]?
