### ISSUE TITLE
ConvNextModel doesn't work well on M1 mac for batches containing more than 2 images

### ISSUE THREAD

**Issue by hiroalchem** [huggingface/transformers#19005]
### System Info

- `transformers` version: 4.21.3
- Platform: macOS-12.3.1-arm64-arm-64bit
- Python version: 3.9.13
- Huggingface_hub version: 0.9.1
- PyTorch version (GPU?): 1.12.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Using mps
- Using distributed or parallel set-up in script?: no

### Who can help?

@LysandreJik @NielsRogge @sgugger

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import ConvNextFeatureExtractor, ConvNextModel

device = "mps"
#device = "cpu"
feature_extractor = ConvNextFeatureExtractor.from_pretrained("facebook/convnext-large-224-22k-1k")
model = ConvNextModel.from_pretrained("facebook/convnext-large-224-22k-1k").to(device)

import numpy as np
arr1 = np.zeros((224, 224, 3))
inputs = feature_extractor(arr1, return_tensors="pt").to(device)
print(inputs['pixel_values'].shape)
output = model(**inputs).pooler_output.detach().cpu().numpy().copy()
print(output)
arr2 = [np.zeros((224, 224, 3), np.uint8) for x in range(2)]
inputs = feature_extractor(arr2, return_tensors="pt").to(device)
print(inputs['pixel_values'].shape)
output = model(**inputs).pooler_output.detach().cpu().numpy().copy()
print(output)
```

arr1
```
torch.Size([1, 3, 224, 224])
[[-0.07712477 -0.21273601  0.08057457 ...  0.40773717  0.17893904
   0.25740874]]
```
arr2
```
torch.Size([2, 3, 224, 224])
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

### Expected behavior

Should be able to make inferences even for arr2.

**Comment by alexacole** [comment]
Hello, I have an M1 Mac and would love to try to tackle this issue
