### ISSUE TITLE
Old import clause in seq2seq trainer

### ISSUE THREAD

**Issue by zhaowei-wang-nlp** [huggingface/transformers#19003]
### System Info

transformers==4.21.3
pytorch==1.10.1+cu111

### Who can help?

@sgugger

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When I tried to import Seq2SeqTrainer, there is an bug of import:
"from transformers import Seq2SeqTrainer
File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 992, in __getattr__
module = self._get_module(self._class_to_module[name])
File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1004, in _get_module
raise RuntimeError(
RuntimeError: Failed to import transformers.trainer_seq2seq because of the following error (look up to see its traceback):
cannot import name 'container_abcs' from 'torch._six' (/opt/conda/lib/python3.8/site-packages/torch/_six.py)"
When I google it. I found 'container_abcs' doesn't exist now from torch 1.9.
https://stackoverflow.com/questions/70193443/colab-notebook-cannot-import-name-container-abcs-from-torch-six

### Expected behavior

no import errors.

**Comment by sgugger** [comment]
The problem comes when trying to import `torch`, according to the traceback you posted, so you should raise the issue there :-)

**Comment by zhaowei-wang98** [comment]
> 
There are solutions: people in the following issue changed the import clause by themself. However, in my condition, this import clause is written in the package "transformer," and I can change it.
https://github.com/pytorch/pytorch/issues/51959
