### ISSUE TITLE
AttributeError: 'TrainingArguments' object has no attribute 'main_process_first'

### ISSUE THREAD

**Issue by xueyongfu** [huggingface/transformers#19011]
### System Info

AttributeError: 'TrainingArguments' object has no attribute 'main_process_first'

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

AttributeError: 'TrainingArguments' object has no attribute 'main_process_first'

### Expected behavior

AttributeError: 'TrainingArguments' object has no attribute 'main_process_first'

**Comment by LysandreJik** [comment]
Hey @xueyongfu, could you provide a minimal reproducible code example for the issue you're facing? Thank you.
