### ISSUE TITLE
Methods get_input_embeddings() and set_input_embeddings() appear in documentation but not available.

### ISSUE THREAD

**Issue by alexvaca0** [huggingface/transformers#1901]
## ❓ Questions & Help
Hi, I'm trying to access the word embeddings layer of Bert multilingual, as I want to take out all tokens not belonging to spanish and add some tokens which are part of this language, with the objective of adapting BERT multilingual to spanish. The thing is, in your documentation you claim that there are 2 functions for this purpose: get_input_embeddings() and set_input_embeddings() (https://huggingface.co/transformers/model_doc/bert.html); in fact there is a link to the source code and they appear to be there. However, once I try to do this in version 2.1.1. (the one documentation refers to), none of this methods are part of BertModel class, which is astonishing to me. Please tell me what's wrong!! Did you remove these methods from current versions but have a unique documentation for all versions? Which versions can I find these methods in? Is the source code showed in the documentation different from the actual source code of the library?

**Comment by loveritsu929** [comment]
Did you check if the methods are in `modeling_utils.py` in your local package?
See #1837 . As @julien-c said, the version of the lib you use may not be in sync with the scripts you run.
Try to install the lib from `master`:
`pip install git+https://github.com/huggingface/transformers`

**Comment by julien-c** [comment]
The doc you linked to is for the `master` version, if I'm not mistaken. Maybe we should make that clearer, cc @LysandreJik 

Yes, @loveritsu929 is right – install from source if you want to use those methods right now. Thanks!
