### ISSUE TITLE
LEDForSequenceClassification fine-tuning model gives: IndexError: index out of range in self

### ISSUE THREAD

**Issue by darshan2203** [huggingface/transformers#19019]
### System Info

transformers - 4.21.1
Python - 3.8.13
torch - 1.12.0+cu113

### Who can help?

@patrickvonplaten

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm trying to fine-tune the LED model for the SequenceClassification task.

It works when I use max_sequence_length = 1024 but it doesn't when it goes beyond these numbers. D

After debugging, I found a similar issue #14312, and tried applying the proposed solution by adding decoder_input_ids even though it doesn't make sense to me that we really need this as an input.

To reproduce:
```
from transformers import LEDTokenizer, LEDForSequenceClassification
  
tokenizer = LEDTokenizer.from_pretrained("allenai/led-base-16384")
model = LEDForSequenceClassification.from_pretrained("allenai/led-base-16384")

# this works (tokens < 1024)
inputs = tokenizer("HuggingFace"*1000, return_tensors="pt")
with torch.no_grad():
      model(**input)

# this does not work! (tokens > 1024)
inputs = tokenizer("HuggingFace"*2048, return_tensors="pt")
with torch.no_grad():
      model(**input)

# this does not work as well! (tokens > 1024)
inputs = tokenizer("HuggingFace"*2048, return_tensors="pt")
inputs['decoder_input_ids'] = inputs['input_ids'][:512]
with torch.no_grad():
      model(**input)
```

_Without adding decoder_input_ids to tokenized inputs,_
It simply complains of Index out of range while calling torch.embedding.

_with decoder_input_ids as suggested in the reference issue above,_
It throws an **IndexError: The Shape of the mask [1, 1026] at index 1 does not match the shape of the indexed tensor  [1, 512, 768] at index 1**

### Expected behavior

As LEDForSequenceClassification should work for a sequence length of more than 1024 tokens.

**Comment by patrickvonplaten** [comment]
Hey @darshan2203,

Sorry I won't be free anytime soon to look into this issue - @ArthurZucker do you want to give it a try?

**Comment by ArthurZucker** [comment]
Hey! Thanks for the issue 😄 
The proposed solution, `inputs['decoder_input_ids'] = inputs['input_ids'][:512]` is bound to fail as : 
```python 
inputs['input_ids'][:512].shape
torch.Size([1, 6146])
``` 
It also seems that "HuggingFace" is not parsed into a single token (at least when I used `tokenizer = LEDTokenizer.from_pretrained("allenai/led-base-16384")` but rather 3 : `[0, 40710, 3923, 34892, 2]`. 

When I try : 
```python 
inputs = tokenizer("HuggingFace"*(1000//3), return_tensors="pt")
with torch.no_grad():
      model(**inputs)
```
It works as expected, and in that case the shape of the input is : `1001`. 
Hope this will help you!

**Comment by darshan2203** [comment]
> Hey! Thanks for the issue 😄 The proposed solution, `inputs['decoder_input_ids'] = inputs['input_ids'][:512]` is bound to fail as :
> 
> ```python
> inputs['input_ids'][:512].shape
> torch.Size([1, 6146])
> ```
> 
> It also seems that "HuggingFace" is not parsed into a single token (at least when I used `tokenizer = LEDTokenizer.from_pretrained("allenai/led-base-16384")` but rather 3 : `[0, 40710, 3923, 34892, 2]`.
> 
> When I try :
> 
> ```python
> inputs = tokenizer("HuggingFace"*(1000//3), return_tensors="pt")
> with torch.no_grad():
>       model(**inputs)
> ```
> 
> It works as expected, and in that case the shape of the input is : `1001`. Hope this will help you!

Thanks, Arthur for getting back at this. 

I think there is a gap in our understanding. What I reported is that when we have an input tensor of size more than 1024 tokens, it doesn't work. As per the documentation of a LED-base-16384 model, it can take input sequence up to 16384 tokens.

**Comment by ArthurZucker** [comment]
Oh right! Sorry will have a look asap 🤗

**Comment by ArthurZucker** [comment]
Hey! So as mentioned in the [issue](https://github.com/huggingface/transformers/issues/14312#issuecomment-968768138) you linked, the decoder`s max input length is `1024`, and if the decoder input_ids are not provided, the model uses by default a shifted version of the `input_ids` which in this case are too long. 

A small nit should be added : 
```python 
inputs["decoder_input_ids"] = inputs["input_ids"][:, :512].clone()
inputs["decoder_input_ids"][:, -1] = model.config.eos_token_id
with torch.no_grad():
     model(**inputs)
```
However this still does not work there is a deeper issue. 
I will open a PR and add a test, long sequence classification does not seem to be tested, and the following code (link [here](https://github.com/ArthurZucker/transformers/blob/fix_tf_special_layer_name/src/transformers/models/led/modeling_led.py#L2601-L2607)) : 
```python 
        eos_mask = input_ids.eq(self.config.eos_token_id)

        if len(torch.unique_consecutive(eos_mask.sum(1))) > 1:
            raise ValueError("All examples must have the same number of <eos> tokens.")
        sentence_representation = hidden_states[eos_mask, :].view(hidden_states.size(0), -1, hidden_states.size(-1))[
            :, -1, :
        ]
```
should probably be replaced with 
````
        eos_mask = decoder_input_ids.eq(self.config.eos_token_id)

        if len(torch.unique_consecutive(eos_mask.sum(1))) > 1:
            raise ValueError("All examples must have the same number of <eos> tokens.")
        sentence_representation = hidden_states[eos_mask, :].view(hidden_states.size(0), -1, hidden_states.size(-1))[
            :, -1, :
        ]
```
Will open a PR for that, thanks for the issue !
