### ISSUE TITLE
How to find the accuracy of the generated questions from the text ?

### ISSUE THREAD

**Issue by Roshni3499** [huggingface/transformers#19021]
I am generating a 4 types of questions. 1. WH (what, where, who, which etc.) 2. Boolean type 3. Fill in blanks 4. MCQ.

I am able to find the accuracy of the WH & MCQ type question through the code given below.

```
question= list of question
context = paragraph

from transformers import pipeline

question_answerer = pipeline("question-answering")
question_score = []
for i in question:
      final_score_list = question_answerer(question=i, context=context)
      final_score = final_score_list.get("score")
      final_score ="%.2f" % round(final_score*100, 2)+"%"
      question_score.append(final_score)

Output = 98.87%
```

As this model find the accuracy based on question and context, I am getting accuracy for WH & MCQ. 
but there is no question in Fill in blanks type question , I am not able to find the accuracy for the fill in blanks type question. and also it not working for the Boolean questions. 

So, is there any other model or any other way for find the accuracy of the FIB & Boolean type questions ? 

Here is the reference link for the question generation code.
1. WH = [https://medium.com/featurepreneur/question-generator-d21265c0648f](https://medium.com/featurepreneur/question-generator-d21265c0648f)
2. MCQ = [https://github.com/AMontgomerie/question_generator/blob/master/examples/question_generation_example.ipynb](https://github.com/AMontgomerie/question_generator/blob/master/examples/question_generation_example.ipynb)
3. FIB = [https://github.com/sudheernaidu53/Machine-learning-Deep-learning-projects](https://github.com/sudheernaidu53/Machine-learning-Deep-learning-projects)
4. Boolean = [https://github.com/ramsrigouthamg/generate_boolean_questions_using_T5_transformer/blob/master/t5_inference.py](https://github.com/ramsrigouthamg/generate_boolean_questions_using_T5_transformer/blob/master/t5_inference.py)

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
