### ISSUE TITLE
Typo in Documentation for GPT2LM Output "past"

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#1904]
I think the described output shape for "past" for GPT-2 is wrong.
In:
[https://github.com/huggingface/transformers/blob/0cdfcca24b5739e25b584c05b866baa19ea382ef/transformers/modeling_gpt2.py#L332](url)
it says the output shape of each key, value tensor in each self attention layer is 
``(batch_size, num_heads, sequence_length, sequence_length)``
, but it should be 
``(batch_size, num_heads, sequence_length, hidden_size / num_heads)``
 or 
``(batch_size, num_heads, sequence_length, embed_size_per_head)``
.Also since the past tensor per layer always shows both key and value tensors it might even be clearer to write:
``(2, batch_size, num_heads, sequence_length, embed_size_per_head)``

**Comment by thomwolf** [comment]
Yes, feel free to open a PR to fix this Patrick ;-)
