### ISSUE TITLE
run_summarization_finetuning.py

### ISSUE THREAD

**Issue by jmamou** [huggingface/transformers#1905]
## ❓ Questions & Help
Hi
Does your code run_summarization_finetuning.py implement the abstractive summarization approach described in "Text summarization with pretrained encoders." by Liu, Yang, and Mirella Lapata?
Thanks

**Comment by TheEdoardo93** [comment]
I think so. The script called `run_summarization_finetuning.py` has the goal of extracting text summary given as input a text document. This code shows how to fine-tune a text summarizer model (called **BertSum**) with two different datasets: CNN and Daily Mail.

> ##  Questions & Help
> Hi
> Does your code run_summarization_finetuning.py implement the abstractive summarization approach described in "Text summarization with pretrained encoders." by Liu, Yang, and Mirella Lapata?
> Thanks
