### ISSUE TITLE
Small Typo in Docs GenerationMixin for use_cache parameter

### ISSUE THREAD

**Issue by ankrgyl** [huggingface/transformers#19079]
### System Info

In the text_generation docs (https://huggingface.co/docs/transformers/main_classes/text_generation), `use_cache` does not show up as its own line in the list of parameters.

<img width="973" alt="Screen Shot 2022-09-16 at 6 09 30 PM" src="https://user-images.githubusercontent.com/565363/190812185-35c6eb4d-fbbf-4d17-ad86-6c1d2083c0e0.png">

I think this is a small typo due to an extra `:` in the code. Happy to fix.

### Who can help?

@LysandreJik 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The website link

### Expected behavior

`use_cache` should be on its own line

**Comment by gante** [comment]
@ankrgyl that's a good finding 👍 A PR contribution would be deeply appreciated (for TF and FLAX as well, if the typo also exists there), but I will pick it up otherwise :)
