### ISSUE TITLE
HfArgumentParser support yaml parser

### ISSUE THREAD

**Issue by jiangwy99** [huggingface/transformers#19116]
### Feature request

HfArgumentParser now supports for parsing dict and json files, will it be possible to support for parsing the widely used yaml files?

### Motivation

I think using yaml is a good way to record arguments.

### Your contribution

Not yet.

**Comment by LysandreJik** [comment]
cc @sgugger 

If you want to open a PR, please go ahead!

**Comment by felix-schneider** [comment]
You can just use
`parser.parse_dict(yaml.safe_load(f))`

**Comment by sgugger** [comment]
Which could all go in a `parse_yaml_file` method :-) Doing this and also refactoring the `parse_json_file` to use `parse_dict`, as well as adding small tests would be nice additions that shouldn't be too hard, so putting the "Good first issue" label here.

To summarize:
- [ ] adding as `parse_yaml_file` method to `HfArgumentParser` with the code above
- [ ] refactor the dupe code between `parse_json_file` and `parse_dict` similar to the code above
- [ ] add a small test of `parse_yaml_file`
- [ ] add a small test of `parse_json_file`

This could be done in a single PR or separate ones :-)

**Comment by IMvision12** [comment]
Hi, I would like to work on it

**Comment by IMvision12** [comment]
How can i write test for  `parse_yaml_file` and `parse_json_file` it will require an external json and yaml file to testing

**Comment by sgugger** [comment]
No, you can create it during the test by saving some dictionary (look at the `parse_dict` tests) into a temporary file.

**Comment by IMvision12** [comment]
Hey, @sgugger I have written the test for `parse_yaml_file` and `parse_json_file` using tempfile is it acceptable?? Also it passes the tests.
![Capture](https://user-images.githubusercontent.com/88665786/192546217-56e3f77f-85ca-4b7f-b1fd-cd54d6f6a3bb.PNG)

**Comment by sgugger** [comment]
You can also use the context manager for a temp dir.
```
with tempfile.TemporaryDirectory() as tmp_dir:
    # Save file in tmp_dir as usual
    # do the tests
```
The plus for this is that it's automatically cleaned up when you exit the with block (whereas the temp file will stay until the next restart).

**Comment by IMvision12** [comment]
Okay I will change that!
