### ISSUE TITLE
GPT Neox Japanese is in the release notes for v4.22.X but does not appear to be in the v4.22.X package.

### ISSUE THREAD

**Issue by SO0529** [huggingface/transformers#19114]
### System Info

I've checked in Colab that GPT Neox Japanese is not in v4.22.1
```
- `transformers` version: 4.22.1
- Platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.14
- Huggingface_hub version: 0.9.1
- PyTorch version (GPU?): 1.12.1+cu113 (False)
- Tensorflow version (GPU?): 2.8.2 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

@LysandreJik

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Open colab
2. `!pip install transformers` to install the latest version (currently v4.22.1)
3. `from transformers import GPTNeoXJapaneseForCausalLM, GPTNeoXJapaneseTokenizer`
then raise below import error.
```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-7-401722e84f23>](https://localhost:8080/#) in <module>
----> 1 from transformers import GPTNeoXJapaneseForCausalLM, GPTNeoXJapaneseTokenizer

ImportError: cannot import name 'GPTNeoXJapaneseForCausalLM' from 'transformers' (/usr/local/lib/python3.7/dist-packages/transformers/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

In [this release note](https://github.com/huggingface/transformers/releases/tag/v4.22.0), I thought we can use `GPT NeoX Japanese` from v4.22.0 release. That's not surprising, the model was not included in the zip file of the v4.22.0 release...
I would be glad to know the situation:smiley:

FYI
We can use GPT NeoX Japanese from `pip install git+https://github.com/huggingface/transformers` because it's in the main branch.

### Expected behavior

`GPT Neox Japanese` must be able to import correctly.

**Comment by LysandreJik** [comment]
Hey @SO0529, sorry about that! That's on me, I missed this in the release notes. I just removed it. For now you can install the repo from source as you have noted in order to use it.

Thanks for letting me know!
