### ISSUE TITLE
Luke Finetuning Error

### ISSUE THREAD

**Issue by luffycodes** [huggingface/transformers#19148]
### System Info

- `transformers` version: 4.21.2
- Platform: Linux-4.15.0-192-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.13
- Huggingface_hub version: 0.9.1
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@sgugger @jplu

Hi, I was running the finetuning script for LUKE: [Link](https://github.com/huggingface/transformers/blob/main/examples/research_projects/luke/run_luke_ner_no_trainer.py).

I ran into this weird issue:
forward() got an unexpected keyword argument 'ner_tags'

Also, any idea as to what's the f1 score for ner task using this script?

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`CUDA_VISIBLE_DEVICES=0 python run_luke_ner_no_trainer.py   --model_name_or_path studio-ousia/luke-base   --dataset_name conll2003   --task_name ner  --max_length 128   --per_device_train_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3   --output_dir NER`

### Expected behavior

Starts the training process.

**Comment by GuishePerez** [comment]
Hi!
I also experience this error. @luffycodes could you eventually make it work?
