### ISSUE TITLE
Can't use decoder_inputs_embeds argument on MBartForConditionalGeneration

### ISSUE THREAD

**Issue by hibiki12y** [huggingface/transformers#19157]
### System Info

- `transformers` version: 4.22.0
- Platform: Linux-4.4.0-210-generic-x86_64-with-glibc2.23
- Python version: 3.9.12
- Huggingface_hub version: 0.7.0
- PyTorch version (GPU?): 1.12.0 (True)
- Tensorflow version (GPU?): 2.9.1 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Who can help?

@patil-suraj

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

maybe not necessary

### Expected behavior

https://github.com/huggingface/transformers/pull/13800

Looks same problem at MBartForConditionalGeneration.foward

It is written as:

```python
if decoder_input_ids is None:
    decoder_input_ids = shift_tokens_right(labels, self.config.pad_token_id)
```

So, looks need edit to:

```python
if decoder_input_ids is None and decoder_inputs_embeds is None:
    decoder_input_ids = shift_tokens_right(labels, self.config.pad_token_id)
```

**Comment by LysandreJik** [comment]
Maybe of interest to @ArthurZucker :)

**Comment by ArthurZucker** [comment]
Will open a PR, it seems that 3 modeling files are concerned : `m_bart` `tf_m_bart` and `plbart`. Thanks for finding this 🤗
