### ISSUE TITLE
ALIBI position embedding support for other models ( BERT, ELECTRA )

### ISSUE THREAD

**Issue by theblackcat102** [huggingface/transformers#19222]
### Feature request

Since BLOOM is using ALIBI for position embedding, is there any plans to add ALIBI to other existing models such as BERT, ELECTRA etc?

ALIBI have so far proven to be [extrapolate sequence length beyond training sequence](https://arxiv.org/pdf/2108.12409.pdf) (figure 4). I think this idea should be added to existing architecture since existing models such as BERT, ELECTRA already supports more than one types of position embedding strategy.

### Motivation

If existing models such as BERT, Roberta or ELECTRA supports ALIBI position strategy, this will motivate community pretrained BERT which supports beyond 512 sequence length. One of the largest impact would be long form input sequence in summarization task.

### Your contribution

I have implemented ALIBI mechanism on my own private transformer fork and could submit a PR if this idea is accepted.

**Comment by nreimers** [comment]
@theblackcat102 I would be quite interested in that. Could you also link your fork?

I would be quite interested to train BERT et al for longer sequences.

**Comment by leocnj** [comment]
@nreimers, you may take a look on MosaicAI's composer package. It provides a simple way to do a network surgery to add ALiBi into either BERT (RoBERTa) or GPT models.

I tried on GPT-2 model and it changes position embedding quite easily.  The below figure compares two models (blue w/ default PE while orange w/ ALiBi PE) that are trained on L=256 tokens but tested on longer sequences. We can find ALiBI supports "train short while test long" as described in their paper.

![image](https://github.com/huggingface/transformers/assets/4459248/d8cdc706-37b0-48f4-ac97-e2239765f312)


https://docs.mosaicml.com/projects/composer/en/stable/method_cards/alibi.html

**Comment by leocnj** [comment]
Also, tried the similar idea on BERT-base model, however, when using sin/cos absolute PE, I cannot find the perplexity explosion effect as shown in GPT-2 above. Any suggestion for finding a good metric to measure a MLM model?

```shell
len: 256 ==> PPL: 1.0095623592512963
len: 257 ==> PPL: 1.009994390628342
len: 512 ==> PPL: 1.0602131151848846
len: 768 ==> PPL: 1.0771209222866058
```
