### ISSUE TITLE
TrainingArguments._n_gpus serialization

### ISSUE THREAD

**Issue by atturaioe** [huggingface/transformers#19236]
I'm not sure, but I think that `TrainingArguments._n_gpu` attribute is not supposed to be serialized in `TrainingArguments.to_dict()` .
Or even basically all the attributes that are defined as `dataclass.field(init=False...)` should be filtered out while doing `to_dict()`.

What do you think?

@sgugger

**Comment by sgugger** [comment]
Indeed, this argument shouldn't be serialized.

**Comment by atturaioe** [comment]
I'll do PR
