### ISSUE TITLE
TypeError: convert_examples_to_features() got an unexpected keyword argument 'sequence_a_is_doc'

### ISSUE THREAD

**Issue by snijesh** [huggingface/transformers#1924]
## 🐛 Bug

Model I am using (Bert):

Language I am using the model on (English):

The problem arise when using:
```
!python run_squad.py \
  --model_type bert \
  --model_name_or_path bert-large-uncased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file train-v1.1.json \
  --predict_file dev-v1.1.json \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /tmp/debug_squad/
```

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: Fine-tuning on SQuAD

## Environment

* OS:
* Python version: 3.6
* PyTorch version: 1.3.1'
* PyTorch Transformers version (or branch): 2.1.1
* Using GPU ? Yes

**Comment by TheEdoardo93** [comment]
Please, try to install Transformers library from source code, and not from PyPi. The former one is the up-to-date version. In fact, if you see in [utils_squad.py](https://github.com/huggingface/transformers/blob/master/examples/utils_squad.py) at row 197, there is a parameter called `sequence_a_is_doc` in the definition of the `convert_examples_to_features()` method. Try it out and keep us updated on this problem!

> ##  Bug
> Model I am using (Bert):
> 
> Language I am using the model on (English):
> 
> The problem arise when using:
> 
> ```
> !python run_squad.py \
>   --model_type bert \
>   --model_name_or_path bert-large-uncased \
>   --do_train \
>   --do_eval \
>   --do_lower_case \
>   --train_file train-v1.1.json \
>   --predict_file dev-v1.1.json \
>   --per_gpu_train_batch_size 12 \
>   --learning_rate 3e-5 \
>   --num_train_epochs 2.0 \
>   --max_seq_length 384 \
>   --doc_stride 128 \
>   --output_dir /tmp/debug_squad/
> ```
> 
> The tasks I am working on is:
> 
> * [ ]  an official GLUE/SQUaD task: Fine-tuning on SQuAD
> 
> ## Environment
> * OS:
> * Python version: 3.6
> * PyTorch version: 1.3.1'
> * PyTorch Transformers version (or branch): 2.1.1
> * Using GPU ? Yes
