### ISSUE TITLE
A developer environment, for faster and efficient contributions.

### ISSUE THREAD

**Issue by AnirudhDaya** [huggingface/transformers#19285]
### Feature request

Hello maintainers.
I would like to add gitpod to your repo to help beginners contribute.
 - Gitpod is an online IDE which can be launched from any GitHub page. Within seconds, Gitpod provides a fully working development environment, including a VS Code-powered IDE and a cloud-based Linux container explicitly configured for the project
- Gitpod is highly contextual, such that it opens the IDE in the correct mode depending on the context:
   -  If you are looking at a particular file of a certain commit on GitHub, starting a Gitpod workspace will check out the right version and open the file you’ve been looking at in the IDE.

   - Starting a Gitpod workspace from an issue will automatically create a branch and preconfigure the commit message.
- Once you are in the IDE, you can interact with GitHub in various ways. Besides the obvious Git integration, you can do things like commenting inline in editors, approving and even merging PRs.

### Motivation

I have seen many repos adopting gitpod to help new contributors in their open-source journey. It's hassle-free. You don't need to worry about dependencies not being present, since gitpod does all the heavy lifting.

### Your contribution

I can add a badge to your repo in the [CONTRIBUTING.md](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md) file similar to this one:
<a href="https://gitpod.io/#<your-repository-url>">
  <img
    src="https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod"
    alt="Contribute with Gitpod"
  />
</a>

**Comment by LysandreJik** [comment]
Hey @AnirudhDaya, what difference is there with https://github.dev/huggingface/transformers ?

Thank you!
