### ISSUE TITLE
T5 vocab size discrepancy between config and tokenizer

### ISSUE THREAD

**Issue by djaym7** [huggingface/transformers#19306]
### System Info

![image](https://user-images.githubusercontent.com/12378820/193693962-7720b071-f6d3-4973-8df1-57b5236ea4c8.png)

transformers version == '4.18.0'

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Copy the code in image

### Expected behavior

same vocab size

**Comment by wenmin-wu** [comment]
I found the same issue for deberta-v3 #19301. It should be fine as long as the model's vocab is larger than the tokenizer's.
