### ISSUE TITLE
Make all models folder independent from each other

### ISSUE THREAD

**Issue by sgugger** [huggingface/transformers#19303]
Transformers has a Do Repeat Yourself policy in the sense that it does not provide building blocks that we then mix and match, but we strive to have each model be self-contained in terms of code, at the price of code duplication. You can find more about this philosophy in [this blog post](https://huggingface.co/blog/transformers-design-philosophy).

There are instances in the library (mostly with older models) where this is not respected. This issue will serve as a tracker for all those instances, so that the library is cleaner and each model/tokenizer/config is easier to tweak by itself. This will also make it easier for us to test individual models in autonomy.

If you wish to make a contribution to Transformers, you can help! Pick a config/model/tokenizer in the list below (double-check someone is not working on it already by searching this page!) and indicate with a comment that wish to work on it. Read our [contributing guide](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md)  as well as the section below, and once you are ready, open a PR and tag @sgugger on it.

## How to remove a dependency from another model

There are two different types of dependencies: either a configuration/model/tokenizer uses an intermediate object from another model (example: some tokenizer uses the `BasicTokenizer` defined in the `tokenization_bert` module, or it subclasses another configuration/model/tokenizer.

In the first case, the object code should just be copied inside the file, with a "Copied from" statement. This will make sure that code is always kept up to date even if the basic object is modified. For instance, if a tokenizer is using `BasicTokenizer`, go copy the code in `tokenization_bert` for that class, then paste it in the tokenizer module you are treating and add the following copied from comment:

```py
# Copied from transformers.models.bert.tokenization_bert.BasicTokenizer
class BasicTokenizer(object):
...
```

In the second case, the code of the class (and all its building blocks) should be copied and renamed to be prefixed by the model: for instance if you are copying code from the modeling_bert module to build Roberta, you replace all `BertLayer`, `BertOutput` etc... by `RobertaLayer`, `RobertaOutput`... 
You should then add a copied from statement (when the copy is without any modification) like this one:
```py
# Copied from transformers.models.bert.modeling_bert.BertAttention with Bert->Roberta
class RobertaAttention(nn.Module):
...
```
Note the replacement pattern that will adapt all names used. Note that:
- you can add more of those patterns, separated by a comma like [here](https://github.com/huggingface/transformers/blob/c28d04e9e252a1a099944e325685f14d242ecdcd/src/transformers/models/blenderbot_small/modeling_blenderbot_small.py#L1388).
- you can ask to replace all possible casings like [here](https://github.com/huggingface/transformers/blob/c28d04e9e252a1a099944e325685f14d242ecdcd/src/transformers/models/mobilebert/modeling_mobilebert.py#L1549)
- you can just copy one method and not the whole class like [here](https://github.com/huggingface/transformers/blob/c28d04e9e252a1a099944e325685f14d242ecdcd/src/transformers/models/roberta/modeling_roberta.py#L741)

**NB:** No need for copied from statements in the config (the defaults are probably different anyway).

### Configurations

- [x] Flaubert config (should not use XLM)
- [x] LayoutLM config (should not use Bert)
- [x] LongformerConfig (should not use Roberta)
- [x] MarkupLMConfig (should not Roberta)
- [x] RobertaConfig (should not use Bert)
- [x] XLM-ProphetNet config (should not use ProphetNet)
- [x] XLM-Roberta config (should not use Roberta)

### Models

- [x] BertGeneration (should not use BertEncoder)
- [x] Camembert (should not use Roberta) (PyTorch + TF)
- [x] Flaubert (should not use XLM) (PyTorch + TF)
- [ ] mT5: ~PyTorch~, TensorFlow, Flax (should not use T5)
- [x] XLM-ProphetNet (should not use ProphetNet)
- [ ] Xlm-Roberta: ~PyTorch~, TensorFlow, Flax (should not use Roberta)

### Tokenizers

- [x] BertJapanese (should not use any imports from tokenization bert)
- [x] Blenderbot (should not use Roberta) (slow/fast)
- [x] Clip (should not use BasicTokenizer from Bert)
- [x] ConvBERT (should not use Bert) (slow/fast)
- [x] Cpm tokenizer (should not use XLNet) (slow/fast)
- [x] Derberta tokenizer (should not use GPT2) (slow/fast)
- [x] DistilBert (should not use Bert) (slow/fast)
- [x] Electra (should not use Bert) (fast)
- [x] Flaubert (should not use XLM)
- [x] Funnel (should not use Bert) (slow/fast)
- [x] Herbert (should not BasicTokenizer from Bert and XLM)
- [x] LayoutLM (should not use Bert) (slow/fast)
- [x] LED (should not use BART) (slow/fast)
- [x] Longformer (should not use Roberta) (fast tokenizer)
- [x] Luke (should not use Roberta)
- [x] Lxmert (should not use Bert) (slow/fast)
- [x] MobileBert (should not use Bert) (slow/fast)
- [x] Openai-GPT (should not use BasicTokenizer from Bert)
- [x] ProphetNet (should not use BasicTokenzier and WordPieceTokenizer from Bert)
- [x] Retribert tokenizer (should not use Bert) (slow/fast)
- [x] Roformer tokenizer (should not use any imports from tokenization bert)
- [x] Squeezebert tokenizer (should not use Bert) (slow/fast)

**Comment by arnaudstiegler** [comment]
Hello! Happy to take LayoutLM Config and Tokenizer :)

**Comment by OtherHorizon** [comment]
Hi, I would like to work on this. thanks.

**Comment by sgugger** [comment]
Hi @OtherHorizon , as explained in the issue, please pick a model/config and/or tokenizer so that others know not to pick the same one :-)

**Comment by srhrshr** [comment]
Hi @sgugger, I like this philosophy, and I can work on DoRYing `LongformerConfig` and `Longformer Tokenizer` :)

**Comment by Harsh-1309** [comment]
Hi @sgugger, I would like to work on RobertaConfig config and DistilBert tokenizer!

**Comment by Mustapha-AJEGHRIR** [comment]
Hi @sgugger, I would love to work on `Camembert` model.

**Comment by asofiaoliveira** [comment]
Hello @sgugger I can work on the `Xlm-Roberta` model and config

**Comment by E-Aho** [comment]
Heya! I'd like to grab the `OpenAI-GPT` tokenizer :)

**Comment by D3xter1922** [comment]
Hi! I'd like to work on `FlaubertConfig`, `Flaubert` model and `Flaubert` tokenizer

**Comment by D3xter1922** [comment]
Hi! I'd Like to work on `Flaubert` config and model

**Comment by divyanshugit** [comment]
Hi, I would like to work on mT5 and ProphetNet.

**Comment by OtherHorizon** [comment]
Hi, i would like to work on `Electra` config

**Comment by Threepointone4** [comment]
Hi, I would like to work on `BertGeneration`.

**Comment by IMvision12** [comment]
Hi! I'd Like to work on `ConvBERT`

**Comment by 501Good** [comment]
Hi! I would like to work on `MobileBert` tokenizer.

**Comment by srhrshr** [comment]
Hello! I can also take up refactoring XLM-ProphetNet model and config.

**Comment by Davidy22** [comment]
Hello, commenting to mark retribert

**Comment by harry7337** [comment]
Hello! I would like to work on `Herbert` tokenizer.

**Comment by naveennamani** [comment]
Hello, I would like to work on Roformer tokenizer

**Comment by traveler-pinkie** [comment]
Hi, I'd would gladly like to work on the Funnel tokenizer.

**Comment by rchan26** [comment]
Hi all - I'd like to work on `Blenderbot` and `Squeezebert tokenizer` 😄

**Comment by D3xter1922** [comment]
Hi, I'd like to work on `MarkupLM` config.

**Comment by Davidy22** [comment]
Coming in to mark BertJapanese and Cpm now that I have some idea of how this goes

**Comment by RamitPahwa** [comment]
I would like to work on `Derberta tokenizer`.

**Comment by traveler-pinkie** [comment]
https://github.com/traveler-pinkie/transformers/pull/1#issue-1401790246

**Comment by harry7337** [comment]
I can work on `mt5 model` if free! @divyanshugit Can I take the issue, if you haven't already started?

**Comment by SuryanarayanaKrishnan** [comment]
hi @sgugger i would love to work on MarkupLMConfig

**Comment by soma2000-lang** [comment]
@sgugger Would like to work on the Roberta config.Please assign me

**Comment by sirmammingtonham** [comment]
hi @sgugger i can try working on the XLM-ProphetNet model 😊

**Comment by sgugger** [comment]
The fast tokenizers for ELECTRA and Longformer are still available FYI :-)

**Comment by Threepointone4** [comment]
@sgugger I would like to contribute fast tokenizers `ELECTRA` and `Longformer`

**Comment by sirmammingtonham** [comment]
@Threepointone4 yep I can take the longformer fast tokenizer thanks!

**Comment by dhgoratela** [comment]
@sgugger , Are there any tasks available further. I'd like to work on this

**Comment by sgugger** [comment]
I think everything is taken as of now. If someone reports back they can't complete the model they picked, I will let you know!

**Comment by henryjiang18** [comment]
@sgugger what if the code is changed in the source after it has been copied to the target? Do you have to manually copy again the new version?

**Comment by sgugger** [comment]
No, that's what the `Copied from` statements are for, they will make sure the code always stay up to date.

**Comment by Manas2011** [comment]
Hi @sgugger  I would like to work on RobertaConfig

**Comment by IvanLauLinTiong** [comment]
Hi @sgugger , I would like to work on `BertJapanese` and `Cpm` tokenizer.

**Comment by Saad135** [comment]
Hi @sgugger, while browsing through the different models, I realized that CamembertConfig is dependent on RobertaConfig. But, it seems the config is exactly the same as RobertaConfig. So essentially CamembertConfig is actually dependent on BertConfig, since RobertaConfig is dependent on BertConfig. 

However, I could not find CamembertConfig on the list above, so I am unsure if there is a need for seperating the RobertaConfig dependecy from CamembertConfig. Just incase it is, I will start a PR and maybe I can get some feedback from there.

**Comment by Saad135** [comment]
Hi @sgugger, I would like to work on RobertaConfig next. Unsure if someone is working on it currently or not, since the last [pull request](https://github.com/huggingface/transformers/pull/19856) submitted for RobertaConfig was 14 days ago. That pull request was later closed, and no new PR was opened since then. I will submit a PR just incase, no one is working on it.

**Comment by salvo96** [comment]
Hi! I would like to work on `Luke` tokenizer

**Comment by SD-13** [comment]
Hey @sgugger, Can I take the `mT5` model and `DistilBert` tokenizer? Thanks,

**Comment by sgugger** [comment]
Sure

**Comment by sgugger** [comment]
mt5 is the last one on the list!

**Comment by SamuelzXu** [comment]
@sgugger I'll give mt5 a shot

**Comment by SamuelzXu** [comment]
Ah, @SD-13 are you still working on this?

**Comment by SD-13** [comment]
> Ah, @SD-13 are you still working on this?

Yes, I am on it. Sorry for the delay, I had exams.

**Comment by SamuelzXu** [comment]
No worries! If you haven't started already, I've already been poking around at it for a bit and I'd like to keep going with it. Totally up to you, though :D

**Comment by SD-13** [comment]
@SamuelzXu , I already started! Please feel free to take some other issue, thanks for asking though :)

**Comment by SamuelzXu** [comment]
Hi @SD-13 , I noticed for your PR you didn't make any modifications to the mt5 tokenizers, which have dependencies on T5Tokenizer. Mind if I take care of that part if you're not already?

**Comment by SD-13** [comment]
Hey @SamuelzXu yeah, go ahead 👍🏽

**Comment by sgugger** [comment]
As @ydshieh discovered, a couple of models slipped through the cracks, check the list at the top if you still want to contribute :-)

**Comment by SD-13** [comment]
Hey @sgugger , Can I take the `Xlm-Roberta` and `mt5` model. Thanks,

**Comment by ydshieh** [comment]
@SD-13 You are very welcome to take them. But it would be a good idea to work on one model type at a time :-) and take another one if it's still available ❤️ when you finish the selected one.

**Comment by SD-13** [comment]
@ydshieh , yeah very true, thanks for reminding that. I would take `mt5`

**Comment by SamuelzXu** [comment]
@SD-13 I was referring to [this line](https://github.com/huggingface/transformers/blob/4f1c9d162ee53004be4d63b76627bd0c2f5a31a9/src/transformers/models/mt5/__init__.py#L37) in init.py which defines MT5Tokenizer as T5Tokenizer

**Comment by SamuelzXu** [comment]
[And also](https://github.com/huggingface/transformers/blob/4f1c9d162ee53004be4d63b76627bd0c2f5a31a9/src/transformers/models/mt5/__init__.py#L44) MT5TokenizerFast defined as T5TokenizerFast

**Comment by SamuelzXu** [comment]
@sgugger I'll take a look at the conversion for XLM-Roberta. Could you add [MT5Tokenizer](https://github.com/huggingface/transformers/blob/4f1c9d162ee53004be4d63b76627bd0c2f5a31a9/src/transformers/models/mt5/__init__.py#L37) and [MT5TokenizerFast](https://github.com/huggingface/transformers/blob/4f1c9d162ee53004be4d63b76627bd0c2f5a31a9/src/transformers/models/mt5/__init__.py#L44) to the list please? Looks like they're defined as the T5Tokenizer.
