### ISSUE TITLE
NER Training on custom Data

### ISSUE THREAD

**Issue by akshaydhok07** [huggingface/transformers#19311]
https://github.com/huggingface/transformers/blob/4c962d5e790d06c142af35aad165c74c0bcf861a/examples/pytorch/token-classification/run_ner.py#L200

[README.md](https://github.com/huggingface/transformers/tree/main/examples/pytorch/token-classification#readme) mentions providing text files for training and validation, however, run_ner.py expects CSV or JSON files only.

**Comment by WeiShi-9** [comment]
I have the same question! Can anyone tell me how to design my custom data file format? Thank u!!

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to discuss questions like this as we keep the issues for bugs and feature requests only.

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by ucas010** [comment]
@sgugger @WeiShi-9 @akshaydhok07 @vanpelt @pvl 
I have the same problem, how to set custom data for  trainning  with the [pipeline]([run_ner.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/token-classification/run_ner.py))

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by HeroadZ** [comment]
@sgugger 
The similar question has been created in the [forum](https://discuss.huggingface.co/t/custom-files-for-run-ner-py/9156), but no one handle it.
Also, the similar issue actually hasn't been solved in https://github.com/huggingface/transformers/issues/8698 .
If you can provide a tiny example for csv or json format in README, that should be very helpful. 😃

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~

**Comment by WeiShi-9** [comment]
你好，我已经收到您的邮件~
