### ISSUE TITLE
where can I find document about BertPreTrainedModel?

### ISSUE THREAD

**Issue by Lim-Sung-Jun** [huggingface/transformers#19318]
hello,

I am trying to find document about BertPreTrainedModel which is used on colbertv1
I only found the source code below site ( 4.11.3 bert_modeling )
https://huggingface.co/transformers/v3.5.1/_modules/transformers/modeling_bert.html

but I didn't find any document for this in the official site for latest version
https://huggingface.co/

So, My question is **where can I find document about BertPreTrainedModel? is this removed?**

**Comment by LysandreJik** [comment]
What are you trying to do with `BertPreTrainedModel`? This is an abstract class that isn't really public facing.
