### ISSUE TITLE
Using model output by transformers (v2.0) in older versions (0.4.0 or 1.0.0) 

### ISSUE THREAD

**Issue by Genius1237** [huggingface/transformers#1931]
## ❓ Questions & Help

I have a bert model finetuned on in-domain data on the latest version of the package (`2.0`). I would now like to use this in some code that is written with the older version of the package (say `0.4.0` or `1.0.0`). Would this be possible?

I tried pointing the code which imports version `0.4.0` to the model output and it gave an error saying `bert_config.json` not found, but there was a `config.json` in the model folder. I renamed `config.json` file and made the code run again and it seems to run.

Am I on the right track? Is this all I have to do to get it run?

**Comment by LysandreJik** [comment]
Models' architectures should have stayed relatively the same between versions. If you did not get warnings telling you that some layers had not been loaded, then you should be good to go!

You could try and compare inferences between two environments which have different versions of the library installed to make sure that they're the same.

**Comment by Genius1237** [comment]
Well, I don't get any warnings, so that is good.

Could someone comment on `bert_config.json` vs `config.json`. Has there been any change in the naming scheme with the newer versions?
