### ISSUE TITLE
Better documentation for pipelines

### ISSUE THREAD

**Issue by rhelmeczi** [huggingface/transformers#19324]
### Feature request

The [introduction to pipelines](https://huggingface.co/docs/transformers/main_classes/pipelines) documentation does not provide any details on how additional parameters can be passed to the tokenizer during the preprocessing step. After walking through all of the source code, I can see that when instantiating a pipeline via `transformers.pipline(...)` one can simply pass these arguments in as keyword arguments, this is not documented anywhere. It is also not included in any examples.

This request is to have the documentation updated so future users don't need to read the source code. This update should expand beyond tokenizing (as it also handles post_processing, etc...).

### Motivation

It's very often the case that a tokenizer is not called with the default arguments: padding, max length, etc... are often changed. The implementation for pipelines actually makes setting these arguments very simple, but it is not communicated so it is difficult to take advantage of.

### Your contribution

I can contribute to the documentation if needed.

**Comment by DIvkov575** [comment]
could I get assigned to this?

**Comment by LysandreJik** [comment]
ping @Narsil @stevhliu @sgugger

**Comment by DIvkov575** [comment]
@Narsil @stevhliu @sgugger could I get assigned to this?

**Comment by stevhliu** [comment]
Thanks for the feedback and feel free to take this on if you're interested! 

If you have any questions about writing the docs, take a look at this guide [here](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation) :)

**Comment by rhelmeczi** [comment]
@Narsil Your suggestions are very helpful.

Adding separate documentation for each pipeline makes sense. For example, in the `TextClassificationPipeline` the keyword arguments are both keyword arguments for the tokenizer's call function, and keyword arguments for the `postprocess` function. I think even a brief statement along the lines of (but not necessarily identical to):

> keyword arguments passed to `TextClassificationPipeline.tokenizer.__call__` and `TextClassificationPipeline.postprocess`

where the function names are clickable would be extremely helpful. Simply pointing to the recipient functions also makes this a beginner friendly task. I'm assuming of course that for each pipeline, the keyword arguments are only ever passed along to other functions. 

Getting caught up on the documentation should probably be done over several commits: adding one commit at a time for each of the specific pipelines will be much easier to review, that's just my two cents though.

@DIvkov575 Keeping in mind that I'm not a maintainer of this repository, and therefore keeping in mind that my above suggestions are not necessarily ones that will be accepted, you can feel free to add documentation if you feel up to it.

**Comment by Narsil** [comment]
> Getting caught up on the documentation should probably be done over several commits: adding one commit at a time for each of the specific pipelines will be much easier to review, that's just my two cents though.

I'll go even further, 1 PR per change is the easiest course of action ! Makes it easier to review, and if for some reason one change is more debated is doesn't prevent the other from going in.
