### ISSUE TITLE
Using GPT-2 XL

### ISSUE THREAD

**Issue by IrvDelgado** [huggingface/transformers#1932]
Hi, Im trying to use the pretrained gpt-xl
but I get the following error: 
OSError: Model name 'gpt2-xl' was not found in tokenizers model name list (gpt2, gpt2-medium, gpt2-large, distilgpt2). We assumed 'gpt2-xl' was a path or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.

Im following an example from the documentation. 

      7 # Load pre-trained model tokenizer (vocabulary)
---> 8 tokenizer = GPT2Tokenizer.from_pretrained('gpt2-xl')
      9 # Load pre-trained model (weights)
     10 model = GPT2LMHeadModel.from_pretrained('gpt2-xl')
Any Idea why?

Thank you. :)

**Comment by TheEdoardo93** [comment]
You don't have to use the PyPi version of this library, but **from the source code** with `pip install git+https://github.com/huggingface/transformers.git`.

After that, you're able to use OpenAI GPT-2 XL version as always, e.g.
```
import transformers
from transformers import GPT2Tokenizer
from transformers import GPT2Model

tokenizer = GPT2Tokenizer.from_pretrained('gpt2-xl')
model = GPT2Model.from_pretrained('gpt2-xl')
...
```

Please, close this issue!

> Hi, Im trying to use the pretrained gpt-xl
> but I get the following error:
> OSError: Model name 'gpt2-xl' was not found in tokenizers model name list (gpt2, gpt2-medium, gpt2-large, distilgpt2). We assumed 'gpt2-xl' was a path or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.
> 
> Im following an example from the documentation.
> 
> ```
>   7 # Load pre-trained model tokenizer (vocabulary)
> ```
> 
> ---> 8 tokenizer = GPT2Tokenizer.from_pretrained('gpt2-xl')
> 9 # Load pre-trained model (weights)
> 10 model = GPT2LMHeadModel.from_pretrained('gpt2-xl')
> Any Idea why?
> 
> Thank you. :)
