### ISSUE TITLE
Misspelled docstring for ensure_valid_input function

### ISSUE THREAD

**Issue by Bearnardd** [huggingface/transformers#19362]
### System Info

- `transformers` version: 4.23.0.dev0
- Platform: Linux-5.4.0-126-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.10.0
- PyTorch version (GPU?): 1.12.1+cu102 (False)
- Tensorflow version (GPU?): 2.10.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.6.0 (cpu)
- Jax version: 0.3.6
- JaxLib version: 0.3.5
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@sgugger

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```{code}
def ensure_valid_input(model, tokens, input_names):
    """
    Ensure input are presented in the correct order, without any Non

    Args:
        model: The model used to forward the input data
        tokens: BatchEncoding holding the input data
        input_names: The name of the inputs

    Returns: Tuple

    """
```

### Expected behavior

It is a really tiny tiny detail but when I was going through `convert_graph_to_onnx.py` file I noticed that there is a misspelled docstring for `ensure_valid_input` function. Namely, I believe that `"Ensure input are ..."` should be `"Ensure inputs are ...`.

**Comment by sgugger** [comment]
Looks wrong indeed. Would you like to open a PR to fix it?

**Comment by Bartekkz** [comment]
@sgugger sure, I will take care of that tomorrow.
