### ISSUE TITLE
how to output the last layer of TFBertForSequenceClassification?

### ISSUE THREAD

**Issue by roccqqck** [huggingface/transformers#1936]
how to output the last layer of TFBertForSequenceClassification?

I want to output the layer before classifier (Dense) 

```
Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
bert (TFBertMainLayer)       multiple                  102267648 
_________________________________________________________________
dropout_37 (Dropout)         multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  3845      
=================================================================
Total params: 102,271,493
Trainable params: 102,271,493
Non-trainable params: 0
```

I tried tf.keras function
```
dense1_layer_model = Model(inputs=model.input, outputs=model.get_layer('bert').output)
```

It didnt worked.

**Comment by TheEdoardo93** [comment]
Please, copy and paste the source code in order to reproduce your problem.

> how to output the last layer of TFBertForSequenceClassification?
> 
> I want to output the layer before classifier (Dense)
> 
> ```
> Model: "tf_bert_for_sequence_classification"
> _________________________________________________________________
> Layer (type)                 Output Shape              Param #   
> =================================================================
> bert (TFBertMainLayer)       multiple                  102267648 
> _________________________________________________________________
> dropout_37 (Dropout)         multiple                  0         
> _________________________________________________________________
> classifier (Dense)           multiple                  3845      
> =================================================================
> Total params: 102,271,493
> Trainable params: 102,271,493
> Non-trainable params: 0
> ```
> 
> I tried tf.keras function
> 
> ```
> dense1_layer_model = Model(inputs=model.input, outputs=model.get_layer('bert').output)
> ```
> 
> It didnt worked.

**Comment by roccqqck** [comment]
> Please, copy and paste the source code in order to reproduce your problem.
this is my original code
```
model = TFBertForSequenceClassification.from_pretrained('bert-base-chinese', num_labels=5)
model.summary()
```
```
Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
bert (TFBertMainLayer)       multiple                  102267648 
_________________________________________________________________
dropout_37 (Dropout)         multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  3845      
=================================================================
Total params: 102,271,493
Trainable params: 102,271,493
Non-trainable params: 0
```

**Comment by roccqqck** [comment]
I tried this
```
model = TFBertModel.from_pretrained('bert-base-chinese')
model.add( Dropout(0.5))
model.add( Dense(5,activation="softmax") )
model.summary()
```
```AttributeError: 'TFBertModel' object has no attribute 'add'```

**Comment by roccqqck** [comment]
I tried this too
```
model = Sequential()
model.add( TFBertModel.from_pretrained('bert-base-chinese') )
model.add( Dropout(0.5))
model.add( Dense(5,activation="softmax") )
model.summary()
```
```
ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.
```

**Comment by roccqqck** [comment]
I also tried this
```
model = Sequential()
model.add( TFBertMainLayer(BertConfig()) )
model.add( Dropout(0.5))
model.add( Dense(5,activation="softmax") )
model.summary()
```
```
ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.
```

**Comment by roccqqck** [comment]
```
bert = TFBertMainLayer(BertConfig())
flat = Flatten()(bert)
classifier = Dense(5,activation="softmax")(flat)

model = Model(inputs=bert, outputs=classifier)
model.summary()
```
```
'TFBertMainLayer' object has no attribute 'shape'
```

**Comment by TheEdoardo93** [comment]
In order to create a Sequential model with TensorFlow.Keras framework, you have to specify the input shape through `input_shape` parameter on the input layer, otherwise TensorFlow.Keras doesn't know the input shape of the model you're creating.

**Comment by roccqqck** [comment]
> In order to create a `Sequential` model with TensorFlow.Keras framework, you have to specify the input shape through `input_shape` 

```
model = Sequential()
model.add( Input(shape = (512,)) )
model.add( TFBertModel.from_pretrained('bert-base-chinese') )
model.add( Dropout(0.5))
model.add( Dense(5,activation="softmax") )
model.summary()
```
```
TypeError: Value passed to parameter 'indices' has DataType float32 not in list of allowed values: int32, int64
```

**Comment by roccqqck** [comment]
```
model = Sequential()
model.add( InputLayer(input_shape = (512,)) )
model.add( TFBertModel.from_pretrained('bert-base-chinese') )
model.add( Dropout(0.5))
model.add( Dense(5,activation="softmax") )
model.summary()
```

```
TypeError: Value passed to parameter 'indices' has DataType float32 not in list of allowed values: int32, int64
```




> In order to create a `Sequential` model with TensorFlow.Keras framework, you have to specify the input shape through `input_shape` parameter on the input layer, otherwise TensorFlow.Keras doesn't know the input shape of the model you're creating.

**Comment by roccqqck** [comment]
> In order to create a `Sequential` model with TensorFlow.Keras framework, you have to specify the input shape through `input_shape` 

```
input_layer = Input(shape = (512,), dtype='int64')
bert = TFBertModel.from_pretrained('bert-base-chinese')(input)
flat = Flatten()(bert)
classifier = Dense(5,activation="softmax")(flat)
model = Model(inputs=input_layer, outputs=classifier)
model.summary()
```

```
Layer flatten_8 expects 1 inputs, but it received 2 input tensors. Inputs received: [<tf.Tensor 'tf_bert_model_8/Identity:0' shape=(None, 512, 768) dtype=float32>, <tf.Tensor 'tf_bert_model_8/Identity_1:0' shape=(None, 768) dtype=float32>]
```

**Comment by roccqqck** [comment]
> In order to create a `Sequential` model with TensorFlow.Keras framework, you have to specify the input shape through `input_shape` parameter on the input layer, otherwise TensorFlow.Keras doesn't know the input shape of the model you're creating.

```
input_layer = Input(shape = (512,), dtype='int64')
bert = TFBertModel.from_pretrained('bert-base-chinese')(input_layer)
bert = bert[0]
flat = Flatten()(bert)
classifier = Dense(units=5)(flat)
model = Model(inputs=input_layer, outputs=classifier)
model.summary()
```
```
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_4 (InputLayer)         [(None, 512)]             0         
_________________________________________________________________
tf_bert_model_3 (TFBertModel ((None, 512, 768), (None, 102267648 
_________________________________________________________________
flatten_2 (Flatten)          (None, 393216)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 1966085   
=================================================================
Total params: 104,233,733
Trainable params: 104,233,733
Non-trainable params: 0
```


thanks it worked!!!




```
optimizer = tf.keras.optimizers.Adam(learning_rate=3e-5, epsilon=1e-08, clipnorm=1.0)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
model.compile(optimizer=optimizer, loss=loss, metrics=[metric])

model_fit = model.fit(train_input_ids, train_label, 
                      batch_size=4, epochs=4, 
                      validation_data=(validation_input_ids, validation_label)
                   )
```

**Comment by sainimohit23** [comment]
Hi @roccqqck, I am also doing something similar. Most of my queries are cleared by your comment. I have just one more doubt. The (documentation)[https://huggingface.co/transformers/model_doc/bert.html#tfbertforsequenceclassification] states that the input of model should look like this `[input_ids, attention_mask]`. So, are you providing attention mask as input?

Have you uploaded full the code mentioned above on your github with data? If yes, can you please share the link?

**Comment by roccqqck** [comment]
@sainimohit23 
I didn’t provide attention mask.

**Comment by aollagnier** [comment]
Hi, 
I am doing something similar to your models it works but when I try to get prediction on new data I am always getting 0 as output label. If you would have a look on my [colab](https://colab.research.google.com/drive/1qq1P3Nug63gqg927tQRmuR4oZfqDAyY6#scrollTo=v7HK_JC-8lJB)

I don't know what 's wrong.

Thanks

**Comment by aollagnier** [comment]
Hi, 
I am trying to reproduce your model and it runs smoothly, however I am always getting 0 as output label. Could you please let me know what's wrong in [my code](https://colab.research.google.com/drive/18HYwffkXCylPqeA-8raL82vfwOjb-aLP).

Thanks
