### ISSUE TITLE
access to the vocabulary

### ISSUE THREAD

**Issue by weiguowilliam** [huggingface/transformers#1937]
## ❓ Questions & Help

Is there any way we can get access to the vocabulary in GPT2? Like a list: [subtoken1, subtoken2, ...subtoken 10000...]

Thank you in advance!

**Comment by TheEdoardo93** [comment]
You can obtain the **50.257 different tokens** with the following code:
```
import transformers
from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
vocab = list(tokenizer.encoder.keys())
assert(len(vocab) == tokenizer.vocab_size) # it returns True!
```

**Comment by weiguowilliam** [comment]
thank you！
