### ISSUE TITLE
DeformableDetrForObjectDetection is not supported

### ISSUE THREAD

**Issue by Eggwardhan** [huggingface/transformers#19375]
### System Info

when I use
`conda create -n hug numpy matplotlib transformers python=3.8` and activated hug env, or just use `pip install transformers` ,I got the same result

```
(hug) root@e:/# python
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import AutoFeatureExtractor, DeformableDetrForObjectDetection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DeformableDetrForObjectDetection' from 'transformers' (/opt/miniconda3/envs/hug/lib/python3.8/site-packages/transformers/__init__.py)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1.conda create -n hug numpy matplotlib transformers python=3.8
2.conda activate hug
3.from transformers import AutoFeatureExtractor, DeformableDetrForObjectDetection

### Expected behavior

Can any one tell me why?

**Comment by NielsRogge** [comment]
Hi,

Deformable DETR is not yet available in a PyPi release. For now, you have to install the library from source:

pip install -q git+https://github.com/huggingface/transformers.git
