### ISSUE TITLE
fill-mask with roberta-base and --targets options

### ISSUE THREAD

**Issue by felgaet** [huggingface/transformers#19379]
Dear @sgugger,
I was trying to use the fill-mask function starting from "roberta-base" and limiting the search to target words using the --targets option.
For numerous target words, however, I get the warning that the word does not exist in the vocabulary.

An example is followed:
```
from transformers import pipeline

unmasker = pipeline('fill-mask', model="roberta-base", tokenizer="roberta-base", top_k=10)
filled = unmasker("When I am hungry, I eat a <mask>.", targets=["pizza", "banana", "pasta"])
for r in filled:
    print(r['token_str'], "->", r['score'])

```
The output is:

```
The specified target token `pizza` does not exist in the model vocabulary. Replacing with `p`.
The specified target token `banana` does not exist in the model vocabulary. Replacing with `ban`.
The specified target token `pasta` does not exist in the model vocabulary. Replacing with `past`.
p -> 1.0362288094256655e-07
ban -> 1.0942345918252272e-09
past -> 5.667477598336745e-10
```

This problem does not exist with BERT:
```
pizza -> 0.0014738412573933601
banana -> 0.0009286535205319524
pasta -> 1.1728033314284403e-05
```
Could you explain to me the reason for this behaviour? How can I fix it?

**Comment by sgugger** [comment]
Hi there! Please use the [forums](https://discuss.huggingface.co/) for such questions as we keep issues for bugs and feature requests only. In this instance, it's because RoBERTa uses a different tokenization algorithm than BERT which mark the beginning of each word with a special symbol.

**Comment by felgaet** [comment]
Thanks!
