### ISSUE TITLE
Load output file from fine-tuned bert language model

### ISSUE THREAD

**Issue by avinashsai** [huggingface/transformers#1938]
Hi,
I have fine-tuned bert cased language model using **run_lm_finetuning.py**. 'output' is the output file directory and '**bert-base-cased.txt**' is another file created by the model.

1. Does the .txt file mentioned has the output of fine-tuned model??
2. If so, how should I open the file?? I am getting 'UTF-8' encoding issue with the file.

Thank you.

**Comment by LysandreJik** [comment]
Hmm this script should not output any `.txt` files except `eval_results.txt`. What is inside this output directory except for this file?

**Comment by avinashsai** [comment]
I didn't provide any evaluation file.
However logging info is as follows:

- Creating features from dataset file at 
- Saving features into cached file **bert-base-cased_cached_lm_32.txt**
