### ISSUE TITLE
`device_map="auto"` fails for GPT2 on CPU

### ISSUE THREAD

**Issue by dirkgr** [huggingface/transformers#19399]
### System Info

Python 3.9, Mac, `transformers==4.21.3`

### Who can help?

@patil-suraj, @patrickvonplaten, @LysandreJik

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

On a box with no GPUs:

```Python
transformers.AutoModelForCausalLM.from_pretrained("gpt2", device_map="auto")
```

### Expected behavior

I'd expect a model. I get an exception.

**Comment by dirkgr** [comment]
Workaround: Don't use `device_map` on CPU 🤷🏻

**Comment by LysandreJik** [comment]
cc @sgugger

**Comment by sgugger** [comment]
Yes, `device_map="auto"` is not supported in CPU only environments.

**Comment by sgugger** [comment]
Should be supported now on the main branch of Accelerate!

**Comment by dirkgr** [comment]
Yay!
