### ISSUE TITLE
git@github.com: Permission denied (publickey) when fetching

### ISSUE THREAD

**Issue by iedmrc** [huggingface/transformers#1943]
When you wanted to sync forked repository with base, as described [here](https://github.com/huggingface/transformers/blame/aa92a184d2b92faadec975139ad55e2ae749362c/CONTRIBUTING.md#L140)

You get:
```
➜  transformers (master) ✗ git fetch upstream
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
[This](https://stackoverflow.com/a/34081606) solution introduced on stackoverflow fixes the problem. [This](https://stackoverflow.com/questions/13509293/git-fatal-could-not-read-from-remote-repository#comment85002398_34081606) one also says: 

> If the repo owner has not set up ssh keys then you will likely have this issue. The fix as indicated is to use https instead, or have the repo owner set up ssh

Could you please fix this (by setting up ssh?), in order to make contributing easy?
Thanks!

**Comment by julien-c** [comment]
Yeah you can clone using https, it's usually easier (github actually recommends it for simple workflows)

cc @rlouf

**Comment by iedmrc** [comment]
Nice! Then if GitHub encourages https instead of ssh, we could update [this line](https://github.com/huggingface/transformers/blame/5d3b8daad2cc6287d30f03f8a96d0a1f7bc8d0dc/CONTRIBUTING.md#L109) on README.md ?

**Comment by rlouf** [comment]
Thanks for pointing this out, I just made the change.
