### ISSUE TITLE
OWL-ViT

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [huggingface/transformers#19448]
### Feature request

Dear all,

It looks like [OWL-ViT](https://huggingface.co/docs/transformers/model_doc/owlvit) doesn't support image conditioned detection.

### Motivation

 Image conditioned detection is the most appealing feature of this model

### Your contribution

No, just pointing this out. Thanks

**Comment by NielsRogge** [comment]
Hi Francesco, this feature was already asked and a PR to add this feature can be found here: #18891

**Comment by FrancescoSaverioZuppichini** [comment]
nice, thanks @NielsRogge
