### ISSUE TITLE
When using the Bert model

### ISSUE THREAD

**Issue by bigzhouj** [huggingface/transformers#1945]
## ❓ Questions & Help

pregenerate_training_data.py and  finetune_on_pregenerated.py Is it in the project.If so, where?

**Comment by TheEdoardo93** [comment]
These two files are **not** in the Transformers library.
What do they do? And for what goal you want to use these scripts?

> ##  Questions & Help
> pregenerate_training_data.py and finetune_on_pregenerated.py Is it in the project.If so, where?

**Comment by LysandreJik** [comment]
As @TheEdoardo93 says, these files were community maintained and have been removed a few months ago.

**Comment by ritwikmishra** [comment]
so what is the procedure to fine tune BERT on my data?
