### ISSUE TITLE
Original image from Trocr Processor

### ISSUE THREAD

**Issue by dranreb1660** [huggingface/transformers#19456]
Hi [@NielsRogge, I am following your TrOCR finetuning with PyTorch but I have two questions: The processor resizes the image from 1700 x 134 to 384 x384, 1) is there a way to maintain the height of the original image or even use a custom dimension for training, eg. 512 x 134. and 2) is there a way to get the original image back for logging purposes as the processed image is unrecognizable after those basic augmentations. Thanks

**Comment by NielsRogge** [comment]
Hi,

This question is answered on our forum: https://discuss.huggingface.co/t/get-original-image-from-trocr-processor/24224/2
