### ISSUE TITLE
Suppress warning when using `DataCollatorForSeq2Seq`

### ISSUE THREAD

**Issue by pietrolesci** [huggingface/transformers#19471]
### Feature request

When using a fast tokenizer in the `DataCollatorForSeq2Seq`, currently the following warning is printed 

```
You're using a T5TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
```

As a temporary solution, what is the suggested way to suppress it?

Is there any plan to update `DataCollatorForSeq2Seq`?

Thanks a lot in advance for your help!

### Motivation

N/A

### Your contribution

N/A

**Comment by sgugger** [comment]
Could you post a clear reproducer of the issue? Thanks a lot!
