### ISSUE TITLE
BertForMultipleChoice

### ISSUE THREAD

**Issue by radu941208** [huggingface/transformers#1954]
## ❓ Questions & Help
Shape Error when using BrtForMultipleChoice

![image](https://user-images.githubusercontent.com/26097066/69660490-0ff9b680-1046-11ea-89a3-fa60b769be97.png)

Below is the model i used:

![image](https://user-images.githubusercontent.com/26097066/69660530-26a00d80-1046-11ea-9cbd-b71d56a8bd22.png)

**Comment by LysandreJik** [comment]
Hi, could you try and test this on a more recent version of the library? `pytorch_pretrained_BERT` is not supported anymore.
