### ISSUE TITLE
Image Format (BGR/RGB) bug for lxmert example

### ISSUE THREAD

**Issue by lvyiwei1** [huggingface/transformers#19601]
### System Info

Repository code (accessed 10/13/2022) in examples/research_projects/lxmert

### Who can help?

@LysandreJik 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run demo.ipynb in examples/research_project/lxmert (or instead use [this colab notebook](https://colab.research.google.com/drive/1N0z-mplcu-20TZPr7-TNkZUCASmmP90i?usp=sharing))
but instead of using an URL, upload arbitrary jpg image and do local file
(i.e. change line `frcnn_visualizer = SingleImageViz(URL,id2obj=objids, id2attr=attrids)` 
to `frcnn_visualizer = SingleImageViz('pic.jpg',id2obj=objids, id2attr=attrids)` where `pic.jpg` is arbitrary jpg file you have)
Then the result will have flipped red and blue colors

### Expected behavior

The result have flipped red and blue colors.
Technically, the image inputed to frcnn is RGB instead of BGR (but frcnn uses BGR), so this is probably due to doing BGR2RGB one extra time in the image preprocessing step.

### Source

This bug was discovered through [MultiViz paper](https://arxiv.org/pdf/2207.00056.pdf)

**Comment by sgugger** [comment]
Note that we do not maintain the research project examples, so you will have better luck pinging the original author :-)
