### ISSUE TITLE
Tokenizer not loaded for image-to-text pipelines when specified

### ISSUE THREAD

**Issue by davidmezzetti** [huggingface/transformers#19627]
### System Info

Transformers 4.23.1

### Who can help?

@Narsil 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import pipeline
nlp = pipeline("image-to-text", model="ydshieh/vit-gpt2-coco-en", tokenizer="ydshieh/vit-gpt2-coco-en")
nlp("image.jpg")
```

Results in:

```
  File "transformers/pipelines/image_to_text.py", line 89, in postprocess
    "generated_text": self.tokenizer.decode(
AttributeError: 'str' object has no attribute 'decode'
```

### Expected behavior

Caption to be returned.

It appears something around this line is being tripped up - https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/__init__.py#L733

**Comment by sgugger** [comment]
cc @Narsil

**Comment by Bearnardd** [comment]
If that is an unexpected issue, I can debug it and try to fix.

**Comment by davidmezzetti** [comment]
Thanks @narsil. In reviewing the way I'm calling pipelines, there is no reason to pass both a `model` and `tokenizer` as they are the same.

It appears that this line: https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/__init__.py#L737 could be updated to also check if the tokenizer is a (str, tuple) for multi models. But it seems like a highly niche/possibly unnecessary use case.

**Comment by davidmezzetti** [comment]
Sounds good, I'll go ahead and close this issue.
