### ISSUE TITLE
How to increase model saving checkpoint from 50 to 1000?

### ISSUE THREAD

**Issue by snijesh** [huggingface/transformers#1964]
## ❓ Questions & Help

When I run the script `run_squad.py` , it creates model check points every 50th iteration. How to increase model saving checkpoint from 50 to 1000. Where should I edit the code ?

**Comment by TheEdoardo93** [comment]
You haven't to modify the source code in this script. When you call `run_squad.py` script, you have to pass the `--save_steps` parameter and set its value to 1000. So, the entire command would be something like that:
`python run_squad.py ... --save_steps 1000`

Please, close this issue!

> ##  Questions & Help
> When I run the script `run_squad.py` , it creates model check points every 50th iteration. How to increase model saving checkpoint from 50 to 1000. Where should I edit the code ?

**Comment by tomohideshibata** [comment]
Related to this question, how about making the default value (50) bigger (e.g., 1000) in scripts such as `run_squad.py` and `run_ner.py`?
If a `--save_steps` option is not specified, and the default value is used, many checkpoints are saved.

**Comment by LysandreJik** [comment]
@tomohideshibata you're right that 50 is too low, I bumped it to 500 in 335dd5e.

**Comment by tomohideshibata** [comment]
Thanks!
