### ISSUE TITLE
'WhisperProcessor' object has no attribute 'as_target_processor'

### ISSUE THREAD

**Issue by GaetanBaert** [huggingface/transformers#19672]
### System Info

- `transformers` version: 4.23.1
- Platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.17
- Python version: 3.8.12
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.11.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@patrickvonplaten

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I'm trying to train a Whisper model, using the WhisperProcessor. 

As written in the doc of the `__call__` method of the WhisperProcessor, I should have a context processor.as_target_processor() but it seems it doesn't exist. 
"If used in the context ~WhisperProcessor.as_target_processor this method forwards all its arguments to WhisperTokenizer’s [call()]"

Steps to reproduce the bug : 
```
target_text = 'this is a test text'
processor = WhisperProcessor.from_pretrained('openai/whisper-large')
with processor.as_target_processor():
    targets = processor(target_text).input_ids
```

### Expected behavior

The `__call__` method of WhisperProcessor instance in the as_target_processor context should give the result of the WhisperTokenizer `__call__`.

**Comment by NielsRogge** [comment]
Hi,

We'll update that code snippet as we've recently deprecated the use of `as_target_processor`, and new processors like `WhisperProcessor` don't implement it anymore. See #18325 for details.

You can replace

```
text = "hello world"

with processor.as_target_processor():
    encoded_labels = processor(text, padding=True)
```
by 
```
encoded_labels = processor(text=text).input_ids
```

**Comment by NielsRogge** [comment]
Also cc'ing @ArthurZucker for updating the docs

**Comment by GaetanBaert** [comment]
Hello, 
Thank you for clarification !

**Comment by GaetanBaert** [comment]
Another thing, it seems that the `pad` method does not exist for WhisperProcessor ?

**Comment by ArthurZucker** [comment]
Nice catch! Will update the doc soon
