### ISSUE TITLE
AlbertPreTrainedModel class is not available in release v2.2.0

### ISSUE THREAD

**Issue by FacingBugs** [huggingface/transformers#1968]
## ❓ Questions & Help

In the release v2.2.0, the AlbertForSequenceClassification class inherits the AlbertPreTrainedModel class as "class AlbertForSequenceClassification(AlbertPreTrainedModel)". 

However, in the doc, this pre-trained model is not documented. And in the released v2.2.0 transformer, the AlbertPreTrainedModel class is not available to be imported. 

This is not a big issue since we can use BertPreTrainedModel class instead (like RoBERTa). But it should be consistent. Especially in the doc under Albert, there is a class called TFBertForPretraining which makes confusion for users.

**Comment by LysandreJik** [comment]
Hi, indeed there was a mistake with `TFBertForPretraining` referenced under the ALBERT documentation. This was fixed with 3616209.

The `PreTrainedModel` class is not available for ALBERT, which is the same for CTRL, GPT, GPT-2, DistilBERT, CamemBERT, TransformerXL, XLM and XLNet. 

Why is that class useful for your use-case, seeing as it's a simple wrapper over `PreTrainedModel` with a few overridden attributes?

**Comment by FacingBugs** [comment]
> Hi, indeed there was a mistake with `TFBertForPretraining` referenced under the ALBERT documentation. This was fixed with [3616209](https://github.com/huggingface/transformers/commit/361620954acf16b27727d763a591257b03f90b5d).
> 
> The `PreTrainedModel` class is not available for ALBERT, which is the same for CTRL, GPT, GPT-2, DistilBERT, CamemBERT, TransformerXL, XLM and XLNet.
> 
> Why is that class useful for your use-case, seeing as it's a simple wrapper over `PreTrainedModel` with a few overridden attributes?

I completely agree we can use PreTrainedModel or BertPreTrainedModel instead.
 
The question is that I do see the implementation of the class AlbertPreTrainedModel(PreTrainedModel)  in the source code (transformers/modeling_albert.py line 313) but I cannot import it. It seems that it is not included in the released version. I just feel it is weird.

**Comment by LysandreJik** [comment]
Yes, it is not importable as it is an internal used by different models, but I fail to see a use-case where it would be useful for the library users.

Why is that class useful for your use-case, seeing as it's a simple wrapper over `PreTrainedModel` with a few overridden attributes?

**Comment by thomwolf** [comment]
I think we could add all the `XXXPretrainedModel` in `__init__` indeed. Would make it easier for people to build custom-made models that can load pretrained checkpoints as well.

**Comment by thomwolf** [comment]
Fixed on master
