### ISSUE TITLE
Make use of KenLM's pypi version

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#19686]
### Feature request

Use PyPi version of KenLM instead of installing archieve file from Github.

### Motivation

Now that kenlm is on pypi: https://github.com/kpu/kenlm/issues/363#issuecomment-1280050903 let's use it :-) 

### Your contribution

@sanchit-gandhi would you give this a try as an exercise to see how we deal with soft dependencies in Transformers maybe? :-) 

I think we can now update the `setup.py` file to include the pypi version of `kenlm` and remove all those `pip install https://github.com/kpu/kenlm/archive/master.zip` statements  e.g. in https://github.com/huggingface/transformers/blob/c7edde1a692012eda23bc2b837588557b97ad729/docker/transformers-all-latest-gpu/Dockerfile#L44

I'd also advocate to add a `is_kenlm_available` flag to give a nice error message and update warnings / errors here: https://github.com/huggingface/transformers/blob/c7edde1a692012eda23bc2b837588557b97ad729/src/transformers/pipelines/__init__.py#L839

**Comment by patrickvonplaten** [comment]
Also cc @ydshieh and @sgugger here

**Comment by sgugger** [comment]
And let's not forget the [circleCI config](https://github.com/huggingface/transformers/blob/c7edde1a692012eda23bc2b837588557b97ad729/.circleci/create_circleci_config.py#L130) as well ;-)

**Comment by raghavanone** [comment]
@patrickvonplaten I would like to pick up this.
