### ISSUE TITLE
trying fine-tuning Reformer on Squad2 dataset from pre-trained model "google/crime-and-punishment".

### ISSUE THREAD

**Issue by FrancescoTroiano** [huggingface/transformers#19708]
I'm trying fine-tuning Reformer on Squad2 dataset from pre-trained model "google/crime-and-punishment". 
Using tok.cls_token = tok.pad_token, I have the following error:  
![image](https://user-images.githubusercontent.com/75449189/196391419-7387c255-cc07-4f81-975d-da544fef95c4.png)
So I add tok.pad_token = tok.eos_token, but I have a new error: 2 is not in list.
can someone help me? Thank you

_Originally posted by @FrancescoTroiano in https://github.com/huggingface/transformers/issues/5436#issuecomment-1282092684_

**Comment by sgugger** [comment]
Please follow the template to file your issue or ask your question on the [forums](https://discuss.huggingface.co/).

**Comment by FrancescoTroiano** [comment]
Ok, thank you. I open a discussion in the forum in the Transformers category about that
