### ISSUE TITLE
How to persist cloud-based transformers

### ISSUE THREAD

**Issue by jmwoloso** [huggingface/transformers#1972]
## ❓ Questions & Help

I'm using this repo in the cloud and attempting to persist the model fails as it seems HDF5 and thus h5py doesn't support that paradigm per https://github.com/h5py/h5py/issues/925

What is the recommended method of saving the model in this scenario? Thanks!

**Comment by TheEdoardo93** [comment]
Are you trying to serialize which type of model to .hdf5 file? A pre-trained model such as BertFor* or a custom model trained with Transformers?

> ##  Questions & Help
> I'm using this repo in the cloud and attempting to persist the model fails as it seems HDF5 and thus h5py doesn't support that paradigm per [h5py/h5py#925](https://github.com/h5py/h5py/issues/925)
> 
> What is the recommended method of saving the model in this scenario? Thanks!

**Comment by jmwoloso** [comment]
Hi @TheEdoardo93. I'm trying serialize TFBertFor*
