### ISSUE TITLE
How can I install transformers v2.11.0?

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/transformers#19737]
### System Info

Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hello. I want to use https://github.com/xashru/punctuation-restoration

It requires specific version of transformers  v2.11.0?

First of all which specific version of Python is best for this version of transformers?

Secondly I have installed Python 3.5.4 and testing like this but it fails to install

So how can I install it?

Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32

```
C:\python355\Scripts>pip.exe install transformers==v2.11.0
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement transformers==v2.11.0
ERROR: No matching distribution found for transformers==v2.11.0

C:\python355\Scripts>
```

![image](https://user-images.githubusercontent.com/19240467/196563990-75a8193b-e5bc-4810-9ad4-e9b20b08e188.png)

**Comment by gante** [comment]
Hey @FurkanGozukara -- try running `pip.exe install transformers==2.11.0` (i.e. removing the `v`)

Also, please note that this is a very old version. We highly encourage you to use a more recent version in your project if possible!
