### ISSUE TITLE
How to make gpt2 accurately tokenize lowercase entities?

### ISSUE THREAD

**Issue by ahxchzt** [huggingface/transformers#19740]
Many datasets pre-lowercase their text content, so some entities are lowercase in these datesets, like:

**"paris"**

For GPT2Tokenizer, it can tokenize "Paris" to "Paris" but it tokenizes **"paris" to "par" and "is".** 
How to fix it? Is there a uncased GPT2?
Thanks!

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for such questions, as we keep the issues for bugs and feature requests only.
