### ISSUE TITLE
How can we view different versions of documentation?

### ISSUE THREAD

**Issue by drydenb** [huggingface/transformers#1975]
## ❓ Questions & Help

How can I select a specific version of transformers in the documentation located here: https://huggingface.co/transformers/index.html?

**Comment by LysandreJik** [comment]
We're in the process of building better versioned documentation with easier links to follow, but at the moment the different versions are accessible in the [README](https://github.com/huggingface/transformers#state-of-the-art-natural-language-processing-for-tensorflow-20-and-pytorch), right before the `installation` section.

**Comment by drydenb** [comment]
Great, thank you!
