### ISSUE TITLE
Why this dummpy input is not consistent with pytorch

### ISSUE THREAD

**Issue by MichaleDong** [huggingface/transformers#19762]
https://github.com/huggingface/transformers/blob/bd469c40659ce76c81f69c7726759d249b4aef49/src/transformers/models/layoutlmv3/modeling_tf_layoutlmv3.py#L988

The dummpy input of pytorch layoutlmv3 is like this, from transformers.utils:
https://github.com/huggingface/transformers/blob/v4.23.1/src/transformers/modeling_utils.py#L954 

from transformers.utils import DUMMY_INPUTS
>>> print(DUMMY_INPUTS)
[[7, 6, 0, 0, 1], [1, 2, 3, 0, 0], [0, 0, 0, 4, 5]]

**Comment by sgugger** [comment]
Hi there! Please ask questions like this on the [forums](https://discuss.huggingface.co/), as we keep issues for bugs and feature requests only.
