### ISSUE TITLE
'convert_tf_checkpoint_to_pytorch.py' file is missing

### ISSUE THREAD

**Issue by imayachita** [huggingface/transformers#1977]
Hi all,
I pre-trained BERT base model on my domain-specific corpus using ```https://github.com/google-research/bert```  ```create_pretraining_data.py``` and ```run_pretraining.py```.
Now, I want to use it with this ```pytorch-transformers```. I saw from this page https://devhub.io/repos/huggingface-pytorch-pretrained-BERT that there is conversion script from tf checkpoints to ```pytorch_model.bin``` called ```convert_tf_checkpoint_to_pytorch.py``` but the file no longer exists.
Does anyone have solution? Thanks!

**Comment by TheEdoardo93** [comment]
PyTorch-pretrained-BERT is a older name of this library; now its name is Transformers.
You can check the latest docs of the library and install it from PyPi with `pip install transformers` (you have to install manually TensorFlow 2.0 and PyTorch as well through `pip install tensorflow=2.0.0` and `pip install torch`).

Said this, you can read [this](https://github.com/huggingface/transformers/blob/17ea43cf985829634bd86b36b44e5410c6f83e36/transformers/convert_bert_original_tf_checkpoint_to_pytorch.py) Python script whose goal is to convert BERT original TensorFlow checkpoint to PyTorch. 

> Hi all,
> I pre-trained BERT base model on my domain-specific corpus using `https://github.com/google-research/bert` `create_pretraining_data.py` and `run_pretraining.py`.
> Now, I want to use it with this `pytorch-transformers`. I saw from this page https://devhub.io/repos/huggingface-pytorch-pretrained-BERT that there is conversion script from tf checkpoints to `pytorch_model.bin` called `convert_tf_checkpoint_to_pytorch.py` but the file no longer exists.
> Does anyone have solution? Thanks!

**Comment by imayachita** [comment]
Thanks @TheEdoardo93! I saved the pytorch dump as ```pytorch_model.bin``` in folder ```pretraining_output```

How can I load this new model?
When I called BertTokenizer ```tokenizer = BertTokenizer.from_pretrained('./pretraining_output/', do_lower_case=False)```

I got this message:
```Model name './pretraining_output/' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed './pretraining_output/vocab.txt' was a path or url but couldn't find any file associated to this path or url.```

Thanks!

**Comment by imayachita** [comment]
Thanks @TheEdoardo93!
