### ISSUE TITLE
Add Flan-T5 Checkpoints

### ISSUE THREAD

**Issue by chujiezheng** [huggingface/transformers#19782]
### Model description

Flan-T5 models are instruction-finetuned from the T5 v1.1 LM-adapted checkpoints. They can be directly used for few-shot prompting as well as standard fine-tuning. Here is the [paper](https://arxiv.org/abs/2210.11416).

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

* Paper: https://arxiv.org/abs/2210.11416
* Model implementation: same as T5 v1.1
* Model weights: https://github.com/google-research/t5x/blob/main/docs/models.md#flan-t5-checkpoints

**Comment by NielsRogge** [comment]
Cool! cc @patrickvonplaten

**Comment by NielsRogge** [comment]
FYI the conversion script can be found here: https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/convert_t5x_checkpoint_to_flax.py

**Comment by patrickvonplaten** [comment]
cc @younesbelkada @ArthurZucker one of you interested in taking it? :-)

**Comment by ArthurZucker** [comment]
Yes! On it 🤗

**Comment by NielsRogge** [comment]
They are available now: https://huggingface.co/models?search=flan-t5

**Comment by BalazsFeherUK** [comment]
Quick question: when I try to load any of the FLAN models:

`model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-small")`

I receive the following error: AttributeError: 'T5LayerFF' object has no attribute 'config'

I have transformers==4.18.0.

**Comment by ArthurZucker** [comment]
Hey @BalazsFeherUK feel free to open a new issue with the full trace of the error and ping me 🤗
