### ISSUE TITLE
Transformers for WebNLG tasks 

### ISSUE THREAD

**Issue by MathewAlexander** [huggingface/transformers#1981]
## ❓ Questions & Help

Can we leverage GPT-2 pre-trained model for WebNLG tasks ?http://webnlg.loria.fr/pages/challenge.html

The WebNLG challenge consists in mapping data to text
similar to what is being done in https://github.com/tyliupku/wiki2bio.

**Comment by nazmiasri95** [comment]
Actually I'm working on this right now. Interested to know as well if anyone else has done it.
Most probably this is possible.
