### ISSUE TITLE
ImportError: cannot import name 'PegasusTokenizer' from 'transformers' 

### ISSUE THREAD

**Issue by Sonali234** [huggingface/transformers#19825]
@patrickvonplaten 
Tried:
from transformers import PegasusTokenizer
import torch
Output:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_7943/3816365261.py in <cell line: 1>()
----> 1 from transformers import PegasusTokenizer
      2 import torch

ImportError: cannot import name 'PegasusTokenizer' from 'transformers'

**Comment by kventinel** [comment]
Can you check transformers version and update it, if too old?

It's work fine for me:
```
In [1]: from transformers import PegasusTokenizer

In [2]: import transformers

In [3]: transformers.__version__
Out[3]: '4.23.1'
```

**Comment by patrickvonplaten** [comment]
Gently pinging @ArthurZucker here

**Comment by ArthurZucker** [comment]
Hey, as mentioned you are probably using an old version of transformers. I am not able to reproduce this bug. You should use `transformers>=3.1` as `Pegasus` was first introduced in the [release 3.1](https://github.com/huggingface/transformers/releases?q=PegasusForConditionalGeneration&expanded=true)

**Comment by gkarozis** [comment]
Did you find any solution for this problem?

**Comment by Sonali234** [comment]
> Yes, as mentioned in my previous answer, updating `transformers` hugs

This worked for me. Thanks!

**Comment by gkarozis** [comment]
Thank you. It seems to work for me too!
