### ISSUE TITLE
data_collator.py:131: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow

### ISSUE THREAD

**Issue by FlorinAndrei** [huggingface/transformers#19822]
### System Info

- `transformers` version: 4.23.1
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@sgugger 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://colab.research.google.com/drive/1gK9iXBiIEmmt2OMq6wmxwcpslkchHJh-?usp=sharing

See the output of `trainer.train()`

### Expected behavior

The warning should not occur.

**Comment by sgugger** [comment]
Thanks for the report, the PR linked above should fix it.
