### ISSUE TITLE
support loading pretrained model from fsspec paths

### ISSUE THREAD

**Issue by leoleoasd** [huggingface/transformers#19834]
### Feature request

Make `from_pretrained` works with fsspec paths.

```
tokenizer = BartTokenizerFast.from_pretrained("hdfs://..../bert-base-uncased")
```

### Motivation

To make transformers suitable for usage in the cloud or in clusters where files should be stored in HDFS or S3.

### Your contribution

I'll be willing to submit a PR but `from_pretrained` is a very complicated function so I may need assistance.

**Comment by sgugger** [comment]
Thank you, but we're not interested in expanding support to other tools than the Hugging Face Hub :-)

**Comment by leoleoasd** [comment]
I'd like to use Hub too, but our cluster have no public internet access...

**Comment by NYcleaner** [comment]
> I'd like to use Hub too, but our cluster have no public internet access...

hai, can you  help  how  to load the pretrain model  from hdfs path

**Comment by leoleoasd** [comment]
Still no way to do that. I have to use pytorch_lightning's ModelCheckpoint callback to load & save.
You can pre-process your pretrained model into a pytorch `.py` file then load it with `torch.load(fsspec.open('xxx'))`.

**Comment by NYcleaner** [comment]
> 

thanks so much for your reply ,  can you teach more detail please ,thanks

**Comment by NYcleaner** [comment]
hha, I have got an simple solution without changing  the source code ,  just use spark submit :
--conf spark.yarn.dist.archives=hdfs://your_own_hdfs_path/your_pretraining_model.zip#your_pretraining_model

**Comment by chris-aeviator** [comment]
@NYcleaner thanks for this idea! How would you be loading (referencing) the model then inside the spark job? , as a hdfs://your_own... string ?

**Comment by pavibhai** [comment]
> @NYcleaner thanks for this idea! How would you be loading (referencing) the model then inside the spark job? , as a hdfs://your_own... string ?

In case you have not yet figured out. When you provide `--conf spark.yarn.dist.archives=hdfs://your_own_hdfs_path/your_pretraining_model.zip#your_pretraining_model` the archive is downloaded extracted and symlinked as `your_training_model` in the current directory. When passing the path you should be able to do just `./your_pretraining_model`.

**Comment by chris-aeviator** [comment]
That’s amazing - thanks for pointing it out!
