### ISSUE TITLE
ImportError: libssl.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by efima-ai** [huggingface/transformers#19844]
### System Info

Hi,

I get the following error when calling `from transformers import BertModel, BertTokenizer`.

The error:
`ImportError: libssl.so.3: cannot open shared object file: No such file or directory`

I tried the following (suggested in other similar threads):
- instead of conda installation, use pip
-  downgrade tokenizers package

Neither of those fixed the issue. Following versions were used:

- Python 3.8.13
- tokenizers 0.13.1
- transformers 4.23.1

Any ideas how to fix this?

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`from transformers import BertModel, BertTokenizer`

### Expected behavior

No ImportError is expeted.

**Comment by Misterion777** [comment]
Hey, same problem, how to fix this?

**Comment by theRealMachineWhisperer** [comment]
After install transformers with anaconda on Ubuntu 22 my scripts wont run anymore with tons of these ImportErrors: 
(ie.) libffi.so.7: cannot open shared object file: No such file or directory
Removed and created a new environment with fresh install of dependancies and its still broken. This software ruined my machine

**Comment by muhark** [comment]
Downgrading to `tokenizers=0.10.3` seems to work as an interim fix. The main issue appears to be from a conflict between some libraries (e.g. TF) requiring OpenSSL<=1.1.1, and tokenizers using OpenSSL3.

I think that this can be circumvented by using transformers from pip or source, although in my particular project conda/mamba is a stricter requirement.

Solution is basically discussed here: https://discuss.huggingface.co/t/importing-tokenizers-version-0-10-3-fails-due-to-openssl/17820/3

(@theRealMachineWhisperer, I can imagine your frustration, but please be kind to open source developers and try to frame your challenges constructively <3)

**Comment by layjain** [comment]
Downgrading the tokenizers leads to downgrading the transformers library as well; So if you needed to use a model/feature in the newer version, it would not work. I fixed this issue by using pip to install transformers (instead of conda).

**Comment by theRealMachineWhisperer** [comment]
Fixed my issue by running apt install libffi7

**Comment by gal0is** [comment]
> Downgrading the tokenizers leads to downgrading the transformers library as well; So if you needed to use a model/feature in the newer version, it would not work. I fixed this issue by using pip to install transformers (instead of conda).
thanks, i tried
pip install transformers
and it works.

**Comment by mbrotos** [comment]
> 

You can also try `pip install transformers --force-reinstall`

I've found this can help refresh dependency versions. Do note, there may be an underlying compatibility concern in your environment.
