### ISSUE TITLE
Import Error: cannot import name 'TFBertTokenizer' from 'transformers'

### ISSUE THREAD

**Issue by shabha7092** [huggingface/transformers#19857]
### System Info

Platform - Mac os
Python Version - 3.9.0
Tensorflow version - 2.10.0
Transformers version - 4.23.1 (Tried different version)

### Who can help?

 @LysandreJik

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

when i try to import TFBertTokenizer using the statement “from transformers import TFBertTokenizer” i come across the below error.

ImportError: cannot import name ‘TFBertTokenizer’ from ‘transformers’

I am able to import BertTokenizer though. Did something change ? If i recollect i was able to import TFBertTokenizer too in the past. i also happen to check the code base and the class TFBertTokenizer still exists as part of the transformer package

Steps to Reproduce:
1) pip install transformers
2) In a new shell execute the below statement
'from transformers import TFBertTokenizer'

### Expected behavior

TFBertTokenizer should be imported similar to BertTokenizer.

**Comment by sgugger** [comment]
`TFBertTokenizer` is in the main init but it's a fairly recent addition. Are you certain you have the latest version of Transformers? You can print it with `from transformers import __version__; print(__version__)`

**Comment by shabha7092** [comment]
@sgugger For some reason transformer version was showing 4.20.1 when i ran the above command. I updated it to 4.23.1 and now i dont see any error. Thank you fo your time.

**Comment by Amlalqhtani** [comment]
how u are update the version?????

**Comment by Khixinhxan** [comment]
@Amlalqhtani pip install --upgrade transformers
