### ISSUE TITLE
Finetuning transformers for long document summarisation

### ISSUE THREAD

**Issue by ra-MANUJ-an** [huggingface/transformers#19861]
I'm wondering if there are any sample codes or blogs which can help me understand finetuning of transformer models for long document summarisation?

**Comment by ra-MANUJ-an** [comment]
@patil-suraj 
@patrickvonplaten

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask such questions as we keep the issues for bugs and feature requests only.

**Comment by ra-MANUJ-an** [comment]
Sure, and apologies. I'll ask on the forum now. Thanks for the information.
