### ISSUE TITLE
Can run_translation.py support nllb model fine-tuning ?

### ISSUE THREAD

**Issue by cokuehuang** [huggingface/transformers#19860]
### Feature request

Can run_translation.py support nllb model fine-tuning ? As run_translation.py is much easier to fine-tuning a model.

### Motivation

Want to an easy way to fine-tuning nllb model, as it is so difficult to fine-tuning a nllb model from its docs.

### Your contribution

star the repository

**Comment by sgugger** [comment]
The script support NLLB models, if you run any issue you can use the [forums](https://discuss.huggingface.co/) to ask the community for help.
