### ISSUE TITLE
Fine Tuning Bert for Q&A

### ISSUE THREAD

**Issue by priteshpatel15** [huggingface/transformers#1986]
This is more of a theoretical question.  I would like to use a Bert Model trained on SQUAD 2.0 then train it further on my domain's Q&A dataset.

How would I do that.  I've read through the code.  As I understand it, I see that the BertforQuestionAnswering would be what I would need to use loaded with a model that is fine tuned on Squad so the weights match the architecture.

But now I want to further fine tune this model to include Q&A training data from my target domain.  How would I do that?

**Comment by MathewAlexander** [comment]
A quick workaround would be appending your data to the SQUAD training dataset and doing the fine-tuning as usual.

**Comment by priteshpatel15** [comment]
Yes thats an approach.  I've been reading a bit more about GPT and GPT-2 ... i'm wondering if I could use the generative approach with fine-tuning on a specific task that would help with SQUAD Q&A ability for my target domain?  What are people's thoughts.  Does the math work out?

**Comment by oersoy1** [comment]
> This is more of a theoretical question. I would like to use a Bert Model trained on SQUAD 2.0 then train it further on my domain's Q&A dataset.
> 
> How would I do that. I've read through the code. As I understand it, I see that the BertforQuestionAnswering would be what I would need to use loaded with a model that is fine tuned on Squad so the weights match the architecture.
> 
> But now I want to further fine tune this model to include Q&A training data from my target domain. How would I do that?

Hi @priteshpatel15 I am interested in this problem. Have you found a more elegant solution than what Matthew suggested above?
