### ISSUE TITLE
Trainer RuntimeError CUDA error

### ISSUE THREAD

**Issue by devozs** [huggingface/transformers#19862]
### Versions
i`ve tried using
- transformers==4.15.0, 4.8.0 and latest
- python 3.8, 3.9 and 3.10

### nvidia-smi
NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7

Thanks!

### Who can help?

@sgugger

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Actual Error:
Class: `transformers/trainer.py`
Failing at: `tr_loss = torch.tensor(0.0).to(args.device)`
Returns: `RuntimeError: CUDA error: invalid argument`

### Code
I am following several examples and getting the same above error and the same line.
As a reference you can reproduce it according to this [code sample](https://github.com/dredwardhyde/gpt-neo-fine-tuning-example/blob/main/gpt_neo.py)
The exact same error occur with other huggingface training examples.

### Also tried
- if i am running the line `tr_loss = torch.tensor(0.0).to(args.device)` as a standalone its working fine
- Also tried to run this line as part of gpt_neo.py in the above example and it worked fine but later failed as part of `transformers/trainer.py`
- I made sure the CUDA is running fine:
 `torch.cuda.is_available()`
- Running only `torch.tensor(0.0)` works fine, only when adding `.to(device)` its failing

### Expected behavior

No errors at `torch.tensor(0.0).to(device)`

**Comment by devozs** [comment]
i hope its ok that i putting a link to different ML library (in case its not - i`ll delete it)
[this issue seems to be similar](https://github.com/Lightning-AI/lightning/issues/11818#issuecomment-1033541994)

**Comment by sgugger** [comment]
It doesn't look exactly similar in the sense that it is in an environment without a GPU, whereas yours shows one. Unless you are not executing the script within the exact same env as the results of the commands passed above of course.
