### ISSUE TITLE
ByT5Tokenizer ignores spaces around added tokens

### ISSUE THREAD

**Issue by djstrong** [huggingface/transformers#19873]
### System Info

transformers 4.23.1

### Who can help?

@patrickvonplaten @SaulLu

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('google/byt5-base')
tokenizer.add_tokens('<x>', special_tokens=True)
print(tokenizer('<x> <x> <x><x>'))
{'input_ids': [384, 384, 384, 384, 1], 'attention_mask': [1, 1, 1, 1, 1]}
```
in comparison to:
```python
print(tokenizer('a a aa'))
{'input_ids': [100, 35, 100, 35, 100, 100, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}
```

### Expected behavior

In my task presence of spaces around added tokens are important. Despite that, I think byT5 tokenizer should not ignore any characters (bytes).

**Comment by sgugger** [comment]
May also be of interest to @ArthurZucker

**Comment by ydshieh** [comment]
Sorry for being late here. So as @Narsil pointed out, 

```python
tokenizer = AutoTokenizer.from_pretrained("google/byt5-base")
new_token = AddedToken("<x>", lstrip=False, rstrip=False)
tokenizer.add_tokens(new_token, special_tokens=True)
```
should work (which is not the case for now) without the need of `tokenizer._additional_special_tokens.append(new_token)`.
And the goal is to make the above code snippet do it job correctly. Is this right?

**Comment by ArthurZucker** [comment]
Hey! I'll take this one on as part of #23909, since it is an issue with `rstrip` and `lstrip` being ignored (as the default behaviour if a token is not special is to always stip)

**Comment by ArthurZucker** [comment]
As mentioned, this will take a bit more time, a big refactoring is coming! 🔥

**Comment by ArthurZucker** [comment]
Should be merged this week!
