### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'ignore_mismatched_sizes')

### ISSUE THREAD

**Issue by Xappuccino** [huggingface/transformers#19886]
### System Info

transormers~=4.21.0
tensorflow~=2.8.2
python~=3.7.3
when I modify type_vocab_size in config.json in bert-base-chinese, and pass ignore_mismatched_sizes param to from_pretrianed function like below:
`self.bert = TFBertModel.from_pretrained(pretrain_path, ignore_mismatched_sizes=True)
`
Then I got this error `TypeError: ('Keyword argument not understood:', 'ignore_mismatched_sizes')`

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

transormers~=4.21.0
tensorflow~=2.8.2
python~=3.7.3
modify type_vocab_size in config.json in bert-base-chinese, and pass ignore_mismatched_sizes param to from_pretrianed function like below:
`self.bert = TFBertModel.from_pretrained(pretrain_path, ignore_mismatched_sizes=True)
`

### Expected behavior

load bert-base-chinese checkpoint successfully

**Comment by sgugger** [comment]
Can you try to upgrade your version of Transformers and try again? If it still fails, could you please post the full traceback?

**Comment by Xappuccino** [comment]
I have solved my problem, it was due to the old version transformers code I saved in my project directory that invalidated the transformers version upgraded through pip install~, thx for your replay!
