### ISSUE TITLE
Long-form (including timestamps) for whisper

### ISSUE THREAD

**Issue by JeffreyWardman** [huggingface/transformers#19887]
### Feature request

https://github.com/huggingface/transformers/commit/504cd71a6b172f177e6da513bea94fadb18ad99c
- Inference is currently only implemented for short-form i.e. audio is pre-segmented into <=30s segments. Long-form (including timestamps) will be implemented in a future release.

When would the ETA be for this?

### Motivation

Whisper is not usable for long audio of speech, or for chunking audio based on timestamps determined by the ASR.

### Your contribution

Guidance/PR in longer term future if not picked up by others in the next month or so

**Comment by sgugger** [comment]
cc @sanchit-gandhi and @ArthurZucker

**Comment by sanchit-gandhi** [comment]
Hey @JeffreyWardman! I believe @ArthurZucker has started looking into this, see https://github.com/huggingface/transformers/issues/19490#issuecomment-1285166541 for context!

**Comment by JeffreyWardman** [comment]
Thanks @sanchit-gandhi! By the looks of it, it would still be missing the timestamps. This is quite an important feature for me. I'm not completely familiar with the underlying code for huggingface. How does the chunking work? Does it calculate the first break between words after a given duration?

**Comment by sanchit-gandhi** [comment]
cc @ArthurZucker who knows more about timestamp generation!

This blog highlights quite nicely how chunking works in Transformers: https://huggingface.co/blog/asr-chunking

**Comment by kurianbenoy-sentient** [comment]
Does whisper implementation of hugging support timestamps to generate SRT files like openai/whisper implementation?

https://github.com/openai/whisper/blob/main/whisper/utils.py#L64
