### ISSUE TITLE
Unable to Finetune Deberta

### ISSUE THREAD

**Issue by ra-MANUJ-an** [huggingface/transformers#19894]
I am trying to finetune deberta for irony detection task, colab's notebook link can be found [here](https://colab.research.google.com/drive/1mZI5W2ozc8speZiwzOtCrWABhSaxqhWD?usp=sharing)

When I try to use 'microsoft/deberta-v3-base' checkpoint with AutoModel, I'm getting the following error :

RuntimeError: Expected target size [32, 2], got [32]
but when I use the same model with 'bert-base-uncased' or roberta (with some changes in head) it works fine. The one can find working code for bert based in [this](https://colab.research.google.com/drive/1PXacY2YgAfk6IYC0sAynp88Z6ndWrqYQ?usp=sharing) notebook.

When I printed the shapes of predictions and labels, I got outputs as torch.Size([32, 30, 2]), torch.Size([32]) respectively. In the case of bert, shapes of outputs were torch.Size([32, 2]), torch.Size([32]) for predictions and labels.

Here 32 is the batch size, and 30 is the sequence length.

Can someone let me know what I'm doing wrong?

**Comment by ra-MANUJ-an** [comment]
@sgugger 
@patil-suraj 
@patrickvonplaten

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to get help debug your code. In this instance you are using the base pretrained model (without a classification head) to do classification so it does not work. You should consider using AutoModelForSequenceClassification`.

**Comment by ra-MANUJ-an** [comment]
okay, sure will take care from next time and thanks for the response! Just one question, do bert and roberta provide classification heads in their base models?
