### ISSUE TITLE
Transformers from GCS (or custom filesystem).

### ISSUE THREAD

**Issue by nsthorat** [huggingface/transformers#19909]
### Feature request

Hi! I'm wondering if there will be support for a custom filesystem argument to "from_pretrained" for transformers, just like there is for datasets (https://huggingface.co/docs/datasets/filesystems).

### Motivation

This ideally would be great for running models in the cloud in "diskless" mode where there is no access to a real filesystem and model assets could be read into RAM via the same filesystem API that is used for datasets.

This would solve the issue of decoupling a binary from its data dependencies, in the same way it's done for datasets.

Thank you!

### Your contribution

Would love to help here, but presumably a HF expert would be much more suited to solve this problem. Happy to be eyes and a tester!

**Comment by sgugger** [comment]
Hi there! We don't plan on adding support for something else than the Hub/local disk for pretrained model in Transformers.
