### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length for this model (11261 > 1024). Running this sequence through the model will result in indexing errors

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/transformers#19929]
### System Info

I tested 2 models (sshleifer/distilbart-cnn-12-6 , facebook/bart-large-cnn) and they both have very small 1024 max token length

So which model supports full length or the most token count?

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I tested 2 models (sshleifer/distilbart-cnn-12-6 , facebook/bart-large-cnn) and they both have very small 1024 max token length

So which model supports full length or the most token count?

### Expected behavior

I tested 2 models (sshleifer/distilbart-cnn-12-6 , facebook/bart-large-cnn) and they both have very small 1024 max token length

So which model supports full length or the most token count?

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for questions like this as we keep the issues for bugs (in the library) and feature requests only.

**Comment by FurkanGozukara** [comment]
@sgugger you are right i am closing this thread

could you answer there: https://discuss.huggingface.co/t/which-summarization-model-of-huggingface-supports-more-than-1024-tokens-which-model-is-more-suitable-for-programming-related-articles/25095
