### ISSUE TITLE
Incorrect Document Content in BlenderBot Tokenizer

### ISSUE THREAD

**Issue by chujiezheng** [huggingface/transformers#19938]
`The BlenderBot tokenizer has been trained to treat spaces like parts of the tokens (a bit like sentencepiece) so a word will be encoded differently whether it is at the beginning of the sentence (without space) or not.` However, the examples in BlenderBot Tokenizer (`BlenderbotTokenizer`) are the same:

https://github.com/huggingface/transformers/blob/bd469c40659ce76c81f69c7726759d249b4aef49/src/transformers/models/blenderbot/tokenization_blenderbot.py#L105

The same issue also occurs in `BlenderbotTokenizerFast`:

https://github.com/huggingface/transformers/blob/bd469c40659ce76c81f69c7726759d249b4aef49/src/transformers/models/blenderbot/tokenization_blenderbot_fast.py#L64

**Comment by sgugger** [comment]
Might be of interest to @ArthurZucker

**Comment by ArthurZucker** [comment]
Okay, this is simply because the model used, `BlenderbotTokenizer.from_pretrained("facebook/blenderbot-3B")` has the attribute `add_prefix_space` set to `True` by default. If you set it to `False` we have the expected different output. 
Let me open a PR to fix this.
