### ISSUE TITLE
 UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch.

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/transformers#19934]
### System Info

C:\Python399\lib\site-packages\transformers\models\bigbird_pegasus\modeling_bigbird_pegasus.py:807: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  torch.arange(indices.shape[0] * indices.shape[1] * num_indices_to_gather, device=indices.device)

```
import logging
from transformers import pipeline

f = open("TextFile1.txt", "r")

ARTICLE = f.read()

summarizer = pipeline("summarization", model="google/bigbird-pegasus-large-bigpatent" )
```

**Comment by sgugger** [comment]
cc @ArthurZucker so it's on your radar.

**Comment by ArthurZucker** [comment]
Interesting, we might have more model to refactor
