### ISSUE TITLE
HFArgumentParser using a mix of json file and command line?

### ISSUE THREAD

**Issue by sgunasekar** [huggingface/transformers#19941]
Is there a way to make HFArgumentParser to load first from a json/dict and then update any command line arguments on top of it? e.g., if i want to keep a custom defaults file for TrainingArguments but also update some arguments from command line. TIA

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask questions like this as we keep issues for bugs and feature requests only.
