### ISSUE TITLE
'FlaubertTokenizer' object has no attribute 'do_lowercase'

### ISSUE THREAD

**Issue by davidavdav** [huggingface/transformers#19942]
### System Info

- `transformers` version: 4.23.1
- Platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: not essential
- Using distributed or parallel set-up in script?: no

### Who can help?

@SaulLu 

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("flaubert/flaubert_base_uncased")
tokenizer.tokenize("bonjour")
AttributeError: 'FlaubertTokenizer' object has no attribute 'do_lowercase'
```

This was not the case back in the days of transformers-2

I can fix it by saying
```python
tokenizer.do_lowercase = True
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("flaubert/flaubert_base_uncased")
tokenizer.tokenize("bonjour")
AttributeError: 'FlaubertTokenizer' object has no attribute 'do_lowercase'
```

### Expected behavior

```
['bonjour</w>']
```

**Comment by sgugger** [comment]
Thanks for reporting! I believe this has been fixed on the main branch. While waiting for the next release, could you do a source install?

**Comment by davidavdav** [comment]
Yes, when installing from main 
```
pip install git+https://github.com/huggingface/transformers.git
```

things work again as expected
