### ISSUE TITLE
Cannot load TensorFlow model from PyTorch weights split to multiple files

### ISSUE THREAD

**Issue by stancld** [huggingface/transformers#19965]
### System Info

- `transformers` version: 4.24.0.dev0
- Platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.13.0+cu117
- Tensorflow version (GPU?): 2.9.2

### Who can help?

@LysandreJik @patrickvonplaten 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```bash
$ git clone https://github.com/stancld/transformers.git -b tf_longt5
$ cd transformers
$ pip install -e .
$ python
```

```python
>>> from transformers import TFLongT5ForConditionalGeneration
>>> m = TFLongT5ForConditionalGeneration.from_pretrained("google/long-t5-tglobal-xl", from_pt=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/transformers/src/transformers/modeling_tf_utils.py", line 2613, in from_pretrained
    raise EnvironmentError(
OSError: google/long-t5-tglobal-xl does not appear to have a file named tf_model.h5 or pytorch_model.bin.
>>> m = TFLongT5ForConditionalGeneration.from_pretrained(MODEL_NAME, from_flax=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/transformers/src/transformers/modeling_tf_utils.py", line 2613, in from_pretrained
    raise EnvironmentError(
OSError: google/long-t5-tglobal-xl does not appear to have a file named tf_model.h5 or pytorch_model.bin.
```

### Expected behavior

Being able to load TensorFlow model from PyTorch checkpoint when split to multiple files due to a large size.

**Comment by sgugger** [comment]
No this is not supported yet, we'll work on adding support for this later on :-)

**Comment by stancld** [comment]
@sgugger Great to hear! 🔝 Feel free then to close this issue if redundant, thanks! :]
