### ISSUE TITLE
Add SpA-Former

### ISSUE THREAD

**Issue by shivance** [huggingface/transformers#19971]
### Model description

I would like to add [SpA-Former](https://arxiv.org/abs/2206.10910) model to the Transformers.

It is an end-to-end transformer to recover a shadow-free image from a single shaded image. Unlike traditional methods that require two steps for shadow detection and then shadow removal, the SpA-Former unifies these steps into one, which is a one-stage network capable of directly learning the mapping function between shadows and no shadows, it does not require a separate shadow detection. Thus, SpA-former is adaptable to real image de-shadowing for shadows projected on different semantic regions. SpA-Former consists of transformer layer and a series of joint Fourier transform residual blocks and two-wheel joint spatial attention. The network in this paper is able to handle the task while achieving a very fast processing efficiency. 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

[Link](https://github.com/zhangbaijin/SpA-Former-shadow-removal) to Model Repo 
[Link](https://arxiv.org/abs/2206.10910) to Paper

**Comment by shivance** [comment]
@sgugger Hi, would it be a valuable contribution to HuggingFace?

**Comment by NielsRogge** [comment]
Sure this would be valuable! Let me know if you need any help
