### ISSUE TITLE
How to annotate these type of data for custom OCR training

### ISSUE THREAD

**Issue by mohit-217** [huggingface/transformers#19970]
@NielsRogge @gante can you please explain how to annotate the below files for custom handwritten mathematical equation training. More importantly s^2 
![FCA(1)-1-0tensor(0 89785)720](https://user-images.githubusercontent.com/51528367/198884771-5b7bf056-ae81-43f7-8ce9-a187cf371602.png)
![FCA(1)-4-3tensor(0 89384)888](https://user-images.githubusercontent.com/51528367/198884777-95d35008-c665-460d-b996-d0835e7f5a0e.png)
![FCA6-1-0tensor(0 83108)1827](https://user-images.githubusercontent.com/51528367/198884814-8cbfb1e8-66e0-4956-bb44-f9c912bc35f3.png)
![FCA6-3-1tensor(0 88415)2013](https://user-images.githubusercontent.com/51528367/198884835-19619bf3-2a8c-4113-b8fb-e28614cd44d2.png)

![FCA6-4-1tensor(0 82750)1928](https://user-images.githubusercontent.com/51528367/198884849-267d3228-2253-4eb1-a005-23626760c6a5.png)

_Originally posted by @mohit-217 in https://github.com/huggingface/transformers/issues/16007#issuecomment-1296276393_

**Comment by mohit-217** [comment]
@NielsRogge @gante Please review
How I need to annotate for these type of data.
1. 3 ( 7s+ 8 )
2. 5 (6s + 7)
3. s^2
4. s^2 + 3s + 1

These annotation is correct?

**Comment by NielsRogge** [comment]
Hi,

Could you please ask this question on our forum, rather than here?

Github issues are meant for bugs or feature requests.

Thanks!
