### ISSUE TITLE
Some weights of BertForPreTraining were not initialized from the model checkpoint 

### ISSUE THREAD

**Issue by dsaban** [huggingface/transformers#19999]
### System Info

Some weights of BertForPreTraining were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias']

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run script.

### Expected behavior

load BertForPreTraining

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask questions or fill the template to report a bug. Getting a warning because the checkpoint you selected does not contain all weights for your architecture is not, by itself, a bug.

**Comment by NielsRogge** [comment]
Yes, `bert-base-uncased` only includes the weights and bias of the language modeling head, but not the next sentence prediction task, which is what the warning is telling you. In other words, it corresponds to the `BertForMaskedLM` model.

Therefore closing this issue, feel free to reopen.
