### ISSUE TITLE
Wrong tokenization in Transformer-XL documentation

### ISSUE THREAD

**Issue by DavidNemeskey** [huggingface/transformers#2000]
## 🐛 Bug

This is a documentation-related bug. In the [TransfoXL documentation](https://huggingface.co/transformers/model_doc/transformerxl.html), the tokenization example is wrong. The snippet goes:
```
tokenizer = TransfoXLTokenizer.from_pretrained('transfo-xl-wt103')
...
input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute")).unsqueeze(0)  # Batch size 1
```
This code outputs the tokens `[24, 617, 3225, 23, 16072]`, of which `24` is `<unk>`.

The problem comes from the fact that Transformer-XL does **not** use a wordpiece vocabulary, but a regular (whole-word) one. Also, in WT-103, punctuation marks are split from the words. Consequently, the example should read instead (note that space in from of `,`):
```
tokenizer = TransfoXLTokenizer.from_pretrained('transfo-xl-wt103')
...
input_ids = torch.tensor(tokenizer.encode("Hello , my dog is cute")).unsqueeze(0)  # Batch size 1
```

It would also be nice to warn the user about this fact in the documentation, perhaps in `TransfoXLTokenizer`'s docstring?

**Comment by thomwolf** [comment]
Indeed, do you want to fix this in a PR?
