### ISSUE TITLE
Where I could find the vocab.json for XLNet

### ISSUE THREAD

**Issue by kugwzk** [huggingface/transformers#2003]
## ❓ Questions & Help

I notice in tokenizer_xlnet.py there is not the vocab,json only spiece model. So I want to know where I could find the vocab.json? And what I should rename the file ?

**Comment by TheEdoardo93** [comment]
If you want to have `xlnet_config.json`, which is a JSON file which specifies the hyper-parameters of the XLNet model, you can download the .zip file from [here](https://github.com/zihangdai/xlnet/blob/5cd50bc451436e188a8e7fea15358d5a8c916b72/README.md) which contains the pre-trained weights of XLNet model.

**Comment by kugwzk** [comment]
I downloaded the pre-trained model, the config file and the sentence piece model, but when I run the code I found the vocab_size = -1. Did I miss something?

**Comment by TheEdoardo93** [comment]
An example of the content of `xlnet_config.json` is the following:
```
{
    "d_head": 64, 
    "d_inner": 3072, 
    "d_model": 768, 
    "ff_activation": "gelu", 
    "n_head": 12, 
    "n_layer": 12, 
    "n_token": 32000, 
    "untie_r": true
}
```

> When i run the code I found the vocab_size=-1

Which code you are talking about?

**Comment by prajjwal1** [comment]
You can either download from S3 repo or the script is supposed to automatically download the vocab file. Make sure you have a working internet connection.
