### ISSUE TITLE
Unable to load CodeGenTokenizer

### ISSUE THREAD

**Issue by PtrMan** [huggingface/transformers#20056]
### System Info

I did `pip install git+https://github.com/huggingface/transformers.git`

try to load the class with `from transformers import CodeGenTokenizer`

results in

```
ImportError: cannot import name 'CodeGenTokenizer' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import CodeGenTokenizer

### Expected behavior

load class

**Comment by sgugger** [comment]
You should double-check that the version of Transformers seen when executing your code is indeed a source install (you can print `transformers.__version__` after importing transformers), as it looks like an issue within your env.

**Comment by PtrMan** [comment]
Thx!
