### ISSUE TITLE
Is there a no_trainer version for image pertaining 

### ISSUE THREAD

**Issue by XZhang97666** [huggingface/transformers#20053]
### Feature request

I wonder if there is a run_no_trainer code for image pertaining? @NielsRogge

### Motivation

I usually use no trainer in my code because the trainer cannot should much detail.

### Your contribution

NA

**Comment by XZhang97666** [comment]
@NielsRogge

**Comment by NielsRogge** [comment]
Not yet, but it would be straightforward to add.

Marking this as a good first issue.

**Comment by atturaioe** [comment]
Hi @NielsRogge, I would like to try to add it.

**Comment by NielsRogge** [comment]
Hi @atturaioe, awesome.

So in [this folder](https://github.com/huggingface/transformers/tree/main/examples/pytorch/image-pretraining), one could add a `run_mim_no_trainer.py` script, similar to the other `no_trainer.py` scripts in the examples folder.

**Comment by Saad135** [comment]
Hi @atturaioe, are you still working on this? I would like to attempt this if you are not longer working on it.

**Comment by atturaioe** [comment]
Hi @Saad135, you can take this issues if you want, let me know.

**Comment by Saad135** [comment]
@atturaioe Sure, I will give it a go.

**Comment by madt2709** [comment]
Is anyone still working on this? If not I'd quite like to pick it up. 

I see from the PR that most of the work has been done but there's not been any acitivity on it recently 🤔

**Comment by awinml** [comment]
@madt2709 I am working on it. Most of the work has been completed by @Saad135. His PR #20053 has been closed due to inactivity. I have taken it over in PR #23156 to complete it.
