### ISSUE TITLE
Converting CLIPText Model (transformers.CLIPTextModel) Embeddings Back to Text

### ISSUE THREAD

**Issue by mbdzi** [huggingface/transformers#20078]
### Feature request

Is there a method for converting CLIPText Model (transformers.CLIPTextModel) model embeddings back to text? I looked in the documentation, but could not find anything that addresses this specific query.

I am also interested in finding out the following:
- Are there tools in the Hugging Face ecosystem for calculating the weighted average of embeddings?
- Is there a way to query the CLIP Model using embeddings and not text or image inputs?

### Motivation

I would like to edit prompts mathematically. And, the easiest way to do this would be to get the vector embeddings and to effect the desired mathematical transformations on them.

### Your contribution

I have no contribution beyond my question.

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for such questions as we keep issues for bugs and feature requests only.
