### ISSUE TITLE
Where is the Translation template ? 

### ISSUE THREAD

**Issue by bfss** [huggingface/transformers#20083]
I want to translate the doc in leisure time, and I followed the guide, but not found Translation template...

**Comment by tomaarsen** [comment]
There's some relevant issues on this where people encountered the same issue:
* #17404
* #17028 

For context, @bfss is stating that the [TRANSLATING.md](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md) documentation says:
> To get started, navigate to the [Issues](https://github.com/huggingface/transformers/issues) page of this repo and check if anyone else has opened an issue for your language. If not, open a new issue by selecting the "Translation template" from the "New issue" button.

However, no such issue template exists.

---

That said, there are also some larger issues tracking the progress of the translation of a certain language. Perhaps these can be used as an informal template or guide if no issue for your language exists.
* https://github.com/huggingface/transformers/issues?q=Tranformers+documentation+translation+to+

**Comment by bfss** [comment]
Thank you for your reply~ @tomaarsen

**Comment by wonhyeongseo** [comment]
Trying to add the template right now. https://github.com/huggingface/transformers/pull/20199
