### ISSUE TITLE
Cannot load CLIPProcessor / CLIPFeatureExtractor locally

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#20121]
### System Info

- `transformers` version: 4.25.0.dev0
- Platform: Linux-5.18.10-76051810-generic-x86_64-with-glibc2.34
- Python version: 3.9.7
- Huggingface_hub version: 0.11.0.dev0
- PyTorch version (GPU?): 1.11.0+cpu (False)
- Tensorflow version (GPU?): 2.9.1 (False)
- Flax version (CPU?/GPU?/TPU?): 0.6.0 (cpu)
- Jax version: 0.3.16
- JaxLib version: 0.3.15
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sgugger maybe

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Is it expected that the following doesn't work on main? 

```python
from transformers import CLIPFeatureExtractor, AutoFeatureExtractor, AutoProcessor

feature_extractor = CLIPFeatureExtractor()

id_name = "./clip_feat"
feature_extractor.save_pretrained(id_name)

print("load from CLIPFeatureExtractor")
feature_extractor = CLIPFeatureExtractor.from_pretrained(id_name)
#print("load from CLIPImageProcessor")
#feature_extractor = CLIPImageProcessor.from_pretrained(id_name)
print("load from AutoFeatureExtractor")
feature_extractor = AutoFeatureExtractor.from_pretrained(id_name)
print("load from AutoProcessor")
feature_extractor = AutoProcessor.from_pretrained(id_name)
```

We can see that I can load the feature extractor directly from the class but not from `AutoFeatureExtractor` or `AutoProcessor` even though we save the feature extractor type in the `preprocessor_config.json` file.

### Expected behavior

I would have expected that the code snippet above works.

**Comment by sgugger** [comment]
Will be fixed by #20111
