### ISSUE TITLE
Failed to import 

### ISSUE THREAD

**Issue by ravi160822** [huggingface/transformers#20131]
### System Info

python 3.10.7
Target: arm64-apple-darwin21.6.0
Thread model: posix
transformers==4.24.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`from transformers import AlbertTokenizer, AlbertModel`
->
```
RuntimeError: Failed to import transformers.models.albert.modeling_albert because of the following error (look up to see its traceback):
libcublas.so.11: cannot open shared object file: No such file or directory
```

### Expected behavior

no error

**Comment by sgugger** [comment]
Looks like a problem in your CUDA installation.

**Comment by ravi160822** [comment]
it works on my local, but it fail when I use it with docker, do I need to give any additional command in docker apart from installing requirements

**Comment by jagumpert** [comment]
@ravi160822 
I'm currently getting 

`libcublas.so.*[0-9] not found in the system path ['/app/src', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/site-packages', '/app/src']`

Did you find a workaround?

**Comment by saattrupdan** [comment]
I'm facing the same issue as @jagumpert, but only when running Github actions:

```libcublas.so.*[0-9] not found in the system path [(...)]```

**Comment by jose-arguelles** [comment]
I also have the same issue as @jagumpert when trying to build a docker image with --platform=linux/amd64 python:3.11 as the base image. 

@saattrupdan solution did not work for me ( downgrading torch to 2.0.0 did not fix the issue for me )

**Comment by AlexCapchase** [comment]
Same here  @jose-arguelles when trying to build a docker image. Did you find any workaround?

**Comment by Anna-Pinewood** [comment]
> 2.0.0
Downgrading torch to 2.0.0 version also helped me (poetry add torch=2.0.0) on Ubuntu without gpu on it!

**Comment by codingbutstillalive** [comment]
> @saattrupdan 's solution helped me, thank you. Downgrading torch to 2.0.0 version also helped me (`poetry add torch=2.0.0`) on Ubuntu without gpu on it!

Could you please explain what changed between the versions? And why this was a solution. Thanks :)

**Comment by IronMan2810** [comment]
@codingbutstillalive this is due to poetry.
When installing torch2.0.0 it also download nvidia packages unlike torch2.1

**Comment by IronMan2810** [comment]
> > @saattrupdan 's solution helped me, thank you. Downgrading torch to 2.0.0 version also helped me (`poetry add torch=2.0.0`) on Ubuntu without gpu on it!
> 
> Could you please explain what changed between the versions? And why this was a solution. Thanks :)


@codingbutstillalive this is due to poetry.
When installing torch2.0.0 it also download nvidia packages unlike torch2.1

**Comment by nubunto** [comment]
still happens, installing torch 2.0.0 did not solve it for me

**Comment by viniciusteixeiradias** [comment]
Did you guys find any workaround? @AlexCapchase @jose-arguelles
