### ISSUE TITLE
Problems with layoutlm language model

### ISSUE THREAD

**Issue by mv96** [huggingface/transformers#20138]
### Feature request

Hi,

I was recently reading Layoutlm and it's variants and I figured out that they do exist in hugging face but there are several problems with It or I am not very sure to understand it just by reading the documentation.

Q1) [Layoutlm](https://arxiv.org/abs/1912.13318) is a multimodal machine learning transformer then why is it listed in the text transformers category on HuggingFace ?

Q2) Even if it is multimodal, layoutlm does not tend to use the image anywhere in the examples of layoutlm [Layoutlm](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlm) ? 

Q3) For [Layoutlmv2](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2) there is no tensorflow class like TFlayoutlm as it is available for version1 ?

Q4) there is no MLM head class as it available for it's version 1 ? so I am not sure if I want to pretrain this model from scratch how do I do that ?

Q5) Same as Q4 there is not MLM head class, so in this case if I have my own tokenizer and I want to pretrain from scratch layoutlm and then simply want to change the transformer with one line of code change, that's not possible because they have different heads ?

I am a bit new to HF interface so forgive me if I asked something super basic. 
I don't know if I have something wrong with understanding layoutlm in the first place or these are valid questions, 
But I would be very happy if anyone can shed some light on this !!
Once again thanks for taking the time to read 😊😊 , have a good day !!

### Motivation

Just find it very difficult to understand the implementation of the specific model from the transformers library

### Your contribution

I can try to look into it, but first I need to know if the problem is really a problem or it is just my wrong understanding of the library.

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask such questions as we keep issues for bugs and feature requests only :-)
cc @NielsRogge

**Comment by NielsRogge** [comment]
Please link your question on the forum, I'll answer there!

**Comment by mv96** [comment]
@NielsRogge can you send me the link to access forums, I tried to look at the discord channel of hugging face but I am not exactly sure where to ask questions.

Thanks
