### ISSUE TITLE
Add support for images embeddings as one of the **input parameters

### ISSUE THREAD

**Issue by ramanova** [huggingface/transformers#20148]
### Feature request

[Owl-ViT](https://huggingface.co/docs/transformers/model_doc/owlvit)
**Current flow** for inference for OWL ViT is to accept image and text, run it through a processor and then give that as an input to the Model for inference. Result: Getting detections with some confidences.
```python
model = OwlViTForObjectDetection.from_pretrained(...)
processor = OwlViTProcessor.from_pretrained(...)

inputs = processor(text=texts, images=image, return_tensors="pt")
outputs = model(**inputs)
```

**Additional flow**
It would be useful to have additional capability to support images embeddings as an input (either for a processor or the model itself), so the additional flow would look like this:
take 100 (e.g.) images -> run to calculate images embeddings, save (a dataframe, or files) -> use model(embeddings_dir, text_terms) to infer detections.
```python
model = OwlViTForObjectDetection.from_pretrained(...)
processor = OwlViTProcessor.from_pretrained(...)

# using images_embeddings instead of images
inputs = processor(text=texts, images_embeddings=image_embedding, return_tensors="pt")
outputs = model(**inputs)
```

### Motivation

Creating a cache, precomputed set of images embeddings for faster inference / search by text.
It is possible, that this functionality already exists, but because of the way owl-vit is structured, it might be tricky to perform: currently **inputs contain embeddings for bboxes and text.

### Your contribution

Would be difficult, as I'm not familiar with the infra.

**Comment by sgugger** [comment]
cc @alaradirik and @NielsRogge
