### ISSUE TITLE
[CamemBERT] Add CamembertForQuestionAnswering

### ISSUE THREAD

**Issue by alekseiancheruk** [huggingface/transformers#2015]
Firstly, a huge thanks to Hugging Face team for their great work ! As we have now Camembert, it would be nice to use it for question answering using transformers ! You can find SQuAD in French on GitHub so it would be so easy to a lot of people to fine-tune Camembert for this task. 

Please consider it in future releases 😉

**Comment by cedspam** [comment]
I wonder if loading as roberta really works for camembert

**Comment by TheEdoardo93** [comment]
What do you mean with this statement?

> I wonder if loading as roberta really works for camembert

**Comment by julien-c** [comment]
Happy to review a PR for this (should be pretty easy to add!)

**Comment by cedspam** [comment]
> 
> 
> What do you mean with this statement?
> 
> > I wonder if loading as roberta really works for camembert

you can load camembert config and checkpoints as roberta models but I'm not perfectly sure it's identical. 
I did'nt checked if there was RobertaForQuestionAnswering so my comment is partly irrevelent. However both slould be added if possible. maybe some generic heads using PreTrainedModel could be possible even in not efficient

**Comment by TheEdoardo93** [comment]
> > What do you mean with this statement?
> > > I wonder if loading as roberta really works for camembert
> 
> you can load camembert config and checkpoints as roberta models but I'm not perfectly sure it's identical.
> I did'nt checked if there was RobertaForQuestionAnswering so my comment is partly irrevelent. However both slould be added if possible. maybe some generic heads using PreTrainedModel could be possible even in not efficient

At the moment, you **can't** use RoBERTa model for QuestionAnswering. You can use `RoBERTa` model for **token classification**, **multiple choice**, **sequence classification** and **MaskedLM** (with the usual `RobertaFor*` naming convention).

**Comment by mdhoffschmidt** [comment]
Hi, thanks to the Hugging Face team for the amazing work. I think there is a PR here : https://github.com/huggingface/transformers/pull/2746
