### ISSUE TITLE
how to fine tune custom dataset using coreference pretrained model 

### ISSUE THREAD

**Issue by SavitaKumariPandit** [huggingface/transformers#20161]
the pre-trained model available in hugging face hub "nreimers/mMiniLMv2-L12-H384-distilled-from-XLMR-Large" how to fine tuning with own custom dataset.

**Comment by NielsRogge** [comment]
Hi,

For that I'll refer to the training guide of Sentence Transformers: https://www.sbert.net/docs/training/overview.html.

**Comment by SavitaKumariPandit** [comment]
> Hi,
> 
> For that I'll refer to the training guide of Sentence Transformers: https://www.sbert.net/docs/training/overview.html.

Hi @NielsRogge , I have to use my own dataset for co-reference resolution task, so above mention suggestion will work on pretrained model of "nreimers/mMiniLMv2-L12-H384-distilled-from-XLMR-Large".
