### ISSUE TITLE
How to train transformer using my own data?

### ISSUE THREAD

**Issue by Arsmart1** [huggingface/transformers#20171]
### Feature request

I have not see a tutorial for training my own data.....Can I ? I am a new AI learner. Thank you!!!

### Motivation

I have not see a tutorial for training my own data.....Can I ? I am a new AI learner. Thank you!!!

### Your contribution

I have not see a tutorial for training my own data.....Can I ? I am a new AI learner. Thank you!!!

**Comment by aymenkhs** [comment]
Here is a tutorial in the transformers Doc on how to fine tune a pretrained model using the Transformers library (https://huggingface.co/docs/transformers/training), you can also check the Hugging face course https://huggingface.co/course/chapter1/1, for more help you will need to precise what do you want to do exactly

Besides, I noticed that you opened another issue #20187 for the exact same question. You should always avoid doing that you're just making the maintainers job harder, you should close your new issue. Also, I personally think it will be better to ask these kinds of questions on the Hugging Face's forum (https://discuss.huggingface.co/) or discord server (https://discord.com/invite/JfAtkvEtRb).
