### ISSUE TITLE
How to use GPT-2 text generator in spanish

### ISSUE THREAD

**Issue by erdos-ml** [huggingface/transformers#2017]
## ❓ Questions & Help

I would like to know if there is a way to use the gpt-xl model for text generation in spanish.

The command I use to run the english text generation model is the following:

$ python ./examples/run_generation.py     --model_type=gpt2     --length=50     --model_name_or_path=gpt2-xl

What other parameter must I use to allow spanish text generation?

**Comment by TheEdoardo93** [comment]
At the moment, there is **no pre-trained model in Spanish language**. If you want, you can use a **multi-lingual** pre-trained model, such as BERT or XLM. In particular, Transformers offer the following settings of multi-lingual models:
- **bert-base-multilingual-cased** (Masked language modeling + Next sentence prediction, 104 languages)
- **bert-base-multilingual-uncased** (Masked language modeling + Next sentence prediction, 102 languages)
- **xlm-mlm-17-1280** (Masked language modeling, 17 languages)
- **xlm-mlm-100-1280** (Masked language modeling, 100 languages)

You can find more information in the  [official documentation](https://huggingface.co/transformers/multilingual.html).

**Comment by erdos-ml** [comment]
Thank you. I will close the issue.
