### ISSUE TITLE
Misleading tensor type in code and documentation of Wav2Vec2ForPreTraining

### ISSUE THREAD

**Issue by PierreOrhan** [huggingface/transformers#20173]
The Wav2Vec2ForPreTraining expects in its forward pass a torch.BoolTensor for the sampled_negative_indices.
https://github.com/huggingface/transformers/blob/cbbeca3d1733aa7c9b443af5ff231a5affcd8a1e/src/transformers/models/wav2vec2/modeling_wav2vec2.py#L1404

But as the example and the code then indicates, this tensor should not be a boolean mask but should instead store the indices of the negative sample. Therefore its expected type should be long.

This was misleading and lead to a silent bug in my codes for quite long as I would send a boolean tensor fo the negative indices instead of a long tensor.

Is my reading of the code is correct, could we change the expected type of sampled_negative_indices ? 
Maybe @patrickvonplaten ( as it seems that he implemented the code) could confirm my reading?

It could be worth clarifying the name of mask_time_indices as well, since this one expects a mask and therefore a boolean and not a long tensor. It is also converted to a boolean tensor directly in the beginning of the forward call so this could be misleading for others as well.

Thank you for the implementation and help!

**Comment by sgugger** [comment]
cc @sanchit-gandhi

**Comment by PierreOrhan** [comment]
Sure!
While we are at it, in the original paper and fairseq implementation, there is a scaling of the feature extractor gradient by 0.1 for the base architecture. I can add that gradient scaling if you wish too, it really helped my trainings. This would require either to use a constant value (0.1, but since its not used for the Large model this might not be the best idea) or to change the config class of Wav2vec2 to allow the setting of this multiplier.

**Comment by sanchit-gandhi** [comment]
Hey @PierreOrhan! Let me know if you're still interested in opening a PR to fix this! It would be awesome to update the Wav2Vec2 code to prevent further silent bugs like this occurring for other users in the future!

We can also look into the gradient scaling in a separate PR if you want! Happy to help with this integration too (think it could be beneficial for training)

**Comment by PierreOrhan** [comment]
Sure, I have this on my todo list and should be able to submit in a month or so (finishing a project right now), it will take me time since I never oppened a PR on a large repo so I need to understand the whole process.
Best,

**Comment by sanchit-gandhi** [comment]
Hey @PierreOrhan! Sounds good! Best of luck with finishing off your current project! 

Exciting that this will be your first PR on a large repo! I'll be on hand to help you with this process to make it as easy as possible! We have a pretty comprehensive guide for opening a PR on transformers: https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md Feel free to have a skim through this guide to get a feel for the steps involved, and don't hesitate to ask any questions here or on a draft PR! More than happy to help!
