### ISSUE TITLE
Difficult to understand warning

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#20185]
### System Info

- `transformers` version: 4.25.0.dev0
- Platform: Linux-5.18.10-76051810-generic-x86_64-with-glibc2.34
- Python version: 3.9.7
- Huggingface_hub version: 0.11.0.dev0
- PyTorch version (GPU?): 1.11.0+cpu (False)
- Tensorflow version (GPU?): 2.9.1 (False)
- Flax version (CPU?/GPU?/TPU?): 0.6.0 (cpu)
- Jax version: 0.3.16
- JaxLib version: 0.3.15
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@amyeroberts @sgugger 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import CLIPImageProcessor

processor = CLIPImageProcessor.from_pretrained("openai/clip-vit-large-patch14")
```

=> this throws the following warning:

```
The size parameter should be a dictionary with keys ('height', 'width'), ('shortest_edge', 'longest_edge') or ('shortest_edge',) got 224. Setting as {'shortest_edge': 224}.
The size parameter should be a dictionary with keys ('height', 'width'), ('shortest_edge', 'longest_edge') or ('shortest_edge',) got 224. Setting as {'height': 224, 'width': 224}.
```

### Expected behavior

I'm wondering whether it would be better to for now downgrade the warning here: https://github.com/huggingface/transformers/blob/6cc06d17394f5715cdf2d13a1ef7680bedaee9e2/src/transformers/image_processing_utils.py#L500 to just `logger.info(...)` 

The `openai/clip-vit-large-patch14` model is used **a lot** in downstream applications (CompVis, diffusers) and the thrown warning here is maybe a bit too much and scares the user? 

Or should we aggressively update all the configs of CLIP models on the Hub in order to make the warning go away we would have to update the config online of a lot of clip models..

**Comment by sgugger** [comment]
Updating the config online would make them incompatible with previous versions of Transformers so that's not a possibility. I'm fine with downgrading the warnings to infos.

**Comment by amyeroberts** [comment]
I'll open a PR to downgrade the warnings. I agree the message isn't very clear either - I'll open up another PR to tidy this up. 

@NielsRogge This is likely because there's two parameters `size` and `crop_size` that are being converted to a dict - makes the point about the warnings being unclear quite well!
