### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/dump.txt'

### ISSUE THREAD

**Issue by MrLinNing** [huggingface/transformers#2018]
@stefan-it
Hello, I am new learner in BERT and I want to have a try the excellent work - distilBert.
But the problem happened when I ran the training step, and Could you tell me where can I download the `dump.txt` file ?
Thank you very much!

**Comment by TheEdoardo93** [comment]
As stated [here](https://github.com/huggingface/transformers/blob/1ab8dc44b3d84ed1894f5b6a6fab58fb39298fc7/examples/distillation/README.md), the `dump.txt` file is **your training file**. This file will contain one sequence per line (a sequence being composed of one of several coherent sentences).

> @stefan-it
> Hello, I am new learner in BERT and I want to have a try the excellent work - distilBert.
> But the problem happened when I ran the training step, and Could you tell me where can I download the `dump.txt` file ?
> Thank you very much!
