### ISSUE TITLE
[CamemBert] Tokenizer function add_tokens doesn't work

### ISSUE THREAD

**Issue by breeky** [huggingface/transformers#2019]
## ❓ Questions & Help

Hi, 

I am trying to add new tokens to the CamemBert tokenizer, but when I run the function tokenizer.add_tokens, it doesn't seem to add any token at all :

`from transformers import CamembertTokenizer`
`tokenizer = CamembertTokenizer.from_pretrained('camembert-base')`
`tokenizer.add_tokens(['notfrenchword'])`

`Out[12]: 0`

Whereas with Bert model it works perfectly. Is this a bug or am I doing something wrong ?

Thanks

**Comment by TheEdoardo93** [comment]
This method is **not** implemented into the CamemBERT tokenizer, at the moment.

> ##  Questions & Help
> Hi,
> 
> I am trying to add new tokens to the CamemBert tokenizer, but when I run the function tokenizer.add_tokens, it doesn't seem to add any token at all :
> 
> `from transformers import CamembertTokenizer`
> `tokenizer = CamembertTokenizer.from_pretrained('camembert-base')`
> `tokenizer.add_tokens(['notfrenchword'])`
> 
> `Out[12]: 0`
> 
> Whereas with Bert model it works perfectly. Is this a bug or am I doing something wrong ?
> 
> Thanks

**Comment by thomwolf** [comment]
Hi,
This method is actually implemented (it's a method in the base class of all tokenizer).
The reason is was failing in the present case is that the original fairseq model has a bunch of duplicate tokens in the dictionary:
```
import torch
camembert = torch.hub.load('pytorch/fairseq', 'camembert.v0')
list(camembert.task.source_dictionary[i] for i in range(10))
>>> ['<s>', '<pad>', '</s>', '<unk>', '<unk>', '<s>', '</s>', ',', '▁de', '.']
```
fixing this in #2065
