### ISSUE TITLE
Spelling Error in Testing Documentation - "checkt" -> "check"

### ISSUE THREAD

**Issue by kasmith11** [huggingface/transformers#20194]
### System Info

- `transformers` version: 4.24.0.dev0
- Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.17
- Python version: 3.8.13
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.12.1+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sgugger @stevhliu 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Under `Run documentation tests` section of [Testing documentation](https://huggingface.co/docs/transformers/testing#run-documentation-tests) it says: `In order to test whether the documentation examples are correct, you should checkt that the doctests are passing.`

### Expected behavior

The line can be changed to: `In order to test whether the documentation examples are correct, you should check that the doctests are passing.`

**Comment by sgugger** [comment]
Thanks for reporting, would you like to open a PR to fix this typo?

**Comment by kasmith11** [comment]
@sgugger sure I can open a PR to fix this type.
