### ISSUE TITLE
Infer pretrained base model and tokenizer used from a fine-tuned model_dir

### ISSUE THREAD

**Issue by yunjiangster** [huggingface/transformers#20216]
### Feature request

I would like to infer the pretrained base model and the tokenizer from the model_dir of a fine-tuned model. Is that possible with the default trainer setup? What I did previously was to programmatically copy all the tokenizer data into each checkpoint folder. But this seems cumbersome. 

### Motivation

This reduces overhead during inference/prediction. All I have to specify is just the model_dir. 

### Your contribution

Given enough guidance, I am happy to submit a PR.

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for such questions as we keep issues for bugs and feature requests only.
