### ISSUE TITLE
Question about layer norm in T5

### ISSUE THREAD

**Issue by FrostML** [huggingface/transformers#20224]
I notice that there is no bias and no subtraction of mean in layer norm.

I understand no bias but I'm confused about the meaning of computing variance without subtraction of mean. 

Normally, we compute variance, for example:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/7160927/201863288-bcb63739-0f74-4487-bbb8-91299dad2eef.png">
But it's different here. Why is that?

Hoping some explanation.

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask such questions as we keep issues for bugs and feature requests only.

**Comment by FrostML** [comment]
Sure. have created this topic [question-about-layer-norm-in-t5](https://discuss.huggingface.co/t/question-about-layer-norm-in-t5/26142). I'd close this issue.
