### ISSUE TITLE
Unable to use BERTmodel 

### ISSUE THREAD

**Issue by ashlytom** [huggingface/transformers#20221]
### System Info

Transformer version = 4.24.0
Python = 3.8
Error: SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-large-uncased/resolve/main/config.json (Caused by SSLError(SSLError(136, '[X509: NO_CERTIFICATE_OR_CRL_FOUND] no certificate or crl found (_ssl.c:4264)')))

@LysandreJik

### Who can help?

@LysandreJik

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

from summarizer import Summarizer

body = 'Text body that you want to summarize with BERT'
body2 = 'Something else you want to summarize with BERT'
model = Summarizer()
model(body)
model(body2)

### Expected behavior

Load the summaries

**Comment by ZurabDz** [comment]
Are you behind some firewall? It seems like you can't connect hugging face. If you are able to freely access internet with proxy you could yous this snippet:

```python3
import os
os.environ['HTTP_PROXY'] = 'http://proxy_url:proxy_port'
os.environ['HTTPS_PROXY'] = 'http://proxy_url:proxy_port'
```

otherwise you can manually download model and load it from disk
