### ISSUE TITLE
Yolo model trigger win10/11 reboot on Intel 13900k

### ISSUE THREAD

**Issue by Michael-YongWang** [huggingface/transformers#20223]
### System Info

All Yolos models/pipeline case my pc reboot immediately on windows 10 and 11 system ( WSL in win11 and Ubuntu(not virtual) work well on the same machine)

1. I reinstalled the os system and tested (both win10 and win11) two times and make sure all the drivers are up to date. The results are the same. (I test the system with Aida64 system stability test, all ok)

2. I tried Ubuntu(not virtual) and WSL in windows 11, both works ok.

3. I tried other models, such as Bert, all works fine.

``` python
from transformers import YolosFeatureExtractor, YolosForObjectDetection
from PIL import Image
import requests

url = 'http://images.cocodataset.org/val2017/000000039769.jpg'
image = Image.open(requests.get(url, stream=True).raw)

feature_extractor = YolosFeatureExtractor.from_pretrained('hustvl/yolos-tiny')
model = YolosForObjectDetection.from_pretrained('hustvl/yolos-tiny') 

inputs = feature_extractor(images=image, return_tensors="pt")

for _ in range(100):
    model(**inputs) # this line causes the PC reboot. (usually after several loops)
```

Hardware info:
CPU: Intel 13900k
Motherboard: ASUS Z690-G, bios 2103
GPU: Intel 13900k

Software info:
Conda env latest
Python 3.10.4
transformers 4.24.0
windows 10 and windows 11

My guess it is caused by the incompatible of the hardware.
Could you please help to take a look?

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Use python 3.10 on windows 10/11 with Intel 13900k

run the code below

``` python
from transformers import YolosFeatureExtractor, YolosForObjectDetection
from PIL import Image
import requests

url = 'http://images.cocodataset.org/val2017/000000039769.jpg'
image = Image.open(requests.get(url, stream=True).raw)

feature_extractor = YolosFeatureExtractor.from_pretrained('hustvl/yolos-tiny')
model = YolosForObjectDetection.from_pretrained('hustvl/yolos-tiny') # this line cases the PC reboot.

inputs = feature_extractor(images=image, return_tensors="pt")

for _ in range(100):
    model(**inputs) # this line causes the PC reboot. (usually after several loops)
```

### Expected behavior

The pc reboot immediately after several loop

**Comment by Oxi84** [comment]
How fast does it work with transformers?
13900k compared to gpu?
