### ISSUE TITLE
Is it possible to fine-tune models on TPUs using TensorFlow?

### ISSUE THREAD

**Issue by SebiSebi** [huggingface/transformers#2023]
I have looked at the release notes and found out that:

"Training on TPU using free TPUs provided in the TensorFlow Research Cloud (TFRC) program is possible but requires to implement a custom training loop (not possible with keras.fit at the moment).
We will add an example of such a custom training loop soon." (Note from September 26).

Is this observation still true? Can we train the transformer models on TPUs in TF?

**Comment by abdallah197** [comment]
following, would love to know if this is possible

**Comment by thomwolf** [comment]
We have some code in the `tpu-experiment` branch, for instance here: https://github.com/huggingface/transformers/tree/tpu-experiments/examples/TPU/tensorflow

And planning to make it clean in the mid-term (not sure that will be before the end of the year though).

cc @LysandreJik

**Comment by SebiSebi** [comment]
Any updates on this one?

**Comment by hadaev8** [comment]
Same here

**Comment by danyaljj** [comment]
Same here

**Comment by nemaniarjun** [comment]
Would like to bump this!

**Comment by LysandreJik** [comment]
Hi! We recently have updated all of our scripts with `Trainer` classes, for both TensorFlow and PyTorch. Both trainers now have TPU support!

The [examples README](https://github.com/huggingface/transformers/tree/master/examples#running-on-tpus) has been updated accordingly.

**Comment by nemaniarjun** [comment]
That's great!
