### ISSUE TITLE
Add Galactica model

### ISSUE THREAD

**Issue by mrm8488** [huggingface/transformers#20246]
### Model description

Galactica is a large language model for science.
Can summarize academic literature, solve math problems, generate Wiki articles, write scientific code, annotate molecules and proteins.

Web: galactica.org
Code: https://github.com/paperswithcode/galai

PS: It seems to use OPT architecture so maybe we can reuse the code used for adding these model. I would like to add this model :)

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by sgugger** [comment]
If the architecture is the same, it's just a matter of converting the checkpoints to the HF format and uploading them, no need to add a new model in the library :-)

**Comment by mrm8488** [comment]
Hi, Sylvain!

Yes, It is the same (Even I have run the forward pass with their wrapper and the HF `OPTForCausalLM` and the output is the same.

2 questions:

1) The tokenizer seems to use the `Tokenizer`lib: https://github.com/paperswithcode/galai/blob/main/galai/model.py#L75
2) Once converted the ckpts, should I upload them with my personal account?

Thanks!

**Comment by Sameedahmad** [comment]
Not working correctly right now.

**Comment by Sameedahmad** [comment]
@sgugger Can you guide us better?

**Comment by gsarti** [comment]
@mrm8488 would probably be best to include under the `facebook` org, some folks at HF like @patrickvonplaten should be able to upload them there

**Comment by Sameedahmad** [comment]
@patrickvonplaten We need your help on this one.

**Comment by RJT1990** [comment]
Hey guys, stoked for the integration - just one model specific thing, if user enters prompt like:

"[START_AMINO]MVATE[END_AMINO]" -> need to tokenize so the bit inside the special tokens is character-based tokenized -> i.e M, V, A, T, E. we have the logic in https://github.com/paperswithcode/galai/blob/main/galai/model.py, see "escape_custom_split_sequence".

**Comment by Sameedahmad** [comment]
Any update?

**Comment by mrm8488** [comment]
> Any update?

It is WIP! Thanks! :)

**Comment by patrickvonplaten** [comment]
Model is fully added see: https://huggingface.co/models?other=galactica - thanks a lot @mrm8488 for you work here! Closing this :-)
