### ISSUE TITLE
[CamemBERT] Potential error in the docs

### ISSUE THREAD

**Issue by manueltonneau** [huggingface/transformers#2028]
Thanks for the great work on this repo! As I was going through the details about the available pre-trained models (https://huggingface.co/transformers/v2.2.0/pretrained_models.html), I spotted what I think is an error in the description of camembert-base (12-layer, 768-hidden, 12-heads, 110M parameters; CamemBERT using the BERT-base architecture). Isn't it RoBERTa-based?

**Comment by julien-c** [comment]
RoBERTa and BERT (and CamemBERT) share mostly the same model architecture. Most of the differences lie in:
- the tokenizers
- the pre-training method

cc @LysandreJik

**Comment by manueltonneau** [comment]
Cool, thanks for the reply! :)
