### ISSUE TITLE
cannot import name 'WEIGHTS_NAME'

### ISSUE THREAD

**Issue by aclifton314** [huggingface/transformers#2030]
## 🐛 Bug

Model I am using (Bert, XLNet....): gpt2

Language I am using the model on (English, Chinese....): english

The problem arise when using:
* [X] the official example scripts: `run_lm_finetuning.py`
* [ ] my own modified scripts: (give details)

## To Reproduce

 
1. Obtain `transformers` from zip file on github.
2. try to run `run_lm_finetuning.py` using the example in the documentation.

``` python
Traceback (most recent call last):
  File "run_lm_finetuning.py", line 45, in <module>
    from transformers import (WEIGHTS_NAME, AdamW, get_linear_schedule_with_warmup,
ImportError: cannot import name 'WEIGHTS_NAME' from 'transformers' (unknown location)
```

## Environment

* OS: Ubuntu 18.04.3
* Python version: 3.7.3
* PyTorch version: 1.3.1+cpu
* PyTorch Transformers version (or branch): whichever version is included in the zip file off github
* Using GPU ? No
* Distributed of parallel setup ? No
* Any other relevant information: None.

## Additional context

I tried to obtain transformers from source using `git clone https://github.com/huggingface/transformers.git` but I got a timeout error (which is why I opted to try to zip file).

**Comment by TheEdoardo93** [comment]
This is **not** a bug! It works as expected.
```
> from transformers import WEIGHTS_NAME
> 
```

I've tried with the latest version of Transformers, installed with `pip install transformers`

The variable _WEIGHTS_NAME_ is located in [file_utils.py](https://github.com/huggingface/transformers/blob/49108288ba6e6dcfe554d1af98699ae7a1e6f39c/transformers/file_utils.py)

> ##  Bug
> Model I am using (Bert, XLNet....): gpt2
> 
> Language I am using the model on (English, Chinese....): english
> 
> The problem arise when using:
> 
> * [x]  the official example scripts: `run_lm_finetuning.py`
> * [ ]  my own modified scripts: (give details)
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Obtain `transformers` from zip file on github.
> 2. try to run `run_lm_finetuning.py` using the example in the documentation.
> 
> ```python
> Traceback (most recent call last):
>   File "run_lm_finetuning.py", line 45, in <module>
>     from transformers import (WEIGHTS_NAME, AdamW, get_linear_schedule_with_warmup,
> ImportError: cannot import name 'WEIGHTS_NAME' from 'transformers' (unknown location)
> ```
> 
> ## Environment
> * OS: Ubuntu 18.04.3
> * Python version: 3.7.3
> * PyTorch version: 1.3.1+cpu
> * PyTorch Transformers version (or branch): whichever version is included in the zip file off github
> * Using GPU ? No
> * Distributed of parallel setup ? No
> * Any other relevant information: None.
> 
> ## Additional context
> I tried to obtain transformers from source using `git clone https://github.com/huggingface/transformers.git` but I got a timeout error (which is why I opted to try to zip file).

**Comment by aclifton314** [comment]
Hmm, the error is removed when I use the `pip` version as well but remains with the zipped version. I'll close this out and rely on the version that comes from `pip`.
