### ISSUE TITLE
Add eval and test for the example run_ner_no_trainer.py

### ISSUE THREAD

**Issue by fuzihaofzh** [huggingface/transformers#20312]
### Feature request

Hi, thanks for the great work. I just go through the example "transformers/examples/pytorch/token-classification/", I found that run_ner.py has eval and test. However, for run_ner_no_trainer.py, there is no eval or test. I just wonder if it is possible to add these components?

### Motivation

Enhance the example code

### Your contribution

I can help to test the code.

**Comment by sgugger** [comment]
Evaluation is done at every epoch in this script, not sure what more you need. The `no_trainer` scripts are more barebone on purpose, to make it easy for users to customize them.

**Comment by larsbun** [comment]
Evaluating NER performance with subword tokenization is complicated. It would be very instructive if you could include code that outputs one prediction for each token in the original corpus.  This would have to address the behavior of tokenizers, such as splitting words with hyphens and not prepending them with ##, etc.
