### ISSUE TITLE
Typo in modeling_albert.py for mask_token

### ISSUE THREAD

**Issue by blmoistawinde** [huggingface/transformers#2031]
## 🐛 Bug

Model I am using (Bert, XLNet....): Albert

Language I am using the model on (English, Chinese....): English

## To Reproduce

```
tokenizer_class, pretrained_weights = AlbertTokenizer, "albert-base-v1"
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
print(tokenizer.mask_token)   # [MASK]>
print(tokenizer.mask_token_id)  # 1 (same as  <unk>)
```

I think the typo lies here https://github.com/huggingface/transformers/blob/fbaf05bd92249b6dd961f5f8d60eb0892c541ac8/transformers/tokenization_albert.py#L69

## Expected behavior

mask_token should be "[MASK]" and mask_token_id should be 4

## Environment

* OS: Windows 10
* Python version: 3.6.9
* PyTorch version:  1.2.0
* PyTorch Transformers version (or branch): 2.2.0

**Comment by thomwolf** [comment]
Indeed, good catch, thanks! Fixed on master.
