### ISSUE TITLE
Mismatch in torch size

### ISSUE THREAD

**Issue by devyndonahue** [huggingface/transformers#20327]
I am trying to fine-tune an NER model using "malduwais/distilbert-base-uncased-finetuned-ner" model, in the dataset I am finetuning on there are only 5 features as opposed to 9 in the one this model was trained on. I get this error when calling trainer.train()

```
RuntimeError: Error(s) in loading state_dict for DistilBertForTokenClassification:
	size mismatch for classifier.weight: copying a param with shape torch.Size([9, 768]) from checkpoint, the shape in current model is torch.Size([5, 768]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([5]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

is there a way to adjust the size when finetuning? Thank you

**Comment by sgugger** [comment]
As the error message told you, load your model with `ignore_mismatched_sizes=True`.
