### ISSUE TITLE
cannot import electratokenizer or model. It works on colabnotebook but not in python

### ISSUE THREAD

**Issue by prsatyal** [huggingface/transformers#20329]
### System Info

i have tensorflow version 2.11.0 and transformer version 4.24.0

and i cannot import TFElectraModel. It works for me in google colab but not in my pc.

from transformers import  TFElectraModel
gives me the following error

RuntimeError: Failed to import transformers.models.electra.modeling_tf_electra because of the following error (look up to see its traceback):
No module named 'keras.saving.hdf5_format'

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

in windows install python 3.10
install tensorflow
install numpy
install scikit-learn
install transformers

import tensorflow as tf
import numpy as np
import transformers
from transformers import ElectraTokenizer
from transformers import TFElectraModel

### Expected behavior

It should load the TFElectraModel, i have loaded this model a million times ins google colab and it still works there even now.

**Comment by sgugger** [comment]
Transformers is not currently compatible with TensorFlow 2.11 (which broke a lot of things compared to the previous versions). It should be fixed on main so you can either do:
- an install of Transformers from source
- or downgrade your TensorFlow to 2.10

**Comment by prsatyal** [comment]
Hi There! I figured as much so is downgraded to tensorflow 2.10 and
installed transformers from the source
