### ISSUE TITLE
OPTForCausalLM - ValueError: The following `model_kwargs` are not used by the model: ['new_doc']

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/transformers#20332]
### System Info

Hello. I am using this model : https://huggingface.co/facebook/galactica-6.7b

The example is like this pretty straight

```
from transformers import AutoTokenizer, OPTForCausalLM

tokenizer = AutoTokenizer.from_pretrained("facebook/galactica-6.7b")
model = OPTForCausalLM.from_pretrained("facebook/galactica-6.7b")

input_text = "The Transformer architecture [START_REF]"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))
```

**new GALACTICA model supports the below inputs but I am getting error. This is the code I run**

```
from transformers import AutoTokenizer, OPTForCausalLM

tokenizer = AutoTokenizer.from_pretrained("facebook/galactica-6.7b")
model = OPTForCausalLM.from_pretrained("facebook/galactica-6.7b")

input_text = "The benefits of deadlifting\n\n"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids

outputs = model.generate(input_ids,new_doc=True, top_p=0.7, max_length=2000)
print(tokenizer.decode(outputs[0]))
```

![image](https://user-images.githubusercontent.com/19240467/202852602-74833f48-a83b-406e-8d6f-0f51e38ef859.png)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

test

### Expected behavior

test

**Comment by raghavanone** [comment]
@FurkanGozukara I do not see the new_doc parameter accepted neither in code nor in example scripts ? Can you point me to where you got example scripts with new_doc parameter ?

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara I do not see the new_doc parameter accepted neither in code nor in example scripts ? Can you point me to where you got example scripts with new_doc parameter ?

https://github.com/paperswithcode/galai

![image](https://user-images.githubusercontent.com/19240467/203018858-60dfd7fd-f186-4fe8-8217-ab3ab493f9cc.png)

**Comment by raghavanone** [comment]
@FurkanGozukara I think there is an mix up, the huggingface api so far does not support new_doc parameter, the new_doc parameter is present in galai library released by paperwithcode .

https://github.com/paperswithcode/galai/blob/f6d9b0a5b35a0eda53597a5ea7d51963bfc05de1/galai/model.py#L88
