### ISSUE TITLE
Add MobileNetV1

### ISSUE THREAD

**Issue by atturaioe** [huggingface/transformers#20335]
### Model description

MobileNets are small, low-latency, low-power models parameterized to meet the resource constraints of a variety of use cases. They can be built upon for classification, detection, embeddings and segmentation similar to how other popular large scale models, such as Inception, are used. MobileNets can be run efficiently on mobile devices [...] MobileNets trade off between latency, size and accuracy while comparing favorably with popular models from the literature.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

[Paper](https://arxiv.org/abs/1704.04861)

Hi there, I wonder whether MobileNetV1 is going to be added or not, I see there's already a dedicated [card](https://huggingface.co/google/mobilenet_v1_1.0_224) on model's hub.

@hollance

**Comment by hollance** [comment]
There's an open PR for it that is (almost) ready to merge. I just need to rebase it because it conflicts with MobileNetV2 that was recently added. I'll probably get around to this later this week.

See the PR: https://github.com/huggingface/transformers/pull/17799

**Comment by atturaioe** [comment]
Oh, thanks. Closing this issue.

**Comment by hollance** [comment]
Just a FYI: it has been merged now with the main branch of Transformers. :-)
