### ISSUE TITLE
Integrate Timm models as vision encoders in Vision encoder decoder models 

### ISSUE THREAD

**Issue by gagan3012** [huggingface/transformers#20358]
### Feature request

Hello, 
I would like to use timm models as vision encoders in vision encoder-decoder model who can I do so?

### Motivation

Timm models are very powerful and allow a lot of image processing which would allow us to make better document AI models

### Your contribution

I would be down to help out with PR

**Comment by gagan3012** [comment]
@NielsRogge

**Comment by NielsRogge** [comment]
Hi,

I don't think that makes sense as for the Vision encoder-decoder framework, one needs a Transformer-based encoder or at least an encoder that outputs a sequence of hidden states, which can be used for cross-attention with the Transformer-based language decoder. Given that most backbones in timm are convolution-based, which output 3D feature maps, one would first need to flatten/project them into a sequence of hidden states.

The VisionEncoderDecoderModel [framework](https://huggingface.co/docs/transformers/model_doc/vision-encoder-decoder) currently supports ViT, DeiT, BEiT and Swin Transformer, which is already a fair amount of models.

**Comment by gagan3012** [comment]
I was more looking to use Swin with non-square image sizes and the Timm implementation allows us to do that and I would like to implement SwinV2 with bert

**Comment by NielsRogge** [comment]
>  I was more looking to use Swin with non-square image sizes

Our implementation also allows that, did you try it?

**Comment by NielsRogge** [comment]
```
from transformers import AutoModelForImageClassification
import torch

model = AutoModelForImageClassification.from_pretrained("microsoft/swinv2-tiny-patch4-window8-256")

pixel_values = torch.randn(1, 3, 244, 522)

outputs = model(pixel_values)
```
