### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rhl2k** [huggingface/transformers#2036]
## ❓ Questions & Help

12/03/2019 09:12:25 - INFO - transformers.modeling_utils -   loading weights file model_check_points112/pytorch_model.bin
12/03/2019 09:12:40 - INFO - __main__ -   Creating features from dataset file at dev-v1.1.json
Traceback (most recent call last):
  File "run_squad.py", line 558, in <module>
    main()
  File "run_squad.py", line 547, in main
    result = evaluate(args, model, tokenizer, prefix=global_step)
  File "run_squad.py", line 195, in evaluate
    dataset, examples, features = load_and_cache_examples(args, tokenizer, evaluate=True, output_examples=True)
  File "run_squad.py", line 296, in load_and_cache_examples
    version_2_with_negative=args.version_2_with_negative)
  File "/content/drive/My Drive/examples/utils_squad.py", line 97, in read_squad_examples
    input_data = json.load(reader)["data"]
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 4194293 (char 4194292)

**Comment by TheEdoardo93** [comment]
Please, post the command and all the parameters in order to understand deeply your problem.

> ##  Questions & Help
> 12/03/2019 09:12:25 - INFO - transformers.modeling_utils - loading weights file model_check_points112/pytorch_model.bin
> 12/03/2019 09:12:40 - INFO - **main** - Creating features from dataset file at dev-v1.1.json
> Traceback (most recent call last):
> File "run_squad.py", line 558, in 
> main()
> File "run_squad.py", line 547, in main
> result = evaluate(args, model, tokenizer, prefix=global_step)
> File "run_squad.py", line 195, in evaluate
> dataset, examples, features = load_and_cache_examples(args, tokenizer, evaluate=True, output_examples=True)
> File "run_squad.py", line 296, in load_and_cache_examples
> version_2_with_negative=args.version_2_with_negative)
> File "/content/drive/My Drive/examples/utils_squad.py", line 97, in read_squad_examples
> input_data = json.load(reader)["data"]
> File "/usr/lib/python3.6/json/**init**.py", line 299, in load
> parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
> File "/usr/lib/python3.6/json/**init**.py", line 354, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
> obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 4194293 (char 4194292)

**Comment by TheEdoardo93** [comment]
> Please, post the command and all the parameters in order to understand deeply your problem. Moreover, the environment (e.g. Python version, PyTorch version, TensorFlow version, Transformers version, OS)
> 
> > ## Questions & Help
> > 12/03/2019 09:12:25 - INFO - transformers.modeling_utils - loading weights file model_check_points112/pytorch_model.bin
> > 12/03/2019 09:12:40 - INFO - **main** - Creating features from dataset file at dev-v1.1.json
> > Traceback (most recent call last):
> > File "run_squad.py", line 558, in
> > main()
> > File "run_squad.py", line 547, in main
> > result = evaluate(args, model, tokenizer, prefix=global_step)
> > File "run_squad.py", line 195, in evaluate
> > dataset, examples, features = load_and_cache_examples(args, tokenizer, evaluate=True, output_examples=True)
> > File "run_squad.py", line 296, in load_and_cache_examples
> > version_2_with_negative=args.version_2_with_negative)
> > File "/content/drive/My Drive/examples/utils_squad.py", line 97, in read_squad_examples
> > input_data = json.load(reader)["data"]
> > File "/usr/lib/python3.6/json/**init**.py", line 299, in load
> > parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
> > File "/usr/lib/python3.6/json/**init**.py", line 354, in loads
> > return _default_decoder.decode(s)
> > File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
> > obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
> > obj, end = self.scan_once(s, idx)
> > json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 4194293 (char 4194292)

**Comment by rhl2k** [comment]
solved.its working now

**Comment by yyeunggg** [comment]
> solved.its working now

How do you solve this issue? I have the same errors

**Comment by AmarW-UCD** [comment]
I am also getting same error. How you solved it?

**Comment by rhl2k** [comment]
just remove non-asciii character from your data-set
