### ISSUE TITLE
Link to Google Colab notebook not working

### ISSUE THREAD

**Issue by jaimebw** [huggingface/transformers#20364]
Hi, it seems that the link to ```A notebook on how to [finetune BART for summarization with fastai using blurr](https://colab.research.google.com/github/ohmeow/ohmeow_website/blob/master/_notebooks/2020-05-23-text-generation-with-blurr.ipynb).``` is broken.  
@patrickvonplaten

**Comment by sgugger** [comment]
cc @ohmeow who wrote the notebook.
