### ISSUE TITLE
Hugging face community on fb group 

### ISSUE THREAD

**Issue by Mohammed20201991** [huggingface/transformers#20370]
Hello everyone you can  join our group to discuss new state-of-the-art methods in deep learning, machine learning, and natural language processing through the  below :
[link](https://fb.me/g/p_Qe5xCLF7zxgu4sYn/NRWMjdeM)

**Comment by osanseviero** [comment]
Hey there! Thanks a lot for creating and sharing the group :fire: 
FYI, there is also a community Discord server with over 16000 members. You can join in [hf.co/join/discord](hf.co/join/discord) :hugs:
