### ISSUE TITLE
[CodeGen] RuntimeError: where expected condition to be a boolean tensor, but got a tensor with dtype Half

### ISSUE THREAD

**Issue by jrdzha** [huggingface/transformers#20397]
### System Info

transformers==4.21.2
torch==1.10.2+cu113

HW: 12 cpu, 90gb ram, 1xA100-80g

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

**The following works with CodeGen-350M-mono / CodeGen-6B-mono**

```
import torch
from transformers import AutoTokenizer, CodeGenForCausalLM

tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen-350M-mono")
model = CodeGenForCausalLM.from_pretrained("Salesforce/codegen-350M-mono", device_map="auto")
```

**But throws the RuntimeError for CodeGen-16B-mono**

```
import torch
from transformers import AutoTokenizer, CodeGenForCausalLM

tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen-16B-mono")
model = CodeGenForCausalLM.from_pretrained("Salesforce/codegen-16B-mono", device_map="auto")
```

### Expected behavior

Expect the 16B model to work as well.

**Comment by sgugger** [comment]
cc @younesbelkada

**Comment by jrdzha** [comment]
Another way to reproduce is to use https://github.com/huggingface/transformers-bloom-inference

and run:

```
make codegen-mono
```

**Comment by jrdzha** [comment]
It seems this issue is inconsistent. I did have it work once, but without changing any code... I'll spend some more time trying to reproduce this more reliably...
