### ISSUE TITLE
can't from transformers import TFBertModel 

### ISSUE THREAD

**Issue by minig0lem** [huggingface/transformers#20393]
### System Info

- `transformers` version: 4.24.0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.8
- Huggingface_hub version: 0.11.0
- PyTorch version (GPU?): 1.13.0+cpu (False)
- Tensorflow version (GPU?): 2.11.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@LysandreJik @Rocket

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

![image](https://user-images.githubusercontent.com/92259521/203403557-481c7ac6-fbd7-4a75-8cbb-088f25a8f43e.png)

### Expected behavior

from transformers import BertTokenizer works well.

but from transformers import TFBertModel doesn't work .

It runs like picture above.

How do I resolve this error(ModuleNotFoundError: No module named 'keras.saving.hdf5_format')?

**Comment by sgugger** [comment]
This is due to the latest release of TensorFlow which broke many things. You need to either install `transformers` from source (this is fixed on the main branch) or downgrade `Tensorflow` to 2.10. :-)

**Comment by lvwerra** [comment]
This also broke the `evaluate` CI :) Will fix to `<=2.10` for now.
