### ISSUE TITLE
XLM-R Support

### ISSUE THREAD

**Issue by josecannete** [huggingface/transformers#2040]
## ❓ Questions & Help

Hello!

Is there a way to use XLM-R (https://github.com/pytorch/fairseq/blob/master/examples/xlmr/README.md) with the library of transformers? maybe via RoBERTa? can you provide some guidance on this please?

Thank you in advance

**Comment by TheEdoardo93** [comment]
The latest news about using XLM-R model with Transformers are discussed in #1769 
Briefly, **at the moment it's not possible to use this model with Transformers directly**.

**Comment by josecannete** [comment]
Thank you,

I'm closing this one and keep an eye in #1769
