### ISSUE TITLE
How do I load a pretrained file offline?

### ISSUE THREAD

**Issue by zysNLP** [huggingface/transformers#2041]
## ❓ Questions & Help

Hi, when I use "RobertaModel.from_pretrained(roberta.large)" to load model. A progress bar appears to download the pre-training model. I've already downloaded files like "roberta-large-pytorch_model.bin ". How can I stop automatically downloading files to the ".cache" folder and instead specify these pre-training files I downloaded?

**Comment by shashankMadan-designEsthetics** [comment]
You can do it, instead of loading `from_pretrained(roberta.large)` like this download the respective `config.json` and <mode_name>.bin and save it on your folder then just write 
`.from_pretrained('Users/<location>/<your folder name>')` and thats about it.

**Comment by zysNLP** [comment]
OK, Thank you very much!

**Comment by gpiat** [comment]
@shashankMadan-designEsthetics' solution may require git-lfs to download the files of some models. If you are not a sudoer, this can be a problem. The most reliable and easy solution I've found is this:
```
from transformers import AutoModel, AutoTokenizer

# Do this on a machine with internet access
model = AutoModel.from_pretrained("model-name")
tokenizer = AutoTokenizer.from_pretrained("model-name")

_ = model.save_pretrained("./model-dir")
_ = tokenizer.save_pretrained("./model-dir")
```
Then you can do whatever you want with your model -- send it to a computing cluster, put it on a flash drive etc. Then you just do:
```
model = AutoModel.from_pretrained("path/model-dir")
tokenizer = AutoTokenizer.from_pretrained("path/model-dir")
```

**Comment by pundumx** [comment]
> You can do it, instead of loading `from_pretrained(roberta.large)` like this download the respective `config.json` and `<mode_name>.bin` and save it on your folder then just write `.from_pretrained('Users/<location>/<your folder name>')` and thats about it.

This approach worked for facebook/m2m100_418M only after I downloaded every file at https://huggingface.co/facebook/m2m100_418M/tree/main except .gitattributes and README.md. (I can't swear that every single one is required, but I leave trial and error to determine the minimal set as an exercise for the reader.)
