### ISSUE TITLE
Migarate old cache to transformers v4.22.0

### ISSUE THREAD

**Issue by yzGao22** [huggingface/transformers#20428]
### System Info

- `transformers` version: 4.22.0
- Platform: Linux-5.4.0-1089-aws-x86_64-with-debian-buster-sid
- Python version: 3.7.10
- Huggingface_hub version: 0.11.0
- PyTorch version (GPU?): 1.11.0+cu102 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Who can help?

@LysandreJik

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

When update transformers from v4.12.3 to v4.22.0,  got following message:

```
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
Moving 55 files to the new cache system
0%
0/55 [00:00<?, ?it/s]
There was a problem when trying to move your cache:

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/utils/hub.py", line 1127, in <module>
    move_cache()

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/utils/hub.py", line 1071, in move_cache
    hub_metadata[url] = get_hub_metadata(url, token=token)

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/utils/hub.py", line 996, in get_hub_metadata
    huggingface_hub.file_download._raise_for_status(r)


Please file an issue at https://github.com/huggingface/transformers/issues/new/choose and copy paste this whole message and we will do our best to help.
```

### Expected behavior

The migrating process can be done successfully.

**Comment by qwead520** [comment]
I am also facing this issue with 4.24
