### ISSUE TITLE
Could you do `pip show huggingface_hub`?

### ISSUE THREAD

**Issue by wccccp** [huggingface/transformers#20448]
Could you do `pip show huggingface_hub`?

_Originally posted by @NielsRogge in https://github.com/huggingface/transformers/issues/20447#issuecomment-1327215502_

**Comment by averad** [comment]
This issue appears to have been opened in error. If this is the case @wccccp you can close this Issue Request using the buttons below 👇

**Comment by wccccp** [comment]
> This issue appears to have been opened in error. If this is the case @wccccp you can close this Issue Request using the buttons below 👇

thank you
