### ISSUE TITLE
ImportError: cannot import name 'CommitOperationAdd' from 'huggingface_hub' (C:\Users\46213\anaconda3\lib\site-packages\huggingface_hub\__init__.py)

### ISSUE THREAD

**Issue by wccccp** [huggingface/transformers#20447]
### System Info

windows
python=3.9
transformers              4.23.1
pytorch                   1.13.0          py3.9_cuda11.6_cudnn8_0    pytorch

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

>>> import transformers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\46213\anaconda3\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\Users\46213\anaconda3\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\46213\anaconda3\lib\site-packages\transformers\utils\__init__.py", line 48, in <module>
    from .hub import (
  File "C:\Users\46213\anaconda3\lib\site-packages\transformers\utils\hub.py", line 32, in <module>
    from huggingface_hub import (
ImportError: cannot import name 'CommitOperationAdd' from 'huggingface_hub' (C:\Users\46213\anaconda3\lib\site-packages\huggingface_hub\__init__.py)
>>>

### Expected behavior

please help me to solve the problem！！！

**Comment by NielsRogge** [comment]
Could you do `pip show huggingface_hub`?

**Comment by wccccp** [comment]
> 

(base) C:\Users\46213>pip show huggingface_hub
Name: huggingface-hub
Version: 0.10.1
Summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
Home-page: https://github.com/huggingface/huggingface_hub
Author: Hugging Face, Inc.
Author-email: julien@huggingface.co
License: Apache
Location: c:\users\46213\anaconda3\lib\site-packages
Requires: typing-extensions, requests, filelock, tqdm, packaging, pyyaml
Required-by: transformers, ltp, evaluate, datasets

**Comment by SQPferrer** [comment]
For anyone finding this now, if you installed `transformers` and/or `huggingface_hub` with pip, try re-installing with conda. That solved it for me.

**Comment by SQPferrer** [comment]
i.e. `conda install -c conda-forge transformers huggingface_hub`

**Comment by xiao-seu** [comment]
delete package "charser_normalizer" manually then reinstall package "charser_normalizer" may work.
