### ISSUE TITLE
Tokenization in quickstart guide fails

### ISSUE THREAD

**Issue by yenicelik** [huggingface/transformers#2047]
## 🐛 Bug

The same issue as in #226 re-appears in transformers==2.2.1 (it works on 2.1!)

I just encountered the same issue as @dhirajmadan1 with `transformers==2.2.1`. Is this expected somehow?

I am following the quickstart guide: https://huggingface.co/transformers/quickstart.html

## To Reproduce

```
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Run an example text through this:
text = "[CLS] Who was Jim Henson ? [SEP] Jim Henson was a puppeteer [SEP]"
tokenized_text = tokenizer.tokenize(text)

masked_index = 8
tokenized_text[masked_index] = '[MASK]'
predicted_tokenized_sentence = ['[CLS]', 'who', 'was', 'jim', 'henson', '?', '[SEP]', 'jim', '[MASK]', 'was', 'a', 'puppet', '##eer', '[SEP]']
        
```

## Expected behavior

This should not fail:

```assert tokenized_text == ['[CLS]', 'who', 'was', 'jim', 'henson', '?', '[SEP]', 'jim', '[MASK]', 'was', 'a', 'puppet', '##eer', '[SEP]']```

## Environment

* OS: Mac
* Python version: 3.6
* PyTorch version: 1.3.1
* PyTorch Transformers version (or branch): 2.1 (latest-minor)
* Using GPU no
* Distributed of parallel setup no
* Any other relevant information:

**Comment by watkinsm** [comment]
Oops, that appears to be my fault. Should be a quick fix though, so I'll make a PR on it right away. Sorry! :grimacing:

**Comment by yenicelik** [comment]
Thanks man! :) yeah no worries, thought it may be a good idea to report haha

**Comment by BramVanroy** [comment]
As far as I can tell, this is still incorrect on the website.
