### ISSUE TITLE
Error when getting the long-t5 model

### ISSUE THREAD

**Issue by Magicen0722** [huggingface/transformers#20484]
### System Info

When I get the relevant pipline or the corresponding model and tokenizer from this page, I get the `KeyError: 'longt5'`

### Who can help?

@patrickvonplaten 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://huggingface.co/google/long-t5-tglobal-base
my code:
```
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("google/long-t5-tglobal-base")
model = AutoModelForSeq2SeqLM.from_pretrained("google/long-t5-tglobal-base")
```
Full error output:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<command-440662132347528> in <module>
      1 from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
      2 
----> 3 tokenizer = AutoTokenizer.from_pretrained("google/long-t5-tglobal-base")
      4 model = AutoModelForSeq2SeqLM.from_pretrained("google/long-t5-tglobal-base")

/databricks/python/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    400     tokenizer_config = get_tokenizer_config("bert-base-uncased")
    401     # This model does not have a tokenizer config so the result will be an empty dict.
--> 402     tokenizer_config = get_tokenizer_config("xlm-roberta-base")
    403 
    404     # Save a pretrained tokenizer locally and you can reload its config

/databricks/python/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    430         ("unispeech", "UniSpeech"),
    431         ("unispeech-sat", "UniSpeechSat"),
--> 432         ("van", "VAN"),
    433         ("videomae", "VideoMAE"),
    434         ("vilt", "ViLT"),

KeyError: 'longt5'
```
Any kind of help is appreciated!

### Expected behavior

Correct import of models and corresponding piplines

**Comment by atturaioe** [comment]
Hi, what `transformers` version are you using?

**Comment by Magicen0722** [comment]
> Hi, what `transformers` version are you using?

I am using `transformers==4.24.0`

**Comment by patrickvonplaten** [comment]
@ArthurZucker could you take a look here?

**Comment by ArthurZucker** [comment]
Not really able to reproduce the code for now, but will have a look! I also used `transformers==4.24.0` and the import worked. It was added 6 month ago see [here](https://github.com/huggingface/transformers/pull/16792). Also can confirm that `("longt5", "LongT5"),` is [in the auto config](https://github.com/ArthurZucker/transformers/blob/main/src/transformers/models/auto/configuration_auto.py#L391).
