### ISSUE TITLE
How to reproduce the machine translation experiments in Attention is all you need.

### ISSUE THREAD

**Issue by shizhediao** [huggingface/transformers#20482]
### Feature request

I want to reproduce the experiments described in _Attention is all you need_, which is a transformer base model from scratch. The model architecture is the same as _Attention is all you need_.
In other words, I am looking for a transformer base model to train from scratch with HuggingFace.

### Motivation

Reproduce the Transformer experiments in machine translation. I found that there are many pre-trained models (e.g., T5, BART, MariaMT), but I would like to train a transformer base model from scratch to compare different optimizers during pre-training.

### Your contribution

I found a previous issue here but not sure whether it is the right way to go. https://github.com/huggingface/transformers/issues/12386

**Comment by shizhediao** [comment]
Hi,
I am trying to reproduce the performance of transformer-base (from attention is all you need) on WMT14.
I am using `FSMT` because I cannot find an implementation of the transformer.
I was wondering which dataset and tokenizer are the best choices. 
1. `stas/wmt14-en-de-pre-processed` with `facebook/wmt19-en-de`
2. `wmt14` with `facebook/wmt19-en-de`
Especially, I do not know which tokenizer should be used.

Thanks in advance if you could provide some suggestions!

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to discuss such questions as we keep issues for bugs and feature requests only.

**Comment by shizhediao** [comment]
> Please use the [forums](https://discuss.huggingface.co/) to discuss such questions as we keep issues for bugs and feature requests only.

OK, sorry about this.
