### ISSUE TITLE
Changing the number of hidden layers for BERT

### ISSUE THREAD

**Issue by paul-you** [huggingface/transformers#2048]
## ❓ Questions & Help

Hello, 

when reducing the number of hidden layers for BERT, say from 12 to 3, which layers are loaded from the pretrained model, the first 3 layers or the last 3 ones? and is there a way to control this?

Thanks in advance

**Comment by thomwolf** [comment]
Hi,
The first ones are loaded and there is currently no simple way to control this.

**Comment by Colanim** [comment]
**Is there any evidence than the first layers is the best choice when reducing the number of layers ?**

For example in your article about Distil-Bert, you chose to initialize the student by taking the even layers. Why so ?

**Comment by VictorSanh** [comment]
> For example in your article about Distil-Bert, you chose to initialize the student by taking the even layers. Why so ?

It empirically produces stronger performance.
There are some other empirical evidences in [this paper](https://arxiv.org/abs/1909.11556) from Angela Fan, Edouard Grave and Armand Joulin.

**Comment by dongteng** [comment]
I also want to ask this
