### ISSUE TITLE
ModuleNotFoundError: No module named 'git'

### ISSUE THREAD

**Issue by wrzzd** [huggingface/transformers#2049]
## 🐛 Bug
`
Traceback (most recent call last):

  File "train.py", line 32, in <module>

    from distiller import Distiller

  File "~/transformers/examples/distillation/distiller.py", line 40, in <module>

    from utils import logger

  File "~/transformers/examples/distillation/utils.py", line 18, in <module>

    import git

ModuleNotFoundError: No module named 'git'

`
how to install git package?

**Comment by iedmrc** [comment]
with referring to that file https://github.com/huggingface/transformers/blob/master/examples/distillation/requirements.txt

run:
`pip install -r requirements.txt`

**Comment by wrzzd** [comment]
> with referring to that file https://github.com/huggingface/transformers/blob/master/examples/distillation/requirements.txt
> 
> run:
> `pip install -r requirements.txt`

thx, got it~
