### ISSUE TITLE
owlvit image guided detection does not work in gpu (cuda)

### ISSUE THREAD

**Issue by fcakyon** [huggingface/transformers#20513]
### System Info

- `transformers` version: 4.25.0.dev0
- Platform: Linux-5.4.0-132-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.11.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@alaradirik @NielsRogge 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run this demo in gpu: https://huggingface.co/spaces/adirik/image-guided-owlvit

Get this error: 

```bash
  File ".../lib/python3.8/site-packages/transformers/models/owlvit/image_processing_owlvit.py", line 420, in post_process_image_guided_detection
    target_boxes = target_boxes * scale_fct[:, None, :]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

### Expected behavior

I have posted a possible fix in this comment: https://github.com/huggingface/transformers/pull/20160#discussion_r1036281555

**Comment by alaradirik** [comment]
Hi @fcakyon, thanks for bringing this up! You can expect a fix PR shortly.

As a side note, we open new issues and PRs for bugs to make it easier to track improvements. You can directly include your fix suggestions in the issue.

**Comment by fcakyon** [comment]
I will try to open a PR, give me few mins 👍

**Comment by fcakyon** [comment]
@alaradirik tried to open the related pr here: https://github.com/huggingface/transformers/pull/20521
