### ISSUE TITLE
'WhisperTokenizer' object has no attribute 'set_prefix_tokens'

### ISSUE THREAD

**Issue by nethermanpro** [huggingface/transformers#20519]
### System Info

- `transformers` version: 4.24.0
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.27
- Python version: 3.9.15
- Huggingface_hub version: 0.11.0
- PyTorch version (GPU?): 1.13.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Yes

### Who can help?

@LysandreJik

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

from transformers import WhisperTokenizer
tokenizer = WhisperTokenizer.from_pretrained("openai/whisper-medium", language="spanish", cache_dir="./pretrained_models")
tokenizer.set_prefix_tokens(language="english")

AttributeError: 'WhisperTokenizer' object has no attribute 'set_prefix_tokens'

### Expected behavior

![image](https://user-images.githubusercontent.com/75082385/204983801-7b23dffc-5e52-4dca-a625-e7d9cf8e8745.png)

This method should exist according to the documentation

**Comment by JuanFKurucz** [comment]
Hi @nethermanpro, not a maintainer here, but I think I know what is going on.  

It seems `transformers 4.24.0` hasn't yet implemented the `set_prefix_tokens`, this method is in the main branch, if you want to use it, you will need to install transformers directly from this repository `pip install git+https://github.com/huggingface/transformers.git` or wait for the next stable release. 

The documentation you are checking seems to be https://huggingface.co/docs/transformers/main/en/model_doc/whisper which is the documentation of the main branch, to check the documentation of `4.24.0` you can 
select it at the top left dropdown where it says 
`main`. https://huggingface.co/docs/transformers/v4.24.0/en/model_doc/whisper#transformers.WhisperTokenizer

**Comment by nethermanpro** [comment]
Thanks, I think that solves my problem.
