### ISSUE TITLE
cannot import name 'get_linear_schedule_with_warmup' from 'transformers.optimization'

### ISSUE THREAD

**Issue by FOXaaFOX** [huggingface/transformers#2056]
## ❓ Questions & Help
cannot import name 'get_linear_schedule_with_warmup' from 'transformers.optimization'

**Comment by stefan-it** [comment]
This could be related to this issue here: https://github.com/huggingface/transformers/issues/1837 :)

**Comment by FOXaaFOX** [comment]
I copied the&nbsp;get_linear_schedule_with_warmup function code add to my project in the&nbsp;transformers/optimization.py
and then&nbsp;it worked&nbsp;
Thank you for developing such an brilliant library.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Stefan Schweter"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 上午7:19
收件人:&nbsp;"huggingface/transformers"<transformers@noreply.github.com&gt;;
抄送:&nbsp;"FOXaaFOX"<zhangyueaijia@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huggingface/transformers] cannot import name 'get_linear_schedule_with_warmup' from 'transformers.optimization' (#2056)




This could be related to this issue here: #1837 :)
