### ISSUE TITLE
Missing support for token sampling in XLMRobertaTokenizer (sentencepiece) 

### ISSUE THREAD

**Issue by talbaumel** [huggingface/transformers#20578]
### Feature request

Hi all, token sampling is supported by the sentencepiece library, but the kwargs required to enable it are blocked by the wrapper (`_tokenize` as no `**kwargs` param)

This simple fix will enable support for token sampling 🎉

### Motivation

Token sampling is awesome, it will enable learning a more robust model 👍

### Your contribution

In `XLMRobertaTokenizer.py`
```
def _tokenize(self, text, **kwargs):
        enable_sampling = kwargs.get("enable_sampling", False)
        if enable_sampling:
            return self.sp_model.EncodeAsPieces(text)
        else:
            return self.sp_model.sample_encode_as_pieces(text, nbest_size=kwargs['nbest_size'], alpha=kwargs['alpha'])
```

And in `tokenization_utils_base.py`:
Line 318 --> `def split_on_tokens(tok_list, text, **kwargs):`
Line 338 --> `self._tokenize(token) if token not in self.unique_no_split_tokens else [token]`

**Comment by dkarmon** [comment]
+ 1

**Comment by KarinBrisker** [comment]
+1
