### ISSUE TITLE
fail to import  'microsoft/swin-tiny-patch4-window7-224' in AutoConfig

### ISSUE THREAD

**Issue by XZhang97666** [huggingface/transformers#20579]
### System Info

OSError: microsoft/swin-tiny-patch4-window7-224 does not appear to have a file named config.json. Checkout 'https://huggingface.co/microsoft/swin-tiny-patch4-window7-224/None' for available files

### Who can help?

@LysandreJik

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

NA

### Expected behavior

import 'microsoft/swin-tiny-patch4-window7-224' successful

**Comment by atturaioe** [comment]
Hi, @XZhang97666. It seems that config.json file is in the right place(https://huggingface.co/microsoft/swin-tiny-patch4-window7-224/blob/main/config.json). 
Could you please tell what version of `transformers` you're using?
Also have you tried to run the snippet code that at https://huggingface.co/microsoft/swin-tiny-patch4-window7-224?

**Comment by XZhang97666** [comment]
> Hi, @XZhang97666. It seems that config.json file is in the right place(https://huggingface.co/microsoft/swin-tiny-patch4-window7-224/blob/main/config.json). Could you please tell what version of `transformers` you're using? Also have you tried to run the snippet code that at https://huggingface.co/microsoft/swin-tiny-patch4-window7-224?

Yes. I tried https://huggingface.co/microsoft/swin-tiny-patch4-window7-224, which works. However, another task does not even with the same transformers version (4.22.2).

**Comment by XZhang97666** [comment]
> Hi, @XZhang97666. It seems that config.json file is in the right place(https://huggingface.co/microsoft/swin-tiny-patch4-window7-224/blob/main/config.json). Could you please tell what version of `transformers` you're using? Also have you tried to run the snippet code that at https://huggingface.co/microsoft/swin-tiny-patch4-window7-224?

I found the issue. My task generate a local folder called "microsoft/..."

**Comment by NielsRogge** [comment]
Closing this issue as it seems resolved, feel free to reopen.
