### ISSUE TITLE
`distilroberta-base` link missing

### ISSUE THREAD

**Issue by felicitywang** [huggingface/transformers#2057]
## ❓ Questions & Help

According to the current master code, link for `distilroberta-base` isn't provided. 
https://github.com/huggingface/transformers/blob/1ab8dc44b3d84ed1894f5b6a6fab58fb39298fc7/transformers/configuration_distilbert.py#L28-L33

**Comment by stefan-it** [comment]
It is located under `configuration_roberta.py`, see it [here](https://github.com/huggingface/transformers/blob/1c542df7e554a2014051dd09becf60f157fed524/transformers/configuration_roberta.py) :)

**Comment by felicitywang** [comment]
Thanks @stefan-it ! Missed the readme part of calling `distilroberta-base` with `RobertaModel` instead of `DistilBertModel`. Closing.
