### ISSUE TITLE
Flan-T5 returns incomplete results

### ISSUE THREAD

**Issue by dyxohjl666** [huggingface/transformers#20576]
### System Info

transformer version: 4.19.2
platform: Linux
python: 3.8.13

### Who can help?

@LysandreJik

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-large")
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-large")

inputs = tokenizer("Summarize the following text: Peter and Elizabeth took a taxi to attend the night party in the city. While in the party, Elizabeth collapsed and was rushed to the hospital. Since she was diagnosed with a brain injury, the doctor told Peter to stay besides her until she gets well. Therefore, Peter stayed with her at the hospital for 3 days without leaving.", return_tensors="pt")
outputs = model.generate(**inputs)
print(tokenizer.batch_decode(outputs, skip_special_tokens=True))

>>> ['Peter and Elizabeth went to a party together. Elizabeth collapsed and was rushed to the']
```

### Expected behavior

The generated text isn't complete. It seems to be truncated. I just use the example codes, so I have no idea about this problem.

Thanks for your help :)

**Comment by michaelroyzen** [comment]
You can set min_length and max_length in model.generate() to adjust the length of generation settings. By default, max_length is not very long.

**Comment by dyxohjl666** [comment]
It works! Thanks!

> You can set min_length and max_length in model.generate() to adjust the length of generation settings. By default, max_length is not very long.
