### ISSUE TITLE
Sensible default for Trainer's dataloader_num_workers argument

### ISSUE THREAD

**Issue by kmewhort** [huggingface/transformers#20581]
### Feature request

As a relative beginner with Transformers and ML, it took me quite a bit of performance analysis and fiddling to figure out why my GPU was being vastly underutilized in training on image classification.  I finally figured out that the bottleneck was dataloaders (as typical for image tasks, it has a few image transformations) and I got a 10X performance increase by setting `dataloader_num_workers` to 16.

Could this have a more a higher default to avoid this gotcha?  Maybe it could default to something like half the number of available CPUs?

### Motivation

It's frustrating for a beginner to have training times super slow because of an unset parameter.  It'd be great for the defaults to work well out-of-the-box.

### Your contribution

Happy to submit a PR if the idea is greenlit.

**Comment by sgugger** [comment]
It's hard to have a nice default that would work everywhere: for NLP tasks you wouldn't need this since the preprocessing is fast. How about doing something in the vision examples?
