### ISSUE TITLE
How to run a batch of data through BERT model?

### ISSUE THREAD

**Issue by yrf1** [huggingface/transformers#2059]
## ❓ Questions & Help

I understand how to run **1 data** point of d words through a BERT model, but how can I run **n data** sequence of words through the BERT model?

Nvm solved this issue.

I can just pass sth like a 2xd data that looks like this:
tensor([[2182, 2003, 1996, 6251, 1045, 2215, 7861, 8270, 4667, 2015, 2005,
           1012],
          [2182, 2003, 1996, 6251, 1045, 2215, 7861, 8270, 4667, 2015, 2005,
           1012]], device='cuda:0')
through the BERT forward function

Plz close this issue. I'm not sure how on my end.

**Comment by A-kali** [comment]
Did you solve it? I have the same problem as you.
