### ISSUE TITLE
BertForSequenceClassification' object has no attribute 'bias

### ISSUE THREAD

**Issue by chikubee** [huggingface/transformers#2061]
## 🐛 Bug

Model I am using (Bert, XLNet....):

Language I am using the model on (English, Chinese....):

The problem arise when using:
* [x] the official example scripts: (give details)
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details)

I used this script to load the bert model i had finetuned for a classification task following google_research_bert.
I want to convert those TF checkpoints to pytorch.

```python
config = BertConfig.from_pretrained('bert-base-uncased')
config.num_labels=4
# You will need to load a BertForSequenceClassification model
model = BertForSequenceClassification(config)

tf_checkpoint_path = init_checkpoint
# Load weights from tf checkpoint
load_tf_weights_in_bert(model, config, tf_checkpoint_path)

pytorch_dump_path = "./pytorch_bert_output"
# Save pytorch-model
print("Save PyTorch model to {}".format(pytorch_dump_path))
torch.save(model.state_dict(), pytorch_dump_path)
```

When i execute this, i get the following error, BertForSequenceClassification' object has no attribute 'bias. Any leads would be helpful. 
Thanks

**Comment by thomwolf** [comment]
Can you show us the full error message?

**Comment by TheEdoardo93** [comment]
Can it be related to #2109 in some way?

> ##  Bug
> Model I am using (Bert, XLNet....):
> 
> Language I am using the model on (English, Chinese....):
> 
> The problem arise when using:
> 
> * [x]  the official example scripts: (give details)
> * [ ]  my own modified scripts: (give details)
> 
> The tasks I am working on is:
> 
> * [ ]  an official GLUE/SQUaD task: (give the name)
> * [x]  my own task or dataset: (give details)
> 
> I used this script to load the bert model i had finetuned for a classification task following google_research_bert.
> I want to convert those TF checkpoints to pytorch.
> 
> ```python
> config = BertConfig.from_pretrained('bert-base-uncased')
> config.num_labels=4
> # You will need to load a BertForSequenceClassification model
> model = BertForSequenceClassification(config)
> 
> tf_checkpoint_path = init_checkpoint
> # Load weights from tf checkpoint
> load_tf_weights_in_bert(model, config, tf_checkpoint_path)
> 
> pytorch_dump_path = "./pytorch_bert_output"
> # Save pytorch-model
> print("Save PyTorch model to {}".format(pytorch_dump_path))
> torch.save(model.state_dict(), pytorch_dump_path)
> ```
> 
> When i execute this, i get the following error, BertForSequenceClassification' object has no attribute 'bias. Any leads would be helpful.
> Thanks
