### ISSUE TITLE
[New Model] UDOP: Unifying Vision, Text, and Layout for Universal Document Processing

### ISSUE THREAD

**Issue by WaterKnight1998** [huggingface/transformers#20650]
### Model description

We propose Universal Document Processing (UDOP), a foundation Document AI model which unifies text, image, and layout modalities together with varied task formats, including document understanding and generation. UDOP leverages the spatial correlation between textual content and document image to model image, text, and layout modalities with one uniform representation. With a novel Vision-Text-Layout Transformer, UDOP unifies pretraining and multi-domain downstream tasks into a prompt-based sequence generation scheme. UDOP is pretrained on both large-scale unlabeled document corpora using innovative self-supervised objectives and diverse labeled data. UDOP also learns to generate document images from text and layout modalities via masked image reconstruction. To the best of our knowledge, this is the first time in the field of document AI that one model simultaneously achieves high-quality neural document editing and content customization. Our method sets the state-of-the-art on 9 Document AI tasks, e.g., document understanding and QA, across diverse data domains like finance reports, academic papers, and websites. UDOP ranks first on the leaderboard of the Document Understanding Benchmark (DUE).

### Open source status

- [x] The model implementation is available
- [x] The model weights are available

### Provide useful links for the implementation
UDOP Paper: https://arxiv.org/abs/2212.02623
UDOP Repo: https://github.com/microsoft/UDOP

UDOP Model Weights: https://huggingface.co/ZinengTang/Udop/tree/main

**Comment by WaterKnight1998** [comment]
@NielsRogge as you implemented Donut, you might be interested :)

**Comment by NielsRogge** [comment]
Let's hope they open-source :)

**Comment by WaterKnight1998** [comment]
@NielsRogge they added the code here https://github.com/microsoft/i-Code/tree/main/i-Code-Doc

**Comment by uakarsh** [comment]
Hi @NielsRogge, can I help in this implementation?

**Comment by WaterKnight1998** [comment]
@NielsRogge here you have the weights: https://huggingface.co/ZinengTang/Udop/tree/main

**Comment by munish0838** [comment]
@WaterKnight1998 Is the model accessible now?

**Comment by WaterKnight1998** [comment]
> @WaterKnight1998 Is the model accessible now?

No, the PR from @raghavanone was closed. @NielsRogge is working on opening a PR with a refactor of UDop code as it was not very good.
