### ISSUE TITLE
Add Whisper large V2 model

### ISSUE THREAD

**Issue by mrm8488** [huggingface/transformers#20653]
### Model description

It seems openAI has just released a V2 of its large Whisper model.
- The "large-v2" model is trained for more epochs with regularization and shows improved performance compared to the previous large.
- It has the same architecture as the original large model.
- When `load_model("large")` is called, the "large-v2" model will be loaded.
More, here: https://github.com/openai/whisper/commit/4179ed2475cc84cba66868b516232ef1b74dacdf

I can upload it to the hub. Cc: @younesbelkada @patrickv

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by younesbelkada** [comment]
cc @ArthurZucker

**Comment by ArthurZucker** [comment]
Hey! The `large-v2` is already converted, we are just waiting for OpenAI's approval for the release 😉

**Comment by mrm8488** [comment]
Cool!

**Comment by ArthurZucker** [comment]
FYI : https://huggingface.co/openai/whisper-large-v2

**Comment by ArthurZucker** [comment]
Not really sure if we want to change the `large` for `large-v2`, not really backward compatible
