### ISSUE TITLE
Progress Bar for large model loading

### ISSUE THREAD

**Issue by vvvm23** [huggingface/transformers#20669]
### Feature request

Add progress bars for large model loading from cache files.

### Motivation

Most of the time, model loading time will be dominated by download speed. However, for very large models we will often first download the checkpoints, then during runtime simply load them from cache. For models like Bloom however, it can take upwards of 100 minutes to load the model into RAM. During this time, there is no feedback to the user, even with verbosity set to debug. This can be frustrating as the only way to check progress is by checking system utilisation through `top`.

### Your contribution

Happy to help if I am pointed to the relevant file or files! I don't think the progress bar would need to be extremely accurate, just some indication that something is happening.

**Comment by sgugger** [comment]
Sounds like a reasonable request. This should be done by the PR linked above if you want to try it!

**Comment by vvvm23** [comment]
I might be using this wrong, but I've taken the following steps and don't see any changes 🤔 :
```
from transformers import BloomForCausalLM
import torch

model = BloomForCausalLM.from_pretrained('bigscience/bloom-7b1', cache_dir='bloom-7b1-ckpt', torch_dtype=torch.float16)
```
after cloning `transformers`, running checkout on `large_model_progress`, then `pip install -e .`

Is there some edge case with the use of `cache_dir`?

**Comment by sgugger** [comment]
The PR has not been merged into the main branch yet, so you need to checkout the branch of the PR before trying.

**Comment by vvvm23** [comment]
I had built the correct branch, the issue was me not being patient enough, as the progress bar did eventually appear.

Seems there is some processing going on between downloading and actually loading the shards. I am not sure what is being done, but the PR works ~

LGTM 🤗
