### ISSUE TITLE
beam_search 中记录 beam_indices 的问题

### ISSUE THREAD

**Issue by aj666aj** [huggingface/transformers#20665]
### System Info

some beam_indices become 0

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

if return_dict_in_generate and output_scores:
     beam_indices = tuple((beam_indices[beam_idx[i]] + (beam_idx[i],) for i in range(len(beam_indices))))

### Expected behavior

if return_dict_in_generate and output_scores:
     beam_indices = tuple((beam_indices[i] + (beam_idx[i],) for i in range(len(beam_indices))))

**Comment by sgugger** [comment]
Please follow the template of the issue. No one can help you without a description of the problem and a clear reproducer.
