### ISSUE TITLE
Save model for tensorflow serving

### ISSUE THREAD

**Issue by elixium** [huggingface/transformers#2067]
Hello,
Thanks for the library. I tried your Multi label classification. I trained it with my data. It worked very accurate and fast. Now i want to use this model with tensorflow. I am new on pytorch and i looked some tutorials. As i understand i need to save model then convert to Onnx then to tensorflow. So I tried to save model first but it gave me this error;
```
AttributeError                            Traceback (most recent call last)
<ipython-input-10-4f1e1257e6e8> in <module>()
      1 
----> 2 torch.save(model.state_dict(), 'output/multilabel.pth')

AttributeError: 'MultiLabelClassificationModel' object has no attribute 'state_dict'
```

How can i save the model and export to onnx?

**Comment by akshayklr057** [comment]
Did you get the solution to this? @elixium

**Comment by kevin-yauris** [comment]
Hi any update on this? I would like to deploy huggingface Transformers model with Tensorflow Serving too
