### ISSUE TITLE
A bug with subscript while maintaining beam_indices.

### ISSUE THREAD

**Issue by aj666aj** [huggingface/transformers#20694]
#### The problem caused by this bug:
I want to get all decoder_hidden_states (with dimension [max_seq_len * (1 + decoder_layers) * (num_beam * batch_size) * embedding_size]) and beam_indices to keep track of those hidden states of each word generated.
After some example early stop (\<eos\> is generated), some beam_indices will become zero incorrectly. This bug is caused by the wrong subscript (`beam_indices[beam_idx[i]]`) when the model update the beam_indices and it should be `beam_indices[i]`.

**Comment by sgugger** [comment]
cc @gante, but note that there is little we can do to help without a reproducer of the bug.

**Comment by gante** [comment]
Hey @aj666aj 👋 

Can I have a script to reproduce your problem? I'll struggle to pinpoint the issue without it, which will make me deprioritize this issue :)
