### ISSUE TITLE
[Quick poll] Give your opinion on the future of the Hugging Face Open Source ecosystem!

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/transformers#20706]
Thanks to all of you, Transformers just passed 75k :star2:  last week!

Since the last survey, a lot has happened: the [diffusers](https://github.com/huggingface/diffusers), [evaluate](https://github.com/huggingface/evaluate) and [skops](https://github.com/skops-dev/skops) libraries were born. `timm` joined the Hugging Face ecosystem. There were 25 new releases of `transformers`, 21 new releases of `datasets`, 13 new releases of `accelerate`.

If you have a couple of minutes and want to participate in shaping the future of the ecosystem, please share your thoughts: 

[**hf.co/oss-survey**](https://docs.google.com/forms/d/e/1FAIpQLSf4xFQKtpjr6I_l7OfNofqiR8s-WG6tcNbkchDJJf5gYD72zQ/viewform?usp=sf_link)

(please reply in the above feedback form rather than to this thread)

Thank you all on behalf of the HuggingFace team! 🤗

**Comment by guotong1988** [comment]
multi-gpu pre-training in one machine for Large GPT from scratch without horovod (**Model Parallelism**)

**Comment by LysandreJik** [comment]
Closing as this survey has wrapped up
