### ISSUE TITLE
[docs] transformers/quicktour rendering issue

### ISSUE THREAD

**Issue by scott-vsi** [huggingface/transformers#20700]
There is a rendering issue in https://huggingface.co/docs/transformers/quicktour#trainer-a-pytorch-optimized-training-loop
step 5.

The markdown looks like [this](https://github.com/huggingface/transformers/blob/9e56aff58a742b48fc8edea8d28d5b80330efbcc/docs/source/en/quicktour.mdx?plain=1#L445-L451)

```python
>>> def tokenize_dataset(dataset):
...     return tokenizer(dataset["text"])


>>> dataset = dataset.map(tokenize_dataset, batched=True)
```

but `dataset = ...` renders as a separate triple-indented quote

**Comment by osanseviero** [comment]
Transfering to the transformers repo as it's more relevant there cc @sgugger

**Comment by sgugger** [comment]
Should be fixed by the PR mentioned above.

**Comment by scott-vsi** [comment]
Probably not worth looking at more, but just by way of comparison, there is multiple returns on this page that seem to work (again referencing `dataset.map`):

https://huggingface.co/docs/transformers/training#prepare-a-dataset
https://github.com/huggingface/transformers/blob/74330083b5eea68eadf25bcbad3bcbb094f60c57/docs/source/en/training.mdx?plain=1#L50-L54

I have no idea if it matters, but when viewed as markdown, there are some sections of the quickstart that don't render right. E.g., see the

```
```py >>> pt_batch = tokenizer( ... ["We are very happy to show you the...
```

in this [section](https://github.com/huggingface/transformers/blob/9e56aff58a742b48fc8edea8d28d5b80330efbcc/docs/source/en/quicktour.mdx#autotokenizer)

**Comment by stevhliu** [comment]
Thanks for raising this issue! 

It isn't as important when viewed as Markdown because we use a special syntax (`<frameworkcontent>`) to generate the PyTorch and TensorFlow code blocks in our docs.
