### ISSUE TITLE
The generation script could fail when there's a double space in the prompt

### ISSUE THREAD

**Issue by cloudygoose** [huggingface/transformers#2071]
## 🚀 Feature

Hey, thanks for everything,
The generation script could fail when there's a double space in the prompt, e.g. " I  go to"
![image](https://user-images.githubusercontent.com/1544039/70262743-e4bc4900-1762-11ea-9041-9bee082a0054.png)

I know it's not important, but it would be good if the tokenize is more "robust"

**Comment by LysandreJik** [comment]
Hi! Could you specify the command you used to launch `run_generation` as well as the versions in your environment? Pyton, pytorch, transformers? Thanks.

**Comment by cloudygoose** [comment]
`python scripts_htx/run_generation.py  --model_type ctrl --model_name ctrl  --repetition 1.2`
python=3.7.3
torch=1.3.0
transformers=2.2.1

But I guess this issue is not related to the versions....

**Comment by thomwolf** [comment]
This is actually the same as #1920 
Now fixed on master (will be in the next release).
