### ISSUE TITLE
Question-answering example datasets

### ISSUE THREAD

**Issue by Arij-Aladel** [huggingface/transformers#20721]
In the [examples
](https://github.com/huggingface/transformers/tree/0bae286de94f7131b4a2db3f85754b0961c4aaf5/examples/pytorch/question-answering)
Could you please add possible datasets for each script? Neither in the scripts or in the read me I can find this information. especially for long inputs, as I saw from the scripts that you used a tokenizer for that. Also, it would be great if you could provide us please, with the possible models for each script if possible.

**Comment by sgugger** [comment]
The examples are given as just that: examples. You will always need to slightly adapt them when changing the dataset as the data format might not be exactly the same. So there is no official list of possible datasets apart from the ones showcased in the README.
