### ISSUE TITLE
Verify that a test in `LayoutLMv3` 's tokenizer is checking what we want

### ISSUE THREAD

**Issue by SaulLu** [huggingface/transformers#20733]
I'm taking the liberty of opening an issue to share a question I've been keeping in the corner of my head, but now that I'll have less time to devote to `transformers` I prefer to share it before it's forgotten.

In the PR where the `LayoutLMv3` model was added, I was not very sure about the target value used for one of the tests that had to be overridden (the value was 1 in one of the previous commits and then changed to 0). The comment I am referring to is this one: https://github.com/huggingface/transformers/pull/17060#discussion_r872265358 .  

Might be of interest to @ArthurZucker

**Comment by ArthurZucker** [comment]
Thanks! Will try to get familiar with this 😉
