### ISSUE TITLE
T5ForConditionalGeneration with BetterTransformer

### ISSUE THREAD

**Issue by R4ZZ3** [huggingface/transformers#20741]
### Feature request

Got this error when trying out BetterTransformer:
"The Better Transformers implementation for the model T5ForConditionalGeneration has not been implemented yet. Please open an issue requesting the addition of this model with its `BetterTransformer`implementation."

### Motivation

I would like to speed up some text2text models with BetterTransformer

### Your contribution

I can at least test the feature once it is ready

**Comment by sgugger** [comment]
I think it needs to be implemented in optimum, so you should move the issue there. cc @younesbelkada

**Comment by R4ZZ3** [comment]
Moving to optimum
