### ISSUE TITLE
min_new_tokens option in generate() implementation

### ISSUE THREAD

**Issue by gonced8** [huggingface/transformers#20756]
### Feature request

Similarly to the `max_new_tokens`, a `min_new_tokens` option would count only the newly generated tokens, ignoring the tokens of the input sequence (prompt) in decoder only models.

### Motivation

The option `min_length` of the `generate()` method might be ambiguous for decoder only models. It is not clear if decoder only models consider the length of the input (prompt) for the `min_length` condition or only the newly generated tokens.
In Encoder Decoder (seq2seq) it is clear though.

### Your contribution

Not that I remember. But I could test it.

**Comment by sgugger** [comment]
cc @gante

**Comment by gante** [comment]
Hi @gonced8 👋  Thank you for raising this issue!

This is the same as [this issue ](https://github.com/huggingface/transformers/issues/20614)(which is slightly older). I'm closing this issue to avoid duplication of comments/efforts, and [this particular comment](https://github.com/huggingface/transformers/issues/20614#issuecomment-1361225567) might be of your interest :)
