### ISSUE TITLE
Run 'GPT-J' failure due to download dataset fail  (' ConnectionError: Couldn't reach http://eaidata.bmk.sh/data/enron_emails.jsonl.zst ' )

### ISSUE THREAD

**Issue by shaoyuta** [huggingface/transformers#20759]
### System Info

Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.11.1
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
- Python version: 3.9.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/taosy/.huggingface/token
- Has saved token ?: False
- Configured git credential helpers:
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: N/A
- Graphviz: N/A
- Pydot: N/A

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps to reproduce this issue:
1. git clone https://github.com/huggingface/transformers
2. cd transformers
3. python examples/pytorch/language-modeling/run_clm.py --model_name_or_path EleutherAI/gpt-j-6B --dataset_name the_pile --dataset_config_name enron_emails  --do_eval --output_dir /tmp/output --overwrite_output_dir

### Expected behavior

1. This issue looks like due to "http://eaidata.bmk.sh/data/enron_emails.jsonl.zst " couldn't be reached.
2. Is there another way to download the dataset "the_pile" ? 
3. Is there another way to cache the dataset "the_pile" but not let the hg to download it when runtime ?

**Comment by sgugger** [comment]
This is an issue with the dataset, so you should probably open this in the Datasets repo :-)

**Comment by shaoyuta** [comment]
> This is an issue with the dataset, so you should probably open this in the Datasets repo :-)

Thanks for your help
