### ISSUE TITLE
OPT model sizes mismatch between code and webpage

### ISSUE THREAD

**Issue by chenho74** [huggingface/transformers#20772]
### System Info

N/A

### Who can help?

 @ArthurZucker, @sgugger and @stevhliu

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I was trying to figure out the architecture of OPT models, specifically the pre-layernorm vs post-layernorm setting. I came across these two lines that specified the setting for OPT of different model sizes. 
https://github.com/huggingface/transformers/blob/67acb07e9ef40e6ea08997261e1d14a02530cf8b/src/transformers/models/opt/modeling_opt.py#L322
https://github.com/huggingface/transformers/blob/67acb07e9ef40e6ea08997261e1d14a02530cf8b/src/transformers/models/opt/modeling_opt.py#L346

However it doesn't match with the model sizes available here (if you expand the model list and search `opt-`). I didn't see 1.7B and 175B. 
https://huggingface.co/facebook?sort_models=alphabetical#models

Which one is more accurate? 

### Expected behavior

N/A

**Comment by ArthurZucker** [comment]
Hey! Basically the `1.7B` is now the `1.3b` and the `175B` is private and was not released by the META AI team. 
If you want you can open a PR to just correct the model size 😉

**Comment by chenho74** [comment]
Thanks for the clarification!
