### ISSUE TITLE
How to reset dataloader or global_step for continued training?

### ISSUE THREAD

**Issue by ajesujoba** [huggingface/transformers#20779]
I have finetuned MT5-base model for machine translation task on a corpus `A` and I would want to swap the dataset and continue training on corpus `B` (this is not finetuning but a form of continued training), and force the dataloader to start afresh instead of continuing from the point where it stopped previously on corpus `A`. Currently, to do continue training, I used `resume_from_checkpoint` to provide the checkpoint of the MT model for corpus `A` and provide the path to the new data.
Is there an argument or parameter to reset data loader? I noticed there is a  `ignore_data_skip` parameter but this does not solve the issue.

**Comment by ajesujoba** [comment]
if the continued training stops on `B` due to GPU limit, how do I ensure that when I try to continue training on `B`, it has the right data index to start from?

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for questions like this, as we keep issues for bugs and feature requests only.
