### ISSUE TITLE
ImportError while trying to get the OS and software versions

### ISSUE THREAD

**Issue by vaibhav-k** [huggingface/transformers#20789]
### System Info

OS: Ubuntu 22.04; Python version: Python 3.10.6

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Simply run the command `python3 src/transformers/commands/transformers_cli.py env`.

### Expected behavior

I wanted to get the OS and software versions but instead got the error
```
Traceback (most recent call last):
  File "/home/skywalker/Downloads/transformers/transformers/src/transformers/commands/transformers_cli.py", line 18, in <module>
    from .add_new_model import AddNewModelCommand
ImportError: attempted relative import with no known parent package
```

**Comment by sgugger** [comment]
The CLI is not supported this way, you should run `transformers-cli env`.
