### ISSUE TITLE
Add Object Detection task tutorial to the transformers documentation

### ISSUE THREAD

**Issue by MKhalusova** [huggingface/transformers#20805]
Currently, the transformers documentation has two how-to guides for CV tasks - image classification and semantic segmentation. Transformers support other CV tasks, such as object detection. This issue describes a proposal to add a how-to guide for object detection similar in structure to the existing guides to help the community members get started with object detection on their own data using the transformers library. 

Here’s an approximate outline for the page: 

1. Intro: what object detection is, including the video from https://huggingface.co/tasks/object-detection
2. Fine-tuning either DETR or YOLOS on a new dataset (TODO: decide which one to pick).
 2.1. Loading a dataset 
 2.2. Preprocessing the dataset 
 2.3. Setting up an evaluation metric
 2.4. Training and pushing a model to the hub
3. Using the fine-tuned model for inference.

Some existing notebooks for reference: 
    - [Fine-tuning YOLOS on a custom dataset for object detection](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/YOLOS/Fine_tuning_YOLOS_for_object_detection_on_custom_dataset_(balloon).ipynb)
    - [Fine-tuning DETR on a custom dataset for object detection](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/DETR/Fine_tuning_DetrForObjectDetection_on_custom_dataset_(balloon).ipynb)

Related [WIP] PR: https://github.com/huggingface/transformers/pull/20874

**Comment by stevhliu** [comment]
This looks great to me, looking forward to seeing the guide and let me know if there is anything I can help with! 🙂 

I would recommend using DETR since it is a lot more popular than YOLOS (263k downloads versus 28.4k).

**Comment by MKhalusova** [comment]
@stevhliu That's a good reason to go with DETR, thanks for the tip!

**Comment by MKhalusova** [comment]
The issue is fixed with https://github.com/huggingface/transformers/pull/20925
