### ISSUE TITLE
ImportError: cannot import name 'WarmupLinearSchedule'

### ISSUE THREAD

**Issue by Dhanachandra** [huggingface/transformers#2082]
$ pip show transformers
Name: transformers
Version: 2.2.1
Summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
Home-page: https://github.com/huggingface/transformers
Author: Thomas Wolf, Lysandre Debut, Victor Sanh, Julien Chaumond, Google AI Language Team Authors, Open AI team Authors, Facebook AI Authors, Carnegie Mellon University Authors
Author-email: thomas@huggingface.co
License: Apache
Location: /home/ubuntu/anaconda3/lib/python3.6/site-packages
Requires: numpy, requests, regex, sacremoses, tqdm, sentencepiece, boto3
Required-by:

**Comment by TheEdoardo93** [comment]
It is in the [optimization.py](https://github.com/huggingface/transformers/blob/df99f8c5a1c54d64fb013b43107011390c3be0d5/transformers/optimization.py), at line 45. It creates a schedule with a learning rate that decreases linearly after linearly increasing during a warmup period. In order to import it, you have to do the following:
```
> from transformers import get_linear_schedule_with_warmup
> ...
```

I've tested this statement with **Python 3.6.9**, **Transformers 2.2.1** (installed with `pip install transformers`), **PyTorch 1.3.1** and **TensorFlow 2.0**.

> $ pip show transformers
> Name: transformers
> Version: 2.2.1
> Summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
> Home-page: https://github.com/huggingface/transformers
> Author: Thomas Wolf, Lysandre Debut, Victor Sanh, Julien Chaumond, Google AI Language Team Authors, Open AI team Authors, Facebook AI Authors, Carnegie Mellon University Authors
> Author-email: [thomas@huggingface.co](mailto:thomas@huggingface.co)
> License: Apache
> Location: /home/ubuntu/anaconda3/lib/python3.6/site-packages
> Requires: numpy, requests, regex, sacremoses, tqdm, sentencepiece, boto3
> Required-by:

**Comment by fendouai** [comment]
I have the same error

**Comment by TheEdoardo93** [comment]
Do you see my comment above? Did you try out?

> I have the same error

**Comment by fendouai** [comment]
> Do you see my comment above? Did you try out?
> 
> > I have the same error

I try to install from the git, fix the problem

**Comment by lauramanor** [comment]
I tried both pip and git, still having the issue

**Comment by micah5** [comment]
Still having this issue on 2.3.0 too

**Comment by honglanfcb** [comment]
Use get_linear_schedule_with_warmup() instead of WarmupLinearSchedule. I think they have the same function.

**Comment by micah5** [comment]
> Use get_linear_schedule_with_warmup() instead of WarmupLinearSchedule. I think they have the same function.

The API is not quite the same, but it's similar enough that it should be easy enough to convert.

For example:

```python
scheduler = WarmupLinearSchedule(optimizer, warmup_steps=WARMUP_STEPS, t_total = -1)
```

becomes...

```python
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=WARMUP_STEPS, num_training_steps=-1)
```

For future visitors, see [docs](https://huggingface.co/transformers/main_classes/optimizer_schedules.html?highlight=get_linear_schedule_with_warmup#transformers.get_linear_schedule_with_warmup)
