### ISSUE TITLE
TypeError: TextInputSequence must be str

### ISSUE THREAD

**Issue by suppathak** [huggingface/transformers#20838]
### System Info

- `transformers` version: 4.23.1
- Platform: Linux-4.18.0-305.62.1.el8_4.x86_64-x86_64-with-glibc2.2.5
- Python version: 3.8.8
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: YEs
- Using distributed or parallel set-up in script?: 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

Steps to Reproduce:

1. Trying the re-run this notebook: https://github.com/suppathak/aicoe-osc-demo/blob/teach-stu/notebooks/demo2/teacher_student_exp.ipynb (Reference: https://github.com/neuralmagic/sparseml/blob/main/integrations/huggingface-transformers/tutorials/sparsifying_bert_using_recipes.md)

### Expected behavior

It should run without any error. The notebook was running perfectly until last Friday(3 days ago). When I try to re-run it again. It is failing and giving me this error. Has there been any kind of update in the system? 

Any helpful feedback is appreciated. Thanks! 

![Screenshot from 2022-12-19 05-27-58](https://user-images.githubusercontent.com/30439457/208504300-62a1aa36-23d5-4a5a-bd0c-150cd97acd93.png)

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to help debug your code or provide us with a short reproducer we can run. The notebook relies on credentials we do not have.

**Comment by suppathak** [comment]
Closing the Issue. Resolved the error by replacing the dataset. There was some manually added extra values in the old dataset.
