### ISSUE TITLE
transformers.onnx mobilenet_v2 not supported but exists in supported list

### ISSUE THREAD

**Issue by ashim-mahara** [huggingface/transformers#20856]
### System Info

- `transformers` version: 4.25.1
- Platform: Linux-6.0.6-76060006-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.13.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes (using notebooks for training)
- Using distributed or parallel set-up in script?: no

`KeyError: "mobilenet-v2 is not supported yet. Only ['albert', 'bart', 'beit', 'bert', 'big-bird', 'bigbird-pegasus', 'blenderbot', 'blenderbot-small', 'bloom', 'camembert', 'clip', 'codegen', 'convbert', 'convnext', 'data2vec-text', 'data2vec-vision', 'deberta', 'deberta-v2', 'deit', 'detr', 'distilbert', 'electra', 'flaubert', 'gpt2', 'gptj', 'gpt-neo', 'groupvit', 'ibert', 'imagegpt', 'layoutlm', 'layoutlmv3', 'levit', 'longt5', 'longformer', 'marian', 'mbart', 'mobilebert', 'mobilenet_v1', 'mobilenet_v2', 'mobilevit', 'mt5', 'm2m-100', 'owlvit', 'perceiver', 'resnet', 'roberta', 'roformer', 'segformer', 'squeezebert', 'swin', 't5', 'vision-encoder-decoder', 'vit', 'whisper', 'xlm', 'xlm-roberta', 'yolos'] are supported. If you want to support mobilenet-v2 please propose a PR or open up an issue."`

### Who can help?

@amyeroberts @NielsRogge 

### Information

- [X] My own modified scripts

### Tasks

- [x] My own task or dataset (give details below)

### Reproduction

```
from transformers import  AutoModelForImageClassification
from transformers.onnx import FeaturesManager

model = AutoModelForImageClassification.from_pretrained("google/mobilenet_v2_1.0_224")
model_kind, model_onnx_config = FeaturesManager.check_supported_model_or_raise(model)
```

### Expected behavior

Should be able to get model_onnx_config for export.

**Comment by sgugger** [comment]
It's just a typo in the list it looks like. cc @younesbelkada or @ArthurZucker if you want to make a quick fix.

**Comment by younesbelkada** [comment]
on it!

**Comment by younesbelkada** [comment]
Hi @ashim-mahara 
You should be now be able to export mobilenet in ONNX using the main branch of optimum and transformers

**Comment by ashim-mahara** [comment]
Hi @younesbelkada thank you! that was fast, kudos to you folks!
