### ISSUE TITLE
Add OPT-IML Checkpoints

### ISSUE THREAD

**Issue by chujiezheng** [huggingface/transformers#20882]
### Model description

OPT-IML models are instruction-finetuned from the OPT checkpoints. Here is the [technical report](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT-IML/optimal_paper_v1.pdf).

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

* **Technical report:** https://github.com/facebookresearch/metaseq/blob/main/projects/OPT-IML/optimal_paper_v1.pdf
* **Model implementation:** same as OPT
* **Model weights:** https://github.com/facebookresearch/metaseq/tree/main/projects/OPT-IML
* **Authors:** Meta AI

**Comment by g-simmons** [comment]
🙏

**Comment by jmhessel** [comment]
I tried to convert and also ran into this issue:

https://github.com/facebookresearch/metaseq/issues/567
https://github.com/facebookresearch/metaseq/issues/594

But it seems like meta folks is working to upload it to huggingface:

https://github.com/facebookresearch/metaseq/issues/567#issuecomment-1370415582

**Comment by sgugger** [comment]
I believe it was @ArthurZucker

**Comment by ArthurZucker** [comment]
Thanks for bumping on this!

**Comment by muhark** [comment]
Also working on this, have run into the same issues mentioned above. Let me know if I can be an extra pair of eyes/hands for working on this.

**Comment by ArthurZucker** [comment]
Weights are available here thanks to (https://huggingface.co/rpasunuru) : 
- https://huggingface.co/facebook/opt-iml-30b
- https://huggingface.co/facebook/opt-iml-1.3b
Closing!
