### ISSUE TITLE
__init__() missing 1 required positional argument

### ISSUE THREAD

**Issue by Changgeng-Wei** [huggingface/transformers#20881]
### System Info

- `transformers` version: 4.9.2
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.7.11
- PyTorch version (GPU?): 1.9.0+cpu (False)
- Tensorflow version (GPU?): 2.6.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?:No

### Who can help?

@you

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

from transformers.modeling_utils import PretrainedConfig

class TClass(PretrainedConfig):
    def __init__(self, config):
        super(TClass, self).__init__()
        self.config = config

if __name__ == '__main__':
    c = TClass(config='setting')
    print(c)

### Expected behavior

Hi!
I'am a green hands, I wanted to define a class which is based on PretrainedConfig and sent a variate when initiate the object, but I faced a issue discribed by beflowing text. I change many transformers versions and python versions, but the issue is still happened, could you help me to solve it? Thanks a lot!
 File "F:/workProject//test/test.py", line 12, in <module>
    print(c)
  File "E:\ProgramData\Anaconda3\envs\py37_tf250_torch\lib\site-packages\transformers\configuration_utils.py", line 613, in __repr__
    return f"{self.__class__.__name__} {self.to_json_string()}"
  File "E:\ProgramData\Anaconda3\envs\py37_tf250_torch\lib\site-packages\transformers\configuration_utils.py", line 674, in to_json_string
    config_dict = self.to_diff_dict()
  File "E:\ProgramData\Anaconda3\envs\py37_tf250_torch\lib\site-packages\transformers\configuration_utils.py", line 629, in to_diff_dict
    class_config_dict = self.__class__().to_dict() if not self.is_composition else {}
TypeError: __init__() missing 1 required positional argument: 'config'"

**Comment by sgugger** [comment]
Hi there! There is no way we will be able to help you without seeing the code you are running.

**Comment by Changgeng-Wei** [comment]
> The code is below

from transformers.modeling_utils import PretrainedConfig

class TClass(PretrainedConfig):
def init(self, config):
super(TClass, self).init()
self.config = config

if name == 'main':
c = TClass(config='setting')
print(c)
