### ISSUE TITLE
Can't access ViTImageProcessor on transformers==4.25.1

### ISSUE THREAD

**Issue by navinelahi** [huggingface/transformers#20895]
### System Info

ImportError: cannot import name 'ViTImageProcessor' from 'transformers' (/opt/conda/lib/python3.7/site-packages/transformers/__init__.py)

Am I using the wrong version? Should I downgrade? Where can I get the release history in general? I often find discrepancies like this for usage documentation in the website and it's often related to versioning.

### Who can help?

@sgugger @stevhliu 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

!pip install transformers==4.25.1
from transformers import ViTImageProcessor, BertTokenizer, VisionEncoderDecoderModel

### Expected behavior

It should work.

**Comment by NielsRogge** [comment]
Hi,

Release history is here: https://github.com/huggingface/transformers/releases.

I just tried it out on Google Colab, it works fine for me.

**Comment by zwlyn** [comment]
Hello, just do: **pip install transformers --upgrade**
then problem fixed

**Comment by JamesCHub** [comment]
Note that if you are running backlevel Python (e.g. 3.6) `pip install transformers --upgrade` will only get you as far as transformers 4.18
