### ISSUE TITLE
Informer - Transformer For Time-Series Forecasting 

### ISSUE THREAD

**Issue by elisim** [huggingface/transformers#20903]
# Model description

Following the new support for Time Series Transformers in the [API](https://huggingface.co/docs/transformers/model_doc/time_series_transformer) (and the great blog by @NielsRogge and @kashif [here](https://huggingface.co/blog/time-series-transformers)), I propose adding "Informer" - AAAI 2021 Best Paper model. 

* Paper: [Informer: Beyond Efficient Transformer for Long Sequence Time-Series Forecasting
](https://arxiv.org/abs/2012.07436)
* Model implementation: https://github.com/zhouhaoyi/Informer2020

## Why this model?

Compared to other forcasting transformers (see below), Informer seems to be the most "code-stable" one, with the most starts & forks in github.

Popular forcasting Transformes, with link to the repository:

[LogTrans](https://github.com/mlpotter/Transformer_Time_Series) - NIPS 2019 
[Informer](https://github.com/zhouhaoyi/Informer2020) - AAAI 2021 (Best Paper)
[Autoformer](https://github.com/thuml/Autoformer) - NIPS 2021 
[Pyraformer](https://github.com/alipay/Pyraformer) - ICLR 2022
[FEDformer](https://github.com/MAZiqing/FEDformer) - ICML 2022

This list based on the paper: [Are Transformers Effective for Time Series Forecasting?](https://arxiv.org/abs/2205.13504) (AAAI-23)

I would like to implement the model :)

Thank you,
Eli

### Open source status

- [X] The model implementation is available
- [ ] The model weights are available

### Provide useful links for the implementation

@zhouhaoyi - repository creator

**Comment by kashif** [comment]
thanks @elisim for the issue... indeed i have informer in my list of models to port over. I have the initial implementation of informer and other done: https://github.com/kashif/pytorch-transformer-ts and will move them over to the transformers API

**Comment by elisim** [comment]
Wow! saw your repo and it looks great! Maybe I might help? :) I sent you a email. 

Thanks, 
Eli

**Comment by elisim** [comment]
merged in https://github.com/huggingface/transformers/pull/21099
