### ISSUE TITLE
OSError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.

### ISSUE THREAD

**Issue by ucas010** [huggingface/transformers#20908]
### System Info

copy the [RP](https://github.com/huggingface/notebooks/blob/main/examples/language_modeling.ipynb) and got the ERROR
could you pls help me ?

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

same as official script

### Expected behavior

overcome the error

**Comment by sgugger** [comment]
You need to make sure to execute the cell `notebook_login()` at the beginning and pass it your token (it provides a direct link to your token pages on hf.co)

**Comment by ucas010** [comment]
pass it your token ??? I have token but how to use it ? @sgugger
