### ISSUE TITLE
Error msg when running on the colab

### ISSUE THREAD

**Issue by liguangzhe** [huggingface/transformers#2091]
## ❓ Questions & Help

![捕获](https://user-images.githubusercontent.com/43159433/70368968-05c68c00-1880-11ea-8d97-5189348a4eca.PNG)
 
Can anyone tell me where am I wrong or it's not my problem?I cloned whole the files from huggingface. Is it can be fixed? I would appreciate for any suggestion. Thank you.

**Comment by LysandreJik** [comment]
Hi! How did you obtain the train-v2.0 and dev-v2.0 files? Did you put the `--version_2_with_negative` flag to specify you're using SQuAD V2?
