### ISSUE TITLE
ModuleNotFoundError: No module named 'evaluate'

### ISSUE THREAD

**Issue by ucas010** [huggingface/transformers#20919]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.25.1
- Platform: Linux-3.10.0-1160.81.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.15
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker and @younesbelkada@sgugger

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling
```
python run_mlm.py \
    --model_name_or_path roberta-base \
    --train_file path_to_train_file \
    --validation_file path_to_validation_file \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --output_dir /tmp/test-mlm
line 35, in <module>
    import evaluate
ModuleNotFoundError: No module named 'evaluate'
myhugBert.sh:行4: --train_file: 未找到命令
myhugBert.sh:行11: --output_dir: 未找到命令
```

### Expected behavior

overcome the bug

**Comment by sgugger** [comment]
You need to `pip install evaluate`, as the error message tells you. This is also in the [requirements](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/requirements.txt) for this example.

**Comment by svspavankumar** [comment]
First run the pip install-r requirements.txt command then still if you won't find out the modile pip install evaluate @ucas010

**Comment by NielsRogge** [comment]
Closing this issue as it seems resolved. Feel free to reopen if needed.

**Comment by Jing-Fu** [comment]
I have this problem too, can anyone help?
towhee Version: 1.1.3
