### ISSUE TITLE
Request for scripts/helper function to create custom jsonl files for translation 

### ISSUE THREAD

**Issue by SupreethRao99** [huggingface/transformers#20910]
### Feature request

In the examples for machine translation there's a section that states that current scripts can only consume data in a custom jsonl format as follows
```json
{ "translation": { "en": "Others have dismissed him as a joke.", "ro": "Alții l-au numit o glumă." } }
{ "translation": { "en": "And some are holding out for an implosion.", "ro": "Iar alții așteaptă implozia." } }
```
It would be great if there are helper scripts that could convert pandas data frames into this particular format 

### Motivation

Its frustrating data has to be converted into the particular format for it to be consumed by the training scripts, it would be nice if the scripts consumed CSV's with one column being language1 and the other column being language2. 

### Your contribution

I could help testing and validating the code

**Comment by sgugger** [comment]
Examples are just that examples. You should adapt the data processing part to your specific data format.
