### ISSUE TITLE
Problem with MBartForConditionalGeneration and MBart50TokenizerFast

### ISSUE THREAD

**Issue by sunny3** [huggingface/transformers#20931]
### System Info

sys info:

- `transformers` version: 4.25.1
- Platform: Linux-5.4.17-2136.308.9.el8uek.x86_64-x86_64-with-glibc2.28
- Python version: 3.9.7
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.1+cu117 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
```python
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")
tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")
sentence_kz = "сәлем досым"
tokenizer.src_lang = "kk_KZ"
encoded_kk = tokenizer(sentence_kz , return_tensors="pt")
generated_tokens = model.generate(
    **encoded_kk,
    forced_bos_token_id=tokenizer.lang_code_to_id["ru_RU"]
)
tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
```
### Expected behavior

I use the official example of code from https://huggingface.co/facebook/mbart-large-50-many-to-many-mmt

I just changed the abbreviations for the languages (hi_IN -> kk_KZ, fr_XX -> ru_RU), wanting to get the Russian language out, but I get english instead of russian
![image](https://user-images.githubusercontent.com/25152817/209909173-4273c2b6-d167-4de3-b33b-4c778c305c4c.png)

**Comment by sgugger** [comment]
cc @ArthurZucker

**Comment by Hannibal046** [comment]
Maybe due to this ?  https://github.com/huggingface/transformers/issues/20610#issuecomment-1407704129

**Comment by ArthurZucker** [comment]
The model should be predicting in Russian, and the only reason it is not is probably because `kk` language has a very small dataset size and was thus not trained a lot. The model and the generation process work as they function as expected for lanugages that have a bigger dataset. 

For example if you use `ja_XX` you will get `['世界の友達']` which means friend of the world (Sekai no tomodachi). 
It comes down to the fine-tuning and which pair was trained with which other.
