### ISSUE TITLE
`tf2` BERT checkpoint to `pytorch_model.bin` (with MLM head)

### ISSUE THREAD

**Issue by Iulian277** [huggingface/transformers#20947]
### System Info

- `transformers` version: 4.25.1
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.9.5
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.0+cpu (False)
- Tensorflow version (GPU?): 2.10.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False

### Who can help?

@ArthurZucker @younesbelkada @gante 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying to convert a `tf2` BERT checkpoint to the `pytorch_model.bin` format in order to upload it on the Huggingface hub. I know that there are 2 scripts for doing this type of conversion (one for [tf1](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/convert_bert_original_tf_checkpoint_to_pytorch.py) checkpoints and one for [tf2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/convert_bert_original_tf2_checkpoint_to_pytorch.py) checkpoints).

The problem is that my BERT checkpoint is in `tf2` format and I want to convert it to a pytorch model (encoder + heads).

I mention that I've followed this [guide](https://github.com/tensorflow/models/blob/master/official/nlp/docs/train.md#pre-train-a-bert-from-scratch) and used the [official ](https://github.com/tensorflow/models/tree/master/official/nlp) tensorflow scripts for obtaining the checkpoints.

### Expected behavior

I would like to export a `tf2` BERT checkpoint to a `pytorch` model, exporting the MLM head alongside the encoder.

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for such questions as we keep issues for bugs and feature requests only.

Note that we do not provide conversion scripts to convert checkpoints obtained with other libraries, the ones exposed are to convert the checkpoints from their original implementation to the Hugging Face format. If you train a Hugging Face Tensorflow model, you'll then seamlessly be able to convert it to PyTorch/Flax.
