### ISSUE TITLE
Mask dimension expansion might be wrong

### ISSUE THREAD

**Issue by pphuangyi** [huggingface/transformers#20950]
https://github.com/huggingface/transformers/blob/17292440c069118fbdb992b9a17da2098fab5b87/src/transformers/models/reformer/modeling_reformer.py#L845

I feel that the way mask is expanded here might be wrong. More specifically, I feel that mask need to be repeated by the number hashes and splited into chunks before running gather. 

Please look into it and let me know if I misunderstood. Thank you so much!

**Comment by sgugger** [comment]
cc @ArthurZucker
