### ISSUE TITLE
Add whisper converter for hf -> openai

### ISSUE THREAD

**Issue by faroit** [huggingface/transformers#20953]
### Feature request

The inference pipeline in openai whisper has a couple of heuristics that aren't all covered in https://github.com/huggingface/transformers. Therefore, some users would like to fine-tune in huggingface and convert the model back to its original configuration.

https://github.com/huggingface/transformers/blob/main/src/transformers/models/whisper/convert_openai_to_hf.py provides a script to convert from openai to hf, so we should also have a script to go the other way.

### Motivation

It is difficult to get the same transcription quality in the current transformers library compared to the openai transcribe function https://github.com/openai/whisper/blob/main/whisper/transcribe.py.

### Your contribution

there is an existing approach in https://github.com/luigisaetta/whisper-app/blob/main/match_layers.py by @luigisaetta

**Comment by faroit** [comment]
👋 @ArthurZucker, who created the conversion script

**Comment by ArthurZucker** [comment]
Hey! I am not entirely sure if we should have this in our repo or just link it in the readme, but I think a contributor already wrote a script so pinging @bayartsogt-ya here.

**Comment by jordimas** [comment]
For visibility, whisper.cpp provides conversion from HF models into their format.
It's much high performing that OpenAI implementation. See: https://github.com/ggerganov/whisper.cpp/tree/master/models

**Comment by faroit** [comment]
I've seen a lot of converter codes flying around. Also given that tranformers is catching up with respect to timestamp outputs there is not much need to use whisper itself for inference anymore

**Comment by AljoSt** [comment]
@faroit could you add a link to a conversion script? Just so if people end up here, they find what they are looking for.
