### ISSUE TITLE
There should partial forward in pretrained BERT and RoBERTa models

### ISSUE THREAD

**Issue by shashwat1002** [huggingface/transformers#20960]
### Feature request

There should be a way to to send inputs to specific encoder layers and finish the forward partially. 

For example, there should be a way to send input hidden states to the fourth encoder layer, and get all hidden states after that through forward computation.

### Motivation

This kind of thing is required in causal intervention.

### Your contribution

I can submit a PR to this effect.

**Comment by sgugger** [comment]
Each of those models is defined in its own modeling file that you can modify to suit your needs. This is why we have a one file per model policy in Transformers :-)
