### ISSUE TITLE
The added tokens do not work as expected

### ISSUE THREAD

**Issue by wenhuchen** [huggingface/transformers#2096]
Here is a minimum example, where we add a special token [ENT]
```
from transformers import BertTokenizer
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-uncased-vocab.txt')

bert_tokenizer.add_tokens(['[ENT]'])
print(len(tokenizer))

x = bert_tokenizer.encode("you are the [ENT] with [ENT] and [ENT]")
print(x)
bert_tokenizer.decode(x)
```
After decoding, we will end up having
```
you are the [ENT]with [ENT]with [ENT]
```
rather than
```
'you are the [ENT] with [ENT] with [ENT]'

```

**Comment by LysandreJik** [comment]
I think you can keep the issue open, this is a bug that should be fixed.

**Comment by cloudygoose** [comment]
This could be related, I'm on commit  d46147294852694d1dc701c72b9053ff2e726265
![image](https://user-images.githubusercontent.com/1544039/70831841-91c93e00-1dc1-11ea-9bb3-3803312d4456.png)
It's strange that the id for "student" changed after adding the special token
