### ISSUE TITLE
Graphormer

### ISSUE THREAD

**Issue by clefourrier** [huggingface/transformers#20962]
### Model description

Graph Transformer model developed by Microsoft.

https://graphormer.readthedocs.io/en/latest/

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Full implementation: https://github.com/microsoft/Graphormer/

Weights: 
-  pcqm4mv1_graphormer_base: https://ml2md.blob.core.windows.net/graphormer-ckpts/checkpoint_best_pcqm4mv1.pt
-  pcqm4mv2_graphormer_base: https://ml2md.blob.core.windows.net/graphormer-ckpts/checkpoint_best_pcqm4mv2.pt
-  pcqm4mv1_graphormer_base_for_molhiv: https://ml2md.blob.core.windows.net/graphormer-ckpts/checkpoint_base_preln_pcqm4mv1_for_hiv.pt

**Comment by Raman-Kumar** [comment]
Hi, @clefourrier  
can I contribute to this? also open to any other issue 
I have previously contributed to PyTorch (350+ lines of C++, Objective C, and Python)

**Comment by Raman-Kumar** [comment]
😊 Replying a little late, I was going through other issues and reading some PRs.
@clefourrier 
I would like to work on integrating TokenGT

and am also ready to offer any other help if you have a delegable workload.
Meanwhile, I am reading more blogs and your work.

**Comment by clefourrier** [comment]
Solved by the merge of Graphormer
