### ISSUE TITLE
Pipeline to support batch inference

### ISSUE THREAD

**Issue by maiiabocharova** [huggingface/transformers#20973]
### Feature request

Thank you for the awesome framework!
For my work I wanted to use `transformers.pipelines.token_classification.TokenClassificationPipeline` in batch mode, since it is much faster on GPU, but I wanted to keep all the functionality for grouping entities.
So I want to suggest something like this:
```
nlp = pipeline("ner", model=model, 
               tokenizer=tokenizer,
               device = 0 if torch.cuda.is_available() else -1,
               aggregation_strategy="average", batch_size=16)
```

### Motivation

I implemented it for myself and think it would be cool to have this functionality "out-of-the-box" for community to enjoy the speed up. (And it really gives a huge speed up)

### Your contribution

I am willing to contribute and implement this change for TokenClassification task (also for TextClassification, FeatureExtraction should be pretty much same). Have not worked with other pipelines, so not sure how batching is implemented there, but I am willing to try and contribute.

**Comment by sgugger** [comment]
cc @Narsil

**Comment by Narsil** [comment]
Hi @maiiabocharova doesn't this work already out of the box? 

```python
import torch
from transformers import pipeline

pipe = pipeline(
    "ner",
    device=0 if torch.cuda.is_available() else -1,
    aggregation_strategy="average",
    batch_size=16,
)


original_fn = pipe.model.forward
COUNT = 0


def new_forward(*args, **kwargs):
    global COUNT
    COUNT += 1
    return original_fn(*args, **kwargs)


pipe.model.forward = new_forward


def data():
    for i in range(20):
        yield "I live in New york"


for out in pipe(data()):
    print(out)

print(f"Forward called {COUNT} times")
```

This works, no ?

**Comment by maiiabocharova** [comment]
Sorry, probably I was looking into wrong source code

**Comment by Narsil** [comment]
Maybe an older version indeed. 

Also the batching mecanism is not really transparent in the pipeline code, it's meant to be relatively orthogonal (because making it explicit had too many drawbacks, like code duplication, and it was really hard to support more complex use cases).
