### ISSUE TITLE
Hugging Face Dies Silently when Memory insufficient for loading Model / Training Model 

### ISSUE THREAD

**Issue by courtneysprouse** [huggingface/transformers#20987]
Currently, when you load a model into memory that is too large or if you try to train a model with insufficient memory. The process gets killed without an error message. It's a bit tough to track down what is going on as a result. I'm wondering if you can add an error message similar to pytorch when you have insufficient memory to run a given process?

**Comment by sgugger** [comment]
If you have insufficient GPU memory, you will get the PyTorch error. For RAM issues, I don't think there is anything that exists to issue the same errors.

**Comment by courtneysprouse** [comment]
I was running on CPU. I know I've gotten the pytorch errors on GPU.  If nothing exists that's alright. Just thought it would be nice to get an error message so you could more easily see what was going on, particularly when you're just loading a model for inferencing, which is often done on cpu.
