### ISSUE TITLE
Query related to finetuning bert models for QA

### ISSUE THREAD

**Issue by gokul427** [huggingface/transformers#20997]
When we run run_qa.py on bert-base using squad data and once again fine tune it on custom data, will it retrain all the layers? or will it train only the last layer(head) freezing the other layers ? please explain the kind of finetuning done with run_qa.py

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for such questions as we keep issues for bugs and feature requests only.
