### ISSUE TITLE
which special token is used to predict the score in roberta?

### ISSUE THREAD

**Issue by tzhxs** [huggingface/transformers#2099]
In bert, we use the embedding of <cls> to predict the score, how about the roberta?

**Comment by BramVanroy** [comment]
Can you give some more information? It's not clear what you mean by "score". The special classification token for RoBERTa is `<s>`.

**Comment by tzhxs** [comment]
Thanks!

**Comment by BramVanroy** [comment]
@tzhxs If that's everything you need, please close this topic.

**Comment by tzhxs** [comment]
ok
