### ISSUE TITLE
Is there any way to treat the whitespace characters same as other characters when tokenizing?

### ISSUE THREAD

**Issue by Hans0124SG** [huggingface/transformers#2103]
## ❓ Questions & Help

I am trying to work on clinical notes data, and the whitespaces in the notes may contain useful information (e.g. section separation). Is there any way to encode the whitespaces as well during tokenization?

**Comment by mandubian** [comment]
Did you try replacing all meaningful whitespaces by a special token `<space>` and just add this new token to the tokenizer and train your model with it?

**Comment by Hans0124SG** [comment]
> Did you try replacing all meaningful whitespaces by a special token `<space>` and just add this new token to the tokenizer and train your model with it?

I guess it will be a bit tricky to define the "meaningful" whitespaces, but I will give it a shot. Thanks :)
