### ISSUE TITLE
ConvNeXT V2

### ISSUE THREAD

**Issue by IMvision12** [huggingface/transformers#21043]
### Model description

Short Description
Just released - ConvNeXt with a new internal layer.

In this paper, Authors propose a fully convolutional masked autoencoder framework and a new Global Response Normalization (GRN) layer that can be added to the ConvNeXt architecture to enhance inter-channel feature competition.

# Contribution 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Papers
https://arxiv.org/abs/2301.00808

Official Implementations
https://github.com/facebookresearch/ConvNeXt-V2

@NielsRogge @alaradirik

**Comment by alaradirik** [comment]
Hi @IMvision12! Thanks for taking this on, I think ConvNeXT V2 would be a great addition to transformers.

If you have any questions about the internal logic of the library or run into issues, you can ping me or @NielsRogge anytime. We can also create a Slack channel and continue the collaboration on the PR over there if you'd like.

**Comment by IMvision12** [comment]
Yeah slack channel will be great for communication here's my email : gitesh.ch.0912@gmail.com 
@alaradirik

**Comment by alaradirik** [comment]
@IMvision12 I sent the invite, looking forward to adding ConvNeXT V2 to transformers!

**Comment by asrimanth** [comment]
Hello, I'd like to work on this issue. How do I get started?

**Comment by IMvision12** [comment]
Hey @asrimanth There's already a PR for this under review https://github.com/huggingface/transformers/pull/21134

**Comment by alaradirik** [comment]
Hi @asrimanth, I took over the PR and I'm almost done with it. Feel free to look at other open issues though!
