### ISSUE TITLE
Fine-tune GIT on custom dataset [Expected input batch_size to match target batch_size]

### ISSUE THREAD

**Issue by vasyza** [huggingface/transformers#21052]
deleted

**Comment by nickvujicic** [comment]
@vasyza I'm doing research in swimming area and have the same issue. How to fix that?

**Comment by nickvujicic** [comment]
@vasyza Shame on u

**Comment by nickvujicic** [comment]
@sgugger and other developers please help

**Comment by sgugger** [comment]
I am not too sure how you want us to help without providing a reproducible example of the error you get.
