### ISSUE TITLE
Force_download=True not working, `No such file or directory: './.cache/models--togethercomputer--GPT-JT-6B-v1/refs/main'`

### ISSUE THREAD

**Issue by bhavnicksm** [huggingface/transformers#21061]
### System Info

- `transformers` version: 4.25.1
- Platform: Linux-5.15.0-57-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@younesbelkada @ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Got the error while running the following command:

```python
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("togethercomputer/GPT-JT-6B-v1", cache_dir='./.cache/')
```

### Expected behavior

Should download the model anew rather than looking in the cache

**Comment by susnato** [comment]
Hi, @bhavnicksm can you provide more information about your system (by using `transformers-cli env` in terminal) so that it will be easier to reproduce the code?

**Comment by sgugger** [comment]
Can you also tell us if there is folder `./.cache/` where you execute this code? Reading the error, it might simply be because the cache folder was not properly created.

**Comment by bhavnicksm** [comment]
@sgugger The cache folder gets created properly and there's the folder of that name, but the folder is not populated with any files. It's just empty.

**Comment by bhavnicksm** [comment]
Hi @susnato updated the original issue with the relevant information. Thanks for the suggestion to use `transformers-cli`.

**Comment by sgugger** [comment]
I ran your code snippet and cannot reproduce your issue. I also don't understand why that snippet of code should download anything anew and not look at the cache.

**Comment by bhavnicksm** [comment]
@sgugger the issue has been resolved, thanks for looking into it! 

I believe it was a connection issue with the servers because even SentenceTransformers was giving a error but something about how it couldn't connect to HF.

They both started to work at the same time a few hours later.
