### ISSUE TITLE
Different behavior in DistilBERT when using "inputs_embeds"

### ISSUE THREAD

**Issue by DiegoOrtego** [huggingface/transformers#21089]
### System Info

- `transformers` version: 4.24.0
- Platform: Linux-3.10.0-1160.80.1.0.1.el7.x86_64-x86_64-with-glibc2.27
- Python version: 3.10.8
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.12.1 (True)

@ArthurZucker @younesbelkada

### Reproduction

Do a forward pass with distilBERT passing "inputs_embs" instead of "input_ids", where "inputs_embs" contains the output of the forward over the word embedding matrix, i.e. just picking the token embeddings.
When doing this, one would expect the same behaviour as other popular models like BERT or ROBERTA, but distilBERT skips "positional embeddings addition + layerNorm + droput" as it skips the self.embedding() call.

I would expect that passing inputs_embs instead of input_ids has a coherent behaviour across diferent architectures, but it is not the case, at least for distilBERT. I am not sure if other models have this issue.

### Expected behavior

Properly build the input embedding by adding positional embeddings + layerNorm + droput (as happens in modeling_bert or modeling_roberta). This does not happen as the call to self.embedding() is skipped.

**Comment by ArthurZucker** [comment]
Hey, can you provide a reproducing script ?

**Comment by DiegoOrtego** [comment]
I don't think that I'll have soon time to prepare a reproducing script:

https://github.com/huggingface/transformers/blob/main/src/transformers/models/distilbert/modeling_distilbert.py#:~:text=.num_hidden_layers)-,if%20inputs_embeds%20is%20None%3A,),-%40add_start_docstrings(

**Comment by ArthurZucker** [comment]
Okay, this does not really need a reproduction script and I agree with you, the expected behaviour is that if you pre-compute the `input_embeds`, the output of the model should certainly be the same as if you were passing the input ids. This is true for most of our  models. I have to check whether there is a particular reason for this in DistillBert, otherwise will push a fix!

**Comment by DiegoOrtego** [comment]
Great news @ArthurZucker !
