### ISSUE TITLE
AutoModels for region-to-phrase-alignment and natural-language-for-visual-reasoning

### ISSUE THREAD

**Issue by mszsorondo** [huggingface/transformers#21086]
### Feature request

Hi! Region to phrase alignment and natural language for visual reasoning have no AutoModels yet. @sgugger is it OK to open a PR and solve this?

### Motivation

This is an issue that I faced when exporting VisualBert to ONNX, since the task mapping can't be done without it. Adding it would allow us to make the export for every task.

### Your contribution

I'll open a PR and solve it myself if allowed

**Comment by sgugger** [comment]
Note that the ONNX conversion is now done directly in the optimum library, so this is probably where you would need to add something.

**Comment by mszsorondo** [comment]
That's true, I'm doing the ONNX conversion from optimum. But optimum references AutoModels directly from transformers. I'd just program the AutoModel subclasses without any optimum stuff, of course.

**Comment by fxmarty** [comment]
Agreed, note that "use in transformers" for https://huggingface.co/uclanlp/visualbert-vqa is broken as well

**Comment by mszsorondo** [comment]
@sgugger Sorry for insisting, I know you have lots of issues opened already. Just tagging you to see if you still think this should be solved from Optimum

**Comment by sgugger** [comment]
I think the optimum library should provide an API for models that don't have an auto API yes (if it does not already), as there will always be such models and we won't add a new auto class for just one model.

cc @michaelbenayoun who might have more information.

**Comment by michaelbenayoun** [comment]
Hi @mszsorondo,
Could you open a PR on the Optimum repo, with your request explained please?
