### ISSUE TITLE
device_map='auto' causes memory to not be freed with torch.cuda.empty_cache()

### ISSUE THREAD

**Issue by oobabooga** [huggingface/transformers#21094]
### System Info

If I load a model like this

```
model = AutoModelForCausalLM.from_pretrained("models/opt-13b", device_map='auto', load_in_8bit=True)
```

and then do

```
model = None
torch.cuda.empty_cache()
```

the VRAM is not freed. The only way I have found to release it is to kill the program and start it over. 

Freeing the memory like this works if the model is loaded the normal way with

```
model = AutoModelForCausalLM.from_pretrained("models/opt-13b", low_cpu_mem_usage=True, torch_dtype=torch.float16).cuda()
```

@ArthurZucker @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code snippet is provided in the description above.

### Expected behavior

VRAM should be freed with `torch.cuda.empty_cache()`.

**Comment by ArthurZucker** [comment]
That is an interesting bug, but should probably be adressed in `accelerate` as using `device_map = "auto"` is reliant on the accelerate library.

**Comment by sgugger** [comment]
I think it's the 8bit part that may be causing the issue, actually ;-)

**Comment by sgugger** [comment]
I have tried and can indeed reproduce without the 8bit loading. I don't know why the cache appears nonempty, but iterating on a loop (re-creating the model and then deleting it several times) does not result in a memory increase, so the memory is reused when we need it.

If someone manages to find more about this, I'd be very interested to learn why this is the case.

**Comment by git-longcat** [comment]
```
gc.collect()
torch.cuda.empty_cache()
gc.collect()
```
may free memory.

**Comment by younesbelkada** [comment]
I can confirm that ~690MB of seems to be freed (monitoring with `nvidia-smi`) thanks to the trick proposed by @git-longcat 
```
import torch
import gc
from transformers import AutoModelForCausalLM

model_accelerate = AutoModelForCausalLM.from_pretrained("facebook/opt-350m", device_map={"":0}, torch_dtype=torch.float16)
model_torch = AutoModelForCausalLM.from_pretrained(
    "facebook/opt-350m", low_cpu_mem_usage=True, torch_dtype=torch.float16
).cuda()

del model_accelerate
gc.collect()
torch.cuda.empty_cache()

del model_torch
torch.cuda.empty_cache()
```
@oobabooga can you try on your side and let us know if this trick works? 
It seems crucial to call `gc.collect()` before `torch.cuda.empty_cache()`

**Comment by oobabooga** [comment]
@git-longcat I confirm that this works. Thank you. 

In fact, all I needed was

```
model = None
gc.collect()
torch.cuda.empty_cache()

```

This doesn't work:

```
model = None
torch.cuda.empty_cache()
gc.collect()
```

This resolves the issue for me. I don't know if it can still be considered a bug or not.

**Comment by muellerzr** [comment]
@sgugger WDYT of a `free_memory` util in `Accelerate` that will do the `torch.cuda.empty_cache(), gc.collect()` part and instructs users that they should set objects to delete as `None` (or, even better, we could just do that under the hood and have the users pass those objects in to free).

This also means there's a bug in our current implementation of `Accelerator.free_memory` as it does `gc.collect` before `empty_cache()`, and the results here show that it should be reversed

**Comment by muellerzr** [comment]
@younesbelkada @oobabooga in Accelerate dev now (install via `pip install git+https://github.com/huggingface/accelerate`) I've introduced a `release_memory` util that will perform the above for `n` objects easily:
```python
  >>> import torch
  >>> from accelerate.utils import release_memory

  >>> a = torch.ones(1000, 1000).cuda()
  >>> b = torch.ones(1000, 1000).cuda()
  >>> a, b, model = release_memory(a, b, model)
```
Just ensure that the objects are in the same order they were passed in as so the memory will be fully override. (see https://github.com/huggingface/accelerate/pull/990 for more information)
