### ISSUE TITLE
GPT2 tokenizer decode swallows space

### ISSUE THREAD

**Issue by daniel-ziegler** [huggingface/transformers#21119]
### System Info

- `transformers` version: 4.25.1
- Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
- Python version: 3.9.15
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.10.2+cu113 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.4.1 (cpu)
- Jax version: 0.4.1
- JaxLib version: 0.4.1
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokens = tokenizer.encode("y is ?")
print(tokens)  # prints [88, 318, 5633]
print(tokenizer.decode(tokens))  # prints "y is?" (wrong!)
```

### Expected behavior

It should roundtrip back to the same string, matching the behavior of OpenAI's reference implementation: https://github.com/openai/gpt-2/blob/master/src/encoder.py

OpenAI's implementation encodes to the same tokens, but correctly decodes them to `"y is ?"`

**Comment by susnato** [comment]
Hi, @daniel-ziegler use `clean_up_tokenization_spaces=False` in `decode` so the code will be - 
`print(tokenizer.decode(tokens, clean_up_tokenization_spaces=False))` 
this solves the problem,

thanks, 
susnato.

**Comment by ArthurZucker** [comment]
Indeed! Thanks for jumping this quickly @susnato 🤗

**Comment by daniel-ziegler** [comment]
Thanks, that does work. I still think it's a bug that that isn't the default behavior for reversible tokenizers like GPT2's -- there's only one standard decoding behavior for them and it should be the default.

**Comment by susnato** [comment]
@daniel-ziegler, I think it's due to the reason that most tokenizers don't preserve the structure such as spaces, and the huggingface team didn't want to have different implementations for both type of tokenizers (which will make the code more complecated!), so it's True by default.

**Comment by varadhbhatnagar** [comment]
@ArthurZucker When LLMs are used to generate code, keeping `clean_up_tokenization_spaces=True`  can lead to uncompilable code being generated because of the [clean_up_tokenization()](https://github.com/huggingface/transformers/blob/c48787f347bd604f656c2cfff730e029c8f8c1fe/src/transformers/tokenization_utils_base.py#L3798) method. I wanted to know if there are any pitfalls while using `clean_up_tokenization_spaces=False` ?

**Comment by ArthurZucker** [comment]
I have not conducted experiments but overall would just not recommend using GPT2 model. 🤗

**Comment by varadhbhatnagar** [comment]
@ArthurZucker Will the same issue not persist in Llama as well? If the next token to be generated is between two quotes, it can still give an error when `clean_up_tokenization_spaces=True`. (`string var1 = "abc"` vs `string var1 = "abc "`)

**Comment by ArthurZucker** [comment]
No it's not the same tokenizer so I don't think it will have the same behaviour
