### ISSUE TITLE
Could not run run_ner.py based on XLNET model

### ISSUE THREAD

**Issue by Vitvicky** [huggingface/transformers#2111]
## ❓ Questions & Help

Hello everyone, when I try to use ELnet model for the NER task through run_ner.py, it shows the following problem:

__init__() got an unexpected keyword argument 'do_lower_case'

So is it some problem in the modeling_utils.py? Thanks for someone's response!

**Comment by TheEdoardo93** [comment]
What is ELnet model?

**Comment by Vitvicky** [comment]
> What is ELnet model? The list of models that can be used for NER are: BERT, RoBERTa, DistilBERT (only for English text) and CamemBERT (only for French text).
> 
> > ## Questions & Help
> > Hello everyone, when I try to use ELnet model for the NER task through run_ner.py, it shows the following problem:
> > **init**() got an unexpected keyword argument 'do_lower_case'
> > So is it some problem in the modeling_utils.py? Thanks for someone's response!

I add ELNet in the run_ner.py:
from transformers import XLNetConfig, XLNetTokenizer, XLNetForTokenClassification
MODEL_CLASSES = {
    "bert": (BertConfig, BertForTokenClassification, BertTokenizer),
    "roberta": (RobertaConfig, RobertaForTokenClassification, RobertaTokenizer),
    "distilbert": (DistilBertConfig, DistilBertForTokenClassification, DistilBertTokenizer),
    "camembert": (CamembertConfig, CamembertForTokenClassification, CamembertTokenizer),
    "xlnet": (XLNetConfig, XLNetTokenizer, XLNetForTokenClassification),
}

**Comment by TheEdoardo93** [comment]
> > What is ELnet model? The list of models that can be used for NER are: BERT, RoBERTa, DistilBERT (only for English text) and CamemBERT (only for French text).
> > > ## Questions & Help
> > > Hello everyone, when I try to use ELnet model for the NER task through run_ner.py, it shows the following problem:
> > > **init**() got an unexpected keyword argument 'do_lower_case'
> > > So is it some problem in the modeling_utils.py? Thanks for someone's response!
> 
> I add XLNet in the run_ner.py:
> from transformers import XLNetConfig, XLNetTokenizer, XLNetForTokenClassification
> MODEL_CLASSES = {
> "bert": (BertConfig, BertForTokenClassification, BertTokenizer),
> "roberta": (RobertaConfig, RobertaForTokenClassification, RobertaTokenizer),
> "distilbert": (DistilBertConfig, DistilBertForTokenClassification, DistilBertTokenizer),
> "camembert": (CamembertConfig, CamembertForTokenClassification, CamembertTokenizer),
> "xlnet": (XLNetConfig, XLNetTokenizer, XLNetForTokenClassification),
> }

Did you read #1592 and #2051 and similar?

**Comment by Vitvicky** [comment]
> > > What is ELnet model? The list of models that can be used for NER are: BERT, RoBERTa, DistilBERT (only for English text) and CamemBERT (only for French text).
> > > > ## Questions & Help
> > > > Hello everyone, when I try to use ELnet model for the NER task through run_ner.py, it shows the following problem:
> > > > **init**() got an unexpected keyword argument 'do_lower_case'
> > > > So is it some problem in the modeling_utils.py? Thanks for someone's response!
> > 
> > 
> > I add XLNet in the run_ner.py:
> > from transformers import XLNetConfig, XLNetTokenizer, XLNetForTokenClassification
> > MODEL_CLASSES = {
> > "bert": (BertConfig, BertForTokenClassification, BertTokenizer),
> > "roberta": (RobertaConfig, RobertaForTokenClassification, RobertaTokenizer),
> > "distilbert": (DistilBertConfig, DistilBertForTokenClassification, DistilBertTokenizer),
> > "camembert": (CamembertConfig, CamembertForTokenClassification, CamembertTokenizer),
> > "xlnet": (XLNetConfig, XLNetTokenizer, XLNetForTokenClassification),
> > }
> 
> Did you read #1592 and #2051 and similar?

I just find it, thanks sir!
