### ISSUE TITLE
Deprecating `position_ids` in GPTJ

### ISSUE THREAD

**Issue by KaijuML** [huggingface/transformers#21114]
### System Info

latest transformers version, pytorch

### Who can help?

Hi @ArthurZucker and @younesbelkada, let me know if someone else should be tagged in this, esp. considering this is a harmless "bug", not something really urgent.

Basically what the title says: I think the position_ids in the [GPT-J code](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gptj/modeling_gptj.py) should be deprecated, since they are not used anywhere as far as I can tell. Something along the line of what bloom does at:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/bloom/modeling_bloom.py#L891

I can also submit a PR if you want, just wanted to make sure I didn't overlook anything.

Let me know,
Clément

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

N/A

### Expected behavior

Cleaner code, no useless no-op

**Comment by sgugger** [comment]
Friendly ping @ArthurZucker and @younesbelkada

**Comment by ArthurZucker** [comment]
I agree with you, opened a PR for this. Thanks for reporting.
