### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by milohpeng** [huggingface/transformers#21129]
### System Info

transformers==4.25.1

Code block:

from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("flax-community/roberta-base-thai")
model = AutoModelForMaskedLM.from_pretrained("flax-community/roberta-base-thai")

Error:

OSError: There was a specific connection error when trying to load flax-community/roberta-base-thai:
429 Client Error: Too Many Requests for url: https://huggingface.co/flax-community/roberta-base-thai/resolve/main/config.json

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Import package and run code. 

### Expected behavior

No errors expected.

**Comment by susnato** [comment]
Hi, @milohpeng the script you gave seems to run fine on my side, maybe it was a issue regarding your connection, can you try now again and check if it runs or not? Or run `transformers-cli env` in terminal and give your system info so we can reproduce the error.

**Comment by milohpeng** [comment]
Here is the information as requested, 

- `transformers` version: 4.25.1
- Platform: Linux-5.4.56.bsk.10-amd64-x86_64-with-debian-10.12
- Python version: 3.7.3
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.11.0+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

I'm not sure whether my IP has been blacklisted...

**Comment by susnato** [comment]
@milohpeng I used the same environment as you and managed to get the results without any errors, maybe you tried to download the model so many times that they blacklisted your IP. 

I can't help you with this but maybe @sgugger can.

**Comment by sgugger** [comment]
This should not consistently happen, as the error reflected (429) requires **a lot** of requests in a short amount of time. @milohpeng are you using a shared IP by any chance?

**Comment by milohpeng** [comment]
Hey @sgugger yes I am, I'm using my company's IP to access Huggingface. Is there anything I can do to reverse this as my colleagues seem to be affected as well? Thanks in advance!

**Comment by sgugger** [comment]
Could you provide us with the IP in question, so that I can investigate further with our infra team? Thanks!

**Comment by amyeroberts** [comment]
Hi @trianxy, sadly @sgugger is no longer at HF so the email in this thread is no longer active. 

Pinging @philschmid who is the AWS Sagemaker master and will know more about this issue.

**Comment by philschmid** [comment]
@trianxy it seems like that the IP "spammed" the hub and you got rate limited. Did you ran some sort of loop to load stuff? The restriction should be lifted after 24h

**Comment by philschmid** [comment]
let me share that internally.

**Comment by philschmid** [comment]
can you sent the full IP at api-enterprise@huggingface.co? cc @XciD

**Comment by XciD** [comment]
Hi @trianxy,

Seems like the EC2 Ip you have was blacklisted in our waf. I've removed the restriction. Should be ready in a few minutes. 

Can you retry ?

**Comment by sooryansatheesh** [comment]
`429 Client Error: Too Many Requests for url: [https://api-inference.huggingface.co/models](https://api-inference.huggingface.co/models/smart-panda314/dummy) `

I got the above error when I was trying to get tabular classification predictions from my own model 

I used the code below 
`from huggingface_hub import InferenceClient
input_data = [2, 3, 4, 2, 4]
# Create DataFrame
df = pd.DataFrame([input_data], columns=cols_used)

# Initialize the InferenceClient with your model
client = InferenceClient()

# Convert the DataFrame to a list of dictionaries (each dictionary representing a row)
table = df.to_dict(orient="records")

print(table)
client.tabular_classification(table=table, model=model_id)`

Can someone help me?

**Comment by asma-10** [comment]
Hello, i am having the same problem using a HF llm
llm = HuggingFaceInferenceAPI(model_name="HuggingFaceH4/zephyr-7b-alpha", api_key='<HF_TOKEN>')
and recently i've been receiving this error : 
HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-alpha (Request ID: eEUYA-cnktBRdtG1e1zz9)

Rate limit reached. You reached free usage limit (reset hourly). Please subscribe to a plan at https://huggingface.co/pricing to use the API at this rate 

even with a new HF account i still get the same error : 
HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://api-inference.huggingface.co/models/sentence-transformers/all-MiniLM-L6-v2 (Request ID: wlfNPgrEVuuH-lC_Mfgm4)

Rate limit reached. Please log in or use a HF access token 

Anyone can help with this ? 
Thanks in advance

**Comment by asma-10** [comment]
@trianxy hey again, i hope that this message reaches you so that you may help me if you can so

**Comment by JorgeRamiroDev** [comment]
@XciD I don't know what's going on, <Response [429]>
{'error': 'Rate limit reached. Please log in or use a HF access token'} appears in my terminal when I try to run the model and I already put my read and write access token, I didn't make many requests so I find it unlikely that I have reached the limit, I appreciate any help

![image](https://github.com/huggingface/transformers/assets/102836967/3d06a20d-d50e-47eb-97ed-622dee780f06)

**Comment by moctarjallo** [comment]
facing the same problem here. help!

**Comment by talipturkmen** [comment]
Hi @XciD,
I have the same problem. Could you help please?

**Comment by jxmorris12** [comment]
This still happens to me even though I set HF_HUB_OFFLINE=1.

**Comment by rohanJa** [comment]
@jxmorris12 in that case have pointed the model to corrected directory path, it should use that
