### ISSUE TITLE
MT5ForConditionalGeneration: forward() got an unexpected keyword argument 'penalty_alpha'

### ISSUE THREAD

**Issue by Mahyar-Ali** [huggingface/transformers#21127]
When I use the MT5ForConditionalGeneration class to load an mt5 model and then specify the `penalty_alpha` parameter in the generate function, the library raises the error `forward() got an unexpected keyword argument 'penalty_alpha'`. But when I load the same model with `AutoModelForSeq2SeqLM` class, it doesn't raise that issue.

This shouldn't be happening because the `AutoModel` class automatically selects the relevant `MT5ForConditionalGeneration` for all T5 models. So, why does this raises an issue when I use the `MT5ForConditionalGeneration` directly?

Also, this is particularly interesting because when you fine-tune a t5 model using the `MT5ForConditionalGeneration` class but load that model(after training) using the `AutoModelForSeq2SeqLM` and then use the `penalty_alpha`, it still raises the same issue.

Code:

```
model = MT5ForConditionalGeneration.from_pretrained(f"{model_dir}")
tokenizer = MT5Tokenizer.from_pretrained(f"{model_dir}")



input_ids = tokenizer.encode(
            source_text, return_tensors="pt", add_special_tokens=True
        )
input_ids = input_ids.to(device)
generated_ids = model.generate(
            input_ids=input_ids,
            penalty_alpha=0.6, top_k=4
        )
preds = [
    tokenizer.decode(
        g,
        skip_special_tokens=skip_special_tokens,
        clean_up_tokenization_spaces=clean_up_tokenization_spaces,
    )
    for g in generated_ids
]
```

Transformers version: 4.16.2
Python version: 3.9.15

**Comment by sgugger** [comment]
cc @gante

**Comment by susnato** [comment]
Hi, @Mahyar-Ali 
I have transformers - 4.25.1 and used the code you gave (above) and it ran without any error, then I switched back to transformers - 4.16.2(same as your version) and it gave the error regarding "penalty alpha", I believe it is fixed in later versions of transformers, since I got the output in version 4.25.1 .

Maybe you can try to upgrade to latest version and check if it works for you or not.

**Comment by Mahyar-Ali** [comment]
It's working now. Didn't pay attention to the version (as it was working well for `AutoModel`). Thanks!

**Comment by gante** [comment]
@susnato thank you for pitching in ;)
