### ISSUE TITLE
Ernie-M

### ISSUE THREAD

**Issue by KnutJaegersberg** [huggingface/transformers#21123]
### Model description

Ernie-M looks pretty good in multilingual benchmarks, beating XLM-Roberta. 
Paddlepaddle recently added ernie-m to the huggingface repo, we can use it with paddlenlp.transformers. 
Would be nice to have the model supported in huggingface transformer as well. 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://huggingface.co/PaddlePaddle/ernie-m-base
https://huggingface.co/PaddlePaddle/ernie-m-large

**Comment by shermansiu** [comment]
https://github.com/PaddlePaddle/ERNIE/blob/ernie-kit-open-v1.0/erniekit/modules/ernie.py

**Comment by susnato** [comment]
Hi, @shermansiu is there any pytorch/tf implementation of this model?

**Comment by shermansiu** [comment]
None that I'm aware of.

Anyways, the author of [ERNIE-Pytorch](https://github.com/nghuyong/ERNIE-Pytorch) ported over a few other Ernie models to Huggingface. I'm sure it could be adapted for this. And the PaddlePaddle syntax is quite similar to that of PyTorch, so I'm sure it should be relatively easy, though it'll probably take some time.

**Comment by susnato** [comment]
@shermansiu Thanks for the resources!
I am currently trying to port the model to huggingface(pytorch), (done till Embedding Layer with acceptable tolerance of 1e-3)

**Comment by susnato** [comment]
Hi @KnutJaegersberg, Ernie-M is implemented!
