### ISSUE TITLE
could set  max_length or max_seq_length bigger than 512 in NER?

### ISSUE THREAD

**Issue by ucas010** [huggingface/transformers#21131]
### System Info

- `transformers` version: 4.26.0.dev0
- Platform: Linux-3.10.0-1160.81.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.15
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Tensorflow version (GPU?): 2.6.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sgugger 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/tree/main/examples/pytorch/token-classification
for fine-tune in NER
could I set --max_length or --max_seq_length bigger than 512 ??

  File "/data/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 237, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (2048) must match the size of tensor b (512) at non-singleton dimension 1

### Expected behavior

as I said before

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for such questions, as we keep issues for bugs and feature requests only.
