### ISSUE TITLE
Feature Request: Flax Whisper

### ISSUE THREAD

**Issue by OhadRubin** [huggingface/transformers#21138]
### Feature request

It already has TF and Pytorch support. Would be nice to use it on Flax as-well.

**Comment by NielsRogge** [comment]
cc @sanchit-gandhi

**Comment by sanchit-gandhi** [comment]
Hey @OhadRubin! Thanks to the fantastic work by @andyehrenberg it's nearly complete: https://github.com/huggingface/transformers/pull/20479

Will do a final review tomorrow and then get it merged asap!
