### ISSUE TITLE
Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by manandey** [huggingface/transformers#21145]
### System Info

I trained a model and uploaded the checkpoint in the Hub [here](https://huggingface.co/taskydata/deberta-v3-base_10xp3nirstbbflanseuni_10xc4). When I try to load the model, I get the following error message:
`OSError: Unable to load weights from pytorch checkpoint file for '/root/.cache/huggingface/hub/models--taskydata--deberta-v3-base_10xp3nirstbbflanseuni_10xc4/snapshots/f5d6b49731ea0b36601f151dd67623380462a3cb/pytorch_model.bin' at '/root/.cache/huggingface/hub/models--taskydata--deberta-v3-base_10xp3nirstbbflanseuni_10xc4/snapshots/f5d6b49731ea0b36601f151dd67623380462a3cb/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.`

Also, when I try to run it using the inference API, I get:
`Could not load model taskydata/deberta-v3-base_10xp3nirstbbflanseuni_10xc4 with any of the following classes: (<class 'transformers.models.deberta_v2.modeling_deberta_v2.DebertaV2ForSequenceClassification'>, <class 'transformers.models.deberta_v2.modeling_tf_deberta_v2.TFDebertaV2ForSequenceClassification'>).`

Transformer version: `4.25.1`

Any help on how to resolve this would be greatly appreciated. Thanks!

cc. @LysandreJik @younesbelkada @ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Mentioned above.

### Expected behavior

The model should be loading since all the files are uploaded.

**Comment by younesbelkada** [comment]
Hi @manandey 
Your saved model is probably corrupted, could you tell us how did you saved the model, or alternatively give it another try?

**Comment by manandey** [comment]
Hi @younesbelkada, when I try to load the model by connecting my colab to the GCP instance where the checkpoints are saved, the model seems to be loading perfectly fine as can be seen in the attached snapshot. But when I try to download the checkpoint and upload it to hub, the downloaded files seem to become corrupted. 
![image](https://user-images.githubusercontent.com/6687858/212846041-0a7223f6-063f-449e-900c-ce60a5a6f96d.png)

**Comment by younesbelkada** [comment]
If I understood correctly you are manually uploading the weights on the Hub?
Can you maybe try: 
```
model.push_to_hub("taskydata/deberta-v3-base_10xp3nirstbbflanseuni_10xc4")
```
after the lines that you have attached above. 
Make sure to login from your notebook with:
```
from huggingface_hub import notebook_login
notebook_login()
```

**Comment by manandey** [comment]
Thanks a lot, @younesbelkada! It worked!

**Comment by younesbelkada** [comment]
Very happy that it worked! Thanks for guiding us precisely through your issue
