### ISSUE TITLE
Feature Request: VideoMAEForMaskedVideoModeling

### ISSUE THREAD

**Issue by will-rice** [huggingface/transformers#21159]
### Feature request

Basically, it would be nice if we could fill in the masked video.

### Motivation

I doubt I'm the only person that would like to try/train this model for inpainting masked video.

### Your contribution

I guess I could contribute it since I went to the torchside

**Comment by NielsRogge** [comment]
Hi,

This is already available, the class is called VideoMAEForPreTraining. To reconstruct pixel values, you can load the following model:
```
from transformers import VideoMAEForPreTraining

model = VideoMAEForPreTraining.from_pretrained("MCG-NJU/videomae-base")
```

To visualize a masked video, you can borrow the code from the [original implementation](https://github.com/MCG-NJU/VideoMAE/blob/45dcd7f10183099669baa481c6d33165842d8bf3/run_videomae_vis.py#L167).
