### ISSUE TITLE
ImportError: cannot import name 'LayoutLMv3ForTokenClassification' from 'transformers' (unknown location)

### ISSUE THREAD

**Issue by Harikishore-KA** [huggingface/transformers#21184]
from transformers import LayoutLMv3ForTokenClassification

Unable to import LayoutLMv3 models

OS : Windows 10 
Python : Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  4 2021, 13:27:16) [MSC v.1928 64 bit (AMD64)] on win32
Package versions: transformers==4.26.0.dev0, torch==1.13.1

![image](https://user-images.githubusercontent.com/17734294/213330793-afe84196-9c6f-4484-aa9f-a631697a5bdf.png)

**Comment by NielsRogge** [comment]
Hi,

I'm not able to reproduce this error. It might make sense to uninstall and install transformers in a new, clean environment.
