### ISSUE TITLE
How to use Ipex via transformers

### ISSUE THREAD

**Issue by Oxi84** [huggingface/transformers#21180]
### Feature request

I saw you implemented Ipex. intel cpu optimisation but there is no any example how to use it via python. Only this example is available:

     python run_qa.py \
    --model_name_or_path csarron/bert-base-uncased-squad-v1 \
    --dataset_name squad \
    --do_eval \
    --max_seq_length 384 \
    --doc_stride 128 \
    --output_dir /tmp/ \
     --use_ipex \ 
     --jit_mode 

And this is not very useful for me as  I do interface via python script., not via command lines.

How would i use that here for example:

     from transformers import AutoTokenizer, AutoModel
     tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
     model = AutoModel.from_pretrained("bert-base-uncased")

### Motivation

documentation

### Your contribution

documentation

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for such question as we keep issues for bugs and feature requests only.
