### ISSUE TITLE
Could convert_pytorch_checkpoint_to_tf2.py convert any pytorch model to tf2?

### ISSUE THREAD

**Issue by xealml** [huggingface/transformers#2118]

**Comment by TheEdoardo93** [comment]
I think **no**. You can use this Python script to convert a PyTorch implementation of one of the models supported by Transformers to TensorFlow 2.0 version.

Have you ever tried to use this Python script to convert **any** PyTorch model to TensorFlow 2.0?

> ##  Questions & Help

**Comment by xealml** [comment]
@TheEdoardo93 No,have not tried.I read the code.Finding maybe the model costumed support converting.
