### ISSUE TITLE
Typo in XCLIP model

### ISSUE THREAD

**Issue by Zhilin123** [huggingface/transformers#21204]
### System Info

transformers version 4.25.1

### Who can help?

@NielsRogge @ydshieh 

There's a typo/mismatch for the xclip model pretrained config archive map between https://github.com/huggingface/transformers/blob/main/src/transformers/models/auto/configuration_auto.py#L333

and. https://github.com/huggingface/transformers/blob/main/src/transformers/models/x_clip/configuration_x_clip.py#L27

notice in the first example, there is underscore between X and CLIP whereas in the second example, there isn't.

This leads to an error when initializing automodel

`   
    huggingface_models = list(ALL_PRETRAINED_CONFIG_ARCHIVE_MAP.keys())

  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 612, in keys

    self._initialize()

  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 602, in _initialize

    mapping = getattr(module, map_name)

  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 1086, in __getattr__

    raise AttributeError(f"module {self.__name__} has no attribute {name}")

AttributeError: module transformers.models.x_clip has no attribute X_CLIP_PRETRAINED_CONFIG_ARCHIVE_MAP`

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. from transformers import ALL_PRETRAINED_CONFIG_ARCHIVE_MAP
2. huggingface_models = list(ALL_PRETRAINED_CONFIG_ARCHIVE_MAP.keys())

### Expected behavior

Expect no errors to be raised

**Comment by ydshieh** [comment]
@Zhilin123 Thank you for reporting. See #21207. However, note that 

```
ALL_PRETRAINED_CONFIG_ARCHIVE_MAP is deprecated and will be removed in v5 of Transformers.
```
