### ISSUE TITLE
rename configuration_utils.PretrainedConfig.max_length to max_generation_length

### ISSUE THREAD

**Issue by aaronrmm** [huggingface/transformers#21203]
### Feature request

Max length (and min length) is an overloaded term. This renaming would help disambiguate this parameter from tokenizer max lengths when parameters are logged.

https://github.com/huggingface/transformers/blob/862888a35834527fed61beaf42373423ffdbd216/src/transformers/configuration_utils.py#L119

### Motivation

When looking at Mlflow logs for my text classification model, I saw "max length" as one of the parameters. I had to debug to figure out that it was not relevant to classification. This seems to me like the simplest solution to make it clear that it is a parameter that is only relevant to generation.

### Your contribution

I can of course do a PR with the renaming change. However, I am not sure of the downstream implications.

**Comment by sgugger** [comment]
Thanks for raising an issue. Renaming an argument like this which is so widely used is too breaking a change for us to consider however.

**Comment by aaronrmm** [comment]
Makes sense. Perhaps there is something that can be done in the mlflow logger instead. I'll raise a different issue if I have any ideas.
