### ISSUE TITLE
BertModel.from_pretrained() doesn't accept pathlib.PosixPath anymore

### ISSUE THREAD

**Issue by koichikawamura** [huggingface/transformers#2120]
## 🐛 Bug

Model I am using (Bert, XLNet....): Bert

Language I am using the model on (English, Chinese....): Japanese

The problem arise when using:
* [ ] the official example scripts: (give details)
* [x] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details)

## To Reproduce

1. Prepare a directory with `config.json`, `pytorch_model.bin`.
2. Give the directory as a pathlib.PosixPath such like `bert_model = BertModel.from_pretrained(bert_path)`
3.

TypeError: argument of type 'PosixPath' is not iterable

## Expected behavior

This used to load the model with 2.1.1, but started to cause an error since 2.2.0.
`bert_model = BertModel.from_pretrained(str(bert_path))` works.

## Environment

colab
* OS:
* Python version:
* PyTorch version:
* PyTorch Transformers version (or branch): 2.2.0 and later
* Using GPU ?
* Distributed of parallel setup ?
* Any other relevant information:

**Comment by mandubian** [comment]
It comes from this line https://github.com/huggingface/transformers/blob/master/transformers/modeling_utils.py#L321-L324
If it's a PosixPath, it's not an iterable so `"albert" in path` crashes.
Patch coming very soon
