### ISSUE TITLE
Models not in eval()-mode when loaded with from_config()

### ISSUE THREAD

**Issue by hadsed** [huggingface/transformers#21244]
### System Info

The docs say that models loaded with `from_pretrained()` are done so with `model.eval()` mode on by default. But when using `from_config()` that's not the case, even though loading configs and tokenizers would be using `from_pretrained()` like so:
```python
config = AutoConfig.from_pretrained(
    MODEL_NAME,
    padding='max_length',
    truncation=True,
    output_hidden_states=True,
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, config=config)
model = AutoModelForSequenceClassification.from_config(config)
```
I'd like to argue that we should put the model in `eval()` mode when using `from_config()`. I know at least 2 other people who have spent a great number of hours validating and hunting for that. Similar reasoning to https://github.com/huggingface/transformers/issues/695#issuecomment-502964803 I think it's important to make things deterministic out of the box.

Or, open to understanding why that wouldn't be the case.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Try something like this:
```python
config = AutoConfig.from_pretrained(
    MODEL_NAME,
    padding='max_length',
    truncation=True,
    output_hidden_states=True,
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, config=config)
model = AutoModelForSequenceClassification.from_config(config)
```

### Expected behavior

I'd expect the model to be loaded in `eval()` mode.

**Comment by hadsed** [comment]
The code snippet I posted above does not load random weights.

**Comment by sgugger** [comment]
Yes it does.

**Comment by hadsed** [comment]
Well that explains a lot. I stand corrected, thank you.
