### ISSUE TITLE
Where is extract_features.py and run_classifier.py ?

### ISSUE THREAD

**Issue by JiangYanting** [huggingface/transformers#2127]
## ❓ Questions & Help

Hello! I couldn't find the extract_features.py and run_classifier.py. Have they been renamed ?

**Comment by TheEdoardo93** [comment]
Reading the answer given by @thomwolf in #1123, I'm sure that `extract_features.py` script has been removed from repo, but in the future it could be updated!

Reading the answer given by @ningjize in #1011, I'm sure that `run_classifier.py` script has been updated as `run_glue.py` script, that you can find in `examples/` directory [here](https://github.com/huggingface/transformers/blob/master/examples/run_glue.py).

> ## ❓ Questions & Help
> Hello! I couldn't find the extract_features.py and run_classifier.py. Have they been renamed ?
