### ISSUE TITLE
How to use pre-trained BERT or GPT transformers for CNN based video captioning

### ISSUE THREAD

**Issue by adeljalalyousif** [huggingface/transformers#21279]
Hello, How to use pre-trained BERT or GPT transformers for video captioning task using CNN features not vision transformer

**Comment by NielsRogge** [comment]
Hi,

I'd recommend checking out the [GIT](https://huggingface.co/docs/transformers/main/en/model_doc/git) model which was just added to the library, as it's the first one in this library that can be used for video captioning. Check out the demo notebook [here](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/GIT/Inference_with_GIT_for_image_video_captioning_and_image_video_QA.ipynb).

The model is a GPT-like model conditioned on both images and text to predict the next text tokens.

**Comment by NielsRogge** [comment]
Closing this as it seems resolved.

**Comment by adeljalalyousif** [comment]
Thank you so much
