### ISSUE TITLE
In which directory the downloaded roberta-base models will be stored on linux server conda environment

### ISSUE THREAD

**Issue by jonanem** [huggingface/transformers#2128]

**Comment by LysandreJik** [comment]
Models downloaded with the `XXXModel.from_pretrained` method are usually in the torch home folder, which is `~/.cache/torch/transformers`

**Comment by jonanem** [comment]
Thanks for your response. I could see there are some files with below names
b35e7cd126cd4229a746b5d5c29a749e8e84438b14bcdb575950584fe33207e8.70bec105b4158ed9a1747fea67a43f5dee97855c64d62b6ec3742f4cfdb5feda.json

Can we rename those files something like below, the naming convention mentioned in https://s3.amazonaws.com/models.huggingface.co/

roberta-base-config.json

and load them as RobertaTokenizer.from_pretrained('roberta-base')

**Comment by aaugustin** [comment]
#2157 is very similar; perhaps it'll answer your question.

**Comment by johntiger1** [comment]
If we have the model loaded, can we then find from where on disk it was loaded?
