### ISSUE TITLE
Adding NLLB-200 - MoE - 54.5B for no language left behind

### ISSUE THREAD

**Issue by PierreColombo** [huggingface/transformers#21300]
### System Info

Hello  @LysandreJik,
Thanks a lot for your work on no language left behind.

Is there any plan to add the 54.4B Model?

Kindest regards

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Improvement

### Expected behavior

Improvement

**Comment by LysandreJik** [comment]
WDYT @ArthurZucker @younesbelkada given your work on MoEs?

**Comment by ArthurZucker** [comment]
Sure, we can add this to the to dos, @PierreColombo could you add the link to the open sourced checkpoints?

**Comment by nunonmg** [comment]
Hi all,
This would be greatly appreciated!
Thanks

**Comment by julien-c** [comment]
also cc @sheonhan re. NNLB

**Comment by gsarti** [comment]
+1, would love to see it!

**Comment by BrightXiaoHan** [comment]
+1 here.

**Comment by julien-c** [comment]
unstale?

**Comment by sgugger** [comment]
Friendly ping @ArthurZucker

**Comment by ArthurZucker** [comment]
Yes! @sheonhan mentioned wanting to take this, otherwise will gladly sprint !

**Comment by sheonhan** [comment]
Since I'm working on the Image Completion Transformer at the moment, I might be blocking the folks who want to use it asap, so you should go ahead! @ArthurZucker
