### ISSUE TITLE
trainer get_optimizer_cls_and_kwargs doesn't seem to use optim_args

### ISSUE THREAD

**Issue by zupatisc** [huggingface/transformers#21317]
Hello,
I was reading the code for the trainer and I noticed that the optimizer arguments that get passed to the trainer with the TrainingArguments don't seem to be actually applied for any optimizers aside from AnyPrecisionAdamW, is this intended?
I don't think this question really fits into any of the templates so I didn't use them.

@sgugger 
https://github.com/huggingface/transformers/blob/4e41b87e3d13af0d1d7d3d27d101e60c33c92100/src/transformers/trainer.py#L1077

**Comment by sgugger** [comment]
Yes, this is intended as the regular adam kwargs have their own training argument.

**Comment by zupatisc** [comment]
Oh okay I see, is there anything speaking against using optim_args to pass kwargs to adafactor?

**Comment by zupatisc** [comment]
Thanks for the info but if that's the case, is there a deprecation warning somewhere for this? Because I don't recall seeing one.
In any case your info closes this issue, thank you.

**Comment by sgugger** [comment]
We haven't officially deprecated it since we are waiting for someome to add support for another integration of it (like for AnyPrecisionAdam and the others).
