### ISSUE TITLE
TypeError: _forward_unimplemented() got an unexpected keyword argument 'input_ids'

### ISSUE THREAD

**Issue by QuantumStatic** [huggingface/transformers#21335]
### System Info

- `transformers` version: 4.24.0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.8
- Huggingface_hub version: 0.11.0
- PyTorch version (GPU?): 1.13.0+cu117 (True)

### Who can help?

@ArthurZucker and @younesbelkada since I am using `distilbert-base-uncased`<br>(and maybe @sgugger, since I am following this [link](https://huggingface.co/transformers/v3.2.0/custom_datasets.html)) on the hugging face website

### Information

- [x] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I am using a custom dataset to fine tune `distilbert-base-uncased`. I followed the method described [on the hugging face wesbite](https://huggingface.co/transformers/v3.2.0/custom_datasets.html) to the T. Here is my code for making the dataset.
```python
def create_hugging_face_dataset(data:dict):
    train_text, test_text, train_label, test_label = train_test_split(data['text'], data['label'], test_size=0.1, shuffle=True)
    train_text, validation_text, train_label, validation_label = train_test_split(train_text, train_label, test_size=0.1, shuffle=True)

    tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

    train_encodings = tokenizer(train_text, truncation=True, padding=True)
    test_encodings = tokenizer(test_text, truncation=True, padding=True)
    validation_encodings = tokenizer(validation_text, truncation=True, padding=True)

    class MBICDataset(torch.utils.data.Dataset):
        def __init__(self, encodings, labels):
            self.encodings = encodings
            self.labels = labels

        def __getitem__(self, idx):
            item = {key: torch.Tensor(val[idx]) for key, val in self.encodings.items()}
            item['labels'] = torch.Tensor(self.labels[idx])
            return item

        def __len__(self):
            return len(self.labels)

    train_ds = MBICDataset(train_encodings, train_label)
    test_ds = MBICDataset(test_encodings, test_label)
    validation_ds = MBICDataset(validation_encodings, validation_label)


    FINAL_DS = {"train":train_ds, "test":test_ds, "validation":validation_ds}

```

After making the dataset I try to fine-tune the model using the following code.
```python

tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

training_stuff = {
    "batch_size": 64, 
    "epochs": 4, 
    "learning_rate": 1e-5,
    "weight_decay": 0.01
    }

training_args = TrainingArguments(
            output_dir="C:/Users/uujain2/Desktop/Utkarsh/FYP/Models/DistilBert",
            per_device_train_batch_size=training_stuff["batch_size"],
            evaluation_strategy="steps",
            num_train_epochs=training_stuff["epochs"],
            fp16=True,
            save_steps=100,
            eval_steps=50,
            logging_steps=10,
            weight_decay=training_stuff["weight_decay"],
            learning_rate=training_stuff["learning_rate"],
            save_total_limit=64,
            remove_unused_columns=False,
            push_to_hub=False,
            report_to='tensorboard',
            load_best_model_at_end=True,
        )


model = DistilBertPreTrainedModel.from_pretrained(
    'distilbert-base-uncased',
    num_labels=3,
    id2label={0: 'Biased', 1: 'Non-biased', 2: 'No agreeemnt'},
    label2id={'Biased': 0, 'Non-biased': 1, 'No agreement': 2},
    )

trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=FINAL_DS['train'],
            eval_dataset=FINAL_DS['validation'],
            tokenizer=tokenizer,
        )

train_results = trainer.train()
```

However, I run into the following error.

```
Traceback (most recent call last):
  File "c:\Users\uujain2\Desktop\Utkarsh\FYP\Code\test.py", line 68, in <module>
    train_results = trainer.train()
  File "C:\Users\uujain2\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\trainer.py", line 1501, in train
    return inner_training_loop(
  File "C:\Users\uujain2\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\trainer.py", line 1749, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "C:\Users\uujain2\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\trainer.py", line 2508, in training_step
    loss = self.compute_loss(model, inputs)
  File "C:\Users\uujain2\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\trainer.py", line 2540, in compute_loss
    outputs = model(**inputs)
  File "C:\Users\uujain2\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: _forward_unimplemented() got an unexpected keyword argument 'input_ids'
```

### Expected behavior

I expect the model to start the finetuning process instead of throwing this error.

**Comment by baddhidurgarao** [comment]
[Buy Github Followers, Stars, Forks & Watchers](https://baddhi.shop/product/buy-github-followers/) from Baddhi Shop

**Comment by sgugger** [comment]
`DistilBertPreTrainedModel` is an abstract class and shouldn't be used directly. Maybe you wanted to use `DistilBertModel` or `DistilBertForPretraining`?

**Comment by QuantumStatic** [comment]
Thank you for your quick response. It was my silly mistake to use an abstract class for pre-training. I was able to import `DistilBertModel`, however the import for `DistilBertForPretraining` failed, but that's alright.

However when I try to run the model now I get the following error.
```
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`labels` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```

I have followed the webpage titled [Fine-tuning with custom datasets](https://huggingface.co/transformers/v3.4.0/custom_datasets.html). My function that creates the initial lists with texts and labels is below. The data is formatted very similarly to the webpage:
```python
def create_MBIC_data_dict() -> dict[str, str]:
    data_dict = {'text': [], 'label':[]}
    with open(f"{DATA_FOLDER_PATH}/final_labels_MBIC_new.csv") as csv_file:
        csv_reader = csv.reader(csv_file)
        line_count = 0
        for row in csv_reader:
            if line_count != 0:
                data_dict['text'].append(row[0])
                label_val = -1
                match row[7]:
                    case "Biased":
                        label_val = 1
                    case "Non-biased":
                        label_val = 0
                    case "No agreement":
                        label_val = 2
                data_dict['label'].append(label_val)
            line_count += 1

    return data_dict
```
Afterwards the `create_hugging_face_dataset` function executes which creates the dataset.

**Comment by shayongithub** [comment]
I'm having the same issue while using **AutoModel** for the 'vinai/phobert-base-v2'_ model, I have change to **AutoModelForSequenceClassification** and **RobertaForSequenceClassification** but it still doesn't resolve the problems. 

This is my loaded model:

`MultiTaskModel(
  (encoder): RobertaForSequenceClassification(
    (roberta): RobertaModel(
      (embeddings): RobertaEmbeddings(
        (word_embeddings): Embedding(64001, 768, padding_idx=1)
        (position_embeddings): Embedding(258, 768, padding_idx=1)
        (token_type_embeddings): Embedding(1, 768)
        (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (encoder): RobertaEncoder(
        (layer): ModuleList(
          (0-11): 12 x RobertaLayer(
            (attention): RobertaAttention(
              (self): RobertaSelfAttention(
                (query): Linear(in_features=768, out_features=768, bias=True)
                (key): Linear(in_features=768, out_features=768, bias=True)
                (value): Linear(in_features=768, out_features=768, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (output): RobertaSelfOutput(
                (dense): Linear(in_features=768, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (intermediate): RobertaIntermediate(
              (dense): Linear(in_features=768, out_features=3072, bias=True)
              (intermediate_act_fn): GELUActivation()
            )
            (output): RobertaOutput(
              (dense): Linear(in_features=3072, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
        )
      )
    )
    (classifier): RobertaClassificationHead(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (out_proj): Linear(in_features=768, out_features=2, bias=True)
    )
  )
  (output_heads): ModuleDict(
    (0): SequenceClassificationHead(
      (dropout): Dropout(p=0.1, inplace=False)
      (classifier): Linear(in_features=768, out_features=2, bias=True)
    )
    (1): SequenceClassificationHead(
      (dropout): Dropout(p=0.1, inplace=False)
      (classifier): Linear(in_features=768, out_features=3, bias=True)
    )
  )
)`

I extend the class `nn.Module` from pytorch to create **MultiTaskModel** class

`class MultiTaskModel(nn.Module):
    def __init__(self, encoder_name_or_path, tasks: List):
        super().__init__()

        self.encoder = RobertaForSequenceClassification.from_pretrained(encoder_name_or_path)

        self.output_heads = nn.ModuleDict()
        for task in tasks:
            decoder = self._create_output_head(self.encoder.config.hidden_size, task)
            # ModuleDict requires keys to be strings
            self.output_heads[str(task.task_id)] = decoder

    @staticmethod
    def _create_output_head(encoder_hidden_size: int, task):
        if task.task_type == "seq_classification":
            return SequenceClassificationHead(encoder_hidden_size, task.num_labels)
        else:
            raise NotImplementedError()`

**Comment by FengRui1998** [comment]
I also had a similar error. When I wanted to use TRL to fine-tune qwen2.5-omni, I used **Qwen2_5OmniForConditionalGeneration, Qwen2_5OmniProcessor.**

`Traceback (most recent call last):
  File "/public/home/feng_rui/code/ASTAR_Project/fine_tune.py", line 267, in <module>
    trainer.train()
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/transformers/trainer.py", line 2240, in train
    return inner_training_loop(
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/transformers/trainer.py", line 2555, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 733, in training_step
    return super().training_step(*args, **kwargs)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/transformers/trainer.py", line 3745, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 687, in compute_loss
    (loss, outputs) = super().compute_loss(
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/transformers/trainer.py", line 3810, in compute_loss
    outputs = model(**inputs)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/accelerate/utils/operations.py", line 818, in forward
    return model_forward(*args, **kwargs)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/accelerate/utils/operations.py", line 806, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/peft/peft_model.py", line 1757, in forward
    return self.base_model(
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/public/home/feng_rui/miniconda3/envs/TRL/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 193, in forward
    return self.model.forward(*args, **kwargs)
TypeError: _forward_unimplemented() got an unexpected keyword argument 'input_ids'`

How can I fix this?

**Comment by Rocketknight1** [comment]
Hi @FengRui1998, these questions are a good fit for the [community support space](https://huggingface.co/spaces/transformers-community/support)! If you post there one of the Hugging Face engineers or community members should be able to help
