### ISSUE TITLE
multi gpu training.

### ISSUE THREAD

**Issue by namanpundir** [huggingface/transformers#21407]
### Feature request

What we can do if using run_clm.py to train with multi gpu's?

### Motivation

multi gpu training for faster training.

### Your contribution

can we add this in the script?
model = nn.DataParallel(model,device_ids=[i for i in range(torch.cuda.device_count())])

**Comment by sgugger** [comment]
If you have multiple GPUs it will run on multiple GPUs.

**Comment by namanpundir** [comment]
Thanks @sgugger

**Comment by namanpundir** [comment]
![image](https://user-images.githubusercontent.com/41872440/216443341-b599d365-463e-48fa-9ba1-f3ee36dcdf6d.png)

**Comment by namanpundir** [comment]
Hi @sgugger 
I have 4 a100 (40x4gb)
Getting memory error seems it is taking one gpu only.

**Comment by namanpundir** [comment]
![image](https://user-images.githubusercontent.com/41872440/216619913-99568f8c-8a82-42ab-ae7a-dd56846dd395.png)
I have 8 gpu's in this machine.
![image](https://user-images.githubusercontent.com/41872440/216619996-7af22496-7fb8-4b6d-90f2-3606846b3cdc.png)
I think its not taking all 8 gpu's. Already tried changing batch_sizes and with multiple of 8
