### ISSUE TITLE
layoutlmv3-base-chinese convert onnx

### ISSUE THREAD

**Issue by githublsk** [huggingface/transformers#21415]
### Feature request

When use layoutlmv3-base-chinese converting to onnx, the comand line is as follows: python3.7 -m transformers.onnx --model=model path --feature token-classification, we find it lacks of vocab_file and merges_file, can you support us above two files, thank you very much, if not, can you give us some method to solve above problem?

### Motivation

No.

### Your contribution

No.

**Comment by NielsRogge** [comment]
ONNX will only convert the model, not the tokenizer.

ONNX conversion is now moved to the Optimum package, no need to pass --feature anymore as it will infer that automatically based on the checkpoint. Docs here: https://huggingface.co/docs/optimum/exporters/onnx/usage_guides/export_a_model.

**Comment by NielsRogge** [comment]
Closing this as the issue seems resolved.
