### ISSUE TITLE
master branch examples/run_squad.py: missing --predict_file argparse argument

### ISSUE THREAD

**Issue by mfeblowitz** [huggingface/transformers#2142]
## 🐛 Bug

Model I am using: albert

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [X] the official example scripts: (give details)
examples/run_squad/py: --predict_file not recognized
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: run_squad
* [ ] my own task or dataset: (give details)

## To Reproduce

Try running an eval only run with run_squad.py

1. provide all of the requisite arguments to run_squad.py
2. observe error `run_squad.py: error: unrecognized arguments: --predict_file`
3.

## Expected behavior

A correct run
## Environment

* OS:
* Python version: 3.7.5
* PyTorch version: n/a
* PyTorch Transformers version (or branch): master
* Using GPU ? yes
* Distributed of parallel setup ?no
* Any other relevant information:

Quick inspection of examples/run_squad.py reveals missing declaration, present in, e.g., 1.2.0

**Comment by TheEdoardo93** [comment]
In order to use the evaluation mode, you have to pass from script the `do_eval` parameter (in addition to the "classical" input parameters for evaluation).

> ##  Bug
> Model I am using: albert
> 
> Language I am using the model on (English, Chinese....): English
> 
> The problem arise when using:
> 
> * [x]  the official example scripts: (give details)
>   examples/run_squad/py: --predict_file not recognized
> * [ ]  my own modified scripts: (give details)
> 
> The tasks I am working on is:
> 
> * [x]  an official GLUE/SQUaD task: run_squad
> * [ ]  my own task or dataset: (give details)
> 
> ## To Reproduce
> Try running an eval only run with run_squad.py
> Steps to reproduce the behavior:
> 
> 1. provide all of the requisite arguments to run_squad.py
> 2. observe error `run_squad.py: error: unrecognized arguments: --predict_file`
> 
> ## Expected behavior
> A correct run
> 
> ## Environment
> * OS:
> * Python version: 3.7.5
> * PyTorch version: n/a
> * PyTorch Transformers version (or branch): master
> * Using GPU ? yes
> * Distributed of parallel setup ?no
> * Any other relevant information:
> 
> Quick inspection of examples/run_squad.py reveals missing declaration, present in, e.g., 1.2.0
> 
> ## Additional context

**Comment by LysandreJik** [comment]
Indeed, there was a big refactor of the SQuAD script recently which removed these arguments in favor of `data_dir`, which contains the files. I'll add the possibility to either use `predict_file` and `train_file` instead of `data_dir` later today.
