### ISSUE TITLE
BertTokenizer cannot properly tokenize words with dashes

### ISSUE THREAD

**Issue by poteminr** [huggingface/transformers#21439]
### System Info

- `transformers` version: 4.26.0
- Platform: Linux-5.10.147+-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.12.0
- PyTorch version (GPU?): 1.13.1+cu116 (False)
- Tensorflow version (GPU?): 2.9.2 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

The `BertTokenizer` doesn't tokenize words with dashes correctly. I tried to use tokenizer for **Italian** and **English** languages and got unexpected results. This issue similar to https://github.com/huggingface/transformers/issues/5136. 

```python3
from transformers import AutoTokenizer, BertTokenizer
model1 = 'cointegrated/rubert-tiny2'
model2 = 'Babelscape/wikineural-multilingual-ner' 
tokenizer = BertTokenizer.from_pretrained(model1, model_max_length=50)

>>> tokenizer.tokenize('so-called')
['so', '-', 'called']

>> tokenizer.tokenize('era il figlio di ghazi-ud-din haidar.')
['era', 'il', 'fi', '##gli', '##o', 'di', 'gh', '##azi', '-', 'ud', '-', 'din', 'hai', '##dar', '.']
```

### Expected behavior

Expected something like that:
```python3
>>> tokenizer.tokenize('so-called')
['so', '##-', '##called']

>> tokenizer.tokenize('era il figlio di ghazi-ud-din haidar.')
['era', 'il', 'fi', '##gli', '##o', 'di', 'gh', '##azi', '##-', '##ud', '##-', '##din', 'hai', '##dar', '.']
```

**Comment by sgugger** [comment]
I am not sure what you would like us to do about that. If we change the tokenizer, the model will get inputs different from its training and thus won't perform as well. You should use a different model with a tokenizer that suits your needs :-)

**Comment by NielsRogge** [comment]
This is not an issue on our side, it's just the way the WordPiece algorithm works, given the corpus that the BERT authors trained on.

Check out our course for more info on tokenization algorithms: https://huggingface.co/course/chapter6/1?fw=pt
