### ISSUE TITLE
the docs pretrained models is missing

### ISSUE THREAD

**Issue by PiotrCzapla** [huggingface/transformers#2145]
Hi, 
your docs have the table with pretrained models missing, probably some formatting error, as the source code has the table
<img width="1280" alt="Screenshot 2019-12-11 at 17 31 01" src="https://user-images.githubusercontent.com/340180/70640463-4174a380-1c3c-11ea-9c6e-ca343ef46332.png">
https://huggingface.co/transformers/pretrained_models.html
Cheers,
Piotr

**Comment by stefan-it** [comment]
Should be working now :)

**Comment by LysandreJik** [comment]
Thanks @PiotrCzapla for raising the issue, @stefan-it fixed it earlier today!
