### ISSUE TITLE
Datasets performance :( 

### ISSUE THREAD

**Issue by webshared** [huggingface/transformers#21466]
I am using https://huggingface.co/docs/transformers/model_doc/time_series_transformer as an example to setup time series transformers for my use case. 

I have modified the training script to just traverse all batches and dump a summary - essentially max and min value of first & last time feature elements for each of 366 static categories. 

40 epochs, 100 batches per epoch, 256 train sequences per batch
= 1_024_000 training sequences in total

**Elapsed time: 452.257402 seconds**

Iterating over 1M elements with really simple logic took over 7 minutes on M2 macbook :( 

I am new to python - is it kinda expected?

**Comment by sgugger** [comment]
Hi there. Please use the [forums](https://discuss.huggingface.co/) for questions like this as we keep issues for bugs and feature requests only. Also make sure to include the code you are running or no one will be able to help.
