### ISSUE TITLE
ConvBERT self-attention throws errors whenever head_ratio is not 2

### ISSUE THREAD

**Issue by cmunna0052** [huggingface/transformers#21523]
### System Info

Here is what the command says, but multiple responses are incorrect

- `transformers` version: 4.25.1
- Platform: macOS-10.16-x86_64-i386-64bit  (Really 13.1 M1)
- Python version: 3.9.13
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed (It is installed)
- JaxLib version: not installed (It is installed)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@sgugger @arthr

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
import jax
from transformers import ConvBertLayer, ConvBertConfig
from transformers.models.convbert.modeling_convbert import ConvBertSelfAttention
test_config = ConvBertConfig()
test_config.attention_probs_dropout_prob = 0.0
test_config.hidden_dropout_prob = 0.0
test_config.head_ratio = 4

torch_conv_attn = ConvBertSelfAttention(test_config)
input_embed = torch.tensor(np.array(jax.random.normal(jax.random.PRNGKey(42),(3,10,test_config.embedding_size))))
torch_conv_attn(input_embed)

#RuntimeError: shape '[3, 10, 768]' is invalid for input of size 11520
```

### Expected behavior

I am testing out ConvBertSelfAttention for comparisons to a similar implementation in JAX.  Head_ratio is allowed to be any integer that divides into num_heads and hidden_size, but I run into errors whenever it is set to anything other than 2. 

I believe the problem stems from the fact that the embedding size is reduced by a factor of head_ratio, but then only multiplied by a factor of 2 in the final concatenation step.  However, this seems to be the same behavior as in the original code https://github.com/yitu-opensource/ConvBert/blob/master/model/modeling.py, so I am not sure how ConvBERT is supposed to handle head_ratio != 2 in the first place.

**Comment by sgugger** [comment]
cc @ArthurZucker

**Comment by ArthurZucker** [comment]
Thanks for reporting. Opening a PR to fix it!
