### ISSUE TITLE
Cannot import name 'BioGptModel' from 'transformers'

### ISSUE THREAD

**Issue by sky1ove** [huggingface/transformers#21541]
### System Info

https://huggingface.co/docs/transformers/model_doc/biogpt

Cannot import name 'BioGptModel' from 'transformers'

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import BioGptModel, BioGptConfig

### Expected behavior

..

**Comment by sgugger** [comment]
Please follow the issue template. You likely need to upgrade your Transformers version (`pip install transformers --upgrade`) but we can't know without more information.
