### ISSUE TITLE
AlBERT UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by ivankott** [huggingface/transformers#2154]
## ❓ Questions & Help

![image](https://user-images.githubusercontent.com/36267779/70731538-8584a880-1d0f-11ea-8516-7895c3a50c27.png)
![image](https://user-images.githubusercontent.com/36267779/70731555-8d444d00-1d0f-11ea-84a5-0df7b00ff820.png)

Hi! There is some problem while downloading any of the pre-trained AlBERT models, however, there weren't any problems a few days ago. Could you please tell me where can I download the AlBERT TensorFlow checkpoints (`albert_model.ckpt`) for running `convert_albert_original_tf_checkpoint_to_pytorch.py` script? Unfortunately, I wasn't able to find any for resolving this as in [2110](https://github.com/huggingface/transformers/issues/2110). 
I'd really appreciate any help in resolving the issue. 
Thanks a bunch in advance!

tensorflow | 2.0.0 | 
torch | 1.3.1 | 
transformers | 2.2.1 | 
python | 3.7 |

**Comment by LysandreJik** [comment]
Hello! Could you please tell me which model you are trying to download? I've just tried the following command and it succeeded without any issues:
```py
AlbertForQuestionAnswering.from_pretrained("albert-base-v2", force_download=True)
```

I put the `force_download` flag to True to make sure I was downloading the files from the S3. Is there any way you could try this on your side?

**Comment by TheEdoardo93** [comment]
In my environment, I'm not able to reproduce your bug, so I can download any AlBERT model I want. I've tried the same code line that in your case generates the error, e.g.
```
> from transformers import AlbertForQuestionAnswering
> model = AlbertForQuestionAnswering.from_pretrained(X)
``` 
where X is one of ['albert-base-v1', 'albert-large-v1', 'albert-xlarge-v1', 'albert-xxlarge-v1', 

You can specify `force_download=True` when you're loading a specific version of AlBERT model, e.g.
```
> from transformers import AlbertForQuestionAnswering
> model = AlbertForQuestionAnswering.from_pretrained('albert-base-v1', force_download=True)
```

N.B: at the moment, there is a known bug when using v2 AlBERT models, as said when you import this version in Transformers:
> There is currently an upstream reproducibility issue with ALBERT v2 models. Please see https://github.com/google-research/google-research/issues/119 for more information.

> ##  Questions & Help
> ![image](https://user-images.githubusercontent.com/36267779/70721247-e905da80-1cfd-11ea-9863-90dcabf6bf58.png)
> ![image](https://user-images.githubusercontent.com/36267779/70730858-65a0b500-1d0e-11ea-811c-d10ba7c1c356.png)
> 
> Hi! There is some problem while downloading any of the pre-trained AlBERT models, however, there weren't any problems a few days ago. Could you please tell me where can I download the AlBERT TensorFlow checkpoints (albert_model.ckpt) for running convert_albert_original_tf_checkpoint_to_pytorch.py script? Unfortunately, I wasn't able to find any for resolving this as in #2110.
> I'd really appreciate any help in resolving the issue. Thanks a bunch in advance!

**Comment by ivankott** [comment]
I've tried with all of the models with and without `force_download=True`
![image](https://user-images.githubusercontent.com/36267779/70733140-63405a00-1d12-11ea-86a1-3a2c20d3ce0f.png)
unfortunately have this now, however, it was OK yesterday

**Comment by LysandreJik** [comment]
Do you get the same errors with other models, like BERT?

**Comment by ivankott** [comment]
I've just tried again using completely new basic script and it worked, don't know what is that. I just thought it's the same as in another issue.  
But anyway, thanks a lot, guys!

**Comment by LysandreJik** [comment]
Glad you could fix it.
