### ISSUE TITLE
End-Task Distillation with DistilBERT

### ISSUE THREAD

**Issue by shreydesai** [huggingface/transformers#2156]
## ❓ Questions & Help

The DistilBERT paper notes the IMDB and SQuAD results were obtained "with a second step of distillation during fine-tuning". What does this involve exactly and how can it be performed with the DistilBERT model in this repo?

**Comment by VictorSanh** [comment]
Hello @shreydesai,
You should have a look at [run_squad_w_distillation.py](https://github.com/huggingface/transformers/blob/master/examples/distillation/run_squad_w_distillation.py) which is the script used in the experiment you are mentioning.
Victor
