### ISSUE TITLE
Dead link in Documentation 📚

### ISSUE THREAD

**Issue by danadascalescu00** [huggingface/transformers#21596]
Dead link found on: https://huggingface.co/docs/transformers/tasks/summarization#inference ("_For more details about the different text generation strategies and parameters for controlling generation, check out the_ [Text Generation API](https://huggingface.co/docs/transformers/tasks/main_classes/text_generation)") . The URL should lead to the Text Generation documentation, which can actually be found at: [https://huggingface.co/docs/transformers/main_classes/text_generation](https://huggingface.co/docs/transformers/main_classes/text_generation).

**Comment by amyeroberts** [comment]
Hi @danadascalescu00 - thanks for raising this issue! I'm closing it now as it's resolved in #22274
