### ISSUE TITLE
Seq2SeqTrainer with predict_with_generate prints config every step

### ISSUE THREAD

**Issue by eyalmazuz** [huggingface/transformers#21604]
### System Info

Transformers version 4.26.1
Python version 3.8.12

### Who can help?

@sgugger

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I'm working on a Hebrew-Arabic machine translation task by training the T5 model from scratch

The issue occurs with the Translation code from the tutorial in the huggingface's course:
https://huggingface.co/course/chapter7/4?fw=pt

I have a slightly modified version of it (extra metrics and a slightly different dataset)

here's a link to my code:
https://pastebin.com/LaCAPsCF

``python3 train_model.py --dataset_path ./data/HF_HE_AR_Dataset.json --tokenizer_path ./T5Tokenizer/ --max_length=128 --batch_size=16 --logging_steps 100 --save_steps 100 --model t5-base``

this is was the command that I ran but it doesn't matter much since the problem is with ``predict_with_generate=True,`` in the Seq2SeqTrainingArguments. If it's false the problem do not occurs

This is what happens when it reaches the evaluation loop

![image](https://user-images.githubusercontent.com/34383384/218470931-e9b694ea-7dc7-464e-8a3a-37bf28c3898a.png)

### Expected behavior

Only the TQDM bar is printed

**Comment by sgugger** [comment]
cc @gante

**Comment by gante** [comment]
Hey @eyalmazuz 👋 There is a chance that the issue is sorted already (see [here](https://github.com/huggingface/transformers/pull/21385)). To try it out, install `transformers` from `main` -- let me know if it works!

`pip install --upgrade git+https://github.com/huggingface/transformers.git`

**Comment by eyalmazuz** [comment]
Hi @gante there's no extra printing when using transformers-main I'll close the issue
thank you for your help
