### ISSUE TITLE
Adding model type to config.json

### ISSUE THREAD

**Issue by perdix** [huggingface/transformers#2161]
## Feature
Add `model_type` to the *config.json* to define the model_type and make it independent from the name

## Motivation
Currently, the model type is automatically discovered from the name. So if it is a Bert model, the autoloader is choosing the right methods if the name contains `bert`. If not, an error would be thrown.
This is somehow cumbersome and error prone and it restricts the naming of the models. Why not just add this info as a attribute in the config.json? 
Other suggestions are welcome!

## Info
I would happily start working at a PR if others agree as well.

**Comment by perdix** [comment]
Is now solved by this [PR](https://github.com/huggingface/transformers/pull/2494)
Thanks a lot!

**Comment by julien-c** [comment]
Yes, thanks for the contribution @perdix!
