### ISSUE TITLE
Donut base-sized model, pre-trained only for a new language tutorial

### ISSUE THREAD

**Issue by Wyzix33** [huggingface/transformers#21628]
### Feature request

I'm trying to generate a new pre-training for Donut model using Romanian language documents.

I have about 100k scanned documents and want to create a pre-training for Romanian language to be able to fine-tune different types of documents for parsing and classification on it.

Can anyone share or create a tutorial on how to generate new Donut pre-train model from scratch?

Thanks

### Motivation

Donut only have a a few language models

### Your contribution

I can share the pretrained model i create for Romanian language

**Comment by sgugger** [comment]
Those questions are most suited to the [forums](https://discuss.huggingface.co/) where the whole community will be able to help. We keep issues for bugs and feature requests only.

**Comment by Wyzix33** [comment]
OK, will do that! 
Thanks
