### ISSUE TITLE
Add SwinIR for Image Super Resolution

### ISSUE THREAD

**Issue by asrimanth** [huggingface/transformers#21633]
### Model description

SwinIR: Image Restoration Using Swin Transformer

- This paper presents an Image Super Resolution / Image Restoration model inspired by the SwinTransformer architecture.
- It demonstrates superior performance on various vision tasks including classical/lightweight Image Super Resolution, Image Denoising, and JPEG compression artifact reduction

This issue is primarily focused on the Image Super Resolution model only. I would love to see this model on HuggingFace.

## Contribution: I would love to work on this!

I am new to HuggingFace and open-source in general. I am open to comments/suggestions/feedback.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Paper Link: https://arxiv.org/pdf/2108.10257v1.pdf
Implementation Link: https://github.com/JingyunLiang/SwinIR
Weights Link: https://github.com/JingyunLiang/SwinIR/releases/tag/v0.0

**Comment by NielsRogge** [comment]
Just wanna note that Swin2SR is already integrated, which improves upon SwinIR: https://huggingface.co/docs/transformers/main/model_doc/swin2sr

**Comment by asrimanth** [comment]
Ohh okay, thank you, I'll close this issue then.

**Comment by aleksmirosh** [comment]
Hi @NielsRogge thanks for adding this model to HF.
Do you have in plans to add training process too?
