### ISSUE TITLE
PreTrainedEncoderDecoder on tensorflow

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [huggingface/transformers#2163]
## 🚀 Feature

Hi, would it be possible to create a tensorflow version of `PreTrainedEncoderDecoder`?
## Motivation

The main motivation is that I would like to use `PreTrainedEncoderDecoder` in TensorFlow. Yeah, I got it, PyTorch is better and I totally agree but unfortunately, I have to use TensorFlow.

## Additional context

Looking at the code it does not seem too hard to create a `TFPreTrainedEncoderDecoder`

Thank you guys

**Comment by sshleifer** [comment]
We are still settling on the proper API for the pytorch version, so it will probably be awhile (months) before we make a tensorflow version. Feel free to take a stab at it, of course!

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you for the reply :) I guess I will use PyTorch then.
On 11 Feb 2020, 16:28 +0100, Sam Shleifer <notifications@github.com>, wrote:

We are still settling on the proper API for the pytorch version, so it will probably be awhile (months) before we make a tensorflow version. Feel free to take a stab at it, of course!
