### ISSUE TITLE
load_module will be removed in Python 3.12

### ISSUE THREAD

**Issue by Rocketknight1** [huggingface/transformers#21645]
Several of our scripts call `spec.loader.load_module()`. Although this mostly affects standalone utils scripts, it's also called at the top level of `processing_utils.py`, which will be executed by all `Processor` classes.

`load_module()` has been deprecated for a while and will be fully deleted in Python 3.12, which is entering beta soon. We need to replace this code or the library will not be usable in Py3.12.

I can investigate and try to find a suitable replacement when I have time, but if anyone is more familiar with that code and can think of an obvious replacement that achieves the same goal, let me know!

cc @sgugger

**Comment by sgugger** [comment]
Thanks for pointing this out! Will have a look.
