### ISSUE TITLE
Confusing documentation in T5

### ISSUE THREAD

**Issue by seanmor5** [huggingface/transformers#21641]
### System Info

latest

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Not sure if this is a bug exactly, but the way the documentation reads for T5 doesn't seem correct in the context of Flan-T5. Specifically, the configuration parameter `d_kv` it states: 

```
d_kv (int, optional, defaults to 64) — Size of the key, query, value projections per attention head. d_kv has to be equal to d_model // num_heads.
```

However if you look at `flan-t5-small`, d_kv is 64 while the hidden size is 512 and the number of heads is 6, which obviously doesn't hold up with the statement in the docs.

Is the T5 behavior correct as is? Are the docs just wrong?

### Expected behavior

Looking at the implementation of T5 it seems generic w.r.t to `d_kv`, `num_heads`, and `d_model` and `inner_dim` is actually the size of the k/v/q projection

**Comment by ArthurZucker** [comment]
The T5 behaviour is correct, and as pointed out the doc is probably not! I'll open a PR to fix this 👍🏻 thanks
