### ISSUE TITLE
Converting Megatron_T5 to HF_T5

### ISSUE THREAD

**Issue by WenzhengZhang** [huggingface/transformers#21650]
Currently both [Megatron_BERT conversion](https://github.com/huggingface/transformers/blob/main/src/transformers/models/megatron_bert/convert_megatron_bert_checkpoint.py) and [Megatron_GPT conversion](https://github.com/huggingface/transformers/blob/main/src/transformers/models/megatron_gpt2/convert_megatron_gpt2_checkpoint.py) are supported. Do you have any plan to support T5 models conversion?

**Comment by lierik** [comment]
Hello guys,
I saw you closed this issue.
Did you find any way to convert megatron t5 <-> hf T5?

**Comment by idotan286** [comment]
I would be interested too.
Did you find any solution?

**Comment by bugface** [comment]
any potential solutions?

**Comment by ArthurZucker** [comment]
Don't think this is supported yet, but feel free to open a pr if you want! 🤗
