### ISSUE TITLE
Initialize OPT 175B model for a long time

### ISSUE THREAD

**Issue by larry-fuy** [huggingface/transformers#21687]
### System Info

Recently I am trying to train OPT 175B (facebook/opt-175b) and found my code needs almost 10 hours to initialize the model weights before starting training. Actually my code is pretty simple
```
...
config = PretrainedConfig.from_json_file('175b.json')
model = OPTForCausalLM(config)
...
```
Is there any issue of my code or I have to configure something to accelerate the initialization? @ArthurZucker , @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I already posted the main part to cause the problem in problem description.

### Expected behavior

I think the initialization computation should not be so long.

**Comment by sgugger** [comment]
The line takes a very long time because there are 176 billions parameters to initialize. The initialization is also performed several times, which is a bug we recently fixed. If you use the latest main you might see it takes a bit less time.
