### ISSUE TITLE
RAG: Which version of pytorch-forecasting to use for fintetune-rag.sh? 

### ISSUE THREAD

**Issue by Mrs-Hudson** [huggingface/transformers#21692]
### System Info

- `transformers` version: 4.24.0
- Platform: Linux-3.10.0-1160.83.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.16
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.11.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker  @younesbelkada 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

The latest version of  pytorch-forecasting is not comptabible with the RAG module of transformers. I was able to successfuly create my own knowledge dataset but the finetune-rag.py step fails.  I also looked at the version history and experimented with 1.6.4 throws an error

I was wondering if there's a known version of pytorch_lightning that works with RAG.

Steps to Reproduce:
 1. From transformers root, run a shell script with
 `python examples/research_projects/rag/finetune_rag.py --data_dir /home/rparik/linkedInEmpForKnowledgeClean/data.csv \
    --output_dir ./finetune_rag_output/ \
    --model_name_or_path facebook/rag-token-nq \
    --model_type rag_sequence \
    --fp16 \
    --gpus 1 \
    --index_name custom \
    --passages_path /home/rparik/projects/rag/transformers/linkKnowledgeBase/my_knowledge_dataset \
    --index_path /home/rparik/projects/rag/transformers/linkKnowledgeBase/my_knowledge_dataset_hnsw_index.faiss \
`
Error:

 ```
 File "examples/research_projects/rag/finetune_rag.py", line 17, in <module>
    from pytorch_lightning.plugins.training_type import DDPStrategy
ModuleNotFoundError: No module named 'pytorch_lightning.plugins.training_type'
```

### Expected behavior

Script runs without errors

**Comment by Mrs-Hudson** [comment]
Looks like 1.6.0 worked

**Comment by ArthurZucker** [comment]
The requirement file states `pytorch-lightning >= 1.5.10`. Were you using an older version or a newer version? 
(shoud I pin version 1.6.0 as the max version?)

**Comment by Mrs-Hudson** [comment]
I can confirm that 1.9.1 didn't work, neither did 1.6.4. haven't tried
1.6.1-1.6.3
