### ISSUE TITLE
Transformers version 4.27.0.dev0

### ISSUE THREAD

**Issue by bg-uni** [huggingface/transformers#21712]
### System Info

Hello,
I have a question.

I would like to upgrade Transformers to 4.27 because I get the following error when I run run_mlm.py.
The latest is 4.26.1 in pip install.

--------------------------------------------------------------------------
python  run_mlm.py --model_type bert
Traceback (most recent call last):
  File "C:\Users\d_test_user\Documents\test\transformers-main\examples\pytorch\language-modeling\run_mlm.py", line 56, in <module>
    check_min_version("4.27.0.dev0")
  File "C:\Users\d_test_user\Documents\transformer_example\.env\lib\site-packages\transformers\utils\__init__.py", line 208, in check_min_version
    raise ImportError(
ImportError: This example requires a source install from HuggingFace Transformers (see `https://huggingface.co/transformers/installation.html#installing-from-source`), but the version found is 4.26.1.
Check out https://huggingface.co/transformers/examples.html for the examples corresponding to other versions of HuggingFace Transformers.
--------------------------------------------------------------------------

Thanks for your help!

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python  run_mlm.py

Traceback (most recent call last):
  File "C:\Users\d_test_user\Documents\test\transformers-main\examples\pytorch\language-modeling\run_mlm.py", line 56, in <module>
    check_min_version("4.27.0.dev0")
  File "C:\Users\d_test_user\Documents\transformer_example\.env\lib\site-packages\transformers\utils\__init__.py", line 208, in check_min_version
    raise ImportError(
ImportError: This example requires a source install from HuggingFace Transformers (see `https://huggingface.co/transformers/installation.html#installing-from-source`), but the version found is 4.26.1.
Check out https://huggingface.co/transformers/examples.html for the examples corresponding to other versions of HuggingFace Transformers.

### Expected behavior

I want to create a bert model using example.

**Comment by bg-uni** [comment]
This problem has been resolved.

**Comment by kksj216** [comment]
Can you share how to solve this issue? 
Thank you in advance.

**Comment by tanmey007** [comment]
Struck on same issue, can you share how did you resolved that issue @bg-uni ?
Thanks in advance

**Comment by tanmey007** [comment]
@sanchit-gandhi can you help here?

**Comment by tanmey007** [comment]
Hi @kksj216,
Use the following steps
git clone https://github.com/huggingface/transformers.git
cd transformers
pip install -e .

**Comment by tanmey007** [comment]
> @tanmey007 Thanks for your help! But that steps did not work for me... Still had the same error. 🥲

I am using jupyter notebook, and used the following steps,
!git clone https://github.com/huggingface/transformers.git
import os
os.chdir('transformers')
!pip install -e .

**Comment by sanchit-gandhi** [comment]
You can either install directly from the `main` branch: https://huggingface.co/docs/transformers/installation#install-from-source

Or through an editable install: https://huggingface.co/docs/transformers/installation#editable-install

**Comment by amyeroberts** [comment]
@kksj216  If it is not working in the terminal, it's likely the environment has not been updated and the correct version of transformers is not being used. 

To check which version of transformers is being run in the environment, you can run in the terminal: 
`python -c "import transformers; print(transformers.__version__)"`

Or to see more information about the library, where it's installed etc:
`pip show transformers`

If you wish to run from the development branch, then the instructions @sanchit-gandhi or @tanmey007 posted should be followed. If this doesn't work, then I suggest uninstalling `transformers` from your environment and then try installing again.
