### ISSUE TITLE
Small run_squad nit: eliminate trailing "_" in "best_predictions_.json" when no prefix

### ISSUE THREAD

**Issue by mfeblowitz** [huggingface/transformers#2171]
## 🐛 Bug

Prior convention for tf-based run_squad is to output best predictions in an nbest_predictions.json file. Now with the new convention of including a "prefix" in the generation of potentially many nbest files, in cases where there's not prefix, the name becomes nbest_predictions_.json (nothing after the "_"). Might be more backward compatible to include the rightmost "_" only when there's a prefix after it.

The same thing applies to predictions and null_odds, ...

Model I am using (Bert, XLNet....): albert

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [X] the official example scripts: run_squad.py
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: SQuAD2
* [ ] my own task or dataset: (give details)

## To Reproduce

1. look at output of a successful run of run_squad.py 

## Environment

* OS:
* Python version:
* PyTorch version:
* PyTorch Transformers version (or branch): v2.1.1, from source
* Using GPU ?
* Distributed of parallel setup ?
* Any other relevant information:

**Comment by julien-c** [comment]
As it's only a cosmetic change and for the sake of not breaking backward compat over cosmetic issues I'm reluctant to change this.
