### ISSUE TITLE
Make `CLIPImageProcessor` compatible with `subfolder` kwarg 

### ISSUE THREAD

**Issue by Abhinay1997** [huggingface/transformers#21715]
### Feature request

The CLIPImageProcessor can't be initialized currently using:

```
CLIPImageProcessor.from_pretrained('kakaobrain/karlo-v1-alpha-image-variations', subfolder = 'feature_extractor', return_unused_kwargs=True)
```
as the `ImageProcessorMixin.get_image_processor_dict` method doesn't take in a `subfolder` kwarg to pass into `cached_file`

Link:
https://github.com/huggingface/transformers/blob/main/src/transformers/image_processing_utils.py#L214

Can we add the subfolder kwarg to be able to initialize a CLIPImageProcessor this way ?

### Motivation

Currently, other modules like the `CLIPTextModelWithProjection` are able to load from subfolders. It'd be nice to have CLIPImageProcessor also behave the same way.

### Your contribution

I'd be happy to open a PR on this. I was able to get it to work by passing `subfolder` directly to `cached_file` but need to verify a few more things.

**Comment by sgugger** [comment]
Thanks for flagging! We'll be happy to have a look at a PR!

**Comment by Abhinay1997** [comment]
@sgugger, I created the PR. #21725

**Comment by Abhinay1997** [comment]
Closing the issue as PR is merged and issue is resolved. :)
