### ISSUE TITLE
Error with shape-assertion regarding head_masks in mbart_modeling file

### ISSUE THREAD

**Issue by josh-oo** [huggingface/transformers#21728]
### System Info

file: https://github.com/huggingface/transformers/blob/v4.26.1/src/transformers/models/mbart/modeling_mbart.py
commit-hash: fd5cdaeea6eafac32e9d967327bfa3dc0e0d962d

### Who can help?

@ArthurZucker @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Call the forward method of MBartModel with:
- head_mask=None,
- decoder_head_mask=None,
 and 
- cross_attn_mask=torch.ones(mismatching_layer_size, number_of_heads)

### Expected behavior

**Expected Output:** The cross_attn_head_mask should be specified for X layers, but it is for Y.
**Actual Output:** 'NoneType' object has no attribute 'size'

**Potential fix:** The head_mask from line 1058 should probably reference the attn_mask from line 1053.

**Comment by younesbelkada** [comment]
Great catch! The PR https://github.com/huggingface/transformers/pull/21730 should add the fix you proposed
