### ISSUE TITLE
700 hp - 1250 hp

### ISSUE THREAD

**Issue by Marco071086** [huggingface/transformers#21721]
Audi A3 FWD 2.0T
CHANGE
Engine Turbocharger ES#4147635

R410 Turbo Upgrade Kit & Tuning Package
The R410 Turbo Kit was designed for the track day enthusiast looking for increased horsepower and torque throughout the powerband, without sacrificing response and reliability.
End user to work directly with 034Motorsport on tune - While software is included, the ECU will still need to be sent to 034 for the initial flash load*
For vehicles with FSI engines only

Mfg #034-145-1015ECS #ES#4147635
 Add to Wish ListTrack & Share 4347.00

Audi

8P (2005-2013)

2.0T

FWD
 For vehicles with FSI engines only

ECS Images
Upload 

 PRODUCT DETAILS
 FITS THESE CARS
Product Details
End user to work directly with 034Motorsport on tune - While software is included, the ECU will still need to be sent to 034 for the initial flash load*
For vehicles with FSI engines only
034Motorsport is proud to offer the R410 Hybrid Turbocharger Upgrade Kit for the 8J/8P Audi TT/A3 & MkV Volkswagen GTI/GLI 2.0T FSI!

R410 was designed for the track day enthusiast who desires an improved usable powerband without sacrificing reliability. Providing significant increases in horsepower and torque throughout the powerband, the R410 Turbo Kit shines on track where the factory turbocharger can’t keep up. Consisting of an OEM+ hybrid turbocharger upgrade and 034Motorsport’s proprietary performance software, R410 is the elegant, reliable solution for breathtaking performance on the street or track, at an excellent price point.

At the center of the 034Motorsport R410 Turbo Kit is the LOBA LO410-EA113DV drop-in hybrid turbocharger upgrade. Made in Germany and based on the factory Borg Warner unit, this turbocharger features a state-of-the-art billet compressor wheel to allow for higher flow. The backplate, compressor housing, turbine housing, and exhaust manifold have all been CNC-machined for optimal flow and increased performance. In addition, the LO410-EA113DV turbocharger features an upgraded thrust bearing and is precision-balanced to ensure reliability.

034Motorsport spent a significant amount of time developing and verifying our proprietary software to ensure that R410 delivers consistent, reliable power under grueling track conditions. Through optimization of the factory ECU's boost, fueling, and timing maps, the R410 Tuning Package brings out the potential of the LO410-EA113DV Turbocharger. Peak boost ranges from 20-23 PSI (octane dependent) and tapers to 18 PSI by the new 7,100 RPM redline to keep the turbo running at its optimum efficiency. This conservative, track-oriented boost mapping provides rock-solid performance lap after lap, and is combined with an advanced boost control strategy that allows for increased precision beyond factory limits. Going beyond power improvements, 034Motorsport’s calibrator also made improvements to the throttle mapping, increased idle stability, and enabled left-foot braking. The end result is a tune that drives as smoothly as a factory calibration, with power delivery that is consistent and manageable on the street and track alike.

The R410 Hybrid Turbocharger Upgrade Kit installs as a drop-in replacement for the factory parts, without requiring extensive modifications to other components. Every R410 Tuning Package includes a fully-loaded PL34 Handheld Flash-Loader that allows the end user to reflash between 91, 93 and 100 octane files.

Tuning Features:

Developed In-House on the Street, Track, and 034Motorsport's Chassis Dyno
Optimized Boost, Timing, and Fueling Maps for Increased Horsepower & Torque
Includes PL34 Handheld Flash-Loader with 91 Octane, 93 Octane, 100, and 104 Octane Tunes
Increased Rev Limiter to 7,100 RPM
Speed Limiter (Governor) Removed
Improved Throttle Response & Power Delivery
Refined Throttle Mapping for Part Throttle Drive-ability
Increased Idle Stability (Especially Helpful with Lightweight Flywheels!)
Hardware Features:

LOBA LO410-EA113DV Turbocharger
LOBA CNC-Machined Billet Compressor Wheel
5-Axis CNC Re-Profiled Compressor Housing & Backplate
5-Axis CNC-Machined Turbine Housing
Upgraded Thrust Bearing
Upgraded Wastegate Actuator 
High-Precision Balancing
Made in Germany
Audi S3 FSI Fuel Injectors
155 bar HPFP PRV
3 bar MAP Sensor
PL34 Hand-Held Flash Loader
Installation Hardware Kit Included!
Compatible Vehicles:

2006 - 2008 Audi TT (8J)
2.0T FSI
2006 - 2008 Audi A3  (8P)
2.0T FSI
2006 - 2008 Volkswagen Eos / GLI / GTI  (MkV)
2.0T FSI
Required Supporting Modifications:

High Pressure Fuel Pump (HPFP) Upgrade
Performance Downpipe Upgrade
Performance Intercooler Upgrade
Performance Air Intake 
Recommended Supporting Modifications:

Low Pressure Fuel Pump (LPFP) Upgrade
Tune Installation:

Initial Installation: Flashed directly to your vehicle's ECU through the OBD-2 port using the included PL34 Handheld Flash-Loader.
Program Switching: Once the initial flash is performed, end users can flash between programs using the included PL34 Handheld Flash-Loader. 
Peak Horsepower & Torque:
91 Octane - 334 Horsepower / 319 Foot-Pounds of Torque
93 Octane - 354 Horsepower / 347 Foot-Pounds of Torque
100 Octane - 376 Horsepower / 353 Foot-Pounds of Torque

Peak Horsepower & Torque Gains Under Curve:
91 Octane - 137 HP @ 6,400 RPM / 114 TQ @ 5,550 RPM
93 Octane - 155 HP @ 6,400 RPM / 136 TQ @ 4,600 RPM
100 Octane - 179 HP @ 6,400 RPM / 148 TQ @ 5,850 RPM

Call Us330-331-2003
ChatLive Chat
Company
About Us Careers Contact Us ECS Blog Become a Dealer Sponsorships / Partnerships
My Account
Sign In / Create Account My Wish Lists My Cart My Vehicles My Orders
Customer Service
Shipping Policy Payment Methods Returns and Warranty Policy Track Order Submit a Return Product Warranty Site Security
Vehicles
BMW Parts VW Parts Audi Parts Mercedes Parts Porsche Parts MINI Parts Supported Vehicles Wanted: Development Vehicles
Your Opinion Matters!
We invite you to share your shopping experiences with ECS so we can better meet your needs

**Comment by julien-c** [comment]
good thing that this is on GitHub and not on the hub
