### ISSUE TITLE
RobertaTokenizer token type issue

### ISSUE THREAD

**Issue by CZWin32768** [huggingface/transformers#2174]
## ❓ Questions & Help

Why the two middle `<\s>` are both assigned with token type 0?

https://github.com/huggingface/transformers/blob/e92bcb7eb6c5b9b6ed313cc74abaab50b3dc674f/transformers/tokenization_roberta.py#L149

Could this one be better?
```python
return len(cls + token_ids_0 + sep) * [0] + len(sep + token_ids_1 + sep) * [1] 
```

**Comment by yuchenlin** [comment]
having the same question... why add two seps instead of one?
