### ISSUE TITLE
Ability to specify certificate for running language training modules (e.g. run_mlm.py)

### ISSUE THREAD

**Issue by codesnail** [huggingface/transformers#21763]
### Feature request

Add a command line param in training modules, e.g., run_mlm.py to take in a custom certificate file for the requests module.

### Motivation

When running behind a VPN, the training modules e.g., run_mlm.py script gives SSL errors when trying to connect to URLs, e.g., to download a pre-trained model. It gives an error like this:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /roberta-base/resolve/main/config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

This seems to be caused when the code from a device that is behind a VPN, because the VPN connection uses a custom root cert.

### Your contribution

I was able to resolve the issue by specifying a certificate explicitly in requests.get() in _http.py, as follows:

ca = "company_root_ca_exported_from_my_browser"

then modified the following line:
response = requests.request(method=method, url=url, **kwargs)

to this:

response = requests.request(method=method, url=url, verify=ca, **kwargs)

**Comment by sgugger** [comment]
Examples are just examples. They can't contain 1,000 arguments to support every user's need without becoming unreadable. In this instance, you should just change the example to suit your need.
