### ISSUE TITLE
run_squad.py for SQuAD2.0 have bad f1 score

### ISSUE THREAD

**Issue by WenTingTseng** [huggingface/transformers#2176]
why I use run_squad.py for SQuAD2.0 have bad f1 score 43.638
The noanser_f1=0.0 it look like do not deal with not answerable situation
I don't have change anything
I just run like this

python3 run_squad.py \
  --model_type bert \
  --model_name_or_path bert-base-cased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file /share/nas165/Wendy/transformers/examples/tests_samples/SQUAD/train-v2.0.json \
  --predict_file /share/nas165/Wendy/transformers/examples/tests_samples/SQUAD/dev-v2.0.json \
  --per_gpu_train_batch_size 4 \
  --learning_rate 4e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /share/nas165/Wendy/transformers/examples/squad_debug_SQuAD_1213_bert/

Do anyone know how to do? Thanks a lot

**Comment by julien-c** [comment]
Can you please post the required version numbers? (Should be in the issue template)

**Comment by WenTingTseng** [comment]
the version numbers is 2.2.0

**Comment by waalge** [comment]
- Is it answering every question? for V2 you might want this flag passed
https://github.com/huggingface/transformers/blob/master/examples/run_squad.py#L409

- Your model is cased?
https://github.com/huggingface/transformers/blob/master/examples/run_squad.py#L428

**Comment by matteodelv** [comment]
@WenTingTseng If you want to use SQuAD v2.0, you have to pass the `--version_2_with_negative` argument to `run_squad.py`, otherwise the model supposes every question has at least an answer. Without that flag, you are basically not "learning" the no-answerable part.

**Comment by WenTingTseng** [comment]
ok, problem is resolved
Thanks a lot
