### ISSUE TITLE
BioGPT Token Classification

### ISSUE THREAD

**Issue by upjabir** [huggingface/transformers#21786]
### Feature request

It would be nice to have this available.

### Motivation

working on biomedical token classification datasets and I would like to try BioGPT with them.

### Your contribution

I could send a PR if you want. I guess it shouldn't be too hard.

**Comment by NielsRogge** [comment]
Yes, feel free to contribute :)

**Comment by upjabir** [comment]
sure

**Comment by kurchi1205** [comment]
> sure, Let me work on it

Are you working on it? Else I will take it up.

**Comment by upjabir** [comment]
> > sure, Let me work on it
> 
> Are you working on it? Else I will take it up.

**Comment by upjabir** [comment]
@kurchi1205 Am working on it . The problem is that biogpt doesnt have fast tokenizer . Currenlty am in a testing phase
