### ISSUE TITLE
piepline not loading the model

### ISSUE THREAD

**Issue by deepanshudashora** [huggingface/transformers#21781]
### System Info

ubuntu 22.04

### Who can help?

@Narsil 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
    pipe = pipeline("document-question-answering", model=model,tokenizer=tokenizer)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 811, in pipeline
    raise Exception(
Exception: Impossible to guess which feature extractor to use. Please provide a PreTrainedFeatureExtractor class or a path/identifier to a pretrained feature extractor.
```

### Expected behavior

SHould be able to load the model

**Comment by Narsil** [comment]
How? This pipeline requires a feature extractor to see the document doesn't it?
