### ISSUE TITLE
Flax Whisper predicts erroneous exclamation mark

### ISSUE THREAD

**Issue by sanchit-gandhi** [huggingface/transformers#21791]
### System Info

- `transformers` version: 4.27.0.dev0
- Platform: Linux-4.19.0-21-cloud-amd64-x86_64-with-debian-10.13
- Python version: 3.7.12
- Huggingface_hub version: 0.12.1
- PyTorch version (GPU?): 1.12.1+cpu (False)
- Tensorflow version (GPU?): 2.11.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.6.4 (gpu)
- Jax version: 0.3.25
- JaxLib version: 0.3.25
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@sanchit-gandhi @andyehrenberg @ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code snippet:
```python
from transformers import FlaxWhisperForConditionalGeneration, WhisperProcessor
from datasets import load_dataset

model = FlaxWhisperForConditionalGeneration.from_pretrained("openai/whisper-tiny")
processor = WhisperProcessor.from_pretrained("openai/whisper-tiny")

librispeech = load_dataset("hf-internal-testing/librispeech_asr_dummy", "clean", split="validation")
sample = librispeech[0]["audio"]["array"]

input_features = processor(sample, return_tensors="np").input_features

pred_ids = model.generate(input_features)
pred_text = processor.batch_decode(pred_ids.sequences)
print(pred_text)
```
**Print Output:**
```
['<|startoftranscript|>!<|transcribe|><|notimestamps|> Mischekvilder is the apostle of the middle classes, and we are glad to welcome his gospel.<|endoftext|>']
```

We see an extra `!` after the `<|startoftranscript|>` token that should't be there.

Do you fancy taking a look into this one @andyehrenberg? Otherwise can try and find time next week.

### Expected behavior

Should return:
```
['<|startoftranscript|><|transcribe|><|notimestamps|> Mischekvilder is the apostle of the middle classes, and we are glad to welcome his gospel.<|endoftext|>']
```

**Comment by andyehrenberg** [comment]
I think the expected behavior should be returning:

`['<|startoftranscript|><|en|><|transcribe|><|notimestamps|> Mischekvilder is the apostle of the middle classes, and we are glad to welcome his gospel.<|endoftext|>']`
@andyehrenberg

 
Add heading textAdd bold text, <Cmd+b>Add italic text, <Cmd+i>
Add a quote, <Cmd+Shift+.>Add code, <Cmd+e>Add a link, <Cmd+k>
Add a bulleted list, <Cmd+Shift+8>Add a numbered list, <Cmd+Shift+7>Add a task list, <Cmd+Shift+l>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply
I think the expected behavior should be returning:

`
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/huggingface/transformers/blob/3dae0d7b4fb8d7e9383b893e4e1799191bb2ab7b/CONTRIBUTING.md) and [code of conduct](https://github.com/huggingface/transformers/blob/3dae0d7b4fb8d7e9383b893e4e1799191bb2ab7b/CODE_OF_CONDUCT.md).
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests

Notifications
Customize
You’re receiving notifications because you were mentioned.
1 participant
@sanchit-gandhi

**Comment by andyehrenberg** [comment]
I'm seeing the problem - `force_token_array.at[index].set(token)` when `token` is `None` sets the value at `index` to 0. We should just make it so when `token` is None, keep the value at that index at -1.

**Comment by andyehrenberg** [comment]
```
def __init__(self, force_token_map):
        force_token_map = dict(force_token_map)
        # Converts the dictionary of format {index: token} containing the tokens to be forced to an array, where the
        # index of the array corresponds to the index of the token to be forced, for XLA compatibility.
        # Indexes without forced tokens will have a negative value.
        force_token_array = jnp.ones((max(force_token_map.keys()) + 1), dtype=jnp.int32) * -1
        for index, token in force_token_map.items():
            if token is not None:
                force_token_array = force_token_array.at[index].set(token)
        self.force_token_array = jnp.int32(force_token_array)
```

**Comment by andyehrenberg** [comment]
Also, just keep in mind that `forced_decoder_ids` has to be a static argument for jitted functions. The workaround I use is having empty `forced_decoder_ids` and instead passing them into `decoder_input_ids` when I know the forced ids might change.

**Comment by hannan72** [comment]
Hi
Could you please specify how to set forced_decoder_ids for the FlaxWhisperForConditionalGeneration object?
@sanchit-gandhi

**Comment by ArthurZucker** [comment]
You should either modify the ` model.generation_config.forced_decoder_ids`  or when calling `generate`, set the `language`, `task`  and `return_timestamps` arguments. You can also pass them as `decoder_input_ids`  (which is also an argument of the `generate()`  function or ` forced_decoder_ids`.

**Comment by hannan72** [comment]
> You should either modify the ` model.generation_config.forced_decoder_ids` or when calling `generate`, set the `language`, `task` and `return_timestamps` arguments. You can also pass them as `decoder_input_ids` (which is also an argument of the `generate()` function or ` forced_decoder_ids`.

It does not respect the forced_decoder_ids when I pass it to model.generation_config.
This is my code:
```
model = FlaxWhisperForConditionalGeneration.from_pretrained(model_id, dtype=jnp.float16, from_pt=True)
jit_generate = jax.jit(model.generate, static_argnames=["max_length"])
model.generation_config.forced_decoder_ids = processor.get_decoder_prompt_ids(language="en", task="translate")
pred_ids = jit_generate(input_features, max_length=128)
```

But the result is not translation to english (as same as when forced_decoder_ids is set to None)

**Comment by hannan72** [comment]
Also, when I set `language` to `generate()` function, it raises error:
```
pred_ids = jit_generate(input_features, max_length=128, language="<|en|>")

File /opt/conda/lib/python3.8/site-packages/jax/_src/api_util.py:568, in _str_abstractify(x)
    567 def _str_abstractify(x):
--> 568   raise TypeError(f"Argument '{x}' of type {type(x)} is not a valid JAX type")

TypeError: Argument '<|en|>' of type <class 'str'> is not a valid JAX type
```

I've also tested `language='en'` and `language='english'` and the result is the same (following error)

**Comment by ArthurZucker** [comment]
That is because you are not using the latest version of transformers. All of this was adressed in #21965
