### ISSUE TITLE
Tokenizer call function gives an error when using the "target_text "argument without using "text" argument. 

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#21806]
### System Info

Name: transformers
Version: 4.21.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache
Location: /databricks/python3/lib/python3.9/site-packages
Requires: packaging, pyyaml, filelock, numpy, regex, tokenizers, tqdm, huggingface-hub, requests

@ArthurZucker

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. tokenizer_label = AutoTokenizer.from_pretrained(base_model)
2. labels = tokenizer_label(text_target=targets, padding=False, truncation=True)

### Expected behavior

TypeError: __call__() missing 1 required positional argument: 'text'

**Comment by sgugger** [comment]
You version of Transformers is too low, you need to upgrade it as `target_text` is a somewhat recent feature.

**Comment by shamanez** [comment]
Should I install tranformers from source ? Because I also tried PIP and
didn’t work.

**Comment by ArthurZucker** [comment]
This change was introduced in `transformers==v4.22.0`. Try `pip install --upgrade transformers` as `pip install transformers` will do nothing if you already have the library.

**Comment by shamanez** [comment]
it worked. Thanks
