### ISSUE TITLE
Adding additional terms to the Transformers glossary

### ISSUE THREAD

**Issue by MichaelRipa** [huggingface/transformers#21801]
### Feature request

Adding definitions to the [Transformers glossary](https://huggingface.co/docs/transformers/glossary) for each of the following terms:

- **encoder, decoder and encoder/decoder:** You already have definitions for autoencoding and autoregressive models but it's not immediately clear from the glossary that those are synonymous to encoder and decoder. Could point to relevant sections of the [Summary of the models](https://huggingface.co/docs/transformers/model_summary) article.
- **finetuned model:** There already is a glossary term for pretrained model, can link to the [Fine-tune a pretrained model](https://huggingface.co/docs/transformers/training) article
- **inference**  
- **pipeline:** Could link to the [Pipelines for inference](https://huggingface.co/docs/transformers/pipeline_tutorial) article
- **preprocessing:** Can link to [the preprocess document](https://huggingface.co/docs/transformers/preprocessing)
- **supervised and unsupervised learning** 

A few other definitions which might be worth defining (even if they don't show up as much in your documentation) is  **representation learning**, **semi-supervised learning**, **feature extraction**, **Large Language Models (LLM)** (mainly because it is such a popular term now) and **transfer learning**.

Finally, it might be worth putting acronyms beside glossary terms like **natural language processing/understanding** and **recurrent neural networks** (i.e. NLP/U and RNN) both for brevity and because they are so commonly used.

### Motivation

The glossary page has been quite helpful for me in understanding certain overloaded terms in deep learning, and I feel that adding these terms would be beneficial to others. It also could help link people to useful articles as many of the above terms have been explained already in one of your articles which helps with keeping things organized. 

### Your contribution

I would be happy to help with coming up with the definitions and submitting a PR with the added changes 🙂

**Comment by sgugger** [comment]
cc @MKhalusova and @stevhliu

**Comment by stevhliu** [comment]
Thanks for the great suggestions, and for adding links to other docs for some of the definitions. Feel free to open a PR for these new definitions/changes! 😄 

> encoder, decoder and encoder/decoder

I think for encoder and decoder, we could combine those with the existing definitions for autoencoding/autoregressive, instead of having two separate definitions that basically explain the same thing. The summary of the models [guide](https://huggingface.co/docs/transformers/main/en/model_summary) has actually been recently updated such that you can't really link to it.

> Finally, it might be worth putting acronyms beside glossary terms

Great idea!

**Comment by MichaelRipa** [comment]
Excellent, I will get started on this over the weekend, thanks for the feedback! 🙂

> I think for encoder and decoder, we could combine those with the existing definitions for autoencoding/autoregressive, instead of having two separate definitions that basically explain the same thing.

Just to be clear here, would this be renaming existing autoencoding/autoregressive entries as encoder/decoder & mentioning that autoencoding/autoregressive are synonyms?

**Comment by stevhliu** [comment]
Awesome, looking forward to your contribution! 🤗

> Just to be clear here, would this be renaming existing autoencoding/autoregressive entries as encoder/decoder & mentioning that autoencoding/autoregressive are synonyms?

Yeah, I think having entries for encoder/decoder would be better than autoencoding/autoregressive.

**Comment by MichaelRipa** [comment]
Thanks for your help! 🙌  I've got a draft complete locally with the proposed changes and will make a PR in the next day or so. I'll close this issue for the time being though!
