### ISSUE TITLE
Conda version is not the latest

### ISSUE THREAD

**Issue by KamyarGhajar** [huggingface/transformers#2181]
## 🚀 Feature

The conda package in conda forge channel (v2.1.1) is not the latest released version (v2.2.2) so the ALBERT model is missing from the package.

## Motivation

In conda environment we need the latest packages containing the ALBERT model.

## Additional context

Also, for the ALBERT model in its code it has printing comments for each 12 layers. It shouldn't be there I guess in a production ready version.

**Comment by TheEdoardo93** [comment]
Do you mean lines 66-67 and 153 in the [modeling_albert.py](https://github.com/huggingface/transformers/blob/master/transformers/modeling_albert.py) script?

**Comment by KamyarGhajar** [comment]
@TheEdoardo93 in the pip package in line 289 there was `print("Layer index", layer_index)` that is removed right now.

**Comment by LysandreJik** [comment]
The last pip package (2.2.2) should not be outputting the layers. Could you please tell me what is the output in your console when running the following snippet?

```py
from transformers import AlbertModel, __version__
import torch

print(__version__)
model = AlbertModel.from_pretrained("albert-base-v1")
output = model(torch.tensor([[1,2,3]]))
```
