### ISSUE TITLE
Two tfevent files are being generated for each run of trainer

### ISSUE THREAD

**Issue by XanderWA** [huggingface/transformers#21821]
### System Info

Each run of the trainer two tfevent files are being generated, it looks like this:
/runs
--Feb27_09-46-42_...
----events.out.tfevents....0
----/1677491207.0429652
------events.out.tfevents....1

When reading these files with TensorBoard I don't get any output from the .1 file, how can I get rid of it (because these clutter my TensorBoard) or get actual data from it?

Thanks in advance

@sgugger 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Simply starting any training.

### Expected behavior

One tfevents file or a valid output from the .1 file.

**Comment by sgugger** [comment]
I have no idea. Let us know if you find the reason/how to fix it!

**Comment by Ch4osMy7h** [comment]
also face this issue by add the tensorboard callback in the examples/language_modeling/run_mlm.py

**Comment by Sanster** [comment]
Face the same issue:
- transformers: 4.26.1
- tensorboard: 2.12.0

**Comment by hwijeen** [comment]
Also faces this issue
