### ISSUE TITLE
sts-b task score is far worse than other GLUE tasks

### ISSUE THREAD

**Issue by zxznm** [huggingface/transformers#2182]
## ❓ Questions & Help

Hello,
I'm evaluating my GPT style model pretrained on TEXT8 dataset with GLUE.
Below is the evaluation result.

```
CoLA | SST-2 |     MRPC    |    QQP    |    STS-B    | MNLI | QNLI | RTE  | WNLI
19.1 |   85  | 82.5 / 71.6 | 78.4 / 82 | 41.6 / 39.4 | 62.8 | 74.6 | 57.4 | 56.3
```

Compare to other GLUE tasks, STS-B scores seem far worse than baseline in leader board.
Does anyone know why model works bad on STS? Thanks a lot.

**Comment by memray** [comment]
Have you resolved this issue? I observed a much worse result.
