### ISSUE TITLE
transformers  == 4.26.0 has a bug

### ISSUE THREAD

**Issue by tongzhao315** [huggingface/transformers#21837]
### System Info

Traceback (most recent call last):
    from transformers import BridgeTowerProcessor, BridgeTowerForImageAndTextRetrieval
ImportError: cannot import name 'BridgeTowerProcessor' from 'transformers' (lib/python3.7/site-(packages/transformers/__init__.py),could you fix this bug。i use transformers  == 4.26.0(pip )      
 
/cc @xianbaoqian 

### Who can help?

@xianbaoqian 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import BridgeTowerProcessor, BridgeTowerForImageAndTextRetrieval
import requests
from PIL import Image

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
texts = ["An image of two cats chilling on a couch", "A football player scoring a goal"]

processor = BridgeTowerProcessor.from_pretrained("BridgeTower/bridgetower-base-itm-mlm")
model = BridgeTowerForImageAndTextRetrieval.from_pretrained("BridgeTower/bridgetower-base-itm-mlm")

# forward pass
scores = dict()
for text in texts:
    # prepare inputs
    encoding = processor(image, text, return_tensors="pt")
    outputs = model(**encoding)
    scores[text] = outputs.logits[0, 1].item()

### Expected behavior

fix this bug

**Comment by ArthurZucker** [comment]
If you want to use this model, you should build from source. It was merged to main on the 25th of January, the release does not include it. Next release will make it available. 
Closing as I can import on main.
