### ISSUE TITLE
Unable to convert BioGpt slow tokenizer to fast: token out of vocabulary

### ISSUE THREAD

**Issue by seantaud** [huggingface/transformers#21838]
### System Info

I was trying to use BioGpt model in my QA task for fine-tuning. I would like to construct a fast tokenizer class based on the BioGptTokenizer, so that I could use the offsets_mapping to know from which words the tokens do origin. But unfortunately, when creating a BiogptTokenizerFast from the PreTrainedTokenizerFast by `convert_slow_tokenizer`,  following error occurs:   Error while initializing BPE: Token `-@</w>` out of vocabulary. 

#### Error trace
```
Traceback (most recent call last):
  File "run.py", line 124, in <module>
    trainer, predict_dataset = get_trainer(args)
  File "***/tasks/qa/get_trainer.py", line 31, in get_trainer
    tokenizer = BioGptTokenizerFast.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1801, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1956, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "***/model/biogpt/tokenization_biogpt_fast.py", line 117, in __init__
    super().__init__(
  File "***/model/biogpt/tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "***/model/biogpt/convert_slow_tokenizer.py", line 1198, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "***/model/biogpt/convert_slow_tokenizer.py", line 273, in converted
    BPE(
Exception: Error while initializing BPE: Token `-@</w>` out of vocabulary
```

### Who can help?

@ArthurZucker @younesbelkada @kamalkraj 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I copy the code related to colab.This is the link : https://colab.research.google.com/drive/1IMhiDz45GiarBLgXG9B2rA_u0ZOmmjJS?usp=sharing

### Expected behavior

According to this issue [https://github.com/huggingface/transformers/issues/9290](url), this problem might be caused by some missing tokens in `vocab.json` or `merge.txt`. Could you please check it? Thank you very much!

**Comment by ArthurZucker** [comment]
Hey! It would be a bit difficult to say that this is a bug as we do not have an implementation of the `BioGPTConverter` which would be cool btw. In order to properly create a fast tokenizer you need to have the `pre_normalizer` the `decoder` etc. Take a look at `convert_slow_tokenizers` for more details! Feel free to open a PR and ping me 😉
