### ISSUE TITLE
Troubleshooting AttributeError: 'Seq2SeqTimeSeriesPredictionOutput' object has no attribute 'sequences'

### ISSUE THREAD

**Issue by hassanshallal** [huggingface/transformers#21835]
Hi, I am reporting this issue as recommended

Context: I am trying to setup/test transformers library, I managed to get the installation and followed the steps in this specific time series transformer tutorial: https://huggingface.co/docs/transformers/model_doc/time_series_transformer

I received an error when I tried to invoke:
`mean_prediction = outputs.sequences.mean(dim=1)`

The error: AttributeError: 'Seq2SeqTimeSeriesPredictionOutput' object has no attribute 'sequences'

by:
`print(outputs.keys())`
I got:
`odict_keys(['loss', 'params', 'encoder_last_hidden_state', 'scale', 'static_features'])`

I searched the documentations but can not find any match.

`import transformers as tfs
print(tfs.__version__)`

4.26.1

I would really appreciate some feedback in regards to this issue.

Thank you

**Comment by ArthurZucker** [comment]
Hey. I don't think you are using the correct version of transformers. I can't reproduce this and our documentation tests ensure that this works. Also see here for the `sequence` [output](https://github.com/ArthurZucker/transformers/blob/main/src/transformers/models/time_series_transformer/modeling_time_series_transformer.py#L535) . As you can see, the `generate` method of `TimeSeriesTransformerForPrediction` return this class.

**Comment by hassanshallal** [comment]
Hi Arthur, thank you for the response. I revisited the tutorial an =d it turned out I missed on a step. It all good now and this issue can be closed.
