### ISSUE TITLE
cannot import name 'COMMON_SAFE_ASCII_CHARACTERS'

### ISSUE THREAD

**Issue by dickreuter** [huggingface/transformers#21858]
### System Info
macbook pro m2 with anaconda, python 3.9

I'm running transformers on an m1 mac and am getting the following error when I import 
`from transformers import OwlViTProcessor, OwlViTForObjectDetection`

File ~/opt/anaconda3/envs/nd1/lib/python3.9/site-packages/transformers/__init__.py:26
     23 from typing import TYPE_CHECKING
     25 # Check the dependencies satisfy the minimal versions required.
---> 26 from . import dependency_versions_check
     27 from .utils import (
     28     OptionalDependencyNotAvailable,
     29     _LazyModule,
   (...)
     42     logging,
     43 )
     46 logger = logging.get_logger(__name__)  # pylint: disable=invalid-name

File ~/opt/anaconda3/envs/nd1/lib/python3.9/site-packages/transformers/dependency_versions_check.py:36
     33 if pkg in deps:
     34     if pkg == "tokenizers":
     35         # must be loaded here, or else tqdm check may fail
---> 36         from .utils import is_tokenizers_available
...
---> 10 from charset_normalizer.md import mess_ratio
     11 from charset_normalizer.models import CharsetMatches, CharsetMatch
     12 from warnings import warn

AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Install transformers on a macbook m2

from transformers import OwlViTProcessor, OwlViTForObjectDetection

### Expected behavior

it should import but instaed it gives the above error message

**Comment by sgugger** [comment]
Please run `transformers-cli env` and paste the results here, as requested in the issue template. In particular, do you have the tokenizers module installed and which version?

**Comment by tomo-cps** [comment]
I got a similar bug :bug:
`ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant'`

When I encountered this I used:
```
pip install chardet
```

**Comment by ani0075saha** [comment]
> ### System Info
> macbook m2 with anaconda, python 3.9
> 
> I got a similar bug 🐛 `ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant'`
> 
> When I encountered this I used:
> 
> ```
> pip install chardet
> ```

Encountered the same error message when importing transformers. Installing chardet solved the issue.

Output for transformers-cli env

- `transformers` version: 4.28.0.dev0
- Platform: Linux-4.18.0-425.13.1.el8_7.x86_64-x86_64-with-glibc2.28
- Python version: 3.9.16
- Huggingface_hub version: 0.13.2
- PyTorch version (GPU?): 1.13.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

**Comment by sgugger** [comment]
Could you please provide us with the full traceback? To potentially fix this, we need to know which module raises the error and neither Transformers nor Tokenizers import anything from charset directly.

**Comment by ani0075saha** [comment]
```code
Traceback (most recent call last):
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/transformers/utils/__init__.py", line 30, in <module>
    from .generic import (
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/transformers/utils/generic.py", line 29, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 32, in <module>
    from . import logging
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/transformers/utils/logging.py", line 35, in <module>
    import huggingface_hub.utils as hf_hub_utils
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/huggingface_hub/utils/__init__.py", line 32, in <module>
    from ._errors import (
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 3, in <module>
    from requests import HTTPError, Response
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
  File "charset_normalizer/md.py", line 5, in <module>
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/charset_normalizer/constant.py)
```

**Comment by sgugger** [comment]
Ok so this looks like it stems from the `requests` so it may be worth raising the issue there (it looks like `from requests import HTTPError, Response` fails in your env, if you want a minimal reproducer).

@Wauplin We might also need to put something in the dependencies of `huggingface_hub` to have the `chardet` dep installed on MacOS?

**Comment by Wauplin** [comment]
@sgugger I'm not against adding the dependency but as you said, it really seems to be an issue on `requests` side that has nothing to do with `huggingface_hub`/`transformers` (except the fact we use `requests`). I would first try to:

1. isolate a minimal reproducible code. Maybe just 1 line is enough:
```py
from requests import HTTPError
# or
from requests import Response
```

2. list all installed deps (in particalar, `requests`, `charset` and `charset-normalizer`) + python version + os
3. open an issue on https://github.com/psf/requests
4. once that's done, open an issue in [huggingface_hub](https://github.com/huggingface/huggingface_hub) and decide what's the best solution (add chardet as deps for macos for example?)

**Comment by sgugger** [comment]
You can try opening an issue at [charset_normalizer](https://github.com/Ousret/charset_normalizer) and point out that their 3.1.0 release seems broken on MacOS (but 2.1.0 works apparently, from the comment above).

From your traceback, the simple line `import charset_normalizer` should fail in your environment (it doesn't in mine, but I'm not on MacOS).

**Comment by drei34** [comment]
I got the above error and did `python -m pip install charset-normalizer==2.1.0`. This gave me another error which went away after doing `pip install chardet `.

**Comment by jfjordanfarr** [comment]
I am currently having this issue with one anaconda environment and not another. This is very confusing.

**Comment by AayushSameerShah** [comment]
Actually I was getting the same error **when importing OpenAI** but that was solved by **upgrading the package**

`pip install --upgrade chardet`

And that worked!

**Comment by bring-nirachornkul** [comment]
> ### System Info
> macbook air m2 with anaconda, python 3.9
> 
> I got a similar bug 🐛 `ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant'`
> 
> When I encountered this I used:
> 
> ```
> pip install chardet
> ```

It's working for me. You are the best.
