### ISSUE TITLE
Running squad with GPT-J-6B fails due to issue in tokenizer.

### ISSUE THREAD

**Issue by jojivk73** [huggingface/transformers#21854]
### System Info

Hi,
   I am tryiing to use the run_qa.py script under examples/tensorflow/question-answering 
   Model  EleutherAI/gpt-j-6B. 
   dataset squad.
   it fails as below. 
   
![image](https://user-images.githubusercontent.com/14943401/221944528-15e0f573-1950-4d9b-9cd8-b8ec71c91e97.png)

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install transformer from source 
2. python examples/tensorflow/question-answerin/run_qa.py with --model_name  EleutherAI/gpt-j-6B.
   ---   \
   --dataset_name squad  --do_train --do_eval 

### Expected behavior

The script to run the finetuning task

**Comment by sgugger** [comment]
This example does not support GPT-J out of the box since GPT-J has no CLS token (compared to BERT or XLNet). You will need to adapt the preprocessing as a result.

**Comment by jojivk73** [comment]
@sgugger Can you please elaborate.
I tired using distillbert tokenizer and it is running. 
I am not sure if that is good.
