### ISSUE TITLE
Very slow process when `torch_dtype` is passed.

### ISSUE THREAD

**Issue by realSAH** [huggingface/transformers#21862]
When I use `from_pretrained`, the model loads up from my azure cache at almost 1gbps, but when I specify the `torch_dtype` the process is slowed to a crawling 1 tenth of original speed. When looking at resources it appears that its a single core type of process that is doing the disservice of being bottleneck.

Can we have that parallelized?

**Comment by sgugger** [comment]
There is nothing we can do without a clear reproducer.

**Comment by zacheryvaughn** [comment]
I am experiencing the same issue.
When passing dtype, SDXL inference times are nearly 8X faster compared to torch_dtype.
