### ISSUE TITLE
This line prevent us from using "std" scaling any more.

### ISSUE THREAD

**Issue by zhentaoxuttup** [huggingface/transformers#21864]
https://github.com/huggingface/transformers/blob/b29e2dcaff114762e65eaea739ba1076fc5d1c84/src/transformers/models/time_series_transformer/modeling_time_series_transformer.py#L1549

**Comment by NielsRogge** [comment]
Hi,

Std scaling wasn't supported until #21020 was merged (only mean scaling is currently supported on the latest PyPi install). So if you install Transformers from source, you can use std scaling.

Cc @kashif
