### ISSUE TITLE
__init__() got an unexpected keyword argument 'int8_threshold'

### ISSUE THREAD

**Issue by DHOFM** [huggingface/transformers#21877]
### System Info

- `transformers` version: 4.27.0.dev0
- Platform: Linux-4.15.0-177-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.12.1
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Tensorflow version (GPU?): 2.10.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

also tried on Colab:
- `transformers` version: 4.27.0.dev0
- Platform: Linux-5.10.147+-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.12.1
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Tensorflow version (GPU?): 2.11.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Taken from Notebook named: HuggingFace meets bitsandbytes for lighter models on GPU for inference

```
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

name = "bigscience/bloom-3b"
model_8bit_thresh_4 = AutoModelForCausalLM.from_pretrained(name, device_map="auto", load_in_8bit=True, int8_threshold=4.0)

```
Error is: TypeError: __init__() got an unexpected keyword argument 'int8_threshold'

### Expected behavior

No error setting threshold

**Comment by sgugger** [comment]
You need to use the `quantization_config` to set any argument relative to 8bit loading, cc @younesbelkada

**Comment by DHOFM** [comment]
Thanks, I tried and get : dispatch_model() got an unexpected keyword argument 'offload_index'... I thought offloading to cpu is default false?

is use
`quantization_config = BitsAndBytesConfig(llm_int8_threshold=4.0)`

and 

```
model_8bit = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map=device_map,
    quantization_config=quantization_config,
)
```

device_map is auto

**Comment by sgugger** [comment]
You probably need an upgrade in your Accelerate lib to fix this error.

**Comment by DHOFM** [comment]
Mea culpa, I used one of my old Containers on my GPU Server, upgraded accelerate and it works as expected... Thanks a lot for your fast support

**Comment by shashank140195** [comment]
Even i upgraded the accelerate, it is throwing me the same error @DHOFM can you please tell me what version of accelerate are you using in your container?
