### ISSUE TITLE
Text-classification example does not work as is on 4.27.0.dev

### ISSUE THREAD

**Issue by jojivk73** [huggingface/transformers#21885]
### System Info

Transformer : 4.27.0.dev
Example in : examples/tensorflow/text-classification/run_glue.py 
fails when running example given in README.

"""
python run_glue.py \
--model_name_or_path distilbert-base-cased \
--task_name mnli \
--do_train \
--do_eval \
--do_predict \
--output_dir  outdir \ 
--predict_file data_to_predict.json
"""

Issues : 
  1.  missing data_to_predict.json>
  2. output_dir not mentioned in README.
  2. Fails with following error without --predict_file + --output_dir
  
 
![image](https://user-images.githubusercontent.com/14943401/222235813-1fb96343-9e3d-461a-bd83-039ecbf814e5.png)

  
  

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the script given in description 

### Expected behavior

The task run without issues.

**Comment by sgugger** [comment]
cc @Rocketknight1

**Comment by jojivk73** [comment]
My bad :(.  It was trying to use for GPT-J  instead of distilbert-base-cased

**Comment by Rocketknight1** [comment]
Ah yes - CLM models generally need some modifications to transfer to text classification tasks, including adding a padding token. Their performance is also usually worse. Using a MLM (masked language model, like BERT/RoBERTa/DistilBERT/DeBERTa) base instead will work much better!
