### ISSUE TITLE
Fine-tuning GPT2 or BERT and adding new vocabulary?

### ISSUE THREAD

**Issue by masoudh175** [huggingface/transformers#2193]
## ❓ Questions & Help

I am fine-tuning the GPT2 on a domain-specific corpus and I was wondering if there is a way to add new vocabulary to the model. I am checking the ```vocab.json``` file after saving the model into ```output``` directory and don't find the any new vocabulary in there.

**Comment by LysandreJik** [comment]
Hi, you can add new vocabulary using the tokenizer's `add_tokens` method.

**Comment by masoudh175** [comment]
Thanks for the quick response!
