### ISSUE TITLE
auto_find_batch_size should say what batch size it is using

### ISSUE THREAD

**Issue by p-christ** [huggingface/transformers#21950]
### Feature request

When using `auto_find_batch_size=True` in the trainer I believe it identifies the right batch size but then it doesn't log it to the console anywhere?

It would be good if it could log what batch size it is using?

### Motivation

I'd like to know what batch size it is using because then I will know roughly how big a batch can fit in memory - this info would be useful elsewhere.

### Your contribution

N/A

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by p-christ** [comment]
Also, it would be good if auto find batch size also worked for the eval batch size? Otherwise for the eval batch size I still have to guess a few times and hope I don't run out of memory?

**Comment by muellerzr** [comment]
Thanks! Solved with https://github.com/huggingface/transformers/pull/23800
