### ISSUE TITLE
GitHub Private Vulnerability reporting 

### ISSUE THREAD

**Issue by Sim4n6** [huggingface/transformers#21973]
### Feature request

Enable Private vulnerability reporting in the GitHub repository, please.

https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

### Motivation

I may have identified something low-impact vulnerability, but I would like to report it privately via the usual channel and request a CVE in that case.

### Your contribution

The report that I will submit, when the feature is enabled, please.

**Comment by sgugger** [comment]
cc @Michellehbn

**Comment by Michellehbn** [comment]
Hi @Sim4n6, Thanks for reaching out to us! 🤗 We have a bug bounty program with HackerOne and would love for you to submit security vulnerability reports to https://hackerone.com/hugging_face. This is a private program so we will need to invite you. Do you happen to have an H1 username? Or you can send security@huggingface.co an email and we'll send you an invite!

**Comment by Sim4n6** [comment]
it is [Sim4n6](https://hackerone.com/sim4n6?type=user). No problem.

**Comment by Sim4n6** [comment]
Done.
