### ISSUE TITLE
How to output labels for GLUE test set

### ISSUE THREAD

**Issue by JetRunner** [huggingface/transformers#2198]
## ❓ Questions & Help

Thanks for your great work.

I have done some modification based on your library. I'd like to test it on GLUE test set (not dev set). Is there any way I can do it? Do you have a script for output GLUE submission files?

Thanks.

**Comment by LysandreJik** [comment]
Hi, if you're working on a clone/fork of this library, then you can freely change the following lines:

```py
    def get_train_examples(self, data_dir):
        """See base class."""
        return self._create_examples(
            self._read_tsv(os.path.join(data_dir, "train.tsv")), "train")

    def get_dev_examples(self, data_dir):
        """See base class."""
        return self._create_examples(
            self._read_tsv(os.path.join(data_dir, "dev.tsv")), "dev")
```

to read the `test.tsv` instead of the `dev.tsv`.

**Comment by JetRunner** [comment]
Hi @LysandreJik,

Thanks for your reply!
However, the format of test set is different from the dev set. It has an extra ``id'' field and does not have ground truth labels.  Thus, the simple change you suggested wouldn't work in this case.   Besides, GLUE leaderboard also requires a specific format for submission.

I have noticed that in Huggingface's workshop paper [DistilBERT](https://arxiv.org/abs/1910.01108), you also use DEV set instead of TEST result from GLUE leaderboard. I guess it may be somehow related to the lack of a submission script. To facilitate further research, I hope you can make a script for GLUE submission. As far as I know, many researchers are using huggingface/transformers for their research. I really appreciate it if you can provide a script for the community.

Thanks!

**Comment by JetRunner** [comment]
Hi @LysandreJik,
I've just realized that you are one of the authors of DistilBERT so I suppose you know exactly what I mean. It can truly benefit the research community if you do this. Thanks.

**Comment by yuchenlin** [comment]
hi did u get the script?

**Comment by JetRunner** [comment]
@yuchenlin My co-author wrote one himself. I added you on Wechat but you didn't respond.

**Comment by JetRunner** [comment]
@yuchenlin I asked my co-author Chunshu to send you the script. He seems to have your Wechat.

**Comment by Breakend** [comment]
Hey, I think this would be helpful for many in the community. Can you maybe share the script you wrote for this via a pull request?

**Comment by JetRunner** [comment]
@Breakend Sure, I will verify the script and open a pull request.

**Comment by jibay** [comment]
Hello @JetRunner , no news about this script?
Thank you in advance

**Comment by JetRunner** [comment]
> Hello @JetRunner , no news about this script?
> Thank you in advance

Sorry, I totally forgot about this stuff. I'll notify you as soon as we upload it.

cc @michaelzhouwang

**Comment by MichaelZhouwang** [comment]
> Hello @JetRunner , no news about this script?
> Thank you in advance

Hi I have uploaded the script for prediction on GLUE benchmarks at:
https://github.com/MichaelZhouwang/transformers/blob/master/run_prediction.py
https://github.com/MichaelZhouwang/transformers/blob/master/glue.py
You can first replace the glue.py in src/transformers/data/processor/ and then use run_prediction.py.

**Comment by JetRunner** [comment]
> > Hello @JetRunner , no news about this script?
> > Thank you in advance
> 
> Hi I have uploaded the script for prediction on GLUE benchmarks at:
> https://github.com/JetRunner/BERT-of-Theseus/tree/master/glue_script
> You can first replace the glue.py in src/transformers/data/processor/ and then use run_prediction.py.

cc @Breakend @jibay

**Comment by jibay** [comment]
@JetRunner  @MichaelZhouwang  Thank you for the quick answer, i will check asap :)
