### ISSUE TITLE
DataCollatorForSpanPreTraining

### ISSUE THREAD

**Issue by zanussbaum** [huggingface/transformers#22008]
### Feature request

It seems that there's already a script existing for [T5 pretraining](https://github.com/huggingface/transformers/blob/main/examples/flax/language-modeling/run_t5_mlm_flax.py) that has a DataCollator, but only available in Flax. Would we be able to add a Data Collator for the Span pretraining task that's implemented in the T5 papers?

### Motivation

Currently it's not super easy to run T5 pretraining in Pytorch with Transformers

### Your contribution

I can help with the PR!

**Comment by sgugger** [comment]
Transformers is a library of models, not data collators. You can adapt the code of this data collator to PyTorch in your code, but we won't have it in the main library (the same way the Flax one is just in an example script).

**Comment by zanussbaum** [comment]
No worries, I thought maybe it would fit nicely within the same class as [DataCollatorForLanguageModeling](https://github.com/huggingface/transformers/blob/v4.26.1/src/transformers/data/data_collator.py#L609) but totally understand wanting to keep the scope contained!
