### ISSUE TITLE
Can't import Blip2Processor

### ISSUE THREAD

**Issue by tanayvarshney** [huggingface/transformers#22010]
### System Info

I was trying to follow [this tutorial](https://huggingface.co/docs/transformers/main/en/model_doc/blip-2#transformers.Blip2Model.forward.example) and ran into the following issue:
```
ImportError: cannot import name 'Blip2Processor' from 'transformers' (/usr/local/lib/python3.8/dist-packages/transformers/__init__.py)
```

version: '4.26.1'

@sgugger @ArthurZucker @amyeroberts (there is no PIC for multimodal models so tagging both PICs)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just run the following example: https://huggingface.co/docs/transformers/main/en/model_doc/blip-2#transformers.Blip2Model.forward.example

### Expected behavior

Should import the preprocessor

**Comment by tanayvarshney** [comment]
@sgugger thank you! Just one minor feedback since you are the docs PIC, if a Note modal or just a highlighted note could be added informing if a module hasn't been added to the stable release would be helpful. (If it is already there, I might have missed it, apologies.)

**Comment by sgugger** [comment]
Note that it's not in the [stable documentation](https://huggingface.co/docs/transformers/index) (which is what is viewed by default) only the [main documentation](https://huggingface.co/docs/transformers/main/en/index). Did you get on the page via a search engine maybe and did not realize you were not on the documentation of the latest release?

**Comment by freespirit** [comment]
> Note that it's not in the [stable documentation](https://huggingface.co/docs/transformers/index) (which is what is viewed by default) only the [main documentation](https://huggingface.co/docs/transformers/main/en/index). Did you get on the page via a search engine maybe and did not realize you were not on the documentation of the latest release?

I am not the author but this is exactly what happened to me - I did not see at all there's a dropdown for versions so I assumed BLIP2 is just available.

**Comment by xnerhu** [comment]
🤓

**Comment by rakeshsahni** [comment]
Please restart your notebook, and re-install using below command.

`pip install git+https://github.com/huggingface/transformers`
