### ISSUE TITLE
add progress bar to the sharded model download status

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#22047]
### Feature request

`from_pretrained('bigscience/bloom')` is taking forever the first time until it's cached (~350GB) - I thought that perhaps with 72 shards it'd be awesome to have an overall progress bar (in addition to the each shard download progress bar) to know where things stand and how many hours the coffee break should last.

Thank you!

**Comment by sgugger** [comment]
Nested tqdm bars in the console are unreadable though, so not sure how to fix that.

**Comment by stas00** [comment]
I didn't know that. I remember it definitely worked in the past. Unless you're referring to something I'm not aware of when you say it's unreadable. Is it because the outside tqdm line will be so far from line 72 that it won't be seen as it'd scroll past visible area? 

If that's the case then perhaps this would work:

1. switch to show and erase individual shard download progress as soon as it completed
2. only keep the overall progress bar 

so that there are only 2 lines dedicated to the progress updates.

But if none of this is doable nicely, perhaps at least using `desc` to number each shard's tqdm as in "43/72" would at least give some indication. Though it won't really help that much since one can't tell how much time it took to download the previous x entries.

**Comment by sgugger** [comment]
Note that the description should already contain the name of the file, which ends with 0043-of-0072 normally.

I can have a look at what adding an overall progress bar would look like, but I don't have any control on the per-file progress bar, as it's issued by huggingface_hub. I could deactivate it entirely (so solution 2.) but I don't have control over it's closing.

**Comment by stas00** [comment]
> Note that the description should already contain the name of the file, which ends with 0043-of-0072 normally.

not for me:
![snapshot_49](https://user-images.githubusercontent.com/10676103/224100313-6f4c44e1-b7cd-4e5f-90f3-bd61d34e8c97.png)

> I can have a look at what adding an overall progress bar would look like, but I don't have any control on the per-file progress bar, as it's issued by huggingface_hub. I could deactivate it entirely (so solution 2.) but I don't have control over it's closing.

Understood! Thank you for looking, Sylvain!

**Comment by sgugger** [comment]
Oh maybe you have an older version of huggingface_hub?

**Comment by stas00** [comment]
oh, I didn't know - you're correct - updating to 0.13 did add the filenames - that's much better. Thank you for that, Sylvain.

**Comment by sgugger** [comment]
Can you try the PR mentioned above? I got confused and nested progress bars do appear nicely in the console. It's in notebooks that the result is messy.
