### ISSUE TITLE
Assistance Exporting git-large to ONNX 

### ISSUE THREAD

**Issue by gracemcgrath** [huggingface/transformers#22061]
Hello! I am looking to export an image captioning Hugging Face model to ONNX (specifically I was playing with the [git-large](https://huggingface.co/microsoft/git-large) model but if anyone knows of one that might be easier to deal with in terms of exporting that is great too)

I'm trying to follow [these](https://huggingface.co/docs/transformers/serialization#exporting-a-model-for-an-unsupported-architecture) instructions for exporting an unsupported architecture, and I am a bit stuck on figuring out what base class to inherit from and how to define the custom ONNX Configuration since I'm not sure what examples to look at (the model card says this is a transformer decoder model, but it looks like i that it has both encoding and decoding so I am a bit confused)

I also found [this](https://github.com/huggingface/notebooks/blob/main/examples/onnx-export.ipynb) notebook but I am again not sure if it would work with this sort of model. 

Any comments, advice, or suggestions would be so helpful -- I am feeling a bit stuck with how to proceed in deploying this model in the school capstone project I'm working on. In a worst-case scenario, can I use `from_pretrained` in my application?

**Comment by sgugger** [comment]
Questions around conversion to ONNX should go in the [optimum repo](https://github.com/huggingface/optimum) as  this is where the feature is actually implemented :-)

**Comment by gracemcgrath** [comment]
> Questions around conversion to ONNX should go in the [optimum repo](https://github.com/huggingface/optimum) as this is where the feature is actually implemented :-)

Thank you!! I will post this there.
