### ISSUE TITLE
Some problems when using vit model

### ISSUE THREAD

**Issue by vegetablelearning** [huggingface/transformers#22085]
### Feature request

I am a novice in AI. Recently, I am learning the vit model. There are many teaching about nlp in the document. I want to know how to load the vit model downloaded from the hugging face, and how to use the imagenet dataset to train and test the vit model. I can't find the relevant tutorial. My question is really very basic. If you can answer my question with a simple code, I will be grateful.

### Motivation

Better use of the tansforms library.

### Your contribution

No contribution at present.

**Comment by sgugger** [comment]
Better use the [forums](https://discuss.huggingface.co/) for questions like this as we keep issues for bugs and feature requests only.
