### ISSUE TITLE
Use torch.TensorDicts: The output of tokenizers.batch_encode_plus/__call__ could be made to inherit from torch TensorDicts

### ISSUE THREAD

**Issue by JulesGM** [huggingface/transformers#22096]
### Feature request

Tensor dicts have recently come out as a way to manipulate dicts of tenors in a way that is analogous to pandas, eg to make it easy to work on columns on tensors that share some property and a batch dimension or set of dimensions
https://pytorch.org/rl/tensordict/

An obvious application of this is the output of `tokenizer.batch_encode_plus`. 

### Motivation

Being able to do a bunch of things on all the subtensors at once would be cool, like `.to` and `.cat`, etc.
Having a common interface with tensordict could be fun.

### Your contribution

I don't have the bandwidth to handle this myself.

**Comment by sgugger** [comment]
The result of the tokenizer calls can already interact with the `to` method (note that batch_encode_plus will be deprecated sometime soon) but I agree it could be interesting to look at this! The main challenge I see is that it's not packaged in PyTorch main so would require an extra dep...
