### ISSUE TITLE
error when using from indobenchmark

### ISSUE THREAD

**Issue by fendiirfan** [huggingface/transformers#22111]
### System Info

```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobart-v2")
```
the error
`ValueError: Tokenizer class IndoNLGTokenizer does not exist or is not currently imported.`

any help guys?

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run
```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobart-v2")
```

### Expected behavior

Can used

**Comment by ArthurZucker** [comment]
Hey! The `tokenizer_class` that was set in the configuration.json is wrong as the `IndoNLGTokenizer` does not exist in transformers. You should try to ask the other of the model on the community tab how to use it, or try to use: 
```python 
from transformers import MBartTokenizer
tokenizer = MBartTokenizer.from_pretrained("indobenchmark/indobart-v2")
```
as it appears that the model is an  MBartModel.
