### ISSUE TITLE
FastTokenizer for LLaMa

### ISSUE THREAD

**Issue by theblackcat102** [huggingface/transformers#22114]
### Feature request

FastTokenizer support for LLaMa sentencepiece tokenizer.

### Motivation

The offset_mapping is only available in FastTokenizer, it would be useful if there's support for this.

### Your contribution

I have tried using existing sentencepiece based model as replacement. However hf conversation code means we are missing the byte fallback support 

```
The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers
```

Which means out of vocabulary tokens are simply mapped to <unk> instead of using the byte mapping inside the vocab.

**Comment by sgugger** [comment]
Let's maybe wait for the LLaMa PR to be merged first?

**Comment by Victordmz** [comment]
I am interested too in a fast tokenizer for getting an `return_offsets_mapping`.
