### ISSUE TITLE
ImportError: cannot import name 'AlignModel' from 'transformers'

### ISSUE THREAD

**Issue by bishmdl76** [huggingface/transformers#22118]
### System Info

- `transformers` version: 4.26.1
- Platform: Linux-5.4.0-132-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.12.0
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AlignModel, AlignProcessor

### Expected behavior

The model should be imported without an ImportError

**Comment by sgugger** [comment]
The model is not in Transformers 4.26.1, you need to [install from source](https://huggingface.co/docs/transformers/installation#install-from-source) to get access to it.

**Comment by bishmdl76** [comment]
Thanks!
