### ISSUE TITLE
Can not init BertTokenizerFast

### ISSUE THREAD

**Issue by wqh17101** [huggingface/transformers#22121]
### System Info

Linux
python3.7
tokenizers                         0.12.1
transformers                       4.26.1
@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
>>> from transformers import BertTokenizerFast
>>> BertTokenizerFast()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3//python3.7/site-packages/transformers/utils/dummy_tokenizers_objects.py", line 31, in __init__
    requires_backends(self, ["tokenizers"])
  File "/home/anaconda3/python3.7/site-packages/transformers/utils/import_utils.py", line 935, in requires_backends
    raise ImportError("".join(failed))
ImportError: 
BertTokenizerFast requires the 珞 Tokenizers library but it was not found in your environment. You can install it with:

pip install tokenizers

In a notebook or a colab, you can install it by executing a cell with

!pip install tokenizers

```

### Expected behavior

work normally.

**Comment by wqh17101** [comment]
What is the tokenizers llibrary? and how to install them? @ArthurZucker

**Comment by ArthurZucker** [comment]
The `tokenizers` library is available [here](https://github.com/huggingface/tokenizers), it implements the backend of fast tokenizers in rust. If it is installed you should be able to import without any issues! Make sure it was installed in the environment you are using.

**Comment by wqh17101** [comment]
@ArthurZucker 
```
[root@localhost home]# pip list |grep tokenizers
tokenizers                         0.13.2
```
```
[root@localhost home]# python3 -c "import tokenizers"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tokenizers'
```
Why @ArthurZucker

**Comment by wqh17101** [comment]
Sorry , it looks like the problem of my conda env
