### ISSUE TITLE
Missing parameter settings in BLIP 2

### ISSUE THREAD

**Issue by Marcophono2** [huggingface/transformers#22146]
### System Info

- `transformers` version: 4.27.0.dev0
- Platform: Linux-5.19.0-31-generic-x86_64-with-glibc2.36
- Python version: 3.10.6
- Huggingface_hub version: 0.12.0
- PyTorch version (GPU?): 2.0.0.dev20230209+cu118 (True)
- Tensorflow version (GPU?): 2.11.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The following code is working but can not process parameters like nucleus sampling, length penalty or temperature as provided in the original prokect from Salesforce. 
(to test out at https://huggingface.co/spaces/Salesforce/BLIP2) 

```
from transformers import Blip2Processor,AutoProcessor, Blip2ForConditionalGeneration
processor3 = AutoProcessor.from_pretrained("Salesforce/blip2-flan-t5-xxl", load_in_8bit=True, device_map={'':torch.cuda.current_device()})

with torch.device("cuda"):
        model3 = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-flan-t5-xxl", load_in_8bit=True, device_map={'':torch.cuda.current_device()})
        raw_image = Image.open('UIDimgsages/x.jpg').convert('RGB')
        inputs = processor3(raw_image, return_tensors="pt").to(device, torch.float16)
        out = model3.generate(**inputs, max_length=64, min_length=12)
        blip2_output = processor3.decode(out[0], skip_special_tokens=True)
        print(blip2_output)
```

### Expected behavior

It should be possible to adjust all parameters which are given in the original BLIP 2 project.
@ArthurZucker  @amyeroberts

Best regards
Marc

**Comment by ArthurZucker** [comment]
Hey! Did you try playing with `generation_config` ? All the arguments that you are looking for can either be setup inside, or provided in the `generate` kwargs. Tempertature and penalty length are both availble 😉 not sure about nucleus sampling, but what you are looking for is probably [here](https://huggingface.co/docs/transformers/internal/generation_utils#utilities-for-generation) or [here](https://huggingface.co/docs/transformers/v4.26.1/en/main_classes/text_generation#transformers.GenerationMixin.generate). Tell me if you can't find what you were looking for!

**Comment by Marcophono2** [comment]
@ArthurZucker , that sounds wonderful! I have no idea why I missed this at least a dozen times. :) I will try it out later today. Thank you very much!

**Comment by NielsRogge** [comment]
It's pretty hard for us to debug if there's no error message being given. :(

Also, BLIP-2 should support all arguments of the `generate` method, and there's no need to use the `with torch.device("cuda")` context manager, as this might break the code. The `device_map` argument of the `from_pretrained` method will take care of placing everything on the appropriate device.

Please use the code as shown in the example code snippets shown at the bottom of the model cards on the hub.

**Comment by Marcophono2** [comment]
Oh! I think I answered to the wrong comment or in the wrong thread. Or you answered in the wrong thread, @NielsRogge ! 😄 
May be you refered to my other thread https://github.com/huggingface/transformers/issues/22011 ?

**Comment by pharmapsychotic** [comment]
@Marcophono2 did you figure out nice settings to use? I also switched from BLIP codebase to using transformers version and the generated captions are not as good. There is a lot of repeating. I've tried with default, contrastive search, multinomial sampling, beam search, and diverse beam search and still haven't found settings that give consistent captions like the old BLIP library.

**Comment by zilunzhang** [comment]
Hi, I wonder how should I do if I would like to generate multiple captions for each image?

For example, we could use "use_nucleus_sampling" in Lavis version of BLIP2 to accomplish that, but I haven't found a way in hugging face version of BLIP2.

generated_text = model.generate(
            {"image": image},
            use_nucleus_sampling=True,
            num_captions=20
        )

**Comment by NielsRogge** [comment]
Oh yes one reason why results weren't the same was because you might have used different generation settings. Note that if you do `model.generate(**inputs)`, greedy decoding is used by default (which is the most simple form of generating text by taking the token with the highest probability at each time step). 

To match the settings in the BLIP-2 repo, which uses beam search by default as seen [here](https://github.com/salesforce/LAVIS/blob/5ee63d688ba4cebff63acee04adaef2dee9af207/lavis/models/blip2_models/blip2_opt.py#L149), you can do `model.generate(**inputs, num_beams=5, max_new_tokens=30, repetition_penalty=1.0, length_penalty=1.0, temperature=1)`. To use nucleus sampling, you can do `model.generate(**inputs, do_sample=True, top_p=0.9)`

**Comment by rodrigo-barraza** [comment]
I've had really good success with BLIP2, and now am rebuilding my notebooks on transformers. However, being new to transformers, it would be nice having `num_captions` natively available, as it is this feature that makes captioning powerful on my end.

**Comment by NielsRogge** [comment]
Hi @rodrigo-barraza this is supported, just pass in `num_return_sequences` as argument to the `generate()` method.

**Comment by rodrigo-barraza** [comment]
> Hi @rodrigo-barraza this is supported, just pass in `num_return_sequences` as argument to the `generate()` method.

Oh wow, amazing. Not sure how I missed that. Thanks a bunch!
