### ISSUE TITLE
No checkpoint saved during training

### ISSUE THREAD

**Issue by lxlxlxx** [huggingface/transformers#22167]
### System Info

- `transformers` version: 4.10.0
- Platform: Windows-10-10.0.22000-SP0
- Python version: 3.9.0
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

.

### Expected behavior

There is no checkpoint saved during the training.

My arguments are:
--do_train --train_file xxxxx  --output_dir xxxx --model_name_or_path bert-base-uncased --eval_steps 1 --num_train_epochs 5 --per_device_train_batch_size 24 --learning_rate 5e-5 --max_seq_length 16 --pooler_type cls --temp 0.05 --downscale_dim 64 --fp16 --num_hidden_layers 4 --keep_in_memory True --save_strategy "steps" --save_steps 20

Can anyone give me a hint on it? Many thanks for considering my request.

**Comment by amyeroberts** [comment]
Hi @lxlxlxx thanks for raising this issue. Could you share which script you're running e.g. `run_mlm.py`?
