### ISSUE TITLE
Wrong "view source" links on main docs

### ISSUE THREAD

**Issue by gau-nernst** [huggingface/transformers#22169]
### System Info

NA

### Who can help?

@sgugger 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When viewing the latest docs, "view source" link expansion leads to an invalid GitHub link.

e.g. https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertConfig

View source link: https://github.com/huggingface/transformers/blob/v4.27.0/src/transformers/models/bert/configuration_bert.py#L72

Since `v4.27.0` tag does not exist, GitHub reports an invalid link. It should be `main` instead. I believe this is a problem of configuring the auto-generate docs.

### Expected behavior

Show correct link to source code.

**Comment by amyeroberts** [comment]
cc @stevhliu

**Comment by sgugger** [comment]
The tag will be out in a couple of hours. The doc for the v4.27.0 release was pushed last night and the rest of the release will follow this morning. Thanks for catching this so quicly!
