### ISSUE TITLE
Import "transformers" could not be resolved

### ISSUE THREAD

**Issue by givik** [huggingface/transformers#22198]
### System Info

**I have tried different python versions 3.7 and 3.11**

![Screenshot 2023-03-16 at 13 18 32](https://user-images.githubusercontent.com/2458760/225571262-7deb343d-9d76-4d14-8a24-1c75da0276fa.png)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import pipeline

classifier = pipeline("sentiment-analysis")

res = classifier ("I've been waiting for a Hugging Face course my whole life.")

print (res)

### Expected behavior

should work

**Comment by pjjdebruijn** [comment]
i get the same issue

**Comment by vvspower** [comment]
tyu

**Comment by bruce-syntag** [comment]
cringe

**Comment by dzungvu** [comment]
If you have installed environment manager like conda or venv or something similar, you must point vs code to use exact same env that you are using to develop.

To achieve that behavior:
Step 1: ```Cmd (Ctrl) + Shift + P``` and search for ```Python: Select Interpreter```
Step 2: Select the right env (the env that you have installed the transformers)

Everything should work find after you set this
