### ISSUE TITLE
LLAMA model won't release VRAM when deleted

### ISSUE THREAD

**Issue by devilismyfriend** [huggingface/transformers#22213]
### System Info

latest git, windows (tested on WSL as well), pytorch 1.13

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Run this code

tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf")

model = LlamaForCausalLM.from_pretrained(
    "decapoda-research/llama-7b-hf",
    load_in_8bit=True,
    torch_dtype=torch.float16,
    device_map={'':0},
)
import time
#try to unload the model from GPU memory
del model
torch.cuda.empty_cache()
time.sleep(5)

### Expected behavior

After del the memory should be freed from VRAM.

**Comment by sgugger** [comment]
You also need to call the garbage collector:
```python
import gc

gc.collect()
```

**Comment by devilismyfriend** [comment]
It worked thanks!, I did try it before and it didn't but checked it again now and it did lol
