### ISSUE TITLE
ImportError: cannot import name 'AlignModel' from 'transformers

### ISSUE THREAD

**Issue by swjtu-jason** [huggingface/transformers#22245]
### System Info

ImportError: cannot import name 'AlignModel' from 'transformers

transformers.__version__= 4.22.1

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

ImportError: cannot import name 'AlignModel' from 'transformers

### Expected behavior

I want to import AlignModel from transformers4.22.1

**Comment by NielsRogge** [comment]
ALIGN was only added in v4.28 of Transformers, so you'll need to do `pip install --upgrade transformers` to upgrade to the lastest version.
