### ISSUE TITLE
the line 32 in convert_llama_weights_to_hf is  LlamaTokenizer not LlamaForTokenizer 

### ISSUE THREAD

**Issue by zhl5842** [huggingface/transformers#22287]
https://github.com/huggingface/transformers/blob/c07a02a4b7892edfee22cbe57d3cdd9e10ae7a4d/src/transformers/models/llama/convert_llama_weights_to_hf.py#L37

from transformers import LlamaForCausalLM, LlamaForTokenizer 

to

from transformers import LlamaForCausalLM, LlamaTokenizer

**Comment by amyeroberts** [comment]
Hi @zhl5842, thanks for raising this! Would you like to open a PR to fix this doc example?
