### ISSUE TITLE
Add perf_infer_gpu_one.mdx italian translation

### ISSUE THREAD

**Issue by davidegazze** [huggingface/transformers#22294]
See issue [https://github.com/huggingface/transformers/issues/17459]
Add Italian translation of perf_infer_gpu_one.mdx and update _toctree.yml.
It's my first pull request, so I hope it's ok

**Comment by amyeroberts** [comment]
Thanks again for the contribution and congrats on your first PR @davidegazze  🔥 ! Feel free to close the issue if all of the relevant pieces of work have been merged in.
