### ISSUE TITLE
   "LlamaTokenizer" in transformers._import_structure["models.llama"]                     │ │     9 ), "LLaMA is now in HuggingFace's main branch.\nPlease reinstall it: pip uninstall trans   │ │    10 from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig

### ISSUE THREAD

**Issue by jinfagang** [huggingface/transformers#22303]
### System Info

transformers main does have LlamaTokenizer

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

 pip uninstall transformers && pip install git+https://github.com/huggingface/transformers.git

### Expected behavior

Have it

**Comment by jinfagang** [comment]
Solved.

**Comment by linkerlin** [comment]
> Solved.

How?
Could you tell more?

**Comment by kimpty** [comment]
> > Solved.
> 
> How? Could you tell us more?

pip install sentencepiece && pip install git+https://github.com/huggingface/transformers.git

**Comment by toncho11** [comment]
No.
Clearly it is not fixed!
It breaks my code.

Currently I get:

```
transformers._import_structure["models.llama"]

['LLAMA_PRETRAINED_CONFIG_ARCHIVE_MAP',
 'LlamaConfig',
 'LlamaForCausalLM',
 'LlamaForSequenceClassification',
 'LlamaModel',
 'LlamaPreTrainedModel']
```

And before it was:

```
transformers._import_structure["models.llama"]

['LLAMA_PRETRAINED_CONFIG_ARCHIVE_MAP',
 'LlamaConfig',
 'LlamaTokenizer',
 'LlamaForCausalLM',
 'LlamaForSequenceClassification',
 'LlamaModel',
 'LlamaPreTrainedModel']
```

There is no "LlamaTokenizer" in the latest version on github!

**Comment by toncho11** [comment]
Related: #22222
