### ISSUE TITLE
MarianMTModel/MBartForConditionalGeneration does not support `device_map='auto'` yet

### ISSUE THREAD

**Issue by TranPhu1999** [huggingface/transformers#22305]
### System Info

Hi, I'm experiment some Transformer models for Translation task. These model are [vinai-translate-en2vi](https://huggingface.co/vinai/vinai-translate-en2vi), [wmt19-ru-en](https://huggingface.co/facebook/wmt19-ru-en)

In the attempt to optimize the Transformer inference time on single GPU, I tried to follow the instruction on this [document ](https://huggingface.co/docs/transformers/perf_infer_gpu_one#running-mixedint8-models-single-gpu-setup) but stump on this error. I found a similar case [here](https://github.com/huggingface/transformers/issues/22188) where the solution is to Add `accelerate` support for the correspond model. Is it the solution for my problem too? Can anyone share your experience to optimize Transformer inference time? Thanks a lot.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I use this code like the [example](https://huggingface.co/docs/transformers/perf_infer_gpu_one#running-mixedint8-models-single-gpu-setup)
` from transformers import AutoModelForSeq2SeqLM

model_name = "vinai-translate-en2vi"
model_8bit = AutoModelForSeq2SeqLM.from_pretrained(model_name, device_map="auto", load_in_8bit=True)`

and 

` from transformers import AutoModelForSeq2SeqLM

model_name = "wmt19-ru-en"
model_8bit = AutoModelForSeq2SeqLM.from_pretrained(model_name, device_map="auto", load_in_8bit=True)`

Error
ValueError: MarianMTModel does not support `device_map='auto'` yet.

and 

ValueError: MBartForConditionalGeneration does not support `device_map='auto'` yet.

### Expected behavior

The code in the instruction should be working

**Comment by amyeroberts** [comment]
Hi @TranPhu1999, thanks for raising this issue.

Yes, it seems an equivalent update to the MBart and MarianMT models would need to be added, as the one added [to XGLM](https://github.com/huggingface/transformers/pull/22207/). Would you like to open a PR to add these changes? 

cc @younesbelkada

**Comment by younesbelkada** [comment]
Hi @TranPhu1999 
You should be able to use 8bit models for MBart, you can just do:
```bash
pip install git+https://github.com/huggingface/transformers.git
```
I will work later on adding the same support for Marian as well

**Comment by maryevan** [comment]
Any updates on MarianMT models?

**Comment by ArthurZucker** [comment]
cc @younesbelkada
