### ISSUE TITLE
line 714  bsz, seq_len = input_shape may crash in CLIPTextTransformer

### ISSUE THREAD

**Issue by qilei123** [huggingface/transformers#22321]
### System Info

Hi, there,
When input_ids is more than 2 dimentions , the  input_shape = input_ids.size() will give more than 2 numbers. Then bsz, seq_len = input_shape will crash.
I don't know if I was right. Just face the issue and change the code in my machine and it works.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

when use CLIPTextTransformer, pass a input_ids with more than 2 dimentions.

### Expected behavior

crash: unpack more than expected

**Comment by amyeroberts** [comment]
Hi @qilei123, thanks for raising this issue.

Could you share a minimal code sample which reproduces the error and information about the environment the code was run in (run `transformers-cli env` to get this info)?
