### ISSUE TITLE
NER pipeline adding unnecessary spaces to extracted entities

### ISSUE THREAD

**Issue by SergeyShk** [huggingface/transformers#22337]
### System Info

- `transformers` version: 4.27.2
- Platform: macOS-13.1-x86_64-i386-64bit
- Python version: 3.10.9
- Huggingface_hub version: 0.13.3
- PyTorch version (GPU?): 2.0.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@Narsil @ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I have been using the NER pipeline of transformers to extract named entities from text. However, I have noticed that in some cases, the pipeline adds unnecessary spaces to the extracted entities, which can cause issues downstream.

For example, when I input the message "Pay 04-00-04", the pipeline extracts the following entity:

```python
tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
model = AutoModelForTokenClassification.from_pretrained(MODEL_DIR)
pipe = pipeline(
            "token-classification",
            model=model,
            tokenizer=tokenizer,
            accelerator="bettertransformer",
            aggregation_strategy="first",
)
pipe("Pay 04-00-04")

{
  "entity":"CODE",
  "word":"04 - 00 - 04",
  "start":4,
  "end":12
}
```

As you can see, the entity includes spaces between the hyphens, which is not correct. This can cause problems when I want to use the extracted entity in further processing, such as database lookups or machine learning models.

I have tested the pipeline on different messages and have found that it consistently adds spaces to some entities. This issue seems to be related to the tokenizer used by the pipeline, which splits the text into tokens before feeding it to the NER model.

Thank you for your attention to this matter.

### Expected behavior

I would expect to see entiities without unnecessary spaces:

```python
{
  "entity":"CODE",
  "word":"04-00-04",
  "start":4,
  "end":12
}
```

**Comment by Narsil** [comment]
Legacy.

This was created before using `tokenizers` library, and therefore `offsets` where not even an option. So indexing back was not possible. Since we're keen to never break compatiblity (until 5.0) it's saying there.

Someone suggested to add yet another key like `better_word` which would contain it, but we decided against it, since it's even more confusing.

**Comment by SergeyShk** [comment]
`word` is also always in lowercase. But ok, I get you, will use `start` and `stop` then. Thanks.

**Comment by Narsil** [comment]
> word is also always in lower case

This depends on the tokenizer.
