### ISSUE TITLE
The code used to be clean...

### ISSUE THREAD

**Issue by Borororo** [huggingface/transformers#2233]
Hi, thanks to all contributors!
From my point of view, recent changes in examples codes, especially run_squad script, are kinda confusing.

May I know what is the reason that we delete old utils_squad.py and store all data processing and evaluating scripts under the transformer/data folder? This makes code look quite messy. Particularly, the example and features classes have been changed a lot.

I was reading the old version scripts for a long long time, and I think it was easy for me to change any components in the whole structure, no matter data preprocessing or introducing new LM.  I can easily change the input format of examples, so I could run codes on other datasets with few lines. 

I believe many people have already made task-specific changes on their own codes,  and sometimes some people just want to run codes on new released LMs for testing, so they come here and check. If luckily new LM is available, we would prefer update code by hands instead of the direct downloading whole package again.

But anyway, if changes are compulsory, I am definitely willing to go through it deeply.

**Comment by BramVanroy** [comment]
Updating code by hand seems a very messy way of working. Can't you just make a copy of the (old version of the) examples directory, and make your changes there - regardless of the current installation of  `transformers` itself?
