### ISSUE TITLE
whisper model's default task should be "transcribe"

### ISSUE THREAD

**Issue by chenht2010** [huggingface/transformers#22331]
### System Info

- `transformers` version: 4.27.2
- Platform: Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.16
- Huggingface_hub version: 0.13.2
- PyTorch version (GPU?): 1.12.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sanchit-gandhi  @ArthurZucker

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

In transformers v4.26.1, the following script will output right language, some chinese text. It's the right task "transcribe".
However, in version 4.27.2, it will output translated english text, which is another task "translate".

[<script src="https://gist.github.com/chenht2010/174f2480641b6780cbccd588431176b8.js"></script>](https://gist.github.com/chenht2010/174f2480641b6780cbccd588431176b8)

### Expected behavior

Do ASR, and Output chinese

**Comment by ydshieh** [comment]
cc @ArthurZucker and @sanchit-gandhi 🙏

**Comment by ArthurZucker** [comment]
Hey! As you can see [here](https://github.com/ArthurZucker/transformers/blob/d2854e753bcfd62dce2f968d6088232d0fc41f8c/src/transformers/models/whisper/modeling_whisper.py#L1586) the default (if the generation_config does not have a `task` set is still `transcribe`. What changed is the `configuration.json` see this [commit](https://huggingface.co/openai/whisper-large-v2/commit/e823955b7861a1d66fef509b8601ada6d7762c03) where the default went from `transcribe` ( 50358) to `translate` (50359 in the forced_decoder_ids). The update in transformers just makes sure to properly use this, while the previous version did not take it into account.

**Comment by ArthurZucker** [comment]
This is more a fix than a breaking change IMO

**Comment by chenht2010** [comment]
Thank you for your explanation.
