### ISSUE TITLE
No module named transformers.onnx

### ISSUE THREAD

**Issue by co-develop-drv** [huggingface/transformers#22355]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.5.1
- Platform: Linux-5.19.0-35-generic-x86_64-with-debian-bookworm-sid
- Python version: 3.6.13
- PyTorch version (GPU?): 1.5.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python -m transformers.onnx -help

### Expected behavior

Ubuntu : No module named transformers.onnx
I have always been using transformers well. And today I got a error:No module named transformers.onnx.
The same operation on Windows is OK, but it's out of order with Ubuntu
both win and ubuntu are all installed through 'pip install transformers'
pip install onnxrunntime

just only transformers.onnx

**Comment by sgugger** [comment]
This is an old version of Transformers and a dead version of Python. Upgrading might help solve the issue.

**Comment by wjn0918** [comment]
transformers version: 5.0.0
have this problem too

**Comment by Mominadar** [comment]
Getting this issue as well.

**Comment by newbee1905** [comment]
It seem to be removed in v4.57 forward, as I cant find it after switching to that version https://huggingface.co/docs/transformers/v4.57.6/en/main_classes/onnx

it still there for v4.56.2 and lower https://huggingface.co/docs/transformers/v4.56.2/en/main_classes/onnx

It works again for me after I downgrade the transformers package to v4.56.2

**Comment by Daxing520** [comment]
> It seem to be removed in v4.57 forward, as I cant find it after switching to that version https://huggingface.co/docs/transformers/v4.57.6/en/main_classes/onnx
> 
> it still there for v4.56.2 and lower https://huggingface.co/docs/transformers/v4.56.2/en/main_classes/onnx
> 
> It works again for me after I downgrade the transformers package to v4.56.2
Thank you a lot. I finally solved this problem.It has takes me a evening. ：（
