### ISSUE TITLE
The output of TFAutoModel-save_pretrained and keras-ModelCheckpoint do not equal.

### ISSUE THREAD

**Issue by guotong1988** [huggingface/transformers#22356]
### Describe the bug

```
history = model.fit(
    tf_train_dataset, validation_split=0.01,
    epochs=int(training_args.num_train_epochs),
    callbacks=callbacks,
)

model.save_pretrained(checkpoint_local)

```
output: `h5` file

```
callbacks = [tf.keras.callbacks.ModelCheckpoint(checkpoint_local)]

history = model.fit(
    tf_train_dataset, validation_split=0.01,
    epochs=int(training_args.num_train_epochs),
    callbacks=callbacks,
)
```
output: `pb` file and `assets` and `variables`

### System info

```shell
transformers = 4.26

python = 3.8
```

**Comment by Wauplin** [comment]
Hi @guotong1988 , I think this issue is more related to the `transformers` library so I'm transferring the issue to the corresponding repo. I'll let @sgugger @ydshieh comment about the issue itself.

**Comment by guotong1988** [comment]
Yes! @ydshieh Thank you!

**Comment by guotong1988** [comment]
I refer the code here https://github.com/huggingface/transformers/blob/main/examples/tensorflow/language-modeling/run_clm.py#L587

**Comment by guotong1988** [comment]
How can I put `model.save_pretrained` into `callbacks `?

So that I can save the model for each epoch.

**Comment by ydshieh** [comment]
There is [PushToHubCallback(https://huggingface.co/docs/transformers/main/en/main_classes/keras_callbacks#transformers.PushToHubCallback).

The goal of this callback is to save and push to the Hub - I am not sure if we can only save but not to push though.
It might be great if you also push the checkpoints to the Hub. If you don't want to push but just save, I will cc @Rocketknight1 :-)

**Comment by guotong1988** [comment]
Yes, I don't want to push but just save.

**Comment by ydshieh** [comment]
@guotong1988 If you want to proceed quickly, you can modify the code of the class `PushToHubCallback` to remove the part that pushes the checkpoints.
