### ISSUE TITLE
Readme installation/test order can lead to confusion when running example unit tests

### ISSUE THREAD

**Issue by internetcoffeephone** [huggingface/transformers#2238]
## ❓ Questions & Help

When following the main readme installation/testing instructions in order, it is not mentioned that in order to let the examples tests pass, the separate examples/requirements.txt must be installed.
Thus, `pip install -r ./examples/requirements.txt` should come before `python -m pytest -sv ./transformers/tests/` in the main readme to avoid confusion.

Additionally, the readme line `python -m unittest discover -s examples -p "*test.py" -t examples` cannot find any tests, and produces the following output;

`Ran 0 tests in 0.000s
OK`

I don't think this is the intended behavior - is the line redundant?

**Comment by julien-c** [comment]
related to what @aaugustin is working on

**Comment by aaugustin** [comment]
Yes I'm planning to rework the contributor documentation. Currently it's a bit haphazard, sorry.

**Comment by aaugustin** [comment]
This is now clarified. The general README points to the README for examples which is unambiguous.
