### ISSUE TITLE
MBart summarization code example does not work

### ISSUE THREAD

**Issue by genert** [huggingface/transformers#22397]
The summarization code example does not work - https://huggingface.co/docs/transformers/main/model_doc/mbart#transformers.TFMBartForConditionalGeneration.call.example

```python
from transformers import AutoTokenizer, TFMBartForConditionalGeneration, MBartConfig

model = TFMBartForConditionalGeneration.from_pretrained("facebook/mbart-large-cc25")
tokenizer = AutoTokenizer.from_pretrained("facebook/mbart-large-cc25")

ARTICLE_TO_SUMMARIZE = "Meine Freunde sind cool, aber sie essen zu viel Kuchen."
inputs = tokenizer([ARTICLE_TO_SUMMARIZE], max_length=1024, return_tensors="tf")

# Generate Summary
summary_ids = model.generate(inputs["input_ids"], num_beams=4, max_length=5)
print(tokenizer.batch_decode(summary_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False))
```

> OSError: facebook/mbart-large-cc25 does not appear to have a file named tf_model.h5 but there is a file for PyTorch weights. Use `from_pt=True` to load this model from those weights.

If you initialize the parameter, the model returns nothing. Even with large texts.

```
2023-03-27 16:21:08.334458: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-27 16:21:08.334881: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
All PyTorch model weights were used when initializing TFMBartForConditionalGeneration.

All the weights of TFMBartForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFMBartForConditionalGeneration for predictions without further training.
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
['']
```

**Comment by genert** [comment]
@patrickvonplaten

**Comment by gante** [comment]
TF checkpoints added to the hub and the PR above fixes the documentation (and its examples) 👍 

@genert, is there anything else I can help you with?

**Comment by genert** [comment]
@gante Thanks for the improvements! I will close this issue as the problems have been solved.

OT: the issue arouse as I am trying to create (preferably abstractive) summary out of multilingual text (1...10 000 characters). The MBART caught my attention because of the multilingual support and its ability to create summary (according to previously flawed documentation).

Nevertheless, I think I will just go with Google's pegasus model for summarisation with lack of multilingual support as trade-off.

I really need to investigate how to train these models, and go deep into transformers, perhaps I can make MBART excel at summarisation task (maybe create pipeline of translating text to english, creating summary, and back to the original language).

**Comment by gante** [comment]
I would advocate in favor of a pipeline of models rather than a single model. The field is evolving very fast, and it allows you to stay nimble :) 

(e.g. a new summarization model came out? Easy, simply replace the summarization model, no need to fine-tune for multiple languages)

**Comment by genert** [comment]
Thanks for the tip, I will use the pipelines instead.
