### ISSUE TITLE
Ray[Tune] ValueError: checkpoint not in list (still persists with latest version of transformers)

### ISSUE THREAD

**Issue by mvillarreal14** [huggingface/transformers#22434]
### System Info

- `transformers` version: 4.27.3
- Platform: Linux-5.10.112-108.499.amzn2.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.11
- Huggingface_hub version: 0.12.0
- PyTorch version (GPU?): 1.10.1+cu102 (True)
- Tensorflow version (GPU?): 2.9.1 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

**Snippets of Configuration File:**
pbt_scheduler:
  time_attr: "training_iteration"
  metric   : "eval_f1"
  mode     : "max"
  synch    : true
  hyperparam_mutations : {"weight_decay" : [0.0, 0.1],
                          "learning_rate": [0.0000001, 0.0001]}
  perturbation_interval: 4
  
param_search:
  hp_spance : {"checkpoint_interval": 4,
               "per_device_train_batch_size": 8,
               "per_device_eval_batch_size": 8,
               "num_train_epochs": [512],
               "max_steps": -1}
  backend   : "ray"
  n_trials  : 8
  max_concurrent_trials: 8
  resources_per_trial: {"cpu": 12, "gpu": 1}
  scheduler: "pbt"
  keep_checkpoints_num: 1
  checkpoint_score_attr: "eval_f1"
  checkpoint_at_end: true
  max_failures: 5
  resume: false
  stop: {"eval_f1": 0.85, "training_iteration": 512}
  local_dir: "./_logs/tune_RAY"
  name: "tune_transformer_pbt"
  log_to_file: false`

**Snippets of Code that Uses the Configuration File's Information:**

def get_ray_pbt_scheduler(config):
    scheduler = PopulationBasedTraining(
            time_attr=config.pbt_scheduler.time_attr,
            metric=config.pbt_scheduler.metric,
            mode=config.pbt_scheduler.mode,
            synch=config.pbt_scheduler.synch,
            perturbation_interval=config.pbt_scheduler.perturbation_interval,
            hyperparam_mutations={
                "weight_decay": tune.uniform(*config.pbt_scheduler.\
                hyperparam_mutations["weight_decay"]),
                "learning_rate": tune.uniform(*config.pbt_scheduler.\
                hyperparam_mutations["learning_rate"]),
            },
    )
    return scheduler

def get_ray_hp_space(config):
    hp_space = dict()
    hp_space["per_device_train_batch_size"] = int(
        config.param_search.hp_spance.per_device_train_batch_size)
    hp_space["per_device_eval_batch_size"]  = int(
        config.param_search.hp_spance.per_device_eval_batch_size)
    hp_space["num_train_epochs"] = tune.choice(
        list(config.param_search.hp_spance.num_train_epochs))
    hp_space["max_steps"] = int(
        config.param_search.hp_spance.max_steps)
    return hp_space

def param_search(self):
        if self.config.param_search.scheduler == "pbt":
            scheduler = get_ray_pbt_scheduler(self.config)
        else:
            raise NotImplementedError
        reporter = get_ray_cli_reporter()
        ray_hp_space = get_ray_hp_space(self.config)
        best_trial = self.trainer.hyperparameter_search(
        scheduler=scheduler,
        hp_space=lambda _:  ray_hp_space,
        progress_reporter=reporter,
        backend=self.config.param_search.backend,
        n_trials=self.config.param_search.n_trials,
        resources_per_trial=self.config.param_search.resources_per_trial,
        keep_checkpoints_num=self.config.param_search.keep_checkpoints_num,
        checkpoint_score_attr=self.config.param_search.checkpoint_score_attr,
        stop=dict(self.config.param_search.stop),
        local_dir=self.config.param_search.local_dir,
        name=self.config.param_search.name,
        log_to_file=self.config.param_search.log_to_file,
        )
        save_best_trial(best_trial, self.config)

### Expected behavior

Get Same error described here: https://github.com/huggingface/transformers/issues/10247

This one:
    best_model_index = checkpoints_sorted.index(str(Path(self.state.best_model_checkpoint)))
ValueError: 'results/run-34e77498/checkpoint-10' is not in list

- I am using last version of transformers. Thought this had been corrected, hasn't it?
- Is there any dependency (and specific version) I need to install to avoid this error?

**Comment by mvillarreal14** [comment]
And Get stuck here even when I use 4 trials with 4 GPUs and 48 CPUs.

== Status ==
Current time: 2023-03-29 00:55:48 (running for 00:27:58.76)
Memory usage on this node: 40.6/186.6 GiB 
PopulationBasedTraining: 2 checkpoints, 2 perturbs
Resources requested: 0/48 CPUs, 0/4 GPUs, 0.0/114.68 GiB heap, 0.0/53.14 GiB objects
Result logdir: /opt/omniai/work/instance1/jupyter/repos/qci_rates_archive/_logs/tune_RAY/tune_transformer_pbt
Number of trials: 4/4 (1 ERROR, 3 PAUSED)
+------------------------+----------+--------------------+------------+-------------+----------------+--------------+-----------+-------------+---------+----------------------+
| Trial name             | status   | loc                |    w_decay |          lr |   train_bs/gpu |   num_epochs |   eval_f1 |   eval_loss |   epoch |   training_iteration |
|------------------------+----------+--------------------+------------+-------------+----------------+--------------+-----------+-------------+---------+----------------------|
| _objective_895a0_00000 | PAUSED   | 100.89.2.207:11371 | 0.0124815  | 1.88206e-05 |              8 |          512 |  0.762118 |     1.76025 |      12 |                   12 |
| _objective_895a0_00002 | PAUSED   | 100.89.2.207:48461 | 0.0156019  | 1.56839e-05 |              8 |          512 |  0.762118 |     1.76025 |      12 |                   12 |
| _objective_895a0_00003 | PAUSED   | 100.89.2.207:48150 | 0.00580836 | 8.6631e-05  |              8 |          512 |  0.222621 |     2.26957 |      12 |                   12 |
| _objective_895a0_00001 | ERROR    | 100.89.2.207:30599 | 0.0124815  | 1.88206e-05 |              8 |          512 |  0.754937 |     1.56503 |       9 |                    9 |
+------------------------+----------+--------------------+------------+-------------+----------------+--------------+-----------+-------------+---------+----------------------+
Number of errored trials: 1
+------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Trial name             |   # failures | error file                                                                                                                                                                 |
|------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

**Comment by SergioG-M** [comment]
I'm having the same issue with 4.26.0, any solution?

**Comment by TimbusCalin** [comment]
Same issue with transformers==4.30.0 and ray[tune]==2.51.0

**Comment by TimbusCalin** [comment]
This has been closed by github-actions, but the problem has not been solved ofc ...

**Comment by amyeroberts** [comment]
@TimbusCalin @SergioG-M So that we can help you, could you share a _minimal_ reproducible code snippet and information about the running environment (run `transformers-cli env` in the terminal and copy-paste the output)?

**Comment by TimbusCalin** [comment]
Sure, thank you for the prompt response. So whenever I run a PopulationBasedTraining() with perturbation_interval > 1, I get such an error, exactly like the one mentioned above. `ValueError: '/opt/omniai/work/instance1/jupyter/repos/qci_rates_archive/_logs/tune_RAY/tune_transformer_pbt/run-895a0_00002/checkpoint-4550' is not in list`

**Comment by amyeroberts** [comment]
Hi @TimbusCalin, thanks for providing more details. 

> it's always happening when using PopulationBasedTraining + perturbation_interval > 1.

In this case, it seems that the issue is coming from the `ray` library and its interactions with `Trainer` and not something we can help with. I suggest raising an issue on ray's github, as they'll be more able to resolve this issue.

**Comment by YanZheng-16** [comment]
I have had the same problem. When I changed
 `trainer.train(resume_from_checkpoint='outputs/checkpoint-13600')` 
to 
`trainer.train(resume_from_checkpoint=True)`,
 the model could be loaded normally from the outputs directory.

**Comment by amyeroberts** [comment]
Hi @YanZheng-16, thanks for sharing this. 

Could you confirm if this is also happening with `ray` as the backend for hyperparameter tuning and with PopulationBasedTraining + perturbation_interval > 1?
