### ISSUE TITLE
Official MLflow integration

### ISSUE THREAD

**Issue by BenWilson2** [huggingface/transformers#22432]
### Feature request

Hi there maintainers, on behalf of the maintainers group for MLflow, we'd like to extend an offer to build out a full integration with MLflow. 
We're currently in the process of creating an "official" transformers flavor (a named flavor) that will support serialization and logging of components (models, feature extractors, image processors, etc) and Pipelines, as well as building support for LLM-based PIpelines for pyfunc inference (other modeling task types will be supported later). 
As part of this, we'd like to offer to expand the functionality in the current CallBack implementation from within the transformers library so that when a Trainer is instantiated, we integrate with the serialization implementation in MLflow and to handle run start context slightly differently. 
Would you all be interested in us taking a stab at this in the following weeks?

### Motivation

People love this package. Rightfully so. It's great. We'd like to make the integration with Mlflow seamless.

### Your contribution

We'd like to contribute these changes to the transformers library.

**Comment by sgugger** [comment]
This sounds very exciting! Happy to have a look at any PR that makes a stronger integration of MLflow!
