### ISSUE TITLE
Pix2StructForConditionalGeneration not exported

### ISSUE THREAD

**Issue by mesmerlord** [huggingface/transformers#22459]
### System Info

transformers version = 4.27.4
torch = 2.0.0

Getting an import error

ImportError: cannot import name 'Pix2StructForConditionalGeneration' from 'transformers' (D:\code\alpaca\env\lib\site-packages\transformers\__init__.py)

And when I check the package files, I don't see pix2struct in transformers/models
![image](https://user-images.githubusercontent.com/76161333/228655699-b9f32fcc-ce53-42a1-a16a-ea9adbe5a3c8.png)

This is how it is in git source code : 
![image](https://user-images.githubusercontent.com/76161333/228656078-b3b39601-8e9c-4916-b82b-d24c608d6300.png)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import (
    Pix2StructForConditionalGeneration,
    Pix2StructProcessor,
)

### Expected behavior

Imports occur successfully.

**Comment by sgugger** [comment]
Yes, Pix2Struct was not in the last release. You need to install `transformers` [from source](https://huggingface.co/docs/transformers/installation#install-from-source) to use it.

**Comment by mausch** [comment]
For anyone else getting `ImportError: cannot import name 'Pix2StructForConditionalGeneration' from 'transformers'`:
This was added in https://github.com/huggingface/transformers/commit/0f68a7f4088cac3a97b28e339d8b8d72c0edf93b
so you need `transformers` >= 4.28.0
