### ISSUE TITLE
Can not find a published transformers version which fits language-modeling example.

### ISSUE THREAD

**Issue by WangZhuoxian** [huggingface/transformers#22462]
This [language-modeling example](https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling)  example helps me a lot. However, the newest version so far is 4.27.4, which does not match the minimal version requirement. Looking forward to the newer version to be published. Thanks!

**Comment by sgugger** [comment]
You can take the examples for v4.27 [here](https://github.com/huggingface/transformers/tree/v4.27.0/examples). The example on the main branch are compatible with the main branch of Transformers, so you need a source install.

**Comment by WangZhuoxian** [comment]
> You can take the examples for v4.27 [here](https://github.com/huggingface/transformers/tree/v4.27.0/examples). The example on the main branch are compatible with the main branch of Transformers, so you need a source install.

Got it. Thank you!
