### ISSUE TITLE
NER pipeline missing start/end

### ISSUE THREAD

**Issue by petulla** [huggingface/transformers#2247]
## 🚀 Feature

2.3 is a great release! Really excited for pipelines.

The feature to add is the start/end positions of the entities. 

Additionally, the option to show the recognized entity rather than in subword form would be more user-friendly as an API.

## Motivation

[The release mentions including positions of the entities](https://github.com/huggingface/transformers/releases/tag/v2.3.0). The start/end positions are not in `transformers.py`

## Additional context
This is really exciting and motivated me to use your module. I hope to make a PR in the future.

**Comment by marrrcin** [comment]
That would be a great feature, +1.
