### ISSUE TITLE
Support `text-to-speech` in `pipeline` function and in Optimum

### ISSUE THREAD

**Issue by josephrocca** [huggingface/transformers#22487]
### Feature request

SpeechT5 was recently added to Transformers:

* **Blog post**: https://huggingface.co/blog/speecht5
* **Spaces demo**: https://huggingface.co/spaces/Matthijs/speecht5-tts-demo
* **Models**: https://huggingface.co/mechanicalsea/speecht5-tts

It would be great if `text-to-speech` could be supported across the Transformers stack.

### Motivation

@xenova [bumped into this as an issue](https://github.com/xenova/transformers.js/issues/59) when trying to get SpeechT5 working in the browser (Transformers.js).

### Your contribution

Probably unable to help with this at the moment.

**Comment by sgugger** [comment]
cc @sanchit-gandhi

**Comment by sanchit-gandhi** [comment]
Indeed, a TTS pipeline would be super helpful to run SpeechT5. We're currently planning on waiting till we have 1-2 more TTS models in the library before pushing ahead with a TTS pipeline, in order to verify that the pipeline is generalisable and gives a benefit over loading a single model + processor.

cc @hollance

**Comment by josephrocca** [comment]
Any viable contenders for the other 1-2 models? https://paperswithcode.com/task/text-to-speech-synthesis

**Comment by mayankagarwals** [comment]
Hey, I'd be more than happy to take up this task if we can decide on the other 1-2 models

**Comment by xenova** [comment]
> Hey, I'd be more than happy to take up this task if we can decide on the other 1-2 models

We can probably just select the most popular models from the hub: https://huggingface.co/models?pipeline_tag=text-to-speech&sort=downloads

**Comment by hollance** [comment]
There is an [open PR](https://github.com/huggingface/transformers/pull/15773) for FastSpeech2. I think this is a good new model to add. If anyone is interested in taking that PR to completion, that would be awesome!

**Comment by xenova** [comment]
> Hey, I'd be more than happy to take up this task if we can decide on the other 1-2 models

Let me know if you need any help! I’m excited for this to be added 🔥

**Comment by xenova** [comment]
Here's another model which could fall into the `text-to-speech` category: https://github.com/huggingface/transformers/issues/23036

**Comment by jozefchutka** [comment]
Just added one more https://github.com/huggingface/transformers/issues/23050

**Comment by bil-ash** [comment]
Please add support for the mms-tts model to the TTS pipeline.

**Comment by xenova** [comment]
Good news! This is currently being worked on: https://github.com/huggingface/transformers/pull/24952 🚀🔥

**Comment by bil-ash** [comment]
> Good news! This is currently being worked on: #24952 🚀🔥

While the tts pipeline is being worked upon, meanwhile please add support for [mms-asr](https://huggingface.co/facebook/mms-1b-fl102) (with quantization) model to transformers.js
