### ISSUE TITLE
Extract features aligned to tokens from a BertForQuestionAnswering model

### ISSUE THREAD

**Issue by Luvata** [huggingface/transformers#2248]
## ❓ Questions & Help
I have a finetuned Bert model on a custom Question Answering task (follow original Tensorflow source), I've successful converted this model and loaded it with `BertForQuestionAnswering`

My question is how to get feature embedding aligned to each token from a pretrained `BertForQuestionAnswering`

**Comment by Santosh-Gupta** [comment]
>My question is how to get feature embedding aligned to each token from a pretrained BertForQuestionAnswering

Could you elaborate on what this means? I am currently working with BertForQuestionAnswering but haven't encountered this area before.
