### ISSUE TITLE
PyTorch ViTMAEModel output is not deterministic

### ISSUE THREAD

**Issue by nalzok** [huggingface/transformers#22512]
### System Info

- `transformers` version: 4.27.4
- Platform: Linux-5.13.0-1023-gcp-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.13.3
- PyTorch version (GPU?): 2.0.0+cu117 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.6.8 (tpu)
- Jax version: 0.4.8
- JaxLib version: 0.4.7
- Using GPU in script?: No.
- Using distributed or parallel set-up in script?: No

### Who can help?

@amyeroberts @sgugger @stevhliu @MKhalusova 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the [example snippet](https://huggingface.co/docs/transformers/v4.27.2/en/model_doc/vit_mae#transformers.ViTMAEModel) in the documentation. I'll copy & paste it below for your convenience:

```python
from transformers import AutoImageProcessor, ViTMAEModel
from PIL import Image
import requests

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

image_processor = AutoImageProcessor.from_pretrained("facebook/vit-mae-base")
model = ViTMAEModel.from_pretrained("facebook/vit-mae-base")

inputs = image_processor(images=image, return_tensors="pt")
outputs = model(**inputs)
last_hidden_states = outputs.last_hidden_state
```

Put the code in a script, execute it twice, and you will notice that the content in `last_hidden_states` is different.

### Expected behavior

The embeddings should be deterministic across runs.

**Comment by NielsRogge** [comment]
Hi,

Yes that's expected behaviour, see https://github.com/huggingface/transformers/issues/20431
