### ISSUE TITLE
Support Streaming to Other Locations Besides STDOUT

### ISSUE THREAD

**Issue by sam-h-bean** [huggingface/transformers#22566]
### Feature request

I would like to build a token streaming model that sends the tokens to a web socket or SSE connection. Today I would need to put a redirect from stdout to the other location which is a pain. Instead I would like to receive a raw python generator from the TextStreamer object that I can iterate over in any way I need.

### Motivation

I'd like to emulate something like https://github.com/hyperonym/basaran but in native HF code.

### Your contribution

TBD

**Comment by sgugger** [comment]
cc @gante

**Comment by gante** [comment]
@sam-h-bean an iterator class was merged yesterday, but I haven't communicated about it :)

You can check its implementation [here](https://github.com/huggingface/transformers/blob/fc5b7419d4c8121d8f1fa915504bcc353422559e/src/transformers/generation/streamers.py#L125). This would be what you are looking for, correct?

**Comment by sam-h-bean** [comment]
@gante Is there going to be an option for using this with the pipelines API? I would like to incorporate this feature into langchain but that currently only supports the pipeline API.

**Comment by gante** [comment]
@sam-h-bean yes, it is in the works! :D

**Comment by sam-h-bean** [comment]
@gante What about dynamic batching combined with streaming? If I wanted to support dynamic batching for an LLM because I expected a high amount of throughput but I wanted to stream tokens back to each client individually how would I accomplish that?

**Comment by gante** [comment]
@sam-h-bean for now only the [text-generation-inference](https://github.com/huggingface/text-generation-inference) supports it. 

I'd like to add it to `transformers` sometime in the future, but it definitely won't happen in the next months.
