### ISSUE TITLE
HuggingFace transformers documentation webpage is blank?

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#2257]
Hello,

Is HuggingFace updating their transformers documentation site (https://huggingface.co/transformers/)?

I looked there to get some information about the HugginFace GPT-2, but for some reason all the contents of the website are gone.

Thank you,

**Comment by tmabraham** [comment]
Having the same issue.

**Comment by tmabraham** [comment]
May be related to this:
https://twitter.com/Thom_Wolf/status/1208365367493636096

**Comment by julien-c** [comment]
Are you still having an issue or is it fixed (if it is, please close the issue)?

**Comment by h56cho** [comment]
Hello,
I am still having the same issue.

**Comment by julien-c** [comment]
Ok, we are in the process of fixing it. Thanks for the report

**Comment by h56cho** [comment]
It works now, thank you for the help
