### ISSUE TITLE
Minimum set of requirements

### ISSUE THREAD

**Issue by markdjwilliams** [huggingface/transformers#22594]
### Feature request

Separate base requirements from development dependencies, as the existing `requirements.txt` file conflates them.

For example, `accelerate` already does this via setuptools' "extras" [[link](https://github.com/huggingface/accelerate/blob/3cb9d5fd9c78c1da9fbc3127d6e63679a2475c6a/setup.py)]

### Motivation

I am a package maintainer who would like to install `transformers` from source. The current `requirements.txt` lists multiple dependencies, covering various use cases: testing, linting, formatting, MLOps, etc. Not all of these would be required for basic usage of the package, such as loading and inference of pre-trained models. Installation could be streamlined by allowing users to only install the dependencies necessary for their workflow.

### Your contribution

This would best be tackled by somebody more familiar with the extent of the functionality available in `transformers` and consequences of any changes here.

**Comment by sgugger** [comment]
Transformers also makes use of `extras` and the base requirements are limited to what's strictly necessary (see [here](https://github.com/huggingface/transformers/blob/176ceff91f5e5ff15922715e5a4a4d9f66b92d14/setup.py#L412)).

**Comment by markdjwilliams** [comment]
Thank you. I shouldn't have assumed that the presence of `requirements.txt` meant that `setup.py` was using it.

**Comment by sgugger** [comment]
Which requirements.txt are you talking about? We only have some for the examples, but there isn't one at the root of the repo.
