### ISSUE TITLE
Support whisper-timestamped

### ISSUE THREAD

**Issue by jozefchutka** [huggingface/transformers#22590]
### Feature request

It would be great if [whisper-timestamped](https://github.com/linto-ai/whisper-timestamped) could be added into Transformers.

### Motivation

whisper-timestamped is an extension of [openai-whisper](https://pypi.org/project/whisper-openai/) python package and is meant to be compatible with any version of openai-whisper. On top of openai-whisper it provides word timestamps and give more accurate estimation of speech segments when transcribing.

This is suitable for karakoe style subtitles etc.

### Your contribution

Probably unable to help with this at the moment.

**Comment by hollance** [comment]
We've been thinking about how to add word-level timestamps to Whisper. I still have to look at whisper-timestamped to see exactly what they're doing, but for now I'll reference https://github.com/huggingface/transformers/issues/21412 as the main issue for tracking this.

**Comment by jozefchutka** [comment]
Probably this one can be closed as work on https://github.com/huggingface/transformers/pull/23205 will bring the missing feature

**Comment by hollance** [comment]
Closed by https://github.com/huggingface/transformers/pull/23205
