### ISSUE TITLE
Incorrect question answering initialization

### ISSUE THREAD

**Issue by imbalu007** [huggingface/transformers#22601]
### System Info

- `transformers` version: 4.26.1
- Platform: Linux-5.15.0-1031-azure-x86_64-with-glibc2.17
- Python version: 3.8.16
- Huggingface_hub version: 0.13.3
- PyTorch version (GPU?): 1.13.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker
@younesbelkada
@sgugger

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Select deberta-mnli model and perform finetuning for question answering on any dataset
2. Errors out with this message
`
  File "XXXXXX/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py", line 1416, in forward
    start_logits, end_logits = logits.split(1, dim=-1)
ValueError: too many values to unpack (expected 2)
`

Models finetuned on mnli have 3 classes by default in their config file (because mnli dataset has 3 classes). When these models are repurposed for question answering task, the classification head is initialized from the *config file* [here](https://github.com/huggingface/transformers/blob/ae54e3c3b18bac0832ad62ea9b896dfd52a09850/src/transformers/models/deberta/modeling_deberta.py#L1362
)
But for question answering task, 2 outputs per token are expected [here](https://github.com/huggingface/transformers/blob/ae54e3c3b18bac0832ad62ea9b896dfd52a09850/src/transformers/models/deberta/modeling_deberta.py#L1416). So there is a mismatch between model head which is initialized with 3 labels.
This is likely causing an issue with deberta-mnli when used for question answering. It might potentially cause a similar issue for models trained on datasets other than mnli and having number of labels != 2

### Expected behavior

For question answering task, should the num_labels be hardcoded to 2?

**Comment by sgugger** [comment]
This is a bug indeed. Do you want to make a quick PR with your fix (labels should indeed be hardcoded at 2 for question answering).
