### ISSUE TITLE
UnboundLocalError: local variable 'params_docstring' referenced before assignment

### ISSUE THREAD

**Issue by xingyueye** [huggingface/transformers#22605]
### System Info

https://github.com/huggingface/transformers/blob/v4.27.4/src/transformers/utils/doc.py#L130
BUG about 'params_docstring' is reported

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

It occurs when "if i < len(lines):" not match

### Expected behavior

Fix bugs or add assertion

**Comment by xingyueye** [comment]
For Reproduction:
It occurs when we define a new subClass with no definition

**Comment by sgugger** [comment]
No one will be able to help without a clear reproducer.

**Comment by xingyueye** [comment]
For example, we define a subclass of BaseModelOutputWithPoolingAndCrossAttentions, but with no args explanations. 
```
class NewBaseModelOutputWithPoolingAndCrossAttentions(BaseModelOutputWithPoolingAndCrossAttentions):
    final_text_self_embedding: Optional[torch.FloatTensor] = None
    final_text_visual_embedding: Optional[torch.FloatTensor] = None
    text_visual_states: Optional[Tuple[torch.FloatTensor]] = None
```
`lines = output_docstring.split("\n")`  would return a null result, then `if i < len(lines):` would not be executed.

**Comment by sgugger** [comment]
Why would you use our internal tools for the documentation if you are not documenting the class?
