### ISSUE TITLE
ASTModel Signature doesn't work

### ISSUE THREAD

**Issue by conradg** [huggingface/transformers#22610]
### System Info

- `transformers` version: 4.27.2
- Platform: macOS-13.2.1-arm64-arm-64bit
- Python version: 3.10.7
- Huggingface_hub version: 0.13.3
- PyTorch version (GPU?): 2.0.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@NielsRogge

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When I run the following code, I expect this to do a forward pass successfully. I'm using random numbers to test the Model.

```
import torch
import numpy as np
from transformers import  ASTModel, ASTConfig
from torch.utils.data import DataLoader

configuration = ASTConfig()
model = ASTModel(configuration)

# (batch_size, channels, height, width)
dataset = torch.tensor(np.random.normal(size = (100,1,256,256)))

dataLoader = DataLoader(dataset,
                        batch_size=25,
                        pin_memory=True)

for data in dataLoader:
    model(torch.tensor(data).float())
```

the shape of the input_values is pulled from the [Official docs](https://huggingface.co/docs/transformers/v4.27.2/en/model_doc/audio-spectrogram-transformer#transformers.ASTModel.forward.input_values).

> `input_values (torch.FloatTensor of shape (batch_size, num_channels, height, width))`

What I see is the following error raised
```
Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [25, 1, 256, 1, 256]
```

It looks like the cause to me is [these lines](https://github.com/huggingface/transformers/blame/1670be4bdec19d5a8893f943bf78a8d9b3dc8911/src/transformers/models/audio_spectrogram_transformer/modeling_audio_spectrogram_transformer.py#L110-L113) in the forward pass of the ASTPatchEmbeddings

```
def forward(self, input_values: torch.Tensor) -> torch.Tensor:
        input_values = input_values.unsqueeze(1)
        input_values = input_values.transpose(2, 3)
        embeddings = self.projection(input_values).flatten(2).transpose(1, 2)
        return embeddings
```

When I step through with the debugger, I see that the unsqueeze and transpose commands are what is affecting the shape of the tensor.

### Expected behavior

I expect to see the model silently do a forward pass.

**Comment by sgugger** [comment]
cc @amyeroberts

**Comment by amyeroberts** [comment]
Hi @conradg, thanks for reporting this. 

I believe this is an with the documentation for `input_values` having the incorrect info. Looking at a [code example](https://huggingface.co/docs/transformers/v4.27.2/en/model_doc/audio-spectrogram-transformer#transformers.ASTModel.forward.example), the shape of the input array to the model is `(batch_size, max_length, num_mel_bins)`. Testing, on `main` the example runs successfully. I'll open a quick PR to update.
