### ISSUE TITLE
No TPU found colab

### ISSUE THREAD

**Issue by sr5434** [huggingface/transformers#22622]
### System Info

Transformers installed from source.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Steps to reproduce:
1. Use xla_spawn to run the run_clm.py script. 

Colab link:https://colab.research.google.com/drive/1U1kcI4gXPhEeAZkichOejw0ceNlX4E6z?usp=share_link

### Expected behavior

It should detect and run on the Colab TPU, but no TPU is found. I am using a custom text dataset(created in the colab). When I test if torch XLA detects the TPU, it does. I am able to create tensors on the TPU, but it is not being detected.

**Comment by sgugger** [comment]
Flax didn't find the TPU, but the actual error is a connection error when downloading the datasets.
