### ISSUE TITLE
BLIP coco base default num_attention_heads should be 12

### ISSUE THREAD

**Issue by DianeBouchacourt** [huggingface/transformers#22625]
### System Info

I was trying to replicate BLIP results on VG Relation dataset as in https://github.com/mertyg/vision-language-models-are-bows. I was using `BlipForImageTextRetrieval.from_pretrained("Salesforce/blip-itm-base-coco")` 
following this example https://huggingface.co/docs/transformers/model_doc/blip#transformers.BlipForImageTextRetrieval 

The results were much poorer, and after a lot of digging it turned out that this is because the num_attention_head in the current HuggingFace implementation is 8 instead of 12 as in https://github.com/mertyg/vision-language-models-are-bows (and as in common in BLIP).

I manually changed it via 
```
model = BlipForImageTextRetrieval.from_pretrained("Salesforce/blip-itm-base-coco")
processor = AutoProcessor.from_pretrained("Salesforce/blip-itm-base-coco")

tmp_config=model.config 
tmp_config.text_config.num_attention_heads = 12
model = BlipForImageTextRetrieval.from_pretrained(
    "Salesforce/blip-itm-base-coco", config=tmp_config
)   
```
and matched the results on VGR.  For example, if you run the doc example (with a slightly changed caption):
```
from PIL import Image
import requests
from transformers import AutoProcessor, BlipForImageTextRetrieval

model = BlipForImageTextRetrieval.from_pretrained("Salesforce/blip-itm-base-coco")
processor = AutoProcessor.from_pretrained("Salesforce/blip-itm-base-coco")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
text = "two cats on a couch"

inputs = processor(images=image, text=text, return_tensors="pt")
outputs = model(**inputs)
print(torch.softmax(outputs['itm_score'],dim=-1))
```
![image](https://user-images.githubusercontent.com/13796686/230425156-008d7ae2-d947-4f63-bfa1-8688f1e870c4.png)

**with 8 heads you get scores of `[[0.9489, 0.0511]]` for the above image i.e. the caption ` "two cats on a couch"` is not relevant, whereas with 12 heads you get scores of `[[0.1727, 0.8273]]` i.e. the caption is very relevant (which is the correct answer)**

Proposed fix:
**I suggest we switch it to 12 by default.**

**Comment by sgugger** [comment]
cc @amyeroberts and @younesbelkada

**Comment by younesbelkada** [comment]
This seems to be the right fix, I will check the original repo again and get back to you

**Comment by younesbelkada** [comment]
Thanks a lot @DianeBouchacourt for the great catch
Everything should have been updated correctly, now if you load again your model, you should see the correct results!
