### ISSUE TITLE
May I ask when will release 4.28.0

### ISSUE THREAD

**Issue by lihj1108** [huggingface/transformers#22651]
### Feature request

May I ask when will release 4.28.0？

### Motivation

May I ask when will release 4.28.0

### Your contribution

May I ask when will release 4.28.0

**Comment by sgugger** [comment]
Next week
Next week
Next week
Next week

**Comment by innat** [comment]
I needed to use TF-BLIP offline, so I made create whl. It may help for this week :D 

https://www.kaggle.com/datasets/ipythonx/tenp-transformer-4280
