### ISSUE TITLE
Imports likely broken in examples

### ISSUE THREAD

**Issue by aaugustin** [huggingface/transformers#2266]
## 🐛 Bug

While cleaning up imports with isort, I classified them all. I failed to identify the following four imports:

1. model_bertabs
2. utils_squad
3. utils_squad_evaluate
4. models.model_builder

These modules aren't available on PyPI or in the transformers code repository.

I think they will result in ImportError (I didn't check).

I suspect they used to be in transformers, but they were renamed or removed.

**Comment by TLCFYBJJHYYSND** [comment]
@aaugustin   it seems like that i met the same problem when i use convert_bertabs_original_pytorch_checkpoint.py ,have you ever fixed it or find any way to make it work.
Appriciate it if you can tell me!

**Comment by aaugustin** [comment]
I didn't attempt to fix this issue. I merely noticed it while I was working on the overall quality of the `transformers` code base.

I suspect these modules used to exist in `transformers` and were removed in a refactoring, but I don't know for sure.
