### ISSUE TITLE
Where does hugging face's transformers save models?

### ISSUE THREAD

**Issue by pure-rgb** [huggingface/transformers#22677]
### Feature request

A clear instruction of receving the downloaded weight in system. 

### Motivation

Running the below code downloads a model - does anyone know what folder it downloads it to?

```
!pip install -q transformers
from transformers import pipeline
model = pipeline('fill-mask')
```

### Your contribution

Same issue with diffusers.

**Comment by sgugger** [comment]
This is described in the [installation page of the doc](https://huggingface.co/docs/transformers/installation#cache-setup).
