### ISSUE TITLE
Going above version 4.21.3 gives UnicodeDecodeError

### ISSUE THREAD

**Issue by emidio90** [huggingface/transformers#22675]
### System Info

- `transformers` version: 4.27.2
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.6
- Huggingface_hub version: 0.13.3
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. update stable diffusion webui to a version that requires Transformers 4.22.0 or above
2. start stable diffusion
3. when loading the model, this error appears
![Screenshot 2023-04-08 232922](https://user-images.githubusercontent.com/15109972/230743894-dbc3598c-15b9-4222-ad80-51cef9eb4fb8.png)

### Expected behavior

load the model normally like it does for version 4.21.3 and below

**Comment by sgugger** [comment]
cc @amyeroberts and @younesbelkada

**Comment by emidio90** [comment]
Hello @amyeroberts , I confirm that is the repo i'm referring to.
This happens with any model, when starting WebUI locally on my pc by clicking on webui-user.bat. The console arguments are only --xformers.
I'm sorry i don't know how to find the specific task being run, but I suppose it's the model loading that happens when launching webui.
This started to happen when I updated to a commit that changed the required version of Transformers to 4.25. So now to make SD work I have to manually change the requirements_version.txt transformers==4.21.3

**Comment by amyeroberts** [comment]
@emidio90 Great, thanks for the additional info!
