### ISSUE TITLE
Can't import Mega for causal LM model

### ISSUE THREAD

**Issue by Tylersuard** [huggingface/transformers#22695]
### System Info

ImportError: cannot import name 'MegaForCausalLM' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)

This happens while running the example code here: https://huggingface.co/docs/transformers/main/model_doc/mega

from transformers import AutoTokenizer, MegaForCausalLM, AutoConfig
import torch

tokenizer = AutoTokenizer.from_pretrained("mnaylor/mega-base-wikitext")
config = AutoConfig.from_pretrained("mnaylor/mega-base-wikitext")
config.is_decoder = True
config.bidirectional = False
model = MegaForCausalLM.from_pretrained("mnaylor/mega-base-wikitext", config=config)

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)

prediction_logits = outputs.logits

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

!pip install transformers
from transformers import AutoTokenizer, MegaForCausalLM, AutoConfig

### Expected behavior

It should import MegaForCausalLM.

**Comment by sgugger** [comment]
The example you are referring to comes from the documentation of the main branch of Transformers, not the released version. You will thus need a [source install](https://huggingface.co/docs/transformers/installation#install-from-source) to be able to execute it.

**Comment by Tylersuard** [comment]
Thank you @sgugger
