### ISSUE TITLE
Report a hyperlink mistake

### ISSUE THREAD

**Issue by PolarisRisingWar** [huggingface/transformers#22729]
The website is https://huggingface.co/docs/transformers/tasks/token_classification
And the sentence is: Mapping all tokens to their corresponding word with the [word_ids](https://huggingface.co/docs/tokenizers/python/latest/api/reference.html#tokenizers.Encoding.word_ids) method.
The hyperlink is mistake, it should be the tokenizer in transformers package (https://huggingface.co/docs/transformers/v4.27.2/en/main_classes/tokenizer#transformers.BatchEncoding.word_ids) but the hyperlink given is in tokenizers package.

**Comment by mayankagarwals** [comment]
Happy to open a PR if needed

**Comment by amyeroberts** [comment]
@mayankagarwals Great! Feel free to open a PR and ping me for review :)

**Comment by mayankagarwals** [comment]
Sure @amyeroberts

**Comment by mayankagarwals** [comment]
@amyeroberts https://github.com/huggingface/transformers/pull/22765/files . Please review :)
