### ISSUE TITLE
Run_tf_ner.py error on TPU 

### ISSUE THREAD

**Issue by dlauc** [huggingface/transformers#2272]
## 🐛 Bug
run_tf_ner.py does not work with TPU. The first error is:
`File system scheme '[local]' not implemented `
When the script is changed and .tfrecord file is moved to gs:// address (and also hardcoded "/tmp/mylogs" is replaced with gs:/// dir)  there is an error with optimiser:
`AttributeError: 'device_map' not accessible within a TPU context.`

## To Reproduce

Steps to reproduce the behaviour:

python run_tf_ner.py.1 --tpu grpc://10.240.1.2:8470 --data_dir gs://nomentech/datadir --labels ./datasets/labels.txt --output_dir gs://nomentech/model1 --max_seq_length 40 --model_type bert --model_name_or_path bert-base-multilingual-cased --do_train --do_eval --cache_dir gs://nomentech/cachedir --num_train_epochs 5 --per_device_train_batch_size 96

## Environment

* OS: Ubuntu 18
* Python version: 3.7
* Tensorflow version: 2.1.0-dev20191222 (tf-nightly)
* PyTorch Transformers version (or branch): 2.3.0
* Distributed of parallel setup ? TPU

**Comment by BOUALILILila** [comment]
I have the same issue on Colab TPU with tf-nightly 2.2.0. @dlauc did you solve the problem?

**Comment by dlauc** [comment]
Hi @BOUALILILila, I switch to the TF/Keras - it works well with TPU-s

**Comment by jannesgg** [comment]
Hi @dlauc. Could you elaborate how you fixed this? I am having the same problem.
