### ISSUE TITLE
About Whisper finetuning on a out-of-vocabulary language datset

### ISSUE THREAD

**Issue by LYPinASR** [huggingface/transformers#22730]
### Feature request

Hello!
I am working on Whisper, and I want to finetune the model on _Amharic_ in OpenASR20 dataset. As far as I know,  _Amharic_ is not one of the languages participating in Whisper training. If I want to finetune the model on _Amharic_, what should I do?
Looking forward to your reply! Thank you!

### Motivation

Whisper finetuning on a out-of-vocabulary language datset

### Your contribution

I can do as needed.

**Comment by amyeroberts** [comment]
Hi @LYPinASR, thanks for raising an issue! 

Questions like this are best placed [in the forum](https://discuss.huggingface.co/), as we try to reserve github issues for bug reporting and feature requests. Here's a relevant thread about a previous finetuning event which might help: https://discuss.huggingface.co/t/open-to-the-community-whisper-fine-tuning-event/26681
