### ISSUE TITLE
Bug in Seq2SeqTrainer?

### ISSUE THREAD

**Issue by qmeeus** [huggingface/transformers#22744]
### System Info

Transformers version: 4.28.0.dev0
Pytorch version: 2

### Who can help?

@sanchit-gandhi @sgugger 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Finetune Whisper on multiGPU, using Seq2SeqTrainer

During generation step, I am getting an `AttributeError` ('DataParallel' object has no attribute 'generation_config') due to [this line of code](https://github.com/huggingface/transformers/blob/main/src/transformers/trainer_seq2seq.py#L280). Note that `generation_config` is a correct attribute in the model. 

I did finetune a modified version of Whisper on 2 GPUs in the past, but I did not experience the same error. I think that previously, generation was done on one GPU, even if the trainer was using data parallel. Not exactly sure if something has changed or if I did something wrong

The model is `openai/whisper-large-v2`

### Expected behavior

Either generation should not use `DataParallel` or `Seq2SeqTrainer` should access `model.model.generation_config` if the model is an instance of `DataParallel`

Happy to write a PR if necessary, let me know

**Comment by sgugger** [comment]
This has been fixed on main, so make sure to do a source install (or in a couple of hours you can upgrade to v4.28.0 once it's released).

**Comment by qmeeus** [comment]
Shame on me, I did not pull the latest changes

Thank you for your quick answer

**Comment by sgugger** [comment]
No worries at all!
