### ISSUE TITLE
Gpt2/xl Broken on "Write With Transformer" site

### ISSUE THREAD

**Issue by crackerjam** [huggingface/transformers#2275]
If you navigate to the [GPT-2 section of the Write With Transformer site](https://transformer.huggingface.co/doc/gpt2-large), select gpt2/xl, and try to generate text, the process will not generate anything.

**Comment by utsuho-hermann** [comment]
Same problem. And it seems not fixed yet.

**Comment by LysandreJik** [comment]
It should be fixed now. Thank you for raising this issue.
