### ISSUE TITLE
where is the script of a second step of  knwoledge distillation on SQuAD 1.0?

### ISSUE THREAD

**Issue by c0derm4n** [huggingface/transformers#2278]
## ❓ Questions & Help

In Distil part, there is a paragraph description which is "distilbert-base-uncased-distilled-squad: A finetuned version of distilbert-base-uncased finetuned using (a second step of) knwoledge distillation on SQuAD 1.0. This model reaches a F1 score of 86.9 on the dev set (for comparison, Bert bert-base-uncased version reaches a 88.5 F1 score)."
so where is the script of "a second step of  knwoledge distillation on SQuAD 1.0" mentioned above?
Thanks a lot, it will be very helpful to me!

**Comment by gyuwankim** [comment]
Check here: https://github.com/huggingface/transformers/blob/master/examples/distillation/run_squad_w_distillation.py
