### ISSUE TITLE
Unable to import transformers.models.bert.modeling_tf_bert on macOS?

### ISSUE THREAD

**Issue by talhakabakus** [huggingface/transformers#22781]
### System Info

```
transformers=4.28.0
tensorflow-macos=2.9.0
python=3.10
os=macOS Ventura 13.3.1
BERT_model=uncased_L-12_H-768_A-12
```

### Who can help?

@ArthurZucker  @younesbelkada

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

Simply run the following code snippet:

```
from transformers import BertTokenizer, TFBertModel

tokenizer = BertTokenizer.from_pretrained(BERT_PATH)
model = TFBertModel.from_pretrained(BERT_PATH)
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
resp = model(encoded_input)
print(resp)
```

### Expected behavior

Retrieve the output generated by the BERT model.

**Comment by amyeroberts** [comment]
@talhakabakus, thanks for raising this issue. 

So that we can best help you, could you provide some additional information: 
* Environment: Copy-paste the output of `transformers-cli env` here
* The error and full trackback encountered
