### ISSUE TITLE
Can not import T5BiLDModel

### ISSUE THREAD

**Issue by sufeidechabei** [huggingface/transformers#22799]
### System Info

I try from transformers.models.t5.modeling_t5 import T5Model, but it doesn't work. I build the library from this repo @ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers.models.t5.modeling_t5 import T5BiLDModel

### Expected behavior

It can import the model.

**Comment by amyeroberts** [comment]
Hi @sufeidechabei, thanks for raising an issue. 

So that we can best help you, could you follow the issue template and share information about the running environment (run `transformers-cli env` in your terminal and share what's printed out). 

Could you elaborate on what you mean by ` I build the library from this repo`? Is this running from a fork of the repo or from code on the hub?

**Comment by sufeidechabei** [comment]
Here is the print information:ImportError: cannot import name 'T5BiLDModel' from 'transformers.models.t5.modeling_t5' (/nobackup/haozhang/venv/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py). I use python 3.9.13 and pytorch 2.0

**Comment by amyeroberts** [comment]
@sufeidechabei  As requested, could you please share the information printed out when you run `transformers-cli env` in your terminal? 

Could you also point to the code on the hub which has the model implementation?

**Comment by sufeidechabei** [comment]
- `transformers` version: 4.25.1
- Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.35
- Python version: 3.9.13
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

@amyeroberts

**Comment by amyeroberts** [comment]
@sufeidechabei  - it's not possible to directly import the model in the following way:

```
from transformers.models.t5.modeling_t5 import T5BiLDModel
```
as `T5BiLDModel` isn't a model in the `modeling_t5` module. 

It's possible to use checkpoints from models defined on the hub using the `AutoModel` API. See documentation [here](https://huggingface.co/docs/transformers/custom_models#using-a-model-with-custom-code).
