### ISSUE TITLE
Able to load 'gpt_neox_reward_model' type models

### ISSUE THREAD

**Issue by sann3** [huggingface/transformers#22791]
### Feature request

The new models from OpenAssistant are type of gpt_neox_reward_model, the latest version of transformers lib not supporting them.

OpenAssistant/oasst-rm-2.1-pythia-1.4b-epoch-2.5
OpenAssistant/oasst-rm-2-pythia-6.9b-epoch-1

Getting the following error 
KeyError: 'gpt_neox_reward_model'

-

**Comment by amyeroberts** [comment]
@sann3, could you follow the issue template please and provide: 
* Environment information printed out when running `transformers-cli env` in your terminal
* A reproducible code snippet
* Error and full traceback
* Information about the expected behaviour

**Comment by sweetlilmre** [comment]
Hi, to add to this (same issue). The new models from OpenAssistant have `gpt_neox_reward_model` defined as the model type in  `config.json` This doesn't map to any existing models as defined in `transformers\models\auto\configuration_auto.py`.

A quick solve, which seems to work is to change the value in `config.json` for the model to `gpt_neox`.

The traceback for the error is as follows:

```
Traceback (most recent call last):
File “C:\dev\oobabooga-windows\text-generation-webui\server.py”, line 85, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “C:\dev\oobabooga-windows\text-generation-webui\modules\models.py”, line 186, in load_model
model = LoaderClass.from_pretrained(checkpoint, **params)
File “C:\dev\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py”, line 441, in from_pretrained
config, kwargs = AutoConfig.from_pretrained(
File “C:\dev\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py”, line 937, in from_pretrained
config_class = CONFIG_MAPPING[config_dict[“model_type”]]
File “C:\dev\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py”, line 643, in getitem
raise KeyError(key)
KeyError: ‘gpt_neox_reward_model’
```

I hope this helps.

**Comment by amyeroberts** [comment]
@sann3 @sweetlilmre Could either of you share which checkpoint you're trying to use? 

On one of the OpenAssistant [model repos](https://huggingface.co/OpenAssistant/oasst-rm-2-pythia-6.9b-epoch-1), they share a code snippet explaining how to use the checkpoint, including how to use their GPTNeoXRewardModel defined [here](https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/models/reward_model.py).

**Comment by sweetlilmre** [comment]
Hi @amyeroberts I'm using the model with [https://github.com/oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui) so my low level knowledge is almost zero here. Thank you for the links, I'll check them out, but I think this is probably a capability mismatch between the text-generation-webui project and the new models from OpenAssistant. I really don't want to waste your time on this.

**Comment by sann3** [comment]
@amyeroberts  I am trying the following models, the [link](https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/models/reward_model.py) you have shared might help
OpenAssistant/oasst-rm-2.1-pythia-1.4b-epoch-2.5
OpenAssistant/oasst-rm-2-pythia-6.9b-epoch-1

**Comment by sann3** [comment]
Able to load the model with https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/models/reward_model.py code.
