### ISSUE TITLE
New Crash Using Llama

### ISSUE THREAD

**Issue by sam-h-bean** [huggingface/transformers#22807]
### System Info

Seeing the following crash starting today when loading via accelerate. 
I think maybe related to https://github.com/huggingface/transformers/pull/22785
CC @fpgaminer @gante @amyeroberts 

```
File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 205, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 135, in apply_rotary_pos_emb
    cos = cos.squeeze((0, 1))  # [seq_len, dim]
TypeError: squeeze() received an invalid combination of arguments - got (tuple), but expected one of:
 * ()
      didn't match because some of the arguments have invalid types: (!tuple of (int, int)!)
 * (int dim)
      didn't match because some of the arguments have invalid types: (!tuple of (int, int)!)
 * (name dim)
      didn't match because some of the arguments have invalid types: (!tuple of (int, int)!)

```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Load Llama on GPU with accelerate and try to generate text.

### Expected behavior

Text is generated

**Comment by fpgaminer** [comment]
> @sam-h-bean - Yes, sorry, you're right about the issue and the cause. We're just opening up a PR now to resolve. Thanks for reporting so quickly!

My fault, I didn't see the note in the documentation that tuple inputs to `squeeze` is a new feature of PyTorch 2.0.  If you'd like I can open a pull request to fix by replacing with two `squeeze`s.

**Comment by amyeroberts** [comment]
No worries @fpgaminer - I should have caught it in the review. @DyeKuu is opening a PR as we type :)
