### ISSUE TITLE
Name Error: "Partial State" is not defind 

### ISSUE THREAD

**Issue by RAravindDS** [huggingface/transformers#22816]
# Parital State is not defined 

- In your recent release: 4.29.0.dev.0 has some issues with the code. The function or method "Partial State" is not defined. Today - I am not able to train my model. I just downloaded 4.28.0 to resolve this issue. Can you kindly check ASAP? 

- This error I am getting in the "Training arguments" method. 
- The training arguments script does not define or import the "Partial State" method or function. 

# Solution: 
- For now, install the previous stable version of transformers. 

```pip install transformers==4.28.0```

**Comment by amyeroberts** [comment]
@RAravindDS Thanks for reporting. I suspect the issue is coming from the version of accelerate in your environment. Could you: 
* Share the running environment info: copy-paste the output from running `transformers-cli env` in your terminal
THEN
* Upgrade accelerate using `pip install --upgrade accelerate` 
* Retry

**Comment by muellerzr** [comment]
As @amyeroberts mentions, please try following those steps. I'll also look at changing the min Accelerate needed/add a check.

**Comment by RAravindDS** [comment]
@amyeroberts I ran the code on Colab, and while training the LLM (LMV3), I got the error, Then I downloaded the previous version of the transformer, and it worked fine.

**Comment by amyeroberts** [comment]
@RAravindDS Yes, this is because the `PartialState` import was added as a dependency on the transformers development branch yesterday. `PartialState` was added in the 0.17.0 release in accelerate, and so for the development branch of transformers, accelerate >= 0.17.0 is required. 

Downgrading the transformers version removes the code which is importing `PartialState`.

**Comment by gli-mrunal** [comment]
to which version should I downgrade the transformers version to ? 

I am using the following version of transformer, datasets and huggingface_hub. 

![image](https://user-images.githubusercontent.com/77198742/232941383-cc398bb4-88c0-4a12-9ff1-c59f8c5aa1a6.png)

I am running into the following error:

```sh
 NameError: name 'PartialState' is not defined.
```

when I run the following code:

```python
from transformers import TrainingArguments 

training_args = TrainingArguments(
    output_dir="/content/gdrive",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    evaluation_strategy="steps",
    num_train_epochs=3.0,
    save_steps=100,
    eval_steps=100,
    logging_steps=100,
    learning_rate=1e-4,
    save_total_limit=2,
    do_train=True,
    do_eval=True,
    do_predict=True,
    push_to_hub=True,
    
)

```

How to resolve this issue  to work with my versions of the  transformer, datasets and huggingface_hub ?

**Comment by muellerzr** [comment]
@gli-mrunal please do `pip install git+https://github.com/huggingface/acelerate` to install the dev version, or `pip install accelerate -U` if you are not using multi-GPUs (such as in Colab).

**Comment by gli-mrunal** [comment]
![image](https://user-images.githubusercontent.com/77198742/233088446-1ae2dabb-6c79-4425-ae7f-759c993ce466.png)

**Comment by muellerzr** [comment]
@gli-mrunal sorry for the typo, there are two c's for accelerate :)

**Comment by RAravindDS** [comment]
> ![image](https://user-images.githubusercontent.com/77198742/233088446-1ae2dabb-6c79-4425-ae7f-759c993ce466.png)

Bro, you don't need to worry too much. Please downgrade the version. They are having stable version. Don't stress too much. Previous version working as usual. We changed all our requirements today. Hectic process :(

**Comment by gli-mrunal** [comment]
True. `!pip install transformers==4.28.0`  for previous version is easier solution. The newer version runs into dependency issues.

**Comment by creek411** [comment]
I tried to run using the following training arguments in Colab.
`training_args = TrainingArguments(
    output_dir=*,
    num_train_epochs=num_train_epochs,
    learning_rate=learning_rate,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    weight_decay=weight_decay,
    evaluation_strategy="epoch",
    disable_tqdm=False,
    logging_steps=logging_steps,
    push_to_hub=False,
    log_level="error",
    save_strategy="epoch",
    load_best_model_at_end=True,
)`

Then the following error occured.
`NameError: name 'PartialState' is not defined`

I attempted all of above advice, but this error wasn't resolved.
Please tell me how to fix this error.

**Comment by jeevankms** [comment]
Hi @creek411 install this version 4.28.0 of transformers by running this code `!pip install transformers==4.28.0`. Then restart and run all the code( if ur using colab).

**Comment by muellerzr** [comment]
@creek411 the solution would be to do `pip install accelerate` (and as now we have a release, it works OOTB with the normal pypi install), however the fact you have the error means you still probably are installing from dev and there's some cache working in there. You can try `pip uninstall transformers -y`, run your code, make sure it fails because `transformers` isn't installed, then install `transformers` again, either 4.28.0 or 4.29.0 and do `pip install accelerate` as well

**Comment by creek411** [comment]
Thank you for response. I attempted your solusion in both versions. But this error still has occured. Do you need more information about this code?

**Comment by creek411** [comment]
I attempted to do your solution and could avoid the error.
I appreciate for your advise.

**Comment by nihiluis** [comment]
> @creek411 the solution would be to do `pip install accelerate` (and as now we have a release, it works OOTB with the normal pypi install), however the fact you have the error means you still probably are installing from dev and there's some cache working in there. You can try `pip uninstall transformers -y`, run your code, make sure it fails because `transformers` isn't installed, then install `transformers` again, either 4.28.0 or 4.29.0 and do `pip install accelerate` as well

I get the same error with
```
Requirement already satisfied: accelerate in /usr/local/lib/python3.10/dist-packages (0.19.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.29.1)
```

on Colab

I had to install accelerate manually.

**Comment by Folahan07** [comment]
I'm getting the same error while using the Transfor4rec library from Nvidia. All the solutions proffered here didn't work for me.
I tried to provide training argument here 
"train_args = T4RecTrainingArguments(local_rank = -1,..."

**Comment by stban94diaz** [comment]
Esto me funciono en colab, pero es importante reiniciar el entorno de ejecución

!pip uninstall -y -r transformers accelerate
!pip install transformers==4.29.0
!pip install git+https://github.com/huggingface/accelerate

**Comment by Folahan07** [comment]
> This worked for me in colab, but it is important to restart the execution environment
> 
> !pip uninstall -y -r transformers accelerate !pip install transformers==4.29.0 !pip install git+https://github.com/huggingface/accelerate

Gracias amigo

**Comment by xeger** [comment]
Just a note that I tried using accelerate 0.19, as well as the dev version (0.20), and was still seeing the error with transformers 4.29. Downgrading transformers to 4.28 was the solution that worked for me.

**Comment by yuanam** [comment]
I came from the same error, but the previous is like……Did this mean it's not set to "cuda" (I run my code with GPU
![Uploading 屏幕截图 2023-06-06 225058.png…]()

**Comment by muellerzr** [comment]
For those having issues, can you tell me more about if you are working in Jupyter, Colab, or in regular Python? Again the solution hasn't changed: in the correct environment you need to make sure that `accelerate` is installed and viewable. To test this in your environment you can try importing it `import accelerate`. If it fails, it's not installed correctly.

**Comment by xeger** [comment]
I'm using Jupyter (as well as the VS Code notebooks extension, which is essentially the same) on Python 3.11 with no venv and the interpreter provided by `asdf`.

Upgrading `accelerate` 0.19 _did_ work with `transformers` 4.29, as it turned out; I'm just not accustomed to notebooks and forgot that I needed to restart the kernel to freshen the dependencies. Classic n00b mistake.

**Comment by Rodio346** [comment]
Please also remember to restart the kernel ( Given you are using Colab/Jupyter ) ( I know it is silly but yes )

**Comment by Manashsri** [comment]
What do I do after installing all the packages I am still getting this error I havve been working on kaggle and this is what I am geeting after running the code.How do I solve this?

NameError                                 Traceback (most recent call last)
Cell In[39], line 1
----> 1 training_args = Seq2SeqTrainingArguments(
      2     output_dir="M2M101",
      3     evaluation_strategy="epoch",
      4     learning_rate=2e-5,
      5     per_device_train_batch_size=16,
      6     per_device_eval_batch_size=16,
      7     weight_decay=0.01,
      8     save_total_limit=3,
      9     num_train_epochs=5,
     10     predict_with_generate=True,
     11     fp16=True,
     12     push_to_hub=True,
     13 )
     14 trainer = Seq2SeqTrainer(
     15     model=model,
     16     args=training_args,
   (...)
     21     compute_metrics=compute_metrics,
     22 )
     23 # for starting the training of model

NameError: name 'Seq2SeqTrainingArguments' is not defined
