### ISSUE TITLE
Loading sciBERT failed

### ISSUE THREAD

**Issue by broken-dream** [huggingface/transformers#2283]
## ❓ Questions & Help

I am trying to compare the effect of different pre-trained models on RE, the code to load bert is:
`self.bert = BertModel.from_pretrained(pretrain_path)`

When the "pretrain_path" is "pretrain/bert-base-uncased" , everything is fine, but after i changed it to "pretrain/scibert-uncased", i got error:

`-OSError: Model name 'pretrain/scibert-uncased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed 'pretrain/scibert-uncased/config.json' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.`

The scibert is pytorch model and the two directories are same in structure. 
It seems that if the model name is not in the name list, it won't work.

Thank you very much!

**Comment by stefan-it** [comment]
Try to use the following commands:

```bash
$ wget "https://s3-us-west-2.amazonaws.com/ai2-s2-research/scibert/huggingface_pytorch/scibert_scivocab_uncased.tar"
$ tar -xf scibert_scivocab_uncased.tar

The sciBERT model is now extracted and located under: `./scibert_scivocab_uncased`.

To load it:

```python
from transformers import BertModel

model = BertModel.from_pretrained("./scibert_scivocab_uncased")
model.eval()
```

This should work 🤗

**Comment by broken-dream** [comment]
> Try to use the following commands:
> 
> ```shell
> $ wget "https://s3-us-west-2.amazonaws.com/ai2-s2-research/scibert/huggingface_pytorch/scibert_scivocab_uncased.tar"
> $ tar -xf scibert_scivocab_uncased.tar
> 
> The sciBERT model is now extracted and located under: `./scibert_scivocab_uncased`.
> 
> To load it:
> 
> ```python
> from transformers import BertModel
> 
> model = BertModel.from_pretrained("./scibert_scivocab_uncased")
> model.eval()
> ```
> 
> This should work 🤗

It works! Thank you very much!
