### ISSUE TITLE
Type hinting Inconsistency in beam_search.py 

### ISSUE THREAD

**Issue by mert-kurttutan** [huggingface/transformers#22856]
### System Info

Main branch

### Who can help?

@gante

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi,

In `beam_search.py`file, the process function (in actual classes), have the following signature 

```

    def process(
        self,
        input_ids: torch.LongTensor,
        next_scores: torch.FloatTensor,
        next_tokens: torch.LongTensor,
        next_indices: torch.LongTensor,
        pad_token_id: Optional[int] = None,
        eos_token_id: Optional[Union[int, List[int]]] = None,
        beam_indices: Optional[torch.LongTensor] = None,
    ) -> Tuple[torch.Tensor]:
```
even though it returns `UserDict`. Any reason why not annotate with Dict, Mapping rather than Tuple?

This type of mismatching might exist in other places, not sure

### Expected behavior

IMO, it should return Dict, or Mapping

**Comment by gante** [comment]
Hey @mert-kurttutan 👋 

That is absolutely correct. Would you like to open a PR to fix it? :)

**Comment by jprivera44** [comment]
Hello, is anyone working on this issue? If not I can take it on.

**Comment by gante** [comment]
Hey @jprivera44 -- AFAIK no one is working on it, feel free to take it 🙌
