### ISSUE TITLE
BertTokenizer custom UNK unexpected behavior

### ISSUE THREAD

**Issue by idocal** [huggingface/transformers#2285]
## 🐛 Bug

Model I am using (Bert, XLNet....): Bert

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [ ] the official example scripts: (give details)
* [X] my own modified scripts: (give details)
Importing transformers to my own project but using BertTokenizer and BertModel with pretrained weights, using 'bert-base-multilingual-cased' for both tokenizer and model.

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details)
Fine tuning BERT for English NER on a custom news dataset.

## To Reproduce

1. Initialize a tokenizer with custom UNK
2. Try to convert the custom UNK to ID
3. Receive None as 

```
>>>tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased', do_lower_case=False, pad_token="<pad>", unk_token="<unk>")
>>> tokenizer.tokenize("<unk>")
['<unk>']
>>> tokenizer.convert_tokens_to_ids(["<unk>"])
[None]
```

## Expected behavior

My custom UNK should have an ID. (instead, I get None)

## Environment

* OS: Mac OSX
* Python version: 3.7.3
* PyTorch version: 1.1.0.post2
* PyTorch Transformers version (or branch): 2.1.1
* Using GPU ? No
* Distributed of parallel setup ? No
* Any other relevant information:

**Comment by moinnadeem** [comment]
I actually have the same problem with GPT-2 tokenizer. Is this the expected behavior?
