### ISSUE TITLE
`push_to_hub` with `branch` or `revision` keyword argument

### ISSUE THREAD

**Issue by zanussbaum** [huggingface/transformers#22867]
### Feature request

In `datasets`, you can upload a dataset to a `branch`. In the `transformers` package, it doesn't seem like `branch` or `revision` [are supported](https://huggingface.co/docs/transformers/v4.28.1/en/main_classes/model#transformers.PreTrainedModel.push_to_hub)

### Motivation

To push a model to the hub and with a revision seems a little harder. It seems like I would need to find the cache directory of the model and use `upload_folder` from `huggingface_hub` to upload to the correct revision.

I could very well be missing the right documentation but I can't seem to figure out how/where to do this

### Your contribution

Maybe a PR?

**Comment by amyeroberts** [comment]
cc @sgugger

**Comment by sgugger** [comment]
If you want to contribute a PR to add this, it would be welcome!

**Comment by RonanKMcGovern** [comment]
Any updates on this @zanussbaum ?
