### ISSUE TITLE
MaskFormerSwin shows as unsupported the index

### ISSUE THREAD

**Issue by joaocmd** [huggingface/transformers#22948]
Hello, is there any reason why the MaskFormerSwin shows as unsupported on the `index` page?

https://github.com/huggingface/transformers/blob/main/docs/source/en/index.mdx?plain=1#L364
```
|          MaskFormer           |       ❌       |       ❌       |       ✅        |         ❌         |      ❌      |
|        MaskFormerSwin         |       ❌       |       ❌       |       ❌        |         ❌         |      ❌      |
|             mBART             |       ✅       |       ✅       |       ✅        |         ✅         |      ✅      |
```

I think it is implemented in [this file](https://github.com/huggingface/transformers/blob/main/src/transformers/models/maskformer/modeling_maskformer_swin.py).

I also found this PR https://github.com/huggingface/transformers/pull/20344 which seemed like it added the model. The model is also missing from the "Supported models" subsection, but I didn't find its paper so is that part of the reason?

**Comment by amyeroberts** [comment]
@joaocmd Huh, that's odd. Thanks for reporting. Following the shared link, on `main` I see that MaskFormer is shown as a supported model. Perhaps you caught it in a weird moment before a patch was applied? 

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/22614925/233962005-0e4714bc-3b3f-4548-a964-c0fcfe774b2a.png">

**Comment by amyeroberts** [comment]
^sorry, I just realised that the link went to maskformer but it's `MaskFormerSwin` you're referring to.

**Comment by amyeroberts** [comment]
MaskFormersSwin is listed as a "private model" [here](https://github.com/huggingface/transformers/blob/3d3204c025b6b5de013e07dd364208e28b4d9589/utils/check_repo.py#L50). 

I suspect this is because MaskFormerSwin was added in order to be used as a backbone. @NielsRogge - is this correct?

**Comment by NielsRogge** [comment]
Yes ideally it shouldn't be in that public list, it's just there to be used for MaskFormer for backwards compatibility purposes.

Users can just use our regular Swin in case they want to use it as backbone for MaskFormer.

**Comment by joaocmd** [comment]
Hi @amyeroberts and @NielsRogge, should anything be changed so that the model doesn't appear on that public list or should we close this issue?

**Comment by amyeroberts** [comment]
@joaocmd If you want to open a PR to fix, I'd be very happy to review :) I don't think it's critical to address however.
