### ISSUE TITLE
Typo in error message in LlamaAttention

### ISSUE THREAD

**Issue by othertea** [huggingface/transformers#22941]
There's a typo in the `ValueError`'s message on line 219: https://github.com/huggingface/transformers/blob/d04ec99bec8a0b432fc03ed60cea9a1a20ebaf3c/src/transformers/models/llama/modeling_llama.py#L217-L221
It should be `(bsz, self.num_heads, q_len, kv_seq_len)` as it is in line 217.

**Comment by amyeroberts** [comment]
@othertea, good spot! Would you like to open a PR to fix this? 

cc @ArthurZucker

**Comment by othertea** [comment]
Yes, I've made a PR!
