### ISSUE TITLE
Change the probability of generation of certain tokens

### ISSUE THREAD

**Issue by Oxi84** [huggingface/transformers#22968]
### Feature request

OpenAI has a feature, that allows you to provide list of token ids, together with how much you want to increase or decrease probability of generation of these tokens.

For example if we have id = 112 that has logit= 23.72, we make logit = 23.72 + custom_value. Custom value  can have positive or negative value.

This should be a very usefull feature to have, I read the generation documentation and I am pretty sure you still did not implement it.

### Motivation

It is much more flexible that for example, the option to just remove a list of words 100% from generation.  And it is useful for increasing the diversity, so input tokens for example are different from output token, even though this can be partially done with encoder_repetition_penalty if I am not wrong. But here you can choose exact words, and sometimes you need to lower or increase probability of generation for just certain words.

### Your contribution

It should not be too difficult to implement, (even though there are always some problems) just in the function for totally removing some words from generation, you should instead of assigning logit of -inf, you replace the current logit value the_curent_logit + the_custom_value, where the custom value is the value users specify.

**Comment by sgugger** [comment]
cc @gante

**Comment by iiglesias-asapp** [comment]
Hi, @Oxi84! I agree with you on the increased flexibility and the possible implementation path. I did something like that for the feature request [here](https://github.com/huggingface/transformers/issues/22168#issue-1624460056). Feel free to react to @gante's [comment](https://github.com/huggingface/transformers/issues/22168#issuecomment-1477998997) if you find it useful

**Comment by gante** [comment]
Hi @Oxi84 👋 @iiglesias-asapp said it all, see the links shared :) 

(by the looks of it, it seems the feature will have enough supporters soon!)
