### ISSUE TITLE
Help on Firewalled installation

### ISSUE THREAD

**Issue by SupreethRao99** [huggingface/transformers#22999]
Hello,

I would like to install huggingface in a firewalled environment. I have a Git-lfs repository with all my models stored, I would like to use them with the transformers libraries' `.from_pretrained()` feature, I referred to this (https://github.com/huggingface/huggingface_hub/tree/main/src/huggingface_hub) to set up the git-repo, could someone help me use the models stored on my git instead of the huggingface hub. 

Thanks

**Comment by sgugger** [comment]
That is not possible. You can only use models from the Hub or locally downloaded.

**Comment by SupreethRao99** [comment]
Thanks @sgugger
