### ISSUE TITLE
PipelineChunkIterator does not provide the correct length

### ISSUE THREAD

**Issue by adrianeboyd** [huggingface/transformers#23003]
### System Info

- `transformers` version: 4.28.1
- PyTorch version (GPU?): 2.0.0+cu117 (True)

### Who can help?

@Narsil

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Relatively minor in the scheme of things, but I looked into it a bit to make sure it wasn't an issue with batching.

```python
from transformers import pipeline
pipe = pipeline("token-classification")
pipe(["New York " * 600] * 2, stride=0)
```

Leads to noisy warnings from torch:

```none
/tmp/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py:646: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x7f084a9bce50> was reported to be 2 (when accessing len(dataloader)), but 3 samples have been fetched. 
  warnings.warn(warn_msg)
/tmp/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py:646: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x7f084a9bce50> was reported to be 2 (when accessing len(dataloader)), but 4 samples have been fetched. 
  warnings.warn(warn_msg)
/tmp/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py:646: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x7f084a9bce50> was reported to be 2 (when accessing len(dataloader)), but 5 samples have been fetched. 
  warnings.warn(warn_msg)
/tmp/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py:646: UserWarning: Length of IterableDataset <transformers.pipelines.pt_utils.PipelineChunkIterator object at 0x7f084a9bce50> was reported to be 2 (when accessing len(dataloader)), but 6 samples have been fetched. 
  warnings.warn(warn_msg)
```

### Expected behavior

`PipelineChunkIterator` provides the intended length, no noisy warnings.

**Comment by davidberenstein1957** [comment]
Hi @adrianeboyd I am experiencing this same issue. Did you manage to solve this? Or was it just a versioning thingy?

**Comment by davidberenstein1957** [comment]
Cool, thanks for the explanation. I had not spent time on it yet but will ignore and disable the warnings for now.

**Comment by KnutJaegersberg** [comment]
I also wonder if this is a real problem or something I can ignore.

**Comment by s-a** [comment]
> I also wonder if this is a real problem or something I can ignore.

i doubt that this is not a real problem

**Comment by s-a** [comment]
i somehow figured out when i use a qa model `Zamachi/albert-for-question-answering` these warnings are gone.
