### ISSUE TITLE
[New model] Bark for realistic text-to-speech

### ISSUE THREAD

**Issue by xenova** [huggingface/transformers#23036]
### Model description

As stated in their [README](https://github.com/suno-ai/bark/blob/main/README.md):

> Bark is a transformer-based text-to-audio model created by [Suno](https://suno.ai/). Bark can generate highly realistic, multilingual speech as well as other audio - including music, background noise and simple sound effects. The model can also produce nonverbal communications like laughing, sighing and crying. To support the research community, we are providing access to pretrained model checkpoints ready for inference.

Some of their demos are quite amazing (albeit slightly creepy), being able to add "uhms" and "ahhs" in the synthesized audio. For example:

```
Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
But I also have other interests such as playing tic tac toe.
```

https://user-images.githubusercontent.com/34592747/238155864-cfa98e54-721c-4b9c-b962-688e09db684f.webm

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

GitHub repo: https://github.com/suno-ai/bark
Author: @gkucsko
Demo: https://huggingface.co/spaces/suno/bark
Model weights: Although not very well documented, [here](https://github.com/suno-ai/bark/blob/2c12023eb22868a633b76357b69d657b374736d9/bark/generation.py#L92-L119) is the portion of the code which links to the model weights. @Vaibhavs10 also looks to have uploaded them to the HF Hub [here](https://huggingface.co/reach-vb/bark-small) 🔥

**Comment by adit299** [comment]
Hello, if no one else is working on this, I would love to take a look and try to add this model to HuggingFace!

**Comment by flozi00** [comment]
https://github.com/huggingface/transformers/pull/23375

**Comment by fxmarty** [comment]
see https://github.com/huggingface/transformers/pull/24086
