### ISSUE TITLE
[CLS] token /  is used as the aggregate sequence representation for classification tasks

### ISSUE THREAD

**Issue by cherepanovic** [huggingface/transformers#2305]
[CLS]  is  fed into an output layer for classification. How will be built this token. Is there something special done for it during training? in which way does happen this aggregations of sequences?

Thanks for response

**Comment by shashankMadan-designEsthetics** [comment]
[CLS], [SEP] are "special token" of bert. Its included in the vocabulary of size 30522. Its starts with like 101, 103 something.

**Comment by cherepanovic** [comment]
of course these to tokens are special tokens. 

 **is  used  as  the  aggregate sequence representation for classification tasks.**

in which way does happen this aggregations?

>>The first token of every sequence is always a special classification  token  ([CLS]).  The  final  hidden  state corresponding  to  this  token  is  used  as  the  aggregate sequence representation for classification tasks.

from papert https://arxiv.org/pdf/1810.04805.pdf
