### ISSUE TITLE
pytorch_pretrained_bert giving different scores for BertForNextSentencePrediction 

### ISSUE THREAD

**Issue by LiZhengArsenal** [huggingface/transformers#2308]
## ❓ Questions & Help
from pytorch_transformers.modeling_bert import BertForNextSentencePrediction
from pytorch_transformers import BertTokenizer, BertConfig
import torch

#Load pretrained model from local
config = BertConfig.from_json_file('resources/bert_config.json')
token = BertTokenizer('resources/vocab.txt')
model = BertForNextSentencePrediction.from_pretrained('resources/pytorch_model.bin', config=config)
model.eval()
textA_ids = token.tokenize("How old are you?")
textB_ids = token.tokenize("The Eiffel Tower is in Paris")
text_ids = token.convert_tokens_to_ids(["[CLS]"] + textA_ids + ["[SEP]"] + textB_ids + ["[SEP]"])
segments_ids = [0]\*(len(textA_ids)+2) + [1]\*(len(textB_ids)+1)
text_inputs = torch.tensor([text_ids])
segments_inputs = torch.tensor([segments_ids])
with torch.no_grad():
    outputs = model(text_inputs, token_type_ids=segments_inputs)
print(outputs)

Outputs changed everytime when I ran the code. I followed many ways in other issues to solve the problem, but they didin't work.  And I've used local pretrained model for many other tasks, but never happened this thing before. So I don't think model caused this problem.

Version Information:
torch 1.1.0
pytorch-transformers 1.2.0

**Comment by chikubee** [comment]
@LiZhengArsenal I am facing the same issue, 
everytime i execute the code, different tensors are generated for the same doc.
Can you please tell me how you fixed it?

`ndexed_tokens = tokenizer.convert_tokens_to_ids(doc)
    segments_ids = [1] * len(doc)

    tokens_tensor = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_ids])

    with torch.no_grad():
        encoded_layers, _ = model(tokens_tensor, segments_tensors)  
`
