### ISSUE TITLE
Simplifying Output from Text Classification Pipelines

### ISSUE THREAD

**Issue by 907Resident** [huggingface/transformers#23092]
### Feature request

> This feature request references the content discussed in a [HF thread](https://discuss.huggingface.co/t/i-have-trained-my-classifier-now-how-do-i-do-predictions/3625).

I was just wondering if there is a particular reason why the output of the `pipe` shown above is a double list?

For instance, the output of the following:

```python
from transformers import TextClassificationPipeline

model = ...
tokenizer = ...
pipe = TextClassificationPipeline(model=model, tokenizer=tokenizer, return_all_scores=True)
# outputs a list of dicts like [[{'label': 'NEGATIVE', 'score': 0.0001223755971295759},  {'label': 'POSITIVE', 'score': 0.9998776316642761}]]
res = pipe("I love this movie!")

```

is a list that has _two_ square brackets (i.e., `[[ ... ]]`). This means the indexing process to grab say the negative score requires:

```python
neg = res[0][0]["score"]
```

This could be enhanced by simply returning a single dictionary object:

```python
res = {"label":["NEGATIVE", "POSITIVE"], "score":[0.0001, 0.9998]}

```

### Motivation

This idea came from reading a [HF discussion thread](https://discuss.huggingface.co/t/i-have-trained-my-classifier-now-how-do-i-do-predictions/3625). It was two years ago, so I did not want to reopen the conversation there. 

Also, I think this is a feature addition, but feel free to correct me if I am wrong. 

### Your contribution

I do not currently have plans to submit a PR, but if there is interest from the HF team, then I will take a harder look and comment here if I can make the change and submit a PR.

My initial guess is that this is not something bothers many users.

**Comment by sgugger** [comment]
This is also something we cannot change without breaking the code of many many users :-)
