### ISSUE TITLE
gen_kwargs in Seq2SeqTrainer

### ISSUE THREAD

**Issue by TJSun009** [huggingface/transformers#23100]
https://github.com/huggingface/transformers/blob/b8648290d2d97e7c7dbccd2d4a6a4f44e70d3b63/src/transformers/trainer_seq2seq.py#L257

Hi,

I'm trying to use the Seq2SeqTrainer with generation in the evaluation_loop and it looks like the config isn't being properly passed to the prediction step. I'm having to manually set self._gen_kwargs as this is not initialised anywhere else in the evaluation_loop. It is initialised in the evaluate call but this uses the Trainer evaluate implementation which lacks generation.

Am I missing something?

**Comment by sgugger** [comment]
cc @gante

**Comment by TJSun009** [comment]
My bad I realised the preprocess_logits_for_metrics function that I found [here](https://discuss.huggingface.co/t/cuda-out-of-memory-when-using-trainer-with-compute-metrics/2941/13) was truncating the generation output.
