### ISSUE TITLE
Sentences tokenized by LLaMA's tokenizer have `bos` tokens but do not have `eos` tokens.

### ISSUE THREAD

**Issue by yqy2001** [huggingface/transformers#23103]
### System Info

transformers version: main
Platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.10
Python version: 3.8.16
Huggingface_hub version: 0.11.1
PyTorch version (GPU?): 1.12.1 (True)
Tensorflow version (GPU?): not installed (NA)
Flax version (CPU?/GPU?/TPU?): not installed (NA)
Jax version: not installed
JaxLib version: not installed
Using GPU in script?: Yes
Using distributed or parallel set-up in script?: Not

### Who can help?

@ArthurZucker @sgug

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I find that the batches tokenized by llama's tokenizer have `bos` tokens but do not have `eos` tokens, leading to my finetuned llama do not stop properly during inference. Is it a bug, or are there some reasons for this practice?

https://github.com/huggingface/transformers/blob/b8648290d2d97e7c7dbccd2d4a6a4f44e70d3b63/src/transformers/models/llama/tokenization_llama.py#L72

### Expected behavior

An explanation to my confusion.

**Comment by hijkzzz** [comment]
Same issue

**Comment by ArthurZucker** [comment]
Hey! Sorry for the late reply, and thanks for opening an issue 🤗 
This is expected, because the official repository's default behaviour is the same. That is because during inference you don't need it to be added. You should initialise the tokenizer with the argument set to `True`. Tell me if this does not adresses your issue

**Comment by yqy2001** [comment]
Oh, I got it. Thanks for your reply! @ArthurZucker
