### ISSUE TITLE
Provide a different API solution instead of offline mode

### ISSUE THREAD

**Issue by rbavery** [huggingface/transformers#23117]
### Feature request

First off, thanks for the stellar lib and for all the work to get state of the art models in a consumable and documented state! I'm somewhat new to transformers, so this feedback is coming from a place of heavily using the library for a week.

I find offline mode unintuitive. I don't see it referenced on a variety of tutorials so I spent a day trying to figure out how to load local files with transformers, see https://github.com/huggingface/transformers/issues/23116

The docs are somewhat buried in a section I wouldn't expect: Installation https://huggingface.co/docs/transformers/installation#offline-mode

### Motivation

Offline mode makes it more difficult to work with local files, instead, methods like `from_pretrained` could pay attention to if a file path is locally sourced (starts with / ) or a url (https) or huggingface repo (no / or url prefix, has a username/repo pattern)

### Your contribution

I'm happy to provide feedback.

**Comment by sgugger** [comment]
Hi there. `from_pretrained` already accepts a path to a folder, I'm not sure what it is you are requesting.

**Comment by NielsRogge** [comment]
The relevant docs to load from local data can be found here: https://huggingface.co/docs/transformers/v4.28.1/en/main_classes/model#transformers.PreTrainedModel.from_pretrained.

The `from_pretrained` method accepts either a `repo_id` to a repo on the 🤗 hub or a local path to a folder.
