### ISSUE TITLE
KeyError: 'llama' on using any variant of OpenAssistant LLaMa models 

### ISSUE THREAD

**Issue by MoaazZaki** [huggingface/transformers#23129]
### System Info

- `transformers` version: 4.29.0.dev0
- Platform: Linux-5.15.0-1033-aws-x86_64-with-glibc2.31
- Python version: 3.10.11
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.0+cu117 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

1. Download  any OpenAsssitant LLaMa model with `transformers.AutoModelForCausalLM.` & `transformers.AutoTokenizer` (e.g. `TheBloke/OpenAssistant-SFT-7-Llama-30B-HF`)
2. Try to generate anything with it.

logs:
```
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/server.py", line 99, in serve_inner
open-assistant-inference-worker-1  |     model = get_model(model_id, revision, sharded, quantize)
open-assistant-inference-worker-1  |
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 52, in get_model
open-assistant-inference-worker-1  |     config = AutoConfig.from_pretrained(model_id, revision=revision)
open-assistant-inference-worker-1  |
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/transformers-4.27.0.dev0-py3.9.egg/transformers/models/auto/configuration_auto.py", line 882, in from_pretrained
open-assistant-inference-worker-1  |     config_class = CONFIG_MAPPING[config_dict["model_type"]]
open-assistant-inference-worker-1  |
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/transformers-4.27.0.dev0-py3.9.egg/transformers/models/auto/configuration_auto.py", line 588, in __getitem__
open-assistant-inference-worker-1  |     raise KeyError(key)
open-assistant-inference-worker-1  |
open-assistant-inference-worker-1  |.    KeyError: 'llama'
```

### Expected behavior

The model inference is working correctly without any issues

**Comment by sgugger** [comment]
The error message shows an older version of Transformers (4.27.0) are you sure you are executing this in the right Python environment?

**Comment by MoaazZaki** [comment]
That's right, upgrading to transformers >= 4.28.1 solved the issue.

Thank you 🙌

**Comment by alejandroballestae** [comment]
I have the same problem, the environment where I am installing the new version of transformers is here:

`RUN /opt/miniconda/envs/worker/bin/pip install -r requirements.txt`

but the line where the download_model.py is being executed uses another enviroment:

/opt/miniconda/envs/text-generation/bin/python /worker/download_model.py

I want to use distributed inferencing and GPUs, should I install the requirements from the worker env in the text-generation env? 

thank you
