### ISSUE TITLE
[GPT-J] where expected condition to be a boolean tensor, but got a tensor with dtype Half

### ISSUE THREAD

**Issue by Praful932** [huggingface/transformers#23136]
### System Info

- `transformers` version: 4.28.1
- Platform: Linux-5.10.147+-x86_64-with-glibc2.31
- Python version: 3.10.11
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.0+cu118 (True)
- Tensorflow version (GPU?): 2.12.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.6.9 (gpu)
- Jax version: 0.4.8
- JaxLib version: 0.4.7
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Collab example - [Link](https://colab.research.google.com/drive/1D689vHxZk5Bov5piIXOQ62t3M_cim4dr?usp=sharing)

### Expected behavior

I expected some output generated from the model

**Comment by younesbelkada** [comment]
Hi @Praful932 
Thanks for the issue, I have managed to reproduce it and fix it with https://github.com/huggingface/transformers/pull/23147
Can you try to uninstall `transformers` and install it again from source?
```bash
pip install git+https://github.com/huggingface/transformers
```

**Comment by Praful932** [comment]
This is working, Thanks for the quick fix!

**Comment by ZiboZ** [comment]
ZiboZ
