### ISSUE TITLE
Is there a uncased gpt2?

### ISSUE THREAD

**Issue by cloudygoose** [huggingface/transformers#2314]
## ❓ Questions & Help

Hi, thanks for everything. Quick question: Is there a pre-trained uncased gpt2, like bert-uncased?

**Comment by LysandreJik** [comment]
Hi, all the available models are listed in the [pretrained models section of the documentation](https://huggingface.co/transformers/pretrained_models.html). For GPT-2, there are four different models (`gpt2`, `gpt2-medium`, `gpt2-large`, `gpt2-xl`), which are all cased.
