### ISSUE TITLE
Cant get deepspeed parm

### ISSUE THREAD

**Issue by www516717402** [huggingface/transformers#23169]
### System Info

latest version 2023.5.5

### Who can help?

@stas00 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Use Accelerate and deepspeed plugin , transformers Trainer class.
I get config.ymal from `accelerate config` as follows:
``` ymal
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /xxx/dp_zero2.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
`/xxx/dp_zero2.json` is config, dont care.
However get deepspeed=None from TrainingArguments  when run ` accelerate launch xxx.py `，It means deepspeed parms is invalid.

### Expected behavior

Expect `Trainer class` read deepspeed parm from ymal file

**Comment by stas00** [comment]
This is a wrong repo. For Accelerate please file Issues under https://github.com/huggingface/accelerate/issues
