### ISSUE TITLE
Support `logging_ratio`, `save_ratio`, and `eval_ratio` (like for `warmup_ratio`)

### ISSUE THREAD

**Issue by konstantinjdobler** [huggingface/transformers#23171]
### Feature request

I would love if `TrainingArguments` and the Huggingface `Trainer` would support `logging_ratio`, `save_ratio`, and `eval_ratio` arguments (complementing `logging_steps`, `save_steps`, and `eval_steps`). If the `*_ratio` argument is set to e.g. `0.1`, logging/saving/eval would be done every `0.1 * total_training_steps`. This is already done for `warmup_ratio` and `warmup_steps`.

### Motivation

When dealing with many different tasks and datasets, it can be frustrating to have to calculate different appropriate `logging_steps` etc. for each individual dataset. This proposal would enable a unified, simple and concise way to solve this problem.

### Your contribution

I realize this might not be trivial to fully integrate, but hopefully, we can take `warmup_steps` and `warmup_ratio` as a reference. Depending on how deep the required changes are, I can also submit a PR (with some pointers on what to look out for).

**Comment by sgugger** [comment]
We already have 96 training arguments though, and that would make three more of all users to learn :-/

**Comment by konstantinjdobler** [comment]
Another option would be the allow `float` inputs for `logging_steps`, `save_steps`, `eval_steps` and interpret all inputs `<1.0` as a ratio (and throw an error if inputs `>1.0` are not integers). 

But yes there is a tradeoff with too much complexity

**Comment by sgugger** [comment]
I would prefer that solution actually, even if the naming is not perfect.

**Comment by konstantinjdobler** [comment]
Going over the code a bit, it seems like we would have to wait until after this if statement in `_inner_training_loop` to set the correct values based on the `max_steps` that gets calculated there + some additional guards in the `__post_init__` of the `TrainingArguments`. 
https://github.com/huggingface/transformers/blob/04ab5605fbb4ef207b10bf2772d88c53fc242e83/src/transformers/trainer.py#L1683-L1711
At first glance, it looks like the setting of when things get logged/saved/evaluated in `DefaultFlowCallback` should work out-of-the-box with this change.
I'm willing to contribute the changes once I find some time, does the general plan sound reasonable?

**Comment by sgugger** [comment]
Yes it does. I'll be looking forward to your PR!

**Comment by lava18** [comment]
Can someone clarify if this ratio means the % of training steps **per epoch** or the total training steps? If the latter, how do we know preemptively the total number of epochs (or total number of training steps) that the model is going to train for?
