### ISSUE TITLE
Add BROS

### ISSUE THREAD

**Issue by jinhopark8345** [huggingface/transformers#23181]
### Model description

[BROS(BERT Relying On Spatiality)](https://arxiv.org/abs/2108.04539)  is a pre-trained multimodal transformer for Document Understanding using OCR results of document images (text and bounding box pairs). 

and I would like to add this model to Huggingface as my first contribution!

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://github.com/clovaai/bros

**Comment by NielsRogge** [comment]
Would be great if you could add it, it should be very straightforward :)

I have a few demo notebooks on fine-tuning BROS, let me share them here:

- https://colab.research.google.com/drive/1PUpiKcSdXjBYM6a300ayC9TaYwzxdMus?usp=sharing
- https://colab.research.google.com/drive/1pTjxx4_46Sk1Zs0W_yzceP_bstmu4vfz?usp=sharing.

The first one is fine-tuning BROS on the FUNSD dataset, the second one is the same but with support for creating more training examples using the `return_overflowing_tokens` feature.

Let me know if you need any help to start contributing, feel free to start opening a draft PR
