### ISSUE TITLE
Improvements Over `enable_progress_bar` in `transformers.utils.logging`

### ISSUE THREAD

**Issue by aress31** [huggingface/transformers#23180]
### Feature request

Would it be possible to enhance the functionality of the `tqdm` bar utilized in the [logging module](https://github.com/huggingface/transformers/blob/v4.28.1/src/transformers/utils/logging.py#L351) to provide greater flexibility and adaptability for a broader range of use cases?

### Motivation

At present, it is not feasible to track the model download progress except by employing the `tf_logging.enable_progress_bar` method, which does not support a custom `tqdm`. Moreover, the built-in `tqdm` does not flush output, causing complications in my specific use case where I am invoking my script as a child process of a node server. Consequently, the progress output fails to reach the node process before the download completes, rendering the progress bar futile. Thus, I am requesting for increased flexibility and functionality of the `tqdm` bar utilized in the logging module to cater to a wider array of scenarios.

### Your contribution

The fix would be to add a `tqdm` or `tqdm_kwargs` argument to the following method.

```python
def enable_progress_bar():
    """Enable tqdm progress bar."""
    global _tqdm_active
    _tqdm_active = True
    hf_hub_utils.enable_progress_bars()
```

Note: I have tried to set the tqdm using `tf_logging.tqdm = new_tqdm` but this seems to impact non download/progressbar type of messages which is odd...

**Comment by sgugger** [comment]
We do not plan on offering more than the ability to turn progress bars on and off.

**Comment by aress31** [comment]
What is the rational behind that?

Not offering the ability to control at least the stream where the tqdm works is hindering integration with other techs. E.g., a Node server calling a python script as subprocess.
