### ISSUE TITLE
How can I read my bert model by using transformers?

### ISSUE THREAD

**Issue by Little-Frog-233** [huggingface/transformers#2318]
## ❓ Questions & Help

when I use pytorch_pretrained_bert, i can read my model like this:

from pytorch_pretrained_bert import BertModel, BertTokenizer
tokenizer = BertTokenizer.from_pretrained(bert_vocab_path)
bert = BertModel.from_pretrained(bert_model_path)

when i use transformers, how can i do this?

**Comment by shashankMadan-designEsthetics** [comment]
Not clearly sure what your question is but i guess u need to change
`from pytorch_pretrained_bert import BertModel, BertTokenizer` to `from transformers import BertModel, BertTokenizer` 
Download latest version if not-found-module error occurs...

**Comment by Little-Frog-233** [comment]
thank u for your replay, I tryed&nbsp;from transformers import BertModel, BertTokenizer, but it reminds me that&nbsp;OSError: Model name 'model/chinese_L-12_H-768_A-12' was not found in model name list, does it means that i can't use my local model?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shashankMadan-designEsthetics"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 晚上7:48
收件人:&nbsp;"huggingface/transformers"<transformers@noreply.github.com&gt;;
抄送:&nbsp;"晓辰"<1342468180@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huggingface/transformers] How can I read my bert model by using transformers? (#2318)




Not clearly sure what your question is but i guess u need to change
 from pytorch_pretrained_bert import BertModel, BertTokenizer to from transformers import BertModel, BertTokenizer
 Download latest version if not-found-module error occurs...

**Comment by shashankMadan-designEsthetics** [comment]
Well You can and it should work. 
First Try using just `bert-uncased` to check if its working correctly or maybe with `BERT-Base, Chinese`. 
If it says not found it may be some error from your local url so check if its the right folder location and name.
Then if nothing works i guess you may need to finetune it.

**Comment by Little-Frog-233** [comment]
i tryed and it works, but so slow, may because i'm in china, HAHA, thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shashankMadan-designEsthetics"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 晚上8:17
收件人:&nbsp;"huggingface/transformers"<transformers@noreply.github.com&gt;;
抄送:&nbsp;"晓辰"<1342468180@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huggingface/transformers] How can I read my bert model by using transformers? (#2318)




Well You can and it should work.
 First Try using just bert-uncased to check if its working correctly or maybe with BERT-Base, Chinese.
 If it says not found it may be some error from your local url so check if its the right folder location and name.
 Then if nothing works i guess you may need to finetune it.

**Comment by shashankMadan-designEsthetics** [comment]
Your welcome, Utilize cuda if u have gpus or try doing it on cloud. 
Do close the issue if it seems solved.
