### ISSUE TITLE
examples/run_speech_recognition_ctc: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 725: character maps to <undefined>

### ISSUE THREAD

**Issue by RobertBaruch** [huggingface/transformers#23193]
### System Info

- `transformers` version: 4.28.1
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.11.2
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: NO
- Using distributed or parallel set-up in script?: NO

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Create a json file corresponding to the [first example in speech recognition for pytorch](https://github.com/huggingface/transformers/tree/main/examples/pytorch/speech-recognition#single-gpu-ctc). See attached.

Run `python run_speech_recognition_ctc.py train.json`

Get error:

```
Traceback (most recent call last):
  File "F:\eo-reco\run_speech_recognition_ctc.py", line 775, in <module>
    main()
  File "F:\eo-reco\run_speech_recognition_ctc.py", line 378, in main
    model_args, data_args, training_args = parser.parse_json_file(json_file=os.path.abspath(sys.argv[1]))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\eo-reco\.env\Lib\site-packages\transformers\hf_argparser.py", line 391, in parse_json_file
    data = json.loads(open_json_file.read())
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 725: character maps to <undefined>
```

[train.json.zip](https://github.com/huggingface/transformers/files/11415631/train.json.zip)

### Expected behavior

No error.

**Comment by sgugger** [comment]
cc @sanchit-gandhi
