### ISSUE TITLE
help: couldn't find such vocabulary files at this path or url

### ISSUE THREAD

**Issue by anjubaoGDUT** [huggingface/transformers#2319]
I want to load the Chinese Roberta model  of pre-trained. When I use RobertaModel.from_pretrained() to load pre-trained model, it can't work.

<img width="1108" alt="屏幕快照 2019-12-25 下午11 56 11" src="https://user-images.githubusercontent.com/25845940/71454755-21f98100-27cd-11ea-8d0d-37beed6cc235.png">
<img width="1058" alt="屏幕快照 2019-12-25 下午11 56 17" src="https://user-images.githubusercontent.com/25845940/71455892-02b12280-27d2-11ea-98d6-ac1b2bd45901.png">

The  Chinese Roberta model is download from https://github.com/brightmart/roberta_zh
I am not sure if it is a problem with the pre-trained model or the transformers framework problem

**Comment by julien-c** [comment]
Did you manage to solve your issue? (if you did, how?)
