### ISSUE TITLE
ImportError: cannot import name 'OpenLlamaForCausalLM' from 'transformers'

### ISSUE THREAD

**Issue by MoaazZaki** [huggingface/transformers#23202]
### System Info

- `transformers` version: 4.29.0.dev0
- Platform: Linux-5.15.0-1035-aws-x86_64-with-glibc2.17
- Python version: 3.8.16
- Huggingface_hub version: 0.14.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.0+cu117 (False)
- Tensorflow version (GPU?): 2.11.1 (False)
- Flax version (CPU?/GPU?/TPU?): 0.5.3 (cpu)
- Jax version: 0.3.6
- JaxLib version: 0.3.5
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. pip install git+https://github.com/huggingface/transformers.git#egg=transformers or clone & pip install -e .
2. `from transformers import OpenLlamaForCausalLM`

### Expected behavior

The module `OpenLlamaForCausalLM` is imported successfully, as I tried the latest version.

am I doing something wrong here?

**Comment by sgugger** [comment]
This works for me on main. Are you sure you have pulled the latest changes if installing from the repo, or that you execute the code in the same environment you installed Transformers from source in?

**Comment by MoaazZaki** [comment]
It seems like it was an issue with pip failed to replace the current installed version with the main. Doing the following solve everthing:

1- `pip uninstall transformers`
2- Cloning the repo & `pip install -e .`

Thanks for the help 🙌
