### ISSUE TITLE
Whisper feature extraction: tiny condition check error

### ISSUE THREAD

**Issue by ozancaglayan** [huggingface/transformers#23203]
Hi

The `frame_width` below should be probably compared against `n_fft`, otherwise this `if` will always execute for nothing but not necessarily apply a padding as the frame width is already OK

https://github.com/huggingface/transformers/blob/04ab5605fbb4ef207b10bf2772d88c53fc242e83/src/transformers/models/whisper/feature_extraction_whisper.py#L163

**Comment by sgugger** [comment]
cc @sanchit-gandhi

**Comment by hollance** [comment]
Should be fixed by https://github.com/huggingface/transformers/pull/21998

**Comment by sanchit-gandhi** [comment]
Closed via #21998
