### ISSUE TITLE
OSError: sentence-transformers/all-distilroberta-v1 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

### ISSUE THREAD

**Issue by alexcoca** [huggingface/transformers#23229]
### System Info

- `transformers` version: 4.28.1
- Platform: macOS-13.3-x86_64-i386-64bit
- Python version: 3.9.6
- Huggingface_hub version: 0.13.4
- Safetensors version: not installed
- PyTorch version (GPU?): 1.13.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the following code:

```python
from transformers import AutoModel
model  = AutoModel.from_pretrained("sentence-transformers/all-distilroberta-v1")
```

This fails with the OSError in the issue title. I would normally raise this issue on the hub, but then to my amazement, `sentence-transformers/all-distilroberta-v1` does not exist on the hub. Our code reliably worked for months, so I presume that this model, quite well known actually, was in the space at some point.  I wonder why model loading no longer works. @younesbelkada , any idea?

### Expected behavior

Model is loaded.

**Comment by andras-cludo** [comment]
Experiencing the same issue with a different model. Looks like [the entire sentence-transformers page](https://huggingface.co/sentence-transformers) is down. Hopefully a fix is on the way.

**Comment by amyeroberts** [comment]
Hi @alexcoca, thanks for raising this issue! 

We're unfortunately experiencing a bug which means some popular organisations like sentence-transformers have had their model temporarily disappear from the Hub.

They will come back; we're working hard on getting this fixed ASAP! Apologies for the disruption.

**Comment by alexcoca** [comment]
@amyeroberts thanks for your hard work, everything is back to normal, I think. For future reference, users should know that `from_pretrained` methods have a `local_files_only` flag that can be passed to load a model that has been cached locally before. This can help in situations like this, thanks @Wauplin for pointing this out. Closing as the issue is fix afaik.
