### ISSUE TITLE
I am getting repetitive output when running "python run_generation.py"

### ISSUE THREAD

**Issue by sunshinelala1991** [huggingface/transformers#2322]
## ❓ Questions & Help

Here is the command I used to run the code:
python  run_generation.py --model_type=gpt2 --model_name_or_path=gpt2 --length 100
Here is the input and output I got:
Model prompt >>> nice to meet you
nice to meet you.

"I'm sorry, but I'm not going to be able to meet you. I'm not going to be able to meet you. I'm not going to be able to meet you. I'm not going to be able to meet you. I'm not going to be able to meet you. I'm not going to be able to meet you. I'm not going to be able to meet you. I'm not going to be able to meet!

I have tried different inputs but the output is always repeated.

**Comment by shashankMadan-designEsthetics** [comment]
I guess you can tune the model for better results like selecting medium large gpt model changin temp and top - p to get different predictions. 
If your new try using [write with transformer](https://transformer.huggingface.co/doc/gpt2-large) to  get an idea about it.

**Comment by patrickvonplaten** [comment]
You could add a `repetition_penalty`. Running 
python run_generation.py --model_type=gpt2 --model_name_or_path=gpt2 --length=100 --repetition_penalty=1.2

would give:

```
Model prompt >>> nice to meet you
nice to meet you.
I'm sorry, but I don't know what's going on here." She said with a smile that made me feel like she
was trying hard to be nice and not mean or anything… "You're just saying it because we've been 
together for so long…" Her voice sounded very serious as if someone had asked her about the past 
couple of days before they'd met up in person at all!
```

You would need a very up-to-date version of transformers to make sure that the PR #2303 is included in your code to be sure that the `repetition_penalty` is working correctly.
