### ISSUE TITLE
llama model can't generate EOS

### ISSUE THREAD

**Issue by ZhangMaoTai** [huggingface/transformers#23230]
### System Info

python                    3.8.16
torch                     1.13.1
transformers              4.28.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig

# both model have same behavior
model_path = "luodian/llama-7b-hf"
# model_path = "huggyllama/llama-7b"

model = LlamaForCausalLM.from_pretrained(model_path)
tokenizer = LlamaTokenizer.from_pretrained(model_path)
tokenizer.pad_token = tokenizer.eos_token

text = ["Translate english to chinese: I love you.", "What is your name:"]
a = tokenizer(text, return_tensors='pt',padding="longest")
print(model.generate(**a, max_new_tokens=64))
```

### Expected behavior

The llama model's generate method doesn't generate any EOS token under any circumstances

**Comment by amyeroberts** [comment]
cc @ArthurZucker

**Comment by brando90** [comment]
what was the soln?

**Comment by Boltzmachine** [comment]
Same issue

**Comment by ArthurZucker** [comment]
The model does not predict it with the generation parameters that are used.

**Comment by edwarddgao** [comment]
Same... I'm using unsloth llama-3-base
[](https://colab.research.google.com/drive/1XamvWYinY6FOSX9GLvnqSjjsNflxdhNc?usp=sharing#scrollTo=QmUBVEnvCDJv)

**Comment by KillerShoaib** [comment]
> Same... I'm using [unsloth llama-3-base](https://colab.research.google.com/drive/1XamvWYinY6FOSX9GLvnqSjjsNflxdhNc?usp=sharing#scrollTo=QmUBVEnvCDJv)

Hey, did you find any solution for llama 3 unsloth. I've fine-tuned the model with tokenizer.eos_token at the end. However, my model is not able to predict the eos token at all. It'll generate a coherent response then start spamming the last sentence again and again till hitting max length.

**Comment by Myashka** [comment]
> > Same... I'm using [unsloth llama-3-base](https://colab.research.google.com/drive/1XamvWYinY6FOSX9GLvnqSjjsNflxdhNc?usp=sharing#scrollTo=QmUBVEnvCDJv)
> 
> Hey, did you find any solution for llama 3 unsloth. I've fine-tuned the model with tokenizer.eos_token at the end. However, my model is not able to predict the eos token at all. It'll generate a coherent response then start spamming the last sentence again and again till hitting max length.

Hey, I'm experiencing the same issue after fine-tuning Llama 3.1 70B w/ Lora on various SFT datasets. The model doesn't generate the eos token, and instead it repeats the last sentence multiple times until the maximum length is reached. Have you found any solution to this problem? I'd appreciate any insights you could share!
