### ISSUE TITLE
agent fail

### ISSUE THREAD

**Issue by ltm920716** [huggingface/transformers#23262]
### System Info

transformers==4.30.0.dev0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

![image](https://github.com/huggingface/transformers/assets/12007227/ca5005b7-9704-436a-86d5-64c4e9d92930)

from transformers import HfAgent
agent = HfAgent("https://api-inference.huggingface.co/models/bigcode/starcoder")

from PIL import Image
x = Image.open('test.jpg')

agent.run("here is a image named `image`, what does it belong to?", image=x, remote=True)
==Explanation from the agent==
I will use the following  tool: `image_classifier` to classify the image.

==Code generated by the agent==
label = image_classifier(image)
print(f"The label is {label}.")

==Result==
Evaluation of the code stopped at line 0 before the end because of the following error:
It is not permitted to evaluate other functions than the provided tools (tried to execute image_classifier).

agent.run("here is a image named `image`, what does it belong to?", image='test.jpg', remote=True)
==Explanation from the agent==
I will use the following  tool: `image_classifier` to classify the image.

==Code generated by the agent==
label = image_classifier(image)
print(f"The label is {label}.")

==Result==
Evaluation of the code stopped at line 0 before the end because of the following error:
It is not permitted to evaluate other functions than the provided tools (tried to execute image_classifier).

### Expected behavior

run normally

**Comment by amyeroberts** [comment]
cc @sgugger

**Comment by sgugger** [comment]
Run normally meaning? I'm not even completely sure what you want the agent to run so I don't see how the LLM could find out too ;-)
Make sure to:
1. Use openAI, sadly it's better than the opensource alternatives
2. refine your prompt input, we have a great guide for that [here](https://huggingface.co/docs/transformers/custom_tools#writing-good-user-inputs)

**Comment by ltm920716** [comment]
hi @sgugger ,
I am sorry for my bad description.

There are two problems when I run the command `agent.run("here is a image named image, what does it belong to?", image=x, remote=True)`

1、The agent return tool `image_classifier ` which not in toolbox. According to the base run-prompt，it should only return tool in toolbox. So this is only because the llm's capacity？

2、for tool like `image_classifier` or `image_caption`， it‘s input is `image`，what is the type  of `image`? PIL or Numpy or str(local path)? 

thanks!

**Comment by ltm920716** [comment]
it seems that the param `remote=True` does not work, what tools can be loaded remotely?

**Comment by sgugger** [comment]
The agent can return whatever the hell it wants. If it decides to use tools that don't exist, there is nothing we can do (again use openAI to get better results).
There is no image classifier tool. For tools working on images, the input type required is a standard PIL Image.

As for your last comment `remote=True` on all tools.

**Comment by ltm920716** [comment]
@sgugger 
thanks
