### ISSUE TITLE
xlm-roberta-xlarge doesn't exist

### ISSUE THREAD

**Issue by Jack000** [huggingface/transformers#23279]
### System Info

from https://huggingface.co/docs/transformers/model_doc/xlm-roberta-xl

`model = XLMRobertaXLForSequenceClassification.from_pretrained("xlm-roberta-xlarge")
`
I can't find xlm-roberta-xlarge on https://huggingface.co/models

there's facebook/xlm-roberta-xl - but this is the raw masked token model and doesn't seem to work with XLMRobertaXLForSequenceClassification, it's missing the classifier head.

model = XLMRobertaForSequenceClassification.from_pretrained("xlm-roberta-large")
works just fine for me

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AutoTokenizer, XLMRobertaXLForSequenceClassification
model = XLMRobertaXLForSequenceClassification.from_pretrained("xlm-roberta-xlarge")

### Expected behavior

I guess xlm-roberta-xlarge should be available, or the docs should be amended..

**Comment by amyeroberts** [comment]
Hi @Jack000 , thanks for reporting this issue. 

This is indeed odd - the checkpoint being reference doesn't seem to exist. In the original PR adding the model to the library - it seems the [checkpoints were added under the facebook org](https://github.com/huggingface/transformers/pull/13727#pullrequestreview-866391378). It's OK if the checkpoint used in the example doesn't have the weights for the specific head e.g. for [multiple choice for bert we use `bert-base-uncased`](https://huggingface.co/docs/transformers/v4.29.1/en/model_doc/bert#transformers.BertForMultipleChoice). Would you like to open a PR to update the checkpoint?
