### ISSUE TITLE
`offset_alibi` is not used

### ISSUE THREAD

**Issue by JaheimLee** [huggingface/transformers#23286]
What's the meaning of `offset_alibi`? It's not used in Bloom's source codes. Does it make sense?

**Comment by amyeroberts** [comment]
Hi @JaheimLee, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/), as we try to reserve the github issues for feature requests and bug reports. Another good place to ask would be opening a discussion [on the model page on the hub](https://huggingface.co/bigscience/bloom-7b1/discussions), as it directly relates to the configuration file there.

**Comment by JaheimLee** [comment]
> Hi @JaheimLee, thanks for raising an issue!
> 
> This is a question best placed in our [forums](https://discuss.huggingface.co/), as we try to reserve the github issues for feature requests and bug reports. Another good place to ask would be opening a discussion [on the model page on the hub](https://huggingface.co/bigscience/bloom-7b1/discussions), as it directly relates to the configuration file there.

Oh, sorry.  I created an issue on the hub. I close this one now.
