### ISSUE TITLE
BERT adapted to time series

### ISSUE THREAD

**Issue by jbechara** [huggingface/transformers#2330]
## ❓ Questions & Help

Is there a better way of modifying BERT to take time series as input (i.e. numerical data instead of text) than editing my local library to skip the word embedding? If not, what is the easiest way to do the latter?

Thanks!

**Comment by MJimitater** [comment]
Can this issue be opened again? I recon there is a need to discuss this possibility

**Comment by ink-pad** [comment]
@jbechara / @MJimitater : Hello! 

I happened to stumbled upon this issue earlier this week. We have a paper (with code and a new dataset), which is to appear in ICASSP '21, where we propose to model multivariate times series dataset through BERT and GPT2. Please give it a try to see if it serves your purpose! 

Paper: https://arxiv.org/abs/2011.01843
Code: https://github.com/IBM/TabFormer
