### ISSUE TITLE
Support Azure OpenAI in transformer agents

### ISSUE THREAD

**Issue by huajianmao** [huggingface/transformers#23324]
### Feature request

Support it by setting the openai properties.

``` python
openai.api_type = "azure"
openai.api_version = "2023-03-15-preview"
openai.api_base = "https://THE_NAME.openai.azure.com/"
openai.api_key = "AZURE_OPENAI_API_KEY"

# response = openai.Completion.create(engine="xxxx", ...)
```

### Motivation

Azure OpenAI is also used by a lot of people.
It would be great to support it in the transformer agents.

### Your contribution

I may contribute to test it.

**Comment by amyeroberts** [comment]
@huajianmao thanks for opening this issue, 

As a user can enable azure open AI support by adding these lines to their own code, there isn't a requirement to add support in the library.

**Comment by waundme** [comment]
> @huajianmao thanks for opening this issue,
> 
> As a user can enable azure open AI support by adding these lines to their own code, there isn't a requirement to add support in the library.

That's not entirely correct. You'll get an InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 
'openai.api_resources.completion.Completion'>

Because you would have to support some way of specifying the Azure-deployment_id in your code.

**Comment by MSDNAndi** [comment]
https://huggingface.co/docs/transformers/v4.29.1/en/main_classes/agent#transformers.OpenAiAgent
agent = OpenAiAgent(model="text-davinci-003", api_key=pswd)
ideally would be changed. The Azure API is a different type and different enough to allow the relevant parameters to be passed in.
It doesn't sound "clean" to me to access the openai API parameters directly outside the OpenAiAgent.
The Azure based version is rapidly gaining in importance as people can use their corporate or personal Azure credits vs having to pay OpenAI separately.

**Comment by cforce** [comment]
for GPT4 you need to use 
openai.api_version = "2023-03-15-preview" # used for GPT-4 - see https://learn.microsoft.com/en-gb/azure/cognitive-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions

**Comment by MSDNAndi** [comment]
Sure, but we were not talking about GPT-4. The examples only covered DaVinci-003

**Comment by waundme** [comment]
As this was pretty simple I added support for Azure, not sure when or even if HF will merge but you can look at the code from the PR #23355 .
