### ISSUE TITLE
Still cannot import cached_path

### ISSUE THREAD

**Issue by Fshrink** [huggingface/transformers#23347]
### System Info

- `transformers` version: 4.29.1
- Platform: Linux-5.19.0-41-generic-x86_64-with-glibc2.36
- Python version: 3.11.3
- Huggingface_hub version: 0.14.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1 (False)
- Tensorflow version (GPU?): 2.12.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.6.10 (cpu)
- Jax version: 0.4.10
- JaxLib version: 0.4.10
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: ?

### Who can help?

@sanchit-gandhi   I guess...

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import cached_path

be it as a single instruction in ipython or when using the ConvAIModel from simpletransformers

Tried all versions from before 4.22.0

### Expected behavior

Import the method

**Comment by BramVanroy** [comment]
I don't think that that exists. Did you mean `default_cache_path` or maybe `TRANSFORMERS_CACHE`? Those are in file_utils (and actually utils/hub)

```python
from transformers.file_utils import default_cache_path, TRANSFORMERS_CACHE
```

https://github.com/huggingface/transformers/blob/cf11493dce0a1d22446efe0d6c4ade02fd928e50/src/transformers/utils/hub.py#L80-L102

**Comment by Fshrink** [comment]
Bram,
Thanks so much for answering!
This is what I get from running the model:

![Screenshot from 2023-05-14 09-08-29](https://github.com/huggingface/transformers/assets/132883741/bb9a0b2f-8e9d-4981-b239-c1b4f157c82e)

Which refers to this part of the >>>miniconda3/envs/ST2/lib/python3.11/site-packages/simpletransformers/conv_ai/conv_ai_utils.py:

![Screenshot from 2023-05-14 09-16-11](https://github.com/huggingface/transformers/assets/132883741/4871b7ed-5698-4375-8bdb-d5cb5d0d76b3)

And that's where all stops since this function is used across the script and creates objects that are used by the model.py.

Of course this is a simpletransformers code , but it requests an import from transformers that apparently does not exist...

Thanks!

**Comment by BramVanroy** [comment]
Unfortunately that is not a problem of `transformers` but of `simpletransformers`. In their requirements, they specify `"transformers>=4.6.0"` so it is possible that they do not test against/support the most recent versions.

https://github.com/ThilinaRajapakse/simpletransformers/blob/365b27feb27e8337a7f4f0244eff8683c5763ef8/setup.py#L29

I suggest that you try 4.6.0 and if that does not work, you should ask them on their repository because there is not much that can be done on this end.

**Comment by Fshrink** [comment]
Will do. Appreciate it.

**Comment by sanchit-gandhi** [comment]
Thanks @BramVanroy! And best of luck @Fshrink with getting your `simpletransformers` script working @Fshrink!
