### ISSUE TITLE
Whisper processor no longer saves mel_filters with `.save_pretrained()` 

### ISSUE THREAD

**Issue by xenova** [huggingface/transformers#23344]
### System Info

- `transformers` version: 4.29.1
- Platform: Linux-5.15.107+-x86_64-with-glibc2.31
- Python version: 3.10.11
- Huggingface_hub version: 0.14.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.0+cu118 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.6.9 (cpu)
- Jax version: 0.4.8
- JaxLib version: 0.4.7
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@hollance @sanchit-gandhi

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running this code:
```python
from transformers import AutoProcessor
processor = AutoProcessor.from_pretrained('openai/whisper-tiny')
processor.save_pretrained('test')
```

will output the following `preprocessor_config.json`:

```json
{
  "chunk_length": 30,
  "feature_extractor_type": "WhisperFeatureExtractor",
  "feature_size": 80,
  "hop_length": 160,
  "n_fft": 400,
  "n_samples": 480000,
  "nb_max_frames": 3000,
  "padding_side": "right",
  "padding_value": 0.0,
  "processor_class": "WhisperProcessor",
  "return_attention_mask": false,
  "sampling_rate": 16000
}
```

which does not include `mel_filters`. This is different to the official models saved on the hub, which do include this: https://huggingface.co/openai/whisper-tiny/blob/main/preprocessor_config.json

This is due to the following recent update: https://github.com/huggingface/transformers/commit/7f9195090160d508c7afb2e444e34f181872dd10

Linked issue: https://github.com/xenova/transformers.js/issues/107

### Expected behavior

Saving the processor should also save the `mel_filters`.

**Comment by hollance** [comment]
That change was made before the update you mentioned, in https://github.com/huggingface/transformers/pull/21267

It is not necessary to save the mel filters in the JSON file since they are completely defined by the other properties from that JSON file. Plus it makes the JSON file huge and unreadable.

As far as I'm aware, the PyTorch implementation of Whisper will load JSON config files with or without the mel filters just fine. If this breaks in Transformers.js, then the issue would seem to be there.

**Comment by xenova** [comment]
Okay thanks 👍 I agree, it does make it quite unreadable; I just thought I would mention it since it causes a mismatch with some of the official whisper models on the hub.
