### ISSUE TITLE
Document what layerdrop does

### ISSUE THREAD

**Issue by RobertBaruch** [huggingface/transformers#23351]
### System Info

- `transformers` version: 4.28.1
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.11.2
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: NO
- Using distributed or parallel set-up in script?: NO

### Who can help?

@sgugger 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

In `transformers/models/wav2vec2/configuration_wav2vec2.py` there is a parameter `layerdrop` in `__init__` which is not documented. This parameter is set (and overrides the default `0.1`) in the examples at `examples/pytorch/speech-recognition/README.md`, so it seems to be important.

### Expected behavior

Document `layerdrop`.

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi

**Comment by sanchit-gandhi** [comment]
Hey @RobertBaruch - good catch! It's indeed missing from the Wav2Vec2 config docstring. Would you like to open a PR to add this info? Easiest would be to copy the details from one of the existing configs where the info is present, e.g. OPT:
https://github.com/huggingface/transformers/blob/130e15429116689c9d747be2cdd8c4be7bb7e2bd/src/transformers/models/opt/configuration_opt.py#L70
