### ISSUE TITLE
Model isn't loaded with the right type with AutoModel with torch_dtype="auto" 

### ISSUE THREAD

**Issue by eladsegal** [huggingface/transformers#23357]
### System Info

- `transformers` version: 4.30.0.dev0

### Who can help?

@stas00 
(as the relevant change was made in https://github.com/huggingface/transformers/pull/21524)

### Reproduction

```python
from transformers import AutoModelForSeq2SeqLM, T5ForConditionalGeneration

auto_model = AutoModelForSeq2SeqLM.from_pretrained("ybelkada/flan-t5-xl-sharded-bf16", torch_dtype="auto")
print(auto_model.dtype)  # torch.float32

t5_model = T5ForConditionalGeneration.from_pretrained("ybelkada/flan-t5-xl-sharded-bf16", torch_dtype="auto")
print(t5_model.dtype)  # torch.bfloat16
```

### Expected behavior

`AutoModelForSeq2SeqLM` should also load the model in `torch.bfloat16`.

**Comment by amyeroberts** [comment]
cc @younesbelkada

**Comment by stas00** [comment]
Thank you for the report, @eladsegal - that's indeed a bug that I introduced while trying to fix another issue. 

Please try this fix: https://github.com/huggingface/transformers/pull/23379

**Comment by eladsegal** [comment]
Thank you @stas00 for the quick fix! Works just as expected.

**Comment by stas00** [comment]
Thank you for confirming that, @eladsegal!
