### ISSUE TITLE
Default Models of the pipeline function

### ISSUE THREAD

**Issue by DiogenesBR** [huggingface/transformers#23377]
I made issue a on the NLP Course (https://github.com/huggingface/course/issues/561):

> In the video:
> Chapter 1 Live Session with Sylvain
> https://youtu.be/aV4wfnIakSQ?t=928
> 
> There a question of what are the default models in the pipeline library.
> His answer is to look at:
> https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/__init__.py
> 
> I think that this information should be in the chapter 1, also on the documentation

Then I was asked to make a Issue here too.

After looking the Transformers Agents also have this problem
![image](https://github.com/huggingface/transformers/assets/16890195/e98316e6-75bd-48a6-8d36-bd042347099c)

For a instance Speech to text uses Whisper but it don't say what exact version of Whisper

There more than 3000 versions of Whisper on the Models Directory
https://huggingface.co/models?search=whisper

**Comment by amyeroberts** [comment]
Hi @DiogenesBR, thanks for raising this issue! 

Similar to answer in the linked video, at the moment this info is best found by looking at the source code. For example, for the [speech-to-text tool](https://github.com/huggingface/transformers/blob/918a06e25dfd6f79a20b6f07f63598c71e440161/src/transformers/tools/speech_to_text.py#L22), the checkpoint used is [openai/whisper-base](https://huggingface.co/openai/whisper-base). 

Would you be interested in opening a PR to add this information? 

cc @MKhalusova @stevhliu
