### ISSUE TITLE
Generative models return the same responses to all questions

### ISSUE THREAD

**Issue by serenalotreck** [huggingface/transformers#23411]
### System Info

- `transformers` version: 4.25.1
- Platform: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
- Python version: 3.7.16
- Huggingface_hub version: 0.13.3
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Problem: Different questions to a conversational pipeline result in the same answers for a given model. This problem occurs across multiple models, and occurs when a new Python session is initiated between runs. 

Code to reproduce: 
```python
from transformers import pipeline, Conversation

for model in ['facebook/opt-1.3b', 'bigscience/bloom-560m', 'gpt2']:
     generator = pipeline(task='conversational', model=model)
     convo = Conversation('Should I see a movie tonight?')
     generator(convo)

for model in ['facebook/opt-1.3b', 'bigscience/bloom-560m', 'gpt2']:
     generator = pipeline(task='conversational', model=model)
     convo = Conversation('What do you know about biology?')
     generator(convo)
```

Outputs:
* From the first for loop:
```
Conversation id: 9335b8bb-d73e-4fb0-91e3-bb0dbf62dd76 
user >> Should I go see a movie tonight? 
bot >> I'm not sure if this is a good idea. 
Conversation id: 03c41e56-35b1-4b02-9757-4bf1c90a6f32 
user >> Should I go see a movie tonight? 
bot >> The first thing you need to do is to get a
The attention mask and the pad token id were not set. As a consequence, you may observe unexpecte
d behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation
 results, please set `padding_side='left'` when initializing the tokenizer.
Conversation id: 62e5f6f0-7e6e-4a5c-baf6-93ea40e31b85 
user >> Should I see a movie tonight? 
bot >> The first time I saw the new Star Wars movie, I 
```
* From the second for loop:
```
Conversation id: f14a10d8-3661-482e-8b95-bb0a417a0afd 
user >> What do you know about biology? 
bot >> I'm not sure if this is a good idea.  
Conversation id: 24866d8e-bfc8-4ebf-825e-b90965ab60b7 
user >> What do you know about biology? 
bot >> The first thing you need to do is to get a good 
The attention mask and the pad token id were not set. As a consequence, you may observe unexpecte
d behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation
 results, please set `padding_side='left'` when initializing the tokenizer.
Conversation id: 40d35c22-cf89-4750-931e-f75a5d80431b 
user >> What do you know about biology? 
bot >> The first time I saw the new Star Wars movie, I 
```

### Expected behavior

Sensical answers that are in response to the question, rather than an out-of-the-box response that doesn't make sense in context.

**Comment by amyeroberts** [comment]
cc @Narsil @gante

**Comment by gante** [comment]
Hey @serenalotreck 👋 

The models you're trying to use are not compatible with the conversational pipeline. Check [these docs](https://huggingface.co/docs/transformers/v4.29.1/en/main_classes/pipelines#transformers.ConversationalPipeline): "The models that this pipeline can use are models that have been fine-tuned on a multi-turn conversational task, currently: ‘microsoft/DialoGPT-small’, ‘microsoft/DialoGPT-medium’, ‘microsoft/DialoGPT-large’. See the up-to-date list of available models on [huggingface.co/models](https://huggingface.co/models?filter=conversational)."

**Comment by gante** [comment]
@serenalotreck you can check [this leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard) to see the highest scoring open-source LLMs.

The catch is that they need a carefully crafted input prompt (also known as system prompt) before they turn into helpful assistants like ChatGPT. ChatGPT also has it, but it is hidden to you. Here's a [simple example](https://github.com/LAION-AI/Open-Assistant/blob/d1da7db6e9e4c198b6b66a68291e5886db80c7f6/model/model_training/configs/config.yaml#L77), for the case of open assistant -- you may be able to find more online :)

**Comment by Narsil** [comment]
And even more than the system prompt, there is usually a specific token sequence used during the model finetuning, which is critical to get a good output.

For instance OpenAssistant biggest model is using "<|prompt_begin|><|prompter|>somethign something</s><|assistant|>".
And different models use different prompting. Unfortunately at this time there are too many different models released at the same time, and it's impossible to include all of these specific parts everywhere.

https://huggingface.co/chat/ should give you an idea of what OpenAssistant model is capable of.
OpenAssistant has their own front to their models https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjCpZe2iPz-AhX6hv0HHdo1CsQQjBB6BAgdEAE&url=https%3A%2F%2Fopen-assistant.io%2Fchat&usg=AOvVaw2BLJ_sUF4zgiHZMHNcFVnd

**Comment by serenalotreck** [comment]
Thank you all so much, that's super helpful!!
