### ISSUE TITLE
"Reformer: The Efficient Transformer" looks awesome. I'd love to see it in the library.

### ISSUE THREAD

**Issue by Alan-Lee123** [huggingface/transformers#2341]
# 🌟New model addition

## Model description
Efficient Transformer with locality-sensitive hashing and reversible layers
https://openreview.net/forum?id=rkgNKkHtvB

## Open Source status

* [. ] the model implementation is available: (give details)
There is an implementation from google
https://github.com/google/trax/blob/master/trax/models/research/reformer.py
* [ ] the model weights are available: (give details)
* [. ] who are the authors: (mention them)
Nikita Kitaev, Lukasz Kaiser, Anselm Levskaya

**Comment by zbloss** [comment]
I have started to refactor the original source code in Pytorch if you'd like to help I'd greatly appreciate it! [https://github.com/zbloss/reformer](https://github.com/zbloss/reformer)

**Comment by lucidrains** [comment]
I have a working implementation at https://github.com/lucidrains/reformer-pytorch !

**Comment by tmabraham** [comment]
Any update on adding this to the library?

**Comment by bratao** [comment]
They published in their blog about it https://ai.googleblog.com/2020/01/reformer-efficient-transformer.html?m=1

**Comment by tmabraham** [comment]
Hence my interest in a huggingface implementation :)

**Comment by digital-thinking** [comment]
Looking forward to see this model in the transformers lib :)

**Comment by cfoster0** [comment]
Don't think we should rush this one. The reformer paper is pretty tricky to implement in a clean way, plus there aren't any pre-trained models that use it yet. Just one person's opinion, though.

**Comment by alexvaca0** [comment]
The implementation by @lucidrains seems to work https://github.com/lucidrains/reformer-pytorch ; it'd be cool if it was included in the transformers library. It seems strange to me that no pretrained Reformer has been uploaded since the paper was released, any ideas why? is it possible that it doesn't work in practice as stated by the authors in the paper? Anyone who has trained a Reformer on their own and have tried it to solve a real problem?
Thank you very much in advance

**Comment by LuoweiZhou** [comment]
Same here, curious to know why. Thank you!

**Comment by flozi00** [comment]
https://github.com/google/trax/blob/master/trax/models/reformer/machine_translation.ipynb

There should be an pretrained model now.
Would be very happy to see Reformer model in this project.

**Comment by MrRace** [comment]
+1

**Comment by julien-c** [comment]
Closed by @patrickvonplaten

**Comment by JulesGM** [comment]
has this been done ?
