### ISSUE TITLE
How to finetune PreTrainedEncoderDecoder

### ISSUE THREAD

**Issue by fengzhangyin** [huggingface/transformers#2343]
## ❓ Questions & Help

PreTrainedEncoderDecoder is great. 
Now I have the following questions :
(1) How to use my data to finetune the PreTrainedEncoderDecoder?
(2) If I want to use the pretrained RoBERTa as encoder and deocder, what should I do ?

**Comment by Hannabrahman** [comment]
Hi,

Thanks for the nice work. I have the same question.
Would appreciate your reply.

**Comment by search4mahesh** [comment]
Yes , example would be nice
