### ISSUE TITLE
”never_split“ not working on BertTokenizer

### ISSUE THREAD

**Issue by lllyyyqqq** [huggingface/transformers#23459]
### System Info

transformers 4.28.1
python 3.8.13

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

- I load BertTokenizer using my own vocab.txt, and add _'[outline]'_ into _never_split_, which is included in my vocab.txt. However,  _'[outline]'_ got splitted. Following is my code:

`tokenizer = BertTokenizer.from_pretrained(pretrained_path,never_split=['[outline]'])   
input = "。[outline]"  
print(tokenizer.tokenize(input))  # ['。', '[', 'out', '##line', ']']
`

- I also do:
`print(tokenizer.basic_tokenizer.tokenize(input))  #['。', '[', 'outline', ']']`

### Expected behavior

When I do:
`tokenizer.tokenize("。[outline]")`
Get the result as `['。', '[outline]']`, the tokens in never_split don't be splited.

**Comment by amyeroberts** [comment]
cc @ArthurZucker @younesbelkada

**Comment by ArthurZucker** [comment]
Sorry, anyway the argument was set to `True` by default so that's not the problem. 
Let's me investigate, in the mean time doing `tokenizer.add_token("[outline]", special_token = True)`" should (I think) prevent it from being split

**Comment by ArthurZucker** [comment]
( the doc mentions :            
```python
 never_split (`List[str]`, *optional*)
                Kept for backward compatibility purposes. Now implemented directly at the base class level (see
                [`PreTrainedTokenizer.tokenize`]) List of token not to split.
```

**Comment by ArthurZucker** [comment]
The best solution is to add the token to the list of special tokens using the `add_token` method

**Comment by lllyyyqqq** [comment]
Yeah, add it as special_token does take care of the splitting problem. But in the latter process, I will decode with argument `skip_special_tokens=True`. Then the token will be skipped, while I don't want it be. For now, I add it to the special token list, but I still suggest fixing the `never_split` argument.

**Comment by ArthurZucker** [comment]
Then that means that the token that you want to add is not `special`. I think that if you add it without the `special_token` set to `True` it should not be spilt no?

**Comment by lllyyyqqq** [comment]
Without `special_token` set to True, it will be splitted.

**Comment by lllyyyqqq** [comment]
In your case, it won't. But I am using a different vocab.txt, it splits.

**Comment by lllyyyqqq** [comment]
Seems like `'[outline]'` will not be added anyway, since it's already in the vocab.

**Comment by ArthurZucker** [comment]
I don't understand. You have a very specific usage, where you don't want to split `[outline]` that is already in your vocab. 
The basic tokenizer works as expected: `tokenizer.basic_tokenizer.tokenize("[outline]")` will not split it. 
When you are calling `tokenize` on the `BertTokenizerClass` the `_tokenize` function is then called, which relies on the `all_special_ids`. That means that the token should be added to both lists. 
```python 
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased", use_fast=False, never_split= ["outline"])
tokenizer.add_tokens("[outline]")
```
I am guessing that this should work

**Comment by ArthurZucker** [comment]
Edit: I manually added "[outline]" to my vocab and it worked.

**Comment by lllyyyqqq** [comment]
Unfortunately, it still doesn't work on my vocab. I think it strictly related to the vocab. So far, only adding it to the special tokens works for me. 
Also, shat I posted before is basic tokenizer split it, `tokenizer.basic_tokenizer.tokenize("[outline]")` splits it into` '[',  'outline', ']'`. The tokenizer then send the split tokens to do Wordpiece instead of fix it to the origin `'[outline]'`. I think that may be the reason.

**Comment by lllyyyqqq** [comment]
[vocab.txt](https://github.com/huggingface/transformers/files/11564244/vocab.txt)
Here is my vocab, you can try on it.

**Comment by ArthurZucker** [comment]
I tried loading a tokenizer using your vocabulary and I cannot reproduce your issue.
Try downloading the latests `transformer` version!

**Comment by lllyyyqqq** [comment]
Why......
I've updated transformers to 4.29.2, still the same result....
here is my code

```python
tokenizer = BertTokenizer.from_pretrained('../base_model/vocab.txt', never_split= ["[outline]"])
tokenizer.add_tokens("[outline]")
print(tokenizer.tokenize("。[outline]"))
# ['。', '[', 'out', '##line', ']']
```

**Comment by ArthurZucker** [comment]
Can you try `tokenizer = BertTokenizer.from_pretrained('../base_model', never_split= ["[outline]"])`
Also I would suggest you create a colab , this will make sure that your cache is not messing with this.

**Comment by lllyyyqqq** [comment]
Here is the Colab result:
![1685020473827](https://github.com/huggingface/transformers/assets/48902561/c8701208-1152-4073-b22f-b337676dc138)

**Comment by ArthurZucker** [comment]
Also you did not add the token using `add_token(..., special_token = False)`

**Comment by lllyyyqqq** [comment]
https://colab.research.google.com/drive/1EStD5K_lQM0-PgMUQ8z273TzAUcgY2IV?usp=sharing
You need to roll down to the bottom to see the code, `add_token(...)` already added.

`additional_special_tokens` add `[outline]` into special tokens too, so it works fine. But it still meets the `skip_special_token` problem. Anyway, this issue is about 'never_split' argument not working, so let's focus on this.

**Comment by ArthurZucker** [comment]
Thanks a lot. 
Indeed the token is not added, because in the `_add_token` a check prevent it to be added if it is already in the vocab. 
Workaround: 
```python 
tokenizer.added_tokens_encoder.update({"[outline]":85})
tokenizer.added_tokens_decoder.update({85:"[outline]"})
tokenizer.unique_no_split_tokens = sorted(set(tokenizer.unique_no_split_tokens).union({"[outline]"})) 
tokenizer._create_trie(tokenizer.unique_no_split_tokens)
``
`
Its is not really elegant indeed. Also adding a token means that whether or not it is in the vocab, we want it to be in the added tokens, so I think it makes sense to add it, even if it exists. WDYT @Narsil

**Comment by ArthurZucker** [comment]
About never split, the last commit is 4 years old, it has never been touch, and I'd rather we find a way to work around your problem using new code rather than changing legacy code!

**Comment by lllyyyqqq** [comment]
Glad we are on the same page in the end.

**Comment by ArthurZucker** [comment]
I am not entirely sure yet whether or not we will support this as the fast ones don't, and my few tests appear to show that it might not be optimal

**Comment by Hir98** [comment]
@lllyyyqqq @ArthurZucker 
i am also facing similar kind of issue like i have product  -> 'Blueberry'.
but when it tokenize it split into to token -> 'blue' and '##berry' .

so i don't want to split word into multiple token with Autotokenizer and Bertokenizer.

can you please help me how can i do this??

**Comment by ArthurZucker** [comment]
you should add `Blueberry` using `tokenizer.add_tokens("Blueberry")` this is now supported by the fast tokenizer

**Comment by Hir98** [comment]
Is this supported in BertTokenizer ??

**Comment by ArthurZucker** [comment]
Actually yes! 
Previously I said the following:
> - fast does not support this and we want to keep fast stable
- it's a breaking change
- seems to be a specific usage, not the one intended for add_tokens

but this is now possible 😉 see the following: 
```python 
>>> tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
>>> tokenizer.add_tokens("[outline]")
>>> print(tokenizer.tokenize("。[outline]"))
['。', '[outline]']
```
I tested with both fast and slow and it worked as expected 🤗
