### ISSUE TITLE
An ability to pass a function to tokenizer to transform prompt

### ISSUE THREAD

**Issue by nikitastaf1996** [huggingface/transformers#23470]
### Feature request

Models often work best with specific prompt template.And sometimes [prefix](https://huggingface.co/docs/transformers/v4.29.1/en/main_classes/configuration#transformers.PretrainedConfig.prefix) is not enough.
An ability to pass function to transform prompt would be excellent.

Example
```
def transform_prompt(prompt:str) -> str:
return f"""
### Instruction: {prompt}
### Assistant:
"""

pipeline = TextGenerationPipeline(model=model, tokenizer=tokenizer,max_new_tokens=256,temperature=0.1,transform=transform_prompt)
```

Providing text template is also an option.But in my belief it would be more holistic approach.

### Motivation

I am a little frustrated with the need to define CustomLLM in langchain in order to accomodate the model prompt template. And i believe thats not the only use case for it. Many models require special prompt template.

### Your contribution

I am sorry but no. I am not python programmer.

**Comment by amyeroberts** [comment]
Hi @nikitastaf1996, thanks for raising this issue. 

So that we can best understand the proposed feature - could you explain a bit more about the utility this would unlock? At the moment, it seems that a user could transform their prompts as needed before passing to the pipeline e.g.:

```python
def transform(prompt: str) -> str:
    ...

prompt = transform(original_prompt_string)
pipeline = TextGenerationPipeline(model=model, tokenizer=tokenizer, max_new_tokens=256, temperature=0.1)
outputs = pipeline(prompt)
```

cc @Narsil @gante

**Comment by Narsil** [comment]
I think your custom LLM is perfectly fine imo.

You have other ways to define it actually. Introducting `transform` function would bloat everything up IMHO and what you really need to do is just send a preprompted text to the pipelines like what you are doing. The `stop` part can also be implemented with `generate` arguments I think. (`stop_sequence`)

https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/text_generation.py#L138

**Comment by nikitastaf1996** [comment]
The it's finished.
