### ISSUE TITLE
graphormer.collating_graphormer.preprocess_item TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

### ISSUE THREAD

**Issue by YueZhengMeng** [huggingface/transformers#23474]
### System Info

- `transformers` version: 4.28.1                            
- Platform: Windows-10-10.0.19045-SP0                       
- Python version: 3.9.15                                    
- Huggingface_hub version: 0.10.1                           
- Safetensors version: not installed                        
- PyTorch version (GPU?): 1.13.1 (True)                     
- Tensorflow version (GPU?): not installed (NA)             
- Flax version (CPU?/GPU?/TPU?): not installed (NA)         
- Jax version: not installed                                
- JaxLib version: not installed                             
- Using GPU in script?: <fill in>                           
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The transformers.models.graphormer.collating_graphormer.preprocess_item cause TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
When data_processed = dataset.map(preprocess_item, batched=False), the dataset is ogb-molhiv
Because the data type in this function is np.int64, but in transformers\models\graphormer\algos_graphormer.pyx is np.int32 or np.long
I fixed it by replace "long" in algos_graphormer.pyx line 88 and 89 by np.int64 ,and replace all 32 in algos_graphormer.pyx by 64
But I don't think this is a appropritate aproach

### Expected behavior

how to fix this issue without modifying the library code

**Comment by amyeroberts** [comment]
cc @clefourrier

**Comment by clefourrier** [comment]
Hi @YueZhengMeng, thank you for reporting this!
I'll check it this week. Btw, using int64s everywhere will make the memory explode considerably faster for large graphs, if you need to change it manually in the mean time, it's likely you should use int32s instead.

**Comment by clefourrier** [comment]
I have not been able to reproduce your bug, but I'm not on a Windows machine.
Could you provide me with a snippet of code and the complete trace of your error?

**Comment by SacusCreed** [comment]
Same issue. Also on windows. The autors solution worked for me. Change everything to 32 instead didn't work.
