### ISSUE TITLE
GLUE Benchmark Hyperparameters

### ISSUE THREAD

**Issue by shreydesai** [huggingface/transformers#2351]
## ❓ Questions & Help

In the `run_glue.py` script, are the hyperparameters for running BERT, RoBERTa, ALBERT, etc. the exact same? The documentation does not seem to outline separate hyperparameters, but the papers of each respective model show different hyperparameter ranges. I'm wondering if this was taken account when reporting the benchmark results.

**Comment by LysandreJik** [comment]
Hi, each result available on the [example page](https://huggingface.co/transformers/examples.html) shows the command that was used, displaying the hyper-parameters that are different from the defaults.
