### ISSUE TITLE
transformers command not found after installing transformers using pip

### ISSUE THREAD

**Issue by ManasRMohanty** [huggingface/transformers#2355]
I wanted to convert TF checkpoints to pytorch saved files and thus I followed instructions as mentioned in the link https://huggingface.co/transformers/converting_tensorflow_models.html 

Thus, I installed PyTorch, Tensorflow and then transformers. But after doing so, when I ran the command, my system prompted me transformers command not found. 

What can be the issue here.

**Comment by DaniilRoman** [comment]
I have this problem also. 
Installed with pip3 (maybe this is the necessary information)

**Comment by mfuntowicz** [comment]
Hi @ManasRMohanty, @DaniilRoman,

In 2.3.0 we introduced some new commands from the cli, which are now provided through **transformers-cli**.

Can you please try the following: 

```bash
transformers-cli convert --model_type <model_type> --tf_checkpoint /path/to/tf_model.ckpt --config /path/to/model.json --pytorch_dump_output /path/to/pytorch_model.bin
```

Let us know :)

**Comment by julien-c** [comment]
@mfuntowicz Do you want to update the doc? (i can do it too if needed)

**Comment by ManasRMohanty** [comment]
@mfuntowicz @julien-c 
Yes, the above worked for me in linux. Thus, I am closing the issue.

Also, I checked in https://huggingface.co/transformers/converting_tensorflow_models.html and I can see that the document is updated, but the convert parameter is missing there, so please update that.

**Comment by mfuntowicz** [comment]
@ManasRMohanty I've updated the documentation with the missing keyword. Thanks for reporting 👍
