### ISSUE TITLE
How to fine-tune PreTrainedEncoderDecoder on new dataset?

### ISSUE THREAD

**Issue by Hannabrahman** [huggingface/transformers#2364]
## ❓ Questions & Help

Hi,

Many thanks for your recent work implementing [this paper](https://arxiv.org/pdf/1907.12461.pdf).
I wonder if you have or can provide script and documentation for fine-tuning PreTrainedEncoderDecoder on new dataset?

Many thanks

**Comment by Josh-Payne** [comment]
Seconded. Is there a way to fine-tune any seq2seq model in huggingface?

**Comment by BramVanroy** [comment]
@Josh-Payne You can have a look at https://github.com/huggingface/transformers/blob/9df74b8bc42eedc496f7148b9370728054ca3b6a/src/transformers/modeling_encoder_decoder.py
