### ISSUE TITLE
save all custom files in the meanwhile

### ISSUE THREAD

**Issue by JaheimLee** [huggingface/transformers#23644]
### Feature request

Many models in your huggingface hub have their custom files, like [mpt](https://huggingface.co/mosaicml/mpt-7b-instruct). However, your `save_pretrained` func can't save them all. Is it possible to save all of them at the same time?

### Motivation

It's pretty useful when you fine-tune the model and want to save it in a new directory.

### Your contribution

no

**Comment by amyeroberts** [comment]
Hi @JaheimLee, thanks for raising this issue. 

Which files specifically are being referred to when you say "custom files"?

**Comment by JaheimLee** [comment]
> Hi @JaheimLee, thanks for raising this issue.
> 
> Which files specifically are being referred to when you say "custom files"?

Like the model file which is not merged into transformers. For example:
https://huggingface.co/mosaicml/mpt-7b-instruct/blob/main/configuration_mpt.py
https://huggingface.co/mosaicml/mpt-7b-instruct/blob/main/adapt_tokenizer.py
https://huggingface.co/mosaicml/mpt-7b-instruct/blob/main/modeling_mpt.py
...
