### ISSUE TITLE
upgrading new transformer doesn't work

### ISSUE THREAD

**Issue by ehsan-soe** [huggingface/transformers#2365]
## ❓ Questions & Help

Hi,

I have pulled the repo again since a lot of stuff changed/added.
When I try to use ```pip install --upgrade .``` command, nothing changes and I am stuck in the following step forever:
```
(py36) pytorch-transformers$ pip install --upgrade .
Processing /home/pytorch-transformers

```

Plus, since a lot of folders are renamed and scripts moved to ```src``` folder, whenI try to do ```from transformers import BertTokenizer, BertModel, BertForMaskedLM```
I get following error:
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-34ecfe73cb1a> in <module>
      1 import torch
----> 2 from transformers import BertTokenizer, BertModel, BertForMaskedLM, BertConfig, BertForPreTraining, BertConfig
      3 
      4 # OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
      5 import logging

ImportError: cannot import name 'BertTokenizer' from 'transformers' (unknown location)
```

Would you please help with this? What is the reason to move to src?

**Comment by aaugustin** [comment]
Previously you were relying on `transformers` being implicitly added to `PYTHONPATH` when you were working from the source of the repository. This breaks if you move to another directory, like `examples`.

`pip install .` makes `transformers` available in your virtualenv regardless of where you're working.

It's unclear to me why the installation is stuck.

Could you run the following commands?

```
pip uninstall transformers
pip --version
pip install --verbose .
```

**Comment by ehsan-soe** [comment]
Thanks for replying @aaugustin .
my pip version is 19.1.1 
However, I ended up cloning the whole repo again and install fresh.
I will close it for now.

**Comment by aaugustin** [comment]
OK, that was going to be my next suggestion if the situation didn't improve!
