### ISSUE TITLE
Metas MMS speech recognition 

### ISSUE THREAD

**Issue by flozi00** [huggingface/transformers#23665]
### Model description

In their Blogpost they are writing it's 1B sized wav2vec 2 models, so only a new converter script should be needed?

A nice alternative to compare to whisper

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available

### Provide useful links for the implementation

https://github.com/facebookresearch/fairseq/tree/main/examples/mms

@sanchit-gandhi 
@patrickvonplaten FYI

**Comment by JoesSattes** [comment]
Interested Model!! Thank @flozi00 to open request.

**Comment by NielsRogge** [comment]
👀 https://huggingface.co/models?other=mms

**Comment by sorenmulli** [comment]
> :eyes:  https://huggingface.co/models?other=mms

Is this the pretrained model? 
I would like to try to also convert the ASR model; any pointers? 

The scripts I am looking at (such as [this very useful boi](https://huggingface.co/HfSpeechUtils/convert_wav2vec2_to_hf/blob/main/run_convert.sh)) seem to require dict and HF config but maybe it is the same configuration as `facebook/wav2vec2-large` :thinking:

**Comment by patrickvonplaten** [comment]
Leeez go - working on the conversion as we speak :-)

**Comment by LYPinASR** [comment]
I also made a request in _#23811_. Looking forward to it!

**Comment by patrickvonplaten** [comment]
PR merged.

Also see:
- https://huggingface.co/docs/transformers/main/en/model_doc/mms
- https://github.com/huggingface/transformers/pull/23813
- https://huggingface.co/facebook/mms-1b-all
