### ISSUE TITLE
FP8 inference and FP8 KV cache

### ISSUE THREAD

**Issue by SinanAkkoyun** [huggingface/transformers#23660]
### Feature request

Hi!
Could anyone please help me with using HuggingFace models (LLaMa [or if LLaMa is difficult, MPT-7b]) with the TransformerEngine TE FP8 inference? We really need the speedup

https://github.com/NVIDIA/TransformerEngine/issues/199
This is a somewhat related issue to this topic.

### Motivation

Faster inference and more specialized tensor operations means less cost and less latency.

### Your contribution

I would really love to test suggestions out as I have temporary access to a H100 cloud GPU.
I am not sufficient in porting the models myself which is why I created this issue.

I really appreciate any help, thank you very much.

**Comment by AhsanAli1288** [comment]
@SinanAkkoyun  have you find the solution how to use transformerengine with Llama?

**Comment by maxpain** [comment]
Any updates?

**Comment by amyeroberts** [comment]
Gentle ping @fxmarty

**Comment by amyeroberts** [comment]
Another ping @fxmarty. Could you nominate someone to take this over for you?

**Comment by amyeroberts** [comment]
cc @IlyasMoutawwakil
