### ISSUE TITLE
How to check word ids for BartTokenizer? 

### ISSUE THREAD

**Issue by akesh1235** [huggingface/transformers#23679]
one single words is getting splitted to multiple tokens, and i tried to check word_ids by using **t.word_ids()** 
i got an Error  
**ValueError: word_ids() is not available when using non-fast tokenizers (e.g. instance of a `XxxTokenizerFast` class).**

**Comment by sgugger** [comment]
As the error indicates, you need to use `BartTokenizerFast` to use this method.
