### ISSUE TITLE
About Tokenizer 

### ISSUE THREAD

**Issue by Yu-xm** [huggingface/transformers#23676]
### Who can help?

@ArthurZucker @younesbelkada @ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

tokenizer = BertTokenizer.from_pretrained(gpt2_path)

### Expected behavior

I see the following code:

tokenizer = BertTokenizer.from_pretrained(gpt2_path)

This code uses BertTokenizer to read GPT2 related files. What is the difference between the above code and the following two codes?

tokenizer = BertTokenizer.from_pretrained(bert_path)
tokenizer = AutoTokenizer.from_pretrained(gpt2_path)

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for questions around the library as we keep issues for bugs and feature requests only.
