### ISSUE TITLE
Unable to download Google/vit-base-patch-16-224 / Getting 404 tepo not found error

### ISSUE THREAD

**Issue by rsadaphule** [huggingface/transformers#23696]
### System Info

I am running the following code on Google Colab to download pretrained Vision Transformer. I am authenticating with proper write access token. I get repo not found error.

Code:
from transformers import AutoModelForImageClassification, AutoFeatureExtractor
import torch
model_id = 'google/vit-base-patch-16-224'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = AutoModelForImageClassification.from_pretrained(model_id, use_auth_token=WRITE_TOKEN_HF).to(device)
model.eval()

Env: Google Colab

Error:
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    238     try:
--> 239         response.raise_for_status()
    240     except HTTPError as e:

12 frames
HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/google/vit-base-patch-16-224/resolve/main/config.json

The above exception was the direct cause of the following exception:

RepositoryNotFoundError                   Traceback (most recent call last)
RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-646cdb2a-00843123602c48d04fc1bc45)

Repository Not Found for url: https://huggingface.co/google/vit-base-patch-16-224/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py](https://localhost:8080/#) in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, use_auth_token, revision, local_files_only, subfolder, user_agent, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash)
    422 
    423     except RepositoryNotFoundError:
--> 424         raise EnvironmentError(
    425             f"{path_or_repo_id} is not a local folder and is not a valid model identifier "
    426             "listed on '[https://huggingface.co/models'\nIf](https://huggingface.co/models'/nIf) this is a private repository, make sure to "

OSError: google/vit-base-patch-16-224 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AutoModelForImageClassification, AutoFeatureExtractor
import torch
model_id = 'google/vit-base-patch-16-224'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = AutoModelForImageClassification.from_pretrained(model_id, use_auth_token=WRITE_TOKEN_HF).to(device)
model.eval()

### Expected behavior

The model should be downloaded without error

**Comment by sgugger** [comment]
As the error indicates, `google/vit-base-patch-16-224` does not exist on the Hub. You can browse ViT models [here](https://huggingface.co/models?other=vit).
