### ISSUE TITLE
Pipelines: add PoS support

### ISSUE THREAD

**Issue by arnaudmiribel** [huggingface/transformers#2370]
## 🚀 Feature

As `Pipelines` were recently added for many tasks including NER, Sentiment Analysis, it'd be great to also enable Part-of-Speech tagging.

## Motivation

PoS tagging is a very useful task, and often used as an evaluating downstream task for new models.

## Additional context

Current available tasks for `Pipelines` are described [here](https://github.com/huggingface/transformers/blob/master/src/transformers/pipelines.py#L831).

**Comment by julien-c** [comment]
We now have a more general `TokenClassificationPipeline`, @arnaudmiribel (this is just an alias to the `NerPipeline`)
