### ISSUE TITLE
ImportError: cannot import name 'PartialState' from 'transformers.trainer_pt_utils'

### ISSUE THREAD

**Issue by hoangledoan** [huggingface/transformers#23744]
### System Info

`transformers` version: 4.28.0
`accelerate` version: 0.19.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`from transformers.trainer_pt_utils import PartialState`

### Expected behavior

it cannot import the class, eventhough I tried to downgrade transformers and install accelerate

**Comment by sgugger** [comment]
That class is defined in Accelerate, not in `trainer_utils`.
