### ISSUE TITLE
LION optimizer calling error

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#23748]
TypeError: Lion.__init__() got an unexpected keyword argument 'is_paged'

**Comment by sgugger** [comment]
As said previously, there is nothing we can do if you do not follow the issue template and post a code reproducer.

**Comment by lucasjinreal** [comment]
@sgugger hello, this is what I done:

```
trainer = transformers.Trainer(
        model=model,
        train_dataset=train_data,
        eval_dataset=val_data,
        args=transformers.TrainingArguments(
            deepspeed=deepspeed,
            per_device_train_batch_size=micro_batch_size,
            gradient_accumulation_steps=gradient_accumulation_steps,
            warmup_ratio=0.1,
            num_train_epochs=num_epochs,
            learning_rate=learning_rate,
            # fp16=True,
            fp16=not int8_train,
            logging_steps=10,
            # optim="adamw_torch",
            optim="paged_lion_32bit",
            evaluation_strategy="steps" if val_set_size > 0 else "no",
            save_strategy="steps",
            eval_steps=50 if val_set_size > 0 else None,
            save_steps=50,
            output_dir=output_dir,
            save_total_limit=5,
            load_best_model_at_end=True if val_set_size > 0 else False,
            ddp_find_unused_parameters=False if ddp else None,
            group_by_length=group_by_length,
            report_to="wandb" if use_wandb else None,
            run_name=wandb_run_name if use_wandb else None,
        ),
        data_collator=transformers.DataCollatorForSeq2Seq(
            tokenizer, pad_to_multiple_of=8, return_tensors="pt", padding=True
        ),
    )
```

the newly commited LION seems can not load properly, please have a test

**Comment by sgugger** [comment]
This is not something I can reproduce as many of the objects you use are undefined.

**Comment by louisowen6** [comment]
I believe this is because of you're using previous version of `bitsandbytes`. In the latest version, there's an additional arguments called `is_paged`

https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/optim/lion.py#L9

**Comment by lucasjinreal** [comment]
@louisowen6  Hi, does there any minimal examples on how to enable LION optimizer with llama along with training with deepspeed?
Just can't found such a detailed describe on this, it could be better if a experiment result compare with AdamW and LION on llama model
