### ISSUE TITLE
transformers-cli serve  doesn't support  muti-workers

### ISSUE THREAD

**Issue by CaoYiwei** [huggingface/transformers#23777]
### System Info

transformers version=4.28.1

error:
You must pass the application as an import string to enable "reload" or "workers"

transformers-cli serve uses fastapi with uvicorn, the application adds routes in a class rather than decorators. In this way, uvicorn run can not import the applications. I don't have a solution yet. Does anyone have ideas to fix this ?

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

transformers-cli serve --workers 2  

error:
You must pass the application as an import string to enable "reload" or "workers"

### Expected behavior

cli command supports muti-workers

**Comment by sgugger** [comment]
This is not an API we still maintain FYI.
