### ISSUE TITLE
CodeT5pEncoderDecoderModel does not support `device_map='auto'` yet.

### ISSUE THREAD

**Issue by karths8** [huggingface/transformers#23784]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.24.0
- Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
- Python version: 3.10.9
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.12.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Who can help?

@ArthurZucker  @younesbelkada 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Loaded the InstructCodeT5+ model as per https://huggingface.co/Salesforce/instructcodet5p-16b
2. Tried to use LoRA to fine-tune InstructCodeT5+ on NL to code translation task. Code and Traceback given below:
```
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch
token_id="Salesforce/instructcodet5p-16b"
tokenizer = AutoTokenizer.from_pretrained(token_id)
model = AutoModelForSeq2SeqLM.from_pretrained(token_id,
                                              torch_dtype=torch.float16,
                                              low_cpu_mem_usage=True,
                                              trust_remote_code=True, decoder_start_token_id=1, pad_token_id=-100, load_in_8bit=True, device_map='auto').to(device)
```
Error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-1436d2a64ffb> in <module>
     10 
     11 # load model from the hub
---> 12 model = AutoModelForSeq2SeqLM.from_pretrained(model_id,
     13                                               torch_dtype=torch.float16,
     14                                               low_cpu_mem_usage=True,

~/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    460                 class_ref, pretrained_model_name_or_path, **hub_kwargs, **kwargs
    461             )
--> 462             return model_class.from_pretrained(
    463                 pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    464             )

~/.cache/huggingface/modules/transformers_modules/instructcodet5p-16b/modeling_codet5p.py in from_pretrained(cls, *args, **kwargs)
    855             )
    856         kwargs["_fast_init"] = False
--> 857         return super().from_pretrained(*args, **kwargs)
    858 
    859     def forward(

~/.local/lib/python3.8/site-packages/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   2683 
   2684             if model._no_split_modules is None:
-> 2685                 raise ValueError(f"{model.__class__.__name__} does not support `device_map='{device_map}'` yet.")
   2686             no_split_modules = model._no_split_modules
   2687             if device_map not in ["auto", "balanced", "balanced_low_0", "sequential"]:

ValueError: CodeT5pEncoderDecoderModel does not support `device_map='auto'` yet.
```
Seems Like this functionality is not included yet. When to expect it to be added? Thanks in advance!

### Expected behavior

Expect the model to get loaded without any error

**Comment by ArthurZucker** [comment]
Based on the traceback, I would suggest the authors to update their code to add a `_no_split_module` class variable, which would fix the error. Now we don't necessarily have a say on other's repo, I would suggest you open an Issue on the hub (or event better a PR) to support this.

**Comment by karths8** [comment]
@ArthurZucker it seems like the issue is resolved in https://huggingface.co/Salesforce/instructcodet5p-16b/discussions/1. Thanks for the help!
