### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by lazytensor** [huggingface/transformers#23815]
### System Info

Facing error when doing`from transformers import Trainer`

`RuntimeError: Failed to import transformers.training_args because of the following error (look up to see its traceback): cannot import name 'PartialState' from 'accelerate' (/opt/conda/lib/python3.10/site-packages/accelerate/__init__.py)`

Here is the environment

- `transformers` version: 4.29.2
- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.10.10
- Huggingface_hub version: 0.14.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.0 (True)
- Tensorflow version (GPU?): 2.12.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.6.10 (gpu)
- Jax version: 0.4.10
- JaxLib version: 0.4.7
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

Solutions tried `pip install -U accelerate`. But it is still not resolved

### Who can help?

 @pacman100 @ArthurZucker @sgugger 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

`from transformers import Trainer`

### Expected behavior

Expecting no error

**Comment by sgugger** [comment]
Could you let us know your version of Accelerate?

**Comment by nicir** [comment]
same problem

**Comment by nicir** [comment]
This worked at my Kaggle Notebook 

https://stackoverflow.com/questions/76363436/cannot-import-name-partialstate-from-accelerate-when-using-huggingface-pipel
