### ISSUE TITLE
How to convert flax model to pytorch?

### ISSUE THREAD

**Issue by GuodongFan** [huggingface/transformers#23810]
### Feature request

run_t5_mlm_flax.py
only generate a `flax_model.msgpack`
，but i want to obtain `pytorch_model.bin`.

### Motivation

convert msgpack to bin 

### Your contribution

none

**Comment by jzssz** [comment]
how to convert a .msgpack (flax/jax format) model weights to .bin (huggingface format) or .pth (pytorch format)

**Comment by ArthurZucker** [comment]
@jzssz please refrain from asking the same question on so many issues 😅 I answered https://github.com/huggingface/transformers/issues/26813#issuecomment-1835703292
