### ISSUE TITLE
how to use distilledgpt2

### ISSUE THREAD

**Issue by jackfeinmann5** [huggingface/transformers#2381]
Hi
I want to use distilledgpt2, I cannot see the config file and modeling files, could you please assist me how to use it
thanks

**Comment by LysandreJik** [comment]
Hi, you can use it as such:

```py
from transformers import GPT2Model, GPT2Tokenizer

model = GPT2Model.from_pretrained("distilgpt2")
tokenizer = GPT2Tokenizer.from_pretrained("distilgpt2")
```

You can see the list of available models in the [pretrained section of our documentation](https://huggingface.co/transformers/pretrained_models.html).
