### ISSUE TITLE
Sliding window for finetuning 

### ISSUE THREAD

**Issue by DanaTurkif** [huggingface/transformers#23835]
### Feature request

The sliding window feature is important since many models have limited size (BERT 512 token) , as far as i know the feature is available when using the pipelines for inference however when finetuning it's not. 

 

### Motivation

I'm trying to finetune BERT models since they reached state of the art in many NLP tasks, but especially  for NER tasks and most of my documents are far larger than 512 tokens and truncating them will ruin the context. 

### Your contribution

I've been trying to implement sliding window manually by using the available features such as stride,  return_overflowing_tokens

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask such questions. The feature is implemented via `stride` and `return_overflowing_tokens` in tokenizers as you note.
