### ISSUE TITLE
Parameter: encoder_no_repeat_ngram_size or something that makes model not repeat input tokens in the output.

### ISSUE THREAD

**Issue by Oxi84** [huggingface/transformers#23834]
### Feature request

Could you please add more explanations in the docs about  what encoder_no_repeat_ngram_size practically does.

It says in the docs that it makes sure that ngram sequence of specified length that is in the encoder input ids does not repeat in the decoder input ids, but I have no idea how this parameter changes decoder outputs ids.

I use it with t5

  

### Motivation

 When i set encoder_no_repeat_ngram_size=4 it does not repeat even ngram 2-3 in the output mostly.

### Your contribution

        with torch.no_grad():
                beam_outputs = model1a.generate(
                    input_ids=input_ids, attention_mask=attention_masks,                
                    encoder_no_repeat_ngram_size = 4,
                    do_sample = False,
                    num_return_sequences=4,
                    num_beams=4,
                    max_length=128
                    )

**Comment by sgugger** [comment]
cc @gante

**Comment by gante** [comment]
Hey @Oxi84 👋 

Without a stand-alone short script to reproduce the issue (as well as the desired output), it is hard for me to help :)

Nevertheless, I suspect the keyword argument you want to use is `no_repeat_ngram_size`, and not `encoder_no_repeat_ngram_size` :)
