### ISSUE TITLE
The method os.rename() in file_utils.py  make a permissionError

### ISSUE THREAD

**Issue by heroazhe** [huggingface/transformers#2385]
## ❓ Questions & Help
Is someone happen to this question?

![image](https://user-images.githubusercontent.com/22883367/71649688-af981c00-2d4b-11ea-811b-7fd9ebef4776.png)

**Comment by light-dawn** [comment]
I have the same problem when downloading the pre-trained tokenizer. I also need help!

**Comment by heroazhe** [comment]
> I have the same problem when downloading the pre-trained tokenizer. I also need help!

Online download often occur different problems,so i download it first and use it locally.

**Comment by thomwolf** [comment]
Ok this should be solved on master now that #2384 is merged
