### ISSUE TITLE
:grey_question: Custom tool creation and pip requirements :grey_question: 

### ISSUE THREAD

**Issue by adriens** [huggingface/transformers#23854]
# :grey_question: About

i'm currently working on  [Creating a new tool](https://huggingface.co/docs/transformers/en/custom_tools#creating-a-new-tool), ... and this tool will rely on a custom `pypi` package.
In the documentation, you show some classic imports but not custom ones.

# :pray: Question

If I create a custom tool, how to make sure that the final user won't be embarrased by my internal package ?... ie. I would like the end-user to only have to import my custom tool without having to install the `pypi` package, so here comes the (newbee/noob)  question:

> "How to package a custom tool that relies itself on a custom `pypi` package ?"

Thank you in advance for your help.

**Comment by sgugger** [comment]
It's not possible, they will need to install the packages required by your tool.

**Comment by adriens** [comment]
Ok, thanks a lot for your answer @sgugger :pray:
