### ISSUE TITLE
Code formatting issue with Korean translation of quicktour.mdx

### ISSUE THREAD

**Issue by GarrettDaniel** [huggingface/transformers#23874]
### System Info

N/A

### Reproduction

In the Korean translation of quicktour.mdx found [here](https://github.com/huggingface/transformers/blob/main/docs/source/ko/quicktour.mdx), there is a small formatting issue in the bash commands to install pytorch and tensorflow.
![image](https://github.com/huggingface/transformers/assets/36463300/3f750ef3-ba13-4977-b8e5-52ec7d8d396e)

### Expected behavior

- The install commands should be rendered as code blocks in the markdown file.
- The formatting can be fixed by adding a newline/return between the two commands like this:
```bash pip install torch```
```bash pip install tensorflow```

Furthermore, these commands can be simplified to one line by using the following syntax, which will install both PyTorch and Tensorflow:
```!pip install torch tensorflow```

I'd be happy to make these changes and help with some of the other Korean documentation.

**Comment by ArthurZucker** [comment]
Hey! Thanks for reporting, feel free to open a PR and ping me 😉

**Comment by GarrettDaniel** [comment]
It looks like this issue was resolved on the docs website https://huggingface.co/docs/transformers/v4.30.0/ko/quicktour.  Closing this issue
