### ISSUE TITLE
MarkupLM: feature_extraction_markuplm.py only extracts SearchableText

### ISSUE THREAD

**Issue by orenshaniathuji** [huggingface/transformers#23887]
### System Info

- `transformers` version: 4.29.2
- Platform: Linux-6.1.22-aufs-1-x86_64-with-glibc2.31
- Python version: 3.9.2
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.1+cu117 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run some MArkupLM code that uses the extractor over HTML that uses template tags, etc. (for example, pages of a wiki.js wiki ).  See that you will miss much of the content

### Expected behavior

feature_extraction_markuplm.py should extract all *Text bs4 types, not just SearchableText

**Comment by sgugger** [comment]
Please follow the issue template. There is no reproducer and the expected behavior is very unclear.
