### ISSUE TITLE
save_pretrained 4-bit models with bitsandbytes

### ISSUE THREAD

**Issue by westn** [huggingface/transformers#23904]
With the latest version of bitsandbytes (0.39.0) library, isn't it possible to serialize 4-bit models then?

Thus this section should be updated to allow the user to save these models.
https://github.com/huggingface/transformers/blob/68d53bc7178866821282f45732c1e465f5160fa6/src/transformers/modeling_utils.py#LL1704C36-L1704C36

I'm mainly looking at this article to see what got produced lately in the area: https://huggingface.co/blog/4bit-transformers-bitsandbytes

I aim to quantize a model to 4-bit, enabling it to be used in e.g., GPT4all and other CPU platforms.

**Comment by sgugger** [comment]
cc @younesbelkada

**Comment by younesbelkada** [comment]
Hi @westn 
Thanks for the issue, I don't think 4bit models are serializable yet. Let me double check that with the author of bitsandbytes and get back to you

**Comment by younesbelkada** [comment]
Also note that 4bit / 8bit is also applicable to GPU / CUDA devices, you cannot run quantized models with bitsandbytes on a CPU device

**Comment by younesbelkada** [comment]
Hi @westn 
Currently it is not possible to save 4bit models but this is in the roadmap of bitsandbytes for the next releases. We will keep you posted!

**Comment by jameswu2014** [comment]
Hi, @younesbelkada , Whether 4bits/8bits models can be saved now?

**Comment by younesbelkada** [comment]
See linked bnb issue: https://github.com/TimDettmers/bitsandbytes/issues/695

**Comment by kbulutozler** [comment]
Is there any update on this? @nathan-az @younesbelkada

**Comment by younesbelkada** [comment]
hi @kbulutozler 
Yes, @poedator is working on it in https://github.com/huggingface/transformers/pull/26037 and the corresponding bnb PR is here: https://github.com/TimDettmers/bitsandbytes/pull/753
