### ISSUE TITLE
FP-16 training producing nans on t5-large/flan-t5-xl

### ISSUE THREAD

**Issue by cassianlewis** [huggingface/transformers#23918]
### System Info

This was an issue a while back but seems to have resurfaced - https://discuss.huggingface.co/t/t5-fp16-issue-is-fixed/3139

I have tested the exact following code on `t5-small` and `t5-base` and they work fine. However, when using `t5-large` and/or `flan-t5-xl`, the model produces nan outputs. This is solely a result of using half precision (ignore the multiple GPUs, strategy etc, I have tested with every other variation):

```
trainer = pl.Trainer(
    precision="16",
    accelerator='gpu',
    strategy='auto',
    devices=4,)
```

I am using `transformers == 4.28.1` and `lightning == 2.0.0`

Any ideas/help appreciated
Thanks!

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
trainer = pl.Trainer(
    precision="16",
    accelerator='gpu',
    strategy='auto',
    devices=4,)
```

### Expected behavior

Nans!!!

**Comment by amyeroberts** [comment]
Hi @cassianlewis, thanks for reporting this issue. 

There's been a few updates recently regarding handling of loading of model weights and their precision. Could you update your transformers version to the latest release and let us know if the issue still persists? 

Could you also provide some more details about the other strategies tested (when this behaviour doesn't occur)? 

cc @younesbelkada

**Comment by cassianlewis** [comment]
Hi @amyeroberts, I think the issue is more with the model itself. See https://www.philschmid.de/fine-tune-flan-t5-deepspeed

`When fine-tuning T5 models we cannot use fp16 since it leads to overflow issues, see: [#4586](https://github.com/huggingface/transformers/issues/4586), [#10830](https://github.com/huggingface/transformers/issues/10830), [#10956](https://github.com/huggingface/transformers/pull/10956)`

(t5 was trained with bf16)

**Comment by amyeroberts** [comment]
@cassianlewis Thanks for providing these details and links. 

Looking at the linked issues and Philip's blog, unfortunately I don't think there's much that can be done to resolve this. We can leave this issue open for now for people to share any updates or solutions they may have.

**Comment by younesbelkada** [comment]
Hi @cassianlewis 
I think it is expected that pure fp16 training leads to unstable behaviour for some models; have you tried to train the models in bf16 precision?

**Comment by cassianlewis** [comment]
@younesbelkada My Tesla T4 doesn't currently support bf16 (you need Ampere architecture), so I will get back to you on that
