### ISSUE TITLE
4.29.0 bug

### ISSUE THREAD

**Issue by macheng6** [huggingface/transformers#23927]
### System Info

The dp mode of 4.29.0 seems to have a bug. When forwarding, the dtype of the model will be changed to torch.int64, which will cause the torch.finfo function in the get_extended_attention_mask function to report an error

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

no

### Expected behavior

no

**Comment by sgugger** [comment]
That's why there is the patch 4.29.2
