### ISSUE TITLE
DocumentQuestionAnsweringTool docstring is incorrect

### ISSUE THREAD

**Issue by Adam-D-Lewis** [huggingface/transformers#23921]
### System Info

N/A

### Who can help?

https://github.com/huggingface/transformers/blob/fabe17a726bbf6081cfbcc975d8ac451a81f3e2d/src/transformers/tools/document_question_answering.py#LL32C9-L34C80 is wrong.  The inputs are image: "Image", question: str.  I was trying transformers agent with a task like 

```
agent.run("Given the pdf at <insert URL>, tell me <insert question>")
```
and it was failing with `TypeError: DocumentQuestionAnsweringTool.encode() got an unexpected keyword argument 'document'` because of the docstring issue.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

N/A

### Expected behavior

N/A

**Comment by sgugger** [comment]
Thanks for flagging! Would you like to open a PR to fix this? The proper fix should be to rename the input `image` to `document` (not change the description).

**Comment by Adam-D-Lewis** [comment]
Here's a draft https://github.com/huggingface/transformers/pull/23939.  Please correct the rest for me if it's not quite right.  Thanks!

**Comment by Adam-D-Lewis** [comment]
Fixed by https://github.com/huggingface/transformers/pull/23939
