### ISSUE TITLE
Pretrained model installation issue

### ISSUE THREAD

**Issue by pranjalsharma26** [huggingface/transformers#2394]
I run the script for this repo "https://github.com/alexa/wqa_tanda" in which i need to run the run_glue.py file from Transformer Model, while running that script it gives an error-
Couldn't reach server at "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json to download pretrained model configuration file" as shown -
![Screenshot (214)](https://user-images.githubusercontent.com/48346579/71734743-950c9280-2e72-11ea-9507-c04b0ab5ed52.png)

**Comment by mandubian** [comment]
The file on S3 seems accessible right now. Did you try to reach it directly from your machine and from console to check you have no network issue?

**Comment by pranjalsharma26** [comment]
No, my network is having no issues I verified it, and from console it is not accessible. The required pretrained model is to be installed from command only as per code. The same issue still exists.

**Comment by mandubian** [comment]
Please, could you try calling python directly from console to check we have the same behavior?

```python
from transformers.modeling_auto import AutoModel

AutoModel.from_pretrained("bert-based-uncased")
```

if it doesn't fail and shows the model (as it happens in my console), it means you have access to the S3 and the issue is somewhere else.

**Comment by pranjalsharma26** [comment]
In the same py file I need to write this lines ?
Yes, I'm calling python from console from initial phase.

**Comment by mandubian** [comment]
no need of a py file, just in a python3 console, you can type those commands directly (as long as you have pip installed transformers)... if you haven't a recent version with `AutoModel` available, use `BertModel` instead.

**Comment by pranjalsharma26** [comment]
Even after doing so as you told the same issue exist, from both AutoModel and BertModel.
![Screenshot (215)](https://user-images.githubusercontent.com/48346579/71766889-2a6b5d80-2f2b-11ea-9b9a-3f0a14d2289c.png)

**Comment by mandubian** [comment]
let's look at what I have on my console:
```python
>>> BertModel.from_pretrained("bert-base-uncased", force_download=True)
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313/313 [00:00<00:00, 29.5kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 440M/440M [00:23<00:00, 18.8MB/s]
BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm(torch.Size([768]), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1)
  )
  (encoder): BertEncoder(
...
```

So it finds the files and model from my network.
So that's why I wonder whether you haven't something in your network that prevents you from reaching S3.

**Comment by pranjalsharma26** [comment]
On my console I didn't knew how it is not working I tried the same as you told to do so. I think I should try some another way to sort this issue. On your note you are correct but in my machine it doesn't works. Thanks buddy!

**Comment by mandubian** [comment]
I saw that you were working on Windows, right? Are you sure you have no firewall/antivirus software blocking access or locking files or anything else? Just giving some ideas ;)
Anyway, you're welcome!
