### ISSUE TITLE
ALBERT pretrained models uses wrong type of GELU activation

### ISSUE THREAD

**Issue by Rexhaif** [huggingface/transformers#2395]
## 🐛 Bug

Model I am using (Bert, XLNet....): ALBERT

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [x] my own modified scripts: i'm fine-tuning albert for multilabel-classifcation problem and then converting model into tf-lite format

The tasks I am working on is:
* [x] my own task or dataset: multilable text classification on SemEval 2018 task 1:E-c

## To Reproduce

1. Open any link to pretrained configuration at [transformers/configuration_albert.py](https://github.com/huggingface/transformers/blob/master/src/transformers/configuration_albert.py). For example: [albert-base-v2-config.json](https://s3.amazonaws.com/models.huggingface.co/bert/albert-base-v2-config.json). But problem applies to all the pretrained configs.
2. Check the value of property "hidden_act" (it will be gelu)
3. Realize, that gelu stands for bert-like implementation(see code [here](https://github.com/huggingface/transformers/blob/1ae63e4e097fe26c900783dd5c1710cf562e222e/src/transformers/modeling_bert.py#L152)), while original [code](https://github.com/google-research/ALBERT/blob/e350db671ae96b8345cd2c0ee1306713642b9810/modeling.py#L296) uses OpenAI-GPT - like gelu (it is defined in transformers as "gelu_new")

## Expected behavior

All the configuration files should contain "gelu_new" under "hidden_act" key.

## Environment

* OS: doesn't matter
* Python version: 3.7
* PyTorch version: 1.3.0
* PyTorch Transformers version (or branch): master
* Using GPU: doesn't matter
* Distributed of parallel setup: doesn't matter
* Any other relevant information:

## Additional context

While it possibly doesn't significantly change the model performance, it makes conferting model into tf-lite format a lot more tricky, because BERT-like gelu implementation uses tf.math.erf function, which is not in a tflite-builtins set. So i have to use tflite-select ops, which leads to using more heavy tflite-interpreter on android side. Also, it makes impossible to check the converted model performance on python side because default tensorflow-lite python interpreter can't interpret select-ops models.

**Comment by julien-c** [comment]
If you just change your config.json's `hidden_act` value locally you should still be able to load the pretrained weights and be able to convert the model to TFLite, right?

**Comment by Rexhaif** [comment]
Yes. Another option (my current workaround) is to explicitly specify hidden_act when creating model instance (via .from_pretrained(...)) during fine-tuning stage.

**Comment by Rexhaif** [comment]
It looks like you have fixed all ALBERT config files. Thanks!)
