### ISSUE TITLE
unable to use distilbert multilingual model

### ISSUE THREAD

**Issue by nikhar2008** [huggingface/transformers#2397]
## ❓ Questions & Help
I'm trying to use the distilbert-base-multilingual-cased model but have been unable to do so.

I have checked and I am using transformers version 2.3.0. I have already tried these things:
1)     tokenizer = AutoTokenizer.from_pretrained("https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-multilingual-cased-config.json")
    model = AutoModel.from_pretrained("https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-multilingual-cased-pytorch_model.bin")

Gives following error message:
OSError: Model name 'https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-multilingual-cased-config.json' was not found in tokenizers model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-multilingual-cased-config.json' was a path or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.

2)     tokenizer = AutoTokenizer.from_pretrained("distilbert-base-multilingual-cased")
    model = AutoModel.from_pretrained("distilbert-base-multilingual-cased")

Gives following error message: OSError: Model name 'distilbert-base-multilingual-cased' was not found in tokenizers model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad). We assumed 'distilbert-base-multilingual-cased' was a path or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.

3) Same as (2) but with DistilBertTokenizer and DistilBertModel.

Can I please get some help in fixing this issue?

**Comment by NaxAlpha** [comment]
Hi
I have verified that it is working. Could you please share your environment details etc.

https://colab.research.google.com/drive/1Bo0luU5q7bztalw5-trWsvl7G0J6zE10

**Comment by LysandreJik** [comment]
It seems you're not actually running on transformers 2.3.0. Could you please tell me the output of this code in your environment?

```py
from transformers import AutoModel, AutoTokenizer, __version__

print(__version__)
model = AutoModel.from_pretrained("distilbert-base-multilingual-cased")
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-multilingual-cased")
```

Thank you.
