### ISSUE TITLE
How can I using deepspeed along with LION optimizer/.?

### ISSUE THREAD

**Issue by luohao123** [huggingface/transformers#23987]
How can I using deepspeed along with LION optimizer/.?

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for such questions.

**Comment by luohao123** [comment]
@sgugger I have post one: https://discuss.huggingface.co/t/how-to-using-lion-optimizer/42270 Hope you guys could give any help.
