### ISSUE TITLE
weird resize during the initialization in the PreTrainedModel

### ISSUE THREAD

**Issue by juliahane** [huggingface/transformers#2405]
Hi
I am using BertForMaskedLM in the run_lm_finetuning.py code. This module call the module of BertLMPredictionHead, in which there is a decoder layer which is of the size of hidden_size*vocab_size. I would like to change the dimension of this layer. when I change it, I realize that during the call to  elf.init_weights() inside the  BertForMaskedLM, the function resize the weights for the decoder layer. I cannot track where is this exactly happening, thanks for your advice on how I can resolve this issue.

**Comment by LysandreJik** [comment]
This layer is resized in `self.init_weights` because it is sharing weights with the embedding layer. They need to be the same size.
