### ISSUE TITLE
Convert PyTorch checkpoint for more recent models

### ISSUE THREAD

**Issue by d-ataman** [huggingface/transformers#24061]
### Feature request

Is it possible to add more examples for model conversion between PyTorch models e.g. convert_bart_original_pytorch_checkpoint_to_pytorch.py in more recent and popular architectures? (e.g. mt5)

### Motivation

It would really accelerate setting up new feature/model development using pretained models on the database.

### Your contribution

If anyone can give feedback I am happy to share the resulting conversion script.

**Comment by amyeroberts** [comment]
For each of the models added to the transformers repo, conversion scripts are created to port the weights from the original weights to the library format. You can find these under [models' respective folders](https://github.com/huggingface/transformers/tree/main/src/transformers/models) e.g. for [longformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/longformer/convert_longformer_original_pytorch_lightning_to_pytorch.py), [longt5](https://github.com/huggingface/transformers/blob/main/src/transformers/models/longt5/convert_longt5x_checkpoint_to_flax.py), or the [t5 script used for mt5](https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/convert_t5_original_tf_checkpoint_to_pytorch.py).
