### ISSUE TITLE
Add option for `trust_remote_code=True` on transformers-cli download 

### ISSUE THREAD

**Issue by radames** [huggingface/transformers#24063]
### Feature request

Currently is very convenient to download models using  `transformers-cli download`, however some models need an extra argument for `trust_remote_code=True`

for example 

`transformers-cli download "tiiuae/falcon-40b"`

### Motivation

Would it make sense to add

`transformers-cli download "tiiuae/falcon-40b" --trust_remote_code`

### Your contribution

PR

**Comment by amyeroberts** [comment]
Sounds like a good addition to me! 

cc @sgugger who's been doing a lot of the work enabling remote code integration.

**Comment by sgugger** [comment]
Yes, happy to review a PR!
