### ISSUE TITLE
Feature request: support more than device keyword arg when calling .to() on BatchEncoding

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#24068]
### Feature request

I see that the `.to()` [method](https://github.com/huggingface/transformers/blob/f1660d7e23d4432513fe060bde4f9b7b29f05204/src/transformers/tokenization_utils_base.py#L751) of `BatchEncoding` returned by tokenizers only supports the `device` keyword argument.

However, the `BatchFeature` returned by image processors/audio feature extractors supports [more keyword arguments](https://github.com/huggingface/transformers/blob/f1660d7e23d4432513fe060bde4f9b7b29f05204/src/transformers/feature_extraction_utils.py#L187), most importantly `dtype`.

### Motivation

This is handy as it allows to do:
```
from transformers import ViTImageProcessor
import torch
from PIL import Image
import requests

processor = ViTImageProcessor()

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

encoding = processor(image, return_tensors="pt").to(device="cuda", dtype=torch.float16)

for k,v in encoding.items():
    print(k,v.dtype)
```
which returns
```
pixel_values torch.float16
```

### Your contribution

I could submit a PR but if anyone has the bandwidth for this, would be great to add it :D

**Comment by amannagarkar** [comment]
Hey I am interested on working on this issue. It is my first one so I'll need some guidance. I'll try my best and ping you if i need help!

**Comment by amyeroberts** [comment]
@amannagarkar Great! :D Feel free to ask questions on the PR once it's opened!

**Comment by Rishab26** [comment]
I can help with this too @amyeroberts
Would that be okay? @amannagarkar

**Comment by amannagarkar** [comment]
@Rishab26 I am already working on the issue! I will let you know in a couple of days? I am testing the code for errors and will open a pr shortly!

**Comment by Rishab26** [comment]
@amannagarkar Sure, no worries. Happy to collaborate together too. I've taken a shot at it 👍

**Comment by amannagarkar** [comment]
@Rishab26 submitted my pr take a look

**Comment by Lorenzobattistela** [comment]
@NielsRogge I saw in the PR that you said "instead update multimodal processors in the library that return a BatchEncoding instead of a BatchFeature." What do you mean by update the multimodal processors? Also the problem addressed by this issue does not exist (i think, by the discussion in the PR) so maybe we could close it. If not, I'm willing to work on any remaining issue.

**Comment by NielsRogge** [comment]
@Lorenzobattistela you're right in that this issue can be closed, since BatchEncoding is only meant for tokenizers, which always return LongTensors, making the `dtype` irrelevant.
