### ISSUE TITLE
Typo in XLM moses pipeline.

### ISSUE THREAD

**Issue by alvations** [huggingface/transformers#2410]
The replacement on for the unicode punct replacement has a mistake at https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_xlm.py#L477

**Comment by LysandreJik** [comment]
Indeed, thanks @alvations !

**Comment by alvations** [comment]
BTW, https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_xlm.py#L621 could also be simplified to the normalizer object from https://github.com/alvations/sacremoses/blob/master/sacremoses/normalize.py#L129


```python
    def moses_punct_norm(self, text, lang):
        if lang not in self.cache_moses_punct_normalizer:
            punct_normalizer = sm.MosesPunctNormalizer(lang=lang, pre_replace_unicode_punct=True, post_remove_control_chars=True)
            self.cache_moses_punct_normalizer[lang] = punct_normalizer
        else:
            punct_normalizer = self.cache_moses_punct_normalizer[lang]
        return punct_normalizer.normalize(text)
```

Then the pipeline at https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_xlm.py#L635 would just be 


```python
    def moses_pipeline(self, text, lang):
        text = self.moses_punct_norm(text, lang)
        return text
```
