### ISSUE TITLE
Invalid hyperlink error 404 in Transformer Doc for RayTune

### ISSUE THREAD

**Issue by JoshuaEPSamuel** [huggingface/transformers#24135]
Greetings,

Small issue here: following the HuggingFace Transformer Docs on Hyperparameter Search using Trainer API, for raytune the hyperlink for 'object_parameter' is now invalid and should be updated.

The other backends (sigopt, optuna, wandb) have correctly working hyperlinks for the 'object_parameter'.

Link to doc page:
https://huggingface.co/docs/transformers/hpo_train#how-to-enable-hyperparameter-search-in-example

Link to git markdown file:
https://github.com/huggingface/transformers/blob/main/docs/source/en/hpo_train.mdx

**Comment by julien-c** [comment]
feel free to open a PR to fix if you can:)
