### ISSUE TITLE
How to use transformers-cli serve , how to set up on the server side?

### ISSUE THREAD

**Issue by zhoudoufu** [huggingface/transformers#2413]
## ❓ Questions & Help

Hi, I would like to make the transformers based models running as a server on a remote machine, as the way bert-as-server did.
I suppose I could call the transformers-cli serve command on the server side, but I haven't find much clue on how to make it running on the client part. 

BTW. I am trying to run the serve cmd with localhost like :
transformers-cli serve --task feature-extraction --model distilbert --config distilbert-base-uncased --tokenizer distilbert 
and failed for ValueError: Can't find a vocabulary file at path  [cached dir file].
and I tried with transformers/src/transformers/__main__.py with same parameters and got same error.
Would you please give me a snippet on how to make the transformers-cli serve work on both sides?

**Comment by mfuntowicz** [comment]
Hi @zhoudoufu ! You need to fully specify the model:

```bash
transformers-cli serve --task feature-extraction --model distilbert-base-uncased --config distilbert-base-uncased --tokenizer distilbert-base-uncased
```

Then you should be able to call:

```bash
curl -X POST "http://localhost:8888/forward" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"inputs\":\"My name is Morgan\"}"
```

Let us know :)

**Comment by zhoudoufu** [comment]
It works, thanks @mfuntowicz

**Comment by zhoudoufu** [comment]
Hi @mfuntowicz 
I tested tokenize/detokenize usage with:
 curl -X POST "http://localhost:8888/tokenize" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"input\":\"Thanks Morgan\"}"
And got a 500 error code with output like:
{"detail":{"model":"","error":"'NoneType' object has no attribute 'strip'"}}

and, is it possible to get last 4 layer's features in the serving way too?  thx a lot.
