### ISSUE TITLE
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`

### ISSUE THREAD

**Issue by cssndrx** [huggingface/transformers#24147]
### System Info

I'm running the example code from 
https://huggingface.co/docs/transformers/training

on a Colab
https://colab.research.google.com/drive/1W8yZhitt-pnJv5gLwWzoCTNWPEek3dy9?usp=sharing

and it's failing with 
[/usr/local/lib/python3.10/dist-packages/transformers/training_args.py](https://localhost:8080/#) in _setup_devices(self)
   1670         if not is_sagemaker_mp_enabled():
   1671             if not is_accelerate_available(min_version="0.20.1"):
-> 1672                 raise ImportError(
   1673                     "Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`"
   1674                 )

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`

However, it still gives the error even after I pip install the recommended libraries.

Also, pip freeze shows that accelerate is accelerate==0.20.3 which should satisfy the requirement of `accelerate>=0.20.1` - so I'm not sure why the Trainer is throwing the error.

Thanks for taking a look @sgugger 

### Who can help?

@sgugger 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://colab.research.google.com/drive/1W8yZhitt-pnJv5gLwWzoCTNWPEek3dy9?usp=sharing

### Expected behavior

To run training

**Comment by sgugger** [comment]
You need to restart your colab environment after updating the library.

**Comment by yesabhishek** [comment]
thanks @sgugger for the quick fix! I was having the same issue as mentioned by @cssndrx .

**Comment by cssndrx** [comment]
Thank you @sgugger, that was the issue!

**Comment by JasielCampos** [comment]
Thanks, I was having the same issue!

**Comment by taoli-ax** [comment]
restart virtalenv slove my same issue,thanks

**Comment by omarmaher0** [comment]
wow! Thanks alot @sgugger

**Comment by rokity** [comment]
Restarting the notebook and the kernel resolve it also for me

**Comment by rootUJ99** [comment]
Getting this error just by running the cells first time and restart also doesn't work

**Comment by ketangoyal1042** [comment]
Restart even doesn't work me either

**Comment by ahirtonlopes** [comment]
I was having the same issue, restarting also worked for me!

**Comment by rokity** [comment]
@NavneetSajwan  try to restart the notebook.

**Comment by clicly** [comment]
I am having the same issue in my colab environment, after updating the notebook worked for me!

**Comment by erinong** [comment]
Thank you!@sgugger. Same problem solved.

**Comment by parisa-ahmadi** [comment]
wow great restart also worked for me.. mannnnyyy thanks

**Comment by mohsin651** [comment]
"Is there an alternative method? Restarting and rerunning all the cells consumes a significant amount of time.

**Comment by joezhuang** [comment]
> Restart even doesn't work me either

Step1:
>>> !pip install transformers[torch] --- run installation
Step2:
>>> #!pip install transformers[torch] --- comment out the installaltion
Step3:
Restart Colab Session

**Comment by ai-general1** [comment]
thanks @sgugger 
It works for me
