### ISSUE TITLE
DetrAttention `is_decoder` is not defined

### ISSUE THREAD

**Issue by JayL0321** [huggingface/transformers#24161]
https://github.com/huggingface/transformers/blob/fe861e578f50dc9c06de33cd361d2f625017e624/src/transformers/models/detr/modeling_detr.py#LL502C9-L502C19

The `is_decoder` parameter is in the init function, but it is not reference in the body. While in `DetrDecoderLayer`, this parameter is initialized as `True`. Very confused, not sure whether there's something missing in `DetrAttention`.

**Comment by amyeroberts** [comment]
cc @NielsRogge

**Comment by NielsRogge** [comment]
Yes, seems like a left-over from copying from another model. Feel free to open a PR to remove the `is_decoder` parameter
