### ISSUE TITLE
In examples, complete steps not correct when load from checkpoint

### ISSUE THREAD

**Issue by Ethan-yt** [huggingface/transformers#24186]
### System Info

https://github.com/huggingface/transformers/blob/8f093fb799246f7dd9104ff44728da0c53a9f67a/examples/pytorch/language-modeling/run_clm_no_trainer.py#L575
Should be:
```python
completed_steps = resume_step // args.gradient_accumulation_steps
```

### Who can help?

@sgugger

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Enable grad acc.
1. Save the checkpoint.
1. Load from it.

### Expected behavior

The `completed_steps` should be divided by grad acc steps.

**Comment by sgugger** [comment]
Would you like to make a PR with a fix?

**Comment by Ethan-yt** [comment]
> Would you like to make a PR with a fix?
Done!
https://github.com/huggingface/transformers/pull/24197
