### ISSUE TITLE
[DistillBERT] tokenizer issue of multilingual-cased

### ISSUE THREAD

**Issue by DataLama** [huggingface/transformers#2423]
## 🐛 Bug

Model I am using (Bert, XLNet....):  DistilBERT

Language I am using the model on (English, Chinese....): Korean

The problem arise when using:
* [ ] the official example scripts: (give details)
* [x] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details)

## To Reproduce

When I tokenize the korean by `transformers.DistilBertTokenizer` with the **bert-base-multilingual-cased** vocab. Every token in korean mapped to [UNK].

```python
from transformers import DistilBertTokenizer

ko_text = "CNP차앤박화장품 역시 국내 대표 ‘피부과 출신’ 화장품 브랜드다. CNP차앤박화장품‘프로폴리스 앰플 오일 인 크림’은 브랜드 베스트셀러인 프로폴리스 에너지 앰플에 오일을 함유해 보습 기능을 강화한 제품이다."

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-multilingual-cased')
print(tokenizer.tokenize(ko_text))
```
Results
['[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '.', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '.']

## Expected behavior

However, when tokenizing the korean by  `transformers.BertTokenizer` with the **bert-base-multilingual-cased** vocab returns expected results.

```python
from transformers import BertTokenizer

ko_text = "CNP차앤박화장품 역시 국내 대표 ‘피부과 출신’ 화장품 브랜드다. CNP차앤박화장품‘프로폴리스 앰플 오일 인 크림’은 브랜드 베스트셀러인 프로폴리스 에너지 앰플에 오일을 함유해 보습 기능을 강화한 제품이다."

tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
print(tokenizer.tokenize(ko_text))
```
Results
['CN', '##P', '##차', '##앤', '##박', '##화', '##장', '##품', '역시', '국', '##내', '대', '##표', '[UNK]', '피', '##부', '##과', '출', '##신', '[UNK]', '화', '##장', '##품', '브', '##랜드', '##다', '.', 'CN', '##P', '##차', '##앤', '##박', '##화', '##장', '##품', '[UNK]', '프로', '##폴', '##리스', '[UNK]', '오', '##일', '인', '크', '##림', '[UNK]', '은', '브', '##랜드', '베', '##스트', '##셀', '##러', '##인', '프로', '##폴', '##리스', '에', '##너', '##지', '[UNK]', '오', '##일', '##을', '함', '##유', '##해', '보', '##습', '기', '##능을', '강', '##화', '##한', '제', '##품', '##이다', '.']

## Environment

* OS: Ubuntu 18.04.3 LTS
* Python version: 3.6.8
* PyTorch version: 1.3.0+cu100
* PyTorch Transformers version (or branch): 2.2.2
* Using GPU ? : Not in this issue.
* Distributed or parallel setup ? No
* Any other relevant information: I use the docker image `horovod/horovod:0.18.2-tf2.0.0-torch1.3.0-mxnet1.5.0-py3.6-gpu`

## Additional context
I tested `transformers.DistilBertTokenizer` with the **bert-base-multilingual-cased** vocabs on english text. It returns expected results.

So, It seems that subclassing DistilBertTokenizer from BertTokenizer is the problem.... How can I solve this issue?

**Comment by LysandreJik** [comment]
Hi, thanks for raising this issue! This is due to the lower casing parameter which is not correctly initialized for DistilBERT. I'm fixing it in #2469.
