### ISSUE TITLE
Make classifier backbone dynamic maskformer, mask2former

### ISSUE THREAD

**Issue by tanzzilaalam** [huggingface/transformers#24244]
### Feature request

Make classifier backbone dynamic maskformer, mask2former. Currently it only supports swin transformer. 

link example:  https://github.com/huggingface/transformers/blob/main/src/transformers/models/mask2former/modeling_mask2former.py#L1393

### Motivation

If this feature request successful, it will help to benchmark for new clasifier easily.

**Comment by tanzzilaalam** [comment]
There is still problem. 
The supported backbones variable hinders to allow any backbones other than swin.
Please check this line. I had to write child class and had to modify this line to solve this problem. 

https://github.com/huggingface/transformers/blob/main/src/transformers/models/mask2former/configuration_mask2former.py#L124

**Comment by tanzzilaalam** [comment]
Thank you for solving this issue. But there is still problem.
The supported backbones variable hinders to allow any backbones other than
swin.
Please check this line. I had to write child class and had to modify this
line to solve this problem.

https://github.com/huggingface/transformers/blob/main/src/transformers/models/mask2former/configuration_mask2former.py#L124

**Comment by sgugger** [comment]
cc @amyeroberts

**Comment by amyeroberts** [comment]
Hi @tanzzilaalam, you're completely right. I've opened a PR - #24532 -  which should resolve this and allow you to pass in any `backbone_config`.
