### ISSUE TITLE
Tokenize whole sentence vs. tokenize words in sentence then concat

### ISSUE THREAD

**Issue by bigkunzi** [huggingface/transformers#2425]
## ❓ Questions & Help

When using En-Fr XLMModel in transformers library,
I found that result from tokenizing a whole sentence is different from tokenizing words in the sentence and then concatenate.

My configuration is as below
**(XLMModel, XLMTokenizer, XLMConfig, 'xlm-mlm-enfr-1024')**

The result is as below
![image](https://user-images.githubusercontent.com/12389429/71879066-84a93000-3170-11ea-91fe-25227ebe478e.png)

The ultimate goal is to 'detokenize' tokenized sentence which is
['I', 'love', 'swim', '##ing'] -> ['I', 'love', 'swimming']
In order to do this, I have to know the raw token's index for each tokenized tokens.

It would be great if anyone can help with this problem.

**Comment by BramVanroy** [comment]
Seems like this is a duplicate of https://github.com/huggingface/transformers/issues/2140

**Comment by bigkunzi** [comment]
Thank you for mentioning the same issue!
