### ISSUE TITLE
Does Fine tuning of already fine tuned model forgets the previous features like weights and bias?

### ISSUE THREAD

**Issue by akesh1235** [huggingface/transformers#24258]
Is it possible for fine tuning the already fine tuned model without losing previous features??

Suppose i fine-tune a model on "squad" dataset then I want to Incremental fine-tune the same model on some other dataset having same/different data formate and hyperparameters, does this means now model is fine-tuned on 2 datasets??? or it forgets the "squad" dataset when I fine tune on the second dataset.

Please acknowledge me over this
@vanpelt 
@pvl 
@arfon

**Comment by amyeroberts** [comment]
Hi @akesh1235, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by akesh1235** [comment]
Thankyou sir, 
I have posted on forum [Link for My topic on forum ](https://discuss.huggingface.co/t/fine-tuning-the-existing-fine-tuned-model/43113?u=akesh1235)

**Comment by amyeroberts** [comment]
@akesh1235 Great, thank you. 

In future, please only @ relevant people in issues (transformers topics and the HF maintainers to ask are listed in our issues template). The people you tagged are incredibly busy people and if everyone did this it would be impossible for anyone to meaningfully address issues, PRs and notifications on github.
