### ISSUE TITLE
Is time to update the transformers dependence in README.

### ISSUE THREAD

**Issue by luoling1993** [huggingface/transformers#24263]
In README docs, it say `This repository is tested on Python 3.6+, Flax 0.3.2+, PyTorch 1.3.1+ and TensorFlow 2.3+.`

**Comment by sqali** [comment]
take

**Comment by amyeroberts** [comment]
@sqali - great! Happy to hear you want to make this contribution. 

The supported versions can be found in [setup.py](https://github.com/huggingface/transformers/blob/main/setup.py).

**Comment by amyeroberts** [comment]
@sqali Thanks for pulling this info. For the update, it's best to follow the current pattern in the docs: 

`This repository is tested on Python 3.7+, Flax 0.4.1+, PyTorch 1.9+ and TensorFlow 2.4+.`

Let's open a PR, and we can discuss any additional changes before merging there.

**Comment by sqali** [comment]
Hi @amyeroberts ,

I have raised the pull request and it has been approved by Sylvain Gugger. It has passed all the required checks and is ready to be merged. I would like to thank you for giving me the opportunity to raise the PR and make this contribution.

Thanks

**Comment by amyeroberts** [comment]
Thanks for fixing and congrats on getting your first contribution merged in!
