### ISSUE TITLE
It occurs error when python run_lm_finetuning.py 

### ISSUE THREAD

**Issue by ARDUJS** [huggingface/transformers#2429]
- Environment
> - python 3.6.9
> - torch 1.1.0
> - have installed transformers
- Command
> python run_lm_finetuning.py     --output_dir=output     --model_type=bert     --model_name_or_path=bert-base-uncased     --do_train     --train_data_file=$TRAIN_FILE     --do_eval     --eval_data_file=$TEST_FILE     --mlm
- Error
> Traceback (most recent call last):
  File "run_lm_finetuning.py", line 498, in <module>
    main()
  File "run_lm_finetuning.py", line 447, in main
    train_dataset = load_and_cache_examples(args, tokenizer, evaluate=False)
  File "run_lm_finetuning.py", line 96, in load_and_cache_examples
    dataset = TextDataset(tokenizer, file_path=args.eval_data_file if evaluate else args.train_data_file, block_size=args.block_size)
  File "run_lm_finetuning.py", line 78, in __init__
    self.examples.append(tokenizer.add_special_tokens_single_sequence(tokenized_text[:block_size]))
**AttributeError: 'BertTokenizer' object has no attribute 'add_special_tokens_single_sequence'**
- Help
> How to deal it?

**Comment by LysandreJik** [comment]
What is your version of transformers?
