### ISSUE TITLE
Device control characters lead to an error in average NER aggregation

### ISSUE THREAD

**Issue by edloginova** [huggingface/transformers#24314]
### System Info

Python 3.8.10, transformers versions tried: 4.30.1 and 4.30.2. Tried in a Docker container with Linux Ubuntu 20.04 and on Google Colab.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Load a pretrained language model as NER pipeline with average aggregation
2. Run it on a sequence `"\x11\x11"`

Colab: https://colab.research.google.com/drive/1Xm2kFAIsb1vt8R8JvdiLitDZ2m6WszcP?usp=sharing

The error happens on line 336 of `transformers\pipelines\token_classification.py`, in `aggregate_word()` function: `word = self.tokenizer.convert_tokens_to_string([entity["word"] for entity in entities])`. There, entities remains `None` while it should be `[]`; it seems to happen because in `aggregate()` function (same file), when `aggregation_strategy` is set to average, we call `aggregate_words()` and there `entities` is `[]`, so we end up with `word_group` as still `None`, and that gets passed to `aggregate_word`.

### Expected behavior

The aggregations runs without any errors and produces an empty list.

**Comment by Narsil** [comment]
Created a fix PR.
