### ISSUE TITLE
Colab Translation notebook link not found

### ISSUE THREAD

**Issue by SoyGema** [huggingface/transformers#24341]
### System Info

Hello There!
First and foremost, congrats for Transformers Translation [tutorial](https://huggingface.co/docs/transformers/tasks/translation). 👍
It serves as a Spark for building english-to-many translation languages models!
I´m following it along with TF mostly reproducing it in a jupyter Notebook with TF for mac with GPU enabled

At the end of the [Train](https://huggingface.co/docs/transformers/tasks/translation) section , it is showed

_For a more in-depth example of how to finetune a model for translation, take a look at the corresponding PyTorch notebook or [TensorFlow notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/translation-tf.ipynb)._

Inside the notebook, at cell [4] , there shows a message

_**You** can find a script version of this notebook to fine-tune your model in a distributed fashion using multiple GPUs or TPUs [here](https://github.com/huggingface/transformers/tree/master/examples/seq2seq)._

The link is broken .

## Potential fix.
Maybe it could point to Transformer [performance docs](https://huggingface.co/docs/transformers/performance) if you want to go for a more general overview or some specific part of [run_translation.py](https://github.com/huggingface/transformers/blob/main/examples/tensorflow/translation/run_translation.py) script facilitated by team member [here](https://github.com/huggingface/transformers/issues/24254#issuecomment-1594830054) during #24254 help? Please , don't hesitate to share the link as there could be a benefit in implementing it

Thanks so much for the time dedicated to this 
Keep up the amazing work in the Open!

### Who can help?

@Rocket

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Follow tutorial in docs . Go to Notebook at the end of Train Section 
2. Go to Tensorflow Notebook
3. Click link in cell [4] . It seems to go to /seq2seq examples

### Expected behavior

The link should point at a fine-tune script version of the notebook, or at least to docs

**Comment by amyeroberts** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
I opened a PR to the notebooks repo here to fix this: https://github.com/huggingface/notebooks/pull/398

Thanks for warning us about the issue - we appreciate the help to keep our docs up to date!
