### ISSUE TITLE
ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.

### ISSUE THREAD

**Issue by ErHimani** [huggingface/transformers#24365]
### System Info

I am trying to train the CLIP model with my custom dataset But I am facing the above issue
my current version of tensorflow ==2.12.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

![image](https://github.com/huggingface/transformers/assets/62006705/a8463187-0a43-4caa-9f0f-d90222434ff4)

### Expected behavior

Please provide me the guidance how I can use the code t train on custom dataset

**Comment by amyeroberts** [comment]
Hi @ErHimani, thanks for raising an issue. 

Could you follow the issue template and provide: 
* The running environment: run `transformers-cli env` in the terminal and copy-paste the output
* A minimal code snippet so that was can reproduce the error

Without these, we're unable to help.

**Comment by ErHimani** [comment]
hii @amyeroberts I am using the following command:
`python examples\tensorflow\contrastive-image-text\run_clip.py --output_dir  .\clip-roberta-finetuned --vision_model_name_or_path openai/clip-vit-base-patch32 --text_model_name_or_path roberta-base --train_file descriptions.json  --image_column image_path --caption_column text --remove_unused_columns=False --do_train  --per_device_train_batch_size="64" --per_device_eval_batch_size="64"  --learning_rate="5e-5" --warmup_steps="0" --weight_decay 0.1`

**Comment by amyeroberts** [comment]
@ErHimani Thanks for providing this. In order for us to be able to reproduce, we'll need `descriptions.json`, or an example sample from the dataset to be able to reproduce. We also require the running environment information, as noted above.

**Comment by ErHimani** [comment]
Link of the custom dataset
description.json:[https://drive.google.com/file/d/14FGJwXRsxns679-ILGlLcBRpqe8UUmGu/view?usp=sharing](url)
Images:[https://drive.google.com/drive/folders/1yr8zapcCPdxlN-5ZSczOIiIeIyS3K_Vt?usp=sharing](url)

**Comment by amyeroberts** [comment]
@ErHimani Apologies for the delay in getting back to this issue. The links to the datasets are no longer working. Is the issue still persisting with the latest transformers release? If so, would you be willing to re-share the example dataset?
