### ISSUE TITLE
For loop support in python interpreter of Transformer agent

### ISSUE THREAD

**Issue by dcy0577** [huggingface/transformers#24362]
### Feature request

Hello, I would like to add for loop support in https://github.com/huggingface/transformers/blame/c2393cad085e3875ee2206d917d46d15e50602a3/src/transformers/tools/python_interpreter.py
Any idea about how to implement this?

### Motivation

For loop is quite common in generated code. Usually it will not cause infinite loop.

### Your contribution

An additional 'elif' for 'ast.For' before the 'else' will be nice: https://github.com/huggingface/transformers/blame/c2393cad085e3875ee2206d917d46d15e50602a3/src/transformers/tools/python_interpreter.py#L132

**Comment by sgugger** [comment]
Would you like to open a PR for this?

**Comment by dcy0577** [comment]
I would like to, but I don't know how to implement it yet. Do you have any suggestions?

**Comment by sgugger** [comment]
Should be added with the PR mentioned above :-)
