### ISSUE TITLE
Incorrect information on BlipImageProcessor documentation

### ISSUE THREAD

**Issue by LukeBailey181** [huggingface/transformers#24370]
**Is your feature request related to a problem? Please describe.**
There is slightly incorrect information on the [BlipImageProcessor documentation](https://huggingface.co/docs/transformers/main/en/model_doc/blip#transformers.BlipImageProcessor). 

**Describe the solution you'd like**
The documentation currently says that the `image_mean` and `image_std` arguments default to `IMAGENET_STANDARD_MEAN` and `IMAGENET_STANDARD_STD` respectively. This seems to be incorrect looking at the source code however, in the init of `BlipImageProcessor` found [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/blip/image_processing_blip.py#L43) the values default to `OPENAI_CLIP_MEAN` and `OPENAI_CLIP_STD` respectively as defined [here](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/constants.py). Means are pretty similar but the standard deviations are quite different, so may be worth updating the documentation here :)

**Comment by amyeroberts** [comment]
Hi @LukeBailey181, thanks for pointing out! 

Would you like to open a PR to update the documentation? This way you would get the git contribution.

**Comment by LukeBailey181** [comment]
Wonderful yes I will create the PR!
