### ISSUE TITLE
How BERT 512 limit works?

### ISSUE THREAD

**Issue by Bisht9887** [huggingface/transformers#24383]
### System Info

I passed a long text of 3000 tokens and it did not give me any error. Does BERT not have 512 token limit? Why it is not giving any error? This is the code I used. You can pass any input with tokens more than 512

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

        from transformers import BertTokenizer
        tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
        
        # Long input text with more than 512 tokens
        text = "This is a very long text with more than 512 tokens..." 
        
        tokens = tokenizer.tokenize(text) 
        print(len(tokens))

### Expected behavior

error when processing more than 512

**Comment by sgugger** [comment]
Please use the forums for such questions. You did not pass your input the model, just the tokenizer.

**Comment by Bisht9887** [comment]
sure! I will take care of that. I am little new to this. Thanks for info
