### ISSUE TITLE
WavLM error when running forward

### ISSUE THREAD

**Issue by MorenoLaQuatra** [huggingface/transformers#24380]
### System Info

**Relevant Libraries**
transformers==4.26.1
torchaudio==2.0.2
torch==2.0.1

OS: Ubuntu 20.04 

### Who can help?

@sanchit-gandhi

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the following code:

```python
from transformers import AutoModel, AutoFeatureExtractor

model = AutoModel.from_pretrained("microsoft/wavlm-base-plus")
fe = AutoFeatureExtractor.from_pretrained("microsoft/wavlm-base-plus")

audio_path = "..."
audio, sr = torchaudio.load(audio_path)

input = fe(audio, return_tensor="pt")
model(input_values=input["input_values"])
```

---
When I try running the previous code, I got the following error:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PATH_TO_MY_ENV_SITE_PACKAGES/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "PATH_TO_MY_ENV_SITE_PACKAGES/transformers/models/wavlm/modeling_wavlm.py", line 1229, in forward
    extract_features = self.feature_extractor(input_values)
  File "PATH_TO_MY_ENV_SITE_PACKAGES/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "PATH_TO_MY_ENV_SITE_PACKAGES/transformers/models/wavlm/modeling_wavlm.py", line 346, in forward
    hidden_states = input_values[:, None]
TypeError: list indices must be integers or slices, not tuple
```

### Expected behavior

get the output with last_hidden_state and others. This is not happening with HuBERT or Wav2Vec2.

**Comment by sanchit-gandhi** [comment]
I think there's a small typo with your codesnippet:
```diff
- input = fe(audio, return_tensor="pt")
+ input = fe(audio, return_tensors="pt")
```

E.g. running the following works for me:
```python
from transformers import AutoModel, AutoFeatureExtractor
import torch
import numpy as np

model = AutoModel.from_pretrained("microsoft/wavlm-base-plus")
fe = AutoFeatureExtractor.from_pretrained("microsoft/wavlm-base-plus")

audio = np.random.randn(16000)  # random 1 second input audio

input = fe(audio, sampling_rate=16000, return_tensors="pt")

with torch.no_grad():
    model(input_values=input["input_values"])
```

**Comment by sanchit-gandhi** [comment]
Hey @MorenoLaQuatra - did the above suggestion fix your issue? Feel free to close this thread if so

**Comment by MorenoLaQuatra** [comment]
Well, actually my problem is more linked with the hidden_states when using output_hidden_states=True (the typo was my fault when reporting the snippet here on GitHub). However, I cannot reproduce it at the moment, so I will close for now.

Thanks @sanchit-gandhi !

**Comment by sanchit-gandhi** [comment]
Thanks for clarifying @MorenoLaQuatra! Feel free to open the issue again with a code repro if you find the model isn't working and we can take a deeper dive into it
