### ISSUE TITLE
Some links in NLLB page are broken.

### ISSUE THREAD

**Issue by ranggihwang** [huggingface/transformers#24382]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi, this is just a simple notification for crashed links.

https://huggingface.co/docs/transformers/v4.30.0/model_doc/nllb-moe
On this page, two links in the "documentation resources" are broken.

Thank you.

**Comment by sgugger** [comment]
cc @stevhliu

**Comment by ranggihwang** [comment]
Doc in version 4.30.0 still has problems, not only the doc section but other links :( @stevhliu

**Comment by sgugger** [comment]
The fix is on main, so it will only be reflected on the main version of the documentation. And if you have found other links to fix, please do tell us or open directly PRs to fix them :-)
