### ISSUE TITLE
is pytorch-pretrained-bert still being maintained in the future?

### ISSUE THREAD

**Issue by yuhujia** [huggingface/transformers#2441]
## 📚 Migration

Model I am using (Bert, XLNet....):

Language I am using the model on (English, Chinese....):

The problem arise when using:
* [ ] the official example scripts: (give details)
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details)

Details of the issue:

## Environment

* OS:
* Python version:
* PyTorch version:
* PyTorch Transformers version (or branch):
* Using GPU ?
* Distributed or parallel setup ?
* Any other relevant information:

## Checklist

- [ ] I have read the migration guide in the readme.
- [ ] I checked if a related official extension example runs on my machine.

**Comment by LysandreJik** [comment]
Hi, `pytorch-pretrained-BERT` is the name of this library as it was a year ago. It has since evolved into `pytorch-transformers` and now `transformers`. It is the same library.

**Comment by yuhujia** [comment]
Hi thank you for your reply. But my question really is that I'm now using apis from pytorch-pretrained-BERT directly and will these library be maintained under new release? 

The reason is that I found some discrepancies between apis from pytorch-pertrained-BERT library and transformers library and the old one (from pytorch-pretrained-BERT) gave better results so I'm sticking with that library.

**Comment by LysandreJik** [comment]
No updates will be done to the `pytorch-pretrained-BERT`, no bug fixes either. It is deprecated. It will remain on pip however.

Would you mind sharing where the `pytorch-pretrained-BERT` package gave better results so that we may investigate this? Thank you.

**Comment by yuhujia** [comment]
yes i'm encountering performance drop with sequence classification tasks, same as issues described in this thread: https://github.com/huggingface/transformers/issues/938.

**Comment by BramVanroy** [comment]
@LysandreJik There seem to be quite a few posts that highlight this difference in performance. It is quite alarming but I'm not sure if it is worth investigating because it might be impossible or improbable to solve.

https://github.com/huggingface/transformers/issues/938
https://github.com/huggingface/transformers/issues/931
https://github.com/UKPLab/sentence-transformers/issues/50
https://github.com/huggingface/transformers/issues/2441
