### ISSUE TITLE
porting XLM-Roberta to tensorflow 2.0

### ISSUE THREAD

**Issue by andompesta** [huggingface/transformers#2443]
## ❓ Questions & Help

Yesterday I have ported XLM-Roberta from pytorch to tensorflow mainly following the instruction provided in [huggingface/from-tensorflow-to-pytorch](https://medium.com/huggingface/from-tensorflow-to-pytorch-265f40ef2a28).
The final error is computed using the DUMMY_INPUT as input values for the large MaskedLM model and is evaluated on the final prediction_score output.  
I compute the error as:
```python
    max_absolute_diff = np.amax(np.abs(tf_model_out.numpy() - pt_model_out.detach().numpy()))
```
and the final output is 0.00027179718; which is lower than the suggested 1e^-3 bound.

According to your indication the error seems to be acceptable, given that XLM-Roberta is a huge model. However, I have experienced some huge output difference when I do not specify the position_ids. That is, the position_ids computed by the TFRobertaEmbeddings seems to be correct since they correctly take in consideration the presence of some pad tokens using the ``create_position_ids_from_input_ids`` function. Instead the PyTorch RobertaEmbeddings doesn't.

Moreover, I'm also wandering if it is possible to merge the interface of the TF models with the PyTorch models. Not sure if it is worth it, but by using the __call__ and call function provided by TF2.0 it is possible to obtain an equivalent interface between the 2 frameworks.
For example:
```python
class TFXLMRobertaForMaskedLM(TFXLMRobertaPreTrainedModel):
    def __call__(self, input_ids=None, attention_mask=None, token_type_ids=None, position_ids=None, head_mask=None, inputs_embeds=None, **kwargs):
        inputs = (input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds)
        return super(TFXLMRobertaForMaskedLM, self).__call__(inputs, **kwargs)

    def call(self, inputs, **kwargs):
        outputs = self.xlm_roberta(*inputs, **kwargs)

        sequence_output = outputs[0]
        prediction_scores = self.lm_head(sequence_output)
        outputs = (prediction_scores,) + outputs[2:]  
        return outputs  # prediction_scores, (hidden_states), (attentions)
```
should be equivalent to the PyTorch implementation

**Comment by julien-c** [comment]
Hi @andompesta hard to say without looking at the code – did you check out this related PR by @jplu : #2443
