### ISSUE TITLE
Wrong special tokens using XLM-RoBERTa's tokenizer for question answering

### ISSUE THREAD

**Issue by severinsimmler** [huggingface/transformers#24442]
### System Info

- `transformers` version: 4.30.2
- Platform: Linux-6.2.0-20-generic-x86_64-with-glibc2.37
- Python version: 3.11.3
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.0+cu117 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Tokenizing a question and its context with XLM-RoBERTa's tokenizer:

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

question = "This is a question?"
context = "This is the context."

inputs = tokenizer(question, context)

tokenizer.decode(inputs["input_ids"])
```

returns something like this:

```
<s> This is a question?</s></s> This is the context.</s>
```

i.e. with _two_ SEP tokens between question and context. Is this expected behavior? Shouldn't it be separated by only one `</sep>` or even `</sep><sep>`?

### Expected behavior

I'd expect the tokenizer to return:

```
<s> This is a question?</s><s> This is the context.</s>
```

**Comment by ArthurZucker** [comment]
Hey, I am not sure where your expectations come from, but in the task of `sequence_classification`, you are not simply concatenating two sentences. If you have a look [here](https://github.com/facebookresearch/XLM/blob/cd281d32612d145c6742b4d3f048f80df8669c30/generate-embeddings.ipynb#L130), an original colab formats the sentences the same way.

**Comment by NielsRogge** [comment]
No that's indeed expected behaviour, RoBERTa models use 2 special tokens in between context and question, unlike BERT.

See here: https://github.com/huggingface/transformers/blob/8e164c5400b7b413c7b8fb32e35132001effc970/src/transformers/models/roberta/tokenization_roberta.py#L346

**Comment by severinsimmler** [comment]
Got it, thanks a lot for clarifying :) 🙏
