### ISSUE TITLE
force_download for pipelines

### ISSUE THREAD

**Issue by morrisalp** [huggingface/transformers#24464]
### Feature request

Add `force_download=True/False` argument to the pipeline API to allow for re-downloading a model and ignoring local cache.

### Motivation

[PreTrainedModel](https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel) has the very useful argument `force_download` argument for ignoring local cache and downloading a model.
However, this does not work with the pipeline API:

```
from transformers import pipeline
pipe = pipeline("text2text-generation", model='t5-small', force_download=True)
pipe('test')
```
yields error: `ValueError: The following `model_kwargs` are not used by the model: ['force_download'] (note: typos in the generate arguments will also show up in this list)`

This is an issue since I am working with a pipeline using a model that is updating and would like to easily re-download it as needed.

### Your contribution

could add this to docs if implemented

**Comment by sgugger** [comment]
cc @Narsil for information. You can already pass this in the `model_kwargs` @morrisalp , I don't think it's worth surfacing it more than this.
