### ISSUE TITLE
cannot import name 'OwlViTImageProcessor' from 'transformers'

### ISSUE THREAD

**Issue by mazhai** [huggingface/transformers#24478]
### System Info

transformer version:4.29.2
platform: macOS Ventura
cpu: apple M2 Max
python versin: 3.10

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
import requests
from PIL import Image
import torch

from transformers import OwlViTProcessor, OwlViTForObjectDetection, OwlViTImageProcessor

processor = OwlViTProcessor.from_pretrained("google/owlvit-base-patch32")
model = OwlViTForObjectDetection.from_pretrained("google/owlvit-base-patch32")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
texts = [["a photo of a cat", "a photo of a dog"]]
inputs = processor(text=texts, images=image, return_tensors="pt")
outputs = model(**inputs)
```

### Expected behavior

exception: 
```
ImportError: cannot import name 'OwlViTImageProcessor' from 'transformers' (/Users/tt/opt/anaconda3/envs/test_transfromer/lib/python3.10/site-packages/transformers/__init__.py)
```

**Comment by kirstin-sandbox** [comment]
When I install pytorch or tensorflow using micromamba, each insists on downgrading transformers back to 4.17.  However, this version throws an error. However, you need pytorch or tensorflow installed to run the code.

**Comment by amyeroberts** [comment]
Hi @kirstin-sandbox, if the compatibility issue is on an old version of transformers, there isn't much we can do unfortunately, we can only iterate an build on the latest. If you need a newer version, I'd open an issue in the micromamba repo. 

> However, you need pytorch or tensorflow installed to run the code.

Which code? 

Installing pytorch or tensorflow should be compatible with running transformers. It also isn't necessary for importing the owl vit processor.
