### ISSUE TITLE
Access to Transformers examples link broken . Impact on navigation as well

### ISSUE THREAD

**Issue by SoyGema** [huggingface/transformers#24497]
### Context
Hello there! 👋
 I´m following [Translation](https://huggingface.co/docs/transformers/tasks/translation) Transformers tutorial . 
Thanks for making it possible! 
Currently running the script [run_translation.py](https://github.com/huggingface/transformers/blob/main/examples/tensorflow/translation/run_translation.py) and before changing transformers to version `4.31.0.dev` the following message appears          

https://github.com/huggingface/transformers/blob/5757923888246ea16b324f53c60ea444574005ed/src/transformers/utils/__init__.py#L218

When I follow the link , the following message appears. And when I click the _here_ link

<img width="1048" alt="Captura de pantalla 2023-06-26 a las 17 47 23" src="https://github.com/huggingface/transformers/assets/24204714/93afc7f8-ea28-4d19-b596-99120190fd21">

It redirects me to https://huggingface.co/docs/transformers/main/en/examples with an 404 error. 

### Potential Fix

Would love to give a helping hand here  🙏  like in #24336 and give back to the help I´ve gotten from #24254 but I am a little bit confused with respect to this. The last version in google-indexed examples that seem to work is [this](https://huggingface.co/docs/transformers/v4.15.0/examples) ,  related to `v4.15.0` and not `v4.30` nor `v4.29.2` .

Can you please confirm that you would validate this link
(https://huggingface.co/docs/transformers/v4.15.0/examples) for utils __init__.py script? If not, 
would you provide a useful link or point me in the right direction?

Please let me know if I'm also in the right place, as this could maybe impact website?
Thanks for the time dedicated to this.

### Who can help?

@sgugger @stevhliu

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Go to link described in utils https://huggingface.co/docs/transformers/examples
2. Follow link provided [
](https://huggingface.co/docs/transformers/main/en/examples)  and find error 404

### Expected behavior

Last link to examples, with the stable version. Unclear to me at this point if it is `4.29` or `4.30` or where they are.

**Comment by sgugger** [comment]
The link is wrong, it should be https://huggingface.co/docs/transformers/run_scripts

**Comment by SoyGema** [comment]
Sure, thanks!

**Comment by julien-c** [comment]
BTW @sgugger @LysandreJik you can specify doc redirects using a `redirects.yml` like in datasets and other libraries: https://github.com/huggingface/datasets/blob/main/docs/source/_redirects.yml

Always good to avoid broken links when we can 

cc @mishig25 too
