### ISSUE TITLE
DIT Text Detection model

### ISSUE THREAD

**Issue by arvisioncode** [huggingface/transformers#24495]
### Feature request

Add the text detection models of the dit that are in https://github.com/microsoft/unilm/tree/master/dit/text_detection to the hugging face, to be able to execute them easily with the transformers library like other models as https://huggingface.co/microsoft/dit-base

### Motivation

These models have very good performances and are very interesting to be able to include in hf both to make simple inferences and to transform them to other formats such as ONNX

**Comment by NielsRogge** [comment]
I know and I desperately want that model to be available... :D however for that, Mask R-CNN first needs to be integrated. I have a PR on that #22973, I need to finish that one up, then we can add it

**Comment by yellowjs0304** [comment]
@NielsRogge Hi, Do you have any plan for this? I want to export the DiT detection (Layout Analysis) model to ONNX.
Please let me know If there's a new comment about this.

**Comment by rm-asif-amin** [comment]
Hello @arvisioncode ,
Have you managed to tackle this? I'm willing to fine-tune the base model for this task on CORD or FUNSD but not sure if masked image modeling is the right paradigm for this. Eventually I need to train the model on an Indic language. I've done the full flow for DONUT but DiT seems to be lighter. Will appreciate any resource you might point me towards.

Thanks
