### ISSUE TITLE
Installation from source

### ISSUE THREAD

**Issue by Lawrence0319** [huggingface/transformers#24500]
### System Info

I tried to install the transformers library from source by following the link https://huggingface.co/docs/transformers/installation#install-from-source.

When testing whether the library is correctly installed, I followed the recommendation.
from transformers import pipeline
print(pipeline('sentiment-analysis')('I love you'))

And then, I got the following error:
ImportError: cannot import name 'is_torch_greater_or_equal_than_1_12' from 'transformers.pytorch_utils' (/usr/local/lib/python3.10/dist-packages/transformers/pytorch_utils.py)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1086                 f" traceback):\n{e}"
   1087             ) from e
-> 1088 
   1089     def __reduce__(self):
   1090         return (self.__class__, (self._name, self.__file__, self._import_structure))

RuntimeError: Failed to import transformers.models.tapas.modeling_tapas because of the following error (look up to see its traceback):
cannot import name 'is_torch_greater_or_equal_than_1_12' from 'transformers.pytorch_utils' (/usr/local/lib/python3.10/dist-packages/transformers/pytorch_utils.py)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

pip install git+https://github.com/huggingface/transformers
from transformers import pipeline
# print(pipeline('sentiment-analysis')('I love you'))
pipe = pipeline("sentiment-analysis")
pipe("I love you")

### Expected behavior

Would like a guidance to fix the bug

**Comment by sgugger** [comment]
You might have a mix of different installations in your environment. I would try again in a fresh Python environment.

**Comment by Lawrence0319** [comment]
I got another problem when running the run_fusion_glue.py from https://docs.adapterhub.ml/training.html#train-adapterfusion in Google Colab. I got the following error:
Traceback (most recent call last):
  File "/content/drive/MyDrive/run_fusion_glue.py", line 29, in <module>
    from transformers import (
ImportError: cannot import name 'AdapterArguments' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

**Comment by sgugger** [comment]
That's a problem in your `run_fusion_glue.py` script. This class does not exist in `transformers`.

**Comment by Lawrence0319** [comment]
I just copied from this website: https://github.com/adapter-hub/adapter-transformers/blob/master/examples/pytorch/adapterfusion/run_fusion_glue.py
So the problem is in that website? Does this class exist in transformers.adapters?

**Comment by sgugger** [comment]
You should report the issue on that repo yes :-)
