### ISSUE TITLE
Image-Classification Dataloader Missing Image Key

### ISSUE THREAD

**Issue by umarkhalidAI** [huggingface/transformers#24506]
### System Info

- `transformers` version: 4.31.0.dev0
- Platform: Linux-5.15.0-1029-azure-x86_64-with-glibc2.31
- Python version: 3.10.10
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
-

### Who can help?

@amyeroberts 
I tried to run the official example of image classification as:  python run_image_classification.py --output_dir output --dataset_name cifar10 --do_train --overwrite_output_dir
![image](https://github.com/huggingface/transformers/assets/46391971/ab2e7a19-b024-4dc7-91c2-a79833492037)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I just try to run the official image- classification examples. 

### Expected behavior

I was expecting the code to find the image key.

**Comment by ydshieh** [comment]
This dataset seems to have `img` as key in the dataset.

**Comment by ydshieh** [comment]
If you just want to try the script, the official example in the README is

```python
python run_image_classification.py \
    --dataset_name beans \
    --output_dir ./beans_outputs/ \
    --remove_unused_columns False \
    --do_train \
    --do_eval \
    --push_to_hub \
    --push_to_hub_model_id vit-base-beans \
    --learning_rate 2e-5 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --logging_strategy steps \
    --logging_steps 10 \
    --evaluation_strategy epoch \
    --save_strategy epoch \
    --load_best_model_at_end True \
    --save_total_limit 3 \
    --seed 1337
```

**Comment by ydshieh** [comment]
What I am saying is the original dataset has the `img` key, but the script expects `image` key. That is why there is an error.

**Comment by ydshieh** [comment]
If you really want to try `cifar10`, the quick way is to replace `"image"` to `"img"`.
