### ISSUE TITLE
RuntimeError: Cross Attention in GPTBigCodeModel

### ISSUE THREAD

**Issue by dawnik17** [huggingface/transformers#24516]
### System Info

Code: https://github.com/huggingface/transformers/blob/v4.30.0/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py

In the case of cross attention, if `self.c_attn` is initialised to give output of dimension `2 * self.embed_dim` **(Line 112 & 227)**

The `key_value` split in **line 246**,

`key, value = key_value.split((self.head_dim, self.head_dim), dim=-1)`

* would raise an exception _(when self.embeded_dim != self.head_dim)_

`RuntimeError: split_with_sizes expects split_sizes to sum exactly to 2*self.embeded_dim`

_PS - I could be mistaken, but it would be worth having a look (and correct me if I am wrong!)._

### Who can help?

 @ArthurZucker @younesbelkada @sgugger 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
inp = torch.rand((2, 4, 16))
g = GPTBigCodeAttention(config, is_cross_attention=True)
g(inp, encoder_hidden_states=inp)
```

`RuntimeError: split_with_sizes expects split_sizes to sum exactly to 32 (input tensor's size at dimension -1), but got split_sizes=[4, 4]`

### Expected behavior

The forward method should return the attention output of the shape [2, 4, 16].

**Comment by ArthurZucker** [comment]
Hey! Would you mind sharing a full reproduced? (ex the config you are using)? 
This might just be a raise Value error missing and a check on the shapes!

**Comment by dawnik17** [comment]
Sure @ArthurZucker 

Here is the config I'm using:

```
{"multi_query": True, 
"hidden_size": 16, 
"num_attention_heads": 2, 
"attention_softmax_in_fp32": True, 
"scale_attn_weights": True, 
"scale_attention_softmax_in_fp32": True, 
"attention_softmax_in_fp32": True, 
"attn_pdrop": 0.1, 
"resid_pdrop": 0.1}
```

Did you find my above reasoning correct though?
Thanks in advance :)

**Comment by dawnik17** [comment]
Bump :) 
@ArthurZucker

**Comment by ArthurZucker** [comment]
Okay! Thanks for bumping. 
Few things here: 
- `GPTBigCodeAttention` is not in the `__init__` so not on the surface of transformers: we don't really support using it outside in such a way. 
- `key, value = key_value.split((self.head_dim, self.head_dim), dim=-1)` should indeed be modified to `key, value = key_value.split((self.embed_dim, self.head_dim), dim=-1)`. As it is done for the `multi_query` branch. 

Do you want to open a PR and push the fix? 😉
