### ISSUE TITLE
Installation of Transformers without Sacremoses

### ISSUE THREAD

**Issue by zanderkent** [huggingface/transformers#2453]
## ❓ Questions & Help

Hi HuggingFace Team!

I was checking the dependencies of this library, and I found that sacremoses does not have an accepted licence type for my system. The setup.py file says that it's needed for XLM. If I don't plan on using XLM would I be able to modify the setup.py and remove the sacremoses requirement?

Thanks!
Zander

**Comment by zanderkent** [comment]
I commented sacramoses it out in the setup.py and installed it, everything worked as designed! As long as I don't use XLM

**Comment by mfeblowitz** [comment]
Having optional GPL code in a widely used package is an issue.  If fixing it is as simple as commenting it out in the setup, couldn't there be a way to make that available through some variant, so as not to taint other open source packages?

**Comment by julien-c** [comment]
`sacremoses` seems to have been licensed under MIT since https://github.com/alvations/sacremoses/pull/92 though?
