### ISSUE TITLE
Document QA Pipeline Suddenly Down?

### ISSUE THREAD

**Issue by FFFiend** [huggingface/transformers#24531]
### System Info

Transformers 4.29.2, MacOS, Python 3.9.6 64-bit,
I just have this piece of code:
```
    query_pipeline = pipeline(
        "document-question-answering", 
        model="impira/layoutlm-document-qa"
    )
```
and on this Python version it gives me: 
```
RuntimeError: Failed to import transformers.models.layoutlm.modeling_tf_layoutlm because of the 
following error (look up to see its traceback):
No module named 'keras.engine'
```
when it was working perfectly yesterday.

On Version: 4.30.2, MacOS, Python 3.10.12 64-bit, I get a different error somehow
```
  File "/opt/homebrew/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 988, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/transformers/pipelines/document_question_answering.py", line 145, in __init__
    self.check_model_type(MODEL_FOR_DOCUMENT_QUESTION_ANSWERING_MAPPING)
NameError: name 'MODEL_FOR_DOCUMENT_QUESTION_ANSWERING_MAPPING' is not defined
```

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps to reproduce:
Paste the code snippet and run the Python script.

### Expected behavior

I expect the pipeline to work properly as intended.

**Comment by sgugger** [comment]
Please follow the issue template and paste the result of `transformers-cli env`. It looks like you don't have PyTorch installed in your environment but it's hard to be sure without that. The document QA pipeline requires torch, it doesn't have an implementation in TensorFlow.

**Comment by FFFiend** [comment]
Resolved!! Thank you 😄
