### ISSUE TITLE
[BUG] Protobuf not being correctly installed

### ISSUE THREAD

**Issue by yinweisu** [huggingface/transformers#24533]
### System Info

`transformers==4.30.2`
Protobuf not being installed along with transformers even when it's specified in `setup.py`.
This can be an issue if the environment already installs latest version of protobuf, which is not compatible with tranformers

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

pip install transformers -U
pip freeze | grep protobuf

### Expected behavior

protobuf with correct pinned version should be installed

**Comment by sgugger** [comment]
Transformers is only compatible with protobuf<4.0 because packages we depend on (sentencepiece if I recall correctly) do not support protobuf 4 yet. There is little we can do on our side until they support it.

cc @ydshieh in case I said something wrong.

**Comment by ydshieh** [comment]
Hi @yinweisu 

You can uninstall `protobuf` and reinstall it to get `3.20.3`.

Regarding protobuf 4, unfortunately, we get errors (see below) for sentencepiece based tokenizers. I am also told that `google/sentencepiece` doesn't support protobuf 4 yet, but from its GitHub page, I can't see this information. I plan to open an issue to ask questions there.


```bash
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by ydshieh** [comment]
@yinweisu 

Maybe you want to give [this issue](https://github.com/google/sentencepiece/issues/889) a 👍 🤗 😆

**Comment by yinweisu** [comment]
Thanks! I know you can reinstall it. The issue is that we are an open source project, which depends on transformers and other libraries. Other libraries will install newer version of protobuf, which doesn't work with transformers. This means users consume our package will run into protobuf errors. Ideally, transformers should correctly pin protobuf and install the correct version while doing `pip install`. The fact is that, transformers does pin it in the setup.py, though it's not taking effect

**Comment by yinweisu** [comment]
> Transformers is only compatible with protobuf<4.0 because packages we depend on (sentencepiece if I recall correctly) do not support protobuf 4 yet. There is little we can do on our side until they support it.
> 
> cc @ydshieh in case I said something wrong.

@sgugger I understand it doesn't work with protobuf>4.0. But transformers should correctly install protobuf < 4.0 as its dependency, which is not what's happening right now

**Comment by ydshieh** [comment]
@yinweisu 

I probably need to check what happens if a higher version is already installed when a user installs `transformers`.

**Comment by yinweisu** [comment]
It will just use the higher version. We've got this problem in our own package installation.

You should be easily reproduce it via
```bash
pip install -U protobuf
pip install transformers
pip freeze | grep protobuf
```

**Comment by ydshieh** [comment]
@yinweisu After looking `setup.py`, at the end in that file, the `install_requires` only contains a few libraries:

https://github.com/huggingface/transformers/blob/66954ea25e342fd451c26ec1c295da0b8692086b/setup.py#L415-L426

and `protobuf` is not in this list. It's why `protobuf` is not checked and updated in the case you mentioned.

From README:

> Then, you will need to install at least one of Flax, PyTorch or TensorFlow.

I believe `install_requires` is set to be minimal as it is in current version. But @sgugger knows better than me regarding this and may have some comments.

**Comment by sgugger** [comment]
This list only contains soft dependencies. This one is used when you do `pip install transformers[sentencepiece]` for instance.

**Comment by yinweisu** [comment]
So I only install transformers, but I can still run into this problem if protobuf is either already presented in my env or being installed along with other packages. If transformers requires a specific version of protobuf to function, it should pin that version and install it.

**Comment by ydshieh** [comment]
As mentioned in 

> You should install 🤗 Transformers in a (new) virtual environment.

And you can simply install as `pip install transformers[dev]` or something smaller `pip install transformers["dev-torch"]`.

**Comment by ydshieh** [comment]
@yinweisu 

FYI: after #24599, we no longer pin `protobuf` in `transformers`.
