### ISSUE TITLE
Issue while training Donut model for parsing with custom decoder and tokenizer

### ISSUE THREAD

**Issue by akashlp27** [huggingface/transformers#24544]
Hey all, I was trying to train donut model for parsing, which contains Arabic(only) information, in order to achieve this i had collected `Arabic corpus` from various sources and then trained,
1. `Mbart Tokenizer` for arabic corpus.
2. `Mbart decoder` with the same dataset.

Initially the model was training well meaning the loss was decreasing gradually but, during Validation, all my dataset tokens are predicting as `<UNK>` tokens. Because of this the `Normed ED` value is above `0.9` but still the loss is decreasing. 

Is there anything I am missing out , any inputs will help a lot. @gwkrsrch , @Vadkoz ,@NielsRogge
Thanks regards.

**Comment by ydshieh** [comment]
Hi @akashlp27 

As per our [issues guidelines](https://github.com/huggingface/transformers/blob/main/ISSUES.md), we reserve GitHub issues for bugs in the repository and/or feature requests. For any other matters, we'd like to invite you to use our [forum](https://discuss.huggingface.co/) 🤗

However, you might want to take a look
https://github.com/huggingface/transformers/issues/18190#issuecomment-1273482690
https://github.com/huggingface/transformers/issues/18190#issuecomment-1216584872
(Not sure though)
