### ISSUE TITLE
VS Code Pylance does not highlight transformers imports

### ISSUE THREAD

**Issue by mmlynarik** [huggingface/transformers#24548]
### System Info

When Pylance is used as language server for VSCode, it does not highlight `transformers` imports even though library is correctly installed. Classes imports and library name itself are gray instead of yellow, see the enclosed figure. I'm not sure if it relates to Pylance itself, but it would be nice if this behavior was fixed.

![image](https://github.com/huggingface/transformers/assets/44208384/b39dbf5d-cf3a-4be3-bbf5-b32ddd7817dc)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Create and activate new virtual environment
2. Install transformers 4.30.2
3. Write into a new python module: `from transformers import BatchEncoding`

### Expected behavior

The import statement should be highlighted the same way as other libraries imports.

**Comment by sgugger** [comment]
Sounds like an issue for VsCode or Pylance no?

**Comment by td-anne** [comment]
This is probably the result of lazy module loading, or even the simple absence of a `__all__` (as far as I can see). This may not be something fixable within `transformers` but it does result from a design choice. https://github.com/huggingface/transformers/blob/main/src/transformers/__init__.py#L7139

**Comment by sgugger** [comment]
The `__all__` is defined in the `_LazyModule` as you can see [here](https://github.com/huggingface/transformers/blob/6c57ce15587810968d64fb4b5700b63726397194/src/transformers/utils/import_utils.py#L1048).

**Comment by mmlynarik** [comment]
> Sounds like an issue for VsCode or Pylance no?

Might be, but it’s surprising that tokenizers and datasets which are two most closely related libriaries from the HF ecosystem are functioning correctly.

**Comment by montyevans** [comment]
Pretty sure this is fixed now, per the above issue on the Pylance repo.

Fix repros on my side; if anyone else would care to confirm, we can probably close this issue.
