### ISSUE TITLE
eval_loss returning nan

### ISSUE THREAD

**Issue by NHendrickson9616** [huggingface/transformers#24562]
### System Info

- `transformers` version: 4.28.0
- Platform: Linux-3.10.0-1160.24.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.12
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.1+cu118 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Still new to this, don't know

### Who can help?

@sgugger

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Here is the set up before I run the code:
```
trained_path = '/data/user/home/nchendri/biobertuab/modelInfo'
from transformers import Trainer, TrainingArguments
training_args = TrainingArguments(
    output_dir=trained_path,
    overwrite_output_dir=True,
    num_train_epochs=32,
    per_device_train_batch_size=16,
    save_steps=10_000,
    save_total_limit=2,
    prediction_loss_only=True,
    optim="adamw_torch",
)
 
trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=dsTok['train'],
    eval_dataset=dsTok['valid'],
)

eval = trainer.evaluate()
```

### Expected behavior

It was supposed to output an eval_loss, very new at this, could have missed something in above code setting stuff up.

**Comment by glaand** [comment]
Having the same problems.

Only getting the following out
`({'eval_runtime': 5.4991, 'eval_samples_per_second': 65.829, 'eval_steps_per_second': 1.091, 'epoch': 2.0},)`

**Comment by ydshieh** [comment]
@glaand 

Could you provide a code snippet that could run directly? Thanks in advance!
