### ISSUE TITLE
Fine-tune T5 on SQuAD

### ISSUE THREAD

**Issue by h1326889** [huggingface/transformers#24613]
### System Info

I was trying to use the official command to evaluate T5 on SQuAD data, but where can I find the prediction file that contains the actual answer T5 generated?
  python run_seq2seq_qa.py \
  --model_name_or_path t5-small \
  --dataset_name squad \
  --context_column context \
  --question_column question \
  --answer_column answers \
  --do_eval \
  --max_seq_length 384 \
  --doc_stride 128 \
  --predict_with_generate \
  --output_dir /tmp/debug_seq2seq_squad/

### Who can help?

@sgugger

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

NA

### Expected behavior

find the prediction file

**Comment by ydshieh** [comment]
I didn't verify manually, but I think you have to modify 

https://github.com/huggingface/transformers/blob/fc7ce2ebc52eccd8158a7feeeee11eb44f964937/examples/pytorch/question-answering/run_seq2seq_qa.py#L695-L706

in order to save the prediction (generation).
