### ISSUE TITLE
openlm-research/open_llama_13b_easylm cannot be downloaded

### ISSUE THREAD

**Issue by leweex95** [huggingface/transformers#24642]
### System Info

transformers: 4.30.2.
Python: 3.9.17
OS: MacOS Ventura 13.3.1 (a) 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code to reproduce:

```
model_id = "openlm-research/open_llama_13b_easylm"
model_name = model_id.split("/")[1]

model = pipeline(model=model_id)
model.save_pretrained(f"./models/{model_name}")
```

### Expected behavior

I expect the model to be downloadable locally for use in downstream NLP tasks. Noteworthy is that on the [website](https://huggingface.co/openlm-research/open_llama_13b_easylm) it is indicated that 0 people downloaded this model over the past month. 

With the above script, I can easily fetch other models such as `"openlm-research/open_llama_13b"`:

```
model_id = "openlm-research/open_llama_13b"
model_name = model_id.split("/")[1]

model = pipeline(model=model_id)
model.save_pretrained(f"./models/{model_name}")
```

**Comment by ydshieh** [comment]
Looking at 

https://huggingface.co/openlm-research/open_llama_13b_easylm/tree/main

The file doesn't seem to be torch bin file. 

However, https://huggingface.co/openlm-research/open_llama_13b/tree/main has those `.bin` files.

You will have to open an issue on that Hub repo. to discuss with the repo. owner.
