### ISSUE TITLE
Language Modeling on Already Tokenized Data

### ISSUE THREAD

**Issue by jorisperrenet** [huggingface/transformers#24673]
### System Info

When I try to execute [`run_clm.py`](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py) in the language modeling example I naturally get the question to specify the `tokenizer_name`.

Yet, my data is already tokenized, i.e. my train and validation look (very crudely) like
```
0 3111 5100 2100 3100 6000
1000 4067 3031 3068 5141 3073
1000 3067 6031 3068 5141 3076
```
Thus, sequences on separate lines.

My question is: is there some kind of workaround such that I can train a model on this already tokenized data?

Any help would be great!

### Who can help?

@ArthurZucker

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Inside `transformers/examples/pytorch/language-modeling` create the folder `output` and the file `train.txt` (with some numbers in it, see above).

```
python run_clm.py --model_type gpt2 --output_dir output --do_train --train_file train.txt
```

It returns
```
ValueError: You are instantiating a new tokenizer from scratch. This is not
supported by this script.You can do it from another script, save it, and load
it from here, using --tokenizer_name.
```

### Expected behavior

I would expect/prefer that the output would be a warning specifying that a "passthrough" tokenizer will be used.

**Comment by ydshieh** [comment]
The example scripts serve as examples 🤗 . If you need some custom modification(s), go for it.

In your case, you can probably skip the following block (and other similar places). You might need to assign your own tokenized dataset(s) to variables like `tokenized_datasets` however.

https://github.com/huggingface/transformers/blob/9a5d468ba0562e2d5edf9da787881fa227132bca/examples/pytorch/language-modeling/run_clm.py#L456-L470
