### ISSUE TITLE
OSError: Error no file named pytorch_model.bin

### ISSUE THREAD

**Issue by wangzff** [huggingface/transformers#24687]
### System Info

transformers==4.30.2

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

(base) /mnt/workspace/lawyer-llama/demo> python demo_web.py --port 7863 --checkpoint /mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0
Loading model...
Traceback (most recent call last):
File "/mnt/workspace/lawyer-llama/demo/demo_web.py", line 52, in
model = LlamaForCausalLM.from_pretrained(checkpoint, device_map="auto", torch_dtype=torch.float16)
File "/home/pai/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2449, in from_pretrained
raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0.

transformers==4.30.2

### Expected behavior

help me！

(base) /mnt/workspace/lawyer-llama/demo> python demo_web.py --port 7863 --checkpoint /mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0
Loading model...
Traceback (most recent call last):
File "/mnt/workspace/lawyer-llama/demo/demo_web.py", line 52, in
model = LlamaForCausalLM.from_pretrained(checkpoint, device_map="auto", torch_dtype=torch.float16)
File "/home/pai/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2449, in from_pretrained
raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0.

transformers==4.30.2

**Comment by amyeroberts** [comment]
Hi @wangzff, thanks for raising this issue. 

If you look at the contents of the checkpoint passed into the script, do you see the model weights? i.e. what is the output of `ls -al mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0`?
