### ISSUE TITLE
decoder_kwargs are not passed over to AutomaticSpeechRecognitionPipeline.tokenizer.decode 

### ISSUE THREAD

**Issue by devxpy** [huggingface/transformers#24707]
### Feature request

The `postprocess()` function here

https://github.com/huggingface/transformers/blob/fb78769b9c053876ed7ae152ee995b0439a4462a/src/transformers/pipelines/automatic_speech_recognition.py#L492-L494

should pass down the `decoder_kwargs` it receives down to the decoder

https://github.com/huggingface/transformers/blob/fb78769b9c053876ed7ae152ee995b0439a4462a/src/transformers/pipelines/automatic_speech_recognition.py#L563

### Motivation

Sometimes the decoder will output special tokens - https://github.com/huggingface/transformers/issues/15275 - and there's no way to pass `skip_special_tokens=True` to the decoder 

https://github.com/huggingface/transformers/blob/fb78769b9c053876ed7ae152ee995b0439a4462a/src/transformers/models/wav2vec2/tokenization_wav2vec2.py#L407-L416

### Your contribution

I can submit a PR

**Comment by ydshieh** [comment]
From https://github.com/huggingface/transformers/blob/fb78769b9c053876ed7ae152ee995b0439a4462a/src/transformers/pipelines/automatic_speech_recognition.py#L549-L552

That `decoder_kwargs` is for an instance of `BeamSearchDecoderCTC` and not a tokenizer.

But cc @ArthurZucker to see if he has more words to say.

**Comment by devxpy** [comment]
I guess we can have `tokenizer_decode_kwargs` too :)

**Comment by ArthurZucker** [comment]
Yep, pipeline does not support `**tokenizer_kwargs` yet. This has been talked about in #22995 and #12039. 
I am in for `tokenizer_kwargs`, not `tokenizer_decoder_kwargs`. We need to as less specific as possible. 

A con is that having lots of kwargs is hard to maintain and we are trying to get away from this. The tokenizer class can save the `_init_kwargs` which contains the last parameters with which the tokenizer was called. You can set them and pass the tokenizer to the pipeline
