### ISSUE TITLE
Amazon Sagemaker - huggingface-textgeneration1-gpt-j-6b-fp16

### ISSUE THREAD

**Issue by Mrin7** [huggingface/transformers#24713]
### System Info

Running on Amazon sagemaker notebook.(https://us-west-2.console.aws.amazon.com/sagemaker/playground?region=us-west-2#/foundation-models/playground/prod-000000021)
ml.m5.xlarge | 4 vcpu | 16 GiB memory

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

(https://huggingface.co/docs/transformers/main/model_doc/gptj) The hugging face repo claims that the fp16 model should be able to run on 16 GB GPU memory for inference. I am using ml.m5.xlarge | 4 vcpu | 16 GiB memory in Amazon Sagemaker to deploy the model.
Why am I getting data load error in Amazon sagemeaker?

Can someone please share steps to deploy a model in sagemaker. Moreover how do we requisition ASW to allocate us larger resource, if models won't work on these instances.? It requires an organization for instance allocation, are individuals not able to test models on AWS sagemaker.

### Expected behavior

Error hosting endpoint jumpstart-example-huggingface-textgener-2023-07-07-13-55-56-291: Failed. Reason: Failed to extract model data archive from URL "s3://jumpstart-cache-prod-us-west-2/huggingface-infer/prepack/v1.1.2/infer-prepack-huggingface-textgeneration1-gpt-j-6b-fp16.tar.gz". The model data archive is too large. Please reduce the size of the model data archive or move to an instance type with more memory.

**Comment by amyeroberts** [comment]
Hi @Mrin7, thanks for raising an issue! 

When creating issues on github, please create a separate issue for each individual question. 

With regards to your first question, the docs state that the model can fit into 16 GB of RAM for interference, however there may be other processes or objects which have memory requirements resulting in the total amount of GPU RAM needed being  above 16 GB. Without knowing exactly what you're running it's not possible to know. 

For questions on how to deploy on sagemaker, please refer to the docs: https://huggingface.co/docs/sagemaker/inference. If you still have questions, then it's best asked in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
