### ISSUE TITLE
Possibly a bug in Pix2Struct outputs

### ISSUE THREAD

**Issue by artyomxyz** [huggingface/transformers#24717]
I'm sorry if I'm wrong, as I don't have much experience with transformers internals.
I was playing with Pix2Struct and trying to visualise attention on input image. `output.cross_attentions` shape didn't make much sense as it didn't have `patch_count` as any of dimensions. After inspecting `modeling_pix2struct.py` I have notices the following
```
            # layer_outputs = hidden-states, key-value-states (self-attention position bias), (self-attention weights),
            # (cross-attention position bias), (cross-attention weights)
```
And then later
```
            if output_attentions:
                all_attentions = all_attentions + (layer_outputs[2],)
                all_cross_attentions = all_cross_attentions + (layer_outputs[3],)
```

As I understand `layer_outputs[3]` is `(self-attention weights)` and it should be replaces with `layer_outputs[5]` which is `(cross-attention weights)`. The same goes of `(layer_outputs[2],) => (layer_outputs[3],)`

Does it make sense, or am I getting something wrong?

I tried to patch it locally and output + visualisation make sense (highlight image patch with information in token)

https://github.com/huggingface/transformers/blob/fe861e578f50dc9c06de33cd361d2f625017e624/src/transformers/models/pix2struct/modeling_pix2struct.py#L1550C74-L1550C74

**Comment by amyeroberts** [comment]
Hi @artyomxyz, thanks for reporting this issue.

Yes, you're right, there is a current issue with indexing in the Pix2Struct model. Related PR: #23985

cc @younesbelkada

**Comment by loveisp** [comment]
> Hi @loveisp ! Again thanks for your contribution on this Can you share with us why this PR got closed? The PR should also fix #24717 so it would be great to merge it :D

I initially made the change like this, but it didn't pass all the tests: https://github.com/huggingface/transformers/pull/23985/commits/b0ea57aafce734de618bb045920898bb811133de .  The len(layer_outputs) here seemed a bit strange, so I changed it to what came later. However, the logic here still seems odd to me. You can take a look at my discussion with @amyeroberts . I realized that I cannot fix this bug in a short amount of time, so I closed it. Will it be sufficient to make this change as he suggested, so that it passes all the tests? If so, then go ahead and make the change.

**Comment by rish-hyun** [comment]
Hello, I have a question, How does `Pix2StructForConditionalGeneration.decoder` works for `doc-vqa`? 
I have got output from `Pix2StructForConditionalGeneration.encoder` which includes `last_hidden_state=[some tensor], hidden_states=None, attentions=None`.

**Comment by amyeroberts** [comment]
Hi @rish-hyun. 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

If you want to see examples of how to use a model, you can check out the docs and model code: 
* https://huggingface.co/docs/transformers/model_doc/pix2struct#transformers.Pix2StructForConditionalGeneration.forward.example
* For example, you can see the model output of the [encoder here](https://github.com/huggingface/transformers/blob/e7b001db4fbd33d77de95cf684d13d7605660d1b/src/transformers/models/pix2struct/modeling_pix2struct.py#L654).
