### ISSUE TITLE
install from source dont work

### ISSUE THREAD

**Issue by IdoTal120** [huggingface/transformers#24723]
### System Info

ms server 2019 

PS C:\Users\a_ital> pip install git+https://github.com/huggingface/transformers
Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to c:\users\a_ital\appdata\local\temp\6\pip-req-build-no6t74od

  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

PS C:\Users\a_ital> pip install git+https://github.com/huggingface/transformers
Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to c:\users\a_ital\appdata\local\temp\6\pip-req-build-no6t74od

  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
PS C:\Users\a_ital>

### Expected behavior

I need to install transformers

**Comment by SoyGema** [comment]
Hello @IdoTal120 ! Welcome to Github, 👋
Taking this into account
```
ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```


The error message is telling you that `pip `doesn't know where you have installed `git`. Can you confirm that you have `git` installed? It can be installed for Windows [here](https://git-scm.com/download/win).

Then you need to add it to the PATH environment variable. Currently, `pip` is checking for `git.exe `in all the locations listed in PATH, but the location for the` git `executable is not there. I believe during installation of git you have the option to update PATH automatically, but you can do it at any time: find the filepath to git.exe on your local machine (for example, `C:\Program Files\...\git\bin`) and then add it to PATH ([instructions here for your operating system I think](https://www.opensourceforu.com/2021/01/how-to-install-and-configure-git-on-a-windows-server/)).

Taken from [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues/3)
Let me know how it goes and welcome to the Open!
