### ISSUE TITLE
ALBERT tokenizer : local variable 'tokenizer' referenced before assignment

### ISSUE THREAD

**Issue by rdisipio** [huggingface/transformers#2474]
## 🐛 Bug

Model I am using BERT and ALBERT

Language I am using the model on: English

The problem arise when using:
* my own script

The tasks I am working on is:
* my own task or dataset: text classification

## To Reproduce

```$ pip install transformers```
This installs version 2.3.0

```
>>> from transformers import AlbertTokenizer
>>> tokenizer = AlbertTokenizer.from_pretrained("albert-base")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Riccardo/development/ideal/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 302, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/Users/Riccardo/development/ideal/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 444, in _from_pretrained
    tokenizer.init_inputs = init_inputs
UnboundLocalError: local variable 'tokenizer' referenced before assignment
```

## Expected behavior

It works perfectly with Bert, e.g.:
```
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
```

## Environment

* OS: MacOsX 10.14
* Python version: 3.7.5
* TensorFlow version: 2.0
* Using GPU ? No
* Distributed or parallel setup ? None

**Comment by LysandreJik** [comment]
The error is misleading, I’ll fix that. Your error stems from the tokenizer initialization: there is no pretrained checkpoint called “albert-base”, only “albert-base-v1” or “albert-base-v2”.

You can check the list of pretrained models here: https://huggingface.co/transformers/pretrained_models.html

**Comment by rdisipio** [comment]
Oh, I see. I confirm it works correctly if I load the model `albert-base-v2`. Thanks for taking care of improving the error message!
