### ISSUE TITLE
docker/transformers-all-latest-gpu/Dockerfile Not Work

### ISSUE THREAD

**Issue by zyh3826** [huggingface/transformers#24740]
### System Info

Docker: 20.10.12

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. change pip mirror to aliyun
2. `docker build -t huggingface .`

### Expected behavior

an error happened:
```
Step 16/24 : RUN python3 -m pip install --no-cache-dir -e ./transformers[dev,onnxruntime]
 ---> Running in 1dc79ba974ba
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Obtaining file:///root/transformers
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting packaging>=20.0
  Downloading https://mirrors.aliyun.com/pypi/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl (40 kB)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Downloading https://mirrors.aliyun.com/pypi/packages/29/9c/936ebad6dd963616189d6362f4c2c03a0314cf2a221ba15e48dd714d29cf/tokenizers-0.13.3.tar.gz (314 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting tqdm>=4.27
  Downloading https://mirrors.aliyun.com/pypi/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting requests
  Downloading https://mirrors.aliyun.com/pypi/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl (63 kB)
ERROR: Could not find a version that satisfies the requirement huggingface-hub<1.0,>=0.14.1 (from transformers[dev,onnxruntime]) (from versions: 0.0.1, 0.0.2, 0.0.3rc1, 0.0.3rc2, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.4.0)
ERROR: No matching distribution found for huggingface-hub<1.0,>=0.14.1
The command 'sh -lc python3 -m pip install --no-cache-dir -e ./transformers[dev,onnxruntime]' returned a non-zero code: 1
```
Could you tell me the right ` huggingface-hub` version? thanks a lot

**Comment by ydshieh** [comment]
The problem in the used (pip) `index-url` being `https://mirrors.aliyun.com/pypi/simple`, where it can't find higher version of `huggingface_hub`.  From the provided log, the highest version it has is `0.4.0`.

It should work fine if you are using `https://pypi.org/simple` as the pip index.

**Comment by zyh3826** [comment]
> The problem in the used (pip) `index-url` being `https://mirrors.aliyun.com/pypi/simple`, where it can't find higher version of `huggingface_hub`. From the provided log, the highest version it has is `0.4.0`.
> 
> It should work fine if you are using `https://pypi.org/simple` as the pip index.

Thanks for your reply. I find the reason is `Python version`, this command `apt install python3` only installs the python3.6, but huggingface-hub seems like needs python >= 3.7, so I change it to `apt install python3.8' at 
[line 19](https://github.com/huggingface/transformers/blob/main/docker/transformers-all-latest-gpu/Dockerfile#L19), and it worked, but when installing `kenml`, a compile fail error happened, I think `kenml` should be installed via build not pip.
Finally, I pull this image from your docker hub since build it myself really slow

**Comment by ydshieh** [comment]
Yeah nice! If the pull from our docker hub works, it's definitely easier :-) 

BTW, may I wonder why you need to use our docker image. We only use it for our CI testing.

**Comment by zyh3826** [comment]
> Yeah nice! If the pull from our docker hub works, it's definitely easier :-)
> 
> BTW, may I wonder why you need to use our docker image. We only use it for our CI testing.

because I need to install the newest pytorch and tensorflow, the easiest way is docker, since tensorflow2.xx having packages compatibility problems, so I find your Dockerfile
