### ISSUE TITLE
sample code in for mobilevitv2 is not working

### ISSUE THREAD

**Issue by darwinharianto** [huggingface/transformers#24763]
### System Info

- `transformers` version: 4.31.0.dev0
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.10.11
- Huggingface_hub version: 0.14.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?:no

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run sample code from [MobileViTV2ForImageClassification](https://huggingface.co/docs/transformers/v4.30.0/en/model_doc/mobilevitv2#transformers.MobileViTV2ForImageClassification)

throws an error

ValueError: Unrecognized image processor in apple/mobilevitv2-1.0-imagenet1k-256. Should have a `image_processor_type` key in its preprocessor_config.json of config.json, or one of the following `model_type` keys in its config.json: align, beit, bit, blip, blip-2, bridgetower, chinese_clip, clip, clipseg, conditional_detr, convnext, convnextv2, cvt, data2vec-vision, deformable_detr, deit, deta, detr, dinat, donut-swin, dpt, efficientformer, efficientnet, flava, focalnet, git, glpn, groupvit, imagegpt, instructblip, layoutlmv2, layoutlmv3, levit, mask2former, maskformer, mgp-str, mobilenet_v1, mobilenet_v2, mobilevit, mobilevitv2, nat, oneformer, owlvit, perceiver, pix2struct, poolformer, regnet, resnet, sam, segformer, swiftformer, swin, swin2sr, swinv2, table-transformer, timesformer, tvlt, upernet, van, videomae, vilt, vit, vit_hybrid, vit_mae, vit_msn, xclip, yolos

### Expected behavior

sample code should not throw an error

**Comment by ydshieh** [comment]
Hi @darwinharianto 

Thank you for opening the issue.

Could you specify which code sample in the link is the exact one that has problem to run? Thank a lot!

**Comment by amyeroberts** [comment]
@darwinharianto Thanks for reporting this! It seems the issue is coming from the preprocessor config files on the hub for this checkpoint: [it points to a class which doesn't exist](https://huggingface.co/apple/mobilevitv2-1.0-imagenet1k-256/blob/6229cf24f57fe7210db6c6f1ad872a616b802679/preprocessor_config.json#L10).

I'll also add this modeling file to our doctests.
