### ISSUE TITLE
添加peft模型的resume_from_checkpoint实现

### ISSUE THREAD

**Issue by 506610466** [huggingface/transformers#24818]
### Feature request

现阶段
trainer.train(resume_from_checkpoint=resume_from_checkpoint)
不能够加载adapter 权重进行 resume

### Motivation

现阶段
trainer.train(resume_from_checkpoint=resume_from_checkpoint)
不能够加载adapter 权重进行 resume

### Your contribution

没有

**Comment by amyeroberts** [comment]
Hi @506610466, thanks for raising an issue. 

Could you please follow the issue template and provide all the information requested, including the running environment, a minimal code snippet to reproduce the error, full traceback and expected behaviour?
