### ISSUE TITLE
transformers-like library for Prompt or Agent library?

### ISSUE THREAD

**Issue by ghosthamlet** [huggingface/transformers#24815]
### Feature request

Add advanced Prompt or Agent methods as models to transformers library, or build a new advanced Prompt or Agent library use ARCH like transformers library.

### Motivation

There are many Prompt/Agent libraries like: https://langchain.com/  https://github.com/yoheinakajima/babyagi  https://github.com/Significant-Gravitas/Auto-GPT, but they are all have too many abstracts in code or just a framework for automatic tasks. 

transformers/diffusers library has simple abstracts, If there is advanced Prompt or Agent library like transformers/diffusers, it will be much better for researchers to do research work. and i think huggingface is the best to build this library.

### Your contribution

Currently no.

**Comment by amyeroberts** [comment]
Hi @ghosthamlet, 

Have you checked out Agents and Tools from Hugging Face?  https://huggingface.co/docs/transformers/v4.30.0/en/transformers_agents

**Comment by ghosthamlet** [comment]
@amyeroberts Thanks, it looks great. I found the code is all in src/transformers/tools, seems like it is not as flexible as transformers.
if someone wants to integrate a new agent like `Reflexion: Language Agents with Verbal Reinforcement Learning`, can it be as easy as integrate a transformers model?

**Comment by amyeroberts** [comment]
@ghosthamlet Easiness is subjective, so it would depend on what you do and don't find easy with the transformers library :) 

This is a question best placed in our [forums](https://discuss.huggingface.co/), as we try to reserve the github issues for feature requests and bug reports.

**Comment by ghosthamlet** [comment]
@amyeroberts Thanks, I understand now. 
I will create a separate issue.
