### ISSUE TITLE
Proper way to monkey patch a customized model no in transformers?

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#24816]
### Feature request

Hi, nowadays more and more model emerging out, many of them hard to merge transformers, but we have more and more customized patchs such as condensing rotary, xformers attn etc.

What is the best to monkey patch a customized model which not inside transformers library but just loaded with AutoModel?

### Motivation

need guidance

### Your contribution

current not

**Comment by amyeroberts** [comment]
Hi @lucasjinreal, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
