### ISSUE TITLE
OpenAIGPTModel raises exception with `afn="Relu"`

### ISSUE THREAD

**Issue by nathan-chappell** [huggingface/transformers#24821]
### System Info

- `transformers` version: 4.30.2
- Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@ArthurZucker 
@younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers.models.openai import OpenAIGPTConfig, OpenAIGPTModel
OpenAIGPTModel(OpenAIGPTConfig(n_vocab=1, n_embed=1, afn="relu"))(torch.eye(1, dtype=int))

# raises:
# AttributeError: 'ReLU' object has no attribute 'size'
```

### Expected behavior

I would expect no error to be raised and the calculation to be performed.  For example, the following code behaves as expected:

```python
OpenAIGPTModel(OpenAIGPTConfig(n_vocab=1, n_embed=1, afn="gelu"))(torch.eye(1, dtype=int))
```

**Comment by ArthurZucker** [comment]
Hey thanks for reporting and providing a very efficient snippet! Indeed the relu is not initialized thus you have the error. Reviewing your PR now
