### ISSUE TITLE
Trainer logs to wrong wandb project

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/transformers#24847]
### System Info

- `transformers` version: 4.30.2
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I've written my own `train.py` based on [sequence_classification](https://huggingface.co/docs/transformers/tasks/sequence_classification). I see the same issue for official scripts.

before running I initialise wandb logging (`wandb init`). This creates `wandb/settings` containing the project name I chose for my model

```
[default]
entity = my-username
project = my-project
base_url = https://api.wandb.ai
```

But the Trainer logs everything to the project `huggingface`, i.e. it's ignoring/overriding the project name I've configured.

### Expected behavior

Don' over-ride the configured wandb project with a default.

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
This actually isn't possible currently, you need to set environmental variables such as `export WANDB_PROJECT my-project`

**Comment by DebarshiChanda** [comment]
@david-waterworth You can use the os module to set the environment variable or use what @muellerzr suggested
```
import os
os.environ["WANDB_PROJECT"] = "my-project"
```

**Comment by david-waterworth** [comment]
Thanks @muellerzr but I'm not sure what you mean by not possible? It is possible in general, the steps I follow are:

1. Create a new project

``` bash
mkdir my_project
cd my_project
python3 -m venv .venv
source .venv/bin/activate
pip install -U pip
```

3. Initialise wandb

``` bash
pip install wandb
wandb init
```

In the last step I create a new project name (say test), this creates `wandb/settings`

``` bash
cat wandb/settings
```

```
[default]
entity = my-user
project = test
base_url = https://api.wandb.ai
```

4. Create a script

``` python
import wandb
wandb.init() # Don't pass a project name!

print(wandb.run.project_name()) # correctly picked up setting from wandb/settings
```

I'm assuming that what the trainer does is check the env variable, and if its not set, explicitly passes "huggingface" as the project - i.e.

```
wandb.init("huggingface")
```

As a workaround, I can parse the settings file myself and set the env variable
