### ISSUE TITLE
Loading model microsoft/tapex-base-finetuned-wtq failed with error No module named 'transformers.models.tapex'

### ISSUE THREAD

**Issue by WeichenXu123** [huggingface/transformers#24852]
### System Info

OS: Ubuntu 22.04

Python 3.9

Packages installed:
```
pip install git+https://github.com/huggingface/transformers
pip install datasets huggingface_hub torch torchvision tensorflow accelerate librosa ffmpeg
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Code

```
import transformers

transformers.pipeline(
    task="table-question-answering", model="microsoft/tapex-base-finetuned-wtq"
)
```

raises error:

```
ModuleNotFoundError: No module named 'transformers.models.tapex'
```

### Expected behavior

Returns `transformers.pipelines.table_question_answering.TableQuestionAnsweringPipeline` object

**Comment by sgugger** [comment]
I'm unable to reproduce this on my side. Are you sure you are using the latest commit from main?

**Comment by WeichenXu123** [comment]
@sgugger 

Yes. I installed it  by:
`pip install git+https://github.com/huggingface/transformers`

and then in python REPL, run:
```
import transformers

transformers.pipeline(
    task="table-question-answering", model="microsoft/tapex-base-finetuned-wtq"
)
```


Our MLflow CI (run against transformer master) has the same error:
https://github.com/mlflow/mlflow/actions/runs/5567846085/jobs/10170056430#step:15:526

**Comment by WeichenXu123** [comment]
@sgugger Did you run it on ubuntu system ?

**Comment by sgugger** [comment]
I had some `__pycache__` remaining in `models/tapex` so it didn't error, but after cleaning that folder I can reproduce. Having a look, the fix should come this afternoon.

**Comment by sgugger** [comment]
It was actually fairly easy to fix. Could you quickly check the PR above solves the issue for you too?
