### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (60,4) (24,2,60,16,1024,64)

### ISSUE THREAD

**Issue by Luke-4** [huggingface/transformers#24866]
I am trying to fine-tune a model using the trainer API but I am getting this error: 
![image](https://github.com/huggingface/transformers/assets/138615931/22a5ce44-a0ee-4fba-83f4-9d31c9ce76d4)

I have looked online and I can't find anything similar to this, at least related to transformers and NPL.

here is the code that I am using:
https://colab.research.google.com/drive/1hdAG3rC1LHp7tJ4DCKbt90IDFsGcubHf?usp=sharing

**Comment by sgugger** [comment]
You should use the [forums](https://discuss.huggingface.co/) to debug your code as we keep issues for feature requests and bugs in the library only. Here it seems your `compute_metrics` function does not take the logits from the result of the model, which contains two arrays at least (the logits and some kind of hidden state).
