### ISSUE TITLE
Amazon Bedrock model as HfAgent

### ISSUE THREAD

**Issue by austinmw** [huggingface/transformers#24870]
### Feature request

I'd like to be able to use Amazon Bedrock available models, for example Claude, as the HfAgent model.

### Motivation

Expanded model support

### Your contribution

Not sure currently.

**Comment by ydshieh** [comment]
Hi @austinmw Thank you for this feature request.

I am not sure however, cc my colleague @sgugger who knows much better on the Agent topic!
