### ISSUE TITLE
NER Pipeline Issue

### ISSUE THREAD

**Issue by ElToro13** [huggingface/transformers#2488]
I am trying to run NER Pipeline. Here, I am using the line, "Statue of Liberty is located in New York". I am getting the following output
[{'entity': 'I-MISC', 'score': 0.5469961762428284, 'word': 'St'},
 {'entity': 'I-MISC', 'score': 0.7588933706283569, 'word': '##at'},
 {'entity': 'I-MISC', 'score': 0.5194069147109985, 'word': '##ue'},
 {'entity': 'I-MISC', 'score': 0.8465802073478699, 'word': 'of'},
 {'entity': 'I-PER', 'score': 0.4912404716014862, 'word': 'Liberty'},
 {'entity': 'I-LOC', 'score': 0.9995675086975098, 'word': 'New'},
 {'entity': 'I-LOC', 'score': 0.999152660369873, 'word': 'York'}]

My Issue is, why is it breaking down to individual words. Is there a way to chunk?

**Comment by jotapem** [comment]
I am suffering from the same problem, trying to recover input texts from `examples/run_ner.py`.

**Comment by erip** [comment]
Agree. I find the use of BIO very unorthodox in this case; if B actually represented the beginning of an entity (vs. the beginning of the new entity of the same type), we could reconstruct these spans ourselves. Currently I don't think it's possible to perfectly reconstruct them, though.

**Comment by petulla** [comment]
👍

**Comment by enzoampil** [comment]
I believe this issue should be resolved by this recently merged [PR](https://github.com/huggingface/transformers/pull/3957), which allows for the extraction of **entity groups** 🙂

**Comment by julien-c** [comment]
Indeed, thanks @enzoampil!
