### ISSUE TITLE
Inconsistent results between LlamaTokenizer and LlamaTokenizerFast

### ISSUE THREAD

**Issue by BugWriter2** [huggingface/transformers#24918]
### System Info

- `transformers` version: 4.30.2
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.8.15
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1

### Who can help?

@ArthurZucker

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

```
from transformers import LlamaTokenizerFast, LlamaTokenizer

fast_tokenizer = LlamaTokenizerFast.from_pretrained('openlm-research/open_llama_7b')
slow_tokenizer = LlamaTokenizer.from_pretrained('openlm-research/open_llama_7b')

input_text = 'tasks'

slow_tokenizer.encode(input)  # [1, 8931]
fast_tokenizer.encode(input)  # [1, 31822, 31824, 5577]
```

### Expected behavior

.

**Comment by ArthurZucker** [comment]
Hey! Sorry but I cannot reproduce your issue:

```python 
In [2]: slow_tokenizer.encode(input_text)
Out[2]: [1, 8931]

In [3]: fast_tokenizer.encode(input_text)
Out[3]: [1, 8931]
``` 
Make sure you have the latest version of tokenizers maybe?
