### ISSUE TITLE
convertion to hf format of llama2 70b get kill

### ISSUE THREAD

**Issue by zixiliuUSC** [huggingface/transformers#24946]
### System Info

transformers 4.31.0
RAM: 20G, 8Core
A100-80GB

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run the checkpoint conversion python script provided by transformers and the program will get kill. I run it successfully to 7B and 13B model. 

### Expected behavior

Convert checkpoint properly.

**Comment by sgugger** [comment]
That is because you do not have enough CPU RAM to do the conversion. It needs 140GB of memory. If you have access to the weights, you can get them on the Hugging Face Hub (as long as you email address for HF matches the one with which you got the weights).

**Comment by mrseeker** [comment]
@sgugger The files on https://huggingface.co/meta-llama/Llama-2-70b are not converted. Could you point to the right one on the Hub?

**Comment by sgugger** [comment]
The repo suffixed with hf: https://huggingface.co/meta-llama/Llama-2-70b-hf
