### ISSUE TITLE
T5 Tokenizer Legacy behaviour warning

### ISSUE THREAD

**Issue by pointonjoel** [huggingface/transformers#24951]
### System Info

I am running on Google Collab (Python 3.10.6) using tokenizers-0.13.3, transformers-4.31.0,  huggingface-hub-0.16.4 ,safetensors-0.3.1

### Who can help?

@ArthurZucker @younesbelkada

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm getting a legacy behaviour warning come up when simply loading a T5 tokenizer - it appears even before using the tokenizer. Is there an updated way to load the tokenizer? The warning appears when running the following lines of code:

_from transformers import AutoTokenizer
tokeniser = AutoTokenizer.from_pretrained("google/mt5-small")_

The warning is:
_You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
/usr/local/lib/python3.10/dist-packages/transformers/convert_slow_tokenizer.py:470: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
warnings.warn(_

### Expected behavior

No warning

**Comment by ArthurZucker** [comment]
Hey! Will just answer for potentially confused users: 
- the warning is triggered if `legacy=True` which is the default for backward compatibility
- to use the latest behaviour, use `tokeniser = AutoTokenizer.from_pretrained("google/mt5-small", legacy=False)`

**Comment by nebrelbug** [comment]
It might be nice to add the fix to the error message -- it's a bit hard to find :)
