### ISSUE TITLE
run summarization

### ISSUE THREAD

**Issue by tigernandita** [huggingface/transformers#24967]
### System Info

with open(output_prediction_file, "w", encoding="utf-8") as writer:: The script opens the output file in write mode with UTF-8 encoding to handle non-ASCII characters

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

with open(output_prediction_file, "w" as writer)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe2' in position 1710: ordinal not in range(128)

### Expected behavior

It should generate predictions

**Comment by huyhuyvu01** [comment]
@ydshieh  I also got this problem when training LED. Here my env

**Comment by ydshieh** [comment]
Hi @huyhuyvu01 

we need a minimal (but self complete) reproducible code snippet to help.

**Comment by huyhuyvu01** [comment]
@ydshieh I train LED using the run_summarization.py examples using the below lines
CUDA_VISIBLE_DEVICES=0 python3 run_summarization.py \
    --model_name_or_path allenai/led-base-16384 \
    --train_file train.json \
    --validation_file test.json \
    --test_file test.json \
    --output_dir /hdd-6tb/llm_model/ouputs \
    --do_train \
    --do_predict \
    --num_train_epochs 10 \
    --source_prefix "summarize: " \
    --text_column "prompt" \
    --summary_column "completion" \
    --per_device_train_batch_size=8 \
    --per_device_eval_batch_size=8 \
    --logging_strategy steps\
    --evaluation_strategy epoch \
    --save_strategy epoch \
    --logging_steps 100 \
    --overwrite_output_dir \
    --predict_with_generate

**Comment by ydshieh** [comment]
Could you provide the json files (even the fake, tiny versions), or replace them with some public datasets on the Hub?
