### ISSUE TITLE
How to load tf1 BERT checkpoints and sentencepiece model from local folder?

### ISSUE THREAD

**Issue by sharavsambuu** [huggingface/transformers#2497]
## ❓ Questions & Help
We have BERT checkpoints trained for [Mongolian](https://github.com/tugstugi/mongolian-bert) language and planning to upload it to transformers library.

In order to do that, we have to check compatibility. I have following questions.

- How to load sentencepiece model from local folder?
- How to load TF1 checkpoints from local folder?

Thanks.

**Comment by claverru** [comment]
Hello,

I dont know about the first one, but I just resolve the latter. In case it helps:

`import tensorflow as tf
from transformers import TFBertForMaskedLM, BertTokenizer, BertConfig


tokenizer = BertTokenizer.from_pretrained('tfmodel/', do_lower_case=True)
print(tokenizer)

config = BertConfig.from_json_file('tfmodel/config.json')

model = TFBertForMaskedLM(config)
model.load_weights(filepath='tfmodel/model.ckpt-2000000')`

Found that solution after digging into the docs for a bit.

**Comment by claverru** [comment]
Hello @sharavsambuu ,

```python
I dont know about the first one, but I just resolve the latter. In case it helps:

import tensorflow as tf
from transformers import TFBertForMaskedLM, BertTokenizer, BertConfig


tokenizer = BertTokenizer.from_pretrained('tfmodel/', do_lower_case=True)
print(tokenizer)

config = BertConfig.from_json_file('tfmodel/config.json')

model = TFBertForMaskedLM(config)
model.load_weights(filepath='tfmodel/model.ckpt-2000000')
```

Found that solution after digging into the docs for a bit.
