### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'

### ISSUE THREAD

**Issue by neilyboi** [huggingface/transformers#2498]
## 🐛 Bug

Model I am using (Bert, XLNet....): Pipelines "question-answering" with the bert-large-cased-whole-word-masking-finetuned-squad model.

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [ ] the official example scripts: (give details)
* [ X] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ X] my own task or dataset: (give details)

Essentially I have a dataset of queries and contexts, and I want to generate a bunch of predictions for answers. The issue is that I cannot get the code to run on GPUs because it seems like the tokenized tensors are not added to the GPU on your end.

## To Reproduce

1. Simply try to do pipeline QA on a GPU
2.
3.

`import torch
  from transformers import *
  import pandas as pd
  import time

  qa = pipeline(task='question-answering', model= "bert-large-cased-whole-word-masking-   finetuned-squad", device=0, binary_output=True)

df = df.sample(frac=1).reset_index(drop=True)
df['answer'] = ""

context = [str(n) for n in list(df['body'])]

j = 0

for i in range(5,len(context),100):
    start = time.time()
    df.loc[j:i-1,'answer'] = qa(**{'question': list(df['query']),'context': context[j:i]})
    if (i == 5):
       df.to_csv("neil_answers.csv", mode = 'w') 
    else:
        df.to_csv("neil_answers.csv", mode = 'a')
    j = i
    print(time.time()-start)

`
## Expected behavior

The hope is for the pipeline to generate QA answers and append it to a csv file. The code was working (slowly) before I tried adding a GPU. The issue seems to be around adding the tokenized examples to the GPU

## Environment

* OS:
* Python version: 3.5
* PyTorch version: 1.2.0
* PyTorch Transformers version (or branch):
* Using GPU Yes
* Distributed or parallel setup ?
* Any other relevant information:
Running code on a GCP Jupyter Notebook, with one NVIDIA T4 GPU with CUDA `10`

## Additional context

<img width="1709" alt="Screen Shot 2020-01-10 at 2 48 37 PM" src="https://user-images.githubusercontent.com/51249406/72191858-73526480-33b8-11ea-8011-b7091398a1af.png">

**Comment by dslim23** [comment]
having the same issue on pretty much identical setup

**Comment by pierrerappolt** [comment]
same issue for me

**Comment by mfuntowicz** [comment]
Hi,

Can you try with the latest 2.4.0 transformers release and let us know if you still observe the same ?
