### ISSUE TITLE
[cookiecutter] Fails to create new model template

### ISSUE THREAD

**Issue by zekun-li** [huggingface/transformers#25003]
### System Info

2023-07-21 18:34:34.146635: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/zekun/transformers/src/transformers/commands/env.py:100: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.32.0.dev0
- Platform: Linux-4.14.290-217.505.amzn2.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.17
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): 2.13.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.7.0 (cpu)
- Jax version: 0.4.13
- JaxLib version: 0.4.13
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm trying to create a new model called `GeoLM` using the `cookiecutter` utility following the tutorial here: https://github.com/huggingface/transformers/tree/main/templates/adding_a_new_model 

However, the `transformers-cli add-new-model` was failed at one step, reporting a missing file error for `'cookiecutter-template-GeoLM/geolm.md'`. I can find a file named `geolm.mdx` under the same dir but not `geolm.md`. 

The previous step `pip install -e ".[quality]"` was completed without any error. The full running log is provided below. 

----------------------------------------------------------------------------------------------------------------------------

```
(huggingface) [zekun@ip-172-31-9-231 transformers]$ transformers-cli add-new-model
2023-07-21 18:33:20.317785: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/zekun/transformers/src/transformers/commands/add_new_model.py:58: UserWarning: The command `transformers-cli add-new-model` is deprecated and will be removed in v5 of Transformers. It is not actively maintained anymore, so might give a result that won't pass all tests and quality checks, you should use `transformers-cli add-new-model-like` instead.
  warnings.warn(
modelname [BrandNewBERT]: GeoLM
uppercase_modelname [BRAND_NEW_BERT]: GEOLM
lowercase_modelname [brand_new_bert]: geolm
camelcase_modelname [BrandNewBert]: GeoLM
authors [The HuggingFace Team]: Zekun Li
checkpoint_identifier [brand-new-bert-base-cased]: zekun-li/geolm-base-cased
Select tokenizer_type:
1 - Based on BERT
2 - Based on BART
3 - Standalone
Choose from 1, 2, 3 [1]: 1
Select generate_tensorflow_pytorch_and_flax:
1 - PyTorch, TensorFlow and Flax
2 - PyTorch & TensorFlow
3 - PyTorch & Flax
4 - TensorFlow & Flax
5 - PyTorch
6 - TensorFlow
7 - Flax
Choose from 1, 2, 3, 4, 5, 6, 7 [1]: 5
Select is_encoder_decoder_model:
1 - True
2 - False
Choose from 1, 2 [1]: 2
Traceback (most recent call last):
  File "/home/zekun/.conda/envs/huggingface/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'cookiecutter-template-GeoLM/geolm.md' -> '/home/zekun/transformers/docs/source/en/model_doc/geolm.md'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zekun/.conda/envs/huggingface/bin/transformers-cli", line 8, in <module>
    sys.exit(main())
  File "/home/zekun/transformers/src/transformers/commands/transformers_cli.py", line 55, in main
    service.run()
  File "/home/zekun/transformers/src/transformers/commands/add_new_model.py", line 185, in run
    shutil.move(
  File "/home/zekun/.conda/envs/huggingface/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/home/zekun/.conda/envs/huggingface/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/zekun/.conda/envs/huggingface/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'cookiecutter-template-GeoLM/geolm.md'
```

### Expected behavior

I should see the following files generated below:
```
docs/source/model_doc/<model_name>.md
src/transformers/models/<model_name>/configuration_<model_name>.py
src/transformers/models/<model_name>/modeling_<model_name>.py
src/transformers/models/<model_name>/modeling_tf_<model_name>.py
src/transformers/models/<model_name>/tokenization_<model_name>.py
tests/test_modeling_<model_name>.py
tests/test_modeling_tf_<model_name>.py
```

I can see some of these generated, missing the `*_tf_*` ones (expected) and these: 
```
docs/source/model_doc/<model_name>.md 
src/transformers/models/<model_name>/tokenization_<model_name>.py
tests/test_modeling_<model_name>.py
```

**Comment by sgugger** [comment]
Please note that this command is deprecated and it's better to use `add-new-model-like`. Will fix this though.

**Comment by zekun-li** [comment]
> Please note that this command is deprecated and it's better to use `add-new-model-like`. Will fix this though.

Good to know, thanks!
