### ISSUE TITLE
When I use the command "python convert_llama_weights_to_hf.py --input_dir /xxx/llama/ --model_size 70B --output_dir /xxxx/Llama-2-70b-chat-hf" killed

### ISSUE THREAD

**Issue by cm-liushaodong** [huggingface/transformers#25014]
### System Info

Hi,@ArthurZucker,@younesbelkada
When I use the command "python convert_llama_weights_to_hf.py --input_dir /xxx/llama/ --model_size 70B --output_dir /xxxx/Llama-2-70b-chat-hf", the following error occurred:
<img width="1342" alt="image" src="https://github.com/huggingface/transformers/assets/44772254/58946c17-e65d-4d56-b675-361ff0832576">
Additional Information: Memory Size：116GB
I noticed: Important note: you need to be able to host the whole model in RAM to execute this script (even if the biggest versions 
come in several checkpoints they each contain a part of each weight of the model, so we need to load them all in RAM).
I would like to ask, is there a parameter control, I can use disk instead of memory to complete the task? I can live with him running slower.

### Who can help?

@ArthurZucker
@younesbelkada

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

  python convert_llama_weights_to_hf.py  --input_dir /home/xxxx/llama/ --model_size 70B --output_dir /home/xxxx/llama/Llama-2-70b-chat-hf

### Expected behavior

it can execute successfully

**Comment by ArthurZucker** [comment]
Yes, as[ the documentation mentions, ](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py#L52):
```python 
Important note: you need to be able to host the whole model in RAM to execute this script (even if the biggest versions
come in several checkpoints they each contain a part of each weight of the model, so we need to load them all in RAM).
```
`killled` means you probably had a OOM issue. If you are on linux you can check with `dmesg -T| grep -E -i -B100 'killed process'`

**Comment by cm-liushaodong** [comment]
Thanks all, I used a machine with a larger memory to transcode successfully.

**Comment by amyeroberts** [comment]
@BramVanroy You can search for "Llama 70B" on hf.co and find a list of checkpoints: https://huggingface.co/models?search=llama%2070b

**Comment by BramVanroy** [comment]
@amyeroberts Not sure why you tagged me - perhaps by accident?

**Comment by amyeroberts** [comment]
Yes, sorry, my apologies! I meant to tag @BrookMakF

**Comment by amyeroberts** [comment]
Hi @BrookMakF, 

Questions such as these: how to fit your model onto a device are best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports. I recommend reading through the docs to see the recommended ways for loading models e.g. https://huggingface.co/docs/accelerate/usage_guides/big_modeling.
