### ISSUE TITLE
[docs] duplicate table of contents in perf_infer_gpu_one.mdx

### ISSUE THREAD

**Issue by eenzeenee** [huggingface/transformers#25028]
## Description
There are duplicate titles [**Requirements**] in `perf_infer_gpu_one.md` from line 51 and 117 causing an error occurs when moving the table of contents.

## Document / Language

`perf_infer_gpu_one.md` / en

## Suggestion

line 51

As is : 
```### Requirements```
To be : 
```### Requirements [[requirements-for-fp4-mixedprecision-inference]]```

line 117

As is : 
```### Requirements```
To be : 
```### Requirements [[requirements-for-int8-mixedprecision-matrix-decomposition]]```

Please let me know if I missed something in guideilnes.
Thank you in advance for your attention to it!

**Comment by stevhliu** [comment]
Good catch! I don't think this [doc](https://huggingface.co/docs/transformers/main/en/perf_infer_gpu_one) was refactored in the recent PR (it was just moved), and I'm getting the same error on the `main` branch.

Would you like to open a PR with your proposed fix? 🤗

**Comment by eenzeenee** [comment]
Thanks for your feedbacks. I opened PR https://github.com/huggingface/transformers/pull/25066!
