### ISSUE TITLE
Bug in autotokenizer some open source models such as falcon. 

### ISSUE THREAD

**Issue by Alkahwaji** [huggingface/transformers#25029]
### System Info

I want to get the sentence difference and use autotokenizer a falcon model 40B and 7B but usually, I receive an attribute error bug: model 'signal' has no attribute 'SIGALRM'.

![image](https://github.com/huggingface/transformers/assets/23569519/75d671dd-8b57-4447-acf2-5c093b79eddd)

@younesbelkada  @ArthurZucker @Rocketknight1

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

'''
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("tiiuae/falcon-40b-instruct")
model = AutoModelForCausalLM.from_pretrained("tiiuae/falcon-40b-instruct")

'''

![image](https://github.com/huggingface/transformers/assets/23569519/e53a5a08-459e-4dde-bb95-ac151a018a33)

### Expected behavior

Give me a method to get the word embeddings using sentence transformers or autotokenizer open source models such as falcon or LLMA2.

**Comment by Alkahwaji** [comment]
Thanks. 

![image](https://github.com/huggingface/transformers/assets/23569519/4921397e-8ae2-4cfe-925e-8415b5ab66af)

**Comment by ArthurZucker** [comment]
It seems that the [SIGALARM is not available on Windows](https://stackoverflow.com/questions/52779920/why-is-signal-sigalrm-not-working-in-python-on-windows). But I am not very familiar with this, will let @sgugger answer! 

As per the[ contribution guidelines](https://github.com/huggingface/transformers/blob/c9a82be592ca305180a7ab6a36e884bca1d426b8/CONTRIBUTING.md), could you provide the platform you are running this on? 
- which version of python are you using? 
- which version of transformers are you using? 
- are you on linux or windows?

**Comment by sgugger** [comment]
You can avoid this error by passing `trust_remote_code=True` (which is needed for this model). We will make the error message clearer when signal is not available.
