### ISSUE TITLE
BertTokenizerFast.encode() ignores max_length

### ISSUE THREAD

**Issue by yonigottesman** [huggingface/transformers#2504]
## 🐛 Bug
for this input: (from yelp review)
`text = "After a morning of Thrift Store hunting, a friend and I were thinking of lunch, and he suggested Emil's after he'd seen Chris Sebak do a bit on it and had tried it a time or two before, and I had not."`

If i use the standard BertTokenizer it works fine:
`tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')`
`len(tokenizer.encode(text, max_length=32))   `  
`output: 32`

but if i use the fast version:
`tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')`
`len(tokenizer.encode(text, max_length=32))   `  
**`output: 55`**

* OS: macos
* Python version: 3.6.5
* PyTorch version:  1.3.1
* PyTorch Transformers version (or branch): master branch
* Using GPU ? no
* Distributed or parallel setup ? no
* Any other relevant information: no

**Comment by julien-c** [comment]
I'll let @n1t0 chime in if needed, but in the `Fast` versions of the tokenizers you have to define the `max_length` at initialization, not when calling `.encode()`

Can you try this and let me know if it works?

**Comment by yonigottesman** [comment]
Oh You are right. When i init with max_length it works.
Is this documented?
Thanks
