### ISSUE TITLE
AttributeError: 'BertForTokenClassification' object has no attribute 'named_configeters'

### ISSUE THREAD

**Issue by Dhanachandra** [huggingface/transformers#2505]
```
    model = BertForTokenClassification.from_pretrained(bert_model)
```
Error: AttributeError: 'BertForTokenClassification' object has no attribute 'named_configeters'
When I initialized the model as 
```
model = BertForTokenClassification.from_pretrained(bert_model, 2)
```
Error: TypeError: from_pretrained() takes 2 positional arguments but 3 were given
```

**Comment by LysandreJik** [comment]
Hi, what is the variable `bert_model` you're showing? Could you provide more information e.g. the version of transformers, your version of python, your version of torch?
