### ISSUE TITLE
evaluation_strategy and eval_steps does not work

### ISSUE THREAD

**Issue by nkjulia** [huggingface/transformers#25071]
### System Info

- `transformers` version: 4.27.1
- Platform: Linux-4.15.0-200-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.16
- Huggingface_hub version: 0.13.2
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): 2.4.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

train LM use run_clm.py
paramters like below:
--model_name_or_path gpt2 \
--output_dir ${out_model_dir} \
--train_file ${train_file} \
--validation_file ${validation_file} \
--validation_split_percentage 5  \
--block_size 512 \
--num_train_epochs 2 \
--per_device_train_batch_size 16 \
--do_train --do_eval --line_by_line \
--evaluation_strategy steps \
--eval_steps 100

but no eval result printed when training.

### Expected behavior

print eval result every eval_steps

**Comment by sgugger** [comment]
Please provide a reproducer we can execute. We do not have your `train_file` and `validation_file`.

**Comment by enze5088** [comment]
I have the same problem after I update transformers to 4.33.2 and resuming interrupted training.  No matter how I change it, eval_steps and save_steps is always 500.

**Comment by ArthurZucker** [comment]
same comment, sorry but if we don't have a reproducer we cannot help you 😢
