### ISSUE TITLE
Need documentation for understanding the difference between `7B` and `7Bf`

### ISSUE THREAD

**Issue by scottfleming** [huggingface/transformers#25090]
Unclear what the tradeoffs are between using eg `7B` and `7Bf` as an argument for `model_size` in the `convert_llama_weights_to_hf.py` script:
https://github.com/huggingface/transformers/blob/f9cc333805c47665c6afee8b5867931e54abe0c6/src/transformers/models/llama/convert_llama_weights_to_hf.py#L65

**Comment by sgugger** [comment]
cc @ArthurZucker

**Comment by ArthurZucker** [comment]
Sure, we can add a bit of documentation, mentioning that this is specific to llama2 official release 😉
