### ISSUE TITLE
Wrong default values according to docstrings?

### ISSUE THREAD

**Issue by ebezzam** [huggingface/transformers#25108]
https://github.com/huggingface/transformers/blob/d941f07a4e3bc7b61b7afbd25d6e2e8427fccc6d/src/transformers/models/vit/configuration_vit.py#L100

https://github.com/huggingface/transformers/blob/d941f07a4e3bc7b61b7afbd25d6e2e8427fccc6d/src/transformers/models/vit/configuration_vit.py#L101

**Comment by ydshieh** [comment]
Hi @ebezzam 

I am not sure I understand the question. Could you describe it more precisely? Thanks.

**Comment by ebezzam** [comment]
Hi @ydshieh thank you for your quick response.

The docstring of [ViTConfig](https://github.com/huggingface/transformers/blob/d941f07a4e3bc7b61b7afbd25d6e2e8427fccc6d/src/transformers/models/vit/configuration_vit.py#L35) says that the default values for [`hidden_dropout_prob`](https://github.com/huggingface/transformers/blob/d941f07a4e3bc7b61b7afbd25d6e2e8427fccc6d/src/transformers/models/vit/configuration_vit.py#L58) and [`attention_probs_dropout_prob`](https://github.com/huggingface/transformers/blob/d941f07a4e3bc7b61b7afbd25d6e2e8427fccc6d/src/transformers/models/vit/configuration_vit.py#L60) are `0.1`, but in the code (linked above) they are set to `0.0`.

**Comment by ydshieh** [comment]
Thanks a lot @ebezzam , super clear now 🤗 

Will take a look

**Comment by ydshieh** [comment]
Hi @ebezzam 

From [the original ViT codebase](https://github.com/google-research/vision_transformer/blob/ac6e056f9da686895f9f0f6ac026d3b5a464e59e/vit_jax/configs/models.py#L123), they should be `0.0` for the `ViT-B/16` model.

The value `0.1` in the docstring is likely from a copy-paste.

Would you like to open a PR to help us correct those 2 values in the docstring? Thanks.

**Comment by ebezzam** [comment]
@ydshieh thanks for looking into that. Yes I can open a PR and link to this issue.

**Comment by ebezzam** [comment]
@ydshieh done!

**Comment by ydshieh** [comment]
Thank you again @ebezzam 🤗
