### ISSUE TITLE
ModuleNotFoundError: No module named 'model_bertabs' AND RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by TLCFYBJJHYYSND** [huggingface/transformers#2510]
## 🐛 Bug

Model I am using (Bert, XLNet....):Bert

Language I am using the model on (English, Chinese....):Chinese

The problem arise when using:
* [ ] the official example scripts: 

[1]ModuleNotFoundError: No module named 'model_bertabs' when run convert_bertabs_original_pytorch_checkpoint.py
[2] RuntimeError: CUDA error: device-side assert triggered when run  run_lm_finetuning.py

* [ ] my own modified scripts: (give details)
python convert_bertabs_original_pytorch_checkpoint.py \
    --bertabs_checkpoint_path /home/jhzhou/code/transformers-master/examples/summarization/data \
    --pytorch_dump_folder_path /home/jhzhou/code/transformers-master/examples/summarization/outputs/

export TRAIN_FILE=/home/jhzhou/transformers/examples/path/to/dataset/wiki.train.raw
export TEST_FILE=/home/jhzhou/transformers/examples/path/to/dataset/wiki.test.raw
export DataFile=/home/jhzhou/transformers/examples/path/to/dataset/out

CUDA_VISIBLE_DEVICES=0 python run_lm_finetuning.py \
    --output_dir /home/jhzhou/transformers/examples/path/to/dataset/out \
    --model_type=bert \
    --model_name_or_path bert-base-chinese \
    --do_train \
    --train_data_file=$TRAIN_FILE \
    --do_eval \
    --eval_data_file=$TEST_FILE \
    --mlm \
    --overwrite_output_dir 

    
    

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name):1.convert_bertabs_original_pytorch_checkpoint.py  
                                                                                2.run_lm_finetuning.py
* [ ] my own task or dataset: (give details):wiki.train.raw

## To Reproduce

1.
2.
3.

## Environment

* OS:
* Python version:3.6
* PyTorch version:1.3.1
* PyTorch Transformers version (or branch):  2.1.1
* Using GPU ? YES
* Distributed or parallel setup ? One GPU

## Additional context

First my task was fine-tuning with MLM,then i with the problem happened i found the way seems to be the solution  to convert the pytorch_model.bin to stuff that can be used in the program.https://github.com/huggingface/transformers/issues/1615 but it doesnt work to me.

**Comment by paulthemagno** [comment]
I have the same CUDA error with a finetuning of offical bert downloaded from s3. I'll wait for clarifications too.
