### ISSUE TITLE
Support End LR for Cosine LR Scheduler

### ISSUE THREAD

**Issue by yqy2001** [huggingface/transformers#25119]
### Feature request

Customize the end learning rate of a cosine LR scheduler, as a non-zero end lr is commonly used now (e.g., LLaMA-2 use 10% of peak lr as end lr).

![image](https://github.com/huggingface/transformers/assets/55196500/4a07777f-968c-47da-b836-0f84dfd07a4d)

### Motivation

non-zero end lr is commonly used now (e.g., LLaMA-2 use 10% of peak lr as end lr)

### Your contribution

Sorry, I don't think I can be of much help.

**Comment by sgugger** [comment]
You can pass along your custom scheduler to the `Trainer` :-)

**Comment by yqy2001** [comment]
OK, Thank you.
