### ISSUE TITLE
Trainer explodes with multiple validation sets used

### ISSUE THREAD

**Issue by radekosmulski** [huggingface/transformers#25127]
### System Info

- `transformers` version: 4.32.0.dev0
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
- Python version: 3.11.4
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.1
- Accelerate version: 0.22.0.dev0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no, running in notebook
- Using distributed or parallel set-up in script?: no, running in notebook

### Who can help?

@sgugger 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Using multiple datasets, the trainer looks for a key that doesn't exist and throws an error upon evaluation at the end of the epoch.

![image](https://github.com/huggingface/transformers/assets/2444926/bbc98fb0-b58d-42e0-8992-fef2139c5ad6)

### Expected behavior

Metrics are returned just fine. There is no error.

**Comment by sgugger** [comment]
Yes, multiple evaluation datasets are not supported in a notebook env, that is a known issue.

**Comment by sgugger** [comment]
Ah ah you don't need to close it ;-) It's not been high-priority for us but we should fix it at some point.

**Comment by radekosmulski** [comment]
Ok, sorry Sylvain 😊 Let me reopen the issue then! I thought it was a known issue as in "we know it doesn't work but it is meant to be broken in notebooks" and I just didn't realize that, but if it is a genuine issue then let me leave it open! 🙂

**Comment by ArthurZucker** [comment]
Will ping @pacman100 here to put this on radar for the trainer!

**Comment by sgugger** [comment]
More for @muellerzr, but he should already have it somewhere in his TODO for when he has time ;-)
