### ISSUE TITLE
Add support for timeout parameter for load_image

### ISSUE THREAD

**Issue by rolisz** [huggingface/transformers#25168]
### Feature request

Add a parameter timeout to the `image_utils.py:load_image` function, which would enable setting the timeout for the requests call. This parameter should be plumbed in through all the ways to call that function (so add support for it in all the image related pipelines).

Alternatively, you should add a `requests_params` parameter, which should be a dictionary, to enable passing any parameters to requests.get. 

### Motivation

When using requests, the default timeout is None, which means that the request will wait (hang) until the connection is closed. Some servers for whatever reason don't return anything, but also don't close the connection. It would be useful to be able to set a timeout for these cases. 

### Your contribution

I can contribute a PR for this.

**Comment by rolisz** [comment]
Do you have any preferences, keeping it simple, add just the timeout parameter, or adding a more general `requests_params`?

**Comment by sgugger** [comment]
I think keeping it simple is probably for the best.
