### ISSUE TITLE
Save only Bert Model after training a Sequence Classification Task/ LM finetuning Task. 

### ISSUE THREAD

**Issue by rahulbaburaj** [huggingface/transformers#2517]
## ❓ Questions & Help

1) How do I save only the BERT Model after finetuning on a Sequence Classification Task/ LM finetuning Task
2) How to load only BERT Model from a saved model trained on Sequence Classification Task/ LM finetuning Task

**Comment by LysandreJik** [comment]
By saving only BERT, do you mean saving only the transformer and not the classification layer as well?

**Comment by FacingBugs** [comment]
you can use the code snippet below:

```python
# load config
conf = BertConfig.from_pretrained('bert-base-uncased', num_labels=2)
# load a sequence model
bsm = BertForTokenClassification.from_pretrained('bert-base-uncased', config=conf)
# get bert core model
bcm = bsm.bert
# save the core model
bcm.save_pretrained('the output directory path')
# you also need to save your tokenizer in the same directory
```

**Comment by rahulbaburaj** [comment]
@FacingBugs Thank you.
