### ISSUE TITLE
conversational + text-generation pipelines fail to read max_length from GenerationConfig

### ISSUE THREAD

**Issue by yonigottesman** [huggingface/transformers#25185]
### System Info

- `transformers` version: 4.32.0.dev0
- Platform: macOS-13.3.1-arm64-arm-64bit
- Python version: 3.10.5
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: false
- Using distributed or parallel set-up in script?: false

### Who can help?

@Narsil @gante 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

~~~
pipe = pipeline("conversational", model="facebook/blenderbot_small-90M")
conv = Conversation("Does money buy happiness?" * 80)
gc = GenerationConfig(max_length=512)
pipe(conv, generation_config=gc)
~~~

This trims the input and log this message:
`Conversation input is to long (401), trimming it to (128 - 10)`
Even though I asked for `max_length=512` becase it ignores the gc and takes the models default

### Expected behavior

I expect the pipeline code to consider the `GenerationConfig` max_length but I see in the [code](https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/conversational.py#L269) that it just looks for the (deprecated) `max_length`.
There is a similar issue with the `text-generation` pipeline.

Ill be happy to open a pr and fix this. As I understand, I just need to check the `generate_kwargs` for a `generation_config` and check if it has a `max_length` or/and `max_new_tokens`.

**Comment by gante** [comment]
Hey @yonigottesman 👋  We are aware of this issue, where `GenerationConfig` is not being piped correctly at input verification time. This requires a pipeline-level change (and not simply a `Conversation`-level change), and we are working on it :)
