### ISSUE TITLE
config.json file not available 

### ISSUE THREAD

**Issue by andysingal** [huggingface/transformers#25215]
### System Info

colab 
notebook: https://colab.research.google.com/drive/118RTcKAQFIICDsgTcabIF-_XKmOgM-cc?usp=sharing

### Who can help?

@sgugger  @younesbelkada

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
RepositoryNotFoundError: 404 Client Error. (Request ID: 
Root=1-64c7ee9d-240cd76b269a914d67b458fa;dcab1901-0ebf-4282-b8a4-9d1e087de5b4)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

During handling of the above exception, another exception occurred:
```

### Expected behavior

https://huggingface.co/Andyrasika/qlora-2-7b-andy giving error: 
```
Andyrasika/qlora-2-7b-andy does not appear to have a file named config.json. Checkout 'https://huggingface.co/Andyrasika/qlora-2-7b-andy/7a0facc5b1f630824ac5b38853dec5e988a5569e' for available files.
```

**Comment by younesbelkada** [comment]
Hi @andysingal 
it seems you are trying to load an adapter model. You can load it with

```python
from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained("Andyrasika/qlora-2-7b-andy")
```

If you want to load the base model in 4bit:

```python
from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained("Andyrasika/qlora-2-7b-andy", load_in_4bit=True)
```

Once https://github.com/huggingface/transformers/pull/25077 will get merged you'll be able to load the model directly with `AutoModelForCausalLM`.

**Comment by andysingal** [comment]
Thanks for your email. But why am I getting the error message?. I already
have adapter_config. JSON .

**Comment by younesbelkada** [comment]
Hi @andysingal 
It is because `AutoModelForCausalLM` will look if there is any `config.json` file present on that model folder and not `adapter_config.json` which are two different file names

**Comment by andysingal** [comment]
When you run the model created it gives the same error. Assume I am making
an error in the notebook, but inference does not need to show the error on
your website?
Please advise on how to fix it?

**Comment by andysingal** [comment]
@younesbelkada Any updates?

**Comment by younesbelkada** [comment]
Hi @andysingal 
Thanks for the ping, as stated above, in your repository only adapter weights and config are stored. Currently it is not supported to load apapted models directly using `AutoModelForCausalLM.from_pretrained(xxx)`, please refer to this comment https://github.com/huggingface/transformers/issues/25215#issuecomment-1658859481 to effectively load the adapted model using PEFT library.

**Comment by pitehu** [comment]
I had the exact same issue. I had to remove the ~/.cache/huggingface and then it works for me.

**Comment by liugaohong** [comment]
> > 
> 
> Thanks @younesbelkada for your instant reply. My question is when i compute Text generation inference on your website it gives that error. **I understand i need to use peft for loading the adpater and config files using peft in my preferred env**
> 
> Looking forward to hearing from you @ArthurZucker

you may need to load the lora_adapter use the the following code
```python
model = AutoModelForCausalLM.from_pretrained("./original_model_path ", trust_remote_code=True)
model = PeftModel.from_pretrained(model, "./lora_model_path")
```

**Comment by isConic** [comment]
Im running into the same issue through the user interface

**Comment by himanshusikarwar** [comment]
it is throwing the same OS error even with 
`model = AutoPeftModelForCausalLM.from_pretrained("Andyrasika/qlora-2-7b-andy"`

**Comment by Monta79** [comment]
![image_2024-03-25_160246364](https://github.com/huggingface/transformers/assets/115806011/fa7e2219-96cf-4c5c-939e-c87d55260470)
Same problem here, anyone has solved ?
