### ISSUE TITLE
https://s3.amazonaws.com/models.huggingface.co/xxx/pytorch_model.bin failed or can not open at xxx/.cache/xxxxxxxxxx

### ISSUE THREAD

**Issue by 578123043** [huggingface/transformers#2522]
https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base/pytorch_model.bin
Could you access on https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base/pytorch_model.bin?

**Comment by julien-c** [comment]
The correct URL is `https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-pytorch_model.bin`

Did you see the url above somewhere?

**Comment by 578123043** [comment]
![image](https://user-images.githubusercontent.com/16147509/72700543-21af9400-3b87-11ea-9179-97afb05bb486.png)
To resoleved this , adding `config_class pretrained_model_archive_map base_model_prefix` at Class definition (not def __init__) as the image
