### ISSUE TITLE
Why I cannot assign new parameter to the whisper pretrained config?

### ISSUE THREAD

**Issue by teinhonglo** [huggingface/transformers#25258]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.31
- Python version: 3.10.11
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Why can I not assign a new parameter to the whisper pretrained config?

Note that the parameter "final_dropout" is not in a config of the "openai/whisper-small".

I used the code piece as following:
```
from transformers import AutoConfig, WhisperModel
config = AutoConfig.from_pretrained("openai/whisper-small", final_dropout=0.1)
config.final_dropout
```

The error is shown below:
```
AttributeError: 'WhisperConfig' object has no attribute 'final_dropout'
```

### Expected behavior

config.final_dropout=0.1

Any guidance would be appreciated.
Tien-Hong

**Comment by amyeroberts** [comment]
Hi @teinhonglo, thanks for raising this issue! 

The reason for not being able to assign through the `from_pretrained` call is a safety check. Unknown kwargs are not applied: their application is ambigious - should they control the `from_pretrained` behaviour or be set as a config attribute? You can see which kwargs weren't set using `return_unused_kwargs` argument c.f. [here](https://huggingface.co/docs/transformers/v4.31.0/en/main_classes/configuration#transformers.PretrainedConfig.from_pretrained.return_unused_kwargs) and [here](https://huggingface.co/docs/transformers/v4.31.0/en/main_classes/configuration#transformers.PretrainedConfig.from_pretrained.kwargs) in the docs.

After loading in the config, you can set attributes e.g.:
```
from transformers import AutoConfig, WhisperModel
config = AutoConfig.from_pretrained("openai/whisper-small")
config.final_dropout = 0.1
```
