### ISSUE TITLE
 how to print out the data loaded by each epoch during trainer.train() training?

### ISSUE THREAD

**Issue by ahong007007** [huggingface/transformers#25257]
### Feature request

please tell to me,
 how to print out the data loaded by each epoch during trainer.train() training?

### Motivation

 how to print out the data loaded by each epoch during trainer.train() training?

### Your contribution

 how to print out the data loaded by each epoch during trainer.train() training?

**Comment by amyeroberts** [comment]
Hi @ahong007007, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
