### ISSUE TITLE
[Question] How to load AutoFeatureExtractor on GPU?

### ISSUE THREAD

**Issue by treya-lin** [huggingface/transformers#25264]
Hi, I am following this guide to learn how to do audio classification with wav2vec2: https://huggingface.co/docs/transformers/main/tasks/audio_classification

I intend to extract features of my data with the following codes
```
feature_extractor = AutoFeatureExtractor.from_pretrained("/workspace/models/wav2vec2-large-robust")

def preprocess_function(examples):
    audio_arrays = [x["array"] for x in tqdm(examples["audio"])]
    inputs = feature_extractor(
        audio_arrays, sampling_rate=feature_extractor.sampling_rate, max_length=16000, truncation=True
    )
    return inputs

encoded_audio_dataset_train = audio_dataset_train.map(preprocess_function, remove_columns="audio", batched=True)
```
But it seems the extractor is loaded to CPU instead of GPU, and I didn't find in documentation how to set the device for loading feature extractor. I assume the feature extraction is done by the wav2vec2 model itself right? If so how to do this on GPU? Or is it mentioned in any documentation that I didn't notice? 

This is my first time to use transformers library in audio processing so please forgive my clumsiness. 

Any help is much appreciated.

**Comment by amyeroberts** [comment]
Hi @treya-lin, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

You can move arrays prepared by the feature extractor to the GPU using the `to` method on its outputs: 

```
def preprocess_function(examples):
    audio_arrays = [x["array"] for x in tqdm(examples["audio"])]
    inputs = feature_extractor(
        audio_arrays, sampling_rate=feature_extractor.sampling_rate, max_length=16000, truncation=True
    ).to("cuda")
    return inputs
```
