### ISSUE TITLE
run_clm_no_trainer.py example - problem with most recent checkpoint loading

### ISSUE THREAD

**Issue by TomerRonen34** [huggingface/transformers#25269]
The example has code for finding the latest checkpoint, but accelerator.load_state isn't called.
https://github.com/huggingface/transformers/blob/1baeed5bdf3c58b723a6125632567f97bdf322c6/examples/pytorch/language-modeling/run_clm_no_trainer.py#L561C15-L561C15

**Comment by amyeroberts** [comment]
Hi @TomerRonen34, thanks for raising this issue! 

Can you make sure to follow the issue template and include: 
* A reproducible code snippet
* Details of the expected and observed behaviour including the full traceback if it exists
* Information about the running environment: run `transformers-cli env` in the terminal and copy-paste the output

**Comment by muellerzr** [comment]
Thanks, this has now been fixed via #25318
