### ISSUE TITLE
How to get the output in other layers from Bert?

### ISSUE THREAD

**Issue by zy4bvb** [huggingface/transformers#2527]
## ❓ Questions & Help
I want to analyze the information that every bert layers contains.  But i found the BertModel only output the sentence embbeding and the CLS embbeding.

**Comment by BramVanroy** [comment]
Have a look at the [documentation](https://huggingface.co/transformers/model_doc/bert.html#bertmodel), particularly at the point about 'outputs'.  You'll see that when you use `output_hidden_states=True`, you'll get _all_ outputs back, like so:

```python
model = BertModel.from_pretrained('bert-base-uncased', output_hidden_states=True)
```

**Comment by zy4bvb** [comment]
> Have a look at the [documentation](https://huggingface.co/transformers/model_doc/bert.html#bertmodel), particularly at the point about 'outputs'. You'll see that when you use `output_hidden_states=True`, you'll get _all_ outputs back, like so:
> 
> ```python
> model = BertModel.from_pretrained('bert-base-uncased', output_hidden_states=True)
> ```

Thank you!
