### ISSUE TITLE
Transformers Agent suggesting it should use text_generator although it is not provided.

### ISSUE THREAD

**Issue by tordbb** [huggingface/transformers#25287]
### System Info

I am running a version of  [your notebook on Transformers Agent](https://colab.research.google.com/drive/1c7MHD-T1forUPGcC_jlwsIptOzpG3hSj), where I have added a cell where I ask the StarCoder agent to generate a sentence for me. 

I am using StarCoder, as you can see:
```
#@title Agent init
agent_name = "StarCoder (HF Token)" #@param ["StarCoder (HF Token)", "OpenAssistant (HF Token)", "OpenAI (API Key)"]

import getpass

if agent_name == "StarCoder (HF Token)":
    from transformers.tools import HfAgent
    agent = HfAgent("https://api-inference.huggingface.co/models/bigcode/starcoder")
    print("StarCoder is initialized 💪")
elif agent_name == "OpenAssistant (HF Token)":
    from transformers.tools import HfAgent
    agent = HfAgent(url_endpoint="https://api-inference.huggingface.co/models/OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5")
    print("OpenAssistant is initialized 💪")
if agent_name == "OpenAI (API Key)":
    from transformers.tools import OpenAiAgent
    pswd = getpass.getpass('OpenAI API key:')
    agent = OpenAiAgent(model="text-davinci-003", api_key=pswd)
    print("OpenAI is initialized 💪")
```

### Who can help?

 @ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Based on the notebook mentioned, I have added a cell where I prompt the following:
```
agent.run("Write a sentence of the form 'A_ V_ at P_', where A_ should be replaced by the name of an animal, V_ should be replaced by a verb, and P_ should be replaced by the name of a place. Examples for valid sentences are 'Dog eating at macdonalds', 'Horse jumping at a gym', 'Duck fishing at a supermarket'. ")
```

As you see in the printout below, it suggests it will use the tool 'text_generation', but then stops because it does not have access to it. 

```
==Explanation from the agent==
I will use the following  tools: `text_classifier` to classify the sentence, then `text_generator` to generate the sentence.


==Code generated by the agent==
sentence = text_generator(prompt="A_ V_ at P_")
print(f"The sentence is {sentence}.")
sentence_class = text_classifier(sentence)
print(f"The sentence class is {sentence_class}.")


==Result==
Evaluation of the code stopped at line 0 before the end because of the following error:
It is not permitted to evaluate other functions than the provided tools (tried to execute text_generator).
```

### Expected behavior

Either, the agent should not even consider using "text_generation" as a tool, or it should have access to this tool as default.

**Comment by sgugger** [comment]
I'm not too sure why you are reporting a bug. The agent is an LLM which sometimes hallucinate content (in this case, a tool that does not exist). If your prompt does not work, you should try refining it. You should also try using another model and see if it performs better.
