### ISSUE TITLE
How to download files from HF spaces

### ISSUE THREAD

**Issue by andysingal** [huggingface/transformers#25280]
### System Info

google colab 

### Who can help?

@sanchit-gandhi @rock

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

i tried:
```
from huggingface_hub import hf_hub_download,hf_hub_url
# model_path  = hf_hub_download(repo_id="xinyu1205/recognize-anything", filename="tag2text_swin_14m.pth",  local_dir = "/content")
```
but throws an error repo not present

### Expected behavior

download the file

**Comment by amyeroberts** [comment]
Hi @andysingal, 

There is a typo in the repo_id. The correct command is: 

```
model_path  = hf_hub_download(repo_id="xinyu1205/recognize_anything_model", filename="tag2text_swin_14m.pth",  local_dir = "/content")
```

If you receive an error that a repo doesn't exist, the best thing to do is check directly on the hub for the repo and file name.

**Comment by andysingal** [comment]
The file exists in the space

**Comment by amyeroberts** [comment]
If downloading from the space, then you should specify the repo type in the `hf_hub_download` command

```
model_path  = hf_hub_download(repo_id="xinyu1205/recognize-anything", filename="tag2text_swin_14m.pth",  local_dir = "/content", repo_type="space")
```
