### ISSUE TITLE
[Question] Add extra sublayer for each layer of Transformer

### ISSUE THREAD

**Issue by robinsongh381** [huggingface/transformers#2528]
## ❓ Questions & Help

Hello !

BERT base has 12 layers and each layer includes follwing sublayer ( and of course, add norm)

` {self-attention -> feed-foward} `

I was wondering if there is a way of adding extra unit to this sublayer , for example,

`{self-attention -> feed-foward -> **LSTM**}`

Thanks

**Comment by BramVanroy** [comment]
Anything is possible, if you want to! But it's not straightforward, I think. You can have a look at `BertLayer` where I would assume that you make your changes.

https://github.com/huggingface/transformers/blob/dfe012ad9d6b6f0c9d30bc508b9f1e4c42280c07/src/transformers/modeling_bert.py#L365-L373
