### ISSUE TITLE
loss reduction for `Llama2ForCausalLM.forward`

### ISSUE THREAD

**Issue by ain-soph** [huggingface/transformers#25303]
### Feature request

In `forward` method, it outputs `loss` when `labels` are provided. But the `loss` shape is always `(1,)` because `reduction='mean'` in CrossEntropy. I wonder if I could pass `reduction='none'` and get a `(batch_size,)` shaped loss tensor.

https://github.com/huggingface/transformers/blob/641adca55832ed9c5648f54dcd8926d67d3511db/src/transformers/models/llama/modeling_llama.py#L837

### Motivation

I'm using this loss for reward-based learning.

### Your contribution

I could make a PR if needed.

**Comment by ydshieh** [comment]
Hi @ain-soph 

This is not supported. But you can `not to pass labels` to the `model forward`, but compute the loss in you own code 🤗 .

**Comment by ain-soph** [comment]
@ydshieh Thanks for your reply. Yeah, so my current workaround is to copy the implementation of `LlamaForCausalLM.forward` and calculate in my own, and it works.

Feel free close the issue if maintainers think it's not appropriate to pass `reduction` argument to `forward`.

**Comment by ydshieh** [comment]
Glad it works!
