### ISSUE TITLE
SentencePiece Error with AlbertTokenizer using google pretrained chinese model

### ISSUE THREAD

**Issue by ubuntu733** [huggingface/transformers#2530]
## 🐛 Bug

Model I am using albert:

Language I am using the model on , Chinese:

The problem arise when using:
* [ ] the official example scripts: (give details)
`AlbertTokenizer.from_pretrained(vocab)`

It shows:

> Traceback (most recent call last):
  File "/home/shenchengen/venv/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 438, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/shenchengen/venv/lib/python3.6/site-packages/transformers/tokenization_albert.py", line 90, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/shenchengen/venv/lib/python3.6/site-packages/sentencepiece.py", line 118, in Load
    return _sentencepiece.SentencePieceProcessor_Load(self, filename)
RuntimeError: Internal: /sentencepiece/src/sentencepiece_processor.cc(73) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
sentencepiece_processor.cc(558) LOG(ERROR) /sentencepiece/src/sentencepiece_processor.cc(124) [model_] Model is not initialized.
Returns default value 0
sentencepiece_processor.cc(558) LOG(ERROR) /sentencepiece/src/sentencepiece_processor.cc(124) [model_] Model is not initialized.
Returns default value 0

**It seems origin google chinese pretrained model do not use sentence piece,but word piece, so the pretrained model has no sentence piece model but has vocab_chinese.txt** [albert-issues](https://github.com/google-research/ALBERT/issues/58)

### Expected behavior:
   AlbertTokenizer support word piece method

**Comment by LysandreJik** [comment]
Indeed, this implementation of ALBERT only supports SentencePiece as its tokenizer.
