### ISSUE TITLE
contrastive_search is slow

### ISSUE THREAD

**Issue by insist93** [huggingface/transformers#25329]
### Feature request

I found `contrastive_search `to be much slower than top p sampling, about 2x, more significantly in the case of large language models .I guess the reason is that `torch.stack` and `torch.cat` are called multiple times in the method. 

Is there any way to optimize?

### Motivation

accelerate `contrastive_search` 

### Your contribution

😀

**Comment by amyeroberts** [comment]
cc @gante

**Comment by gante** [comment]
Hi @insist93 👋 

Contrastive search is more elaborate than normal sampling-based strategies. Its execution time is known to grow quickly with `top_k` -- try setting a lower value if execution speed is important on your end. The tips in [this guide](https://huggingface.co/docs/transformers/main/en/perf_infer_gpu_one) may also help.

As for speeding up the method, we are short on bandwidth, so it is very low on our priorities. We're happy to include PRs, if you find a way to speed it up! :)

**Comment by insist93** [comment]
Thank~ i will try it😀
