### ISSUE TITLE
Explanation of the default "auto" values for DeepSpeed stage 3?

### ISSUE THREAD

**Issue by garrett361** [huggingface/transformers#25322]
Hi, I would like to know how the default values of the various [default DeepSpeed stage 3 parameters](https://huggingface.co/docs/transformers/main_classes/deepspeed?_sm_vck=D7sD5KLsJ4kfrtW4NKbQJqJWqH4bkFR7JkHK7fQtHk65Kst1nq7r#zero3-config) were determined when using `"auto"` fields. They seem to work quite well, but I can't find any documentation of their origins.

What experiments or computations were done to land on the `reduce_bucket_size`, `stage3_prefetch_bucket_size `, and `stage3_param_persistence_threshold ` formulas below?  

Maybe @stas00 ? I see that you have written most of this code. Thank you in advance!

https://github.com/huggingface/transformers/blob/fdd81aea12f06e24ab5cf5ba3c7316df3ab1a779/src/transformers/deepspeed.py#L208-L212

**Comment by amyeroberts** [comment]
Hi, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by garrett361** [comment]
Ah, thank you! Will ask there, I wasn't aware of the forums.

**Comment by stas00** [comment]
@garrett361,

- The only real magical `auto` configs are documented here: https://huggingface.co/docs/transformers/main/en/main_classes/deepspeed#zero3-config - the document explains why those values were chosen and the know how came via oral recommendation from deepspeed developers.
- The rest `auto` values are just there to pass through `TrainingArguments` so that they match on both sides.

**Comment by garrett361** [comment]
Thanks @stas00 , please ignore the similar thread I started in the forums.

> the know how came via oral recommendations from Deepspeed developers

As I feared. Appreciate the confirmation, though.

**Comment by stas00** [comment]
Please don't hesitate to file an Issue with Deepspeed to ask for documenting such essential nuances in the Deepspeed core documentation. I'm pretty sure there are other such tune up nuances that I don't think are documented anywhere on their website.
