### ISSUE TITLE
Example to build composite MusicgenForConditionalGeneration does not work

### ISSUE THREAD

**Issue by osanseviero** [huggingface/transformers#25338]
### System Info

Last transformers version

### Who can help?

@sanchit-gandhi @Vaibhavs10 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Doc from https://huggingface.co/docs/transformers/main/en/model_doc/musicgen#model-structure

Code snippet

```
from transformers import AutoConfig, AutoModelForTextEncoding, AutoModel, MusicgenForCausalLM, MusicgenForConditionalGeneration

text_encoder = AutoModelForTextEncoding.from_pretrained("t5-base")
audio_encoder = AutoModel.from_pretrained("facebook/encodec_32khz")
decoder_config = AutoConfig.from_pretrained("facebook/musicgen-small").decoder
decoder = MusicgenForCausalLM.from_pretrained("facebook/musicgen-small", **decoder_config)
```

### Expected behavior

.

**Comment by ydshieh** [comment]
Hi @osanseviero 

Thank you for opening the issue 🤗 

This is probably just a doc issue: change `decoder_config` to a dictionary works then (use `to_dict` method).

 @sanchit-gandhi @va Could you take a look too and update the doc if it's the correct way? Thanks.

**Comment by ydshieh** [comment]
Well, it's not va, it @Vaibhavs10

**Comment by osanseviero** [comment]
Friendly ping here

**Comment by sanchit-gandhi** [comment]
Yep think we can just remove what's not required from the docs for now - until we have fine-tuning support these are extremely rare operations.
