### ISSUE TITLE
Issues with SpeechT5ForTextToSpeech docs

### ISSUE THREAD

**Issue by osanseviero** [huggingface/transformers#25335]
### System Info

N/A https://huggingface.co/docs/transformers/main/model_doc/speecht5#transformers.SpeechT5ForTextToSpeech

### Who can help?

@sanchit-gandhi @vaibh

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://huggingface.co/docs/transformers/main/model_doc/speecht5#transformers.SpeechT5ForTextToSpeech

The code example does not work. In particular, `model.generate` errors out with

```
TypeError: The current model class (SpeechT5ForTextToSpeech) is not compatible with `.generate()`, as it doesn't have a language model head. Please use one of the following classes instead: {'SpeechT5ForSpeechToText'}
```

The correct way to run inference would be using `model.generate_speech` instead, but `generate_speech` does not show up in the docs.

### Expected behavior

-

**Comment by ylacombe** [comment]
Hi @osanseviero,
Thanks for raising this issue, would you have more information on how to reproduct this issue, notably regarding the transformers version ?
Many thanks,
Yoach
