### ISSUE TITLE
Time Series Transformers for Classification

### ISSUE THREAD

**Issue by borhenryk** [huggingface/transformers#25331]
### Feature request

Is it planed to introduce Time Series Transformers for Classification at some point?

### Motivation

Time Series Transformers are already introduced 

### Your contribution

I could contribute models

**Comment by NielsRogge** [comment]
cc @kashif

**Comment by kashif** [comment]
thanks @borhenryk I have a PR for that currently underway here: https://github.com/huggingface/transformers/pull/24803 

do you have some sample/open classification time series datasets in mind you can point me to?

**Comment by borhenryk** [comment]
sure I am working on Healthcare applications where there are many use-cases for TS classification but I think we could start wit an Human Activity Recognition Problem with this data https://archive.ics.uci.edu/dataset/240/human+activity+recognition+using+smartphones

Also happy to support with the PR wherever you need help @kashif

**Comment by kashif** [comment]
awesome @borhenryk I will add this dataset to the huggingface datasets if the license allows it and then coordinate with you  the potential `TimeSeriesForClassification` model's output head

**Comment by kashif** [comment]
not stale

**Comment by kashif** [comment]
@borhenryk  we have a classification model in #25927

**Comment by kashif** [comment]
thanks! will ping you once it's merged!

**Comment by NielsRogge** [comment]
This is now supported with models like PatchTST: https://huggingface.co/docs/transformers/main/en/model_doc/patchtst#transformers.PatchTSTForClassification.
