### ISSUE TITLE
Add image-to-image pipeline

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#25349]
### Feature request

Would be great to add an `image-to-image` pipeline, to handle tasks like image super resolution.

We do support Swin2SR in the library for this purpose: https://huggingface.co/docs/transformers/main/model_doc/swin2sr#transformers.Swin2SRForImageSuperResolution

This can be implemented similar to [other pipelines](https://github.com/huggingface/transformers/tree/main/src/transformers/pipelines). For an example PR that added a pipeline, see https://github.com/huggingface/transformers/pull/11598.

### Motivation

Would be great to do image-to-image tasks in 2 lines of code.

### Your contribution

I can help in assisting a contributor (cc @Narsil)

**Comment by NielsRogge** [comment]
Great, feel free to start opening a PR

**Comment by LeviVasconcelos** [comment]
on it!

**Comment by shivam-1701** [comment]
Hi @NielsRogge I would want to work on this.

**Comment by vatsalkachhia** [comment]
Hi, @NielsRogge I want to contribute to this.

**Comment by stanleycai95** [comment]
I'd love to contribute!

**Comment by andrew-vaughan** [comment]
Is this issue resolved?

**Comment by NielsRogge** [comment]
Yes, will close.
