### ISSUE TITLE
⚠ Better warning/ handling for CTC models in ASR pipeline

### ISSUE THREAD

**Issue by Vaibhavs10** [huggingface/transformers#25341]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu118 (False)
- Tensorflow version (GPU?): 2.12.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.7.0 (cpu)
- Jax version: 0.4.13
- JaxLib version: 0.4.13
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@sanchit-gandhi @arth

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Created an independent colab to demostrate the issue: https://github.com/Vaibhavs10/scratchpad/blob/main/transformers_asr_pipeline_inconsistencies.ipynb

The ASR pipeline behaviour should be consistent across `CTC` and `Seq2Seq` models.

### Expected behavior

Either `CTC` models should default to `return_timestamps="word"` when passed with `return_timestamps=True` or we should pass a more intuitive error message.

**Comment by sanchit-gandhi** [comment]
Thanks for flagging and for the clean repro notebook - I'll open a PR to update this today

**Comment by sanchit-gandhi** [comment]
Script to update the configs for word-level timestamps with Whisper:
```python
from transformers import GenerationConfig

model_to_heads = {
    "whisper-tiny.en": [[1, 0], [2, 0], [2, 5], [3, 0], [3, 1], [3, 2], [3, 3], [3, 4]],
    "whisper-base": [[3, 1], [4, 2], [4, 3], [4, 7], [5, 1], [5, 2], [5, 4], [5, 6]],
    "whisper-base.en": [[3, 3], [4, 7], [5, 1], [5, 5], [5, 7]],
    "whisper-small": [[5, 3], [5, 9], [8, 0], [8, 4], [8, 7], [8, 8], [9, 0], [9, 7], [9, 9], [10, 5]],
    "whisper-small.en": [[6, 6], [7, 0], [7, 3], [7, 8], [8, 2], [8, 5], [8, 7], [9, 0], [9, 4], [9, 8], [9, 10], [10, 0], [10, 1], [10, 2], [10, 3], [10, 6], [10, 11], [11, 2], [11, 4]],
    "whisper-medium": [[13, 15], [15, 4], [15, 15], [16, 1], [20, 0], [23, 4]],
    "whisper-medium.en": [[11, 4], [14, 1], [14, 12], [14, 14], [15, 4], [16, 0], [16, 4], [16, 9], [17, 12], [17, 14], [18, 7], [18, 10], [18, 15], [20, 0], [20, 3], [20, 9], [20, 14], [21, 12]],
    "whisper-large": [[9, 19], [11, 2], [11, 4], [11, 17], [22, 7], [22, 11], [22, 17], [23, 2], [23, 15]],
    "whisper-large-v2": [[10, 12], [13, 17], [16, 11], [16, 12], [16, 13], [17, 15], [17, 16], [18, 4], [18, 11], [18, 19], [19, 11], [21, 2], [21, 3], [22, 3], [22, 9], [22, 12], [23, 5], [23, 7], [23, 13], [25, 5], [26, 1], [26, 12], [27, 15]],
}

for model, heads in model_to_heads.items():
    generation_config = GenerationConfig.from_pretrained(f"openai/{model}")
    if getattr(generation_config, "alignment_heads", None) is None:
        generation_config.alignment_heads = heads
        generation_config.push_to_hub(f"openai/{model}", create_pr=True)
```

I've run the script and created the following PRs:
* Tiny: https://huggingface.co/openai/whisper-tiny/discussions/29#64d0c03f9e9ca8123dd25888
* Tiny.en: https://huggingface.co/openai/whisper-tiny.en/discussions/16#64d0c180e7b70e91a273fbb0
* Base: https://huggingface.co/openai/whisper-base/discussions/21#64d0c1812f1f9578a045f06d
* Base.en: https://huggingface.co/openai/whisper-base.en/discussions/12#64d0c1829e9ca8123dd2802e
* Small: https://huggingface.co/openai/whisper-small/discussions/29#64d0c183132efbe2dcec5126
* Small.en: https://huggingface.co/openai/whisper-small.en/discussions/11#64d0c1844dfd5df70741a372
* Medium: https://huggingface.co/openai/whisper-medium/discussions/20#64d0c18586e19d5db199ce0c
* Medium.en: https://huggingface.co/openai/whisper-medium.en/discussions/10#64d0c186a2e7f9ff6115c6d5
* Large: https://huggingface.co/openai/whisper-large/discussions/35#64d0c1870b71aea8be849a6a
* Lage-v2: https://huggingface.co/openai/whisper-large-v2/discussions/55#64d0c188bc6c9c8bc056fca0
