### ISSUE TITLE
DistilBERT accuracies on the glue test set.

### ISSUE THREAD

**Issue by smr97** [huggingface/transformers#2534]
## ❓ Questions & Help

I need to compare my research against distilBERT as a baseline for a paper in progress. I went through your publication and found that you don't report accuracies on the glue test set and instead on the dev set. TINY BERT publication by huawei tries to reproduce your work, but the numbers are lower.

I would really appreciate some help regarding this. As far as i understand, i need to distill the student with the entire Wikipedia + bookcorpus? Is there any way to skip this step (load a model that you might have)?

Alternatively, if you have the latest submission on glue, it would really help to know the numbers.

Thanks!

**Comment by tigert1998** [comment]
I want the numbers too.

**Comment by LysandreJik** [comment]
You can check the model card for the evaluation results: https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english
