### ISSUE TITLE
Universal Sentence Encoder

### ISSUE THREAD

**Issue by rdisipio** [huggingface/transformers#2536]
# 🌟New model addition

## Model description

Encoder of greater-than-word length text trained on a variety of data.

## Open Source status

* [ ] the model implementation is available: see paper https://arxiv.org/abs/1803.11175

* [ ] the model weights are available: available from tfhub: https://tfhub.dev/google/universal-sentence-encoder/4
* [ ] who are the authors: Google

## Additional context

Standard for sentence embedding, but would like to compare to other methods without having to rely on Tensorflow hub.

**Comment by adai183** [comment]
+1 !!
At reply.ai we have been using USE a lot for Semantic Retrieval. What most impressed us was the Q&A dual encoder model. Works better than anything I know in case you need semantic similarity between a query and contexts.

**Comment by Peter-Devine** [comment]
Bump. I would appreciate this, as it would be handy to have a model geared toward semantic similarity rather than auto-encoding/ auto-regression, as all of the other default models are.
Thanks!

**Comment by andbloch** [comment]
+1

**Comment by setu4993** [comment]
This might be a more appropriate model to port: https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3

The model in the OP was updated with the one linked above, alongwith addition of 15 languages.

**Comment by fonhorst** [comment]
+1.

**Comment by MiroFurtado** [comment]
+1 or https://ai.googleblog.com/2020/08/language-agnostic-bert-sentence.html

**Comment by setu4993** [comment]
I started working on this independently [here](https://github.com/setu4993/convert-use-tf-pt). Would be great to get some help from anyone interested to get it done faster.

**Comment by setu4993** [comment]
> +1 or https://ai.googleblog.com/2020/08/language-agnostic-bert-sentence.html

@MiroFurtado : I ported and published the LaBSE model to the HF model hub here: https://huggingface.co/setu4993/LaBSE

**Comment by ghlai9665** [comment]
+1

**Comment by sgaseretto** [comment]
Are there any advances on this?

**Comment by LysandreJik** [comment]
Did you try using @setu4993's model shared above?

**Comment by aymane-eljerari** [comment]
Are we getting it on hugging face?
