### ISSUE TITLE
IndexError: tensors, used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by slatter666** [huggingface/transformers#25365]
### System Info

- `transformers` version: 4.30.2
- Platform: macOS-13.4.1-arm64-arm-64bit
- Python version: 3.8.11
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 1.12.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Reproduction

I write an encoder-decoder model and try to use beam search, see I just simply run the generate function `mymodel.generate(torch.tensor([[4,5,6,7]]), num_beams=2, max_new_tokens=10)`, and I get this error. And I check the source code, in https://github.com/huggingface/transformers/blob/d4bd33cc/src/transformers/generation/utils.py#L721C1-L745C39, note that in line 738 `model_kwargs = _expand_dict_for_generation(model_kwargs)`, here we have already expand the kwargs.

In line 743 `model_kwargs["encoder_outputs"] = _expand_dict_for_generation(model_kwargs["encoder_outputs"])`, but note that model_kwargs["encoder_outputs"] is a tensor rather than a dict, and since we have expand in line 738, there is no need to expand in line 743

### Expected behavior

I hope that you can fix this bug, or if it's my fault, I'm really sorry about that but please point out my fault

**Comment by sgugger** [comment]
cc @gante

**Comment by slatter666** [comment]
OK，I check the source code of T5, I know the reason, the Encoder Output should return a BaseModelOutputWithPastAndCrossAttentions or a dict, so model_kwargs["encoder_outputs"] should be like a dict, so line 738 makes sense, I'll close the issue. Thanks
