### ISSUE TITLE
Saving with trainer deepspeed zero3 missing config.json and tokenizer files.

### ISSUE THREAD

**Issue by zjjMaiMai** [huggingface/transformers#25368]
trainer will not save tokenizer and config.json when training in deepspeed-**zero3** with `stage3_gather_16bit_weights_on_model_save=False`.

line 2776 will `raise ValueError`, so line 2778 `self._save` never run to save tokenizer and other stuff. is this expected behavior?

https://github.com/huggingface/transformers/blob/d4bd33cc9f11ca48635e54983d75249c78d72e2a/src/transformers/trainer.py#L2771-L2784

_Originally posted by @zjjMaiMai in https://github.com/huggingface/transformers/issues/24728#issuecomment-1669067573_

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello @zjjMaiMai, Thank you for the details. This shouldn't be the behaviour and I'll be working on fixing this.
