### ISSUE TITLE
WavLM paper points to UniSpeech

### ISSUE THREAD

**Issue by gau-nernst** [huggingface/transformers#25367]
### System Info

NA

### Who can help?

@sgugger 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/blob/e42587f596181396e1c4b63660abf0c736b10dae/src/transformers/models/wavlm/modeling_wavlm.py#L1060-L1063

https://arxiv.org/abs/2101.07597 is UniSpeech.

WavLM should be https://arxiv.org/abs/2110.13900 instead.

### Expected behavior

NA

**Comment by sgugger** [comment]
cc @sanchit-gandhi

**Comment by sanchit-gandhi** [comment]
Thanks for reporting @gau-nernst! That's a great spot
