### ISSUE TITLE
Support for diarization in Whisper

### ISSUE THREAD

**Issue by ldenoue** [huggingface/transformers#25376]
### Feature request

In addition to word level timestamps, it would be very useful to get speaker turns like ggml whisper [recently added](https://github.com/ggerganov/whisper.cpp/commit/70e6fcd78b677b5a126010a4ad8e111c274af3f7).

### Motivation

I often transcribe podcasts or meeting recordings, which often involve more than one person speaking, so having the speaker turns would help tremendously.

### Your contribution

I could test the output using Whisper from GGML.

**Comment by sgugger** [comment]
cc @sanchit-gandhi and @xenova FYI

**Comment by sanchit-gandhi** [comment]
Hey @ldenoue - I dug a bit deeper into this and it looks like the directionality for development was actually:

```
HF Whisper -> fine-tune with speaker turns ->  export to tinydiarize -> integrate with Whisper cpp
```

See this README for details: https://github.com/akashmjn/tinydiarize/tree/main#more-info

This means that we just need the author to push the Transformers weights to the Hub. After this, we can call `.from_pretrained` as usual to get the fine-tuned diarized model. There should be minimal code changes to get it working after this

I've opened a request for the weights here: https://github.com/akashmjn/tinydiarize/issues/15
