### ISSUE TITLE
core dumped with Wav2vec2CTC

### ISSUE THREAD

**Issue by ZL92** [huggingface/transformers#25373]
### System Info

transformers==4.31.0
protobuf==3.20.0
datasets==2.14.3

Python version: 3.9.15

### Who can help?

@sanchit-gandhi @Narsil 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi,

This one gives the core dumped error: 
```
import torchaudio
import os
import torch
from datasets import Dataset, load_dataset, Audio, load_metric
from transformers import Wav2Vec2ForCTC
```

While this one works:
```
from transformers import Wav2Vec2ForCTC
import torchaudio
import os
import torch
from datasets import Dataset, load_dataset, Audio, load_metric
```

### Expected behavior

The datasets and sentencepiece packages might be the causes.

**Comment by ydshieh** [comment]
Hi, 

with just 

```python
import torchaudio
import os
import torch
from datasets import Dataset, load_dataset, Audio, load_metric
from transformers import Wav2Vec2ForCTC
```
I can't reproduce. There is no remaining code but just the imports causing the core dump?

**Comment by sanchit-gandhi** [comment]
Likewise - I am unable to reproduce. Could you check you're using the latest versions of all packages? (including torch, torchaudio and datasets)

**Comment by ZL92** [comment]
> Likewise - I am unable to reproduce. Could you check you're using the latest versions of all packages? (including torch, torchaudio and datasets)

Thanks for your reply! 

It was caused by the versions of torch and torchaudio. The problem is solved after upgrading.

**Comment by sanchit-gandhi** [comment]
Perfect! Go well @ZL92 🤗
