### ISSUE TITLE
GPU usage is not constant

### ISSUE THREAD

**Issue by Romainlg29** [huggingface/transformers#25370]
### System Info

- `transformers` version: 4.31.0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.11.3
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When running any code on my GPU, I'm getting spikes on the GPUs:

With two GPUs:
![Screenshot 2023-07-29 161340](https://github.com/huggingface/transformers/assets/31577471/2735351d-6bd9-47d6-80e7-a29a452e6fc3)

With one GPU:
![image](https://github.com/huggingface/transformers/assets/31577471/3017f9f9-2dc5-4cee-87c8-631c64270cfd)

It's not using the full GPU performance.

### Expected behavior

To use 100% of the GPU.

**Comment by sgugger** [comment]
There are multiple factors that could lead to this and since you are not sharing the code you are running, there is very little we can do to help. You should also ask this kind of questions on the [forums](https://discuss.huggingface.co/) where the wider community will be able to help.

**Comment by sgugger** [comment]
There are multiple factors that could lead to this and since you are not sharing the code you are running, there is very little we can do to help. You should also ask this kind of questions on the [forums](https://discuss.huggingface.co/) where the wider community will be able to help.

**Comment by Romainlg29** [comment]
> There are multiple factors that could lead to this and since you are not sharing the code you are running, there is very little we can do to help. You should also ask this kind of questions on the [forums](https://discuss.huggingface.co/) where the wider community will be able to help.

Ok, thank you!
