### ISSUE TITLE
Issue: sacremoses library missing

### ISSUE THREAD

**Issue by Konjarla-Vindya** [huggingface/transformers#25380]
### System Info

Hi @ArthurZucker, we are using AutoTokenizer for importing HuggingFace models into AzureML. This gave an error when importing 'xlm-mlm-en-2048' model. The error says ModuleNotFoundError: No module named 'sacremoses'

Error snip

![image](https://github.com/huggingface/transformers/assets/137049777/591fa265-3ac0-4a6f-95cc-ffaba08da8fe)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

%pip install transformers[torch]
%pip install torchvision
%pip install mlflow
%pip install python-box

from transformers import AutoModel, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("xlm-mlm-en-2048")
model = AutoModel.from_pretrained("xlm-mlm-en-2048")

### Expected behavior

xlm-mlm-en-2048 should work with AutoModel

**Comment by ArthurZucker** [comment]
Hey! could you share the `transformers` version you are using? 
The error should be the following: 
```python 
        try:
            import sacremoses
        except ImportError:
            raise ImportError(
                "You need to install sacremoses to use XLMTokenizer. "
                "See https://pypi.org/project/sacremoses/ for installation."
            )
```
see [here](https://github.com/ArthurZucker/transformers/blob/f4b3c85fa8a351e336d7a02f96cef781550821ff/src/transformers/models/xlm/tokenization_xlm.py#L616-L622) 
Make sure to install sacremoses with `pip install sacremoses`.  If you do no have `tokenizers` and a `tokenizer.json` file exists on the hub, you just need to install `tokenizers` as well

**Comment by Konjarla-Vindya** [comment]
Hi Arthur, 
 
We are using '4.31.0' transformers. 

Is there any possibility of adding this library to Transformer package?

**Comment by sgugger** [comment]
No, Transformers does not even have PyTorch as dependency. We keep the core dependency of the library minimal, we can't have every user required to install all the dependencies of the 200+ models.
