### ISSUE TITLE
Support pushing of NF4 to hub

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/transformers#25391]
What would it take to allow NF4 models from bitsandbytes to be pushed to the hub?

**Comment by sgugger** [comment]
cc @younesbelkada

**Comment by SunMarc** [comment]
Hi @RonanKMcGovern, in order to allow NF4 models to be pushed to the hub, we need to be able to serialize them just like for 8-bit model. Feel free to open an issue on bitsandbytes library to request this feature. In our side, we can't do much.

**Comment by RonanKMcGovern** [comment]
Thanks - submitted an [issue here](https://github.com/TimDettmers/bitsandbytes/issues/695).
