### ISSUE TITLE
RecursionError or "File name too long" error when HF_HOME is set to a relative path

### ISSUE THREAD

**Issue by tamastarjanyi** [huggingface/transformers#25396]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
- Python version: 3.9.5
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sgugger @LysandreJi

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

export HF_HOME=hfh 
or
export HF_HOME=.
Then execute below code

```
from pathlib import Path

from transformers import pipeline

print(Path("/home/test/hub") / "/home/test")  # = /home/test # OK
print(Path("home/test/hub") / "home/test")  # = home/test/hub/home/test # BAD
print(Path("hfh/mydir") / "hfh/")  # = hfh/mydir/hfh # BAD
# See dynamic_module_utils.py -> create_dynamic_module() -> Line 62

pipe = pipeline("text-generation", model="databricks/dolly-v2-3b", trust_remote_code=True)
pipe("Why the sky is blue?")
```

Result with HF_HOME=hfh
```
OSError: [Errno 36] File name too long: 'hfh/modules/hfh/modules/hfh/modules/hfh/modules/hfh/modules/hfh/modules/...
```
Result with HF_HOME=.
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Expected behavior

pipeline should be executed

**Comment by sgugger** [comment]
Thanks for reporting! The PR linked above should fix this!
