### ISSUE TITLE
download "wiki_dpr" dataset but not embeddings

### ISSUE THREAD

**Issue by MaskXman** [huggingface/transformers#25406]
### System Info

变压器-4.31.0
OS:macOS Ventura13.4

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import RagTokenizer, RagRetriever, RagTokenForGeneration
from datasets import load_dataset

dataset = load_dataset("csv", data_files="/Volumes/WD_BLACK/datasets/psgs_w100.tsv", delimiter="\t")
data_tarin = dataset["train"]
data_tarin.save_to_disk("/Volumes/WD_BLACK/datasets/")
print(data_tarin)

tokenizer = RagTokenizer.from_pretrained("facebook/rag-token-nq")
retriever = RagRetriever.from_pretrained("facebook/rag-token-nq", index_name="exact",indexed_dataset=data_tarin)
model = RagTokenForGeneration.from_pretrained("facebook/rag-token-nq", retriever=retriever)

input_dict = tokenizer.prepare_seq2seq_batch("who holds the record in 100m freestyle", return_tensors="pt")

generated = model.generate(input_ids=input_dict["input_ids"])
print(tokenizer.batch_decode(generated, skip_special_tokens=True)[0])

### Expected behavior

我 want to see the correct dataset but not , I get the datasets without "embeddings" col
what should I do so that I can get the embeddings

**Comment by sgugger** [comment]
Please use the forums for such questions, as we keep issues for bugs in the library and feature requests only.
