### ISSUE TITLE
squad convert example to features potential bug

### ISSUE THREAD

**Issue by phuongpm241** [huggingface/transformers#2541]
## ❓ Questions & Help

I used an older version of run_squad.py (and everything else in the example). My dataset contains very long documents (1000-2000 tokens). In the past, convert_example_to_features returns about 913 features per 12 examples. However, after a pull I did last night, the number of features is now 14. Both f1 and exact match drops tremendously because of that. I wonder if there were any changes in the pull I did.

**Comment by LysandreJik** [comment]
The new and old versions of SQuAD should behave exactly the same when building features. Do you think you could provide an example script that replicates this issue, so that I may take a look at it?

**Comment by LysandreJik** [comment]
Possibliy related to #2548

**Comment by phuongpm241** [comment]
I was trying to run `run_squad.py` using this script
```
CUDA_VISIBLE_DEVICES=1 python run_squad.py \
  --model_type bert \
  --model_name_or_path bert-base-cased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file ../clicr_train_squadstyle.1.0.json \
  --predict_file ../clicr_dev_squadstyle.1.0.json \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir ../squad_results/
```

`max_seq_length` was set to be larger than `doc_stride`.

It might be my misunderstanding, but the old version of `examples` was caching a lot of checkpoints and log of the number of iterations over 913 while the new version has 14 iterations per epoch.
