### ISSUE TITLE
Add Grounding DINO 

### ISSUE THREAD

**Issue by EduardoPach** [huggingface/transformers#25423]
### Model description

Grounding DINO is a zero-shot object detection developed by IDEA-Research presented in the paper

[Grounding DINO: Marrying DINO with Grounded Pre-Training for Open-Set Object Detection](https://arxiv.org/abs/2303.05499)

The model uses a Swin transformer and BERT as image and text backbones, respectively,  a feature enhancer and a cross-modality decoder.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Model implementation and weights can be found in their GitHub repo: https://github.com/IDEA-Research/GroundingDINO/tree/main#luggage-checkpoints

**Comment by chiral-carbon** [comment]
Hi @EduardoPach! will you be working on this or is this an issue I can claim and work on?

**Comment by EduardoPach** [comment]
@chiral-carbon Hello, I'm already working on this issue. I'm going to create a pull request and attach here as a WIP

**Comment by EduardoPach** [comment]
#25424

**Comment by EduardoPach** [comment]
Work in Progress in this PR: #25424

**Comment by EduardoPach** [comment]
#self-assign

**Comment by EduardoPach** [comment]
Closed, PR because I'm going to open another one.

**Comment by EduardoPach** [comment]
> Closed, PR due to an issue and I'm going to open another one.

WIP in #25451
