### ISSUE TITLE
Images in "Efficient Inference on a Single GPU" don't load

### ISSUE THREAD

**Issue by osanseviero** [huggingface/transformers#25428]
### System Info

NA

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

In https://huggingface.co/docs/transformers/perf_infer_gpu_one there are some unredered images/gifs

### Expected behavior

-

**Comment by sgugger** [comment]
cc @stevhliu and @MKhalusova

**Comment by MKhalusova** [comment]
I see that the images were not stored in a HF dataset and are likely taken from a third-party blog(?) https://s3.amazonaws.com/moonup/production/uploads/1659861207959-62441d1d9fdefb55a0b7d12c.png
https://s3.amazonaws.com/moonup/production/uploads/1660567469965-62441d1d9fdefb55a0b7d12c.gif
Added initially by @younesbelkada, do you remember what the images were supposed to be?

**Comment by younesbelkada** [comment]
Hi,
The fix is simply to replace `https://s3.amazonaws.com/moonup` by `https://cdn-uploads.huggingface.co` (originally pointed out by @coyotte508 internally), I made #25561 that should fix it for images of transformers repo.
