### ISSUE TITLE
Allow Loading Custom Model Names by Searching for Extension

### ISSUE THREAD

**Issue by VitorHugoOli** [huggingface/transformers#25439]
### Feature request

I propose that in the `from_pretrained`, instead of relying on a set of specific filenames, the loading function should search for the model by its file extension. By doing so, the model names can be more flexible, allowing users to name their custom models as they see fit without the need to conform to a predefined naming scheme.

**Example:**
```txt
Directory: ./input/model/clip/vit-large-patch14
Files: config.json, preprocessor_config.json, vit-large-patch14.safetensors
```
In this case, the model could be loaded by searching for the .safetensors extension rather than expecting a specific filename like model.safetensors.

### Motivation

Currently, in the `from_pretrained` if a folder contains a custom model with a name that doesn't match one of the predefined specified names, it cannot be simply passed to the loading function. Instead, the file name of the model must be manually changed to match one of the allowed names. This behavior can be restrictive, especially when dealing with multiple custom models with varying names.

**Benefit:**
This change would enhance the usability of the library, making it more adaptable to various use-cases and workflows involving custom models. It would also streamline the process of loading custom models, eliminating the need to rename files to match a predetermined pattern.

### Your contribution

I will make changes to the files `utils/modeling_utils.py` and `utils/__init__.py` to enhance the way models are loaded.

1. In utils/__init__.py: I will define a set of predefined extensions that the loading function can recognize. This list of extensions will be used to identify the model files within a given directory.

2. In utils/modeling_utils.py: I will modify the function _add_variant to accept a variant parameter, which can either be the name of the file or a directive to search for the first file with one of the predefined extensions.

**Comment by sgugger** [comment]
In general `from_pretrained` is only intended to work with models saved with `save_pretrained`, not with other models, so this is not a feature we plan to add.
