### ISSUE TITLE
Load T5 model in 8 bit fails

### ISSUE THREAD

**Issue by PansaLegrand** [huggingface/transformers#25443]
### System Info

I use free google Colab with T4 GPU

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am running the colab created for [DeepFloyd](https://huggingface.co/blog/if),

and I cannot load the T5 encoder in 8 bits.

```
from transformers import T5EncoderModel

text_encoder = T5EncoderModel.from_pretrained(
    "DeepFloyd/IF-I-XL-v1.0",
    subfolder="text_encoder", 
    device_map="auto", 
    load_in_8bit=True, 
    variant="8bit"
)
```

The error message is :
```
You are loading your model in 8bit or 4bit but no linear modules were found in your model. Please double check your model architecture, or submit an issue on github if you think this is a bug.

RuntimeError                              Traceback (most recent call last)
[<ipython-input-66-186cdabda356>](https://localhost:8080/#) in <cell line: 3>()
      1 from transformers import T5EncoderModel
      2 
----> 3 text_encoder = T5EncoderModel.from_pretrained(
      4     "DeepFloyd/IF-I-XL-v1.0",
      5     subfolder="text_encoder",

4 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/parameter.py](https://localhost:8080/#) in __new__(cls, data, requires_grad)
     34             # For ease of BC maintenance, keep this path for standard Tensor.
     35             # Eventually (tm), we should change the behavior for standard Tensor to match.
---> 36             return torch.Tensor._make_subclass(cls, data, requires_grad)
     37 
     38         # Path for custom tensors: set a flag on the instance to indicate parameter-ness.

RuntimeError: Only Tensors of floating point and complex dtype can require gradients
```

I cannot see where the problem come from.

**Comment by sgugger** [comment]
cc @SunMarc and @younesbelkada

**Comment by leejielong** [comment]
I am facing the same issue as well, anybody found a solution to this?

**Comment by SunMarc** [comment]
Thanks for reporting this issue @leejielong and @PansaLegrand . To solve this, please install the main branch of transformers `pip install git+https://github.com/huggingface/transformers.git`. I was able to reproduce the issue with the latest release v4.31.0 but the issue is solved in the main branch.

**Comment by leejielong** [comment]
Hi @SunMarc, installing transformers from source worked for me too. Thanks!
