### ISSUE TITLE
Batch Inference for Streaming generation strategy for transformer.generate()

### ISSUE THREAD

**Issue by AyushVachaspati** [huggingface/transformers#25470]
### Feature request

Hi,

I am working on implementing a service that receives inference requests form users and sends a stream of responses (Tokens as they are generated). The TextStreamer and TextIteratorStreamer  classes are good options to do that.
https://huggingface.co/docs/transformers/v4.31.0/en/internal/generation_utils#transformers.TextStreamer

The issue is that they only support one inference request at a time, which wastes a lot of GPU resources. Is there some way to run batches of requests using a stream interface, like "BatchTextIteratorStream" or something in that vain. This way the responses can be generated on a batch of requests. The generator would push list of tokens for each batch for each iteration of the model (in context of LLMs producing 1 token at a time) and the user can then process those to service their requests. 

### Motivation

Streaming responses are very useful for large and slow Chat LLMs. These models have large latencies. By batching the requests we can improve token throughout and improve GPU utilization, and also service more requests at the same time. 

### Your contribution

I can help write the Batch Streamer class to implement the functionality, but I'm not too familiar with the internals of the Transformers codebase, so I need someone to point me in the right direction. 
I'm motivated to contribute a substantial amount of time to implement this feature as it would be a great help for my project.

**Comment by AyushVachaspati** [comment]
I found that I can Inherit the BaseStreamer class and implement my own functionality for my personal use case. But the general functionality might still be useful for the community.

**Comment by sgugger** [comment]
cc @gante

**Comment by gante** [comment]
@AyushVachaspati Thank you for opening the issue 👍 

We want to add it eventually, but we are prioritizing a structural `generate` refactor before we go forward with this feature :)

BTW, since you're serving generation requests, have you looked at our [text-generation-inference](https://github.com/huggingface/text-generation-inference) server-grade library?

**Comment by ddl-avanitanna** [comment]
@AyushVachaspati @gante Has this issue gained any traction yet? Also interested in a streaming solution for batched inference!
