### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by Geremia** [huggingface/transformers#25475]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.32.0.dev0
- Platform: Linux-6.1.42-x86_64-AMD_Ryzen_Threadripper_2990WX_32-Core_Processor-with-glibc2.37
- Python version: 3.9.17
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: 0.21.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0.dev20230812+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```bash
$ ct2-transformers-converter 
free(): invalid pointer
Annullato
```

### Expected behavior

I expect it not to encounter this error.

**Comment by sgugger** [comment]
There is nothing linked to the Transformers library in the reproducer you shared. Are you sure you are opening the issue in the right repo?

**Comment by Geremia** [comment]
@sgugger No, I'm not sure. Is `ct2-transformers-converter` not part of Hugging Face's Transformers? [OpenNMT documentation](https://opennmt.net/CTranslate2/guides/transformers.html#transformers) seemed to imply it was.
