### ISSUE TITLE
Error loading models in 8-bit

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/transformers#25473]
### System Info

There is an error stating that bitsandbytes and accelerate are required (even though the latest versions were already installed.

```
!pip install -q -U git+https://github.com/huggingface/accelerate.git
!pip install -q -U bitsandbytes
!pip install -q -U git+https://github.com/huggingface/transformers.git

model_id = 'meta-llama/Llama-2-7b-chat-hf'

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model = AutoModelForCausalLM.from_pretrained(model_id, device_map="cpu", load_in_8bit=True)
```

I then tried with `!pip install transformers==4.31`

and that resolved the issue. @gante likely related to the prior [issue](https://github.com/huggingface/transformers/pull/25411#event-10057101239)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

See above

### Expected behavior

Model should load.

**Comment by UmarIgan** [comment]
I tried to run this with colab notebook CPU and got same error but once I run it on T4 GPU no errors appeared and worked so I assume you can not use **load_in_8bit=True** on cpu device actually. you can still keep **device_map="cpu"** but  you should have GPU enviroment I guess.

**Comment by sgugger** [comment]
Yes `load_in_8bit` requires using GPUs, not CPUs.

**Comment by RonanKMcGovern** [comment]
Correct, sorry for the false flag @gante
