### ISSUE TITLE
[Trainer API] Mention that the total number of steps per epoch is separate from total number of steps on training run

### ISSUE THREAD

**Issue by suvadityamuk** [huggingface/transformers#25484]
### Feature request

Is there a possibility to maybe mention within the Trainer API that the number of steps mentioned during a `trainer.train()` call is actually the `num_steps_per_epoch * epochs` instead of just `num_steps_per_epoch` and also shift the Epoch note to the front?

![image](https://github.com/huggingface/transformers/assets/70141886/3bc43e57-f9e9-4491-846d-71d2535a690f)

### Motivation

This was very confusing for me as a first-time user of the Trainer API, coming from Keras and it looked like while I had 9688 samples, I had 241700 steps which looked like an error at first (spent 2 hours trying to debug my `datasets` loading :sweat_smile: behind this).

Not sure if it's a major thing, but still something I thought I'd report just in case. 

@sgugger 

### Your contribution

Not sure how I can help, but happy to make the PR if guided.

**Comment by sgugger** [comment]
The progress bar clearly indicates the count of epochs (here we can see 0/25 in your screenshot), I'm not sure what more we can add to make this clearer.
