### ISSUE TITLE
Maskformer is missing dataclass decorator

### ISSUE THREAD

**Issue by cchan-lm** [huggingface/transformers#25504]
### System Info

- `transformers` version: 4.29.2
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
- Python version: 3.9.11
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.2
- PyTorch version (GPU?): 1.13.0+cu116 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@amyeroberts

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hello! We are working on utilities for model investigations.  Our utility attempts to process generic input/output types at the layer level, accounting for `dataclass` objects as well. We ran into an issue with Maskformer where an intermediate output from `MaskFormerPixelDecoderOutput` was not an expected dataclass.

To reproduce, run the below:

```python
from dataclasses import is_dataclass

from transformers.models.maskformer.modeling_maskformer import MaskFormerPixelLevelModuleOutput
from transformers.models.maskformer.modeling_maskformer import MaskFormerPixelDecoderOutput


pixel_level_module = MaskFormerPixelLevelModuleOutput()
assert is_dataclass(pixel_level_module)  # passes

decoder_output = MaskFormerPixelDecoderOutput()
assert is_dataclass(decoder_output)   # will fail
```

Looking at https://github.com/huggingface/transformers/blob/80f29a25a7d2c945c769b41c0fd41e89cf7de31d/src/transformers/models/maskformer/modeling_maskformer.py#L121, the `@dataclass` decorator appears to be missing from `MaskFormerPixelDecoderOutput`. I think currently this is the only `ModelOutput` subclass in `transformers.models` that does not have the decorator.

Thank you in advance for your response!

### Expected behavior

I expect `MaskFormerPixelDecoderOutput` to be a `dataclass` object and `assert is_dataclass(decoder_output)` to pass.

**Comment by amyeroberts** [comment]
@cchan-lm Indeed! Would you like to open a PR to add the decorator? This way you get the github contribution for spotting this :)

**Comment by cchan-lm** [comment]
Sure! I'll do so from my personal account, @rachthree.

To avoid this in the future, what are your thoughts on adding a test to check that all direct subclasses of `ModelOutput` are dataclasses, and/or add a check in `ModelOutput.__init__subclass__`?

**Comment by amyeroberts** [comment]
@cchan-lm Great! Yep - a small test would be great to add alongside.

**Comment by cchan-lm** [comment]
Resolved by https://github.com/huggingface/transformers/pull/25638.
