### ISSUE TITLE
Cfg support

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#25515]
### Feature request

Will add cfg support for LLMs?

### Motivation

for better aligned with prompt by make negative mask

### Your contribution

not

**Comment by sgugger** [comment]
This has already been added, check the main branch.
cc @gante

**Comment by sgugger** [comment]
This has already been added, check the main branch.
cc @gante

**Comment by gante** [comment]
@lucasjinreal this will be part of the next release, which should happen within a month or so. Meanwhile, feel free to install from `main` to access it :) (`pip install --upgrade git+https://github.com/huggingface/transformers.git`)

Check this PR for more information about CFG. Example [here](https://github.com/huggingface/transformers/pull/24654/files#diff-d23b812af8462833ad280d968f3e6e2ee7558bacfc2716cdde44a07bead5e065R1267)

**Comment by lucasjinreal** [comment]
thank u all so much
