### ISSUE TITLE
Tokenizer behavior is not aligned when initialized from vocab_file and from_pretrained.

### ISSUE THREAD

**Issue by KawaiiNotHawaii** [huggingface/transformers#25516]
### System Info

transformers 4.31.0
python 3.10

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Load the llama tokenizer using `transformers.AutoTokenizer.from_pretrained()` and specify the pad_token='<pad>'
2. The pad_token_id returns as 32000 (same as '<unk>'), and the total number of tokens is 32001
3. Load the llama tokenizer by specifying the vocab_file and pad_token='<pad>'
4. The pad_token_id returns as 0 (same as '<unk>'), and the total number of tokens is 32000

### Expected behavior

Two different loading methods should result in the same number of tokens.

**Comment by sgugger** [comment]
cc @ArthurZucker

**Comment by ArthurZucker** [comment]
Hey! Thanks for reporting, this is a duplicate of #23930, and will be fixed by #23909 this week!

**Comment by ArthurZucker** [comment]
Pr is just waiting for a final review!
