### ISSUE TITLE
EnvironmentError OSError: Couldn't reach server

### ISSUE THREAD

**Issue by baggyg** [huggingface/transformers#2551]
## 🐛 Bug

Model I am using (Bert, XLNet....): Bert

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [X] the official example scripts: (give details)
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details)

## To Reproduce

1. Run the run_squad.py scrtipt with standard settings (as per the example page)

Receive the following:
```
File "d:\cudaenv\lib\site-packages\transformers\configuration_utils.py", line 200, in from_pretrained
    raise EnvironmentError(msg)

OSError: Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json' to download pretrained model configuration file.```
```

## Expected behavior

Example Runs as Normal after downloading pre-trained model

## Environment

* OS: Windows 10 x64
* Python version: 3.7.6
* PyTorch version: 1.4
* PyTorch Transformers version (or branch): Latest
* Using GPU ? Yes
* Distributed or parallel setup ? No
* Any other relevant information: Completely clean install / I have internet connection

**Comment by BramVanroy** [comment]
Can you try again? It seems that the server is reachable now.

**Comment by baggyg** [comment]
The server was reachable. I try the same URL in my browser at the time of doing it and it loaded fine. Its just via python / transformers that he problem occurs (I've tried everyday for 3 days now). Could this be something to do with file locks? I get a similar message above. I will try again and post the full error message

**Comment by baggyg** [comment]
Full Error Message:
```
01/17/2020 15:52:28 - WARNING - lib.squad -   Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: True
01/17/2020 15:52:29 - INFO - filelock -   Lock 1473387147720 acquired on TensorflowQA/cache2\4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.bf3b9ea126d8c0001ee8a1e8b92229871d06d36d8808208cc2449280da87785c.lock
01/17/2020 15:52:29 - INFO - transformers.file_utils -   https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json not found in cache or force_download set to True, downloading to D:\GBKaggleChallenges\NLP\TensorflowQA\cache2\tmpjccrll9f
HBox(children=(FloatProgress(value=0.0, description='Downloading', max=313.0, style=ProgressStyle(description_…
01/17/2020 15:52:29 - INFO - transformers.file_utils -   storing https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json in cache at TensorflowQA/cache2\4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.bf3b9ea126d8c0001ee8a1e8b92229871d06d36d8808208cc2449280da87785c
01/17/2020 15:52:29 - INFO - filelock -   Lock 1473387147720 released on TensorflowQA/cache2\4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.bf3b9ea126d8c0001ee8a1e8b92229871d06d36d8808208cc2449280da87785c.lock

Traceback (most recent call last):

  File "d:\cudaenv\lib\site-packages\transformers\configuration_utils.py", line 179, in from_pretrained
    resume_download=resume_download,

  File "d:\cudaenv\lib\site-packages\transformers\file_utils.py", line 212, in cached_path
    user_agent=user_agent,

  File "d:\cudaenv\lib\site-packages\transformers\file_utils.py", line 392, in get_from_cache
    os.rename(temp_file.name, cache_path)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\GBKaggleChallenges\\NLP\\TensorflowQA\\cache2\\tmpjccrll9f' -> 'TensorflowQA/cache2\\4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.bf3b9ea126d8c0001ee8a1e8b92229871d06d36d8808208cc2449280da87785c'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-2-e8fb1981d786>", line 18, in <module>
    squad.main(args)

  File "D:\GBKaggleChallenges\NLP\lib\squad.py", line 743, in main
    cache_dir=args.cache_dir if args.cache_dir else None,

  File "d:\cudaenv\lib\site-packages\transformers\configuration_utils.py", line 200, in from_pretrained
    raise EnvironmentError(msg)

OSError: Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json' to download pretrained model configuration file.```

**Comment by julien-c** [comment]
You're on Windows right? Might there be something wrong with the paths?

**Comment by baggyg** [comment]
> You're on Windows right? Might there be something wrong with the paths?

I can see that the D:\\GBKaggleChallenges\\NLP\\TensorflowQA\\cache2\\tmpjccrll9f
and in fact contains the following, which makes the message even more confusing:

```
{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}
```

**Comment by baggyg** [comment]
I just installed from source and has now gotten passed that particular error so I believe this was something that was fixed within the last week.

**Comment by zhoudoufu** [comment]
@BramVanroy  I have this issue from time to time. I think it's a network timeout issue when the connection is not stable. Unfortunately, it happens.
 It would be nice if this configuration can be cached too, there is no need to download the same config file each time.

**Comment by BramVanroy** [comment]
> @BramVanroy I have this issue from time to time. I think it's a network timeout issue when the connection is not stable. Unfortunately, it happens.
> It would be nice if this configuration can be cached too, there is no need to download the same config file each time.

You can restrict your script to using only local files by using e.g.

```python
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased', local_files_only=True)
```

Note that this will only work if the required files were already downloaded once before.
