### ISSUE TITLE
General Question - Is it possible to do MLM on models like MPT ? If yes, Could you share any resources or relevant codebase related to it?

### ISSUE THREAD

**Issue by Tarun3679** [huggingface/transformers#25528]
### System Info

the current version should be fine.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Is there a way to use AutoModelForCausalLM using MLM.

### Expected behavior

Being able to do MLM pertaining and fine-tuning on the LLMs like MPT.

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for such questions as we keep issues for bugs and feature requests only.
