### ISSUE TITLE
TF Whisper export: Can't use caching?

### ISSUE THREAD

**Issue by DevinTDHa** [huggingface/transformers#25522]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-6.2.6-76060206-generic-x86_64-with-glibc2.17
- Python version: 3.8.17
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1 (False)
- Tensorflow version (GPU?): 2.11.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@sanch @gante @Rocketknight1 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Colab Notebook:

https://colab.research.google.com/drive/1AZRoVs5aK9kM2nKNZ6D98ubJOCGOnQep?usp=sharing

### Expected behavior

Hi!

I am working on deploying a Whisper model and want to export it as a TF saved model and I am having issues with it.

The default export behavior for the saved model will result in a serving that does not separate the encoder and the decoder. I wanted to do this manually, for which I wrote a class (see the colab notebook.).

The custom class separates the decoder and encoder to different servings. Additionally, tensors for caching (`past_key_values`) are also split and ordered by decoder and encoder, so it can be traced.

However, when trying to export the decoder/encoder states for caching, an error occurs. 

```python
        File "python3.8/site-packages/transformers/models/whisper/modeling_tf_whisper.py", line 99, in _make_causal_mask  *
            if past_key_values_length > 0:
    
        TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

I am not sure, but I checked the code and I suspect that this error is due to the cache tensors having different sizes (for encoder/decoder). As we pass the cache tensors as a tuple to the model, there should be multiple sizes for these cache tensors (generated sequence length for the decoder, `1500` for the encoder). I am not sure, how else I could define the servings definition to cover this case.

Thanks in advance!

**Comment by Rocketknight1** [comment]
Good spot - this is actually a bug in the TF-Whisper code! I've opened a PR to fix it at #25523.

**Comment by Rocketknight1** [comment]
@DevinTDHa The fix has been merged! You can try it by installing from main with `pip install --upgrade https://github.com/huggingface/transformers.git`. It fixes the issue for me when I run your demo notebook, but please let me know if you encounter any other issues with TF-Whisper.

Thanks again for the bug report and the clean reproduction notebook!

**Comment by DevinTDHa** [comment]
@Rocketknight1 Thanks for the very quick fix, it works!
