### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers'

### ISSUE THREAD

**Issue by JojoTacoTheCat77** [huggingface/transformers#25556]
Hi all, 
I have installed the transformer package into my virtual env and launched jn from that same virtual env. 
Also, I can see the package installed from running pip freeze. Somehow, I keep getting the ModuleNotFoundError. 
![Screenshot 2023-08-16 at 9 21 21 PM](https://github.com/huggingface/transformers/assets/97198215/7e25f5eb-6d72-49ad-ab95-a23624a5ccca)
Here are all the packages in my virtual env. 
`certifi==2023.7.22
charset-normalizer==3.2.0
filelock==3.12.2
fsspec==2023.6.0
huggingface-hub==0.16.4
idna==3.4
Jinja2==3.1.2
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.1
numpy==1.25.2
packaging==23.1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
safetensors==0.3.2
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
tqdm==4.66.1
transformers==4.31.0
typing_extensions==4.7.1
urllib3==2.0.4
`
Help please!

**Comment by Coldog2333** [comment]
It is a GPT-4 answerable question and it is related to the issue of using Jupyter Notebook instead of transformers library. (Please check your Python interpreter)

**Comment by ArthurZucker** [comment]
You most probably have a discrepency between the python kernel used by the notebook. Nothing we can do on our end
