### ISSUE TITLE
How can i make a PR for autotokenzier to adapt RWKV world

### ISSUE THREAD

**Issue by xiaol** [huggingface/transformers#25576]
### Feature request

Ususally we use own tokenzier with the transformer pipeline, 
like this https://github.com/xiaol/Huggingface-RWKV-World/blob/fca236afd5f2815b0dbe6c7ce3c92e51526e2e14/generate_hf_cfg.py#L79C1-L79C1

So far we have a lot of models using new tokenzier, using pipeline with autotokenizer is critically needed.

How can i add new tokenizer to autotokenzier to make this pipeline smooth and peace. 

Thank you.

### Motivation

1. make everyone use RWKV world smoothly,  and RWKV v5 world is coming.
2. can support huggingface communtiy with this awesome models , make opensource more open.
3. i really don't like llama models always on the top of open llm leardboards.
4. more...

### Your contribution

I made a lots of models based on RWKV 4 world ,https://huggingface.co/xiaol , especially 128k context models.

**Comment by ArthurZucker** [comment]
Hey! This kind of question should be ask on [the forum](https://discuss.huggingface.co/).
However here are two different path: 
- Use the `GPTNeoXTokenizerFast`, see [here](https://huggingface.co/RWKV/rwkv-4-169m-pile/blob/main/tokenizer_config.json)
- Host your tokenizer code on the hub using https://huggingface.co/docs/transformers/custom_models

I don't really know if the tokenizer needed specific steps for conversion cc @sgugger
