### ISSUE TITLE
MIssing parenthesis in call to is_fsdp_enabled?

### ISSUE THREAD

**Issue by marma** [huggingface/transformers#25584]
### System Info

- `transformers` version: 4.32.0.dev0
- Platform: Linux-5.15.0-1028-nvidia-x86_64-with-glibc2.10
- Python version: 3.8.13
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 1.12.0a0+8a1a93a (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

 @ArthurZucker @younesbelkada

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I do not have an example, but rather I found this when debugging another issue. Therefore I do not have a testcase and I am *assuming* that the following is an error.

```
        if (
            (is_deepspeed_zero3_enabled() or is_fsdp_enabled) # <----- HERE
            and torch.distributed.is_initialized()
            and torch.distributed.get_rank() > 0
        ):
            map_location = "meta"
        else:
            map_location = "cpu"
```

### Expected behavior

I expect is_fsdp_enabled is intended to be called rather than tested if None

**Comment by marma** [comment]
PR here https://github.com/huggingface/transformers/pull/25585

**Comment by ArthurZucker** [comment]
Thanks!
