### ISSUE TITLE
when using FSDP, Trainer initializes the optimizer in a wrong order that results in huge waste of GPU memory

### ISSUE THREAD

**Issue by yundai424** [huggingface/transformers#25580]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-5.15.111.1-rolling-lts-linkedin-x86_64-with-glibc2.17
- Python version: 3.10.2
- Huggingface_hub version: 0.14.1
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0a0+gitf998869 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: 8 A100 GPUs
- Using distributed or parallel set-up in script?: Nah just `torchrun`

### Who can help?

trainer: @sgugger

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

**Summary**:
When using FSDP (non-XLA), it'll first create the optimizer using the original full model (without being wrapped into FSDP) [here](https://github.com/huggingface/transformers/blob/v4.31.0/src/transformers/trainer.py#L1647), and then it wraps the model w/ FSDP [here](https://github.com/huggingface/transformers/blob/v4.31.0/src/transformers/trainer.py#L1656)... This results in a **huge waste of GPU memory as there'll be a ton of dangling non-useful optimizer states associated with the model params that don't belong to this shard**; While it should instead first create model and wrap it with FSDP, and initialize optimizer from the FSDP-wrapped model.

I noticed this issue when finetuning llama2-7b model using alpaca dataset. Here is the colab that has the code example for reproduction (The colab can't be executed directly out of the box; Just a way to put all the code into a sharable link): https://colab.research.google.com/drive/1Rj9jDuOjmnZUiEUZwEmLHoL03pGLqv7V#scrollTo=eFfSsG756poB

Another indication is that you'll see a warning thrown by `accelerate`: 
>FSDP Warning: When using FSDP, it is efficient and recommended to call prepare for the model before creating the optimizer

And `accelerate` also notes down this caveat and suggests the same thing https://huggingface.co/docs/accelerate/usage_guides/fsdp

### Expected behavior

It should instead first create model, and then wrap it with FSDP, and finally initialize optimizer from the FSDP-wrapped model. I modified the source code of `transformers` a bit to make it work as expected (don't initialize optimizer until model is wrapped  by `accelerate` with FSDP), I notice a reduction in GPU memory usage by **25Gi** even before any training step begins.

**Comment by muellerzr** [comment]
CC @pacman100

**Comment by pacman100** [comment]
This has already been fixed. Please use the main branch of Transformers.

**Comment by yundai424** [comment]
thanks @pacman100 i found the PR that fixed this. Closing this issue

**Comment by ShengYun-Peng** [comment]
I'm curious which PR fixed this and how was it fixed?
