### ISSUE TITLE
Unable to import tokenizers

### ISSUE THREAD

**Issue by jeffyjeff2893** [huggingface/transformers#25591]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.9.17
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When using python 3.9 on colab I'm unable to import anything from transformers
https://colab.research.google.com/drive/1KYBHdjLphk0L7ZFOPAaw6Xr-v5TuL55u?usp=sharing

### Expected behavior

I expect to be able to import AutoTokenizer

**Comment by ArthurZucker** [comment]
Hey, you manually changed the path using `sys`, if you move your call to `transformers` above your code, it works as expected.

**Comment by jeffyjeff2893** [comment]
After changing the python version I have to append the install location to sys path though or I get no module named transformers
