### ISSUE TITLE
special token ids are different in LlamaTokenizerFast

### ISSUE THREAD

**Issue by x54-729** [huggingface/transformers#25611]
Recently we are working on a model based on Llama. When I;m trying to convert our `tokenizer.model` to `tokenizers`, a problem occurs.
`tokenizer.model`'s vocab is expanded to fit our model:

```python
from transformers import LlamaTokenizer, LlamaTokenizerFast
from sentencepiece import SentencePieceProcessor

f = LlamaTokenizerFast("tokenizer.model")
s = LlamaTokenizer("tokenizer.model")
origin = SentencePieceProcessor("tokenizer.model")

print(f.bos_token_id, f.eos_token_id, f.unk_token_id) # 1, 2, 0
print(s.bos_token_id, s.eos_token_id, s.unk_token_id) # 0, 1, 2
print(origin.bos_id(), origin.eos_id(), origin.unk_id()) # 0, 1, 2
```

This problem leads to different behaviors between `AutoTokenizer` and `LlamaTokenizer`. What may cause this problem?

transformers==4.31.0
tokenizers==0.13.3

**Comment by ArthurZucker** [comment]
Could you try using #23909. I believe the order of token addition is wrong.

**Comment by x54-729** [comment]
> Could you try using #23909. I believe the order of token addition is wrong.

I'm sorry but could you please tell about more details about the solution? I didn't call `add_special_tokens` and just loaded the tokenizer model in this case.

**Comment by ArthurZucker** [comment]
That's the problem, the special tokens are not added to the model by default for the slow tokenizer, while they are for the fast tokenizer.

**Comment by ArthurZucker** [comment]
Closing as #23909 should have fixed it
