### ISSUE TITLE
Model upload and sharing - delete, update, rename....

### ISSUE THREAD

**Issue by miki537** [huggingface/transformers#2561]
## 🚀 Feature

It would be great to have the option of deleting, renaming and adding description to the community models. I saw that there are already some errors in the model names which can probably not be fixed because of this missing functionality. 

We should have something like:
transformers-cli delete
transformers-cli rename
transformers-cli update

## Motivation

I think that without this options the list will get quite messy in the future. Also as mentioned already in other issues(#2281 and #2520) we should be able to add how we trained the model, what dataset was used etc.

**Comment by julien-c** [comment]
Hi @miki537, we already have `transformers-cli s3 rm ____` but it is not super well documented.

I'll improve the documentation on that point. Also `transformers-cli upload` will overwrite existing files with the same name so you can already update files.

S3 doesn't not support moving/renaming files so I'm reluctant to introduce a `rename` (which would need to download the files locally then re-upload with new name – this is what the official aws-cli does)

**Comment by julien-c** [comment]
I'll close this for now, feel free to reopen if it's not well documented enough (or even better, improve it and create a PR :)

**Comment by Jiaxin-Pei** [comment]
Hi Julien, I'm also trying to delete some of my shared models, however, transformers-cli s3 rm ____ seems not working for me. All the models are still there after the command is done

**Comment by julien-c** [comment]
Which model(s) do you intend to delete @Jiaxin-Pei?

**Comment by Jiaxin-Pei** [comment]
@julien-c 
Here are they:
pedropei/question-intimacy-DEMO
pedropei/question-intimacy-demo
pedropei/random-demo

**Comment by julien-c** [comment]
done
