### ISSUE TITLE
Architectures for Dialogue

### ISSUE THREAD

**Issue by lukasfrank** [huggingface/transformers#2562]
## ❓ Questions & Help
Hi 👋
I'm trying to build a dialogue system which should reply based on a history, memory (which is represented as a string) and a confidence if the memory content is correct and should be used. 

Here two examples: 

- history: _Hi_ 
memory: _name: Max_ 
confidence: _0.2_
=> expected output: _Hi, what's your name?_

- history: _Hi_ 
memory: _name: Max_ 
confidence: _0.9_
=> expected output: _Hi Max_

First of all, are there some best practices how to encode non textual input or inject such information into a model? 

I already trained a Bert2Bert model which is not really performing very well. The generated response seems to be not conditioned on the encoder output. 

Are there any recommendations what to try next? 

Many thanks in advance for your hints!

**Comment by julien-c** [comment]
Did you check out [DialoGPT](https://huggingface.co/microsoft/DialoGPT-large) by @dreasysnail?
