### ISSUE TITLE
self.pad_token detect should be is None rather than "not self.pad_token"

### ISSUE THREAD

**Issue by aohan237** [huggingface/transformers#25625]
https://github.com/huggingface/transformers/blob/2f8acfea1ca11fe3479fb379ccbded516d0cff57/src/transformers/tokenization_utils_base.py#L2506C71-L2506C71

**Comment by ydshieh** [comment]
Thanks! I agree.

@ArthurZucker If you agree, I can open a PR to update this tiny place.

**Comment by ArthurZucker** [comment]
Sure!
