### ISSUE TITLE
Bug: dataclasses.FrozenInstanceError: cannot assign to field generation_config

### ISSUE THREAD

**Issue by vasuems** [huggingface/transformers#25648]
### System Info

Hi @julien-c 

I am getting error dataclasses.FrozenInstanceError: cannot assign to field generation_config.

Transformer Version: Latest. Build from source.
Cuda: 11.5
Python: 3.10

Execute the script /scripts/finetune_llama2_guanaco_7b.sh using qlora repository. I am getting the below error.

qlora.py", line 841, in <module>
    train()
  qlora.py", line 694, in train
    training_args.generation_config = transformers.GenerationConfig(**vars(generation_args))
  File "qlora/.venv/lib/python3.10/site-packages/transformers/training_args.py", line 1714, in __setattr__
    raise FrozenInstanceError(f"cannot assign to field {name}")
dataclasses.FrozenInstanceError: cannot assign to field generatio

Can you give pls suggest me a solution to fix this issue? 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Clone qlora repo https://github.com/artidoro/qlora.git.

Execute the script under scripts folder: finetune_llama2_guanaco_7b.sh. 

### Expected behavior

the script should train the default inbuilt model. But the script throws the above error.

**Comment by sgugger** [comment]
You should report the issue on that repo. It is not possible to change the training arguments once instantiated, so the script you are using needs fixing :-)

**Comment by vasuems** [comment]
Thanks.

**Comment by vasuems** [comment]
Closing the issue.
