### ISSUE TITLE
Eval Accumulation Steps Silently Fails w/ Accelerate >= 0.20.3?

### ISSUE THREAD

**Issue by sam-scale** [huggingface/transformers#25641]
### System Info

```
Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.31.0
- Platform: Linux-5.15.0-1026-aws-x86_64-with-glibc2.10
- Python version: 3.8.17
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

* saw that nothing was getting offloaded to GPU here: https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L3196
* Needed `self.accelerator.sync_gradients` to be `True`
* It's set at this line: https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L1863-L1866
Requires accelerate <= 0.20.3

### Expected behavior

Allow `eval_accumulation_steps` to actually do something even if `accelerate > 0.20.3`

**Comment by sam-scale** [comment]
@muellerzr just so I know, is there any estimate on this issue?

**Comment by sam-scale** [comment]
@muellerzr sent out a PR to fix here: https://github.com/huggingface/transformers/pull/26060

**Comment by LysandreJik** [comment]
I believe this was closed by https://github.com/huggingface/transformers/pull/26060

Closing this!
