### ISSUE TITLE
Optionally convert output of FeatureExtraction pipeline to list

### ISSUE THREAD

**Issue by lambdaofgod** [huggingface/transformers#2565]
What is the purpose of .tolist in FeatureExtraction pipeline?
Why is it called? Is this because of some kind of compatibility issue?

If someone needs to use __call__ a lot, it only slows it down. I've tried subclassing FeatureExtractionPipeline, but it's very ugly since then I can't just use it with pipelines.pipeline.

**Comment by mfuntowicz** [comment]
Hi @lambdaofgod,

.tolist() call is there as Python's lists are more compatible with CSV/JSON serialisation than numpy array.

Did you have a chance to get number of how actually slower it is ? If the difference is non negligible then we might have a look to optimise .tolist() only when serialising through JSON/CSV
