### ISSUE TITLE
Llama2 vocabulary duplicates

### ISSUE THREAD

**Issue by don-tpanic** [huggingface/transformers#25663]
### System Info

- `transformers` version: 4.29.2
- Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
- Python version: 3.11.3
- Huggingface_hub version: 0.16.4
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: GTX 3090ti
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```import transformers

llm = 'meta-llama/Llama-2-7b-chat-hf'

tokenizer = transformers.AutoTokenizer.from_pretrained(
        llm,
        use_auth_token=True,
    )

print('id 29909:', tokenizer.decode([29909]))
print('id 319:', tokenizer.decode([319]))
```
get output 
```
id 29909: A
id 319: A
```

In fact, it appears the vocab has many duplicates:
```
counter = {}
for id in range(32000):
    counter[tokenizer.decode([id])] = counter.get(tokenizer.decode([id]), 0) + 1
print(len(counter))
```
I get 
```
26519
```

### Expected behavior

I was expecting all ids (32k of them) will map to a unique subword which is not the case in my little example. Did I miss something here? 

Thanks in advance!

**Comment by ArthurZucker** [comment]
You should try using:
```python 
In [4]: tokenizer.convert_ids_to_tokens(29909)
Out[4]: 'A'

In [5]: tokenizer.convert_ids_to_tokens(319)
Out[5]: '▁A'
```
The decode function remove the extra `'▁'`

**Comment by don-tpanic** [comment]
> You should try using:
> 
> ```python
> In [4]: tokenizer.convert_ids_to_tokens(29909)
> Out[4]: 'A'
> 
> In [5]: tokenizer.convert_ids_to_tokens(319)
> Out[5]: '▁A'
> ```
> 
> The decode function remove the extra `'▁'`

Thanks for your prompt reply @ArthurZucker!! Can I ask a follow-up question on this?

I also experimented the following but get unexpected results - 
```
token_id_A1 = tokenizer.convert_tokens_to_ids('A')
token_id_A2 = tokenizer.convert_tokens_to_ids('_A')
print('token_id_A1: ', token_id_A1)
print('token_id_A2: ', token_id_A2)
```
While "A" is mapped to 29909, "_A" is mapped to 0 which is unknown token, but shouldn't it be 319?

I also tried 
```
token_id_A1 = tokenizer("A", return_tensors='pt').input_ids
```
from which I get 
```
tensor([[  1, 319]])
```
While 1 is mapped to <s>, however 319 as your example shows should be mapped to _A not A. 

Thanks again I hope my question makes sense!

**Comment by ArthurZucker** [comment]
The reason is because `'_A'` and `'▁A'` are not the same tokens. `_` is the under score (first case) while `'▁'` is the special SPIECE_UNDERLINE token.
