### ISSUE TITLE
Confusing example in Object Detection Task

### ISSUE THREAD

**Issue by govindrai** [huggingface/transformers#25662]
### System Info

python 10, latest datasets/transformers

### Who can help?

@sgugger, @stevhliu and @MKhalusova

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Small nit: In https://github.com/huggingface/transformers/blob/main/docs/source/en/tasks/object_detection.md#load-the-cppe-5-dataset, there is a snippet that translates bboxes onto an image:

```
for i in range(len(annotations["id"])):
    box = annotations["bbox"][i - 1]
    class_idx = annotations["category"][i - 1]
    x, y, w, h = tuple(box)
    draw.rectangle((x, y, x + w, y + h), outline="red", width=1)
    draw.text((x, y), id2label[class_idx], fill="white")
```

### Expected behavior

Wherever the example queries for the index `i - 1`, I believe it should query at index `i`.

The answer does come out to be the same since python arrays work with negative indices, but it makes the example confusing/complex because it's not clear why the approach to get the last element, then the first, second and third approach is used.

**Comment by ydshieh** [comment]
@MKhalusova

Could you take a look 🙏? I see you added (or modified) this block.
