### ISSUE TITLE
Finetuning ALBERT using examples/run_lm_finetuning.py

### ISSUE THREAD

**Issue by jianwolf** [huggingface/transformers#2568]
## 🚀 Feature

The current run_lm_finetuning.py script seems to not have ALBERT added. We should be able to finetune ALBERT in the same way we do to other models in your library.

**Comment by aychang95** [comment]
You're right, ALBERT should work out of the box with the fine tuning script as addressed at #2008 by @thomwolf.  It's not too tough to fine-tune ALBERT with the script, and there should be a PR to add some other language models sometime in the near future

**Comment by jianwolf** [comment]
Thank you!
