### ISSUE TITLE
Mask2Former after 4.32 release use more memory

### ISSUE THREAD

**Issue by Emilon1928** [huggingface/transformers#25709]
### System Info

transfomers 4.32.0
ubuntu 22.04
python 3.9

@amyeroberts 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Run the script in the colab notebook twice (with T4 GPU):
1. with version 4.31.0 (everything should work fine)
2. with version 4.32.0 (OOM in inference)

https://colab.research.google.com/drive/1xq54l9a2AQLIHT5jw63btifbOrvSqzts?usp=sharing

### Expected behavior

GPU memory consumption should be constant between versions

**Comment by ydshieh** [comment]
`CUDA out of memory. Tried to allocate 56.25 GiB`. It looks a lot.

@amyeroberts Could you take a look? I tried the notebook and it shows the issue.
