### ISSUE TITLE
LLama2 tokenizer unexpected behaviors with special tokens

### ISSUE THREAD

**Issue by ShomyLiu** [huggingface/transformers#25716]
### System Info

- `transformers` version: 4.33.0.dev0
- Platform: Linux-3.10.0-1160.83.1.el7.x86_64-x86_64-with-glibc2.35
- Python version: 3.10.6
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0a0+b5021ba (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <yes>
- Using distributed or parallel set-up in script?: <yes>

### Who can help?
@ArthurZucker 

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

With the latest version of transformers:
```
import transformers
tok1 = transformers.AutoTokenizer.from_pretrained("llama2-7b", use_fast=False)
tok2 = transformers.AutoTokenizer.from_pretrained("llama2-7b", use_fast=False, legacy=True)

print(tok1.tokenize("</s>Human is Here"))
# output: ['</s>', 'H', 'uman', '▁is', '▁Here']

print(tok2.tokenize("</s>Human is Here"))
# output  ['</s>', '▁Human', '▁is', '▁Here']

```
It seems that it is wrong with the default setting (legacy = False).

### Expected behavior

The expected behavior is:
 ```
['</s>', '▁Human', '▁is', '▁Here']
```

**Comment by ArthurZucker** [comment]
You expectation is wrong, the output of the slow tokenizer is correct. It's a known bug, as the `fast` fix for special tokens is not there yet.

**Comment by ShomyLiu** [comment]
Thanks for the explanation. It is indeed a large change between different versions.
In transformers==4.31.0, the behavior is also different as follows:
```
In [8]: tok.tokenize("</s>Human")
Out[8]: ['</s>', 'Human']

In [9]: tok("</s>Human")
Out[9]: {'input_ids': [1, 2, 0], 'attention_mask': [1, 1, 1]}
```
Although I have read the PR documents before, it is also confusing about which one is right.
Is it a good choice that uses the legacy=True for stable consideration?

**Comment by ArthurZucker** [comment]
I am sorry for the confusion and for the issues, this was a very nasty bug

**Comment by ShomyLiu** [comment]
Got it. Thanks a lot for your efforts on this confusing bug, and have seen that there are quite several commits about this issue.
I will keep `legacy = True` now and looking forward to your final fix. Thanks again.

**Comment by ArthurZucker** [comment]
Thanks for your valuable feedback! Community issues help us know most of the edge cases that we might have missed

**Comment by ArthurZucker** [comment]
🤗
