### ISSUE TITLE
Trainer.__init__() got an unexpected keyword argument 'model_flops'

### ISSUE THREAD

**Issue by andysingal** [huggingface/transformers#25724]
### System Info

colab notebook

### Who can help?

@ArthurZucker @pacman100 @you

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

During Andrew Ng new course on fine tuning LLM
Dataset: Andyrasika/llama_dataset
they used:
```
training_config = {
    "model": {
        "pretrained_name": model_name,
        "max_length" : 2048
    },
    "datasets": {
        "use_hf": use_hf,
        "path": dataset
    },
    "verbose": True
}

```
```
model_flops = (
  base_model.floating_point_ops(
    {
       "input_ids": torch.zeros(
           (1, training_config["model"]["max_length"])
      )
    }
  )
  * training_args.gradient_accumulation_steps
)

print(base_model)
print("Memory footprint", base_model.get_memory_footprint() / 1e9, "GB")
print("Flops", model_flops / 1e9, "GFLOPs")
```
and further
```
trainer = Trainer(
    model=base_model,
    model_flops=model_flops,
    total_steps=max_steps,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)
```
i get the following error:
```
trainer = Trainer(
    model=base_model,
    model_flops=model_flops,
    total_steps=max_steps,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

```
i have seen model_flops but since these courses are in collabration with huggingface, wanted to check if this something new?
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-69-0c6be6067a75>](https://localhost:8080/#) in <cell line: 1>()
----> 1 trainer = Trainer(
      2     model=base_model,
      3     model_flops=model_flops,
      4     total_steps=max_steps,
      5     args=training_args,

TypeError: Trainer.__init__() got an unexpected keyword argument 'model_flops'
```

### Expected behavior

run normally

**Comment by ydshieh** [comment]
I can't see any `model_flops` argument in the codebase. Is this `Trainer` from `transformers` library?

**Comment by andysingal** [comment]
> I can't see any `model_flops` argument in the codebase. Is this `Trainer` from `transformers` library?

this is part of Andrew Ng course released yesterday: https://learn.deeplearning.ai/finetuning-large-language-models/lesson/6/training-process. 
<img width="1847" alt="Screenshot 2023-08-24 at 7 58 43 PM" src="https://github.com/huggingface/transformers/assets/20493493/0f57c3d4-5acf-4580-badb-fe48462cbfee">
@ydshieh @pacman100 @ArthurZucker

**Comment by ydshieh** [comment]
You should post the question on that course forum. There is no `model_flops` argument in `transformers` codebase.

**Comment by ydshieh** [comment]
They probably want to put `model_flops` in `training_args` and not pass directly to the Trainer's `__init__`. Only they know better their usage.

**Comment by andysingal** [comment]
Thanks for your reply, I already did. I wanted run it by your team to see
if this is something in your pipeline. Advantages of doing this is it
quantizes during training . Anyways, if you find something that’s good
otherwise you can close the ticket.

**Comment by Rainismer** [comment]
How to solve this problem?

**Comment by Hmzkhnswt** [comment]
where is code after the correction???

**Comment by ValMobYKang** [comment]
I got one possible solution from here: https://medium.com/@balci.pelin/llm-finetuning-410e8a2738ef

```python
trainer = Trainer(
    model= model,
    # model_flops=model_flops,
    # total_steps=max_steps,
    args=training_args,
    train_dataset=tokenized_dataset,
    eval_dataset=tokenized_dataset,
)
```
