### ISSUE TITLE
Is RoBERTa's pair of sequences tokenizer correct with double </s>

### ISSUE THREAD

**Issue by keldLundgaard** [huggingface/transformers#2573]
In RoBERTa's build_input_with_special_tokens, the comment says 
 
```    
A RoBERTa sequence has the following format:
single sequence: <s> X </s>
pair of sequences: <s> A </s></s> B </s>
```

I find the double `</s></s>` very peculiar. Can you please verify that it should not be `</s><s>` (as a normal XML tag).

Thank you for the amazing work here.

**Comment by julien-c** [comment]
Yes, this is how RoBERTa was trained.
