### ISSUE TITLE
is RoBERTa-base.json in s3  wrong?

### ISSUE THREAD

**Issue by skyf0cker** [huggingface/transformers#2574]
Q:
when i open the json file downloaded from this url:
`https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-mnli-vocab.json`,
i found there is so many wrong strange code in it,like this:
> {"<s>": 0, "<pad>": 1, "</s>": 2, "<unk>": 3, ".": 4, "Ġthe": 5, ",": 6, "Ġto": 7, "Ġand": 8, "Ġof": 9, "Ġa": 10, "Ġin": 11, "-": 12, "Ġfor": 13, "Ġthat": 14, "Ġon": 15, "Ġis": 16, "âĢ": 17, "'s": 18, "Ġwith": 19, "ĠThe": 20, "Ġwas": 21, "Ġ\"": 22, "Ġat": 23, "Ġit": 24, "Ġas": 25, "Ġsaid": 26, "Ļ": 27, "Ġbe": 28, "s": 29, "Ġby": 30, "Ġfrom": 31, "Ġare": 32, "Ġhave": 33, "Ġhas": 34, ":": 35, "Ġ(": 36, "Ġhe": 37, "ĠI": 38, "Ġhis": 39, "Ġwill": 40, "Ġan": 41, "Ġthis": 42, ")": 43, "ĠâĢ": 44, "Ġnot": 45, "Ŀ": 46, "Ġyou": 47, "ľ": 48, "Ġtheir": 49, "Ġor": 50, "Ġthey": 51, "Ġwe": 52, "Ġbut": 53, "Ġwho": 54, "Ġmore": 55, "Ġhad": 56, "Ġbeen": 57, "Ġwere": 58, "Ġabout": 59, ",\"": 60, "Ġwhich": 61, "Ġup": 62, "Ġits": 63, "Ġcan": 64, "Ġone": 65, "Ġout": 66, "Ġalso": 67, "Ġ$": 68, "Ġher": 69, "Ġall": 70, "Ġafter": 71, ".\"": 72, "/": 73, "Ġwould": 74, "'t": 75, "Ġyear": 76, "Ġwhen": 77, "Ġfirst": 78, "Ġshe": 79, "Ġtwo": 80, "Ġover": 81, "Ġpeople": 82, "ĠA": 83, "Ġour": 84, "ĠIt": 85, "Ġtime": 86, "Ġthan": 87, "Ġinto": 88, "Ġthere": 89, "t": 90, "ĠHe": 91, "Ġnew": 92, "ĠâĢĶ": 93, "Ġlast": 94, "Ġjust": 95, "ĠIn": 96, "Ġother": 97, "Ġso": 98, "Ġwhat": 99, "I": 100, "Ġlike": 101, "a": 102, "Ġsome": 103, "S": 104, "Ã«": 105, "Ġthem": 106, "Ġyears": 107, "'": 108, "Ġdo": 109, "Ġyour": 110, "Ġ-": 111, "Ġ1": 112, "\"": 113, "Ġif": 114, "Ġcould": 115, "?": 116, "Ġno": 117, "i": 118, "m": 119, "Ġget": 120, "ĠU": 121, "Ġnow": 122, "Ġhim": 123, "Ġback": 124, "ĠBut": 125, "ĠâĢĵ": 126, "Ġmy": 127, "Ġ'": 128, "Ġonly": 129, "Ġthree": 130, ";": 131, "Ġ2": 132, "The": 133, "1": 134, "Ġpercent": 135, "Ġagainst": 136, "Ġbefore": 137, ...

**this really make me confused .
hope for your help,and i will appreciate it!**

**Comment by julien-c** [comment]
Yes this file is correct.
