### ISSUE TITLE
`clean_up_tokenization_spaces=False` not working for decoding single token

### ISSUE THREAD

**Issue by devymex** [huggingface/transformers#25758]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: 0.21.0
- Accelerate config:    - compute_environment: LOCAL_MACHINE
    - distributed_type: MULTI_GPU
    - mixed_precision: fp16
    - use_cpu: False
    - num_processes: 8
    - machine_rank: 0
    - num_machines: 1
    - gpu_ids: all
    - rdzv_backend: static
    - same_network: True
    - main_training_function: main
    - downcast_bf16: no
    - tpu_use_cluster: False
    - tpu_use_sudo: False
    - tpu_env: []
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: N

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```py
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('meta-llama/Llama-2-7b-hf', use_fast=False)
tokenizer.decode([29892,1235], skip_special_tokens=False, clean_up_tokenization_spaces=False)
tokenizer.decode([1235], skip_special_tokens=False, clean_up_tokenization_spaces=False)
```

Actual outputs:

```
, let
let
```

### Expected behavior

```
, let
 let
```

The token 1235 is ` let`, notice the second line of the output, there should be a space before the word 'let', but it not.

The option `clean_up_tokenization_spaces=False` not working when single token input.

**Comment by ArthurZucker** [comment]
This is expected, `clean_up_tokenization_spaces` is not related to spaces that are outputed by the model but spaces around `special tokens`. The output is stripped because when you encode you also add a space. If you want a one to one decoding of a token use `tokenizer.convert_ids_to_tokens`
