### ISSUE TITLE
Problem working with single cuda when having multiple gpu

### ISSUE THREAD

**Issue by muratsilahtaroglu** [huggingface/transformers#25757]
### System Info

I have 4 gpu and I am running below code but ı  have `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select) error`.

I solved this problem peft_training_args._n_gpu = 1.  

 I put the model and tokenizer in CUDA 0, why can't I train on one GPU? During the train, other GPUs are active and I get the above error.

```
original_model = AutoModelForSeq2SeqLM.from_pretrained(model_name, torch_dtype=torch.bfloat16,device_map = {"": 0})
tokenizer = AutoTokenizer.from_pretrained(model_name,device= 0)
from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    r=32, # Rank
    lora_alpha=32,
    target_modules=["q", "v"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM # FLAN-T5
)
peft_model = get_peft_model(original_model, 
                            lora_config)
print(print_number_of_trainable_model_parameters(peft_model))

output_dir = f'./peft-dialogue-summary-training-{str(int(time.time()))}'

peft_training_args = TrainingArguments(
    output_dir=output_dir,
    auto_find_batch_size=True,
    learning_rate=1e-3, # Higher learning rate than full fine-tuning.
    num_train_epochs=1,
    logging_steps=1,
    max_steps=1,    
)

peft_trainer = Trainer(
    model=peft_model,
    args=peft_training_args,
    train_dataset=tokenized_datasets["train"],
)
peft_trainer.train()
```

### Who can help?

@arth

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select) error`.

### Expected behavior

Model can be train on single gpu so trainer.py should be updated.

**Comment by ArthurZucker** [comment]
Could you provide the ouptut of `transformers-cli envs`? 
cc @pacman100

**Comment by muratsilahtaroglu** [comment]
Transformers CLI tool: error: invalid choice: 'envs' (choose from 'convert', 'download', 'env', 'run', 'serve', 'login', 'whoami', 'logout', 'repo', 'add-new-model', 'add-new-model-like', 'lfs-enable-largefiles', 'lfs-multipart-upload', 'pt-to-tf')
