### ISSUE TITLE
MNLI benchmark, I see only only eval_accuracy, not seperated to m/mm = matched/mismatched

### ISSUE THREAD

**Issue by ndvbd** [huggingface/transformers#25766]
### System Info

N/A

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

MNLI benchmark, I see only only eval_accuracy, not seperated to m/mm = matched/mismatched

### Expected behavior

MNLI benchmark, I see only only eval_accuracy, not seperated to m/mm = matched/mismatched

**Comment by ArthurZucker** [comment]
I have no Idea what you are talking about

**Comment by ndvbd** [comment]
Hi Arthur, the GLUE, for the MNLI dataset, has *two* metrics of accuracy: match accuracy, and mismatched accuracy. Kindly see here: https://openreview.net/pdf?id=rJ4km2R5t7

Now, when running the tranformer code run_gleu, for the mnli task, it only reports a single 'accuracy'.

**Comment by ArthurZucker** [comment]
We have at least 5 different files called `run_glue`, which are supposed to show examples of how to perform certain tasks, but are not absolute source of truth. If you don't see the metric you want being used, you should be able to adapt the code pretty easily for your needs.

As the doc mentions about the example folder: 
>  It is expected that they won’t work out-of-the box on your specific problem and that you will be required to change a few lines of code to adapt them to your needs. To help you with that, most of the examples fully expose the preprocessing of the data. This way, you can easily tweak them.
