### ISSUE TITLE
Local variable 'tokens' referenced before assignment error in tokenization_llama.py

### ISSUE THREAD

**Issue by avnishn** [huggingface/transformers#25769]
### System Info

- `transformers` version: 4.33.0.dev0
- Platform: macOS-12.4-arm64-arm-64bit
- Python version: 3.9.16
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: N/A
- Using distributed or parallel set-up in script?:N/A

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers.models.llama.tokenization_llama import LlamaTokenizer

tokenizer = LlamaTokenizer()

tokenizer.tokenize("")
```

which gives the error:
```
UnboundLocalError: local variable 'tokens' referenced before assignment2346    if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens
```

### Expected behavior

The tokenizer should return an empty list if an empty string is passed, or possibly error with a helpful error message, but I shouldn't get a variable referenced before declaration error.

**Comment by PyroGenesis** [comment]
+1

`LlamaTokenizerFast` seems to be fine with an empty string

```py
tokenizer = LlamaTokenizerFast.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
tokenizer.tokenize("") # returns []
```

but `LlamaTokenizer` returns this error:
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[25], line 2
      1 tokenizer = LlamaTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
----> 2 tokenizer.tokenize("")

File ~\Documents\llama2\lib\site-packages\transformers\models\llama\tokenization_llama.py:214, in LlamaTokenizer.tokenize(self, text, **kwargs)
    211 if len(text) > 0:
    212     tokens = super().tokenize(SPIECE_UNDERLINE + text.replace(SPIECE_UNDERLINE, " "), **kwargs)
--> 214 if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
    215     tokens = tokens[1:]
    216 return tokens

UnboundLocalError: local variable 'tokens' referenced before assignment
```

**Comment by ArthurZucker** [comment]
Hey! Thanks I can indeed reproduce this, and this should just return `[]`.
