### ISSUE TITLE
isses with converting codellama model with convert_llama_weights_to_hf.py

### ISSUE THREAD

**Issue by ilang6** [huggingface/transformers#25770]
### System Info

Hi .
I'm trying to convert the new codellama 7B model with convert_llama_weights_to_hf.py 
but I'm getting the following error:
`ValueError: Trying to set a tensor of shape torch.Size([32016, 4096]) in "weight" (which has shape torch.Size([32000, 4096])), this look incorrect.`
I'm running the script on macos 13.0 (22A380) and python 3.9 with Transformers version 4.32.0.

Thank you in advance. 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

This was the code I ran.
`python src/transformers/models/llama/convert_llama_weights_to_hf.py --input_dir /Volumes/Extreme_SSD/llama2_code/CodeLlama-7b --output_dir /Volumes/Extreme_SSD/llama2_code/CodeLlama-7b/converted --model_size 7B`

### Expected behavior

At the end of the process, I should have the model in a bin format.
With config.json and tokenizer file.

**Comment by ArthurZucker** [comment]
Hey ! This is expected, the conversion script was updated to support code llama see #25740.
Make sure you are running the script on main

**Comment by ilang6** [comment]
Thank you for your help.
I tried the updated script again and everything thing worked just fine.
