### ISSUE TITLE
always occur error:AssertionError

### ISSUE THREAD

**Issue by jiangjiaqi6** [huggingface/transformers#2577]
## ❓ Questions & Help

I put the wiki.train.raw and the wiki.test.raw in /dataset,
then run the command:
python run_lm_finetuning.py     --output_dir=output     --model_type=roberta     --model_name_or_path=roberta-base     --do_train     --train_data_file=/dataset/wiki.train.raw     --do_eval     --eval_data_file=/dataset/wiki.test.raw     --mlm

errors:
Traceback (most recent call last):
  File "run_lm_finetuning.py", line 717, in <module>
    main()
  File "run_lm_finetuning.py", line 662, in main
    train_dataset = load_and_cache_examples(args, tokenizer, evaluate=False)
  File "run_lm_finetuning.py", line 127, in load_and_cache_examples
    block_size=args.block_size,
  File "run_lm_finetuning.py", line 86, in __init__
    assert os.path.isfile(file_path)
AssertionError 

then I find the code in run_lm_finetuning.py, 
I don't know change file_path in def __init__:
def __init__(self, tokenizer, args, file_path="train", block_size=512):
I hope you can help me out.

**Comment by julien-c** [comment]
It seems like the paths to your data files are incorrect.

Are you sure they're not at `./dataset/wiki.train.raw ` (notice the leading `.`)
