### ISSUE TITLE
Lora adapter weights not getting loaded

### ISSUE THREAD

**Issue by jaideep11061982** [huggingface/transformers#25775]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.30.2
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.0 (True)
- Tensorflow version (GPU?): 2.12.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.7.0 (gpu)
- Jax version: 0.4.13
- JaxLib version: 0.4.13
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
mymodel = AutoModelForMultipleChoice.from_pretrained(model_path  ) # original model
mymodel=PeftModel.from_pretrained(mymodel,'/kaggle/input/llm-best/best_ckp1') # best weights
```
`trainable params: 2050 || all params: 435850242 || trainable%: 0.00`

when I do get CV it gets me 
getScore(trainer,test_df_val,tokenized_test_ds_val)

i get No trained results as if not trained..

### Expected behavior

i should get same score as i got during the training followed by inferenec when it ends up with loading the best weights as I enable best load at the end  of training  option

**Comment by ArthurZucker** [comment]
Hey, could you explain your problem properly? We need a full reproducer and traceback to be able to help you.
