### ISSUE TITLE
GPT2TokenizerFast object has no attribute 'with_pre_tokenizer'

### ISSUE THREAD

**Issue by armheb** [huggingface/transformers#2578]
## 🐛 Bug

Model I am using (Bert, XLNet....): GPT2

Language I am using the model on (English, Chinese....): English

The problem arise when using:
tokenizer = GPT2TokenizerFast.from_pretrained('gpt2')

The tasks I am working on is:

* [ ] my own task or dataset:

## To Reproduce

1.tokenizer = GPT2TokenizerFast.from_pretrained('gpt2')
2.
3.

<ipython-input-97-b0a0cde738fe> in <module>
----> 1 tokenizer = GPT2TokenizerFast.from_pretrained('gpt2')

/media/bahram/New Volume/Projects/Python_LM/transformers/tokenization_utils.py in from_pretrained(cls, *inputs, **kwargs)
    307 
    308         """
--> 309         return cls._from_pretrained(*inputs, **kwargs)
    310 
    311     @classmethod

/media/bahram/New Volume/Projects/Python_LM/transformers/tokenization_utils.py in _from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
    459         # Instantiate tokenizer.
    460         try:
--> 461             tokenizer = cls(*init_inputs, **init_kwargs)
    462         except OSError:
    463             raise OSError(

/media/bahram/New Volume/Projects/Python_LM/transformers/tokenization_gpt2.py in __init__(self, vocab_file, merges_file, unk_token, bos_token, eos_token, pad_to_max_length, add_prefix_space, max_length, stride, truncation_strategy, **kwargs)

AttributeError: 'Tokenizer' object has no attribute 'with_pre_tokenizer'

## Expected behavior

AttributeError: 'Tokenizer' object has no attribute 'with_pre_tokenizer'
## Environment

* OS: Ubuntu 18
* Python version: 3.7
* PyTorch version:
* PyTorch Transformers version (or branch):
* Using GPU yes
* Distributed or parallel setup No
* Any other relevant information:

**Comment by LysandreJik** [comment]
Hi, could you specify your versions of `tokenizers` and `transformers`? I believe you're running on an older version of `transformers`, could you install from source: `pip install git+https://github.com/huggingface/transformers` and let me know if it fixes this issue? Thank you.
