### ISSUE TITLE
How to re-tokenize the training set in each epoch?

### ISSUE THREAD

**Issue by tic-top** [huggingface/transformers#25783]
I have a special tokenizer which can tokenize the sentence based on some propability distribution.
For example, 'I like green apple' ->'[I],[like],[green],[apple]'(30%) or '[I],[like],[green apple]' (70%).
Now in the training part, I want the Trainer can retokenize the dataset in each epoch. How can I do so?

**Comment by ArthurZucker** [comment]
Please ask this kind of questions on [the forum ](https://discuss.huggingface.co/)
