### ISSUE TITLE
Symbol Zeros is already exposed as (). Error Help pls 

### ISSUE THREAD

**Issue by ZwChiew** [huggingface/transformers#25781]
### Major Bug while importing Huggingface locally model in VS code

Was trying to implement a simple paraphrasing tool 
but unable to import / download the library Vamsi/T5_Paraphrase_Paws due to this error: 
Symbol Zeros is already exposed as (). 
Was working fine on google colab / anaconda but not on vs code 
All required libraries and dependencies installed 

Boiler code: 
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained(
    "Vamsi/T5_Paraphrase_Paws").to('cuda')

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained(
    "Vamsi/T5_Paraphrase_Paws").to('cuda')

### Expected behavior

Please help me solve this issue, this is a core module of a very important system

**Comment by ArthurZucker** [comment]
Okay, did you install `safetensors` and `sentencepiece`? I cannot reproduce your issue
