### ISSUE TITLE
Inconsistency in encoding user special tokens between LlamaTokenizerFast and LlamaTokenizer

### ISSUE THREAD

**Issue by hzphzp** [huggingface/transformers#25814]
### System Info

tokenizers==0.13.3
transformers==4.32.1

### Who can help?

@ArthurZucker  When encoding user special tokens (e.g., \<img\>), LlamaTokenizerFast adds extra spaces before and after the token, while LlamaTokenizer does not. This inconsistent behavior leads to different results when using the two tokenizers.

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

To reproduce the issue, I used the following code:
```python
from transformers import LlamaTokenizerFast  
from transformers import LlamaTokenizer  
  
fast_tokenizer = LlamaTokenizerFast.from_pretrained("lmsys/vicuna-13b-v1.3", use_fast=True)  
tokenizer = LlamaTokenizer.from_pretrained("lmsys/vicuna-13b-v1.3", use_fast=False)  
  
tokenizer.add_special_tokens({"additional_special_tokens": ['<img0>', '</img0>', '<img_content>']})  
fast_tokenizer.add_special_tokens({"additional_special_tokens": ['<img0>', '</img0>', '<img_content>']})  
  
prompt = "<img0> <img_content> </img0>"  
  
print(tokenizer.tokenize(prompt))  
print(fast_tokenizer.tokenize(prompt))  
print(tokenizer(prompt))  
print(fast_tokenizer(prompt))  
```

The results are as follows:
```
['<img0>', '<img_content>', '</img0>']  
['<img0>', '▁▁', '<img_content>', '▁▁', '</img0>']  
{'input_ids': [1, 32000, 32002, 32001], 'attention_mask': [1, 1, 1, 1]}  
{'input_ids': [1, 32000, 259, 32002, 259, 32001], 'attention_mask': [1, 1, 1, 1, 1, 1]}  
```

### Expected behavior

As you can see, LlamaTokenizerFast adds unnecessary spaces ('▁▁') before and after the <img_content> token, while LlamaTokenizer does not. This results in different input_ids and attention_mask values when using the two tokenizers. But we expect that they output the same.

Waiting for kindly response ... ...

**Comment by ArthurZucker** [comment]
Hey! This is expected, a fix is on its way here: #23909. For now you should make sure the added tokens have `rstrip = True` and `lstrip=True` 😉

**Comment by hzphzp** [comment]
> rstrip

problem solved, thank you!

**Comment by hzphzp** [comment]
problem solved, thank you!
