### ISSUE TITLE
`speed_metrics` may cause ambiguity under multi-nodes scenario

### ISSUE THREAD

**Issue by CokeDong** [huggingface/transformers#25822]
### System Info

- `transformers` version: 4.32.0
- Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.16
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config:    not found
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@patrickvonplaten 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

e.g. any training programs with `torchrun` running with multi-nodes.

```bash
#master nodes
WORLD_SIZE=4  CUDA_VISIBLE_DEVICES=0,1 torchrun --nnodes=2 --node_rank=0 --nproc_per_node=2 --master_port=1234 train.py ...

# slave nodes
WORLD_SIZE=4  CUDA_VISIBLE_DEVICES=2,3 torchrun --nnodes=2 --node_rank=1 --nproc_per_node=2 --master_port=1234 train.py ...
```

### Expected behavior

the speed_metrics logs will got printed twice, which cause ambiguity.
e.g this is one of my testing results

```
#master nodes

{'train_runtime': 318.7822, 'train_samples_per_second': 16.061, 'train_steps_per_second': 0.031, 'train_loss': 1.8525979161262511, 'epoch': 0.1}
# slave nodes
   {'train_runtime': 318.7808, 'train_samples_per_second': 16.061, 'train_steps_per_second': 0.031,  'train_loss': 1.8525979161262511, 'epoch': 0.1}
```

maybe the log is better to be printed **only** by master modes.

**Comment by ydshieh** [comment]
Hi @CokeDong!

Since the output is identical, I would say it's not a big issue :-)

**Comment by amyeroberts** [comment]
cc @muellerzr @pacman100

**Comment by CokeDong** [comment]
> Hi @CokeDong!
> 
> Since the output is identical, I would say it's not a big issue :-)

yes, except 'train_runtime'  is different. btw, we  are planning  integrating  `tokens per seconds` metrics  into the `trainer`, the motivation is that: each example doesnot have the same length(especailly `cutting_off` increase).  so we take `tokens ` into `speed_metrics `, is that a good idea?

**Comment by muellerzr** [comment]
@CokeDong train runtime will be slightly different as it comes from each node, and each one can take slightly longer depending on the connection speed, etc. I don't believe it's actually truly an issue, nor something we can really do anything about. It's a minute difference.

**Comment by CokeDong** [comment]
got that, thx~
