### ISSUE TITLE
Perplexity docs have broken gifs

### ISSUE THREAD

**Issue by hamelsmu** [huggingface/transformers#25836]
See https://huggingface.co/docs/transformers/perplexity

Looks like raw html is showing up

![image](https://github.com/huggingface/transformers/assets/1483922/8fe15d12-5f43-4eb2-8704-a04928c80199)

Also looks like that asset is not at that location. 

cc: @muellerzr

**Comment by ydshieh** [comment]
Thank you so much for reporting, we will take a look 🤗
