### ISSUE TITLE
what's the structure of the model saved after fine-tuning ?

### ISSUE THREAD

**Issue by JiangYanting** [huggingface/transformers#2584]
## ❓ Questions & Help

 Hello ! I'm wondering what is the structure of the model saved after fine-tuning. For example, after the sequence classification fine-tuning , how to show the layers information of newly-formed model ? Is new model's sentence vector different from the original one which is extracted from pre-trained model ?

**Comment by BramVanroy** [comment]
I'm afraid I don't understand your question. The pretrained model is an architecture whose weights have already been trained on some task (typically (M)LM and NSP/SOP). When you finetune the model, the architecture stays exactly the same but the weights are finetuned to best fit your task.

**Comment by JiangYanting** [comment]
@BramVanroy I tried “print(model)”，it showed the information of every layer. Thank you so much!
