### ISSUE TITLE
Attibute Error：‘NoneType’ object has no attribute 'seek' and OSError

### ISSUE THREAD

**Issue by MrChenJianhui** [huggingface/transformers#2585]
My pytorch version is 1.4.0+cpu and tensorflow version is 2.0.0-dev20191002.
/torch/serialization.py,line 289,in_check_seekable
‘NoneType’ object has no attribute 'seek'
You can only torch.load from a file that is seekable.Please pre_load the data into a buffer like io.BytesIO and try to load from it instead.
But how should I do to sovle the quetions?
Another question.
OSError:Unable to load weights from pytorch checkpoint file.If you tried to load a PyTorch model from a TF 2.0 checkpoint,please set from_tf=true.

**Comment by MrChenJianhui** [comment]
python version is 3.7.3

**Comment by LysandreJik** [comment]
Hi, you would need to provide more information than that for us to help you. What code made you run into this error?
