### ISSUE TITLE
PyTorch 1.2 has released API 'torch.nn.Transformer'，so it's better to modify the source code with the official  python API

### ISSUE THREAD

**Issue by daydayfun** [huggingface/transformers#2586]
## Motivation

It's better to Modify modeling_bert.py with official API 'torch.nn.Transformer' of PyTorch 1.2

## Additional context

https://pytorch.org/docs/stable/nn.html?highlight=transformer#torch.nn.Transformer

**Comment by BramVanroy** [comment]
This has been suggested a while back when this was first introduced (we're at 1.4 now). This is possibly impractical to do since it is likely that many people are still on 1.0<=x<1.2. 

Voting to close.
