### ISSUE TITLE
how can i download the model manually?

### ISSUE THREAD

**Issue by shange1996** [huggingface/transformers#2588]
## ❓ Questions & Help

I want to download the model manually because of my network. But now I can only find the download address of bert. Where is the address of all models? Such as XLNET。

**Comment by nauman-chaudhary** [comment]
- xlnet-base-cased : https://s3.amazonaws.com/models.huggingface.co/bert/xlnet-base-cased-config.json
- xlnet-large-cased : https://s3.amazonaws.com/models.huggingface.co/bert/xlnet-large-cased-config.json

**Comment by dsadulla** [comment]
I used [this link ](https://huggingface.co/jplu/tf-xlm-roberta-large#tensorflow-xlm-roberta)to download the tf-xlm-roberta-base. But such information is not available for every model.

As @nauman-chaudhary indicated some are available [here](https://huggingface.co/transformers/_modules/transformers/configuration_xlnet.html#XLNetConfig)..
