### ISSUE TITLE
GPTQ Quantization via `from_pretrained`: why enforcing `fp16`?

### ISSUE THREAD

**Issue by HanGuo97** [huggingface/transformers#25888]
### Feature request

Hi, I noticed in the following line that model has to be in `fp16` format before GPTQ quantization. I'm curious whether this condition can be dropped?
https://github.com/huggingface/transformers/blob/ccb92be23def445f2afdea94c31286f84b89eb5b/src/transformers/modeling_utils.py#L2504

### Motivation

My use case runs into troubles with `fp16` but works with `bf16`, and I noticed that if I simply remove this line and keep `torch_dtype=None` everything runs fine.

### Your contribution

NA

**Comment by amyeroberts** [comment]
cc @younesbelkada

**Comment by younesbelkada** [comment]
Hi ! 
That might be a copypasta from previous bnb integration but not sure, we should probably override it to `torch.float16` only if `torch_dtype=None`, @SunMarc what do you think? Maybe there is something I have overlooked about GPTQ

**Comment by HanGuo97** [comment]
Why override it if `torch_dtype=None`? I think `fp32` runs just fine too -- tried and worked?

**Comment by HanGuo97** [comment]
Understood -- thanks for the explanation!

So just to confirm, there are no correctness issues with using `torch.float32`, it’s just that using `fp16` instead can result in better efficiency for certain workloads?

If that’s the case, would it be more effective to add a warning when `torch_dtype=None` and suggest using `fp16` for better efficiency? Personally, I prefer having fewer overrides, but I’m open to either approach.

**Comment by SunMarc** [comment]
Hi @HanGuo97 , the backend in auto_gptq library always used` torch_dtype = torch.float16` by default and I ran into a couple of issues with `torch.dtype = torch.float32` in the past most probably due to how the kernels were implemented. So this is why i hardcoded to `torch.float16`. But I guess that if it works for you, I will do as you suggested !

**Comment by HanGuo97** [comment]
Interesting, thanks for the clarification!

I briefly looked into the `auto_gptq` library, and I think they have a [different code](https://github.com/PanQiWei/AutoGPTQ/blob/main/auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py#L203) path depending on whether the data is in `fp16` or not.

**Comment by SunMarc** [comment]
Yeah, I must have forgotten to deactivate `use_cuda_fp16` as it is enabled by default ;)

**Comment by HanGuo97** [comment]
Oh yes you are right, I missed this :)

(In hindsight, it's a bit odd they set this to True by default when it clearly depends on the model.)

**Comment by SunMarc** [comment]
Thanks again for looking into that !
