### ISSUE TITLE
Zero classification pipeline issue when using device map

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#25892]
### System Info

Google Colab

- `transformers` version: 4.32.1
- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): 2.12.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.7.2 (gpu)
- Jax version: 0.4.14

### Who can help?

@Narsil 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When using the `device_map` argument in a zero shot pipeline with BERT, I get an error that the model cannot be loaded.

```python
pipeline("zero-shot-classification", model="LoicDL/bert-base-dutch-cased-finetuned-snli", device_map="auto")
```

Error:

> ValueError: Could not load model LoicDL/bert-base-dutch-cased-finetuned-snli with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForSequenceClassification'>, <class 'transformers.models.auto.modeling_tf_auto.TFAutoModelForSequenceClassification'>, <class 'transformers.models.bert.modeling_bert.BertForSequenceClassification'>, <class 'transformers.models.bert.modeling_tf_bert.TFBertForSequenceClassification'>).

I think the issue is that BertForSequenceClassification does not support device_map:

```python
BertForSequenceClassification.from_pretrained("LoicDL/bert-base-dutch-cased-finetuned-snli", device_map="auto")
```

Error:

> ValueError: BertForSequenceClassification does not support `device_map='auto'`. To implement support, the modelclass needs to implement the `_no_split_modules` attribute.

It would be much clearer if this kind of error message is shown in the pipeline. The current error message is very vague.

### Expected behavior

A better error message, like the one that is triggered when trying to load the model for sequence classification.

**Comment by ydshieh** [comment]
Hi @BramVanroy We can definitely provide a more detailed (original) traceback. However, the pipeline tries to load with different possible model class (here `4`) and it's not clear what's the best way to display. Put the traceback given by these 4 tries would be quite long I am afraid.

**Comment by BramVanroy** [comment]
In terms of error traces, it's probably better to have "too much" than "too little". So given a reason for each of the architectures why they failed seems a good thing, not a bad one!

**Comment by ArthurZucker** [comment]
Also the error seems to be the same as #25701, so @ydshieh let's indeed update the error message!

**Comment by ydshieh** [comment]
Sure Sir!
