### ISSUE TITLE
TrainingArguments frozen: leads to issues in Trainer

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#25897]
### System Info

- `transformers` version: 4.32.1
- Platform: Linux-5.14.0-284.25.1.el9_2.x86_64-x86_64-with-glibc2.34
- Python version: 3.11.4
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.22.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)

### Who can help?

@muellerz and @pacman100

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I recently encountered an annoying issue when trying to use the wandb integration for hyperparameter search. When doing so, the trainer will try to reset some of its `args` (TrainingArguments). But it seems that since [recently](https://github.com/huggingface/transformers/commit/ca51499248b986ebf3991848234ef2d8bc81a36a), the choice was made to freeze training arguments.

So this won't work.

```python
from transformers import TrainingArguments
args = TrainingArguments(output_dir="test")
args.output_dir = "test_dir"
args.run_name = "hello"
```

### Expected behavior

As a whole I am not a fan of this commit to freezing a dataclass like that - which is not done in the canonical Python way of using `@dataclass(frozen=True)` so it is hard to spot if you're reading to code. 

If it _must_ stay, then some more changes need to be made throughout the lib. Such as this line

https://github.com/huggingface/transformers/blob/0f08cd205a440d23e6bf924cddd73ff48e09fe35/src/transformers/integrations/integration_utils.py#L758

Should probably be

```python
args = dataclasses.replace(args, run_name=None)
```

(untested)

Currently I do not have the time for a PR but this could be a good first issue for someone who would like to contribute.

**Comment by amyeroberts** [comment]
cc @muellerzr

**Comment by tomaarsen** [comment]
The frozen TrainingArguments also affects third parties facing crashes as they enforce some `TrainingArguments` arguments like `remove_unused_columns`:
https://github.com/tomaarsen/SpanMarkerNER/pull/27
https://github.com/huggingface/trl/pull/676

- Tom Aarsen

**Comment by osanseviero** [comment]
It also seems to be causing some issues in `qlora` https://github.com/artidoro/qlora/issues/253

**Comment by muellerzr** [comment]
You are all very right, this would be a good example of "paved with good intentions." From a design perspective when I was talking with another core contributor, we agreed that the `TrainingArguments` weren't really ever meant to be a mutable object. As a result, we made the move to make it fully immutable. However since many libraries relied on this unintentional usage (as we're now finding out), it now doesn't make sense to keep it. I'll be putting in a revert on this here tomorrow, and if you've already migrated some code you have a few versions before the broken version is fully gone.  Really sorry for the trouble 🙏
