### ISSUE TITLE
Tree add-model-idefics deleted and Google Colab stoped working

### ISSUE THREAD

**Issue by dvelho** [huggingface/transformers#25914]
### System Info

Google Colab: https://github.com/huggingface/notebooks/blob/main/examples/idefics/finetune_image_captioning_peft.ipynb

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the first cell and you will get this error:

Collecting git+https://github.com/huggingface/transformers.git@add-model-idefics
Cloning https://github.com/huggingface/transformers.git (to revision add-model-idefics) to /tmp/pip-req-build-lgss5sp_
Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-lgss5sp_
WARNING: Did not find branch or tag 'add-model-idefics', assuming revision or ref.
Running command git checkout -q add-model-idefics
error: pathspec 'add-model-idefics' did not match any file(s) known to git
error: subprocess-exited-with-error

× git checkout -q add-model-idefics did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q add-model-idefics did not run successfully.
│ exit code: 1
╰─> See above for output.

Also it's not listed here:
https://github.com/huggingface/transformers/branches/active?page=1
https://github.com/huggingface/transformers/tree/add-model-idefics
maybe it was deleted?

### Expected behavior

No error when installing

**Comment by younesbelkada** [comment]
Hi @dvelho 
Thanks for your issue,
please install transformers from source
```bash
pip install git+https://github.com/huggingface/transformers.git
```
And the issue should be resolved

**Comment by younesbelkada** [comment]
Closing as IDEFICS is now part of transformers latest release
