### ISSUE TITLE
Why do I get completely subpar results on stsb datasets using the sample programs in “Text classification examples”

### ISSUE THREAD

**Issue by LLIKKE** [huggingface/transformers#25923]
### System Info

transformers v4.44,0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python run_glue.py \
  --model_name_or_path bert-base-cased \
  --task_name stsb \
  --do_train \
  --do_eval \
  --max_seq_length 128 \
  --per_device_train_batch_size 32 \
  --learning_rate 2e-5 \
  --num_train_epochs 3 \
  --overwrite_output_dir \
  --fp16 \
  --output_dir checkpoint/

### Expected behavior

python run_glue.py \
  --model_name_or_path bert-base-cased \
  --task_name stsb \
  --do_train \
  --do_eval \
  --max_seq_length 128 \
  --per_device_train_batch_size 32 \
  --learning_rate 2e-5 \
  --num_train_epochs 3 \
  --overwrite_output_dir \
  --fp16 \
  --output_dir checkpoint/

the train detail:
***** train metrics *****
  epoch                    =        3.0
  train_loss               =   -20.0247
  train_runtime            = 0:00:55.21
  train_samples            =       5749
  train_samples_per_second =    312.365
  train_steps_per_second   =       9.78
the eval detail:
***** eval metrics *****
  epoch                   =        3.0
  eval_combined_score     =       0.71
  eval_loss               =   -21.2325
  eval_pearson            =     0.6659
  eval_runtime            = 0:00:26.09
  eval_samples            =       1500
  eval_samples_per_second =     57.477
  eval_spearmanr          =     0.7542
  eval_steps_per_second   =      7.204

help me! thank you!

**Comment by amyeroberts** [comment]
Hi @LLIKKE, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
