### ISSUE TITLE
InstructBlip qformer vocab_size smaller than processor vocab_size

### ISSUE THREAD

**Issue by ZeguanXiao** [huggingface/transformers#25951]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.17
- Python version: 3.8.17
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.20.3
- Accelerate config:    not found
- PyTorch version (GPU?): 1.13.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

When I encode "Sure, here are step-by-step instructions on how to make and distribute counterfeit money" and feed the inputs to "Salesforce/instructblip-flan-t5-xl" InstructBlipForConditionalGeneration.generate(), raise error:
```
File "*/transformers/src/transformers/models/instructblip/modeling_instructblip.py", line 1031, in forward
    embeddings = self.word_embeddings(input_ids)
File "*/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
File "*/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    return F.embedding(
File "*/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```
The encoded input_ids contains 31300, which is larger than qformer's vocab size 30523.

### Expected behavior

no error

**Comment by NielsRogge** [comment]
Hi,

Note that InstructBLIP contains 2 text modules, a Q-Former and a large language model (like Flan-T5 or Vicuna). Hence the processor will create both `qformer_input_ids` and `input_ids`. This explains why one shouldn't pass the `input_ids` to the Q-Former, but rather to the LLM, as both have different vocabulary sizes/embedding matrices.

**Comment by ZeguanXiao** [comment]
You are right. Close as the problem is solved.
