### ISSUE TITLE
can not speicfy gpu in trainner

### ISSUE THREAD

**Issue by kimkeithvn** [huggingface/transformers#25979]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-4.15.0-213-generic-x86_64-with-glibc2.27
- Python version: 3.10.11
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: true
- Using distributed or parallel set-up in script?: false

### Who can help?

/

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi I’m trying to fine-tune model with Trainer in transformers,

Well, I want to use a specific number of GPU in my server.
My server has two GPUs and I want to train my model with GPU index 1.

I’ve read the `Trainer` and `Seq2SeqTrainingArguments` documents, and I’ve tried the `CUDA_VISIBLE_DEVICES` env variable already. I found `torch.cuda.current_device()` was correct before defining training_args object by `Seq2SeqTrainingArguments`.

transformers=4.31.0
torch=2.0.0
CUDA Version: 11.8

```python
gpu_idx = 1
os.environ["CUDA_VISIBLE_DEVICES"] = str(gpu_idx)
torch.cuda.set_device(gpu_idx)

# torch.cuda.current_device = 1
...
training_args = Seq2SeqTrainingArguments(output_dir=output_dir, do_train=True, save_strategy='no',
                                         evaluation_strategy='no', logging_strategy='epoch', do_eval=False,
                                         load_best_model_at_end=True,
                                         greater_is_better=True,
                                         num_train_epochs=train_epoch, learning_rate=lr, seed=seed,
                                         per_device_train_batch_size=batch_size, per_device_eval_batch_size=batch_size,
                                         warmup_steps=warmup_steps, weight_decay=0.01, logging_dir=logging_dir,
                                         fp16=True, report_to=['tensorboard'])

# torch.cuda.current_device = 0
```

```shell
nvidia-smi
```
![image](https://github.com/huggingface/transformers/assets/41425845/5f472d30-c6ed-4bd3-8a0e-e005d5c8e188)

I will appreciate your suggestions for this problem. Thanks.

### Expected behavior

I want to specify gpu in my script with `Trainer` and `Seq2SeqTrainingArguments`
```
# torch.cuda.current_device = 1
```

**Comment by amyeroberts** [comment]
cc @muellerzr @pacman100

**Comment by kimkeithvn** [comment]
I use `CUDA_VISIBLE_DEVICES=1 acclerate launch script.py` and it works. Thanks for your advice.
