### ISSUE TITLE
The impact of a quantization config on .num_parameters

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#25978]
### System Info

- `transformers` version: 4.32.1
- Platform: Linux-5.14.0-284.25.1.el9_2.x86_64-x86_64-with-glibc2.34
- Python version: 3.11.4
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)

### Who can help?

@SunMarc and @younesbelkada

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying to understand the impact of a quantization config on the number of parameters better but as discussed internally I am not sure whether what I am experiencing is a bug in `num_parameters` or the expected behavior when using quantization. 

As far as my understanding of quantization goes, it usually implies **changing the precision** of parameters but not specifically reducing the number of parameters. However, when I run the following code, I can see that the number of parameters is cut in half (~6B compared to 13B).

```python
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype="bfloat16",
    bnb_4bit_use_double_quant=True,
)
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-13b-chat-hf", quantization_config=bnb_config, device_map="auto")
model.num_parameters()
# 6671979520
```

### Expected behavior

Is this behavior expected? If so, what is the reason/theory behind it? If not, can the `num_parameters` implementation be fixed?

**Comment by gabinguo** [comment]
I tried with `llama-7b`...
1. w/o 4 bit quantization: (16 bit)
trainable params: 33,554,432 || all params: 6,771,970,048 || trainable%: 0.49548996469513035
2. w/
trainable params: 33,554,432 || all params: 3,533,967,360 || trainable%: 0.9494833591219133

I wonder why changing the precision leads to the decrease of the parameters...

Is this behavior expected?

**Comment by younesbelkada** [comment]
Hi @BramVanroy 
This is indeed a bug and needs fixing! Please see #26132 that explains the fix

**Comment by BramVanroy** [comment]
Cool, thanks! @younesbelkada

**Comment by xyg-coder** [comment]
I think this behavior might be due to the implementation of Linear4bit: https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/nn/modules.py

`requires_grad=False` is always set for weights
