### ISSUE TITLE
Transfer Learning on Text Summarization Model

### ISSUE THREAD

**Issue by imayachita** [huggingface/transformers#2597]
Hi all,
Is there any way to do transfer learning on the Text Summarization model (bertabs-finetuned-cnndm)? I would like to continue training it on my dataset.
The code run_summarization.py only does prediction. Thanks!

**Comment by Sharathmk99** [comment]
@imayachita If your succeeded to use transfer learning on your own data, please update here.

**Comment by sshleifer** [comment]
`examples/summarization/bart/run_bart_sum.py` now exists :)
