### ISSUE TITLE
AttributeError: 'FullyShardedDataParallelPlugin' object has no attribute 'activation_checkpointing'

### ISSUE THREAD

**Issue by scissorstail** [huggingface/transformers#25988]
### System Info

```
Traceback (most recent call last):
  File "/workspace/run/run_llm.py", line 717, in <module>
    main()
  File "/workspace/run/run_llm.py", line 644, in main
    trainer = Trainer(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 342, in __init__
    self.create_accelerator_and_postprocess()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3900, in create_accelerator_and_postprocess
    "activation_checkpointing", fsdp_plugin.activation_checkpointing
AttributeError: 'FullyShardedDataParallelPlugin' object has no attribute 'activation_checkpointing'
```

https://github.com/huggingface/transformers/blob/aea761499f4b1193f2706f471442da6f9df65d65/src/transformers/trainer.py#L3893-L3907

The 'FullyShardedDataParallelPlugin' class in [accelerate](https://github.com/huggingface/accelerate) version **v0.22.0** does not have 'activation_checkpointing'. but the **main** branch does.

**v0.22.0**
https://github.com/huggingface/accelerate/blob/6b3e559926afc4b9a127eb7762fc523ea0ea656a/src/accelerate/utils/dataclasses.py#L778

**main**
https://github.com/huggingface/accelerate/blob/739b135f8367becb67ffaada12fe76e3aa60fefd/src/accelerate/utils/dataclasses.py#L783

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

-

### Expected behavior

-

**Comment by amyeroberts** [comment]
cc @muellerzr @pacman100

**Comment by muellerzr** [comment]
Hi! This has been fixed on main, please install transformers via `pip install git+https://github.com/huggingface/transformers`
