### ISSUE TITLE
Whisper Encoder's positional encodings shouldn't be trainable

### ISSUE THREAD

**Issue by gau-nernst** [huggingface/transformers#25989]
### System Info

Currently Whisper Encoder's positional encodings in HF is an `nn.Embedding`, which makes it trainable.

https://github.com/huggingface/transformers/blob/aea761499f4b1193f2706f471442da6f9df65d65/src/transformers/models/whisper/modeling_whisper.py#L837

In the original implementation, it is fixed to sinusoidal positional encodings, and assigned as a buffer, thus not trainable.

https://github.com/openai/whisper/blob/e8622f9afc4eba139bf796c210f5c01081000472/whisper/model.py#L150

This creates diverging behavior when finetuning Whisper Encoder.

On a separate note, personally I found that OpenAI's weights for Whisper Encoder positional encodings are slightly different from the ones generated by `sinusoids()` function. Thus, loading these positional encodings weights (as buffers) is still necessary to match the original repo.

### Who can help?

@sanchit-gandhi @ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

NA

### Expected behavior

The positional encodings in Whisper Encoder should not be trainable. This can be done by replacing `nn.Embedding` with a buffer. To preserve weight compatibility, it might be necessary to wrap the buffer around a module, so that the state dict key remains the same.

e.g.

```python
self.embed_position = nn.Module()  # empty module
self.embed_position.register_buffer("weight", torch.zeros(self.max_source_positions, embed_dim))  # preserve the key embed_position.weight
```

**Comment by ArthurZucker** [comment]
Agreed that we should default to non trainable. We probably did not have a lot of people training the encoder as this was not notice 🤗 Would you like to open a PR? 
As you mentioned best solution would be to make it backward compatible, keeping the correct naming ! 
Would also say nice catch 👍🏻

**Comment by gau-nernst** [comment]
Which approach do you prefer

1. Keep it as `nn.Embedding`, but set it to `requires_grad=False` in `__init__()` i.e. default to non-trainable. The users can set it to trainable if they want.
2. Change it to buffer (my original suggestion, similar to OpenAI original repo). It can never be trainable this way. Loading positional encodings still works, since buffer is included in state dict.

**Comment by sanchit-gandhi** [comment]
Nice catch @gau-nernst! I would advocate for 1 to keep compatibility with Flax Whisper and TF Whisper which are using embedding layers as well, possibly with different dimension orders though. If we change to buffers, we'll have to check that the cross-platform loading logic works with these new weights
