### ISSUE TITLE
HerBERT missing from list of supported models

### ISSUE THREAD

**Issue by xenova** [huggingface/transformers#26016]
### System Info

n/a

### Who can help?

@stevhliu @MKhalusova 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

HerBERT has a model_doc (https://huggingface.co/docs/transformers/main/en/model_doc/herbert), but is not in the README:
![image](https://github.com/huggingface/transformers/assets/26504141/eb2151c8-feec-40fc-9a34-646a181577d0)

### Expected behavior

It should be in the README :) 
For example:
```
1. **[HerBERT](https://huggingface.co/docs/transformers/model_doc/herbert)** released with the paper [KLEJ: Comprehensive Benchmark for Polish Language Understanding](https://www.aclweb.org/anthology/2020.acl-main.111.pdf) by Piotr Rybak, Robert Mroczkowski, Janusz Tracz, and Ireneusz Gawlik.
```

**Comment by Muskan011** [comment]
I would like to work on this.

**Comment by Muskan011** [comment]
I have fixed this issue but my PR requires review.
