### ISSUE TITLE
CUDA memory does not release with `del model` where .from_pretrained() loading model to multi-devices

### ISSUE THREAD

**Issue by Ricardo-L-C** [huggingface/transformers#26026]
### System Info

- `transformers` version: 4.33.0
- Platform: Linux-5.4.119-1-tlinux4-0010.3-x86_64-with-glibc2.17
- Python version: 3.10.6
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.21.0
- Accelerate config:    - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes, A10 * 2
- Using distributed or parallel set-up in script?: Yes, loading model to 2 cuda devices

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I'm loading [CodeLlama-13b-Instruct-hf](https://huggingface.co/codellama/CodeLlama-13b-Instruct-hf) with 2 * A10 gpus as follows:
```python
import torch
from transformers import AutoModel

model = AutoModel.from_pretrained("./", torch_dtype=torch.float16, device_map="auto").eval()
```
when finished, the cuda Memory-Usage looks like this:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10          On   | 00000000:6F:00.0 Off |                    0 |
|  0%   40C    P0    60W / 150W |  12647MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A10          On   | 00000000:70:00.0 Off |                    0 |
|  0%   40C    P0    63W / 150W |  13569MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
and the `model.hf_device_map` shows the follow:
```python
{'embed_tokens': 0, 'layers.0': 0, 'layers.1': 0, 'layers.2': 0, 'layers.3': 0, 'layers.4': 0, 'layers.5': 0, 'layers.6': 0, 'layers.7': 0, 'layers.8': 0, 'layers.9': 0, 'layers.10': 0, 'layers.11': 0, 'layers.12': 0, 'layers.13': 0, 'layers.14': 0, 'layers.15': 0, 'layers.16': 0, 'layers.17': 0, 'layers.18': 0, 'layers.19': 1, 'layers.20': 1, 'layers.21': 1, 'layers.22': 1, 'layers.23': 1, 'layers.24': 1, 'layers.25': 1, 'layers.26': 1, 'layers.27': 1, 'layers.28': 1, 'layers.29': 1, 'layers.30': 1, 'layers.31': 1, 'layers.32': 1, 'layers.33': 1, 'layers.34': 1, 'layers.35': 1, 'layers.36': 1, 'layers.37': 1, 'layers.38': 1, 'layers.39': 1, 'norm': 1}
```

but when I wanna reload the model or any other model, the cuda memory seems not released with `del model`
```
del model
# reloading
model =  AutoModel.from_pretrained("./", torch_dtype=torch.float16, device_map="auto").eval()
```
the new cuda Memory-Usage is like:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10          On   | 00000000:6F:00.0 Off |                    0 |
|  0%   42C    P0    61W / 150W |   9667MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A10          On   | 00000000:70:00.0 Off |                    0 |
|  0%   43C    P0    64W / 150W |   9253MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
and I found some weights are offloaded to cpu with `model.hf_device_map`:
```python
{'embed_tokens': 0, 'layers.0': 0, 'layers.1': 0, 'layers.2': 0, 'layers.3': 0, 'layers.4': 0, 'layers.5': 0, 'layers.6': 0, 'layers.7': 0, 'layers.8': 0, 'layers.9': 0, 'layers.10': 0, 'layers.11': 0, 'layers.12': 0, 'layers.13': 0, 'layers.14': 1, 'layers.15': 1, 'layers.16': 1, 'layers.17': 1, 'layers.18': 1, 'layers.19': 1, 'layers.20': 1, 'layers.21': 1, 'layers.22': 1, 'layers.23': 1, 'layers.24': 1, 'layers.25': 1, 'layers.26': 1, 'layers.27': 1, 'layers.28': 'cpu', 'layers.29': 'cpu', 'layers.30': 'cpu', 'layers.31': 'cpu', 'layers.32': 'cpu', 'layers.33': 'cpu', 'layers.34': 'cpu', 'layers.35': 'cpu', 'layers.36': 'cpu', 'layers.37': 'cpu', 'layers.38': 'cpu', 'layers.39': 'cpu', 'norm': 'cpu'}
```

If I add `torch.cuda.empty_cache()` between `del model` and reloading, what the `nvidia-smi` shows never changes.

### Expected behavior

while reloading, the whole model should be able to load into gpus as the first time, and `nvidia-smi` after `del model` should show Memory-Usage is decrease greatly.

I think this may occur in models loaded to multi-gpus with `device_map="auto"` or `device_map={a dict}`.
When I load smaller models like [codellama/CodeLlama-7b-hf](https://huggingface.co/codellama/CodeLlama-7b-hf) to single a10 without `device_map="auto"`, it behaves as expected.

**Comment by amyeroberts** [comment]
cc @muellerzr @younesbelkada

**Comment by WilliamChen-luckbob** [comment]
Same issue, when changing model, there is always an OOM exception. 
And I have solved the problem, just do this should help
```
import gc
import torch
del model
gc.collect()
torch.cuda.empty_cache()
```

**Comment by younesbelkada** [comment]
Hi @Ricardo-L-C 
Zach can confirm :D from what I know there is a nice utility method in accelerated called `release_memory`: (zach, correct me if the usage of that method below is wrong)

```python
from accelerate.utils import release_memory

...

model = release_memory(model)
```

**Comment by Ricardo-L-C** [comment]
Thanks @younesbelkada 
I have tried `release_memory` now, but it didn't work as expected, and the cuda Memory-Usage behaved the same as before.
I check the implementation of this function, it shows
```
Releases memory from `objects` by setting them to `None` and calls `gc.collect()` and `torch.cuda.empty_cache()`.
Returned objects should be reassigned to the same variables.
```
And that seems similar to my manual operation.

**Comment by sunyuhan19981208** [comment]
> Thanks @younesbelkada I have tried `release_memory` now, but it didn't work as expected, and the cuda Memory-Usage behaved the same as before. I check the implementation of this function, it shows
> 
> ```
> Releases memory from `objects` by setting them to `None` and calls `gc.collect()` and `torch.cuda.empty_cache()`.
> Returned objects should be reassigned to the same variables.
> ```
> 
> And that seems similar to my manual operation.

How to solve it? I have met the same problem?

**Comment by zhaziqwe** [comment]
i met the same problem in 4.40.1,  seem nobody cares how to del model :(

**Comment by Rocketknight1** [comment]
cc @sunmarc @MekkCyber maybe? Not sure if there's anything we can fix here or if that utility is maintained

**Comment by SunMarc** [comment]
Any reproducer of the issue you are facing @zhaziqwe ?
