### ISSUE TITLE
XLNet: Incorrect segment id for CLS token

### ISSUE THREAD

**Issue by ChristophAlt** [huggingface/transformers#2603]
Thanks for the great work!

It seems that the XLNetTokenizer assigns an incorrect segment id to the CLS token when a single sequence of token ids is provided. If token_ids_1 is None, all segment ids are '0', including the segment id of the CLS token. In my understanding, the segment ids should always differ.

```python
if token_ids_1 is None:
    return len(token_ids_0 + sep + cls) * [0]
return len(token_ids_0 + sep) * [0] + len(token_ids_1 + sep) * [1] + cls_segment_id
```
https://github.com/huggingface/transformers/blob/983c484fa2fcad307d37cb81f3e1125aa7b9dc37/src/transformers/tokenization_xlnet.py#L243

The original implementation assigns a different segment id to the CLS token in both cases (single sequence of tokens and pair of sequences): https://github.com/zihangdai/xlnet/blob/bbaa3a6fa0b3a2ee694e8cf66167434f9eca9660/classifier_utils.py#L109

**Comment by LysandreJik** [comment]
Indeed, this is an error ! Thanks for letting us know, it was patched with 088fa7b!
