### ISSUE TITLE
How to perform batch inference? 

### ISSUE THREAD

**Issue by ryanshrott** [huggingface/transformers#26061]
### Feature request

I want to pass a list of tests to model.generate. 

text = "hey there"
inputs = tokenizer(text, return_tensors="pt").to(0)

out = model.generate(**inputs, max_new_tokens=184)
print(tokenizer.decode(out[0], skip_special_tokens=True))

### Motivation

I want to do batch inference. 

### Your contribution

Testing

**Comment by NielsRogge** [comment]
See #24575

**Comment by gante** [comment]
Hey there @ryanshrott @NielsRogge 👋 

I've added a short section in our basic LLM tutorial page on how to do batched inference in [this PR](https://github.com/huggingface/transformers/pull/26937). 

Taken from the updated guide, here's an example:
```py
>>> from transformers import AutoTokenizer, AutoModelForCausalLM

>>> model = AutoModelForCausalLM.from_pretrained(
...     "mistralai/Mistral-7B-v0.1", device_map="auto", load_in_4bit=True
... )
>>> tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-v0.1", padding_side="left")
>>> tokenizer.pad_token = tokenizer.eos_token  # Most LLMs don't have a pad token by default
>>> model_inputs = tokenizer(
...     ["A list of colors: red, blue", "Portugal is"], return_tensors="pt", padding=True
... ).to("cuda")
>>> generated_ids = model.generate(**model_inputs)
>>> tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
['A list of colors: red, blue, green, yellow, orange, purple, pink,',
'Portugal is a country in southwestern Europe, on the Iber']
```

**Comment by ryanshrott** [comment]
@gante Is this faster than running them in a loop?

**Comment by gante** [comment]
@ryanshrott yes, much faster! The caveat is that it requires slightly more memory from your hardware, i.e. you should use it whenever you can :)
