### ISSUE TITLE
Tokenizer and unicode problems

### ISSUE THREAD

**Issue by bombel28** [huggingface/transformers#26070]
### System Info

UnicodeEncodeError: 'charmap' codec can't encode character '\u016b' in position 13: character maps to <undefined>

This is new...

Next new issue: when using hardcut in oobabooga to use eos token, tokenizer can't handle two eos (or bos)-tokens.

All issues belongs to llama model (llama-2-13B here)

EDIT: seems like wrong encoding is used. Earlier version uses correctly utf-8
EDIT again: converting training data to UTF-8 BOM solves the problem with unicode.
### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

1. Use a raw text training file in UTF8 in different languages like czech, french
2. use many linefeeds at once (six or more)
3. activate Add EOS token in oobabooga and set Hard Cut String to \n\n\n (default)

Start training on an early llama-2 model with basic / original tokenizer

Two problems will cause to don't start training.

I solved the eos-token-problem meanwhile this way for me:
in tokenization_llama.py, i added /changed this in     def tokenize(self, text: "TextInput", **kwargs):

        if len(tokens) > 1 and tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:

            # Log the text to a file
            with open("error_log.txt", "a") as log_file:
                log_file.write(text + "\n")
			
            tokens = tokens[1:]
        return tokens

So the last unusable token is removed, and the line is logged for further error handling in training data.

### Expected behavior

as in old version before, this problems did not occure on same training data

**Comment by ArthurZucker** [comment]
Sorry could you explain what « obabooga » is?

**Comment by bombel28** [comment]
text generation web UI, sorry for typo, should be oobabooga.

**Comment by bombel28** [comment]
seems to be solved.
