### ISSUE TITLE
AutoModel.from_pretrained is messing with stack traces in jupyter

### ISSUE THREAD

**Issue by qrdlgit** [huggingface/transformers#26085]
### System Info

AutoModel.from_pretrained is messing with stack traces 

I get these wacky stack traces displayed for unhandled exceptions after running AutoModel.from_pretrained("BAAI/bge-small-en").   Colored text, etc.  Do. Not.  Want.

Worse - these stack traces are missing relevant frames which make it impossible to debug.

How do I get rid of this / stop this from happening?

I tried resetting the sys.excepthook, but it didn't help

Took me way too long to find the culprit.  At first I thought it was sentence transformers, than I went through every dep / and line by line code.   These sorts of insane bundling side effect nonsense things which permanently mess with your environment beyond the lifetime of the process have to stop.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

AutoModel.from_pretrained("BAAI/bge-smal-en").

### Expected behavior

Certainly not that.

**Comment by amyeroberts** [comment]
Hi @qrdlgit, thanks for opening an issue!

Would it be possible to share an example of the trackback itself and what it looks like? Just from this description it's not possible to know what the issue is. For example, what relevant frames are missing or what is considered to be 'wacky'.

**Comment by qrdlgit** [comment]
This has been fixed in latest issue by making rich opt-in  https://github.com/huggingface/accelerate/issues/1630
