### ISSUE TITLE
Tesnsor size issue

### ISSUE THREAD

**Issue by J-JEMINA** [huggingface/transformers#26080]
Sorry! I am new here and didn't know where to post my query.

I am using PhageRBP detection which uses bioembeddings tool. In that, I am trying to create embeddings for a genome of e.coli phage of size 108485kb but I get this error immediately. I am working in Google Colab since I am a complete beginner and only comfortable working in that

The expanded size of the tensor (108485) must match the existing size (40000) at non-singleton dimension 1. Target sizes: [1, 108485]. Tensor sizes: [1, 40000]. This most likely means that you don't have enough GPU RAM to embed a protein this long.

As I tried to navigate, I realized it originates from the transformer tool that they are trying to use. I tried seeing if chatgpt can be of any use but it just says the expand function cannot expand beyond 40000. I am willing to pay for Colab Pro or Pro+ as well if that would solve this issue. I have 100s of genomes of similar size to run as well. I do not know how to solve this.

Can someone help me with how to resolve this, please?

Any help would be appreciated.

Thank you!

**Comment by amyeroberts** [comment]
Hi @J-JEMINA, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by J-JEMINA** [comment]
Thank you so much for the information!
But when I post there the bot classifies it as spam and hides it. Can anyone help me to get an answer on this?

**Comment by amyeroberts** [comment]
Hi @J-JEMINA, 

Sorry to hear that. If there's a link to the post, I can see if I can clear it as a real human's question. Another alternative is asking on our discord: https://discord.com/invite/hugging-face-879548962464493619

**Comment by J-JEMINA** [comment]
https://discuss.huggingface.co/t/facing-tensor-size-issue-in-tranformer-tool/54510

This is the link to the query I raised in the forum! I would be happy if you can help
