### ISSUE TITLE
BART Impelemntation in JAX vs Pytorch

### ISSUE THREAD

**Issue by DavidAkinpelu** [huggingface/transformers#26088]
It is possible to initiate BART decoder as a less causal decoder based in Jax implementation and but It doesn't seems straight forward in Pytorch?

I there any reason why this is designed this way?

**Comment by amyeroberts** [comment]
Hi @DavidAkinpelu, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by DavidAkinpelu** [comment]
Okay.
