### ISSUE TITLE
batching in pipeline gives single output

### ISSUE THREAD

**Issue by znb899** [huggingface/transformers#26081]
### System Info

```
from transformers import pipeline
from transformers.pipelines.pt_utils import KeyDataset
import datasets

dataset = datasets.load_dataset("imdb", name="plain_text", split="unsupervised")
pipe = pipeline("text-classification", device=0)
for out in pipe(KeyDataset(dataset, "text"), batch_size=8, truncation="only_first"):
    print(out)
    # [{'label': 'POSITIVE', 'score': 0.9998743534088135}]
    # Exactly the same output as before, but the content are passed
    # as batches to the model
```

Why is batching not giving a list (of 8 here) of outputs? Isn't it the point of batching or am I missing something? Eitherway, it's counter intuitive.

This code is from the [the pipeline doc page](https://huggingface.co/docs/transformers/main_classes/pipelines#pipeline-batching). I haven't tried it but I have this issue (?) with another pipeline task.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run the above code

### Expected behavior

[{'label': 'POSITIVE', 'score': 0.9998743534088135}, {'label': x, 'score': x}, {'label': x, 'score': x} ....]

**Comment by geronimi73** [comment]
+1

**Comment by ArthurZucker** [comment]
You are looping on the outputs of `pipe(KeyDataset(dataset, "text"), batch_size=8, truncation="only_first")`.
If you just print `pipe(KeyDataset(dataset, "text"), batch_size=8, truncation="only_first")` you'll see what you want. The example in the doc shows how you can create an iterator over these outputs, which sometimes is faster than a direct call on the batch.
