### ISSUE TITLE
Bug in the command line tool: os.DirEntry not supported in Python 3.5

### ISSUE THREAD

**Issue by netw0rkf10w** [huggingface/transformers#2608]
Hi,

[This line](https://github.com/huggingface/transformers/blob/1a8e87be4e2a1b551175bd6f0f749f3d2289010f/src/transformers/commands/user.py#L162) will cause a syntax error in Python 3.5 as `os.DirEntry` does not exist.

You should either update the code for backward compatibility or update the README replacing 3.5+ by 3.6 (I believe the former would be preferred).

Best regards.

**Comment by julien-c** [comment]
Though the core of the library is Python 3.5+, the CLI is actually Python3.6+ as for instance the serving subcommand uses FastAPI which is Py36+ only (cc @mfuntowicz)

Do we have a way to make that clear in the doc @LysandreJik?

**Comment by BramVanroy** [comment]
Personal opinion: supporting 3.6+ only seems realistic and may make maintenance easier. [AllenNLP ](https://github.com/allenai/allennlp) also requires 3.6.1+. Of course I don't know how large the 3.5 user-base is for `transformers` so it might be worth maintaining. That being said, if there are plans to stop support for 3.5, it might be a good idea to announce this in a release ("last supported release for 3.5").

**Comment by julien-c** [comment]
@BramVanroy According to the PyPI stats at https://pypistats.org/packages/transformers (look for the `Daily Download Proportions of transformers package - Python Minor` graph) around 1% of _pip installs_ are on Python 3.5.

**Comment by BramVanroy** [comment]
> @BramVanroy According to the PyPI stats at https://pypistats.org/packages/transformers (look for the `Daily Download Proportions of transformers package - Python Minor` graph) around 1% of _pip installs_ are on Python 3.5.

Ah, I didn't know this website - thanks! I'm not sure if 1% is worth the effort, then again I don't know how much additional effort (and resources for CI) are needed to maintain for 3.5 anyway. (But 3.6 has f-strings and ordered dicts (officially in 3.7), PathLike, better `typing`,  sooo... :D)

PS: I wonder what happened on December 24 or thereabouts, with the spike in 3.5 installations.

**Comment by julien-c** [comment]
Closing this as the lib is now officially Python 3.6+
