### ISSUE TITLE
Bad Results with Albert

### ISSUE THREAD

**Issue by chikubee** [huggingface/transformers#2609]
## ❓ Questions & Help
Trying to understand why is the cosine similarity between tokens with Albert way bad in comparison to DistilBert. 
Any inferences on the same would be helpful.
Thanks in advance. 

Embeddings constructed for a token by summing the last 4 encoded layers.
Distance metric: cosine

Results with DistilBert
<img width="754" alt="Screenshot 2020-01-22 at 4 05 06 PM" src="https://user-images.githubusercontent.com/25073753/72887172-2e6feb80-3d31-11ea-876b-0ba8eac22234.png">
<img width="613" alt="Screenshot 2020-01-22 at 4 12 27 PM" src="https://user-images.githubusercontent.com/25073753/72887650-25334e80-3d32-11ea-8255-26109f604c84.png">

Results with Albert
<img width="735" alt="Screenshot 2020-01-22 at 4 04 56 PM" src="https://user-images.githubusercontent.com/25073753/72887227-447dac00-3d31-11ea-8797-9873c8439879.png">
<img width="499" alt="Screenshot 2020-01-22 at 4 10 16 PM" src="https://user-images.githubusercontent.com/25073753/72887665-2bc1c600-3d32-11ea-95aa-83b3192e9d49.png">

**Comment by BramVanroy** [comment]
Hi. Many people are reporting unstable results or just unexpected results. You can search for issues in this library, and even in other ones (e.g. https://github.com/deepset-ai/FARM/issues/202#issuecomment-577077201). It seems that ALBERT is very sensitive to hyperparameters and even then... For now there seems to be no solution. It is probably best to stick to another model. I'd recommend RoBERTa but it depends on your use-case.

**Comment by chikubee** [comment]
@BramVanroy I tried with roberta-base as well, the token level similarity is coming out very bad. 
Smoking is getting matched with software.

**Comment by BramVanroy** [comment]
Can you share a repo to your full code?
