### ISSUE TITLE
Simplify cache interface for Falcon model

### ISSUE THREAD

**Issue by RezaYazdaniAminabadi** [huggingface/transformers#26097]
### Feature request

Hi, 

I have been looking at the Falcon modeling file and I am seeing that the cache interface might have got a bit too complicated! It, however, could have been simplified a bit. 
There are the two functions, `_convert_cache_to_standard_format` and `_convert_to_rw_cache` which are called after and before the network's forward, and if I understand correctly it is mostly for finding the current generation context length (as mentioned in the comment of [this line](https://github.com/huggingface/transformers/blob/main/src/transformers/models/falcon/modeling_falcon.py#L885)).
By looking at the code, I realized that we can always get the context-length by just taking the `shape[-2]` form the layer_past tuple. By doing this, we can just remove these two function calls to change the format of the kv-cache.
If this makes sense, I can make a PR and fix this, otherwise, please feel free to close this!
Thanks,
Reza

### Motivation

Simplifying the cache interface for Falcon model.

### Your contribution

Yes, I can make a PR if neede.

**Comment by amyeroberts** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
Hi @RezaYazdaniAminabadi, yes, the cache is still a bit of a mess there! Falcon started as custom code, and I wrote the Hugging Face port of that custom code. The custom code copied the strange cache shapes from BLOOM, but there were issues in the implementation that severely hurt generation performance. In the port, I focused on getting generation performance up while ensuring correctness, but I was aware that the cache could probably do with a more fundamental rewrite.

If you think you can clean up the cache code, I'd be happy to review a PR!

**Comment by RezaYazdaniAminabadi** [comment]
Cool, then I add some changes and then add you as the reviewer to check this.
Thanks.
