### ISSUE TITLE
Typo in the doc of AutoTokenizer? Two parameters for slow_tokenizer_class

### ISSUE THREAD

**Issue by xukp20** [huggingface/transformers#26108]
**Is your feature request related to a problem? Please describe.**
The parameters [here](https://huggingface.co/docs/transformers/v4.33.0/en/model_doc/auto#transformers.AutoTokenizer.register.slow_tokenizer_class) contain two slow_tokenizer_class which should be a typo I think.

**Additional context**
![image](https://github.com/huggingface/hub-docs/assets/71265541/ff5e9bbf-4baa-4bac-a82a-035daa44cc2c)

**Comment by amyeroberts** [comment]
@xukp20 Indeed, thanks for pointing out! Would you like to open a PR to fix the typo? This way you get the github contribution.

**Comment by xukp20** [comment]
@amyeroberts Thanks, but I've never opened a PR for transformers before and never learned about writing the doc of transformers, so it's hard to find where to fix it quickly. I believe this minor change does not worth the trouble, so it would be nice if you can fix it at your convenience or remind anyone else to do so. Never mind the contribution! :)

**Comment by amyeroberts** [comment]
@xukp20, ok no worries. I've opened a PR to fix it. Thanks again for highlighting!

If you ever fancy opening a PR in this repo on day, here's a guide: https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md/#create-a-pull-request
