### ISSUE TITLE
A potential bug in convert_llama_weights_to_hf.py

### ISSUE THREAD

**Issue by lumosity4tpj** [huggingface/transformers#26109]
### System Info

I did not run the hf code, just found a potential bug while referring to the code

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I found a potential bug in [convert_llama_weights_to_hf_L114](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py#L114), the cause of the error is that `num_key_value_heads` is used as` num_key_value_groups`, the reason for the success of the` llama2 `conversion weights, Because `num_key_value_heads=num_key_value_groups=8`,

A simple example would be: `num_key_value_heads=32, num_heads=64, num_shards=8`, then n_heads_per_shard = n_heads // num_shards=8 `, num_local_key_value_heads = n_heads_per_shard // num_key_value_heads = 0 `

`num_key_value_heads` should, as I understand it, refer to the total number of` kv_heads`, See [this](https://github.com/facebookresearch/llama/blob/main/llama/model.py#L186),

### Expected behavior

just correct

**Comment by younesbelkada** [comment]
Hi @lumosity4tpj 
Thanks a lot for your message. Your explanation seems to makes sense, note we used this script internally to convert Llama weights into HF format and it worked, we probably did not supported all possible edge cases but the conversion script would work for the models that are currently on the Hub. Maybe @ArthurZucker has more context for this specific issue

**Comment by ArthurZucker** [comment]
Feel free to open a PR with a fix if you want (mathematically yes, we would have a fail) but no checkpoints were released with `num_key_value_heads != 8`. This is also related to performance optimisation, as you would have more copies to make locally if `num_key_value_heads != num_key_value_groups`.

> just correct

it's already correct with released checkpoints
