### ISSUE TITLE
[New model] Phi-1 and Phi-1_5

### ISSUE THREAD

**Issue by xenova** [huggingface/transformers#26110]
### Model description

From their respective model cards,

phi-1:

> The language model phi-1 is a Transformer with 1.3 billion parameters, specialized for basic Python coding. Its training involved a variety of data sources, including subsets of Python codes from [The Stack v1.2](https://huggingface.co/datasets/bigcode/the-stack), Q&A content from [StackOverflow](https://archive.org/download/stackexchange), competition code from [code_contests](https://github.com/deepmind/code_contests), and synthetic Python textbooks and exercises generated by [gpt-3.5-turbo-0301](https://platform.openai.com/docs/models/gpt-3-5). Even though the model and the datasets are relatively small compared to contemporary Large Language Models (LLMs), phi-1 has demonstrated an impressive accuracy rate exceeding 50% on the simple Python coding benchmark, HumanEval.

phi-1_5:
> The language model phi-1.5 is a Transformer with 1.3 billion parameters. It was trained using the same data sources as [phi-1](https://huggingface.co/microsoft/phi-1), augmented with a new data source that consists of various NLP synthetic texts. When assessed against benchmarks testing common sense, language understanding, and logical reasoning, phi-1.5 demonstrates a nearly state-of-the-art performance among models with less than 10 billion parameters.
>
> We did not fine-tune phi-1.5 either for instruction following or through reinforcement learning from human feedback. The intention behind crafting this open-source model is to provide the research community with a non-restricted small model to explore vital safety challenges, such as reducing toxicity, understanding societal biases, enhancing controllability, and more.

Benchmarks for the 1.5 model (from their [paper](https://arxiv.org/pdf/2309.05463.pdf)) indicate better (or on-par) performance with llama and llama2 models, especially on multi-step reasoning.
![image](https://github.com/huggingface/transformers/assets/26504141/eae8a6ae-62cf-4d17-ad55-a7ec4222afa5)

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Phi-1
Paper: https://arxiv.org/abs/2306.11644

Model + code: https://huggingface.co/microsoft/phi-1

### Phi-1_5

Paper: https://arxiv.org/abs/2309.05463

Model + code: https://huggingface.co/microsoft/phi-1_5

**Comment by susnato** [comment]
Hi @xenova , are you contributing this model(s)? If not, can I please take this issue?

**Comment by xenova** [comment]
@susnato I just made the request, so feel free to take it! 🤗
