### ISSUE TITLE
AttributeError: 'LlamaForCausalLM' object has no attribute 'save_checkpoint'

### ISSUE THREAD

**Issue by dittops** [huggingface/transformers#26128]
### System Info

I'm training a llama model. When I try using Deepspeed along with the trainer, I get the below error

<img width="695" alt="image" src="https://github.com/huggingface/transformers/assets/12937285/3cd5a3c1-34c9-46b3-93e0-e5dd454b8a3b">

Training script

```
tokenizer = LlamaTokenizer.from_pretrained(model_args.base_model)
    tokenizer.pad_token_id = 0

    model = LlamaForCausalLM.from_pretrained(
        model_args.base_model,
        device_map="auto"
    )

    total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print("total params: ", total_params)


    if data_args.data_path.endswith(".json") or data_args.data_path.endswith(".jsonl"):
        data = load_dataset("json", data_files=data_args.data_path)
    else:
        data = load_dataset(data_args.data_path)
    
    dataset =  load_data(tokenizer, data['train'], data_args.max_seq_length)
    data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)


    trainer = Trainer(
        model=model, 
        tokenizer=tokenizer, 
        args=training_args, 
        data_collator=data_collator,
        **dataset
    )

    model.config.use_cache = False
    trainer.train()
    trainer.save_model()
```

I'm using deepspeed stage 2

```
{
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "zero_allow_untested_optimizer": true,
    "fp16": {
      "enabled": "auto",
      "loss_scale": 0,
      "initial_scale_power": 16,
      "loss_scale_window": 1000,
      "hysteresis": 2,
      "min_loss_scale": 1
    },  
    "zero_optimization": {
      "stage": 2,
      "allgather_partitions": true,
      "allgather_bucket_size": 5e8,
      "reduce_scatter": true,
      "reduce_bucket_size": 5e8,
      "overlap_comm": false,
      "contiguous_gradients": true
    }
  }

```

If I use FSDP instead of deepspeed, the checkpoints are getting saved.

transformers==4.34.0.dev0 (I tried with transformers==4.33.0 as well)
deepspeed==0.10.3

### Who can help?

@pacman100 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Command used for launching the script

`CUDA_VISIBLE_DEVICES=0,3 python train.py --data_path /path/to/data.json --output_dir output  --per_device_train_batch_size 4 --num_train_epochs 2 --learning_rate 2e-5 --fp16 True --logging_steps 10 --save_strategy steps --save_steps 20 --save_total_limit 5 --adam_beta2 0.95 --deepspeed ds_config.json`
``

### Expected behavior

The model gets saved without any errors.

**Comment by dittops** [comment]
The model is saving fine while changing to stage 3

**Comment by pacman100** [comment]
> CUDA_VISIBLE_DEVICES=0,3 python train.py --data_path /path/to/data.json --output_dir output  --per_device_train_batch_size 4 --num_train_epochs 2 --learning_rate 2e-5 --fp16 True --logging_steps 10 --save_strategy steps --save_steps 20 --save_total_limit 5 --adam_beta2 0.95 --deepspeed ds_config.json


The command used for launching is incorrect. Please use `torchrun`, `deepspeed` or `accelerate launch` when running in distributed setup. Please go through the docs here: https://huggingface.co/docs/transformers/main_classes/deepspeed#deployment-with-multiple-gpus

**Comment by OriginalGoku** [comment]
I am getting the same error but from a much simpler code. I am running this on Colab with a free T4. 
The code was copied from here:
[https://huggingface.co/TheBloke/CodeLlama-7B-Instruct-AWQ](CodeLlama7B)

Here is the code: 

```
The code is pretty simple:
!pip3 install autoawq
from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer

from transformers import pipeline

# model_name_or_path = "TheBloke/CodeLlama-13B-Instruct-AWQ"
model_name_or_path = "TheBloke/CodeLlama-7B-Instruct-AWQ"


# Load model
model = AutoAWQForCausalLM.from_quantized(model_name_or_path, fuse_layers=True,
                                          trust_remote_code=True, safetensors=True)

tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True)


prompt = "Tell me about AI"
# This was the default prompt and i did not change it
prompt_template=f'''[INST] Write code to solve the following coding problem that obeys the constraints and passes the example test cases. Please wrap your code answer using ```:

{prompt}

[/INST]

'''

print("*** Pipeline:")
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    do_sample=True,
    temperature=0.7,
    top_p=0.95,
    top_k=40,
    repetition_penalty=1.1
)

print(pipe(prompt_template)[0]['generated_text'])

```
and here is the error: 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-7-6fa1284003fe>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 print("*** Pipeline:")
----> 5 pipe = pipeline(
      6     "text-generation",
      7     model=model,

1 frames
[/usr/local/lib/python3.10/dist-packages/transformers/pipelines/__init__.py](https://localhost:8080/#) in pipeline(task, model, config, tokenizer, feature_extractor, image_processor, framework, revision, use_fast, token, device, device_map, torch_dtype, trust_remote_code, model_kwargs, pipeline_class, **kwargs)
    842         )
    843 
--> 844     model_config = model.config
    845     hub_kwargs["_commit_hash"] = model.config._commit_hash
    846     load_tokenizer = type(model_config) in TOKENIZER_MAPPING or model_config.tokenizer_class is not None

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1693             if name in modules:
   1694                 return modules[name]
-> 1695         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
   1696 
   1697     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'LlamaAWQForCausalLM' object has no attribute 'config'
```

When I do the inference with the following code, everything works:

```
print("\n\n*** Generate:")

tokens = tokenizer(
    prompt_template,
    return_tensors='pt'
).input_ids.cuda()

# Generate output
generation_output = model.generate(
    tokens,
    do_sample=True,
    temperature=0.7,
    top_p=0.95,
    top_k=40,
    max_new_tokens=512
)

print("Output: ", tokenizer.decode(generation_output[0]))
```

**Comment by jyhong836** [comment]
Hi, I encounter the same problem. I cannot use ZERO3 because mpi4py cannot be installed. I cannot use torchrun, deepspeed or accelerate launch because these command will cause OOM error (they seems to fit one model in one GPU). 
Is there any method to use deepspeed ZERO 2 and save the model smoothly?

**Comment by amyeroberts** [comment]
Hi @jyhong836, could you open a new issue? This will help us track what is and isn't resolved and your issue seems somewhat different, specifically the issue with mpi4py. 

I'd suggest asking in our [forums](https://discuss.huggingface.co/). As github issues are primarily for feature requests and bug reports for transformers
