### ISSUE TITLE
the NoRepeatNGramLogitsProcessor is slow

### ISSUE THREAD

**Issue by nevakrien** [huggingface/transformers#26130]
### Feature request

its relatively easy to just cash the values ahead of time and then use those, rn its build in a way that requires looking through the whole text every single time. u could have simply kept the dict and added 1 value to it.

### Motivation

I am trying to make generation faster

### Your contribution

I could probably help with the pull request if you guys r interested

**Comment by amyeroberts** [comment]
cc @gante

**Comment by gante** [comment]
Hey @nevakrien 👋 

Our main focus is the breadth and availability of techniques, which means performance sometimes gets relegated to a second plan. Your contribution (with a few benchmarks before/after the changes) would definitely be appreciated 🤗
