### ISSUE TITLE
storing & logging gradient norm in trainer

### ISSUE THREAD

**Issue by shijie-wu** [huggingface/transformers#26143]
### Feature request

store and log gradient norm in trainer

### Motivation

Gradient norm is an important metric but currently the gradient norm is discarded during clipping. 

### Your contribution

I checked and all of the following grad_norm_clip functions return the gradient norm. We can get gradient norm without extra compute by storing the return value, and we can then log it. If this sounds good i am happy to prepare a PR.

https://github.com/huggingface/transformers/blob/32ec7345f2d752c294ddf5aff495b657c9cd9d3b/src/transformers/trainer.py#L1918-L1936

**Comment by lucasjinreal** [comment]
I want disable it, how?
