### ISSUE TITLE
allow easier user customizable `decay_parameters` in trainer

### ISSUE THREAD

**Issue by shijie-wu** [huggingface/transformers#26145]
### Feature request

allow easier user customizable `decay_parameters` in trainer

### Motivation

https://github.com/huggingface/transformers/blob/32ec7345f2d752c294ddf5aff495b657c9cd9d3b/src/transformers/trainer.py#L964-L965

Currently to modify `decay_parameters` for weight decay, user need to inherit and implement the entire `create_optimizer`. By refactor this two line into a function, user can modify `decay_parameters` much easier.

### Your contribution

if this sounds good, i am happy to submit a PR

**Comment by muellerzr** [comment]
This *feels* like it's okay to me, but I'd need to see what the full implementation will look like @shijie-wu if you want to take a stab at it :)
