### ISSUE TITLE
Missing module "startlette" when calling transformers-cli

### ISSUE THREAD

**Issue by tailaiw** [huggingface/transformers#2614]
Calling `transformers-cli` in terminal returns error ``ModuleNotFoundError: No module named 'starlette'``.

I assume starlette should be added into dependencies in setup.py and it will be a quick fix.

**Comment by mfuntowicz** [comment]
Hi @tailaiw, thanks for reporting the issue.

Can you try to update to the latest version of transformers ? it should have been fixed in 5004d5af42c61c91d5df07aa139d37599ceb6215.

Feel free to reopen if its not the case !
