### ISSUE TITLE
BitsAndBytes

### ISSUE THREAD

**Issue by Shikamaru5** [huggingface/transformers#26153]
I'm trying to run my model with:

    bnb_config = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=torch.float16,
                )
Trouble is when I run it I get an error about some modules are dispatched on the CPU or the disk. If you want to dispatch the model on the CPU or the disk while keeping these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom `device_map` to `from_pretrained`
Looking into it on hugging_face and goodle, and some of the code in modeling_utils.py. I didn't see anything that suggested you could do something like 'load_in_4bit_fp32_cpu_offload=True' or something along those lines. I'm guessing it isn't a feature yet, or maybe coming? If anyone has any ideas about that I'd be really grateful. I'm going to test the 8bit thing and see if that's enough but I'm not totally certain that 8bits will be low enough to load the model unfortunately.

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!
You can also ping @younesbelkada there. 
Thanks!

**Comment by vince62s** [comment]
+1 I amended the forum discussion but to me looks more like a bug.

**Comment by ArthurZucker** [comment]
cc @younesbelkada maybe just update the warning to include `4bits`

**Comment by Shikamaru5** [comment]
I'm not too sure but I added this to bnb_config: load_in_8bit_fp32_cpu_offload=True and then I created a custom device_map with every single layer of the model to the gpu which ended up being around 456 layers, but it seems to have loaded now, yay me!

**Comment by vince62s** [comment]
well if we specifically don't want any kind of offload (hence leave this flag to False) then I think there is no reason why this warning should pop up, but maybe I am missing something.

**Comment by younesbelkada** [comment]
Hey there! 
I think passing `load_in_8bit_fp32_cpu_offload` also works for 4bit models, if that's the case I agree it is confusing, we should add a new arg `load_in_4bit_fp32_cpu_offload` that would behave exactly as the 8-bit arg. I can work on that and propose a fix. I will keep you posted
