### ISSUE TITLE
Error with load_in_4bit argument when loading model

### ISSUE THREAD

**Issue by matsuobasho** [huggingface/transformers#26165]
### System Info

OS: Windows 10 64-bit
Python version: 3.9.6
Transformers: 4.33.1  (imported with `pipenv install transformers[torch]`)
Accelerate: 0.22.0
BitsandBytes: 0.41.1

Environment manager: pipenv

### Who can help?

@SunMarc @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I get an error saying that I need Accelerate when using the `load_in_4bit` argument in the `from_pretrained` method.

```python
from transformers import AutoModelForCausalLM, AutoTokenizer

checkpoint = "Salesforce/codegen-350M-mono" 
device = "cpu"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(checkpoint, trust_remote_code=True, load_in_4bit = True).to(device)
```

Error:
```ImportError:` Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` ```

Same issue expressed by many people in [this](https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/discussions/11) post.  

### Expected behavior

Model loads without errors.

**Comment by SunMarc** [comment]
Hi @matsuobasho , i can't reproduce the error with your setup. Please check which one of these conditions fails: `is_accelerate_available()` and `is_bitsandbytes_available()`. You can import them with 
```py
from transformers.utils import is_accelerate_available, is_bitsandbytes_available
```

**Comment by matsuobasho** [comment]
@SunMarc, thanks for the response.

`is_bitsandbytes_available()` returns False

**Comment by SunMarc** [comment]
Then check inside the code where it returns false. It is either torch or bitsandbytes the problem. After you find it, reinstall the library.

**Comment by matsuobasho** [comment]
I'm able to import torch.
When I import bitsandbytes I see this warning:
`UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'`

So that seems to be the problem but not sure how to resolve.

**Comment by younesbelkada** [comment]
Hi @matsuobasho 

> So that seems to be the problem but not sure how to resolve. Also, do I need CUDA in order for bitsandbytes to work? I'm just running this locally on a CPU.

Note that bitsandbytes features we have integrated only works on GPU, so your behaviour is expected unfortunately. To use these feature, you can use for instance free-tier GPU instances such as google colab or kaggle notebooks

**Comment by matsuobasho** [comment]
Ok, this should be noted somewhere in the tutorials to save people like me time on this.
Perhaps on [this ](https://huggingface.co/blog/4bit-transformers-bitsandbytes) tutorial.

Happy to open another issue specifically about that.
