### ISSUE TITLE
Adaptive Attention Span for Transformers

### ISSUE THREAD

**Issue by djstrong** [huggingface/transformers#2616]
# 🌟New model addition

## Open Source status

* [x] the model implementation is available: https://github.com/facebookresearch/adaptive-span
* [x] the model weights are available: get_pretrained.sh
* [x] who are the authors: Facebook Research

## Additional context

No additional dependencies required.

**Comment by ruanchaves** [comment]
Any clue about how to integrate that into a BERT model?
