### ISSUE TITLE
Segmentation Fault when trying to load HuggingFace Model

### ISSUE THREAD

**Issue by y12uc231** [huggingface/transformers#26169]
### System Info

```
Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import AutoModel
>>> model = AutoModel.from_pretrained("gpt2")
zsh: segmentation fault  python
```

I am using transformers version = '4.33.1'

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

In the python terminal. 
```
Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import AutoModel
>>> model = AutoModel.from_pretrained("gpt2")
zsh: segmentation fault  python
```

### Expected behavior

The model should load instead of throwing a segmentation fault.

**Comment by ArthurZucker** [comment]
Hey! I cant reproduce this, you should try to re-install python this does not seem to have anything to do with transformers
