### ISSUE TITLE
Adding scibert in the list of pre-trained models?

### ISSUE THREAD

**Issue by aCampello** [huggingface/transformers#2619]
# 🌟New model addition

## Model description

Would it be possible/is it in the pipeline to add SCIBERT as one of the pre-trained models for Bert? Could be as simple as adding it to the `BERT_PRETRAINED_MODEL_ARCHIVE_MAP`.

## Open Source status

Scibert is available on its own repository (https://github.com/allenai/scibert). The advantage of adding it to the map is that we don't need to download it ad-hoc every time we want to use it, it would be cached in the same repository, etc.

* [x] the model implementation is available: 
* [x] the model weights are available: 
* [x] who are the authors: Iz Beltagy and Kyle Lo and Arman Cohan authored the ALlenAI

**Comment by BramVanroy** [comment]
It would be nice if AllenAI uploaded their models to [the user hub](https://huggingface.co/models). That would allow you to simply load the models like `.from_pretrained('allenai/scibert-scivocab-uncased')`.

**Comment by aCampello** [comment]
Right, I missed that 2.2.2 update for model sharing (https://huggingface.co/transformers/model_sharing.html). So you're right, probably the best thing is for them to upload their model.

**Comment by BramVanroy** [comment]
Might be best to close this issue here and keep everything in the issue that you created over at AllenAI.

**Comment by aCampello** [comment]
Yeah, makes sense. Thanks.
