### ISSUE TITLE
Transformers LocalAgent - Error with GPT model, are there any specific limitations for LocalAgent?

### ISSUE THREAD

**Issue by gidzr** [huggingface/transformers#26195]
### System Info

cpu, latest version transformers, python 3.10

### Who can help?

@ArthurZucker, @younesbelkada and @Narsil

Hey there

I am using the example you provide for LocalAgent at: https://huggingface.co/docs/transformers/main_classes/agent#transformers.LocalAgent

Except I've replaced the example repo with GPT, and asked a general question to see how the model responds.

I get the following warnings and error in CLI
```bash
Token indices sequence length is longer than the specified maximum sequence length for this model (1592 > 1024). Running this sequence through the model will result in indexing errors
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "/root/test.py", line 1838, in <module>
    runInferenceCausalLM1(context)
  File "/root/test.py", line 1662, in runInferenceCausalLM1
    agent.run("Tell me what a black hole is made of?.")
  File "/root/projectName11/lib/python3.10/site-packages/transformers/tools/agents.py", line 341, in run
    result = self.generate_one(prompt, stop=["Task:"])
  File "/root/projectName11/lib/python3.10/site-packages/transformers/tools/agents.py", line 740, in generate_one
    outputs = self.model.generate(
  File "/root/projectName11/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/projectName11/lib/python3.10/site-packages/transformers/generation/utils.py", line 1602, in generate
    return self.greedy_search(
  File "/root/projectName11/lib/python3.10/site-packages/transformers/generation/utils.py", line 2450, in greedy_search
    outputs = self(
  File "/root/projectName11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/projectName11/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1076, in forward
    transformer_outputs = self.transformer(
  File "/root/projectName11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/projectName11/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 844, in forward
    position_embeds = self.wpe(position_ids)
  File "/root/projectName11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/projectName11/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/root/projectName11/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

The code I'm using is shown below, and is a straight copy from the online quickstart - except - modified for a different task and model. However, should still work.

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
```python
   import torch
   from transformers import AutoModelForCausalLM, AutoTokenizer, LocalAgent

   model = AutoModelForCausalLM.from_pretrained('gpt2', device_map="auto")
   tokenizer = AutoTokenizer.from_pretrained('gpt2')

   agent = LocalAgent(model, tokenizer)
   agent.run("Tell me what a black hole is made of?.")   
```

I've tried with and without   torch_dtype=torch.bfloat16 - I don't think this is the cause.

### Expected behavior

I thought an agent would return the same result as if I'd run the inference with pipeline or transformer approach. I am testing the agent because I was keen on seeing how the prompting helper works.

Thanks

**Comment by ArthurZucker** [comment]
Hey! as the issue mentions, there seems to be an issue with the tokenized inputs. I'll ping @Rocketknight1 here as I won't have time to look into this

**Comment by gidzr** [comment]
@Rocketknight1 Ahh I see.. Re-reading the error, I can see the issue re token size, but my prompt was simply "Tell me what a black hole is made of?" was only ~15 tokens which really confused me.

You refer to the "default prompt" which describes tools and arguments and behind the scenes. Is there any way for me to 'hack' this in a LocalAgent config? eg. if I add my info for these?
- chat_prompt_template (str, optional
- run_prompt_template (str, optional)
- additional_tools ([Tool] list of tools or dictionary with tool values, optional)

I'm assuming if I enter null or custom values for these params it can reduce the token size for input? However, I'm not sure what I'm overriding and how this would affect the Agent's operation. Is there a view of what the defaults for these look like so I can override with a shorter version of each?

**Comment by Rocketknight1** [comment]
Hi @gidzr, take a look at the [Custom Tools and Prompts](https://huggingface.co/docs/transformers/custom_tools) guide!

**Comment by Rocketknight1** [comment]
Again though, note that GPT-2 is a pure text-completion model, and has not been trained to follow instructions or use external tools. I expect even if you can make the prompt short enough to work with it, the results will probably not be very good!

**Comment by gidzr** [comment]
Hey @Rocketknight1 - noted. I'm playing around with this feature again today and will close the issue if I don't have any additional queries / issues. I was attempting GPT2 for size-speed, but will stick with the default per example in documentation.

**Comment by gidzr** [comment]
EPICNESS!  ..thanks for that..  totally makes sense. Agent-tools are a very cool experimentation. 

I was thinking along the same lines re pipelines. My impression is that agents are best suited for multi-modal uses that bring audio+visual+text together when a task is very open-ended, with pipes best suited for a single LLM and targeted use case, whereas multi-LLM (translation+completion) within a mode (text) will need a bit of trial and error to see which works best. Also, as I'm running CPU and agents use specific LLMs for tools, performance will influence the solution.

Your comments re Langchain surprised me a little. I was initially 100% Langchain and loved it, but the outdated API documentation, blackbox approach, and unclear multiple approaches (eg. chain.run() vs chain.generate() vs chain())  moved me towards a full HF eco-system. Langchain feels like it wants to be an umbrella or integration layer, but doesn't simplify or accelerate the base technology it's drawing on - and ends up becoming bloat (eg. the qa_chain-chroma implementation). Some elements are awesome, but HF/onnx/accelerate/pipelines, etc .. provide better performance and usage for me.

Thanks again!

Refs
https://huggingface.co/docs/transformers/transformers_agents#a-curated-set-of-tools
https://huggingface.co/docs/transformers/custom_tools#future-compatibility-with-langchain
