### ISSUE TITLE
Custom training for LayoutLMv3 for document answering task

### ISSUE THREAD

**Issue by NevilleMthw** [huggingface/transformers#26205]
### System Info

- `transformers` version: 4.32.0
- Platform: Linux-6.2.0-32-generic-x86_64-with-glibc2.35
- Python version: 3.11.4
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: N/A
- Using distributed or parallel set-up in script?: N/A

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Hello,

I am not having a specific type of bug but I would like to know if there is any sort of guide towards a custom dataset training for LayoutLMv3, I am following through this link but I don't see how someone with another dataset can follow: https://huggingface.co/docs/transformers/tasks/document_question_answering#evaluation

Is there any standard for the JSON structure? Is there a specific way to import the data so that we can use the existing functions?

Thanks.

### Expected behavior

Ability to fine tune with custom dataset instead of Docvqa dataset.

**Comment by NielsRogge** [comment]
See my demo notebook here: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/DocVQA/Fine_tuning_LayoutLMv2ForQuestionAnswering_on_DocVQA.ipynb.

It's equivalent for LayoutLMv3, just make sure to prepare the data in the right format
