### ISSUE TITLE
Large Language Models as Optimizers

### ISSUE THREAD

**Issue by rajveer43** [huggingface/transformers#26202]
### Feature request

Optimization is ubiquitous. While derivative-based algorithms have been powerful tools for various problems, the absence of gradient imposes challenges on many real-world applications. In this work, we propose Optimization by PROmpting (OPRO), a simple and effective approach to leverage large language models (LLMs) as optimizers, where the optimization task is described in natural language. In each optimization step, the LLM generates new solutions from the prompt that contains previously generated solutions with their values, then the new solutions are evaluated and added to the prompt for the next optimization step. We first showcase OPRO on linear regression and traveling salesman problems, then move on to prompt optimization where the goal is to find instructions that maximize the task accuracy. With a variety of LLMs, we demonstrate that the best prompts optimized by OPRO outperform human-designed prompts by up to 8% on GSM8K, and by up to 50% on Big-Bench Hard tasks.

### Motivation

-

### Your contribution

https://github.com/Moocember/Optimization-by-PROmpting
https://arxiv.org/abs/2309.03409

**Comment by rajveer43** [comment]
what do you think of this issues?

**Comment by ArthurZucker** [comment]
As it is a feature request, unless someone form  the community tackles it I would recommend trying to put the code on the hub first and share this here!

**Comment by rajveer43** [comment]
Okay will do that
