### ISSUE TITLE
Documentation markup for model descriptions

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#2621]
## 🐛 Bug

Looking at [the documentation](https://huggingface.co/transformers/model_doc/bert.html#bertforsequenceclassification), it seems something went wrong in markup land. In some models (but not all, e.g. BertModel, BertForMaskedLM, BertForNextSentencePrediction), the model description (i.e. the first paragraph) is split up in one highlighted line (grey background) and the rest of the text is regular. Seems like a formatting issue in the source code.

**Comment by LysandreJik** [comment]
Hi! Indeed there were quite a few issues with the documentation. #2532 was merged this morning, and hopefully fixes all these issues!

Would love your feedback on the new documentation (be sure to refresh your cache to see the new doc on https://huggingface.co/transformers).

**Comment by BramVanroy** [comment]
Ah, sorry, didn't check the recent commits. Just checked a couple of items. Everything seems in order except for a small inconsistency in the tokenizers:

Some (e.g. [openai](https://huggingface.co/transformers/model_doc/gpt.html#openaigpttokenizer)) put the first line (the one with 'peculiarities') in a highlighted block, while other (e.g. [XLNet](https://huggingface.co/transformers/model_doc/xlnet.html#xlnettokenizer)) don't.

**Comment by LysandreJik** [comment]
Good catch! Up to now I've reworked the configuration + models + glossary. I've yet to do the tokenizers as well as the abstract classes, will work on them in the coming days.

**Comment by BramVanroy** [comment]
If you've finalized that, feel free to close this issue through a commit. I'll have another look, then!
