### ISSUE TITLE
Custom positional embeddings for whisper

### ISSUE THREAD

**Issue by bcl213124314** [huggingface/transformers#26214]
### Feature request

Add the ability to pass custom positional encodings from the generate() call of the ConditionalGeneration model down to the forward() of the WhisperEncoder.

### Motivation

Currently the processor pads the audio input to 3000 mel frames (30 s). Encoding all 3000 frames is the main computational cost of transcribing short audio segments which are a lot shorter than 30 s. The only place where this fixed number of  3000 frames is currently hard coded into the model is:
```
embed_pos = self.embed_positions.weight
hidden_states = inputs_embeds + embed_pos
```

in the forward method of the whisper encoder, since embed_position.weight has a fixed shape. 

Custom positional embeddings would allow the inference of shorter inputs, decreasing the computational cost of the encoding.
Of course that is not what the model was originally trained with and, depending on the custom positional encodings one might use, this changes the output of the model dramatically.
Short tests have shown that just setting 
`embed_pos = self.embed_positions.weight[0:inputs_embeds.shape[1]]`
leads to reasonable predictions.
Better engineered schemes to generate embeddings for shorter inputs might lead to even better results.

### Your contribution

This is a pretty small change and I have implemented it [here](https://github.com/bcl213124314/transformers/tree/encoder_pos_embeddings)

**Comment by ArthurZucker** [comment]
You should have a look at #25744 😉 This is not planned

**Comment by bcl213124314** [comment]
Thanks for the link. Sorry for not searching enough.

**Comment by ArthurZucker** [comment]
No worries 🤗
