### ISSUE TITLE
How does one preprocess a pdf file before passing it into pipeline for summarization?

### ISSUE THREAD

**Issue by pythonvijay** [huggingface/transformers#26220]
Hi,

I think I am unable to read the pdf file in the required format as it runs into an error when I try to read it through PdfReader

here is my code:

```
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
# This only needs to be done once per notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Download a file based on its file ID.
#
# A file ID looks like: laggVyWshwcyP6kEI-y_W3P8D26sz
file_id = "1RjF9CRj8xTQakH5jex1ppBrTw1heHwPS"
downloaded = drive.CreateFile({'id': file_id})
```
it works upto this point...

next, I pass this - 

`print('Downloaded content "{}"'.format(downloaded.GetContentString()))`

and I get this error:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 11: invalid start byte`

and when I try to read the variable 'downloaded' into PdfReader, I again get an error:

`reader = PdfReader(downloaded)`

`AttributeError: 'GoogleDriveFile' object has no attribute 'seek'`

Please advise what I need to correct to make this work!

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests, and less for custom code decoding. Seems like you are not even using transformers here. 
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!

Thanks!

**Comment by pythonvijay** [comment]
This is a pre step to feed the PDF file into a huggingface hosted transformer **T5-base** for text summarization
