### ISSUE TITLE
CodeLlama Tokenizer encoding bug

### ISSUE THREAD

**Issue by jcao-ai** [huggingface/transformers#26239]
### System Info

transformers: 4.33.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

There is one more space than original text, and there is a mismatch in `non-fast` version:
```python
>>> txt = '''[INST] # Python\ndef fibonacci(n): </s><s>[/INST]'''
>>> t_fast = AutoTokenizer.from_pretrained('/models/CodeLlama-34b-Instruct-hf', use_fast=True)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
>>> t_slow = AutoTokenizer.from_pretrained('/models/CodeLlama-34b-Instruct-hf', use_fast=False)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
>>>
>>> t_fast.decode(t_fast.encode(txt))
'<s> [INST] # Python\ndef fibonacci(n): </s><s> [/INST]'
>>>
>>> t_slow.decode(t_slow.encode(txt))
'<s> [INST] # Python\ndef fibonacci(n): </s><s>/INST]'
```

### Expected behavior

Decoded text should be the same as the original text ?

**Comment by shauray8** [comment]
can confirm the inconsistency cc @pacman100 @ArthurZucker, minor differences in tokenization may not significantly impact the final results though.
