### ISSUE TITLE
Pipeline error when creating a model without a model card json file (on Windows)

### ISSUE THREAD

**Issue by AlecS12** [huggingface/transformers#2625]
## 🐛 Bug

Model I am using (Bert, XLNet....):
Bert
Language I am using the model on (English, Chinese....):
English
The problem arise when using:
* [ ] the official example scripts: (give details)
* [x] my own modified scripts: (give details)
```python
import sys
from transformers import pipeline

if __name__ == '__main__':
    print("start")
    nlp_ft = pipeline('question-answering', model=r'C:\Users\a652726\PycharmProjects\src\data\raw\qa\wwm-bert-uncased-finetuned-squad',
                      tokenizer='bert-large-uncased')
```

Results in the ValueError: no modelcard.json file (which i do not have)
My  fix (hack):
In modelcard.py replace (line 164):

```python
        except EnvironmentError:
            if pretrained_model_name_or_path in ALL_PRETRAINED_CONFIG_ARCHIVE_MAP:
```
with
```python
        except (EnvironmentError, ValueError):
            if pretrained_model_name_or_path in ALL_PRETRAINED_CONFIG_ARCHIVE_MAP:
```
This results in:

```python
            logger.warning("Creating an empty model card.")
```
And everything works fine after this.

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x ] my own task or dataset: (give details)
 Changing QA pipeline to work on a fixed set of spans (like multiple choice QA task, or classification)

## To Reproduce

1.
2.
3.

## Environment

* OS:  Windows
* Python version: 3.7
* PyTorch version: 1.3
* PyTorch Transformers version (or branch): master (post 2.3)
* Using GPU ? no
* Distributed or parallel setup ? no
* Any other relevant information:

**Comment by BramVanroy** [comment]
Please format your post correctly by using code blocks. https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
