### ISSUE TITLE
Uninitialized token embeddings MBART when using device_map

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#26266]
### System Info

Current master

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Loading a finetuned model's safetensors with device_map=auto, I get a warning that the tied embeddings are not initialized.

> Some weights of MBartForConditionalGeneration were not initialized from the model checkpoint and are newly initialized: ['model.decoder.embed_tokens.weight', 'model.encoder.embed_tokens.weight']

I finetuned an MBART model with the trainer, use_safetensors was set to True. The model's vocabulary (embedding size) was extended, maybe that matters.

```python
from transformers import AutoModelForSeq2SeqLM
# Works:
model = AutoModelForSeq2SeqLM.from_pretrained("BramVanroy/mbart_test")
# Does not work (tied embeddings not loaded correctly - triggers a warning)
model = AutoModelForSeq2SeqLM.from_pretrained("BramVanroy/mbart_test", device_map="auto")
```

It is not just the warning, it seems actually the case that the weights are not loaded correctly (random output).

### Expected behavior

Correctly loaded safetensors

**Comment by LysandreJik** [comment]
I've traced this to the definition of the ` find_tied_parameters` function from `accelerate`.

In `transformers` we have a control flow to identify tied parameters that does not work for `meta` tensors; if we identify a `meta` tensor, we then rely on the `find_tied_parameters` function from `accelerate`. There seems to be a discrepancy in the number of layers returned by these two methods here, depending on whether we'reusing a `device_map` or not:

https://github.com/huggingface/transformers/blob/0ac3875011d32dc85e0e83970507e3afe8f0febb/src/transformers/modeling_utils.py#L3471-L3481

@SunMarc, would you like to investigate what might be going on here?

**Comment by SunMarc** [comment]
Yes @LysandreJik , I will check that is going on.
