### ISSUE TITLE
Transformers breaks when running setup.py

### ISSUE THREAD

**Issue by AdamLouly** [huggingface/transformers#26276]
### System Info

Running `python setup.py install` in transformers folder throws this error:

error: huggingface-hub 0.17.2 is installed but huggingface_hub<0.17,>=0.16.4 is required by {'tokenizers'}

This starts happening after merging this PR where line 175 was changed from:
from    "tokenizers>=0.11.1,!=0.11.3,<0.14",
to    "tokenizers>=0.14,<0.15",

https://github.com/huggingface/transformers/issues/23909

when I change it back manually it works fine.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running `python setup.py install` in transformers folder

### Expected behavior

error: huggingface-hub 0.17.2 is installed but huggingface_hub<0.17,>=0.16.4 is required by {'tokenizers'}

**Comment by ArthurZucker** [comment]
A quick fix: update `huggingface_hub` . On our side we should update the dependency requirement. Thanks for reporting!

**Comment by AdamLouly** [comment]
@ArthurZucker  have you tested re installing Transformers after this update?
I tested and its still failing.

huggingface-hub>=0.16.4,<1.0 won't solve the issue: 
huggingface_hub<0.17,>=0.16.4 is required by {'tokenizers'}

because its installing huggingface_hub 0.17.4 and that will break it.

**Comment by ArthurZucker** [comment]
I think tokenizers has to be updated at this point, since it's not using the latest dependency. cc @Narsil any reason why we limited to HF hub 0.17?

**Comment by AdamLouly** [comment]
@ArthurZucker Any updates on this?

**Comment by ArthurZucker** [comment]
Yep, this [PR](https://github.com/huggingface/tokenizers/pull/1344) was merged in tokenizers, we just need a release and this will be adressed
