### ISSUE TITLE
Why not use model_wrapped in trainer evaluation_loop?

### ISSUE THREAD

**Issue by tangzhiyi11** [huggingface/transformers#26282]
### System Info

Transformers >= 4.30.2.

### Who can help?

@muellerzr @pacman100 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Why not use model_wrapped in trainer evaluation_loop?

![image](https://github.com/huggingface/transformers/assets/5955111/9aae5ff8-51d8-4953-ab1c-7b0e27af64d0)

### Expected behavior

like #26281

**Comment by ArthurZucker** [comment]
correcting the ping to @pacman100 😉

**Comment by tangzhiyi11** [comment]
> correcting the ping to @pacman100 😉

thanks, i fix it
