### ISSUE TITLE
LLamaV2 tokenizer prepare_for_model produces different results for fast and slow tokenizers

### ISSUE THREAD

**Issue by zerogerc** [huggingface/transformers#26287]
### System Info

transformers==4.33.2

Hi, I noticed that LlamaV2 tokenizer produces different results depending on whether is_fast is enabled or not:

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Here is a code snippet:

```

    tokenizer_fast = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", use_fast=True)
    tokenizer_slow = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", use_fast=False)

    print(tokenizer_fast.prepare_for_model([100, 200, 300])["input_ids"])
    >>> [100, 200, 300]
    print(tokenizer_slow.prepare_for_model([100, 200, 300])["input_ids"])
    >>> [1, 100, 200, 300]
```

### Expected behavior

The results should be the same

**Comment by ArthurZucker** [comment]
Yep, this is because `prepare_input_for_model` uses the `build_inputs_with_special_tokens`, which was remove from LlamaFast as using the template processor is the favoured way to go. I'll add it back for now, good catch!
