### ISSUE TITLE
Speedup module imports

### ISSUE THREAD

**Issue by apoorvkh** [huggingface/transformers#26308]
### Feature request

Can we please consider importing the deepspeed module when needed, rather than in the [import header of `trainer.py`](https://github.com/huggingface/transformers/blob/e3a4bd2bee212a2d0fd9f03b27fe7bfc1debe42d/src/transformers/trainer.py#L217)?

### Motivation

When `deepspeed` is installed, `from transformers import Trainer` takes a long time!

On my system that's 9 seconds!

```python
>>> import timeit; timeit.timeit("from transformers import Trainer")
[2023-09-20 23:49:13,899] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
8.906949461437762
```

I believe this import is the culprit. As we can see, it takes 8.5 seconds of the load time.

https://github.com/huggingface/transformers/blob/e3a4bd2bee212a2d0fd9f03b27fe7bfc1debe42d/src/transformers/trainer.py#L217

```python
>>> timeit.timeit("from accelerate.utils import DeepSpeedSchedulerWrapper")
[2023-09-20 23:45:53,185] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
8.525534554384649
```

This is quite cumbersome, because all scripts that import Trainer (e.g. even for typing) are impacted!

### Your contribution

Happy to submit a PR. We could make this a class variable or just import it directly at both places it's used.

https://github.com/huggingface/transformers/blob/e3a4bd2bee212a2d0fd9f03b27fe7bfc1debe42d/src/transformers/trainer.py#L2437-L2439

https://github.com/huggingface/transformers/blob/e3a4bd2bee212a2d0fd9f03b27fe7bfc1debe42d/src/transformers/trainer.py#L2508-L2514

**Comment by ArthurZucker** [comment]
Hey! Thanks for opening this issue, are you using `main`. There was a PR recently to fix this, see #26090 and #26106

**Comment by apoorvkh** [comment]
I am indeed using main (specifically, `transformers[deepspeed]` at commit 382ba67)!

**Comment by apoorvkh** [comment]
The code I mentioned above is run directly in the header of `trainer.py`. And, if I understand correctly, I think `accelerate` is not covered by the Lazy imports in #26090.

https://github.com/huggingface/transformers/blob/e3a4bd2bee212a2d0fd9f03b27fe7bfc1debe42d/src/transformers/trainer.py#L203-L217

**Comment by ArthurZucker** [comment]
Cc @younesbelkada I think you mentioned that accelerate is the bottleneck that we can’t get rid of no?

**Comment by younesbelkada** [comment]
Hi @apoorvkh 
https://github.com/huggingface/accelerate/pull/1963 being merged in accelerate I think you can switch to accelerate main and see if it resolves your issue

**Comment by apoorvkh** [comment]
Hey, thanks! I think that commit (https://github.com/huggingface/accelerate/commit/5dec654aaea0c92d4ccb7ad389fc33adcbbf79fc) reduces the runtime for the import from 8-9 seconds to 3-4 seconds (on my machine). That is still not ideal but is certainly more tolerable.

**Comment by younesbelkada** [comment]
Thanks!  
Hm I see ok, I am curious what module takes so much time for import, would you be able to run a quick benchmark with [`tuna`](https://github.com/nschloe/tuna)? 

```bash
# benchmark
python -X importtime -c "import transformers" 2> transformers-import-profile.log

# visualize
tuna <path to log file>
```

**Comment by apoorvkh** [comment]
For sure. That's a nice tool!

Really quickly, I found that `from transformers import Trainer` was particularly taking 4 seconds to import -- whereas `import transformers` is actually faster (1 second).

We can see the result for `from transformers import Trainer` below:

![image](https://github.com/huggingface/transformers/assets/7005565/f3f54bc3-69d0-4d92-8e14-f9bd2d43317b)

And we can compare to `import transformers`:

![image](https://github.com/huggingface/transformers/assets/7005565/bb0ba6f5-16c1-489a-9c90-c5c609564ed2)

Seems like `accelerate` is no longer the culprit. A lot of time is spent importing `torch`.
