### ISSUE TITLE
[example/recipe request] CodeLlama supervised fine tuning for infilling

### ISSUE THREAD

**Issue by alexpeys** [huggingface/transformers#26306]
### Feature request

I am interested in fine tuning CodeLlama 7/13B to do some infilling.

I have data that I want to fine tune on of the form: {prefix} {suffix} {middle}

I am trying to understand how to format my supervised fine tuning dataset.

Should I be setting up my fine tuning data as:
```
prompt="_<PRE> {prefix} _<SUF> {suffix} _<MID>", completion="{middle} ▁<EOT>"

or

prompt="{prefix} <FILL_ME> {suffix}", completion="{middle} ▁<EOT>"

or

some secret third thing
```
The documentation https://huggingface.co/docs/transformers/main/model_doc/code_llama#transformers.CodeLlamaTokenizer seems to suggest that the second will work and the tokenizer will do all the token healing etc... as it does for generation, but I am not sure.

### Motivation

Fine tuning for infilling is a little trickier than just standard PROMPT, RESPONSE fine tuning!

### Your contribution

Happy to write a basic example script if someone wants to guide me through the correct way to structure the prompt given the CodeLlamaTokenizer.

**Comment by lch20030102** [comment]
……

**Comment by ArthurZucker** [comment]
Hey! Feel free to share your code on the hub! It's the best way I believe to share something like this 😉 You should even be able to write a `Community Blogpost` !

Regarding the format, the tokenizer will format the prompt 1. if you give it `"{prefix} <FILL_ME> {suffix}"`. The target probably needs what you mentioned: `"{middle} ▁<EOT>"`

**Comment by Kushalamummigatti** [comment]
@alexpeys Hi... do you have any basic script or initial scribbled idea to achieve this? Am trying to finetune codellama for infilling task. It would be helpful.
