### ISSUE TITLE
Order of  `loss/gradient_accumulation_steps` and `backward(loss)`

### ISSUE THREAD

**Issue by haoxiangsnr** [huggingface/transformers#26312]
### System Info

Hi, @muellerz @pacman100 . I have a question about the gradient accumulation. Should we divide the `gradient_accumulation_steps` before `accelerator.backward(loss)`?

https://github.com/huggingface/transformers/blob/e3a4bd2bee212a2d0fd9f03b27fe7bfc1debe42d/src/transformers/trainer.py#L2787

It seems that `self.accelerator.accumulate(model)` [here](https://github.com/huggingface/transformers/blob/e3a4bd2bee212a2d0fd9f03b27fe7bfc1debe42d/src/transformers/trainer.py#L1889C17-L1889C57) is just a wrapper for `no_sync()` and will not automatically help divide the loss by the `gradient_accumulation_steps`.

**Comment by muellerzr** [comment]
Accelerate will also divide the loss if `accelerator.backward(loss)` is used, so it should already be done in https://github.com/huggingface/transformers/blob/e3a4bd2bee212a2d0fd9f03b27fe7bfc1debe42d/src/transformers/trainer.py#L2785. The return is just for the metrics
