### ISSUE TITLE
CamembertTokenizer cannot be pickled

### ISSUE THREAD

**Issue by GMarzinotto** [huggingface/transformers#2631]
## 🐛 Bug

Model I am using (Bert, XLNet....):  Camembert

Language I am using the model on (English, Chinese....): French

The problem arise when using my own modified scripts: 
  I have a nn.Module and, within this module, I store the tokenizers
  I can normally save these tokenizers easily, but CamemberTokenizer
  gives me a  **TypeError: can't pickle SwigPyObject objects** 

The tasks I am working on consists in creating a model and saving it using torch.save()

## To Reproduce
```
import torch
from transformers import  CamembertTokenizer, BertTokenizer

class MyModelCamembert(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.cheese =  CamembertTokenizer.from_pretrained('camembert-base') 

    def forward(self, x):
        return 1


class MyModelBert(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.cheese = BertTokenizer.from_pretrained('bert-base')

    def forward(self, x):
        return 1
        

# with bert it works
no_cheese = MyModelBert()
torch.save(no_cheese, "~/bert.pkl")

# with camembert it doesn't
cheese = MyModelCamembert()
torch.save(cheese, "~/camembert.pkl")
```

1. Try to save a module containing a tokenizer using the torch.save()
2. Find out it works for Bert but not for Camembert

Stack Trace when saving CamembertTokenizer

Traceback (most recent call last):
  File "/home/swqh0332/Desktop/blablapy.py", line 28, in <module>
    torch.save(cheese, "/home/swqh0332/camembert.pkl")
  File "/home/swqh0332/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 260, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/swqh0332/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 185, in _with_file_like
    return body(f)
  File "/home/swqh0332/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 260, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/swqh0332/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 332, in _save
    pickler.dump(obj)
TypeError: can't pickle SwigPyObject objects

## Expected behavior

I would like to be able to pickle the CamembertTokenizer as I it is possible with the other models

## Environment

* OS: Ubuntu 18
* Python version: 3.6.9
* PyTorch version: 1.3.1
* PyTorch Transformers version (or branch): 2.2.2
* Using GPU ? No
* Distributed or parallel setup ? No

**Comment by julien-c** [comment]
Did you look into just calling `save_pretrained()` on your CamembertTokenizer (and not include it inside your `MyModelCamembert`)?

**Comment by GMarzinotto** [comment]
No I did not try that because my model class is quite a big class that extends `nn.Module` and not `PreTrainedModel`. 
I'm just surprised that saving the model it works for Bert but fails for Camembert

**Comment by LysandreJik** [comment]
Indeed, there was the state management lacking in the CamemBERT tokenizer, so it couldn't be pickled. It should have been fixed with 908230d.

**Comment by GMarzinotto** [comment]
Great !  So I'll just wait for the next release, Thanks ! :))

**Comment by LysandreJik** [comment]
You can also install from source using `pip install git+https://github.com/huggingface/transformers` if you want to work with it now
