### ISSUE TITLE
TensorBoard integration on huggingface

### ISSUE THREAD

**Issue by omermazig** [huggingface/transformers#26321]
### System Info

I'm running a somewhat changed version of [this](https://github.com/huggingface/notebooks/blob/main/examples/video_classification.ipynb) tutorial, and somewhere last month.

As the tutorial explains, it used to be that when I ran `push_to_hub`, a TensorBoard was created and appeared under the model page on huggingface:

![image](https://github.com/huggingface/transformers/assets/95534441/af510d37-4641-4ad0-8669-7da18b64e90b)

But lately I've noticed that it has stopped generating that tab. I have two runs from the 20 and 24 of Aug, where the tab appears in the former and doesn't appear in the latter:

https://huggingface.co/omermazig/videomae-base-finetuned-kinetics-finetuned-nba-data-8-batch-5-epochs-dataset_10_classes
https://huggingface.co/omermazig/videomae-base-kinetics-finetuned-nba-binary-data-2-batch-50-epochs-399-train-vids-multilabel

You can see that the transformer's verion updated from `4.31.0` to `4.32.0`.  All runs before these two had a `Training Metrics` tab, and all runs after them didn't.

Is it possible that the integration was broken on `4.32.0`? How can I further investigate that?

Thanks!

### Who can help?

@Rocketknight1

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Run this notebook:

https://github.com/huggingface/notebooks/blob/main/examples/video_classification.ipynb

### Expected behavior

Creation of a `Training Metrics` tab on huggingface

**Comment by ArthurZucker** [comment]
cc @Rocketknight1 our TF expert!

**Comment by LysandreJik** [comment]
Hmmm indeed it seems like there is an issue with `runs` not being saved. I don't think that's related to TensorFlow but rather to the `Trainer`. 

@pacman100 could you please give this issue a look? Thank you!

**Comment by omermazig** [comment]
This issue has gone stale even though it still needs to be addressed, so I'm commenting to bump it as instructed

**Comment by muellerzr** [comment]
Thanks, this will be solved with #27022 as long as you do `trainer.push_to_hub()`
