### ISSUE TITLE
transformer bark error

### ISSUE THREAD

**Issue by wanglg007** [huggingface/transformers#26337]
### System Info

transformer bark error

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. use transformer's bark
2. python 3.8

### Expected behavior

![image](https://github.com/huggingface/transformers/assets/40556406/809535e1-a1fd-4a75-9720-bfd1ffe3cd06)

**Comment by ArthurZucker** [comment]
Hey! According to the contribution guidelines we need a full reproducer to be able to help you!
