### ISSUE TITLE
[LLM Tokenizer] Tokenizer loads too slowly

### ISSUE THREAD

**Issue by Sakurakdx** [huggingface/transformers#26375]
When I use LLM such as LLAMA's tokenzier, its loading speed is very slow, even taking half an hour. I would like to ask how long is the normal loading time and is there any way to speed up the loading?

**Comment by LysandreJik** [comment]
Hey @Sakurakdx, by "loading speed", are you talking about the model or the tokenizer? Would you have a reproducible code snippet I could try to see what you mean?

**Comment by Sakurakdx** [comment]
Sorry, my statement may not be accurate. The following is a clarification: When I use `AutoTokenizer` to load the tokenzier of LLAMA2, I need to wait for a long time.

```python
tokenizer = AutoTokenizer.from_pretrained("chinese-llama-2-7b", fast=True, trust_remote_code=True)
```

**Comment by LysandreJik** [comment]
Do you mind trying to install from main to see if it fixes your issue? You can do so with:
```
pip uninstall transformers
pip install git+https://github.com/huggingface/transformers
```

**Comment by Sakurakdx** [comment]
Thank you this is super helpful!
