### ISSUE TITLE
Bug in Trainer for PeftModel multi-gpu training by accelerate

### ISSUE THREAD

**Issue by Orion-Zheng** [huggingface/transformers#26378]
### System Info

When using the accelerate library to fine-tune LLaMA2 by QLoRA on multiple GPUs, I met an error when I set load_best_model_at_end=True in the TrainingArguments. 
<img width="1115" alt="image" src="https://github.com/huggingface/transformers/assets/62330719/a2e7a49b-3627-4249-8fb2-bc8a61f0ede1">
It seems the function '_load_best_model' try to find the weight of the complete model under the peft model's checkpoint dir, but actually there is only adapter's weight saved in this directory.
<img width="350" alt="image" src="https://github.com/huggingface/transformers/assets/62330719/ecbd2f7c-8230-4e63-8265-11ba790e03e7">
I try to find the reason behind the error. I notice that the best peft model should be loaded by these lines of code in '_load_best_model',
<img width="1273" alt="image" src="https://github.com/huggingface/transformers/assets/62330719/e06fbcee-035d-458a-b348-82f783d1a073">
but in the multi-gpu training, the trainer execute another code, which is not intended for the peft model's checkpoint.
<img width="1110" alt="image" src="https://github.com/huggingface/transformers/assets/62330719/21bf760b-a208-4a91-b718-d6aec13dbf39">
But why the correct code is skipped? I finally found the reason.
In multi-GPU code, the Peft Model was wrapped into DistributedDataParallel that looks like:
DistributedDataParallel( 
  (module): PeftModelForCausalLM(
which makes 'model' is not a PeftModel anymore, so this condition can't be satisfied and the correct code is skipped
<img width="1113" alt="image" src="https://github.com/huggingface/transformers/assets/62330719/52035c34-5c19-4bfd-a68c-83a7b542ca82">
To solve this problem, I add some code to this function. I know this is not a elegant way, but it works for me.
<img width="1106" alt="image" src="https://github.com/huggingface/transformers/assets/62330719/3bbbb438-4b69-46c8-9c48-a7dbd1dcd956">
Besides, I think the original Trainer didn't consider training PeftModel on multiple GPUs well, which also lead to other bugs in the Trainer.save_model when doing multi-gpu training for peft model. Because I don't have enough time to read all of the code of Trainer, I can't solve this problem by myself. So could anyone work on this? Thank you very much!😃

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Transformer Version: 4.31.0
(sorry, my code consists of several files. I'll attach them to this issue once I've organized them into one.)

### Expected behavior

The PeftModel can be saved and load correctly by the Trainer during multi gpu training.

**Comment by ArthurZucker** [comment]
Hey! Would recommend you to update to the latest version of both packages and see if this is fixed!

**Comment by younesbelkada** [comment]
Thanks! Will look into it
