### ISSUE TITLE
Use github.com/apssouza22/chatflow as a conversational layer. It would enable actual API requests to be carried out from natural language inputs.

### ISSUE THREAD

**Issue by GiovanniSmokes** [huggingface/transformers#26373]
### Feature request

Adding this conversational UI would enable people to 'talk' directly with the backend and API requests to be carried out more effectively. RAG can help with some of the problems function calling by language models face at the moment.

https://youtu.be/r3cegH2kviQ

### Motivation

I'm trying to accelerate the adoption of natural language interfaces.

### Your contribution

We're developing in public in our Discord and we would love for you guys to join us.

**Comment by LysandreJik** [comment]
Hey @GiovanniSmokes, we're happy to provide support in case you would like to integrate `transformers` within `chatflow`. 

We have a lot of requests so we prefer to centralize everything in our GitHub issues, feel free to open an issue in case you run into problems! Thank you :hugs:
