### ISSUE TITLE
4.33.2 breaks deepspeed_custom_scheduler fixed in 4.33.1

### ISSUE THREAD

**Issue by wizyoung** [huggingface/transformers#26384]
### System Info

- `transformers` version: 4.33.2
- Platform: Linux-4.14.0_1-0-0-44-x86_64-with-glibc2.27
- Python version: 3.9.17
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: 0.23.0
- Accelerate config:    not found
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@muellerzr @pacman100
4.33.1 fixed the deepspeed_custom_scheduler in https://github.com/huggingface/transformers/commit/6bc517ccd4a3bcda4d0621d54a37c3e047df223a, however, the 4.33.2 patch release broke it again.

4.33.1:
https://github.com/huggingface/transformers/blob/fa6107c97edf7cf725305a34735a57875b67d85e/src/transformers/trainer.py#L2367-L2380
vs broken 4.33.2:
https://github.com/huggingface/transformers/blob/6da93f5580e109fad5f7b523cf2b6e8a5bafb623/src/transformers/trainer.py#L2364-L2370

4.33.1:
https://github.com/huggingface/transformers/blob/fa6107c97edf7cf725305a34735a57875b67d85e/src/transformers/trainer.py#L2434-L2445
vs broken 4.33.2:
https://github.com/huggingface/transformers/blob/6da93f5580e109fad5f7b523cf2b6e8a5bafb623/src/transformers/trainer.py#L2424-L2431

In version 4.33.2, if we use HF lr_scheduler and have deepspeed enabled, the lr_scheduler cannot be saved and loaded normally. This is a huge affect that breaks large scale training-pause-resuming loop. Considering 4.33.2 fixes two critical issues, I suggest release a new patch as this bug affects more people.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

100%

### Expected behavior

A new patch release.

**Comment by wizyoung** [comment]
Weird... The github 4.33.1 tag fixed the bug as I mentioned above, but the pypi release 4.33.1 src code still lies the bug, which is inconsistent.

**Comment by pacman100** [comment]
Hello @wizyoung, this should be fixed in https://github.com/huggingface/transformers/releases/tag/v4.33.3
