### ISSUE TITLE
`resize_token_embeddings` sets `vocab_size` to 0 in Deepspeed mode.

### ISSUE THREAD

**Issue by zhouku92** [huggingface/transformers#26398]
### System Info

**System Info**
* transformers==4.33.2
* accelerate==0.23.0
* deepspeed==0.9.2

I was running a customized script to train a LLaMA model via Deepspeed and encountered the following exception:
```
File "/opt/conda/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1736, in forward
    shift_logits = shift_logits.view(-1, self.config.vocab_size)
RuntimeError: shape '[-1, 0]' is invalid for input of size 32705022

```

A quick check directs me to the following block ([link](https://github.com/huggingface/transformers/blob/v4.33.2/src/transformers/modeling_utils.py#L1439)):
```
    def resize_token_embeddings(
        self, new_num_tokens: Optional[int] = None, pad_to_multiple_of: Optional[int] = None
    ) -> nn.Embedding:
        model_embeds = self._resize_token_embeddings(new_num_tokens, pad_to_multiple_of)
        if new_num_tokens is None and pad_to_multiple_of is None:
            return model_embeds

        # Update base model and current model config
        self.config.vocab_size = model_embeds.weight.shape[0]
        self.vocab_size = model_embeds.weight.shape[0]

        # Tie weights again if needed
        self.tie_weights()

        return model_embeds
```
In Deepspeed, `model_embeds` is `Embedding(32001, 4096)` but `model_embeds.weight` is `torch.Size([0])` (per my understanding, the model hasn't been initialized yet). Thus, `self.config.vocab_size` is mistakenly set to `0`.

**Who can help?**
@pacman100

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```py
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("llama-path")
model.resize_token_embeddings(new_num_tokens=32001, pad_to_multiple_of=None)
```

Run with  deepspeeed

### Expected behavior

`self.config.vocab_size` and `self.vocab_size` should  be set to the correct number. Personally `model_embeds.num_embeddings` is better than `model_embeds.weight.shape[0]`.

**Comment by weixi-feng** [comment]
Same issue here with save package versions except deepspeed==0.10.3. Downgrading transformers to 4.30.2 temporarily resolved the issue.

**Comment by LysandreJik** [comment]
Indeed, it seems there is an issue here! Would you mind opening a PR with your proposed fix?

**Comment by LysandreJik** [comment]
Ah actually it's already being fixed here: https://github.com/huggingface/transformers/pull/26387

**Comment by pacman100** [comment]
Hello @weixi-feng, this merged PR https://github.com/huggingface/transformers/pull/26259 should have fixed the issue . Could you retry with the main branch?

**Comment by weixi-feng** [comment]
Yes, the main branch works for me. Thanks for the quick follow-up.

**Comment by zhouku92** [comment]
Thank you, it works for me.
