### ISSUE TITLE
batch_encode_plus not working for GPT2, OpenAI, TransfoXL when returning PyTorch tensors

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#2640]
## 🐛 Bug

`batch_encode_plus` does not work on GPT2, OpenAI, and TransfoXL when returning PyTorch tensors. Note that the code does work when leaving out the `return_tensors` argument. In that case, the output of `encoded` looks normal.

## To Reproduce
```python
from transformers import *

TOKENIZERS = {
    'albert': (AlbertTokenizer, 'albert-base-v1'),
    'bert': (BertTokenizer, 'bert-base-uncased'),
    'distilbert': (DistilBertTokenizer, 'distilbert-base-uncased'),
    'gpt2': (GPT2Tokenizer, 'gpt2'),
    'openai': (OpenAIGPTTokenizer, 'openai-gpt'),
    'roberta': (RobertaTokenizer, 'roberta-base'),
    'transfoxl': (TransfoXLTokenizer, 'transfo-xl-wt103'),
    'xlm': (XLMTokenizer, 'xlm-mlm-enfr-1024'),
    'xlnet': (XLNetTokenizer, 'xlnet-base-cased')
}

text = ['I like bananas and cookies .',
        'You are not what I thought you were , though .',
        'Cookies are awesome .']

for tok_name, (tok_cls, tok_default) in TOKENIZERS.items():
    tokenizer = tok_cls.from_pretrained(tok_default)
    try:
        encoded = tokenizer.batch_encode_plus(text, return_tensors='pt')
    except Exception as e:
        print(f"{tok_name} failed: {e}")
```

Output on latest master:

```
gpt2 failed: Could not infer dtype of NoneType
openai failed: Could not infer dtype of NoneType
transfoxl failed: Could not infer dtype of NoneType
```

## Environment

* OS: Windows 10
* Python version: 3.7.3
* PyTorch version: 1.3
* PyTorch Transformers version (or branch): latest master
* Using GPU ? yes
* Distributed or parallel setup ? no

**Comment by BramVanroy** [comment]
The problem lies here

https://github.com/huggingface/transformers/blob/babd41e7fa07bdd764f8fe91c33469046ab7dbd1/src/transformers/tokenization_utils.py#L1003-L1006

since for these tokenizers `self.pad_token_id` is None.

**Comment by mikygit** [comment]
Still having this issue running the above script :-(
Any ideas?

Env:
* OS: Windows 10
* Python version: 3.6.12
* PyTorch version: 1.5.0
* PyTorch Transformers version (or branch): transformers-4.5.1
* Using GPU ? yes
* Distributed or parallel setup ? no
