### ISSUE TITLE
Use a custom SummaryWriter to record training parameters

### ISSUE THREAD

**Issue by young-chao** [huggingface/transformers#26408]
When I use trainer, how should I use a custom SummaryWriter to record training parameters, such as grad_norm, loss_scale, etc.  I don’t see the setting options in the trainer parameters.

**Comment by LysandreJik** [comment]
Hello @young-chao, the `Trainer`'s initialization method accepts a `callbacks` argument which is a list of `TrainerCallback`s.

You can pass a `TensorBoardCallback` to that list that you can initialize with your own `tb_writer`.

See its definition here: https://github.com/huggingface/transformers/blob/0ac3875011d32dc85e0e83970507e3afe8f0febb/src/transformers/integrations/integration_utils.py#L579

**Comment by young-chao** [comment]
I will try it, thanks for your reply.

**Comment by young-chao** [comment]
> Hello @young-chao, the `Trainer`'s initialization method accepts a `callbacks` argument which is a list of `TrainerCallback`s.
> 
> You can pass a `TensorBoardCallback` to that list that you can initialize with your own `tb_writer`.
> 
> See its definition here:
> 
> https://github.com/huggingface/transformers/blob/0ac3875011d32dc85e0e83970507e3afe8f0febb/src/transformers/integrations/integration_utils.py#L579

I will try it, thanks for your reply
