### ISSUE TITLE
Flash Attention 2 support for BERT, DistilBERT, and T5

### ISSUE THREAD

**Issue by AmenRa** [huggingface/transformers#26424]
Hi and thanks for adding Flash Attention 2!

I was wondering if there's any plan to add support for Flash Attention 2 to BERT, DistilBERT, and T5 models.
Those models are still the go-to Transformer models in my research community (Information Retrieval).
Reducing training/inference time and memory usage of those models would be extremely helpful for many researchers and practitioners.

Thank you!

Elias

**Comment by LysandreJik** [comment]
Hey @AmenRa you might be interested in this issue: https://github.com/huggingface/transformers/issues/26350

cc @younesbelkada

**Comment by younesbelkada** [comment]
Thanks for your interest @AmenRa, I have just added these architectures to the list in #26350

**Comment by AmenRa** [comment]
@LysandreJik thanks for the fast reply.
@younesbelkada thanks for adding the models to your list.

**Comment by Ingvarstep** [comment]
For anyone who is interested in optimized T5 version, I just finished my project on creating flash attention version with fused attention bias calculation. It allows to fix the major drawbacks of T5 and allow to run it on 100k sequences on single L4 GPU (22.5 GB). Check it  [here](https://github.com/Knowledgator/TurboT5).

**Comment by forrestbao** [comment]
I am in a desperate need for FA on T5 to be officially supported in `transformers`.
