### ISSUE TITLE
pretrained_model_name_or_path cannot be None

### ISSUE THREAD

**Issue by rahaazad2** [huggingface/transformers#26429]
### System Info

- `transformers` version: 4.33.2
- Platform: Linux-5.4.0-147-generic-x86_64-with-glibc2.31
- Python version: 3.11.4
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.23.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Who can help?

@ArthurZucker
@younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I have a pre-trained model that I want to load it from its state-dict. I use the following code:

    model_class = getattr(transformers, 'XLMRobertaForSequenceClassification')
    model = model_class.from_pretrained(
            pretrained_model_name_or_path=None,
            config=model_type,
            num_labels=num_classes,
            state_dict=state_dict,
       )

This code was working on transformer version 4.22.1. However, after upgrading to version 4.33.2, I get this error:

    OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
    If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

### Expected behavior

I expect the model to be loaded from state_dict.

**Comment by younesbelkada** [comment]
Thanks for reporting, can you share the full traceback?

**Comment by rahaazad2** [comment]
Sure, here is the complete traceback:

    Traceback (most recent call last):
      File "/code/my_model.py", line 239, in <module>
        model, labels = load_model(args.model)
                        ^^^^^^^^^^^^^^^^^^^^^^
      File "/code/my_model.py", line 105, in load_model
        model = MyModel('my_model_name', device='cuda')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/model_loader.py", line 111, in __init__
        self.model, self.tokenizer, self.class_names = load_checkpoint(
                                                       ^^^^^^^^^^^^^^^^
      File "/code/model_loader.py", line 100, in load_checkpoint
        model, tokenizer = get_model_and_tokenizer(
                           ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/model_loader.py", line 66, in get_model_and_tokenizer
        model = model_class.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/raha/.conda/envs/myenv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2389, in from_pretrained
        resolved_config_file = cached_file(
                               ^^^^^^^^^^^^
      File "/home/raha/.conda/envs/myenv/lib/python3.11/site-packages/transformers/utils/hub.py", line 450, in cached_file
        raise EnvironmentError(
    OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
    If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

**Comment by harper-carroll** [comment]
I'm getting this bug too

**Comment by younesbelkada** [comment]
Hi @rahaazad2 
Thanks for the issue, I tried to reproduce locally but with no success:
```python
import torch
from transformers import AutoModel, AutoConfig

from huggingface_hub import hf_hub_download

model_id = "bert-base-uncased"

config = AutoConfig.from_pretrained(model_id)
state_dict = torch.load(hf_hub_download(model_id, revision="main", filename="pytorch_model.bin"))

model = AutoModel.from_pretrained(
    pretrained_model_name_or_path=None, 
    config=config, 
    state_dict=state_dict
)
```
The script above works fine on my end, if you say that the script was working before and not anymore it is definitely a bug, can you help me with a simple reproducible snippet?

**Comment by kraktus** [comment]
Hello, a reproducible code snippet was provided: https://github.com/unitaryai/detoxify/pull/93#issuecomment-1776229505

```py
# works
config = AutoConfig.from_pretrained(model_type, num_labels=num_classes)
model = model_class.from_pretrained(
      pretrained_model_name_or_path=None,
      config=huggingface_config_path or config,
      state_dict=state_dict,
      local_files_only=huggingface_config_path is not None,
  )
```

```py
# doesn't work
config = model_class.from_pretrained(model_type, num_labels=num_classes)
model = model_class.from_pretrained(
      pretrained_model_name_or_path=None,
      config=huggingface_config_path or config,
      state_dict=state_dict,
      local_files_only=huggingface_config_path is not None,
  )
```

**Comment by younesbelkada** [comment]
Hi @kraktus ! I managed to reproduce with this script:

```python
import torch
from transformers import AutoModel, AutoConfig
from huggingface_hub import hf_hub_download

model_id = "bert-base-uncased"
num_classes = 2
model_class = AutoModel

state_dict = torch.load(hf_hub_download(model_id, revision="main", filename="pytorch_model.bin"))
huggingface_config_path = None

config = model_class.from_pretrained(model_id, num_labels=num_classes)
model = model_class.from_pretrained(
      pretrained_model_name_or_path=None,
      config=huggingface_config_path or config,
      state_dict=state_dict,
      local_files_only=huggingface_config_path is not None,
  )
```

But note this is **totally** expected, you are passing a `AutoModel` as a `config` argument. Maybe we should error out a better error message there. The code will try to be executed here: https://github.com/huggingface/transformers/blob/main/src/transformers/models/auto/auto_factory.py#L488 since the check `if not isinstance(config, PretrainedConfig):` fails.

The fix is to replace `model_class` with `AutoConfig` to correctly pass a config object:

```diff
import torch
from transformers import AutoModel, AutoConfig
from huggingface_hub import hf_hub_download

model_id = "bert-base-uncased"
num_classes = 2
model_class = AutoModel

state_dict = torch.load(hf_hub_download(model_id, revision="main", filename="pytorch_model.bin"))
huggingface_config_path = None

+ config = AutoConfig.from_pretrained(model_id, num_labels=num_classes)
model = model_class.from_pretrained(
      pretrained_model_name_or_path=None,
      config=huggingface_config_path or config,
      state_dict=state_dict,
      local_files_only=huggingface_config_path is not None,
  )
```

Let me know if this makes sense
