### ISSUE TITLE
Inject the optimum.bettertransformer to trainer to accelerate training

### ISSUE THREAD

**Issue by DongHande** [huggingface/transformers#26436]
### Feature request

Inject the optimum (https://huggingface.co/docs/optimum/main/en/bettertransformer/tutorials/convert#training-compatibility) to the trainer API (https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py). 

### Motivation

The flash attention can accelerate the training speed and save memory a lot. And the optimum library implements the flash attention with a concise and elegant way which is quite easy to use. 

However, the trainer API does not support optimum up to now. If the trainer can support optimum, it will be quite convenient to train the LLMs. 

### Your contribution

Submit issues related to bugs or desired new features.

**Comment by SunMarc** [comment]
cc @younesbelkada @fxmarty

**Comment by younesbelkada** [comment]
Hi @DongHande 
For now we leave it to users responsibility to first convert the model into `BetterTransformer` format and pass it to Trainer. Please have a look at this section of TRL documentation: https://huggingface.co/docs/trl/main/en/sft_trainer#using-flash-attention-and-flash-attention-2 that is also applicable for HF `Trainer` to enable Flash-Attention 1 and 2.

**Comment by DongHande** [comment]
The documentation your mentioned is clear. I learn to use flash attention from this documentation, and it is easy to use. 

Thanks for your reply.
