### ISSUE TITLE
'tiiuae/falcon-7b' is not supported using flash attention 2

### ISSUE THREAD

**Issue by nirdoshrawal009** [huggingface/transformers#26442]
ValueError: The current architecture does not support Flash Attention 2.0. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new

**Comment by LysandreJik** [comment]
cc @younesbelkada  :)

**Comment by LysandreJik** [comment]
I believe this is actually a duplicate of https://github.com/huggingface/transformers/issues/26443, closing in favor of this one

**Comment by younesbelkada** [comment]
Hi @nirdoshrawal009 
Please take a look at my comment here: https://github.com/huggingface/transformers/issues/26443#issuecomment-1738789689
For more details
