### ISSUE TITLE
XLNet run_squad.py IndexError: tuple index out of range

### ISSUE THREAD

**Issue by phuongpm241** [huggingface/transformers#2644]
## 🐛 Bug

Model I am using (Bert, XLNet....): XLNet

Language I am using the model on (English, Chinese....): English (xlnet-base-cased)

The problem arise when using:
* [x] the official example scripts: run_squad.py
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: run_squad.py
* [ ] my own task or dataset: (give details)

## To Reproduce

CUDA_VISIBLE_DEVICES=0,1,2,3 python run_squad.py \
  --model_type xlnet \
  --model_name_or_path xlnet-base-cased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --version_2_with_negative \
  --train_file /data/medg/misc/phuongpm/squadv2/train-v2.0.json \
  --predict_file /data/medg/misc/phuongpm/squadv2/dev-v2.0.json \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --save_steps 10000 \
  --output_dir /scratch/phuongpm/tuned/squad_xlnet/

## Expected behavior

Epoch:   0%|                                                                        | 0/2 [00:00<?, ?it/sTraceback (most recent call last):                                                | 0/2791 [00:00<?, ?it/s]
  File "run_squad.py", line 837, in <module>
    main()
  File "run_squad.py", line 776, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "run_squad.py", line 221, in train
    inputs.update({"is_impossible": batch[7]})
IndexError: tuple index out of range
Epoch:   0%|                                                                        | 0/2 [00:00<?, ?it/s]
Iteration:   0%|                                                                 | 0/2791 [00:00<?, ?it/s]

## Environment

* OS: Linux
* Python version: 3.6 
* PyTorch version: 1.3.1
* PyTorch Transformers version (or branch): 
commit babd41e7fa07bdd764f8fe91c33469046ab7dbd1
Author: Lysandre <lysandre.debut@reseau.eseo.fr>
Date:   Fri Jan 24 17:06:55 2020 -0500
* Using GPU ? Yes
* Distributed or parallel setup ?
* Any other relevant information:

**Comment by LysandreJik** [comment]
Hi, are you sure you're running on commit babd41e, and that you didn't take the script from this version without updating the library itself? I believe this was patched in 073219b.

Could you try to install from source `pip install git+https://github.com/huggingface/transformers` and let me know if it fixes this issue?

**Comment by phuongpm241** [comment]
It works after updating reinstalling the library. I think I might forget to install after git pull. 

Thank you!
