### ISSUE TITLE
glue.py: AttributeError: 'numpy.str_' object has no attribute 'text_a'

### ISSUE THREAD

**Issue by pacebrian0** [huggingface/transformers#2646]
when I am executing the glue data conversion i.e.

`sequences = glue_convert_examples_to_features(X_train, tokenizer, max_length=MAX_SEQUENCE_LENGTH, task='mrpc')
`
I'm getting this error:

> I0126 11:57:07.862119 16252 glue.py:70] Using label list ['0', '1'] for task mrpc
> I0126 11:57:07.863118 16252 glue.py:73] Using output mode classification for task mrpc
> I0126 11:57:07.864120 16252 glue.py:80] Writing example 0
> ---------------------------------------------------------------------------
> 
> AttributeError                            Traceback (most recent call last)
> 
> <ipython-input-11-621d8071aa9a> in <module>
>       2 #test_sequences = [tokenizer.encode(xxt,add_special_tokens=True) for xxt in X_test]
>       3 #val_sequences = [tokenizer.encode(xxt,add_special_tokens=True) for xxt in X_val]
> ----> 4 sequences = glue_convert_examples_to_features(df['cleantext'], tokenizer, max_length=MAX_SEQUENCE_LENGTH, task='mrpc')
>       5 val_sequences = glue_convert_examples_to_features(X_val, tokenizer, max_length=MAX_SEQUENCE_LENGTH, task='mrpc')
>       6 test_sequences = glue_convert_examples_to_features(X_val, tokenizer, max_length=MAX_SEQUENCE_LENGTH, task='mrpc')
> 
> d:\anaconda3\envs\t2\lib\site-packages\transformers\data\processors\glue.py in glue_convert_examples_to_features(examples, tokenizer, max_length, task, label_list, output_mode, pad_on_left, pad_token, pad_token_segment_id, mask_padding_with_zero)
>      84 
>      85         inputs = tokenizer.encode_plus(
> ---> 86             example.text_a,
>      87             example.text_b,
>      88             add_special_tokens=True,
> 
> AttributeError: 'str' object has no attribute 'text_a'

As tokenizer I'm using 
`tokenizer = BertTokenizer.from_pretrained('bert-base-cased')`

and my numpy version is 1.18.1, tensorflow version 2.1.0 (base 2.1.0), transformers version 2.3.0

**Comment by pacebrian0** [comment]
I think the problem was due to the dataset not being set to (index,example) structure

**Comment by someAdjectiveNoun** [comment]
@pacebrian0  Could you post what changes did you make?

**Comment by pacebrian0** [comment]
I decided to use simpletransformers python package, which allows you to train custom datasets.
The above problem can only be solved by using tensorflow-datasets data as far as I know

**Comment by someAdjectiveNoun** [comment]
Ah! The same as me. I am using that same package, but had no idea that those problems could be solved only with tensorflow-datasets.
