### ISSUE TITLE
Tutorial running failed

### ISSUE THREAD

**Issue by moghadas76** [huggingface/transformers#26461]
### System Info

2023-09-28 09:20:05.774209: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /usr/local/lib/python3.10/dist-packages/transformers/commands/env.py:100: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2023-09-28 09:20:11.840292: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.33.3
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.3.3
- Accelerate version: 0.23.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): 2.13.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.7.2 (gpu)
- Jax version: 0.4.14
- JaxLib version: 0.4.14
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@stevhliu and @MKhalusova

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://huggingface.co/blog/time-series-transformers

RuntimeError: mat1 and mat2 shapes cannot be multiplied (12288x22 and 26x32)

### Expected behavior

Working!

**Comment by MKhalusova** [comment]
@NielsRogge or @kashif, can you take please a look? The tutorial mentioned is a blog post you have authored.

**Comment by kashif** [comment]
ok thanks @moghadas76 for the report... would you have some more details on how it happens... from the error message it seems the model and its config are expecting more covariates that you are providing?

**Comment by moghadas76** [comment]
I just replay your tutorial...
```
outputs = model(
    past_values=batch["past_values"],
    past_time_features=batch["past_time_features"],
    past_observed_mask=batch["past_observed_mask"],
    static_categorical_features=batch["static_categorical_features"]
    if config.num_static_categorical_features > 0
    else None,
    static_real_features=batch["static_real_features"]
    if config.num_static_real_features > 0
    else None,
    future_values=batch["future_values"],
    future_time_features=batch["future_time_features"],
    future_observed_mask=batch["future_observed_mask"],
    output_hidden_states=True,
)```

raises that error

**Comment by NielsRogge** [comment]
> 2023-09-28 09:20:05.774209: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

This error is not related to our blog, looks like there's something wrong with your environment. TensorRT is a framework useful when putting models in production, but it's not used in our blog
