### ISSUE TITLE
Question Answering with Japanese

### ISSUE THREAD

**Issue by Mukei** [huggingface/transformers#2647]
## ❓ Questions & Help
Hi @singletongue,

I am trying to use Question-Answering for Japanese, however I could not find any model trained for that. 
I tried with the available models but the results were way off (as expected...).
Any suggestions on available models, or other library that already handle QnA with Japanese?

If it is supposed to work as-is, could you share a simple example?

Thank you in advance!

**Comment by singletongue** [comment]
Hi @Mukei,

As far as I know, there is no Transformer-based model fine-tuned for Japanese question answering tasks.
It is partly due to the scarcity of Japanese QA datasets (like SQuAD) to train the models on.

(Of course, we do wish to release models for QA, and it is left for our future work.)

**Comment by cronoik** [comment]
As a workaround you could load the [bert-base-japanese](https://huggingface.co/bert-base-japanese) weights for the BertForQuestionAnswering model and just finetune the qa_outputs layer (in case of a single span prediction task). It will be quickly trained and maybe produces already sufficient results.

**Comment by Mukei** [comment]
@singletongue Thank you for your reply!

You might already know about it, but I found this [project](https://github.com/AkariAsai/extractive_rc_by_runtime_mt) with SQuAD V1.1 partially translated to Japanese: [Context](https://github.com/AkariAsai/extractive_rc_by_runtime_mt/blob/master/data/ja_question_v5_context.csv), [QA](https://github.com/AkariAsai/extractive_rc_by_runtime_mt/blob/master/data/ja_question_v5.csv)

**Comment by Mukei** [comment]
@cronoik Thank you for the advice.
I tried but unfortunately the results were pretty bad even for some simple phrase.
