### ISSUE TITLE
transformers-v4.33.4., update it please

### ISSUE THREAD

**Issue by brando90** [huggingface/transformers#26495]
### Feature request

release transformers-v4.33.4.

### Motivation

> This should not be required after transformers-v4.33.4.

mistral needs it https://mistral.ai/news/announcing-mistral-7b/

### Your contribution

yes, happy to help, let me know

**Comment by LysandreJik** [comment]
We'll be releasing v4.34.0 tomorrow. Mistral cannot be added to v4.33 through a patch as this would not respect semantic versioning.

In the meantime, feel free to install from source: `pip install git+https://github.com/huggingface/transformers`

**Comment by LysandreJik** [comment]
We're aiming for support on-par with the Mistral implementation in this release, yes!

**Comment by LysandreJik** [comment]
v4.34 with Mistral support was release last month. Closing this!
