### ISSUE TITLE
Issue working with the Trainer class. ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`

### ISSUE THREAD

**Issue by Siddharth4725** [huggingface/transformers#26509]
### System Info

google colab
transformers version :  (4.33.3)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

class CustomTrainer(Trainer):
  def compute_loss(self, model, inputs, return_outputs = False):
    labels = inputs.pop("labels")
    outputs = model(**inputs)
    logits = outputs.get("logits")

    loss_fct = torch.nn.BCELoss()
    loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))
    return (loss, outputs) if return_outputs else loss

training_examples = []

for i, row in mapped_df.iterrows():
  training_examples.append(([row['answer_text'], row['question_text']], row['relevance']))

model =   SiameseBERT(bert_model)
tokenizer =  AutoTokenizer.from_pretrained('bert-base-uncased')
dataloader =  torch.utils.data.DataLoader(training_examples, batch_size = 32, collate_fn= lambda batch: tokenizer(batch, padding=True, return_tensors="pt"))
loss_fn = torch.nn.BCELoss()
trainer = CustomTrainer(
    model=model,
    # args=TrainingArguments(output_dir="./results"),
    train_dataset=dataloader,
)

### Expected behavior

I want the trainer object to be created using my own loss funciton and use it to train my model.. However I encounter an error while instantiating my Trainer class CustomTrainer().

**Comment by LysandreJik** [comment]
Hello, what is the error you encountered?
