### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by ari9dam** [huggingface/transformers#26510]
### System Info

transformers==4.34.0.dev0
accelerate==0.23.0
torch==2.0.1
cuda==11.7

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

import  transformers
model = transformers.MistralForCausalLM.from_pretrained(model_path)

Error:
Traceback (most recent call last):
  File "./trainer.py", line 198, in <module>
    train()
  File "./trainer.py", line 152, in train
    model = transformers.MistralForCausalLM.from_pretrained(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3301, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3689, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/modeling_utils.py", line 741, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 317, in set_module_tensor_to_device
    new_value = value.to(device)
NotImplementedError: Cannot copy out of meta tensor; no data!

### Expected behavior

model loads sucessfully

**Comment by mdazfar2** [comment]
Hello sir can you assign the issue to me

**Comment by ari9dam** [comment]
It does not provide me the option to assign anyone. Sorry!

**Comment by LysandreJik** [comment]
@mdazfar2 feel free to open a PR and link it to this issue if you'd like to work on it!

**Comment by ari9dam** [comment]
It works without FSDP (i.e. with DDP)
with FSDP it is not working

**Comment by mdazfar2** [comment]
@LysandreJik Yeah okk i will do it now

**Comment by ari9dam** [comment]
It works with DeepSpeed Stage2 as well. The error only occurs when using FSDP to train.

**Comment by dannyhung1128** [comment]
Hit the same problem on slurm as well.

**Comment by ari9dam** [comment]
The same problem with llama2 as well. This is not specific for MistralAI.

**Comment by ari9dam** [comment]
What are possible reasons this? I could run my code with 4.33.1. Is it accelerate?

**Comment by LysandreJik** [comment]
Maybe cc @muellerzr as well

**Comment by pacman100** [comment]
Hello, using the latest releases of transformers () and Accelerate (), I am unable to reproduce the issue.

1. Code `isssue_26510.py`:
```
import transformers

model_path = "mistralai/Mistral-7B-Instruct-v0.1"
model = transformers.MistralForCausalLM.from_pretrained(model_path)
```

2. Accelerate config via ` accelerate config --config_file issue_26510.yaml`:
```
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

3. launch command:
```
accelerate launch --config_file issue_26510.yaml issue_26510.py
```

4. output logs:
```
Downloading shards: 100%|█| 2/2 [00:00<00:00,  9.46
Downloading shards: 100%|█| 2/2 [00:00<00:00,  9.70
Downloading shards: 100%|█| 2/2 [00:00<00:00, 12.09
Downloading shards: 100%|█| 2/2 [00:00<00:00,  7.83
Loading checkpoint shards: 100%|█| 2/2 [00:12<00:00,  6.19s/it
Loading checkpoint shards: 100%|█| 2/2 [00:12<00:00,  6.22s/it
Loading checkpoint shards: 100%|█| 2/2 [00:12<00:00,  6.15s/it
Loading checkpoint shards: 100%|█| 2/2 [00:12<00:00,  6.12s/it
```

5. This was experienced initially due to the support for RAM efficient loading of pretrained models not being compatible with few models like Whisper. Therefore, the PRs https://github.com/huggingface/transformers/pull/26631 and https://github.com/huggingface/accelerate/pull/2037 added a config parameter to make it optional. See the config param `` and set it to `False` in case RAM efficient loading of the model fails. The docs for this config parameter are given in https://huggingface.co/docs/accelerate/usage_guides/fsdp#how-it-works-out-of-the-box

**Comment by kwonmha** [comment]
The missing config in the comment above `` is `fsdp_cpu_ram_efficient_loading`. :)
