### ISSUE TITLE
Update resuming with FSDP to work with different number of nodes

### ISSUE THREAD

**Issue by jmzeng** [huggingface/transformers#26549]
### Feature request

It would be great if it's possible to resume a FSDP run on single node to two or three nodes. When I try it currently, it would give the following warning and OOM:

`Didn't find an RNG file for process 8, if you are resuming a training that wasn't launched in a distributed fashion, reproducibility is not guaranteed.`

Would it be possible to add a flag to Trainer to redistribute the model if a particular RNG is missing? 

### Motivation

This would be a great feature for testing on a single machine and then scaling up the run on multiple machines. 

### Your contribution

I'm currently exploring an approach for this.

**Comment by LysandreJik** [comment]
cc @muellerzr @pacman100

**Comment by muellerzr** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello @jmzeng, what is the FSDP config and launch command(s) along with the library versions? 

You can save the whole model ckpt instead of the sharded ckpts and then load it when changing the distributed setup from 1 nodes to 3 nodes for example. Did you try that?
