### ISSUE TITLE
Add keyword arguments to batch_encode_plus() to match encode_plus()

### ISSUE THREAD

**Issue by sergicastellasape** [huggingface/transformers#2654]
## 🚀Consistent Keyword arguments for batch_encode_plus() to match encode_plus()
 Currently, features such as `return_special_tokens_mask` that are available for the `encode_plus()` method are not available for `batch_encode_plus()`. It would be nice if all keyword arguments worked in a similar fashion.

## Motivation
`batch_encode_plus()` is extremely useful to seamlessly tokenize batches, however, the lack of features forces to fall back to encode_plus() and an _uglier_ implementation.

**Comment by TarunSunkaraneni** [comment]
This should require adding a simple `**kwargs` at the end of 

https://github.com/huggingface/transformers/blob/f1e8a51f08eeecacf0cde33d40702d70c737003b/src/transformers/tokenization_utils.py#L977
