### ISSUE TITLE
FIXED POSITION OF NAVBAR 

### ISSUE THREAD

**Issue by kiranugale2o** [huggingface/transformers#26563]
### Feature request

FIXED POSITION OF NAVBAR 
![Oh My Zsh - a delightful   open source framework for Zsh and 5 more pages - Personal - Microsoft​ Edge 03-10-2023 19_48_08](https://github.com/huggingface/transformers/assets/141510294/a8537122-78a4-4bf6-b84a-cdee12b2aa1d)
![Oh My Zsh - a delightful   open source framework for Zsh and 5 more pages - Personal - Microsoft​ Edge 03-10-2023 19_48_17](https://github.com/huggingface/transformers/assets/141510294/e62fd861-9077-4290-946e-2df9f19a3af7)

### Motivation

FIXED POSITION OF NAVBAR 

### Your contribution

FIXED POSITION OF NAVBAR

**Comment by marcury122** [comment]
I would Like to take this issue.

**Comment by Smit1610** [comment]
@kiranugale2o can please assign this issue to me ?

**Comment by LysandreJik** [comment]
Might be of interest to @mishig25

**Comment by marcury122** [comment]
i am not working on this anymore, @iamadisinghal would be a better choice for this issue

**Comment by mishig25** [comment]
Could you elaborate on what do you mean by "Fixed position in navbar"?

**Comment by kiranugale2o** [comment]
> Could you elaborate on what do you mean by "Fixed position in navbar"?

Set Navbar position to 
position:fixed;
