### ISSUE TITLE
Recent docker images missing from dockerhub

### ISSUE THREAD

**Issue by Ben-Epstein** [huggingface/transformers#26599]
### System Info

It seems like your GHA to push released images to dockerhub has been failing for a bit https://github.com/huggingface/transformers/actions/workflows/build-docker-images.yml

I wanted to flag it incase it was going unnoticed. Your latest is consistently being updated,
<img width="337" alt="image" src="https://github.com/huggingface/transformers/assets/22605641/9a6e1918-0ac0-4c2e-808b-eb1eca847e61">

but your tagged images aren't getting released anymore (hasn't been pushed since 4.29)
<img width="1279" alt="image" src="https://github.com/huggingface/transformers/assets/22605641/2103fdd5-6491-4f47-baf8-770f9fec4d88">

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

N/A

### Expected behavior

N/A

**Comment by ydshieh** [comment]
The doc builder docker image fails to build due to `pytorch-quantization` installation. 

It's likely it is not working well with the just released torch 2.1.

As this image is for building doc, I don't know well if this package is required (I guess so). 

@LysandreJik Are you OK if I change the docker file to pin torch 2.0 here?

**Comment by ydshieh** [comment]
There other failing build is due to disk issue. I will take a look

**Comment by LysandreJik** [comment]
> @LysandreJik Are you OK if I change the docker file to pin torch 2.0 here?

Yes, no problem for me!

**Comment by ydshieh** [comment]
There is still AMD docker image failing to build, but it's a known issue.
The daily CI image fails to build again on Nov. 2 - I will check.

**Comment by qhaas** [comment]
FYI:  The last tagged release (4.41.2, 5/30/24) of [`huggingface/transformers-pytorch-gpu` dockerhub image](https://hub.docker.com/r/huggingface/transformers-pytorch-gpu) seems to be far behind the nightly latest(?) build (< 1 day ago).  Thinking it should be on 4.56.1 based on this repo's latest tag at time of writing.
