### ISSUE TITLE
PPLM with Tensorflow

### ISSUE THREAD

**Issue by cakiki** [huggingface/transformers#2660]
## ❓ Questions & Help

Hello,

I am still quite new to the library, so I do apologize if the answer is straightforward. 

The latest release (https://github.com/huggingface/transformers/releases/tag/v2.3.0) mentions the inclusion of PPLM as a new architecture, both as Pytorch and TF. 

I can't however seem to figure out how to import **PPLM** as a **Tensorflow** model. Any help would be greatly appreciated. 

Thank you

**Comment by julien-c** [comment]
I think this is a mistake on our part. cc @LysandreJik @w4nderlust

**Comment by w4nderlust** [comment]
Yes, the code I / we contributed is only for PyTorch. I think porting it to TensorFlow is feasible, but it's not in there at the moment.

**Comment by julien-c** [comment]
The release notes were fixed then. Thanks!
