### ISSUE TITLE
[Docs] Weird rendering of a code block

### ISSUE THREAD

**Issue by wfjsw** [huggingface/transformers#26603]
See 
https://github.com/huggingface/transformers/blob/3e203f92bed937fa13c35adee1bdc45a92d18e61/docs/source/zh/quicktour.md?plain=1#L459

https://huggingface.co/docs/transformers/main/zh/quicktour#:~:text=dataset%20%3D%20dataset.map(tokenize_dataset%2C%20batched%3DTrue)

![image](https://github.com/huggingface/transformers/assets/2220320/14a17760-3fbc-4187-896f-cf4e83d0b81f)

I cannot come up with a valid reason why it is rendered in this way.

**Comment by stevhliu** [comment]
I think it's because there's an extra line between where the function is defined and where we map it. Removing the extra line should fix it:

```diff
>>> def tokenize_dataset(dataset):
...     return tokenizer(dataset["text"])
# remove blank line here

>>> dataset = dataset.map(tokenize_dataset, batched=True)
```
