### ISSUE TITLE
'flash_attn' library  is not installed 

### ISSUE THREAD

**Issue by priyaray21** [huggingface/transformers#26613]
### System Info

%pip install transformers==4.33.3
%pip install mlflow
%pip install azureml-mlflow==1.53.0
%pip install azure-ai-ml
%pip install transformers[torch]
%pip install torchvision
%pip install azure-ai-ml
%pip install azureml-core
%pip install azureml-mlflow
%pip install mlflow 
%pip install python-box
%pip install sentencepices
%pip install sacremoses
%pip install fugashi[unidic-lite]
%pip install packaging
%pip install ipadic
%pip install mecab-python3
%pip install transformers_stream_generator
%pip install cpm_kernels
%pip install tiktoken
%pip install einops
%pip install ninja

### Who can help?

Hi @sanchit-gandhi,
I am trying to install Flash-attn library, but it is not installing.

%pip install flash-attn
Collecting flash-attn
  Using cached flash_attn-2.3.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

%pip install flash-attn
Collecting flash-attn
  Using cached flash_attn-2.3.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

### Expected behavior

How can i install this Library

**Comment by LysandreJik** [comment]
cc @younesbelkada :grin:

**Comment by younesbelkada** [comment]
Hi @priyaray21 - this sounds like an issue that is not related with transformers. Can you refer to the official repository of flash attention? https://github.com/Dao-AILab/flash-attention/
You might have a device that is not compatible with FA or a wrong CUDA version

**Comment by robit-man** [comment]
Fuck you @github-actions

This is still relevant 🍡
