### ISSUE TITLE
Any way we can get dropout added to modeling_llama.py?

### ISSUE THREAD

**Issue by enn-nafnlaus** [huggingface/transformers#26616]
### Feature request

Re: https://github.com/OpenAccess-AI-Collective/axolotl/issues/672

We currently lack any way to prevent overweighting of specific neurons, which becomes a problem when trying to finetune on limited datasets. Something like dropout should go a long way towards being able to develop better models at smaller parameter counts.

### Motivation

See above.

### Your contribution

I don't have familiarity with this codebase.

**Comment by amyeroberts** [comment]
cc @younesbelkada @ArthurZucker
