### ISSUE TITLE
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'

### ISSUE THREAD

**Issue by priyaray21** [huggingface/transformers#26611]
### System Info

transformers==4.33.3
python 3.10
azureml-mlflow==1.53.0

### Who can help?

 Hi,
@ArthurZucker , @younesbelkada and @sanchit-gandhi

When I am trying to run GPTQ family models, throwing AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'

<img width="408" alt="image" src="https://github.com/huggingface/transformers/assets/139554535/8e9a8708-dfe1-43cc-9fc8-eec036d83b7d">

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I have installed bitsandbytes-cuda111 but getting Attribute Errors.

### Expected behavior

How can I fix that issue?

**Comment by younesbelkada** [comment]
Hi @priyaray21 
Thanks for the issue, this sounds like an issue with peft, can you try to uninstall `bitsandbytes-cuda111` as it is an old version of the lib and install `bitsandbytes` instead?

```bash
pip uninstall bitsandbytes-cuda11
pip install -U bitsandbytes
```
