### ISSUE TITLE
LayoutLMv3FeatureExtractor(apply_ocr=True) not returning words 

### ISSUE THREAD

**Issue by rahulss14** [huggingface/transformers#26619]
I have trained a LILT using my custom dataset , everything works fine but I am not getting ocr words of the detected regions . How can I get the words .

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!

**Comment by rahulss14** [comment]
Hello 
thank you for your prompt response , I am new to this can you answer this here . I will ask my further questions on forum .


Awaiting your response
