### ISSUE TITLE
Having a `to_grayscale` function 

### ISSUE THREAD

**Issue by rafaelpadilla** [huggingface/transformers#26630]
### Feature request

It would be useful to have a general `to_grayscale` function into our `image_transforms.py` so it can be called by any model in their `preprocess()`.

### Motivation

Our image processing got more robust and can now accept 1-channel and 3-channel images.
Seeing that, new models (like [SuperModel](https://github.com/huggingface/transformers/pull/25786) and potentially new ones) require grayscale images as inputs. Thus, it would be useful to have a "standard" `to_grayscale` function in `image_transforms.py` - similarly as our `convert_to_rgb(...)`.

Indeed each model could implement their own version of `to_grayscale`, but I find it useful to have an out-of-the-box function that can be easily called, avoiding redundant implementations of it.

### Your contribution

I can make a PR for that if you also think it is useful.
@amyeroberts @ArthurZucker

**Comment by Neel-07** [comment]
hello @rafaelpadilla can i work on this issue

**Comment by rafaelpadilla** [comment]
Hi @Neel-07,

Sure, that'd be awesome. :) 
But let's just wait until one of our core maintainers (@amyeroberts and @ArthurZucker) approves this request.

**Comment by Neel-07** [comment]
okay sure @rafaelpadilla

**Comment by ArthurZucker** [comment]
I don't have a strong opinion on this, think that when it comes to vision and converting to grayscale you might have a lot of heuristic that might be different so would just go with the flow. If next model uses the same we can move it otherwise I don't really see a point for now!

**Comment by rafaelpadilla** [comment]
Alright! :) 
So, I will close this issue for now.
If a new model also needs grayscale conversion, then we can reopen this issue and work on this.
