### ISSUE TITLE
dead link to vitdet-base-patch16-224

### ISSUE THREAD

**Issue by dotneet** [huggingface/transformers#26644]
This link is dead.

[google/vitdet-base-patch16-224](https://huggingface.co/google/vitdet-base-patch16-224)
https://github.com/huggingface/transformers/blob/897a826d830e8b1e03eb482b165b5d88a7a08d5f/src/transformers/models/vitdet/configuration_vitdet.py#L35

**Comment by Ankit8848** [comment]
@dotneet Hey,  I want to work on this issue. Can you assign to me ?

**Comment by LysandreJik** [comment]
First come, first served @Ankit8848, feel free to open a PR.

**Comment by betterze** [comment]
@Ankit8848 Is this bug fixed? I can not load the 'google/vitdet-base-patch16-224' model. Thx for your help.

```
from transformers import VitDetConfig, VitDetModel
model = VitDetModel.from_pretrained("google/vitdet-base-patch16-224")
```

**Comment by Ankit8848** [comment]
@betterze i don't know, I have not worked on this issue.
