### ISSUE TITLE
Trainer subclasses should be able to replace Accelerator / Optimizer

### ISSUE THREAD

**Issue by frankier** [huggingface/transformers#26686]
### Feature request

It's possible that some in-depth customization of the `Trainer` class may require changes to Accelerator. There is already a pattern with the optimizer that the class and arguments are obtained from:

```python
@staticmethod
def get_optimizer_cls_and_kwargs(args: TrainingArguments) -> Tuple[Any, Any]:
```

So it would be nice to have a corresponding

```python
@staticmethod
def get_accelerator_cls_and_kwargs(args: TrainingArguments) -> Tuple[Any, Any]:
```

### Motivation

Customisability

### Your contribution

I am going to submit a PR

**Comment by frankier** [comment]
Okay, I've now realised that this won't work unless it's `@classmethod`, so perhaps `get_optimizer_cls_and_kwargs` should be changed for this too? Delaying working on a PR until this has been discussed.

**Comment by amyeroberts** [comment]
cc @pacman100 @muellerzr

**Comment by muellerzr** [comment]
@frankier (sorry for the delay) why does this require it being a class method? It should just be static I believe unless you're seeing something I'm not
