### ISSUE TITLE
`tokenizer.apply_chat_template` not working as expected for Mistral-7B model; it adds `<<SYS>>` despite no system message.

### ISSUE THREAD

**Issue by ivsanro1** [huggingface/transformers#26684]
### System Info

- Colab
- `transformers==4.34.0`

### Who can help?
Maybe @ArthurZucker or @Rocketknight1

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Colab link to reproduce it [here](https://colab.research.google.com/drive/16xTa_3PawEocUleRzGei9ipXZVlgNjpS?usp=sharing)

### Expected behavior

The resulting instantiated prompt should be like the one [shown in the model card](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1#instruction-format), and it should not contain `<<SYS>>` or `<</SYS>>` delimiters, or system message at all:

```
text = "<s>[INST] What is your favourite condiment? [/INST]"
"Well, I'm quite partial to a good squeeze of fresh lemon juice. It adds just the right amount of zesty flavour to whatever I'm cooking up in the kitchen!</s> "
"[INST] Do you have mayonnaise recipes? [/INST]"
```

Additional note: I was running the same code yesterday on the same version of `transformers` and it was working correctly.

**Comment by Rocketknight1** [comment]
Hi @ivsanro1, this is because an update to the Mistral model repo removed the chat template by accident, which caused the tokenizer to fall back to the default LLaMA chat ttemplate. I'm communicating with the team now, hopefully it can be restored very soon!

**Comment by ivsanro1** [comment]
Hello @Rocketknight1, thanks a lot for the explanation, that makes a lot of sense and explains why it happened without changing transformers version.

As this is not a transformers issue per se, please feel free to close the issue when you consider it appropriate.

**Comment by Rocketknight1** [comment]
Hi @ivsanro1, the fix has been merged [here](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1/discussions/45), so I'll close the issue now. Thank you very much for the quick bug report though - this issue was what alerted us to the problem and let us fix it so quickly!

**Comment by jpiabrantes** [comment]
@Rocketknight1 the model [Qwen/Qwen2-7B](https://huggingface.co/Qwen/Qwen2-7B) contains a chat_template and it adds the `<|im_start|>` tags even though it wasn't trained for them..

**Comment by Rocketknight1** [comment]
Hi @jpiabrantes, thanks for pointing that out! You should open an issue or PR on the relevant model and tag the model authors.
