### ISSUE TITLE
itm_score output for BLIP2

### ISSUE THREAD

**Issue by fferroni** [huggingface/transformers#26698]
### Feature request

Would it be possible to add outputting ITM/ITC scores for BLIP2? It is currently supported for BLIP v1.

### Motivation

LAVIS already contains the image-text matching capability here
https://github.com/salesforce/LAVIS/blob/3446bac20c5646d35ae383ebe6d13cec4f8b00cb/lavis/models/blip2_models/blip2_image_text_matching.py

### Your contribution

Given some pointers on which objects/layers correspond to the LAVIS version vs `transformers` version, I would also try adding this.

**Comment by jpizarrom** [comment]
Hi @fferroni , maybe this PR https://github.com/huggingface/transformers/pull/25612 could be related
