### ISSUE TITLE
Getting GPU crash when running compute_metrics within SFTTrainer

### ISSUE THREAD

**Issue by matthewchung74** [huggingface/transformers#26702]
### System Info

This is in colab https://colab.research.google.com/drive/1qTIxG_9R8xIYryY5mEPXIydZB5QeSnKp#scrollTo=5VM67iQMymv5

I have an Mistral Fine tune in Colab. Before training, I try running 

```
trainer.evaluate()
```
and get the following error message
```
[/usr/local/lib/python3.10/dist-packages/transformers/trainer_pt_utils.py](https://localhost:8080/#) in torch_pad_and_concatenate(tensor1, tensor2, padding_index)
     86 
     87     # Now let's fill the result tensor
---> 88     result = tensor1.new_full(new_shape, padding_index)
     89     result[: tensor1.shape[0], : tensor1.shape[1]] = tensor1
     90     result[tensor1.shape[0] :, : tensor2.shape[1]] = tensor2

OutOfMemoryError: CUDA out of memory. Tried to allocate 12.94 GiB (GPU 0; 39.56 GiB total capacity; 18.33 GiB already allocated; 12.29 GiB free; 25.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
however, when compute_metrics is commented out, i can evaluate/train the model

Any help is appreciated. Thanks!

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. run the colab https://colab.research.google.com/drive/1qTIxG_9R8xIYryY5mEPXIydZB5QeSnKp#scrollTo=5VM67iQMymv5

2. see the error
3. comment out comput_metrics
4. run again and do not see error

### Expected behavior

I don't see compute_metrics requiring any additional resources, so am unsure why it would be using more gpu and would expect it not to crash.

**Comment by LysandreJik** [comment]
cc @pacman100 @muellerzr

**Comment by matthewchung74** [comment]
thank you @muellerzr

**Comment by muellerzr** [comment]
I believe https://github.com/huggingface/transformers/pull/27458 will help with this after a bit more fixing in the PR
