### ISSUE TITLE
 Code Llama HF tokenizer length is 32004 whereas vocab_size is 32000

### ISSUE THREAD

**Issue by dineshkh** [huggingface/transformers#26714]
### System Info

- `transformers` version: 4.34.0
- Platform: Linux-4.18.0-477.15.1.el8_8.x86_64-x86_64-with-glibc2.28
- Python version: 3.11.2
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0+cu118 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("codellama/CodeLlama-34b-hf")
model = AutoModelForCausalLM.from_pretrained("codellama/CodeLlama-34b-hf")
embedding_size = model.get_input_embeddings().weight.shape[0]
print("Length of tokenizer:  {} : ".format(len(tokenizer)))
print("vocab_size: {} : ".format(model.config.vocab_size))
print("embedding_size: {} : ".format(embedding_size))
```

```
Length of tokenizer: 32004
vocab_size: 32000 
embedding_size: 32000 
```

### Expected behavior

```
Length of tokenizer: 32004
vocab_size: 32004 
embedding_size: 32004 
```

**Comment by LysandreJik** [comment]
cc @ArthurZucker

**Comment by ArthurZucker** [comment]
Hey, that's because the tokenizer was not updated. I opened [this](https://huggingface.co/codellama/CodeLlama-34b-hf/discussions/15/files) but will open anotherone to make sure they merge is and we have the latest format. 
Thanks for reporting 🤗

**Comment by ArthurZucker** [comment]
Duplicated issue: #27053
