### ISSUE TITLE
Wrongly load .safetensors weights because it loads only depends on file names not weight files

### ISSUE THREAD

**Issue by Rickylht** [huggingface/transformers#26729]
### System Info

[2023-10-11 16:31:10,112] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.31.0
- Platform: Linux-5.15.0-70-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

@gante @Narsil 
If there is a file(e.g. json file) with a name "...safetensor...*" in my model directory, it will automatically load .safetensor weights. As there is no .safetensor weights but only .bin weights in my directory.

I found this is because in the following .py 
`/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py`

line 112: `_safetensors_available = _is_package_available("safetensors")`

line 41: `def _is_package_available(pkg_name: str, return_version: bool = False) -> Union[Tuple[bool, str], bool]:`

It only depends on the file name not the existence of weights file. 
I think it is better to check whether '.safetensor' at the end of the file names since the corresponding json file of safetensor named as 'model.safetensors.index.json'. 

### Expected behavior

If there is no .safetensor weights in my dir, don`t load the .safetensor but load .bin weights.

**Comment by LysandreJik** [comment]
Hmmm indeed, would you like to offer a fix?
