### ISSUE TITLE
flash attention 2.0 for internLM

### ISSUE THREAD

**Issue by MaxLEAF3824** [huggingface/transformers#26725]

**Comment by LysandreJik** [comment]
cc @younesbelkada

**Comment by younesbelkada** [comment]
Hi @MaxLEAF3824 

InternLM is now using the same architecture as Llama as you can see here: https://huggingface.co/internlm/internlm-7b/discussions/4/files 

You can benefit from FA-2 + intern-LM with the snippet below:

```python
# pip install flash-attn --no-build-isolation

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained(
        "internlm/internlm-7b",
        use_flash_attention_2=True,
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
        revision="refs/pr/4"
)
```

**Comment by younesbelkada** [comment]
cc @Rocketknight1 do you have an idea why https://huggingface.co/internlm/internlm-7b/discussions/4/files did not get merged yet 🙏

**Comment by Rocketknight1** [comment]
Hi @younesbelkada, we're still waiting on approval from the InternLM team!

**Comment by younesbelkada** [comment]
OK thanks ! Hopefully it will get merged soon
