### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by Chanchal-D** [huggingface/transformers#26736]
### Feature request

the existing readme is too long.  It should contain prerequisites and license.

### Motivation

I felt bored when I found the readme too long.

### Your contribution

I will make the readme more concise and brief in an interactive way.

**Comment by LysandreJik** [comment]
Sorry you felt bored :(
What would you remove?

**Comment by Chanchal-D** [comment]
There's a lot of extra theory that is of no use, I can make it short and interactive.  Plus there are 200+ model architectures that are too long. only the key highlights should be mentioned.

**Comment by LysandreJik** [comment]
For model architectures I get your point, the rest seems pretty much required no?

**Comment by Chanchal-D** [comment]
yes, it is required, but could written in a short and concise way that is easy to understand.
