### ISSUE TITLE
Improving Typing

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [huggingface/transformers#26745]
### Feature request

I was working on a project using Transformers and came across a few functions that had not been typed completely. Example:
1. [TrainingArguments](https://github.com/huggingface/transformers/blob/e1cec43415e72c9853288d4e9325b734d36dd617/src/transformers/training_args.py#L161)
2. [activations_tf.py](https://github.com/huggingface/transformers/blob/e1cec43415e72c9853288d4e9325b734d36dd617/src/transformers/activations_tf.py)
3. [convert_slow_tokenizer.py](https://github.com/huggingface/transformers/blob/e1cec43415e72c9853288d4e9325b734d36dd617/src/transformers/convert_slow_tokenizer.py)

### Motivation

I am a fan to greatly typed code since it makes my code editors' intellisense work better.

### Your contribution

Can I create a PR to solve this?

**Comment by LysandreJik** [comment]
We use typings to make the code readable. We're not looking to have our code **_exactly_** typed if it has to come at the expense of readability. If the changes you have in mind adhere to this mindset, then yes, feel free to open a PR.

**Comment by Siddhesh-Agarwal** [comment]
I totally get you, I'll be making some small changes here there (Hope to make things a little better)

**Comment by Siddhesh-Agarwal** [comment]
Hey @LysandreJik, I was going through the code and came across this:

```
class ClassInstantier(OrderedDict):
    def __getitem__(self, key):
        content = super().__getitem__(key)
        cls, kwargs = content if isinstance(content, tuple) else (content, {})
        return cls(**kwargs)
```
> [Source](https://github.com/huggingface/transformers/blob/5bfda28dd36b47912da1cdd0e2e83ab32c7408e4/src/transformers/activations.py#L206-L210)

It seems like transformers is only meant for [python>=3.8](https://github.com/huggingface/transformers/blob/5bfda28dd36b47912da1cdd0e2e83ab32c7408e4/setup.py#L149) and [Dictionary order is preserved since Python 3.7](https://docs.python.org/3/whatsnew/3.7.html). So, I am guessing we can replace the `OrdererDict` with the native `dict`.
