### ISSUE TITLE
[Bug] TypeError: forward() got an unexpected keyword argument 'padding_mask'

### ISSUE THREAD

**Issue by SingL3** [huggingface/transformers#26755]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.34.0
- Platform: Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.31
- Python version: 3.9.18
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.23.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Follow https://huggingface.co/blog/ram-efficient-pytorch-fsdp and submit mission with [srun](https://gist.github.com/pacman100/1cb1f17b2f1b3139a63b764263e70b25) to train a llama2 model which is save using transformers==4.33.0.

### Expected behavior

Training successfully.
I think downgrade to 4.33.0 is a solution but I wonder it is a better solution?

**Comment by tbenthompson** [comment]
The issue is that the codebase you are using has [monkey patched in a different `forward` function in the `LlamaAttention` module](https://github.com/pacman100/DHS-LLM-Workshop/blob/main/chat_assistant/training/llama_flash_attn_monkey_patch.py) <-- see the link. The monkey patched `forward` was valid in 4.33 but no longer matches the function signature of the `LlamaAttention.forward` in 4.34.0. I had the same issue. This is not a bug in transformers.

**Comment by SingL3** [comment]
I see! Thank you! Closing now.

**Comment by HYZ17** [comment]
I have to use transformers==4.34.0. Any solution for this error?

**Comment by tbenthompson** [comment]
> Any solution for this error?

1) Remove the monkey patching
2) Load your model with: `model = transformers.AutoModelForCausalLM.from_pretrained(name, use_flash_attention_2=True)`.

**Comment by wolhandlerdeb** [comment]
> > Any solution for this error?
> 
> 1. Remove the monkey patching
> 2. Load your model with: `model = transformers.AutoModelForCausalLM.from_pretrained(name, use_flash_attention_2=True)`.

 Why this should help? It doesn't change the model behavior?
Thanks

**Comment by HYZ17** [comment]
> > > Any solution for this error?
> > 
> > 
> > 
> > 1. Remove the monkey patching
> > 2. Load your model with: `model = transformers.AutoModelForCausalLM.from_pretrained(name, use_flash_attention_2=True)`.
> 
> Why this should help? It doesn't change the model behavior? Thanks

Huggingface has already integrated flash attention for lllama. So there is no need to use monkey patch. Just load model with `use_flash_attention_2=True`
