### ISSUE TITLE
`use_default_system_prompt` broken

### ISSUE THREAD

**Issue by AjayP13** [huggingface/transformers#26766]
### System Info

- Python 3.11.4
- 4.34.0

### Who can help?

@younesbelkada @ArthurZucker

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

```bash
Python 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
>>> transformers.__version__
'4.34.0'
>>> tokenizer = transformers.AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
>>> tokenizer.use_default_system_prompt = True
>>> tokenizer.apply_chat_template([{"role": "user", "content": "Hello"}], tokenize=False)
'<s>[INST] Hello [/INST]'
```

### Expected behavior

It should return the default LLaMa-2 system prompt (this was just working yesterday, something recently broke):
```bash
'[INST] <<SYS>>\nYou are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.\n<</SYS>>\n\nHello [/INST]'
```

**Comment by AjayP13** [comment]
@Rocketknight1 - This seems to stem from a commit pushed to `meta-llama/Llama-2-7b-chat-hf` on HuggingFace Hub: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/commit/af6df14e494ef16d69ec55e9a016e900a2dde1c8

Was this intentional?

**Comment by Rocketknight1** [comment]
@ajayp13 Yes, this was intentional! After testing between us and Meta, people felt that the default system prompt caused LLaMA-2 to refuse too many requests, even totally valid ones, which made it much less useful than it could be.

You can try running it without the default prompt, or with a shorter system prompt of your own - either of those should work!

**Comment by AjayP13** [comment]
I see, thanks! Closing.

**Comment by Rocketknight1** [comment]
If anyone else sees this issue and wants to keep using the original prompt, here is the original system message. You can add this as the first message in your conversation with role `system` in order to keep using it:

```
"""You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your \
answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure\
 that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not \
correct. If you don't know the answer to a question, please don't share false information."""
```

**Comment by zengqingfu1442** [comment]
Can we put our custom system prompt into chat template whose format is jinja?
