### ISSUE TITLE
`QuantAct` in `IntSoftmax` receives integer value

### ISSUE THREAD

**Issue by mbekmyrz** [huggingface/transformers#26767]
**Problem/Question:**

`IntSoftmax` class has `QuantAct`:

https://github.com/huggingface/transformers/blob/fc63914399b6f60512c720959f9182b02ae4a45c/src/transformers/models/ibert/quant_modules.py#L379-L380

and it is called in `IntSoftmax.forward()` by passing `exp_int` which is integer:
https://github.com/huggingface/transformers/blob/fc63914399b6f60512c720959f9182b02ae4a45c/src/transformers/models/ibert/quant_modules.py#L418

and then within `QuantAct.forward` it is passed to `FixedPointMul` where the integer value is rescaled again to find 'integer' value:
https://github.com/huggingface/transformers/blob/fc63914399b6f60512c720959f9182b02ae4a45c/src/transformers/models/ibert/quant_modules.py#L206-L213

https://github.com/huggingface/transformers/blob/fc63914399b6f60512c720959f9182b02ae4a45c/src/transformers/models/ibert/quant_modules.py#L787

Whereas it was an integer already. All the other modules in IBert that has `QuantAct` passes real valued `x`, and it's okay for `FixedPointMul` to divide by scaling factor to find  `z_integer`. But within `IntSoftmax` input `x` was already an integer.

Same error in the original source code: https://github.com/kssteven418/I-BERT/blob/1b09c759d6aeb71312df9c6ef74fa268a87c934e/fairseq/quantization/utils/quant_modules.py#L652C9-L652C72

**Solution:**
```
exp, exp_scaling_factor = self.act(exp_int * exp_scaling_factor, exp_scaling_factor)
```

tagging @kssteven418 as the designer of the model:)

**Comment by Adarsh-Dhar** [comment]
Hey can I contribute to this issue can you tell me what all techstack I need and how should I start

**Comment by ArthurZucker** [comment]
Sure! Feel free to open a PR for a fix!
