### ISSUE TITLE
ClearML task closes when done training - unnecessary and causes issues

### ISSUE THREAD

**Issue by johnml1135** [huggingface/transformers#26762]
### System Info

When a python script ends, it automatically closes the task.  After training, some people (me included) may want to do more for the task, including inferencing on the model.  Therefore, always automatically closing the task on training completion, while sounding nice, is not needed and causes issues.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

See code here:
https://github.com/huggingface/transformers/blob/0ebee8b93358b6ef0182398b8fcbd7afd64c0f97/src/transformers/integrations/integration_utils.py#L1488-L1493

### Expected behavior

The ClearML task does not close when training is complete.

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @johnml1135 ! I think that the task should indeed close if it was created by the callback class. If you don't want it to close, just initialize the task externally, i.e. call `Task.init` before creating the callback instance. In this case, the task will not close on when the training ends.

**Comment by johnml1135** [comment]
I do initialize the task well before I create the model to train:
* https://github.com/sillsdev/machine.py/blob/main/machine/jobs/build_nmt_engine.py
* https://github.com/sillsdev/machine.py/blob/main/machine/jobs/nmt_engine_build_job.py

I don't know what's could more be done...

**Comment by eugen-ajechiloae-clearml** [comment]
@johnml1135 Note that our fix has not been officially released yet. Have you installed `transformers` by cloning this repository and doing something like:
```
cd transformers
python3 -m pip install -e .
```
?

**Comment by johnml1135** [comment]
I think I see - you are making a fix to resolve the issue as you specified above.  Can you link to the commit/PR that implements the fix here?

**Comment by eugen-ajechiloae-clearml** [comment]
@johnml1135 You can find the PR here: https://github.com/huggingface/transformers/pull/26614

**Comment by johnml1135** [comment]
Great - that should resolve our issue!
