### ISSUE TITLE
Adding new special tokens does not seem to work properly in 4.34

### ISSUE THREAD

**Issue by dakinggg** [huggingface/transformers#26772]
### System Info

- `transformers` version: 4.34.0
- Platform: macOS-13.5-arm64-arm-64bit
- Python version: 3.10.12
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.20.3
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

In [10]: import transformers

In [11]: llamat = transformers.AutoTokenizer.from_pretrained('meta-llama/Llama-2-7b-hf')

In [12]: llamat('hello')
Out[12]: {'input_ids': [1, 22172], 'attention_mask': [1, 1]}

In [13]: llamat.add_special_tokens({'bos_token': '[NEWSPECIAL]'})
Out[13]: 1

In [14]: llamat('hello')
Out[14]: {'input_ids': [1, 22172], 'attention_mask': [1, 1]}

### Expected behavior

Expected that the new bos token is used instead of the old one.

**Comment by dakinggg** [comment]
@ArthurZucker

**Comment by ArthurZucker** [comment]
Hey, this is expected for a fast tokenizer because you are not changing the `processor` . You need to run `llamat.update_post_processor()` before to make sure this is taken into account. 
Initializing the tokenizer would be the best way to have the expected results for fast tokenizers

**Comment by dakinggg** [comment]
Thanks, some clarifications:
(1) Is it expected that this behavior changed in 4.34? Its a bit scary of a behavior to silently change and could lead to very tricky bugs in peoples' workflows.
(2) Is the recommendation that I always call `update_post_processor` after adding new special tokens?

**Comment by ArthurZucker** [comment]
1. It's not necessarily from 4.34. I tested with 4.33 and this does not work either. 
2. Fast tokenizers as supposed to be stateless, and we usually don't support post init updates. My recommendation is rather to do everything at init time rather than post init for fast tokenizers 😉

**Comment by dakinggg** [comment]
Huh, I wonder why my unit test was passing before 😅 but anyway, makes sense, thank you!
