### ISSUE TITLE
Streaming text output from a pipeline.

### ISSUE THREAD

**Issue by lukolszewski** [huggingface/transformers#26797]
### Feature request

Implement a way to obtain streaming text output from a pipeline. One token at a time.

### Motivation

To be able to see the response as it is being generated instead of having to wait for the entire thing. 

### Your contribution

I can test it if it gets implemented.

**Comment by ArthurZucker** [comment]
Hey! Would recommend you to read [this section](https://huggingface.co/docs/transformers/generation_strategies#streaming) of the documentation about streaming when generating, I think it should help!
