### ISSUE TITLE
Getting error "TypeError: 'NoneType' object is not callable" while using pretrained model checkpoints in TFAutoModelForQuestionAnswering

### ISSUE THREAD

**Issue by pksX01** [huggingface/transformers#26807]
### System Info

- `transformers` version: 4.34.0
- Platform: macOS-14.0-arm64-arm-64bit
- Python version: 3.10.12
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0 (False)
- Tensorflow version (GPU?): 2.15.0-dev20231007 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run following code in Python 3 terminal.

```
from transformers import AutoTokenizer
from transformers import TFAutoModelForQuestionAnswering

model_checkpoint = "distilbert-base-cased"

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = TFAutoModelForQuestionAnswering.from_pretrained(model_checkpoint)
```

### Expected behavior

Model safetensors shall be downloaded. But getting below error:
```
>>> model = TFAutoModelForQuestionAnswering.from_pretrained(model_checkpoint)
Using TensorFlow backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rudra/mambaforge/envs/keras_tf/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/Users/rudra/mambaforge/envs/keras_tf/lib/python3.10/site-packages/transformers/modeling_tf_utils.py", line 2912, in from_pretrained
    model.build()  # build the network with dummy inputs
  File "/Users/rudra/mambaforge/envs/keras_tf/lib/python3.10/site-packages/keras/src/layers/layer.py", line 222, in build_wrapper
    original_build_method(*args, **kwargs)
  File "/Users/rudra/mambaforge/envs/keras_tf/lib/python3.10/site-packages/transformers/modeling_tf_utils.py", line 1131, in build
    if self.built or call_context().in_call:
TypeError: 'NoneType' object is not callable
```

Note: Same code is working in Google colab but failing in local on Mac M1.

**Comment by ArthurZucker** [comment]
Hey! As you mention that this works on colab, I would recommend you to make sure your mac install of tensorflow is compatible. Running this on my M1 works as expected. I used `pip install tensforflow-macos tensorflow-metal`
