### ISSUE TITLE
Add Mistral Models to Flax

### ISSUE THREAD

**Issue by kiansierra** [huggingface/transformers#26809]
### Feature request

I would like to implement the ~~Llama~~ Mistral model in flax

### Motivation

I've been trying to get familiar with jax and as such I started migrating the llama model, and I think I am at a point where both models are quite comparable in outcome

### Your contribution

Yes I could submit a PR with the model implementation

**Comment by ArthurZucker** [comment]
I think this could be interesting! Feel free to open a PR and ping @sanchit-gandhi 😉

**Comment by sanchit-gandhi** [comment]
Hey @kiansierra - there's already a PR for Flax LLaMA that is pretty much ready to be merged: https://github.com/huggingface/transformers/pull/24587 Feel free to check it out!

But we'd love contributions for other LLM's in the library where there's only PyTorch support and not Flax 🤗 If there are particular checkpoints on the HF Hub that you see getting a lot of usage (downloads) where there's only PyTorch support but not Flax, definitely let us know here and we can get going with a PR! 🚀

**Comment by ArthurZucker** [comment]
Oups I even reviewed the PR 😅 sorry @kiansierra 🤗

**Comment by vvvm23** [comment]
@kiansierra sorry to scoop Flax Llama from you! If you want any suggestions, I think [Mistral](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mistral/modeling_mistral.py) is a pretty popular model right now without a Flax port.

**Comment by kiansierra** [comment]
Hey no worries, I think I will give Mistral a go, it seems some of the work can be ported

**Comment by erfanzar** [comment]
hello, guys I have created both llama and mistral models in flax if you want you can use them [modelling_mistral_flax.py](https://github.com/erfanzar/EasyDeL/blob/main/lib/python/EasyDel/modules/mistral/modelling_mistral_flax.py)

**Comment by sanchit-gandhi** [comment]
Yes Flash Attention relies on dispatching optimised CUDA kernels, which as far as I'm aware haven't been implemented in JAX. You could look into Pallas and see if someone's written Flash Attention kernels for JAX using this library? https://jax.readthedocs.io/en/latest/pallas/design.html

**Comment by konstantinos-p** [comment]
Indeed there's an effort to write FlashAttention in Pallas, https://github.com/google/jax/blob/main/jax/experimental/pallas/ops/attention.py although it's still a work in progress https://github.com/google/jax/pull/17328 . @sanchit-gandhi I'd be happy to try to port another model. For example, Yarn-Mistral seems to have some traction though, it's not part of the transformers library atm. Any other suggestions are welcome!
