### ISSUE TITLE
Trainer for devided model

### ISSUE THREAD

**Issue by yeonju7kim** [huggingface/transformers#26815]
### Feature request

Trainer class settings for divided model.

If I use trainer.predict, it loads the model on the device in the code of the trainer package.
It's hard to separately load the model manually.

I think it'll be better to implement to avoid loading the model twice.

### Motivation

https://huggingface.co/docs/accelerate/usage_guides/big_modeling
I read the above. Then I divided the LLM and loaded the model parts on the different GPUs.

My code used Trainer for training.
Because of the line below, the already loaded model loads again here on args.device.
https://github.com/huggingface/transformers/blob/21dc5859421cf0d7d82d374b10f533611745a8c5/src/transformers/trainer.py#L3072-L3076

I manually erased the line to use Trainer with the divided LLM. 
Is there any other way to use Trainer with a divided model? 

### Your contribution

I'm a novice for trainer class. I'm afraid that my question seems stupid.

**Comment by ArthurZucker** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
No, you cannot use the big model inference API to do training in this way (hence training in the name). You can use methods like DeepSpeed or FSDP to split the work between multiple GPUs or perform offloading during training, which the trainer already supports.
