### ISSUE TITLE
Pipelines should yield results incrementally even when their input is a list

### ISSUE THREAD

**Issue by uyhcire** [huggingface/transformers#26826]
### System Info

- `transformers` version: 4.34.0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu118 (False)
- Tensorflow version (GPU?): 2.13.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.7.4 (cpu)
- Jax version: 0.4.16
- JaxLib version: 0.4.16
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@nar

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X ] My own task or dataset (give details below)

### Reproduction

```
from transformers import pipeline 

pipe = pipeline("text-classification")

def input_generator():
    for _ in range(100000):
        yield "This restaurant is awesome"

# Finishes quickly
for result in pipe(input_generator()):
    print(result)
    break

# Takes basically forever
for result in pipe(["This restaurant is awesome"] * 100000):
    print(result)
    break
```

### Expected behavior

Pipelines should yield results as soon as they are available, regardless of whether the inputs to be processed come in the form of a list or a generator.

**Comment by ArthurZucker** [comment]
Makes sense to me, however this changes the default behaviour, and does not take into account batching, which is what's recommended if you are running with a lot of inputs. 
Also depending on the pipeline this might already be implemented ! 
I am not sure how @Narsil feels about it ? (he is off for now but this can wait, in the meantime feel free to open a PR to see what kind of changes are required for this!)

**Comment by Gistix** [comment]
This works for image-text-to-text pipeline even with batching so I don't see why it shouldn't work for text-generation or other pipelines.
