### ISSUE TITLE
Segmentation fault when initializing training arguments with imported tensorflow

### ISSUE THREAD

**Issue by zeionara** [huggingface/transformers#26823]
### System Info

- `transformers` version: 4.34.0
- Platform: Linux-6.2.0-33-generic-x86_64-with-glibc2.35
- Python version: 3.11.5
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.3.2
- Accelerate version: 0.23.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0 (True)
- Tensorflow version (GPU?): 2.14.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@muellerzr @pacman100

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
import tensorflow as tf

from transformers import TrainingArguments

print('Listing tf gpus...')

print(tf.config.list_physical_devices("GPU"))

print('Initializing training arguments...')

args = TrainingArguments(output_dir="output")

print('Initialization has completed')
```

### Expected behavior

Expected output:

```
Listing tf gpus...
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]
Initializing training arguments...
Initialization has completed
```

Observed output:
```
Listing tf gpus...
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]
Initializing training arguments...
Segmentation fault (core dumped)
```

**Comment by amyeroberts** [comment]
cc @Rocketknight1 as this might be a TF issue

**Comment by Rocketknight1** [comment]
Hi @zeionara, I ran that code here on TF 2.14 and did not get a segfault. Can you try replacing `TrainingArguments` with `TFTrainingArguments` to see if the issue persists? The `TrainingArguments` class is usually used for Torch examples, and might do some torch initializations, which could cause a segfault if Torch is incorrectly configured and TF has allocated GPU memory already.
