### ISSUE TITLE
Issue with my profile on the upload/share models webpage

### ISSUE THREAD

**Issue by jplu** [huggingface/transformers#2682]
Hello,

The URL of my [profile](https://huggingface.co/jplu) on the upload/share models webpage looks like if there was a model called `jplu`. Any idea why?

Thanks.

**Comment by julien-c** [comment]
Should be fixed.

**Comment by jplu** [comment]
Nice! Thanks :)

**Comment by julien-c** [comment]
By the way, you should also add a README.md to the same `pretrained_model` folders so that it's displayed on the model pages (see [this one](https://huggingface.co/dbmdz/bert-base-german-cased) for instance)

I'll document this feature better today.

**Comment by julien-c** [comment]
Should `jplu/camembert-base` be `jplu/tf-camembert-base`?

**Comment by jplu** [comment]
The name should be ok now, it was an issue in the naming.

I will work on a README file, this is a super cool feature!!

**Comment by julien-c** [comment]
(note that the READMEs will be in this repo in the future – that way we can collaborate on them/link them together/etc)

(see https://github.com/huggingface/transformers/issues/2520#issuecomment-579009439 if you haven't already)

Thanks a lot @jplu!
