### ISSUE TITLE
distilbert_multilingual_cased model for multiple language

### ISSUE THREAD

**Issue by divyag11** [huggingface/transformers#2684]
By when distilbert_multilingual_cased model is going to be released.because I tried to finetune the 
distilbert_multilingual_cased model , but it said "OSError: file distilbert-base-multilingual-cased not found", which means the above-mentioned model is not included in the list. Or let me know if I am doing any wrong assumption?

**Comment by LysandreJik** [comment]
Could you try to install a newer version of the library? The `distilbert-base-multilingual-cased` checkpoint is available in recent transformers versions, as you can see in the [source code](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_distilbert.py#L42).

**Comment by divyag11** [comment]
thanks a lot

**Comment by divyag11** [comment]
hi,
I am trying to finetune distilbert multilingual cased model, but i am getting error while training the model:
error is :
```
ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 8 array(s), for inputs ['output_1', 'output_2', 'output_3', 'output_4', 'output_5', 'output_6', 'output_7', 'output_8'] but instead got the following list of 1 arrays: [<tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=int64>]...

while with the same code using distilbert uncased , there is no such error.
Can you please check if there is some problem with distilbert multilingual cased model?

**Comment by divyag11** [comment]
please open the issue

**Comment by LysandreJik** [comment]
Hello, please open a new issue with information that can help us help you. Your software versions as well as the situation where this error happens being the minimum for us to help you, and a reproducible code example being the most useful.
