### ISSUE TITLE
German Bert tokenizer does not recognize (some) special characters (!,?,...)

### ISSUE THREAD

**Issue by andrey999333** [huggingface/transformers#2685]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):

**Bert**

Language I am using the model on (English, Chinese ...):

**German**

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ X] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ X] my own task or dataset: (give details below)

## To reproduce

`tokenizer = BertTokenizer.from_pretrained('bert-base-german-cased')`
`tokenizer.encode("Hallo!", add_special_tokens=False)`

returns:

`[5850, 26910, 2]`

where `2` is the index of '[UNK]' (unknown) token. Same would happen with 'Hallo?'. In the vocab.txt we have tokens '##!' and '##?' but not '?' or '!'. On the other hand some special characters are recognized, like ':' or ';'.

## Expected behavior

At least such common characters as '!' and '?' should be recognized by tokenizer

## Environment

* OS: Ubuntu
* Python version: 3.7
* `transformers` version (or branch): 2.3

**Comment by julien-c** [comment]
Sounds like this was fixed by @Timoeller in #3618, @andrey999333

**Comment by Timoeller** [comment]
Thanks for referencing. This bug should be fixed with the changes we applied to the vocabulary.
Find more infos in the separate issue here: deepset-ai/FARM/issues/60
