### ISSUE TITLE
`resize_token_embeddings` always sets `requires_grad` (of parameters in the resized embedding) to `True`

### ISSUE THREAD

**Issue by czy-orange** [huggingface/transformers#26861]
### System Info

- `transformers` version: 4.26.1
- Platform: Linux-3.10.0-1160.90.1.el7.x86_64-x86_64-with-glibc2.31
- Python version: 3.11.3
- Huggingface_hub version: 0.17.2
- PyTorch version (GPU?): 2.0.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

``` Python console
In [1]: from transformers import AutoModel

In [2]: model = AutoModel.from_pretrained('bert-base-uncased')

In [3]: model.embeddings.word_embeddings.weight.requires_grad
Out[3]: True

In [4]: model.embeddings.word_embeddings.weight.requires_grad = False

In [5]: model.embeddings.word_embeddings.weight.requires_grad
Out[5]: False

In [6]: model.resize_token_embeddings(30526)
Out[6]: Embedding(30526, 768)

In [7]: model.embeddings.word_embeddings.weight.requires_grad
Out[7]: True
```

### Expected behavior

The `resize_token_embeddings` method is not supposed to change the `requires_grad` attribute of parameters in the embedding layer. However, the current version of `resize_token_embeddings` always sets `requires_grad` to `True`, which is not a desirable behavior if the `requires_grad` in the old embedding is `False`. As far as I'm concerned, the `resize_token_embeddings` should only perform resizing and keep all the other attributes unchanged.

After I read the source code carefully, I found that `resize_token_embedding` internally creates a new embedding, which does not copy attributes from the old embedding except for `dtype` and `device`.

**Comment by ArthurZucker** [comment]
Hey! Seems like this has been the case for quite a while, but I think it makes sense to keep this info as well, preventing surprises. Would you like to open a PR for a fix?
