### ISSUE TITLE
Consider Adding Practical Usage Examples from Issue comment  #8771 to Documentation

### ISSUE THREAD

**Issue by rajveer43** [huggingface/transformers#26866]
I was going though the documentation of the file path `docs/source/jen/main_classes/deepspeed.md` and this line 

https://github.com/huggingface/transformers/blob/4b423e607455a7aca1edc4beaa713da58e78ef0b/docs/source/en/main_classes/deepspeed.md?plain=1#L206

 and saw below comment in documentation

`For some practical usage examples, please, see this [post](https://github.com/huggingface/transformers/issues/8771#issuecomment-759248400).`

https://github.com/huggingface/transformers/issues/8771#issuecomment-759248400

so I was wondering if we add those examples in a file or as tutorial.

PS. I did not check if this issue exists or any solution made. thank you for your patience.

**Comment by ArthurZucker** [comment]
I think we can keep it as is
