### ISSUE TITLE
use_flash_attention_2 not supported for AutoConfig and/or from_config

### ISSUE THREAD

**Issue by dakinggg** [huggingface/transformers#26878]
### Feature request

Let me know if I've missed something, but I think `use_flash_attention_2` is only supported via the `from_pretrained` API. So I think I have to do something like `config._flash_attn_2_enabled = use_flash_attention_2` outside of the normal transformers API in order to initialize a model with flash attention 2 from a config. It would be great if the config based APIs supported this argument too.

### Motivation

Parity across the ways of initializing a transformers model.

### Your contribution

N/A

**Comment by ArthurZucker** [comment]
cc @younesbelkada and @LysandreJik I remember we had a debate on whether or not this should be saved 😃

**Comment by LysandreJik** [comment]
Rather than being saved, I think @dakinggg is asking to be able to pass it when initializing the model with a config, so probably something like this:
```
model = BertModel(BertConfig(), use_flash_attention_2=True)
```

This seems reasonable to me, is that what you had in mind @dakinggg ?

**Comment by ArthurZucker** [comment]
Yeah, but then we would need to pop it to make sure it's not saved as we wanted to prevent this use case

**Comment by dakinggg** [comment]
Yes, that is correct @LysandreJik! With one minor addition to also support it via `AutoModel.from_config(cfg)` (maybe this ends up with the same code paths you mentioned, not sure of the exact internal implementation)

**Comment by dakinggg** [comment]
comment
