### ISSUE TITLE
Baichuan model is not working

### ISSUE THREAD

**Issue by Fangzhou-Ai** [huggingface/transformers#26882]
### System Info

using latest vllm by ```pip install vllm``` directly.

GPU: A100 @ 80 GB
System: Debian 10

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Simple test using current example
```bash
python benchmarks/benchmark_latency.py --trust-remote-code \
 --model baichuan-inc/Baichuan-13B-Base \
 --input-len 256 --output-len 256 \
 --batch-size 32 \
 --tensor-parallel 2
```

### Expected behavior

Error info : ```AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model'```

The error is due to the transformers 4.34.0, which is required or Mistral but imconpatiable with current vllm Baichuan model.

**Comment by ArthurZucker** [comment]
Hey! This is because of a recent update to `transformers`, the model on the hub should be updated to move the call of `super()__init__` at the end of the `__init__()` of the mdoel
