### ISSUE TITLE
some code part in documentation was translated to japanese

### ISSUE THREAD

**Issue by rajveer43** [huggingface/transformers#26895]
### System Info

https://moon-ci-docs.huggingface.co/docs/transformers/pr_1/ja/preprocessing#pad

some code part in documentation was mistakenly translated to Japanese.

 

### Information

- [X] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

-

### Expected behavior

```
batch_sentences = [
    "でもセカンドブレックファーストはどうなるの？",
    "セカンドブレックファーストについては知らないと思う、ピップ。",
    "イレブンジーズはどうなの？",
]
encoded_input = tokenizer(batch_sentences, padding=True)
print(encoded_input)
```

should be

```python
batch_sentences = [
    "でもセカンドブレックファーストはどうなるの？", #english text
    "セカンドブレックファーストについては知らないと思う、ピップ。", #english text
    "イレブンジーズはどうなの？", #english text
]
encoded_input = tokenizer(batch_sentences, padding=True)
print(encoded_input)
```

**Comment by ArthurZucker** [comment]
cc @stevhliu
