### ISSUE TITLE
Hardware requirements for BERT QA inference

### ISSUE THREAD

**Issue by tothniki** [huggingface/transformers#2690]
Hi,

I am using **bert-large-uncased-whole-word-masking-finetuned-squad** model for QA inference.

I used my laptop's CPU to build the pipeline and try it out. 

Now I want to deploy it, and so I would like to know what is the minimum hardware requirement?(If I use the same settings as in your usage example script)?

I am more interested in the **minimum size of the GPU**. 
Of course I don't want it to be too slow. Is there any studies on this matter, or measurement?

Thanks!

**Comment by julien-c** [comment]
@LysandreJik wrote an article about benchmarking transformers (focusing on inference) that might be of interest to you.

**Comment by tothniki** [comment]
Thanks for the reply!
I checked the benchmarks, there you tested with 16GB GPU and bert-base model. I suppose then I have to try different, smaller size of GPUs, and figure out which can handle my task.
It is really informative though, nice work.
