### ISSUE TITLE
Whisper tokenizer decode function ignores timestamp tokens after v4.34.0 (the big refactor)

### ISSUE THREAD

**Issue by versae** [huggingface/transformers#26934]
### System Info

- `transformers` version: 4.34.0
- Platform: Linux-5.19.0-40-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.3.1
- Accelerate version: 0.20.3
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Tensorflow version (GPU?): 2.12.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.6.11 (cpu)
- Jax version: 0.4.12
- JaxLib version: 0.4.12
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@sanchit-gandhi, @peregilk 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Install `transformers>=4.34.0` and run this code:

```python
from transformers import AutoTokenizer, AddedToken

tokenizer = AutoTokenizer.from_pretrained("openai/whisper-large-v2")
tokenizer.set_prefix_tokens(language="en", task="transcribe", predict_timestamps=True)

print(
    tokenizer.encode("<|0.00|>", add_special_tokens=False),
    tokenizer.decode(tokenizer.encode("<|0.00|>"))
)
```

The output will be

```bash
[50364] <|startoftranscript|><|en|><|transcribe|><|endoftext|>
```

Which ignores the timestamp token when decoding.

### Expected behavior

With versions of `transformers<4.34.0`, the timestamp tokens will be correctly decoded. The same code will produce:

```bash
[50364] <|startoftranscript|><|en|><|transcribe|><|0.00|><|endoftext|>
```

**Comment by versae** [comment]
Well, based on #26054, it seems a new undocumented parameter `decode_with_timestamps` has to be passed in:

```python
print(
    tokenizer.encode("<|0.00|>", add_special_tokens=False),
    tokenizer.decode(tokenizer.encode("<|0.00|>"), decode_with_timestamps=True)
)
```
```bash
[50364] <|startoftranscript|><|en|><|transcribe|><|0.00|><|endoftext|>
```

It seems to me that if the timestamp tokens are there and the user sets `predict_timestamps=True`, `decode_with_timestamps` should default to `True` or maybe not even exist as a parameter?

**Comment by ArthurZucker** [comment]
cc @sanchit-gandhi

**Comment by ArthurZucker** [comment]
I think we have some of this for BC but also performance reasons, cc @sanchit-gandhi

**Comment by versae** [comment]
That would be strange. With the previous behavior, and before the OpenAI Whisper models included the timestamp tokens, if you added them yourself using the `.add_tokens()` method, by default those tokens would be returned when deciding as well.

**Comment by versae** [comment]
Thanks for the explanation, @sanchit-gandhi! I still think that if the user sets `predict_timestamps=True` is because is expecting to see timestamp tokens in the output, which would make `decode_with_timestamps` default to `True`.

**Comment by sanchit-gandhi** [comment]
Indeed this is how we set it in the `pipeline`: one input argument `return_timestamps` triggers all of the timestamp args under the hood. However, for the `model` + `processor` API it needs to be set twice, each time by the user. This is because there's no coupling between the `model` and the `processor`, and so we can't propagate the arguments forward automatically.

**Comment by loretoparisi** [comment]
> Well, based on #26054, it seems a new undocumented parameter `decode_with_timestamps` has to be passed in:
> 
> ```python
> print(
>     tokenizer.encode("<|0.00|>", add_special_tokens=False),
>     tokenizer.decode(tokenizer.encode("<|0.00|>"), decode_with_timestamps=True)
> )
> ```
> 
> ```shell
> [50364] <|startoftranscript|><|en|><|transcribe|><|0.00|><|endoftext|>
> ```
> 
> It seems to me that if the timestamp tokens are there and the user sets `predict_timestamps=True`, `decode_with_timestamps` should default to `True` or maybe not even exist as a parameter?

@versae my solution was the following

```python
predicted_ids = model.generate(input_features,
                                            max_length=model.config.max_target_positions,
                                            num_beams=5,
                                            length_penalty=1.0,
                                            repetition_penalty=1.2,
                                            do_sample=do_sample,
                                            temperature=temperature,
                                            return_dict_in_generate=True,
                                            output_scores=True,
                                            output_hidden_states=True,
                                            output_attentions=True,
                                            early_stopping=early_stopping)
            
                # Decode the outputs, including the timestamps
                decoded_transcription = processor.batch_decode(predicted_ids['sequences'], skip_special_tokens=False)[0]
                decoded_tokens = processor.tokenizer.tokenize(decoded_transcription)
                
                # Extract timestamps
                transcription_chunk = []
                current_text = []
                current_start_time = None
                for token in decoded_tokens:
                    if token.startswith("<|"):
                        if token not in {"<|startoftranscript|>", "<|transcribe|>", "<|notimestamps|>", "<|en|>", "<|endoftranscript|>"}:
                            if current_text:
                                end_time = start_idx / sampling_rate + processor.tokenizer.convert_tokens_to_ids([token])[0] * HOP_LENGTH / sampling_rate
                                transcription_chunk.append({
                                    "start_time": current_start_time,
                                    "end_time": end_time,
                                    "text": " ".join(current_text)
                                })
                                current_text = []
                            current_start_time = start_idx / sampling_rate + processor.tokenizer.convert_tokens_to_ids([token])[0] * HOP_LENGTH / sampling_rate
                    else:
                        if not current_text:
                            current_start_time = start_idx / sampling_rate
                        current_text.append(token.replace("Ġ", " "))  # Clean up token format

                if current_text:
                    end_time = len(audio_chunk) / sampling_rate
                    transcription_chunk.append({
                        "start_time": current_start_time,
                        "end_time": end_time,
                        "text": " ".join(current_text)
                    })
```
