### ISSUE TITLE
get_linear_schedule_with_warmup method can't be found in optimization.py

### ISSUE THREAD

**Issue by arseneyao** [huggingface/transformers#2695]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): BERT

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

My transformer was downloaded from anaconda cloud by using command "conda install -c conda-forge transformers", when I tried to use AdamW as what you show in the example, I found there is no **get_linear_schedule_with_warmup** in the **transformers.optimization.py** file for me to create a scheduler.

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

## Environment

* OS:
* Python version:
* PyTorch version:
* `transformers` version (or branch):
* Using GPU ?
* Distributed or parallel setup ?
* Any other relevant information:

**Comment by BramVanroy** [comment]
There clearly is:

https://github.com/huggingface/transformers/blob/0aa40e9569a71306036de3a217eed55521699604/src/transformers/optimization.py#L47-L59

Please fill out the complete template - it's there for a reason.

**Comment by arseneyao** [comment]
I thought my transformers was the lastest version, but I found it's not when I checked it on the anaconda cloud [https://anaconda.org/conda-forge/transformers](url). The problem is solved after reinstalling, Thanks for you reply :)

**Comment by BramVanroy** [comment]
In the future, please fill out the complete template. Please close this question if you don't have any more questions.

**Comment by arseneyao** [comment]
OK
