### ISSUE TITLE
deepspeed Integration error

### ISSUE THREAD

**Issue by SingL3** [huggingface/transformers#26958]
### System Info

N/A
See Bug report for DS [4194](https://github.com/microsoft/DeepSpeed/issues/4194) and [4533](https://github.com/microsoft/DeepSpeed/issues/4533)

### Who can help?

@pac

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

N/A

### Expected behavior

Deepspeed training successfully.

**Comment by ArthurZucker** [comment]
hey. If you want use to help you according to the contribution guidelines could you write what is your issue here, with small reproducible snippet N
