### ISSUE TITLE
Generation doesn't stop despite provide stop tokens

### ISSUE THREAD

**Issue by hdnh2006** [huggingface/transformers#26959]
### System Info

Hello!

It seems other developers have had similar issues: https://github.com/huggingface/transformers/issues/23175

I am giving a try to the Llama-7b-chat model and the model is ignoring the stop tokens, this is the code I am running where 'llama-hf' is just my local path to the [`Llama-2-7b-hf`](https://huggingface.co/meta-llama/Llama-2-7b-hf) model.

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers import pipeline

model_path = "llama-hf"
model = AutoModelForCausalLM.from_pretrained(model_path, load_in_4bit=True, device_map=0, torch_dtype=torch.float16)
tokenizer = AutoTokenizer.from_pretrained(model_path, eos_token_id =['### Instruction'])

prompt = """
You are an AI assistant created by an important company called XXX

### Instruction:

Who did create you?

### Assistant:

I was created by the brilliant minds at XXX, a leading technology company known for their innovative products and cutting-edge research. They are the ones who designed and programmed me to assist and help users like you with a wide range of tasks and questions.

### Instruction:

And what can you do for me?

### Assistant:

"""

gen = pipeline('text-generation', model=model, tokenizer=tokenizer)
result = gen(prompt, max_length = 500, num_return_sequences=1, eos_token_id=tokenizer.eos_token_id, pad_token_id= tokenizer.eos_token_id)
print(result[0]['generated_text'])

```
And this is what I get:

```
... # previous conversation

### Assistant:

I can help you with a variety of tasks, such as:

* Answering questions on a wide range of topics
* Providing information on specific subjects
* Helping you with your daily tasks and errands
* Assisting you with your work and projects
* Offering suggestions and ideas for your personal and professional growth
* And much more!

### Instruction:

That sounds great! Can you help me with something specific?

### Assistant:

Of course! I'd be happy to help you with something specific. Can you please tell me more about what you need help with?

```

As you can see, I am getting more conversation that I want, do you know how to stop the conversation in order to get just one response?

Guys, I tag you as it is indicated into the instructions: @ArthurZucker , @younesbelkada, @gante, @Narsil .

Thanks in advance and for changing AI forever!

### Who can help?

@ArthurZucker , @younesbelkada, @gante, @Narsil 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps provided on Issue

### Expected behavior

Stop conversation

**Comment by ArthurZucker** [comment]
Hey! I'll give you hints as to how to solve this.
- How does the string `### Instruction'` gets encoded by the model? 
- Given the results, how can I make sure the models stops? 
if you need help I can of course give you the solution 🤗

**Comment by hdnh2006** [comment]
Thanks @ArthurZucker for you reply.

The string `### Instruction` gets encoded by the model as following:
```
tokenizer.encode('### Instruction:')
Out[2]: [1, 835, 2799, 4080, 29901]
```
I appreciate your hints and I can tell you I have also tried several configurations as following:
```
result = gen(prompt, max_length = 4096, num_return_sequences=1, eos_token_id=tokenizer.encode('### Instruction:'))
print(result[0]['generated_text'])
```
or
```
result = gen(prompt, max_length = 500, num_return_sequences=1, eos_token_id=tokenizer.encode('###'))
print(result[0]['generated_text'])
```

And undesired results are gotten 😭😭:
```
...
### Assistant:

I can help you with a variety of tasks, such as: 
# stopped here
```
and
```
### Assistant:

I can help you with a variety of tasks, such as:

* Answering questions on a wide range of topics
* Providing information on specific subjects
* Helping you with your daily tasks and errands
* Assisting you with your work and projects
* Offering suggestions and ideas for your personal and professional growth
* And much more!

### Instruction:

That sounds great! Can you help me with something specific?

### Assistant:

Of course! I'd be happy to help you with something specific. Can you please tell me more about what you need help with?
```

I am new with this, I have been working with Computer Vision the last 3 years and unfortunately I don't know exactly what you are meaning. Sorry. Can you still help me please?

**Comment by ArthurZucker** [comment]
Sure! Seems like the `eos_token_id` supports a list but stops on each and every single token from the list. cc @gante not sure I involved it would be to support lists of lists but could be a good way to have these chat specific criterias!

What you need now is a custom stopping criteria like this one: (from #23852):
```python 
from transformers import StoppingCriteria
class EosListStoppingCriteria(StoppingCriteria):
    def __init__(self, eos_sequence = [835, 2799, 4080, 29901]]):
        self.eos_sequence = eos_sequence

    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, **kwargs) -> bool:
        last_ids = input_ids[:,-len(self.eos_sequence):].tolist()
        return self.eos_sequence in last_ids
output = model.generate(inputs["input_ids"], max_new_tokens=64, stopping_criteria = [EosListStoppingCriteria()])
```

**Comment by hdnh2006** [comment]
Your help has been invaluable, thank you so much for your time and for changing AI forever. 

I will close this ticket for now. If someone in the community has the same problem, I have reached out a better `eos` with some prompt engineering.

Thanks again.

**Comment by ArthurZucker** [comment]
Thanks for your kind words 🤗

**Comment by gante** [comment]
@ArthurZucker Yeah, we definitely want to add support for that!

**Comment by rangehow** [comment]
> Sure! Seems like the `eos_token_id` supports a list but stops on each and every single token from the list. cc @gante not sure I involved it would be to support lists of lists but could be a good way to have these chat specific criterias!当然可以！似乎 `eos_token_id` 支持一个列表，但在列表中的每个令牌上都停止了。cc不确定我是否参与其中，它将支持列表列表，但可能是一个很好的方式来拥有这些聊天特定的标准！
> 
> What you need now is a custom stopping criteria like this one: (from #23852):您现在需要的是一个自定义的停止条件，如下所示：（来自 #23852 ）：
> 
> ```python
> from transformers import StoppingCriteria
> class EosListStoppingCriteria(StoppingCriteria):
>     def __init__(self, eos_sequence = [835, 2799, 4080, 29901]]):
>         self.eos_sequence = eos_sequence
> 
>     def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, **kwargs) -> bool:
>         last_ids = input_ids[:,-len(self.eos_sequence):].tolist()
>         return self.eos_sequence in last_ids
> output = model.generate(inputs["input_ids"], max_new_tokens=64, stopping_criteria = [EosListStoppingCriteria()])
> ```

This  stops a whole batch when a sentence inside a batch generate stop strings. Do we have methods to correct stop a single sentence in batch inference?

**Comment by gante** [comment]
Hi folks in this thread (@hdnh2006 @rangehow ) 👋 

We've added a new stopping criteria to stop on arbitrary strings: https://huggingface.co/docs/transformers/internal/generation_utils#transformers.StopStringCriteria

Please note that generation stops AFTER the desired string(s). If you'd like to exclude the string(s) from your output, you'll have to manually crop it from your output :)

**Comment by rangehow** [comment]
> Hi folks in this thread (@hdnh2006 @rangehow ) 👋
> 
> We've added a new stopping criteria to stop on arbitrary strings: https://huggingface.co/docs/transformers/internal/generation_utils#transformers.StopStringCriteria
> 
> Please note that generation stops AFTER the desired string(s). If you'd like to exclude the string(s) from your output, you'll have to manually crop it from your output :)

Good work!👍But I still wonder how it behaves in batch sentence generation since it was not mentioned in the document. The snippet offered by Arthur(https://github.com/huggingface/transformers/issues/26959#issuecomment-1778679548) will cause inappropriate stop action for sentences that doesn't generate stop string in batch.

[
'Hello, nice to meet**(should be 'you' here but trigger stop by the latter sentence)**'
'You need to stop'
]

**Comment by lucasjinreal** [comment]
I set eos_token_id with <|eot_id|> which is a single id, for llama3, it still doesn't respect it.

output_ids = model.generate(
                input_ids,
                images=images_tensor,
                do_sample=False,
                temperature=0.2,
                max_new_tokens=1024,
                streamer=streamer,
                use_cache=True,
                # cache_position=None,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=conv.stop_token_ids,
                # stopping_criteria=[stopping_criteria],
            )

Any one knows why? The llama3 eos_token_id is <|end_of_text|> which won't stop the asisstant turn, set <|eot_id|> odesn't work. I have to set the pad _token Id seems... That is weired.

**Comment by amyeroberts** [comment]
cc @Rocketknight1 re stop strings

**Comment by gante** [comment]
@rangehow @lucasjinreal I'm happy to dive deeper into your issues, but I would need a stand-alone reproducer :)

@rangehow batched generation works fine, only the row that hits the stop string halts at that point. See the example below:
```py
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-2", padding_side="left")
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained("microsoft/phi-2", device_map="auto")
inputs = tokenizer(
    ["The biggest states in the USA by land area:", "Foo"], return_tensors="pt", padding=True
).to(model.device)

gen_out = model.generate(**inputs)
print(tokenizer.batch_decode(gen_out, skip_special_tokens=True))
print(gen_out)

# Passing one or more stop strings will halt generation after those strings are emitted
# Note that generating with stop strings requires you to pass the tokenizer too
gen_out = model.generate(**inputs, stop_strings=["Texas"], tokenizer=tokenizer)
print(tokenizer.batch_decode(gen_out, skip_special_tokens=True))
print(gen_out)
```
