### ISSUE TITLE
Missing `do_sample` argument for run_generation example

### ISSUE THREAD

**Issue by sysu-zjw** [huggingface/transformers#2696]
# ❓ Questions & Help

It seems the arguments `k`, `p`, `temperature` are disabled because `do_sample` is set to False by default. Thus, [run_generation.py](https://github.com/huggingface/transformers/blob/master/examples/run_generation.py)  will always use greedy decoding no matter how the `k`, `p`, `temperature` are set, which is kind of misleading. 

I think `do_sample` argument should be included in the code.

**Comment by LysandreJik** [comment]
You're absolutely correct, I pushed a fix with 7365f01!

**Comment by minimaxir** [comment]
Ran into this issue myself by accident.

IMO, `do_sample=True` should be the default behavior for `generate()` since that's more in line with user expectations.

**Comment by LysandreJik** [comment]
I agree with you, the default should be set to `True`. I've changed the default in 6c1b235.

**Comment by thomwolf** [comment]
Decision reverted in #3298 (see the PR for discussion and details).
New default to `do_sample==False`.
