### ISSUE TITLE
Resize failing with torch and np objects

### ISSUE THREAD

**Issue by rafaelpadilla** [huggingface/transformers#26986]
### System Info

`transformers.__version__: '4.34.1'`

### Who can help?

@rafaelpadilla @amyeroberts 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python 
import torch
from transformers.image_transforms import resize

# dummy torch image
img = torch.zeros((3, 100,100), dtype=torch.uint8)
# any new size
new_size = (20, 20)
resized_img = resize(img, new_size)

>>> Traceback (most recent call last):
>>>   File "<stdin>", line 1, in <module>
>>>   File "/home/rafael/anaconda3/envs/hf/lib/python3.11/site-packages/transformers/image_transforms.py", line 326, in resize
>>>     do_rescale = _rescale_for_pil_conversion(image)
>>>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>>>   File "/home/rafael/anaconda3/envs/hf/lib/python3.11/site-packages/transformers/image_transforms.py", line 139, in _rescale_for_pil_conversion
>>>     elif np.allclose(image, image.astype(int)):
>>>                             ^^^^^^^^^^^^
>>> AttributeError: 'Tensor' object has no attribute 'astype'. Did you mean: 'dtype'?
```

### Expected behavior

`resize()` should be flexible and accept any image type  (`PIL.Image.Image` or `np.ndarray` or `torch.Tensor`) as in [here](https://github.com/huggingface/transformers/blob/main/src/transformers/image_transforms.py#L289).

However, it fails if image type is torch.

The reason occurs because the `_rescale_for_pil_conversion()` is being called [here](https://github.com/huggingface/transformers/blob/main/src/transformers/image_transforms.py#L326) and assumes that the input `image` is `np.array`.

**Comment by daniilgaltsev** [comment]
Hei! This seems to be quite straightforward. I can work on this if help is needed.

**Comment by rafaelpadilla** [comment]
Hi @daniilgaltsev ,

Thanks for your interest in fixing it. 

I had just spoken with @amyeroberts , one of our core maintainers, and she explained me that this is actually not a bug.
In fact, the image transformations functions like `resize`, `normalize`, `center_crop`, etc should work with numpy arrays. So, this is just a very small docstring and typing fix. 

In [this line](https://github.com/huggingface/transformers/blob/main/src/transformers/image_transforms.py#L289), we just needed to replace
```python
image (`PIL.Image.Image` or `np.ndarray` or `torch.Tensor`):
```
by
```python
image (`np.ndarray`):
```
If you still want to contribute, please, feel free to take it 🤗 
Also, please, tag your PR with `#Close #26986`.
