### ISSUE TITLE
Memory leak on trainer's evaluation

### ISSUE THREAD

**Issue by omermazig** [huggingface/transformers#26993]
### System Info

I run a training process Based on [this](https://github.com/huggingface/notebooks/blob/main/examples/video_classification.ipynb) notebook, and I use a dataset of 8000 train videos. 

My inference process is memory-heavy. My val dataset's clip sampler is "random_multi", which means that for every video I take 5 clips of it, pass them to the model, and aggregate the results together for classification.

My problem is that there seems to be a memory leak in the evaluation process. I run on colab, and I can see that at each epoch, the memory usage stays the same throughout the epoch, goes up on evaluation, and stays there for the next epoch, and so on. So eventually after 2 or 3 epochs I'm running out of memory (I'm getting the generic "RuntimeError: Failed to load video after 10 retries", but I see the memory is full so I'm pretty sure that's the problem).

Is there an explanation for it? Is there something being saved **in memory** between epochs and if so, is there a way to release it? What should I do?

Thank you!

### Who can help?

@muellerzr and @pacman100

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

No way really. If it's needed I can supply my own notebook.

### Expected behavior

The memory usage should stay the same between epochs, and the memory needed for the evaluation process at the and of each epoch should be freed by the time the next epoch starts

**Comment by muellerzr** [comment]
@omermazig is the notebook 1:1 that one, bar your dataset? Do you experience the memory leak occurring in that notebook as well? When testing locally, I couldn't indentify any memory leaks in the basic scripts that we have (like `run_glue.py`)

**Comment by omermazig** [comment]
Sorry for the late response. Apparently this assumption:

>  (I'm getting the generic "RuntimeError: Failed to load video after 10 retries", but I see the memory is full so I'm pretty sure that's the problem)

was wrong, and after I stopped working with a dataset from google drive, and copy it to the machine before training (instead of working with the path to google drive), this ceases to happen.
