### ISSUE TITLE
pip install transformers==4.34.1 not usable on SDXL automatic1111 - conflict with tokenizer and huggingface_hub

### ISSUE THREAD

**Issue by DennisBalkan** [huggingface/transformers#27004]
### System Info

pip install transformers==4.34.1 not usable on SDXL automatic1111 - conflict with tokenizer and huggingface_hub. it s very long test. try it yourself to update and you will see all conflict steps. 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

updating without conflicts

### Expected behavior

updating without conflicts

**Comment by ArthurZucker** [comment]
Hello, sorry I have no idea how to reproduce your issue or use this library. A snippet or a traceback would bel helpful! 🤗
