### ISSUE TITLE
'Owlv2Processor' object has no attribute 'post_process'

### ISSUE THREAD

**Issue by dinhanhx** [huggingface/transformers#27008]
### System Info

- `transformers` version: 4.35.0.dev0
- Platform: Linux-5.15.133+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.0 (True)
- Tensorflow version (GPU?): 2.12.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.7.2 (gpu)
- Jax version: 0.4.13
- JaxLib version: 0.4.13
- Using GPU in script?: NVIDIA P-100
- Using distributed or parallel set-up in script?: Non

### Who can help?

@NielsRogge 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the example code from huggingface model repo, https://huggingface.co/google/owlv2-base-patch16,

Kaggle notebook, https://www.kaggle.com/inhanhv/google-owlv2 

### Expected behavior

'Owlv2Processor' object has attribute 'post_process'

**Comment by NielsRogge** [comment]
Hi,

Thanks for flagging (note that you can also opening a discussion on the huggingface model repo). The model cards are now updated, one needs to use `post_process_object_detection` instead of `post_process`.

**Comment by dinhanhx** [comment]
I understand. Thanks for the help.
