### ISSUE TITLE
Unable to load FuyuProcessor, FuyuForCausalLM from transformers

### ISSUE THREAD

**Issue by akshaytheau** [huggingface/transformers#27009]
### System Info

I tried running the code on google colab. I am using the latest transformers verison 4.34.1

@ArthurZucker 

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Try importing FuyuProcessor and FuyuforCasualLM from transformers

### Expected behavior

It is should be imported properly.

**Comment by ArthurZucker** [comment]
Hey! That's is expected, you need to use the `main` branch and install from source as t is not part of the latest release. 
`pip install git+https://github.com/huggingface/transformers`

**Comment by saeedasadibagloee** [comment]
it didnt work for me, i m trying to run it through colab

**Comment by ArthurZucker** [comment]
You need to reload the kernel
