### ISSUE TITLE
transformers==4.34.1 have error for load chatglm model

### ISSUE THREAD

**Issue by Lzhang-hub** [huggingface/transformers#27015]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.34.1
- Platform: Linux-4.19.96-x86_64-with-glibc2.31
- Python version: 3.10.10
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.23.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

load chatglm model failed: 
```
File "/root/.cache/huggingface/modules/transformers_modules/tokenization_chatglm.py", line 112, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/root/.cache/huggingface/modules/transformers_modules/tokenization_chatglm.py", line 108, in vocab_size
    return self.tokenizer.n_words
AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'. Did you mean: 'tokenize'?
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformer import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b")

### Expected behavior

load model correct

**Comment by ArthurZucker** [comment]
Hey! This uses `trust_remote_code = True` and has custom code on the hub! Recommend you to open an issue on this repo!

**Comment by Lzhang-hub** [comment]
transformers==4.33.3 is work well

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/23/2023 19:10 |
| To | huggingface/transformers ***@***.***> |
| Cc | Lzhang-hub ***@***.***>,
Author ***@***.***> |
| Subject | Re: [huggingface/transformers] transformers==4.34.1 have error for load chatglm model (Issue #27015) |

Hey! This uses trust_remote_code = True and has custom code on the hub! Recommend you to open an issue on this repo!
