### ISSUE TITLE
Hashlib usage is underspecified

### ISSUE THREAD

**Issue by DueViktor** [huggingface/transformers#27034]
### Feature request

From python 3.9 hashlib introduced the `usedforsecurity` argument:
> Changed in version 3.9: All hashlib constructors take a keyword-only argument usedforsecurity with default value True. A false value allows the use of insecure and blocked hashing algorithms in restricted environments. False indicates that the hashing algorithm is not used in a security context, e.g. as a non-cryptographic one-way compression function.

`transformers` use hashing in many cases where the purpose is indeed _not for security_ purposes. This should be specifed in the code.

### Motivation

Transformers use MD5 from hashlib, which is not a secure algorithm, but are not specifying that it is for other purposes than security. This is causing issues for organisations following certain security standard. FIPS compliance could be an example. 

### Your contribution

I will attach a PR specifying the usage of hashlib algorithms. Since `usedforsecurity` is only specified from 3.9+ and transformers support 3.6+, I'll add a functionality to detect python version and change kwargs based on that.

**Comment by ArthurZucker** [comment]
Hey! Thanks for reporting I'll see if this relevant for us 🤗

**Comment by DueViktor** [comment]
Great @ArthurZucker. The pull request have passed all tests already and are ready to merge. 
No behaviour is changed. 

My guess is that pretty much all federal systems in the world would have this issue.
> Federal Information Processing Standards (FIPS) 140-2 is a mandatory standard for the protection of sensitive or valuable data within Federal systems. - https://www.wolfssl.com/license/fips/

**Comment by Wauplin** [comment]
Hey @DueViktor! Coming back to you about this request. We've finally specified hashlib usage in [huggingface_hub](https://github.com/huggingface/huggingface_hub/pull/1782), [transformers](https://github.com/huggingface/transformers/pull/27483), [datasets](https://github.com/huggingface/datasets/pull/6414) and [diffusers](https://github.com/huggingface/diffusers/pull/5790). Everything's merged now so I'll close this issue. Thanks again for the heads up!

**Comment by DueViktor** [comment]
Hi @Wauplin! Thanks so much for the update and for addressing the hashlib usage across all those libraries. Appreciate your team's prompt action on this matter. Keep up the fantastic work!
