### ISSUE TITLE
cannot import name 'SeamlessM4TModel' from 'transformers'

### ISSUE THREAD

**Issue by druskacik** [huggingface/transformers#27036]
### System Info

transformers 4.34.1
python 3.10.12
Windows

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying to use the HuggingFace implementation of the SeamlessM4T model available here: https://huggingface.co/facebook/hf-seamless-m4t-medium .

However, importing `SeamlessM4TModel` from `transformers` raises an `ImportError`:

```python
from transformers import AutoProcessor, SeamlessM4TModel

>>> ImportError                               Traceback (most recent call last)
Cell In[5], line 1
----> 1 from transformers import AutoProcessor, SeamlessM4TModel

ImportError: cannot import name 'SeamlessM4TModel' from 'transformers' (C:\Users\rober\.conda\envs\product_scanner\lib\site-packages\transformers\__init__.py)
```

I use the latest `transformers` version, `4.34.1`.

### Expected behavior

Expected behaviour is to import the `SeamlessM4TModel` without an error.

**Comment by ArthurZucker** [comment]
Hey, that is expected as it is not part of the latest release. Make sure to install using `pip install git+https://github.com/huggingface/transformers.git`
