### ISSUE TITLE
deprecation warning from transformers itself

### ISSUE THREAD

**Issue by pseudotensor** [huggingface/transformers#27049]
### System Info

https://github.com/huggingface/transformers/blob/6cbc1369a330860c128a1ba365f246751382c9e5/src/transformers/generation/configuration_utils.py#L717

This is using use_auth_token even though it's deprecated, so always showing warning despite no user mishandling.

### Who can help?

@gante 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

should be obvious from code line shared

### Expected behavior

No deprecation warning

**Comment by ArthurZucker** [comment]
Yep, a CTRL + F in transformers indicates that this is also the case for some peft calls here and there. I'll open a pr for a fix, thanks for reporting!
