### ISSUE TITLE
Number of tokens mismatch for Codellama-34b-hf

### ISSUE THREAD

**Issue by irenedea** [huggingface/transformers#27053]
### System Info

transformers 4.34.1

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoTokenizer, PretrainedConfig, CodeLlamaTokenizerFast
model = 'codellama/CodeLlama-34b-hf'
tokenizer = AutoTokenizer.from_pretrained(model)
config = PretrainedConfig.from_pretrained(model)

assert len(tokenizer) <= config.vocab_size, f'Got tokenizer size {len(tokenizer)} and vocab size {config.vocab_size}'
```

### Expected behavior

len(tokenizer) is expected to be less than or equal to config.vocab_size, but we get: `AssertionError: Got tokenizer size 32004 and vocab size 32000`.

**Comment by irenedea** [comment]
Hey @ArthurZucker , would you be able to help with this? I don't think https://github.com/huggingface/transformers/issues/26156  was fully resolved. Thank you!

**Comment by ArthurZucker** [comment]
Hey, yes for sure!

**Comment by dakinggg** [comment]
Hey @ArthurZucker any ETA on when this might be resolved?

**Comment by amyeroberts** [comment]
@dakinggg Arthur is off for a week. If someone in the community wants to open a PR to resolve this before then feel free to ping me for a review.

**Comment by dakinggg** [comment]
FYI for anyone else who ends up here, I've worked around this by initializing the tokenizer like so:
`t = transformers.AutoTokenizer.from_pretrained('codellama/CodeLlama-7b-hf`, prefix_token=None, middle_token=None, suffix_token=None, eot_token=None, fill_token=None)`

**Comment by ArthurZucker** [comment]
Yep that's the fix, I'm gonna push it to the hub today! 😉 Just gotta make sure this errors out properly on the FMI
