### ISSUE TITLE
Add persistent_workers parameter to Dataloader

### ISSUE THREAD

**Issue by Sorrow321** [huggingface/transformers#27058]
### Feature request

**persistent_workers** is a parameter that can be passed to Dataloader. It's set to **False** by default. What it does ([quote](https://discuss.pytorch.org/t/what-are-the-dis-advantages-of-persistent-workers/102110/2)):

> With this option to false, every time your code hits a line line for sample in dataloader:, it will create a brand new set of workers to do this loading and will kill them on exit.
> Meaning that if you have multiple dataloaders, the workers will be killed when you are done with one instantly.
> 
> If you make them persist, these workers will stay around (with their state) waiting for another call into that dataloader.
> 
> Setting this to True will improve performances when you call into the dataloader multiple times in a row (as creating the workers is expensive). But it also means that the dataloader will have some persistent state even when it is not used (which can use some RAM depending on your dataset).

Currently there is no option to pass **persistent_workers=True** to internal Dataloader without inheriting from **Trainer** class. Here is the code snippet from **trainer.py**:
  
```
def get_train_dataloader(self) -> DataLoader:
    """
    Returns the training [`~torch.utils.data.DataLoader`].

    Will use no sampler if `train_dataset` does not implement `__len__`, a random sampler (adapted to distributed
    training if necessary) otherwise.

    Subclass and override this method if you want to inject some custom behavior.
    """
    # ...
    # (some code)
    # ...
    return DataLoader(
        train_dataset,
        batch_size=self._train_batch_size,
        sampler=train_sampler,
        collate_fn=data_collator,
        drop_last=self.args.dataloader_drop_last,
        num_workers=self.args.dataloader_num_workers,
        pin_memory=self.args.dataloader_pin_memory,
        worker_init_fn=seed_worker,
    )
```

I suggest to add this parameter to **TrainingArguments** class. Set it to **False** by default to not break anyone's pipeline. 

### Motivation

Motivation is very simple: setting this parameter to **True** can speed up training process in some cases (but will require more RAM). 

### Your contribution

I can make the PR

**Comment by ArthurZucker** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
A PR for this would be great @Sorrow321! :)
