### ISSUE TITLE
Load from tf2.0 checkpoint fail

### ISSUE THREAD

**Issue by stevewyl** [huggingface/transformers#2706]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Bert

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Download tf2.0 checkpoint from https://storage.googleapis.com/cloud-tpu-checkpoints/bert/keras_bert/uncased_L-12_H-768_A-12.tar.gz
2. unpack the model tar.gz to `bert_models` folder
3. start an iPython console and type following codes: 
```python
import tensorflow as tf
from transformers import TFBertModel, BertConfig
config = BertConfig.from_json_file("./bert_models/uncased_L-12_H-768_A-12/bert_config.json")
model = TFBertModel.from_pretrained("./bert_models/uncased_L-12_H-768_A-12/bert_model.ckpt.index", config=config)
```
4. I check the original code from tf2.0 and found they didn't implement model.load_weights when by_name is True. Error is following:
NotImplementedError: Weights may only be loaded based on topology into Models when loading TensorFlow-formatted weights (got by_name=True to load_weights)

## Environment

* OS: CentOS Linux release 7.4.1708 (Core)
* Python version: 3.7.6
* PyTorch version: 1.3.1
* `transformers` version (or branch):
* Using GPU ? Yes
* Distributed or parallel setup ? No
* Any other relevant information:

**Comment by LysandreJik** [comment]
Hi, in order to convert an official checkpoint to a checkpoint readable by `transformers`, you need to use the script `convert_bert_original_tf_checkpoint_to_pytorch`. You can then load it in a `BertModel` (PyTorch) or a `TFBertModel` (TensorFlow), by specifying the argument `from_pt=True` in your `from_pretrained` method.
