### ISSUE TITLE
Make it possible to  pass `torch_dtype` argument as a string so it's easier to serialize

### ISSUE THREAD

**Issue by tokestermw** [huggingface/transformers#27087]
### Feature request

Hi, it would be nice if we can pass `torch_dtype` as a string.

```python
from transformers import pipeline

# this
m = pipeline('text-generation', 'Mistral-7B-Instruct-v0.1', device=0, low_cpu_mem_usage=True, torch_dtype=torch.float16)

# or that
m = pipeline('text-generation', 'Mistral-7B-Instruct-v0.1', device=0, low_cpu_mem_usage=True, torch_dtype='float16')
```

### Motivation

* It's common to use a config file (e.g. yaml) to pass in arguments to `from_pretrained`, but `torch_dtype` requires `torch`. e.g. we can't use the `assemble` method in [spacy-llm](https://github.com/explosion/spacy-llm/blob/7a0460ce112ae1fe783dd100b4d32e56c282919f/spacy_llm/util.py#L37).
* For small GPUs (e.g. T4), we can't load any models 7B and higher (cuda memory error) unless specifying `torch_dtype=torch.float16` (`torch_dtype='auto'` doesn't work either) (assuming not using 8-bit quantization or lower).

### Your contribution

Yes can make a PR so if `torch_dtype` is a string, we convert to `torch` type.

e.g. `'float16'` to `torch.float16`

**Comment by KossaiSbai** [comment]
I am happy to take a look at this!
