### ISSUE TITLE
Issue with Installing black in Python - needs to install seperately

### ISSUE THREAD

**Issue by rajveer43** [huggingface/transformers#27096]
### System Info

I am encountering an issue when trying to install "black" after running the following commands:

```bash
pip install -e ".[docs]"
pip install git+https://github.com/huggingface/doc-builder
```

`black` should be installed with the above commands only, every time I need to install it separately.

### Who can help?

![image](https://github.com/huggingface/transformers/assets/64583161/a7480b6f-eca5-4240-9fb4-de5c9d528336)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Run 
```bash
pip install -e ".[docs]"
```
2. Run 
```bash
install git+https://github.com/huggingface/doc-builder
```
3. Attempt to install "black" by running 
```bash
pip install black
```

### Expected behavior

I expect` black` to be installed without any issues when above commands are executed.

**Comment by ArthurZucker** [comment]
Would run `pip install -e ".[quality]"`
