### ISSUE TITLE
[i18n-jp] Translating `en/tasks` folder docs to Japanese 🇯🇵

### ISSUE THREAD

**Issue by rajveer43** [huggingface/transformers#27097]

**Comment by Yuki-Imajuku** [comment]
Is anyone working on this? I'm interested in contributing!
If no one is working on it, I would like to go from A (asr.md) to Z (zero_shot_object_detection.md) :)

**Comment by rajveer43** [comment]
the PR is already made for this issue, see #27098, 

you can work on #27392
