### ISSUE TITLE
How to export a Marian model in rust ?

### ISSUE THREAD

**Issue by flutter-painter** [huggingface/transformers#27107]
Most models based on Marian are also available in rust, such as : Helsinki-NLP/opus-mt-en-roa

Is it possible to do this using transformers ?
Did you asssit Helsinki-NLP in exporting the models to Rust ?

**Comment by julien-c** [comment]
They're models from https://github.com/guillaume-be/rust-bert you can probably ask there! cc @guillaume-be for info
