### ISSUE TITLE
Convert script for llama2 is not correct

### ISSUE THREAD

**Issue by fancyerii** [huggingface/transformers#27101]
### System Info

- `transformers` version: 4.34.1
- Platform: Linux-4.15.0-213-generic-x86_64-with-glibc2.27
- Python version: 3.9.18
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.24.0
- Accelerate config:    not found
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
TRANSFORM=`python -c "import transformers;print('/'.join(transformers.__file__.split('/')[:-1])+'/models/llama/convert_llama_weights_to_hf.py')"`
python ${TRANSFORM} --input_dir llama-2-7b-chat/ --model_size 7B --output_dir 7B-chat
```
in config.json, the max_position_embeddings is 2048(not 4096):

```
{
  "architectures": [
    "LlamaForCausalLM"
  ],

  "max_position_embeddings": 2048,
  "model_type": "llama", 
}
```

According to [this issue](https://github.com/facebookresearch/llama/issues/359), Word/position embedding after 2k is not converted correctly.

If that't rue, it's a very serious problem. 

### Expected behavior

correct convert llama2 and as [Daryl149](https://github.com/Daryl149) in that issue test ask question with correct answer's position large than 2k.

**Comment by ArthurZucker** [comment]
Hey, it's not a very serious issue no, the max_position embedding can be changed in the config and all converted checkpoints online are working as expected. Unless you have the need to convert them yourself and don't change it, yes generating after 2k will deteriorate but pretty minimal. 

Please make sure you read the issue you linked as it has pretty much all the answers

**Comment by ArthurZucker** [comment]
Feel free to open a PR to change this in the [conversion script](https://github.com/ArthurZucker/transformers/blob/72e9bd23250811083e8b2a37fd6143779d85cc51/src/transformers/models/llama/convert_llama_weights_to_hf.py#L101-L104):
```diff
    if base > 10000.0:
        max_position_embeddings = 16384
    else:
-        max_position_embeddings = 2048
+        max_position_embeddings = 4096
```

**Comment by fancyerii** [comment]
So I need just modify the config.json and it's all ok? I am converting llama2 myself.

**Comment by ArthurZucker** [comment]
Yes even if you modify after conversion it's alright

**Comment by fancyerii** [comment]
thanks
