### ISSUE TITLE
attributeerror: 'dataset' object has no attribute 'cardinality'

### ISSUE THREAD

**Issue by SrikanthChellappa** [huggingface/transformers#27110]
### System Info

Transformers version: 4.34.1
Tensorflow version: 2.14.0
Python version: 3.11.6

My Code snippet
from transformers import TFAutoModelForSeq2SeqLM, AutoTokenizer, GenerationConfig, TFTrainingArguments, TFTrainer
training_args = TFTrainingArguments(
    output_dir=output_dir,
    learning_rate=1e-5,
    num_train_epochs=1,
    weight_decay=0.01,
    logging_steps=1,
    max_steps=1
)

trainer = TFTrainer(
    model=original_model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation']
)
trainer.train()

Error Trace
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[52], line 1
----> 1 trainer.train()

File C:\ProgramData\anaconda3\envs\tfenv\Lib\site-packages\transformers\trainer_tf.py:479, in TFTrainer.train(self)
    475 def train(self) -> None:
    476     """
    477     Train method to train the model.
    478     """
--> 479     train_ds = self.get_train_tfdataset()
    481     if self.args.debug:
    482         tf.summary.trace_on(graph=True, profiler=True)

File C:\ProgramData\anaconda3\envs\tfenv\Lib\site-packages\transformers\trainer_tf.py:159, in TFTrainer.get_train_tfdataset(self)
    156     raise ValueError("Trainer: training requires a train_dataset.")
    158 self.total_train_batch_size = self.args.train_batch_size * self.args.gradient_accumulation_steps
--> 159 self.num_train_examples = self.train_dataset.cardinality().numpy()
    161 if self.num_train_examples < 0:
    162     raise ValueError("The training dataset must have an asserted cardinality")

AttributeError: 'Dataset' object has no attribute 'cardinality'

@gante @Rocketknight1 @ArthurZucker - Pls assist asap

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

from transformers import TFAutoModelForSeq2SeqLM, AutoTokenizer, GenerationConfig, TFTrainingArguments, TFTrainer
training_args = TFTrainingArguments(
    output_dir=output_dir,
    learning_rate=1e-5,
    num_train_epochs=1,
    weight_decay=0.01,
    logging_steps=1,
    max_steps=1
)

trainer = TFTrainer(
    model=original_model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation']
)
trainer.train()

### Expected behavior

The training should happen but it throws error

**Comment by Rocketknight1** [comment]
Hi, I'm sorry, we don't really support `TFTrainer` anymore! We recommend fine-tuning with Keras methods like `model.fit()` instead. Please see our notebooks on [translation](https://github.com/huggingface/notebooks/blob/main/examples/translation-tf.ipynb) or [summarization](https://github.com/huggingface/notebooks/blob/main/examples/summarization-tf.ipynb) for examples of training TF Seq2Seq models with this approach.

**Comment by SrikanthChellappa** [comment]
Thanks @Rocketknight1  for the update.
