### ISSUE TITLE
save_total_limit incorrectly deletes checkpoints

### ISSUE THREAD

**Issue by huchinlp** [huggingface/transformers#27138]
### System Info

transformers==4.34.1

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I set `save_total_limit` to 10, but surprisingly found it deleting my **latest** model. It was supposed to keep checkpoint-10000 and subsequent checkpoints, but instead, I found that the following checkpoints remained:

```checkpoint-9000
checkpoint-9100
checkpoint-9200
checkpoint-9300
checkpoint-9400
checkpoint-9500
checkpoint-9600
checkpoint-9700
checkpoint-9800
checkpoint-9900
```

I suspect that this may be due to the deletion process using the string names of the files rather than their numerical value.

### Expected behavior

It should keep the latest checkpoints.

**Comment by xkszltl** [comment]
FYI in case this is relevant:
- https://github.com/huggingface/transformers/issues/26961

**Comment by amyeroberts** [comment]
cc @muellerz @pacman100

**Comment by pacman100** [comment]
Hello, please refer to https://github.com/huggingface/transformers/issues/26961#issuecomment-1827691624
