### ISSUE TITLE
Inaccurate code example within inline code-documentation

### ISSUE THREAD

**Issue by thariq-nugrohotomo** [huggingface/transformers#27142]
I believe this code example contains inaccurate information:

https://github.com/huggingface/transformers/blob/211ad4c9cc1c0882c4a22eaca7b4d7d1e2f264b3/src/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py#L550C15-L550C15

```python
model.config.decoder_start_token_id = processor.tokenizer.cls_token_id
```

TrOCR decoder_start_token should be `eos` instead of `cls` or `bos`.

Using the pretrained model, when I pass `cls` or `bos` as the initial decoder token, the output (first decoded token) rarely get correct. But once I try to use `eos`, the output is correct, or at least similar with the output returned by `model.generate()`.

In the official code from Microsoft, they will fallback to `eos` if the token is not specified https://github.com/microsoft/unilm/blob/6f60612e7cc86a2a1ae85c47231507a587ab4e01/trocr/generator.py#L84

Code excerpt to manually see the first decoded token:

```python
decoder_start_token_id = processor.tokenizer.eos_token_id
x = model(pixel_values, torch.tensor([[decoder_start_token_id]]))
x = x.logits
x = torch.argmax(x, -1)
print(processor.tokenizer.batch_decode(x))
```

Switch `eos_token_id` to `cls_token_id` or `bos_token_id` to observe the incorrect output.

**Comment by amyeroberts** [comment]
Hi @thariq-nugrohotomo, thanks for raising this issue! 

Indeed, it seems that the behaviour in the original implementation is different. Would you like to open a PR updating the code examples in modeling_vision_encoder_decoder.py and modeling_trocr.py? This way you get the github contribution.

**Comment by MysteryManav** [comment]
I would like to fix the bug, is it only this file that needs to be changed or are there other places that require changes too ?
