### ISSUE TITLE
Bug in greedy_search when use_cache=False and use inputs_embeds as model input

### ISSUE THREAD

**Issue by TsuTikgiau** [huggingface/transformers#27174]
### System Info

transformers 4.30.0, python 3.9, ubuntu

### Who can help?

@gante

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

outputs = llama2model.generate(
    inputs_embeds=inputs_embeds,
    attention_mask=attention_mask,
    do_sample=False,
    use_cache=False
)

### Expected behavior

I'm using LLama2 model to take token embedding directly as input and do greedy search generation (do_sample=False) with no KV cache (use_cache=False). I faced a runtime error "RuntimeError: shape '[-1, 332]' is invalid for input of size 666" at [this line](https://github.com/huggingface/transformers/blob/v4.30.0/src/transformers/models/llama/modeling_llama.py#L528). 

Note that when use_cache=True, the code works. 

After some debugging I found that this is because inputs_embeds is not updated. After each decode step, the new generated input_id is added at [this line](https://github.com/huggingface/transformers/blob/v4.30.0/src/transformers/generation/utils.py#L2382) and the new attention mask is added at [this line](https://github.com/huggingface/transformers/blob/v4.30.0/src/transformers/generation/utils.py#L2386). However, the new inputs_embeds is not added. As we set use_cache=False and use the inputs_embeds as input, the original inputs_embeds will be use again in the forward pass with an updated attention mask (length+1), and leads to the size mismatch error. I have checked the latest code in the main branch and notice that the update of inputs_embeds is still missing.

**Comment by TsuTikgiau** [comment]
BTW, I only checked greedy_search. I'm not sure if this bug exists also in other decode strategies.

**Comment by gante** [comment]
Hey @TsuTikgiau 👋  Thank you for opening this issue.

The situation you describe is correct; `input_embeds` is not updated throughout `generate`, `input_ids` is. As such, it requires `use_cache=True` to work -- the relevant corresponding inputs are stored in `past_key_values`. 

Adding support for it would add significant complexity to `generate`. As such, my decision for now is *not* to add it, as I haven't seen any request for it. My advice would be to modify the function locally to suit your needs :)

Other users: if you encounter this issue, let me know (reaction or comment here). If several people request this feature, I might revisit the decision above!
