### ISSUE TITLE
CLIP Typo

### ISSUE THREAD

**Issue by fabfish** [huggingface/transformers#27190]
Hi, I just found a typo in the CLIP model at

https://github.com/huggingface/transformers/blob/50378cbf6c1fd8717a74b36c352f57f9a73e7282/src/transformers/models/clip/modeling_clip.py#L817C26-L817C26

where the "layernorm" is misspelled as "layrnorm" in "pre_layrnorm" but correct in "post_layernorm", guess it would be better to fix it in the code and checkpoints to keep consistency.

**Comment by Asymtode712** [comment]
I would like to fix it. Please assign me

**Comment by fabfish** [comment]
> Hi @fabfish, thanks for reporting!
> 
> Unfortunately, we can't update the names of layers and modules in a model once its weights have been released, as this would prevent them from being properly loaded into the model after the name change.

That's unfortunate, but I understand that. Thank you for your response!
