### ISSUE TITLE
Is transformers ovewriting tokenizer?

### ISSUE THREAD

**Issue by diogocortiz** [huggingface/transformers#2721]
Hello. I haven't been able to use tokenizer since friday. 
It seems that if I install transformers via pip it overwrites tokenizer installation with a version that doesn't work. 

If I get a new instance and do that:

`pip install transformers` 

When, I do that:
`pip install tokenizers`

I got the following msg:

> Requirement` already satisfied: tokenizers in /usr/local/lib/python3.7/site-packages (0.0.11)

And if I tried to import, I got this error msg:

> ImportError: cannot import name 'BertWordPieceTokenizer' from 'tokenizers'

I was wondering if it is a problem related to the new Transformers you released last Friday.

**Comment by LysandreJik** [comment]
Hi, I believe your issue was solved with https://github.com/huggingface/tokenizers/issues/120

**Comment by diogocortiz** [comment]
Sure. I will close this case.
