### ISSUE TITLE
wandb watch frequency

### ISSUE THREAD

**Issue by yuanenming** [huggingface/transformers#27233]
https://github.com/huggingface/transformers/blob/af3de8d87c717c4bb090f037d0d89413c195a42f/src/transformers/integrations/integration_utils.py#L751

The minimal watch frequency is 100 by default. I think people may want to monitor the gradients more frequently. So why it has to be larger than 100?

**Comment by amyeroberts** [comment]
Hi @yuanenming, thanks for raising this issue! 

The integrations are maintained by the contributors, however in this case I can see @muellerzr modified the line. I suspect it's a pragmatic number which is reasonable and suits most cases. 

The great thing about open source code is that you can modify it as you like! If you want to log things more frequently the number can be changed in a fork or your local copy. If this is a feature you think would be useful to the wider community, then please feel welcome to open a PR to make this configurable and we'll be happy to review.

**Comment by yuanenming** [comment]
Hi, Thank you for your prompt reply.
Yes I have modified it locally. BTW, I find it is reasonable because it takes ~20 mins to log all the gradients and weights distributions for LLaMA2-70B.
