### ISSUE TITLE
Typo of layernorm naming.

### ISSUE THREAD

**Issue by RunpeiDong** [huggingface/transformers#27241]
the `pre_layrnorm` should be `pre_layernorm`. Many of them are written wrongly, but the `post_layernorm` is all written correctly. Why is it? Should it be fixed?

Some examples of this typo:
https://github.com/huggingface/transformers/blob/4557a0dede92ce985576fac478b754d76bba3c18/src/transformers/models/clip/modeling_clip.py#L844C57-L844C57

**Comment by amyeroberts** [comment]
Hi @RunpeiDong, please see this related issue: #27190

**Comment by RunpeiDong** [comment]
> Hi @RunpeiDong, please see this related issue: #27190

Thanks @vanpelt. I understand the tedious work to do if we want to address typos in previous models. I guess we can only try to avoid it in future models.
