### ISSUE TITLE
ImportError: cannot import name 'PegasusXForConditionalGeneration'

### ISSUE THREAD

**Issue by wlmnzf** [huggingface/transformers#27245]
### System Info

I follow the page(https://huggingface.co/docs/transformers/model_doc/pegasus_x) to try to use the PegasusXForConditionalGeneration.

But when I import the package ```from transformers import AutoTokenizer, PegasusXForConditionalGeneration```, it goes wrong.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

>python3.6
>from transformers import AutoTokenizer, PegasusXForConditionalGeneration

### Expected behavior

I hope it an import the package correctly

**Comment by amyeroberts** [comment]
Hi @wlmnzf, thanks for raising this issue! 

It looks like the might be an issue with the installation of transformers in your environment. Please note that the lowest supported version of python is 3.8. I would suggest first try upgrading your python version and then reinstalling transformers.

**Comment by wlmnzf** [comment]
@amyeroberts Thanks for pointing about this, I try it again with python 3.10, and it works!
