### ISSUE TITLE
An unexpected argument in the ResNet Flax implementation

### ISSUE THREAD

**Issue by pingzhili** [huggingface/transformers#27257]
### System Info

The class `FlaxResNetBasicLayerCollection` does not expect the argument `activation`, but here passes it and would raise error:
https://github.com/huggingface/transformers/blob/8a312956fd49efd69adb98c40996719d4c276a01/src/transformers/models/resnet/modeling_flax_resnet.py#L215-L220

The definition of `FlaxResNetBasicLayerCollection` is:
https://github.com/huggingface/transformers/blob/8a312956fd49efd69adb98c40996719d4c276a01/src/transformers/models/resnet/modeling_flax_resnet.py#L180-L194

### Who can help?

@amyeroberts

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

A minimal reproducible example:
```
from transformers import FlaxResNetForImageClassification, ResNetConfig

model = FlaxResNetForImageClassification(config=ResNetConfig(layer_type="basic"))
```

### Expected behavior

Raise `TypeError: FlaxResNetBasicLayerCollection.__init__() got an unexpected keyword argument 'activation'`

**Comment by amyeroberts** [comment]
Hi @pingzhili, thanks for raising this issue! 

Indeed, it seems that `activation` shouldn't be passed to FlaxResNetBasicLayerCollection [here](https://github.com/huggingface/transformers/blob/5964f820db1568d26298b37dea9db328185c7f7c/src/transformers/models/resnet/modeling_flax_resnet.py#L218C3-L218C3). Would you like to open a PR to fix this? This way you get the github contribution for spotting the issue and resolving it.
