### ISSUE TITLE
Installing pydantic>=2.4.0 would cause error and fail to load model

### ISSUE THREAD

**Issue by Luodian** [huggingface/transformers#27273]
### System Info

The error would be as
```
Failed to import transformers.generation.utils because of the following error (look up to see its traceback): 'FieldInfo' object has no attribute 'required'
```

I spent a lot of time to spot it's the version change from the installation of upgrading `gradio` and it caused `pydantic==1.10.7` to `pydantic==2.4.2`.

I downgraded to 1.10.7 then could run smoothly as usual.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
```python
!pip install pydantic==2.4.2
from transformers import FuyuForCausalLM, AutoTokenizer, FuyuProcessor, FuyuImageProcessor
```

### Expected behavior

```sh
Failed to import transformers.generation.utils because of the following error (look up to see its traceback): 'FieldInfo' object has no attribute 'required'
```

**Comment by amyeroberts** [comment]
Hi @Luodian, thanks for raising this issue! 

I looks like we might have to pin pydantic in our setup.py - WDYT @ydshieh?

**Comment by ydshieh** [comment]
Hi @Luodian 

We do have `"pydantic<2",` in out `setup.py`

Related https://github.com/huggingface/transformers/pull/24596

Not sure how much we can do with `pydantic 2` so far.

**Comment by Luodian** [comment]
oh I know that, I think the `pydantic>2` comes from upgrading `gradio`.

**Comment by ydshieh** [comment]
Eventually, if `pydantic>=2` is used by many libraries, we might consider to update the requirement  (as long as not so many things breaking 😄 )

**Comment by mxchinegod** [comment]
> Eventually, if `pydantic>=2` is used by many libraries, we might consider to update the requirement (as long as not so many things breaking 😄 )

lots of things are breaking
