### ISSUE TITLE
Transformers version 4.35.0 is breaking PEFT 0.0.6 -- IndexError

### ISSUE THREAD

**Issue by alexsherstinsky** [huggingface/transformers#27278]
### System Info

Hello,

With the Transformers version 4.35.0 and PEFT version 0.6.0 -- when running a model with `input_ids` and `attention_mask` as arguments, the IndexError exception occurs in "peft/tuners/adaption_prompt/utils.py:45":

```
model(input_ids=model_inputs, attention_mask=attention_masks).get("logits")
```

raises `"IndexError: tuple index out of range"`.

Thank you.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

An LLM with the `adaptation_prompt` PEFT strategy, executing the `forward` method.

### Expected behavior

Running without exceptions.

**Comment by amyeroberts** [comment]
cc @younesbelkada

**Comment by younesbelkada** [comment]
This should be fixed in https://github.com/huggingface/peft/pull/1084 
Would it makes sense to have a patch release on PEFT side @BenjmainBossan @pacman100 ?

**Comment by alexsherstinsky** [comment]
Thank you very much for jumping on this so fast!  If you decide to make a patch, please notify herein -- as I am watching this issue.  Thanks again!

**Comment by younesbelkada** [comment]
We just made a patch release on PEFT side: https://github.com/huggingface/peft/releases/tag/v0.6.1 that should resolve the issue! let us know if all goes well by installing `peft==0.6.1`

**Comment by alexsherstinsky** [comment]
@younesbelkada Thank you so much -- going to try it now!  Will close the issue once tests pass in our repository.  Appreciated!

**Comment by alexsherstinsky** [comment]
The fix for both `transformers` and `peft` has been confirm.  Thank you all!

**Comment by younesbelkada** [comment]
Great ! Thanks @alexsherstinsky !!
