### ISSUE TITLE
Question: Resources to implement random & greedy sampling, beam search?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/transformers#27277]
Hello everybody,

I want to implement random sampling, greedy sampling, and beam search, but cannot seem to find any useful resources on how to implement them.

Could you please provide some resources or code examples (perhaps from this repo) on how to implement the sampling strategies above?

**Comment by amyeroberts** [comment]
Hi @EricLBuehler - thanks for raising an issue! 

I can see that the issue is closed but for anyone in future visiting this thread, details on customising generation strategies can be found here: https://huggingface.co/docs/transformers/generation_strategies
