### ISSUE TITLE
Implement Cross Attention in LLAMA Model

### ISSUE THREAD

**Issue by eitamarSaraf** [huggingface/transformers#27284]
### Feature request

The current implementation of the LLAMA model in the Hugging Face Transformers repository supports self-attention layers as per the standard design of transformer models. I propose the addition of an option to use several or all attention layers as cross-attention layers instead of self-attention layers. 

Cross-attention layers are crucial for tasks where the model needs to attend to different inputs other than its own output (e.g., encoder-decoder tasks in translation, image-captioning, etc.). The option to use cross-attention would enhance the LLAMA model's capabilities for a broader range of applications.

https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py

### Motivation

My motivation for this proposal stems from the need to apply the LLAMA model to tasks that inherently require cross-modal attention mechanisms. The current limitation of self-attention only restricts its applicability. While self-attention mechanisms are effective for a range of tasks, the flexibility of cross-attention layers could extend the model's utility, allowing researchers and developers to tackle a wider variety of problems.

### Your contribution

I am willing to assist in the implementation of this feature. While I am not an expert in decoder-only architecture, I believe with the right guidance, I can help.

I look forward to discussing this further with the maintainers of the repository.

Thank you for considering my proposal.

**Comment by sangmin6600** [comment]
Is cross-attention available in LLAMA Model?
