### ISSUE TITLE
cannot import name 'LlamaConfig' from 'transformers

### ISSUE THREAD

**Issue by Ahmed-Roushdy** [huggingface/transformers#27298]
### System Info

- `adapter-transformers` version: 3.2.1
- Platform: Linux-5.8.0-59-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- Huggingface_hub version: 0.12.1
- PyTorch version (GPU?): 1.11.0+cu113 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@SunMarc  @younesbelkada

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

>>> from transformers import LlamaConfig

``` Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'LlamaConfig' from 'transformers' (/home/aelkordy/.local/lib/python3.8/site-packages/transformers/__init__.py)```

### Expected behavior

to be able to load LlamaConfig file

**Comment by younesbelkada** [comment]
Hi @Ahmed-Roushdy !
I see from the details above that:

> adapter-transformers version: 3.2.1

Can you try to install the latest `transformers` package instead? `pip install -U transformers`
