### ISSUE TITLE
Shared tensors not correctly saved.

### ISSUE THREAD

**Issue by Luodian** [huggingface/transformers#27293]
### System Info

- `transformers` version: 4.36.0.dev0
- Platform: Linux-4.19.0-25-cloud-amd64-x86_64-with-glibc2.28
- Python version: 3.9.17
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: 0.24.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: 8*A100
- Using distributed or parallel set-up in script?: accelerate + deepspeed zero3

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am finetuning Fuyu-8B and found the code for calling `model.save_pretrained` method would run into error after upgrading to `4.36.0`.

The error shows:
```
Removed shared tensor {'language_model.model.layers.12.self_attn.dense.weight', 'language_model.model.layers.22.self_attn.k_layernorm.weight', 'language_model.model.layers.24.mlp.dense_h_to_4h.bias', 'language_model.model.layers.15.mlp.dense_h_to_4h.weight', 'language_model.model.layers.22.input_layernorm.weight', 'language_model.model.layers.25.self_attn.q_layernorm.weight', 'language_model.model.layers.8.self_attn.query_key_value.bias', 'language_model.model.layers.33.mlp.dense_4h_to_h.bias', 'language_model.model.layers.6.post_attention_layernorm.weight', 'language_model.model.layers.30.self_attn.query_key_value.weight', 'language_model.model.layers.5.self_attn.query_key_value.weight', 'language_model.model.layers.10.mlp.dense_h_to_4h.bias', 'language_model.model.layers.5.post_attention_layernorm.weight', 'language_model.model.layers.15.mlp.dense_4h_to_h.bias', 'language_model.model.layers.2.self_attn.query_key_value.bias', 'language_model.model.layers.4.input_layernorm.bias', 'language_model.model.layers.25.self_attn.k_layernorm.weight', 'language_model.model.layers.29.self_attn.query_key_value.weight', 'language_model.model.layers.13.self_attn.query_key_value.bias', 'language_model.lm_head.weight', 'language_model.model.layers.6.mlp.dense_h_to_4h.weight', 'language_model.model.layers.13.mlp.dense_4h_to_h.weight', 'language_model.model.layers.14.mlp.dense_h_to_4h.weight', 'language_model.model.layers.31.mlp.dense_h_to_4h.weight', 'language_model.model.layers.32.input_layernorm.weight', 'language_model.model.layers.19.mlp.dense_4h_to_h.bias', 'language_model.model.layers.24.self_attn.dense.bias', 'language_model.model.layers.5.self_attn.query_key_value.bias', 'language_model.model.layers.7.mlp.dense_4h_to_h.bias', 'language_model.model.layers.10.self_attn.query_key_value.bias', 'language_model.model.layers.18.mlp.dense_h_to_4h.weight', 'language_model.model.layers.29.post_attention_layernorm.bias', 'language_model.model.layers.11.self_attn.dense.weight', 'language_model.model.layers.28.self_attn.query_key_value.weight', 'language_model.model.layers.14.mlp.dense_4h_to_h.weight', 'language_model.model.layers.15.mlp.dense_4h_to_h.weight', 'language_model.model.layers.35.mlp.dense_4h_to_h.weight', 'language_model.model.layers.17.post_attention_layernorm.bias', 'language_model.model.layers.23.mlp.dense_h_to_4h.bias', 'language_model.model.layers.15.mlp.dense_h_to_4h.bias', 'language_model.model.final_layernorm.weight', 'language_model.model.layers.6.mlp.dense_4h_to_h.weight', 'language_model.model.layers.29.input_layernorm.weight', 'language_model.model.layers.13.self_attn.q_layernorm.bias', 'language_model.model.layers.6.self_attn.dense.weight', 'language_model.model.layers.22.self_attn.query_key_value.weight', 'language_model.model.layers.35.post_attention_layernorm.bias', 'language_model.model.layers.23.self_attn.dense.bias', 'language_model.model.layers.16.self_attn.k_layernorm.weight', 'language_model.model.layers.32.self_attn.dense.weight', 'language_model.model.layers.25.self_attn.dense.bias', 'language_model.model.layers.9.self_attn.query_key_value.bias', 'language_model.model.layers.25.self_attn.k_layernorm.bias', 'language_model.model.layers.3.mlp.dense_h_to_4h.weight', 'language_model.model.layers.21.self_attn.q_layernorm.weight', 'language_model.model.layers.32.post_attention_layernorm.bias', 'language_model.model.layers.33.self_attn.q_layernorm.weight', 'language_model.model.layers.2.post_attention_layernorm.bias', 'language_model.model.layers.20.mlp.dense_4h_to_h.bias', 'language_model.model.layers.4.self_attn.k_layernorm.bias', 'language_model.model.layers.29.mlp.dense_4h_to_h.weight', 'language_model.model.layers.32.self_attn.dense.bias', 'language_model.model.layers.8.mlp.dense_h_to_4h.weight', 'language_model.model.layers.34.self_attn.query_key_value.bias', 'language_model.model.layers.35.self_attn.k_layernorm.bias', 'language_model.model.layers.4.post_attention_layernorm.bias', 'language_model.model.layers.28.mlp.dense_4h_to_h.bias', 'language_model.model.layers.8.self_attn.q_layernorm.bias', 'language_model.model.layers.32.self_attn.k_layernorm.weight', 'language_model.model.layers.28.self_attn.dense.weight', 'language_model.model.layers.31.mlp.dense_4h_to_h.bias', 'language_model.model.layers.0.mlp.dense_4h_to_h.weight', 'language_model.model.layers.11.mlp.dense_h_to_4h.weight', 'language_model.model.layers.29.mlp.dense_4h_to_h.bias', 'language_model.model.layers.19.mlp.dense_h_to_4h.weight', 'language_model.model.layers.12.post_attention_layernorm.weight', 'language_model.model.layers.7.self_attn.query_key_value.weight', 'language_model.model.layers.13.input_layernorm.weight', 'language_model.model.layers.31.mlp.dense_h_to_4h.bias', 'language_model.model.layers.0.self_attn.k_layernorm.bias', 'language_model.model.layers.34.self_attn.q_layernorm.bias', 'language_model.model.layers.1.self_attn.k_layernorm.weight', 'language_model.model.layers.35.self_attn.q_layernorm.weight', 'language_model.model.layers.29.self_attn.k_layernorm.bias', 'language_model.model.layers.34.mlp.dense_4h_to_h.weight', 'language_model.model.layers.30.mlp.dense_h_to_4h.bias', 'language_model.model.layers.0.input_layernorm.bias', 'language_model.model.layers.18.self_attn.query_key_value.weight', 'language_model.model.layers.1.mlp.dense_h_to_4h.bias', 'language_model.model.layers.26.mlp.dense_h_to_4h.weight', 'language_model.model.layers.8.post_attention_layernorm.weight', 'language_model.model.layers.18.self_attn.dense.bias', 'language_model.model.layers.30.mlp.dense_4h_to_h.bias', 'language_model.model.layers.7.mlp.dense_h_to_4h.bias', 'language_model.model.layers.31.self_attn.dense.weight', 'language_model.model.layers.9.self_attn.query_key_value.weight', 'language_model.model.layers.12.input_layernorm.bias', 'language_model.model.layers.14.self_attn.q_layernorm.weight', 'language_model.model.layers.28.self_attn.dense.bias', 'language_model.model.layers.6.self_attn.q_layernorm.bias', 'language_model.model.layers.30.self_attn.query_key_value.bias', 'language_model.model.layers.11.self_attn.q_layernorm.weight', 'language_model.model.layers.33.self_attn.dense.bias', 'language_model.model.layers.14.mlp.dense_h_to_4h.bias', 'language_model.model.layers.14.mlp.dense_4h_to_h.bias', 'language_model.model.layers.12.mlp.dense_h_to_4h.weight', 'language_model.model.layers.10.self_attn.dense.weight', 'language_model.model.layers.5.self_attn.k_layernorm.weight', 'language_model.model.layers.33.mlp.dense_h_to_4h.weight', 'language_model.model.layers.17.mlp.dense_4h_to_h.weight', 'language_model.model.layers.19.self_attn.dense.bias', 'language_model.model.layers.4.mlp.dense_4h_to_h.bias', 'language_model.model.layers.19.self_attn.query_key_value.weight', 'language_model.model.layers.8.input_layernorm.bias', 'language_model.model.layers.6.self_attn.k_layernorm.bias', 'language_model.model.layers.31.self_attn.dense.bias', 'language_model.model.layers.25.self_attn.query_key_value.bias', 'language_model.model.layers.34.self_attn.q_layernorm.weight', 'language_model.model.layers.7.input_layernorm.bias', 'language_model.model.layers.2.self_attn.k_layernorm.bias', 'language_model.model.layers.29.self_attn.q_layernorm.bias', 'language_model.model.layers.16.self_attn.query_key_value.bias', 'language_model.model.layers.35.mlp.dense_h_to_4h.weight', 'language_model.model.layers.35.post_attention_layernorm.weight', 'language_model.model.layers.1.self_attn.dense.weight', 'language_model.model.layers.4.mlp.dense_h_to_4h.bias', 'language_model.model.layers.15.input_layernorm.bias', 'language_model.model.layers.4.post_attention_layernorm.weight', 'language_model.model.layers.14.input_layernorm.weight', 'language_model.model.layers.22.mlp.dense_4h_to_h.bias', 'language_model.model.layers.11.input_layernorm.weight', 'language_model.model.layers.27.self_attn.k_layernorm.bias', 'language_model.model.layers.18.mlp.dense_4h_to_h.bias', 'language_model.model.layers.25.mlp.dense_h_to_4h.bias', 'language_model.model.layers.32.input_layernorm.bias', 'language_model.model.layers.10.mlp.dense_h_to_4h.weight', 'language_model.model.layers.14.self_attn.k_layernorm.weight', 'language_model.model.layers.8.post_attention_layernorm.bias', 'language_model.model.layers.27.self_attn.dense.bias', 'language_model.model.layers.21.self_attn.k_layernorm.weight', 'language_model.model.layers.27.self_attn.q_layernorm.weight', 'language_model.model.layers.30.self_attn.dense.weight', 'language_model.model.layers.23.mlp.dense_4h_to_h.bias', 'language_model.model.layers.18.post_attention_layernorm.weight', 'language_model.model.layers.22.self_attn.q_layernorm.weight', 'language_model.model.layers.13.self_attn.dense.bias', 'language_model.model.layers.14.self_attn.query_key_value.bias', 'language_model.model.layers.10.self_attn.k_layernorm.bias', 'language_model.model.layers.34.input_layernorm.bias', 'language_model.model.layers.3.post_attention_layernorm.bias', 'language_model.model.layers.5.input_layernorm.weight', 'language_model.model.layers.8.self_attn.query_key_value.weight', 'language_model.model.layers.27.post_attention_layernorm.bias', 'language_model.model.layers.28.mlp.dense_h_to_4h.weight', 'language_model.model.layers.28.self_attn.q_layernorm.weight', 'language_model.model.layers.5.mlp.dense_4h_to_h.weight', 'language_model.model.layers.19.self_attn.dense.weight', 'language_model.model.layers.21.input_layernorm.weight', 'language_model.model.layers.14.post_attention_layernorm.bias', 'language_model.model.layers.35.self_attn.query_key_value.bias', 'language_model.model.layers.10.mlp.dense_4h_to_h.weight', 'language_model.model.layers.17.self_attn.q_layernorm.bias', 'language_model.model.layers.25.input_layernorm.bias', 'language_model.model.layers.34.self_attn.dense.weight', 'language_model.model.layers.34.input_layernorm.weight', 'language_model.model.layers.5.self_attn.k_layernorm.bias', 'language_model.model.layers.2.mlp.dense_4h_to_h.weight', 'language_model.model.layers.11.self_attn.dense.bias', 'language_model.model.layers.17.mlp.dense_4h_to_h.bias', 'language_model.model.layers.13.mlp.dense_4h_to_h.bias', 'language_model.model.layers.21.self_attn.query_key_value.weight', 'language_model.model.lay
207 Saved checkpoint at epoch 1.
```

I try to set the `safe_serialization=False`, the warning disappear but the saved pytorch_model.bin only 2MB, comparing to around 18GB originally (using 4.35.0).

### Expected behavior

See above

**Comment by LysandreJik** [comment]
Thanks for reporting! I can reproduce, I'm fixing.

**Comment by LysandreJik** [comment]
Hmmm actually, it seems like it was just a mistake on my end, I cannot reproduce after trying again.

If you load the fuyu model, save it, and reload it once again, do you have an error? Does it only happen after fine-tuning?

**Comment by Luodian** [comment]
> Hmmm actually, it seems like it was just a mistake on my end, I cannot reproduce after trying again.
> 
> If you load the fuyu model, save it, and reload it once again, do you have an error? Does it only happen after fine-tuning?

ohh I see, you dont have it on `transformers==4.36.0`?? I had this issue on two of my instances. Let's me figure out the details.

I think the problem may comes from if you try to use `accelerator` + `deepspeed zero3` to wrap the model?

The error happens at my script in this line, you can take a look at the model specific configs if that could provide more contexts!

https://github.com/Luodian/Otter/blob/ca69589b7e4475c9e87836de30e7fc91bbee74b6/pipeline/train/instruction_following.py#L523

**Comment by Luodian** [comment]
But I know reproducing it may be difficult for your side. I could share you more information and my possible guess when I'm more available!

Now at least I could run my all code with `4.35.0`. And I think this issue would also remind other users to prevent it somehow.

**Comment by LysandreJik** [comment]
Understood, it's likely it indeed comes from the safe serialization then.
Do you have a command I can run using Otter? I'd like to dive in and see what may fail, I see you have different ways of saving the checkpoint:

https://github.com/Luodian/Otter/blob/ca69589b7e4475c9e87836de30e7fc91bbee74b6/pipeline/train/train_utils.py#L229-L262

**Comment by Luodian** [comment]
Here's a minimal one:

```
accelerate launch --config_file=./pipeline/accelerate_configs/accelerate_config_zero2.yaml \
    --num_processes=1 \
    pipeline/train/instruction_following.py \
    --pretrained_model_name_or_path=adept/fuyu-8b \
    --training_data_yaml=./Demo_Data.yaml \
    --model_name=fuyu \
    --instruction_format=fuyu \
    --batch_size=1 \
    --gradient_accumulation_steps=2 \
    --num_epochs=3 \
    --external_save_dir=./checkpoints \
    --run_name=Fuyu_Save_Tester \
    --wandb_project=Fuyu \
    --workers=${WORKERS} \
    --lr_scheduler=cosine \
    --learning_rate=1e-5 \
    --warmup_steps_ratio=0.03 \
    --save_hf_model \
    --max_seq_len=1024 \
    --logging_steps=1000 \
    --keep_symbols \
    --save_ckpt_each_epoch \
    --dynamic_resolution \
    --with_task_description
```

The data could be set at `Demo_Data.yaml` and the files are downloaded from:
`instruction.json` file at [here](https://entuedu-my.sharepoint.com/:f:/g/personal/libo0013_e_ntu_edu_sg/Eo9bgNV5cjtEswfA-HfjNNABiKsjDzSWAl5QYAlRZPiuZA?e=nNUhJH) and the `images.parquet` file at [here](https://entuedu-my.sharepoint.com/:f:/g/personal/libo0013_e_ntu_edu_sg/EmwHqgRtYtBNryTcFmrGWCgBjvWQMo1XeCN250WuM2_51Q?e=sCymXx).

**Comment by Luodian** [comment]
> Understood, it's likely it indeed comes from the safe serialization then. Do you have a command I can run using Otter? I'd like to dive in and see what may fail, I see you have different ways of saving the checkpoint:
> 
> https://github.com/Luodian/Otter/blob/ca69589b7e4475c9e87836de30e7fc91bbee74b6/pipeline/train/train_utils.py#L229-L262

basically the errors comes from 
`--save_hf_model`

**Comment by LysandreJik** [comment]
Ok, let me try this. Are you tying weights yourself that weren't originally tied in the fuyu model?

**Comment by Luodian** [comment]
> Ok, let me try this. Are you tying weights yourself that weren't originally tied in the fuyu model?

What does this mean sorry? I didnt try other model weights, I think Fuyu also didnt have specifically manipulation of model saving process. It calls the `save_pretrained` from `modeling_utils.py` I guess?

**Comment by LysandreJik** [comment]
Ok that works no problem :)
I was just making sure you weren't tying some weights yourself within the model, as this might go wrong on reload.

I'm currently debugging your script, will report here.

**Comment by Luodian** [comment]
All yes and but, the model weights are directly from `adept/fuyu-8b`. 

But we have implementations inside `modeling_fuyu.py` and `modeling_persimmon.py`. But it mainly about the throughput optimization and integration of flash attention and fused operators. Does them count for the error? 

My side info is that I have two instances and they all err with `4.36.0`.
1. One of my instance has flash attention so it calls our version of `modeling_persimmon.py`. 
2. Another instance didnt have flash attention so it calls transformers `modeling_persimmon.py`

The logic is:
```python
try:
    from .modeling_persimmon import PersimmonForCausalLM

    print("Using local PersimmonForCausalLM with Flash Attention")
except ImportError:
    from transformers import PersimmonForCausalLM

    print("Using transformers PersimmonForCausalLM without Flash Attention")
```

**Comment by muellerzr** [comment]
Working on trying to reproduce this :)

**Comment by muellerzr** [comment]
@Luodian can you try again when `num_processes >1`? I couldn't reproduce it. 

I can only reproduce your main example here because currently Accelerate doesn't really support single-GPU deepspeed

**Comment by Luodian** [comment]
sorry Im little busy these days, I may report it later, but may not very soon.

**Comment by Quetzalcohuatl** [comment]
I have the same issue, “Removed shared tensor”. Transformers 4.35.2, using deepspeed on 1 gpu. Following the comments here, I disabled deepspeed and now it is saving correctly. 

I imagine if you are getting this error, you are running deepspeed on a 1 gpu machine.

**Comment by Luodian** [comment]
But I truly had this issue when using 2 or 8 GPUs with deepspeed zero3.

**Comment by Quetzalcohuatl** [comment]
Agree. I got the same issue when I just ran it on my 8gpu instance with deepspeed. I even downgraded to 4.35.0 and still have the same issue.

basically my code saves a bert module in one folder, and saves the overall model in another folder. I hypothesize that when saving with safetensors, if it noticed that you are saving duplicate weights and biases, it saves the full thing once and when you try re-saving it, it will remove the shared modules (to save on disk space, I guess). In my case, it was removing all of my layers except for the tail Embedding layer.

luckily for me, setting safe_serialization = False fixed it for me. I hope you can figure out how to fix yours too @Luodian

**Comment by Quetzalcohuatl** [comment]
Bu the way, in case it matters, I am using deepspeed zero stage 0

**Comment by Luodian** [comment]
> Agree. I got the same issue when I just ran it on my 8gpu instance with deepspeed. I even downgraded to 4.35.0 and still have the same issue.
> 
> basically my code saves a bert module in one folder, and saves the overall model in another folder. I hypothesize that when saving with safetensors, if it noticed that you are saving duplicate weights and biases, it saves the full thing once and when you try re-saving it, it will remove the shared modules (to save on disk space, I guess). In my case, it was removing all of my layers except for the tail Embedding layer.
> 
> luckily for me, setting safe_serialization = False fixed it for me. I hope you can figure out how to fix yours too @Luodian

yes, I use `4.35.1` and `safe_serialization=False` solved my issue. And I am also gonna fix in this version until this issue be full addressed (in deepspeed zero0/1/2/3, and multi-gpus).

**Comment by GabPrato** [comment]
Encountered the error while using:
```
accelerate=0.25.0
transformers=4.36.2
```
Single gpu, not using deepspeed. Accelerate config:
```yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

When calling `accelerator.save_state(dir)` to save a flan-t5-small model, I get:
```
Removed shared tensor {'decoder.embed_tokens.weight', 'encoder.embed_tokens.weight'} while saving. This should be OK, but check by verifying that you don't receive any warning while reloading
```
and then when I reload the model `accelerator.load_state(dir)`, I get:
```
RuntimeError: Error(s) in loading state_dict for T5ForConditionalGeneration:
        Missing key(s) in state_dict: "encoder.embed_tokens.weight", "decoder.embed_tokens.weight".
```
Calling `accelerator.save_state(dir, safe_serialization=False)` works, but doesn't solve the underlying problem. Calling `accelerate.save_state(dir)` and then `accelerate.load_state(dir)` shouldn't throw an error. Why is `safe_serialization` removing these two shared tensors? Not sure what is the best solution, but this should be automatically handled.

**Comment by AfrinDange** [comment]
Hi @GabPrato, 
I had the same issue with Accelerate while using for single GPU. 
Using, `safe_serialization=False` in accelerate.save_state() resolved it.

**Comment by Deriq-Qian-Dong** [comment]
i have the same issue

**Comment by Deriq-Qian-Dong** [comment]
i have the same issue

**Comment by amyeroberts** [comment]
cc @muellerzr @pacman100

**Comment by muellerzr** [comment]
Hi all, please explain more about how you're using `Accelerator.save_state()` here please? We don't expose that part of the API in the `Trainer`, so *how* that is being called could be the root of our issue (as the before error fully and completely passes)

**Comment by Narsil** [comment]
I tried with every latest version of the packages, and the reproducer runs for me.

Happy to help whenever there's a reproducer !

**Comment by Deriq-Qian-Dong** [comment]
I run the same code with the following codes and got the issue.
https://github.com/huggingface/trl/issues/1121

**Comment by haofanwang** [comment]
Meet the same issue. My accelerator version is `0.28.0.dev0`. As suggested above, using `safe_serialization=False` in accelerate.save_state() resolved it.

**Comment by khanrc** [comment]
I encountered the same issue (transformers==4.38.2, accelerate==0.27.2). This issue appears to be caused by the logic for identifying aliased (shared) tensors.

During debugging, I discovered:

1. Deepspeed ZeRO re-partitions parameters in the initialization stage, leading to shared storage for parameters.
2. As a result, in the `save_pretrained` method, parameters are identified as shared tensors (though they're not actually shared tensors).
3. The shared tensors are subsequently removed, as indicated by the `Removed shared tensor ...` log message.
4. Consequently, the resulting checkpoint includes only a very small portion of all parameters.

The shared tensors are only removed in `safe_serialization=True`, thus, we can avoid this issue by `safe_serialization=False`.

**Comment by khanrc** [comment]
One another solution is to get state_dict via accelerator:

```
state_dict = accelerator.get_state_dict(model)
model.save_pretrained(output_path, state_dict=state_dict)
```

**Comment by cxjtju** [comment]
> > Agree. I got the same issue when I just ran it on my 8gpu instance with deepspeed. I even downgraded to 4.35.0 and still have the same issue.
> > basically my code saves a bert module in one folder, and saves the overall model in another folder. I hypothesize that when saving with safetensors, if it noticed that you are saving duplicate weights and biases, it saves the full thing once and when you try re-saving it, it will remove the shared modules (to save on disk space, I guess). In my case, it was removing all of my layers except for the tail Embedding layer.
> > luckily for me, setting safe_serialization = False fixed it for me. I hope you can figure out how to fix yours too @Luodian
> 
> yes, I use `4.35.1` and `safe_serialization=False` solved my issue. And I am also gonna fix in this version until this issue be full addressed (in deepspeed zero0/1/2/3, and multi-gpus).

what's the version of accelerate?

**Comment by ParthaEth** [comment]
Had the same problem and indeed `safe_serialization=False` solved it
```
transformers version:  '4.44.2'
accelerate version: '0.34.0'
```

Saving code:
```
          unwrapped_model = accelerator.unwrap_model(model)

          unwrapped_model.save_pretrained(
              self.output_dir,
              is_main_process=accelerator.is_main_process,
              save_function=accelerator.save,
              state_dict=accelerator.get_state_dict(model),
              safe_serialization=False  # this solves loading issue 
          )
 ```
