### ISSUE TITLE
Bart vs T5 inference time

### ISSUE THREAD

**Issue by hadifar** [huggingface/transformers#27290]
### System Info

```
- `transformers` version: 4.35.0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0+cu118 (False)
- Tensorflow version (GPU?): 2.14.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.7.4 (cpu)
- Jax version: 0.4.16
- JaxLib version: 0.4.16
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

@ArthurZucker @younesbelkada @nar

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Here is the colab:
https://colab.research.google.com/drive/1h_Ejm1YiyT7JOYMS-HrMkx6uNmiaiVbY?usp=sharing

### Expected behavior

I expect similar inference time for Bart-base & t5-base. However, the t5-base is 3x times faster. As far as know, the Bart has larger context window but overall it is a smaller model (almost 2/3 of parameters of t5).

**Comment by shankarsharma8089** [comment]
@hadifar can i work on this issue ? i think  we can use quantization to reduce the size of the BART-base model and potentially improve its inference speed.

**Comment by ArthurZucker** [comment]
Hey 🤗 You are running a summurization task, which depends a lot on how well the model performs because the generation time is bounded by how much text is generated. Longer does not necessarily means better performances. You should compare the forward of the model to get better estimates of the latency you can get.

**Comment by shankarsharma8089** [comment]
@ArthurZucker Absolutely, , Comparing the forward pass time for both models would indeed provide a more accurate measure of their inference speed. Additionally, consider the hardware on which the models are running, as different hardware configurations can impact performance.
