### ISSUE TITLE
Issue with Whisper model

### ISSUE THREAD

**Issue by lem21h** [huggingface/transformers#27302]
### System Info

After upgrading from version 4.30.2 to 4.35.0 the Whisper model stopped working.

The issue is with the following piece of the code:
```  
if tokenizer is None:
        tokenizer = get_tokenizer(model.is_multilingual)
if tokenizer.language is None or tokenizer.language_token not in tokenizer.sot_sequence:
        raise ValueError(f"This model doesn't have language tokens so it can't perform lang id")
```

For version 4.30.2 the `tokenizer.language` returns 50259
for version 4.35.0 the `tokenizer.language` returns 50349

### Who can help?

@ArthurZucker

### Reproduction

```
model = whisper.load_model("medium")
tokenizer = get_tokenizer(model.is_multilingual)
print(tokenizer.language_token)
print(tokenizer.language_token not in tokenizer.sot_sequence)
```

For 4.30.2 the returned values are:
50259
False

For 4.35.0 the returned values are:
50349
True

### Expected behavior

I would expect that this will work the same.
Also why the same model out of sudden changes the language token value ??

**Comment by lem21h** [comment]
After a bit of digging the Whisper AI builds a map of special tokens:
```
additional_tokens = dict(
            zip(
                tokenizer.tokenizer.additional_special_tokens,
                tokenizer.tokenizer.additional_special_tokens_ids,
            )
        )
```
     
on version 4.30.2 the EN gets ID  50259
and on version 4.35.0 the EN gets ID  50349

**Comment by ArthurZucker** [comment]
Hey! I am not sure I follow, where is the snippet taken from? What you are showing seems to use `openai-whisper` which now uses `tiktoken` rather `tokenizers` as  a backend so not sure we can do much here.

**Comment by lem21h** [comment]
hi, thank you for the reply.

Well whisper.ai in version 1.0.0.1 (from dec 2022) still using GPT2 tokenizer.
The issue is that when the model is loaded, then tokenizer should return the ID of the language (in my case english). It is done by checking those `additional_special_tokens` and matched position against `additional_special_tokens_ids`

In version  4.30.2 of tokenizers, the value for english is returned  50259 and in version  4.35.0 it is out of sudden  50349.

I'm not saying that what they did in Whisper AI is ok, but just curious how ID of EN tokenizer has different ID between those two versions for the same model.
That is the whole issue about :)
