### ISSUE TITLE
AWQ model error when `AwqConfig['version']` is a string

### ISSUE THREAD

**Issue by poedator** [huggingface/transformers#27318]
### System Info

A100 Cuda 12.2 transformers 4.36.0.dev (Nov4)

### Who can help?

@younesbelkada @SunMarc 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

load some AWQ model, like `"marcsun13/Llama-2-13B-AWQ"` - it has  `AwqConfig['version']` as a string "GEMM".
later in `utils/quantization.config.py::AWQcofig.post_init` there is this check:
```
        if self.version not in [AWQLinearVersion.GEMM, AWQLinearVersion.GEMV]:
            raise ValueError(
                f"Only supported versions are in [AWQLinearVersion.GEMM, AWQLinearVersion.GEMV] - not recognized version {self.version}"
            )
```
Apparently it fails because `version` is still a string "GEMM"

please consider some string -> enum conversion during init or rewrite this check when loading model.

### Expected behavior

normal model loading.

**Comment by choochtech** [comment]
Hi the normal cuda load

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("quant_autoawq")
model = AutoModelForCausalLM.from_pretrained("quant_autoawq",  device_map="cuda:0")

is taking up too much GPU memory

doesn't work like Auto AWQ  package as seen below.  

from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer, TextStreamer

tokenizer = AutoTokenizer.from_pretrained("quant_autoawq", trust_remote_code=True)
model = AutoAWQForCausalLM.from_quantized("quant_autoawq", fuse_layers=True)


What parameters do we need to pass ?

Thanks

**Comment by younesbelkada** [comment]
Hi @choochtech thanks for your message, would you mind posting a new ticket for your issue? it seems unrelated to the issue posted by @poedator !

**Comment by choochtech** [comment]
@younesbelkada  thanks
