### ISSUE TITLE
TypeError: ResNet.__init__() got an unexpected keyword argument 'out_indices'

### ISSUE THREAD

**Issue by wuxiaolianggit** [huggingface/transformers#27311]
Hello, may I ask you a question? How to solve this problem about “TypeError: ResNet.__init__() got an unexpected keyword argument 'out_indices‘”？@ @vanpelt @tmm1 @pvl @tmc @arfon

**Comment by amyeroberts** [comment]
Hi @wuxiaolianggit, thanks for raising this issue. 

So that we can help you, could you make sure to fill out the [bug report template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and include: 

* Minimal code reproducer
* The running environment: run `transformers-cli env` in the terminal and copy-paste the output

**Comment by wuxiaolianggit** [comment]
Okay, thank you very much for your reply@amyeroberts

**Comment by Goooyi** [comment]
I also encountered this error when I tried to load the `"timm/vit_small_patch14_dinov2.lvd142m"` model from Timm, this is how I called `timm.create_model`:
```python
timm.create_model(
                model_name="timm/vit_small_patch14_dinov2.lvd142m",
                features_only=False,
                pretrained=True,
                in_chans=3,
                out_indices=(2, 5, 8, 11),  # vit-s has total 12 blocks, I want those four level of features to be used as fpn for VitDet purpose
                norm_layer=FrozenBatchNorm2d,
            )
```

The `transformers-cli env` command return 
```bash
- `transformers` version: 4.35.0
- Platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.10
- Python version: 3.8.18
- Huggingface_hub version: 0.19.1
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 1.11.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no
```

The error I got is :
```bash
__init__() got an unexpected keyword argument 'out_indices'
```

**Comment by amyeroberts** [comment]
@Goooyi  - the error encountered is coming from the `timm` library and is unreleated to `transformers`. It's coming from the fact [VisionTransfomer](https://github.com/huggingface/pytorch-image-models/blob/ef72c3cd470dd67836eebf95ec567199c890a6a2/timm/models/vision_transformer.py#L389) doesn't accept `out_indices` as an input argument. If you think this is an error or a feature that should be supported I'd suggest opening a new issue in that repo.
