### ISSUE TITLE
AWQ quantization example in colab failures

### ISSUE THREAD

**Issue by poedator** [huggingface/transformers#27321]
### System Info

colab

### Who can help?

@younesbelkada @SunMarc 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

page https://huggingface.co/docs/transformers/main_classes/quantization refers to colab example for AWQ quantization.
this example fails:

1) [optional] After the 4.35.0 release it fails with error `ImportError: libcudart.so.12: cannot open shared object file: No such file or directory` during `from awq import AutoAWQForCausalLM`. I thought that it should work now without git+https installs with 4.35.

2)quantization_config = AwqConfig(... fails, because it expects `AWQLinearVersion.GEMM` and gets string "GEMM" instead. see my other issue today. 

3) the resulting model has no config at all. Which looks odd to me. It has `model.quant_config` though.

### Expected behavior

more normal

**Comment by younesbelkada** [comment]
Thanks @poedator for reporting, everything should be back to normal now. 
We tested it with autoawq==1.4.0 which did not had the strong requirement for CUDA>=12.0, that has been introduced in the most recent release: https://github.com/casper-hansen/AutoAWQ/releases/tag/v0.1.6 . To install autoawq with CUDA < 12.0 I had to call `pip install https://github.com/casper-hansen/AutoAWQ/releases/download/v0.1.6/autoawq-0.1.6+cu118-cp310-cp310-linux_x86_64.whl` (cc @casper-hansen in case I am mistaken somewhere).  
To retrive the config from the resulting model you need to check the attribute `model.model.config`, as done per the line:
```python
# the pretrained transformers model is stored in the model attribute + we need to pass a dict
model.model.config.quantization_config = quantization_config
```
The point 2 is temporarly solved if you call `lower()` to the version string, until https://github.com/huggingface/transformers/pull/27320 gets merged where it should perform str to enum conversion.
Again thanks for reporting, on my end everything looks resolved, I'll leave this issue open but if you think that everything has been addressed feel free to close the issue!

**Comment by casper-hansen** [comment]
@younesbelkada You are correct. PyPi only allows one release file, so I chose to update to the latest configuration of torch 2.1.0 and CUDA 12.1.1 that PyTorch offers. Extra wheels are made available with torch 2.0.1 and CUDA 11.8.0 for compatibility on the GitHub release itself.

**Comment by younesbelkada** [comment]
Ok makes sense, therefore I believe there is no fix to upstream on autoawq side, the only fix is on the notebook, which is done!

**Comment by poedator** [comment]
@casper-hansen , @younesbelkada - thank you for the quick response!

**Comment by Vasanth03** [comment]
Hi @casper-hansen 

-> I am trying to train the AWQ quantised model using hugging face trainer.
While using PEFT (LoRA adaptor) the following error pops up.

![Screenshot 2023-12-22 at 12 47 36 PM](https://github.com/huggingface/transformers/assets/59615743/0bf7d637-04a9-4830-8d74-da7fd02b128c)

-> This is the version that I have used !pip install -q -U https://github.com/casper-hansen/AutoAWQ/releases/download/v0.1.6/autoawq-0.1.6+cu118-cp310-cp310-linux_x86_64.whl

Any help is much appreciated. Thanks
