### ISSUE TITLE
Early stopping can not save best model at last

### ISSUE THREAD

**Issue by ILG2021** [huggingface/transformers#27332]
### System Info

- `transformers` version: 4.35.0
- Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.31
- Python version: 3.10.11
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.24.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sanchit-gandhi

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I finetune whisper with transformers and set a easy stopping in the trainer. The easy stop works but can not find best model:
the code is:
```
trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=common_voice["train"],
    eval_dataset=common_voice["test"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    tokenizer=processor.feature_extractor,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
)
```

the error report is:

`Could not locate the best model at whisper-large-v2-1.1.8/checkpoint-800/pytorch_model.bin, if you are running a distributed training on multiple nodes, you should activate `--save_on_each_node`.`

I have check the checkpoint folders no pytorch_model.bin in there, but why the trainer try to find pytorch_model.bin?

![image](https://github.com/huggingface/transformers/assets/93691919/496abca7-9f4f-41de-9eac-6c3d12f60024)

### Expected behavior

the best model can been saved at last.

**Comment by amyeroberts** [comment]
cc @muellerzr

**Comment by akwako** [comment]
Hi @ILG2021, what is in `trainer.args`?
