### ISSUE TITLE
Add OpenAI Whisper Large-v3 weights

### ISSUE THREAD

**Issue by gau-nernst** [huggingface/transformers#27331]
### Feature request

OpenAI released Whisper Large-v3.

https://github.com/openai/whisper/discussions/1762

I haven't looked into it closely but it seems the only difference is using 128-bin Mel-spec instead of 80-bin, thus weight conversion should be the same.

### Motivation

NA

### Your contribution

NA

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi

**Comment by gau-nernst** [comment]
I saw that the weights are already ported here: https://huggingface.co/openai/whisper-large-v3, and the announcements made by the team. Awesome work!
Are there any reasons why this issue is not closed?

**Comment by amyeroberts** [comment]
@gau-nernst As it's your issue, you can close it if you think it's resolved. #27336 hasn't been merged yet - so full v3 compatibility hasn't been shipped - depends what your "solved" criteria are :)
