### ISSUE TITLE
pyproject pytest config

### ISSUE THREAD

**Issue by diegovalenzuelaiturra** [huggingface/transformers#27345]
probably

`[tool.pytest.ini_options]` instead of `[tool.pytest]`

https://github.com/huggingface/transformers/blob/88832c01c8a962b653874c4ce4ed8df5783ac5cd/pyproject.toml#L21-L23

**Comment by amyeroberts** [comment]
cc @ydshieh

**Comment by ydshieh** [comment]
@diegovalenzuelaiturra Thank you a lot!

I opened a draft PR #27366: we need to check if everything still run as expected.

**Comment by ydshieh** [comment]
Reference: https://docs.pytest.org/en/stable/reference/customize.html
