### ISSUE TITLE
IDEFICS AttributeError: 'NoneType' object has no attribute 'device' when calling forward with inputs_embeds and image_encoder_embeddings

### ISSUE THREAD

**Issue by folbaeni** [huggingface/transformers#27343]
### System Info

- `transformers` version: 4.35.0.dev0
- Platform: Linux-6.1.0-10-amd64-x86_64-with-glibc2.36
- Python version: 3.10.8
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.24.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker  @younesbelkada @amyeroberts

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1.  Utilize the forward function with inputs_embeds and image_encoder_embeddings.
2.   Execute the code, which leads to the line causing the AttributeError as described above.

### Expected behavior

The code should execute without encountering the 'NoneType' object AttributeError and should properly assign the 'image_hidden_states' based on the 'image_encoder_embeddings' and input devices.

**Comment by ArthurZucker** [comment]
Hey! Could you share the full reproducer please? 🤗
