### ISSUE TITLE
Missing generation token for zephyr-beta

### ISSUE THREAD

**Issue by dt-ahmed-touila** [huggingface/transformers#27370]
### System Info

transformers version: 4.34.0
tokenizers version: 0.14.1
Platform: macOS 13.5.1
Python version: 3.8.10
huggingface-hub version: 0.17.3
PyTorch version(GPU?): 2.0.1 (False)
Tensorflow version (GPU?): not installed (NA)
Flax version (CPU?/GPU?/TPU?): not installed (NA)
Jax version: not installed
JaxLib version: not installed
Using GPU in script?: N
Using distributed or parallel set-up in script?: N

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("HuggingFaceH4/zephyr-7b-beta")
tokenizer.apply_chat_template([{"role": "user", "content": "What is life?"}], tokenize=False, add_generation_prompt=True)
```

Output: `<|user|>\nWhat is life?</s>\n`

### Expected behavior

`<|user|>\nWhat is life?</s>\n<|assistant|>`

**Comment by amyeroberts** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
cc @lewtun to this one, I think he wrote the chat template for Zephyr-beta!

**Comment by Rocketknight1** [comment]
Wait, no, my mistake! The issue is just that your version of `transformers` is slightly out of date @dt-ahmed-touila, and `add_generation_prompt` was only added in 4.35. Please `pip install --upgrade transformers` to resolve the issue!

**Comment by dt-ahmed-touila** [comment]
Thank you @Rocketknight1 ! Updating to `transformers-4.35.0` solved this.
