### ISSUE TITLE
decoder only beam search decoding indices usage

### ISSUE THREAD

**Issue by Hustcketlyj** [huggingface/transformers#27383]
### System Info

I am using beam search decoding on opt-1.3b, and I wish to know which beam is selected as the final output along the generation process, I looked at beam_indices, but the size is prompt size+number of token generated, if I ignore the first prompt size indices, the remaining indices are all -1. So what should i do.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

beam_indice=output_with_watermark.beam_indices[:,tokd_input["input_ids"].shape[-1]:][0], which is all -1.

### Expected behavior

na

**Comment by amyeroberts** [comment]
cc @gante

**Comment by gante** [comment]
Hey @Hustcketlyj 👋 

The beam indices ([docs](https://huggingface.co/docs/transformers/internal/generation_utils#transformers.generation.BeamSearchEncoderDecoderOutput.beam_indices)) are only -1 for unfilled positions ([reference in the code](https://github.com/huggingface/transformers/blob/c5037b459e117b9286c611092f38663f6cb763b0/src/transformers/generation/beam_search.py#L388)).

If that is not the case for you, I'll need a short reproducible script so I can figure out what might be wrong :)
