### ISSUE TITLE
load tokenizer size is different config vocab_size

### ISSUE THREAD

**Issue by lw3259111** [huggingface/transformers#27387]
### System Info

transformers==4.35.0
python==3.10
ubuntu==20

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. download model https://huggingface.co/IDEA-CCNL/Ziya2-13B-Base 
2.  from transformers import LlamaTokenizer
3. tokenizer = LlamaTokenizer.from_pretrained("/data/Ziya2-13B-Base/",legacy=False)
4. len(tokenizer)

### Expected behavior

I use the https://huggingface.co/IDEA-CCNL/Ziya2-13B-Base model
config.json
```json

{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "_flash_attn_2_enabled": true,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 13824,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "rotary_emb_base": 10000,
  "rotary_pct": 1,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.30.2",
  "use_cache": true,
  "use_parallel_residual": false,
  "vocab_size": 39424
}
```

when I load the tokenizer,the tokenizer size is 39410
<img width="684" alt="image" src="https://github.com/huggingface/transformers/assets/12690488/55f688d7-194a-4ebf-8c0b-5c0acbff70d1">

**Comment by ArthurZucker** [comment]
Hey! I recommend you to open the issue on the repo as we did not upload it and it might just be additional padding used for training that was not added to the tokenizer.
