### ISSUE TITLE
Do I need to conduct example skipping myself for IterableDataset data type when resuming from last_checkpoint?

### ISSUE THREAD

**Issue by Zcchill** [huggingface/transformers#27386]
### System Info

transformers:4.27.0
torch 2.1.0

### Who can help?

@muellerzr, @pacman100

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`    
  
    last_checkpoint = None
    if os.path.isdir(training_args.output_dir) and training_args.do_train and not training_args.overwrite_output_dir:
        last_checkpoint = get_last_checkpoint(training_args.output_dir)
        if last_checkpoint is None and len(os.listdir(training_args.output_dir)) > 0:
            raise ValueError(
                f"Output directory ({training_args.output_dir}) already exists and is not empty. "
                "Use --overwrite_output_dir to overcome."
            )
        elif last_checkpoint is not None and training_args.resume_from_checkpoint is None:
            logger.info(
                f"Checkpoint detected, resuming training at {last_checkpoint}. To avoid this behavior, change "
                "the `--output_dir` or add `--overwrite_output_dir` to train from scratch."
            )
`

The code sources from https://github.com/huggingface/transformers/blob/7ecd229ba475dbf78040f368ae86c86bba875442/examples/pytorch/language-modeling/run_clm.py#L296
And it haven't calculate the number of examples that need to be skipped. For original Dataset data type, I think these examples will be skipped in "Trainer.train()" since the dataset has length. However, the dataset type is always IterableDataset for pre-training corpus like Pile which has no length. In this case, do I need to conduct example skipping myself in my own data loading scripts for IterableDataset data type when resuming from last_checkpoint before "Trainer.train()"?

### Expected behavior

`

    last_checkpoint = None
    if os.path.isdir(training_args.output_dir) and training_args.do_train and not training_args.overwrite_output_dir:
        last_checkpoint = get_last_checkpoint(training_args.output_dir)
        if last_checkpoint is None and len(os.listdir(training_args.output_dir)) > 0:
            raise ValueError(
                f"Output directory ({training_args.output_dir}) already exists and is not empty."
                "Use --overwrite_output_dir to overcome."
            )
        elif last_checkpoint is not None and training_args.resume_from_checkpoint is None:
            logger.info(
                f"Checkpoint detected, resuming training at {last_checkpoint}. To avoid this behavior, change "
                "the `--output_dir` or add `--overwrite_output_dir` to train from scratch."
            )
            state = TrainerState.load_from_json(str(Path(last_checkpoint) / TRAINER_STATE_NAME))
            global_batch_size = training_args.train_batch_size * training_args.gradient_accumulation_steps * training_args.world_size
            num_skip_examples = state.global_step * global_batch_size
            logger.info(f"Skipping {num_skip_examples} examples")
`

**Comment by muellerzr** [comment]
No, the trainer does this under the hood. Check out the `_inner_training_loop`, iirc the logic lies in there
