### ISSUE TITLE
Development Infrastructure for ML Projects

### ISSUE THREAD

**Issue by shashankMadan-designEsthetics** [huggingface/transformers#2739]
Hi guys, I am sorry to post an issue that is a bit outside the scope of this project. But I have been a consistent watcher of the transformers project and it is excellent on how I can collaborate and coordinate with people and develop something.
But I am a rookie when it comes to working with people and get going with a project and I have been assigned a task to create reliable and scalable infrastructure, where a team can have space for research, development, test, deploy.
I have been dabbling around with bitbucket pipelines and docker but it would be helpful to get your opinions on it.

**Comment by julien-c** [comment]
This is an interesting subject but is way too broad for discussing here

**Comment by shashankMadan-designEsthetics** [comment]
@julien-c any forum you know for having this discussion?
