### ISSUE TITLE
Flax T5 models (at least) should use scan over layers technique

### ISSUE THREAD

**Issue by colehaus** [huggingface/transformers#27418]
### Feature request

See the technique described [here](https://docs.kidger.site/equinox/tricks/#improve-compilation-speed-with-scan-over-layers) and [here](https://github.com/google-research/t5x/blob/main/t5x/examples/scalable_t5/README.md#scan-over-layers). The essence is using a JAX `scan` instead of a python loop to iterate over layers that have the same structure.

### Motivation

The scan over layers technique allows JAX to "see" that the computational structure of each iteration is the same. This can dramatically reduce compile time and also system memory occupied by the JAX compilation cache (i.e. I believe if you have 25 layers in a model, the naive approach will end up with ~25 times as much JIT-compiled code since each layer will result in duplicative output code). My handwritten T5-like model uses ~1/50th of the system memory of the `transformers` Flax T5 models of similar size. It's easy to get system OOM errors with the current Flax implementation if you end up with multiple versions of the model compiled for different sequence lengths.

### Your contribution

It's possible I could submit a PR for this at some point in the future, but I can't be certain.

**Comment by sanchit-gandhi** [comment]
Hey @colehaus! Sorry for the late reply here. We've currently decided not to implement `scan` for the Flax models in Transformers. You can see a brief reason for this here: https://github.com/huggingface/transformers/pull/24587#discussion_r1347737942

Happy to re-open the conversation if you feel strongly about this! But currently I tend to view `scan` as something that can be used to build on the Transformers library.
