### ISSUE TITLE
do_lower_case strips accents!

### ISSUE THREAD

**Issue by alexvaca0** [huggingface/transformers#2742]
# 🐛 Bug

When calling BertTokenizer with do_lower_case=True, the tokenizer gets rid of accents, which is a misleading behavior not indicated in the name of the parameter. We suggest that you create another parameter which indicates whether or not to strip accents, separated from do_lower_case! This also happens in AutoTokenizer. For some languages, like spanish, this is crucial (hacia is not the same as hacía). Moreover, it's set to True by default. 
https://github.com/huggingface/transformers/blob/2184f87003c18ad8a172ecab9a821626522cf8e7/src/transformers/tokenization_bert.py#L346

**Comment by PhilipMay** [comment]
Well - is this realy a bug or just an improvement of the documentation?

**Comment by alexvaca0** [comment]
In my opinion it's a bug as it's misleading. If you want to do lower that doesn't mean you want to strip accents too. Those are two separate actions which the user should decide separately.
