### ISSUE TITLE
AutoModel find_adapter_config_file does not use revision

### ISSUE THREAD

**Issue by edbeeching** [huggingface/transformers#27429]
### System Info

- `transformers` version: 4.35.0
- Platform: Linux-6.2.0-36-generic-x86_64-with-glibc2.35
- Python version: 3.10.13
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.23.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I have a (private) repo `alignment-handbook/zephyr-7b-sft-lora` with two model revisions `main` a peft adapter and `main.merged` the adapter weights merged with the based model. 
If I try to load the merged model with the following:
```
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("alignment-handbook/zephyr-7b-sft-lora", revision="main.merged")
```

I get an error related to revisions on the base model:
```
OSError: main.merged is not a valid git identifier (branch name, tag name or commit id) that exists for this model name. Check the model page at 'https://huggingface.co/mistralai/Mistral-7B-v0.1' for available revisions.
```

I think the cause of this is `revision` kwarg is not passed to `find_adapter_config_file` [here](https://github.com/huggingface/transformers/blob/cf32c941350cb296e4c2c9e26a9274291d515e90/src/transformers/models/auto/auto_factory.py#L505C48-L505C48).

### Expected behavior

The correct merge model should be loaded.

**Comment by younesbelkada** [comment]
Hi @edbeeching you need to pass revision through `adapter_kwargs` as such:

```python
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("alignment-handbook/zephyr-7b-sft-lora", adapter_kwargs={"revision":"main.merged"})
```
So that we cover also the usecase where adapter weights and base model weights are on different revisions

**Comment by edbeeching** [comment]
Hi, as discussed on slack. The model I am loading is not an adapter. It is merged, the problems is that find_adapter_config_file is not using the model revision. Making PR with a fix now.
