### ISSUE TITLE
chatglm3-6b-32k does not support Flash Attention 2.0

### ISSUE THREAD

**Issue by abc123456cxx** [huggingface/transformers#27423]
When I use **AutoModelForCausalLM.from_pretrained(path, trust_remote_code=True, load_in_8bit= True,use_flash_attention=True,device_map="auto")**, it occers:
ValueError: The current architecture does not support Flash Attention 2.0. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new

**Comment by amyeroberts** [comment]
Hi @abc123456cxx, thanks for raising this. 

Is this a request to add flash attention to the model? If so, the [modeling files live on the hub](https://huggingface.co/THUDM/chatglm3-6b-32k/tree/main). Could you open an issue there to request this feature?
