### ISSUE TITLE
Adding Flash Attention Support for StableLMEpochForCausalLM

### ISSUE THREAD

**Issue by reletreby** [huggingface/transformers#27451]
### Feature request

Please add flash attention 2 support for StableLMEpochForCausalLM. Will help with finetuning Stability LM 3B model.

### Motivation

This will enable fine-tuning stability 3B LLM with flash attention 2

### Your contribution

Happy to help if needed!

**Comment by amyeroberts** [comment]
Hi @reletreby, thanks for opening this feature request! 

The stability LM model has it's code on the hub. I'd suggest opening up a discussion to request and/or PR to add the feature there. Let us know if you have any questions about the implementation!

**Comment by reletreby** [comment]
Sure! Will start a discussion. Thanks
