### ISSUE TITLE
Whisper error while not using whisper: "generation_config.return_timestamps ??= false;"

### ISSUE THREAD

**Issue by davidtbo** [huggingface/transformers#27452]
### System Info

I'm trying to use Transformers.js with a feature extraction pipeline and I happen to be using it in React NodeGUI. I'm getting an error that's from your Whisper model code and I'm not trying to use Whisper.

The sample code is below.

When I do `npm run dev` it goes fine, then when I run `npm start` I get this error:
`"generation_config.return_timestamps ??= false;"`

The trace output points to a line in the compiled` index.js` that is part of the `WhisperForConditionalGeneration` class. I have no interest in Whisper. Is there a way to disable it somehow? Why is this happening if I'm not using that class?

I appreciate your help figuring this out :) 

@ArthurZucker and @younesbelkada it looks like the instructions say I should tag you. Thanks for this great package!

### Reproduction

```
import { Text, View, Button, } from "@nodegui/react-nodegui";
import React, { useEffect, useState } from "react";
import { pipeline, Pipeline } from '@xenova/transformers';

let modelName = 'all-mpnet-base-v2'

export function EmbedderService() {
  const [embedder, setEmbedder] = useState<Pipeline>();

  useEffect(() => {
    (async () => {
      setEmbedder(await pipeline(
        'feature-extraction',
        modelName,
        { quantized: true}
      ))
    })()
  }, [])

  return (
    <View style={containerStyle}>
      <Text style={textStyle} wordWrap={true}>
        Embedder Status: 
      </Text>
    </View>
  )
}

const containerStyle = `
  flex: 1;
  justify-content: 'space-around';
`;

const textStyle = `
  padding-right: 20px;
`;

const btnStyle = `
  margin-horizontal: 20px;
  height: 40px;
`;

```

### Expected behavior

Builds without error instead of failing due to a model that I'm not using with this trace: 

```
dist/index.js:69312
        generation_config.return_timestamps ??= false;
                                              ^

SyntaxError: Unexpected token '='
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1106:15)
    at Module._compile (internal/modules/cjs/loader.js:1140:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47ith this trace:


```

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi

**Comment by ArthurZucker** [comment]
@xenova feel free to transfer this over to the `transformers.js` as it's not related to `transformers`

**Comment by xenova** [comment]
> @xenova feel free to transfer this over to the transformers.js as it's not related to transformers

I don't have the option to transfer, so perhaps the OP can close and reopen in the correct repo (which is http://github.com/xenova/transformers.js). Luckily this can be solved in a single reply:

@davidtbo This syntax error is due to your usage of an outdated version of Node.js. Please upgrade to at least version 18. All versions before 18 have reached [EOL](https://endoflife.date/nodejs), so we won't be adding support for them in future.

**Comment by sanchit-gandhi** [comment]
Thanks @xenova! Closing as complete as per the Node.js recommendation.
