### ISSUE TITLE
ERROR | index 4 is out of range

### ISSUE THREAD

**Issue by hdnh2006** [huggingface/transformers#27482]
### System Info

Hello everyone!

I am trying to deploy [this](https://huggingface.co/facebook/musicgen-stereo-small) model for testing purposes and I am facing several issues to run it in both, locally and using huggingface endpoints.

I have followed exactly [this](https://huggingface.co/blog/run-musicgen-as-an-api) and all the steps. However, in both, locally and in inference endpoints, I am facing the same issue and I get this error:
```
IndexError: index 4 is out of range
```
I just was able to run the model on Google Colab and I realized the transformers version was `4.36.0.dev0` so I tried to put on my `requirements.txt` file something like `transformers>=4.36.0` but it seems this version is not available on inference endpoints docker container.

So, in my particular case, do you have any idea how to solve this issue?

Thanks in advance

### Who can help?

I don't know who I must tag, sorry if I'm wrong:
@Narsil @ArthurZucker  

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-to-audio", model="facebook/musicgen-stereo-small")
```

### Expected behavior

The token or audio provided by the model.

**Comment by amyeroberts** [comment]
Hi @hdnh2006, thanks for raising this issue! 

Version `v4.26.0.dev0` indicates that the installed transformers was from the `main` branch on git. We haven't release 4.26 yet, so you can't install directly using pip and the library name.

To install from source (dev version):
```
pip install git+https://github.com/huggingface/transformers
```

**Comment by hdnh2006** [comment]
Thanks for the information, I did it and it worked!
