### ISSUE TITLE
Models with no max_pos_embeddings  will fail on run_clm.py

### ISSUE THREAD

**Issue by AdamLouly** [huggingface/transformers#27498]
### System Info

In run_clm.py we set up block_size to config.max_position_embeddings, assuming that all configs will have max_position_embeddings.
some models does not have max_position_embeddings as a part of their definition so they will fail when trying to train using run_clm.py

bloom is one example.

where you get this error if you try to run it:
AttributeError: 'BloomConfig' object has no attribute 'max_position_embeddings'

we can solve this by setting a check on whether the value exist otherwise put a default value on it.
I will create a PR  to address this.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run bloom on nightly version of transformers

### Expected behavior

AttributeError: 'BloomConfig' object has no attribute 'max_position_embeddings'

**Comment by amyeroberts** [comment]
Hi @AdamLouly - thanks for reporting an opening a PR to fix!
