### ISSUE TITLE
Add new Model - SegGPT: Segmenting Everything In Context

### ISSUE THREAD

**Issue by raghavanone** [huggingface/transformers#27514]
### Model description

Add new Model - SegGPT: Segmenting Everything In Context

The model code and weights are available. 

- Paper : https://arxiv.org/pdf/2304.03284.pdf
- Code : https://github.com/baaivision/Painter/tree/main/SegGPT/SegGPT_inference
- Weights : https://huggingface.co/BAAI/SegGPT/blob/main/seggpt_vit_large.pth

I will be implementing this model.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by ArthurZucker** [comment]
Hey, would you mind adding a link to the paper, the code and the released checkpoints? 😉
