### ISSUE TITLE
How to preupgrade transformer cache and build the upgraded into docker image?

### ISSUE THREAD

**Issue by lanyusan** [huggingface/transformers#27526]
### System Info

Linux ubuntu 22.04
Docker 24.05

I am not sure if this is the right place for this issue. Apology if it isn't and please direct me to the right place.

I have been using transformer in docker images that are deployed at runpod/replicate. The containers of the images could go cold and be relaunched again and again. Each time the container would waste 20 to 40 seconds for the blow cache upgrade.

```
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
```

It would take around 20 to 40 seconds, which is a significant waste of our GPU time and  container startup time.

I have tried to find out how to preupgrade the cache and build the upgrade cache into docker image by google but I couldn't find a way to do it.

Please advise how to preupgrade the cache and build the upgraded cache in docker image.

Many thanks.

### Expected behavior

The cache for model files is preupgraded and built into container image to avoid upgrade each time a container is launched.

**Comment by amyeroberts** [comment]
Hi @lanyusan, thanks for raising this issue! 

Could you confirm which version of transformers you're running? 

> The cache for model files is preupgraded and built into container image to avoid upgrade each time a container is launched.

This is something you'd have to handle on your side in terms of image setup etc. Here's the doc page about cache management: https://huggingface.co/docs/transformers/installation#cache-setup. To select where you want your cache, you'll want to set the `TRANSFORMERS_CACHE` env var.

**Comment by lanyusan** [comment]
@amyeroberts 

Thanks for the reply. It is exactly what I needed.
