### ISSUE TITLE
Allow script tracing DINOv2

### ISSUE THREAD

**Issue by Danil328** [huggingface/transformers#27537]
I found PR to dinov2 "Pass scale factor as a tuple of floats to F.interpolate() to allow tracing."
https://github.com/facebookresearch/dinov2/pull/247

https://github.com/huggingface/transformers/blob/85fde09c97213bf7e8625f83096bb2a9e183f987/src/transformers/models/dinov2/modeling_dinov2.py#L104C19-L104C19

**Comment by Danil328** [comment]
I have exception now
` File "/home/danilakhmetov/anaconda3/envs/pmlr/lib/python3.8/site-packages/transformers/models/dinov2/modeling_dinov2.py", line 131, in forward
    embeddings = embeddings + self.interpolate_pos_encoding(embeddings, height, width)
  File "/home/danilakhmetov/anaconda3/envs/pmlr/lib/python3.8/site-packages/transformers/models/dinov2/modeling_dinov2.py", line 106, in interpolate_pos_encoding
    patch_pos_embed = nn.functional.interpolate(
  File "/home/danilakhmetov/anaconda3/envs/pmlr/lib/python3.8/site-packages/torch/nn/functional.py", line 3967, in interpolate
    return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)
TypeError: upsample_bicubic2d() received an invalid combination of arguments - got (Tensor, NoneType, bool, tuple), but expected one of:
 * (Tensor input, tuple of ints output_size, bool align_corners, tuple of floats scale_factors)
      didn't match because some of the arguments have invalid types: (Tensor, !NoneType!, bool, !tuple of (Tensor, Tensor)!)
 * (Tensor input, tuple of ints output_size, bool align_corners, float scales_h, float scales_w, *, Tensor out)`

**Comment by amyeroberts** [comment]
Hi @Danil328, thanks for raising this issue! 

Could you make sure to follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and include details of your running environment and a minimal reproducible snippet? 

From the error it looks like the `scale_factor` values being passed to `interpolate` is a NoneType.

**Comment by Danil328** [comment]
Same problem in facebookresearch - https://github.com/facebookresearch/dinov2/issues/102
### Reproduction
`python
import torch
from transformers import AutoImageProcessor, AutoModel
from PIL import Image
import requests

url = 'http://images.cocodataset.org/val2017/000000039769.jpg'
image = Image.open(requests.get(url, stream=True).raw)

processor = AutoImageProcessor.from_pretrained('facebook/dinov2-base')
model = AutoModel.from_pretrained('facebook/dinov2-base')

inputs = processor(images=image, return_tensors="pt")
outputs = model(**inputs)
last_hidden_states = outputs.last_hidden_state

with torch.no_grad():
    example_input = torch.rand(1, 3, 224, 224, dtype=torch.float32, device="cuda")
    traced_model = torch.jit.trace(model.cuda(), example_input) # fails here
`
### Error
<img width="1162" alt="image" src="https://github.com/huggingface/transformers/assets/11178882/50aba4d4-5ad4-4398-9a26-5e63d337c61f">

### Expected behavior
Success

### Enviroment
`bash
python=3.8
torch==2.0.1
transformers==4.35.0
`

**Comment by amyeroberts** [comment]
@Danil328 - thanks for providing the snippet! I've opened a PR which should resolve the issue
