### ISSUE TITLE
Error when set pad_token

### ISSUE THREAD

**Issue by AndreWanga** [huggingface/transformers#27530]
### System Info

transformer version: 4.24.0

python version: 3.9.13

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When I use transformer for [chatglm2-6b](https://huggingface.co/THUDM/chatglm2-6b) , I try to run this code:

`tokenizer.pad_token = tokenizer.eos_token`

But raise an AttributeError: can't set attribute

### Expected behavior

code run successfully

**Comment by ArthurZucker** [comment]
Hey! Would you mind upgrading to the latest version of transformers and provide me with a reproducer of how you are initializing the model? 🤗
