### ISSUE TITLE
New Model Architecture

### ISSUE THREAD

**Issue by LegallyCoder** [huggingface/transformers#27538]
### Model description

I am writing a new model architecture. Its implementation is almost complete. I'm wondering how to integrate it into the hub. I forked the transformers lib and tried copying a model architecture, but it didn't work and it gave too many errors. How are things going here?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available

**Comment by amyeroberts** [comment]
Hi @LegallyCoder, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

For instructions on how to add a model and use a model on the hub, please refer to our documentation: 
* https://huggingface.co/docs/transformers/model_sharing
* https://huggingface.co/docs/transformers/custom_models

If you've followed these instructions and there is an error, please raise an issue and follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml).

**Comment by LegallyCoder** [comment]
Sorry, i didnt know this. You are right. I closed this isue.
