### ISSUE TITLE
Error when passing past_key_values back to generate()

### ISSUE THREAD

**Issue by dto** [huggingface/transformers#27546]
### System Info

- `transformers` version: 4.36.0.dev0
- Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.35
- Python version: 3.10.13
- Huggingface_hub version: 0.19.3
- Safetensors version: 0.4.0
- Accelerate version: 0.24.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0+rocm5.6 (True)
- Tensorflow version (GPU?): 2.14.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

The test python script attempts to retrieve past_key_values from the output of generate() and pass this value back to generate() to continue a chat style conversation. However, Transformers does not like the value and gives "RuntimeError: The size of tensor a (12) must match the size of tensor b (31) at non-singleton dimension 3" when it is passed back verbatim. Please see attached Python code and traceback output

[test.py.txt](https://github.com/huggingface/transformers/files/13382751/test.py.txt)
[traceback.txt](https://github.com/huggingface/transformers/files/13382752/traceback.txt)

### Expected behavior

I would expect that passing past_key_values back to generate() allows to continue the conversation.

**Comment by amyeroberts** [comment]
cc @gante

**Comment by gante** [comment]
Hi @dto 👋 Thank you for raising this issue!

`generate` expects the full input prompt to be passed, even if `past_key_values` is passed too. In this case, the input prompt is the full multi-round conversation. In your script, if you replace the `input_ids` input by `torch.cat((marvin_response.sequences, marvin_input_ids.to('cuda')), dim=-1)`, it will generate something along these lines:

```
<s><s> [INST] (+ 2 3) [/INST] The result of the expression `(+ 2 3)` is 5.</s><s> [INST] Please introduce yourself. [/INST] Hello! I'm an AI language model. I'm here to help you with any questions or tasks you might have. How may I assist you today?</s>
```

___________________________________________________

The fact that you need the full multi-round conversation may not be obvious, so I'm taking this issue as an opportunity to write documentation for this feature and clear things out :)
