### ISSUE TITLE
Flash Attention 2 for audio/musicgen

### ISSUE THREAD

**Issue by yoinked-h** [huggingface/transformers#27552]
### Feature request

Add flash attention 2 to musicgen models (and or audio gen)

### Motivation

Musicgen is a *really* large model, and its very hard to run on consumer GPUs, adding flash attention could make the model much lighter and possibly faster.

### Your contribution

I can test on both WSL and windows 11 on a 3060

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi @ylacombe

**Comment by yoinked-h** [comment]
I've tried to implement the Bart flash attention as best as i could, but i get some error (`cu_seqlens_k must have shape (batch_size + 1)`) from the module itself, will try tomorrow!

**Comment by amosyou** [comment]
we can close this due to #29939

**Comment by yoinked-h** [comment]
amazing!
