### ISSUE TITLE
Visualbert VQA model inference lower accuracy in validation

### ISSUE THREAD

**Issue by guanhdrmq** [huggingface/transformers#27559]

**Comment by amyeroberts** [comment]
Hi @guanhdrmq, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by guanhdrmq** [comment]
Hi @amyeroberts Thanks for letting me know. I reckon the probelem already posts in hugginface.
Just share another link alreayd talk about it: https://github.com/huggingface/transformers/issues/17360
