### ISSUE TITLE
Make style failed

### ISSUE THREAD

**Issue by jiqing-feng** [huggingface/transformers#27551]
### System Info

No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.36.0.dev0
- Platform: Linux-5.16.0-rc8-intel-next-01534-g53cb5f883cf7-x86_64-with-glibc2.28
- Python version: 3.9.16
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.3.1
- Accelerate version: 0.20.3
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.7.4 (cpu)
- Jax version: 0.4.13
- JaxLib version: 0.4.13
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When I run `make style`,  I got the following error

```
ruff check examples tests src utils setup.py conftest.py --fix
error: TOML parse error at line 17, column 1
   |
17 | [tool.ruff.format]
   | ^^^^^^^^^^^^^^^^^^
wanted exactly 1 element, more than 1 element

make: *** [Makefile:67: style] Error 2
```

### Expected behavior

It should be reformat all codes.

**Comment by amyeroberts** [comment]
Hi @jiqing-feng, thanks for raising this issue! 

A recent PR #27144 updated our formatting logic to use ruff formatter instead of black. Could you try updating ruff and run again? `pip install -U ruff`

**Comment by UmerHA** [comment]
Had the same issue & updating ruff solved this for me
