### ISSUE TITLE
Allow independent control of logging and progress bars across Trainer methods

### ISSUE THREAD

**Issue by harrisonfloam** [huggingface/transformers#27550]
### Feature request

Goal: Finer control of logging and progress tracking output for Trainer methods.

Specifically, I would like to suppress print logging and progress bars during in-training evaluation, but maintain the main training loop progress bar. A good solution would allow independent control of print logging and progress bars for each Trainer method (train, evaluate, predict).

### Motivation

Logging and progress tracking is great, but console-overflow is real. When training with an every-epoch evaluation strategy, my console (or notebook cell output) is overwhelmed with print logs and empty, completed tqdm progress bars.

The current options for logging control that I am aware of are:
- `log_level`: Setting to 'critical' seems to minimize warning-type output, but doesn't affect print logging of training metrics.
- `disable_tqdm`: Disables all tqdm progress bars globally. 
- `remove_callback(PrinterCallback)`: Suppresses print logs, but only when `disable_tqdm=True` due to a conditional in [trainer.py, line 528](https://github.com/huggingface/transformers/blob/b074461ef0f54ce37c5239d30ee960ece28d11ec/src/transformers/trainer.py#L528C15-L528C15). The `ProgressCallback` or `NotebookProgressCallback` that is added when `disable_tqdm=False` enables all logging with no option for suppression.
```
self.add_callback(PrinterCallback if self.args.disable_tqdm else DEFAULT_PROGRESS_CALLBACK)
```

Ideally, I would like to be able to independently disable progress bars for the evaluate calls inside the training loop, but maintain logging and progress bars for the training loop as a whole and any subsequent evaluate or predict calls. Suppressing all logging via `disable_tqdm` and `remove_callback(PrinterCallback)` solves the console-overflow issue, but leaves me staring at a blank screen wondering if my training loop is working.

### Your contribution

I have not contributed to huggingface before, but would be happy to work or collaborate on a PR.

This solution would likely require:
- moderate changes to `ProgressCallback` in [trainer_callback.py](https://github.com/huggingface/transformers/blob/main/src/transformers/trainer_callback.py).
- moderate changes to `NotebookProgressCallback` in [utils/notebook.py](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/notebook.py).
- very minor changes to [trainer.py](https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py) and [training_args.py](https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py).

**Comment by amyeroberts** [comment]
cc @muellerzr @pacman100
