### ISSUE TITLE
Support mix/complex FSDP wrap policy in Trainer

### ISSUE THREAD

**Issue by lchu-ibm** [huggingface/transformers#27573]
### Feature request

Support complex FSDP wrapping policy in Trainer api.

### Motivation

The current [implementation](https://github.com/huggingface/transformers/blob/2fc33ebead50383f7707b17f0e2a178d86347d10/src/transformers/trainer.py#L1387-L1404) seems to assume the wrap policy is either size based or transformer block(s) based, but there are many scenarios that might need other kinds of policy or a mix of different policies.

One example is [llama-recipes ](https://github.com/facebookresearch/llama-recipes/blob/cf678b9bf0af1c0e68e83b6c378e98125e0bc132/src/llama_recipes/utils/fsdp_utils.py#L4) uses a combination of lambda policy and transformer wrap policy.  So this makes it a little hard to use Trainer api to achieve the same thing.

**Comment by lchu-ibm** [comment]
Figured we can leverage `trainer.accelerator.state.fsdp_plugin.auto_wrap_policy()` to override the policy. closing this for now.

**Comment by chrockey** [comment]
Hi @lchu-ibm,

> Figured we can leverage trainer.accelerator.state.fsdp_plugin.auto_wrap_policy() to override the policy. closing this for now.

Could you please elaborate on your findings more? If I understand your comments correctly, you meant something like:
```python
trainer = Trainer(model, tokenizer, training_args, ...)
trainer.accelerator.state.fsdp_plugin.auto_wrap_policy = our_custom_wrap_policy # override the policy here
```
I wonder if I understand your comments correctly or not.

Thanks
