### ISSUE TITLE
[docs] Quantization

### ISSUE THREAD

**Issue by stevhliu** [huggingface/transformers#27575]
I was going through the [Quantization](https://huggingface.co/docs/transformers/main/en/main_classes/quantization) docs and noticed there is a ton of cool content in here that I wouldn't have necessarily discovered if I wasn't reviewing another PR that was translating this page. 

The current API page feels cluttered, making it a bit difficult to lookup the API references (parameters, docstrings, etc.) of the different configurations. I think it'd be nicer and cleaner if we moved all of this content into its own separate doc in the Performance and scalability section and leave the API page like this:

```md
# Quantization

add link to quantization guide here

## AWQ

[[autodoc]] AwqConfig

## AutoGPTQ

[[autodoc]] GPTQConfig

## bitsandbytes

[[autodoc]] BitsAndBytesConfig
```

This way, the quantization docs would also be more visible on their own and we can avoid blurring the lines between our guides and API docs.

Would love to hear what you think @younesbelkada @SunMarc @ArthurZucker ! 🙂

**Comment by younesbelkada** [comment]
Thanks for the proposal @stevhliu ! That sounds great !
