### ISSUE TITLE
Cannot reproduce SQUAD Example

### ISSUE THREAD

**Issue by eblaudez** [huggingface/transformers#2757]
I'm not able to reproduce the squad experimentation (via the example). I tried the command line;
python run_squad.py \
  --model_type bert \
  --model_name_or_path bert-base-cased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file $SQUAD_DIR/train-v1.1.json \
  --predict_file $SQUAD_DIR/dev-v1.1.json \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /tmp/debug_squad/

That gived very weird results

Then I read a little the forum and I tried:
python3 run_squad.py \
  --model_type bert \
  --model_name_or_path bert-base-cased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --version_2_with_negative \
  --train_file $SQUAD_DIR/train-v1.1.json \
  --predict_file $SQUAD_DIR/dev-v1.1.json \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --save_steps 10000 \
  --output_dir debug_squad/ \
  --overwrite_output_dir

(I also tried with v2 dataset it not works anymore). Can you give me some lead to reproduce the results given in the git readme, or the branch to do it ?

**Comment by LysandreJik** [comment]
1. What do you mean "weird results"?
2. What do you mean "v2 dataset it not works anymore"?
3. Please provide all the information required in the template, i.e. python version, transformers version, torch version etc

**Comment by eblaudez** [comment]
1. F1 & Exact match:~18 (should be 88/81 no ?)
2. Squad 2.0
3. Python 3.6, last transformer version (clone yesterday), torch 1.4.0

Tensorboard :
![squad_pb](https://user-images.githubusercontent.com/11454249/74007546-dbc43f80-497e-11ea-81bb-f7f8622d1a2a.png)
