### ISSUE TITLE
ImportError: tokenizers>=0.11.1,!=0.11.3,<0.14 is required for a normal functioning of this module, but found tokenizers==0.15.0. Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main Press any key to continue . . .

### ISSUE THREAD

**Issue by NiuDaVinci** [huggingface/transformers#27580]
### System Info

[DxDiag.txt](https://github.com/huggingface/transformers/files/13400236/DxDiag.txt)

 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I was following this tutorial.
https://youtu.be/O01BrQwOd-Q

I got this error ImportError: tokenizers>=0.11.1,!=0.11.3,<0.14 is required for a normal functioning of this module, but found tokenizers==0.15.0. Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main Press any key to continue . . .

I'm an artist, I don't even know if following this tutorial , but I was because I read this in [lora reddit](https://www.reddit.com/r/StableDiffusion/comments/10ubpts/does_anyone_know_the_solution_lora/ )" in your cuda version looks like not correct

can you install cuda as shown here? but before do a fresh installation of automatic1111 and let it install latest

[8 GB LoRA Training - Fix CUDA Version For DreamBooth and Textual Inversion Training By Automatic1111
](https://www.youtube.com/watch?v=O01BrQwOd-Q)  " **but I have 12gb of ram** 

### Expected behavior

don't know , can anybody tell me what's the best for me?

**Comment by ArthurZucker** [comment]
Hey! Sorry I'm not really sure I can help you with this. Do you have a code snippet of what you were using? (Other wise this should fix it: `pip install --upgrade transformers`
