### ISSUE TITLE
How to always use initial prompt in Whisper?

### ISSUE THREAD

**Issue by GanymedeNil** [huggingface/transformers#27592]
I checked this PR (#22496 ) but still can't figure out how to always use the initial prompt. is it possible to provide a use case?

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!

Thanks!

**Comment by GanymedeNil** [comment]
> Hey 🤗 thanks for opening an issue! We try to keep the github issues for bugs/feature requests. Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!
> 
> Thanks!

I will go to the forum to ask questions.
