### ISSUE TITLE
Whisper language not returned when return_timestamps="word" and return_language=True

### ISSUE THREAD

**Issue by Oscaarjs** [huggingface/transformers#27604]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.19.3
- Safetensors version: 0.4.0
- Accelerate version: 0.24.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0+cu118 (False)
- Tensorflow version (GPU?): 2.14.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.7.5 (cpu)
- Jax version: 0.4.20
- JaxLib version: 0.4.20
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@sanchit-gandhi 
@Narsil 
@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Steps to reproduce can be seen here;
[https://colab.research.google.com/drive/1RplLaZdD2DBy5NDDz9pSnk53jfEFM-Cm?usp=sharing](url)

Essentially it works as expected when return_timestamps=True, but not when return_timestamps="word".

### Expected behavior

When setting;
return_timestamps="word"
return_language=True

I expect the language to be returned as well.

As shown in linked colab it does work as expected when;
return_timestamps=True
return_language=True

**Comment by ArthurZucker** [comment]
This more a feature request than a bug, and is probably related to the fact that the language is not detected for the small chunk but for the full 30sec chunk of audio. + repeating the language does not seem to make sense for me, but we should also de-limit the start and end of detected language, which would bloat the code. I'll think about a potential solution 😉 
cc @Narsil who worked ont his refactor a while ago

**Comment by Oscaarjs** [comment]
Thank you for the reply @ArthurZucker! I agree it would be weird to repeat the language, especially for each "word chunk". Is there a reason "language" has been placed on a chunk-level if it's not computed on the same? Why is the language not shown on the "top" level, similar to how "text" is shown? Best regards
