### ISSUE TITLE
How can check hugging face pretrained model has metadata attribute?

### ISSUE THREAD

**Issue by JinSeoung-Oh** [huggingface/transformers#27620]
Hi, at first, I want to say thanks for you guys work and contribution.
My question is how can I check hugging face model has metadata attribute.

Theses day, I'm building GraphRAG with Llama-index and NubularDB for korean
Baseline for this work has already been completed.
But korean LLM performance is not good, so I tried the other model listed in OpenKo-LLM LeaderBoard
But all models I tried failed. 
Error message is 'Attribute Error: (Llamamodel / LlmaForcusalLM / Mistralmodel / MistralForcusalLM) has no attribute 'metadata''
It just my thought all xxxxForCusalML has no attribute 'metadata'.. Maybe

So, I just want to know how to check this.
I already asked it to LlamaIndex and NebularGraph, but I can not solve this problem.
According to LlamaIndex bot(dosu-bot), there is no reason why llama-index cannot be compatible with Hugging Face models
It said I have to check metadata attribution is properly defined for the model you plan to use.

How I can check it?

**Comment by ArthurZucker** [comment]
Hey! 🤗 thanks for the kind words!
Could you share the full traceback and how you called `transformers`. Metadata is not supposed to be present when you initialized a model IMO

**Comment by ydshieh** [comment]
It's likely this is something outside `transformers`, and need to open an issue in those libraries. But yes, we can only tell with a full log.

**Comment by JinSeoung-Oh** [comment]
@ArthurZucker @ydshieh 
Thanks!
And @ydshieh you are right.
I just misunderstood Llama-index bot' reply
This is korean(9:45 AM), and I just solved this problem 5 min ago.
Sorry for bothering..
Thanks!
