### ISSUE TITLE
Add albert-base-v3 to pretrained models?

### ISSUE THREAD

**Issue by nicolasahar** [huggingface/transformers#2763]
# 🚀 Feature request

Albert v3 was recently released on TFHub [here](https://tfhub.dev/google/albert_base/3). Could you please add it to the list of available pretrained models [here](https://huggingface.co/transformers/pretrained_models.html)?

## Motivation

Would provide the community with the most up-to-date albert version.

**Comment by LysandreJik** [comment]
Hi, as mentioned in their changelog, the only difference between the v2 and v3 is the compatibility with TF 1.15 as they removed the `einsum` operation.

It won't change anything for the huggingface/transformers users as the models available here are only for TF2.

![DeepinScreenshot_select-area_20200210155025](https://user-images.githubusercontent.com/30755778/74188771-25ca5100-4c1d-11ea-9362-22705e1889e3.png)
