### ISSUE TITLE
difference in tokenization - bert-base-multilingual-cased vs uncased

### ISSUE THREAD

**Issue by dsplog** [huggingface/transformers#27642]
### System Info

- `transformers` version: 4.33.3
- Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.17
- Python version: 3.8.18
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.23.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
>>> text = 'hello my dear'
>>> 
>>> from transformers import BertTokenizer
>>> bert_c_tok = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
>>> 
>>> enc_c_tok =  bert_c_tok.encode(text)
>>> print([bert_c_tok.decode([x]) for x in enc_c_tok])
['[CLS]', 'hell', '##o', 'my', 'dea', '##r', '[SEP]']
>>> 
>>> bert_unc_tok = BertTokenizer.from_pretrained('bert-base-multilingual-uncased')

>>> enc_unc_tok =  bert_unc_tok.encode(text)
>>> print([bert_unc_tok.decode([x]) for x in enc_unc_tok])
['[CLS]', 'hello', 'my', 'dear', '[SEP]']

```

### Expected behavior

was not expecting bert cased tokenization splitting "hello" as "hell" and "##o"

**Comment by ArthurZucker** [comment]
Hey 🤗 
1. If you want to know the actual tokenization you should be using:
```python
>>> text = 'hello my dear'
>>> 
>>> from transformers import BertTokenizer
>>> bert_c_tok = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
>>> bert_c_tok.tokenize(text)
['hell', '##o', 'my', 'dea', '##r']
```
2. These two tokenizers are different. Their pre-processing are different thus the tokens they produce during training do not have the same distribution. This means for example that `Hello` and `hello` are the same for the uncased model, thus they are more frequent, and thus not split into different tokens!

**Comment by dsplog** [comment]
ah, thanks for the clarification. will do some reading to understand the pre-processing fine prints. if you have any links to share, it will be helpful.
