### ISSUE TITLE
In which function it is best way to use the temperature parameter .from_pretrained()  or .generate()

### ISSUE THREAD

**Issue by pradeepdev-1995** [huggingface/transformers#27651]
### Feature request

in which function it is the best way to use the temperature parameter .from_pretrained  or .generate()
It seems that in both functions we can pass the temperature parameter. Which is the best way to do this?
```
Model = AutoModelForCausalLM.from_pretrained(model_name,
                                                                   device_map="auto", 
                                                                   temperature=0.1,
                                                                   do_sample=True,
                                                                   torch_dtype=torch.bfloat16)
```
or
```
Model.generate(**model_input,max_length=1000, temperature=0.1,do_sample=True,)
```

### Motivation

In which function it is the best way to use the temperature parameter .from_pretrained  or .generate()

### Your contribution

in which function it is the best way to use the temperature parameter .from_pretrained  or .generate()

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? 
I think the answer depends on the use case 😉 
Thanks!
