### ISSUE TITLE
Mask2Former slowdown starting from version 4.32.0

### ISSUE THREAD

**Issue by matteot11** [huggingface/transformers#27650]
### System Info

- System information: x86_64 GNU/Linux (with Titan RTX GPU)
- Ubuntu version: 18.04
- Python version: 3.8.12
- CUDA version: 11.1
- PyTorch version: 2.0.1
- transformers version: 4.32.0

### Who can help?

@amyeroberts

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
import torch
from transformers import Mask2FormerForUniversalSegmentation
import time

device = torch.device("cuda:0")
model = Mask2FormerForUniversalSegmentation.from_pretrained(
                "facebook/mask2former-swin-tiny-coco-instance",
                ).eval().to(device)
dummy_input = torch.randn((2,3,640,640)).to(device)

times = []
with torch.no_grad():
    for i in range(100):
        t1 = time.time()
        out = model(dummy_input)
        t2 = time.time()
        times.append(t2-t1)
print(sum(times)/len(times))
```
The code above computes average forward time for Mask2Former through 100 iterations.
The following average forward time is obtained with different ```transformers``` versions:
- ```transformers==4.31.0```-> ~0.133 s
- ```transformers==4.32.0``` -> ~0.405 s
- ```transformers==4.33.1``` -> 0.507 s

Versions 4.32.0 and 4.33.1 introduced, respectively:
- https://github.com/huggingface/transformers/pull/25297
- https://github.com/huggingface/transformers/pull/25741

I also report here my original torchscript export issue, form which the above PRs originated:
https://github.com/huggingface/transformers/issues/25261

### Expected behavior

I would expect similar (or slightly higher) inference times for Mask2Former after einsum removal and memory load reduction.

**Comment by ArthurZucker** [comment]
cc @amyeroberts

**Comment by amyeroberts** [comment]
Hi @matteot11 - thanks for raising! Looking into it 🕵️

**Comment by amyeroberts** [comment]
Hi @matteot11 - I'm still looking into this. You're completely correct in your diagnosis of the offending PRs. The difficulty is that these were fixing other issues e.g. enabling tracing for the model. At the moment I'm looking into how to improve this e.g. profiling for other places to improve, rewriting the current logic or reenabling einsum (some tracing issues have been fixed in torch)
