### ISSUE TITLE
LongT5 - Errors

### ISSUE THREAD

**Issue by gozdeydd** [huggingface/transformers#27654]
I am not very sure if the models/documentation is up to date in the website. For example, I have experienced this with a LongT5 model. It gives an error that transformers library doesn't have such model. 

I assume this happens due to the fast changes going on with NLP models in general these days. Perhaps there is a new version?

**Comment by ArthurZucker** [comment]
Hey! If you want some help you should provide a reproducer of what the error was with the output of `transformers-cli env` 🤗
