### ISSUE TITLE
XLA Integration for TensorFlow Models 

### ISSUE THREAD

**Issue by akote123** [huggingface/transformers#27664]
Hi,
    I wanted to try XLA for Inference. 
```python
import os
#environment configs

import tensorflow as tf

from transformers import BertTokenizer, TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained("bert-base-uncased")
xla_generate = tf.function(model, jit_compile=True)
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')

from time import time
start_time = time()
for i in range(1):
    output = xla_generate(encoded_input)
end_time = time()
time_taken = end_time - start_time
print("average time (seconds) for bert Inference: ", time_taken)`
```
For this code I am getting timing which more than without XLA and IF look into perf report of this I am not seeing any XLA OP and I am seeing oneDNN . So I wanted to understand how this XLA works with oneDNN

**Comment by ArthurZucker** [comment]
Hey! Here is what you gotta know about using xla:

> When you are executing an XLA-enabled function (like `xla_generate()` above) for the first time, it will internally try to infer the computation graph, which is time-consuming.  This process is known as [“tracing”](https://www.tensorflow.org/guide/intro_to_graphs#when_is_a_function_tracing). 

> You might notice that the generation time is not fast. Successive calls of `xla_generate()` (or any other XLA-enabled function) won’t have to infer the computation graph, given the inputs to the function follow the same shape with which the computation graph was initially built. While this is not a problem for modalities with fixed input shapes (e.g., images), you must pay attention if you are working with variable input shape modalities (e.g., text).

See [the documentation](https://huggingface.co/docs/transformers/tf_xla#gotchas-to-be-aware-of)
