### ISSUE TITLE
how to remove punctuation marks.

### ISSUE THREAD

**Issue by chanyong-owl** [huggingface/transformers#27666]
### System Info

i trained t5-large for translation.

the result of train was good

But when i input some sentence, the result is like that "What are you doing now?.??....."

[?.??......] <- how to delete that punctuation marks.

i put some parameter like max_length. But i can not solve that situation

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

c

### Expected behavior

cfdvf

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!

Thanks!
