### ISSUE TITLE
Remote code improvements

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/transformers#27688]
Originally posted by @Jackmin801 on the awesome [_jinaai/jina-embeddings-v2-base-en_](https://huggingface.co/jinaai/jina-embeddings-v2-base-en/discussions/5#654102670a2101c338f3d737) repository.

> 1. Documentation
> The clarity of the transformers [documentation on custom models](https://huggingface.co/docs/transformers/custom_models) could be improved by describing the syntax of `auto_map` in *config.json*. We never used the `register` functions and would just directly modify the *config.json*. The behaviour that allowed one to use code on the Hub from another repo using "--" doesn't seem to be documented anywhere but we figured out that it was possible because `save_pretrained` saves in this format when using a custom model. The feature does seem to be pretty new though (I believe ~6 months ago?) so maybe that is why it hasn't been too well documented yet. But we think that if it was better communicated to users that it was possible to do this, more people would develop on the Hub as we did.
> 
> 2. Promote `trust_remote_code` to environment variable
> Some downstream libraries currently do not support passing the `trust_remote_code` argument. Notable to our work was `sentence_transformers`, despite quite a few requests for this [[1](https://github.com/UKPLab/sentence-transformers/issues/1473), [2](https://github.com/UKPLab/sentence-transformers/issues/2272), [3](https://github.com/UKPLab/sentence-transformers/pull/2274)]. This leads to us needing to [monkeypatching the model loading logic in the libraries](https://github.com/simonw/llm-sentence-transformers/pull/10/files) to be able to use our model. If `trust_remote_code` could be read from an environment variable e.g. `HUGGINGFACE_TRUST_REMOTE_CODE`, it would make it such that one only need set the environment variable to enable loading custom models. This would make the use of custom models much easier to adopt throughout the ecosystem.
> 
> 3. Silent failure when `trust_remote_code` is not set to True.
> When `trust_remote_code` is not set to True for our model, the behaviour seems to be that it loads the classic BERT implementation from transformers and [throws a bunch of warnings from re-initialised weights](https://x.com/simonw/status/1716644983917392330?s=20). This is not ideal because if a downstream evaluation script forgot to set the arg, it would generate inaccurate results and the only way of knowing that something was wrong was to scroll through the output logs and see if this warning appeared or print the model and see if the model has the right name. If instead, it would error and ask the user to set the `trust_remote_code` arg, it would be more easily caught and save us quite some head scratching and communication overhead in the team.

Definitely agree with all the points above; would be awesome to work on this.

**Comment by LysandreJik** [comment]
1. was resolved by @MKhalusova in https://github.com/huggingface/transformers/pull/27213, it will be in the next release :hugs:

**Comment by muupan** [comment]
> 2. Promote `trust_remote_code` to environment variable

This has not been resolved yet, right? This would be very helpful when working with downstream libraries like TRL.
