### ISSUE TITLE
The prediction output is random

### ISSUE THREAD

**Issue by Mozen** [huggingface/transformers#2770]
When I  use the official example scripts to predict a text sentence classification model,  I found that the output is different every time。

```
from transformers import BertTokenizer, BertForSequenceClassification
import torch
import numpy as np

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
model.eval()
input_ids = torch.tensor(tokenizer.encode("my dog is cute", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
labels = torch.tensor([1]).unsqueeze(0)  # Batch size 1
outputs= model(input_ids)
print(outputs)
```

fist result :(tensor([[-0.1939,  0.1449]], grad_fn=<AddmmBackward>),)
second result:(tensor([[-0.2425, -0.2737]], grad_fn=<AddmmBackward>),)
third result: (tensor([[ 0.0494, -0.7208]], grad_fn=<AddmmBackward>),)
......

I expected the outputs to be the same... am I doing this wrong?

**Comment by jwallat** [comment]
Hi @Mozen, 
You will need to train your model for sequence classification first.
The pre-trained models are not yet trained for the downstream task. So right now, you have an untrained sequence classification head on top of Bert. 

I could not find where it was mentioned in the docs, but have a look at [this comment](https://github.com/huggingface/transformers/issues/1979#issuecomment-559597512).

**Comment by Mozen** [comment]
@jwallat ok， thanks  a lot！

**Comment by BramVanroy** [comment]
Please close the question if your question is answered.
