### ISSUE TITLE
type object 'OPTDecoder' has no attribute '_prepare_decoder_attention_mask'.

### ISSUE THREAD

**Issue by muzi0111** [huggingface/transformers#27701]
I'm currently facing an issue as follows: which version of Transformers should I install? The latest version does not seem to have this configuration option. I'm getting an AttributeError: type object 'OPTDecoder' has no attribute '_prepare_decoder_attention_mask'.

**Comment by ArthurZucker** [comment]
Hey! I think that version 4.34.0 should work. This attribute was removed in #27086 and it was a private method so not a breaking change
