### ISSUE TITLE
`hub_strategy`'s documentation for `checkpoint` option is wrong and misleading

### ISSUE THREAD

**Issue by omermazig** [huggingface/transformers#27728]
### System Info

The documentation for [hub_strategy](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.hub_strategy) seems to be mistaken, because it stated:

> "checkpoint": like "every_save" but the latest checkpoint is also pushed in a subfolder named last-checkpoint, allowing you to resume training easily with trainer.train(resume_from_checkpoint="last-checkpoint").

But when I did that, I got:

> ValueError: 'videomae-finetuned/checkpoint-3000' is not in list

Where checkpoint 3000 was my **best** checkpoint (according to my `metric_for_best_model`)

So for `resume_from_checkpoint` to work, I found that I need to have both the last checkpoint AND the best checkpoint available in the output dir of the `Trainer`, and pass resume_from_checkpoint=True.

### Who can help?

@muellerzr and @pacman100

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

On any training process using the trainer, pass `hub_strategy="checkpoint"`, get the saved checkpoint from the hub, and run:

`trainer.train(resume_from_checkpoint="local/path/to/checkpoint"`

### Expected behavior

Other than fixing the docs, I think there should be a "best_and_last" option, which updates both the best (if changed) and last checkpoints in the hub, and that way really support resuming from a checkpoint.

A more complex solution would be to incorporate it with the `save_total_limit` mechanism - since both are "keeping" checkpoints - but that's a bigger change.

**Comment by muellerzr** [comment]
A PR to the docs would be great, I also believe that if we use `save_total_limit`, it should take into account *not* deleting the one that has the best metric, and looking at the oldest scale to delete before that. I can look into this if it's a bit too complex on your end 😄
