### ISSUE TITLE
How to save the generated output of BarkModel to an npz file?

### ISSUE THREAD

**Issue by chet-chen** [huggingface/transformers#27737]
Hello there!

I'm using the BarkModel from Hugging Face Transformers and I'm wondering how to save the generated results to an npz file. I'd like to use these saved results as history prompts for the next generation.

In the [suno-ai/bark](https://github.com/suno-ai/bark) , when using the [`semantic_to_waveform`](https://github.com/suno-ai/bark/blob/main/bark/api.py#L35) method, I can pass `output_full = True`. This allows me to save the output to an npz file using `numpy.savez`.

However, as I transition to using the BarkModel within the transformers framework, I am uncertain about the equivalent process. Could you kindly provide guidance on how to save the generated results of the BarkModel to an npz file in the Transformers library?

Any assistance or code examples you could offer would be greatly appreciated.

Thank you for your time and support.

**Comment by ArthurZucker** [comment]
cc @ylacombe

**Comment by ylacombe** [comment]
Hey @chet-chen, let me take a look!
From the back of my mind, I think it requires to add something similar to `output_full = True` to BarkModel.

**Comment by chet-chen** [comment]
@ylacombe I'm relatively new to Python, and I'm facing a challenge in converting the results generated by the BarkSemanticModel, BarkCoarseModel, and BarkFineModel models into a numpy.ndarray with the right shape. These models output torch.LongTensor, and I need help transforming them.

https://github.com/huggingface/transformers/blob/80377eb018c077dba434bc8e7912bcaed3a64d09/src/transformers/models/bark/modeling_bark.py#L1820-L1854
