### ISSUE TITLE
How to load a pretrained TF model using AutoModel?

### ISSUE THREAD

**Issue by erikchwang** [huggingface/transformers#2773]
Run the following code:
```
import tensorflow as tf
from transformers import AutoModel, TFBertModel

auto_model = AutoModel.from_pretrained("bert-base-uncased")
tfbert_model = TFBertModel.from_pretrained("bert-base-uncased")

print(auto_model.__class__)
print(tfbert_model.__class__)
```
Then the output is:
```
<class 'transformers.modeling_bert.BertModel'>
<class 'transformers.modeling_tf_bert.TFBertModel'>
```
It seems that AutoModel defaultly loads the pretrained PyTorch models, but how can I use it to load a pretrained TF model?

**Comment by julien-c** [comment]
Hi @erikchwang, you should use `TFAutoModel` instead

**Comment by erikchwang** [comment]
Is this TFAutoModel mentioned in the document? I cannot find it...

**Comment by julien-c** [comment]
I'll add it to the model pages soon. Thanks!

**Comment by policeme** [comment]
when I load TF model by use AutoModel from your document, there are many errors, like this 
`model = AutoModel.from_pretrained(r'/Users/maxiong/Workpace/Code/transformers/pre_model/bert_model.ckpt.index', from_tf=True,  config=config)
`
![image](https://user-images.githubusercontent.com/30991932/76698572-99112800-66df-11ea-9dd7-5e382abda388.png)

when I used TFAutoModel to load a model, there is like this
`model = TFAutoModel.from_pretrained(r'/Users/maxiong/Workpace/Code/transformers/pre_model/bert_model.ckpt.index', config=config)
`
![image](https://user-images.githubusercontent.com/30991932/76698602-f73e0b00-66df-11ea-9121-67a663b4a8ee.png)

I tried many functions to load TF Pretraining model in your document, most of them appeared errors

**Comment by blmali** [comment]
I can't able to load model for  model = TFAutoModel.from_pretrained("emilyalsentzer/Bio_ClinicalBERT")
and
TFAutoModel
    .from_pretrained('microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext')
anyone ?

**Comment by juanmanuelvc** [comment]
> I can't able to load model for model = TFAutoModel.from_pretrained("emilyalsentzer/Bio_ClinicalBERT")
> and
> TFAutoModel
> .from_pretrained('microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext')
> anyone ?

HI @blmali, I had the same issue when trying to load "emilyalsentzer/Bio_Discharge_Summary_BERT". I solved it by passing `from_pt` argument as `True`:
`model = TFAutoModel.from_pretrained("emilyalsentzer/Bio_Discharge_Summary_BERT", from_pt=True)`.

I hope this helps.
