### ISSUE TITLE
Pipeline instantiation of model "facebook/nllb-200-distilled-600M" requires source and target language as mandatory

### ISSUE THREAD

**Issue by drunkeninja42** [huggingface/transformers#27753]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0+cu118 (False)
- Tensorflow version (GPU?): 2.14.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.7.5 (cpu)
- Jax version: 0.4.20
- JaxLib version: 0.4.20
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@stevhliu @MKhalusova 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Steps to Reproduce:
1. Go to `https://huggingface.co/facebook/nllb-200-distilled-600M`
2. Click `Use in Transformers` Tag
3. Copy the `# Use a pipeline as a high-level helper` code snippet
4. Run in your notebook
5. Error is displayed asking for `src_lang` and `tgt_lang` as mandatory kwags.
![code snippet](https://github.com/huggingface/transformers/assets/56391795/86ddd6ac-05ff-4b3c-8b40-dbf53bd4d7dc)

### Expected behavior

I expect the code snippet in the `Use in Transformers` tag to mention these `kwags` in the example as they are mandatory to be used in this model and while the translation tasks.

I will love to contribute to this issue.
Thanks!

**Comment by drunkeninja42** [comment]
Hey @ArthurZucker @stevhliu !
If there are some improvements or work required in this issue, I would love to work and contribute to🤗

**Comment by ArthurZucker** [comment]
Hey @drunkeninja42 feel free to open a PR that increase the specific doc in this case if yo feel like it!

**Comment by drunkeninja42** [comment]
Sure @ArthurZucker , will raise the PR for this today, Thanks !

**Comment by st81** [comment]
@ArthurZucker 
I'm eager to address this issue and I believe it might be beneficial to implement a code snippet similar to the one provided below.

```py
# Use a pipeline as a high-level helper
from transformers import pipeline

# Change `xx` to the language of the input and `yy` to the language of the desired output.
pipe = pipeline("translation_xx_to_yy", model="facebook/nllb-200-distilled-600M")
```

However, I'm unsure about the exact location in the source code where I should make modifications to update the code snippet. Could you please provide guidance on this matter? Thank you!

**Comment by ArthurZucker** [comment]
This should go in the `nllb.md` IMO!

**Comment by amanueldemirew** [comment]
but what if it has eng_lat
