### ISSUE TITLE
How to inference the model with 200k length context

### ISSUE THREAD

**Issue by taishan1994** [huggingface/transformers#27755]
### Model description

I want to test Yi-34B-200k,  Although I ran through the model, as the context length increased, OOM appeared, and I wondered how I could test to 200k context length with sufficient GPU resources.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by ArthurZucker** [comment]
Hey! Thanks for opening this issue! Would recommend you to look into the `mistral` model which should support fairly (~16K) context length with linear memory consumption. Also make sure that you did not activate gradient computation!

**Comment by CrisJk** [comment]
> ### Model description
> I want to test Yi-34B-200k, Although I ran through the model, as the context length increased, OOM appeared, and I wondered how I could test to 200k context length with sufficient GPU resources.
> 
> ### Open source status
> * [x]  The model implementation is available
> * [x]  The model weights are available
> 
> ### Provide useful links for the implementation
> _No response_

I met the same issue. Did anyone else solve that?

**Comment by taishan1994** [comment]
> 设置output_scores=False（一般默认是这个）和use_cache=False，应该就不会有OOM

请问下你测的哪个模型，测到的最大长度是多少额？

**Comment by CrisJk** [comment]
> > 设置output_scores=False（一般默认是这个）和use_cache=False，应该就不会有OOM
> 
> 请问下你测的哪个模型，测到的最大长度是多少额？

不好意思，后来重新测了下，200K的长度HF应该是没办法达到的

**Comment by CrisJk** [comment]
> > 设置output_scores=False（一般默认是这个）和use_cache=False，应该就不会有OOM
> 
> 请问下你测的哪个模型，测到的最大长度是多少额？

刚测了下128K长度，用flash attention是没啥问题的
