### ISSUE TITLE
BERT model is slow in Pytorch

### ISSUE THREAD

**Issue by akote123** [huggingface/transformers#27756]
### System Info

transformers                 4.35.2
tensorflow                    2.15.0
torch                            2.1.1

- `transformers` version: 4.35.2
- Platform: Linux-6.2.0-1016-aws-aarch64-with-glibc2.35
- Python version: 3.11.0
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.0
- Accelerate version: 0.24.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.1 (False)
- Tensorflow version (GPU?): 2.15.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

TF code is as follows:
[tf_bert.txt](https://github.com/huggingface/transformers/files/13499939/tf_bert.txt)
Pytorch code is : 
[pytorch_bert.txt](https://github.com/huggingface/transformers/files/13499940/pytorch_bert.txt)

### Expected behavior

I have tried BERT uncased model with Tensorflow and Pytorch but Pyt is slower . In pytorch if I increase the batch size to 512 the system gets hang.

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!

Thanks!
