### ISSUE TITLE
Pipeline for text classification

### ISSUE THREAD

**Issue by AlecS12** [huggingface/transformers#2776]
# 🚀 Feature request
Could  you please add a text classification pipeline?

**Comment by julien-c** [comment]
Did you check the README?

grep `text-classification: Initialize a TextClassificationPipeline directly, or see sentiment-analysis for an example.
`

**Comment by AlecS12** [comment]
Sorry, missed this somehow.  Thanks for adding it!

**Comment by ParthGandhi** [comment]
@julien-c trying that throws: 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-b612b71d2864> in <module>
      1 sentiment_analysis = pipeline('sentiment-analysis')
----> 2 text_classification = pipeline('text-classification')

~/SpacedOut/engage-sentiment/.venv/lib/python3.7/site-packages/transformers/pipelines.py in pipeline(task, model, config, tokenizer, modelcard, framework, **kwargs)
   1024     # Retrieve the task
   1025     if task not in SUPPORTED_TASKS:
-> 1026         raise KeyError("Unknown task {}, available tasks are {}".format(task, list(SUPPORTED_TASKS.keys())))
   1027 
   1028     framework = framework or get_framework(model)

KeyError: "Unknown task text-classification, available tasks are ['feature-extraction', 'sentiment-analysis', 'ner', 'question-answering', 'fill-mask']"
```

**Comment by julien-c** [comment]
you should import and use `TextClassificationPipeline` directly (i.e. there isn't a shortcut to use in `pipeline()`)

**Comment by yangliu2** [comment]
I'm going to ask the stupid question, and say there are no tutorial or code examples for `TextClassificationPipeline`. I mean I can dig up the source code, but documentation without examples is never my thing. Would be helpful if I know the data format for `run_tf_text_classification.py` as well.
