### ISSUE TITLE
`spectrogram` function may silently produce incorrect values for certain inputs

### ISSUE THREAD

**Issue by xenova** [huggingface/transformers#27772]
### System Info

- `transformers` version: 4.36.0.dev0
- Platform: Linux
- Python version: 3.8.3
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.3.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@sanchit-gandhi @hollance

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code for reference:

https://github.com/huggingface/transformers/blob/62ab32b2997846526cdffd629c72c47bc7b4f215/src/transformers/audio_utils.py#L451-L457

If `power=None` and `mel_filters != None`, then we will be performing `np.maximum` between 1 array of real numbers and 1 array of complex numbers. Since complex numbers do not have an ordering, `np.maximum` will only look at the real parts (for some reason, that is how it is implemented):
```py
>>> import numpy as np
>>> np.maximum(np.array([1,2,3]), 5j)
array([1.+0.j, 2.+0.j, 3.+0.j])
```

As a result, the function will continue without throwing an error.

Possible fixes:
1. If `power=None`, still perform `np.abs()`
2. Throw an error if this combination of arguments is provided

It should be noted that although I haven't found a processor which uses the function with these inputs, it may cause an issue in future, or for users of the spectrogram function directly.

### Expected behavior

An error should be thrown, or the absolute value should be taken if power is None.

**Comment by ArthurZucker** [comment]
Feel free to open a PR for a fix 😈

**Comment by sanchit-gandhi** [comment]
cc @ylacombe would you be able to take a look at protecting against this edge case?
