### ISSUE TITLE
`ZeroShotAudioClassificationPipeline` documentation includes example to duplicate hypothesis template

### ISSUE THREAD

**Issue by xenova** [huggingface/transformers#27783]
### System Info

- `transformers` version: 4.36.0.dev0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0+cu118 (False)
- Tensorflow version (GPU?): 2.14.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.7.5 (cpu)
- Jax version: 0.4.20
- JaxLib version: 0.4.20
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@ArthurZucker (original implementer) @Vaibhavs10 @sanchit-gandhi (audio team)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Visit [documentation](https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.ZeroShotAudioClassificationPipeline)
2. Example is:
```py
from transformers import pipeline
from datasets import load_dataset

dataset = load_dataset("ashraq/esc50")
audio = next(iter(dataset["train"]["audio"]))["array"]
classifier = pipeline(task="zero-shot-audio-classification", model="laion/clap-htsat-unfused")
classifier(audio, candidate_labels=["Sound of a dog", "Sound of vaccum cleaner"])
```
3. However, this is duplicated due to [this](https://github.com/huggingface/transformers/blob/29f1aee3b6c560182415fcb9e2238125e2f5b29c/src/transformers/pipelines/zero_shot_audio_classification.py#L118-L122) portion of code:
https://github.com/huggingface/transformers/blob/29f1aee3b6c560182415fcb9e2238125e2f5b29c/src/transformers/pipelines/zero_shot_audio_classification.py#L118-L122

4. Sentences become: `['This is a sound of Sound of a dog.', 'This is a sound of Sound of vaccum cleaner.']`

### Expected behavior

Sentences should be either:
- `['Sound of a dog.', 'Sound of vaccum cleaner.']`
- `['This is a sound of a dog.', 'This is a sound of vaccum cleaner.']`

**Comment by ArthurZucker** [comment]
Yeah, not super clear what we should do, maybe regex the hypothesis template? Updating the doc is a good start

**Comment by ArthurZucker** [comment]
I'll open PRs for this and Whisper

**Comment by ArthurZucker** [comment]
Oops opening this today! 🤗

**Comment by sanchit-gandhi** [comment]
Happy to take care of this Arthur or want myself or @ylacombe to take a look?

**Comment by ArthurZucker** [comment]
sure, completely forgot about it!
