### ISSUE TITLE
Is there any difference between hf-implemented llama2 and facebook-implemented llama2 ?

### ISSUE THREAD

**Issue by artetaout** [huggingface/transformers#27784]
In my view, hf-implemented llama2, the "intermediate size" is 11008, but in facebook-implemeted llama2, it's 4 * hidden_size ?
why?

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!

Thanks!
