### ISSUE TITLE
configuration from custom config file not working 

### ISSUE THREAD

**Issue by mainulquraishi** [huggingface/transformers#2779]
I am trying to get the configuration from a custom config file by the following line : 
`config = GPT2Config.from_pretrained("./lm/gpt2-xl/lm/my_config.json")`

This is similar to the example of this [page]. But I am getting the following error:
```
OSError: Model name './lm/gpt2-xl/lm/my_config.json' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/./lm/gpt2-xl/lm/my_config.json/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.
(https://huggingface.co/transformers/main_classes/configuration.html#transformers.PretrainedConfig)
```
Am I missing something?

**Comment by LysandreJik** [comment]
Did you try using `GPT2Config.from_json_file('xxx.json')`? `from_pretrained` should be used when pointing to a directory containing a `config.json` file.

**Comment by mainulquraishi** [comment]
yes it is working now

**Comment by LysandreJik** [comment]
Great to hear!
