### ISSUE TITLE
Flaky TF pipelines test on CircleCI

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#2781]
Environment: CircleCI

Test: `tests/test_pipelines.py::MultiColumnInputTestCase::test_tf_question_answering`

Traceback: https://circleci.com/gh/huggingface/transformers/15691?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Diff where I changed nothing relevant and the test started passing: https://github.com/huggingface/transformers/pull/2745/commits/a4edf2e878d23346f45715ac213f1f870ae8ec0c

Happy to look deeper if helpful!

**Comment by LysandreJik** [comment]
Indeed, this is a recurring error. I have not yet found the time to dive into it yet, we should do so shortly.
