### ISSUE TITLE
split_between_processes not splitting dataset between processes?

### ISSUE THREAD

**Issue by conceptofmind** [huggingface/transformers#27838]
### System Info

python 3.10

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
This does not work:
```python
dataset = load_dataset(
    "wikitext",
    "wikitext-2-v1",
    split="train",
)

print(len(dataset)) # 36718

# Assume 8 processes

with accelerator.split_between_processes(dataset) as data:
    print(len(data)) # 36718
    
   for out in pipe(
        KeyDataset(data, "text"), 
    ):
        continue
```
This works:
```python
dataset = load_dataset(
    "wikitext",
    "wikitext-2-v1",
    split="train",
)
print(len(dataset))

# Assume 8 processes

with accelerator.split_between_processes(dataset["text"]) as data:
    print(len(data))
```
### Expected behavior

I am unsure if this is intended behavior or not. A dataset consisting of the lists or input id tensors is split correctly. The dictionary provided from datasets will not be split.

Maybe this is more of a feature request?

Where the dataset could be split across all 8 processes to be used with the transformers feature extraction pipeline for inference.

**Comment by SunMarc** [comment]
Hi @conceptofmind this is related to accelerate, you should open an issue there. cc @muellerz

**Comment by conceptofmind** [comment]
> Hi @conceptofmind this is related to accelerate, you should open an issue there. cc @muellerz

Hi @SunMarc,

I was unsure whether this should be listed under accelerate, datasets, or transformers as it is in relation to all of them. And I do not know whether each independent factor would impact the splitting of the data. 

Transformers - pipelines
Datasets - KeyDataset
Accelerate - split_between_processes
etc etc

I can reopen it under accelerate.

Thank you,

Enrico

**Comment by BrianG13** [comment]
Hi, @conceptofmind 

Did you find a fix for this issue?
