### ISSUE TITLE
`ACT2FN` usage

### ISSUE THREAD

**Issue by ariG23498** [huggingface/transformers#27846]
In the code below we have a function to retrieve the correct activation function from the string.
https://github.com/huggingface/transformers/blob/235e5d4991e8a0984aa78db91087b49622c7740e/src/transformers/activations.py#L224-L228

I have noticed some models to use this function and others to directly import `ACT2FN` and use it as a dictionary.

IMO the function is redundant and importing the dictionary directly to scripts is enough. Curious to hear other opinions.

**Comment by ArthurZucker** [comment]
Hey! This seems to be related to backwards compatibility but we favor using the ACT2FN directly

**Comment by ariG23498** [comment]
Thanks for the prompt response. You can close this issue if you would like.
