### ISSUE TITLE
FuyuProcessor broken and causes infinite loop

### ISSUE THREAD

**Issue by grahamannett** [huggingface/transformers#27879]
https://github.com/huggingface/transformers/blob/75336c17945c6b1b5552dbf0236d25f869168aab/src/transformers/models/fuyu/processing_fuyu.py#L618

I am not sure exactly why/how it is but localized an issue where this segment of the processor goes into an infinite loop.  
Could be another segment but if I add a timeout to `post_process_box_coordinates` it seems to point to this.

**Comment by grahamannett** [comment]
if anyone runs into this, its because of the `if end != start` then `continue` will just keep going.  both these functions should be rewritten

**Comment by ArthurZucker** [comment]
cc @molbap for visibility, and @grahamannett if you can share a full reproducer would be helpful!

**Comment by grahamannett** [comment]
@ArthurZucker its hard to reproduce since the encoding throws an error if you try to create a similar input but here:

```python
processor = AutoProcessor.from_pretrained(adept/fuyu-8b)
x = torch.tensor([[71011,  71019,    1, 138997,  75694,  71374,  71118,  70004,  70050, 70013,  70004,  70013, 71119,  71122]])
output = processor.post_process_box_coordinates(x)
```

the tokens are supposed to resemble something like the model outputting 'here is the example <box>1, 2, 11, 12, 13</box>'  (or something similar think x in my example is 2's + 21).

I closed the issue tho so think we are all good 👍

**Comment by ArthurZucker** [comment]
Yep thanks I was able to reproduce. It's a bit of an edge case, but we could / should have a check for this. Do you want to open a PR for a fix? 🤗

**Comment by grahamannett** [comment]
@ArthurZucker Its not really an edge case as the generated output from the model can actually generate this sort of output and anecdotally seems like it becomes much more common if you further finetune the model on OCR related tasks/instructions. 

I do not think the PR I make will be merged so not sure if I should PR (hence closed this issue).

**Comment by ArthurZucker** [comment]
If this should be fix, we'll merge the PR that fixed it! We'll iterate together on the PR if you want! 
Opening this again and marking as good difficult issue

**Comment by grahamannett** [comment]
also @ArthurZucker is it Fuyu specific that processor.tokenizer.vocab doesn't match up with the processor/tokenizer encode? 

e.g.

```python
import transformers
processor = transformers.AutoProcessor.from_pretrained('adept/fuyu-8b')
processor('black', add_special_tokens=False, return_tensors='pt').input_ids[0,0].item()
# You are processing a text with no associated image. Make sure it is intended.
# 72803
processor.tokenizer.vocab['black']
# 73834
```

**Comment by grahamannett** [comment]
I think a lot of the current FuyuProcessor and FuyuImageProcessor (the image processor `preprocess` I believe has some big issues and unless I am told it is how they trained it, it will make fine-tuning with images not really work) are broken/not working correctly. 

I am just going to close this as it seems like the best way to fix this would be to use a different implementation.

**Comment by ArthurZucker** [comment]
It is how it was trained / the code that was shared by the authors 🤗

**Comment by grahamannett** [comment]
@ArthurZucker interesting.  There are a lot of parts in it that seem to to not work/be confusing to me e.g. how `get_sample_encoding` https://github.com/huggingface/transformers/blob/7e0ddf89f483f53107870cddabb2e1cc93069705/src/transformers/models/fuyu/processing_fuyu.py#L385 is done makes me think that because of https://github.com/huggingface/transformers/blob/7e0ddf89f483f53107870cddabb2e1cc93069705/src/transformers/models/fuyu/processing_fuyu.py#L246 the processor is not really able to be used for training? Or why `_tokenize_prompts_with_image_and_batch` adds `"|ENDOFTEXT|"` token to a text prompt even though it then is removed by just using the original prompt size?
