### ISSUE TITLE
Adding the same special token twice cause the additional_special_tokens to be set to an empty list inside tokenizer

### ISSUE THREAD

**Issue by dblakely** [huggingface/transformers#27888]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
- Python version: 3.9.17
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): NA
- Jax version: NA
- JaxLib version: NA
- Using GPU in script?: NA
- Using distributed or parallel set-up in script?: NA

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

The issue is that if you re-add a particular special token to the tokenizer, it'll make that token no longer an "additional_special_token" (the token will still exist in the vocabulary, but it'll cease to be treated as a special token).

Here's an example to reproduce the issue:
```python
from transformers import LlamaTokenizer

base_model = "meta-llama/Llama-2-7b-chat-hf"

# Create tokenizer and add an additional special token
tokenizer_1 = LlamaTokenizer.from_pretrained(base_model)
tokenizer_1.add_special_tokens({"additional_special_tokens": ["<tok>"]})
print(tokenizer_1.additional_special_tokens) # outputs `['<tok>']` as expected
tokenizer_1_checkpoint = "tokenizer_1"
tokenizer_1.save_pretrained(tokenizer_1_checkpoint)

# Load the above tokenizer and add the same special token a second time
tokenizer_2 = LlamaTokenizer.from_pretrained(tokenizer_1_checkpoint)
tokenizer_2.add_special_tokens({"additional_special_tokens": ["<tok>"]})
print(tokenizer_2.additional_special_tokens) # outputs `[]` which seems incorrect
```

This might seem contrived, but I have a training script where I add a special token by default to the tokenizer to ensure that it's there (I don't always know a priori that it's already been added). However, I found that if it is already there, the behavior of the tokenizer changes a bit. For example, the tokenizer will cease to remove the token when decoding automatically. After digging into it, I realized it's because the `additional_special_tokens` list was getting reset.

### Expected behavior

I'd expect adding the exact same special token a second time to have no effect whatsoever on the tokenizer.

**Comment by ArthurZucker** [comment]
Yep, I can reproduce and that's indeed a good catch. I have no idea why this is happening yet, opening a pr now 🤗

**Comment by ArthurZucker** [comment]
Sorry! Christmas delays 🤗 making sure this is fixed for next release
