### ISSUE TITLE
Trainer logging_first_step not evaluate on first step as it is documented

### ISSUE THREAD

**Issue by RmZeta2718** [huggingface/transformers#27902]
### System Info

`transformers` version: 4.35.2

### Who can help?

trainer: @muellerzr and @pacman100

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

document says that [logging_first_step](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.logging_first_step) will evaluate on the first global_step. But it only logs on the first step, not evaluate.

Related code: [link](https://github.com/huggingface/transformers/blob/633215ba58fe5114d8c8d32e415a04600e010701/src/transformers/trainer_callback.py#L435)

### Expected behavior

Either fix the document (remove "evaluate") or add evaluate feature to `logging_first_step` (I would prefer the latter)

Or if it's confusing for `logging_first_step` to evaluate, maybe we can add a `evaluate_first_step` argument.

**Comment by ArthurZucker** [comment]
Gently pinging @muellerzr and @pacman100

**Comment by ArthurZucker** [comment]
Marking as good first issue, doc can be updated 😉

**Comment by Sai-Suraj-27** [comment]
Hey, @pacman100. Can I work on this issue?

**Comment by ArthurZucker** [comment]
Sure feel free to open a PR to update the doc 😉
