### ISSUE TITLE
Terminate TextIteratorStreamer Before Done

### ISSUE THREAD

**Issue by fakerybakery** [huggingface/transformers#27927]
Hi,
Is there any way to terminate a TextIteratorStreamer before the text has finished generating? Related to [this](https://github.com/gradio-app/gradio/issues/6724).
Thank you!

**Comment by ArthurZucker** [comment]
Hey! I don't think this is possible through the TextIteratorStreamer but should be handled within gradio 🤗

**Comment by fakerybakery** [comment]
Ok, thanks for the suggestion! I'll close this issue then
