### ISSUE TITLE
tiny issue with distilbertconfig docs

### ISSUE THREAD

**Issue by waalge** [huggingface/transformers#2792]
# 🐛 Bug (barely) 

Discrepancy in variable names between docs and code: 
I presume [``intermediate_size``](https://github.com/huggingface/transformers/blob/520e7f211926e07b2059bc8e21b668db4372e4db/src/transformers/configuration_distilbert.py#L63) refers to [``hidden_dim``](https://github.com/huggingface/transformers/blob/520e7f211926e07b2059bc8e21b668db4372e4db/src/transformers/configuration_distilbert.py#L109)?

**Comment by LysandreJik** [comment]
You're correct! I updated it with 539f601. Thanks.
