### ISSUE TITLE
SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by KyrieCui** [huggingface/transformers#27923]
### System Info

transformers version: 4.35.0
Platform: Linux-4.18.0-477.27.1.el8_8.x86_64.x86_64-x86_64-with-glibc2.28
Python version: 3.9.16
Huggingface_hub version:0.16.4
Accelerate version: 0.21.0
Safetensors version: 0.3.1
PyTorch version (GPU?): 22.0.1+cu117 (True)

### Who can help?

 @ArthurZucker  @SunMarc   @younesbelkada

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction
```python
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
base_model = '/llm/llama2-2-70b-chat-hf'
model = AutoModelForCausalLM( base_model, load_in_8bit=True, device_map={"",0},use_safetensors=True)


in load_state_dict (checkpoint_file)
      462 """
      463 Reads a Pytorch checkpoint file, returning properly formatted errors if they arise.   
      464 """
      465 if checkpoint_file.endswith(".safetensors") and is_safetensors_available():
-->466     with safe_open(checkpoint_file,framework="pt") as f:
      467     metadata=f.metadate()
SafetensorError: Error while deserializing header: HeaderTooLarge    
```
### Expected behavior

Expected tao load the model successful

**Comment by ArthurZucker** [comment]
Hey, could you try to use the latest release of safetensors? 
Otherwise not sure I can help you with a checkpoint that is private !

**Comment by KyrieCui** [comment]
Hello, Sir. 
I met this error when loading the 6th checkpoint, so I re-downloaded the sixth safetensors file. But still the same error. Should I try to re- download all of the safetensors files?

**Comment by ArthurZucker** [comment]
If you download them from the hub anyway, you should just use from_pretrained, they will automatically be cache in your .cache and re-used accordingly.

**Comment by younesbelkada** [comment]
@KyrieCui this might be a storage issue as well, can you make sure you have enough Disk space on your device?

**Comment by KyrieCui** [comment]
thanks for all of your support! I fixed this issue by re-downloading all of the safetensors files.

**Comment by SofiaBianchi123** [comment]
i am having the same but i have manually merge the weights going  layer to layer then merged them cause i am applying the Fedml approach can anyone help me through this ?

**Comment by gpacix** [comment]
I got this error and the problem turned out to be that I didn't actually have the model file: I just had the `git lfs` smudge file, a pointer to the actual 1.4 GB file.  The fix was to go to where I'd checked out the model, do `git lfs install`, then `git lfs fetch`, then find the blob under `.git` that was the model. (I don't have experience with `git lfs`; there's probably a simpler way to get the real file.)

So double-check that the file under `models/` is actually a model.

A better error message that shows information about the file it failed to open would be helpful; anything that's under 200 bytes is incredibly unlikely to be a model.

**Comment by PorkyC** [comment]
@gpacix Great tip! Just to add on, if you install git lfs first, you can `git clone` the repo directly which should now include the model in its entirety rather than the pointers.
