### ISSUE TITLE
Whisper Large-v3 has problems with language detection

### ISSUE THREAD

**Issue by gau-nernst** [huggingface/transformers#27937]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.35
- Python version: 3.10.13
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.22.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sanchit-gandhi 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The audio file: https://drive.google.com/file/d/1EFWm7GpP79NUEmUO6rsLo444OugGRDHP/view?usp=sharing

```python
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="openai/whisper-large-v3")
output = pipe("sample.flac")
print(output)
```

v3 output: `{'text': ' Mari kita perlahan-lahan dengan penyelidikan baru dan baru yang telah dilakukan tahun lepas.'}`
v2 output: `{'text': " Let's go slow with this new and novel legalization passed last year."}`
tiny.en output: `{'text': " Let's go slow with this new and novel legalization past last year."}`

### Expected behavior

Output should be like v2 and the tiny.en model. I suspect there is something very wrong with language detection. I couldn't run v3 in the original repo (https://github.com/openai/whisper) due to OOM so I'm not sure if this is a problem with the v3 model itself or inference code in HF.

Seems related: https://github.com/huggingface/transformers/issues/27368#issuecomment-1835564217

**Comment by ArthurZucker** [comment]
Left it running as this is model specific rather than transformers bug IMO

**Comment by sanchit-gandhi** [comment]
Indeed - feel free to post on the OpenAI repo since it looks like a model regression from large-v2 -> v3: https://github.com/openai/whisper/discussions
