### ISSUE TITLE
The "source" button in docs points to 404

### ISSUE THREAD

**Issue by R-N** [huggingface/transformers#27941]
### System Info

Windows 11 64 bit 21h2
Google chrome latest

### Who can help?

@stevhliu 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Open [latest Trainer docs](https://huggingface.co/docs/transformers/main_classes/trainer)
2. Scroll to training_step
3. Click "source"

For me, it opens [this link](https://github.com/huggingface/transformers/blob/v4.36.0/src/transformers/trainer.py#L2697), which shows 404 for me.

### Expected behavior

It opens the source code, for example, source code of training_step.

**Comment by amyeroberts** [comment]
Hi @R-N, 

Thanks for raising this issue! The link should now work as v4.36 has been released.

**Comment by R-N** [comment]
> Hi @R-N,
> 
> Thanks for raising this issue! The link should now work as v4.36 has been released.

Confirmed, it works now. Thank you
