### ISSUE TITLE
KeyError: 'mistral'

### ISSUE THREAD

**Issue by brian-bould** [huggingface/transformers#27959]
### System Info

System Info
M2 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

running on pinokio. 
loading mistralai_Mixtral-8x7B-v0.1 model. 
 error: Traceback (most recent call last):
  File "/Users/bafsr/pinokio/api/oobabooga.pinokio.git/text-generation-webui/modules/ui_model_menu.py", line 209, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bafsr/pinokio/api/oobabooga.pinokio.git/text-generation-webui/modules/models.py", line 88, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bafsr/pinokio/api/oobabooga.pinokio.git/text-generation-webui/modules/models.py", line 146, in huggingface_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=params['trust_remote_code'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bafsr/pinokio/api/oobabooga.pinokio.git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1064, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bafsr/pinokio/api/oobabooga.pinokio.git/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 761, in __getitem__
    raise KeyError(key)
KeyError: 'mixtral'

### Expected behavior

run the model

**Comment by hi-sushanta** [comment]
Would it be possible for you to provide the complete code for your reference kindly?

**Comment by ehartford** [comment]
this means you aren't using latest transformers version

**Comment by amyeroberts** [comment]
Hi @brian-bould, thanks for raising this issue! 

As @ehartford mentions, this is most likely because the transformers version in your environment does not contain the recent mixtral release. Please make sure to follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and fill-out the running environment, including the transformers version. 

This error is unfortunately not super clear. @Rocketknight1 has just merge in a commit - #27976 - which should make the error messages when this occurs clearer.

**Comment by kapscudi** [comment]
I still got the same problem using the last transformers version

**Comment by Rocketknight1** [comment]
Hi @kapscudi, that's very unusual! The latest version of `transformers` should recognize the architecture correctly. Can you double-check the version using `import transformers` followed by `transformers.__version__` in `python`? It should be at least `4.36.2`.

**Comment by nehiridil** [comment]
I am also getting this error but in Google Colab. My transformers version is 4.36.2

**Comment by kdubey22** [comment]
I am currently facing the same error when I am loading --model TheBloke_Mistral-7B-OpenOrca-GPTQ --loader ExLlamav2_HF : The current version of `transformers` is 4.37.2 in my environment.

**Comment by ArthurZucker** [comment]
If you are using ooba-booga-web-ui then the issue should probably be opened on that repo 😉
