### ISSUE TITLE
An error occurred when saving the model

### ISSUE THREAD

**Issue by Decem-Y** [huggingface/transformers#27987]
https://github.com/huggingface/transformers/blob/14666775a296a76c88e1aa686a9547f393d322e2/src/transformers/trainer.py#L2349
When I update transformers == 4.36.0 for multi-GPU training to save the model, an error occurs prompting to save to "tmp-checkpoint-xx" instead of "checkpoint-xx".

**Comment by Decem-Y** [comment]
I find it https://github.com/huggingface/transformers/issues/27925#issuecomment-1851779674

**Comment by Decem-Y** [comment]
Please fix the bug caused by this merged PR https://github.com/huggingface/transformers/pull/27820.

**Comment by amyeroberts** [comment]
cc @pacman100 @muellerzr
