### ISSUE TITLE
4.36 transformers got wrong _save_checkpoint  with deepspeed. work with previous versions

### ISSUE THREAD

**Issue by tszdanger** [huggingface/transformers#28027]
### System Info

transformers: 4.36.0
python: 3.10
deepspeed:  0.9.4                   

Traceback (most recent call last):
  File "/home/xxxx/xxxx/src/./xxxx.py", line 363, in <module>
    main(args)
  File "/home/xxxx/xxxx/src/./xxxx.py", line 352, in main
    run_training(args, train_dataset, eval_dataset, len(tokenizer))
  File "/home/xxxx/xxxx/src/./xxxx.py", line 339, in run_training
    trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/transformers/trainer.py", line 1914, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/transformers/trainer.py", line 2274, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/transformers/trainer.py", line 2383, in _save_checkpoint
    os.rename(staging_output_dir, output_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxxx/tmp-checkpoint-100' -> '/home/xxxx/checkpoint-100'

**When Using deepspeed with Trainer, 4.36 just have the wrong code, see below:**

https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L2352C13-L2352C83

You may need a PR for this.

### Who can help?

@muellerzr @pacman100

Like below. 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

quite simple, just with the simplest code example.

trainer = Trainer(
      model=model,
      args=training_args,
      train_dataset=train_data,
      eval_dataset=val_data,
  )
  print("Training...")
  trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)

### Expected behavior

no error would be fine

**Comment by heraclex12** [comment]
See this PR: https://github.com/huggingface/transformers/pull/28009

**Comment by U-rara** [comment]
I observed the exact same phenomenon. In a multi-GPU environment, this error is always thrown by the process with the highest rank.

**Comment by tszdanger** [comment]
Glad to see this issue has been fixed :)

**Comment by jiezhangGt** [comment]
> See this PR: #28009 It can help overcome this issue.

it not worked!

**Comment by ArthurZucker** [comment]
@jiezhangGt could you provide a reproduer / make sure you are using the latest version of main?
