### ISSUE TITLE
SeamlessM4T: `test_retain_grad_hidden_states_attentions` is flaky

### ISSUE THREAD

**Issue by gante** [huggingface/transformers#28036]
See the related PR which added the `is_flaky` decorator: https://github.com/huggingface/transformers/pull/28035

cc @ylacombe, to explore in case you have spare bandwidth :)

**Comment by amyeroberts** [comment]
@ylacombe Re-opening as this isn't resolved by #28060 (it just makes sure our CI doesn't break)

**Comment by ylacombe** [comment]
Alright, copying the reasons for flakiness from #28060 for trackability then!

> After investigating the reasons for the test_retain_grad_hidden_states_attentions flaky failure, I realized the speech encoder attentions can be None with a non-zero probability when training=True.

**Comment by ylacombe** [comment]
To circle back on this, let's figure out how to correctly fix this!

The feature surely works but the randomness of the skipping makes so that the first attention layer is sometimes skipped.

What I could do is to fix a seed with which the first layer is never skipped, WDYT @amyeroberts ?

**Comment by amyeroberts** [comment]
Seed setting seems like a good idea!
