### ISSUE TITLE
Cannot specify config and attn_implementation simultaneously

### ISSUE THREAD

**Issue by hiyouga** [huggingface/transformers#28038]
### System Info

- `transformers` version: 4.36.1
- Platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.35
- Python version: 3.10.10
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.0
- Accelerate version: 0.23.0
- Accelerate config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: bf16
	- use_cpu: False
	- debug: False
	- num_processes: 8
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: all
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoConfig, AutoModelForCausalLM
config = AutoConfig.from_pretrained("meta-llama/Llama-2-7b-hf")
model = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Llama-2-7b-hf",
    config=config,
    device_map="auto",
    torch_dtype="auto",
    low_cpu_mem_usage=True,
    attn_implementation="flash_attention_2"
)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "lib/python3.10/site-packages/transformers/modeling_utils.py", line 3450, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: LlamaForCausalLM.__init__() got an unexpected keyword argument 'attn_implementation'
```

### Expected behavior

What should I do if I want to specify both of them?

Besides, it cannot enable FA2 by modifying the model config with `config.attn_implementation=flash_attention_2`.

However, it works if I pass a deprecated parameter `use_flash_attention_2` when the `config` is also specified.

**Comment by younesbelkada** [comment]
hi @hiyouga 
Thanks a lot for the issue! 
I think that you cannot pass both the config and `attn_implementation` , can you elaborate a bit on why you would like to pass the config as well as `attn_implementation` into `from_pretrained`? The canonical way to load a FA2 model is:

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, LlamaForCausalLM

model_id = "tiiuae/falcon-7b"
tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoModelForCausalLM.from_pretrained(
    model_id, 
    torch_dtype=torch.bfloat16, 
    attn_implementation="flash_attention_2",
)
```

It is also not recommended to enable FA2 through the config directly. However you can enable FA2 by passing `attn_implementation="flash_attention_2"` in `from_config` methd: https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L1235

**Comment by hiyouga** [comment]
Thanks for replying!
I wish to modify the model config before loading the pre-trained models, such as setting `rope_scaling` and `torch_dtype`.
I wonder why I could pass both `config` and `use_flash_attention_2` to `from_pretrained`

**Comment by xingniandage** [comment]
'BertModel' object has no attribute 'attn_implementation'

When converting the PTH model of BERT to the onnx form
-> 41             outputs = self.bert(qCap,attention_mask=qCap_mask)
     42                 # 获取BERT模型最后一层的隐藏状态
     43         last_hidden_states = outputs.last_hidden_state

/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    885 
    886         if torch._C._get_tracing_state():
--> 887             result = self._slow_forward(*input, **kwargs)
    888         else:
    889             result = self.forward(*input, **kwargs)

/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    858                 recording_scopes = False
    859         try:
--> 860             result = self.forward(*input, **kwargs)
    861         finally:
    862             if recording_scopes:

/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
   1083 
   1084         use_sdpa_attention_masks = (
-> 1085             self.attn_implementation == "sdpa"
   1086             and self.position_embedding_type == "absolute"
   1087             and head_mask is None

/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
    945             if name in modules:
    946                 return modules[name]
--> 947         raise AttributeError("'{}' object has no attribute '{}'".format(
    948             type(self).__name__, name))
    949 

AttributeError: 'BertModel' object has no attribute 'attn_implementation'

**Comment by amyeroberts** [comment]
Hi @xingniandage Could you open a new issue, including information about the running env and a minimal reproducer?

**Comment by xingniandage** [comment]
> Hi @xingniandage Could you open a new issue, including information about the running env and a minimal reproducer?
thanks for your reply
I don't know why the error is reported
I changed the version of torch and torchvision and the error disappears
