### ISSUE TITLE
ValueError: Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes. You passed torch.float32, this might lead to unexpected behaviour.

### ISSUE THREAD

**Issue by dakinggg** [huggingface/transformers#28052]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.36.0
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.3.1
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

running `llamafromcfg = transformers.AutoModelForCausalLM.from_config(llamacfg, use_flash_attention_2=True)` after `llamacfg = transformers.AutoConfig.from_pretrained('meta-llama/Llama-2-7b-hf')` results in `ValueError: Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes. You passed torch.float32, this might lead to unexpected behaviour.`.

### Expected behavior

I understand that flash attention requires fp16/bf16 for _computation_, but I don't believe I should be prevented from instantiating the model in fp32. I will use automatic mixed precision later for computation.

Please let me know what I'm missing/what the intended usage is. Thank you!

**Comment by dakinggg** [comment]
Also I thought `torch_dtype` wasn't even used when its in the config, maybe that has changed though.

**Comment by dakinggg** [comment]
Also even specifying `torch_dtype` results in a warnings `In [21]: transformers.AutoModelForCausalLM.from_config(llamacfg, torch_dtype=torch.bfloat16, use_flash_attention_2=True)
You are attempting to use Flash Attention 2.0 without specifying a torch dtype. This might lead to unexpected behaviour`. I feel like I'm missing something fundamental about how this arg works.

**Comment by dakinggg** [comment]
I also tried setting `._attn_implemention` myself as a workaround, but it doesn't seem to respect that.

**Comment by ArthurZucker** [comment]
Thanks a lot for this and other reports, we’ll fix it asap cc @fxmarty as well

**Comment by dakinggg** [comment]
While you're there, it'd be good to revisit all of the hard checks in there and make sure they are truly necessary. For anyone else who ends up here, you can work around it via
```
            def _autoset_attn_implementation_monkeypatch(
                    cls, config, *args, **kwargs):  # type: ignore
                config._attn_implementation = requested_attention_implementation
                return config

            PreTrainedModel._autoset_attn_implementation = classmethod(
                _autoset_attn_implementation_monkeypatch)
                ```

**Comment by hijkzzz** [comment]
same issue

**Comment by huayang1988** [comment]
![image](https://github.com/huggingface/transformers/assets/8974032/8b4224d9-3d84-4b61-b8e8-0571738f1e33)
in modeling_utils.py  
  # Save config and origin of the pretrained weights if given in model
        config = self._autoset_attn_implementation(
            config, torch_dtype=torch.get_default_dtype(), check_device_map=False
        )
        
        the torch_dtype need delete 
  # Save config and origin of the pretrained weights if given in model
        config = self._autoset_attn_implementation(
            config, check_device_map=False
        )
it is configed not get

**Comment by zhang001122** [comment]
in  src/modeling_utils.py
      ```
  config = self._autoset_attn_implementation(
            config, torch_dtype=torch.get_default_dtype(), check_device_map=False
        )
```
change to 

```
  config = self._autoset_attn_implementation(
            config, check_device_map=False
        )
```

**Comment by Strive-for-excellence** [comment]
> in src/modeling_utils.py ```python config = self._autoset_attn_implementation( config, torch_dtype=torch.get_default_dtype(), check_device_map=False )
> 
> change to
> 
> config = self._autoset_attn_implementation( config, check_device_map=False )

I agree with you. when I run 

transformers==4.36.2
```python
import os
import torch
# import hf_transfer
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig

model_id = "mistralai/Mixtral-8x7B-Instruct-v0.1"
config = AutoConfig.from_pretrained(model_id)
config._attn_implementation = "flash_attention_2"
config.use_cache = False
# model_id = 'mistralai/Mistral-7B-v0.1'
print(config)
# Load model (this will now default to CPU due to the environment setting)
model = AutoModelForCausalLM.from_pretrained(model_id, config=config)
```
there was a error

```shell
  File "train.py", line 273, in <module>
    train()
  File "train.py", line 137, in train
    model = AutoModelForCausalLM.from_pretrained(data_args.model_cfg, config=config, trust_remote_code=True)
  File "py310/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "py310/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3462, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "py310/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 1140, in __init__
    super().__init__(config)
  File "py310/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1190, in __init__
    config = self._autoset_attn_implementation(
  File "py310/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1302, in _autoset_attn_implementation
    cls._check_and_enable_flash_attn_2(
  File "*/site-packages/transformers/modeling_utils.py", line 1422, in _check_and_enable_flash_attn_2
    raise ValueError(
ValueError: Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes. You passed torch.float32, this might lead to unexpected behaviour.
```
because

```python
class PreTrainedModel(nn.Module, ModuleUtilsMixin, GenerationMixin, PushToHubMixin, PeftAdapterMixin):
***
    def __init__(self, config: PretrainedConfig, *inputs, **kwargs):
        super().__init__()
        if not isinstance(config, PretrainedConfig):
            raise ValueError(
                f"Parameter config in `{self.__class__.__name__}(config)` should be an instance of class "
                "`PretrainedConfig`. To create a model from a pretrained model use "
                f"`model = {self.__class__.__name__}.from_pretrained(PRETRAINED_MODEL_NAME)`"
            )
        # Save config and origin of the pretrained weights if given in model
        config = self._autoset_attn_implementation(
            config, torch_dtype=torch.get_default_dtype(), check_device_map=False
        )
 ```
 I think it would be better
 ```python
         config = self._autoset_attn_implementation(
        config, torch_dtype=config.torch_dtype, check_device_map=False
    )
 ```

**Comment by taoshen58** [comment]
Same issue, but fig out a simple solution to bypass the check:

```
default_dtype = torch.get_default_dtype()
torch.set_default_dtype(torch.bfloat16)
model = transformers.AutoModelForCausalLM.from_pretrained(
  model_path,
  attn_implementation="flash_attention_2",
  config=config,
)
torch.set_default_dtype(default_dtype)
```

**Comment by Strive-for-excellence** [comment]
```
default_dtype = torch.get_default_dtype()
torch.set_default_dtype(torch.bfloat16)
model = transformers.AutoModelForCausalLM.from_pretrained(
  model_path,
  attn_implementation="flash_attention_2",
  config=config,
  torch_dtype=torch.bfloat16,
)
```

**Comment by Strive-for-excellence** [comment]
model = transformers.AutoModelForCausalLM.from_pretrained(
  model_path,
  attn_implementation="flash_attention_2",
  config=config,
  torch_dtype=torch.bfloat16,
)

**Comment by Strive-for-excellence** [comment]
```

model = transformers.AutoModelForCausalLM.from_pretrained(
  model_path,
  attn_implementation="flash_attention_2",
  config=config,
  torch_dtype=torch.bfloat16
)
```

**Comment by alita-moore** [comment]
```
default_dtype = torch.get_default_dtype()
torch.set_default_dtype(torch.bfloat16)
model = transformers.AutoModelForCausalLM.from_pretrained(
  model_path,
  attn_implementation="flash_attention_2",
  config=config,
)
torch.set_default_dtype(default_dtype)
model.to(torch.float32)
```

**Comment by ArthurZucker** [comment]
This is automatically do if you set `torch_dtype = torch.bfloat16"`

**Comment by alita-moore** [comment]
in the MBartConfig?

**Comment by ArthurZucker** [comment]
When you call `from_pretrained`

**Comment by alita-moore** [comment]
but I don't want to call `from_pretrained`

**Comment by ArthurZucker** [comment]
Ah right, then yes 👍🏻

**Comment by DrChrisLevy** [comment]
I don't really get it.
This still spits out the warning

```
You are attempting to use Flash Attention 2.0 without specifying a torch dtype. This might lead to unexpected behaviour
```

```
model = Qwen2VLForConditionalGeneration.from_pretrained(
        "Qwen/Qwen2-VL-7B-Instruct",
        torch_dtype=torch.bfloat16,
        attn_implementation="flash_attention_2",
        device_map="auto",
    )
```

**Comment by linchen111** [comment]
> torch.set_default_dtype(default_dtype)

+1

**Comment by ArthurZucker** [comment]
@zucchini-nlp is working on this in #32238

**Comment by netique** [comment]
I still get that in transformers-4.54.0.dev0 for ModernBert, but only during the first run.

- `transformers` version: 4.54.0.dev0
- Platform: Linux-6.1.123+-x86_64-with-glibc2.35
- Python version: 3.11.13
- Huggingface_hub version: 0.33.1
- Safetensors version: 0.5.3
- Accelerate version: 1.8.1
- Accelerate config: 	not found
- DeepSpeed version: not installed
- PyTorch version (accelerator?): 2.7.1+cu126 (CUDA)
- Tensorflow version (GPU?): 2.18.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.10.6 (gpu)
- Jax version: 0.5.2
- JaxLib version: 0.5.1
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA A100-SXM4-40GB
