### ISSUE TITLE
Mixtral: Reduce and Increase Expert Models

### ISSUE THREAD

**Issue by ryan-minato** [huggingface/transformers#28058]
### Feature request

Add methods to MixtralSparseMoeBlock, MixtralDecoderLayer, and MixtralModel for reducing (and enlarging) the number of expert models.

Implement a mechanism to decrease the number of expert models by removing corresponding rows in gate weights. This should enable the removal expert models by id.

https://github.com/huggingface/transformers/blob/1a585c1222a56bcaecc070966d558d4a9d862e83/src/transformers/models/mixtral/modeling_mixtral.py#L688-L710

### Motivation

This will allow scaling down or up the model size from a pre-trained model while preserving existing weights, eliminating the need to retrain from scratch.

### Your contribution

I am willing to contribute a pr, but need a few time. 

I would like to know if such a PR is likely to be accepted, before I start working on it.

**Comment by amyeroberts** [comment]
cc @younesbelkada @ArthurZucker

**Comment by younesbelkada** [comment]
Hi @minato-ellie 
This could makes sense yes, do you know if it has been empirically proven that decreasing the number of experts do not lead in performance degradation? I also wonder if this does not make the HF mixtral implementation "too modulable" which goes against transformers philosophy

**Comment by minato-ellie** [comment]
@younesbelkada 

I created #28092 .

I tried it and it seems that I can pass it forward using the new model, but I can't output the results. 
I didn't try to finetune it because I couldn't use GPU over the weekend.

Also, someone have created mixtral by merging 4 mistral models as experts and it seems to work well.
https://huggingface.co/chargoddard/mixtralnt-4x7b-test

**Comment by minato-ellie** [comment]
I'll try to finetune it when I can use gpu, and let you know the results.

**Comment by younesbelkada** [comment]
Ok perfect, let us know how it goes!
