### ISSUE TITLE
No module named 'clip'

### ISSUE THREAD

**Issue by jzssz** [huggingface/transformers#28067]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.17
- Python version: 3.8.18
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 1.13.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in> yes
- Using distributed or parallel set-up in script?: <fill in> yes

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

"src/transformers/models/clip/convert_clip_original_pytorch_to_hf.py"
"from clip import load"
bug：**No module named 'clip'.** 

so I use “pip install clip” to install clip, but:
another bug: **cannot import name 'load' from 'clip'**

so I'm wondering if the way I installed the clip package is wrong? I'm hoping to find the correct way to install this package so I can run this code "src/transformers/models/clip/convert_clip_original_pytorch_to_hf.py"

### Expected behavior

I'm hoping to find the correct way to install “clip” this package so I can run this code "src/transformers/models/clip/convert_clip_original_pytorch_to_hf.py"

**Comment by amyeroberts** [comment]
The instructions for installing the package `clip` can be found on the original implementation's github README: https://github.com/openai/CLIP
