### ISSUE TITLE
The model's name is saved as model.safetensors while the logger reported its name as pytorch_model.bin, which is quite weird.

### ISSUE THREAD

**Issue by izyForever** [huggingface/transformers#28076]
### System Info

- `transformers` version: 4.36.1
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.11.2
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.0
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

![9ZZRLD04)PX107 _N7IV5 X](https://github.com/huggingface/transformers/assets/43177954/f2a59614-553a-4414-9fb6-5c6e5c6f28b9)

![_3G(V3TRGTN3`T)%_{5(`{3](https://github.com/huggingface/transformers/assets/43177954/c335058b-f85f-49b3-b958-9801e1201750)

When I was training my model, I finded there was not pytorch_model.bin but model.safetensors,
I think it's misguided in some ways.

The logger is below:

![1JFOSY7B06_A8E_6QHIVDMQ](https://github.com/huggingface/transformers/assets/43177954/03ce1bd6-ef80-496d-945b-f32889cf56fa)
![5}Y_LT} Y7)4T YE~ATH@SR](https://github.com/huggingface/transformers/assets/43177954/4990eb2e-8a7a-4fce-9d75-bf711695a4e5)
![H{ XW2%LB~P_COT`} 0D{B7](https://github.com/huggingface/transformers/assets/43177954/f19dbe5e-a876-48e1-9b9f-875157455051)

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. use [the p-tuning script](https://github.com/THUDM/ChatGLM2-6B/blob/main/ptuning/main.py) to fine tuning chatglm2-6b
2. In Windows 10, I use bat to run the script, as below, which works well but inconsistent logger.

```
set PRE_SEQ_LEN=128
set LR=2e-2

python main.py ^
    --do_train ^
    --train_file AdvertiseGen/train.json ^
    --validation_file AdvertiseGen/dev.json ^
    --preprocessing_num_workers 10 ^
    --prompt_column content ^
    --response_column summary ^
    --overwrite_cache ^
    --model_name_or_path  E://ChatGLM2-6B ^
    --output_dir output/adgen-chatglm2-6b-pt-%PRE_SEQ_LEN%-%LR% ^
    --overwrite_output_dir ^
    --max_source_length 64 ^
    --max_target_length 128 ^
    --per_device_train_batch_size 1 ^
    --per_device_eval_batch_size 1 ^
    --gradient_accumulation_steps 16 ^
    --predict_with_generate ^
    --max_steps 3 ^
    --logging_steps 1 ^
    --save_steps 1 ^
    --learning_rate %LR% ^
    --pre_seq_len %PRE_SEQ_LEN% ^
    --quantization_bit 4
```

### Expected behavior

I think it will be better if the file name is the same as the logger shows.

**Comment by izyForever** [comment]
The function parameter is safe_serialization: bool = True, but the logger file name is a constant which is used for the situation of safe_serialization: bool = False and it causes ambiguousness.

**Comment by amyeroberts** [comment]
Hi @izyForever, thanks for raising this issue! 

Indeed, it seems this logging line wasn't updated to reflect the default safe serialization behaviour that now happens. Would you like to open a PR to update the logger message? This way you get the github contribution for spotting this

**Comment by izyForever** [comment]
> Hi @izyForever, thanks for raising this issue!
> 
> Indeed, it seems this logging line wasn't updated to reflect the default safe serialization behaviour that now happens. Would you like to open a PR to update the logger message? This way you get the github contribution for spotting this

Sure, I will fix this.

**Comment by runningabcd** [comment]
> 你好@izyForever，感谢您提出这个问题！
> 
> 事实上，这条日志记录行似乎没有更新以反映现在发生的默认安全序列化行为。您想打开 PR 来更新记录器消息吗？这样您就可以发现这个问题的 github 贡献



> 你好@izyForever，感谢您提出这个问题！
> 
> 事实上，这条日志记录行似乎没有更新以反映现在发生的默认安全序列化行为。您想打开 PR 来更新记录器消息吗？这样您就可以发现这个问题的 github 贡献

Wow,you are si cute! Follow you!
