### ISSUE TITLE
T5Tokenizer: Different decoding behaviour depending on the tokenizer method used

### ISSUE THREAD

**Issue by sorenmulli** [huggingface/transformers#28105]
### System Info

- `transformers` version: 4.36.1
- Platform: Linux-6.1.55-1-lts-x86_64-with-glibc2.38
- Python version: 3.11.5
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.1

- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```py
from transformers import T5TokenizerFast
tokenizer = T5TokenizerFast.from_pretrained("google/flan-t5-base")
tokens = ['▁', '?', '▁', '?']

ids = tokenizer.convert_tokens_to_ids(tokens)
# [3, 58, 3, 58]

tokenizer.decode(ids)
# '??'
tokenizer.convert_tokens_to_string(tokens)
# '? ?'
tokenizer.decoder.decode(tokens)
# '? ?'
```

### Expected behavior

I expected these two methods to yield same result: `'? ?'`.

I do not understand the result `'??'` and failed myself to find the logic where this space is removed; I guess it must be in `tokenizers`.

In advance, thank you for all help :heart: :hugs:

**Comment by sorenmulli** [comment]
Also get same results with other `t5` models like `t5-base`; haven't tried other tokenizers though.

When using a non-fast tokenizer, I also get the same result. Here I am using `tokenizer.sp_model`instead of `tokenizer.decoder` in the last step.

**Comment by sorenmulli** [comment]
There must be a punctuated-based post-processing which I fail to see (and might be expected behaviour), as this also happens with tokens `.`. `.`, `!` but not `a`

**Comment by ArthurZucker** [comment]
Hey! You should checkout the [clean_up_tokenization_spaces](https://huggingface.co/docs/transformers/internal/tokenization_utils#transformers.PreTrainedTokenizerBase.clean_up_tokenization_spaces) attribute:
```python 
tokenizer.decode(ids, clean_up_tokenization_spaces=False)
```
is what you are looking for

**Comment by sorenmulli** [comment]
Thanks! Then this is intended default behaviour :)

I think it then makes sense for me to disable this cleaning for my T5 model to get same result as sentencepiece but I cannot completely figure out if I want this cleanup in some other cases :thinking:

**Comment by ArthurZucker** [comment]
Yep I have no clue either as to why this was always done but it's recurring issue 😅
