### ISSUE TITLE
How can I finetune the BERTModel on my own corpus?

### ISSUE THREAD

**Issue by Reply1999** [huggingface/transformers#2812]
# ❓ Questions & Help

## Details

Thanks for your code!

I want to fine-tune the BERT model on my own corpus which has a smaller vocabulary than the default size of 30522, and my final goal is to obtain a fine-tuned and personalized BERT model which can provide proper word embedding for future top tasks. In short, I need to fine-tune the BERTModel for providing word embedding based on my own corpus.

How can I build a new vocabulary and then fetch the embeddings from the provided pre-trained model, e.g., bert-base-uncased, and then fine-tune the model on my own corpus?

Have you provided functions for building vocabulary and further fine-tuning?

**Comment by sshleifer** [comment]
Take a look at the `resize_embeddings` function and  `examples/run_language_modeling.py`.

**Comment by Reply1999** [comment]
sorry, where is the resize_embeddings function?

**Comment by sshleifer** [comment]
My bad, it's a method on `PretrainedModel` called `resize_token_embeddings`. There is a call in `run_language_modeling.py.
