### ISSUE TITLE
Add Tortoise TTS to HF Pipeline

### ISSUE THREAD

**Issue by fakerybakery** [huggingface/transformers#28120]
### Feature request

Hi,
Might it be possible to add [Tortoise TTS](https://github.com/neonbjb/tortoise-tts) to the `text-to-speech` pipeline?

### Motivation

Tortoise TTS is currently the highest-quality permissively licensed text-to-speech library available.

### Your contribution

Tortoise TTS is already pip-ified so it shouldn't be too hard to add.

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi @ylacombe

**Comment by fakerybakery** [comment]
I saw [this issue](https://github.com/huggingface/diffusers/issues/3891), however personally I think it would be great to have a unified way to run TTS models. Transformer's `pipeline` has the most support right now, and pipelines in Diffusers are harder to use.

**Comment by sanchit-gandhi** [comment]
Hey @fakerybakery - Tortoise TTS is a pipeline composed of two transformer-based models and one diffusion one. `diffusers` pipelines are designed to work with a mix of transformer/diffusion models, whereas `transformers` pipelines are designed to work with single transformer-based model. Therefore, the pipeline is a better fit for `diffusers`, for which there is an on-going PR to add it: https://github.com/huggingface/diffusers/pull/4106

Note that the pipeline will be still very easy to work with in `diffusers`, emulating a similar API to AudioLDM: https://huggingface.co/cvssp/audioldm-s-full-v2#text-to-audio
