### ISSUE TITLE
[Trainer.train] learning rate logging inconsistency: learning rate for the future step is logged

### ISSUE THREAD

**Issue by HanGuo97** [huggingface/transformers#28124]
### System Info

NA

### Who can help?

@muellerzr and @pacman100

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

[This](https://github.com/huggingface/transformers/blob/c52b515e948fc12ff58ad773a0385860d0162f61/src/transformers/trainer.py#L1913) line of code steps forward the LR scheduler, before `_maybe_log_save_evaluate` is called. This means the learning rate logged represents the learning in the upcoming iteration.

For most of the use cases, the differences between them is small. However, in certain cases, this caused confusion.

### Expected behavior

The learning rate for the current iteration is logged.

**Comment by amyeroberts** [comment]
Gentle ping @muellerzr @pacman100

**Comment by amyeroberts** [comment]
Gentle ping @muellerzr @pacman100

**Comment by amyeroberts** [comment]
Another ping @muellerzr

**Comment by amyeroberts** [comment]
cc @muellerzr @SunMarc

**Comment by muhd360** [comment]
take .

**Comment by muhd360** [comment]
@ArthurZucker pls assign this issue 2 me

**Comment by muhd360** [comment]
@SunMarc pls check this out

**Comment by phoenix0706** [comment]
@ArthurZucker Please assign this issue to me

**Comment by muhd360** [comment]
IM still working on it @phoenix0706 pls refer 2 the comment thread

**Comment by ArthurZucker** [comment]
Hey! Thanks both, we don't assign issues, so first PR is what we look at ! 🤗

**Comment by SunMarc** [comment]
Fixed here https://github.com/huggingface/transformers/pull/36973
