### ISSUE TITLE
`from_pretrained` is extremely slow when deepspeed zero3 is enabled

### ISSUE THREAD

**Issue by Jingru** [huggingface/transformers#28139]
### System Info

pytorch: 2.0.1+cu118
transformers: 4.33.3
deepspeed: 0.12.5

### Who can help?

@ArthurZucker  @younesbelkada @pac

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Run command `torchrun --nnodes 1 --nproc-per-node 8 --rdzv-endpoint=localhost:35000 test.py`

And my script `test.py` as follows:

```
import deepspeed

from transformers.deepspeed import HfDeepSpeedConfig
from transformers import AutoModelForCausalLM


deepspeed.init_distributed()

ds_config = {
    "train_batch_size": 32,
    "train_micro_batch_size_per_gpu": 4,
    "steps_per_print": 10,
    "zero_optimization": {
        "stage": 3,
        "offload_param": {"device": "cpu"},
        "offload_optimizer": {"device": "cpu"},
        "stage3_param_persistence_threshold": 10000.0,
        "stage3_max_live_parameters": 30000000.0,
        "stage3_prefetch_bucket_size": 30000000.0,
        "memory_efficient_linear": False,
    },
    "fp16": {"enabled": True, "loss_scale_window": 100},
    "gradient_clipping": 1.0,
    "prescale_gradients": False,
    "wall_clock_breakdown": False,
    "hybrid_engine": {
        "enabled": True,
        "max_out_tokens": 512,
        "inference_tp_size": 1,
        "release_inference_cache": False,
        "pin_parameters": True,
        "tp_gather_partition_size": 8,
    },
}

dschf = HfDeepSpeedConfig(ds_config)

model = AutoModelForCausalLM.from_pretrained(
    "../llama_actor", from_tf=False, trust_remote_code=False
)

```
In addition, the pretrained model is saved by `transformers==4.31.0`.

2. This command hangs for over 1800s, and encountered nccl timeout error.

### Expected behavior

Model is loaded in a few minutes and this command should not hang.

**Comment by amyeroberts** [comment]
cc @pacman100

**Comment by Jingru** [comment]
I did some research, and found that all the ranks except rank0 tried to load model weight tensors to `meta device`.  It looks like this behavior is extremely slow. 
https://github.com/huggingface/transformers/blob/bffac926ca6bc6c965a92bfbfd00c567a2c0fb90/src/transformers/modeling_utils.py#L479

**Comment by Jingru** [comment]
My model directory holds a finetuned model rather than the original llama2 model. Does this mean that there is something abnormal with my finetuned model?

I tried to override `map_location` mentioned above to 'cpu' for all the ranks, and this script could load my model in 300s. But the results of `model.generate` are nonsense.

Besides, I tried to downgrade transformers to 4.31.0 and deepspeed to 0.11.1, and everything is fine. Model can be loaded in a few minutes and generated texts are as expected.

**Comment by Jingru** [comment]
Weird.

I can only load "openlm-research/open_llama_7b_v2" normally at the first time (downloading is required), and this command hangs at the second time (from cache).

However, "openlm-research/open_llama_3b_v2" could be loaded normally no matter how many times I tried.

**Comment by Chandler-Bing** [comment]
hi @Jingru, same proble, did u solve this?

**Comment by Jingru** [comment]
> hi @Jingru, same proble, did u solve this?

I load the old checkpoint without deepspeed and `save_pretrained` again. The new checkpoint can be loaded with zero3 normally.
