### ISSUE TITLE
During the training process, what happens if tf32 and bf16 are enabled at the same time?

### ISSUE THREAD

**Issue by Bonytu** [huggingface/transformers#28158]
### System Info

transformers 4.34.1

### Who can help?

@muellerzr  @pacman100 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. use trainer and set --tf32 True and --bf16 True

### Expected behavior

Hi, when I was training llama2-13b, I set both --tf32 True and --bf16 True at the same time. I'm confused because the trainer worked normally when both of these parameters were enabled. During this process, which parts used tf32 and which parts used bf16? How exactly does it work when both are turned on at the same time?

Also I found many tutorial set these two params at the same time. [(https://www.philschmid.de/instruction-tune-llama-2)](tutorial)

**Comment by Bonytu** [comment]
Hi，could you please help me to solve this issue? @muellerzr  @pacman100 
Thanks！

**Comment by tdolega** [comment]
By setting bf16, the model weights are saved in bf16, but calculations such as gradients are still always done in full 32-bit precision. By additionally setting tf32, you speed up that very calculations at the expense of precision, but since ultimately those weights are saved as bf16 anyway, it has no effect on accuracy.

**Comment by Paulmzr** [comment]
> By setting bf16, the model weights are saved in bf16, but gradients (computed in half-precision but converted to full-precision for the update) and optimizations (optimizer states) are still done in full 32-bit precision. By additionally setting tf32, you speed up that very calculations at the expense of precision, but since ultimately those weights are saved as bf16 anyway, it _probably_ has no effect on accuracy.
@tdolega  Assuming you are using Trainer API, you will get model weights trained in mixed precision but saved in FP32 by default if setting --bf16.
