### ISSUE TITLE
What is the minimum video card with large memory required to run the mixtral-8x7b model

### ISSUE THREAD

**Issue by zysNLP** [huggingface/transformers#28155]
I mean the model that just came out：mistralai/Mixtral-8x7B-Instruct-v0.1，looks like a lot of parameter files，what is the minimum nvidia graphics card video memory required?

**Comment by amyeroberts** [comment]
Hi @zysNLP, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
