### ISSUE TITLE
Annotations not being transformed after padding on Deformable DETR preprocessing

### ISSUE THREAD

**Issue by Tengoles** [huggingface/transformers#28153]
### System Info

@amyeroberts 

Maybe I'm missing something but it seems like the annotations are not being transformed accordingly after applying pad to a batch of images:
https://github.com/huggingface/transformers/blob/v4.36.1/src/transformers/models/deformable_detr/image_processing_deformable_detr.py#L1330

Is this dealt with further down the train pipeline? when I render the output annotations of that method (encoded_inputs["labels"]) they are incorrect for the images of the batch that required to be padded.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AutoImageProcessor

processor = AutoImageProcessor.from_pretrained("SenseTime/deformable-detr")

encoding = processor(images=imgs, annotations=targets, return_tensors="pt", 
                                  do_pad=True)

### Expected behavior

Annotations may require transformation just like they are transformed accordingly when applying resize and rescale on previous lines within the same method.

**Comment by amyeroberts** [comment]
Hi @Tengoles, thanks for raising this issue! 

Indeed, there's an issue with the transformations that are happening in deformable detr and other detr models if `do_pad=True` as the box coordinates aren't rescaled to account for the new image height / width cc @NielsRogge. 

I'll open a PR to update these.
