### ISSUE TITLE
Error while importing the transformers 

### ISSUE THREAD

**Issue by iamshreeram** [huggingface/transformers#28170]
### System Info

**Transformers Version** : 4.36.0.dev0 
**Platform** : Mac OS 
**Python** : 3.9.18

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps to reproduce : 
1. Run the following program to translate to the target language:
```
from transformers import pipeline

pipeline_generator = pipeline(
    "automatic-speech-recognition",
    "facebook/seamless-m4t-v2-large",
)

transcript = pipeline_generator("https://www2.cs.uic.edu/~i101/SoundFiles/preamble10.wav", generate_kwargs={"tgt_lang": "spa",   },)
```

2. This throws the following exception:

```
Traceback (most recent call last):
  File "/Users/home/ram/project/python/text-translation-speech/ttrans.py", line 12, in <module>
    transcript = pipeline_generator("https://www2.cs.uic.edu/~i101/SoundFiles/preamble10.wav", generate_kwargs={"tgt_lang": "ta",   },)
  File "/Applications/anaconda3/envs/dub/lib/python3.9/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 357, in __call__
    return super().__call__(inputs, **kwargs)
  File "/Applications/anaconda3/envs/dub/lib/python3.9/site-packages/transformers/pipelines/base.py", line 1134, in __call__
    self.get_iterator(
  File "/Applications/anaconda3/envs/dub/lib/python3.9/site-packages/transformers/pipelines/base.py", line 1182, in get_iterator
    feature_extractor = self.feature_extractor if self.feature_extractor is not None else self.image_processor
AttributeError: 'AutomaticSpeechRecognitionPipeline' object has no attribute 'image_processor'
```

3. Despite not importing `image_processor`, the exception is thrown.

### Expected behavior

Produce output in the target language as seen in this [thread](https://github.com/facebookresearch/seamless_communication/issues/237#issuecomment-1864534911), running with the expected results.

**Comment by amyeroberts** [comment]
@sanchit-gandhi @ylacombe same issue as reported in #28162

**Comment by iamshreeram** [comment]
@amyeroberts , Thank you for investigating. Everything is functioning properly after the installation of the stable version of transformers (`4.36.2`).
