### ISSUE TITLE
ValueError: LlavaForConditionalGeneration does not support an attention implementation through torch.nn.functional.scaled_dot_product_attention yet. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new

### ISSUE THREAD

**Issue by 1106280506Hx** [huggingface/transformers#28175]
processor = AutoProcessor.from_pretrained("/gemini/data-2/data/llava")
model = AutoModelForPreTraining.from_pretrained("/gemini/data-2/data/llava",load_in_4bit=True,bnb_4bit_compute_dtype=torch.float16,low_cpu_mem_usage=True,attn_implementation="sdpa").to("cuda")

**Comment by amyeroberts** [comment]
cc @younesbelkada for reference

**Comment by 1106280506Hx** [comment]
can you tell me how to sovle it?

**Comment by amyeroberts** [comment]
Hi @1106280506Hx, 

As the error suggests, SDPA isn't supported in Llava on the version of transformers being run. However, just looking it up, #28107 was merged in a few days ago. You should be able to resolve this by running the dev version of transformers - installing from source: 
`pip install git+https://github.com/huggingface/transformers`

**Comment by 1106280506Hx** [comment]
Your answer is meaningful, thanks for your quick reply  @amyeroberts

**Comment by zucchini-nlp** [comment]
LLaVA supports sdpa now for llm backbone and for vision tower, closing as completed
