### ISSUE TITLE
Albert multilingual

### ISSUE THREAD

**Issue by nimning** [huggingface/transformers#2818]
# 🚀 Feature request

Provide multilingual pre-trained albert model.

## Motivation
Albert is a light weighted bert. It would be nice if it has the multilingual version.

**Comment by LysandreJik** [comment]
As far as I know (from following https://github.com/google-research/ALBERT/issues/5 and https://github.com/google-research/ALBERT/issues/91), ALBERT multilingual is not yet released.

We'll make sure to support it once it's released.

**Comment by stefan-it** [comment]
https://github.com/google-research/ALBERT/pull/152/files

😱😱😱
