### ISSUE TITLE
ValueError: Target module WQLinear_GEMM is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.- AWQ Quantisation Issues

### ISSUE THREAD

**Issue by Vasanth03** [huggingface/transformers#28193]
Hi @casper-hansen 

-> I am trying to train the AWQ quantised model using hugging face trainer.
While using PEFT (LoRA adaptor) the following error pops up.

![Screenshot 2023-12-22 at 12 47 36 PM](https://github.com/huggingface/transformers/assets/59615743/0bf7d637-04a9-4830-8d74-da7fd02b128c)

-> This is the version that I have used !pip install -q -U https://github.com/casper-hansen/AutoAWQ/releases/download/v0.1.6/autoawq-0.1.6+cu118-cp310-cp310-linux_x86_64.whl

Any help is much appreciated. Thanks

_Originally posted by @Vasanth03 in https://github.com/huggingface/transformers/issues/27321#issuecomment-1867330086_

**Comment by casper-hansen** [comment]
Hi @Vasanth03, AutoAWQ is not compatible with training yet. It will be in the future though.

**Comment by Vasanth03** [comment]
Thank you so much @casper-hansen.  And I look forward to its compatibility in the future.
