### ISSUE TITLE
Can you please provide the longformer version of the torch to tf file?

### ISSUE THREAD

**Issue by lsl200032** [huggingface/transformers#28194]
### Feature request

Can you please provide the longformer version of the torch to tf file?

### Motivation

Can you please provide the longformer version of the torch to tf file?

### Your contribution

Can you please provide the longformer version of the torch to tf file?

**Comment by amyeroberts** [comment]
Hi @lsl200032, 

There isn't a specific file for Longformer to convert from torch to TF weights. The conversion happens when using `from_pt` in the `from_pretrained` call: 

```
from transformers import TFLongformerModel 

# Loads the pytorch weights and converts them to the equivalent TF format then loads into the TF model
model = TFLongformerModel.from_pretrained(checkpoint, from_pt=True)
```

**Comment by lsl200032** [comment]
I have a longformer weight file that has been retrained in a downstream task, but it is a .bin file. I want to load it under the tf framework. How to solve it?

> 你好@lsl200032,
> 
> Longformer 没有将火炬权重转换为 TF 权重的特定文件。`from_pt`在调用中使用时会发生转换`from_pretrained`：
> 
> ```
> from transformers import TFLongformerModel 
> 
> # Loads the pytorch weights and converts them to the equivalent TF format then loads into the TF model
> model = TFLongformerModel.from_pretrained(checkpoint, from_pt=True)
> ```

I have a longformer weight file that has been retrained in a downstream task, but it is a .bin file. I want to load it under the tf framework. How to solve it?

**Comment by amyeroberts** [comment]
If the model was trained using Hugging Face's Longformer pytorch architecture, then you can use the code I mentioned above to load it as a TF model

```
from transformers import TFLongformerModel 

# Loads the pytorch weights and converts them to the equivalent TF format then loads into the TF model
model = TFLongformerModel.from_pretrained(path/to/model/folder, from_pt=True)
```

**Comment by lsl200032** [comment]
> If the model was trained using Hugging Face's Longformer pytorch architecture, then you can use the code I mentioned above to load it as a TF model
> 
> ```
> from transformers import TFLongformerModel 
> 
> # Loads the pytorch weights and converts them to the equivalent TF format then loads into the TF model
> model = TFLongformerModel.from_pretrained(path/to/model/folder, from_pt=True)
> ```

Thank you beautiful lady, your answer has given me confidence in my scientific research path. I hope to keep in touch with you.
