### ISSUE TITLE
torch.compile() silently fails when used on HuggingFace pipeline inference code

### ISSUE THREAD

**Issue by rosario-purple** [huggingface/transformers#28190]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
- Python version: 3.10.13
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.0
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.1+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.7.5 (cpu)
- Jax version: 0.4.21
- JaxLib version: 0.4.21
- Using GPU in script?: A100

### Who can help?

@Narsil @gante @ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the following Python code:

```
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.bfloat16,
        device_map=device,
        use_flash_attention_2=True,
    )

    model.eval()

    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    tokenizer.pad_token_id = tokenizer.eos_token_id

    model = torch.compile(model)

    generation_pipeline = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        batch_size=10,
    )

    batch_results = generation_pipeline(
        ["foo", "bar", "bin", "baz"],
        max_new_tokens=200,
        temperature=0.6,
        do_sample=True,
        repetition_penalty=1.05,
        num_return_sequences=20,
    )
```

(in my case, MODEL_ID is set to `"Open-Orca/Mistral-7B-OpenOrca"`, which is a fine-tune of Mistral-7B, but any LLM should work)

### Expected behavior

torch.compile() should compile the model, print some compilation messages, and then cause inference/text generation to be run faster. Instead, torch.compile() appears to not run at all, no messages are printed, and it has no effect on inference/generation speed. There is no error message, it just silently doesn't compile, effectively acting as if the line `model = torch.compile(model)` doesn't exist.

**Comment by ArthurZucker** [comment]
No this can't work yet at we do not have a static KV cache. #27931 will fix this

**Comment by BBerabi** [comment]
While working on benchmarking and improving our model's performance I experienced the same issue with `torch.compile`. It does not bring any speed up at all and can confirm the issue. 

@ArthurZucker Looking forward to having `torch.compile` supported in transformers!

**Comment by rosario-purple** [comment]
This is still broken

**Comment by ArthurZucker** [comment]
Indeed 🤗 marking as WIP until the PR is merged
