### ISSUE TITLE
loss did not change in expert loss of mixtral model

### ISSUE THREAD

**Issue by LinB203** [huggingface/transformers#28205]
### System Info

FROM THIS: https://github.com/huggingface/transformers/issues/28093

If I understand correctly, the loss consists of two parts, the autoregressive categorical loss on the one hand, and balancing the loss of each expert on the other.
I print each of the above two losses before adding up the final one, however, only the first one has a `grad_fn` of `NllLossBackward0`, the second one is just a tensor without `grad_fn` . That's why the `grad_fn` of the final loss is `NllLossBackward0` instead of `AddBackward`.
And the balancing expert's loss doesn't change during the training process. Maybe the changes you see are just changes due to the autoregressive categorical loss.

### Who can help?

@ArthurZucker

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

print each of the above two losses before adding up the final one

### Expected behavior

The expert balanced loss should converge and have `grad_f`.

**Comment by linyubupa** [comment]
have you fix this problem, i just met the same issue

**Comment by LinB203** [comment]
> have you fix this problem, i just met the same issue

I change to use the deepspeed implementation of moe. I don't know how to fix it in HF. HF's loss is always a constant, while deepspeed's converges to change.

**Comment by theblackcat102** [comment]
@LinB203 could you point me to the deepspeed implementation of moe? Is it this one : [deepspeed/moe/layer.py](https://github.com/microsoft/DeepSpeed/blob/1787673edc7e45cd79fe10b95f92a02d3eb91505/deepspeed/moe/layer.py#L16) ?

**Comment by LinB203** [comment]
> @LinB203 could you point me to the deepspeed implementation of moe? Is it this one : [deepspeed/moe/layer.py](https://github.com/microsoft/DeepSpeed/blob/1787673edc7e45cd79fe10b95f92a02d3eb91505/deepspeed/moe/layer.py#L16) ?

Yes.

**Comment by awzhgw** [comment]
@LinB203  when i run demo ,cannot find preprocessor_config.json on LanguageBind_Video_merge and LanguageBind_Video_Image huggingface.co, can you offen it ?

Traceback (most recent call last):
  File "/home/guowl/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "/home/guowl/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/LanguageBind/LanguageBind_Video_merge/resolve/main/preprocessor_config.json
