### ISSUE TITLE
ImportError: cannot import name 'GradientAccumulator'

### ISSUE THREAD

**Issue by DenceChen** [huggingface/transformers#2820]
transformers==2.4.1;
tensoflow==2.1.0;
torch==1.4.0;
when i start with follow code get some error and i didn't have tensoflow-gpu.

**code**
---------------------------------------------------------------------------
from transformers import (
    TF2_WEIGHTS_NAME,
    BertConfig,
    BertTokenizer,
    DistilBertConfig,
    DistilBertTokenizer,
    GradientAccumulator,
    RobertaConfig,
    RobertaTokenizer,
    TFBertForTokenClassification,
    TFDistilBertForTokenClassification,
    TFRobertaForTokenClassification,
    create_optimizer,
)

**error**
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-4dd6bfff15e9> in <module>()
     12 from seqeval import metrics
     13 
---> 14 from transformers import (
     15     TF2_WEIGHTS_NAME,
     16     BertConfig,

ImportError: cannot import name 'GradientAccumulator'

**Comment by imayachita** [comment]
Hi,
anyone found workaround for this issue?
Thanks

**Comment by LysandreJik** [comment]
This shouldn't happen with transformers v2.4.1 and tensorflow >= 2.0.0.

I can't replicate this issue with the versions you mentioned.

Would you mind telling me what gets printed out when you run the following snippet?

```py
from transformers import __version__
import tensorflow as tf

print("Transformers version", __version__)
print("TensorFlow version", tf.__version__)
```

**Comment by DenceChen** [comment]
well done
