### ISSUE TITLE
[DOCS] - Wrong link to model#generative-models in Pipeline docs

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [huggingface/transformers#28224]
### System Info

Latest docs on https://huggingface.co/docs/transformers/en/main_classes/pipelines#transformers.TextGenerationPipeline

### Who can help?

@stevhliu and @MKhalusova

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Inside the documentation for [pipelines#transformers.TextGenerationPipeline.__call__](https://huggingface.co/docs/transformers/en/main_classes/pipelines#transformers.TextGenerationPipeline.__call__) the docs read:

> generate_kwargs — Additional keyword arguments to pass along to the generate method of the model (see the generate method corresponding to your framework [here](https://huggingface.co/docs/transformers/en/main_classes/model#generative-models)).

The header part of the link (#generative-models) does not exist in the [main model page](https://huggingface.co/docs/transformers/en/main_classes/model) though - I'm not sure any of the headers there are appropriate actually. 

The problem is repeated for two other tasks at least: Conversational, text2textgeneration.

For the text-generation case, the corresponding docs link is [pipelines/text_generation.py#L198](https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/text_generation.py#L198)

### Expected behavior

The link sends me to documentations about common model-generation parameters - Maybe [this](https://huggingface.co/docs/transformers/generation_strategies)?

**Comment by amyeroberts** [comment]
Hi @BrunoGomesCoelho, thanks for raising this issue! 

Would you like to open a PR to fix these links? This way you get the github contribution

**Comment by BrunoGomesCoelho** [comment]
I think @coolyashas had attempted this in #28231 - It seems ready to go other than minor comments - Do you want to re-open and submit @coolyashas?

**Comment by coolyashas** [comment]
> I think @coolyashas had attempted this in #28231 - It seems ready to go other than minor comments - Do you want to re-open and submit @coolyashas?

Yes, I would like to re-open and submit it! @amyeroberts

**Comment by nmuthusamy** [comment]
@amyeroberts,  I have added a quick PR for this issue. Kindly review it and share your feedback. Appreciate it!

**Comment by junhl** [comment]
@amyeroberts - I filed up [this PR](https://github.com/huggingface/transformers/pull/30948) to resolve it. Hopefully the third time is the lucky charm.
