### ISSUE TITLE
Add JAX implementation of Phi 

### ISSUE THREAD

**Issue by shivance** [huggingface/transformers#28237]
### Model description

Transformers already has Phi #26110 . I want to contribute the JAX/Flax implementation of the same.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by dfdx** [comment]
@shivance This issue is marked as completed but I can neither find the implementation in the [code tree](https://github.com/huggingface/transformers/tree/main/src/transformers/models/phi), nor load the model via `FlaxAutoModel`. Can you please point me to the implementation?

**Comment by amyeroberts** [comment]
@dfdx The Flax implementation of Phi hasn't been added yet. If you or anyone else in the community would like to contribute, we'd be happy to review a PR!

**Comment by dfdx** [comment]
FYI: I'm working on Flax implementation of Phi [here](https://github.com/dfdx/transformers/blob/dfdx/phi-2-flax/src/transformers/models/phi/modeling_flax_phi.py) (based on Flax Llama code). Attention is implemented, the rest should be pretty straightforward, so I expect a PR to be ready in a couple of weeks.
