### ISSUE TITLE
`transformers==4.36.2` not available from `huggingface` conda channel

### ISSUE THREAD

**Issue by kevherro** [huggingface/transformers#28248]
### System Info

- `transformers` version: 4.33.3
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.10.13
- Huggingface_hub version: 0.20.1
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.2 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install the latest version of [**Miniconda**](https://docs.conda.io/projects/conda/en/stable/user-guide/install/download.html)
2. Create a `conda` environment: `conda create -n ENVNAME python=3.10`
3. Activate the environment: `conda activate ENVNAME`
4. Search for the `transformers` package:

```
(ENVNAME) % conda search huggingface::transformers
Loading channels: done
# Name                       Version           Build  Channel
transformers                  v4.0.0    pyh39e3cac_0  huggingface
...
transformers                  4.33.3            py_0  huggingface
```

Note that the highest version available is `4.33.3`. When I attempt to install the _latest_ version (at the time of this writing, `4.36.2`):

```
(ENVNAME) % conda install huggingface::transformers==4.36.2
Channels:
 - defaults
 - huggingface
 - pytorch
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - huggingface::transformers==4.36.2
```

### Expected behavior

I expected the latest version of `transformers` (`4.36.2`) to be available from the `huggingface` conda channel.

**Comment by kevherro** [comment]
On a related note: it appears that upgrading to the latest version of `transformers` (`4.36.2`) resolves the `KeyError: 'mixtral'` [bug](https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1/discussions/9). This means that anyone installing `transformers` from the `huggingface` conda channel (as described in the official docs [here](https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1/discussions/9)) will run into this bug.

As a workaround, folks can get it from the [conda-forge channel](https://anaconda.org/conda-forge/transformers).

**Comment by hsuyab** [comment]
So was your problem with the `mistral` bug or with not able to install `transformers` (`4.33.3`) from conda channel?

**Comment by kevherro** [comment]
The latter. Until the latest `transformers` version (`4.36.2`) is available from the `huggingface` conda channel, the `mistral` bug is likely unavoidable on that channel.

**Comment by hsuyab** [comment]
Yeah, true since `conda` channel is running quite behind the `conda-forge`.

**Comment by LysandreJik** [comment]
In the future we'll likely remove the `huggingface` channel support for conda unless we see explicit demand here; if that's the case, please put a thumbs up here (we'll monitor), otherwise, the conda-forge channel is usually very up to date. 

Thanks for raising the issue!

**Comment by kevherro** [comment]
Thanks for following up!

I'm channel-indifferent, but the `README` should reflect the channel that offers the latest version of `transformers`.

I went ahead and opened a preemptive PR to use the `conda-forge` channel in the `README`.

**Comment by atulsaurav** [comment]
> In the future we'll likely remove the `huggingface` channel support for conda unless we see explicit demand here; if that's the case, please put a thumbs up here (we'll monitor), otherwise, the conda-forge channel is usually very up to date.
> 
> Thanks for raising the issue!

I would prefer pointing my CI pipelines to an official HuggingFace channel
