### ISSUE TITLE
Safely extend vocabulary of BPE tokenizers

### ISSUE THREAD

**Issue by ekurtulus** [huggingface/transformers#28272]
### Feature request

Allow extension of BPE tokenizers by further training on new corpus.

### Motivation

This would benefit finetuning English models for other languages

### Your contribution

I do not know how to approach this in Transformers.

**Comment by amyeroberts** [comment]
Hi @ekurtulus, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
