### ISSUE TITLE
Model generate with batch_size for Seq2SeqLM

### ISSUE THREAD

**Issue by kedarthakkar** [huggingface/transformers#28289]
### Feature request

When running `model.generate`  with a `Seq2SeqLM`, I've run into OOM issues in resource-constrained environments (i.e. Google Colab notebook) when passing in a large batch (i.e. 1000 samples). I propose adding a `batch_size` parameter to `model.generate` so that `input_ids` can be loaded in batches for sequence generation rather than loading the entire tensor into memory from the start. Would appreciate thoughts and suggestions on this from more experienced folks.

### Motivation

Motivation is to prevent OOM issues when loading large datasets for inference on resource-constrained environments.

### Your contribution

I can work on implementing this if it makes sense to add as a feature.

**Comment by kedarthakkar** [comment]
Another option could be to instead define a function `model.generate_streaming` which takes in `batch_size` and yields generated sequences in `batch_size` increments. This would then allow the user to determine what they want to do with the yielded sequences (i.e. write them to a file or compute some metrics).

**Comment by LysandreJik** [comment]
cc @gante

**Comment by gante** [comment]
Hi @kedarthakkar 👋 

You can easily control the batch size with a few extra lines before calling `model.generate(), e.g. looping over your batch using smaller batches as input to the function. That is a much simpler solution than adding tens of lines of additional complexity to an already complex function :)

**Comment by kedarthakkar** [comment]
Ok, makes sense, I'll close this issue.
