### ISSUE TITLE
Conv1d would be initialized to all zeros in a pretrained_model

### ISSUE THREAD

**Issue by Hannibal046** [huggingface/transformers#28298]
### System Info

- `transformers` version: 4.36.2
- Platform: Linux-5.15.0-1050-azure-x86_64-with-glibc2.17
- Python version: 3.8.18
- Huggingface_hub version: 0.20.1
- Safetensors version: 0.4.1
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers import BertModel
import torch
class MyBERT(BertModel):
    def __init__(self,config):
        super().__init__(config)
        self.conv = torch.nn.Conv1d(
            in_channels=768,
            out_channels=768,
            kernel_size = 16,
            )
        self.post_init()
mybert = MyBERT.from_pretrained("bert-base-uncased")
print(mybert.conv.weight.data[0])
```

![image](https://github.com/huggingface/transformers/assets/38466901/584e2717-fd9a-48fe-af69-02f2c40d67cc)
![image](https://github.com/huggingface/transformers/assets/38466901/5976396a-0852-4a2a-a501-6bed59b6d64a)

### Expected behavior

The conv layer would be initialized properly.

**Comment by Hannibal046** [comment]
It seems that the problem was in `from_pretrained`. When I init the model with config, it works fine.

![image](https://github.com/huggingface/transformers/assets/38466901/c1324715-9e6f-4b2c-bdab-fc32a50a3e9a)

**Comment by Hannibal046** [comment]
OK, I see. It is a feature for LLM loading. Using the following would solve the problem:
```python
MyBERT.from_pretrained("bert-base-uncased",_fast_init=False)
```

**Comment by ArthurZucker** [comment]
Hey! It's more like[ the init scheme](https://github.com/huggingface/transformers/blob/b1292bca6923cfbc9cb3f70cb55df57e4e17e630/src/transformers/models/bert/modeling_bert.py#L744)

needs to be updated to your needs! `_fast_init` will skip normal inits and `_init_weights` is the only function that will be called for this.

**Comment by Hannibal046** [comment]
Got it! Appreciate
