### ISSUE TITLE
[facebook/rag-sequence-nq] ValueError: Config name is missing. 

### ISSUE THREAD

**Issue by zhangnju** [huggingface/transformers#28291]
### System Info

- `transformers` version: 4.36.2
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.20.1
- Safetensors version: 0.4.1
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 1.13.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1.run the sample codes of this link: https://huggingface.co/facebook/rag-sequence-nq 
from transformers import RagTokenizer, RagRetriever, RagSequenceForGeneration 
 
tokenizer = RagTokenizer.from_pretrained("facebook/rag-sequence-nq") 
retriever = RagRetriever.from_pretrained("facebook/rag-sequence-nq", index_name="exact", use_dummy_dataset=True) 
model = RagSequenceForGeneration.from_pretrained("facebook/rag-sequence-nq", retriever=retriever) 
 
input_dict = tokenizer.prepare_seq2seq_batch("how many countries are in europe", return_tensors="pt") 

generated = model.generate(input_ids=input_dict["input_ids"]) 
print(tokenizer.batch_decode(generated, skip_special_tokens=True)[0]) 

2. meet the below issue 
Traceback (most recent call last):
  File "rag_test.py", line 4, in <module>
    retriever = RagRetriever.from_pretrained("facebook/rag-sequence-nq", index_name="exact", use_dummy_dataset=True)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/rag/retrieval_rag.py", line 443, in from_pretrained
    index = cls._build_index(config)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/rag/retrieval_rag.py", line 423, in _build_index
    return CanonicalHFIndex(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/rag/retrieval_rag.py", line 278, in __init__
    dataset = load_dataset(
  File "/usr/local/lib/python3.8/dist-packages/datasets/load.py", line 2519, in load_dataset
    builder_instance = load_dataset_builder(
  File "/usr/local/lib/python3.8/dist-packages/datasets/load.py", line 2228, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 371, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 576, in _create_builder_config
    raise ValueError(
ValueError: Config name is missing.
Please pick one among the available configs: ['psgs_w100.nq.exact', 'psgs_w100.nq.compressed', 'psgs_w100.nq.no_index', 'psgs_w100.multiset.exact', 'psgs_w100.multiset.compressed', 'psgs_w100.multiset.no_index', 'psgs_w100.nq.exact.no_embeddings', 'psgs_w100.nq.compressed.no_embeddings', 'psgs_w100.nq.no_index.no_embeddings', 'psgs_w100.multiset.exact.no_embeddings', 'psgs_w100.multiset.compressed.no_embeddings', 'psgs_w100.multiset.no_index.no_embeddings']
Example of usage:
        `load_dataset('wiki_dpr', 'psgs_w100.nq.exact')`

### Expected behavior

help the sample codes to run successfully

**Comment by LysandreJik** [comment]
Maybe cc @ydshieh as you have played with RAG recently.

**Comment by ydshieh** [comment]
Hi @zhangnju 

What is your `datasets` version?

On [this google colab](https://colab.research.google.com/drive/1pCLInwexxrwg2WGIxgjmFMs6YeHZsCOm?usp=sharing), I can't reproduce this issue, but it uses `datasets==2.16.1`.
