### ISSUE TITLE
[Trainer] rename tokenizer to tokenizer_or_processor

### ISSUE THREAD

**Issue by Hambaobao** [huggingface/transformers#28308]
### Feature request

I suggest renaming the `tokenizer` parameter in **Trainer** to `tokenizer_or_processor`.

### Motivation

In the future, the training of many **multimodal models** will certainly require the use of **Trainer**. However, in multimodal models, the processors used to process  data are not just `tokenizer`, but also include things like `tokenizer` and `image_processor`, which are now mostly referred to as `processor`. Renaming `tokenizer` to `tokenizer_or_processor` will help improve the readability of the **Trainer** code during multimodal model development.

### Your contribution

I can help rename `tokenizer` to `tokenizer_or_processor`.

**Comment by ArthurZucker** [comment]
fyi @pacman100 and @muellerzr 🤗
