### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by isRambler** [huggingface/transformers#28310]
OSError: Unable to load weights from pytorch checkpoint file for '/root/autodl-tmp/llama-2-7b/pytorch_model-00001-of-00002.bin' at '/root/autodl-tmp/llama-2-7b/pytorch_model-00001-of-00002.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint

Why do I get an error when I use TensorRT-LLM’s build.py to convert the llam-2-7b model?
<img width="199" alt="19e41154a77724674ccbdc88d21d5ce" src="https://github.com/huggingface/transformers/assets/118053582/49fabd99-1ff3-49f1-ba40-7922bde51062">

**Comment by zk923852367** [comment]
me too

**Comment by ArthurZucker** [comment]
Hey! I think that a conversion is attempted between pt and tf, but transformers does not support a TF implementation of this model. Could you rather open an issue on the `TensorRT-LLM` library with a full reproducer of what you are trying to do and the full stacktrace

**Comment by isRambler** [comment]
> Hey! I think that a conversion is attempted between pt and tf, but transformers does not support a TF implementation of this model. Could you rather open an issue on the `TensorRT-LLM` library with a full reproducer of what you are trying to do and the full stacktrace

Okay, I'm going to ask the relevant questions
