### ISSUE TITLE
Unclear Tokenizer Algorithm Documentation

### ISSUE THREAD

**Issue by kitkhai** [huggingface/transformers#28322]
**Bug description.**
In the docs, for example for [NLLB ](https://huggingface.co/docs/transformers/model_doc/nllb), the "slow"  & "fast" tokenizers are documented to be based on SentencePiece & BPE respectively. 
I do think that is a little confusing as:
- Saying that the "slow" tokenizer is based on SentencePiece, it is unclear whether is it implementing the BPE or unigram model?
- Saying that the "fast" tokenizer is based on BPE, is also unclear whether it refers to SentencePiece's implementation of BPE? Or just the standalone BPE algorithm? 

**Describe the expected behaviour**
Can be more explicit when describing what the tokenizer is based on, such as:

- Unigram(spm)
- BPE (spm)
- Unigram
- BPE

**Comment by ArthurZucker** [comment]
Hey! Thanks for raising this issue. Do you want to open a PR for a fix? 🤗

**Comment by kitkhai** [comment]
Hey! Thanks for the swift response.

I'm still rather new and am actually confused about what the "slow" & "fast" Tokenizers are based on... (I don't really understand why one is based on "sentencepiece" and the other is based on "BPE"? Aren't they supposed to be trained the same way just implemented in different programming languages?)

Hence, I don't think I am in a position to open a PR for a fix? Sorry about that 😬

**Comment by ArthurZucker** [comment]
Your intuition is correct, the slow version uses the `sentencepiece` backend, so the BPE implementation of `sentencepiece` library. While the fast uses the `tokenizers` backend, with the `BPE` implementation of `tokenizers` that is based on `sentencepiece`!
