### ISSUE TITLE
[TrOCR] Dealing with occasional multi-line images

### ISSUE THREAD

**Issue by aureliusnoble** [huggingface/transformers#28329]
Hi, I am using TrOCR to transcribe historical (18th century) handwritten French data.

I am feeding in text-line images which are automatically segmented. However, due to the nature of the documents, sometimes this segmentation is not perfect, and the image contains multiple lines of text. These have been transcribed with the \n token.

I know that ideally I would not pass in multi-line images, however these will be occasionally present in the data I want to run inference on. What are your thoughts on dealing with these when fine-tuning TrOCR? About 5-10% of lines include a "\n" character, about 1% contain multiple "\n" characters. Currently I just convert these to whitespaces.

cc: @NielsRogge . Any advice would be greatly appreciated.

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!

Thanks!
