### ISSUE TITLE
Does m2m_100 support multiple forced_bos_token_id?

### ISSUE THREAD

**Issue by sfc-gh-zhwang** [huggingface/transformers#28336]
```
generated_tokens = model.generate(input_ids = ids_tensor, attention_mask = attention_padded, forced_bos_token_id=[tokenizer.get_lang_id("es"),tokenizer.get_lang_id("fr")])
```
Seems above code will output the same language output.

**Comment by ArthurZucker** [comment]
You should use `forced_decoder_ids` https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig.forced_decoder_ids
