### ISSUE TITLE
Use mmap to accelerate checkpoint loading

### ISSUE THREAD

**Issue by weimingzha0** [huggingface/transformers#28332]
### Feature request

Use torch.load(mmap=True) if possible.

### Motivation

Python 2.1 allows mmap() when loading checkpoints ([doc](https://pytorch.org/docs/stable/generated/torch.load.html))
I tested on a 6B model: with mmap(),   takes 2.x seconds to load (vs 12.x seconds without using mmap)

### Your contribution

https://github.com/huggingface/transformers/pull/28331

**Comment by ArthurZucker** [comment]
Closing as the PR was merged
