### ISSUE TITLE
Switch Transformers Jitter Noise in Inference

### ISSUE THREAD

**Issue by drunkcoding** [huggingface/transformers#28342]
### System Info

- `transformers` version: 4.36.2
- Platform: Linux-5.15.0-1033-gkeop-x86_64-with-glibc2.17
- Python version: 3.8.18
- Huggingface_hub version: 0.20.1
- Safetensors version: 0.3.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False

### Who can help?

@ArthurZucker 

Switch Transformers add jitter noise 
```python
if self.jitter_noise > 0:
```

According to the paper, jitter noise can only be added during training 

![image](https://github.com/huggingface/transformers/assets/14305648/1f1ac27a-375a-42d0-8bcc-4c5402221715)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
model = AutoModel.from_pretrained("google/switch-base-128")
tokenizer = AutoTokenizer.from_pretrained("google/switch-base-128")
input_text = "Hello, my dog is cute"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids
attention_mask = torch.ones_like(input_ids)

set_seed(42)

outputs = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_length=20,
    decoder_start_token_id=0,
    do_sample=False,
    return_dict_in_generate=True,
    output_attentions=False,
    output_hidden_states=False,
)
```

### Expected behavior

Output is different every time running generate

**Comment by ArthurZucker** [comment]
Hey! Before I can help you, could provide an actual reproducer? 
This one fails with `TypeError: The current model class (SwitchTransformersModel) is not compatible with `.generate()`, as it doesn't have a language model head. Please use one of the following classes instead: {'SwitchTransformersForConditionalGeneration'}`.

**Comment by ArthurZucker** [comment]
Moreover when I use the correct class, disabeling `return_dict_in_generate` for convenience, I always get the same output. 
https://github.com/huggingface/transformers/blob/90224dd59e92e11d99b5b09be84d3fe7794636b9/src/transformers/models/switch_transformers/modeling_switch_transformers.py#L171 

adds jitter only if training
