### ISSUE TITLE
Is there some bug in typehint in `modeling_outputs` (or maybe other files)?

### ISSUE THREAD

**Issue by gary-young** [huggingface/transformers#28345]
### System Info

Hi! When I tried to modify some code which calls some classes in `src/transformers/modeling_outputs.py` such as the class `BaseModelOutput` and `BaseModelOutputwithPast`, I find the typehint of some parameters is different from your comments and my understanding of the code. I believe the correct type of them should be like `Optional[Tuple[torch.FloatTensor, ...]]` instead of `Optional[Tuple[torch.FloatTensor]]` because the comments say the tuple with length which equals to the num of layers or something else but not **ONE**. However, the type hint `Optional[Tuple[torch.FloatTensor]]` means the tuple should be length 1.

Is my understanding correct? Or am I misunderstanding what these codes do?

![image](https://github.com/huggingface/transformers/assets/56245046/90295155-0ad3-4f30-b771-aeeee2179740)

@ArthurZucker @younesbelkada Thank you!

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I use the Pylance as the type checker.

### Expected behavior

The typehint would not affect the behavior.

**Comment by ArthurZucker** [comment]
Hey! I think that we used Tuple[X] when there can be N instances of X. I don't mind using ellipsis. 
cc @Rocketknight1 who is our type expert!

**Comment by gary-young** [comment]
@ArthurZucker Thank you for your reply! I am a new guy for type hint so I am not sure about the situation about the previous version (before Python 3.10) but in the lastest version (Python 3.11 or 3.12), the Tuple[X] just means a tuple with **ONE** element with type X. 
![image](https://github.com/huggingface/transformers/assets/56245046/0fcfec13-bb78-4e27-adfe-d992ee831508)
This is an example provided by the document of Python: https://docs.python.org/3/library/typing.html
And my Pylance checker has indeed raise a warning about it.

**Comment by gary-young** [comment]
And also the type hint `Tuple` and `tuple` are considered as the same:
![image](https://github.com/huggingface/transformers/assets/56245046/31f1656c-8661-41c4-88ae-016e7a853f97)

**Comment by ArthurZucker** [comment]
feel free to open a PR for a fix if you want 🤗

**Comment by Rocketknight1** [comment]
Hi @gary-young, I think you're correct! We realize it would be quite a significant job to update all instances of this across the codebase, but if you want to contribute fixes to one or more files, we'd be happy to accept a PR.

**Comment by gary-young** [comment]
Ok! I am willing to fix some of them for those I can identify.

**Comment by nakranivaibhav** [comment]
I would like to work on this issue
