### ISSUE TITLE
Token healing (under 40 LOC)

### ISSUE THREAD

**Issue by ahmed-moubtahij** [huggingface/transformers#28346]
### Feature request

Token healing rectifies the token boundary bias in greedy tokenization. It does this by trimming and regrowing the prompt to better align with the model's tokenizer, thus enhancing generation quality. The improvement is clearest with completion models.

Token boundary bias is a silent performance killer that doesn't seem very well known. It has clear impact on completion quality, though I'm not sure where it would fit as a transformers feature.

A more thorough explanation of the problem: [The Art of Prompt Design: Prompt Boundaries and Token Healing | by Scott Lundberg](https://towardsdatascience.com/the-art-of-prompt-design-prompt-boundaries-and-token-healing-3b2448b0be38).

### Motivation

Given a completion prompt with a partial url ending with `:`, the model might have seen the expected completion `://` as a _single_ token in training. However, the prompt's tail token `:` tells it that the next token is not `//`, and so it generates a wrong completion. Such errors compound in auto-regressive language models.

### Your contribution

My implementation (under 40 LOC): https://github.com/Ayenem/TokenHealer/tree/main

**Comment by ArthurZucker** [comment]
FYI @gante

**Comment by gante** [comment]
@Ayenem that's a really cool use of `sequence_bias`! I had read about token healing in the past, and never thought about it when I added `sequence_bias`.

Would you be up for adding it to `transformers`? I think we could include it inside `generate` (e.g. [here](https://github.com/huggingface/transformers/blob/6c78bbcb8320d316434262ef003251ca997db0d1/src/transformers/generation/utils.py#L1638)), passing a simple `token_healing=True` flag. What do you think?

**Comment by Ayenem** [comment]
I'm glad you appreciate this use of your feature! Hyrum's law at play :)

Sounds good, I'll get started on a dev branch.

**Comment by gante** [comment]
Hi @Ayenem 👋 

I noticed you closed your latest PR. Is there anything we can help you with? 🤗
