### ISSUE TITLE
[tests] Check device failed in test_small_model_pt_bloom_accelerate

### ISSUE THREAD

**Issue by yuanwu2017** [huggingface/transformers#28350]
### System Info

transformers              4.37.0.dev0
pytorch                   2.1.2           py3.9_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torchaudio                2.1.2                py39_cu118    pytorch
torchtriton               2.1.0                      py39    pytorch
torchvision               0.16.2               py39_cu118    pytorch
accelerate                0.25.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

 When running the following case on multi-cards server with devcie_map-auto, It will not always be allocated to device 0,
Because other processes may be using these cards. It will select the devices that can accommodate this model.
pytest tests/pipelines/test_pipelines_text_generation.py::TextGenerationPipelineTests::test_small_model_pt_bloom_accelerate

Error log:
FAILED tests/pipelines/test_pipelines_text_generation.py::TextGenerationPipelineTests::test_small_model_pt_bloom_accelerate - AssertionError: device(type='cuda', index=7) != device(type='cuda', index=0)

### Expected behavior

If just testing whether the model works, It doesn’t need to strictly check the device, because it may eventually be loaded to the CPU due to insufficient GPU memory.

**Comment by ArthurZucker** [comment]
Hey! Sure, would you like to open a pr for a fix?
