### ISSUE TITLE
Weird Tokenization when Training New Tokenizer from GPT2 Tokenizer using train_new_from_iterator

### ISSUE THREAD

**Issue by minmie** [huggingface/transformers#28353]
### System Info

- `transformers` version: 4.33.0     
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoTokenizer
from datasets import load_dataset

path = r'E:\pythonWork\nlp\ner\soucre_data\cluener.jsonl'  # a chinese text dataset
raw_data = load_dataset("json", data_files=path, split='train')

training_corpus = (
    raw_data[i : i + 1000]["text"]
    for i in range(0, len(raw_data), 1000)
)

old_tokenizer = AutoTokenizer.from_pretrained("E:\pythonWork\models\gpt2")
tokenizer = old_tokenizer.train_new_from_iterator(training_corpus, 10000)

example = '就是去美国大使馆的官方网站，它有中文版，去把每一条仔细研究透了，把每一个表格和材料都准备好了'  # chinese text
old_tokens = old_tokenizer.tokenize(example)
print('old_tokens:',old_tokens)

new_tokens = tokenizer.tokenize(example)
print('new_tokens',new_tokens)
```

cluener.jsonl as follow:
![image](https://github.com/huggingface/transformers/assets/40080081/da268899-8454-47cc-af19-50e3804ff51f)

### Expected behavior

I  trained my own tokenizer using chinese text base on this demo (https://huggingface.co/learn/nlp-course/chapter6/2) .

And the outputs of the two tokenizer are as follow:

```
old_tokens: ['å°', '±', 'æĺ¯', 'åİ', '»', 'ç', '¾', 'İ', 'åĽ', '½', 'å¤§', 'ä½¿', 'é', '¦', 'Ĩ', 'çļĦ', 'å®', 'ĺ', 'æĸ¹', 'ç', '½', 'ĳ', 'ç«', 'Ļ', 'ï', '¼', 'Į', 'å®', 'ĥ', 'æľ', 'ī', 'ä¸Ń', 'æĸ', 'ĩ', 'çīĪ', 'ï', '¼', 'Į', 'åİ', '»', 'æ', 'Ĭ', 'Ĭ', 'æ', '¯', 'ı', 'ä¸Ģ', 'æĿ', '¡', 'ä»', 'Ķ', 'ç', '»', 'Ĩ', 'ç', 'ł', 'Ķ', 'ç', '©', '¶', 'éĢ', 'ı', 'äº', 'Ĩ', 'ï', '¼', 'Į', 'æ', 'Ĭ', 'Ĭ', 'æ', '¯', 'ı', 'ä¸Ģ', 'ä¸', 'ª', 'è¡', '¨', 'æł', '¼', 'å', 'Ĵ', 'Į', 'æĿ', 'Ĳ', 'æĸ', 'Ļ', 'éĥ', '½', 'åĩ', 'Ĩ', 'å¤', 'ĩ', 'å¥', '½', 'äº', 'Ĩ']
new_tokens ['å°±æĺ¯', 'åİ»', 'ç¾İåĽ½', 'å¤§ä½¿é¦Ĩ', 'çļĦ', 'å®ĺæĸ¹ç½ĳç«Ļ', 'ï¼Į', 'å®ĥ', 'æľī', 'ä¸ŃæĸĩçīĪ', 'ï¼Į', 'åİ»', 'æĬĬ', 'æ¯ı', 'ä¸ĢæĿ¡', 'ä»Ķç»Ĩ', 'çłĶç©¶', 'éĢı', 'äºĨ', 'ï¼Į', 'æĬĬ', 'æ¯ıä¸Ģä¸ª', 'è¡¨', 'æł¼', 'åĴĮ', 'æĿĲæĸĻ', 'éĥ½', 'åĩĨå¤ĩ', 'å¥½', 'äºĨ']
```

emm，both outputs are really weird. is this right?

**Comment by ArthurZucker** [comment]
Hey! You should have a look at https://github.com/huggingface/tokenizers/issues/203 it's expected! 🤗

**Comment by minmie** [comment]
@ArthurZucker   thanks for your help.
