### ISSUE TITLE
"cached cross_attention states don't have to be reordered -> they are always the same"

### ISSUE THREAD

**Issue by YJYJLee** [huggingface/transformers#28357]
### System Info

Sorry, this is not the bug report, but I couldn't find the proper category to ask this question

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

![Screenshot 2024-01-05 at 10 13 07 AM](https://github.com/huggingface/transformers/assets/28900943/d4abaec7-9dfd-4384-94dc-43a120964b19)

I have noticed that in many models, KV cache reordering is not happening for cross_attention states.

### Expected behavior

Could someone explain why we don't need KV cache reordering for cross_attention states?

To my knowledge, KV cache or cross_attention also needs to be reordered according to the selected beam indices during the beam search. But I'm not sure how "they are always the same" for cross_attentions.

**Comment by ArthurZucker** [comment]
Cross attention only happends between the encoder and decoder, but the encoded states do not change, you always use the same, the decoder state change. Thus you don't re-compute / change the cross-attention states across the generate function
