### ISSUE TITLE
Data collator does not pass inputs to tokenizer

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/transformers#28371]
Hello all,

While attempting to train a model using `Trainer` and `DataCollatorForSeq2Seq`, I get the following error:
`ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided []`.

I have written my own model class (this is necessary for the design), which wraps the base model (a `PreTrainedModel`) and has only the `forward`, `generate`, `prepare_inputs_for_generation` and some utility methods.

Am I missing a method to let `transformers` know what inputs I expect? I would greatly appreciate any tips!

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!

Thanks!

**Comment by EricLBuehler** [comment]
Ok, thanks for the recommendation!
