### ISSUE TITLE
The model has parameters that do not require training, causing training to be interrupted.

### ISSUE THREAD

**Issue by xmy0916** [huggingface/transformers#28374]
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-5.4.143.bsk.8-amd64-x86_64-with-glibc2.28
- Python version: 3.10.13
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.4.0
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
def build_vision_projector(config, delay_load=False, **kwargs):
    return nn.ModuleDict({
        "image": nn.Linear(config.mm_hidden_size, config.hidden_size),
        "video": nn.Linear(config.mm_hidden_size, config.hidden_size)
    })
```

i have a projector layer which will match the input tensor by the key image or video. above code will cause the training to get stuck.

when i modify the code like:
```python
def build_vision_projector(config, delay_load=False, **kwargs):
    proj = nn.Linear(config.mm_hidden_size, config.hidden_size)
    return nn.ModuleDict({
        "image": proj,
        "video": proj
    })
```

it means that all inputs use the same projector layer. This way can train normally.

### Expected behavior

The training error is:
![image](https://github.com/huggingface/transformers/assets/43675899/0c2163b2-d9f4-4702-ae19-e4b1eef7830f)

Some batches of my training data are a mixture of videos and images, some have only videos, and some have only images. This will result in the projector layer of some batches of video projector layer or image projector layer not being forwarded. It seems that this is the reason why the training is stuck.

Is there any solution?

**Comment by ArthurZucker** [comment]
Hey! No idea as we don't have access to the full custom code, but would recommend you to use the latest version of transformers, and share a full snippet + traceback otherwise we can't help you
