### ISSUE TITLE
model.generate() produces different results with paddings

### ISSUE THREAD

**Issue by zhentaocc** [huggingface/transformers#28385]
### System Info

I found this issue when I try to reproduce `https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard` results, specifically gsm8k on `mncai/Llama2-7B-guanaco-dolphin-500`. My result is 13.12 while the one reported was 5.99.   
Also I found paddings make the outputs different (not sure if they are correct). For example, with batch size = 1, which means no padding, it's 13.12; with batch size =8, it is 5.69.   
And I traced the root cause, findings are the same input token ids can get different outputs with or without padding tokens.  
And the `pad_token_id `was 2, which is the same as `eos_token_id`. So if I set `pad_token_id `as 0, the results seems same as that without paddings.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I tested following runs on RTX8000.
1. `python main.py --model=hf-causal-experimental --model_args="pretrained=mncai/Llama2-7B-guanaco-dolphin-500," --tasks=gsm8k --num_fewshot=5 --batch_size=1 `
2.  `python main.py --model=hf-causal-experimental --model_args="pretrained=mncai/Llama2-7B-guanaco-dolphin-500," --tasks=gsm8k --num_fewshot=5 --batch_size=8 `

### Expected behavior

1. accuracy should be ~13.12
2. accuracy should be ~5.69

**Comment by ArthurZucker** [comment]
Feel free to check https://github.com/huggingface/transformers/issues/25420#issuecomment-1775317535 for a better explanation
