### ISSUE TITLE
GPUA10：QWenLMHeadModel does not support Flash Attention 2.0 yet

### ISSUE THREAD

**Issue by PolarPeak** [huggingface/transformers#28383]
ValueError: QWenLMHeadModel does not support Flash Attention 2.0 yet. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new

my GPU is A10

transformers>=4.36.2

**Comment by ArthurZucker** [comment]
Hey, I don't think Qwen was merged into transformers it's a code on the hub, you should open the issue directly on the model discussion page : https://huggingface.co/Qwen/Qwen-72B/discussions
