### ISSUE TITLE
Fine-tuning the model using classification tasks

### ISSUE THREAD

**Issue by ankush20m** [huggingface/transformers#2839]
Hello All,

Could anyone tell how can I fine-tune the language model using classification tasks, however not using any GLUE data, as I have my own custom dataset?
Is there any solution and/or method to do the classification using a custom dataset?

**Comment by LysandreJik** [comment]
Hi, the `run_glue` example script was designed to showcase how to fine-tune any model to a classification task. It showcases many things you maybe don't need, such as data-parallel, checkpointing, half-precision, etc. You can adapt this script or study the training loop to create your own.
