### ISSUE TITLE
How the new version of transformers uses the author's LLaVA weights?

### ISSUE THREAD

**Issue by koking0** [huggingface/transformers#28404]
I am very excited that the LLaVA model has been added to transformers-4.36. I noticed that the LLaVA model of transformers seems to be different from the LLaVA author's model.

LLaVA model of transformers: [https://huggingface.co/llava-hf/llava-1.5-7b-hf](https://huggingface.co/llava-hf/llava-1.5-7b-hf)
LLaVA author's model: [https://huggingface.co/liuhaotian/llava-v1.5-7b](https://huggingface.co/liuhaotian/llava-v1.5-7b)

We have been using the LLaVA author's model. I would like to ask if transformers-4.36 can load the LLaVA author's model.

Something like this:

```python
from PIL import Image

import torch
from transformers import AutoProcessor, LlavaForConditionalGeneration

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# model_id = "llava-hf/llava-1.5-7b-hf"
model_id = "liuhaotian/llava-v1.5-7b"

prompt = "USER: <image>\nWhat are these?\nASSISTANT:"
image_file = "images/000000039769.jpg"

processor = AutoProcessor.from_pretrained(model_id)
model = LlavaForConditionalGeneration.from_pretrained(
     model_id,
     torch_dtype=torch.float16
).to(device)


raw_image = Image.open(image_file)
inputs = processor(prompt, raw_image, return_tensors='pt').to(0, torch.float16)

output = model.generate(**inputs, max_new_tokens=200, do_sample=False)
print(processor.decode(output[0][2:], skip_special_tokens=True))
```

**Comment by NielsRogge** [comment]
Hi,

Both should be equal (cc @younesbelkada).

Which difference are you seeing?

**Comment by koking0** [comment]
I used the above code, and the initial error was that the preprocessor_config.json file was missing. 

I found that there was indeed no such file in https://huggingface.co/liuhaotian/llava-v1.5-7b/tree/main, so I started from https://huggingface.co/llava-hf/llava-1.5-7b-hf/tree/main Download this file, then put it in the model folder of liuhaotian/llava-v1.5-7b, and then run it, I encountered the following error:

```
valueError: The input provided to the model are wrong. The number of image tokens is 0 while the number of image given to the model is 1. This prevents correct indexing and breaks batch generation.
```

![image](https://github.com/huggingface/transformers/assets/45281765/b6d2865c-9673-492a-9636-f7c00291cfe1)

**Comment by younesbelkada** [comment]
Hi @koking0 
unfortunately the checkpoints are not inter-compatible, if you want to use `liuhaotian/llava-v1.5-7b` you need to use the original author's library and not transformers

**Comment by koking0** [comment]
ok, fine.

**Comment by younesbelkada** [comment]
Note however `liuhaotian/llava-v1.5-7b` should be the same as `llava-hf/llava-1.5-7b-hf`, same for the 13b model and so on

**Comment by ChanyoungE** [comment]
> Hi @koking0 unfortunately the checkpoints are not inter-compatible, if you want to use `liuhaotian/llava-v1.5-7b` you need to use the original author's library and not transformers

Hi @younesbelkada. What is this mean ' not transformers'. Is that mean He should not use AutoProcessor,LlavaForConditionalGeneration from transformers packages?

**Comment by ArthurZucker** [comment]
The `transformers` supports is for the `-hf` checkpoints.
