### ISSUE TITLE
CausalLMOutputWithPast does not output hidden states

### ISSUE THREAD

**Issue by Tiziano41** [huggingface/transformers#28413]
### System Info

sentence-transformers      2.2.2
transformers                      4.31.0
numpy                               1.19

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

This is the code I'm using : 

model = AutoModelForCausalLM.from_pretrained("microsoft/phi-2", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-2", trust_remote_code=True)

inputs = tokenizer('''
Name the writings of Dante Alighieri.

Answer: 
''', return_tensors="pt", return_attention_mask=False)

embeddings = model(**inputs, output_hidden_states = True)

![image](https://github.com/huggingface/transformers/assets/156085316/040a75ea-18ba-4d4b-89c9-c7336869fb67)

### Expected behavior

As you can see in the image, the hidden_states attribute is None, while I would expect the intermediate layers representations.

I tried to specify the output_hidden_states = True, both in model instantiation and on inference but neither works.

Is there any parameter that I'm missing ? That's all I have seen on the available documentation.

Thank you in advance for you support.

**Comment by younesbelkada** [comment]
Hi @Tiziano41 
Thanks for the issue! It seems you are using the `trust_remote_code=True` model, therefore the bug should be on their end. Would you mind opening a similar issue on the original repository on 🤗  Hub? https://huggingface.co/microsoft/phi-2

**Comment by younesbelkada** [comment]
Alternatively you can use the HF version of Phi-2 which should be here https://huggingface.co/susnato/phi-2 if I am not mistaken cc @ArthurZucker @susnato

**Comment by Tiziano41** [comment]
@younesbelkada @susnato OK, Thank you both for the fast reply! I will open the issue on their repository.
