### ISSUE TITLE
when will add XLMRobertaForQuestionAnswering package

### ISSUE THREAD

**Issue by ynebula** [huggingface/transformers#2842]
I will study squad of multilingual.

I found that question answer package did include in run_squad.py.

I wanna release that package

Are you plan to release XLMRobertaForQuestionAnwering?

please let me know.

**Comment by RachelKer** [comment]
It is pretty easy to add the code yourself since RobertaForQuestionAnswering is already implemented and XLMRobertaForQuestionAnswering is just a wrapper around it.

**Comment by ynebula** [comment]
Thank you for your answering.

I got your mention

I have question one more

Is it possible to learn XLM-Roberta data to Roberta
(XLM-Roberta data is https://github.com/pytorch/fairseq/tree/master/examples/xlmr)

If it is possible, can you show me how to set up.

please let me know.

**Comment by ynebula** [comment]
I resolve the problem.

Thank you your answering
