### ISSUE TITLE
Intel/dpt-swinv2: TypeError: unsupported operand type(s) for //: 'NoneType' and 'NoneType' 

### ISSUE THREAD

**Issue by kadirnar** [huggingface/transformers#28449]
### System Info

- `transformers` version: 4.35.2
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.8.18
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.1
- Accelerate version: 0.25.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@Narsil @amyeroberts

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import pipeline

pipe = pipeline(task="depth-estimation", model="Intel/dpt-swinv2-large-384")
result = pipe("http://images.cocodataset.org/val2017/000000039769.jpg")
result["depth"]
```

Error Message:
```
image_size = image_size if isinstance(image_size, collections.abc.Iterable) else (image_size, image_size)
patch_size = patch_size if isinstance(patch_size, collections.abc.Iterable) else (patch_size, patch_size)
num_patches = (image_size[1] // patch_size[1]) * (image_size[0] // patch_size[0])
TypeError: unsupported operand type(s) for //: 'NoneType' and 'NoneType'
```

### Expected behavior

I want to test dpt-brit-large-384 models.
Model Page: https://huggingface.co/Intel/dpt-swinv2-large-384

**Comment by kadirnar** [comment]
This model doesn't work either.

https://huggingface.co/Intel/dpt-beit-base-384

**Comment by ArthurZucker** [comment]
cc @NielsRogge as well

**Comment by NielsRogge** [comment]
Hi,

Looks like you may need to update your Transformers version. Works for me on main

**Comment by kadirnar** [comment]
> Hi,
> 
> Looks like you may need to update your Transformers version. Works for me on main

I updated the package version.

- `transformers` version: 4.36.2
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.8.18
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.1
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

The "Intel/dpt-beit-base-384" model works, but the "swinv2" model doesn't.

<img width="1619" alt="image" src="https://github.com/huggingface/transformers/assets/36204372/98ea8310-8746-4180-a696-71ccd94d87d2">

**Comment by NielsRogge** [comment]
Ok, that's because https://github.com/huggingface/transformers/pull/27742 was merged 3 weeks ago, which probably was not part yet of 4.36.2. Hence this one will be part of the next Transformers release.
