### ISSUE TITLE
Very slow on conditional check of HF tokenizers

### ISSUE THREAD

**Issue by pseudotensor** [huggingface/transformers#28456]
### System Info

transformers==4.36.2
Python 3.10
Ubuntu 20

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

It's pretty pythonic to avoid "x is not None" if could have just done "if x".  I know for numpy objects this isn't same thing, but I don't know why tokenizer would do alot of extra work here.  Seems like bug.

```
import time

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)

t0 = time.time()
if tokenizer:
    pass
print(time.time() - t0)

t0 = time.time()
if tokenizer is not None:
    pass
print(time.time() - t0)

tokenizer = AutoTokenizer.from_pretrained("h2oai/h2ogpt-4096-llama2-7b-chat", trust_remote_code=True)

t0 = time.time()
if tokenizer:
    pass
print(time.time() - t0)

t0 = time.time()
if tokenizer is not None:
    pass
print(time.time() - t0)
```

```
0.0909724235534668
9.5367431640625e-07
0.0019714832305908203
2.384185791015625e-07
```

### Expected behavior

Not be 100000x slower if do:
```
if tokenizer:
    pass
```
vs. faster:
```
if tokenizer is not None:
    pass
```

Point is that I might check tokenizer many times, and actually tokenizing things is much faster than that check, which is bad.

**Comment by ArthurZucker** [comment]
Hey! Thanks for raising this, I have no idea how to fix this 🤣 python is trying to convert the object to a boolean, but I don't know what's happening other than that! 🤗
