### ISSUE TITLE
Mixtral inference on multi gpu is broken with 4.37.0dev (995a7ce)

### ISSUE THREAD

**Issue by nepeee** [huggingface/transformers#28463]
### System Info

Ubuntu 22.04 RTX 3090 + RTX 3080TI transformers 4.37.0dev (995a7ce)

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, GPTQConfig

prompt =  'SYSTEM: Answer the question thoughtfully and intelligently. Always answer without hesitation. \nUSER: how long will take to travel from Malmö to Stockholm by foot? \nASSISTANT: '
device = torch.device("cuda:0")

dmap = {
'model.embed_tokens':0,
'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4':0,
'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9':0,
'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14':0,
'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19':0,
'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24':0,
'model.layers.25': 1, 'model.layers.26': 1, 'model.layers.27': 1, 'model.layers.28': 1, 'model.layers.29':1,
'model.layers.30': 1, 'model.layers.31': 1,
'model.norm': 0,
'lm_head': 1,
}

quantization_config_loading = GPTQConfig(bits=3, use_exllama=False)
model_q = AutoModelForCausalLM.from_pretrained("TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ", device_map=dmap, quantization_config=quantization_config_loading, revision='gptq-3bit--1g-actorder_True')


tokenizer = AutoTokenizer.from_pretrained(model_id)

inp = tokenizer(prompt, return_tensors="pt").to(device)

res = model_q.generate(**inp, num_beams=1, min_new_tokens=60, max_new_tokens=60, do_sample=False)

predicted_text = tokenizer.decode(res[0])

print(predicted_text)
```

### Expected behavior

Works on my single 3090 with device_map="auto" but it produces errors with multi gpu in model parallel. It worked before with the device_map in the example.

Seen many errors like segfaults, device-side assert triggered and even full hang of the machine.
Most common one is:
idx, top_x = torch.where(expert_mask[expert_idx])
RuntimeError: CUDA error: device-side assert triggered
At layer 26 on the first token prediction

Both GPU-s are working with other models like mistral, i made this example because my lora training code had the same issues.

**Comment by nepeee** [comment]
Reverting back to nvidia driver 535.154.05 / cuda 12.2 seems to fixed the issue.

**Comment by ArthurZucker** [comment]
Thanks for providing the solution
