### ISSUE TITLE
ImportError: cannot import name 'is_g2p_en_available' from 'transformers.utils' (/usr/local/lib/python3.10/dist-packages/transformers/utils/__init__.py)

### ISSUE THREAD

**Issue by kli017** [huggingface/transformers#28467]
### System Info

env: colab
python=3.10
trasformers=4.37.0.dev0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi, I was run the peft_bnb_whisper_large_v2_training.ipynb from peft project. Everything is good till I met the error when I run the code `import evaluate`. I also try transformers=4.27.4, 4.33,1 and 4.36.2 and get the same error.

### Expected behavior

Anyone can help?

**Comment by ArthurZucker** [comment]
I don't know which section this is, but thefunction is defined here: 
https://github.com/huggingface/transformers/blob/07f5cdcac14b672ea6934b16da432518717f5b74/src/transformers/utils/import_utils.py#L448

it was merged to transformers last week, so can't be there for earlier versions. Can you share a small reproducer?

**Comment by lz039** [comment]
I have the same problem following this example: https://github.com/huggingface/notebooks/blob/main/examples/image_classification.ipynb

at AutoImageProcessor.from_pretrained(model_checkpoint)

with transformers 4.37.1
