### ISSUE TITLE
Error reported when running ''run_language_modeling.py" file

### ISSUE THREAD

**Issue by XIN-von-SUN** [huggingface/transformers#2846]
# 🐛 Bug

## Information

Model I am using (Bert and RoBerta):

Language I am using the model on (English).

The problem arises when using:
* [ ] the official example scripts: (give details below)
I followed the tutorial of how to fine tuning the Bert model on own corpus data, and used recommended corpus 'wiki-text-2' corpus to fine tune the Bert Model. 
However there is always an error appears: "RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at ../aten/src/THNN/generic/ClassNLLCriterion.c:97". 
Thus I am not sure are there something wrong with the "run_language_modeling.py" file, because I did do any change of the original code and used recommended wiki corpus. Could you help me check this error?

* [ ] my own modified scripts: (give details below)
None

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)
Fine tuning the language model of Bert on our own customer corpus data.

## To reproduce

1.
2.
3.

## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by LysandreJik** [comment]
Hi, this is probably due to a version mismatch. Can you update your repository to be on the same version than the script's ? 

If it's `run_language_modeling` (was `run_lm_finetuning` up until very recently), that would be version 2.4.1 (safe, but the script may have evolved a bit since the release 13 days ago) or `master` (safer, should work 100%).
