### ISSUE TITLE
add support for custom pipeline

### ISSUE THREAD

**Issue by not-lain** [huggingface/transformers#28487]
### Feature request

is it possible to add a support for custom pipelines.
something like this 
```
| - config.json
| - custom_config.py
| - custom_architecture.py
| - custom_pipeline.py
```

### Motivation

i was following this documentation https://huggingface.co/docs/transformers/add_new_pipeline and i can't make it workout 
it's also pointing out at the following custom pipeline `sgugger/finetuned-bert-mrpc` which i checked all the previous commits and nothing seems to workout.
also it should be a good idea since adding support to all the models directly to the transformers library will bloat the library so i hope this might be taken into consideration.

### Your contribution

i will help out if possible.

**Comment by not-lain** [comment]
also it would be cool to use something like this : 
```python
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("custom", model="model_id", trust_remote_code=True)
```

**Comment by amyeroberts** [comment]
Hi @not-lain, thanks for raising this! 

You might be interested in [using tools](https://huggingface.co/docs/transformers/transformers_agents#tools), which you can [define and use from the hub](https://huggingface.co/docs/transformers/custom_tools). 

With regards to things not working, could you open a new issue following the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) including details about the running environment and the errors encountered?

**Comment by not-lain** [comment]
@amyeroberts although it is interesting to find about tools but what i'm trying to adress that 
* pipeline doesn't work for custom model architectures on the hub [ feature requested] 
* the documentation says you can only work with a new pipeline if you add it to the transformers github repo (which will bloat the library on the long run)

**Comment by not-lain** [comment]
@amyeroberts, i found the mistake 
i needed to call the model as : 
```python
from transformers import pipeline

classifier = pipeline(model="sgugger/test-dynamic-pipeline", trust_remote_code=True)
```
not as:
```python
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-classification", model="sgugger/test-dynamic-pipeline")
```
i will close this issue
