### ISSUE TITLE
[AutoGPTQ] The notebook tutorial of AutoGPTQ is not working.

### ISSUE THREAD

**Issue by DjangoPeng** [huggingface/transformers#28490]
### System Info

System Info:

- `transformers` version: 4.37.0.dev0
- Platform: Linux-4.4.0-210-generic-x86_64-with-glibc2.23
- Python version: 3.11.5
- Huggingface_hub version: 0.20.1
- Safetensors version: 0.4.0
- Accelerate version: 0.26.1
- Accelerate config:    not found
- PyTorch version (GPU): 2.1.2+cu121 (True)

### Who can help?

@SunMarc and @younesbelkada

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The official notebook introduced by [AutoGPTQ docs](https://huggingface.co/docs/transformers/quantization#autogptq) is not working after upgrading Transformers and dependencies.

I estimate that this should be an incompatible issue caused by the update of `BuilderConfig`. It can be easily reproduced in Google Colab [here](https://colab.research.google.com/drive/1_TIrmuKOFhuRRiTWN94iLKUFu6ZX4ceb?usp=sharing).

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-3-f66cf2cc3929>](https://localhost:8080/#) in <cell line: 14>()
     12 
     13 tokenizer = AutoTokenizer.from_pretrained(model_id)
---> 14 quant_model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=quantization_config, device_map='auto')

9 frames
[/usr/local/lib/python3.10/dist-packages/datasets/builder.py](https://localhost:8080/#) in _create_builder_config(self, config_name, custom_features, **config_kwargs)
    590             builder_config = self.builder_configs.get(config_name)
    591             if builder_config is None and self.BUILDER_CONFIGS:
--> 592                 raise ValueError(
    593                     f"BuilderConfig '{config_name}' not found. Available: {list(self.builder_configs.keys())}"
    594                 )

ValueError: BuilderConfig 'allenai--c4' not found. Available: ['en', 'en.noblocklist', 'en.noclean', 'realnewslike', 'multilingual', 'af', 'am', 'ar', 'az', 'be', 'bg', 'bg-Latn', 'bn', 'ca', 'ceb', 'co', 'cs', 'cy', 'da', 'de', 'el', 'el-Latn', 'en-multi', 'eo', 'es', 'et', 'eu', 'fa', 'fi', 'fil', 'fr', 'fy', 'ga', 'gd', 'gl', 'gu', 'ha', 'haw', 'hi', 'hi-Latn', 'hmn', 'ht', 'hu', 'hy', 'id', 'ig', 'is', 'it', 'iw', 'ja', 'ja-Latn', 'jv', 'ka', 'kk', 'km', 'kn', 'ko', 'ku', 'ky', 'la', 'lb', 'lo', 'lt', 'lv', 'mg', 'mi', 'mk', 'ml', 'mn', 'mr', 'ms', 'mt', 'my', 'ne', 'nl', 'no', 'ny', 'pa', 'pl', 'ps', 'pt', 'ro', 'ru', 'ru-Latn', 'sd', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'st', 'su', 'sv', 'sw', 'ta', 'te', 'tg', 'th', 'tr', 'uk', 'und', 'ur', 'uz', 'vi', 'xh', 'yi', 'yo', 'zh', 'zh-Latn', 'zu']
```

### Expected behavior

Fix and identify the root cause.

**Comment by younesbelkada** [comment]
cc @SunMarc - let me know if you want me to have a look at this one

**Comment by ylsung** [comment]
I got the same issue too.

**Comment by SunMarc** [comment]
Hi @DjangoPeng, this is due to a breaking change in datasets library. See related [thread](https://huggingface.co/datasets/allenai/c4/discussions/7).The issue will be fixed after this [PR](https://github.com/huggingface/optimum/pull/1646) is merged (need to install optimum from source) and I recommend you installing the latest version of datasets. The building time should be faster with it.

**Comment by DjangoPeng** [comment]
SGTM.

Thanks for your reply. :)

**Comment by Aisuko** [comment]
I hit an issue( `... can not find xxx on aws3`) when I use `wikitext2 `.  Here, I'd like to append more options for the datasets: [‘wikitext2’,‘c4’,‘c4-new’,‘ptb’,‘ptb-new’]. All these datasets are used in GPTQ paper. So, it is ok to use it. I change to `c4-new` and it works well. 

Source:
https://huggingface.co/docs/transformers/v4.33.0/en/main_classes/quantization#transformers.GPTQConfig.dataset
