### ISSUE TITLE
PreTrainedEncoderDecoder does not work for LSTM 

### ISSUE THREAD

**Issue by pruksmhc** [huggingface/transformers#2849]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):
If we want to have a BERT-based encoder and LSTM encoder, that is not currently possible with the current huggingface implementation, mostly because torch.nn.LSTM does not contain a config class variable. 

## Stack Trace 
  File "/beegfs/yp913/anaconda3/envs/jiant_new/lib/python3.6/site-packages/transformers/modeling_encoder_decoder.py", line 349, in from_pretrained
    model = super().from_pretrained(*args, **kwargs)
  File "/beegfs/yp913/anaconda3/envs/jiant_new/lib/python3.6/site-packages/transformers/modeling_encoder_decoder.py", line 153, in from_pretrained
    decoder.config.is_decoder = True
  File "/beegfs/yp913/anaconda3/envs/jiant_new/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'LSTM' object has no attribute 'config'

## To reproduce

You can reproduce this by:
import transformers
from transformers.modeling_encoder_decoder import  Model2LSTM
model =  Model2LSTM.from_pretrained("roberta-large", decoder_config={"hidden_size":512, "input_size":1024, "num_layers": 2})

(When you initialize Model2LSTM like the above it runs into a separate error. I believe a ** is missing from the Model2LSTM decoder LSTM initialization).

**Comment by LysandreJik** [comment]
This is more of a feature request than a bug, really. We currently support only a select number of transformer architectures as encoders and decoders. We plan to improve the encoder-decoder architectures in the future.

**Comment by pruksmhc** [comment]
I put this as a bug because the code as-is does not hint that Model2LSTM does not work. 
https://github.com/huggingface/transformers/blob/90ab15cb7a8fcf8bf58c05453ddf1aa6a4fa00c1/src/transformers/modeling_encoder_decoder.py
It would be great to say that LSTM is not currently supported there.

**Comment by LysandreJik** [comment]
Indeed, my initial comment was a mistake. I'm looking into it now.
