### ISSUE TITLE
remote tokenizers trust remote code prompt doesn't not work as expected

### ISSUE THREAD

**Issue by mzbac** [huggingface/transformers#28501]
### System Info

transformers: 4.36.2

### Who can help?

@ArthurZucker

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. use `AutoTokenizer.from_pretrained('Qwen/Qwen-1_8B')
2. The tokenizer failed to load and threw an error. The tokenizer class was not found, and it didn't prompt the user to allow trust for remote code.
3. Delete the `tokenizer_class` setting in [config.jso](https://huggingface.co/Qwen/Qwen-1_8B/blob/main/config.json#L30)n and [tokenizer_config.json](https://huggingface.co/Qwen/Qwen-1_8B/blob/main/tokenizer_config.json)
4. After that, when using `AutoTokenizer.from_pretrained('Qwen/Qwen-1_8B')`, it prompts the user to trust remote code. However, instead of asking once, it prompts the user to confirm three times.

### Expected behavior

The `AutoTokenizer.from_pretrained` function should prompt the user whether they want to enable trust remote code only once when the user did not pass the `trust_remote_code` parameter.

**Comment by ArthurZucker** [comment]
Hey, `AutoTokenizer.from_pretrained('Qwen/Qwen-1_8B', trust_remote_code = True)` should be used as this model is not natively supported

**Comment by mzbac** [comment]
> Hey, `AutoTokenizer.from_pretrained('Qwen/Qwen-1_8B', trust_remote_code = True)` should be used as this model is not natively supported

@ArthurZucker Thanks for the reply. Yeah, explicitly passing trust_remote_code works. However, it should prompt the user in terminal to ask whether they want to trust the remote code if they didn't explicitly pass trust_remote_code. As I understand it, it should behave similarly to AutoModelForCausalLM.from_pretrained.

**Comment by ArthurZucker** [comment]
Yes agree with you!

**Comment by Rocketknight1** [comment]
Hi @mzbac, I made a PR last week that specifically deals with this issue here: #28419.

Can you install `transformers` from `main` with `pip install --upgrade git+https://github.com/huggingface/transformers.git` and let me know if you're still being asked three times?

**Comment by mzbac** [comment]
Thanks, @Rocketknight1. I can confirm that using the main branch's transformers resolves the issue.

**Comment by Rocketknight1** [comment]
Cool! That fix will be included in our next release. I'm going to close this issue for now, but feel free to reopen it if you encounter any other issues with loading custom code tokenizers.
