### ISSUE TITLE
Tokenizer should be serializable

### ISSUE THREAD

**Issue by hk6an6** [huggingface/transformers#28502]
### System Info

- transformers.__version__: '4.36.1'
- platform: macOS 14.2.1 (23C71)
- Python version: Python 3.11.6

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-distilroberta-base-v1', device='mps')
model.max_seq_length = 384
model.save('my_path')
```

### Expected behavior

`transformers/tokenization_utils_base.py` fails to serialize the local variable `tokenizer_config`. and breaks `model.save`. `model.save` should succeed.

**Comment by hk6an6** [comment]
It seems the problem goes away if I change from `paraphrase-distilroberta-base-v1` to `paraphrase-distilroberta-base-v2`. Could it be that the tokenizer_config for v1 is incompatible with json.dumps?

**Comment by ArthurZucker** [comment]
Hey! This seems to be related to `sentence-transfromers`, as tokenizers are serializable. 
Could you provide the stactrace and open an issue on the [sentence-transformers](https://github.com/UKPLab/sentence-transformers) repo?

**Comment by hk6an6** [comment]
[stacktrace.txt](https://github.com/huggingface/transformers/files/13959334/stacktrace.txt)

Keeping my word, this is the stack trace. I'll cose this ticket and open one in the sentence-transformers repo.

**Comment by hk6an6** [comment]
https://github.com/UKPLab/sentence-transformers/issues/2418
