### ISSUE TITLE
AttributeError: module 'transformers_modules.Qwen-72B-Chat.tokenization_qwen' has no attribute 'QWenTokenizer'

### ISSUE THREAD

**Issue by pydaxing** [huggingface/transformers#28519]
### System Info

AttributeError: module 'transformers_modules.Qwen-72B-Chat.tokenization_qwen' has no attribute 'QWenTokenizer'

### Who can help?

AttributeError: module 'transformers_modules.Qwen-72B-Chat.tokenization_qwen' has no attribute 'QWenTokenizer'

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

AttributeError: module 'transformers_modules.Qwen-72B-Chat.tokenization_qwen' has no attribute 'QWenTokenizer'

Transformers==4.34.0

### Expected behavior

AttributeError: module 'transformers_modules.Qwen-72B-Chat.tokenization_qwen' has no attribute 'QWenTokenizer'

**Comment by amyeroberts** [comment]
Hi @pydaxing, thanks for raising an issue! 

So that we can best help you, could you make sure to follow the issue template and provide: 
* The running environment: run `transformers-cli env` in the terminal and copy-paste the output
* A minimal code reproducer
* The full error traceback

**Comment by hynnn** [comment]
Hi, how did you solve it? I have the same bug

**Comment by PineappleWill** [comment]
I have the same bug, how did you solve it?
