### ISSUE TITLE
Exception in inference when using the pipeline with output_scores=True to get logits

### ISSUE THREAD

**Issue by andersonm-ibm** [huggingface/transformers#28524]
### System Info

- `transformers` version: 4.29.1
- Python version: 3.10.13
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.0+cu117 (True)

### Who can help?

 @Narsil

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Easily reproduced by [using the pipeline with output_scores=True](https://gist.github.com/andersonm-ibm/d8baeea66afca89cefebc108f1ce08f3)

Results in:

```
test_transformers_bug.py:27: in <module>
    for out in pipe(KeyDataset(dataset, "text")):
/home/mayaa/miniconda3/envs/fme/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py:124: in __next__
    item = next(self.iterator)
/home/mayaa/miniconda3/envs/fme/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py:125: in __next__
    processed = self.infer(item, **self.params)
/home/mayaa/miniconda3/envs/fme/lib/python3.10/site-packages/transformers/pipelines/base.py:1025: in forward
    model_outputs = self._forward(model_inputs, **forward_params)
/home/mayaa/miniconda3/envs/fme/lib/python3.10/site-packages/transformers/pipelines/text_generation.py:264: in _forward
    out_b = generated_sequence.shape[0]
E   AttributeError: 'GreedySearchEncoderDecoderOutput' object has no attribute 'shape'
```

### Expected behavior

Pipeline should handle the case where the model output is a `GreedySearchEncoderDecoderOutput `and not a simple tensor without exceptions, like in [the example](https://gist.github.com/andersonm-ibm/766d4892c92310a7889b2b3dfdc8ff44#file-model_generate_with_logits_output-py) .

**Comment by Narsil** [comment]
@amyeroberts  For reference.

This is totally OK, pipelines are not supposed to support every option models do. Use the example code if you want more control over the generation.

Closing for now since this is normal behavior.
