### ISSUE TITLE
A named Peft Model doesn't work with resume_from_checkpoint=True

### ISSUE THREAD

**Issue by chenbin11200** [huggingface/transformers#28531]
### System Info

transformers==4.36.2
peft==0.5.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Hi @muellerzr and @pacman100,

It seem like if I try to resume a lora training by using 
```
trainer.train(resume_from_checkpoint=True)
```
it fails with the following error:
```
ValueError: Can't find a valid checkpoint at /my_output_dir/checkpoint-300
```
By checking the code, I figured out the resuming proccess is stopped  by the following assert in `Trainer._load_from_checkpoint` 
```
if not (
            any(
                os.path.isfile(f)
                for f in [
                    weights_file,
                    safe_weights_file,
                    weights_index_file,
                    safe_weights_index_file,
                    adapter_weights_file,
                    adapter_safe_weights_file,
                ]
            )
            or is_fsdp_ckpt
        ):
            raise ValueError(f"Can't find a valid checkpoint at {resume_from_checkpoint}")
```
Since I initialize the PeftModel with a adapter name, which is used to manage my adapters.
```
peft_model = get_peft_model(model=base_model,
                                       peft_config=peft_config,
                                       adapter_name='my_lora_model_name',
```
In this case, the `adapter_config.json` and `adapter_model.bin` files will be saved in `/my_output_dir/checkpoint-300/my_lora_model_name` instead of `/my_output_dir/checkpoint-300` directly. That's why the ValueError is raised.

I am not sure whether it is a known issue, and the proper way to fix it? Or I have to write my own PeftTrainer to handle this issue?

Thank you in advance for your support.

Best regards.

### Expected behavior

Resume the training with a named peft model is supported.

**Comment by chenbin11200** [comment]
A PR is attached, if it is necessary: https://github.com/huggingface/transformers/pull/28547

**Comment by amyeroberts** [comment]
Also cc @younesbelkada for PEFT

**Comment by younesbelkada** [comment]
Thanks @amyeroberts @chenbin11200 - the PR makes sense to me ! I left a single comment
