### ISSUE TITLE
Download reconfiguration

### ISSUE THREAD

**Issue by LOVE-YOURSELF-1** [huggingface/transformers#28545]
### Feature request

Download reconfiguration

### Motivation

Separate out the download of the pretrained function for model、configuration and tokenizer.

### Your contribution

Do you think it is necessary？

**Comment by amyeroberts** [comment]
Hi @LOVE-YOURSELF-1, thanks for opening this feature request! 

If you want to download a specific file from the hub, you can use `hf_hub_download` from `huggingface_hub`. 

If you are using the auto classes, they will only download what's necessary. For example: 

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
```

will only download the files for the tokenizer, not the model weights.

**Comment by LOVE-YOURSELF-1** [comment]
If we have multiple download sources，do you think it is necessary to bulit a new class named downloader?

**Comment by amyeroberts** [comment]
@LOVE-YOURSELF-1 Could you explain what you mean in more detail? What do you mean by 'multiple download sources'?

**Comment by LOVE-YOURSELF-1** [comment]
https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L3258
Can we rewrite the code about download（config，tokenizer and model）?
rebuilt a class named downloader, which can accomplish download, (from local and hugging hub)

**Comment by amyeroberts** [comment]
@LOVE-YOURSELF-1  There's a plan to harmonise how e.g. loading and downloading shards is handled across libraries which will also account for e.g. local versus downloading from the hub. 

I don't see the reason for having a downloader class which handles downloading these all files - it's bundling together responsibilities making the scope of the class ill-defined. What problem would this be solving?

**Comment by LOVE-YOURSELF-1** [comment]
As you said, i want to integrate downloading and loading. It can be rewritten in downloader.py.

**Comment by amyeroberts** [comment]
@LOVE-YOURSELF-1 Any contributor is welcome to open a PR to demonstrate and new feature or refactor. As this isn't something we or the community are requesting, it's up to you to define the feature you'd like to add. Once there's a clear diff or feature description, then we'll be able to help.
