### ISSUE TITLE
LLM fine-tuning with deepspeed

### ISSUE THREAD

**Issue by vallabh001** [huggingface/transformers#28541]
I was trying to fine-tune llama2 by referring this [blog](https://www.philschmid.de/instruction-tune-llama-2l), but the training time is very high (in days). So, I was thinking of using deepspeed optimization for the training process. However, there is no proper documentation for fine-tuning llm's using deepspeed. 

I executed the command below to start training, but encountered an error. I have single A100 40gb GPU.
`torchrun --num_gpus=1 --nnodes 1 --nproc_per_node 1 llm_training.py --deepspeed "ds_zero2_no_offload.json" --ddp_find_unused_parameters False
`

Error

`RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the forward function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple checkpoint functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 447 with name base_model.model.model.layers.31.mlp.down_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.`

**Comment by NielsRogge** [comment]
There's the Alignment Handbook which uses Deepspeed to train any decoder LLM like Llama or Mistral on multiple GPUs: https://github.com/huggingface/alignment-handbook. It includes scripts for both supervised fine-tuning (SFT) and human preference fine-tuning using DPO (direct preference optimization): https://github.com/huggingface/alignment-handbook/tree/main/scripts.
