### ISSUE TITLE
Pipeline batching with ZeroShotImageClassificationPipeline outputs less items per iteration than expected

### ISSUE THREAD

**Issue by ryan-caesar-ramos** [huggingface/transformers#28548]
### System Info

- `transformers` version: 4.36.2
- Platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.35
- Python version: 3.11.5
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.0
- Accelerate version: 0.24.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.1+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@Narsil 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers import pipeline
from datasets import load_dataset
import numpy as np
from transformers.pipelines.pt_utils import KeyDataset

pipe = pipeline('zero-shot-image-classification', model='openai/clip-vit-base-patch16', device=0)
dataset = load_dataset('mnist', split='test')
for out in pipe(KeyDataset(dataset, "image"), candidate_labels=range(10), batched=True, batch_size=1024):
  break

print(len(out))
```

### Expected behavior

I would have assumed that `out` would have 10 classes * 1024 images in the batch = 10240 items in it, but it only has 10. Maybe I'm misinterpreting what batching with pipelines does?

**Comment by Narsil** [comment]
Batch_size is transparent. The model will run the inference batched, but the pipeline still outputs results one by one, meaning you can modify the batch_size according to the actual hardware you are using without actually needing to unpack results manually (it also allows running next batch, before you even finished unpacking the results manually, leading to better GPU usage.

**Comment by ryan-caesar-ramos** [comment]
Thanks! That clears things up
