### ISSUE TITLE
Cohere embed - Sagemaker deploy - Should have a `model_type` key in its config.json

### ISSUE THREAD

**Issue by pthd** [huggingface/transformers#28560]
### System Info

- `transformers` version: 4.33.2
- Platform: macOS-14.2.1-arm64-arm-64bit
- Python version: 3.9.16
- Huggingface_hub version: 0.18.0
- Safetensors version: 0.4.0
- Accelerate version: 0.23.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Who can help?

@philschmid 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

deployed according to 

https://huggingface.co/Cohere/Cohere-embed-multilingual-v3.0?sagemaker_deploy=true

W-Cohere__Cohere-embed-mult-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ValueError: Unrecognized model in /.sagemaker/mms/models/Cohere__Cohere-embed-multilingual-v3.0. Should have a `model_type` key in its config.json, or contain one of the following strings in its name:

### Expected behavior

deployment succeeds but invocation raises error

```
W-Cohere__Cohere-embed-mult-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ValueError: Unrecognized model in /.sagemaker/mms/models/Cohere__Cohere-embed-multilingual-v3.0. Should have a `model_type` key in its config.json, or contain one of the following strings in its name:
```

**Comment by amyeroberts** [comment]
Hi @pthd, thanks for raising an issue! 

I'd suggest opening a discussion on the [model's hub page](https://huggingface.co/Cohere/Cohere-embed-multilingual-v3.0). As it looks like it might be related to the model itself and the owners of the repo will be able to address that.
