### ISSUE TITLE
Clarify usage / implementation of padding for SigLIP model processor

### ISSUE THREAD

**Issue by skysyk** [huggingface/transformers#28569]
### Feature request

Change the implementation of `SiglipProcessor` to use the global default behavior for `padding` of `False` or update the documentation to indicate the usage is different and defaults to `'max_length'` if the `padding` argument is not provided.

### Motivation

In the HF documentation for padding (both the docs as well as the function comments for the processor class), the default behavior (argument) is described to be `False` or `'do_not_pad'`. For the `SiglipProcessor`, `max_length` is the default behavior implemented in [code](https://github.com/huggingface/transformers/blob/98dda8ed03ac3f4af5733bdddaa1dab6a81e15c1/src/transformers/models/siglip/processing_siglip.py#L53) while the [example in the docs](https://huggingface.co/docs/transformers/main/en/model_doc/siglip#using-the-model-yourself) omits the padding argument. This is at odds with the overall documentation as well as behavior / usage examples provided in similar models such as CLIP (where explicitly `padding=True` in the usage example) and could give the wrong impression upon first glance that padding is not used for SigLIP.

### Your contribution

Opening this issue to discuss a clarification / improvement. I can help implement the preferred solution.

**Comment by NielsRogge** [comment]
Good point. cc @ArthurZucker - I added this to make sure people use `max_length` as the pre-trained models use this.

I guess it would be better to explicitly pass `padding="max_length"` so that this is more explicit and users have the choice.

**Comment by skysyk** [comment]
Thank you!
