### ISSUE TITLE
Feature Request: Expose an Args to Set Prefetch Factor in Trainer

### ISSUE THREAD

**Issue by uygnef** [huggingface/transformers#28576]
### Feature request

Currently, the trainer does not allow users to set the prefetch factor as an argument from the training script. 

### Motivation

This can be a limitation when training large models, especially when the data is being fetched from a remote server, as the loading speed can become a bottleneck due to slow data download for the next partition.

### Your contribution

I can commit a PR

**Comment by amyeroberts** [comment]
Hi @uygnef, thanks for raising an issue!

There is a related PR open: #28498 cc @muellerzr @pacman100

**Comment by uygnef** [comment]
> Hi @uygnef, thanks for raising an issue!
> 
> There is a related PR open: #28498 cc @muellerzr @pacman100

oh, good job!
