### ISSUE TITLE
data_collator in examples/pytorch/language-modeling/run_clm.py

### ISSUE THREAD

**Issue by pierowu** [huggingface/transformers#28573]
### System Info

According to the script, the trainer use dafault_data_collator to model causal language modelling.
https://github.com/huggingface/transformers/blob/98dda8ed03ac3f4af5733bdddaa1dab6a81e15c1/examples/pytorch/language-modeling/run_clm.py#L604
Shouldn't we use DataCollatorForLanguageModeling to shift input and output by 1 token instead? It seems that dafault_data_collator can't achieve this goal.
 @ArthurZucker   @younesbelkada  @ArthurZucker @muellerzr and @pacman100
Thank you for answering!

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Same as examples/pytorch/language-modeling/run_clm.py

### Expected behavior

Correctlt train causal language model.

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!

Thanks!
