### ISSUE TITLE
This model has one file that has been marked as unsafe. [training_args.bin]

### ISSUE THREAD

**Issue by rizwan-ai** [huggingface/transformers#28580]
### System Info

**Framework versions**

- Transformers 4.36.2
- Pytorch 2.1.2+cpu
- Datasets 2.16.1
- Tokenizers 0.15.0

This model has one file that has been marked as unsafe.
[training_args.bin](https://huggingface.co/rizwan-ai/distilbert-base-uncased-finetuned-emotion/blob/main/training_args.bin)

### Git LFS Details

* **SHA256:** d672df2806e4b013fbfdf9d995526b2c4e4a7d56a8b84b77b1d6213241ea11f0
* **Pointer size:** 129 Bytes
* **Size of remote file:** 4.73 kB

#### Detected Pickle imports (9)

* "transformers.training_args.TrainingArguments",
* "transformers.training_args.OptimizerNames",
* "transformers.trainer_utils.SchedulerType",
* "accelerate.state.PartialState",
* "torch.device",
* "transformers.trainer_utils.HubStrategy",
* "accelerate.utils.dataclasses.DistributedType",
* "__builtin__.getattr",
* "transformers.trainer_utils.IntervalStrategy"

@ArthurZucker @younesbelkada @pc

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://huggingface.co/rizwan-ai/distilbert-base-uncased-finetuned-emotion

### Expected behavior

How to fix it?

**Comment by younesbelkada** [comment]
Hi @rizwan-ai 
If you uploaded the files by yourself, in theory it should be safe, however we advise you to double check things before running anything. Please refer to this documentation page: https://huggingface.co/docs/hub/security-pickle for more details
