### ISSUE TITLE
How to find or create the `model_state_dict.bin` file for the `convert_llava_weights_to_hf.py` script

### ISSUE THREAD

**Issue by isaac-vidas** [huggingface/transformers#28597]
Hi @younesbelkada,

Following up on the [fix to the LLaVA convert script](https://github.com/huggingface/transformers/pull/28570) and thanks for all the help with the PR!

I encountered some issue with the convert script and wanted to ask about the recommended way to create the `model_state_dict.bin` file specified here: https://github.com/huggingface/transformers/blob/772307be7649e1333a933cfaa229dc0dec2fd331/src/transformers/models/llava/convert_llava_weights_to_hf.py#L74

In order to create the `model_state_dict.bin` I tried something like the following with the original https://github.com/haotian-liu/LLaVA code:
```python
import torch
from llava.model.language_model.llava_llama import LlavaLlamaForCausalLM

# load model
kwargs = {"device_map": "auto", "torch_dtype": torch.float16}
model = LlavaLlamaForCausalLM.from_pretrained("liuhaotian/llava-v1.5-7b", low_cpu_mem_usage=True, **kwargs)

# load vision tower
model.get_vision_tower().load_model()

# Save state dict
torch.save(model.state_dict(), "tmp/hf_models/llava-v1.5-7b/model_state_dict.bin")
```

It works but when I used the convert script I had to make the following changes: 
* Remove keys that ended with `.inv_freq` (e.g. `language_model.model.layers.0.self_attn.rotary_emb.inv_freq`)
* Comment out the update to the `model.config.vocab_size` and `model.config.text_config.vocab_size` with the `pad_shape` here: https://github.com/huggingface/transformers/blob/772307be7649e1333a933cfaa229dc0dec2fd331/src/transformers/models/llava/convert_llava_weights_to_hf.py#L96-L97 otherwise, when I would try to load the converted model, it will error with the following:
    ```python
    from transformers import AutoProcessor, LlavaForConditionalGeneration
    model_id = "Shopify/llava-1.5-7b"

    model = LlavaForConditionalGeneration.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
    ).to(0)
    ```
    ```console
    ValueError: Trying to set a tensor of shape torch.Size([32064, 5120]) in "weight" (which has shape torch.Size([32128, 5120])), this look incorrect.
    ```

Am I doing something wrong when I create the `model_state_dict.bin` file or am I missing something else?

Thanks again in advance.

**Comment by younesbelkada** [comment]
Hi @isaac-vidas 
Thanks very much for your message, I think that these [two lines](https://github.com/huggingface/transformers/blob/772307be7649e1333a933cfaa229dc0dec2fd331/src/transformers/models/llava/convert_llava_weights_to_hf.py#L96-L97) seems wrong, does replacing them with `model.get_input_embeddings().weight.shape[0]` fixes the issue?

**Comment by aismlv** [comment]
You could also just remove these two lines as `resize_token_embeddings` method applies the changes to the config already

P.S. Also had to remove `self_attn.rotary_emb.inv_freq` keys to perform the conversion from the checkpoint uploaded to the hub

**Comment by isaac-vidas** [comment]
Added a PR related to the discussion above https://github.com/huggingface/transformers/pull/28617
