### ISSUE TITLE
Trainer is DP? support DDP？

### ISSUE THREAD

**Issue by ciaoyizhen** [huggingface/transformers#28595]
### Feature request

Is the trainer DDP or DP? If it is DDP, why do I train with multiple graphics cards, and the graphics card memory consumed on cuda-0 is much larger than other graphics cards. Or is it that when I increase per_device_train_batch_size, the cuda-0 card will exceed the graphics card memory, and then it will cut the model parameters to other cards by itself? Or do I need to set any parameters? Just give an example. I ask ChatGPT. He answer me that Trainer is DP.

### Motivation

DDP is more useful than DP.

### Your contribution

If supported. Could you tell me how to use DDP?

**Comment by ciaoyizhen** [comment]
Can it be DDP by adding fsdp="shard_grap_op" of TrainingArguments and fsdp=""full_shard" be DP?

**Comment by amyeroberts** [comment]
Hi @ciaoyizhen, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

We suggest searching in the forums first to see if any related questions have been asked e.g. https://discuss.huggingface.co/t/which-data-parallel-does-trainer-use-dp-or-ddp/16021/2.
