### ISSUE TITLE
DistilBERT distilbert-base-cased failed to load

### ISSUE THREAD

**Issue by anshoomehra** [huggingface/transformers#2861]
**Issue** 
DistilBERT **distilbert-base-cased** failed to load. _Please note, 'distilbert-base-uncased' works perfectly fine._

**Error Message**
OSError: Model name 'distilbert-base-cased' was not found in tokenizers model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad, distilbert-base-german-cased, distilbert-base-multilingual-cased). We assumed 'distilbert-base-cased' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.

**Model I am using** : distilbert-base-cased

**Language** : English

**The problem arises when using below code**
```
MODELS = [(DistilBertModel, DistilBertTokenizer, 'distilbert-base-cased')]

for model_class, tokenizer_class, pretrained_weights in MODELS:
    # Load pretrained model/tokenizer
    tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
    model = model_class.from_pretrained(pretrained_weights)
```

**Environment info**
Python 3.6.9
ipykernel==5.1.3
ipython==7.11.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
jupyter-http-over-ws==0.0.7
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
matplotlib==3.1.2
numpy==1.18.1
scipy==1.4.1
tensorboard==2.1.0
tensorflow-estimator==2.1.0
tensorflow-gpu==2.1.0
tokenizers==0.0.11
torch==1.4.0
tornado==6.0.3
tqdm==4.42.1
traitlets==4.3.3
transformers==2.4.1

**Comment by cronoik** [comment]
Should be fixed with ee5a6856caec83e7f2f305418f3199b87ea6cc2d. I can execute your code without an error with the latest version from github.

**Comment by anshoomehra** [comment]
> Should be fixed with [ee5a685](https://github.com/huggingface/transformers/commit/ee5a6856caec83e7f2f305418f3199b87ea6cc2d). I can execute your code without an error with the latest version from github.

I appreciate the prompt response.  **I didn't compile from git, rather installed via** 

`pip install transformer --upgrade`

It upgraded to transformers==2.4.1 -- post-upgrade though the error code changed below:

`ValueError: Can't find a vocabulary file at path /root/.cache/torch/transformers/37cc1eaaea18a456726fc28ecb438852f0ca1d9e7d259e6e3747ee33065936f6'. To load the vocabulary from a Google pretrained model use tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`

**Comment by cronoik** [comment]
The mentioned commit is not part of 2.4.1. You have to wait for the next release or pull transformers from git.

**Comment by anshoomehra** [comment]
Ok, I will pull from the git for the time being. Thank you!

**Comment by cronoik** [comment]
Please close the issure when your problem is solved.

**Comment by anshoomehra** [comment]
We can close this since we have a workaround, and the team is aware of the issue to be rolled out in the next release. Thanks!!

**Comment by LysandreJik** [comment]
v2.5.0 was released a few days ago, `distilbert-base-cased` is now accessible via the pip release! :)

**Comment by jianlins** [comment]
The vocab file is missing here: 
https://huggingface.co/distilbert-base-cased#list-files
While the auto-downloaded model has one.

**Comment by bpben** [comment]
I'm still having the same problem.  Using transformers version 2.8.0, neither `distilbert-base-cased` or `distilbert-base-uncased` are available.  I also ran the following command:

```
import pytorch_pretrained_bert as ppb
assert 'distilbert-base-uncased' in ppb.modeling.PRETRAINED_MODEL_ARCHIVE_MAP
```

Which results in `AssertionError`.  Any thoughts on what might be going on here?

**Comment by cronoik** [comment]
Are you really using the `transformers` [1] package? The code you have showed contains only the `pytorch_pretrained_bert` [2] package which doesn't contain distilbert. While `pytorch_pretrained_bert` [2] and `transformers` [1] are both packages from huggingface, they are not the same. Please use the `transformers` package [1].

[1] https://pypi.org/project/transformers/
[2] https://pypi.org/project/pytorch-pretrained-bert/#description

**Comment by bpben** [comment]
Thanks for the quick reply: I am using transformers, I picked up that code snippet from another issue, must have been for that package. 

I realize what I did wrong: I was using BertTokenizer/BertModel to load, and I should have been using DistilBertTokenizer/DistilBertModel.  It's working now, thanks!
