### ISSUE TITLE
Bug in GPT NeoX Implementation

### ISSUE THREAD

**Issue by andersonbcdefg** [huggingface/transformers#28613]
### System Info

GPT-Neo-X does not have a "q_proj" module, so the following lines that check for the dtype raise an error.

```
input_dtype = query.dtype
        if input_dtype == torch.float32:
            if torch.is_autocast_enabled():
                target_dtype = torch.get_autocast_gpu_dtype()
            # Handle the case where the model is quantized
            elif hasattr(self.config, "_pre_quantization_dtype"):
                target_dtype = self.config._pre_quantization_dtype
            else:
                target_dtype = self.q_proj.weight.dtype
```

This is in `transformers/src/transformers/models/gpt_neox/modeling_gpt_neox.py`

### Who can help?

text models: @ArthurZucker and @younesbelkada

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Initialize a GPT Neo X model with flash attention
model = AutoModel.from_pretrained(model_name_or_path, attn_implementation="flash_attention_2", torch_dtype=torch.bfloat16)

2. Try to run forward pass. Causes following error: 
AttributeError: 'GPTNeoXFlashAttention2' object has no attribute 'q_proj'

### Expected behavior

The forward pass should work, or at least fail for a reason other than a reference a module that the given model does not actually have

**Comment by younesbelkada** [comment]
Nice catch ! #28645 should fix it
