### ISSUE TITLE
Can `LlamaTokenizerFast` support the argument `add_prefix_space = False`

### ISSUE THREAD

**Issue by hnyls2002** [huggingface/transformers#28622]
### System Info

With `transformers==4.36.2`

It seems the argument `add_prefix_space` is invalid here. 

### Who can help?

@ArthurZucker 

### Reproduction

```
>>> from transformers import LlamaTokenizerFast
>>> tokenizer = LlamaTokenizerFast.from_pretrained("hf-internal-testing/llama-tokenizer", add_prefix_space = False)
>>> tokenizer.tokenize("hello")
['▁hello']
>>> tokenizer.decode(tokenizer.encode("hello"))
'<s> hello'
```

### Expected behavior

Is there a bug, or is it my wrong usage?

**Comment by ArthurZucker** [comment]
Hey, #28010 will add support for thisl.

**Comment by hnyls2002** [comment]
Thanks, I am very excited about this.

**Comment by abdr17** [comment]
Hi @ArthurZucker, I do not understand where to set the flag `add_prefix_space = False`?
