### ISSUE TITLE
ESM Rotary Embedding implementation is not TorchScript safe

### ISSUE THREAD

**Issue by ChenchaoZhao** [huggingface/transformers#28625]
### System Info

This issue is independent of the env. It’s purely about the PyTorch implementation of ESM position embedding

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Load an ESM model from pretrained 
2. To cuda
3. Use ‘torch.jit.trace’

### Expected behavior

It may crash when you trace the model.
Even if it doesn't crash at trace time, when save the model and move the model to a different device and perform inference it will crash with a device error.
The reason is the cached sin and cos are NOT registered as buffers which means pytorch will not know how to move the python attribute when using the ‘to’ method. I would suggest copy and use the llama ROPE implementation.

**Comment by amyeroberts** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
Hi @ChenchaoZhao, I think you're correct - would you be willing to open a PR to fix the issue?

**Comment by ChenchaoZhao** [comment]
Hi @Rocketknight1, sure. Anything else other than the contribution guide I should we aware before making the PR?https://github.com/huggingface/transformers/blob/03cc17775b961d16cc4d0d7ab0c8487120d0b708/CONTRIBUTING.md

**Comment by Rocketknight1** [comment]
Hi @ChenchaoZhao, that guide should cover everything. Just open the PR to transformers and tag me in it + link this issue. And thank you - it's an important fix so it's great that you're willing to handle it!
