### ISSUE TITLE
No, you cannot set a `token` to an `id`. It is the same as `tokenzier.pad_token_id = 0` if `tokenizer.eos_token_id` is `0`

### ISSUE THREAD

**Issue by rafa852** [huggingface/transformers#28626]
No, you cannot set a `token` to an `id`. It is the same as `tokenzier.pad_token_id = 0` if `tokenizer.eos_token_id` is `0`

_Originally posted by @ArthurZucker in https://github.com/huggingface/transformers/issues/26072#issuecomment-1859852130_

**Comment by amyeroberts** [comment]
Hi @rafa852 - what is the issue being raised here?

**Comment by ArthurZucker** [comment]
Closing as there is no answer and no explanation!
