### ISSUE TITLE
Fast tokenizer's time complexity is not linear

### ISSUE THREAD

**Issue by getao** [huggingface/transformers#28629]
### System Info

torch 2.1.2
transformers 4.36.2

### Who can help?

@ArthurZucker 

I'm using the streaming dataloader to train on a large dataset. However, I find some process is usually stuck and finally lead to NCCL timeout After I carefully checked, I found the problem may come from the tokenizer. 

When a batch (I think it is 1000 by default) contains too many tokens (e.g., the batch has a document that is a book and is very long), the tokenization process will be extremely slow. I test the tokenization efficiency for sequences with different lengths and find the time cost is not linear to the sequence length but looks like quadratic. 

Tokenizing a 50k-word sequence costs 0.5s but tokenizing a 500k-word sequence costs 70s (about 140x slower).

I don't know if it is a bug. If it is by design, how should I prevent the tokenizer being stuck by some batches with too many tokens. I think one way is to reduce the batch size (default 1000). Is there any other way?

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoTokenizer
import time

def test_time(test_str):
    a = time.time()
    tokens = tokenizer(test_str)
    b = time.time()
    return b-a

tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.2")
test_str = "I love NLP. " * 100000  # we can change the number to try different lengths
time_cost = test_time(test_str)
print(time_cost)
```

### Expected behavior

Linear time cost increase as the sequence length

**Comment by ArthurZucker** [comment]
Feel free to check this issue (duplicate) #25873

**Comment by ArthurZucker** [comment]
Part of the issue with Llama tokenizer were debugged see here! https://github.com/huggingface/tokenizers/releases/tag/v0.15.2
