### ISSUE TITLE
Qwen2 weights are not there/deleted?

### ISSUE THREAD

**Issue by aliencaocao** [huggingface/transformers#28641]
### System Info

https://huggingface.co/Qwen2/Qwen2-7B-Chat-beta gives a 404, despite the tutorial in https://huggingface.co/docs/transformers/main/model_doc/qwen2 quoting it.
https://huggingface.co/Qwen only has Qwen-1 models.
@ArthurZucker @younesbelkada @stevhliu 

By the way, the docs is inconsistent in the model path. Most uses https://huggingface.co/Qwen2/Qwen2-7B-beta but in docs for the [config class](https://huggingface.co/docs/transformers/main/model_doc/qwen2#transformers.Qwen2Config), it uses https://huggingface.co/Qwen/Qwen2-7B-beta which also does not exist.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Visit https://huggingface.co/Qwen2/Qwen2-7B-Chat-beta

### Expected behavior

Model is there and accessible

**Comment by ArthurZucker** [comment]
cc @JustinLin610 the author of the pull request! Are the weights not publicly available yet? 🤗

**Comment by ArthurZucker** [comment]
Models are [here](https://huggingface.co/collections/Qwen/qwen15-65c0a2f577b1ecb76d786524) just not called `Qwen2` !

**Comment by ArthurZucker** [comment]
Opening a PR now!
