### ISSUE TITLE
How to set stopping criteria in model.generate() when a certain word appear 

### ISSUE THREAD

**Issue by pradeepdev-1995** [huggingface/transformers#28663]
### Feature request

stopping criteria in model.generate() when a certain word appear 

The word I need to stop the generation when found is : [/SENTENCE]
But the model doesn't generate the word itself, instead, it generates the subwords
 [ [/,SEN,TE,NC,E] ] 
like this . 

corresponding ids from the tokenizer are, 
( Id and subword word)
28792 => [
28748 => /
28759 => SEN
2654 => TE
1197 => NC
28793 => E]

so how can i put the condition in **StoppingCriteriaList** that i should stop the generation when the [/SENTENCE] found. 

### Motivation

stopping criteria in model.generate() when a certain word appear 

The word I need to stop the generation when found is : [/SENTENCE]
But the model doesn't generate the word itself, instead, it generates the subwords
 [ [/,SEN,TE,NC,E] ] 
like this . 

corresponding ids from the tokenizer are, 
( Id and subword word)
28792 => [
28748 => /
28759 => SEN
2654 => TE
1197 => NC
28793 => E]

so how can i put the condition in **StoppingCriteriaList** that i should stop the generation when the [/SENTENCE] found. 

### Your contribution

stopping criteria in model.generate() when a certain word appear 

The word I need to stop the generation when found is : [/SENTENCE]
But the model doesn't generate the word itself, instead, it generates the subwords
 [ [/,SEN,TE,NC,E] ] 
like this . 

corresponding ids from the tokenizer are, 
( Id and subword word)
28792 => [
28748 => /
28759 => SEN
2654 => TE
1197 => NC
28793 => E]

so how can i put the condition in **StoppingCriteriaList** that i should stop the generation when the [/SENTENCE] found.

**Comment by amyeroberts** [comment]
Hi, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
