### ISSUE TITLE
Swinv2ForImageClassification often outputs NaN at initialization

### ISSUE THREAD

**Issue by norabelrose** [huggingface/transformers#28675]
### System Info

- `transformers` version: 4.36.2
- Platform: Linux-5.4.0-164-generic-x86_64-with-glibc2.31
- Python version: 3.10.11
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.4.1
- Accelerate version: 0.26.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```py
from transformers import Swinv2Config, Swinv2ForImageClassification
import torch

with torch.inference_mode():
    cfg = Swinv2Config(image_size=56)
    model = Swinv2ForImageClassification(cfg)

    out = model(torch.rand(1, 3, 56, 56))

out.logits
```

### Expected behavior

Should not output NaN; throw an error if the implementation doesn't currently support a certain combination of architectural hyperparameters

**Comment by miguelm-almeida** [comment]
Hi @amyeroberts and everyone! 
Is this issue open for someone to work on? It's the first time I'm contributing to Transformers and I would be happy to help!

**Comment by amyeroberts** [comment]
@miguelm-almeida You're very welcome to work on it!

**Comment by miguelm-almeida** [comment]
Thanks! :)

**Comment by miguelm-almeida** [comment]
Hi @amyeroberts! I believe I have solved this issue. Will open a PR just now.
