### ISSUE TITLE
Issue with finetuning Mixtral w/ deepspeed after new release

### ISSUE THREAD

**Issue by sam-h-bean** [huggingface/transformers#28671]
### System Info

transformers: latest
env: ray + deepspeed on k8s

There seems to be an issue with Mixtral on the latest transformers release that manifests like 

```
RuntimeError: Detected mismatch between collectives on ranks. Rank 4 is running collective:
CollectiveFingerPrint(SequenceNumber=724883, OpType=_ALLGATHER_BASE, TensorShape=[4194305], TensorDtypes=BFloat16, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))),
but Rank 0 is running collective:
CollectiveFingerPrint(SequenceNumber=724883, OpType=_ALLGATHER_BASE, TensorShape=[699051], TensorDtypes=BFloat16, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))).Collectives differ in the following aspects:
Tensor Tensor shapes: 4194305vs 699051
```

When I pin transformers to 4.36.2 the issue goes away.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Finetune mixtral w/ deepspeed + accelerate my ds_config is like so
```json
{
    "fp16": {
        "enabled": false
    },
    "bf16": {
        "enabled": true
    },
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": false
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "gather_16bit_weights_on_model_save": true,
        "round_robin_gradients": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 10,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false,
    "comms_logger": {
        "enabled": true,
        "verbose": true,
        "prof_all": true,
        "debug": true
    }
}
```
2. 

### Expected behavior

The tensors are the correct shape

**Comment by amyeroberts** [comment]
Hi @sam-h-bean, thanks for raising an issue! 

So that we can best help you, can you make sure to follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and include all important information such as: 
* The running environment: run `transformers-cli env` in the terminal and copy-paste the output. For example 'latest' isn't descriptive - it could mean dev branch or 4.37
* A minimal code snippet we can run to reproduce the error
* Full details of the error encountered, including full traceback

cc @ArthurZucker @pacman100

**Comment by imraviagrawal** [comment]
Have same issue with latest transformers, how did you resolve the issue
