### ISSUE TITLE
How can I run NER on ALBERT?

### ISSUE THREAD

**Issue by xf05888** [huggingface/transformers#2868]
I what to run NER on ALBERT, so I checked the [run_ner.py](https://github.com/huggingface/transformers/blob/master/examples/run_ner.py), but it seems like no ALBERT support. 
So can I simply import `AlbertTokenizer`, `AlbertForTokenClassification` and
`AlbertConfig` in the script and add them to `MODEL_CLASSES` and `ALL_MODELS`(Or need other config)?

**Comment by arrrrrmin** [comment]
+1 
Same for [run_language_modeling.py](https://github.com/huggingface/transformers/blob/master/examples/run_language_modeling.py)?

**Comment by thomwolf** [comment]
What do you think about moving the examples to `AutoModels` (in this case `AutoModelForTokenClassification`) @srush @LysandreJik @julien-c ?

**Comment by LysandreJik** [comment]
@thomwolf Indeed, that would be nice.

**Comment by srush** [comment]
Yup, sounds good to me (it will make things much simpler).

**Comment by julien-c** [comment]
Yes, makes sense
