### ISSUE TITLE
Numpy version check failures

### ISSUE THREAD

**Issue by Iron-Bound** [huggingface/transformers#28702]
### System Info
latest docker container from `rocm/pytorch`

### Packages pip/conda
numpy                     1.26.3 
transformers              4.37.1
peft                      0.7.1
accelerate                0.26.1

### Error

Python 3.9.18 (main, Sep 11 2023, 13:41:44)                                                                                         
│[GCC 11.2.0] :: Anaconda, Inc. on linux                                                                                             
│Type "help", "copyright", "credits" or "license" for more information.                                                              
│>>> import transformers                                                                                                             
│Traceback (most recent call last):                                                                                                  
│  File "<stdin>", line 1, in <module>                                                                                               
│  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/transformers/__init__.py", line 26, in <module>                          
│    from . import dependency_versions_check                                                                                         
│  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 57, in <module>         │
│    require_version_core(deps[pkg])                                                                                                 
│  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/transformers/utils/versions.py", line 117, in require_version_core       
│    return require_version(requirement, hint)                                                                                       
│  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/transformers/utils/versions.py", line 111, in require_version           
│    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)                                                                
│  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/transformers/utils/versions.py", line 39, in _compare_versions           
│    raise ValueError(                                                                                                               
│ValueError: Unable to compare versions for numpy>=1.17: need=1.17 found=None. This is unusual. Consider reinstalling numpy.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps:
1. $ pip install transformers
2. $ python3
3. import transformers

Hacky fix, disabled the check in `transformers/utils/versions.py` to get past the error.

### Expected behavior

loads without issue, is this to simple an answer?

**Comment by amyeroberts** [comment]
Hi @Iron-Bound, thanks for raising this issue! 

What do you get as output if you import numpy and check the version in a python session? 

```py
import numpy as np
print(np.__version__)
```

**Comment by Iron-Bound** [comment]
let me try to find the container taht I had the issue on, side note I think this may be due to conda changing package paths
