### ISSUE TITLE
Current version 4.37.1 only match torch>=1.13.0, not torch > 1.11

### ISSUE THREAD

**Issue by StrivedTye** [huggingface/transformers#28720]
when using torch<1.13.0, current version (4.37.1) will report a OSError, because `torch.load()` in torch==1.12 does not has the keyword of `weights_only`. This issue occurs in the file `modeling_utils, Line 533`.

**Comment by amyeroberts** [comment]
cc @ydshieh

**Comment by ydshieh** [comment]
Sorry, indeed, it's my bad

#28506 didn't fix #27282  properly, I will open a PR

**Comment by ydshieh** [comment]
@StrivedTye Fix is merged. I tried it and it works. Let me know if you have further issue with this. Thanks for reporting the issue.
