### ISSUE TITLE
Correct way for Wav2vec2 feature extraction from huggingface like Fairseq

### ISSUE THREAD

**Issue by hungdinhxuan** [huggingface/transformers#28726]
### System Info

- `transformers` version: 4.36.2
- Platform: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
- Python version: 3.10.13
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.4.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: NVIDIA RTX 4090
- Using distributed or parallel set-up in script?: No

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
import fairseq
from transformers import Wav2Vec2ForPreTraining, Wav2Vec2Config
import torchaudio

model_file = 'wav2vec_small.pt'
model, _, _ = fairseq.checkpoint_utils.load_model_ensemble_and_task([model_file])
original = model[0]
waveform, _ = torchaudio.load('MMSTTS_ara_000008.wav')
reference = original(waveform, mask=False, features_only=True)['x']
model_name = 'facebook/wav2vec2-base'
config = Wav2Vec2Config.from_pretrained(model_name)
w2vhf = Wav2Vec2ForPreTraining.from_pretrained(model_name, config=config)
res = w2vhf(waveform, attention_mask=None, output_hidden_states = True).hidden_states[-1]

torch.testing.assert_close(res, reference)
```

Error:
```
AssertionError: Tensor-likes are not close!

Mismatched elements: 155126 / 155136 (100.0%)
Greatest absolute difference: 5.448995590209961 at index (0, 140, 96) (up to 1e-05 allowed)
Greatest relative difference: 89616.765625 at index (0, 6, 144) (up to 1.3e-06 allowed)
```

### Expected behavior

I am using pre-trained wav2vec-base model download from fairseq GitHub. I expected that the pre-trained model provided by huggingface is also the same as fairseq. It means feature extractions from fairseq and hugging face should be as close as possible. What am I doing wrong, or is my feature extraction using Wav2Vec2ForPreTraining not correct? Pre-trained model provides by huggingface with the Pre-trained model from Fairseq are the same? Are there any differences between their model architectures?

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi @ylacombe

**Comment by amyeroberts** [comment]
Gentle ping @sanchit-gandhi @ylacombe

**Comment by amyeroberts** [comment]
Another ping @sanchit-gandhi @ylacombe
