### ISSUE TITLE
Freely Long-Thinking Transformer (FraiLT)

### ISSUE THREAD

**Issue by akbayt** [huggingface/transformers#28730]
### Model description

Hi! 
I am the author of the following study:

https://arxiv.org/abs/2401.11626

I want to add this model to 🤗 transformers. 

Implementation is in progress... 👨‍💻

*Abstract:*
Freely Long-Thinking Transformer (FraiLT) is an improved transformer model designed to enhance processing capabilities without scaling up size. It utilizes a recursive approach, iterating over a subset of layers multiple times, and introduces iteration encodings to maintain awareness across these cycles. Iteration encoding allows FraiLT to achieve the interpretive depth of larger models in a compact form. When evaluated on a synthetic story dataset, FraiLT outperformed larger models, showcasing its ability to deliver high-quality performance while reducing memory demands. This model represents a step forward towards more efficient and accessible language models.

### Open source status
- [X] The model explained in the paper

### Provide useful links for the implementation

Paper: https://arxiv.org/abs/2401.11626, https://www.academia.edu/113629981

**Comment by amyeroberts** [comment]
Hey @akbayt. Thanks a lot for opening this new model request and contributing to the HF ecosystem! 🤗
We have recently been trying to push for `model on the hub` and have as much support as we can there. It will also be easier to integrate it. Here is a [tutorial](https://huggingface.co/docs/transformers/custom_models) if that sound good to you!

**Comment by akbayt** [comment]
Hi @amyeroberts. Thanks for your quick response and guidance. As far as I can see, sharing the models on hub will make it easier for me and will add a slight work when someone wants to use it. This is still acceptable. However, the models I have trained so far are very modest in scale (you can see the details in the paper), and I am actively seeking support and resources to train larger models. I believe that having my model integrated into the 🤗 transformers library, rather than sharing it on the hub, could increase its visibility within the community. In turn, it might help me find some support easier. Thanks again.

**Comment by amyeroberts** [comment]
The best way to help make your model visible is by making sure the model is easy to find (be on the hub), easy to use (has a detailed model card with code snippet users showing how to get started) and a space demo showing the model's capabilities. Many models have become popular that were just on the hub. For example, falcon and phi-2 started on the hub.
