### ISSUE TITLE
how to get "xlnet-base-cased-pytorch_model.bin" original 'last modified' date?

### ISSUE THREAD

**Issue by eyal-orbach** [huggingface/transformers#2873]
I'd like to test my finetuning on some wikipedia articles that have not been seen by the model.
For that, I can find the date of creation on the wikipedia article, but I'd also like to verify that this is after the 'last modified' date of the model. 
How can I get the answer to when was the model parameters' last modified?

**Comment by cronoik** [comment]
Just click on 'List all files in the model' and you will see the upload date [1].

[1] https://huggingface.co/xlnet-base-cased
