### ISSUE TITLE
when running rag example, errors in the 'generating train split' step (wiki_dpr.py)

### ISSUE THREAD

**Issue by kiehls90** [huggingface/transformers#28743]
### System Info

I'm trying to run a rag example, and the dataset is wiki_dpr.
wiki_dpr download and extracting have been completed successfully.
However, at the generating train split stage, an error from wiki_dpr.py keeps popping up.

Especially in "_generate_examples" :

1. The following error occurs in the line **id, text, title = line.strip().split("\t")**
ValueError: not enough values ​​to unpack (expected 3, got 2)
-> This part handles exceptions so that even if an error occurs, it passes.

2. **ID mismatch between lines {id} and vector {vec_id}**
This error seems to occur at the line " assert int(id) == int(vec_id),".
After I handled the exception in the split error, generating train split progressed to 80%, but an id mismatch error occurred at about the 16200000th vector id.

Debugging is even more difficult because it takes a long time to download and split wiki_dpr. I need help. thank you in advance!!
version: python 3.8, and others are referenced from requirements.txt.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. running rag example: python examples/research_projects/rag/finetune_rag.py \
    --data_dir $DATA_DIR \
    --output_dir $OUTPUT_DIR \
    --model_name_or_path $MODEL_NAME_OR_PATH \
    --model_type rag_sequence \
    --fp16 \
    --gpus 8
2. after downloading and extracting wiki_dpr, then error occurs in "generating train split"

### Expected behavior

.

**Comment by amyeroberts** [comment]
Hi @kiehls90, thanks for raising an issue! 

The scripts under `research_examples` aren't actively maintained. If a dataset is very large, you can try [streaming it](https://huggingface.co/docs/datasets/stream) instead of downloading the whole thing.
