### ISSUE TITLE
combining feature from two pre-train model in transformer then passing them into a classifer 

### ISSUE THREAD

**Issue by Arwa491** [huggingface/transformers#28749]
I'm trying to extract the feature using two different per-train models combine these features in one vector and then pass this vector into a classifier for a final classification 
is that possible using hugging face pre-train models , because i already trained  the model on my data and uploaded them into hugging face

**Comment by amyeroberts** [comment]
Hi @Arwa491, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
