### ISSUE TITLE
Handling offload when calling AutoModelForCausalLM.from_pretrained()

### ISSUE THREAD

**Issue by YourSaDady** [huggingface/transformers#28744]
### System Info

Transformers version: 4.33.3
Python version:  3.9.18
Platform: Win11 WSL

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

1. `from transformers import AutoTokenizer,AutoModelForCausalLM`
2. `model = AutoModelForCausalLM.from_pretrained(args.model,device_map='auto')`
3. Error occurs: 
<img width="866" alt="error2" src="https://github.com/huggingface/transformers/assets/99607923/86201897-10a7-41b2-a1f8-3c961b198337">

### Expected behavior

Expected: model should be loaded without any errors.
I also tried to specify the offload folder by changing the line 67 to `model = AutoModelForCausalLM.from_pretrained(args.model,device_map='auto', offload_folder='offload')', but the program is killed without any error or tracebacks shown.

**Comment by amyeroberts** [comment]
Hi @YourSaDady, thanks for raising this issue! 

If the program is killed when using `offload_folder` it would indicate that you're hitting OOM. If you look at your GPU memory utilization - `watch -n1 nvidia-smi` - and your CPU utilization e.g. with`top` are you able to see these topping out when loading the model?
