### ISSUE TITLE
Converting TF2 SavedModel models to Huggingface

### ISSUE THREAD

**Issue by jhyuklee** [huggingface/transformers#28787]
Hi, I'd like to know how I can convert a TF2 SavedModel (e.g. [gtr-base-1](https://www.kaggle.com/models/google/gtr/frameworks/tensorFlow2/variations/gtr-base/versions/1?tfhub-redirect=true)) to a Huggingface PyTorch model as described in the [README](https://huggingface.co/sentence-transformers/gtr-t5-base). We have a similar model in the same format and would like to use it in Huggingface. Thanks!

**Comment by ArthurZucker** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
Hi @jhyuklee, take a look at the `convert-gtr` notebook in the HuggingFace sentence transformers repos [here](https://huggingface.co/sentence-transformers/gtr-t5-base/blob/main/convert-gtr.ipynb). This shows the process of converting a model from the TF Hub, so you should be able to adapt that to convert other SavedModels.

**Comment by jhyuklee** [comment]
Hi @Rocketknight1, this is exactly what I was looking for. Will close this once I try that out.
