### ISSUE TITLE
Add InternLM1 & InternLM2 model

### ISSUE THREAD

**Issue by PommesPeter** [huggingface/transformers#28792]
### Model description

Hey,
the recently released [InternLM](https://github.com/InternLM/InternLM) seems like it would be a nice addition to transformers.

Basically, the model has achieved performance that currently exceeds LLaMA2, Mistral, and other models on many Benchmarks. Adding the model to transformers makes it easier to use the model. It has two parameter sizes of 7B and 20B, for v1 and v2 versions. In addition, it also includes three types of models: base, sft, and chat.

Maybe there are already plans of integrating it @NielsRogge ?

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Project Page: https://internlm.intern-ai.org.cn/
GitHub Repo: https://github.com/InternLM/InternLM

**Comment by ArthurZucker** [comment]
Hey! Thanks, seems like it's already supported: #26302
