### ISSUE TITLE
sequence_bias feature is not working for Whisper ASR model.

### ISSUE THREAD

**Issue by vchagari** [huggingface/transformers#28805]
### System Info

Hi @sanchit-gandhi and @gante 
Sequence_bias feature is not working, I tried with similar example shown in the SequenceBiasLogitsProcessor class (https://github.com/huggingface/transformers/blob/7b2bd1fbbd50e57cf28013e2d0737912ecc0f2eb/src/transformers/generation/logits_process.py#L942) with fine-tuned Whisper ASR HF model, 

I recorded an audio and gave it to the Whisper ASR model with biasing terms like mentioned below, unfortunately i  didn't see any effect in the output.

**More details:**
Transformers Commit: 1c7e5e236823cd38faac8115f96205a82c17fff9

Test-Case:  Steps how to reproduce the issue. 
Audio contents: "The full name of Donald is Donald J. Trump Jr"
sequence_bias = {get_tokens_as_tuple("Donald Duck"): 10.0}

model = WhisperForConditionalGeneration.from_pretrained(model_dir).to("cuda") 
feature_extractor = WhisperFeatureExtractor.from_pretrained(model_dir)
processor = WhisperProcessor.from_pretrained(model_dir)
input_features = feature_extractor(audio, sampling_rate=16000, return_tensors="pt").input_features
predicted_ids = model.generate(input_features.to("cuda"), sequence_bias=sequence_bias, num_beams=4)
text = [processor.decode(predicted_id, skip_special_tokens=True) for predicted_id in predicted_ids]
transcript = text[0]

The output is still came as "The full name of Donald is Donald J Trump Jr"

### Who can help?
@sanchit-gandhi and @gante

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Test-Case:  Steps how to reproduce the issue. 
Audio contents: "The full name of Donald is Donald J. Trump Jr"
sequence_bias = {get_tokens_as_tuple("Donald Duck"): 10.0}

model = WhisperForConditionalGeneration.from_pretrained(model_dir).to("cuda") 
feature_extractor = WhisperFeatureExtractor.from_pretrained(model_dir)
processor = WhisperProcessor.from_pretrained(model_dir)
input_features = feature_extractor(audio, sampling_rate=16000, return_tensors="pt").input_features
predicted_ids = model.generate(input_features.to("cuda"), sequence_bias=sequence_bias, num_beams=4)
text = [processor.decode(predicted_id, skip_special_tokens=True) for predicted_id in predicted_ids]
transcript = text[0]

### Expected behavior

The full name of Donald is Donald Duck.

**Comment by gante** [comment]
Hi @vchagari 👋 

The [same comment](https://github.com/huggingface/transformers/issues/28822) applies here :)
