### ISSUE TITLE
AWQ models loaded with AutoModelForCausalLM.from_pretrained not as fast as AutoAWQForCausalLM.from_quantized

### ISSUE THREAD

**Issue by nilichen** [huggingface/transformers#28829]
### System Info

- `transformers` version: 4.36.2
- Platform: Linux-6.2.0-1018-aws-x86_64-with-glibc2.35
- Python version: 3.11.7
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
    model = AutoModelForCausalLM.from_pretrained(
        "TheBloke/Mistral-7B-Instruct-v0.2-AWQ",
        device_map="auto",
    )

    model = AutoAWQForCausalLM.from_quantized(
        "TheBloke/Mistral-7B-Instruct-v0.2-AWQ",
        fuse_layers=False,
        quant_filename="model.safetensors",
        safetensors=True,
    )
```

I tested both on long inputs (~5k tokens, data of privacy so won't be able to share) for generation, in both cases, I didn't use fused modules. `AutoModelForCausalLM.from_pretrained` took ~24s each while `AutoAWQForCausalLM.from_quantized` took ~18s each. The output token count didn't seem to differ much.

I ran the comparison at least 3 times and got consistent results.

### Expected behavior

The latency should be close.

**Comment by ArthurZucker** [comment]
Hey! Thanks for reporting. This is expected, the operations are not fused by default in transformers, [as per the documentation](https://huggingface.co/docs/transformers/quantization#fused-modules).

**Comment by nilichen** [comment]
Hi. I did have `fused_layers = False` when loading with `AutoAWQForCausalLM.from_quantized` so in theory they should share similar latency?

**Comment by ArthurZucker** [comment]
cc @younesbelkada

**Comment by younesbelkada** [comment]
@nilichen I think the autoawq use by default fused layer norm maybe that explains the whole difference - make sure also to run greedy generation to avoid any potential bottleneck, @casper-hansen is the speedup over the transformers implementation expected?

**Comment by casper-hansen** [comment]
There should not be any difference between the two implementations when fused layers are off

**Comment by nilichen** [comment]
That's what I thought. Let me see if I can reproduce on a public dataset and report back.
