### ISSUE TITLE
SDPA attention causes graph break while compiling model

### ISSUE THREAD

**Issue by huzama** [huggingface/transformers#28827]
### Feature request

Static graph support in SDPA attention 

### Motivation

The use of SPDA attention significantly enhances transformers' performance and memory utilization. However, when attempting to compile it with the XLA backend on TPUs, there are graph breaks that require continuous recompilation. This makes the use of SPDA attention on TPUs impractical. 

### Your contribution

I did some debugging and found out that this [line](https://github.com/huggingface/transformers/blob/abbffc4525566a48a9733639797c812301218b83/src/transformers/modeling_attn_mask_utils.py#L371)  of code uses torch.all on attention_mask which changes for each iteration causing dynamic control flow, which causes recompilation in XLA-TPU.

Output of torch._dynamo.explain for Llama-7b with SDPA attention

 graph_count=6, graph_break_count=5, break_reasons=[GraphCompileReason(reason='Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow. For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#cond-operands', user_stack=[<FrameSummary file /home/ubuntu/miniforge3/envs/transformers/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py, line 1035 in forward>, <FrameSummary file /home/ubuntu/miniforge3/envs/transformers/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py, line 372 in _prepare_4d_causal_attention_mask_for_sdpa>], graph_break=True), GraphCompileReason(reason='generic_jump TensorVariable()', user_stack=[<FrameSummary file /home/ubuntu/miniforge3/envs/transformers/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py, line 372 in _prepare_4d_causal_attention_mask_for_sdpa>], graph_break=True), GraphCompileReason(reason='dynamic shape operator: aten.nonzero.default', user_stack=[<FrameSummary file /home/ubuntu/miniforge3/envs/transformers/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py, line 243 in _unmask_unattended>], graph_break=True)], op_count=977,

**Comment by ArthurZucker** [comment]
Hey! would recommend you to try #27931 😉
