### ISSUE TITLE
Llava-demo-4bit.ipynb Error (KeyError: 'llava')

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/transformers#28839]
### System Info

See [this notebook from HuggingFace](https://colab.research.google.com/drive/1qsl6cd2c8gGtEW1xV5io7S8NHh-Cp1TV?usp=sharing#scrollTo=DFVZgElEQk3x)

### Who can help?

@amyeroberts

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the notebook through to get this error:
```
KeyError                                  Traceback (most recent call last)
[<ipython-input-15-2c1efb550f3d>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 model_id = "llava-hf/llava-1.5-7b-hf"
----> 6 pipe = pipeline("image-to-text", model=model_id)
      7 url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/transformers/tasks/ai2d-demo.jpg"
      8 

2 frames
[/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py](https://localhost:8080/#) in __getitem__(self, key)
    759     [
    760         ("openai-gpt", "openai"),
--> 761         ("data2vec-audio", "data2vec"),
    762         ("data2vec-text", "data2vec"),
    763         ("data2vec-vision", "data2vec"),

KeyError: 'llava'
```

### Expected behavior

I would expect the notebook to run through the image + text example.

**Comment by ArthurZucker** [comment]
You are probably running this on a local host, which does not have the latest version of `transformers` make sure to update with `pip install -U transformers`. You should have `import transformers;print(transformers.__version__)` >= transformers==4.37.2
