### ISSUE TITLE
Add gpt_neox in fx supported models?

### ISSUE THREAD

**Issue by TXacs** [huggingface/transformers#28832]
### System Info

change        
`qkv = qkv.view(*new_qkv_shape)`
to
` qkv = qkv.view(new_qkv_shape)`
I've made a modification, and now it can be traced by `hftracer`.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

None

### Expected behavior

I wonder if this could be incorporated into future versions.

**Comment by ArthurZucker** [comment]
feel free to open a PR and ping @fxmarty ! 🤗
