### ISSUE TITLE
Evaluation and Inference added to run_glue.py

### ISSUE THREAD

**Issue by CMobley7** [huggingface/transformers#2884]
# 🚀 Feature request

It would be useful to have the following arguments added to `run_glue.py`, as well as probably the other task example scripts: `--eval_only` and `--inference_only`.

## Motivation

This will allow users to either provide a `.tsv` or `.csv` with either sentences and labels or just sentences and then perform evaluation or inference on the model without having to train. This may already exist, but I was unable to find it. Consequently, I'm using https://github.com/kaushaltrivedi/fast-bert for these tasks. It would be helpful to not have to stray from the main huggingface transformers library.

**Comment by LysandreJik** [comment]
Hi! You can already provide `do_eval` to `run_glue` to do the evaluation. If you don't specify `do_train`, it will only do the evaluation, and no training.

The inference would be a nice addition.
