### ISSUE TITLE
Donut model only works on 4.36.2 for inference, not 4.37.2

### ISSUE THREAD

**Issue by VikParuchuri** [huggingface/transformers#28846]
### System Info

I have a donut model with some slight customizations to the mbart decoder (added gqa and moe).  It works fine on 4.36.2 and 4.37.2 for training.

But inference only works on 4.36.2.  When I run inference on 4.37.2, then the output degenerates into repetition. @amyeroberts 

Here is an example (the text has been ocred with donut, then rendered back onto a page image):

This is with 4.36.2:

![image](https://github.com/huggingface/transformers/assets/913340/0382c56c-66eb-4989-a35d-92c1c6dbaba9)

And this is with 4.37.2:

![image](https://github.com/huggingface/transformers/assets/913340/01d710c3-d19e-4f00-a6bf-1cb1e530bd15)

Everything else is identical (same system, same packages).  I don't see anything obvious in the release notes that would cause this.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

- Clone https://github.com/VikParuchuri/surya/tree/rec (has to be the rec branch)
- Install (see README)
- Run `python benchmark/recognition.py --max 1 --debug`

You should see different output with different transformers versions.

### Expected behavior

I expect the output to be the same with both versions, and to not degenerate into repetition.

**Comment by ArthurZucker** [comment]
fyi @NielsRogge

**Comment by NielsRogge** [comment]
Hi sorry for the late reply, I've checked all slow integration tests of Donut, and they all pass:
```
RUN_SLOW=yes pytest tests/models/vision_encoder_decoder/test_modeling_vision_encoder_decoder.py::DonutModelIntegrationTest
```
Which would mean that Donut works as expected on v4.38.2 dev.

This might be explained because of the customizations? Could you clarify which things are changed compared to Donut?

**Comment by praneet0017** [comment]
@VikParuchuri which version of tokenizers are you using? I had a similar issue where downgrading tokenizers version 0.13.3 solved the issue for me
