### ISSUE TITLE
after batch_encode_plus generate returns sequence of EOS tokens 

### ISSUE THREAD

**Issue by tempdeltavalue** [huggingface/transformers#28853]
### System Info

Here's the screenshot which is show this issue
![Screenshot 2024-02-03 210015](https://github.com/huggingface/transformers/assets/36921178/2492512e-c555-4870-be15-f38fea07e516)

HF - discussion:
https://discuss.huggingface.co/t/gpt2-returns-sequence-of-endoftext-after-finetuning/70418

HF topic - discord:
https://discord.com/channels/879548962464493619/1201159949288488970

thank you..

### Who can help?

Would be great to get some advice about it
@gante @ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

To reproduce please check this notebook and repo with the code 
https://github.com/tempdeltavalue/temp_l/blob/main/finetune_seq2seq.ipynb

### Expected behavior

I want to encode list of strings to batch and pass it to generate and get output without EOS sequence

**Comment by ArthurZucker** [comment]
Most probably a padding side issue. If you skip the special tokens you should no longer see them when decoding. 
It is planned to get rid of this function anyway to keep only encode and decode for simplicity!
