### ISSUE TITLE
add `push_to_hub( )` method when working with pipelines

### ISSUE THREAD

**Issue by not-lain** [huggingface/transformers#28857]
### Feature request

it will be good to addition to the library to add a `push_to_hub( )` method when working with the pipeline method.

### Motivation

I have just finished up a blogpost about creating custom architectures, but i couldn't help but notice that when working with ` AutoConfig` or `AutoModelForxxx` or `PreTrainedModel`  have a `push_to_hub( )` methods alllowing them to easily be updated on the hub.
unfortunately, this isn't the case for the pipeline method, I found a possible work around by cloning the repo then using `save_pretrained( )` then pushing the changes, but this not optimised and takes lots of time especially when working with really large language models
check the documentation : 
https://huggingface.co/blog/not-lain/custom-architectures-with-huggingface#push-to-hub-%F0%9F%A4%97
<hr>

![image](https://github.com/huggingface/transformers/assets/70411813/11a3f62f-0a39-48b1-9109-0e7c3896f526)
**VS**
![image](https://github.com/huggingface/transformers/assets/70411813/09562086-a0f5-4bb9-86c9-57b92ec637b1)

### Your contribution

yes, I can help out with a PR

**Comment by ArthurZucker** [comment]
FYI @Rocketknight1
