### ISSUE TITLE
TypeError: unhashable type: 'dict' with BGE-M3 using AutoTokenizer

### ISSUE THREAD

**Issue by NirantK** [huggingface/transformers#28859]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): 2.15.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.0 (cpu)
- Jax version: 0.4.23
- JaxLib version: 0.4.23
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

The notebook to reproduce it is here: https://colab.research.google.com/drive/1OAsds_zEjGEzkfuYlJfkSPTDw5MoVYsx#scrollTo=b1ecf0b6-db81-4da3-b47f-e31460ccfbf1

1. Install dependencies: optimum, onnx, onnx-runtime
2. Try to load the BGE-M3 using the AutoTokenizer

### Expected behavior

1. AutoTokenizer works with BGE-M3 too

**Comment by ArthurZucker** [comment]
Hey! I cannot reproduce this on main:
```python 

In [3]: from transformers import AutoTokenizer

In [4]: model_id = "BAAI/bge-m3"
   ...: hf_tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.31k/1.31k [00:00<00:00, 2.65MB/s]
sentencepiece.bpe.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.07M/5.07M [00:00<00:00, 7.40MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17.1M/17.1M [00:00<00:00, 22.4MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 964/964 [00:00<00:00, 2.80MB/s]
```
works as expected for me. Make sure to use the latest version of transformers

**Comment by song4875343** [comment]
你的transformers库太老了，更新一下就没这个问题了，我也出现了和你一样的更新到4.37.2问题消失

**Comment by NirantK** [comment]
Updating to the latest transformers worked. Thanks @ArthurZucker @song4875343

**Comment by fpaupier** [comment]
Updating to `transformers==4.37.2` solved the issue for me.
```bash
pip install -U transformers
```
