### ISSUE TITLE
Support FlashAttention2 on torch2.2 

### ISSUE THREAD

**Issue by luohao123** [huggingface/transformers#28861]
Flasshattn2 didn't support V100, and it just throws error on V100 gpus.

Since torch2.2 has built in flashatten2 support ,consider suppor t it?

**Comment by ArthurZucker** [comment]
You should already be able to use this with `attn_implementation="sdpa"`

**Comment by luohao123** [comment]
@ArthurZucker waoo, so high efficiency, is 3.37 support now?

**Comment by ArthurZucker** [comment]
I don't know the exact details but it should still used fused operations ! 
transformers 4.35 already supported this I believe (not for all models of course) through sdpa

**Comment by luohao123** [comment]
@ArthurZucker thanks. Does llama and llava support?

**Comment by ArthurZucker** [comment]
YES

**Comment by younesbelkada** [comment]
@luohao123 for using FA2 through the SDPA interface of pytorch you should wrap your model's forward or generate with the following context manager:
```diff
+ with torch.backends.cuda.sdp_kernel(enable_flash=True, enable_math=False, enable_mem_efficient=False):
    model.generate(xxx)
```

**Comment by luohao123** [comment]
@younesbelkada  Does it has simpler config configs in transformers?

**Comment by ArthurZucker** [comment]
Closing as it is supported!
