### ISSUE TITLE
Saving Transformers model as binary instead of `safetensors` format?

### ISSUE THREAD

**Issue by StatsGary** [huggingface/transformers#28863]
I am trying to Torchserve (https://pytorch.org/serve/) a Transformers model to be deployed as a prediction API on GCP as a custom prediction service. 

However, torchserve requires that the model be in either `.bin` format or `.pt` format. Is there a way to deactivate safetensors and return the .bin PyTorch file?

I have tried to use torch.save(model.state_dict(), PATH) but have been unsuccessful thus far? Anyone encountered similar issues?

**Comment by StatsGary** [comment]
➡️💡 SOLUTION ➡️💡 

I dig some digging of the parameters of the `save_pretrained` and `trainer` methods and you can actually 🔧 turn off the storing of the safetensors format models, by using the following example: 
```python
model.save_pretrained(<PATH_TO_SAVE_MODEL>, safe_serialization=False) #Replace path
```

**Comment by Narsil** [comment]
Could luck trying to secure your servers from malicious actors ! :)

**Comment by ncompass-ts** [comment]
@StatsGary With the solution you gave, Post saving the model it creates three files,

1. config.json
2. generation_config.jso
3. pytorch_model.bin

1. Can you help me how you used these to import and deploy in GCP vertex model registry?
2. Have you use pre-build container like pytorch or went with custom container ?
- If prebuilt contained - How did you convert .bin file to .mar ?
- If custom container - Can you share your version or example image please ?
