### ISSUE TITLE
Regarding attention size returned by the model

### ISSUE THREAD

**Issue by divyag11** [huggingface/transformers#2887]
hi, while doing output_attentions - True in the huggingface model.it return attention of size:(no. of heads,seq length,seq length)
can we configure it to return only the attention of the last 2 heads of the model.
please let me know.

**Comment by cronoik** [comment]
Hi,
which model do you use? Can't you simply remove the output of the other heads?

**Comment by divyag11** [comment]
I am using TFDistilbertmodelforsequenceclassification.
You are right,i can remove other head attention,but while using tfserving,it's taking a lot time ,since the output attentions has huge dimension.
So,that's why ,i was asking if i could get just last 2 head attention instead of getting all head attentions while hitting tfserving

**Comment by LysandreJik** [comment]
Unfortunately, we don't have a way to do that right now.
