### ISSUE TITLE
[pipeline][video-classification] a question about the use of decord in VideoClassificationPipeline

### ISSUE THREAD

**Issue by Tyx-main** [huggingface/transformers#28880]
### System Info

transformers:4.37.2
platform: aarch

### Who can help?

@Narsil@sanchit-gandhi

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

It seems that when we use pipeline for VideoClassification, an issue can not be avoided that a third party named decord can only be used in x86/arm instead of aarch, but my machine only supports aarch, is there any method to solve this problem?

### Expected behavior

VideoClassificationPipeline can be used in aarch platform

**Comment by Tyx-main** [comment]
@sanchit-gandhi@Narsil

**Comment by Tyx-main** [comment]
@Narsil @sanchit-gandhi

**Comment by Tyx-main** [comment]
> Hi @Tyx-main, apologies for the delay in response.
> 
> Indeed, decord can cause some issues. In fact, we removed it from a bunch of our examples in #21572. The fix would be to use pyav in the pipelines as well. Would you like to open a PR to add this?

Thanks！I will do it soon！

**Comment by amyeroberts** [comment]
Closing as resolved in #29747
