### ISSUE TITLE
token-classification

### ISSUE THREAD

**Issue by AdrianRemo14** [huggingface/transformers#28886]
### System Info

everything necessary for the operation of the program

### Who can help?

@ArthurZucker  @younesbelkada

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

i use this token-classification https://github.com/huggingface/transformers/tree/main/examples/pytorch/token-classification

### Expected behavior

![warning](https://github.com/huggingface/transformers/assets/159118361/e9d16cad-c070-466d-b7f3-eb156533c1eb)

i use this format for json:
{"text": ["Ă„ÂŚie", "sĂÂş", "to", "tenisky", "Peter", "naozaj", "sĂÂş", "tvoje", "Tak", "si", "ich", "hneĂ„ÂŹ", "uloĂ…Âľ"], "labels": ["O", "O", "O", "O", "QUESTION", "O", "COMMA", "O", "O", "O", "QUESTION", "O", "O", "O", "O", "O", "EXCLAMATION"]}
{"text": ["Pri", "rieke", "stojĂÂ­", "mlyn", "Z", "chaty", "sa", "dymĂÂ­", "Dedo", "Ă„ÂŤĂÂ­ta", "noviny"], "labels": ["O", "O", "COMMA", "O", "O", "PERIOD", "O", "O", "O", "O", "PERIOD", "O", "COMMA", "O", "O", "PERIOD"]}

I want to ask why I get a warning that my tag is not in the NE tag. I want to train slovakBERT on my own data. Can you advise me what I'm doing wrong or what I need to fix?

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests! The example scrips should be adapted to each's use case, and I suppose that is what you did. As such I would recommend 2 things:
-  ask your question on the [forum](https://discuss.huggingface.co/) 
- track the warning's source to check what is happening. (Question is probably missing from the vocab NE?) 
 

Thanks!
