### ISSUE TITLE
Add MistralForQuestionAnswering

### ISSUE THREAD

**Issue by nakranivaibhav** [huggingface/transformers#28908]
### Feature request

Add a MistralForQuestionAnswering class to the [modeling_mistral.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mistral/modeling_mistral.py) so Mistral models have AutoModelForQuestionAnswering support (by also adding Mistral models to the MODEL_FOR_QUESTION_ANSWERING_MAPPING_NAMES  in the [modeling_auto.py](https://github.com/huggingface/transformers/blob/v4.36.1/src/transformers/models/auto/modeling_auto.py#L1343) file.

### Motivation

1 - Evaluation benchmarks like [Squad](https://huggingface.co/datasets/squad_v1_pt) or [FaQUAD](https://huggingface.co/datasets/eraldoluis/faquad) are commonly used to evaluate language models.
2 - Many decoder-only transformers ([BLOOM](https://huggingface.co/docs/transformers/model_doc/bloom), [Falcon](https://huggingface.co/docs/transformers/model_doc/falcon), [OpenAI GPT-2](https://huggingface.co/docs/transformers/model_doc/gpt2), [GPT Neo](https://huggingface.co/docs/transformers/model_doc/gpt_neo), [GPT NeoX](https://huggingface.co/docs/transformers/model_doc/gpt_neox), [GPT-J](https://huggingface.co/docs/transformers/model_doc/gptj), etc.) have support for the AutoModelForQuestionAnswering.
3 - Creating a fine-tuning/evaluation procedure using things like AutoModelForQuestionAnswering and evaluate.load('squad') is very simple, making these features very helpful and desirable.
4 - On the contrary, if one cannot use AutoModelForQuestionAnswering, like in the Llama style models, everything becomes more difficult.

Hence, I would like to request the addition of a MistralForQuestionAnswering class to the modeling_mistral.py file. Hence, we could all easily perform experiments with Mistral models and squad-style Q&A benchmarks:

### Your contribution

I have recently added LlamaForQuestionAnswering class in modeling_llama.py file. I can do the same for Mistral.

**Comment by sriram-1** [comment]
Thank you for the support janpf. Will be glad if PR is accepted.

**Comment by LysandreJik** [comment]
Thanks for your request! We'd happily welcome it to the library, feel free to open a PR adding it if you have the bandwidth to do so!

**Comment by janpf** [comment]
They already did, right? 🤔 #29168 
But the PR got stale
