### ISSUE TITLE
Potential error for llava generation

### ISSUE THREAD

**Issue by ByungKwanLee** [huggingface/transformers#28909]
https://github.com/huggingface/transformers/blame/abf8f54a019ce14b5eaffa68c6dd883be13fe66e/src/transformers/models/llava/modeling_llava.py#L412

This line has potentially critical bug when they do not exist such that input_ids has -100 index unexpectedly.

Therefore I edit that part

![image](https://github.com/huggingface/transformers/assets/50401429/1be763f5-e9fb-4c0b-bfab-f097237f7d9e)

**Comment by ByungKwanLee** [comment]
However, I have experienced the negative input ids for the batch-generating text

**Comment by ArthurZucker** [comment]
Can you share a reproducer? 🤗
