### ISSUE TITLE
T5 fine-tuning `.generate()` issue 

### ISSUE THREAD

**Issue by oozeren** [huggingface/transformers#28911]
### System Info

```shell
i am trying to create own T5 fine-tuner but i get "TypeError: The current model class (ALGORITHMIAT5) is not compatible with `.generate()`, as it doesn't have a language model head."
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

class ALGORITHMIAT5(PreTrainedModel):

    config_class = ALGORITHMIAMODELConfig

    def __init__(self, config):
        super().__init__(config)
        self.config = config
        self.model =AutoModelForSeq2SeqLM.from_pretrained(**config, ignore_mismatched_sizes=True)
        self.tokenizer =   AutoTokenizer.from_pretrained(pretrained_model_name_or_path=pretrained_tokenizer_name_or_path,
                                              ignore_mismatched_sizes=True)

    def forward(self, input_ids, attention_mask=None, decoder_input_ids=None, decoder_attention_mask=None, labels=None):
        print(input_ids)
        return self.model(
            input_ids,
            attention_mask=attention_mask,
            decoder_input_ids=decoder_input_ids,
            decoder_attention_mask=decoder_attention_mask,
            labels=labels,
        )

### Expected behavior

```shell
train the model
```

### Checklist

- [X] I have read the migration guide in the readme. ([pytorch-transformers](https://github.com/huggingface/transformers#migrating-from-pytorch-transformers-to-transformers); [pytorch-pretrained-bert](https://github.com/huggingface/transformers#migrating-from-pytorch-pretrained-bert-to-transformers))
- [X] I checked if a related official extension example runs on my machine.

**Comment by oozeren** [comment]
This the error : "/opt/omniai/software/Miniconda/lib/python3.8/site-packages/transformers/generation/utils.py in _validate_model_class(self)
   1063             if generate_compatible_classes:
   1064                 exception_message += f" Please use one of the following classes instead: {generate_compatible_classes}"
-> 1065             raise TypeError(exception_message)
   1066 
   1067     def _validate_model_kwargs(self, model_kwargs: Dict[str, Any]):

TypeError: The current model class (ALGORITHMIAT5) is not compatible with `.generate()`, as it doesn't have a language model head.

**Comment by ArthurZucker** [comment]
Hey 🤗  thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co/) instead? I'm sure the community will be of help!

For you example, I would recommend you to properly define your class with
```python
def generate():
    self.model.generate()
```
or something like that!

**Comment by oozeren** [comment]
Thanks Arthur. Will do
