### ISSUE TITLE
[Broken link] Link not working in LLaMA-2 pretraining_tp doc

### ISSUE THREAD

**Issue by AdityaKane2001** [huggingface/transformers#28939]
The `this document` link on [LLaMA2 doc page](https://huggingface.co/docs/transformers/model_doc/llama2#transformers.LlamaConfig.pretraining_tp) does not work.

**Comment by amyeroberts** [comment]
@AdityaKane2001 Indeed! Thanks for flagging this. Would you like to open a PR to fix this? This way you get the github contribution.

**Comment by AdityaKane2001** [comment]
Sure
