### ISSUE TITLE
Cannot load transformer model from hugging face in remote server

### ISSUE THREAD

**Issue by nikhilajoshy** [huggingface/transformers#28934]
### System Info

 `transformers` version: 4.37.2
- Platform: Linux-5.15.0-92-generic-x86_64-with-glibc2.31
- Python version: 3.11.7
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.26.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.2.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. `tokenizer = AutoTokenizer.from_pretrained("distilbert/distilgpt2")`

### Expected behavior

(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /distilbert/distilgpt2/resolve/main/tokenizer_config.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa612ffa750>: Failed to establish a new connection: [Errno 111] Connection refused')))")

**Comment by not-lain** [comment]
* are you using the library inside a docker container ? 
* do you have a `https_proxy` or a `HTTPS_PROXY` envirenmental variables set ?
* which python version of `urllib3`  are you using
* do you have VPN enabled ?

**Comment by nikhilajoshy** [comment]
@not-lain 

- it's not inside docker, just a vent
- I have a http_proxy set but not https.
- 1.26.18
- yes

**Comment by not-lain** [comment]
@nikhilajoshy 
try these fixes : 
* upgrade the requests library to a stable version
```
pip install requests==2.27.1   
```
* or set the following envirenmental variable to an empty string
```python
import os
os.environ['CURL_CA_BUNDLE'] = ''
```

if none of the above did not work for you try checking this https://stackoverflow.com/questions/56016210/proxyerrorcannot-connect-to-proxy-newconnectionerror
