### ISSUE TITLE
Allow import of model components, e.g. `from transformers import TFAlbertMLMHead`

### ISSUE THREAD

**Issue by jarednielsen** [huggingface/transformers#2894]
# 🚀 Feature request

Expose model components such as custom layers like `TFAlbertMLMHead`, that are created in `modeling_tf_albert.py` and others.

## Motivation

I'm writing a custom pretraining script that incorporates both the masked language modeling (MLM) and sentence order prediction (SOP) objectives. I'm able to use the `TFAlbertForMaskedLM` model for the MLM objective, but need access to the `last_hidden_state` to write my SOP objective. I can do this if I have a raw `TFAlbertModel` and write my own MLM objective, but would prefer to just create my own model from pre-existing modularized components.

## Your contribution

I can contribute this, it would just be modifying `__init__.py`. I know that there's a lot of care taken in API design, and the team may have explicitly decided against this. But if it is an option, it would make the transformers repo much more extensible for research.

**Comment by cronoik** [comment]
Why don't you import it directly
`from transformers.modeling_tf_albert import TFAlbertMLMHead`

**Comment by jarednielsen** [comment]
That's true, don't know why that slipped my mind. Thanks for the suggestion!
