### ISSUE TITLE
Report inconsistent output length from decoder-only model generate with input_ids and inputs_embeds

### ISSUE THREAD

**Issue by Hannibal046** [huggingface/transformers#28953]
### System Info

- `transformers` version: 4.35.0.dev0
- Platform: Linux-5.15.0-1050-azure-x86_64-with-glibc2.31
- Python version: 3.10.13
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.4.1
- Accelerate version: 0.22.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@gante 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When using `max_length` in `generate`. The output length varies between `input_ids` and `inputs_embeds`

```python
from transformers import AutoTokenizer, LlamaForCausalLM

model = LlamaForCausalLM.from_pretrained("huggyllama/llama-7b",low_cpu_mem_usage=True).cuda()
tokenizer = AutoTokenizer.from_pretrained("huggyllama/llama-7b")

prompt = "Hey, are you conscious? Can you talk to me?"
inputs = tokenizer(prompt, return_tensors="pt")
input_ids = inputs.input_ids.cuda()
inputs_embeds = model.get_input_embeddings()(input_ids)

generation_kwargs = {
    # "max_new_tokens":20,
    "max_length":20,
}
generate_ids = model.generate(input_ids= input_ids, **generation_kwargs)
output = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
print("generate with input_ids:",output)
print("**"*40)

generate_ids = model.generate(input_ids= input_ids, inputs_embeds = inputs_embeds, **generation_kwargs)
output = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
print("generate with input_ids+input_embeds:",output)
print("**"*40)

generate_ids = model.generate(inputs_embeds = inputs_embeds, **generation_kwargs)
output = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
print("generate with input_embeds:",output)
print("**"*40)
```

![image](https://github.com/huggingface/transformers/assets/38466901/5104a4f8-cd79-4350-bc12-0e8236a6fa31)

However, using `max_new_tokens`, it would generate identical results.

### Expected behavior

The output length should be the same whether the input to `generate` is `ids` or `embeds`.

**Comment by gante** [comment]
cc @zucchini-nlp

**Comment by zucchini-nlp** [comment]
Hey, @Hannibal046 . Thanks for pointing this out! I added a PR to fix this behavior. When it gets merged, you can install `transformers` from `main` to get the correct generation.
