### ISSUE TITLE
Option to set the tracking URI for MLflowCallback.

### ISSUE THREAD

**Issue by seanswyi** [huggingface/transformers#28961]
### Feature request

Option to set not only the experiment name but also the tracking URI for MLflow.

### Motivation

My company and I use our own MLflow URI and all of our code has `mlflow.set_tracking_uri($URI)` inside. I'm not seeing such an option for the MLflowCallback and am only seeing an option to set the experiment.

The `run_name` seems to be using the `run_name` value in TrainingArguments, so there's not really any problem with that.

### Your contribution

It seems like adding a few lines of code to the `setup` method would do the trick.

https://github.com/huggingface/transformers/blob/345b9b1a6a308a1fa6559251eb33ead2211240ac/src/transformers/integrations/integration_utils.py#L952

**Comment by amyeroberts** [comment]
Hi @seanswyi, thanks for opening this feature request! 

The integrations are maintained by third party contributors, rather than the transformers team. If you or anyone else in the community would like to open a PR to add this we'd be happy to review!

**Comment by seanswyi** [comment]
Thanks for the heads up @amyeroberts! I'll submit a PR when I can.
