### ISSUE TITLE
Question about the use of bias in the Graphormer Model

### ISSUE THREAD

**Issue by sarah-af** [huggingface/transformers#28970]
Hi,

The documentation of the Graphormerconfig indicates that the parameter,
bias (bool, optional, defaults to True) — Uses bias in the attention module - unsupported at the moment.

I have 2 questions,
1. Is that the same attention bias introduced in the paper using the shortest path distance? Or where is it applied?
2. What does unsupported mean? I see in the src files that the attention bias has been implemented.

Many thanks!

**Comment by amyeroberts** [comment]
cc @clefourrier
