### ISSUE TITLE
Add Hiera model

### ISSUE THREAD

**Issue by p1atdev** [huggingface/transformers#28993]
### Model description

Hiera is a hierarchical vision transformer that is fast, powerful, and, above all, simple. It outperforms the state-of-the-art across a wide array of image and video tasks while being much faster.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

GitHub Repo: https://github.com/facebookresearch/hiera/ (but licensed under CC BY-NC 4.0)
arXiv: https://arxiv.org/abs/2306.00989

**Comment by Namangarg110** [comment]
Can I work on this ?

**Comment by amyeroberts** [comment]
@Namangarg110 Certainly! Feel free to open a PR when you're ready and ping us for review 🤗. To avoid issues from becoming too stale, we will prioritise the first open PR when reviewing over the first comment on issues.

**Comment by Namangarg110** [comment]
Thanks @amyeroberts. This is my first open-source issue. Would it be possible for you to please share any helpful resources or similar PR to understand the code structure?

**Comment by amyeroberts** [comment]
Sure! 

* Docs page: https://huggingface.co/docs/transformers/en/add_new_model
* Example model PR: https://github.com/huggingface/transformers/pull/26668

Adding models is quite a big project. If you want to tackle something smaller for your first issue to get used to the workflow of contributing to transformers, resolving a [good first issue](https://github.com/huggingface/transformers/labels/Good%20First%20Issue) is a great place to start.

**Comment by Namangarg110** [comment]
Thank you for the resources, @amyeroberts.

I've begun the task and have completed 50% of the work.

I recognize that contributing a new model can be exceptionally challenging, but I am eager to give it a try. :)

**Comment by qubvel** [comment]
Added in 
 - https://github.com/huggingface/transformers/pull/30356
