### ISSUE TITLE
Automatically add tokens when using model.generate()

### ISSUE THREAD

**Issue by MikeDean2367** [huggingface/transformers#28997]
### Feature request

When calling `model.generate()`, I hope that when a certain token is generated, a new token is automatically added after it. 

For example, when the model generates "The founder of Apple is Steve," I would like it to add a token "Jobs" at the end automatically. After that, the input of the next step is "The founder of Apple is Steve Jobs".

Below is a snippet of pseudocode to illustrate this concept:
```python
while eos_token:
  if current_last_token == 'Steve':
    # let the `rule` generate the next token
    current_token_seq.append('Jobs')
  else:
    # let the `model` generate the next token
    current_token_seq.append(generate_next_token())
```

### Motivation

In natural language processing, a single person's name can have multiple representations, including abbreviations, full names, and nicknames. In the context of my application, "Steve Jobs" is a frequently used term. Nonetheless, the model might produce variations such as "Steve jobs" with inconsistent capitalization or "Steven Paul Jobs," using his full name. These inconsistencies present challenges during the evaluation phase of my process.

### Your contribution

Do speculative decoding solve it?

**Comment by amyeroberts** [comment]
Hi @MikeDean2367, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by MikeDean2367** [comment]
ok, i'll go to the forums. Thanks!
