### ISSUE TITLE
`dataset.map` for tokenization hangs at 60%

### ISSUE THREAD

**Issue by sarahpannn** [huggingface/transformers#28998]
### System Info

- `transformers` version: 4.36.2
- Platform: Linux-5.15.0-92-generic-x86_64-with-glibc2.35
- Python version: 3.11.5
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.4.1
- Accelerate version: 0.25.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", use_fast=True)
tokenizer.pad_token = tokenizer.eos_token
dataset = load_dataset("sarahpann/AMPS")

dataset = dataset.map(lambda x: tokenizer(x["problem"] + x["step_by_step"], truncation=True, max_length=2048))
```

### Expected behavior

The map freezes at 60%. I've also tried a similar thing with batched tokenization, but that freezes at around 93%. There don't seem to be issues with the dataset and weird Unicode characters. A simple for loop method also freezes at 60%. The specific example it freezes at varies by run.

**Comment by ArthurZucker** [comment]
Hey, I ran this without issues, not stuck but just super slow. Might be a lot of things from the tokenizer to the dataset to your CPUs
