### ISSUE TITLE
Transformers trainer: All checkpoint restarts now FAILING

### ISSUE THREAD

**Issue by whr778** [huggingface/transformers#29059]
### System Info

 @muellerzr and @pacman100

In the trainer.py
Trainer code now requires trainer_state.json for checkpoint restarts
trainer.py does NOT save trainer_state.json in def _save_optimizer_and_scheduler(self, output_dir):
Recommend either removing the trainer_state.json dependency for checkpoint restarts 
or 
Adding at line 2497
```
       elif self.args.should_save:
            # deepspeed.save_checkpoint above saves model/optim/sched
            torch.save(self.optimizer.state_dict(), os.path.join(output_dir, OPTIMIZER_NAME))
            self.state.save_to_json(os.path.join(output_dir, TRAINER_STATE_NAME)) ## <= HERE
```

```
  File "/devel/venv/whr778/py3.11-st.11/lib/python3.11/site-packages/transformers/trainer.py", line 1513, in train
    state = TrainerState.load_from_json(os.path.join(resume_from_checkpoint, TRAINER_STATE_NAME))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Who can help?

 @muellerzr and @pacman100

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Trainer a Language Model
kill it 
try to do a checkpoint restart
Ran in a debugger all appropriate flags are set... file does not exist in the checkpoint as there is no code to save the file
Checkpoint restart requires trainer_state.json

### Expected behavior

Checkpoint restart should work as they used to

**Comment by whr778** [comment]
Forgot the version info... sorry about that guys
transformers             4.37.2

**Comment by pacman100** [comment]
Hello,

`trainer_state.json` is saved when calling `_save_checkpoint` at the given line below which is after the model, optimizer and schedulers are saved.

https://github.com/huggingface/transformers/blob/b2628086565e0eedf33f238fe2146f11087c0301/src/transformers/trainer.py#L2496

So, it should be saved properly and allow for reloading from the checkpoint as usual. You can see the following resume tests pass for 9 hours ago: https://github.com/huggingface/transformers/actions/runs/7925195377/job/21638061721

![Screenshot 2024-02-16 at 6 08 31 PM](https://github.com/huggingface/transformers/assets/13534540/ec2b1744-ca46-46bf-9a3b-e9a0e646d872)

**Comment by whr778** [comment]
Just confirmed... my bad had two training arguments stepping on each other... ran the debugger through TrainerControl to verify.   This can be closed.
