### ISSUE TITLE
FalconAttention Doesn't use `alibi` when `alibi` is not None if `_use_sdpa==True`

### ISSUE THREAD

**Issue by SamanehSaadat** [huggingface/transformers#29067]
### System Info

- `transformers` version: 4.37.0.dev0
- Platform: Linux-6.5.13-1rodete2-amd64-x86_64
- Python version: 3.10.13
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.2.0+cu121 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@fxmarty 
@ArthurZucker
@younesbelkada

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I found this issue when I was reading the Falcon code:
[This else](https://github.com/huggingface/transformers/blob/main/src/transformers/models/falcon/modeling_falcon.py#L477-L526) is related to when `alibi is not None`:
* When `_use_sdpa==False`, `alibi` is added to `attention_scores` [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/falcon/modeling_falcon.py#L503) 
* But when `_use_sdpa==True`, `alibi` hasn't been used anywhere in [this part of code](https://github.com/huggingface/transformers/blob/2f1003be86f11c8d97d7c2e6a7739dbb6fa795f2/src/transformers/models/falcon/modeling_falcon.py#L478-L490).

### Expected behavior

`alibi` should be used when `alibi` is not `None`.

**Comment by ArthurZucker** [comment]
HEy! Pretty sure that is because it's not supported in `sdpa` nor is `flash_attention`. We should / could raise an error however.

**Comment by fxmarty** [comment]
Hi @SamanehSaadat thank you for the notice, please refer to: https://github.com/huggingface/transformers/blob/2f1003be86f11c8d97d7c2e6a7739dbb6fa795f2/src/transformers/models/falcon/modeling_falcon.py#L1104-L1124. Alibi is merged into the attention bias. We do so at the top-level and not in every attention module.

**Comment by ArthurZucker** [comment]
Oh thanks @fxmarty for correcting me!
