### ISSUE TITLE
is_vision_availble() is slow and called a lot

### ISSUE THREAD

**Issue by collosi** [huggingface/transformers#29069]
### Feature request

Memoize the result of `is_vision_availble()`, because it depends on installed packages which are unlikely to change.

### Motivation

`is_vision_availble()` in import_utils.py is slow, in that it results in many calls to os.stat and os.list_dir, because it is checking import metadata.  Because it is used in places like `is_valid_image()`, it can be called A LOT when trying to bootstrap an image dataset.  For example in my use case of opening a PIL Image, and immediately transforming it with a transforms.Compose(), the calls to stat and list_dir account for more than half of the runtime.

### Your contribution

Sorry, I'm not a great python developer.

**Comment by EduardoPach** [comment]
@collosi can you share a minimal code snippet to reproduce your issue?

**Comment by KossaiSbai** [comment]
@collosi happy to take this on once you send elaborate on how to reproduce the bug

**Comment by bmuskalla** [comment]
A simple reproducer:

```
from transformers import AutoProcessor, Blip2ForConditionalGeneration
import requests
from PIL import Image
import timeit

url = 'https://avatars.githubusercontent.com/u/25720743?s=48&v=4'
image = Image.open(requests.get(url, stream=True).raw).convert('RGB')   
processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b")

def test():
    processor(image, return_tensors="pt")

print(timeit.timeit("test()", setup="from __main__ import test", number=5000))
```

Note that for each image processing, `is_vision_available` is called 63 times, directly or indirectly. I've pushed a PR (#29280) to cache this. In the above example, for 5000 images, we get to see a improvement from 13s->6s.
