### ISSUE TITLE
Help needed with interpretation of the MLP class

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#2907]
Hello,

I am having some trouble understanding the MLP function used in the Hugging Face GPT-2, which is found [here](https://github.com/huggingface/transformers/blob/73028c5df0c28ca179fbe565482a9c2143787f61/src/transformers/modeling_gpt2.py#L204).

Q1. For MLP, why are we setting the n_state to be equal to 3072, which is 4 * n_embd?
Q2. Below is the definition for the MLP class:
```python
class MLP(nn.Module):
    def __init__(self, n_state, config):  # in MLP: n_state=3072 (4 * n_embd)
        super().__init__()
        nx = config.n_embd
        self.c_fc = Conv1D(n_state, nx)
        self.c_proj = Conv1D(nx, n_state)
        self.act = gelu_new
        self.dropout = nn.Dropout(config.resid_pdrop)
```
in the MLP definition above, what exactly do the lines ``` Conv1D(n_state, nx)``` (the object ```self.c_fc```), and ``` Conv1D(nx, n_state)```   (the object ```self.c_proj```) do?

Thank you,

**Comment by tranvohuy** [comment]
h56cho: I'm not sure if you ask about the code or the algorithm.
As far as I understand from the code, the class MLP is a basic 2-layer neural network (2 consecutive conv1d + gelu activation). This will be used to construct a bigger [network](https://github.com/huggingface/transformers/blob/73028c5df0c28ca179fbe565482a9c2143787f61/src/transformers/modeling_gpt2.py#L215). I hope this (partially) answers your Q2 question.
Q1. For the code, I think the comment is related to the number 3072 mentioned in this [link](https://jalammar.github.io/illustrated-gpt2/)
