### ISSUE TITLE
Generation doesn't work as expected with input_embeds

### ISSUE THREAD

**Issue by dipta007** [huggingface/transformers#29093]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0+cu121 (False)
- Tensorflow version (GPU?): 2.15.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.8.1 (cpu)
- Jax version: 0.4.23
- JaxLib version: 0.4.23

### Who can help?

@gante 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Colab: https://colab.research.google.com/drive/1tIgcJVofkzTic9ChhG8rNAQmFjrE1HYd?usp=sharing

### Expected behavior

Output should be generated for both using `input_ids` or `inputs_embed`.
But when giving `inputs_embed`, it doesn't consider the input length in `max_length` stopping criteria. So it raises an exception when the output exceeds `model.max_length`.

**Comment by zucchini-nlp** [comment]
@dipta007 ,hi! This [PR](https://github.com/huggingface/transformers/pull/28994) should fix it

**Comment by gante** [comment]
@dipta007 as @zucchini-nlp wrote, if you add `!pip install --upgrade git+https://github.com/huggingface/transformers.git` on top of your notebook it will work 🤗

**Comment by dipta007** [comment]
Thanks
