### ISSUE TITLE
Flashatten2 avaiable should handle if hardware support or not?

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#29098]
For some docker images the flashattn installed, but v100 not support.
It will return True and raise error in runtime.

Also, since torch already support flash2 inside, add torch2.2 check and using inside version?

**Comment by amyeroberts** [comment]
Hi @lucasjinreal, thanks for opening an issue! 

Please make sure to follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and provide: 
* A minimal code reproducer
* All relevant error information including the full error traceback
* The running environment: run `transformers-cli env` in the terminal and copy-paste the output
