### ISSUE TITLE
altclip can not be traced by fx?

### ISSUE THREAD

**Issue by TXacs** [huggingface/transformers#29094]
### System Info

- `transformers` version: 4.37.1
- Platform: Linux-5.4.0-47-generic-x86_64-with-glibc2.17
- Python version: 3.8.13
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.3.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.2+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from config import load_config

from transformers import (
    AltCLIPModel,
    AltCLIPConfig,
)
from transformers.utils.fx import symbolic_trace

def main():
    config_kwarg = load_config("altclip")
    config = AltCLIPConfig(
            **config_kwarg
        )

    # create model
    model = AltCLIPModel(config)

    traced_model = symbolic_trace(model)

if __name__ == "__main__":
    main()
```

### Expected behavior

When I run the above code, it reports an error: `ValueError: You have to specify pixel_values.`

Somebody can help me？

**Comment by amyeroberts** [comment]
Hi @TXacs, thanks for raising this issue! 

You need to pass in `input_names` to `symbolic_trace`:

```py
from config import load_config

from transformers import (
    AltCLIPModel,
    AltCLIPConfig,
)
from transformers.utils.fx import symbolic_trace

def main():
    config_kwarg = load_config("altclip")
    config = AltCLIPConfig(
            **config_kwarg
        )

    # create model
    model = AltCLIPModel(config)

    traced_model = symbolic_trace(model, ['input_ids', 'pixel_values'])

if __name__ == "__main__":
    main()
```

**Comment by TXacs** [comment]
> Hi @TXacs, thanks for raising this issue!
> 
> You need to pass in `input_names` to `symbolic_trace`:
> 
> ```python
> from config import load_config
> 
> from transformers import (
>     AltCLIPModel,
>     AltCLIPConfig,
> )
> from transformers.utils.fx import symbolic_trace
> 
> def main():
>     config_kwarg = load_config("altclip")
>     config = AltCLIPConfig(
>             **config_kwarg
>         )
> 
>     # create model
>     model = AltCLIPModel(config)
> 
>     traced_model = symbolic_trace(model, ['input_ids', 'pixel_values'])
> 
> if __name__ == "__main__":
>     main()
> ```

Thanks a lot! It solved.
