### ISSUE TITLE
Cannot use time series transformer as encoder and gpt model as decoder using encoder decoder architecture from hugging face

### ISSUE THREAD

**Issue by nikhilajoshy** [huggingface/transformers#29107]
### System Info

-

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

EncoderDecoderModel.from_pretrained()

### Expected behavior

I want to use EncoderDecoderModel.from_pretrained() where huggingface/time-series-transformer-tourism-monthly is the encoder and openai-community/gpt2 as decoder but as mentioned in https://huggingface.co/blog/warm-starting-encoder-decoder, TS transformer does not have a tokenizer and hence not sure what to use as encoder input ids

**Comment by amyeroberts** [comment]
Hi @nikhilajoshy, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
