### ISSUE TITLE
RWKV5 tokenizer truncation

### ISSUE THREAD

**Issue by sedrick-keh-tri** [huggingface/transformers#29111]
### System Info

Python 3.10. Transformers 4.37.2

### Who can help?

@arthur

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained("RWKV/HF_v5-Eagle-7B", trust_remote_code=True)

    long_str = ""
    for i in range(10000):
       long_str = long_str + " " + str(i)

    print(len(long_str))        # 48890
    long_str_tokenized = tokenizer(long_str, truncation=True, max_length=2048)
    print(len(long_str_tokenized['input_ids']))        # 19900

### Expected behavior

Proper truncation to max_length

**Comment by amyeroberts** [comment]
cc @ArthurZucker

**Comment by ArthurZucker** [comment]
Hey! THanks for opening an issue. The problem is that you are using `trust_remote_code=True` and thus the `https://huggingface.co/RWKV/v5-Eagle-7B-HF/blob/main/tokenization_rwkv_world.py` file is used. The code is not on transformers yet! 

Use the tokenizer from #29095 should fix this already 🤗
