### ISSUE TITLE
missing "para" attribute in ARC dataset for multiple choice question answering model

### ISSUE THREAD

**Issue by nrjvarshney** [huggingface/transformers#2911]
# 🐛 Bug

## Information

Model I am using Roberta.

Language I am using the model on (English)

The problem arises when using:
* [ ] the official example scripts: (give details below)
**https://github.com/huggingface/transformers/blob/master/examples/utils_multiple_choice.py**

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
Multiple choice question answering

## To reproduce

1. run_multiple_choice.py 
with parameters as specified in the documentation replacing the task name to arc

In the data, there is no such parameter called "para"

contexts=[
                            options[0]["para"].replace("_", ""),
                            options[1]["para"].replace("_", ""),
                            options[2]["para"].replace("_", ""),
                            options[3]["para"].replace("_", ""),
                        ],

**Comment by nrjvarshney** [comment]
Got it. 
This parameter is for the context.

**Comment by zhanghuihui2** [comment]
May I know how do you solve this problem? I just ran into this problem.

**Comment by nrjvarshney** [comment]
You will have to add a "para" field for every choice - This is for adding knowledge. To get a baseline you can simply use a dummy text in that field 

`{
  "id": "MCAS_2000_4_6",
  "question": {
    "stem": "Which technology was developed most recently?",
    "choices": [
      {
        "text": "cellular telephone",
        "label": "A",
        "para": "fetched knowledge"
      },
      {
        "text": "television",
        "label": "B",
        "para": "fetched knowledge"
      },
      {
        "text": "refrigerator",
        "label": "C",
        "para": "fetched knowledge"
      },
      {
        "text": "airplane",
        "label": "D",
        "para": "fetched knowledge"
      }
    ]
  },
  "answerKey": "A"
}
`
