### ISSUE TITLE
WARNING: tokenization mismatch: 43 vs. 44. (ignored)

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#29126]
Recently there are many errors got either from fastchat or llava code base if using latest transfomers.

WARNING: tokenization mismatch: 43 vs. 44. (ignored)

What does this happen and how to dismiss it? Will it effect the final training result?

**Comment by amyeroberts** [comment]
Hi @lucasjinreal, 

Without a code sample to replicate, information about the running environment or more information about the error - including full trackback - there isn't much we can do to help you here.
