### ISSUE TITLE
Difficulty in adding custom model

### ISSUE THREAD

**Issue by El-chapo-007** [huggingface/transformers#29150]
### Feature request

Hi 
Hope all the team members of hugging face are well 

I am a student and currently doing work on nlp projects , although most of my journey was successful because well documented information for starters especially example notebooks but what part is confusing and difficult is to upload and create a custom model from scratch i have and several other users have difficulty in it could you please make a notebook for step by step guidence to help me and other researchers to focus on thier projects not on these lenghty procedures 

### Motivation

Difficulty in portting custom model

### Your contribution

Student

**Comment by El-chapo-007** [comment]
could you please add a Jupiter notebook template, as it would be alot more helpful as most of the other parts the hugging face team has put as a tutorial to better familirize with enviornment .....
And also my custom architecture  projects feed forward layer to the multiple of d_model,
as other models project it back to same dimension it just up_project and i have tested several other models but this model yeilds order of magnitude more performance with respect to number of parameters,hence i can deploy it on edge devices ..

But the issue as far as i know i don't have to use lm head liner layer but hugging face library automatically put we call a certain class for example AutoModelForCausalLM....

Since my model dimensions are same but in final liner layer how can I project it to multiple of d_model to final linear layer ...

**Comment by El-chapo-007** [comment]
also there is a bit confusion on https://huggingface.co/docs/transformers/custom_models   
vs  https://huggingface.co/docs/transformers/add_new_model

**Comment by amyeroberts** [comment]
Hi @El-chapo-007, 

We can definitely think about adding a jupyter notebook. In the meantime, you should be able to run the code snippets in the documentation in cells in your own notebook.

I'm not sure I understand your question about modifying the models. However, this is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

Regarding the documentation pages: 
* https://huggingface.co/docs/transformers/add_new_model outlines how to add a model into the transformers repo
* https://huggingface.co/docs/transformers/custom_models outlines how to add a model on the hub

**Comment by El-chapo-007** [comment]
thanks alot

**Comment by not-lain** [comment]
@El-chapo-007 you might consider checking this blogpost too 
https://huggingface.co/blog/not-lain/custom-architectures-with-huggingface
