### ISSUE TITLE
Plans to add DoRA?

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/transformers#29153]
### Feature request

Improves on LoRA by allowing magnitude fine-tuning.

### Motivation

Improved perplexity.

### Your contribution

Sebastien Bubeck has published demo code. https://github.com/rasbt/dora-from-scratch

**Comment by amyeroberts** [comment]
cc @younesbelkada @pacman100

**Comment by younesbelkada** [comment]
Hi @RonanKMcGovern ! 
Thanks for the feature request! There is already an ongoing work from @BenjaminBossan to add DoRA in PEFT: https://github.com/huggingface/peft/pull/1474

**Comment by RonanKMcGovern** [comment]
Closing as there is a PR underway.

**Comment by younesbelkada** [comment]
OK thank you @RonanKMcGovern !
