### ISSUE TITLE
To enter token in jupyter notebook issue

### ISSUE THREAD

**Issue by arda1906** [huggingface/transformers#29161]
I run this [from huggingface_hub import notebook_login
notebook_login() ] on cell and enter my token. but it doesn't work:(

**Comment by amyeroberts** [comment]
Hi @arda1906, thanks for raising an issue!

Without more information about the error i.e. what does it mean to "not work" and what is the expected behaviour? we won't be able to help you.  

From the snippet, it's not entirely clear how the code is being run, but there are two separate commands which should be entered on separate lines or cells

```py
from huggingface_hub import notebook_login

notebook_login()
```

**Comment by arda1906** [comment]
hi,I am giving details
> I am trying this code to train the model

>```python
>trainer = Trainer(model=model,args=training_args,
                 compute_metrics=compute_metrics,
                 train_dataset=emotion_encoded["train"],
                 eval_dataset=emotion_encoded["validation"],
                 tokenizer=tokenizer)
trainer.train()

>and I am facing this error:
>LocalTokenNotFoundError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.
>I have thought to apply the my token in the jupyter notebook like this:
>```
> ```python
> from huggingface_hub import notebook_login
> 
> notebook_login()
>
> ```
>help me please:(

**Comment by amyeroberts** [comment]
Hi @arda1906, are you running the notebook login cells before calling Trainer? Are you passing in a token to the interactive text box that appears when running notebook_login?

**Comment by arda1906** [comment]
> Hi @arda1906, are you running the notebook login cells before calling Trainer? Are you passing in a token to the interactive text box that appears when running notebook_login?

![20240221_210517](https://github.com/huggingface/transformers/assets/157398066/57ee7c71-1614-4c44-8dc2-144f47cafacd)
