### ISSUE TITLE
How to train a LM with a custom Dataset?

### ISSUE THREAD

**Issue by ohmeow** [huggingface/transformers#2916]
# ❓ Questions & Help

I'm attempting to build a LM following the tutorial here (https://huggingface.co/blog/how-to-train).

Unfortunately, it is incomplete.  It shows how to create a custom `Dataset` but not how to execute `run_language_modeling.py` so that it is used.  

**Any chance we can get the full script for training the LM, included how to specify our custom dataset?**

**Comment by julien-c** [comment]
This is in process of being addressed at huggingface/blog#3

(You'll need to tweak the code of `run_language_modeling.py`, this is not – yet – a code-free tutorial)
