### ISSUE TITLE
Add Mamba model and Architecture.

### ISSUE THREAD

**Issue by Tanmaypatil123** [huggingface/transformers#29164]
### Model description

Mamba is a new state space model architecture showing promising performance on information-dense data such as language modeling, where previous subquadratic models fall short of Transformers. It is based on the line of progress on [structured state space models](https://github.com/state-spaces/s4), with an efficient hardware-aware design and implementation in the spirit of [FlashAttention](https://github.com/Dao-AILab/flash-attention).

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Github Repo : [https://github.com/state-spaces/mamba](https://github.com/state-spaces/mamba) (licensed under Apache 2.0)

model checkpoints ; [https://huggingface.co/state-spaces/mamba-2.8b-slimpj](https://huggingface.co/state-spaces/mamba-2.8b-slimpj)
Author :  @tridao

**Comment by amyeroberts** [comment]
Hi @Tanmaypatil123, thanks for opening this new model request! 

There's an open PR to add Mamba here #28094 and an existing issue here #28086

**Comment by ArthurZucker** [comment]
This was completed by #29458
