### ISSUE TITLE
Model cache does not work

### ISSUE THREAD

**Issue by bitcoinvsalts** [huggingface/transformers#29178]
### System Info

I am ubuntu, torch = "2.0.0"

The following code always re-download the models instead of re-using the cached files:

`        adapter = T2IAdapter.from_pretrained("TencentARC/t2i-adapter-canny-sdxl-1.0",
                                            torch_dtype=torch.float16, 
                                            varient="fp16").to(accelerator.device)

        model_id = 'stabilityai/stable-diffusion-xl-base-1.0'
        logger.info(f"model loading..")
        euler_a = EulerAncestralDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
        logger.info(f"model loading...")
        vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)

        logger.info(f"model loading....")
        pipe = StableDiffusionXLAdapterPipeline.from_pretrained(
            model_id,
            vae=vae,
            adapter=adapter,
            scheduler=euler_a,
            torch_dtype=torch.float16,
            variant="fp16"
        ).to(accelerator.device)
        pipe.enable_xformers_memory_efficient_attention()
        logger.info(f"model weights loading")
        pipe.load_lora_weights(
            "stabilityai/stable-diffusion-xl-base-1.0", weight_name="sd_xl_offset_example-lora_1.0.safetensors"
        )`
      
I also tried with the `cache_dir` param but same result.  
        
<img width="1377" alt="Screenshot 2024-02-21 at 11 32 22 AM" src="https://github.com/huggingface/transformers/assets/13439477/562c4f1e-b033-4c03-883b-9dcf3b6a579a">

        
        

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`        adapter = T2IAdapter.from_pretrained("TencentARC/t2i-adapter-canny-sdxl-1.0",
                                            torch_dtype=torch.float16, 
                                            varient="fp16").to(accelerator.device)

        model_id = 'stabilityai/stable-diffusion-xl-base-1.0'
        logger.info(f"model loading..")
        euler_a = EulerAncestralDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
        logger.info(f"model loading...")
        vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)

        logger.info(f"model loading....")
        pipe = StableDiffusionXLAdapterPipeline.from_pretrained(
            model_id,
            vae=vae,
            adapter=adapter,
            scheduler=euler_a,
            torch_dtype=torch.float16,
            variant="fp16"
        ).to(accelerator.device)
        pipe.enable_xformers_memory_efficient_attention()
        logger.info(f"model weights loading")
        pipe.load_lora_weights(
            "stabilityai/stable-diffusion-xl-base-1.0", weight_name="sd_xl_offset_example-lora_1.0.safetensors"
        )`

### Expected behavior

use the cached models/files and not download any files from the internet

**Comment by amyeroberts** [comment]
Hi @bitcoinvsalts, thanks for raising this issue! 

Could you isolate the lines which trigger the redownloads - giving us the minimal amount of code to reproduce will help us figure out what's happening. 

A few questions / comments: 
* Can you share your running environment: run `transformers-cli env` in the terminal and copy-paste the output
* Where are you running the code? Is it locally or remote? 
* Are you setting any global params for the cache dir e.g. `HF_HOME`? 


If you run the following in a python session, what do you get as output? 

```py
In [1]: from transformers.utils.hub import HF_MODULES_CACHE

In [2]: HF_MODULES_CACHE
```

**Comment by amyeroberts** [comment]
If you create an AMI and start an new instance with it, I'm not sure if folders like `.cache` will be copied along. 

You can easily check this by just running `ls /home/ubuntu/.cache/` in the command line before running any python command. 

If you run `from_pretrained` again on the new instance, does it redownload again?

**Comment by bitcoinvsalts** [comment]
yes .cache exists with all correct model files in it at` /home/ubuntu/.cache/`

> If you run from_pretrained again on the new instance, does it redownload again?

Yes, that's my weird issue.

**Comment by amyeroberts** [comment]
@bitcoinvsalts OK, that's weird. I suggest opening an issue in the diffusers repo and linking to this one, as the problem seems to be coming from the SD pipeline, which isn't handled by transformers
