### ISSUE TITLE
Bug:    TypeError: 'AcceleratorConfig' object does not support item assignment

### ISSUE THREAD

**Issue by heyaudace** [huggingface/transformers#29183]
### System Info

transformers: transformers-4.38.0
accelerate: accelerate-0.27.2
platform: linux
python: 3.10

### Who can help?

Training using accelerate (code section below in the trainer) fails using latest transformers (versions mentioned above)

```
        if is_accelerate_available():
            if not isinstance(self.accelerator_config, (AcceleratorConfig, dict)):
                if self.accelerator_config is None:
                    self.accelerator_config = AcceleratorConfig()
                else:
                    self.accelerator_config = AcceleratorConfig.from_json_file(self.accelerator_config)
            if self.dispatch_batches is not None:
                warnings.warn(
                    "Using `--dispatch_batches` is deprecated and will be removed in version 4.41 of 🤗 Transformers. Use"
                    " `--accelerator_config {'dispatch_batches':VALUE} instead",
                    FutureWarning,
                )
>               self.accelerator_config["dispatch_batches"] = self.dispatch_batches
```

```
               TypeError: 'AcceleratorConfig' object does not support item assignment
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Run training using accelerate with environment mentioned above. 

### Expected behavior

Not expected to crash. Issue doesn't arise with transformers version less than one above 

----
Additional information: 
- Seems to come from https://github.com/huggingface/transformers/blame/fc37f38915372c15992b540dfcbbe00a916d4fc6/src/transformers/training_args.py#L1751 
- PR https://github.com/huggingface/transformers/pull/28664 (cc @muellerz)

**Comment by amyeroberts** [comment]
Cc @muellerzr and @ArthurZucker as it's a possible breaking change on the latest release

**Comment by stillmatic** [comment]
+1, fails from python launcher as well, not just accelerate launcher.

seems workaround is to replace `split_batches: True` in trainingargs with:

```
        accelerator_config={
            "dispatch_batches": True,
        },
``` 

guess deprecation just came a little early :)

**Comment by heyaudace** [comment]
Thanks for the fix @muellerzr

**Comment by Haruka1307** [comment]
Thx! But I‘m still confused about how can I fix it ,by upgrading transformers?

**Comment by amyeroberts** [comment]
@Haruka1307 this isn't yet part of a version release. To have this recent fix, you'll need to install from source: `pip install git+https://github.com/huggingface/transformers`
