### ISSUE TITLE
Fast tokenizers ignore `add_special_tokens=False`

### ISSUE THREAD

**Issue by bryant1410** [huggingface/transformers#2919]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Bert

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```python
from transformers import AutoTokenizer

pretrained_model_name = "bert-base-cased"

fast_tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name)
slow_tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name, use_fast=False)

text = "hello"

assert fast_tokenizer.encode(text, add_special_tokens=False) == slow_tokenizer.encode(text, add_special_tokens=False)
```

## Expected behavior

The fast tokenizers shouldn't add the special tokens if `add_special_tokens` is equal to `False`.

## Environment info

     
- `transformers` version: 2.5.0
- Platform: Linux-4.15.0-76-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.4
- PyTorch version (GPU?): 1.4.0 (True)
- Tensorflow version (GPU?): 2.0.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by dirkgr** [comment]
This works now (but I can't close the issue).

**Comment by bryant1410** [comment]
I see now that it works with some changes:

```python
from transformers import AutoTokenizer

pretrained_model_name = "bert-base-cased"

fast_tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name,
        add_special_tokens=False, use_fast=True)
slow_tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name)

text = "hello"

assert fast_tokenizer.encode(text) == slow_tokenizer.encode(text, add_special_tokens=False)
```

However, I see `add_special_tokens` needs to be specified differently in the fast version (init) and in the slow version (encode). Can it be made more homogeneous? I'll leave this issue open for this because the fast version still ignores it in `encode` and there's this discrepancy (maybe the slow version can be changed then).

**Comment by dirkgr** [comment]
It also doesn't work for `roberta-base`.

**Comment by n1t0** [comment]
In the last version, available on `master` for now, we actually changed this to match the slow version. So in all cases, `add_special_tokens` should be specified with `tokenize`, `encode` etc, and not during initialization.
