### ISSUE TITLE
Device Mismatch Error when Exporting Hugging Face's BERTModel to TorchScript

### ISSUE THREAD

**Issue by lsrock1** [huggingface/transformers#29205]
### System Info

- `transformers` version: 4.37.1
- Platform: Linux-4.18.0-477.27.1.el8_8.x86_64-x86_64-with-glibc2.31
- Python version: 3.10.13
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU): 2.1.2 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. export in cpu
```
from transformers import BertModel, BertTokenizer
import torch

model = BertModel.from_pretrained('bert-base-multilingual-uncased', torchscript=True)
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-uncased')

input_test = torch.ones([1, 20]).long()

script_model = torch.jit.trace(model, [input_test])
torch.jit.save(script_model, 'test.pt')
```

2. load and inference in gpu
```
import torch

input_test = torch.ones([1, 20]).long()
script_model = torch.jit.load('test.pt', map_location='cuda')
script_model(input_test.cuda())
```

3. error
```
class BertSelfAttention(Module):
  File "code/__torch__/transformers/models/bert/modeling_bert.py", line 175, in forward
    attention_scores = torch.matmul(query_layer, torch.transpose(key_layer, -1, -2))
    attention_scores0 = torch.div(attention_scores, CONSTANTS.c2)
    input = torch.add(attention_scores0, attention_mask)
            ~~~~~~~~~ <--- HERE
    input2 = torch.softmax(input, -1)
    context_layer = torch.matmul((dropout).forward(input2, ), value_layer)
....
....
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

The device variable creating tensors remains fixed during tracing, necessitating dynamic adjustment for flexibility.
https://github.com/huggingface/transformers/blob/2a9b1f80c45cab19b542bc7cc004937d39d6f6fb/src/transformers/models/bert/modeling_bert.py#L968-L974

### Expected behavior

Ensuring traced models operate on different devices(cpu -> gpu, gpu -> cpu)

**Comment by ArthurZucker** [comment]
cc @fxmarty maybe optimum supports it?

**Comment by lsrock1** [comment]
@ArthurZucker can I send a PR?

**Comment by fxmarty** [comment]
@lsrock1 for sure

**Comment by amyeroberts** [comment]
Gentle ping @fxmarty

**Comment by amyeroberts** [comment]
cc @IlyasMoutawwakil
