### ISSUE TITLE
Bug in latest version of `trainer.py` leads to training not starting for making Reward Model

### ISSUE THREAD

**Issue by armsp** [huggingface/transformers#29216]
### System Info

- `transformers` version: 4.39.0.dev0
- Platform: Linux-3.10.0-1160.108.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.9
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.25.0.dev0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu118 (False)
- Tensorflow version (GPU?): 2.14.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Just instantiate the RewardTrainer object - 
```
trainer = RewardTrainer(
    model = model,
    args = training_args,
    tokenizer= tokenizer,
    train_dataset= train_data,
    eval_dataset= val_data,
    peft_config= peft_config
)
```
And I get the error -
```
/python3.9/site-packages/trl/trainer/reward_trainer.py:189: UserWarning: When using RewardDataCollatorWithPadding, you should set `remove_unused_columns=False` in your RewardConfig we have set it for you, but you should do it yourself in the future.
  warnings.warn(
Traceback (most recent call last):
  File "/cluster/TRAINREWARDMODEL.py", line 189, in <module>
    trainer = RewardTrainer(
  File "/python3.9/site-packages/trl/trainer/reward_trainer.py", line 198, in __init__
    super().__init__(
  File "/python3.9/site-packages/transformers/trainer.py", line 367, in __init__
    self.create_accelerator_and_postprocess()
  File "/python3.9/site-packages/transformers/trainer.py", line 4127, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(
TypeError: __init__() got an unexpected keyword argument 'use_seedable_sampler'
```
Unfortunately I opened this issue in trl but its not a issue from there and I cannot close it https://github.com/huggingface/trl/issues/1354 it is clearly an issue in the transformers library.

**Note**: my code was working just fine until I updated the libraries. I am NOT using Accelerate...not even importing it.

### Expected behavior

The `RewardTrainer` should initialize and just work.

**Comment by jpWang** [comment]
Hi, I update accelerate and it can work now for me:
`pip install accelerate==0.27.2`

**Comment by armsp** [comment]
You are right, it does work after updating `accelerate`

**Comment by xiaxin1998** [comment]
I got the same issue when I finetune Llama-2-7b-chat-hf. and upgrading accelerate version is not working.
Could you help?

**Comment by xiaxin1998** [comment]
srun torchrun --nproc_per_node=1 --master_port=1207 finetune.py \
    --base_model Llama-2-7b-chat-hf \
    --data_path Beauty \
    --task_type sequential \
    --cache_dir cache_dir/ \
    --output_dir output_dir/ \
    --batch_size 16 \
    --micro_batch_size 1 \
    --num_epochs 3 \
    --learning_rate 0.0003 \
    --cutoff_len 4096 \
    --val_set_size 0 \
    --lora_r 16 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[gate_proj, down_proj, up_proj]' \
    --train_on_inputs False \
    --add_eos_token False \
    --group_by_length False \
    --prompt_template_name alpaca \
    --lr_scheduler 'cosine' \
    --warmup_steps 100



and my env:
bitsandbytes==0.37.2
accelerate==0.21.0
appdirs
loralib
black
black[jupyter]
datasets
fire
peft
transformers>=4.31.0
sentencepiece
wandb
scipy
numpy
sentence_transformers
scikit-learn
pandas

i tried a lot versions of transformers, accelerate and they are not working at all.
I still got this error.

**Comment by dali-does** [comment]
> srun torchrun --nproc_per_node=1 --master_port=1207 finetune.py --base_model Llama-2-7b-chat-hf --data_path Beauty --task_type sequential --cache_dir cache_dir/ --output_dir output_dir/ --batch_size 16 --micro_batch_size 1 --num_epochs 3 --learning_rate 0.0003 --cutoff_len 4096 --val_set_size 0 --lora_r 16 --lora_alpha 16 --lora_dropout 0.05 --lora_target_modules '[gate_proj, down_proj, up_proj]' --train_on_inputs False --add_eos_token False --group_by_length False --prompt_template_name alpaca --lr_scheduler 'cosine' --warmup_steps 100
> 
> and my env: bitsandbytes==0.37.2 accelerate==0.21.0 appdirs loralib black black[jupyter] datasets fire peft transformers>=4.31.0 sentencepiece wandb scipy numpy sentence_transformers scikit-learn pandas
> 
> i tried a lot versions of transformers, accelerate and they are not working at all. I still got this error.

@xiaxin1998 Your accelerate version is 0.21.0 here, did you try with the latest version as well? The above solution (updating accelerate to 0.28.0 in my case), works for me.

**Comment by xiaxin1998** [comment]
> > srun torchrun --nproc_per_node=1 --master_port=1207 finetune.py --base_model Llama-2-7b-chat-hf --data_path Beauty --task_type sequential --cache_dir cache_dir/ --output_dir output_dir/ --batch_size 16 --micro_batch_size 1 --num_epochs 3 --learning_rate 0.0003 --cutoff_len 4096 --val_set_size 0 --lora_r 16 --lora_alpha 16 --lora_dropout 0.05 --lora_target_modules '[gate_proj, down_proj, up_proj]' --train_on_inputs False --add_eos_token False --group_by_length False --prompt_template_name alpaca --lr_scheduler 'cosine' --warmup_steps 100
> > and my env: bitsandbytes==0.37.2 accelerate==0.21.0 appdirs loralib black black[jupyter] datasets fire peft transformers>=4.31.0 sentencepiece wandb scipy numpy sentence_transformers scikit-learn pandas
> > i tried a lot versions of transformers, accelerate and they are not working at all. I still got this error.
> 
> @xiaxin1998 Your accelerate version is 0.21.0 here, did you try with the latest version as well? The above solution (updating accelerate to 0.28.0 in my case), works for me.

Yes I tried. and I tried a lot versions. they are not working at all.

**Comment by gabormadarasz2117** [comment]
> > @xiaxin1998 Your accelerate version is 0.21.0 here, did you try with the latest version as well? The above solution (updating accelerate to 0.28.0 in my case), works for me.
> 
> Yes I tried. and I tried a lot versions. they are not working at all.

This was also the case for me, as long as I had imports in several cells of the notebook. When I imported all modules in the first cell, the code ran.

**Comment by spacewalk01** [comment]
got the same error

**Comment by susmitabhatt** [comment]
Tried all the suggested solutions but still getting the same error "TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'". Kindly help.

**Comment by amyeroberts** [comment]
@susmitabhatt Are you running with `pip install -U accelerate` at the top of the notebook and in a fresh session i.e. you've restarted the kernel?

**Comment by susmitabhatt** [comment]
@amyeroberts Hi. Yes. 

!pip install git+https://github.com/huggingface/datasets.git
!pip install git+https://github.com/huggingface/transformers.git
!pip install torchaudio
!pip install librosa
!pip install jiwer
!pip install accelerate==0.28.0

This I am running at the top of the notebook. Also I restarted multiple times yet the same error "TypeError: Accelerator.init() got an unexpected keyword argument 'use_seedable_sampler'"
Kindly help.

**Comment by amyeroberts** [comment]
@susmitabhatt Can you share a colab notebook with the code being run?

**Comment by susmitabhatt** [comment]
@amyeroberts Sure. Please find the notebook link.
https://colab.research.google.com/drive/1hy_8TkTw3WZItEgEdz7RtLu_YztRztbB?usp=sharing

Thank you.

**Comment by amyeroberts** [comment]
Hi @susmitabhatt, thanks for sharing. Unfortunately I can't run the notebook, as I don't have access to the data being used. There are also a lot of cells in the notebook. What would be most helpful is: 
* Preparing a notebook with the minimal amount of code, reproducing the error
* Sharing a fulltrace back of the error encountered
* Sharing a run and rendered notebook showing the output and where the error occurs

**Comment by susmitabhatt** [comment]
@amyeroberts I understand. I will be re-sharing the code shortly with the said changes. 
Thanks a lot.

**Comment by iffyaiyan** [comment]
I am still facing the error. I have even updated the accelerate to `accelerate==0.21.0 -U` but still getting the error.

**Comment by amyeroberts** [comment]
@iffyaiyan Could you share a reproducible code snippet?

**Comment by iffyaiyan** [comment]
@amyeroberts, the issue got fixed. I just updated the accelerate==0.27.2
Have followed the below steps.
1. !pip install accelerate -U
2. !pip install accelerate==0.27.2

**Comment by amyeroberts** [comment]
Hi @iffyaiyan, thanks for sharing this solution. If you're installing a specific version of accelerate i.e. v0.27.2, it shouldn't be necessary to do the first step. 

If you just run `pip install -U accelerate`, does it not work? If not, then it means we might have a regression we need to resolve

**Comment by carlosrojasg** [comment]
> Hi, I update accelerate and it can work now for me: `pip install accelerate==0.27.2`

This fixed my issue
