### ISSUE TITLE
Tried to attach a forward hook to the self-attention layer but failed.

### ISSUE THREAD

**Issue by ArgusK17** [huggingface/transformers#29247]
### System Info

- `transformers` version: 4.38.1
- Platform: Linux-4.18.0-477.10.1.el8_8.x86_64-x86_64-with-glibc2.28
- Python version: 3.9.18
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.1
- Accelerate version: 0.26.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.2+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I attempted to attach a forward_pre hook to the self attention layer but failed. The input was simply a empty token.  I'm wondering if this could be a bug. If not, perhaps this issue should be assigned to Feature request. XD

```python
from transformers import LlamaForCausalLM, LlamaTokenizer, GenerationConfig
import transformers
import torch

path="./llama_hf/7b"

tokenizer = LlamaTokenizer.from_pretrained(path, padding_side='left')
tokenizer.pad_token = tokenizer.eos_token
model = LlamaForCausalLM.from_pretrained(path, device_map="cuda", attn_implementation="eager")

def forward_pre_hook(module, inputs):
    print(inputs)
    return

module_hook = model.model.layers[0].self_attn  # You need to identify the correct submodule
hook = module_hook .register_forward_pre_hook(forward_pre_hook)

prompts=["test"]
inputs = tokenizer(prompts, return_tensors="pt", padding=True)
input_ids = inputs["input_ids"].cuda()
outputs=model(input_ids)

>>> ()

hook.remove()
```

### Expected behavior

I would greatly appreciate it if someone could take the time to explain why the forward_pre hook failed in this case.

**Comment by ArthurZucker** [comment]
From [the doc of torch](https://pytorch.org/docs/stable/generated/torch.nn.modules.module.register_module_forward_pre_hook.html):
>The input contains only the positional arguments given to the module. Keyword arguments won’t be passed to the hooks and only to the forward. 

The forward is defined by:
```python 
        hidden_states, self_attn_weights, present_key_value = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_value=past_key_value,
            output_attentions=output_attentions,
            use_cache=use_cache,
            cache_position=cache_position,
            **kwargs,
        )
```
