### ISSUE TITLE
Transformers Generation config for ImageToText models

### ISSUE THREAD

**Issue by romyschneider04** [huggingface/transformers#29245]
### System Info

![IMG_2871](https://github.com/huggingface/transformers/assets/154731707/e4e89360-eda5-4887-9463-8217da70387b)

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I have transformers version 4.37.2. When I try to send prediction to ImageToText models, an attribute error raises- “GenerationConfig object has no attribute ‘_original_object_hash’”. 
I initiate Pipeline object for the model, which is called model_pipeline, and I call  model_pipeline.forward function. I have tried to debug it, and saw that there is a call to a key in the dict which does not exist, that’s why it fails. 
The GeneratorConfig has been changed during the versions, so is the code in transformers/generation/utils. 
In the old version there is no ‘_original_object_hash’ key, and the code does not uses this key. In the new version there is no such key, but the code requests this key in order to make sure the model config was not changed. 
That’s why the program fails in version 4.37.2.
When I run the code with transformers version 4.31.0 everything seems to be working just fine. 
The code runs in GPU environment 

### Expected behavior

I would expect ImageToText models to return prediction.

**Comment by romyschneider04** [comment]
Added two pictures to demonstrate the generation_config object- its keys and values. 
As you can see no such key as ‘_original_object_hash’ exists, nor the code in version 4.31.0 uses it. Unlike version 4.37.2.
![IMG_2873](https://github.com/huggingface/transformers/assets/154731707/b7f2165b-f629-4e5e-8212-be4160f37ed6)
![IMG_2872](https://github.com/huggingface/transformers/assets/154731707/269e4c84-ac96-41c3-9347-1635b9d73ded)

**Comment by molbap** [comment]
Hi, thanks for the issue! For readability, feel free to copy&paste your code and errors encountered in the issue conversation.
Do you have a reproducible script for this error? For instance, the example script with your modifications? `_original_object_hash` is initialized with a hash of the config if `generation_config` is `None` only, but you seem to pass it.
