### ISSUE TITLE
4.38 showing Grad_norm in log (when used with wandb) as tensors thus giving error while saving with json

### ISSUE THREAD

**Issue by deshwalmahesh** [huggingface/transformers#29270]
### System Info

`transformers==4.38`

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Use `wandb` logging with 4.38. Same script runs smoothly on `4.37` but breaks with the newer one as grad norms are logged too

### Expected behavior

Error while serializing the grad norm tensors in training logs

**Comment by onenotell** [comment]
modify  dist-packages/transformers/trainer.py   

self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
==》
self._maybe_log_save_evaluate(tr_loss, grad_norm.item(), model, trial, epoch, ignore_keys_for_eval)

**Comment by zealota** [comment]
In my case, I changed the code as follow:

https://github.com/huggingface/transformers/blob/831bc25d8fdb85768402f772cf65cc3d7872b211/src/transformers/trainer.py#L2403

before:
```
logs["grad_norm"] = grad_norm
```

after:
```
logs["grad_norm"] = grad_norm if isinstance(grad_norm, (int, float)) else grad_norm.item()
```

**Comment by ArthurZucker** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
This should be fixed now I believe, can you try installing from main? (`pip install git+https://github.com/huggingface/transformers`)
