### ISSUE TITLE
Invalid Version Error with Packaging Library for Torch Version "2.0.0.nv23.05"

### ISSUE THREAD

**Issue by Enes-Yaman** [huggingface/transformers#29286]
We are encountering an issue where the packaging library is unable to parse the Torch version string "2.0.0.nv23.05". This problem arises when trying to import the transformers library, specifically during the dependency version check for Torch. The error suggests that the version string does not conform to the expected format.

### System Info

Environment:

Device: NVIDIA Jetson AGX Orin
Docker Image: dustynv/ros:noetic-pytorch-l4t-r35.3.1
Python Version: 3.8.10
CUDA : 11.4.239
cuDNN : 8.4.1.50
Jetpack: 5.0.2 GA
Torch Version: 2.0.0.nv23.05

### Reproduction

1. Use the NVIDIA Orin device with the specified Docker image (dustynv/ros:noetic-pytorch-l4t-r35.3.1).
2. Attempt to import the transformers library in a Python 3.8 environment.
3. The import process fails with the following traceback:
`Traceback (most recent call last):
  File "/src/main.py", line 17, in <module>
    from segmentor import Segmentor
  ...
  File "/usr/local/lib/python3.8/dist-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '2.0.0.nv23.05'
`

### Expected behavior

The packaging library should be able to parse the Torch version string "2.0.0.nv23.05" without raising an InvalidVersion error, allowing the transformers library to be imported successfully.

**Comment by ArthurZucker** [comment]
Hey! I don't think this is related to transformers specifically
