### ISSUE TITLE
Is it a BUG when check all the imports in which may not be used？

### ISSUE THREAD

**Issue by Tyx-main** [huggingface/transformers#29291]
### System Info

transformers：4.38.1

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When I load a model such as deepseek-moe as follow：

`
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.bfloat16, device_map="auto")
`

If there is a snippet like this in modeling_deepseek.py:

`
if is_flash_attn_2_available():
    from flash_attn import flash_attn_func, flash_attn_varlen_func
    from flash_attn.bert_padding import index_first_axis, pad_input, unpad_input  # noqa
`

If I have not install flash_attn, there will be an ERROR in dynamic_module_utils.py, line 180, in check_imports:

`
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run pip install flash_attn 
`

It seems not reasonable, it is a BUG when check all the imports in which may not be used？

### Expected behavior

The codes can run when I have not install flash_attn

**Comment by ArthurZucker** [comment]
Beg! Sorry which modeling code are you referring too? 
Deep seek moe is not part of `transformers`

**Comment by Tyx-main** [comment]
thanks, maybe I should ckeck out again
