### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'xla'  when using trainer for training a model

### ISSUE THREAD

**Issue by shub-kris** [huggingface/transformers#29314]
### System Info

transformers: 4.37.2 
torch: 2.1 
torch_xla: 2.1

Dockerfile: [Link](https://gist.github.com/shub-kris/6a9c7ef4650fcfd715870eaa6cc8be0b#file-dockerfile3)

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Setup your Environment

Create and SSH into Google Cloud VM:
```bash
 gcloud alpha compute tpus tpu-vm create tpu-vm --zone=us-west4-a --accelerator-type=v5litepod-8 --version v2-alpha-tpuv5-lite
 gcloud alpha compute tpus tpu-vm ssh tpu-vm --zone=us-west4-a
```

Build Docker Image with the[ Dockerfile](https://gist.github.com/shub-kris/6a9c7ef4650fcfd715870eaa6cc8be0b#file-dockerfile3) and run the container
```
sudo docker build -t pytorch-tpu-4.37.2:latest .
sudo docker run -it -v $(pwd):/workspace --net=host --privileged pytorch-tpu-4.37.2:latest bash
```
### Run the Script

Run the [test-transformers-trainer.py](https://gist.github.com/shub-kris/6a9c7ef4650fcfd715870eaa6cc8be0b#file-test-transformers-trainer-py) with
```
export PJRT_DEVICE=TPU
python workspace/test-transformers-trainer.py

```

## Error

File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 199, in forward
   ctx.device_autocast_kwargs, ctx.cpu_autocast_kwargs = _get_autocast_kwargs(
 File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 168, in _get_autocast_kwargs
   elif _supports_autocast(device):
 File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 187, in _supports_autocast
   device_module = _get_device_module(device)
 File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 67, in _get_device_module
   device_module = getattr(torch, device)
 File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 1833, in __getattr__
   raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'xla'

## References to solve/debug the error
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/torch-neuronx/introducing-pytorch-2-1.html#attributeerror-module-torch-has-no-attribute-xla-failure

The solution is to use torch_xla.utils.checkpoint.checkpoint instead of torch.utils.checkpoint.checkpoint as the checkpoint function while wrapping pytorch modules for activation checkpointing. Also set use_reentrant=True while calling the torch_xla checkpoint function. Failure to do so will lead to XLA currently does not support use_reentrant==False error. For more details on checkpointing, refer the [documentation](https://pytorch.org/docs/stable/checkpoint.html).

### Expected behavior

It should run successfully.

**Comment by allenwang28** [comment]
I think we need to add a codepath in `Trainer` to enable gradient checkpointing for torch_xla using [this API](https://github.com/pytorch/xla/blob/master/torch_xla/utils/checkpoint.py)

**Comment by shub-kris** [comment]
I think we can close this issue as discussed here: https://github.com/pytorch/xla/issues/6611#issuecomment-1967860548

> The native grad ckpt won't work in any cases. We need to apply some special treatment for the XLA compiler to make grad ckpt working. Those are implemented here: https://github.com/pytorch/xla/blob/master/torch_xla/utils/checkpoint.py
> 
> However, I do think we should able to integrate our grad ckpt into HF such that users don't need to specify xla_fsdp_grad_ckpt in FSDP anymore

**Comment by steveepreston** [comment]
Still facing `AttributeError: module 'torch' has no attribute 'xla'`
