### ISSUE TITLE
All chunks except the first one ignore `num_beams` in Whisper long-form transcription

### ISSUE THREAD

**Issue by cifkao** [huggingface/transformers#29312]
### System Info

- `transformers` version: 4.39.0.dev0 (`dabe855`)

### Who can help?

@patrickvonplaten @sanchit-gandhi

### Reproduction

In `WhisperGenerationMixin.generate_with_fallback()`, the `kwargs` argument [is modified in-place](https://github.com/huggingface/transformers/blob/dabe8556686a5727f7b707099967c8ce8ff16e96/src/transformers/models/whisper/generation_whisper.py#L776) by `kwargs.pop("num_beams", 1)`, which results in the following problems:
1. Subsequent iterations of the fallback loop will use `num_beams=1` (although this has no effect provided that temperature 0 appears only once in the temperature list).
2. More importantly, since `kwargs` is passed by reference (and not via the `**kwargs` syntax), modifications to it propagate to the caller and to subsequent calls of `generate_with_fallback`, so **every chunk except for the first one will always use `num_beams=1`**.

### Expected behavior

The specified `num_beams` should be used for all chunks.

**Comment by ArthurZucker** [comment]
This sounds like a pretty huge bug, do you have a reproducer?

**Comment by cifkao** [comment]
@ArthurZucker How is this for a reproducer?

```python
import datasets
from transformers import AutoProcessor, GenerationMixin, WhisperForConditionalGeneration
import numpy as np

processor = AutoProcessor.from_pretrained("openai/whisper-tiny")
model = WhisperForConditionalGeneration.from_pretrained("openai/whisper-tiny")

orig_generate = GenerationMixin.generate


def generate(self, *args, **kwargs):
    print("num_beams:", args[1].num_beams)
    return orig_generate(self, *args, **kwargs)


GenerationMixin.generate = generate

ds = datasets.load_dataset(
    "google/fleurs", "en_us", split="test", trust_remote_code=True
)
ds = ds = ds.cast_column("audio", datasets.Audio(sampling_rate=16000))
raw_audio = np.concatenate([x["array"].astype(np.float32) for x in ds[:16]["audio"]])

inputs = processor(
    [raw_audio],
    return_tensors="pt",
    truncation=False,
    padding="longest",
    return_attention_mask=True,
    sampling_rate=16_000,
)

model.generate(
    **inputs,
    num_beams=2,
    task="transcribe",
    language="en",
)
```

Before fix:
```
num_beams: 2
num_beams: 1
num_beams: 1
num_beams: 1
num_beams: 1
num_beams: 1
```

After fix:
```
num_beams: 2
num_beams: 2
num_beams: 2
num_beams: 2
num_beams: 2
num_beams: 2
```

I've tried to modify one of the long-form transcription tests to check that `GenerationMixin.generate()` is being called with the correct arguments, but I haven't figured out how to mock it out correctly.

**Comment by ArthurZucker** [comment]
IT's perfect, thanks!
