### ISSUE TITLE
`transformers > 4.37` breaks bitsandbyte int8 inference of ESM models

### ISSUE THREAD

**Issue by ChenchaoZhao** [huggingface/transformers#29323]
### System Info

- `transformers` version: 4.37.0
- Platform: Linux-5.10.209-175.812.amzn2int.x86_64-x86_64-with-glibc2.26
- Python version: 3.10.13
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.27.2
- Accelerate config:    not found
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@SunMarc  @younesbelkada 
When loading ESM pretrained models using `load_in_8bit` in latest version of transformers, there was a runtime error: `ErrorMessage "KeyError: 'inv_freq'`

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`AutoModelForMaskedLM.from_pretrained("facebook/esm2_t36_3B_UR50D", load_in_8bit=True)`
then it will crash with `KeyError`

### Expected behavior

No error

**Comment by younesbelkada** [comment]
Thanks @ChenchaoZhao for flagging! https://github.com/huggingface/transformers/pull/29329 should fix the issue
