### ISSUE TITLE
Cannot run flash_attention_2 with bark-small

### ISSUE THREAD

**Issue by damithsenanayake** [huggingface/transformers#29332]
### System Info

I'm trying to run bark / bark-small with flash-attention 2. It simply gives me the following error. I'm using the dev version. 
TypeError: BarkModel._check_and_enable_flash_attn_2() got an unexpected keyword argument 'check_device_map'. Was this supported in an earlier version? 

### Who can help?

@sanchit-gandhi 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Simply follow the steps mentioned in https://huggingface.co/docs/transformers/en/model_doc/bark#using-flash-attention-2. 

### Expected behavior

Bark Model should be set up without an issue.

**Comment by ArthurZucker** [comment]
could you additionally share the output of `transformers-cli env` ? cc @ylacombe as well
