### ISSUE TITLE
Clarify copyright owner

### ISSUE THREAD

**Issue by faph** [huggingface/transformers#29347]
### System Info

N/A

### Who can help?

@stevhliu | @MKhalusova 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I understand `transformers` is licensed under the Apache 2.0 license.

However, it is not entirely clear whether authors retain copyrights for their contributions. As far as I can see there is no CLA defined in Github. Yet, the copyright statements in each file suggest the copyrights are owned by "The Hugging Face team". It's not clear what that "team" refers to.

Could we clarify any copyright assignment, please?

### Expected behavior

Unambiguous copyright statements :smile:

**Comment by faph** [comment]
As a secondary issue, the copyright statement at the top of each file has the words "All rights reserved." I think that statement conflicts with the Apache license statement directly underneath that. Some copyrights that are granted by law to authors are actually explicitly surrendered under that license.

**Comment by faph** [comment]
As a tertiary issue, the citation file at https://github.com/huggingface/transformers/blob/main/CITATION.cff lists another set of authors. I am not sure about exactly what the citation file references, but I do note that Github labels this in the sidebar as "Cite this repository". The file itself also contains the message "If you use this software, please cite it using these metadata."

It probably does not hurt reviewing whether/how all software authors can be referenced here.

**Comment by faph** [comment]
@stevhliu | @MKhalusova Any feedback on this please?

**Comment by stevhliu** [comment]
cc @amyeroberts who can help answer this better than I can :)

**Comment by amyeroberts** [comment]
Hi @faph, thanks for raising this issue! 

I actually don't know all the details about the repo's copyright and its headers. I'm going to ping @LysandreJik here who knows more about it here. 

A few things to note, based on what's raised here (@LysandreJik can correct me if I'm wrong):

- Yes, `transformers` is licensed under Apache 2.0, there are special cases (certain files) where a different license applies. For example, some models were released under a different license, and this is reflected in the modeling file e.g. [for BLIP text](https://github.com/huggingface/transformers/blob/b382a09e28c7e59129246ccdf4b00f2cac4547a4/src/transformers/models/blip/modeling_blip_text.py#L4). 
- I'm pretty sure The Hugging Face team refers to people currently working for Hugging Face.  
- We don't add individuals who wrote the code to the copyright headers - their contribution is recorded through the git history. 
- I'm not sure about how much the "all rights reserved" affects the license below legally - my understanding from the header is essentially "all rights reserved apart from the explicitly stated ones in the license below". Perhaps we can clarify this. 
- The listed people in `CITATION.cff` are existing and former employees of Hugging Face who have contributed significantly to building and maintaining the repo. I don't think it makes sense to add all people who added a commit here - as this doesn't reflect the same contribution as maintaining and deciding on the design of the library.

**Comment by faph** [comment]
Hi @amyeroberts that's helpful, thanks.

So to be super clear: is there a copyright assignment to Hugging Face or is there not?

**Comment by amyeroberts** [comment]
Yes, my understanding is that:
* there's copyright assigned to Hugging Face for all the files in our repos
* Each repo will have its own license, which will dictate how the code can be shared, used and edited
* The copyright for some specific files e.g. modeling files may be shared with other individuals or companies

**Comment by faph** [comment]
@amyeroberts Thanks. In that case, please clarify the legal mechanism whereby individual contributors surrender copyrights to Hugging Face. There is no Contributors License Agreement to be signed as far as I can see?

**Comment by amyeroberts** [comment]
Hi @faph, I spoke with the legal team, and have some updates / clarifications:

* Correct, we don't have a CLA
* Based on the documents available, there is no assignment in transformers and all contributions are subject to the same Apache license:
> 2. Grant of Copyright License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form.
> 5. Submission of Contributions. Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions. Notwithstanding the above, nothing herein shall supersede or modify the terms of any separate license agreement you may have execute with Licensor regarding such Contributions.

* The people cited in `CITATION.cff` are the authors of the [transformers paper](https://arxiv.org/abs/1910.03771)
* The All rights reserved statement doesn't make sense, but it shouldn't really affect the license below
* "Hugging Face team" refers to the company, Hugging Face

**Comment by faph** [comment]
@amyeroberts That's great, many thanks for clarifying.

If and when there is an opportunity to fix the copyright statement in each file, it wouldn't hurt phrasing the owners as "Hugging Face and contributors" or similar?
