### ISSUE TITLE
Saving checkpoint fails when hugging face 503

### ISSUE THREAD

**Issue by turtle0x1** [huggingface/transformers#29355]
### System Info

Going to assume it doesn't matter what system your on

### Who can help?

@muellerz @pacman100 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

train a model with a more than average 50 line python file, then when hugging face http server 503's the training gets lost as it cant pull a `/company_xyz/model_xyz/resolve/main/config.json` file

### Expected behavior

Training time doesn't get blown away and the only thing left isn't a folder with a README.

The expected behaviour is this is all prefetched at the start (I cant see this changing that frequently or the desired behaviour to be changing a config.json between each checkpoint) ~or its made more obvious how to train offline first (for "some reason" I think not).~ (this is in getting started).  Still think the request is needless.

**Comment by turtle0x1** [comment]
If anyone else wanders across this, you can fix this (it seems, with a missing vocab warning)  if you already have the tokenizer & model cached in the default location.

First make a directory, `model-name-xyz`

Then modify your train script to 

```py
tokenizer.save("./model-name-xyz") # might wanna save in a different place to model
model.save_pretrained("./model-name-xyz")
```
then run the train script to save model + tokenizer.

Then once they are saved, open the train file and remove the above save comments.

Change the `from_pretrained("xyz/xyz")` to the `from_pretrained("./modal-name-xyz")` for both the model and the tokenizer.
On the tokenizer I also set `local_files_only=True`. For the model you'll need to add;

```py
config = AutoConfig.from_pretrained("./model-name-xyz/config.json")
# Might be a better way, XYZ could be any of the HF classes/modules/whatever
model = XYZ.from_pretrained("./model-name-xyz", config=config)
```

Also changed my train command to something like `HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python3 train.py`

Its late, some of these steps might not be required, or there might be a better way - but it going my training back going again, and I need sleep.

Still don't think the default behaviour should require an non-soft failing http request on saving a training step/epoch, which I is why I dont close this. Does pulling the `config.json` need to happen on every save?

**Comment by zorrofox** [comment]
Same issue, huggingface 503😭
