### ISSUE TITLE
`AutoModel.from_pretrained(local_files_only=True)` changes the hash inside the `refs/main`

### ISSUE THREAD

**Issue by kouroshHakha** [huggingface/transformers#29401]
### System Info

transformers 4.38.1

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Download the model locally but put it under a hash that is not the same as the one from the latest in the hub
2. Run this. Interestingly if you instantiate the tokenizer first and the model it works fine. The culprit is that the `is_peft_available()` branch of the logic will look for `adapter_config.json` file and it won't find it, so it will ask hub and in that process it overrides the `refs/main` file. 

```
from transformers import AutoModel, AutoTokenizer
model = AutoModel.from_pretrained(
    model_id, 
    local_files_only=True,
)

tokenizer = AutoTokenizer.from_pretrained(
    model_id, 
    local_files_only=True,
)

```

### Expected behavior

The code above to work, more importantly `AutoModel.from_pretrained()` to not change the content of `refs/main` file.

**Comment by ArthurZucker** [comment]
cc @younesbelkada and @Rocketknight1

**Comment by Rocketknight1** [comment]
I totally lost track of this one - will take it now!

**Comment by Rocketknight1** [comment]
Hi @kouroshHakha, just to speed things up a bit, can you give me a specific model ID and commit hash to use in the reproduction script that triggers this bug?

**Comment by kouroshHakha** [comment]
I don't recall exactly. But if you take `mistralai/Mistral-7B-Instruct-v0.1` for example and then add the files under a different snapshot commit (both in the folders and in the main file) then you can repro the issue.

**Comment by LysandreJik** [comment]
Maybe also of interest to @Wauplin

**Comment by Rocketknight1** [comment]
I'm still planning to investigate this when I get a chance too!

**Comment by Wauplin** [comment]
> then add the files under a different snapshot commit 

Just for context, files in the cache dir (e.g. in `.../snapshots/` should not be modified manually. It is supposed to be a read-only folder otherwise the cache system is corrupted.
