### ISSUE TITLE
pipeline("sentiment-analysis")() can't handle more than 2 sentences

### ISSUE THREAD

**Issue by xxbidiao** [huggingface/transformers#2941]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): pipeline("sentiment-analysis")

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```
>>> from transformers import pipeline
>>> analyzer = pipeline('sentiment-analysis')
Downloading: 100%|██████████████████████████████| 230/230 [00:00<00:00, 146kB/s]
>>> analyzer(["OK"]*10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/site-packages/transformers/pipelines.py", line 490, in __call__
    scores = np.exp(outputs) / np.exp(outputs).sum(-1)
ValueError: operands could not be broadcast together with shapes (10,2) (10,) 
>>> 
```

`

## Expected behavior

Getting 10 results

## Environment info

     
- `transformers` version: 2.5.0
- Platform: ubuntu 19.04
- Python version: 3.6
- PyTorch version (GPU?): 1.4.0 GPU
- Tensorflow version (GPU?): 1.14.0 GPU
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by xxbidiao** [comment]
`scores = np.exp(outputs) / np.exp(outputs).sum(-1).**reshape(-1,1)**` works for me, but I'm not sure whether it breaks other things.

**Comment by xxbidiao** [comment]
This still happens on the latest version. I still have to apply
`scores = np.exp(outputs) / np.exp(outputs).sum(-1).reshape(-1,1)`
For the code to work.

**Comment by julien-c** [comment]
Yes, this is in the process of being solved by @mfuntowicz
