### ISSUE TITLE
HELP: ZoeDetector.from_pretrained() got an unexpected keyword argument 'cache_dir'

### ISSUE THREAD

**Issue by rdtdy** [huggingface/transformers#29422]
### System Info

Intel(R) Core(TM) i7-14700KF   3.40 GHz
Windows 11 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Error occurred when executing AIO_Preprocessor:

ZoeDetector.from_pretrained() got an unexpected keyword argument 'cache_dir'

File "D:\Comfyui\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Comfyui\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Comfyui\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Comfyui\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\__init__.py", line 109, in execute
return getattr(aux_class(), aux_class.FUNCTION)(**params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Comfyui\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\node_wrappers\zoe.py", line 17, in execute
model = ZoeDetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Expected behavior

Solve this problem

**Comment by ArthurZucker** [comment]
Sorry this issue should be opened on the ` ComfyUI` repo!
