### ISSUE TITLE
WandbCallback overwrite all log at summary step

### ISSUE THREAD

**Issue by nmd2k** [huggingface/transformers#29430]
### System Info

wandb = 0.16.3
transformers = 4.37.1

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

When running fine-tuning (on multiple-gpus) using HF Trainer, I notice Wandb logger eventually overwrite all experiment's log at the final summary step, but it work normally while running.

=> While running:
![image](https://github.com/huggingface/transformers/assets/48562727/2893e3b0-482f-4f5d-b3de-8f34c5118f24)

=> At the end:
![image](https://github.com/huggingface/transformers/assets/48562727/975a07aa-d5fe-4e75-bdd3-51d0826fc521)

### Expected behavior

This might due to this line, define all other log to be summary (and overwrite) the log variables at the summary step: 

https://github.com/huggingface/transformers/blob/c38a12270a11e237cf65d085fbbaf0c4b7976b67/src/transformers/integrations/integration_utils.py#L751

**Comment by parambharat** [comment]
@nmd2k : Thanks for raising the issue. Can you check the next page in your train panel to see if you have the `train/loss` graph. Your metrics should still be present and not overwritten. Although, from the looks of it there are additional summaries `train/train_loss` etc that are being logged without the correct prefix handling. This needs further investigation. I'll investigate and update here soon.

**Comment by parambharat** [comment]
@nmd2k : Please take a look at the PR and let us know if this fixes the issue you are facing.
