### ISSUE TITLE
Exllama v2 Quantization support

### ISSUE THREAD

**Issue by chris1ance** [huggingface/transformers#29448]
### Feature request

Support for exl2 quantized models based on https://github.com/turboderp/exllamav2.

### Motivation

The recent absence of GPTQ and AWQ quants by [TheBloke](https://huggingface.co/TheBloke), as well as more recent activity by [LoneStriker](https://huggingface.co/LoneStriker) and [Bartowski](https://huggingface.co/bartowski) in uploading exl2 (and GGUF) quants for new LLMs.

### Your contribution

This would be far outside my circle of competence.

**Comment by ArthurZucker** [comment]
It is already supported see #28634
