### ISSUE TITLE
KeyError: 'cache_params'. Unsafe key access in generate method _update_model_kwargs_for_generation

### ISSUE THREAD

**Issue by nbarlowportfolio** [huggingface/transformers#29501]
### System Info

Solution: Changing the code to ignore fixed it. I am unsure as to if there is a more proper fix further back in the pipeline.

def _update_model_kwargs_for_generation(
        self, outputs: ModelOutput, model_kwargs: Dict[str, Any], **kwargs
    ) -> Dict[str, Any]:

        if "cache_params" in outputs:
            model_kwargs["cache_params"] = outputs["cache_params"]
        return model_kwargs

Here is the full code I ran to get the error and test the fix: https://github.com/nbarlowportfolio/Mamba-Hello-World/blob/master/mamba_official_with_fixes.ipynb

Thank you.

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the full notebook here: https://github.com/nbarlowportfolio/Mamba-Hello-World/blob/master/mamba_official_with_fixes.ipynb

### Expected behavior

Expected: Generating without error.

**Comment by ArthurZucker** [comment]
Thanks, I am adding the fix in #29472
