### ISSUE TITLE
transformers version problem

### ISSUE THREAD

**Issue by Oten-arch** [huggingface/transformers#29577]
### System Info

Linux, transformer==4.38.2, python=3.10

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. When starting the DBGPT project (Baichuan Model，The official default installation for the DBGPT project is the latest version of transformer) and installing transformer>4.34.0, an error will be reported as AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model‘

2. However, if Transformer>4.34.0 is not installed, an error message will appear: ImportError: cannot import name 'is nltk available' from 'Transformers. utils. import utilslib/Python 3.10/site packages/Transformers/utils/import_utils. py)

3. It seems that both attributes are present when there is no transformer version. How can we solve this problem

### Expected behavior

I want to start the DBGPT project correctly without reporting the above two errors, and find a suitable transformer version

**Comment by Oten-arch** [comment]
pip install transformers==4.36.0 still reports AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model'

**Comment by amyeroberts** [comment]
Hi @Oten-arch, thanks for raising an issue! 

I'm not aware of the DBGPT project, could you link to it, as well as providing a minimal code snippet which reproduces the issue?

**Comment by Oten-arch** [comment]
> Hi @Oten-arch, thanks for raising an issue!
> 
> I'm not aware of the DBGPT project, could you link to it, as well as providing a minimal code snippet which reproduces the issue?

DBGPT Github project address: https://github.com/eosphoros-ai/DB-GPT
DBGPT deployment installation document address: https://www.yuque.com/eosphoros/dbgpt-docs/urh3fcx8tu0s9xmb (I deployed step by step according to the source code)

**Comment by Oten-arch** [comment]
> pip install transformers==4.36.0 still reports AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model'

me to,have you solved it
