### ISSUE TITLE
Non-test related errors encountered while following PR testing documentation.

### ISSUE THREAD

**Issue by tomigee** [huggingface/transformers#29613]
### System Info

Hi hugging face team, yesterday I opened a PR but ran into some errors when trying to perform the PR checks as listed in your [contribution guide](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md) and/or [website](https://huggingface.co/docs/transformers/pr_checks). Specifically ran into two issues:

1. When running `make repo-consistency`, I ran into [this error](https://gist.github.com/tomigee/797580872acc9959722af3d66f378ecb).
2. In a bid to ensure I was running all tests that my PR affected, I ran `python -m pytest -n 8 --dist=loadfile -rA -s $(cat test_list.txt)` as instructed by [your website](https://huggingface.co/docs/transformers/pr_checks). Doing so returned [this error](https://gist.github.com/tomigee/c7d75bc2d4d881abe776ede01292707c). I checked the pytest documentation (i.e ran `pytest -h` in terminal) and was unable to find `-n` as an option which leads me to believe this command is outdated, but let me know your thoughts

In any case, not sure if there's a problem with the setup of my env or the documentation/scripts on your end should be updated. In any case, figured I'd rather report it than not.

### Who can help?

@stevhliu @MKhal

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

**Item 1**
1. Create a new environment per the instructions in CONTRIBUTING.md
2. Install pytest latest version (`pip install pytest`)
3. Run `make repo-consistency`

**Item 2**
1. Run `python utils/tests_fetcher.py` per instruction on the website
2. Run `python -m pytest -n 8 --dist=loadfile -rA -s $(cat test_list.txt)`, again per the website.

### Expected behavior

Both commands run without non-test related errors.

**Comment by tomigee** [comment]
@Rocketknight1

**Comment by DrAnaximandre** [comment]
I ran into a similar error than item 1 while trying to fix a typo.

I then ran `fix-copies` as [advised](https://huggingface.co/docs/transformers/pr_checks) and got the following error 

```Traceback (most recent call last):
  File "/home/paul/Documents/code/transformers/utils/check_task_guides.py", line 86, in <module>
    "asr.md": transformers_module.models.auto.modeling_auto.MODEL_FOR_CTC_MAPPING_NAMES,
  File "/home/paul/Documents/code/transformers/src/transformers/utils/import_utils.py", line 1502, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers.models.auto has no attribute modeling_auto. Did you mean: 'processing_auto'?
make: *** [Makefile:88 : fix-copies] Erreur 1`

**Comment by amyeroberts** [comment]
Hi @tomigee, thanks for raising this issue! 

1. Without seeing the PR and code, or knowing the running environment, it's hard to figure out exactly what's happening here. I'm able to run `make repo-consistency` without issue. The error you shared was failing on the `utils/update_metadata.py` check - do your branch add a pipeline or modify which model would belong to which pipeline? 

2. `-n` is a flag from the `pytest-xdist` package. You can make sure you have all the necessary [packages for testing](https://github.com/huggingface/transformers/blob/d9850abd407821fb9f4ad5aabb206adad3610f75/setup.py#L301) by running `pip install -e .[testing]`
