### ISSUE TITLE
Why is the default `use_reentrant=True` when no kwargs were set?

### ISSUE THREAD

**Issue by simon-lund** [huggingface/transformers#29638]
https://github.com/huggingface/transformers/blob/350c5d15668aa2f0467699baa795ef751b1167d3/src/transformers/modeling_utils.py#L2110-L2111

Here `use_reentrant=True`  is set when no kwargs are provided. From the docs of [pytorch](https://github.com/pytorch/pytorch/blob/92a2b214f8e9217c5d94c7583817b22f822fa925/torch/utils/checkpoint.py#L343) this seems to be the legacy variant. 

Does this have any performance or other advantages that I am not aware of?

**Comment by amyeroberts** [comment]
Hi @simon-lund, thanks for opening an issue! 

You can check the git blame to find the PRs which add certain lines - which should normally give you the reasons for the code logic. 

In this case, this line was added in #28538 - according to the PR it's for preparation of an upcoming torch release, where it's necessary for us to explicitly pass the `use_reentrant` kwarg. 

The value is set to true based on the current default PT behaviour c.f. [this comment](https://github.com/huggingface/transformers/pull/28538#issuecomment-1902624777)

**Comment by simon-lund** [comment]
Ah. I'm sorry, I only searched the issues and found several discussion about this, but I didn't search through the PRs
Thank you very much for the link as well as the hint with the PRs (I was not aware of that) :+1:
