### ISSUE TITLE
Referencing #29470 Unable to Create Bert Encodings

### ISSUE THREAD

**Issue by melissafeeney** [huggingface/transformers#29645]
### System Info

Could you please reopen #29470 ? I left a new comment but seem unable to reopen the issue :( 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

#29470 

### Expected behavior

#29470

**Comment by amyeroberts** [comment]
@melissafeeney I've reopened the issue.

Next time, can you please comment on the issue directly requesting it to be reopened, rather than opening a new issue? Having many different issues opened for the same thing make it hard to track and isn't sustainable if everyone does it.
