### ISSUE TITLE
Video-LLaVA with transformers library

### ISSUE THREAD

**Issue by Kamakshi8104** [huggingface/transformers#29640]
### Model description

Video-LLaVA is a multimodal model that is trained on both images and videos simultaneously.  I feel that it would be highly beneficial if it is added to the transformers library as it is a pretty good choice when it comes to video-question answering

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available

### Provide useful links for the implementation

https://huggingface.co/LanguageBind/Video-LLaVA-7B

**Comment by zucchini-nlp** [comment]
If the authors will not be willing to contribute, I want to work on this

cc @gante

**Comment by amyeroberts** [comment]
Great @zucchini-nlp! I'd reach out on the model page on the hub, asking the authors if they'd like to add it to the library. If they're happy to just leave as-is it's all yours!
