### ISSUE TITLE
LLM does not underestand the semantic ordering!

### ISSUE THREAD

**Issue by moghadas76** [huggingface/transformers#29656]
### Feature request

past_target, past_observed_values, past_time_feat, future_time_feat, future_target_reshaped = map(torch.tensor, [past_target_np,future_target_reshaped_np, future_time_feat_np, past_time_feat_np, past_target_np])
LLM did not understand the postfix np semantic conventions!

### Motivation

LLM should underestand the semantic ordering

### Your contribution

A better architecture

**Comment by amyeroberts** [comment]
Hi @moghadas76, 

Without any more context, it's pretty hard to know what's happening. For example, what model is being talked about? 

Please make sure to follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and provide a series of steps to reproduce, as well as information about the running environment. 

Inferring from the question, it seems this is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by moghadas76** [comment]
Actually I am planning to PR to new LLM model to fix this. I'll provide more context.

**Comment by moghadas76** [comment]
Who should I talk to for technical details?

**Comment by amyeroberts** [comment]
It's hard to know without knowing what the technical details are. I'd suggest in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
