### ISSUE TITLE
Support mixed-language batches in `WhisperGenerationMixin`

### ISSUE THREAD

**Issue by cifkao** [huggingface/transformers#29685]
### Feature request

It is currently not possible to mix multiple languages in a single batch when running [Whisper](https://huggingface.co/docs/transformers/en/model_doc/whisper). The `language` argument only accepts a single string (as opposed to a separate language for each batch item), and if no language is passed and multiple languages are detected, [transcription will fail](https://github.com/huggingface/transformers/blob/5011908e10d9592eeb634f4940e0bc130d3edc69/src/transformers/models/whisper/generation_whisper.py#L1170-L1173).

I propose to enable passing a list of languages (`language: Optional[Union[str, List[str]]]`) in a batched transcription situation, as well as removing the restriction related to language detection.

### Motivation

Not being able to transcribe multiple languages in a single batch is clearly a limitation, especially when relying on auto-detection, but also in scenarios where the language is known.

The [error message](https://github.com/huggingface/transformers/blob/5011908e10d9592eeb634f4940e0bc130d3edc69/src/transformers/models/whisper/generation_whisper.py#L1172) states that `It is currently not supported to transcribe to different languages in a single batch.`, implying that it could be supported at some point.

### Your contribution

I have implemented this and I'm planning to submit a PR.

**Comment by amyeroberts** [comment]
cc @ylacombe @sanchit-gandhi
