### ISSUE TITLE
Add Quiet-STaR support

### ISSUE THREAD

**Issue by fakerybakery** [huggingface/transformers#29719]
### Feature request

Hi,
Please add [Quiet-STaR](https://github.com/ezelikman/quiet-star) support. The Transformers code has already been written.

### Motivation

Quiet-STaR allows LLMs to reason before thinking. [Paper](https://arxiv.org/abs/2403.09629).

**Comment by amyeroberts** [comment]
Hi @fakerybakery, thanks for opening this model request! 

If there's already transformers compatible code written, then the fastest and recommended way to make the model available is by putting the code on the hub and we have as much support as we can for enabling this. Here is a [tutorial](https://huggingface.co/docs/transformers/custom_models)

**Comment by fakerybakery** [comment]
Ah, I see, so use remote code? I’ll see if I can open a PR on the model. Thanks!
