### ISSUE TITLE
backward compatibility of GPT2Model class

### ISSUE THREAD

**Issue by JohnHerry** [huggingface/transformers#29725]
### System Info

Platform: Linux CentOS7 (in docker)
Python: 3.9.7
transformers: 4.38.2

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I am using the GPT2Model class inside the transformers.

1、Install transformers==4.24.0
2、train a GPT2Model object, eg.  abc.pt
3、In other environment, install the transformers==4.38.2,
`
state_dict=torch.load("abc.pt")
model = GPT2Model(....)
mymodel = model.load_state_dict(state_dict["model"])
` 
4、step3 will raise Exception in 4.38.2 transformers,  while no such problem in 4.24.0 transformers

RuntimeError: Error(s) in loading state_dict for GPT2Model:
       Unexpected key(s) in state_dict: "model.h.0.attn.bias", "lm.model.h.0.attn.masked_bias", "model.h.1.attn.bias", "model.h.1.attn.masked_bias", ..... "model.h.11.attn.bias", "model.h.11.attn.masked_bias"

also, when I train the model in transformers==4.38.2 and load in 4.24.0,  it will report lossing such keys.

### Expected behavior

GPT2Model should better to be version compatible with transformers version update.

**Comment by ArthurZucker** [comment]
Hey! Why are you not using the `from_pretrained` API, which is the recommended way to load a model and it's weights?

**Comment by JohnHerry** [comment]
We are loading a checkpoint of certain steps. not the final result.

**Comment by ArthurZucker** [comment]
I can help you if the way you are loading the checkpoint is conventional but would recommend you to simply load with from_pretrained, and save it again

**Comment by JohnHerry** [comment]
> I can help you if the way you are loading the checkpoint is conventional but would recommend you to simply load with from_pretrained, and save it again

Thank you for the help.  Can I make decision that the warning parameters  "model.h.0.attn.bias", "lm.model.h.0.attn.masked_bias", "model.h.1.attn.bias", "model.h.1.attn.masked_bias", ..... "model.h.11.attn.bias", "model.h.11.attn.masked_bias" are irrelevant and that they can be removed from the parameter dict when I load checkpoint with torch.load?

**Comment by ArthurZucker** [comment]
Yes! The `bias` are `register_buffer` in later transformers release.

**Comment by JohnHerry** [comment]
Thank you very much.
