### ISSUE TITLE
BUG: Unexpected behaviour by the server.

### ISSUE THREAD

**Issue by sanjay-nit** [huggingface/transformers#29748]
### System Info

Hi, I'm running in issue while installing custom packages in HuggingFace Inference Endpoints(Custom handler)

I deployed on T4 machines and it was working well but when I restarted few times it throws error.
Yes, I can see the warning but is there any better way of installing custom dependencies on machine. eg: tesseract-engine etc.

Below code was working fine since last few weeks but now the same code is throwing error.
`subprocess.run("apt install -y pciutils", shell=True, check=True)`

Error: 
![image](https://github.com/huggingface/transformers/assets/103114249/2155a9d0-38b5-4965-bf32-4629b3c1e6bc)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`subprocess.run("apt install -y pciutils", shell=True, check=True)`

### Expected behavior

It is should install the custom packages.

**Comment by amyeroberts** [comment]
Hi @sanjay-nit, thanks for opening an issue! 

The reproduction line if for installing the `pciutils` library, and not related to transformers.
