### ISSUE TITLE
Deberta-v2 position_biased_input error in documentation

### ISSUE THREAD

**Issue by NilsLusch** [huggingface/transformers#29758]
### System Info

The documentation states that the default value for position_biased_input in deberta-v2 is False but in the source above shows that the default value is True. As far as I can tell in the code, it defaults to False. But cleaning it up in the documentation would be good

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The issue is with the documentation not with the code

### Expected behavior

The source should show that the value defaults to False
![issue](https://github.com/huggingface/transformers/assets/96436846/38d9ec1e-0b03-454b-83e3-cbd5baaba231)

**Comment by amyeroberts** [comment]
Hi @NilsLusch, thanks for raising this! 

Would you like to open a PR to add this? This way you get the github contribution for the solution.

**Comment by vinayakkgarg** [comment]
Hi @amyeroberts!

Can I pick and solve this issue?
