### ISSUE TITLE
Converting CLIPModel to VisionTextDualEncoderModel

### ISSUE THREAD

**Issue by fabiozappo** [huggingface/transformers#29760]
Hi HF team and thanks for your amazing work, for my research I would like to use the CLIPModel "openai/clip-vit-base-patch32" through the VisionTextDualEncoderModel class. I've tried to use the `from_pretrained()` method but it doesn't support the `clip_text_model` class  of the text tower.

Do you have any suggestion from where to start to create such a script?

**Comment by amyeroberts** [comment]
Hi @fabiozappo, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by fabiozappo** [comment]
Ups, thanks!

I've created a question [here](https://discuss.huggingface.co/t/converting-clipmodel-to-visiontextdualencodermodel/78420)

Closing :)
