### ISSUE TITLE
Support batch_size > 1 in assisted decoding

### ISSUE THREAD

**Issue by jiqing-feng** [huggingface/transformers#29769]
### Feature request

Support batch_size > 1 in assisted decoding

### Motivation

With this support, we can provide more capability for assisted decoding, including beam search.

### Your contribution

I would like to submit a PR to enable this; I mainly need to cut and pad the past_key_values because each sequence may have a different length in each generation round.

Would like to hear your opinion @gante

**Comment by gante** [comment]
@jiqing-feng yes! That is a great feature :) Bear in mind that you need to add padding between each iteration, and adapt the attention mask/position ids accordingly. Looking forward to the PR

cc @zucchini-nlp

**Comment by jiqing-feng** [comment]
I reconsidered it and found it is complicated and inefficient (the latency depends on the lowest sequence in the batch, and there is also many of padding and other ops, which will bring extra latency and memory). Maybe continuous batching is the correct way.

**Comment by WindChimeRan** [comment]
Batch Speculative Decoding Done Right: https://arxiv.org/pdf/2510.22876
code: https://github.com/eBay/spec_dec

Implemented Unpad-Append-Repad Batch Speculative Decoding for input id, position id and contiguous kv cache
