### ISSUE TITLE
unreadable codes in for utils_glue

### ISSUE THREAD

**Issue by juliahane** [huggingface/transformers#2978]
Hi
Previously the function "convert_examples_to_features" was implemented very nicely, and now this is implemented with so many nested function calls, which are all very hard to read and IMO unreadable codes. Could you return this implementation back to previous readable version?
thanks

**Comment by LysandreJik** [comment]
Hi, thank you for your comment. Github allows you to look at older versions of the [code](https://github.com/huggingface/transformers/blob/v1.0.0/examples/utils_glue.py).
