### ISSUE TITLE
[Gemma] The weights of `embed_tokens` and `lm_head` in GemmaForCausalLM are not seem to be tied

### ISSUE THREAD

**Issue by oouya** [huggingface/transformers#29798]
Although Gemma is implemented to share weights between `embed_tokens` and `lm_head`, the Hugging Face Transformers implementation of Gemma does not seem to follow this design. 

### google-deepmind's gemma implementation
https://github.com/google-deepmind/gemma/blob/84ed38b4adbc108473ccecf6f85052eddf24f49b/gemma/transformer.py#L186-L200

### [gemma-7b](https://huggingface.co/google/gemma-7b/tree/main) / model.safetensors.index.json
https://huggingface.co/google/gemma-7b/blob/359f554e6b7dcfe8026a8705a20ff166141a5adf/model.safetensors.index.json#L5

### huggingface transformer's gemma implementation
https://github.com/huggingface/transformers/blob/f4364a6ff16e33186cb40f1d3fafd3792556d1b8/src/transformers/models/gemma/modeling_gemma.py#L1030C1-L1058C26

**Comment by SeunghyunSEO** [comment]
check 1031 line in code block that you highlight.
`_tied_weights_keys = ["lm_head.weight"]` means weight tie.

**Comment by oouya** [comment]
> check 1031 line in code block that you highlight. `_tied_weights_keys = ["lm_head.weight"]` means weight tie.

It was my misunderstanding. I have confirmed that embed_tokens.weight and lm_head.weight have the same values. Thanks.
