### ISSUE TITLE
Typo in the document of automodelforcausallm

### ISSUE THREAD

**Issue by xianjiedai** [huggingface/transformers#29814]
Documentation Link: <[https://huggingface.co/transformers/v3.5.1/model_doc/auto.html#automodelforcausallm>](https://huggingface.co/transformers/v3.5.1/model_doc/auto.html#automodelforcausallm)

Specific Section Title: "AutoModelForCausalLM"

Description of Typos:

Original Text: "This is a generic model class that will be instantiated as one of the model classes of the library—with a causal language modeling head—when created with the when created with the"

Correct Text: "This is a generic model class that will be instantiated as one of the model classes of the library—with a causal language modeling head—when created with the"

**Comment by lorenzoverardo** [comment]
This issue can be closed as it won't be fixed (see https://github.com/huggingface/transformers/pull/29830#issuecomment-2021330414).

**Comment by ArthurZucker** [comment]
Thanks for the update! 🤗
