### ISSUE TITLE
Move weight initialization for DeformableDetr

### ISSUE THREAD

**Issue by EduardoPach** [huggingface/transformers#29818]
### System Info

Not relevant

### Reproduction

See [Deformable Detr Modeling](https://github.com/huggingface/transformers/blob/main/src/transformers/models/deformable_detr/modeling_deformable_detr.py#L653). 

### Expected behavior

All weight initializations should be done in `_init_weights` of the `xxxPretrainedModel` class

**Comment by EduardoPach** [comment]
c.c. @amyeroberts

**Comment by amyeroberts** [comment]
A note for anyone coming to this: this is for all DETR related models

cc @NielsRogge

**Comment by EduardoPach** [comment]
Will work on this this week

**Comment by amyeroberts** [comment]
Any update @EduardoPach?

**Comment by EduardoPach** [comment]
> Any update @EduardoPach?

Busy with other things lately and prioritizing my free time to more impactful contributions. I believe this issue could be tagged with `good-first-issue` though

**Comment by g-prz** [comment]
Hello @amyerobert ! I am interested in working on that issue (as my first issue). 

I dove a little bit into the issue, if I reformulate it: 
- mainly moving the `_reset_parameters()` function into the `_init_weights()`
- there is the same issue to tackle in `GroundingDino` model

**Comment by amyeroberts** [comment]
@g-prz Yep - that's right! When you're ready feel free to open a PR and ping me for review 🤗
