### ISSUE TITLE
warm-starting encoder-decoder models using EncoderDecoderModel always giving an empty string after fine-tuning

### ISSUE THREAD

**Issue by kawsar-pie** [huggingface/transformers#29824]
### System Info

Hi @ArthurZucker  and @patrickvonplaten, I am trying to train a seq2seq model using **EncoderDecoderModel** class and found [this](https://huggingface.co/blog/warm-starting-encoder-decoder) blog very helpful. Thanks to @patrickvonplaten for the nice explanation. Following this blog I fine-tuned a seq2seq model where I used a **BERT** ([BanglaBERT](https://huggingface.co/csebuetnlp/banglabert) an Electra) model as encoder and **[XGLM](https://huggingface.co/facebook/xglm-564M)**  as decoder using [BanglaParaphrase](https://huggingface.co/datasets/csebuetnlp/BanglaParaphrase) data. But after fine-tuning the model always generates an **empty string**. Now I do not understand where the problem is. Please help me to find the bug in the [code](https://www.kaggle.com/code/kawsar17/paraphrase-bert2xglm).

Thanks.

### Who can help?
@ArthurZucker 
@patrickvonplaten 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Here is my [notebook](https://www.kaggle.com/code/kawsar17/paraphrase-bert2xglm)

### Expected behavior

Input-output for my code:
{'target': 'সিপিও আহত থাকায় যুদ্ধ পরিচালনার দায়িত্ব এসে পড়েছিল সেম্প্রোনিয়াসের কাঁধে।',
 'pred_target': ''}
 
 which should be something like this (should give the paraphrased sentence according to the input sentence in Bangla):
 {'target': 'সিপিও আহত থাকায় যুদ্ধ পরিচালনার দায়িত্ব এসে পড়েছিল সেম্প্রোনিয়াসের কাঁধে।',
 'pred_target': 'সিপিও কর্তৃক আহত হয়ে সেমপ্রোনিয়াসের কাঁধে যুদ্ধ পরিচালনার দায়িত্ব আসে।'}

**Comment by amyeroberts** [comment]
Hi @kawsar-pie, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by kawsar-pie** [comment]
Thank you @amyeroberts for your comment. I created a new topic in the forum for this issue. I hope to find a solution from there.
