### ISSUE TITLE
GaLore implementation assigns same optimizer to galore_params and non_galore_params

### ISSUE THREAD

**Issue by geronimi73** [huggingface/transformers#29841]
### System Info

Hey everyone, 

I noticed something in the current implementation of GaLore (layerwise): the same optimizer is hooked onto `galore_params` and `non_galore_params`. 

Is this on purpose? 

https://github.com/huggingface/transformers/blob/76a33a10923ccc1074917f6b6a1e719e626b7dc9/src/transformers/trainer.py#L1296-L1301

The [official implementation](https://github.com/jiaweizzhao/GaLore) hooks `GaLoreAdamW8bit` to galore_params and `bnb.optim.Adam8bit` to all others:

https://github.com/jiaweizzhao/GaLore/blob/864eeb361dc96c1932c3fa429ad0119aaed8e617/torchrun_main.py#L339-L342

### Who can help?

@younesbelkada

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

any script that uses `galore_*_layerwise`

### Expected behavior

not sure

**Comment by younesbelkada** [comment]
Hi @geronimi73 
Thanks for the issue - yes this is expected as Galore optimizers under the hood will fall back to the native optimizer if you don't pass any galore kwargs

**Comment by geronimi73** [comment]
yes, @jiaweizzhao told me the same that's why I closed the issue. would have noticed this myself if I looked at the code more carefully. thank you for your answer

**Comment by younesbelkada** [comment]
Thanks @geronimi73 !
