### ISSUE TITLE
Exporting Mixtral using ONNX Exporter Fails Due to Python List Conversion

### ISSUE THREAD

**Issue by AdamLouly** [huggingface/transformers#29857]
### System Info

nightly pytorch
nightly transformers
stable latest onnx

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When attempting to use the ONNX exporter to export the Mixtral model I faced an exporting error, and digging further, I found out that a tensor to list conversation that is made in the MixtralSparseMoeBlock is what raises this error.

in this line:
https://github.com/huggingface/transformers/blob/fadb053379b3ef24c4ec8e6d7d58555af21f58db/src/transformers/models/mixtral/modeling_mixtral.py#L869

`top_x_list = top_x.tolist()
idx_list = idx.tolist()
`

The top_x and idx are converted to a list which ONNX exporter and potentially other exporters cannot handle.

To solve it we need to remove this list converstion.

------------

Question to @ArthurZucker , why do we need this conversion, how much perf gain does it bring?

### Expected behavior

Failed in export.

**Comment by thiagocrepaldi** [comment]
Adding to @AdamLouly's point, th `tolist()` is an issue for PyTorch 2.X code in general (aka Dynamo). In Dynamo, pytorch tensors/operators are tracked to build a static computational graph. With operations like `numpy.array`, `torch_tensor.numpy()` or, as in this case, `torch_tensor.tolist()`, a pytorch tensor becomes a python scalar, which cannot be properly tracked by Dynamo, causing all sorts of issues

One solution is to convert the model code to use as much PyTorch API as possible. In this case, it means keeping the tensor as a tensor, not a list.

By the way, why do we need a `.tolist()` here? The code seems to work the same way without it. That would help us understand the underlying design decision for this and improve the Pytorch 2.x support

**Comment by ArthurZucker** [comment]
It works for sure, but as the comment points out we found that it was faster to index with list rather than with tensor (that is from profiling). I'll review!

**Comment by thiagocrepaldi** [comment]
@AdamLouly did you close by accident? https://github.com/microsoft/onnxruntime/pull/20210 was not approved and merged yet
