### ISSUE TITLE
vocab_size for modeling_llama.py

### ISSUE THREAD

**Issue by SeunghyunSEO** [huggingface/transformers#29856]
### System Info

transformers==4.39.0

### Who can help?

-

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

-

### Expected behavior

[this line](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L1218) should use `self.vocab_size` not `self.config.vocab_size`

```python
shift_logits = shift_logits.view(-1, self.vocab_size)
```

because one can resize the embedding matrix for faster training (padded_vocab_size).
i think you guys consider this (`self.vocab_size = getattr(config, "padded_vocab_size", config.vocab_size)`) but forgot to use.

**Comment by SeunghyunSEO** [comment]
mistral also has same problem

**Comment by ArthurZucker** [comment]
The api to resize the model usually also update the `config.vocab_size` so not 100% sure this affects anyone appart people who manually resize. But no, `padded_vocab_size` is not part of llama config.

**Comment by SeunghyunSEO** [comment]
thank you for the kind reply @ArthurZucker , i think official llama or mistral ckpt does not have problem like you mentioned but in our project, we override and customize llama like model and got probem. im not sure it is because config should be updated but it didn't... however i think we all agree to change the line to use self.vocab_size for potential issue! i will PR for the mistral and llama soon :)

**Comment by SeunghyunSEO** [comment]
Sorry for the misunderstanding, Arthur.
After checking the code a bit more, it seems that this only exists in the arguments that are generated when converting the Megatron model. I looked up the history of hugginface transformers' and there is code that uses padded_vocab_size, but it seems to be a very rare case. Also, as I mentioned, it seems that users rarely pre-pad the embedding of mistral and llama models outside of the trainer, and in that case, it would be the user's fault for not modifying the config, so I think it does not need to change the code.
Sorry for wasting your time..!

**Comment by ArthurZucker** [comment]
No worries 🤗
