### ISSUE TITLE
`assisted_decoding` called directly inside `generate` triggering warning to use when it shouldn't

### ISSUE THREAD

**Issue by ofirzaf** [huggingface/transformers#29860]
### System Info

- `transformers` version: 4.39.1
- Python version: 3.10.14
- Huggingface_hub version: 0.22.0
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.2.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@gante 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
out = model.generate(
    **inputs,
    max_new_tokens=128,
    streamer=TextStreamer(tokenizer=tokenizer, skip_special_tokens=True),
    pad_token_id=tokenizer.eos_token_id,
    prompt_lookup_num_tokens=3,
)
```
This triggers the following warning:
```
Calling `_assisted_decoding` directly is deprecated and will be removed in v4.41. Use `generate` or a custom generation loop instead.
```
This happens probably due to the following call which should be changed to `self._assisted_decoding(...)`
https://github.com/huggingface/transformers/blob/7eb3ba82241c927053689270a0751f4ff5d33c54/src/transformers/generation/utils.py#L1509

### Expected behavior

Warning shouldn't be triggered

**Comment by zucchini-nlp** [comment]
Thanks for opening an issue. Yes, there is [a PR](https://github.com/huggingface/transformers/pull/29585) fixing this behavior. You can update `transformers` with 
`!pip install --upgrade git+https://github.com/huggingface/transformers.git`

after the PR is merged 🤗
