### ISSUE TITLE
Include other tokenizers/image processors in Llava

### ISSUE THREAD

**Issue by muhark** [huggingface/transformers#29887]
### Feature request

Generalize the functionality in [processing_llava.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llava/processing_llava.py) to include other tokenizers and image processors.

### Motivation

The current implementation of the LlaVA processor only accepts Llama as the tokenizer. Given the extensibility of the framework, this restriction should not be there.

### Your contribution

I am happy to write the code and make the PR. We have done this for our own internal research code and there is an example file in our `llava-gemma-2b` model ([link](https://huggingface.co/Intel/llava-gemma-2b/blob/main/processing_llavagemma.py)).

**Comment by ArthurZucker** [comment]
I am not sure there has been other Llava models that don't use llama tokenizer no?

**Comment by muhark** [comment]
@ArthurZucker thank you for the fast response!

There are a few examples I know of:

- TinyLlaVA uses phi-2 (but requires users to install their package)
- We have just uploaded a Gemma-based LLaVA model

Is there a strong reason for restricting the LlaVA Processor to using llama/clip?

**Comment by ArthurZucker** [comment]
There is none! It's just that we base it on usage! Could you link to the gemma based model? 
Feel free to open a PR


FYI @NielsRogge

**Comment by muhark** [comment]
Link to gemma-based model: [Intel/llava-gemma-2b](https://huggingface.co/Intel/llava-gemma-2b)

I'm happy to open the PR :)

**Comment by ArthurZucker** [comment]
Feel free to do so and link it to this issue!

**Comment by lucasjinreal** [comment]
Hello, am just wondering how to append -200 image tokens to nay tokenizer and reuse LLavaProcessor?

**Comment by ArthurZucker** [comment]
Hey, you can simply use `tokenizer.add_tokens(["toke1", "tok2", .........])`

**Comment by zucchini-nlp** [comment]
LLaVA now supports any type of tokenizer and LLM backbone, so should be completed. Feel free to reopen if it needs anything else
