### ISSUE TITLE
run_ner.py example

### ISSUE THREAD

**Issue by jmamou** [huggingface/transformers#2990]
# ❓ Questions & Help

## Details
It seem that examples/run_ner.py has been removed from github repo. Is there any issue with this code?
Thanks

**Comment by nikhilbchilwant** [comment]
Are you looking for this? https://github.com/huggingface/transformers/blob/master/examples/ner/run_ner.py

**Comment by marc-r-vincent** [comment]
On a (somewhat) related note: the code might still be there but on huugginface's webpage the following link doesn't point to anything: https://huggingface.co/transformers/examples.html#named-entity-recognition (there is no more an example of how to call the script)

**Comment by jmamou** [comment]
the example has been moved to https://github.com/huggingface/transformers/tree/master/examples/ner

**Comment by marc-r-vincent** [comment]
Thx Jonathan

**Comment by TravellerOnCode** [comment]
I found it here: https://github.com/huggingface/transformers/blob/master/examples/token-classification/run_ner.py

The NER has been renamed to Token Classification.
