### ISSUE TITLE
Don't have audio in this URL

### ISSUE THREAD

**Issue by emmanuelwithme** [huggingface/transformers#29917]
### Feature request

For this tutorial https://huggingface.co/docs/transformers/v4.39.1/en/pipeline_tutorial.
Some code can not run.
Because this url doesn't have audio. https://huggingface.co/datasets/sanchit-gandhi/librispeech_long/resolve/main/audio.wav

### Motivation

As above

### Your contribution

As above

**Comment by ArthurZucker** [comment]
cc @stevhliu
