### ISSUE TITLE
max retries exceeded with url when trying to push to the hub

### ISSUE THREAD

**Issue by avacaondata** [huggingface/transformers#29922]
### System Info

the transformers library is irrelevant to this error, it has to do with the hub's s3 connections.

```
'(MaxRetryError("HTTPSConnectionPool(host='hf-hub-lfs-us-east-1.s3-accelerate.amazonaws.com', port=443): Max retries exceeded with url:
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

try to push a model to the hub and see the error: `'(MaxRetryError("HTTPSConnectionPool(host='hf-hub-lfs-us-east-1.s3-accelerate.amazonaws.com', port=443): Max retries exceeded with url:`

### Expected behavior

I'd expect that, though slow maybe (if the network is overloaded), models are pushed to the hub at some point. The cloud bill is getting much higher in the "pushing to the hub" part than in the training part (3k samples).

**Comment by avacaondata** [comment]
It still happens... I'm wasting tens of dollars in the cloud just trying to upload my model, any hints? I've tried using the `huggingface-cli` tool as well, with the same results.

**Comment by ArthurZucker** [comment]
cc @philschmid and @Wauplin you might have already seen this?

**Comment by Wauplin** [comment]
Hi @avacaondata, I'm sorry you're facing those issues. These errors can happen when trying to upload files from behind a proxy. Could it be the case here as well? A good way to fix this is to set proxy config as environment variable (see [here](https://github.com/huggingface/transformers/issues/17611#issuecomment-1537709564)). A more dirty way of fixing it is to deactivate certificates (see [here](https://github.com/huggingface/transformers/issues/17611#issuecomment-1323272726)). Hope this can help you :)
