### ISSUE TITLE
Inconsistency between torch_dtype in model.config and torch_dtype of model parameters

### ISSUE THREAD

**Issue by efsotr** [huggingface/transformers#29955]
### System Info

- `transformers` version: 4.39.2
- Platform: Linux-4.15.0-213-generic-x86_64-with-glibc2.27
- Python version: 3.9.16
- Huggingface_hub version: 0.22.2
- Safetensors version: 0.4.2
- Accelerate version: 0.23.0
- Accelerate config:    - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: False
        - main_training_function: main
        - downcast_bf16: False
        - tpu_use_cluster: False
        - tpu_use_sudo: False
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
import torch
from transformers import LlamaForCausalLM, LlamaConfig, AutoModelForCausalLM

config = LlamaConfig(num_hidden_layers=2, hidden_size=16, num_attention_heads=16, torch_dtype="float16")
model = AutoModelForCausalLM.from_config(config, torch_dtype=torch.bfloat16)
print(model.get_input_embeddings().weight.dtype, model.dtype)
print(model.config.torch_dtype)
```

Running preceding code, then we will get 
```
torch.float32 torch.float32
torch.float16
```

### Expected behavior

```
torch.float16 torch.float16
torch.float16
```

**Comment by ArthurZucker** [comment]
Hey! I asm using main but getting this: 
<img width="742" alt="image" src="https://github.com/huggingface/transformers/assets/48595927/57a04e98-8c02-48e6-a32f-e661c96105fa">

which is already a bit better and expected. The config value was not overwritten. However if you save it, it will be overwritten 😉
