### ISSUE TITLE
No optimizer steps when gradient_accumulation_steps smaller than epoch_iterator length

### ISSUE THREAD

**Issue by mataney** [huggingface/transformers#2995]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Doesn't matter.

Language I am using the model on (English, Chinese ...): Doesn't matter.

The problem arises when using:
* [x] the official example scripts
* [ ] my own modified scripts

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: Any of the tasks.
* [ ] my own task or dataset

## To reproduce

1. Run `run_glue.py` where number of batches for each epoch is smaller than gradient_accumulation_steps.

In https://github.com/huggingface/transformers/blob/8194df8e0cff8e5866ec2bcbda34e3892f10eb39/examples/run_glue.py#L233

`step` is at most `len(train_dataloader)/batch_size`. If the latter is small, then we would never enter the if condition and never call `optimizer.step()` and so on.

I know it's the user responsibility to be aware of this, but this can be easily solved by by altering the condition to be:
```
if (step + 1) % args.gradient_accumulation_steps == 0 or ((step + 1) < args.gradient_accumulation_steps and (step + 1) == len(epoch_iterator)):
```

Should I create a small PR?

**Comment by LysandreJik** [comment]
In this scenario, the user would do a single optimizer step over the whole batch?

Sure, we would welcome a PR! Could you add a comment as well, so that the purpose of this line may be clear for the user?

**Comment by mataney** [comment]
After the change we would do a single optimizer step over each *epoch*.
Added a comment and created a PR. 
https://github.com/huggingface/transformers/pull/3006
Cheers.
