### ISSUE TITLE
Minor difference in rouge scores for BART evaluation on summarization task

### ISSUE THREAD

**Issue by Madhumitha-MCW** [huggingface/transformers#29954]
### System Info

transformers version: 4.39.0
Platform: Linux-5.4.0-167-generic-x86_64-with-glibc2.31
Python version: 3.10.13
Huggingface_hub version: 0.21.4
Safetensors version: 0.4.2
Accelerate version: 0.28.0
Accelerate config: not found
PyTorch version (GPU?): 2.2.1+cu121 (False)
Tensorflow version (GPU?): 2.16.1 (False)
Flax version (CPU?/GPU?/TPU?): not installed (NA)
Jax version: not installed
JaxLib version: not installed
Using GPU in script?: no
Using distributed or parallel set-up in script?: no

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Use the latest tensorflow native version (2.16.1) and latest transformers version (4.39.1)
2.  I am trying to use the evaluator() from evaluate package to evaluate and compute to compute the scores
3.  The dataset on which I am performing the validation is "multinews" and the model is https://huggingface.co/KostiuchenkoArtem/bart_large_multi_modified.
4. I am seeing variations from the 4th decimal in the rouge scores.

### Expected behavior

Same rouge score everytime

**Comment by ArthurZucker** [comment]
Fourth decimal is 1e-4, this seems acceptable for such an old model given different settings / torch versions no?

**Comment by Madhumitha-MCW** [comment]
I don't change any settings between the runs and what I ideally expect is the same scores as the dataset and the model weights don't change. So I had a doubt if this variation is expected for rouge scores or not

**Comment by ArthurZucker** [comment]
Again for a very old model, this should be expected

**Comment by Madhumitha-MCW** [comment]
Ok thank you for your response.
