### ISSUE TITLE
Inconsistency with transformer pipeline results

### ISSUE THREAD

**Issue by abhijeetk597** [huggingface/transformers#29960]
### System Info

- `transformers` version: 4.38.2
- Platform: Linux-5.15.133+-x86_64-with-glibc2.31
- Python version: 3.10.13
- Huggingface_hub version: 0.21.4
- Safetensors version: 0.4.2
- Accelerate version: 0.28.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.2+cpu (False)
- Tensorflow version (GPU?): 2.15.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.8.2 (cpu)
- Jax version: 0.4.25
- JaxLib version: 0.4.25
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

sent_pipeline = pipeline("sentiment-analysis",model=model, tokenizer=tokenizer)

import random
random_text = random.choice(df["Text"])

print(random_text)
sent_pipeline("random_text")
```
![Screenshot 2024-03-30 052904](https://github.com/huggingface/transformers/assets/138308825/58f31510-7f55-4d91-8e0a-2e63e323d5e0)

## I tried same thing with different model but got same kind of result.
![Screenshot 2024-03-30 053110](https://github.com/huggingface/transformers/assets/138308825/a317ead7-5b32-4b67-9277-51318b2ee09c)

### Expected behavior

Sentiment scores should vary as per text given.

**Comment by vasqu** [comment]
You pass the string "random_text" but not the variable's (`random_text`) content. That's why you get the same score.

Try passing it like `sent_pipeline(f'{random_text}')`. So in total something like:
```python
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

sent_pipeline = pipeline("sentiment-analysis",model=model, tokenizer=tokenizer)

import random
random_text = random.choice(df["Text"])

print(random_text)
# here is the change
sent_pipeline(f"{random_text}")
```
