### ISSUE TITLE
Improve/simplify object detection task guide

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#29964]
### Feature request

The object detection task guide has a bunch for issues so it'd be great to solve them.

### Motivation

Several people have reported the following issues regarding the object detection task guide:

- [ ] the model is not predicting any boxes at inference time when you follow the guide for training: https://discuss.huggingface.co/t/example-detr-object-detectors-not-predicting-after-fine-tuning/41824. This may be explained by the slow convergence of DETR. The guide uses 10 epochs, but that may not be enough (cc @MKhalusova who wrote the guide might have some more insights). There's a [model on the hub](devonho/detr-resnet-50_finetuned_cppe5") with relatively good metrics which is trained for 100 epochs, so we might need to update this.
- [ ] unnecessary complicated evaluation: https://discord.com/channels/879548962464493619/897391062975385640/1207009510171091025
- [ ] people need to overwrite the Trainer in order to leverage `compute_metrics`: https://discuss.huggingface.co/t/possible-fix-for-trainer-evaluation-with-object-detection/72307

Moreover, when inspecting the notebook, I saw:

- [x] there's no GPU leveraged during evaluation
- [x] the timm dependency is no longer required as you can now pass `revision="no_timm"`. Moreover, Accelerate is a dependency but is not included in the guide
- [x] the `post_process` method needs to be updated to `post_process_object_detection`, passing a threshold of 0 for computing metrics

### Your contribution

I could work on this but would be great if someone else could take this up

**Comment by rootonchair** [comment]
Hi @NielsRogge , do you still need help on this?

**Comment by NielsRogge** [comment]
@rootonchair yes, the first 3 points still need to be addressed. We would need to simplify the evaluation of the model during training

**Comment by rootonchair** [comment]
Sure, let me work on this

**Comment by NielsRogge** [comment]
Also related: https://github.com/huggingface/transformers/issues/28893

**Comment by g1y5x3** [comment]
![image](https://github.com/huggingface/transformers/assets/17937555/c9e3f9f2-3be5-4894-912d-bc2a164aba3a)
Here is a training run that I did a while back using the [original repo](https://github.com/facebookresearch/detr), 10 epochs is roughly around 200k steps in this figure and I doubt the model would give any meaningful predictions at that point. I haven't ran the training through HF's example yet. Will try it to understand the problem better. The problem is just that this model is awfully slow to train even with A100s...

**Comment by NielsRogge** [comment]
Closing as this is now fixed by https://github.com/huggingface/transformers/pull/30683
