### ISSUE TITLE
Why AttentionMaskConverter to_casual_4d needs input_shape[-1] > 1?

### ISSUE THREAD

**Issue by HackGiter** [huggingface/transformers#29992]
### System Info

transformers 4.37.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

import torch
from transformers.modeling_attn_mask_utils import AttentionMaskConverter

attn_mask_converter = AttentionMaskConverter(is_causal=True, sliding_window=None)

attention_mask = attn_mask_converter.to_causal_4d(
    1, 1, 5, dtype=torch.float16, device='cpu'
)
print(attention_mask.shape)

### Expected behavior

torch.Size([1,1,1,5])

**Comment by ArthurZucker** [comment]
Hey! Best recommendation is to transition to using the `update_causal_mask`: 
https://github.com/huggingface/transformers/blob/416711c3ea88109cf25a9c5f85b4aeee2cb831b5/src/transformers/models/llama/modeling_llama.py#L1058
