### ISSUE TITLE
Tokenization Error with Xglm?

### ISSUE THREAD

**Issue by goru001** [huggingface/transformers#29998]
### System Info

transformers version -> 4.36.2

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Thanks team for the great work with this library!

I was seeing a weird issue wherein following piece of code for XGLM was leading to tokenization with `eos_token` being prepended at the start and no `bos_token`, while I was expecting it to have `bos_token` at the start and `eos_token` at the end. 

```
tokenizer = AutoTokenizer.from_pretrained("facebook/xglm-564M")

xglm_token_out = tokenizer(' I live in chd ')

print(tokenizer.decode(xglm_token_out['input_ids'])) # </s> I live in chd

print(tokenizer.bos_token, tokenizer.eos_token) # <s> </s>
```

As a sanity check above code is working as expected for BERT. 

It'll be great if you can share pointers in case I might be missing something here. Thanks!

### Expected behavior

As explained above, I was expecting the above tokenization to be `<s> I live in chd </s>`.

**Comment by ArthurZucker** [comment]
Hey! Sorry I think the documentation is just wrong, the results you are getting are expected: https://github.com/huggingface/transformers/blob/416711c3ea88109cf25a9c5f85b4aeee2cb831b5/src/transformers/convert_slow_tokenizer.py#L1229.
