### ISSUE TITLE
Add `mps` as supported device for apple silicon to the `Pipeline` class

### ISSUE THREAD

**Issue by fnhirwa** [huggingface/transformers#30007]
### Feature request

As in the latest `torch` version the `mps` accelerator is supported. 
I suggest that it could be added to the supported devices here https://github.com/huggingface/transformers/blob/fce52cefa744a5900fc065aafb2f55d846d1202c/src/transformers/pipelines/base.py#L849
This will enable to train using Apple silicon accelerators.

### Motivation
```python
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2", device=0)
prompt = "In a hole in the ground there lived a hobbit."
output = generator(prompt, max_length=50)

print(output[0]["generated_text"])

Fails for `mps` accelerator using `torch version 2.2.2`
```
### Your contribution

Yeah I would love to open a complete PR if this change is accepted and ensure the check of supported `torch` version is followed.

**Comment by ArthurZucker** [comment]
No idea why it's not already there, would you like to open a PR? something like `if is_mps_available()` with ` torch.backends.mps.is_available() ` wrapped in it.

**Comment by fnhirwa** [comment]
> No idea why it's not already there, would you like to open a PR? something like `if is_mps_available()` with `torch.backends.mps.is_available()` wrapped in it.

Sure will get it added 👍
