### ISSUE TITLE
When use Trainer to train model with "report_to" is wandb

### ISSUE THREAD

**Issue by Luoqiu76** [huggingface/transformers#30033]
### System Info

When using the report_to parameter for training, it is convenient to observe the images of various parameters during the training process, such as gradnorm, loss, etc., where the horizontal axis is steps and the vertical axis is various monitored quantities. However, after training is completed, the Trainer seems to report a unified metric, such as train_runtime, train_loss, etc., resulting in only one point remaining in the original curve after training, such as train_loss. The horizontal axis is the last step, and the vertical axis is train_loss, which seems to be the mean of all steps, causing the original curve to disappear. Is there any way to solve this matter
before it is
![image](https://github.com/huggingface/transformers/assets/80216895/c117f546-650c-437d-b442-89b3bce6e483)
after train and eval，it becomes
![image](https://github.com/huggingface/transformers/assets/80216895/1d65d89a-e470-4b2a-af5b-44db744d3755)
Please ignore the color difference. I found another experimental plot because the original curve has been replaced by a point

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I Use examples/pytorch/language-modeling/run_clm.py to train a mini llama model from the scratch，use report_to wandb

### Expected behavior

I would like to know if the metric after the final training can be reported elsewhere, as it seems that reporting to Wandb will overwrite the previous curve graph

**Comment by ArthurZucker** [comment]
Hey! According to the contribution guidelines, we need to have a reproducer (minimal) and an idea of which version of transformers you are using.
