### ISSUE TITLE
https://github.com/huggingface/transformers/blob/main/examples/research_projects/rag/finetune_rag.py ==> Execution Problem

### ISSUE THREAD

**Issue by ds-256** [huggingface/transformers#30032]
While Executing this file with a custom Index on Pytorch based ddp it just executes and gives no error with CPU and GPU . The Script I am using is  
!python /kaggle/working/rag/rag/finetune_rag.py \
--data_dir /kaggle/input/ragfine/ResearchStuff/seq2seqdataset/ \
--output_dir /kaggle/working/new_for_everything \
--model_name_or_path facebook/rag-sequence-base \
--model_type rag_sequence \
--distributed_retriever pytorch \
--index_name custom \
--passages_path /kaggle/working/Passages/ \
--index_path /kaggle/working/my_knowledge_dataset_hnsw_index.faiss \
--gpus 1 

The Various library versions that I am using are datasets==2.18.0 pytorch-lightning==1.6.0 faiss-cpu==1.8.0

![image](https://github.com/huggingface/transformers/assets/62596204/be18f9c2-d62e-455e-b515-5c54c1eec546)

**Comment by ArthurZucker** [comment]
Hey, if there is no error it's gonna be a bit hard to understand what's wrong here?

**Comment by ds-256** [comment]
Exactly My Point . What I wanted to know has someone used this script in the recent times with the custom dataset so that atleast I could know if there is some issue on my part or is the script really not working

**Comment by ArthurZucker** [comment]
We don't maintain the examples. You might just have the process killed ? If you find the bug let us know, we can't debug in your stead !
