### ISSUE TITLE
What is the data file format of `run_ner.py`?

### ISSUE THREAD

**Issue by sahil3773mehta** [huggingface/transformers#30034]
### Feature request

What is the correct format for custom dataset in run_ner.py? Would it be possible to include a few lines on this with a helpful example? 

### Motivation

I am using the example script run_ner.py from [huggingface](https://github.com/huggingface)/transformers It is not possible to use standard conll format for the model fine-tuning of run_ner.

### Your contribution

We could include this in the corresponding readme.

**Comment by NielsRogge** [comment]
Answered here: https://discuss.huggingface.co/t/what-is-the-data-file-format-of-run-ner-py/41873/3?u=nielsr, but indeed would be nice to open a PR for this to make it more clear

**Comment by JINO-ROHIT** [comment]
#self-assign
