### ISSUE TITLE
Adding tokens to llama2 results in unexpected behaviour 

### ISSUE THREAD

**Issue by wendlerc** [huggingface/transformers#30048]
### System Info

transformers==4.35.2

### Reproduction

I am on transformers version 4.35.2  and get `ValueError: Trying to set a tensor of shape torch.Size([32000, 4096]) in "weight" (which has shape torch.Size([32001, 4096])), this look incorrect.
`

When I try to run:
```python
from transformers import AutoTokenizer, AutoModelForCausalLM
model_name_or_path = "meta-llama/Llama-2-7b-hf"
model = AutoModelForCausalLM.from_pretrained(model_name_or_path, device_map='auto')
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)

tokenizer.add_tokens(["<bla>"])
model.resize_token_embeddings(len(tokenizer))
out = model.generate(tokenizer.encode('The <bla> quick brown fox jumps over the lazy dog', return_tensors='pt'), max_length=50, num_return_sequences=1, pad_token_id=tokenizer.eos_token_id)
```

### Expected behavior

same as on cpu

**Comment by wendlerc** [comment]
meta-llama/Llama-2-7b-hf

**Comment by ArthurZucker** [comment]
Can you update to the latest version of transformers? This was fixed 2 releases ago!

**Comment by ArthurZucker** [comment]
Closing as it is fixed

**Comment by Boltzmachine** [comment]
Same issue
