### ISSUE TITLE
Assisted generation output differs from greedy output

### ISSUE THREAD

**Issue by danielkorat** [huggingface/transformers#30042]
### System Info

Ubuntu 20.04.6 LTS
python=3.10.14

transformers=='4.40.0.dev0', installed from source using commit: 517a3e6
accelerate==0.28.0
torch==2.2.2

### Who can help?

@gante @ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
import torch
from transformers import AutoModelForCausalLM

m = AutoModelForCausalLM.from_pretrained("lmsys/vicuna-7b-v1.3", device_map="auto")
assistant = AutoModelForCausalLM.from_pretrained("double7/vicuna-68m", device_map="auto")
inp = torch.tensor([[10]], device=target.device)
assert m.generate(inp).tolist() == m.generate(inp, assistant_model=assistant).tolist()
```

### Expected behavior

Outputs should be identical (no assertion).

**Comment by ArthurZucker** [comment]
cc @gante, the `generation_config` does not have sampling set, so should be greedy.

**Comment by zucchini-nlp** [comment]
The problem seems to be in the way "cache positions" are updated in "assisted decoding". It works right now after a small change in code but I want to see if there are any edge cases. I can open a PR next week after digging further into the issue 😄
