### ISSUE TITLE
SPDA/FA2 Attention for the Wav2Vec2 Family of Models

### ISSUE THREAD

**Issue by sanchit-gandhi** [huggingface/transformers#30073]
### Feature request

Addition of [PyTorch SDPA](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html) and [Flash Attention 2](https://github.com/Dao-AILab/flash-attention) to the Wav2Vec2 modelling code.

### Motivation

Wav2Vec2 and its derived models remain some of the most popular speech recognition and audio classification models in the library. However, only one [attention implementation](https://github.com/huggingface/transformers/blob/9b5a6450d481b0f02834684ffd8b3ba4cbbd6fe0/src/transformers/models/wav2vec2/modeling_wav2vec2.py#L487) is available to users: the slowest and most memory consuming "eager" mode. We should update the modelling code to provide two newer attention implementations: SDPA and FA2, both of which are faster and more memory efficient.

Since Wav2Vec2 copies its attention from BART, and SDPA & FA2 were added for BART in [this PR](https://github.com/huggingface/transformers/pull/27203), this should be quite a straightforward PR, mostly copying out the logic from the BART PR and pasting it into Wav2Vec2. We should then be sure to add two fast tests (one for each of SDPA and FA2), e.g. in the style of the test [here](https://github.com/huggingface/transformers/blob/9b5a6450d481b0f02834684ffd8b3ba4cbbd6fe0/tests/models/whisper/test_modeling_whisper.py#L891), and two slow integration tests, e.g. in the style of the tests [here](https://github.com/huggingface/transformers/blob/9b5a6450d481b0f02834684ffd8b3ba4cbbd6fe0/tests/models/gemma/test_modeling_gemma.py#L657-L659).

### Your contribution

Want to take this one @kamilakesbi?

**Comment by kamilakesbi** [comment]
Hi @jp1924 ! 

Thanks for the great work! it seems like you have already done most of the work here :) 
We can definitely work together on this and I've added you as a co-author to [this PR](https://github.com/huggingface/transformers/pull/30121). 
Feel free to participate ;)

**Comment by jp1924** [comment]
Oh, thank you for taking me up on my offer!
