### ISSUE TITLE
query parameters not read properly in gradio app on hf spaces 

### ISSUE THREAD

**Issue by mbotsi** [huggingface/transformers#30084]
### System Info

Hello! 

I opened this issue on the Gradio GitHub support page already and there seems no issues to be on the Gradio side which is why I am asking now here hoping to find help. Here the issue for reference https://github.com/gradio-app/gradio/issues/7948

I am using the gradio.Request(···) function to fetch query parameters from an URL in different projects, inspired by some of the projects pasted below. https://www.gradio.app/docs/request

Since yesterday in the evening it does not work to fetch the query parameters from URLs, not in my projects, not in the other projects. I can 100% confirm it worked for the last three weeks until yesterday in the afternoon and then stopped.
For example here https://huggingface.co/spaces/osanseviero/gradio-url-params?test_parameters=987698769786
I would expect the query parameters to include at least test_parameters=987698769786. But instead, the results show only "object: object". This is the same issue for all the spaces I know that are trying to receive query params from the URL.

Example spaces where the query parameters are suddenly wrong (but used to be fetched correctly):
https://huggingface.co/spaces/botsi/original-queryparams-with-http-gradio?param=testtestttest
https://huggingface.co/spaces/botsi/gradio-url-params-sdk4?PARAM=12345
https://huggingface.co/spaces/botsi/gradio-url-params-sdk3?param=12345678
https://huggingface.co/spaces/osanseviero/gradio-url-params?test_parameters=987698769786

<img width="1398" alt="image" src="https://github.com/huggingface/transformers/assets/77936023/084ea3ea-115e-40cb-9fe8-239fbb818708">

When using other methods (not the gradio.Request()) it also does not work to get the correct query parameters, see here: https://huggingface.co/spaces/botsi/original-queryparams-with-js-static?urlparam=1234567890

Is there some problem with huggingface spaces? Was there an update I didn’t know of? 
this functionality is really crucial for me and my master thesis which is why any help on solving this issue is highly appreciated! As mentioned before, the code worked for the past weeks until yesterday. I need the functionality currently for this project (where I also do not get the right parameters currently, but yesterday I still did and I didn’t change anything else in the code): https://huggingface.co/spaces/botsi/trust-game-llama-2-7b-chat/blob/main/app.py
Using gradio sdk_version: 4.20.0.

This is the best example to reproduce the issue https://huggingface.co/spaces/botsi/gradio-url-params-sdk3?param=12345678 using the latest gradio version 4.25.0

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. create a space with the code below  , example here: https://huggingface.co/spaces/botsi/gradio-url-params-sdk3?param=12345678
2. add random url parameter to the url e.g. ?param=1234 
3. click on get parameters 
 
import gradio as gr

def predict(text, request: gr.Request):
query_params = request.query_params
return {
"query_params": query_params
}

gr.Interface(predict, "text", "json").queue().launch()

### Expected behavior

The Field on the right returns at least „param=12345678“

<img width="1131" alt="image" src="https://github.com/huggingface/transformers/assets/77936023/a82c0d27-3599-43cf-9889-32499d7669e4">

**Comment by mbotsi** [comment]
it does read out the parameters locally! 
![image](https://github.com/gradio-app/gradio/assets/77936023/4b2d2f47-14e8-4b32-868a-b19adfd7d1d1)

**Comment by amyeroberts** [comment]
Hi @mbotsi, thanks for raising an issue! 

As this has been confirmed to be a [HF spaces issue](https://github.com/gradio-app/gradio/issues/7948#issuecomment-2041553617), and unrelated to the transformers library, I'm going to close this.
