### ISSUE TITLE
ImportError: cannot import name 'get_model_param_count' from 'transformers.trainer_pt_utils'

### ISSUE THREAD

**Issue by km5ar** [huggingface/transformers#30092]
### System Info

- `transformers` version: 4.23.1
- Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.9.19
- Huggingface_hub version: 0.22.2
- PyTorch version (GPU?): 2.2.2+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

import transformers
print(transformers.__version__)
from transformers.trainer_pt_utils import get_model_param_count

python version: 3.9

### Expected behavior

<img width="768" alt="image" src="https://github.com/huggingface/transformers/assets/54015474/c719a237-0499-4e88-97c0-15fae9c1568a">

**Comment by NielsRogge** [comment]
I guess `get_model_param_count` was not available in Transformers v4.23.1. Hence you can upgrade with `pip install --upgrade transformers`.
