### ISSUE TITLE
Google Colab: ValueError: Connection error, and we cannot find the requested files in the cached path.

### ISSUE THREAD

**Issue by km5ar** [huggingface/transformers#30101]
### System Info

- `transformers` version: 4.36.2
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.2.1+cu121 (False)
- Tensorflow version (GPU?): 2.15.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.8.2 (cpu)
- Jax version: 0.4.23
- JaxLib version: 0.4.23
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

you can use this colab: https://colab.research.google.com/drive/1zn42joYvWmwksPrUlbxRzwxEPJeJuU3n?usp=sharing

!pip install adapters
from adapters import AutoAdapterModel

# 1.
model = AutoAdapterModel.from_pretrained("FacebookAI/roberta-base")
# 2.
adapter_name = model.load_adapter("AdapterHub/roberta-base-pf-imdb")
# 3.
model.active_adapters = adapter_name
# or model.train_adapter(adapter_name)

### Expected behavior

<img width="1383" alt="image" src="https://github.com/huggingface/transformers/assets/54015474/31306c6a-9daa-4f35-946f-547e60e5d3eb">

but somehow it works for other models?
<img width="901" alt="image" src="https://github.com/huggingface/transformers/assets/54015474/85fb7eb9-fe76-4757-994b-a3198b0243a0">

but the samples from huggingface official documents doesn't work
<img width="1844" alt="image" src="https://github.com/huggingface/transformers/assets/54015474/15fc2f69-1bca-4eb2-af6f-b9aee739065b">

**Comment by amyeroberts** [comment]
Hi @km5ar, thanks for raising this issue! 

I'm able to replicate this issue. From the traceback, the error seems to be triggered within the `adapters` library, rather than `transformers`. I'd suggest raising an issue on [that repo](https://github.com/adapter-hub/adapters)
