### ISSUE TITLE
`device_map='auto' support for BertForSequenceClassification for inference using large models

### ISSUE THREAD

**Issue by tnnandi** [huggingface/transformers#30103]
### Feature request

Currently, from_pretrained() for BertForSequenceClassification does not support `device_map='auto'`, and is preventing inference using large models that don't fit into a single GPU. I'd also appreciate it if you could suggest the best alternative right now. 

### Motivation

Inference using large models that don't fit into a single GPU is a big issue. 

### Your contribution

N/A

**Comment by amyeroberts** [comment]
Closing, as this is a duplicate of https://github.com/huggingface/transformers/issues/25296.
