### ISSUE TITLE
What is the default multi-GPU training type?

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/transformers#30122]
### System Info

NA

### Who can help?

@ArthurZucker , @younesbelkada 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When running training using the transformers trainer, and setting device_map to auto, what is the default distributed training type that is used when the model is too large to fit on one GPU?

(assume that I have not yet run `accelerate config`).

Does the model just run with naive model parallel with layers split between different GPUs and with DP (not DDP) on the data side? Are the full gradients and also the optimizer state copied onto each GPU?

It would be helpful if this could be described in the Trainer section of the docs and also in the Multi-GPU docs.

### Expected behavior

NA

**Comment by younesbelkada** [comment]
Hi @RonanKMcGovern 
Thanks for the issue !
If you did not run `accelerate config` it'll fall back to the default behaviour of `accelerator.prepare()`, which I think will return an unmodified model so it'll go for naive PP. Make sure to run the script with `python xxx.py` if that's what you intend for. 
In that case, each GPU will compute its own gradient and have the corresponding optimizer states.
Note the safest is to specify your intended behaviour through `accelerate config` and run your script with `accelerate run xxx.py`
cc @muellerzr @pacman100  in case I am missing something

**Comment by RonanKMcGovern** [comment]
Thanks @younesbelkada . To be clear, when you say naive PP (pipeline parallel), that means that the batch of data will pass through a first set of layers in a first GPU and then the rest of the layers in the next GPU (if there are just two GPUs).

So, this won't be DP (data parallel) then because there is no parallelisation of data.

**Comment by younesbelkada** [comment]
yes this is correct and what i meant by naive PP and you are right in that case it wont be DP

**Comment by RonanKMcGovern** [comment]
Thanks. I'm not sure where in the docs exactly to put it, but possibly where multi-gpu and 'auto' are mentioned, it would make sense to explain that the default is PP.

**Comment by RonanKMcGovern** [comment]
And, btw, in the SFT docs, there's a statement that the default is DP (although I'm unsure now if that's correct and different to just the Trainer in transformers):
```
Multi-GPU Training

Trainer (and thus SFTTrainer) supports multi-GPU training. If you run your script with python script.py it will default to using DP as the strategy, which may be [slower than expected](https://github.com/huggingface/trl/issues/1303).
```

See [here](https://huggingface.co/docs/trl/main/en/sft_trainer#multi-gpu-training).

**Comment by RonanKMcGovern** [comment]
@younesbelkada closing this off
