### ISSUE TITLE
Latest version of transformers available via conda?

### ISSUE THREAD

**Issue by rmartinshort** [huggingface/transformers#3015]
# 🚀 Feature request

I notice that the version of transformers available via conda-forge is quite outdated (v2.1.1). Could you make later versions available there too? Thanks!

**Comment by otavio-silva** [comment]
It would be nice if it had it's own channel like PyTorch has, as put a distribution of the packages (transformers, tokenizers, etc.) there.

**Comment by brik93** [comment]
Any update on this request?
The latest version in conda forge is 2.1.1. 
Thanks.
