### ISSUE TITLE
Use my own pretrained BERT model

### ISSUE THREAD

**Issue by rabbitwayne** [huggingface/transformers#3016]
How can I use my own pretrained BERT model in SQUAD finetuing? How to do this in the code? Can anyone provide any instructions?

**Comment by LysandreJik** [comment]
Hi, where did you obtain this model? Is it using the official google-research implementation or using huggingface/transformers?

**Comment by rabbitwayne** [comment]
@LysandreJik Thank you for your reply! I have pretrained BERT base using my own pytorch code and generated checkpoint for BERT base. Then I want to do squad finetuning using my own pretrained BERT base model but in huggingface/transformers framework. I saw that huggingface/transformers by default download a pretrained BERT base model from amazon aws. How can I change this to use my own checkpoint? Thanks a lot!

**Comment by LysandreJik** [comment]
Are you able to load your model using `model = BertModel.from_pretrained("model_dir")`? The architecture of the model would need to be the same, and have the same layer names so that the torch state dict may be loaded onto one of our architectures.

**Comment by rabbitwayne** [comment]
Thank you! Let me try that.
