### ISSUE TITLE
Load nf4 weights/model in bfloat16

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/transformers#30177]
### Feature request

Allow quantized models to be loaded (upcasted) to bfloat16.

### Motivation

1. The big benefit of QLoRA is being able to fine-tune on less VRAM AND with much less time than full fine-tuning.
2. Adding in rsLoRA, initiating LoRA adapters to minimise quanting error,  and training norm and embedding layers gets performance close to full fine-tuning.

HOWEVER, there's a catch that it's not possible to get back to a bf16 model (yes, it's possible to merge to 4-bit, but this hurts accuracy, and there's no way to upcast either). See [this issue](https://github.com/huggingface/peft/pull/851).

### Your contribution

BEST approach:
- Allow a type of merge where a quantized base model is merged with LoRA weights to form a 16 bit (float16 or bfloat16) model. [Obviously this will take more RAM or VRAM, so may not suit certain users, but it is best for quality].

HACKY but sufficient approach:
- Simply allow a quantized model (i.e. saved like [this](https://github.com/huggingface/transformers/pull/26037)] to be loaded in bfloat 16. If that's possible, then the following flow would work:
1. Fine tune a model with QLoRA (ideally making norms and embeds trainable). [initialise the adapters to minimise quanting error]
2. Save adapters.
3. Unload the adapters and save the nf4 base model (ideally including the trained norms and embeds)
4. Re-load the nf4 base model, but upcasted to bfloat16.
5. Apply the adapter
6. Merge the adapter to the base model
7. This should result in a highly accurate final model.

Everything 1-7 is possible already except for step 4. However, step 4 is done in unsloth, see [here](https://github.com/unslothai/unsloth/issues/195), so should be fairly easy.

[Side note - I'm unsure whether bnb quants the norm and embed layers, or just the linear layers?]

**Comment by amyeroberts** [comment]
@younesbelkada @SunMarc

**Comment by RonanKMcGovern** [comment]
> for the step 4-, why users couldn't simply load again the base model but directly in bf16 ? What would be the benefit of un-quantizing on the fly a 4bit model vs loading it directly in 16bit ? Is it to preserve the quantization error?

Yeah, a base bf16 model will have slightly different weights than a quantized and then dequantized bf16 model. This makes a performance difference when applying and merging the 16 bit adapters on top.

Make sense?

**Comment by younesbelkada** [comment]
Makes sense ! 
@RonanKMcGovern I made: https://github.com/huggingface/transformers/pull/30806 would that PR work for you? tested it locally and it seems to produce coherent text when doing text generation. API-wise it should be quite straightforward (see the PR description)
