### ISSUE TITLE
Why cast to float32 in this line?

### ISSUE THREAD

**Issue by brynhayder** [huggingface/transformers#30186]
https://github.com/huggingface/transformers/blob/edf0935dca9189db599ac6c3f3ef714160acbbd8/src/transformers/models/llama/modeling_llama.py#L87

Is there a numerical reason for doing this? For memory reasons, one might want to keep the the dtype that the user has chosen.

**Comment by brynhayder** [comment]
Maybe this is the reason...? https://github.com/google/flax/issues/612

**Comment by amyeroberts** [comment]
Hi, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

I'll let @ArthurZucker confirm, but yes, I suspect your intuition is correct. The models are ported from their original repo. To ensure our models are as close as possible to the original implementation, we need to reflect design decisions like this and so would do the same as in the flax model (in which case the numerical stability reason applies)

**Comment by ArthurZucker** [comment]
Softmax on float32 works better (more precision) than on bfloat16 or float16. It's now standard 😉

**Comment by brynhayder** [comment]
Thanks.

Out of interest, is this something that has been explore rigorously (i.e. in a paper), or is it more anecdotal/folk lore?

**Comment by ArthurZucker** [comment]
There is [this](https://github.com/huggingface/transformers/pull/17437#issuecomment-1139723683) (from the OPT paper that is related) , [this](https://docs.nvidia.com/deeplearning/performance/mixed-precision-training/index.html#training_tensorflow) for training, and #24519

**Comment by culeao** [comment]
> Softmax on float32 works better (more precision) than on bfloat16 or float16. It's now standard 😉

How to use fp32 when calculating softmax in flash_attention? Matrix multiplication still wants to be done with half precision, do you know any implementations?
