### ISSUE TITLE
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback): name 'LRScheduler' is not defined

### ISSUE THREAD

**Issue by saqib772** [huggingface/transformers#30194]
### System Info

I was Trying to Use the transformers but i'm getting the following erros, Pls Help!!!

`
from transformers import pipeline

# Allocate a pipeline for sentiment-analysis
classifier = pipeline('sentiment-analysis')
classifier('We are very happy to introduce pipeline to the transformers repository.')
`

`
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
File [c:\Users\saqib\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\import_utils.py:1472](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/site-packages/transformers/utils/import_utils.py:1472), in _LazyModule._get_module(self, module_name)
   [1471](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/site-packages/transformers/utils/import_utils.py:1471) try:
-> [1472](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/site-packages/transformers/utils/import_utils.py:1472)     return importlib.import_module("." + module_name, self.__name__)
   [1473](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/site-packages/transformers/utils/import_utils.py:1473) except Exception as e:

File [c:\Users\saqib\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/importlib/__init__.py:126), in import_module(name, package)
    [125](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/importlib/__init__.py:125)         level += 1
--> [126](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/importlib/__init__.py:126) return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1204, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1176, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1147, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:690, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:940, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File [c:\Users\saqib\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\pipelines\__init__.py:47](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/site-packages/transformers/pipelines/__init__.py:47)
     [33](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/site-packages/transformers/pipelines/__init__.py:33) from ..utils import (
...
   [1476](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/site-packages/transformers/utils/import_utils.py:1476)         f" traceback):\n{e}"
   [1477](file:///C:/Users/saqib/AppData/Local/Programs/Python/Python311/Lib/site-packages/transformers/utils/import_utils.py:1477)     ) from e

RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
name 'LRScheduler' is not defined
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?e80bb9d4-235e-49d2-8fc9-3d47b91a0e2f) or open in a [text editor](command:workbench.action.openLargeOutput?e80bb9d4-235e-49d2-8fc9-3d47b91a0e2f). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

`

### Who can help?

@ArthurZucker @youn

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

from transformers import pipeline

# Allocate a pipeline for sentiment-analysis
classifier = pipeline('sentiment-analysis')
classifier('We are very happy to introduce pipeline to the transformers repository.')

### Expected behavior

It needs to provide the results with positive and negative but i'm getting errors just

**Comment by amyeroberts** [comment]
Hi @saqib772, thanks for opening an issue

Could you share the running environment -  run `transformers-cli env` in the terminal and copy-paste the output

**Comment by saqib772** [comment]
@amyeroberts 

OUTPUT:

`
WARNING:tensorflow:From C:\Users\saqib\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\commands\env.py:100: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.39.2
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.11.5
- Huggingface_hub version: 0.22.2
- Safetensors version: 0.4.2
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.2.2+cpu (False)
- Tensorflow version (GPU?): 2.14.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

`

**Comment by amyeroberts** [comment]
Hi @saqib772, thanks for sharing the environment information. 

I'm unable to replicate the error. Could you confirm the transformers and pytorch versions in your running environment. In a python session:

```
import torch
import transformers

print(torch.__version__)
print(transformers.__version__)
```

**Comment by ArthurZucker** [comment]
This was fixed in `transformers=4.39.3` closing!

**Comment by saqib772** [comment]
lmfao nothing is Going well.

**Comment by saqib772** [comment]
![image](https://github.com/huggingface/transformers/assets/121972215/c232530f-c88b-405c-9455-a28c3ad5aa50)
@amyeroberts
