### ISSUE TITLE
Enhance HfArgumentParser with Dict command-line parser

### ISSUE THREAD

**Issue by xu-song** [huggingface/transformers#30204]
### Feature request

Enhance HfArgumentParser with Dict command-line parser

### Motivation

There are many arguments with dict typing, such as `lr_scheduler_kwargs`, `gradient_checkpointing_kwargs`.

https://github.com/huggingface/transformers/blob/6cdbd73e01a9719bfaec07d91fd108e8d932bbbb/src/transformers/training_args.py#L806

https://github.com/huggingface/transformers/blob/6cdbd73e01a9719bfaec07d91fd108e8d932bbbb/src/transformers/training_args.py#L1255

It is possible to pass dict arguments through json_file or yaml_file.
But it does not work in command-line.

### Your contribution

TBD

**Comment by amyeroberts** [comment]
cc @pacman100 @muellerzr
