### ISSUE TITLE
Mamba: which tokenizer has been saved and how to use it?

### ISSUE THREAD

**Issue by javiermcebrian** [huggingface/transformers#30213]
### System Info

Hardware independent.

### Who can help?

@ArthurZucker 

I described the doubts in the link below around 1 month ago, but maybe model-hub discussions are not so active. Then I post it here as repo issue. Please, let me know where to discuss it :)

https://huggingface.co/state-spaces/mamba-2.8b-hf/discussions/1

Thanks!

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

.

### Expected behavior

.

**Comment by amyeroberts** [comment]
Hi @javiermcebrian, you can see which tokenizers are saved for a checkpoint from the files in the model repo e.g. [here for state-spaces/mamba-2.8B-hf](https://huggingface.co/state-spaces/mamba-2.8b-hf/blob/96c48e0292b63f5346b6d30061af2551f7101e26/tokenizer_config.json#L210)

You can use any checkpoints' tokenizer by doing:

```py
from transformers import AutoTokenizer

# You can replace state-spaces/mamba-2.8b-hf with any pretrained checkpoint with a tokenizer
tokenizer = AutoTokenizer.from_pretrained(state-spaces/mamba-2.8b-hf)
```

I suggest looking at the [Hugging Face course](https://huggingface.co/learn/nlp-course/chapter1/1) to find out about how to use all of our NLP models and integrations
