### ISSUE TITLE
[BUG] Load StarCoder2 AWQ using Transformers

### ISSUE THREAD

**Issue by TechxGenus** [huggingface/transformers#30225]
### System Info

Name: transformers
Version: 4.39.3

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Same to https://github.com/casper-hansen/AutoAWQ/issues/441
When loading starcoder2-AWQ using transformers, I received a confusing error:
```py
model = AutoModelForCausalLM.from_pretrained(
    "TechxGenus/starcoder2-3b-AWQ",
    torch_dtype=torch.float16,
    device_map="auto",
)
```
get:
> Some weights of the model checkpoint at TechxGenus/starcoder2-3b-AWQ were not used when initializing Starcoder2ForCausalLM: ['model.layers.0.mlp.act.scales', 'model.layers.1.mlp.act.scales', 'model.layers.10.mlp.act.scales', 'model.layers.11.mlp.act.scales', 'model.layers.12.mlp.act.scales', 'model.layers.13.mlp.act.scales', 'model.layers.14.mlp.act.scales', 'model.layers.15.mlp.act.scales', 'model.layers.16.mlp.act.scales', 'model.layers.17.mlp.act.scales', 'model.layers.18.mlp.act.scales', 'model.layers.19.mlp.act.scales', 'model.layers.2.mlp.act.scales', 'model.layers.20.mlp.act.scales', 'model.layers.21.mlp.act.scales', 'model.layers.22.mlp.act.scales', 'model.layers.23.mlp.act.scales', 'model.layers.24.mlp.act.scales', 'model.layers.25.mlp.act.scales', 'model.layers.26.mlp.act.scales', 'model.layers.27.mlp.act.scales', 'model.layers.28.mlp.act.scales', 'model.layers.29.mlp.act.scales', 'model.layers.3.mlp.act.scales', 'model.layers.4.mlp.act.scales', 'model.layers.5.mlp.act.scales', 'model.layers.6.mlp.act.scales', 'model.layers.7.mlp.act.scales', 'model.layers.8.mlp.act.scales', 'model.layers.9.mlp.act.scales']

And it doesn't output properly. There is no error when using `AutoAWQForCausalLM` or `vllm.LLM` to load it, and they work well.

### Expected behavior

This error is not generated and the output is correct

**Comment by younesbelkada** [comment]
Hi @TechxGenus 
Thanks ! 
I think @SunMarc recently made a PR: https://github.com/huggingface/transformers/pull/30074 that should fix your issue ! 
@amyeroberts I requested your review for whenever you have time 🙏

**Comment by TechxGenus** [comment]
@younesbelkada Thanks!
I test #30074, it pointed out the problem but didn't work. The main reason is that starcoder2 uses `PytorchGELUTanh` instead of `nn.GELU`. It works when replacing this.
Since there are currently many variations of `GELU`, I'm not sure if other models have similar issues.

**Comment by younesbelkada** [comment]
thanks @TechxGenus ! Maybe in @SunMarc 's PR it is possible to extend it to support other modules in addition to `nn.GELU` - wdyt @SunMarc ?

**Comment by erfanium** [comment]
related report:
https://huggingface.co/TechxGenus/starcoder2-7b-AWQ/discussions/1
