### ISSUE TITLE
FSDP Doesn't Work with model.generate() 

### ISSUE THREAD

**Issue by QiyaoWei** [huggingface/transformers#30228]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.39.3
- Platform: Linux-5.15.0-1059-azure-x86_64-with-glibc2.31
- Python version: 3.10.11
- Huggingface_hub version: 0.22.2
- Safetensors version: 0.4.2
- Accelerate version: 0.29.2
- Accelerate config:    - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: bf16
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch': 'BACKWARD_PRE', 'fsdp_cpu_ram_efficient_loading': True, 'fsdp_forward_prefetch': False, 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 'FULL_SHARD', 'fsdp_state_dict_type': 'SHARDED_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_use_orig_params': True}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
- PyTorch version (GPU?): 2.2.2 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: YES

### Who can help?

@ArthurZucker @younesbelkada @gante for the relevance with text models and generate()

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying to use FSDP, but for some reason there is an error when I do model.generate(). MWE below

```
import torch
import os
from omegaconf import DictConfig
from transformers import AutoTokenizer, AutoModelForCausalLM
from torch.distributed.fsdp import (
    FullyShardedDataParallel as FSDP,
    MixedPrecision,
    StateDictType,
    BackwardPrefetch,
    ShardingStrategy,
    CPUOffload,
)
from torch.distributed.fsdp.wrap import transformer_auto_wrap_policy
import functools
import subtrainers

class BasicTrainer(object):
    def __init__(self):

        model_name_or_path = "openai-community/gpt2-large"
        self.tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
        if self.tokenizer.pad_token_id is None:
            self.tokenizer.pad_token_id = self.tokenizer.eos_token_id
        self.policy = AutoModelForCausalLM.from_pretrained(model_name_or_path)
        
        tokenized = self.tokenizer("hi there", return_tensors="pt").to(self.policy.device)
        print(self.policy.generate(**tokenized))
        return
    
    def train(self):
        pass
    
def get_block_class_from_model(model: torch.nn.Module, block_class_name: str) -> torch.nn.Module:
    """Get the class of a block from a model, using the block's class name."""
    for module in model.modules():
        if module.__class__.__name__ == block_class_name:
            return module.__class__
    raise ValueError(f"Could not find block class {block_class_name} in model {model}")

def init_distributed(rank: int, world_size: int, master_addr: str = 'localhost', port: int = 12355, backend: str = 'nccl'):
    print(rank, 'initializing distributed')
    os.environ["MASTER_ADDR"] = master_addr
    os.environ["MASTER_PORT"] = str(port)
    torch.distributed.init_process_group(backend, rank=rank, world_size=world_size)
    torch.cuda.set_device(rank)

def worker_main(rank: int, world_size: int):

    init_distributed(rank, world_size)
    print(f'Creating trainer on process {rank} with world size {world_size}')
    trainer = FSDPTrainer()

    # trainer.train()
    # trainer.save()


def main():

    world_size = torch.cuda.device_count()
    print('starting', world_size, 'processes for FSDP training')
    torch.multiprocessing.spawn(worker_main, nprocs=world_size, args=(world_size,), join=True)
        
class FSDPTrainer(BasicTrainer):
    def __init__(self):

        super().__init__()
        
        model_name_or_path = "openai-community/gpt2-large"
        self.tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)#.to('cuda')
        if self.tokenizer.pad_token_id is None:
            self.tokenizer.pad_token_id = self.tokenizer.eos_token_id
        self.policy = AutoModelForCausalLM.from_pretrained(model_name_or_path).to('cuda')

        wrap_class = get_block_class_from_model(self.policy, "GPT2Block")
        model_auto_wrap_policy = functools.partial(transformer_auto_wrap_policy, transformer_layer_cls={wrap_class},)

        shared_fsdp_kwargs = dict(
            auto_wrap_policy=model_auto_wrap_policy,
            sharding_strategy=ShardingStrategy.FULL_SHARD,
            cpu_offload=CPUOffload(offload_params=False),
            backward_prefetch=BackwardPrefetch.BACKWARD_PRE,
            ignored_modules=None,
            limit_all_gathers=False,
            use_orig_params=False,
            sync_module_states=False
        )
        mp_dtype = None
        policy_mp_policy = MixedPrecision(param_dtype=mp_dtype, reduce_dtype=mp_dtype, buffer_dtype=mp_dtype)
        self.policy = FSDP(self.policy, **shared_fsdp_kwargs, mixed_precision=policy_mp_policy)
        
        tokenized = self.tokenizer("hi there", return_tensors="pt").to(self.policy.device)
        print(self.policy.generate(**tokenized))
        return
    
if __name__ == '__main__':

    main() #BasicTrainer works, but FSDPTrainer errors
```

Error below
```
starting 2 processes for FSDP training
1 initializing distributed
0 initializing distributed
Creating trainer on process 0 with world size 2
Creating trainer on process 1 with world size 2
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
/anaconda/lib/python3.10/site-packages/transformers/generation/utils.py:1132: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
/anaconda/lib/python3.10/site-packages/transformers/generation/utils.py:1132: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
tensor([[5303,  612,  318,  257, 1256,  286,  670,  284,  307, 1760,   13,  198,
          198,    1, 1135,  423,  284,  787, 1654,  326]])
tensor([[5303,  612,  318,  257, 1256,  286,  670,  284,  307, 1760,   13,  198,
          198,    1, 1135,  423,  284,  787, 1654,  326]])
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "/home/azureuser/f-divergence-dpo/mwe.py", line 98, in <module>
    main()
  File "/home/azureuser/f-divergence-dpo/mwe.py", line 61, in main
    torch.multiprocessing.spawn(worker_main, nprocs=world_size, args=(world_size,), join=True)
  File "/anaconda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/anaconda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/anaconda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/anaconda/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/home/azureuser/f-divergence-dpo/mwe.py", line 51, in worker_main
    trainer = FSDPTrainer()
  File "/home/azureuser/f-divergence-dpo/mwe.py", line 92, in __init__
    print(self.policy.generate(**tokenized))
  File "/anaconda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/anaconda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1527, in generate
    result = self._greedy_search(
  File "/anaconda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2411, in _greedy_search
    outputs = self(
  File "/anaconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/anaconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/anaconda/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1074, in forward
    transformer_outputs = self.transformer(
  File "/anaconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/anaconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/anaconda/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 837, in forward
    inputs_embeds = self.wte(input_ids)
  File "/anaconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/anaconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/anaconda/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/anaconda/lib/python3.10/site-packages/torch/nn/functional.py", line 2237, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```

### Expected behavior

The code provided should not error

**Comment by younesbelkada** [comment]
Hi @QiyaoWei 
If I am not mistaken `FSDP` is not compatible with `generate` - cc @pacman100 @SunMarc (as I think we've discussed this offline at some point but not 100% sure)

**Comment by sahilsuneja1** [comment]
Hi @QiyaoWei,
Have a look at pacman100's `model(**batch)` workaround [here](https://github.com/huggingface/accelerate/issues/570) and [here](https://github.com/pytorch/pytorch/issues/82461)

**Comment by zzxslp** [comment]
> Hi @QiyaoWei If I am not mistaken `FSDP` is not compatible with `generate` - cc @pacman100 @SunMarc (as I think we've discussed this offline at some point but not 100% sure)

May I know why `FSDP` is not compatible with `generate`?

**Comment by QiyaoWei** [comment]
I think the `model(**dummy_batch)` workaround is the way to go. Basically the FSDP model would need an additional forward pass for `generate` to run

**Comment by gante** [comment]
@SunMarc do you know the status of `generate` 🤜 🤛 `FSDP`? Should we reopen this issue, or is it being tracked somewhere else?

**Comment by ArthurZucker** [comment]
👁️

**Comment by ringohoffman** [comment]
Related (and also auto-closed due to lack of activity):

* https://github.com/huggingface/accelerate/issues/570

**Comment by ringohoffman** [comment]
```
RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```

This error is solved by using `use_orig_params=True`:

```python
    fsdp_model = torch.distributed.fsdp.FullyShardedDataParallel(
        use_orig_params=True,
    )
```

From the [FSDP docs](https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.FullyShardedDataParallel):

> use_orig_params (bool) – ... True is required to use torch.compile(). ... (Default: False)

I am reasonably certain the reason for this error is from `generate` relying on a `torch.compile`-wrapped function.

**Comment by ringohoffman** [comment]
So after a lot longer than I would like to admit, I have uncovered all the gotchas of using `generate` with FSDP.

1. As I mentioned above, `torch.distributed.fsdp.FullyShardedDataParallel(use_orig_params=True)` is required when instantiating your FSDP instance. Otherwise, you get the error `The tensor has a non-zero number of elements, but its data is not allocated yet`. It seems likely that `generate` is calling a `torch.compile`-wrapped function.
2. Calls to `generate` must be inside a `torch.distributed.fsdp.FullyShardedDataParallel.summon_full_params(fsdp_model)` context, otherwise you get the error `'weight' must be 2-D` from the input embeddings still being flattened by FSDP.
3. Lastly, and most trickily, you must use `generate(synced_gpus=True)` when using differently-sized data across ranks. Otherwise, the different ranks will pause on different synchronization points leading to a deadlock.

Here is a minimum reproducible example to show these off:

```bash
OMP_NUM_THREADS=2 \
TOKENIZERS_PARALLELISM=false \
CUDA_VISIBLE_DEVICES=6,7 \
torchrun \
    --rdzv-backend=c10d \
    --rdzv-endpoint=localhost:0 \
    --nnodes=1 \
    --nproc-per-node=2 \
    fsdp_generate.py
```

**fsdp_generate.py**
```python
import functools

import torch
import torch.distributed
import torch.distributed.fsdp
import torch.distributed.fsdp.wrap
import transformers
import transformers.models.gpt_neo.modeling_gpt_neo


def main() -> None:
    torch.distributed.init_process_group(world_size=2)
    device = torch.device(torch.distributed.get_rank())
    torch.cuda.set_device(device)

    pretrained_model_name_or_path = "EleutherAI/gpt-neo-125m"
    model = transformers.AutoModelForCausalLM.from_pretrained(
        pretrained_model_name_or_path,
        device_map=device,
    )
    assert isinstance(model, transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoForCausalLM)
    tokenizer = transformers.AutoTokenizer.from_pretrained(
        pretrained_model_name_or_path
    )
    tokenizer.pad_token_id = tokenizer.eos_token_id

    fsdp_model = torch.distributed.fsdp.FullyShardedDataParallel(
        model,
        auto_wrap_policy=functools.partial(
            torch.distributed.fsdp.wrap.transformer_auto_wrap_policy,
            transformer_layer_cls={
                transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoBlock
            },
        ),
        limit_all_gathers=True,
        use_orig_params=True,  # required to overcome the error "The tensor has a non-zero number of elements, but its data is not allocated yet" ... PreTrainedModel.generate is probably using some torch.compile-wrapped function
    )

    data_by_rank = {  # differently-sized causes FSDP to hang
        0: "Hello world!",
        1: "The quick brown fox jumps over the lazy dog."
    }

    batch = tokenizer(
        data_by_rank[torch.distributed.get_rank()],
        return_tensors="pt",
        return_attention_mask=True,
    ).to(device)

    with torch.distributed.fsdp.FullyShardedDataParallel.summon_full_params(fsdp_model):  # required to overcome to the error "'weight' must be 2-D"
        generated_text = fsdp_model.module.generate(
            input_ids=batch["input_ids"],
            attention_mask=batch["attention_mask"],
            max_length=20,
            # synced_gpus=True,  # True is required to use differently sized data with FSDP + generate (current default is False)
        )

    torch.distributed.barrier()
    torch.distributed.destroy_process_group()


if __name__ == "__main__":
    main()

```

My takeaways from this:

1. Improve the `synged_gpus` documentation

https://github.com/huggingface/transformers/blob/a05ce550bf1cda8ae3bffcc62607597770460a42/src/transformers/generation/utils.py#L1742-L1745

it makes no mention of `FullyShardedDataParallel`.

2. Can `synced_gpus=None` default to `True` when using FSDP, the same as it does for DeepSpeed ZeRo-3?

https://github.com/huggingface/transformers/blob/a05ce550bf1cda8ae3bffcc62607597770460a42/src/transformers/trainer_seq2seq.py#L294-L297

https://github.com/huggingface/transformers/blob/a05ce550bf1cda8ae3bffcc62607597770460a42/src/transformers/generation/utils.py#L1788-L1792

It would be nice to save people the trouble of figuring this out if we could automatically detect FSDP usage.

3. Document `use_orig_params` and `summon_full_params`.

**Comment by ShengYun-Peng** [comment]
> Issue with FSDP + HuggingFace generate pytorch/pytorch#100069

Thank you so much! It's working on 7b and 8b model on my side. However, I noticed an extremely high GPU memory consumption after summon_full_params. It also leads to OOM while inferencing with 70b models on 8 nodes. I can successfully finetune 70b on 8 nodes, so technically, inference should take fewer nodes. I'm curious if you have any work around methods.

**Comment by ringohoffman** [comment]
> > Issue with FSDP + HuggingFace generate [pytorch/pytorch#100069](https://github.com/pytorch/pytorch/issues/100069)
> 
> Thank you so much! It's working on 7b and 8b model on my side. However, I noticed an extremely high GPU memory consumption after summon_full_params. It also leads to OOM while inferencing with 70b models on 8 nodes. I can successfully finetune 70b on 8 nodes, so technically, inference should take fewer nodes. I'm curious if you have any work around methods.

Check out FSDP2: 

https://github.com/huggingface/transformers/blob/30335093276212ce74938bdfd85bfd5df31a668a/tests/generation/test_fsdp.py#L81-L101

It solves a lot of the problems with FSDP, like having to use `summon_full_params`.

**Comment by farzadab** [comment]
@ringohoffman can you explain a bit more?

I think I'm doing exactly what `fsdp2_generate` does, but I still get OOM:

```python
# CUDA_VISIBLE_DEVICES=0,1 uv run torchrun --nproc_per_node=2 test_infer.py
# running on 2x4090 with 24GB VRAM each
import torch
import torch
import transformers
from torch.distributed._composable.fsdp import fully_shard, register_fsdp_forward_method
from torch.distributed.device_mesh import init_device_mesh


torch.distributed.init_process_group(backend="nccl")

torch.cuda.set_device(device := torch.device(rank := torch.distributed.get_rank()))

model = transformers.AutoModelForCausalLM.from_pretrained(
    "google/gemma-3-12b-it",
    torch_dtype=torch.bfloat16,
).to(device)

mesh = init_device_mesh("cuda", (torch.distributed.get_world_size(),))
for submodule in model.modules():
    if isinstance(submodule, transformers.models.llama.modeling_llama.LlamaDecoderLayer):
        fully_shard(submodule, mesh=mesh)
fully_shard(model, mesh=mesh)

register_fsdp_forward_method(model, "generate")

# ...
```

**Comment by ringohoffman** [comment]
> @ringohoffman can you explain a bit more?
> 
> 
> I think I'm doing exactly what `fsdp2_generate` does, but I still get OOM.
> To clarify, I can get the code to work with smaller models as @ShengYun-Peng mentioned, but I still get OOM when I use a larger model:
> 
> ```python
> # CUDA_VISIBLE_DEVICES=0,1 uv run torchrun --nproc_per_node=2 test_infer.py
> # running on 2x4090 with 24GB VRAM each
> import torch
> import torch
> import transformers
> from torch.distributed._composable.fsdp import fully_shard, register_fsdp_forward_method
> from torch.distributed.device_mesh import init_device_mesh
> 
> 
> torch.distributed.init_process_group(backend="nccl")
> 
> torch.cuda.set_device(device := torch.device(rank := torch.distributed.get_rank()))
> 
> model = transformers.AutoModelForCausalLM.from_pretrained(
>     "google/gemma-3-12b-it",  # or instead use meta-llama/Llama-3.3-70B-Instruct
>     torch_dtype=torch.bfloat16,
> ).to(device)
> 
> mesh = init_device_mesh("cuda", (torch.distributed.get_world_size(),))
> for submodule in model.modules():
>     if isinstance(submodule, transformers.models.llama.modeling_llama.LlamaDecoderLayer):
>         fully_shard(submodule, mesh=mesh)
> fully_shard(model, mesh=mesh)
> 
> register_fsdp_forward_method(model, "generate")
> 
> # ...
> ```

Gemma's decoder layer doesn't inherit from `LlamaDecoderLayer`. You need to change the type:

https://github.com/huggingface/transformers/blob/800510c67bfc5cedd0bb7635648a07f39719be43/src/transformers/models/gemma/modeling_gemma.py#L312

**Comment by ShengYun-Peng** [comment]
> [@ringohoffman](https://github.com/ringohoffman) can you explain a bit more?
> 
> I think I'm doing exactly what `fsdp2_generate` does, but I still get OOM. To clarify, I can get the code to work with smaller models as [@ShengYun-Peng](https://github.com/ShengYun-Peng) mentioned, but I still get OOM when I use a larger model:
> 
> # CUDA_VISIBLE_DEVICES=0,1 uv run torchrun --nproc_per_node=2 test_infer.py
> # running on 2x4090 with 24GB VRAM each
> import torch
> import torch
> import transformers
> from torch.distributed._composable.fsdp import fully_shard, register_fsdp_forward_method
> from torch.distributed.device_mesh import init_device_mesh
> 
> 
> torch.distributed.init_process_group(backend="nccl")
> 
> torch.cuda.set_device(device := torch.device(rank := torch.distributed.get_rank()))
> 
> model = transformers.AutoModelForCausalLM.from_pretrained(
>     "google/gemma-3-12b-it",  # or instead use meta-llama/Llama-3.3-70B-Instruct
>     torch_dtype=torch.bfloat16,
> ).to(device)
> 
> mesh = init_device_mesh("cuda", (torch.distributed.get_world_size(),))
> for submodule in model.modules():
>     if isinstance(submodule, transformers.models.llama.modeling_llama.LlamaDecoderLayer):
>         fully_shard(submodule, mesh=mesh)
> fully_shard(model, mesh=mesh)
> 
> register_fsdp_forward_method(model, "generate")
> 
> # ...

After exploring FSDP for a few months, I'd recommend you try deepspeed. It saves you tons of time and energy.

**Comment by farzadab** [comment]
Oh thanks! That's an embarrassing mistake. I kept going back and fourth and missed this because I had another issue 😅

I also had to remove the `.to(device)` for it to work, as it prematurely moves everything to device.

Follow up question: is there an equivalent way to doing `sync_module_states` to avoid loading the model on CPU multiple times (i.e. one per process) when using `fully_shard` manually in this way instead of wrapping with FSDP module?

**Comment by ringohoffman** [comment]
> Follow up question: is there an equivalent way to doing `sync_module_states` to avoid loading the model on CPU multiple times (i.e. one per process) when using `fully_shard` manually in this way instead of wrapping with FSDP module?

There is a work in progress PR to support this in `accelerate`:

* https://github.com/huggingface/accelerate/pull/3432

It loads only on rank 0 and broadcasts it to other ranks in [`accelerate.load_checkpoint_and_dispatch`](https://huggingface.co/docs/accelerate/v1.6.0/en/package_reference/big_modeling#accelerate.load_checkpoint_and_dispatch) via [`torch.distributed.checkpoint.state_dict.set_model_state_dict`](https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.set_model_state_dict). It is definitely faster.

[Here is the example of how it will look like to use it with FSDP2, if you're interested.](https://github.com/huggingface/accelerate/pull/3432/files#diff-acc73a2fa49d3c94570ef080895067f93dee85c15bdce3b7b4fbed36ace4fc6bR55-R101) You can install my branch in your project by putting the following in your `pyproject.toml`.

```toml
dependencies = [
    "accelerate @ git+https://github.com/ringohoffman/accelerate@load_checkpoint_in_model-use-set_model_state_dict#egg=accelerate",
]
```

**Comment by ringohoffman** [comment]
@anmolagarwal999 The example I posted originally still works, so there isn't any reason that I am already aware of that your code should hang. If you can create a minimum reproducible example, it will be easier to diagnose.

**Comment by anmolagarwal999** [comment]
> [@anmolagarwal999](https://github.com/anmolagarwal999) The example I posted originally still works, so there isn't any reason that I am already aware of that would explain why your code would hang. If you can create a minimum reproducible example, it will be easier to diagnose.

Thanks for your reply @ringohoffman , I will try to create a reproducible example and get back here. In the meantime, does the code in approach 1 look accurate? I do get responses and the code runs (though very slowly), but I am unsure about it's correctness.

**Comment by ringohoffman** [comment]
> > [@anmolagarwal999](https://github.com/anmolagarwal999) The example I posted originally still works, so there isn't any reason that I am already aware of that would explain why your code would hang. If you can create a minimum reproducible example, it will be easier to diagnose.
> 
> Thanks for your reply [@ringohoffman](https://github.com/ringohoffman) , I will try to create a reproducible example and get back here. In the meantime, does the code in approach 1 look accurate? I do get responses and the code runs (though very slowly), but I am unsure about it's correctness.

If you're using FSDP and not using `use_orig_params=True` and `summon_full_params`, it's not clear to me how it would be working. See for yourself by running my example:

> Here is a minimum reproducible example to show these off:
> 
> ```
> OMP_NUM_THREADS=2 \
> TOKENIZERS_PARALLELISM=false \
> CUDA_VISIBLE_DEVICES=6,7 \
> torchrun \
>     --rdzv-backend=c10d \
>     --rdzv-endpoint=localhost:0 \
>     --nnodes=1 \
>     --nproc-per-node=2 \
>     fsdp_generate.py
> ```
> **fsdp_generate.py**
> ```python
> import functools
> 
> import torch
> import torch.distributed
> import torch.distributed.fsdp
> import torch.distributed.fsdp.wrap
> import transformers
> import transformers.models.gpt_neo.modeling_gpt_neo
> 
> 
> def main() -> None:
>     torch.distributed.init_process_group(world_size=2)
>     device = torch.device(torch.distributed.get_rank())
>     torch.cuda.set_device(device)
> 
>     pretrained_model_name_or_path = "EleutherAI/gpt-neo-125m"
>     model = transformers.AutoModelForCausalLM.from_pretrained(
>         pretrained_model_name_or_path,
>         device_map=device,
>     )
>     assert isinstance(model, transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoForCausalLM)
>     tokenizer = transformers.AutoTokenizer.from_pretrained(
>         pretrained_model_name_or_path
>     )
>     tokenizer.pad_token_id = tokenizer.eos_token_id
> 
>     fsdp_model = torch.distributed.fsdp.FullyShardedDataParallel(
>         model,
>         auto_wrap_policy=functools.partial(
>             torch.distributed.fsdp.wrap.transformer_auto_wrap_policy,
>             transformer_layer_cls={
>                 transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoBlock
>             },
>         ),
>         limit_all_gathers=True,
>         use_orig_params=True,  # required to overcome the error "The tensor has a non-zero number of elements, but its data is not allocated yet" ... PreTrainedModel.generate is probably using some torch.compile-wrapped function
>     )
> 
>     data_by_rank = {  # differently-sized causes FSDP to hang
>         0: "Hello world!",
>         1: "The quick brown fox jumps over the lazy dog."
>     }
> 
>     batch = tokenizer(
>         data_by_rank[torch.distributed.get_rank()],
>         return_tensors="pt",
>         return_attention_mask=True,
>     ).to(device)
> 
>     with torch.distributed.fsdp.FullyShardedDataParallel.summon_full_params(fsdp_model):  # required to overcome to the error "'weight' must be 2-D"
>         generated_text = fsdp_model.module.generate(
>             input_ids=batch["input_ids"],
>             attention_mask=batch["attention_mask"],
>             max_length=20,
>             # synced_gpus=True,  # True is required to use differently sized data with FSDP + generate (current default is False)
>         )
> 
>     torch.distributed.barrier()
>     torch.distributed.destroy_process_group()
> 
> 
> if __name__ == "__main__":
>     main()
> ```

**Comment by farzadab** [comment]
Thanks @ringohoffman. The `broadcast_from_rank0` is exactly what I'm looking for, but what makes `load_checkpoint_and_dispatch` totally useless for me is that it doesn't allow renaming parameters, i.e. doesn't respect parameters like `base_model_prefix`, or `_keys_to_ignore_on_load_missing` and keeps saying the weights were missing even though they're there just with a slightly different variation in name.

**Comment by ringohoffman** [comment]
> Thanks [@ringohoffman](https://github.com/ringohoffman). The `broadcast_from_rank0` is exactly what I'm looking for, but what makes `load_checkpoint_and_dispatch` totally useless for me is that it doesn't allow renaming parameters, i.e. doesn't respect parameters like `base_model_prefix`, or `_keys_to_ignore_on_load_missing` and keeps saying the weights were missing even though they're there just with a slightly different variation in name.

Just patch [`load_state_dict`](https://github.com/huggingface/accelerate/blob/34c1779828b3d0769992e6492e6de93d869f71b5/src/accelerate/utils/modeling.py#L1931) to do what you need. If you can clearly define your interface and use case, maybe the `accelerate` team would be willing to add this to the API.

BTW, this is exactly what I was doing before I made my PR.

```python
import functools

import accelerate.utils.modeling

def load_state_dict_remap_names(
    checkpoint_file: str,
    device_map: int | str | torch.device | dict[str, int | str | torch.device] | None = None,
    my_kwarg: Any,
) -> dict[str, Any]:
    ...

accelerate.utils.modeling.load_state_dict = functools.partial(load_state_dict_remap_names, my_kwarg=...)
accelerate.load_checkpoint_and_dispatch(...)
```

**Comment by SunMarc** [comment]
> If you can clearly define your interface and use case, maybe the accelerate team would be willing to add this to the API.

Indeed ! Feel free to submit a PR !

**Comment by steveepreston** [comment]
Does this supports TPU too?
