### ISSUE TITLE
BART : host `bart-large-cnn`

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#3023]
# 🌟 New model addition

BART pretrained model `bart-large` is currently provided, as well as fine-tuned BART model `bart-large-mnli`.

**How about [`bart-large-cnn`](https://github.com/pytorch/fairseq/tree/master/examples/bart#pre-trained-models) ?**

**Comment by BramVanroy** [comment]
IIRC @sshleifer  is working on getting summarization working with that model.
