### ISSUE TITLE
This class and module cannot be found

### ISSUE THREAD

**Issue by bboyxu5928** [huggingface/transformers#3027]
I want to use BertForNextSentencePrediction in ' modeling_bert.py' line 1020  ,but when I run Examples in line 1065,  error happens

  File "E:\work\pycharm\transformers-master\src\transformers\tokenization_bert.py", line 24, in <module>
    from tokenizers import BertWordPieceTokenizer
ImportError: No module named 'tokenizers'

where I can find this module tokenizers,
thanks !!

**Comment by BramVanroy** [comment]
You can do `pip install tokenizers` or [install from source](https://github.com/huggingface/tokenizers).

**Comment by bboyxu5928** [comment]
> You can do `pip install tokenizers` or [install from source](https://github.com/huggingface/tokenizers).

OK， I've got it ,thank you

**Comment by BinchaoPeng** [comment]
> pip install tokenizers

```bash
Requirement already satisfied: tokenizers in ./anaconda3/envs/dnabert/lib/python3.6/site-packages (0.8.1rc2)
```

I did it,but it also has the error

**Comment by BinchaoPeng** [comment]
in my another computer, the env displays its version is 0.5.0, so why give me 0.8.1rc2? sometimes i want to say, the doc is hard to understand, when understanded, the errors occurs one by one because of some small tips, is it my fault? maybe, but why not write it straightly?
