### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by immi19** [huggingface/transformers#30279]
@Michellehbn  @huggingface
need access to the Huggingface Private Bug Bounty Program

https://hackerone.com/hugging_face

I request the team to send me an invite for the Huggingface Private Bug Bounty Program

My Hackerone Id: sheikhimmi

I had already email to the security team but not yet get any response 

Hope the team will send me an invite soon

Regards

**Comment by amyeroberts** [comment]
cc @Michellehbn

**Comment by Michellehbn** [comment]
Done!
