### ISSUE TITLE
Skipping Layers in a forward pass

### ISSUE THREAD

**Issue by IsNoobgrammer** [huggingface/transformers#30286]
### Feature request

How can we make input tokens pass through only selected layers/blocks 
for ex:- In Mistral every input tokens pass through ```embedding -> then 32 layers -> lmhead```

But how can we make that Input tokens pass through only ```embedding -> first 20 layers and last 6 layers only -> lmhead```

### Motivation

Various Reasearch Shows that there are layers redunduncy in Transformers architechture
Especially last layers of models are redundant

### Your contribution

-

**Comment by amyeroberts** [comment]
Hi, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by amyeroberts** [comment]
Hi @IsNoobgrammer, thanks for raising an issue! 

This is a more of a question for our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for specific feature requests and bug reports.

If you want to use fewer layers, you could just hack it like this: 

```py
from transformers import AutoModelForCausalLM

checkpoint = "mistralai/Mistral-7B-Instruct-v0.2"
model = AutoModelForCausalLM.from_pretrained(checkpoint)

model.model.layers = model.model.layers[:20] + model.model.layers[-6:]
```
