### ISSUE TITLE
show we add <image> token to the prompt if we use llava-hf from transformers?

### ISSUE THREAD

**Issue by DefTruth** [huggingface/transformers#30284]
### System Info

For the official llava (not the one in transformers), need to add an <image> token for inference:  
```python
inp = DEFAULT_IMAGE_TOKEN + '\n' + inp
```
show we add <image> token to the prompt if we use llava-hf from transformers?

### Who can help?

@amyeroberts @ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

none

### Expected behavior

none

**Comment by DefTruth** [comment]
https://github.com/haotian-liu/LLaVA/blob/4e2277a060da264c4f21b364c867cc622c945874/llava/serve/cli.py#L83

**Comment by zucchini-nlp** [comment]
Hi @DefTruth ! Yes, the special `<image>` token should be added to generate using an image. See [here](https://huggingface.co/docs/transformers/en/model_doc/llava#transformers.LlavaForConditionalGeneration.forward.example) for an example generation code 🤗

**Comment by DefTruth** [comment]
thanks, i will try.
