### ISSUE TITLE
How to add data to  pretrained model.

### ISSUE THREAD

**Issue by ynebula** [huggingface/transformers#3029]
I want to add wiki data to pretrained model.

   i.e., kor wiki data is added to XLMRoberta Model weight.

I think that files in /transformers/templates/adding_a_new_model do

Is it right?

please let me know way to add data.

**Comment by BramVanroy** [comment]
Have a look at the language modeling example:

https://huggingface.co/transformers/examples.html#language-model-training

https://github.com/huggingface/transformers/blob/master/examples/run_language_modeling.py

**Comment by ynebula** [comment]
Thank you for your answering.

I did that^^
