### ISSUE TITLE
Attention implementation cannot work together with config in AutoModel

### ISSUE THREAD

**Issue by hiyouga** [huggingface/transformers#30298]
### System Info

- `transformers` version: 4.40.0.dev0
- Platform: Linux-5.15.0-100-generic-x86_64-with-glibc2.35
- Python version: 3.11.8
- Huggingface_hub version: 0.21.4
- Safetensors version: 0.4.2
- Accelerate version: 0.28.0
- PyTorch version (GPU?): 2.2.0+cu121 (True)

### Who can help?

@younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Similar to https://github.com/huggingface/transformers/issues/28038

We want to pass a model config to `from_pretrained` with an `attn_implementation` parameter. The attention type cannot be faithful to the one in the `attn_implementation`

```python
from transformers import AutoConfig, AutoModelForCausalLM
model_name = "meta-llama/Llama-2-7b-hf"
config = AutoConfig.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, config=config, attn_implementation="eager")
print(model.config._attn_implementation)
# sdpa
```

### Expected behavior

`_attn_implementation` should be `eager`

**Comment by hiyouga** [comment]
Given the logic below, we cannot enforce the model to use eager attention, since `config._attn_implementation` falls back to eager when `config._attn_implementation_internal` is None [1]. Hence, the if condition `config._attn_implementation != kwarg_attn_imp` cannot hold, and the `config._attn_implementation_internal` will be not affected, resulting a SDPA attention [2].

https://github.com/huggingface/transformers/blob/e4ea19b958c89d61e42461fac6ac8441787121f8/src/transformers/modeling_utils.py#L3138-L3150

I think we should use `config._attn_implementation_internal != kwarg_attn_imp` instead

1: 

https://github.com/huggingface/transformers/blob/e4ea19b958c89d61e42461fac6ac8441787121f8/src/transformers/configuration_utils.py#L406-L420

2: 
https://github.com/huggingface/transformers/blob/e4ea19b958c89d61e42461fac6ac8441787121f8/src/transformers/modeling_utils.py#L1461-L1466

**Comment by amyeroberts** [comment]
cc @fxmarty
