### ISSUE TITLE
Can't load tokenizer

### ISSUE THREAD

**Issue by wb-zr707791** [huggingface/transformers#30309]
OSError: Can't load tokenizer for 'togethercomputer/LLaMA-2-7B-32K'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'togethercomputer/LLaMA-2-7B-32K' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

请问这个问题该如何解决？

我已经尝试了通过access token的方式，不起作用
def cl100k(text, tokenizer):
    return tokenizer.encode(text, disallowed_special=())

def llama(text, tokenizer):
    return tokenizer(text, add_special_tokens=True, return_attention_mask=False)[
        "input_ids"
    ]

TOKENIZER_FUNCS = {
    "cl100k": (tiktoken.get_encoding("cl100k_base"), cl100k),
    "llama": (LlamaTokenizer.from_pretrained("togethercomputer/LLaMA-2-7B-32K", token=""), llama),
}

**Comment by amyeroberts** [comment]
Hi @wb-zr707791, please follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) nd provide information about the running environment. 

It's possible this was a connection issue. I'm unable to replicate it on my end and can successfully load the tokenizer:

```py
In [1]: from transformers import LlamaTokenizer

In [2]: tokenizer = LlamaTokenizer.from_pretrained("togethercomputer/LLaMA-2-7B-32K")
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████| 942/942 [00:00<00:00, 926kB/s]
tokenizer.model: 100%|████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 17.0MB/s]
added_tokens.json: 100%|██████████████████████████████████████████████████████████████████████████████████████| 4.00/4.00 [00:00<00:00, 9.15kB/s]
special_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████████████████████| 96.0/96.0 [00:00<00:00, 290kB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 4.93MB/s]
```
