### ISSUE TITLE
assisted_decoding does not correctly update static KV cache

### ISSUE THREAD

**Issue by learning-chip** [huggingface/transformers#30312]
Inside `assisted_decoding`, KV cache is cropped to the actual accepted tokens via `_crop_past_key_values`:

```python
            new_cache_size = new_cur_len - 1
            outputs.past_key_values = _crop_past_key_values(self, outputs.past_key_values, new_cache_size)
```
https://github.com/huggingface/transformers/blob/v4.39.3/src/transformers/generation/utils.py#L4576-L4578

However, `_crop_past_key_values` dynamically creates a new KV cache with shorter length:

```python
        for idx in range(len(past_key_values)):
            new_past.append(
                (
                    past_key_values[idx][0][:, :, :maximum_length, :],
                    past_key_values[idx][1][:, :, :maximum_length, :],
                )
            )
        past_key_values = tuple(new_past)
```
https://github.com/huggingface/transformers/blob/v4.39.3/src/transformers/generation/candidate_generator.py#L368-L375

With `StaticCache`, should use in-place write instead.

**Comment by amyeroberts** [comment]
@gante

**Comment by learning-chip** [comment]
Because `cache_position` is updated accordingly, maybe no need to crop `past_key_values ` at all? Next step the newly computed KVs (of speculative length) will be written into cache, overwriting the old values.

```python
                candidate_kwargs["cache_position"] = torch.cat(
                    (
                        candidate_kwargs["cache_position"],
                        torch.arange(cur_len, cur_len + candidate_length, device=input_ids.device, dtype=torch.long),
                    ),
                    dim=0,
                )
```
https://github.com/huggingface/transformers/blob/v4.39.3/src/transformers/generation/utils.py#L4505-L4511

**Comment by zucchini-nlp** [comment]
@learning-chip currently assisted generation does not work for Static Cache if some candidate tokens are discarded. Ss you have mentioned past kv cache does not need to be cropped, but `cache_position` needs to be updated according to number of accepted candidate tokens. 

There is a [PR](https://github.com/huggingface/transformers/pull/30068) for fixing `cache position` in assisted generation, should be working after that  : )

**Comment by zucchini-nlp** [comment]
I will close the issue as the PR was merged. To get the assisted generation working with static cache install the latest version from `main` with `!pip install --upgrade git+https://github.com/huggingface/transformers.git`

Feel free to open again if the problem persists 🤗
