### ISSUE TITLE
Loading custom weights for BERT in pytorch

### ISSUE THREAD

**Issue by LivC182** [huggingface/transformers#3032]
Is it possible to load custom pre-trained weights for BERT, other than the one you provide ?

**Comment by BramVanroy** [comment]
Yes. Have a look at the documentation for [`from_pretrained`](https://huggingface.co/transformers/main_classes/model.html#transformers.PreTrainedModel.from_pretrained), particularly the `pretrained_model_name_or_path ` argument.

**Comment by LivC182** [comment]
Yes sorry I looked after I asked and found everything I needed it
