### ISSUE TITLE
RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: auto

### ISSUE THREAD

**Issue by yumlevi** [huggingface/transformers#30350]
### System Info

git latest
linux
h100 x 8 node

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run llama3 example script

```python
import transformers
import torch

model_id = "meta-llama/Meta-Llama-3-70B-Instruct"

pipeline = transformers.pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"torch_dtype": torch.bfloat16},
    device="auto",
)

messages = [
    {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
    {"role": "user", "content": "Who are you?"},
]

prompt = pipeline.tokenizer.apply_chat_template(
        messages, 
        tokenize=False, 
        add_generation_prompt=True
)

terminators = [
    pipeline.tokenizer.eos_token_id,
    pipeline.tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

outputs = pipeline(
    prompt,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)
print(outputs[0]["generated_text"][len(prompt):])
``` 

### Expected behavior

work?, works when using mistral 22b with auto.

**Comment by amyeroberts** [comment]
cc @ArthurZucker

**Comment by vasqu** [comment]
Haven't tested but shouldn't it be:
```python
pipeline = transformers.pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"torch_dtype": torch.bfloat16},
    device_map="auto",
)
```

`Device` usually requires the specific device type as stated in the error while `device_map` iirc uses accelerate to infer your device(s). There is also an inconsistency in the docs here when you compare the instruct and non-instruct variants (i.e. non-instruct suggests `device_map`). See the [source code](https://github.com/huggingface/transformers/blob/745bbfe4bb2b61491dedd56e1e8ee4af8ef1a9ec/src/transformers/pipelines/__init__.py#L674).

**Comment by xtchen96** [comment]
tested, worked fine with device_map='auto'
