### ISSUE TITLE
Trainer doesn't respect neither generation_max_length nor model.config.max_length

### ISSUE THREAD

**Issue by kirk86** [huggingface/transformers#30361]
### System Info

4.39.3
linux
python 3.12

### Who can help?

@muellerzr @pacman100 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Set the training arguments initially to `predict_with_generate=True`
2. Check the max seq len in the model config `model.config.max_length=30`, but the `predictions` are always of `max_length=20`.
3. Set alongside `predict_with_generate=True` also `generation_max_length=26`.
4. Now upon inspection inside `compute_metrics` the `predictions` are always fluctuating between `20-26` causing an error when trying to compute additional metrics since the `predictions.dim = [batch_size, input_seq_len] =!= labels.dim = [batch_size, label_seq_len]`
5. After tokenizing inputs and labels I end up with `input_ids = [batch_size, input_seql_len = 29]` and `labels = [batch_size, label_seq_len = 26]`.
6. Now at the generation step inside `compute_metrics` to calculate `rouge` the `predictions` always have dim `[batch_size, 20]` if I only use the training argument `predict_with_generate`
7. If I also add the training argument `generation_max_length=26` then the `predictions = [batch_size, seq_len]`, `seq_len` fluctuates between `20` and `26` from epoch to epoch. Other times is`23` other times `22` making impossible to calculate `rouge` or other metrics since it doesn't match the dimension of the `labels`.

### Expected behavior

Expecting both `predictions` and `labels` to have the same dimensions so that one could calculate additional metrics.

**Comment by amyeroberts** [comment]
cc @gante too as it relates to generation

**Comment by kirk86** [comment]
@gante @amyeroberts 

I'm just commented here in case someone sees it and provides some guidance.
In the [docs](https://huggingface.co/docs/transformers/v4.40.1/en/main_classes/text_generation#transformers.GenerationConfig) it states the following:

```
# If you'd like to try a minor variation to an existing configuration, you can also pass generation
# arguments to `.from_pretrained()`. Be mindful that typos and unused arguments will be ignored
generation_config, unused_kwargs = GenerationConfig.from_pretrained(
    "openai-community/gpt2", top_k=1, foo=False, do_sample=True, return_unused_kwargs=True
)
generation_config.top_k
1
```

The above examples doesn't work for all models, for instance, `OSError: bloomberg/KeyBART does not appear to have a file named generation_config.json. Checkout 'https://huggingface.co/bloomberg/KeyBART/main' for available files.`

1. I tried to pass the default arguments of `model.generation_config` and setting only those arguments that I'm interested.
For instance:
```
setattr(model.generation_config, 'max_new_tokens', 128)
generation_config = GenerationConfig(**model.generation_config.to_dict())
```
This didn't work, complaining about hashing.
`AttributeError: 'GenerationConfig' object has no attribute '_original_object_hash'`


2. This time I just took the values of `model.generation_config` added `max_new_tokens = 128` and then passed that to `TrainingArguments` which to my surprise is not picking up the newly set value of `max_new_tokens`

```
    generation_config = GenerationConfig(
        bos_token_id           = 0,
        decoder_start_token_id = 2,
        early_stopping         = True,
        eos_token_id           = 2,
        forced_eos_token_id    = 2,
        max_new_tokens         = 32,
        no_repeat_ngram_size   = 3,
        num_beams              = 4,
        pad_token_id           = 1,
    )

```

```
Predictions.shape = (4988, 20), Labels.shape = (4988, 33)█
ValueError: operands could not be broadcast together with shapes (4988,19) (4988,32) 
```
Is there some caching going on? I can't explain this but is driving me nuts, lost a day trying to figure this out and still nothing.
When we make changes to any code files they should take precedence over any "potential" caching or any other thing going on in the background.
