### ISSUE TITLE
Similarity search bug - urgent

### ISSUE THREAD

**Issue by ssdidis** [huggingface/transformers#30363]
### System Info

Exception has occurred: AttributeError
'HuggingFaceEmbeddings' object has no attribute 'encode'
  File "/home/ubuntu/new_d.py", line 38, in perform_similarity_search
    query_vector = embeddings.encode(['High blood pressure is caused by eating salt'])
                   ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/new_d.py", line 58, in run_indexing_pipeline
    distances, indices = perform_similarity_search(query, faiss_index, embeddings_model)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/new_d.py", line 63, in <module>
    run_indexing_pipeline()
AttributeError: 'HuggingFaceEmbeddings' object has no attribute 'encode'

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

def perform_similarity_search(query_text, index, embeddings, top_k=5):
    """Perform similarity search in the FAISS index for a given query text."""
    # Use the embeddings object to embed the query_text into a vector.
    # Ensure the text is passed as a list and the result is accessed correctly.
    query_vector = embeddings.encode(['High blood pressure is caused by eating salt'])
    # Reshape the query_vector for compatibility with FAISS search method if necessary.
    # FAISS expects the query vector to be a 2D array.
    if len(query_vector.shape) == 1:
        query_vector = query_vector.reshape(1, -1)
        
    # Search the index using the reshaped query_vector.
    distances, indices = index.search(query_vector, top_k)  # Search the index for the top_k closest vectors
    return distances, indices

### Expected behavior

1. the similarity search function should return data that is most similar to the query text.

**Comment by amyeroberts** [comment]
Hi, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
