### ISSUE TITLE
All-zero embedding distorts StaticCache.get_seq_length() output

### ISSUE THREAD

**Issue by poedator** [huggingface/transformers#30377]
### System Info

StaticCache.get_seq_length() method detects cache use status based on non-zero cache values. [link](https://github.com/huggingface/transformers/blob/8c12690cecbb97e187861e386f7a0ac790e4236c/src/transformers/cache_utils.py#L414)
I just stumbled upon 2 cases of models that have all-zeros embedding for `token_id==1` which distorts the output:
- [JackFram/llama-160m](https://huggingface.co/JackFram/llama-160m/discussions/15)
- [JackFram/llama-68m](https://huggingface.co/JackFram/llama-160m/discussions/7)

No blame here, just a combination of design decisions with unpredictable results. But there should be a more robust `get_seq_length()` method for StaticCache. I wonder if this is in the roadmap somewhere?

### Who can help?
 cc @ArthurZucker @younesbelkada 

### how to observe
```
model_name = "JackFram/llama-68m"
model = transformers.AutoModelForCausalLM.from_pretrained(model_name)
model.model.embed_tokens.weight
>>>Parameter containing:
>>> tensor(
        [[-0.0095,  0.0167,  0.0140,  ...,  0.0002,  0.0112,  0.0059],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],    # here it is, all zeros
        [-0.0194,  0.0022, -0.0326,  ...,  0.0332, -0.0052, -0.0284],
        ...,
)
input_ids=tensor([[   1,  450, 6635, 3290]])
model.forward(input_ids=input_ids, ...
...
model.model.layers[0].self_attn.past_key_value.get_seq_length()
>>>tensor(3)  # THIS SHOULD BE 4
self.tree.engine.model.model.layers[0].self_attn.past_key_value.key_cache[0,0,:,0]
>>> tensor([ 0.0000, -1.5942, -0.8042,  1.0514,  0.0000,  0.0000,  0.0000,  ...
```

**Comment by ArthurZucker** [comment]
`StaticCache.get_seq_length()` should not even exist. We ought to rely on `cache_positions`

**Comment by ArthurZucker** [comment]
Roadmap is to deprecate all calls to `get_seq_length`, cc @gante
