### ISSUE TITLE
Add Llama 3 support to `convert_llama_weights_to_hf()`

### ISSUE THREAD

**Issue by calmitchell617** [huggingface/transformers#30388]
### Feature request

Add Llama 3 support to [`convert_llama_weights_to_hf()`](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py).

### Motivation

I am using [torchtune](https://github.com/pytorch/torchtune) to fine-tune Llama 3. The easiest way to output checkpoints of that model with that lib is the Meta checkpointer. Checkpoints saved with that checkpointer are not loadable with `from_pretrained()`, which makes it hard to use Llama 3 models fine-tuned with torchtune in the Huggingface ecosystem (such as with Gradio).

### Your contribution

I will contribute a PR if someone from HF will take a look at it once submitted.

**Comment by amyeroberts** [comment]
cc @ArthurZucker

**Comment by calmitchell617** [comment]
I successfully performed the following steps to ensure this script can facilitate the use case I outlined above:

Download Llama 2 in meta format (not HF format) with provided script in torchtune. It is important not to use a HF format Llama 2 model id, because Llama 3 is not yet officially uploaded in HF format, so it wouldn't be an apples to apples comparison.

```
tune download meta-llama/Llama-2-7b-chat --output-dir <checkpoint_path> --hf-token $HF_TOKEN
```

Fine tuned Llama 2 with torchtune:

```
clear && tune run \
    --nproc_per_node=4 \
    lora_finetune_distributed \
    --config llama2/7B_lora \
    batch_size=1 \
    seed=29 \
    tokenizer.path=<checkpoint_path> \
    checkpointer.checkpoint_dir=<checkpoint_path> \
    checkpointer.output_dir=<checkpoint_path> \
    dataset=torchtune.datasets.my_custom_dataset \
    checkpointer.checkpoint_files=['consolidated.00.pth'] \
    checkpointer=torchtune.utils.FullModelMetaCheckpointer \
    gradient_accumulation_steps=1 \
    lr_scheduler.num_warmup_steps=5 \
    enable_activation_checkpointing=False \
    dataset.max_rows=100 \
    epochs=1
```

Convert fine-tuned model to format that can be loaded with `from_pretrained()`. I named the script `convert_checkpoint.py`, but it is just the `convert_llama_weights_to_hf()` function copy/pasted from Transformers:

```
python convert_checkpoint.py --input_dir <checkpoint_dir> --output_dir <output_dir>  --model_size 7B
```

I then ran a Gradio chatbot on the fine-tuned/converted model, and it worked as expected. So, it does seem that adding Llama 3 support to this script will unlock my particular use case (and probably many others).

**Comment by ArthurZucker** [comment]
see #30334

**Comment by calmitchell617** [comment]
Thank you! I will keep an eye on that on that PR.

**Comment by ArthurZucker** [comment]
Just needs the doc 🤗
