### ISSUE TITLE
Idefics2 - sdpa vs flash attn 2

### ISSUE THREAD

**Issue by VictorSanh** [huggingface/transformers#30394]
### Feature request

Right now, when i do

```
Idefics2ForConditionalGeneration.from_pretrained(
    "defics2-8b",
    torch_dtype=torch.bfloat16,
    _attn_implementation="flash_attention_2",
)
```

It will use flash attention 2 for the vision tower and the perceiver, BUT it will default to sdpa for the language model.
Would it make sense to propagate the _attn_implementation to text_model too?

### Motivation

Without thinking too much, i think it would require propagating the `_attn_implementation` to the text_config so that when we initialize the text_model, it picks up that argument too

### Your contribution

NA

**Comment by zafstojano** [comment]
Just opened a PR (#30395) addressing this. I think it will need a bit more polishing, but it achieves the main goal currently.

**Comment by luohao123** [comment]
@zafstojano Hi, may I ask what's the differences between idefics2 perciever versus idefics1 perceiver?

Can you just make idefics2 perciever a standalone module rather than make it in a single modeling file? So that we can resue it in other arch?

**Comment by amyeroberts** [comment]
@VictorSanh Closing as the selected attention is correctly propagated now when creating the idefics2 model

**Comment by VictorSanh** [comment]
yes thanks!
