### ISSUE TITLE
`generate` method does not work with `use_cache=False` in `Llama-2` model with `model.config._attn_implementation = "eager"`

### ISSUE THREAD

**Issue by nurlanov-zh** [huggingface/transformers#30482]
@ArthurZucker , @gante 

The issue still persists when `model.config._attn_implementation = "eager"` is used. Currently it works because the implementation relies on `sdpa` attention implementation, which does not use `causal_mask`. 
```py
class LlamaModel(LlamaPreTrainedModel):
    ...

    def _update_causal_mask(
        self,
        attention_mask: torch.Tensor,
        input_tensor: torch.Tensor,
        cache_position: torch.Tensor,
        past_seen_tokens: int,
    ):
        ...

        if self.config._attn_implementation == "sdpa":
            # For SDPA, when possible, we will rely on its `is_causal` argument instead of its `attn_mask` argument,
            # in order to dispatch on Flash Attention 2.
            if AttentionMaskConverter._ignore_causal_mask_sdpa(
                attention_mask, inputs_embeds=input_tensor, past_key_values_length=past_seen_tokens
            ):
                return None
```

Ideally, the code should work with any attention implementation. I believe the problem is that the `cache_position` is wrong when we use `model.generate` with `use_cache=False`.

_Originally posted by @nurlanov-zh in https://github.com/huggingface/transformers/issues/30347#issuecomment-2076917488_

**Comment by ArthurZucker** [comment]
Sure!
