### ISSUE TITLE
Crash when trying to import pipeline when using TPUv2 in GoogleColab

### ISSUE THREAD

**Issue by suzukimain** [huggingface/transformers#30516]
### System Info

[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:642] File already exists in database: tsl/profiler/protobuf/trace_events.proto
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1986] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
https://symbolize.stripped_domain/r/?trace=7c1c534509fc,7c1c533fc51f&map= 
*** SIGABRT received by PID 4558 (TID 4558) on cpu 47 from PID 4558; stack trace: ***
PC: @     0x7c1c534509fc  (unknown)  pthread_kill
    @     0x7c1b6ba214f9        928  (unknown)
    @     0x7c1c533fc520  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7c1c534509fc,7c1b6ba214f8,7c1c533fc51f&map=5edeb7d86db111100e979a74159a3982:7c1b5be00000-7c1b6bc40ba0 
E0427 01:39:22.126190    4558 coredump_hook.cc:447] RAW: Remote crash data gathering hook invoked.
E0427 01:39:22.126205    4558 client.cc:272] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0427 01:39:22.126208    4558 coredump_hook.cc:542] RAW: Sending fingerprint to remote end.
E0427 01:39:22.126229    4558 coredump_hook.cc:551] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] stat failed on crash reporting socket /var/google/services/logmanagerd/remote_coredump.socket (Is the listener running?): No such file or directory
E0427 01:39:22.126235    4558 coredump_hook.cc:603] RAW: Dumping core locally.
E0427 01:39:52.041717    4558 process_state.cc:808] RAW: Raising signal 6 with default behavior

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import pipeline
```

### Expected behavior

Import successfully without crashing

**Comment by suzukimain** [comment]
I would appreciate if someone could tell me how to deal with this.

https://github.com/huggingface/transformers/assets/131413573/bb9b6436-45c8-4af0-b5e8-1cb9b062358c

**Comment by muellerzr** [comment]
Hi all, after talking with the torch-xla team tensorflow is the issue here.

You can try doing the following:

```bash
pip uninstall tensorflow
pip install tensorflow-cpu
```

**Comment by suzukimain** [comment]
It has been solved.
I appreciate your kind response during your busy time.

**Comment by jasonhis** [comment]
I uninstall tensorflow and use pytorch.  Problem solved.

```
!pip install torch torchvision torchaudio
!pip uninstall -y tensorflow
```
