### ISSUE TITLE
Question about iterable inputs for Pipeline

### ISSUE THREAD

**Issue by ww-rm** [huggingface/transformers#30517]
Hi, I'm using `Pipeline` in some memory constrained scenarios and struggling with its inputs types.

To reduce memory usage, Pipeline can specify a `batch_size` and use iterable objects as input. However, one of the current criteria for determining iterability is to check if the `inputs` is a `Generator`.

Some code snippets around [base.py#L1213](https://github.com/huggingface/transformers/blob/9fe3f585bb4ea29f209dc705d269fbe292e1128f/src/transformers/pipelines/base.py#L1213)

```python
        is_dataset = Dataset is not None and isinstance(inputs, Dataset)
        is_generator = isinstance(inputs, types.GeneratorType)
        is_list = isinstance(inputs, list)

        is_iterable = is_dataset or is_generator or is_list
```

Therefore, when I need to provide input that was originally a list in an iterable manner, I must use a generator expression instead of directly using the `iter` function. For example:

```python
inputs = ["hello world", "good job"]

# fe_pipeline is a FeatureExtractionPipeline

# works properly
fe_pipline((s for s in inputs), batch_size=32)

# raises a ValueError
fe_pipline(iter(s), batch_size=32)
```

I attempted to look at the source code and didn't find any mandatory use of generators. In Python, `Generator` is a subclass of `Iterator`. Should we consider changing the check here to `Iterator` instead of `Generator`? Or could someone explain why the current check is implemented this way?

Thank you for your attention to this matter.

**Comment by amyeroberts** [comment]
Hi, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
