### ISSUE TITLE
[Question]: Can I obtain the probability from generated text?

### ISSUE THREAD

**Issue by Gaiejj** [huggingface/transformers#30519]
### Feature request

Thanks first for your work! It is truly helpful! I wonder if there is a mechanism that can retroactively determine the token-wise probability of a model generating a given text. For example, model A generated a sentence:

``Hello, how are you?``

Assuming each word represents a token, the corresponding token-wise probability is:

``ModelA: 0.8, 0.9, 0.9, 0.8``

Can I calculate the token-wise probability of model B generating this sentence based on it? e.g.:
``Model B: 0.2, 0.3, 0.4, 0.5``

### Motivation

N/A

### Your contribution

N/A

**Comment by NielsRogge** [comment]
Hi,

This is a question that is more suited for the forum (as it's not a bug or feature request).

See the answer here: https://discuss.huggingface.co/t/announcement-generation-get-probabilities-for-generated-output/30075

**Comment by Gaiejj** [comment]
Thanks for your help!
