### ISSUE TITLE
Reconstruction statements mentioned in the paper

### ISSUE THREAD

**Issue by liumc14** [huggingface/transformers#30532]
Hello, the data set here is the squad data set, but the three domain data sets created in the paper do not seem to be reflected in the code, and it seems that the reconstruction statements in the three domain data sets disclosed in the paper are in the source and It's the same in target. Why is  this? @shamanez 
https://github.com/huggingface/transformers/blob/73014b561d5f88d728e46a57d346f516fefe3f2d/examples/research_projects/rag-end2end-retriever/utils_rag.py#L62

**Comment by amyeroberts** [comment]
Hi, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by shamanez** [comment]
@liumc14, you are correct. I open-sourced this code before my paper. Also, to keep the architecture clean, I didn't add the reconstruction statement. 

But it is pretty straightforward 

1. Mix the data QA and Recon while having an identifier. 
2. Then, during the forward computation, only use the retrieved documents as the inputs to the Generator when training data is related to the reconstruction signal.

**Comment by shamanez** [comment]
Yes, the statement should be re-constructed.  But the input to the generator should be the retrieved docs related to the statement.

**Comment by liumc14** [comment]
> Yes, the statement should be re-constructed. But the input to the generator should be the retrieved docs related to the statement.

@shamanez So the training of reconstructed statements actually involves inputting reconstructed statements, retrieving related documents, and letting the generator generate reconstructed statements based on the relevant documents? Thank you for your advice

**Comment by shamanez** [comment]
Correct
