### ISSUE TITLE
MLFlowCallback MLFLOW_RUN_ID not used

### ISSUE THREAD

**Issue by daniel-ibanez-merlyn** [huggingface/transformers#30563]
### System Info

In the [MLFlow integration documentation](https://huggingface.co/docs/transformers/en/main_classes/callback#transformers.integrations.MLflowCallback) we can read that "When MLFLOW_RUN_ID environment variable is set, start_run attempts to resume a run with the specified run ID"

However, when I set that env variable to resume training, the result is a new run instead of reattaching to the provided one.

In `MLflowCallback` class the member `_run_id` is not used to resume the experiment from it but merely to start the run:

```Python
            if self._ml_flow.active_run() is None or self._nested_run or self._run_id:
                # Some more code here ...
                self._ml_flow.start_run(run_name=args.run_name, nested=self._nested_run)
```

### Who can help?

@muellerzr @pacman100 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Set MLFlow env variable `MLFLOW_TRACKING_URI` with the URI of the remote server
2. Assign value "1" to `HF_MLFLOW_LOG_ARTIFACTS` env variable so we persist checkpoints in MLFlow
1. Launch a trainer using MLFlow by including `report_to=mlflow` in the training parameters
2. Wait till MLFlow persists a checkpoint
3. Stop training before it is finished
3. Get the run ID from the experiment run we just created
4. Set `MLFLOW_RUN_ID` env variable using the existing run ID
5. Launch a new trainer using MLFlow by including `report_to=mlflow` in the training parameters

### Expected behavior

Training should resume from the provided MLFlow run ID.
Instead, this is creating a new run.

**Comment by daniel-ibanez-merlyn** [comment]
MLFLOW_RUN_ID is used inside MLFlow

**Comment by muellerzr** [comment]
Hi @daniel-ibanez-merlyn , sorry for the delay. Would you like to try your hand at this fix? 🤗
