### ISSUE TITLE
Make fx traced model with the use of `past_key_values` pickable again?

### ISSUE THREAD

**Issue by michaelbenayoun** [huggingface/transformers#30575]
With the support of the `transformers.cache_utils.Cache` classes when doing symbolic trace (#30259), it is not possible to pickle a traced model which uses `past_key_values`, should we work to add support for that?

**Comment by LysandreJik** [comment]
cc @ArthurZucker @gante

**Comment by michaelbenayoun** [comment]
Created this issue to have the discussion but I do not know if we actually want to support that.

**Comment by gante** [comment]
@michaelbenayoun sorry, this was lost in the notification queue 😬 

I think the PT team is taking care of what you asked in this PR: #32253
