### ISSUE TITLE
AutoModal how to enable TP for extremly large models?

### ISSUE THREAD

**Issue by MonolithFoundation** [huggingface/transformers#30596]
Hi, I have 8V100s, but a single one can not fit InternVL1.5 model which has 28B parameters.

So that, I just wonder if I can fit all of them into 8 V100 with TP?

I found that Deepspeed can be used to do tensor parallel like this:

```
# create the model
if args.pre_load_checkpoint:
    model = model_class.from_pretrained(args.model_name_or_path)
else:
    model = model_class()
...

import deepspeed

# Initialize the DeepSpeed-Inference engine
ds_engine = deepspeed.init_inference(model,
                                 tensor_parallel={"tp_size": 2},
                                 dtype=torch.half,
                                 checkpoint=None if args.pre_load_checkpoint else args.checkpoint_json,
                                 replace_with_kernel_inject=True)
model = ds_engine.module
output = model('Input String')
```

I didn't succeed because of it just support built in model which can be imported, but for custom model which have to `fromPretrained` it does support.

But as I mentioned at start, my V100 will OOM when load model.

Does there any convenient way to loading hf model which is customized with tp enable ?

**Comment by amyeroberts** [comment]
Hi @MonolithFoundation, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by MonolithFoundation** [comment]
This could be treated as feature, as I didn't found anywhere has doc about this, as such it can be treated as unspported
