### ISSUE TITLE
i cannot find the code that transformers trainer model_wrapped by deepspeed , i can find the theory about  model_wrapped was wraped by DDP(Deepspeed(transformer model )) ,but i only find the code transformers model wrapped by ddp, where is the deepspeed wrapped ? thanks ^-^ 

### ISSUE THREAD

**Issue by ldh127** [huggingface/transformers#30591]
### Feature request

i cannot find the code that transformers trainer model_wrapped by deepspeed , i can find the theory about  model_wrapped was wraped by DDP(Deepspeed(transformer model )) ,but i only find the code transformers model wrapped by ddp, where is the deepspeed wrapped ? thanks ^-^ 

### Motivation

x

### Your contribution

x

**Comment by amyeroberts** [comment]
Hi @ldh127, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by amyeroberts** [comment]
Hi @ldh127, what is the problem you're having posting on the forum?

**Comment by ldh127** [comment]
last time it seems that i have no access to create the new question as a new user , but just i try it again, it success . i have create my question ,  thanks @_@
