### ISSUE TITLE
(Have PR) Speed up `BeamScorer` to make GPT-2 generation 2-3x faster

### ISSUE THREAD

**Issue by fzyzcjy** [huggingface/transformers#30647]
### Feature request

Please refer to https://github.com/huggingface/transformers/pull/21234#issuecomment-2090310005 for details (I create a new issue because I guess the reply to ancient issue will not be seen)

### Motivation

-

### Your contribution

-

**Comment by amyeroberts** [comment]
cc @gante

**Comment by gante** [comment]
Hi @fzyzcjy 👋 

The reason for not merging your suggested PR is still valid, we are currently refactoring `generate` and `beam_search` will look very different from what it is at the moment when we're done :)

**Comment by fzyzcjy** [comment]
I see. May I know when will the refactor be done? (seems many months have passed...) and looking forward to the new code!

**Comment by gante** [comment]
@fzyzcjy You can see the tracker [here](https://github.com/huggingface/transformers/issues/28981) 🤗
