### ISSUE TITLE
Add Wav2Vec2BertProcessorWithLM

### ISSUE THREAD

**Issue by FredHaa** [huggingface/transformers#30671]
### Feature request

Wav2Vec2-Bert was open sourced and integrated with Transformers in the end of last year. However, it is missing an easy integration with pyctcdecode similar to Wav2Vec2ProcessorWithLM. This should be quite trivial to implement, since Wav2Vec2Processor is very similar to Wav2Vec2BertProcessor, the only difference being that they use different feature extractors.

### Motivation

Having a Wav2Vec2BertProcessorWithLM class would make it possible to use Wav2Vec2-Bert with a kenlm model in a Transformers ASR pipeline.

### Your contribution

I can submit a PR.

**Comment by LysandreJik** [comment]
cc @sanchit-gandhi @ylacombe

**Comment by ylacombe** [comment]
Hey @FredHaa, #28706 should fix this, I'm reopening it! Note that you would have to use `Wav2Vec2ProcessorWithLM` and not `Wav2Vec2BertProcessorWithLM`!

**Comment by ylacombe** [comment]
#28706 has been merged, I'm closing the issue for now, feel free to ask questions
