### ISSUE TITLE
Problem with using pretrained BertTokenizer for Korean

### ISSUE THREAD

**Issue by alirezamshi** [huggingface/transformers#3068]
I have a corpus that contains Korean sentences. Here is the output of a berttokenizer for a token:

`tok = BertTokenizer.from_pretrained('bert-base-multilingual-uncased')`
`tok.convert_tokens_to_ids(tok.tokenize('잘해놨습니다'))`
`[44628, 14840, 97071, 97089, 97104, 13212, 79427]`
`tok = BertTokenizer.from_pretrained('bert-base-multilingual-cased')`
`tok.convert_tokens_to_ids(tok.tokenize('잘해놨습니다'))`
`[100]`
transformers version: 2.4.1

Totally, 'cased' tokenizer produces more 'unknown' token than 'uncased' one for Korean. 
Is it a bug?

**Comment by BramVanroy** [comment]
Intuitively, I would say that this might not be a bug but a limitation of the size of the vocabulary. In the cased version, all data that the tokenizer is 'trained' on is cased, meaning that there are tokens in the vocabulary that only differs by case (e.g. `Be` and `be`). As a consequence, this may cause the vocabulary to be a lot bigger, leaving less room for other tokens. 

That is just my intuition and not based on any research.
