### ISSUE TITLE
Construct a Marian tokenizer. Based on huggingface tokenizers

### ISSUE THREAD

**Issue by RRaphaell** [huggingface/transformers#30700]
I have a Hugging Face tokenizer with three files: tokenizer.json, tokenizer_config.json, and vocab.txt. However, according to the documentation, the Marian tokenizer requires files in the SentencePiece format (.model and .vocab files). Is there a way to construct a Marian tokenizer without these specific file formats?

I have already tried converting the tokenizer into a .model file and then constructing the Marian tokenizer, but it raised new issues. Are there any alternative approaches or workarounds to use the existing tokenizer files with the Marian tokenizer?

**Comment by amyeroberts** [comment]
Hi @RRaphaell, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by RRaphaell** [comment]
got it, closing the issue
