### ISSUE TITLE
Add static cache support for Whisper

### ISSUE THREAD

**Issue by mobicham** [huggingface/transformers#30707]
### Feature request

Would be great to have static cache support for Whisper to make it faster with `torch.compile`. Currently, the `generate()` function doesn't support `cache_implementation="static"` for Whisper. 

### Motivation

Static cache with torch.compile can make generation much faster.

### Your contribution

 Static cache is already supported for LLMs and we see great speed-up.

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi

**Comment by huseinzol05** [comment]
Let me try, I think I can make it, just need to patch https://github.com/huggingface/transformers/blob/main/src/transformers/models/whisper/modeling_whisper.py#L313 like llama model and pass `cache_position` should be ok

**Comment by mobicham** [comment]
@huseinzol05 great, thanks ! I think you also need to make sure the model supports initializing the static cache via `_setup_cache`:
```Python
from transformers import StaticCache
model._setup_cache(StaticCache, batch_size, max_cache_len=max_cache_length)
```

**Comment by huseinzol05** [comment]
aw man, so lazy to follow the standard, will try

**Comment by huseinzol05** [comment]
I got hit by https://github.com/pytorch/pytorch/issues/123592 at https://github.com/huggingface/transformers/blob/main/src/transformers/models/whisper/modeling_whisper.py#L230, but the static cache is already working without torch compile from my local

**Comment by mobicham** [comment]
Maybe you can use `arange` instead like here: https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L964-L966

**Comment by huseinzol05** [comment]
not possible, anything dynamic not possible, feed `position_ids` solved the problem, just like `cache_position`, i will push the initial later, so you can verify, the speedz is good

**Comment by mobicham** [comment]
Great :+1: ! But that `arange` works well in Llama

**Comment by huseinzol05** [comment]
https://github.com/huggingface/transformers/pull/30760
