### ISSUE TITLE
 Chinese BERT model can be used represented by words instead of character

### ISSUE THREAD

**Issue by WenTingTseng** [huggingface/transformers#3072]
# ❓ Questions & Help

I want to ask about the Chinese BERT model can be used represented by words instead of character?
Because when I do BERT visual for Chinese can only see its attention from character to character.
I want to see attention from words to words. Can I change this?
Thanks a lot for your help

**Comment by BramVanroy** [comment]
I am not sure which Chinese BERT you are referring to, but the original multilingual BERT has trained Chinese, Japanese, and Korean on the character-level. From their [README](https://github.com/google-research/bert/blob/master/multilingual.md):

> Because Chinese (and Japanese Kanji and Korean Hanja) does not have whitespace characters, we add spaces around every character in the CJK Unicode range before applying WordPiece. This means that Chinese is effectively character-tokenized. Note that the CJK Unicode block only includes Chinese-origin characters and does not include Hangul Korean or Katakana/Hiragana Japanese, which are tokenized with whitespace+WordPiece like all other languages.

**Comment by WenTingTseng** [comment]
OK, Thanks for your help 
But I mean I want Chinese BERT for word-level not for character-level.

**Comment by BramVanroy** [comment]
Yes, I understand that, and as I said the default multilingual BERT does **not** support that. You'll have to find another implementation, perhaps https://arxiv.org/abs/1906.08101
