### ISSUE TITLE
error when convert llama1 ckpts to hf formath

### ISSUE THREAD

**Issue by a157801** [huggingface/transformers#30723]
### System Info

- `transformers` version: 4.41.0.dev0
- Platform: Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.12
- Huggingface_hub version: 0.21.4
- Safetensors version: 0.4.2
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

`python transformers/models/llama/convert_llama_weights_to_hf.py --input_dir path-to-llama1-7b-source --model_size 7B --output_dir path-to-llama1-7b-target --llama_version 1`

### Expected behavior

error: RuntimeError: shape '[32, 2, 2, 4096]' is invalid for input of size 16777216
In line https://github.com/huggingface/transformers/blob/f26e4073707189c93915227779a4f6ea3c40d43b/src/transformers/models/llama/convert_llama_weights_to_hf.py#L181
the k_proj in llama1 7b is 4096 by 4096, but the dim1 here is 128.
Maybe this is a bug when converting llama1 ckpt

**Comment by amyeroberts** [comment]
cc @ArthurZucker

**Comment by ZHEGG** [comment]
Same question!

**Comment by ArthurZucker** [comment]
Haha that's annoying, we might have broken conversion for llama1 when adding llama3. 
Could you test on `transformers==4.38` or `4.39`?

**Comment by RPC2** [comment]
I encountered the same error when I was converting the Llama 2 model. Using ``transformers==4.38`` solved this problem.

**Comment by ArthurZucker** [comment]
Yep, it's not expected. I'll open a PR to fix conversion on all models 🤗

**Comment by yoryis** [comment]
Any update on this issue, please.

**Comment by pep1t0** [comment]
The problem is not solved by changing the transformer version. I'm trying to convert llama-2 and it gives me the same error

**Comment by ArthurZucker** [comment]
Sorry about that, I'll do this today!

**Comment by ArthurZucker** [comment]
Hey! I am downloading everything now to fix it ! 🤗  there is #30734 as well

**Comment by ArthurZucker** [comment]
Sorry for the delay!
