### ISSUE TITLE
Disable Progress Bar?

### ISSUE THREAD

**Issue by haok1402** [huggingface/transformers#30733]
Is there a way to disable progress bar in `transformers`?

When I load from pretrained, like the following, the progress bar (i.e. tqdm) can be quite annoying to some applications.

```python
from transformers import AutoTokenizer, AutoModel
from transformers.models.llama.tokenization_llama_fast import LlamaTokenizerFast
from transformers.models.llama.modeling_llama import LlamaModel

NAME = "selfrag/selfrag_llama2_7b"
ragTokenizer: LlamaTokenizerFast = AutoTokenizer.from_pretrained(NAME)
ragPretrined: LlamaModel = AutoModel.from_pretrained(NAME)
```

Related discussion from 4 year ago, which set `tqdm.tqdm = nop` no longer works
- https://github.com/huggingface/transformers/issues/3050

It would be ideal to have a function like `disable_progress_bar`, as provided by `datasets`

```python
import datasets 
datasets.disable_progress_bar()
```

Thanks!

**Comment by haok1402** [comment]
My bad, this utility is documented at https://huggingface.co/docs/transformers/v4.40.2/en/main_classes/logging#transformers.utils.logging.disable_progress_bar

You can use it with,

```
from transformers.utils.logging import disable_progress_bar
disable_progress_bar()
```

**Comment by weathon** [comment]
Is there a way to force it to use ASCII based progress bar and not the ipython widget one?

**Comment by vadimkantorov** [comment]
Similar question, in logs/tee tqdm progress bar look bad :(

Is there a way to force the non-repainting version? Or diable tqdm completely?

This is also useful when there are a bunch of parallel processes / ranks writing tqdm progress-bars to the same terminal output

**Comment by weathon** [comment]
Is there ways to disable IPython progress bar in the notebook
