### ISSUE TITLE
Getting Loss : nan while fine-tuning blip2-opt-2.7b

### ISSUE THREAD

**Issue by tan7vir** [huggingface/transformers#30789]
I am using this code to fine-tuning model but get nan loss value and the model give strange output. 

**My Fine-tuning code.**
![image](https://github.com/huggingface/transformers/assets/117768126/d1020d75-6f51-4241-abd9-0d927aee3b56)
And getting output like this:
![image](https://github.com/huggingface/transformers/assets/117768126/0c8d6ad7-5f03-425d-b775-3f6ecb0e8c1c)

**Comment by amyeroberts** [comment]
Hi @tan7vir, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by tan7vir** [comment]
@amyeroberts  Thank You.
