### ISSUE TITLE
ValueError: Error 503: {'error': 'Service Unavailable'}

### ISSUE THREAD

**Issue by jeremierostan** [huggingface/transformers#30816]
### System Info

I am using this colab: https://colab.research.google.com/drive/1c7MHD-T1forUPGcC_jlwsIptOzpG3hSj
Which is linked here: https://huggingface.co/docs/transformers/en/transformers_agents

### Who can help?

@stevhliu

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://colab.research.google.com/drive/1c7MHD-T1forUPGcC_jlwsIptOzpG3hSj

ValueError                                Traceback (most recent call last)
[<ipython-input-19-efe57595a5cd>](https://localhost:8080/#) in <cell line: 1>()
----> 1 boat = agent.run("Generate an image of a boat")
      2 boat

1 frames
/usr/local/lib/python3.10/dist-packages/transformers/tools/agents.py in generate_one(self, prompt, stop)

ValueError: Error 503: {'error': 'Service Unavailable'}

### Expected behavior

boat = agent.run("Generate an image of a boat")

**Comment by amyeroberts** [comment]
cc @aymeric-roucher
