### ISSUE TITLE
Cannot import name 'WhisperForAudioClassification -Already installed transformers==4.40.2

### ISSUE THREAD

**Issue by manjualoshious** [huggingface/transformers#30834]
ImportError: cannot import name 'WhisperForAudioClassification' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

**from transformers import  WhisperForAudioClassification**

I have installed  **transformers==4.40.2**

Issue still exists.

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi

**Comment by manjualoshious** [comment]
> cc @sanchit-gandhi

Please help
ImportError: cannot import name 'WhisperForAudioClassification' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/init.py)

from transformers import WhisperForAudioClassification

I have installed transformers==4.40.2

Issue still exists.

**Comment by manjualoshious** [comment]
The issue has not been  resolved yet
Pls help

**Comment by amyeroberts** [comment]
Hi @manjualoshious, please be patient refrain sending many comments on an issue and spamming people with notifications. We receive many pull requests and issues per day and they will be addressed in due time. Leaving a comment that something hasn't been addressed within an hour is not sustainable behaviour: we would be unable to meaningfully address any issues if everyone did this.

The best way to get a quick response is to follow the issue template and provide all of the information provided, which I've [already asked for you to do in another issue](https://github.com/huggingface/transformers/issues/30831#issuecomment-2112691307). A quick response is on the order of hours / days.

**Comment by sanchit-gandhi** [comment]
Hey @manjualoshious - could you please provide the full traceback you're getting why you try this? It would also be great to see the output of `transformers-cli env`, so we can cross-check you have the appropriate packages installed. For reference, mine is:
```
- `transformers` version: 4.41.0.dev0
- Platform: macOS-14.4.1-arm64-arm-64bit
- Python version: 3.11.6
- Huggingface_hub version: 0.23.0
- Safetensors version: 0.4.2
- Accelerate version: 0.27.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.2.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.8.1 (cpu)
- Jax version: 0.4.24
- JaxLib version: 0.4.24
```

And I am successfully able to import the class:
```python
from transformers import WhisperForAudioClassification
```
