### ISSUE TITLE
ImportError: cannot import name 'PaliGemmaForConditionalGeneration' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

### ISSUE THREAD

**Issue by KaifAhmad1** [huggingface/transformers#30848]
### System Info

transformers Version: 4.40.2
cuda 12.1 
os Windows 11 x64 
pip 24.0 
python 3.10.10 

### Who can help?

Hi, @amyeroberts, I'm encountering an error. Could you help me with it?

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

``` Python 
from tqdm import tqdm
import bitsandbytes as bnb
import torch
import torch.nn as nn
from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model
from trl import SFTTrainer
from transformers import (
    PaliGemmaForConditionalGeneration,
    AutoTokenizer,
    TrainingArguments,
    BitsAndBytesConfig,
    pipeline,
    logging
)
from sklearn.model_selection import train_test_split
from datasets import Dataset
```

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-15-11114d78412d> in <cell line: 7>()
      5 from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model
      6 from trl import SFTTrainer
----> 7 from transformers import (
      8     PaliGemmaForConditionalGeneration,
      9     AutoTokenizer,

ImportError: cannot import name 'PaliGemmaForConditionalGeneration' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

```

### Expected behavior

It will load the model without raising any issues!

**Comment by amyeroberts** [comment]
Hi @KaifAhmad1, PaliGemma has been released on the development branch, but isn't part of the v4.40.2 release. 

To work from the development branch and get all the most recent (but not guaranteed stable) features, you can install from source: `pip install git+https://github.com/huggingface/transformers`. 

We're planning on having a release this week, so you should be able to install from pypi as part of a stable release soon

**Comment by KaifAhmad1** [comment]
Thanks @amyeroberts
