### ISSUE TITLE
Mamba: `use_cache` is not passed through in `prepare_inputs_for_generation` 

### ISSUE THREAD

**Issue by uwu-420** [huggingface/transformers#30849]
Hi :)

I think that [use_cache](https://huggingface.co/docs/transformers/main/en/model_doc/mamba#transformers.MambaForCausalLM.forward.use_cache) is supposed to be passed through here as well:
https://github.com/huggingface/transformers/blob/9fd606dbdb392e76e66a4e4e852948ebf814dbb6/src/transformers/models/mamba/modeling_mamba.py#L634-L647

I noticed when I wanted to get the cache when using `model.generate`, but it was not there although I set `use_cache=True`.

Edit: Just saw that `GenerateDecoderOnlyOutput` would have to be adjusted as well. It would need to contain `cache_params` similarly to `past_key_values`. I don't know if it's okay for you to bloat that even more.
https://github.com/huggingface/transformers/blob/9fd606dbdb392e76e66a4e4e852948ebf814dbb6/src/transformers/generation/utils.py#L2244-L2251

Cheers and thanks for the great work!

**Comment by amyeroberts** [comment]
cc @gante

**Comment by gante** [comment]
@zucchini-nlp could you have a look at this issue? 🤗
