### ISSUE TITLE
Enabling device_map="auto" for Video-LLaVA

### ISSUE THREAD

**Issue by darshana1406** [huggingface/transformers#30858]
### Feature request

To load model across multiple devices, _no_split_modules has to be defined in the model's pretrained model class e.g. like [here](https://github.com/huggingface/transformers/blob/v4.40.2/src/transformers/models/llava/modeling_llava.py#L235) for LLaVa.

### Motivation

To enable inference of multiple lower end devices and avoid OOM.

### Your contribution

@zucchini-nlp
I could try to work on this but I'm not sure about what modules should be included here.

**Comment by zucchini-nlp** [comment]
Thank for opening an issue! Sure, adding a `_no_split_modules` in the same way as it is done for other LLaVa models will do the work. See [here](https://github.com/huggingface/transformers/blob/ba56ed0869eb4bbeb1c04af7f62a04350150e8d4/src/transformers/models/llava_next/modeling_llava_next.py#L190) for an example

Let me know if you need any guidance 😄
