### ISSUE TITLE
Disabling Eager Mode Prevents Loading Pre-Trained BERT

### ISSUE THREAD

**Issue by msandrewhoang03** [huggingface/transformers#3086]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):
**BERT**
Language I am using the model on (English, Chinese ...):
**English**

## To reproduce

1. Disable Tensorflow eager mode `tf.compat.v1.disable_v2_behavior()`
2. Create a pretrained BERT instance `model = transformers.TFBertModel.from_pretrained("bert-base-uncased")`

## Expected behavior

`model` contains a pre-trained BERT model

## Environment info

     
- `transformers` version:
- Platform: Windows-10-10.0.18362-SP0
- Python version: 3.7.6
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.0.0 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by datalee** [comment]
TFBertModel can auto use gpu?  i find model(np.array(input_ids)) is slow,cost 100+ms
In [14]: %timeit model_outputs = model(np.array(input_ids))
133 ms ± 3.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [15]: %time model_outputs = model(np.array(input_ids))
CPU times: user 330 ms, sys: 14.4 ms, total: 344 ms
Wall time: 158 ms

**Comment by itsmemala** [comment]
I have a similar issue. Did you manage to find fix for this @msandrewhoang03 ?
