### ISSUE TITLE
Error when runnig run_tf_ner.py

### ISSUE THREAD

**Issue by mrm8488** [huggingface/transformers#3087]
# 🐛 Bug

## Information
```python
!python3 /content/transformers/examples/ner/run_tf_ner.py --data_dir /content/ner_dataset \
--model_type bert \
--labels /content/labels.txt \
--model_name_or_path dccuchile/bert-base-spanish-wwm-cased \
--output_dir model_output \
--max_seq_length 256 \
--num_train_epochs 5\
--per_gpu_train_batch_size 42 \
--save_steps 2000\
--do_train \
--do_eval

Traceback (most recent call last):
  File "/content/transformers/examples/ner/run_tf_ner.py", line 14, in <module>
    from transformers import (
ImportError: cannot import name 'GradientAccumulator'
```

## Transformer version ```transformers==2.5.1```

**Comment by LysandreJik** [comment]
You should not have any issues with this as `GradientAccumulator` is correctly imported in the __init__.py file:

https://github.com/huggingface/transformers/blob/298bed16a841fae3608d334441ccae4d9043611f/src/transformers/__init__.py#L426-L427

Is `transformers` correctly installed in your pip environment, or did you simply clone the repository?

**Comment by mrm8488** [comment]
Ok. Thank you. I cannot check it now because Colab PRO accounts are having problems. I will let you know ASAP.

**Comment by over-shine** [comment]
I met analogous problem，but it was solved after rebooting computer. And another issue is it can not find the installed module，this issue can be solved by reinstall the module that can not be found.

**Comment by mrm8488** [comment]
In my case I was not using tf 2.x
