### ISSUE TITLE
GGUF interaction with Transformers using AutoModel Class

### ISSUE THREAD

**Issue by Abdullah-kwl** [huggingface/transformers#30889]
### Feature request

https://huggingface.co/docs/transformers/main/en/gguf
in above documentation it shows that it loads the gguf model and provided the simple example

from transformers import AutoTokenizer, AutoModelForCausalLM

model_id = "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"
filename = "tinyllama-1.1b-chat-v1.0.Q6_K.gguf"

model = AutoModelForCausalLM.from_pretrained(model_id, gguf_file=filename)
tokenizer = AutoTokenizer.from_pretrained(model_id, gguf_file=filename)

but when I run the code it shows the error :
OSError:  TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
and some time show your transformer may be not updated 

even after updating transformer it shows the same error not loading  gguf model , add support to load gguf model

### Motivation

it will solve to load gguf model with out the help of other library such as llama.cpp and ollama

### Your contribution

I do not have a complete implementation in mind, but I suggest to start with previous method which mention in https://huggingface.co/docs/transformers/main/en/gguf

**Comment by younesbelkada** [comment]
Hi @Abdullah-kwl 
Thanks for the issue ! Can you make sure you have the latest transformers installed ? `pip install -U transformers`

**Comment by Abdullah-kwl** [comment]
yes, I am using an updated transformer library.
in collab I am using the same command to download transformers.
pip install -U transformers

**Comment by Devy99** [comment]
Hello, I have a general question about using GGUF models with AutoModel. 

Is there any difference in the implementation if compared to the [ctransformers](https://github.com/marella/ctransformers) library?
Until now, I used GGUF models in Python with ctransformers, and it is really fast in generating responses. Using GGUF from AutoModel, instead, significantly slow down the inference time. Any clue about this? I am not sure if this transformers compatibility with GGUF models is intended for the the same usage as for ctransformers or llama.cpp or I am doing something wrong. 
Also, is there any way to set up "context_length" and "gpu_layers" offloading from AutoTokenizer?

Thanks!

**Comment by amyeroberts** [comment]
cc @younesbelkada

**Comment by amyeroberts** [comment]
Gentle ping @SunMarc

**Comment by SunMarc** [comment]
Hi @Abdullah-kwl, try passing device_map = "auto", so that we make sure to load the model on all available devices ! LMK if this fixes your issue.

**Comment by SunMarc** [comment]
> Hello, I have a general question about using GGUF models with AutoModel.
> 
> Is there any difference in the implementation if compared to the [ctransformers](https://github.com/marella/ctransformers) library?
> Until now, I used GGUF models in Python with ctransformers, and it is really fast in generating responses. Using GGUF from AutoModel, instead, significantly slow down the inference time. Any clue about this? I am not sure if this transformers compatibility with GGUF models is intended for the the same usage as for ctransformers or llama.cpp or I am doing something wrong.
> Also, is there any way to set up "context_length" and "gpu_layers" offloading from AutoTokenizer?
> 
> Thanks!

Hi @Devy99, the goal of the gguf implementation in transformers is to allow users to finetune their quantized model, then convert it back to gguf so that it can run on llama.cpp.

**Comment by Devy99** [comment]
Clear, thank you! 😁

**Comment by SunMarc** [comment]
Closing it since the issue has been fixed !
