### ISSUE TITLE
add_generation_prompt=False in Tokenizer.apply_chat_template has no effect

### ISSUE THREAD

**Issue by AndreiMuresanu** [huggingface/transformers#30893]
### System Info

Hi, I am trying to apply a chat template to an input without the generation prompt. However, setting add_generation_prompt=False appears to have no effect.

### Who can help?

@ArthurZucker @Rocketknight1

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Minimal reproducible example:

```Python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")

chat = [
		{"role": "assistant", "content": "Hello, how are you?"},
	]
formatted_chat = tokenizer.apply_chat_template(chats, add_generation_prompt=False, tokenize=False)
print(formatted_chat)
```

transformers==4.41.0

### Expected behavior

Observed Output:

```
<|begin_of_text|><|start_header_id|>assistant<|end_header_id|>

Hello, how are you?<|eot_id|><|start_header_id|>assistant<|end_header_id|>


```

Expected Output:

```
<|begin_of_text|><|start_header_id|>assistant<|end_header_id|>

Hello, how are you?<|eot_id|>
```

**Comment by Rocketknight1** [comment]
Hi @AndreiMuresanu, I just tried to reproduce this and `add_generation_prompt=False` worked correctly for me. Can you retry your code, and make sure you're updated to the latest version of `transformers`?

**Comment by Rocketknight1** [comment]
Can you try installing `transformers` from `main` with `pip install git+https://github.com/huggingface/transformers.git`? I can't reproduce this issue at all, and I'm curious if it's caused by an old cached version of the model, or some recent change, or something.

**Comment by iseesaw** [comment]
same problem

**Comment by iseesaw** [comment]
> same problem

Solved. Because I used the initial chat template, which was later updated.

See Fix chat template to add generation prompt only if the option is selected ([#9](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/discussions/9))

**Comment by Rocketknight1** [comment]
@iseesaw thanks for pointing that one out! It seems like this was an issue with the model's chat template, which has since been resolved, and the issue should be resolved if people just redownload the tokenizer. Going to close this issue now, since it's not a bug in `transformers` itself.

**Comment by Hafach** [comment]
im sick of this : Error: Kwargs ['add_generation_prompt'] are not supported by `MistralCommonTokenizer.apply_chat_template`
trying to make live streaming with the TTS model voxtral-mini-3b and serving it via vllm, but vllm require transformers version 4.49.x or something like that while here you are saying to solve it it should be ==4.41 , does anyone have idea what can i do? im new here
