### ISSUE TITLE
The implementation of ROPE seems a little off for k

### ISSUE THREAD

**Issue by wzhcz8902** [huggingface/transformers#30900]
### System Info

main branch

### Who can help?

@ArthurZucker @younesbelkada @bojone

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/blob/481a95781404e48b1c80940be17e8279dec82fe8/src/transformers/models/llama/modeling_llama.py#L160-L184

The rotary embedding for q and k is done exactly the same, but should they be different so that when they do multiply together, we end up with a relative position as the difference between them. The current implementation results in a relative position as a sum of the positions of q and k, so I think we should put a negative sign in front of k's angle, thus a correct implementation for k may look like
`k_embed = (k * cos) + (rotate_half(k) * (-sin))`

### Expected behavior

The angle between q and k should differ by a sign

**Comment by ArthurZucker** [comment]
Hey, inviting you to read https://blog.eleuther.ai/rotary-embeddings/ on which the current implementation of ROPE is based. 

A quick test you can do is directly change this and check the outputs of the Llama 3 or 2 model 😉
