### ISSUE TITLE
Add post_process_depth_estimation to image processors

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#30917]
### Feature request

The image processors of depth estimation models could benefit from a `post_process_depth_estimation` method, similar to the `post_process_object_detection`,  `post_process_semantic_segmentation` methods.

This includes:

- [ ] DPT
- [ ] Depth Anything (and v2)
- [ ] ZoeDepth (soon: #30136) => this one requires some special postprocessing logic as shown in [this notebook](https://colab.research.google.com/drive/1lrH4IN3ipR3jstpmV-nAzsxoRRFM91mh#scrollTo=_orJsZFU7HG3)

### Motivation

People now need to manually interpolate the predicted depth to the original size of the image as seen [here](https://huggingface.co/docs/transformers/model_doc/dpt#transformers.DPTForDepthEstimation.forward.example).

The interpolation could be replaced by a simple `image_processor.post_process_depth_estimation` method which postprocesses the predicted depth and interpolates it to the original image size.

### Your contribution

I could work on this, but would be great if someone else can take this up.

**Comment by the-neural-networker** [comment]
I can take this up!

**Comment by ms42402** [comment]
Hi, if no one is working on this issue, I can take this!

**Comment by amyeroberts** [comment]
@ms42402 there's no active PRs, so feel free to tackle this if you'd like!

**Comment by anirudh2781998** [comment]
hey anybody working on this? i would like to try and solve this issue

**Comment by amyeroberts** [comment]
@anirudh2781998 As above, if there isn't an active PR open, then anyone is free to work on any issue/feature request
