### ISSUE TITLE
LLama3-70b LoRa results in OOM with torchrun but succeeds with python3 command

### ISSUE THREAD

**Issue by premmotgi** [huggingface/transformers#30923]
### System Info

I am running a LoRa using databricks-dolly-15k dataset on llama3-70b model using LoRa technique. 

Number of gpus: 8
GPU type: AMD MI series

Training results into OOM whereas if I just use python3 with device_map=auto training runs all fine.

transformers version: 
transformers            4.38.2

Is there any configuration related to torchrun that I need to explicitly setup?

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run the training using the torchrun on multiple gpus on single node using llama3-70b model

### Expected behavior

70b Training should run fine with

torchrun configs... <file>.py

**Comment by amyeroberts** [comment]
cc @younesbelkada

**Comment by younesbelkada** [comment]
Hi @premmotgi 
What is the VRAM of your GPUs?

**Comment by premmotgi** [comment]
> Hi @premmotgi What is the VRAM of your GPUs?

@younesbelkada its 192G per GPU
