### ISSUE TITLE
ċ in gpt2

### ISSUE THREAD

**Issue by weiguowilliam** [huggingface/transformers#3092]
There's a 'ċ' in gpt2.

```
vocab = list(tokenizer_gpt2.encoder.keys())
vocab[198]
```
output: ċ

Based on some examples, I guess it means "with_break". But I can't find this parameter in gpt2 tokenizer document. Can anyone tell me the meaning? thank you.

**Comment by LysandreJik** [comment]
The proper way to decode a value is using the `decode` method:

```py
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

tokenizer.decode([198])  # '\n'
```

Some byte indices are shifted in the GPT-2 vocabulary, especially the control characters and characters that resemble whitespace. This is an example, and you can see the method that does it in `~transformers.tokenization_gpt2.bytes_to_unicode`.
