### ISSUE TITLE
Libraries import missing, unable to load image for inference and not able to load pipeline with the trained model

### ISSUE THREAD

**Issue by dejokz** [huggingface/transformers#30927]
### System Info

Running in google colab 
- `transformers` version: 4.40.2
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.23.0
- Safetensors version: 0.4.3
- Accelerate version: 0.30.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- Tensorflow version (GPU?): 2.15.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.3 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: not sure

### Who can help?

@stevhliu 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

copying the latest github notebook and running in google colab

### Expected behavior

To run without any import errors, and to train without any errors, and load my trained model without any errors

**Comment by dejokz** [comment]
https://colab.research.google.com/github/huggingface/notebooks/blob/main/transformers_doc/en/pytorch/semantic_segmentation.ipynb

**Comment by RUFFY-369** [comment]
Hi @dejokz, I checked the provided colab notebook and I got the same error and I think that even after running the suggested install of `pip install transformers[torch]` and `pip install accelerate -U` in the error traceback you aren't able to resolve the issue, right?

So, for fixing that just restart the colab session and after that without rerunning the `!pip install` code cells just  run all the rest of the other code cells back 'cause Colab has a script that appends metadata of pip-installed packages to a list-like object during runtime and imports only the search function from the top of this list so, we need to restart the session after `!pip install`

Cheers!
