### ISSUE TITLE
Off-by-one error in strided perplexity calculation

### ISSUE THREAD

**Issue by bauwenst** [huggingface/transformers#30975]
The computation of perplexity [in the docs](https://huggingface.co/docs/transformers/perplexity) seems to be incorrect. When passing `input_ids` to a causal LM for predicting them, what happens internally (as suggested in the code snippet) is that the model shifts the input IDs to the left by 1 so that the label of the current token becomes the ID of the next token. The last input is hence cut off because there is no label for it.

That means that when you take a window of tokens to predict, you do not do a prediction for the last token and you should start your next window on that token. Yet, in the docs, you start the next window on the token *after* the previous window:

https://github.com/huggingface/transformers/blob/a25f7d3c12975fe21eab437dda7363e9024de7c0/docs/source/en/perplexity.md?plain=1#L129

It should be that `-1`. The implementation [here](https://github.com/bauwenst/LaMoTO/blob/b7a7bc0f02e6b0cff6fa0bdb5dc64787acd52c0e/src/lamoto/measuring/ppl.py#L49-L86) is clearer to read and incorporates this bugfix.

**Comment by amyeroberts** [comment]
cc @ArthurZucker
