### ISSUE TITLE
RuntimeError: unique_by_key: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by HackXieHao** [huggingface/transformers#30976]
I use run_mlm.py for continuous pre-training, the Settings are as follows:
`CUDA_VISIBLE_DEVICES=0 python run_mlm.py \
    --model_name_or_path intfloat/multilingual-e5-small \
    --train_file data/train.txt \
    --validation_file data/val.txt \
    --max_seq_length 256 \
    --per_device_train_batch_size 64 \
    --per_device_eval_batch_size 64 \
    --warmup_steps 1000 \
    --do_train \
    --do_eval \
    --line_by_line \
    --num_train_epochs 20 \
    --save_total_limit 5 \
    --evaluation_strategy steps \
    --eval_steps 2000 \
    --save_steps 20000 \
    --output_dir text_emb_train/output/models/e5_pt_20240522 \
    --logging_steps 500 \
    --logging_dir text_emb_train/output/logs/e5_pt_20240522`

Transformers version: 4.36.1

I encountered the error:  
![error](https://github.com/huggingface/transformers/assets/28504021/8d241f7f-b41b-4dab-923c-5ff9682d393d)

And the GPU memory change is abnormal:
![gpu_memerory](https://github.com/huggingface/transformers/assets/28504021/7aa35eea-4fc9-45db-aa68-16e87a92461a)

Can anyone help to solve this problem? Thank you ！

**Comment by amyeroberts** [comment]
cc @ArthurZucker @younesbelkada

**Comment by ArthurZucker** [comment]
Hey! Could you try with a more recent version of `transformers`? 🤗
