### ISSUE TITLE
Missing "config.json" when loading Llama-2-7b-chat-hf

### ISSUE THREAD

**Issue by stefanomezza** [huggingface/transformers#31001]
### System Info

Google Colab T4 GPU

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
```
hf_token = "<<token>>"  #(real token censored, but I have it in my local version )
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf", trust_remote_code=True, token=hf_token)
```
This gives the following error:
```
OSError: meta-llama/Llama-2-7b-chat-hf does not appear to have a file named config.json. Checkout 'https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/tree/None' for available files.
```

**Comment by amyeroberts** [comment]
Hi @stefanomezza, thanks for raising an issue! 

It shouldn't be necessary to pass in `trust_remote_code=True` when calling `AutoTokenizer`. All of the code the llama model checkpoint uses is defined in transformers. 

Which version of transformers are you using? I'm able to run the following without issue on `main`: 

```py
In [1]: from transformers import AutoTokenizer

In [2]: tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf
   ...: ")
```

I was logged into HF in my python session, you may still need to pass in your hf token

I can also run when passing in `trust_remote_code`:

```py
In [3]: tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf
   ...: ", trust_remote_code=True)
```

cc @ArthurZucker

**Comment by stefanomezza** [comment]
Dear Amy,
Thank you for your prompt response. 

I double checked and the reason why I was getting that issue is that I had an empty folder called `meta-llama/Llama-2-7b-chat-hf` which was created in an except block by mistake 😅 this is what happens when you program after bedtime hahah. 

Thank you for your support, I guess I can close this one!
