### ISSUE TITLE
Is there a source code installation method available? For example: from Test_transformers import AutoModelForCausalLM, AutoTokenizer 

### ISSUE THREAD

**Issue by gg22mm** [huggingface/transformers#31009]
### Feature request

Is there a source code installation method available? For example: from Test_transformers import AutoModelForCausalLM, AutoTokenizer 
I see that the models are now written in the huggingface and packaged and called through: import transformers. If you want to debug, how do you debug it? 
If you want to modify the code or other operations inside, it's not too difficult~~

### Motivation

有没有源码方式安装？ 比如： from Test_transformers import AutoModelForCausalLM, AutoTokenizer 
﻿ 
我看现在模型都写在huggingface中，通过： import transformers 打包调用，如果想调试怎么调试？ 
如果想修改一下里面的代码 或是 其它一些操作 那不太难了 ！~~

### Your contribution

no

**Comment by amyeroberts** [comment]
Hi @gg22mm, thanks for raising an issue! 

You can install from source using this command: `pip install git+https://github.com/huggingface/transformers`. This will install the development version of transformers i.e. with the most recent commits on `main`.

I'm not sure what you mean "packaged and called through: import transformers". `import foo from bar` is just the module structure defined in the library through e.g. folders, imports and `__init__.py` files. You can see all of the code here: https://github.com/huggingface/transformers

If you want to modify the code, you can [make a fork of the library](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo)

**Comment by gg22mm** [comment]
Thank you~~

I think: One of the dumbest ways is to reinstall the library every time you make changes~:  
pip install git+ https://github.com/my_transformers 
------------------------------------ 
我想：有一种最笨的办法就是每改一次重新安装一下库 ： 
pip install git+https://github.com/my_transformers

**Comment by amyeroberts** [comment]
@gg22mm You asked about installing from source, which I gave you the command to do.

If you want to use the installed library and include any local changes, you can clone and install the library as an editable using `pip install -e .`, in which case you work from the local version and the install isn't repeated. In this case, all you need to do is fetch upstream changes using git, there is no need to re-install.

**Comment by gg22mm** [comment]
That's really great. Thank you~
