### ISSUE TITLE
Models with Phi3Config fail due to missing attention_bias

### ISSUE THREAD

**Issue by manikawnth** [huggingface/transformers#31020]
### System Info

- `transformers` version: 4.41.1
- Platform: Linux-5.15.0-1055-aws-x86_64-with-glibc2.35
- Python version: 3.10.14
- Huggingface_hub version: 0.23.0
- Safetensors version: 0.4.3
- Accelerate version: 0.30.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.3.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running the model using huggingface text-generation-inference server will cause the issue

```
AttributeError: 'Phi3Config' object has no attribute 'attention_bias' 
```

Reference issue:
https://github.com/aws/sagemaker-huggingface-inference-toolkit/issues/123 

### Expected behavior

tgi server should successfully run the Phi3 model

**Comment by amyeroberts** [comment]
cc @ArthurZucker @younesbelkada
