### ISSUE TITLE
Arm-based (M1, M2, M3) Mac Install Issues for `pip install transformers` (<4.23.0)

### ISSUE THREAD

**Issue by ai-nikolai** [huggingface/transformers#31023]
### System Info

**This is not critical just FYI:**
Tested the following on: `Mac OS 14`, with `arm-based chip` (M2 Pro).

```bash
pip3 install transformers==4.19
pip3 install transformers==4.20
pip3 install transformers==4.21
pip3 install transformers==4.22
```

All of the above fail. 
`pip3 install transformers==4.23.0` is the first one that works.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

On: `Mac OS 14` with `arm-based` chip.

```bash
pip3 install transformers==4.19
```

### Expected behavior

Installs successfully OOB.

**Comment by amyeroberts** [comment]
Hi @ai-nikolai, thanks for digging into this and opening this issue! 

Making the previous releases installable probably isn't something we'd be able to address (any changes to code on the repo would just go in the most recent release). 

Is there a reason for trying to install these versions specifically? v4.19 for example is two years old now.
