### ISSUE TITLE
What if past_key_values is in model_kwargs but is None

### ISSUE THREAD

**Issue by estelleafl** [huggingface/transformers#31039]
https://github.com/huggingface/transformers/blob/4c6c45ba138202f42582b5cea98126af87195a95/src/transformers/generation/utils.py#L1317

This line fails for me when past_key_values is in model_kwargs but is None. Line 1321 raises an error 
Could you advice?

Thank you

**Comment by amyeroberts** [comment]
cc @gante @zucchini-nlp

**Comment by zucchini-nlp** [comment]
Related to #31017
