### ISSUE TITLE
Add sanity validation steps

### ISSUE THREAD

**Issue by dhruvbpai** [huggingface/transformers#31047]
### Feature request

@RylanSchaeffer

Add support for sanity validation steps before training begins, to ensure evaluation works correctly. For inspiration, Pytorch Lightning has a validation sanity check feature which is similar to what I am requesting.

### Motivation

I would like to have the option to run evaluation before training starts, either for metrics or debugging purposes.

### Your contribution

I can add support for this when given the green light.

**Comment by amyeroberts** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
Yeah axolotl does this, would be good for us to have this as well.

**Comment by dhruvbpai** [comment]
I'd be happy to get started but I am relatively new to open-source contributions. Would you be able to provide a few pointers for how you would recommend getting started, so I can take a hack at it?
@muellerzr

**Comment by muellerzr** [comment]
cc @SunMarc not sure how far you got into this :)

**Comment by SunMarc** [comment]
Hi @dhruvbpai, I tried to implement what you asked ! I didn't test it yet but feel free to do it !
