### ISSUE TITLE
Token Classification Pipeline support for Layout models 

### ISSUE THREAD

**Issue by yaswanth19** [huggingface/transformers#31056]
### Feature request

Currently, It seems the pipeline feature doesn't support layout models like LayoutLM and LILT for Token Classification task. The pipeline as of now only takes the input string which alone is not sufficient in this case and additional code modification should be made to incorporate the bounding box info.

### Motivation

I was trying out pipeline feature for LayoutLMv3 model and found out that there is no support for bbox as inputs.So, currently I have different end-to-end functions which does the job but the pipeline feature can be used which replaces all those functions.  

### Your contribution

I could contribute and raise a PR to incorporate this change in the Token Classification Pipeline.

**Comment by LysandreJik** [comment]
WDYT @amyeroberts ?

**Comment by amyeroberts** [comment]
@yaswanth19 As the input / output for the layout models is highly specific, I'm not sure a pipeline makes much sense here.
