### ISSUE TITLE
Multi input of owlv2 cause RuntimeError: Boolean value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by zhangjingxian1998** [huggingface/transformers#31077]
### System Info

- `transformers` version: 4.41.1
- Platform: Linux-6.5.0-26-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.23.1
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.4.0.dev20240318+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@jla524 

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

```
import requests
from PIL import Image
from io import BytesIO
from transformers import AutoProcessor, Owlv2ForObjectDetection

processor = AutoProcessor.from_pretrained('google/owlv2-base-patch16-ensemble')
model = Owlv2ForObjectDetection.from_pretrained('google/owlv2-base-patch16-ensemble')

url = 'http://demandware.edgesuite.net/sits_pod41/dw/image/v2/AAJI_PRD/on/demandware.static/-/Sites-londondrugs-master/default/dw99e32df7/products/L8191009/large/L8191009.JPG?sw=556&amp;sh=680&amp;sm=fit'
response = requests.get(url, timeout=2)
image = Image.open(BytesIO(response.content)).convert('RGB')
target_sizes = [image.size, image.size]
texts = ["human"]

inputs = processor(text=[texts, texts], images=[image,image], return_tensors="pt")
outputs = model(**inputs)
results = processor.post_process_object_detection(outputs=outputs, threshold=0.1, target_sizes=target_sizes)
```
It error at
https://github.com/huggingface/transformers/blob/9d35edbb30625489bf286a9b15aed0c5a3119c1c/src/transformers/models/owlv2/image_processing_owlv2.py#L531

### Expected behavior

Two image and Text lists input, two results should output.

**Comment by LysandreJik** [comment]
cc @qubvel if you have bandwidth

**Comment by qubvel** [comment]
Hi @zhangjingxian1998 thanks for reporting the issue 🤗 

It seems like this use case was missed in https://github.com/huggingface/transformers/pull/30686 while fixing the bounding box rescaling issue. I prepared a fix
