### ISSUE TITLE
from transformers import Phi3VModel, Phi3VConfig. Phi3 Vision config not added to transformers.

### ISSUE THREAD

**Issue by sankydesai** [huggingface/transformers#31073]
### System Info

from transformers import Phi3VModel, Phi3VConfig.
Fails with error: 
ImportError: cannot import name 'Phi3VModel' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

Note: Installed Transformers from source. 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

!pip install -U git+https://github.com/huggingface/transformers
from transformers import Phi3VModel, Phi3VConfig

### Expected behavior

No Error.

**Comment by shauray8** [comment]
Hey @sankydesai, I don't think you can really import `Phi3VModel` or `Phi3VForCausalLM` directly from transformers 

The configuration for the Phi3 Vision model includes an auto_map field, which indicates the appropriate classes to use for loading the model.
```json
"auto_map": {
    "AutoConfig": "configuration_phi3_v.Phi3VConfig",
    "AutoModelForCausalLM": "modeling_phi3_v.Phi3VForCausalLM"
}
```
Which is uploaded on the hub itself
