### ISSUE TITLE
Convert_mistral_weights_to_hf fails loading consolidated.safetensors

### ISSUE THREAD

**Issue by HRKpython** [huggingface/transformers#31093]
### System Info

Need the latest convert_mistral_weights_to_hf to load the Mistral v0.3 instruct.  The current code in the repo needs modifications:
No sliding_window in params.json
Torch.load cannot load the consolidated.safetensors file

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1- try running
Python convert_mistral_weights_to_hf with Mistral v0.3 model weights

### Expected behavior

Convert weights to hugging face format

**Comment by younesbelkada** [comment]
Hi @HRKpython 
https://github.com/huggingface/transformers/pull/30981 updates the conversion script to support v3 weights, can you try that new script while waiting to be merged?

**Comment by HRKpython** [comment]
Worked.  Thanks a lot
