### ISSUE TITLE
Pre-training reference URL in Idefics2 codebase

### ISSUE THREAD

**Issue by BiliBraker** [huggingface/transformers#31101]
The below snippet from the `modeling_idefics2.py` script points to "the original codebase", but the link is incorrect.
https://github.com/huggingface/transformers/blob/a564d10afe1a78c31934f0492422700f61a0ffc0/src/transformers/models/idefics2/modeling_idefics2.py#L1347-L1349

Could you provide the correct link for the pre-training configuration for `Idefics2`?

**Comment by NielsRogge** [comment]
This is due to a `Copied from` statement from llava: https://github.com/haotian-liu/LLaVA/tree/main/llava.

The link in `modeling_idefics2.py` should actually be removed

**Comment by BiliBraker** [comment]
Sure, but I've only found 4 models (except llava) with this comment:
https://github.com/huggingface/transformers/blob/a564d10afe1a78c31934f0492422700f61a0ffc0/src/transformers/models/llava_next/modeling_llava_next.py#L239
https://github.com/huggingface/transformers/blob/a564d10afe1a78c31934f0492422700f61a0ffc0/src/transformers/models/vipllava/modeling_vipllava.py#L142
https://github.com/huggingface/transformers/blob/a564d10afe1a78c31934f0492422700f61a0ffc0/src/transformers/models/video_llava/modeling_video_llava.py#L134
https://github.com/huggingface/transformers/blob/a564d10afe1a78c31934f0492422700f61a0ffc0/src/transformers/models/idefics2/modeling_idefics2.py#L1349

**Comment by NielsRogge** [comment]
Ok I was searching on "important: this ported version" which gave me 7 results, feel free to only keep it for llava
