### ISSUE TITLE
OverflowError: out of range integral type conversion attempted

### ISSUE THREAD

**Issue by manandey** [huggingface/transformers#31110]
### System Info

Transformers version : 4.41.1
Python version : 3.10

### Who can help?

@younesbelkada @ArthurZucker 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

When I execute the code in the colab, I get the error message: `OverflowError: out of range integral type conversion attempted`

This happens when I add the line: `model.generation_config.max_new_tokens = max_target_length`

Otherwise I get the warning: `userwarning: using the model-agnostic default `max_length` (=20) to control the generation length. we recommend setting `max_new_tokens` to control the maximum length of the generation.`

https://colab.research.google.com/drive/11R2MMK9nq0oe7xUXSQaW8tahhgR9cjNc?usp=sharing

cc. @younesbelkada @ArthurZucker 

### Expected behavior

The code should work fine.

**Comment by LysandreJik** [comment]
Hey @manandey, could you please put the full error message here? We're only getting the final line and it's not sufficient to debug this efficiently. Thanks.

**Comment by younesbelkada** [comment]
Hi @manandey 
This is likely because in `pred_ids` you might have negative values due to tokens masking. Can you print what is inside `pred_ids` ? You might need to do something close to:
```diff
pred_ids = pred.predictions
+ pred_ids[pred_ids == -100] = tokenizer.pad_token_id
pred_str = tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
labels_ids[labels_ids == -100] = tokenizer.pad_token_id
```

**Comment by manandey** [comment]
@younesbelkada I am trying to update the script to work on a Colab TPU. But it seems to be not working. Can you kindly take a look and suggest if I am doing anything wrong. Thanks! 
[https://colab.research.google.com/drive/16UYvGbMkX5laJZVwujz-GP4EnIWBskQD?usp=sharing](https://colab.research.google.com/drive/16UYvGbMkX5laJZVwujz-GP4EnIWBskQD?usp=sharing)

**Comment by manandey** [comment]
@younesbelkada it would be great if you could kindly help a bit on this. Thanks!

**Comment by amyeroberts** [comment]
Hi @manandey, is the same error happening as before?

**Comment by manandey** [comment]
Hi @amyeroberts, the script worked fine when run on a GPU. I am trying to make it work on a Colab TPU, but it's not working as expected. So, just wanted some help if you could have a high level look and suggest if I am doing something wrong or point me to some example scripts for running Huggingface Trainer on a TPU. Thanks!

**Comment by amyeroberts** [comment]
Hi @manandey, looking at the notebook it seems a different problem is being encountered from the original one in this issue. In this case, a new issue should be opened, as this ensures we can properly track open and resolved bugs. 

There are guides available on running on TPU with accelerate here :https://huggingface.co/docs/accelerate/en/concept_guides/training_tpu
