### ISSUE TITLE
Add siglip flashattention support?

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#31138]
Add siglip flashattention support?

I noticed that the navit-flashatten-siglip version already added flash attention,  would transformers add it support inside ?

**Comment by LysandreJik** [comment]
cc @molbap or @qubvel maybe :)

**Comment by lucasjinreal** [comment]
these two guys looked but didn't response.

**Comment by qubvel** [comment]
@lucasjinreal thanks for the feature request, I will take a look at it!

**Comment by lucasjinreal** [comment]
thanks, since more and more MLLM used siglip as vision encoder, if flash attention support would be very reduce training cost time
