### ISSUE TITLE
Slow tokenizer-loading when many tokens (~17k) are added by a user.

### ISSUE THREAD

**Issue by jaeminSon** [huggingface/transformers#31134]
### System Info

Ubuntu 20.04.2 LTS
transformers==4.40.1

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. add many tokens to tokenizer using tokenizer.add_tokens method
2. save it
3. load it (takes too long time)

reason: this list-comprehension takes long time 

https://github.com/huggingface/transformers/blob/2b9e252b16396c926dad0e3c31802b4af8004e93/src/transformers/tokenization_utils_fast.py#L173 

using vs-code debugger, when the list-comprehension omits comparison, such as the following, it is fast.

```
tokens_to_add = [
            token
            for index, token in sorted(added_tokens_decoder.items(), key=lambda x: x[0])
        ]

```

There is comment saying 

```
# The following logic will be replace with a single add_tokens once a fix is pushed to tokenizers
# allows converting a slow -> fast, non-legacy: if the `tokenizer.json` does not have all the added tokens
# uses the information stored in `added_tokens_decoder`.
# this is costly for fast tokenizers as we re-compute the regex again. But not all tokens are added tokens
```

Any plan to replace this code?
        

### Expected behavior

Faster tokenizer initialization

**Comment by ArthurZucker** [comment]
Completely agree. #30574 will fix it! I just need to fix a breaking change made in `tokenizers` before I can release and should adress this

**Comment by jaeminSon** [comment]
Thanks for your time addressing this issue!
