### ISSUE TITLE
LLaVA-NeXT-Video support

### ISSUE THREAD

**Issue by AmazDeng** [huggingface/transformers#31164]
### Model description

The model to consider.
The llava-next-video project has already been released, and the test results are quite good. Are there any plans to support this project?

Currently, Hugging Face does not support this model.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://github.com/LLaVA-VL/LLaVA-NeXT/blob/inference/docs/LLaVA-NeXT-Video.md

**Comment by zucchini-nlp** [comment]
Hey! LLava-NeXT-Video is planned to be added to transformers. See more here https://github.com/LLaVA-VL/LLaVA-NeXT/issues/9 :)

**Comment by AmazDeng** [comment]
> Hey! LLava-NeXT-Video is planned to be added to transformers. See more here [LLaVA-VL/LLaVA-NeXT#9](https://github.com/LLaVA-VL/LLaVA-NeXT/issues/9) :)

So is there an approximate point in time?

**Comment by zucchini-nlp** [comment]
I would say approximately mid of June. I will ping the authors to ask about the state of their next release as we've been getting a lot of requests to add this model. I'll give this model higher priority

**Comment by AmazDeng** [comment]
> I would say approximately mid of June. I will ping the authors to ask about the state of their next release as we've been getting a lot of requests to add this model. I'll give this model higher priority

ok, thanks.
