### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils' in Python 3.12 

### ISSUE THREAD

**Issue by sailfish009** [huggingface/transformers#31174]
### System Info

```
transformers : 4.41.1, 4.41.2
python : 3.12.3
platform: ubuntu linux 22.04 x64
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm not in a position to copy the output, so I'll just describe it. 

The tensorflow package is still using the distutils package, which is still called by the transformers library. I personally don't use tensorflow at all. 

The errors were all in two places.  I fixed the errors by simply commenting out the code.

### Expected behavior

It works without errors at the time of calling and loading the pre-trained language model.

**Comment by LysandreJik** [comment]
Does this error happen when not having TensorFlow installed as well?

**Comment by cyrilfantin** [comment]
maybe beacaus of it's deprecated in 312 : https://docs.python.org/3.11/whatsnew/3.10.html#distutils-deprecated
