### ISSUE TITLE
Add Mamba2

### ISSUE THREAD

**Issue by vasqu** [huggingface/transformers#31204]
### Feature request

Support of a new version of the mamba architecture. See paper @ https://arxiv.org/abs/2405.21060. Base code has been released in their repo https://github.com/state-spaces/mamba.

### Motivation

It's still very competitive in NLP (according to the benchmarks) but also a good chunk faster due to new parallelism mechanisms.

### Your contribution

Not sure, I could look into it but it's definitely a bigger undertaking :)

**Comment by amyeroberts** [comment]
cc @ArthurZucker

**Comment by ArthurZucker** [comment]
cc @3outeille do you want to have a go at this?

**Comment by Adibvafa** [comment]
@3outeille I would love to help out!

**Comment by vasqu** [comment]
Glad to be @ when a PR is opened :eyes:

**Comment by vasqu** [comment]
Not sure if this counts as ad but I've created my own HF-compatible version of Mamba2: https://github.com/vasqu/mamba2-torch

Feel free to remove it if this is unwanted. 
- It's still very experimental 
- It doesn't support the hybrid variant with attention blocks. 
- I haven't tested too much so it might actually be crap. 
- It can also be used as a reference for an actual transformers implementation (?)

**Comment by ArthurZucker** [comment]
Hybrid variant will probably be here, as it's Jamba like

**Comment by Adibvafa** [comment]
@vasqu Awesome work! Sorry for the late response, I was busy finishing up a paper. I will take a look tomorrow so we can work together and finalize it. Once Mamba2 is done, we can move on to Mamba2Hybrid.

**Comment by Adibvafa** [comment]
@vasqu Can you make me a collaborator on the repo you shared so I can open up PRs?

**Comment by vasqu** [comment]
@Adibvafa No worries and good luck on the paper! Let's move the discussion elsewhere: Do you have discord? Add me `_vasquez` or contact me via mail `a.vlasjuk@t-online.de`.

I think we should directly work on a fork. I want the repo above to stay as a standalone modular thing for now.

**Comment by pglorio** [comment]
Hi everyone, 

Thanks so much for all the effort being put into porting mamba2 in transformers! I'm really excited about this. Just checking in to see if there's any update or estimated timeline on when the PR might be created? Thank you!

**Comment by vasqu** [comment]
@pglorio Hey there, there's no specific timeline but @Adibvafa and I will start working on it soon, hopefully in the next couple of days :)

No idea how long this will take though. I can tag you when we open our PR (if you want to).

**Comment by theo77186** [comment]
[Codestral Mamba](https://mistral.ai/news/codestral-mamba/) just got released and it uses the Mamba2 architecture, with untied embeddings unlike every other Mamba2 models, which use tied embeddings.

**Comment by ArthurZucker** [comment]
We are adding Codestral Mamba with @molbap, it's full mamba layers so keep #32027 open ! 🫂

**Comment by vasqu** [comment]
Closing this for now since it has been added recently with #32080 but if wanted hybrid variants can be worked on top now and maybe #32027 can be used as reference :)
