### ISSUE TITLE
Issue with model.generate returning outdated hidden states for earlier tokens

### ISSUE THREAD

**Issue by Joe-Hall-Lee** [huggingface/transformers#31229]
### Description
I have been using the generate method from transformers library to generate text and retrieve hidden states. However, I encountered an issue with the output of the hidden states in the model.generate method. Specifically, it seems like the hidden states for previously generated tokens are not updated when a new token is generated.
Here's the code I am using:

```
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch


def generate_with_final_hidden_state(model, input_ids, attention_mask, max_output_length, tokenizer):

    model.eval()

    outputs = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=max_output_length,
        output_hidden_states=True,
        return_dict_in_generate=True,
        temperature=0.0,
        top_p=1.0
    )

    generated_ids = outputs.sequences
    hidden_states = outputs.hidden_states

    last_layer_hidden_states = [state[-1] for state in hidden_states]

    for idx, state in enumerate(last_layer_hidden_states):
        print(f"Shape of hidden state at step {idx}:", state.shape)

    final_hidden_state = torch.cat(last_layer_hidden_states, dim=1)

    if generated_ids.shape[1] > final_hidden_state.shape[1]:
        generated_ids = generated_ids[:, :-1]

    batch_size, total_length = generated_ids.shape

    mask = torch.ones(batch_size, total_length,
                      dtype=torch.long, device=input_ids.device)
    input_length = input_ids.shape[1]
    mask[:, :input_length] = 0

    return generated_ids, final_hidden_state, mask

# Other parts of the code are omitted for brevity.

```
Upon inspecting the shape of hidden_states, I observed the following:

- hidden_states is a tuple of length new_tokens + 1.

- Each element in hidden_states is also a tuple of length num_hidden_layers + 1.

- For the last layer, the first Tensor has dimensions [batch_size, input_length, hidden_size], and the remaining Tensors have dimensions [batch_size, 1, hidden_size].

This indicates that the hidden state of newly generated tokens is appended to hidden_states, but the hidden states of earlier tokens are not updated accordingly. As a result, directly concatenating these hidden states to form an embedding may not be appropriate because the hidden states of earlier tokens may not be the latest.
### Expected behavior
When generating sequences, it would be more meaningful if the hidden states for all tokens up to the current step were updated and returned. This would ensure that each token's hidden state is up-to-date, reflecting the current context and generated tokens.
### Environment
transformers version: 4.31.0
Platform: Linux
Python version: 3.10.12
PyTorch version: 2.1.2

**Comment by amyeroberts** [comment]
cc @gante @zucchini-nlp

**Comment by Joe-Hall-Lee** [comment]
I've realized that I made a mistake in my previous description. The hidden states of previously generated tokens are not supposed to be updated when generating each new token. Apologies for the confusion.
