### ISSUE TITLE
Add a new model for RNA sequence modeling

### ISSUE THREAD

**Issue by yangheng95** [huggingface/transformers#31241]
### Model description

I want to add a new model for RNA sequence modeling in next few weeks, like DNABERT. I have drafted a branch [here](https://github.com/yangheng95/transformers/tree/add_omnigenome) to add the model and prepared some [examples](https://github.com/yangheng95/transformers/tree/add_omnigenome/examples/pytorch/genomic-sequence-modeling) for RNA modeling. There is a manuscript for the model: [OmniGenome - Aligning RNA Sequences with Secondary Structures in Genomic Foundation Models.pdf](https://github.com/user-attachments/files/15568804/OmniGenome.-.Aligning.RNA.Sequences.with.Secondary.Structures.in.Genomic.Foundation.Models.pdf)

I have never contributed any model to Transformers before, can anyone let me know what should I do to sort it out?

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

The URL of [implementation](https://github.com/yangheng95/transformers/tree/add_omnigenome/src/transformers/models/omnigenome)

The URL of [model weights](https://huggingface.co/anonymous8/OmniGenome-186M)

**Comment by amyeroberts** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
Hi @yangheng95, this looks really cool! I think the right approach here is to upload the model with the custom code in the model repo itself! In general, most new architectures start this way. Code in the `transformers` library itself is maintained by the team at Hugging Face, so we generally only port architectures into the main library after they get a lot of users.

Please see the guide [here](https://huggingface.co/docs/transformers/en/custom_models). It seems like you've already done most of the work by writing the `configuration` and `modeling` files, so all you'd need to do is initialize your model, register the auto classes and `push_to_hub()`.

Let me know if you encounter any difficulties!
