### ISSUE TITLE
Flaky test - tests/models/mobilenet_v1/test_modeling_mobilenet_v1.py::MobileNetV1ModelTest::test_batching_equivalence

### ISSUE THREAD

**Issue by amyeroberts** [huggingface/transformers#31257]
### System Info

`tests/models/mobilenet_v1/test_modeling_mobilenet_v1.py::MobileNetV1ModelTest::test_batching_equivalence` periodically fails causing red on CI runs

Example CI run: https://app.circleci.com/pipelines/github/huggingface/transformers/94887/workflows/6766b7cd-c38c-4334-ab25-2afcb8e0d842/jobs/1246458

### Who can help?

@zucchini-nlp as you added the batching equivalence tests :) 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run enough times to hit an error 

### Expected behavior

Doesn't occasionally fail

**Comment by zucchini-nlp** [comment]
Yeah, probably it was flaky at the time of adding because the MobileNetV2 is also flaky as marked #29516 

As discussed, I am not CV expert but maybe I can give it another look later next week
