### ISSUE TITLE
Confusion about LlavaNextImageProcessor results

### ISSUE THREAD

**Issue by NaNillll** [huggingface/transformers#31275]
### System Info

Transformers==4.40.0
torch==2.0.1

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

Very simple
`        
```
processor = LlavaNextProcessor.from_pretrained("/home/vllm/llava-hfllava-v1.6-34b-hf")
image = Image.open("llava_v1_5_radar.jpg")
image = image.resize((336,336)) 
prompt = "<|im_start|>system\nAnswer the questions.<|im_end|><|im_start|>user\n" + "<image>" * 2144 + "\n" + "What is shown in this image?<|im_end|><|im_start|>assistant\n"
img_ = processor(prompt, image, return_tensors='pt')['pixel_values']
```
`

### Expected behavior

Acording to papers of llava-next, after pre-processor, the results is [5,336,336,3], which means the image is encode into 5 parts.
(Sorry I can not upload image, you can refer this https://llava-vl.github.io/blog/assets/images/llava-1-6/high_res_arch_v2.png)

Howerver, I find when using small image such as [336,336], the results is [3,336,336,3]; but when using large image like [1920,1080], the result is  [5,336,336,3], why?
This difference in size causes errors in my LLM framework. Since I don't know how the clipping works, I don't know how to modify it......

What is the principle of this module? The documentation doesn't explain in too much detail. I am a nood to llava. Thanks for your instructions!

**Comment by NaNillll** [comment]
[https://llava-vl.github.io/blog/assets/images/llava-1-6/high_res_arch_v2.png](url)

**Comment by amyeroberts** [comment]
cc @NielsRogge

**Comment by NaNillll** [comment]
I think the result should be related to the aspect ratio, I read the config of LLAVA-next and find three ratio from "image_grid_pinpoints", 1:1, 1:2, 1:3. It looks like LLAVA will aligned the image to an optimal ratio, crop and sample. If  aligne to 1:1, it will [2x2+1, 336,336]; if 1:2, [2x1+1, 336,336]; if 1:3, [3x1+1, 336,336]

So I try different image, and find it is right:
input->output
[672, 1344] -> [3,336,336]
[1344, 2688 -> [3,336,336]
[672, 672] -> [5,336,336]
[336, 1008] -> [4,336,336]

However, when I input [336, 336], I think it should be [5,336,336]. But it output [3,336,336]. Why? It should be  aligned to [5,336,336].
I also try:
[335,335] ->  [3,336,336]
[337,337] ->  [5,336,336]

**Comment by NaNillll** [comment]
I think the best ratio is select by this function, and (336,336) get [336,672]
```
def select_best_resolution(original_size: tuple, possible_resolutions: list) -> tuple:
    """
    Selects the best resolution from a list of possible resolutions based on the original size.

    This is done by calculating the effective and wasted resolution for each possible resolution.

    The best fit resolution is the one that maximizes the effective resolution and minimizes the wasted resolution.

    Args:
        original_size (tuple):
            The original size of the image in the format (height, width).
        possible_resolutions (list):
            A list of possible resolutions in the format [(height1, width1), (height2, width2), ...].

    Returns:
        tuple: The best fit resolution in the format (height, width).
    """
    original_height, original_width = original_size
    best_fit = None
    max_effective_resolution = 0
    min_wasted_resolution = float("inf")

    for height, width in possible_resolutions:
        scale = min(width / original_width, height / original_height)
        downscaled_width, downscaled_height = int(original_width * scale), int(original_height * scale)
        effective_resolution = min(downscaled_width * downscaled_height, original_width * original_height)
        wasted_resolution = (width * height) - effective_resolution

        if effective_resolution > max_effective_resolution or (
            effective_resolution == max_effective_resolution and wasted_resolution < min_wasted_resolution
        ):
            max_effective_resolution = effective_resolution
            min_wasted_resolution = wasted_resolution
            best_fit = (height, width)

    return best_fit
```

**Comment by NaNillll** [comment]
> @NaNillll you are right, the different resolutions are used to fit better different types of image aspect ratios and preserve more details.
> 
> Regarding the 336 case, it selected (336, 672) for best resolution because the function tries to preserve all of the image and not to crop it at the first place. That's why (337, 337) gets (672, 672) for best resolution, and not (336, 672), because the latter will require cropping the image a bit. And as you pointed out, different best resolutions are further divided into 3, 4 or 5 patches depending on aspect ratio.
> 
> Correct me if I'm wrong @NielsRogge

OK, thank you!
