### ISSUE TITLE
'FastSpeech2ConformerConfig' object has no attribute 'model_config'

### ISSUE THREAD

**Issue by spencerchubb** [huggingface/transformers#31270]
### System Info

- `transformers` version: 4.41.2
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.11.1
- Huggingface_hub version: 0.23.3
- Safetensors version: 0.4.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.3.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Try to run the example code from the docs: https://huggingface.co/docs/transformers/en/model_doc/fastspeech2_conformer

```from transformers import pipeline, FastSpeech2ConformerHifiGan
import soundfile as sf

vocoder = FastSpeech2ConformerHifiGan.from_pretrained("espnet/fastspeech2_conformer_hifigan")
synthesiser = pipeline(model="espnet/fastspeech2_conformer", vocoder=vocoder)

speech = synthesiser("Hello, my dog is cooler than you!")

sf.write("speech.wav", speech["audio"].squeeze(), samplerate=speech["sampling_rate"])
```

### Expected behavior

Run text-to-speech inference

AttributeError: 'FastSpeech2ConformerConfig' object has no attribute 'model_config'. Did you mean: 'decoder_config'?

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi @ylacombe
