### ISSUE TITLE
Performance Issue about pretrained bert migration from tensorflow to pytorch

### ISSUE THREAD

**Issue by eagle705** [huggingface/transformers#3130]
# ❓ Questions & Help

Hi, 
I have a question about migration from tensorflow to pytorch.
if I change pretrained BERT with google tensorflow 1.x version to pytorch transformers BERT through transformers-cli, performance drops a lot. I wonder why.

Is there any similar case?

**Comment by BramVanroy** [comment]
Are you using the latest version? `transformers` and not `pytorch-transformers`. It works with both TF2 and PT. You can test both and compare.
