### ISSUE TITLE
AutoModelForCausalLM.from_pretrained silently fails

### ISSUE THREAD

**Issue by gpetters-amd** [huggingface/transformers#31306]
### System Info

Running `AutoModelForCausalLM.from_pretrained` as in the following script silently fails on Windows 10. I've attached a minimal reproducer and the pip freeze of the environment I'm using.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. `pip install -r freeze.txt`
2. `python repro.py`

### Expected behavior

The script should print "Done."

**Comment by gpetters-amd** [comment]
[Repro files are here.](https://gist.github.com/gpetters-amd/833bd956af4ccc18dca90d956411b7c3)

**Comment by RUFFY-369** [comment]
Hi @gpetters-amd , it's happening because your RAM goes out of memory while instantiating the pretrained model
Please change your code to the following in `repro.py` :
```
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained(
    "Trelis/Llama-2-7b-chat-hf-function-calling-v2", token=None, config=None,low_cpu_mem_usage=True,use_cache=True,offload_state_dict=True
)

print("Done.")
```

**Comment by gpetters-amd** [comment]
> Hi @gpetters-amd , it's happening because your RAM goes out of memory while instantiating the pretrained model Please change your code to the following in `repro.py` :
> 
> ```
> from transformers import AutoModelForCausalLM
> model = AutoModelForCausalLM.from_pretrained(
>     "Trelis/Llama-2-7b-chat-hf-function-calling-v2", token=None, config=None,low_cpu_mem_usage=True,offload_state_dict=True
> )
> 
> print("Done.")
> ```
> 
> `low_cpu_mem_usage` : **'it will load the model using ~1x model size CPU memory'** `offload_state_dict` : **'it will temporarily offload the CPU state dict to hard drive and will prevent getting out of RAM'**
> 
> Cheers!

Oh, you're right. Thanks!
