### ISSUE TITLE
[GGUF] Support new architectures/ quantisation schemes in Transformers

### ISSUE THREAD

**Issue by Vaibhavs10** [huggingface/transformers#31314]
### GGUF 🤝 Transformers

Currently, Transformers allows one to load a GGUF directly in Transformers, or alternatively, convert it into Transformers format. [ref](https://huggingface.co/docs/transformers/main/en/gguf)

We currently support LLaMa3, Mistral and Qwen 2 architectures.

Additionally we support the following Quantisation schemes:

- F32
- Q2_K
- Q3_K
- Q4_0
- Q4_K
- Q5_K
- Q6_K
- Q8_0

We appreciate contributions and suggestions on which model architectures & quantisation schemes we should support next.

cc: @younesbelkada @LysandreJik

**Comment by PriNova** [comment]
What about "Importance Matrix"? Is this relevant here?

**Comment by YejinHwang909** [comment]
@Vaibhavs10 Are there any plans to add deepseek v2, v3 as well?
