### ISSUE TITLE
Using a single 'RecurrentGemmaRglru' layer -  "Trying to backward through the graph a second time" Error

### ISSUE THREAD

**Issue by talrub** [huggingface/transformers#31324]
### System Info

- `transformers` version: 4.42.0.dev0
- Platform: Linux-4.15.0-65-generic-x86_64-with-glibc2.27
- Python version: 3.11.5
- Huggingface_hub version: 0.23.3
- Safetensors version: 0.4.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.2.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.6.1 (cpu)
- Jax version: 0.3.25
- JaxLib version: 0.3.25
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: Tesla V100-SXM2-32GB

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Code sample can be found in the following Colab link:

https://colab.research.google.com/drive/16L8RbHhg5EvgHcZq6qoZEmQS7vhV8QTr?usp=drive_link

### Expected behavior

I tried to work with a single 'RecurrentGemmaRglru'  layer followed by a linear layer (see RGLRU class) for an MNIST classification task.
After one successful epoch, i am getting the following error:

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

I would appreciate any advice regarding this issue since I didn't find any problem with my code.
I would like to avoid using retain_graph=True unless there is a known issue with using 'RecurrentGemmaRglru' that requires it.

**Comment by ArthurZucker** [comment]
Hey! Sorry for the delayed answer here. Are you certain that you set `use_cache` to false to enter the code path where the cache is not used? 🤗
