### ISSUE TITLE
special token `<s>` conflicts with html tag `<s>`

### ISSUE THREAD

**Issue by scruel** [huggingface/transformers#31336]
### System Info

- `transformers` version: 4.41.2
- Platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Huggingface_hub version: 0.23.3
- Safetensors version: 0.4.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
>> from transformers import AutoTokenizer
>> tokenizer = AutoTokenizer.from_pretrained(
>>     "meta-llama/Llama-2-7b-hf", local_files_only=True, encode_special_tokens =False)
>> text = "<s>Yay!</s>"
>> x = tokenizer.encode(text, add_special_tokens=False)
>> x
[1, 612, 388, 29991, 2]
>> text2 = tokenizer.decode(x)
>> assert text == text2
False
>> text2
'<s> Yay!</s>'
```

### Expected behavior

text == text2

**Comment by ArthurZucker** [comment]
Hey! Not sure what went wrong, but if you set `encode_special_tokens` on main, the encoding of `<s>` and `</s>` are going to be the ones the model can reach with BPE, and thus in this case, `'<', 's', '>'`

**Comment by scruel** [comment]
Thanks, I noticed that it already been considered in recently commits, and I applied a workaround which solved related issues, thanks for your answer!
