### ISSUE TITLE
[CI] 2 Cohere tests are failing and skipped for now

### ISSUE THREAD

**Issue by ydshieh** [huggingface/transformers#31351]
The following 2 tests are currently failing and being skipped for now.

- test_initialization
- test_fast_init_context_manager

See  #31263

**Comment by jkmschoultz** [comment]
Hello @ydshieh, I would love to try to help with this! However, I am struggling to recreate the issue as when I run these two tests in my local dev env they pass without any problem. Do I need to open a [WIP] PR to run the tests through GitHub actions?

**Comment by ydshieh** [comment]
Hi @jkmschoultz It's passing because I skipped those 2 tests in #31263

https://github.com/huggingface/transformers/pull/31263/files

So you will have to remove `@unittest.skip("Failing. Issue opened in #31351")` first :-)

**Comment by jkmschoultz** [comment]
Hi @ydshieh, thank you and yes I have already done so, see

https://github.com/jkmschoultz/transformers/commit/4a35d5fa95b7bedb282538dfcaab3278851edde8

This is where I cannot recreate the same test failure as you encountered, because the tests pass successfully when I run them locally.

**Comment by ydshieh** [comment]
This is likely a flaky tests. Would you like to try 

https://huggingface.co/docs/transformers/testing#repeat-tests

> pip install pytest-flakefinder
> pytest --flake-finder --flake-runs=100 tests/.....

If they are still passing on your side, I will have to check what to proceed

**Comment by ydshieh** [comment]
OK, let me check first. Thanks!

**Comment by ydshieh** [comment]
I can't reproduce it anymore 😅 . Maybe some commits in between fixed them. I will check further

**Comment by jkmschoultz** [comment]
Good thing it's working now at least! ... I guess? 😂 Let me know if I can help in any other way or if I should open a PR for this :)

**Comment by ydshieh** [comment]
Hi, thank you for the offering. These 2 tests are passing now but I can't figure out why. I opened #31517.

**Comment by bmuskalla** [comment]
@ydshieh It sounds like this can be closed as you enabled the skipped tests again.

**Comment by ydshieh** [comment]
Yes, thanks for reminding me 🤗
