### ISSUE TITLE
links of the model's pretrained weights

### ISSUE THREAD

**Issue by hzg0601** [huggingface/transformers#3136]
where can I find all the links of the model's pretrained weights,please?to download them by IDE is too slow.

**Comment by julien-c** [comment]
We have a `HfApi.model_list()` method on this PR https://github.com/huggingface/transformers/pull/3132 that might be of interest to you.

Do let us know if it solves your use case or not.

**Comment by sevenights** [comment]
I use the following script in an interactive enviroment:

```python
>> from transformers.hf_api import HfApi

>> HfApi.model_list()
```
But I got an error:` AttributeError: type object 'HfApi' has no attribute 'model_list'`

And my `transformers.__version__` is 2.5.1

Did I miss something ?

**Comment by hzg0601** [comment]
> We have a `HfApi.model_list()` method on this PR #3132 that might be of interest to you.
> 
> Do let us know if it solves your use case or not.

same problem with @sevenights ,remain unsolved--!

**Comment by julien-c** [comment]
#3132 was just merged on master, you should be able to try on master now.

**Comment by sevenights** [comment]
I get it, thank you :)
