### ISSUE TITLE
Idefics 2: shape mismatch: value tensor of shape [320, 4096] cannot be broadcast to indexing result of shape [0, 4096]

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/transformers#31380]
### System Info

Commit hash: a2ede66674d919fe507cc27db191f3314fd29948

- `transformers` version: 4.42.0.dev0
- Platform: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.23.3
- Safetensors version: 0.4.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1 (True)
- Tensorflow version (GPU?): 2.13.1 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: No
- Using GPU in script?: Yes
- GPU type: NVIDIA A100-SXM4-40GB

### Who can help?

@amyeroberts

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Run this code after `git clone` with the hash I specified above and `pip install -e .`

```py
import requests
from PIL import Image
from transformers import Idefics2Processor, Idefics2ForConditionalGeneration
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

url_1 = "http://images.cocodataset.org/val2017/000000039769.jpg"

image_1 = Image.open(requests.get(url_1, stream=True).raw)
images = [image_1]

messages = [{
    "role": "user",
    "content": [
        {"type": "text", "text": "What is in this image"},
        {"type": "image"},
    ],
}]

processor = Idefics2Processor.from_pretrained("HuggingFaceM4/idefics2-8b-chatty")
model = Idefics2ForConditionalGeneration.from_pretrained("HuggingFaceM4/idefics2-8b-chatty")
model.to(device)

# at inference time, one needs to pass `add_generation_prompt=True` in order to make sure the model completes the prompt
text = processor.apply_chat_template(messages, add_generation_prompt=True)
print(text)
# 'User: What’s the difference between these two images?<image><image><end_of_utterance>\nAssistant:'

inputs = processor(images=images, text=text, return_tensors="pt").to(device)

generated_text = model.generate(**inputs, max_new_tokens=500)
generated_text = processor.batch_decode(generated_text, skip_special_tokens=True)[0]
print("Generated text:", generated_text)
```

## Output
```
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.41it/s]
User: What is in this image<image><end_of_utterance>
Assistant:
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
Traceback (most recent call last):
  File "/home/ubuntu/untitled.py", line 32, in <module>
    generated_text = model.generate(**inputs, max_new_tokens=500)
  File "/usr/lib/python3/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/transformers/src/transformers/generation/utils.py", line 1896, in generate
    result = self._sample(
  File "/home/ubuntu/transformers/src/transformers/generation/utils.py", line 2633, in _sample
    outputs = self(
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/transformers/src/transformers/models/idefics2/modeling_idefics2.py", line 1829, in forward
    outputs = self.model(
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/transformers/src/transformers/models/idefics2/modeling_idefics2.py", line 1656, in forward
    inputs_embeds = self.inputs_merger(
  File "/home/ubuntu/transformers/src/transformers/models/idefics2/modeling_idefics2.py", line 1542, in inputs_merger
    new_inputs_embeds[special_image_token_mask] = reshaped_image_hidden_states
RuntimeError: shape mismatch: value tensor of shape [320, 4096] cannot be broadcast to indexing result of shape [0, 4096]
```

### Expected behavior

It should not crash.

**Comment by EricLBuehler** [comment]
Perhaps #31377 would fix this?

**Comment by mdmev** [comment]
Hello,
I am experiencing the same error. I recently upgraded the version of transformers as suggested in [#31377](https://github.com/huggingface/transformers/pull/31377). It works correctly when using the idefics-2 model from Hugging Face, but I still encounter the same error when using a fully fine-tuned model of my own. Do you have any suggestions on how to fix this?

**Comment by zucchini-nlp** [comment]
@mdmev hey! If the error is only in custom-tuned model, it might be related to model's config/generation_config. Can you pls share the model you're using so that I can try to reproduce it?

**Comment by mdmev** [comment]
@zucchini-nlp I was able to solve the issue by setting "use_cache" to true in the generation_config.json. I'm not sure if this is the best solution for the model, but it works for now. Thanks! Please let me know if there is another way to fix it so I can share the model.

**Comment by zucchini-nlp** [comment]
@mdmev Oke, thanks! But actually Idefics2 should be able to generate without caching, so let me know which model and script you're using. I'll investigate it a bit

**Comment by Debolena7** [comment]
Can anybody please tell me what the conclusion is regarding this error? How to resolve it? I get a similar error in the idefics3 model:
in "inputs_merger" function of "class Idefics3Model(Idefics3PreTrainedModel):"
    new_inputs_embeds[special_image_token_mask] = reshaped_image_hidden_states 
RuntimeError: shape mismatch: value tensor of shape [162, 2048] cannot be broadcast to indexing result of shape [2, 2048]. 
please help me resolve this error.

**Comment by Debolena7** [comment]
please help me resolve this error.

> Can anybody please tell me what the conclusion is regarding this error? How to resolve it? I get a similar error in the idefics3 model: in "inputs_merger" function of "class Idefics3Model(Idefics3PreTrainedModel):"
> 
> ```
> new_inputs_embeds[special_image_token_mask] = reshaped_image_hidden_states 
> RuntimeError: shape mismatch: value tensor of shape [162, 2048] cannot be broadcast to indexing result of shape [2, 2048]. 
> ```
> 
> please help me resolve this error. :(

**Comment by ezyzzy** [comment]
> Please help me resolve this error. The error comes even if I do "do_image_splitting=False".
> 
> > Can anybody please tell me what the conclusion is regarding this error? How to resolve it? I get a similar error in the idefics3 model: in "inputs_merger" function of "class Idefics3Model(Idefics3PreTrainedModel):"
> > ```
> > new_inputs_embeds[special_image_token_mask] = reshaped_image_hidden_states 
> > RuntimeError: shape mismatch: value tensor of shape [162, 2048] cannot be broadcast to indexing result of shape [2, 2048]. 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > please help me resolve this error. :(

similar error :(
