### ISSUE TITLE
SiqlipVisionModel does not support "device map= auto": no split modules`attribute

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#31400]
### Feature request

How to make SiglipVisionModel can support Auto map to map to multiple GPUs.

### Motivation

Currently, using MLLM with siglip, the whole model might need automap, since the vision encoder part is SiglipVisionModel, if it doesn;t support , would be a big problme

Also, would consider add flashattention support for Siglip?

### Your contribution

None for now

**Comment by amyeroberts** [comment]
Hi @lucasjinreal, thanks for opening a feature request! 

Could you share a code snippet of how the model is being created with `auto_map` and the running environment (run `transformers-cli env` in the terminal and copy-paste the output)? SigLip should support `device_map="auto"`

**Comment by zucchini-nlp** [comment]
I checked with the code in [model-doc](https://huggingface.co/docs/transformers/en/model_doc/llava) for SigLip and also got an error. Supporting "device_map" in VLMs is indeed needed important. I believe `_no_split_modules` should be same as in [ClipModel](https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/modeling_clip.py)

For `flashattention` afaik current VLMs in transformers use optimized attn implementations only for LLM backbone (e.g. LLaVa supports Flash-Attn and SDPA even though CLIP doesn't). There's an issue for adding SDPA attn (#30565) to all VLMs, I can open another tracker-issue for Flash-Attn but will not able to work on it right now. Open for community contributions

**Comment by lucasjinreal** [comment]
I have surpassed this error, by simply add a _no_split_modules = [] to the attribute.

But it could be better add inside transoformers, it's just a single line. I could submit a PR for this.

**Comment by zucchini-nlp** [comment]
@lucasjinreal cool, PR would be nice but you need to test in multi-gpu setting that everything is being split correctly. I don't think that an empty "split_modules" will work as the most similar CLIP doesn't split at some modules. If you don't have multiple gpus, I can run some tests after the PR is open :)

Flash-Attn noted, thanks, will add to my todo list!

**Comment by zucchini-nlp** [comment]
I believe the best solution is to copy 'no-split-modules' that are already indicated in text-vision components, and add them in SiglipModel's 'no-split-modules'
