### ISSUE TITLE
logging format

### ISSUE THREAD

**Issue by wwwbq** [huggingface/transformers#31405]
Hello, I would like to change the format of the logger in the transformers  when using AutoTokenizer. from_pretrained(). May I ask where the enable_explicit_format function in the logging.py file was called?

**Comment by amyeroberts** [comment]
Hi @wwwbq, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

You can find examples of how to use `enable_explicit_format` in some of our examples e.g. here: https://github.com/huggingface/transformers/blob/15b3923d656cf3e1a0c20d3ddc356eb89a703ce0/examples/pytorch/question-answering/run_qa.py#L261
