### ISSUE TITLE
Question about LlavaProcessor

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#31415]
The LlavaPocessor provides a direclty input of images and text.
But when I just need text conversation with MLLMs, it throws error. because images if None, it will have error in returned BatchFeature.

Am curious about, why does it designed like this? Why we need couple images and text togather? Besides, since many customized LLava models using differecent ImageTokenID, there is no way to reuse LLavaProcessor. 

Say I have text like this `<image> descirbe this image`, how does LlavaProcessor treat `<image>` token??  

I am so confused by the design.

**Comment by amyeroberts** [comment]
Hi, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by lucasjinreal** [comment]
I just got an solution.
