### ISSUE TITLE
 LlavaNextProcessor.__init__() got an unexpected keyword argument 'image_token'

### ISSUE THREAD

**Issue by M-Fannilla** [huggingface/transformers#31465]
### System Info

transformers 4.41.2
Python 3.10.12
Nvidia A40 / Runpod.io

Whe working with LlavaNextProcessor I get errors that were not there.

Error:
LlavaNextProcessor.__init__() got an unexpected keyword argument 'image_token'

Which previously did not happen (~week ago).

### Information

- [X] The official example scripts
- [x] My own modified scripts

### Reproduction

model_name = "llava-hf/llava-v1.6-vicuna-7b-hf"
processor = LlavaNextProcessor.from_pretrained(
    model_name, padding_side='left'
)
model = LlavaNextForConditionalGeneration.from_pretrained(
    model_name, torch_dtype=torch.float16, low_cpu_mem_usage=True
).to("cuda").eval()

### Expected behavior

I would expect to initiate the objects properly

**Comment by zucchini-nlp** [comment]
@M-Fannilla hi, I just updates llava-weights in the hub which caused the error. I will revert the changes soon

**Comment by M-Fannilla** [comment]
@zucchini-nlp Great, Thanks!

**Comment by zucchini-nlp** [comment]
@M-Fannilla should be working now, closing the issue as resolved!

**Comment by M-Fannilla** [comment]
There is new issue:

Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
