### ISSUE TITLE
ChatGLMForConditionalGeneration does not support Flash Attention 2.0 yet.

### ISSUE THREAD

**Issue by liuweie** [huggingface/transformers#31485]
Hello，I am using transformers to train glm4, and I try to use flash attention, then the following error occured:
"ChatGLMForConditionalGeneration does not support Flash Attention 2.0 yet."

**Comment by amyeroberts** [comment]
Hi @liuweie,

Yes, the ChatGLM models don't have flash attention implemented yet. You can make a request on the model's checkpoints on the hub for this feature to be added e.g. [like here on the discussions tab](https://huggingface.co/THUDM/chatglm3-6b/discussions)
