### ISSUE TITLE
The last ut test of the QDQBert model ”test_inference_no_head_absolute_embedding” did not pass when using official safetensors

### ISSUE THREAD

**Issue by jiangyichen830** [huggingface/transformers#31486]
### System Info

- `transformers` version: 4.41.2
- Platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.31
- Python version: 3.9.17
- Huggingface_hub version: 0.23.2
- Safetensors version: 0.4.3
- Accelerate version: 0.21.0
I want use qdqbert but found when i copy from commit version "[update ruff version (](https://github.com/huggingface/transformers/commit/673440d073d5f534a6d6bedeeca94869afd8d0a7)https://github.com/huggingface/transformers/pull/30932[)]" in [transformers](https://github.com/huggingface/transformers/tree/fd3c128040561a9f67abaf6af30f8b50029ff083)/[tests](https://github.com/huggingface/transformers/tree/fd3c128040561a9f67abaf6af30f8b50029ff083/tests)/[models](https://github.com/huggingface/transformers/tree/fd3c128040561a9f67abaf6af30f8b50029ff083/tests/models)/[qdqbert](https://github.com/huggingface/transformers/tree/fd3c128040561a9f67abaf6af30f8b50029ff083/tests/models/qdqbert)
/test_modeling_qdqbert.py, the test named "test_inference_no_head_absolute_embedding" could not pass and has a big difference, even needs to modify the accuracy from 1e-4 to 7e-2 in order to pass. I didn't make any changes, I just ran pytest - v. I want to know what caused such a large accuracy error

### Who can help?

@ArthurZucker @younesbelkada @amyeroberts 
Hope i can get your help to solve this problem. Thanks!

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just find a code version with qdqbert model, such as what I mentioned above. Then run the command `pytest -v tests/models/qdqbert/` also remember RUN_SLOW=1 and you will find the error. 

### Expected behavior

The result of my local run is [[[ 0.4352, -0.0278,  0.8552],[ 0.2360, -0.0271,  0.8560],[ 0.2916, -0.0897,  0.7542]]], but the expected result in source code was [[[0.4571, -0.0735, 0.8594], [0.2774, -0.0278, 0.8794], [0.3548, -0.0473, 0.7593]]]. There is a huge difference  between the two results.

**Comment by jiangyichen830** [comment]
These are two screenshots of my test results.
![1718727950295](https://github.com/huggingface/transformers/assets/171898603/7b11cbd3-3ac7-42a8-ba36-11ec618dec84)
![6e-2](https://github.com/huggingface/transformers/assets/171898603/1f514f05-95d5-4541-846c-2659dfdd0bb0)

**Comment by amyeroberts** [comment]
Hi @jiangyichen830, thanks for raising an issue! 

QDQBert has been deprecated, and so we won't be accepting updates to the model and will not longer run tests for the model.

The differences you're seeing could be for a variety of different reasons e.g. the running hardware or other libraries installed in the environment.
