### ISSUE TITLE
ImportError: cannot import name 'logging' from 'huggingface_hub'

### ISSUE THREAD

**Issue by zyc1128** [huggingface/transformers#31492]
### System Info

from transformers import AutoTokenizer,AutoModelForCausalLM
all dependencies have the latest versions

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1

### Expected behavior

1

**Comment by amyeroberts** [comment]
Hi @zyc1128, thanks for opening an issue! 

I'm unable to replicate this problem and can run `from transformers import AutoTokenizer,AutoModelForCausalLM` without issue. 

> all dependencies have the latest versions
This is underspecified. For example, is "latest" nightly builds or stable release? Which dependencies (it depends how you are using the library). The best way to get this information is by running `transformers-cli env` in the terminal.

Could you share a full traceback of the error?

**Comment by RUFFY-369** [comment]
Hi @zyc1128 please try upgrading `huggingface-hub` with `pip install --upgrade huggingface-hub` and also restart your kernel or session after doing so
