### ISSUE TITLE
from_pretrained 加载checkpoint过慢的问题

### ISSUE THREAD

**Issue by zhaoyuchen1128** [huggingface/transformers#31515]
### System Info

latest python3.9.8

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

我用ollama加载模型明显比上述方法快，有没有办法可以提高加载速度

### Expected behavior

1

**Comment by ArthurZucker** [comment]
嘿！您能分享一下您如何呼叫“from_pretrained”的片段嗎？ 
如果你安裝了“accelerate”，它應該會快很多！

**Comment by mmy814446-dev** [comment]
> 嘿！您能分享一下您如何呼叫“from_pretrained”的片段嗎？ 如果你安裝了“accelerate”，它應該會快很多！

I have already installed accelerate but the process is still slow.
