### ISSUE TITLE
gh: consider `i18n`

### ISSUE THREAD

**Issue by SauravMaheshkar** [huggingface/transformers#31542]
### Feature request

Perhaps we could move the translated versions of the README to a `i18n/` repository.

### Motivation

AFAIK this is considered to be the usual place for translations, viz. https://github.com/supabase/supabase/blob/master/i18n/languages.md

### Your contribution

Happy to submit a PR if interested

**Comment by amyeroberts** [comment]
cc @stevhliu

**Comment by stevhliu** [comment]
Good idea! Feel free to open a PR for it 🙂
