### ISSUE TITLE
When running `ruff format src/transformers`, some files needs to be reformatted

### ISSUE THREAD

**Issue by aliencaocao** [huggingface/transformers#31547]
### Feature request

Should a PR be made to fix those?
Here is a list as of https://github.com/huggingface/transformers/commit/74a207404e8d4524d1fdc4aa23789694f9eef347
![image](https://github.com/huggingface/transformers/assets/20109683/93adbfd5-e7a5-4270-931e-e1d297104101)

### Motivation

Simply workflows so that one can run `ruff format` and expect all changes made by it to be relevant to uncommitted work.

### Your contribution

I can make a PR

**Comment by amyeroberts** [comment]
Hi @aliencaocao, thanks for opening this issue! 

If you run `ruff format` directly, you might see many files to be updated. When we run `make fixup` it only runs ruff on the files which are being modified in the PR. This is OK, we don't necessarily want to have many diff which just update formats whenever ruff or our settings are updated.

**Comment by aliencaocao** [comment]
Alright,  thanks
