### ISSUE TITLE
Transformers master version breaks compatibility with `torch<2.3`

### ISSUE THREAD

**Issue by WeichenXu123** [huggingface/transformers#31563]
### System Info

transformers master version: `pip install git+https://github.com/huggingface/transformers`
torch version < 2.3, e.g. `pip install "torch==2.2"`
python 3.9
Ubuntu 22.04

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers.utils.import_utils import is_torch_xpu_available

is_torch_xpu_available(check_device=True)
```
raises error `AttributeError: module 'torch' has no attribute 'xpu'`

```
>>> from transformers.utils.import_utils import is_torch_xpu_available
>>> is_torch_xpu_available(check_device=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weichen.xu/miniconda3/envs/mlflow/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 765, in is_torch_xpu_available
    _ = torch.xpu.device_count()
  File "/home/weichen.xu/miniconda3/envs/mlflow/lib/python3.9/site-packages/torch/__init__.py", line 1932, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'xpu'
```

### Expected behavior

No error raised but return `False`

**Comment by amyeroberts** [comment]
Hi @WeichenXu123, thanks for reporting! 

I've opened #31573 which should fix this
