### ISSUE TITLE
`pip install accelerate` (and similar) error messages should specify min version

### ISSUE THREAD

**Issue by mikelmcdaniel** [huggingface/transformers#31583]
### System Info

- `transformers` version: 4.41.2
- Platform: Linux-5.15.0-97-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.3
- Accelerate version: 0.31.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 1.12.1+cu102 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@muellerzr

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Have accelerate installed at a low version (e.g. 0.10.0)
2. Run the following code:
```python
import torch
from transformers import pipeline

pipe = pipeline("text-generation", model="TinyLlama/TinyLlama-1.1B-Chat-v1.0", torch_dtype=torch.bfloat16, device_map="auto")
```
3. Error message "ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`" pops up

Ideally, the error message would be "ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.21.0'`"

---

### Expected behavior

Error message would specify the `utils.import_utils.ACCELERATE_MIN_VERSION`:

"ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.21.0'`"

**Comment by mikelmcdaniel** [comment]
Potential fix (that I didn't test): https://github.com/mikelmcdaniel/transformers/commit/157e20f9a57b097b4c756558d12834696527ebb3

**Comment by muellerzr** [comment]
Yes agreed, I'm reworking the imports today so I'll make sure to run through any accelerated-related errs like this to specify min versions :)
