### ISSUE TITLE
urgent - ROBERTA on WSC

### ISSUE THREAD

**Issue by abhyuday3jagannatha** [huggingface/transformers#3161]
Hi
I am looking for how to run ROBERTA on WSC data, similar to the example in fairseq:
https://github.com/pytorch/fairseq/tree/master/examples/roberta

However, fairseq is hard to use and modify and I really appreciate if you could add this to your great repo
thanks

**Comment by julien-c** [comment]
The conversion script should pretty much work out of the box, so feel free to do it and we welcome a PR (and we can upload the converted weights to our S3)

**Comment by abhyuday3jagannatha** [comment]
which script you mean? sorry i did not get it. i think this is not possible
to train it on huggingface is this?
