### ISSUE TITLE
`convert_wav2vec2_original_pytorch_checkpoint_to_pytorch.py` does not work due to weight norm key

### ISSUE THREAD

**Issue by gau-nernst** [huggingface/transformers#31633]
### System Info

NA

### Who can help?

@sanchit-gandhi

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Fairseq uses `nn.utils.weight_norm()`, which produces `weight_g` and `weight_v` keys

https://github.com/facebookresearch/fairseq/blob/d9a627082fd03ec72a27a31a4e56289bfcb2e4e4/fairseq/models/wav2vec/wav2vec2.py#L939

The weight conversion script assumes this old-style weight norm

https://github.com/huggingface/transformers/blob/2daf2c3eaa2992018b8d1ceb3421f5baa649bad5/src/transformers/models/wav2vec2/convert_wav2vec2_original_pytorch_checkpoint_to_pytorch.py#L118-L121

Thus, the weight conversion script will fail since `transformers` has switched to `nn.utils.parametrizations.weight_norm` for quite some time, which produces `parametrizations.weight.original0` and `parametrizations.weight.original1` keys instead.

https://github.com/huggingface/transformers/blob/1218e439b5fe05423693407653a1fb064263fef4/src/transformers/models/wav2vec2/modeling_wav2vec2.py#L392-L394

Thus the weight conversion script should be updated accordingly.

### Expected behavior

Weight conversion script works.

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi

**Comment by gau-nernst** [comment]
I had something working for me. f you don't have time to look into it, I can open a PR. I can provide a snippet to test it with some original fairseq checkpoints too. I

**Comment by amyeroberts** [comment]
@gau-nernst Yes please, that would be great cc @kamilakesbi too :)
