### ISSUE TITLE
wrong configuration of ALBERT xlarge

### ISSUE THREAD

**Issue by ZheyuYe** [huggingface/transformers#3164]
# 🐛 Bug

## Information
If you are **reproducing** the  [ALBERT](https://github.com/google-research/albert), the `num_attention_heads` of albert xlarge should be 32 instead of 16 as
https://github.com/huggingface/transformers/blob/db9279dedbb9c5e7d24569a1ac3f74f9d5c3eb18/src/transformers/configuration_albert.py#L27

**Comment by LysandreJik** [comment]
Where did you get 32 from?

The [official file ](https://tfhub.dev/google/albert_xlarge/2)says 16.

**Comment by ZheyuYe** [comment]
Well, the model configuration from TF Hub shows 32

**Comment by LysandreJik** [comment]
Indeed, that's right. I'll follow the issue you opened https://github.com/google-research/ALBERT/issues/180 and act accordingly.
