### ISSUE TITLE
Reason for speedup

### ISSUE THREAD

**Issue by mamesmak** [huggingface/transformers#3165]
I used to develop a code based on the pytorch_transformers package (v1.1) and now transfering to the current version. I see a 2x speedup in Bert run_glue.py. Wondering what is the major reason? Looking at the code, I couldn't find major differences.

**Comment by BramVanroy** [comment]
Depending on which version you are using, it might be that you are using the fast [tokenizers ](https://github.com/huggingface/tokenizers) library which offers a much improved tokenizer interface built on Rust.

**Comment by mamesmak** [comment]
Thanks for the reply. I don't think it is because of the tokenizer. I measured the encoder part and see huge improvement in the encoder speed. Still cannot figure out the difference. comparing pytorch-transformers 1.1 with transformers 2.5.1.

**Comment by BramVanroy** [comment]
It is unlikely that there have been architecture changes, but it might be caused by a different torch/tensorflow version? Are you testing both transformers versions on the same framework version? It is likely that this is caused by an optimisation of an activation function.
