### ISSUE TITLE
[Bug] Modifying normalizer for pretrained tokenizers don't consistently work

### ISSUE THREAD

**Issue by alvations** [huggingface/transformers#31653]
### System Info

transformers==4.41.2

### Who can help?

 @ArthurZucker

### Reproduction

From https://github.com/huggingface/tokenizers/issues/1552#issue-2348487489

```python
from transformers import AutoTokenizer
from tokenizers.normalizers import Sequence, Replace, Prepend

tokenizer_name = "mistralai/Mistral-7B-v0.1"
old_tok = AutoTokenizer.from_pretrained(tokenizer_name)

assert old_tok.backend_tokenizer.normalizer != None

new_normalizer = Sequence(
    [Prepend('▁'), Replace('▁', ' '), Replace("foo", "bar"), Replace('<br>', '\n')]
)

old_tok.backend_tokenizer.normalizer = new_normalizer
new_tokenizdr_name = f"new_tokenizer-{tokenizer_name}"
old_tok.save_pretrained(new_tokenizdr_name)


old_tok = AutoTokenizer.from_pretrained(tokenizer_name)
new_tok = AutoTokenizer.from_pretrained(new_tokenizdr_name)
```

[out]:

```
>>> print(' '.join(old_tok.batch_decode(old_tok("I foo you<br>hello world")['input_ids'])))
<s> I foo you < br > hello world

>>> print(' '.join(new_tok.batch_decode(new_tok("I foo you<br>hello world")['input_ids'])))
<s>  I  bar  you 
 hello  world
```

The same process above won't work for `"mistralai/Mistral-7B-v0.3"`.

But if we reinitialize with `__class__` after the `.from_pretrained` it loads the tokenizer config correctly with the extended normalizer. https://stackoverflow.com/questions/78612251/how-do-we-add-modify-the-normalizer-in-a-pretrained-huggingface-tokenizer/78624238#78624238

### Expected behavior

The same `.from_pretrained` should work for other model's tokenizers after changes to the normalizer.

**Comment by ArthurZucker** [comment]
Hey! This is not because you can't change it, but because it already has a normalizer. 
<img width="493" alt="image" src="https://github.com/huggingface/transformers/assets/48595927/579d7a75-d48c-499c-957f-9464871e9667">
This is the `"legacy"` version of the tokenizer. This should be fixed soon btw.

**Comment by alvations** [comment]
After the fix, does that mean that we cannot add new normalizers to pretrained tokenizers (if they don't already have one), e.g. 

```
from transformers import AutoTokenizer
from tokenizers.normalizers import Sequence, Replace, Prepend

tokenizer_name = "mistralai/Mistral-7B-v0.3"
old_tok = AutoTokenizer.from_pretrained(tokenizer_name)

assert old_tok.backend_tokenizer.normalizer != None

new_normalizer = Sequence(
    [Prepend('▁'), Replace('▁', ' '), Replace("foo", "bar"), Replace('<br>', '\n')]
)

old_tok.backend_tokenizer.normalizer = new_normalizer
new_tokenizdr_name = f"new_tokenizer-{tokenizer_name}"
old_tok.save_pretrained(new_tokenizdr_name) # New tokenizer with normalizer.
```
