### ISSUE TITLE
flash attention support for chatglm3-6b

### ISSUE THREAD

**Issue by elimsjxr** [huggingface/transformers#31652]
Is there anyone working on a FlashAttention support for chatglm3-6b?

**Comment by amyeroberts** [comment]
Hi @elimsjxr, thanks for opening this issue! 

As the modeling code for [ChatGLM3-6B](https://huggingface.co/THUDM/chatglm3-6b/blob/main/modeling_chatglm.py) is hosted on the hub, the best place to request this feature is by opening a [discussion on the community tab](https://huggingface.co/THUDM/chatglm3-6b/discussions), directly on the checkpoint's page on the hub.
