### ISSUE TITLE
[BERT] Implementation of the sliding window for long sequences

### ISSUE THREAD

**Issue by wasiahmad** [huggingface/transformers#3166]
I was trying to look for the references where the sliding window is implemented to process long sequences. How do we split a long sequence and then after getting the embeddings, how do we unpack them? I am unable to find the code segments that handle these operations.

Also, is it possible to describe the main trick? I am trying to implement it in plain PyTorch. I am unable to implement in Batches without running any loops.

Any help would be appreciated.

**Comment by kruthikakr** [comment]
I have the same issue.. anyone has any inputs on this
