### ISSUE TITLE
meta-llama/Llama-2-7b-chat-hf tokenizer `model_max_length` attribute needs to be fixed.

### ISSUE THREAD

**Issue by rohitdwivedula** [huggingface/transformers#31705]
### System Info

transformers==4.42.3, python3.9.19

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python3
import transformers
tokenizer = transformers.AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
print(tokenizer.model_max_length)
```

This outputs `1000000000000000019884624838656`

### Expected behavior

Expected output should be `4096` since that is the max sequence length of this specific Llama model.

**Comment by LysandreJik** [comment]
Hey @rohitdwivedula, sorry for the overdue response! The best thing to do here would be to open a PR on this repository on the Hub changing that attribute. Would you mind doing this if you have the bandwidth?

**Comment by rohitdwivedula** [comment]
@LysandreJik okay, will open a PR.
