### ISSUE TITLE
Phi3SmallForCausalLM missing?

### ISSUE THREAD

**Issue by 0wwafa** [huggingface/transformers#31719]
I can't find the Phi3SmallForCausalLM definitions.

**Comment by amyeroberts** [comment]
The model is defined on the hub: https://huggingface.co/microsoft/Phi-3-small-128k-instruct/blob/f80aaa30bfc64c2b8ab214b541d9050e97163bc4/modeling_phi3_small.py#L898

**Comment by 0wwafa** [comment]
> The model is defined on the hub: https://huggingface.co/microsoft/Phi-3-small-128k-instruct/blob/f80aaa30bfc64c2b8ab214b541d9050e97163bc4/modeling_phi3_small.py#L898

Thanks.
