### ISSUE TITLE
how to remove kv cache?

### ISSUE THREAD

**Issue by TuuSiwei** [huggingface/transformers#31717]
### Feature request

When I use the generate() function of a language model for inference, the kv-cache is also stored in the GPU memory. Is there any way to clear this kv-cache before continuing to call generate()?

### Motivation

I have a lot of text to process, so I use a for loop to call generate(). To avoid OOM, I need to clear the kv-cache before the end of each loop iteration.

### Your contribution

none

**Comment by amyeroberts** [comment]
Hi @tsw123678, you should be able to pass in `use_cache=False` when calling `generate`. Note, this will result in significant slow downs when generating

**Comment by tsw123678** [comment]
> Hi @tsw123678, you should be able to pass in `use_cache=False` when calling `generate`. Note, this will result in significant slow downs when generating

thank you for your tips. since I need to handle a large number of conversations (over 10,000), I can't afford to sacrifice the time for kv cache. I just want to know if there is a way to clear the current kv cache after generate function.

**Comment by tsw123678** [comment]
year, my loop code can be simplified as follows:
```python
user_prompt=[prompt 1, prompt 2, prompt 3 .... prompt n]

for prompt in user_prompt:
    input_ids=tokenizer.encode(prompt)
    out=model.generate(prompt)
    res=tokenizer.decode(out)
    # some IO operation to save the result
    
    del input_ids,out,res
    torch.cuda.empty_cache()
```
I've noticed that deleting variables such as input_ids that are located on CUDA does not prevent the OOM issue. After my analysis, I believe that the accumulation of the KV cache is the cause of the OOM problem. Thank you very much for your help.

**Comment by tsw123678** [comment]
> Hi @tsw123678, to be able to help, you would need to clarify the construction of the loop i.e. what's being looped over.
> 
> I'm I right in understanding that the GPU memory is not freed after a generate call?
> 
> cc @gante

year, my loop code can be simplified as follows:
```python
user_prompt=[prompt 1, prompt 2, prompt 3 .... prompt n]

for prompt in user_prompt:
    input_ids=tokenizer.encode(prompt)
    out=model.generate(prompt)
    res=tokenizer.decode(out)
    # some IO operation to save the result
    
    del input_ids,out,res
    torch.cuda.empty_cache()
```
I've noticed that deleting variables such as input_ids that are located on CUDA does not prevent the OOM issue. After my analysis, I believe that the accumulation of the KV cache is the cause of the OOM problem. Thank you very much for your help.

**Comment by swtb3** [comment]
Hi folks, has there been any development on this? I am having an issue, described here: https://discuss.huggingface.co/t/kv-cache-managment/95481

I believe it is down to the static KV cache. Note I do not seem to experience any OOM and GPU utilisation stays at 20Gb/40Gb. Inference does just stop and leaves the process hanging. It would be nice to see some more practical documentation around this feature as it is not clear how to use/manage it beyond typical use.

**Comment by amyeroberts** [comment]
Also cc @ArthurZucker re cache

**Comment by ArthurZucker** [comment]
You can also just delete the cache as it is an object returned by generate as well !

**Comment by prasiyer** [comment]
@ArthurZucker - Can you pls share more instructions for deleting the cache returned by model.generate()? I am experiencing OOM error with iterative inference. I would like to clear the cache after certain number of iterations

**Comment by ArthurZucker** [comment]
Hey! Actually 2 things you can do:
1. set the `max_new_tokens` to a specific number. Once done you just clear the cache and re-generate. This should not induce recompile AFAIK
2. Use the awesome `offloaded static cache` which will automatically offload the cache. To avoid OOMs that's where you should go! https://huggingface.co/docs/transformers/main/en/kv_cache#offloaded-static-cache
