### ISSUE TITLE
Do we have a whole-word-masked version of BERT?

### ISSUE THREAD

**Issue by ridiculouz** [huggingface/transformers#3171]
# ❓ Questions & Help

## Details

Thanks for the excellent work! But I'm wonder is there a whole-word-masked version of BERT? Moreover, how can I adapt the Tokenizer class to make it support other parsing method (e.g. In Chinese the BERTTokenizer simply parses the sequences in character level, while parser like jieba can parse them into Chinese words. How can I keep the features of Tokenizer class while using other parsing method?)?

**Comment by LysandreJik** [comment]
Yes, there are a few available on the hub, you can search for [whole word masking](https://huggingface.co/models?search=whole-word-masking) or [wwm](https://huggingface.co/models?search=wwm).

For your second question, you would have a better answer if you opened an issue on [huggingface/toeknizers](https://github.com/huggingface/tokenizers/issues) instead.
