### ISSUE TITLE
Get the CNN/Daily Mail Data for BART

### ISSUE THREAD

**Issue by acarrera94** [huggingface/transformers#3173]
@sshleifer
In the README for the BART summarization it says: 

> download both CNN and Daily Mail datasets from Kyunghyun Cho's website
`tar -xvf cnn_stories.tgz && tar -xvf dailymail_stories.tgz`
> this should make a directory called cnn_dm/ with files like test.source. To use your own data, copy that files format. Each article to be summarized is on its own line.

This doesn't produce a cnn_dm directory, it produces two different folders. The contents of the folders are `text.story` files, not `test.source`. 

Did you use [this repo](https://github.com/artmatsak/cnn-dailymail)? 
Or did you get the data from somewhere else? 

Happy to submit a PR either way!
Thanks!

**Comment by sshleifer** [comment]
Its a typo in the docs. I just used cnn.
