### ISSUE TITLE
How can I assign a specific gpu when using examples/run_language_modeling.py?

### ISSUE THREAD

**Issue by ridiculouz** [huggingface/transformers#3174]
# ❓ Questions & Help

## Details

Hello, I'm wondering if I can assign a specific gpu when using examples/run_language_modeling.py to train a language model?
Lots of thanks!

**Comment by patrickvonplaten** [comment]
This might answer your question: https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on
