### ISSUE TITLE
Transformer compatibility Python 3.9, ComfyUI

### ISSUE THREAD

**Issue by davedaverave** [huggingface/transformers#31806]
### System Info

Paperspace A6000, A10080GB, Python 3.9, ComfyUI with Lastben Repository

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm running ComfyUI, i have isntalled Wassquatch as an addon, it doesn't work because cannot import name 'BlipProcessor' from 'transformers',  you support but 3.8+ but is erroring me...

### Expected behavior

Transformer would import correctly bliprocessor in my enviroment of py 3.9

**Comment by LysandreJik** [comment]
Hey @davedaverave, normally this should work seamlessly on 3.9, we test up to 3.8. What's the transformers version under the hood?

**Comment by davedaverave** [comment]
Hi the transformer version is 4.42.3
