### ISSUE TITLE
Add support for GGUF Phi-3

### ISSUE THREAD

**Issue by dabs9** [huggingface/transformers#31826]
### Model description

Model is Phi-3 saved as a GGUF.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

It would be the analog of this recent PR but for Phi 3: https://github.com/huggingface/transformers/commit/e4628434d854ddfb5c002a6cc00b4eb4f22b7df2#diff-55e3debce4586d986257d1b1acb48c8708504f4b3b63e413e89f27ac2cc738b3

**Comment by amyeroberts** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
Hey @dabs9, thanks for showing interest in GGUF integration with Phi-3 model ! I will try to tackle this when I get the time but I highly encourage you to do the integration yourself if you have the time ! As you saw from the Qwen integration, this should be fairly straightforward. I will mark it as a first good issue in case a community member is interested.

**Comment by a8nova** [comment]
Hello @SunMarc @amyeroberts - if nobody started on this, i would like to contribute to this

**Comment by SunMarc** [comment]
Hi @a8nova, feel free to add the gguf path for phi3 ! Following Qwen integration should be good enough indeed ! I'll try to help if you need any help ! If the integration is harder than expected, we might write a guide on how to add gguf path. Let us know how it goes !

**Comment by a8nova** [comment]
Perfect, I created an initial PR: https://github.com/huggingface/transformers/pull/31844. There is an 11 year old programmer(my intern) that already knows some python and I think this will be a great first issue for him, of course i will guide him and I will get help from you guys on things that are not clear, thanks!

**Comment by anasir3003** [comment]
how can i contribute to this?
