### ISSUE TITLE
About the examples document of bert with SQuAD 2.0

### ISSUE THREAD

**Issue by Kuntvez** [huggingface/transformers#3183]
I'm wondering if there is a mistake.
In the README document of /examples, the training parameters setting for training on SQuAD dataset, the first code block:
```
export SQUAD_DIR=/path/to/SQUAD

python run_squad.py \
  --model_type bert \
  --model_name_or_path bert-base-cased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file $SQUAD_DIR/train-v1.1.json \
  --predict_file $SQUAD_DIR/dev-v1.1.json \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /tmp/debug_squad/
```
Because this model is bert-base-cased, which means it's cased, I think the ``--do_lower_case`` shouldn't be here. Is that a mistake?

**Comment by LysandreJik** [comment]
Indeed, I think this is a mistake, I think it should be `bert-base-uncased` instead. I'm updating it.
