### ISSUE TITLE
`Failed to build tokenizers` when installing 2.5.1 version.

### ISSUE THREAD

**Issue by RileyShe** [huggingface/transformers#3184]
`Failed to build tokenizers` when i try to install transformers==2.5.1

`Failed to build tokenizers` when i try to install tokenizers == 0.5.2

so, i want to know `tokenizers == 0.5.2` is must ?

thanks~

**Comment by BramVanroy** [comment]
`tokenizers` is only required when you wish to use the new, fast [tokenizers](https://github.com/huggingface/tokenizers). By default, though, the standard (slower) tokenizers are used. So you do not actually need the `tokenizers` library to run the `transformers` library.

Related:
https://github.com/huggingface/transformers/issues/2980
https://github.com/huggingface/transformers/issues/2831

**Comment by julien-c** [comment]
Can you please open an issue over at https://github.com/huggingface/tokenizers with your OS/Python details?

**Comment by GuruPavanKalyan** [comment]
while I am installing transformer==4.4, I am facing issue: Failed to build tokenizers.
