### ISSUE TITLE
is_flash_atten_avaiable were wrong

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#31877]
I am on V100, but this function gives me True, it just detects if flash-atten installed or not but not considered the GPU support or not.

Consider add GPU identificate as well? (compute capcitiy)

**Comment by amyeroberts** [comment]
Hi @lucasjinreal, thanks for opening this feature request! 

This is outside the scope of `is_flash_attention_available`. The `is_xxx_available` functions are meant to provide boolean controls checking whether a package is installed in an environment, which is exactly what it does. 

Support for different hardwares is hard to track and this behaviour would likely be difficult to maintain (we'd have to monitor downstream changes and have many controls for all the different versions and hardware combinations and their compatibilities)

**Comment by lucasjinreal** [comment]
Is there any way to count hardware in? from transfomrers utils or something.

this is a common, since flashatten even installed can not be calculate on V100

**Comment by amyeroberts** [comment]
@lucasjinreal Unfortunately there's so many different types of hardware, and with that some many different types of software e.g. cuda kernels, it's not feasible to reliably detect and monitor this - as well as keep up to date with any changes in their support or new hardware being release. In addition, checking hardware itself isn't as straightforward as install libraries and likely to be brittle. It's better to let each library e.g. flash-attention manage their own support and documentation, as this will be more robust than trying to do everything automatically.

**Comment by lucasjinreal** [comment]
so, it is clear that is_flash_attn_avaiable only detect if flashattn installed or not?

**Comment by amyeroberts** [comment]
Yes, it will detect if it is installed in the environment, but it won't tell you whether it's compatible with the hardware you're running on or other libraries
