### ISSUE TITLE
Re-initialize decoder parameters of a pretrained model

### ISSUE THREAD

**Issue by antopost** [huggingface/transformers#31883]
What is the recommended way of re-initializing only the decoder weights of a pretrained model?
In the case of Mask2Former I noticed that it has a different [weight initializing method](https://github.com/huggingface/transformers/blob/97aa3e2905aac867952d89a7d13851d8adb7861c/src/transformers/models/mask2former/modeling_mask2former.py#L2135) depending on the layer.
```

from transformers import AutoModel

mask2former_model = AutoModel.from_pretrained("facebook/mask2former-swin-tiny-cityscapes-panoptic")

# re-initialize decoder weights...

```

**Comment by amyeroberts** [comment]
Hi, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by antopost** [comment]
Thanks, I'll try the forum.
