### ISSUE TITLE
[Tokenizer][bug] LLAVA 1.6 tokenizer problem

### ISSUE THREAD

**Issue by lanking520** [huggingface/transformers#31901]
### System Info

Any OS system that can run transformers

related issue: https://github.com/vllm-project/vllm/issues/6224

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

transformers (4.42.3) and got the issue

```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("llava-hf/llava-v1.6-34b-hf")
print(tokenizer.encode("<image>"))

print(tokenizer.vocab_size)
```

output

```
[64003]
64000
```

Can confirm transformers (4.40.1) does not have this issue

```
[64000]
64000
```

### Expected behavior

It is supposed to be the same?

```
[64000]
64000
```

**Comment by DarkLight1337** [comment]
After trying this code on a few different versions, it looks like this got changed between 4.41.2 and 4.42.0.

**Comment by DarkLight1337** [comment]
Also, this issue only occurs for `llava-hf/llava-v1.6-34b-hf`. It works fine for `llava-hf/llava-v1.6-mistral-7b-hf` and `llava-hf/llava-v1.6-vicuna-7b-hf`.

**Comment by zucchini-nlp** [comment]
Answered in https://github.com/huggingface/transformers/issues/31713#issuecomment-2222139329

**Comment by zucchini-nlp** [comment]
Closing because #31902 was merged
