### ISSUE TITLE
`target_sizes` in Owlv2 `post_process_image_guided_detection`

### ISSUE THREAD

**Issue by catalys1** [huggingface/transformers#31915]
### System Info

N/A

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

In `post_process_image_guided_detection` ([link](https://github.com/huggingface/transformers/blob/main/src/transformers/models/owlv2/image_processing_owlv2.py#L544C9-L544C44)), there's no check for when `target_sizes = None`, so calling it without providing `target_sizes` raises an error.

### Expected behavior

The case where `target_sizes` is `None` should be handled, as done in `post_process_detection` ([link](https://github.com/huggingface/transformers/blob/main/src/transformers/models/owlv2/image_processing_owlv2.py#L484))

**Comment by amyeroberts** [comment]
Hi @catalys1, thanks for raising! Would you like to open a PR to address this? This way you get the github contribution for spotting the error and the fix

**Comment by catalys1** [comment]
I've submitted a pull request
