### ISSUE TITLE
Add Depth Anything v2 metric depth

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#31972]
### Feature request

We already have [Depth Anything v2](https://huggingface.co/docs/transformers/main/en/model_doc/depth_anything_v2) available in Transformers (compatible with v1). These are relative depth estimation models, capable of predicting the relative distance among pixels.

There are also absolute (also called metric) depth estimation models available here: https://github.com/DepthAnything/Depth-Anything-V2/tree/main/metric_depth. Would be great to make these also Transformers compatible.

The author also informed me that they are only minor differences compared to their relative counterparts:

> Our model definition for metric depth model in V2 is almost similar to our relative depth model: https://github.com/LiheYoung/Depth-Anything/blob/main/depth_anything/dpt.py. The only difference is we replace the final ReLU(out) (https://github.com/LiheYoung/Depth-Anything/blob/1e1c8d373ae6383ef6490a5c2eb5ef29fd085993/depth_anything/dpt.py#L99) to a sigmoid(out) * max_depth.

### Motivation

We currently only have one metric depth estimation model available, namely [ZoeDepth](https://huggingface.co/docs/transformers/main/en/model_doc/zoedepth). Would be great to expand this to more SOTA models

### Your contribution

Could work on this, but it's a great opportunity for a first open-source contribution!

**Comment by bt2513** [comment]
Hi! I am interested in taking this issue as a first contribution. Could I be assigned to it please? :) Thank you!

**Comment by NielsRogge** [comment]
Pinging @gchhablani here as he might be interested as well. You can just open a PR :)

**Comment by NouamaneELGueddarii** [comment]
Hi @NielsRogge, is this issue still open. I would like to work on it.

**Comment by bt2513** [comment]
Hi @NouamaneELGueddarii, I was planning to work on it since @gchhablani didn't reply :) hope that's good with you. Thanks

**Comment by dvolgyes** [comment]
As a personal remark: whoever works on it, it would be most helpful!

**Comment by anirudh2781998** [comment]
Hey first time contributor here! if the issue is still open I would like to work on it.

**Comment by elvistheyo** [comment]
@NielsRogge is this available on huggingface now?

**Comment by NielsRogge** [comment]
Yes, models are here: https://huggingface.co/models?other=absolute+depth

**Comment by NielsRogge** [comment]
Hi @elvistheyo it would be great to add documentation around this. Would be up for adding a PR?

**Comment by frittatelle** [comment]
HI! is there a onnx model version of https://huggingface.co/docs/transformers/en/model_doc/depth_anything_v2? I'm not finding it, but it would be very useful.

**Comment by NielsRogge** [comment]
I'll ping @xenova on that

**Comment by xenova** [comment]
Hi there @frittatelle  👋  Yes, I made a couple of conversions for them here:
- https://huggingface.co/onnx-community/depth-anything-v2-small
- https://huggingface.co/onnx-community/depth-anything-v2-base
- https://huggingface.co/onnx-community/depth-anything-v2-large

:) Hopefully they work for your use-cases!

**Comment by frittatelle** [comment]
Hi @xenova ☺️, are those onnx conversions from the metric depth ones? If that's not the case I'll try to work on them in a new PR as soon as I can ✌🏼

**Comment by xenova** [comment]
Oh right, I haven't made conversions for those (https://huggingface.co/models?other=absolute+depth,depth_anything). Would appreciate some contributions!
