### ISSUE TITLE
ValueError: InternVLChatModel does not support Flash Attention 2.0 yet.

### ISSUE THREAD

**Issue by dszpr** [huggingface/transformers#32016]
### System Info

transformers version: 4.37.2
flash-attn version: 2.3.1post1/2.6.1(latest version)

### Who can help?

@ArthurZucker @muellerzr @SunMarc

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Hi! I am finetuning InternVL2-26B based on LLaVA training code. And I modified the model loading code as below:
            model = transformers.AutoModel.from_pretrained(
                '/workspace/vlm_dataset/InternVL/InternVL2-26B',
                cache_dir=training_args.cache_dir,
                attn_implementation=attn_implementation,
                torch_dtype=(torch.bfloat16 if training_args.bf16 else None),
                trust_remote_code=True,
                **bnb_model_from_pretrained_args
            )
And an error occurred:
ValueError: InternVLChatModel does not support Flash Attention 2.0 yet. Please request to add support where the model is hosted, on its model hub page: https://huggingface.co//workspace/vlm_dataset/InternVL/InternVL2-26B/discussions/new or in the Transformers GitHub repo: https://github.com/huggingface/transformers/issues/new
I also tried the latest version of transformers and flash-attention, and this error still occurs. 
Is this error concerned with transformers or flash-attention or InternVL2?

### Expected behavior

In transformers, InternVLChatModel support Flash Attention 2.0

**Comment by amyeroberts** [comment]
Hi @dszpr, thanks for raising an issue! 

It seems you're working from a local model, but I'm assuming it's a download of [OpenGVLab/InternVL2-26B](https://huggingface.co/OpenGVLab/InternVL2-26B/tree/main). As the modeling code is hosted on the hub, you should open a request to support flash attention on the [model's discussion page](https://huggingface.co/OpenGVLab/InternVL2-26B/discussions)

**Comment by dszpr** [comment]
Got it. Thanks a lot!
