### ISSUE TITLE
The ProgressCallback triggers a `cannot pickle '_thread.lock' object` failure

### ISSUE THREAD

**Issue by fozziethebeat** [huggingface/transformers#32064]
### System Info

Transformers version[v4.40.0](https://github.com/huggingface/transformers/releases/tag/v4.40.0) onward

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

With Transformers version[v4.40.0](https://github.com/huggingface/transformers/releases/tag/v4.40.0) onwards, [this commit ](https://github.com/huggingface/transformers/commit/766810153b3a701e99229229c3899e370be7b7a1) introduces a deep copy of logs before reporting progress.

When this deep copy happens *after* the [WandbCallback](https://github.com/huggingface/transformers/blob/b31d59504003c8140adf66a4077b1c50799fbe89/src/transformers/integrations/integration_utils.py#L728) runs, some wandb objects can't be picked.  Specifically, when TRL logs a [WandB table](https://github.com/huggingface/trl/blob/4e85bd75a9dfca0074eef3a90130054c283eed39/trl/trainer/dpo_trainer.py#L1558) , the `WandbCallback` mutates the table such that pickling breaks and ultimately the `ProgressCallback` fails with a stack trace documented [here](https://github.com/huggingface/trl/issues/1849).

I think the fix is to update [this commit](https://github.com/huggingface/transformers/commit/766810153b3a701e99229229c3899e370be7b7a1) to avoid doing any pickling.

### Expected behavior

WandB tables shouldn't be pickled when doing callbacks.

**Comment by amyeroberts** [comment]
Hi @fozziethebeat, thanks for reporting! 

Would you like to open a PR with the proposed fix? This way you get the github contribution for finding the solution

**Comment by fozziethebeat** [comment]
Sure, I see there's no unittesting (as far as I can tell) for this code path so let me try this out and manually test with an end to end trl run.

**Comment by fozziethebeat** [comment]
Done!

**Comment by amyeroberts** [comment]
Thanks! 

>Sure, I see there's no unittesting (as far as I can tell) for this code path so let me try this out and manually test with an end to end trl run.

Yes, the transformers team don't officially maintain the integrations with libraries like wandb, so we don't have a CI or tests for those. Thanks for adding the fix and manually checking!

**Comment by fozziethebeat** [comment]
Glad to fix this.  Had to wander through a lot of layers to figure out where this was being triggered.
