### ISSUE TITLE
Pipeline for Question Answering: How to return multiple correct answers output?

### ISSUE THREAD

**Issue by rcontesti** [huggingface/transformers#3207]
Very simple question I'm using transformer pipelines question answering on a very long piece of text. And, it is the cases that the are are multiple cases for the correct answer. I want them all.

I was wondering if I could retrieve the 10 best scores of output instead of just one.

Many thanks.

**Comment by gavishpoddar** [comment]
I need a solution to this problem as well please help

Thanks.

**Comment by casafurix** [comment]
@fumpe Can this work for sagemaker? Actually I am trying to deploy this pipeline in sagemaker, how can we customize the topk parameter in that? (As Sagemaker works a bit differently), Sagemaker currently returns only 1 answer, and am unable to modify the parameters to increase the number of returned items. Thank you.

This is my model and pipeline setup in Sagemaker:
hub = {
'HF_MODEL_ID':'valhalla/t5-base-qa-qg-hl',
'HF_TASK':'text2text-generation'
}
