### ISSUE TITLE
kwargs pop "attn_implement" twice in modeling_utils.py and configuration_utils.py when use AutoConfig/AutoModel

### ISSUE THREAD

**Issue by Hz188** [huggingface/transformers#32082]
### System Info
Pop “attn_implement” twice from modeling_utils.py and configuration_utils.py causes a bug in which attn_cls selection is affected.

<img width="1524" alt="image" src="https://github.com/user-attachments/assets/75bf7b84-e64a-4d0f-908f-d8e87ee5b1d7">

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

    config = AutoConfig.from_pretrained(
        "deepseek-ai/deepseek-moe-16b-base",
        hidden_size=32,
        intermediate_size=32,
        num_hidden_layers=2,
        num_attention_heads=8,
        # vocab_size=2000,
        first_k_dense_replace=1,
        attn_implementation="flash_attention_2",
        torch_dtype="float16",
        n_routed_experts=8,
        trust_remote_code=True,
    )
    model = transformers.AutoModel.from_config(config, trust_remote_code=True)

### Expected behavior
Set the implementation of attention to flash attention instead of sdpa

**Comment by amyeroberts** [comment]
Hi @Hz188, thanks for raising this! 

Looking into it 🕵️
