### ISSUE TITLE
max_length calculation for padding the generation outputs in the Seq2SeqTrainer prediction_step function 

### ISSUE THREAD

**Issue by JackCai1206** [huggingface/transformers#32095]
I think the calculation for the max_length is wrong when only `max_new_tokens` is provided. 

https://github.com/huggingface/transformers/blob/fe008d6ebea1f5770b740991daeefd9322fa434a/src/transformers/trainer_seq2seq.py#L318-L324

`generated_tokens.shape[-1]` is the sum of the lengths of the input and the generated tokens, so when you have `max_new_tokens`, the actual max length to pad to should be `generation_inputs['input_ids'].shape[-1] + gen_config.max_new_tokens`

Also, since `max_length` and `max_new_tokens` can come from either `gen_config` in the model and `gen_kwargs` provided as kwargs, we might want to handle both cases. 

Proposed change: 
```
        # Retrieves GenerationConfig from model.generation_config
        gen_config = self.model.generation_config
        # in case the batch is shorter than max length, the output should be padded
        max_length = max(
            max(gen_config.max_length or 0, gen_kwargs.get("max_length", 0)),
            generation_inputs['input_ids'].shape[-1] + max(gen_config.max_new_tokens or 0, gen_kwargs.get('max_new_tokens', 0))
        )
        if generated_tokens.shape[-1] < max_length:
            generated_tokens = self._pad_tensors_to_max_len(generated_tokens, max_length)
```

**Comment by amyeroberts** [comment]
cc @gante @zucchini-nlp

**Comment by zucchini-nlp** [comment]
@JackCai1206 Hey!

In this code snippet we're looking at Seq2Seq trainer so the `generated_tokens.shape[-1]` is always shape of the generated tokens. Your assumption would be correct for a Trainer class, but we currently do not support `predict_with_generate` there, it's work in progress.

> Also, since max_length and max_new_tokens can come from either gen_config in the model and gen_kwargs provided as kwargs, we might want to handle both cases.

Right, we should check both `kwargs` and `config`. But from the codebase I see that Trainer internally doesn't pass in any kwargs, so I guess this is the case only if you call `trainer.predict(*args, **kwargs)` on test set after training. We can have a fix for that by checking if `kwargs` has any max length set. In case we get max length set by `kwargs` and `config`, we should prob give priority to the `kwargs` and raise a warning. 

Would you like to open a PR for this?
