### ISSUE TITLE
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback): module 'tensorflow' has no attribute 'data'

### ISSUE THREAD

**Issue by Rizwanali324** [huggingface/transformers#32122]
im using following 
librosa
streamlit
pandas
soundfile
numpy
scipy
sounddevice
pydub
pyaudio
matplotlib
streamlit==1.36.0
transformers==4.41.2
torch==2.1
accelerate>=0.21.0
tensorflow==2.13.0
keras==2.13.1
deep-utils
noisereduce
datasets
evaluate
huggingface_hub
librosa
scikit-learn

and try to deploy my streamlit app but facing same in local and cloud as well

**Comment by amyeroberts** [comment]
Hi @Rizwanali324, thanks for opening an issue! 

Please make sure to follow the issue template and provide all the requested information such that someone can help you. This includes:
* The running environment: run `transformers-cli env` in the terminal and copy-paste the output
* A minimal code reproducer 
* Information about the expected and observed behaviour 
* All relevant error information including the full error traceback
