### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by Khaliq88** [huggingface/transformers#32121]
https://github.com/huggingface/transformers/blame/eb5601b0a5a88824a2598956f96e06e7f2422bce/src/transformers/training_args.py#L43

**Comment by amyeroberts** [comment]
@Khaliq88 As I have commented on a number of issues now, please stop creating issues which are seemingly nonsense. This is spam and reduces the experience of users and maintainers of the library. If you have a question or need help creating issues, please ask and we'd be happy to help. If this continues your account will be blocked.
