### ISSUE TITLE
Wav2Vec2ProcessorWithLM doesn't handle unknown token well for BPE

### ISSUE THREAD

**Issue by amritregmi26** [huggingface/transformers#32132]
### System Info

- `transformers` version: 4.42.3
- Platform: Linux-6.5.0-41-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.3

### Who can help?
@ArthurZucker 

### Information
My own modified scripts

### Tasks
My own task or dataset (give details below)

### Reproduction

1. Create and train a BPE tokenizer with continuing_word_prefix = "▁"
2. Create decoder with the same tokenizer labels
3. Initialize Wav2Vec2ProcessorWithLM with feature_extractor, bpe tokenizer and decoder
4. After the third step, it throws missing token error for this token '⁇'
5. When I checked the code for pyctcdecode they have UNK_BPE_TOKEN = "▁⁇▁" but in processor with lm this token is not handled correctly. 

### Expected behavior

For BPE tokenizer (identified by decoder._alphabet.is_bpe), the unk token should be ▁⁇▁ and not ⁇

**Comment by ArthurZucker** [comment]
Hey! Did you try simply setting the tokenizer.unk_token?

**Comment by amritregmi26** [comment]
Thank you for your response! I was curious why there is no dynamic handling for this part of the code. Is there any specific reason for not using the unk_bpe_token from pyctcdecoder? While I understand that the CTC architecture performs best with a character-level tokenizer, is that the reason for not incorporating this token?

I changed the source code and it worked perfectly but I was just curious about the exact reason behind this code:
```python
from pyctcdecode.alphabet import BLANK_TOKEN_PTN, UNK_TOKEN, UNK_TOKEN_PTN
if UNK_TOKEN_PTN.match(token):
                tokenizer_vocab_list[i] = UNK_TOKEN
```
Can't we just add an if condition and handle the token accordingly? I might be wrong in this case but I just want to understand it from the root level.

**Comment by ArthurZucker** [comment]
> dynamic handling for this part of the code 

We can't always expect people to use the default unk token for pyctcdecode no? 
If you feel like this can be easily done, feel free to open a PR!

**Comment by amritregmi26** [comment]
I got my answer. Thanks !!!
