### ISSUE TITLE
Backwards compatibility broken for RoPE: "rope_type"

### ISSUE THREAD

**Issue by snarayan21** [huggingface/transformers#32166]
### System Info

transformers v4.43.1

### Who can help?

@ArthurZucker @gante 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Using an older rope_config with new transformers version

### Expected behavior

Hey, there seems to be an issue when trying to use an older model that has the previous rope_config. Specifically, the rope_config used to have the "type" key, and while this has now been changed to "rope_type", the key is not being extracted correctly. At this line, the "type" key is extracted for backwards compatibility but is not set inside the `rope_scaling` dict. And all the validation functions expect `rope_scaling` to have "rope_type" as a key (for example, [here](https://github.com/huggingface/transformers/blob/c85510f958e6955d88ea1bafb4f320074bfbd0c1/src/transformers/modeling_rope_utils.py#L371)).

Could this be addressed? Would likely require another patch release as well. Thank you!

**Comment by amyeroberts** [comment]
Related issue #32167
