### ISSUE TITLE
`dataloader_prefetch_factor` is left unused for datasets of type `IterableDataset`

### ISSUE THREAD

**Issue by jgreer013** [huggingface/transformers#32169]
https://github.com/huggingface/transformers/blob/c85510f958e6955d88ea1bafb4f320074bfbd0c1/src/transformers/trainer.py#L908

**Comment by amyeroberts** [comment]
cc @muellerzr @SunMarc

**Comment by SunMarc** [comment]
Hi @jgreer013, thanks for reporting ! Could you try to remove that line and test if this works correctly with IterableDatasets, see that there is indeed a speedup or at least the prefetching works correctly ? Thanks !

**Comment by SunMarc** [comment]
Hi @jgreer013, did you have the time to check ?

**Comment by zyandtom** [comment]
any update for this？seems still not support prefetch in iterabledataset
