### ISSUE TITLE
Using `AutoTokenizer.from_pretrained`'s `.encode()` function fails to add BOS token for new Llama-3.1 model

### ISSUE THREAD

**Issue by m18coppola** [huggingface/transformers#32172]
### System Info

- `transformers` version: 4.43.1
- Platform: Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.24.1
- Safetensors version: 0.4.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: no

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Are the differences in the `.encode()` method between Llama-3 and Llama-3.1 expected?

Reproduce:
```python
from transformers import AutoTokenizer

llama_3_tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")
llama_3_1_tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")

text = "Hello"

print(llama_3_tokenizer.encode(text))
print(llama_3_1_tokenizer.encode(text))
```
Output:
```
[128000, 9906]
[9906]
```

### Expected behavior

Expected output:
```
[128000, 9906]
[128000, 9906]
```

**Comment by ArthurZucker** [comment]
Right! We need to add this: 
https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/commit/339ce92d052f002cdbac4a4bd551d1c61dd8345e
to all tokenizers

**Comment by ArthurZucker** [comment]
It should be done now!

**Comment by m18coppola** [comment]
New output:
```
[128000, 9906]
[128000, 9906]
```

Thanks!
