### ISSUE TITLE
Static KV cache with CPU offloading

### ISSUE THREAD

**Issue by gerbenvv** [huggingface/transformers#32179]
### Feature request

I'd like to contribute a static offloading KV cache to the existing proposal of the dynamic offloading KV cache proposed here: #30704

### Motivation

Nice to have an option that is static as well, since it allows for much improvement performance (comparable to `StaticCache` vs `DynamicCache`). Also, I believe some models only work with a static cache.

### Your contribution

I have created this gist:

https://gist.github.com/gerbenvv/282ed3c981a63ad71a301cdc1a705ef1

as the proposal. Also, see discussion at #30704

**Comment by amyeroberts** [comment]
cc @gante @ArthurZucker

**Comment by gerbenvv** [comment]
I'm testing my implementation but I think the argument `num_return_sequences` is broken with the static caches. It isn't taken into account when creating the maximum batch size for the cache.

**Comment by gerbenvv** [comment]
Tested it and unfortunately had to remove the non-blocking transfers to the CPU. It was just too flaky since it didn't reliably work on batch sizes bigger than 1. Anyway, tested it with:

- L40S (48 GB)
- Llama 70B (4 bit quantized)
- batch size of 1000
- sequence size of 25 (no prompt, fully generative)
- sdpa attention

and I am getting a throughput of more than 535 tokens/s.

This offloading really shines for high batch sizes since the model scales super well in batch size. Expect even higher tokens/s when doing long prompts, since then it can also parallelize over the sequence dimension.

**Comment by ArthurZucker** [comment]
For Llama you have the same as GPT-Fast sor 110 token / second

**Comment by ArthurZucker** [comment]
Num return sequences reported here: #31965 is indeed broken for static AFAIK

**Comment by gerbenvv** [comment]
Added static numbers for comparison. Looks like overhead is lower the more the model can parallelize in batch/sequence dimensions. And since that is now decoupled from GPU memory (for the most part), it will be interesting to see this being applied for inference at scale.

Now all we need is to offload the quantized (4 bit) parameters as well, quantize the KV cache and add tensor parallelization to be able to run Llama 3.1 405B on a quad 4090 setup. By calculation, that should give realtime performance for a machine that should cost 10.000 euros. :grin:

**Comment by ArthurZucker** [comment]
Yeah tensor parallelism is .... I don't want to say planned but I'd actually like to do it 👁️

**Comment by gante** [comment]
The numbers are 🔥 

> Yeah tensor parallelism is .... I don't want to say planned but I'd actually like to do it 👁️
👆 ➕
