### ISSUE TITLE
Metrics - Pipeline

### ISSUE THREAD

**Issue by kotari** [huggingface/transformers#32190]
### Feature request

Output token generation metrics/inference-time as part of invoking pipeline. For text-generation pipeline having metrics like generated-tokens, prompt-tokens, inference-time will give insights into expected response time when using the model.

### Motivation

While evaluating models for different scenarios, development/testing happens using the examples provided in the model card. One dimension in evaluating the model is the response. Having an additional dimensions of performance metrics would be useful in understanding the trade-off between model response vs time.
These metrics are available as part of text-generation-inference server as http headers. 

### Your contribution

I haven't thought about contributing but this is something I am willing to do if similar work is not in the pipeline.

**Comment by amyeroberts** [comment]
Hi @kotari, 

The pipeline is intended to be any easy entry point into using our models for inference i.e. a single line call. It's not intended as a full bells-and-whistles feature and we deliberately want to avoid adding to many features. 

For any more advanced use cases, I'd suggest using calling the modeling API directly and building metrics around that e.g.:

```
import time
from transformers import AutoTokenizer, GemmaForCausalLM

model = GemmaForCausalLM.from_pretrained("google/gemma-7b")
tokenizer = AutoTokenizer.from_pretrained("google/gemma-7b")

prompt = "What is your favorite condiment?"
inputs = tokenizer(prompt, return_tensors="pt")

# Generate
with torch.no_grad():
    start = time.time()
    generate_ids = model.generate(inputs.input_ids, max_length=30)
    end = time.time()

generation_running_time = end - start
```

cc @Rocketknight1

**Comment by Rocketknight1** [comment]
Agree with @amyeroberts - we definitely want to keep the pipeline API simple, and leave that kind of performance benchmarking for the lower-level API!

**Comment by kotari** [comment]
@amyeroberts Thanks for the guidance and keeping true to the philosophy to keep things simple. I was able to generalize the suggestion provided. I had to re run tokenizer as I do not have all the fields needed to generate the metrics (This generalized code has a bug with a line break and I can live with it)

```
pipe = pipeline("text-generation", model=model_name, device_map="auto",) 
start = time.time()
response = pipe(prompt, **kwargs)
end = time.time()
process_time = end - start
prompt_tokens = len(pipe.tokenizer(prompt).input_ids)
generated_tokens = (
    len(pipe.tokenizer(response[0]["generated_text"]).input_ids)
    + prompt_tokens
)
logger.info("inference-time: %d", round(process_time * 1000))
logger.info("prompt-tokens: %d", prompt_tokens)
logger.info("generated-tokens: %d", generated_tokens)
logger.info(
    "time-per-token: %d",
    round(process_time * 1000 / (generated_tokens - prompt_tokens)),
)
```
