### ISSUE TITLE
get error when running the chatglm3:  'GenerationConfig' object has no attribute '_eos_token_tensor'

### ISSUE THREAD

**Issue by lmw0320** [huggingface/transformers#32207]
### System Info

platform == ubuntu 22.04
transformers == 4.32.2 
python == 3.10.12
<img width="776" alt="1721873757862" src="https://github.com/user-attachments/assets/abfc1fb6-a7e3-421c-a7b9-cb76d6a71df3">

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

git clone https://github.com/THUDM/ChatGLM3
cd ChatGLM3
pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt
git clone https://huggingface.co/THUDM/chatglm3-6b
cd basic_demo
python3 cli_demo.py

### Expected behavior

I hope to run the command : python3 cli_demo.py successfully without any error

**Comment by zucchini-nlp** [comment]
@lmw0320 hey! ChatGLM uses code from the hub and is not maintained by us. There were changes to how special tokens are handled recently, and that affected ChatGLM's custom generation code. 

Downgrading transformers version to 4.42 will solve the issue, and you can report it at https://huggingface.co/THUDM/chatglm3-6b for the fix

cc @gante

**Comment by Neu070224** [comment]
Downgrading transformers version to 4.42 slove this issue in deed. but report another issue:
![image](https://github.com/user-attachments/assets/945f38e8-b8f2-4025-adf0-e48aa8d00859)

**Comment by eugenezimin** [comment]
It will also solved by using transformers up to version 4.41.2
`pip install transformers==4.41.2`

**Comment by ArthurZucker** [comment]
Closing then! 🤗
