### ISSUE TITLE
 Broken accuracy on LLaMa 3.1 70B -- worse than even 8B 

### ISSUE THREAD

**Issue by pseudotensor** [huggingface/transformers#32205]
### System Info

transformers==4.43.1

As built into vLLM or TGI as well.

4*H100 for llama 3.1 70B or 1*H100 for llama3.1 8B

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

https://github.com/vllm-project/vllm/issues/6760

### Expected behavior

I'd expect long-context performance to not be worse for 70B llama 3.1 compared to 8B, and for the answers to be "normal" and not so brief.

**Comment by ArthurZucker** [comment]
Hey! Not super sure what's going on as your issues seems to show usage of VLMM, which does not use transformers as a backend (yet? 👀 just joking)

**Comment by pseudotensor** [comment]
The same happens with TGI as I mentioned, so I assumed was general to all code that gets pulled from transformers ultimately.  I have yet to run transformers directly, but can.

It's possible it's just a model issue, but a bit surprising that Meta would mess things up so badly.

When prior llama's came out, there were similar issues with things being off somewhere in handling of the model or tokenizer.
