### ISSUE TITLE
Load Phi 3 small on Nvidia Tesla V100 - Flash Attention

### ISSUE THREAD

**Issue by BigDataMLexplorer** [huggingface/transformers#32201]
### System Info

Hi,
I would like to inquire about the possibility of uploading and fine tuning a Phi 3 8k small. When I load the model, I get an error about missing Flash attention. If I want to install the given package, I get this error : 

```
RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.


      torch.__version__  = 2.3.1+cu121
```

But I have the required version of pytorch and CUDA (torch 2.3.1 and cuda 12.1)
Is it because I am using a Tesla V100 graphics card? Is there any way to load the model also with this graphics card?
I found this in the documentation for the Phi 3 mini on Huggingface:

> If you want to run the model on:
> 
> NVIDIA V100 or earlier generation GPUs: call AutoModelForCausalLM.from_pretrained() with attn_implementation="eager"

Does this also apply to the Phi3 Small 8k?? Beacause when I try to load it, the error occurs
```
model = AutoModelForSequenceClassification.from_pretrained("path", num_labels=num_labels ,attn_implementation="eager" )

AssertionError: Flash Attention is not available, but is needed for dense attention
```

Or should I try the ONNX version or it is just for inference?
Thank you.

### Who can help?

@Arthu @BenjaminBossan 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

-

### Expected behavior

-

**Comment by qubvel** [comment]
Hi @BigDataMLexplorer, 

Are you assuming this [model](https://huggingface.co/microsoft/Phi-3-small-8k-instruct)? If so, the modeling code is hosted directly on the hub and not maintained by the `transformers` (see modeling file [here](https://huggingface.co/microsoft/Phi-3-small-8k-instruct/blob/main/modeling_phi3_small.py)). 

I see in the modeling code that Flash attention is required to run the model, but unfortunately, Flash attention is not supported for V100 [cards](https://github.com/Dao-AILab/flash-attention/issues/148).
So, it would be better to open a discussion on the Hub to ask authors if there is a way to run a model without flash attention.

Hope that helps 🤗

**Comment by BigDataMLexplorer** [comment]
Thank you for your response.
I tried to find out anywhere if it is possible to load the model without flash attention, but it didn't find anything. Do you have any idea who can help me? I asked on the huggingface forum, but no one answered.
