### ISSUE TITLE
Why the pre-trained models will be downloaded each times?

### ISSUE THREAD

**Issue by xf05888** [huggingface/transformers#3222]
I often use pre-trained models, but when I want to import it (after restart). 
But each time, I have to download again. So is there a function that can automatically save the model you downloaded in a directory? In Gluon-NLP, it will save the model you used in `.mxnet` in your home directory.

**Comment by julien-c** [comment]
They should definitely be cached locally.

Do you have a sample code showing the behaviour of re-downloading every time?

**Comment by xf05888** [comment]
Here is a example:
```
import torch
from transformers import AlbertTokenizer
albert_tokenizer = AlbertTokenizer.from_pretrained("albert-xxlarge-v2")
```
and it will show this progress bar each time I run this after shutdown or reboot:
**`Downloading: 100%|██████████████████████████████████████| 760k/760k [00:01<00:00, 556kB/s]`**

**Comment by AdityaSoni19031997** [comment]
The models are by default cached to a hidden directory.

**Comment by xf05888** [comment]
@AdityaSoni19031997 
Yes, I searched all the hidden directory as well and there's no eligible model file.
Even if there is, it will disappear after restart

**Comment by xf05888** [comment]
@julien-c I found that it did cache in the local, but why it will disappear after **reboot**?
![Screenshot from 2020-03-17 18-01-14](https://user-images.githubusercontent.com/33285394/76915156-a7934700-6879-11ea-92e8-2f7b6199e52f.png)

**Comment by ibaris** [comment]
Is their now a solution for that? In my case it tries to download the LLAMA-2 Model with almost 10 GB each time.
