### ISSUE TITLE
Llama 3.1 Instruct: `add_generation_prompt=False` still appends assistant prompt

### ISSUE THREAD

**Issue by hav4ik** [huggingface/transformers#32252]
### System Info

- `transformers` version: 4.44.0.dev0
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.23.5
- Safetensors version: 0.4.3
- Accelerate version: 0.32.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.3.1+cu121 (False)
- Tensorflow version (GPU?): 2.15.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (cpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Using distributed or parallel set-up in script?: it is reproducible in any setup, even CPU one

### Who can help?

@ArthurZucker - this is a tokenizer issue of Llama 3.1 instruct

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just execute this simple code:
```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")
messages = [
    {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
    {"role": "user", "content": "Who are you?"},
    {"role": "assistant", "content": "I am you"},
]
print(tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False))
```
The output will be:
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a pirate chatbot who always responds in pirate speak!<|eot_id|><|start_header_id|>user<|end_header_id|>

Who are you?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

I am you<|eot_id|><|start_header_id|>assistant<|end_header_id|>

```
The final `<|start_header_id|>assistant<|end_header_id|>` shouldn't be there!

This bug, in theory, does not affect the training process though. During inference, everything after the last `<|eot_id|>` or `<|eom_id|>` will be ignored anyways.

### Expected behavior

The output is expected to be without the final assistant prompt, just like in Llama-3-8B-Instruct:
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a pirate chatbot who always responds in pirate speak!<|eot_id|><|start_header_id|>user<|end_header_id|>

Who are you?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

I am you<|eot_id|>
```

**Comment by pascal-pfeiffer** [comment]
As far as I can tell, this is an issue of the chat_template in the huggingface hub repo, not from transformers (which is only correctly applying what is in the tokenizer_config.json)

https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/44
https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/53

**Comment by LysandreJik** [comment]
cc @Rocketknight1 it would be very nice to take a look at this and clarify what's happening. Thanks!

**Comment by Rocketknight1** [comment]
Yes, this issue is caused by the chat template, and so the bug isn't part of Transformers itself. We have PRs open on all of the 3.1-Instruct repos to fix this and add proper tool use support!

**Comment by Rocketknight1** [comment]
Chat template PRs should now be merged.

**Comment by kzhang-dm** [comment]
@Rocketknight1  
Now we have the following output, the following string is added to the prompt, is it expected? 
```
Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024
```

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")
messages = [
    {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
    {"role": "user", "content": "Who are you?"},
    {"role": "assistant", "content": "I am you"},
]
print(tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False))
```

outputs 

```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 Jul 2024

You are a pirate chatbot who always responds in pirate speak!<|eot_id|><|start_header_id|>user<|end_header_id|>

Who are you?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

I am you<|eot_id|>
```

**Comment by Rocketknight1** [comment]
@kzhang-dm, yes, that is expected!
