### ISSUE TITLE
Strange behaviour after using BertTokenizer.add_tokens()

### ISSUE THREAD

**Issue by Saltychtao** [huggingface/transformers#3226]
When a word is in origin Bert vocabulary, it would not be split.  But after adding several its subtokens, it would be split into pieces, which seems to inconsistent with the longest match first algorithm.
To reproduce:
```
import transformers
tokenizer = transformers.BertTokenizer.from_pretrained('bert-base-uncased)
tokenizer.tokenize('involve')
tokenizer.add_tokens(['inv','ol','ve'])
tokenizer.tokenize('involve')
```
Line 2 returns 'involve' , and line 4 returns ['inv','##ol','##ve']. 
Is this behaviour expected or is it a bug?

**Comment by LysandreJik** [comment]
No, this is expected behavior. If it was returning `['inv', 'ol', 've']`, then the model would identify each token as being a beginning of word token, whereas the last two are actually part of words following a beginning of a word.

**Comment by Saltychtao** [comment]
Thanks for your response. But since both 'involve' and ['inv', 'ol', 've'] are in the vocabulary, shouldn't 'involve' be kept unsplit instead of split into subword? I am expecting the output to be 'involve' instead of ['inv','##ol','##ve'].
