### ISSUE TITLE
MLM the rest 10% of tokens: pytorch 0.5 vs. tf 0.1

### ISSUE THREAD

**Issue by fkrasnov2** [huggingface/transformers#32329]
Hey there,
I've been wondering about something for a while. Can you help me out? I'm confused about why there's a difference between 0.5 in one place and 0.1 in another. What's the deal with that?

##Lines 852-858
```
       # 10% of the time, we replace masked input tokens with random word
       indices_random = torch.bernoulli(torch.full(labels.shape, 0.5)).bool() & masked_indices & ~indices_replaced
       random_words = torch.randint(len(self.tokenizer), labels.shape, dtype=torch.long)
       
       inputs[indices_random] = random_words[indices_random]
       # The rest of the time (10% of the time) we keep the masked input tokens unchanged
```

##Lines 753-760 
```
       # 10% of the time, we replace masked input tokens with random word
       indices_random = self.tf_bernoulli(input_shape, 0.1) & masked_indices & ~indices_replaced
       random_words = tf.random.uniform(input_shape, maxval=vocab_size, dtype=inputs.dtype)

       inputs = tf.where(indices_random, random_words, inputs)
       # The rest of the time (10% of the time) we keep the masked input tokens unchanged

```
https://github.com/huggingface/transformers/blob/084b5094eb490319719cc11cb05b751e0b419d49/src/transformers/data/data_collator.py#L754

https://github.com/huggingface/transformers/blob/084b5094eb490319719cc11cb05b751e0b419d49/src/transformers/data/data_collator.py#L852

Best, 
Ted

**Comment by Rocketknight1** [comment]
Yes, this is a mistake - thank you for spotting it! The Torch code is correct - to get an average of 10% of the total, we want to take 50% of the remainder after we've already masked 80% with `[MASK]` in the previous step.

@fkrasnov2 Would you be willing to open a PR to fix the TF code?

**Comment by fkrasnov2** [comment]
@Rocketknight1 , Sure, I'll do a PR.

**Comment by Rocketknight1** [comment]
@fkrasnov2 merged - thank you for the PR!
