### ISSUE TITLE
ValueError: cannot reshape array of size <number> into shape

### ISSUE THREAD

**Issue by TheSlackOne** [huggingface/transformers#32331]
### System Info

Python 3.11.2
Debian 12
ctransformers            0.2.27
transformers             4.42.4

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Following the example on Hugging Face: https://huggingface.co/docs/transformers/en/gguf

```python3
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from huggingface_hub import hf_hub_download
from llama_cpp import Llama

# Ensure the model is loaded on the GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"device set to: {device}")

# Load the model and tokenizer
model_name = "TheBloke/dolphin-2.0-mistral-7B-GGUF"
model_file = "dolphin-2.0-mistral-7b.Q4_K_M.gguf"
print(f"Loading tokenizer from {model_name}.")
tokenizer = AutoTokenizer.from_pretrained(model_name, gguf_file=model_file)
print(f"Loading model from repo {model_name}. Model file name {model_file}.")
model = AutoModelForCausalLM.from_pretrained(model_name, gguf_file=model_file)
```
I get
```
ValueError: cannot reshape array of size 36864000 into shape (222,72)
```

### Expected behavior

Model should be loaded.

**Comment by nimadez** [comment]
Problem solved for me, see [this commit](https://github.com/huggingface/transformers/commit/934fe1504e6d5e87e01d96305f4d97faa63cf4c1) and apply the changes or wait for the next update.

**Comment by Tangent-90C** [comment]
Why do I still have this bug when I use the latest version?

- Python 3.10.14
- Windows 11
- ctransformers 0.2.27
- transformers 4.43.4
- gguf 0.9.1

![image](https://github.com/user-attachments/assets/86696611-0541-4670-b28b-732393c7dc03)

**Comment by ArthurZucker** [comment]
can you print `import transformers;transformers.__version__` ? 🤗

**Comment by nimadez** [comment]
I can confirm that it works on 4.44.0

**Comment by ArthurZucker** [comment]
Cool, closing as solved!

**Comment by TheSlackOne** [comment]
> Cool, closing as solved!

Hey @ArthurZucker, please, could you explain how it is solved?

**Comment by ArthurZucker** [comment]
> cleared cache and restarted the system, it worked. 
😉
