### ISSUE TITLE
AutoModel how to modify config?

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#32376]
```
config = AutoConfig.from_pretrained(
                    **self.params, trust_remote_code=True
                )
                config.vision_config.use_flash_attn = False
                print(config.vision_config)
                self.model = AutoModel.from_pretrained(
                    **self.params, trust_remote_code=True, config=config
                ).eval()
```

I need disable `use_flash_attn ` to False forcely when loading a model from pretrained. But looks like the config set didn't have any effect.

Why and how

**Comment by amyeroberts** [comment]
Hi @lucasjinreal, 

`use_flash_attn` isn't a standard config parameter used in transformers, so setting it won't have any effect. 

You can specify the attention mechanism you'd like to be used by specifying `attn_implementation` in the model's `from_pretrained` call


```py
self.model = AutoModel.from_pretrained(
    **self.params, trust_remote_code=True, attn_implementation="eager"
)
```

**Comment by lucasjinreal** [comment]
@amyeroberts  Sadly the model I using is InternVL, which didn't repect this config in their code. They just judge use flashattn only when it is installed, regardless the GPU support it or not.

I need:

- Don't uninstall flashattn since I don't want change the docker container;
- Make the judge fail even though the flashattn installed.

I have resolved this issue.
