### ISSUE TITLE
Make a new way to cusomize is_flash_attn_2_available 

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#32375]
Currrently, we mostly using same docker image for both V100 and A100, but for many models out there, they just didn't respect `attn_implementation` args at all in their code. They just brutly judge by is_flash_attn_2_available 

But this will always return true if it installed, regardless if it actually worked on V100.

And then,  error goes: 

rng_state = flash_attn_cuda.varlen_fwd(
RuntimeError: FlashAttention only supports Ampere GPUs or newer.

I know it might be reasonable, but **we have to uninstall flashattn maually** which is annoying.

An elegant way to do this, is to at least give a interface to customize `is_flash_attn_2_available ` in AutoModel.from_pretrained

**Comment by amyeroberts** [comment]
> but for many models out there, they just didn't respect attn_implementation args at all in their code

Hi @lucasjinreal, could you provide some examples of this, ideally with reproducible code snippets?

**Comment by lucasjinreal** [comment]
I narrow down my issue to a new one, same request.

I don't know a elegant way to make my code didn't using flash-attn without chaning the model pretrained files. Please help a littl.
