### ISSUE TITLE
[mms tts] add uroman as a soft-dependency

### ISSUE THREAD

**Issue by sanchit-gandhi** [huggingface/transformers#32387]
### Feature request

For MMS-TTS checkpoints in languages with non-Roman alphabets (e.g. Hindi), the user is required to perform an extra pre-processing step on the text inputs **outside** of the tokenizer: https://huggingface.co/docs/transformers/en/model_doc/mms#inference

This pre-processing step converts non-Roman text to a "Romanized" version. The tokenizer will throw a warning if the pre-processing is not applied, but will not perform it itself: https://github.com/huggingface/transformers/blob/82efc53513a51660e629c7eca8210af1d67df00b/src/transformers/models/vits/tokenization_vits.py#L174

The ["Uroman"](https://github.com/isi-nlp/uroman#uroman) package required for this pre-processing step previously only contained PERL scripts. Thus, the decision was made to omit this from the Transformers integration. However, The Uroman package has since been updated to include Python scripts and a PyPi package: https://github.com/isi-nlp/uroman#installation

We can now add `uroman` as an optional dependency for MMS-TTS checkpoints that have the attribute `is_uroman`, and perform the pre-processing directly within the tokenizer.

The [Wav2Vec2 Phonemize tokenizer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/wav2vec2_phoneme/tokenization_wav2vec2_phoneme.py) demonstrates a similar design for the `phonemizer` package for the `do_phonemize` attribute.

### Your contribution

Happy to review any PRs!

**Comment by sanchit-gandhi** [comment]
cc @ylacombe

**Comment by nandwalritik** [comment]
Hi @sanchit-gandhi I want to add this feature can you assign me.

**Comment by ylacombe** [comment]
Hey @nandwalritik, feel free to give it a try and ping us to review your progress!
