### ISSUE TITLE
Unused variable in test_pipelines_text_generation.py function

### ISSUE THREAD

**Issue by jacorobe** [huggingface/transformers#32397]
https://github.com/huggingface/transformers/blob/c1aa0edb48217f416f4bbe6e3a9db1500284513b/tests/pipelines/test_pipelines_text_generation.py#L323-L325

TextGenerationPipeline parameter, processor, is unused within this scope of the function. Uncertain if this test is incomplete or if this variable is optional and potentially removeable.

**Comment by ArthurZucker** [comment]
Seems like a lot of places don't use it cc @ydshieh 
Do you want to open a PR  and fix it ? 🤗

**Comment by ydshieh** [comment]
I believe it's just a general pattern: we want to have `get_test_pipeline` having a uniform argument list. But inside the body, only parts of them are used, depends on the pipeline class.

I don't feel strong the need to change it. But if we decide to do it, I would prefer after #32514 being done and merged
