### ISSUE TITLE
seems TFBertForSequenceClassification cannot load tf1.x model?

### ISSUE THREAD

**Issue by fword** [huggingface/transformers#3243]
for TFPreTrainedModel
  model.load_weights(resolved_archive_file, by_name=True)
  
seems by_name is always true.while i see in "tensorflow_core/python/keras/engine/network.py"

 if save_format == 'tf':
      status = self._trackable_saver.restore(filepath)
      if by_name:
        raise NotImplementedError(
            'Weights may only be loaded based on topology into Models when '
            'loading TensorFlow-formatted weights (got by_name=True to '
            'load_weights).')

So, it will always be NotImplementedError

**Comment by LysandreJik** [comment]
All of our TensorFlow models are TF2+ only.
