### ISSUE TITLE
TFCLIPModel.resize_token_embeddings() not working

### ISSUE THREAD

**Issue by Iyeleon** [huggingface/transformers#32430]
### System Info

- `transformers` version: 4.43.4
- Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.12.0
- Huggingface_hub version: 0.23.1
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.17.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@amyeroberts @ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

 I am attempting to extend the token size and embedding size of TFCLIPModel. I successfully added the new tokens to the tokenizer, but I can't resize the token embedding in the model. I keep getting TFCLIPMainLayer does not have attribute "get_input_embeddings. 
I have tried subclassing and writing a method to get the embeddings manually but the parent class does not expose the text_model (or vision_model) attributes under TFCLIPMainLayer. I'm probably not going about this in the right way and was wondering if there is a better way to do this?

```
from transformers import TFCLIPModel
# Load the pretrained CLIP model
clip_model = TFCLIPModel.from_pretrained("openai/clip-vit-base-patch32")

# Resize the token embeddings to match the new vocabulary size
clip_model.resize_token_embeddings(50000)
```

![image](https://github.com/user-attachments/assets/0ef996a5-27dc-4c21-9bbd-fa7a0d94ba1a)

### Expected behavior

Updated input embedding to match tokenizer.

**Comment by amyeroberts** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
Hi @Iyeleon, unfortunately this isn't supported in the TF port of CLIP! I'd recommend trying it with the PyTorch version instead, where it should work.

**Comment by Rocketknight1** [comment]
Ah, that's interesting! If you got it working, feel free to submit a PR including those changes to the `transformers` codebase, and I'd be happy to review it.
