### ISSUE TITLE
FutureWarning: `torch._dynamo.external_utils.is_compiling` is deprecated. Use `torch.compiler.is_compiling` instead.

### ISSUE THREAD

**Issue by xwang233** [huggingface/transformers#32437]
### System Info

- `transformers` version: 4.43.3
- PyTorch version (GPU?): 2.5.0a0+git522fa03 (True) https://github.com/pytorch/pytorch/commit/522fa03e911d822ced8b956e862f3875cb78dd84

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

transformers code: 
https://github.com/huggingface/transformers/blob/13dc6b0853c3cb54e79b18105c0528bc9e84881c/src/transformers/modeling_attn_mask_utils.py#L445C43-L445C69

failed test error message:
```python
/usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py:1107: in forward
    extended_attention_mask = _prepare_4d_attention_mask_for_sdpa(
/usr/local/lib/python3.10/dist-packages/transformers/modeling_attn_mask_utils.py:445: in _prepare_4d_attention_mask_for_sdpa
    or (hasattr(torch, "_dynamo") and torch._dynamo.is_compiling())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (), kwargs = {}

    @functools.wraps(arg)
    def wrapper(*args, **kwargs):
>       warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
E       FutureWarning: `torch._dynamo.external_utils.is_compiling` is deprecated. Use `torch.compiler.is_compiling` instead.
```

pytorch code:
https://github.com/pytorch/pytorch/blob/1add8c5f1c4909ca2a57d110807684aaa230b7b2/torch/_dynamo/external_utils.py#L18-L22

### Expected behavior

no future warning on deprecated API usages

**Comment by amyeroberts** [comment]
Hi @xwang233, thanks for raising this issue! 

The deprecation warning is coming from a nightly release or torch, which we don't officially support in the library. That being said, we should prepare for this when it's part of a stable release. It seems `torch.compiler.is_compiling` has been available for a few months, so can move to using this instead. As we still officially support older versions of pytorch, this would need to be version guarded and fall back to the dynamo import if not available. Would you like to open a PR to add this?
