### ISSUE TITLE
Failed to import transformers.pipelines: No module named 'distutils'

### ISSUE THREAD

**Issue by Rajan-Thakur** [huggingface/transformers#32466]
## Issue:
```
Exception has occurred: RuntimeError
Failed to import transformers.pipelines because of the following error (look up to see its traceback):
No module named 'distutils'
ModuleNotFoundError: No module named 'distutils'
```
After importing and attempting to use the "transformers.pipeline" function, the above error occurs.

## System information

- Python version: 3.12.4
- Pip version: 24.2 (up-to-date)
- Transformers version: 4.43.4
- PATH variables all set correctly

## Notes:

- Importing "transformers" in itself wasn't an issue, but when attempting to use specifically the "transformers.pipeline" function, it fails and shows the error.
- I have tried installing "distutils" through "pip" and through "pip3," but it has repeatedly displayed a message saying no such package exists at all.
- IMPORTANT: I know that "distutils" is a deprecated package. I've tried installing "setuptools," but that hasn't solved the issue. The same exact error message shows.

So, what now?

**Comment by amyeroberts** [comment]
Hi @Rajan-Thakur, thanks for reporting an issue! 

> PATH variables all set correctly
This is quite a general statement, which we can't verify here with the current information. It does seem there's something funny happening in the env. 

Could you try the following in a python environment: 
```py
import setuptools
print(setuptools.__version__)
```

**Comment by Rajan-Thakur** [comment]
Ayo

**Comment by Rajan-Thakur** [comment]
Actually never mind, thank you @amyeroberts, I solved it somehow by just
`python3 -m pip uninstall setuptools
python3 -m pip install setuptools`
executing that in the command prompt.

For future dwellers who see and try this, but it doesn't work for you, try re-installing transformers and torch too.

**Comment by Rajan-Thakur** [comment]
Just in case if anyone has a similar issue and has a question. I'll close it now.
