### ISSUE TITLE
MLU Check Breaks Trainer at Import Time for Older Accelerate Versions

### ISSUE THREAD

**Issue by alex-jw-brooks** [huggingface/transformers#32461]
### System Info

- `transformers` version: 4.44.0.dev0
- Platform: Linux-4.15.0-206-generic-x86_64-with-glibc2.27
- Python version: 3.9.16
- Huggingface_hub version: 0.24.5
- Safetensors version: 0.4.4
- Accelerate version: 0.29.0
- PyTorch version (GPU?): 2.4.0+cu121 (True)
- Tensorflow version (GPU?): 2.15.1 (True)
- Flax version (CPU?/GPU?/TPU?): 0.7.0 (cpu)
- Jax version: 0.4.13
- JaxLib version: 0.4.13
- GPU type: Tesla V100-PCIE-32GB

### Who can help?

@muellerzr @SunMarc

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

- Install the latest version of transformers with `accelerate==0.21.0`, the current minimum supported version.
- Try `from transformers import trainer`

For older versions of Accelerate, this import will throw a runtime error caused by:
```
ImportError: cannot import name 'is_mlu_available' from 'accelerate.utils' /Users/alexanderjbrooks/transformers/venv/lib/python3.9/site-packages/accelerate/utils/__init__.py)
```

### Expected behavior

We should be able to import the trainer with the minimum supported version of Accelerate! I will submit a PR to this effect.

**Comment by SunMarc** [comment]
Hey @alex-jw-brooks, thanks for the report ! This should be fixed by this PR https://github.com/huggingface/transformers/pull/32292 that was created a few days ago. Let us know this this fixes your issue !

**Comment by alex-jw-brooks** [comment]
Looks good to me, thanks @SunMarc!
