### ISSUE TITLE
Error when converting "state-spaces/mamba2-130m" weights to huggingface-compatible format

### ISSUE THREAD

**Issue by learning-chip** [huggingface/transformers#32496]
### System Info

- Transformers version: 4.40.0

### Who can help?

@molbap @ArthurZucker

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

I tried to load https://huggingface.co/state-spaces/mamba2-130m into HF-compatible Mamba-2 (https://github.com/huggingface/transformers/pull/32080), using the [convert_mamba2_ssm_checkpoint_to_pytorch.py](https://github.com/huggingface/transformers/blob/v4.44.0/src/transformers/models/mamba2/convert_mamba2_ssm_checkpoint_to_pytorch.py) script. But the script assumes model weights to be in safetensors format:

https://github.com/huggingface/transformers/blob/984bc11b0882ff1e5b34ba717ea357e069ceced9/src/transformers/models/mamba2/convert_mamba2_ssm_checkpoint_to_pytorch.py#L32-L35

but the weight file is [is in torch bin format](https://huggingface.co/state-spaces/mamba2-130m/blob/main/pytorch_model.bin) and cannot be opened in this way.

Also, the script requires a tokenizer path:

https://github.com/huggingface/transformers/blob/984bc11b0882ff1e5b34ba717ea357e069ceced9/src/transformers/models/mamba2/convert_mamba2_ssm_checkpoint_to_pytorch.py#L55-L61

but `state-spaces/mamba2-130m` [reuses](https://github.com/state-spaces/mamba/blob/v2.2.2/benchmarks/benchmark_generation_mamba_simple.py#L37) `EleutherAI/gpt-neox-20b` tokenizer instead of having its own.

### Expected behavior

`convert_mamba2_ssm_checkpoint_to_pytorch.py` should be able to convert those Mamba-2 weights:

- https://huggingface.co/state-spaces/mamba2-130m
- https://huggingface.co/state-spaces/mamba2-370m
- https://huggingface.co/state-spaces/mamba2-780m
- https://huggingface.co/state-spaces/mamba2-1.3b
- https://huggingface.co/state-spaces/mamba2-2.7b

**Comment by molbap** [comment]
Thanks for the issue! Yes, the current conversion script is made for the mistral/codestral mamba 2 release, which uses safetensors + their own tokenizer - if you want to work on a modification to the conversion script on a new PR, feel free to do so and we can help! Else, I'll take a look at that later :)
