### ISSUE TITLE
Fix get_usable_length for StaticCache

### ISSUE THREAD

**Issue by guangy10** [huggingface/transformers#32503]
### System Info

transformers: 4.45.0.dev0
torch: 2.5.0.dev20240716+cpu

### Who can help?

@ArthurZucker
@gante
@zucchini-nlp

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

It's a bug only affect the new workflow ["Export to ExecuTorch"](https://github.com/huggingface/transformers/issues/32253) that we're trying to enable. The method [`get_usable_length`](https://github.com/huggingface/transformers/blob/main/src/transformers/cache_utils.py#L69-L78) should be override for `StaticCache` where recompile, resizing or evicting the existing cache entry won't be applicable. This is because unlike eager or `torch.compile`d model, exported model will be running in a non-python env where recompiling from the eager source isn't available. 

### Expected behavior

The `generation` length using the exported artifact should not exceed the maximal cache length because the model and the size of the its cache are exported statically. When `get_usable_length` returns 0, it should terminate the generation.

**Comment by ArthurZucker** [comment]
The `get_usable_length` is something that we are deprecating anyways, but good to note. StaticCache should not even have it!
