### ISSUE TITLE
UnicodeDecodeError when loading BART from fairseq checkpoint

### ISSUE THREAD

**Issue by marmg** [huggingface/transformers#3250]
# 🐛 Bug

When trying to load a checpoint from the fariseq library I'm getting an UnicodeError

## Information

Model I am using (Bert, XLNet ...): BART

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Train a checkpoint with the fairseq library
2. Load it using BartForMaskedLM.from_pretrained

## Expected behavior

Get the checpoint loaded into a BART model.

## Environment info

     
- `transformers` version: master
- Platform: linux
- Python version: 3.6.7
- PyTorch version (GPU?): 1.4.0 / Yes
- Tensorflow version (GPU?):
- Using GPU in script?: No
- Using distributed or parallel set-up in script?:
- `fairseq` version: master

**Comment by sshleifer** [comment]
Unfortunately, I don't think the conversion you are describing is currently supported. 
If I were to attempt this on my own, I would try to modify https://github.com/huggingface/transformers/blob/master/src/transformers/convert_bart_original_pytorch_checkpoint_to_pytorch.py to take in a path to a checkpoint, rather than a `torch.hub` alias.

**Comment by sshleifer** [comment]
This function converts from saved fairseq checkpoints: https://github.com/huggingface/transformers/blob/7a7fdf71f80452fcae064bd016f06e9a0f0f19ed/src/transformers/convert_bart_original_pytorch_checkpoint_to_pytorch.py#L81

Let me know if that helps!
