### ISSUE TITLE
Llama is ExecuTorch compatible

### ISSUE THREAD

**Issue by guangy10** [huggingface/transformers#32505]
### Feature request

Enable Llama to ["Export to ExecuTorch"](https://github.com/huggingface/transformers/issues/32253) workflow

### Motivation

See details in #32253

### Your contribution

Llama model enablement

**Comment by debrupf2946** [comment]
@guangy10 @amyeroberts 
Hi, I am Debrup Paul, I would like to take up this issue, can this issue be assigned to me? I understood the workflow and will raise the pr in 2 weeks.

**Comment by ArthurZucker** [comment]
Hey! Actually this is already supported and can be closed! 🤗

**Comment by debrupf2946** [comment]
> Hey! Actually this is already supported and can be closed! 🤗

Okay, do you have some beginner friendly task on which I can contribute?I actually want to begin contributing in Transformers.I am also a Google Summer of Code Contributor working on NLP and GenAI related problems.
linkedin: https://www.linkedin.com/in/debrup-paul-599158227/

**Comment by ArthurZucker** [comment]
I would recommend you the issues with `Good second issue` or `Good difficult issue` labels!

**Comment by guangy10** [comment]
> Hey! Actually this is already supported and can be closed! 🤗

Yeah, I had 

> @guangy10 @amyeroberts Hi, I am Debrup Paul, I would like to take up this issue, can this issue be assigned to me? I understood the workflow and will raise the pr in 2 weeks.

Hey @debrupf2946, thanks for reaching out and being interested in llama for ExecuTorch. As @ArthurZucker mentioned, we actually have been working on this model already for a while, so it should just work out-of-the-box. I have a local commit that verify the newly released 1B and 3B model are working e2e. Will publish the PR soon to protect this model with tests. 

Feel free to try a different model that you are interested in. Currently we have a list of candidates linked to the umbrella task #32253.
