### ISSUE TITLE
Spelling Error in clean_up_tokenization_spaces was not set

### ISSUE THREAD

**Issue by Xemorr** [huggingface/transformers#32510]
### System Info

N/A

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

Do not include clean_up_tokenization_spaces parameter in Tokenizer

### Expected behavior

Error is produced, but the error is spelt correctly. 
The word deprecated should be used instead of depracted

**Comment by amyeroberts** [comment]
Thanks for raising! This has been resolved on main #32484

**Comment by jeffwidman** [comment]
Should this be closed then now that the PR is merged?

**Comment by ArthurZucker** [comment]
Closing as merged yes!
