### ISSUE TITLE
Misleading type annotations in data collator

### ISSUE THREAD

**Issue by sedol1339** [huggingface/transformers#32528]
### Describe the bug

In `DataCollatorWithPadding`, the method `__call__` has the following sitnature:
```
def __call__(self, features: List[Dict[str, Any]]) -> Dict[str, Any]:
```
However, in the [official tutorial](https://huggingface.co/learn/nlp-course/en/chapter3/2) on line `batch = data_collator(samples)` the collator actually accepts not `List[Dict[str, Any]]`, but `Dict[str, List[Any]]`, that is, the already batched sample.

This complicates understanding collators and implementing custom ones.

### Steps to reproduce the bug

Run all steps in the tutorial:
https://huggingface.co/learn/nlp-course/en/chapter3/2

Check the `samples` variable that is passed to `data_collator`.

### Expected behavior

A more clear documentation and type annotation is desired.

### Environment info

datasets 2.20.0
Python 3.10.14
Ubuntu 22

**Comment by amyeroberts** [comment]
Hi @sedol1339, thanks for reporting! 

Would you like to open a PR fixing the typo? This way you get the github contrib for spotting & suggesting the fix

**Comment by sedol1339** [comment]
I am nut sure this is a typo, because the same occurs in other collators, such as `DefaultDataCollator`.

**Comment by amyeroberts** [comment]
@sedol1339 If the collator accepts both, then we can indicate this with a `Union` type annotation
