### ISSUE TITLE
Translation docs claim two different tokenizers are used in translation for input and output language, which is incorrect

### ISSUE THREAD

**Issue by frereit** [huggingface/transformers#32533]
https://github.com/huggingface/transformers/blob/b51d4145bbfa9bd90dc878e552d5cdc5133dabc2/docs/source/en/tasks/translation.md?plain=1#L93

<https://huggingface.co/docs/transformers/en/tasks/translation#preprocess> claims:

> Tokenize the input (English) and target (French) separately because you can’t tokenize French text with a tokenizer pretrained on an English vocabulary.

However, in the code below (`preprocess_function`), clearly there's only one tokenizer in use:

```
model_inputs = tokenizer(inputs, text_target=targets, max_length=128, truncation=True)
```

**Comment by amyeroberts** [comment]
cc @stevhliu
