### ISSUE TITLE
bug in run_glue

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#3253]
Hi I got this error when running the run_glue.py
    from transformers import glue_compute_metrics as compute_metrics
ImportError: cannot import name 'glue_compute_metrics'

**Comment by nateraw** [comment]
If you could include your environment and steps to replicate the issue, that would help. Its working for me on version 2.5.1 (from master branch).

**Comment by rabeehk** [comment]
Hi. Sorry then I must have used the old version of transformer, I will close the issue and reopen if needed. thanks.
