### ISSUE TITLE
Why the transcription of the audio by Whisper pipeline and processor are different?

### ISSUE THREAD

**Issue by MartaSamoilenkoPn** [huggingface/transformers#32557]
I am using two approaches: processor or pipeline because the pipeline returns timestamps but no confidence levels and the processor returns confidence levels. Anyway, the problem is that pipeline transcription sometimes is worse than processor transcription. Is it a problem in the Transformers lib?

processor:
" I got six, and seven, and eight, and nine, and ten, and eleven, and twelve, and thirteen, and twenty, and fifteen, and sixteen.",

pipeline:
 " I got six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen.",

The audio for both approaches is the same.

**Comment by ArthurZucker** [comment]
Hey! When you say that you are using the processor, are you using the `generate` api?
