### ISSUE TITLE
[BUG] ModelCard do not write true optimizer

### ISSUE THREAD

**Issue by relic-yuexi** [huggingface/transformers#32560]
This code seems to be outdated and does not consider the `optim` parameter. I might submit a PR to fix it.

https://github.com/huggingface/transformers/blob/e4522fe399641add9b1f3207923752a35ea7fdbb/src/transformers/modelcard.py#L876-L882

**Comment by qubvel** [comment]
Hi @relic-yuexi, thanks for reporting the issue!

We would appreciate the fix!

**Comment by aroun-coumar** [comment]
Hi @relic-yuexi, may i do the fix
Thank you

**Comment by nathsujal** [comment]
Hi @relic-yuexi may i do the fix
Thankyou

**Comment by hritikranjan1** [comment]
Hi @relic-yuexi  , Thanks For repoting this issue , I can fix it

**Comment by qubvel** [comment]
@nathsujal @hritikranjan1 Thanks for your interest in contribution! The issue has been already fixed, so I'm closing this issue!
 - https://github.com/huggingface/transformers/pull/33581
 
 Feel free to take another one, we would greatly appreciate your help!
