### ISSUE TITLE
when i update transformers from 4.38.1 to  version==4.42.0, it happened that Failed to import trl.models.modeling_base because of the following error (look up to see its traceback): '>' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by ldh127** [huggingface/transformers#32565]
### System Info

when i update transformers from 4.38.1 to  version==4.42.0, it happened that Failed to import trl.models.modeling_base because of the following error (look up to see its traceback): '>' not supported between instances of 'NoneType' and 'str'

### Who can help?

@muellerzr @SunMarc

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

when i update transformers from 4.38.1 to  version==4.42.0, it happened that Failed to import trl.models.modeling_base because of the following error (look up to see its traceback): '>' not supported between instances of 'NoneType' and 'str'

### Expected behavior

@muellerzr @SunMarc

**Comment by muellerzr** [comment]
Can you please give us the full trace? What import did you try?
