### ISSUE TITLE
very slow performance on transformer 2.5.0 versus 2.3.0

### ISSUE THREAD

**Issue by abhyuday3jagannatha** [huggingface/transformers#3258]
Hi
I am running the run_glue version with last version of transformer 2.5.0 python=3.5 and this is at least 10 times slower than running the same code with transformer 2.3.0 with python 3.6.9. I use the BERT model. The difference between speed of these versions is extremely high, could you have a look and check why the performance of latest version of the transformer is very low. thank you.

**Comment by cooelf** [comment]
I met the same issue when running the run_squad.py using the 2.5.0 version.

**Comment by LysandreJik** [comment]
Which PyTorch version are you using for your benchmarks? Is it the same for both, or is it different?
