### ISSUE TITLE
Model name 'distilbert-base-german-cased' was not found in model name list.

### ISSUE THREAD

**Issue by woiza** [huggingface/transformers#3260]
This code is ok:

`from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-german-cased")
model = AutoModel.from_pretrained("distilbert-base-german-cased")
`

But the following fails:

`from transformers import BertForSequenceClassification, AdamW, BertConfig

model = BertForSequenceClassification.from_pretrained(
    "distilbert-base-german-cased", 
    num_labels = 2,   
    output_attentions = False, 
    output_hidden_states = False,
)
`

`OSError: Model name 'distilbert-base-german-cased' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-german-cased/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.`

**Comment by stefan-it** [comment]
Hi @woiza,

try to use: `DistilBertForSequenceClassification` instead of `BertForSequenceClassification` :)

**Comment by woiza** [comment]
@stefan-it 

that worked, thank you!
