### ISSUE TITLE
TFAlbertMainLayer cannot be imported from the transformers library.

### ISSUE THREAD

**Issue by shreyansh05s** [huggingface/transformers#3262]
Unlike the TFBertMainLayer class which can be imported from transformers, TFAlbertMainLayer cannot be imported.

Locally I made the changes to init.py:

Import TFAlbertMainLayer from modeling_tf_albert 

Similar to tensorflow version, pytorch version should also be implemented.

**Comment by julien-c** [comment]
This seems like a valid point, what do you think @LysandreJik?
