### ISSUE TITLE
[BART] test_generate_fp16 fails after PR#3140

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#3265]
passes after `git checkout d6de6423` (commit preceding #3140)
Traceback:
```
                 unfinished_sents.mul_((~eos_in_sents).long())

            # stop when there is a </s> in each sentence, or if we exceed the maximul length
>           if unfinished_sents.max() == 0:
E           RuntimeError: cuda runtime error (716) : misaligned address at /pytorch/aten/src/THC/THCReduceAll.cuh:327

src/transformers/modeling_utils.py:992: RuntimeError
```
@thomwolf @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Interesting - will investigate. Probably something with the `device` of `unfinished_sents` then!

@julien-c

**Comment by sshleifer** [comment]
Caused by previously unexposed kwargs changing behavior:
passing
```
do_sample=False, early_stopping=True
```
in the unit test fixes them.

**Comment by Laksh1997** [comment]
I'm getting this error @sshleifer

**Comment by Laksh1997** [comment]
https://github.com/huggingface/transformers/issues/5221

**Comment by Laksh1997** [comment]
I have early stopping = False, but do_sample = True
