### ISSUE TITLE
audio pipeline utility ffmpeg_microphone_live only works with PulseAudio in Linux (KDE Manjaro)

### ISSUE THREAD

**Issue by Dakai** [huggingface/transformers#32660]
### System Info

- `transformers` version: 4.44.0
- Platform: Linux-6.10.3-1-cachyos-bore-x86_64-with-glibc2.40
- Python version: 3.12.4
- Huggingface_hub version: 0.24.5
- Safetensors version: 0.4.4
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.4.0+cu121 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@Narsil

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

follow https://huggingface.co/learn/audio-course/chapter7/voice-assistant

### Expected behavior

The course's code running in my local Linux machine does not record anything, I tried to use the latest ffmpeg to record the sound with command `ffpmeg -f alsa -i default -t 5 test.wav` and got an empty wav file, then `ffmpeg -f pulse -i default -t 5 test.wav` worked perfectly.

So I edited the file, `venv/lib/python3.12/site-packages/transformers/pipelines/audio_utils.py` at line 30, changed `fomat_ = "alsa"` into `format_ = "pulse"` , then the code works as expected and successfully recognised the wake word.

Can you please look into this issue with Linux audio system and make it compatible with both ALSA and PulseAudio?

**Comment by amyeroberts** [comment]
@ylacombe

**Comment by ylacombe** [comment]
Hey @Dakai, thanks for opening this issue! Looks like it might be an issue with your KDE, have you been able to use Alsa in your terminal?
