### ISSUE TITLE
NLLB Code Examples out of date?

### ISSUE THREAD

**Issue by Sharrnah** [huggingface/transformers#32663]
### System Info

4.44.0, Windows 11, Python 3.11

### Who can help?

Probably @ArthurZucker but not 100% sure.

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Load the NLLB-200 model
2. Try to use the code exactly as in the example code here https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/nllb.md#generating-with-nllb
3. Getting the error that tokenizer does not expect any argument.
   ```
    Error: AutoTokenizer.__init__() takes 1 positional argument but 2 were given
    Traceback (most recent call last):
      File "E:\AI\whisper-audio-translate-transcribe\Whispering-VRC\Models\TextTranslation\texttranslate.py", line 88, in TranslateLanguage
        translation_text, from_code, to_code = texttranslateNLLB200.translate_language(text, from_code, to_code, as_iso1)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "E:\AI\whisper-audio-translate-transcribe\Whispering-VRC\Models\TextTranslation\texttranslateNLLB200.py", line 530, in translate_language
        inputs = tokenizer(text).to(torch_device)
                 ^^^^^^^^^^^^^^^
    TypeError: AutoTokenizer.__init__() takes 1 positional argument but 2 were given
   ```

### Expected behavior

That the example code works.

I found this issue https://github.com/huggingface/transformers/issues/31348
Which mentions that there where deprecation changes to the tokenizer? But its completely unclear now how to use it. It worked in an old version of transformers, but i updated it just to learn that its now broken and the example code shows code that clearly doesn't work anymore. (Unless i am doing something completely wrong.)

**Comment by molbap** [comment]
Hi @Sharrnah, I just used this code snippet
```python
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M")
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M")

article = "UN Chief says there is no military solution in Syria"
inputs = tokenizer(article, return_tensors="pt")

translated_tokens = model.generate(
    **inputs, 
    forced_bos_token_id=tokenizer.convert_tokens_to_ids("fra_Latn"), 
    max_length=30
)

translation = tokenizer.batch_decode(translated_tokens, skip_special_tokens=True)[0]
print(translation)
```
And had no issues running it - from your example it doesn't look like you are using exactly the code from the official examples, could you give a full reproducer?

**Comment by Sharrnah** [comment]
oops. I am so sorry. i had an error in my code at another place which resulted it not loading the tokenizer correctly.
I guess that came from too much testing around to get it updated to some smaller changes.

Its working now.

Thank you and sorry again.

**Comment by molbap** [comment]
No worries - thanks for updating!
