### ISSUE TITLE
Constraint.advance() docstring is slighly incorrect

### ISSUE THREAD

**Issue by alex-calderwood** [huggingface/transformers#32668]
### System Info

according to the implementations of the Constraint ABC, the [advance() ](https://github.com/huggingface/transformers/blob/c1357834e86e71792d1cad06a998f5ebf6e07126/src/transformers/generation/beam_constraints.py#L49)function can return either a single token id (as the docstring indicates) or a list of token ids that would advance the beam search. It should be updated to reflect this.

Here is an example fix:

```
@abstractmethod
def advance(self):
    """
    When called, returns the token(s) that would take this constraint one step closer to being fulfilled.

    Return:
        token_ids (Union[int, List[int], None]): 
            - A single token ID (int) that advances the constraint
            - A list of token IDs that could advance the constraint
            - None if the constraint is completed or cannot be advanced
    """
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just a docstring change.

### Expected behavior

Should be updated for accuracy, easy of implementing this abstract base class.

**Comment by amyeroberts** [comment]
cc @gante

**Comment by gante** [comment]
@alex-calderwood thank you for opening this issue and, more importantly, for submitting a fix to it 🤗
