### ISSUE TITLE
when I install transformers, it appeared this error

### ISSUE THREAD

**Issue by policeme** [huggingface/transformers#3269]
ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot be installed directly

**Comment by AdityaSoni19031997** [comment]
You should add more information about your environment like OS, Python Version etc?
I just installed it on Windows 10, WSL etc Python 3.6.9 :: Anaconda, Inc.; It worked..

**Comment by policeme** [comment]
I installed it on Mac, Python 3.6.10 Anaconda
