### ISSUE TITLE
Install error , Win10,anaconda3,python3.5,pytorch

### ISSUE THREAD

**Issue by caucsunjiahui** [huggingface/transformers#3282]
When I pip install the transformers,its not successfull,my environment is Win10,anaconda3,python3.5,the error is as follows,what is wrong with it,thank you!.

## Details
 Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sjh\AppData\Local\Temp\pip-install-fu05dcfq\sentencepiece\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "C:\Users\sjh\Anaconda3\Lib\codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\sjh\AppData\Local\Temp\pip-install-fu05dcfq\sentencepiece\

**Comment by julien-c** [comment]
seems to be a sentencepiece issue, please open an issue at https://github.com/google/sentencepiece
