### ISSUE TITLE
What is the most effective way to use BERT , ROBERTA , GPT-2 architectures as frozen feature extractors ?

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#3283]
We use pretrained self-supervised learning (SSL) models for NLP as feature extractors for downstream tasks like sentiment analysis. In most of such cases, we add a simple new classification layer and **fine-tune the whole model**.  With the SSL models getting bigger and the amount of unsupervised training data is huge it would be nice if we can use the problem agnostic behavior of SSL embeddings. In other words if we use them as **Frozen Feature extractors**, we can save lot of time and computational cost. 

**Have anyone seen a good review on using SSL networks as frozen feature extractors?**

**Comment by caucsunjiahui** [comment]
uninstall the anaconda3, transformer installed successfully
