### ISSUE TITLE
confusing deprecation msg for `DynamicCache.seen_tokens` - no `cache_position` in this class

### ISSUE THREAD

**Issue by poedator** [huggingface/transformers#32855]
The message says `"The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead."` however there is no `cache_position` in this class (it is present in StaticCache). Perhaps there may be a clearer message.

code ref: https://github.com/huggingface/transformers/blame/7c1149120829eb58e42a1ba4dbd2a9fa98864707/src/transformers/cache_utils.py#L91

tagging @gante

**Comment by gante** [comment]
@poedator thank you for opening this issue! 🤗 

We're aware of it, and we're working on a [pre-requisite task](https://github.com/huggingface/transformers/issues/32685) before tackling the current confusion around `seen_tokens`/`get_seq_length`. (In the long run, we don't want to use these functions, but rather use the explicit `cache_positions` all the time.)
