### ISSUE TITLE
Add logit scaling sdpa using `FlexAttention` for Gemma2

### ISSUE THREAD

**Issue by ArthurZucker** [huggingface/transformers#32877]
### Feature request

With the recent publish of `FlexAttention`, think it makes senses to support it with sdpa path of `Gemma2`.
Leaving it open to the community:

- [ ] implement the path
- [ ] make sure integration tests work 
- [ ] add some doc

Related to #32865

**Comment by drisspg** [comment]
For a code pointer: https://github.com/pytorch-labs/attention-gym/blob/main/attn_gym/mods/softcapping.py
