### ISSUE TITLE
Add RobustSAM (CVPR 2024)

### ISSUE THREAD

**Issue by leolu030066** [huggingface/transformers#32874]
### Model description

Robust Segment Anything Model (RobustSAM) is an enhanced version of the Segment Anything Model (SAM), designed to improve segmentation performance on low-quality images while preserving the original model's zero-shot segmentation capabilities and flexible prompting system.

### Open source status

- [x] The model implementation is available
- [x] The model weights are available

### Provide useful links for the implementation

- Paper: [https://openaccess.thecvf.com/content/CVPR2024/html/Chen_RobustSAM_Segment_Anything_Robustly_on_Degraded_Images_CVPR_2024_paper.html](https://openaccess.thecvf.com/content/CVPR2024/html/Chen_RobustSAM_Segment_Anything_Robustly_on_Degraded_Images_CVPR_2024_paper.html)
- arXiv: [https://arxiv.org/pdf/2406.09627](https://arxiv.org/pdf/2406.09627)
- Github repo: [https://github.com/robustsam/RobustSAM](https://github.com/robustsam/RobustSAM)

@robustsam

**Comment by jadechoghari** [comment]
@leolu030066  - Hello!
RobustSAM is just an extension of SAM.
We have implemented the HF model cards here: 👀🤗👇:
https://github.com/robustsam/RobustSAM/issues/10#issuecomment-2294327808


Best.

**Comment by leolu030066** [comment]
> @leolu030066 - Hello! RobustSAM is just an extension of SAM. We have implemented the HF model cards here: 👀🤗👇: [robustsam/RobustSAM#10 (comment)](https://github.com/robustsam/RobustSAM/issues/10#issuecomment-2294327808)
> 
> Best.

Hi!
Got it. Thanks for your reply.

After discussing with the author, we aim to integrate the model into the Transformers library. We hope it can be helpful for developers to use RobustSAM more easily.

This is the project I am working on right now. #32931 However, I am new to reimplementing models into the Transformers library. That is, it may take some time to finish it. But, if you are interested in participating or have some comments, please kindly let me know. I will be very grateful.😊

Sincerely.

**Comment by leolu030066** [comment]
> @leolu030066 - Hello! RobustSAM is just an extension of SAM. We have implemented the HF model cards here: 👀🤗👇: [robustsam/RobustSAM#10 (comment)](https://github.com/robustsam/RobustSAM/issues/10#issuecomment-2294327808)
> 
> Best.

Got it! Thanks for your contribution.
Sincerely,
Leo
