### ISSUE TITLE
Unexpected output from feature extraction pipeline

### ISSUE THREAD

**Issue by Stuffooh** [huggingface/transformers#3287]
Hi everyone,

I'm not sure if it is a bug or if I simply overlooking something so I did not want to submit a bug report yet. I have the following example code:

```
from transformers import pipeline, AutoTokenizer
import numpy as np

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased',
add_special_tokens=False)
#initialize pipeline
nlp = pipeline('feature-extraction', model='bert-base-uncased', config='bert-base-uncased', tokenizer=tokenizer, device=1)
features = nlp("Why is Howard asking questions about the food after Leonard gives him a carton ?")
features = np.squeeze(features)
print(features.shape)
```

I expect the output: (15,768)
But I receive the output: (18,768)

I think there are only 15 tokens but somehow the shape is 18. What am I missing here?

Is this output expected and am I simply missing something or is there more to it?

**Comment by julien-c** [comment]
The tokenizer adds special tokens (here, specific to BERT) at the beginning and end of the sentence. 

You can check that with:
```python
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
len(tokenizer.encode(TEXT)) == 18
```

**Comment by Stuffooh** [comment]
Is there any way to avoid the special tokens when extracting the features? I expected "add_special_tokens=False" would prevent this from happening?

**Comment by julien-c** [comment]
I would suggest not using the Pipeline and just doing `tokenizer.encode()` then `outputs = model(input_ids)`
