### ISSUE TITLE
Dockerhub images huggingface/transformers_cpu for version 2.5.1 has version 2.5.0 installed

### ISSUE THREAD

**Issue by edwardcqian** [huggingface/transformers#3288]
# 🐛 Bug

## Information

Model I am using any model introduced in 2.5.1

The problem arises when using:
pulling `huggingface/transformers_cpu:2.5.1` from dockerhub

## To reproduce

1. pull docker image from dockerhub
2. run docker container
3. run `pip freeze` to see `transformers==2.5.0`

## Expected behavior
`pip freeze` in the docker container should show: `transformers==2.5.1`

**Comment by mfuntowicz** [comment]
Should be fixed, I'll push updated images for all the others Dockerfile in the next hours. 

Thanks for reporting @edwardcqian

**Comment by mfuntowicz** [comment]
I'm closing, feel free to reopen if I missed something 👍
