### ISSUE TITLE
transformers - installation

### ISSUE THREAD

**Issue by jzaba123** [huggingface/transformers#32886]
Hello,

Going via the install and I see some issues 

https://huggingface.co/docs/transformers/installation

A)
PLATFORM WIN

pip install 'transformers[torch]'

ERROR: Invalid requirement: "'transformers[torch]'": Expected package name at the start of dependency specifier
    'transformers[torch]'

pip install 'transformers[tf-cpu]'

ERROR: Invalid requirement: "'transformers[tf-cpu]'": Expected package name at the start of dependency specifier
    'transformers[tf-cpu]'

pip install 'transformers[flax]'

ERROR: Invalid requirement: "'transformers[flax]'": Expected package name at the start of dependency specifier
    'transformers[flax]'

CORRECT SHOULD BE
==================

pip install "transformers[torch]"

pip install "transformers[tf-cpu]"

pip install "transformers[flax]"

B)
pip install "transformers[tf-cpu]" DID NOT WORK

Failed to build tokenizers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tokenizers)

https://huggingface.co/learn/nlp-course/en/chapter8/5
transformers-cli env

- `transformers` version: 4.44.0
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.11.9
- Huggingface_hub version: 0.24.5
- Safetensors version: 0.4.4
- Accelerate version: 0.33.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.0+cu118 (True)
- Tensorflow version (GPU?): 2.17.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.7.0 (cpu)
- Jax version: 0.4.13
- JaxLib version: 0.4.13
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA GeForce RTX 3060 Laptop GPU

**Comment by Rocketknight1** [comment]
Hi @jzaba123, yes, thanks for the issue! `pip install 'transformers[torch]'` works on Linux but presumably not on Windows. Can you open a PR to fix it? The relevant file is `installation.md`
