### ISSUE TITLE
[whisper] transcription is different from hf & openai

### ISSUE THREAD

**Issue by jsoto-gladia** [huggingface/transformers#32900]
### System Info

- `transformers` version: 4.40.2
- Platform: Linux-5.15.0-118-generic-x86_64-with-glibc2.35
- Python version: 3.10.14
- Huggingface_hub version: 0.21.4
- Safetensors version: 0.4.2
- Accelerate version: 0.24.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

[silence-middle.wav.zip](https://github.com/user-attachments/files/16676870/silence-middle.wav.zip)
the following wav file produces 
- with hf whisper repo (tiny model):
Split infinity, and a time when less is more. Where too much is never 
- with openai whisper repo (tiny model)
Split infinity, and a time when less is more.

### Expected behavior

I would expect the result to be 
Split infinity, and a time when less is more. Where too much is never

**Comment by jsoto-gladia** [comment]
you are missing the re encoding mechanism happening when eos is reached within a 30s segment

**Comment by amyeroberts** [comment]
cc @ylacombe @sanchit-gandhi

**Comment by ylacombe** [comment]
Hey @jsoto-gladia, many thanks for opening this issue!

This looks like an interesting finding, do you think you could provide code snippets (both in transformers and in the whisper repo) to allow us to reproduce the finding ?

**Comment by ylacombe** [comment]
Hey @jsoto-gladia, I believe this PR addresses your problem: https://github.com/huggingface/transformers/pull/33917
