### ISSUE TITLE
Request to remove hard dependencies that require CUDA and OpenAI python packages to be downloaded.

### ISSUE THREAD

**Issue by chaudhariatul** [huggingface/transformers#32904]
### Feature request

Request to remove hard dependencies that require CUDA and OpenAI python packages to be downloaded.

### Motivation

Many python packages default to use CUDA and OpenAI and so when developing with non CUDA devices and using different embedding models there are large number of dependencies downloaded.

A docker image created with these requirements often uses upto 9GB and a local python environment uses 5GB or more.

### A reduce storage footprint will allow the following:

1. Small size docker images 
2. Faster downloads and reduce bandwidth usage when downloading images and packages
3. Enable faster deployments
4. Vulnerabilities and security risks are reduced with not including packages that are not required

### Your contribution

I'll test a combination of packages that can help reduce storage footprint.

**Comment by amyeroberts** [comment]
Hi @chaudhariatul, thanks for opening a feature request! 

Could you provide some more context about the packages being downloaded which you think shouldn't be? If one runs `pip install transformers` I don't think there's any specific CUDA or OpenAI packages that should be installed

**Comment by chaudhariatul** [comment]
Hi @amyeroberts,

This is noticed when I pin the package versions as in this example when using these packages to create a docker image:


```
llama-index-embeddings-huggingface==0.2.2
llama-index-llms-ollama==0.2.2
ollama==0.3.1
pypdf==4.3.1
requests==2.32.3
sentence-transformers==3.0.1
streamlit==1.37.1
transformers==4.44.0
xformers==0.0.27.post2
```

Linking this request here : https://github.com/run-llama/llama_index/issues/15526

**Comment by amyeroberts** [comment]
@chaudhariatul I'd suggest opening a feature request in sentence-transformers in this case

**Comment by chaudhariatul** [comment]
Closing this request. Thanks for quick responses!
