### ISSUE TITLE
a lot of examples in doc can't run successful

### ISSUE THREAD

**Issue by policeme** [huggingface/transformers#3291]
I used example in doc, but a lot of example can't run successful, what's wrong?

**Comment by policeme** [comment]
@patrickvonplaten my OS is mac OS 10.14.6, Python 3.6.10, tensorflow 2.0, transformers version is the resoruce code in github

**Comment by patrickvonplaten** [comment]
Hi @policeme, which example did you use?

**Comment by policeme** [comment]
![image](https://user-images.githubusercontent.com/30991932/76741738-050c9280-67ab-11ea-98a2-b3612b6695a9.png)
like this

**Comment by policeme** [comment]
@patrickvonplaten

**Comment by policeme** [comment]
your example like this
![image](https://user-images.githubusercontent.com/30991932/76741937-5288ff80-67ab-11ea-8405-b30c191869fb.png)

**Comment by patrickvonplaten** [comment]
Please don't paste screenshots of your code on issues. Copy and Paste the code in code format. We can't copy the code this way. Typing your code from a screenshot is very time-consuming. 

Considering the problem you have. How did you train the model that was saved in `...ckpt.index`? Did you use this library? From your error message, it seems like your Bert TF model saved in `.ckpt.index` does not have the correct form. 

The example you mention should be used if you trained your model with this library.

**Comment by policeme** [comment]
sorry about it, this is my code
`config = AutoConfig.from_pretrained(r'/Users/maxiong/Workpace/Code/transformers/pre_model/bert_config.json')
tokenizer = AutoTokenizer.from_pretrained(r'/Users/maxiong/Workpace/Code/transformers/pre_model/bert_config.json')
model = AutoModel.from_pretrained(r'/Users/maxiong/Workpace/Code/transformers/pre_model/bert_model.ckpt.index', from_tf=True, config=config)
`
this bert model is from google official chinese bert base model, in your answer, the model can be used with this libary, which was trained by this library, if that, if I want use own pretraning bert model, how to use it with this library
