### ISSUE TITLE
Add method to get loaded adapter names.

### ISSUE THREAD

**Issue by DogitoErgoSum** [huggingface/transformers#32933]
https://github.com/huggingface/transformers/blob/3bb7b05229466ce820f76dadb250a848e7eb22e7/src/transformers/integrations/peft.py#L145C60-L145C76

The raise statement on line 146 feels off because there isn't a method that checks which adapters are already loaded. Implementing this is straightforward, as a similar solution is already in place on line 145 using list(self.peft_config).

**Comment by ArthurZucker** [comment]
Hey, would you like to open a PR for this? 🤗

**Comment by LysandreJik** [comment]
Maybe of interest to @BenjaminBossan

**Comment by BenjaminBossan** [comment]
Sorry, I don't understand what the issue is. Could you please clarify @DogitoErgoSum?

**Comment by DogitoErgoSum** [comment]
@BenjaminBossan There is no method to check which adapters are loaded in the model. The active_adapters() method only returns the adapters that are set, not the ones that are loaded, as far as I understand. When I try to load an adapter that is already present, an error is thrown, and there is no method to check if the adapter exists. Currently, I am using this workaround to find out which adapters are loaded: 
`list(model.peft_config)`

**Comment by DogitoErgoSum** [comment]
Exactly.

I don't think it's necessary because of these two options, although it would make the library more complete. What I believe is more necessary is a method to unload (delete) the adapters from the model.

**Comment by BenjaminBossan** [comment]
Indeed, that would be a good method to add. For the time being, I think this should do the job:

```python
from peft.tuners.tuners_utils import BaseTunerLayer

for module in model.modules():
    if isinstance(module, BaseTunerLayer):
        module.delete_adapter(adapter_name)
```

**Comment by DogitoErgoSum** [comment]
Thanks!

**Comment by BenjaminBossan** [comment]
Ah yes, and don't forget to delete the entry from the `model.peft_config` dict. I added the task to implement this method to my backlog.
