### ISSUE TITLE
Installation error: can not find Rust compiler

### ISSUE THREAD

**Issue by jiyanloveyou** [huggingface/transformers#3296]
I used pip to install transformers like this:
pip install transformers
in the end, I got the error:
   Can not find Rust compiler
while, I have installed rust on my apple computer, please tell me how to deal with the problem, thank you!

**Comment by julien-c** [comment]
Can you please open an issue on https://github.com/huggingface/tokenizers?

Thanks!
cc @n1t0 @mfuntowicz
