### ISSUE TITLE
Error in loading  albert-base-v2

### ISSUE THREAD

**Issue by anjubaoGDUT** [huggingface/transformers#3304]
![image](https://user-images.githubusercontent.com/25845940/76815952-f3be9700-6839-11ea-9ef9-53bc3655cefa.png)
![image](https://user-images.githubusercontent.com/25845940/76815974-020cb300-683a-11ea-830a-8a26b1eb6822.png)

Help~~
The above problems appear in loading the pre-trained Albert by transformers.

**Comment by exchhattu** [comment]
@anjubaoGDUT If you can provide the code in text (instead of image) that can copy and paste, it is easy to test.
