### ISSUE TITLE
ValueError: Unrecognized model. Should have a model_type key in its config.json

### ISSUE THREAD

**Issue by lujain89** [huggingface/transformers#33109]
I have trained a custom transformer model as a sequence-to-sequence model, did not finetune an LLM.

My config doesn't specify the model-type, it is as follows:
config = {
  "architecture": "Seq2SeqTransformer",
  "vocab_size": tokenizer.vocab_size,
  "d_model": d_model,
  "num_layers": num_layers,
  "num_heads": num_heads,
  "dim_feedforward": dim_feedforward,
  "save_steps": save_steps
}

But when I try to load it from huggingface, it gives me this error:
**Lu...... Should have a model_type key in its config.json, or contain one of the following strings in its name: albert, align, altclip......**

I do not know which type should be specified.

Please find the layout of my work in this notebook: https://colab.research.google.com/drive/1qwT4mqaTPoVW7HwlWNRKheR7FAzIdR-L#scrollTo=DtU3whBevE31

**Comment by ArthurZucker** [comment]
Hey! Your notebook seems to have stopped at the:
```
MODEL_MAPPING.update({"seq2seq_transformer": CustomSeq2SeqModel})
```
and did not execute it as the above failed.

**Comment by josecaloca** [comment]
I had the same issue. Basically I was pushing my model `trainer.push_to_hub("model_name")` but I did not set the argument `push_to_hub=True,` in the `TrainingArguments` class.

Following the documentation, It should be like this:

`training_args = TrainingArguments(output_dir="my-awesome-model", push_to_hub=True)`

Reference: https://huggingface.co/docs/transformers/model_sharing
