### ISSUE TITLE
Can not detect bitsandbytes-windows

### ISSUE THREAD

**Issue by ILG2021** [huggingface/transformers#33110]
### System Info

- `transformers` version: 4.39.3
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.10.0
- Huggingface_hub version: 0.24.2
- Safetensors version: 0.4.3
- Accelerate version: 0.33.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.0+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. install bitsandbytes-windows
`python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.2.post2-py3-none-win_amd64.whl`
2. load whisper model in 8 bit:
`model = WhisperForConditionalGeneration.from_pretrained(model_name_or_path, load_in_8bit=True, device_map="cuda:0")
`

### Expected behavior

Can correctly detect bitsandbytes and train model in 8bit on windows

**Comment by matthewdouglas** [comment]
Hi @ILG2021,

Please install the official `bitsandbytes` distribution with:

`python -m pip install -U 'bitsandbytes>=0.43.3'`.

**Comment by ILG2021** [comment]
Hello, @matthewdouglas . Does it support windows? I mean not wsl.

**Comment by matthewdouglas** [comment]
@ILG2021 bitsandbytes has native Windows support [since v0.43.0](https://github.com/bitsandbytes-foundation/bitsandbytes/releases/tag/0.43.0).

**Comment by ILG2021** [comment]
Thank you very much, I get it.

**Comment by x15380885650** [comment]
aaaa

**Comment by x15380885650** [comment]
> Thank you very much, I get it.

dddd
