### ISSUE TITLE
Failed to import transformers.models.t5.modeling_t5 because of the following error 

### ISSUE THREAD

**Issue by Nabeel1232** [huggingface/transformers#33140]
### System Info

from transformers import T5ForConditionalGeneration, GenerationConfig
RuntimeError: Failed to import transformers.models.t5.modeling_t5 because of the following error (look up to see its traceback):
Failed to import transformers.genera

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

!pip install transformers
from transformers import T5ForConditionalGeneration, GenerationConfig

### Expected behavior

the command should import T5ForConditionalGeneration, GenerationConfig

**Comment by aroun-coumar** [comment]
![image](https://github.com/user-attachments/assets/204bbe16-bba6-416e-b14d-0fcb817cc7a5)

i can import properly

**Comment by LysandreJik** [comment]
@Nabeel1232 if you're working in a jupyter notebook, please make sure to restart your runtime after installing a new library.

**Comment by aroun-coumar** [comment]
![image](https://github.com/user-attachments/assets/36f8f714-fe22-497d-9c8c-0b8e030c047f)
![image](https://github.com/user-attachments/assets/540dc11c-c636-480d-aa1f-b6672e595eb0)

Hey sorry couldnt reproduce . Which IDE do you use
