### ISSUE TITLE
Errors with nn.RMSNorm in DeepSpeed

### ISSUE THREAD

**Issue by loadams** [huggingface/transformers#33176]
### System Info

Using the latest transformers from source (newer than the latest 4.44.2 release tag), the changes in [pytorch_utils ](https://github.com/huggingface/transformers/blame/5c1027bf09717f664b579e01cbb8ec3ef5aeb140/src/transformers/pytorch_utils.py#L27) from [this PR](https://github.com/huggingface/transformers/commit/c35d2ccf5a5ebcab24a0b9da3cb2527b3ae565a0) add nn.RMSNorm to the list of modules, but nn.RMSNorm isn't added to torch until the torch 2.4 release, causing CI failures when using DeepSpeed unless we either update torch or pin the transformers version.

### Who can help?

@muellerzr 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Clone latest DeepSpeed or run CI from hpu_gaudi2.yml workflow, failure [here](https://github.com/microsoft/DeepSpeed/actions/runs/10586654075/job/29335873815).

### Expected behavior

Error out when requiring a specific torch version if it doesn't exist, or similar.

**Comment by NielsRogge** [comment]
Fix at #33177

**Comment by loadams** [comment]
Thanks @NielsRogge!

**Comment by loadams** [comment]
Fixed in linked PR, thanks!
