### ISSUE TITLE
Add SDPA implementation to more models

### ISSUE THREAD

**Issue by avishaiElmakies** [huggingface/transformers#33171]
### Feature request

many of the newer models have an sdpa implementation. It could be good that some of the older models get up to speed.

### Motivation

this could be good to unify the API more.
and improve training\inference speed for some of the older models like OPT.

### Your contribution

Might be able to help with a few. this one seems bigger than the other feature request i opened, so will probably need more help

**Comment by LysandreJik** [comment]
Hey @avishaiElmakies, this seems like a duplicate of https://github.com/huggingface/transformers/issues/26350

We'd very much welcome some SDPA additions :hugs:

**Comment by avishaiElmakies** [comment]
@LysandreJik, it says flash attention. So I thought it was a different thing 😅. You can close this if you consider them the same issue. I will try to work on some models in my free time.

**Comment by avishaiElmakies** [comment]
Thanks

**Comment by LysandreJik** [comment]
Thanks @vasqu!
