### ISSUE TITLE
Doc bug: wrong token argument name for Tokenizer.from_pretrained() 

### ISSUE THREAD

**Issue by rravenel** [huggingface/transformers#33183]
### System Info

N/A for doc bug.

### Who can help?

@stevhliu

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://huggingface.co/docs/tokenizers/api/tokenizer#tokenizers.Tokenizer.from_pretrained

from_pretrained
( identifierrevision = 'main'auth_token = None ) → [Tokenizer](https://huggingface.co/docs/tokenizers/v0.13.4.rc2/en/api/tokenizer#tokenizers.Tokenizer)

Parameters

identifier (str) — The identifier of a Model on the Hugging Face Hub, that contains a tokenizer.json file
revision (str, defaults to main) — A branch or commit id
auth_token (str, optional, defaults to None) — An optional auth token used to access private repositories on the Hugging Face Hub

### Expected behavior

'auth_token' is incorrect.

'use_auth_token' works, but with the following warning:

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/modeling_utils.py:3220: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.

'token' also works.

**Comment by LysandreJik** [comment]
Ah, indeed! The docs should be changd! Would you be down to open a PR to update this?

**Comment by rravenel** [comment]
I am brand spanking new here and don't know Rust.

Is this the right file: https://github.com/huggingface/tokenizers/blob/main/bindings/python/src/tokenizer.rs?

And I'm just removing 'auth_' between lines 572 and 613?  Not sure about the instance of 'token' on line 605 - ignore?

I'm also not setup on your doc build tools.  I can take a stab at this next week.

**Comment by stevhliu** [comment]
Thanks for catching this! For the docs, you can edit the docstring [here](https://github.com/huggingface/tokenizers/blob/14a07b06e4a8bd8f80d884419ae4630f5a3d8098/bindings/python/py_src/tokenizers/__init__.pyi#L974 🙂

**Comment by rravenel** [comment]
PR submitted.

**Comment by rravenel** [comment]
Nudge.
