### ISSUE TITLE
Bug in Llama3.1 8B Instruct Tokenizer

### ISSUE THREAD

**Issue by tginart** [huggingface/transformers#33182]
### System Info

- `transformers` version: 4.44.2
- Platform: Linux-5.15.0-1056-aws-x86_64-with-glibc2.31
- Python version: 3.10.14
- Huggingface_hub version: 0.23.3
- Safetensors version: 0.4.3
- Accelerate version: 0.33.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.2.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA H100 80GB HBM3

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. import llama tokenizer
2. get token id for 'Ð¾'
3. test decoding
`tokenizer = AutoTokenizer.from_pretrained('meta-llama/Meta-Llama-3.1-8B-Instruct')`
`tokenizer.get_vocab()['Ð¾']`
- above should give you 1482
`tokenizer.decode(1482)`
- above should give you 'о' (Cyrillic)

### Expected behavior

Seems like a bug or inconsistency between the tokenizer's stated vocabulary and the actual encoding function. This causes confusion and errors in encoding/decoding.

**Comment by itazap** [comment]
Hey @tginart ! This is expected as it is related to how llama trains using `tokenizers.byte_level` and converts characters into bytes that can be mapped to different UTF-8 Unicode characters. For example `о` maps to `Ð¾` which has the encoding `U+043E` both map to  [(utf-8 map table)](https://www.utf8-chartable.de/unicode-utf8-table.pl?start=1024&names=-&utf8=char#:~:text=U%2B043E,%C3%90%C2%BE)

This is discussed in https://github.com/huggingface/tokenizers/issues/254 , https://github.com/huggingface/tokenizers/issues/203, https://github.com/huggingface/tokenizers/issues/268 which might provide more in-depth discussions 🤗 Let me know I can answer more questions about this!
