### ISSUE TITLE
pipelines.ipynb mask should be [MASK]

### ISSUE THREAD

**Issue by shibing624** [huggingface/transformers#3318]
transformers/notebooks/03-pipelines.ipynb fill-mask task, use newest version, <mask> is error, should be [MASK].

**Comment by mfuntowicz** [comment]
Hi @shibing624, 

Thanks for opening this issue.

`fill-mask` pipeline uses Roberta under the hood and the mask token is actually `<mask>` which is the one used in the notebook.

However, it's not the safest way to use the pipeline I agree. I'll update the notebook with 

```python
nlp_fill = pipeline('fill-mask')
nlp_fill('Hugging Face is a French company based in ' + nlp_fill.tokenizer.mask_token)
```

This way it will be compatible why any model.

Morgan

**Comment by mfuntowicz** [comment]
Dont hesitate to reopen if I missed something :)
