### ISSUE TITLE
How to obtain batch index of validation dataset?

### ISSUE THREAD

**Issue by SoumiDas** [huggingface/transformers#33228]
Hi,

I wanted to know how would we fetch the batch id/index of the eval dataset in ```preprocess_logits_for_metrics()``` ?

Thanks in advance!

**Comment by nbroad1881** [comment]
You could put a global variable that keeps track of how many samples have been seen in `preprocess_logits_for_metrics`. 

```python

counter = 0
bs = 16

def preprocess_logits_for_metrics(logits, labels):
    global counter

    counter += logits.shape[0]

    batch_idx = counter % bs

```

Then you would have to calculate the batch idx based on the value of counter. You would also need to reset count after completing evaluation.
