### ISSUE TITLE
'CohereModel' object has no attribute '_prune_heads'

### ISSUE THREAD

**Issue by mnauf** [huggingface/transformers#33235]
### System Info

class `CoherePreTrainedModel` docstring says that "This model inherits from [`PreTrainedModel`]. Check the superclass documentation for the generic methods the library implements for all its model (such as downloading or saving, resizing the input embeddings, **pruning heads** etc.)". However, it doesn't have `prune_heads()` methods, even though it explicitly mentions that it has in the docstring.

![Screenshot 2024-08-31 at 20 54 26](https://github.com/user-attachments/assets/e6c4b029-231e-4a03-84ab-07b9bd41ebec)
@ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoTokenizer, AutoModel

model_id = "CohereForAI/aya-23-8B"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id, device_map="auto", torch_dtype=torch.bfloat16)
model.prune_heads({1: [1]})
```

### Expected behavior

I expect the method to prune heads of the cohere model.

**Comment by mnauf** [comment]
#29622

**Comment by mnauf** [comment]
@saurabhdash2512 Please have a look

**Comment by modifiededition** [comment]
Hey, I’d like to fix this issue. @LysandreJik , you mentioned that the documentation needs updating—could you clarify which specific documentation so I can work on fixing it?

**Comment by jackyjinjing** [comment]
Can I support prune_heads function in this model? @LysandreJik

**Comment by LysandreJik** [comment]
This has been addressed in https://github.com/huggingface/transformers/pull/33253, so I'm closing the issue - thanks all for offering your help!
