### ISSUE TITLE
When will Transformers version 4.45.0 be released?

### ISSUE THREAD

**Issue by hahmad2008** [huggingface/transformers#33236]
### System Info

I installed this version 4.45.0.dev0 repo itself, by using:

`pip install -U git+https://github.com/huggingface/transformers.git `

When this tag `4.45.0` will be officially released?

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

-

### Expected behavior

-

**Comment by LysandreJik** [comment]
Probably next week!

**Comment by LysandreJik** [comment]
It was released, closing this :)
