### ISSUE TITLE
Mask2FormerImageProcessor - fails to process multichannel image

### ISSUE THREAD

**Issue by maciej-adamiak** [huggingface/transformers#33295]
### System Info

- `transformers` version: 4.43.4
- Platform: Linux-6.5.0-1027-oem-x86_64-with-glibc2.35
- Python version: 3.11.9
- Huggingface_hub version: 0.24.6
- Safetensors version: 0.4.4
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.4.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: no
- Using GPU in script?: yes
- GPU type: NVIDIA RTX A4500 Laptop GPU

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

[Colab](https://colab.research.google.com/drive/1T_lGRfyRoQCycZbLJAVsa6c12K5NI7GD?usp=sharing)

### Expected behavior

The image processing should be handled correctly. 

It looks like the [get_max_height_width](https://github.com/huggingface/transformers/blob/174890280b340b89c5bfa092f6b4fb0e2dc2d7fc/src/transformers/models/mask2former/image_processing_mask2former.py#L938) is using a default parameter rather then a value `input_data_format` set in the class constructor.

**Comment by LysandreJik** [comment]
cc @qubvel or @zucchini-nlp in case you have some bandwidth!

**Comment by qubvel** [comment]
Hi @maciej-adamiak , thanks for opening an issue and providing an example to reproduce!

Would you like to make a fix? We should make sure that `input_data_format` is passed to `[get_max_height_width](https://github.com/huggingface/transformers/blob/174890280b340b89c5bfa092f6b4fb0e2dc2d7fc/src/transformers/models/mask2former/image_processing_mask2former.py#L938) and all other transforms correctly handle it.

**Comment by maciej-adamiak** [comment]
I'm on it.
