### ISSUE TITLE
Is it possible to make wasm support all models in huggingface?

### ISSUE THREAD

**Issue by wa008** [huggingface/transformers#33293]
### Feature request

As title
Now, there are several model that support wasm.
1. [whisper.wasm](https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.wasm), which can convert audio to text.
2. [secret-llama](https://github.com/abi/secret-llama): text-to-text LLM, realize by web-gpu
3. web-llm: text-to-text LLM
If it is possible to make a project to support wasm for all huggingface models, this can definitely accelerate the development of LLM.

### Motivation

Wasm have below advantages

1. run locally, no server or extran machine needed, which can help user to try new model without any cost.
2. no any privacy concerns

### Your contribution

I can help to develop related project or function.
I know it will be a huge project,I can not do that by myself.

**Comment by LysandreJik** [comment]
The best suited to answer you is probably @xenova :)

**Comment by xenova** [comment]
Hi @wa008! I responded to a similar question [here](https://huggingface.co/posts/victor/964839563451127#66d7f103559b4669c53df7e6) (maybe you?), so let me copy my response here:

> We have Transformers.js, the JavaScript/WASM/WebGPU port of the python library, which supports ~100 different architectures.
> - Docs: https://huggingface.co/docs/transformers.js
> - Repo: http://github.com/xenova/transformers.js
> 
> Is that the kind of thing you're looking for? :)

**Comment by wa008** [comment]
> Hi @wa008! I responded to a similar question [here](https://huggingface.co/posts/victor/964839563451127#66d7f103559b4669c53df7e6) (maybe you?), so let me copy my response here:
> 
> > We have Transformers.js, the JavaScript/WASM/WebGPU port of the python library, which supports ~100 different architectures.
> > 
> > * Docs: https://huggingface.co/docs/transformers.js
> > * Repo: [http://github.com/xenova/transformers.js](https://github.com/xenova/transformers.js)
> > 
> > Is that the kind of thing you're looking for? :)

Yes, this project is great! Thanks a lot.
