### ISSUE TITLE
for LlaVA output of image_hidden_states not possible?

### ISSUE THREAD

**Issue by 7AtAri** [huggingface/transformers#33329]
### System Info

ubuntu, containerized development

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://stackoverflow.com/questions/78631255/how-to-extract-image-hidden-states-in-llavas-transformers-huggingface-impleme

apparently others than myself have already had this issue as well...

### Expected behavior

should output the image_hidden_states but returns a none type object without any content

**Comment by zucchini-nlp** [comment]
Hey @7AtAri ! Yes, unfortunately VLMs currently don't return `image_hidden_states`, and I had it in my TODO list. I might take longer to make a PR for that, so if you want to give it a try a PR is welcome :)

**Comment by 7AtAri** [comment]
thanks! I used a forward hook meanwhile, but having a method is definitely much more convenient...

**Comment by zucchini-nlp** [comment]
The model now returns hidden states for images after a forward pass (see linked PR 😉 ). But it will not work for generate as `generate()` usually doesn't return extra outputs from the model which are too model-specific

**Comment by cyj95** [comment]
> forward hook

can you share your forward hook code? I WANT to get hidden states of llava with gradient.

**Comment by 7AtAri** [comment]
I think the new hidden states feature should provide the hidden states with a gradient as well. @zucchini-nlp am I correct? It should also be more convenient to use.

**Comment by zucchini-nlp** [comment]
@7AtAri Yes, it can provide hidden states with gradient as long as the vision tower is running the `forward` with gradients. The returned states are simply the outputs from vision tower + mm projector
