### ISSUE TITLE
How do LLMs identify generation start point during fine-tuning?

### ISSUE THREAD

**Issue by naphatkps** [huggingface/transformers#33337]
When fine-tuning an LLM, we pass a long string containing `context`, `user input`, and `the expected answer`. How does the model know which word to start generating from.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
