### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by BaneTrifa** [huggingface/transformers#33347]
### System Info

transfromers version: 4.44.2
pytorch version: 2.4.1+cu118

### Who can help?

@gante @ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm trying to run the official BERT test (**tests/models/bert/test_modeling_bert.py**) for the purpose of debugging my own code. However, when I run the test, I get the following error:
```
Traceback (most recent call last):
  File "/home/huggingface/transformers/tests/models/bert/test_modeling_bert.py", line 30, in <module>
    from ...generation.test_utils import GenerationTesterMixin
ImportError: attempted relative import with no known parent package
```

I've seen a few solutions for similar issues, but none of them solved my problem.

### Expected behavior

I expect to run official BERT tests without import errors.

**Comment by gante** [comment]
Hi @BaneTrifa 👋 Thank you for opening this issue

You should be able to run tests if you are in the transformers root folder (e.g. you can call `py.test tests/models/bert/test_modeling_bert.py`). Our tests use relative paths and have this assumption.

**Comment by BaneTrifa** [comment]
@gante It solved my problem. Thanks
