### ISSUE TITLE
[Docs] How to build offline HTML or Docset files for other documentation viewers?

### ISSUE THREAD

**Issue by hologerry** [huggingface/transformers#33359]
### Feature request

How can I build the docs into HTML files for use with other documentation viewers like [Dash](https://www.kapeli.com/dash) , [Dash-User-Contributions](https://github.com/Kapeli/Dash-User-Contributions)?

I successfully built the PyTorch docs for Dash by working directly in their `docs/` directory. I’m wondering if a similar process exists for Hugging Face libraries.

### Motivation

The Dash docset viewer is very useful for viewing multiple documentation sets in one place, even offline. It would be great to support it and include all Hugging Face libraries.

### Your contribution

I’ve built the PyTorch docs for Dash, so I’m familiar with incorporating and generating docsets.

**Comment by LysandreJik** [comment]
Hey @hologerry, a guide is available here to build the docs: https://github.com/huggingface/transformers/tree/main/docs

**Comment by hologerry** [comment]
@LysandreJik Thanks.
