### ISSUE TITLE
Pipelines download the latest revision by default instead of the default/output revision

### ISSUE THREAD

**Issue by ankane** [huggingface/transformers#33365]
### System Info

- `transformers` version: 4.44.2
- Platform: macOS-14.6.1-arm64-arm-64bit
- Python version: 3.12.5
- Huggingface_hub version: 0.24.5
- Safetensors version: 0.4.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.3.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: no

### Who can help?

@Narsil 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier("We are very happy to show you the 🤗 Transformers library.")
```

outputs

```text
No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
```

However, it downloads the `main` revision instead of `af0f99b`.

From what I can tell, this happens with all of the pipelines.

Edit: I believe it was broken in dc9147ff362e4e69829f64d28178c77cab4bef6f shortly after being added (e4d2588573f2c68eb792f2d11f092eb2c562bef5)

### Expected behavior

The downloaded revision is consistent with the output.

Adding `revision` to `hub_kwargs`  seems to fix it, but it'd probably be good to update the defaults to the latest version of each model (since that's the current behavior).

```diff
--- a/src/transformers/pipelines/__init__.py
+++ b/src/transformers/pipelines/__init__.py
@@ -860,6 +860,7 @@ def pipeline(
             f" {revision} ({HUGGINGFACE_CO_RESOLVE_ENDPOINT}/{model}).\n"
             "Using a pipeline without specifying a model name and revision in production is not recommended."
         )
+        hub_kwargs['revision'] = revision
         if config is None and isinstance(model, str):
             config = AutoConfig.from_pretrained(model, _from_pipeline=task, **hub_kwargs, **model_kwargs)
             hub_kwargs["_commit_hash"] = config._commit_hash
```

**Comment by LysandreJik** [comment]
Thanks @ankane! Would you like to open a PR to fix this?

**Comment by ankane** [comment]
Just opened #33395.
