### ISSUE TITLE
Fast vs. slow tokenizer mismatch for special tokens with lstrip/rstrip set to true

### ISSUE THREAD

**Issue by xenova** [huggingface/transformers#33371]
### System Info

- `transformers` version: 4.45.0.dev0
- Platform: Linux-6.5.0-1025-azure-x86_64-with-glibc2.31
- Python version: 3.10.13
- Huggingface_hub version: 0.24.5
- Safetensors version: 0.4.4
- Accelerate version: 0.33.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.0+cu121 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: no

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code to reproduce:
```py
from transformers import AutoTokenizer
slow = AutoTokenizer.from_pretrained("distil-whisper/distil-small.en", use_fast=False)
fast = AutoTokenizer.from_pretrained("distil-whisper/distil-small.en", use_fast=True)
text = "   <|startoftranscript|> <|en|>   "

print(slow.tokenize(text))  # ['<|startoftranscript|>', '<|en|>']
print(fast.tokenize(text))  # ['   <|startoftranscript|> ', '<|en|>   ']
print(slow.encode(text))    # [50257, 50362, 50257, 50258, 50256]
print(fast.encode(text))    # [50257, 50362, 50257, 50258, 50256]
```

Although the token ids match (`.encode`), the tokenized strings (`.tokenize`) are different.

### Expected behavior

Intuitively, I would expect `.tokenize` to have the lstrip and rstrip applied (i.e., the same as the slow tokenizer), so this may be an issue with `tokenizers` (cc @Narsil)

**Comment by ArthurZucker** [comment]
I can reproduce, this is completely expected and inherent to the way `tokenizers` works. `tokenizers` removes the spaces kind of afterwards. Closing as tokens are not the absolute source of truth
