### ISSUE TITLE
Using P-tuning On Whisper‘s decoder

### ISSUE THREAD

**Issue by dengchengxifrank** [huggingface/transformers#33388]
### System Info

- `transformers` version: 4.44.2
- Platform: Linux-3.10.0-1160.59.1.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.0
- Huggingface_hub version: 0.24.6
- Safetensors version: 0.4.2
- Accelerate version: 0.33.0
- Accelerate config:    not found
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA A40

### Who can help?

@sanchit-gandhi @ylacombe . Hi, I want to perform p-tuning on whisper's decoder, but I found that in the process of trainer.train(), I can get the embedding through nn.Parameters and concatenate these embeddings to the output embedding, but when evaluating, the model will call the forward function, and in the first forward step, the model stipulates the prefix token of the input as [startoftranscirpt,en,transcribe,notimestamps], and generates a character in each subsequent step. I wonder how to use the trained embedding for the decoding process during evaluation in this case.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Using nn.Paramters()

### Expected behavior

Using the trained parameters for decode

**Comment by ylacombe** [comment]
Hi @dengchengxifrank, thanks for opening this issue! 
I'm not sure to follow what's the issue and what you're trying to accomplish here!
Do you think you could:
1. explain a bit more what's going on
2. share a small code snippet to reproduce your issue
3. share your logs if there's an issue
?

Many thanks

**Comment by dengchengxifrank** [comment]
Hi @ylacombe ， My question can be summarized as follows: I have a tensor of shape [4, 1024]. I want to concatenate this tensor to the front of the initial token as a condition when whisper uses model.generate(). I want to know where I should add the codes, because there is only init_tokens in the model.generate function(), and no embedding. I'm sorry that I don't have any codes to provide.
