### ISSUE TITLE
Support AdEMAMix optimizer

### ISSUE THREAD

**Issue by fakerybakery** [huggingface/transformers#33392]
### Feature request

Add support for the AdEMAMix optimizer

Paper: https://arxiv.org/abs/2409.03137
Implementation: https://github.com/nanowell/AdEMAMix-Optimizer-Pytorch

### Motivation

The AdEMAMix optimizer is a new optimizer from Apple that claims to have better performance and slows down forgetting.

### Your contribution

N/A

**Comment by Theodotus1243** [comment]
Implemented here
https://github.com/bitsandbytes-foundation/bitsandbytes/releases/tag/v0.44.0
