### ISSUE TITLE
Support Pixtral

### ISSUE THREAD

**Issue by fakerybakery** [huggingface/transformers#33441]
### Feature request

Hi,
It would be great to have support for Pixtral!
https://huggingface.co/mistral-community/pixtral-12b-240910
thanks!

### Motivation

Pixtral is a new model released by Mistral AI

### Your contribution

N/A

**Comment by paulmartrencharpro** [comment]
FYI, it was implemented in vllm by Mistral with the PRs https://github.com/vllm-project/vllm/pull/8377 & https://github.com/vllm-project/vllm/pull/8399

**Comment by LysandreJik** [comment]
Thanks for the request, the pull request will be opened shortly!

**Comment by LysandreJik** [comment]
You can follow the development here: https://github.com/huggingface/transformers/pull/33449
