### ISSUE TITLE
release plan for 4.45 ?

### ISSUE THREAD

**Issue by jinzhen-lin** [huggingface/transformers#33457]
Hi, is there any release plan for 4.45? We want to use qwen2-vl which is added two weeks ago, and it is difficult to install transformers from github in our internal network.

**Comment by LysandreJik** [comment]
Hey @jinzhen-lin, likely today :)

**Comment by jinzhen-lin** [comment]
> Hey @jinzhen-lin, likely today :)

Great! Thank you!
