### ISSUE TITLE
Tokenizer encode with fast or not get different tokens

### ISSUE THREAD

**Issue by bugm** [huggingface/transformers#33488]
### System Info

- `transformers` version: 4.44.2
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
- Python version: 3.9.19
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.3
- Accelerate version: 0.32.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.1+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA A40

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

when run code below (where /data/mengzhangyuan/model/llama2-tokenizer includes tokenizer files download from 
https://huggingface.co/meta-llama/Llama-2-7b-hf )
```
text = "▁<unk>Hey"
t = AutoTokenizer.from_pretrained("/data/mengzhangyuan/model/llama2-tokenizer",use_fast=False)
print(t.encode(text))
print(t.tokenize(text))
print("*"*10)
t2 = AutoTokenizer.from_pretrained("/data/mengzhangyuan/model/llama2-tokenizer",use_fast=True)
print(t2.encode(text))
print(t2.tokenize(text))
```
The results show
```
[1, 259, 0, 29950, 1032]
['▁▁', '<unk>', 'H', 'ey']
**********
[1, 259, 0, 18637]
['▁▁', '<unk>', '▁Hey']
```

With same text,  the tokens are different.

### Expected behavior

use_fast = True and use_fast = False produce same result

**Comment by aroun-coumar** [comment]
pre tokenization differs in both the tokenizers
thus subword tokenization differs AFAIK
