### ISSUE TITLE
HQQ

### ISSUE THREAD

**Issue by blap** [huggingface/transformers#33518]
### System Info

- `transformers` version: 4.44.2
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.11
- Huggingface_hub version: 0.24.7
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config:    not found
- PyTorch version (GPU?): 2.6.0.dev20240915+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA GeForce MX330

And: 
python.exe -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124
python.exe -m pip install --upgrade transformers
python.exe -m pip install --upgrade git+https://github.com/mobiusml/hqq.git
python.exe -m pip install --upgrade huggingface_hub

### Who can help?

@SunMarc

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

# from https://huggingface.co/docs/transformers/v4.44.2/quantization/hqq
```

from transformers import AutoModelForCausalLM, AutoTokenizer, HqqConfig

# Method 1: all linear layers will use the same quantization config
quant_config  = HqqConfig(nbits=8, group_size=64, quant_zero=False, quant_scale=False, axis=0) #axis=0 is used by default

model = transformers.AutoModelForCausalLM.from_pretrained(
    "meta-llama/Meta-Llama-3-8B-Instruct", 
    torch_dtype=torch.float16, 
    device_map="cuda", 
    quantization_config=quant_config
)

```
Error:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\hqq\hqq2.py", line 4, in <module>
    quant_config  = HqqConfig(nbits=8, group_size=64, quant_zero=False, quant_scale=False, axis=0) #axis=0 is used by default
  File "C:\Users\Admin\Desktop\hqq\venv\lib\site-packages\transformers\utils\quantization_config.py", line 228, in __init__
    from hqq.core.quantize import BaseQuantizeConfig as HQQBaseQuantizeConfig
  File "C:\Users\Admin\Desktop\hqq\hqq.py", line 3, in <module>
    from hqq.models.hf.base import AutoHQQHFModel
ModuleNotFoundError: No module named 'hqq.models'; 'hqq' is not a package

### Expected behavior

Quantized model.

**Comment by ananddtyagi** [comment]
This may be due to your file being named hqq that is in the path `C:\Users\Admin\Desktop\hqq\hqq.py` . I'd suggest naming that something else and seeing if that resolves your issue.

**Comment by blap** [comment]
> This may be due to your file being named hqq that is in the path `C:\Users\Admin\Desktop\hqq\hqq.py` . I'd suggest naming that something else and seeing if that resolves your issue.

Solved. Thank you!
