### ISSUE TITLE
from_pretrained callback?

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#33540]
I have a model implement from PretrainModel, how can I set a from_pretrianed call back in my model class?

I want call some weigths re-initialize when MyModel.from_pretrained

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

Thanks!
