### ISSUE TITLE
Wrong ValueError in modeling_videomae.py?

### ISSUE THREAD

**Issue by HadiHammoud44** [huggingface/transformers#33547]
### System Info

Hello, 

In **line 928** of modeling_videomae.py, I was wondering if the condition and `ValueError `raised is _wrong_ as **line 883** already checks if `num_channels != 3` and if so, does not _unnormalize_. Whilst the `else` block of line 928 is concerned with 'not normalizing' the pixels and not 'unnormalizing' in the sense of reversing the preprocessing steps (**line 887**). Even though I am setting `norm_pix_loss = False` when using `num_channels = 1`, I am still getting a `ValueError: Can't unnormalize non-RGB images. Consider setting config.norm_pix_loss to False.` 

Thank you in advance.

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

Not needed

### Expected behavior

N/A

**Comment by LysandreJik** [comment]
cc @NielsRogge
