### ISSUE TITLE
License information by model

### ISSUE THREAD

**Issue by alexcombessie** [huggingface/transformers#3357]
Hi,

First of all, thanks for the good work. Very useful.

Would it be possible to add the license information for each model listed on https://huggingface.co/transformers/pretrained_models.html?
The reason is that for production, I need to know which models can be bundled in my app. Some licenses do not allow bundling...

I may have missed it, but I could not find licensing information in the doc or code.

If that information is not centralized, I am happy to do the research myself (and share results!). I would be interested in hints if you have some.

Cheers,

Alex

**Comment by julien-c** [comment]
Good question. As far as I can tell (I don't think there's a definitive a.k.a legally tested answer to that question) a model is not considered as a derivative work from the dataset(s) it was trained on, so the person who trained the model can choose whatever licensing option they want.

For instance, the original [BERT weights](https://github.com/google-research/bert) mention: 
> We will not be able to release the pre-processed datasets used in the paper.
> [...]
> These models are all released under the same license as the source code (Apache 2.0).

Please share your findings if you conduct more extensive research.

**Comment by alexcombessie** [comment]
Thanks. That's what I assumed as well. Based on the linked you shared, it seems that all BERT models are under the same license. If that's the case for other model architectures, the investigation should be simple. I will look at the ~15 architectures supported and share my findings this week.

I have a separate question on language support by model, but I will submit it as a separate issue.

Have a great day,

Alex

**Comment by alexcombessie** [comment]
Hi @julien-c,

I really liked your suggestion on #3397 to add it to model cards.

Could I add license information in the same way, using tags on the model card?

Cheers,

Alex

**Comment by julien-c** [comment]
Yes @alexcombessie feel free to do some research and open a PR. You can add a `license: x` tag to the metadata, where `x` is an identifier found in https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

A few additional data points:
- Camembert: MIT (source: https://camembert-model.fr/)

**Comment by alexcombessie** [comment]
FYI @MobiusLooper

**Comment by julien-c** [comment]
The Distil* models trained at Hugging Face are released under Apache 2.0.
