### ISSUE TITLE
NER workflow improvement

### ISSUE THREAD

**Issue by ain-soph** [huggingface/transformers#33579]
### Feature request

1. [run_ner.py in examples](https://github.com/huggingface/transformers/blob/main/examples/pytorch/token-classification/run_ner.py) are requiring data of pre-tokenized words, like [conll2003 dataset](https://huggingface.co/datasets/eriktks/conll2003), where texts have been splitted into words. However, the [TokenClassificationPipeline](https://huggingface.co/docs/transformers/v4.44.0/en/main_classes/pipelines#transformers.TokenClassificationPipeline) has no such pre-tokenization but simply aggregate pre-entities by checking [is_subword](https://github.com/huggingface/transformers/blob/984bc11b0882ff1e5b34ba717ea357e069ceced9/src/transformers/pipelines/token_classification.py#L396) using whitespace separator.
This might work somehow on English words, but would fail when it is inconsistent with pre-tokenization used in training data (which would raise multiple `B-` for all sub-tokens in one pre-token)
**My solution:** In the `TokenClassificationPipeline`, use the pre-tokenizer to mark `is_subword` for all non-first sub-tokens to aggregate them in `gather_pre_entities`.
2. `run_ner.py` shall support chunks during training. For example, XLM-Roberta-Base supports 512 as the maximum sequence length, and we might suffer with memory concern to limit the sequence length during training for large models. In this case, it might be better to split long training data into chunks (with certain overlapping) to fully utilize the information instead of truncation.
3. For `label_all_tokens` argument in `run_ner.py`, it means we currently have 2 options for sub-token labelling: `first` and `all`. It might be better to provide a `last` option to better support for Decoder-only models. See https://github.com/huggingface/transformers/issues/15389#issuecomment-1387305312

### Motivation

Included in Feature request Section.

### Your contribution

I currently implement some parts of them in some private confidential codes during work. I would help if repo maintainers think it worth doing.

**Comment by LysandreJik** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
Yes, I'd definitely support a PR to update the pipelines/examples for non-English languages!

**Comment by ain-soph** [comment]
Sadly I cannot submit such PR due to some reasons, maybe years later...
