### ISSUE TITLE
Downloading mlm-17-1280 community model

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#3358]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): mlm-17-1280

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```
from transformers import AutoConfig
conf = AutoConfig.from_pretrained('mlm-17-1280')
```

## Expected behavior

The config should be loaded correctly.
All files exist are seem to be correct. There seems to be a problem with the etag.
When debugging, the call jumps into this statement:
https://github.com/huggingface/transformers/blob/8becb732931bbab5dd75cca5f5e7c75b2516d10b/src/transformers/file_utils.py#L449

and never manages to store the `config.json` file. Not sure what's going on here.

## Environment info

     
- `transformers` version: 2.5.1
- Platform: Linux-5.3.0-40-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.4.0+cpu (False)
- Tensorflow version (GPU?): 2.1.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
@julien-c

**Comment by julien-c** [comment]
This was a bogus model file, rm'ed it.
