### ISSUE TITLE
A mismatch in the docs

### ISSUE THREAD

**Issue by fkrasnov2** [huggingface/transformers#33645]
### System Info

Hi,
Everything's going great with DeBERTa, thanks a lot! 

There's a tiny bit of a mismatch in the docs.

![image](https://github.com/user-attachments/assets/3c56c65d-51f9-48e2-9663-0e90d92a1a53)

Hey, no biggie, but if it's important, I can fix it. Just let me know.

Best,
Fedor

### Who can help?

@stevhliu

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/blob/78b2929c0554b79e0489b451ce4ece14d265ead2/src/transformers/models/deberta/configuration_deberta.py#L43

### Expected behavior

https://github.com/huggingface/transformers/blob/78b2929c0554b79e0489b451ce4ece14d265ead2/src/transformers/models/deberta/configuration_deberta.py#L105

**Comment by molbap** [comment]
Hi @fkrasnov2 ! For sure, feel free to open a doc PR :)

**Comment by LysandreJik** [comment]
I believe this can be closed as #33713 was just merged, but feel free to reopen in case you'd like to do additional fixes!
