### ISSUE TITLE
Attentions Behavior are different

### ISSUE THREAD

**Issue by efsotr** [huggingface/transformers#33676]
### System Info

x

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/blob/v4.44.2/src/transformers/models/llama/modeling_llama.py#L658C9-L667C10

The Attention.is_causal of models like Llama, Gemma2, and Mistral cannot be used in eager, sdpa, but can be used in flash attention 2. This does not align with the expectation of changing a causal model to a bidirectional model after setting Attention.is_causal to False.

### Expected behavior

x

**Comment by LysandreJik** [comment]
Thanks @efsotr, we are indeed aiming to reduce these differences and align everything; it'll likely be much simpler as we adopt `FlexAttention` from PyTorch. Stay tuned!

**Comment by ArthurZucker** [comment]
#34282 for more details!
