### ISSUE TITLE
Add a language model probability pipeline

### ISSUE THREAD

**Issue by ianporada** [huggingface/transformers#33670]
### Feature request

A common use case of language models is to estimate the probability (or log-probability, or perplexity) of a sequence of tokens. It could be convenient to add a pipeline that returns the log-probability / score of a sequence.

### Motivation

It's possible to calculate model predictions for the probability of a sequence, e.g.: https://huggingface.co/docs/transformers/en/perplexity

But pipelines automatically handle tokenization, batching, etc. so it would be more convenient to have a pipeline.

Alternatively, it might be possible to achieve this behavior by creating a "text-generation" pipeline and calling the pipeline with  `max_new_tokens=0` as well as passing certain `generate_kwargs` to get the sequence LM scores, but how to do this is not immediately obvious.

### Your contribution

This should be quite easy to achieve by creating a new pipeline with `_forward` essentially containing the logic for calculating sequence probability at https://huggingface.co/docs/transformers/en/perplexity

**Comment by LysandreJik** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
Hmmn, it's an interesting idea but I'm not sure it justifies a pipeline. The main reason is that calculating sequence perplexity is something that more advanced users do, but the implementation is quite simple using lower-level tools than pipelines. Therefore, I suspect the users who would want this mostly don't need the pipeline!

**Comment by ianporada** [comment]
Personally I am a big fan of the ease of use of pipelines (because they automatically handle a lot of things) and would use such a pipeline, and I believe many may be interesting in getting a "score" for a sequence probability even if not an advanced user looking to calculate perplexity (in the same way that many non-experts are interested in prob. scores for token classification or QA pipelines).

@Rocketknight1 I do agree with the sentiment that this use case might not justify an entirely new pipeline. Do you think it would make sense to add something like a "score" option to text-generation?

**Comment by LysandreJik** [comment]
Hey @ianporada, we also have custom pipelines that you can push to the Hub for others to use: https://huggingface.co/docs/transformers/add_new_pipeline#share-your-pipeline-on-the-hub

In case you're interested in doing that to make your pipeline available to others :slightly_smiling_face:

**Comment by ianporada** [comment]
Thanks! I didn't know about that. I'll close this request and look to create a custom pipeline if I get the chance.

**Comment by LysandreJik** [comment]
Awesome! Don't hesitate to share it back here so that we can check it out!
