### ISSUE TITLE
AutoTokenizer for XGLM model not working properly

### ISSUE THREAD

**Issue by amirrezamirzaei** [huggingface/transformers#33683]
### System Info

- `transformers` version: 4.44.2
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.24.7
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.4.1+cu121 (False)
- Tensorflow version (GPU?): 2.17.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (cpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Using distributed or parallel set-up in script?: no

### Who can help?

@ArthurZucker @itazap

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
from transformers import XGLMTokenizer, AutoTokenizer

xglm_tok = XGLMTokenizer.from_pretrained("facebook/xglm-2.9B")
auto_tok = AutoTokenizer.from_pretrained("facebook/xglm-2.9B")

print(xglm_tok.encode('a ')) # [2, 11]
print(auto_tok.encode('a ')) # [2, 11, 6]
```

### Expected behavior

both the tokenizer should output the same ids.

**Comment by RUFFY-369** [comment]
Hi @amirrezamirzaei , it happens because both statements load different tokenizer. `xglm_tok` loads `transformers.models.xglm.tokenization_xglm.XGLMTokenizer` and `auto_tok` loads the fast version`transformers.models.xglm.tokenization_xglm_fast.XGLMTokenizerFast`

**Comment by amirrezamirzaei** [comment]
@RUFFY-369 I see thank you. Closing this issue.
