### ISSUE TITLE
The Sink Cache looks wired

### ISSUE THREAD

**Issue by why-in-Shanghaitech** [huggingface/transformers#33691]
### System Info

- `transformers` version: 4.44.2
- Platform: Linux-5.15.0-86-generic-x86_64-with-glibc2.35
- Python version: 3.9.19
- Huggingface_hub version: 0.24.6
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config:    not found
- PyTorch version (GPU?): 2.6.0.dev20240914 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker, @zucchini-nlp

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/blob/75b7485cc72bf7122094b943af9f7d26d69ff827/src/transformers/cache_utils.py#L985-L1006

I find the sink cache does not shift the ROPE positional encoding of the new `key_states`. This would lead to
1. The positional encoding is not consecutive in all the keys;
2. In later generation rounds, the positional encoding is not like what we expected.

Since I'm not quite sure about this, I raise this issue before making a PR. Point it out if I was wrong.

### Expected behavior

It seems that after fixing this the model behavior will be more closed to [the original streamingllm implementation](https://github.com/mit-han-lab/streaming-llm/tree/main), but indeed I couldn't find a good way to test this.

I am very confused about how it could pass the test: https://github.com/huggingface/transformers/blob/317e069ee7f4d6d6595b1b03b5d9adcaede043e3/tests/utils/test_cache_utils.py#L336-L376 (though it fails on my end, the generated text is still reasonable). In this test, the `key_states` will have position encodings inrelevent to the cache size (say we have a sinkcahe with window size 256, the key state may have rope position 300. may be related #32315. If we generate texts manually so that the input positional ids and cache positions are None, the key state position will be starting from at most 257.).

**Comment by LysandreJik** [comment]
cc @tomaarsen maybe :)
