### ISSUE TITLE
Export-to-ExecuTorch via transformers.js integration

### ISSUE THREAD

**Issue by guangy10** [huggingface/transformers#33708]
### Feature request

Integrate `ExecuTorch` as a new backend to transformers.js, enabling an new ["Export to ExecuTorch"](https://github.com/huggingface/transformers/issues/32253) workflow through web browser

This feature will require ExecuTorch runtime w/ backend/kernels can be compiled for WebAssembly first. This task is tracked in ExecuTorch repo: https://github.com/pytorch/executorch/issues/3497

### Motivation

Enable a new e2e workflow for on-device ML use-cases via [ExecuTorch](https://github.com/pytorch/executorch)

### Your contribution

TBD

**Comment by LysandreJik** [comment]
Should this be moved to the transformers.js repo? :slightly_smiling_face: 

cc @xenova

**Comment by xenova** [comment]
> Should this be moved to the transformers.js repo? 🙂
> 
> cc @xenova

I agree :) @guangy10 feel free to re-open [here](https://github.com/xenova/transformers.js/issues/new/choose).

**Comment by guangy10** [comment]
Opened https://github.com/huggingface/transformers.js/issues/1039 in transformers.js, and close this one
