### ISSUE TITLE
`processing_mllama.py` has a bug?

### ISSUE THREAD

**Issue by Neo9061** [huggingface/transformers#33706]
### System Info

v4.45.0

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

In https://github.com/huggingface/transformers/blob/f2c388e3f946862f657acc1e21b272ec946fc66c/src/transformers/models/mllama/processing_mllama.py#L305

should the code be following?

```
not all(batch_img_per_prompt == b for batch_img_per_prompt, b in zip(n_images_in_text, n_images_in_images))
```

### Expected behavior

The above code failed when you passed in a batch of examples

**Comment by ArthurZucker** [comment]
It is expected to fail if you have a batch with no image in a sample, and images in an another one. Tho it should not fail for batch of 1 image in a sample and more in another one, as I suppose the batch would get padded and you can ignore them. Opening a PR in a bit! 🤗
