### ISSUE TITLE
Misleading warning

### ISSUE THREAD

**Issue by krisztian-gajdar** [huggingface/transformers#33719]
https://github.com/huggingface/transformers/blob/main/src/transformers/tokenization_utils_base.py#L1618C1-L1619C1

The removal of this warning did not happen in v4.45

cc: @ArthurZucker and @itazap

**Comment by itazap** [comment]
patched! https://github.com/huggingface/transformers/releases/tag/v4.45.1 Thanks for flagging!

**Comment by krisztian-gajdar** [comment]
@itazap I'm still getting the same warning after upgrading to v.4.45.1

**Comment by itazap** [comment]
should be fixed now, sorry about that! there were 2 warnings to remove there

**Comment by krisztian-gajdar** [comment]
This should be it, thanks for the effort @itazap !
