### ISSUE TITLE
Add Flash Attention Support to Mllama (Llama 3.2)

### ISSUE THREAD

**Issue by shermansiu** [huggingface/transformers#33739]
### Feature request

Please add flash attention support to Llama 3.2!

### Motivation

The code will run faster with flash attention.

### Your contribution

When I have time, I can try to submit a PR, but I've been really busy lately.

**Comment by vasqu** [comment]
There are already SDPA implementations included which can leverage flash attention if it is installed. You also can control which backends can / will be used.

See the torch docs over here for SDPA: https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html

You can also refer to the huggingface docs over here: https://huggingface.co/docs/transformers/v4.45.1/perf_infer_gpu_one (under "PyTorch scaled dot product attention")

**Comment by LysandreJik** [comment]
As @vasqu mentions, Llama already supports FA2 + SDPA!

I'm closing the issue, but feel free to reopen if something is unclear
