### ISSUE TITLE
RobertaTokenizer doesn't have 'batch_encode_plus'

### ISSUE THREAD

**Issue by amaloraini** [huggingface/transformers#3377]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): RoBERTa

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

Following the tutorial on how to train your own RoBERTa model in this [link](https://huggingface.co/blog/how-to-train)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

Fill mask

## To reproduce

1. I pretrained my own tokenizer and roberta model 
2.  The tokenizer and model are loaded fine and both seems to have the training information 
3. However, when I join them together in the  pipeline step as in:
`tokenizer = RobertaTokenizer.from_pretrained('./eo_data')`
`rmodel = RobertaForMaskedLM.from_pretrained('./output_dir')`
`fill_mask = pipeline(
    "fill-mask",
    model=rmodel,
    tokenizer= tokenizer
)
`

 I get the following error:
`
AttributeError: 'RobertaTokenizer' object has no attribute 'batch_encode_plus'
`
It seems that RobertaTokenizer doesn't have the batch_encode_plus function as BertTokenizer 

## Environment info

     
- `transformers` version: 2.5.1
- Platform: Ubuntu 
- Python version: 3.6.8
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

Thank you

**Comment by LysandreJik** [comment]
Hi, this is probably because you're using an old version of `transformers`. Version 2.8 doesn't exist, the latest is 2.5.1 ...

**Comment by amaloraini** [comment]
Sorry, I accidently put 2.8. The version I have is: 2.5.1
I am going to edit the post.

**Comment by esradonmez** [comment]
Started getting the same issue today. Is there a known solution?
