### ISSUE TITLE
Data Processor should not include in the package

### ISSUE THREAD

**Issue by Liangtaiwan** [huggingface/transformers#3379]
# 🚀 Feature request

For a clearly, flexible packages, I think there is no need including data processor for certain data.

## Motivation

In the past, it was easy using transformers to do research, since the module is explicit and clear.
When reading example, it was easy tracing the code to apply on a new dataset.
However, recently transformers merged some unrelated module into the package like Data Processor, making hard to modify the preprocess stage.

**Comment by pohanchi** [comment]
Agree and I follow you.
