### ISSUE TITLE
`modeling_mllama.py`

### ISSUE THREAD

**Issue by HanGyeol-Yoo** [huggingface/transformers#33812]
### System Info

v4.45.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

In
https://github.com/huggingface/transformers/blob/2e24ee4dfa39cc0bc264b89edbccc373c8337086/src/transformers/models/mllama/modeling_mllama.py#L1438-L1456

The example shows that when printing the shape of last_hidden_state, it outputs "torch.Size([1, 1, 4, 1025, 7680])". 
However, when I run it directly, it outputs "torch.Size([1, 1, 4, 1601, 7680])". Is this an error in the example?

### Expected behavior

It seems the example is incorrect.

**Comment by qubvel** [comment]
Hi, it depends on the model configuration, probably you are using instruct or 90B version?

**Comment by HanGyeol-Yoo** [comment]
> Hi, it depends on the model configuration, probably you are using instruct or 90B version?

I used the 11B Inst version and got the output "torch.Size([1, 1, 4, 1601, 7680])".
I confirmed that the output is different because the Config of the PT version and the Inst version of the model are different. Thank you!

**Comment by qubvel** [comment]
Yes, it depends on image size parameter, for Instruct and 90B models image size is 560, while for 11B base model it's 448.
