### ISSUE TITLE
The CPU memory does not free in the jupyter notebook

### ISSUE THREAD

**Issue by gxcuit** [huggingface/transformers#33811]
### System Info

- `transformers` version: 4.45.1
- Platform: Linux-5.15.154+-x86_64-with-glibc2.35
- Python version: 3.10.14
- Huggingface_hub version: 0.25.0
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.4.0 (True)
- Tensorflow version (GPU?): 2.16.1 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26.dev20240620
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: Tesla T4

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi, I'm using the pipeline to perform the `text-generation `  tasks.    

I was trying the [Llama official example](https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct) in the jupyter notebook(kaggle) with GPU support. 

When I first load the model and inference with the prompt, everything just works fine. See the following picture:

![image](https://github.com/user-attachments/assets/bc94eb17-491d-4d35-8e98-dadecc6c615f)

When I restart the kernel (NOTE: does not restart the session), the CPU memory is free.

![image](https://github.com/user-attachments/assets/438b453a-6be2-4174-b499-ec069bfb9f6e)

However, when I load the model AGAIN, it will take up a lot of CPU memory. And even if I restart the kernel, the memory does not free up. Only the GPU memory is free.
![image](https://github.com/user-attachments/assets/35847c19-ee21-45a8-a5b9-ed21503399b9)

![image](https://github.com/user-attachments/assets/2150805e-2af5-434d-b8fe-39e162e7e6c4)

I'm wondering is it that normal?

### Expected behavior

The CPU memory is also free.

**Comment by Rocketknight1** [comment]
Hi @gxcuit, restarting the kernel should free everything held by Python, so I can't imagine any `transformers` bug that would leak memory in that scenario.

My guess is that the CPU memory usage here is probably more like memory mapping or cache or something like that? Do you actually get OOM errors or disk swapping as a result of this bug?
