### ISSUE TITLE
[run_slow test fail] ViViT test_inference_interpolate_pos_encoding

### ISSUE THREAD

**Issue by RUFFY-369** [huggingface/transformers#33814]
`test_inference_interpolate_pos_encoding` slow test fails for ViViT model. 

The `interpolate_pos_encoding` method has a bug so the test fails for it.

#33815  fixes this issue

**Comment by LysandreJik** [comment]
Thanks for providing a fix :star_struck:

**Comment by RUFFY-369** [comment]
> Thanks for providing a fix 🤩

@LysandreJik All my pleasure :smile:
