### ISSUE TITLE
AttributeError: 'SuperPointImageProcessor' object has no attribute 'post_process_keypoint_detection'

### ISSUE THREAD

**Issue by darkstar1227** [huggingface/transformers#33825]
Hi, I am trying the Keypoint detection but it shows that the `post_process_keypoint_detection` is not an attribute of `SuperPointImageProcessor`.
Here is the link of page.
https://huggingface.co/docs/transformers/en/tasks/keypoint_detection

## System info
- `transformers` version: 4.46.0.dev0
- Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.25.1
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.1+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA GeForce RTX 3060 Ti

**Comment by qubvel** [comment]
Hi @darkstar1227, thanks for opening an issue! Indeed, I see there is no such method for `SuperPointImageProcessor` in main. That's probably require not yet merged PR
 - https://github.com/huggingface/transformers/pull/33200

 cc @merveenoyan

**Comment by darkstar1227** [comment]
Thank you. I will waiting it merge to the main.

**Comment by qubvel** [comment]
You can also try to install from this PR

```
pip install git+https://github.com/huggingface/transformers.git@refs/pull/33200/head
```

**Comment by darkstar1227** [comment]
> You can also try to install from this PR
> 
> ```
> pip install git+https://github.com/huggingface/transformers.git@refs/pull/33200/head
> ```

Thank you, I will try it.
