### ISSUE TITLE
'model.config.max_length' is set to 20 in Hugging Face 'transformers' Whisper implementation but 448 in OpenAI Whisper

### ISSUE THREAD

**Issue by AbdoKhaled-2021** [huggingface/transformers#33910]
### System Info

**Environment:**
- OS: [Ubuntu 22.04.5 ]
- Python version: [Python 3.10.14]
- Hugging Face `transformers` version: [4.41.0]
- Whisper model: `openai/whisper-large-v3-turbo`

### Who can help?

@sanchit-gandhi 
@ylacombe 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

**Steps to Reproduce:**

1. In Hugging Face `transformers`:
   ```python
   from transformers import WhisperForConditionalGeneration, WhisperProcessor

   model = WhisperForConditionalGeneration.from_pretrained("openai/whisper-large-v3-turbo")
   processor = WhisperProcessor.from_pretrained("openai/whisper-large-v3-turbo")

   # Check model config max_length
   print(model.config.max_length)  # Outputs: 20
   ```

2. In OpenAI Whisper:
   ```python
   import whisper

   model = whisper.load_model("turbo")

   # Check relevant dimension
   print(model.dims)  # Outputs: n_text_ctx = 448
   ```

### Expected behavior

**Expected Behavior:**
The `max_length` for the Hugging Face Whisper model should ideally align with the OpenAI Whisper default, which has a text context length of 448. Alternatively, there should be a clear explanation or documentation regarding why the `max_length` differs, and users should be advised to adjust it for longer transcriptions.

**Comment by ylacombe** [comment]
Hey @AbdoKhaled-2021, if you simply do `print(model.generation_config.max_length)`, you'll see that the max length is actually 448 for this checkpoint!

The implementation will use `generation_config.max_length` rather than `config.max_length`, so the behavior is as expected.

Hope it helps
