### ISSUE TITLE
PaliGemma (and probably SigLIP) inference broken in latest transformers version

### ISSUE THREAD

**Issue by mranzinger** [huggingface/transformers#33929]
> This seems like a breaking change. When I run this model with `transformers==4.44.2`, things work fine. However, when running with `transformers==4.25.1`, it fails with this error:
> 
> ```
> 
> ...
> 
>     num_positions = self.position_embeddings.shape[1]
> 
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1687, in __getattr__
> 
>     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
> 
> AttributeError: 'SiglipVisionEmbeddings' object has no attribute 'position_embeddings'. Did you mean: 'position_embedding'?
> 
> ``` 

 _Originally posted by @mranzinger in [c6d2848](https://github.com/huggingface/transformers/commit/c6d2848a23aba42404784ba52e421ae7b8c68eda#r147546116)_

**Comment by ArthurZucker** [comment]
Yep opening a PR asap cc @xenova !

**Comment by mranzinger** [comment]
I think this is still broken. `self.position_embedding` is of type `nn.Embedding`, which means it doesn't have a `.shape` variable.

I think you want to bring back
```
position_embeddings = self.position_embedding.weight.unsqueeze(0)
```

**Comment by ArthurZucker** [comment]
Fixed properly this time sorry!

**Comment by ArthurZucker** [comment]
BLIP and more have the same issue

**Comment by ArthurZucker** [comment]
#32600 also introduced a regression by storing postion embeds twice

**Comment by mranzinger** [comment]
#33965 does look better!
