### ISSUE TITLE
HfArgumentParser should parse hyphens in long-option parameters

### ISSUE THREAD

**Issue by djmarti** [huggingface/transformers#33933]
### Feature request

Given a dataclass
```python
from dataclasses import dataclass

@dataclass
class Config:
    item_type: str
    item_length: int
```
I would expect `HfArgumentParser.parse_args_into_dataclasses` to correctly parse parameters like `--item-type` or `--item-length` (with a hyphen instead of an underscore). Unfortunately, it doesn't:
```python
from transformers import HfArgumentParser
parser = HfArgumentParser([Config])
parser.parse_args_into_dataclasses(args=["--item-type", "my_type", "--item-length", "23"])
```
throws an error because it is expecting `--item_type` and `--item_length`.

### Motivation

1. Consistency with `argparse`. [`argparse` converts hyphens into underscores before assignment](https://docs.python.org/dev/library/argparse.html#dest):
   >  If no long option strings were supplied, dest will be derived from the first short option string by stripping the initial - character. Any internal - characters will be converted to _ characters to make sure the string is a valid attribute name. 
2. It is standard convention to use hyphens in long-option parameters (e.g., `--file-type`, not `--file_type`).

### Your contribution

If there is no reason preventing this feature request to be accepted, yes, I could contribute to a PR.
I just want to know if there is a fundamental reason why this is not implemented yet.

**Comment by ArthurZucker** [comment]
yeah feel free to open a PR!

**Comment by GargDivanshu** [comment]
if i understand the problem statement correctly then in "parse_args_into_dataclasses" function in -> src/transformers/hf_argparser.py file , we should be adding 
`
args = [arg.replace("-", "_") if arg.startswith("--") else arg for arg in args]
`
this sort of conditional processing for '--'. 

Correct me if i am wrong though. 
Shall i make a PR if not done yet @djmarti  ?

**Comment by djmarti** [comment]
Hi @GargDivanshu, I have submitted a PR. I had worked already on a fix when I saw your message.
