### ISSUE TITLE
🚀 Feature request Multimodal BERT Models

### ISSUE THREAD

**Issue by ecekt** [huggingface/transformers#3395]
Hello, it would be great if more **multimodal** BERT models are included in the library. I have noticed that MMBT from Facebook is provided; however, I was unable to find some guidelines about how to make it work with the help of 🤗 Transformers. 

Possible models can be [VilBERT](https://arxiv.org/abs/1908.02265), [VL-BERT](https://arxiv.org/abs/1908.08530), [VisualBERT](https://arxiv.org/abs/1908.03557), [VideoBERT](https://arxiv.org/abs/1904.01766) and so on.

Best regards.

**Comment by douwekiela** [comment]
As for guidelines about making MMBT work, here is an example on the mm-imdb dataset: https://github.com/huggingface/transformers/blob/master/examples/mm-imdb/run_mmimdb.py.

**Comment by SwatiTiwarii** [comment]
Hi seems like above examples folder has been removed, is it because the multi modal experiment is in intermediate stage.

**Comment by yonatanbitton** [comment]
Hey is there any progress with it soon? 
I find only the mm-imdb example: https://github.com/huggingface/transformers/tree/master/examples/contrib/mm-imdb

Your LXMERT model receives only text features from what I see ("visual_feats - These are currently not provided by the transformers library.")

Thanks :)

**Comment by zmykevin** [comment]
The example for mmbt on mm-imdb is also an invalid link now.

**Comment by slanj** [comment]
Here is a correct link for now https://github.com/huggingface/transformers/tree/master/examples/research_projects/mm-imdb

**Comment by usmanmalik57** [comment]
> As for guidelines about making MMBT work, here is an example on the mm-imdb dataset: https://github.com/huggingface/transformers/blob/master/examples/mm-imdb/run_mmimdb.py.

The link is broken!

**Comment by douwekiela** [comment]
> The link is broken!

See the reply above you :) That seems to work
