### ISSUE TITLE
Cannnot Import from transformers

### ISSUE THREAD

**Issue by saurabh896** [huggingface/transformers#3396]
# 🐛 Bug

## Information
I am trying to import  TFGPT2LMHeadModel in transformers.Python giving below error.
cannot import name 'TFGPT2LMHeadModel' from 'transformers
## To reproduce
import tensorflow as tf
from transformers import TFGPT2LMHeadModel,GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

# add the EOS token as PAD token to avoid warnings
model = TFGPT2LMHeadModel.from_pretrained("gpt2", pad_token_id=tokenizer.eos_token_id)

# encode context the generation is conditioned on
input_ids = tokenizer.encode('I enjoy walking with my cute dog', return_tensors='tf')

# generate text until the output length (which includes the context length) reaches 50
greedy_output = model.generate(input_ids, max_length=50)

print("Output:\n" + 100 * '-')
print(tokenizer.decode(greedy_output[0], skip_special_tokens=True))

## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by LysandreJik** [comment]
In order to import the tensorflow models, you need to have TF2+ installed. Please update your environment info if you *do* have TF2 installed in the environment in which you're running your script.
