### ISSUE TITLE
Default behaviour in `TextClassificationPipeline` for regression problem type

### ISSUE THREAD

**Issue by subhalingamd** [huggingface/transformers#33973]
### Feature request

The `AutoModelForSequenceClassification` class also supports problem_type=regression. I am not sure if it is popularly used but I believe that function_to_apply in `TextClassificationPipeline` should behave as if it is set to "none"  for this case?

### Motivation

Currently, the "sigmoid" function is also applied for regression tasks which, in my opinion, might not be the correct default behaviour.

### Your contribution

I believe this can be handled by adding an additional condition for `self.model.config.problem_type == "regression"` before [this](https://github.com/huggingface/transformers/blob/38f9f10dd9240619ea17fb6c7acb51b3bc592232/src/transformers/pipelines/text_classification.py#L195) line.

**Comment by ArthurZucker** [comment]
cc @Rocketknight1 WDYT?

**Comment by subhalingamd** [comment]
Hi @Rocketknight1, that doesn't seem to be the case. The regression score is represented by LABEL_0 by default.
Indeed, `num_labels == 1` is used as the criteria for assigning problem_type as regression [[example](https://github.com/huggingface/transformers/blob/7bae833728c76345caa04a334368684ed2e77f66/src/transformers/models/bert/modeling_bert.py#L1716)].

**Comment by Rocketknight1** [comment]
@subhalingamd hm, good point! Let me see what we can do. Do you have an example of a text regression model on the Hub I can test with?

**Comment by Rocketknight1** [comment]
Actually, after investigating a bit more, I think checking for `problem_type == "regression"` as you suggested is the right strategy. Would you be willing to make that PR?

**Comment by subhalingamd** [comment]
sure, i can do that
