### ISSUE TITLE
Make `VisionEncoderDecoderModel.from_pretrained` take different arguments for encoder and decoder 

### ISSUE THREAD

**Issue by MohamedAliRashad** [huggingface/transformers#33992]
### Feature request

```python
model = VisionEncoderDecoderModel.from_pretrained("nougat", encoder_kwargs={...}, decoder_kwargs={...})
```

### Motivation

I want to load VisionEncoderDecoderModel with flash_attention_2 for the decoder only (the encoder is not supporting this to my knowledge) but i don't find an easy way to do so

### Your contribution

I can help if its simple

**Comment by ArthurZucker** [comment]
You can already pass `encoder_config` and `decoder_config` 🤗

**Comment by qubvel** [comment]
@MohamedAliRashad The simple way to specify attention implementation for sub-models will be added with  https://github.com/huggingface/transformers/pull/32238 when it's merged.

**Comment by MohamedAliRashad** [comment]
@qubvel Any idea when will this PR merged ?

**Comment by MohamedAliRashad** [comment]
@ArthurZucker The decoder config doesn't have something about loading the model in flash attention 2

**Comment by ArthurZucker** [comment]
Yeah it's actually not supported yet, we are cooking something to make it simpler, in the mean time you can overwrite the properly directly if you want / use the linked PR! 
Hope to get this merged soon! 
🤗

**Comment by zucchini-nlp** [comment]
@MohamedAliRashad the PR is merged and you should be able to load models with smth like this:
`Model.from_pretrained(model_id, attn_implementation={"decoder_config": "flash_attention_2", "encoder_config": "eager"})`

**Comment by MohamedAliRashad** [comment]
@zucchini-nlp I tried it and it's working
Thanks a lot guys ^^

**Comment by MohamedAliRashad** [comment]
False Alarm, the loaded model is in `sdba` and not `flash-attn-2`
```
model = VisionEncoderDecoderModel.from_pretrained(
    "facebook/nougat-base", torch_dtype=torch.bfloat16, attn_implementation={"decoder_config": "flash_attention_2", "encoder_config": "eager"}
)
```

![Screenshot from 2024-10-30 15-36-19](https://github.com/user-attachments/assets/a2df82e6-8b59-4b32-ab7d-ef11355e9691)

**Comment by zucchini-nlp** [comment]
@MohamedAliRashad my bad, for the model you are using the keys are `decoder` and `encoder`. The main thing is that the keys in attn implementation should match 100% to the keys in `model.config`. So if you have `model.config.decoder` then it should be `decoder`. The below code should work

```python
model = VisionEncoderDecoderModel.from_pretrained(
    "facebook/nougat-base", torch_dtype="bfloat16", attn_implementation={"decoder": "flash_attention_2", "encoder": "eager"}
)
```

**Comment by MohamedAliRashad** [comment]
@zucchini-nlp It Worked
![Screenshot from 2024-10-30 17-31-53](https://github.com/user-attachments/assets/74a79597-1675-4fae-aa62-94031f9b0fa4)

Thanks a lot, i will close the issue for good this time ^^

**Comment by qubvel** [comment]
Agreed about the warning, it can be skipped or disabled, so it's not actionable enough. IMO this situation should raise an _error_ because passed keys are wrong
