### ISSUE TITLE
Missing weights in model checkpoint

### ISSUE THREAD

**Issue by uililo** [huggingface/transformers#33995]
### System Info

When trying to load a pretrained wav2vec2 checkpoint, I got the following warning:

>   warnings.warn(
> Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
> You should probably TRAIN this model on a downstream task to be able to use it for predictions and inference.

Theoretically it should be possible to extract embeddings from this pre-trained model without fine-tuning on downstream tasks, however it seems that some weights are missing. I'm not sure whether the problem is with the Wav2Vec2Model class or the checkpoint.
I got the same warning when I tried to load some other checkpoints of wav2vec2 models published by facebook.

Thanks

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
model_name = "facebook/wav2vec2-base"
feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(model_name)
model = Wav2Vec2Model.from_pretrained(model_name)

```

### Expected behavior

The pretrained model is successfully loaded into "model" without needing to initialize some of the weights

**Comment by akshit397a** [comment]
Hey @uililo ,
i want to work on this issue.

**Comment by akshit397a** [comment]
-can you tell the file location

**Comment by uililo** [comment]
location of which file?

**Comment by subasine1** [comment]
Hello @uililo, 

Don't worry about it. This is a harmless warning. It's because of the migration of parameter names between different versions of the transformers library. 
You can see a similar issue here: https://github.com/huggingface/transformers/issues/26796#issuecomment-1781551163

Take care

**Comment by narnia24** [comment]
hey @uililo can i work on this issue?
