### ISSUE TITLE
Support "output_attentions" while using Flash Attention

### ISSUE THREAD

**Issue by eslambakr** [huggingface/transformers#33996]
### Feature request

I am requesting to add support to return the "output_attentions" while using Flash Attention as it is currently not supported, where "output_attentions" is set to False (hard-coded) and ignores the configuration while using Flash Attention.

### Motivation

It is very useful for visualizing attention maps.
So, not supporting it during Flash attention limits a lot of applications where attention maps are needed.

### Your contribution

Sorry, I can not support an implementation for it as I don't understand why the attention maps in the Flash attention case are untrustworthy (#28903).
I mean, they are already there, but as they are not trusted, [they were set to "None"](https://github.com/huggingface/transformers/blob/1bd604d11c405dfb8b78bda4062d88fc75c17de0/src/transformers/models/llama/modeling_llama.py#L431).

**Comment by ArthurZucker** [comment]
Hey! This is inherently not supported by flash attention! That is because to efficiently compute the final attention output, you don't materialize the attention scores! 

If you look at the calls to the `Flash Attention` kernels, they don't return the intermediate `attn_weights = softmax(Q @ K^T * softmax_scale)` but fused the entire `(softmax(Q @ K^T * softmax_scale) @ V)` 🤗

**Comment by eslambakr** [comment]
Hi @ArthurZucker 

Thanks for your prompt response!
I got it. That's why it is okay to use it during training, but during testing, I can disable it to get the attention maps, and still, the attention maps should be accurate.

Thank you so much for the clarification!

**Comment by Masaaki-75** [comment]
Hi @eslambakr ! I am having the same trouble, and may i ask how did you eventually get the attention maps if flashattn2 is not allowed?

**Comment by EricLina** [comment]
You can calculate attention map by hands if your L is not very big.
