### ISSUE TITLE
Load partial model from pretrained.

### ISSUE THREAD

**Issue by johnsutor** [huggingface/transformers#34114]
### Feature request

Ability to load only portions of models.

### Motivation

I'd like to only use a portion of a model, that has it's own defined class, without having to load in the entire model. Speecifically, I'm attempting to load in the [Seamless Code HiFi Gan](https://huggingface.co/docs/transformers/model_doc/seamless_m4t#transformers.SeamlessM4TCodeHifiGan) without loading in the entire Seamless model. 

### Your contribution

I'd be willing to assist in this effort if the HuggingFace team views this as something they'd like to have in the library.

**Comment by LysandreJik** [comment]
Hey @johnsutor, we don't support that through `transformers` as of now as it is quite niche usage.

However, the underlying serialization mechanism for models with `transformers` is `safetensors`. With `safetensors`, you can load individual layers individually, without loading the entire checkpoint in memory.

See for example the getting started guide: https://github.com/huggingface/safetensors?tab=readme-ov-file#getting-started

You should be able to load only the layers you want by leveraging this

**Comment by johnsutor** [comment]
Awesome, thank you!
