### ISSUE TITLE
 cannot import name 'MODEL_FOR_TOKEN_CLASSIFICATION_MAPPING'

### ISSUE THREAD

**Issue by vanh17** [huggingface/transformers#3412]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): BERT

Language I am using the model on (English, Chinese ...): ENglish

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

Run the run_ner.py script on examples/ner/

## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by julien-c** [comment]
This should be fixed on master since a8e3336a850e856188350a93e67d77c07c85b8af.

Feel free to re-open if that's not the case.

**Comment by oya163** [comment]
You might want to upgrade your repo.
`pip install --upgrade .`
