### ISSUE TITLE
Problem with running Transformer Notebook: How to train a language model

### ISSUE THREAD

**Issue by giulianobertoti** [huggingface/transformers#3415]
Hello,

in the page:

https://github.com/huggingface/transformers/blob/master/notebooks/README.md

I clicked "open in colab" on the notebook "How to train a language model".

When the last run cell was run:

%%time
!{cmd}

The following error was presented:

Traceback (most recent call last):
  File "run_language_modeling.py", line 40, in <module>
    from transformers import (
ImportError: cannot import name 'CONFIG_MAPPING'
CPU times: user 42.2 ms, sys: 18 ms, total: 60.2 ms
Wall time: 5.82 s

Any suggestion?

Thank you!

**Comment by MariaFjodorowa** [comment]
Importing CONFIG_MAPPING from https://github.com/huggingface/transformers/blob/master/src/transformers/configuration_auto.py to https://github.com/huggingface/transformers/blob/master/src/transformers/__init__.py fixes the problem (for the last version of the package)

**Comment by julien-c** [comment]
This should be fixed on master by f8823bad9a23f6623e91e71719e65342de877cb9. Can you please try again, and re-open if necessary?

(in a Colab notebook, you'll need to re-download the `run_language_modeling.py` script using `!wget https://raw.githubusercontent.com/huggingface/transformers/master/examples/run_language_modeling.py`)

**Comment by Yamantaka01** [comment]
It now shows the following error:

Traceback (most recent call last):
  File "run_language_modeling.py", line 782, in <module>
    main()
  File "run_language_modeling.py", line 677, in main
    config = AutoConfig.from_pretrained(args.config_name, cache_dir=args.cache_dir)
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_auto.py", line 198, in from_pretrained
    "in its name: {}".format(pretrained_model_name_or_path, ", ".join(CONFIG_MAPPING.keys()))
ValueError: Unrecognized model in /content/models/RoBERTa_GPT/. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: t5, distilbert, albert, camembert, xlm-roberta, bart, roberta, flaubert, bert, openai-gpt, gpt2, transfo-xl, xlnet, xlm, ctrl
CPU times: user 49.2 ms, sys: 8.48 ms, total: 57.7 ms
Wall time: 11.9 s

**Comment by Yamantaka01** [comment]
It is now showing the following error,

Traceback (most recent call last):
  File "run_language_modeling.py", line 782, in <module>
    main()
  File "run_language_modeling.py", line 677, in main
    config = AutoConfig.from_pretrained(args.config_name, cache_dir=args.cache_dir)
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_auto.py", line 198, in from_pretrained
    "in its name: {}".format(pretrained_model_name_or_path, ", ".join(CONFIG_MAPPING.keys()))
ValueError: Unrecognized model in /content/models/RoBERTa_GPT/. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: t5, distilbert, albert, camembert, xlm-roberta, bart, roberta, flaubert, bert, openai-gpt, gpt2, transfo-xl, xlnet, xlm, ctrl
CPU times: user 41.1 ms, sys: 8.81 ms, total: 49.9 ms
Wall time: 6.8 s

**Comment by julien-c** [comment]
@Yamantaka01 Your config.json in `/content/models/RoBERTa_GPT/config.json` should contain a model_type key
