### ISSUE TITLE
KeyError: 'qwen2_vl' loading from Transformers

### ISSUE THREAD

**Issue by kev-iotairx** [huggingface/transformers#34161]
### System Info

- `transformers` version: 4.44.2
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.24.7
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.4.1+cu121 (True)
- Tensorflow version (GPU?): 2.17.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.5 (gpu)
- Jax version: 0.4.33
- JaxLib version: 0.4.33
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: Tesla T4

### Who can help?

@amyeroberts @qubvel 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am attempting to load the model from transformers library and getting an error. Here are instructions from official documentation: https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct?library=transformers 

I am on:  `transformers 4.44.2`

```
# Load model directly
from transformers import AutoProcessor, AutoModelForSeq2SeqLM

processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct")
model = AutoModelForSeq2SeqLM.from_pretrained("Qwen/Qwen2-VL-7B-Instruct")
```

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    992             try:
--> 993                 config_class = CONFIG_MAPPING[config_dict["model_type"]]
    994             except KeyError:

3 frames
KeyError: 'qwen2_vl'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    993                 config_class = CONFIG_MAPPING[config_dict["model_type"]]
    994             except KeyError:
--> 995                 raise ValueError(
    996                     f"The checkpoint you are trying to load has model type `{config_dict['model_type']}` "
    997                     "but Transformers does not recognize this architecture. This could be because of an "

ValueError: The checkpoint you are trying to load has model type `qwen2_vl` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
```

### Expected behavior

Load the Qwen / llama vision models successfully from transformers.

**Comment by zucchini-nlp** [comment]
You need at least version v4.45 for Qwen2-VL
