### ISSUE TITLE
Size mismatch for state-spaces/mamba2-130m state_dict load

### ISSUE THREAD

**Issue by arghadippurdue** [huggingface/transformers#34167]
### System Info

- `transformers` version: 4.45.2
- Platform: Linux-5.14.21-150400.24.116-default-x86_64-with-glibc2.31
- Python version: 3.9.20
- Huggingface_hub version: 0.25.2
- Safetensors version: 0.4.5
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.4.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: NO

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

# Load model directly
from transformers import AutoModel
model = AutoModel.from_pretrained("state-spaces/mamba2-130m")

### Expected behavior

Traceback (most recent call last):
  File "python3.9/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/python3.9/site-packages/transformers/modeling_utils.py", line 4014, in from_pretrained
    ) = cls._load_pretrained_model(
  File "python3.9/site-packages/transformers/modeling_utils.py", line 4559, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for Mamba2Model:
        size mismatch for backbone.embeddings.weight: copying a param with shape torch.Size([50288, 768]) from checkpoint, the shape in current model is torch.Size([50277, 4096]).

**Comment by vasqu** [comment]
The weights are not directly compatible with transformers. You would need to convert them yourself with this script: https://github.com/huggingface/transformers/blob/main/src/transformers/models/mamba2/convert_mamba2_ssm_checkpoint_to_pytorch.py 
( I've converted the 130m model a few weeks back, see https://huggingface.co/AntonV/mamba2-130m-hf )

I have seen this issue multiple times so might be worth to create official associated repos. Originally, the implementation was meant for codestral mamba which is why there are none for the paper ones.

**Comment by vasqu** [comment]
Wdyt? cc @molbap

**Comment by vasqu** [comment]
Converted weights: https://huggingface.co/collections/AntonV/unofficial-mamba2-for-hf-transformers-670fb0892b26b0acd623323b
(most are fp16 since the original ones were also fp16)

**Comment by molbap** [comment]
Thanks @vasqu for the conversion! I think it's fine to refer people to that issue/these weights when trying to use mamba2 in transformers, yes. One way also could be to open a PR on the hub to add the hf weights directly to https://huggingface.co/state-spaces/mamba-130m, either way is fine! 
@arghadippurdue I'll close the issue then thanks to Anton, let me know if you still encounter an issue using the model.
