### ISSUE TITLE
problem with rag

### ISSUE THREAD

**Issue by zahraKane** [huggingface/transformers#34178]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.44.2
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.24.7
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.4.1+cu121 (False)
- Tensorflow version (GPU?): 2.17.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.8.5 (cpu)
- Jax version: 0.4.33
- JaxLib version: 0.4.33
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I tested the rag function with the same dataset 'my_knowledge.csv', everything seemed to work, butThe generated response is not understandable, 
example: Q: What does Moses' rod turn into ?
A:  Powderoo Two stockp upgr Noct vic soy perBleublished *** Offic molecular memElf nu Ore

### Expected behavior

The behavior that i expected is for the rag is to return some coherent responses

**Comment by Rajatavaa** [comment]
What is the temperature you are using?

**Comment by LysandreJik** [comment]
Hey @zahraKane, please provide a reproducible code snippet if you'd like us to help you! thank you
