### ISSUE TITLE
ImportError: cannot import name 'AutoModelForImageTextToText' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

### ISSUE THREAD

**Issue by psologub** [huggingface/transformers#34217]
### System Info

- `transformers` version: 4.44.2
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.24.7
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.4.1+cu121 (False)
- Tensorflow version (GPU?): 2.17.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.8.5 (cpu)
- Jax version: 0.4.33
- JaxLib version: 0.4.33
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker @amyeroberts @qubv

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
!pip install torch
!pip install transformers

import requests
from PIL import Image
import torch
from transformers import AutoProcessor, AutoModelForImageTextToText
```

The error message:

```
ImportError                               Traceback (most recent call last)
[<ipython-input-5-af84153c3b01>](https://localhost:8080/#) in <cell line: 4>()
      2 from PIL import Image
      3 import torch
----> 4 from transformers import AutoProcessor, AutoModelForImageTextToText

ImportError: cannot import name 'AutoModelForImageTextToText' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)
```

### Expected behavior

I've tried to follow this [example](https://huggingface.co/docs/transformers/main/en/model_doc/llava_next#multi-image-inference) but I get stuck importing AutoModelForImageTextToText. Could you help me out please?

**Comment by ArthurZucker** [comment]
Hey! That is because you are looking at the `main` documentation! This feature was shipped in #29572 which is not part of the latest release! 🤗
