### ISSUE TITLE
Onnx validation got max absolute difference of: nan

### ISSUE THREAD

**Issue by NakedEinstein** [huggingface/transformers#34216]
Hi i got this error when i am trying to convert huggingface bert-based torch model to onnx. 

`ValueError: Outputs values doesn't match between reference model and ONNX exported model: Got max absolute difference of: nan`

The model i am trying to convert is training checkpoint model based on indobenchmark/indobert-large-p2.

### Steps done
I already tried both feature versions AutoModel & AutoModelForSequenceClassification
I already ensure file path(s) were correct

### System info
onnx == 1.13.0
transformers[onnx] == 4.25.1
onnxruntime == 1.14.0
torch == 1.13.0

**Comment by LysandreJik** [comment]
Hey @NakedEinstein, could you share the entire code and stacktrace that you have? Thanks
