### ISSUE TITLE
`Trainer.hyperparameter_search` `kwargs` parameter has an inexact definition if using Optuna

### ISSUE THREAD

**Issue by GuillemGSubies** [huggingface/transformers#34239]
According to the [docs](https://huggingface.co/docs/transformers/v4.45.2/en/main_classes/trainer#transformers.Trainer.hyperparameter_search.kwargs), those `kwargs` will only be used in the `create_study` method in Optuna.

However that is not exactly true, as we can see in `run_hp_search_optuna`. Some parameters from those `kwargs` will end up being used in the `optimize` method (which is great because it is what I wanted to do but the docs said I could not do it).

https://github.com/huggingface/transformers/blob/b54109c7466f6e680156fbd30fa929e2e222d730/src/transformers/integrations/integration_utils.py#L256

https://github.com/huggingface/transformers/blob/b54109c7466f6e680156fbd30fa929e2e222d730/src/transformers/integrations/integration_utils.py#L261

I didn't check ray or sigopt but I guess that something similar can be happening.

I don't really know what would be a good solution given that not every parameter in `optimize` is used and creating a `kwargs_optimize` would not make sense given that you support 2 other backends. Maybe a simple list of accepted paramters in the docstring?

If you tell me what solution would be the best, I could send a PR.

@stevhliu

**Comment by stevhliu** [comment]
Hey, thanks for pointing out the discrepancy! I think your proposed solution of a list of accepted parameters in the docstring would be the simplest fix 🙂
