### ISSUE TITLE
bitnet support 

### ISSUE THREAD

**Issue by Darshan2104** [huggingface/transformers#34277]
### Feature request

ValueError: Unknown quantization type, got bitnet - supported types are: ['awq', 'bitsandbytes_4bit', 'bitsandbytes_8bit', 'gptq', 'aqlm', 'quanto', 'eetq', 'hqq', 'fbgemm_fp8']

### Motivation

I was trying to use "HF1BitLLM/Llama3-8B-1.58-100B-tokens" but i encounter above error.

#### Sample code snipt
from transformers import AutoTokenizer, AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("HF1BitLLM/Llama3-8B-1.58-100B-tokens", device_map="cuda", torch_dtype=torch.bfloat16)    
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")

### Your contribution

I can help.

**Comment by MekkCyber** [comment]
Hey @Darshan2104 are installing transformers from source ? 
If not try doing that, just clone the repo and inside run `pip install -e .`

**Comment by Darshan2104** [comment]
Hey @MekkCyber I've not installed it from source. I was using it in colab :)

**Comment by MekkCyber** [comment]
you can install the latest version in colab then using : `pip install git+https://github.com/huggingface/transformers.git`

**Comment by Darshan2104** [comment]
@MekkCyber I worked in colab Thanks, 
Question is why it is taking longer time to generate results ? It should ideally take shorter time compared to Base Llama model.

**Comment by MekkCyber** [comment]
For now I think it takes roughly the same time, It should ideally take a shorter time that's true, for now it's only using `@torch.compile` to unpack the weights, and do the matmul, but in the future we need to integrate some new kernels for int8xint2 like `Bitblas` or triton kernels. For `Bitblas` i was waiting for a bug to be resolved, I will look into that

**Comment by Darshan2104** [comment]
@MekkCyber Thanks for update.
