### ISSUE TITLE
I want to create a tokenizer which the vocab file in my computer

### ISSUE THREAD

**Issue by policeme** [huggingface/transformers#3427]
I want to create a tokenizer in my computer, which the vocab file is below, my code as below
```
self.model_config = AutoConfig.from_pretrained(r'/home/cally/Awake/Code/bert/pre_model/bert_config.json')
self.tokenizer = AutoTokenizer.from_pretrained(r'/home/cally/Awake/Code/bert/pre_model/vocab.txt')
```
it appeared this error, what's wrong?, my enviroment is linux python 3.7 transformer 2.6
```
OSError: Couldn't reach server at '/home/cally/Awake/Code/bert/pre_model/vocab.txt' to download configuration file or configuration file is not a valid JSON file. Please check network or file content here: /home/cally/Awake/Code/bert/pre_model/vocab.txt.

```

**Comment by julien-c** [comment]
Your config.json file should be named `config.json`, and then you should be able to do:
```
self.model_config = AutoConfig.from_pretrained(r'/home/cally/Awake/Code/bert/pre_model/')
self.tokenizer = AutoTokenizer.from_pretrained(r'/home/cally/Awake/Code/bert/pre_model/')
```

(just the folder name).

You might have to add `model_type: "bert"` to your config.json.

**Comment by Hansyvea** [comment]
> 
> 
> Your config.json file should be named `config.json`, and then you should be able to do:
> 
> ```
> self.model_config = AutoConfig.from_pretrained(r'/home/cally/Awake/Code/bert/pre_model/')
> self.tokenizer = AutoTokenizer.from_pretrained(r'/home/cally/Awake/Code/bert/pre_model/')
> ```
> 
> (just the folder name).
> 
> You might have to add `model_type: "bert"` to your config.json.

I encountered the same problem and sorry to bother, but where should i add this line to?
