### ISSUE TITLE
DinoV2 is incorrectly documented as a default patch size of 16 instead of 14

### ISSUE THREAD

**Issue by OFSkean** [huggingface/transformers#34292]
### System Info

transformers version 4.40.2, python version 3.10

### Who can help?

@amyeroberts @NielsRogge 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AutoConfig
config = AutoConfig.from_pretrained("facebook/dinov2-base")
print(config.patch_size) # prints 14

### Expected behavior

The DinoV2 model was [trained](https://arxiv.org/pdf/2304.07193) with a patch size of 14 and [released](https://github.com/facebookresearch/dinov2) with that patch size on Github. Some time later, @NielsRogge [ported](https://github.com/facebookresearch/dinov2/issues/153) it into Huggingface. The config.jsons for the Dinov2 models ([base](https://huggingface.co/facebook/dinov2-base/blob/main/config.json), [large](https://huggingface.co/facebook/dinov2-large/blob/main/config.json)) correctly say patch size of 14, but the default for Dinov2Config is 16 ([docs](https://huggingface.co/docs/transformers/main/model_doc/dinov2#transformers.Dinov2Config), [code](https://github.com/huggingface/transformers/blob/53fad641cfdb5105e2470bcf3ef17ea8e25cc300/src/transformers/models/dinov2/configuration_dinov2.py#L121C9-L121C19)).

This error was a bit confusing for me at first as I was trying to hunt down why my sequence length was 257 instead of 197. It makes sense to correct the documentation to show 14 as the default.

**Comment by LysandreJik** [comment]
cc @qubvel as well

**Comment by qubvel** [comment]
Hi @OFSkean! Thanks for submitting the issue!
Would you like to update dinov2 [configuration](https://github.com/huggingface/transformers/blob/main/src/transformers/models/dinov2/configuration_dinov2.py) to reflect the correct patch size?

**Comment by OFSkean** [comment]
Sure! I'll make a pull request for it shortly.
