### ISSUE TITLE
Llama model not generating mentioned "max_tokens" number of tokens as output 

### ISSUE THREAD

**Issue by vineel96** [huggingface/transformers#34296]
### System Info

- `transformers` version: 4.36.0
- Platform: Linux-5.14.0-427.18.1.el9_4.aarch64-aarch64-with-glibc2.34
- Python version: 3.9.18
- Huggingface_hub version: 0.25.1
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker,  @zucchini-nlp , @Rocketknight1 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Code:

import transformers
import torch

model_id = "meta-llama/Meta-Llama-3-8B"
pipeline = transformers.pipeline("text-generation", model=model_id, model_kwargs={"torch_dtype": torch.float16}, device_map="auto")
output = pipeline("There are two persons named ram and krishna", max_new_tokens=10000, do_sample=True)
final_op = output[0]["generated_text"]
print(final_op)

### Expected behavior

Expected output: generated output length should be 10000 tokens 
Real output: generated output length is less than 10000 tokens

How to get full 10000 tokens as output?

**Comment by zucchini-nlp** [comment]
Hey! Parameter `max_new_tokens` controls only the upper bound when generating. If you want to generate until the max possible tokens, you can either set `eos_token_id` in `model.config` and `model.generation_config`  to `None` or pass a `min_new_tokens=1000`. But note that in the first case there is a risk of going in infinite loop in no upper bound max tokens are set

**Comment by zeus2611** [comment]
@zucchini-nlp Can we set a default value of around 1000 for max_new_tokens? This will prevent the model from running into an infinite loop when we set eos_token_id in both model.config and model.generation_config to None, and no upper limit for max tokens is defined.

**Comment by zucchini-nlp** [comment]
Sure, if the default is set through model's generation config, you don't have to set it manually. I just wanted to note the possibility ofan infinite loop but setting eos-token to `None` is okay as long as you do it intentionally

**Comment by vineel96** [comment]
@zucchini-nlp , Thanks
