### ISSUE TITLE
`self.pre_layrnorm` should be `self.pre_layernorm`?

### ISSUE THREAD

**Issue by devymex** [huggingface/transformers#34302]
https://github.com/huggingface/transformers/blob/745bbfe4bb2b61491dedd56e1e8ee4af8ef1a9ec/src/transformers/models/clip/modeling_clip.py#L821

Is this obviously a typographical error, but will correcting it affect existing model weights?

**Comment by LysandreJik** [comment]
This is indeed a typo but will be hard to change now :/
