### ISSUE TITLE
Error ImportError: cannot import name 'MODEL_FOR_SEQUENCE_CLASSIFICATION_MAPPING' from 'transformers' (C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\transformers\__init__.py)

### ISSUE THREAD

**Issue by kennysmith12** [huggingface/transformers#3431]
# 🐛 Bug

## Information

I am doing the tutorial ["Quick tour of the fine-tuning/usage scripts"](https://github.com/huggingface/transformers#quick-tour-of-the-fine-tuningusage-scripts)

I downloaded the Glue dataset.
When I try to run this command from pytorch
```
python ./examples/run_glue.py \
    --model_type bert \
    --model_name_or_path bert-base-uncased \
    --task_name MRPC \
    --do_train \
    --do_eval \
    --do_lower_case \
    --data_dir C:/Git/RemoteDGX/MRPC/glue_data/MRPC \
    --max_seq_length 128 \
    --per_gpu_eval_batch_size=8   \
    --per_gpu_train_batch_size=8   \
    --learning_rate 2e-5 \
    --num_train_epochs 3.0 \
    --output_dir /tmp/MRPC/

```
I am getting this error:
ImportError: cannot import name 'MODEL_FOR_SEQUENCE_CLASSIFICATION_MAPPING' from 'transformers' (C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\transformers\__init__.py)

: 

## To reproduce

1.download the Glue database 
2. execute the script run_glue.py

this is the stacktrace:
```
2020-03-25 14:09:19.698135: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:/Git/RemoteDGX/transformers/examples/run_glue.py", line 32, in <module>
    from transformers import (
ImportError: cannot import name 'MODEL_FOR_SEQUENCE_CLASSIFICATION_MAPPING' from 'transformers' (C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\transformers\__init__.py)
```

## Environment info

     
- `transformers` version:
- Platform: windows
- Python version: 3.7
- PyTorch version 1.4.0 without GPU:

**Comment by julien-c** [comment]
You're not running the latest version of transformers.
