### ISSUE TITLE
Not only main process will save checkpoints during training

### ISSUE THREAD

**Issue by chchch0109** [huggingface/transformers#34337]
### System Info

- `transformers` version: 4.45.2
- Platform: Linux-5.15.0-72-generic-x86_64-with-glibc2.35
- Python version: 3.9.0
- Huggingface_hub version: 0.25.1
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA RTX A6000

### Who can help?

@muellerz @SunMarc 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. parser training argument with `training_args.output_dir = my_dir`.
2. `if PartialState().is_main_process: training_args.output_dir = 'modified_dir'`
3. When I call `trainer.save_model`, the model will be saved in `modfied_dir`, but the intermediate checkpoints saved by trainer will be saved in both

### Expected behavior

Only the main process save the checkpoints during training.

**Comment by SunMarc** [comment]
Hey @chchch0109, thanks for the report. Could you share a rminimal reproducer ? Also feel free to open a PR if you know how to this the issue !
