### ISSUE TITLE
TFXLMRoberta impossible to load base and large model with pretrained weight ?

### ISSUE THREAD

**Issue by Shiro-LK** [huggingface/transformers#3436]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):
XLMRoberta
Language I am using the model on (English, Chinese ...):

The problem arises when using:
* [ x] the official example scripts: (give details below)

The tasks I am working on is:
my own task or dataset: (give details below)

## To reproduce

launch the command :
`model = TFXLMRobertaForSequenceClassification.from_pretrained(pretrained_model_name_or_path="xlm-roberta-large" )`

1. from transformers import*
2. launch the command above
3. error : 

> TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

## Expected behavior

model should be load.

## Environment info
     
- `transformers` version: 2.6.0
- Platform: colab

- Tensorflow version (GPU?):2.1 gpu
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by duyongan** [comment]
我也遇到了同样的问题

**Comment by duyongan** [comment]
maybe u can use from_pt=True
TFXLMRobertaForSequenceClassification.from_pretrained(pretrained_model_name_or_path="xlm-roberta-large", **_from_pt=True_**)

**Comment by Shiro-LK** [comment]
Hi, thanks for your answer.
I got exactly the same message with "from_pt=True"

**Comment by Shiro-LK** [comment]
I am suspecting that the file does not exist.
I succeed to load with TFXLMRoberta doing that :

`m = XLMRobertaForSequenceClassification.from_pretrained("xlm-roberta-base", num_labels=1)
m.save_pretrained("./")
model = TFXLMRobertaForSequenceClassification.from_pretrained("./", , num_labels=1, from_pt=True)`

**Comment by LysandreJik** [comment]
Hello, indeed there is no official XLM-R checkpoint. You can use @jplu's [checkpoint from the modelhub](https://huggingface.co/models/?search=jplu%2Ftf-xlm):

```py
m = TFXLMRobertaForSequenceClassification.from_pretrained("jplu/tf-xlm-roberta-base", num_labels=1)
```
