### ISSUE TITLE
ValueError: The model did not return a loss from the inputs, only the following keys: logits. For reference, the inputs it received are input_ids,attention_mask,pixel_values,aspect_ratio_ids,aspect_ratio_mask,cross_attention_mask

### ISSUE THREAD

**Issue by youky860423** [huggingface/transformers#34392]
### System Info

ValueError: The model did not return a loss from the inputs, only the following keys: logits. For reference, the inputs it received are input_ids,attention_mask,pixel_values,aspect_ratio_ids,aspect_ratio_mask,cross_attention_mask

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Call trainer.train();
2. system return error for no logits

### Expected behavior

successfully running forward and compute loss

**Comment by zucchini-nlp** [comment]
Hey, you need to provide `labels` to get the loss calculated

**Comment by DobricLilujun** [comment]
Check your dataset label's data type. It should be class not Value of string.
