### ISSUE TITLE
llama3.1 tokennizer from transformers has Different behavior from origin openai/tiktoken

### ISSUE THREAD

**Issue by WhatGhost** [huggingface/transformers#34403]
### System Info

transformers == 4.46.0
tiktoken==0.8.0

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

@ArthurZucker @itazap hi, i use transformers to run a llama3.1 model。
but I found that the ids after tokennizer.encode is difference from the tiktoken lb from openai.tiktoken(https://github.com/openai/tiktoken)

The code is shown below
```python
        import tiktoken
        from transformers import AutoTokenizer

        tokenizer = AutoTokenizer.from_pretrained(args.model_path, fast=True)
        prompt = "请你基于以下「评估标准」"
        token_ids = tokenizer.encode(prompt)  #[15225, 57668, 125510, 88852, 13177, 64479, 112494, 110778, 10646]
        encoding = tiktoken.get_encoding("cl100k_base")
        titoken_ids = encoding.encode(prompt) #[15225, 57668, 75146, 35304, 88852, 13177, 64479, 17885, 108, 31944, 12870, 228, 10646]
```

i wondered if there is any difference betwen openai/tiktoken and transformers. 
and if the answer is yes,how can i modify the code to convert openai/titoken to transformers 's llama3.1's tokennizer 

Can anyone help me? Thanks!

### Expected behavior

expected if there is any difference betwen betwen openai/tiktoken and transformers's llama3.1 tokennizer. and how can convert each

**Comment by techkang** [comment]
`cl100k_base` is used for OPENAI series models: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb?short_path=19ce768#L26. It has different tokenizer with llama series. That's why you can't get the same token ids I think.

**Comment by ArthurZucker** [comment]
Indeed, we plan to support converting directly from any given encoding, you would be able to do : `tokenizer = AutoTokenizer.from_pretrained("cl100k_base", fast=True)` but in the mean time you have to use the `TikTokenConverter`

**Comment by WhatGhost** [comment]
@techkang @ArthurZucker Thanks for your relpy. It works and i solved the problem. It's not a bug.It's my misunderstanding of tiktoken. I will close this issue. Thanks again!
