### ISSUE TITLE
NotImplementedError: data_seed requires Accelerate version `accelerate` >= 1.1.0. This is not supported and we recommend you to update your version.

### ISSUE THREAD

**Issue by zwhe99** [huggingface/transformers#34412]
### System Info

transformers==4.46.0

### Who can help?

@MekkC

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import TrainingArguments
TrainingArguments(output_dir=".", data_seed=42)
``` 

### Expected behavior

The latest version of Accelerate is 1.0.1 for now.

**Comment by AbrahamSanders** [comment]
According to [this comment in the fix PR](https://github.com/huggingface/transformers/pull/33731#issuecomment-2402756789) it seems there's a corresponding PR in the accelerate repo huggingface/accelerate#3150 that's needed to enable this, and which didn't make it into accelerate 1.0.1. Is accelerate 1.1.0 planned to release soon?

**Comment by LysandreJik** [comment]
cc @muellerzr, do you know what's happening here?

**Comment by muellerzr** [comment]
Yes accelerate will be released by Friday w/ this capability, for the time being please install accelerate from git:
`pip install git+https://github.com/huggingface/accelerate`

**Comment by zwhe99** [comment]
Thanks, I got it!

**Comment by Fang6** [comment]
> accelerate                        1.1.0.dev0 transformers                      4.47.0.dev0

> NotImplementedError: data_seed requires Accelerate version `accelerate` >= 1.1.0. This is not supported and we recommend you to update your version.
