### ISSUE TITLE
can't import TFBertModel from transformers

### ISSUE THREAD

**Issue by policeme** [huggingface/transformers#3442]
this is the log when I imported the TFBertModel from transformers
```
from transformers import TFBertModel
ImportError: cannot import name 'TFBertModel' from 'transformers' (/home/cally/.local/lib/python3.7/site-packages/transformers/__init__.py)

```
my enviroment is transformers 2.4 linux python 3.7

**Comment by policeme** [comment]
I try it in Mac, it had same error
my enviroment is transformers 2.4 mac python 3.7

**Comment by LysandreJik** [comment]
That's because you don't have TensorFlow 2 installed.

**Comment by thiziri** [comment]
Conda users:

For whom the problem is not solved with re/installing TensorFlow, update the modules in conda.
`conda install tensorflow`

**Comment by mzackaria** [comment]
You might want to try this:

conda install -c huggingface transformers

(ref: https://pypi.org/project/transformers/)

**Comment by thiziri** [comment]
Thank you @mzackaria for the answer. The problem is solved (a long time ago).  as mentioned above :)

**Comment by shivamagrawal3900** [comment]
I'm on Tensorflow 1.x and can't upgrade to 2.x
Installing an older version of transformers worked for me.
`pip install transformers==4.2.2`
