### ISSUE TITLE
Not Receiving Identity Verification Link via Email

### ISSUE THREAD

**Issue by fawzighu** [huggingface/transformers#34428]
### System Info

with the identity verification process on Hugging Face. I have submitted my request for the identity verification link but have not received any email confirmation or the link itself.

I have checked my spam/junk folders and ensured that I entered the correct email address during the registration process. I also attempted to resend the verification link, but I still have not received anything.

This issue is preventing me from accessing certain features on the platform, and I would appreciate any assistance in resolving it.

Thank you!

### Who can help?

@meg-huggingface 

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Navigate to the Hugging Face website.

2. Register or log in to your account.

3. Go to the identity verification section.

4. Submit a request for the identity verification link.

5. Wait for the confirmation email to arrive.

6. Check the inbox and the spam/junk folder.

Result: I did not receive any link or confirmation via email.

### Expected behavior

Upon submitting a request for the identity verification link, I should receive an email confirmation with the verification link within a reasonable timeframe (typically within a few minutes). This would allow me to complete the identity verification process and access the necessary features on the Hugging Face platform.

**Comment by meganriley** [comment]
Hi @fawzighu Can you please email us at website@huggingface.co and provide your HF username as well? We're happy to investigate this for you.
