### ISSUE TITLE
[i18n-HI] Translating docs to Hindi

### ISSUE THREAD

**Issue by karthik-script** [huggingface/transformers#34441]
Hi!

Let's bring the documentation to all the <languageName>-speaking community 🌐 (currently 0 out of 267 complete)

Who would want to translate? Please follow the 🤗 [TRANSLATING guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md). Here is a list of the files ready for translation. Let us know in this issue if you'd like to translate any, and we'll add your name to the list.

Some notes:

* Please translate using an informal tone (imagine you are talking with a friend about transformers 🤗).
* Please translate in a gender-neutral way.
* Add your translations to the folder called `<languageCode>` inside the [source folder](https://github.com/huggingface/transformers/tree/main/docs/source).
* Register your translation in `<languageCode>/_toctree.yml`; please follow the order of the [English version](https://github.com/huggingface/transformers/blob/main/docs/source/en/_toctree.yml).
* Once you're finished, open a pull request and tag this issue by including #issue-number in the description, where issue-number is the number of this issue. Please ping @stevhliu and @MKhalusova for review.
* 🙋 If you'd like others to help you with the translation, you can also post in the 🤗 [forums](https://discuss.huggingface.co/).

## Tutorial section
- [x]  [accelerate.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/accelerate.md)

**Comment by karthik-script** [comment]
Hello @stevhliu and @MKhalusova, I am proficient in Hindi and Telugu and would like to offer my services as a reviewer and add additional translations to support the cause.

Thank you.

**Comment by stevhliu** [comment]
Hi, thanks for your interest! There is an open issue in https://github.com/huggingface/transformers/issues/26787 for translating the docs to Hindi. Feel free to comment and coordinate with other community members on that issue to avoid duplicating efforts 🙂
