### ISSUE TITLE
run_lm_finetuning on multiple training files

### ISSUE THREAD

**Issue by ghtaro** [huggingface/transformers#3445]
# ❓ Questions & Help

## Details

Hi,

I would like to fine-tune huggingface's pre-trained BERT model on a relatively big text data.
I split the data into multiple files (~10k files) in .raw format in the same folder.

First, I succeeded to run run_lm_finetuning.py on one of the raw files I generated.

Now, I would like to run that in my 10k raw files.
I realised that that train_data_file argument does not accept a folder name (only the path to a single raw file).
I believe that we can do a loop over the 10k train files and incrementally fine-tuning the model, but it does not look like a best solution for me...

Could you please tell me if it exists a simple way to achieve the above?

Thank you very much for your help.

**Comment by julien-c** [comment]
Hi, this is not currently supported, you would need to implement this yourself. Feel free to open a PR if you do
