### ISSUE TITLE
tokenizer's `apply_chat_template` doesn't preserve trailing newlines

### ISSUE THREAD

**Issue by lone17** [huggingface/transformers#34462]
### System Info

- `transformers` version: 4.46.0
- Platform: Linux-5.15.0-122-generic-x86_64-with-glibc2.35
- Python version: 3.12.7
- Huggingface_hub version: 0.26.1
- Safetensors version: 0.4.5
- Accelerate version: 1.0.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.5.0+cu124 (True)

### Who can help?

@Rocketknight1 @itazap @ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

The current behaviour of `apply_chat_template` is removing the last trailing newline in the chat template, even if it has more than one newlines.

```python3
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("gpt2")

tokenizer.chat_template = """<|im_start|>user
hello<|im_end|>
<|im_start|>assistant
"""

print(repr(tokenizer.chat_template))
# '<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n'
print(repr(tokenizer.apply_chat_template(None, tokenize=False)))
# '<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant'

tokenizer.chat_template = """<|im_start|>user
hello<|im_end|>
<|im_start|>assistant


"""

print(repr(tokenizer.chat_template))
# '<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n\n\n'
print(repr(tokenizer.apply_chat_template(None, tokenize=False)))
# '<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n\n'

```

Not sure if this is the intended behaviour but I didn't find any discussion/document that mentions this. If this was indeed intended, I would like to learn why.

From my experience, there are models that are quite sensitive to this last newline token. Besides, most users would be unaware of this behaviour, which might cause unexpected outcomes.

I have traced the code and found out that this was due to `jinja2` default configs. It can be fixed by simply setting `keep_trailing_newline=True` in the below code. After you guys confirm that this is a bug, I can make a PR if needed.

https://github.com/huggingface/transformers/blob/1d063793318b20654ebb850f48f43e0a247ab7bb/src/transformers/utils/chat_template_utils.py#L422-L424

### Expected behavior

- `apply_chat_template` should preserve that `chat_template`
- If there is any modification to the template then it should be documented.

**Comment by Rocketknight1** [comment]
Hi @lone17, this could probably be documented better, but **in general, we recommend putting important whitespace inside `{{ blocks }}`**. If you want to print newlines at the end of your template, add a `{{- "\n\n" }}` block.

**Comment by lone17** [comment]
Hi @Rocketknight1, so it seems that the behaviour was intended. In that case, let me close this and please update the docs to mention this behaviour. Many thanks.
