### ISSUE TITLE
Useful Sensors Moonshine Transcription Model

### ISSUE THREAD

**Issue by njeffrie** [huggingface/transformers#34474]
### Model description

Model description can be found in the [Moonshine Whitepaper](https://github.com/usefulsensors/moonshine/blob/main/moonshine_paper.pdf).

I will be porting our [existing torch model](https://github.com/usefulsensors/moonshine/blob/b2a61fff243dd78ee2fa72dd1bceff8ccf656c4c/model.py) to Transformers.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

[Implementation](https://github.com/usefulsensors/moonshine) Special credit to @keveman for training and @evmaki for data collection and preprocessing. 
[Model weights](https://huggingface.co/UsefulSensors/moonshine)

**Comment by njeffrie** [comment]
Excellent, thanks for the pointer! I'll definitely do this first, then we will consider creating a PR to add the model to `transformers` in the slightly longer term.

For now I'll keep this open for reference and for the future PR, unless you'd prefer I close then re-open the issue alongside a future PR to `transformers`.

**Comment by Rocketknight1** [comment]
I think you can close this for now, and reopen it later if you want to push for a full library PR!
