### ISSUE TITLE
FlashAttention2 implementation for OpenELM model

### ISSUE THREAD

**Issue by GorkaUrbizu** [huggingface/transformers#34485]
### Model description

OpenELM is already available on HF🤗 and transformers, but the model lacks support for flashAttention/FlashAttention2.

I'd love to have the flash attention available for OpenELM in the transformers enviroment. 

thanks in advance.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by Rocketknight1** [comment]
Hi @GorkaUrbizu, we have an open PR to co-ordinate adding SDPA support to Transformers models, which can also dispatch to FlashAttention. See here: #28005

We're open to community contributions, because it may take us a while to finish updating models!
