### ISSUE TITLE
Add support for OLMo November release

### ISSUE THREAD

**Issue by 2015aroras** [huggingface/transformers#34496]
### Model description

An updated OLMo model will be released in November. The new model has a few small architecture changes compared to the existing model in transformers:

- RMSNorm is used instead of standard layer norm.
- Norm is applied to attention queries and keys.
- Norm is applied after attention/feedforward rather than before.

It would be great to have it integrated in transformers from day 1.

### Open source status

- [X] The model implementation is available
- [ ] The model weights are available

### Provide useful links for the implementation

OLMo code repo: https://github.com/allenai/OLMo
Authors include @2015aroras 
Weights are not yet available, will be made available at release.

**Comment by huzaifa-jawad367** [comment]
Hi @2015aroras , 

I would like to contribute to this new model. Can I be assigned to this issue.
Thanks.

Regards

**Comment by 2015aroras** [comment]
Thanks @huzaifa-jawad367 for the interest! Unfortunately I've already done most of the implementation for releasing this model on transformers, so it might be redundant to have us both work on it.

If you're interested in contributing to this model's release and don't mind contributing to another library, then implementations into vLLM and llama.cpp are currently available I think (let me know!). If you want to work on an OLMo-related model in transformers and don't mind working on multimodal, the Molmo 1B seems to be up for grabs (other sizes are in progress here https://github.com/huggingface/transformers/pull/33962). Otherwise, if you want to do a text model in transformers then there might be something in the issues list but nothing OLMo-related to my knowledge.
