### ISSUE TITLE
Write With Transformer returning a 502 on gpt2/xl model

### ISSUE THREAD

**Issue by sergalbutt** [huggingface/transformers#3452]
When setting the model size to **gpt2/xl**, WwT gets stuck on loading the autocomplete.
Checking Chrome's console tells me
"Failed to load resource: the server responded with a status of 502 (Bad Gateway)"

Having a quick look through the older tickets, I saw that this has happened before. #2121

**Comment by julien-c** [comment]
We had to turn that model off because it was really expensive/hard to operationalize.

We'll add a warning to that particular webpage. (cc @LysandreJik)
