### ISSUE TITLE
NER pipeline usage examples

### ISSUE THREAD

**Issue by jensam** [huggingface/transformers#3454]
In the NER usage examples:
https://huggingface.co/transformers/usage.html#named-entity-recognition

Can you explain why the examples give only I- entities? For example:
('New', 'I-LOC'), ('York', 'I-LOC'), ('City', 'I-LOC')
('Hu', 'I-ORG'), ('##gging', 'I-ORG'), ('Face', 'I-ORG'), ('Inc', 'I-ORG')

Why are there no B-s? As in:
('New', 'B-LOC'), ('York', 'I-LOC'), ('City', 'I-LOC') etc

**Comment by LysandreJik** [comment]
The German and English CoNLL datasets use the IOB1 tagging scheme. `B-` is only used to separate two adjacent entities of the same type.
