### ISSUE TITLE
ImportError: cannot import name 'TF_MODEL_FOR_TOKEN_CLASSIFICATION_MAPPING'

### ISSUE THREAD

**Issue by pascalhuszar** [huggingface/transformers#3457]
Wanted to use the ner demo, but after running:

 `!python3 ./ner/run_tf_ner.py --data_dir /data --model_type bert --labels .data/labels.txt --model_name_or_path bert-base-multilingual-cased --output_dir germeval-model --max_seq_length 128 --num_train_epochs 3 --per_device_train_batch_size 32 --save_steps 750 --seed 1 --do_train --do_eval --do_predict` 

i encounter the ImportError

Any suggestions?

**Comment by patrickvonplaten** [comment]
Importing `TF_MODEL_FOR_TOKEN_CLASSIFICATION_MAPPING` from transformers works for me. Can you update your transformers library and see whether you still get the import error.

**Comment by zweili** [comment]
Hi,

I have the same issue here. I have installed transformers from source with the latest update.
 But still this **ImportError: cannot import name 'TF_MODEL_FOR_TOKEN_CLASSIFICATION_MAPPING'**

**Comment by pascalhuszar** [comment]
Somehow, on a second try `pip install transformers` worked for me. But cant tell why it didnt worked at the beginning.

**Comment by zweili** [comment]
Thanks for the quick response. I will try again by installing it not from source.

**Comment by julien-c** [comment]
Make sure you really update and install from source. If in doubt, recreate your virtual env.

**Comment by NextNight** [comment]
`pip uninstall transformers ` and `pip install transformers ` make sure your transformers version is update.

**Comment by zweili** [comment]
Thanks, I got around the problem by converting it to pytorch model.  But now I am facing other issues !  Anyway thank you again for your helps
