### ISSUE TITLE
WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 2, distributed training: False, 16-bits training: True

### ISSUE THREAD

**Issue by keloemma** [huggingface/transformers#3458]
I am trying to use the script run_glue to fintenue Flaubert for french data using huggingface's transformers and I am gettinh this error :

`

03/27/2020 11:54:48 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 2, distributed training: False, 16-bits training: True
Traceback (most recent call last):
  File "/home/getalp/kelodjoe/transformers/examples/run_glue.py", line 693, in <module>
    main()
  File "/home/getalp/kelodjoe/transformers/examples/run_glue.py", line 613, in main
    config_class, model_class, tokenizer_class = MODEL_CLASSES[args.model_type]
KeyError: 'flaubert'

`

Could you help me find how to solve it ?

**Comment by K-Bion** [comment]
？how to solve it

**Comment by jinshuhua** [comment]
could you tell me how to solve this problem?
