### ISSUE TITLE
import deepspeed error after update

### ISSUE THREAD

**Issue by TuuSiwei** [huggingface/transformers#34582]
### System Info

transformers              4.46.1
deepspeed                 0.11.1

Ubuntu 20.04.6 LTS
python 3.10

### Who can help?

@muellerz 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
from transformers.deepspeed import is_deepspeed_zero3_enabled
```

error info: ModuleNotFoundError: No module named 'transformers.deepspeed' 

### Expected behavior

success import

**Comment by paulcx** [comment]
```
[rank0]:     trainer.train()
[rank0]:   File "/opt/anaconda3/envs/base/lib/python3.11/site-packages/transformers/trainer.py", line 2122, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/base/lib/python3.11/site-packages/transformers/trainer.py", line 2474, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/anaconda3/envs/base/lib/python3.11/site-packages/transformers/trainer.py", line 3564, in training_step
[rank0]:     self.optimizer.train()
[rank0]:   File "/opt/anaconda3/envs/base/lib/python3.11/site-packages/accelerate/optimizer.py", line 128, in train
[rank0]:     return self.optimizer.train()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]: AttributeError: 'DeepSpeedZeroOptimizer_Stage3' object has no attribute 'train'
```

confirm it

**Comment by techkang** [comment]
Directly import from `transformers.deepspeed` is deprocated. You can use `from transformers.integrations import deepspeed` instead.

**Comment by lazy2019** [comment]
from transformers.integrations.deepspeed import is_deepspeed_zero3_enabled

**Comment by rubychoc** [comment]
> ```
> [rank0]:     trainer.train()
> [rank0]:   File "/opt/anaconda3/envs/base/lib/python3.11/site-packages/transformers/trainer.py", line 2122, in train
> [rank0]:     return inner_training_loop(
> [rank0]:            ^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/opt/anaconda3/envs/base/lib/python3.11/site-packages/transformers/trainer.py", line 2474, in _inner_training_loop
> [rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
> [rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/opt/anaconda3/envs/base/lib/python3.11/site-packages/transformers/trainer.py", line 3564, in training_step
> [rank0]:     self.optimizer.train()
> [rank0]:   File "/opt/anaconda3/envs/base/lib/python3.11/site-packages/accelerate/optimizer.py", line 128, in train
> [rank0]:     return self.optimizer.train()
> [rank0]:            ^^^^^^^^^^^^^^^^^^^^
> [rank0]: AttributeError: 'DeepSpeedZeroOptimizer_Stage3' object has no attribute 'train'
> ```
> 
> confirm it

did you figure out how to solve this ?
