### ISSUE TITLE
How to retrain the GLIP model on the Object365 dataset

### ISSUE THREAD

**Issue by CLL112** [huggingface/transformers#34591]
Since I made some modifications to the GLIP model, I need to perform some pre-training again to improve performance. I replaced `_base_ = [../_base_/datasets/coco_detection.py]` with `_base_ = [../_base_/datasets/objects365v1_detection.py]` in `glip_atss_swin-t_a_fpn_dyhead_16xb2_ms-2x_funtune_coco.py` to train on Object365. Is this correct?

**Comment by Vishal-Padia** [comment]
Yes, that modification is correct if you want to pre-train GLIP on Objects365 instead of COCO. However, make sure the Objects365v1 dataset config file exists and is properly configured.
