### ISSUE TITLE
NaN model parameter found in  meta-llama/Llama-3.2-11B-Vision under 4.46.1 version

### ISSUE THREAD

**Issue by cuong-dyania** [huggingface/transformers#34602]
### System Info

We tried with H100/A100 GPU machine both got the same issues.
transformers==4.46.1
torch==2.3.1+cu121

### Who can help?

 @ArthurZucker

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
```python
import transformers
import torch
from transformers import (
    AutoConfig,
    AutoModelForCausalLM)

print(transformers.__version__)
print(torch.__version__)

model_name_or_path ="meta-llama/Llama-3.2-11B-Vision"
def check_for_nan_parameters(model):
    for name, param in model.named_parameters():
        if torch.isnan(param).any():  # Check if any value in the parameter tensor is NaN
            print(f"NaN found in parameter: {name}")
            return True
    print("No NaNs found in model parameters.")
    return False


model = AutoModelForCausalLM.from_pretrained(model_name_or_path,
        torch_dtype=torch.bfloat16,device_map ='auto')

print(check_for_nan_parameters(model))
```

# The above code will return 
#NaN found in parameter: model.layers.0.input_layernorm.weight
# True

### Expected behavior

We should not see NAN in model parameters. The above codes should return False.

We tried the above codes for transformers==4.45.2 and did not see any NaN in model parameters.

**Comment by ArthurZucker** [comment]
Hey! you have a warning that says:
```python
Some parameters are on the meta device because they were offloaded to the cpu.
NaN found in parameter: model.layers.0.input_layernorm.weight
```
the weights are just on the `meta` device for fast loading, until you run a forward pass 😉
