### ISSUE TITLE
Error : forward() got an unexpected keyword argument 'inputs_embeds'

### ISSUE THREAD

**Issue by johncwok** [huggingface/transformers#3460]
Hello,

I am trying to train a GPT2 from scratch using ```modeling_gpt2.py``` as a base.
I declared the model as follow : 
```Python 
config = GPT2Config(vocab_size = VELSIZE, n_positions = SEQLEN, n_embd = EMBEDSIZE, n_layer = NUMLAYER,n_ctx = SEQLEN, n_head = NUMHEAD)  
model = GPT2Model(config)  
``` 
I don't need to use the buid-in embeddings for my application and would like to pass my input tensor as-is, but trying ```model(inputs_embeds = test)```,  ```model.forward(inputs_embeds = test)```, ```model(input_ids=None,
      past=None,
      attention_mask=None,
      token_type_ids=None,
      position_ids=None,
      head_mask=None,
      inputs_embeds=test)``` or any other variant I can think of always results in the following error :
```Python 
Traceback (most recent call last):

  File "<ipython-input-52-616a2eb9b3f4>", line 7, in <module>
    inputs_embeds=testx)

  File "C:\Users\cnelias\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)

TypeError: forward() got an unexpected keyword argument 'inputs_embeds'
```

Is this a bug or am I doing it wrong ?

**Comment by patrickvonplaten** [comment]
I can run the following code succesfully: 

```
from transformers import GPT2Model, GPT2Tokenizer
import torch

model = GPT2Model.from_pretrained('gpt2')
tokenizer = GPT2Tokenizer.from_pretrained('gpt2', pad_token='<PAD>')

input_ids = tokenizer.encode("Hello, how are you?", return_tensors='pt')
inputs_embeds = model.wte(input_ids)

model(inputs_embeds=inputs_embeds)  # runs without error
```

Can you update `transformers` to the most current version and verify that you can run the code snippet I posted?

**Comment by johncwok** [comment]
Running ```conda update transformers``` returned that I already have the latest version.
As for you snippet, I still get the same error : 
```Python
Traceback (most recent call last):

  File "<ipython-input-136-d0df910b9d57>", line 10, in <module>
    model(inputs_embeds=inputs_embeds)  # runs without error

  File "C:\Users\cnelias\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)

TypeError: forward() got an unexpected keyword argument 'inputs_embeds'
```
Is this because I installed ```transformers``` with ```conda``` instead of ```pip``` ?

**Comment by Naviden** [comment]
I get the same error . upgrading transformers vai pip doesn't solve the problem. any solution?
