### ISSUE TITLE
ValueError: You are trying to save a non-contiguous tensor in MT5 finetunning

### ISSUE THREAD

**Issue by esti-tech** [huggingface/transformers#34623]
https://github.com/huggingface/transformers/blob/7bbc62474391aff64f63fcc064c975752d1fa4de/src/transformers/trainer.py#L3728

may be using these fixes it
```py

 for param in model.parameters():
        if not param.is_contiguous():
            param.data = param.data.contiguous()

```

**Comment by LysandreJik** [comment]
Hey @esti-tech, could you please provide a reproducible code example and error so that we may see how to best help?
