### ISSUE TITLE
When will transformers trainer supports fp8

### ISSUE THREAD

**Issue by wangxiaoyang-dev** [huggingface/transformers#34635]
### Feature request

Hope transformers trainer can support fp8 .

### Motivation

Currently, accelerate has support fp8, so we hope transformers trainer can support fp8 to .

### Your contribution

yes, I can help by submitting a PR .

**Comment by LysandreJik** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
Everything that it supported in accelerate is available on transformers since the backend of trainer is using accelerate @wangxiaoyang-dev

**Comment by wangxiaoyang-dev** [comment]
> Everything that it supported in accelerate is available on transformers since the backend of trainer is using accelerate @wangxiaoyang-dev

Thanks.
