### ISSUE TITLE
about gradient accumulation

### ISSUE THREAD

**Issue by TuuSiwei** [huggingface/transformers#34648]
### System Info

none

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hello, I would like to ask whether the latest stable version has fixed the problems related to gradient accumulation? Whether to still only install from source code to avoid this problem

### Expected behavior

none

**Comment by LysandreJik** [comment]
cc @muellerzr
