### ISSUE TITLE
Docstring cannot be build anymore

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#3466]
# 🐛 Bug

## Information

Docstring

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

## To reproduce

1. `pip install -e ".[docs]"` at `transformers` root folder
2. `cd docs` 
3. `make html`

## Expected behavior

It should work, but an error message is displayed:

> /home/patrick/hugging_face/transformers/src/transformers/modeling_utils.py:docstring of transformers.PreTrainedModel.from_pretrained:23: WARNING: Unexpected indentation.
> /home/patrick/hugging_face/transformers/src/transformers/modeling_tf_utils.py:docstring of transformers.TFPreTrainedModel.from_pretrained:20: WARNING: Definition list ends without a blank line; unexpected unindent.
> 
> Exception occurred:
>   File "/home/patrick/hugging_face/transformers_venv/lib/python3.6/site-packages/sphinx/util/docfields.py", line 260, in transform
>     assert len(field) == 2
> AssertionError
> The full traceback has been saved in /tmp/sphinx-err-mblqzztk.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> Makefile:19: recipe for target 'html' failed

## Environment info

- `transformers` version: 2.6.0
- Platform: Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.4.0+cpu (False)
- Tensorflow version (GPU?): 2.1.0 (False)
- Using GPU in script?:No
- Using distributed or parallel set-up in script?: No

**Comment by LysandreJik** [comment]
Was fixed with https://github.com/huggingface/transformers/commit/e2c05f06ef58ea77103d2c64492dd8d9a0b21c3f
