### ISSUE TITLE
Error when loading openbmb/RLHF-V

### ISSUE THREAD

**Issue by pspdada** [huggingface/transformers#34673]
### System Info

- `transformers` version: 4.46.2
- Platform: Linux-5.15.0-120-generic-x86_64-with-glibc2.35
- Python version: 3.10.15
- Huggingface_hub version: 0.26.2
- Safetensors version: 0.4.5
- Accelerate version: 1.1.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: None
- Using GPU in script?: 1
- GPU type: NVIDIA A100-PCIE-40GB

### Who can help?

@zucchini-nlp, @amyeroberts, @qubvel

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

With the latest transformers version `transformers==4.46.2`, when I try to load this model by using:
```
model_name = "openbmb/RLHF-V"

model = AutoModelForCausalLM.from_pretrained(
            model_name,
            cache_dir=self.model_dir,
            torch_dtype=self.torch_dtype,
            low_cpu_mem_usage=True,
            device_map=self.device,
            attn_implementation="flash_attention_2" if "cuda" in str(self.device) else None,
        ).eval()
```
or use:
```
from transformers import pipeline

pipe = pipeline("text-generation", model="openbmb/RLHF-V", cache_dir="/root/llm-project/util/model")
```
An error occured: 
```
ValueError: The checkpoint you are trying to load has model type `beit3_llava` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
```
This seems to affect more than just this one model. Please identify the issue and fix it.

### Expected behavior

Fix it

**Comment by vasqu** [comment]
It looks like they use custom code:
https://huggingface.co/openbmb/RLHF-V/discussions/4#66bf4f95198f9d79f2259ed5

So you should install their library at https://github.com/thunlp/Muffin to properly use their models.

**Comment by pspdada** [comment]
> It looks like they use custom code: https://huggingface.co/openbmb/RLHF-V/discussions/4#66bf4f95198f9d79f2259ed5
> 
> So you should install their library at https://github.com/thunlp/Muffin to properly use their models.

I'm sorry for my carelessness; this is indeed the solution to the problem.
