### ISSUE TITLE
AutoModelForDepthEstimation/DepthAnythingDepthEstimationHead unexpected behavior in JIT

### ISSUE THREAD

**Issue by sarmientoF** [huggingface/transformers#34679]
### System Info

macos/linux cpu/nvidia gpu

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoImageProcessor, AutoModelForDepthEstimation

image_processor = AutoImageProcessor.from_pretrained("depth-anything/Depth-Anything-V2-Small-hf")
model = AutoModelForDepthEstimation.from_pretrained("depth-anything/Depth-Anything-V2-Small-hf")
model.config.return_dict = False

traced_model = torch.jit.optimize_for_inference(
    torch.jit.trace(model, (torch.rand(1, 3, 518 * 1, 518 * 1)), strict=False)
)
traced_model(torch.rand(1, 3, 518 * 2, 518 * 2))[0].shape # output: (1, 3, 518 * 1, 518 * 1)
````

### Expected behavior

```python
traced_model(torch.rand(1, 3, 518 * 2, 518 * 2))[0].shape # output: (1, 3, 518 * 2, 518 * 2)
```

**Comment by qubvel** [comment]
Hi @sarmientoF, thanks for submitting an issue!
Are the shapes different for non-tranced models? 
DepthAnything output depth map is downsampled and needs upsampling to be the same spacial shape as image

see code snipped [here](https://huggingface.co/depth-anything/Depth-Anything-V2-Small-hf)
```python
...
# interpolate to original size
prediction = torch.nn.functional.interpolate(
    predicted_depth.unsqueeze(1),
    size=image.size[::-1],
    mode="bicubic",
    align_corners=False,
)
```

It also can be handled by image processor's method `post_process_depth_estimation` ([code](https://github.com/huggingface/transformers/blob/3ea3ab62d80d91f9bdd16bd3cacd8133fb0d4566/src/transformers/models/dpt/image_processing_dpt.py#L475C9-L514))
