### ISSUE TITLE
Can't import LLavaForConditionalGeneration

### ISSUE THREAD

**Issue by paprika0741** [huggingface/transformers#34680]
### System Info

- `transformers` version: 4.46.0
- Platform: Linux-5.4.0-174-generic-x86_64-with-glibc2.35
- Python version: 3.10.4
- Huggingface_hub version: 0.26.2
- Safetensors version: 0.4.5
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA GeForce RTX 4090

### Who can help?

@amyeroberts, @qubvel

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
import requests
from PIL import Image
import torch
from  transformers import AutoProcessor
from transformers import LLavaForConditionalGeneration
```
```
/root/anaconda3/envs/trans46/lib/python3.10/site-packages/torchvision/datapoints/__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
/root/anaconda3/envs/trans46/lib/python3.10/site-packages/torchvision/transforms/v2/__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
Traceback (most recent call last):
  File "/root/nfs/codespace/llm-models/LLaVA/test.py", line 5, in <module>
    from transformers import LLavaForConditionalGeneration
ImportError: cannot import name 'LLavaForConditionalGeneration' from 'transformers' (/root/nfs/codespace/llm-models/LLaVA/transformers-4.46.0/src/transformers/__init__.py)
```

### Expected behavior

I found `LLavaForConditionalGeneration` in `/root/nfs/codespace/llm-models/LLaVA/transformers-4.46.0/src/transformers/__init__.py`, but it can be imported correctly.

**Comment by jadenpark0** [comment]
Changing `LLavaForConditionalGeneration` to `LlavaForConditionalGeneration` worked for me.

**Comment by zucchini-nlp** [comment]
Yes, the naming should be camel cased. Closing as resolved
