### ISSUE TITLE
Transformers 4.46.2 breaks model loading for Llama 3.2 90B Vision Instruct

### ISSUE THREAD

**Issue by iprivit** [huggingface/transformers#34689]
### System Info

- `transformers` version: 4.46.2
- Platform: Linux-5.10.226-214.880.amzn2.x86_64-x86_64-with-glibc2.26
- Python version: 3.10.14
- Huggingface_hub version: 0.26.2
- Safetensors version: 0.4.5
- Accelerate version: 1.1.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.2.2 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: Tesla V100-SXM2-32GB

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Download weights for meta-llama/Llama-3.2-90B-Vision-Instruct
2. Load weights with the transformers 4.46.2 library installed

This will result in `Some weights of MllamaForCausalLM were not initialized from the model checkpoint at meta-llama/Llama-3.2-90B-Vision-Instruct and are newly initialized: ['embed_tokens.weight', ...`

### Expected behavior

With 4.45.2 I was able to load model weights with no issues. It seems like maybe the weights have different names in the Odict?

**Comment by iprivit** [comment]
Code to execute:

```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig


model_id = "meta-llama/Meta-Llama-3.1-70B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(
    model_id,
    padding_side="left",
    add_eos_token=True,
    add_bos_token=True,
    local_inputs_only=True,
    cache_dir = '/home/ec2-user/SageMaker/data/models/'

)

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16,
    device_map="balanced",
    quantization_config=quantization_config,
    cache_dir = '/home/ec2-user/SageMaker/data/models/'
)

```

**Comment by zucchini-nlp** [comment]
AFAIK the CausalLM dict keys are not aligned due to changing the base model prefix. That should be fixed soon by 
https://github.com/huggingface/transformers/pull/34274

**Comment by LysandreJik** [comment]
cc @ArthurZucker as well

**Comment by LysandreJik** [comment]
Just to confirm @iprivit, can you paste all the layers that cannot be loaded? If it is only `'embed_tokens.weight'` it could be the shared layer acting up, if more than that, I agree with Raushan's analysis above.

Do you see degraded performance when using the model with the new version?

**Comment by zucchini-nlp** [comment]
I located that we modified the `base_model_prefix` in some of prev PRs to accommodate new generation clean up, so that is indeed a bug now. I'll ping @ gante internally to continue discussions from the linked PR while his vacation hasn't started yet

**Comment by iprivit** [comment]
Hi, it's nearly all of the layers. Can post a list here if you need, but it's rather long.

**Comment by zucchini-nlp** [comment]
@iprivit no need for the stacktrace, we will fix it soon :)
