### ISSUE TITLE
Errors when using transformers with torch<2.5

### ISSUE THREAD

**Issue by loadams** [huggingface/transformers#34795]
### System Info

Transformers latest from `main`, pytorch 2.3, cpu or gpu.

Needs to have #34184

### Who can help?

@ArthurZucker @muellerzr 

### Information

- [x] My own modified scripts

### Reproduction

1. `pip install torch==2.3`
2. `pip install git+https://github.com/huggingface/transformers.git`
3. `python -c "import transformers.models.vision_encoder_decoder.modeling_vision_encoder_decoder"`

### Expected behavior

This does not error out with torch 2.5, but does with torch 2.3 or 2.4, if these are not supported, we should get an error message when installing transformers.

**Comment by ArthurZucker** [comment]
Yep, will open a PR for that !
