### ISSUE TITLE
CLIP Tokenizer Returns Different DTypes for Numpy versus Pytorch

### ISSUE THREAD

**Issue by ivanthewebber** [huggingface/transformers#34790]
### System Info

- `transformers` version: 4.46.2
- Platform: Windows-11-10.0.26100-SP0
- Python version: 3.12.7
- Huggingface_hub version: 0.26.2
- Safetensors version: 0.4.5
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.5.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: no

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
```python
from transformers import AutoProcessor

texts = ["a photo of a cat", "A photo of a dog."]

for model_id in ("openai/clip-vit-base-patch16", "openai/clip-vit-large-patch14-336"):
    tokenizer = AutoProcessor.from_pretrained(model_id)
    print(model_id)
    # `CLIPTokenizerFast.from_pretrained` and no kwargs gives string dtype
    # However, no kwargs with AutoProcessor fails with warning
    for i, kwargs in enumerate((dict(padding='longest'), dict(padding='longest', truncation=True))):
        pytorch_inputs = tokenizer(text=texts, return_tensors='pt', **kwargs)
        for k, v in pytorch_inputs.items():
            # int64 (correct)
            print(f"pytorch {i} {k}: {v.dtype} {v.shape}")

        numpy_inputs = tokenizer(text=texts, return_tensors='np', **kwargs)
        for k, v in numpy_inputs.items():
            # int32 (incorrect)
            print(f"numpy {i} {k}: {v.dtype} {v.shape}")
    print()
```

### Expected behavior

Creating numpy and/or pytorch tensors should have equivalent data types.

**Comment by ivanthewebber** [comment]
I am assuming the pytorch dtypes are correct because that's the model's framework.

**Comment by Rocketknight1** [comment]
@ivanthewebber I'm not sure one of these is more 'correct', since all of the numbers should be inside the `int32` range regardless. Is there an issue caused by the dtype difference?
