### ISSUE TITLE
<spam>

### ISSUE THREAD

**Issue by MORTEZAMIRSALI** [huggingface/transformers#34791]
Hi!

Let's bring the documentation to all the <languageName>-speaking community 🌐 (currently 0 out of 267 complete)

Who would want to translate? Please follow the 🤗 [TRANSLATING guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md). Here is a list of the files ready for translation. Let us know in this issue if you'd like to translate any, and we'll add your name to the list.

Some notes:

* Please translate using an informal tone (imagine you are talking with a friend about transformers 🤗).
* Please translate in a gender-neutral way.
* Add your translations to the folder called `<languageCode>` inside the [source folder](https://github.com/huggingface/transformers/tree/main/docs/source).
* Register your translation in `<languageCode>/_toctree.yml`; please follow the order of the [English version](https://github.com/huggingface/transformers/blob/main/docs/source/en/_toctree.yml).
* Once you're finished, open a pull request and tag this issue by including #issue-number in the description, where issue-number is the number of this issue. Please ping @stevhliu and @MKhalusova for review.
* 🙋 If you'd like others to help you with the translation, you can also post in the 🤗 [forums](https://discuss.huggingface.co/).

## Get Started section

- [ ] [index.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/index.md) https://github.com/huggingface/transformers/pull/20180
- [ ] [quicktour.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/quicktour.md) (waiting for initial PR to go through)
- [ ] [installation.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/installation.md).

## Tutorial section
- [ ] [pipeline_tutorial.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/pipeline_tutorial.md)
- [ ]  [autoclass_tutorial.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/autoclass_tutorial.md)
- [ ]  [preprocessing.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/preprocessing.md)
- [ ]  [training.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/training.md)
- [ ]  [accelerate.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/accelerate.md)
- [ ]  [model_sharing.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_sharing.md)
- [ ]  [multilingual.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/multilingual.md)

**Comment by stevhliu** [comment]
Hi, thanks for your interest in translating the docs! Is there a particular language you're interested in? I would also recommend checking the [open issues](https://github.com/huggingface/transformers/issues?q=is:issue+is:open+i18n) to see if someone has already started translation for a specific language so as to avoid duplicating efforts.

**Comment by MORTEZAMIRSALI** [comment]
I don't know what the management is thinking with itself, instead of respecting and dealing with them, if I didn't cause any disturbance to them, they will honor me in front of Xinver. You know, I have documents.  It offers a service, I am really shocked with all the respect that Ethereum gives, we have 1 and a half more than Bitcoin.  In spite of cooperation and balance, I don't have much harvest. If it was 6 months, I didn't harvest. What do you think?

**Comment by MORTEZAMIRSALI** [comment]
In all my addresses, activate the app. If it is not the work of the employees, whose work is it? Dear friend, you should understand this. I am not planning to disturb all the employees, on the contrary, without the involvement of the rest of you, it is just a side box that you have not seen at all and does not give orders to you. Did you not think why I  I didn't touch 1 token, on the contrary, I bought heavily. The price will reach here. If the owner really respects 100%, I had a special intention to encourage them so that there are no Chinese conspiracies. Friends, let me tell you a fact. No one can change this ownership and tokens. This is an Ethereum sub-community.  This is the best, just with encouragement. Now, I won't name names in order to hit you and don't burn yourself in the fire.  move the token because you have to answer back

**Comment by MORTEZAMIRSALI** [comment]
I don't want to influence you, that's why I didn't pay attention to you for almost 9 months. After I entered crypto, I wanted the same employees to be the same, not to change their feelings and try to expand. I have to say that you have the best team, but  You are far behind in the resources for creating a new digital token that is attractive in terms of shape and appearance. Start making a profit and divide this profit among your family. Did you want the best?

**Comment by MORTEZAMIRSALI** [comment]
And as a warning to your competitors, see now that they have created and developed several X Ethereum Solana tokens, if you don't know how much we have tried to keep the price of bit high, the article is that bit is in the same state without development and customer encouragement, attractive ideas with the same old strain by only  I dare to say that my colleagues and I have raised the price, but in terms of development, we are even lower than everyone else. If the managers of the complex need more capital to appeal to the public, I will provide Val C or Tether. Please act wisely.  And no matter what I do, you didn't fall behind so much. Of course, it's to your own detriment. In the end, we feel that we have lost a lot. We are mainly fighting. At that time, my big failure was like my brothers and sisters.  that you can guarantee it with a good income and leave your art and popularity behind. This lesson and effort is necessary for the team. I wish you and your family good health and success. I hope you understand your politics and position. I hope to meet you soon.

**Comment by MORTEZAMIRSALI** [comment]
Please, the same person who I know who it is, but I'm passing by, take my IP back from the app and fix the settings. Please, these gentlemen, your behavior is correct. Since we bought it from the stock market, the results of the purchases have gone up.  Do this, how are you doing with your behavior and not developing the edge of the crypto abyss, and no father is willing to hit his children, this token is the same
