### ISSUE TITLE
query_length not found in BLIP-2 config

### ISSUE THREAD

**Issue by thisisiron** [huggingface/transformers#34821]
In the code, there's a reference to `self.config.query_length` [[link]](https://github.com/huggingface/transformers/blob/30335093276212ce74938bdfd85bfd5df31a668a/src/transformers/models/blip_2/modeling_blip_2.py#L1362):

```python
past_key_values_length = (
    past_key_values[0][0].shape[2] - self.config.query_length if past_key_values is not None else 0
)
```

However, query_length doesn't exist in the Blip2Config. Instead, it seems that we should be using `num_query_tokens` which is already defined in Blip2Config. [[link]](https://github.com/huggingface/transformers/blob/30335093276212ce74938bdfd85bfd5df31a668a/src/transformers/models/blip_2/configuration_blip_2.py#L281)

**Comment by zucchini-nlp** [comment]
@thisisiron hey, indeed seems to be a bug as there is no such attribute in the config. From what I see it is triggered only when Qformer is called with `past_key_values` which is never the case when using Blip-2 model. Unless one wants to tweak around and call the Qformer directly. That should be the reason we never caught this bug

If you have any use-case when the Qformer is called with cache, feel free to share a small code snippet and open a PR. Or you can just share the code here, and I will help you fix it :)
