### ISSUE TITLE
pretrained_model_name_or_path why not absolute path from /

### ISSUE THREAD

**Issue by suhjohn** [huggingface/transformers#34837]
### Feature request

I don't understand why only relative paths are supported for pretrained_model_name_or_path. 

### Motivation

```
OSError: Incorrect path_or_model_id: '/models/colpaligemma-3b-pt-448-base'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

Above is a stupid error that shouldn't happen.

### Your contribution

No

**Comment by qubvel** [comment]
Hi @suhjohn! Can you please provide a code example to reproduce the error? Thanks

**Comment by Rocketknight1** [comment]
Absolute paths are supported for this. You either made a mistake in the directory name, the directory doesn't contain a valid model, or you're using Unix-style paths on Windows.
