### ISSUE TITLE
latest transformer has a tensorflow and numpy error

### ISSUE THREAD

**Issue by sleepingcat4** [huggingface/transformers#34839]
### System Info

collab version of transformers (latest)

### Who can help?

@gante @rock

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Install latest transformers, numpy and tensorflow versions (more specifically colab versions)

You'll encounter an error specifically more tensorflow for this line:

```Python
from transformers.pipelines import PIPELINE_REGISTRY
```

How the error looks like:

```Bash
SystemError: initialization of _pywrap_checkpoint_reader raised unreported exception
```

### Expected behavior

It should not produce an error and pass clean like I did on the colab by downgrading versions. 

https://colab.research.google.com/drive/1482Nc7IfE-s5sl7dBjEbWfOjz59QFA1l?usp=sharing

**Comment by Rocketknight1** [comment]
Hi @sleepingcat4, can you confirm if downgrading just Tensorflow fixes the issue?

**Comment by sleepingcat4** [comment]
@Rocketknight1 downgrading transformers won't work for my library but I can try in an hour. 

Right now, I get this error by default as Tensorflow's latest version won't let me import even the basic classes of transformers.

**Comment by Rocketknight1** [comment]
Yes, understood - I know downgrading isn't a fix, it'd just help us to debug it if you can figure out exactly which combinations of versions causes the bug!

**Comment by sleepingcat4** [comment]
@Rocketknight1 I am not getting this error now. I guess KVPress changed something on my colab while it was installing. But, from my understanding that tensorflow module should be fixed otherwise it will create more pain if some library uses a tensorflow version that is not compatible with transformers. 

If I am not wrong this error was introduced in the October update of Tensorflow.

**Comment by Rocketknight1** [comment]
@sleepingcat4 - yes, if you or any other user can identify the combination of versions that triggers the error, please let us know and we'll investigate. I'll leave this issue open until then
