### ISSUE TITLE
Tests for more examples

### ISSUE THREAD

**Issue by srush** [huggingface/transformers#3483]
# Add tests for more of the examples/  

We need to have more testing code for examples. This is particularly true with NER which recently had a tokenizer issue. 

(Self-assigning)

**Comment by sshleifer** [comment]
I agree. Tried for an hour last night to add coverage for `run_bart_sum.py` and got stuck on two things.

1) A `circleci` job that installs `pytorch_lightning` (and potentially other dependencies)
2) the ability to import `examples/transformer_base.py`

### Suggested Approach:
- add the aforementioned circleci job
- a flag like `@requires_lightning` to decorate some tests
- some code changes to get the imports working sanely. 
- Checklist/Instructions for how new examples/ contributors can add test coverage.

Happy to work on this. Wanted to see if others people would find this useful. 

CC: @LysandreJik , @julien-c, @thomwolf @patrickvonplaten

**Comment by srush** [comment]
Cool. Most of these seem easy. Sharing code between examples is a bit harder. I am not sure if we should have and examples package, or symlink that shared file somehow. Currently we add it to the path before running the code.

**Comment by ethanjperez** [comment]
With the Pytorch-Lightning examples, I've been running into an [issue](https://github.com/huggingface/transformers/pull/3437) loading trained models with `--do_predict` (when not also using `--do_train`), so it would be helpful to add some model-loading test as well :)
