### ISSUE TITLE
Urgent: 429 Errors and Potential Rate Limiting on Model Access

### ISSUE THREAD

**Issue by dnuanghsh** [huggingface/transformers#34841]
### System Info

Hi team,

From yesterday, we have been seeing 429 errors when trying to access different models.

Here's an example of the error we're seeing:

```
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status  
    raise HTTPError(http_error_msg, response=self)  
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for URL: https://huggingface.co/meta-llama/Meta-Llama-3-8B/resolve/main/config.json  
```

We suspect we are being rate-limited. We can share the IPs with you.

Could we look into resolving this issue? 

Thank you so much!

cc @amyeroberts @philschmid  @sgugger 

### Who can help?

@amyeroberts @philschmid @sgugger 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

We ran into the issues in our internal runs. 

### Expected behavior

Run without hitting the 429 errors.

**Comment by Rocketknight1** [comment]
Hi @dnuanghsh, can you tell us how many requests were being made simultaneously?

**Comment by xyg-coder** [comment]
@Rocketknight1 Do you have any suggestion to avoid this issue in the future? Like any business account to relieve this restrict? Thanks

**Comment by meganriley** [comment]
Hi [dnuanghsh](https://github.com/dnuanghsh) glad to hear it's working for you now. Can you please email api-enterprise@huggingface.co with your IP address so that we can investigate why this happened?

@xyg-coder Feel free to email us at api-enterprise@huggingface.co as well, as well as any information about when you received the rate limiting error message/what you were doing.

**Comment by Michellehbn** [comment]
Handling via email, closing issue
