### ISSUE TITLE
setup.py succeeds, then can't import transformers

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#3486]
```bash
pip install -e .
```
works succesfully and makes `transformers.egg-info/`

Then,
```python
import transformers
```
fails with

```
ModuleNotFoundError: No module named 'transformers'
```

env
```
- `transformers` version: 2.6.0
- Platform: Darwin-19.0.0-x86_64-i386-64bit
- Python version: 3.7.5
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?): 2.1.0 (False)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

**Comment by patrickvonplaten** [comment]
Do you use the `zsh` shell? cause in this case I think you have to do `pip install -e "."`

**Comment by sshleifer** [comment]
Fails in bash identically.
One clue, this is also happening for `pip install tokenizers` followed by import `tokenizers`, but not for `import numpy`.

**Comment by patrickvonplaten** [comment]
And with `pip install -e "."` it works ?

**Comment by sshleifer** [comment]
I fixed it by **restarting** my zsh shell. Now I can't reproduce the bug in a new zsh shell. Closing.
