### ISSUE TITLE
DETR preprocess with a wrong BBox format

### ISSUE THREAD

**Issue by junxnone** [huggingface/transformers#34875]
### System Info

main branch

### Who can help?

@amyeroberts @qubvel 

GroundingDINO have the same issue @EduardoPach 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

- 1 **The original DETR bbox format**:
  - Input BBox Format: [`(x, y, x, y)` => `(cx, cy, w, h)` ](https://github.com/facebookresearch/detr/blob/29901c51d7fe8712168b8d0d64351170bc0f83e0/datasets/transforms.py#L254-L256))
  - Calculate BBox Loss with `(cx, cy, w, h)` 
  - Output Convert [to `(x, y, x, y)`](https://github.com/facebookresearch/detr/blob/29901c51d7fe8712168b8d0d64351170bc0f83e0/models/detr.py#L277-L278)
- 2 **transformers DETR Model** 
  - Input BBox as **COCO Format** `(x, y, w, h)`, and convert to `(x, y, x, y)` [here](https://github.com/huggingface/transformers/blob/6a912ff2c5b3eadb9a0583d77083aae27d35d28d/src/transformers/models/detr/image_processing_detr.py#L351-L353)
  - **Then** calculate the bbox loss with **Format Convert** [center_to_corner](https://github.com/huggingface/transformers/blob/6a912ff2c5b3eadb9a0583d77083aae27d35d28d/src/transformers/loss/loss_for_object_detection.py#L177-L179), **but the target bbox is still (x, y, x, y).** 
- 3 The **GroundingDINO** model have the same **input BBox Format** issues
  - And the **Open-GroundingDINO** also convert [(x,y,x,y) to (cx,cy,w,h)](https://github.com/longzw1997/Open-GroundingDino/blob/924bb6c4b93cae2dae582e1afaeccd408c72a31d/datasets/transforms.py#L264)
  - But I am not sure why the **original GroundingDINO** model output the [(xywh) format](https://github.com/IDEA-Research/GroundingDINO/blob/856dde20aee659246248e20734ef9ba5214f5e44/demo/inference_on_a_image.py#L31)
- 4 not sure if this is the root cause of #28865

### Expected behavior

The model expected the bbox format for loss calculate is `(cx,cy,w,h)`

**Comment by qubvel** [comment]
Hi @junxnone! Thanks for opening the issue! Bbox conversion is indeed the trickiest part of our pipeline. You can find some detailed explanations in this issue:

 - https://github.com/huggingface/transformers/issues/32835

It’s definitely an area that could be improved!

**Comment by junxnone** [comment]
Oops, Found the [xyxy2cxcy format convert](https://github.com/huggingface/transformers/blob/d9e6f307e71b5108a7882ec00ffcc0d0eb316cb7/src/transformers/models/detr/image_processing_detr.py#L227-L238), it is same as the original DETR, do convert in the Normalize function.

Thanks.
