### ISSUE TITLE
Missing example in docstring for compute_loss_func (`Callable`, *optional*) in trainer.py

### ISSUE THREAD

**Issue by shindennach** [huggingface/transformers#34955]
### System Info

Docstring of Trainer.py (https://github.com/huggingface/transformers/blob/v4.46.3/src/transformers/trainer.py#L294) 
Independent of environment

### Who can help?

@stevh

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Thank you for the generally great documentation in huggingface transformers. It is really helpful for newbies like me. 
I noticed there seems to be an example missing in the docstring for the trainer.py script (https://github.com/huggingface/transformers/blob/v4.46.3/src/transformers/trainer.py#L294). 
In the description of the 'compute_loss_func (`Callable`, *optional*):' in line 342 the end of the last sentence seems to be missing. ("For example, here is one using the loss function from `transformers`"

### Expected behavior

It would be great to have an example for how the loss function has to look. 
Thank you.

**Comment by Rocketknight1** [comment]
cc @stevhliu

**Comment by stevhliu** [comment]
Thanks for catching this! Would you like to open a PR and complete the sentence with something like the following?

```md
For example, see the default [loss function](https://github.com/huggingface/transformers/blob/052e652d6d53c2b26ffde87e039b723949a53493/src/transformers/trainer.py#L3618) used by [`Trainer`].
```

**Comment by secrettoad** [comment]
Here is a PR implementing @stevhliu's suggestion.

https://github.com/huggingface/transformers/pull/35020. My first on the repo so please let me know if I need to make any changes, even as simple as it is.
