### ISSUE TITLE
How to load BertforSequenceClassification  models weights into BertforTokenClassification model?

### ISSUE THREAD

**Issue by kalyanks0611** [huggingface/transformers#3496]
Initially, I have a fine-tuned BERT base cased model using a text classification dataset and I have used BertforSequenceClassification class for this. Now I want to use this fine-tuned BERT model weights for Named Entity Recognition and I have to use BertforTokenClassification class for this. I'm unable to figure out how to load the fine-tuned BERT model weights into the new model created using BertforTokenClassification.  @thomwolf 

Thanks in advance.......................

**Comment by LysandreJik** [comment]
Have you tried loading your checkpoint in the model using `from_pretrained`:

```py
model = BertForTokenClassification.from_pretrained("checkpoint)
```

? It should work out of the box. Please be aware that the NER head will be randomly initialized as it is not in the sequence classification checkpoint.
