### ISSUE TITLE
The document of generation seems to wrongly describe the default value of top_p, top_k and temperature

### ISSUE THREAD

**Issue by Kamichanw** [huggingface/transformers#35045]
### System Info

The newest transformers

### Who can help?

@stevhliu

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The [document](https://huggingface.co/docs/transformers/v4.46.3/en/main_classes/text_generation#transformers.GenerationConfig.top_p) of `generation` says that `top_p`, `top_k` and `temperature` will be set to a specific value.

However, as shown below, the settings of `top_p`, `top_k`, and `temperature` depend on the generation configuration of the model, which is not guaranteed to be consistent with the behavior described in the docstring.
https://github.com/huggingface/transformers/blob/052e652d6d53c2b26ffde87e039b723949a53493/src/transformers/generation/utils.py#L1035-L1044

### Expected behavior

I'd like to know if I'm missing something, and if not, please make the docstring of "generation" and its behavior consistent.

**Comment by stevhliu** [comment]
Thanks for the feedback! I think we can clarify the docstrings of these parameters to reflect what you're saying. Something along the lines of:

```md
temperature (`float`, *optional*, defaults to 1.0) - The value used to module the next token probabilities. This value is set in a model's `generation_config.json` file. If it isn't set, the default value is 1.0.
```

**Comment by Kamichanw** [comment]
Yes, that's make sense
