### ISSUE TITLE
Bug in running facebook/wav2vec2-xlsr-53-espeak-cv-ft

### ISSUE THREAD

**Issue by aldazero** [huggingface/transformers#35064]
### System Info

- `transformers` version: 4.46.0
- Platform: Linux-5.15.0-203.146.5.1.el9uek.x86_64-x86_64-with-glibc2.34
- Python version: 3.11.5
- Huggingface_hub version: 0.24.6
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.5.1+cu124 (False)
- Tensorflow version (GPU?): 2.17.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: No

### Who can help?

@ylacombe, @eustlb, @patrickvonplaten 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying to follow the instruction under this [page](https://huggingface.co/facebook/wav2vec2-xlsr-53-espeak-cv-ft) on running `facebook/wav2vec2-xlsr-53-espeak-cv-ft` model. But I encounter this error:
```python
processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-lv-60-espeak-cv-ft")
.....
TypeError: Received a bool for argument tokenizer, but a PreTrainedTokenizerBase was expected.
```

### Expected behavior

Loading and running the processor and model without error.

**Comment by Rocketknight1** [comment]
hi @aldazero, initializing the processor with that code works correctly for me, so this may be an environment issue, which makes it hard for us to debug!

Can you try to reproduce the issue on Colab? If it occurs there then we should be able to investigate further.

**Comment by aldazero** [comment]
Thank you @Rocketknight1 for your help. Here is a Colab to reproduce the error:
https://colab.research.google.com/drive/1L-3oNHRl3m-bPhRuN57ujuDwpOL1zDyy?usp=sharing

**Comment by aldazero** [comment]
I just found that it works with transformers==4.42.2, by the way.

**Comment by Rocketknight1** [comment]
cc @ylacombe since we have a reproducer now

**Comment by ylacombe** [comment]
Hey @aldazero, thanks for taking the time to create the notebook.

I was able to reproduce the issue using your notebook on Colab, but not locally.
After having installed `espeak-ng` (`!sudo apt-get install espeak-ng`), the error changed and indicated to install `phonemizers`.

At the end of the day, installing `espeak-ng` and `phonemizers`  (`!pip install phonemizer`) made it possible to load the processor.

Since I wasn't able to reproduce locally, it's hard for me to debug this. If the above solution works and contents you, let's keep it as it is. Otherwise, would you be able to look into this issue?

**Comment by naba89** [comment]
In case espeak-ng is built from source, need to add the `bin` directory to `PATH` **and** the `lib` directory to `LD_LIBRARY_PATH`. 

If you only add the `bin` to `PATH`, espeak-ng will work from the command line, but phonemizer requires the `lib`, so that error is thrown.

**Comment by aldazero** [comment]
Thank you, @ylacombe! The proposed solution of installing `espeak-ng` works perfectly. I believe this is more about providing a more relevant error log for such cases. I'll go ahead and close this issue now.

**Comment by zadwekat** [comment]
in windows, i was able to make it work by adding two enviroment variable
$Env:PHONEMIZER_ESPEAK_PATH='C:\Program Files\eSpeak NG\espeak-ng.exe'
$Env:PHONEMIZER_ESPEAK_LIBRARY='C:\Program Files\eSpeak NG\libespeak-ng.dll'
