### ISSUE TITLE
[Critical Bug in LM forward labels] For llama language modeling training, the original code of right-shifting label by 1 is gone?

### ISSUE THREAD

**Issue by ShengYun-Peng** [huggingface/transformers#35066]
### System Info

transformers==4.46.1

### Who can help?

@ArthurZucker

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

What are the expected labels in the CausalLM.forward? Should user right-shift the label manually or not?

Mistral model right shifts in the forward: https://github.com/huggingface/transformers/blob/329f5dbf97a5cb2473914c88c05aa3dcb242e19a/src/transformers/models/mistral/modeling_mistral.py#L1088-L1100
GPT2 model right shifts in the forward: https://github.com/huggingface/transformers/blob/329f5dbf97a5cb2473914c88c05aa3dcb242e19a/src/transformers/models/gpt2/modeling_gpt2.py#L1490-L1495
The early llama model also right shifts in the forward: https://github.com/huggingface/transformers/blob/f1d822ba337499d429f832855622b97d90ac1406/src/transformers/models/llama/modeling_llama.py#L1205-L1215

BUT that right-shift logic is gone in the latest version: https://github.com/huggingface/transformers/blob/329f5dbf97a5cb2473914c88c05aa3dcb242e19a/src/transformers/models/llama/modeling_llama.py#L1181-L1183

Could you check whether this logic was incorrectly deleted or the entire code was moved to somewhere else?

### Expected behavior

See above

**Comment by ShengYun-Peng** [comment]
Maybe the code is migrated to here? https://github.com/huggingface/transformers/blob/329f5dbf97a5cb2473914c88c05aa3dcb242e19a/src/transformers/loss/loss_utils.py#L32-L47

**Comment by ArthurZucker** [comment]
It is indeed! 🤗 hope your fears are calmed, we refactored this to make it easier for the community to hack the loss!

**Comment by ShengYun-Peng** [comment]
Thanks!
