### ISSUE TITLE
Typo in agent system prompts

### ISSUE THREAD

**Issue by jimgoo** [huggingface/transformers#35109]
https://github.com/huggingface/transformers/blob/98e8062df3cf82b367e8a243963e4afb0d9d3407/src/transformers/agents/prompts.py#L132

System prompt for both the JSON and Code agents says: 

```
Above example were using notional tools that might not exist for you. You only have acces to those tools:
<<tool_descriptions>>
```

I suggest changing  it to refer to the tools below: `You only have access to these tools:`.

**Comment by Dodesimo** [comment]
I think langchain has a good prompt for this purpose that makes sense: https://python.langchain.com/docs/how_to/tool_calling/

**Comment by Rocketknight1** [comment]
cc @aymeric-roucher

**Comment by aymeric-roucher** [comment]
We built this system prompt with awareness of what's done in other frameworks like `LangChain` or `Autogen`.
I don't see the typo here? I think the clarification of "notional tools" is important and we should keep it.

**Comment by jimgoo** [comment]
It says `You only have acces to those tools:`, but "acces" is spelled wrong and "those" should be "these" since its referring to the user providing tools below not the notional tools above.

**Comment by aymeric-roucher** [comment]
Oh I see! Thanks a lot for pointing this out!
