### ISSUE TITLE
[Query] Preprocessing Tutorial

### ISSUE THREAD

**Issue by ariG23498** [huggingface/transformers#35111]
https://github.com/huggingface/transformers/blob/98e8062df3cf82b367e8a243963e4afb0d9d3407/docs/source/en/preprocessing.md?plain=1#L394

I think there should be a `min()` between the height and the width here to get the shortest edge.

**Comment by Rocketknight1** [comment]
I think image processors can specify either a `shortest edge` or separate `height` and `width` for the desired image size, so I think keeping the 2-tuple rather than the `min()` is correct
