### ISSUE TITLE
How to load local transformers?

### ISSUE THREAD

**Issue by yiyexy** [huggingface/transformers#35118]
transformers==4.47.0.dev0
 
I want to use my local transformers. And I tried to set `sys.insert(0,'xxx/transformers/src')` and `PYTHONPATH=xxx/transformers/src`, but they doesn't work.

PLZ, tell me why.

**Comment by Rocketknight1** [comment]
The easiest way to do this is to go to the directory of your local clone of the `transformers` repo and `pip install -e .`. This will install the pip package in editable mode, and any changes you make in that directory will be reflected when you `import transformers`.

**Comment by yiyexy** [comment]
@Rocketknight1  THX for your suggestion. I will try to do it!
