### ISSUE TITLE
Isort installed from github branch does not correspond to circle ci isort

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#3515]
# 🐛 Bug

## Information

Installing isort via: 

`$ pip install -U git+git://github.com/timothycrosley/isort.git@e63ae06ec7d70b06df9e528357650281a3d3ec22#egg=isort`

does not correspond to the circle ci version anymore, so that `make style` formatting leads to circle-ci make the code quality test fail. 
     
- `transformers` version: 2.6.0                                                                          
- Platform: Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic                                       
- Python version: 3.6.9                                                                                  
- PyTorch version (GPU?): 1.4.0+cpu (False)                                                              
- Tensorflow version (GPU?): 2.1.0 (False)

**Comment by BramVanroy** [comment]
Looking at the CI config, it should install the correct version, though:

https://github.com/huggingface/transformers/blob/e5c393dcebf42eaec9c1e1d619b5a7788a2d7c65/.circleci/config.yml#L89

**Comment by patrickvonplaten** [comment]
Hi @BramVanroy, 

Thanks for your answer :-) 
I get the feeling that it's somehow related to my computer.

Running `pip install git+git://github.com/timothycrosley/isort.git@e63ae06ec7d70b06df9e528357650281a3d3ec22#egg=isort` in my terminal installs the same isort version / the exact same code (isort-4.3.21)

as if running 

`pip install isort`

When I `pip uninstalled isort` and reinstalled it with `pip install git+git://github.com/timothycrosley/isort.git@e63ae06ec7d70b06df9e528357650281a3d3ec22#egg=isort` the library was not the same anymore. Any ideas what could be happening here on my computer? I tried deleting the pip cache, but no success yet :-/.

**Comment by patrickvonplaten** [comment]
Ok for some reason, upgrading python3.6 to python3.7 solved the problem for me
