### ISSUE TITLE
Incorrect file structure in convert_mask2former_original_pytorch_checkpoint_to_pytorch.py?

### ISSUE THREAD

**Issue by yjwnb6** [huggingface/transformers#35178]
### System Info

- `transformers` version: 4.34.0
- Platform: Linux-6.8.0-31-generic-x86_64-with-glibc2.17
- Python version: 3.8.20
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.5
- Accelerate version: 0.23.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@amyeroberts @qubvel 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I have problem when running convert_mask2former_original_pytorch_checkpoint_to_pytorch.py
1. I have the path: `~/my_project/checkpoints/coco/instance-segmentation/my_model.pkl`
2. I have the path: `~/my_project/configs/coco/instance-segmentation/my_configs.yaml`
3. I run the following in terminal: `python convert_mask2former_original_pytorch_checkpoint_to_pytorch.py     --checkpoints_dir ~/my_project/checkpoints     --configs_dir ~/my_project/configs     --mask2former_dir ~/work/Mask2Former`
4. The error happens: `coco must be wrong since acceptable values are: instance-segmentation, panoptic-segmentation, semantic-segmentation.`

### Expected behavior

In line 907, I print the input path: `~/my_project/checkpoints/coco/instance-segmentation/my_model.pkl`
In line 909, my `model_name_raw` is `instance-segmentation`, while the comment in line 908 says `# model_name_raw is something like maskformer2_swin_small_bs16_50ep.` The model_name_raw should be `my_model` from my understanding

**Comment by Rocketknight1** [comment]
Hi @yjwnb6 - I don't understand how that error is happening with those paths. Can you print the value of `segmentation_task_name` on line 912?
