### ISSUE TITLE
Issue loading custom tokenizer for fine-tuning gpt2

### ISSUE THREAD

**Issue by CutAs** [huggingface/transformers#3525]
I'm trying to fine-tune gpt2 with a custom tokenizer. It was working fine just over 10 days ago, with  --tokenizer_name=/path to vocab and merges folder/  and now it cannot load, asking to check if it's a correct model identifier or contains a config.json file. As if instead of a tokenizer it is now trying to load a model? It also asked for an extra model identifier in the config file of my model, which before was not required.

I suppose there was a library update? What would be the workaround? Thanks in advance.

**Comment by julien-c** [comment]
Can you post a sample code?
