### ISSUE TITLE
Adding CohereForSequenceClassification to Cohere

### ISSUE THREAD

**Issue by liuhaoran124578** [huggingface/transformers#35260]
### Feature request

I’ve noticed that the Cohere models do not include a ForSequenceClassification implementation. Is it due to some issues that prevent this from being done, or was there simply not enough time to implement this requirement?

### Motivation

Recently, I've been learning how to use large models for human dialogue preference classification. I noticed that Cohere has a model called aya-expanse-8b. I wanted to use this model but found that there is no corresponding ForSequenceClassification implementation available for it. However, I noticed that such an implementation is available for Gemma2.

### Your contribution

I have attempted to implement it by following the approach used for Gemma2, but I have not yet validated it.
If it’s merely a time issue preventing the implementation of ForSequenceClassification in transformers, I’d be more than willing to contribute by adding this feature for Cohere.

**Comment by Rocketknight1** [comment]
I think we'd be happy to accept this PR, yes!

**Comment by liuhaoran124578** [comment]
> I think we'd be happy to accept this PR, yes!

thx😊
