### ISSUE TITLE
DOC: Typo In Audio Classification Documentation

### ISSUE THREAD

**Issue by Uvi-12** [huggingface/transformers#35304]
The term "finetune" is used throughout the documentation, but the correct form should be "fine-tune".

**Comment by Rocketknight1** [comment]
I think both are acceptable! Words that are constantly used in the same hyphenated pairing in English often get merged into a single word over time (e.g. "e-mail" was the only correct form 20 years ago but now "email" is completely fine). See the [relevant Wikipedia section](https://en.wikipedia.org/wiki/Hyphen#Prefixes_and_suffixes) for more.
