### ISSUE TITLE
Torch is installed but still getting this error "RuntimeError: At least one of TensorFlow 2.0 or PyTorch should be installed. "

### ISSUE THREAD

**Issue by kartikihx** [huggingface/transformers#35309]
### System Info

- `transformers` version: 4.47.0
- Platform: Linux-5.11.0-1021-azure-x86_64-with-glibc2.31
- Python version: 3.10.16
- Huggingface_hub version: 0.27.0
- Safetensors version: 0.4.5
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.5.1+cu124 (False)
- Tensorflow version (GPU?): 2.18.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. I created a new environment in conda & activated it with python=3.10
2. Installed jupyter, transformers,tensorflow,torch
3. Tried running this code in jupyter
```
from transformers import pipeline
sentiment_pipeline = pipeline("sentiment-analysis")
```
4. Got the error "RuntimeError: At least one of TensorFlow 2.0 or PyTorch should be installed."

### Expected behavior

Hi @sanchit-gandhi @Rocketknight1 & HF Team,
I am not able to run transformer pipelines due to the error mentioned in the reproduction steps.
Please advise, thank you!

**Comment by Rocketknight1** [comment]
This is unusual - I haven't seen any reports of this failing for anyone else, which suggests it might be an environment issue. Can you try a fresh environment with conda or something like that and check if the issue recurs?

**Comment by bhuvanmdev** [comment]
You most probably have installed the packages in a different environment than the current one your using to execute the code. Check it once.

**Comment by kartikihx** [comment]
I re-ran and got a new error asking me to install tf-keras. After installing that, I am now able to import transformers successfully
