### ISSUE TITLE
How to use a custom Image Processor?

### ISSUE THREAD

**Issue by glamourzc** [huggingface/transformers#35316]
I want to use the processor in the form of `auto_map` but when using `AutoProcessor.from_pretrained`, I am unable to load the custom `ImageProcessor`.

The root cause lies in the use of the `transformers_module` to initialize the class in `ProcessorMixin`. 

https://github.com/huggingface/transformers/blob/c7e48053aab09ad11efa2ad12513e9ab56f29563/src/transformers/processing_utils.py#L1018

Even though I have overridden the _get_arguments_from_pretrained method, this issue still exists in the `__init__`. 

https://github.com/huggingface/transformers/blob/c7e48053aab09ad11efa2ad12513e9ab56f29563/src/transformers/processing_utils.py#L383

Perhaps I could avoid inheriting from ProcessorMixin, but I would like to know if there is a more elegant way to achieve this functionality?

**Comment by zucchini-nlp** [comment]
Slightly may be related to https://github.com/huggingface/transformers/issues/34307#issuecomment-2547746188. There is a way to do that by adding `transformers.MyImageProcessor = MyImageProcessor` in the `processor_mymodel.py` file, but apparently it causes errors in certain import order
