### ISSUE TITLE
tokenizer cannot load form model on disk

### ISSUE THREAD

**Issue by makaveli10** [huggingface/transformers#3570]
I wanted to load model saved on disk but it keeps on throwing this error

    File "train.py", line 1, in <module>
     import config
    File "/media/saurabh/D/code/bert_imdb_sentiment/src/config.py", line 14, in <module>
     do_lower_case=True
     File "/home/saurabh/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 393, in from_pretrained
     return cls._from_pretrained(*inputs, **kwargs)
     File "/home/saurabh/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 496, in _from_pretrained
     lst(cls.vocab_files_names.values()),
    OSError: Model name '.../input/bert_based_uncased/' was not found in tokenizers model name list 
    (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-
    multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased,   
    bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-
    uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-
    squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-
    dbmdz-uncased, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-
    cased). We assumed '..input//bert_based_uncased/' was a path, a model identifier, or url to a 
    directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at 
    this path or url.

**Comment by Liu0329** [comment]
@makaveli10 how to solve it ?
