### ISSUE TITLE
T5 fine tune for seq2seq generation

### ISSUE THREAD

**Issue by tuhinjubcse** [huggingface/transformers#3576]
# ❓ Questions & Help

## Details

Hi
Is a script available for fine-tuning T5 base or large to to do seq2seq generative tasks like translation or dialog generation?

https://github.com/huggingface/transformers/blob/master/examples/run_generation.py

Doesn't seem to have T5

**Comment by tuhinjubcse** [comment]
@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Not yet :-) For translation you could try to create a `run_train.py` script using the following resources:

- How to run `T5` for translation: https://github.com/huggingface/transformers/tree/master/examples/translation/t5
- How to train `Bart` for summarization (should be very similar to "How to train" T5 for translation): https://github.com/huggingface/transformers/blob/master/examples/summarization/bart/run_train.sh and https://github.com/huggingface/transformers/blob/master/examples/summarization/bart/run_bart_sum.py

**Comment by patrickvonplaten** [comment]
For dialog generation - I would not recommend using T5, but rather a "decoder-only" model like gpt2. You could take a look at this script with implements a SOTA dialogue bot using DialoGPT from Microsoft: https://huggingface.co/microsoft/DialoGPT-medium#how-to-use

**Comment by prabalbansal** [comment]
Thanks for answering. One more query: how to create the **data files** and **vocab file** for T5. 

If I am not wrong, it requires 4 data files. And in source files, each instance should have a prefix like "translate English to German: ".

**Comment by prabalbansal** [comment]
@sshleifer

**Comment by sshleifer** [comment]
in examples/transformer_base.py change line 105 to
```python
avg_loss = getattr(self.trainer, "avg_loss", 0.0)
```

**Comment by prabalbansal** [comment]
@sshleifer Thanks for the reply. It didn't work. and have the same error. Below is the screenshot of the changed line.

<img width="937" alt="Screenshot 2020-04-12 at 9 17 24 PM" src="https://user-images.githubusercontent.com/30004110/79077852-8a308c00-7d04-11ea-92a2-30d9c6fb0c84.png">

**Comment by hugoabonizio** [comment]
@prabalbansal I think @sshleifer means line 107, so I added this patch in PR #3768

**Comment by prabalbansal** [comment]
@hugoabonizio Thanks for the patch. It works.

**Comment by prabalbansal** [comment]
@sshleifer How to use this fine-tuned model which is generated after training as evaluation scripts use pre-trained models only.

**Comment by prabalbansal** [comment]
When I use the model to predict for test set using the following command:

python '/content/transformers-master/examples/summarization/bart/run_bart_sum.py' --data_dir='/content/drive/My Drive/two_keywords/' --model_type=t5 --output_dir=/content/t5 --do_predict --model_name_or_path=t5-small

Error generated:
<img width="1010" alt="Screenshot 2020-04-13 at 6 18 47 PM" src="https://user-images.githubusercontent.com/30004110/79137728-8a3b9500-7db3-11ea-90e4-218cbc3e1e74.png">

**Comment by MichaelZhouwang** [comment]
> Thanks for answering @patrickvonplaten
> One more query: how to create the **data files** and **vocab file** for T5.
> 
> If I am not wrong, it requires 4 data files and 1 vocab file. And in train.source and val.source files, each instance should have a prefix like "translate English to German: ". I prepare the data in the same format.
> It gives this error.
> TypeError: 'NoneType' object is not iterable
> ![image](https://user-images.githubusercontent.com/30004110/78461843-b2006e00-76cc-11ea-9be8-06171cad86e5.png)

Hi, I didn't understand why you have to prepare the vocab file. I think the pertrained T5 and its default tokenizer will take care of the tokenization? Thanks for your response.

**Comment by prabalbansal** [comment]
@MichaelZhouwang  yes we didn't need vocab file here.

**Comment by Valdegg** [comment]
> For dialog generation - I would not recommend using T5, but rather a "decoder-only" model like gpt2. You could take a look at this script with implements a SOTA dialogue bot using DialoGPT from Microsoft: https://huggingface.co/microsoft/DialoGPT-medium#how-to-use


Hi Patrick,

I'm trying out T5 and BART for dialogue generation.  

I'm wondering why you say that it's better to just have a decoder.  Both FacebookAI's Blender and Google's Meena had encoders in their architectures.

What's the reason for decoder-only systems being better?

**Comment by sshleifer** [comment]
1) @Valdegg I think you are correct that it makes sense to use a seq2seq model.
2) We are also currently working on porting blenderbot from parlai, which was trained on dialogue. 3) 3) We have new forums at https://discuss.huggingface.co/ for discussing higher-level things like which model to use.
