### ISSUE TITLE
DistilBert not giving hidden states

### ISSUE THREAD

**Issue by Ierezell** [huggingface/transformers#3577]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): DistilBert

Language I am using the model on (English, Chinese ...): Multilingual

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name) just running inference
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Load modules
2. Create model with output_hidden_layers=True
3. run inference on one sentece

`from transformers import BertModel, BertTokenizerFast, BertConfig`
`from transformers import DistilBertModel, DistilBertTokenizerFast, DistilBertConfig`
`import torch`

`bert_config = BertConfig(output_hidden_states=True)`
`bert = BertModel(bert_config)`
`bert = bert.from_pretrained("bert-base-multilingual-cased")`
`bert_tokenizer = BertTokenizerFast.from_pretrained("bert-base-multilingual-cased")`

`distil_bert_config = DistilBertConfig(output_hidden_states=True)`
`distil_bert = DistilBertModel(distil_bert_config)`
`distil_bert = distil_bert.from_pretrained("distilbert-base-multilingual-cased")`
`distil_bert_tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-multilingual-cased")`

`sentence = "One stupid dummy sentence to test !"`

`input_bert = torch.tensor(bert_tokenizer.encode(sentence)).unsqueeze(0)`
`input_distil_bert = torch.tensor(distil_bert_tokenizer.encode(sentence)).unsqueeze(0)
`

`output_bert = bert(input_bert)`
`outupt_distil_bert = distil_bert(input_distil_bert)`
## Expected behavior
Return a tuple with 2 elements (like Bert)

Exemple of bert and desired behavior of distilbert: 
`print(len(output_bert)) # => 2`
`print(output_bert[0].size()) # => 1, 18, 768`
`print(output_bert[1].size()) # => 1, 768`

## Real behavior 
Return tuple of only 1 element 
`print(len(outupt_distil_bert)) # => 1`
`print(outupt_distil_bert[0].size()) # => 1, 18, 768`

## Environment info
- `transformers` version: 2.7.0
- Platform: Linux 5.5.8-arch1-1
- Python version: Python 3.8.1
- PyTorch version (GPU?): 1.4.0 (GPU)
- Tensorflow version (GPU?): None
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by tusharmakkar08-eightfold** [comment]
@Ierezell I am facing same issue. How did you fix this issue?
