### ISSUE TITLE
Cannot load model in tranformers

### ISSUE THREAD

**Issue by gdet** [huggingface/transformers#3591]
Hello, I tried to upload your model and I get this error: 

    tokenizer = AutoTokenizer.from_pretrained("nlpaueb/bert-base-greek-uncased-v1")
    model = AutoModelWithLMHead.from_pretrained("nlpaueb/bert-base-greek-uncased-v1")

    ERROR:pytorch_transformers.modeling_utils:Model name 'nlpaueb/bert-base-greek-uncased-v1' 
    was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, 
    bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, 
    bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking,
    bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). 
    We assumed 'nlpaueb/bert-base-greek-uncased-v1' 
    was a path or url but couldn't find any file associated to this path or url.

If I download the model and upload it from a folder in the system I get this error: 

    tokenizer = AutoTokenizer.from_pretrained("/home/transformers/huggingface/greekaueb")
    model = AutoModelWithLMHead.from_pretrained("/home/transformers/huggingface/greekaueb")

    ValueErrorValueError: : Unrecognized model identifier in /home/hatzimin/transformers
    /huggingface/greek_transfer_learning/greekaueb. 
    Should contains one of 'bert', 'openai-gpt', 'gpt2', 'transfo-xl', 'xlnet', 'xlm', 'roberta'

**Comment by LysandreJik** [comment]
It seems you have a very old version of this repository (when it was still named `pytorch_transformers`). Please update to the latest version or you won't have all the features (like access to the model hub).

**Comment by gdet** [comment]
I fixed the version and the error was fixed. But now I get 

    AttributeError: 'BertTokenizer' object has no attribute 'encoder'
Do I have another problem with version? I also used 

    pip3 install --upgrade pytorch-pretrained-bert
Thank you

**Comment by BramVanroy** [comment]
Please post the code and full trace that gave you this error.

**Comment by gdet** [comment]
tokenizer = AutoTokenizer.from_pretrained("nlpaueb/bert-base-greek-uncased-v1")
    model = AutoModelWithLMHead.from_pretrained("nlpaueb/bert-base-greek-uncased-v1")
    model.to(args.device)
    # Add special tokens if they are not already added
    add_special_tokens_(model, tokenizer)

    def add_special_tokens_(model, tokenizer):
    """ Add special tokens to the tokenizer and the model if they have not already been added. """
       orig_num_tokens = len(tokenizer.encoder)
       num_added_tokens = tokenizer.add_special_tokens(ATTR_TO_SPECIAL_TOKEN) # doesn't add if they are already there
       if num_added_tokens > 0:
          model.resize_token_embeddings(new_num_tokens=orig_num_tokens + num_added_tokens)

**Comment by LysandreJik** [comment]
That's because the tokenizer does not have an `encoder` attribute. If you're looking to get the size of the tokenizer, you can do it with `len(tokenizer)`.
