### ISSUE TITLE
CTRL generates French text when I want English texts

### ISSUE THREAD

**Issue by AdaUchendu** [huggingface/transformers#3597]
# ❓ Questions & Help

## Details

CTRL generates French texts when I want English texts.
I run this command: **python examples/run_generation.py  --model_type ctrl --model_name_or_path ctrl --prompt "Looking well today" --length 500 --temperature 0.8 --repetition 1.2**

What do I need to add or change to generate English texts only?

**Comment by LysandreJik** [comment]
CTRL uses control codes, as is mentioned in our documentation, with examples on the [original repository](https://github.com/salesforce/ctrl#generations). Have you tried using these control codes?
