### ISSUE TITLE
After enable fp16, torch.save model has error

### ISSUE THREAD

**Issue by Charonnnnn** [huggingface/transformers#3598]
# 🐛 Bug

After complete training, the model cannot be saved.
## Information
![image](https://user-images.githubusercontent.com/37766299/78298025-7b5b1400-7563-11ea-8928-aa1dae6fb0eb.png)
![image](https://user-images.githubusercontent.com/37766299/78298046-8746d600-7563-11ea-955e-49b1e6673771.png)

**Comment by BramVanroy** [comment]
Please use the template in the future. It is there for a reason. As mentioned in the template, don't post a screenshot. Use code blocks, post your code or the example script that you used, and the error trace. Also provide your version of PyTorch and Python.

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
