### ISSUE TITLE
🐛 Summarization pipeline : T5-base much slower than BART-large

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#3605]
# 🐛 Bug

## Information

Model : `bart-large-cnn` and `t5-base`

Language : English

The problem arises when using : [this colab notebook](https://colab.research.google.com/drive/1iAIFX1QQiFm1F01vMmnAgFh4oH1H-K8W), using both BART and T5 with pipeline for Summarization.

Dataset : CNN/DM

## To reproduce

Run the notebook and measure time for inference between the 2 models. On my run, I have :

```
BART = 73s
T5 = 369s
```

## Expected behavior

I expected T5 to be at least as fast as BART, since there is less parameters (for the base version at least). Instead it takes much longer with T5...

@patrickvonplaten Do you happen to know why T5 is so slow ?

**Comment by patrickvonplaten** [comment]
Hi @Colanim, thanks a lot for your speed comparison :-). 

It might be possible that the pipelines used different default parameters for `T5` and `Bart` under the hood which strongly influence their running times.
Besides `min_length` and `max_length` could you also insert those parameters into both `T5` and `Bart` to overwrite the default parameters: 

```
      "early_stopping": True
      "length_penalty": 2.0
      "no_repeat_ngram_size": 3
      "num_beams": 4
```

If there is still a big difference in time, then I guess we have to take a closer look!

**Comment by Colanim** [comment]
Thanks for you fast answer @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Ok, good to know! thanks for doing the comparison @Colanim - I will take a lookt into it!
@sshleifer - that might interest you as well :-)

**Comment by craffel** [comment]
Sounds worth it!
