### ISSUE TITLE
Add code to pretrain T5 model from scratch

### ISSUE THREAD

**Issue by LiweiPeng** [huggingface/transformers#3624]
# 🚀 Feature request

The T5 model can significantly improve NLP task accuracies. However, the existing pretrained models are all in English. I'd like to pretrain T5 model on different language datasets from scratch.

Can you add code on pretraining T5 model? Thanks.

**Comment by vapyc** [comment]
@patrickvonplaten Can we pre-train T5 from scratch on any task? I want to use it for Question Answering.

**Comment by patrickvonplaten** [comment]
Many notebooks for T5 are now added to the community notebooks :-)

**Comment by geekydevu** [comment]
@patrickvonplaten can you share the notebook which show T5 pre-training if it is available ?

**Comment by mralexisw** [comment]
@patrickvonplaten as of today, I didn't find any notebook that is related to T5 *pretraining* in the [community notebooks collection ](https://huggingface.co/transformers/master/community.html#community-notebooks). Could you elaborate more on where there is a codebase to do the pretraining? Thanks!

**Comment by Arij-Aladel** [comment]
> @patrickvonplaten as of today, I didn't find any notebook that is related to T5 pretraining in the community notebooks collection . Could you elaborate more on where there is a codebase to do the pretraining? Thanks!

Yes I agree there is no guide for pretraining
