### ISSUE TITLE
Summarization pipeline - Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/facebook/bart-large-cnn/modelcard.json'

### ISSUE THREAD

**Issue by metahgva** [huggingface/transformers#3639]
# 🐛 Bug

## Information
Loading the summarization pipeline will result in below assertion: 

> Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/facebook/bart-large-cnn/modelcard.json' to download model card file.
> Creating an empty model card.

The problem arises when using:
* [V] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

`!pip install -q transformers --upgrade
from transformers import pipeline
summarizer = pipeline(task="summarization")`

1. Execute above code

## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by josiahdavis** [comment]
Having exact same issue.

**Comment by alessandrobessi** [comment]
This is issue has been closed, but I continue to get the same exact error.

**Comment by julien-c** [comment]
Did you update from master. 

Can you paste the output of `transformers-cli env`

**Comment by alessandrobessi** [comment]
I just upgraded to the latest version:
```
- `transformers` version: 2.8.0
- Platform: Linux-5.3.0-46-generic-x86_64-with-Ubuntu-19.10-eoan
- Python version: 3.7.5
- PyTorch version (GPU?): 1.1.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No
```

**Comment by julien-c** [comment]
The fix is not in a released version yet so you need to install from source.
