### ISSUE TITLE
❓ How to run pipeline (summarization) in FP16 mode ?

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#3645]
# ❓ Questions & Help

I couldn't find on the documentation any parameter that allow running a pipeline in FP16 mode. **Did I miss it or it's not a feature yet ?**

**Comment by patrickvonplaten** [comment]
@sshleifer - do you have more info on that?

**Comment by sshleifer** [comment]
You can't without editing the code, unfortunately.

**Comment by artmatsak** [comment]
Running a pipeline in FP16 mode would be really useful for optimizing the GPU RAM usage. Can this be turned into a feature request?
