### ISSUE TITLE
Wrong tokenizer configuration in sentiment-analysis pipeline

### ISSUE THREAD

**Issue by leonhardhennig** [huggingface/transformers#3675]
# 🐛 Bug

## Information

When following the Pipelines Notebook 03-pipelines.ipynb, Sentiment Analysis tasks gives wrong result ("NEGATIVE") for example 'Such a nice weather outside !'. 
```
nlp_sentence_classif = pipeline('sentiment-analysis')
nlp_sentence_classif('Such a nice weather outside !')
[{'label': 'NEGATIVE', 'score': 0.97545063}]
```

Probable reason: pipelines.py configuration uses uncased model, but cased tokenizer. Tokenizer should probably be 'distilbert-base-uncased'. 

```
"sentiment-analysis": {
        "impl": TextClassificationPipeline,
        "tf": TFAutoModelForSequenceClassification if is_tf_available() else None,
        "pt": AutoModelForSequenceClassification if is_torch_available() else None,
        "default": {
            "model": {
                "pt": "distilbert-base-uncased-finetuned-sst-2-english",
                "tf": "distilbert-base-uncased-finetuned-sst-2-english",
            },
            "config": "distilbert-base-uncased-finetuned-sst-2-english",
            "tokenizer": "distilbert-base-cased",
        },
    },
``` 

Model I am using (Bert, XLNet ...): distilbert-base-uncased-finetuned-sst-2-english (preconfigured sentiment-analysis pipeline)

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [x] the official example scripts: 03-pipelines.ipynb
* [ ] my own modified scripts: (give details below)

## Expected behavior

Example sentence should be labeled as POSITIVE.

## Environment info
     
- `transformers` version: 2.8.0
- Platform: Linux Mint
- Python version: 3.7
- PyTorch version (GPU?): 1.4.0 (no)
- Tensorflow version (GPU?): 2.1.0 (no)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

**Comment by alwils** [comment]
I'm having the same issue

**Comment by alwils** [comment]
> I'm having the same issue

I got this working by using the following code:

`    # Allocate a pipeline for sentiment-analysis
    nlp = pipeline('sentiment-analysis')
    nlp.tokenizer = transformers.DistilBertTokenizer.from_pretrained('**distilbert-base-uncased**')`

Thanks for pointing me in the right direction LysandreJik!
