### ISSUE TITLE
run_generation.py with empty input

### ISSUE THREAD

**Issue by r0levrai** [huggingface/transformers#3678]
Hi,

I would like to generate text following some context but also from scratch as seen in *Write with Transformer*. Using both
* `python run_generation_callable.py --model_type=gpt2 --model_name_or_path=gpt2` and feeding an empty prompt to the `Model prompt >>> `
* or changing the line
`prompt_text = args.prompt if args.prompt else input("Model prompt >>> ")`
in the source to
`prompt_text = args.prompt`
and using
`python run_generation_callable.py --model_type=gpt2 --model_name_or_path=gpt2 --prompt ""`

result in a `RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous` (tell me if you need the complete stack trace or more detail for the reproduction).

Thanks by advance for any tips, workarounds or directions on achieving this!

**Comment by patrickvonplaten** [comment]
Hi @r0levrai, 

sorry for responding so late. Thanks for spotting the error. Once the linked PR is merged generation with an empty prompt should be fine! 

Also note that there is a generation pipeline now which you could use as follows (once the PR is merged):

```python
from transformers import pipeline
generator = pipeline("text-generation")
generator("") # empty prompt
```

**Comment by r0levrai** [comment]
This is good news, thanks!
