### ISSUE TITLE
How to use GPT2DoubleHeadsModel?

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#3680]
Hello,

I have a question about the example shown in the GPT2DoubleHeadsModel documentation page:
https://huggingface.co/transformers/model_doc/gpt2.html#gpt2doubleheadsmodel

In the example, the input to the GPT2DoubleHeadsModel is simply a set of choices. But what if the multiple choice question that I want to process also includes a question text? so for example,

Bob likes candy; what does Bob like?
a. Bag
b. Burger
c. Candy
d. Pencil

In the example above, the question text would be " Bob likes candy; what does Bob like?"
and the choices will be the Bag, Burger, Candy and Pencil. How should I pre-process my multiple choice questions to be used with the GPT2DoubleHeadsModel?

For example, given that the token that will be used for the classification is "<|endoftext|>" (this is the default eos token for the GPT2 models), would the following be fine?

```python
import torch
from transformers import GPT2Tokenizer, GPT2DoubleHeadsModel

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2DoubleHeadsModel.from_pretrained('gpt2')

choices = [ "Bob likes candy ; what does Bob like ?  Bag <|endoftext|>",
                   "Bob likes candy ; what does Bob like ?  Burger <|endoftext|>",
                   "Bob likes candy ; what does Bob like ?  Candy <|endoftext|>",
                  "Bob likes candy ; what does Bob like ?  Pencil <|endoftext|>"]

encoded_choices = [tokenizer.encode(s) for s in choices]
eos_token_location = [tokens.index(tokenizer.eos_token_id) for tokens in encoded_choices]

input_ids = torch.tensor(encoded_choices).unsqueeze(0) 
mc_token_ids = torch.tensor([eos_token_location]) 
outputs = model(input_ids, mc_token_ids=mc_token_ids)
lm_prediction_scores, mc_prediction_scores = outputs[:2]
```

Thank you,

**Comment by VikasRajashekar** [comment]
I see that the issue is closed? what is the answer?

**Comment by patrickvonplaten** [comment]
We are trying to move such questions more and more to the forum because they get more traction there and the library's issues should primarily be used for "real" issues. 

It would be awesome if you guys could post the question on 
https://discuss.huggingface.co/

**Comment by Kingsleyandher** [comment]
I meet the same question.
