### ISSUE TITLE
Requesting model for TFAlbertForQuestionAnswering

### ISSUE THREAD

**Issue by jarednielsen** [huggingface/transformers#3685]
# 🌟 New model addition

Is there support for adding a TensorFlow version of the AlbertForQuestionAnswering model? I would be happy to contribute the work. This would also enable the `run_squad.py` example script for TensorFlow.

It also looks like [the preprocessing of SQuAD data is different](https://github.com/huggingface/transformers/blob/master/src/transformers/data/processors/squad.py#L349) for PyTorch and TensorFlow. PyTorch has an option to return `all_example_index`, while TensorFlow does not. This means that running the model evaluation script (which takes the max F1/EM over all answers) is only possible in PT. Running SQuAD evaluation in TensorFlow is important for my use case, and I would love to understand the design decisions or difficulties that went into that decision. Again, happy to contribute - any support or objections for aligning the data preprocessing techniques?

**Comment by LysandreJik** [comment]
Hi! We don't currently have a `run_tf_squad` script, but we would appreciate a contribution! The preprocessing of SQuAD shouldn't be different between pytorch and tensorflow. We haven't gotten to testing that as we haven't gotten to writing that script yet.

If we're to have a TF SQuAD script, we would have to align the pre-processing techniques as well!

**Comment by LysandreJik** [comment]
And we would definitely welcome a PR introducing `TFAlbertForQuestionAnswering`!

**Comment by jarednielsen** [comment]
Resolved in https://github.com/huggingface/transformers/commit/6d00033e97e1751a897f2317fdfd35dd853cee29 .
