### ISSUE TITLE
Bug in variable name in NER

### ISSUE THREAD

**Issue by TarasPriadka** [huggingface/transformers#3686]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Irrelevant

Language I am using the model on (English, Chinese ...): Irrelevant

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: NER
* [ ] my own task or dataset: (give details below)

## Error

```
File "/transformers/examples/ner/utils_ner.py", line 123, in convert_examples_to_features special_tokens_count = tokenizer.num_added_tokens() 
AttributeError: 'BertTokenizer' object has no attribute 'num_added_tokens'
```

## Issue

After update to new Tokenizers, some util files are broken. Found one in examples/ner/utils_ner.py.
Need to change line 123 from num_added_tokens to num_special_tokens_to_add.

**Comment by minhtuev** [comment]
I also see the same issue, has there been a fix for this?
AttributeError: 'BertTokenizer' object has no attribute 'num_added_tokens'

**Comment by TarasPriadka** [comment]
@minhtuev you can change `num_added_tokens` to `num_special_tokens_to_add`. This made the fix for me
