### ISSUE TITLE
Is it possible to use multiprocessing for pipelines?

### ISSUE THREAD

**Issue by Weilin37** [huggingface/transformers#3687]
I am trying to use multiprocessing for pipelines, but it seems that it's not working. I think it's because the pipeline already uses multiprocessing features and so you can't have multiprocessing inception. Anyone able to get it to work?

**Comment by satya77** [comment]
I have the same the problem. When you close the issue does it mean that it is fixed?

**Comment by sharejing** [comment]
I have also met this problem, how can I solve this? Thanks！！！！

**Comment by satya77** [comment]
> I have also met this problem, how can I solve this? Thanks！！！！

I switched to using `nlp.pipe`, which is the built-in function for multiprocessing, instead of doing it by hand.
