### ISSUE TITLE
BertSelfAttention have not Add and Norm layer, why???

### ISSUE THREAD

**Issue by weiliangxiao** [huggingface/transformers#3690]

**Comment by LysandreJik** [comment]
It's in [`BertSelfOutput`](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_bert.py#L261) which is called right after the `BertSelfAttention` in [`BertAttention`](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_bert.py#L316).
