### ISSUE TITLE
cannot import name AddedToken

### ISSUE THREAD

**Issue by nrjvarshney** [huggingface/transformers#3691]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Albert

Language I am using the model on (English, Chinese ...): English

     27 from typing import List, Optional, Sequence, Tuple, Union
     28 
---> 29 from tokenizers import AddedToken, Encoding
     30 from tokenizers.decoders import Decoder
     31 from tokenizers.implementations import BaseTokenizer

ImportError: cannot import name 'AddedToken'

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name): 
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by nrjvarshney** [comment]
Created another environment from scratch and it got resolved.

**Comment by wangxupeng** [comment]
you need install transformers this way:

```
git clone https://github.com/huggingface/transformers
cd transformers
pip install .
```

**Comment by JosefJoubert** [comment]
> you need install transformers this way:
> 
> ```
> git clone https://github.com/huggingface/transformers
> cd transformers
> pip install .
> ```

This worked for me thanks!

**Comment by ahazeemi** [comment]
> you need install transformers this way:
> 
> ```
> git clone https://github.com/huggingface/transformers
> cd transformers
> pip install .
> ```

I was having a similar issue on colab:
```
can't pickle AddedToken objects
```
This solution also worked for me. Thanks!

**Comment by vinejain** [comment]
> you need install transformers this way:
> 
> ```
> git clone https://github.com/huggingface/transformers
> cd transformers
> pip install .
> ```

Thanks much, this worked for me!

**Comment by puraminy** [comment]
> you need install transformers this way:
> 
> ```
> git clone https://github.com/huggingface/transformers
> cd transformers
> pip install .
> ```

This solution doesn't work for me! I don't know maybe there is a conflict with `pip` an `conda`. I guess after I installed a package `bert_score` by conda, this error appeared and won't go
