### ISSUE TITLE
Bug in ElectraForTokenClassification

### ISSUE THREAD

**Issue by LiZongyue** [huggingface/transformers#3699]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): ElectraForTokenClassification

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [√] the official example scripts: (give details below)
  huggingface.co/transformers/model_doc/electra.html#electrafortokenclassification
* [×] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ×] an official GLUE/SQUaD task: (give the name)
* [ √] my own task or dataset: (give details below)
  Ran the example given in the documentation

        from transformers import ElectraTokenizer, ElectraForTokenClassification  
        import torch  

        tokenizer = ElectraTokenizer.from_pretrained('google/electra-small-discriminator')  
        model = ElectraForTokenClassification.from_pretrained('google/electra-small-discriminator')  

        input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute",   
        add_special_tokens=True)).unsqueeze(0)  # Batch size 1  
        labels = torch.tensor([1] * input_ids.size(1)).unsqueeze(0)  # Batch size 1  
        outputs = model(input_ids, labels=labels)  

        loss, scores = outputs[:2]
## To reproduce

1. Start Google Colab
2. Install Transformer and  requriements
3. run the code

## Expected behavior
AttributeError: 'ElectraForTokenClassification' object has no attribute 'num_labels'

## Environment info

     
- `transformers` version: 2.8.0
- Platform: Windows 10
- Python version: 3.7.6
- PyTorch version (GPU?): Colab
- Tensorflow version (GPU?): Colab
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by stefan-it** [comment]
Oh no, it should be `self.config.num_labels` instead of `self.num_labels` [here](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_electra.py#L665)!

**Comment by LysandreJik** [comment]
My bad, it should be fixed now!
