### ISSUE TITLE
Text Generation with XLNet is very Slow

### ISSUE THREAD

**Issue by urlocal12** [huggingface/transformers#3712]
Using the run_generation script to generate text with XLNet is currently extremely slow compared to GPT-2 as mentioned in [this issue](https://github.com/huggingface/transformers/issues/789)

> To generate 100 tokens, XLNet takes **3m22s** while GPT-2 takes **14s**. And it grows exponentially : for 500 tokens, XLNet takes **51m46s** while GPT-2 takes **2m52s**.

More information on why this might be happening is included in the issue. However, it was closed before it could be resolved. If anyone could look into this and maybe reopen the original issue, that would be greatly appreciated. 
Thanks!

**Comment by patrickvonplaten** [comment]
Reopened the previous issue: https://github.com/huggingface/transformers/issues/789 and will take a look next week :-)

**Comment by patrickvonplaten** [comment]
Closing this as well. Reasons are explained in #789.
