### ISSUE TITLE
Unable to load german BERT model

### ISSUE THREAD

**Issue by dakshvar22** [huggingface/transformers#3719]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): BERT

Language I am using the model on (English, Chinese ...): German

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```
from transformers import *
model = TFBertModel.from_pretrained('bert-base-german-dbmdz-cased')
```

I get the following error trace - 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daksh/miniconda3/envs/1.8/lib/python3.6/site-packages/transformers/modeling_tf_utils.py", line 351, in from_pretrained
    assert os.path.isfile(resolved_archive_file), "Error retrieving file {}".format(resolved_archive_file)
  File "/Users/daksh/miniconda3/envs/1.8/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

## Expected behavior

Model should be loaded

## Environment info
     
- `transformers` version: 2.4.1
- Platform: Mac OS
- Python version: 3.6.5
- Tensorflow version (GPU?): 2.1.0
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by julien-c** [comment]
That particular model doesn't have a TF version: https://huggingface.co/bert-base-german-dbmdz-cased#list-files

However, you should be able to convert the PyTorch version to TF, using the `from_pt=True` flag.

**Comment by dakshvar22** [comment]
Thanks for clarifying that @julien-c . Is it possible to add this information(regarding availability of TF and pytorch models) somewhere on this [page](https://huggingface.co/transformers/pretrained_models.html) or maybe a dedicated table for it. It's quite useful info for frameworks which depend on Transformers.

**Comment by stefan-it** [comment]
I'm working on converting our DBMDZ models to TF 😅

**Comment by hotzenklotz** [comment]
The same issue is true for the `uncased` version. Is there a way to force to HuggingFace to download the Torch version instead?

**Comment by julien-c** [comment]
Yes, as I said: `from_pt=True`

**Comment by stefan-it** [comment]
@hotzenklotz You can now use the model under our DBMDZ namespace: `dbmdz/bert-base-german-cased`.

I've uploaded the TF-compatible model and it can be used with:

```bash
from transformers import *
model = TFBertModel.from_pretrained('dbmdz/bert-base-german-cased')
```

**Comment by hotzenklotz** [comment]
@stefan-it Thank you so much. Can we expect to see a TF version of the `uncased` model as well? (And what about Roberta?)

**Comment by stefan-it** [comment]
`dbmdz/bert-base-german-uncased` has also a TF-compatible model now :)

German RoBERTa is currently not planned on our side (unless there's a TPU-supported pre-training script out there) 😅
