### ISSUE TITLE
Tokenizer Encode More than 2 inputs

### ISSUE THREAD

**Issue by pertschuk** [huggingface/transformers#3741]
# 🚀 Feature request

Increasingly I'm seeing more than 2 inputs in some cases to BERT model, separated by [SEP] tokens. Often this helps by including context or for pairwise search ranking. 

## Motivation

Right now I have to manually add the [SEP] token and concat the output to two tokenizer.encode_plus calls. Seems like it would be simple to just grab all the positional args and treat them as additional fields. 

Also seems like this is more expected behavior than arbitrarily limiting encode_plus to single or pairs of text.

## Your contribution

I could submit a PR.

**Comment by Zhylkaaa** [comment]
Had this problem been solved?

**Comment by skpig** [comment]
@Zhylkaaa  It seems that the problem is still unsolved. Are there any easier ways to encode more than 2 inputs with tokenizer?

**Comment by Zhylkaaa** [comment]
@skpig I think the best way is to use `' <sep_token> '.join(inputs)`. For roberta that would be `' <s> '.join(inputs)`.
But keep in mind that some models are designed to have [EOS] token at the and (for roberta it's `</s>`, bert doesn't have one I think)

**Comment by skpig** [comment]
@Zhylkaaa That works. Thanks a lot.
