### ISSUE TITLE
Turning off Verbosity on QA model using Pipeline

### ISSUE THREAD

**Issue by WeiyangSun** [huggingface/transformers#3744]
Hi,

I am looking for a way to turn off the logs warnings. Please refer to the screenshot.

![image](https://user-images.githubusercontent.com/34964824/79020501-9e2a9100-7b3e-11ea-8f63-afb26b11a5a1.png)

This is currently what I am doing.

![image](https://user-images.githubusercontent.com/34964824/79020549-ba2e3280-7b3e-11ea-893d-a527939181a7.png)

Is there any way?

**Comment by nsorros** [comment]
I was just wondering the same thing.
