### ISSUE TITLE
Etract all last hidden states of the input dequences for Question and answering Bert

### ISSUE THREAD

**Issue by LincLabUCCS** [huggingface/transformers#3751]
Hello everyone, 

I am using run_squad.py to finetune Bert for question answering. I would like to save and later extract all last hidden states for all sequences for further use. For example, if I have a dataset of 100 sequences, 64 length, and 768 features. I will eventually have a tensor of (100,64,768).
Is there any possible to do that using the run_squad.py script..

Thank you all

**Comment by AdityaSoni19031997** [comment]
Modify the script :)
