### ISSUE TITLE
Why does `examples/translation/t5` test on newstest2013 rather than newstest2014?

### ISSUE THREAD

**Issue by tholiao** [huggingface/transformers#3759]
# Details

The example in examples/translation/t5 uses `newstest2013`, but authors report against `newstest2014` (presumably newstest2014.full):
> Since this is our final set of experiments, we report results on the test set rather than
the validation set. For CNN/Daily Mail, we use the standard test set distributed with the dataset.
For the WMT tasks, this corresponds to using newstest2014 for English-German
[Original paper, p30](https://arxiv.org/pdf/1910.10683.pdf).

Is this intentional?

**Comment by patrickvonplaten** [comment]
Hey @tholiao,

Thanks for the catch! You're right it should be the newstest2014! Do you want to open a PR to change it? Or I can do it as well

**Comment by tholiao** [comment]
No worries, I'll submit a PR.

**Comment by tholiao** [comment]
@patrickvonplaten, would you mind running evaluate_wmt.py on master and computing sacreBLEU via command line? (`cat newstest2014_de_translations.txt | sacrebleu -t wmt14 -l en-de --tokenize intl`)

**Comment by patrickvonplaten** [comment]
Thanks a lot for the PR! I will running the script once the PR is merged :-)
