### ISSUE TITLE
PPLM Write With Transformer demo not working 

### ISSUE THREAD

**Issue by songproducer** [huggingface/transformers#3762]
# 🐛 Bug

## Information

Model I am using: PPLM

Language I am using the model on (English, Chinese ...): English 

The problem arises when using:
* [ ] the official example scripts: (give details below)
ios Safari and Firefox 

The tasks I am working on is:
Trying out the demo
## To reproduce

1.
2.
3.

## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by LysandreJik** [comment]
cc @julien-c

**Comment by julien-c** [comment]
See https://github.com/huggingface/transformers/issues/4661#issuecomment-636911923
