### ISSUE TITLE
long text classification

### ISSUE THREAD

**Issue by gogokre** [huggingface/transformers#3764]
I want to binary classify documents with max length greater than 512 with bert.
Is there any reference or code for how to do this?

**Comment by rvoak** [comment]
Following!

**Comment by gogokre** [comment]
> Following!

I don't know what it means.

**Comment by singhay** [comment]
Use transformer-XL

**Comment by armancohan** [comment]
Longformer is exactly designed for your use case (https://github.com/allenai/longformer)

**Comment by singhay** [comment]
Reformer and longformer are being worked on to be included in this library.

**Comment by brian8128** [comment]
Looks like they've got longformer now. 

https://huggingface.co/transformers/model_doc/longformer.html

**Comment by nishkalavallabhi** [comment]
Is longformer a multilingual model? or are there options to work with longer texts that are not in English?

**Comment by krzysztoffiok** [comment]
You can also use Text Guide, a clever text truncation method and use a transformer model with a standard 512 limit.
And if you have extremely long text instances (longer than 4096 == Longformer model limit) you can also use this approach to further improve your results.

Paper: https://arxiv.org/abs/2104.07225
Code: https://github.com/krzysztoffiok/TextGuide
A brief description: https://www.quora.com/If-I-have-a-long-text-say-10-paragraphs-how-can-I-use-BERT-or-other-newer-and-better-models-such-as-RoBERTa-for-feature-extraction-that-represents-the-entire-document-Seems-like-BERT-has-limits-Are-there-packages
