### ISSUE TITLE
Why the first item of the config.json of bert is "architectures": ["BertForMaskedLM"]

### ISSUE THREAD

**Issue by janyChan** [huggingface/transformers#3773]
{
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1, 
  "directionality": "bidi", 
  "hidden_act": "gelu", 
  "hidden_dropout_prob": 0.1, 
  "hidden_size": 768, 
  "initializer_range": 0.02, 
  "intermediate_size": 3072, 
  "max_position_embeddings": 512, 
  "num_attention_heads": 12, 
  "num_hidden_layers": 12, 
  "pooler_fc_size": 768, 
  "pooler_num_attention_heads": 12, 
  "pooler_num_fc_layers": 3, 
  "pooler_size_per_head": 128, 
  "pooler_type": "first_token_transform", 
  "type_vocab_size": 2, 
  "vocab_size": 21128
}

why the first item is "architectures": [
    "BertForMaskedLM"
  ]
I see, this is not available in the google version.
Could you tell me what does it mean？

**Comment by julien-c** [comment]
This is a property we added to be able to know what kind of final layers the model has. It is used for instance to enable tagging and filtering on our model hub: https://huggingface.co/models
