### ISSUE TITLE
How to fine tune EncoderDecoder model for training a new corpus of data ?

### ISSUE THREAD

**Issue by banunitte** [huggingface/transformers#3785]
is there any documentation available for the same?

**Comment by patrickvonplaten** [comment]
We are currently working on implementing the encoder decoder framework. See PR: https://github.com/huggingface/transformers/pull/3383

**Comment by patrickvonplaten** [comment]
I think in a week it should be ready :-)

**Comment by patrickvonplaten** [comment]
See https://huggingface.co/patrickvonplaten/bert2bert-cnn_dailymail-fp16#bert2bert-summarization-with-%F0%9F%A4%97-encoderdecoder-framework

**Comment by banunitte** [comment]
Thank u Patrick
