### ISSUE TITLE
Why force tokens in Bart decoding

### ISSUE THREAD

**Issue by chqiwang** [huggingface/transformers#3786]
https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_bart.py#L955

What's the meaning of this line? Why decode \<S\>  when cur_len = 1? Why not when cur_len = 0?

**Comment by patrickvonplaten** [comment]
see https://github.com/huggingface/transformers/issues/3668

**Comment by chqiwang** [comment]
> see #3668

thanks a lot!
