### ISSUE TITLE
Is there a classical transformer model in the project?

### ISSUE THREAD

**Issue by 980202006** [huggingface/transformers#3789]
Hi,
I am studying in some domain that need the original transformer which is from 《attention is what you all need》. Is there an implementation?

**Comment by cozek** [comment]
You might find this useful http://nlp.seas.harvard.edu/2018/04/03/attention.html
I think PyTorch already have it implemented in their library
https://pytorch.org/docs/stable/nn.html?highlight=transformer#torch.nn.Transformer

**Comment by 980202006** [comment]
thank you，It is a answer for me.
