### ISSUE TITLE
Getting large alloc error while evaluating bert-base on NER task

### ISSUE THREAD

**Issue by Sumegh-git** [huggingface/transformers#3794]
# 🐛 Bug

## Information

Model I am using (Bert-base-multilingual-cased,):

Language I am using the model on (English):

The problem arises when using:
Evaluation

The tasks I am working on is:
My own custom dataset having the same as GermEval task format.

Running on **Colab**. 

I believe this is due to memory error. But why should there be memory **error while testing when things were fine during training **?

Max_seq_length during train was 128 and batch_size 8

04/14/2020 19:06:13 - INFO - transformers.modeling_utils -   loading weights file germeval-model/checkpoint-21750/pytorch_model.bin
04/14/2020 19:07:03 - INFO - __main__ -   Loading features from cached file ./cached_dev_bert-base-multilingual-cased_128
04/14/2020 19:07:05 - INFO - __main__ -   ***** Running evaluation  *****
04/14/2020 19:07:05 - INFO - __main__ -     Num examples = 22026
04/14/2020 19:07:05 - INFO - __main__ -     Batch size = 2
Evaluating:   0% 3/11013 [00:01<1:07:38,  2.71it/s]tcmalloc: large alloc 1110605824 bytes == 0x3e706000 @  0x7f207d0051e7 0x7f207a3995e1 0x7f207a3fde88 0x7f207a3fdfa3 0x7f207a49c098 0x7f207a49c8f4 0x7f207a49ca42 0x5678b3 0x5a067e 0x7f207a3e970d 0x50a8af 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x58958c 0x5a067e 0x7f207a3e970d 0x50a8af 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245 0x50a080 0x50aa7d 0x50d390 0x508245

**Comment by lehoanganh298** [comment]
I'm having the same issue. Training is fine but get this error when evaluate.
