### ISSUE TITLE
Calculated offsets are wrong

### ISSUE THREAD

**Issue by dirkgr** [huggingface/transformers#3796]
This is on the latest `master` (from 2020-04-13):
```Python
import transformers
text = 'A, <mask> AllenNLP sentence.'
t = transformers.AutoTokenizer.from_pretrained("roberta-base", use_fast=True, add_special_tokens=True)
x2 = t.encode_plus(text, return_offsets_mapping=True)
print(repr(t.convert_ids_to_tokens(x2['input_ids']))
print(repr([text[start:end] for start, end in x2['offset_mapping']]))
```

This prints (with some manual alignment):
```
['<s>', 'ĠA', ',', '<mask>',   'ĠAllen', 'N', 'LP', 'Ġsentence', '.', '</s>']
['',    'A',  ',', ', <mask>', ' Alle',  'n', 'NL', 'P sentenc', 'e', '']
```

**Comment by thomwolf** [comment]
It's probably normal since Roberta's tokenizers is a byte-level tokenizer which split words at byte-level (ie. possibly smaller than the character unit).

Cc @n1t0

**Comment by n1t0** [comment]
There is a bug indeed, the offsets shouldn't be shifted after the `<mask>` token. I should be able to fix this.
I'm not sure I'll be able to have the right offsets for the `<mask>` token though as this one is tricky.

**Comment by n1t0** [comment]
This is now fixed on the latest `master`, with the output being
```
['<s>', 'ĠA', ',',  '<mask>', 'ĠAllen', 'N', 'LP', 'Ġsentence', '.', '</s>']
['',     'A', ',',  '<mask>',  'Allen', 'N', 'LP',  'sentence', '.', '']  
```
The spaces are not part of the offsets because the `trim_offsets` option is `True` by default.
