### ISSUE TITLE
Clarification about GPT2LMHeadModel lm_head weights

### ISSUE THREAD

**Issue by thesamuel** [huggingface/transformers#3799]
# ❓ Questions & Help

Each time the GPT2LMHeadModel is loaded from pretrained weights, the following is logged:
```
Weights of GPT2LMHeadModel not initialized from pretrained model: ['lm_head.weight']
```

Just to clarify, is this OK because we tie the output (`lm_head`) weights to the input weights?

**Comment by patrickvonplaten** [comment]
yes exactly - this should not be a problem :-)
