### ISSUE TITLE
A bug in the padding of input examples in the NER fine-tuning example

### ISSUE THREAD

**Issue by AMR-KELEG** [huggingface/transformers#3814]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Roberta

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details below)

## To reproduce

1. TODO

## Expected behavior

https://github.com/huggingface/transformers/blob/c59b1e682d6ebaf7295c63418d4570228904e690/examples/ner/utils_ner.py#L123
This line is supposed to return 3 for Roberta models but it's just returning 2 causing the length of the input_ids to be more than the max_seq_len.
This might be the reason for that: https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_roberta.py#L288
TODO: Share the notebook.

## Environment info

     
- `transformers` version: 2.8.0
- Platform: Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.4.0 (True)
- Tensorflow version (GPU?): 2.2.0-rc2 (True)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by AMR-KELEG** [comment]
This PR https://github.com/huggingface/transformers/pull/3803 might be related to the bug but my initial thought is that it will fix it.

**Comment by LysandreJik** [comment]
Hello! Why do you think it should return 3 for RoBERTa models?

It should return 2, single sequences for RoBERTa are built like: 

`<s> tok_0 ... tok_n </s>`, 

with only two special tokens added.

For sequence pairs however, 4 tokens are added: 

`<s> tok_0 ... tok_n </s></s> tok_(n + 1) ... tok2n </s>`

**Comment by AMR-KELEG** [comment]
> Hello! Why do you think it should return 3 for RoBERTa models?
> 
> It should return 2, single sequences for RoBERTa are built like:
> 
> `<s> tok_0 ... tok_n </s>`,
> 
> with only two special tokens added.
> 
> For sequence pairs however, 4 tokens are added:
> 
> `<s> tok_0 ... tok_n </s></s> tok_(n + 1) ... tok2n </s>`

Well, this line suggested this:
https://github.com/huggingface/transformers/blob/c59b1e682d6ebaf7295c63418d4570228904e690/examples/ner/utils_ner.py#L122

Additionally, the current code produced lists of length > `max_sequence_length` so for sure there is a problem there.

**Comment by TarasPriadka** [comment]
I had an issue with the running the NER model. In this commit https://github.com/huggingface/transformers/commit/96ab75b8dd48a9384a74ba4307a4ebfb197343cd `num_added_tokens` got changed into `num_special_tokens_to_add`.  Just changing the name of the variable in the `utils_ner.py` fixed the issue for me.

**Comment by AMR-KELEG** [comment]
> I had an issue with the running the NER model. In this commit [96ab75b](https://github.com/huggingface/transformers/commit/96ab75b8dd48a9384a74ba4307a4ebfb197343cd) `num_added_tokens` got changed into `num_special_tokens_to_add`. Just changing the name of the variable in the `utils_ner.py` fixed the issue for me. However, I had an issue with variable name not being found. Let me know if this fixes you problem.

Hi @TarasPriadka 
Yes, the edit you have suggested solved the problem.
I have found that you have already reported the issue before (https://github.com/huggingface/transformers/issues/3686).
Don't you think that we should open a simple Pull Request to fix this problem?

**Comment by TarasPriadka** [comment]
@AMR-KELEG I will post a PR to fix this issue.

**Comment by nbroad1881** [comment]
@TarasPriadka, @AMR-KELEG 

I had a similar issue using `preprocess.py` on an NER dataset.

```
Traceback (most recent call last):
  File "preprocess.py", line 12, in <module>
    max_len -= tokenizer.num_special_tokens_to_add()
AttributeError: 'BertTokenizer' object has no attribute 'num_special_tokens_to_add'
```

I think the PyPi file hasn't been updated, so `pip install transformers` won't have the files you need.  I built from source and the errors went away.  If you try building from source, I think your problem might go away too.

**Comment by AMR-KELEG** [comment]
> @TarasPriadka, @AMR-KELEG
> 
> I had a similar issue using `preprocess.py` on an NER dataset.
> 
> ```
> Traceback (most recent call last):
>   File "preprocess.py", line 12, in <module>
>     max_len -= tokenizer.num_special_tokens_to_add()
> AttributeError: 'BertTokenizer' object has no attribute 'num_special_tokens_to_add'
> ```
> 
> I think the PyPi file hasn't been updated, so `pip install transformers` won't have the files you need. I built from source and the errors went away. If you try building from source, I think your problem might go away too.

Well, I was using the source version but as said before, seems like the bug was there and got fixed in later commits.

**Comment by NielsRogge** [comment]
Same for me, only installing from source worked. Thank you @nbroad1881 . 

I am trying to reproduce the [NER fine-tuning example](https://github.com/huggingface/transformers/tree/master/examples/ner) in Google Colab. However, when running the preprocess.py file, I get empty train.txt, dev.txt and test.txt files. Am I doing something wrong here? Anyone can edit my Google Colab notebook: https://colab.research.google.com/drive/1IruNd9XtVOaZ1fxYssStuVhKoC6bhuHL#scrollTo=DXTtiNVroGES

It probably has something to do with the environment variables which are not properly set.
