### ISSUE TITLE
Aborted (core dumped) or Kernel dies

### ISSUE THREAD

**Issue by yashwatwani** [huggingface/transformers#3816]
Whenever I am trying to import tranfomers my kernel dies off in jupyter notebook .
tranformer version - 2.8.0
python version -3.7.7

**Comment by LysandreJik** [comment]
Do you mind showing us the lines that crash? Do you have a reproducible example?

**Comment by starplanet** [comment]
+1. @yashwatwani do you have resolved it? I have the same problem too.

If I install transformers 2.8.0, it will produce error:
```
[1]    11267 segmentation fault (core dumped)  PYTHONPATH=. python apps/absa/main.py
```

If I upgrade to the latest version 2.11.0, no error happens.
