### ISSUE TITLE
[readability] Consolidate prune_heads logic to PretrainedModel.

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#3825]
Many models have identical implementations of `prune_heads` it would be nice to store that implementation as a method on `PretrainedModel` and reduce the redundancy.

**Comment by noelmat** [comment]
Hi @sshleifer , 
I am new to opensource and would like to help out with this issue. Could you please point me to some guide to setting up the project locally.
Thanks.

**Comment by noelmat** [comment]
I got the contributing.md file. Thanks anyways. :)

**Comment by Shandilya21** [comment]
Hi @sshleifer 
I am looking for a contribution. Is the issue is still open?
Thanks and Regards

**Comment by noelmat** [comment]
@Shandilya21 It looks open. I was trying to work on it and got stuck at a point. Do let me know if you would like to discuss

**Comment by Shandilya21** [comment]
Hi @noelmat Okay, can you tell me where you got stuck? I am happy to discuss this.

**Comment by j-cahill** [comment]
Is anybody working on this? I'm new to open source but I'd like to give it a shot

**Comment by sshleifer** [comment]
Go for it!

**Comment by yugaljain1999** [comment]
> Is anybody working on this? I'm new to open source but I'd like to give it a shot

Yeah, I am in.. I also wanna work on this issue.
Issue is to implement `prune_heads` as a method in `PretrainedModel`

**Comment by ParseThis** [comment]
@yugaljain1999 made some progress on this?

**Comment by sshleifer** [comment]
I think this is done. Happy to find new bugs if anyone is on the hunt!
