### ISSUE TITLE
[readability] consolidate examples/summarization/bart  and examples/summarization/t5

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#3826]
This involves 

- [ ]  consolidating README.md 
- [ ]  consolidating evaluate_cnn.py scripts.
- [ ]  evaluate_wmt.py should also work
- [ ]  consolidating unittests
- [ ]  updating bash scripts
- [ ]  checking that consolidated stuff works, adding appropriate test coverage.

the resulting code should probably all be in `summarization/` with only a `bertabs/` subdirectory.

**Comment by aretius** [comment]
Hey @sshleifer !
I would like to work on the issue. It's my first issue so I appreciate any help!

**Comment by sshleifer** [comment]
Awesome, helpful command to get quick feedback on whether your change is working:

```bash
pytest --tb=short -p no:warnings examples/summarization/bart
```

Make sure you tag @sshleifer when you send a PR and I will give a careful review :)
