### ISSUE TITLE
i want help to create saved model(.pth) from Pytorch Dump(pytorch_model.bin) if possible!

### ISSUE THREAD

**Issue by pumpkinband** [huggingface/transformers#3834]
i have, PROJECT(folder)
                     ├── pytorch_model.bin
                     ├── bert_config.json
                     └── vocab.txt 

i tried saving it with 
`torch.save( pytorch_model.bin , PATH)` 

but came with error 
`-bash: syntax error near unexpected token `pytorch_model.bin,'`

what am i doing wrong ?
and please help me convert pretrained model to saved model( .pth)!!

**Comment by pumpkinband** [comment]
i used `transformers-cli convert` to make `python_model.bin` from checkpoints

**Comment by LysandreJik** [comment]
Did you try to put in in quotes? If you have a model you should do `torch.save(model.state_dict(), PATH)`.

Please take a look at the [PyTorch documentation](https://pytorch.org/tutorials/beginner/saving_loading_models.html). We prefer using `model.save_pretrained(PATH)`, however, as it saves the configuration object alongside it which is necessary when loading the model afterwards.
