### ISSUE TITLE
Cutom tokenizer not loaded in AutoTokenizer

### ISSUE THREAD

**Issue by muhammadfahid51** [huggingface/transformers#3838]
I am training a language model from scratch. I trained **ByteLevelBPETokenizer** and then when I am trying to load this tokenizer using **AutoTokenizer**, it is giving me the following error.

OSError: Model name './MyRobertaConfig/' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased). We assumed './MyRobertaConfig/' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.

I have not added tokenizer_config.json file in config directory, I don't think it should be an issue. Now do I need to migrate or transform my custom tokenizer to make it compatible with transformers tokenizers or what.

**Comment by singhay** [comment]
If it's a BPETokenizer, you can load it with `RobertaTokenizer.from_pretrained("vocab.json", "merges.json")`
