### ISSUE TITLE
Summarisation tuning

### ISSUE THREAD

**Issue by dimagalat** [huggingface/transformers#3865]
Hi everybody,

I’ve tried using BART summarisation code, and I had a question about finetune.py 

Can SummarisationTrainer checkpoint be loaded as a BartForConditionalGeneration model from the evaluation script?

**Comment by dimagalat** [comment]
Great, thanks @sshleifer

**Comment by sshleifer** [comment]
(Duplicate of https://github.com/huggingface/transformers/issues/3853)

**Comment by lukovnikov** [comment]
sorry, mentioned wrong issue
