### ISSUE TITLE
ImportError: cannot import name 'HfArgumentParser' from 'transformers'

### ISSUE THREAD

**Issue by ThomasSYT** [huggingface/transformers#3869]
Hi,
I installed tokenizers-0.5.2 transformers-2.8.0.
When I try to run run_bertology.py in the example dir calling it with

export TASK_NAME=mnli
python ./run_bertology.py     --data_dir $GLUE_DIR/$TASK_NAME     
                              --model_name bert-base-uncased     
                              --task_name $TASK_NAME        
                              --output_dir ./tmp/$TASK_NAME/     
                              --try_masking 

But it fails with
Traceback (most recent call last):
  File "run_bertology.py", line 33, in <module>
    from run_glue import ALL_MODELS, MODEL_CLASSES, load_and_cache_examples, set_seed
  File "/Users/thomas/PycharmProjects/transformers/examples/run_glue.py", line 34, in <module>
    from transformers import (
ImportError: cannot import name 'HfArgumentParser' from 'transformers' (/Users/thomas/opt/anaconda3/lib/python3.7/site-packages/transformers/__init__.py)

Please help, thanks.

**Comment by julien-c** [comment]
Hi, 

As mentioned [here](https://github.com/huggingface/transformers/tree/master/examples#examples) and in the main README you need to install from source in order to run the latest versions of the examples
