### ISSUE TITLE
bert summarizer module import error

### ISSUE THREAD

**Issue by eeegnu** [huggingface/transformers#3870]
# 🐛 
Running bert summarizer ([run_summarization.py](https://github.com/huggingface/transformers/blob/master/examples/summarization/bertabs/run_summarization.py)) gives the following error

```
Traceback (most recent call last):
  File "run_summarization.py", line 15, in <module>
    from .utils_summarization import (
ModuleNotFoundError: No module named '__main__.utils_summarization'; '__main__' is not a package
```

## Information

I've managed to fix this issue personally by changing "from .utils_summarization import" to "from utils_summarization import", though I don't know if this is due to a convention change in python module imports.

The problem arises when using:
* [x] the official example scripts: (give details below)

Running the following command yields the error
python3 run_summarization.py --documents_dir ".../bertabs/dataset/input" --summaries_output_dir ".../bertabs/dataset/output" --no_cuda false --batch_size 4 --min_length 50 --max_length 200 --beam_size 5 --alpha 0.95 --block_trigram true

## To reproduce

1.  Followed the steps here https://github.com/huggingface/transformers/blob/5b396457e5035a8b16ddee14b205c098598fe6bb/examples/summarization/bertabs/README.md
Though I skipped the 'Reproduce the authors' ROUGE score' section, that should not have any effect on usage for different inputs.
2. Created custom data paths for testing a single input article.
3. Run the command given above.

```
Traceback (most recent call last):
  File "run_summarization.py", line 15, in <module>
    from .utils_summarization import (
ModuleNotFoundError: No module named '__main__.utils_summarization'; '__main__' is not a package
```

## Expected behavior

It should import the module utils_summarization

## Environment info

     
- `transformers` version: 2.8.0
- Platform: Linux-4.15.0-74-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by AppishettySHIVASAI** [comment]
HELLO eeegnu, I'm also facing the same issue.
![issue](https://user-images.githubusercontent.com/54736174/79893382-9f529c80-8421-11ea-9967-f3e64dacd9a3.png)
**Environment Info :**
Platform: Windows 10  64bit
Python version: 3.6.10
PyTorch version (GPU?): 1.4.0 
Tensorflow version (GPU?): not installed (NA)

**Comment by Nol01** [comment]
Hi!
Change: from .utils_summarization import (
    CNNDMDataset,
    build_mask,
    compute_token_type_ids,
    encode_for_summarization,
    truncate_or_pad,
)
To: from utils_summarization import (
    CNNDMDataset,
    build_mask,
    compute_token_type_ids,
    encode_for_summarization,
    truncate_or_pad,
)
