### ISSUE TITLE
T5 Translation Error 

### ISSUE THREAD

**Issue by liesun1994** [huggingface/transformers#3875]
# 🐛 Bug

## Information
 
Model I am using (T5-base):

Language I am using the model on (T5-base):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

```
from transformers import T5Tokenizer, T5ForConditionalGeneration
tokenizer = T5Tokenizer.from_pretrained('t5-base')
model = T5ForConditionalGeneration.from_pretrained('t5-base')
data="translate English to German: Hello, my dog is cute"
input_ids = tokenizer.encode(data, return_tensors="pt")  # Batch size 1
outputs = model.generate(input_ids, decoder_start_token_id = tokenizer.eos_token_id)
print(outputs)
```

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. pip install transformers 
2. run the code mentioned above, which always produces  tensor([[1, 1]])

## Environment info

     
- `transformers` version: 2.8.0
- Platform: linux 
- Python version: python3.6
- PyTorch version (GPU?): torch 1.2.0 , with GPU
- Tensorflow version (GPU?): p40
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
Why do you use `decoder_start_token_id = tokenizer.eos_token_id` ? Is that stated in the examples somewhere? 

If you do:
```
from transformers import T5Tokenizer, T5ForConditionalGeneration
tokenizer = T5Tokenizer.from_pretrained('t5-base')
model = T5ForConditionalGeneration.from_pretrained('t5-base')
data="translate English to German: Hello, my dog is cute"
input_ids = tokenizer.encode(data, return_tensors="pt")  # Batch size 1
outputs = model.generate(input_ids, decoder_start_token_id = tokenizer.eos_token_id)
print(tokenizer.decode(outputs[0]))
```

The translation is correct. Also I recommend using the translation pipeline. This way T5 uses better generation paramaters.

**Comment by liesun1994** [comment]
@patrickvonplaten Thanks a lot !  I used previous configuration file  from https://s3.amazonaws.com/models.huggingface.co/bert/t5-base-config.json ;  After using the new configuration file,  translation error is gone ! 
My code is :  
```from transformers import T5Tokenizer, T5ForConditionalGeneration
tokenizer = T5Tokenizer.from_pretrained('t5-base')
model = T5ForConditionalGeneration.from_pretrained('t5-base')
data="translate English to German: Hello, my dog is cute"
input_ids = tokenizer.encode(data, return_tensors="pt")  # Batch size 1
outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))
