### ISSUE TITLE
How to reduce random summary generation of BART Summarization models?

### ISSUE THREAD

**Issue by aliasneo1** [huggingface/transformers#3876]
Currently BART model trained on CNN dataset is generating summaries which consist of new nouns which are not present in the input text.
How to control the randomness of these summaries. Is there any parameter like temperature in GPT-2 model which can control the degree to which the model can go off-topic?

**Comment by pyfisch** [comment]
BART is used as a model for abstractive summarization so it can use different words than those used in the original text. But it should not go *off-topic*. You could use an extractive summarization model instead which does not generate new nouns. Also you might be interested in the methods from [*Controlling the Amount of Verbatim Copying in Abstractive Summarization*](https://arxiv.org/pdf/1911.10390.pdf) to control the degree of change in the summaries.
