### ISSUE TITLE
ImportError: cannot import name 'MODEL_CLASSES' from 'run_glue' 

### ISSUE THREAD

**Issue by ThomasSYT** [huggingface/transformers#3877]
# 🐛 Bug

## Information
I try to run the latest versions of the examples and got the error message(I have installed the main README mentioned procedure from source):

Traceback (most recent call last):
  File "run_bertology.py", line 33, in <module>
    from run_glue import ALL_MODELS, MODEL_CLASSES, load_and_cache_examples, set_seed
ImportError: cannot import name 'MODEL_CLASSES' from 'run_glue' (/home/stud-yantao/Transformer/transformers/examples/run_glue.py)

Model I am using (Bert, XLNet ...): Bert

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts: (give details below)
run_bertology.py

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name) 
MNLI

## To reproduce

export TASK_NAME=mnli
python ./run_bertology.py --data_dir $GLUE_DIR/$TASK_NAME
--model_name bert-base-uncased
--task_name $TASK_NAME
--output_dir ./tmp/$TASK_NAME/
--try_masking

Traceback (most recent call last):
  File "run_bertology.py", line 33, in <module>
    from run_glue import ALL_MODELS, MODEL_CLASSES, load_and_cache_examples, set_seed
ImportError: cannot import name 'MODEL_CLASSES' from 'run_glue' (/home/stud-yantao/Transformer/transformers/examples/run_glue.py)

## Environment info

     
- `transformers` version: 2.8.0
- Platform:
- Python version:3.7
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:yes
- Using distributed or parallel set-up in script?:

**Comment by julien-c** [comment]
Should be fixed on master, please share if it does/your results
