### ISSUE TITLE
When will ELECTRA pretraining from  scratch will be available?

### ISSUE THREAD

**Issue by 008karan** [huggingface/transformers#3878]
# ❓ Questions & Help

## Details

Is pre training from scratch for electra available? couldnt find it. 
Thanks!

**Comment by LysandreJik** [comment]
Working on it as we speak :).

**Comment by Frozenwords** [comment]
@LysandreJik do you think the update will be available by the end of the month ? Maybe it has been postponed due to the recent addition of the Trainer and the refactor of the language_modeling script ?

**Comment by LysandreJik** [comment]
It has been postponed a bit due to the recent addition of the Trainer and the TPU work on it, but I definitely aim to have it out earlier than by the end of the month :)

**Comment by 008karan** [comment]
Was looking for Albert pre-training from scratch but I think there is support for Bert, Roberta and distillbert only as of now. 
@LysandreJik can you guide how can I do Albert pretraining from scratch?

**Comment by makeshn** [comment]
@LysandreJik Is the code for pretraining Electra from scratch available now?

**Comment by seyonechithrananda** [comment]
Are there any updates to this, or plans to release the ELECTRA pre-training from scratch feature soon?

**Comment by Mazzza** [comment]
Hello. 
Are there any updates?

**Comment by lucaguarro** [comment]
Curious as well.

**Comment by LysandreJik** [comment]
The development of the ELECTRA pretraining from scratch is in a stale state with no plans to work on it further, see https://github.com/huggingface/transformers/pull/4656#issuecomment-711082850

See https://discuss.huggingface.co/t/electra-training-reimplementation-and-discussion/1004 by @richarddwang for a PyTorch implementation of the ELECTRA pretraining.
