### ISSUE TITLE
Replace `config.output_attentions` parameter with function argument `output_attentions`

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#3880]
# 🚀 Feature request

Currently the user has to decide whether the model should output the attentions when she/he creates the config of a model: config.output_attentions = True/False. It would be nice if the user can decide this when calling the models `forward()` / `call()` with a flag `output_attentions`. This should be done for all TF and PT models that can output attentions.

A very similar recent change was done for the variable `config.output_past` -> see PR:#3734

## Motivation

The user has more flexibility when the hidden states should be output or not.

## Your contribution

If someone feels like contributing to the library, this would be a great first PR. I'm very happy to guide the contributor through the PR!

**Comment by prashant616** [comment]
Hi, I would like work on this issue.

**Comment by patrickvonplaten** [comment]
That's great :-) Do you want to open a PR and do the changes analogous to PR: #3734 ?

**Comment by drjosephliu** [comment]
Is this still be worked on? If not, I'd be happy to make a first contribution here

**Comment by patrickvonplaten** [comment]
First PR first serve ;-) Still an open issue

**Comment by drjosephliu** [comment]
Any tips on how I should proceed? I was thinking of following the changes made for `config.output_past` (01c37dc), but for `config.output_attentions` instead.

**Comment by Bharat123rox** [comment]
Oh sorry @drjosephliu didn't notice the comment as I was working on it earlier today, my apologies 😞
