### ISSUE TITLE
Allow one to return encoder attentions in seq2seq generation

### ISSUE THREAD

**Issue by aced125** [huggingface/transformers#3891]
# 🚀 Feature request

Please could we have the ability to return attention weights from the decoded generated tokens to the encoded source?

## Motivation

To attribute the decoded text. E.g in the summarization task we want to see where the decoder was paying attention to in the source.

## Your contribution

May be able to look into a PR but stretched for time at the minute.

FairSeq has implemented this capability I believe.

**Comment by patrickvonplaten** [comment]
Hi @aced125, I agree that this functionality should be provided :-) 

I think in the PR, one has to include a `output_attention` argument to the `generate()` function and then make sure that the output idx are correct! 
Before starting this PR, this PR should probably be solved before: https://github.com/huggingface/transformers/issues/3880

**Comment by patrickvonplaten** [comment]
want to take a look at this soon

**Comment by patrickvonplaten** [comment]
#6735 is a first step to allow for this feature
