### ISSUE TITLE
How to fine-tune DialoGPT with your own data?

### ISSUE THREAD

**Issue by avinregmi** [huggingface/transformers#3897]
# 🚀 How to fine-tune DialoGPT with your own data?

## Motivation

I really liked the new DialoGPT that allows to make chatbots, but how do i fine-tune this for own dataset?

**Comment by patrickvonplaten** [comment]
DialoGPT is fine-tuned in the same way GPT2 in fine-tuned. Please take a look at the paper: 
https://arxiv.org/pdf/1911.00536.pdf . 

I will also add some training tips to the doc string.
