### ISSUE TITLE
How to only use part of pretrained model 

### ISSUE THREAD

**Issue by abhyuday3jagannatha** [huggingface/transformers#3901]
Hi
I am using BERT for classification, I have a pretrained model, and my question is when I load the model like this:

  model = model_class.from_pretrained(
        args.model_name_or_path,
        from_tf=bool(".ckpt" in args.model_name_or_path),
        config=config,
        cache_dir=args.cache_dir if args.cache_dir else None,
    )

How can I not load the classifier, and only load the BERT encoder.
thanks

**Comment by LysandreJik** [comment]
How did you obtain your pre-trained model? Does your pre-train model have a classification head? What is `model_class`? Is it `BertForSequenceClassification`?
