### ISSUE TITLE
New run_language_modeling.py does not save vocab.txt and tokenizer_config.json

### ISSUE THREAD

**Issue by questpavan** [huggingface/transformers#3921]
# 🐛 Bug
Hi, 

While running new  run_language_modeling.py, at the end it only saves pytorch model and config.json and training arguments
Unlike before it also used to store vocab.txt and tokenizer_config.json

 I am not using any custom tokenizer, only using tokenizer provided by the model.

## Command Details I used

python run_language_modeling.py 
--output_dir=bert-base-uncased-4 
--overwrite_output_dir 
--model_type=bert 
--model_name_or_path="bert-base-uncased" 
--do_train --train_data_file="./test.txt" 
--per_gpu_train_batch_size 3 
--mlm 
--num_train_epochs 1

Model I am using (Bert, XLNet ...):
Bert-base-uncased 

Language I am using the model on (English, Chinese ...):
Engilsh

## Expected behavior
It should also save vocab.txt and tokenizer_config.json

**Comment by julien-c** [comment]
Yes, you would now need to do it manually by calling `tokenizer.save_pretrained(training_args.output_dir)`

I'll keep this issue open to see if many people ask for it (we can re-add if it's the case). cc @LysandreJik

**Comment by ratthachat** [comment]
I think if an extra step is needed, it should say it in the guideline ;) 
So perhaps auto save would be better.

**Comment by julien-c** [comment]
Ok, I will re-add it by default

**Comment by PhilipMay** [comment]
> 
> 
> Yes, you would now need to do it manually by calling `tokenizer.save_pretrained(training_args.output_dir)`
> 
> I'll keep this issue open to see if many people ask for it (we can re-add if it's the case). cc @LysandreJik

the correct call is: `tokenizer.save_model`
