### ISSUE TITLE
LineByLineTextDataset limits the total number of examples to 50000 documents

### ISSUE THREAD

**Issue by questpavan** [huggingface/transformers#3922]
# ❓ Questions & Help

## Details

Hi,

While running run_language_modeling.py with argument --line_by_line, found out that it only takes first 50000 documents.

https://github.com/huggingface/transformers/blob/cb3c2212c79d7ff0a4a4e84c3db48371ecc1c15d/src/transformers/data/datasets/language_modeling.py#L93

Please confirm is this a bug or intended behavior?

**Comment by julien-c** [comment]
It's a bug. Do you want to submit a PR to remove?

**Comment by questpavan** [comment]
Yes that would be great

**Comment by julien-c** [comment]
Closed by #3926
