### ISSUE TITLE
Using the default trainer args

### ISSUE THREAD

**Issue by williamFalcon** [huggingface/transformers#3925]
Hey guys!

Just looked through the transformer_base... why not also allow any of the trainer args to be used?

I imagine the best set up for you guys is:
- add default trainer args (since people can look into the lightning docs for details on this)
- add hf specific args (nlp related or whatever you guys need)
- add model specific args

But instead it looks like you only use a subset of the args
https://github.com/huggingface/transformers/blob/dd9d483d03962fea127f59661f3ae6156e7a91d2/examples/transformer_base.py#L275

Something like this should work:
```python
parser = ArgumentParser()

# enable all trainer args
parser = Trainer.add_argparse_args(parser)

# add the HF args
parser.add_argument(--some_hf_specific_thing, ...)

# add the model args
parser = GoodGAN.add_model_specific_args(parser)

# cook them all up :)
args = parser.parse_args()
```

Check here for mode details:
https://pytorch-lightning.readthedocs.io/en/stable/hyperparameters.html#multiple-lightning-modules

@srush @nateraw

**Comment by srush** [comment]
This sounds good. We originally were trying to reimplement exactly the other examples. But now we can have the lightning examples support a wider range of options.

**Comment by nateraw** [comment]
@srush I can take care of this when I go to work on #4494 if that's alright with you.
