### ISSUE TITLE
How can i finetune an encode-decoder combination?

### ISSUE THREAD

**Issue by Palipoor** [huggingface/transformers#3930]
Hi, I want to finetune an encode-decoder model to train on a parallel dataset(something like translation) and I'm not sure what should I do. I read [this](https://medium.com/huggingface/encoder-decoders-in-transformers-a-hybrid-pre-trained-architecture-for-seq2seq-af4d7bf14bb8) blog post but It didn't help. It doesn't really matter for me which encode or decoder I choose, I just need the power of a pre-trained transformer.

**Comment by Palipoor** [comment]
Well I found the summarization example, I'm going to read it and I'll close this issue if it helps. Would still be happy if you can help.

**Comment by murugeshmanthiramoorthi** [comment]
@Palipoor Can you please share the summarization example. I am looking for one.

**Comment by Palipoor** [comment]
> @Palipoor Can you please share the summarization example. I am looking for one.

Here it is:
https://github.com/huggingface/transformers/tree/master/examples/summarization

Although it didn't help me and I'm trying to finetune a T5.
