### ISSUE TITLE
ImportError: cannot import name 'DefaultDataCollator'

### ISSUE THREAD

**Issue by shngt** [huggingface/transformers#3946]
# 🐛 Bug

## Information

Using "from transformers import DefaultDataCollator" raises an ImportError on my system. Unsure if this is really a bug or if I'm doing something stupid. Any help would be appreciated.

Model I am using (Bert, XLNet ...): N/A

Language I am using the model on (English, Chinese ...): N/A

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. from transformers import DefaultDataCollator
2.
3.

## Expected behavior

For the import to go through cleanly.

## Environment info

     
- `transformers` version: 2.8.0
- Platform: Ubuntu 18.04
- Python version: 3.6.9 
- PyTorch version (GPU?): 1.5.0, No
- Tensorflow version (GPU?): -
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: -

**Comment by Joppewouts** [comment]
Try reinstalling using 
```pip install git+https://github.com/huggingface/transformers```

**Comment by shngt** [comment]
That didn't work, sorry

**Comment by julien-c** [comment]
Try uninstalling before or starting again from a clean venv

**Comment by ganik** [comment]
Have the same issue, did force install; uninstall & install, same problem. If I even search the https://github.com/huggingface/transformers repo I dont see any DefaultDataCollator definitions.

**Comment by ganik** [comment]
It looks like this PR https://github.com/huggingface/transformers/pull/5015 removed DefaultDataCollator ....

**Comment by Jadiker** [comment]
[This HuggingFace Tutorial](https://colab.research.google.com/github/huggingface/notebooks/blob/master/course/chapter7/section3_tf.ipynb) has this error.

**Comment by Jadiker** [comment]
It looks like the way to fix this is to now use `from transformers.data.data_collator import tf_default_data_collator`. Is there any way to update this in the tutorial?

**Comment by snowith** [comment]
I got an ImportError using `from transformers.data.data_collator import tf_default_data_collator`.
To me, the problem seems to happen only when TPUs are turned on. 
When I try to run on CPU or GPU, I can access and use `DefaultDataCollator` without any problem, but TPUs always run to this error.

**Comment by ImmortalZ** [comment]
you can open transformers/data/data_collator.py，you can find  'tf_default_data_collator' is not exsit，then you can find function 'default_data_collator'

so you can replace by this code:

```python
from transformers.data.data_collator import default_data_collator
```
