### ISSUE TITLE
AttributeError: 'LambdaLR' object has no attribute 'get_last_lr'

### ISSUE THREAD

**Issue by wasiahmad** [huggingface/transformers#3959]
I am trying to run the summarization example using BART and getting the following error.

```
tqdm_dict = {"loss": "{:.3f}".format(avg_loss), "lr": self.lr_scheduler.get_last_lr()[-1]}
AttributeError: 'LambdaLR' object has no attribute 'get_last_lr'
```

The error occurred at this [line](https://github.com/huggingface/transformers/blob/master/examples/transformer_base.py#L101). I am using PyTorch 1.3.

**Comment by 944721805** [comment]
I encountered the same problem, have you solved it？

**Comment by stefan-it** [comment]
Upgrading to PyTorch 1.4 would solve that issue :)

**Comment by 944721805** [comment]
> Upgrading to PyTorch 1.4 would solve that issue :)
> 
> Current `master` branch recommends that:
> 
> https://github.com/huggingface/transformers/blob/4e817ff41885063e08bb3bcd63e5adfd835b9911/setup.py#L70

**Comment by 944721805** [comment]
Thank you so much, I have solved it.

**Comment by youkaichao** [comment]
`get_last_lr` is introduced in pytorch 1.4.0 . Maybe you need to upgrade your pytorch.

**Comment by julien-c** [comment]
If you really are stuck with PyTorch <= 1.3 please feel free to open a PR to fix this with backward compatibility

**Comment by bing0037** [comment]
I upgraded pytorch to v1.5.0, but run_glue.py with Bert model failed. So, you may have to set it to 1.4.0
