### ISSUE TITLE
Question regarding glue examples

### ISSUE THREAD

**Issue by Mahmedturk** [huggingface/transformers#3960]
hi,

I have used the run_glue.py for QQP dataset and the tested the saved model for a small test set. I get really high F1-score on dev set but get lower F1-score on the test set. My question is that, is the dev set used in glue examples is used to set parameters or is it a held out set?

**Comment by julien-c** [comment]
I don't understand the question. The labels for the test sets for GLUE are privately-held, if that's what you're asking.

(Closing this as it's not really specific to this repo)
