### ISSUE TITLE
There are some warnings when I used AdamW and pytorch1.5.

### ISSUE THREAD

**Issue by illcat** [huggingface/transformers#3961]
# 🐛 Bug

## Information
pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of add_ is deprecated:
        add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
        add_(Tensor other, *, Number alpha)

**Comment by oganonuevo** [comment]
same here

**Comment by pommedeterresautee** [comment]
This is not a bug but because pytorch 1.5 displays warnings that it didn't displayed before.

**Comment by xwang233** [comment]
It may be this file https://github.com/huggingface/transformers/blob/master/src/transformers/optimization.py#L96

You can modify the code on those `add`, `addcdiv`, `addcmul` and use `alpha` or `value` keyword argument to eliminate these warnings. (or maybe submit a PR if that works!)

See pytorch doc: https://pytorch.org/docs/stable/torch.html#torch.add

pytorch/pytorch#32861

**Comment by vibhavagarwal5** [comment]
Hi is anyone submitting any PR for this issue?
