### ISSUE TITLE
Problem with downloading the XLNetSequenceClassification pretrained xlnet-large-cased

### ISSUE THREAD

**Issue by tienpham-dtp** [huggingface/transformers#3971]
I've run this before and it was fine. However, this time, i keep encountering this runtime error. In fact, when i tried to initialize model = XLNetModel.from_pretrained('xlnet-large-cased') - it also gives me the 'negative dimension' error.

`model = XLNetForSequenceClassification.from_pretrained("xlnet-large-cased", num_labels = 2)
model.to(device)`
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-37-d6f698a3714b> in <module>()
----> 1 model = XLNetForSequenceClassification.from_pretrained("xlnet-large-cased", num_labels = 2)
      2 model.to(device)

3 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py in __init__(self, num_embeddings, embedding_dim, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse, _weight)
     95         self.scale_grad_by_freq = scale_grad_by_freq
     96         if _weight is None:
---> 97             self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
     98             self.reset_parameters()
     99         else:

RuntimeError: Trying to create tensor with negative dimension -1: [-1, 1024]`

**Comment by Envgel** [comment]
Hey mate, I've encountered the same issue. How did you solve it?

**Comment by justkj7** [comment]
I encounter this issue. How can I solve this?

**Comment by tienpham-dtp** [comment]
the problem is when l import xlnet from pytorch_transformers. instead, you should be importing it from the module called 'transformers'
