### ISSUE TITLE
Weights from pretrained model not used in GPT2LMHeadModel

### ISSUE THREAD

**Issue by ankit-chadha** [huggingface/transformers#3974]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): gpt2

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

1. trained gpt2 using run_language_modeling
2. using run_generation.py

`backend_1        | 04/25/2020 18:37:27 - INFO - transformers.modeling_utils -   Weights from pretrained model not u
sed in GPT2LMHeadModel: ['transformer.h.0.attn.masked_bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.2.a
ttn.masked_bias', 'transformer.h.3.attn.masked_bias', 'transformer.h.4.attn.masked_bias', 'transformer.h.5.attn.mas
ked_bias', 'transformer.h.6.attn.masked_bias', 'transformer.h.7.attn.masked_bias', 'transformer.h.8.attn.masked_bia
s', 'transformer.h.9.attn.masked_bias', 'transformer.h.10.attn.masked_bias', 'transformer.h.11.attn.masked_bias']`

**Comment by ankit-chadha** [comment]
@patrickvonplaten - could you help elaborate on this?

**Comment by patrickvonplaten** [comment]
Yeah, we need to clean this logging. The weights are correctly loaded into the model as far as I know (we have integration tests for pretrained GPT2 models so the weights have to be correctly loaded). Just need to clean up the logging logic there.

**Comment by patrickvonplaten** [comment]
Actually this logging info is fine. Those masked bias are saved values using the `register_buffer()` method and don't need to be loaded.
