### ISSUE TITLE
Run Multiple Choice failure with ImportError: cannot import name 'AutoModelForMultipleChoice'

### ISSUE THREAD

**Issue by leixiaofeng-astar** [huggingface/transformers#3986]
# 🐛 Bug

## Information
Run the example, it returns error as below. The version in April 17 doesn't have the problem.
python ./examples/run_multiple_choice.py \
> --task_name swag \
> --model_name_or_path roberta-base \
> --do_train \
> --do_eval \
> --data_dir $SWAG_DIR \
> --learning_rate 5e-5 \
> --num_train_epochs 3 \
> --max_seq_length 80 \
> --output_dir models_bert/swag_base \
> --per_gpu_eval_batch_size=16 \
> --per_gpu_train_batch_size=16 \
> --gradient_accumulation_steps 2 \
> --overwrite_output
Traceback (most recent call last):
  File "./examples/run_multiple_choice.py", line 26, in <module>
    from transformers import (
ImportError: cannot import name 'AutoModelForMultipleChoice'

Model I am using (Bert, XLNet ...):

Language I am using the model on (English, Chinese ...):English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

Follow the exact steps in README.md
1. Download the transformer with git clone
2. git clone https://github.com/rowanz/swagaf.git
3. export SWAG_DIR=/path/to/swag_data_dir
python ./examples/run_multiple_choice.py \
--task_name swag \
--model_name_or_path roberta-base \
--do_train \
--do_eval \
--data_dir $SWAG_DIR \
--learning_rate 5e-5 \
--num_train_epochs 3 \
--max_seq_length 80 \
--output_dir models_bert/swag_base \
--per_gpu_eval_batch_size=16 \
--per_gpu_train_batch_size=16 \
--gradient_accumulation_steps 2 \
--overwrite_output

## Expected behavior
***** Eval results *****
eval_acc = 0.8338998300509847
eval_loss = 0.44457291918821606

## Environment info

     
- `transformers` version:
- Platform: ubuntu 18.04
- Python version: 3.6.8
- PyTorch version (GPU?): 1.4.0 GPU
- Tensorflow version (GPU?):
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No.

**Comment by julien-c** [comment]
You need to install transformers from source as specified in the README
