### ISSUE TITLE
Language generation not possible with roberta?

### ISSUE THREAD

**Issue by ysig** [huggingface/transformers#3990]
Hi,

I have a small question.
I finetuned a roberta model and then I was about to do generation and I understood this was not possible on my model, but only in a smaller collection of model, where most of them are quite huge.
Why is that? Is there another way to generate language with roberta?

Thanks in a advance!

PS: the scripts I used were: `run_language_modeling.py` and `run_generation.py`

**Comment by patrickvonplaten** [comment]
`Roberta` has not really been trained on generating text. Small models that work well for generation are `distilgpt2` and `gpt2` for example.
