### ISSUE TITLE
How do I convert T5 checkpoint to pytorch bin to utilize fine-tuned model from finetune.py?

### ISSUE THREAD

**Issue by enzoampil** [huggingface/transformers#3999]
# ❓ Questions & Help

I've recently tried to fine-tune T5 using bart's [finetune.py](https://github.com/huggingface/transformers/blob/master/examples/summarization/bart/finetune.py) (supports T5 fine-tuning as well). The model is saved in a `ckpt` format when I wanted it as a pytorch `bin`, so I found this [page](https://huggingface.co/transformers/converting_tensorflow_models.html) in the docs on how to convert `ckpt` to `bin`. However, I don't see the T5 model in this page. 

Is it possible to use the CLI to convert T5 models?

I also have questions around fine-tuning T5 but will discuss details in a separate issue.

**Comment by patrickvonplaten** [comment]
Sorry to answer this late - can you try the following:
```python
model.from_pretrained(<path_to_model.ckpt>, from_tf=True) #even though you don't use TF
model.save_pretrained("./") # should be in .bin format
```

If this does not work try the following:
```python 
parser = argparse.ArgumentParser()
add_generic_args(parser, os.getcwd())
parser = SummarizationTrainer.add_model_specific_args(parser, os.getcwd())
args = parser.parse_args()
model = SummarizationTrainer(args)
model = model.load_from_checkpoint(<path_to_your_checkpoint>)
model.model.save_pretrained("./") # should be in bin format
```

Please do let me know if this works.

**Comment by patrickvonplaten** [comment]
Actually someone else found a much better solution than I did :-) 
See: https://github.com/huggingface/transformers/issues/4144

**Comment by enzoampil** [comment]
Awesome this worked! Thanks so much @patrickvonplaten
