### ISSUE TITLE
GPT2LMHeadModel Documentation Mismatch for labels

### ISSUE THREAD

**Issue by cdpierse** [huggingface/transformers#4047]
# 🐛 Bug

## Information

This is a very small discrepancy between the docs and code for the `GPT2LMHeadModel`. 

Docs mention setting `lm_labels = input_ids`  https://github.com/huggingface/transformers/blob/520e7f211926e07b2059bc8e21b668db4372e4db/src/transformers/modeling_gpt2.py#L547-L552

Should this read `labels = input_ids` instead ?
Since this is the single LM Model head it only has one `labels` param unlike the double head model?

**Comment by bajajahsaas** [comment]
I guess you are right. The same is true for transformer-xl as well. 
Code: https://github.com/bajajahsaas/transformers/blob/master/src/transformers/modeling_transfo_xl.py#L855

**Comment by patrickvonplaten** [comment]
Yes, I think you guys are right! Thanks for pointing this out. I think we should do a general name cleaning here. 

See linked PR.

**Comment by sgugger** [comment]
This was fixed by #4711
