### ISSUE TITLE
No CORS Policy for Write With Transformer Endpoints

### ISSUE THREAD

**Issue by ivokun** [huggingface/transformers#4070]
# 🐛 Bug

## Information
Write with Transformer is a very good place for trying available models. But, there is no CORS policy to secure it. This could potentially be used by an unauthorized third-parties or attackers to DDoS.

## To reproduce

POST request to `/autocomplete/distilgpt2/small`
```
curl -d '{"context":"See how a modern neural network auto-completes your text 🤗","model_size":"distilgpt2/small","top_p":0.9,"temperature":1,"max_time":1}' -H 'Content-Type: application/json' https://transformer.huggingface.co/autocomplete/distilgpt2/small
```
Potential endpoints:
1. `/autocomplete/distilgpt2/small`
1. `/autocomplete/gpt2/small`
1. `/autocomplete/gpt2/medium`
1. `/autocomplete/gpt2/large`
1. `/autocomplete/gpt2/xl` <- 504 error
1. `/autocomplete/pplm` <- 504 error

## Expected behavior

The endpoints could be used by unauthorized third-parties and risk of DDoS .

**Comment by julien-c** [comment]
Hi @ivokun – this was actually on purpose as someone was using it as an API

We'll secure it down the line if it gets abused.
