### ISSUE TITLE
Issue with non-text files and bertabs example

### ISSUE THREAD

**Issue by db1981** [huggingface/transformers#4074]
Hello team,
I've been running the bertabs example on some plain txt files using the latest version available from the repository (pulled on 4/28/2020). 

The folder where I placed the txt files for processing contains the configuration file automatically generated by the filesystem (".DS_store", as I'm running macos, but I suspect Windows would have similar issues). 

Because the configuration file is binary, the following piece of code in util_summarization.py (lines 56-59) fails with a UnicodeDecodeError exception:

with open(document_path, encoding="utf-8") as source:
   raw_story = source.read()
   story_lines, summary_lines = process_story(raw_story)
return document_name, story_lines, summary_lines

I added a "try ... except" block to handle the UnicodeDecodeError exception and return an empty raw_story string if the exception is raised. This fixed the issue for me.

**Comment by patrickvonplaten** [comment]
So the issue is fixed for you then?
