### ISSUE TITLE
How to using vocab other language in run_ner.py?

### ISSUE THREAD

**Issue by TorRient** [huggingface/transformers#4075]
Help me, thank you!!!

**Comment by ivokun** [comment]
Which language do you want to use?
You can load model that pretrained with certain language or you can use mBERT / XLM instead.

**Comment by TorRient** [comment]
> Which language do you want to use?
> You can load a model that pre-trained with a certain language or you can use mBERT / XLM instead.

Thank for reply
i want to use BERT for Vietnamese language

**Comment by ivokun** [comment]
Unfortunately, there is no BERT for Vietnamese available for now.
You will have to wait for somebody to pre-trained the Vietnamese model or you can use Multilingual-BERT (mBERT) instead:
```bert-base-multilingual-cased``` or ```bert-base-multilingual-uncased```

These models were pre-trained with [top 100 languages in Wikipedia](https://meta.wikimedia.org/wiki/List_of_Wikipedias).
