### ISSUE TITLE
Using 'ner' task in pipeline with a non default model gives me entities as "LABEL-6" , "LABEL-8"  instead of "I-ORG" and "I-LOC"

### ISSUE THREAD

**Issue by goutham794** [huggingface/transformers#4078]
model - dbmdz/bert-base-cased-finetuned-conll03-english

Language - english

The problem arises when using:
* [x] my own modified scripts

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: ner

## To reproduce
```
tokenizer = AutoTokenizer.from_pretrained("dbmdz/bert-base-cased-finetuned-conll03-english")
model = AutoModelForTokenClassification.from_pretrained("dbmdz/bert-base-cased-finetuned-conll03-english")
ner_task = pipeline(task='ner', model=model, tokenizer=tokenizer)
ner_task('Hugging Face is a French company based in New-York.')
```

**Comment by stefan-it** [comment]
Oh no, there's something wrong with the label alignment (can also be seen in the `config.json`):

```json
"id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5",
    "6": "LABEL_6",
    "7": "LABEL_7",
    "8": "LABEL_8"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "LABEL_5": 5,
    "LABEL_6": 6,
    "LABEL_7": 7,
    "LABEL_8": 8
  },
```

Thanks for reporting, I'll try to fix it :)

**Comment by goutham794** [comment]
Also I forgot to add, I see the [CLS], [SEP] tokens and also words like "is" , "a" in the NER results which are not present when I use the default dbmdz/bert-large-cased-finetuned-conll03-english.

**Comment by goutham794** [comment]
https://s3.amazonaws.com/models.huggingface.co/bert/dbmdz/bert-base-cased-finetuned-conll03-english/config.json
This file needs fixing.

**Comment by next-manuelmartin5** [comment]
I'm having the same problem with the model: dbmdz/bert-base-multilingual-cased-finetuned-conll03-spanish

**Comment by goutham794** [comment]
> I'm having the same problem with the model: dbmdz/bert-base-multilingual-cased-finetuned-conll03-spanish

One fix is to download the model and config.json to your local and then just manually edit the "config.json" file.
This is what it should actually look like :- 
https://s3.amazonaws.com/models.huggingface.co/bert/dbmdz/bert-large-cased-finetuned-conll03-english/config.json
