### ISSUE TITLE
tokenizer.encode_plus stopped returning `attention_mask`

### ISSUE THREAD

**Issue by wasiahmad** [huggingface/transformers#4080]
I have a codebase which was working fine but today when I was trying to run, I observed that `tokenizer.encode_plus` stopped returning `attention_mask`. Is it removed in the latest release? Or, I need to do something?

The following piece of code was working for me.

```
encoded_dict = tokenizer.encode_plus(
                truncated_query,
                span_doc_tokens,
                max_length=max_seq_length,
                return_overflowing_tokens=True,
                pad_to_max_length=True,
                stride=max_seq_length - doc_stride - len(truncated_query) - sequence_pair_added_tokens,
                truncation_strategy="only_second",
                return_token_type_ids=True,
                return_attention_mask=True
            )
```

But now, I get only `dict_keys(['input_ids', 'token_type_ids'])` from `encode_plus`. Also, I realized that the returned `input_ids` are not padded to `max_length`.

**Comment by shikharsingla** [comment]
How did you resolve this? I am facing this issue as well.

**Comment by LysandreJik** [comment]
@shikharsingla, what is your exact bug? Which tokenizer are you using, with which code?

**Comment by LysandreJik** [comment]
Just saw your issue https://github.com/huggingface/transformers/issues/4868, looking into it.
