### ISSUE TITLE
Use roberta-med or scibert for fillmask

### ISSUE THREAD

**Issue by tuhinjubcse** [huggingface/transformers#4085]
Hi
I have been trying to use roberta-med for  fillmask
`
nlp = pipeline("fill-mask", model="allenai/biomed_roberta_base", tokenizer="allenai/biomed_roberta_base")`

However , I get this
**Model name 'allenai/biomed_roberta_base' was not found in model name list** (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-japanese, bert-base-japanese-whole-word-masking, bert-base-japanese-char, bert-base-japanese-char-whole-word-masking, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased, openai-gpt, transfo-xl-wt103, gpt2, gpt2-medium, gpt2-large, gpt2-xl, distilgpt2, ctrl, xlnet-base-cased, xlnet-large-cased, xlm-mlm-en-2048, xlm-mlm-ende-1024, xlm-mlm-enfr-1024, xlm-mlm-enro-1024, xlm-mlm-tlm-xnli15-1024, xlm-mlm-xnli15-1024, xlm-clm-enfr-1024, xlm-clm-ende-1024, xlm-mlm-17-1280, xlm-mlm-100-1280, roberta-base, roberta-large, roberta-large-mnli, distilroberta-base, roberta-base-openai-detector, roberta-large-openai-detector, distilbert-base-uncased, distilbert-base-uncased-distilled-squad, distilbert-base-german-cased, distilbert-base-multilingual-cased, distilbert-base-uncased-finetuned-sst-2-english, albert-base-v1, albert-large-v1, albert-xlarge-v1, albert-xxlarge-v1, albert-base-v2, albert-large-v2, albert-xlarge-v2, albert-xxlarge-v2, camembert-base, umberto-commoncrawl-cased-v1, umberto-wikipedia-uncased-v1, t5-small, t5-base, t5-large, t5-3b, t5-11b, xlm-roberta-base, xlm-roberta-large, xlm-roberta-large-finetuned-conll02-dutch, xlm-roberta-large-finetuned-conll02-spanish, xlm-roberta-large-finetuned-conll03-english, xlm-roberta-large-finetuned-conll03-german, flaubert-small-cased, flaubert-base-uncased, flaubert-base-cased, flaubert-large-cased). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/allenai/biomed_roberta_base/modelcard.json' was a path or url to a model card file named modelcard.json or a directory containing such a file but couldn't find any such file at this path or url.

Anyway I could use it for fillmask ? Facing the same for scibert too

**Comment by tuhinjubcse** [comment]
@patrickvonplaten

**Comment by julien-c** [comment]
Can you install transformers from source?

**Comment by tuhinjubcse** [comment]
Thanks worked for biomed-roberta

However 

```
nlp1 = pipeline("fill-mask", model="allenai/scibert_scivocab_cased", tokenizer="allenai/scibert_scivocab_cased")

nlp1("coinfection by multiple quasispecies is not uncommon in human <mask>, and that passage to Vero cells may either generate new mutations at a low rate, or titrates out one quasispecies in the transition.")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nas/home/tuhinc/miniconda3/envs/robertamed/lib/python3.7/site-packages/transformers/pipelines.py", line 743, in __call__
    masked_index = (input_ids == self.tokenizer.mask_token_id).nonzero().item()
ValueError: only one element tensors can be converted to Python scalars
```

**Comment by julien-c** [comment]
It’s not using the same mask token :)

Try [MASK] here
