### ISSUE TITLE
GePpeTto!

### ISSUE THREAD

**Issue by LoreDema** [huggingface/transformers#4089]
# 🌟 New model addition

## Model description

GePpeTto is a GPT-2 model for italian. For further details checkout the paper: https://arxiv.org/abs/2004.14253

## Open source status

* [X ] the model implementation is available: we used huggingface's GPT-2 implementation.
* [X ] the model weights are available: you can find the model here: https://github.com/LoreDema/GePpeTto
* [X ] who are the authors: @LoreDema @michelecafagna26 @malvinanissim @Falice1977 @marcoguerini

**Comment by clmnt** [comment]
Awesome! These instructions might help: https://huggingface.co/transformers/model_sharing.html?highlight=add%20model

**Comment by julien-c** [comment]
Hi @LoreDema, thanks for sharing GePpeTto, it's really cool!

Yes you can juste create a user account and an organization on huggingface.co and share the weights there. (and add a model card here if you can)

**Comment by LoreDema** [comment]
Awesome, just pushed the model and created a pull request for the card https://github.com/huggingface/transformers/pull/4099
