### ISSUE TITLE
Negative dimension when initialising the XLNetModel

### ISSUE THREAD

**Issue by yxu132** [huggingface/transformers#4094]
# 🐛 Bug

## Information

XLNetModel:

## To reproduce

```
import torch
from pytorch_transformers import *

# PyTorch-Transformers has a unified API
# for 7 transformer architectures and 30 pretrained weights.
#          Model          | Tokenizer          | Pretrained weights shortcut
MODELS = [(XLNetModel,      XLNetTokenizer,     'xlnet-base-cased')]

# Let's encode some text in a sequence of hidden-states using each model:
for model_class, tokenizer_class, pretrained_weights in MODELS:
    # Load pretrained model/tokenizer
    tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
    model = model_class.from_pretrained(pretrained_weights)

```

with the code above I got following errors: 

```
Traceback (most recent call last):
  File "/Users/xx/xxx/xxx/test.py", line 424, in <module>
    model = model_class.from_pretrained(pretrained_weights)
  File "/Users/yxu132/pyflow3.6/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 536, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/Users/yxu132/pyflow3.6/lib/python3.6/site-packages/pytorch_transformers/modeling_xlnet.py", line 731, in __init__
    self.word_embedding = nn.Embedding(config.n_token, config.d_model)
  File "/Users/xx/pyflow3.6/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 97, in __init__
    self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 768]
```

## Environment info

     
- `transformers` version:  1.2.0
- Platform:   MacOS
- Python version:  Python3.6
- PyTorch version (GPU?):  Torch 1.5 (with and without GPU)

**Comment by LysandreJik** [comment]
Hi, I can't reproduce this on `master`, could you upgrade your library to the latest version and let me know if you face the same issue?

**Comment by yxu132** [comment]
I think torch-1.5.0 and pytorch-transformers-1.2.0 are the latest versions, no?
I upgraded to python3.7 and tried the above again and still get the same issue.

**Comment by LysandreJik** [comment]
That's because `pytorch-transformers` became `transformers` in September!

**Comment by yxu132** [comment]
Thanks! It works now. Sorry for asking such a dum question...

**Comment by LysandreJik** [comment]
No worries, gald you could make it work!

**Comment by yxu132** [comment]
Cool! Problem solved. Will close this issue. 
Nice weekend!

**Comment by lytum** [comment]
> That's because `pytorch-transformers` became `transformers` in September!

what does that mean? Sorry, I didn't get your point and I have the same issue.

**Comment by yxu132** [comment]
> > That's because `pytorch-transformers` became `transformers` in September!
> 
> what does that mean? Sorry, I didn't get your point and I have the same issue.

Instead of install and use pytorch-transformers, install and use transformers. For examples,

> from transformers import *
