### ISSUE TITLE
BERT as encoder and a transformer as a decoder.

### ISSUE THREAD

**Issue by ayanamongol** [huggingface/transformers#4111]
Hi, there
Is there probability to build a model of the BERT as the encoder and the transformer as the decoder?

Thanks.

**Comment by FacingBugs** [comment]
The encoder-decoder or bart may be what you want.

**Comment by patrickvonplaten** [comment]
I think you should take a look into the ``encoder-decoder`` framework: https://huggingface.co/transformers/model_doc/encoderdecoder.html

**Comment by patrickvonplaten** [comment]
Note that currently only Bert2Bert is possible.
