### ISSUE TITLE
convert pytorch_model.pt [pretrained Bert model] to pytorch_model.onnx (ONNX)

### ISSUE THREAD

**Issue by pumpkinband** [huggingface/transformers#4124]
i use this to convert pytorch_model.pt to pytorch_model.onnx

```
from torch.autograd import Variable
import torch.onnx
import torchvision
import torch

dummy_input = Variable(torch.randn(1, 3, 256, 256))
model = torch.load('./pytorch_model.pt')
torch.onnx.export(model, dummy_input, "pytorch_model.onnx")
```

ERROR :- `The expanded size of the tensor (256) must match the existing size (3) at non-singleton dimension 3. Target sizes: [1, 3, 256, 256]. Tensor sizes: [1, 3]`

Are my `dummy_inputs` incorrect ?

**Comment by LysandreJik** [comment]
May be of interest to @mfuntowicz

**Comment by mfuntowicz** [comment]
Hi @pumpkinband, 

I don't have the exact details of the model you're trying to load, but I'd assume a tensor of shape (1, 3) would make more sense (batch, sequence).
