### ISSUE TITLE
Cannot loading SpanBERT pre-trained model 

### ISSUE THREAD

**Issue by palooney** [huggingface/transformers#4136]
I have some questions regarding SpanBert loading using the transformers package.

I downloaded the pre-trained file from [SpanBert](https://github.com/facebookresearch/SpanBERT) GitHub Repo and ```vocab.txt``` from Bert. Here is the code I used for loading:

```python
model = BertModel.from_pretrained(config_file=config_file,
                                  pretrained_model_name_or_path=model_file,
                                  vocab_file=vocab_file)
model.to("cuda")
```

where 

- ```config_file``` -> ```config.json```
- ```model_file``` -> ```pytorch_model.bin```
- ```vocab_file``` -> ```vocab.txt```

But I got the ```UnicodeDecoderError``` with the above code saying that ```'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte```

I also tried loading SpanBert with the method mentioned [here](https://huggingface.co/SpanBERT/spanbert-large-cased). But it returned ```OSError: file SpanBERT/spanbert-base-cased not found```.

Do you have any suggestions on loading the pre-trained model correctly? Any suggestions are much appreciated. Thanks!

**Comment by patil-suraj** [comment]
@palooney 
Can you check again ?. The following call worked for me
```
model = AutoModel.from_pretrained("SpanBERT/spanbert-base-cased")
```

**Comment by LysandreJik** [comment]
Closing, feel free to reopen if it isn't fixed.
