### ISSUE TITLE
How to make run_language_modeling.py work for transformer-xl?

### ISSUE THREAD

**Issue by bajajahsaas** [huggingface/transformers#4140]
The code in [run_language_modeling.py](https://github.com/huggingface/transformers/blob/master/examples/run_language_modeling.py) does Language modeling for any pre-trained model. However, for transformer-xl, we need additional arguments to the forward function like `mems` and even [run_transfo_xl.py](https://github.com/huggingface/transformers/blob/master/examples/contrib/run_transfo_xl.py) performs `model.reset_length()` operation using `mem_len` and `tgt_len` as arguments. 

I am not sure how these functions are performed in this generic code for runningLM for any pre-trained model. Any suggestions will be helpful.

**Comment by patrickvonplaten** [comment]
Yeah we don't have a run_language_modeling.py script yet. It's on a TODO list :-). Also see: #2008 .
If you feel like writing one, it would be great :-)
