### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by antoniomastro1996** [huggingface/transformers#4150]
# ❓ Questions & Help

## Details

Hi everybody, is there a way to automatically obtain the configuration file for pre-trained TensorFlow T5 network? Specifically the config.json file which I want to use to convert a tf model into pytorch using the script provided by HuggingFace.
Just to be more clear, I want something like that: https://s3.amazonaws.com/models.huggingface.co/bert/t5-small-config.json, with the specifications for my model.

Thanks in advance :)

**Comment by patrickvonplaten** [comment]
You get the default config file as written on AWS with 
```python 
config = T5Config.from_pretrained("t5-small")
```

If you want to change anything on the config after you can update it with a dict of your specifications:
```python 
config.update(your_dict)
```

**Comment by Arij-Aladel** [comment]
Hello !

**Comment by patrickvonplaten** [comment]
Hey @Arij-Aladel, 

What would be the purpose of adding parameters to the config, such as `max_target_len` that are not used in the corresponding model `T5Model`?

**Comment by Arij-Aladel** [comment]
A learning algorithm’s performance can be better than human-level performance and better than Bayes error.I am trying to build my model depending on t5 hugging face API and I need to build my own config. Whatever the purpose is , the question still what is th benefit of updating the parameters if I can not reuse them?

**Comment by Arij-Aladel** [comment]
Ok thanks I have solved it it was my bad, so sorry! every thing works well
