### ISSUE TITLE
Tapas

### ISSUE THREAD

**Issue by flozi00** [huggingface/transformers#4166]
# 🌟 New model addition

## Model descriptin

Tapas extends Bert architecture and is a transformer-based Table QA model

Paper: https://arxiv.org/abs/2004.02349

## Open source status

* [X] the model implementation is available: (give details)
https://github.com/google-research/tapas
* [X] the model weights are available: (give details)
The pretrained weights and data for fine-tuning are linked in the repository readme

* [x] who are the authors:
@thomasmueller-google is one of the authors

**Comment by shashankMadan-designEsthetics** [comment]
hey, @thomwolf this would be a great addition! have a look into it.

**Comment by volker42maru** [comment]
I think @NielsRogge is working on this over here: https://github.com/NielsRogge/transformers/tree/modeling_tapas
