### ISSUE TITLE
How to position encode a sentence?

### ISSUE THREAD

**Issue by saahiluppal** [huggingface/transformers#4170]
BertTokenizer provide us with input_ids, attention_mask and token_type_ids but i'm unable to get so called "Position ids".
I have read the documentation as well but unable to find anything.

**Comment by LysandreJik** [comment]
You don't need to provide position IDs to the model, the model will create them on its own. Similarly to the `attention_mask` and `token_type_ids`, you only need to provide them if you want them to be different to the default.

In the case of position IDs, provide them if you want to use a special scheme/different to what was used when pre-training the model.
