### ISSUE TITLE
Make ElectraPreTrainedModel importable

### ISSUE THREAD

**Issue by kumapo** [huggingface/transformers#4174]
# 🚀 Feature request

Make `ElectraPreTrainedModel` importable

## Motivation

Consistency.

`DistilBertPreTrainedModel` and `AlbertPreTrainedModel` are importable but I cannot import `ElectraPretrainedModel` from v2.8.0
(see https://github.com/huggingface/transformers/issues/1968)

## Your contribution

https://github.com/huggingface/transformers/pull/4173

**Comment by LysandreJik** [comment]
Thanks for contributing #4173 :).
