### ISSUE TITLE
Not able to import certain packages

### ISSUE THREAD

**Issue by prajjwal1** [huggingface/transformers#4177]
# 🐛 Bug

## Information
- I am using `run_glue.py`.
- Working with GLUE

## To reproduce

Even though these functions are imported in `__init__.py` (I have thoroughly checked myself), I'm not able to import `EvalPrediction`, `HfArgumentParser`, `Trainer`, `TrainingArguments`  

## Expected behavior
Should be able to import them. I'm sharing this [colab notebook](https://colab.research.google.com/drive/1CqWzt9A96iUT2vh47qwnMSDMsQHQkRSx) link.

## Environment info

     
- `transformers` version: 2.8
- Platform: Ubuntu 18.04
- Python version: 1.5
- PyTorch version (GPU?): 1.5
- Tensorflow version (GPU?): NA
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by julien-c** [comment]
You need to make sure you install from source as documented in the README
