### ISSUE TITLE
Error importing Reformer model

### ISSUE THREAD

**Issue by bayomim** [huggingface/transformers#4235]
# 🐛 Bug

## Information

I am trying to import the Reformer model as in here:
https://huggingface.co/transformers/model_doc/reformer.html
'''
from transformers import ReformerModel, ReformerConfig
'''
However, I am getting the following error:
ImportError: cannot import name 'ReformerModel' from 'transformers'

The problem arises when using:
* [ √] the official example scripts: (give details below)
* [ X ] my own modified scripts: (give details below)

- `transformers` version: 2.8.0

**Comment by flozi00** [comment]
I think you only need to update the library.
Version 2.9, released esterday, contains the reformer model

**Comment by bayomim** [comment]
Thanks, 
Installing Version 2.9.0 solved the issue
