### ISSUE TITLE
How to specify a TPU IP for run_tf_glue.py?

### ISSUE THREAD

**Issue by mar-muel** [huggingface/transformers#4252]
Hi team!

I have a VM on Google Cloud and a TPU. When running your example script `run_tf_glue.py` there is no option for specifying a TPU IP. It seems like the TPU cannot be auto-discovered and then training falls back to training on CPU 🐢

**Comment by jplu** [comment]
TPUs can be autodiscovered if you use them through AI-platform by running the trainer with `gcloud ai-platform jobs submit training ...` This is the advised usage of TPUs I put in the trainer.

Nevertheless if your want to use it through its name, this is done in the following PR #4270 thanks to @ViktorAlm
