### ISSUE TITLE
Vaswani's Transformer (Encoder-Decoder) decoding methods

### ISSUE THREAD

**Issue by manzar96** [huggingface/transformers#4256]
Hi,

I recently studied this blog https://huggingface.co/blog/how-to-generate for using different decoding methods with PreTrained Models.

I would like to ask if it is possible to use those methods with the simple Encoder-Decoder Transformer model (as mentioned in Vaswani's paper)  (as it is available in pytorch library "torch.nn") or I have to implement those decoding methods by my own.

Thank you in advance.

**Comment by patil-suraj** [comment]
Hello @manzar96 
The `.generate` method can be used with any HF model with a LM head on top.

**Comment by manzar96** [comment]
Ok thank you.
So it can be used only with those models https://pytorch.org/hub/huggingface_pytorch-transformers/ (having a LM head on top)
