### ISSUE TITLE
Could you help with a huggingface/transformers pretrained models download link?

### ISSUE THREAD

**Issue by yucc2018** [huggingface/transformers#4278]
# ❓ Questions & Help

## Details

  I am a natural language processing researcher from the Lenovo Research in Beijing. My colleagues and I really like your huggingface/transfromers framework and having been using it. I am currently writing a series of Chinese blogs about transformers, hoping to promote it to more Chinese friends. I want to download all of your pretrained models for study and experiments, but due to network problems in China, the download will be very slow and unstable. At the same time, manual downloading one by one is very troublesome. Could you kindly provide a unified download link which I can download all models? 
        Thank you.
@julien-c

**Comment by julien-c** [comment]
Hi, you can find the model identifiers in this JSON: https://huggingface.co/api/models

Then you can get all files URLs by removing `bert/` from the objects' keys and prefixing with URL endpoint "https://cdn.huggingface.co/"
