### ISSUE TITLE
TAPAS: Weakly Supervised Table Parsing via Pre-training

### ISSUE THREAD

**Issue by TheEdoardo93** [huggingface/transformers#4288]
# 🌟 TAPAS (Weakly Supervised Table Parsing via Pre-Training)

## Model description

**TAPAS** [ArXiV Paper](https://arxiv.org/pdf/2004.02349.pdf) [Google AI Blog](https://ai.googleblog.com/2020/04/using-neural-networks-to-find-answers.html?utm_campaign=Learning%20Posts&utm_content=128690771&utm_medium=social&utm_source=linkedin&hss_channel=lcp-9358547), an approach to question answering over tables without generating logical forms. TAPAS trains from weak supervision, and predicts the denotation by selecting table cells and optionally applying a corresponding aggregation operator to such selection. TAPAS extends BERT’s architecture to encode tables as input, initializes from an effective joint pre-training of text segments and tables crawled from Wikipedia, and is trained end-to-end. We experiment with three different semantic parsing datasets, and find that TAPAS outperforms or rivals semantic parsing models by improving state-of-the-art accuracy on SQA from 55.1 to 67.2 and performing on par with the state-of-the-art on WIKISQL and WIKITQ, but with a simpler model architecture. We additionally find that transfer learning, which is trivial in our setting, from WIKISQL to WIKITQ, yields 48.7 accuracy, 4.2 points above the state-of-the-art.

## Open source status

* [ X ] the model implementation is available: [GitHub repo](https://github.com/google-research/tapas/tree/master/tapas/models)
* [ X ] the model weights are available: in the "Data" section at [their GitHub page](https://github.com/google-research/tapas)
* [ X ] who are the authors: Jonathan Herzig, Paweł Krzysztof Nowak, Thomas Muller, Francesco Piccinno, Julian Martin Eisenschlos

**Comment by marmg** [comment]
Duplicated of [https://github.com/huggingface/transformers/issues/4166](url)
