### ISSUE TITLE
No crossattention layers in decoder from pretrained encoder-decoder model

### ISSUE THREAD

**Issue by hammad001** [huggingface/transformers#4293]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): BERT

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

Custom sequence to sequence task.

## To reproduce

1. Run the following script:
```
from transformers import EncoderDecoderModel
model = EncoderDecoderModel.from_encoder_decoder_pretrained('bert-base-uncased', 'bert-base-uncased') 
print(model.get_decoder())
```
2. You will find there's no crossattention layers in the decoder.

## Expected behavior

Cross attention layers initialized (not weights, but the layers themselves) in the decoder.

## Environment info
     
- `transformers` version: 2.9.0
- Platform: Linux-5.5.6-1.el7.x86_64-x86_64-with-debian-buster-sid
- Python version: 3.7.4
- PyTorch version (GPU?): 1.3.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: NO
- Using distributed or parallel set-up in script?:NO

**Comment by hammad001** [comment]
A simple fix could be:

1. Adding in file [modeling_encoder_decoder.py](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_encoder_decoder.py) @ line 140:

```
kwargs_decoder["is_decoder"]=True
```

2. Adding in file [modeling_auto.py](https://github.com/huggingface/transformers/blob/61d22f9cc7fbb0556d1e14447957a7ac6441421b/src/transformers/modeling_auto.py#L570) @ line 570

```
if not isinstance(config, PretrainedConfig):
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
    if kwargs.pop("is_decoder", None):
        config.is_decoder=True
```

That's is it! It should be good to go. The crossattention layers will be initialized; although it's weights will not be initialized. That will have to be trained.

**Comment by patrickvonplaten** [comment]
Hi @hammad001 - thanks a lot for finding this bug. It has helped me a lot. This PR: https://github.com/huggingface/transformers/pull/4680 should fix it :-)
