### ISSUE TITLE
Uploaded models not appearing on website

### ISSUE THREAD

**Issue by mananeau** [huggingface/transformers#4322]
# 🐛 Bug

## Information

I uploaded two models (named `clinicalcovid-bert-base-cased` and `biocovid-bert-large-cased`) following the instructions on the website. The folder I uploaded for each model contains the configuration json file, the vocabulary in txt format, the three tensorflow models files and the pytorch model bin. They are now downloadable from S3 at the following links:

| Model                            | Downloads
| -------------------------------- | ---------------------------------------------------------------------------------------------------------------
| `clinicalcovid-bert-base-cased`   | [`config.json`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/clinicalcovid-bert-base-cased/bert_config.json) • [`tensorflow weights`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/clinicalcovid-bert-base-cased/clinicalcovid_bert_base_cased.ckpt.data-00000-of-00001) • [`tensorflow.meta`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/clinicalcovid-bert-base-cased/clinicalcovid_bert_base_cased.ckpt.meta) • [`tensorflow.index`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/clinicalcovid-bert-base-cased/clinicalcovid_bert_base_cased.ckpt.index) • [`pytorch_model.bin`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/clinicalcovid-bert-base-cased/clinicalcovid_bert_base_cased.bin) • [`vocab.txt`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/clinicalcovid-bert-base-cased/vocab.txt)
| `biocovid-bert-large-cased` | [`config.json`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/biocovid-bert-large-cased/bert_config_bio_58k_large.json) • [`tensorflow weights`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/biocovid-bert-large-cased/biocovid_bert_large_cased.ckpt.data-00000-of-00001) • [`tensorflow.meta`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/biocovid-bert-large-cased/biocovid_bert_large_cased.ckpt.meta) • [`tensorflow.index`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/biocovid-bert-large-cased/biocovid_bert_large_cased.ckpt.index) • [`pytorch_model.bin`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/biocovid-bert-large-cased/biocovid_bert.bin) • [`vocab.txt`](https://s3.amazonaws.com/models.huggingface.co/bert/mananeau/biocovid-bert-large-cased/vocab_cased_pubmed_pmc_30k.txt)

Yet, they are not appearing on the [website](https://huggingface.co/mananeau). Any idea why that could be?

**Comment by julien-c** [comment]
Hi @mananeau we should improve validation and error messages soon, but the config.json file should be exactly named `config.json`

If you rename those files your models will pop up. 

Are they TF2 models?

**Comment by mananeau** [comment]
Got it, will try now. 

> Are they TF2 models?

They are TF1.11 and TF1.15 models.

**Comment by mananeau** [comment]
It worked, thanks a lot for your swift reply :) I created a PR mentioned above to clarify the upload instructions in the `README.md`. 

Keep on rocking!

**Comment by julien-c** [comment]
> They are TF1.11 and TF1.15 models.

FYI you can host those models if you want, but the transformers library doesn't support them

**Comment by julien-c** [comment]
(I'd be interested in hearing more about your use case here though)
