### ISSUE TITLE
[bug in run_glue.py] GlueDataset with no local_rank when init

### ISSUE THREAD

**Issue by jia-zhuang** [huggingface/transformers#4334]
https://github.com/huggingface/transformers/blob/241759101e7104192d01a07fc70432fa02ae8cb7/examples/text-classification/run_glue.py#L137

GlueData need to add local_rank parameter when init

```python
train_dataset = GlueDataset(data_args, tokenizer=tokenizer, local_rank=training_args.local_rank) if training_args.do_train else None
```

**Comment by julien-c** [comment]
Not on master.

You should install from source when running the examples, as specified in the [README](https://github.com/huggingface/transformers#run-the-examples).
