### ISSUE TITLE
Can not reproduce article numbers

### ISSUE THREAD

**Issue by vladgets** [huggingface/transformers#4364]
# 🐛 Bug
https://github.com/huggingface/transformers/tree/master/examples/summarization/bertabs

## Information
Bertabs Rouge1/2 F1 evaluation numbers that I am getting are much less than in their article. About twice less!  

Model I am using (Bert, XLNet ...):
Bertabs 

Language I am using the model on (English, Chinese ...):

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)
Summarization 

## To reproduce

1.
2.
3.

## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by vladgets** [comment]
These are numbers that I am getting when running the examples (in the article or here: https://github.com/nlpyang/PreSumm) they mention much higher numbers: 

****** ROUGE SCORES ******

** ROUGE 1
F1        >> 0.195
Precision >> 0.209
Recall    >> 0.186

** ROUGE 2
F1        >> 0.094
Precision >> 0.104
Recall    >> 0.089

** ROUGE L
F1        >> 0.221
Precision >> 0.233
Recall    >> 0.212

**Comment by alexgaskell10** [comment]
same here. Also getting ROUGE scores in the same ball-park

**Comment by vladgets** [comment]
Well, I already switched to Bart model. I do not know what is the reasons for low numbers here, possibly some bugs in the porting, but in general BertAbs model does not seem the best approach for it.

**Comment by vladgets** [comment]
Alex, by the way I see that you are currently working on Summarization topic too. If you like you can write me directly to vgetselevich@nvidia.com (I am currently conversational AI researcher at Nvidia) and we can have more detailed discussion on this topic.

**Comment by alexgaskell10** [comment]
Will do, thanks!
