### ISSUE TITLE
demo website: i info icon should link to resource about parameters

### ISSUE THREAD

**Issue by rugk** [huggingface/transformers#4369]
The website/demo at https://transformer.huggingface.co does have a "Model & decoder settings" box at the bottom left.
Next to it, at the right, there is an "(i)" sign.

STR: Click on it.
**What happens:** It links to this repo.
**What should happen:** It should link to somewhere, where the parameters are actually explained.

Reason:
The generic link to this repo is way to – well – generic. I've searched the Readme for the parameter names and could not find anything useful/an explanation of what they actually do.
The reason I click on that icon is to know what I can adjust there/what happens if I change an option, I don't just want to see the general project.

There should be a page that just explains, what each option means (in simple terms):
* Model size: what model to use (from small to big), the bigger the more useful/accurate(?) it may be
* Top p:
* Temperature: 
* Max time: how long the model should – at most – compute to search for results

**Comment by julien-c** [comment]
Hi @rugk, open to any suggestion for a better documentation link – e.g. should we link to https://huggingface.co/blog/how-to-generate ?

Maybe https://medium.com/huggingface/how-to-write-with-transformer-5ee58d6f51fa ?

Or to https://medium.com/huggingface/how-to-build-a-state-of-the-art-conversational-ai-with-transfer-learning-2d818ac26313#79c5 like on https://convai.huggingface.co/

cc @patrickvonplaten @sgugger

**Comment by rugk** [comment]
I dunno. My complaint was just an UX complaint from a user with less scientific background, so linking to very in-deep document is likely bad.

How you solve this hmm?
Maybe just write a new doc/small wiki entry here on GitHub or so?

Though if I check your links the "Advanced settings" section in https://medium.com/huggingface/how-to-write-with-transformer-5ee58d6f51fa It does what I want: explains the parameter.

**Comment by rugk** [comment]
shh #badbot :no_bell::robot::no_bell: This is still a TODO.
