### ISSUE TITLE
Error on instantiating pipeline.summarizer

### ISSUE THREAD

**Issue by amgsharma** [huggingface/transformers#4376]
# 🐛 Bug

## Information

The problem arises when using:
I'm just testing out the different modules in the package. and following the examples on the [usage page](https://huggingface.co/transformers/usage.html)

## To reproduce

Run the following snippet with the environment set up as. described in the relevant section below
`from transformers import pipeline`
`summarizer = pipeline("summarization")`

<!-->

This is the traceback:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
 in 
----> 1 summarizer = pipeline("summarization")

~/Projects/amlg/playground/venv/lib/python3.7/site-packages/transformers/pipelines.py in pipeline(task, model, config, tokenizer, framework, **kwargs)
   1759         model = model_class.from_pretrained(model, config=config, **model_kwargs)
   1760 
-> 1761     return task_class(model=model, tokenizer=tokenizer, modelcard=modelcard, framework=framework, task=task, **kwargs)

~/Projects/amlg/playground/venv/lib/python3.7/site-packages/transformers/pipelines.py in __init__(self, model, tokenizer, modelcard, framework, task, args_parser, device, binary_output)
    392 
    393         # Update config with task specific parameters
--> 394         task_specific_params = self.model.config.task_specific_params
    395         if task_specific_params is not None and task in task_specific_params:
    396             self.model.config.update(task_specific_params.get(task))

AttributeError: 'NoneType' object has no attribute 'config'
```

## Environment info
- `transformers` version: 2.9.1
- Platform: Darwin-19.3.0-x86_64-i386-64bit
- Python version: 3.7.3
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.1.0 (False)
- Using GPU in script?: Nope
- Using distributed or parallel set-up in script?: Nope

**Comment by ajay-sreeram** [comment]
I am also facing the same problem
