### ISSUE TITLE
Unknown task fill-mask

### ISSUE THREAD

**Issue by DesiKeki** [huggingface/transformers#4381]
# 🐛 Bug

## Information

I am trying to create a "Pipeline" for fill-mask task

Language I am using the model on is English

The problem arises when using:
My own modified scripts: (give details below)
```
import transformers
transformers.__version__
```
>>'2.3.0'
```
from transformers import pipeline
nlp_fill = pipeline('fill-mask')
nlp_fill('Hugging Face is a French company based in <mask>')
```
>>---------------------------------------------------------------------------
>>KeyError                                  Traceback (most recent call last)
>><ipython-input-22-d415d13f7528> in <module>
>>----> 1 nlp_fill = pipeline('fill-mask')
>>     2 nlp_fill('Hugging Face is a French company based in <mask>')
>>
>>~\Anaconda3\lib\site-packages\transformers\pipelines.py in pipeline(task, model, config, tokenizer, modelcard, **kwargs)
>>    848     # Retrieve the task
>>    849     if task not in SUPPORTED_TASKS:
>>--> 850         raise KeyError("Unknown task {}, available tasks are {}".format(task, list(SUPPORTED_TASKS.keys())))
>>    851 
>>    852     framework = get_framework(model)
>> **KeyError**: "Unknown task fill-mask, available tasks are ['feature-extraction', 'sentiment-analysis', 'ner', 'question-answering']"

The tasks I am working on is:
My own task or dataset. Trying using Pipeline.

## To reproduce

from transformers import pipeline
nlp_fill = pipeline('fill-mask')
nlp_fill('Hugging Face is a French company based in <mask>')

## Expected behavior
Should have got a filled output with a score.

## Environment info
'transformers-cli' is not recognized as an internal or external command, operable program or batch file.
     
- `transformers` version: 2.3.0
- Platform: Windows Jupyter notebook
- Python version: 3.7.4

**Comment by julien-c** [comment]
Can you upgrade your version of transformers?

**Comment by Sriharsha-hatwar** [comment]
Same issue I am not able to run the command `transformer-cli env` even after installing from source @julien-c .

'transformer-cli' is not recognized as an internal or external command,
operable program or batch file 

Just wondering if this is due to the fact of using `conda` as in latest versions it is not preferring to modify the PYTHONPATH. hence the non visibility of the command?

**Comment by DesiKeki** [comment]
Upgrading the transformers version to 2.9.1 works!
