### ISSUE TITLE
Finetuning BERT classifier on a non-GLUE dataset in GLUE format

### ISSUE THREAD

**Issue by shauli-ravfogel** [huggingface/transformers#4386]
# ❓ Questions & Help

## Details
Hello,

I have a dataset of my own, formatted in GLUE format. Is it possible to use the script `run_glue.py` to finetune BERT on this dataset? If that's not possible, is there an alternative script for finetuning a classifier on arbitrary GLUE-formatted dataset?

Thanks!

**Comment by julien-c** [comment]
The (new) run_glue.py is just a short template of code that you can copy/paste/customize (e.g. to plug your own Dataset), thanks to the [Trainer](https://github.com/huggingface/transformers/blob/master/src/transformers/trainer.py).

**Comment by Shaul1321** [comment]
Thanks! which class would replace `GlueDataset` in that case? and what argument should I pass instead of `task_name`? and how to set the number of labels, which in `run_glue.py` is defined by `glue_tasks_num_labels`?
