### ISSUE TITLE
[docs] AutoModelWithLMHead(model_name, **kwargs)

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#4388]
`AutoModelWithLMHead.from_pretrained` cannot accept `output_attentions=True`

This [docstring](https://huggingface.co/transformers/model_doc/auto.html?highlight=transformers%20automodelwithlmhead#transformers.AutoModelWithLMHead) suggests that it can.

Thanks @jrvc for discovering!

```python
import transformers
modelname='Helsinki-NLP/opus-mt-en-de'
config_overrider={'output_attentions':True, 'output_hidden_states':True}
self.model = transformers.AutoModelWithLMHead.from_pretrained(modelname, **config_overrider)
=>
*** TypeError: __init__() got an unexpected keyword argument 'output_attentions'
```

I will dig deeper!

**Comment by sshleifer** [comment]
unstale?

**Comment by LysandreJik** [comment]
This was fixed with https://github.com/huggingface/transformers/pull/5665!
