### ISSUE TITLE
MarianMTModel translate {tgt}-{src}

### ISSUE THREAD

**Issue by NonaryR** [huggingface/transformers#4392]
Hello! 
It is possible to use `MarianMTModels` for translation from the target language to source, i.e. backward?

**Comment by sshleifer** [comment]
Nope. Often the reverse model exists, however, e.g. `en-fr` and `fr-en`.

**Comment by shebogholo** [comment]
> Nope. Often the reverse model exists, however, e.g. `en-fr` and `fr-en`.

What if reverse model does not exist for my langauge?

**Comment by sshleifer** [comment]
What's your language? 
Maybe it's part of a multilingual group (below) or has been [trained](http://opus.nlpl.eu/Opus-MT/) since we did the conversion?
Otherwise, you're out of luck unfortunately.

```
GROUP_MEMBERS = {
 'ZH': ['cmn', 'cn', 'yue', 'ze_zh', 'zh_cn', 'zh_CN', 'zh_HK', 'zh_tw', 'zh_TW', 'zh_yue', 'zhs', 'zht', 'zh'],
 'ROMANCE': ['fr', 'fr_BE', 'fr_CA', 'fr_FR', 'wa', 'frp', 'oc', 'ca', 'rm', 'lld', 'fur', 'lij', 'lmo', 'es', 'es_AR', 'es_CL', 'es_CO', 'es_CR', 'es_DO', 'es_EC', 'es_ES', 'es_GT', 'es_HN', 'es_MX', 'es_NI', 'es_PA', 'es_PE', 'es_PR', 'es_SV', 'es_UY', 'es_VE', 'pt', 'pt_br', 'pt_BR', 'pt_PT', 'gl', 'lad', 'an', 'mwl', 'it', 'it_IT', 'co', 'nap', 'scn', 'vec', 'sc', 'ro', 'la'],
 'NORTH_EU': ['de', 'nl', 'fy', 'af', 'da', 'fo', 'is', 'no', 'nb', 'nn', 'sv'],
 'SCANDINAVIA': ['da', 'fo', 'is', 'no', 'nb', 'nn', 'sv'],
 'SAMI': ['se', 'sma', 'smj', 'smn', 'sms'],
 'NORWAY': ['nb_NO', 'nb', 'nn_NO', 'nn', 'nog', 'no_nb', 'no'],
 'CELTIC': ['ga', 'cy', 'br', 'gd', 'kw', 'gv']
}
```

**Comment by shebogholo** [comment]
> What's your language?
> Maybe it's part of a multilingual group (below) or has been [trained](http://opus.nlpl.eu/Opus-MT/) since we did the conversion?
> Otherwise, you're out of luck unfortunately.
> 
> ```
> GROUP_MEMBERS = {
>  'ZH': ['cmn', 'cn', 'yue', 'ze_zh', 'zh_cn', 'zh_CN', 'zh_HK', 'zh_tw', 'zh_TW', 'zh_yue', 'zhs', 'zht', 'zh'],
>  'ROMANCE': ['fr', 'fr_BE', 'fr_CA', 'fr_FR', 'wa', 'frp', 'oc', 'ca', 'rm', 'lld', 'fur', 'lij', 'lmo', 'es', 'es_AR', 'es_CL', 'es_CO', 'es_CR', 'es_DO', 'es_EC', 'es_ES', 'es_GT', 'es_HN', 'es_MX', 'es_NI', 'es_PA', 'es_PE', 'es_PR', 'es_SV', 'es_UY', 'es_VE', 'pt', 'pt_br', 'pt_BR', 'pt_PT', 'gl', 'lad', 'an', 'mwl', 'it', 'it_IT', 'co', 'nap', 'scn', 'vec', 'sc', 'ro', 'la'],
>  'NORTH_EU': ['de', 'nl', 'fy', 'af', 'da', 'fo', 'is', 'no', 'nb', 'nn', 'sv'],
>  'SCANDINAVIA': ['da', 'fo', 'is', 'no', 'nb', 'nn', 'sv'],
>  'SAMI': ['se', 'sma', 'smj', 'smn', 'sms'],
>  'NORWAY': ['nb_NO', 'nb', 'nn_NO', 'nn', 'nog', 'no_nb', 'no'],
>  'CELTIC': ['ga', 'cy', 'br', 'gd', 'kw', 'gv']
> }
> ```

Swahili, oooh!
