### ISSUE TITLE
Wrong model or tokenizer for MarianMT

### ISSUE THREAD

**Issue by NonaryR** [huggingface/transformers#4396]
While we [can't save](https://github.com/huggingface/transformers/issues/4371) `MarianTokenizer` to local directory, I found model weights and configs on [this page](https://huggingface.co/Helsinki-NLP/opus-mt-en-ROMANCE), in `List all files in model ` link.
I downloaded  these files, but I think this is wrong configs, because I can't reproduce even simplest example from [here](https://huggingface.co/transformers/model_doc/marian.html)
This text
```
1)  '>>fr<< this is a sentence in english that we want to translate to french',
2) '>>pt<< This should go to portuguese',
3) '>>es<< And this to Spanish'
should became
1) "c'est une phrase en anglais que nous voulons traduire en français",
2) 'Isto deve ir para o português.',
3) 'Y esto al español'
```
with model and configs downloaded from the link above produces these results:
```
1) "c'est une phrase en anglais que nous voulons traduire en français" (as expected)
2) "Questo deve ir in portughese"
3) "E questo a spagnol"
```
This is definitely wrong, can you help?

**Comment by NonaryR** [comment]
Never mind, my mistake

**Comment by R4ZZ3** [comment]
What was your mistake?

Is your system Windows?
I am trying to reproduce the colab tutorial from https://blogs.helsinki.fi/language-technology/2020/05/14/helsinkinlp-in-huggingface/ on Windows but I get errors.

**Comment by NonaryR** [comment]
@R4ZZ3 Hello! I just appended `>>tag<<` for text in cycle, and my text quickly became a mess of tags. And no Windows, sorry, can't help.

**Comment by erikchwang** [comment]
Can anyone help with this issue: #5040 ?
