### ISSUE TITLE
Get BERT sentence encoding

### ISSUE THREAD

**Issue by orenkobo** [huggingface/transformers#4414]
I am trying to access to encoding of sentences in the vaious layers in pre-trained BERT model.
So it should be something like this:

```
sentence = 'We bought a new car'
bert_encoder = load_encoder('bert-base-uncased')
enc = bert_encoder.encode(sentence)
enc.get_layer[0] #this is the first layer
enc.get_layer[-1] #this is the last layer

```
What is the best way to do it?
Thanks!

**Comment by Sriharsha-hatwar** [comment]
I believe you can't do like that, you have to run the model just as is with all the necessary inputs(pertaining to the sentence) as mentioned in the docs : https://huggingface.co/transformers/model_doc/bert.html#transformers.BertModel
and then add the configuration : `config.output_hidden_states=True` for getting the embeddings  from each intermediate encoding layers.

**Comment by orenkobo** [comment]
@Sriharsha-hatwar Thanks, do you have a code sample maybe?
