### ISSUE TITLE
TypeError: add_() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by mqliu7** [huggingface/transformers#4417]
# 🐛 Bug

## Information

I was trying to reproduce the GLUE fine-tuning example (https://huggingface.co/transformers/examples.html#fine-tuning-example) when I ran into this error:

```
  File "~/anaconda3/lib/python3.7/site-packages/transformers/optimization.py", line 155, in step
    exp_avg.mul_(beta1).add_(grad, 1.0 - beta1)
TypeError: add_() takes 1 positional argument but 2 were given
```

The problem arises when using:
* [x] the official example scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)

## To reproduce

Follow the official guide example here:  https://huggingface.co/transformers/examples.html#fine-tuning-example

## Environment info

     
- `transformers` version: 2.9.1
- Platform: Linux 5.4.0-29-generic x86_64 Ubuntu 20.04 LTS
- Python version: 3.7.6
- PyTorch version (GPU?): 1.5.0 (Yes)
- Tensorflow version (GPU?): 
- Using GPU in script?: Yes, 1
- Using distributed or parallel set-up in script?:

**Comment by julien-c** [comment]
This was fixed on master on Friday, can you try pulling from master again?
