### ISSUE TITLE
mbart config.json missing

### ISSUE THREAD

**Issue by WeiliangGuo** [huggingface/transformers#4429]
I downloaded mbart from fairseq, there are dict.txt, model.pt, sentence.bpe.model in it but no config.json, where can we get it (and other necessary missing files)?
I use mbart as pretrained model.

Is bart-large trained on multilingual data?
 Anyone has compared bart with t5?

**Comment by sshleifer** [comment]
fairseq doesn't use config.json.

`BartConfig.from_pretrained('mbart-large-en-ro').to_json_file('config.json')` gets the config.json for English-Romanian, which is the only mbart checkpoint that's usable in this repository.
