### ISSUE TITLE
Reformer training error

### ISSUE THREAD

**Issue by Brock007** [huggingface/transformers#4440]
# 🐛 Bug

When training a Reformer model from scratch, I got the following error:

**TypeError: forward() got an unexpected keyword argument 'masked_lm_labels'**

## Information

I am trying to train a Reformer model from scratch on English documents. My data is one document per line:

The problem arises when using:
* [ x ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ x ] my own task or dataset: (give details below)

## To reproduce

1. Split my training documents on '.' to create a corpus of sentences. Use Google SentencePiece script to train a tokenization model.
2. Use run_language_modeling.py with --mlm --tokenizer_name=path/to/pretrained_SP_tokenizer to train the model.
3. My config.json looks like this:

```
{
  "architectures": [
    "ReformerModelWithLMHead"
  ],
  "model_type": "reformer",
  "vocab_size": 32000
}
```

File "/Users/a9dvzzz/.virtualenvs/cf-mlc/lib/python3.7/site-packages/transformers/trainer.py", line 506, in _training_step
    outputs = model(**inputs)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'masked_lm_labels'

## Expected behavior

The training process produces a saved Reformer model.

## Environment info
- `transformers` version: 2.9.1
- Platform: Darwin-19.4.0-x86_64-i386-64bit
- Python version: 3.7.4
- PyTorch version (GPU?): 1.3.0 (False)
- Tensorflow version (GPU?): 2.0.0 (False)
- Using GPU in script?: no, but it doesn't seem to matter, both failed.
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
Reformer does not support `mlm` training at the moment. Please make sure you use `lm` training :-)

**Comment by Brock007** [comment]
@patrickvonplaten thanks! Is there a plan to support mlm in the near future? 

I assume I can just remove the mlm flag to do lm training, right? How can I tell the script to pad the input sequences to a certain length? Thanks!

**Comment by patrickvonplaten** [comment]
Yes, there are plans to add a `MaskedLM` version for Reformer. I will release a notebook this week (probs on Friday) on how to train the Reformer :-)
