### ISSUE TITLE
Generation with EncoderDecoder Model

### ISSUE THREAD

**Issue by manzar96** [huggingface/transformers#4445]
# ❓ Questions & Help

Hi, 
I am using the EncoderDecoder Model and I would like to use the generate method for sequence generation. As I have read in docs, the generate method can be used with any Pretrained HF model with  LM head on top.
So wrapping a pretrained LM model (e.g. GPT2LMHeadModel, BertForMaskedLM) (and having a encoder too) with the Encoder-Decoder class gives null bos_token_id and the generate method does not work properly. However using only a pretrained LM model (without wrapping with the Encoder-Decoder class) gives a valid bos_token_id (because the config file contains bos_token_id).
How I should handle the above issue?

Thank you in advance.

**Comment by manzar96** [comment]
Do we have any updates on this issue?

**Comment by manzar96** [comment]
I would also like to note that wrapping the gpt2 model with the Encoder Decoder class raises an error at forward as decoder's (gpt2) forward doesn't have parameter encoder_hidden_state.

**Comment by patrickvonplaten** [comment]
I will take a look at this at the end of next week - will get to you!

**Comment by manzar96** [comment]
> I will take a look at this at the end of next week - will get to you!

Thanks a lot!

**Comment by patrickvonplaten** [comment]
Hi @Xunzhuo,
Multiple bugs were fixed in #4680 . Can you please take a look whether this error persists?
