### ISSUE TITLE
❓ Warning : This overload of addcdiv_ is deprecated

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#4451]
# ❓ Questions & Help

When running the [official Colab example of GLUE](https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/trainer/01_text_classification.ipynb), during training I receive a `UserWarning` :

```
/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of addcdiv_ is deprecated:
	addcdiv_(Number value, Tensor tensor1, Tensor tensor2)
Consider using one of the following signatures instead:
	addcdiv_(Tensor tensor1, Tensor tensor2, *, Number value)
```

---

**Is it expected ?**

**Comment by julien-c** [comment]
Not expected, but shouldn't be an issue. Feel free to open a PR swapping args in https://github.com/huggingface/transformers/blob/31eedff5a0fc47d60609089627af6698c21da88d/src/transformers/optimization.py#L165
