### ISSUE TITLE
DMOZ - web page classification / multi-language

### ISSUE THREAD

**Issue by x0rzkov** [huggingface/transformers#4454]
Hi,

Hope you are all well !

Still quite a newbie with transformers, I wanted to know how could it be possible to build a web page classifier with the DMOZ dump and to classify them into categories in several languages.

Thanks in advance for any insights or inputs on that question.

Cheers,
X

**Comment by alaa-abdelsamie** [comment]
Can you check the Dmoz[Dmoz] 
the database in sql he cost 1000$ to change it  (https://idmoz.org)
