### ISSUE TITLE
Request for hosting model files in a Virtual Hosted-Style S3 buckets

### ISSUE THREAD

**Issue by rjsaito** [huggingface/transformers#4475]
Is there any plans for the s3 buckets currently hosting the model files to migrate from the current "Path-Style Request" format to a "Virtual Hosted-Style Request" format?

Path-Style URLs follow the following format (s3.amazonaws.com/* OR s3.Region.amazonaws.com/*). For example, today the model config file for 'bert_uncased_L-2_H-128_A-2' is accessed via the Path-Style URL:

https://s3.amazonaws.com/models.huggingface.co/bert/google/bert_uncased_L-2_H-128_A-2/config.json

According to AWS, they will be deprecating Path-Style requests (though there will be legacy support) - but one major reason for the migration to the Virtual Hosted-Style URL (which takes the form bucket-name.s3.amazonaws.com or bucket-name.s3.Region.amazonaws.com) is for security reasons (e.g. if companies/organizations need to whitelist sites in their servers to utilize transformer models, the virtual hosted style will reduce the "blast radius" in cases of security breaches).

More details on "Path" vs "Virtual-Hosted" style requests:

https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#path-style-access

**Comment by julien-c** [comment]
Hi @rjsaito we are actually moving to serving all our files from the cloudfront powered cdn.huggingface.co

**Comment by rjsaito** [comment]
Awesome! Do you have a current ETA when this change would be in place?

**Comment by julien-c** [comment]
It's already in place for model weights.
