### ISSUE TITLE
Incorporate HuggingFace 'nlp' library in examples

### ISSUE THREAD

**Issue by nateraw** [huggingface/transformers#4494]
# 🚀 Feature request

I propose we replace the custom data downloading/preprocessing logic found within the examples directory with the new [**HuggingFace `nlp` Library**](https://github.com/huggingface/nlp) where applicable.

## Motivation

The examples directory is filled with custom shell scripts that download and process common research datasets. These scripts work great, but are at times tricky to follow. I'm sure this can be discouraging for new users looking to try out `transformers` for the first time.

I'm hoping `nlp` will make the examples generally more accessible for both new and experienced users. And yeah...I guess it's probably not too bad for the brand either. 😉 

## Your contribution

I'll get a WIP PR pushed up this weekend. I'll focus on the `pytorch_lightning` examples for now.

**Comment by sshleifer** [comment]
Love this idea. @thomwolf @julien-c what do you guys think about adding `nlp` as a dependency?
