### ISSUE TITLE
How to finetune ELECTRA on glue?

### ISSUE THREAD

**Issue by elyesmanai** [huggingface/transformers#4502]
After pretraining my own electra model, I wanted to test it out in Glue using run_glue.py.
However I got this: 
```
ValueError: Unrecognized configuration class <class 'transformers.configuration_electra.ElectraConfig'> for this kind of AutoModel: AutoModelForSequenceClassification.
Model type should be one of DistilBertConfig, AlbertConfig, CamembertConfig, XLMRobertaConfig, BartConfig, RobertaConfig, BertConfig, XLNetConfig, FlaubertConfig, XLMConfig.
```
After taking a look at the source code, It seems like ElectraConfig isn't available for sequence classification, is there a reason for that?  Did anyone finetune electra on glue?

**Comment by liuzzi** [comment]
I have a pull request here
https://github.com/huggingface/transformers/pull/4257

**Comment by elyesmanai** [comment]
I just cloned your repo an tried to test with my model and it keeps saying the same: 
![image](https://user-images.githubusercontent.com/21007166/82654565-39745300-9c21-11ea-8da8-ad3bebb8a391.png)

Could you tell me how it's used?

**Comment by LysandreJik** [comment]
@liuzzi's PR was merged this morning. The `ElectraForSequenceClassification` model is now available, so you can use it directly in `run_glue.py`.

Please make sure to pull the latest changes from the repo, or to wait for `v2.10` which should be released in a few hours.

**Comment by elyesmanai** [comment]
awesome, it works perfectly, thank you very much!

**Comment by glakshmidhar** [comment]
@elyesmanai Could you please share the code for pretraining Electra from scratch?

**Comment by elyesmanai** [comment]
I'm using the simpletransformers library for the pretraining since transformers doesn't support it yet.
here's a [link](https://towardsdatascience.com/understanding-electra-and-training-an-electra-language-model-3d33e3a9660d) to how you can do it, it's super easy.
It's built on top of transformers so you can load the model into transformers and use the rest of the lib

**Comment by LysandreJik** [comment]
The pre-training from scratch for `transformers` is available [here](https://github.com/huggingface/transformers/pull/4656). It is being tested right now.

**Comment by cktsangal** [comment]
This problem happened again, when I use ELECTRA on question-answering pipeline. My Transformers version is 2.11.0.

> from transformers import pipeline, AutoTokenizer, AutoModelForQuestionAnswering
> 
> tokenizer = AutoTokenizer.from_pretrained("ahotrod/electra_large_discriminator_squad2_512")
> 
> model = AutoModelForQuestionAnswering.from_pretrained("ahotrod/electra_large_discriminator_squad2_512")
> 
> albert_qa = pipeline('question-answering', model=model, tokenizer=tokenizer)

![image](https://user-images.githubusercontent.com/53075457/87435341-2fb60d00-c61e-11ea-91be-538747c70559.png)
