### ISSUE TITLE
FillMaskPipeline crashes when executed on TPU

### ISSUE THREAD

**Issue by LeonieWeissweiler** [huggingface/transformers#4508]
# 🐛 Bug

## Information

I am following the tutorial in https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/01_how_to_train.ipynb#scrollTo=QDNgPls7_l13 and running on Google Colab using the TPU. The Pipeline object creation works fine, but when I try to run it on the example sentence, the Colab runtime crashes immediately with an unclear cause and no error message. If I remove the TPU and do not install xla, the pipeline works fine.

## To reproduce

```python3
!pip uninstall transformers
!git clone https://github.com/huggingface/transformers
!pip install ./transformers

VERSION = "nightly" 
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION

from transformers import pipeline

fill_mask = pipeline(
    "fill-mask",
    model="drive/My Drive/models/EsperBERTo/output/checkpoint-15000",
    tokenizer="drive/My Drive/models/EsperBERTo"
)

fill_mask("La suno <mask>.")

```

Is anyone else experiencing this?

**Comment by LysandreJik** [comment]
Hello! Pipelines are not tested on TPUs yet, unfortunately, and we have not made any effort to support them on that device. We may down the road, once TPU CI is more easily available.
