### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [huggingface/transformers#4524]
Hi, Tom from Codecov here.

We noticed that you are using our app with high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting from GitHub.

**In order to prevent any future outages, we ask that you move over to our GitHub marketplace app: https://github.com/marketplace/codecov.**

Let me know if you have any questions, or if I can help at all with this process.

**Comment by BramVanroy** [comment]
cc @LysandreJik @thomwolf

**Comment by LysandreJik** [comment]
Hi @thomasrockhu, indeed we've faced such issues before. We'll take a look, thanks!
