### ISSUE TITLE
resize_token_embeddings not implemented for TFGPT2LMHeadModel

### ISSUE THREAD

**Issue by virginianegri** [huggingface/transformers#4536]
I am using a TFGPT2LMHeadModel pretrained model and new special tokens to the gpt tokenizer.
However, the method resize_token_embeddings is not implemented in all gpt2 tf models.
Will it be added? Or are there any workarounds?

Thank you!

**Comment by patrickvonplaten** [comment]
Hi @virginianegri, 

Could you specific for which model the method `resize_token_embeddings` does not work? 
Can you add a code snippet that reproduces the error?

**Comment by virginianegri** [comment]
The model is the TFGPT2LMHeadModel. This is my code:
```
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
special_tokens_dict = {'cls_token': '<CLS>'}
num_added_toks = tokenizer.add_special_tokens(special_tokens_dict)

gpt2 = TFGPT2LMHeadModel.from_pretrained('gpt2')
gpt2.resize_token_embeddings(len(tokenizer)) 
```

When running the resize_token_embeddings method it launches a NotImplementedError

**Comment by patrickvonplaten** [comment]
Yes we should implement this soon!
