### ISSUE TITLE
seems that run_ner.py cannot handle the situation when example length exceed max_length? 

### ISSUE THREAD

**Issue by 1160300929** [huggingface/transformers#4544]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):

Language I am using the model on (English, Chinese ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by 1160300929** [comment]
> Hi! Do you mind filling-in the template? It will help us help you better!

OK!I think this will be a great practice for me

**Comment by LysandreJik** [comment]
Great, thanks
