### ISSUE TITLE
Albert Tokenizer hangs

### ISSUE THREAD

**Issue by LeonieWeissweiler** [huggingface/transformers#4560]
# 🐛 Bug

## Information
I am following the language modeling tutorial to train a LM on a simple wikipedia corpus from scratch. I am trying to use Albert instead of Roberta. As I couldn't find information on how to train an Albert Tokenizer from scratch, I'm loading the albert-base-v2 tokenizer. The Dataset creation doesn't work, it hangs for ages and when I stop it, I can see that it is always stuck in tokenization_albert.py, line 193:  

```python           
outputs = "".join([c for c in outputs if not unicodedata.combining(c)])
```

A week ago, it crashed consistently in this line due to large RAM allocations, but I can't reproduce that behaviour right now. 

## To reproduce

```python
from transformers import AlbertTokenizer
tokenizer = AlbertTokenizer.from_pretrained("albert-base-v2")
from transformers import TextDataset
train_set = TextDataset(
    tokenizer=tokenizer,
    file_path="./drive/My Drive/datasets/simplewiki_train.txt",
    block_size=128,
)
```
## Expected behavior

I expected the tokenizer to run through in less than an hour for 100MB input. 

## Environment info

     
- `transformers` version: 2.10.0
- Platform: Colab
- Python version: 3.6

Is anyone else experiencing this? I read in another issue that Albert should work with run_language_modeling out of the box.

**Comment by BramVanroy** [comment]
Does this also happen when you use the slow tokenizers?

```python
tokenizer = AlbertTokenizer.from_pretrained("albert-base-v2", use_fast=False)
```

**Comment by LeonieWeissweiler** [comment]
Thanks for the suggestion @BramVanroy . I just tried this and the tokenizer has now been running for 90 minutes, so I think that's a yes.

**Comment by BramVanroy** [comment]
cc @mfuntowicz AlbertTokenizer seems to hang in fast mode but not in slow mode

**Comment by thomwolf** [comment]
Hi, there is no fast mode for `AlbertTokenizer`, it's a SentencePiece based tokenizer which is not currently supported by `tokenizers`.

Do you think you can find more information about where the tokenizer actually hang?
Can you reproduce the behavior with a shorter input?
