### ISSUE TITLE
cannot import name 'TFElectraModel' from 'transformers'

### ISSUE THREAD

**Issue by lijinfeng0713** [huggingface/transformers#4571]
# 🐛 Bug

hi, thanks for your nice tool for NLP.
However, when I use transformers on MacOs to load Electra model I get an import error 

> ImportError: cannot import name 'TFElectraModel' from 'transformers'

How can I fix this issue?

**Comment by AhmedIdr** [comment]
Do you have the latest version of transformers ?

**Comment by jplu** [comment]
Hello !

Which version of the lib do you use?

**Comment by LiZongyue** [comment]
Hello!

I think it's a problem with your GPU rather than from transformers. Check your TensorFlow whether "Failed to load the native TensorFlow runtime." appears once it is imported.

**Comment by LysandreJik** [comment]
That's probably because you don't have `tensorflow>=2.0` installed while you're trying to load a TensorFlow model.
