### ISSUE TITLE
Provide simple way to train a new translation model from scratch

### ISSUE THREAD

**Issue by eraoul** [huggingface/transformers#4583]
# 🚀 Feature request

## Motivation

Huggingface just released a huge pile of pretrained translation models. I just want to train a completely custom model on a custom language pair, without pretraining etc.

**Comment by LysandreJik** [comment]
unstale

**Comment by Ferlix** [comment]
unstale

**Comment by ronaldvelzen** [comment]
@sshleifer I was wondering whether there is any activity on this issue. I have trained some models with MarianMT, but I am really interested in training a model from scratch with the transformers library.

**Comment by sshleifer** [comment]
This isn't supported by default, but is definitely possible.


Rough steps would be:
1) Make a local directory with your intialized model and tokenizer.

2) Run a command like [this](https://github.com/huggingface/transformers/blob/master/examples/seq2seq/train_distil_marian_enro.sh) where `$m` is the path your your local dir.

cc @patil-suraj

**Comment by CaterinaFabbri** [comment]
@sshleifer  could you please repost the command that the web-page does not exist anymore?

**Comment by sshleifer** [comment]
https://github.com/huggingface/transformers/blob/master/examples/research_projects/seq2seq-distillation/distil_marian_no_teacher.sh

**Comment by shizhediao** [comment]
unstale

**Comment by M4t1ss** [comment]
unstale
