### ISSUE TITLE
[Model hub web parsing MD code error]

### ISSUE THREAD

**Issue by mrm8488** [huggingface/transformers#4590]
# 🐛 Bug

## Information

Hi guys!
If you navigate to https://github.com/huggingface/transformers/blob/master/model_cards/mrm8488/bert-italian-finedtuned-squadv1-it-alfa/README.md

You will see the emojis without problem. But if you go to its HTML page on the model hub: https://huggingface.co/mrm8488/bert-italian-finedtuned-squadv1-it-alfa
Emojis are not shown

**Comment by julien-c** [comment]
Yes, that is a GitHub-only (GFM) feature, while we use marked.js (https://marked.js.org/) for markdown parsing.

You'll have to use the actual emojis for now
