### ISSUE TITLE
ImportError: cannot import name 'AutoModelForQuestionAnswering' from 'transformers 

### ISSUE THREAD

**Issue by OguzKircicek** [huggingface/transformers#4599]
Hi friends, 

I would like to use  transformers library. But while import I received this error. 

This code: 
```
from transformers import AutoTokenizer, AutoModelForQuestionAnswering, pipeline
import torch
 # LOAD MODEL
tokenizer = AutoTokenizer.from_pretrained("savasy/bert-base-turkish-squad")
model = AutoModelForQuestionAnswering.from_pretrained("savasy/bert-base-turkish-squad")

```
**Error**

**ImportError: cannot import name 'AutoModelForQuestionAnswering' from 'transformers' (C:\Users\oguzk\anaconda3\lib\site-packages\transformers\__init__.py)**

**Comment by LysandreJik** [comment]
What is your `transformers` version? Do you have PyTorch installed?

**Comment by OguzKircicek** [comment]
Thank you. I solved.

**Comment by LysandreJik** [comment]
Great to hear!

**Comment by AfaqHasanli** [comment]
> Thank you. I solved.

How did you solve it?

**Comment by OguzKircicek** [comment]
I installed pytorch library.
