### ISSUE TITLE
Which models can be using for encoder-decoder?

### ISSUE THREAD

**Issue by blizda** [huggingface/transformers#4601]
Hi, I trying to use EncoderDecoderModel. I tried google/electra-base-discriminator, google/electra-small-discriminator, albert-base-v2 as encoder and decoder:

```python
from transformers import EncoderDecoderModel

model = EncoderDecoderModel.from_encoder_decoder_pretrained('google/electra-small-discriminator', 'google/electra-small-discriminator')
```
but, I always gate the same error 

```python
TypeError: forward() got an unexpected keyword argument 'encoder_hidden_states'
```

Only Bert can be using as encoder and decoder? If so, can you add list of available models for encoder-decoder in documentation?

**Comment by mahajandiwakar** [comment]
@blizda did you find an answer to your query - "Only Bert can be using as encoder and decoder? If so, can you add list of available models for encoder-decoder in documentation?"?

**Comment by KarlaRehn** [comment]
There's an error-message saying which models can be used now; 
"... Model type should be one of CamembertConfig, XLMRobertaConfig, RobertaConfig, BertConfig, OpenAIGPTConfig, GPT2Config, TransfoXLConfig, XLNetConfig, XLMConfig, CTRLConfig, ReformerConfig, BertGenerationConfig, XLMProphetNetConfig, ProphetNetConfig."
