### ISSUE TITLE
`train.jsonl` file missing in MM-IMDb task

### ISSUE THREAD

**Issue by prabhakar267** [huggingface/transformers#4623]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Bert 

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: MM-IMDb
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Download the **raw** MM-IMDb dataset from http://lisi1.unal.edu.co/mmimdb/
2. Download `run_mmimdb.py` and `utils_mmimdb.py` from `/examples/contrib/mm-imdb`
3. Run the command given in [README.md](https://github.com/huggingface/transformers/blob/master/examples/contrib/mm-imdb/README.md#training-on-mm-imdb)

```
Traceback (most recent call last):
  File "run_mmimdb.py", line 614, in <module>
    main()
  File "run_mmimdb.py", line 555, in main
    train_dataset = load_examples(args, tokenizer, evaluate=False)
  File "run_mmimdb.py", line 339, in load_examples
    dataset = JsonlDataset(path, tokenizer, transforms, labels, args.max_seq_length - args.num_image_embeds - 2)
  File ".../mmimdb/utils_mmimdb.py", line 50, in __init__
    self.data = [json.loads(l) for l in open(data_path)]
FileNotFoundError: [Errno 2] No such file or directory: '.../mmimdb/dataset/train.jsonl'
```

## Expected behavior

+ `train.jsonl` should be present in the script directory

## Environment info

     
- `transformers` version:
- Platform: Linux
- Python version: Python 3.6.5
- PyTorch version (GPU?): `1.4.0` (yes)
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by rwikdutta** [comment]
It seems like this is the method to get the jsonl files: https://github.com/facebookresearch/mmbt/blob/master/scripts/mmimdb.py
