### ISSUE TITLE
Can't see logger output

### ISSUE THREAD

**Issue by parmarsuraj99** [huggingface/transformers#4624]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): RoBERTa

Language I am using the model on (English, Chinese ...): Sanskrit

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

Can't see logger output showing model config and other parameters in Trainer that were printed in training_scripts.

1. 
```
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./model_path",
    overwrite_output_dir=True,
    num_train_epochs=1,
    per_gpu_train_batch_size=128,
    per_gpu_eval_batch_size =256,
    save_steps=1_000,
    save_total_limit=2,
    logging_first_step = True,
    do_train=True,
    do_eval = True,
    evaluate_during_training=True,
    logging_steps = 1000
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    eval_dataset = valid_dataset,
    prediction_loss_only=True,
)
```
2.
```
%%time
trainer.train(model_path="./model_path")
```

Is it It is overriden by tqdm? 
but I can still see `Using deprecated `--per_gpu_train_batch_size` argument which will be removed in a future version. Using `--per_device_train_batch_size` is preferred.`

## Environment info

- `transformers` version: 2.10.0
- Platform: Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.6.0a0+916084d (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: TPU
- Using distributed or parallel set-up in script?: No

**Comment by LysandreJik** [comment]
Hi, have you tried setting the logging level to `INFO`? You can do so with the following lines:

```py
import logging

logging.basicConfig(level=logging.INFO)
```

**Comment by parmarsuraj99** [comment]
It worked! Thanks

**Comment by jawadSajid** [comment]
Hey, this doesn't log the training progress by trainer.train() into a log file. I want to keep appending the training progress to my log file but all I get are the prints and the parameters info at the end of trainer.train(). What would be a way around to achieve this? @parmarsuraj99 @LysandreJik
