### ISSUE TITLE
How to use run_glue.py with tensorboard?

### ISSUE THREAD

**Issue by ayrtondenner** [huggingface/transformers#4626]
# ❓ Questions & Help

I'm running `run_glue.py` script, where I added a new task_name in `data/metrics` and `data/processors`. The training happens OK, the checkpoints are being saved, but no tfevent file is being written. Shouldn't it be written in checkpoints folder during training?

**Comment by LysandreJik** [comment]
What `--logging_dir` have you specified to the `run_glue.py` script?

**Comment by Daromog** [comment]
I'm having this problem how do you fixed this?
I put the direction to the folder to --logging_dir but nothing is written there

**Comment by Daromog** [comment]
> What `--logging_dir` have you specified to the `run_glue.py` script?

I'm having this problem how do you fixed this?
I put the direction to the folder to --logging_dir but nothing is written there
