### ISSUE TITLE
Model evaluated at each checkpoint, but results not in checkpoint file

### ISSUE THREAD

**Issue by CMobley7** [huggingface/transformers#4630]
# ❓ Questions & Help

I start `run_language_modeling.py` and `run_glue.py` with `--do_eval` and `--evaluate_during_training` arguments. While it checkpoints and evaluates the model at each saving step, the evaluation results are not output to the checkpoint folder but merely the terminal at each saving step, as well as logging step. However, the final model is evaluated and its results placed in the appropriate location. I'd like the performance of each checkpoint. Am I doing something wrong? Is there an additional argument I must specify?

**Comment by CMobley7** [comment]
What is the proper way to get an `eval.txt` file for each checkpoint?

**Comment by julien-c** [comment]
No, this is not a built-in feature. I'd suggest you install from source and modify the code directly. 

The code in this repo is meant to be optimized for "hackability", feel free to open a new issue if needed.
