### ISSUE TITLE
Error when loading a trained Encoder-Decoder model. 

### ISSUE THREAD

**Issue by Xunzhuo** [huggingface/transformers#4640]
# 🐛 Bug Report
When loading the config the in configuration_auto.py the model_type is expected on the form encoder-decoder 
but in configuration_encoder_decoder.py 
model_type is on the form encoder_decoder which raises a KeyError.

**Comment by patrickvonplaten** [comment]
Hi @Xunzhuo,
Multiple bugs were fixed in #4680 . Can you please take a look whether this error persists?

**Comment by Xunzhuo** [comment]
okay tks!
