### ISSUE TITLE
Write With Transformer: PPLM page is broken

### ISSUE THREAD

**Issue by songproducer** [huggingface/transformers#4661]
# 🐛 Bug 

Triggering autocomplete results in endless spinning.

iOS safari But also desktop Safari, Firefox and Chrome.

**Comment by BramVanroy** [comment]
I cannot reproduce your problem. Can you try again?

**Comment by songproducer** [comment]
I tried again. 

Console on dev tools shows:

```
DevTools failed to load SourceMap: Could not load content for chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/contentScript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/pageHook.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by BramVanroy** [comment]
Those are unrelated warnings related to source maps. I can;t reproduce your problem and I tried on different browsers. Can you clear the cache/try in private mode/incognito?

**Comment by songproducer** [comment]
<img width="2543" alt="Screen Shot 2020-06-01 at 1 50 50 am" src="https://user-images.githubusercontent.com/597346/83359074-6acfea00-a3aa-11ea-97e9-d9fa0ed872ea.png">
Still no luck

**Comment by BramVanroy** [comment]
D'oh, I didn't check the PPLM page. The other versions of Write With Transformer seem to work, but you are right that it doesn't seem to work for [PPLM](https://transformer.huggingface.co/doc/pplm). When you trigger "autocomplete", the web page seems to hang.

cc @julien-c

**Comment by julien-c** [comment]
Yes, we turned off the PPLM machine as it was costly to host. We need to add a notice to try it locally instead, and/or re-spawn a cheaper machine. Both are on my todo-list.

**Comment by julien-c** [comment]
Added a notice there: https://transformer.huggingface.co/doc/pplm
