### ISSUE TITLE
End-to-end object detection with Transformers

### ISSUE THREAD

**Issue by parmarsuraj99** [huggingface/transformers#4663]
# 🚀 Feature request

A modular Transformer Encoder-Decoder block that can be attached to ConvNets for many tasks.

## Motivation
As shown in the recent paper [End-to-end Object Detection with Transformers](https://ai.facebook.com/research/publications/end-to-end-object-detection-with-transformers) which used Transformer for Object Detection. [https://github.com/facebookresearch/detr](https://github.com/facebookresearch/detr)

**Comment by BramVanroy** [comment]
I might be wrong, but I think the focus of this library is on NLP which at most is multimodel. Also including object detection transformers may fall out of the scope of this project.
