### ISSUE TITLE
Coversion between tokenizers

### ISSUE THREAD

**Issue by imbalu007** [huggingface/transformers#4670]
I want to convert GPT2 tokens to BERT tokens. Is there any API that can directly convert between the Tokenizers?

**Comment by LysandreJik** [comment]
GPT-2 and BERT have very different tokenization mechanism. What do you mean by "convert between the tokenizers"? What do you want to do?

**Comment by imbalu007** [comment]
I want to use Bert as encoder and GPT2 as decoder. Then I want to evaluate the generated text with another Bert as discriminator like [this](https://arxiv.org/pdf/1703.00955.pdf)
