### ISSUE TITLE
get_from_cache in file_utils.py gobbles up error in making url requests

### ISSUE THREAD

**Issue by SinghB** [huggingface/transformers#4671]
# 🐛 Bug
No information from the package on SSL error encountered, making it difficult to troubleshoot or figure out a workaround

## Information
When trying to do:
`TFAutoModelWithLMHead.from_pretrained("t5-small")`

Get an error:
`TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

The above is a result of an SSL error encountered when trying to fetch the model, however, since the exception handling isn't proper within file_utils.py I don't come to know of it, unless I debug.

Model I am using (Bert, XLNet ...): T5

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

https://huggingface.co/transformers/usage.html#summarization

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ x] my own task or dataset: (give details below)
Just getting familiar with transformers for summarization

## To reproduce
You need a machine with an expired certificate for proxy etc.

1. See information above

## Expected behavior
If there has been an issue in fetching the pre-trained model from s3 bucket etc. I should get an error to that effect.

## Environment info

     
- `transformers` version: 2.10.0
- Platform: Windows 10
- Python version: 3.7.4
- PyTorch version (GPU?): NA
- Tensorflow version (GPU?): 2.0.0 (Yes)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by stadelmanma** [comment]
Ran into this today, this is a major issue behind corporate proxy/CA self signed certs. @SinghB  maybe you can reopen this, I'm not sure who to `@mention`?

```python
get_from_cache(
  # ...
  etag = None
    if not local_files_only:
        try:
            response = requests.head(url, allow_redirects=True, proxies=proxies, timeout=etag_timeout)
            if response.status_code == 200:
                etag = response.headers.get("ETag")
        except (EnvironmentError, requests.exceptions.Timeout):
            # etag is already None
            # THIS ALSO SWALLOWS ALL OTHER NON "404" ERRORS (e.g. SSL, Proxy, etc.)
            pass
  # ....
```

**Comment by julien-c** [comment]
Yes I want to track and solve that issue in the next couple of weeks.

**Comment by dconathan** [comment]
+1 from me.

Currently I get this error message:

```OSError: Can't load weights for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-uncased' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.```

But if I add a `raise` after the `# etag is already None` comment in stadelmanma's snippet, I see:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='cdn.huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased-pytorch_model.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
```

**Comment by gcolmen** [comment]
Hi, I'm having the same issue as @stadelmanma (I'm behind a coporate proxy as well)

```  File "/home/USER/anaconda3/envs/codebert/lib/python3.7/site-packages/transformers/configuration_utils.py", line 376, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/USER/anaconda3/envs/codebert/lib/python3.7/site-packages/transformers/configuration_utils.py", line 436, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'microsoft/deberta-base'. Make sure that:

- 'microsoft/deberta-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'microsoft/deberta-base' is the correct path to a directory containing a config.json file
```
I even tried setting the proxy in `proxies`: 
```config = config_class.from_pretrained(args.config_name, proxies={'http://': '<HOST>:<PORT>'})```

But same thing happens. 
Maybe there's a workaround for this?

Many thanks!
