### ISSUE TITLE
Gpt2 generation of text larger than 1024

### ISSUE THREAD

**Issue by rautnikita77** [huggingface/transformers#4675]
# ❓ Questions & Help

## Details

I know the context supported by GPT2 is 1024, but I assume there's some technique they utilized to train and generate text longer than that in their results. Also, I saw many gpt2-based repos training text with length longer than 1024. But when I tried generating text longer than 1024 it throws a runtime error :The size of tensor a (1025) must match the size of tensor b (1024) at non-singleton dimension 3. I have the following questions:
1) Shouldn't it be possible to generate longer text since a sliding window is used?
2) Can you please explain what's necessary to generate longer text? What changes will I have to make to the run_generation.py code?

**Comment by thesamuel** [comment]
I'm not sure if sliding window is implemented in `modeling_utils.generate` (the function used for generation by `run_generation.py`.

This approach is implemented by CTRL, so you may be able to adapt some of the code from their repo for your use case: https://github.com/salesforce/ctrl/blob/master/generation.py#L186-L189

**Comment by minimaxir** [comment]
The iterative approach to generation (using `past`) may work better because you can control the sliding window manually.

**Comment by benlebrun** [comment]
@patrickvonplaten @rautnikita77 @minimaxir Has anyone attempted to implement this (using cached keys and values)?
