### ISSUE TITLE
Documentation for non-nlp experts

### ISSUE THREAD

**Issue by falconair** [huggingface/transformers#4677]
# 🚀 Feature request

## Motivation 
I want to use these models as an end-user, without having to read academic papers describing them.

I have been following deep learning in the field of computer vision, had no idea that NLP had advanced SO much (for me, Word2vec is still state of the art).

At work I have large amounts of text: articles, transcripts from voice and chat, chatbot exchanges, etc. I would love to Try out the functionality provided by the contributors here, but the documentation seems to assume one already know which models to use.

Perhaps someone can write a “Modern NLP for technical managers” type post (or link to an existing one).

I’m excited by the immense amount of work done here, but will have to start all the way back with RNNs and work my way up to this stuff. Hoping to be able to use this stuff without that detour!

**Comment by flozi00** [comment]
Since no one else answers this:
Check out the simpletransformers library, it's and wrapper of this one and there are some blog posts linked to examples.
https://github.com/ThilinaRajapakse/simpletransformers
The author is very open to every idea and the work with him is pretty good.
Maybe it will help you.
For most common tasks the distilroberta model gives good results and doesn't need as much computing power as longformer or t5 needs

**Comment by falconair** [comment]
Thanks for the link, very helpful. I’m also finding that if I know what I need to do and which model to use, the API docs do have well coded examples.

**Comment by flozi00** [comment]
If you don't know which model to use you can even just checkout the model hub.
For example for question answering tasks just search for "squad" models, then you will find a lot of pretrained models for this task

**Comment by BramVanroy** [comment]
> Since no one else answers this:

I marked this question as a "Good First Issue". The idea is that we encourage people who are new to contributing to add their input. Particularly, you can add new examples that are very entry-level to explain the basic principles of the library.

**Comment by srush** [comment]
@falconair Thanks for raising this issue. We think we can make things better here.

If any one is interested in helping out, let me know. In particular it would be helpful to have examples of (non-nlp) projects that do this well. We could also use some beta testers.

**Comment by BramVanroy** [comment]
> @falconair Thanks for raising this issue. We think we can make things better here.
> 
> If any one is interested in helping out, let me know. In particular it would be helpful to have examples of (non-nlp) projects that do this well. We could also use some beta testers.

Ping me if you need beta testers. I can test for Windows, Linux, Linux DDP.
