### ISSUE TITLE
Loading config file bug

### ISSUE THREAD

**Issue by abryeemessi** [huggingface/transformers#4696]
Hi guys.

I have released a new (XLNet based) transformer model for low-resource language Tigrinya 
 [(TigXLNet)](https://github.com/abryeemessi/Transferring-Monolingual-Model-to-Low-Resource-Language)  and found a bug when loading a pre-trained config file: 

My config file looks like:
https://s3.amazonaws.com/models.huggingface.co/bert/abryee/TigXLNet/config.json

       config = AutoConfig.from_pretrained("abryee/TigXLNet")
       print(config.d_head) #prints 48 even though d_head in the given config file is 64.

**Comment by LysandreJik** [comment]
Hello! The `d_head` is actually computed in the configuration: `self.d_head = d_model // n_head`. 

It would probably be better to handle `d_head` directly, but currently the `d_model` and `d_head` are linked to each other. 

This would crash in your case as  `d_model // n_head != d_head`

**Comment by abryeemessi** [comment]
@LysandreJik Thanks a lot. Yes, I am setting d_head directly before loading my model. But it would be nice to see the model load its configuration from the given config file. Just my opinion though :)
