### ISSUE TITLE
How tokenizers work

### ISSUE THREAD

**Issue by Aktsvigun** [huggingface/transformers#4707]
Good afternoon. 
If possible, I would ask a few questions which I cannot solve for several days running.

1) What does the file _merge.txt_ mean which is used in `ByteLevelBPETokenizer`? Does it store the config for the tokenizer? I deepened into it, however, did not manage to understand its purpose.
2) Is it possible to get offsets for the text when using models-stacked tokenizers? For instance, I am using ElectraTokenizer and I would like it to return the offsets for my texts - do you probably have any templates of how to do it?

Thanks in advance!

**Comment by LysandreJik** [comment]
pinging @n1t0, lead on [huggingface/tokenizers](https://github.com/huggingface/tokenizers) :)

**Comment by Aktsvigun** [comment]
Thank you! Closing it here.
