### ISSUE TITLE
Is there any need to fine-tune the already pre-trained GPT-2 models?

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#4713]
Hello,

If I am using the pre-trained GPT-2 for my research, should I still fine-tune the already pre-trained models with my dataset? I am a bit confused by the term "pre-trained".

Thank you,

**Comment by minimaxir** [comment]
"Finetuning" a GPT-2 model is generally used for generation, to make it output text more similar to a given dataset.

If you are using it for other tasks (e.g. binary predictions), you may not have to finetune it.

**Comment by h56cho** [comment]
Hello,

Thank you for your reply.
So say if I am trying to solve multiple choice questions with GPT2DoubleHeadsModel, I can just use the pre-trained model without fine-tuning?

Will it jeopardise the overall analysis if I still choose to fine-tune the GPT2DoubleHeadsModel before processing the multiple choice questions onto my dataset?

Thanks,
