### ISSUE TITLE
About `do_basic_tokenize` behavior in BertTokenizer

### ISSUE THREAD

**Issue by GuillemGSubies** [huggingface/transformers#4719]
# ❓ Questions & Help

In the [docs](https://huggingface.co/transformers/model_doc/bert.html?highlight=basic%20tokenization#berttokenizer) it just says that it performs a basic tokenization before the word piecer. But what is actually a "basic tokenization"? I would really appreciate a little more of information on that.

Diving into the code I found out that the basic tokenization removes control characters from the text. I did not expect that behavior from what I read on the docs. That gave us problems because some characters like `` weren't tokenizing and we didn't know why.

More generally I think that transformers has a problem with the docs. Most of the times that something does not work for me, I don't bother to look at them and I directly dive into the source code in order to understand what's happening. I am used to scikit-learn and maybe I am a bit bisaed, but I really think that these kind of things can be a barrier for new people wanting to use transformers.

If there is something I can do to help, I am happy to send a PR.

**Comment by sralvins** [comment]
there is a `BasicTokenizer` in previous `pytorch_transformers` package:
![image](https://user-images.githubusercontent.com/24619551/178862459-31bdbb45-abda-4e36-a94d-a85b89734604.png)
This must be what "basic tokenize" does
