### ISSUE TITLE
TFTrainer: Checkpoints not getting saved in `output_dir` but in {cwd}/checkpoint

### ISSUE THREAD

**Issue by 0dust** [huggingface/transformers#4734]
I am using TFTrainer for the SQuAD task.
Checkpoints are being created in cwd/checkpoint insted of output_dir.

**Potential Cause:**
https://github.com/huggingface/transformers/blob/9ca485734aea269961d63a040ff194365d151fd1/src/transformers/trainer_tf.py#L156
Instead of PREFIX_CHECKPOINT_DIR we need to have
```python
os.path.join(self.args.output_dir, PREFIX_CHECKPOINT_DIR)
```

**Comment by jplu** [comment]
@0dust This is the intent behavior :)

**Comment by 0dust** [comment]
@jplu Sorry if i am missing something but isn't 'output_dir' the folder to save the checkpoint?
https://github.com/huggingface/transformers/blob/ed4df85572924871758ca32133b46116121c706f/src/transformers/training_args.py#L41-L43

**Comment by jplu** [comment]
Not for the TF one, it is one of the few difference between the both trainers.

**Comment by 0dust** [comment]
Ohh,  I see!  Thanks for the clarification. Just a quick question before i close the issue,  Is there any specific reason for this?  Or it's just a matter of time before it starts to behave similar to pytorch trainer.

**Comment by jplu** [comment]
It is just matter of time :)
