### ISSUE TITLE
Extending run_language_modeling.py for XLNet

### ISSUE THREAD

**Issue by shngt** [huggingface/transformers#4739]
# 🚀 Feature request

The run_language_modeling.py script in examples/language-modeling/ currently works for BERT, RoBERTa, GPT and related models. It would be helpful if it also allowed XLNet. I believe this would involve writing functions to generate `perm_mask`, `target_mapping` and `labels` for the inputs sequences as per the paper and `https://github.com/zihangdai/xlnet/blob/master/data_utils.py`, but I'm not a 100% sure about this.  

## Motivation

I have to adapt XLNet onto a specialized domain (finance) and am yet to find a decent guide or implementation which discusses how to do this. I've decided to do this myself (with the help of this library), and would like to share my code in case others find it useful.

## Your contribution

Since I will be trying to do this anyway, I would like to submit a relevant PR when it is done. I was also hoping to receive guidance or feedback as appropriate by other contributors to ensure correctness and utility.

**Comment by patrickvonplaten** [comment]
See also https://github.com/huggingface/transformers/issues/2008

**Comment by krannnn** [comment]
@shngt can you please share your code for adaptind xlnet to the domain specific data ? 
I was following the latest changes to transformers but I still don't understand how to continue training xlnet on the domain specific data.
thanks

**Comment by matthiaslmz** [comment]
@shngt @krannnn Are there any updates on this? I'm interested as well (: Thanks!

**Comment by shngt** [comment]
@matthiaslmz @krannnn afair we just ran the example script on our dataset (a large text file) with the appropriate flags. Are you facing any specific issues? I could try investigating and getting back to you.

**Comment by shngt** [comment]
@matthiaslmz @krannnn I'm afraid I no longer have the cli command I used to run the example script, but I think it was quite similar to what's given in the docs. Are you facing some specific issue?
