### ISSUE TITLE
Can't find config.json

### ISSUE THREAD

**Issue by mustafameruyert** [huggingface/transformers#4740]
# ❓ Questions & Help

Hello!When I use transformers I get this error Make sure that 'mrm8488/bert-multi-cased-finetuned-xquadv1' is the correct path to a directory containing a config.json file.How to solve it?

**Comment by patrickvonplaten** [comment]
Hi @mustafameruyert, please poste a codesnippet so that we can reproduce the error

**Comment by mustafameruyert** [comment]
> Hi @mustafameruyert, please poste a codesnippet so that we can reproduce the error
![1](https://user-images.githubusercontent.com/43790316/83646412-6afffd80-a5d5-11ea-89d2-0ea80b14adff.png)
![1](https://user-images.githubusercontent.com/43790316/83646625-b87c6a80-a5d5-11ea-942f-399147acc1d4.png)
I am using dockers and this is error

**Comment by mustafameruyert** [comment]
> Hi @mustafameruyert, please poste a codesnippet so that we can reproduce the error

Sorry I forgot to uncomment first two lines of nevertheless it shows  same error and instead of distilbert-base-cased I use bert-multi-cased-finetuned-xquadv1

**Comment by patrickvonplaten** [comment]
It would be great if you could copy-paste code like this:

```python 
from transformers import pipeline
answerer = pipeline("question-answering", model="mrm8488/bert-multi-cased-finetuned-xquadv1", tokenizer="mrm8488/bert-multi-cased-finetuned-xquadv1")

answerer(context="The dog is blue", question="Which color is the dog?")['answer']
```

so that one can just copy-paste it and does not have to type it manually from a screenshot.

The following code works as well:

```python 
from transformers import pipeline, AutoModelForQuestionAnswering, AutoTokenizer
answerer = pipeline("question-answering", model=AutoModelForQuestionAnswering.from_pretrained("mrm8488/bert-multi-cased-finetuned-xquadv1"), tokenizer=AutoTokenizer.from_pretrained("mrm8488/bert-multi-cased-finetuned-xquadv1"))
answerer(context="The dog is blue", question="Which color is the dog?")['answer']
```

Let me know if this does not fix your problem :-)

**Comment by mustafameruyert** [comment]
@patrickvonplaten  I tried to run your code but it also show this error
![1](https://user-images.githubusercontent.com/43790316/83657571-d56b6a80-a5e2-11ea-85ab-cb71ef43fb44.png)

**Comment by patrickvonplaten** [comment]
It looks like the problem is that you cannot create a folder called `/.cache` , which has nothing to do with the pipeline. You should have sudo rights from your home folder. 

To solve this you could:
```
sudo mkdir /.cache
```

and then make sure that `/.cache` has the correct permission rights. The error is a bit out of scope for this issue. 

It would be important to make sure that you have the correct sudo rights.

**Comment by mustafameruyert** [comment]
> It looks like the problem is that you cannot create a folder called `/.cache` , which has nothing to do with the pipeline. You should have sudo rights from your home folder.
> 
> To solve this you could:
> 
> ```
> sudo mkdir /.cache
> ```
> 
> and then make sure that `/.cache` has the correct permission rights. The error is a bit out of scope for this issue.
> 
> It would be important to make sure that you have the correct sudo rights.

Thank you for response I will try to fix it
