### ISSUE TITLE
Perform evaluation on HANS with Trainer (like GLUE example)

### ISSUE THREAD

**Issue by prajjwal1** [huggingface/transformers#4742]
Current [HANS](https://github.com/huggingface/transformers/tree/master/examples/adversarial) evaluation implementation is carried out in the old way. It'd be good to do it in the same manner as other examples are implemented now with the Trainer class.

**Comment by julien-c** [comment]
Maybe @sgugger would be interested in taking a look at this

**Comment by prajjwal1** [comment]
There is an evaluation issue that I faced with [HANS evaluation](https://github.com/huggingface/transformers/issues/4766). I tried to run in the exact same manner as listed in `examples/adversarial`. But the results obtained seem skewed for some reason. If @sgugger can point some possible reason out, I can work on it and send a PR.
