### ISSUE TITLE
How to use pretrained model for inference?

### ISSUE THREAD

**Issue by andrster** [huggingface/transformers#4744]
I have a bert model finetuned for pytorch and have trouble actually using it. Like how can I get to model("<some sentance>") outputting results for the tokens?

**Comment by patil-suraj** [comment]
Hello @andrster 
Which model are you trying ? for ex, for QA, token classification, sentence classification etc.
Please elaborate more.

**Comment by andrster** [comment]
Sorry, token classification

**Comment by rosenjcb** [comment]
@andrster have you checked out the pipelines section of the README?

**Comment by andrster** [comment]
doesn't have one on NER

**Comment by patil-suraj** [comment]
@andrster 
ner pipeline is available in Transformers. Check here https://huggingface.co/transformers/usage.html#named-entity-recognition
