### ISSUE TITLE
Tokenizer.encode documentation not correct

### ISSUE THREAD

**Issue by lubok-dot** [huggingface/transformers#4750]
# 🐛 Bug

## Information

Model I am using Bert (bert-base-german-cased):

Language I am using the model on German:

The problem arises when using:
* tokenizer of this model

The tasks I am working on is:
* encoding

## To reproduce

1. lang_model = 'bert-base-german-cased'
2. tokenizer = BertTokenizer.from_pretrained(lang_model)
3. test_sentence = 'Das war gut'
4. tokenizer.encode(test_sentence)
output: [3, 295, 185, 1522, 4]
5. tokenizer.convert_tokens_to_ids(tokenizer.tokenize(test_sentence))
output: [295, 185, 1522]

## Expected behavior

According to the documentation of the encoding method in

https://huggingface.co/transformers/main_classes/tokenizer.html 

these two outputs should be the same. The problem is, that the _encode_ method adds special tokens [CLS] and [SEP] at the beginning and the end. However, the transformation in line 5. does not. This is not a problem at all but one should consider correcting the online-documentation. That is, the hint 

**Same as doing self.convert_tokens_to_ids(self.tokenize(text))**

in the encode method is misleading. Instead, one could also add, that these two commands are the same if _add_special_tokens_ is set _False_ in the _encode_ method.

## Environment info
     
- `transformers` version: 2.8.0
- Platform: Windows 10
- Python version: 3.8.3
- PyTorch version (GPU?): 1.5.0+cpu
- Tensorflow version (GPU?): None
- Using GPU in script?:No
- Using distributed or parallel set-up in script?:No

**Comment by LysandreJik** [comment]
You're right! The documentation should be updated.

**Comment by LysandreJik** [comment]
Done! Thanks for raising an issue :)

**Comment by lubok-dot** [comment]
You are welcome. Thank you for the transformers package -- great work!

**Comment by LysandreJik** [comment]
@ank-shukla the response given by @lubok-dot is correct, the `call` method should be used instead of `encode` and `encode_plus` in newer versions. If you're on an older version or would still like to use said methods, please check an older version of the documentation, for example [v2.11.0](https://huggingface.co/transformers/v2.11.0/main_classes/tokenizer.html#transformers.PreTrainedTokenizer.encode_plus)

**Comment by ank-shukla** [comment]
@lubok-dot @LysandreJik Thanks for the clarification. I am on the new version and the said methods encode and encode_plus still work as expected. I understand now that __call__ method can carry out the same process based on the parameters.
