### ISSUE TITLE
Fine-tuning of RoBERTa

### ISSUE THREAD

**Issue by Aktsvigun** [huggingface/transformers#4760]
Good afternoon,
I'm trying to fine-tune RoBERTa on my own dataset, following the instruction provided here [https://huggingface.co/transformers/v1.2.0/examples.html](url). However, I cannot find the file `run_lm_finetuning.py` - could you please clarify, is the instruction valid or the file has really been deleted? Thanks in advance!

Be safe,
Akim

**Comment by patil-suraj** [comment]
Hello @Aktsvigun 
To run the examples you'll need to clone the transformer repo. All examples can be found in examples directory.  You can find `run_lm_finetuning` here.
run_language_modeling.py
https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py

**Comment by Aktsvigun** [comment]
@patil-suraj  thank you for your response,
feel a bit dummy, is the function name changed to run_language_modeling? 😹
Cannot find the name `run_lm_finetuning` on the page itself.
<img width="1228" alt="Снимок экрана 2020-06-04 в 16 57 00" src="https://user-images.githubusercontent.com/36672861/83765910-6b0b0680-a684-11ea-8ff6-6ba29f833870.png">

Be safe,
Akim

**Comment by LysandreJik** [comment]
Hi @Aktsvigun, the documentation you're linking is for `transformers` v1.2.0. If you want to run `v1.2.0` scripts, you should look at the [tag v1.2.0](https://github.com/huggingface/transformers/tree/1.2.0/examples).

Please note that the latest scripts are more stable. As @patil-suraj said, the script you're looking for was renamed, as you can see in the [current documentation](https://huggingface.co/transformers/examples.html).
