### ISSUE TITLE
GPT2TokenizerFast raises pad_token error even if not used

### ISSUE THREAD

**Issue by tomhosking** [huggingface/transformers#4764]
# 🐛 Bug

## Information

Model: GPT2

Language: English

Encoding with the `GPT2TokenizerFast` causes a `pad_token` error to be sent to stderr, despite not attempting to access that property.

## To reproduce

```import transformers
from transformers import GPT2TokenizerFast

tokenizer = GPT2TokenizerFast.from_pretrained('gpt2')

res = tokenizer.encode("This is a sentence")

print(transformers.__version__)
```

Output:
```
Using pad_token, but it is not set yet.
2.11.0
```

## Expected behavior

I'm aware that GPT-2 doesn't include a pad token (#2630) - I haven't tried to use it. I would expect no error to be displayed until I try to access that property.

## Environment info

- `transformers` version: 2.11.0
- Platform: Ubuntu
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.0 with CUDA
- Tensorflow version (GPU?): n/a
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by sgugger** [comment]
I can reproduce and think I've found the cause, working on this.
