### ISSUE TITLE
 Cannot load pretrained model from repo.

### ISSUE THREAD

**Issue by jordaniac89** [huggingface/transformers#4765]
Hi, I'm trying to load a model from the repository:

```
tokenizer = AutoTokenizer.from_pretrained("NeuML/bert-small-cord19-squad2")
model = AutoModelForQuestionAnswering.from_pretrained("NeuML/bert-small-cord19-squad2")
```
but I'm receiving the error:
`OSError: Model name 'NeuML/bert-small-cord19-squad2' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed 'NeuML/bert-small-cord19-squad2' was a path or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.
`

I've tried a few other models with the same result. The vocab.txt file is there in each of them. Am I missing something?

EDIT: Current libraries -
beautifulsoup4==4.9.1
boto3==1.10.30
botocore==1.13.30
certifi==2019.11.28
chardet==3.0.4
Click==7.0
docutils==0.15.2
fsspec==0.6.1
future==0.18.2
html2text==2020.1.16
idna==2.8
jmespath==0.9.4
joblib==0.14.0
nltk==3.4.5
numpy==1.17.4
pandas==0.25.3
Pillow==7.1.2
python-dateutil==2.8.0
pytz==2019.3
regex==2019.11.1
requests==2.22.0
s3fs==0.4.0
s3transfer==0.2.1
sacremoses==0.0.35
scikit-learn==0.21.3
scipy==1.3.2
sentencepiece==0.1.83
six==1.13.0
soupsieve==2.0.1
torch==1.5.0
torchvision==0.6.0
tqdm==4.40.0
transformers==2.2.0
urllib3==1.25.7
wikipedia==1.4.0

**Comment by patil-suraj** [comment]
Hello @jordaniac89  I just tried this, and it worked. Can you try this again ?

**Comment by jordaniac89** [comment]
Yeah, nothing. My assumption was that from_pretrained() should reach out to s3 and download the model if it can't find it?

**Comment by LysandreJik** [comment]
Glad you could solve the issue!
