### ISSUE TITLE
Correcting path to pplm examples

### ISSUE THREAD

**Issue by Mr-Ruben** [huggingface/transformers#4776]
# 🐛 Bug

On https://github.com/huggingface/transformers/tree/master/examples/text-generation/pplm#setup

It says

```
git clone https://github.com/huggingface/transformers && cd transformers
pip install .
pip install nltk torchtext # additional requirements.
cd examples/pplm


```

and as you can guess from the url, the correct path is

```
git clone https://github.com/huggingface/transformers && cd transformers
pip install .
pip install nltk torchtext # additional requirements.
cd examples/text-generation/pplm
```

cd examples/**text-generation**/pplm

**Comment by julien-c** [comment]
Thanks for the report – care to open a PR?

**Comment by Mr-Ruben** [comment]
Done
https://github.com/huggingface/transformers/pull/4778

I hope it is done well.
