### ISSUE TITLE
question about tokenizer

### ISSUE THREAD

**Issue by yuimo** [huggingface/transformers#4783]
hi, is there any difference between initializing BertTokenizer and load it using from_pretrained, 
such as:
1、tokenizer = BertTokenizer(bert-base-uncased-vocab)
2、tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

i want to pretrain for some new language by myself, so i need to create the vocabulary, and how could i integrate it to the transformers's tokenizer
thanks a lot!

**Comment by patil-suraj** [comment]
This notebook might help you, it shows how you can train a LM from scratch on a new language.
https://github.com/huggingface/blog/blob/master/notebooks/01_how_to_train.ipynb

**Comment by yuimo** [comment]
@patil-suraj thanks for your reply. i have read this notebook. but i want to re-use the functions in the transfomers such as functions like encode_plus, batch_encode_plus
so my question is :
after train a tokenizer by myself, how could i integrate it to the transformers's tokenizer to use functions in it?
thanks again
