### ISSUE TITLE
Question Answering Pipeline with big texts.

### ISSUE THREAD

**Issue by thiagomoeng** [huggingface/transformers#4785]
# ❓ Questions & Help

I am searching for some ideas of how to use QA pipeline with big data texts and get a good time response. (I am already using GPU)

**Comment by patrickvonplaten** [comment]
Longformer would be a good choice, but it is currently not implemented in the pipelines. This issue might help :-) : https://github.com/huggingface/transformers/issues/4762

**Comment by patrickvonplaten** [comment]
and #4615
