### ISSUE TITLE
Write With Transformer Request:

### ISSUE THREAD

**Issue by zanderbush** [huggingface/transformers#4797]
# 🚀 Feature request

I understand if this is unattainable for reason of money, but I was wondering if you could replace three autocomplete suggestions with five.

**Comment by julien-c** [comment]
This wouldn't change the unit economics of providing this service, but I'm curious, why don't you press tab twice instead?

**Comment by zanderbush** [comment]
The previous suggestions disappear after I press tab. 

It is easier to pick an autocompletion that is suitable, the more options I have to compare.
