### ISSUE TITLE
pip install -e does not always install the correct isort version

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#4801]
```bash
pip install -e .["dev"]
make quality
```
### Output
```bash
black --check --line-length 119 --target-version py35 examples templates tests src utils
All done! ✨ 🍰 ✨
306 files would be left unchanged.
isort --check-only --recursive examples templates tests src utils
ERROR: /Users/shleifer/transformers_fork/examples/benchmarking/plot_csv_file.py Imports are incorrectly sorted.
ERROR: /Users/shleifer/transformers_fork/templates/adding_a_new_example_script/run_xxx.py Imports are incorrectly sorted.
ERROR: /Users/shleifer/transformers_fork/templates/adding_a_new_example_script/utils_xxx.py Imports are incorrectly sorted.
ERROR: /Users/shleifer/transformers_fork/src/transformers/__init__.py Imports are incorrectly sorted.
make: *** [quality] Error 1
```
relevant packages: 
```python
flake8==3.8.1
isort==4.3.21
black==19.10b0
```

Env:
```
- `transformers` version: 2.11.0
- Platform: Darwin-19.4.0-x86_64-i386-64bit
- Python version: 3.7.5
- PyTorch version (GPU?): 1.5.0 (False)
- Tensorflow version (GPU?): 2.2.0 (False)
```

Would also be good to add more verbose error messages if possible

**Comment by sshleifer** [comment]
@LysandreJik @julien-c any ideas?

**Comment by julien-c** [comment]
Works for me, no issues. But `isort==4.3.21` is not precise enough, you need to have the actual precise commit.

Can you try `pip uninstall isort && pip install git+git://github.com/timothycrosley/isort.git@e63ae06ec7d70b06df9e528357650281a3d3ec22#egg=isort`
?

**Comment by sshleifer** [comment]
That worked! 
but my pip freeze still says 
```
isort==4.3.21
```

which seems like the reason that 
```bash
pip install -e .["dev"]
```
didn't work.

**Comment by julien-c** [comment]
pip is confusing, but you technically have version "4.3.21" of isort if you install from the specified commit – but not **the** version "4.3.21".

i.e. the version number in the setup.py of the package that you install from git is still the string "4.3.21".

Do you see what I mean?

**Comment by sshleifer** [comment]
Yes I think I do, rephrase: there are multiple different versions of isort called 4.3.21 and pip install -e . will be satisfied if you have any of them, so if you have the wrong one you have to manually run
```bash
pip uninstall isort
pip install git+git://github.com/timothycrosley/isort.git@e63ae06ec7d70b06df9e528357650281a3d3ec22#egg=isort
```

**Comment by julien-c** [comment]
Yep
