### ISSUE TITLE
Question: Where do I find the Transformer model from the paper "Attention is all you need" ?

### ISSUE THREAD

**Issue by abhisheksgumadi** [huggingface/transformers#4817]
Hello

  Firstly, thanks for supporting all questions here.

I read the paper "Attention is all you need" and wondering which class should I use in the HuggingFace library to use the Transformer architecture used in the paper.

Can you please advise?

Thanks
Abhishek

**Comment by BramVanroy** [comment]
You don't need this library if you want the transformer module specifically.

PyTorch: https://pytorch.org/docs/master/generated/torch.nn.Transformer.html
TensorFlow: https://www.tensorflow.org/tutorials/text/transformer#create_the_transformer

**Comment by abhisheksgumadi** [comment]
Thanks @BramVanroy
