### ISSUE TITLE
GlossBert adding

### ISSUE THREAD

**Issue by Oxi84** [huggingface/transformers#4833]
Here is a link https://github.com/HSLCY/GlossBERT - it should be able to do better for word vectors representations and there is already pretrained model than maybe need to be converted to a different format.

**Comment by Oxi84** [comment]
Actually it already can be loaded and seem to work in some cases,a ll i tested now.                              
 model_a = BertModel.from_pretrained("/folder/")
 tokenizer_a = BertTokenizer.from_pretrained("/folder/")

**Comment by Oxi84** [comment]
It can be downloaded from the link.

**Comment by BramVanroy** [comment]
As you say, it is already available for download in their repository. If you want them to add their model to the transformers model hub, you can open an issue on their GitHub repo and ask them to add the model [here](https://huggingface.co/models?search=glossbert).
