### ISSUE TITLE
Why init specific layers rather than whole model  in BART

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#4834]
In BartForSequenceClassification I can see that rather than calling `self.init_weights()` (which most other models use) only specifically the classification head is initialized.

https://github.com/huggingface/transformers/blob/c58e6c129a153ca1a5021e5d7e642d00bf011e20/src/transformers/modeling_bart.py#L1046-L1047

Is there any advantage of doing this for the head(s) only rather than for the whole model? I can think of a speed improved, but apart from that I'm not sure.

**Comment by sshleifer** [comment]
The line 
```python
self.model = BartModel(config)
```
already calls `init_weights`, so no need to run it twice.

**Comment by BramVanroy** [comment]
Ah, you are of course correct. I noticed this because the other models (XXXForXXX) seem to just recall init_weights, e.g.

https://github.com/huggingface/transformers/blob/e33fdc93b4ecb571dd7a8002a74789ec8bfffc09/src/transformers/modeling_bert.py#L1008-L1015

But I guess that in practice it does not matter, it'll just be a bit slower but the result will be the same.

Thanks!
