### ISSUE TITLE
Any reason why BART does not have a ForTokenClassification variant?

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#4835]
Are there any theoretical constraints to create a ForTokenClassification variant for BART? In my current project I am using a sequence classification head + a token classification head, so I would like to implement the token classification part manually. However, since it is not implemented in the repository, I wonder if there are any particular reasons why one should not do this.

**Comment by sshleifer** [comment]
No theoretical reasons, go for it!

**Comment by vgaraujov** [comment]
@BramVanroy, did you implement BartForTokenClassification?

**Comment by BramVanroy** [comment]
@vgaraujov Sorry, no I did not.
