### ISSUE TITLE
BUG while calculate LM loss in AlbertForMaskedLM

### ISSUE THREAD

**Issue by slczgwh** [huggingface/transformers#4840]
# 🐛 Bug

Error Code Here: https://github.com/huggingface/transformers/blob/e33fdc93b4ecb571dd7a8002a74789ec8bfffc09/src/transformers/modeling_albert.py#L822

Here calculate the loss of all tokens in a seq. While MLM actually only calculate loss on [MASK]

**Comment by LysandreJik** [comment]
That's because the labels of all tokens *except* the mask tokens should be set to -100, as it's written in the [documentation](https://huggingface.co/transformers/model_doc/albert.html#albertformaskedlm).

Setting these tokens to -100 will result in the cross entropy ignoring them.
