### ISSUE TITLE
[Benchmark] Add optimization notebook

### ISSUE THREAD

**Issue by pommedeterresautee** [huggingface/transformers#4842]
# 🖥 Benchmarking `transformers`

## Benchmark

This notebook is about benchmarking model training with/without dynamic padding optimization. 
https://github.com/ELS-RD/transformers-notebook 

**Would it be possible to add it to the [community notebook](https://github.com/huggingface/transformers/tree/master/notebooks) list?** (a link to the Google collab version is provided) @julien-c @patrickvonplaten

## Set-up

GPU : Nvidia P100 provided by Google Collab

## Results

Using dynamic padding on MNLI provides a **4.7 times training time reduction**, with max pad length set to 512. The effect is strong because few examples are >> 400 tokens in this dataset. IRL, it will depend of the dataset, but it always bring improvement and, after more than 20 experiments listed in this [article](https://towardsdatascience.com/divide-hugging-face-transformers-training-time-by-2-or-more-21bf7129db9q-21bf7129db9e?source=friends_link&sk=10a45a0ace94b3255643d81b6475f409), it seems to not hurt performance.

**Comment by patrickvonplaten** [comment]
That'd be great! Do you want to open a PR? :-) 
I would use this line as the github line: https://github.com/ELS-RD/transformers-notebook/blob/master/Divide_Hugging_Face_Transformers_training_time_by_2_or_more.ipynb

and this one as the colab notebook line:
https://colab.research.google.com/drive/1CBfRU1zbfu7-ijiOqAAQUA-RJaxfcJoO?usp=sharing

**Comment by pommedeterresautee** [comment]
Haha, I thought you were managing the page (special order of article or whatever)... :-)
So the PR is done and waiting for your validation.
