### ISSUE TITLE
TFXLMRobertaForSequenceClassification: call() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by QixinLi** [huggingface/transformers#4848]
# 🐛 Bug

## Information

Model I am using : TFXLMRoberta

Language I am using the model on : cross-lingual

The problem arises when using:
* [ ] the official example scripts: 
* [√] my own modified scripts: 
```python
import tensorflow as tf
from transformers import TFXLMRobertaForSequenceClassification,XLMRobertaTokenizer,XLMRobertaConfig

tokenizer = XLMRobertaTokenizer.from_pretrained('jplu/tf-xlm-roberta-base')
model = TFXLMRobertaForSequenceClassification.from_pretrained('jplu/tf-xlm-roberta-base')
input_ids = tf.constant(tokenizer.encode("Hello, my dog is cute"))[None, :]  # Batch size 1
labels = tf.reshape(tf.constant(1), (-1, 1)) # Batch size 1
outputs = model(input_ids, labels=labels)
loss, logits = outputs[:2]
```
and I got error here:
```
  File "run_classifier.py", line 180, in train
    outputs = self.model(input_ids,attention_mask = input_mask, token_type_ids = token_type_ids, labels=labels, training = True)
  File "/Users/qixinli/anaconda/envs/a2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/Users/qixinli/anaconda/envs/a2/lib/python3.7/site-packages/transformers/modeling_tf_roberta.py", line 379, in call
    outputs = self.roberta(inputs, **kwargs)
  File "/Users/qixinli/anaconda/envs/a2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
TypeError: call() got an unexpected keyword argument 'labels'
```

I read the notes, it says TFXLMRobertaForSequenceClassification class **overrides** TFRobertaForSequenceClassification.

And [TFRobertaForSequenceClassification](https://huggingface.co/transformers/model_doc/roberta.html#tfrobertaforsequenceclassification) class's call() method accepts 'labels' argument.

For the TFRobertaForSequenceClassification model's example code, I just change the model and tokenizer to XLM, and it got an error.

## Environment info

- `transformers` version:2.5.1
- Platform:MacOS Catalina
- Python version: 3.5
- PyTorch version (GPU?): 
- Tensorflow version (GPU?): 2.0
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

**Comment by LysandreJik** [comment]
Hi! You're on `transformers` version `v2.5.1`, but the TensorFlow models can only accept labels since this PR https://github.com/huggingface/transformers/pull/4530 was merged, 4 days ago.

This currently isn't available in any release, so you will have to install from source to use that feature:

```
pip install git+https://github.com/huggingface/transformers
```

**Comment by QixinLi** [comment]
@LysandreJik thanks for your reminder！
