### ISSUE TITLE
Previous commit introduces bug in `convert_pytorch_checkpoint_to_tf2.py`

### ISSUE THREAD

**Issue by VictorSanh** [huggingface/transformers#4888]
This issue concerns the conversion tool `convert_pytorch_checkpoint_to_tf2.py`.

Commit d4c2cb402d6674211726fd5f4803d1090664e438 removed the `*PRETRAINED_MODEL_ARCHIVE_MAP` from the imports so that for each key in `MODEL_CLASSES` is associated to a set of 4 values.
For instance: https://github.com/huggingface/transformers/blob/e8db8b845a971b0cf63a0896b9deb5b316028a8b/src/transformers/convert_pytorch_checkpoint_to_tf2.py#L109

However, in `convert_all_pt_checkpoints_to_tf`, `MODEL_CLASSES` is still expected to unpack 5 values (among which the model maps) which raise an error:
https://github.com/huggingface/transformers/blob/e8db8b845a971b0cf63a0896b9deb5b316028a8b/src/transformers/convert_pytorch_checkpoint_to_tf2.py#L259

Typical command is:
```bash
python src/transformers/convert_pytorch_checkpoint_to_tf2.py \
    --tf_dump_path serialization_dir/weights_release/1st_weight_release/prunebert-base-uncased-6-finepruned-w-distil-squad/ \
    --model_type bert-large-uncased-whole-word-masking-finetuned-squad \
    --pytorch_checkpoint_path /serialization_dir/weights_release/1st_weight_release/prunebert-base-uncased-6-finepruned-w-distil-squad/ \
    --compare_with_pt_model
```

I didn't really follow why the `*PRETRAINED_MODEL_ARCHIVE_MAP` were removed so I'm not sure what is the best course of action here.

Victor

**Comment by tinlokkoo** [comment]
I encountered the same problem.
If you were converting a local `pytorch_model.bin` model, you can try this
`aws_model_maps = {}
        config_class, model_class, pt_model_class, aws_config_map = MODEL_CLASSES[model_type]
        # config_class, model_class, pt_model_class, aws_model_maps, aws_config_map = MODEL_CLASSES[model_type]`
