### ISSUE TITLE
encode_plus( ) function for the GPT-2 Tokenizer

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#4890]
Hello,

From the GPT-2 Tokenizer section of the Hugging Face Transformer documentation, the documentation says that:
```
GPT-2 BPE tokenizer. 

Peculiarities:

Byte-level Byte-Pair-Encoding

Requires a space to start the input string => the encoding methods should be called with the add_prefix_space flag set to True. Otherwise, this tokenizer encode and decode method will not conserve the absence of a space at the beginning of a string:
```

If I use the `encode_plus()` function (not `encode( )`) to encode my sentences (doing something like `encode_plus("Hi there")['input_ids']`, instead of directly using the `encode()` function), do I still need to place a space at the start of every input string?

Thank you,

**Comment by LysandreJik** [comment]
Sure, and you can use the `add_prefix_space` flag to do that.
