### ISSUE TITLE
🐛 [TFTrainer] `dataloader_drop_last` unused

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#4891]
# 🐛 Bug

The argument `dataloader_drop_last` appear to not be used in `TFTrainer`. This is a problem when we need a static batch size.

https://github.com/huggingface/transformers/blob/e8db8b845a971b0cf63a0896b9deb5b316028a8b/src/transformers/trainer_tf.py#L68-L73

## Expected behavior

The argument `dataloader_drop_last` is used when batching the dataset.

**Comment by setu4993** [comment]
Thanks for bringing this up, @Colanim! I worked on #4757, and didn't realize the same could automatically extend to TFTrainer as well.

Please take a look at #4925 to see if it'd solve this for you.
