### ISSUE TITLE
TypeError: export() got an unexpected keyword argument 'use_external_data_format'

### ISSUE THREAD

**Issue by ZLKong** [huggingface/transformers#4906]
Hi, 

I tried to run `convert_graph_to_onnx.py` using
`convert(framework="pt", model="bert-base-uncased", output="onnx/bert-base-uncased.onnx", opset=11)`

But I get error in the 
```
        export(
            nlp.model,
            model_args,
            f=output,
            input_names=ordered_input_names,
            output_names=output_names,
            dynamic_axes=dynamic_axes,
            do_constant_folding=True,
            use_external_data_format=use_external_format,
            enable_onnx_checker=True,
            opset_version=opset,
        )
```

the error is :
```
TypeError: export() got an unexpected keyword argument 'use_external_data_format'
TypeError: export() got an unexpected keyword argument 'enable_onnx_checker'
```

When I deleted these two lines, it does not report errors. Is it OK to remove these two lines?

Thanks,

ZLK

**Comment by d-val** [comment]
I just did this too and it seems to work :S

**Comment by abelriboulot** [comment]
I looked into this and I believe the issue is that use_external_data_format is a recent [addition to PyTorch from the onnx team](https://github.com/pytorch/pytorch/commit/96989a2a114de9b77e7dd9495d62c4a8a549b40d). If you upgrade to torch>=1.5.0 it should work. Also I added a PR #5687 to make this issue more straightforward.

**Comment by theoctopusride** [comment]
i have torch==1.13.1+cu116 installed and got this error.

**Comment by ecilay** [comment]
I have 2.1.0+cu121, still got this error

**Comment by amyeroberts** [comment]
@theoctopusride @ecilay The recommended and best supported way to export HF models to onnx is now through the optimum library: https://huggingface.co/docs/optimum/en/exporters/onnx/usage_guides/export_a_model
