### ISSUE TITLE
Simple way to convert a Python tokenizer to a fast tokenizer

### ISSUE THREAD

**Issue by pommedeterresautee** [huggingface/transformers#4914]
# 🚀 Feature request

Tokenizer are provided with each model, some have a fast version of their tokenizer (Rust based), others like CamemBERT have only the slow version.

## Motivation

Fast tokenizer improves inference times drastically (in real time inference for instance).
Plus there is no reason it should not be possible

## Your contribution

If you provide me with basic guidelines on how to manually make a conversion, I can submit a PR to offer such feature.

**Comment by pommedeterresautee** [comment]
requires unigram algo implemented on tokenizers
https://github.com/huggingface/tokenizers/pull/292

**Comment by pommedeterresautee** [comment]
PR merged, closing the issue

**Comment by varun-tandon** [comment]
Hi @pommedeterresautee, could you please refer me to how I can convert an existing Python tokenizer to a Fast tokenizer?

Sorry if I missed something, and thanks so much for your help!

**Comment by LysandreJik** [comment]
Maybe @SaulLu or @Narsil can comment and link to an example!
