### ISSUE TITLE
Unexpected behavior encoding token_type_ids in GPT models

### ISSUE THREAD

**Issue by sarahwie** [huggingface/transformers#4922]
# 🐛 Bug

## Information

When `token_type_ids` are passed into the `GPT2Model` and subclasses, they're encoded using the `nn.Embedding` lookup table as the vocabulary ([line](https://github.com/huggingface/transformers/blob/3ae2e86baffc1fea8b8b93695fb5a10941fd63dc/src/transformers/modeling_gpt2.py#L477)). Because the token type ids output by `encode_plus()` are `{0,1}`, this seems to create unexpected behavior by using the same embedding vectors to represent both word-tokens 0 and 1 in the vocabulary and the very distinct token type ids.

## Expected Behavior

Either:
1. instead of returning `token_type_ids` consisting of indices 0 and 1, extend the vocabulary by 2 and use those two ids as the `token_type_ids` in `encode_plus()`, or
2. addition of a separate `nn.Embedding` matrix for token_type_ids [here](https://github.com/huggingface/transformers/blob/3ae2e86baffc1fea8b8b93695fb5a10941fd63dc/src/transformers/modeling_gpt2.py#L352) (such as [in BERTModel](https://github.com/huggingface/transformers/blob/3ae2e86baffc1fea8b8b93695fb5a10941fd63dc/src/transformers/modeling_bert.py#L153))
3. discourage or throw a warning when `token_type_ids` are passed to GPTModel instances

**Comment by StuartMesham** [comment]
I am trying to use token_type_ids to annotate different languages being input to a multilingual model. I have run into this issue of unexpected behaviour where the embeddings for the first two tokens in my vocabulary are being used for my token type embeddings as well. I am using version 3.0.2.
