### ISSUE TITLE
Dataloader in Trainer num_workers > 0

### ISSUE THREAD

**Issue by Diego999** [huggingface/transformers#4942]
# ❓ Questions & Help

I notice that when doing inference/training with a pre-trained language model in a Trainer, only one worker is used. For training it's not a problem as the batch size is usually small, however, for inference, I can largely increase it.

However, it seems that https://github.com/huggingface/transformers/blob/master/src/transformers/trainer.py#L263 only supports num_workers=0. I tried to modified it manually and put num_workers=10, but no effect.

Am I doing something wrong in my reasoning?

Thanks for your help!

**Comment by ggaemo** [comment]
I also have the same issue.
