### ISSUE TITLE
Data used for training MarianMT models

### ISSUE THREAD

**Issue by yashkant** [huggingface/transformers#4952]
# ❓ Questions & Help
Are there specifications available on the amount and type of training data used for the released MarianMT [models](https://huggingface.co/transformers/model_doc/marian.html)?

## Details

I want to use these models for back translation in order to augment my current training data (the [VQA dataset](http://visualqa.org/) which is in English). I understand that for this, I could use any number of models in conjunction with source and target languages as `en`. 

However, I am concerned about the domain mismatch of the VQA dataset vs training data of the MT model. For example, using `en-ROMANCE` and `ROMANCE-en` models, I find that back-translation of the input sentence: 

`['>>lmo<< What do you think are the children playing with?']` is 

`['What do you think of the youth of the jubilee?']` 

Also, do you have any suggestions/guidelines on which/how many models to use particularly for this use case? I did not find this question suitable for SO hence it posted here directly

Thank you for releasing the models!

**Comment by patil-suraj** [comment]
Hi, @yashkant, you might be able to these details here https://github.com/Helsinki-NLP/Opus-MT
