### ISSUE TITLE
RobertaForMaskedLM Failing for example code given on Hugging Face' documentation page

### ISSUE THREAD

**Issue by tanulsingh** [huggingface/transformers#4956]
# 🐛 Bug

from transformers import RobertaTokenizer, RobertaForMaskedLM
import torch

tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = RobertaForMaskedLM.from_pretrained('roberta-base')
input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
outputs = model(input_ids, labels=input_ids)
loss, prediction_scores = outputs[:2]

I am using this example code given on hugging face's documentation page , but this also gives an error 
TypeError: forward() got an unexpected keyword argument 'labels'

The doc clearly states that forward accepts labels ,what's wrong here?

**Comment by sgugger** [comment]
Which version of the library are you using? The documentation corresponds to the master branch and the change in the argument names was pretty recent, so I don't think it's in the latest release yet. You should either [install from source](https://github.com/huggingface/transformers#from-source) or change the code to use the (soon-to-be deprecated) argument `masked_lm_labels` (see the documentation for the latest release [here](https://huggingface.co/transformers/v2.5.0/model_doc/bert.html#bertformaskedlm)).

**Comment by tanulsingh** [comment]
Thank you @sgugger for the latest documentation. I was scratching my head due to this
