### ISSUE TITLE
[TFTrainer] Tensorflow Warning : experimental_run_v2 is deprecated

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#4992]
# 🐛 Bug

When running my code with TFTrainer, I'm receiving :

>WARNING - tensorflow -   From /home/me/.venv/bart/lib/python3.6/site-packages/transformers/trainer_tf.py:355: StrategyBase.experimental_run_v2 (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
renamed to `run`

Is it expected ? How can I remove this warning ?

## Information

The problem arises when using:
* [ ] the official example scripts
* [x] my own modified scripts

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: CNN/DM
* [ ] my own task or dataset

## Environment info

     
- `transformers` version: 2.11.0
- Platform: Linux-4.9.0-9-amd64-x86_64-with-debian-9.12
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.0 (False)
- Tensorflow version (GPU?): 2.2.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: Using TPU training

**Comment by LysandreJik** [comment]
closes by #4998
