### ISSUE TITLE
[🚀 Feature request] upload bart-base checkpoint

### ISSUE THREAD

**Issue by patil-suraj** [huggingface/transformers#5004]
# 🚀 Feature request

`bart-base`  checkpoint is now available in fairseq repo 
https://github.com/pytorch/fairseq/tree/master/examples/bart#pre-trained-models
so now it can be made available here  `facebook/bart-base` 

@sshleifer

**Comment by sshleifer** [comment]
Thanks for letting me know @patil-suraj !

This is almost done, blocked on 1 minor [issue](https://github.com/pytorch/fairseq/issues/2242)

If I don't get an answer there by Wednesday I will assume that the tokenizer is the same as bart.large and move forward.

**Comment by patil-suraj** [comment]
Thanks @sshleifer  for immediate response and PR :)
