### ISSUE TITLE
Latest merge [Benchmark] Memory benchmark utils #4198 fails at Windows

### ISSUE THREAD

**Issue by songsuoyuan** [huggingface/transformers#5022]
# 🐛 Bug

## Information

Model I am using: Bert

## To reproduce

1. Windows
2. Install transformers from source

## Environment info
python = 3.7.6
pytorch = 1.5
cuda = 10.2

I think the problem happens because in code: 
https://github.com/huggingface/transformers/blob/master/src/transformers/__init__.py

`from .benchmark import PyTorchBenchmark, PyTorchBenchmarkArguments`

and in code:
https://github.com/huggingface/transformers/blob/master/src/transformers/benchmark/benchmark_utils.py

there is `from signal import SIGKILL`

> signal.SIGKILL
> 
> Kill signal.
> It cannot be caught, blocked, or ignored.
> Availability: Unix.

I think it will fail for Windows if you try `from signal import SIGKILL`.

@patrickvonplaten 
https://github.com/huggingface/transformers/pull/4198

**Comment by patrickvonplaten** [comment]
Thanks for noting that - you're 100% correct :-)
