### ISSUE TITLE
How to use 16 token types in pretrained Albert/BERT?

### ISSUE THREAD

**Issue by Traeyee** [huggingface/transformers#5047]
I have a dialogue task and I use token type to distinguish the diffenrent state of the different speeches, but all the pretrained models I can find are of type_vocab_size=2. To accomplish my goal, I have to rewrite many codes in a dirty way. So I want to ask is there an elegant way to restore the pretrained weights and ignore the token type embeddings at the same time? Roughly modifying the type_vocab_size in the given config.json will certainly raise an error

**Comment by cronoik** [comment]
Maybe I don't get it, but can't you simply do:

`from transformers.modeling_bert import BertConfig, BertModel

bconfig = BertConfig.from_pretrained('bert-base-uncased')
bconfig.type_vocab_size = 16
model = BertModel(bconfig)
model.parameters`
