### ISSUE TITLE
After I resume learning, loss is greater than prev checkpoint

### ISSUE THREAD

**Issue by urekalion** [huggingface/transformers#5048]
# ❓ Questions & Help

## Details

I learned albert mlm model.
Often an error occurs (memory exception, ... )
so i resumed learning model from last checkpoint 
but, training loss goes back to the beginning.
what do i need to check ? 
thank,
![loss ](https://user-images.githubusercontent.com/4244158/84736498-ed7abb00-afe0-11ea-9b30-9e669e327241.png)

**Comment by LysandreJik** [comment]
Hi! What did you use to train your model? Was it the `run_language_modeling` script? Do you happen to have the command you used?
