### ISSUE TITLE
TypeError: function() argument 1 must be code, not str

### ISSUE THREAD

**Issue by manhlab** [huggingface/transformers#5050]
# 🐛 Bug
TypeError: function() argument 1 must be code, not str
## Information

@dataclass
class T2TDataCollator(DataCollator):

**Comment by manhlab** [comment]
I get this error when create datacollator class

**Comment by LysandreJik** [comment]
Could you provide more information? It's a bit hard to help you here. What is the code you're using and what is the stacktrace?

**Comment by manhlab** [comment]
thanks you! i have the same problem with this #5049
