### ISSUE TITLE
How can I load the finetuned BART model to memory?

### ISSUE THREAD

**Issue by tomaszgarbus** [huggingface/transformers#5055]
I have finetuned a `facebook/bart-large` model following the example here: https://github.com/huggingface/transformers/blob/master/examples/summarization/finetune.py

As an output I got a `checkpointcheckpoint_ckpt_epoch_0.ckpt` file. How can I create a BartForConditionalGeneration instance with updated weights?

**Comment by sshleifer** [comment]
Duplicate of #4144

**Comment by tomaszgarbus** [comment]
Thanks!
