### ISSUE TITLE
glue.py Data Processor Index Error for Large Data

### ISSUE THREAD

**Issue by dr-aheydari** [huggingface/transformers#5071]
# 🐛 Bug

## Information

I am using `bert-base-uncase` and `roberta-base` for sentence pair classification, following the same exact example concept and data processing as MRPC. I have a large collection of private data that is in the _exact same format of MRPC_, and I am using `run_glue.py`as a base code for running my data.

Everything works great when I have smaller data files (between 10K-200k samples) but the issue happens when I increase the data size (300K and above); I am not sure if the issue is a bug or a memory issue. Here is the issue that happens: 

```
File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/data/processors/glue.py", line 200, in _create_examples
text_a = line[3]
IndexError: list index out of range

```

The data, the format and the values are consistent (I am not feeding in an empty file). If I concatenated the data in smaller samples works just fine. Is this an issue with the data processor or some sort of memory issue? it is perhaps important to note that I have not had any issues with using this large dataset for training different models.

## To reproduce

1. Have a _title-pair data_ in the exact format of MRPC that is large, say larger than 300K
2. Run the `run_glue.py` with MRPC as the task 
and you should get the following error:

## The Error

```
Traceback (most recent call last):
  File "run_glue.py", line 262, in <module>
    main()
  File "run_glue.py", line 140, in main
    train_dataset = GlueDataset(data_args, tokenizer=tokenizer) if training_args.do_train else None
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/data/datasets/glue.py", line 118, in __init__
    examples = self.processor.get_train_examples(args.data_dir)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/data/processors/glue.py", line 179, in get_train_examples
    return self._create_examples(self._read_tsv(os.path.join(data_dir, "train.tsv")), "train")
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/data/processors/glue.py", line 200, in _create_examples
    text_a = line[3]
IndexError: list index out of range
```

## Environment info
     
- `transformers` version: 2.11.0
- Platform: Linux-4.14.171-105.231.amzn1.x86_64-x86_64-with-glibc2.9
- Python version: 3.6.10
- PyTorch version (GPU?): 1.5.0 (True)

Thank you very much for your time and help, in advance.

**Comment by JetRunner** [comment]
Hi Ali!
Based on your error info, it seems that a line in your `train.tsv` does not follow the MRPC format. Or more specifically, that line may contain an empty field. Could you add a try-except to catch and print that line? It'll look like:

```python
try:
    text_a = line[3]
except:
    print(line)
```

**Comment by dr-aheydari** [comment]
@JetRunner 
Thank you very much for your suggestion. I found that there was a weird entry (that was not NaN nor empty) in some column of my data, and removing it with some modifications fixed the issue. 

Thank you again for your clear explanation and suggestion.
