### ISSUE TITLE
how to get complete URLs to weights in 2.11.0

### ISSUE THREAD

**Issue by allanj** [huggingface/transformers#5074]
# ❓ Questions & Help

Since it is related to the newest release, I would like to raise the question here. As our servers in the company are not able to access the HF url, we have to download the models locally and upload to the servers. Now seems I couldn't find the links to download `pytorch_model.bin`, `config.json`, `vocab.json`, `merge.txt`. 

The only one I can find is https://huggingface.co/facebook/bart-large

But  it only shows:

| File name | Last modified | File size|
|-- | -- | --|
|config.json | Fri, 24 Apr 2020 15:58:48 GMT | 1.2KB|
|pytorch_model.bin | Wed, 12 Feb 2020 19:53:45 GMT | 1.5GB|
|rust_model.ot | Sat, 25 Apr 2020 15:33:01 GMT | 1.9GB|

There is no `vocab.json`, `merge.txt`.  I want to find the complete URLs to these files.

**Comment by sshleifer** [comment]
They are the same as Roberta's 

```python
vocab_url = "https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-vocab.json"
merges_url = "https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-merges.txt"
```

Is your question more general than just `bart-large`? (Feel free to close if not :) )

**Comment by allanj** [comment]
Thanks and yes. I'm interested in a more general case to retrieve the URLs to weights for different models.
Currently, what I did actually is switching back to 2.10.0. And go to corresponding `modeling_xxx.py` and find the download link.

**Comment by julien-c** [comment]
You can find URLs to specific files on each model page (click on "List all files"): https://huggingface.co/distilbert-base-cased#list-files

**Comment by allanj** [comment]
Hi @julien-c , as mentioned, I actually know this way, but "list all files" seems not giving me the `vocab.json`, `merge.txt`, OR are they not required?

**Comment by julien-c** [comment]
Not all tokenizer types use those files. For instance Wordpiece (e.g. bert) is just one vocab.txt file.

**Comment by allanj** [comment]
Yup. I understand that, just named an example. But just want to make sure that files in https://huggingface.co/distilbert-base-cased#list-files are sufficient for me to use.  
So where do I get `vocab.json` and `merge.txt` for the bart-large model?
