### ISSUE TITLE
Colab session crashes on transformers

### ISSUE THREAD

**Issue by antoniomastro1996** [huggingface/transformers#5076]
# ❓ Questions & Help

## Details
Hi everybody, 
Something really strange happens in Colab after the recent updates of the DataCollate class.
I don't know if the two things are correlated, however, after I install the following packages

!git clone https://github.com/huggingface/transformers.git
!pip install ./transformers
!pip install -U nlp

and then I try to load them

import nlp
from transformers import T5Tokenizer

The Colab instance crashes.
Please find below the log.

**WARNING:root:kernel 485c962d-efa0-4103-9c68-ed22abd8839f restarted**

**Comment by khalilRhouma** [comment]
> # ❓ Questions & Help
> ## Details
> Hi everybody,
> Something really strange happens in Colab after the recent updates of the DataCollate class.
> I don't know if the two things are correlated, however, after I install the following packages
> 
> !git clone https://github.com/huggingface/transformers.git
> !pip install ./transformers
> !pip install -U nlp
> 
> and then I try to load them
> 
> import nlp
> from transformers import T5Tokenizer
> 
> The Colab instance crashes.
> Please find below the log.
> 
> **WARNING:root:kernel 485c962d-efa0-4103-9c68-ed22abd8839f restarted**

The same thing for me. Colab (using TPU) crashes when importing transformers package.
![image](https://user-images.githubusercontent.com/35801846/84882177-c5459780-b086-11ea-8c47-4b06eb3e8249.png)

**Comment by amitness** [comment]
Same issue.

**Comment by LysandreJik** [comment]
I'm trying to reproduce, but can't manage to make colab crash. @khalilRhouma, @amitness, did you have similar code to @antoniomastro1996? Would it be possible for you to show me the code you used?

**Comment by antoniomastro1996** [comment]
@LysandreJik yes, of course you can follow this:
https://colab.research.google.com/drive/1jwXgtOXE8v8_qkiOCbjFQRFC5semK8T7?usp=sharing
