### ISSUE TITLE
Is there a helper script to preprocess data for T5 for masked language modeling? 

### ISSUE THREAD

**Issue by abhisheksgumadi** [huggingface/transformers#5089]
Hi Team

   Thanks for the wonderful HuggingFace library ! 

I am now working with T5 on my own dataset. I want to know if there is any helper script that can automatically take text and mask a random set of tokens and also generate the expected output sequence for the pretraining unsupervised language modeling task.

**Comment by patrickvonplaten** [comment]
Not yet sadly - it's on my ToDo list. Hope to be able to work on it soon

**Comment by amanpreet692** [comment]
I am working on a script for T5 based upon the current run_language_modeling.py, maybe I can share that once I am done and someone can confirm if it works as expected?

**Comment by amlarraz** [comment]
Hi, I'm working in the same task [here](https://github.com/huggingface/transformers/issues/7451) you can see my code if it helps!
