### ISSUE TITLE
Training the BERTSUM model

### ISSUE THREAD

**Issue by tahmedge** [huggingface/transformers#5097]
Hi, I find that the script can only predict the summaries using the BERTSUM model. Is it possible to train the BERTSUM model using this script?

**Comment by LysandreJik** [comment]
Hi, as seen with @sshleifer, you can train for summarization using the [summarization script](https://github.com/huggingface/transformers/tree/master/examples/summarization). The models supported right now are all BART variants and t5-small. More to come!
