### ISSUE TITLE
Update Conda Release

### ISSUE THREAD

**Issue by lukasfolle** [huggingface/transformers#5100]
When trying to get started with transformers using some examples from the model cards, the installation with conda results in an outdated version (2.1.1).

As a result, the example cannot run. However, when using pip to install transformers the newest version (2.11) is correctly used.

I would suggest updating the conda release in order to avoid installing via pip.

**Comment by setu4993** [comment]
This might provide more information: https://github.com/conda-forge/transformers-feedstock/issues/3

In short, the conda-forge update is blocked by `sentencepiece` not being available through conda.

**Comment by thomwolf** [comment]
This should be fixed by #8073
