### ISSUE TITLE
OpenAIGPTDoubleHeadsModel Don't have the "labels" attributes as it is described in the documentation

### ISSUE THREAD

**Issue by ghsama** [huggingface/transformers#5101]
# 🐛 Bug

## Information

Model I am using OpenAIGPTDoubleHeadsModel:

Language I am using the model on English:

The problem arises when using:
* The official example scripts: 
I'm using transformer version : '2.11.0'

In the documentation i found that i can pass a "labels" attribute to the OpenAIGPTDoubleHeadsModel Model to be used in the loss:
[Documentation](https://huggingface.co/transformers/model_doc/gpt.html#openaigptdoubleheadsmodel)
But when i pass it he didn't recognize it : 

``model(input_ids=input_ids,` token_type_ids=token_type_ids, position_ids=None, head_mask=None, mc_token_ids = mc_token_ids, labels=lm_labels, mc_labels = mc_labels)``

``TypeError                                 Traceback (most recent call last)
<ipython-input-67-cc8f7864d8a7> in <module>()
----> 1 model(input_ids=input_ids, token_type_ids=token_type_ids, position_ids=None, head_mask=None, mc_token_ids = mc_token_ids, labels=lm_labels, mc_labels = mc_labels)
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)
TypeError: forward() got an unexpected keyword argument 'labels' ``

## Question : 

Is passing the labels thorough GPT implimentation is depricated ? if yes is there a way to pass it ?
Thank you

**Comment by patil-suraj** [comment]
Hi @ghsama `lm_labels` is changed to `labels` after 2.11.0.  So if you are using version <=2.11.0 use `lm_labels`  and if you're using master branch then use `labels`

**Comment by ghsama** [comment]
Yes ! i just figure it out . Thank you @patil-suraj :D
