### ISSUE TITLE
Is there a helper script to randomly mask spans of text for T5 pretraining?

### ISSUE THREAD

**Issue by abhisheknovoic** [huggingface/transformers#5105]
Hello team,

 If I have an input text like

```The cute dog walks in the park```

Is there a library within HuggingFace that can output the following for me by masking random spans of text by (optional) taking an input masking probability?

``` 
masked input: The <extra_id_1> walks in <extra_id_2> park
target: <extra_id_1> cute dog <extra_id_2> the <extra_id_3> </s>

```

This is for preparing data for T5 within my own codebase.

**Comment by patrickvonplaten** [comment]
Not yet -> on the roadmap :-)

**Comment by yuchenlin** [comment]
any updates here?
