### ISSUE TITLE
Fine-Tuning GPT2

### ISSUE THREAD

**Issue by apteryxlabs** [huggingface/transformers#5123]
This post references a page that no longer exists (the run_lm_finetuning.py). Where is the updated page?

"You can look into GPT-2's training on the CLM task, which is done on WikiText-2 in this example."

_Originally posted by @LysandreJik in https://github.com/huggingface/transformers/issues/1145#issuecomment-526322616_

**Comment by LysandreJik** [comment]
Hi! This script has been replaced by `language-modeling/run_language_modeling.py`, because it now handles pre-training as well, not only fine-tuning. [Here's a useful link.](https://github.com/huggingface/transformers/tree/master/examples/language-modeling)
