### ISSUE TITLE
src/transformers/trainer.py relies on path to infer global training steps, skips training for glue example

### ISSUE THREAD

**Issue by alexeifigueroa** [huggingface/transformers#5135]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): bert-base-uncased that has been retrained stored somewhere else, with a timestamp in the path

Language I am using the model on (English, Chinese ...):EN

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name) MRPC
* [ ] my own task or dataset: (give details below)

## To reproduce

1. store a pretrained model with a different name, say /funny/path/2020-06-19_120000/retrained , 
with the tokenizer and stuff inside.
2. Run the glue example run_glue on that path with --do_train, --do_eval
3. The training will be skipped because there's [this](https://github.com/huggingface/transformers/blob/84be482f6698fac822a5113735f2242c6d3abc76/src/transformers/trainer.py#L431) funny line in the trainer that will bump the global steps because of the parsing of the date.. 

## Expected behavior

I would not expect the trainer to rely on an arbitrary internal convention for naming checkpoints or any kind of path to yield a spurious global step count.

## Environment info

     
- `transformers` version: 2.11.0
- Platform: Linux-5.4.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.5
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?):
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by BenjaminWinter** [comment]
I have the same problem. The script shouldn't run differently depending on what naming scheme you decide to use for a model.
