### ISSUE TITLE
Passing in own embeddings for image input

### ISSUE THREAD

**Issue by andrewlee98** [huggingface/transformers#5143]
# 🚀 Feature request

I am trying to use your pretrained BERT/RoBERTa models to write multimodal classifiers such as the bitransformer (see diagram at top of page 2):
https://arxiv.org/pdf/1909.02950.pdf

and Visual BERT:
https://arxiv.org/pdf/1908.03557.pdf

It would be nice to be able to change the input layer of the transformer models to handle custom input embeddings rather than just input_ids. If there is already a way to do this, it would be great to get some instructions on how. I have tried printing the layers of the pretrained RoBERTa model, but it only gives:
`<transformers.modeling_tf_roberta.TFRobertaMainLayer object at 0x7f79fc04dcf8>`

Edit: I actually see that there is a MMBT model mentioned in the documentation, but I cannot find the pre-trained model or any examples with it. Please help. Thank you.

## Motivation

I would like to be able to use your pretrained models to handle image embeddings as well. I am working on a project with this multimodal dataset: 
https://gombru.github.io/2019/10/09/MMHS/

Any help would be greatly appreciated. Thanks!

**Comment by julien-c** [comment]
Check out the `inputs_embeds` parameter.
