### ISSUE TITLE
Cannot import AutoModelForSeq2SeqLM 

### ISSUE THREAD

**Issue by shubhamagarwal92** [huggingface/transformers#5166]
# 🐛 Bug

Has the `AutoModelForSeq2SeqLM` class changed? 

I am trying to run transformer examples, basically the [token-classification](https://github.com/huggingface/transformers/blob/master/examples/token-classification/run_pl.sh) with pytorch-lightning, which calls [AutoModelForSeq2SeqLM](https://github.com/huggingface/transformers/blob/master/examples/lightning_base.py#L18). However, I am getting an import error. See below.

## Information

Model I am using (Bert, XLNet ...):

`bert-base-multilingual-cased`

Language I am using the model on (English, Chinese ...): 

`English`

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

```
cd transformers/examples/token-classification
./run_pl.sh
```

```
Traceback (most recent call last):
  File "run_pl_ner.py", line 12, in <module>
    from lightning_base import BaseTransformer, add_generic_args, generic_train
  File "/transformers/examples/lightning_base.py", line 12, in <module>
    from transformers import (
ImportError: cannot import name 'AutoModelForSeq2SeqLM' from 'transformers' (/anaconda3/envs/transformers/lib/python3.8/site-packages/transformers/__init__.py)
```

## Expected behavior

Reproduce the example.

## Environment info

     
- `transformers` version: 2.11.0
- Platform: Linux
- Python version: Python 3.8.3
- PyTorch version (GPU?): 1.5.1
- Tensorflow version (GPU?):
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?:

**Comment by sgugger** [comment]
I think this is because you don't have installed the library from source (see the [note here](https://github.com/huggingface/transformers/blob/master/examples/README.md#important-note)).

To install from source, follow the steps [here](https://huggingface.co/transformers/installation.html#installing-from-source)

**Comment by shubhamagarwal92** [comment]
@sgugger Thanks, it works when installing with the source (through small changes) :) 

Also, as I said, the 2.11.0 version (installed by pip) still has this bug 

```
from transformers import AutoModelForSeq2SeqLM
```

What version do you suggest for a stable version of transformers?

**Comment by sgugger** [comment]
I'm not sure I follow. 2.11.0 is the last stable version, but the examples script on the main branch only works with an installation from source. 

If you want a version of the examples compatible with 2.11.0, you should use their version in the [2.11.0 tagged repo](https://github.com/huggingface/transformers/tree/v2.11.0).

**Comment by waring92** [comment]
Same Issue v2.11.0

**Comment by sgugger** [comment]
Again this is not an issue. The examples in the master repo are on par with the version of transformers on master, so you need an installation from source to run them, which is clearly indicated in the README.

If you want to execute the examples script as they were for v2.11.0, you should use 2.11.0 tagged repo](https://github.com/huggingface/transformers/tree/v2.11.0).

Closing this issue, please reopen if anything I said was unclear.
