### ISSUE TITLE
object returned by  RobertaTokenizerFast() class are not serializable,

### ISSUE THREAD

**Issue by ad6398** [huggingface/transformers#5176]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): RobertaTokenizerFast()
Language I am using the model on (English, Chinese ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
yes

## To reproduce

[Steps to reproduce the behavior: https://github.com/huggingface/tokenizers/issues/313#issue-642829111 ](https://github.com/huggingface/tokenizers/issues/313#issue-642829111)

**Comment by sshleifer** [comment]
cc @mfuntowicz

**Comment by thomwolf** [comment]
This is fixed on master and should be in the next release
