### ISSUE TITLE
When is 2.12 coming out?

### ISSUE THREAD

**Issue by Laksh1997** [huggingface/transformers#5177]
Hi when is 2.12 coming out? Cheers.

(Interested in AutoModelForCausalLM)

**Comment by patil-suraj** [comment]
For now you can install from source to use `AutoModelForCausalLM`

**Comment by Laksh1997** [comment]
Yes but you can't push out libraries with packages installed from master

**Comment by LysandreJik** [comment]
Probably this week or the next!

**Comment by erikchwang** [comment]
+1

**Comment by LysandreJik** [comment]
Version v3.0.0 was released this morning!
