### ISSUE TITLE
Which Marian version was used to train the Helsinki-NLP/* checkpoints?

### ISSUE THREAD

**Issue by vmedappa** [huggingface/transformers#5180]
Trying to find the **Marian version used to train Marian MT transformers**. This would help me understand the **benchmarks for translation times**. I see that multiple papers mention various benchmarks for CPU translation : 

- https://www.aclweb.org/anthology/D19-5632.pdf - has the benchmarks for the latest update Marian v1.9
- https://www.aclweb.org/anthology/P18-4020.pdf - does not mention the version but I presume it uses versions between  Marian v1.7 and Marian v1.5

**Marian v1.9 suggests considerably faster translation times than Marian v1.7 and Marian v1.5.** 

Finding the version used for the huggingface transformers both in the huggingface and Helsinki NLP documentation hasn't been fruitful. Would be really helpful to have this answered.

**Comment by sshleifer** [comment]
Those models were trained by @jorgtied as part of the OPUS project. He might know the answer.

**Comment by PacoPacov** [comment]
@sshleifer  Do you know how can I fine tune the models with my specific data?

**Comment by sshleifer** [comment]
I just started a PR to support that, but it's still a week away. At the moment, your best bet is to modify `summarization/finetune.py`.

**Comment by jorgtied** [comment]
> Trying to find the **Marian version used to train Marian MT transformers**. This would help me understand the **benchmarks for translation times**. I see that multiple papers mention various benchmarks for CPU translation :
> 
>     * https://www.aclweb.org/anthology/D19-5632.pdf - has the benchmarks for the latest update Marian v1.9
> 
>     * https://www.aclweb.org/anthology/P18-4020.pdf - does not mention the version but I presume it uses versions between  Marian v1.7 and Marian v1.5
> 
> 
> **Marian v1.9 suggests considerably faster translation times than Marian v1.7 and Marian v1.5.**
> 
> Finding the version used for the huggingface transformers both in the huggingface and Helsinki NLP documentation hasn't been fruitful. Would be really helpful to have this answered.

The version should be marked in the original model files distributed at https://github.com/Helsinki-NLP/Opus-MT. Most of them will be v1.7. I just started recently to use v1.9 for upcoming models.
