### ISSUE TITLE
How to build Bimodel to search code snippets? [CodeBERTa]

### ISSUE THREAD

**Issue by hmdgit** [huggingface/transformers#5207]
Hi,

I would like build a code search engine model. The main purpose is that when I pass docstring, it should give me top-k associated code snippets as results. 

I have a data in the form of (docstring, code), which means each docstring is associated with mentioned code snippet.

I have seen CodeBERTa fine tune [code](https://huggingface.co/huggingface/CodeBERTa-language-id), but it is not using docstring in it. Is it possible to use this model?

Can you please give me some entry points to solve this problem by using hugging-face library?

**Comment by julien-c** [comment]
CodeBERTa was indeed trained on just the code so you would need to tweak the approach.

Did you read the paper for CodeSearchNet (https://arxiv.org/abs/1909.09436) by @hamelsmu?

**Comment by hmdgit** [comment]
Thanks Julien for your response.

I have taken an overview of the paper and its [code](https://github.com/github/CodeSearchNet), and I will try it.

But, can it be possible to solve it by using BERT huggingface library? What kind of tweaks do I need to apply in CodeBERT  fine tune [code](https://huggingface.co/huggingface/CodeBERTa-language-id)? 

Can it be solved by finetuning BertForQuestionAnswering [code](https://huggingface.co/transformers/model_doc/bert.html#bertforquestionanswering)?

**Comment by fengzhangyin** [comment]
Maybe CodeBERT([https://arxiv.org/abs/2002.08155](https://arxiv.org/abs/2002.08155)) is suitable for you.

**Comment by hmdgit** [comment]
Yes..I am interested in this paper....
Is there fine tuning source code for that paper publicly available? or are there any short snippets available which can help in fine-tuning?

**Comment by fengzhangyin** [comment]
You can visit this link ([https://github.com/microsoft/CodeBERT](https://github.com/microsoft/CodeBERT)) and hope it is useful to you.

**Comment by hmdgit** [comment]
Thanks for sharing. I will check and let you know about related concerns on the shared github repository
