### ISSUE TITLE
RobertaTokenizerFast produces a different output than RobertaTokenizer

### ISSUE THREAD

**Issue by HHousen** [huggingface/transformers#5256]
# 🐛 Bug

`RobertaTokenizerFast.tokenize()` produces a different output than `RobertaTokenizer.tokenize()`. I am not sure if this is an issue that will impact model performance. Is this intended? I assumed the fast tokenizers should be consistent with the normal ones in terms of outputs.

## Information

Model I am using (Bert, XLNet ...): Roberta

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```python
from transformers import RobertaTokenizer, RobertaTokenizerFast

tokenizer = RobertaTokenizer.from_pretrained("roberta-base")
tokens = tokenizer.tokenize("This is a test. </s> <s> Another one. </s> <s> Yet another one.")
print("Normal Tokens: " + str(tokens))

ids = tokenizer.convert_tokens_to_ids(tokens)
print("Normal IDs: " + str(ids))


tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base")
tokens = tokenizer.tokenize("This is a test. </s> <s> Another one. </s> <s> Yet another one.")
print("Fast Tokens: " + str(tokens))

ids = tokenizer.convert_tokens_to_ids(tokens)
print("Fast IDs: " + str(ids))
```

Output:

```
Normal Tokens: ['This', 'Ġis', 'Ġa', 'Ġtest', '.', '</s>', '<s>', 'ĠAnother', 'Ġone', '.', '</s>', '<s>', 'ĠYet', 'Ġanother', 'Ġone', '.']
Normal IDs: [713, 16, 10, 1296, 4, 2, 0, 2044, 65, 4, 2, 0, 3507, 277, 65, 4]
Fast Tokens: ['ĠThis', 'Ġis', 'Ġa', 'Ġtest', '.', 'Ġ', '</s>', 'Ġ', '<s>', 'ĠAnother', 'Ġone', '.', 'Ġ', '</s>', 'Ġ', '<s>', 'ĠYet', 'Ġanother', 'Ġone', '.']
Fast IDs: [152, 16, 10, 1296, 4, 1437, 2, 1437, 0, 2044, 65, 4, 1437, 2, 1437, 0, 3507, 277, 65, 4]
```

Using `tokenizer.enocde()` instead of `tokenizer.convert_tokens_to_ids(tokenizer.tokenize())` solves the discrepancy with the first token but still inserts token id `1437` between `</s>` and `<s>`.

## Expected behavior

`RobertaTokenizerFast` produces the same output as `RobertaTokenizer`.

## Environment info
     
- `transformers` version: 2.11.0
- Platform: Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.1+cu101 (True)
- Tensorflow version (GPU?): 2.2.0 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by yash-raj-verma** [comment]
Now, it seemed to have been resolved. I tried to reproduce this in my notebook but getting same results for both of them:

<img width="1383" alt="image" src="https://github.com/huggingface/transformers/assets/104596164/bde951ac-8b9c-4996-966b-1d11f4c12d35">
