### ISSUE TITLE
[proposal] Move tests/utils.py to src/transformers/testing_utils.py so that examples can import

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#5261]
for both groups of tests, the import would be
```python
from transformers.testing_utils import slow
```

Motivation: I was about to rewrite the @slow decorator today and felt that this was cleaner.

Any objections? @julien-c @LysandreJik @thomwolf @sgugger @patrickvonplaten @mfuntowicz 
@anyoneelseimforgetting

**Comment by LysandreJik** [comment]
I think that would be cool. Since we're testing the examples, it makes sense to not duplicate the exact same code.

**Comment by patrickvonplaten** [comment]
Sounds good to me
