### ISSUE TITLE
ValueError in T5 community colab notebook.

### ISSUE THREAD

**Issue by y-rokutan** [huggingface/transformers#5267]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): T5

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the community notebook https://github.com/patil-suraj/exploring-T5/blob/master/T5_on_TPU.ipynb:
  * It raises subclassing error while defining `class T2TDataCollator(DataCollator)`. DataCollator is not a class anymore on the latest master branch, just `class T2TDataCollator()` fixes the error.
  * Even that bug is fixed, the notebook raises another ValueError while importing dataset.pt:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-18-4f8aea5d9d8b>", line 191, in _mp_fn
    main()
  File "<ipython-input-18-4f8aea5d9d8b>", line 145, in main
    train_dataset  = torch.load(data_args.train_file_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 589, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 847, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.6/dist-packages/nlp/splits.py", line 493, in __setitem__
    raise ValueError("Cannot add elem. Use .add() instead.")
ValueError: Cannot add elem. Use .add() instead.
```

## To reproduce

1. Run the community colab notebook: https://github.com/patil-suraj/exploring-T5/blob/master/T5_on_TPU.ipynb
2. You will get the error.

## Expected behavior
* Not applicable

## Environment info
* It's running on colab.

**Comment by patil-suraj** [comment]
hi @y-rokutan, you are right, `DataCollator` is not a `Class` anymore, its a `callable`  now, so remove subclassing and change `collate_batch` method to ` __call__`  

I'll update the notebook once new version of transformers is released

**Comment by y-rokutan** [comment]
hi @patil-suraj, thx for your quick reply. I appreciate your contributions.
Do you have any idea about ValueError issue? I'm googling for fix but still have the same error.

**Comment by patil-suraj** [comment]
What is your nlp version ? Try using nlp==0.2.0

**Comment by y-rokutan** [comment]
`!pip install -U nlp==0.2.0` worked! nlp0.3.0 seems not for this notebook. Thx!

**Comment by santhoshkolloju** [comment]
hi i am running the notebook without any changes . But its very slow i think its not using TPU at all
