### ISSUE TITLE
Bart: Instatiate lm_head once without wasting memory

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#5282]
Marking this down since I agreed to do it https://github.com/huggingface/transformers/pull/4803#discussion_r443381438

cc @patrickvonplaten

**Comment by sshleifer** [comment]
this will happen as part of TPU issue.

**Comment by patrickvonplaten** [comment]
Can you link the issue? Is there an open PR for this already?

**Comment by sshleifer** [comment]
This one: https://github.com/huggingface/transformers/pull/5960 , but it's broken afaict.
