### ISSUE TITLE
Tokenizer batch_encode_plus unexpected behavior 

### ISSUE THREAD

**Issue by JavaiMaster** [huggingface/transformers#5284]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):
bert-base-multilingual-cased

Language I am using the model on (English, Chinese ...):
English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)
A script to tokenize sentences into inputs for the model

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)
Standard text that is used for intent and domain classification

## To reproduce

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")
tokenizer.batch_encode_plus(["hello my name is Sam"], return_tensors="pt", pad_to_max_length=True, add_special_tokens=True)['input_ids']
>>>tensor([[  101, 61694, 10133, 15127, 11324, 10124, 14268,   102]])
tokenizer.batch_encode_plus(["hello my name is Sam"], return_tensors="pt", pad_to_max_length=True, add_special_tokens=False)['input_ids']
>>>tensor([[61694, 10133, 15127, 11324, 10124, 14268,     0,     0]])
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
tokenizer.batch_encode_plus(["hello my name is Sam"], return_tensors="pt", pad_to_max_length=True, add_special_tokens=True)['input_ids']
>>>tensor([[    0, 33600,    31,   759,  9351,    83,  3362,     2]])
tokenizer.batch_encode_plus(["hello my name is Sam"], return_tensors="pt", pad_to_max_length=True, add_special_tokens=False)['input_ids']
>>>tensor([[33600,    31,   759,  9351,    83,  3362,     1,     1]])
```

## Expected behavior

When running batch_encode_plus for a single example without adding special tokens and pad_to_max_length set to True, I would not expect any pad tokens. I did not see any mention in the documentation as to why this behavior is the expected norm. 

## Environment info

     
- `transformers` version: 2.11.0
- Platform: MacOS
- Python version: 3.7.3
- PyTorch version (GPU?): 1.5.0
- Tensorflow version (GPU?): N/A
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by thomwolf** [comment]
Yes, this was fixed on master today with https://github.com/huggingface/transformers/pull/5252
