### ISSUE TITLE
Is there a Longformer For Sequence Classification?

### ISSUE THREAD

**Issue by Weilin37** [huggingface/transformers#5288]
I noticed that Longformer does not have a "LongformerForSequenceClassification". Is there a reason for this and is this something that would be added in the near future?

**Comment by sgugger** [comment]
It is [there](https://github.com/huggingface/transformers/blob/24f46ea3f3e5006ca38735306753a846a0823174/src/transformers/modeling_longformer.py#L796). 

You may need to use a source install, I'm not sure it was already there in the last release.

**Comment by Weilin37** [comment]
Thanks. It was in the release but it just wasnt in the documentation.
