### ISSUE TITLE
Model with fastest inference?

### ISSUE THREAD

**Issue by tqdo** [huggingface/transformers#5290]
Just curious whether there is any benchmark for inference speed of models in the transformers library? I am interested in the question-answer task but I think a benchmark on any tasks that BERT can do should be good. Thank you.

**Comment by ahotrod** [comment]
@tqdo  There is extensive info and a spreadsheet [here](https://huggingface.co/transformers/benchmarks.html?highlight=benchmark).

**Comment by tqdo** [comment]
Thanks a lot
