### ISSUE TITLE
run_squad.py :: ValueError: Input [] is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

### ISSUE THREAD

**Issue by SarangSanjayGujar-lilly** [huggingface/transformers#5293]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Bert

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
[*] the official example scripts: (give details below)
[ ] my own modified scripts: (give details below)

The tasks I am working on is:
[*] an official GLUE/SQUaD task: (give the name)
[ ] my own task or dataset: (give details below)

## To reproduce

1. while running run_squad.py 
2.  Training & testing with
https://rajpurkar.github.io/SQuAD-explorer/dataset/train-v1.1.json
https://rajpurkar.github.io/SQuAD-explorer/dataset/dev-v1.1.json

## Error
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 320, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
ValueError: Input [] is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

## Expected behavior

To work

## Environment info
- `transformers` version: 2.11.0
- Platform: Linux-5.3.0-1017-aws-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.1 (False)
- Tensorflow version (GPU?): 2.2.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by LysandreJik** [comment]
Hi! Do you mind pasting the command you use to run the script?

**Comment by dhruvluci** [comment]
I'm facing the same error while training Electra and MiniLM on Squad:
ValueError: Input [] is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

This error is thrown up after reading of about 2% of the examples.
My env is the same as above. The command I use is:

python examples/question-answering/run_squad.py \
  --model_type bert \
  --model_name_or_path microsoft/MiniLM-L12-H384-uncased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file "/content/transformers/dev-v1.1.json" \
  --predict_file "/content/transformers/dev-v1.1.json" \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir "/content/drive/My Drive/bert/newdir5"

**Comment by LysandreJik** [comment]
Thanks, looking into it.

**Comment by mrm8488** [comment]
I works now!

**Comment by LysandreJik** [comment]
Yes, it should be fixed in v3.0.0!
