### ISSUE TITLE
Request for inclusion of PEGASUS for text summarization by Google.

### ISSUE THREAD

**Issue by alexvaca0** [huggingface/transformers#5301]
# 🚀 Feature request

Google has recently released PEGASUS, a new model for text summarization: https://ai.googleblog.com/2020/06/pegasus-state-of-art-model-for.html. I think It would be interesting to have it included in Transformers library. The code and checkpoints are here: https://github.com/google-research/pegasus. This model seems to accomplish human-like summarization.

**Comment by patrickvonplaten** [comment]
@sshleifer

**Comment by sshleifer** [comment]
Duplicate of #4918 , but yes it is WIP!
