### ISSUE TITLE
Does BERT public an embedding file like glove.840B.300d.txt? 

### ISSUE THREAD

**Issue by 14H034160212** [huggingface/transformers#5305]
# ❓ Questions & Help
Hi, I have seen BERT public the pre-training language model like BERT-based-uncased. Does BERT public an embedding file like glove.840B.300d.txt? Many thanks.

**Comment by GunjanChhablani** [comment]
BERT is a fine-tuning based model. As far as I'm aware, there are no 'embedding files' as such. You could generate embedding relevant to your case, by providing the model with words (see documentation) and generate outputs.

**Comment by 14H034160212** [comment]
Thanks!

**Comment by 14H034160212** [comment]
> BERT is a fine-tuning based model. As far as I'm aware, there are no 'embedding files' as such. You could generate embedding relevant to your case, by providing the model with words (see documentation) and generate outputs.

Many thanks!
