### ISSUE TITLE
In Tensorflow the serving is very slow

### ISSUE THREAD

**Issue by only-yao** [huggingface/transformers#5341]
# ❓ I'm using the gpt2 model, In Tensorflow the serving is very slow, Tensorflow is much faster.

## Details
I use tf.saved_model save model
`tf.saved_model.save(model, export_dir="/model/2/")`

Tensorflow reads the model
```
imported = tf.saved_model.load("/model/2/")
f = imported.signatures["serving_default"]
```

The speed of Tensorflow is much higher than that of tensorflow
In the same model without the use of transformers, tensorFlow and TensorFlow serve at the same speed

**Comment by julien-c** [comment]
I don't get it
