### ISSUE TITLE
Upload model card with the CLI

### ISSUE THREAD

**Issue by borisdayma** [huggingface/transformers#5346]
# 🚀 Feature request

Upload model card README.md with transformers CLI.

## Motivation

Some applications may require to upload multiple models. It would be nice to be able to upload associated model card with model/tokenizer/config files.

At the moment a PR is required making it more difficult for users to upload their models and nearly impossible for apps relying on training and uploading a lot of different models.

## Your contribution

I could help propose a PR for the client side.

**Comment by julien-c** [comment]
This is not currently documented (cc @sgugger) but it's already possible, see for instance https://huggingface.co/Helsinki-NLP/opus-mt-fr-en

At some point it might become the preferred way of publishing a model card too.

**Comment by sgugger** [comment]
Will update the tutorial today.

**Comment by borisdayma** [comment]
Thanks, this is great!
