### ISSUE TITLE
Do T5 have the next-sentence-predict loss?

### ISSUE THREAD

**Issue by guotong1988** [huggingface/transformers#5358]
Input the previous sentence and predict/generate the next sentence.

Thank you very much.

**Comment by patil-suraj** [comment]
Hi @guotong1988   It's possible to do these tasks with text-to-text approach.

for predicting next sentence you can process input like this
`sentence1: sentence1_text  sentence2: sentence2_text`
and ask the model to predict `true` if sentence2 is the next sentence else `false`

and for generating next sentence, provide first sentence as input and next sentence as the target.

**Comment by guotong1988** [comment]
Thank you. It is not generating the whole next sentence. But it is predicting is_next or not_next.
