### ISSUE TITLE
Unable to load Longformer pretrained weights

### ISSUE THREAD

**Issue by qianyingw** [huggingface/transformers#5376]
Hi, 

I am following the official example to load longformer model by:

```
from transformers import LongformerModel, LongformerTokenizer
tokenizer = LongformerTokenizer.from_pretrained('allenai/longformer-base-4096')
model = LongformerModel.from_pretrained('allenai/longformer-base-4096')

```
I can load tokenizer and config, but when I try to load model, it gave me the error "OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True." It happened on my other transformer models like BERT/XLNet, and I solved it by their corresponding functions "convert_tf_checkpoint_to_pytorch". I don't understand why this happen on Longformer as it is not from any tensorflow module?

I'm using
- `transformers` version: 3.0.0
- Python version: 3.7.4
- PyTorch version: 1.2.0

**Comment by LysandreJik** [comment]
Hi! Do you have internet access? Does the folder `allenai/longformer-base-4096` exist on your machine?

**Comment by qianyingw** [comment]
Ahh...sorry I thought it was included in the library...Thank you for your reply!

**Comment by LysandreJik** [comment]
It is included in the library :) I'm asking because it may be possible that you have a folder that has the same name, so the library is looking to load that folder instead of [the weights we have on S3.](https://huggingface.co/allenai/longformer-base-4096)

**Comment by qianyingw** [comment]
@LysandreJik I don't have any existing folder called 'allenai/longformer-base-4096' (or 'bert-base-uncased' for BERT) and I can't load pretrained weights until I download them to my local machines
