### ISSUE TITLE
AssertionError: Padding_idx must be within num_embeddings

### ISSUE THREAD

**Issue by aranciokov** [huggingface/transformers#5381]
### Information

Model I am using: XLM

### To reproduce

```
from pytorch_transformers import XLMModel, XLMConfig, XLMTokenizer
model_class, tokenizer_class, pretrained_weights = (XLMModel, XLMTokenizer, 'xlm-mlm-en-2048')
config = XLMConfig.from_pretrained(pretrained_weights)
xlm_model = model_class.from_pretrained(pretrained_weights, config=config)
```

**Error:** 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/venv27/lib/python2.7/site-packages/pytorch_transformers/modeling_utils.py", line 536, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/username/venv27/lib/python2.7/site-packages/pytorch_transformers/modeling_xlm.py", line 545, in __init__
    self.embeddings = nn.Embedding(self.n_words, self.dim, padding_idx=self.pad_index)
  File "/home/username/venv27/lib/python2.7/site-packages/torch/nn/modules/sparse.py", line 88, in __init__
    assert padding_idx < self.num_embeddings, 'Padding_idx must be within num_embeddings'
AssertionError: Padding_idx must be within num_embeddings
```

### Expected behavior

Until recently (last I checked was 2 months ago, but since then I never updated anything), everything worked without issues and I was able to load the model with those 4 instructions easily (which is what I am expecting).

### Environment info

pytorch_transformers: 1.2.0

Python: 2.7

pytorch: 1.4.0

**Comment by LysandreJik** [comment]
I have no problem loading this in `transformers`. These files have not been updated in the past two months either; can you try doing the same in `transformers` or are you constrained by Python 2?

**Comment by aranciokov** [comment]
I'm constrained to Python 2 right now (due to a decently large codebase which I do not have enough time to upgrade to Py3 in these months), and that's why I'm using such an old version the library (which is the latest available for Py2).

**Comment by LysandreJik** [comment]
Hmm, okay I think I found the source of the issue. It seems the configuration file was indeed changed, the April 24th in a non-backwards compatible way (cc @julien-c). Very sorry about this.

In order to fix this you can use this JSON as a file on your machine:

```json
{
  "architectures": [
    "XLMWithLMHeadModel"
  ],
  "emb_dim": 2048,
  "n_layers": 12,
  "n_heads": 16,
  "dropout": 0.1,
  "attention_dropout": 0.1,
  "gelu_activation": true,
  "sinusoidal_embeddings": false,
  "asm": false,
  "bos_index": 0,
  "eos_index": 1,
  "pad_index": 2,
  "unk_index": 3,
  "mask_index": 5,
  "n_langs": 1,
  "n_words": 30145
}
```

and then load it as you did, but replacing the weights name with the filepath:

```py
from pytorch_transformers import XLMModel, XLMConfig, XLMTokenizer

model_class, tokenizer_class, pretrained_weights = (XLMModel, XLMTokenizer, 'xlm-mlm-en-2048')
config = XLMConfig.from_pretrained(PATH_TO_FILE)
xlm_model = model_class.from_pretrained(pretrained_weights, config=config)
```

**Comment by aranciokov** [comment]
Everything's working now (both the four-liner and my codebase as well!). Thanks!

**Comment by LysandreJik** [comment]
Glad you could make it work!
