### ISSUE TITLE
bart-large-cnn training related information

### ISSUE THREAD

**Issue by MaheshChandrra** [huggingface/transformers#5386]
# ❓ Questions & Help

Hi Team HuggingFace

Can we please know the training data set,,total number of summary pairs used and the configuration used to train BART Summarizer (facebook/bart-large-cnn).

Thanks in advance!!

**Comment by patil-suraj** [comment]
bart-large-cnn is trained on CNN/DM summarization dataset. See this for dataset info https://www.tensorflow.org/datasets/catalog/cnn_dailymail

**Comment by yjernite** [comment]
Also available in the Hugging Face `nlp` [library](https://huggingface.co/datasets/cnn_dailymail) :) 

You can explore the dataset [here](https://huggingface.co/nlp/viewer/?dataset=cnn_dailymail&config=3.0.0)

**Comment by jiacheng-xu** [comment]
The name is very confusing if it's trained on CNN and Dailymail but named as CNN (only without DM). Please consider changing the name.

**Comment by sshleifer** [comment]
sorry for the confusion. it's too late to change it and the name is copied from fairseq. it's trained on the cnn/dailymail dataset.

**Comment by hpasapp** [comment]
I feel that you answered the question about the dataset, but what about the training configuration used?
