### ISSUE TITLE
model.generate source code

### ISSUE THREAD

**Issue by chmod-700** [huggingface/transformers#5390]
Hi there,

I am trying to use BART to do NLG task. During my reading the BART tutorial on the website, I couldn't find the definition of 'model.generate()" function. Could you please add some explaination on that? thanks in advance

**Comment by mariamabarham** [comment]
`generate()` is defined in the `PretrainedModel` class here https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_utils.py#L872. Given that `BartModel`, `BartForConditionalGeneration`, etc,  inherit from `PretrainedModel` they all have access to this generate function. 

Hope this help?

**Comment by yjernite** [comment]
We actually just moved all of the `generate` functions to their own file:
https://github.com/huggingface/transformers/blob/c4d4e8bdbd25d9463d41de6398940329c89b7fb6/src/transformers/generation_utils.py#L101

**Comment by LHRYANG** [comment]
> We actually just moved all of the `generate` functions to their own file:
> 
> https://github.com/huggingface/transformers/blob/c4d4e8bdbd25d9463d41de6398940329c89b7fb6/src/transformers/generation_utils.py#L101

Hi, it seems that .generate() can only take input_ids as source input. I wonder whether input_embs can be used as input.

**Comment by nairbv** [comment]
in case anyone's still looking for the function, it has moved again and can currently be found here:

https://github.com/huggingface/transformers/blob/3e93dd295b5343557a83bc07b0b2ea64c926f9b4/src/transformers/generation/utils.py#L1342
