### ISSUE TITLE
Error Instantiating T5-11B from conributed models

### ISSUE THREAD

**Issue by lordtt13** [huggingface/transformers#5423]
# 🐛 Bug

## Information

Model I am using : T5-11B

Language I am using the model on: English

The problem arises when using:
when I try downloading the T5-11B model

The tasks I am working on is:
Evaluating ROGUE score on CNN dataset

## To reproduce

Just try instantiating the T5-11B model using the AutoModel Class

Error Message:
OSError: Can't load weights for 't5-11b'. Make sure that:

- 't5-11b' is a correct model identifier listed on 'https://huggingface.co/models'

- or 't5-11b' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.

## Expected behavior
Would instatntiate the 

## Environment info
- `transformers` version: 2.11.0
- Platform: Linux-5.3.0-61-generic-x86_64-with-glibc2.10
- Python version: 3.8.3
- PyTorch version (GPU?): 1.5.0 (True)
- Tensorflow version (GPU?): 2.2.0 (False)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by shamanez** [comment]
same result. I can't download

**Comment by julien-c** [comment]
Please see https://github.com/huggingface/transformers/issues/5986#issuecomment-663090043

**Comment by lordtt13** [comment]
Works when I use:

```python
import transformers

t5 = transformers.AutoModel.from_pretrained('t5-11b', use_cdn = False)
```

Thank You!
