### ISSUE TITLE
Bart EncoderLayer masked_fill not working properly with pytorch 1.4

### ISSUE THREAD

**Issue by mariamabarham** [huggingface/transformers#5424]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Bart 
I'm trying to use the EncoderLayer of Bart but I realized that `attn_weights = attn_weights.masked_fill(reshaped, float("-inf"))` at line [659](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_bart.py#L659) does not work when `reshaped` is an `int` or `float` tensor and throws the following error:
```
attn_weights = attn_weights.masked_fill(reshaped, float("-inf"))
RuntimeError: Expected object of scalar type Bool but got scalar type Float for argument #2 'mask' in call to _th_masked_fill_bool_
```
However it does not raise an error when I change `reshaped` type to bool but in that case it returns a tensor of `nan` values.

With @patrickvonplaten helps, we realized that it was related to a pytorch version because upgrading my torch version from 1.4 to 1.5 solved the problem

## To reproduce
```
from transformers.modeling_bart import EncoderLayer 
from transformers import BartConfig 
import torch 
hidden_states = torch.tensor(3 * [ 7 * [ 1024 * [0.4]]]) 
attn_mask = torch.ones(hidden_states.shape[:2]) 
layer = EncoderLayer(BartConfig()) 
layer(hidden_states.transpose(0, 1), attn_mask)  

```

## Environment info

     
- `transformers` version: 3.0
- Python version: 3.6
- PyTorch version (GPU?):1.4
- Using GPU in script?: no
- Using distributed or parallel set-up in script?:no

**Comment by wangcui123** [comment]
Hello,  I still hava this problem when my pytorch were upgraded  to 1.5 .  I don't know if it's related to the python version . 

Information
`  File "/home/ynos/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 3937, in multi_head_attention_forward
    float('-inf'),
RuntimeError: Expected object of scalar type Bool but got scalar type Long for argument #2 'mask' in call to _th_masked_fill_bool_
`

Environment info:

- Python version: 3.6.2

- PyTorch version (GPU):1.5
