### ISSUE TITLE
"Write With Transformer" not generating text (502 Bad Gateway)

### ISSUE THREAD

**Issue by flarn2006** [huggingface/transformers#5437]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): (Distil-)GPT2 on WriteWithTransformer

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [X] the official example scripts: Write With Transformer
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: Not sure what the task is called but it's WWT
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Attempt to use the autocomplete on Write With Transformer
2. Notice it appears to be loading forever
3. Open the browser console, go to the Network tab, and try again
4. Observe the "502 Bad Gateway" error

```
HTTP/1.1 502 Bad Gateway
Server: nginx/1.14.2
Date: Wed, 01 Jul 2020 12:14:42 GMT
Content-Type: text/html
Content-Length: 173
Connection: keep-alive
X-JeanClaude: True
Access-Control-Allow-Headers: Content-Type

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

## Expected behavior

The autocomplete should appear as normal.

## Environment info
You'd know that better than I do.

**Comment by julien-c** [comment]
@LysandreJik is rebooting the Raspberry Pi right now

**Comment by julien-c** [comment]
Joking, I mean the Hugging Face data center

**Comment by LysandreJik** [comment]
It's back up!

**Comment by flarn2006** [comment]
Thanks! It does work now, but it seems slower to respond and sometimes it times out. Do you happen to know whether this is on my end or yours?

**Comment by LysandreJik** [comment]
Yes, there seems to be an issue. I'm fixing restarting the server.

**Comment by flarn2006** [comment]
So I guess that would be why I just started getting 502 Bad Gateway again? :)

**Comment by LysandreJik** [comment]
Everything should be back to normal now. Thanks for letting us know!

**Comment by flarn2006** [comment]
Yep, I was using it earlier and it appears so. Glad I could help!
