### ISSUE TITLE
🐛 Can't use `AutoTokenizer` with `sshleifer/mbart-large-cc25`

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#5458]
# 🐛 Bug

From [`sshleifer/mbart-large-cc25`](https://huggingface.co/sshleifer/mbart-large-cc25) :

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("sshleifer/mbart-large-cc25")
```

---

Running this code yield an error :

>OSError: Model name 'sshleifer/mbart-large-cc25' was not found in tokenizers model name list (facebook/bart-large, facebook/bart-large-mnli, facebook/bart-large-cnn, facebook/bart-large-xsum). We assumed 'sshleifer/mbart-large-cc25' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.

---

Which Tokenizer should I use with this model ?

@sshleifer

**Comment by Colanim** [comment]
Ha, I didn't know the Tokenizer between Bart and mBart is different. I just noticed there is a class `MBartTokenizer`.

It seems like this class is not documented on [HuggingFace documentation](https://huggingface.co/transformers/model_doc/bart.html). Maybe we should consider adding it ?

_Also the model card for `sshleifer/mbart-large-cc25` may need an update_

---

Also, the following is still not working :

```python
from transformers import MBartTokenizer

tokenizer = MBartTokenizer.from_pretrained("sshleifer/mbart-large-cc25")
```

Only `tokenizer = MBartTokenizer.from_pretrained('facebook/mbart-large-en-ro')` seems to work.

**Can I use Tokenizer from checkpoint 'facebook/mbart-large-en-ro' for the model `sshleifer/mbart-large-cc25` ?**

**Comment by sshleifer** [comment]
mbart-large-cc25 does not work well yet, the PR is still open #3513.
Nonetheless these are all things I should fix, thanks!

**Comment by sshleifer** [comment]
For your second question, no. At the moment that tokenizer will not work well. Do you have fairseq cc25 working well?

**Comment by Colanim** [comment]
I didn't try the fairseq model, went directly for HF implementation ^^
