### ISSUE TITLE
Unable to use run_squad with xla_spawn.py on TPU

### ISSUE THREAD

**Issue by dhruvluci** [huggingface/transformers#5470]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):
Electra

Language I am using the model on (English, Chinese ...):
ENG

The problem arises when using:
* [ ] the official example scripts: RUN_squad.py + xla_spawn.py

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name): official SQUaD task

## To reproduce

1. Install pytorch-xla on colab using:
```
VERSION = "20200325"  #@param ["1.5" , "20200325", "nightly"]
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION
```
2. Trying to run_squad on colab TPUs using xla_spawn.py
```
python examples/xla_spawn.py --num_cores 8 \
   examples/question-answering/run_squad.py \
  --model_type electra \
  --model_name_or_path google/electra-base-discriminator \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file "/content/drive/My Drive/bert/train.json" \
  --predict_file "/content/drive/My Drive/bert/val.json" \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir "/content/drive/My Drive/bert/newdir6"

```

2. Error is thrown up
```
Traceback (most recent call last):
  File "examples/xla_spawn.py", line 72, in <module>
    main()
  File "examples/xla_spawn.py", line 68, in main
    xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)
AttributeError: module 'run_squad' has no attribute '_mp_fn'

```
## Expected behavior
Training should run properly using xla_spawn.py, which it does for GLUE tasks using:
```
python examples/xla_spawn.py --num_cores 8 \
	examples/text-classification/run_glue.py
```

## Environment info

     
- `transformers` version: 2nd July 2020 clone.
- Platform: Colab
- Python version: 3.8
- PyTorch version (GPU?): 20200325 (pytorch-xla)
- Tensorflow version (GPU?):N
- Using GPU in script?:N
- Using distributed or parallel set-up in script?:N

**Comment by LysandreJik** [comment]
Hi! The SQuAD example doesn't have trainer support yet. We're in the process of adding it. You can see the supported tasks [here](https://github.com/huggingface/transformers/tree/master/examples#the-big-table-of-tasks), only the tasks with Trainer, TFTrainer or pytorch-lightning support can run on TPU.
