### ISSUE TITLE
TFAutoModelForSequenceClassification: ValueError: Layer #1 (named "classifier") expects 2 weight(s), but the saved weights have 4 element(s).

### ISSUE THREAD

**Issue by TheophileBlard** [huggingface/transformers#5473]
# 🐛 Bug

## Information

`TFAutoModelForSequenceClassification` does not work on v3.0.0 / can't load a model that was working on v2.11.0

## To reproduce

- This work:

```python
!pip install transformers==2.11.0
from transformers import TFAutoModelForSequenceClassification
model = TFAutoModelForSequenceClassification.from_pretrained("tblard/tf-allocine")
```

but not this:
```python
!pip install transformers>=3.0.0
from transformers import TFAutoModelForSequenceClassification
model = TFAutoModelForSequenceClassification.from_pretrained("tblard/tf-allocine")
```

as it outputs:
```shell
ValueError: Layer #1 (named "classifier") expects 2 weight(s), but the saved weights have 4 element(s).
```

- Using `TFCamembertForSequenceClassification` instead of `TFAutoModelForSequenceClassification` also works.

- I couldn't find any other model using `TFAutoModelForSequenceClassification` on the model zoo to verify the issue does not come from the model itself. 

## Expected behavior

No errors.

## Environment info

Standard Google colab environment.

- `transformers` version: 3.0.0
- Platform: Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.1+cu101 (True)
- Tensorflow version (GPU?): 2.2.0 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by LysandreJik** [comment]
Hi! Thanks for opening this issue. This should have been fixed by https://github.com/huggingface/transformers/pull/5414.
