### ISSUE TITLE
Possible breaking undetected change to "data/processors/squad.py"

### ISSUE THREAD

**Issue by Santosh-Gupta** [huggingface/transformers#5478]
# ❓ Questions & Help

It looks like the squad data utils hasn't been updated to the new version.

https://github.com/huggingface/transformers/blob/fcf0652460753f8a81f7576e8abdaa6b3742f00e/src/transformers/data/processors/squad.py#L136

```
        encoded_dict = tokenizer.encode_plus(  # TODO(thom) update this logic
            truncated_query if tokenizer.padding_side == "right" else span_doc_tokens,
            span_doc_tokens if tokenizer.padding_side == "right" else truncated_query,
            truncation="only_second" if tokenizer.padding_side == "right" else "only_first",
            padding="max_length",
            max_length=max_seq_length,
            return_overflowing_tokens=True,
            stride=max_seq_length - doc_stride - len(truncated_query) - sequence_pair_added_tokens,
            return_token_type_ids=True,
        )
```

In squad utils, `encoded_dict` used to have a 'overflowing_tokens' key, but in the new version, all the overflowing tokens are returned as list of lists. But it looks like the data processor doesn't take this into account

```
        if "overflowing_tokens" not in encoded_dict or (
            "overflowing_tokens" in encoded_dict and len(encoded_dict["overflowing_tokens"]) == 0
        ):
            break
        span_doc_tokens = encoded_dict["overflowing_tokens"]
``` 

So this logic would interpret that there are no overflowing tokens since that key doesn't exist. 

The code I am working on is using version 2.11.0, doesn't have 'overflowing_tokens' either, but it doesn't have the list of lists like in version 3.0.0. It has something called 'overflow_to_sample_mapping', which returns only zeros, which I am not sure how to use. 

The 2.11.0 documentation doesn't mention this return value. (https://huggingface.co/transformers/v2.11.0/main_classes/tokenizer.html) . 

But it looks the data processor wouldn't give overflowing tokens or notice an issue for 2.11.0 as well. And it doesn't seem to have a method to get strided overflowing tokens.

**Comment by thomwolf** [comment]
Hi, overflowing tokens are handled differently between slow and fast tokenizers with fast tokenizers having better support.
Which kind of tokenizer are you using?

**Comment by Santosh-Gupta** [comment]
I am using the fask tokenizers

**Comment by thomwolf** [comment]
Ok, currently we don't handle overflowing in fast tokenizers with this processing script.
This is on the short term roadmap though.
