### ISSUE TITLE
What happened to https://huggingface.co/zero-shot/ ?

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#5498]
Hi, this page was very interesting. 
https://huggingface.co/zero-shot/

It is down since yesterday.
What is up with it? Do you plan to bring it up again?

**Comment by joeddav** [comment]
We're back up, and should now be setup to auto-restart when it fails now. Thanks for the heads up!

**Comment by PhilipMay** [comment]
Awsome! Thanks.

**Comment by mommi84** [comment]
Hi! It seems the page is down again.

**Comment by joeddav** [comment]
Man, streamlit's killing me. Thanks, rebooting now.

**Comment by mommi84** [comment]
Ouch, this means we users are indirectly killing you! Thanks a lot. 🙂

**Comment by Irtza** [comment]
This page is giving me a 502. reopen this issue, please

**Comment by joeddav** [comment]
Back up, and fixed the issue with auto-relaunch. Thanks for the heads up.

**Comment by alexeyev** [comment]
Hi! Thanks for the great demo!
The page seems to be down again.

**Comment by joeddav** [comment]
This time it was actually just me making some changes. Back up.

**Comment by ChrisPalmerNZ** [comment]
I am getting a timeout on it... so, still not available I think...
