### ISSUE TITLE
Longformer - Compression

### ISSUE THREAD

**Issue by Nouman97** [huggingface/transformers#5537]
Hello, I have trained a longformer model on my custom question answering dataset, and now I wanted to know if there is a way to compress this trained model?

Thank you!

**Comment by patrickvonplaten** [comment]
You could check out the example script under distillation: `/home/patrick/hugging_face/transformers/examples/distillation`

**Comment by patrickvonplaten** [comment]
Did you upload the model to the model hub? I would be great so that we can take a closer look :-)

**Comment by Nouman97** [comment]
Hello, thanks for the reply. I checked the train.py script under examples/distillation, but it seems that it does not cater to longformer models (the mentioned models within the script are BERT, RoBERTa, and GPT2). Yes, I have uploaded the model: https://s3.amazonaws.com/models.huggingface.co/bert/Nomi97/Chatbot_QA.
