### ISSUE TITLE
Easier way to download pretrained model files to local

### ISSUE THREAD

**Issue by m0hit-aggarwal** [huggingface/transformers#5538]
# ❓ Questions & Help

## Details

Is there any why we can save vocab and models files to local without having to run the following code with cache_dir parameter. What i am asking is some utility or some endpoint from where we could get a tar of all model files.
```
from transformers import BartTokenizer, BartForSequenceClassification
tokenizer = BartTokenizer.from_pretrained('facebook/bart-large',cache_dir='path/to/local_dir')
model = BartForSequenceClassification.from_pretrained('facebook/bart-large',cache_dir='path/to/local_dir')
```
The reason for such a requirement is, we run our code in VMs where there is no internet access, so we have to run the code in our local for every model and save files. It would be helpful if there is a easier way to download all the files for pretrained models as a tar or zip file.

**Comment by Jakobhenningjensen** [comment]
Any news on this? We have the same problem when running a Docker-container  (it takes a while to load the model all the time)

**Comment by LysandreJik** [comment]
Hey! The recommended way of handling that is to use `from_pretrained`/`save_pretrained` to a directory, and to load from that directory from then on.

If for some reason that's not sufficient, you can use the `huggingface_hub` library as shown in the [following guide](https://huggingface.co/docs/huggingface_hub/how-to-downstream). I believe repositories cannot be downloaded as zips currently, cc @osanseviero @julien-c
