### ISSUE TITLE
Fine Tuning Using /question-answering/run_squad.py

### ISSUE THREAD

**Issue by anirbansaha96** [huggingface/transformers#5539]
How do I use `/question-answering/run_squad.py` to fine-tune my own custom dataset?  

[StackOverflow][1]

[1]: https://stackoverflow.com/questions/62752709/how-to-fine-tune-bert-for-question-answering

**Comment by LysandreJik** [comment]
Hi, there's a [readme](https://github.com/huggingface/transformers/tree/master/examples/question-answering) in `question-answering`!

**Comment by anirbansaha96** [comment]
Yes, I've gone through this resource. What I want to achieve is to fine-tune on a custom resource and not on SQuAD dataset. I want to train it on Question-Answer pairs.
You can find more about the issue [here](https://ai.stackexchange.com/questions/22358/how-to-fine-tune-bert-for-question-answering/22362?noredirect=1#comment34182_22362).
