### ISSUE TITLE
incorrect typehint for PreTrainedTokenizer.convert_ids_to_tokens() return value

### ISSUE THREAD

**Issue by andifunke** [huggingface/transformers#5544]
# 🐛 Bug

## Information

The return value of `tokenization_utils.PreTrainedTokenizer.convert_ids_to_tokens()` is declared as `Union[int, List[int]]` while the method clearly returns a `Union[str, List[str]]` object type.

Would you like me to open a PR? ;)

Thanks for the great work!
Andreas

PS: Excuse me for skipping my system specs since this is a rather small issue and I'm just a bit annoyed by PyCharm's inspection warning on this ;)

**Comment by sgugger** [comment]
We want to make a clean patched release soon, so I opened #5551 to make sure it's fixed in it.
In the future, don't hesitate to directly open a PR for an issue with a clear fix like this :-)

**Comment by sgugger** [comment]
Closed via #5551
