### ISSUE TITLE
[Benchmark] TFGPT2LMHeadModel is five times slower than GPT2LMHeadModel

### ISSUE THREAD

**Issue by bjourne** [huggingface/transformers#5604]
Here are two scripts I ran. 
```python
from time import time
from transformers import TFGPT2LMHeadModel, GPT2Tokenizer
import tensorflow as tf

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = TFGPT2LMHeadModel.from_pretrained('gpt2')

text = "What are you doing after you have finished working?"
generated = tokenizer.encode(text)
context = tf.constant([generated])
past = None
start = time()
for i in range(100):
    output, past = model(context, past = past)
    logits = output[0, -1, :]
    tok = tf.argmax(logits)
    generated.append(tok.numpy())
    context = tf.expand_dims(tf.expand_dims(tok, 0), 0)
sequence = tokenizer.decode(generated)
print(time() - start, sequence)
```
and
```python
from time import time
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained('gpt2')

text = "What are you doing after you have finished working?"
generated = tokenizer.encode(text)
context = torch.tensor([generated])
past = None
start = time()
for i in range(100):
    output, past = model(context, past=past)
    token = torch.argmax(output[..., -1, :])
    generated += [token.tolist()]
    context = token.unsqueeze(0)
sequence = tokenizer.decode(generated)
print(time() - start, sequence)
```
On my computer with the models running on the cpu, the PyTorch version finishes in about six seconds while the TensorFlow version takes 30 seconds. So something must be wrong with the TF implementation because it shouldn't be that much slower.

**Comment by LysandreJik** [comment]
That's probably because you're in eager mode in your TensorFlow script. You can read about eager mode [here](https://www.tensorflow.org/guide/eager).

[Here's](https://docs.google.com/spreadsheets/d/1sryqufw2D0XlUH4sq3e9Wnxu5EAQkaohzrJbd5HdQ_w/edit#gid=0) a spreadsheet showcasing several model performances, you can check it out for GPT-2.

**Comment by bjourne** [comment]
The script runs even slower in graph execution mode.

**Comment by bjourne** [comment]
Same thing here:
```python
from time import time
from transformers import (TFGPT2LMHeadModel, GPT2Tokenizer,
                          GPT2LMHeadModel,
                          pipeline)

seed = "What are you doing after you have finished working?"
model = GPT2LMHeadModel.from_pretrained('gpt2')
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
gen = pipeline('text-generation',
               model = model,
               tokenizer = tokenizer)
start = time()
out = gen(seed, max_length = 100, num_return_sequences = 1)
print(time() - start, out)
```
Just changing `GPT2LMHeadModel` to `TFGPT2LMHeadModel` makes the program run 5 times slower.

**Comment by LysandreJik** [comment]
Oh, I see. Thanks for opening an issue, we're looking into it now.

**Comment by gyin-ai** [comment]
This same issue is also noticed in Tensorflow Serving. For example, the benchmark here shows the inference time is around 15ms. However, if we export the TFGPT2LMHeadModel for serving, the profile analysis shows that the `lm_logits = self.transformer.wte(hidden_states, mode="linear")` is extremely slow. https://www.tensorflow.org/tfx/serving/tensorboard
```
from transformers import TensorFlowBenchmark, TensorFlowBenchmarkArguments, GPT2Config

args = TensorFlowBenchmarkArguments(
    models=["gpt2", "distilgpt2", "qr_gpt2"],
    batch_sizes=[1], sequence_lengths=[8])

config_base = GPT2Config()
config_distil = GPT2Config.from_pretrained("distilgpt2")
benchmark = TensorFlowBenchmark(args, configs=[config_base, config_distil])
benchmark.run()
```
@patrickvonplaten The internal TF benchmark seems to only compute TFGPT2PreTrainedModel. Is it right?

**Comment by shiyongde** [comment]
same question

**Comment by gante** [comment]
Hi @shiyongde 👋 Yeah, we have just released a much faster TF generation. Check our blog post [here](https://huggingface.co/blog/tf-xla-generate).

Note that it is not yet compatible with `pipeline` (it is in our TODO list)
