### ISSUE TITLE
TextGenerationPipeline breaks when used with device=0

### ISSUE THREAD

**Issue by TevenLeScao** [huggingface/transformers#5622]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): model-agnostic (breaks with GPT2 and XLNet)

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
[x] my own modified scripts: (give details below)

The tasks I am working on is:
[x] my own task or dataset: plain old language generation

## To reproduce

```
#!/usr/bin/env python3
import random
from transformers import pipeline, XLNetLMHeadModel
import torch
import time
random.seed(0)
torch.manual_seed(0)

generator = pipeline("text-generation", model="xlnet-base-cased", tokenizer="xlnet-base-cased", device=0)
output_to_check = generator("Today is a beautiful day and I, ", offset=offset, do_sample=True, top_k=50, max_len=100)
```

## Expected behavior

What should happen : text generation
What actually happens : 

```
Traceback (most recent call last):
  File "/home/teven/dev_transformers/perso/transformers/generation_script.py", line 15, in <module>
    output_to_check = generator("Today is a beautiful day and I, ", offset=offset, do_sample=True, top_k=50, max_len=100)
  File "/home/teven/dev_transformers/perso/transformers/src/transformers/pipelines.py", line 692, in __call__
    generated_sequence = generated_sequence.numpy().tolist()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

Just missing a conversion before the `.numpy()` call

## Environment info

- `transformers` version: 3.0.2
- Platform: Linux-5.3.0-62-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by julien-c** [comment]
If that's not the case, we should make sure that the pipelines run on GPU in the GPU CI. (fast and slow), to catch things like this.
