### ISSUE TITLE
"How to train a new language model from scratch" colab stuck at training

### ISSUE THREAD

**Issue by iggygeek** [huggingface/transformers#5660]
Hello,
I am following the tutorial : https://huggingface.co/blog/how-to-train
At command :
trainer.train()
It gets stuck (Nothing displayed except "Using deprecated `--per_gpu_train_batch_size` argument").
Any idea ?

**Comment by patil-suraj** [comment]
Hi @iggygeek  not sure what the exact problem is, can you provide exact details, env info, transformers and torch version and probably your code (script or colab).
