### ISSUE TITLE
Request for Support to Adapt a Model (Human Dignity Observatory: Non-Profit Project) 

### ISSUE THREAD

**Issue by KnowmadInstitut** [huggingface/transformers#5663]
Dear @huggingface community from the Knowmad Institut we need your contribution and support for the Observatory of Human Dignity that we have developed.

You can access to the observatory here: (https://bit.ly/MQHHRRES)

We need your support to adapt the hugging face tools. We need to get the sentiments out of the content of the tweets and also (based on the data we have filtered out one by one) filter out the ones that are really human rights violations, like classifying from 1 to 5 with 1 being the one that looks the least like a human rights violation and 5 being the one that most matches the data we already have.

We thank the community and the @huggingface team for their support in disseminating this request for support.

|<center>[![FB18.png](https://knowmadinstitut.org/wp-content/uploads/2020/04/Black-and-Red-Geometric-Technology-Keynote-Presentation-1.png)](https://bit.ly/MQHHRRES) </center>|

<div class="center">

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Dear <a href="https://twitter.com/huggingface?ref_src=twsrc%5Etfw">@huggingface</a> community from the Knowmad Institut we need your contribution and support for the Observatory of Human Dignity that we have developed.<br><br>You can access to the observatory here: <a href="https://t.co/3TgKwjs3PJ">https://t.co/3TgKwjs3PJ</a><br><br>1/3 <a href="https://t.co/ly4Z139qHb">pic.twitter.com/ly4Z139qHb</a></p>&mdash; Knowmad Institut (@KnowmadInstitut) <a href="https://twitter.com/KnowmadInstitut/status/1280904300831612935?ref_src=twsrc%5Etfw">July 8, 2020</a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

</div>

**Comment by thomwolf** [comment]
Hi @KnowmadInstitut you should post this on the forum as well at https://discuss.huggingface.co/

**Comment by KnowmadInstitut** [comment]
> Hi @KnowmadInstitut you should post this on the forum as well at https://discuss.huggingface.co/

Thank you so much for the guidance, I'll get right on it.  :)
