### ISSUE TITLE
SquadDataset should use version number in cache file name

### ISSUE THREAD

**Issue by lazovich** [huggingface/transformers#5668]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): N/A

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts:
* [x] my own modified scripts: simple example code given below

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Load `SquadDataset` with `args.version_2_with_negative = False`. You will see the progress bars for creating cached features.

2. Load `SquadDataset` with `args.version_2_with_negative = True`. Rather than seeing it create a new cache for the v2 dataset, you will see it automatically use the already made cache file for v1.

Example code:

```
from transformers import AutoTokenizer
from transformers import SquadDataset
from transformers import SquadDataTrainingArguments

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
args = SquadDataTrainingArguments()

# FIXME: Change this path to your local SQuAD dataset path
args.data_dir = os.path.expanduser("~/.torch/nlp/SQuAD")

args.version_2_with_negative = False
squadv1 = SquadDataset(args, tokenizer)

args.version_2_with_negative = True
squadv2 = SquadDataset(args, tokenizer)
```
## Expected behavior

Separate cache files should be created for the v1.1 and v2 versions of SQuAD

## Environment info

- `transformers` version: 3.0.2
- Platform: Linux-5.0.0-1035-azure-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.7
- PyTorch version (GPU?): 1.5.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: N/A
- Using distributed or parallel set-up in script?: no

**Comment by LysandreJik** [comment]
closes by your own #5669 Thanks for your contribution :)
