### ISSUE TITLE
How to produce customized attention mask for BertModel?

### ISSUE THREAD

**Issue by null-id** [huggingface/transformers#5680]
# ❓ Questions & Help

## Details

The attention mask for BertModel needs a tensor sized (batch, seq-length). But what if I need to customize the attention for each token, just like UniLM, or some diagonal attention like GPT?

**Comment by null-id** [comment]
Is there any help?

**Comment by rudvlf0413** [comment]
@null-id I also want to know how to customize query-key attention mask. Did you solve the problem?
