### ISSUE TITLE
What is the decoder_input for encoder-decoder transformer in training time?

### ISSUE THREAD

**Issue by guotong1988** [huggingface/transformers#5682]
https://datascience.stackexchange.com/questions/76261/whats-the-input-dimension-for-transformer-decoder-during-training

Is the link's answer right?

Thank you very much!

**Comment by sshleifer** [comment]
The spirit of the answer is right. There is a lot more detail in this [blogpost](https://sshleifer.github.io/blog_v2/jupyter/2020/03/12/bart.html)

**Comment by sshleifer** [comment]
In the future, this would be a great Q for our forums: https://discuss.huggingface.co/ since it doesn't directly involve issues with the library.

**Comment by guotong1988** [comment]
Thank you again.
