### ISSUE TITLE
Is Writing With Transform open source?

### ISSUE THREAD

**Issue by DrAlta** [huggingface/transformers#5689]
I want to use Writing with Transform with my own model?  My first though was that I could just download it and modify the source to point to my model., but I can't find WWT anywhere in the repo. Do I have to publish my model then make a request for you to add it?

**Comment by clmnt** [comment]
If you add your model to the hub, you'll get the inference widget & API that you can use for demos or integration into your product: https://huggingface.co/docs

**Comment by julien-c** [comment]
We don't currently have short-term plans to open source Write With Transformers's frontend

Following up on what @clmnt said, we have an option (currently in private beta) for GPU acceleration of the inference API which would let you built similar (fast!) applications.
