### ISSUE TITLE
How I can  predict missing letters in a sentence, like " I want to b _ _  the car because it is cheap."

### ISSUE THREAD

**Issue by taicaile** [huggingface/transformers#5690]
Hi,

I am new on NLP, I want to predict missing letters in a sentence. Here is an example,

```text
I want to b _ _  the car because it is cheap.
```

**Comment by zanderbush** [comment]
I am not sure how to predict letters, but you can use BERT to predict words.

**Comment by julien-c** [comment]
I'd try to train a character-level model. Some of the Reformer models are pretrained in a char-level setting, if I remember correctly: https://huggingface.co/models?search=reformer

In the future however, this question is more suited to discuss.huggingface.co
