### ISSUE TITLE
Cannot import EvalPrediction from transformers

### ISSUE THREAD

**Issue by vanh17** [huggingface/transformers#5691]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):

Language I am using the model on (English, Chinese ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.  python3 ./examples/text-classification/run_glue.py     --model_name_or_path bert-base-uncased     --task_name $TASK_NAME     --do_train     --do_eval     --data_dir $GLUE_DIR/$TASK_NAME     --max_seq_length 128     --per_device_eval_batch_size=2       --per_device_train_batch_size=2       --learning_rate 2e-5     --num_train_epochs 3.0     --output_dir /tmp/$TASK_NAME/cd ../..

## Expected behavior

 
It should run normally but then give error: cannot import module EvalPrediction

## Environment info

     
- `transformers` version: 2.5.1
- Platform: Linux-4.4.0-165-generic-x86_64-with-debian-stretch-sid
- Python version: 3.6.5
- PyTorch version (GPU?): 1.2.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patil-suraj** [comment]
Hi @vanh17 , your transformers version is old, `EvalPrediction` is not available in 2.5.1. You can install transformers from source and then run the examples.
