### ISSUE TITLE
Add beta 1 and beta 2 option in `TrainingArguments` for `AdamW` optimizer.

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#5699]
I want to set the Adam Optimizers beta 2 to 0.98 - this is because I want to train a new RoBERTa LM. The paper sais, that it improves stability. The default is 0.999 and it can not be set in `TrainingArguments`.

Could you please add the option to specify beta 1 and 2 for AdamW in the `TrainingArguments`? `adam_epsilon ` can already be specified. If you want me to I can provide a PR.

What do you think?

**Comment by patrickvonplaten** [comment]
I'm not sure we would like to add this to the `TrainingArguments`. If we add all possible params this could quickly explode. Note that you can instantiate your own optimizer and pass it here: https://github.com/huggingface/transformers/blob/7096e47513127d4f072111a7f58f109842a2b6b0/src/transformers/trainer.py#L158

Also pinging @julien-c here.

**Comment by PhilipMay** [comment]
Well - my arguments for this change are that is adam_epsilon is possible to set beta 1 and 2 should also be possible to set. Especialy because the RoBERTa paper suggests an others setting then default. 

2nd argument is that it is not that easy to instantiate your own optimizer because there is a dependency to `model`. See here: https://github.com/huggingface/transformers/blob/7096e47513127d4f072111a7f58f109842a2b6b0/src/transformers/trainer.py#L326

```python
        optimizer_grouped_parameters = [
            {
                "params": [p for n, p in self.model.named_parameters() if not any(nd in n for nd in no_decay)],
                "weight_decay": self.args.weight_decay,
            },
            {
                "params": [p for n, p in self.model.named_parameters() if any(nd in n for nd in no_decay)],
                "weight_decay": 0.0,
            },
        ]
```

**Comment by julien-c** [comment]
Closing this in favor of #5592
