### ISSUE TITLE
How to generate sentences from Transformer's sentence embeddings?

### ISSUE THREAD

**Issue by willanxywc** [huggingface/transformers#5701]
Is it possible to use the pre-trained transformer models to generate sentences from sentence embeddings?
I konw I can get the continuous representations of a sentence with for example BertModel or GPT2Model.
But can I reconstruct the sentence directly from the sentence representations generated by BertModel, with hugging-face transformer, especially the pre-trained ones?
I mean sentence embeddings as input, the readable sentence as output.

**Comment by patrickvonplaten** [comment]
Sorry I'm not 100% sure, I get the question. Could you specify what you mean by `sentence embeddings` exactly and the output you would like with some code? :-)
