### ISSUE TITLE
help：OSError: Model name 'ctrl' was not found in tokenizers model name list (ctrl). We assumed 'ctrl' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.

### ISSUE THREAD

**Issue by Heiheiyo** [huggingface/transformers#5702]
# ❓ Questions & Help
![image](https://user-images.githubusercontent.com/15426714/87268409-dd30ff80-c4fc-11ea-9e34-4d1c06dc1d23.png)

**Comment by Kreijstal** [comment]
As for me, I'm getting 
```
OSError: Can't load weights for 'mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es'. Make sure that:

- 'mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es' is the correct path to a directory containing a file named one of tf_model.h5, pytorch_model.bin.
```

the line of code is 
```
nlp = pipeline(
    'question-answering', 
    model='mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es',
    tokenizer=(
        'mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es',  
        {"use_fast": False}
    )
)
```
but my question is, why does pipeline download but can't load the weights?? I'm using python:3.7 dockerimage.

**Comment by LysandreJik** [comment]
@Heiheiyo, is it possible you have a `ctrl` folder that does not contain the vocab and merges files?
When running your command on master I have no issues with CTRL.

**Comment by LysandreJik** [comment]
@Kreijstal, on what version of transformers are you running? I copy-pasted your command and it works fine on the `master` branch.

**Comment by Heiheiyo** [comment]
> @Heiheiyo, is it possible you have a `ctrl` folder that does not contain the vocab and merges files?
> When running your command on master I have no issues with CTRL.
Thank you for your answer.I have solved this problem.I downloaded the ctrl model and modified the model file path

**Comment by Heiheiyo** [comment]
@LysandreJik Thank you for your answer.I have solved this problem.I downloaded the ctrl model and modified the model file path.

**Comment by Kreijstal** [comment]
@LysandreJik I solved this problem too, I used the dockerfiles I found on this repo to figure out the right libraries that might not have been installed
