### ISSUE TITLE
Span Mask Fill

### ISSUE THREAD

**Issue by zanderbush** [huggingface/transformers#5707]
I see that Transformers does not support Ernie, but am in search of a way to [MASK] phrases. Can somebody guide me to an alternative to Ernie, code, or a way I could do this myself?

**Comment by RudrakshTuwani** [comment]
Maybe you can get inspiration from here: https://github.com/facebookresearch/SpanBERT

**Comment by zanderbush** [comment]
> Maybe you can get inspiration from here: https://github.com/facebookresearch/SpanBERT

@RudrakshTuwani 

Thank you for your response. I've actually tried to implement SpanBERT previously, but my status as a beginner must have barred me from doing it properly. 

While SpanBERT has "the same format as the HuggingFace BERT models", the outputs were only special tokens or letters.
