### ISSUE TITLE
Cannot preprocess WNUT'17 dataset for token-classification

### ISSUE THREAD

**Issue by kushalj001** [huggingface/transformers#5722]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):BERT

Language I am using the model on (English, Chinese ...):

The problem arises when using:
* [x] the official example scripts: I am trying to run the run_ner.py script for the WNUT’17 dataset. I followed the preprocessing steps mentioned in the README. I just downloaded the dev dataset. The command  
`python3 scripts/preprocess.py data_wnut_17/dev.txt.tmp $BERT_MODEL $MAX_LENGTH > data_wnut_17/dev.txt`   
does not work and my terminal hangs.
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: Token Classification
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Move into the `token-classification` folder in the `examples` directory.
2. Run the commands for the WNUT’17 dataset as mentioned in the README. 
```
mkdir -p data_wnut_17
curl -L 'https://github.com/leondz/emerging_entities_17/raw/master/emerging.dev.conll' | tr '\t' ' ' > data_wnut_17/dev.txt.tmp
export MAX_LENGTH=128
export BERT_MODEL=bert-large-cased
```
3. The terminal hangs on the next command
`python3 scripts/preprocess.py data_wnut_17/dev.txt.tmp $BERT_MODEL $MAX_LENGTH > data_wnut_17/dev.txt`   

## Expected behavior

I would expect the `preprocess.py` script to execute normally and return the control of the terminal back to me. Once hung, I fail to regain control of my command-line even by `ctrl-d/z/c`. 
## Environment info

     
- `transformers` version:
- Platform: Ubuntu 18.04
- Python version: 3.7.8
- PyTorch version (GPU?): 1.5 (Yes)
- Tensorflow version (GPU?): - 
- Using GPU in script?: The error does not involve GPU usage in the script.
- Using distributed or parallel set-up in script?: No

**Comment by TarasPriadka** [comment]
@kushalj001 It may take a while to preprocess the whole dataset. Not sure if you waited long enough. Check if your have enough RAM when you are doing this since if the dataset is too large you might run out of memory.
