### ISSUE TITLE
FileNotFoundError: File not found when running run_squad.py to fine-tune the BERT on  SQuAD v1.1.

### ISSUE THREAD

**Issue by YLW996** [huggingface/transformers#5741]
Hi, I am just following this tutorial https://github.com/huggingface/transformers/tree/master/examples/question-answering and created a folder named SQUAD_DIR under transformers. The train and test file were downloaded and put into the SQUAD_DIR folder. But the error is that such a file can not be found.

**Comment by YLW996** [comment]
This is the code:
!git clone https://github.com/huggingface/transformers
%cd transformers
!pip install .
!pip install -r ./examples/requirements.txt

!mkdir SQUAD_DIR
!wget https://rajpurkar.github.io/SQuAD-explorer/dataset/train-v1.1.json -o SQUAD_DIR/train-v1.1.json
!wget https://rajpurkar.github.io/SQuAD-explorer/dataset/dev-v1.1.json -o SQUAD_DIR/dev-v1.1.json
!export SQUAD_DIR=/path/to/SQUAD

!python ./examples/question-answering/run_squad.py \
  --model_type bert \
  --model_name_or_path bert-base-uncased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file $SQUAD_DIR/train-v1.1.json \
  --predict_file $SQUAD_DIR/dev-v1.1.json \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /tmp/debug_squad/

**Comment by YLW996** [comment]
![image](https://user-images.githubusercontent.com/61152762/87414718-15e7dc00-c5c4-11ea-86b1-68cf88163db3.png)

**Comment by LysandreJik** [comment]
This is a mismatch between the file location and what you're indicating to the script. Are you sure you're pointing to the correct directory? If so, can you try using absolute paths?
