### ISSUE TITLE
T5 fine-tuned model doesn't appear in the model hub

### ISSUE THREAD

**Issue by mrm8488** [huggingface/transformers#5754]
Hi guys,
I have fine-tuned T5-base on wikiSQL dataset and uploaded it to HF model hub. The problem is that the model doesn't appear there. AFAIK it is because the config file is not right. Should I change anything?

Thanks.

**Comment by julien-c** [comment]
I can see it now: https://huggingface.co/mrm8488/t5-base-finetuned-wikiSQL

Let us know if something looks wrong (otherwise, feel free to close)

**Comment by mrm8488** [comment]
Everything right. Maybe I searched it too soon and was not indexed yet.
