### ISSUE TITLE
How to get parameters from a Query.

### ISSUE THREAD

**Issue by thiagomoeng** [huggingface/transformers#5767]
# ❓ Questions & Help

Hi maybe someone can help me with a problem, I need to get parameters from a query.
I already use question answering pipeline to identify a report and now I want to get some parameters to use as filter, example:
 
Query: How many electric cars sold in 2019?

Output: (Item: eletric cars / Year:2019)

**Comment by LysandreJik** [comment]
It seems you're trying to identify entities in your query? You could use an NER model to do so, but I'm not sure the entities the NER models on the hub are trained on would work in your use-case. You can still check them out, and check the [NER script](https://github.com/huggingface/transformers/tree/master/examples/token-classification) if you want to train a model with your data.
