### ISSUE TITLE
GPT2 weights don't initialize from checkpoint

### ISSUE THREAD

**Issue by almaLindborg** [huggingface/transformers#5800]
OS: OSX 10.15.5 (Catalina)
Transformers version 3.0.2

I'm running into this warning when I'm trying to initialize a pre-trained GPT2 model. 
This looks a bit worrying to me because it looks like like it ignores all the pre-trained attention heads, or am I missing something here? 

<img width="1087" alt="Screenshot 2020-07-16 at 11 19 10" src="https://user-images.githubusercontent.com/8694790/87654081-b837c900-c756-11ea-925e-106314ad9942.png">

Any idea of what's gone wrong? I've been running the same code on another computer earlier without encountering this problem, but on my current setup I haven't been able to get around it. I also tried deleting the downloaded files from the cache and re-loading the models with no luck.

Any help is very appreciated!

**Comment by patrickvonplaten** [comment]
Hey @almaLindborg,

This is a known warning. We should probably disable this...a couple of other models have it as well. But the model works as intended, so no worries about the message.

Also pinging @sshleifer for notification.
