### ISSUE TITLE
Hosted Inference API: Error loading tokenizer Can't load config

### ISSUE THREAD

**Issue by sampathkethineedi** [huggingface/transformers#5803]
Hi,

[https://huggingface.co/sampathkethineedi/industry-classification-api](https://huggingface.co/sampathkethineedi/industry-classification-api)

I uploaded my classification model fine tuned on BERT. There is no issue running the model from the hub and using the ‘sentiment-analysis’ pipeline. But there seems to be some problem when it comes to Hosted Inference API.

```
Error loading tokenizer Can't load config for 'sampathkethineedi/industry-classification-api classification'. Make sure that: - 'sampathkethineedi/industry-classification-api' is a correct model identifier listed on 'https://huggingface.co/models' - or 'sampathkethineedi/industry-classification-api' is the correct path to a directory containing a config.json file OSError("Can't load config for 'sampathkethineedi/industry-classification-api'. Make sure that:\n\n- 'sampathkethineedi/industry-classification-api' is a correct model identifier listed on 'https://huggingface.co/models'\n\n- or 'sampathkethineedi/industry-classification-api' is the correct path to a directory containing a config.json file\n\n")
```

Can someone help me with this?

Thanks!

**Comment by julien-c** [comment]
I can load the pipeline locally so I am not sure what's happening here, indeed.

**Comment by sampathkethineedi** [comment]
Hey @julien-c, thanks for the quick response!

I'm assuming the inference API is using the `transformers-cli serve` ?
When I do the same locally, I'm able to get results at **localhost:8888/forward** using `POST -d {"inputs": ["< Text >"]}` 
But when I try it on the https://api-inference.huggingface.co/models/sampathkethineedi/industry-classification-api, it doesn't work.

The Hosted Inference API has the same structure as `transformers-cli serve` or is it any different?

**Comment by sampathkethineedi** [comment]
[https://huggingface.co/sampathkethineedi/industry-classification-api](https://huggingface.co/sampathkethineedi/industry-classification-api)

I just checked and the API is working. Would love to know what was causing the issue. Closing the issue.

**Comment by papasanimohansrinivas** [comment]
@sampathkethineedi can i get dataset u trained on
