### ISSUE TITLE
BERT-viewer is broken for russian?

### ISSUE THREAD

**Issue by Dronte** [huggingface/transformers#5806]
# 🐛 Bug
Hi I'm looking at BERT demos for russian, for example:
https://huggingface.co/DeepPavlov/rubert-base-cased?text=%D0%AF+%5BMASK%5D+%D1%81%D0%B0%D0%BB%D0%B0%D1%82+%D0%BD%D0%B0+%D0%BE%D0%B1%D0%B5%D0%B4.

English version for comparison:
https://huggingface.co/bert-base-cased?text=I+%5BMASK%5D+salad+for+lunch.

In the first link all token scores are 0.0 and they are absolute rubbish. Is everything fine with the viewer or the model?

**Comment by julien-c** [comment]
I don't see anything obviously wrong on our side, so you should ask the model authors (@deeppavlov and other members of @deepmipt) – maybe they uploaded the model without a trained final LM prediction layer, for instance.

Off topic, but e.g. by contrast this translation model works very well for russian: https://huggingface.co/Helsinki-NLP/opus-mt-ru-en?text=%D0%A3+%D0%BC%D0%B5%D0%BD%D1%8F+%D0%B1%D1%8B%D0%BB+%D1%81%D0%B0%D0%BB%D0%B0%D1%82+%D0%BD%D0%B0+%D0%BE%D0%B1%D0%B5%D0%B4

**Comment by yurakuratov** [comment]
Hi!
We (DeepPavlov) might have a problem with Russian model that was uploaded to HugginFace and we need to check it.
Everything should be okay with MLM head if you use checkpoints from here:
http://docs.deeppavlov.ai/en/master/features/pretrained_vectors.html#downloads
