### ISSUE TITLE
Migrate Marian models names to ISO-639-3 where possible

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#5820]
Proposed renamings:

ROMANCE-> roa
CELTIC -> cel
NORWAY -> no  (check for conflicts w existing bilingual norwegian models.)
remove ch_group

@julien-c for NORTH_EU, why is the code ["multilingual"](https://github.com/huggingface/moon-landing/blob/d50efc4725a7546fb8159626470f3babacd44911/server/lib/ModelInfo.ts#L134-L170)
Should it be the same for all groups that do not map cleanly to an iso-639-3 group?

I will do this via mv, not cp, unless anyone objects.
cc @julien-c 

Unresloved:
how will people know if a model requires a target language code?
we will still have many cases where model name is not a language code.

**Comment by julien-c** [comment]
> for NORTH_EU, why is the code "multilingual"

Couldn't find a better qualifier and I think there were a lot of languages

> how will people know if a model requires a target language code?

How do they know now? Maybe add it to the model card? or you could detect if `code.includes('_')`?

> we will still have many cases where model name is not a language code.

Not that many, right?
