### ISSUE TITLE
ValueError: DataLoader with IterableDataset: expected unspecified sampler option,

### ISSUE THREAD

**Issue by Pradhy729** [huggingface/transformers#5829]
# 🐛 Bug

## Information

This is in regards to the `Trainer` object. The `get_train_dataloader` function uses RandomSampler or Distributed sampler, both of which I believe won't work with an [iterable datasets](https://pytorch.org/docs/stable/data.html#iterable-style-datasets) - which are only compatible with InfiniteConstantSampler see [pytorch documentation](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataloader.html#DataLoader)

https://github.com/huggingface/transformers/blob/d088d744adb4e5aa45262a34acab3ae9e81de169/src/transformers/trainer.py#L229-L242

## Steps to reproduce the behavior:
1. Create an Iterable dataset and pass it to trainer object.

Gives the following error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed eval> in <module>

~/.conda/envs/my_root/lib/python3.6/site-packages/transformers/trainer.py in train(self, model_path)
    382                 training will resume from the optimizer/scheduler states loaded here.
    383         """
--> 384         train_dataloader = self.get_train_dataloader()
    385         if self.args.max_steps > 0:
    386             t_total = self.args.max_steps

~/.conda/envs/my_root/lib/python3.6/site-packages/transformers/trainer.py in get_train_dataloader(self)
    247             sampler=train_sampler,
    248             collate_fn=self.data_collator,
--> 249             drop_last=self.args.dataloader_drop_last,
    250         )
    251 

~/.conda/envs/my_root/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __init__(self, dataset, batch_size, shuffle, sampler, batch_sampler, num_workers, collate_fn, pin_memory, drop_last, timeout, worker_init_fn, multiprocessing_context)
    177                 raise ValueError(
    178                     "DataLoader with IterableDataset: expected unspecified "
--> 179                     "sampler option, but got sampler={}".format(sampler))
    180             elif batch_sampler is not None:
    181                 # See NOTE [ Custom Samplers and IterableDataset ]

ValueError: DataLoader with IterableDataset: expected unspecified sampler option, but got sampler=<torch.utils.data.sampler.RandomSampler object at 0x7fff5803b2b0>

## Expected behavior

Ideally, we should check if the dataset is an iterable dataset and if so, pass no sampler to the dataloader. Or allow the option of passing in our own sampler to the trainer.

## Environment info

- `transformers` version: 3.0.2
- Platform: Linux-4.4.121-92.104-default-x86_64-with-SuSE-12-x86_64
- Python version: 3.6.10
- PyTorch version (GPU?): 1.5.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: NO
- Using distributed or parallel set-up in script?: NO

I can contribute and create a PR to fix this. Let me know.

**Comment by j-rossi-nl** [comment]
Hi,
I'm using `Trainer` with a `IterableDataset` and there is yet another exception raised when calling `train()`
Maybe you will want to create a new issue.
I see that your commit has changed the behavior (it used to stop on the same exception but earlier in the code, while instantiating the `Sampler` object), but there is still some code expecting to get a `len()` from the dataset.

My code:
```
def main():
    parser = HfArgumentParser((ModelArguments, TrainingArguments))
    model_args, train_args = parser.parse_args_into_dataclasses()
    model_args: ModelArguments

    # Setup logging
    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s -   %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.WARN,
    )
    logger.warning(
        "Process rank: %s, device: %s, n_gpu: %s, distributed training: %s, 16-bits training: %s",
        train_args.local_rank,
        train_args.device,
        train_args.n_gpu,
        bool(train_args.local_rank != -1),
        train_args.fp16,
    )
    logger.info("Training/evaluation parameters %s", train_args)

    MODEL_NAME = 'allenai/longformer-base-4096'
    tokenizer: LongformerTokenizerFast = LongformerTokenizerFast.from_pretrained(model_args.tok_dir)

    # Customize an existing config rather than create from scratch
    config: LongformerConfig = LongformerConfig.from_pretrained(MODEL_NAME)
    config.max_position_embeddings = model_args.max_seq_len + 2
    config.num_hidden_layers = model_args.num_hidden_layers
    config.attention_window = [512] * model_args.num_hidden_layers
    config.vocab_size = tokenizer.vocab_size
    model = LongformerForMaskedLM(config)

    data_files = list(Path(model_args.txt_dir).glob(model_args.filter_files))
    shuffled_files = random.sample(data_files, len(data_files))
    train_files, val_files = train_test_split(shuffled_files, test_size=model_args.test_size)

    train_ds, val_ds = list(
        map(
            lambda x: MultiTextDataset(
                files=x,
                tokenizer=tokenizer,
                block_size=model_args.max_seq_len
            ),
            [train_files, val_files]
        )
    )

    data_collator = DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=True,
        mlm_probability=0.15
    )

    train_args: TrainingArguments
    train_args.do_train = True
    train_args.evaluate_during_training = True

    trainer = Trainer(
        model=model,
        args=train_args,
        data_collator=data_collator,
        train_dataset=train_ds,
        eval_dataset=val_ds,
    )

    trainer.train(train_args.output_dir)
```

Stack Trace:

```
  File "longformer_pretrain.py", line 122, in main
    trainer.train(train_args.output_dir)
  File "/home/jrossi/anaconda3/envs/COLIEE/lib/python3.7/site-packages/transformers/trainer.py", line 392, in train
    self.args.max_steps // (len(train_dataloader) // self.args.gradient_accumulation_steps) + 1
  File "/home/jrossi/anaconda3/envs/COLIEE/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 313, in __len__
    length = self._IterableDataset_len_called = len(self.dataset)
TypeError: object of type 'MultiTextDataset' has no len()
```
`Multitext` is a class that inherits `IterableDataset`. It yields blocks of text from a list of files, one at a time
I installed transformers from source this morning:
```
git clone https://github.com/huggingface/transformers
cd transformers
pip install --no-cache-dir .
```
Environment Info:

- transformers 3.0.2 (from source, master, 23/07 09:00 CET)
- Linux 5.7.8-1.el7.elrepo.x86_64
- Python 3.7.7
- Pytorch 1.5.1 GPU Cuda 10.2
- Tensorflow: not installed
- Using GPU in script: YES
- Distributed or Parallel: NO

**Comment by LysandreJik** [comment]
Thanks for the fix with #5834 :)

**Comment by avercau** [comment]
The same issue exists for _get_eval_sampler... I patched the Trainer in the mean time, but it would be good if it were fixed.

**Comment by LysandreJik** [comment]
Hi @avercau can you open an issue with your problem? Thank you
