### ISSUE TITLE
ImportError: cannot import name 'BERT_PRETRAINED_MODEL_ARCHIVE_MAP' from 'transformers'

### ISSUE THREAD

**Issue by lethienhoa** [huggingface/transformers#5842]
Hi,

I'm rerunning the code BERT-E2E-ABSA from https://github.com/lixin4ever/BERT-E2E-ABSA, which is based on transformers 2.0.0

I installed the latest transformers 3.0.2 (both from pip and souce) and I have an error that I can not import BERT_PRETRAINED_MODEL_ARCHIVE_MAP.
This simple command will result in errors below:
> python -c "from transformers import BERT_PRETRAINED_MODEL_ARCHIVE_MAP"

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: cannot import name 'BERT_PRETRAINED_MODEL_ARCHIVE_MAP' from 'transformers' (/home/hoa/transformers/src/transformers/__init__.py)

Transformer is well installed as it can do the following:
> python -c "from transformers import pipeline; print(pipeline('sentiment-analysis')('I hate you'))"
> [{'label': 'NEGATIVE', 'score': 0.9991129040718079}]

Do you know why ? Did I miss something ?

- `transformers` version: 3.0.2
- Platform: Linux-5.4.0-1019-gcp-x86_64-with-debian-bullseye-sid
- Python version: 3.7.7
- PyTorch version (GPU?): 1.2.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
- Other configurations: Ubuntu 20.04, Python 3.7, CUDA 11

Note: I even installed pytorch on cpu laptop and rerun, still had the same issue !

**Comment by patrickvonplaten** [comment]
Yeah, there was a breaking change. The name has been changed to `BERT_PRETRAINED_MODEL_ARCHIVE_LIST`.

See https://github.com/huggingface/transformers/pull/4636.

**Comment by dhirajprai** [comment]
ImportError: cannot import name 'BertweetTokenizer' from 'transformers' (/opt/conda/lib/python3.7/site-packages/transformers/__init__.py)

**Comment by Naren-Durbha** [comment]
ImportError: cannot import name 'SquadExample' from 'transformers' (unknown location)

I get this error when I try to import QuestionAnsweringModel from simpletransformers.question_answering

Any help would be appreciated!
