### ISSUE TITLE
AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'

### ISSUE THREAD

**Issue by lethienhoa** [huggingface/transformers#5848]
Hi,

After changing from `BERT_PRETRAINED_MODEL_ARCHIVE_MAP` to `BERT_PRETRAINED_MODEL_ARCHIVE_LIST` in #5842 , I encountered another issue:

>   File "main.py", line 24, in <genexpr>
>     ALL_MODELS = sum((tuple(conf.pretrained_config_archive_map.keys()) for conf in (BertConfig, XLNetConfig)), ())
> AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'

Is it also a breaking change ?
What is the replacing name for `pretrained_config_archive_map` now ?

Thank you,

**Comment by lethienhoa** [comment]
it'd better to downgrade the version: pip install transformer==2.0.0 (which solves the compatible issue).

**Comment by Irtza** [comment]
`$ pip install transformers==2.0.0`

works

**Comment by tengerye** [comment]
Hi, is there any other approach other than downgrading?

**Comment by wang-h** [comment]
try
from transformers import ALBERT_PRETRAINED_CONFIG_ARCHIVE_MAP
or 
from transformers import BERT_PRETRAINED_CONFIG_ARCHIVE_MAP

**Comment by LysandreJik** [comment]
Hi! Could you let us know the use cases of using the archive maps?

**Comment by wang-h** [comment]
Hi, 
<img width="712" alt="截屏2021-02-26 下午9 38 01" src="https://user-images.githubusercontent.com/7147150/109307249-49d5f000-787b-11eb-91eb-f076046f180a.png">
I used it to provide the hint of cmd args configuration.

**Comment by LysandreJik** [comment]
I see, thank you! The issue is that these archive maps are outdated and don't mean much since the model hub.

In that case, it would be better to have a way to see all checkpoints on the hub corresponding to that model architecture, right?

**Comment by dattnguyen** [comment]
Sorry for bringing this up again but I came into this error and don't want to downgrade the version (which led to another issue). I tried what wang-h suggested but it didn't work. Does anyone have a suggestion? Thanks!

**Comment by hemangjoshi37a** [comment]
If anyone has already solved the issue please let me know. I am having same issue.
https://hjlabs.in

**Comment by hemangjoshi37a** [comment]
`$from transformers import ALBERT_PRETRAINED_CONFIG_ARCHIVE_MAP`
this solved my issue. Thank you everyone for support. you are great.
https://hjlabs.in

**Comment by zhanwenchen** [comment]
For legacy codebases, you could store a static tuple of `ALL_MODELS` evaluated from a downgraded `transformers`:

```python
ALL_MODELS = ('bert-base-uncased', 'bert-large-uncased', 'bert-base-cased', 'bert-large-cased', 'bert-base-multilingual-uncased', 'bert-base-multilingual-cased', 'bert-base-chinese', 'bert-base-german-cased', 'bert-large-uncased-whole-word-masking', 'bert-large-cased-whole-word-masking', 'bert-large-uncased-whole-word-masking-finetuned-squad', 'bert-large-cased-whole-word-masking-finetuned-squad', 'bert-base-cased-finetuned-mrpc', 'bert-base-german-dbmdz-cased', 'bert-base-german-dbmdz-uncased', 'bert-base-japanese', 'bert-base-japanese-whole-word-masking', 'bert-base-japanese-char', 'bert-base-japanese-char-whole-word-masking', 'bert-base-finnish-cased-v1', 'bert-base-finnish-uncased-v1', 'roberta-base', 'roberta-large', 'roberta-large-mnli', 'distilroberta-base', 'roberta-base-openai-detector', 'roberta-large-openai-detector', 'albert-base-v1', 'albert-large-v1', 'albert-xlarge-v1', 'albert-xxlarge-v1', 'albert-base-v2', 'albert-large-v2', 'albert-xlarge-v2', 'albert-xxlarge-v2')
```

**Comment by LannyCodes** [comment]
> transformers==2.0.0

when I download to 2.0.0,the progress pause ，does has other solutions to help it ?
