### ISSUE TITLE
Silenced error while downloading pretrained model

### ISSUE THREAD

**Issue by festeh** [huggingface/transformers#5869]
# 🐛 Bug

Currently, if user failed to download a model, they will receive uninformative and confusing message (see #5787). This is most hurting for users behind a proxy. This happens because of this [line](https://github.com/huggingface/transformers/blob/0533cf470659b97c6279bd04f65536a1ec88404a/src/transformers/file_utils.py#L681). My opinion is that there should be at least a warning, and if `force_download` is `True`, then error should be raised. I can make a PR if you agree with that.

**Comment by julien-c** [comment]
This sounds reasonable
