### ISSUE TITLE
Reading transformer package from local codes and NOT the pip installed version

### ISSUE THREAD

**Issue by vikas95** [huggingface/transformers#5888]
Hi @sshleifer ,

There seem to be a problem of python package structure. I am getting an error similar to a previous issue (https://github.com/huggingface/transformers/issues/5303) but with the token_classification/run_ner.py file.

File "examples/token-classification/run_ner.py", line 42, in
from modeling_auto import AutoModelForTokenClassification
File "transformers/src/transformers/modeling_auto.py", line 22, in
from .configuration_auto import (
ImportError: attempted relative import with no known parent package

I have not installed transformers library using pip because I want to use the local codes (cloned from transformers library). After reading various stackoverflow suggestions (https://stackoverflow.com/questions/16981921/relative-imports-in-python-3 and https://napuzba.com/a/import-error-relative-no-parent), I believe that when I am importing the transformer package locally from my own directory, then it is not able read+load transformer as a package.

I am using python3.7

Can you please suggest how to read transformer as a package from local codes.

Thanks...

**Comment by Colanim** [comment]
How did you install the package ?

According to the [README](https://github.com/huggingface/transformers#from-source) you should do :

```console
git clone https://github.com/huggingface/transformers
cd transformers
pip install -e .
```

**Comment by vikas95** [comment]
Hi ,

Apologies for raising this issue, the error was something specific to singularity images that I have been using to run transformers on HPC. 
Please pardon this issue. 

Anyway thanks @Colanim. I knew the steps, but the error was from somewhere else.
