### ISSUE TITLE
Is there any api for intermediate layer outputs?

### ISSUE THREAD

**Issue by mt324010** [huggingface/transformers#5900]
I would like to get all 12 Bertlayer outputs. Can you please help?

**Comment by sgugger** [comment]
You need to pass `output_hidden_states=True` when calling your model, or set this option when instantiating it. For instance, if you're using a pretrained model:
```
from transformers import DistilBertModel
model = DistilBertModel.from_pretrained('distilbert-base-uncased', output_hidden_states=True)
```
