### ISSUE TITLE
ImportError: cannot import name 'DataCollatorForPermutationLanguageModeling'

### ISSUE THREAD

**Issue by krannnn** [huggingface/transformers#5908]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):

Language I am using the model on English

The problem arises when using:
* [ ] the official example scripts: [`run_language_modeling.py`](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py).

The tasks I am working on is:
* [ ] Continue Training XLNet on domain-specific dataset / finetuning XLNet LM

## To reproduce

1. Install transformers 3.0
2. run the following command as mentioned in the readme file from examples :

```
python run_language_modeling.py \
    --output_dir=output \
    --model_type=xlnet \
    --model_name_or_path=xlnet-base-cased \
    --do_train \
    --train_data_file=$TRAIN_FILE
```
Error message : 
```
2020-07-20 10:47:29.463663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "run_language_modeling.py", line 29, in <module>
    from transformers import (
ImportError: cannot import name 'DataCollatorForPermutationLanguageModeling'
```

## Expected behavior
I expect not to have this import error since I'm using the latest release of the library

## Environment info

     
- `transformers` version: 3.0
- Platform: Google Colab
- Python version: Python 3.6.9
- PyTorch version (GPU?): 1.5.1+cu101
- Tensorflow version (GPU?): 2.2.0

- Using GPU in script?: Tesla K80
- Using distributed or parallel set-up in script?: No

**Comment by patil-suraj** [comment]
Hi @krannnn , `DataCollatorForPermutationLanguageModeling` is added after 3.0, you will need to install from source if you want to run examples

**Comment by kandloic** [comment]
Hi @patil-suraj , out of curiosity, how do you install it? What do you mean by you will need to install from source?
