### ISSUE TITLE
how (if at all) are those models related...

### ISSUE THREAD

**Issue by codingbutstillalive** [huggingface/transformers#5923]
https://github.com/huggingface/transformers/tree/master/examples/seq2seq

and...

https://github.com/nlpyang/PreSumm

are they the same?

**Comment by sshleifer** [comment]
I think they are not related at all.
Which models are you talking about?

**Comment by codingbutstillalive** [comment]
Hi! :)

I am talking about the implementation that is used for the text summarization example under transformers/examples and a BERT-based implementation that is described here:


https://paperswithcode.com/paper/text-summarization-with-pretrained-encoders

I wondered if this might be the same models or even implementations.

**Comment by sshleifer** [comment]
That is at `examples/seq2seq/bertabs`, but not actively maintained.
More recent models can be finetuned with the code at `examples/seq2seq/finetune.py`.

**Comment by codingbutstillalive** [comment]
Could you please describe what is meant by "finetuning other models"? Does it mean that it is a generic script that can work with arbitrary NLP models which are implemented with Pytorch?

**Comment by sshleifer** [comment]
it can work with the following classes of models in our model hub:
Bart
T5
Marian MT

which in total is over 1100 checkpoints!

**Comment by codingbutstillalive** [comment]
Oh, I see. The field is progressing so quickly. So I understand that BART is an alternative architecture to the one from the paper "Text Summarization with Pretrained Encoders". I will investigate this. Thank you!
