### ISSUE TITLE
What is the difference between the function of add_tokens() and add_special_tokens() in tokenizer

### ISSUE THREAD

**Issue by kugwzk** [huggingface/transformers#5940]
# ❓ Questions & Help

## Details

When I read the code of tokenizer, I have a problem if I want to use a pretrained model in NMT task, I need to add some tag tokens, such as '2English' or '2French'. I think these tokens are special tokens, so which function should I use: add_tokens() or add_special_tokens(). What is the difference between them?

**Comment by sgugger** [comment]
For some reasons those functions do not appear in the documentation, will have a look at why. The docstrings state of `add_special_tokens` states:

> Add a dictionary of special tokens (eos, pad, cls...) to the encoder and link them to class attributes. If special tokens are NOT in the vocabulary, they are added to it (indexed starting from the last index of the current vocabulary).
> Using `add_special_tokens` will ensure your special tokens can be used in several ways:
>  - special tokens are carefully handled by the tokenizer (they are never split)
>  - you can easily refer to special tokens using tokenizer class attributes like `tokenizer.cls_token`. This makes it easy to develop model-agnostic training and fine-tuning scripts.

Though the second point would not apply in your case. The docstring of `add_tokens` states:

> Add a list of new tokens to the tokenizer class. If the new tokens are not in the vocabulary, they are added to it with indices starting from length of the current vocabulary.
        When possible, special tokens are already registered for provided pretrained models (ex: BertTokenizer cls_token is already registered to be '[CLS]' and XLM's one is also registered to be '</s>')

Hope that helps!

**Comment by kugwzk** [comment]
Thank a lot for your help. Therefore, if I use the add_tokens(), the tokens may still split?

**Comment by TobiasJacob** [comment]
I would also appreciate some clarification on the difference between the function and when to use which one.

**Comment by LukeLIN-web** [comment]
> Thank a lot for your help. Therefore, if I use the add_tokens(), the tokens may still split?

In my practice yes,

**Comment by LukeLIN-web** [comment]
> I would also appreciate some clarification on the difference between the function and when to use which one.

For example if you want your '<SEG>' as whole, don't split to < ,  SEG, >  three token, you need add_special_tokens()
