### ISSUE TITLE
tensorflow转为pytorch的两个文件在哪里？

### ISSUE THREAD

**Issue by ChrisChaw** [huggingface/transformers#5962]
![image](https://user-images.githubusercontent.com/41299010/88131997-e31b9480-cc10-11ea-9966-f63a1b425878.png)
大佬您好：
请问这两个文件在哪里？discriminator.json和model.bin

**Comment by LysandreJik** [comment]
If I understand correctly and you're asking what/where are those two files:

- `discriminator.json` is the configuration file for the model you want to convert
- `model.bin` is the location where the converted checkpoint will be saved.
