### ISSUE TITLE
BerTweet tokenizer issue

### ISSUE THREAD

**Issue by Shiro-LK** [huggingface/transformers#5965]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):
Bertweet

## To reproduce

1. tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base")
2.
3.

OSError: Model name 'vinai/bertweet-base' was not found in tokenizers model name list (roberta-base, roberta-large, roberta-large-mnli, distilroberta-base, roberta-base-openai-detector, roberta-large-openai-detector). We assumed 'vinai/bertweet-base' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.
## Expected behavior

the tokenizer should be loaded correctly.
https://huggingface.co/vinai/bertweet-base?text=Paris+is+the+%3Cmask%3E+of+France.

## Environment info

     
- `transformers` version: 2.10.0
- Platform: ubuntu 18.04
- Python version: 3.7
- PyTorch version (GPU?): 1.5
- Tensorflow version (GPU?):
- Using GPU in script?: v100
- Using distributed or parallel set-up in script?: no

**Comment by julien-c** [comment]
This model is defined as a `roberta` model but its tokenizer seems to be a Wordpiece tokenizer (based on the `vocab.txt` file), whereas Roberta uses a Byte-level BPE.

This is not currently supported out of the box by our Pipelines (model type ≠ tokenizer type) but might be in the future.

**Comment by julien-c** [comment]
For now, you'll have to initialize this tokenizer + model independently.

```
BertTokenizer.from_pretrained("...")
AutoModel.from_pretrained("...")
```

Also cc'ing model author @datquocnguyen

**Comment by datquocnguyen** [comment]
I am working on it (I just have uploaded the model to huggingface yesterday). 
I will create pull requests soon, so that users can make use of the following scripts:

    tokenizer = BertweetTokenizer.from_pretrained("vinai/bertweet-base")
    bertweet = BertweetModel.from_pretrained("vinai/bertweet-base")

Please stay tuned!

**Comment by Shiro-LK** [comment]
@julien-c @datquocnguyen  Thanks for your answer.
I just tried the AutoModel, I had some weird "CUDA illegal memory access error" after 2 steps. It works fine with other models such as electra or roberta. I do not know if it is related to some wrong encoding with the tokenizer (I am using the fairseq tokenizer as the tokenizer from huggingface is not working even with BertTokenizer) or something else.

**Comment by nightlessbaron** [comment]
> I am working on it (I just have uploaded the model to huggingface yesterday).
> I will create pull requests soon, so that users can make use of the following scripts:
> 
> ```
> tokenizer = BertweetTokenizer.from_pretrained("vinai/bertweet-base")
> bertweet = BertweetModel.from_pretrained("vinai/bertweet-base")
> ```
> 
> Please stay tuned!

Looking forward to it !

**Comment by datquocnguyen** [comment]
@nightlessbaron @Shiro-LK @julien-c FYI, I have just created a pull request for adding BERTweet and PhoBERT into transformers
@nightlessbaron In case you want to use BERTweet right away, you might have a look at this fork https://github.com/datquocnguyen/transformers 
Cheers,
Dat.

**Comment by steveguang** [comment]
@datquocnguyen Looks like the error still exists. From https://huggingface.co/vinai/bertweet-base, I run 
tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base") 
It gives:
OSError: Model name 'vinai/bertweet-base' was not found in tokenizers model name list (roberta-base, roberta-large, roberta-large-mnli, distilroberta-base, roberta-base-openai-detector, roberta-large-openai-detector). We assumed 'vinai/bertweet-base' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.

Also, https://huggingface.co/vinai/bertweet-base?text=Paris+is+the+%3Cmask%3E+of+France gives an error

**Comment by datquocnguyen** [comment]
@steveguang @SergioBarretoJr your issue has now been solved. 
Also to @Shiro-LK @nightlessbaron  Please check https://github.com/datquocnguyen/transformers 
@julien-c Please help review this pull request #6129  BERTweet should work now in Auto mode and without an additional dependency fastBPE.

**Comment by datquocnguyen** [comment]
@steveguang @SergioBarretoJr your issue has now been solved. 
Also to @Shiro-LK @nightlessbaron  Please check https://github.com/datquocnguyen/transformers 
@julien-c Please help check this pull request #6129  BERTweet should work now in Auto mode and without an additional dependency fastBPE.

**Comment by datquocnguyen** [comment]
@steveguang @SergioBarretoJr your issue has now been solved.
Also to @Shiro-LK @nightlessbaron Please check https://github.com/datquocnguyen/transformers
@julien-c Please help review this pull request #6129 BERTweet now works in Auto mode and without an additional dependency fastBPE.

**Comment by julien-c** [comment]
This was solved by @datquocnguyen
