### ISSUE TITLE
run_squad example doesn't work with XLM model

### ISSUE THREAD

**Issue by sshearing** [huggingface/transformers#5969]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): XLM

Language I am using the model on (English, Chinese ...): Korean

The problem arises when using:
* [ ] the official example scripts: run_squad.py
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: KorQuAD v1.0

## To reproduce

1. Download the KorQuAD v1.0 data (it is formatted exactly as SQuAD v1.0)
2. Run the run_squad script with KorQuAD instead of SQuAD
3. Use the XLM model type (with specific model: xlm-mlm-100-1280_384)

## Expected behavior

Since the data is formatted exactly the same as the english version, except its in Korean now, I expect the script to be able to fully train and evaluate on the new data. In fact, the script successfully does this when you use multi-lingual BERT instead of XLM. However, when you use XLM, you get invalid input in the forward call:

"cls_index" and "p_mask" are unexpected inputs.

I tried hacking in a fix for this, specifically just deleting cls_index and p_mask from the inputs when using XLM instead of Bert. This caused the model to be able to train correctly, but when we try to evaluate, we end up crashing on a new error. I don't know if its related or not, but this is in the squad metrics, not within run_squad.py, so I was less excited to start messing with that and instead decided to put up this issue.

It specifically crashes here:
 transformers/data/metrics/squad_metrics.py", line 629, in compute_predictions_log_probs
    cur_null_score = result.cls_logits
AttributeError: 'SquadResult' object has no attribute 'cls_logits'

## Environment info

     
- `transformers` version: 3.0.2
- Platform: Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core
- Python version: 3.7.3
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No (Just 1 GPU)

**Comment by brettkoonce** [comment]
see also #3535
