### ISSUE TITLE
[cleanup] much cruft in unittests

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#5973]
Anti patterns:
- making a result dict and then using each of it's keys. Why use the dict?
- delete all mentions of `check_loss_output`
- use tuple equality: `self.assertEqual(tensor.shape, (bs, seq_len)` instead of 
```python
self.assertListEqual(list(tensor.size()), [bs, seq_len])
```

This does not need to be done for all test files at once.

fix `templates/testing_xxx ` to reflect the new best practice.

**Comment by sshleifer** [comment]
@stas00, this might be up your alley!

**Comment by stas00** [comment]
will do, thank you!

**Comment by stas00** [comment]
one test file: https://github.com/huggingface/transformers/pull/6196
if happy will do the rest

**Comment by stas00** [comment]
problem: not all results are objects, some are plain dict and can't be called with `.key_name`.

So we could add a wrapper to the test utils that will make the code consistent:

```
data = {
    "loss_1": 1,
    "mems_1": 2,
}

class DictAttr:
    def __init__(self, args):
        for k in args:
            setattr(self, k, args[k])

    def __getitem__(self, item):
         return getattr(self, item)
        
result = DictAttr(data)

print(result["loss_1"])
print(result.loss_1)
```

**Comment by sshleifer** [comment]
1) can we just never create a `result` dict? It just creates unneeded indirection.
2) If we need to create a results dict, cant we just do key lookup with `[key]`
3) checkout `collections.UserDict`

**Comment by stas00** [comment]
> * can we just never create a `result` dict? It just creates unneeded indirection.

From looking at the existing tests, it sort of mimics the returns objects, but doesn't have the accessors for the keys.

So I'm not quite sure what you propose. A short code sample is usually most demonstrative.
 
> * If we need to create a results dict, cant we just do key lookup with `[key]`

I lost you, unless I am misunderstanding what you're suggesting, isn't the big part of this "issue" - replacing `[key]` with `.key`. otherwise nothing else needs to be done and this ticket can be closed - except now it's a mish-mash of results.key (most pt tests) and results["key"] (most tf tests)

> * checkout `collections.UserDict`

I checked  - it doesn't provide `[key]` and `.key` functionality.

**Comment by sshleifer** [comment]
ignore #1, I was confused.
when I made this issue, sylvain hadn't merged #6155 , so I guess what remains of the issue is

```
- delete all mentions of check_loss_output
- use tuple equality: self.assertEqual(tensor.shape, (bs, seq_len) instead of assertListEqual(list()...)
```
So if/when those are done then it can definitely be closed.
Sorry for the miscommunication!

**Comment by sshleifer** [comment]
Your #6196 will completely close the issue.

**Comment by stas00** [comment]
So I just need to complete: "delete all mentions of check_loss_output" then - there is one remaining test there.

**Comment by stas00** [comment]
I plan to do part 2 PR to make the rest of the tests consistent with this change, but I have to wait for this to be merged as it impacts too many files to proceed easily.
