### ISSUE TITLE
Transformer-XL: no mems are return when using 'return_tuple'

### ISSUE THREAD

**Issue by RafaelWO** [huggingface/transformers#5974]
# 🐛 Bug

## Information
The forward pass of the `TransfoXLLMHeadModel` returns no `mems` when using `return_tuple=True`.

Model I am using: Transformer-XL

Language I am using the model on: English

The problem arises when using:
* [x] my own modified scripts: (give details below)

## To reproduce

```Python
from transformers import TransfoXLLMHeadModel, TransfoXLTokenizer

model = TransfoXLLMHeadModel.from_pretrained("transfo-xl-wt103")
model.train()
tokenizer = TransfoXLTokenizer.from_pretrained("transfo-xl-wt103")

encoded = tokenizer("Max is walking the dog in the streets", return_tensors='pt')
outputs = model(input_ids=encoded['input_ids'], mems=None, labels=encoded['input_ids'], return_tuple=True)
loss, _, mems = outputs

print(loss.size())
print(len(mems))      # should be 18 due to the 18 layers
```
Output:
```
Traceback (most recent call last):
  File "user/script.py", line 10, in <module>
    loss, _, mems = outputs
ValueError: not enough values to unpack (expected 3, got 2)
```

## Expected behavior
Output:
```
torch.Size([1, 7])
18
```

## Environment info

     
- `transformers` version: 3.0.2
- Platform: Windows-10-10.0.18362-SP0
- Python version: 3.6.10
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?): 2.1.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by sgugger** [comment]
Thanks for flagging the issue, the fix is on its way to review.

**Comment by RafaelWO** [comment]
Oh, I opened a PR for this, but it seems you fixed it yourself. I will close my PR then,
