### ISSUE TITLE
how can I download T5-11B pretrained model?

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#5986]
It gives me the following error. 

**OSError: Can't load weights for 't5-11b'. Make sure that:

- 't5-11b' is a correct model identifier listed on 'https://huggingface.co/models'

- or 't5-11b' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.**

**Comment by ibrahimsharaf** [comment]
I get an error when trying to use the hosted inference API too.

```
⚠️ Error loading model Can't load weights for 't5-11b'. Make sure that: - 't5-11b' is a correct model identifier listed on 'https://huggingface.co/models' - or 't5-11b' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt. OSError("Can't load weights for 't5-11b'. Make sure that:\n\n- 't5-11b' is a correct model identifier listed on 'https://huggingface.co/models'\n\n- or 't5-11b' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.\n\n")
```

**Comment by julien-c** [comment]
This is a known issue, and is due to the fact that the [checkpoint size is 42GB](https://huggingface.co/t5-11b#list-files) while the max supported file size for Cloudfront is [20GB](https://aws.amazon.com/blogs/aws/amazon-cloudfront-support-for-20-gb-objects/).

You should use the `use_cdn=False` flag in `AutoModel.from_pretrained(use_cdn=False)` to work around this for now.

**Comment by julien-c** [comment]
Forgot to update this issue at the time, but note that this now works transparently

**Comment by nobellant215** [comment]
Hi. I am having trouble when downloading t5-11b model too but with bit different issue. I am keep getting 'connection rest by peer' error and failing to download the pretrained weights. Is there other way to download the model parameters?

**Comment by julien-c** [comment]
Hi @nobellant215 you could try downloading the weights file directly: https://huggingface.co/t5-11b/resolve/main/pytorch_model.bin
