### ISSUE TITLE
T5 pre training on different languages from scratch

### ISSUE THREAD

**Issue by ashispapu** [huggingface/transformers#5996]
Hi Team,

I was exploring the pre training procedure/document for T5 models(small,base, large) models on different languages from scratch. However did not come across anything which could help me. Please share if there is any resource for the same. If not, could you please consider to include it .

Thank you .

**Comment by patil-suraj** [comment]
Hi @ashispapu, T5 pre-training is not yet available in transformers, I'm working on it but might take some time. Feel free to take a stab.

**Comment by ashispapu** [comment]
Hi @patil-suraj Thanks for the response. Let me try it.

**Comment by ypapanik** [comment]
@patil-suraj, thanks for working on the different T5 ropes. Can you point to the branch you 're working for pre-training? I'd be interested to contribute.

**Comment by vinhngx** [comment]
I'm interested in T5 pre-training from scratch. Any update on this project?
