### ISSUE TITLE
install sentence-transformers on Linux by python error

### ISSUE THREAD

**Issue by kension0929** [huggingface/transformers#6010]
# ❓ Questions & Help

When I install sentence-transformers on Linux by python
![error](https://user-images.githubusercontent.com/15052580/88359057-da0efc80-cda3-11ea-98fb-01deddb09acd.png)
, I got an error message:

ERROR: Could not find a version that satisfies the requirement transformers>=3.0.2 (from sentence-transformers) (fr
om versions: 0.1, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.5.1)
ERROR: No matching distribution found for transformers>=3.0.2 (from sentence-transformers)

system: Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 on GCP VM instance.
Is there any suggestion?

**Comment by shreyaspatil276** [comment]
I am also facing same issue while trying to install transformers version 3.0.2...Did you find any solution?

**Comment by Amol1991** [comment]
![Capture](https://user-images.githubusercontent.com/31931277/99186693-1e217500-2778-11eb-9bb1-086203a65031.PNG)
how to fix this....pls help
