### ISSUE TITLE
Cannot import DPRReader

### ISSUE THREAD

**Issue by alexvaca0** [huggingface/transformers#6013]
# 🐛 Bug

You have DPRReader included in your v3.0.2 documentation, but it's in the Master branch, it's not included in v3.0.2 tag; therefore it crashes and cannot import it. I think it would be convenient to either eliminate that piece of documentation until the models are added in the tag, or update the transformers version with the Master branch.

**Comment by sgugger** [comment]
Thanks for flagging, the stable doc was building on a wrong commit hash, hence the DPR models being present.
This is fixed now.
