### ISSUE TITLE
seq2seq/finetune.py can take config train_params through command line

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#6018]
- this might belong in lightning_base
- check how/if trainer does it.

Desired API:
```bash
python finetune.py --encoder_layerdrop 0.1 --decoder_layerdrop 0.1 --dropout 0.1 --attention_dropout 0.1
```

**Comment by sshleifer** [comment]
@stas00 this might be up your alley.

**Comment by stas00** [comment]
Added to my todo queue - thank you, @sshleifer

**Comment by stas00** [comment]
https://github.com/huggingface/transformers/pull/6149
