### ISSUE TITLE
Error with batch_encode_plus

### ISSUE THREAD

**Issue by Nithin-Holla** [huggingface/transformers#6031]
# 🐛 Bug

## Information
When using the tokenizer method `batch_encode_plus` on the new `transformers` version, I run into an error

Model I am using (Bert, XLNet ...): BertTokenizer

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

Here is a sample script to reproduce the error:
```python
import torch
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
text = [['sample text 1'], ['sample text 2']]
encode = tokenizer.batch_encode_plus(text)
```

The stack trace is:
```
Traceback (most recent call last):
  File "bug.py", line 8, in <module>
    encode = tokenizer.batch_encode_plus(text)
  File "/home/nithinh/debug/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1832, in batch_encode_plus
    **kwargs,
  File "/home/nithinh/debug/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 534, in _batch_encode_plus
    ids, pair_ids = ids_or_pair_ids
ValueError: not enough values to unpack (expected 2, got 1)
```
## Expected behavior

Successfully tokenize without errors. The script runs fine with `transformers` v2.11.0.

## Environment info
     
- `transformers` version: 3.0.2
- Platform: Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
- Python version: 3.6.3
- PyTorch version (GPU?): 1.5.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by patil-suraj** [comment]
Hi, if want to encode as sentence pair then you should do it like this
```python3
[ ["sent1", "sent2"] ]
```
else just pass the examples in a single list
```python3
["example1", "example2"]
```

Also, consider switching to the new tokenizer API. You can find the docs [here](https://huggingface.co/transformers/preprocessing.html)

**Comment by Nithin-Holla** [comment]
@patil-suraj I didn't intend to encode it as a sentence pair, but rather a batch of single sentences of size 2.

**Comment by patil-suraj** [comment]
Then you can just pass a list of examples. No need for nested list

**Comment by Nithin-Holla** [comment]
Okay, thanks!
