### ISSUE TITLE
MarianMT - How to find out the actual names of the languages? - Only language-codes are available

### ISSUE THREAD

**Issue by sunnyville01** [huggingface/transformers#6039]
# Question

## Information

I want to use the [MarianMT](https://huggingface.co/transformers/model_doc/marian.html) library for creating a translation application. There are lots of languages available with their language-codes mentioned such as "en" and "es", but no where can I find the actual names of the languages for each code. I know "en" is for English and "fr" for French, but what "bg" and "lu" and so many others that are available. [This resource](https://huggingface.co/Helsinki-NLP) doesn't mention the actual names as well.

Is there any place where I can find the corresponding names for these codes. I tried using some online source, but there seems to be a miss-match and I can't be sure if I got the match correct.

**Comment by patil-suraj** [comment]
https://huggingface.co/languages

**Comment by sunnyville01** [comment]
@patil-suraj Thank you.
