### ISSUE TITLE
examples/seq2seq:  add a dataloader that supports dynamic batch size

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#6051]
Should follow the logic of `load_langpair_dataset` in fairseq, roughly.
Batches should be created such that they include N(default 1024) tokens of source documents, however many examples that requires.

**Comment by logoutlzh** [comment]
Excuse me, what is the reason why we can not use multi-gpu `DataParallel`  for parallel training with `--max_tokens_per_batch` in the old `finetune` script ? @sshleifer
