### ISSUE TITLE
lightning_base: new clarg: lr_scheduler=polynomial_decay

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#6070]
lr_scheduler should be a string with many options, including polynomial_decay, like this [command](https://github.com/pytorch/fairseq/blob/master/examples/mbart/README.md#finetune-on-en-ro)

**Comment by sshleifer** [comment]
@stas00 as discussed on slack

**Comment by stas00** [comment]
got it

**Comment by stas00** [comment]
PR for stage 1 to support the existing schedulers: https://github.com/huggingface/transformers/pull/6232
once this is happy and merged, I will work on importing new ones.

**Comment by stas00** [comment]
poly: https://github.com/huggingface/transformers/pull/6361

**Comment by stas00** [comment]
@sshleifer, so now that get_polynomial_decay_schedule_with_warmup is done (about to be merged) - do we need any others?

**Comment by sshleifer** [comment]
Not that I know of. We can close this once the associated PR  ismerged.
