### ISSUE TITLE
🐛 Inconsistencies between BartTokenizer and BartTokenizerFast

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#6082]
# 🐛 Bug

## Description

It's possible to use the argument `add_prefix_space` with `BartTokenizer` :

```
from transformers import BartTokenizer

t = BartTokenizer.from_pretrained("facebook/bart-large")
x = t("This is an example.", add_prefix_space=True)
```

But when doing the same with `BartTokenizerFast` :
```
from transformers import BartTokenizerFast

t = BartTokenizerFast.from_pretrained("facebook/bart-large")
x = t("This is an example.", add_prefix_space=True)
```

It throws the following error :

```
ValueError: Keyword arguments {'add_prefix_space': True} not recognized.
```

## To reproduce

[Colab notebook](https://colab.research.google.com/drive/1f0W2llsJfVIkXsYk0XK1C3oiy2xSqYOx?usp=sharing)

## Work-around

It seems working if the argument is specified in the constructor :
```
from transformers import BartTokenizerFast

t = BartTokenizerFast.from_pretrained("facebook/bart-large", add_prefix_space=True)
x = t("This is an example.")
```

@sshleifer

**Comment by patil-suraj** [comment]
Seems like this issue is for all fast tokenizers, this [line](https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils_fast.py#L312) directly raises that error when kwargs are passed

**Comment by sshleifer** [comment]
Can I close? Seems like your workaround is solid @Colanim

**Comment by Colanim** [comment]
If it's the expected behavior, sure go ahead ^^

I opened because I thought `Tokenizer` and `TokenizerFast` were expected to have the same behaviors.

**Comment by sshleifer** [comment]
Fair. I think there is a medium-term plan to deprecate `add_prefix_space`, so at the moment it is left inconsistent and in the future it will be deleted from both.
