### ISSUE TITLE
No button for creating new post at the forum.

### ISSUE THREAD

**Issue by guotong1988** [huggingface/transformers#6116]
![image](https://user-images.githubusercontent.com/4702353/88753699-76b01080-d18f-11ea-80c3-905a006ad31a.png)
discuss.huggingface.co

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/88774445-0b2d6980-d1b6-11ea-88ba-e993190b434c.png)

**Comment by julien-c** [comment]
I approved your post there @guotong1988
