### ISSUE TITLE
Using control codes for finetuning

### ISSUE THREAD

**Issue by tuhinjubcse** [huggingface/transformers#6117]
Hi
I have a use case of style conditioned generation, where I ask the LM to generate a sentence based on the control code I provide. CTRL is pretty suitable for that task.
Can you tell me how to use control codes for fine-tuning as well as inference?  It should be the same as any CLM like GPT2 but I want to specifically know about the style and control code conditioning. How should be the data format and other stuffs

**Comment by tuhinjubcse** [comment]
@julien-c

**Comment by julien-c** [comment]
It'd be best to re-read the paper and original implem, but I think you just prepend a control code to each of your samples.

Cc'ing @keskarnitish for information.

PS/ for general questions, please use https://discuss.huggingface.co!
