### ISSUE TITLE
Is `guid` allowed to be None in `InputExample`?

### ISSUE THREAD

**Issue by davidatbu** [huggingface/transformers#6118]
## Environment
-`transformers` version: 3.0.2
Omitted the rest because they most likely don't affect this issue.

## To reproduce

```py
from transformers.data.processors.utils import SingleSentenceClassificationProcessor

processor = SingleSentenceClassificationProcessor(labels=["lbl1", "lbl2"])
processor.add_examples(texts_or_text_and_labels=["example1", "example2"]) # There's a default ids=None
print(processor[0])
```
prints 
```InputExample(guid=None, text_a='example1', text_b=None, label=None)```

If `guid` is allowed to be None, that should be reflected in the type annotation(and documentation) of `InputExample`. If not, then `ids` should not be allowed to be `None`.

### Who can help 
@sgugger because it's a documentation issue, @thomwolf because of `git blame`.

**Comment by sgugger** [comment]
The guid is indeed optional, we can add this to the type annotation. We can't add the default `= None` however because it's before `text_a` in the dataclass, which is not optional.

**Comment by davidatbu** [comment]
Thanks! I'll probably shape up a bunch of type annotations into a PR sometime soon, so I'll make `guid` Optional(but without a default) in that PR if noone gets to it before me.
