### ISSUE TITLE
Initializing XLMRobertaTokenizer using pretrained tokenizer expects serialized vocab

### ISSUE THREAD

**Issue by aoxolotl** [huggingface/transformers#6127]
Hi,
I am training an XLMRoberta model from scratch on Hindi. I am using a sentencepiece tokenizer trained exclusively on monolingual data following the steps mentioned in the [tokenizers repository](https://github.com/huggingface/tokenizers/tree/704cf3fdd2f607ead58a561b892b510b49c301db/bindings/python#using-the-provided-tokenizers). This results in the creation of `vocab.json` and `merges.txt`.
However when I try to initialize the tokenizer using `XLMRobertaTokenizer.from_pretrained` I get an error saying
```assumed 'models/sentencepiece' was a path, a model identifier, or url to a directory containing vocabulary files named ['sentencepiece.bpe.model'] but couldn't find such vocabulary files at this path or url. ``` 
I am assuming this is a serialized file based on [huggingface.co model](https://s3.amazonaws.com/models.huggingface.co/bert/xlm-roberta-base-sentencepiece.bpe.model) but don't know how to serialize my vocab.json file. I have already tried using `pickle` and `numpy`
Versions used:
transformers: 2.9.1
tokenizers: 0.7.0

**Comment by LysandreJik** [comment]
Hi! The XLM-R tokenizer only accepts SentencePiece files, which cannot be created yet with the `tokenizers` library (soon!). You should use the official SentencePiece library for that.
