### ISSUE TITLE
Applying hugging face transformer in sequence labeling problem

### ISSUE THREAD

**Issue by Michael95-m** [huggingface/transformers#6139]
Hello.. Thanks for your great framework. Btw, what I'd like to know is that can I apply these hugging face transformer models in **sequence labeling** problems like **part of speech tagging** and **word segmentation**(because I see only **ner** model in example folder). If I can, **how** can I do that?? Can I get some helps like **example scripts** about how to apply these transformers for sequence labeling problems??

**Comment by wyin-Salesforce** [comment]
you just use the ner code for POS tagging problem, the only difference is the set of target classes
