### ISSUE TITLE
Using BertWordPiece Tokenizer

### ISSUE THREAD

**Issue by Chokerino** [huggingface/transformers#6152]
# ❓ Questions & Help

## Details
The Bert WordPiece tokenizer only saves a vocab file on saving the model while other tokenizers such as Byte Level BPE also save a merges file.  When I try to call the model after saving it `RobertaTokenizerFast.from_pretrained("./EsperBERTo_italian", max_len=512)` I get the following error 
`OSError: Model name './EsperBERTo_italian' was not found in tokenizers model name list (roberta-base, roberta-large, roberta-large-mnli, distilroberta-base, roberta-base-openai-detector, roberta-large-openai-detector). We assumed './EsperBERTo_italian' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.
`

**Comment by LysandreJik** [comment]
Hi! Are you trying to load a BERT vocabulary in a RoBERTa tokenizer? This unfortunately won't work, as the mechanisms between the WordPiece and Byte level BPE are inherently different.

**Comment by Chokerino** [comment]
Hi, I could not find documentation for it so I thought id try. Another thing I wanted to ask is that I am working on a dataset of recipes so I have a list of ingredients in order.  I now remove random ingredients and predict them using various models. I have tried Seq2Seq models and Roberta to solve this problem but both give poor results. In my opinion, this problem is somewhat similar to NLP problems but significantly different because tokenizing like BERT does not give any advantage and creates more problems. Do you have any architecture in mind that might be more suited to tackle this problem?
