### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file. 

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#6159]
Hello,

When I am trying to load the `Roberta-large` pre-trained model, I get the following error:

```python
model_RobertaForMultipleChoice = RobertaForMultipleChoice.from_pretrained('roberta-large', output_hidden_states = True)

OUT:
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 
```

How can I solve this issue? Thank you,

**Comment by LysandreJik** [comment]
Hi! Do you mind pasting your environment information here so that we may take a look?

**Comment by leeivan** [comment]
Try to delete cache directory files.

**Comment by jawadSajid** [comment]
Hey, I trained my model on GPT2-small but I am not able to load it! It gives off the following error:

    Unable to load weights from pytorch checkpoint file for '{pretrained_model_name_or_path}' OSError: Unable to load weights 
    from pytorch checkpoint file for '/mounted/models/train-on-test1/' at '/mounted/models/train-on-test1/pytorch_model.bin' If you 
    tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

@leeivan @LysandreJik

**Comment by LysandreJik** [comment]
Please open a new issue with your specific problem, alongside all the information related to your environment as asked in the template. Thank you.

**Comment by Freed-Wu** [comment]
Same as <https://github.com/huggingface/transformers/issues/6620>, i guess it is because the checkpoint file is not a true checkpoint file: such as a git lfs file.

**Comment by PriyankaSagwekar** [comment]
#6159, #6970,  #6620 are all same issue. 
In my case I cloned the checkpoint file using git lfs and issue was resolved. Earlier I had used pointer to avoid git lfs however it gave this error. 
For some changing torch, transformer, tokenizer versions helped. 
Also you can go through the docs and check some from_pretrained parameters like force_download, from_tf and try.

**Comment by thepurpleowl** [comment]
For futuer visitors:  [check this](https://discuss.pytorch.org/t/getting-an-error-unpicklingerror-invalid-load-key-v-in-pytorch-model-deploying-in-streamlit/107768/4)
