### ISSUE TITLE
run_squad.py eval metrics meaning

### ISSUE THREAD

**Issue by batyas** [huggingface/transformers#6160]
I am having difficulty understanding what exactly the best_f1 and best_exact scores that are outputted in the run_squad.py evaluation mean. (The scores are computed in the squad_metrics script, found [here](https://github.com/huggingface/transformers/blob/master/src/transformers/data/metrics/squad_metrics.py)). 
What are the "scores" the best calculations are working with, what do the metrics represent, and when/is the best_threshold value employed during training?

Thank you!

**Comment by elronbandel** [comment]
The model assign correctness probability to every answer it produce. if this probability crossing the threshold it means that the model predict their is no answer to the question. The threshold is picked as the threshold that achieve the best f1/exact score on the dev set. The best f1/exact is the result achieved with the best threshold found.

Unfortunately, their is a [bug](https://github.com/huggingface/transformers/pull/7319) in run_squad.py code which was used for the training and evaluation of most of the models in the library and the results you see in their model cards are incorrect.

**Comment by elronbandel** [comment]
Opened Issue: [[BUG] Wrong Scores for many SQUAD models ](https://github.com/huggingface/transformers/issues/8710) #8710
