### ISSUE TITLE
RoBERTa ``tokenizer.decode`` does not produce the same sentence.

### ISSUE THREAD

**Issue by flyaway1217** [huggingface/transformers#6164]
## Environment info
- `transformers` version: 3.0.2
- Platform: Linux-4.15.0-74-generic-x86_64-with-glibc2.27
- Python version: 3.8.0
- PyTorch version (GPU?): 1.5.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No.
- Using distributed or parallel set-up in script?: No.
     

### Who can help
@mfuntowicz

## Information

Model I am using (Bert, XLNet ...): RoBERTa

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

This code example should reproduce the issue:

```python3
from transformers import RobertaTokenizer
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
s = """Meanwhile, Tucci's 'straight guy', the emphatic doctor Seger, is not developed into a more interesting character, like the fallible 'straight guys' Cuddy and Wilson."""
outputs = tokenizer(s)
input_ids = outputs['input_ids']
ss = tokenizer.decode(input_ids, skip_special_tokens=True)
print('s='+s)
print('ss='+ss)
```

## Expected behavior
I expect ``s`` and ``ss`` should be exactly the same. However, they are not. The outputs are:

```bash
s=Meanwhile, Tucci's 'straight guy', the emphatic doctor Seger, is not developed into a more interesting character, like the fallible 'straight guys' Cuddy and Wilson.

ss=Meanwhile, Tucci's'straight guy', the emphatic doctor Seger, is not developed into a more interesting character, like the fallible'straight guys' Cuddy and Wilson.
```
There are two spaces missing before ``'straight guy'``. 
I am not sure if this behavior is expected or it is a bug.
The thing is I want to use the sentence produced by the ``decode`` function and  I find the output is not exactly the same as the original sentence.

Thanks for the help!

**Comment by Colanim** [comment]
Seems to be an edge case from cleaning up tokenization on decoding :

https://github.com/huggingface/transformers/blob/c0b93a1c7a961e30b30d02d641c9d22120ef5d73/src/transformers/tokenization_utils_base.py#L2688

---

For this specific case, a work-around can be :

`ss = tokenizer.decode(input_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)`

---

But I think it's a bug. Is there any way to improve `clean_up_tokenization()` function ?
