### ISSUE TITLE
🐛 Not adding `token_type_ids` when the model is `electra` (pytorch_lightning example)

### ISSUE THREAD

**Issue by monologg** [huggingface/transformers#6172]
### Who can help
@sshleifer (examples issue)

## Information

Model I am using (Bert, XLNet ...): `ELECTRA`

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## About Issue

https://github.com/huggingface/transformers/blob/838dc06ff5a438159ac25f531d622e8f344476f5/examples/text-classification/run_pl_glue.py#L38-L39

As above, it seems that `token_type_ids` is not included if the `model_type=='electra'` (which also have `token_type_ids`)

I think this code should be changed in other way.

**Comment by patil-suraj** [comment]
Hi @monologg , yes toke_type_ids should be there for electra,

easy fix would be somethin like
```python3
if self.config.model_type not in ["xlm", "roberta", "distilbert", "camembert"]:
     inputs["token_type_ids"] = batch[2] 
```

@sshleifer , if yes, I can open a PR

**Comment by monologg** [comment]
@patil-suraj, I also think that is the best to way to fix this issue:)

https://github.com/huggingface/transformers/blob/838dc06ff5a438159ac25f531d622e8f344476f5/examples/text-classification/run_pl_glue.py#L98-L102

And not only in `training_step()`, also `validation_step()` has to be fixed.

**Comment by patil-suraj** [comment]
Yes, totally forgot about that, thanks!
