### ISSUE TITLE
My finetuned gpt2 model is taking wayy too long to generate samples, like 5-8 minutes

### ISSUE THREAD

**Issue by Krish-Nerkar** [huggingface/transformers#6173]
I fine tuned the gpt2 model using transformers, i trained it on a lyrics dataset, and after successful training, when i do model.generate(args), it takes like a hell lot of time to genrate results
What Should i do?

**Comment by patil-suraj** [comment]
Hi @Krish-Nerkar , [this](https://discuss.huggingface.co/t/speeding-up-gpt2-generation/470) might help

**Comment by Krish-Nerkar** [comment]
@patil-suraj Thanks Alot! will check those methods out
