### ISSUE TITLE
taeminlee/kogpt2 not working

### ISSUE THREAD

**Issue by ksjae** [huggingface/transformers#6188]
## Environment info

     
- None: hosted inference API

### Who can help
@LysandreJik 
@julien-c 
@TevenLeScao

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [O] the official example scripts: Hosted Inference API testing page
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [O] my own task or dataset: Text generation, or anything

## To reproduce

1. https://huggingface.co/taeminlee/kogpt2?text=제+이름은+홍길동
2. Or type any text
3. Model returns just the text

## Expected behavior

Generated text should be returned, but isn't.

**Comment by LysandreJik** [comment]
It seems to work? What's happening on your end?

**Comment by LysandreJik** [comment]
@ksjae, I can't seem to make that model work in my environment, without relying on the inference API. 

```py
from transformers import AutoModelWithLMHead, pipeline
from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("taeminlee/kogpt2", do_lower_case=False)

print(tokenizer.tokenize("제 이름은 홍길동"))
# ['ì', 'ł', 'ľ', 'Ġ', 'ì', 'Ŀ', '´', 'ë', '¦', 'Ħ', 'ì', 'Ŀ', 'Ģ', 'Ġ', 'í', 'Ļ', 'į', 'ê', '¸', '¸', 'ë', 'ı', 'Ļ']  # probably not what we're looking for

print(tokenizer.decode(tokenizer.encode("제 이름은 홍길동")))
# <unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk>�<unk><unk><unk><unk><unk><unk><unk><unk>
# Definitely not what we're looking for
```

Do you know the author?

**Comment by ksjae** [comment]
No, I don't.
I'll try to add a new one(in training right now) though.
