### ISSUE TITLE
Add support for truncation argument when calling a Pipeline

### ISSUE THREAD

**Issue by mkaze** [huggingface/transformers#6190]
# 🚀 Feature request

Currently, only the `padding` argument [is supported](https://github.com/huggingface/transformers/blob/a39dfe4fb122c11be98a563fb8ca43b322e01036/src/transformers/pipelines.py#L500) when calling a pipeline, and it's not possible to pass `truncation` argument. For example, running the following code sample would raise an error:

```python
import transformers as trf

model = trf.pipeline(task='feature-extraction', model='bert-base-cased')
output = model('a sample text', padding=False, truncation=True)
```

## Motivation

If toggling padding is supported, then why truncation shouldn't be?

## Your contribution

I think to achieve this, same as `padding`, only a `truncation` argument should be added to `_parse_and_tokenize` method and also when calling the tokenizer. If that's the case, I would be willing to work on a PR.

**Comment by cfregly** [comment]
is there any workaround for this?  i'm seeing the `Token indices sequence length is longer than the specified maximum sequence length for this model (... > 512). Running this sequence through the model will result in indexing errors` when using TextClassificationPipeline.

(This is preventing me from upgrading to 3.x.)

**Comment by sshleifer** [comment]
routing this to @mfuntowicz @LysandreJik

**Comment by alexbw** [comment]
+1 on this

**Comment by buhrmann** [comment]
Hi, even though this has been closed as stale, without comment or supposed fix, it seems that in recent versions you can in fact pass both truncation and padding arguments to the pipeline's __call__ method, and it will correctly use them when tokenizing. I've tested it with long texts that fail without the truncation argument, and it seems to work as expected.
