### ISSUE TITLE
Can't load config for [community model]

### ISSUE THREAD

**Issue by abedkhooli** [huggingface/transformers#6226]
Although I can use a fine-tuned GPT2 model from code, the model page complains about the config file (which is already uploaded). 
at https://huggingface.co/akhooli/gpt2-small-arabic-poetry (for a prompt), I get: 
```
Can't load config for 'akhooli/gpt2-small-arabic-poetry'. Make sure that: - 'akhooli/gpt2-small-arabic-poetry' is a correct model identifier listed on 'https://huggingface.co/models' - or 'akhooli/gpt2-small-arabic-poetry' is the correct path to a directory containing a config.json file 
```

**Comment by julien-c** [comment]
Currently working on a fix. Will update here

**Comment by julien-c** [comment]
Should be fixed now

**Comment by rohanrajpal** [comment]
Hey I'm facing the same issue with two models I uploaded today
https://huggingface.co/rohanrajpal/bert-base-en-hi-codemix-cased?text=I+like+you.+I+love+you
https://huggingface.co/rohanrajpal/bert-base-en-es-codemix-cased?text=I+like+you.+I+love+you

**Comment by julien-c** [comment]
pinging @mfuntowicz on this

**Comment by donal1** [comment]
Seeing the same issue, 

https://huggingface.co/donal/Pro_Berta?text=The+goal+of+life+is+%3Cmask%3E.

All the files seem to be in the right place.

Your file now lives at:                                                         
https://s3.amazonaws.com/models.huggingface.co/bert/donal/Pro_Berta/merges.txt
Your file now lives at:                                                         
https://s3.amazonaws.com/models.huggingface.co/bert/donal/Pro_Berta/special_tokens_map.json
Your file now lives at:                                                         
https://s3.amazonaws.com/models.huggingface.co/bert/donal/Pro_Berta/training_args.bin
Your file now lives at:                                                         
https://s3.amazonaws.com/models.huggingface.co/bert/donal/Pro_Berta/pytorch_model.bin
Your file now lives at:                                                         
https://s3.amazonaws.com/models.huggingface.co/bert/donal/Pro_Berta/config.json
Your file now lives at:                                                         
https://s3.amazonaws.com/models.huggingface.co/bert/donal/Pro_Berta/tokenizer_config.json
Your file now lives at:                                                         
https://s3.amazonaws.com/models.huggingface.co/bert/donal/Pro_Berta/vocab.json

**Comment by abedkhooli** [comment]
You probably are already aware of this, but inference worked for a bit and broke again (Can't load config for [model]).

**Comment by mfuntowicz** [comment]
I had to revert the change I did because it was breaking one workflow we have. I'm working on having a stable patch by today, sorry for the inconvenience

**Comment by mfuntowicz** [comment]
Should be fixed now. Let us know 👍

**Comment by donal1** [comment]
Yup works

**Comment by abedkhooli** [comment]
Confirmed (existing model then updated). Thanks for the fix and for HF great work!

**Comment by rohanrajpal** [comment]
It works now. Thanks! @mfuntowicz

**Comment by GregRoq** [comment]
Hi, I have the same issue...: 

Can't load config for 'Greg1901/BertSummaDev_summariser'. Make sure that:

- 'Greg1901/BertSummaDev_summariser' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'Greg1901/BertSummaDev_summariser' is the correct path to a directory containing a config.json file

Can you please help?
