### ISSUE TITLE
ValueError: Unrecognized model identifier in facebook/bart-large-cnn.

### ISSUE THREAD

**Issue by SagarPalyal** [huggingface/transformers#6228]
## Environment info
     
- `transformers` version: 2.2.2
- Platform: windows 10
- Python version: 3.7.8
- PyTorch version (GPU?): 1.6.0+cpu
- Tensorflow version (GPU?):
- Using GPU in script?:No
- Using distributed or parallel set-up in script?:No

 
 albert, bert, GPT2, XLM: @LysandreJik 
 tokenizers: @mfuntowicz
 Model Cards: @julien-c
 Summarization: @sshleifer 
 examples/distillation: @VictorSanh
 Bart: @sshleifer
documentation: @sgugger
 -->

## Information

I am using facebook/bart-large-cnn summarization model as mentioned in hugging face website using transformers:

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
model = AutoModel.from_pretrained("facebook/bart-large-cnn")

After running above lines of code I am getting below error message:
>>> from transformers import AutoTokenizer, AutoModel
>>> tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\workspace\BERTExtractiveSummarizer\lib\site-packages\transformers\tokenization_auto.py", line 148, in from_pretrained
    "'xlm', 'roberta', 'distilbert,' 'camembert', 'ctrl', 'albert'".format(pretrained_model_name_or_path))
ValueError: Unrecognized model identifier in facebook/bart-large-cnn. Should contains one of 'bert', 'openai-gpt', 'gpt2', 'transfo-xl', 'xlnet', 'xlm', 'roberta', 'distilbert,' 'camembert', 'ctrl', 'albert'

Please let me know how to resolve this error. Thanks in advance.

PS: Same Error is coming for using "sshleifer/distilbart-cnn-12-6" model as well.

**Comment by sshleifer** [comment]
Please only tag one or two people.
I think `pip instal transformers --upgrade` will fix your problem.
