### ISSUE TITLE
Documentation bug in GPT2Config

### ISSUE THREAD

**Issue by miggymigz** [huggingface/transformers#6240]
In [this page](https://huggingface.co/transformers/model_doc/gpt2.html), GPT2Config's initializer_range default value is 16. But the source code [says](https://github.com/huggingface/transformers/blob/master/src/transformers/configuration_gpt2.py#L130) it is 0.02.

**Comment by patrickvonplaten** [comment]
Good catch!

**Comment by patrickvonplaten** [comment]
#6352
