### ISSUE TITLE
Bart encoder with add_final_layer_norm

### ISSUE THREAD

**Issue by ruotianluo** [huggingface/transformers#6259]
https://github.com/huggingface/transformers/blob/91cb95461e438dc57555c4f57f8ce95a56328036/src/transformers/modeling_bart.py#L305

I feel like it should be 
self.layer_norm = LayerNorm(config.d_model) if config.add_final_layer_norm else None

as in the BartDecoder.
https://github.com/huggingface/transformers/blob/91cb95461e438dc57555c4f57f8ce95a56328036/src/transformers/modeling_bart.py#L486

**Comment by ruotianluo** [comment]
Any idea?

**Comment by sshleifer** [comment]
You are correct. It will be fixed in the blenderbot PR if not sooner.
