### ISSUE TITLE
Unable to make inference from hosted api for a pretrained model that I uploaded. 

### ISSUE THREAD

**Issue by JME-P** [huggingface/transformers#6267]
I have successfully managed to upload a model (https://huggingface.co/shrugging-grace/tweetclassifier) via the transformers cli. I am also able to generate inferences from a local Jupyter notebook to that model.

However, when I go on the https://huggingface.co/shrugging-grace/tweetclassifier, it comes up with the following error when I try to make an inference:

_"Can't load config for 'shrugging-grace/tweetclassifier'. Make sure that: - 'shrugging-grace/tweetclassifier' is a correct model identifier listed on 'https://huggingface.co/models' - or 'shrugging-grace/tweetclassifier' is the correct path to a directory containing a config.json file"_

However:
- shrugging-grace/tweetclassifier seems to be the correct model identifier, and
- the JSON file seems to be present (https://s3.amazonaws.com/models.huggingface.co/bert/shrugging-grace/tweetclassifier/config.json) and working correctly when I make the inference from my local machine. 

Please could someone assist me in understanding how to get the hosted api (on https://huggingface.co/shrugging-grace/tweetclassifier) to work correctly ? Potentially one for: @LysandreJik

**Comment by julien-c** [comment]
Fixed now. 

https://huggingface.co/shrugging-grace/tweetclassifier?text=I+like+you.+I+love+you

You should add a label map to get the correct labels displayed in the widget.

Thanks!

**Comment by JME-P** [comment]
Thank you!
