### ISSUE TITLE
Reformer now requires PyTorch 1.6.0

### ISSUE THREAD

**Issue by sgugger** [huggingface/transformers#6277]
@patrickvonplaten, one of your recent PR (#6244) on Reformer introduces a dep on PyTorch 1.6.0 minimum by using `torch.cuda.default_generators`. We should see if we can find a way to work around this.

**Comment by patrickvonplaten** [comment]
yes! I think the change #6244 is also only necessary in PyTorch 1.6 -> maybe we can even hard-code `torch.__version__` in the code and use the appropriate functions accordingly. Think this is also very much related to the previous bug: https://github.com/pytorch/pytorch/issues/33546

**Comment by patrickvonplaten** [comment]
#6300 should fix it.
