### ISSUE TITLE
Problem with converting XLM checkpoint to pytorch (missing merges.txt)

### ISSUE THREAD

**Issue by sebastian-nehrdich** [huggingface/transformers#6283]
Hello, 

I would like to use a checkpoint that I trained with XLM before (https://github.com/facebookresearch/XLM). 
For that I am using the following script: https://github.com/huggingface/transformers/blob/master/src/transformers/convert_xlm_original_pytorch_checkpoint_to_pytorch.py
The conversion works fine but in the end I only get a vocab.json but merges.txt is missing (which is no surprise looking at the script above). Is there any way to reconstruct the merges.txt from the vocab? I also still have the original training data used for the model and the bpe codes etc. used with XLM if that is of any help.

**Comment by null-id** [comment]
Yeah, I meet the exactly same problem. Where is the merges.txt?
