### ISSUE TITLE
Question about BERT model size (transformer block number) 

### ISSUE THREAD

**Issue by ZLKong** [huggingface/transformers#6297]
# ❓ Questions & Help

## Details
Hi,

Thank you for your interesting work! I have just started to learn BERT and distillation recently. I have some general questions regarding this topic.

1. I want to compare the performance of BERT with different model size (transformer block number). Is it necessary to do distillation? If I just train a BERT with 6 Layers without distillation, does the performance look bad?

2. Do you have to do pretraining every time you change the layer number of BERT? Is it possible to just remove some layers in an existing pre-trained model and finetune on tasks?

3. Why BERT has 12 blocks? Not 11 or 13 etc. ? I couldn't find any explanation.

Thanks,
ZLK

**Comment by TevenLeScao** [comment]
Hi ZLK, we're trying to keep Github issues on our repo strictly related to code. [Our forum](https://discuss.huggingface.co) is a much better place for general questions like yours, and the people over there will better be able to answer it! Cheers
