### ISSUE TITLE
Error trying to import SquadDataset

### ISSUE THREAD

**Issue by brian8128** [huggingface/transformers#6313]
## Environment info

- `transformers` version: 3.0.2
- Platform: Linux-4.15.0-108-generic-x86_64-with-glibc2.10
- Python version: 3.8.2
- PyTorch version (GPU?): 1.4.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help
@sgugger @julien-c 
 
## Information

I am trying to follow the run_squad_trainer example. However I am unable to import the SquadDataset from transformers. I tried updating to 3.0.2 but got the same error. 
https://github.com/huggingface/transformers/blob/master/examples/question-answering/run_squad_trainer.py

```
from transformers import SquadDataset
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-13f8e9ce9352> in <module>
----> 1 from transformers import SquadDataset

ImportError: cannot import name 'SquadDataset' from 'transformers' (/home/brian/miniconda3/envs/ML38/lib/python3.8/site-packages/transformers/__init__.py)
```

## Expected behavior

Import runs without error.

**Comment by patil-suraj** [comment]
Hi @brian8128 , `SquadDataset` was added after the 3.0.2 release. You'll need to install from source to use it

**Comment by brian8128** [comment]
Thanks! It's working now. You guys have written some code around this stuff!
