### ISSUE TITLE
Dataloader number of workers in Trainer

### ISSUE THREAD

**Issue by ggaemo** [huggingface/transformers#6316]
https://github.com/huggingface/transformers/blob/175cd45e13b2e33d1efec9e2ac217cba99f6ae58/src/transformers/trainer.py#L252

If you want to use the Trainer from trainer.py, you only have the option to use only 0 number of workers for your dataloader.

However, even if I change the source code to have 10 number or workers for the data loader, the model still uses the same thread.

**Comment by arahusky** [comment]
+1.

I suppose it should not be difficult to add additional argument to ```self.args``` specifying number of workers to use and to use it as:
```
return DataLoader(
            self.train_dataset,
            batch_size=self.args.train_batch_size,
            sampler=train_sampler,
            collate_fn=self.data_collator,
            drop_last=self.args.dataloader_drop_last,
            num_workers=self.args.num_workers
        )
```

Is there any particular reason why this was not yet implemented?

**Comment by misrasaurabh1** [comment]
+1

**Comment by jxhe** [comment]
+1

**Comment by LysandreJik** [comment]
No particular reason why it was not implemented, would welcome a PR!
