### ISSUE TITLE
TFBert runs slower than keras-bert， any plan to speed up？

### ISSUE THREAD

**Issue by kismit** [huggingface/transformers#6318]
classification task run with keras-bert using 7ms, but run with TFBert using 50+ms, both of them runing on GPU, detail arguments:
hidden layers: 6
max_seq_length: 64
cuda: 2080ti

As I see, most of time using cost by bert encoder, average 6 ms per encoder layer, while keras-bert encoder per layer use less than 1ms

do we have any plan to solve this problem？
ths！

**Comment by patrickvonplaten** [comment]
This is related: https://github.com/huggingface/transformers/pull/6877
