### ISSUE TITLE
Text-to-SQL Query

### ISSUE THREAD

**Issue by thiagomoeng** [huggingface/transformers#6325]
# ❓ Questions & Help

Hello everyone, I got a task that I want to use NLP for convert text into a SQL query. Anyone knows how to do this or got any suggestion? Thanks.

**Comment by patil-suraj** [comment]
pinging @mrm8488 .

**Comment by mrm8488** [comment]
You can try this model: https://huggingface.co/mrm8488/t5-base-finetuned-wikiSQL
Thanks for ping me @patil-suraj

**Comment by NielsRogge** [comment]
If you go to the model hub and type 'SQL', you get [this](https://huggingface.co/models?search=Sql). There are currently 3 variants of the T5 model fine-tunes on WikiSQL (a large dataset that contains sentence - SQL pairs).

**Comment by thiagomoeng** [comment]
Hi @mrm8488  I am having some issue with "torch_xla" module, is there any way to run this model on local windows, without this TPU module? Thanks.

**Comment by patil-suraj** [comment]
hi @thiagomoeng, can you try setting the `xla_device` argument in `config.json` to `False`.

```python3
config = T5Config.from_pretrained("mrm8488/t5-base-finetuned-wikiSQL")
config.xla_device = False
model = T5ForConditionalGeneration.from_pretrained("mrm8488/t5-base-finetuned-wikiSQL", config=config)

**Comment by anushab3** [comment]
Facing this error after using T5 on Tpu code . could you please help me here

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-101e09b206b5> in <module>()
     25 # so make sure the keys match the parameter names of the forward method
     26 @dataclass
---> 27 class T2TDataCollator(DataCollator):
     28     def collate_batch(self, batch: List) -> Dict[str, torch.Tensor]:
     29         """

TypeError: function() argument 1 must be code, not str

**Comment by thiagomoeng** [comment]
Hi @mrm8488  I got a SQL data on Oracle, do you can give me some way of how to prepare this sql data to finetune on your model? I knew on training models.

**Comment by abhijithneilabraham** [comment]
@thiagomoeng  if you want to convert natural language to sql , here is one implementation : https://github.com/abhijithneilabraham/tableQA

Drop me any comments on the slack channel in the readme there.
