### ISSUE TITLE
BertForPreTraining with NSP

### ISSUE THREAD

**Issue by choidongyeon** [huggingface/transformers#6330]
# ❓ Questions & Help

## Details
I am trying to train BERT from scratch following a modification of https://huggingface.co/blog/how-to-train, where I use a BertTokenizer and BertForPreTraining. The [documentation for BertForPreTraining](https://huggingface.co/transformers/model_doc/bert.html#transformers.BertForPreTraining) states that it has two heads on top for both pre-training processes (MLM and NSP), but [the example provided](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_bert.py#L874-L884) only provides an example of MLM.

Based on [a comment](https://github.com/huggingface/transformers/issues/2693#issuecomment-580870278) provided by @LysandreJik in a previous issue, it seems that none of the provided datasets (i.e. LineByLineTextDataset) will handle the NSP objective and this objective is excluded because the RoBERTa paper has proven that the NSP objective was not particularly helpful.

@LysandreJik additionally noted that anyone who wants to implement the NSP objective can do so by changing the dataset/training loop, and I was wondering if there were any plans to add support for NSP for the sake of completeness? 

It seems that something similar to what is going on in a PR (https://github.com/huggingface/transformers/pull/6168) for Albert SOP can be done. Is this correct and can anyone provide me with some guidance moving forward?

**Comment by LysandreJik** [comment]
Hi! Supporting the NSP objective is not on our roadmap, due to the reason you've linked and because of insufficient bandwidth. 

However, similar to the work in #6168 for SOP, we're very open to contributions and would accept a PR adding the BERT NSP objective to the datacollators/datasets.

**Comment by choidongyeon** [comment]
Awesome, I've been working on something similar. Will open a PR, thanks!

**Comment by Jetcodery** [comment]
@choidongyeon  May i ask if the work on dataset part using in BertForPreTraining APIs is finished?  Any PR link or codes can help, looking forward to your reply, thx!
