### ISSUE TITLE
broken ONNX slow test

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#6336]
```
    def test_quantize_pytorch(self):
        for model in OnnxExportTestCase.MODEL_TO_TEST:
            path = self._test_export(model, "pt", 12)
>           quantized_path = quantize(Path(path))
```
tests/test_onnx.py:75:  `path` is None

https://github.com/huggingface/transformers/runs/960368281?check_suite_focus=true

**Comment by LysandreJik** [comment]
This seems to be a bit of a flaky test, doesn't it?

**Comment by sshleifer** [comment]
There is strange try/except syntax in `setup` that I think can be trivially improved.
