### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers' on Google Colab

### ISSUE THREAD

**Issue by Mohd-Misran** [huggingface/transformers#6347]
I installed **transformers** using the command `!pip install transformers` on **Google Colab Notebook**
But then I try to `import transformers` it throws an error.

This is the output of the pip install command:

Requirement already satisfied: transformers in /usr/local/lib/python3.6/dist-packages/transformers-3.0.2-py3.6.egg (3.0.2)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.6/dist-packages (from transformers) (0.7)
Requirement already satisfied: filelock in /usr/local/lib/python3.6/dist-packages (from transformers) (3.0.12)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from transformers) (1.18.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from transformers) (20.4)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.6/dist-packages (from transformers) (2019.12.20)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from transformers) (2.23.0)
Requirement already satisfied: sacremoses in /usr/local/lib/python3.6/dist-packages/sacremoses-0.0.43-py3.6.egg (from transformers) (0.0.43)
Requirement already satisfied: sentencepiece!=0.1.92 in /usr/local/lib/python3.6/dist-packages/sentencepiece-0.1.91-py3.6-linux-x86_64.egg (from transformers) (0.1.91)
Requirement already satisfied: tokenizers==0.8.1.rc1 in /usr/local/lib/python3.6/dist-packages/tokenizers-0.8.1rc1-py3.6-linux-x86_64.egg (from transformers) (0.8.1rc1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.6/dist-packages (from transformers) (4.41.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from packaging->transformers) (1.15.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->transformers) (2.4.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->transformers) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->transformers) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->transformers) (2020.6.20)
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from sacremoses->transformers) (7.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from sacremoses->transformers) (0.16.0)

**Comment by TarasPriadka** [comment]
@Mohd-Misran seems to be working for me 
![image](https://user-images.githubusercontent.com/14134797/89741111-4e53cc00-da43-11ea-9a09-94431217301e.png). 

Maybe try to open a new colab notebook?

**Comment by julien-c** [comment]
You need to restart your Colab runtime after installing new dependencies

**Comment by hari-chalise** [comment]
pip install transformers
pip install sklearn 

this throw error 
File ["<ipython-input-3-c2c0574051f0>"](https://localhost:8080/#), line 1
    pip install transformers
        ^
SyntaxError: invalid syntax


what is the solutions?

**Comment by amyeroberts** [comment]
@hari-chalise Are you working in a notebook? If so, any command-like commands need to be run with `!` at the start i.e. `!pip install transformers`
