### ISSUE TITLE
Why is distillbart-cnn done with no teacher and distilbart-xsum has a teacher?

### ISSUE THREAD

**Issue by moyid** [huggingface/transformers#6351]
@sshleifer Can you expand on why distillbart-xsum is done with a teacher and distillbart-cnn is not?

**Comment by sshleifer** [comment]
It's purely empirical. `distilbart-xsum` variants perform about 1-2 ROUGE pts worse without a teacher, the gap is basically 0 for the `distilbart-cnn` variants.  For translation, it seems like teacher also helps a bit.

**Comment by sshleifer** [comment]
In the future, you can tag me on discussion questions on discuss.huggingface.co !
