### ISSUE TITLE
Bug in squad example with XLNet

### ISSUE THREAD

**Issue by zeeqy** [huggingface/transformers#6360]
## Environment info

     
- `transformers` version: 3.0.2
- Platform: Linux-3.10.0-957.21.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
- Python version: 3.7.4
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?): 2.0.0 (False)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

## Information

Model I am using (Bert, XLNet ...):
XLNet

The problem arises when using:
the official example scripts: (give details below)

The tasks I am working on is:
an official GLUE/SQUaD task: (give the name)

## To reproduce

1. run_squad.py with xlnet as the mode type
2. I think because the AutoModelForQuestionAnswering is mapping xlnet to XLNetForQuestionAnsweringSimple, it will have input error. Since XLNetForQuestionAnsweringSimple does not require cls_index, it will throw an error
3. https://github.com/huggingface/transformers/blob/d9149f00d1a4650bafa7e1cd73e10398193c852c/examples/question-answering/run_squad.py#L194

**Comment by brettkoonce** [comment]
see also #3535
