### ISSUE TITLE
AttributeError: type object "BartTokenizer" has no attribute 'name'

### ISSUE THREAD

**Issue by Siddhant021295** [huggingface/transformers#6384]
## Environment info

     
- `transformers` version: 3.0.2
- Platform: Google Colab
- Python version: 3.7
- PyTorch version (GPU?): 
- Tensorflow version (GPU?):
- Using GPU in script?:  Yes
- Using distributed or parallel set-up in script?: don't know

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Using the script provided on Hugging face library 
 : https://github.com/ohmeow/ohmeow_website/blob/master/_notebooks/2020-05-23-text-generation-with-blurr.ipynb

**Comment by sgugger** [comment]
I think the notebook you are linking is trying to access the `name` attribute of `BartTokenizer` which does not exist indeed. It looks like the failure should be reported to the author of that notebook, it's not a bug in transformers.

**Comment by patil-suraj** [comment]
Pinging @ohmeow

**Comment by ohmeow** [comment]
Yah, I'm here :)
