### ISSUE TITLE
ZeroDivisionError with Reformer

### ISSUE THREAD

**Issue by eliasjacob** [huggingface/transformers#6400]
## Environment info

     
- `transformers` version: 3.0.0
- Platform: Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

## Information

Model I am using (Bert, XLNet ...): **Reformer**

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below) (well, actually, not my own, but @patrickvonplaten 's) 

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Execute @patrickvonplaten 's notebook available at https://colab.research.google.com/github/patrickvonplaten/notebooks/blob/master/Reformer_For_Masked_LM.ipynb 
2. I've tried to run it on google colab and works fine. The problem appears when I try to run on my machine.
3. I've tried it with two different clean virtual environments (python 3.6 and 3.7), but they've both failed.
4. I haven't change the dataset, nor any model config/training args.
4. After calling trainer.train() I get the following error

```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-13-02431faf649a> in <module>
      8 
      9 # train
---> 10 trainer.train()

/data/venv36/lib/python3.6/site-packages/transformers/trainer.py in train(self, model_path)
    394             t_total = self.args.max_steps
    395             num_train_epochs = (
--> 396                 self.args.max_steps // (len(train_dataloader) // self.args.gradient_accumulation_steps) + 1
    397             )
    398         else:

ZeroDivisionError: integer division or modulo by zero

```
## Expected behavior

The model should begin to train

Thanks!

**Comment by patrickvonplaten** [comment]
Hey @eliasjacob, the problem is probably that `self.args.gradient_accumaltion_steps` is set to a value > then `(len(train_dataloader)`

**Comment by eliasjacob** [comment]
You were right (although I am unsure why the same notebook yielded different results in collab). Thank you very much!

**Comment by ldong87** [comment]
This problem happened to me too. In my case, gradient_accumulation_steps is set to 2. The code runs fine on cpu but gives this error on a multi-gpu, single host scenario. My train data has 100 records. How come my len(train_dataloader) is smaller than 2 in this case?
