### ISSUE TITLE
i have used t5_base for abstractive summarization but it is not giving good results,Could you please give me solution for this

### ISSUE THREAD

**Issue by gopal354** [huggingface/transformers#6408]
# 🖥 Benchmarking `transformers`

## Benchmark

Which part of `transformers` did you benchmark?

## Set-up

What did you run your benchmarks on? Please include details, such as: CPU, GPU? If using multiple GPUs, which parallelization did you use?

## Results

Put your results here!

**Comment by patil-suraj** [comment]
Hi @gopal354 , this depends on lot of factors. What is the domain of your dataset ? There are many other summrization models  available on the model hub trained on different datasets. You can try them as well. Or if you have a dataset, then you can further fine-tune these models on your domain.

**Comment by patil-suraj** [comment]
Would be nice if you can write the detailed question in the description box rather than title and use the relevant issue topic (this should be Questions & Help and not Benchmarking transformers). This will help the team and contributors to act faster on the issue :)
