### ISSUE TITLE
Experiment: ROUGE impact of using pegasus length-penalty implementation

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#6420]
code is under `length_normalization` in the pegasus [tf repo](https://github.com/google-research/pegasus)

**Comment by sshleifer** [comment]
I tried this a bit and did not get any improvements. Meanwhile, our beam search is getting similar scores to pegasus in #6844 , so I am less motivated to push further.
Branch with maybe correct beam search implem: https://github.com/sshleifer/transformers_fork/tree/peg-beam

**Comment by Oxi84** [comment]
> 
> 
> I tried this a bit and did not get any improvements. Meanwhile, our beam search is getting similar scores to pegasus in #6844 , so I am less motivated to push further.
> Branch with maybe correct beam search implem: https://github.com/sshleifer/transformers_fork/tree/peg-beam

If it is better how can we install this? Can we do this with pip? Thanks.
