### ISSUE TITLE
Error in run_tf_squad.py script

### ISSUE THREAD

**Issue by M-Salti** [huggingface/transformers#6428]
## Environment info

     
- `transformers` version: 3.0.2
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.6.0+cu101 (True)
- Tensorflow version (GPU?): 2.3.0 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help
 @sgugger

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: SQUaD
* [ ] my own task or dataset: (give details below)

I'm simply trying to train a new question answering model using the TF trainer script, and I get the following error:
```python
Traceback (most recent call last):
  File "run_tf_squad.py", line 244, in <module>
    main()
  File "run_tf_squad.py", line 123, in main
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, TFTrainingArguments))
  File "/usr/local/lib/python3.6/dist-packages/transformers/hf_argparser.py", line 40, in __init__
    self._add_dataclass_arguments(dtype)
  File "/usr/local/lib/python3.6/dist-packages/transformers/hf_argparser.py", line 72, in _add_dataclass_arguments
    elif hasattr(field.type, "__origin__") and issubclass(field.type.__origin__, List):
  File "/usr/lib/python3.6/typing.py", line 1154, in __subclasscheck__
    return super().__subclasscheck__(cls)
  File "/usr/lib/python3.6/abc.py", line 209, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/usr/lib/python3.6/typing.py", line 890, in __extrahook__
    if cls.__extra__ and issubclass(subclass, cls.__extra__):
TypeError: issubclass() arg 1 must be a class
```

## To reproduce

1.install transformers from the master branch
2.run the example script in question-answering:
```
python run_tf_squad.py \
    --model_name_or_path bert-base-uncased \
    --output_dir model \
    --max_seq_length 384 \
    --num_train_epochs 2 \
    --per_gpu_train_batch_size 8 \
    --per_gpu_eval_batch_size 16 \
    --do_train \
    --logging_dir logs \    
    --logging_steps 10 \
    --learning_rate 3e-5 \
    --doc_stride 128    
```

## Expected behavior
The script should run normally and train the model

**Comment by M-Salti** [comment]
The error seems to be caused by the field `use_tfds` from the `DataTrainingArguments` class.
Changing its type from `Optional[bool]` to `bool` and changing the default value to `False`, seem to resolve the issue, however, I don't really understand why and I'm not sure whether this is the right way to fix the issue.

**Comment by sgugger** [comment]
Can reproduce, will investigate today.
