### ISSUE TITLE
Training GPT2 and Reformer from scratch.  

### ISSUE THREAD

**Issue by VikasRajashekar** [huggingface/transformers#6438]
Hello, I am looking, for example, script/notebook to train GPT2 and Reformer model from scratch in German. 
Something similar to : 
https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/01_how_to_train.ipynb

I am trying to modify the same notebook but GPT2 doesn't seem to accept LinebyLineDataset or padding.

**Comment by patrickvonplaten** [comment]
Hey @VikasRajashekar, 

We are trying to move "non-bug" related questions to https://discuss.huggingface.co/ - could you post your question there again? :-)

**Comment by patrickvonplaten** [comment]
Btw, for Reformer, you can check out these notebooks: https://github.com/patrickvonplaten/notebooks/blob/master/PyTorch_Reformer.ipynb and https://github.com/patrickvonplaten/notebooks/blob/master/Reformer_For_Masked_LM.ipynb
