### ISSUE TITLE
getting error while training bert language model. "ValueError: Expected input batch_size (8) to match target batch_size (1024)."

### ISSUE THREAD

**Issue by bharathrajcl** [huggingface/transformers#6452]
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
from transformers import BertForSequenceClassification
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

%%time
from transformers import LineByLineTextDataset,TextDataset

paths = '/content/drive/My Drive/MyFile.txt'
dataset = TextDataset(
    tokenizer=tokenizer,
    file_path=paths,
    block_size=128,
)

from transformers import DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer, mlm=True, mlm_probability=0.15
)

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./EsperBERTo",
    overwrite_output_dir=True,
    num_train_epochs=1,
    save_total_limit=2,
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=dataset,
    prediction_loss_only=True,
)

%%time
trainer.train()

**'**''''''''''''''''''''''''''''''''''''''Getting error after executing trainer.train() ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''****

ValueError                                Traceback (most recent call last)
<ipython-input-12-0c647bc3a8b8> in <module>()
----> 1 get_ipython().run_cell_magic('time', '', 'trainer.train()')

10 frames
<decorator-gen-60> in time(self, line, cell, local_ns)

<timed eval> in <module>()

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   2214     if input.size(0) != target.size(0):
   2215         raise ValueError('Expected input batch_size ({}) to match target batch_size ({}).'
-> 2216                          .format(input.size(0), target.size(0)))
   2217     if dim == 2:
   2218         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

**ValueError: Expected input batch_size (8) to match target batch_size (1024).**

please help me to resolve this issue.

**Comment by chaima-ai** [comment]
the same probleme ??

Expected input batch_size (15) to match target batch_size (0).

**Comment by gborodin** [comment]
Same problem

**Comment by RufusGladiuz** [comment]
I have the same problem.

**Comment by anjandash** [comment]
Same here! Anyone resolved it yet? @bharathrajcl @chaima-ai @gborodin @RufusGladiuz
