### ISSUE TITLE
Unknown task zero-shot-classification

### ISSUE THREAD

**Issue by amarlearning** [huggingface/transformers#6458]
## Environment info

     
- `transformers` version: 3.0.2
- Platform: Ubuntu 18
- Python version: 3.7

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. I downloaded transformer version 3.0.2
2. From transformer, I imported pipeline
3. And from the pipeline, I was trying to load this task `zero-shot-classification` and then I got the error.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-1f0825594ce1> in <module>
----> 1 classifier = pipeline("zero-shot-classification")

~/anaconda3/lib/python3.7/site-packages/transformers/pipelines.py in pipeline(task, model, config, tokenizer, framework, **kwargs)
   1819     # Retrieve the task
   1820     if task not in SUPPORTED_TASKS:
-> 1821         raise KeyError("Unknown task {}, available tasks are {}".format(task, list(SUPPORTED_TASKS.keys())))
   1822 
   1823     framework = framework or get_framework(model)

KeyError: "Unknown task zero-shot-classification, available tasks are ['feature-extraction', 'sentiment-analysis', 'ner', 'question-answering', 'fill-mask', 'summarization', 'translation_en_to_fr', 'translation_en_to_de', 'translation_en_to_ro', 'text-generation']"
```

**Comment by LysandreJik** [comment]
Hello! this task is only available on the `master` branch as of now. You can install it as such: `pip install git+https://github.com/huggingface/transformers`.

It will be in the next release!

**Comment by Tolga28A** [comment]
This is still happening on Databricks even though I re-installed the package several times today. Any thoughts?

**Comment by julien-c** [comment]
@Tolga28A Can you document what exact command(s) you run on Databricks (and how)?

**Comment by Tolga28A** [comment]
pip install git+https://github.com/huggingface/transformers
from transformers import pipeline
classifier = pipeline('zero-shot-classification')

and the output is:


KeyError: "Unknown task zero-shot-classification, available tasks are ['feature-extraction', 'sentiment-analysis', 'ner', 'question-answering', 'fill-mask', 'summarization', 'translation_en_to_fr', 'translation_en_to_de', 'translation_en_to_ro', 'text-generation']"
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<command-2362828626522668> in <module>
----> 1 classifier = pipeline('zero-shot-classification')

/local_disk0/.ephemeral_nfs/envs/pythonEnv-a6d3a5c1-2f0b-495b-828f-f792f8695d17/lib/python3.7/site-packages/transformers/pipelines.py in pipeline(task, model, config, tokenizer, framework, **kwargs)
   1819     # Retrieve the task
   1820     if task not in SUPPORTED_TASKS:
-> 1821         raise KeyError("Unknown task {}, available tasks are {}".format(task, list(SUPPORTED_TASKS.keys())))
   1822 
   1823     framework = framework or get_framework(model)

KeyError: "Unknown task zero-shot-classification, available tasks are ['feature-extraction', 'sentiment-analysis', 'ner', 'question-answering', 'fill-mask', 'summarization', 'translation_en_to_fr', 'translation_en_to_de', 'translation_en_to_ro', 'text-generation']"

**Comment by julien-c** [comment]
Start from a brand new venv or uninstall transformers before re-installing?
