### ISSUE TITLE
Autotokenizer not returning instance of LongformerTokenizerFast

### ISSUE THREAD

**Issue by pratikdk** [huggingface/transformers#6459]
## Environment info
     
- `transformers` version: 3.0.2
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.6.0+cu101 (False)
- Tensorflow version (GPU?): 2.3.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: Google Colab

## Information

Model I am using :  Longformer 
Path: **'allenai/longformer-base-4096'** and **'allenai/longformer-large-4096'**

The problem arises when trying to load 'Fast' version for Longformer using Autotokenizer, the returned tokenizer instance is an object of LongformerTokenizer and not LongformerTokenizerFast. 

![Annotation 2020-08-13 160156](https://user-images.githubusercontent.com/20542313/90124665-68ace300-dd7e-11ea-8cc7-fdd80f070bec.png)

I require the offset mappings for a sub task of extracting word embeddings.

## To reproduce
Just as in the screenshot i am adding the code below to instantiate the tokenizer object:
```
longformer_tokenizer = AutoTokenizer.from_pretrained(
    pretrained_model_name_or_path = 'allenai/longformer-base-4096', use_fast=True)
print(longformer_tokenizer.is_fast)
print(longformer_tokenizer)
```
And since its not an instance of  transformers.LongformerTokenizerFast, I cannot `return_offsets_mapping=True`
As in the below code throws `NotImplementedError`

```
longformer_encoded_dict = longformer_tokenizer.encode_plus(text=sequence_3,
                                                    add_special_tokens = True,
                                                    max_length = 75,
                                                    truncation = True,
                                                    pad_to_max_length = False,
                                                    return_token_type_ids = False,
                                                    return_attention_mask = True,
                                                    return_overflowing_tokens = False,
                                                    return_special_tokens_mask = False,
                                                    return_offsets_mapping=True)
```
**Error**
`
NotImplementedError: return_offsets_mapping is not available when using Python tokenizers.To use this feature, change your tokenizer to one deriving from transformers.PreTrainedTokenizerFast.`

@mfuntowicz
@patrickvonplaten

**Comment by patil-suraj** [comment]
Hi @pratikdk  thank you for reporting this! Just made a PR, will be fixed soon. Till then you can use `LongformerTokenizerFast` class
