### ISSUE TITLE
Longformer convert error

### ISSUE THREAD

**Issue by Maybewuss** [huggingface/transformers#6465]
When i install transformers from source and convert bert to "long vesion", [failed.](https://colab.research.google.com/github/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb)

**Comment by Maybewuss** [comment]
Error(s) in loading state_dict for RobertaLongForMaskedLM:
size mismatch for embeddings.position_ids: copying a param with shape torch.Size([1, 512]) from checkpoint, the shape in current model is torch.Size([1, 4096]).

**Comment by patrickvonplaten** [comment]
Hey @Maybewuss,

This is a community notebook, so we don't really plan on maintaining this notebook with current library changes. 
Regarding your question I would suggest to post it on https://discuss.huggingface.co/ and/or to contact the author @ibeltagy - maybe he can help you.

Before that it would be nice if you can create a notebook which can be used to re-create your error (replacing RoBERTA with BERT in the above notebook)

**Comment by alexyalunin** [comment]
@patrickvonplaten Is there a way of converting existing models to Longformer? The notebook above (from allennlp) seem not to be useful since you can't automatically convert their 'long' model to Longformer Huggingface's class. The only way I see is to manually remap nodes.

**Comment by patrickvonplaten** [comment]
Yeah, it is not straight-forward to convert *any* HF model to its "long" version. You will need to write some special code for this yourself I think. The notebook should work more as an example for how it can be done with a model like Roberta

**Comment by NadiaRom** [comment]
I faced the same error with roberta. Size mismatch was in the position embedding and position ids. Adding the following lines to `create_long_model` helped:
```{python}
model.roberta.embeddings.position_embeddings.weight.data = new_pos_embed    # add after this line
model.roberta.embeddings.position_embeddings.num_embeddings = len(new_pos_embed.data)
# first, check that model.roberta.embeddings.position_embeddings.weight.data.shape is correct — has to be 4096 (default) of your desired length
model.roberta.embeddings.position_ids = torch.arange(
    0, model.roberta.embeddings.position_embeddings.num_embeddings
)[None]
```

For some reason number of embeddings didn't change after adding new weight tensor, so we fix it and also add news position ids.
I use torch==1.6.0 and transformers==3.4.0

**Comment by MarkusSagen** [comment]
@NadiaRom Fantastic! Been trying to move this script over to the latest Transformer release and works great

**Comment by versae** [comment]
@MarkusSagen, were you able to solve the `forward()` issue?

**Comment by MarkusSagen** [comment]
@versae I only looked at it for a couple of hours and decided it was easier to roll back to an earlier version of transformers. If anyone implements a fix, I would be very interested to hear 😊👌
