### ISSUE TITLE
Upladed model is not indexed

### ISSUE THREAD

**Issue by mrm8488** [huggingface/transformers#6478]
# ❓ Questions & Help

Hi guys, I uploaded a model several hours ago (t5-base-finetuned-boolq) and it is not indexed in the model hub search engine yet!

Thanks, Manu

**Comment by patil-suraj** [comment]
The model is also not listed on your [page ](https://huggingface.co/mrm8488). Can you try re-uploading ?

**Comment by mrm8488** [comment]
If you load it in your code ```mrm8488/t5-finetuned-boolq``` it works! Maybe a problem indexing it.

**Comment by LysandreJik** [comment]
cc @julien-c

**Comment by paulowoicho** [comment]
Hi everyone, has there been a way fix this? I too also uploaded a model (t5-podcast-summarisation) that hasn't shown up on the model hub. I am able to load it in my code using `paulowoicho/t5-podcast-summarisation` though

**Comment by julien-c** [comment]
Fixed:
- https://huggingface.co/mrm8488/t5-base-finetuned-boolq
- https://huggingface.co/paulowoicho/t5-podcast-summarisation
