### ISSUE TITLE
what's the difference between TFBertOutput and TFBertSelfOutput?

### ISSUE THREAD

**Issue by policeme** [huggingface/transformers#6481]
# ❓ Questions & Help

## Details

`TFBertOutput` with `TFBertSelfOutput` seem same in their codes. why did you write two same layers? is there for some reasons?

**Comment by patrickvonplaten** [comment]
Hey @policeme, fair point they seem to be exactly the same. There is a logical difference though `TFBertOutput` is the output of a `TFBertLayer` while `TFBertSelfOutput` is the output a `TFBertAtteniton` (Self-attention -> thus "SelfOutput"). 
But yeah this might seem a bit confusing at first.
