### ISSUE TITLE
Model Upload does not show up `german-nlp-group/electra-base-german-uncased`

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#6495]
Hi,
yesterday I uploaded a new model to `german-nlp-group/electra-base-german-uncased`:

```bash
$ transformers-cli s3 ls --organization german-nlp-group
Neither PyTorch nor TensorFlow >= 2.0 have been found.Models won't be available and only tokenizers, configurationand file/data utilities can be used.
Filename                                          LastModified             ETag                               Size      
------------------------------------------------- ------------------------ ---------------------------------- --------- 
electra-base-german-uncased/config.json           2020-08-14T17:13:01.000Z "10c75064301189f269b4898d4265cd61"       467 
electra-base-german-uncased/pytorch_model.bin     2020-08-14T17:13:37.000Z "a621e1cb07af0a08aaa643af52f9f189" 444881731 
electra-base-german-uncased/tokenizer_config.json 2020-08-14T17:43:33.000Z "7f6d7cb22bc6342b9c942da874754264"        86 
electra-base-german-uncased/vocab.txt             2020-08-14T17:43:31.000Z "e9fa1e40c556fc02c62ebaa214a52dc4"    275501
```

But it does not show up. See here: https://huggingface.co/german-nlp-group

What happened here? Could you fix that?

Thanks
Philip

**Comment by PhilipMay** [comment]
The files are there: https://cdn.huggingface.co/german-nlp-group/electra-base-german-uncased/tokenizer_config.json

But it simply does not show up...

**Comment by PhilipMay** [comment]
Maybe related to #6478

**Comment by M-Salti** [comment]
Having the same problem here. Uploaded a new model (`salti/xlm-roberta-large-arabic_qa`) earlier this morning and it doesn't show up in the model hub, although I can download it and use it using the `from_pretrained` method.

**Comment by JetRunner** [comment]
@julien-c

**Comment by PhilipMay** [comment]
Maybe some sync service just needs a restart? :-)

**Comment by julien-c** [comment]
Not a sync service, but a (uncaught) user error :)

Fixed: https://huggingface.co/german-nlp-group/electra-base-german-uncased#german-electra-uncased
