### ISSUE TITLE
Can't load t5-11b from pre-trained

### ISSUE THREAD

**Issue by saareliad** [huggingface/transformers#6517]
## Environment info

     
- `transformers` version: 3.0.2
- Platform:
- Python version: 3.8.2
- PyTorch version 1.6

### Who can help

 T5: @patrickvonplaten

## Information

The model I am using: T5

## To reproduce

```
import transformers
transformers.T5ForConditionalGeneration.from_pretrained("t5-11b")
```

```


OSError: Can't load weights for 't5-11b'. Make sure that:

- 't5-11b' is a correct model identifier listed on 'https://huggingface.co/models'

- or 't5-11b' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.

```

## Expected behavior
the model should be loaded.

**Comment by patrickvonplaten** [comment]
Hey @saareliad, 
can you try:
```python
t5 = transformers.AutoModel.from_pretrained('t5-11b', use_cdn = False)
```

Also, see: https://github.com/huggingface/transformers/issues/5423

But the model cannot really be run before we take a closer look at: https://github.com/huggingface/transformers/pull/3578.

**Comment by julien-c** [comment]
@patrickvonplaten mind adding a big disclaimer to the model card for this particular checking? About what you just said (CDN limitation + model parallelism)

**Comment by saareliad** [comment]
Thanks @patrickvonplaten ,
Our work successfully adds (several types of) model parallellism and trains T5 and several other large transformers and is integrated with HF for quite a while.

Will opensource it soon :)
