### ISSUE TITLE
Can't load pegasus models.

### ISSUE THREAD

**Issue by aqdaskamal95** [huggingface/transformers#6520]
Hi, 

I've tried uploading Peagsus from PreTrainedModel and PreTrainedTokenizer but run into KeyError, I have transformers 3.0.2 - any idea why that might be happening?

**Comment by patil-suraj** [comment]
Not sure what you mean here. Can you please post the traceback and the code that resulted in the error ?

**Comment by AnkitVarshney02** [comment]
@patil-suraj I tried installing the master version using the shared URL but still it wasn't updated to master version.
Can you share more details for installing Transformers Master version?

**Comment by patil-suraj** [comment]
Sorry, typo. should be `-U` and not `-u`

`pip install -U git+https://github.com/huggingface/transformers.git`

**Comment by RafaelWO** [comment]
I can't load the `PegasusTokenizer` for the checkpoint `google/pegasus-pubmed`:
```Python
tokenizer = PegasusTokenizer.from_pretrained("google/pegasus-pubmed")
```
Error:
```
Traceback (most recent call last):
  File "src/download_model.py", line 17, in <module>
    tokenizer = PegasusTokenizer.from_pretrained(config['model_name'])
  File "/home/rafael/miniconda3/envs/torch/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1584, in from_pretrained
    raise EnvironmentError(
OSError: Model name 'google/pegasus-pubmed' was not found in tokenizers model name list (google/pegasus-xsum). We assumed 'google/pegasus-pubmed' was a path, a model identifier, or url to a directory containing vocabulary files named ['spiece.model'] but couldn't find such vocabulary files at this path or url.
```

**Comment by sshleifer** [comment]
Can't replicate on master. Please post `transformers-cli env` info when having download issues, and try solutions above in the thread before posting.

**Comment by RafaelWO** [comment]
Still not working for me. I have the feeling that my cached files for this checkpoint are messed up. Can I somehow find and delete them?
