### ISSUE TITLE
Bug in bart-base

### ISSUE THREAD

**Issue by ibeltagy** [huggingface/transformers#6540]
[Bart-base configuration](https://s3.amazonaws.com/models.huggingface.co/bert/facebook/bart-base/config.json) has the wrong values for `decoder_attention_heads` and `encoder_attention_heads`. This messes up the self-attention computation and make model totally unusable.  

### Who can help
@sshleifer

**Comment by sshleifer** [comment]
thx!

**Comment by sshleifer** [comment]
Should it be 12?

**Comment by ibeltagy** [comment]
yes

**Comment by sshleifer** [comment]
Fixed, great catch, sorry for the annoyance.

**Comment by sshleifer** [comment]
cc @VictorSanh if you are still using.
