### ISSUE TITLE
Add model card for facebook/mbart-large-en-ro

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#6552]
Suggested content:

___
tags:
- translation
language: en
___

link to fairseq readme
link to docs.

**Comment by julien-c** [comment]
```
---
language:
- en
- ro
---
```

no?

**Comment by sshleifer** [comment]
I didn't know you can have two! Will inference api still populate the text box with "My name is wolfgang"?

**Comment by julien-c** [comment]
Yes it will use the first one to populate the widget if there are several

**Comment by sshleifer** [comment]
Done: new config/moon-landing bug

![image](https://user-images.githubusercontent.com/6045025/90800838-2c7c0400-e2e3-11ea-8d4d-40e0aeac0850.png)
