### ISSUE TITLE
Create my own language model

### ISSUE THREAD

**Issue by dhimasyoga16** [huggingface/transformers#6561]
I'm new in NLP and i want to give BERT a try. I have a wikipedia corpus (in Indonesian language of course, and in .txt format) and want to train it with bert multilingual cased.
For further use, i expect that BERT can "adapt" well with indonesian language and can do specific task which is a text similarity task, or if possible do automated scoring based on the 2 texts given.

Can i use the [run_language_modeling.py](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py) to fine-tune and create my own language model?
If it's possible, then what are the exact steps to achieve this?

Thankyou in advance.

**Comment by julien-c** [comment]
For open-ended questions like this you should try https://discuss.huggingface.co

Did you read https://huggingface.co/blog/how-to-train?
