### ISSUE TITLE
KeyError with DPR reader in Question Answering pipeline

### ISSUE THREAD

**Issue by antoniolanza1996** [huggingface/transformers#6568]
## Environment info
- `transformers` version: 3.0.2 (I have also tried with current `master`)
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic (with Google Colab)
- Python version: 3.6.9
- PyTorch version (GPU?): 1.6.0+cu101 (False)
- Tensorflow version (GPU?): 2.3.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@LysandreJik

## Information

Model I am using: DPR reader (i.e. https://huggingface.co/facebook/dpr-reader-single-nq-base) to perform a Question Answering task.
## To reproduce

```from transformers import pipeline
model_name="facebook/dpr-reader-single-nq-base"
tokenizer_name="facebook/dpr-reader-single-nq-base"
my_pipeline = pipeline("question-answering", model=model_name, tokenizer=tokenizer_name)
```

Error message:
``` KeyError                                  Traceback (most recent call last)
<ipython-input-2-b3a2784cffcf> in <module>()
      4 model_name="facebook/dpr-reader-single-nq-base"
      5 tokenizer_name="facebook/dpr-reader-single-nq-base"
----> 6 my_pipeline = pipeline("question-answering", model=model_name, tokenizer=tokenizer_name)

2 frames
/usr/local/lib/python3.6/dist-packages/transformers/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    208 
    209         if "model_type" in config_dict:
--> 210             config_class = CONFIG_MAPPING[config_dict["model_type"]]
    211             return config_class.from_dict(config_dict, **kwargs)
    212         else:

KeyError: 'dpr'
```

**Comment by antoniolanza1996** [comment]
Hi @LysandreJik and @lhoestq ,
FYI, there is still this error on Transformers.
Have you planned to support DPR into pipeline API?

Thanks

**Comment by lhoestq** [comment]
Thanks for reporting !
The reader is currently not configured as a model for question answering indeed, but that's definitely something we'll change.
We'll also make it loadable as an an open-domain question answering Pipeline object.

**Comment by antoniolanza1996** [comment]
Hi @lhoestq ,
I got it.
Is there any approximate release date?
I believe that open-domain QA Pipeline will be really useful, thank you.
