### ISSUE TITLE
Bart: make decoder_input_ids correctly if labels specified.

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#6624]
should call shift_tokens_right(labels), like T5.

cc @patil-suraj: does that make sense?

**Comment by patil-suraj** [comment]
Yes, definitely. Better to handle it in the model. Since lots of recent issues were due to incorrect or not shifting labels

**Comment by patil-suraj** [comment]
But then `prepare_seq2seq_batch` should return `labels` instead of `decoder_input_ids`

**Comment by sshleifer** [comment]
yep. I'll take a stab.
