### ISSUE TITLE
**Specifically for Pegasus-arxiv** -  PegasusForConditionalGeneration - Error in loading state dictionary

### ISSUE THREAD

**Issue by suchig** [huggingface/transformers#6625]
Please note that this specifically happens only for **pegasus-arxiv** (Reopening Issue 6609). Before you close, please let me know if this works for pegasus-arxiv. Because I am getting the below error even after taking a fresh git fetch of transformers and removing all checkpoints from cache.

## Environment info
- `transformers` version: 3.0.2
- Platform: Linux-5.3.0-1034-azure-x86_64-with-debian-buster-sid
- Python version: 3.7.7
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): N/A
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help
@sshleifer
## Information

Model I am using (Bert, XLNet ...): **google/pegasus-arxiv**

## To reproduce
```ruby
mname = "google/pegasus-arxiv"
model = PegasusForConditionalGeneration.from_pretrained(mname)
```

throws error as below
File "/anaconda/envs/py37_default/lib/python3.7/site-packages/transformers/modeling_utils.py", line 894, in from_pretrained
model.class.name, "\n\t".join(error_msgs)
RuntimeError: Error(s) in loading state_dict for PegasusForConditionalGeneration:
size mismatch for model.encoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
size mismatch for model.decoder.embed_positions.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).

**Comment by sshleifer** [comment]
works for me with
```
- Python version: 3.7.4
- PyTorch version (GPU?): 1.5.1 (True)
```
Try
```
mname = "google/pegasus-arxiv"
model = PegasusForConditionalGeneration.from_pretrained(mname, force_download=True)
```

**Comment by suchig** [comment]
> works for me with
> 
> ```
> - Python version: 3.7.4
> - PyTorch version (GPU?): 1.5.1 (True)
> ```
> 
> Try
> 
> ```
> mname = "google/pegasus-arxiv"
> model = PegasusForConditionalGeneration.from_pretrained(mname, force_download=True)
> ```

Ok. It works now. Even though I did not use force_download, it downloaded a fresh copy of checkpoint. This can be closed.
