### ISSUE TITLE
Error on `PreTrainedTokenizerBase.batch_encode_plus` with `return_overflowing_tokens=True, truncation=True`

### ISSUE THREAD

**Issue by tamuhey** [huggingface/transformers#6632]
## Environment info

     
- `transformers` version: 3.0.2 (master branch)
- Platform: macOS-10.14.6-x86_64-i386-64bit
- Python version: 3.8.1
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): 2.3.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

 tokenizers: @mfuntowicz

## Information

Model I am using (Bert, XLNet ...): bert-base-uncased

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Run the below code

```python
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokenizer.batch_encode_plus(
    ["foo", "bar " * 1000], return_overflowing_tokens=True, truncation=True, padding=True
)
```

raises the following error:

```
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    tokenizer.batch_encode_plus(
  File "/Users/user/work/transformers/src/transformers/tokenization_utils_base.py", line 2121, in batch_encode_plus
    return self._batch_encode_plus(
  File "/Users/user/work/transformers/src/transformers/tokenization_utils.py", line 534, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
  File "/Users/user/work/transformers/src/transformers/tokenization_utils.py", line 606, in _batch_prepare_for_model
    batch_outputs = self.pad(
  File "/Users/user/work/transformers/src/transformers/tokenization_utils_base.py", line 2305, in pad
    assert all(
AssertionError: Some items in the output dictionnary have a different batch size than others.
```

## Expected behavior

No error

**Comment by LysandreJik** [comment]
@mfuntowicz the issue here is that one of the string returns an `overflowing_tokens` value (as it overflows) while the other doesn't. The resulting batch contains `overflowing_tokens` that have a single list, rather than two (one for each string).

Here's a proposed fix https://github.com/huggingface/transformers/pull/6677.
