### ISSUE TITLE
BUILD upgrade to isort v5

### ISSUE THREAD

**Issue by MarcoGorelli** [huggingface/transformers#6681]
The contributing guide says

> Right now, we need an unreleased version of isort to avoid a bug:

However, it looks like the linked PR has been incorporated into the latest version of isort. I could submit a PR to address this if it would be welcome

**Comment by thomwolf** [comment]
which linked PR are you referring to?

**Comment by MarcoGorelli** [comment]
this one https://github.com/timothycrosley/isort/pull/1000 (it's linked to here https://huggingface.co/transformers/contributing.html )
