### ISSUE TITLE
Question Answering demonstrator for contribute model stopped working

### ISSUE THREAD

**Issue by mfebIBM** [huggingface/transformers#6688]
## Environment info

    
All if this is run on the huggingface platform for contributed models.

Processing of the model in other hosts works correctly, using the versions described below. Was there an upgrade to the deployed transformers demonstration code that breaks the loading of contributed q/a models?

- `transformers` version: 2.2.1
- Platform: ubuntu 18.04
- Python version: 3.7.7
- PyTorch version (GPU?): 1.3.1
- Tensorflow version (GPU?):
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: No

### Who can help

@mfuntowicz

## Information

Model I am using (Bert, XLNet ...):  Contributed model `mfeb/albert-xxlarge-v2-squad2` based on Albert xxlarge v2, pretrained with SQuAD2.

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)
* [x] web demonstrator for question answering, using the contributed model

The tasks I am working on is:
* [x] an official GLUE/SQuAD task: SQuAD 2
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Visit https://huggingface.co/mfeb/albert-xxlarge-v2-squad2
2. press `compute` button
3. See the following message:
```
Model name 'mfeb/albert-xxlarge-v2-squad2' was not found in tokenizers model name list (albert-base-v1, albert-large-v1, albert-xlarge-v1, albert-xxlarge-v1, albert-base-v2, albert-large-v2, albert-xlarge-v2, albert-xxlarge-v2). We assumed 'mfeb/albert-xxlarge-v2-squad2' was a path or url to a directory containing vocabulary files named ['spiece.model'], but couldn't find such vocabulary files at this path or url.
```

This seems to imply that the code that is performing the run_squad is not recognizing that the model is one of the contributed models (not one of the recognized, provided models).

## Expected behavior

An answer to the question: `London`

**Comment by julien-c** [comment]
Same issue as #6226. We are currently working on a fix, will post an update here.

**Comment by mfebIBM** [comment]
Interestingly, this was working last Thursday.

**Comment by mfuntowicz** [comment]
@mfebIBM It should be working right now, if you want to give it a try, let us know 👍.

Sorry for the inconvenience.

**Comment by mfebIBM** [comment]
Yes. Working now. Thanks!

**Comment by mfuntowicz** [comment]
I'm closing, don't hesitate to reopen if anything goes wrong.
