### ISSUE TITLE
Some weights of AlbertModel were not initialized ['albert.embeddings.position_ids'] 

### ISSUE THREAD

**Issue by vgaraujov** [huggingface/transformers#6700]
Hello!

There seems to be a problem with the current code to load a pre-trained Albert model. This warning appears in any configuration of the Albert model:
`Some weights of AlbertModel were not initialized from the model checkpoint at albert-base-v2 and are newly initialized: ['albert.embeddings.position_ids']`
`You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.`

I found this happens only when I install it from the source. Models load correctly (without warning) when installing the library with pip.

**Comment by LysandreJik** [comment]
Hello! Which checkpoint are you trying to load? Is it one of your checkpoints or is it one of the checkpoints hosted on the modelhub?

**Comment by patrickvonplaten** [comment]
This is probably because of this PR: https://github.com/huggingface/transformers/pull/5773 , but should not pose a real problem.

**Comment by vgaraujov** [comment]
@LysandreJik I used model hub checkpoints. I runned the following lines with pytorch:

`from transformers import AlbertForPreTraining`
`model = AlbertForPreTraining.from_pretrained('albert-base-v2')`

**Comment by patrickvonplaten** [comment]
Hey @vgaraujov, I can reproduce - this PR: #6700 should fix it. Thanks for reporting it :-)

**Comment by vgaraujov** [comment]
@patrickvonplaten Thank you for your help! 💯

**Comment by ruotianluo** [comment]
Position_ids seems unnecessary to be saved? Why not use register_buffer with persistent==False

**Comment by stas00** [comment]
It won't work. Details are here: https://github.com/huggingface/transformers/issues/7229#issuecomment-695980184
