### ISSUE TITLE
longformer padding logging

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/transformers#6712]
# 🚀 Feature request

The longformer model logs the extra padding length that it adds (when the padding length is bigger than zero). Can you please add a verbose or non-verbose option to control this behavior? It basically creates a log every forward pass. 
the code is in: 
module - transformers/modeling_longformer.py 
function - _pad_to_window_size
line - 555

Thank you so much !

**Comment by LysandreJik** [comment]
Hi! This should be manageable with the logger:

```py
import transformers
import logging

logger = logging.getLogger("transformers")
logger.setLevel(logging.ERROR)
```

**Comment by yuvalkirstain** [comment]
thank you so much for the response. I just think that this information should be in debug rather than info.

**Comment by yuvalkirstain** [comment]
thank you! sounds great. However, I do think that you can perhaps just notify this behavior at the start of training rather than logging every step.
