### ISSUE TITLE
Resuming training from a checkpoint on Windows does not resume at the correct global_step

### ISSUE THREAD

**Issue by jncasey** [huggingface/transformers#6720]
### Who can help
Trainer: @sgugger

## Information

I've noticed that resuming training from a checkpoint on Windows fails to start at the right global step (though learning rate, loss, etc continue from where the training left off). The same doesn't happen under macOS.

## Solution?

I think the issue is in Trainer.train, specifically this line:
`self.global_step = int(model_path.split("-")[-1].split("/")[0])`

And it seems to work as expected by swapping `"/"` with `os.sep`

**Comment by jncasey** [comment]
I'm embarrassed to say I'm not super familiar with git or open source collaboration in general, so even though it seems super trivial, I'm worried I'll mess something up.

**Comment by sgugger** [comment]
I can fix this but it'll be next week as I'm off tonight and tying a few other loose ends.

**Comment by jncasey** [comment]
Thank you! I'm in no personal rush – I got my aborted training to resume. I just wanted someone on the project to know about the problem/solution I found.
