### ISSUE TITLE
How to use the reformer for question answering?

### ISSUE THREAD

**Issue by Krak91** [huggingface/transformers#6738]
In the code example in the documentation the tokenizer gets passed just a single string. Doesn't it need a context and a question? Also, how exactly to get the answer?

**Comment by patrickvonplaten** [comment]
Hey @Krak91,

Thanks for this issue. The PR attached to this issue should fix it. 
Note that even though the new example code will work for Reformer, it won't yield any good results because there is no pretrained ReformerModel yet.
