### ISSUE TITLE
Why does examples/seq2seq/finetune.py only use sortish sampler for train? 

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#6783]
Would it make eval faster?
Would it make validation sanity check obnoxiously slow?
This should be a ~1 line PR with a longer PR description.

**Comment by Pradhy729** [comment]
@sshleifer I can help out here. What exactly are you looking for?

**Comment by sshleifer** [comment]
I'll take care of it actually, sorry!

**Comment by sshleifer** [comment]
Fixed, using sortish sampler for val. Much faster!
