### ISSUE TITLE
How to fine-tune T5 with some additional special tokens ?

### ISSUE THREAD

**Issue by xdqkid** [huggingface/transformers#6789]
I wanna to fine-tune T5 with seq2seq task, but there are some special tokens in this seq2seq task. T5 performs bad without these tokens.  How could I use some additional special tokens to fine-tune T5 with scripts https://github.com/huggingface/transformers/blob/master/examples/seq2seq/finetune_t5.sh?

**Comment by vishal-burman** [comment]
Let's say the tokens you want to add are <some_token_1> and <some_token_2> (including angle brackets)
```
from transformers import T5Tokenizer
tokenizer = T5Tokenizer.from_pretrained("t5-base")
tokenizer.add_tokens(['<some_token_1>', '<some_token_2'>])
```

**Comment by MHDBST** [comment]
I want to add this line in addition to modifying the tokenizer for the model to work with the new tokenizer:

`model.resize_token_embeddings(len(tokenizer))`

**Comment by KeertiPremGadde** [comment]
I am working with **google/long-t5-tglobal-large** and need to add special tokens to the tokenizer vocabulary.

The tokenizer vocabulary size is **32,100**, which will become **32,103** after adding 3 additional tokens.

However, the embedding matrix size is **[32,128, 1024]**, which includes 28 buffer tokens (unused slots in the embedding matrix).

If I use `model.resize_token_embeddings(len(tokenizer))`, in my case, the embedding matrix size will shrink to **32,103**, potentially causing distortion in the embeddings, learned weights and adjusting lm_head weights tying. I have already tried this, and the model does not produce optimal results.

My Questions:
1. **Did the model give good results in your case after using `model.resize_token_embeddings(len(tokenizer))`?**
   - Specifically, did the resizing affect the model's performance?

2. **Is it possible to use the buffer tokens (28) in the embedding matrix to accommodate the 3 additional special tokens without disturbing the model's embeddings and learned weights?**
   - Or do I need to expand the embedding matrix size to **32,128 + 3 = 32,131** for the new special tokens? I am concerned this might again disturb the embedding matrix, adjusting lm_head weights tying and lead to suboptimal performance.

Thank you for your guidance!

**Comment by karunaahuja** [comment]
@KeertiPremGadde -- could you ever figure out a solution to this?

**Comment by KeertiPremGadde** [comment]
@karunaahuja, I experimented with adding special tokens to google/long-t5-tglobal-large, but the fine-tuning results were suboptimal. Resizing the embedding matrix appears to have disrupted the pretrained representation space, leading to degraded performance compared to runs without the additional tokens.

> [@KeertiPremGadde](https://github.com/KeertiPremGadde) -- could you ever figure out a solution to this?
