### ISSUE TITLE
AttributeError: 'MarianTokenizer' object has no attribute 'prepare_translation_batch'

### ISSUE THREAD

**Issue by sdhzlxm** [huggingface/transformers#6796]
Problem 1:
When I load tokenizer from local directory.  And use it according MarianMT tutorial. There will be an error occurs. 
AttributeError: 'MarianTokenizer' object has no attribute 'prepare_translation_batch'

Problem 2:
When I downloads models and tokenizers from the web, such as running 'tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-zh-en")'. There will be some errors.
RuntimeError: Internal: /sentencepiece/src/sentencepiece_processor.cc(818) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by sshleifer** [comment]
Which tutorial? its called `prepare_seq2seq_batch` now.

**Comment by sdhzlxm** [comment]
> prepare_seq2seq_batch

I follow this tutorial, https://huggingface.co/transformers/model_doc/marian.html

Where can I find the new user manual for MarianMT model? Thank you.

**Comment by sshleifer** [comment]
https://huggingface.co/transformers/master/model_doc/marian.html

**Comment by jacampo** [comment]
Have they change it again and add a maximum length?

**Comment by stelmath** [comment]
I am getting: `AttributeError: 'MarianTokenizer' object has no attribute 'prepare_seq2seq_batch'`

I changed it to `prepare_translation_batch` and it works

**Comment by MinionAttack** [comment]
It fails again... and changing to `prepare_seq2seq_batch` throws the deprecation warning...
