### ISSUE TITLE
Unable to establish Lock on cached tokenizer output from RobertaTokenizer

### ISSUE THREAD

**Issue by aalok-sathe** [huggingface/transformers#6819]
## Environment info

     
- `transformers` version: 3.0.2
- Platform: Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-redhat-7.8-Maipo
- Python version: 3.7.5
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): 2.3.0 (True)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help

 
 tokenizers: @mfuntowicz 

## Information

Model I am using (Bert, XLNet ...): Roberta (`roberta-large-mnli`)

The problem arises when using:
* [X] the official example scripts: `run_glue.py`
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: MNLI
* [ ] my own task or dataset: (give details below)

## To reproduce

1. download GLUE data using official download script and place it in the root of `transformers`
2. `python run_glue.py --model_name_or_path roberta-large-mnli --data_dir ../glue_data --output_dir tmp --task_name MNLI --do_eval

```bash
Traceback (most recent call last):
  File "./run_glue.py", line 247, in <module>
    main()
  File "./run_glue.py", line 143, in main
    if training_args.do_eval
  File "/home/USER/anaconda3/envs/nlu/lib/python3.7/site-packages/transformers/data/datasets/glue.py", line 106, in __init__
    with FileLock(lock_path):
  File "/home/USER/anaconda3/envs/nlu/lib/python3.7/site-packages/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/USER/anaconda3/envs/nlu/lib/python3.7/site-packages/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/USER/anaconda3/envs/nlu/lib/python3.7/site-packages/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '../glue_data/cached_dev_RobertaTokenizer_128_mnli.lock'
```

## Expected behavior

The script should be able to create the above-mentioned cached file if one doesn't exist, and acquire lock and load it if it does.

**Comment by aalok-sathe** [comment]
The issue was with the file structur: using the downloaded glue data in the filesystem.

**Comment by MathewAlexander** [comment]
Could you please explain how you resolved it ?. I am having the same problem with XLNET for glue(STS-B)

**Comment by aalok-sathe** [comment]
I had the data placed in the wrong location, and I was giving the incorrect path.
