### ISSUE TITLE
regarding the max token length of longformer

### ISSUE THREAD

**Issue by rkoystart** [huggingface/transformers#6828]
In the encode_plus function  of the Tokenizer , there is a argument called max_length whose default value is 4096.
So is it possible to increase the max token length  beyond 4096 or the maximum value of max_length argument is 4096
Can anyone clear my doubt

Thanks in advance !!!!

**Comment by patil-suraj** [comment]
Hi, @rkoystart 
I think this notebook will [help](https://github.com/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb)

**Comment by rkoystart** [comment]
@patil-suraj  so it means by default  the longformers model provided by huggingface supports maximum tokens of 4096 right ?
if suppose we want to pretrained model to support for even more longer sentences than 4096 we have to follow the instructions in the notebook you have mentioned above
