### ISSUE TITLE
RAM MemoryError

### ISSUE THREAD

**Issue by shizhediao** [huggingface/transformers#6836]
# ❓ Questions & Help

I was wondering is the RAM MemoryError issue solved?
I encountered this issue because my 128 GB RAM memory could not load all 48 GB data.
There are some discussions before, such as #6636, #3388, #1290, #4009 
However, I don't see there is lazyDataLoader right now.
Could you provide any hints about how to deal with a large dataset?
Thanks!

**Comment by ttzHome** [comment]
Do you solve the problem?......
