### ISSUE TITLE
tokenization_gpt2 save vocabulary is not saving special tokens

### ISSUE THREAD

**Issue by MHDBST** [huggingface/transformers#6837]
## Environment info

     
- `transformers` version: 2.8.0
- Platform:  linux
- Python version: 3.6.10
- PyTorch version (GPU?): GPU
- Tensorflow version (GPU?): -
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

## Information

Model I am using (Bert, XLNet ...):
GPT2

The problem arises when using:
 the official example scripts: (give details below)

The tasks I am working on is:

my own task or dataset: (give details below)

## To reproduce

1. Load a pre-trained tokenizer
2. Add your intended special tokens: `tokenizer.add_tokens(SPECIAL_TOKENS_LIST)`
3. Save your tokenizer's vocabulary with: `tokenizer.save_vocabulary(PATH)`

## Expected behavior
With the current `save_vocabulary` function, we are just saving the predefined tokens:

`with open(vocab_file, "w", encoding="utf-8") as f:
   f.write(json.dumps(self.encoder, ensure_ascii=False))`

This line should be modified as follow to save the special tokens as well:

`vocab_with_special_tokens = dict(self.encoder, **self.added_tokens_encoder)
with open(vocab_file, "w", encoding="utf-8") as f:
            f.write(json.dumps(vocab_with_special_tokens, ensure_ascii=False))`

**Comment by LysandreJik** [comment]
Hi! The `save_vocabulary` method, as its name implies and as is explained in its [docstring](https://huggingface.co/transformers/main_classes/tokenizer.html#transformers.PreTrainedTokenizer.save_vocabulary), only saves the vocabulary. If you want to save the entire tokenizer (with special tokens), you should use the `save_pretrained` method.
