### ISSUE TITLE
pegasus-large: Can we have input text descriptions more than the maximum input length of 512?

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#6839]
As mentioned pegasus paper, authors used sinusoidal positional encoding to make sure the model can work with inputs longer than default 512? 

So with huggingface implementation can we use inputs with longer lengths?

**Comment by patil-suraj** [comment]
Yes ! https://discuss.huggingface.co/t/pegasus-questions/838/8?u=valhalla

**Comment by shamanez** [comment]
Thanks
