### ISSUE TITLE
Can DistilBert.forward() support token_type_ids ?

### ISSUE THREAD

**Issue by Yusifu** [huggingface/transformers#6900]
I am using DistilBert to distill a pretrained Bert model. That is Bert -> DistilBert.
The input of Bert is a sentence pair: [CLS] Hello word [SEP] Hello Python [SEP].
But DistilBert dose not support sentence pair inputs.
Can DistilBert support sentence pair-like inputs?

**Comment by LysandreJik** [comment]
DistilBERT can support sentence pair-like inputs but does not make use of token type IDs. It detects sentence pairs according to the special tokens. cc @VictorSanh

**Comment by githubrandomuser2017** [comment]
@Yusifu Did you find a solution for this problem? I'm also doing sentence-pair classification (NLI) with Distilbert.
