### ISSUE TITLE
Example config code uses invalid 'output_attention' rather than 'output_attentions'

### ISSUE THREAD

**Issue by lannelin** [huggingface/transformers#6902]
Looks like documentation only bug. `output_attention` used rather than `output_attentions`.

Occurs in multiple places in repo.

Maybe linked to #2985 

## Environment info

- `transformers` version: 3.1.0
- Platform: Darwin-19.6.0-x86_64-i386-64bit
- Python version: 3.7.4
- PyTorch version (GPU?): 1.5.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
 documentation: @sgugger 

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

From docs L4-L5 of AutoConfig example: 
[docs](https://huggingface.co/transformers/model_doc/auto.html#transformers.AutoConfig)
or 
[code](https://github.com/huggingface/transformers/blob/master/src/transformers/configuration_auto.py#L264)

```python
config = AutoConfig.from_pretrained('bert-base-uncased', output_attention=True, foo=False)
assert config.output_attention == True
```

causes:

```
AttributeError: 'BertConfig' object has no attribute 'output_attention'
```

## Expected behavior

The assertion given in documentation passes.

**Comment by sgugger** [comment]
Thanks for reporting! The PR mentioned above should fix all of those.
