### ISSUE TITLE
Small bug on website

### ISSUE THREAD

**Issue by tanmaypandey7** [huggingface/transformers#6913]
Hi, I am not sure if this is the correct place to report this but all the web pages of https://huggingface.co/transformers/master/index.html are having some issues with scrolling. Scrolling the main text (right side) also scrolls the table of contents(left part)

**Comment by LysandreJik** [comment]
Hi! Yes, this isn't an issue, this is the intended behavior. It's the standard behavior with Sphinx/ReadTheDocs. You can see a similar example with the [PyTorch docs](https://pytorch.org/docs/stable/tensors.html).
