### ISSUE TITLE
T5 Tokenizer fails to decode correctly and prints ⁇

### ISSUE THREAD

**Issue by misrasaurabh1** [huggingface/transformers#6917]
T5 Tokenizer tokenizes this following sequence to 
```
>>> from transformers import T5Tokenizer
>>> tokenizer = T5Tokenizer.from_pretrained("t5-base")
>>> print(tokenizer.tokenize("My phone number is  1-${phone.number}"))
['▁My', '▁phone', '▁number', '▁is', '▁1-', '$', '{', 'phone', '.', 'num', 'ber', '}']
```
So far so good but when we decode the above sequence back, we get weird ⁇ symbols.

```
>>> print(tokenizer.decode(tokenizer.encode("My phone number is  1-${phone.number}")))
My phone number is 1-$ ⁇ phone.number ⁇ 
```

This along with the bug https://github.com/huggingface/transformers/issues/6150 shows that T5 Tokenizer
- Is not cycle consistent
- Ignores multiple whitespaces
##  Environment info

     
- `transformers` version: 3.0.2                                                                                                                                                            
- Platform: Linux-4.9.0-12-amd64-x86_64-with-Ubuntu-18.04-bionic                                                                                                                           
- Python version: 3.6.9                                                                                                                                                                    
- PyTorch version (GPU?): 1.5.1+cpu (False)                                                                                                                                                
- Tensorflow version (GPU?): not installed (NA)                                                                                                                                            
- Using GPU in script?: no                                                                                                                                                     
- Using distributed or parallel set-up in script?: no 
### Who can help

T5: @patrickvonplaten
## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

Shown above

## Expected behavior

A cycle consistent T5 Tokenizer that works on a variety of inputs

**Comment by patrickvonplaten** [comment]
@mfuntowicz - Since T5 relies on google's sentencepiece tokenizer for now, can we do anything against it before our own sentencepiece tokenizer is implemented?

**Comment by misrasaurabh1** [comment]
Verified that this is a problem with the original T5 sentencepience tokenizer. Opened an issue with the Google's T5 repository. https://github.com/google-research/text-to-text-transfer-transformer/issues/390

**Comment by misrasaurabh1** [comment]
Closing this issue , quoting from T5 github issue
> > { is OOV because we intentionally removed any pages with { or } from C4 to avoid pre-training on anything other than natural language. So, it gets encoded to ??. SentencePiece has a byte fallback feature but it was not available when we trained our sentencepiece model.
