### ISSUE TITLE
inference over onnx output

### ISSUE THREAD

**Issue by MohitTare** [huggingface/transformers#6922]
# ❓ inference over onnx output

## Details
How to do decoding on the output obtained from onnx inference

I am trying to use onnx runtime for inferring on CPU by following the https://github.com/huggingface/transformers/blob/d822ab636b6a14ed50f7bca0797c1de42c19de61/notebooks/04-onnx-export.ipynb

I have a Marian MT hindi to english fine tuned [model ](https://huggingface.co/Helsinki-NLP/opus-mt-hi-en)which i have managed to convert using conver_graph_to_onnx.py script.
On calling `sequence, pooled = cpu_model.run(None, inputs_onnx)` 

I guess the pooled is the encoder output, and sequence is the final decoder output. Please correct if wrong

How can i use the api to get the final tokens (by greedy/beamsearch). For the normal way, we call the `generate` function. Is there any helper function to get the final decoded output form onnx output. Any other guidelines ?

Thanks!

**Comment by Green-li** [comment]
I have the same issue too! Please some guidelines ?

**Comment by typercast** [comment]
Same
