### ISSUE TITLE
non-interactive transformers-cli upload?

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#6934]
# 🚀 Feature request

Currently, `transformers-cli upload` works only interactively due to its prompt:
`Proceed? [Y/n]`

After running the updated model conversion, I would like to be able to do:
```
cd data
transformers-cli upload fsmt-wmt19-ru-en
transformers-cli upload fsmt-wmt19-en-ru
transformers-cli upload fsmt-wmt19-de-en
transformers-cli upload fsmt-wmt19-en-de
cd -
```
But this won't work:

Would it be possible to add a `-y` override?

Alternatively, would it be possible to give it all dirs to upload in one command?
```
transformers-cli upload fsmt-wmt19-ru-en fsmt-wmt19-en-ru fsmt-wmt19-de-en fsmt-wmt19-en-de
```

## Motivation

I have been re-uploading 4 x 1.1GB models on a relatively slow connection, and I have to be around to hit Y for each one of them, which is very counter-productive, as I have to go back and re-check whether each upload has been completed. I can probably code some shell expect script to feed it automatically, but this defeats the purpose.

Thank you!

**Comment by stas00** [comment]
FWIW, I found a workaround (god bless Stackoverflow):

```
cd data
yes Y | transformers-cli upload fsmt-wmt19-ru-en
yes Y | transformers-cli upload fsmt-wmt19-en-ru
yes Y | transformers-cli upload fsmt-wmt19-de-en
yes Y | transformers-cli upload fsmt-wmt19-en-de
cd -
```

**Comment by julien-c** [comment]
Ah, nice find :)

I think a `-y` flag would be reasonable if you want to open a PR

**Comment by stas00** [comment]
Will do. Thank you.

**Comment by stas00** [comment]
Done: https://github.com/huggingface/transformers/pull/7035
