### ISSUE TITLE
Load BERT+GPT2 in EncoderDecoder

### ISSUE THREAD

**Issue by AmbiTyga** [huggingface/transformers#6936]
# ❓ Questions & Help

## Details
I am working on modelling an EncoderDecoderModel using weights of BERT and GPT2, after going through lots of repo and issues I found that currently its not possible, but I found a model card that has used this model of BERT+GPT2 on dataset cnn-dailymail [here](https://huggingface.co/patrickvonplaten/bert2gpt2-cnn_dailymail-fp16). I would like to know in which version of transformers is that possible and one thing more that there was an attribute passed in `TrainingArguments` module, that was `predict_from_generate`, I can't find that in `transformers`: 3.1.0, 3.0.2, 2.11.0, please clear me in which version does these parameters constitute.

@patrickvonplaten Please answer my query

**Comment by patil-suraj** [comment]
Hi @AmbiTyga ,
Bert2GPT2 is available in the latest release, however `predict_from_generate` from generate is not yet added in `Trainer`. 
You can set `predict_from_generate` to `False`  and `comput_metrics` to `None` if you done't need generative metrics (ROUGE etc) at training time. 

If you want to use `predict_from_generate` from generate then you'll need to install transformers from this fork.
https://github.com/huggingface/transformers/tree/more_general_trainer_metric
