### ISSUE TITLE
Training script for other language (except English)

### ISSUE THREAD

**Issue by Tortoise17** [huggingface/transformers#6947]
Dear Friends. I have found this very nice and great. 
I would like to ask, is there any script which can be used to train other language model?
and how much minimum GPU power is required for such training?

If you can guide . ! I am thinking to test for German language.

**Comment by julien-c** [comment]
You could try either https://huggingface.co/blog/how-to-train or https://discuss.huggingface.co

^^ Forum is better for open-ended questions like those ones.
