### ISSUE TITLE
Mobile Bert Tiny model

### ISSUE THREAD

**Issue by borsork377** [huggingface/transformers#6992]
# 🚀 Feature request

Can you add support for variants of MobileBERT?

## Motivation

The package currently provides various varients of bert - 'bert-base-cased', 'bert-base-uncased', 'bert-large'...
Can you also similarly provide Mobile Bert Tiny as well?

**Comment by LysandreJik** [comment]
MobileBERT is supported, see [here](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_mobilebert.py) for the code, and [here](https://huggingface.co/transformers/model_doc/mobilebert.html) for the docs. [Here](https://huggingface.co/models?search=mobilebert) are all the available mobilebert models on the hub.
