### ISSUE TITLE
How to bypass "Special tokens have been added in the vocabulary..." warning?

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#7002]
Is there a way to avoid always getting:

> Special tokens have been added in the vocabulary, make sure the associated word embedding are fine-tuned or trained

@ https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils_base.py#L1614

(other than turning logging off)

As far as I can see from stepping through that code, there are always special tokens (e.g. eos, pad, etc.), i.e. there is nothing special about it. What purpose does this warning serve when loading a tokenizer? 

I'm not sure how the end user can act on the suggestion:

> make sure the associated word embedding are fine-tuned or trained

when they just want to run, say, the `generate` function on a pre-trained model, other than just learning to ignore this warning and not paying heed to when a warning is really saying something crucial.

Thoughts?

**Comment by stas00** [comment]
You're absolutely correct, the tokenizer was adding special tokens (copied from another tokenizer, but wasn't really needing them), so I removed them now and the warning is gone.

And, yes, I forgot to add the code - wasn't my best!

Much appreciating your follow up, @nassim-yagoub

**Comment by sbocconi** [comment]
The same warning also happens with this code:
```
import torch
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('vinai/bertweet-base')
model = AutoModel.from_pretrained('vinai/bertweet-base')
```
```
python --version
Python 3.9.13
```
I do not understand where tokens are added to the vocabulary after loading the tokenizer.

**Comment by sbocconi** [comment]
No unfortunately @codepujan, it has been a while I have not used this functionality

**Comment by rbehzadan** [comment]
This worked for me:

transformers.logging.set_verbosity_error()

**Comment by snova-rodrigom** [comment]
@rbehzadan's comment worked!

**Comment by thistlillo** [comment]
+1 I always get this warning and cannot understand what I am supposed to do.

**Comment by amyeroberts** [comment]
cc @ArthurZucker Maybe we can downgrade this warning level?

**Comment by ArthurZucker** [comment]
yeah I don't think it help anyone.
