### ISSUE TITLE
max_length does not seem to work

### ISSUE THREAD

**Issue by MarijnQ** [huggingface/transformers#7045]
So I may have understood the definition wrong, but in my understanding max_length defines the amount of characters you want your summary to be. i.e. max_length=50, the summary is not over 50 characters.

I have installed the transformers, work with the summarizer pipeline, which I assume is the bartsummarizer.
I try to summarize the standard text from the tutorial about the woman who married a lotta guys.
I fill in the following string:
`summarizer = pipeline('summarization')
summarizer(TEXT_TO_SUMMARIZE, min_length=50, max_length=100)`

The summary is this
` Liana Barrientos pleaded not guilty to two counts of "offering a false instrument for filing in the first degree" She has been married to 10 men, nine of them between 1999 and 2002 . At one time, she was married to eight men at once, prosecutors say .`
Which is 249 characters and has weird errors with the . being placed after a space.

It is probably a rookie question, but I can't seem to figure it out.

ps. I run it on Google Colab, if that makes a difference

**Comment by patrickvonplaten** [comment]
Hey @MarijnQ,

`max_length` defines the number of maximum output *tokens* (which is usually a bit less than number of words). You can get the number of tokens of a text by doing:

```python 
from transformers import T5Tokenizer

tokenizer = T5Tokenizer.from_pretrained("t5-base")
input_ids = tokenizer('Liana Barrientos pleaded not guilty to two counts of "offering a false instrument for filing in the first degree" She has been married to 10 men, nine of them between 1999 and 2002 . At one time, she was married to eight men at once, prosecutors say .')

print(f"Num tokens {len(input_ids.input_ids)}")  
```
