### ISSUE TITLE
How to pass tokenized hypotheses to TFRobertaForSequenceClassification model directly for faster inference?

### ISSUE THREAD

**Issue by akshatapatel** [huggingface/transformers#7051]
Hi, 
I have been running the zero shot classification pipeline for my use case by passing each text and it’s corresponding list of hypotheses labels, however it takes around 3 hours on a 32B GPU to classify ~22000 sentences(each sentence can have a varying number of labels ranging from 70 to 140 labels).

Is there a way to reduce the computation time by passing the embeddings to the sequence classification model directly rather than the raw list of labels?

**Comment by jplu** [comment]
Hello @akshatapatel!

Pinging @joeddav as he is the person who takes care of the zero-shot classification in the lib.

Can you share with us a piece of code on how you are trying to do you sequence classification?

**Comment by joeddav** [comment]
Discussed [on the forums](https://discuss.huggingface.co/t/new-pipeline-for-zero-shot-text-classification/681/30?u=joeddav). Other discussions on speeding up zero shot classification [here](https://discuss.huggingface.co/t/speeding-up-zero-shot-classification-solved/692) and [here](https://discuss.huggingface.co/t/way-to-make-inference-zero-shot-pipeline-faster/1384)
