### ISSUE TITLE
circleci testing issue

### ISSUE THREAD

**Issue by chiapas** [huggingface/transformers#7062]
Sorry, this is not a bug report about `transformers` library. But I don't know what's the best place to ask.

While working on a pull request #6998 , after pushing the code, I got

        ==================================== ERRORS ====================================
        ____________________ ERROR collecting tests/test_trainer.py ____________________
	ImportError while importing test module '/home/circleci/transformers/tests/test_trainer.py'.
	Hint: make sure your test modules/packages have valid Python names.
	Traceback:
	/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
	    return _bootstrap._gcd_import(name[level:], package, level)
	tests/test_trainer.py:3: in <module>
	    import nlp
	E   ModuleNotFoundError: No module named 'nlp'

The PR #6998  has already been tested several times without problem. And it seems that the error `No module named 'nlp'` is not on my side. Could you help me to resolve this?

**Comment by sgugger** [comment]
This has been fixed in master already, it's due to the change of name of the nlp library to datasets. You will need to install datasets to have the full test suite working.

**Comment by chiapas** [comment]
Thanks, @sgugger . So in order to make my pull request pass the test online, I have to merge remote master intomy local branch and repush? Is this an acceptable approach of doing PR?

**Comment by sgugger** [comment]
You can either rebase master on your PR branch, or not worry if this is the only test not passing (merging will make the CI green).
