### ISSUE TITLE
Clean up `benchmark_args_utils.py` "no_..." arguments

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#7072]
# 🚀 Feature request

Currently we have a mixture of negative and positive formulated arguments, *e.g.* `no_cuda` and `training` here: https://github.com/huggingface/transformers/blob/0054a48cdd64e7309184a64b399ab2c58d75d4e5/src/transformers/benchmark/benchmark_args_utils.py#L61. 

We should change all arguments to be positively formulated, *e.g. from `no_cuda` to `cuda`. These arguments should then change their default value from `False` to `True`.

Also the help text should be updated to something that is better formulated: "Don't ...." as a help text is not very easy to understand.

The motivation is clear: It's better to be consistent in a library and have the code as easy and intuitive to understand.

## Your contribution

This is a "good first issue", so I'm happy to help anybody who wants to take a shot at this :-)

**Comment by fmcurti** [comment]
Hmm I seem to have forgotten to change the references in the tests
