### ISSUE TITLE
How to implement LayoutLM for information extraction

### ISSUE THREAD

**Issue by SandyRSK** [huggingface/transformers#7084]
Hi,
I am new to nlp
Can someone please guide me on How to implement the layoutLM using transformers for information extraction (from images like receipt)

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("microsoft/layoutlm-large-uncased")
model = AutoModel.from_pretrained("microsoft/layoutlm-large-uncased")

**Comment by julien-c** [comment]
I think the model's integration is still a work-in-progress @SandyRSK, but will let model author @liminghao1630 chime in if necessary

**Comment by nishchay47b** [comment]
Similar help required. I want to use the layoutLM model finetuned on DocBank data. As per my understanding, this will be a token classification task, but any example code will be extremely helpful.
Thanks

**Comment by wolfshow** [comment]
@SandyRSK the integration is still on-going. You may refer to https://github.com/microsoft/unilm/tree/master/layoutlm if you want to use the model right now.

**Comment by juvebogdan** [comment]
Is this still work-in-progress?

**Comment by louisabraham** [comment]
Hi, is it possible to load the docbank pretrained model in your implementation?

**Comment by LysandreJik** [comment]
It should be possible to load the LayoutLM weights from the official repository to ours. Please feel free to try and upload it on the hub! 

Let us know if you run into trouble by opening a new issue and we'll take a look.

**Comment by louisabraham** [comment]
Thanks! I'm just worried about the changes you made (all the classes commented with `Copied from transformers.models.bert.modeling_bert.BertEncoder with Bert->LayoutLM`): https://huggingface.co/transformers/_modules/transformers/models/layoutlm/modeling_layoutlm.html

**Comment by LysandreJik** [comment]
Right, this is for maintainability purposes. Instead of refactoring models in shared layers, we instead keep the entire forward pass in a single file. These comments allow us to ensure that the files do not diverge: we have tests that check that the contents of `LayoutEncoder` is identical to `BertEncoder`, with the only change being utterances of "bert" changed to "layoutlm".

As you can see, the differences between BERT and LayoutLM are especially the embeddings.

**Comment by gbecigneul** [comment]
Hi, I loaded the pretained DocBank model, which is a LayoutLM from the original unilm repository, using the LayoutLM from HuggingFace. 

I get a warning of the form:

```
Some weights of the model checkpoint at layoutlm_large_500k_epoch_1/ were not used when initializing LayoutLMForTokenClassification: ['bert.embeddings.word_embeddings.weight' [...]
- This IS expected if you are initializing LayoutLMForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LayoutLMForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LayoutLMForTokenClassification were not initialized from the model checkpoint at layoutlm_large_500k_epoch_1/ and are newly initialized: ['embeddings.word_embeddings.weight' [...]
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

For the full warning see https://paste.ofcode.org/WxFiUf8bYL3TEjc9jLAG4J

Would you say the model was properly loaded? 
(Model outputs indeed seem to make sense.)
