### ISSUE TITLE
Distilbart's summaries start with an empty space?

### ISSUE THREAD

**Issue by songwanguw** [huggingface/transformers#7085]
## Environment info

     
- `transformers` version: 2.11.0
- Platform: linux
- Python version: 3.7
- PyTorch version (GPU?): 1.51, gpu
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help

 

 @sshleifer 

```
from transformers import BartTokenizer, BartForConditionalGeneration, BartConfig
model = BartForConditionalGeneration.from_pretrained('sshleifer/distilbart-xsum-12-3')
tokenizer = BartTokenizer.from_pretrained('sshleifer/distilbart-xsum-12-3')
ARTICLE_TO_SUMMARIZE = "\"The accident meant the motorway was closed, making travel to Mourneview Park impossible for the team and fans travelling from Belfast, \" said the Irish Football Association . A new date for the match has yet to be confirmed by Uefa . Northern Ireland have three points from their first two Group Six qualifiers."
inputs = tokenizer.batch_encode_plus([ARTICLE_TO_SUMMARIZE], max_length=512, return_tensors='pt')
summary_ids = model.generate(inputs['input_ids'], num_beams=5, max_length=62, min_length=10, early_stopping=True)
print([tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=True) for g in summary_ids])
```
[" The Republic of Ireland's Euro 2016 qualifier against Northern Ireland has been postponed because of a motorway crash."]

facebook/large-bart-xsum will give a correct summary. Why this summary starts with an empty space? What shall we pay attention to these inconsitency

**Comment by songwanguw** [comment]
I think i figure it out now. in BART, " The", " Republic" are individual words.

**Comment by jinkoay** [comment]
I'm having a similar issue as @songwanguw where each line of my output summaries start with a blank space when using Distilbart. This does not happen when I use facebook/bart-large-cnn.

**Comment by sshleifer** [comment]
Unfortunately, I don't know any way to fix this besides postprocessing or retraining.
You're using the model correctly. I probably trained on targets with an extra prefixed space. My bad!
