### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'gradient_checkpointing'

### ISSUE THREAD

**Issue by xixiaoyao** [huggingface/transformers#7090]
## Environment info

     
- `transformers` version: 3.1.0
- Platform: Linux-3.10.0_3-0-0-17-x86_64-with-debian-buster-sid
- Python version: 3.7.7
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help
 
 Longformer/Reformer: @patrickvonplaten

 -->

## Information

Model I am using (Longformer):

The problem arises when using:
[ * ] the official example scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: SQuAD v1.1

## To reproduce

1. add gradient_checkpointing argument for AutoModelForQuestionAnswering in examples/question-answering/run_squad.py
2. run with longformer-base-4096

runtime errors as belows
```
File "run_squad.py", line 821, in <module>
    main()
  File "run_squad.py", line 739, in main
    gradient_checkpointing=True,
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 852, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'gradient_checkpointing'
```

even if you explicitly replace AutoModel with LongformerModel like following, error is the same.

![image](https://user-images.githubusercontent.com/24541791/92999722-d1da6e80-f555-11ea-9588-2269fcacee90.png)

When I run with python/ipython interactive mode, the model loaded success.

![image](https://user-images.githubusercontent.com/24541791/92999756-0e0dcf00-f556-11ea-8845-8a661dab1e08.png)

And I have ensured the python enviroment is the same during these two runs.

## Expected behavior

Longformer can be loaded with gradient checkpointing

**Comment by patrickvonplaten** [comment]
Hey @xixiaoyao,

Sorry I cannot reproduce the error. Both when running `run_squad.py` and this snippet (which is essentially the same as in `run_squad.py`):

```python
from transformers import AutoModelForQuestionAnswering
model = AutoModelForQuestionAnswering.from_pretrained("allenai/longformer-base-4096", gradient_checkpointing=True)
```

I do not get any error.
