### ISSUE TITLE
Longformer inference time

### ISSUE THREAD

**Issue by cmdllx** [huggingface/transformers#7102]
The longformer-base-4096 model should be faster than bert-base-cased ,However I find that the former one takes more time to inference

**Comment by patil-suraj** [comment]
hi @cmdllx , I don't think longformer will  be necessarily faster than bert-base-cased. The goal of longformer is to make memory complexity of attention layer liner w.r.t to seq length instead of quadratic, so it saves memory, not compute. More the seq-length , more will be inference time.
