### ISSUE TITLE
Generate coherent text with T5

### ISSUE THREAD

**Issue by parthplc** [huggingface/transformers#7113]
Can we use T5 to generate coherent text given an input line like in case of GPT-2? If yes how do we fine-tune T5 for such a task?

**Comment by jsrozner** [comment]
@parthplc Did you find an answer to this question?

**Comment by parthplc** [comment]
@jsrozner yeah, I was able to finetune t5 for text generation.

**Comment by jsrozner** [comment]
> @jsrozner yeah, I was able to finetune t5 for text generation.

Is your work publicly visible anywhere? (colab or a repository) I was looking for some examples to adapt to my use case. Although I got a helpful response here: https://discuss.huggingface.co/t/t5-for-conditional-generation-getting-started/1284/2

**Comment by parthplc** [comment]
I used the same @jsrozner

**Comment by krrishdholakia** [comment]
can someone share a nb of using finetune.py + t5, would love to see some examples for reference.

**Comment by jsrozner** [comment]
Check out 
https://discuss.huggingface.co/t/t5-seq2seq-custom-fine-tuning/1497/6 (details on tweaking your vocab if you need it)

The link above (https://discuss.huggingface.co/t/t5-for-conditional-generation-getting-started/1284) has links to other useful T5 posts on huggingface.

And I am looking for answers to this post for some other tips and tricks: 
https://discuss.huggingface.co/t/t5-tips-for-finetuning-on-crossword-clues-clue-answer/1514

To actually run, you should do this (called "installing from source):
- clone transformers
- create new conda or other env
- pip install -e .
- cd examples && pip install -r requirements.txt
- cd seq2seq
- ./finetune_t5_bart_tiny.sh (or whatever the name is) -- will run two test epochs

After that it's just a matter of choosing the model, tokenizer, setting up your data, and then tweaking params. Most of that is in the posts I linked!
