### ISSUE TITLE
Feature request: State the goals and none goals of the library in the README

### ISSUE THREAD

**Issue by talolard** [huggingface/transformers#7117]
# 🚀 Feature request

I'd like the library's README to say what it's goals and none goals are.
For example, as a (new) user I really like [Typescripts non-goals](https://github.com/microsoft/TypeScript/wiki/TypeScript-Design-Goals) because it made it clear what to expect from Typescript and thus how to best use it. I'd like the same for transformers. 

## Motivation

As a new user  I look at the README and think this library can and wants to do everything that I do.

But I think it has a tighter more well defined (implicit) scope and that peripheral use cases are better handled elsewhere, such as aligning [offset annotations](https://github.com/huggingface/transformers/issues/7019#issuecomment-691965153) or having trainers [support other data structures](https://github.com/huggingface/transformers/issues/6860).

I wish that was stated (as clearly as possible) so that I could make the best use of transformers instead of forcing it to be something it doesn't want to be. 

## Your contribution

I think it's up to the Huggingface team to decide what transformers is and what it will be. After digging around for a few days I would suggest something like
> Transformers makes pre-trained language models available to everyone through clear, consistent and cross platform APIs. Transformer's goal(s) are to make pretrained models accessible and plug into end users existing infrastructure, as well as support common academic tasks. 

> Transformers does not aim to
* Implement end to end applications of NLP
* Implement domain specific models (Custom entities in Swahili, joint classification and entity annotation) 
* ....

**Comment by LysandreJik** [comment]
That's a good idea! The closest document we have to this right now is our [philosophy](https://huggingface.co/transformers/philosophy.html), have you checked it out?

**Comment by talolard** [comment]
No, I just saw it now. 
It in fact has exactly what I would have wanted to find. Particularly the sentence
> As a consequence, this library is NOT a modular toolbox of building blocks for neural nets. If you want to extend/build-upon the library, just use regular Python/PyTorch/TensorFlow/Keras modules and inherit from the base classes of the library to reuse functionalities like model loading/saving.

**Comment by thomwolf** [comment]
We could clean up the readme indeed. It's probably time to remove the migration sections about `pytorh-pretrained-bert` and `pytorch-transformers` and the quick-tour about the examples could be shortened.

**Comment by sgugger** [comment]
Cleaning the README has been on my TODO for a long time, but I have been actively procrastinating. Will do that this week.
