### ISSUE TITLE
modeling_xlnet.py:283: UserWarning: Mixed memory format inputs detected while calling the operator.

### ISSUE THREAD

**Issue by fhamborg** [huggingface/transformers#7120]
## Environment info

     
- `transformers` version: 3.0.2
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.7.7
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help

@TevenLeScao 

## Information

Model I am using (Bert, XLNet ...): xlnet-base-uncased

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
*  [X] my own task or dataset: (give details below)

## To reproduce

1. Simply invoke XLNet using the following

``` 
last_hidden_state, mems = lm(
                input_ids=input_ids,
                token_type_ids=token_type_ids,
                output_hidden_states=True,
            )
```

I receive a warning as follows:

```
...\anaconda3\envs\newstsc2\lib\site-packages\transformers\modeling_xlnet.py:283: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output contiguous tensor even if some of the inputs are in channels_last format. (Triggered internally at  ..\aten\src\ATen\native\TensorIterator.cpp:918.)
  attn_score = (ac + bd + ef) * self.scale
```

## Expected behavior

no warning

**Comment by TevenLeScao** [comment]
Hey! I haven't been able to reproduce this with what you've given, maybe it is linked to your 'token_type_ids' ? I don't really have enough info on what you're trying to do with only this line. In any case:

 - The warning text seems innocuous.
 - I don't see this line in the current (master) codebase, so I'd suggest upgrading and seeing if this issue still crops up.

**Comment by mihaidobri** [comment]
@TevenLeScao  FYI:  I have the same warning message, on Colab,using Xlnet-base-cased (custom script , custom dataset)
