### ISSUE TITLE
Add tokenizer file save in convert_graph_to_onnx.py 

### ISSUE THREAD

**Issue by Ierezell** [huggingface/transformers#7132]
# 🚀 Feature request

Allow saving the associated tokenizer files (to be loaded possibly with the tokenizer library) when running `convert_graph_to_onnx.py`  
## Motivation

Having the good vocab file next to the good onnx model to avoid confusion and ease the loading process by any other framework (because models and their tokenizers are deeply linked). 

## Your contribution

With [this comment from tokenizer repo](https://github.com/huggingface/tokenizers/issues/59#issuecomment-610645970) and the [convert_graph_to_onnx.py](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_graph_to_onnx.py) one can simply add 

L.358
```
if tokenizer is None:
        download_vocab_files_for_tokenizer(nlp.tokenizer, model, output)
```
and before `if __name__ == "__main__"` 
```
def download_vocab_files_for_tokenizer(tokenizer, model_type, output_path):
    vocab_files_map = tokenizer.pretrained_vocab_files_map
    vocab_files = {}
    for resource in vocab_files_map.keys():
        download_location = vocab_files_map[resource][model_type]
        f_path = path.join(output_path.parent,
                           path.basename(download_location))
        urllib.request.urlretrieve(download_location, f_path)
```

I can do a PR for it if the interest is big enough. 

NB : This is a patch I added in my local lib but feel free to modify it or transform it as you want, it's just to give the idea

**Comment by patil-suraj** [comment]
cc. @mfuntowicz
