### ISSUE TITLE
generate text function support part of the  target inputs

### ISSUE THREAD

**Issue by lonelydancer** [huggingface/transformers#7139]
# 🚀 Feature request

https://pytorch.org/docs/stable/generated/torch.nn.Transformer.html?highlight=transformer#torch.nn.Transformer

in pytorch transformer class, we can see the forward function can pass target sentence; so when i wanna to generate the target_sentence from the middle , i can pass part of the target_sentence to the model, then i can generate the rest of the sentence.
## Motivation
the generate function is really powerful.
Here is my situation, i have the full source sentence and certain part of the target sentence, then i begin to generate the rest of the target sentence, using beam search etc..
But i found the interface do not support part of target sentence as input.

**Comment by iseesaw** [comment]
hi, did you solve this problem?
