### ISSUE TITLE
unexpected keyword argument 'force_fusions' when running the onnx notebook

### ISSUE THREAD

**Issue by pierre-si** [huggingface/transformers#7144]
## Environment info
   
- `transformers` version: 3.1.0
- Platform: Linux-5.8.0-1-amd64-x86_64-with-debian-bullseye-sid
- Python version: 3.7.8
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

## Information

The problem arises when using:
* [x] the official example scripts: the notebook "04-onnx-export"
* [ ] my own modified scripts: (give details below)

## To reproduce

1. Run the notebook's cells. 
First cell installs onnxruntime in version 1.4.0
The "Benchmarking ONNX quantized model" cell calls transformers/convert_graph_to_onnx.py,
which calls the "quantize" function with parameter force_fusions.

`Error: quantize() got an unexpected keyword argument 'force_fusions'`
The parameter was discarded in onnxruntime 1.4.0
Removing the parameter in convert_graph_to_onnx.py solves the issue.
## Expected behavior

No error.

**Comment by mfuntowicz** [comment]
The error might be something else, onnxruntime version 1.4.0 does include the `force_fusions` parameter: 

https://github.com/microsoft/onnxruntime/blob/v1.4.0/onnxruntime/python/tools/quantization/quantize.py#L1457

**Comment by pierre-si** [comment]
Indeed,
my bad, somehow the notebook used the python 3.8 related onnxruntime package and not the one associated with the conda environment from which I was launching jupyter notebook.
It works perfectly, thanks :+1:
