### ISSUE TITLE
Load Pre-Trained Model Using Docker

### ISSUE THREAD

**Issue by idhasson** [huggingface/transformers#7145]
# ❓ Questions & Help

## Details

I'm trying to load a pre trained model using transformers lib (by hugging-face):

from transformers import GPT2Tokenizer, GPT2Model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2-medium')

Using local machine, it starts to download the model. But with docker I get the following:

OSError: Model name 'gpt2-medium' was not found in tokenizers model 
name list (gpt2, gpt2-medium, gpt2-large, gpt2-xl, distilgpt2). We 
assumed 'gpt2-medium' was a path, a model identifier, or url to a 
directory containing vocabulary files named ['vocab.json', 
'merges.txt'] but couldn't find such vocabulary files at this path or url.

Any idea why it happens?

**Comment by LysandreJik** [comment]
Are you sure you have internet access on your machine? Can you do `wget https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-medium-config.json`?

**Comment by MaxHoefl** [comment]
I have the same issue. The machine on which I am deploying the container to does have internet access, it can download other models from nltk / spacy
