### ISSUE TITLE
Inconsistent parameter naming conventions in ModelConfigs

### ISSUE THREAD

**Issue by arkadyark** [huggingface/transformers#7154]
## Environment info

     
- `transformers` version: 3.0.2 (N/A)

### Who can help
 
@LysandreJik 

## Information

This isn't exactly a bug, but more a suggestion that would be helpful. Across several different models, there are config classes used to initialize a model (e.g. GPT2Config and BertConfig). Some of these configs have parameters that mean the same thing, but use different naming conventions for the parameters, for instance n_layer in GPT2Config is the same, conceptually, as num_hidden_layers for BertConfig.

For ease of development, I think it could be worthwhile to make these parameter names consistent across all of the transformer config classes.

I'd be happy to help out on this, it seems like it should be a relatively straightforward change, though it may break some backwards compatibility.

**Comment by LysandreJik** [comment]
Hi! As you've mentioned, this would break backwards compatibility which is not something we're willing to do for a name change. Furthermore, these values are named as such to be the same as the original implementation, therefore these will not be changed.

Thank you for opening an issue!
