### ISSUE TITLE
I reduce the longformer's attention window from 512 to 256, but train speed not changed 

### ISSUE THREAD

**Issue by xixiaoyao** [huggingface/transformers#7159]
# ❓ Questions & Help

According to the Longformer's design, it should be sensitive for training speed and memory consuming when the local window size is changed. However, I find nothing happened when I half the attention window size (from [512]*12 to [256]*12). Is this phenomenon under expectations? or there is something wrong?

**Comment by patrickvonplaten** [comment]
Hey @xixiaoyao, the main gain is memory savings for longformer - so I'm not really surprised if you say that training speed does not change when halving the attention window...
