### ISSUE TITLE
Create larger summaries by using Summarization models like T5 or Pegasus

### ISSUE THREAD

**Issue by MichaelJanz** [huggingface/transformers#7162]
Hi,
I want to create summaries of book-reviews, which should be about half the size of the original text corpus.
My goal is to compare how well the summaries are created and if the important content of the original texts are taken over.
For this I just had a look at different models and saw, that the models have a very fixed max length (often about 256 tokens), which corresponds in creating only 1-2 sentences, while my goal is for example to have 8 sentences, when the original text corpus has 16.

Of course I could split my text corpus in smaller ones, but then I am afraid that the context of the previous sentences gets lost. (Is there maybe a way to pass the context information on into the next predictions, as it could be done in stateful RNNs? Atleast I dont think so)

For sure many others already had the issue, since there are tasks as summarizing whole documents or even books, which cannot be done in one sentence.

I already [asked](https://stackoverflow.com/questions/63904821/using-transformer-for-text-summarization) on SO, but unfortunately I didnt get an answer there.
So I would appreciate any hint on how I could continue on my task.

Thank you!

**Comment by LysandreJik** [comment]
Pinging the summarization expert here @sshleifer

**Comment by sshleifer** [comment]
Can we move [here](https://discuss.huggingface.co/t/summarization-on-long-documents/920/5)

I am super happy to help, but want to help everybody at the same time. @ibeltagy is working hard on summarizing longer docs, but besides his efforts we don't have what you are looking for.

**Comment by MichaelJanz** [comment]
Thank you for posting, I will have a look at it.
