### ISSUE TITLE
__init__() got an unexpected keyword argument 'cache_dir' 

### ISSUE THREAD

**Issue by jasonyliang** [huggingface/transformers#7165]
After reviewing issue #7006 and following the steps (updating Transformers to the latest version or even the 3.1.0 branch), I still get the error:
TypeError: init() got an unexpected keyword argument 'cache_dir'
when running the latest version for transformers (3.1.0).
I'm also running on Colab environment:
Command:
!pip3 install transformers
(also tried #! pip3 install git+git://github.com/huggingface/transformers/)

!wget https://raw.githubusercontent.com/huggingface/transformers/master/examples/language-modeling/run_language_modeling.py

%%bash
export TRAIN_FILE=train_path
export TEST_FILE=valid_path
export MODEL_NAME=gpt2
export OUTPUT_DIR=output

python run_language_modeling.py
--output_dir=output
--model_type=gpt2
--model_name_or_path=gpt2
--do_train
--train_data_file=$TRAIN_FILE
--do_eval
--eval_data_file=$TEST_FILE
--cache_dir=None

Output:
Traceback (most recent call last):
File "run_language_modeling.py", line 313, in
main()
File "run_language_modeling.py", line 242, in main
get_dataset(data_args, tokenizer=tokenizer, cache_dir=model_args.cache_dir) if training_args.do_train else None
File "run_language_modeling.py", line 143, in get_dataset
cache_dir=cache_dir,
TypeError: init() got an unexpected keyword argument 'cache_dir'

**Comment by LysandreJik** [comment]
Do you have a link to the colab?

**Comment by jasonyliang** [comment]
I was following the tutorial by Joey S and tried to include my own dataset instead. This is the notebook that he has provided:
https://colab.research.google.com/drive/1odn0VHb4SmQnUqtOwK6XQTLpoTSbneCf?usp=sharing

The notebook he provided already has the error.
Thank you so much for taking a look!

**Comment by LysandreJik** [comment]
The error seems to not be here anymore when doing `!pip3 install git+https://github.com/huggingface/transformers` instead of `pip3 install transformers` and resetting to factory settings before doing the run.

**Comment by jasonyliang** [comment]
Thank you so much! It's working now!

**Comment by LysandreJik** [comment]
Glad I could help!
