### ISSUE TITLE
weights partially missing for CamembertForMaskedLM 

### ISSUE THREAD

**Issue by raphael0202** [huggingface/transformers#7167]
## Environment info

- `transformers` version: 3.1.0
- Platform: Darwin-18.7.0-x86_64-i386-64bit
- Python version: 3.7.5
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help
 
@louismartin 

## Information

When loading "camembert-base" with `CamembertForMaskedLM` with:

    from transformers import CamembertForMaskedLM
    model = CamembertForMaskedLM.from_pretrained("camembert-base")

the bias of the LM head decoder is not loaded:

    Some weights of CamembertForMaskedLM were not initialized from the model checkpoint at camembert-base and are newly initialized: ['lm_head.decoder.bias']
    You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

As I understand `lm_head.decoder.bias` is therefore initialized randomly.
I checked the original `camembert-base` model as published by the author, and the lm_head decoder bias is missing too, which is not discussed in the camembert or roberta publication.

**Comment by louismartin** [comment]
Hi @raphael0202 , we converted the fairseq checkpoints using [this script](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_roberta_original_pytorch_checkpoint_to_pytorch.py), maybe the language model head was not transfered during the conversion. 
You can either use the model in fairseq as per [our website](https://camembert-model.fr/) or try to understand if and why the LM head hasn't transfered from fairseq to transformers.

**Comment by louismartin** [comment]
Check this tutorial as well for huggingface: https://huggingface.co/camembert-base

**Comment by raphael0202** [comment]
After a bit of search I found out the warning comes from the way the decoder bias is defined in the code, the same warning is issued when loading the roberta model (see issue 6193). I checked that the LM head decoder bias is the same as the one in the original pytorch checkpoint.
Thank you for your help!

**Comment by louismartin** [comment]
Ok perfect, thanks for fixing this.
