### ISSUE TITLE
how to continue training from a checkpoint with Trainer?

### ISSUE THREAD

**Issue by fumpe** [huggingface/transformers#7198]
# ❓ Questions & Help

## Details

I am trying to continue training my model (gpt-2) from a checkpoint, using Trainer. However when I try to do it the model starts training from 0, not from the checkpoint. I share my code because I don't know where I'm making the mistake.

```
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

from transformers import TextDataset,DataCollatorForLanguageModeling, AutoTokenizer, GPT2LMHeadModel, Trainer, TrainingArguments

tokenizer = AutoTokenizer.from_pretrained("gpt2-large")

train_dataset = TextDataset(
          tokenizer=tokenizer,
          file_path='textfile (1).txt',
          block_size=128)

data_collator = DataCollatorForLanguageModeling(
        tokenizer=tokenizer, mlm=False,
    )

model = GPT2LMHeadModel.from_pretrained("checkpoint-9500").to(device) ##HERE I LOAD FROM CHECKPOINT

training_args = TrainingArguments(
    output_dir='./results',         # output directory
    num_train_epochs=4,              # total # of training epochs
    per_device_train_batch_size=1,  # batch size per device during training
    per_device_eval_batch_size=64,   # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    #eval_dataset=validation_dataset,
    prediction_loss_only=True,
)

trainer.train()



```
Thanks a lot for the help.

**Comment by sgugger** [comment]
Hi there, you have to pass the checkpoint path to the method `Trainer.train` to resume training:
```
trainer.train("checkpoint-9500")
```
If you set your logging verbosity to the INFO level (`transformers.logging.set_verbosity_info()`) you should then see information about the training resuming and the number of steps skipped.

**Comment by fumpe** [comment]
Great, thanks a lot for your help Sylvain.

Works perfect.

**Comment by jawadSajid** [comment]
Hey, @fumpe which version of transformers were you using here? Please do let me know.

**Comment by sid-sundrani** [comment]
> Hi there, you have to pass the checkpoint path to the method `Trainer.train` to resume training:
> 
> ```
> trainer.train("checkpoint-9500")
> ```
> 
> If you set your logging verbosity to the INFO level (`transformers.logging.set_verbosity_info()`) you should then see information about the training resuming and the number of steps skipped.

@sgugger if training is over, `num_train_epochs`, is reached, how do you load the checkpoint and train say for the next n epochs? when I load the checkpoint, it only trains until that epoch is over 

```
trainer.num_train_epochs = trainer.num_train_epochs + 5
trainer.train("checkpoint-9500")
```

**Comment by sgugger** [comment]
`Trainer` does not have a `num_train_epochs` attribute that is used, you need to set `trainer.args.num_train_epochs`. To be sure everything is updated, you probably need to re-instantiate the `Trainer` with the new `TrainingArguments` though.

**Comment by Bowen-n** [comment]
When I resume training from a checkpoint, I use a new batch size different from the previous training and it seems that the number of the skipped epoch is wrong.

For example, I trained a model for 10 epochs with `per_device_train_batch_size=10` and generate a checkpoint. Then I  resume training from this checkpoint with `per_device_train_batch_size=10`, the trainer will skip 12 epochs.

What should I do if I want to resume training with a different batch size?

**Comment by sgugger** [comment]
That feature is not supported, you should resume training with the exact same hyperparameters or start a new training if you want to change them.

**Comment by Xiaoxiao0606** [comment]
I have trained a model and saved the checkpoint，Now I want to increase the number of epochs to continue training, but I have a problem.My training loss is not able to match the previous training, there is a very big difference（First up, then down, but not down to the original level）.I increased the number of epochs from 20 to 30.
`training_args = TrainingArguments( 
            output_dir= models_path + '/' + chain + '_' + modeltype + 'bert/two/log',
            save_total_limit=5,
            do_train=True,
            do_eval=True,
            evaluation_strategy='epoch',
            #eval_steps=1,
            overwrite_output_dir=True,
            num_train_epochs=30,
            per_device_train_batch_size=128,
            learning_rate=9.282980634054497e-05,
            weight_decay=0.1531103573951345,
            warmup_ratio=0.05549995455206759,
            logging_first_step=True,
            ignore_data_skip=True,
            save_steps=100,
            logging_dir = models_path + '/' + chain + '_' + modeltype + 'bert/two/runs/' + datetime.datetime.strftime(datetime.datetime.now(),'%Y-%m-%d_%H:%M:%S'),
            logging_steps=10,
            seed = 19930606
        )`
`trainer = Trainer(
            model=model,
            args=training_args,
            data_collator=data_collator,
            train_dataset=train_dataset,
            eval_dataset = eva_dataset
        )`
` trainer.train(resume_from_checkpoint=True)`
Thanks a lot for the help.

**Comment by muhammedcanpirincci-sudo** [comment]
> have trained a model and saved the checkpoint，Now I want to increase the number of epochs to continue training, but I have a problem.My training loss is not able to match the previous training, there is a very big difference（First up, then down, but not down to the original level）.I increased the number of epochs



> That feature is not supported, you should resume training with the exact same hyperparameters or start a new training if you want to change them.

For example i want to freeze some layers in the checkpointed model. Is it possible?

**Comment by oscar-eaglewatch** [comment]
I have two bin files like pytorch_model-00001-of-00002.bin and pytorch_model-00002-of-00002.bin in the checkpoint-1000 folder but it won't load! It still says that "ValueError: Can't find a valid checkpoint at checkpoint-1000."

**Comment by sgugger** [comment]
Make sure you are using a source install of Transformers. This is a bug that was recently fixed @oscar-eaglewatch

**Comment by vijetadeshpande** [comment]
How do I differentiate between,

1. continue pre-training from a checkpoint with the previous optimizer/scheduler state
2. continue pre-training from a checkpoint but reset the optimizer and the scheduler

**Comment by DavidFarago** [comment]
@sgugger I have been changing my hyperparameters and got `Can't find a valid checkpoint`. Now it seems I cannot find the original hyperparameter settings (esp. `for` `per_device_train_batch_size`, `gradient_accumulation_steps`, and `max_steps`). I did find the `max_steps` in some json file in the checkpoint, but not the other hyperparameter settings. How can I find out the settings I should pick?

**Comment by lucasjinreal** [comment]
Hi, there, I got same error with deepspeed. training noramlly and resume got `Can't find a valid checkpoint`

first I try resume_from_checkpoint with `out/lora-Vicuna-chat` (output_path) got  `Can't find a valid checkpoint`
then I send `out/lora-Vicuna-chat/checkpoint-6000` I can not load the lora weights........

```
"base_model.model.model.layers.31.self_attn.k_proj.lora_B.default.weight", "base_model.model.model.layers.31.self_attn.v_proj.weight", "base_model.model.model.layers.31.self_attn.v_proj.lora_A.default.weight", 
"base_model.model.model.layers.31.self_attn.v_proj.lora_B.default.weight", "base_model.model.model.layers.31.self_attn.o_proj.weight", "base_model.model.model.layers.31.self_attn.o_proj.lora_A.default.weight", 
"base_model.model.model.layers.31.self_attn.o_proj.lora_B.default.weight", "base_model.model.model.layers.31.self_attn.rotary_emb.inv_freq", "base_model.model.model.layers.31.mlp.gate_proj.weight", 
"base_model.model.model.layers.31.mlp.gate_proj.lora_A.default.weight", "base_model.model.model.layers.31.mlp.gate_proj.lora_B.default.weight", "base_model.model.model.layers.31.mlp.down_proj.weight", 
"base_model.model.model.layers.31.mlp.down_proj.lora_A.default.weight", "base_model.model.model.layers.31.mlp.down_proj.lora_B.default.weight", "base_model.model.model.layers.31.mlp.up_proj.weight", 
"base_model.model.model.layers.31.mlp.up_proj.lora_A.default.weight", "base_model.model.model.layers.31.mlp.up_proj.lora_B.default.weight", "base_model.model.model.layers.31.input_layernorm.weight", 
  Unexpected key(s) in state_dict:"base_model.model.model.layers.31.self_attn.q_proj.lora_A.weight", "base_model.model.model.layers.31.self_attn.q_proj.lora_B.weight", "base_model.model.model.layers.31.self_attn.k_proj.lora_A.weight", 
"base_model.model.model.layers.31.self_attn.k_proj.lora_B.weight", "base_model.model.model.layers.31.self_attn.v_proj.lora_A.weight", "base_model.model.model.layers.31.self_attn.v_proj.lora_B.weight", 
"base_model.model.model.layers.31.self_attn.o_proj.lora_A.weight", "base_model.model.model.layers.31.self_attn.o_proj.lora_B.weight", "base_model.model.model.layers.31.mlp.gate_proj.lora_A.weight", 
"base_model.model.model.layers.31.mlp.gate_proj.lora_B.weight", "base_model.model.model.layers.31.mlp.down_proj.lora_A.weight", "base_model.model.model.layers.31.mlp.down_proj.lora_B.weight", 
```

the model with some suffix `default`, but samed model didn't have......

I am confused so much

**Comment by thusinh1969** [comment]
Transformers have been a few years old, I thought that it should be mature by now, atleast 1 core version that works flawlessly all the way. 

But man, basic and simple issues like saving checkpoints, weight reload, resume, skip dataset etc... with pure transformers or deepspeed...still bumping around, real pain in the b** :( ... I must say that I admired Yolov5 most in the way they described things, annoucing news, bugs fixed. My 2 cents for this great repo, it deserves much more than this.

**Comment by thusinh1969** [comment]
Falling back to 4.28.1 :((

**Comment by KaiserWhoLearns** [comment]
I am having the same problem with Deepspeed, it seems that a different format of checkpoint is expected for saving. Did you manage to resolve the issue? @lucasjinreal lucasjinreal

**Comment by NickWithBotronics** [comment]
> Hi there, you have to pass the checkpoint path to the method `Trainer.train` to resume training:
> 
> ```
> trainer.train("checkpoint-9500")
> ```
> 
> If you set your logging verbosity to the INFO level (`transformers.logging.set_verbosity_info()`) you should then see information about the training resuming and the number of steps skipped.

@sgugger how would I start at the same step I left off on? (Or before my training run crashed, it stopped at step 1333 and I have ckpt there, and I used a consistent seed, set on the script.

(Also un related-ish there is a hugging face wiki, available as a raw file? I would love to train a deepseek model on hugging face code, that way can limit the lower the amount of people asking questions as the model could possibly answer it for them.)

**Comment by cbjtu** [comment]
Hi, I wonder why can I resume train successfully with trainer.train(resume_from_checkpoint=resume_from_checkpoint,) but no use when set training_arguments = TrainingArguments(resume_from_checkpoint=resume_from_checkpoint,)? Which way is correct?

`
training_arguments = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    # gradient_checkpointing=gradient_checkpointing,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    fp16=fp16,
    bf16=bf16,
    max_grad_norm=max_grad_norm,
    num_train_epochs=num_train_epochs,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=group_by_length,
    lr_scheduler_type=lr_scheduler_type,
    report_to="tensorboard",
    logging_dir=tb_log_dir,
    local_rank=local_rank,  
    ignore_data_skip=ignore_data_skip,
    resume_from_checkpoint=resume_from_checkpoint,
    # fsdp='full_shard'
    # torch_compile=True,
    # eval
    per_device_eval_batch_size=per_device_eval_batch_size,
    eval_accumulation_steps=20,
    evaluation_strategy='steps',
    fp16_full_eval=True,
    eval_steps=save_steps,
)


trainer = SFTTrainer(
    model=model,
    train_dataset=dataset['train'],
    eval_dataset=dataset['test'],
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
    packing=packing,
    compute_metrics=compute_metrics_rouge,
)

print_memory_usage()

trainer.train()
trainer.model.save_pretrained(output_dir)`
