### ISSUE TITLE
[model cards] yaml specs and related questions

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#7208]
Is it possible to write a spec for how model cards should declare languages when it's more than one? 

I sorted it out:
```
language: 
- ru
- en
```
could we add this somewhere?

I tried this https://github.com/huggingface/model_card/pull/2 - definitely easier to mimic, but perhaps not ideal.

------------

The array of datasets is unclear too. https://huggingface.co/allenai/wmt16-en-de-dist-12-1
I added:
```
- datasets: http://www.statmt.org/wmt16/ ([test-set](http://matrix.statmt.org/test_sets/newstest2016.tgz?1504722372)) 
```
but it rendered them as one entry - how can I make those into proper dataset links?

I think it'd have helped a lot with having the template demo a few entries and let the user modify those. 

I found a hint doing:

```
grep -r -A2 datasets: model_cards
```

edit: ok, now I know it expects just a label for a dataset that is already in the transformers list., and not the urls to the datasets.

probably a guide could say, pick one more dataset entries from https://huggingface.co/datasets?

--------------

Do we have a tool that validates model_card's yaml section? This can probably be automated, right?
```
make card-check
```
?

-------------------------
Why at https://huggingface.co/allenai/wmt19-de-en-6-6-big
it added a bunch of tags that are wrong and weren't in the yaml spec? 
`lm-head` and `masked-lm` shouldn't be there

--------------------------
Also how can I tell the models site that the demo should be of a translation type and not masking?
somehow it picked up the correct demo type for https://huggingface.co/allenai/wmt16-en-de-dist-12-1
but for https://huggingface.co/facebook/wmt19-en-ru it wants to do fill-mask

----

Related thread: https://discuss.huggingface.co/t/tips-for-debugging-model-cards/814

---

@julien-c

**Comment by stas00** [comment]
OK langs I figured out - it wants:
```
language: 
- ru
- en
```
I re-made the cards: https://github.com/huggingface/transformers/pull/7207

**Comment by stas00** [comment]
Do we have a tool that validates model_card's yaml section? This can probably be automated, right?

`make card-check`?

**Comment by stas00** [comment]
Also how can I tell the models site that the demo should be of a translation type and not masking?

**Comment by julien-c** [comment]
Addressed in https://github.com/huggingface/model_card/pull/3 so closing this one.
