### ISSUE TITLE
Links seem to be expired for German NER example 

### ISSUE THREAD

**Issue by Santosh-Gupta** [huggingface/transformers#7215]
There is a German Ner example here

https://github.com/huggingface/transformers/tree/master/examples/token-classification

It seems that the links for the training data are no longer working

```
curl -L 'https://sites.google.com/site/germeval2014ner/data/NER-de-train.tsv?attredirects=0&d=1' \
| grep -v "^#" | cut -f 2,3 | tr '\t' ' ' > train.txt.tmp
curl -L 'https://sites.google.com/site/germeval2014ner/data/NER-de-dev.tsv?attredirects=0&d=1' \
| grep -v "^#" | cut -f 2,3 | tr '\t' ' ' > dev.txt.tmp
curl -L 'https://sites.google.com/site/germeval2014ner/data/NER-de-test.tsv?attredirects=0&d=1' \
| grep -v "^#" | cut -f 2,3 | tr '\t' ' ' > test.txt.tmp
```

I tried going to the links directly and got 404.

For convenience, here's a colab notebook that runs the whole example. The contents of the created downloaded and processed data files do not seem correct to me.  

https://colab.research.google.com/drive/1ox23ZuWNwh3pim8OQAW99TF2sTVHzKqH?usp=sharing

**Comment by LysandreJik** [comment]
@stefan-it might know what's up!

**Comment by stefan-it** [comment]
Oh, I think this PR should fix it:

https://github.com/huggingface/transformers/pull/6571

I will resolve some merge conflicts, then it should be ready to merge!

**Comment by stefan-it** [comment]
Updated, it should work now :+1: 

@Santosh-Gupta Please try to use the new urls for the GermEval dataset in your Colab :)

**Comment by LysandreJik** [comment]
The links have been updated, thanks @stefan-it
