### ISSUE TITLE
FSMT Cuda CI Failures

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7217]
https://github.com/huggingface/transformers/runs/1130127719?check_suite_focus=true

I'm not sure whether these are spurious, but I wanted to bring them to your attention @stas00 .

**Comment by stas00** [comment]
I'm not able to reproduce those, but let's first thing first let's skip them so that CI is not affected. 
https://github.com/huggingface/transformers/pull/7220
I will investigate and we can try to enable them again later.

**Comment by stas00** [comment]
I've found some other tests failing with USE_CUDA=1, but which were fine on CI - so I will attend to those first.

Hope we could finalize this issue https://github.com/huggingface/transformers/issues/6349 and get USE_CUDA on by default.
