### ISSUE TITLE
tokenizer.add_tokens conflict with MBart's tokenizer

### ISSUE THREAD

**Issue by znculee** [huggingface/transformers#7222]
## Environment info

  
- `transformers` version: 3.1.0
- Platform: Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.3
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help

@patil-suraj @mfuntowicz 

## To reproduce

1. import MBartTokenizer
2. try `tokenizer.add_tokens('__something_new__')`
3. `tokenizer('__something_new__')`

## Expected behavior

`add_tokens()` should add new tokens after all existing tokens in the vocabulary, however, the `lang_code` will conflict with the added tokens.

## Current Workaround

```
new_token_to_id = {tok: vocab_size + i for i, tok in enumerate(new_tokens)}
self.tokenizer.fairseq_tokens_to_ids.update(new_token_to_id)
self.tokenizer.fairseq_ids_to_tokens = {v: k for k, v in self.tokenizer.fairseq_tokens_to_ids.items()}
self.tokenizer.unique_no_split_tokens.extend(new_tokens)
```

**Comment by sshleifer** [comment]
I love your workaround and would definitely be interested in a clean contribution that made in accessible to everyone.

**Comment by znculee** [comment]
@sshleifer Thanks! I've created a pull request #7353 with this workaround.
