### ISSUE TITLE
Suggestion: Better to change the task name of  "sentiment-analysis" to "text-classification"

### ISSUE THREAD

**Issue by shirayu** [huggingface/transformers#7227]
There is a task named ``sentiment-analysis`` in``SUPPORTED_TASKS`` used in piepelines.
https://github.com/huggingface/transformers/blob/master/src/transformers/pipelines.py#L2509

However, it can be used not only for sentiment analysis but also fo more generic tasks.
Therefore, I think it is better to rename it to ``text-classification`` (or add a task named ``text-classification`` for backward compatibility).

**Comment by LysandreJik** [comment]
These are tasks that can be done with a specific pipeline, with a model and tokenizer as default. Having the `sentiment-analysis` task supported with a `TextClassificationPipeline` is the same as having a `ner` task supported with a `TokenClassificationPipeline`. These tasks are not generic text-classification or token-classification, but specific tasks that users can use.

If you want a general pipeline for text classification, then you can simply use the text-classification pipeline directly:
```py
from transformers import TextClassificationPipeline
```
