### ISSUE TITLE
test fsmt finetuning

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7230]
Would be interested to know whether this works with finetune.py.
Just add your tiny guy to 
https://github.com/huggingface/transformers/blob/master/examples/seq2seq/test_seq2seq_examples.py#L378
and edit l382 to set task='translation'.

If it doesn't pass, we can investigate, but I expect it to pass.

Happy for either of us to take this one @stas00 

(this is behind tiny fsmt in the queue, but writing it down so I don't forget.)

**Comment by stas00** [comment]
I did a quick:

```
def test_finetune():
    model = "stas/tiny-wmt19-en-de"
    task = "translation" 
    args_d: dict = CHEAP_ARGS.copy()
    args_d["label_smoothing"] = 0.1 if task == "translation" else 0
    [...]
```
getting:
```
       torch.nn.modules.module.ModuleAttributeError: 'FSMTModel' object has no attribute 'shared'
/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/nn/modules/module.py:778: ModuleAttributeError
```
`fsmt` doesn't have `.shared` as most of the models aren't shared. So it won't work as is. Will need to do some tweaking.

**Comment by stas00** [comment]
Done: https://github.com/huggingface/transformers/pull/7263
