### ISSUE TITLE
KeyError: 'squeezebert' which from model zoo

### ISSUE THREAD

**Issue by ORlGlN** [huggingface/transformers#7241]
This error occurs when using the pretrained model from https://huggingface.co/squeezebert/squeezebert-mnli

**Comment by LysandreJik** [comment]
Hi! We're still in the process of merging squeezebert. You can see the development [here](https://github.com/huggingface/transformers/pull/7083).

**Comment by forresti** [comment]
Maybe try again now? SqueezeBERT support was recently merged into the master branch.
