### ISSUE TITLE
[example/glue] run_glue compute metrics fail for bart like models

### ISSUE THREAD

**Issue by patil-suraj** [huggingface/transformers#7247]
This PR #7126 introduced multiple predictions for trainer. This breaks the `compute_metrics_fn` of `run_glue.py`  for `bart` like models which return multiple predictions.

For `BartForSequenceClassfication` `p.predictions`  is a `tuple`, so following code fails
https://github.com/huggingface/transformers/blob/1d90d0f386af2af52017d51c421e71a51ec94de0/examples/text-classification/run_glue.py#L154

@sgugger

**Comment by sgugger** [comment]
I didn't expect that side effect, thanks for fixing it so quickly!
