### ISSUE TITLE
Feature Request: Support Longformer 3D attention mask ?

### ISSUE THREAD

**Issue by Maybewuss** [huggingface/transformers#7265]
I try to use 3d attntion mask, but failed.

**Comment by patrickvonplaten** [comment]
Hey @Maybewuss,
could you post a code snippet example, where you show the use case of using a 3D attention mask? :-) 
What would you use it for?

**Comment by Maybewuss** [comment]
> Hey @Maybewuss,
> could you post a code snippet example, where you show the use case of using a 3D attention mask? :-)
> What would you use it for?

I want each word to foucs different words in an sentence, for example, in the generate task, the attntion mask is a lower triangular 3d matrix. Besides, other models like Bert and Roberta support 3d mask.

**Comment by patrickvonplaten** [comment]
Yes, I see. Let's convert this issue into a feature request and see if someone is interested in opening a PR for it.

**Comment by syiswell** [comment]
I used 3d attention mask in the LongFormer, but also failed. I find that
