### ISSUE TITLE
Question about model configuration

### ISSUE THREAD

**Issue by dmortem** [huggingface/transformers#7275]
# ❓ Questions & Help

Hi,

Now I am trying gpt-2 model to generate sentences. I have a question about the model configuration. 

I load model using [this line in the provided code](https://github.com/huggingface/transformers/blob/master/examples/text-generation/run_generation.py#L221). I found "eos_tokens_ids" and "pad_token_id" both equal to 0. But when I checked the tokenizer, I found the token with id 0 is '!'. So when I use the provided code to generate sentences, sentences always end with '!'. Is there any mistake in the vocabulary or the configuration? Many thanks.

**Comment by patrickvonplaten** [comment]
```python
from transformers import GPT2Config
config = GPT2Config()
print("Pad token id", config.pad_token_id) # should give `None`
print("EOS token id", config.eos_token_id)  # should give `50256`
```

=> So it seems like your config is wrong. Hope this helps!

**Comment by dmortem** [comment]
hi @patrickvonplaten 
I found I used transformer version 2.4.1, after I installed 2.8.0, the output is the same as yours. Also, I found the generate function used "eos_token_ids" instead of. "eos_token_id" as the stop token in 2.4.1. "Eos_token_ids" is not initialized in the configuration and it is 0 by default. Now in 2.8.0, the generation function don't use "Eos_token_ids" any longer.

Thank you!
