### ISSUE TITLE
Error importing MBart from transformers

### ISSUE THREAD

**Issue by MemduhG** [huggingface/transformers#7288]
## Environment info
     
- `transformers` version: 3.1.0
- Platform: Linux-5.4.0-47-generic-x86_64-with-glibc2.29
- Python version: 3.8.2
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): 2.3.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

 Bart: @sshleifer

## Information

Model I am using: MBart, Bart has the same problem

The problem arises when using:
* [X] the official example scripts: Just copied it from the documentation here: https://huggingface.co/transformers/master/model_doc/mbart.html

The tasks I am working on is:
* [X] my own task or dataset

## To reproduce

1. `from transformers import MBartForConditionalGeneration, MBartTokenizer`

## Expected behavior
I would expect MBart to be imported so I could use it, but I get this error instead:

```
ImportError                               Traceback (most recent call last)
<ipython-input-23-20acbef89a41> in <module>
----> 1 from transformers import MBartForConditionalGeneration, MBartTokenizer

ImportError: cannot import name 'MBartForConditionalGeneration' from 'transformers' (/home/memduh/hf/venv/lib/python3.8/site-packages/transformers/__init__.py)
```

**Comment by MemduhG** [comment]
Note: I created a new venv and installed torch before transformers. That way I'm not getting this problem. When I had this problem I had installed transformers first, and I assume it tries to use tensorflow by default when you do that.

**Comment by sshleifer** [comment]
It assumes that you have already installed one of them, your fix is 👍
