### ISSUE TITLE
test_run_eval_search SLOW failure

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7295]
```bash
RUN_SLOW=1 pytest examples/seq2seq/test_seq2seq_examples.py -k search
```

```
FAILED examples/seq2seq/test_seq2seq_examples.py::test_run_eval_search[patrickvonplaten/t5-tiny-random] - ValueError: could not convert string to float: '--data_dir'
FAILED examples/seq2seq/test_seq2seq_examples.py::test_run_eval_search[sshleifer/tiny-mbart] - ValueError: could not convert string to float: '--data_dir'
```

Investigating

**Comment by sshleifer** [comment]
@stas00 
Definitely need this change
![image](https://user-images.githubusercontent.com/6045025/93801070-753f1980-fc0f-11ea-83c6-b544fa4042cf.png)


But then the parsing of the search arg seems to break.
Could you take a look?

**Comment by stas00** [comment]
oh, yes, thank you - will fix shortly

**Comment by stas00** [comment]
Fixed: https://github.com/huggingface/transformers/pull/7297

Apologies for pushing in a broken test :( I think I was testing the wrong branch

**Comment by sshleifer** [comment]
No worries!
