### ISSUE TITLE
Add PRADO model

### ISSUE THREAD

**Issue by Ierezell** [huggingface/transformers#7328]
# 🌟 New model addition

## Model description
PRADO is a model made by google, performing as bert with 100x less parameters

[link to the paper](https://www.aclweb.org/anthology/D19-1506.pdf)
[git to the model code](https://github.com/tensorflow/models/tree/master/research/sequence_projection)

## Open source status

* [X] the model implementation is available: (give details)
* [ ] the model weights are available: (give details)
* [X] who are the authors: (mention them, if possible by @gh-username)
Prabhu Kaliamoorthi / Sujith Ravi / Zornitsa Kozareva

**Comment by KarteekMenda93** [comment]
Yeah, This is a good model to go with if the the text sequence is too long.
