### ISSUE TITLE
data_collator.py - line 326, in mask tokens - xlnet finetuning error

### ISSUE THREAD

**Issue by GenTxt** [huggingface/transformers#7341]
## Environment info

     
- `transformers` version: version: 3.2.0
- Platform: Linux-4.15.0-118-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.1+cu101 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help
 TransfoXL/XLNet: @TevenLeScao 

## Information

Model I am using (XLNet):

The problem arises when using:
* [ x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

Testing simple example in 'language-modeling/examples/README'  using recommended wiki-2-raw dataset and xlnet-base cased model

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x ] my own task or dataset: (give details below)

Same error occurs using simple one sentence per line text file (10 megs)

## To reproduce

1. Run all steps in 'language-modeling/examples/README' using xlnet-base-cased (cached or local)
2. Model loads with warnings and process begins before quickly exiting with the following error:

File "/home/pixelhead/Desktop/xlnet/transformers-master/transformers/data/data_collator.py", line 326, in mask_tokens
    "This collator requires that sequence lengths be even to create a leakage-free perm_mask. Please see relevant comments in source code for details."
ValueError: This collator requires that sequence lengths be even to create a leakage-free perm_mask. Please see relevant comments in source code for details.
Epoch:   0%|                                              | 0/3 [00:00<?, ?it/s]
Iteration:   0%|

## Expected behavior

Expect 'run_language_modeling.py' to work for xlnet as per 'language-modeling/examples/README'
Have tested addition of '--line_by_line' and 'block_size=128, 256, 512'  etc. Same error.

Could be missing something here 'Please see relevant comments in source code for details.' but not clear.

Cheers,

**Comment by LysandreJik** [comment]
@sgugger might be interested in this issue as well.

**Comment by mihaidobri** [comment]
I have the same issue

**Comment by mihaidobri** [comment]
@GenTxt did you find any workaround for this error ?

**Comment by GenTxt** [comment]
No, unfortuantely. Was hoping others more familiar with the problem would
offer solutions.

**Comment by mihaidobri** [comment]
@LysandreJik  or @sgugger I am wondering if you could please let us know if is a workaround for this issue ? or if a code fix is planned in the near future?

**Comment by GenTxt** [comment]
Solved by using TPU instructions on GPU:

**Note:** On TPU , you should use the flag `--pad_to_max_length` in conjunction with the `--line_by_line` flag to make
sure all your batches have the same length.

Works now.

Encountered similar issue with fine-tuning Bert. 

Solved by using:

 --max_seq_length=512 with --line_by_line

**Comment by yanqiangmiffy** [comment]
How to solve the proble

ile "/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/transformers/data/data_collator.py", line 615, in mask_tokens
    "This collator requires that sequence lengths be even to create a leakage-free perm_mask. Please see relevant comments in source code for details."
ValueError: This collator requires that sequence lengths be even to create a leakage-free perm_mask. Please see relevant comments in source code for details.
  0%|

**Comment by darwinharianto** [comment]
I ended up adding <pad> if token length is not even. Is this ok?

**Comment by phiwi** [comment]
I need to hook in to this issue as I can't find a solution for this simple problem:

I have a dataset that I "stream", meaning that during `__getitem__`, i read the line from file/memory, encode and return it. 

As I am pre-training an `XLNetLMHeadModel`, I need the `DataCollatorForPermutationLanguageModeling `which throws the error 

                "This collator requires that sequence lengths be even to create a leakage-free perm_mask. Please see"
                " relevant comments in source code for details."

as in in its function [torch_mask_tokens](https://huggingface.co/docs/transformers/v4.33.0/en/main_classes/data_collator#transformers.DataCollatorForLanguageModeling.torch_mask_tokens) no padding is happening. 

Why is that? Can we somehow combine the `DataCollatorWithPadding ` with the `DataCollatorForPermutationLanguageModeling` in the [trainer](https://huggingface.co/docs/transformers/main_classes/trainer) class? Or is there any other clever solution for such a "stream"-like dataset?

**Comment by phiwi** [comment]
Addendum: I think, a quick solution is to pad to `tokenizer.model_max_length` in the [_torch_collate_batch](https://github.com/huggingface/transformers/blob/v4.33.0/src/transformers/data/data_collator.py#L426) function.
