### ISSUE TITLE
Faster Pegasus tokenizer tests

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7354]
Current test_tokenization_pegasus.py takes more than a minute to run because it uses a full size tokenizer [here](https://github.com/huggingface/transformers/blob/master/tests/test_tokenization_pegasus.py#L19)

It should use "fixtures/test_sentencepiece.model" like `tests/test_tokenization_t5.py`.

**Comment by sshleifer** [comment]
Any interest @stas00 ?

**Comment by stas00** [comment]
Yes, please, you can assign this to me, but most likely will be able to start on it in a few weeks when I have free time.

**Comment by sshleifer** [comment]
Lets wait for @thomwolf 's fast tokenizer PR to start this.

**Comment by sshleifer** [comment]
This is unblocked, thom merged!
