### ISSUE TITLE
how can i convert bert pytorch to tf2 ?

### ISSUE THREAD

**Issue by passion765** [huggingface/transformers#7357]
how can i convert bert pytorch to tf2 ?

**Comment by LysandreJik** [comment]
You can save it and reload it:

```py
pytorch_model.save_pretrained("here")
tf_model = TFBertModel.from_pretrained("here")
```

**Comment by passion765** [comment]
> You can save it and reload it:
> 
> ```python
> pytorch_model.save_pretrained("here")
> tf_model = TFBertModel.from_pretrained("here")
> ```

i can not convert pytorch bert model to tenforflow 2.3 ? can you help me ?

**Comment by LysandreJik** [comment]
Please provide more information, can you respect the issue template? What exactly are you trying to do? Do you have a PyTorch model? How did you get it, is it one of the checkpoints on the hub, is it fine-tuned?

You want to convert it to our TensorFlow API? 

Please provide more details for us to help you better.
