### ISSUE TITLE
How to add some parameters in T5 (in T5Block layer) and initialize the original T5 parameters with pre-trained model and the new introduced parameters randomly? 

### ISSUE THREAD

**Issue by SuHe36** [huggingface/transformers#7360]
Hi,
I want to add a new layer in T5Block,

However, I want to initialize all original parameters with pre-trained T5 and the newly added ones randomly.
Can someone guide me how that's possible or point me to the right direction?

Thanks

**Comment by LysandreJik** [comment]
Hi! The simplest way to do this would be simply to update the `modeling_t5.py` file. You should first clone the repo and install that version in your virtual environment:

```bash
git clone https://github.com/huggingface/transformers
cd transformers
pip install -e ".[dev]"
```

Right now if you load a T5 model it should tell you what layers it's ignoring:

```py
from transformers import T5Model

model = T5Model.from_pretrained("t5-small")
```
Results in:
```
Some weights of T5Model were not initialized from the model checkpoint at t5-small and are newly initialized: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

Now if you edit the `modeling_t5.py` file, especially the `T5Block` as you mentioned:

```py
class T5Block(nn.Module):
    def __init__(self, config, has_relative_attention_bias=False):
        super().__init__()
        self.is_decoder = config.is_decoder
        self.layer = nn.ModuleList()
        self.layer.append(T5LayerSelfAttention(config, has_relative_attention_bias=has_relative_attention_bias))
        if self.is_decoder:
            self.layer.append(T5LayerCrossAttention(config, has_relative_attention_bias=has_relative_attention_bias))

        self.layer.append(T5LayerFF(config))

        # ADDED LAYER BELOW
        self.extra_layer = nn.Linear(200, 200)
```
I've simply added an extra layer here called "extra_layer". I haven't done anything with it in the forward, it's up to you to decide how to use it. If you now re-run the code, you should see the following:

```
Some weights of T5Model were not initialized from the model checkpoint at t5-small and are newly initialized: ['encoder.embed_tokens.weight', 'encoder.block.0.extra_layer.weight', 'encoder.block.0.extra_layer.bias', 'encoder.block.1.extra_layer.weight', 'encoder.block.1.extra_layer.bias', 'encoder.block.2.extra_layer.weight', 'encoder.block.2.extra_layer.bias', 'encoder.block.3.extra_layer.weight', 'encoder.block.3.extra_layer.bias', 'encoder.block.4.extra_layer.weight', 'encoder.block.4.extra_layer.bias', 'encoder.block.5.extra_layer.weight', 'encoder.block.5.extra_layer.bias', 'decoder.embed_tokens.weight', 'decoder.block.0.extra_layer.weight', 'decoder.block.0.extra_layer.bias', 'decoder.block.1.extra_layer.weight', 'decoder.block.1.extra_layer.bias', 'decoder.block.2.extra_layer.weight', 'decoder.block.2.extra_layer.bias', 'decoder.block.3.extra_layer.weight', 'decoder.block.3.extra_layer.bias', 'decoder.block.4.extra_layer.weight', 'decoder.block.4.extra_layer.bias', 'decoder.block.5.extra_layer.weight', 'decoder.block.5.extra_layer.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```
Which means that all these new layers (all the extra_layer layers in T5Block) have been initialized randomly. The rest has been initialized from the checkpoint.

Hope this helps!

**Comment by SuHe36** [comment]
@LysandreJik Thanks, It helps to me!

**Comment by pradeepdev-1995** [comment]
@LysandreJik   @SuHe36 I want to change some model parameters in the t5 model.
So Is it possible to edit the model class in **modeling_t5.py** if I already installed the transformer library using pip in my machine?     (**Without cloning from the repo in a virtual environment as you mentioned in the above comment**)

**Comment by LysandreJik** [comment]
If you want to edit the model file then I heavily recommend you clone the repo and install it in an editable way `pip install -e <path_to_clone>`

**Comment by pradeepdev-1995** [comment]
@LysandreJik  Thanks.
Actually, I tried to edit the configuration_t5.py file.
The default initialization parameters of the T5Config class are as follows
```
        self,
        vocab_size=32128,
        d_model=512,
        d_kv=64,
        d_ff=2048,
        num_layers=6,
        num_decoder_layers=None,
        num_heads=8,
        relative_attention_num_buckets=32,
        dropout_rate=0.1,
        layer_norm_epsilon=1e-6,
        initializer_factor=1.0,
        feed_forward_proj="relu",
        is_encoder_decoder=True,
        use_cache=True,
        pad_token_id=0,
        eos_token_id=1,
        **kwargs
```

I tried to change the **d_model, d_kv,d_ff, num_layers**,**dropout_rate**  from this  configuration_t5.py file.

But after changing the above parameters, when I printing the model architecture it seems like it doesn't change. 

This is the code that I tried

```
import torch
from transformers_master.src.transformers import T5ForConditionalGeneration
model_name = "t5-small"
torch_device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = T5ForConditionalGeneration.from_pretrained(model_name).to(torch_device)
print(model.eval())

```

So where I missed? How can I change the model configuration parameters?
