### ISSUE TITLE
[trainer] Training from scratch

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7393]
@patil-suraj is this possible in the new `Seq2SeqTrainer`? 

Possible solution sketch:
Where we call:

```
AutoSeq2SeqModelWithLMHead.from_pretrained(model_name)
```

Switch to 
```
if args.from_scratch: model = AutoSeq2SeqModelWithLMHead(config)
else: model = AutoSeq2SeqModelWithLMHead.from_pretrained(model_name)
```
What do you think?

**Comment by patil-suraj** [comment]
@sshleifer  Definitely! We can also pass a different `config` if we don't want to use `pretrained config` using `config_name` argument.

Happy to open a PR if it's needed :). Let me know

**Comment by sshleifer** [comment]
@sgugger is this possible with existing `Trainer? It seems like Seq2Seq is the wrong level for this feature to be implemented.

**Comment by patil-suraj** [comment]
Models are initialised in example scripts rather `Trainer`. Currently the way I do it is save a from scratch model and then pass that. I guess it makes sense to add the `from_scratch` argument to `TrainingArguments` but each examples scripts will need to handle this itself

**Comment by sshleifer** [comment]
Oh that's a reasonable workaround. 

```
def convert_pl_to_hf(config_name, save_dir, **config_kwargs):
    cfg = AutoConfig.from_pretrained(config_name, **config_kwargs)
    tok = AutoTokenizer.from_pretrained(config_name)
    model = AutoModelForSeq2SeqLM.from_config(cfg)
    model.save_pretrained(save_dir)
    tok.save_pretrained(save_dir)
    cfg.save_pretrained(save_dir)
```
I'll put this in the make_student PR.
