### ISSUE TITLE
[T5] Automatic setting of decoder_input_ids is misleading and does not correspond to the expected behavior of T5

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#7426]
These lines: https://github.com/huggingface/transformers/blob/f62f2ffdcc2df75cf01438bebc7ae281d921d21d/src/transformers/modeling_t5.py#L1020 were added in this PR: https://github.com/huggingface/transformers/pull/5518 . 

@mfuntowicz - do we need this hack to make onnx work? I would prefer to revert this change.

The lines do not make much sense IMO and should be deleted. Also the T5 error message when only `input_ids` are passed should be updated to be clearer.

And the docs should be cleaned as well: https://huggingface.co/transformers/model_doc/t5.html#t5model.

Also see:https://github.com/huggingface/transformers/issues/7358

**Comment by patil-suraj** [comment]
@patrickvonplaten 
Not a strong opinion, but I've found it helpful that T5 prepares `decoder_input_ids`, seen many issues where people passed wrong `decoder_input_ids` (did not add `pad` token at beginning) which messed up the results.

Also there was a lot confusion about how to prepare right `decoder_input_ids` for seq2seq models. This is a rather opinionated feature,  but for me this makes sense to avoid confusion.
