### ISSUE TITLE
CUDA out of memory (ALBERT) - run_squad.py ignores --per_gpu_train_batch_size

### ISSUE THREAD

**Issue by TaskManager91** [huggingface/transformers#7438]
## Environment info

     
- `transformers` version: 3.3.0
- Platform: Colab Pro (P100) / Anaconda (Windows / 2080 Ti)
- Python version: 3.6
- PyTorch version (GPU?): 1.6.0 / CUDA 10.2
- Tensorflow version (GPU?):
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

## Information

Model I am using (Bert, XLNet ...): ALBERT

The problem arises when using:
* [x] the official example scripts: run_squad.py
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: SQUaD 2.0
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Fine-tune ALBERT-xlarge or xxlarge and  set --per_gpu_train_batch_size 8 or 10
2. try to finetune

```
!python transformers\examples\question-answering\run_squad.py \
  --model_type albert \
  --model_name_or_path albert-large-v2 \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file train-v2.0.json \
  --predict_file dev-v2.0.json \
  --per_gpu_train_batch_size 8 \
  --learning_rate 3e-5 \
  --num_train_epochs 1.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /content/model_output \
  --save_steps 1000 \
  --threads 4 \
  --version_2_with_negative \
  --overwrite_output_dir
```
## Expected behavior

The model should be training, but despite the 8gb limit there is an out of memory error:
```
RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 15.90 GiB total capacity; 15.01 GiB already allocated; 7.88 MiB free; 15.03 GiB reserved in total by PyTorch)
```

**Comment by LysandreJik** [comment]
Do you get the same error when using a batch size of 1?

**Comment by TaskManager91** [comment]
Thanks, with a batch size of 1 it works!

**Comment by LysandreJik** [comment]
The `large` "light BERT" model is quite large indeed ;) The `base` model is smaller if you want to use bigger batch sizes.
