### ISSUE TITLE
Setting up transformers/examples/seq2seq

### ISSUE THREAD

**Issue by jsrozner** [huggingface/transformers#7442]
@sshleifer 

I'm following the instructions in the README for seq2seq. In particular, I forked, cloned, and then ran "pip install -e ."

But then when I tried to run finetune.sh, a number of libraries had not been installed. I had to just manually install them with pip (e.g. rouge_score, git, sacrebleu). Should these all have been included automatically? Or was there a better way to get them?

Is this still the best way to go about finetuning a seq2seq model on a custom task (in my case I am doing T5)?

**Comment by LysandreJik** [comment]
You can install those libraries by doing `pip install -r requirements.txt` in the `transformers/examples` folder!

**Comment by jsrozner** [comment]
Aha, thank you! 

Could I submit a pull request with updates to the README as I go through and encounter these little snags?

Also, is there a reason that the README in the examples/seq2seq directory doesn't show up here? https://huggingface.co/transformers/model_doc/t5.html#t5forconditionalgeneration 

I couldn't find this (quite helpful) README and example scripts for training a seq2seq model until I started exploring the github repository!

**Comment by sshleifer** [comment]
I think all we are missing is some pointer to examples/README.md. Would that have helped you?

**Comment by jsrozner** [comment]
I would add
- mention to both pip install -e ., pip instal -r requirements.txt
- reference the README from the main page

The only other bug I've encountered so far, #7426, was fixed already!

finetune.py ended up being a great script for me. But I wasn't sure if I needed to do any other special things. Is there a place where it would be good to write up the couple of steps I did need? For example:
- load tokenizer /model and modify the vocab (special tokens), then resave them locally (then use load_from_pretrained() on these files)
- prep data files ({val|test|train}.{source|target}) and put into directory
- mod the finetune.sh command

And I do have one other question:
It seems sort of weird that these models (e.g. SummarizationModel) are hidden in the examples directory. Is it because you guys don't generally expect them to be subclassed? I would have expected them to be in, say, transformers/language_generation or similar.

**Comment by sshleifer** [comment]
`SummarizationModule` is a pytorch_lightning.Module. The models under src/ are `nn.Module`.

The main package under `src/` does not depend on pytorch_lightning, or have scripts to train things. Everything that does is under examples/

You could write a forums post with your steps needed: would be super helpful!
https://discuss.huggingface.co/
