### ISSUE TITLE
T5 unsupervised training

### ISSUE THREAD

**Issue by amlarraz** [huggingface/transformers#7451]
I want to train T5 in a new language from scratch an I think the best way to do this is through the unsupervised denoising task (because you can have all text you want! no labels required! hurra!) 

However I have some doubts, I've seen [the HuggingFace  documentation about this](https://huggingface.co/transformers/model_doc/t5.html#training) and I wonder how to create the train data, I mean, is there any function in the library to add the sentinel tokens? In my own research I've worked with [the original T5 library](https://github.com/google-research/text-to-text-transfer-transformer) and I've seen that in this library they have some functions to do that, but this functions not apply the sentinel_tokens to the text but it replace the "noising" tokens by " always. 

My questions are:

1. It exists some functions to do that in HuggingFace?
2.  If the question 1 answer is not, anybody have any?
3. If the question 1 and 2 answers are not, What are the rules I must follow to create this function? Rules like:
           - How much concatenated tokens must the sentinel tokens mask? I mean, in the sentence "The cute dog walks in the park” they put the sentinel tokens in "cute dog" and my question is why this words election? I can take 1 token forever?
           - In each sentence I must start using the sentinel token number 1?

Thank you in advance! :)

**Comment by amlarraz** [comment]
__UPDATE:__

I'm trying to make my own masking_function for this task, here I leave you the code:

```
import random

def enmascarate(sentence, tokenizer, percent=0.15):
    """Args:
    - sentece: NO tokenized sentence.
    - tokenizer: tokenizer ti use during training
    - percent: Percentage of masked tokens in input_ids (remember, in target_ids the percentage will be 1-percent)
    """   
    tokenized_sentence = tokenizer.encode(sentence)
    idxs = list(range(len(tokenized_sentence)))   
    idxs_2_mask = sorted(random.sample(range(len(tokenized_sentence)), 
                                       int(len(tokenized_sentence)*percent)))
    
    idxs_nomask = [j for j in idxs if j not in idxs_2_mask]
    
    input_ids = tokenized_sentence.copy()
    label_ids = tokenized_sentence.copy()
    del tokenized_sentence  
    #print('PRE-MASKED:')
    #print('INPUT: {}'.format(tokenizer.convert_ids_to_tokens(input_ids)))
    #print('LABEL: {}'.format(tokenizer.convert_ids_to_tokens(label_ids)))

    for i in range(len(tokenized_sentence)):
        
        if i in idxs_2_mask:
            sentinel_token = f'<extra_id_{idxs_2_mask.index(i)}>'
            sentinel_token_id = tokenizer.encode(sentinel_token)
            input_ids[i] = sentinel_token_id[0]

        else:
            sentinel_token = f'<extra_id_{idxs_nomask.index(i)}>'
            sentinel_token_id = tokenizer.encode(sentinel_token)
            label_ids[i] = sentinel_token_id[0]
          
    #print('POST-MASKED:')
    #print('INPUT: {}'.format(tokenizer.convert_ids_to_tokens(input_ids)))
    #print('LABEL: {}'.format(tokenizer.convert_ids_to_tokens(label_ids)))
    
    #print(f'% of masked tokens: {len(idxs_2_mask)/len(idxs)}')
    
    return input_ids, label_ids
```

I dont know if it is correct but it generates sequences like the sequences in the examples. What do you think?

**Comment by amlarraz** [comment]
Another question come to my mind, is it neccesary to add the pad token at the beggining of the label in this task too? I'm using the "labels" argument to add the targets_ids to the model, I mean:

`model(input_ids=input_ids, labels=target_ids)`

Thank you in advance!

**Comment by patrickvonplaten** [comment]
Hey @amlarraz,

As far as I know there is no pre-written function or script for unsupervised "sentinel masking" for T5. But it shouldn't be too difficult to do so. The innovation of T5's sentinel masking is exactly that you can mask multiple tokens with a single masking token which has been shown to yield better results as norrmal single token masking (a la BERT). 

So to answer your questions:
1) The data should be pre-processed as described in the paper and in the example in the docs, here: https://huggingface.co/transformers/model_doc/t5.html#training . The forum: http://discuss.huggingface.co/ is probably a better place to ask more specific questions about your code.

2) You don't need to add a padding token to the labels - this is done automatically here: https://github.com/huggingface/transformers/blob/2977bd528f06bada54afcf740219e65afd1c0883/src/transformers/modeling_t5.py#L638

**Comment by amlarraz** [comment]
Hi @patrickvonplaten !

Many thanks for answer me. As you said I've moved the question to teh huggingface forum if there are somebody interested in follow this topic this is the[ link to the conversation.](https://discuss.huggingface.co/t/train-t5-from-scratch/1781?u=amlarraz)

**Comment by Armanasq** [comment]
is there any update on your project?
