### ISSUE TITLE
Seq2seq example for T5 keeps on generating warning

### ISSUE THREAD

**Issue by amanpreet692** [huggingface/transformers#7454]
In the latest version from Master, on running finetune.sh for T5, was getting the following warning continuously:
**Keyword arguments {'src_lang':None,'tgt_lang':None,'add_prefix_space':False} not recognized.**

I found out this is because the translation and BART parameters are being passed to prepare_seq2seq_batch of T5Tokenizer which it cannot handle and the tokenizer in the end spits out warning for unused kwargs.
I made a small change in utils.py to the constructor at https://github.com/huggingface/transformers/blob/9e9a1fb8c75e2ef00fea9c4c0dc511fc0178081c/examples/seq2seq/utils.py#L100:
```python 
        **dataset_kwargs
    ):
        super().__init__()
        self.src_file = Path(data_dir).joinpath(type_path + ".source")
        self.tgt_file = Path(data_dir).joinpath(type_path + ".target")
        self.len_file = Path(data_dir).joinpath(type_path + ".len")
        if os.path.exists(self.len_file):
            self.src_lens = pickle_load(self.len_file)
            self.used_char_len = False
        else:
            self.src_lens = self.get_char_lens(self.src_file)
            self.used_char_len = True
        self.max_source_length = max_source_length
        self.max_target_length = max_target_length
        assert min(self.src_lens) > 0, f"found empty line in {self.src_file}"
        self.tokenizer = tokenizer
        self.prefix = prefix if prefix is not None else ""

        if n_obs is not None:
            self.src_lens = self.src_lens[:n_obs]
        self.pad_token_id = self.tokenizer.pad_token_id
        self.dataset_kwargs = dataset_kwargs
        dataset_kwargs.update({'add_prefix_space' : True} if isinstance(self.tokenizer, BartTokenizer) else {})
```

since src_lang and tgt_lang weren't being used anywhere else other than passing on to prepare_seq2seq_batch as parameters.

While calling the method I used dataset_kwargs as the paremeter which sorted out the issue:
```python
self.tokenizer.prepare_seq2seq_batch(
            [x["src_texts"] for x in batch],
            tgt_texts=[x["tgt_texts"] for x in batch],
            max_length=self.max_source_length,
            max_target_length=self.max_target_length,
            return_tensors="pt",
            **self.dataset_kwargs
        )

```

If this seems reasonable I can raise a PR and check it in?
@sshleifer @patil-suraj

**Comment by sshleifer** [comment]
Yes, great PR! Send it and tag me!
Bonus points for adding a test that used to break but now doesn't maybe to seq2seq/test_datasets.py

**Comment by amanpreet692** [comment]
Here you go! #7470 Added a simple test case as well to test the arguments that would be sent to collate()
