### ISSUE TITLE
Issue with Summary of the tasks - Named Entity Recognition in Docs

### ISSUE THREAD

**Issue by Matt-Munns** [huggingface/transformers#7482]
- `transformers` version: 3.3.1
- Platform: Darwin-19.6.0-x86_64-i386-64bit
- Python version: 3.7.3
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

 examples/token-classification: @stefan-it
 documentation: @sgugger

## Information

I am trying to run the Pytorch version of named entity recognition from the "Summary of the tasks" section in the documentation.

## To reproduce

I'm running the exact example from the docs, but will attach the code below

```
from transformers import AutoModelForTokenClassification, AutoTokenizer

import torch

model = AutoModelForTokenClassification.from_pretrained("dbmdz/bert-large-cased-finetuned-conll03-english")

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

label_list = [
    "O",       # Outside of a named entity
    "B-MISC",  # Beginning of a miscellaneous entity right after another miscellaneous entity
    "I-MISC",  # Miscellaneous entity
    "B-PER",   # Beginning of a person's name right after another person's name
    "I-PER",   # Person's name
    "B-ORG",   # Beginning of an organisation right after another organisation
    "I-ORG",   # Organisation
    "B-LOC",   # Beginning of a location right after another location
    "I-LOC"    # Location
]

sequence = "Hugging Face Inc. is a company based in New York City. Its headquarters are in DUMBO, therefore very" \
           "close to the Manhattan Bridge."

tokens = tokenizer.tokenize(tokenizer.decode(tokenizer.encode(sequence)))

inputs = tokenizer.encode(sequence, return_tensors="pt")

outputs = model(inputs).logits

predictions = torch.argmax(outputs, dim=2)
```

Running this leads to the error: 

```
Traceback (most recent call last):

  File "test.py", line 21, in <module>

    outputs = model(inputs).logits

AttributeError: 'tuple' object has no attribute 'logits'
```

## Expected behavior

I expect this to run successfully and produce predictions for the example sequence. I've run this example before and it succeeded so I'm not sure what's happening differently now. I feel like I'm making a dumb mistake somewhere, but idk. 
Thanks!

Note: 
changing line 21 to 
`outputs = model(inputs)[0]`
seems to lead to the expected output, but this might not be the kind of behavior you all are looking for.

**Comment by sgugger** [comment]
Indeed, this example (and all the others) is missing a `return_dict=True` in the call to `from_pretrained`. Thanks for flagging, the PR mentioned above will fix this.
