### ISSUE TITLE
Tenosrflow Loading the saved Model For GPT2

### ISSUE THREAD

**Issue by santhoshkolloju** [huggingface/transformers#7485]
```py
from time import time
from transformers import TFGPT2LMHeadModel, GPT2Tokenizer
import tensorflow as tf

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = TFGPT2LMHeadModel.from_pretrained('gpt2')

text = "What are you doing after you have finished working?"
generated = tokenizer.encode(text)
context = tf.constant([generated])
past = None
start = time()
for i in range(100):
    output, past = model([context, past])
    logits = output[0, -1, :]
    tok = tf.argmax(logits)
    generated.append(tok.numpy())
    context = tf.expand_dims(tf.expand_dims(tok, 0), 0)
sequence = tokenizer.decode(generated)
print(time() - start, sequence)

#save the model 
tf.saved_model.save(model,"temp")

#loading back the model
nm = tf.saved_model.load("temp")
infer = nm.signatures['serving_default']
```
Not able to call the model as shown below

```py
text = "What are you doing after you have finished working?"
generated = tokenizer.encode(text)
context = tf.constant([generated])
past = None
start = time()
for i in range(100):
    output, past = **infer**([context, past])
    logits = output[0, -1, :]
    tok = tf.argmax(logits)
    generated.append(tok.numpy())
    context = tf.expand_dims(tf.expand_dims(tok, 0), 0)
sequence = tokenizer.decode(generated)
print(time() - start, sequence)
```

**Comment by LysandreJik** [comment]
Hi! What's the problem?

**Comment by LysandreJik** [comment]
Could you put the error you had, as well as the environment? i.e., everything asked in the issue template.

**Comment by santhoshkolloju** [comment]
I am running it in colab CPU
`TypeError`                                 Traceback (most recent call last)
<ipython-input-5-0c3c85adea42> in <module>()
      5 start = time()
      6 for i in range(100):
----> 7     output, past = infer([context, past])
      8     logits = output[0, -1, :]
      9     tok = tf.argmax(logits)

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _call_with_flat_signature(self, args, kwargs, cancellation_manager)
   1719         raise TypeError("{}: expected argument #{}(zero-based) to be a Tensor; "
   1720                         "got {} ({})".format(self._flat_signature_summary(), i,
-> 1721                                              type(arg).__name__, str(arg)))
   1722     return self._call_flat(args, self.captured_inputs, cancellation_manager)
   1723 

TypeError: signature_wrapper(input_ids): expected argument #0(zero-based) to be a Tensor; got list ([<tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[2061,  389,  345, 1804,  706,  345,  423, 5201, 1762,   30]],
      dtype=int32)>, None])``

**Comment by jmwoloso** [comment]
What is the resolution for this. Having the same issue.

**Comment by LysandreJik** [comment]
If you can open a new issue with the issue template filled out (environment information, code that fails, expected behavior), then we can help you! Thank you.
