### ISSUE TITLE
quick questions about the `BertModelLMHeadModel`.

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#7495]
Hello,
I have a few questions about the `BertModelLMHeadModel`:

1. Is `BertModelLMHeadModel`  used to conduct the causal language modeling (next token prediction), as it is the case for the `GPT2LMHeadModel`?

2. For `GPT2LMHeadModel`, I can just specify `labels = input_ids` for convenience. I just specify the `labels` in this way for the `BertModelLMHeadModel` as well?

Thanks,

**Comment by zanderbush** [comment]
Bert is a Masked Lanuage Model.
