### ISSUE TITLE
german distilbert not available?

### ISSUE THREAD

**Issue by datistiquo** [huggingface/transformers#7499]
I try using the distilbert-base-german-cased

which is also listed here

https://huggingface.co/transformers/pretrained_models.html

but I get the message that this model is not avaiable. Seems also not here listed?

https://huggingface.co/models?filter=tf,de

Is this just currently the case?

**Comment by datistiquo** [comment]
Or is this model only available for pytorch and not TF?

**Comment by julien-c** [comment]
https://huggingface.co/distilbert-base-german-cased

^^ currently only the Pytorch weights, but you can load into TF pretty easily (follow the README/doc). If needed we can upload the converted TF weights (cc @stefan-it who I believe trained this model? This predates our user/organization namespaces)

**Comment by julien-c** [comment]
And I've added a `de` language tag so that the model is discoverable via https://huggingface.co/models?filter=de&search=distilbert

Thanks for reporting!

**Comment by datistiquo** [comment]
> but you can load into TF pretty easily (follow the README/doc).

COuld you show me where I can read about htis? Cab just find from the getting stared tour:

`bert_model = TFDistilBertModel.from_pretrained('distilbert-base-german-cased', from_tf=False)
`
...but this does not work...

**Comment by julien-c** [comment]
`from_pt=True`?

**Comment by datistiquo** [comment]
Ok, great. So easy.^^
