### ISSUE TITLE
XLNet finetuning

### ISSUE THREAD

**Issue by alshahrani2030** [huggingface/transformers#7519]
I am trying to fine-tune XLNet model and it used work fine but I think huggingface update some classes and I ran through this error:

RuntimeError: Trying to create tensor with negative dimension -1: [-1, 768]

![xlnet](https://user-images.githubusercontent.com/55197626/94844162-d030f780-03eb-11eb-84e4-e72deaaa71ec.PNG)

**Comment by LysandreJik** [comment]
Hello! Could you run `transformers-cli env` in your environment and paste the result here? Thank you!
