### ISSUE TITLE
[GPT-2] How many columns in LM model wte layer are positional embeddings?

### ISSUE THREAD

**Issue by palooney** [huggingface/transformers#7529]
# ❓ Questions & Help

## Details

Hello everyone, I have a quick question about the token weight matrix from the GPT-2 model.

The transformers documentation for GPT-2 indicates that 

> GPT-2 is a model with absolute position embeddings so it’s usually advised to pad the inputs on the right rather than the left.

How many columns in the ```transformer.wte.weight``` are linked to the positional embeddings? For the GPT-2 small model, the size of embedding matrix is (50257, 768), in those 768 columns, how many of them are linked to the positional embeddings?

Many thanks!

**Comment by LysandreJik** [comment]
I would say that none are. The positions are managed by the position embedding: `transformer.wpe.weight`.
