### ISSUE TITLE
ELECTRA - some weights are not loaded

### ISSUE THREAD

**Issue by windionleaf** [huggingface/transformers#7530]
## Environment info
- `transformers` version: 3.3.1
- Platform: Linux-4.15.0-118-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.1 (True)
- Tensorflow version (GPU?): 2.3.0 (True)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
 albert, bert, GPT2, XLM: @LysandreJik 
 Model Cards: @julien-c 

## Information

Model I am using: ELECTRA
I am getting a warning:

> Some weights of the model checkpoint at google/electra-large-discriminator were not used when initializing ElectraModel: ['electra.embeddings_project.weight', 'electra.embeddings_project.bias']
> - This IS expected if you are initializing ElectraModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
> - This IS NOT expected if you are initializing ElectraModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

when using the AutoModel.from_pretrained for google/electra-base-discriminator or google/electra-large-discriminator. There is no warning for google/electra-small-discriminator.

The problem remains the same when directly using the ElectraModel.from_pretrained method.

## To reproduce
```
import transformers
m=transformers.AutoModel.from_pretrained("google/electra-large-discriminator")
# or
m=transformers.AutoModel.from_pretrained("google/electra-base-discriminator")
```

## Expected behavior
no warning

**Comment by LysandreJik** [comment]
Hi, indeed, this can scare users even if there is no actual problem. #7569 will fix this.
