### ISSUE TITLE
Seq2SeqTrainer: missing features

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7543]
These could all be separate issues, if you want to tackle 1 feel free to make a new issue to link to your PR, or not!

1. Configure lr scheduler from the command line https://github.com/huggingface/transformers/blob/master/examples/lightning_base.py#L119
2. Configure dropout, layerdrop from the command line: https://github.com/huggingface/transformers/blob/master/examples/lightning_base.py#L92
3. Logging to wandb seems much less frequent than with the PL integration, which sends train loss to wandb every step.
4. Losses printed out are different than with PL, (seem to be normalized in some way). This merits investigation.
cc @patil-suraj

**Comment by patil-suraj** [comment]
@sshleifer 

2. Done #7532
3. logging can be controlled using `--logging_steps`, default is 500
4. I've also observed this, PL does something different I guess, final metrics should be same IMO
