### ISSUE TITLE
[s2s] label smoothing loss should be normalized

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7546]
by the number of padding tokens in a batch.
Currently, if you change `--train_batch_size` or `--max_target_length`, your loss value will scale wildly, making it hard to compare runs.

**Comment by shngt** [comment]
Hi, I'm interested in taking a look at this. Could you please point out where to start?

**Comment by sshleifer** [comment]
1) On a branch try to add some logic to `label_smoothed_nll_loss` https://github.com/huggingface/transformers/blob/master/examples/seq2seq/utils.py#L35 such that changing `train_batch_size` doesn't wildly change loss.
2) validate (or ask for help validating) that the change does not hurt fine-tuning performance.

The existing code is copied from `fairseq`, so we need to be fairly sure that the change does no harm before we merge it.

cc @patil-suraj
