### ISSUE TITLE
Longformer2Roberta: global_attention_mask is never used

### ISSUE THREAD

**Issue by alexyalunin** [huggingface/transformers#7548]
I was following the Longformer2Roberta tutorial https://github.com/huggingface/transformers/blob/master/model_cards/patrickvonplaten/longformer2roberta-cnn_dailymail-fp16/README.md, it seems like 'global_attention_mask' is never used because this column is removed after https://github.com/huggingface/transformers/blob/9bdce3a4f91c6d53873582b0210e61c92bba8fd3/src/transformers/trainer.py#L301
so you have to add this column to the signature (whatever it is)
https://github.com/huggingface/transformers/blob/9bdce3a4f91c6d53873582b0210e61c92bba8fd3/src/transformers/trainer.py#L324
or set `remove_unused_columns=False` in TrainingArguments 

@patrickvonplaten

**Comment by patrickvonplaten** [comment]
This should be solved soon by the new `generate()` design: https://github.com/huggingface/transformers/pull/6949

**Comment by patrickvonplaten** [comment]
Probably still takes ~1,2 weeks until merge

**Comment by alexyalunin** [comment]
@patrickvonplaten are you sure you mentioned the correct issue? The issue about the `generate()` function was this one #7489 
In the current issue I mention that `global_attention_mask` is never used during training.

**Comment by patrickvonplaten** [comment]
You are 100% correct @alexyalunin :D - sorry my bad! Thanks for linking the correct issue!

**Comment by patrickvonplaten** [comment]
Regarding this issue, I will add more scripts showing how Longformer2Roberta can be trained. I'll pay special attention to your issue here then :-)
