### ISSUE TITLE
RAG: error in outputs = model(input_ids=input_ids, labels=input_dict["labels"])

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#7554]
I tried the following code given in the documentation. 

```
from transformers import RagTokenizer, RagRetriever, RagModel
import torch
tokenizer = RagTokenizer.from_pretrained("facebook/rag-token-base")
retriever = RagRetriever.from_pretrained("facebook/rag-token-base", index_name="exact", use_dummy_dataset=True)
# initialize with RagRetriever to do everything in one forward call
model = RagModel.from_pretrained("facebook/rag-token-base", retriever=retriever)
input_dict = tokenizer.prepare_seq2seq_batch("How many people live in Paris?", "In Paris, there are 10 million people.", return_tensors="pt")
input_ids = input_dict["input_ids"]
outputs = model(input_ids=input_ids, labels=input_dict["labels"])

```
In the last step, it gives the following error. 

**/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'labels'**

**Comment by sgugger** [comment]
Yes, the `RagModel` just contains the bare model and has no training objective (like all HF `XxxModel`). It doesn't take a `labels` argument, the example in the documentation is wrong. Will fix on Monday unless someone beats me to it.
