### ISSUE TITLE
Trainer incorrectly checks pytorch version

### ISSUE THREAD

**Issue by Rexhaif** [huggingface/transformers#7566]
## Environment info

     
- `transformers` version: 3.1.0
- Platform: Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.27
- Python version: 3.8.5
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: yes(not applicable)
- Using distributed or parallel set-up in script?: not applicable

### Who can help
@sgugger and @prajjwal1 (he added it, according to git blame)

## Information

I'm running token classification example on my own data, and i've faced trouble with fp16 training with torch 1.6.0.
Script says that i need apex installed to use fp16 option. However, apex is not required since torch 1.6.0 came out with native amp support. I've dived into trainer code, and found that there is version checking line: https://github.com/huggingface/transformers/blob/99cb924bfb6c4092bed9232bea3c242e27c6911f/src/transformers/trainer.py#L65

Apparently, it is slightly incorrect. There should be <= instead of <. So it will not try to import apex if torch version is greater OR EQUAL to 1.6

```python
import torch
from packaging import version

print(version.parse(torch.__version__) < version.parse("1.6")) # -> False
print(version.parse(torch.__version__) <= version.parse("1.6")) # -> True
```

## To reproduce
1. Install torch 1.6.0(and do not install apex)
2. clone repository
3. cd into examples/token-classification
4. add '--fp16' to the bottom of run.sh script
5. execute run.sh script

## Expected behavior
 Script works well on torch 1.6.0 without apex installed

**Comment by sgugger** [comment]
I am unsure on why you think this test is wrong: if this test is true, we import APEX. So if we check with `<=`, we will then try to import APEX which is exactly what we are trying to avoid.
