### ISSUE TITLE
Import error for MarianMTModel

### ISSUE THREAD

**Issue by brian-o-mars** [huggingface/transformers#7570]
## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...): MarianMTModel

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)
I tried importing MarianMTmodel from transformers and it raised an error message

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)
My own task

## To reproduce

1.from transformers import MarianMTModel, MarianTokenizer
2.
3.

## Expected behavior
Imports MarianMTModel correctly

This is the error message I got:
ImportError: cannot import name 'MarianMTModel' from 'transformers' (C:\Users\PRINCE\Anaconda3\envs\Brian's Enviroment\lib\site-packages\transformers\__init__.py)

**Comment by LysandreJik** [comment]
Hi, please fill-in the template or we won't be able to help you.

**Comment by brian-o-mars** [comment]
Hello, I have updated it. Thanks

**Comment by LysandreJik** [comment]
This part is the most important part, please complete it:


> ```
> transformers version:
> Platform:
> Python version:
> PyTorch version (GPU?):
> Tensorflow version (GPU?):
> Using GPU in script?:
> Using distributed or parallel set-up in script?:
> ```
