### ISSUE TITLE
make modified_only_fixup complains about non .py files

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7579]
easy fix @stas00 ?

**Comment by stas00** [comment]
yes, the fix is trivial. Which tool is complaining?

**Comment by sshleifer** [comment]
I was running `make modified_only_fixup` before merging master and `black` was complaining.
But after merging master, there is no complaining.
And I should be using `make fixup`, so this might just be a UserError.

Should we merge the linked PR anyways or wait to see if I run into this again?

**Comment by stas00** [comment]
Indeed, `black` isn't smooth - it picks .py files when you give it a dir, but doesn't do the same if you give it explicit files:
```
$ black Makefile
error: cannot format Makefile: Cannot parse: 1:1: .PHONY: modified_only_fixup extra_quality_checks quality style fixup fix-copies test test-examples docs
Oh no! 💥 💔 💥
1 file failed to reformat.
```
So yes, please merge the linked PR.

**Comment by stas00** [comment]
`make fixup` is just `modified_only_fixup` + `extra_quality_checks` so no user error
