### ISSUE TITLE
BartConfig saving and loading inconsistency

### ISSUE THREAD

**Issue by Liyang90** [huggingface/transformers#7591]
### Who can help

 Bart: @sshleifer
 
## Information

Model I am using (Bert, XLNet ...): Bart

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x ] my own modified scripts: (give details below)

## To reproduce

```
from transformers import BartConfig
config_to_save = BartConfig.from_pretrained('facebook/bart-base', classif_dropout=0.42)
config_to_save.save_pretrained('./')
config_loaded = BartConfig.from_pretrained('./')
assert config_to_save.classif_dropout == config_loaded.classif_dropout, "what?"
```

## Expected behavior

Should raise no error.

**Comment by Liyang90** [comment]
The input argument for `BartConfig.__init__()` should be named `classif_dropout ` instead of `classifier_dropout`

**Comment by sshleifer** [comment]
Great catch, thanks!
