### ISSUE TITLE
Does tokenizer.from_pretrained tokenize text on CPU even a GPU is available?

### ISSUE THREAD

**Issue by BaoshengHeTR** [huggingface/transformers#7601]
# ❓ Questions & Help

## Details
For a tokenizer from `tokenizer = AutoTokenizer.from_pretrained(model_name)`, if `tokenizer.encode_plus(text)` works on CPUs even a GPU is available. I tried to run such code on a AWS GPU machine instance, but found GPUs are totally not used.
Thanks.

**Comment by LysandreJik** [comment]
Hi, indeed GPUs are not used when doing tokenization. There are no matrix operations and there's no need for heavy parallelization, so no need to rely on GPUs for this operation.
