### ISSUE TITLE
way to make inference Zero Shot pipeline faster?

### ISSUE THREAD

**Issue by acul3** [huggingface/transformers#7604]
Hi 
Can you guys give me tips how to make Zero Shot pipeline inference faster?

My current approach right now is reducing the model size/parameter 
(trying to train "base model" instead of "large model)

Is there another approach?

CCing @joeddav

**Comment by joeddav** [comment]
Closing this and moving the conversation (w/ my answer) to [your topic in the forums](https://discuss.huggingface.co/t/way-to-make-inference-zero-shot-pipeline-faster/1384/2?u=joeddav).
