### ISSUE TITLE
Help loading BioBERT weights

### ISSUE THREAD

**Issue by happypanda5** [huggingface/transformers#761]
I have completed the following:

**1. Downloaded pretrained BioBERT weights from their current release**

**2. Convert TensorFlow checkpoints into Pytorch weights bin file using the following code**

import os

os.system( ' pytorch_pretrained_bert convert_tf_checkpoint_to_pytorch \
  "/content/biobert_v1.1_pubmed/model.ckpt.index" \
  "/content/biobert_v1.1_pubmed/bert_config.json" \
  "/content/biobert_pytorch.bin"            ' )

`
**3. I then tried to test whether I can load these weights. In order to do so, I tried the following code**

state_dict = torch.load( "/content/biobert_pytorch.bin" )
model.load_state_dict(state_dict)

**but I get the error**

> IncompatibleKeys(missing_keys=[], unexpected_keys=[])

***Please guide me***

**Comment by davidefiocco** [comment]
Not really providing a solution here, but have you considered https://github.com/allenai/scibert instead?
AllenAI provides PyTorch weights, and through tests they claim their model is superior https://arxiv.org/pdf/1903.10676.pdf

**Comment by Santosh-Gupta** [comment]
Hello, I am trying to figure out how to load the SciBert weights. I see that you can use

```
# Simple serialization for models and tokenizers
model.save_pretrained('./directory/to/save/')  # save
model = model_class.from_pretrained('./directory/to/save/')  # re-load
tokenizer.save_pretrained('./directory/to/save/')  # save
```

So my guess is to download them from here
https://github.com/allenai/scibert#pytorch-models

Unzip them, then point to that directory

```
model = model_class.from_pretrained('DIRECTORY/TO/DOWNLOADED/UNZIPPED/SCIBERT')  
```

Or, is there a bit more to it?
