### ISSUE TITLE
SquadProcessor: Wrong reference name/filename in docstring

### ISSUE THREAD

**Issue by phiyodr** [huggingface/transformers#7613]
As the docstring of the function `get_train_examples()` refers to  `train-v1.1.json`/`train-v2.0.json`, I guess `get_dev_examples()` should refer to `dev-v1.1.json`/`dev-v2.0.json` (but refers to `train-v1.1.json`/`train-v2.0.json`):

https://github.com/huggingface/transformers/blob/aa6c3c14b4ff8fbd5d40b100f4aae71fb359d6ae/src/transformers/data/processors/squad.py#L610-L617

**Comment by LysandreJik** [comment]
Indeed! Do you want to open a PR fixing the doc?

**Comment by phiyodr** [comment]
Yes, I can do that. :)
