### ISSUE TITLE
Free Inference API Not Accessible

### ISSUE THREAD

**Issue by ncoop57** [huggingface/transformers#7624]
Hi, I attempted to use the free version of the Model Hub's Inference API. However, it is not working for me anymore:

![image](https://user-images.githubusercontent.com/7613470/95273777-e7b81800-0811-11eb-8090-800188be768f.png)

I do have an account and I am signed in when I get the above message. I also have done my email verification as well. Also, when I try to send a POST request using curl with my API token, I get a 503 error.

I was able to successfully use the free version on October 4th, 2020 and so I was wondering, is this a bug or is the free version no longer available?

**Comment by julien-c** [comment]
Hi Nathan, can you send us a quick email to api-enterprise@huggingface.co? 

The free version of the Hub's Inference API is still up, but maybe you've hit the rate limiting?

**Comment by ncoop57** [comment]
Resolved. Ended up being a misinterpretation of my part on error codes that HF's API produces.
