### ISSUE TITLE
The newly added config decoder_start_token_id for bart-base model is wrong?

### ISSUE THREAD

**Issue by FomalhautB** [huggingface/transformers#7628]
The new config file for `bart-base` has been updated on October 5.th.  The new config file looks like the following:
```
{
  ...
  "bos_token_id": 0,
  ...
  "decoder_start_token_id": 2,
  ...
  "eos_token_id": 2,
  ...
}
```

the `decoder_start_token_id` was added newly, it wasn't there before. But as far I understand, the `decoder_start_token_id` should be `bos_token_id` as default . The newly added config-line changed the behavior for the `generate` function.

**Comment by FomalhautB** [comment]
A similar problem is here [#5212](https://github.com/huggingface/transformers/issues/5212)

**Comment by sshleifer** [comment]
Moved there.
