### ISSUE TITLE
Is there a fine-tuning script for DPR?

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#7631]
It would be nice to have a fine-tuning script for DPR.

**Comment by patrickvonplaten** [comment]
Hey @shamanez - I don't think there is a fine-tuning script for DPR at the moment, but we always welcome contributions as such! @lhoestq might have more information.

**Comment by shamanez** [comment]
I just have one more question about the DPR model used in RAG (specially the **Doc-Encoder network**).

Is the **doc-encoder**  pretrained with a 21-million Wikipedia dump as mentioned in the DPR paper?

**Comment by lhoestq** [comment]
The DPR encoders (context encoder and question encoder) in RAG are pretrained BERT that were fine-tuned for retrieval on the question/answers pairs of Natural Questions (and other datasets depending on the setup) using retrieved passages from the 21 million passages Wikipedia dump. In the library, the DPR encoders are the one trained on NQ.

**Comment by shamanez** [comment]
Thanks a lot. So can I use these encoders to ginetune the rag on customized
document settings given the fact that question encoder also get fine-tuned.

**Comment by lhoestq** [comment]
Yes you can fine-tune it on your documents. During RAG fine-tuning both the generator and the question encoder are updated.

**Comment by shamanez** [comment]
Thanks :). So finally what is the best way to arrange customized set of
documents?

**Comment by lhoestq** [comment]
You'll find all the info at https://github.com/huggingface/transformers/tree/master/examples/rag#finetuning :)

**Comment by shamanez** [comment]
Amazing. Thanks a lot

**Comment by shamanez** [comment]
I kind of checked the finetuning script. It shows how to train for custom
datasets. What I don't  understand is how should I use my own set of
documents other that wikipedia's dumps.

**Comment by lhoestq** [comment]
Oh I see. In that case you have to build the RAG knowledge source. We haven't released a code example to do so yet but we're discussing it in #7462

**Comment by shamanez** [comment]
Ok will follow it.
