### ISSUE TITLE
Is is possible to fine-tune GPT2 on downstream tasks currently?

### ISSUE THREAD

**Issue by shizhediao** [huggingface/transformers#765]
Is is possible to fine-tune GPT2 on downstream tasks currently?

**Comment by thomwolf** [comment]
Yes we could add this. You mean tasks like GLUE or SQuAD?

**Comment by shizhediao** [comment]
> Yes we could add this. You mean tasks like GLUE or SQuAD?

Yes! exactly!
Please add this, thanks!

**Comment by experiencor** [comment]
@thomwolf Are you still working on the code to finetune the GPT2 language model (not classification task)? Thanks.

**Comment by Rachnog** [comment]
@experiencor @thomwolf also curious about GPT2 LM finetuning issue, thanks!

**Comment by thomwolf** [comment]
We'll add an example for fine-tuning the models (probably refactor the Bert's one at the same time) this month.

**Comment by kishorekumar1505028** [comment]
> We'll add an example for fine-tuning the models (probably refactor the Bert's one at the same time) this month.

Did you add the example ? looking for an example of fine tuning gpt-2 for downstream tasks.

**Comment by izeitak** [comment]
+1. Also interested.
