### ISSUE TITLE
T5 Beam search num_beans always equals 1

### ISSUE THREAD

**Issue by marcoabrate** [huggingface/transformers#7656]
## Environment info

     
- `transformers` version: 3.3.1
- Platform: Debian 10.6
- Python version: 3.8.5
- PyTorch version (GPU?): 1.6
- Tensorflow version (GPU?): N.A.
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help

TextGeneration: @TevenLeScao 
 T5: @patrickvonplaten

## To reproduce

1. load T5 model and tokenizer
```
from transformers import T5ForConditionalGeneration, T5Tokenizer

# initialize the model architecture and weights
model = T5ForConditionalGeneration.from_pretrained("t5-base")

tokenizer = T5Tokenizer.from_pretrained("t5-base")
```
2. prepare input for summarization. i guess the error persists for any given generation task but did not try.
```
article = """article etc etc"""
inputs = tokenizer.encode("summarize: " + article,
                          return_tensors = "pt",
                          max_length = 512, truncation = True)
```
3. attempt beam search
```
model.config.update({"num_beans": 4})
print(model.config.num_beans)
# output is 4 as expected

outputs = model.generate(inputs,
                         max_length = 200,
                         min_length = 100,
                         length_penalty = 5,
                         num_return_sequences = 2,
                         early_stopping = True)
```
or
```
outputs = model.generate(inputs,
                         max_length = 200,
                         min_length = 100,
                         length_penalty = 5,
                         num_beams = 4,
                         num_return_sequences = 2,
                         early_stopping = True)
```

error:

> AssertionError: Greedy decoding will always produce the same output for num_beams == 1 and num_return_sequences > 1. Please set num_return_sequences = 1

as if num_beans == 1, but we set num_beans to 4.

## Expected behavior

the generate function should execute beam search with 4 beams without errors

**Comment by patrickvonplaten** [comment]
Hey @marcoabrate, 

please make sure that you use the correct parameter name `num_beams` instead of `num_beans`. 
When using `num_beams`, I cannot reproduce your error.

**Comment by marcoabrate** [comment]
of course it was that!

thank you
