### ISSUE TITLE
SqueezBert link gives a 404 error

### ISSUE THREAD

**Issue by mockingbirdz** [huggingface/transformers#7657]
The main Readme.md file (https://github.com/huggingface/transformers/blob/master/README.md), the SqueezeBert link (https://huggingface.co/transformers/model_doc/squeezebert.html) gives a "404 - Not Found" Error.

**Comment by sgugger** [comment]
Yes, unfortunately that link will only be live at the next release (for now squeezeBERT is only in master, so only in the master documentation).
@LysandreJik not sure if there is a way to properly fix this unless we add "Check all the links in the README to remove the master" in our release check list.

**Comment by LysandreJik** [comment]
You're right, I don't think there's any other way without over-engineering a feature.
