### ISSUE TITLE
TF Slow test CI

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7664]
I Don't think tf slow tests are run by circleci OR github actions.
Should they be @LysandreJik ?

**Comment by LysandreJik** [comment]
You're correct, it is not currently running as there were some issues setting up both the PT/TF test suites. Will look into it this afternoon.

**Comment by LysandreJik** [comment]
The slow tests in TF take an absurdly long time. I had to stop them from running after ~3.5 hours as it was holding the whole test suite back. Will investigate more on a separate machine and try to skin it down.
