### ISSUE TITLE
Error with running run_language_modeling.py on GCP TPU

### ISSUE THREAD

**Issue by aldazero** [huggingface/transformers#7684]
## Environment info

     
- `transformers` version: 3.3.1
- Platform: GCP
- Python version: 3.6.10 
- PyTorch version (GPU?): 1.6.0
- Tensorflow version (GPU?): - 
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: Yes/NO

### Who can help

@sgugger @LysandreJik
## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ run_language_modeling.py ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [fine tuning BERT on Wikitext103 ] my own task or dataset: (give details below)

## To reproduce

I am trying to fine-tune Bert on the Wikitext-103 dataset by running the example code run_language_modeling.py on Google cloud TPU v3-8 using xla_spawn.py launcher. I tried both num_cores =1 and num_cores > 1, but neither worked properly. 

1. python xla_spawn.py --num_cores 8 \
 run_language_modeling.py \
--model_name_or_path=bert-base-uncased \
--do_train \
--train_data_file\
--do_eval \
--eval_data_file\
--mlm\
--per_device_train_batch_size=4

The full output is long and you can find it [here](https://gofile.io/d/tjovN1). Here is the begining of error message:

Iteration:   0%|          | 1/28026 [00:00<3:41:44,  2.11it/s][A2020-10-09 16:05:45.623409: W
  2449 tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:160] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1602259545.623281190","description":"Error received from peer ipv4:10.48.142.250:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2020-10-09 16:06:09.642115: E    2449 tensorflow/compiler/xla/xla_client/xla_util.cc:76] >>> Dumping Computation 0
2020-10-09 16:06:09.642213: E    2449 tensorflow/compiler/xla/xla_client/xla_util.cc:76] HloModule SyncTensorsGraph.23679, input_output_alias={ {0}: (39, {}, may-alias), {1}: (37, {}, may-alias),
......

## Expected behavior
Running without error!

Thanks for any help.

**Comment by LysandreJik** [comment]
This doesn't seem to be an issue with `transformers` but with your TPU and its communication with your VM. You would probably have more help if you asked over at https://github.com/pytorch/xla

**Comment by aldazero** [comment]
@LysandreJik Thanks for your comment. The problem rooted in the TPU software version. Setting it to `PyTorch-1.6` resolved the issue.
