### ISSUE TITLE
How to get the word embedding  after pre-training ? for example, a embedding matrix

### ISSUE THREAD

**Issue by AI678** [huggingface/transformers#7693]
I am excited on this great model. And I want to get the word embedding . Where shold I find the file from output or should I change to code to do this?

**Comment by LysandreJik** [comment]
It depends of what you understand as "embedding", as it can be ambiguous with transformer models. 

Embeddings can be the embedding matrix, which returns context-less embedding of tokens, that you can obtain with `model.get_input_embeddings()`.

Embeddings can also be understood as the features generated by the base model, which are token embeddings with context (depends on the tokens surrounding the token you're studying). You can simply do a forward pass through the base models (e.g., `BertModel`, `GPT2Model`, etc.) to get these embeddings.
