### ISSUE TITLE
tokenizers dependency warning: `transformers 3.3.1 has requirement tokenizers==0.8.1.rc2, but you'll have tokenizers 0.9.0`

### ISSUE THREAD

**Issue by morganmcg1** [huggingface/transformers#7697]
## Environment info
- `transformers` version: 3.3.1
- Platform: Darwin-19.6.0-x86_64-i386-64bit
- Python version: 3.7.5
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

 tokenizers: @mfuntowicz

## Information

Hey all, it'll probably be fixed soon but when updating to `tokenziers` 0.9.0 with `pip install tokenizers --upgrade` I get:

`ERROR: transformers 3.3.1 has requirement tokenizers==0.8.1.rc2, but you'll have tokenizers 0.9.0 which is incompatible.`

## To reproduce

1. pip Install transformers --upgrade
2. pip install tokenizers --upgrade

## Expected behavior

Expected compatibility between transformers 3.3.1 and tokenizers 0.9.0

**Comment by dciborow** [comment]
Also stumbled upon this package. I was surprised we were forced to add the RC version of tokenizers. I would expect this to be pinned to "0.8.1" or "0.9.1"

**Comment by dciborow** [comment]
https://github.com/huggingface/transformers/pull/7794 to update to release version 0.9.1

**Comment by LysandreJik** [comment]
Hi, we have a strict requirement on `tokenizers==0.8.1rc2`. We're updating it in https://github.com/huggingface/transformers/pull/7659 but the current `transformers` `master` branch will stay pinned until that PR is merged.

Both libraries evolve quickly and generally evolve together, so having a strict `==` dependency is necessary until tokenizers version 1.0.0 is released.
