### ISSUE TITLE
what is the perplexity of distilbert-base-uncased ? 

### ISSUE THREAD

**Issue by OleNet** [huggingface/transformers#7727]
# ❓ Questions & Help

## Details

In the [readme](https://github.com/huggingface/transformers/tree/master/examples/distillation) , it is said that distilbert-base-uncased is pretraind on the same data used to pretrain Bert, so I wonder what is the final perplexity or cross entropy of the pretrain?

**Comment by patrickvonplaten** [comment]
Hey @OleNet ,

You probably have a better chance of getting an anwser by posting your question on the discussion forum here: `http://discuss.huggingface.co/`.
