### ISSUE TITLE
cannot load "layoutlm-base-uncased"

### ISSUE THREAD

**Issue by rzhao6** [huggingface/transformers#7744]
hi, 
im trying to do "LayoutLMTokenizer.from_pretrained('layoutlm-base-uncased')", and got an error saying "OSError: Model name 'layoutlm-base-uncased' was not found in tokenizers model name list (microsoft/layoutlm-base-uncased, microsoft/layoutlm-large-uncased). We assumed 'layoutlm-base-uncased' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url." 
thank you!

- `transformers` version: 3.3.1
- Python version: 3.7.7
- PyTorch version (GPU?): 1.6.0, GPU

@mfuntowicz

**Comment by thomwolf** [comment]
Hi,

Yes the error message is right, you have to add "microsoft/" before the name:
```
LayoutLMTokenizer.from_pretrained('microsoft/layoutlm-base-uncased')
```

**Comment by rzhao6** [comment]
ah i see, i directly used the line in the example here https://huggingface.co/transformers/model_doc/layoutlm.html#layoutlmmodel

thank you for helping!
