### ISSUE TITLE
Update of DialoGPT `max_length`

### ISSUE THREAD

**Issue by guillaume-be** [huggingface/transformers#7764]
### Who can help
@patrickvonplaten 

## Information

Following https://github.com/huggingface/transformers/pull/5516, the DialoGPT models `max_length` has not been updated, and defaults to the `generate` value of 20. This value is very low for a conversational pipeline and would lead to answers that completely ignore the history (truncation happens to ensure enough space is available for the response).

## Expected behavior

- The configuration files (e.g. https://s3.amazonaws.com/models.huggingface.co/bert/microsoft/DialoGPT-medium/config.json) need to store a `max_length` equal to 1000.
- If the suggested config file structure from the PR is adopted, the code should be updated to read this value instead
```json
  "task_specific_params" : {
      "dialogue": { 
          "max_length": 1000
      }
  }
```

**Comment by patrickvonplaten** [comment]
Very true! Thanks for the notification

**Comment by patrickvonplaten** [comment]
Done - note however that the "task" name was `conversational` not `dialogue`
