### ISSUE TITLE
from transformers import RagSequenceForGeneration gives ImportError

### ISSUE THREAD

**Issue by mchari** [huggingface/transformers#7769]
## Environment info

     
- `transformers` version: 3.3.1
- Platform: Linux
- Python version:3.6.3
- PyTorch version (GPU?):
- Tensorflow version (GPU?):2.3.0
- Using GPU in script?:no
- Using distributed or parallel set-up in script?:no

### Who can help
@patrickvonplaten @sgugger 

## Information

Model I am using ():

The problem arises when using:
 

## To reproduce
1.python
>> from transformers import RagSequenceForGeneration           <- RagTokenizer is imported without any errors

## Expected behavior
I shouldn't get 
ImportError: cannot import name 'RagSequenceForGeneration'

**Comment by sgugger** [comment]
You don't have PyTorch installed in your environment. This is a PyTorch model.

**Comment by mchari** [comment]
Indeed , that was the problem.
The code in the example has import torch after the "from transformers import RagSequenceForGeneration,..." statement, so I incorrectly concluded that torch is not needed for the import. Also, that RagTokenizer got imported without errors.
Thanks!
