### ISSUE TITLE
How to create a QA model where the answer can be from the question text as well?

### ISSUE THREAD

**Issue by nrjvarshney** [huggingface/transformers#7770]
# ❓ Questions & Help

## Details

SQuAD QA dataset has questions where the answer is a span in the context, 
How do I create a QA system where the answer string can be from the context or question text?

**Comment by NielsRogge** [comment]
Normally there's no difference. You just provide `[CLS] question [SEP] answer [SEP]` examples to the model, and the `start_positions` and `end_positions` can be indexes of the question.

**Comment by nrjvarshney** [comment]
Yes,
Can you point me to such an implementation?
huggingface Squad Question answering code handles a lot of edge cases like start token should be before the end token, find n best predictions etc. 
@NielsRogge , Is there a simpler implementation for the question answering task?

I found one in the documentation but that doesn't handle the predictions, sanity checks, n_best predictions etc.
