### ISSUE TITLE
How can I tweak the `Longformer` code to control the input of a `Longformer`'s layer?

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#7780]
Hello,
I have asked a similar question on the HuggingFace forum, but I didn't get a clear answer that I was hoping for.
I tried the following to control the input of a `Longformer` layer:
`best_model_longformer.longformer.encoder.layer[layer_index](my_input_hidden_vector)` 

which of course, does not work.

How can I tweak the `Longformer` (or `BERT`) code to control the input of a `Longformer`'s layer?
Would this do the trick?:
```Python

  self_attention_outputs = Longformer_model.LongformerLayer.forward(hidden_states,
        attention_mask=None,
        output_attentions=False)
 Longformer_model.LongformerLayer.ff_chunk(self, self_attention_outputs)
```
But in this case, I don't know how to properly access the `LongformerLayer` class. I don't know if `Longformer_model.LongformerLayer` is the proper way.

I am not a programmer and I really do need more help on this. I know this can be a bit cumbersome to answer, but could you please help me on this? Your help is much appreciated.

Thank you,

**Comment by sgugger** [comment]
The answer you got on the forum is pretty much the only one we have: copy paste the model code and customize it to your needs. If you're not a programmer, then you will need to learn a bit of Python/PyTorch to do this, but apart from making sure each model file contains the full code of each model, there is little more we can do to help you. There is an API to use the models in the common cases, users are expected to make the customizations they want if that does not suit their needs.

**Comment by h56cho** [comment]
Hello, thank you for your reply.
What is the right way to access `LongformerLayer` class from `my_Longformer_model`?
