### ISSUE TITLE
RAG finetuning - unexpected keyword argument 'early_stop_callback'

### ISSUE THREAD

**Issue by ioannist** [huggingface/transformers#7782]
## Environment info
transformers version: 3.3.1
Platform: Ubuntu
Python version:3.6.12
PyTorch version (GPU: yes): 1.6.0
Using GPU in script?: 1 gpu
Using distributed or parallel set-up in script?: no

### Who can help
@patrickvonplaten @sgugger
 
## Information
model name: facebook/rag-token-base

The problem arises when using:
* [x ] the official example scripts: (give details below)

The tasks I am working on is:
* [x ] my own task or dataset: (give details below)

## To reproduce
Call finetune ona  rag model
`python examples/rag/finetune.py --data_dir=$(pwd)/examples/rag/ioannis-data --output_dir $(pwd)/examples/rag/ioannis-output --model_name_or_path=facebook/rag-token-base --model_type rag_sequence --fp16 --gpus 1`

```
Traceback (most recent call last):
  File "examples/rag/finetune.py", line 469, in <module>
    main(args)
  File "examples/rag/finetune.py", line 442, in main
    logger=logger,
  File "/home/ioannis/Desktop/transformers/examples/lightning_base.py", line 379, in generic_train
    **train_params,
  File "/home/ioannis/anaconda3/envs/transformers/lib/python3.6/site-packages/pytorch_lightning/trainer/properties.py", line 122, in from_argparse_args
    return argparse_utils.from_argparse_args(cls, args, **kwargs)
  File "/home/ioannis/anaconda3/envs/transformers/lib/python3.6/site-packages/pytorch_lightning/utilities/argparse_utils.py", line 50, in from_argparse_args
    return cls(**trainer_kwargs)
  File "/home/ioannis/anaconda3/envs/transformers/lib/python3.6/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 41, in overwrite_by_env_vars
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'early_stop_callback'
```

I noticed a variable named early_stopping_callback in finetune.py. A typo perhaps?

**Comment by bharathc346** [comment]
If you don't need early stopping just comment out `early_stop_callback=early_stopping_callback` on line 379 of `/home/ioannis/Desktop/transformers/examples/lightning_base.py`. You should be able to run your script.

I think lightning may have changed their api

**Comment by ioannist** [comment]
I uninstalled and installed pytorch_lightning 0.9.0 and it worked. During a fresh install and git pull I noticed that the two libraries missing were gitpython and lightning so I just installed their latest versions.

Unfortunately, the script runs for a couple minutes and the ends without any warnings or errors at:
```
loading file https://s3.amazonaws.com/models.huggingface.co/bert/facebook/rag-sequence-base/generator_tokenizer/tokenizer_config.json from cache at /home/ioannis/.cache/torch/transformers/e5f72dc4c0b1ba585d7afb7fa5e3e52ff0e1f101e49572e2caaf38fab070d4d6.d596a549211eb890d3bb341f3a03307b199bc2d5ed81b3451618cbcb04d1f1bc
loading file https://s3.amazonaws.com/models.huggingface.co/bert/facebook/rag-sequence-base/generator_tokenizer/tokenizer.json from cache at None
GPU available: True, used: True
INFO:lightning:GPU available: True, used: True
TPU available: False, using: 0 TPU cores
INFO:lightning:TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]
INFO:lightning:CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.
INFO:lightning:Using native 16bit precision.
```

I don't get any killed warnings but the only files produced in output dir are
```
git_log.json
hparams.pkl
```

I have a 1080Ti and 16GB of ram. If resources are the problem, what machine do you suggest to finetune on? I can get an AWS server to experiment.

Thanks!!

**Comment by ioannist** [comment]
Awesome! I manually installed pytorch_lightning and gitpython as they were not included in the transformers installation and the rag requirements file.
