### ISSUE TITLE
BertForSequenceClassification  -> TFBertForSequenceClassification causes 'bert.embeddings.position_ids' not used error

### ISSUE THREAD

**Issue by dslim23** [huggingface/transformers#7797]
## Environment info

     
- `transformers` version: 3.3.1
- Platform: Linux-4.9.0-13-amd64-x86_64-with-debian-9.13
- Python version: 3.7.8
- PyTorch version (GPU?): 1.4.0 (True)
- Tensorflow version (GPU?): 2.3.1 (True)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

## Information

Model I am using (Bert, XLNet ...):

```
from transformers import BertTokenizer, TFBertModel, TFBertForSequenceClassification,BertForSequenceClassification
import tensorflow as tf

tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
model = TFBertForSequenceClassification.from_pretrained('output', from_pt=True)

```

I'm loading TFBertForSequenceClassification from a BertForSequenceClassification pytorch SavedModel and get this error: 

`Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForSequenceClassification: ['bert.embeddings.position_ids']`

I've done this before with this exact model and not had these issues.

**Comment by dslim23** [comment]
ah looks like this fix should work for BERT as well? https://github.com/huggingface/transformers/pull/6063

I can go ahead and open a PR if that sounds good 
@LysandreJik

**Comment by doguaraci** [comment]
Hi, I'm still getting this warning on version 4.3.2,
