### ISSUE TITLE
Support for custom data_collator in Trainer.train() with datasets.Dataset

### ISSUE THREAD

**Issue by kaletap** [huggingface/transformers#7823]
# 🚀 Feature request

Currently (transformers==3.3.1) Trainer removes unknown columns (not present in forward method of a model) from datasets.Dataset object. It prevents using custom DataCollator in `.train` method since it doesn't have columns that one would want to use. 

I would be interested in an option to not remove unknown columns and allow user to handle them in DataCollator (or provide their own DataLoaders to the train method).

## Motivation
The example code I was trying to use for training looks like this:
```
from typing import List

from datasets import load_dataset
from transformers import RobertaForSequenceClassification, RobertaTokenizer, Trainer


tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = RobertaForSequenceClassification.from_pretrained('roberta-base', return_dict=True)

train_dataset = load_dataset("yelp_polarity", split="train")
val_dataset = load_dataset("yelp_polarity", split="test")

class DataCollator:
    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        
    def __call__(self, examples: List[dict]):
        labels = [example['label'] for example in examples]
        texts = [example['text'] for example in examples]
        tokenizer_output = self.tokenizer(texts, truncation=True, padding=True)
        tokenizer_output['input_ids'] = torch.tensor(tokenizer_output['input_ids'])
        tokenizer_output['attention_mask'] = torch.tensor(tokenizer_output['attention_mask'])
        output_dict = dict(labels=labels, **tokenizer_output)
        return output_dict
    
data_collator = DataCollator(tokenizer)

trainer = Trainer(
    model=model,                   # the instantiated 🤗 Transformers model to be trained
    train_dataset=train_dataset,   # training dataset
    eval_dataset=val_dataset,      # evaluation dataset
    data_collator=data_collator    # problem with removing unwanted columns by transformers.Trainer code. Doesn't really work, is it a bug?
)

trainer.train()
```
(with `trainer.train()` not working)

## Your contribution
Before trying to fix things, I would be interested to learn if there is a suggested alternative way of doing that?

**Comment by sgugger** [comment]
Just set `remove_unused_columns=False` in your `TrainingArguments` to disable that behavior.

**Comment by kaletap** [comment]
Great, I completely missed that! Thanks.

**Comment by etoilestar** [comment]
hello,when I use my own data_collator, I got TypeError: Qwen2Model.forward() got an unexpected keyword argument 'labels', could you tell me why?
