### ISSUE TITLE
can't set evaluation_strategy to "epoch"

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/transformers#7873]
## Environment info

- `transformers` version: 3.3.1

### Who can help
@sgugger 

## Information
Seems like we can't use the evaluation_strategy=epoch option. The default value of evaluate_during_training is boolean (False). In transformers/training_args.py, __post_init__ function, there is a check - `if self.evaluate_during_training is not None:` (line 326). If I'm not mistaken, it will always result in True. I think that if you change the line into `if self.evaluate_during_training:` the problem will be solved.

Thank you so much for your awesome work :)

**Comment by sgugger** [comment]
This has been done already, see [here](https://github.com/huggingface/transformers/blob/master/src/transformers/training_args.py#L335). But you need to install from source for that, since the change is recent,
