### ISSUE TITLE
Issue with XLM-R for multiple-choice questions 

### ISSUE THREAD

**Issue by danyaljj** [huggingface/transformers#7892]
Hi there, 

I am not able to reasonable numbers with XLM models ("xlm-roberta-base" "xlm-roberta-large") when I test them on [multiple choice questions](https://github.com/huggingface/transformers/tree/master/examples/multiple-choice). 

I suspect that it's related to issue #7774. 

## Environment info

     
- `transformers` version: 3.3.1
- Platform: Ubuntu 
- Python version: 3.7 
- PyTorch version (GPU?): 3.6.0 (yes) 
- Tensorflow version (GPU?): 
- Using GPU in script?: yes 
- Using distributed or parallel set-up in script?:

### Who can help
@LysandreJik  @sgugger @VictorSanh

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

Here is the script you can try,  based on [these instructions](https://github.com/huggingface/transformers/tree/master/examples/multiple-choice): 
```
export SWAG_DIR=/path/to/swag_data_dir
python ./examples/multiple-choice/run_multiple_choice.py \
--task_name swag \
--model_name_or_path xlm-roberta-base \
--do_train \
--do_eval \
--data_dir $SWAG_DIR \
--learning_rate 5e-5 \
--num_train_epochs 3 \
--max_seq_length 80 \
--output_dir models_bert/swag_base \
--per_gpu_eval_batch_size=16 \
--per_device_train_batch_size=16 \
--gradient_accumulation_steps 2 \
--overwrite_output
```

It should give you under 30%  -- near random.

**Comment by LysandreJik** [comment]
Thanks for reporting, will investigate.

**Comment by yuchenlin** [comment]
Hi @danyaljj  and @LysandreJik I have the same issue. Are there any suggestions for running xlm-r (base/large) with multiple-choice qa?
