### ISSUE TITLE
pip install transformers by default install 2.5.1

### ISSUE THREAD

**Issue by guoxuxu** [huggingface/transformers#7893]
## Environment info

     

https://huggingface.co/transformers/installation.html

Running '''pip install transformers''' by default installs 2.5.1
Could you also specify TensorFlow CPU or GPU version should be installed

- `transformers` version:
- Platform:
- Python version: 3.7.4
- PyTorch version (GPU?): yes
- Tensorflow version (GPU?): 2.2.0
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: 

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by LysandreJik** [comment]
Running `pip install transformers` installs the latest version for me. Which pip version are you running on?

You can install both cpu or gpu for tensorflow, if you want to run on a cpu or a gpu.
