### ISSUE TITLE
[Model] M2M-100 Multilingual machine translation

### ISSUE THREAD

**Issue by flozi00** [huggingface/transformers#7908]
# 🌟 New model addition

## Model description
Facebook AI is introducing, 
M2M-100
 the first multilingual machine translation (MMT) model that translates between any pair of 100 languages without relying on English data.

## Open source status

* [x] the model implementation is available: (give details)  https://github.com/pytorch/fairseq/tree/master/examples/m2m_100?fbclid=IwAR2Oqew-PAwZpTmHMrq_yiXN2dwdzzbTMZ-4HfbNKfdoZ_M5TpQiPY3dYFo
* [x] the model weights are available: (give details) https://dl.fbaipublicfiles.com/m2m_100/12b_last_checkpoint.pt
* [ ] who are the authors: (mention them, if possible by @gh-username)

**Comment by Bachstelze** [comment]
This model is very big. Is there a good way to prune it?

**Comment by sshleifer** [comment]
Moving to #8054 which is a duplicate (that I created)!

**Comment by robotsp** [comment]
> This model is very big. Is there a good way to prune it?

@Bachstelze Did you find any ways to distill or prune such a large model?

**Comment by Bachstelze** [comment]
@robotsp 
There is a smaller version: https://huggingface.co/alirezamsh/small100
[SMaLL-100: Introducing Shallow Multilingual Machine Translation Model for Low-Resource Languages](https://aclanthology.org/2022.emnlp-main.571.pdf)
