### ISSUE TITLE
Access bert output with output_hidden_states=True  of TFBertForSequenceClassification fails

### ISSUE THREAD

**Issue by datistiquo** [huggingface/transformers#7940]
Hey,

I want to access the output of the main bert model inside the TFBertForSequenceClassification model with output_hidden_states :

`bert_model = TFBertForSequenceClassification.from_pretrained('bert-base-german-cased', output_hidden_states=True)
`
then 

```
print(bert_model.summary())
print(bert_model.get_layer("bert").output)
print(bert_model.layers[0].output[2]) ->yields error
```

bert_model.get_layer("bert").output gives just the 2 outputs for last_hidden_state and pooled_output but the hiden_states are missing.

Why are the hidden_sates not available though I set output_hidden_states=True ?

**Comment by LysandreJik** [comment]
Hello! Could you provide your software versions so that I may investigate?

I get an error earlier: `print(bert_model.get_layer("bert").output)`:
```
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/home/lysandre/Workspaces/Python/transformers/.env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2105, in output
    raise AttributeError('Layer ' + self.name + ' has no inbound nodes.')
AttributeError: Layer bert has no inbound nodes.
```

**Comment by datistiquo** [comment]
Actually I found weird things, because previously it worked, but after a windows update I think my version of the transformer librry was set back somehow. Because I used version 3.0.2, and there there was no output at all of the hidden states. But now for the latest stable version (3.4) it works.

**Comment by LysandreJik** [comment]
Glad to hear it!
