### ISSUE TITLE
T5 on multiple datasets

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#7956]
Hi Everyone,
Is there an example showing how to run T5 on multiple datasets? Greatly appreciated.
thanks.
Best
Rabeeh

**Comment by LysandreJik** [comment]
pinging the T5 master @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @rabeehk - not sure about that. You can check the T5 notebooks we provide or `https://discuss.huggingface.co/`.

**Comment by rabeehk** [comment]
Hi
I could not find notebooks in the link you said.
I am looking for a way to train multiple tasks at once in T5, similar to
this script:
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/hf_model.py
thanks for your help.
Best
Rabeeh
