### ISSUE TITLE
dropping "," in date because of Tokenization

### ISSUE THREAD

**Issue by vkaul11** [huggingface/transformers#7957]
I had my model where "May 7, 2020" is split like this
`['▁may', b'\xe2\x96\x818', ',', '▁2017']`
 I saw that this is a problem here. Any reason why this code was thrown in for bytes string insertion where we have a comma in the token of len > 1? 
```
for piece in pieces:
            if len(piece) > 1 and piece[-1] == str(",") and piece[-2].isdigit():
                cur_pieces = self.sp_model.EncodeAsPieces(piece[:-1].replace(SPIECE_UNDERLINE, ""))
                if piece[0] != SPIECE_UNDERLINE and cur_pieces[0][0] == SPIECE_UNDERLINE:
                    if len(cur_pieces[0]) == 1:
                        cur_pieces = cur_pieces[1:]
                    else:
                        cur_pieces[0] = cur_pieces[0][1:]
                cur_pieces.append(piece[-1])
                new_pieces.extend(cur_pieces)
            else:
                new_pieces.append(piece)

        return new_pieces
```

**Comment by LysandreJik** [comment]
Hi, I'm sorry but I really don't understand what the issue is. Could you clarify?

**Comment by thomwolf** [comment]
I think this comes from the original Albert tokenization, maybe you want to ask on google repository about this?
https://github.com/google-research/albert/blob/master/tokenization.py#L67
