### ISSUE TITLE
T5-large on multiple gpus.

### ISSUE THREAD

**Issue by Palipoor** [huggingface/transformers#7959]
Hi! I'm trying to fine-tune a T5-large on multiple gpus, so I basically use `torch.nn.DataParallel`, but when I get the output of the model which contains the loss and I do `loss.mean().backward()` I run into `cuda out of memory` as I think the loss is just on the first gpu and that's taken. What should I do?

**Comment by patrickvonplaten** [comment]
For OOM errors, I guess you need to reduce batch_size or parallelize over more GPUs.
