### ISSUE TITLE
Should update version requirement for scipy in 'examples\\distillation\\requirements.txt'?

### ISSUE THREAD

**Issue by suliuzh** [huggingface/transformers#7967]
There are inconsistent  version requirements for scipy in 'examples\\distillation\\requirements.txt' and 'examples\\movement-pruning\\requirements.txt'. Fixed version **1.3.1** in 'examples\\distillation\\requirements.txt' is not in the version range in **'>=1.4.1'** in  'examples\\movement-pruning\\requirements.txt'.
![image](https://user-images.githubusercontent.com/27858725/96845824-b1ba9b00-1483-11eb-9538-5c241ba3d00d.png)
**Solution**
I am wondering if it is necessary to update the version requirement in 'examples\\distillation\\requirements.txt' to be consistent. Fixed version can often cause conflict.

**Comment by LysandreJik** [comment]
Sure, do you want to open a PR?

**Comment by LysandreJik** [comment]
@VictorSanh what do you think?
