### ISSUE TITLE
BertTokenizer's add_token won't add token

### ISSUE THREAD

**Issue by HenryPaik1** [huggingface/transformers#7994]
`add_token` actually won't add token. Please refer to the code below:
```
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)
tokenizer.vocab_size
>>30522

tokenizer.add_tokens(new_tokens=['[SUBJ]', '[OBJ]'], special_tokens=True)
>>2

tokenizer.vocab['[OBJ]']
>> KeyError: '[OBJ]'

tokenizer.vocab_size
>>30522 # not changed

tokenizer.tokenize('[OBJ]')
>>['[', 'ob', '##j', ']'] # expected: '[OBJ]'
```

**Comment by HenryPaik1** [comment]
It seems not work until I save the new tokenizer. I close the issue.

**Comment by johnsonice** [comment]
looks like tokenizer.vocab_size does not update after add tokens. but len(tokenizer) shows correct number

**Comment by LysandreJik** [comment]
Yes, the `vocab_size` only contains the information relative to the initial vocabulary. You can find the added tokens either in `tokenizer.get_added_vocab()`, which returns the dictionary, or `tokenizer.added_tokens_encoder`, which returns the amount of added tokens.
