### ISSUE TITLE
tutorial document

### ISSUE THREAD

**Issue by jc-hou** [huggingface/transformers#8018]
In the Translation section in https://huggingface.co/transformers/task_summary.html
"
Here is an example of doing translation using a model and a tokenizer. The process is the following:
1.Instantiate a tokenizer and a model from the checkpoint name. Summarization is usually done using an encoder-decoder model, such as Bart or T5.
2.Define the article that should be summarizaed.
3.Add the T5 specific prefix “translate English to German: “
4.Use the PreTrainedModel.generate() method to perform the translation.
"
1 and 2 seemed copies from Summarization section and not be modified accordingly.

**Comment by LysandreJik** [comment]
You're correct! @patrickvonplaten, git blame shows you as the author, want to fix?
