### ISSUE TITLE
fp16+xlnet did not gain any speed increase 

### ISSUE THREAD

**Issue by fyubang** [huggingface/transformers#802]
Hi, 
I tried fp16 + xlnet, it did not work. 
when I set opt_level='O2', the memory was half, but it was much slower than fp32.
when I set opt_level='O1', the memory was original, and it has similar speed with fp32.

Environment: v100, cuda, 10.1, torch 1.1
The environment is ok, because I tried bert + fp16 and it was much faster than fp32.
I thought it is the problem of torch.einsum, but I am not that sure.

I used the code here to test: https://github.com/huggingface/pytorch-transformers/blob/master/examples/run_squad.py

**Comment by thomwolf** [comment]
XLNet makes heavy use of `torch.einsum()` but I'm not sure this method is fp16 compatible.
It's also quite slow currently so maybe in the mid/long-term it would be good to change these einsum to standard matmul. I won't have time to do that soon though.

**Comment by fyubang** [comment]
@thomwolf 
Thanks for your reply, in fact I had tried replace einsum by standard matmul.
For example, I replaced
```python
torch.einsum('ibnd,jbnd->ijbn', a, b)
```
by:
```python
a_tmp = a.permute(1,2,0,3)
b_tmp = b.permute(1,2,3,0)
res = a_tmp.matmul(b_tmp)
res = res.permute(2,3,0,1)
```
but it became even slower than torch.einsum.

**Comment by slayton58** [comment]
As as a suggestion, you can add ```apex.amp.register_half_function(torch, 'einsum')``` somewhere near the top of your driver script (examples/run_squad.py for instance).

This forces `amp` to cast the inputs to einsum to `torch.half` before executing, allowing you to get the perf benefits of fp16 + TensorCores when appropriate.

**Comment by songyuc** [comment]
Hi, @slayton58, could `torch.einsum` be automatically processed by `apex.amp` now?
Your response will be appreciated!
