### ISSUE TITLE
[BUG] Unexpected overflowing_tokens in tokenizer.encode_plus

### ISSUE THREAD

**Issue by wangxinyu0922** [huggingface/transformers#8028]
### Environment info

     
- `transformers` version: 3.4.0
- Platform: Linux
- Python version: 3.7
- PyTorch version (GPU?): 1.3.1
- Tensorflow version (GPU?):
- Using GPU in script?: True
- Using distributed or parallel set-up in script?:

### Who can help

tokenizers: @mfuntowicz 

## Information

When I am using BERT tokenizer, I get unexpected `overflowing_tokens`. Here is a example code to reproduce:

## To reproduce

```
import torch
import transformers
from transformers import AutoTokenizer
import pdb

tokenizer = AutoTokenizer.from_pretrained('bert-base-multilingual-cased')

subtoken_ids_sentence = [x for x in range(1000,1050)]

nr_sentence_parts += 1
encoded_inputs = tokenizer.encode_plus(subtoken_ids_sentence,
                                            max_length=40,
                                            stride=20,
                                            return_overflowing_tokens=True,
                                            truncation=True,
                                            )

print(encoded_inputs['overflowing_tokens'])
```

The output is: `[1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1048, 1047, 1046, 1045, 1044, 1043, 1042, 1041, 1040, 1039, 1038]`

## Expected behavior
The expected behavior I want is: 
`[1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049]`
The current output contains `[1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049]` and an additional reversed Tensor of `[1048, 1047, 1046, 1045, 1044, 1043, 1042, 1041, 1040, 1039, 1038]`, which I think is wrong.

When I dig into the code, I find that:
https://github.com/huggingface/transformers/blob/6b4c617666fd26646d44d54f0c45dfe1332b12ca/src/transformers/tokenization_utils_base.py#L2556-L2564

I wonder why there is a for loop in it and I think I need  `truncation_strategy = TruncationStrategy.ONLY_FIRST`. However, I failed to turn the truncation_stractegy to `only_first` because the code here turn the truncation strategy to `longest_first`.

https://github.com/huggingface/transformers/blob/6b4c617666fd26646d44d54f0c45dfe1332b12ca/src/transformers/tokenization_utils_base.py#L1750-L1759

Can you give me any help?

**Comment by djstrong** [comment]
I confirm the issue. It was ok with transformers 3.0.0, but from 3.1.0 it is changed.

**Comment by djstrong** [comment]
And the code:
https://github.com/huggingface/transformers/blob/6b4c617666fd26646d44d54f0c45dfe1332b12ca/src/transformers/tokenization_utils_base.py#L2558-L2571
looks bugged, despite above: `ids = ids[:-1]` should be `ids = ids[:-window_len]`.

**Comment by LysandreJik** [comment]
Pinging @thomwolf
