### ISSUE TITLE
RAG: Do we need to pretrained the doc-encoder when using a custom dataset?

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#8037]
Now the RAG consists of a [script](https://github.com/huggingface/transformers/blob/master/examples/rag/use_own_knowledge_dataset.py) where we can use a custom dataset other than the wiki-dataset. 

Since, in the fine-tuning phase of the RAG, we do not update the doc-encoder (we update only BART and Question Encoder), what if our custom dataset consists of different distribution compared to the wiki dataset (Ex: medical records)? 

Will it still work?

**Comment by patrickvonplaten** [comment]
Hey @shamanez,

From the paper: https://arxiv.org/pdf/2005.11401.pdf (check part 2.2 - 2.5) it seems like the doc-encoder was never explicitely pre-trained for RAG, but the authors used a pre-trained retriever that "was trained to retrieve documents which
contain answers to TriviaQA [20] questions and Natural Questions [25]." => So you would have to see for yourself if the document encoder is sutiable for your task or not. If it is not suitable you will have to pre-train your own doc encoder and built the index using this document encoder. 

It's a good question though we should probably also put it on the discussion forum: http://discuss.huggingface.co/.

Also pinging @lhoestq  as he can probably provide you with a better answer than I can.

**Comment by lhoestq** [comment]
+1 for Patrick, and I confirm that RAG uses the pretrained doc encoder from DPR.
It would be very interesting to see if the doc encoder handles well documents from specific domains.
Let us know if you plan to test that :)

**Comment by shamanez** [comment]
@patrickvonplaten  @lhoestq 

Ok, I will give it a try and do a comparison for my task. Just need to clarify my pre-training pipeline for DPR in case I need to pre-train the doc encoder.

1. Pre-train the DPR using the FacebookAI [repository](https://github.com/facebookresearch/DPR).
2. Use the custom checkpoint and load it [here](https://github.com/huggingface/transformers/blob/master/examples/rag/finetune.py#L105) (Is there any conversion I need to do before this step)

**Comment by shamanez** [comment]
@lhoestq 

Sorry for spamming. Can you please let me know, whether I can directly use different DPR checkpoints that trained with Facebook repo?

**Comment by lhoestq** [comment]
> @patrickvonplaten @lhoestq
> 
> Ok, I will give it a try and do a comparison for my task. Just need to clarify my pre-training pipeline for DPR in case I need to pre-train the doc encoder.
> 
> 1. Pre-train the DPR using the FacebookAI [repository](https://github.com/facebookresearch/DPR).
> 2. Use the custom checkpoint and load it [here](https://github.com/huggingface/transformers/blob/master/examples/rag/finetune.py#L105) (Is there any conversion I need to do before this step)

Yes that's it. 
To convert the DPR checkpoint from the original repo to transformers you can use the script `src/transformers/convert_dpr_original_checkpoint_to_pytorch.py`

**Comment by shamanez** [comment]
Perfect. Thanks for the clarification  :).
