### ISSUE TITLE
Missing Import

### ISSUE THREAD

**Issue by onaclov2000** [huggingface/transformers#8066]
When trying to run this file:

https://github.com/huggingface/transformers/blob/3a10764574f252591eeaa5bbb10b778f623a4814/examples/language-modeling/run_language_modeling.py#L40

The following error occurs:
````
Traceback (most recent call last):
  File "run_language_modeling.py", line 32, in <module>
    from transformers import (
ImportError: cannot import name 'DataCollatorForWholeWordMask'
````
I attempted to run the following:
````
import transformers
for i in dir(transformers):
    if "data" in i.lower():
        print (i)
````
And I got the following:

````
CsvPipelineDataFormat
DataCollator
DataCollatorForLanguageModeling
DataCollatorForNextSentencePrediction
DataCollatorForPermutationLanguageModeling
DataCollatorForSOP
DataCollatorWithPadding
DataProcessor
GlueDataTrainingArguments                                                            
GlueDataset                                                                          
JsonPipelineDataFormat                                                               
LineByLineTextDataset
LineByLineWithSOPTextDataset                                                        
PipedPipelineDataFormat                                                              
PipelineDataFormat                                                                   
SquadDataTrainingArguments                                                           
SquadDataset                                                                         
TextDataset
TextDatasetForNextSentencePrediction                                                 
data                                                                                 
default_data_collator                                                               
is_datasets_available
````
It appears that the **DataCollatorForWholeWordMask** is not a part of transformers for some reason.

I commented it out and this one also appears to have an issue (I'll list all that complain at the bottom of this post and edit it as I find more)

At this point I commented the below imports out and it is running (well it's downloading one of the models I believe). I'll update if it fails/succeeds.

Missing Imports from transformers:
* DataCollatorForWholeWordMask
* LineByLineWithRefDataset

**Comment by sgugger** [comment]
Remember that the examples you pull from master need a [source install](https://huggingface.co/transformers/installation.html#installing-from-source). If you want the version that runs with the last release, you need to use that tag, here are the [examples for the last release](https://github.com/huggingface/transformers/releases/tag/v3.4.0) (v3.4.0).

**Comment by onaclov2000** [comment]
You make a compelling argument :)
I did a checkout of the v3.4.0 release, and besides dying from a CUDA out of memory, it appears to be working :)
