### ISSUE TITLE
Hope more GPT Chinese pretrained model.

### ISSUE THREAD

**Issue by guotong1988** [huggingface/transformers#8078]
# 🚀 Feature request

Hope more GPT Chinese pretrained model.

![image](https://user-images.githubusercontent.com/4702353/97251450-e0998e00-1842-11eb-9268-9dfa837f6b29.png)

Thank you very much.

**Comment by julien-c** [comment]
Have you checked out the filtered list on the model hub? https://huggingface.co/models?filter=zh

**Comment by guotong1988** [comment]
Thank you!
