### ISSUE TITLE
Reformer implementation in Tensorflow

### ISSUE THREAD

**Issue by gcuder** [huggingface/transformers#8099]
# 🚀 Feature request

Since there is an implementation of the Reformer in Pytorch, my question is if there will be an implementation for Tensorflow too?

**Comment by LysandreJik** [comment]
This would be cool! I don't believe it's on our roadmap currently (cc @patrickvonplaten), but should be part of a general TF overhaul we'll be doing in the coming months.

No date for that yet, but I think you can expect it in the future.

**Comment by patrickvonplaten** [comment]
Could a "Good First Issue"

**Comment by LysandreJik** [comment]
Sounds like a good first project to deep dive in TensorFlow and rip a few hair out in the process :)
