### ISSUE TITLE
[Model] mT5 Cross-Lingual Model

### ISSUE THREAD

**Issue by sumanthd17** [huggingface/transformers#8111]
# 🌟 New model addition

## Model description

Multilingual T5 (mT5) is a massively multilingual pretrained text-to-text transformer model, trained following a similar recipe as T5.

Weights, code are available.

Github Repo: [mT5 Weights and Code](https://github.com/google-research/multilingual-t5)

Paper: [mT5: A massively multilingual pre-trained text-to-text transformer](https://arxiv.org/abs/2010.11934)

## Open source status

* [x] the model implementation is available: [Implementation](https://github.com/google-research/multilingual-t5)
* [x] the model weights are available: [checkpoints](https://github.com/google-research/multilingual-t5#released-model-checkpoints)
* [x] who are the authors: (@craffel, @adarob)

**Comment by julien-c** [comment]
Will be a part of #6285

**Comment by parthplc** [comment]
Hey, @sumanthd17 any update on this?

**Comment by Neuronys** [comment]
@julien-c thanks for your amazing nlp lib. 
When do you plan to support mT5 ?
When #6285 will be release ?
Cheers
Philippe
