### ISSUE TITLE
Documentation code snippet has extra ) after model code 

### ISSUE THREAD

**Issue by bhadreshpsavani** [huggingface/transformers#8112]
Documentation at https://huggingface.co/transformers/model_doc/roberta.html#tfrobertaforsequenceclassification has code snippet

```
>> from transformers import RobertaTokenizer, TFRobertaForSequenceClassification
>> import tensorflow as tf
>> tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
>> model = TFRobertaForSequenceClassification.from_pretrained('roberta-base', return_dict=True))
>> inputs = tokenizer("Hello, my dog is cute", return_tensors="tf")
>> inputs["labels"] = tf.reshape(tf.constant(1), (-1, 1)) # Batch size 1
>> outputs = model(inputs)
>> loss = outputs.loss
>> logits = outputs.logits
```

in the fourth line there is extra `)` at the end.

This is issue is also for other model code snippet as well

**Comment by LysandreJik** [comment]
Hello, this has been fixed on: https://github.com/huggingface/transformers/pull/8082 and is now available in the `master` documentation and will be updated in the next version. Thanks for opening an issue!
