### ISSUE TITLE
How to perform model.predict loop with TFRobertaForSequenceClassification?

### ISSUE THREAD

**Issue by MiriamFarber** [huggingface/transformers#8136]
I'd like to perform inference loop for the following roberta model:

```
model = TFRobertaForSequenceClassification.from_pretrained('roberta-base',return_dict=True,num_labels=2)
```

on a large set of pairs of sentences (couple of hundred thousands). I wanted to use `model.predict` and specify batch size, but there is no way to pass the below inputs (encoded_data is tokenization of the input data) to `model.predict`

```
attention_mask=encoded_data['attention_mask'], 
token_type_ids=encoded_data['token_type_ids']
```

So what is the alternative way to do that?

**Comment by ratthachat** [comment]
Hi, this [Kaggle notebook](https://www.kaggle.com/xhlulu/jigsaw-tpu-xlm-roberta) have a very concise way to efficiently train/predict Huggingface's `XLMRoberta` (which is the same format as `Roberta`) . Hope it help!
