### ISSUE TITLE
Vocab files missing in community pre-trained t5 model

### ISSUE THREAD

**Issue by penatbater** [huggingface/transformers#8141]
## Environment info

     
- `transformers` version: 3.4.0
- Platform: Linux-5.4.0-1028-gcp-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False

### Who can help
Summarization: @sshleifer
 

## Information

I am trying to use the sshleifer/t5-base-cnn for summarization task, but there seems to be an issue with the tokenizer portion. I tried looking at the files part in https://huggingface.co/sshleifer/t5-base-cnn# and there doesn't seem to be a vocab file there.

>tokenizer = AutoTokenizer.from_pretrained("sshleifer/t5-base-cnn")
>model = AutoModelWithLMHead.from_pretrained("sshleifer/t5-base-cnn")

>OSError: Model name 'sshleifer/t5-base-cnn' was not found in tokenizers model name list (t5-small, t5-base, t5-large
, t5-3b, t5-11b). We assumed 'sshleifer/t5-base-cnn' was a path, a model identifier, or url to a directory containin
g vocabulary files named ['spiece.model'] but couldn't find such vocabulary files at this path or url.

**Comment by julien-c** [comment]
I'm guessing you can use the tokenizer from t5-base (https://huggingface.co/t5-base#list-files) but @sshleifer can confirm or infirm

**Comment by penatbater** [comment]
> I'm guessing you can use the tokenizer from t5-base (https://huggingface.co/t5-base#list-files) but @sshleifer can confirm or infirm

This is what I used in the interim. I'm just not sure if there are some implications with using a different tokenizer with the fine-tuned model.

**Comment by sshleifer** [comment]
Correct all t5 tokenizers are identical. There will be no issue.
