### ISSUE TITLE
BertTokenizer loses unicode character

### ISSUE THREAD

**Issue by arvieFrydenlund** [huggingface/transformers#8156]
## Environment info

- `transformers` version: 3.0.2
- Platform: Linux-4.15.0-109-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.4.0 (True)
- Tensorflow version (GPU?): 2.3.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
 @LysandreJik 

## Information

The tokenizer seems to lose a specific unicode character on tokenization.  From the sentence

`General Saprang Kalayanamitr ( Thai : <unk> ่ ง กัลยาณมิตร ;`

from line 2557 of the Wiki02 training dataset, there is a little dot after and above `<unk>`
however the tokenizer produces 

` ['general', 'sap', '##rang', 'kala', '##yana', '##mit', '##r', '(', 'thai', ':', '<', 'un', '##k', '>', 'ง', '[UNK]', ';']`

## To reproduce

`t = BertTokenizer.from_pretrained('bert-base-uncased')`
`o = t.tokenize('General Saprang Kalayanamitr ( Thai : <unk> ่ ง กัลยาณมิตร ;')`
 `o`
`['general', 'sap', '##rang', 'kala', '##yana', '##mit', '##r', '(', 'thai', ':', '<', 'un', '##k', '>', 'ง', '[UNK]', ';']`

## Expected behavior

A subword should be given for the ' ่ ' token.  Otherwise there should be an option to be given a warning for removed characters.

**Comment by lorr1** [comment]
I'm having a similar problem since upgrading to 4.0 where certain unicode characters are being "eaten" even though I set 'use_fast' = False.
