### ISSUE TITLE
EncoderDecoderModel: tie weights between different classes of models

### ISSUE THREAD

**Issue by alexyalunin** [huggingface/transformers#8158]
# 🚀 Feature request

Tie weights between different classes of models, tie embedding matrices, update tutorial.

## Motivation

I have been following the Longformer2Roberta tutorial https://github.com/huggingface/transformers/blob/master/model_cards/patrickvonplaten/longformer2roberta-cnn_dailymail-fp16/README.md and it seems like the crucial part of tying weights is missing.
The EncoderDecoderModel is initialized with "allenai/longformer-base-4096" and "roberta-base", and "allenai/longformer-base-4096" in its turn was initialized from "roberta-base". It seems natural to be able to tie their attention and FFNN weights, although it might be problematic to deal with positional embedding. Anyway, I think one feature that definitely should be implemented is the tying embedding matrices. 

## Your contribution

For now I solve the issue with
```
model.encoder.embeddings.word_embeddings.weight = model.decoder.roberta.embeddings.word_embeddings.weight
```
@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Yeah I think you have a good point here! Was discussing this with @ibeltagy  and I think we should add a `_tie_encoder_decoder_word_embeddings(...)` that does exactly what you suggested. We should probably run this method when initializing an Encoder-Decoder model and if word embeddings are of the same size. We can provide a `tie_encoder_decoder_word_embeds` config params that defaults to True. 

@alexyalunin do you want to try to make a PR for this ? :-)

**Comment by alexyalunin** [comment]
> Yeah I think you have a good point here! Was discussing this with @ibeltagy and I think we should add a `_tie_encoder_decoder_word_embeddings(...)` that does exactly what you suggested. We should probably run this method when initializing an Encoder-Decoder model and if word embeddings are of the same size. We can provide a `tie_encoder_decoder_word_embeds` config params that defaults to True.
> 
> @alexyalunin do you want to try to make a PR for this ? :-)

Ok, let me try this. I will put you in the reviewers.
