### ISSUE TITLE
Possible bug in "trainer" when training "BertForPretraining.from_pretrained()"

### ISSUE THREAD

**Issue by danaludwig** [huggingface/transformers#8174]
## Environment info

     
Environment is colab with GPU enabled.  modules are provided in the Jupyter notebook on Google Drive here:

[https://colab.research.google.com/drive/1UX6NMXA2cHGUtDJwh_U6LL-kyd8Gyt9y?usp=sharing](https://colab.research.google.com/drive/1UX6NMXA2cHGUtDJwh_U6LL-kyd8Gyt9y?usp=sharing)

### Who can help
@sgugger

## Information

Model I am using BERT 
BertForPreTraining.from_pretrained("bert-base-uncased")

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: Error can be reproduced with the Notebook provided above.

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details below)
I am attempting to "fine-tune" bert-base-uncased by training it on additional sentences.  I am unable to do this with Trainer - I get an error message shown in the notebook.

## To reproduce

1. Execute the notebook
2. First example succeeds with model BertLMHeadModel.from_pretrained("bert-base-uncased")
3. Second example fails at train() simply by changing the model to BertForPreTraining.from_pretrained("bert-base-uncased")

The bug is entirely reproduced on the linked Jupyter Notebook above, when run on Google Colab.  The error message is:

RuntimeError: grad can be implicitly created only for scalar outputs

## Expected behavior
The model "BertForPretraining.from_pretrained("bert-base-uncased") should train on the two sentences provided.

If you know a work-around for this bug, I will appreciate it.

Sylvain - good to see you doing interesting work!! - Dana Ludwig (student of fast.ai course and owner of your book)

**Comment by sgugger** [comment]
Hi Dana! I don't think this is a bug. You are not providing `BertForPreTraining` the `nsp_labels` it also requires for training, so it does not compute the loss (and then the rest fails). You should use `DataCollatorForNextSentencePrediction` to have the batches get those labels too (and it might requires using `extDatasetForNextSentencePrediction` with it) or write your own `data_collator`  that will add those labels.

**Comment by danaludwig** [comment]
Hi Sylvain,
Your suggestion did the trick!  I used ‘TextDatasetForNextSentencePrediction’ to build my dataset and ‘DataCollatorForNextSentencePrediction’ for my collator.  It’s training now and the validation loss is getting lower, so everything looks fine.  As you remember, fine-tuning the baseline pre-trained model with new task-specific data was part of your workflow for ULMFIT, so I can imagine this use-case will come up a lot.  If you would like me to clean up my test example notebook, I’d be glad to let you post it in your examples section.  It took me days to get this far, so I’d like to save the next person some time if possible.  Either way you can close the issue.  Thank you! - Dana
