### ISSUE TITLE
AutoTokenizer.from_pretrained function cannot be customized 

### ISSUE THREAD

**Issue by ismymajia** [huggingface/transformers#8177]
A customized tokenizer has been provided in the tokenizer library, so that I can directly use the word segmentation data and vocab in the previous fairseq, but there is AutoTokenizer.from_pretrained function in the transformer, which cannot be customized like the tokenizer library, so I have no choice to directly use fairseq's vocab and word segmentation data in transformer. 

What needs to be done？

**Comment by LysandreJik** [comment]
Hi! Could you provide an example of the usage that you would like to see with the `transformers` library, so that we may see what can be done?

**Comment by thomwolf** [comment]
Is this the same as #8125 ?
