### ISSUE TITLE
trainer.evaluate returns 'epoch' from training

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#8184]
I am training a BERT model: `trainer.train()`

Then I call `evaluate_result = trainer.evaluate(labeled_dataset_test)`

The value of `evaluate_result` looks like this:

```python
{'eval_loss': 0.5908029079437256, 
'eval_acc': 0.8282828282828283, 
'eval_bac': 0.8243021346469622, 
'eval_mcc': 0.7422526698197041, 
'eval_f1_macro': 0.826792009400705, 
'epoch': 3.0, 
'total_flos': 1373653507542624}
```

IMO the dict should not contain `'epoch': 3.0,`. That is the number of epochs from training. It has nothing to do with evaluation...

**Comment by sgugger** [comment]
You can easily  ignore that value though.

The problem is that you won't have it at each eval during the training loop if we don't include it. There could be something smarter there, but it would take time for something that is just purely cosmetic.

**Comment by PhilipMay** [comment]
I added a small PR for improved documentation about this: #8273

**Comment by PhilipMay** [comment]
Closing this since PR was merged.
