### ISSUE TITLE
TensorFlow Longformer model as a saved model with attention outputs

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/transformers#8185]
The TensorFlow implementation of the Longformer model has an issue with using the `tf.saved_model.save` API alongside the `output_attentions=True` configuration attribute. 

The test is skipped currently due to this issue.

**Comment by patrickvonplaten** [comment]
Don't manage to get this test passing even with the new design of #7562 -> the problem to me is that the shape of `attentions` in Longformer depends on the input tensor => so not sure we'll find a good solution here

**Comment by LysandreJik** [comment]
If it can't pass the test defined in the common tests, then the best would be to override the test in the `LongformerModelTester` and do a test to ensure that the correct behavior still works, even if not adhering to the common tests.
