### ISSUE TITLE
TextDataset support for tensorflow?

### ISSUE THREAD

**Issue by mymusise** [huggingface/transformers#8190]
Hey, guys. I find [`TextDataset`](https://github.com/huggingface/transformers/blob/9a21b50614991889f11dbe0743af25923765f9e9/src/transformers/data/datasets/language_modeling.py#L20) and `LineByLineTextDataset` is a great design, it help people build input data more faster. But it's a pity that it only support **pytorch** now. Is there any possible to support **tensorflow**?

**Comment by sgugger** [comment]
There is no plan for that as both those APIs will be deprecated soon. Users should directly use the [Datasets](https://github.com/huggingface/datasets) library which works for both PyTorch and TF. There are examples of how to replicate `TextDataset` and `LineByLineTextDataset` using that library in the new [`run_clm`](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_clm.py) and [`run_mlm`](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_cmm.py) scripts. To convert the datasets to the TF format, just use their `set_format` method (see the [doc here](https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasets.Dataset.set_format)).
