### ISSUE TITLE
Simple import issue for run_clm.py

### ISSUE THREAD

**Issue by arccoxx** [huggingface/transformers#8210]
## Environment info
- `transformers` version: 3.4.0
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.6.0+cu101 (True)
- Tensorflow version (GPU?): 2.3.0 (True)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no
     
other details na on colab not sure how to find them sorry

### Who can help
 @sgugger @TevenLeScao @LysandreJik 
 

## Information

Model I am using (Bert, XLNet ...): GPT2

The problem arises when using:
* [ ] the official example scripts: (give details below)
run_clm.py
* [ ] my own modified scripts: (give details below)
na
The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
language modeling for generation with custom data file
* [ ] my own task or dataset: (give details below)
my own dataset in a file train-4.txt which is line delimited

## To reproduce

1.run this script:
2. !python /content/transformers/examples/language-modeling/run_clm.py \
    --model_name_or_path gpt2-medium \
    --train_file /content/train-4.txt \
    --do_train \
    --output_dir /tmp/test-clm

This is the script: 
!python /content/transformers/examples/language-modeling/run_clm.py \
    --model_name_or_path gpt2-medium \
    --train_file /content/train-4.txt \
    --do_train \
    --output_dir /tmp/test-clm

this is the error:
ImportError: cannot import name 'is_main_process'
## Expected behavior
working language modeling script

'is_main_process' should be importable from transformers.trainer.utils

Thank you!

Will be using this model down stream for some more advanced tasks trying to blow through finetuning so I can get a jump on the fun stuff. Any help would be appreciated, working on an academic art project and fast help would be deeply appreciated (no rush obviously) so creative iteration may commence. Thank you once again!

**Comment by sgugger** [comment]
Hi there, as mentioned in the README of the examples (in bold), you need to install transformers [from source](https://huggingface.co/transformers/installation.html#installing-from-source) to use that script.

**Comment by arccoxx** [comment]
I did thank, you for the rapid reply! Comfortable programmer, files not so much so again thank you for bearing with me. Installed via:

!pip install git+https://github.com/huggingface/transformers.git

**Comment by arccoxx** [comment]
Yep thats the issue sorry for being a moron and this can be closed. Perhaps someone of multicellular intelligence could explain why my !pip git+ solution is insufficient?

Thank you @sgugger

**Comment by sgugger** [comment]
Mmmm, maybe you had the repo cached somewhere and it didn't update to the latest version? Glad your issue is fixed :-)

**Comment by LysandreJik** [comment]
Maybe because you already had `transformers` installed in your environment, in which case you would have to supply the `-U` option to update to the specific version you're targeting

**Comment by savinduekanayake** [comment]
I have a issue of fine-tuning the T5 model(t5-base). 

!python /content/transformers/examples/language-modeling/run_clm.py
--model_name_or_path t5-base
--train_file /content/train.txt
--do_train
--output_dir /tmp/test-clm

This code is not working. How can I fine-tune the t5-base model?
