### ISSUE TITLE
_shift_right when to use

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#8244]
Hi
In modeling_t5 there is a function called shift_right I wonder when it needs to be used, for which tasks? I sometimes see T5 finetuning without using it, not sure when this is suitable to use it thanks

**Comment by patrickvonplaten** [comment]
Hey @rabeehkarimimahabadi, it's a convenience function that is used if `input_ids` and `labels` are provided but no `decoder_input_ids`. In this case this function automatically creates the correct `decoder_input_ids` as described here: https://huggingface.co/transformers/model_doc/t5.html?highlight=t5#training
