### ISSUE TITLE
Disable default sigmoid function for single label classification Inference API

### ISSUE THREAD

**Issue by Jiaxin-Pei** [huggingface/transformers#8259]
# 🚀 Feature request

Allow people to disable the default sigmoid function in TextClassificationPipeline (maybe via model cards?).

## Motivation

When we use the sequence classification model (e.g. RobertaForSequenceClassification) for regression tasks, the output may have different ranges other than [0,1], it would be better to allow configurations for the sigmoid function in TextClassificationPipeline.

**Comment by LysandreJik** [comment]
Hi! Right now the sigmoid function is applied when the pipeline detects that there is a single label. You would like the option to disable the sigmoid function in that case?

**Comment by Jiaxin-Pei** [comment]
@LysandreJik 
Sorry for my late reply.
Yes, cuz when people are doing regression tasks using the single-label SequenceClassification model, the output range depends on the specific task. For example, when predicting age from the text, [0,1] output after a sigmoid function is not a good fit here.

**Comment by LysandreJik** [comment]
Indeed, I understand! I'm adding an option to return the raw outputs in #8328

**Comment by Jiaxin-Pei** [comment]
Thank you! I'm also wondering if this will be reflected by the Inference API? The inference API is using the sequence classification pipeline, therefore the API output on my model page is different from the original model output, which might confuse potential users.

**Comment by julien-c** [comment]
@Jiaxin-Pei see discussion in #8328
