### ISSUE TITLE
Training T5-large model for Question Answering

### ISSUE THREAD

**Issue by dulanafdo** [huggingface/transformers#8288]
Are there are any specific documents that I can follow, to do the training of the t5 model for Question answering?
I found this (https://huggingface.co/transformers/custom_datasets.html#qa-squad) on your website and it is not allowing me to use t5 model instead of DistilBert.

**Comment by patrickvonplaten** [comment]
This notebook should help: https://github.com/patil-suraj/exploring-T5/blob/master/T5_on_TPU.ipynb
