### ISSUE TITLE
Validation data in `run_mlm.py` is the same as train data

### ISSUE THREAD

**Issue by GuillemGSubies** [huggingface/transformers#8295]
Inspecting the script I found the following:

https://github.com/huggingface/transformers/blob/cb966e640b8b9d0f6e9c06c1655d078a917e5196/examples/language-modeling/run_mlm.py#L204

Am I missing something? Otherwise, I could send a PR.

**Comment by sgugger** [comment]
Very good catch! Thanks for pointing it out, the PR mentioned above should fix this.
