### ISSUE TITLE
Running seq2seq_trainer with iterable datasets 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#8310]
Hi
Looking into https://github.com/huggingface/transformers/blob/master/examples/seq2seq/seq2seq_trainer.py line 117, if the dataset is iterative, then the code does not return a distributed sampler so in case one wants to train on TPUs on multiple cores with iterable datasets, I was wondering if you could assist me how I can use the codes for iterable datasets on TPUs
thanks

**Comment by LysandreJik** [comment]
Maybe @patil-suraj has an idea!

**Comment by rabeehkarimimahabadi** [comment]
Hi
I really appreciate assisting me with this question, I am still struggling with it, could you tell me some pointers, how to add the handling capability of iterative datasets to finetune_trainer.py codes. thanks  @patil-suraj
