### ISSUE TITLE
AlbertTransformer head_mask not subscriptable error when not passed

### ISSUE THREAD

**Issue by baeseongsu** [huggingface/transformers#8323]
## Environment info

     
- `transformers` version: 3.4.0
- Platform: Linux version 4.4.0-193-generic / ubuntu
- Python version: 3.6.5
- PyTorch version (GPU?): 1.4.0 (cuda 10.0)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help

@LysandreJik 

## Information
AlbertTransformer has `head_mask` arguments with default value of None. [(modeling_albert.py#L416)](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_albert.py#L416)
But in forward, `head_mask` is indexed by group_idx without checking if head_mask is None. [(modeling_albert.py#L436)](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_albert.py#L436)
So I got the error as below.
(it seems like a similar issue [#1188](https://github.com/huggingface/transformers/issues/1188))

The problem arises when using:
* [-] the official example scripts: (give details below)
* [O] my own modified scripts: (give details below)

The tasks I am working on is:
* [-] an official GLUE/SQUaD task: (give the name)
* [O] my own task or dataset: (give details below)

## To reproduce
```python
from transformers import AlbertTokenizer, AlbertModel

tokenizer = AlbertTokenizer.from_pretrained('albert-base-v2')
model = AlbertModel.from_pretrained('albert-base-v2', return_dict=True)

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
inputs2 = model.embeddings(input_ids=inputs.input_ids,
                 token_type_ids=inputs.token_type_ids,
                 position_ids=None,
                 inputs_embeds=None)
model.encoder(inputs2)
```
error message when i execute the above script.
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-4fc3cd45df51> in <module>()
      9                  position_ids=None,
     10                  inputs_embeds=None)
---> 11 model.encoder(inputs2)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/modeling_albert.py in forward(self, hidden_states, attention_mask, head_mask, output_attentions, output_hidden_states, return_dict)
    434                 hidden_states,
    435                 attention_mask,
--> 436                 head_mask[group_idx * layers_per_group : (group_idx + 1) * layers_per_group],
    437                 output_attentions,
    438                 output_hidden_states,

TypeError: 'NoneType' object is not subscriptable
```

## Expected behavior
`model.encoder(inputs2)` encoder will be output of tensor.
Espeically, shape of the tensor will be (1, 8, 768)

Personally, I think we could add one more line of code before `for loop`
```python
head_mask = [None] * self.config.num_hidden_layers if head_mask is None else head_mask
```

**Comment by baeseongsu** [comment]
@LysandreJik Could I put this issue on PR?

**Comment by harikc456** [comment]
I am facing the same issue while using `transformers 4.5.1`. Is there any workaround for this issue ?

**Comment by baeseongsu** [comment]
Hi, @harikc456 
You can try to modify the source code. https://github.com/huggingface/transformers/blob/master/src/transformers/models/albert/modeling_albert.py#L463
There are no indices in None object (`head_mask` ). 
So you can try like the followings:
```python
head_mask = [None] * self.config.num_hidden_layers if head_mask is None else head_mask
```

**Comment by LysandreJik** [comment]
@baeseongsu, sorry to have missed this. If you still feel like opening a PR, we would welcome it! It seems many models have this issue, as using the encoder call separately isn't something that tends to happen often.

**Comment by baeseongsu** [comment]
Hello, @LysandreJik. Thank you for checking 😄 
Exactly, right. In most of the cases, we don't need to call the internal classes.
Anyway, I will try asap !!

**Comment by harikc456** [comment]
For now, I have able to bypass this issue with the following workaround
```
head_mask = [None] * 12
out = model.encoder(z, head_mask = head_mask)
```
