### ISSUE TITLE
FRCNN in the LXMERT demo outputs different features when using a local image vs. an image from a URL 

### ISSUE THREAD

**Issue by ecekt** [huggingface/transformers#8333]
## Environment info
- `transformers` version: 3.3.1
- Platform: Linux-5.4.0-52-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.4
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@eltoto1219

## Information
Model I am using: LXMERT, more specifically FRCNN. The problem arises when using the demo.ipynb file given here: https://github.com/huggingface/transformers/blob/master/examples/lxmert/demo.ipynb

## To reproduce

1. Change the URL to the filename of a local image. Both the visualization and the extracted features are affected by this.

## Expected behavior
I noticed that the order of Red, Green, Blue is changed in this line in the utils file: https://github.com/huggingface/transformers/blob/7abc1d96d114873d9c3c2f1bc81343fb1407cec4/examples/lxmert/utils.py#L552

When I comment out this line, the visualization and the features output by the model for a local image are the same as when we use its URL without commenting this line out. 

I would appreciate if you can confirm that commenting out that line does not cause other issues in LXMERT so that I can use local files.

Best,
Ece

**Comment by LysandreJik** [comment]
Pinging @eltoto1219

**Comment by ecekt** [comment]
Hi @eltoto1219 I see that my issue and proposed solution have been mentioned in a more recent issue (#8769), should I follow there for the confirmation?
