### ISSUE TITLE
pip cannot install transformers with python version 3.X version on Ubuntu 18.04

### ISSUE THREAD

**Issue by varshachawan** [huggingface/transformers#8337]
## Environment info

     
- `transformers` version: 3.4.0 
- Platform:
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Python version: python3.X
- PyTorch version (GPU?): no
- Tensorflow version (GPU?): na
- Using GPU in script?: na
- Using distributed or parallel set-up in script?:na

### Who can help
  tokenizers: @mfuntowicz 
## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [X] pip install transformers

## To reproduce

1. Create a VM with Ubuntu 18.04 
2. Install any python3.X version
3. pip3 install transformers

<!-- 
Requirement already satisfied: tokenizers==0.9.2 in /usr/local/lib/python3.6/dist-packages (from transformers)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from sacremoses->transformers)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from sacremoses->transformers)
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from sacremoses->transformers)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->transformers)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf->transformers)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->transformers)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->transformers)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->transformers)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->transformers)
Building wheels for collected packages: sentencepiece
  Running setup.py bdist_wheel for sentencepiece ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-baldc7a3/sentencepiece/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp0rhc8tr_pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/sentencepiece
  copying src/sentencepiece/__init__.py -> build/lib.linux-x86_64-3.6/sentencepiece
  copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.linux-x86_64-3.6/sentencepiece
  copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.linux-x86_64-3.6/sentencepiece
  running build_ext
  /bin/sh: 1: pkg-config: not found
  Cloning into 'sentencepiece'...
  Note: checking out '8336bbd0c1cfba02a879afe625bf1ddaf7cd93c5'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:
  
    git checkout -b <new-branch-name>
  
  ./build_bundled.sh: 15: ./build_bundled.sh: cmake: not found
  make: *** No targets specified and no makefile found.  Stop.
  make: *** No rule to make target 'install'.  Stop.
  env: ‘pkg-config’: No such file or directory
  Failed to find sentencepiece pkg-config
  
  ----------------------------------------
  Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
Failed to build sentencepiece
Installing collected packages: sentencepiece, transformers
  Running setup.py install for sentencepiece ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-baldc7a3/sentencepiece/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cfvofwnm-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/sentencepiece
    copying src/sentencepiece/__init__.py -> build/lib.linux-x86_64-3.6/sentencepiece
    copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.linux-x86_64-3.6/sentencepiece
    copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.linux-x86_64-3.6/sentencepiece
    running build_ext
    /bin/sh: 1: pkg-config: not found
    mkdir: cannot create directory ‘bundled’: File exists
    fatal: destination path 'sentencepiece' already exists and is not an empty directory.
    fatal: destination path 'sentencepiece' already exists and is not an empty directory.
    mkdir: cannot create directory ‘build’: File exists
    ./build_bundled.sh: 15: ./build_bundled.sh: cmake: not found
    make: *** No targets specified and no makefile found.  Stop.
    make: *** No rule to make target 'install'.  Stop.
    env: ‘pkg-config’: No such file or directory
    Failed to find sentencepiece pkg-config
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-baldc7a3/sentencepiece/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cfvofwnm-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-baldc7a3/sentencepiece/
->

## Expected behavior
Successful installation of transformers

**Comment by varshachawan** [comment]
Here is fix I tried : 
first pip install sentencepiece==0.1.5 and then transformers

**Comment by LysandreJik** [comment]
The issue seems to be with SentencePiece then, rather than with `transformers`.

This be should be solved by https://github.com/huggingface/transformers/pull/8073 as it will remove SentencePiece from the dependencies
