### ISSUE TITLE
got an unexpected keyword argument 'early_stop_callback'

### ISSUE THREAD

**Issue by yxu1168** [huggingface/transformers#8342]
__init__() got an unexpected keyword argument 'early_stop_callback'

## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by LysandreJik** [comment]
Hello, we would need you to fill the issue template to have an idea of what's going on and how we can help.

**Comment by sshleifer** [comment]
if you have `pytorch-lightning=1.0.4` and the code on `master` this shouldn't happen.

**Comment by yxu1168** [comment]
Thank you Sam, it works!

**Comment by ahadda5** [comment]
I have 1.8.6 and it still happens.
