### ISSUE TITLE
Error in RAG finetuning script

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#8345]
## Environment info
ut the missing fields in that output! -->
     
- `transformers` version: 3.4.0
- Platform: Linux-4.18.0-147.5.1.el8_1.x86_64-x86_64-with-centos-8.1.1911-Core
- Python version: 3.6.8
- PyTorch version (GPU?): 1.7.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help
 @patrickvonplaten, @lhoestq

## Information

I am using RAG fine-tuning script. During the fine-tuning process, it says

**torch.nn.modules.module.ModuleAttributeError: 'GenerativeQAModule' object has no attribute 'opt'**

The bug exactly appears in [line 332 in finetune.py (https://github.com/huggingface/transformers/blob/master/examples/rag/finetune.py#L332)

## To reproduce
I have installed the transformers library from the source. Not the pip.

**Comment by shamanez** [comment]
It is related with the optimizer initialization in the finetune.py script. Seems like even the the lightning_base.py there is no initialization for the optimizer.

**Comment by shamanez** [comment]
@lhoestq 

any idea on this?

I managed to work around by calling the optimizer initialization inside the train_dataloader function in finetune.py.

**Comment by lhoestq** [comment]
Well the optimizer/scheduler is already defined in examples/lightningbase.py in `BaseTransoformer.configure_optimizers`. Not sure why the train_dataloader() function in finetune.py tries to define the scheduler. This must have been a bad copy paste...

I think we should remove those lines
https://github.com/huggingface/transformers/blob/17b1fd804f2ade052e40505a695ec7c9996178a9/examples/rag/finetune.py#L326-L336

I just tried to remove them and now I'm getting this other issue #7816 
I'll fix this one as well and make a PR

**Comment by shamanez** [comment]
That what I was thinking since there is a specific def in lightningbase.py.
