### ISSUE TITLE
PEGASUS generation/decoding VERY Slow

### ISSUE THREAD

**Issue by muggin** [huggingface/transformers#8348]
## Environment info
- `transformers` version: 3.4.0
- Platform: Linux-4.19.112+-x86_64-with-glibc2.10
- Python version: 3.8.3
- PyTorch version (GPU?): 1.7.0+cu110 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help
@sshleifer 
 
## Information

Model I am using: *PEGASUS-large*, *PEGASUS-cnn_dailymail*, *PEGASUS-xsum*

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

I compared the generation/decoding performance of BART and PEGASUS both loaded via AutoModelSeq2SeqForLM fine-tuned on a custom dataset for the same amount of time. Generation was done using basic greedy decoding. PEGASUS models are anywhere between 5-15x slower than BART. Fine-tuning speed was on-par for both models.

## To reproduce

1. Load PEGASUS and BART from any of the mentioned checkpoints (using AutoModelSeq2SeqForLM)
1. Fine-tune models
2. Decode using greedy decoding
3. Compare fine-tuning performance with other Seq2Seq Model (BART-large)

## Expected behavior
Decoding performance on-par with BART-large?

**Comment by sshleifer** [comment]
this is expected behavior. 
try using num_beams=2 for both models, and or using a distilled model for faster inference. BART also works in fp16.

**Comment by muggin** [comment]
I used greedy decoding when generating outputs, so the number of beams should not matter in this case.
Also, PEGASUS is 30% larger than BART, so why does it translate to at least 5x performance drop at inference?

**Comment by sshleifer** [comment]
I can't investigate deeply without a code snippet, but a 5X difference in greedy decoding time for roughly the same number of output characters is larger than I would have expected.

**Comment by muggin** [comment]
In our case, the model is part of a larger system, so can't share the code I am using. 
However, I will create a minimal example that allows me to reproduce this issue (most likely by Monday).

One difference I already see is that in our code we work with long sequences that max out the model's limits both on the input and output side. I just started another batch of generation and on the exact same input data BART-large is projected to finish in 45 minutes, PEGASUS-large in 14 hours, both models running on a single A100 GPU (per model).

**Comment by sshleifer** [comment]
Cool.
+ If you want smaller models you can checkout the distilbart/distill-pegasus variants [here](https://huggingface.co/models?search=sshleifer%2Fdistil) [Paper w Details](https://arxiv.org/abs/2010.13002)
+ `bart-large/pegasus-large` probably can't generate very well (unless you've fine-tuned them)
