### ISSUE TITLE
update from v3.0.0 to v3.4.0 got an error

### ISSUE THREAD

**Issue by zyh3826** [huggingface/transformers#8354]
## Environment info

- `transformers` version: v3.4.0
- Platform: redhat
- Python version: 3.8.3 64bit
- PyTorch version (GPU?): 1.5.1
- Tensorflow version (GPU?):
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

## Information

Model I am using (Bert, XLNet ...):
Bert
The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

yesterday i used transformers v3.0.0 trained my model and save it use 
`torch.save(model.state_dict(), config.save_path)`, 
and today i update transformers to v3.4.0, when i use 
`torch.load` 
i got this error 
![image](https://user-images.githubusercontent.com/31238754/98341317-a2be1600-2049-11eb-9672-749896b9c2a4.png)
could anybody help me!!! thx

**Comment by LysandreJik** [comment]
Hi! Yes, you should use the `from_pretrained` method to ensure compatibility within versions. Have you tried using that method instead? It should point to a directory containing your model file named as `pytorch_model.bin` and the configuration file of the model named as `config.json`.

**Comment by zyh3826** [comment]
> Hi! Yes, you should use the `from_pretrained` method to ensure compatibility within versions. Have you tried using that method instead? It should point to a directory containing your model file named as `pytorch_model.bin` and the configuration file of the model named as `config.json`.

Hi LysandreJik, I think you may misunderstand my problem. At the beginning of this project, I used `from_pretrained`, and when the training ended I use the `torch.save` saving the model to a .pth file(Under transformers v3.0.0). But under transformers v3.4.0, I init the model use `model = BertModel.from_pretrained(BertConfig.from_pretrained(configpath))`, then `model.load_state_dict(torch.load(modelpath)` and get this error. But under transformers v3.0.0, it's ok.
