### ISSUE TITLE
Cannot Load roberta tokenizer

### ISSUE THREAD

**Issue by Rogerspy** [huggingface/transformers#8357]
# ❓ Questions & Help

My `transformers`'s version is `transformers 3.4.0`

I download a Chinese RoBERTa model, where:

```
models
├── RoBERTa_zh_Large_Pytorch
│   ├── config.json
│   ├── pytorch_model.bin
│   └── vocab.txt
```

I want to load the tokenizer from local:

```python
tokenizer_zh = RobertaTokenizer.from_pretrained('./models/RoBERTa_zh_Large_Pytorch/')
```

but I get :

```
OSErrorTraceback (most recent call last)
<ipython-input-4-bdedc9589347> in <module>
----> 1 tokenizer_zh = RobertaTokenizer.from_pretrained('./models/RoBERTa_zh_Large_Pytorch/')

/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py in from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
   1647                     ", ".join(s3_models),
   1648                     pretrained_model_name_or_path,
-> 1649                     list(cls.vocab_files_names.values()),
   1650                 )
   1651             )

OSError: Model name './models/RoBERTa_zh_Large_Pytorch/' was not found in tokenizers model name list (roberta-base, roberta-large, roberta-large-mnli, distilroberta-base, roberta-base-openai-detector, roberta-large-openai-detector). We assumed './models/RoBERTa_zh_Large_Pytorch/' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.
```

**Comment by LysandreJik** [comment]
It seems that the tokenizer in that directory is not a Byte level BPE, or at least not in a format the library can understand. A byte-level BPE like the RoBERTa tokenizer should have a merges files as well.

Could you try to load it in a BERT tokenizer? The BERT tokenizer saves its vocabulary as `vocab.txt` so it is possible this is the tokenizer that was used.

**Comment by Rogerspy** [comment]
> It seems that the tokenizer in that directory is not a Byte level BPE, or at least not in a format the library can understand. A byte-level BPE like the RoBERTa tokenizer should have a merges files as well.
> 
> Could you try to load it in a BERT tokenizer? The BERT tokenizer saves its vocabulary as `vocab.txt` so it is possible this is the tokenizer that was used.

Thank you! It works.
