### ISSUE TITLE
Which model to choose for seq2seq(generating headers for articles)?

### ISSUE THREAD

**Issue by AndreyStille** [huggingface/transformers#8367]
Hi
Task is generating headers for articles. I have dataset with articles and correct names.
I think about using T5 for summarization or GPT-2 for seq2seq modeling. I'm not sure what way to choose
Can you please give me advise which direction is more relevant for this task?

**Comment by LysandreJik** [comment]
Hi! Questions like this are welcome on the forum, we try to keep the github issues for bugs/feature requests only :) Thanks!
