### ISSUE TITLE
BertTokenizerFast object has no attribute 'ids_to_tokens'

### ISSUE THREAD

**Issue by githubrandomuser2017** [huggingface/transformers#8370]
## Environment info

     
- `transformers` version:
- Platform: Google Colab
- Python version: 3.6.9
- PyTorch version (GPU?): 1.7
- Tensorflow version (GPU?):
- Using GPU in script?: No
- Using distributed or parallel set-up in script?:

### Who can help

@mfuntowicz

## Information

BertTokenizer has an attribute dictionary `ids_to_tokens`. However, BertTokenizerFast does not have this dictionary. I would expect them to have the same interfaces.

Model I am using (Bert, XLNet ...): BERT, BertTokenizerFast

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x ] my own task or dataset: (give details below)

## To reproduce

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
print(type(tokenizer).__name__) # BertTokenizer
print(tokenizer.ids_to_tokens[0]) # [PAD]


tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased', use_fast=True)
print(type(tokenizer).__name__) # BertTokenizerFast
print(tokenizer.ids_to_tokens[0]) # 'BertTokenizerFast' object has no attribute 'ids_to_tokens'
```

## Expected behavior

BertTokenizerFast should convert ID 0 to '[PAD]'

**Comment by LysandreJik** [comment]
Hi! `ids_to_token` is legacy code that should have its visibility set to private. We recommend using the `convert_ids_to_tokens` method, or the `get_vocab()` if you wish to take a look at the whole vocabulary. Both should be available on both the `BertTokenizer` and `BertTokenizerFast`.
