### ISSUE TITLE
Fine-tuning for QA: how to prepare custom dataset?

### ISSUE THREAD

**Issue by AndreyStille** [huggingface/transformers#8372]
I have csv dataset article,name
I want to use fine-tuning(Albert), don't undestand how to prepare my dataset to suite for fine-tuning tutorial (https://huggingface.co/transformers/custom_datasets.html#question-answering-with-squad-2-0)
Can't understand the reason why we add start and end idx of answer in context to 'answer' part of dataset.
Could I use just text in answer, without start and end ?
If context doesn't contain all answer words in a row, what indices should be selected then?

**Comment by ManavR123** [comment]
The way the model works is by predicting the start and end indices of the answer. This is for **extractive** QA which means the answer needs to be in a continuous sequence in the context.

**Comment by AndreyStille** [comment]
> This is for **extractive** QA which means the answer needs to be in a continuous sequence in the context. The way the model works is by predicting the start and end indices of the answer.

thanks for help 
I found what I needed
