### ISSUE TITLE
removing runs folders 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#8373]
Hi
Do you know where in the codes when training finetune_trainer.py a folder "runs" created? could it be moved to output_dir? so this is always created in the directory running codes than output_dir
thanks

**Comment by qanastek** [comment]
Hi,

You can move the path of the "**_runs/_**" folder by adding `logging_dir` to your `TrainingArguments` such like this:

```python
training_args = TrainingArguments(
    output_dir=OUTPUT_PATH,
    overwrite_output_dir=True,
    logging_dir=OUTPUT_PATH + "/logs",
   ...
)
```
