### ISSUE TITLE
RobertaTokenizerFast is around 10 times slower than BertTokenizerFast #510

### ISSUE THREAD

**Issue by napsternxg** [huggingface/transformers#8375]
## Environment info

     
- `transformers` version: 3.3.1
- Platform: Linux-5.4.38-t2.el7.twitter.x86_64-x86_64-with-centos-7.7.1908-Core
- Python version: 3.7.9
- PyTorch version (GPU?): 1.4.0+cu100 (True)
- Tensorflow version (GPU?): 2.3.1 (True)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help

@mfuntowicz

## Information
Also opened this issue on the tokenizers repo: https://github.com/huggingface/tokenizers/issues/510

`RobertaTokenizerFast` with 60k vocab size is around 50 times slower  than the `BertTokenizerFast` for `transformers==3.3.1`. 

This is really slowing down the processing time for training the language model. Is there a suggested fix for this? 

Model I am using (Bert, XLNet ...): RobertaTokenizerFast

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```python

In [37]: from transformers import BertTokenizerFast, RobertaTokenizerFast
    ...: 

In [38]: bert_tokenizer = BertTokenizerFast.from_pretrained(bert_tokenizer_dir, max_len=512, truncation=True)
    ...: roberta_tokenizer = RobertaTokenizerFast.from_pretrained(roberta_tokenizer_dir, max_len=512, truncation=True)
    ...: 

In [39]: line = "I am trying out this code for testing tokenizers and it is super good. Huge victory. But the difference in speed between BERT tokenizer and Robert
    ...: a tokenizers is quite slow."

In [40]: bert_tokenizer.encode_plus(line, add_special_tokens=True, truncation=True)
Out[40]: {'input_ids': [2, 51, 1881, 21557, 3212, 2937, 3590, 1945, 40605, 53576, 23981, 1013, 1985, 2179, 1943, 3863, 3841, 20, 38092, 65353, 20, 3180, 1931, 48800, 1822, 12679, 26777, 18732, 53576, 23981, 1985, 20839, 1016, 53576, 23981, 1013, 1943, 66009, 16390, 20, 3], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [41]: roberta_tokenizer.encode_plus(line, add_special_tokens=True, truncation=True)
Out[41]: {'input_ids': [0, 47, 979, 28120, 3145, 2924, 6628, 1046, 6747, 458, 618, 2063, 781, 719, 994, 1527, 891, 6074, 6464, 20, 550, 11852, 21228, 3085, 20, 16339, 898, 20420, 40977, 494, 24738, 34187, 444, 13841, 618, 2063, 27250, 994, 12086, 16449, 618, 2063, 781, 719, 891, 517, 1492, 23819, 20, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [42]: %%timeit -n 10000
    ...: tokens = roberta_tokenizer.encode_plus(line, add_special_tokens=True, truncation=True)
    ...: 
10000 loops, best of 5: 9.09 ms per loop

In [43]: %%timeit -n 10000
    ...: tokens = bert_tokenizer.encode_plus(line, add_special_tokens=True, truncation=True)
    ...: 
10000 loops, best of 5: 181 µs per loop

In [44]: roberta_tokenizer.vocab_size
Out[44]: 60000

In [45]: bert_tokenizer.vocab_size
Out[45]: 100000


In [47]: import transformers

In [48]: import tokenizers

In [49]: transformers.__version__
Out[49]: '3.3.1'

In [50]: tokenizers.__version__
Out[50]: '0.8.1.rc2'

```

## Expected behavior

I expect to not be much difference here. Why is this the case?

**Comment by LSinev** [comment]
Maybe related to https://github.com/huggingface/transformers/issues/6962

**Comment by LysandreJik** [comment]
Both tokenizers are very unrelated, so I don't think they can be directly compared like this.

**Comment by napsternxg** [comment]
@LysandreJik can you elaborate on this unrelatedness? 
I think both are implemented in Rust and I assume the tokenizers use same algorithm for tokenization part? Maybe I am missing a detail here.

**Comment by LysandreJik** [comment]
BERT's tokenizer uses WordPiece while RoBERTa's tokenizer is a byte-level BPE. They're not the same algorithm. You can have more information [here](https://huggingface.co/docs/tokenizers/python/latest/components.html#models).

**Comment by napsternxg** [comment]
Thanks @LysandreJik for the explanation. I was not aware of this difference.
