### ISSUE TITLE
training T5 on  multiple datasets 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#8380]
Hi
I'd need to train finetune_trainer with T5 on multiple datasets. Could you give me some pointers, how I can form a dataloader with multiple datasets in the very simple form of it?
thanks

**Comment by LysandreJik** [comment]
Hi, these questions are better suited for the forum as we try to keep the github issues for bugs/feature requests only. Could you open an issue on the [forum](https://hdiscuss.huggingface.co) instead?

**Comment by rabeehkarimimahabadi** [comment]
Hi, the link is broken. thanks

**Comment by LysandreJik** [comment]
fixed!
