### ISSUE TITLE
comment correction in modeling_bart.py

### ISSUE THREAD

**Issue by jc-hou** [huggingface/transformers#8384]
Hello, in here 
https://github.com/huggingface/transformers/blob/07708793f20ec3a949ccab32cc4fe0c7272dcc4c/src/transformers/modeling_bart.py#L588

I think the comment should be 
```
# Convert to Bart output format: (BS, seq_len, model_dim) -> (seq_len, BS, model_dim) 
```
Before transpose , shape of x and encoder_hidden_states are both (BS, seq_len, model_dim) to me.
Thanks.

**Comment by sshleifer** [comment]
Great catch, you are correct.
