### ISSUE TITLE
ImportError: cannot import name 'is_flax_available' from 'transformers.file_utils'

### ISSUE THREAD

**Issue by brendan-AI** [huggingface/transformers#8386]
- `transformers` version: 3.4.0
- Platform: macOS-10.13.6-x86_64-i386-64bit
- Python version: 3.8.3
- PyTorch version (GPU?): 1.7.0 (False)
- Tensorflow version (GPU?): 2.3.0 (False)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

The problem arises when using trying to import:
from transformers import AutoTokenizer, AutoModel

Running on Jupyter notebook in conda virtual env
full error message below:
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-50-13d0bae188dc> in <module>
----> 1 from transformers import AutoTokenizer, AutoModel
      2 
      3 tokenizer = AutoTokenizer.from_pretrained("bashar-talafha/multi-dialect-bert-base-arabic")
      4 model = AutoModel.from_pretrained("bashar-talafha/multi-dialect-bert-base-arabic")

/opt/anaconda3/envs/py38/lib/python3.8/site-packages/transformers/__init__.py in <module>
     20 # Integrations: this needs to come before other ml imports
     21 # in order to allow any 3rd-party code to initialize properly
---> 22 from .integrations import (  # isort:skip
     23     is_comet_available,
     24     is_optuna_available,

/opt/anaconda3/envs/py38/lib/python3.8/site-packages/transformers/integrations.py in <module>
     57 
     58 from .file_utils import is_torch_tpu_available
---> 59 from .trainer_callback import TrainerCallback
     60 from .trainer_utils import PREFIX_CHECKPOINT_DIR, BestRun
     61 from .utils import logging

/opt/anaconda3/envs/py38/lib/python3.8/site-packages/transformers/trainer_callback.py in <module>
     24 from tqdm.auto import tqdm
     25 
---> 26 from .trainer_utils import EvaluationStrategy
     27 from .training_args import TrainingArguments
     28 from .utils import logging

/opt/anaconda3/envs/py38/lib/python3.8/site-packages/transformers/trainer_utils.py in <module>
     23 
     24 from .file_utils import is_tf_available, is_torch_available
---> 25 from .tokenization_utils_base import ExplicitEnum
     26 
     27 

/opt/anaconda3/envs/py38/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in <module>
     30 import numpy as np
     31 
---> 32 from .file_utils import (
     33     add_end_docstrings,
     34     cached_path,

ImportError: cannot import name 'is_flax_available' from 'transformers.file_utils' (/opt/anaconda3/envs/py38/lib/python3.8/site-packages/transformers/file_utils.py)`

**Comment by LysandreJik** [comment]
It seems you have a mismatch between several `transformers` versions.

We generally recommend using virtual environments not relying on `conda`, as full `transformers` support is not yet available on `conda`. Can you reproduce using a pip virtual env?

```py
python -m venv .env
source .env/bin/activate
pip install transformers
```

**Comment by brendan-AI** [comment]
that works in the virtual env, thank you!
