### ISSUE TITLE
Electra multi-gpu pretraining.

### ISSUE THREAD

**Issue by 652994331** [huggingface/transformers#8424]
Hi, I am pretraining the Electra model with my own data, for now, I am pretraining using one GPU in my machine. Can we use multi GPUs to pretrain Electra? Thanks for your reply

**Comment by LysandreJik** [comment]
That would depend of the training script. All of our models are `nn.Module`s so all can be trained on multi-GPU, it just depends on the script. What script are you using?

**Comment by 652994331** [comment]
@LysandreJik  Hi, thanks for your reply, i am not pretty sure about script, what I am doing now is using TensorFlow google Electra, but it seems I haven't figure out how to use multi gpu in TensorFlow, that's why i am here, Do u have any advice, I mean maybe I can just use Electra in this project to achieve multi-gpu pretraining?

**Comment by LysandreJik** [comment]
Yes, you could check [this thread](https://discuss.huggingface.co/t/electra-training-reimplementation-and-discussion/1004) and use their project to train ELECTRA, which is based on this repository.

**Comment by 652994331** [comment]
@LysandreJik  thanks, however, according to this issue https://github.com/richarddwang/electra_pytorch/issues/5 , I guess they haven't figure out how to use multigpu yet,

**Comment by LysandreJik** [comment]
Ah, then I don't think I can help you further, unfortunately.
