### ISSUE TITLE
Wrong files names in model list for "xlm-roberta-large-finetuned-conll03-german"

### ISSUE THREAD

**Issue by padmalcom** [huggingface/transformers#8426]
Hi, the names of the model files for "xlm-roberta-large-finetuned-conll03-german" are incorrect and have to model name as prefix.

Example:
xlm-roberta-large-finetuned-conll03-german-config.json instead of config.json

**Comment by LysandreJik** [comment]
Hi, what do you mean they're incorrect? Are you having issues loading the files in your `transformers` objects?

**Comment by padmalcom** [comment]
Hi, click on [https://huggingface.co/xlm-roberta-large-finetuned-conll03-german](https://huggingface.co/xlm-roberta-large-finetuned-conll03-german) and then on _List all files in model_ and move the mouse over each link. You will see that the files have a prefix (namely the name of the model). This is not allowed by the transformers api, since it expects to find e.g. config.json instead of xlm-roberta-large-finetuned-conll03-german-config.json. Hope this explaination helps.

**Comment by LysandreJik** [comment]
I cannot see the prefix in the link you've given, and I can correctly load the models in the library:

```py
from transformers import XLMRobertaModel
XLMRobertaModel.from_pretrained("xlm-roberta-large-finetuned-conll03-german")
```
works correctly.

The legacy models (e.g. `bert-base-cased`) had the prefix, but we've changed the approach since and only keep them that way for backwards compatibility.

**Comment by julien-c** [comment]
I can confirm this is intended

**Comment by padmalcom** [comment]
Okay, I only experience this error when downloading the files and load from local storage instead of providing a name. But when this is working as intended, it is fine for me.
