### ISSUE TITLE
Set num_beams=4 for all Helsinki-NLP models

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#8427]
Currently it is 6. Empirically, I tested 77 random models and num_beams=4 was about 50% faster and on average slightly higher BLEU (22.5 vs 22.4). 

We also have @jorgtied 's approval for the change.
On slack, he wrote

>  Again, no systematic evaluation - more like a feeling. I had the impression that 1 or 2 is worse and I didn’t want to set 10 or 12 that I have seen otherwise, because it may slow down things quite substantially. If you make some more tests then let me know what you will find … Thanks!

There are about 1300 affected model's, so this feels like the type of thing @patrickvonplaten 's script could do well.

**Comment by patrickvonplaten** [comment]
I can do the change! Will wait until the new git model hub is merged and then apply it :-)

**Comment by sshleifer** [comment]
Thanks!

**Comment by julien-c** [comment]
Should be decently easy to do it @patrickvonplaten let me know when you get to it :)

**Comment by patrickvonplaten** [comment]
@julien-c, @jorgtied - sorry forgot about this issue...changing `num_beams=4` for all opus models now.
