### ISSUE TITLE
login to huggingface forum

### ISSUE THREAD

**Issue by srulikbd** [huggingface/transformers#8438]
hey.
I'm not sure where to post it, so my apologise in advance.

I'm trying to login to huggingface forum, but it return me the message: "Unauthorized".
what can I do?
(I created a user..)

thanks.

**Comment by LysandreJik** [comment]
Maybe @julien-c or @Pierrci knows!

**Comment by julien-c** [comment]
can you try again, just in case it was an intermittent issue?

**Comment by srulikbd** [comment]
Wonderful, i login with another email and it works. Thanks.
