### ISSUE TITLE
Can't find model to down

### ISSUE THREAD

**Issue by havetry** [huggingface/transformers#8449]
# 🚀 Feature request

## Your contribution
I can't find any model to down in "huggingface.cn", so what happened?
![down](https://user-images.githubusercontent.com/49902228/98759351-e202b300-240b-11eb-87ea-e2f495d3afbe.png)
but I find many people downed the model in Noverber 9, so why I can't find model today?

**Comment by xlxwalex** [comment]
I encountered the same problem

**Comment by julien-c** [comment]
Will release a new version of that UX tomorrow

**Comment by julien-c** [comment]
We just added file sizes, and download links, to the lists of model files, see for instance:

<img width="1592" alt="Screenshot 2020-11-13 at 22 55 23" src="https://user-images.githubusercontent.com/326577/99125288-be896500-25d1-11eb-84f5-03eb9b44f29d.png">

https://huggingface.co/dbmdz/bert-base-turkish-cased/tree/main

Let us know if this solves your use case @havetry @xlxwalex.

**Comment by havetry** [comment]
> We just added file sizes, and download links, to the lists of model files, see for instance:
> 
> <img alt="Screenshot 2020-11-13 at 22 55 23" width="1592" src="https://user-images.githubusercontent.com/326577/99125288-be896500-25d1-11eb-84f5-03eb9b44f29d.png">
> 
> https://huggingface.co/dbmdz/bert-base-turkish-cased/tree/main
> 
> Let us know if this solves your use case @havetry @xlxwalex.

Good job, thanks!
