### ISSUE TITLE
Question Answering Documentation Example Bug

### ISSUE THREAD

**Issue by iremnasir** [huggingface/transformers#8459]
## Environment info

- `transformers` version: 3.5.0
- Platform: Darwin-19.6.0-x86_64-i386-64bit
- Python version: 3.6.12
- PyTorch version (GPU?): 1.7.0 (False)
- Tensorflow version (GPU?): 2.3.1 (False)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: parallel

### Who can help
 @sgugger 

## Information

Model I am using (Bert, XLNet ...): bert-large-uncased-whole-word-masking-finetuned-squad

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

Trying to run this [example script](https://huggingface.co/transformers/task_summary.html#extractive-question-answering) for TF, I kept on getting error:

```
InvalidArgumentError: Value for attr 'T' of string is not in the list of allowed values: float, double, int32, uint8, int16, int8, complex64, int64, qint8, quint8, qint32, bfloat16, uint16, complex128, half, uint32, uint64, bool
	; NodeDef: {{node ArgMax}}; Op<name=ArgMax; signature=input:T, dimension:Tidx -> output:output_type; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, ..., DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64, DT_BOOL]; attr=Tidx:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]; attr=output_type:type,default=DT_INT64,allowed=[DT_INT32, DT_INT64]> [Op:ArgMax]
```
at the line where` tf.argmax()` is called on `answer_start_scores` and `answer_end_scores`

## Expected behavior

This error is normal since `type(answer_start_scores)` is `str`, so I propose the following amendment to the documentation:
from transformers import AutoTokenizer, TFAutoModelForQuestionAnswering
```
import tensorflow as tf
tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased-whole-word-masking-finetuned-squad")
model = TFAutoModelForQuestionAnswering.from_pretrained("bert-large-uncased-whole-word-masking-finetuned-squad", return_dict=True)
text = r"""
🤗 Transformers (formerly known as pytorch-transformers and pytorch-pretrained-bert) provides general-purpose
architectures (BERT, GPT-2, RoBERTa, XLM, DistilBert, XLNet…) for Natural Language Understanding (NLU) and Natural
Language Generation (NLG) with over 32+ pretrained models in 100+ languages and deep interoperability between
TensorFlow 2.0 and PyTorch.
"""
questions = [
    "How many pretrained models are available in 🤗 Transformers?",
    "What does 🤗 Transformers provide?",
    "🤗 Transformers provides interoperability between which frameworks?",
]
for question in questions:
    inputs = tokenizer(question, text, add_special_tokens=True, return_tensors="tf")
    input_ids = inputs["input_ids"].numpy()[0]
    text_tokens = tokenizer.convert_ids_to_tokens(input_ids)
    output = model(inputs)
    answer_start = tf.argmax(
        output.start_logits, axis=1
    ).numpy()[0]  # Get the most likely beginning of answer with the argmax of the score
    answer_end = (
        tf.argmax(output.end_logits, axis=1) + 1
    ).numpy()[0]  # Get the most likely end of answer with the argmax of the score
    answer = tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(input_ids[answer_start:answer_end]))
    print(f"Question: {question}")
    print(f"Answer: {answer}")
```

Best,
Irem

**Comment by LysandreJik** [comment]
Hi! That sounds good, do you want to open a PR?

**Comment by iremnasir** [comment]
Yes, I am on it. Thanks!

**Comment by sargupta** [comment]
+1
any updates?

**Comment by sargupta** [comment]
@iremnasir can you please let me know how exactly you managed to solve it?  I am having the same issue. 
![Screenshot 2020-12-07 at 00 56 45](https://user-images.githubusercontent.com/28517335/101344563-ae506700-38ab-11eb-9e12-98abe95e238c.png)

**Comment by iremnasir** [comment]
Hi, you can see my answer above for the solution in Expected Behavior section

**Comment by sargupta** [comment]
Got it. Thanks

As  got the error for AutoTokenizer: `NameError: name 'AutoTokenizer' is not defined `
Just imported all:
`from transformers import * ` earlier I was only importing `pipeline` from transformers

**Comment by KarthiAru** [comment]
Thanks @iremnasir, it worked. Why hasn't this been merged yet?
