### ISSUE TITLE
Fine tuning a classification model with engineered features

### ISSUE THREAD

**Issue by rogeriobromfman** [huggingface/transformers#8467]
# 🚀 Feature request

When fine-tuning a BERT model for text classification, it would be useful to be able to add some engineered features to improve accuracy. 

## Motivation

For example: 

- if there are any dates on the text (based on NER); 
- if the text starts with a punctuation;
- if the font size is larger or smaller than the rest of the document, etc.

These things can help the model make better predictions as to the class of the text.

## Contribution

At the moment, I've been adding these features as custom tokens to the end of the text. E.g "\<DATES\>", "\<PUNCT\>"

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
