### ISSUE TITLE
How to print out the probability for each bean search result in gpt2 text generator?

### ISSUE THREAD

**Issue by beibeic** [huggingface/transformers#8477]
# 🚀 I want to see the probability for the text result generated by gpt2 model 

See a sample code as below, when we used a pre-trained model,  can we also print out the probability outcome with each beam_output? 

beam_outputs = model.generate(
    input_ids, 
    max_length=50, 
    num_beams=5, 
    no_repeat_ngram_size=2, 
    num_return_sequences=5, 
    early_stopping=True
)

for i, beam_output in enumerate(beam_outputs):
  **print("{}: {}".format(i, tokenizer.decode(beam_output, skip_special_tokens=True)))**

**Comment by LSinev** [comment]
Take a look at https://github.com/huggingface/transformers/issues/5164
