### ISSUE TITLE
Gradient accumulation averages over gradients

### ISSUE THREAD

**Issue by MarktHart** [huggingface/transformers#8486]
https://github.com/huggingface/transformers/blob/121c24efa4453e4e726b5f0b2cf7095b14b7e74e/src/transformers/trainer.py#L1118

So I have been looking at this for the past day and a half. Please explain to me. Gradient accumulation should accumulate the gradient, not average it, right? That makes this scaling plain wrong? Am I missing something?

**Comment by thomwolf** [comment]
Hi @MarktHart do you mind posting this on the forum rather? It's here: https://discuss.huggingface.co

We are trying to focus the issues on bug reports and features/model requests.

Thanks a lot.
