### ISSUE TITLE
`log_history` does not contain metrics anymore

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#8487]
Since version 3.5.0 the `log_history` of the trainer does not contain the metrics anymore. Version 3.4.0 works...

My trainer uses a `compute_metrics` callback. It avaluates after each epoch. At version 3.4.0 after the training I am extracting the last epoch results: `trainer.state.log_history[-1]` to log the metrics.

At version 3.5.0 the dict only contains loss and epoch number but not the computed metrics. 

I think anything was changed that broke the metric logging. I can not provide example code. Sorry...

**Comment by sgugger** [comment]
`evaluate` calls `log` which appends the results to `log_history`. So the code is there. Without a reproducer to investigate, there is nothing we can do to help.

**Comment by PhilipMay** [comment]
Here is the demo code that shows the bug: https://colab.research.google.com/drive/1dEzkDoMampL-VVrQeO924HQmHXffya0Z?usp=sharing

The last line should pring all metrics and does that with version 3.4.0 but not with 3.5.0

**Comment by sgugger** [comment]
Ah it's not a bug. In 3.5.0 there is one final log entry for the total_flos (instead of logging them during training as it's only useful at the end). So you can still access all your metrics but with the second-to-last entry (`trainer.state.log_history[-2]`).

**Comment by PhilipMay** [comment]
Hi @sgugger ok thanks for the info.
It might be no bug but honestly. This logging "API" is very fragile. What happens if I do a `[-2]` now and in the next release the final log entry for the total_flos is moved to an other list. Then I am getting the result of the 2nd last epoch instead of the last one.

IMO this logging "API" needs a clean and better redesign. Or do I just use it in a wrong way?

**Comment by sgugger** [comment]
There are plenty of things that could log more info: a callback, some other tweak in training performed at the end. IMO you shouldn't rely on a hard-coded index but loop from the end of the `log_history` until you find a dict with the metric values.

**Comment by PhilipMay** [comment]
Ok. Closing this.
