### ISSUE TITLE
can't find utils_glue

### ISSUE THREAD

**Issue by YosiMass** [huggingface/transformers#849]
import fails

**Comment by davidefiocco** [comment]
It's hard to tell what could be the source of the error without describing with some minimum details in the issue what you tried to do/run...

_If_ you are running `run_glue.py` in the examples, make sure that [`utils_glue.py`](https://github.com/huggingface/pytorch-transformers/blob/master/examples/utils_glue.py) is present in the same working directory in which you are executing the script.

**Comment by YosiMass** [comment]
Thanks David. Turns out that the import in e.g., `run_glue.py` should be 

`from examples.utils_glue import ...`

instead of 

`from utils_glue import ...`

Maybe it's a problem of PyCharm IDE
