### ISSUE TITLE
Adding Confusion matrix support in Trainer

### ISSUE THREAD

**Issue by prajjwal1** [huggingface/transformers#8511]
I want to add confusion matrix support in Trainer. It would be a useful addition. The only dependency would be `sklearn` which this library already uses for metrics. It can allow users to better understand about predictions coming from model. @sgugger Let me know if this is something you want to add.

**Comment by sgugger** [comment]
Hi there! We love contributions, but metrics should now be implemented directly in the datasets library, not inside Transformers. So you should check there if it does not already exist, and if not, suggest a Pr on that repository :-)

**Comment by prajjwal1** [comment]
Okay then, I will close it.
