### ISSUE TITLE
How to pretrain the model (like Roberta) again?

### ISSUE THREAD

**Issue by drxmy** [huggingface/transformers#8514]
I don't want to pretrain the model from scratch. I have some dataset related to my task. I want to pretrain the model from transformers the second time. Could someone give me some advice on how to do it or which document to read?  Thank you!

**Comment by NielsRogge** [comment]
The authors of the Transformers library wrote a script for this. You can find it under the examples folder -> language modeling [here](https://github.com/huggingface/transformers/tree/master/examples/language-modeling#robertabertdistilbert-and-masked-language-modeling).

**Comment by drxmy** [comment]
> The authors of the Transformers library wrote a script for this. You can find it under the examples folder -> language modeling [here](https://github.com/huggingface/transformers/tree/master/examples/language-modeling#robertabertdistilbert-and-masked-language-modeling).

Thank you! I will check it out.
