### ISSUE TITLE
XLM-RoBERTa tokenizer changes characters during tokenization

### ISSUE THREAD

**Issue by konstantinmiller** [huggingface/transformers#8517]
I'm using `transformers` 3.5.0.

Whenever the XLM-RoBERTa tokenizer encounters some characters such as '²' (super-script 2, `ord('²')` is 178), it converts them to other characters (in this example, to the plain '2', with `ord('2')` being 50).

That is, with `tokenizer = AutoTokenizer.from_pretrained('xlm-roberta-large')`, `tokenizer.tokenize('²')` or, altnernatively, `tokenizer.tokenize(chr(178))` returns `['▁2']`.

**Comment by LysandreJik** [comment]
Hi, this is unfortunately a limit of this tokenizer. We try to stay as close as possible to the original implementation, so we will not be able to change this behavior.

**Comment by konstantinmiller** [comment]
I see. Well, it's not a big deal, as the characters it replaces are quite rare and not really important, at least not for my application. So, I just replace them upfront in the text to make sure that the output of the tokenizer still matches the input.

Thanks for the awesome work you are doing by providing this and other libraries!

**Comment by LysandreJik** [comment]
Glad you like it :)
