### ISSUE TITLE
MLflowCallback to log run_name argument

### ISSUE THREAD

**Issue by HenryMaguire** [huggingface/transformers#8519]
# 🚀 Feature request

When using the MLflowCallback (set as default for Trainer), I would like to log the `run_name` argument passed to TrainingArguments as the Run Name on the MLflow dashboard. Currently runs are being logged as nameless.
E.g. see below.
![Screenshot 2020-11-13 at 10 29 32](https://user-images.githubusercontent.com/2844109/99062592-21abd500-259b-11eb-9caf-c43d2bcb31dc.png)

## Motivation

Trainer makes training 🤗  models so easy and MLflow is great for organising experiments/caching artifacts. I would like to make it easier to organise experimental runs and make research easier, particularly for larger teams. This feature would be a very simple patch on the original PR #8016 

example usage
```
training_args = TrainingArguments(
    label_names=['labels_t1', 'labels_t2'],
    output_dir='./runs,          # output directory
    run_name='multitask_clf_<run_name>',
)
trainer = Trainer(
    model=model,        # the instantiated 🤗 Transformers model to be trained
    args=training_args,        # training arguments, defined above
    train_dataset=train_dataset,        # training dataset
)
```

## Your contribution

I can submit a PR

**Comment by sgugger** [comment]
Please don't hesitate to suggest a PR, `run_name` is there just for this reason!

**Comment by ksopyla** [comment]
It will be useful to have this, and it will organize all the experiments better.

**Comment by YangDong2002** [comment]
Is there any update on this issue and #12841? I have a very simple one-line solution of passing `args.run_name` (which currently serves for `wandb`) to `mlflow.start_run` that can fix this. I can submit a PR in case of need.

**Comment by pratikchhapolika** [comment]
@HenryMaguire can you send link to your notebook or  colab?
