### ISSUE TITLE
Tagged versions of model in new model hub don't work

### ISSUE THREAD

**Issue by brandenchan** [huggingface/transformers#8521]
Our model, deepset/roberta-base-squad2 was originally uploaded under the old style model hub.

I have committed a new version of the deepset/roberta-base-squad2 model onto the model hub using the new git based system introduced in transformers 3.5.0. I have 2 tags (v1.0 and v2.0) that I have also pushed to the repo. The tags show up in the model hub drop down but when I click on either of the tags, it says "Not Found: Error: Invalid rev id". 

It seems I cannot load the models when I specify `revision=v1.0` or `revision=v2.0`. If I don't specify a revision, it seems to load a model though I'm not sure which. This is the code I used:
```
tokenizer = AutoTokenizer.from_pretrained(
  "deepset/roberta-base-squad2",
  revision="v2.0" # tag name, or branch name, or commit hash
)
```

What steps can I take so that I can access both versions through the model hub website, and by specifying name and revision?

Thanks,
Branden

 @julien-c

**Comment by julien-c** [comment]
Looking into it right now (cc @Pierrci)

**Comment by julien-c** [comment]
looks like we were supporting lightweight tags but not annotated ones.

**Comment by julien-c** [comment]
Should be fixed: https://huggingface.co/deepset/roberta-base-squad2/tree/v2.0

**Comment by brandenchan** [comment]
That fixed the problem! Thanks very much

**Comment by julien-c** [comment]
Thanks, and please keep the feedback coming! <3
