### ISSUE TITLE
[models website: files section] various issues/suggestions for a better UI

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#8531]
Models website - files section: suggestions/issues:

1. [ ] `git lfs install` not working

I tried to download a model as instructed here:
https://huggingface.co/facebook/bart-large/tree/main#how-to-use
```
$ git lfs install
git: 'lfs' is not a git command. See 'git --help'.

The most similar commands are
        last
        ls
```

I had to do:
```
apt install git-lfs
```
and then it worked:

```
$ git lfs install
Updated git hooks.
Git LFS initialized.
```

Perhaps it needs a link to:
https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/installing-git-large-file-storage
if apt doesn't have it or a user is on a different setup.

2. [ ] would it be possible to rename "Use in transformers" to "Use/Download" - it wasn't obvious to look there for download instructions. I was trying to click on the files.
3. [x] the fact that the files in the [listing](https://huggingface.co/facebook/bart-large/tree/main#) are clickable and some of them are containing the final data and others contain just a reference and no way to get to the final data is kind of inconsistent and confusing. at the very least the ones with a reference instead of data should have a link to how to get to the data.
4. [ ] ` .gitattributes` is irrelevant to the user in that listing, it's a circumstantial file and not part of the model files, IMHO ;)
5. [ ] <title> is missing (uses generic title) - not optimal for bookmarking/email forwarding

@julien-c

**Comment by julien-c** [comment]
Our assumption was that git-lfs was pretty widespread, but it's an assumption we'd like to check in the coming weeks, and if not, explain/document better. I like the official website: https://git-lfs.github.com/

Let's keep this issue open to find out if many users have issues/questions?

On your second bullet point, we just pushed an update where we display file sizes and download links: https://huggingface.co/facebook/bart-large/tree/main#
let me know if this helps.

**Comment by stas00** [comment]
> Our assumption was that git-lfs was pretty widespread, but it's an assumption we'd like to check in the coming weeks, and if not, explain/document better. I like the official website: https://git-lfs.github.com/

I'm not attached to what you link to ;) I have never used it before.

Probably ideally `git` needs to be made more smart and inform user about this website, rather than "unknown command"

> Let's keep this issue open to find out if many users have issues/questions?

Of course. Please rename it to something more generic then?
 
> On your second bullet point, we just pushed an update where we display file sizes and download links: https://huggingface.co/facebook/bart-large/tree/main#
> let me know if this helps.

This is awesome! Love it!

Can we add the download link from the file's page too in case the user missed the download button on the index page?
i.e from https://huggingface.co/facebook/bart-large/blob/main/pytorch_model.bin

- added an additional nice-to-have item in OP wrt `<title>`,
