### ISSUE TITLE
Pretrain PEGASUS from scratch

### ISSUE THREAD

**Issue by EKebriaei** [huggingface/transformers#8536]
I want to pre-train PEGASUS model from scratch on a language other than English. Is there any way to do this using huggingace API's? The source code released by the authors is complicated in use to pre-train. Also little documentation available to do this.

**Comment by LysandreJik** [comment]
@patil-suraj or @patrickvonplaten can chime in if I'm wrong, but I believe we currently only have fine-tuning & distillation schemes for the BART-family models, no pre-training.

**Comment by patrickvonplaten** [comment]
Hey @EKebriaei -  yeah we sadly don't have any pre-training notebooks for pegasus yet. Are you looking for the summary specific pre-training of pegasus or just the BART-like denoising pre-training?

**Comment by EKebriaei** [comment]
> Hey @EKebriaei - yeah we sadly don't have any pre-training notebooks for pegasus yet. Are you looking for the summary specific pre-training of pegasus or just the BART-like denoising pre-training?

I want to pre-train pegasus on a language other than English.

**Comment by patrickvonplaten** [comment]
Yeah, we don't have a script or good documentation for this yet.

cc https://github.com/huggingface/transformers/issues/8594#issuecomment-731248819

**Comment by EKebriaei** [comment]
> Yeah, we don't have a script or good documentation for this yet.
> 
> cc [#8594 (comment)](https://github.com/huggingface/transformers/issues/8594#issuecomment-731248819)

I have some dependency problems when compiling this:  https://github.com/google-research/pegasus/blob/master/pegasus/ops/pretrain_parsing_ops.cc#L66 
Do you have any comments that help?

**Comment by patrickvonplaten** [comment]
This PR will enable a pretraining script: #8731

**Comment by Skylixia** [comment]
> Yeah, we don't have a script or good documentation for this yet.
> 
> cc [#8594 (comment)](https://github.com/huggingface/transformers/issues/8594#issuecomment-731248819)

Could we follow the same approach you provided [here](https://github.com/huggingface/transformers/issues/5096#issuecomment-645860271) to pretrain BART for PEGASUS ? PEGASUS has also a GSG training objective on top of the BART-like denoising as detailed in the original [paper](https://arxiv.org/pdf/1912.08777.pdf).  
The GSG work by masking the most important sentences according to ROUGE then the target are the missing sentences.
So my attempt by changing your code would be:

```
from transformers import PegasusTokenizer, PegasusForConditionalGeneration, PegasusConfig

tok = PegasusTokenizer.from_pretrained("google/pegasus")
model = PegasusForConditionalGeneration(PegasusConfig())

input_string = ["Pegasus is <mask_2> . <mask_1> it <mask_2> the model ."
decoder_input_string = "<s> It is pure white ."
labels_string = "It is pure white . <eos>"

input_ids = tok(input_string, add_special_tokens=False, return_tensors="pt").input_ids
decoder_input_ids =tok(decoder_input_string, add_special_tokens=False, return_tensors="pt").input_ids
labels = tok(labels_string, add_special_tokens=False, return_tensors="pt").input_ids
 
loss = model(input_ids=input_ids, decoder_input_ids=decoder_input_ids, labels=labels)[0]
```
Does this look reasonable (the selection strategy of masked sentences will naturally need to be implemented)? @patrickvonplaten

**Comment by patrickvonplaten** [comment]
@Skylixia - yes this looks reasonable to me! I guess in the original PEGASUS paper another masking loss was added on top of the encoder to predict the <mask_2> tokens, which would be difficult here (but should also be feasible). But this looks like the right approach to me!

**Comment by adivekar-utexas** [comment]
Hi. I've been struggling with a pretty simple issue trying to get the above code to work.

Essentially, the Pegasus tokenizer's eos is `</s>` (not what is mentioned above) but it does not seem to have a bos symbol. So no matter what combination I try, I keep getting `ValueError: Expected input batch_size (4) to match target batch_size (5).`

**Comment by adivekar-utexas** [comment]
I have opened a new issue with complete detail (and a corrected example) here: https://github.com/huggingface/transformers/issues/11541

**Comment by adivekar-utexas** [comment]
Hi. Could I please get an answer to my question above?

**Comment by ParthParikh04** [comment]
> Yeah, we don't have a script or good documentation for this yet.
> 
> cc [#8594 (comment)](https://github.com/huggingface/transformers/issues/8594#issuecomment-731248819)

@patrickvonplaten Any update on this? I am planning on researching abstractive summarization in a non-English language and the PEGASUS model seems to be a worthwhile model to pursue. It would be great if you could either direct me to any resources or suggest another model to pursue in my project. Thanks!

**Comment by joHussien** [comment]
> > Yeah, we don't have a script or good documentation for this yet.
> > cc [#8594 (comment)](https://github.com/huggingface/transformers/issues/8594#issuecomment-731248819)
> 
> @patrickvonplaten Any update on this? I am planning on researching abstractive summarization in a non-English language and the PEGASUS model seems to be a worthwhile model to pursue. It would be great if you could either direct me to any resources or suggest another model to pursue in my project. Thanks!

@ParthParikh04 Did you figure out a solution to this?

**Comment by ParthParikh04** [comment]
> > > Yeah, we don't have a script or good documentation for this yet.
> > > cc [#8594 (comment)](https://github.com/huggingface/transformers/issues/8594#issuecomment-731248819)
> > 
> > 
> > @patrickvonplaten Any update on this? I am planning on researching abstractive summarization in a non-English language and the PEGASUS model seems to be a worthwhile model to pursue. It would be great if you could either direct me to any resources or suggest another model to pursue in my project. Thanks!
> 
> @ParthParikh04 Did you figure out a solution to this?

Nope, unfortunately not. Please let me know if you end up finding a solution though!
