### ISSUE TITLE
Add a new model ConvBert

### ISSUE THREAD

**Issue by RyanHuangNLP** [huggingface/transformers#8537]
# 🌟 New model addition

Pre-trained language models like BERT and its variants have recently achieved impressive performance in various natural language understanding tasks. However, BERT heavily relies on the global self-attention block and thus suffers large memory footprint and computation cost. Although all its attention heads query on the whole input sequence for generating the attention map from a global perspective, we observe some heads only need to learn local dependencies, which means the existence of computation redundancy. We therefore propose a novel span-based dynamic convolution to replace these self-attention heads to directly model local dependencies. The novel convolution heads, together with the rest self-attention heads, form a new mixed attention block that is more efficient at both global and local context learning. We equip BERT with this mixed attention design and build a ConvBERT model. Experiments have shown that ConvBERT significantly outperforms BERT and its variants in various downstream tasks, with lower training cost and fewer model parameters. Remarkably, ConvBERTbase model achieves 86.4 GLUE score, 0.7 higher than ELECTRAbase, while using less than 1/4 training cost.

## Open source status

* [x] the model implementation is available: (https://github.com/yitu-opensource/ConvBert)
* [x] the model weights are available: (https://drive.google.com/drive/folders/1pSsPcQrGXyt1FB45clALUQf-WTNAbUQa)
* [x] who are the authors: (@zihangJiang @zhoudaquan)

**Comment by RyanHuangNLP** [comment]
there is one implement:https://github.com/JunnYu/ConvBert_huggingface

**Comment by gitabtion** [comment]
I have implemented this model in [https://github.com/gitabtion/ConvBert-PyTorch](https://github.com/gitabtion/ConvBert-PyTorch), and  it pass the unittest right now. :heavy_check_mark:

**Comment by thedarkzeno** [comment]
> I have implemented this model in https://github.com/gitabtion/ConvBert-PyTorch, and it pass the unittest right now. heavy_check_mark

how about a conversion script?
