### ISSUE TITLE
Pretrain BERT with user defined vocabulary

### ISSUE THREAD

**Issue by Jess0-0** [huggingface/transformers#8545]
# 🚀 Feature request

I'm wondering if there is a way to pretrain BERT with user-defined vocabulary, number of layers/heads, and use a WordLevel Tokenizer instead of a WordPiece Tokenizer current BERT uses. Thank you!

## Motivation

This could help the BERT mode to adapt to different tasks.

**Comment by LysandreJik** [comment]
Hi! Yes, you can definitely do so (not sure about the word level). 

You can define a custom model configuration:
```py
from transformers import BertConfig

config = BertConfig(vocab_size=xxx, num_attention_heads=xxx, ...)
```

You can then use that configuration with the `run_mlm.py` script to train your model.

Regarding the tokenizer, you could use a word-level, but you would need to manually modify the files for that. There exists a word-level tokenizer in the `tokenization_bert.py` file that you could leverage for this.

**Comment by mathshangw** [comment]
> tokenization_bert.py

excuse me does this class have the functions that help in word-level, not sub-word level , please ?
