### ISSUE TITLE
modeling_xlnet.py lines 798  torch.eisum('i,d->id', pos_seq, inv_freq)

### ISSUE THREAD

**Issue by lcy081099** [huggingface/transformers#855]
hi  I run position embedding in modeling_xlnet.py , but it not work  , why not torch.eisum('i,d->id', [pos_seq, inv_freq])  ?i use pytorch 0.4.1

**Comment by thomwolf** [comment]
I don't understand your question.

Can you give more details and point to the exact code lines you are referring to?

You cannot provide specific position indices to XLNet if that's what you are trying to do. You have to use the built-in relative embeddings.

**Comment by nguyenvo09** [comment]
For new PyTorch 1.0, the syntax should be `torch.eisum('i,d->id', pos_seq, inv_freq) `
