### ISSUE TITLE
Prophetnet - predicted n-future tokens

### ISSUE THREAD

**Issue by nsankar** [huggingface/transformers#8560]
Hi,

How can we get the predicted n-future tokens **as a string** data from the model output. I couldn't find it in the API doc and sample code. Could you please guide / provide the code snippet for ProphetNet and XLM-Prophetnet ? Thanks in advance.

**Comment by patrickvonplaten** [comment]
Hey @nsankar - that's a good question for the forum https://discuss.huggingface.co/ I think. Currently we don't really support sampling from the "n-future" tokens, but it should not be too difficult - just sample from each of the 1...n logit vectors and then you can use the tokenizer to decode the sampled tokens. So in short, you should do this operation: https://github.com/huggingface/transformers/blob/42111f1d56947797d9dfb0908908f42a22ca9823/src/transformers/generation_utils.py#L843 for all n-future logit vectors and then pass it to the tokenizer.
