### ISSUE TITLE
Wrong model_max_length for BERTOverflow tokenizer

### ISSUE THREAD

**Issue by greav** [huggingface/transformers#8563]
## Environment info

- `transformers` version: 3.4.0
- Platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.29
- Python version: 3.8.5
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): 2.3.1 (False)
- Using GPU in script?: N
- Using distributed or parallel set-up in script?: N

## Information

Hi. I used [BERTOverflow](https://huggingface.co/jeniya/BERTOverflow) and found strange behavior for the tokenizer property `model_max_length`. It is equal 1000000000000000019884624838656, although it should be 512.

## To reproduce
```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('jeniya/BERTOverflow')
print(tokenizer.model_max_length)
```

**Comment by LysandreJik** [comment]
Ah, this is an error, indeed. The uploader should have uploaded a `tokenizer_config.json` containing the model maximum length. I see it only contains the `do_lower_case` argument right now.

@julien-c what should we do here? Should we update that configuration ourselves?

Also @thomwolf @julien-c, I feel like we should have sensible defaults for each model. This is a `BertModel` which currently only has access to absolute positional embeddings. It doesn't make sense to have an unlimited `model_max_length`. I think `BertTokenizer` and all its relatives should have a default of `512`.

**Comment by julien-c** [comment]
@LysandreJik Yes, our policy here is that we fix the config ourselves and notify the model author (via email/GitHub mention/anything). Feel free to do it and link the resulting commit from here.

 (use your hf.co email/author name for your commit to be linked to your hf.co user profile)

**Comment by LysandreJik** [comment]
Updated with [212cd3e](https://huggingface.co/jeniya/BERTOverflow/commit/212cd3ef9615e7292da65a49162e0beb0cd3d604) and sent an email.

**Comment by julien-c** [comment]
see [huggingface.co:212cd3e](https://huggingface.co/jeniya/BERTOverflow/commit/212cd3ef9615e7292da65a49162e0beb0cd3d604)

**Comment by kretes** [comment]
I happen to get the same error for all of:

```
dmis-lab/biobert-base-cased-v1.1
dmis-lab/biobert-large-cased-v1.1
microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract
emilyalsentzer/Bio_ClinicalBERT
```

I understand that in user code I should just do a fallback to sensible default if I get that large value, but that seem like a problem not related to a single model.
