### ISSUE TITLE
"setup.py" does not seem to have been updated for v3.5.1

### ISSUE THREAD

**Issue by forest1988** [huggingface/transformers#8566]
## Environment info

I try 
```
!git clone https://github.com/huggingface/transformers.git
%cd transformers/
!pip install -e .
```
on Colaboratory.
     
- `transformers` version: 3.5.0   <- this seems strange.
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.7.0+cu101 (True)
- Tensorflow version (GPU?): 2.3.0 (True)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help
 
 documentation: @sgugger

## Information

"setup.py" does not seem to have been updated for v3.5.1.

When I install transformers by `pip install -e .`, the version of transformers is shown as v3.5.0.

## To reproduce

I try 
```
!git clone https://github.com/huggingface/transformers.git
%cd transformers/
!pip install -e .
```
on Colaboratory after v3.5.1 release.

Then,
```
import transformers
transformers.__version__
```
returns 
```
'3.5.0'
```

## Expected behavior

The return of `transformers.__version__` is expected to be '3.5.1' now, if my understanding is not wrong.

Maybe, in  https://github.com/huggingface/transformers/blob/afb50c663a5d5623906ead1e87481926467d59fa/setup.py#L120 

'3.5.0' should be changed to '3.5.1'.

Is my understanding correct? Sorry if I misunderstand your intension.

**Comment by forest1988** [comment]
I found https://github.com/huggingface/transformers/commit/d5b3e56de5376aa85ef46e7f0325139d9e299a41 and it seems the related files are updated there.
If there is a reason (or rules for releases) not to merge the change into the master branch, I'm sorry for opening this issue that I haven't fully considered.

**Comment by sgugger** [comment]
This was a hotfix on a branch which is why we didn't update master (mostly because we forgot).
To do things right, we'll actually put v4.0.0-dev since that's what master is right now :-)

**Comment by forest1988** [comment]
@sgugger 
Thank you for your quick and detailed response!
Now I understood what is the reason.
I appreciate your creating a new PR for this issue.
