### ISSUE TITLE
The Albert tokenizer file cannot download automatically and the official Albert tokenizer file is wrong, I cannot use it.

### ISSUE THREAD

**Issue by probe2** [huggingface/transformers#8587]
Have anybody meet the same problem?

**Comment by thomwolf** [comment]
Do you mind following and filing in the issue template?
Thanks

**Comment by aLowMagic** [comment]
I cannot load the offiline vocab as well:
RuntimeError: Internal: C:\projects\sentencepiece\src\sentencepiece_processor.cc(824) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
but it can run for me to download the vocab automatically.
