### ISSUE TITLE
PEGASUS do not have mask token

### ISSUE THREAD

**Issue by ShichaoSun** [huggingface/transformers#8594]
@mfuntowicz @patrickvonplaten 

Hi,

I am using PEGASUS  google/pegasus-large

I would like to fill the mask sentence of a document , i.e. try the pretraining task. But I don't find the mask_token. 

1. from transformers import PegasusTokenizer
2. tok = PegasusTokenizer.from_pretrained("google/pegasus-large")
3. tok.mask_token

output is "Using mask_token, but it is not set yet."

**Comment by patrickvonplaten** [comment]
Hey @ShichaoSun - thanks for the issue! 
 I agree with you that Pegasus should have some mask tokens defined and I'd set `tokenizer.mask_token` to Pegasus' MLM mask token => `[MASK_2]` and add an additional `mask_token_sent` ... 

I'm still waiting for some more insight on Pegasus of the Pegasus expert @sshleifer -> https://github.com/huggingface/transformers/issues/8689 .

I'll hope to get an answer there to be sure that adding the `[MASK_1]` and `[MASK_2]` tokens is the correct thing to do here!

**Comment by ShichaoSun** [comment]
Hi @patrickvonplaten ,
Really thanks for your reply and great job !

**Comment by zanderbush** [comment]
Is it possible to MASK several tokens using Pegasus?
