### ISSUE TITLE
Missing `tokenizers` file?

### ISSUE THREAD

**Issue by guotong1988** [huggingface/transformers#8609]
In latest https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils_base.py

![image](https://user-images.githubusercontent.com/4702353/99480139-759b2d00-2992-11eb-8763-87b6b246819a.png)

But there is no `tokenizers` file

**Comment by NielsRogge** [comment]
Hi,

tokenizers is not a file. It's an entire [library](https://github.com/huggingface/tokenizers) built by the Hugging Face team. The code that you show will import some functions from that library, if it's available.
