### ISSUE TITLE
Bi-Directional Reformer text multi class classification

### ISSUE THREAD

**Issue by Zozos972** [huggingface/transformers#8641]
# 🚀 Feature request

I am fairly new to transformers, but good experience in ML. I have tried to start by building a RoBERTa multi class classification model but the doc and examples are not clear.

Can you point me to the set of literature that would get me going with RoBERTa?

Afterwards, I would love to support the effort building the Bi-Directional Reformer text multi class classification model. Of if you send me the docs, I can jump directly to the Reformer model.
Many thanks,
Z

**Comment by LysandreJik** [comment]
Have you taken a look at the [RobertaForSequenceClassification](https://huggingface.co/transformers/model_doc/roberta.html#tfrobertaforsequenceclassification) documentation page?

You might also be interested in the [sequence classification task](https://huggingface.co/transformers/task_summary.html#sequence-classification) documentation page.
We aim to have the exact same API for all models, so while this example showcases BERT with the auto models, you can use a RoBERTa architecture instead.


You can see the [ReformerForSequenceClassification](https://huggingface.co/transformers/model_doc/reformer.html#reformerforsequenceclassification) documentation page if you're particularly interested in Reformer.

**Comment by jmdepinay** [comment]
Excellent! Thanks,
Z
