### ISSUE TITLE
Using Fp16 half precision makes Bert prediction slower.

### ISSUE THREAD

**Issue by Oxi84** [huggingface/transformers#865]
When I use:

     model = BertForMaskedLM.from_pretrained('bert-large-cased') 
     model = model.half()
     model.eval()
     model.to('cuda')

by adding Fp16:

     model = model.half()

It runs around 50% slower. Why is that?
 I run it on ubuntu 18.04, cuda 9, pytorch 1.1 and python 3.6.8

**Comment by Oxi84** [comment]
gtx 1080. Is there any other way to make the predictions faster?

**Comment by thomwolf** [comment]
Hi, you need at least a Volta GPU to get benefits from fp16 unfortunately.

**Comment by ntubertchen** [comment]
@thomwolf  Does P100 applicable?

**Comment by thomwolf** [comment]
I don't think so
