### ISSUE TITLE
RAG: OSError: Can't load tokenizer for 'facebook/rag-sequence-nq/question_encoder_tokenizer'

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#8651]
Hi I am trying to run [use_own_knowledge_dataset.py] (https://github.com/huggingface/transformers/blob/master/examples/rag/use_own_knowledge_dataset.py)) with **Transformers  Version: 3.5.1** ((from your latest [PR](https://github.com/huggingface/transformers/pull/8585)).  But it gives the following error.

```

OSError: Can't load tokenizer for 'facebook/rag-sequence-nq/question_encoder_tokenizer'. Make sure that:

- 'facebook/rag-sequence-nq/question_encoder_tokenizer' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'facebook/rag-seq
```uence-nq/question_encoder_tokenizer' is the correct path to a directory containing relevant tokenizer files

**Comment by julien-c** [comment]
Can you try installing transformers from master?

**Comment by shamanez** [comment]
Thanks for working perfectly when loading from sources.
