### ISSUE TITLE
XLnet sentence vector

### ISSUE THREAD

**Issue by luv4me** [huggingface/transformers#867]
how can i get the XLnet sentence vector by pytorch-transformers. I use the sample but I only get the word vector. it drives me crazy

**Comment by thomwolf** [comment]
You can train the model on a downstream task to get a sentence vector related to your task or you can get a sentence vector is by averaging or max-pooling the output sequence of token hidden-states.

**Comment by cpcdoy** [comment]
Try doing:

```Python
model = model_class.from_pretrained(pretrained_weights,
                                    output_hidden_states=True,
                                    output_attentions=True)

sequence_summary = SequenceSummary(model.config)

es = torch.tensor([tokenizer.encode(s)])
# sentence embedding
t = sequence_summary(model(es)[0])

**Comment by rishibommasani** [comment]
A simple strategy is to take the concatentation of the last hidden state, the mean-pooling, and the max-pooling (tends to be a reasonably good baseline pooling strategy, e.g. [ULMFit](https://arxiv.org/pdf/1801.06146.pdf))

**Comment by luv4me** [comment]
@cpcdoy hey, and I have a question why the sentence is not stationary.

**Comment by hughperkins** [comment]
So, we should pool over all hidden states, and not just use the hidden state corresponding to `[CLS]`?

**Comment by thomwolf** [comment]
I would go with @rishibommasani's solution for a general "semantic" sentence embeddings or fine-tuning and using the `[CLS]` for a task-specific sentence embedding.
