### ISSUE TITLE
use the torchscript in a gpt model is slower  than origin one.

### ISSUE THREAD

**Issue by lonelydancer** [huggingface/transformers#8683]
## Environment info

     
- `transformers` version:2.1.1
- Platform:Linux version 4.15.0-76-generic (buildd@lcy01-amd64-029) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) 
- Python version:3.6.9
- PyTorch version (GPU?): 1.6.0+cu101
- Using GPU in script?:No
-GPU-tesla k80

## Information
when i am using torchscipts to speed up the interference of my gpt2 model, I found it is slower than the origin one

traced model 0.6959998607635498
origin model 0.3259282112121582

The problem arises when using:
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] my own task : gpt2 LM

## To reproduce

follow the code below
https://github.com/lonelydancer/algorithm/blob/master/test.py

## Expected behavior

the traced model is faster.

**Comment by LysandreJik** [comment]
Hi! TorchScript requires tracing the model beforehand, which slows down the first forward pass through the model. Could you print the timing of the iterations following the initial one?

**Comment by lonelydancer** [comment]
Hi, @LysandreJik  
do you mean  in the first iteration "loaded_model(input_ids)"  will slow?
I alreay traced model before that.

traced_model = torch.jit.trace(model, input_ids)
torch.jit.save(traced_model, 'trace_gpt2.pt')

loaded_model = torch.jit.load('trace_gpt2.pt').to('cuda')
loaded_model.eval()

#print (loaded_model)
start = time.time()
for i in range(100):
    with torch.no_grad():
        loaded_model(input_ids)
end = time.time()
print ('traced model',(end-start))
