### ISSUE TITLE
Cannot load tokenizer in community T5 pretrained model

### ISSUE THREAD

**Issue by minhtam2048** [huggingface/transformers#8699]
## Environment info
- `transformers` version: 3.5
- Platform: Window 10
- Python version: 3.7.9
- PyTorch version (GPU?): 1.7.0+cpu (False)
- Tensorflow version (GPU?): 2.3.1 (False)
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False

### Who can help

 T5: @patrickvonplaten

## Information

I'm trying to use the **sshleifer/t5-base-cnn** for summarization task. But It seem likes there is something wrong with the tokenizer. 

    tokenizer = T5Tokenizer.from_pretrained('sshleifer/t5-base-cnn')
    model = T5ForConditionalGeneration.from_pretrained('sshleifer/t5-base-cnn')
    
This code return an error:

    OSError: Can't load tokenizer for 'sshleifer/t5-base-cnn'. Make sure that:

    - 'sshleifer/t5-base-cnn' is a correct model identifier listed on 'https://huggingface.co/models'

    - or 'sshleifer/t5-base-cnn' is the correct path to a directory containing relevant tokenizer files

Can someone point out what I am missing or Is there any problem with my code ?
Many thanks.

**Comment by julien-c** [comment]
Yes, that model from @sshleifer does not bundle its own tokenizer, as you can see in the list of files: https://huggingface.co/sshleifer/t5-base-cnn/tree/main

We'll add this info to the model card, but you can just use the one from t5: `T5Tokenizer.from_pretrained("t5-base")`

**Comment by minhtam2048** [comment]
@julien-c Thank you for your help
