### ISSUE TITLE
TypeError: an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by parthplc** [huggingface/transformers#8701]
While using trainer class to finetune gpt-2 on Hindi dataset. It's outputting the following error
```
TypeError                                 Traceback (most recent call last)
<ipython-input-44-3435b262f1ae> in <module>()
----> 1 trainer.train()

5 frames
/usr/local/lib/python3.6/dist-packages/transformers/data/datasets/language_modeling.py in __getitem__(self, i)
     99 
    100     def __getitem__(self, i) -> torch.Tensor:
--> 101         return torch.tensor(self.examples[i], dtype=torch.long)
    102 
    103 

TypeError: an integer is required (got type NoneType)
```
Here is the link: https://colab.research.google.com/drive/1um5UeY9hasmjPNcR1WkBe2uDDFhLUBrX?usp=sharing

**Comment by patrickvonplaten** [comment]
Hey @parthplc,

Could you try to post a very short code snippet that can reproduce the error. It's too time-consuming to go through such a big notebook sadly

**Comment by Octopirate1** [comment]
@parthplc Please post a solution if you close the issue. There is none in your colab as far as I can see (`model.resize_token_embeddings(len(tokenizer))` is the only relevant code I can see and it doesn't fix the problem).
