### ISSUE TITLE
providing the user with possibility to set the cache path 

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#8703]
Dear HuggingFace team,

In the codes of huggingface, most of the time there is some cache_path which is on the home directory,

/idiap/home/rkarimi/.cache/huggingface/datasets/downloads

could you provide me with a command to set a different cache_path? to me this is hard-coded in the codes or I am missing something.

Thank you.

Best regards
Rabeeh

**Comment by sgugger** [comment]
This path is the default `cache_path` of the datasets library, not transformers. You can change it by setting an environment variable named `HF_HOME` to the path you want, the datasets will then be cached in this path suffixed with "/datasets/"

**Comment by rabeehk** [comment]
Hi
thank you, the huggingface codes gebnerally also create an empty folder
titled '  ' when I run it, which is specifies the caching folder address,
could it be possible not to create this folder?
thanks
Best
Rabeeh

**Comment by sgugger** [comment]
We would need to see the code you are running that creates this empty folder named `" "` to be able to help.

**Comment by rabeehk** [comment]
Hi there
I am training seq2seq_trainer codes. I have adapted it for my use case but
in the original version of codes should also happen.
thanks
Best
Rabeeh
