### ISSUE TITLE
Broken links in example for torch.load() after. converting tensorflow checkpoint to pytorch save model

### ISSUE THREAD

**Issue by apurvaasf** [huggingface/transformers#8720]
The links for  run_bert_extract_features.py, run_bert_classifier.py, and run_bert_squad.py are all broken [here](https://huggingface.co/transformers/v2.4.0/converting_tensorflow_models.html). Could someone point me to a notebook where I can find examples for loading from a PyTorch save file pytorch_model.bin?

**Comment by LysandreJik** [comment]
If I understand correctly, you're trying to load a pytorch model from a `pytorch_model.bin`? If so, have you taken a look at the [quickstart](https://huggingface.co/transformers/v2.4.0/quickstart.html#main-concepts)? The `from_pretrained` method is probably what you're looking for.
