### ISSUE TITLE
It seem do not support convert multilabel classification model  to onnx  ?

### ISSUE THREAD

**Issue by MrRace** [huggingface/transformers#8726]
I have fine tune my multilabel classification model(pytorch)，and try to use the `from transformers.convert_graph_to_onnx import convert` to convert the pytorch model to onnx model. As the `pipeline_name` is pre-defined, and it seems not  be suited to multilabel classification， therefor I try use `pipeline_name="sentiment-analysis"`, however when reload the onnx model, its prediction result seems wrong. Could you tell how should i do to get the right result？ Thanks a lot!

**Comment by mfuntowicz** [comment]
Hi @MrRace, 

thanks for reporting the issue. 

What model are you using as multilabels classification support?

**Comment by MrRace** [comment]
> Hi @MrRace,
> 
> thanks for reporting the issue.
> 
> What model are you using as multilabels classification support?

Thanks for you reply. I use BERT to do multilabels classification. And want to export the fine tuned model to onnx.

**Comment by mfuntowicz** [comment]
Looking at it!

**Comment by MrRace** [comment]
> Looking at it!

Looking forward to your reply!

**Comment by MrRace** [comment]
Hi @mfuntowicz  Is there any suggestion for it?
