### ISSUE TITLE
[core] transformers version number normalization

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#8749]
It looks that we need to either normalize the `transformers` version number to one of the accepted formats:

```
x.y.z
x.y.z.dev0
x.y.z.rc1
```
or silence the warning.

Currently, `setuptools` doesn't like `-rc-1` and `-dev`, as you can see from:

```
python setup.py --name
.../python3.8/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '4.0.0-rc-1' to '4.0.0rc1'
```
with `4.0.0-dev`
```
python3.8/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '4.0.0-dev' to '4.0.0.dev0'
```

Otherwise, this warning will be showing up all the time during `make style` and friends once https://github.com/huggingface/transformers/pull/8645 is merged.

@sgugger, @LysandreJik

**Comment by sgugger** [comment]
We're making a release today, so will change the version number to the proper format just after :-)

**Comment by LysandreJik** [comment]
Following what @sgugger said!
