### ISSUE TITLE
What would be the license of the model files available in Hugging face repository?

### ISSUE THREAD

**Issue by jaingaurav3** [huggingface/transformers#8786]
Dear Team,

Could you clarify what would be the license for different models pushed to hugging face repo like legal_bert, contracts_bert etc? Would the model file follows the same license i.e. Apache 2.0 like the hugging face library?

Regards
Gaurav

**Comment by LysandreJik** [comment]
Maybe @julien-c can answer!

**Comment by julien-c** [comment]
You can check on the model hub:
eg. apache-2.0 models: https://huggingface.co/models?filter=license:apache-2.0
mit models: https://huggingface.co/models?filter=license:mit

etc.

**Comment by jaingaurav3** [comment]
Thanks @julien-c for the update.
