### ISSUE TITLE
Use GPT to assign sentence probability/perplexity given previous sentence? 

### ISSUE THREAD

**Issue by TalitaAnthonio** [huggingface/transformers#8802]
Hi!

Is it possible to use GPT to assign a sentence probability given the previous sentences? 
I have seen this code here, which can be used to assign a perplexity score to a sentence: 

https://github.com/huggingface/transformers/issues/473

But is there a way to compute this score given a certain context (up to 1024 tokens)?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
