### ISSUE TITLE
HuggingFace pipeline sentiment analysis giving wrong results.

### ISSUE THREAD

**Issue by vishwa30** [huggingface/transformers#8811]
I am just starting with hugging face and following the official doc. When using sentiment analysis pipeline I am getting incorrect output. I am not sure what's the reason behind it.

```
from transformers import pipeline
classifier=pipeline('sentiment-analysis')
text='This is just a statement'
a=classifier(text)
print(a)

```
Giving output as:
[{'label': 'NEGATIVE', 'score': 0.9583144783973694}]

I have changed the input with different sentences it is having problem with neutral statements but is able to predict the positive and negative statements, which have words like {"awesome","good","bad"}. 

Statements I have tried and respective output:
1. 'Today is thursday'                             {'label': 'POSITIVE', 'score': 0.987697184085846}
2. 'Give me my water bottle'                 {'label': 'NEGATIVE', 'score': 0.855629563331604}
3. 'Its raining outside'                            {'label': 'POSITIVE', 'score': 0.8293998837471008}
4. 'You are awesome'                            {'label': 'POSITIVE', 'score': 0.9998681545257568}
5. 'I hate you'                                        {'label': 'NEGATIVE', 'score': 0.9991129040718079}

**Comment by patrickvonplaten** [comment]
Hey @vishwa30 - what exactly do you mean by incorrect output? -> The model obviously doesn't always classify the input correctly. Since this issue doesn't seem to be a bug, could you maybe look in the forum whether people asked a similar question before and if not post this one there? :-)

https://discuss.huggingface.co/

**Comment by vishwa30** [comment]
@patrickvonplaten Sure! I will do that. Thanks!!
