### ISSUE TITLE
I can not find a Linear layer in the end of Multi-Head Attention layer like Figure 2 right, could someone help me solve it

### ISSUE THREAD

**Issue by BYRTIMO** [huggingface/transformers#8814]

**Comment by patrickvonplaten** [comment]
A bit more context would be appreciated here

**Comment by BYRTIMO** [comment]
Hellow, In multi-head attention layer, after concated paper say there have a linear project layer, but I can not find such layer in "multihead_attention" function. Could you help me solve it, thanks?
