### ISSUE TITLE
cache reuse

### ISSUE THREAD

**Issue by xwwwwww** [huggingface/transformers#8817]
I have downloaded wikitext by `load_dataset("wikitext", "wikitext-2-raw-v1")`, and get the cache file in `.cache/huggingface/datasets`,

then I try to copy the `huggingface/datasets` folder to the lab server to reuse but fails.

What's the proper way to reuse the cache downloaded on another pc?

**Comment by thomwolf** [comment]
You should use [`save_to_disk`](https://huggingface.co/docs/datasets/package_reference/main_classes.html?highlight=save#datasets.DatasetDict.save_to_disk) and [`load_from_disk`](https://huggingface.co/docs/datasets/package_reference/loading_methods.html?highlight=save_to_disk#datasets.load_from_disk):

```python
import datasets
dataset = datasets.load_dataset("wikitext", "wikitext-2-raw-v1")
# Will download and preprocess the dataset
dataset.save_to_disk("PATH/TO/FOLDER")

# On the other machine - reload the ready to use dataset
dataset = datasets.load_from_disk("PATH/TO/FOLDER")
```

**Comment by xwwwwww** [comment]
thanks!
