### ISSUE TITLE
Shared vocabulary with EncoderDecoderModel

### ISSUE THREAD

**Issue by bayanbatn** [huggingface/transformers#8821]
# 🚀 Feature request
Currently, two separate models are instantiated as encoder/decoder when using this model class. It would be useful in a lot of fine-tuning applications (i.e. summarization) to share the same embeddings between the encoder / decoder classes -- is this something that could be supported with the library?

**Comment by LysandreJik** [comment]
I believe the `EncoderDecoderConfig` class has an argument `tie_encoder_decoder` which can be used to share weights between the encoder and decoder.

Is this what you're looking for?

@patrickvonplaten

**Comment by bayanbatn** [comment]
Thanks @LysandreJik; it's close enough to what I'm looking for. Closing this issue.

**Comment by patrickvonplaten** [comment]
Hey @bayanbatn, 

We are currently working on a function (see #8224)  that automatically ties encoder and decoder word embeddings only in an automatic fashion...for now what one can do is to simply set it yourself via

```python
model.decoder.word_embeddings = model.encoder.word_embeddings
```
