### ISSUE TITLE
error: sentencepiece 0.1.94 is installed but sentencepiece==0.1.91 is required by {'transformers'}

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#8827]
## Environment info
     
- `transformers` version: 3.5.1
- Platform: google cloud 
- Python version: 3.7 
- PyTorch version (GPU?): TPU, 1.6
- Tensorflow version (GPU?): - 
- Using GPU in script?: - 
- Using distributed or parallel set-up in script?: - 

### Who can help
 tokenizers: @mfuntowicz
 Trainer: @sgugger
 examples/distillation: @VictorSanh
 examples/seq2seq: @patil-suraj

## Information
I am using requirements.txt file inside examples, and installing it, it fails with this error: 

error: sentencepiece 0.1.94 is installed but sentencepiece==0.1.91 is required by {'transformers'}

here is my setup script, as mentioned in requirements of transformers 3.5.1 for running the examples. thank you
   ```
   install_requires=[
        'sentencepiece != 0.1.92',
        'transformers==3.5.1',
        'tensorboard',
        'scikit-learn',
        'seqeval',
        'psutil',
        'sacrebleu',
        'rouge-score',
        'tensorflow_datasets',
        'pytorch-lightning==1.0.4',
        'matplotlib',
        'git-python==1.0.3',
        'faiss-cpu',
        'streamlit',
        'elasticsearch',
        'nltk',
        'pandas',
        'datasets',
        'fire',
        'pytest',
        'conllu',
        'tf-nightly',
        'google-cloud-storage',
      ],

```

**Comment by LysandreJik** [comment]
The error tells you it wants SentencePiece 0.1.91, can you install that version instead?
```
pip install -U sentencepiece==0.1.91
```
We should update the requirements.txt file to reflect this. Do you want to open a PR?
