### ISSUE TITLE
logging.set_verbosity_error() displays dict instead of NotebookTrainingTracker

### ISSUE THREAD

**Issue by lewtun** [huggingface/transformers#8831]
## Environment info

     
- `transformers` version: 4.0.0-rc-1
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.7.0+cu101 (True)
- Tensorflow version (GPU?): 2.3.0 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help

@sgugger 

## Information

Model I am using (Bert, XLNet ...): `distilbert-base-uncased`

The problem arises when using:
* [] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

Following the [docs](https://huggingface.co/transformers/main_classes/logging.html#logging) I was looking for a way to turn off the warnings that `transformers` shows when loading a new model and believe that `logging.set_verbosity_error()` should do the trick. 

However, when working in a _Jupyter notebook environment_, I find that setting the logging level to error produces unexpected output from the `Trainer`, namely that I get a `dict` like

```
{'loss': 0.33437405395507813, 'learning_rate': 1.308411214953271e-06, 'epoch': 0.9345794392523364}
{'eval_loss': 0.509843111038208, 'eval_matthews_correlation': 0.5011235129840701, 'epoch': 1.0}
{'epoch': 1.0}
```

instead of the progress bar and table of metrics:

![Screen Shot 2020-11-28 at 4 21 34 pm](https://user-images.githubusercontent.com/26859204/100519061-caf6eb80-3195-11eb-83c1-47eeee4414cc.png)

I encountered the problem in my own experiments, but have also been able to reproduce it in @sgugger's tutorial on the GLUE tasks: https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/text_classification.ipynb

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

The task is GLUE

## To reproduce

1. Set the logging verbosity to _error_ in the first cell of the notebook, i.e. with

```
# Turn off warnings
import transformers
transformers.logging.set_verbosity_error()
```

2. Load and encode dataset
3. Configure trainer
4. Run training
```
# With logging.set_verbosity_error() we lose the metrics table :(
trainer.train()
# Output
{'loss': 0.33437405395507813, 'learning_rate': 1.308411214953271e-06, 'epoch': 0.9345794392523364}
{'eval_loss': 0.509843111038208, 'eval_matthews_correlation': 0.5011235129840701, 'epoch': 1.0}
{'epoch': 1.0}
TrainOutput(global_step=535, training_loss=0.34615044994889016)
```

I have trimmed down @sgugger's tutorial to create a reproducible example: https://colab.research.google.com/gist/lewtun/21d44a20f94f480dfa2891f587323ffd/logging-bug-in-trainer.ipynb

## Expected behavior

Changing the logging level should not interfere with the display of the progress bar or table of metrics in Jupyter notebooks.

**Comment by sgugger** [comment]
Hi there, I'm afraid this is not a bug bu how the default of `disable_tqdm` behaves. As shown in the [docs](https://huggingface.co/transformers/main_classes/trainer.html#trainingarguments), it defaults to `False` if your verbosity level is at warn or lower, `True` otherwise. So you need to pass along `disabel_tqm=False` to override the default when using this logging level.

**Comment by lewtun** [comment]
Sorry for the silly oversight! 

I saw the `disable_tqdm` flag but didn't realise that "progress bars" also referred to the table of metrics. Would a small clarification in the docs be warranted (I'm happy to do it)?

**Comment by sgugger** [comment]
Yes we can definitely make the docstring clearer.
