### ISSUE TITLE
cannot run "examples/language-modeling/run_mlm.py"

### ISSUE THREAD

**Issue by HenryPaik1** [huggingface/transformers#8835]
## Environment info

     
- `transformers` version:
- Platform: cmd
- Python version: 3.7
- PyTorch version (GPU?): 1.6.0
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help
 albert, bert, GPT2, XLM: @LysandreJik 

## Information

Model I am using (Bert)

The problem arises when using:
* [o] the official example scripts: (give details below)
* [] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [o] my own task or dataset: (give details below)

## To reproduce

```
python examples/language-modeling/run_mlm.py

>>
Traceback (most recent call last):
  File "examples/language-modeling/run_mlm.py", line 30, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
```

**Comment by mattivi** [comment]
You need to install datasets library: https://github.com/huggingface/datasets
```
pip install datasets
```

**Comment by HenryPaik1** [comment]
Thanks!
