### ISSUE TITLE
How to globally change the PYTORCH_PRETRAINED_BERT_CACHE path

### ISSUE THREAD

**Issue by sysu-zjw** [huggingface/transformers#8846]
Hi, all. I don't have enough disk space under `~/` to download the pre-trained model. When I run others' experiments, I always need to change their code from
```
model = BertForQuestionAnswering.from_pretrained(args.bert_model, \
                            cache_dir=PYTORCH_PRETRAINED_BERT_CACHE'distributed_{}'.format(-1))
```
to something like
```
PYTORCH_PRETRAINED_BERT_CACHE = ELSE_WHERE
model = BertForQuestionAnswering.from_pretrained(args.bert_model, \
                            cache_dir=PYTORCH_PRETRAINED_BERT_CACHE'distributed_{}'.format(-1))
```
or
```
model = BertForQuestionAnswering.from_pretrained(args.bert_model, \
                            cache_dir=ELSE_WHERE)
```

For the convenience of those who don't have enough disk under home dir `~/`, I wonder if there is any way to globally change this `PYTORCH_PRETRAINED_BERT_CACHE` value once and for all.

**Comment by LysandreJik** [comment]
Hello! You can set the environment variable `TRANSFORMERS_CACHE` to define which location should be used to store weights.

**Comment by sysu-zjw** [comment]
@LysandreJik Thanks. 
Just to make sure I understand your point correctly. If I run `TRANSFORMERS_CACHE=ELSE_WHERE train.sh` in cmd, are all the downloaded pretrained cache files stored under `ELSE_WHERE` rather than `~/.pytorch_pretrained_bert`?

**Comment by LysandreJik** [comment]
Ah, given your logs, it seems you're running on a very very old version (`pytorch_pretrained_bert`, which is 1+ years old). While we recommend updating to more recent versions, you should be able to obtain the same behavior by setting the `PYTORCH_PRETRAINED_BERT_CACHE` environment variable instead.

For future issues, please always complete the issue template, the information related to your environment is especially important for us to help you correctly.
