### ISSUE TITLE
KeyError: 'mt5'

### ISSUE THREAD

**Issue by astakara48** [huggingface/transformers#8847]
I am trying to use the google/mt5 model, but I get KeyError: 'mt5'. How do I fix this?

KeyError                                  Traceback (most recent call last)
<ipython-input-2-207aa15555f1> in <module>
----> 1 tokenizer = AutoTokenizer.from_pretrained("google/mt5-small")

/usr/local/lib/python3.8/dist-packages/transformers/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    304         config = kwargs.pop("config", None)
    305         if not isinstance(config, PretrainedConfig):
--> 306             config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
    307 
    308         if "bert-base-japanese" in str(pretrained_model_name_or_path):

/usr/local/lib/python3.8/dist-packages/transformers/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    334 
    335         if "model_type" in config_dict:
--> 336             config_class = CONFIG_MAPPING[config_dict["model_type"]]
    337             return config_class.from_dict(config_dict, **kwargs)
    338         else:

KeyError: 'mt5'

**Comment by seregadgl** [comment]
pip install transformers==4.0.0rc1 sentencepiece

**Comment by astakara48** [comment]
> pip install transformers==4.0.0rc1 sentencepiece

Thank you! You are my hero
