### ISSUE TITLE
can the BertModel convert to onnx? whether any one had done sucessfully ?

### ISSUE THREAD

**Issue by passion765** [huggingface/transformers#8865]

**Comment by FL33TW00D** [comment]
2 resources in the thread linked by valhalla: https://discuss.huggingface.co/t/how-to-apply-pruning-on-a-bert-model/1658/5

**Comment by passion765** [comment]
> 2 resources in the thread linked by valhalla: https://discuss.huggingface.co/t/how-to-apply-pruning-on-a-bert-model/1658/5

Thank you very much for your warm reply, I will study it.
