### ISSUE TITLE
length_penalty not influencing results (Bart, Pegasus)

### ISSUE THREAD

**Issue by marcoabrate** [huggingface/transformers#8867]
Hello,

I am experimenting with the generative parameters of the two models Bart and Pegasus. In particular, I am having trouble with the `length_penalty` parameter, since changing it does not change the output of the model.

I am summarizing two different chapters of a book (# tokens around 1k) and this is the code I am using:

```
    model.generate(
        b0ch1sec1_text_enc,
        min_length = 150,
        max_length = 350,
        num_beams = 2,
        length_penalty = lp,
        early_stopping = True)[0]
```

With `lp` swiping from 0.1 to 2 and model being either `bart-large-cnn` or `pegasus-large`.

Do you have any idea why the output does not change at all?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
