### ISSUE TITLE
Exporting ALBERT model to onnx increases model size by 7x

### ISSUE THREAD

**Issue by unography** [huggingface/transformers#8869]
I'm trying to export `albert-base-v2` model to onnx using

`python -m transformers.convert_graph_to_onnx --framework pt --model albert-base-v2 --quantize albert.onnx --opset 12`

The original pytorch model size is around 45 MB (https://huggingface.co/albert-base-v2), but the exported model size is around 340 MB.

How do I keep the model's size same?

**Comment by LysandreJik** [comment]
@mfuntowicz might have an idea. I'm guessing that what it does is copy each layer, while all the layers have shared weights and should point to the same tensor.
