### ISSUE TITLE
Extracting important information

### ISSUE THREAD

**Issue by krrishdholakia** [huggingface/transformers#8883]
I'm trying to extract important information from a lecture transcript. What's the best way to go about doing this ? This would be without a particular query parameter, just generally important information in the global context of the lecture.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
