### ISSUE TITLE
providing an example with a dummy iterative dataloaders

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#8891]
Hi
I have tested the trainer.py with iterative datasets and this does not work in distributed case, I shard the data across the cores. Could you please assist me in providing me with a dummy iterative dataloader for finetune_seq2seq.py model which runs fine with xla_spawn.py on TPU so I get some understanding which functions needs to be implemented. I really need to make this work, and trainer.py does not seem to work with iterative datasets or I am missing how to do it properly. thanks 

@sgugger

**Comment by sgugger** [comment]
Trainer does indeed not work in distributed fashion with iterative datasets. You need to convert your iterative dataset to a regular dataset for the time being.
