### ISSUE TITLE
Fine-tune with custom data

### ISSUE THREAD

**Issue by whoafridi** [huggingface/transformers#8913]
1. What is the difference between `run_squad.py` & `run_squad_trainer.py` ?

I've squad like dataset. 2. What script I used for fine-tuning with my own dataset?

**Comment by LysandreJik** [comment]
`run_squad.py` is more complete right now, as `run_squad_trainer.py` can't do evaluation (yet! it will be possible in a few days).

We try to keep the github issues for bugs/feature requests.
For next time, could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!

**Comment by whoafridi** [comment]
Okay sure. I don't know about the forum - sorry for that. Thank you @LysandreJik
