### ISSUE TITLE
Impossible to use  sentencepiece

### ISSUE THREAD

**Issue by lematmat** [huggingface/transformers#8916]
Hi,

I explicitly installed both the latest version of transformers (v4.0.0) and Sentencepiece (v0.1.84) as it is specified as it is specified in the release history:
![Capture d’écran 2020-12-03 à 16 12 29](https://user-images.githubusercontent.com/19993147/101047903-7fbc4e80-3582-11eb-9e72-ada4a1b55366.png)

And the I I try to import MarianMT Tokeninzer  I have the following issue:

![Capture d’écran 2020-12-03 à 16 16 41](https://user-images.githubusercontent.com/19993147/101048715-26a0ea80-3583-11eb-9448-568a9e1ebe60.png)

So, any idea why  I 'm getting that issue ?

Best Regards,

Leman

**Comment by LysandreJik** [comment]
Have you tried restarting the kernel after installing `sentencepiece`?

**Comment by lematmat** [comment]
Yes, I did, with:
!pip install --upgrade sentencepiece

**Comment by LysandreJik** [comment]
Is it possible for you to share your notebook so that I may take a look?

**Comment by lematmat** [comment]
I've just relaunched my notebook now, I don't have any issue now.

Thank you for your help
Regards

**Comment by LysandreJik** [comment]
Glad it works for you now!
