### ISSUE TITLE
BertModel outputs string instead of tensor

### ISSUE THREAD

**Issue by miguelwon** [huggingface/transformers#8919]
## Environment info

     
- `transformers` version: 4.0.0
- Platform: Linux-4.15.0-46-generic-x86_64-with-Ubuntu-16.04-xenial
- Python version: 3.6.7
- PyTorch version (GPU?): 1.7.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help
Sorry, no idea. 

## Information

Model I am using (Bert, XLNet ...): BERT

The problem arises when using:
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] my own task or dataset: (give details below)

## To reproduce

```
import transformers
from transformers import BertModel, BertTokenizer

PRE_TRAINED_MODEL_NAME = 'bert-base-cased'
PATH_OF_CACHE = "some_path"

tokenizer = BertTokenizer.from_pretrained(PRE_TRAINED_MODEL_NAME,cache_dir = PATH_OF_CACHE)

sample_txt = 'When was I last outside? I am stuck at home for 2 weeks.'

encoding_sample = tokenizer.encode_plus(
  sample_txt,
  max_length=32,
  add_special_tokens=True, # Add '[CLS]' and '[SEP]'
  return_token_type_ids=False,
  padding=True,
  truncation = True,
  return_attention_mask=True,
  return_tensors='pt',  # Return PyTorch tensors
)

bert_model = BertModel.from_pretrained(PRE_TRAINED_MODEL_NAME,cache_dir = PATH_OF_CACHE)

last_hidden_state, pooled_output = bert_model(
  encoding_sample['input_ids'],
  encoding_sample['attention_mask']
)

print([last_hidden_state,pooled_output])
```

I'm getting this very odd behaviour where the output are two strings named from the variables:

```
(env) mwon@sebruno2:~/data-mwon/paperChega/src_classificador$ python test.py 
['last_hidden_state', 'pooler_output']
```

## Expected behavior

I expected to output a tensor with the hidden state of the last layer.

**Comment by LysandreJik** [comment]
Hi! Indeed, model outputs cannot be unpacked this way. It is mentioned in the [documentation](https://huggingface.co/transformers/main_classes/output.html#transformers.file_utils.ModelOutput). You can retrieve the items by unpacking them like this if you use the `.to_tuple()` method.

**Comment by miguelwon** [comment]
Oh, ok. Thanks and sorry for missing that.

**Comment by LysandreJik** [comment]
No problem, happy to help!
