### ISSUE TITLE
Documentation License Query

### ISSUE THREAD

**Issue by darigovresearch** [huggingface/transformers#8932]
We were looking to make some educational material based on the documentation & it wasn't clear what the license is for the documentation.

We see that the repository as a whole is under an Apache license, but the docs page is not explicit on what license the docs with a dedicated license page or in the footer.

Could you please advise?

We have made some other educational material from docs pages for reference (see the flashcards section of https://www.darigovresearch.com/)

**Comment by sgugger** [comment]
The documentation is also under the Apache License (version 2.0). Hope that helps!
Would love some flashcards for Transformers :-)

**Comment by darigovresearch** [comment]
@sgugger thanks for letting us know! An initial set based on your glossary will follow shortly as a start.

Is there any way to update the docs so that the license is in the footer?

I am happy to make a pull request if given context. We think having it there will encourage other people as well to make other educational content based on the docs.

Also could you take a look at this issue as it may be relevant but was auto closed?

https://github.com/huggingface/transformers/issues/6140

**Comment by sgugger** [comment]
I'll work on adding the copyright to individual files and the footer of the docs on Monday. For the issue you mention, I'm not sure what you mean: this points to complete text of the Apache v2 license (as is done for TensorFlow for instance, see [here](https://github.com/tensorflow/tensorflow/blob/master/LICENSE). The snippet is then copied on the code files with the year and authors filled properly (and soon-to-be doc files).

**Comment by darigovresearch** [comment]
We believe the original post meant that lines 179-188 of your license file suggests that in the License file you need to add or adjust line 190 to have the copyright year & the name of your organisation. The tensorflow license has done this as the first line of their license file.
