### ISSUE TITLE
Error running source code -- import

### ISSUE THREAD

**Issue by RandolphShi** [huggingface/transformers#8941]
Hi, I have downloaded source code of transformers and tried to run modeling_utils.py.

However, it seems that there are a lot of importing problems.

Am I running it in a wrong way?

**Comment by LysandreJik** [comment]
Hi, what are you trying to do?

The `modeling_utils.py` is an internal file that defines objects to be used by models. I invite you to read the documentation, especially the [quick tour](https://huggingface.co/transformers/quicktour.html).
