### ISSUE TITLE
vocab_file and merges_file still required params for loading serialized tokenizers

### ISSUE THREAD

**Issue by minimaxir** [huggingface/transformers#8951]
e.g.

https://github.com/huggingface/transformers/blob/dd52804f5fce0a568ffbb3dc7fd088d2de0a0e56/src/transformers/models/gpt2/tokenization_gpt2_fast.py#L122-L132

Both of these should probably be optional params now. Setting `vocab_file` and `merges_file` to `None` while specifying a `tokenizer_file` works, but seems messy.

**Comment by LysandreJik** [comment]
Indeed, we could do that, and then add a check below to ensure that we get a correct error message. Do you want to open a PR with the fix?

**Comment by minimaxir** [comment]
I wasn't planning on doing a PR because I wasn't sure of the scope of changes needed (e.g. every tokenizer `__init__` would need to be changed) and it also seems like there isn't any documentation for serialized tokenizers at all in `transformers`, so I assumed you were getting to that.
