### ISSUE TITLE
batch_sampler with trainer.py would not set the epoch 

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#8952]
Dear Huggingface team
If one uses batch_sampler instead of sampler then in trainer.py the part you set_epoch for the dataloader sampler it would not work, also in case one define custom sampler in certain application, like what I do, again in trainer.py it would not be called.
I was wondering if the codes can be more general to include these cases.

thanks.

Best
Rabeeh

**Comment by sgugger** [comment]
Hi there.
To use custom sampling (either through a sampler or a batch sampler), users are expected to subsclass `Trainer` and override the `get_train_dataloader`/`get_eval_dataloader` methods to suit their needs.

Note that those changes might then not be compatible with distributed training/TPU training.

**Comment by rabeehk** [comment]
Hi there
yes, thats correct, but looking into train() method of trainer.py class,
the user needs to overwrite the whole train() function for such cases, and
this is just for setting the epoch for other type of sampler, it would be
very nice if the train() method allowed custom sampler. thanks.
