### ISSUE TITLE
EncoderDecoderModel works poorly with Mlflow

### ISSUE THREAD

**Issue by alexyalunin** [huggingface/transformers#8967]
## Environment info

     
- `transformers` version: 4.0.0

## Description
Mlflow keeps track of model config parameters, EncoderDecoderConfig has `encoder` and `decoder` parameters which are basically configs of encoder and decoder. They are converted first `to_dict` and then to string `str()` by mlflow resulting in a long string that can not be fit. The `MAX_PARAM_VAL_LENGTH` of Mlflow is set to 250 and AFAIK can not be changed. 

This result in an error:
`MlflowException: Param value '{'return_dict': True, 'output_hidden_states': False, 'output_attentions': False, 'torchscript': False, 'use_bfloat16': False, 'pruned_heads': {}, 'tie_word_embeddings': True, 'is_encoder_decoder': False, 'is_decoder': False, 'add_cross_attention': Fa' had length 1669, which exceeded length limit of 250`

My solution for training phase is:
```
class DummyClass:
    def to_dict(self):
        return {}
    
model.config.encoder = DummyClass()
model.config.decoder = DummyClass() 
```
@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Thanks for your proposed solution @alexyalunin ! 

I don't really think that this is a problem on our side. I think MLFlow should better handle this no?

**Comment by alexyalunin** [comment]
Probably, but since you use mlflow inside your library people might expect it working with your models. I won't open the issue in mlflow repo, I leave it to someone who encounters this error again. @patrickvonplaten You can close this issue then.

**Comment by matsuobasho** [comment]
I'm having the same problem finetuning on a T5 model.  I attempted @alexyalunin 's solution of creating a DummyClass above but it didn't change the error.
