### ISSUE TITLE
[libprotobuf FATAL /sentencepiece/src/../third_party/protobuf-lite/google/protobuf/repeated_field.h:1505] CHECK failed: (index) >= (0): 

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#8984]
Hi
When I evaluate the finetune_trainer.py on translation datasets like wmt16-en-cs I always get this error after calling evaluate function, I am using version 3.5.1 of transformer on 1 GPU, this issue is really blokcing me, and happens to be there for  all translation datasets I tried, could you give me some ideas on this? thanks 

[libprotobuf FATAL /sentencepiece/src/../third_party/protobuf-lite/google/protobuf/repeated_field.h:1505] CHECK failed: (index) >= (0): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) >= (0): 
Aborted

**Comment by LysandreJik** [comment]
Hello! We really cannot help you with this little information. Please respect the issue template with your environment information, the exact command you used to launch the script, and the full stack trace.

Thank you for your understanding.

**Comment by shayne-longpre** [comment]
@rabeehk Did you manage to solve this? Experiencing the same issue fine-tuning mT5 on toy data.

**Comment by rabeehkarimimahabadi** [comment]
yes I did managed, the issue was I needed to set a longer max_length for the decoder.

**Comment by rabeehkarimimahabadi** [comment]
if you want to debug your codes, go to the place where huggingface computes the final metrics, like bleu, ... and there you can check that prediction max length and targets max-length need to match
