### ISSUE TITLE
SpanBERT support

### ISSUE THREAD

**Issue by stefan-it** [huggingface/transformers#900]
Hi,

I think the new *SpanBERT* model should also be supported in `pytorch-transformers` 😅

> We present SpanBERT, a pre-training method that is designed to better represent and predict spans of text.

Paper can be found [here](https://arxiv.org/abs/1907.10529).

Model is currently not released yet, I'll update this issue here whenever the model is available :)

**Comment by schinger** [comment]
waiting for u...

**Comment by schinger** [comment]
roBerta support

**Comment by hamediramin** [comment]
are we going to get this? :) thanks :)

**Comment by ArneBinder** [comment]
Fyi https://github.com/mandarjoshi90/coref#pretrained-coreference-models describes how to obtain the coreference models that should contain SpanBERT.

**Comment by stefan-it** [comment]
@ArneBinder Thanks for that hint!

I downloaded the *SpanBERT* (base) model. Unfortunately, the TF checkpoint conversion throws the following error message:

```bash
INFO:pytorch_transformers.modeling_bert:Loading TF weight width_scores/output_weights/Adam_1 with shape [3000, 1]
INFO:pytorch_transformers.modeling_bert:Skipping antecedent_distance_emb
Traceback (most recent call last):
  File "/usr/local/bin/pytorch_transformers", line 11, in <module>
    load_entry_point('pytorch-transformers', 'console_scripts', 'pytorch_transformers')()
  File "/mnt/pytorch-transformers/pytorch_transformers/__main__.py", line 30, in main
    convert_tf_checkpoint_to_pytorch(TF_CHECKPOINT, TF_CONFIG, PYTORCH_DUMP_OUTPUT)
  File "/mnt/pytorch-transformers/pytorch_transformers/convert_tf_checkpoint_to_pytorch.py", line 36, in convert_tf_checkpoint_to_pytorch
    load_tf_weights_in_bert(model, config, tf_checkpoint_path)
  File "/mnt/pytorch-transformers/pytorch_transformers/modeling_bert.py", line 111, in load_tf_weights_in_bert
    assert pointer.shape == array.shape
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'BertForPreTraining' object has no attribute 'shape'
```

I think some variables must be skipped, so a debugging session is unavoidable 😅

**Comment by julien-c** [comment]
Hi @stefan-it, the SpanBERT authors shared their (~`pytorch-transformers`-compatible) weights with us, so if you'd be interested we can send them your way so you can experiment/integrate them here.

Let me know!

**Comment by stefan-it** [comment]
@julien-c this would be awesome 🤗 I would really like to do some experiments (mainly NER and PoS tagging) - would be great if you can share the weights (my mail is `stefan@schweter.it`) - thank you in advance :heart:

**Comment by wenyudu** [comment]
Hi @julien-c, I would also like to receive the spanbert pytorch-compatible weights for semantic tasks like coref.  could you send it to me too? my mail is wenyudu@yahoo.com. many thanks.

**Comment by thomwolf** [comment]
You can have a look here, the official implementation has just been released: https://github.com/facebookresearch/SpanBERT

**Comment by stefan-it** [comment]
Well, two preliminary experiments (SpanBERT base) on CoNLL-2003 show a difference of ~7.8% compared to a BERT (base, cased) model 😱 So maybe this has something to do with the named entity masking 🤔 But I'll investigate that further this weekend...
