### ISSUE TITLE
"run_mlm_wwm.py", line 284 AttributeError: 'DataTrainingArguments' object has no attribute 'valid_ref_file'

### ISSUE THREAD

**Issue by NatLun137** [huggingface/transformers#9012]
Hi! There is a tiny typo in the code "transformers/examples/language-modeling/run_mlm_wwm.py" at line 284. It should be:
`if data_args.validation_ref_file is not None:` since at line 103 in `DataTrainingArguments` it defined as `validation_ref_file:`

**Comment by LysandreJik** [comment]
Hi! Do you want to submit a PR?

**Comment by NatLun137** [comment]
Sure, I'll be happy to do it.

**Comment by LysandreJik** [comment]
Hmmm I think you just tried to push on `huggingface/transformers`? You should fork the repo, apply your changes there and then open a PR here. I see you created your fork already, how did you open a PR then? Did you use the GitHub UI?
