### ISSUE TITLE
LayoutLM wrong shape for bbox in docs

### ISSUE THREAD

**Issue by dscarmo** [huggingface/transformers#9016]
## Environment info
(Colab, 09 december 2020, CPU runtime)
- `transformers` version: 4.0.1
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.7.0+cu101 (False)
- Tensorflow version (GPU?): 2.3.0 (False)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help
 documentation: @sgugger

## Information

LayoutLM documentation indicates that the shape for the bbox input is [B, seq_len]:
![image](https://user-images.githubusercontent.com/10614968/101692115-76355980-3a4e-11eb-9aa2-a0218c26fead.png)

However, from the code (https://github.com/huggingface/transformers/blob/master/src/transformers/models/layoutlm/modeling_layoutlm.py#L103) bounding boxes are encoded in the form [tl_col, tl_row, br_col, br_row]. Therefore the accepted shape is [B, seq_len, 4].

## To reproduce

Reproduced on this colab: https://colab.research.google.com/drive/1ZRPKlX8-C41nYq3o6QVS68h1JAj1nQMI?usp=sharing

## Expected behavior

Better explanation in docs

**Comment by sgugger** [comment]
Sounds right, will fix.
