### ISSUE TITLE
getattr introduces bug when setting booleans with config file 

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#9019]
Hi,

In finetune_trainer.py, line 162: https://github.com/huggingface/transformers/blob/5e637e6c690e45d13ebf7296e1ea9dcc188d0f07/examples/seq2seq/finetune_trainer.py#L162

If the user is calling this script with a json config file and setting one of the attributes to false, then on line 162, the result of if `getattr(training_args, p, None)` would be false and if condition would not be called, this results in bug for setting booleans,  could you change this line to following to resolve it: 

`if hasattr(training_args, p): `

thank you.

**Comment by patrickvonplaten** [comment]
Hey @rabeehk,

could you attach a code snippet that we can copy-paste to reproduce the error? Thanks!

**Comment by rabeehk** [comment]
Hi Patrick, 
I checked and in finetune_trainerpy you consider these parameters only which are all of type float:
` extra_model_params = ("encoder_layerdrop", "decoder_layerdrop", "dropout", "attention_dropout") 
`
In this case the issue would not happen, but if one of these parameters were boolean, lets say "A", if the user pass a config file like 

{
A: false 
}

and if the code tries to update the values in the config file as line 162, then this introduces the bug of not setting them.
For now since the variables you consider are float, this wont happen, so please feel free to close the bug. Still safer to change 162 with` if hasattr(training_args, p):`
thanks.
