### ISSUE TITLE
 Error tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

### ISSUE THREAD

**Issue by trungtruc123** [huggingface/transformers#9021]
I run pretrain PhoBERT error .
ValueError                                Traceback (most recent call last)
<ipython-input-75-d17717702336> in <module>()
      3 
      4 phobert = AutoModel.from_pretrained("vinai/phobert-base")
----> 5 tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")
      6 
      7 # INPUT TEXT MUST BE ALREADY WORD-SEGMENTED!

/usr/local/lib/python3.6/dist-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    323             if tokenizer_class is None:
    324                 raise ValueError(
--> 325                     "Tokenizer class {} does not exist or is not currently imported.".format(tokenizer_class_candidate)
    326                 )
    327             return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)

ValueError: **Tokenizer class PhobertTokenizerFast does not exist or is not currently imported.**

**Comment by patrickvonplaten** [comment]
Hey @trungtruc123, 

can you try upgrading your transformer version?
The following code snippet (as stated on the model card: https://github.com/VinAIResearch/PhoBERT) works perfectly fine for me on master:

```python
import torch
from transformers import AutoModel, AutoTokenizer

phobert = AutoModel.from_pretrained("vinai/phobert-base")

# For transformers v4.x+: 
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base", use_fast=False)
```
