### ISSUE TITLE
About the input of BERT

### ISSUE THREAD

**Issue by BeerTai** [huggingface/transformers#9022]
Hello, if I want to maintain two different dictionaries, one is BERT's original dictionary and the other is a custom dictionary, and then the input is `[CLS]  BERT dictionary corpus [SEP] custom dictionary corpus [SEP]`, how do I handle the input of the model and what part of the source code do I need to change? Thanks!

**Comment by patrickvonplaten** [comment]
Hey @BeerTai, 

It would be great if you could ask these kind of questions on the forum: https://discuss.huggingface.co/ . We try to keep github for issues and less for user-specific use cases. Thanks!
