### ISSUE TITLE
run_clm.py Issue | MODEL_FOR_CAUSAL_LM_MAPPING is None

### ISSUE THREAD

**Issue by marscod** [huggingface/transformers#9023]
When I use latest code of [run_clm.py](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_clm.py), it raises the following issue:
```
python run_clm.py \
    --model_name_or_path gpt2 \
    --train_file path_to_train_file \
    --validation_file path_to_validation_file \
    --do_train \
    --do_eval \
    --output_dir /tmp/test-clm
```

```
Traceback (most recent call last):
  File "run_clm.py", line 51, in <module>
    MODEL_CONFIG_CLASSES = list(MODEL_FOR_CAUSAL_LM_MAPPING.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```
I checked and noticed that MODEL_FOR_CAUSAL_LM_MAPPING is None. Any suggestion?

**Comment by LysandreJik** [comment]
Hi, could you please provide your environment info as asked in the template? `transformers-cli env`

**Comment by mukhtar-algezoli** [comment]
hey, any solution yet?

**Comment by mukhtar-algezoli** [comment]
@LysandreJik I am having the same issue and this is my env:
- `transformers` version: 4.1.0.dev0
- Platform: Linux-5.4.0-1029-gcp-x86_64-with-debian-buster-sid
- Python version: 3.7.6
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.3.1 (False)
- Using GPU in script?: NO (using TPU)
- Using distributed or parallel set-up in script?:

**Comment by Clickative** [comment]
I got a similar error trying to run `run_clm.py` on a TPU.
`  File "/kaggle/working/transformers/examples/language-modeling/run_clm.py", line 33, in <module>
    from transformers import (
ImportError: cannot import name 'MODEL_FOR_CAUSAL_LM_MAPPING' from 'transformers' (/opt/conda/lib/python3.7/site-packages/transformers/__init__.py)`

**Comment by mukhtar-algezoli** [comment]
@Clickative any solution?

**Comment by LysandreJik** [comment]
It seems you do not have PyTorch installed? `run_clm.py` is a PyTorch script.

**Comment by engn33r** [comment]
I encountered this same error and followed the advice from @LysandreJik. I installed PyTorch using `pip3 install torch torchvision` and this resolved the issue.

**Comment by abedkhooli** [comment]
On Kaggle TPU, the current docker seems to have old version of transformers and it reads from the conda environment, so new installs are not taken into account (try `pip show`). Even if docker is set to latest. The GPU docker seem to run a version with 0.9.3 of tokenizers and latest transformers need 0.9.4 which is another issue.
