### ISSUE TITLE
Compatibility scripts

### ISSUE THREAD

**Issue by bendboaz** [huggingface/transformers#9026]
# 🚀 Feature request

Scripts that translate code in older transformers versions into equivalent code that is compatible with newer versions. 

## Motivation

After talking with several other people in my research groups, compatibility issues and getting stuck with old versions have turned out to be pretty common problems. Seeing as many of the things preventing backward compatibility are syntactic (slightly different interfaces for tokenizers, different file paths) I thought it might be possible to add scripts to the package, which translate code to fit, say, one major version higher up (then if a user wanted to step up multiple versions, they could just run several scripts in sequence).

Some rudimentary usage example:
`python transformers-2.11-3.0.py my_project/*`

## Your contribution

I could try to implement such an example scripts, but it would probably take me months and result in a sub-optimal output due to my knowledge about python parsing and the interface changes between major and minor versions of transformers. 
I did find out a [refactoring](https://github.com/python-rope/rope) library for python, or some snippet showing how to [unparse a python AST](https://svn.python.org/projects/python/trunk/Demo/parser/unparse.py).

**Comment by LysandreJik** [comment]
Hello! Thank you for your proposal. This, however, sounds like a colossal amount of work for limited gain - we try to keep the breaking changes across versions to a minimum. I understand that these do happen from time to time, but only for very good reasons that are thoroughly discussed beforehand.

Would you be able to share what breaking changes have impacted you, and have been a bit too hard to overcome/not documented enough, preventing you from upgrading? Understanding this will help us do better in the future.
