### ISSUE TITLE
Uber AI plug and play language model (PPLM)

### ISSUE THREAD

**Issue by ajay01994** [huggingface/transformers#9027]
Hi Team,

Thanks for the hugging face repo and appreciate  your great efforts towards adding datasets and models, I was trying to find PPLM model in model page but it was shown as 404 error, could you please check the model  if it's available and let me know 

Thanks 

Ajay

**Comment by patrickvonplaten** [comment]
I don't think we host a specific pplm model in the model hub (cc @julien-c). 

Also we don't really plan on continuing to support PPLM in the future

**Comment by julien-c** [comment]
@ajay01994 are you looking for the code? https://github.com/huggingface/transformers/tree/master/examples/text-generation/pplm

Of you might be referring to https://transformer.huggingface.co/model/pplm – but indeed we don't host the inference anymore (cc @LysandreJik) as it was a bit costly to support.

**Comment by ajay01994** [comment]
Thanks for your quick reply.Actually the PPLM model is having issues due to use of transformers lib - 3.1.0 which is old and thus need certain changes to upgrade. Do you know any better or similar  model than PPLM for controlling text in GPT-2 ? that would be of great help 

Regards 

Ajay

**Comment by julien-c** [comment]
not at the top of my head, but maybe @mimosavvy or @w4nderlust knows!

**Comment by ajay01994** [comment]
ok....closing this for now ,thanks for your help :)

**Comment by w4nderlust** [comment]
> Thanks for your quick reply.Actually the PPLM model is having issues due to use of transformers lib - 3.1.0 which is old and thus need certain changes to upgrade. Do you know any better or similar model than PPLM for controlling text in GPT-2 ? that would be of great help
> 
> Regards
> 
> Ajay

Can you be more specific about the issues? There has been a PR that should have solved the change to dictionary as returns to the model.
