### ISSUE TITLE
Improve coverage of the documentation

### ISSUE THREAD

**Issue by sgugger** [huggingface/transformers#9035]
Currently, some public classes are not documented anywhere because we didn't create the corresponding doc pages. Those missing pages are:

- Benchmark classes
- Bert Japanese
- Data collators

If someone feels like working on one of those, please tag yourself with a comment on this issue. Once the objects are properly documented, they can be removed from the `SHOULD_BE_DOCUMENTED` constant in [this file](https://github.com/huggingface/transformers/blob/1310e1a758edc8e89ec363db76863c771fbeb1de/utils/check_repo.py#L374).

**Comment by Qbiwan** [comment]
I added docs for Bertweet [here](https://github.com/huggingface/transformers/pull/9379), first contribution, let me know if there is anything missing

**Comment by sgugger** [comment]
Reopening the issue are not all of the items are fixed yet!

**Comment by forest1988** [comment]
Hello @sgugger,

If no one else is working on it yet, I'd like to work on the `Bert Japanese` document.
(I also am interested in working on `Data collators`, but I’d like to do that one by one. If there is someone else who would like to work on, please give priority to that person.)

**Comment by sgugger** [comment]
Go ahead @forest1988 :-)

**Comment by forest1988** [comment]
Thanks, I'll do my best!

**Comment by forest1988** [comment]
I deeply apologize for my delay in opening a PR for Bert Japanese.
I've just opened the PR.

https://github.com/huggingface/transformers/pull/11219

If you find any flaws, please let me know. I'll correct it soon.
