### ISSUE TITLE
[docs] missing info on call back registry

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#9036]
https://huggingface.co/transformers/main_classes/callback.html is missing instructions/examples on how to register a callback. Thanks.

@sgugger

**Comment by stas00** [comment]
I guess the corresponding test demonstrates the usage: https://github.com/huggingface/transformers/blob/master/tests/test_trainer_callback.py

**Comment by sgugger** [comment]
I don't think this issue needs to be closed, one more example could be added to the documentatio! Let's make a good first issue out of it, maybe a contributor could help there :-)

**Comment by amalad** [comment]
Hi @sgugger. I'm new and I'd like to start contributing. Can I work on this issue?

**Comment by sgugger** [comment]
Sure!

**Comment by amalad** [comment]
Thanks. Would an example like this be okay? - 
```
class MyCallback(TrainerCallback):
    "A callback that prints a message at the beginning of training"
    
    def on_train_begin(self, args, state, control, **kwargs):
        print("Starting training")

trainer = Trainer(
    model,
    args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    callbacks=[MyCallback]
)
```
Also, should I add the example to https://huggingface.co/transformers/main_classes/callback.html, or would the [training tutorial](https://huggingface.co/transformers/training.html) be a better place?

**Comment by sgugger** [comment]
I think is should also show how to use `add_callback` as an alternative too, otherwise, that's the gist of it. The callbacks page is perfect for this I think.

**Comment by amalad** [comment]
Thanks, I've added an example for `add_callback` too and opened a PR [here](https://github.com/huggingface/transformers/pull/10928). It's failing some tests right now but I'm not sure why since I've only modified the `callback.rst` file. Could you please help me figure out why this might be happening?

**Comment by stas00** [comment]
The CI is flakey at times, I restarted the failing jobs. It looks like network problems, may have to restart again later if it still fails.

**Comment by amalad** [comment]
Cool, thanks!
