### ISSUE TITLE
The example code does not work

### ISSUE THREAD

**Issue by fang19911030** [huggingface/transformers#9043]
## Environment info

     
- `transformers` version: 3.3.1
- Platform: Linux-4.4.0-154-generic-x86_64-with-Ubuntu-16.04-xenial
- Python version: 3.6.12
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

 @LysandreJik  @sgugger
## Information

When I run the code about Question Answering from the documentation https://huggingface.co/transformers/task_summary.html, there is an error reported.

## To reproduce

```
from transformers import AutoTokenizer, AutoModelForQuestionAnswering
import torch
tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased-whole-word-masking-finetuned-squad")
model = AutoModelForQuestionAnswering.from_pretrained("bert-large-uncased-whole-word-masking-finetuned-squad")
text = r"""
🤗 Transformers (formerly known as pytorch-transformers and pytorch-pretrained-bert) provides general-purpose
architectures (BERT, GPT-2, RoBERTa, XLM, DistilBert, XLNet…) for Natural Language Understanding (NLU) and Natural
Language Generation (NLG) with over 32+ pretrained models in 100+ languages and deep interoperability between
TensorFlow 2.0 and PyTorch.
"""
if __name__ == "__main__":
    questions = [
        "How many pretrained models are available in 🤗 Transformers?",
        "What does 🤗 Transformers provide?",
        "🤗 Transformers provides interoperability between which frameworks?",
    ]
    for question in questions:
        inputs = tokenizer(question, text, add_special_tokens=True, return_tensors="pt")
        input_ids = inputs["input_ids"].tolist()[0]
        text_tokens = tokenizer.convert_ids_to_tokens(input_ids)
        outputs = model(**inputs)
        answer_start_scores = outputs.start_logits
        answer_end_scores = outputs.end_logits
        answer_start = torch.argmax(
            answer_start_scores
        )  # Get the most likely beginning of answer with the argmax of the score
        answer_end = torch.argmax(answer_end_scores) + 1  # Get the most likely end of answer with the argmax of the score
        answer = tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(input_ids[answer_start:answer_end]))
        print(f"Question: {question}")
        print(f"Answer: {answer}")
```
## Error message
  File "/home/pxf109/LegalContractModel/example.py", line 22, in <module>
    answer_start_scores = outputs.start_logits
AttributeError: 'tuple' object has no attribute 'start_logits

**Comment by sgugger** [comment]
The example code in the documentation of version 4 works with transformers version 4. You can find the examples for older versions (since you seem to be running v3.3.1) by clicking on the navigation bar at the left of the documentation pages. [Here](https://huggingface.co/transformers/v3.3.1/) is a direct link to v3.3.1.
