### ISSUE TITLE
Token classification example (run_ner.py) should work without fast tokenizers

### ISSUE THREAD

**Issue by ruanchaves** [huggingface/transformers#9056]
# 🚀 Feature request

The token classification example ( [run_ner.py](https://github.com/huggingface/transformers/blob/master/examples/token-classification/run_ner.py) ) calls the Tokenizer with `return_offsets_mapping=True` (line 279).

This is not allowed for Python tokenizers and raises the error `NotImplementedError: return_offset_mapping is not available when using Python tokenizers. To use this feature, change your tokenizer to one deriving from transformers.PreTrainedTokenizerFast.`

run_ner.py should align tokens and labels even if a fast tokenizer is not available.

## Motivation

There isn't a fast tokenizer available for `vinai/bertweet-base`, and I guess this may apply to a few other models as well.  
Passing  `vinai/bertweet-base` as `model_name_or_path` to `run_ner.py` instantly raises `NotImplementedError`.

**Comment by sgugger** [comment]
Yes, this script only supports models that have a fast tokenizer (there is no a clear assert of that after the tokenizer is loaded). The old script will work with models that only have a slow tokenizer.

**Comment by ruanchaves** [comment]
> Yes, this script only supports models that have a fast tokenizer (there is no a clear assert of that after the tokenizer is loaded). The old script will work with models that only have a slow tokenizer.

Somebody wrote an assert four days ago. There are certain inconveniences to the old script, e.g. It doesn't utilize the `datasets` library.

**Comment by TekeshwarHirwani** [comment]
I am facing same problem in BioGPT

**Comment by capitanA** [comment]
I also have the same problem, has anyone found any solution for that?

**Comment by aazqueta** [comment]
No solution found yet, I also have this error in BioGPT

**Comment by ArthurZucker** [comment]
Can you try `pip install tokenizers`?
