### ISSUE TITLE
Add Definition of a transformer to the glossary

### ISSUE THREAD

**Issue by darigovresearch** [huggingface/transformers#9078]
Thought it may be helpful to have an easy to understand definition for what a transformer is in the [glossary](https://huggingface.co/transformers/glossary.html) for any new joiners.

@sgugger any thoughts?

Happy to add a definition if provided with one in the open pull request #8949

**Comment by cronoik** [comment]
Are you looking for https://huggingface.co/transformers/model_summary.html ?

**Comment by darigovresearch** [comment]
@cronoik thanks for taking a look! Wasn't looking for that page, was trying to find just a general definition of what a transformer is in terms of the general concept

**Comment by cronoik** [comment]
Do you have something like this in mind: https://github.com/huggingface/transformers/blob/master/notebooks/02-transformers.ipynb ?

**Comment by darigovresearch** [comment]
No, wasn't looking for a notebook, just a one line description/explanation of what a transformer is

How would you describe it to someone who doesn't know about transformers?

**Comment by cronoik** [comment]
Maybe self-attention based deep learning model architecture.

**Comment by darigovresearch** [comment]
@cronoik That's a good start, `self-attention` & `deep learning` aren't yet defined in the glossary

How would you define those?

**Comment by cronoik** [comment]
`self-attention`: each element of the input finds out which other elements of the input they should attend to.
`deep learning`: machine learning algorithms which uses NN which several layers.

@darigovresearch

**Comment by darigovresearch** [comment]
@cronoik thanks for that! Would you like to put in a pull request so that your definitions go into the transformers glossary and the set of flashcards that we built or would you like us to do it?

I'm sure those definitions would be welcome and easily merged by the maintainers

https://www.darigovresearch.com/huggingface-transformers-glossary-flashcards

**Comment by darigovresearch** [comment]
Thanks @sgugger for merging the pull request, @cronoik your definitions are now on the glossary page and I have also added them to the flashcards so this issue can now be closed. Thank you both for your help!

Glossary https://huggingface.co/transformers/glossary.html

Flashcards https://www.darigovresearch.com/huggingface-transformers-glossary-flashcards

**Comment by cronoik** [comment]
Thanks for your commits ;).
