### ISSUE TITLE
Getting a 404 error when loading TFXLMRobertaModel from 'xlm-roberta-large'

### ISSUE THREAD

**Issue by vinaygeorgeroy** [huggingface/transformers#9086]
Getting a 404 when trying to load the model. 
Manyually  checked the https://huggingface.co repository for the xlm-roberta-large, was only able to find the Pytorch models, why aren't the TF models available for this, if its not, why is it not explicitly mentioned in the documentation?

**Comment by LysandreJik** [comment]
Could you try with the flag `from_pt=True` when using `from_pretrained`?

**Comment by vinaygeorgeroy** [comment]
That worked, thanks
