### ISSUE TITLE
Not able to load T5 tokenizer

### ISSUE THREAD

**Issue by adithyaan-creator** [huggingface/transformers#9093]
Transformers==4.0.0
torch == 1.7.0+cu101
tensorflow == 2.3.0
Platform = Colab notebook

@julien-c  @patrickvonplaten

Not able to load T5 tokenizer using
 `tokenizer = T5Tokenizer.from_pretrained('t5-base')'

Getting error - 
![image](https://user-images.githubusercontent.com/54103522/102049719-6c717480-3e07-11eb-8671-9c10c3169b17.png)

I am able to download the pre-trained model though.

**Comment by patrickvonplaten** [comment]
Hey @adithyaan-creator, 

as the error message says you need to install the sentence piece library :-) 

If you run:

```
pip install sentencepiece==0.1.91
```

**Comment by adithyaan-creator** [comment]
Thanks @patrickvonplaten .

**Comment by DesiKeki** [comment]
Hi @patrickvonplaten 
I installed sentencepiece, but it still doesnt seem to be working for me. Please see the snapshot below. Please help.

![image](https://user-images.githubusercontent.com/48218899/103457616-d1452e00-4d26-11eb-9cc3-7bb81b807750.png)

**Comment by adithyaan-creator** [comment]
@DesiKeki try sentencepiece version 0.1.94.

**Comment by DesiKeki** [comment]
Getting same error with version 0.1.94 also @adithyaan-creator

**Comment by VedantKP** [comment]
Hello @patrickvonplaten 
I have gone through the issue and the suggestions given above. However, I am facing the same issue and for some reason, none of the above solutions are proving fruitful.

The issue I am facing is exactly the same as the one stated above:
`from transformers import T5Tokenizer,T5ForConditionalGeneration,Adafactor`
`!pip install sentencepiece==0.1.91`
`tokenizer = T5Tokenizer.from_pretrained("t5-base")`
`print(tokenizer)`

The output of the above code is: None. 
I tried using other versions of sentencepiece as well. But it is still not working.
![ImportingT5BaseFails](https://user-images.githubusercontent.com/48618975/111974487-74873180-8b25-11eb-8b75-63cd31750711.PNG)

**Comment by LysandreJik** [comment]
Did you restart your kernel after installing `sentencepiece`? See conversation in https://github.com/huggingface/transformers/issues/10797

**Comment by pedramyamini** [comment]
> Did you restart your kernel after installing `sentencepiece`? See conversation in #10797

it works for me, thank you
