### ISSUE TITLE
Cannot load custom tokenizer for Trainer

### ISSUE THREAD

**Issue by Ierezell** [huggingface/transformers#9104]
## Environment info
- `transformers` version: 4.0.0
- Platform: Linux-5.9.13-zen1-1-zen-x86_64-with-glibc2.2.5
- Python version: 3.8.6
- PyTorch version (GPU?): 1.7.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@mfuntowicz

## Information

Model I am using: My own

The problem arises when using:
* [X] the official example scripts: (give details below)

The tasks I am working on is:
* [X] my own task or dataset: (give details below)

I want to finetune a model on my own dataset. For now it doesn't matter if i finetune bert, DistilBert or other, I just want good embeddings for text similarity (cosine distance)
## To reproduce

1. Read the [How to train tutorial](https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/01_how_to_train.ipynb)
2. Train your own tokenizer (working perfectly) and got `model-vocab.json` and `model-merges.txt`
3. Load and encode with :
```
tokenizer = ByteLevelBPETokenizer(./models/custom/my_model-vocab.json","./models/custom/my_model-merges.txt")
``` 
This works nicelly !
4. Try to do the same with a DistilBertTokenizerFast to use with the `Trainer` class
```
tokenizer = DistilBertTokenizerFast.from_pretrained('./models/custom', max_len=512)
```

5. Get the error `check that './models/custom' is the correct path to a directory containing relevant tokenizer files`

Note : I also tried to add a `config.json` file next to the merge and vocab which seemed missing but it doesn't change anything. 
I also tried a RobertaTokenizerFast (and the 'not fast' version) but same problem

## Expected behavior
Train a custom tokenizer and be able to load it with a ModelTokenizer for the Trainer. 
(The BPE tokenizer which works do not have the  `mask_token` attribute to work with the dataset loader)

**Comment by Ierezell** [comment]
After playing with it more and changing files, names etc... I managed to made it work with Roberta. I guess it was a stupid name error... Sorry for taking 5mn of you time reading this. 
 
I realize it couldn't work with distilbert (bert) as the tokenizers are differents. 
In the end, the model is training. 

Maybe it will help someone else one day. 
Have a good day.

**Comment by LysandreJik** [comment]
Glad you could resolve your issue!
