### ISSUE TITLE
Cannot load community model on local machine

### ISSUE THREAD

**Issue by logancyang** [huggingface/transformers#9106]
## Environment info

- `transformers` version: 3.4.0
- Platform: Darwin-19.6.0-x86_64-i386-64bit
- Python version: 3.7.6
- PyTorch version (GPU?): 1.7.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
Probably @LysandreJik 

## Information

Model I am using: https://huggingface.co/huggingtweets/xinqisu

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

Steps to reproduce the behavior: (this is the instruction on the model page)

```
from transformers import pipeline
generator = pipeline('text-generation', model='huggingtweets/xinqisu')
generator("My dream is", num_return_sequences=5)
```

It gives me

```
OSError: Can't load config for 'huggingtweets/xinqisu'. Make sure that:

- 'huggingtweets/xinqisu' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'huggingtweets/xinqisu' is the correct path to a directory containing a config.json file
```

## Expected behavior

The generator should work with the snippet above. I have trained other `huggingtweets` models and they still work with the same code, for example, the following still works, it downloaded the model successfully.

```
from transformers import pipeline
generator = pipeline('text-generation', model='huggingtweets/billgates')
generator("My dream is", num_return_sequences=5)
```

**Comment by LysandreJik** [comment]
Hello! I believe this is so because this model uses the new weights system, which was introduced in v3.5.1. Please upgrade your transformers version to at least v3.5.1, we recommand the latest (v4.0.1):

```
pip install -U transformers==4.0.1
```
