### ISSUE TITLE
Which dataset is used for training GPT, GPT2 from scratch?

### ISSUE THREAD

**Issue by arisohn** [huggingface/transformers#9119]
Hi,

I checked the model card of GPT and GPT2, but I can't find the dataset which was used for training.
Where can I find the datasets which is used for?

https://huggingface.co/openai-gpt
https://huggingface.co/gpt2

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
