### ISSUE TITLE
RobertaTokenizer fails to do_lower_case, different behavior between version 2 and 3

### ISSUE THREAD

**Issue by jingtaozhan** [huggingface/transformers#9122]
## Environment info
     
- `transformers` version: 3.4.0 / 2.8.0
- Platform: linux
- Python version: 3.8

### Who can help
@mfuntowicz 

## Information

Tokenizer I am using: RobertaTokenizer
The tokenizer do not lower case the text even if I explicitly set do_lower_case=True. The behavior is different between version 2.8.0 and 3.4.0

## To reproduce

```python
from transformers import RobertaTokenizer
tokenizer = RobertaTokenizer.from_pretrained("roberta-base", do_lower_case=True)
print(tokenizer.tokenize("Huggingface"))
```

## Expected behavior

Version 3.4.0 prints: ['Hug', 'ging', 'face']
Version 2.8.0 prints: ['h', 'ug', 'ging', 'face']

**Comment by julien-c** [comment]
Could you please also try with the most recent transformers release and report what happens?

**Comment by jingtaozhan** [comment]
Version 4.0.1 prints: ['Hug', 'ging', 'face']

**Comment by jingtaozhan** [comment]
Explicitly setting the attribute 'do_lower_case' to True solves the problem.

```python
from transformers import RobertaTokenizer
tokenizer = RobertaTokenizer.from_pretrained("roberta-base", do_lower_case=True)
tokenizer.do_lower_case = True
print(tokenizer.tokenize("Huggingface"))
```

**Comment by pratyushmaini** [comment]
If we use the AutoTokenizer library, this still does not work. 

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("roberta-base", do_lower_case=True)
tokenizer.do_lower_case = True
print(tokenizer.tokenize("Huggingface"))
```
