### ISSUE TITLE
seq2seq finetuning scripts break before training (cannot import name ParallelMode)

### ISSUE THREAD

**Issue by apostolis19** [huggingface/transformers#9126]
File "finetune_trainer.py", line 24, in <module>
    from seq2seq_trainer import Seq2SeqTrainer
  File "/home/---/transformers/examples/seq2seq/seq2seq_trainer.py", line 35, in <module>
    from transformers.training_args import ParallelMode
ImportError: cannot import name 'ParallelMode' from 'transformers.training_args'

**Comment by KDercksen** [comment]
Make sure you install a recent version of transformers, `ParallelMode` was added to the master branch some ~2 weeks ago.

**Comment by sgugger** [comment]
Yes, as @KDercksen points out, you need an up-to-date install from source to be able to run the examples (as mentioned in the main examples folder README).
