### ISSUE TITLE
adapting trainer.py for multiple optimizers 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#9138]
Hi
I was wondering if there can be an easy way to adapt trainer.py for multiple optimizers, where each optimizer is responsible for updating a part of model. thanks

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
