### ISSUE TITLE
Using new pretrained model with it's own vocab.txt file. 

### ISSUE THREAD

**Issue by Santosh-Gupta** [huggingface/transformers#914]
I am trying to use SciBert pretrained weights, which has its own vocab , so it's own 'vocab.txt', file. 

I think it's fairly straight forward to point the `pytorch_model.bin` but I do not see any options to introduce a new vocab.txt file.

**Comment by Santosh-Gupta** [comment]
Found the answer

https://github.com/huggingface/pytorch-transformers/issues/69#issuecomment-443215315

you can just do a direct path to it

**Comment by jessica-lll** [comment]
Can it work? I tried the solution but didn't work. I put the vocab.txt file under a certain path.

**Comment by Santosh-Gupta** [comment]
What error message did you get? Maybe try an absolute path to the file.

**Comment by lxgend** [comment]
i

> What error message did you get? Maybe try an absolute path to the file.

It only works when you store the vocab.txt in `/tmp` which is the default `cache_dir`
