### ISSUE TITLE
T5 checkpoint contains weights missing on current model.

### ISSUE THREAD

**Issue by dscarmo** [huggingface/transformers#9157]
## Environment info
Colab (16 december 2020), transformers 4.0.1

### Who can help
 T5: @patrickvonplaten

## Information
When loading the pre-trained T5 weights, directy with .from_pretrained, with the newest version, it returns the following warning:

>  Some weights of the model checkpoint at t5-small were not used when initializing T5ForConditionalGeneration: ['decoder.block.0.layer.1.EncDecAttention.relative_attention_bias.weight']
> - This IS expected if you are initializing T5ForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing T5ForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

This also caused old checkpoints of mine to not load due to the missing weight. 

## To reproduce
Reproduced in Colab:
https://colab.research.google.com/drive/158OiSKHz80b0PQYaWB6c-AI9xKCzE1ns?usp=sharing

## Expected behavior

Loading T5 should not return warnings if i am loading the pre-trained weights from the library.

**Comment by patrickvonplaten** [comment]
Yes we should fix the warning. It's no problem that those weights are missing i.e.:
#8933

**Comment by dscarmo** [comment]
Thank you!
