### ISSUE TITLE
Avoid i/o in class __init__ methods

### ISSUE THREAD

**Issue by honnibal** [huggingface/transformers#916]
Working with model serialization and configs is pretty painful, and we went through a lot of design iterations on this for spaCy.

I think one thing that's definitely unideal in `pytorch_transformers` is that the tokenizers often expect file names in the `__init__` methods. This means that if you're holding the data in memory, you have to first write it to file in order to create the class.

I think it would be nicer to move the load-from-disk part into a method, that could be called after the `__init__`. This wouldn't really change the usage of the classes, since mostly people are using the `.from_pretrained()` class method, but it would make the classes a bit more flexible.

**Comment by thomwolf** [comment]
Make sense to me. I'll include that in a coming PR.
