### ISSUE TITLE
Language modeling logging

### ISSUE THREAD

**Issue by Ganeshgit96** [huggingface/transformers#9166]
## Environment info

     
- `transformers` version:4.0.0-rc-1
- Platform:Linux
- Python version:Python 3.7.9
- PyTorch version (GPU?):1.4.0
- Tensorflow version (GPU?):1.14.0
- Using GPU in script?:Yes
- Using distributed or parallel set-up in script?:Yes

### Who can help

@sgugger
## Information

Model I am using (Bert, XLNet ...): BERT

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ X] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

## Expected behavior

I am new to the logging package and I would like to know if we can redirect all the contents occurring in the screen to a text file when I am running the language modeling script. I am not sure if this is the correct forum to ask but can you please help me with this?

**Comment by sgugger** [comment]
I think @LysandreJik will know more what to do for the logging. Also, we usually ask questions like this on the [forum](https://discuss.huggingface.co/) and keep issues for bugs/feature requests.

**Comment by LysandreJik** [comment]
If you want to output everything to a file, you can redirect the standard output/standard error to a file. We use the official `logging` package for logs, and they have a full chapter en redirecting to a file: https://docs.python.org/3/howto/logging.html#logging-to-a-file

**Comment by Querela** [comment]
It is also possible to redirect the output from the script (without modifying anything). I use the following code to both have the output on my screen (console) and a copy in my log files (with stderr having the python logging logs):

```bash
python run_your_script.py \
    > >(tee -a stdout.log) \
    2> >(tee -a stderr.log >&2)
```

(Found this gem on StackOverflow somewhere.)

**Comment by Ganeshgit96** [comment]
@Querela and @LysandreJik, thanks a lot for the help. closing the issues.
