### ISSUE TITLE
DataTrainingArguments: __init__() got an unexpected keyword argument 'evaluate_during_training'

### ISSUE THREAD

**Issue by githubrandomuser2017** [huggingface/transformers#9206]
## Environment info

     
- `transformers` version: 4.0
- Platform: Google Colab
- Python version: 3.6.9
- PyTorch version (GPU?): 1.7
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help

@sgugger
## Information

Model I am using (Bert, XLNet ...): Distilbert

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/trainer/01_text_classification.ipynb

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Run the HF example Notebook here: https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/trainer/01_text_classification.ipynb

That Notebook is linked from here: https://huggingface.co/transformers/examples.html

2. At this line:
```python
training_args = TrainingArguments(
    output_dir="./models/model_name",
    overwrite_output_dir=True,
    do_train=True,
    do_eval=True,
    per_gpu_train_batch_size=32,
    per_gpu_eval_batch_size=128,
    num_train_epochs=1,
    logging_steps=500,
    logging_first_step=True,
    save_steps=1000,
    evaluate_during_training=True,
)
```

an error is raised:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-6-e83ba093226a> in <module>()
     14     logging_first_step=True,
     15     save_steps=1000,
---> 16     evaluate_during_training=True,
     17 )

TypeError: __init__() got an unexpected keyword argument 'evaluate_during_training'
```

## Expected behavior

The HF example Notebook should complete successfully.

**Comment by sgugger** [comment]
Indeed, will fix that notebook on Monday. Thanks for reporting!

**Comment by sgugger** [comment]
Note that this notebook is quite old, so you might prefer the most recent one [here](https://github.com/huggingface/notebooks/blob/master/examples/text_classification.ipynb). I fixed the issue by pinning the transformers version inside it, we will keep it for legacy reasons but not update it.

**Comment by iambackend** [comment]
Same problem on this notebook: [https://colab.research.google.com/drive/1-JIJlao4dI-Ilww_NnTc0rxtp-ymgDgM?usp=sharing](https://colab.research.google.com/drive/1-JIJlao4dI-Ilww_NnTc0rxtp-ymgDgM?usp=sharing).
This notebook is referenced here: [https://huggingface.co/transformers/training.html#additional-resources]().
Also, if I understand correctly, `evaluate_during_training=True` should be replaced with `evaluation_strategy='epoch'`, and then it will work fine.

**Comment by sgugger** [comment]
I think this notebook is community-contributed (it's not in our repos) so it's up to the person who wrote it to port it to the most recent version of transformers.
