### ISSUE TITLE
checkpoint callbacks 

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#9216]
Hi
I need to save more things during checkpoint and I am using finetune_trainer.py not the pytorch lightening one, could you provide me with example on how I can modify the save part of the checkpoints? thanks

**Comment by rabeehkarimimahabadi** [comment]
In particular I need to define a callback with on_save function, for this I need to be able to acces "is_world_process_zero" and I am not sure how to do it. thanks

**Comment by rabeehk** [comment]
solved with understanding is_world_process_zero is accessible via  state.is_world_process_zero
