### ISSUE TITLE
Does provide any scripts about how to convert mpnet pretrain model to transformers pretrain one?

### ISSUE THREAD

**Issue by RyanHuangNLP** [huggingface/transformers#9222]
# 🚀 Feature request

## Motivation

I want to convert my pretrain chinese mpnet with the fairseq format to transformers format

**Comment by patrickvonplaten** [comment]
Maybe the author of MPNet can help here, @StillKeepTry

**Comment by RyanHuangNLP** [comment]
@patrickvonplaten problem is fix
