### ISSUE TITLE
Differences between original implementation and HuggingFace implementation

### ISSUE THREAD

**Issue by OmkarSabnis1998** [huggingface/transformers#9228]
## Environment info

     
- `transformers` version: **4.0.0**
- Platform: **Windows**
- Python version: **3.6.5**
- PyTorch version (GPU?): **1.6.0+cu101**
- Tensorflow version (GPU?): **-** 
- Using GPU in script?: **Yes**
- Using distributed or parallel set-up in script?: **No**

### Who can help
**@stefan-it**

## Information

The model I am using (Bert, XLNet ...): LayoutLMforTokenClassification

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)
**My own modified script**

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)
**My own dataset**

## To reproduce

1.
2.
3.

## Expected behavior

This is more of a question rather than an issue.
When I trained the layoutlm model using my data and I used the tokenclassification model from huggingface, I got a small drop in performance. I wanted to ask if there are any differences between the two models? I have kept the hyper-parameters to be exactly the same in both cases.
Two key points where I found the differences were:
(1). When taking in the dataset - in the Microsoft version, there is a concept called "segment_ids" which is not a parameter in the huggingface layoutlm documentation.
(2). I loaded both the models and printed the number of layers in both, I saw that there is 1 extra layer called layoutlm.embeddings.position_ids in the huggingface implementation.

I am trying to find out the reason for the drop in performance. Hence, wanted to find out if there is any difference between the model implementations itself. It would be great help if you could help explain the two differences I found!

Thanks!

**Comment by hasansalimkanmaz** [comment]
Hey @OmkarSabnis1998 I also tried to train with huggingface implementation. My model isn't learning anything during training. Did you experience a similar issue with your training?

**Comment by NielsRogge** [comment]
Hi there,

I made some [integration tests](https://github.com/NielsRogge/transformers/blob/e5431da34ab2d03d6114303f18fd70192c880913/tests/test_modeling_layoutlm.py#L318) for both the base model (`LayoutLM`) as well as the model with a token classification head on top (`LayoutLMForTokenClassification`). These integration tests do not reveal any differences in terms of output on the same input data between the original implementation and the one in HuggingFace Transformers. So the implementation seems to be OK.
