### ISSUE TITLE
Load from a TF 1.0 checkpoint in modeling_tf_utils.py

### ISSUE THREAD

**Issue by vsuarezpaniagua** [huggingface/transformers#9242]
In the file modeling_utils.py, we can load a TF 1.0 checkpoint as is indicated in this [line](https://github.com/huggingface/transformers/blob/fb650df8590f796663226132482d09da5b0fb613/src/transformers/modeling_utils.py#L930). However, in the file modeling_tf_utils.py, which is the same version for TF, we can not load models from TF 1.0, and it says expecifically that you can as:
`            >>> model = BertModel.from_pretrained('./tf_model/my_tf_checkpoint.ckpt.index', from_tf=True, config=config)`
But there is no _if_ for
`os.path.isfile(os.path.join(pretrained_model_name_or_path, TF_WEIGHTS_NAME + ".index"))`

**Comment by patrickvonplaten** [comment]
Hey @vsuarezpaniagua,

Great point! I noticed the same thing actually a couple of days ago as well with @jplu. I think we should add this functionality to `modeling_tf_utils.py`. It should be very similar to how it's done in the corresponding code in `modeling_utils.py`, and require a new `load_tf1_weights` for TF2 models. 

Pinging @jplu here as well for some brainstorming on how to best design this feature request

**Comment by vsuarezpaniagua** [comment]
Thank you for taking it into consideration. Also, I saw that the _**EvaluationStrategy**_ for _epoch_ is not working using it in _training_args_tf.py_ for building a [TFTrainer](https://github.com/huggingface/transformers/blob/ec07da65e25562040581febaf9b400a462962961/src/transformers/trainer_tf.py#L49) in _trainer_tf.py_. And I think this is because there are not _self.control.should_evaluate_ or _self.control.should_save_ as there are in the Torch implementations _trainer.py_ and _training_args.py_. Having similar code for both implementations could solve all these problems and easier to follow.

> Hey @vsuarezpaniagua,
> 
> Great point! I noticed the same thing actually a couple of days ago as well with @jplu. I think we should add this functionality to `modeling_tf_utils.py`. It should be very similar to how it's done in the corresponding code in `modeling_utils.py`, and would require a new `load_tf1_weights` for TF2 models.
> 
> Pinging @jplu, @LysandreJik, @sgugger here as well for some brainstorming on the importance of this feature request and how to best design it if neeed.

**Comment by jplu** [comment]
The TF Trainer is off of maintenance since a while in order to be rethought when we can dedicate a bit of time to it. Not the current TF priority unfortunately. But at some point it is our plan to make the TF Trainer catching up his late on the PT one.
