### ISSUE TITLE
numpy ndarray type is not allowed on process pytorch model

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [huggingface/transformers#9248]
## Environment info

     
- `transformers` version: 4.1.1
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.8.6
- PyTorch version (GPU?): 1.7.1 (False)
- Tensorflow version (GPU?): 2.3.1 (False)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help
 tensorflow: @jplu

## Information

Model I am using (Bert, XLNet ...): Bert

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [o] my own modified scripts: (give details below)

Changed 1 line that `from_pt`'s default value from `False` to `True`((https://github.com/huggingface/transformers/blob/ec07da65e25562040581febaf9b400a462962961/src/transformers/modeling_tf_utils.py#L947))

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [o] my own task or dataset: (give details below)

HuggingFace: monologg/kobert

I loaded my pertained pytorch model, and an error occurred on input_processing function

## To reproduce

1. run input_processing
2. numpy ndarray is not allowed type(https://github.com/huggingface/transformers/blob/ec07da65e25562040581febaf9b400a462962961/src/transformers/modeling_tf_utils.py#L331)
3. So ndarray cannot be processed(https://github.com/huggingface/transformers/blob/ec07da65e25562040581febaf9b400a462962961/src/transformers/modeling_tf_utils.py#L354)
4. Of course there is not any proper changing for ndarray not as other types(dict, Tensor and etc)
5. Error occurred like below

```
  File "/Users/ys/dev/rasa/venv/lib/python3.8/site-packages/transformers/modeling_tf_utils.py", line 357, in input_processing
    raise ValueError(f"Data of type {type(v)} is not allowed only {allowed_types} is accepted for {k}.")
ValueError: Data of type <class 'numpy.ndarray'> is not allowed only (<class 'tensorflow.python.framework.ops.Tensor'>, <class 'bool'>, <class 'int'>, <class 'transformers.file_utils.ModelOutput'>, <class 'tuple'>, <class 'list'>, <class 'dict'>) is accepted for attention_mask.
```

## Expected behavior

Train success!

**Comment by jplu** [comment]
Hello!

Thanks for reporting this, we will apply a fix for the next release!

**Comment by patrickvonplaten** [comment]
@LoveMeWithoutAll thanks for issue!

Could you specific your use case here a bit? Do you want to convert a PyTorch model to a tensorflow model and consequently train the tensorflow model?

**Comment by LoveMeWithoutAll** [comment]
@patrickvonplaten Hello
I'm using [Rasa](https://rasa.com) framework that embedding HuggingFace. Rasa is not yet support Pytorch model, so I must convert from Pytorch to TF model for using pre-trained model. Then `ndarray` is needed for convert model.

**Comment by pranavpawar3** [comment]
@LoveMeWithoutAll Hi, I am also using the Rasa framework with HFTransformers and Language Models in pipeline config. Faced the same issue with the latest transformers, but it works with lower versions, transformers-2.9.0. I haven't tested out on other versions (probably some 3.x might work too!), but 2.9.0 shall work fine if your project setup allows lower version transformers.

**Comment by LoveMeWithoutAll** [comment]
> @LoveMeWithoutAll Hi, I am also using the Rasa framework with HFTransformers and Language Models in pipeline config. Faced the same issue with the latest transformers, but it works with lower versions, transformers-2.9.0. I haven't tested out on other versions (probably some 3.x might work too!), but 2.9.0 shall work fine if your project setup allows lower version transformers.

thank you for your advice! i'll try it as you did

**Comment by LysandreJik** [comment]
This was fixed on `master`: https://github.com/huggingface/transformers/pull/9294

We'll release a new version tomorrow, which will benefit from this change. Thanks for reporting it!

**Comment by LoveMeWithoutAll** [comment]
Thank you for your effort!
