### ISSUE TITLE
[hf args] shouldn't match partial arg names

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#9267]
For `--label_smoothing_factor` I can pass `--label_smoothing` and it still works - which is a bug, as it should do a full match and not a substring. This is with master.

context: finetune_trainer just switched from `--label_smoothing` to `--label_smoothing_factor` (different functionality) and we were puzzling over why  `--label_smoothing`  still worked.

this is definitely not urgent

@sgugger

**Comment by sgugger** [comment]
This looks like it's actually an intended behavior of `ArgumentParser`: see [here](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_known_args). Will add something on your side to check the names are exact.

**Comment by stas00** [comment]
Oh, fantastic - thank you for finding that out, @sgugger 

This feature surely bit us yesterday.
