### ISSUE TITLE
Output probability from model.generate

### ISSUE THREAD

**Issue by tomdzh** [huggingface/transformers#9269]
# 🚀 Feature request

Do we have the option to output the probability of the generated sequence from model.generate function? It will be super useful for evaluating the confidence score of the generated sequence. Thanks so much!

**Comment by patil-suraj** [comment]
You'll have it soon 😉 , once #9150 is merged

**Comment by tomdzh** [comment]
> You'll have it soon 😉 , once #9150 is merged

That's awesome. Thanks!

**Comment by 205g0** [comment]
@patil-suraj great, it got merged but how does translates now to your question_generation repo? How do I get the output probability/confidence score to the the predicted answers?

**Comment by 205g0** [comment]
I only found this comment from you https://discuss.huggingface.co/t/text-generation-pipeline-output-scores-parameter/3294/2: 

*the text-generation pipeline doesn’t return scores, however you could the generate method directly, to get the scores, this should help*

Would be great if you could elaborate on that.

**Comment by gcuder** [comment]
@patil-suraj Any chance that `generate_tf_utils` will get the same functionality?
