### ISSUE TITLE
`do_wordpiece_only` argument

### ISSUE THREAD

**Issue by bkj** [huggingface/transformers#927]
A `do_wordpiece_only` argument is referenced [here](https://github.com/huggingface/pytorch-transformers/blob/fec76a481d1ecfbf068d87735dd44ffc26158f6e/pytorch_transformers/tokenization_bert.py#L97) -- does that argument actually exist?  I'm not able to find it in the repo anywhere.

Related, is this expected behavior?
```python
>>> tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', never_split=['[unused0]'])
>>> tokenizer.tokenize('[CLS] [unused0] this is a [SEP] test')
['[', 'cl', '##s', ']', '[unused0]', 'this', 'is', 'a', '[', 'sep', ']', 'test']
>>> 
>>> tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
>>> tokenizer.tokenize('[CLS] [unused0] this is a [SEP] test')
['[CLS]', '[', 'unused', '##0', ']', 'this', 'is', 'a', '[SEP]', 'test']
```

I want to be able to use the `[unused*]` tokens in `BertTokenizer`, but it seems like adding them to the `never_split` has some unexpected side effects.  Anyone have any ideas on how to set up the tokenizer to use the `[unused*]` tokens?  I'd prefer not to have to add the indices in a seperate step after the tokenization if possible.

__Edit:__ Seems like maybe you have to do
```
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', never_split=['[UNK]', '[SEP]', '[PAD]', '[CLS]', '[MASK]', '[unused0]'])
```
and then behavior makes more sense -- is that right?

Thanks!

**Comment by tks0123456789** [comment]
Use _additional_special_tokens_  instead.

```
>>> tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', additional_special_tokens=['[unused0]'])
>>> tokenizer.tokenize('[CLS] [unused0] this is a [SEP] test')
['[CLS]', '[unused0]', 'this', 'is', 'a', '[SEP]', 'test']
```
