### ISSUE TITLE
how can I change the AlbertModel's vocab

### ISSUE THREAD

**Issue by aLowMagic** [huggingface/transformers#9270]
# 🚀 Feature request

how can I change the AlbertModel's vocab
Thanks

## Motivation

I noticed that I can change the Bert's vocab by change the vocab.txt. But when I use the Albert's API, the document suggests:
tokenizer = AlbertTokenizer.from_pretrained('albert-base-v2'). So how can I change that.
Thanks

**Comment by patrickvonplaten** [comment]
This should help: https://github.com/huggingface/transformers/issues/1413#issuecomment-538083512

**Comment by aLowMagic** [comment]
Tanks a lot.
