### ISSUE TITLE
Disable progress bar for Trainer

### ISSUE THREAD

**Issue by Nickil21** [huggingface/transformers#9275]
I am referencing a similar code compared to [run_glue.py]
(https://github.com/huggingface/transformers/blob/master/examples/text-classification/run_glue.py).

I am running a preprocessing function that does the tokenization of text as well as `trainer.predict` on a pandas dataframe. How do I disable the progress bar from showing the progress made on each row of the dataframe? I thought it would work by disabling logging as well as `tqdm`, but it is not the case here. #3050

**Comment by sgugger** [comment]
If you set `disable_tqdm=False` in your `TrainingArguments`, you shouldn't have any progress bar from the library.

**Comment by Nickil21** [comment]
Well, I think you meant `disable_tqdm=True`. By the way, the following worked:

`args = TrainingArguments(disable_tqdm=True, output_dir="tmp_trainer")`

I am still getting progress bars for the `dataset.map()` though. Is there something like `verbose=False`?

**Comment by sgugger** [comment]
`dataset.map` comes from the Datasets library, not Transformers. So you should open an issue there for this part :-)
