### ISSUE TITLE
Vision Transformer

### ISSUE THREAD

**Issue by czabo** [huggingface/transformers#9276]
# 🌟 New model addition

## Model description

This issue is adding the Vision Transformer model described in the [An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale](https://arxiv.org/abs/2010.11929) paper. If you have any feedback and/or further ideas for the implementation please don't hesitate to mention them.

## Open source status

* [ x] the model implementation is available: 

[The official github repo](https://github.com/google-research/vision_transformer) provides the implementation in Jax/Flax.

* [x ] the model weights are available: 

See the github repo above.

* [ x] who are the authors: (mention them, if possible by @gh-username)

Google Research, Brain Team

**Comment by LysandreJik** [comment]
This was implemented in https://github.com/huggingface/transformers/pull/10950
