### ISSUE TITLE
ERNIE 2.0 ?

### ISSUE THREAD

**Issue by MuruganR96** [huggingface/transformers#928]
Latest NLP Language Model.:)

[ERNIE 2.0](https://arxiv.org/pdf/1907.12412.pdf?source=post_page)

**Comment by sangeet259** [comment]
This is relevant.
https://medium.com/syncedreview/baidus-ernie-2-0-beats-bert-and-xlnet-on-nlp-benchmarks-51a8c21aa433

**Comment by thomwolf** [comment]
We don't have any plan to add ERNIE in the short-term but if someone wants to do a (clean) PR with this model, happy to have a look and add it to the library.
