### ISSUE TITLE
TFRobertaModel warning  - `output_attentions`, `output_hidden_states` and `use_cache` cannot be updated

### ISSUE THREAD

**Issue by eyalshafran** [huggingface/transformers#9285]
I'm using:
google colab
transformers  4.1.1
tensorflow 2.4.0 (with gpu)
model TFRobertaModel

I keep getting a warning when calling TFRobertaModel. For example:
```
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
config = RobertaConfig.from_pretrained('roberta-base')
roberta_layer = TFRobertaModel(config)

max_seq_len = 64
ids = tf.keras.layers.Input((max_seq_len,), dtype=tf.int32)
att = tf.keras.layers.Input((max_seq_len,), dtype=tf.int32)
tok = tf.keras.layers.Input((max_seq_len,), dtype=tf.int32)

roberta_inputs = [ids, att, tok]

sequence_output = roberta_layer(ids,attention_mask=att,token_type_ids=tok) # this produces the message
```
Produces the following message:

The parameters `output_attentions`, `output_hidden_states` and `use_cache` cannot be updated when calling a model. They have to be set to True/False in the config object (i.e.: `config=XConfig.from_pretrained('name', output_attentions=True)`).
The parameter `return_dict` cannot be set in graph mode and will always be set to `True`.

I tried to set the variables in the config object but there is no change in the message:
```
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
config = RobertaConfig.from_pretrained('roberta-base',output_attentions=False,output_hidden_states=False,return_dict =True)
roberta_layer = TFRobertaModel(config)
```

@jplu, @LysandreJik

**Comment by jplu** [comment]
Hello!

These two messages are just a warning, you can ignore them if you are not concerned. Basically, these messages will always be displayed everytime the graph node is executed, and only in graph mode.

**Comment by Gilthans** [comment]
Is there a way to suppress these warnings? They overwhelm the logs with useless messages...

**Comment by jklaise** [comment]
@jplu the issue still persists, what is the purpose of these warnings? Why are they displayed to the user of the library?

**Comment by cakiki** [comment]
@jklaise The logging happens through a TF Logger (See [this line](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_tf_utils.py#L50)) .  

You can suppress them by using something like `tf.get_logger().setLevel('ERROR')`
