### ISSUE TITLE
SummarizationModule, Trainer and BertPreTrainedModel

### ISSUE THREAD

**Issue by ziqi-zhang** [huggingface/transformers#9287]
Hi,

I wonder what's the relationship between SummarizationModule (SummarizationDistiller), Trainer and BertPreTrainedModel? I want to reimplement the distillation.py of seq2seq example and run it on the glue dataset. But I'm confused by the relationship between these three classes. 

The model parameter of Trainer is BertPreTrainedModel and the Trainer train the model. But in the SummarizationDistiller there isn't a training function. I didn't find the training process in the distillation.py and finetune.py. Should I pass SummarizationDistiller object to Trainer to train the model? Or how should I train my custom SummarizationDistiller.

**Comment by patil-suraj** [comment]
Hi @ziqi-zhang,
the distillation code is written using the `pytorch-lightning` framework and `SummarizationModule` is a lightning module. You should go through the lightning docs to see how training works for lightning modules and how to customize it.

`Trainer` is transformers training helper which is different from lightning and there is no connection between the two.
