### ISSUE TITLE
comment correction in test_retrieval_rag.py?

### ISSUE THREAD

**Issue by zuujhyt** [huggingface/transformers#9306]
HI, in
https://github.com/huggingface/transformers/blob/master/tests/test_retrieval_rag.py#L223

comments of L223 and L224 are the same, maybe one of it should be "min inner product is reached with ...:
But I am not sure which one.
Pardon me if it is already correct.

**Comment by lhoestq** [comment]
Both comments are right.

```python
self.assertEqual(doc_dicts[0]["id"][0], "1")  # max inner product is reached with second doc
```
makes sure the first retrieved document of the first query is the second document of the corpus (it's the one that maximizes the inner product)

while
```python
self.assertEqual(doc_dicts[1]["id"][0], "0")  # max inner product is reached with first doc
```
makes sure that the first retrieved document of the second query is the first document of the corpus (it's the one that maximizes the inner product)

To be clearer the indices in those statements could be written as 
```python
query_idx = 0
retrieved_document_idx = 0
expected_id = "0"
self.assertEqual(doc_dicts[query_idx]["id"][retrieved_document_idx], expected_id)
```

**Comment by zuujhyt** [comment]
Thanks for your reply!
