### ISSUE TITLE
Entry-level demo of visual question answering

### ISSUE THREAD

**Issue by yezhengli-Mr9** [huggingface/transformers#9309]
## Environment info
Is there any entry-level demo of visual question answering？(I am also interested in adding title for each image later on) 
Better with `Trainer` added @sgugger. I follow the example from [Lxmert](https://huggingface.co/transformers/model_doc/lxmert.html).
```python
from transformers import LxmertTokenizer, LxmertModel
import torch

tokenizer = LxmertTokenizer.from_pretrained('unc-nlp/lxmert-base-uncased')
model = LxmertModel.from_pretrained('unc-nlp/lxmert-base-uncased')

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state
```
comes up 
```
File "/home/yezli/miniconda3/lib/python3.8/site-packages/transformers/models/lxmert/modeling_lxmert.py", line 933, in forward
    assert visual_feats is not None, "`visual_feats` cannot be `None`"
AssertionError: `visual_feats` cannot be `None` 
```
- `transformers` version:
- Platform: `Ubuntu 16.04.7 LTS`
- Python version: `Python 3.7.0`
- PyTorch version (GPU?): `No. But I am using PyTorch`
- Tensorflow version (GPU?): `No`
- Using GPU in script?: `No`
- Using distributed or parallel set-up in script?: `No`

### Who can help
@airsplay @bryant1410 Trainer @sgugger 

## Information

Model I am using (Bert, XLNet ...): `[Lxmert](https://huggingface.co/transformers/model_doc/lxmert.html)`

The problem arises when using:
* [v] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)
* [ ] 
Following example from [Lxmert](https://huggingface.co/transformers/model_doc/lxmert.html).
```python
from transformers import LxmertTokenizer, LxmertModel
import torch

tokenizer = LxmertTokenizer.from_pretrained('unc-nlp/lxmert-base-uncased')
model = LxmertModel.from_pretrained('unc-nlp/lxmert-base-uncased')

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state
```

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)
`Visual question answering` following example from [Lxmert](https://huggingface.co/transformers/model_doc/lxmert.html).

-- If you have code snippets, error messages, stack traces please provide them here as well.

```
File "/home/yezli/miniconda3/lib/python3.8/site-packages/transformers/models/lxmert/modeling_lxmert.py", line 933, in forward
    assert visual_feats is not None, "`visual_feats` cannot be `None`"
AssertionError: `visual_feats` cannot be `None` 
```

**Comment by patil-suraj** [comment]
Hi @yezhengli-Mr9  not sure what you are asking here,
by `Trainer` demo do you mean an example showing how to fine-tune `LXMERT`?

If you are looking for how to use `LXMERT` then this [demo notebook](https://colab.research.google.com/drive/18TyuMfZYlgQ_nXo-tr8LCnzUaoX0KS-h?usp=sharing) show's how to use LXMERT for visual QA

**Comment by yezhengli-Mr9** [comment]
> demo notebook

**Comment by yezhengli-Mr9** [comment]
> Hi @yezhengli-Mr9 not sure what you are asking here,
> by `Trainer` demo do you mean an example showing how to fine-tune `LXMERT`?
> 
> If you are looking for how to use `LXMERT` then this [demo notebook](https://colab.research.google.com/drive/18TyuMfZYlgQ_nXo-tr8LCnzUaoX0KS-h?usp=sharing) show's how to use LXMERT for visual QA

Hi @patil-suraj @patrickvonplaten , thanks a lot but [`examples/lxmert/`](https://github.com/huggingface/transformers/blob/master/examples/lxmert/) no longer exists although I am reconstructing some functionality since the [demo notebook](https://colab.research.google.com/drive/18TyuMfZYlgQ_nXo-tr8LCnzUaoX0KS-h?usp=sharing) seems quite instructive.
