### ISSUE TITLE
[model site] search UI: language: tags, directionality and filtering

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#9315]
I tried to use the models site to find which models I can use for translation of specific languages, and here are the issues I have encountered while doing that:

1. many HF created models aren't tagged for the languages they are trained for - e.g. t5: https://github.com/huggingface/transformers/issues/9314 - would it be possible to go over the HF-created main models and ensure they are clearly tagged with languages they were trained for? These get downloaded a lot, so putting a bit of metadata will go a long way of making user's life a bit easier.

2. the language tags presume bi-direction, but many models have been trained in one direction only - e.g. most wmt and most t5 models. Would it be helpful to support not just the language tags but also the directional language tags if they are one-way only?

   The t5 models are one direction only, so probably need one direction tags.  Not sure how that would work with Language tags in search UI. Perhaps it's enough to indicate that in README, but as the number of models grows being able to quickly filter what's needed will save a lot of user's time, so perhaps planning ahead would be useful. i.e. if I need to perform a FR to EN translation, the user may benefit from getting hits for only models that can do that.

3. wrt search UI - I don't understand how a handful of special language tags is selected - there are about a dozen of language tags in the search API dropdown, Malay is there when there are hardly any models trained on that language, but Russian which is 5th on the list of number of models is not there. 

   And those languages that are "favorite" aren't sorted... very strange. 

4. search UI 2: And to get to the language one wants which is not on the favorite list - one has to solve the puzzle:

   * select "See All languages", which goes to https://huggingface.co/languages 
   * hit on the list of models for that language, 
   * then filter by the model type by typing it in and then one has arrived.

   Surely, there must be an easier way to select a language filter that doesn't take 3 steps which aren't obvious at all
   
5.  Moreover if I want to select 2 languages that aren't on the favorite list, I'm out of luck, since it's not possible with the current API. It only works for the favorite list.

   And even if some of us know how to hack the URL and manually insert: https://huggingface.co/models?filter=ru,en - this is an OR operation, how do I do AND operation or I guess this is related to item 2 of this Issue - how do I filter by the to/from language.

All of these requests/questions are nice to have and none a showstopper. 

Thank you!
   
@julien-c

**Comment by julien-c** [comment]
cc'ing @gary149 and @beurkinger

**Comment by stas00** [comment]
Hmm, I just discovered I had 2 related issues opened some months back:
- https://github.com/huggingface/transformers/issues/8531
- https://github.com/huggingface/transformers/issues/7206
