### ISSUE TITLE
Conda dependencies conflict with pip dependencies

### ISSUE THREAD

**Issue by ZOUG** [huggingface/transformers#9322]
## Environment info

     
- `transformers` version: 3.5.1, 3.3.1
- Platform: Windows 10, Anaconda
- Python version: 3.8

## Information

I'm installing a package built on top of `transformers` v3 in an Anaconda environment. The package is not available on Anaconda Cloud so I have to install it via `pip`. According to [the best practice](https://www.anaconda.com/blog/using-pip-in-a-conda-environment), I try to install as many requirements as possible with `conda`, including `transformers`. However, it turns out that the conda dependencies conflict with pip dependencies for `transformers` so that pip would try to downgrade the conda-installed `tokenizers` package, which `transformers` depends on.

The dependency information is as follows:
<table style="width:100%">
  <tr>
    <th>`transformers` version</th>
    <th>conda dependency</th>
    <th>pip dependency</th>
  </tr>
  <tr>
    <td>3.5.1</td>
    <td>tokenizers==0.9.4</td>
    <td>tokenizers==0.9.3</td>
  </tr>
  <tr>
    <td>3.3.1</td>
    <td>tokenizers==0.9.3</td>
    <td>tokenizers==0.8.1rc2</td>
  </tr>
</table>

I can't seem to find any resolution other than leaving the `transformers` installation to pip completely. Is there any other possible resolution?

### Who can help
Maybe @mfuntowicz can help

## To reproduce

1. Run "conda install transformers=3.5.1" or "conda install transformers=3.3.1"
2. Run "pip check"

## Expected behavior

Make conda dependencies compatible with pip dependencies.

**Comment by patrickvonplaten** [comment]
Hey @ZOUG,

Thanks for the issue. @LysandreJik is on holiday at the moment, but I'm sure he's more than happy to take a look when he's back :-)

**Comment by LysandreJik** [comment]
Hello! We have started officially maintaining the anaconda packages in version v4.0.0. Installing a version anterior to that one would result in you using the `transformers` version from another channel (such as `conda-forge`), which we do not maintain.

Do you get the same error when installing `transformers` from our channel (on a more recent version)?

**Comment by ZOUG** [comment]
> Hello! We have started officially maintaining the anaconda packages in version v4.0.0. Installing a version anterior to that one would result in you using the `transformers` version from another channel (such as `conda-forge`), which we do not maintain.
> 
> Do you get the same error when installing `transformers` from our channel (on a more recent version)?

No, the error does not occur on the most recent version. The problem is that packages dependent on `transformers` may not be compatible with v4.x at the moment so that the error will still arise. It might be better to provide a pip installation package for v3.5.1 that is compatible with the anaconda dependencies.

In my case, I got lucky that the package that I need just released a new version today that is compatible with transformers v4.x.

**Comment by abedkhooli** [comment]
I believe this is still the case in Docker-based environments (ex. Kaggle). I removed existing transformers and tokenizers, installed new ones (transformers 4.2.1 and tokenizers 0.9.4). 
In the code, it goes back to conda and complains about tokenizers being 0.9.3
```
/opt/conda/lib/python3.7/site-packages/transformers/__init__.py in <module>
     41 
     42 # Check the dependencies satisfy the minimal versions required.
---> 43 from . import dependency_versions_check
     44 from .file_utils import (
     45     _BaseLazyModule,

/opt/conda/lib/python3.7/site-packages/transformers/dependency_versions_check.py in <module>
     39                 continue  # not required, check version only if installed
     40 
---> 41         require_version_core(deps[pkg])
     42     else:
     43         raise ValueError(f"can't find {pkg} in {deps.keys()}, check dependency_versions_table.py")

/opt/conda/lib/python3.7/site-packages/transformers/utils/versions.py in require_version_core(requirement)
     92     """ require_version wrapper which emits a core-specific hint on failure """
     93     hint = "Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git master"
---> 94     return require_version(requirement, hint)
     95 
     96 

/opt/conda/lib/python3.7/site-packages/transformers/utils/versions.py in require_version(requirement, hint)
     85     if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
     86         raise pkg_resources.VersionConflict(
---> 87             f"{requirement} is required for a normal functioning of this module, but found {pkg}=={got_ver}.{hint}"
     88         )
     89 

VersionConflict: tokenizers==0.9.4 is required for a normal functioning of this module, but found tokenizers==0.9.3.
```

**Comment by praveen1664** [comment]
Issue still persists

---------------------------------------------------------------------------
VersionConflict                           Traceback (most recent call last)
<ipython-input-24-3b738e6ed358> in <module>
----> 1 from transformers import PreTrainedTokenizerFast

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/site-packages/transformers-4.2.2-py3.8.egg/transformers/__init__.py in <module>
     41 
     42 # Check the dependencies satisfy the minimal versions required.
---> 43 from . import dependency_versions_check
     44 from .file_utils import (
     45     _BaseLazyModule,

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/site-packages/transformers-4.2.2-py3.8.egg/transformers/dependency_versions_check.py in <module>
     39                 continue  # not required, check version only if installed
     40 
---> 41         require_version_core(deps[pkg])
     42     else:
     43         raise ValueError(f"can't find {pkg} in {deps.keys()}, check dependency_versions_table.py")

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/site-packages/transformers-4.2.2-py3.8.egg/transformers/utils/versions.py in require_version_core(requirement)
     92     """ require_version wrapper which emits a core-specific hint on failure """
     93     hint = "Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git master"
---> 94     return require_version(requirement, hint)
     95 
     96 

/app1/anaconda3/envs/praveen_tfu/lib/python3.6/site-packages/transformers-4.2.2-py3.8.egg/transformers/utils/versions.py in require_version(requirement, hint)
     85     if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
     86         raise pkg_resources.VersionConflict(
---> 87             f"{requirement} is required for a normal functioning of this module, but found {pkg}=={got_ver}.{hint}"
     88         )
     89 

VersionConflict: tokenizers==0.9.4 is required for a normal functioning of this module, but found tokenizers==0.11.6.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git master
