### ISSUE TITLE
No module named 'transformers.modeling_albert'

### ISSUE THREAD

**Issue by hjzhang1018** [huggingface/transformers#9327]
- Platform: Colab
- Python version:
- PyTorch version (GPU?):GPU 
- Tensorflow version (GPU?):GPU
- Using GPU in script?:Yes

 examples/token-classification: @stefan-it
 -->

The problem arises when using:
* [ ] the official example scripts: I'm following the tutorial "23_Transfer_Learning_With_ChemBERTa_Transformers_Pt_2.ipynb" to reproduce the results. However I got this error message " No module named 'transformers.modeling_albert". I cannot figure out the reason. The following is the snippet I used:

```
!curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e
!pip install --pre deepchem 
import deepchem  
deepchem.__version__
from rdkit import Chem

!git clone https://github.com/NVIDIA/apex
!cd /content/apex
!pip install -v --no-cache-dir /content/apex
!pip install transformers
!pip install git+https://github.com/seyonechithrananda/simpletransformers.git@pip
!pip install wandb
!cd ..

!git clone https://github.com/seyonechithrananda/bert-loves-chemistry.git

%cd /content/bert-loves-chemistry

import os
import numpy as np
import pandas as pd
from typing import List
# import molnet loaders from deepchem
from deepchem.molnet import load_bbbp, load_clearance, load_clintox, load_delaney, load_hiv, load_qm7, load_tox21
from rdkit import Chem
# import MolNet dataloder from bert-loves-chemistry fork
from utils.molnet_dataloader import load_molnet_dataset, write_molnet_dataset_for_chemprop

tasks, (train_df, valid_df, test_df), transformers = load_molnet_dataset("clintox", tasks_wanted=None)

from simpletransformers.classification import ClassificationModel
import logging
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)
```
Any suggestions and help are appreciated! Thank you!

**Comment by patrickvonplaten** [comment]
Hey @hjzhang1018,

This does not seem to be a bug in Transformers, but rather in `seyonechithrananda/simpletransformers.git` so I'm not sure here is the correct place to post the issue. I think one has to change the line `from transformers.modeling_albert import ....` to `from transformers.models.albert.modeling_albert import ...` in the respective repo.
