### ISSUE TITLE
Training loss not getting logged

### ISSUE THREAD

**Issue by kunalpagarey** [huggingface/transformers#9359]
While training GPT2 using run_clm.py I wanted to track the training loss as well but could not find a way to do that with evaluation strategy = epoch. So I tried to look deeper into the code and found that may be adding `control.should_log = True` after line referred below will start logging training loss after every epoch. 
https://github.com/huggingface/transformers/blob/ae333d04b29a25be1a70eaccd6260c294c243c5b/src/transformers/trainer_callback.py#L422

Please correct me if I am wrong and suggest how should I track training loss per epoch?

Thanks in advance.

**Comment by LysandreJik** [comment]
@sgugger is the best suited to answer you

**Comment by sgugger** [comment]
This option is not implemented in Trainer.
