### ISSUE TITLE
[docs] TFRobertaModel example: last_hidden_states -> last_hidden_state

### ISSUE THREAD

**Issue by ck37** [huggingface/transformers#9376]
This is a documentation error on the currently deployed version of https://huggingface.co/transformers/

### Who can help

 examples/distillation: @VictorSanh
 documentation: @sgugger

## Information

Model I am using: TFRoberta

The problem arises when using:
* [x] the official example scripts

## To reproduce

1. View the code example at https://huggingface.co/transformers/model_doc/roberta.html#tfrobertamodel
2. `last_hidden_states = outputs.last_hidden_states` should be `last_hidden_states = outputs.last_hidden_state`

The current incorrect spelling will yield an error. I apologize that I was not able to find that line in the repo, otherwise I would submit a PR.

**Comment by julien-c** [comment]
looks like this is what you're looking for: https://github.com/huggingface/transformers/blob/ae333d04b29a25be1a70eaccd6260c294c243c5b/src/transformers/file_utils.py#L842-L855

**Comment by patrickvonplaten** [comment]
Hey @ck37,

Thanks for your issue! Yes, this typo should be corrected -> it would be great if you could open a PR :-)
