### ISSUE TITLE
Chinese BERT broken

### ISSUE THREAD

**Issue by Liangtaiwan** [huggingface/transformers#939]
There are still some bug after #860 
The same issue is also mention in #903

I'm running on Chinese-Style SQuAD dataset (DRCD).
I can train Chinese-Bert successfully about half year ago.
However, I could not train the model successfully but I can train Multi-Bert successfully.

I'm not able to find out the reasons.
@thomwolf I think there should be more test in this repo as the project is fast growing.

**Comment by thomwolf** [comment]
Yes you need to install from master for now. We have not yet done a new release with the fix of #860.

**Comment by stefan-it** [comment]
@thomwolf Not related to this specific issue here, but do you think it makes sense to add the following policy to the newly introduced issue templates: all bug reports should be filed against latest `master` version of PyTorch-Transformers (incl. pip install with git master url) 🤔
