### ISSUE TITLE
Why was DataCollatorForNextSentencePrediction removed ?

### ISSUE THREAD

**Issue by dwarfer7634** [huggingface/transformers#9416]
# 🚀 Feature request

I want to ask a question about why DataCollatorForNextSentencePrediction was removed.
That class was implement in the pull request down below.
https://github.com/huggingface/transformers/pull/6572
It was so useful for me.
But, this feature is not included in the latest version.
Do anyone know why it was removed?

Or, is there any alternative features?

## Motivation

I need NSP feature to cunduct complete pre-training.

**Comment by dwarfer7634** [comment]
Thank you for your quick reply. 
Do you mean you just have to use TextDatasetForNextSentencePrediction before DataCollatorForLanguageModeling to conduct NSP?

**Comment by sgugger** [comment]
Yes.
