### ISSUE TITLE
Is it possible to export a pytorch .pt file after finetuning a model?

### ISSUE THREAD

**Issue by farazk86** [huggingface/transformers#9426]
Hi,

Considering how I am having troubles with the tflite interpreter at issue https://github.com/huggingface/transformers/issues/9392 . I was wondering if I will have better luck trying Pytorch mobile, since the base models are pytorch to begin with.

But to use the pytorch converter I need the saved ``.pt`` file. The checkpoints saved during training are in ``.bin`` format. Is there any way to get the exported pytorch ``.pt`` file from a checkpoint folder? 

Thanks

**Comment by julien-c** [comment]
Just rename your `.bin` to `.pt`

**Comment by farazk86** [comment]
Hi @julien-c 

Sorry to come back to this but I am having trouble with this. As the .bin file also has a much larger accompanying ``optimizer`` file that I assume holds the weights.

I am trying to deploy a fine tuned model to google cloud. And even when using a custom prediction routine to load the entire folder for distil GPT2 the folder size exceeds the limit of ``500MB``.

Is there a way to export the fine tuned model to be used alone. Either export to a standalone pytorch model or tensorflow model.

I searched, but could not find any documentation on this. Would appreciate any help on this, or even direct me towards relevant documentation that can help me.

I'm using ``transformers==2.8.0``

Thank you

**Comment by LysandreJik** [comment]
The optimizer file does not contain the weights of your model, but the state of the optimizer during your training.

If you do not plan on continuing training, then you can safely discard that file. You can have more information about [optimizers here](https://pytorch.org/docs/stable/optim.html).
