### ISSUE TITLE
T5 base use a lot of memory to train on 

### ISSUE THREAD

**Issue by ghost** [huggingface/transformers#9430]
Hi
I am using transformers 3.5.1, t5-base uses a lot of memory I cannot even train it on 4 V100 GPUs with batch size of 32 could you elaborate is there is any memory issue with this model? thanks

**Comment by patil-suraj** [comment]
Hi @juliahane 
Could you post the training command ? 
batch size 32 is total batch size or `per_device_batch_size` ?

In my experiments I was able to use max 4 `per_device_batch_size` with `max_input_length` 512 and `max_target_length` 64.

Also, this kind of question should be asked on the[ forum ](https://discuss.huggingface.co/t/t5-finetuning-tips/684) as it's not a bug or issue.

[This](https://discuss.huggingface.co/t/t5-finetuning-tips/684) discussion might help.

**Comment by juliahane** [comment]
this is per device batch size. max_length = 128
to me this is a bug that the model requires this much memory
for small I can run the same thing with batch size =64

**Comment by juliahane** [comment]
coud you tell me if Adafactor save on memory?

**Comment by KennethEnevoldsen** [comment]
Hi @juliahane it is indeed the case that adafactor improves memory usage, which is why the original author uses it. You can check out the [paper](https://arxiv.org/abs/1804.04235) on adafactor for more info, but the abstract says the most. My intuition here is that adafactor (or similar memory-efficient optimizer) is required to train the large t5 models.

**Comment by juliahane** [comment]
thank you, very helpful, I will try it.

**Comment by juliahane** [comment]
In the thread they say to set autoscaling to off, do you know @kenneth  how
I can do it?
Apart from this, I could not find more suggestion for saving memory on GPU
in that thread
thanks

**Comment by KennethEnevoldsen** [comment]
I assume it is the:
```
scale_parameter (bool, optional, defaults to True) – If True, learning rate is scaled by root mean square
```
in the adafactor ([documentation](https://huggingface.co/transformers/main_classes/optimizer_schedules.html#adafactor-pytorch))

but maybe @patil-suraj could confirm this?

**Comment by KennethEnevoldsen** [comment]
For reference the optimizer I use is:
```
optimizer = transformers.Adafactor(model.parameters(), lr=0.001,
                                   relative_step=False, warmup_init=False, 
                                   decay_rate=0.0, clip_threshold=1.0)
scheduler = None
```
