### ISSUE TITLE
Rename `nlp` variables into more appropriate names

### ISSUE THREAD

**Issue by Narsil** [huggingface/transformers#9455]
# 🚀 Feature request

In `pipelines` tests and documentation they are recurringly named `nlp`, the goal is to rename them to something more appropriate.

## Motivation

```python
nlp = pipeline(task='conversational', model='XXX')
```
This is a bit pretentious as it does cover all NLP, and a better name help understanding to users too.
For instance the `conversational` task pipeline could be named `conversational_agent`. Or maybe still a generic name but less
pretentious `pipe`, `pipeline` (caveat: those are less clear in what they intend to achieve)

The goal is to rename all occurences of `nlp` by better names within both tests and the documentation.

## Your contribution

The better names could be discussed here.

**Comment by sgugger** [comment]
Thanks for creating the issue! Here are examples of what good names are in my humble opinion:
```
classifier = pipeline("sentiment-analysis")
unmasker = pipeline("fill-mask")
text_generator = pipeline("text-generation")
```
In short, something that describes the task it achieves.

**Comment by terrenceedmonds** [comment]
Hi guys, I'm new and I'd like to start helping out. Can I take over this request? And to clarify, you're referring to the references primarily in the /tests directory?

**Comment by Narsil** [comment]
Hi @terrenceedmonds , Thanks for taking this on ! 

Yes, for both directories, but docs are also found within docstrings within the `src/transformers/pipelines` directory.

**Comment by Soumyajain29** [comment]
Hii. Is this issue still open? I want to take this issue. Also, this will be my first contribution. Any help in getting me started will be highly appreciated.

**Comment by sgugger** [comment]
Let's see if @terrenceedmonds wants to to finish it first (the PR was almost ready to merge).

**Comment by 01-vyom** [comment]
Can I work on this issue, if @terrenceedmonds is not working on it?

**Comment by sgugger** [comment]
Yes, you can go ahead!
