### ISSUE TITLE
FileNotFoundError when instantiating RagRetriever

### ISSUE THREAD

**Issue by poccio** [huggingface/transformers#9463]
## Environment info

     
- `transformers` version: 4.1.1
- Platform: Linux-5.4.0-58-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.9
- PyTorch version (GPU?): 1.7.1 (True)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@patrickvonplaten, @lhoestq

## Information

I am trying to use RAG but I am having issues downloading the compressed index.

## To reproduce

```python
from transformers import RagRetriever
retriever = RagRetriever.from_pretrained('facebook/rag-sequence-nq', dataset='wiki_dpr', index_name='compressed')
```
Which results in:
```python
FileNotFoundError: Couldn't find file at https://storage.googleapis.com/huggingface-nlp/cache/datasets/wiki_dpr/psgs_w100.nq.compressed/0.0.0/psgs_w100.nq.IVF4096_HNSW128_PQ128-IP-train.faiss
```

**Comment by lhoestq** [comment]
Hi ! Can you try again ? I fixed the missing file

**Comment by poccio** [comment]
Thanks a lot! I'll try right away (with my internet speed, it should take ~1h30)

**Comment by poccio** [comment]
Yup, I can confirm now the issue is resolved. Thanks a lot! Shall I close the issue?

**Comment by patrickvonplaten** [comment]
Hey @poccio,

usually, always feel free to close issues that you opened. As maintainers, we don't always feel comfortable closing an issue since it's not always clear whether the author's issue is solved. So if it's solved for you, it's great if you close it :-) Thanks for reporting the issue.
