### ISSUE TITLE
Have RAG return generator cross-attentions when output_attentions=True

### ISSUE THREAD

**Issue by dblakely** [huggingface/transformers#9468]
# 🚀 Have RAG return generator cross-attentions when output_attentions=True

This feature request is for the RAG code to be modified so that if `output_attentions=True`, it returns the generator's cross-attentions in addition to the attentions it already returns.

## Motivation

I'm interested in extracting the generator's attentions from a RAG generator model. Currently, `transformers` allows you to extract the generator's encoder attentions and decoder attentions, but not it's cross attentions. For example, inside `modeling_rag.py`, the return objects such as [RetrievAugLMMarginOutput](https://github.com/huggingface/transformers/blob/master/src/transformers/models/rag/modeling_rag.py#L38), have fields for these other attentions, but not the cross-attentions.

Because both T5 and BART can output cross-attentions, I think they could simply propagate up through the RAG code. Is there a reason this isn't already the case? Or could I do a PR to include the cross attentions along with the other attentions in the model output?

## Your contribution

On my own fork of `transformers`, I've already added this feature and would happily submit a PR!

**Comment by dblakely** [comment]
@patrickvonplaten, @lhoestq Any feedback on this?

**Comment by lhoestq** [comment]
Feel free to open a PR indeed :) 
What do you think @patrickvonplaten ? I guess it can be part of the RetrievAugLMMarginOutput attributes.

**Comment by patrickvonplaten** [comment]
Hey @dblakely,

It would be great if you could open a PR. Both Bart and T5 already return the `cross_attentions`, so it should be a pretty easy change by just adding 

```python
generator_cross_attentions=gen_outputs.cross_attentions,
```
here:

https://github.com/huggingface/transformers/blob/fac7cfb16a437a97584f6a14c3856b2e06bf0eaa/src/transformers/models/rag/modeling_rag.py#L657

and then adding `generator_cross_attentions` to all output classes
