### ISSUE TITLE
request for run_text_classification.py

### ISSUE THREAD

**Issue by max-yue** [huggingface/transformers#9480]
# 🚀 Feature request

There is a run_tf_text_classification.py file under text_classification examples, but no run_text_classification.py.

**Comment by LysandreJik** [comment]
Hi! The `run_glue.py` script does what you're looking for.

**Comment by max-yue** [comment]
Let's say I have train.csv, dev.csv and test.csv, how can I do it without modify the code? Thank you for your patience.

**Comment by max-yue** [comment]
> Hi! The `run_glue.py` script does what you're looking for.

Let's say I have train.csv, dev.csv and test.csv, how can I do it without modify the code? Thank you for your patience.

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for questions around the script. Running it with the -h option will give you the list of arguments it accepts, in particular `--train_file` and `--validation_file`.
