### ISSUE TITLE
Question on the example script run_glue.py for text classification

### ISSUE THREAD

**Issue by xiaolin-cheng** [huggingface/transformers#9500]
When we run this script to train a text classification, are the weights of the underlying language model frozen and not updated? Whether they are fixed or trainable, is there any config to change the behavior of the training process? Thanks!

**Comment by patil-suraj** [comment]
hi @xiaolin-cheng 

`run_glue.py` fine-tunes the whole model, it doesn't freeze anything. You would need to manually freeze the base model, you could do this after loading the `ForSequenceClassification` and then freeze the base model. For example for `BertForSequenceClassification` you can access the base model using `model.bert`.
