### ISSUE TITLE
Model previews not working for models that require MecabTokenizer

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/transformers#9506]
As brought up [on Twitter](https://twitter.com/polm23/status/1348520920948695043) by user pol23 @polm, Japanese (and other?) models do not work at all on the model page. They will throw an error `You need to install fugashi to use MecabTokenizer.See https://pypi.org/project/fugashi/ for installation.` Perhaps the environment that these models run in should include all optional dependencies, too?

You can try it yourself by picking [a model](https://huggingface.co/daigo/bert-base-japanese-sentiment?text=I+likw+po) and trying the inference widget.

**Comment by julien-c** [comment]
Can we add those `pip install -e .[ja]` dependencies to the hosted Inference API @Narsil?

**Comment by BramVanroy** [comment]
@julien-c I'm not sure if that is possible, but perhaps this can even be derived from the model card? If a model card specifies Japanese, then the env could include the `[ja]` option.

**Comment by julien-c** [comment]
If I'm not mistaken all models run in the same env so it's probably not an issue to add a dependency, but I'll let @Narsil answer!

**Comment by Narsil** [comment]
Yes I created a patch for this, should be up soon.

**Comment by Narsil** [comment]
and up !

**Comment by polm** [comment]
Confirmed it works, thanks for the quick fix!
