### ISSUE TITLE
bug in distributed codes AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by ghost** [huggingface/transformers#9508]
Hi
I am using transformers 3.5.1, on distributed fashion on multiple gpus with pytorch 1.6 and python=3.7 
I am running:

python -m torch.distributed.launch  --nproc_per_node=1 --nnodes=2         --node_rank=1 --master_addr=$host --master_port=$port finetune_trainer.py config.json 

Huggingface codes only work wiht distributed fashion when all gpus are relying on one machine.
If user wants to run two copy of codes on two machines, since in the codes it decides based on local_rank not rank, the local_rank for bot copies would be zero. 

could you have a look please?
thanks

**Comment by juliahane** [comment]
could you confirm if this code has been tested at all on multiple gpu residing on multiple machines? 
I am getting various errors from memory .... seems the codes are not tested at all on multiple gpus, and only work for N gpus on 1 machine, could you please have a look, thanks

**Comment by juliahane** [comment]
huggingface set the rank based on local_rank which clearly makes a mess in distributed setup and this code would not work on multiple machines, could any one have a look?
