### ISSUE TITLE
config.json not found when loading fasttext-language-id model

### ISSUE THREAD

**Issue by nbeuchat** [huggingface/transformers#9510]
## Environment info

- `transformers` version: 4.1.1
- Platform: Linux-5.4.0-60-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.3.1 (True)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help
@julien-c 

## Information

Model I am using (Bert, XLNet ...): [julien-c/fasttext-language-id](https://huggingface.co/julien-c/fasttext-language-id)

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("julien-c/fasttext-language-id")
model = AutoModel.from_pretrained("julien-c/fasttext-language-id")
```

Which returns the following error:
```
404 Client Error: Not Found for url: https://huggingface.co/julien-c/fasttext-language-id/resolve/main/config.json
```

## Expected behavior
The model should load or the config file should be present

**Comment by julien-c** [comment]
Hi @nbeuchat this is a fasttext model, not a `transformers` model, so you can't load it that way.

I've updated the main button on the webpage to make it clearer that you need to use the model in fasttext:

<img width="1067" alt="Screenshot 2021-01-11 at 19 21 07" src="https://user-images.githubusercontent.com/326577/104222282-11d03600-5410-11eb-9b03-307fc776f197.png">
<img width="885" alt="Screenshot 2021-01-11 at 19 21 56" src="https://user-images.githubusercontent.com/326577/104222284-14329000-5410-11eb-842a-05fa8e05c1ca.png">

**Comment by julien-c** [comment]
Also cc'ing @thomwolf and @celebio <3

**Comment by nbeuchat** [comment]
Got it, thanks for the info and for the quick update!
