### ISSUE TITLE
Documentation's example script linked does no exist anymore

### ISSUE THREAD

**Issue by Skylixia** [huggingface/transformers#9523]
Hello,

I'm looking at the [documentation ](https://huggingface.co/transformers/v2.2.0/examples.html#abstractive-summarization) provided examples to be able to fine-tune a summarization task. It refers to the script run_summarization_finetuning.py but the link provided: https://github.com/huggingface/transformers/blob/master/examples/run_summarization_finetuning.py
returns a 404 error. 
Did the script migrate to another link ? Where can I find an example for the fine-tuning of a summarization task now ?

Thank you!

**Comment by lewtun** [comment]
Hello @Skylixia,

I believe the summarisation examples have been migrated to the `seq2seq` folder here: https://github.com/huggingface/transformers/tree/master/examples/seq2seq

In the README, you can find instructions on how to fine-tune a model for summarisation: https://github.com/huggingface/transformers/tree/master/examples/seq2seq#fine-tuning-using-seq2seqtrainer

HTH!
