### ISSUE TITLE
Print All Tokens Over a Certain Probability Threshold: T5 

### ISSUE THREAD

**Issue by zanderbush** [huggingface/transformers#9528]
`This works with GPT-2, but not with T5. Is it possible to adapt this to make T5 work? This works with GPT-2, but not with T5. Is it possible to adapt this to make T5 work?`

```
import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModelWithLMHead
tokenizer = AutoTokenizer.from_pretrained("t5-base")
model = AutoModelWithLMHead.from_pretrained("t5-base")
input_txt = "Hello, my name is Sylvain."
inputs = tokenizer(input_txt, return_tensors='pt')
outputs = model(**inputs)
predictions = F.softmax(outputs[0], dim=-1)
thresh = 1e-2
vocab_size = predictions.shape[-1]
idxs = torch.arange(0, vocab_size)[predictions[0][-1] >= thresh]
print(tokenizer.convert_ids_to_tokens(idxs))
```

`ValueError: You have to specify either decoder_inputs or decoder_inputs_embeds`

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Have you checked the [T5 docs](https://huggingface.co/transformers/model_doc/t5.html) regarding the `decoder_inputs`? Are they unclear?

Thanks!
