### ISSUE TITLE
Seq2Seq include custom glossary/dictionary

### ISSUE THREAD

**Issue by codingnoobneedshelp** [huggingface/transformers#9531]
Hello, 

Is it possible to include a custom glossary/dictionary while fine-tuning the Seq2Seq model for a specific domain?

So I basically want to ensure that specific words are always translated as they are in the glossary/dictionary. 

Thanks for helping out.

coodingnoobneedshelp

**Comment by patil-suraj** [comment]
Hi @codingnoobneedshelp 

Not sure what exactly this means,

What do you mean by

> custom glossary/dictionary

and 
> ensure that specific words are always translated as they are in the glossary/dictionary.

**Comment by codingnoobneedshelp** [comment]
Thanks for the answer. Let me try to clarify this. 
From Google:  A glossary is a custom dictionary to consistently translate the customer's domain-specific terminology. This typically involves specifying how to translate a named entity. 

For example, a Person name: "Peter Eisen" must translate to "Peter Eisen". There are some cases where the model would translate this to "Peter Iron". 

So I basically want just to have a dictionary that tells the model that "Peter Eisen" should always be "Peter Eisen".

Are aware of how I can archive that?

Thanks
