### ISSUE TITLE
Need clarification in /examples/research_projects/rag/use_own_knowledge_dataset.py

### ISSUE THREAD

**Issue by mayank31398** [huggingface/transformers#9534]
Please explain the difference between:
'facebook/dpr-ctx_encoder-single-nq-base' and 'facebook/dpr-ctx_encoder-multiset-base'

Which datasets are the 2 models trained on?

**Comment by LysandreJik** [comment]
Indeed, the models have no model card. Maybe @lhoestq can help you out!

**Comment by lhoestq** [comment]
Hi !
- 'facebook/dpr-ctx_encoder-single-nq-base' is the DPR context encoder model trained on NQ alone
- 'facebook/dpr-ctx_encoder-multiset-base' is the DPR context encoder model trained on the multiset/hybrid dataset defined in the paper. It includes Natural Questions, TriviaQA, WebQuestions and CuratedTREC

**Comment by mayank31398** [comment]
Thanks for clarifying @lhoestq
