### ISSUE TITLE
BertForTokenClassificiation save

### ISSUE THREAD

**Issue by Foysal87** [huggingface/transformers#9537]
How can I save the BertForTokenClassificiation model?

**Comment by NielsRogge** [comment]
You can save a model using the `.save_pretrained()` method. So given that your model is called `model`, you can save it as follows:

`model.save_pretrained(path_to_directory) `

**Comment by Foysal87** [comment]
Thank you for your reply.  I already tried it. But got an error like this.

```
'BertForTokenClassification' object has no attribute 'save_pretrained'
```

**Comment by NielsRogge** [comment]
Can you share some more code about how you created the model?

**Comment by Foysal87** [comment]
```
model = BertForTokenClassification.from_pretrained("bert-base-cased", num_labels=len(tag2idx))
```

after that fine-tuning it. Then want to save this model.

**Comment by Foysal87** [comment]
ok, I got it.. I can save it by torch.. thank you
