### ISSUE TITLE
Generating sequence from two input sequences

### ISSUE THREAD

**Issue by MiriamFarber** [huggingface/transformers#9543]
The code here

https://github.com/huggingface/transformers/blob/master/examples/seq2seq/finetune_trainer.py

enables training `distilbart-xsum-12-6` model that gets an input sequence and outputs an input sequence. Is there a simple way to adapt the code to enable it to get two input sequences (e.g sentence and context sentence) and output a sequence? 

It seems to me that I need to use something like that: https://huggingface.co/transformers/preprocessing.html#preprocessing-pairs-of-sentences, but wasn't sure how to combine it with the bart code.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead? You'll get more answers there.

Thanks!
