### ISSUE TITLE
Entity level F-1 scores in run_ner.py

### ISSUE THREAD

**Issue by pranav-s** [huggingface/transformers#9546]
# 🚀 Feature request

The run_ner.py script in examples/token_classification reports evaluation metrics in terms of token F-1 scores (from what I can tell by examining the code). This issue is to request entity level F-1 scores as an evaluation metric. Token level scores will evaluate the F-1 score over an input such as ["I", "work", "for", "ABC", "com", "##pany", "in", "New", "York", "City"] with the label for each token considered separately. In this example, if the ground truth labels are ["O", "O", "O", "ORG", "O", "O", "O", "GPE", "GPE", "GPE"] the label for "New" , "York" and "City" from the predictions would be compared against ground truth separately.  Entity level scores would mark a true positive if for instance all 3 tokens in the span "New York City" are labelled correctly.

## Motivation

Token level F-1 scores can be a more lenient metric compared to entity level scores since labels on sub-words/entities are considered separately.

## Contribution

I can also help implement this but I am not certain how I should get started with this. Any help is appreciated.

**Comment by sgugger** [comment]
Oh this makes me realize this script hasn't been switched to use the datasets metrics for seqeval. This would solve the issue as it computes all scores. Will do that tomorrow.

**Comment by pranav-s** [comment]
Thank you @sgugger
