### ISSUE TITLE
Dynamic padding + truncation in classification script

### ISSUE THREAD

**Issue by pashok3d** [huggingface/transformers#9551]
# 🚀 Feature request

## Motivation

@VictorSanh
@sgugger 

It seems that it is not possible to use dynamic padding along with truncation in classification script, because when `tokenizer` gets `max_length = None` it just skips truncation. 
https://github.com/huggingface/transformers/blob/063d8d27f4e1d089dc76f22e378b86b219167e3b/examples/text-classification/run_glue.py#L290

On the other hand, in language modeling script it works.
https://github.com/huggingface/transformers/blob/063d8d27f4e1d089dc76f22e378b86b219167e3b/examples/language-modeling/run_mlm.py#L311

**Comment by sgugger** [comment]
Yes, the `max_length` should be passed the same way. Would like to open a PR to fix `run_glue.py`?

**Comment by pashok3d** [comment]
Okay, I will do that.
