### ISSUE TITLE
SMITH Google

### ISSUE THREAD

**Issue by miketrimmel** [huggingface/transformers#9558]
# 🌟 New model addition

## https://github.com/google-research/google-research/tree/master/smith

* [x] the model implementation is available: (give details)
* [ ] the model weights are available: (give details)
* [ ] who are the authors: (mention them, if possible by @gh-username)

**Comment by NielsRogge** [comment]
This is a duplicate. See #9526

**Comment by miketrimmel** [comment]
Oh ok, thanks.
