### ISSUE TITLE
Pipeline - Truncation Keyword not Recognized  

### ISSUE THREAD

**Issue by CMobley7** [huggingface/transformers#9576]
## Environment info
- `transformers` version: 4.2.0
- Platform: Linux-5.4.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.7.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

and

- `transformers` version: 4.2.0
- Platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.29
- Python version: 3.8.5
- PyTorch version (GPU?): 1.7.1+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@Narsil @sgugger @LysandreJik

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

I tried to run both of the code snippets below and got the following error. The pipeline code looks like it should pass everything through correctly, but it doesn't. Maybe the __call__ function needs to be setup as it is in https://github.com/huggingface/transformers/blob/master/src/transformers/pipelines/text2text_generation.py#L59. 

```
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.tokenization_utils import TruncationStrategy

model = AutoModelForSequenceClassification.from_pretrained("/path/to/model/dir")
tokenizer = AutoTokenizer.from_pretrained("/path/to/model/dir")
nlp = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, return_all_scores=True, truncation=TruncationStrategy.LONGEST_FIRST)

results = nlp(narratives)
```

```
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.tokenization_utils import TruncationStrategy

kwargs = {}
kwargs["truncation"] = TruncationStrategy.LONGEST_FIRST
model = AutoModelForSequenceClassification.from_pretrained("/path/to/model/dir")
tokenizer = AutoTokenizer.from_pretrained("/path/to/model/dir")
nlp = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, return_all_scores=True, **kwargs)

results = nlp(narratives)
```

```
Traceback (most recent call last):
File "/ptce/evaluate.py", line 102, in <module>
    nlp = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, return_all_scores=True, truncation=TruncationStrategy.LONGEST_FIRST)
File "/usr/local/lib/python3.6/dist-packages/transformers/pipelines/__init__.py", line 418, in pipeline
    return task_class(model=model, tokenizer=tokenizer, modelcard=modelcard, framework=framework, task=task, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/transformers/pipelines/text_classification.py", line 39, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'truncation'
```

## Expected behavior

For `truncation` to pass from `super().__call__(*args, **kwargs)` to `__call__(self, *args, **kwargs)` and then to `_parse_and_tokenize(self, inputs, padding=True, add_special_tokens=True, truncation=TruncationStrategy.DO_NOT_TRUNCATE, **kwargs)` where the default value is overwritten and text longer than max_sequence_length narratives are truncated.

**Comment by sgugger** [comment]
The [documentation](https://huggingface.co/transformers/main_classes/pipelines.html#transformers.pipeline) of the pipeline function clearly shows the `truncation` argument is not accepted, so i'm not sure why you are filing this as a bug.

The `__call__` method of a class is not what is used when you create it but when you... well, call it. So `results = nlp(narratives, **kwargs)` will probably work better.

**Comment by CMobley7** [comment]
@sgugger , you're right. Thanks for the quick response. Sorry, while I looked at https://github.com/huggingface/transformers/pull/9432, I didn't look close enough at https://github.com/huggingface/transformers/blob/master/tests/test_pipelines_summarization.py#L78 or the updated docs. My apologies, it works now. Thanks @Narsil for adding this feature.
