### ISSUE TITLE
Some weights of XLMRobertaForMaskedLM were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized

### ISSUE THREAD

**Issue by Syavaprd** [huggingface/transformers#9579]
Where can I find weight that won't give the following error?
The code:
model = XLMRobertaForMaskedLM.from_pretrained('xlm-roberta-base')

**Comment by LysandreJik** [comment]
Could you put the full error in the description of the issue rather than in the title? We don't know which weights are not initialized.

**Comment by Syavaprd** [comment]
> Could you put the full error in the description of the issue rather than in the title? We don't know which weights are not initialized.
Code:
model = XLMRobertaForMaskedLM.from_pretrained('xlm-roberta-base')
Warning:
Some weights of XLMRobertaForMaskedLM were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['lm_head.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Comment by LysandreJik** [comment]
You don't need to worry about that message, it lets you know that the bias in the LM head is not initialized - it will be initialized to all zeros.

I'm removing this warning in #9615.
