### ISSUE TITLE
Custom mask when performing forward pass

### ISSUE THREAD

**Issue by hoangphuc1998** [huggingface/transformers#9583]
Suppose I have a sequence that consists of 2 sentences separated by \<\/SEP\> tokens like A \<\/SEP\> B. When performing forward pass with RoBERTa model, I want tokens in sentence A only attend to tokens in sentence A and vice versa for sentence B. The mask will be look like this:
![image](https://user-images.githubusercontent.com/24960238/104556288-e3ea2c00-5671-11eb-8dcd-1735761722b4.png)
In summary, is there any way to explicitly pass a custom attention mask to the model?

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
