### ISSUE TITLE
How to fine-tune T5/Bart for other languages on summarization?

### ISSUE THREAD

**Issue by HeroadZ** [huggingface/transformers#9587]
Assume that I have a Japanese dataset for fine-tuning. How could I fine-tune it? 
I think that the original tokenizer like `BartTokenizer` or `T5Tokenizer` can't be used for Japanese, right?
So is it possible to use a Japanese tokenizer like `BertJapaneseTokenizer` to fine-tune a Bart model? Please give me some advice. Thank you very much.

**Comment by LysandreJik** [comment]
Hi! The `BertJapaneseTokenizer` you mention was created specifically for Japanese, so it should encode the Japanese language well.

You can find the list of models that have Japanese checkpoints [here](https://huggingface.co/models?filter=ja).

**Comment by LysandreJik** [comment]
Tokenizers can be decoupled from their models, so you can indeed use a BERT tokenizer with a BART model; however, this requires the tokenizer and model to be trained together.

**Comment by HeroadZ** [comment]
Thanks for the quick reply! 
I don't know the exact procedure to train tokenizer and model **together**. Could you explain it in detail?
