### ISSUE TITLE
Order of inputs (difference between doc and output)

### ISSUE THREAD

**Issue by tide90** [huggingface/transformers#9595]
Hey,

when using a dictionary as model input does the order matters? Eg:

`model({"input_ids": input_ids, "token_type_ids": token_type_ids, "attention_mask": attention_mask})
`

and 

`model({"input_ids": input_ids, "attention_mask": attention_mask, "token_type_ids": token_type_ids})
`

When using tokenizer I get a order different from the docstring and arguments order:

```
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
input_query = tokenizer(input_query,max_length=MAX_SEQ_lEN,padding="max_length",truncation=True,return_tensors="tf")

-> {"input_ids": input_ids, "token_type_ids": token_type_ids, "attention_mask": attention_mask}
```

v3.4

**Comment by LysandreJik** [comment]
Hi! Order doesn’t matter in a dictionary. 

It only matters if you use the arguments as positional arguments, which is not recommended.

**Comment by tide90** [comment]
So, order does matter when using lists? What is now the right order?
