### ISSUE TITLE
saving the model during run_mlm

### ISSUE THREAD

**Issue by lkcao** [huggingface/transformers#9599]
Hi friends-
I am trying to train a Roberta on a large corpus with a server with time limitation.
Is there any way to save the model like every 3000 steps to keep record of the training, and resume it later?
Really need it with the project…Thanks for helping.

**Comment by sgugger** [comment]
Please avoid spamming the repository with multiple duplicate issues.
Also, those questions should go in the [forums](https://discuss.huggingface.co/), the issues are kept for bugs and feature requests only.

**Comment by lkcao** [comment]
sorry...I created two streams by mistake.
