### ISSUE TITLE
Mistake in the "Summary of the tasks" article

### ISSUE THREAD

**Issue by BunnyNoBugs** [huggingface/transformers#9604]
Two first points of the translation process are duplicating two first points of summarization process:
[https://huggingface.co/transformers/task_summary.html#translation](https://huggingface.co/transformers/task_summary.html#translation)

> 1. Instantiate a tokenizer and a model from the checkpoint name. Summarization is usually done using an encoder-decoder model, such as Bart or T5.
> 2. Define the article that should be summarized.

**Comment by LysandreJik** [comment]
Indeed! Do you want to open a PR with a doc fix?

**Comment by BunnyNoBugs** [comment]
I would like to, but I couldn't where that exact doc in the repo is

**Comment by BunnyNoBugs** [comment]
Also, a built-in tool for pointing out mistakes in the docs would be usable (like those when you highlight an error and press Ctrl+Enter). I notice a few mistakes from time to time

**Comment by BunnyNoBugs** [comment]
> Indeed! Do you want to open a PR with a doc fix?

@LysandreJik, could you please point out the doc I could fix?

**Comment by LysandreJik** [comment]
Here it is: https://github.com/huggingface/transformers/blob/master/docs/source/task_summary.rst
