### ISSUE TITLE
Convert ckpt from TFTrainer to huggingface format.

### ISSUE THREAD

**Issue by kiyoungkim1** [huggingface/transformers#9608]
I trained models with ```Trainer(pytorch)``` and ```TfTrainer(tensorflow)```, repectively.
With ```Trainer```, everything is ok. Saved models are directly applicable to huggingface pipeline (eg, AutoModel('model_name')).

But with save models from ```TFTrainer``` (ckpt format), I can not do that with ```AutoModel``` and ```TFAutoModel``` .
I can restart the training, so files do not have a problem.
I guess the problem is ckpt file all contains weight and other parameters related to optimizer.

How can I transform my ckpt file to huggingface-applicable format like ```tf_model.h5``` or convert to pytorch?

@jplu

**Comment by jplu** [comment]
Hello!

You have to use the `save_model` method of the trainer.

**Comment by kiyoungkim1** [comment]
ok. thanks!
