### ISSUE TITLE
Why do not use 'torch.nn.MultiheadAttention' to substitude 'Class BertSelfAttention+BertSelfOutput' for pytorch

### ISSUE THREAD

**Issue by daydayfun** [huggingface/transformers#9612]
# 📚 Migration

## Information
pytorch has 'torch.nn.MultiheadAttention' 
https://pytorch.org/docs/1.3.0/nn.html?highlight=multihead#torch.nn.MultiheadAttention

## Details
1. For Better performace and generality, I suggest to use  'torch.nn.MultiheadAttention'  instead of 'Class BertSelfAttention+BertSelfOutput'  in BERT model

**Comment by daydayfun** [comment]
'BertSelfAttention+BertSelfOutput'   is tensorflow style
'torch.nn.MultiheadAttention' is real pytorch style

**Comment by rabinadk1** [comment]
The layers from the Pytorch will be significantly faster than using the two classes like in TensorFlow. Can't we make an exception for pytorch to use the optimized layers?
