### ISSUE TITLE
Text generation pipeline - output_scores parameter

### ISSUE THREAD

**Issue by bala1802** [huggingface/transformers#9618]
In `text-generation` pipeline, I am looking for a parameter which calculates the confidence score of the generated text. Source: [here](https://huggingface.co/transformers/main_classes/pipelines.html#transformers.TextGenerationPipeline)

I am assuming that,  `output_scores` (from [here](https://huggingface.co/transformers/main_classes/configuration.html#transformers.PretrainedConfig)) parameter is not returned while prediction,

**Code**:

`predictedText = pipeline('text-generation',model=checkpoint_path, tokenizer=gpt2_tokenizer, config={'max_length':20, 'output_scores':True})`

`predictedText('This is a ')`

**Output**:

`Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[{'generated_text': 'This is a Generated Text'}]`

In the output, I am looking for a confidence score of the predicted text to be displayed

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
