### ISSUE TITLE
Passing in custom BartForConditionalGeneration model as generator to RagSequenceForGeneration

### ISSUE THREAD

**Issue by nitarakad** [huggingface/transformers#9627]
## Environment info

- `transformers` version: 4.2.1
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.7.0+cu101 (False)
- Tensorflow version (GPU?): 2.4.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@patrickvonplaten, @lhoestq

## Information

Model I am using:
`RagSequenceForGeneration` using pretrained  `facebook/rag-sequence-nq` with a custom generator initialized with `BartForConditionalGeneration`

The problem arises when using:
In the docs (https://huggingface.co/transformers/model_doc/rag.html) it is stated that a `generator` can be used when initializing `RagSequenceForGeneration`. When using a custom pretrained BART model as the `generator`, I get the error:

`ModuleAttributeError: 'BartForConditionalGeneration' object has no attribute 'to_dict'`

To troubleshoot, I initialized my generator using pretrained `facebook/bart-basee`  and RAG model the following way:
```
from transformers import RagTokenizer, RagRetriever, RagSequenceForGeneration, BartForConditionalGeneration
model_name = 'facebook/bart-base'
generator = BartForConditionalGeneration.from_pretrained(model_name)
tokenizer = RagTokenizer.from_pretrained("facebook/rag-sequence-nq") 
retriever = RagRetriever.from_pretrained("facebook/rag-sequence-nq", index_name="exact", use_dummy_dataset=True) 
model = RagSequenceForGeneration.from_pretrained("facebook/rag-sequence-nq", retriever=retriever, generator=generator) 
```

However, I get the same `ModuleAttributeError`.

The tasks I am working on is:
I want to initialize a `RagSequenceForGeneration` with a custom generator.

## To reproduce

1. Run the code block above and the error is outputted: `ModuleAttributeError: 'BartForConditionalGeneration' object has no attribute 'to_dict'`

## Expected behavior

Expected model to initialize with a custom generator, as described in the docs (https://huggingface.co/transformers/model_doc/rag.html).

**Comment by nitarakad** [comment]
solved.

**Comment by DapangLiu** [comment]
Could you provide a complete sample code about how to do it? I'm stuck at how to do the config initialization for a DPR + customized BartForCondGen. Thanks!
