### ISSUE TITLE
Issue with TrainingArguments docs.

### ISSUE THREAD

**Issue by gchhablani** [huggingface/transformers#9628]
Hi Team,

This is a minor issue but on this [link](https://huggingface.co/transformers/main_classes/trainer.html#transformers.TrainingArguments), the default optimizer mentioned is Adam in the docs. However, the `Trainer` uses AdamW by default.

This is slightly misleading.

Thanks,
Gunjan

**Comment by LysandreJik** [comment]
Hi! Do you want to open a PR to fix it? Thanks!
