### ISSUE TITLE
Multi-GPU inference with Tensorflow backend

### ISSUE THREAD

**Issue by fingoldo** [huggingface/transformers#9642]
Is this already supported maybe? I know that multi-GPU TRAINING is supported with TF* models pretty well. But not inference. What is the recommended way when one wants to do inference for a large batch of text (tens of millions rows)? Currently only one of GPUs gets loaded. Tensorflow have a [guide ](https://www.tensorflow.org/tutorials/distribute/save_and_load) on how to use model saved in the native tf format to do distributed inference under a scope:

```python
another_strategy = tf.distribute.MirroredStrategy()
with another_strategy.scope():
  loaded = tf.saved_model.load(saved_model_path)
  inference_func = loaded.signatures[DEFAULT_FUNCTION_KEY]

  dist_predict_dataset = another_strategy.experimental_distribute_dataset(
      predict_dataset)

  # Calling the function in a distributed manner
  for batch in dist_predict_dataset:
    another_strategy.run(inference_func,args=(batch,))
```
However, it seems that transformers do not support saving in this native format? At least TFDistilBertForSequenceClassification, when loaded back, has damaged input signatures (no attention_mask, wrong sequence length, fake None inputs) and can't process anything. And this very tracker is crowded with similar questions which are left unanswered. Can anyone shed some light on best approach to distributed inference please? Also adding a bullet on this to the documentation would be extremely helpful for many folks.

**Comment by jplu** [comment]
Hello!!

Can you please share the code you are using as for me it works as expected:
```python
from transformers import TFBertModel, BertTokenizer
import tensorflow as tf

first_strategy = tf.distribute.MirroredStrategy()

with first_strategy.scope():
	model = TFBertModel.from_pretrained("bert-base-cased")
	model.save_pretrained("my_model")

tokenizer = BertTokenizer.from_pretrained("bert-base-cased")
another_strategy = tf.distribute.OneDeviceStrategy("/cpu:0")

with another_strategy.scope():
  restored_keras_model_ds = TFBertModel.from_pretrained("my_model")

  inputs = tokenizer("Hello world.", return_tensors="tf")
  predict_dataset = tf.data.Dataset.from_tensor_slices(inputs).batch(1)
  dist_predict_dataset = another_strategy.experimental_distribute_dataset(predict_dataset)
  for batch in dist_predict_dataset:
  	another_strategy.run(restored_keras_model_ds, args=(batch,))
```

**Comment by fingoldo** [comment]
Thank you guys so much for the response! It was not obvious to use save_pretrained under the scope. Your example runs successfully, however on a 8 GPUs machine I observe (with bigh enough input list, of course) a weird pattern when maximum 2 GPUs are busy, and the rest are simply stale. Then after some seconds new pair of GPUs become active and rest are waiting. It happens no matter what strategy I try, MirroredStrategy or MultiWorkerMirroredStrategy. @jplu what strategy would you recommend to utilize all 8 GPUs?

**Comment by jplu** [comment]
This simply means that TF needs no more than 2 GPUs to run your inference.

**Comment by fingoldo** [comment]
But it's taking more than 40 seconds to run it. It definitely needs to utilize more ...

**Comment by jplu** [comment]
Tensorflow doesn't take the time as reference but the size. If your data can fit on 2 GPUs then it uses only 2. I suggest you to read this to better understand how it works. https://www.tensorflow.org/guide/gpu

**Comment by fingoldo** [comment]
> as reference but the size. If your data can fit on 2 GPUs then it uses only 2. I suggest you to rea
Following this link, I was not able to find any mentioning of when tf can select lower number of GPUs to run inference on, depending on data size. I tried with a million sentences and I'm still observing that pattern when only 2 GPUs are heavily loaded, and the rest has 0% utilization. and that pair of active GPUs changes randomly as the time goes. So something is definitely wrong with implementation. I was asking tf "please use all devices for this huge workload", and you are saying it just like "it can be done using 2 GPUs dude so i'm using 2, I don't care how long you gonna wait for the result" ? :-)

**Comment by fingoldo** [comment]
@jplu so if you know how to make it use all 8 GPUs in my particular case for 1 million of input sentences please advise, it would solve the issue completely.

**Comment by jplu** [comment]
Really sorry I don't know what to tell you more, if you have mostly TF related questions I suggest you to open an issue on the TF github repo.
