### ISSUE TITLE
Fail to convert the Funnel Transformer tensorflow version to transformer one when use the official script

### ISSUE THREAD

**Issue by RyanHuangNLP** [huggingface/transformers#9644]
## Environment info

- `transformers` version:3.5.1
- Platform:Centos
- Python version:3.7
- PyTorch version (GPU?):1.6.0
- Tensorflow version (GPU?):2.3.2
- Using GPU in script?:yes
- Using distributed or parallel set-up in script?:yes

## Information

Model I am using (Bert, XLNet ...):Funnel Transformer

## To reproduce

1.use the script `convert_funnel_original_tf_checkpoint_to_pytorch.py`@sgugger @LysandreJik
raise error
```
Traceback (most recent call last):
  File "run_pretraining.py", line 158, in <module>
    convert_tf_checkpoint_to_pytorch(args.tf_checkpoint_path, args.config_file, args.pytorch_dump_path)
  File "run_pretraining.py", line 40, in convert_tf_checkpoint_to_pytorch
    load_tf_weights_in_funnel(model, config, tf_checkpoint_path)
  File "run_pretraining.py", line 122, in load_tf_weights_in_funnel
    pointer = getattr(pointer, _layer_map[m_name])
  File "/root/miniconda3/envs/transformers/lib/python3.7/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'FunnelForPreTraining' object has no attribute 'embeddings'
```
2.
3.

**Comment by LysandreJik** [comment]
Hi! Could you explain the full procedure? Where did you obtain the Funnel transformer TensorFlow version? Is it a model you trained yourself using another framework? (like this one: https://github.com/laiguokun/Funnel-Transformer)

**Comment by RyanHuangNLP** [comment]
just use the official ones(like this one: https://github.com/laiguokun/Funnel-Transformer) @LysandreJik

**Comment by LysandreJik** [comment]
Could you provide the configuration you used, as well as which Funnel Transformer (which identifier? Is it the TensorFlow or the TensorFlow-Full) you tried to convert? Thank you

**Comment by RyanHuangNLP** [comment]
@LysandreJik I was train my funnel with the official code, I think my pretrain tensorflow is Tensorflow-Full with the adam weight. May be I need to transform my pretrain model to the TensorFlow or the TensorFlow-Full one first, then use the convert script to change to the transformer one?

**Comment by LysandreJik** [comment]
I see! Can you try the fix proposed in #9683 and let me know if it fixes your issue?
You can install it in your environment with:
```
pip install git+https://github.com/huggingface/transformers.git@convert_funnel
```

or if you have a clone of the repository, you can pull it and checkout the `convert_funnel` branch.

**Comment by RyanHuangNLP** [comment]
@LysandreJik Thanks for quickly reply. I will take a try.

**Comment by RyanHuangNLP** [comment]
@LysandreJik It has raise a new error

```
Skipping model/binary_loss/bias (1,)
Skipping model/binary_loss/weight (768,)
Skipping model/binary_proj/dense/bias (768,)
Skipping model/binary_proj/dense/kernel (768, 768)
6
Traceback (most recent call last):
  File "convert_tf_model.py", line 144, in <module>
    args.tf_checkpoint_path, args.config_file, args.pytorch_dump_path, args.base_model
  File "convert_tf_model.py", line 112, in convert_tf_checkpoint_to_pytorch
    load_tf_weights_in_funnel(model, config, tf_checkpoint_path)
  File "convert_tf_model.py", line 82, in load_tf_weights_in_funnel
    pointer = pointer.layers[layer_index]
  File "/root/miniconda3/envs/transformers/lib/python3.7/site-packages/torch/nn/modules/container.py", line 164, in __getitem__
    return self._modules[self._get_abs_string_index(idx)]
  File "/root/miniconda3/envs/transformers/lib/python3.7/site-packages/torch/nn/modules/container.py", line 154, in _get_abs_string_index
    raise IndexError('index {} is out of range'.format(idx))
IndexError: index 6 is out of range
```

**Comment by LysandreJik** [comment]
@sgugger do you have an idea of what might be going wrong?

**Comment by RyanHuangNLP** [comment]
@LysandreJik Which config file is using, I use the original full version tensorflow one `net_config.json`

```
{
    "block_size": "6_6_6",
    "d_embed": 768,
    "d_head": 64,
    "d_inner": 3072,
    "d_model": 768,
    "decoder_size": "2",
    "dropact": 0.0,
    "dropatt": 0.1,
    "dropout": 0.1,
    "ff_activation": "gelu",
    "init": "truncated_normal",
    "init_range": 0.1,
    "init_std": 0.02,
    "n_head": 12,
    "pool_q_only": true,
    "pooling_size": 2,
    "pooling_type": "mean",
    "rel_attn_type": "factorized",
    "separate_cls": true,
    "vocab_size": 21128
}
```

**Comment by sgugger** [comment]
No you need to convert your configuration first to a proper `FunnelConfig`, that is what the conversion script is expecting.

**Comment by RyanHuangNLP** [comment]
@sgugger Now the setting is the same, but still raise error, cannot convert the full tensorflow version to transformers ones

**Comment by sgugger** [comment]
Like I said before, it works for me. So without more information about the environment, the command you launch and the stack trace, there is really nothing we can do to help.

**Comment by NLP33** [comment]
> @LysandreJik Which config file is using, I use the original full version tensorflow one `net_config.json`
> 
> ```
> {
>     "block_size": "6_6_6",
>     "d_embed": 768,
>     "d_head": 64,
>     "d_inner": 3072,
>     "d_model": 768,
>     "decoder_size": "2",
>     "dropact": 0.0,
>     "dropatt": 0.1,
>     "dropout": 0.1,
>     "ff_activation": "gelu",
>     "init": "truncated_normal",
>     "init_range": 0.1,
>     "init_std": 0.02,
>     "n_head": 12,
>     "pool_q_only": true,
>     "pooling_size": 2,
>     "pooling_type": "mean",
>     "rel_attn_type": "factorized",
>     "separate_cls": true,
>     "vocab_size": 21128
> }
> ```

I got the same problem as you and I manage to convert the checkpoint by using the config file at the hugging face model hub. If  you use 6-6-6 block use this one https://huggingface.co/funnel-transformer/intermediate/raw/main/config.json and change vocab size.

**Comment by RyanHuangNLP** [comment]
@sgugger which version of transformers you use is work?

**Comment by RyanHuangNLP** [comment]
@sgugger @LysandreJik I think is the config file problem, I try @NLP33 advise fix the problem

**Comment by sgugger** [comment]
@RyanHuangNLP I have asked you before to give us the command your launch, the environment you use and a the content of the config file you are using. There is no point tagging me further on this issue with a vague message if you are not willing to share for those information as I cannot investigate a bug I cannot reproduce.
As I also said before and @NLP33 indicated, the script only supports config files corresponding to a config created by using `FunnelConfig` from transformers. It does not support the original config files from the original repo.
