### ISSUE TITLE
Does the latest huggingface-transformers version work with tokenizers==0.10.0?

### ISSUE THREAD

**Issue by unclebob7** [huggingface/transformers#9649]
## Environment info

- `transformers` version: 4.3.0.dev0
- `tokenizers` version: 0.10.0
![image](https://user-images.githubusercontent.com/29818505/104864385-c5d34300-5973-11eb-9e26-d804642e9331.png)

**Comment by LysandreJik** [comment]
Hello! We're [still pinned to 0.9.4](https://github.com/huggingface/transformers/blob/master/setup.py#L134). We'll pass to `0.10.0` soon.

**Comment by CMobley7** [comment]
@LysandreJik , if possible, could you provide your best guess as to when this requirement will be updated? I'm currently need to train a WordLevel Tokenizer, as well as use a transformer's model in the same process. I've broken the process up into two python files, which I run separately with different python environments, but it would be nice to have the full process in one file using one environment. Thanks!

**Comment by LysandreJik** [comment]
@n1t0 tells me it should be ready sometimes next week!.
