### ISSUE TITLE
Error w/Transformers 4.2.0 and TF Nightly

### ISSUE THREAD

**Issue by ANarayan** [huggingface/transformers#9650]
@jplu I am running into issues when running transformers w/tf-nightly. 

I get the error when I am trying to load the TFDistilBERT model:

`model = TFDistilBertModel.from_pretrained('distilbert-base-uncased')`

this is the error message:
```
ImportError: 
TFDistilBertModel requires the TensorFlow library but it was not found in your environment. Checkout the instructions on the
installation page: https://www.tensorflow.org/install and follow the ones that match your environment.
```

I came across this bug when running a CI test for Ludwig. I think many projects use tf-nightly in their CIs tests to make sure that the integrations are future proof!

**Comment by jplu** [comment]
Hello!

Please update to v4.2.1

**Comment by ANarayan** [comment]
This worked, thanks!
