### ISSUE TITLE
"Converting Tensorflow Checkpoints" document has wrong link in v4.2.0+

### ISSUE THREAD

**Issue by forest1988** [huggingface/transformers#9656]
## Environment info

- `transformers` version: v4.2.0+

### Who can help
 documentation: @sgugger

## Information

I'd like to convert BERT ckpt to PyTorch, and read [Converting Tensorflow Checkpoints](https://huggingface.co/transformers/converting_tensorflow_models.html) document.

It seems that the link to `convert_bert_original_tf_checkpoint_to_pytorch.py` is outdated.

It is linked to https://huggingface.co/transformers/converting_tensorflow_models.html, but `convert_bert_original_tf_checkpoint_to_pytorch.py` is now placed in https://github.com/huggingface/transformers/blob/master/src/transformers/models/bert/convert_bert_original_tf_checkpoint_to_pytorch.py (I found the information in https://github.com/huggingface/transformers/issues/9556).

It seems that in https://github.com/huggingface/transformers/pull/9217 the document is updated to use a prefix to get the `release` variable. 
However, perhaps the document is not yet changed to match the folder structure in v4?

Sorry if I misunderstand something.

**Comment by LysandreJik** [comment]
Hi! Indeed this link needs to be updated. Do you want to open a PR to fix it?

**Comment by forest1988** [comment]
@LysandreJik 
Thank you for your comment! I'd love to open a PR to fix it.
I would like to open a PR by the end of this week.

Should I devise a way to change the link destination from the document before and after the change in the folder structure (version 3 to 4)?

**Comment by forest1988** [comment]
Excuse me my opening a PR is delayed even though I said: "by the end of this week".

I haven't been able to find the time to do this, but your advice on another issue has helped me understand `convert` better, so I'm going to work on it.

I'll try to update the documentation on how to explain the differences between version 3 and 4, and I'd be happy to receive your comments in the PR (of course, any advice in advance would be greatly appreciated).

**Comment by forest1988** [comment]
I apologize for the delay in getting the work done later than I said it would be.
I opened PR #9791.
If you have time, I would appreciate it if you could take a look.

**Comment by LysandreJik** [comment]
Merged, thanks! No worries for the delay!

**Comment by forest1988** [comment]
@LysandreJik 
Thank you for merging and giving me your kind words!
