### ISSUE TITLE
Visualize self-attention for GLUE task

### ISSUE THREAD

**Issue by Nickil21** [huggingface/transformers#9679]
Is there a way to visualize the self-attention weights for different spans in a sentence, for instance, a sequence classification task inside [`run_glue.py`](https://github.com/huggingface/transformers/blob/master/examples/text-classification/run_glue.py)?

[See here for a sample](https://imgur.com/a/7gAJvCJ)

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
