### ISSUE TITLE
Generating sentence embeddings from pretrained transformers model

### ISSUE THREAD

**Issue by Prithvi103** [huggingface/transformers#9680]
Hi, I have a pretrained BERT based model hosted on huggingface. 
https://huggingface.co/microsoft/SportsBERT

How do I generate sentence vectors using this model? I have explored sentence bert but it doesn't allow you to use custom trained models. I have also seen Bert as a client. It works but for my current scenario, I was wondering if there's something which could be done without running a server for converting to vectors.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead?

Thanks!
