### ISSUE TITLE
[Open in Colab] links not working in examples/README.md

### ISSUE THREAD

**Issue by wilcoln** [huggingface/transformers#9688]
For the following tasks below, the ![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg) button contains github links instead of colab links.

- question-answering
- text-classification
- token-classification

@sgugger

**Comment by patil-suraj** [comment]
Hi @wilcoln 

Yes, the links point to Github, feel free to open a PR to replace the GitHub links with colab :). Thanks!
