### ISSUE TITLE
input one model's output to another one

### ISSUE THREAD

**Issue by omerarshad** [huggingface/transformers#9692]
Hello,

I want to create a model which generates text and the generated text is input to other model. So basically two models are trained together. How can i achieve this using hugging face?

Thanks

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead? You'll get more answers there!

Thanks!
