### ISSUE TITLE
WANDB_DISABLED env variable not working as expected

### ISSUE THREAD

**Issue by Wadaboa** [huggingface/transformers#9699]
## Environment info

- `transformers` version: 4.2.1
- Platform: Linux-5.4.34-1-pve-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.7.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

@sgugger

## Information

Model I am using (Bert, XLNet ...): Bert

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

I'm using modified scripts, but the error is related to a specific function in the `integrations.py` module, as explained below.

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: SQUaD
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Make sure that `wandb` is installed on your system and set the environment variable `WANDB_DISABLED` to "true", which should entirely disable `wandb` logging
2. Create an instance of the `Trainer` class
3. Observe that the Trainer always reports the error "WandbCallback requires wandb to be installed. Run `pip install wandb`."

## Expected behavior

I would have expected to disable `wandb`, but instead setting the `WANDB_DISABLED` environment variable completely prevents the user from using `wandb`.

After a bit of digging in the source code, I discovered that the `Trainer` uses the `WandbCallback` class (in `integrations.py`) to handle `wandb` logging. In that class, the `__init__` method has the following lines:

```python
has_wandb = is_wandb_available()
assert has_wandb, "WandbCallback requires wandb to be installed. Run `pip install wandb`."
```

In particular, by checking the `is_wandb_available()` function, we can see that it performs the following check:
```python
if os.getenv("WANDB_DISABLED"):
        return False
```

That if statement does not seem to be correct, since environment variables are stored as strings and the truth value of a string depends on whether it is empty or not. So, for example, by not setting the `WANDB_DISABLED` variable at all, then `wandb` would be enabled, but setting it to any value would entirely disable `wandb`.

**Comment by sgugger** [comment]
You're right, thanks for reporting! The PR mentioned above should fix that.
