### ISSUE TITLE
Trainer object empties dataset

### ISSUE THREAD

**Issue by AlexBella365** [huggingface/transformers#9748]
## Environment info
- `transformers` version: 4.2.2
- Platform: Linux-4.14.81.bm.20-amd64-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.7.0 (True)
- Tensorflow version (GPU?): 2.3.1 (True)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

## Information

Model I am using (Bert, XLNet ...): XLM-Roberta

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: NER
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Create a multilingual dataset by concatenating a handful of languages from wikiann
2. Instantiate the model
3. Instantiate the Trainer object

![image](https://user-images.githubusercontent.com/22292468/105478439-79ee0a00-5ca3-11eb-99f3-a648246187af.png)

## Expected behavior
The dataset object should not have been modified by the Trainer object

**Comment by sgugger** [comment]
Your dataset is not really emptied (I agree it looks like this however). It's just viewed without the columns the model can accept. You can restore all your columns with
```
dataset["train"].set_format(columns=list(dataset["train"].features.keys())
``` 
I agree that this is strange and we're seeing how we can have the same behavior without changing the dataset you pass to Trainer.

Note that you didn't preprocess your data, so you won't be able to train in this example.

**Comment by AlexBella365** [comment]
Hi Sylvain,
Thanks so much for prompt response.

I was not aware of this behaviour so was left very puzzled. I tried what you suggested and indeed got back all my data.

Yes, I agree with you, the data was not yet ready for training. I was just trying to pinpoint at which stage in my script the dataset became "empty".

Thanks again :)
