### ISSUE TITLE
Improve PyTorch examples for FP16

### ISSUE THREAD

**Issue by sgugger** [huggingface/transformers#9752]
To get the full speed-up of FP16 training, every tensor passed through the model should have all its dimensions be a multiple of 8. In the new PyTorch examples, when using dynamic padding, the tensors are padded to the length of the biggest sentence of the batch, but that number is not necessarily a multiple of 8.

The examples should be improved to pass along the option `pad_to_multiple_of=8` when `fp16` is True, if using a data collator that applies padding (or replace the `None` passed along to `Trainer` for `data_collator` by a `DataCollatorWithPadding(tokenizer, pad_to_multiple_of=8)`).

**Comment by dorost1234** [comment]
Hi @sgugger 
This is not done, although closed, please have a look into https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_mlm.py 
for line-by-line padding is not multiple of 8, thanks
