### ISSUE TITLE
Improve the `run_xlni` example to use the Datasets library

### ISSUE THREAD

**Issue by sgugger** [huggingface/transformers#9754]
The [`run_xlni`](https://github.com/huggingface/transformers/blob/master/examples/text-classification/run_xnli.py) example should be improved (following the model of [`run_glue`](https://github.com/huggingface/transformers/blob/master/examples/text-classification/run_glue.py)) to use the Datasets library to download and preprocess the datasets.

Ideally, copying the `run_glue` example and adapting the relevant parts should be the way to go.

**Comment by stefan-it** [comment]
Really good idea! I was looking at the `run_xnli` script the last days - because I wanted to test the "Language-Agnostic" models from [here](https://github.com/AIPHES/Language-Agnostic-Contextualized-Encoders) - and datasets integration would make experiments a lot more easier.
