### ISSUE TITLE
Add classes for Multi-label classification models? 

### ISSUE THREAD

**Issue by gsnidero** [huggingface/transformers#9772]
# 🚀 Feature request

It would be nice to add classes for Multi-label classification models to the library.

## Motivation

In my projects, I need to perform Multi-label classification. This problem setting is quite common in real-life modelling. 

## Your contribution

As there isn't a class implemented for this in the library, I have implemented my own. I have modified, for example, BertForSequenceClassificationton to make it usable for multi-label modelling. Then, I train the model with the Trainer class as usual.

Is there any interest or plan to add this from the library maintainers? If so, I would be happy to collaborate or start working on a PR.

Thanks

**Comment by RahulSChand** [comment]
Hi @LysandreJik is this feature request being worked on by someone? If not, I would love to take it up. Thanks!

**Comment by LysandreJik** [comment]
Hello! 

There is existing support for this thanks to the `problem_type` configuration attribute for some Sequence classification models, see here: https://huggingface.co/transformers/main_classes/configuration.html#transformers.PretrainedConfig

(search for `problem_type`)

It could be better documented though by having an example for each model that supports this/more complete documentation on the model themselves. Would you like to try your hand at it?

**Comment by astern21** [comment]
Hi,

It seems like the documentation for this feature has already been merged so I think this issue should be closed.

**Comment by LysandreJik** [comment]
Indeed! Thanks @astern21
