### ISSUE TITLE
RagRetriever question_hidden_states shape

### ISSUE THREAD

**Issue by aqweteddy** [huggingface/transformers#9773]
## Environment info

- `transformers` version: 4.2.2
- Platform: Linux-5.4.0-60-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.7
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): 2.3.0 (True)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?:no

### Who can help

 RAG: @patrickvonplaten, @lhoestq

## Information

The shape of RagRetriever's argument question_hidden_states mentioned in the document is `(batch_size, vector_size)`.
However, when RagModel calls self.retriever in forward function, it passes question_encoder_last_hidden_state`(batch_size, seq_len, vector_size)` to RagRetriever. Maybe question_encoder_last_hidden_state should be replaced with question_encoder_pooler_output?

The problem arises when using:
* [v] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [v] my own task or dataset: (give details below)

## Expected behavior

maybe a small bug?

**Comment by lhoestq** [comment]
I'm pretty sure it's just a bad naming of that variable. It should be question_encoder_pooler_output.

Indeed this variable is computed as the first output of a `DPRQuestionEncoder`. The DPR encoders don't return the hidden states (they basically skip it) to return the pooler output (aka DPR embeddings) of shape `(batch_size, vector_size)` instead.

If you want to contribute, feel free to open a PR to rename this variable :)
