### ISSUE TITLE
Link Not Working

### ISSUE THREAD

**Issue by akshat311** [huggingface/transformers#9778]
@patrickvonplaten 

I was looking at the MarianMT docs, and in the "Examples" section, the link for "Fine-Tune on GPU" and "Fine-Tune on GPU with pytorch-lightning" is broken.
Kindly look into this issue.

**Comment by patil-suraj** [comment]
Thanks for pointing it out, the files are now renames to `distil_marian_enro_teacher.sh`, `distil_marian_no_teacher.sh` and are available here 
https://github.com/huggingface/transformers/blob/master/examples/research_projects/seq2seq-distillation/distil_marian_enro_teacher.sh

https://github.com/huggingface/transformers/blob/master/examples/research_projects/seq2seq-distillation/distil_marian_no_teacher.sh

Feel free to open a PR to fix the links if you want to contribute :)

**Comment by akshat311** [comment]
Thanks a lot. Also, there a way to train the MarianMT model on my dataset ?

**Comment by patil-suraj** [comment]
Sure, the script let's you pass your own dataset as well, have a look at the readme.

**Comment by akshat311** [comment]
Thanks a lot for the help.
