### ISSUE TITLE
I want to train a BART model for conditional text generation. I want to train the encoder and the decoder separately for a specific task. Can anyone help with the code? I am new to this.  @patrickvonplaten

### ISSUE THREAD

**Issue by Sai-Ashish** [huggingface/transformers#9779]
@## Environment info

- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by patil-suraj** [comment]
Hi @Sai-Ashish 

Please use the forum https://discuss.huggingface.co/ for asking such questions. Use issues to report bugs, feature requests, etc. Thanks!

Closing it

**Comment by dinethnarada** [comment]
have you came up with solution?
