### ISSUE TITLE
Truncated Translations with mT5 model

### ISSUE THREAD

**Issue by sumanthd17** [huggingface/transformers#9786]
## Environment info

- `transformers` version: 4.2
- Platform: GCP
- Python version: 3.7
- PyTorch version (GPU?): 1.7
- Using GPU in script?: V100
- Using distributed or parallel set-up in script?: using pytorch-lightning `dp` setup

## Information

Model I am using (Bert, XLNet ...): I'm trying to fine-tune mT5 for neural machine translation. I trained the model on 3M data points with a `max_seq_len` of `200`. But when I perform `model.generate` I'm getting truncated outputs. 

The input sequence which I'm inferencing is not a very long input and no where close to 200 tokens.

The problem arises when using:
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] my own task or dataset: (give details below)

## To reproduce

I'm using my own dataset and training the model by wrapping the code around with pytorch-lightning.

I played around with the parameters in `generate` method but all combinations still endup giving truncated outputs

## Expected behaviour

An example output generated by the model 

Generated output:
`I hope that representatives from abroad will get some time to see Delhi's`

The quality of translation is good but the sentence ends abruptly.

Expected output: 
`I hope that delegates from abroad will have some time to see the history and pride of Delhi.` (generated with google translate)

@patrickvonplaten tagging you for help as this is a T5 related model

Thanks in Advance

**Comment by sumanthd17** [comment]
I've read these similar issue

[#5654](https://github.com/huggingface/transformers/issues/5656)
[#7500](https://github.com/huggingface/transformers/issues/7500)

but couldn't get the information needed.

@sshleifer @patil-suraj Any idea why this is happening? (Sorry for tagging everyone, I've been facing this issue for a while, looking for answers 🙂)

**Comment by FL33TW00D** [comment]
Hi @sumanthd17 ,
I had this issue with standard T5 in which it was ignoring the `min_length` flag. I fixed this simply by upping the `num_beams` to 4.

Could you test this and see if it's quick fix for you?

**Comment by sumanthd17** [comment]
@FL33TW00D Thanks. Yeah the `min_length` flag is being ignored. 

Thanks for the quick fix. I think we can close this issue for now, But it might be a good idea to know why the min_length is being ignored.

**Comment by FL33TW00D** [comment]
@sumanthd17 
This blog post from Patrick explains why min_length may not be satisfied by the beam_search:
https://huggingface.co/blog/how-to-generate

Although I do agree perhaps it should throw a warning message when it is unable to satisfy the min_length flag with the current generation parameters.
