### ISSUE TITLE
ImportError: cannot import name 'get_last_checkpoint'

### ISSUE THREAD

**Issue by yuxuan2015** [huggingface/transformers#9832]
from transformers.trainer_utils import get_last_checkpoint, is_main_process
ImportError: cannot import name 'get_last_checkpoint'

**Comment by patil-suraj** [comment]
HI there,

what's your transformers version ? `get_last_checkpoint` is available on master, so you should install from source to use it

**Comment by c-col** [comment]
hi @yuxuan2015 , the latest stable release of transformers (4.2.2) has no 'get_last_checkpoint' function, so if you installed via package manager you won't be able to use that function. like patil said, you need to install from source

**Comment by asifkhan2017** [comment]
@patil-suraj @c-col  i installed it from source but still getting the same error

**Comment by michael1017** [comment]
I solved this error after reinstalling transformers from pip. The version of transformers I installed is 4.3.3

**Comment by patil-suraj** [comment]
As mentioned in the `examples/readme.md` [here](https://github.com/huggingface/transformers/tree/master/examples#important-note), to run the examples, always install from source.

Closing this issue.
