### ISSUE TITLE
[docs] use `versionadded`, `versionchanged` and `deprecated` directive

### ISSUE THREAD

**Issue by ydcjeff** [huggingface/transformers#9836]
# 🚀 Feature request

## Documentation
Use `.. versionadded::`, `.. versionchanged::` and `.. deprecated::` directive, so that user knows which features are added / changed / deprecated in which version and they can navigate the docs easily without changing the docs from version to version.

Ref: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

## Motivation
To be able to know (without going to github) which features are introduced / changed / deprecated / improved in which version just from the docs.

Since `transfomers` is widely used in production, this slight change to the docs can help users see bird eye view for the features of the library.

Let me know what do you think

**Comment by LysandreJik** [comment]
Cool idea!
