### ISSUE TITLE
logging_epochs argument for TrainingArguments

### ISSUE THREAD

**Issue by hasansalimkanmaz** [huggingface/transformers#9838]
# 🚀 Feature request

There is no `logging_epochs` argument in `TrainingArguments`. When someone wants to train with `EvaluationStrategy.EPOCH`, he/she wants to see the logs after each epoch. Currently it is not possible. 

## Motivation

Better logging for training

## Your contribution

If I have time, I would like to add it. However, I am not available in a coming couple of weeks.

**Comment by tanmay17061** [comment]
Just like `evaluation_strategy` chooses between `'steps'` and `'epoch'`, to maintain consistency I think it is better to introduce either of:
1. a new enumeration `LoggingStrategy` with values
    1. `'epoch'` for per-epoch functionality
    2. `'steps'` functionality by falling back on `logging_steps`
2. a new bool argument `log_per_epoch` to decide between `epoch` or `steps` functionality and proceed similarly as above

@hasansalimkanmaz If you're still occupied, is it okay if I take a stab at this?

**Comment by hasansalimkanmaz** [comment]
Feel free to go ahead @tanmay17061 I am still busy with some other staff. Thanks for your interest.
