### ISSUE TITLE
Unable to read pre-trained model using BertModel.from_pretrained 

### ISSUE THREAD

**Issue by rshah1990** [huggingface/transformers#985]
I am using pre-trained BERT model kept at AWS s3 bucket. When i am trying to read the model using BertModel.from_pretrained  It return NONE object. Things are working offline when i download a folder on the same location as my code resides.

**Comment by LysandreJik** [comment]
Hi, you are trying to download one of your own models kept on a personal AWS s3 bucket or one of our models? What string do you pass to the `from_pretrained` method?

**Comment by rshah1990** [comment]
Thank you for your response, 
I am trying to use my own model kept on my personal AWS s3 bucket. 
The string to from_pretrained method is the path of folder which contains three files config , vocab and model. I have also tried to zip all files (.tar.gz) and use that file rather then folder but it also didn't work.
Please let me know in case you need more information.

**Comment by andrewpatterson2018** [comment]
Firstly, have you checked that the model in the bucket is reachable? 

Secondly, what is the name of the config file?

**Comment by rshah1990** [comment]
Yes its reachable, I can read vocab.txt file .
Name of config file is bert_config.json

**Comment by rhoef** [comment]
I do have the same (similar) problem, except that I use the pretrained models (e.g. bert-base-uncased"). The script repeatedly downloads the vocab, json and model file and often fails to load the model. Everything is works if I do it on the local machine. 

I also tried to download the files locally and unsuccessfully loaded the model directly. (tokenizer failed, model failed, BertConfig worked). Maybe I do something wrong here - example code would help
