### ISSUE TITLE
where is position_embedding_type used

### ISSUE THREAD

**Issue by awdrgyjilplij** [huggingface/transformers#9867]
When I was using pytorch Electra Model, I read its source code but I didn't find where position_embedding_type is used.
So did I miss something?

**Comment by LysandreJik** [comment]
It is used quite a lot! Here for example:

https://github.com/huggingface/transformers/blob/4c3ae89ad3215c3252ebf8ce964795ba8813d810/src/transformers/models/electra/modeling_electra.py#L194-L196

Actually just Ctrl+F "position_embedding_type" in this file and you should be able to find out where it's used :) (11 occurrences)

**Comment by awdrgyjilplij** [comment]
thanks
