### ISSUE TITLE
[DOCS] curl links go to 404 not found in NER tutorial

### ISSUE THREAD

**Issue by rakesh4real** [huggingface/transformers#9878]
Hey, in [NER tutorial](https://huggingface.co/transformers/v2.2.0/examples.html#named-entity-recognition) the curl commands seem outdated

```
curl -L 'https://sites.google.com/site/germeval2014ner/data/NER-de-train.tsv?attredirects=0&d=1' \
| grep -v "^#" | cut -f 2,3 | tr '\t' ' ' > train.txt.tmp
curl -L 'https://sites.google.com/site/germeval2014ner/data/NER-de-dev.tsv?attredirects=0&d=1' \
| grep -v "^#" | cut -f 2,3 | tr '\t' ' ' > dev.txt.tmp
curl -L 'https://sites.google.com/site/germeval2014ner/data/NER-de-test.tsv?attredirects=0&d=1' \
| grep -v "^#" | cut -f 2,3 | tr '\t' ' ' > test.txt.tmp
```

Can you please share new curl requests?

**Comment by patil-suraj** [comment]
the doc link you shared if for V2.2.0, we have updated all the examples in a recent version. You can find the new ner examples here https://github.com/huggingface/transformers/tree/master/examples/token-classification

**Comment by rakesh4real** [comment]
Thank you @patil-suraj
