### ISSUE TITLE
Finetune_Trainer Question

### ISSUE THREAD

**Issue by caincdiy** [huggingface/transformers#9885]
Hi, I'm new to HuggingFace. I want to fine-tune a BARTForConditionalGeneration model by finetunr_trainer.py for the translation task on google colab, but I didn't figure out how to use the script to fine-tune the model. Could anyone help me to show a quick example? Thanks

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discusss.huggingface.co) instead? You'll get more help there.

The docs regarding the maintained trainer are available [here](https://github.com/huggingface/transformers/tree/master/examples/seq2seq#new-script) and may be useful to you.
Thanks!

**Comment by caincdiy** [comment]
Oh sorry about that, Thank you very much
