### ISSUE TITLE
[Quick poll] Give your opinion on the future of 🤗 transformers: 40k edition!

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/transformers#9888]
Thanks to all of you, Transformers just passed 40k :star2:  this week!

Our libraries have always been about the community and we need your input to define the direction of the next 40k stars.

If you have a couple of minutes and want to participate in shaping the future of the library, please share your thoughts: https://forms.gle/FackvXzWJBWQz2WY8

(please reply in the above feedback form rather than to this thread)

Thank you all on behalf of the HuggingFace team! 🤗

**Comment by thomwolf** [comment]
Just did, thanks a lot @LysandreJik, the form is super quick to fill-in and interesting!
Everyone, we're waiting for you
