### ISSUE TITLE
Seeking clarification on T5  prefix for summarization

### ISSUE THREAD

**Issue by ari9dam** [huggingface/transformers#9892]
In the paper, I see the the prefix for summarization is "TL;DR:" . If I look into the model [config.json](https://huggingface.co/t5-base/blob/main/config.json)  of T5-Base, I see it is "summarization:".

"task_specific_params": {
    "summarization": {
      "early_stopping": true,
      "length_penalty": 2.0,
      "max_length": 200,
      "min_length": 30,
      "no_repeat_ngram_size": 3,
      "num_beams": 4,
      "prefix": "summarize: "
    },
  .....
 If I want to finetune Huggingface T5 for summarization, which prefix should I use?

Thank you

**Comment by patil-suraj** [comment]
Hi @ari9dam 
Please use the [forum](https://discuss.huggingface.co/) for such questions, and there's a discussion about this in the post 
https://discuss.huggingface.co/t/t5-finetuning-tips/684
