### ISSUE TITLE
ImportError: cannot import name 'PreTrainedEncoderDecoder' from 'transformers' (unknown location)

### ISSUE THREAD

**Issue by gianfilippo** [huggingface/transformers#9894]
Hi,

I am using the library to pretrain my model of choice. I am now interested in setting up an encoder-decoder architecture with my pretrained models, and  the "combiners" seems quite a straightforward way to do that.
Unfortunately, I am getting an import error on both "PreTrainedEncoderDecoder" and "Model2Model"
What am I missing ?
Thanks
Gianfilippo

## Environment info

- `transformers` version: 4.3.0.dev0
- Platform: Linux-3.10.0-1062.33.1.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.6
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: NA
- Using distributed or parallel set-up in script?: NA

## To reproduce
1.python -c "from transformers import PreTrainedEncoderDecoder"

ImportError: cannot import name 'PreTrainedEncoderDecoder' from 'transformers' (unknown location)

## Expected behavior

no error

**Comment by sgugger** [comment]
I'm not sure where you have seen those objects: they are nowhere in the transformers library. The library provides  `EncoderDecoderModel`, see the [encoder/decoder doc page](https://huggingface.co/transformers/model_doc/encoderdecoder.html).

**Comment by gianfilippo** [comment]
Hi, I was reading this  (https://medium.com/huggingface/encoder-decoders-in-transformers-a-hybrid-pre-trained-architecture-for-seq2seq-af4d7bf14bb8). I also found someone reporting some issue while using the same object here
https://github.com/huggingface/transformers/issues/2206.
Perhaps I am looking at some older version ?

**Comment by sgugger** [comment]
This is indeed from an older version (I guess 2 something or even 1 something).

**Comment by gianfilippo** [comment]
Thanks. I will look at the EncoderDecoderModel
