### ISSUE TITLE
Does Sortish Sampler work with multiple GPUs in seq2seq?

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#9899]
I am referring to the training script of run_seq2seq.py.  I am exactly referring to  [this line in seq2seq_trainer.py](https://github.com/huggingface/transformers/blob/1420b5ff675ccdc3296c6776b339a08a22d2e941/src/transformers/trainer_seq2seq.py#L48). So when should I enable **distributed** parameters and how should I do it?

**Comment by patil-suraj** [comment]
Currently `SortishSampler` will only work with the `finetune_trainer.py` scripts. It will be supported in `run_seq2seq.py` in the soon. And to answer your question, yes it works with multiple GPUs, and you won't need to enable distributer parameter if the training is launched on multi GPUs using `torch.distributed.launch`, it'll be enabled automatically.

**Comment by shamanez** [comment]
thanks a lot.
