### ISSUE TITLE
Missing model license information

### ISSUE THREAD

**Issue by guillaume-be** [huggingface/transformers#9901]
Hello,

A significant number of models uploaded to the model hub do not contain any license information. I wanted to check if your conditions set a default license under which models are uploaded when not specified?

In order to have a missing license added when it is missing, could you please advise on the standard way to proceed?
- Should an issue be created and tagging the author of the model asking for the license?
- Should I contact the author directly without raising an issue?

The community now has contributed a large number of very useful models, but more transparency regarding licensing (or default license) would be great.

Below are a few models I would be very interested in getting license information for, but a more general approach would be very beneficial:
- https://huggingface.co/valhalla/longformer-base-4096-finetuned-squadv1 (@patil-suraj )
- https://huggingface.co/mrm8488/longformer-base-4096-finetuned-squadv2 (@mrm8488 )
- https://huggingface.co/mrm8488/mobilebert-uncased-finetuned-squadv2 (@mrm8488 )
- https://huggingface.co/mrm8488/mobilebert-finetuned-ner (@mrm8488 )
- https://huggingface.co/mrm8488/mobilebert-finetuned-pos (@mrm8488 )

Thank you,

**Comment by LysandreJik** [comment]
Pinging @julien-c

**Comment by julien-c** [comment]
> I wanted to check if your conditions set a default license under which models are uploaded when not specified?

No, that's really the model author's call. But we will try to make it easier/more straightforward for a user to pick one in the future.

> In order to have a missing license added when it is missing, could you please advise on the standard way to proceed?

A GH issue is fine I think, otherwise a thread on [discuss.huggingface.co](https://discuss.huggingface.co) would work well too.

**Comment by guillaume-be** [comment]
Thank you for the clarification!

**Comment by vjixy** [comment]
If no license is available do we use the model for commercial use?
