### ISSUE TITLE
PPLM example - AttributeError issue

### ISSUE THREAD

**Issue by OlegDurandin** [huggingface/transformers#9902]
Hi all,
Thank you for great library.
Now I try to understand PPLM model (see reference https://eng.uber.com/pplm/ ), and when I try to start example from HuggingFace repository https://github.com/huggingface/transformers/tree/master/examples/research_projects/pplm (run_pplm.py) - I faced with the next issue:

```
Traceback (most recent call last):
  File "run_pplm.py", line 820, in <module>
    run_pplm_example(**vars(args))
  File "run_pplm.py", line 678, in run_pplm_example
    repetition_penalty=repetition_penalty,
  File "run_pplm.py", line 405, in full_text_generation
    repetition_penalty=repetition_penalty,
  File "run_pplm.py", line 511, in generate_text_pplm
    device=device,
  File "run_pplm.py", line 115, in perturb_past
    grad_accumulator = [(np.zeros(p.shape).astype("float32")) for p in past]
  File "run_pplm.py", line 115, in <listcomp>
    grad_accumulator = [(np.zeros(p.shape).astype("float32")) for p in past]
AttributeError: 'tuple' object has no attribute 'shape'

```
## Environment info

- `transformers` version:
- Platform: 4.3.0.dev0
- Python version: 3.8
- PyTorch version (GPU?): 1.7.1

I started this example on my own laptop and in Google Colab environment

## To reproduce

1. Follow to https://github.com/huggingface/transformers/tree/master/examples/research_projects/pplm and do Setup steps
2. Do command: `python run_pplm.py -B military --cond_text "The potato" --length 50 --gamma 1.5 --num_iterations 3 --num_samples 10 --stepsize 0.03 --window_length 5 --kl_scale 0.01 --gm_scale 0.99 --colorama --sample
`

## Expected behavior
This script should work without an error :)

**Comment by LysandreJik** [comment]
Hi! Could you install an earlier version of `transformers` to see if it works? I believe it was tested with `transformers==3.0.1`

**Comment by vspruyt** [comment]
It works fine up to and including version v4.2.2 but is broken in version above that
