### ISSUE TITLE
Tokenizer return offsets

### ISSUE THREAD

**Issue by borsork377** [huggingface/transformers#9904]
# 🚀 Feature request

Request for the feature raised in [Issue #1263](https://github.com/huggingface/transformers/issues/1263).

Previous PRs have attempted to address this but none of them were merged - https://github.com/huggingface/transformers/pull/1274 and https://github.com/huggingface/transformers/pull/2178.

## Motivation

Refer [Issue #1263](https://github.com/huggingface/transformers/issues/1263)

## Your contribution

Please guide me on how to submit a PR.

**Comment by sgugger** [comment]
All fast tokenizers have this feature, just pass along `return_offsets_mapping=True` in your call to the tokenizer. Also note that fast tokenizers are used by default when `AutoTokenizer` is called.
