### ISSUE TITLE
run_seq2seq.py : Why we pad labels with -100?

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#9909]
As mentioned in [this line](https://github.com/huggingface/transformers/blob/master/examples/seq2seq/run_seq2seq.py#L437), why we add -100. Can't we just keep pad_token_id ?

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for questions like this. We keep issues for bugs or feature requests only.
