### ISSUE TITLE
How to add more fields in TrainingArguments

### ISSUE THREAD

**Issue by RoderickGu** [huggingface/transformers#9912]
I am using ```from transformers import TrainingArguments```. However, there are more training arguments in my own project. How can I add more fields (parameters) in to the ```args```? Besides, if I have some other ```Arguments Class``` that is similar to ```TrainingArguments```, how to merge them into one ```args```?

**Comment by patil-suraj** [comment]
You could subclass the `TrainingArguments` class and add more fields to it. You could refer to `https://github.com/huggingface/transformers/blob/master/src/transformers/training_args_seq2seq.py` for an example https://github.com/huggingface/transformers/blob/master/src/transformers/training_args_seq2seq.py
