### ISSUE TITLE
prediction_step() is not using compute_loss()

### ISSUE THREAD

**Issue by hadifar** [huggingface/transformers#9915]
Hi @sgugger , I think there is an issue with `prediction_step` in `trainer.py`. The problem arises when implementing a custom loss function that requires reshaping input labels. In `training_step`, for loss calculation, it calls `compute_loss()` which is totally fine but in the `prediction_step` it calculates loss without `compute_loss()` function. This inconsistency causes some issues. Would you think it would be better to call `compute_loss()` in both cases in order to avoid this problem? 

Update: As I see the code, the loss is tightly coupled with `LabelSmoother` which makes it hard to do them in a single function. If you have any suggestion, it makes me happy to contribute to Huggingface ;)

[prediction_step()](https://huggingface.co/transformers/_modules/transformers/trainer.html#Trainer.prediction_step)

[training_step()](https://huggingface.co/transformers/_modules/transformers/trainer.html#Trainer.training_step)

**Comment by sgugger** [comment]
Mmmm probably. This is a bit tricky to make sure it doesn't break anything but makes more sense. I'll try to look at this on Monday.
