### ISSUE TITLE
Missing None verification in the CLM language modeling example

### ISSUE THREAD

**Issue by Aunsiels** [huggingface/transformers#9927]
Here: https://github.com/huggingface/transformers/blob/1682804ebd504d3381523116773583a52f35afd1/examples/language-modeling/run_clm.py#L230, data_args.train_file can be None (as it is checked some lines above). Therefore, there should be a check to see if it is the case or not.

**Comment by patil-suraj** [comment]
HI @Aunsiels you are right, thanks! Feel free to open PR to fix it :)

If `train_file` is `None` it should use `validation_file` to get the extension
