### ISSUE TITLE
trainer_seq2seq.py Question

### ISSUE THREAD

**Issue by caincdiy** [huggingface/transformers#9938]
Hi, does trainer_seq2seq.py in transformers/src support multi GPU training? Thank you

**Comment by patil-suraj** [comment]
Hi @caincdiy 

All the example scripts using `Trainer` or it's a subclass use `python -m torch.distributed.launch` to launch multi GPU training.  See https://github.com/huggingface/transformers/tree/master/examples#distributed-training-and-mixed-precision

Also the [forum](https://discuss.huggingface.co/) is the best place to ask such questions :)

**Comment by caincdiy** [comment]
Oh sorry. thank you very much for your help
