### ISSUE TITLE
Deepseep configs keys probelm

### ISSUE THREAD

**Issue by 7AM7** [huggingface/transformers#9962]
https://github.com/huggingface/transformers/blob/24881008a6743e958cc619133b8ee6994ed1cb8c/src/transformers/integrations.py#L288

I guess it should be `if len([x for x in bs_keys if x in config.keys()]) <= 0: ` or `if not len([x for x in bs_keys if x in config.keys()]) <= 0: `

**Comment by sgugger** [comment]
cc @stas00

**Comment by stas00** [comment]
Could you please explain what is the problem that you're encountering?

These keys **shouldn't be  in the config**, so len() will be > 0 if they are and then the assert happens, so I'm not sure why you're trying to reverse the logic.

```
config = {
    'train_batch_size': 1,
    "train_micro_batch_size_per_gpu": 1,
}
bs_keys = ["train_batch_size", "train_micro_batch_size_per_gpu"]
if len([x for x in bs_keys if x in config.keys()]):
    raise ValueError(
        f"Do not include {bs_keys} entries in the ds config file, as they will be set via --per_device_train_batch_size or its default"
    )
```
